### ISSUE TITLE
Cannot cancel Sales Invoice or Purchase Receipt -- Session or Lock Wait Timeout

### ISSUE THREAD

**Issue by cphoa28** [frappe/erpnext#10000]
Need much help.  Have a Sales Invoice with 6 items and Purchase Receipt with 20 items and cannot cancel either one.  I either have session timeout or lock wait timeout (which I researched on google that led me to Metadata locks??).  

Both entries are in the past, and for the Purchase Receipt there are tons of sales invoices generated subsequently from the 20 items.

Have increased innodb to 3GB no avail.  Running Oracle VM with 2 CPU and 4GB base memory on a Thinkpad T420 with Core I5 processor.

Please help!

**Comment by cphoa28** [comment]
forgot to add:

Installed Apps

ERPNext: v8.0.21 (master)

Frappe Framework: v8.0.32 (master)

**Comment by manassolanki** [comment]
Please update ERPNext and Frappe Framework. We have fixed this recently. If the issue still persists feel free to reopen.
