### ISSUE TITLE
Print to Pdf Throws up Blank Page

### ISSUE THREAD

**Issue by krishnanhemanth** [frappe/erpnext#10004]
Hi
I have an issue with printing to pdf
print to pdf throws blank
i edited the .json file and added 
"host_name":"http://localhost:8080",
still not able to print to pdf
i have not used a custom script
iam using a custom print format
the letter head is not showing on standard print formats

i have tried all iterations in the .json file like
"host_name":"http://localhost:8080",
"host_name":"http://myip",

Also tried this
cd ~/frappe-bench
bench set-url-root erpnext.erpnext-vm http://localhost:8080
the above command throws up the error shown below
![capture](https://user-images.githubusercontent.com/13927972/28445023-1b561ee4-6ddf-11e7-9cd0-1b398c21c658.PNG)

regards
hemanth

**Comment by manassolanki** [comment]
Hi @krishnanhemanth ,
Is this replicating everywhere in the site? Also, you can post help queries on discuss.erpnext.com.

**Comment by krishnanhemanth** [comment]
Hi manassolanki 
yes
this is replicating everywhere on the site
i am not able print any document in to pdf
its a fresh install what i have done
downloaded a fresh .ova file
atleast for the time being, any chance i can remove the path and timestamp thats getting printed on the print document
regards
hemanth

**Comment by umairsy** [comment]
Request you to post technical query on the ERPNext community forum.

https://discuss.erpnext.com
