### ISSUE TITLE
Give the option to define same delivery date on sales order

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#10003]
Hello,

Now that the delivery date is item wise on sales order, some users found that it is too difficult to put a delivery date on every item in huge sales orders. 

The solution I've found is to define a single delivery date on a custom field and loop trough items to fill the date on validation, but this could be a default option (the same way default warehouses work on some doctypes, and maybe deselecting a box like "same delivery date" the behavior could change to multiple delivery dates.

As a sugestion, a separation to autofill with periodicity (daily, weekly, monthly, etc.) like maintenance program work could spare some time filling the order.

**Comment by umairsy** [comment]
Hi,

You will be glad to know that we are already working the suggestion of Delivery Date on the parent level. Please track progress on the same from here.

https://github.com/frappe/erpnext/issues/10104
