### ISSUE TITLE
ios problem

### ISSUE THREAD

**Issue by ulasaktas** [frappe/erpnext#10018]
Hi, when I load erpnext to my iphone 6s, ıt is working at first time, after not working. Please, could you explain the problem?

**Comment by tundebabzy** [comment]
Hello @ulasaktas 
Thanks for reporting this. However, I'm closing this issue for now as we usually deal with these kinds of question on our forum: https://discuss.erpnext.com

You'll be able to get more attention there.

**Comment by giuseppelamatrice** [comment]
I have the same problem with iPhone 5, iOS 10.3.3

**Comment by krnkris** [comment]
Dear all!

Team working on it, let it happen ....
It takes some time.

https://discuss.erpnext.com/t/error-on-ios-apps-cant-acess-the-site/14477
