### ISSUE TITLE
[Security] Supplier Login

### ISSUE THREAD

**Issue by snvora** [frappe/erpnext#10011]
It is great but needs some more permissions management.

1. Supplier can access all RFQ's - even one that they have not been invited to.
![screenshot 3](https://user-images.githubusercontent.com/10496564/28455979-a46d9240-6e1e-11e7-8f84-d48c2e7beef6.jpeg)

2. He can access email and contacts and actually send email through default email account. 

![1](https://user-images.githubusercontent.com/10496564/28456316-8fcea116-6e1f-11e7-9b60-40d49656d81f.PNG)

![inkedpicture1_li](https://user-images.githubusercontent.com/10496564/28456294-7ecb071a-6e1f-11e7-81f5-58b86688b92b.jpg)

3. A supplier can know from whom else the quote is requested for one particular RFQ. This can unnecessarily jeopardise relationship with trusted suppliers.

Supplier portal is amazing and can reduce work burden to great extent. but Security comes first.

**Comment by umairsy** [comment]
Hello,

Ideally, the supplier should access the client's ERPNext account by using supplier portal, just like we have customer portal.

https://frappe.github.io/erpnext/user/videos/learn/request-for-quotation.html

The form views and permission are meant to be accessed by the users of the Company only, and hence not optimize for the use of other parties in the business (like Customer and Supplier). Rather, we have a completely separate view for them.

**Comment by snvora** [comment]
Hi Umair Sayed,

I am not sure if permissions management is right way to solve above issue. But the screenshots shared by me are from supplier portal only. He is able to access what he should not be allowed to view or access.

So it was meant to change internal permissions using code, to restrict information that is critical when shared with supplier using supplier portal like access to default email ,contacts, other suppliers that are invited to quote, etc.

**Comment by umairsy** [comment]
Hello,

The supplier portal doesn't have a desk access, like a website user. They are added as a Website Users and are able to access transactions where they are linked as a Contact.

https://youtu.be/q85GFvWfZGI?t=1m43s

Request you to refer to the above link once again which demonstrates the view from Supplier Portal.

**Comment by snvora** [comment]
Hi,

This video shows exactly how it is expected to work. 

But unfortunately supplier does have desk access. Setup --> User --> security settings --> show him has system user instead of website user.

Also I checked website page of supplier. It has a lot of bugs.
Like : -
List of RFQ should be filtered to only those he has access to.
Unable to access quotation or address.

![screenshot 1](https://user-images.githubusercontent.com/10496564/28869004-ed64e6dc-7798-11e7-8c16-8785034c70e0.jpeg)

Attached is screenshot where he is linked to only RFQ-2 but list showing both RFQ 1 & 2.
Also he has option to switch to desk. Infact on login - he has direct access to desk instead of website portal unlike what was shown in video.

Using 
ERPNext: v8.5.4 (master)
Frappe Framework: v8.5.7 (master)

**Comment by umairsy** [comment]
Hello,

Can you please mention what are the Roles assigned to this User? Ideally, it should be only Supplier, or no roles should be assigned at all.

**Comment by snvora** [comment]
yes. Role only supplier.

**Comment by netchampfaris** [comment]
I added a new User with the Role **Supplier**, and he only has Portal access. If for some reason your Supplier is shown as System User, then clear all roles and then add the Supplier role.

**Comment by snvora** [comment]
@netchampfaris 

Thanks for efforts. I looked back into my system. Desk access was enabled ( by default ) in our system for role supplier. after disabling that it worked out.

There are some other small request and bugs in supplier login i feel.

-  Error in title. as you can see in below image ( Similar error is seen in announcements )

![screenshot 2](https://user-images.githubusercontent.com/10496564/29762886-5ebab726-8bee-11e7-89a7-8fb668fe47c6.jpeg)

- Status of quotations, eg:- Quoted / Unquoted / Expired / Ordered etc would help supplier to choose which RFQ he should quote.

- Link below RFQ of quotation as seen in below image is not working.

![screenshot 3](https://user-images.githubusercontent.com/10496564/29763046-18aab76c-8bef-11e7-88d3-690af8f431c0.jpeg)

- Terms and conditions as mentioned in RFQ by us, should be visible on portal.

if you want to close this issue, and create new issue, I would gladly do that.

**Comment by tundebabzy** [comment]
Yes. Please open separate issues for each of the bugs/feature requests. I'm closing this for now
