### ISSUE TITLE
Multi-currency per account

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#1002]
- [x] Add Account Currency to Account & Party
- [x] Add Debit (in Alt Currency) and Credit (in Alt Currency) to GL Entry
- [x] [validation] Do not allow currency to change if any transaction has been made for both Party and Account
- [x] Currency input on creation of account from Chart of Accounts
- [x] In GL Entry posting, also post in alternate currency if party and account currencies are alt and match
- [x] Currency in Party and Account (Debtors) must match
- [x] In Journal Entry, on selection of account, select currency for the row.
- [x] In Journal Entry, Sales Invoice, Purchase Invoice post to default currency (DC) (based on exchange rate) and Account Currency (AC)
- [x] Fetch Exchange rate in Journal Entry based on average exchange_rate in case of inter-bank transfer, otherwise fetch current exchange rate
- [x] Currency in transactions must be either in party currency or company currency
- [x] All selected accounts in a transaction must be with transaction currency or in company currency
- [x] Invoice outstanding, advance amount in party account currency
- [x] Invoice paid amount and write off amount in both company currency and transaction currency
- [x] Patch for Outstanding, Paid, advance, write-off amount
- [x] Payment Tool in party currency
- [x] Accounting Currency in Customer / Supplier, patch for existing records
- [x] Force to mention Receivable / Payable account in Customer/Supplier, if party account currency is different from company currency
- [x] Show Receivable / Payable accounts, in accounting currency for customer/supplier and validate
- [x] Update "Advance Paid" in Order, based on party account currency, validate with grand total based on currency
- [x] Test Case
- [x] Patch
  - Set `currency` in Account, GL Entry, Journal Entry
  - Update `base_paid_amount`, `base_write_off_amount`, `party_account_currency` value in sales / purchase invoice
  - Update Exchange Rate, debit/credit in account currency in Journal Entry and GL Entry
  - Set Accounting Currency for party
  - Set party account if default currency of party other than company's default currency
- [x] Reports: Show Balance in account currency if filtered by account and account currency is different from company currency
  - General Ledger
  - Receivable
  - Payable
- [ ] Reports: Show all balances in company currency based on exchange rate as on filter
  - Trial Balance
  - Balance Sheet
  - P&L
  - Financial Analytics
- [x] Update manual
- [x] Add multi currency data in erpnext-demo
- [x] Set currency and exchange rate based on customer in Quotation while making from Opportunity
- [x] Set currency and exchange rate based on Supplier in Supplier Quotation / Purchase Order while making from Material Request

#### Inter-currency Conversion

<table>
<thead>
<tr><td>Account</td><td>Debit</td><td>Credit</td><td>Debit (Alt)</td><td>Credit (Alt)</td></tr>
</thead>
<tbody>
<tr><td>Paypal (USD)</td><td></td><td>6000</td><td></td><td>$100</td></tr>
<tr><td>Bank (INR)</td><td>6100</td><td></td><td></td><td></td></tr>
<tr><td>Exchange Gain / Loss (INR)</td><td></td><td>100</td><td></td><td></td></tr>
</tbody>
</table>

**Comment by aram-k** [comment]
+100

**Comment by devdesco-ceo** [comment]
Whats the safest way to update Grappe to 5.0 and ERP Next on top of it? My previous attempts failed with broken ERPNext instances :(

**Comment by bobzz-zone** [comment]
how this feature progress?

**Comment by anandpdoshi** [comment]
In development for v5.

**Comment by bobzz-zone** [comment]
when is the expected done time for this?....im really wait for it...

**Comment by ligthyear** [comment]
@nabinhait is that in 5.0 now? When is 5.0 supposed to be released? If it is not in 5.0, how much work do you believe it is? We might consider making a PR if that would be welcomed ...

**Comment by bobzz-zone** [comment]
when this will ready to use?.... im really love too see this, and really waiting for it

**Comment by nabinhait** [comment]
Will work on it soon. Have already completed all dependent ground work.

**Comment by abdur-rehman-pk** [comment]
when this feature will be added on erpnext verion 5

**Comment by bobzz-zone** [comment]
Hi, how is the news for this issue?.....thanks

**Comment by bobzz-zone** [comment]
i wonder how is it going ?

**Comment by bobzz-zone** [comment]
@abdur-rehman-pk , @ligthyear  , @aram-k , @devdesco-ceo to support this issues please place bounty on it.... i did myself already , here my thread on forum https://discuss.frappe.io/t/multi-currency-feature/6553

**Comment by rmehta** [comment]
@bobzz-zone we have started this project. Should be done by next week.

**Comment by bobzz-zone** [comment]
im really wait for the release..... if i may... can i pull to the current version?.... i really want to check how its gonna work

**Comment by nabinhait** [comment]
@bobzz-zone We have completed the major development. Now it is in testing phase, some final touch required. You can check https://github.com/nabinhait/erpnext/tree/multi-currency.

**Comment by sinaisix** [comment]
Great. We're patiently waiting.

**Comment by bobzz-zone** [comment]
@nabinhait i think in currency exchange for a date there should be 4 rates ,
1 for buying transaction
2 for selling transaction
3 for buying reports rate
4 for selling report rate
or you might just make 1 rate for the report its also fine , because if we just have 1 rates for all its not applicable , seeling and buying rates is ussually different and also transaction rates and report rates is different also

anyway i cant install the branch its showing error : 
_mysql_exceptions.OperationalError: (1054, "Unknown column 'reference_type' in 'field list'")

**Comment by nabinhait** [comment]
I didn't get your point. Can you please elaborate why there should be 4
different exchange rate?

**Comment by bobzz-zone** [comment]
@nabinhait we should have 4 or at least 3....
because....
like money exchanger we have sell rates and buy rates
but for reporting or counting our assets we should have report rates or it will be better if there is sell report rates and buy report rates..

did you get my point ?

**Comment by andiyan1** [comment]
Dear Team,

Thanks for the update on the currency system. i believe this is a very important feature erpnext should have. I am willing to sponsor for development. 

IMHO, for the currency rate i think it should be handled like stock item. we can value the currency based on FIFO or Moving average. so when we buy dollar or other currency, we can have 2 rate.

one is for buying rate, one another is for average buying rate. so we can expect to have currency gain or currency loss from the transaction.

Thanks and best regards

Anton

**Comment by bobzz-zone** [comment]
@nabinhait anyway if its possible please add currency date , so we can see the used currency history aswell

**Comment by jof2jc** [comment]
I think it's better to have option in feature setup to on/off multicurrency cause this feature is mostly needed by medium businesses. So others can just set it off when not using it to keep everything simple.

**Comment by bobzz-zone** [comment]
@nabinhait about what im suggesting... is that possible ?

**Comment by bobzz-zone** [comment]
and how about the currency exchange loss or profit?... because there should be a calculation for that

**Comment by bobzz-zone** [comment]
@nabinhait how is it ? ...

**Comment by nabinhait** [comment]
@bobzz-zone Almost completed...

**Comment by bobzz-zone** [comment]
@nabinhait i think the one at the git hub i cant manage to test it....i dont know where was the changed..... up tried to update but i cant see any logs for it... is the git not updated ?

**Comment by nabinhait** [comment]
I pushed it in my own repo https://github.com/nabinhait/erpnext/tree/multi-currency, will send a pull request today.

**Comment by bobzz-zone** [comment]
Yap, i did already git checkout -b multi-currency but there is no changes....
ill wait for the update today then.... thanks

**Comment by bobzz-zone** [comment]
@nabinhait is it merged already?....just updated but didnt see any changes

**Comment by sliska** [comment]
Something is off. I checked my account currency setting and are ok but my journal entry is not registering the currencies correctly. 

This account's currency is set to USD but it's not registering as such. Why might this be? 

thanks

![screen shot 2015-10-14 at 10 58 31 am](https://cloud.githubusercontent.com/assets/13278512/10491201/93160b94-7262-11e5-8d71-264dee84b01c.png)

![screen shot 2015-10-14 at 10 59 15 am](https://cloud.githubusercontent.com/assets/13278512/10491221/a6a11e9c-7262-11e5-8063-f661c11362d2.png)
