### ISSUE TITLE
stock balance screen/report  not fetch data 

### ISSUE THREAD

**Issue by schawale** [frappe/erpnext#10020]
![image](https://user-images.githubusercontent.com/8260698/28462970-845ddf2e-6e3b-11e7-9b5d-9240c9aed311.png)

**Comment by tundebabzy** [comment]
Hi @schawale 
Unfortunately I'm not able to reproduce this.

![screenshot from 2017-07-21 19-53-20](https://user-images.githubusercontent.com/818803/28478026-883e93a0-6e4e-11e7-8617-e3c1ae72b2b5.png)

erpnext 8.5.4
frappe 8.5.7

Please check if there are any errors on your browser console. Also, if this issue still persists, please open a new topic on our forum: https://discuss.erpnext.com where we'll be able to troubleshoot the problem.

**Comment by schawale** [comment]
there is no error in console
