### ISSUE TITLE
Incorrect company selected on quotations, sales orders etc...

### ISSUE THREAD

**Issue by francoisDeMan** [frappe/erpnext#10027]
Hi,
Can someone please assist with the following issue:
- 2 companies setup
- Customers are assigned to a company within their accounting section (Company and debtor account)
I would like this assigned company to be selected by default when creating a new quotation, sales order etc... This doesn't seem to work by default.
Could someone please assist?
Thanks in advance
Francois

**Comment by tundebabzy** [comment]
Hi @francoisDeMan 
We usually treat these kinds of questions on our forum: https://discuss.erpnext.com
