### ISSUE TITLE
[Report] Accounts Payable - Fields from journal Entry

### ISSUE THREAD

**Issue by snvora** [frappe/erpnext#10026]
Columns Bill no, Bill Date and Due date gets captured from Purchase Invoice in report accounts payable 

but not from Journal entry.

![inkedscreenshot 2 _li](https://user-images.githubusercontent.com/10496564/28489265-3e9cf7b6-6edd-11e7-840f-68df2dfc0c08.jpg)

**Comment by PawanMeh** [comment]
This is fixed in latest version

![bill_no_date](https://user-images.githubusercontent.com/20460498/47208014-5f34d880-d3aa-11e8-9c26-7fc546c021f5.png)
