### ISSUE TITLE
Employee Loan Should Be Limited To Employee Company

### ISSUE THREAD

**Issue by tundebabzy** [frappe/erpnext#10039]
![screenshot from 2017-07-23 23-54-16](https://user-images.githubusercontent.com/818803/28503671-171598a2-7003-11e7-8f72-e2f8018870fb.png)

![screenshot from 2017-07-23 23-56-09](https://user-images.githubusercontent.com/818803/28503673-18d5f1fa-7003-11e7-8724-9300253c980a.png)

It feels wrong that ERPNext gives the option for a Company to give an Employee Loan to an Employee not employed by the Company.

**Comment by umairsy** [comment]
Hi Tunde,

Should this not be handled by the System Manager by applying User Permission on the Company?

**Comment by tundebabzy** [comment]
Thinking about it now, the company field is useful but should be used to filter the employee drop down by default. This will improve the user experience for users that don't have limited permissions.  At the moment that doesn't happen. 

What do you think?
