### ISSUE TITLE
Journal Entry - Cost Center of default Company fetching always

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#10034]
https://discuss.erpnext.com/t/journal-entry-for-multiple-companies/26349

When creating Journal entry for non-default Company, the cost center selected is the default company instead of the selected one.

![screen shot 2017-07-23 at 11 07 19 am](https://user-images.githubusercontent.com/910238/28496938-1c32c542-6f97-11e7-8b0a-d41bf699d04b.png)

**Comment by Helkyd** [comment]
Thanks for creating.
