### ISSUE TITLE
How to add item code to an existing product that was created without item code (Or empty item code)

### ISSUE THREAD

**Issue by guilledd** [frappe/erpnext#10038]
Hi

I am currently testing ERPNext, and I added a few items with just name, and no item code.

How can I add item code after this?

For the products that already have an item code, I found that I can edit the code in
Stock -> item -> click on the name in the upper left hand part of the screen

However, for the items that have no item code, the only thing I can change is the "Full name", and I can not find a way to add an item code.

Please help

**Comment by tundebabzy** [comment]
Hi @guilledd
We usually answer these kinds of questions on our forum at https://discuss.erpnext.com
