### ISSUE TITLE
Different Products with different tax rates cannot be entered in Purchase receipt

### ISSUE THREAD

**Issue by shanmukhasai6** [frappe/erpnext#10031]
Unable to enter different products with different tax rates in purchase receipt

Tax and Charges is taking only single rate of tax for all the products entered

**Comment by umairsy** [comment]
Hello,

Please check the following help video to learn how to manage itemised taxation in the ERPNext.

https://www.youtube.com/watch?v=3oI1O5bedTo

https://frappe.github.io/erpnext/user/manual/en/accounts/item-wise-taxation
