### ISSUE TITLE
General Ledger Report - Print Report in Account Currency

### ISSUE THREAD

**Issue by mosabamf** [frappe/erpnext#10035]
This report is always used to reconcile accounts with our customers and suppliers, but unfortunately there two important issues missed:

1- Print GL Report in Account Currency when Account currency is **different** from Company Currency , It only printed out in Company Currency, "we tried to make customs report or amend current one but no permission to edit this report", 

2- Raw Balance after any transaction or JV

please it's urgent and so important

Thanks in Advance

**Comment by umairsy** [comment]
Hello,

@rohitwaghchaure for now, Print Format of General Ledger only captures values in the base currency of the company. Can we add one more print format of General Ledger with column where balance is shown in the Account's currency?

![screen shot 2017-07-24 at 10 57 43 am](https://user-images.githubusercontent.com/910238/28509304-f80f843e-705e-11e7-80df-5f468af71ffc.png)

@mosabamf can you please elaborate an issue with Balance shown in the report?

**Comment by mosabamf** [comment]
For the Print out, it's better to give some flexibility or access to edit as there're two cases:
1- When you make internal account reconciliation mostly you do need only company currency or both company and account currencies.
2- But when to need to reconcile the account with External party "Customer/Supplier" you ONLY need the GL statement in Account Currency, in this case Company base currency to be completely removed for print out report

**Comment by mosabamf** [comment]
Inline image 1



you need to add Balance Column (Opening Balance + Cr - Dr) i.e.

- Balance (row1)= Opening Balance + Cr - Dr.

- Balance (row2)= Balance (row1) + Cr - Dr.


Inline image 2

**Comment by addymuliady** [comment]
@mosabamf we are developing custom report for this.

Please do DM me.

**Comment by mosabamf** [comment]
Perfect, when do you expect to be released

**Comment by addymuliady** [comment]
It is in pipeline with current project though, might take probably a couple of months

@umairsy @rohitwaghchaure

**Comment by mosabamf** [comment]
Ok

**Comment by rohitwaghchaure** [comment]
Hi @mosabamf 

We are working on the issue and by this week we'll release the fix

**Comment by mosabamf** [comment]
Perfect , that will be great

**Comment by mosabamf** [comment]
Hi @rohitwaghchaure 

Any update?

**Comment by mosabamf** [comment]
Hi Gents
Any Update?

**Comment by rakesh1230** [comment]
when i use the same html of general ledger and add the path of html file in frappe.render_template it gave an error like tag name was expected.

**Comment by rakesh1230** [comment]
Can't I use the General Ledger HTML in the frappe api whitelisted method?
