### ISSUE TITLE
Navbar breaking on smaller devices

### ISSUE THREAD

**Issue by ishanloya** [frappe/erpnext#10041]
On smaller devices (tested on iPhone 5s), the navbar breaks onto the next line covering the title and action buttons.

![image1](https://user-images.githubusercontent.com/17540310/28508256-5ca38966-7057-11e7-94f2-d9a4b8e497dd.PNG)

**Comment by krnkris** [comment]
Parallel for this 
on devices (Iphone 6) can't choose on EMAIL navbar the outgoing box.
May this subject cause the behaviour.
