### ISSUE TITLE
Number of backups value not used

### ISSUE THREAD

**Issue by krnkris** [frappe/erpnext#10052]
As of:

https://discuss.erpnext.com/t/number-of-backups-value-not-used/26379?u=krnkris

**Comment by saurabh6790** [comment]
@krnkris  Not able to reproduce the issue.

<img width="768" alt="screen shot 2017-08-02 at 12 55 12 pm" src="https://user-images.githubusercontent.com/3784093/28862228-ea8ac402-7781-11e7-988f-d5d9096f838a.png">

<img width="693" alt="screen shot 2017-08-02 at 12 55 18 pm" src="https://user-images.githubusercontent.com/3784093/28862230-ebdb1f5a-7781-11e7-8a86-2a33cd6719fd.png">

---
Are you still facing this issue?

**Comment by krnkris** [comment]
@saurabh6790 
Yes I have set Number of Backups to 10.
I have only two (2) backups. One from today the second one from yesterday.

2017-08-01 11:05 | /backups/20170801_110534_bed8d350_database.sql.gz | 20.7M
-- | -- | --
2017-07-31 15:33 | /backups/20170731_153329_72c73fcb_database.sql.gz | 20.6M

VM instance

Installed Apps

ERPNext: v8.6.5 (master)

Frappe Framework: v8.6.4 (master)

**Comment by krnkris** [comment]
@saurabh6790 

Furthermore just received the info email about the new backup.

It shows again only two (2) backups instead of ten (10):


2017-08-02 10:27 | /backups/20170802_102752_3a35cfef_database.sql.gz | 20.8M
-- | -- | --
2017-08-01 11:05 | /backups/20170801_110534_bed8d350_database.sql.gz | 20.7M

**Comment by saurabh6790** [comment]
@krnkris  Are you on erpnext cloud or using erpnext VM?

**Comment by lasalesi** [comment]
We still have the issue on all installations (not erpnext cloud, virtual servers)

    ERPNext: v8.7.0 (master)
    Frappe Framework: v8.6.6 (master)

Number of backups: 20
Actual backups: 2
The two available backups are moving every day, so new backups are created, but >2 is removed.

**Comment by krnkris** [comment]
@saurabh6790

 Using:  Erpnext VM

**Comment by krnkris** [comment]
Do this happen if user do 
a
bench update?

I mean after bench update the backups goes back to 
two (2) instances and all others are cleared out?

**Comment by krnkris** [comment]
@saurabh6790  Appreciate your support.

Yes this is the case!

If you do a 
bench update --upgrade

it reverts all backups to the last two (2) instance.

Please close this issue.

**Comment by lasalesi** [comment]
@krnkris I am confused, how is it resolved now? 

We were able to have more than 2 backups when explicitly setting the value and then making more backups.

Does this mean after each "bench update" the setting has to be set anew? In that case, this would be a bug in "bench update", right?

**Comment by krnkris** [comment]
@lasalesi
Exactly, if you do 
bench update
it reverts to two backups.
I don't know if it is normal behaviour or not,
but it does in this way.

**Comment by lasalesi** [comment]
@krnkris thanks for the feedback.
I believe this is still an error as after the update then the setting as in the system does not correspond to the number of available backups.

**Comment by krnkris** [comment]
@lasalesi 
Did you checked the numbering?
I don't see it set back to two.
Bench update does clear the ammount of backups,
but not set back the already set backup number.
