### ISSUE TITLE
New Item will not save....

### ISSUE THREAD

**Issue by opsninja1** [frappe/erpnext#10065]
I am getting weird responses to Awesome Bar queries.

![test1](https://user-images.githubusercontent.com/21339160/28540125-c8d12c98-7079-11e7-9dca-89fd46639fcf.gif)

**Comment by tundebabzy** [comment]
Hi @opsninja1 
What error is in the console?

**Comment by opsninja1** [comment]
It is fixed.

Rick Oster
VP of Operations
Kole Digital Systems
815-469-2000 x104
rick@koledigital.com<mailto:rick@koledigital.com>

On Jul 24, 2017, at 6:29 PM, tundebabzy <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @opsninja1<https://github.com/opsninja1>
What error is in the console?
