### ISSUE TITLE
Google Analytics tracking duration of users online when using website

### ISSUE THREAD

**Issue by lxnow** [frappe/erpnext#1007]
When the website is enabled and tracked via Google Analytics, Analytics is counting the time logged in by erpnext backend users. This spikes up the metrics artificially on the duration a user is on the site. I validated this when the average duration per user drops from 1-2 hours per day to a few minutes (Which is what is expected for our site) during holidays and weekends.

**Comment by rmehta** [comment]
This might already be fixed. To check
