### ISSUE TITLE
Delete WareHouse

### ISSUE THREAD

**Issue by zubair2930** [frappe/erpnext#10083]
Hi,

We are setting up ERPNext for our company. For Demo Purposes, we created a Warehouse and put some material in it through stock entry.

Now I want to delete the warehouse. However, it cannot be done as it is telling stock has some quantity in it. I tried but i cannot find anyway to remove the stock quantity. I also tried to remove all the materials using material issue but still no gain.

Please advise how to proceed

**Comment by tundebabzy** [comment]
Hi @zubair2930 
Thanks for trying out ERPNext. In order for you to get faster responses, I'll advise you post the question on our forum (https://discuss.erpnext.com). We use github for confirmed bugs and enhancement requests.

**Comment by zubair2930** [comment]
Thanks a lot for your clarification.
Being new to frappe and erp I posted here
Cheers
