### ISSUE TITLE
Supplier name and tax id vanished from supplier master

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#10091]
Hello,

After the last update the fields for series, supplier name and tax id are hidden, even if the option to hide them are unmarked.

*edit: this is also affecting employees document, the name, company and other fields are also hidden

**Comment by umairsy** [comment]
Working just fine in my test account. Also checked by enabling supplier naming by Naming Series. Field are appearing just fine.

Please share details of your ERPNext account build and version. Also, if any location customization causing this issue.

![screen shot 2017-07-26 at 2 35 16 pm](https://user-images.githubusercontent.com/910238/28613343-c8eca026-720f-11e7-83fc-33e8f0852206.png)

**Comment by applepipe** [comment]
it was fixed with a bench update
