### ISSUE TITLE
GST POS Invoice with Serial Number

### ISSUE THREAD

**Issue by shanmukhasai6** [frappe/erpnext#10113]
How to setup POS Invoice with GST details and with Serial Number in the invoice for items with serial Number

![image](https://user-images.githubusercontent.com/30374799/28618812-6cc9c9a4-7223-11e7-82d1-ab96f1f8b441.png)

**Comment by umairsy** [comment]
Hello,

Can you please elaborate what all GST details are needed for the invoicing. You can update GSTIN of your company in the Letter Head section itself. For the retail, which is mostly the case of B2C, the end user will not have GSTIN.

In the case of Serialized Item, you can directly enter (manually or via Barcode) the Serial No. of an Item in the Search Item field. Based on that, an item will be added to the POS invoice, with Serial No. detail.

![screen shot 2017-07-27 at 5 17 52 pm](https://user-images.githubusercontent.com/910238/28668905-999552d8-72ef-11e7-8259-e832bf2f1dff.png)

**Comment by shanmukhasai6** [comment]
Hello,

As you have said I have tried configuring as below

![image](https://user-images.githubusercontent.com/30374799/28669076-3dff69da-72f0-11e7-9238-9e8397cf1403.png)

But the field Serial No. is to printed on this invoice.  The product shown has a serial number.

It was called for using the serial no. into the invoice.

But when printing the invoice the serial no. is not printing.

The same also applies to GST Invoice

![image](https://user-images.githubusercontent.com/30374799/28669121-8057e564-72f0-11e7-9626-47ce4e6b5bf0.png)

in this visual there are two errors.

One no serial number was printed

the other even though the tax rate in tax breakup is @ 14% the header is showing @9%.  This aspect need to rectified as when I issue a invoice thus the client is not accepting the same.

**Comment by umairsy** [comment]
@rohitwaghchaure can we add Serial No. field in the print format of  POS and GST invoices? Also, other GST related details as needed.

**Comment by shanmukhasai6** [comment]
I would also like to request for payment summary at the end of the POS Invoice
