### ISSUE TITLE
Error when sending emails with accented characters

### ISSUE THREAD

**Issue by gbard** [frappe/erpnext#10119]
Hello,

I'm getting a lot of errors in ERPNext because of the accented characters. Especially when sending e-mails. In French, we commonly use the "é" and it seems to be causing issues:

'ascii' codec can't encode character u'\xc9' in position 390: ordinal not in range(128)

As much as possible, I'm trying to remove the accented characters everywhere (Company names, account names, client names, etc.) but it's hard to remove them to avoid issues in e-mail.

Steps to reproduce: Send an e-mail with the character "é" in the subject line and in the body and check the e-mail queue / error log.

Thanks!

**Comment by joolsr** [comment]
I had a similar problem with accentuated characters like a tilde on an n in Spanish being removed from the contact's name from an email sent into ERPNext. I havent raised a bug as yet, but I think it could be linked

**Comment by joolsr** [comment]
looks like its been fixed today ;-) https://github.com/frappe/frappe/commit/22475a046c8d2da69e6f2158ed8e0f5c09072da4. thi is in Develop and as a hotfix so even running Master you should get this if you update now

**Comment by umairsy** [comment]
As confirmed by @mbauskar pull request mentioned above should resolve this issue. If it doesn't feel free to reopen this issue.

**Comment by gbard** [comment]
I confirm the issue seems to be fixed on latest update:

ERPNext: v8.6.3 (master)
Frappe Framework: v8.6.2 (master)
