### ISSUE TITLE
Change status colors (swap red/green for open/close)

### ISSUE THREAD

**Issue by DrTrills** [frappe/erpnext#10121]
I have a UI enhancement request. I believe it would make more sense to have open things be green, and closed things be red.

Perhaps its the traffic signals that give association go stop/go. But the current color scheme seems backwards to me. If others disagree then we can keep it as is.

Thank you

**Comment by rmehta** [comment]
I think open means "needs attention" -> red!

**Comment by DrTrills** [comment]
Hah I figured that was the thinking behind the color scheme. For whatever reason red mentally triggers STOP and i'd associate it with done. Nothing major, if others have no problem with the color scheme i'm ok with it. Thank you @rmehta for your reply
