### ISSUE TITLE
Standard Print Format - optimize format and space to prevent content flowing in multiple rows

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#10122]
![screen shot 2017-07-27 at 11 03 22 am](https://user-images.githubusercontent.com/910238/28655854-09c74018-72bc-11e7-8e4d-6fdcf5bb685c.png)

**Comment by conelco** [comment]
Page will look more better if alignment is done in all ledgers
D.o. invoice, purchase, etc.

**Comment by conelco** [comment]
Dear Support Noupdate on above issue

**Comment by sharmanakul** [comment]
To meet such requirements custom print formats can be created. 

Seems like this issue is now stale and am closing it.
