### ISSUE TITLE
Payment Entry Reference - Duplication of invoices in the rows.

### ISSUE THREAD

**Issue by addymuliady** [frappe/erpnext#10123]
ERPNext: v8.5.4 (master)
Frappe Framework: v8.5.7 (master)

When doing payment entry, the outstanding invoices are shown. However, the invoices appear twice.

Thanks!

![inked_payment_entry_li](https://user-images.githubusercontent.com/21187126/28656430-87fa0660-72d4-11e7-95f7-a9707aa3285f.jpg)

**Comment by umairsy** [comment]
Hi,

Can you please list the steps followed to replicate this issue?

I just created a new Payment Entry and selected Customer in it. For me, Invoices were fetched only once.

![screen shot 2017-07-27 at 5 21 52 pm](https://user-images.githubusercontent.com/910238/28669070-3b3324bc-72f0-11e7-8e7c-341063ef3c78.png)

**Comment by addymuliady** [comment]
Hi @umairsy I can't replicate it again this time. Very weird on how it appears. Seems intermittent. 

I apologize for your time wasted.
