### ISSUE TITLE
Remove Valuation Rate and Standard Selling Rate field from first section

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#10146]
Mostly user confuses Valuation Rate mentioned with the Item master with the Valuation Rate in the BOM and Stock Ledger, as valuation rate for an item in both these places are different. The field in the item master doesn't convey that it is only for reposting.

Also, Standard Selling Rate field work only when creating New Item. Once Item is saved, editing value in this field doesn't have any impact on the Item Price. We can continue to have these fields in the quick view of item master, but would be better to place it in the former sections of Item master.

![screen shot 2017-07-28 at 10 49 55 am](https://user-images.githubusercontent.com/910238/28703622-032681b6-7383-11e7-93dc-c13cff129d4a.png)

**Comment by joolsr** [comment]
+1 for moving the Std Selling rate
