### ISSUE TITLE
Payment Entry - Multicurrecy Payment - Set Exchange Gain/Loss should be in company currency

### ISSUE THREAD

**Issue by addymuliady** [frappe/erpnext#10145]
ERPNext: v8.5.4 (master)
Frappe Framework: v8.5.7 (master)

1. Create New Payment Entry
2. Select a Foreign Account
3. Allocate to all outstanding invoices
4. There should be a Difference Amount
5. Click on Set Exchange Gain Loss
6. ERPNext will automaticall create a difference entry in account currency instead of company curency
7. Click on Save and Submit

Prompt:
![image](https://user-images.githubusercontent.com/21187126/28698834-8120179a-7378-11e7-8b43-4f74652c6792.png)

**Comment by tundebabzy** [comment]
Seems like there is more to this
![peek 2017-07-28 11-25](https://user-images.githubusercontent.com/818803/28713936-1491f5a6-7389-11e7-8d2d-07b4c637c901.gif)

@addymuliady can you confirm this behaviour that changes to allocated amount are not converted when updating the allocated amount field

**Comment by addymuliady** [comment]
@tundebabzy yes, I can confirm that too. ;(

**Comment by tundebabzy** [comment]
Tasks:
1. The bug in this issue stems from the fact that we are mixing two currencies when calculating unallocated amount and difference amount. Exchange gain/loss should be separated from deductions
- [ ] Create another read only child table for Exchange Gain/Loss. If user needs to do any exotic splits, a journal entry will suffice.
- [ ] Make accounts selectable from Deductions table to be only those in transaction currency.

**Comment by iamkhalidbashir** [comment]
@nabinhait 
This issue is not resolved
"ERPNext will automatically create a different entry in account currency instead of company currency"
This was the actual issue addressed by @addymuliady first, the latter issue is solved only

Only company currency deductions can be made but not account currency
