### ISSUE TITLE
Print Format - Please delete one of the field - Standard or Custom Format

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#10150]
I believe both the field has same purpose, hence we should only have one of it.

![screen shot 2017-07-28 at 12 17 15 pm](https://user-images.githubusercontent.com/910238/28705756-df7640f6-738e-11e7-9219-4565f7cc466f.png)

**Comment by sharmanakul** [comment]
As of today only the checkbox is available in the print format.
