### ISSUE TITLE
Invoices - Notification for the Advance Payment Adjustment missing

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#10152]
WN-SUP26779

In the earlier version, when creating Sales Invoice, if advance Payment Entry was found for the Customer, then it was auto-updated in the Sales Invoice. Also, there use to be the notification that Advance Payment Entry found for the Customer, and you can allocate the Amount if needed. In the current version, this validation is missing, even if Advance Payment Entry existed for an item.

**Comment by jaichavan** [comment]
In the latest version, this issue has been addressed and resolved, hence closing.
Version: v11.0.3-beta.34 () (staging)
