### ISSUE TITLE
Unable to attach GSuite document

### ISSUE THREAD

**Issue by mimiza** [frappe/erpnext#10164]
![d469225320cbbdcbcb8ce51bcf09d430069e600e_1_690x376](https://user-images.githubusercontent.com/20904034/28717103-9c04d40e-73ca-11e7-84ef-b58dc8a36411.png)
Ive successfully integrated GSuite. However, when I try to attach GSuite document, it asks me to provide a file or url.

**Comment by almeidapaulopt** [comment]
I confirm the bug. There's some bug on control, if you select with keyboard it works fine, if you select with a mouse click it's not working.


I'll check it asap.
