### ISSUE TITLE
GST Tax Breakup on Bundled Products with different tax rates 

### ISSUE THREAD

**Issue by shanmukhasai6** [frappe/erpnext#10166]
Is it possible to show different tax breakups with respective HSN codes for different Products in the bundle.

![image](https://user-images.githubusercontent.com/30374799/28718751-edbb46d0-73c4-11e7-9dbf-1ef9ed92b67c.png)

In this picture a product bundle was billed. Parts of the bundle are of different tax rates.
but the invoice so generated shows wrong Tax Rate and amount which may cause issues with Tax Compliance.

![image](https://user-images.githubusercontent.com/30374799/28718765-fbfa2bb2-73c4-11e7-82b1-0c3281007364.png)

can this be rectified and detailed tax breakup be added with respective HSN Codes

**Comment by nabinhait** [comment]
One user in the forum share this link in the forum.

https://cleartax.in/s/mixed-composite-supply-gst

According to this, all items in the bundle should have the same gst rate. Can you please verify?

**Comment by snvora** [comment]
True. As per above only one tax rate on composite sale. 

Eg: if you are selling PC - you will not bill for each individual parts.

**Comment by shanmukhasai6** [comment]
But when we sell a pc we need to bill individual parts for their respective warranties.  
It can be put up as composite sale

As per your help the taxation issue is solved.  

But we need to provide individual item serial numbers for their warranties.

Can we put serial numbers of items in the bundle breakup. And get printed in the invoice

**Comment by nabinhait** [comment]
Yes, you can set serial nos of the individual item in the "Bundled " Item table which appears below the Sales Invoice Item table. Then you need to create a custom print format using Print Format Builder to show the the bundled items table with serial nos.
