### ISSUE TITLE
Customize auto-suggested, search items

### ISSUE THREAD

**Issue by zubair2930** [frappe/erpnext#10175]
In the auto-suggested, search works on some pre-defined fields like Item Code, Name Name, Description etc. But, our requirement is to include Field Brand also be there.
However, this seems impossible as of now

**Comment by zubair2930** [comment]
Come on Anyone. Just do not leave me hanging out here

**Comment by umairsy** [comment]
Hello,

You should enable Global Search for the Brand field, so that it will be included in the search. 

http://imgur.com/a/vy92o

For post your queries on the ERPNext community forum for faster response.

https://discuss.erpnext.com

**Comment by zubair2930** [comment]
Mr. Umair, I am thankful for your detailed response on the matter. However, our requirement is that when we search for items in the material request form or any such form, it is showing description and item code as auto complete suggestion. However, we want it to be showing brand name there as well.

Again in the Auto Complete of Material Request forms, we need to show brand and so on

**Comment by zubair2930** [comment]
![frappe](https://user-images.githubusercontent.com/30434647/28767963-7e5567f0-75de-11e7-9477-9dc0f1ad5bca.png)
