### ISSUE TITLE
Rate and Discount not saved correctly in items for SO, QUO Doctypes

### ISSUE THREAD

**Issue by joezsweet** [frappe/erpnext#10177]
Hi all,

i got a bug in SO, QUO, when saving doctype; changes in Rate or Discount for items are not stored correctly, please see video: 

http://recordit.co/4MQk1RFFMY

Can you please have a look?

**erpnext 8.6.4**
**frappe 8.6.3**

**Comment by drthilina** [comment]
Hi,
   Do you have Pricing rule set up?

**Comment by joezsweet** [comment]
Yup, there is a pricing rule, but "manual discount should overwrite it. It was working like that in previous varsions

**Comment by nabinhait** [comment]
I think, it was never like that, if pricing rule always gets highest priority. If you want to manually edit the discount then check on "Ignore Pricing Rule" field above the item table.

**Comment by joezsweet** [comment]
@nabinhait I can assure you it worked like that, not sure if it changes since multiple delivery date has been added ..btw i'll have a look at "Ignore Pricing Rule"

**Comment by drthilina** [comment]
@joezsweet, please set your pricing rule discount to 0%, then it will work

**Comment by joezsweet** [comment]
@drthilina what you mean? I need to have the discount for the item

**Comment by drthilina** [comment]
I'm using the Pricing rule as well. In my case I needed to apply a margin to the products. but discount should be possible as user wishes. To subject it to a max limit, I had to set the discount individually in item master.

**Comment by joezsweet** [comment]
@drthilina your use case is different, in my case the only way is to apply ignore_pricing_rule but it's not working in Quotation

**Comment by nabinhait** [comment]
@joezsweet In quotation, ignore_pricing_rule is disabled because of Permission, I will fix it in the product. But if you want it urgently, from Permissions Manager > Quotation, please give "Write" permission to permlevel 1 for the related role.

**Comment by joezsweet** [comment]
@nabinhait thx it works now! looking forward for the fix.
