### ISSUE TITLE
Stock Balance Report not getting filtered based on user permissions

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#10179]
Hi

Trust you're doing great. The Stock Balance Report is not getting filtered based on user permissions. A user has only one role with the following permissions:

1. Access to Stock Balance report
2. User Permission set for a specific Warehouse
3. View Stock Ledger Entry if Warehouse is permitted

Still when the user opens Stock Balance Report, he sees stock balance for all warehouses!

Please help fix

Thanks

**Comment by umairsy** [comment]
Hi,

I am facing opposite. After apply User Permission for Stock User, and restriction applied based on Warehouse, then no entries are visible in the Stock Balance report. Not even for the Warehouses for which User Permission is defined in the permission manager.

**Comment by Olawale1** [comment]
Hi @umairsy 

Good to hear from you. Please ensure that the role has 'View' permissions for 'Stock Ledger Entry' doctype and is also permitted for the Stock Balance report in 'Role Permission for Page and Report'. You may need to clear your cache as well. I've tried this again after updating to the latest version and it's exactly the same issue... all balances for all warehouses are visible!

Thanks

**Comment by Olawale1** [comment]
Hi @umairsy

Trust you're doing well. Were you able to validate this? The issue is not allowing us to give permission to Warehouse managers to view Stock Balance 

Thanks

**Comment by Olawale1** [comment]
Hi @umairsy 

Trust you're doing well. Please update the tag if you've been able to validate this

Thanks

**Comment by Arundhatii** [comment]
Hello,

The User permissions for warehouse for Stock Balance report. seems to be working fine. Once you have allowed a Warehouse for a User. In Role permission manager, please check "Apply User permission" and under select documents check "If Warehouse is permitted". Refer the gif. 
![user permission issue](https://user-images.githubusercontent.com/20164097/30374504-cff0c244-98a2-11e7-97f1-cef4a351a51f.gif)

**Comment by Olawale1** [comment]
Hi @Arundhatii 

Thanks for your helpful response. The missing link was setting permission for Warehouse on the Warehouse DocType itself :)

I'm closing this now

Kind regards,
