### ISSUE TITLE
Manufacturing: Product Rejection and Raw Material Accounting

### ISSUE THREAD

**Issue by DhananjayVMX** [frappe/erpnext#10176]
Hi,

We have been using ERP Next for quite some time and we feel that following scenario needs to be handled better in Manufacturing Module ...

Let us consider we need X amount of Raw Material to produce Y amount of Components, we raise a production order for the same and material are transferred to WIP, but during the production of the Component we had to reject Z count due to defects, that means we have consumed the complete raw material (X amount) to produce components (Y Count) but ended up rejecting Z count, but this is no where accounted for.

with current flow, i have to close the Production Order by saying Y Count of components are produced, but after identifying rejections, i have to raise one more work order to produce Z components (if there are rejection in this stage i might need to raise one more ...), raw material accounting and the components produced cannot be reconciled and creates a lots of confusion.

Can we have the feature of entering the rejected component count while we enter the Components produced (even a small screen which can accommodate the rejection reason and add it to a batch as some rejected components can be sold as items) ?

We are willing to sponsor to develop this feature.
Regards,
Prashanth

**Comment by umairsy** [comment]
Hi,

You can enter Scrap items and it's estimated value in the BOM itself. This will be accounted in the manufacturing transaction as well.

Also, you can create entries against Production Order by deviating from items in the BOM. For the same, you should enable this setting in the Manufacturing Setting.

![screen shot 2017-07-31 at 12 38 38 pm](https://user-images.githubusercontent.com/910238/28766437-337120da-75ed-11e7-90f2-3f876bb862c7.png)
