### ISSUE TITLE
Arabic Translation Issue

### ISSUE THREAD

**Issue by dufani1** [frappe/erpnext#10188]
When using the ERPNext translator I faced a problem which is when set the direction RTL and press the update button the translated sentences back to LTR direction. 
I am using Google Chrome and I tried other browsers but the same issue.

![untitled](https://user-images.githubusercontent.com/23026263/28768937-d18e7ae2-75d9-11e7-8c3e-062c050eeb34.png)

and..........

![untitled2](https://user-images.githubusercontent.com/23026263/28768997-1bc16a66-75da-11e7-869d-5d2bbc50a718.png)

**Comment by dufani1** [comment]
@mbauskar any update I am still awaiting to complete the translation.
please help

**Comment by mbauskar** [comment]
@dufani1,

Thanks for reporting, fixed the issue via https://github.com/frappe/translator/pull/110. I, will update the translate.erpnext.com once the PR is merged

**Comment by dufani1** [comment]
@mbauskar the issue still exists. Please check
Thanks

**Comment by dufani1** [comment]
@mbauskar working properly now thanks
