### ISSUE TITLE
The Amount field in POS should be read only

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#10180]
Hi,

The 'Amount' field in the V8 POS should be read only (Just like the Price List Rate field). Some users inadvertently put the price of an item in the Amount field and then proceed to payment screen and wonder why the figure isn't showing automatically in the mode of payment. They then go ahead to fill the mode of payment manually and the full amount shows up in the 'Change' field! This makes for bad user experience

![pos amount field issue](https://user-images.githubusercontent.com/9269337/28367570-55def7ae-6c89-11e7-83fb-bb51b8362767.png)

Please help fix

Kind regards,

**Comment by rohitwaghchaure** [comment]
Hi @Olawale1 

Thanks for reporting an issue
We have fixed this issue and soon we'll release it
