### ISSUE TITLE
Auto email report Headers showing "No Label"

### ISSUE THREAD

**Issue by drthilina** [frappe/erpnext#10181]
Hi,
 Please see the issue below,
![image](https://user-images.githubusercontent.com/29944021/28762811-0b8eb052-75d7-11e7-8e0e-64973f9709b1.png)

Some columns are having "No Label", bug?

**Comment by rmehta** [comment]
Please specify which version you are using

**Comment by drthilina** [comment]
I'm on the hosted plan..

ERPNext: v8.6.4 (master)
Frappe Framework: v8.6.3 (master)

**Comment by netchampfaris** [comment]
@drthilina What DocType is this? Can you provide more information to replicate the issue?

**Comment by drthilina** [comment]
Purchase Orders...
"
{"add_total_row": 0, "sort_by": "Purchase Order Item.schedule_date", "add_totals_row": 0, "sort_order": "desc", "sort_by_next": null, "filters": [["Purchase Order", "docstatus", "!=", "2"], ["Purchase Order", "supplier", "=", "Pubudu Engineering (Pvt) Ltd"], ["Purchase Order", "status", "!=", "Completed"]], "sort_order_next": "desc", "columns": [["schedule_date", "Purchase Order Item"], ["transaction_date", "Purchase Order"], ["name", "Purchase Order"], ["status", "Purchase Order"], ["stock_qty", "Purchase Order Item"], ["per_received", "Purchase Order"], ["item_code", "Purchase Order Item"], ["item_name", "Purchase Order Item"], ["description", "Purchase Order Item"]]}

This is the JSON for the specific report. Hope it will be helpful to replicate..

BTW, When we try to export a report we always a get a failure
![image](https://user-images.githubusercontent.com/29944021/28771687-6116b37e-7601-11e7-897f-6355b0eb3ea2.png)
But when Exported again (2nd time) its successful.. Don't know if its related to this..

**Comment by drthilina** [comment]
[Thilina,-Active-TXN-with-Metafold.xlsx](https://github.com/frappe/erpnext/files/1336065/Thilina.-Active-TXN-with-Metafold.xlsx)

**Comment by mbauskar** [comment]
@drthilina,

this issue may be fixed in https://github.com/frappe/frappe/pull/4096, can you please update and check?

**Comment by drthilina** [comment]
@mbauskar ,

   I just downloaded, it looks like its fixed. I'll keep you posted.
Thanks
Thilina
