### ISSUE TITLE
auto email report html format is broken

### ISSUE THREAD

**Issue by sumitdas4u** [frappe/erpnext#10182]
![image](https://user-images.githubusercontent.com/28945509/28763776-1d7c3b48-75de-11e7-827c-c594a48ba5d2.png)
auto email report html format is broken

**Comment by rmehta** [comment]
Please specify your version

**Comment by sumitdas4u** [comment]
Installed Apps

ERPNext: v8.5.2 (master)

Frappe Framework: v8.5.5 (master)

**Comment by netchampfaris** [comment]
@sumitdas4u This has been fixed. Please wait for the next release.
