### ISSUE TITLE
Sale UOM in item master

### ISSUE THREAD

**Issue by jagjyo** [frappe/erpnext#10183]
There is a default UOM in Item master. It will be good if under sales details if we can capture Sale UOM. This will be helpful for the clients who maintain stock and sell items in different UOMs (like maintaining stock in KGs and selling in Pkts or Nos). So by default in sales order, sale UOM will appear..Not default UOM.

**Comment by jagjyo** [comment]
- [ ] 

- [ ]

**Comment by kennethsequeira** [comment]
Added in v11

![image](https://user-images.githubusercontent.com/33246109/56415839-98dc9280-62ac-11e9-97e6-121b38fe5fed.png)
