### ISSUE TITLE
frappe.patches.v8_x.update_user_permission issue

### ISSUE THREAD

**Issue by KanchanChauhan** [frappe/erpnext#10193]
Patch was fixed recently via https://github.com/frappe/frappe/pull/3809 but some people have already updated and patch already ran for them. Any fix for them.

**Comment by applepipe** [comment]
This would be good! I'm trying to delete the log on tabPatch to rerun the patch. Is there any other way to do it?

**Comment by mbauskar** [comment]
@KanchanChauhan, @applepipe 

You will need to delete the user permissions from User Permission doctype manually, As previously the User Permission was stored in tabDefaultValue and all the User Permission are already deleted from the tabDefaultValue if the patch is already completed.

@applepipe,

Deleting the patch log and rerunning the patch again will not work, as the user permissions are already deleted from tabDefaultValue is already deleted
