### ISSUE TITLE
Salary Register Date range in Portuguese

### ISSUE THREAD

**Issue by Helkyd** [frappe/erpnext#10199]
If Language Portuguese and i select the Date Range .. the default value for the date is not passed and also if i click and select the dates they are not passed ....while the f.value.length has two records... while in EN language it works ....
This is the code from report.min.js

get_values: function get_values(raise) {
	var filters = {};
	var mandatory_fields = [];
	$.each(this.filters || [], function (i, f) {
		var v = f.get_value();

The problem lies in desk.min.js on the Parse function 
This because the value of the value Date is '30-06-2017 para 31-07-2017' and the IF compare is for the TO word not the translated one ....

parse: function parse(value) { 
if (value && (value.indexOf(',') !== -1 || value.indexOf('to') !== -1)) {

**Comment by tundebabzy** [comment]
Hi @Helkyd 
can you have a go at fixing this? We'll happily merge it in.
