### ISSUE TITLE
New Company Address not saving

### ISSUE THREAD

**Issue by SVSRepairs** [frappe/erpnext#10198]
When I add a new customer and then try adding a billing address for that customer, the address does not get saved for that customer. It will eventually save after making several attempts.

**Comment by umairsy** [comment]
Hi,

I just tried to replicate this issue in my test account. I was able to add new Address from the Company master.

Can you please try replicating this issue? Please also mention the version of your ERPNext instance and browser from which you are accessing it.

Let's continue the discussion on this from https://discuss.erpnext.com. If it's validated as a bug, we can reopen this issue.

**Comment by SVSRepairs** [comment]
I just enter a new customer and address and it worked this time, so I don’t know what was happening before.
