### ISSUE TITLE
Error In installation - Using source

### ISSUE THREAD

**Issue by sah-anshu** [frappe/erpnext#10192]
10:53:16 worker_default.1 | 10:53:16 
10:53:16 worker_default.1 | 10:53:16 *** Listening on default...
10:53:17 web.1            |  * Detected change in '/home/erpnext/frappe-bench/apps/erpnext/erpnext/controllers/taxes_and_totals.py', reloading
10:53:17 web.1            | INFO:werkzeug: * Detected change in '/home/erpnext/frappe-bench/apps/erpnext/erpnext/controllers/taxes_and_totals.py', reloading
10:53:17 web.1            |  * Detected change in '/home/erpnext/frappe-bench/apps/erpnext/erpnext/controllers/taxes_and_totals.py', reloading
10:53:17 web.1            | INFO:werkzeug: * Detected change in '/home/erpnext/frappe-bench/apps/erpnext/erpnext/controllers/taxes_and_totals.py', reloading
10:53:17 web.1            | ----------------------------------------
10:53:17 web.1            | Exception happened during processing of request from ('210.56.112.201', 17742)
10:53:17 web.1            | Unhandled exception in thread started by <bound method Thread.__bootstrap of <Thread(Thread-54, stopped daemon 140299694221056)>>
10:53:17 web.1            | Traceback (most recent call last):
10:53:17 web.1            |   File "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
10:53:17 web.1            |     self.__bootstrap_inner()
10:53:17 web.1            |   File "/usr/lib/python2.7/threading.py", line 814, in __bootstrap_inner
10:53:17 web.1            |     (self.name, _format_exc()))
10:53:17 web.1            |   File "/usr/lib/python2.7/traceback.py", line 241, in format_exc
10:53:17 web.1            |     etype, value, tb = sys.exc_info()
10:53:17 web.1            | AttributeError: 'NoneType' object has no attribute 'exc_info'
10:53:17 web.1            |  * Restarting with inotify reloader
10:53:18 web.1            |  * Debugger is active!
10:53:18 web.1            |  * Debugger PIN: 192-864-238

**Comment by umairsy** [comment]
Hello,

Request to post this issue on erpnext community forum where we provide help on technical isuses.

https://discuss.erpnext.com
