### ISSUE TITLE
Request feature - Pricing rule, Max discount

### ISSUE THREAD

**Issue by drthilina** [frappe/erpnext#10190]
Hi,
   Can you add a feature to limit the max discount?, fixed discount is already there but what I'm interested is to override the default max discount and set a new limit via the pricing rule.

BR
Thilina

**Comment by drthilina** [comment]
Meaning user can give any discount below the set discount....

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.
