### ISSUE TITLE
Downstream Cancellation

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#10204]
As per the current design, once a documentation is linked to another document, it cannot be canceled.  Users often ask for the functionality to cancel and amend a transaction which is linked with other transaction.

**Comment by akshay83** [comment]
+1

**Comment by applepipe** [comment]
+1

**Comment by snvora** [comment]
+1

**Comment by cosimot** [comment]
Everyday to unlink and relink documents make us spend hours of work so I think this is really important to allow people to correct mistakes or change according to what Clients ask.
Clients change their mind and we can't tell them "sorry I can't do this as my ERP is not allowing me to do this..."
Plus to unlink and then relink documents is an extremely risky thing to do.

**Comment by umairsy** [comment]
Since version 11 has new feature if updating item's qty and rate in the submitted document only, most of the use-case related downstream cancelling should be addressed with it.

**Comment by cosimot** [comment]
for us the most of the use-case is changing delivery address or billing address, will this be possible?
