### ISSUE TITLE
Parent Group option in Stock Ledger

### ISSUE THREAD

**Issue by lifestylesofas** [frappe/erpnext#10212]
Hello, 

In Stock Ledger Report y we can't search with parent group. The filter option is only for child group which is not right. Filter option should be with both either Parent Group or Child Group. Because in Masters parent Group is already defined in that we make child group, child group can be 100 or more than that. For example Raw Material is parent Group under this many groups come like Hardware, Fabric, Foam, Leather and so on. If we want to check Stock Ledger in heading its saying filter group but only child group filter option is there which is wrong. I request please rectify this issue on urgent basis, it will help so  many people.

Regards

Amit
Lifestylesofas

**Comment by umairsy** [comment]
Add an Item Group filter in the Stock Ledger entry report. In this report, user should be able to apply filter on both Parent and Child Item Group.

**Comment by lifestylesofas** [comment]
Hi, 

any updates on t he above issue.

**Comment by lifestylesofas** [comment]
I am waiting for reply

**Comment by lifestylesofas** [comment]
As this issue is very important and basic thing in ERP. I request you to do needful on top priority.

**Comment by nabinhait** [comment]
As you can see we have added the issue in the August milestone, so you can expect the feature by the end of this month. There are so many things which are important, 992 github issues as of now. I think you can understand, we can't implement everything within a week or so.

**Comment by lifestylesofas** [comment]
Any updates on the above issue.

**Comment by lifestylesofas** [comment]
Hi, 

Thanks fro adding the above issue but still in our side its not showing that filter.

**Comment by manassolanki** [comment]
Hi @lifestylesofas ,
If you are on the frappe cloud, then you will get this fix in the next release.

**Comment by lifestylesofas** [comment]
Still i cannot see the changes in my URL

**Comment by lifestylesofas** [comment]
![image](https://user-images.githubusercontent.com/29091753/29559134-d55d63da-874b-11e7-9709-e45c7155dc63.png)

**Comment by manassolanki** [comment]
Could you please tell us the Frappe and ERPNext version?

**Comment by lifestylesofas** [comment]
![image](https://user-images.githubusercontent.com/29091753/29562572-682ac8c8-8757-11e7-8cf6-e909ef45e336.png)

**Comment by manassolanki** [comment]
Hi,
This has been merged into the develop branch and will be released in the master on Tuesday next week as per our release cycle.
For the working you can view the following pull request (https://github.com/frappe/erpnext/pull/10400)
