### ISSUE TITLE
validation needed for special characters in custom report titles

### ISSUE THREAD

**Issue by episensor** [frappe/erpnext#10219]
a URL is formed from the title of the custom report, so special characters should be encoded.

yoursite.com/desk#modules/CRM

![image](https://user-images.githubusercontent.com/20316499/28848814-416b15ae-770c-11e7-993d-2423b9548e3c.png)

**Comment by umairsy** [comment]
Hello,

I just create a custom report with special characters in it. I am able to access it just fine. Can you please further elaborate as why should we encode special characters in the URL? Are you facing issue in accessing any report with special character in it?

**Comment by episensor** [comment]
It looks like custom report links with special characters (a forward slash in my testing) are badly formed only at the bottom of the following page: /desk#modules/CRM

**Comment by umairsy** [comment]
/ should not be allowed in the report naming. possible to restrict other special characters as well?

**Comment by rohitwaghchaure** [comment]
Hi @episensor 

I have created report with the name TestSale/Order and formed proper URL
#Report/Sales Order/TestSale/Order
