### ISSUE TITLE
Bug - Customer group node doesn't includes its childs when Tax rules are applied.

### ISSUE THREAD

**Issue by drthilina** [frappe/erpnext#10223]
Hi,
   I think this issue had been there for quite a some time. When we create customer groups,
![image](https://user-images.githubusercontent.com/29944021/28859943-f662b64a-7777-11e7-80e0-8bd0d5486342.png)
We put certain customers groups (child) in side a node.
When we select the Group node in "Sales and Tax charges template" it doesn't get applied to its children.
Under Pricing rule it seems to be working fine.

**Comment by umairsy** [comment]
Hi,

Can you please indicate how are you selecting Customer Group for the Sales Taxes and Charges Template? Are you referring to the tax rule or some other configuration, so that we can try and replicate it? For now, please specify child Customer Group to have taxes applied as needed.

**Comment by drthilina** [comment]
Hi, the picture below shows one my Tax rule template,
![image](https://user-images.githubusercontent.com/29944021/28863789-ebc54986-7787-11e7-95a1-b21291e748dc.png)

For the time being I have done what you have mentioned.

Under "Customer Group" if I select a Group node then any customer that have the same Customer group as the name of the Group node will get their Tax rule selected, but it will not work for any child or child node.

**Comment by drthilina** [comment]
Even after selecting a customer belonging to a Child node, Tax and Charges template selection box remains empty
![image](https://user-images.githubusercontent.com/29944021/28864010-bfe83912-7788-11e7-9a4b-730b914ae5b2.png)
But whatever the set default template gets applied, even though its not shown (this is a bug as well, I believe)
