### ISSUE TITLE
Make offline POS optional

### ISSUE THREAD

**Issue by rohitwaghchaure** [frappe/erpnext#10224]
- [ ] Make POS Settings page, where user select Offline/Online option for POS

- [ ] If user has selected online option then data loading and syncing will done at a run time, no data will be kept in the local storage and local cache.

- [ ] If user has selected offline option then data will be stored in the local storage.

- [ ] POS screen resize issue on tablet(https://discuss.erpnext.com/t/if-you-are-going-to-rework-pos-please-also-fix/26801)

**Comment by chdecultot** [comment]
Hi,

It's a great decision, thanks a lot 👍👍👍

Is it possible to consider restricting the access to this option only to the Administrator?
Giving the possibility to use an offline POS is a decision based either on specific requirements or on compliance issues.
In case of France, we need to be able to control this option to allow users to use the POS module. If the Administrator is the only user who can decide it, it will be possible to guarantee that we have control over the user's potentially fraudulent behavior.
If any other end user can change this option (even the system manager), it will not be accepted by the tax administration as compliant enough.

Maybe this option could be in the developer module or in the site_config.json ?

Thanks a lot! I'm happy to help if needed 😊

**Comment by grynn-in** [comment]
We have to assume user is clueless first and fradulent next :) 

Compared to a complete breakdown (offline POS is unstable), I prefer an optional offline/online setting. 

However, maybe it could be done at a profile level to respect Chdecultot's concern.  
As opposed to the user setting himself  up for a disaster.  (A user making his his own setting is akin to giving him a loaded gun without safety lever. Best avoided)

And allowing the Admin to set the option for a user is more "control" than a user doing it himself. 

I dont know how it would prevent fraud. A malicious POS agent can pack a bag of chips or a watch in his pocket and walk out. No POS can prevent it.  :)   👍 

Those are my 2 cents. Thanks

**Comment by rohitwaghchaure** [comment]
Hi @chdecultot 

We can not gives permission of POS only to the Admin user, but it can be achievable. You have to create new role and and admin user and also assign that role to the POS page and remove all other roles.

**Comment by chdecultot** [comment]
Hi @rohitwaghchaure,

Too bad it is not possible to enable/disable the offline POS with the admin as a standard behavior. 
I'll follow your above advice and see if it can fit with the french compliance requirements.

Thanks! 😊

**Comment by chdecultot** [comment]
Hi @rohitwaghchaure,

Is it not possible to have something similar as what is being done to switch on and off the 2FA ?

https://discuss.erpnext.com/t/hide-fields-based-on-site-config-setting/26976/7

It is exactly what we would need to switch on/off the offline POS! 😊
