### ISSUE TITLE
Delivery Note - In the Packing Slip, add button to "select Serial No.", just like in Delivery Note Item

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#10222]
WN-SUP26990

Trying to use Product Bundle, I found that at Delivery Note, the parent item that is precisely a nonstock, in the child item table, appears the button to select a serial number (...it’s ok). But is precisely at the Packing List child table, where are the stock items, that doesn’t have the button to add serial number.

![screen shot 2017-08-02 at 10 32 15 am](https://user-images.githubusercontent.com/910238/28858425-0638d626-776e-11e7-96c0-b2cd0a4c0a58.png)

**Comment by aakvatech** [comment]
Is this problem still valid?

**Comment by jigneshpshah** [comment]
the issue is in 
ERPNext: v13.5.0 
Frappe Framework: v13.5.1

**Comment by yadavyk** [comment]
This seems to be working fine now. Hence closing.
