### ISSUE TITLE
Setup Wizard Error: Bank account cannot be named as Equity

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#10231]
New users often enter Equity as Bank Name in the Setup Wizard, leading to error at the end of the Setup Wizard

`ValidationError: Bank account cannot be named as Equity`

Can we validate this as soon as user enters value in the Bank Account field in the Setup Wizard? Of just ignore it as have Setup Wizard successfully completed?

**Comment by nabinhait** [comment]
It is difficult to validate beforehand. It is not only Equity, bank account cannot be any of the account of the selected chart of accounts.

**Comment by umairsy** [comment]
May we when setting up account, then if Account Name is already found.. then just ignore.. 

Or validate that Bank Account field should not have Equity as a name, as most people make this mistake only.

**Comment by raghukamath** [comment]
This should be handled intelligently by the system, user shouldn't be bothered with the naming conventions, duplicate names etc. ideally there shouldn't be any error.
