### ISSUE TITLE
am not able to make any journal entry 

### ISSUE THREAD

**Issue by yousefbakir** [frappe/erpnext#10232]
Hi all,

am not able to add any journal entry, it keeps giving me the message that this journal number is already in use "even though this number should be generated automatically and i cant put a number on my own".

please advice.

**Comment by rohitwaghchaure** [comment]
Hi @yousefbakir 
can you please share the series used in the journal entry so we can try to replicate the issue locally

**Comment by umairsy** [comment]
Please check following help link - https://erpnext.org/docs/user/manual/en/setting-up/articles/naming-series-current-value?

**Comment by yousefbakir** [comment]
Hi everyone,

i follow the steps Mr Umairsy sent and it worked i had to update the current series number.

thanks all for your help.
