### ISSUE TITLE
Awesome bar does not honour Domain Settings and while accessing restricted domain gives error

### ISSUE THREAD

**Issue by nabinhait** [frappe/erpnext#10235]
**Domain Settings:**

<img width="884" alt="screen shot 2017-08-02 at 2 30 41 pm" src="https://user-images.githubusercontent.com/836784/28866069-78394ee2-778f-11e7-8e71-714d2fdf3cb6.png">

---
**Awesome bar:**

<img width="728" alt="screen shot 2017-08-02 at 2 31 38 pm" src="https://user-images.githubusercontent.com/836784/28866092-83aaeef2-778f-11e7-9079-f457c9009a9e.png">

---
**Error Message:**

<img width="836" alt="screen shot 2017-08-02 at 2 31 48 pm" src="https://user-images.githubusercontent.com/836784/28866103-8d2877ba-778f-11e7-8c9a-633903fa28a2.png">

**Comment by rmehta** [comment]
Check "can_read" in utils/user.py
