### ISSUE TITLE
Request for flexibility to define the time of event reminder in Calendar

### ISSUE THREAD

**Issue by vikramnarayan** [frappe/erpnext#1025]
Hi,

Currently in Calendar while we can define various events, there is also a provision to define the time of the event along with details of the event. 

However an event reminder is sent at 00:00am stating these are all the events that are due for that day. 

It would help instead if we could configure during the event setup itself when should this reminder be sent as an email.

This is similar to calendar request that come in Outlook wherein 15 mins before the meeting a reminder comes up. 

Would suggest you have a field of when reminder should be sent and at that time the email is sent out. 

This would help as sending a event reminder at the beginning of the day at 00:00am is not useful. 

Vikram

**Comment by umairsy** [comment]
Now it can be managed using Email Alerts.
