### ISSUE TITLE
Error in completing the sales orders

### ISSUE THREAD

**Issue by ahmedonee** [frappe/erpnext#10252]
when a sales order is made it minimizes the projected quantities of it's items  and then when
i try to complete the order it says that there is a shortage , but it already have minimized the projected quantities it's not supposed to be checking on quantities again !

**Comment by tundebabzy** [comment]
Hello @ahmedonee
Let's discuss this on the forum (https://discuss.erpnext.com). Adding screen shots and/or screen cast will make it easier to resolve too
