### ISSUE TITLE
 Smallest Currency faction and rounded total  not working in POS 

### ISSUE THREAD

**Issue by taherkhalil** [frappe/erpnext#10264]
https://discuss.erpnext.com/t/smallest-currency-faction-not-working-in-pos/26827/2?u=taher_khalil 

The system shows grand total which is not rounded based on smallest currency fraction. It should also show rounded total and change amount will be calculated based on rounded total.

**Comment by taherkhalil** [comment]
Any updates on this ...
 is it a small fix or a big one?

**Comment by taherkhalil** [comment]
@nabinhait any updates?
Still not **working in V9 .**
Set the smallest currency as 0.25
still the system shows amounts payable as 0.01 to 0.24 , 0.26-0.49.........
When it should only be either 0.25, 0.5, 0.75, 1, 1.25.........
and system should round all other values for customer to pay.

Also it would be great if we could restrict this to specific doctypes or fields....would give greater control to companies for how they pay in various countries and different business areas.

**Comment by jaichavan** [comment]
Hello, just replicated the issue on my test account [ ] 
The system does round off the amount as desired, I referred to your post on the forum and it is indeed working as expected, now! Attaching screenshots for your reference:

1. Smallest Currency Faction:

![image](https://user-images.githubusercontent.com/40264279/51406230-856f3d80-1b7e-11e9-8d0f-813235be4897.png)


2. POS Invoice:

![image](https://user-images.githubusercontent.com/40264279/51406159-5062eb00-1b7e-11e9-8b19-123b9c0af5f6.png)

3. Decimal Precision is set to 3:

![image](https://user-images.githubusercontent.com/40264279/51406267-9ddf5800-1b7e-11e9-958c-2f5cec3470c7.png)

Hope this helps! Thanks for reporting!
