### ISSUE TITLE
POS : queue should be async

### ISSUE THREAD

**Issue by grynn-in** [frappe/erpnext#10278]
The queue for transactions made in the POS is currently sync as the come in to the queue. The problem with this is, if the server side validation fails (when the offline POS tries to post it to the server) then all the subheading transactions get held up. 

This can be potentially fixed by making the queue asynchronous. If one is held up, others should proceed. 

Thanks

**Comment by Olawale1** [comment]
I've encountered issues that held up the queue too many times!

Kind Regards,

**Comment by rohitwaghchaure** [comment]
Hi @grynn-in @Olawale1 

I have already [Open PR](https://github.com/frappe/erpnext/pull/10267) for this issue, can you please share your thoughts on it

Thanks, Rohit

**Comment by olamide2** [comment]
Hello Rohit, another issue for retailers is the fact that a cashier can submit a transaction whose tender payment is not completed. Payment should be by Cash or Credit Card, where full payment is not done by either methods, the system should not allow the invoice to be submitted or saved. Please how can this be achieved through the PoS Module?

**Comment by Olawale1** [comment]
Hi @rohitwaghchaure 

Trust you're doing great. Could you please re-open this issue as it has not yet been addressed? The PR apparently had nothing to do with this. In the alternative, I can open a fresh issue

Please advise

Thanks
