### ISSUE TITLE
Sales order to Material request in not shown in Related documents

### ISSUE THREAD

**Issue by drthilina** [frappe/erpnext#10275]
Hi,
   I specifically recall seeing the Sales Order link in "Related documents" when I go in to material request. but it is not shown any more.

In my sales order I see,
![image](https://user-images.githubusercontent.com/29944021/28923479-d7221550-787b-11e7-834b-ddc0563081e6.png)

Then I click on the pending "Material Request",
![image](https://user-images.githubusercontent.com/29944021/28923527-00dd0da0-787c-11e7-941c-6facae51f8f0.png)

But Once I go in to the Material request,
![image](https://user-images.githubusercontent.com/29944021/28923576-23fd82b0-787c-11e7-980e-90c7986ecac8.png)

I don't see the "Sales Order" link any more, if this is a bug please fix this, kind of hard to trace backwards.

**Comment by drthilina** [comment]
@umairsy , this is not a bug?

**Comment by umairsy** [comment]
No.

**Comment by djpalshikar** [comment]
@drthilina #14953 tracks this by creating a new report. Check it out. You can close this issue.
