### ISSUE TITLE
One company Transaction not showing

### ISSUE THREAD

**Issue by maxfu9** [frappe/erpnext#10282]
![untitled](https://user-images.githubusercontent.com/29174889/28952124-837def90-7912-11e7-9bfb-d733a8af4a9a.gif)
ERPNext: v8.7.0 (master)
after switching from develop

**Comment by umairsy** [comment]
Hello,

In the end of the Sales Invoice list, it indicates that permission restriction has been applied based on the Company, and you don't have permission to access Sales Invoices for that Company.

Please review your permission restrictions once again. For further support, report your queries on the community forum.

https://discuss.erpnext.com
