### ISSUE TITLE
GST - Delivery Note should have "Company Address Name" & "GSTIN"

### ISSUE THREAD

**Issue by PawanMeh** [frappe/erpnext#10298]
1. In many scenarios, delivery note is created first & later on invoice. The delivery note maybe needed for transportation purposes. Hence, it should carry "Company Address Name" and "GSTIN" of the company ( Similar to Sales Invoice )

2. So these fields should appear on the delivery note as well.

**Comment by grynn-in** [comment]
Absolutely agree. Delivery note without invoice is meaning less :0)  (where will be it delivered to?)
