### ISSUE TITLE
Enhancement to handle Cash Advances against Expense Claims

### ISSUE THREAD

**Issue by PawanMeh** [frappe/erpnext#10297]
1. Create a journal entry with party type employee, entry is: Expense A/c To Cash A/c

![screen shot 2017-08-04 at 9 19 24 pm](https://user-images.githubusercontent.com/20460498/28976216-aed5acda-795a-11e7-8862-dd9aca1ef422.png)

2. This is a simple cash reimbursement entry to an employee and should be allowed. So this validation should allow expense accounts.

**Comment by tundebabzy** [comment]
Hi. 
Shouldn't this be done with a expense claim? Also I think the essence of payment party is for validation.

**Comment by PawanMeh** [comment]
In an ideal world yes but not necessarily true for very small companies.  Use Case: a clerk asking for travel allowance or a driver asking for toll reimbursement,  they are not necessarily qualified to even raise expense claims in a system.  They would just get the receipt and hand it over to an accountant,  who makes an entry for reimbursement.

**Comment by PawanMeh** [comment]
Suggested simple enhancement to handle Cash Advances directly for employees against Expense Claims

1. Book advance for Employee to an Employee Ledger account using "Party" = Employee ID & "Party Type" = "Employee" using Journal Entry. Asset account should be allowed for selection when party type is employee.
Eg:           EMP/0001    Nabin Hait    1000   Dr
                    To
                         Cash A/C Company 1000   Cr

2.  We need to provide additional checkbox on Expense Claim form, say "Against Advance".  Employee creates expense claim and approver sanctions amount of say 500, and checks the box "Against Advance".
On approval ( Submit ) , following accounting entry is created
Eg:           Expense A/C    Travel Expenses   500   Dr
                    To
                         EMP/0001    Nabin Hait    500  Cr

3. If sufficient balance is not available in the employee cash advance account, system should throw an error if the "Against Advance" checkbox is checked during approval.

4. Expense Claim ID can be linked with Journal ID to maintain cross reference.

**Comment by PawanMeh** [comment]
Testing & Functionality Video:
![expenses cash advance](https://user-images.githubusercontent.com/20460498/30275505-2e6fba6c-971f-11e7-9ba0-1be92c4b3b18.gif)

**Comment by PawanMeh** [comment]
Discussed with Nabin, he would include changes in design in his PR
