### ISSUE TITLE
Comma is added at address details of customer 

### ISSUE THREAD

**Issue by sumitdas4u** [frappe/erpnext#10290]
![image](https://user-images.githubusercontent.com/28945509/28964592-04eca766-792b-11e7-8511-6bbc554c45d4.png)
Installed Apps

ERPNext: v8.5.2 (master)

Frappe Framework: v8.5.5 (master)

**Comment by sumitdas4u** [comment]
the comma is added before pin code. same at print format

**Comment by umairsy** [comment]
Replicating in baba.erpnext.com as well.

**Comment by rohitwaghchaure** [comment]
Hi @sumitdas4u 

Can you remove the comma from the Address Template
