### ISSUE TITLE
Quotation - Error when try selecting Address or Contact for Lead

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#10306]
Since Quotation can be created for Lead as well, selection of Address and Contact for Lead should be allowed.

![screen shot 2017-08-06 at 7 59 51 pm](https://user-images.githubusercontent.com/910238/29004230-f7b326c0-7ae1-11e7-8e71-b17ebfbe2b5f.png)

**Comment by mertberber** [comment]
Yes it should definitely be allowed
