### ISSUE TITLE
Critical Fix needed in PoS Module

### ISSUE THREAD

**Issue by olamide2** [frappe/erpnext#10305]
Cashier should not be able to submit PoS Invoices till the payment by tender is completed (Cash/Card/Cheque). This is standard in all retail systems. Full payment must be made before submission and printing.

A fourth payment option can be credit/payment on account, but use of this option should be restricted by rights.This can be used to make credit transactions through the PoS. But the key factor is that no transaction should be submitted via PoS till payment is taking in full by any of the four tender types.

This is critical

**Comment by olamide2** [comment]
I do hope this issue will be addressed. It is one of the requirements to making the PoS retail ready

Regards

**Comment by Olawale1** [comment]
I believe this can be achieved by adding an option in the POS Profile to 'Allow User to Accept Part Payment'

If this option is checked, the system works as it is currently

If the option is not checked then there should be a validation that amount(s) entered in the Mode of Payment section is equal to Total Amount of Invoice

Kind regards,
