### ISSUE TITLE
Brand wise Item Price List

### ISSUE THREAD

**Issue by stepsibg** [frappe/erpnext#10302]
I would like to have a Brand wise Item Price List.  It is not available in any of these document or report section.

Report: Item Price - Item-wise Price List Rate
Reports- Item Prices
Stock-items and prices - Item Price Stock.

Thanks

Junaid Hussain
Steps International Business Group
Riyadh, Saudi Arabia

**Comment by umairsy** [comment]
Can we add Brand column in the standard report Item Prices?

**Comment by stepsibg** [comment]
Any update on this?

**Comment by stepsibg** [comment]
@umairsy are you working on this?

**Comment by umairsy** [comment]
Not as of now. Issue assigned to the concerned person. Let's check if it would be feasible to add Brand column in these reports.

**Comment by rohitwaghchaure** [comment]
We have added brand in item price and will be release in version 11
