### ISSUE TITLE
Add From date to date in status

### ISSUE THREAD

**Issue by SOLOSOFTMA** [frappe/erpnext#10301]
hi all i think would be better to add from datetime to datetime within the same date in add new attendance  to give the ability to upload(from attendance machine) or create an correct in & out for a salary also the possibilities to have multiple ins & outs for the same salary in the same day (for breakups for exemple).

**Comment by umairsy** [comment]
You can add DocType for the actual hours and add Intime and Outtime as Datetime fieds.

https://erpnext.org/docs/user/manual/en/customize-erpnext/custom-doctype?
