### ISSUE TITLE
date between filter problem when language is set to german

### ISSUE THREAD

**Issue by christophKi** [frappe/erpnext#10307]
Hi, 

I think there is a problem with the filter when the system language is set to german. When i set the date filter (in german called "zwischen"), the filter is empty and after clicking on apply (in german) the result is also empty. When I set the system language to en everything is working fine. 

Also the translation is not correct. In germen apply is called "anwenden" not "Sich bewerben" 

I'm on the newest ERPNext version. For more details please look at the two images, the first with the working filter in en and the second with the bug in the filter and the wrong translation. 

ERPNext: v8.7.2 (master)
Frappe Framework: v8.6.7 (master)

Greetings christophKi

![erp-en](https://user-images.githubusercontent.com/29779413/29004748-5ebe073c-7acd-11e7-8304-8376ed100f3b.JPG)
![erp-de](https://user-images.githubusercontent.com/29779413/29004750-623c2d94-7acd-11e7-93df-762c377c859d.JPG)

**Comment by chdecultot** [comment]
Hi,
We have the same issue in French.
When you select a filter "between two dates", it is empty:
![image](https://user-images.githubusercontent.com/4903591/29369020-a92e85f4-82a1-11e7-874e-555a0e14696e.png)


In English everything works fine.

**Comment by christophKi** [comment]
Funktioniert leider noch immer nicht. Oder ist der patch noch nicht veröffentlicht?

Greetings christophKi

Installed Apps
ERPNext: v8.8.6 (master)
Frappe Framework: v8.7.10 (master)

**Comment by chdecultot** [comment]
Hi @christophKi,

The patch has been merged into the Develop branch.

I guess it is being tested extensively before a release into Master.

It should be solved in production in a few days.

**Comment by christophKi** [comment]
Great thx!
