### ISSUE TITLE
Generating PDF TimeOut Error

### ISSUE THREAD

**Issue by sumitdas4u** [frappe/erpnext#10316]
http://162.243.0.65/api/method/frappe.utils.print_format.download_pdf?doctype=Quotation&name=CACM%2F17-18%2FQTN%2F00048&format=quote%20format%202&no_letterhead=0

504 Gateway Time-out

nginx/1.4.6 (Ubuntu)

am not able to generate any pdf like quotation, purchase receipt, etc

**Comment by umairsy** [comment]
Please post your technical queries on the ERPNext community forum.

https://discuss.erpnext.com

**Comment by rohan1397** [comment]
Hey @sumitdas4u did you find any solution because I am also facing the same issue
