### ISSUE TITLE
Issue with 'mailto' tag when generate from email alert.

### ISSUE THREAD

**Issue by naim5441** [frappe/erpnext#10315]
Hi guys,

I have issue with email alert. When there are 'mailto' tag , it always get preceded by web url, hence when user click on it, it will become an invalid link. Is there any setting to override this?

Basically, when there are mailto tag in email, when we click it will open an outlook app or any default email client that we are using.

But currently,for an email that was generate from email alert,if there are any mailto tag on it, it will add the email tag with site url infront of it. Eg: sitename.com/@example.com. Hence it will open an invalid link. Supposely, it should not be preceded with site_url.com so that when we click on it , it will open with our mail client.

ERPNext Version :v7.0.63

Frappe Framework: v7.0.47

Thanks.

**Comment by umairsy** [comment]
Can you please share the exact example of Email Alert with mailto tag in it? This that field linked with the email ID field?

Request you to post technical queries on the discuss forum. https://discuss.erpnext.com
