### ISSUE TITLE
Rename "Standard Reply" to "Text Template" so that it can be used as template for other text fields like Project Template or Task Template

### ISSUE THREAD

**Issue by KanchanChauhan** [frappe/erpnext#10323]

**Comment by umairsy** [comment]
Hello Kanchan,

Hope you are doing well.

For fetching values in the rich-text-editor field, we can use Terms and Condition master. The standard reply is primarily designed for fetching values in the email dialog box.

**Comment by KanchanChauhan** [comment]
@umairsy Hi Umair. All is well. :) Totally forgot about Terms and Conditions, we can use that. Let me try.

**Comment by umairsy** [comment]
Am fine. Thanks.

I am sure Terms and Condition will be sufficient. Allow me to close this issue for now. If needed, feel free to re-open it.
