### ISSUE TITLE
Hierarchical User Permissions (aka Group Permissions)

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#10332]
Hi

There should be an option to set hierarchical permissions so that there is no need to set permissions for all child nodes as referenced in this issue: https://github.com/frappe/erpnext/issues/9411

If I give a user access to view 'Customer Group A' and Customer Groups A1 - A10 are all children of Customer Group A, then the user should be able to view them as well (if hierarchical permissions are enabled for Customer Group). Right now, we must set permissions for every single Customer Group individually 

I'm just using Customer Group as an example here. This is applicable to all nested documents (trees)

Thanks

**Comment by umairsy** [comment]
Hello Olawale,

Will be great if you can followup with the original Github Issue only, as both the issues have exactly same purpose.

**Comment by Olawale1** [comment]
Hi @umairsy 

Thanks for your response but they do not have **exactly** the same purpose! The other issue is specifically about Warehouse. I have had similar experiences in the past where issues were fixed for only the specific case when it should have been general. The most recent example is the case of Standard Reports not getting filtered according to User Permissions; only Gross Profit report was fixed even though I pointed out that it affects other reports as well!

Please advise

Thanks
