### ISSUE TITLE
BOM

### ISSUE THREAD

**Issue by lifestylesofas** [frappe/erpnext#10345]
Hi, 

In Bom i want item name should be editable. At present its not taking. example when i making Bom Item name its taking Cameroon but i want to add more names like passat, 9010 pvc-01. when i am adding these name its taking but the moment i save its only showing cameroon not the other names. plz do the needful

**Comment by tundebabzy** [comment]
Hi @lifestylesofas
Can you add screen shots and/or screen cast?

**Comment by lifestylesofas** [comment]
I HAVE SENT SCREEN SHOT TO SUPPORT@ERPNEXT.COM MAIL ID

**Comment by lifestylesofas** [comment]
any updates

**Comment by umairsy** [comment]
Demo of the issue:

![bom](https://user-images.githubusercontent.com/910238/29168458-93b23e3c-7dec-11e7-818d-da9804d68186.gif)

**Comment by lifestylesofas** [comment]
HI, 

STILL NO REPLY. HOW MUCH TIME ITS GOING TO TAKE TO SOLVE THE ISSUE......

**Comment by tundebabzy** [comment]
Hi @lifestylesofas 
Sorry for the late reply. 

As per the issue, when you enter an Item Code of an Item into the Item field, the Item Name field will automatically change to the Item Name of the Item after you save the BOM. What I mean is that the Item Name field maps directly to the Item Code of the main BOM item. It can't be changed from the BOM but only from the Item master.

If you are making similar Items like Red chair, blue chair, which only differs by colour or by just a few parameters then you should using Item Variants and create a BOM for each variant.

Now that you reported this, I admit this is confusing. Perhaps we should make the Item Name field read-only to stop the confusion. The fact that the field is editable feels like an invitation to tweak but that is not actually the case. 

I'm closing this for now but feel to voice any further concerns.

**Comment by lifestylesofas** [comment]
hi, 

in Item Master its mentioned cameroon, passat 3 seater but in item name its only taking cameroon. y

**Comment by lifestylesofas** [comment]
![image](https://user-images.githubusercontent.com/29091753/29238160-65c60d1c-7f4c-11e7-8fcf-b85e5238b381.png)

**Comment by lifestylesofas** [comment]
![image](https://user-images.githubusercontent.com/29091753/29238165-863bd46e-7f4c-11e7-9c98-1dd457b5d219.png)

**Comment by lifestylesofas** [comment]
in first screen Item its showing what the moment u press enter item name change. yyyy

**Comment by lifestylesofas** [comment]
whatever we have mentioned in item master it should take same as per u, but its not taking.

**Comment by lifestylesofas** [comment]
one product is having 2-3 names the same we have mentioned in item master.

**Comment by lifestylesofas** [comment]
but its only taking the first one its not taking after comma in item name.

**Comment by tundebabzy** [comment]
Hi @lifestylesofas 
This is expected behaviour. It's either you edit the Item Name in the Item master or make use of item variants. The text you are seeing after the comma is your item description.

**Comment by umairsy** [comment]
Amit,

If Item Name as all the details (A, B, C), then all of it is getting fetched into BOM as well. Please check.

http://imgur.com/a/sJQml

For the issue specific to your account, I will shortly access it from here and check.

**Comment by lifestylesofas** [comment]
I AM WAITING FOR UR REPLY MR. UMAIR

**Comment by umairsy** [comment]
Just checked Item in question, and found that it only has word "CAMEROON" for an item Name.

![screen shot 2017-08-14 at 4 19 47 pm](https://user-images.githubusercontent.com/910238/29268944-aee19306-810c-11e7-9f48-bdcac93cefff.png)

I just tried replicating other value in the BOM and found that it correctly fetches complete value from item master.

**Comment by lifestylesofas** [comment]
![image](https://user-images.githubusercontent.com/29091753/29269387-ca6e8168-810e-11e7-90fe-b22836baadf7.png)

Increase item name width so that complete name can appear
