### ISSUE TITLE
Assessment Result displays duplicate tables

### ISSUE THREAD

**Issue by Zlash65** [frappe/erpnext#10344]
![assessment_result_issue](https://user-images.githubusercontent.com/11695402/29110683-1c471cec-7d05-11e7-8fdf-4055fc8ca6aa.png)
Goto Assessment Plan -> Click on any plan -> Reload the page -> Click on 'Assessment Result' button.
It shows duplicate table.

**Comment by manassolanki** [comment]
Fixed via https://github.com/frappe/erpnext/pull/11543
