### ISSUE TITLE
sales cycle mapping needed

### ISSUE THREAD

**Issue by mjomane** [frappe/erpnext#10359]
as we know, sales cycle starts with quote > sales order > invoice/delivery note > payment entry.

the only document that shows a reference is payment entry. when creating sales order from quotation, the sales order does not show quotation number referenced on print out. same with invoice.

much needed feature

**Comment by umairsy** [comment]
This is primarily because the ID of preceding transaction (say Quotation) is updated in the child table of succeeding transaction (say Sales Order). You can can make this column visible in the item table to have ID of preceding transaction reflected in the Print Format.
