### ISSUE TITLE
Workflow Status not updating in the Document

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#10357]
**Workflow created for a Doctype:**

![screen shot 2017-08-10 at 2 15 18 pm](https://user-images.githubusercontent.com/910238/29162251-7ca42932-7dd6-11e7-81c6-f66e7165caf8.png)

**Document Status not updating in the doc and the list view:**

![screen shot 2017-08-10 at 2 14 31 pm](https://user-images.githubusercontent.com/910238/29162268-89815d78-7dd6-11e7-8a11-1dc6fe4cc4a8.png)

![screen shot 2017-08-10 at 2 14 37 pm](https://user-images.githubusercontent.com/910238/29162287-98fb8cec-7dd6-11e7-92aa-84f7e0901a87.png)

**Comment by rohitwaghchaure** [comment]
Fixed via https://github.com/frappe/frappe/pull/3889/files
