### ISSUE TITLE
Website Theme - Top Bar and Footer Colour not applied

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#10358]
**As defined in the Website Theme**

![screen shot 2017-08-10 at 2 37 50 pm](https://user-images.githubusercontent.com/910238/29163255-87e812f6-7dd9-11e7-9734-8c6422498af6.png)

Check Website https://alqamar.erpnext.com where it is not updating colors as per Theme. The Theme is correctly selected in the Website Setting.

**Comment by britlog** [comment]
Fonts and CSS are not applied too, it seems all theme settings are useless.
See https://discuss.erpnext.com/t/website-theme-no-more-applied-in-8-6-7/26971
