### ISSUE TITLE
Reset Password Error for User without a Password 

### ISSUE THREAD

**Issue by asmith1** [frappe/erpnext#10366]
Reset Password button on a user that doesn’t yet have a password causes a “Password not found” error and then says your account has expired. However, it works when I type the new password into the Set New Password field of the form as long as “Set Password Update Notification” is unchecked. If it is checked, the same error occurs.

**Comment by umairsy** [comment]
Issue is with the email ID of the user. What is the email ID defined for the User?

Please post this query on the forum for continued support.

https://discuss.erpnext.com

**Comment by asmith1** [comment]
Ah I see. The error occurred because the default email password had not yet been sent. Perhaps a more helpful error message would be beneficial.
