### ISSUE TITLE
Batch-wise stock reconciliation

### ISSUE THREAD

**Issue by nabinhait** [frappe/erpnext#1036]
- I have imported stock using stock reconciliation for item RM-00003 at warehouse CC Enterprises - DT
- I have assign batch number (Batch00001) to item RM-00003
  Now i am going to transfer my item from warehouse CC Enterprises - DT to  warehouse DD - DT
- It show me an error "Not enough quantity (requested: -200.0, current: 0.0 in Batch Batch00001 for Item RM-00003 at Warehouse CC Enterprises - DT as on 2013-10-11 17:29:44"
- Is there any way to assign batch number to the stock which can import from stock reconciliation. 

---- From Rohit Waghchaure

**Comment by Arundhatii** [comment]
Batch-Items, can not be reconciled using Stock Reconciliation, instead use Stock Entry
![screen shot 2017-02-23 at 3 20 16 pm](https://cloud.githubusercontent.com/assets/20164097/23253836/e8cdca20-f9db-11e6-94cf-a1e9c71e3d01.png)

**Comment by joezsweet** [comment]
@umairsy @Arundhatii can this be closed?
