### ISSUE TITLE
workflow status will not override status in list view with the new update

### ISSUE THREAD

**Issue by zubair2930** [frappe/erpnext#10362]
we had a working workflow with the workflow states updating the status in listview perfectly as per our requirements.
with the latest updates 8.7.3, this has become problematic
as it is showing the defaults states and not our defined ones as it used to do so before recent update

Please find our workflow images as reference if problem is from our side
![workflow_state](https://user-images.githubusercontent.com/30434647/29167630-e51a8b08-7dd3-11e7-8b43-22c1fc4d890b.JPG)
![workflow_state_2](https://user-images.githubusercontent.com/30434647/29167629-e5190f94-7dd3-11e7-92e1-289a80a1dced.JPG)
![capture](https://user-images.githubusercontent.com/30434647/29167786-81d7cd52-7dd4-11e7-95cb-6ab8a3cd59eb.PNG)

**Comment by umairsy** [comment]
Issue resolved https://github.com/frappe/frappe/pull/3889/files

**Comment by zubair2930** [comment]
Hi,

Thanks for your prompt response on the matter.

We are using the hosted version of the ERPNext. In the list view, it IS showing the workflow status, thanks to your attention. 

However, when we open the purchase order, it is STILL showing the status and NOT the workflow status

Please note that this problem has arisen in all forms in the list view and in the form view.

We are using workflows in other forms also and we are facing same problem over there.

Your attention on this issue will be appreciated

Regards

**Comment by umairsy** [comment]
Can you please share the screenshots related to issue? We are still trying to replicate the issue.

Please refrain creating a duplicate issue. Even if issue is closed, you can add a comment on it.

**Comment by zubair2930** [comment]
Please find attached the 
![po listview](https://user-images.githubusercontent.com/30434647/29362160-70eb098c-8293-11e7-8e91-f706e33f2099.png)
![status inside po](https://user-images.githubusercontent.com/30434647/29362161-71f82576-8293-11e7-8394-f4ccc7b5245b.png)

**Comment by rohitwaghchaure** [comment]
Fixed the issue, kindly pull the latest update and check

**Comment by zubair2930** [comment]
hi thanks a alot everyone,
issue is resolved
i went on to create a similar issue because for a long time my comment on this issue went unnoticed
Thanks once again

**Comment by umairsy** [comment]
Thanks for the confirmation. Issue closed.
