### ISSUE TITLE
Add Loan Details in the Salary Register report

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#10370]
Add Loan Details in the Salary Register report

**Comment by Judesque** [comment]
![salary register](https://user-images.githubusercontent.com/35927555/45029713-807f7680-b041-11e8-850f-eda79d67302e.png)

Just to add to this. The screenshot above is a Salary Register report.

a) Gross Pay = N300,000;
b) Pensions Deduction = N8,400;
c) Total Deduction  = N8,400;
d) Net Pay = N286,600.

But N300,000 less N8,400 = N291,600, not N286,600. The difference (N5,000) is loan deduction for the month, which is not reflected in the Salary Register report.

**Comment by kennethsequeira** [comment]
Available in v13
