### ISSUE TITLE
[Bug/Enhancement] Delete Created Batch for Cancelled "Material Receipt" Stock Entry

### ISSUE THREAD

**Issue by creamdory** [frappe/erpnext#10371]
Beginning balances for Items with Batches are opened through stock entry "Material Receipt". Though we noticed that when a "Material Receipt" record is cancelled, the batch created is still there. It make sense that the batch is also deleted for no transactions.

![batch](https://user-images.githubusercontent.com/21003054/29204740-596c8fb0-7eab-11e7-9b08-978e93b644f1.gif)

**Comment by kickapoo** [comment]
Via hook.py customization:

```json
doc_events = {
	"Stock Entry": {
		"on_cancel": "newmatik.api.hooks.delete_batch_entry",
	}
}

```


```python
def delete_batch_entry(stock_entry, method):
	if stock_entry.purpose == 'Material Receipt':
		for d in stock_entry.get("items"):
			frappe.db.sql("""delete from `tabBatch` where name=%s and item=%s""",(d.batch_no, d.item_code))
			frappe.db.commit()
```
