### ISSUE TITLE
Bug - Pricing rule discount conflicting with item discount

### ISSUE THREAD

**Issue by drthilina** [frappe/erpnext#10372]
Hi,
    I have a standard discount set on all our items. now I want to give a special discount to one of our clients. I setup a pricing rule but system doesn't allow me to save.

Item discount
![image](https://user-images.githubusercontent.com/29944021/29206266-d0cf20ca-7e9e-11e7-95dc-6379e6ddc5d8.png)

Pricing rule discount
![image](https://user-images.githubusercontent.com/29944021/29206274-e2efe8ca-7e9e-11e7-9ec4-97f30c7dd489.png)

Error saving
![image](https://user-images.githubusercontent.com/29944021/29206310-0a82b39a-7e9f-11e7-8e03-0da94052d78b.png)

**Comment by umairsy** [comment]
Hello,

This is a validation message. If you are applying 27.5% discount from Pricing Rule, then the Max Discount mentioned in the Item master should be more than that. The Max Discount mention in the Item master will be given highest priority in terms of validation the discount entered in the transaction.

**Comment by drthilina** [comment]
@umairsy , Doesn't this seem odd??? during seasonal promos we want to give customers additional discount, based on what you are saying I need to alter all of the items discounts and then switch back once the promo is over.

Any plans you might re-consider the Pricing rule use case?

**Comment by umairsy** [comment]
You can bulk update value in the Max Discount field using Bulk Update feature in ERPNext.

https://www.youtube.com/watch?v=pDDhR-D45eI

**Comment by drthilina** [comment]
Leaving the item master Discount at 0 and defining it through Pricing Rule is useless as the Pricing rule applys a constant value, leaving no room for user to set something inbetween 0 << Max Discount...

@umairsy ,
I checked the video thank you. but this method is prone to errors and have to be handled by a experienced person, whereas Pricing rule can be such a powerful feature if the use case is re-visited override item master discount.

**Comment by drthilina** [comment]
This feature is something I'm looking forward in #10190
