### ISSUE TITLE
Sales Order to Production Order - Fetch Manufacturing Items from Packing List

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#10381]
Currently, when we create Production Order from Sales Order it fetches item from Sales Order Item table only. It should also check Item in the Packing List (fetched from Product Bundle). If a Packing Slip has a Production Item (one with BOM), then it should be shown in the modal when creating Production Order from Sales Order.

![screen shot 2017-08-11 at 6 32 58 pm](https://user-images.githubusercontent.com/910238/29214066-84827d32-7ec3-11e7-91b8-3cd2534c254f.png)

**Comment by hdtmartin** [comment]
The system is now fetching the items in the packing slip. However, when the Make button is clicked, an error stating, "Sales Order XXXX is invalid" is displayed.

![poerr1](https://user-images.githubusercontent.com/26181150/30324144-90b762d2-97f2-11e7-9f91-66f2c268d30b.JPG)
![poerr2](https://user-images.githubusercontent.com/26181150/30324147-90cf428a-97f2-11e7-96c8-e06f0f501413.JPG)
![poerr3](https://user-images.githubusercontent.com/26181150/30324148-90d5d2bc-97f2-11e7-9f04-a9315ab020ac.JPG)
