### ISSUE TITLE
Quantities should be Ints not Floats

### ISSUE THREAD

**Issue by asmith1** [frappe/erpnext#10384]

**Comment by tundebabzy** [comment]
Hi @asmith1
Please give some context.

**Comment by asmith1** [comment]
Oh sorry. The quantities of items, like Quotation Item, Sales Order Item, Supplier Quotation Item, Sales Invoice Item, etc. Should be of type Int rather than type Float, because there cannot  be fractions of items in inventory. When I try to change this in customize form, it does not give me the option to do so.

**Comment by bcornwellmott** [comment]
You can have partial quantities. I could have 2.25 meters of string, 3 kg of salt, etc.
