### ISSUE TITLE
LDAPS support for ERPNext?

### ISSUE THREAD

**Issue by adamsbt** [frappe/erpnext#10392]
I have ERPNext working with the LDAP server (ldap://domain.name:389), but I need to move to LDAPS for password encryption.

When I change the server to ldaps://domain.name:636, ERPNext gives an error message: "Incorrect UserId or Password"

LDAPS works with other applications, but not ERPNext.

Is it supported, I can not find references in the documentation?

Thanks,
Brian

**Comment by mbauskar** [comment]
@adamsbt,

please check https://erpnext.org/docs/user/manual/en/setting-up/integrations/ldap-integration

**Comment by adamsbt** [comment]
So no LDAPS:// support (SSL or TLS encryption of password)?
