### ISSUE TITLE
Sales Analytics Charts not showing daily/weekly report

### ISSUE THREAD

**Issue by LifeP** [frappe/erpnext#10399]
Sales Analytics hides the show chart button when on selecting weekly and daily.
Use case - To review only a week/month's performance.

It would be better to show warning that data may be too big, rather than hiding the Show Chart button  altogether, if this is to protect from errors due to limit on amount of data.

**Comment by sharmanakul** [comment]
report interface has changed since this issue was created. Charts for any frequency can be visualized without clicking any button.
