### ISSUE TITLE
Improvement for self-postbacks in product_page.js

### ISSUE THREAD

**Issue by joelios** [frappe/erpnext#10390]
In the product_page.js is a code wich shall prevent of self-postbacks, starts in line 76:
`if (window.location.search.indexOf(item_code)!==-1) { return; }`

This code does not allow, that variants of an article has an article number like a substring of the other variants article number. For example, Variant # 1 = 12345 and variant # 2 = 12345-1 causes errors in the webshop

A more elegant solution would be:
`if (window.location.search == ("?variant=" + item_code)) { return; }`

**Comment by netchampfaris** [comment]
Can you send a PR for this?

**Comment by joelios** [comment]
Sure, i'll send it as soon as possible

**Comment by joelios** [comment]
PR #10448 is created
