### ISSUE TITLE
Stock Entry List not getting filtered according to User Permission

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#10408]
Hi

I have restricted a user's ability to view Stock Entries based on if warehouse is permitted. The user is however still able to view the entire list. When he tries to open a Stock Entry for which warehouse is not permitted, he gets an 'insufficient permission' error

This makes for very bad User Experience. The user should only see documents for which he is permitted in the list. If he is not permitted to view the document, it should not appear in the list!

Please fix

Thanks

**Comment by umairsy** [comment]
Stock Entry has multiple link field of Warehouse master. Do you want to apply user permission on all the Warehouse link field? If no, then for the field on which permission is not to be applied, then did you check Ignore User Permission for that field?

**Comment by Olawale1** [comment]
Hi @umairsy

Yes I did. I ensured there was only one Warehouse field being considered but the issue is still there!

Thanks

**Comment by Olawale1** [comment]
Hi

Could someone please update the tag on this? I answered the question about a week ago

Thanks

**Comment by umairsy** [comment]
@Arundhatii can you please try to replicate this issue?

**Comment by Olawale1** [comment]
Hi 

Any update on this please?

Thanks

**Comment by jaichavan** [comment]
Hello, @Olawale1 
does the issue persist with the latest version [ v11.0.3-beta.34 () (staging) ] and the upgraded User permissions?
Awaiting your response.
