### ISSUE TITLE
Salary Register Report

### ISSUE THREAD

**Issue by Admakbs** [frappe/erpnext#10402]
Dear Team 
i am facing issue in Salary register when i am using the software in arabic, the issue is there is no data in the report when i use system in arabic language, i checked the report in English and it is works properly when i use the software in English 
![salary register - arabic - error](https://user-images.githubusercontent.com/29948389/29286754-c1678ad8-813b-11e7-8a77-6db251e84450.PNG)
![salary register - english](https://user-images.githubusercontent.com/29948389/29286755-c1739e2c-813b-11e7-8126-ac4eaf1c6dd2.PNG)

**Comment by umairsy** [comment]
Am not able to replicate this issue in my test account. Do you see any error message in the browser console when checking Sales Register in arabic? If yes, please post that error message on the discuss forum.

https://discuss.erpnext.com
