### ISSUE TITLE
Export Single company data from Multiple Company Instance 

### ISSUE THREAD

**Issue by mosabamf** [frappe/erpnext#10406]
If I've two companies in one instance and I need to separate them into two instances, how can I export data for only one of the two companies??  the company selection in data import tool is not there and when I export data for DocType it exports relevant data for all companies and no choice to select specific company,

**Comment by jaichavan** [comment]
Hello, @mosabamf 
Thanks for reaching out. We shall address this with our dev team and revert when we have an update.
