### ISSUE TITLE
[Paid Development] little things on ecommerce

### ISSUE THREAD

**Issue by elvise** [frappe/erpnext#10412]
HI to all, i want pay for integrate this functionality on ecommerce:
<img width="1129" alt="ecommerce 4" src="https://user-images.githubusercontent.com/5269577/29324051-2336b0d4-81e3-11e7-9786-77116d3dd288.png">
<img width="1277" alt="ecommerce 3" src="https://user-images.githubusercontent.com/5269577/29324049-232fbd42-81e3-11e7-8ae1-811417852ce8.png">
<img width="1109" alt="ecommerce 2" src="https://user-images.githubusercontent.com/5269577/29324050-23348034-81e3-11e7-9561-157877453517.png">
<img width="1279" alt="ecommerce" src="https://user-images.githubusercontent.com/5269577/29324048-232b7386-81e3-11e7-879f-dd4ff7d6b6b2.png">

Thanks to all :-)

**Comment by rmehta** [comment]
@elvise did you get these fixed?

**Comment by elvise** [comment]
@rmehta not yet :-(

**Comment by federicocalvo** [comment]
Hi @elvise, any news for this? is excellent!

**Comment by tech4kstudios** [comment]
Hi @elvise, any updates on this feature? Been a few years now! Would be thrilled to see it implemented into ERPNext.
