### ISSUE TITLE
Buttons Show up Twice on Customer

### ISSUE THREAD

**Issue by asmith1** [frappe/erpnext#10411]
Whenever I convert a Lead to a Customer, all of the buttons appear twice at the top of the customer, including the built-in ones and my custom built buttons. This happens only right after the new customer is created and is fixed upon refresh.

**Comment by tundebabzy** [comment]
Hi @asmith1
Thanks for reporting this. I suspect that this has to do with your custom code. Let's troubleshoot this on the forum (https://discuss.erpnext.com) . If we can confirm this is a bug we can then reopen.
