### ISSUE TITLE
workflow status will not override status inside the forms the new ERPNext update

### ISSUE THREAD

**Issue by zubair2930** [frappe/erpnext#10418]
Dear All, 

my issue is related to the issue #10362 
1) in that issue i raised the concern for purchase order but now we have noticed that this problem is coming in all the forms i.e. workflow states are not overriding the status in list forms in all the forms.

2) workflow status will not update status INSIDE forms. Again this problem is arising after the latest update but was not before the update

P.S. Please do not close the issue. Problem is resolved or not the guy who commented first closes the issue and user who raised the issue remain dissatisfied.

**Comment by umairsy** [comment]
Duplicate issue
