### ISSUE TITLE
After deleting a payment entry, Customer / Supplier Balance not updating

### ISSUE THREAD

**Issue by nazakli** [frappe/erpnext#10415]
Hi.

I deleted a submitted payment entry with "Cancel" and "Delete" steps. but Supplier balance didn't updated.

Is there any way to calculate payment history of Supplier balance ? 

![after deleted payment entry](https://user-images.githubusercontent.com/7967396/29336656-2bc8df7c-8217-11e7-9fa8-7d48aee5f82b.png)

**Comment by umairsy** [comment]
Please clear cache of your ERPNext account and then check.

For a complete history, check General Ledger report for the Supplier/Customer.

Please post your queries on the community forum. Github Issue is primarily used for tracking bugs and feature suggestions.

https://discuss.erpnext.com
