### ISSUE TITLE
Quality Inspection for production order

### ISSUE THREAD

**Issue by LifeP** [frappe/erpnext#10428]
1. Should have option to select reference type "production order" in quality inspection for in process.
2. Option to enable workflow where manufacture entry is made only after inspection is done.

**Comment by m-delvalle** [comment]
Relevant:

https://github.com/frappe/erpnext/issues/2273

**Comment by umairsy** [comment]
@LifeP Thanks for the suggestion. Request you to followup for this feature via #2273 as it is for the same purpose.
