### ISSUE TITLE
Email can't be set as Read or Unread

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#10430]
In the Email Inbox, Mark as Read and Unread doesn't work. No error in the console.

![screen shot 2017-08-17 at 12 51 07 pm](https://user-images.githubusercontent.com/910238/29400397-e73d3c60-834a-11e7-8eeb-3b6a9d9a67f0.png)

**Comment by mbauskar** [comment]
@umairsy,

After Mark as Read / Unread please refresh the listview, without refresh the email will not be marked as Read/Unread.
