### ISSUE TITLE
Barcode scanner system should also fetch batch details

### ISSUE THREAD

**Issue by AravindPranera** [frappe/erpnext#10436]
Umair,

While scanning the Barcode item physically, now the system is fetching the details of item master data only.
We have to choose the batch manually. But our requirement is while scanning the barcode item, it also should fetch the batch details of item, don't need to enter the batch manually. We can give the batch details in Barcode sticker itself. Kindly do needful.

Thanks,
Aravind.

**Comment by umairsy** [comment]
Aravind,

If you have Barcode for Batch ID as well, then you will just need to put the cursor in the Batch ID field, and then scan the Barcode for batch ID. For now, we cannot fetch Batch manually, as there can be multiple batch for one item.

**Comment by AravindPranera** [comment]
Umair,

We created a custom field for Batch barcode in Batch Master and we updated
the barcode data in that field. After that in sales invoice batch field if
we scan the barcode, it is fetching wrong batch id.
Kindly do needful.

Thanks,
Aravind.



Pranera Services & Solutions.
Tiruppur.
