### ISSUE TITLE
Tree Structure for Help Category (Knowledge Base)

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#10433]
Hi,

It's difficult to utilize the Knowledge Base functionality as Help Articles cannot be properly categorized based on the current singular structure. Please add a Tree Structure for Help Category

Thanks

**Comment by umairsy** [comment]
Hello,

I felt the same, but I suggest you give new design sometime. For now, you can also consider google search for the help article.

**Comment by Zlash65** [comment]
What kind of tree-structure are we talking about here ? Categorize help-articles in a tree structure based on help category ?

**Comment by Olawale1** [comment]
Hi @zlash65

That is exactly correct 

Thanks

**Comment by Olawale1** [comment]
Hi @Zlash65

Trust you're doing great. Any update on this?

Cheers
