### ISSUE TITLE
Multiple tags not saving.

### ISSUE THREAD

**Issue by Arundhatii** [frappe/erpnext#10445]
Reported via https://discuss.erpnext.com/t/tags-are-auto-deleting/27056 
Unable to add multiple Tags in item.
In a saved version of item A already has three assigned tags, but when I add another tag to the list and either save item A again or leave the page all pre-existing tags delete and the additional tag remains

![tags issue](https://user-images.githubusercontent.com/20164097/29419699-65920608-838d-11e7-88bf-f19b253380e8.gif)

**Comment by tundebabzy** [comment]
Hi @Arundhatii
This has been reported earlier in #10403
