### ISSUE TITLE
Impossible to find gender: Male in fresh install

### ISSUE THREAD

**Issue by jodeq** [frappe/erpnext#10449]
![image](https://user-images.githubusercontent.com/7780466/29433377-3640bee6-839f-11e7-8a45-15e14210a534.png)

ERPNext: v8.8.3 (master)
Frappe Framework: v8.7.8 (master)

Installation was done in french, it should be the problem

**Comment by jodeq** [comment]
Error when creating new employee

**Comment by krismas** [comment]
+1

**Comment by umairsy** [comment]
@Arundhatii can you please try to replicate it by creating a test account in french?

**Comment by jodeq** [comment]
For information, my tabGender contains only these lines : 
```
Autre     2017-08-16 23:25:57	2017-08-16 23:25:57	xxx	xxx	0				0	Autre				
Féminin   2017-08-16 23:25:57	2017-08-16 23:25:57	xxx	xxx	0				0	Féminin				
Masculin  2017-08-16 23:25:57	2017-08-16 23:25:57	xxx	xxx	0				0	Masculin				```

**Comment by mbauskar** [comment]
@jodeq,

Tried to replicate the issue, I am able to create new Employee without any error

![issue](https://user-images.githubusercontent.com/11224291/30263582-158e4fda-96f3-11e7-959a-af3ceea5fd80.gif)

Can you please share the traceback from browser's console?

**Comment by jodeq** [comment]
Issue can be closed, it works now, I think an update resolve this.
Thanks for your help.
