### ISSUE TITLE
Mode of Payment not showing for Invoices with linked Payment Entry

### ISSUE THREAD

**Issue by dhav-d** [frappe/erpnext#10459]
In the sales register/ gst register the invoices which are linked to a payment entry the mode of payment shows empty field.
It should show the 'mode of payment' value of the payment entry for the sales invoice too.

**Comment by nick9822** [comment]
@dhav-d 
Its a standard behavior, the mode of payment within Invoice is used for quick payments (i.e POS).
If you are making payment via Payment Entry system will have a link reference in the Invoice to Payment Entry.

**Comment by dhav-d** [comment]
But when we are seeing a sales report wouldn't it be better to see the mode of payment. because currently it looks like an unpaid invoice in the sales report.
Blank field (in mode of payment column) = payment due
defined field = paid invoice as POS or as adv/post dated payment

**Comment by nick9822** [comment]
Single invoice can have multiple payment entries with different mode of payments to it, so its not possible to show that in a single field.

**Comment by dhav-d** [comment]
But when we are seeing a sales report wouldn't it be better to see the mode of payment. because currently it looks like an unpaid invoice in the sales report.
Blank field (in mode of payment column) = payment due
defined field = paid invoice as POS or as adv/post dated payment

**Comment by dhav-d** [comment]
they already show it in normal POS entries where mode of payment is part cash, part card

**Comment by dhav-d** [comment]
please update this post as "report" - "user experience" / "user interface"

**Comment by umairsy** [comment]
Hello,

In the Sales Invoice, value in the Payment Table is only updated for POS invoices. If you create a Payment entry against Sales Invoice by creating Payment Entry, then values of Payment Entry is not updated in the Payments table of the Sales Invoice.

The purpose of the Sales Register report is to view the total income booked in a given time period. Even if Sales Invoice is not paid, the income is booked for it.

To check Sales Invoice without the payment status, please refer to other reports like Account Receivable or create a custom report on Sales Invoice doctype.
