### ISSUE TITLE
SETUP WIZARD ERROR setting up manufacturing for INDIA

### ISSUE THREAD

**Issue by dhavalfuletra** [frappe/erpnext#10451]
# **1. version number ** 
Installed Apps
ERPNext: v8.8.3 (master)
Frappe Framework: v8.7.8 (master)

# **2. steps to reproduce**
Well i downloaded Latest Erpnext vm official 
updates all well 
then started to login as u can see in gif bug1 
as i am indian i started selecting india as country and manufacturing business
but see the whole gif whats wong 
i have searched every part of erpnext discuss tried everthing 
as follows 
used http timeout seconds by increasing 
ticket and unticked last two option but everthing failed 
finally check both gif 
when i setup with other country in gif2 it worked whoooo
but there is a bug by selecting india 
![bug1](https://user-images.githubusercontent.com/31123073/29447078-a2eb09de-840d-11e7-8f6b-fe9f4311a701.gif)

# **3. Actual behavior**
well as i explained bug is that selecting country India setup wizard fails first it timeout, then it shows setup complete but when logged in again it takes to setup wizard again it keeps repeating it fails
but when i select other country like usa it worked check in gif 2
this is new vm installed latest erpnext by selecting usa country in erpnext vm and it success 
![now changes country](https://user-images.githubusercontent.com/31123073/29447290-ce4c39da-840e-11e7-8e76-6861f6a7825b.gif)

# 
**4. Expected behaviour**
well there should be no error in setup wizard like i select usa it all goes well setwizard sucess
and when i tried with our india country there is error and bug
i think so its due to some GST update or something for india ??
i am not a developer dont know what prob but please solve asap 
sorry for my bad english 
and yes
# **I HAVE USED EVERY NEW UPDATED ERPNEXT VM IN EVERY STEPS OF SOLVING BUT IT FAILS FOR INDIA MANUFACTURING**

**Comment by dhavalfuletra** [comment]
OMG NO RESPONSE FOR THIS BUG

**Comment by Arundhatii** [comment]
This seems to be working fine in the test environment for cloud hosted instance.

**Comment by jaichavan** [comment]
Hello, @dhavalfuletra does the issue still persist?
