### ISSUE TITLE
HSN Code Based Taxation

### ISSUE THREAD

**Issue by troin** [frappe/erpnext#10462]
Feature to set HSN Code Based GST rate is necessary as government is changing Tax rates frequently.
It is not possible to update each and every item.
Depending on transaction type we as per "Tax rules it should pick IGST or CGST+SGST

A provision for cess with HSN code may be required for certain products

**Comment by troin** [comment]
Please remember people have to set the hsn code properly for each item sometimes 4 digit HSN code may be 28% and when you consider full 8 digit with subchapter it may be exempted or 18%
When programming this feature you have to give 8 digit code only
Also the item based tax rate will over ride all other settings if they are set, is that fine

**Comment by xickomesquita** [comment]
Maybe it can use UNSPSC...
