### ISSUE TITLE
Installation wizard: users not applied

### ISSUE THREAD

**Issue by lasalesi** [frappe/erpnext#10460]
When the installation wizard is executed and further users are specified, they are not applied to the system.

Affected:

    ERPNext: v8.8.3 (master)
    Frappe Framework: v8.7.8 (master)

Steps to reproduce:

* install a fresh ERPNext from the install.py script with --production
* follow wizard. when asked for further users, enter more users.
* complete wizard
* log in to ERPNext and go to Setup > Users.

Actual behaviour:

* only first user is present (not others)

Expected behaviour:

* all users should be in the user list.

In the affected version, the avatar of the first user was also not applied (worked in previous versions).

**Comment by rohitwaghchaure** [comment]
Hi @lasalesi 
Can you please check role permission manager for the User doctype, check whether apply user permissions has enabled against the system manager role

**Comment by lasalesi** [comment]
Hi @rohitwaghchaure,

apply user permissions is not enabled:
![erpnext - roles on user for system manager](https://user-images.githubusercontent.com/26505250/29497847-2ac80184-85f0-11e7-8105-8acb48e2fe41.PNG)

**Comment by rohitwaghchaure** [comment]
Hi @lasalesi 

Pull latest version 9 and check, we have added new setup wizard in version 9
