### ISSUE TITLE
Optimization of Print Paper space of Invoices/Purchase orders

### ISSUE THREAD

**Issue by homemaint** [frappe/erpnext#10461]
I am using ERPNEXT since last four months and all thing going fine except print formats. In my ERPNEXT, a lot of paper space getting wasted and invoices ends up in two to three pages and same with purchase orders. 
[HM-TINV-0817-00001 sample.pdf](https://github.com/frappe/erpnext/files/1236087/HM-TINV-0817-00001.sample.pdf)

Please guide me to solve this issue.
regrads,

Pankaj Gupta

**Comment by nick9822** [comment]
@homemaint 
It looks like header and footer is not set correctly, try to check without header.

**Comment by sharmanakul** [comment]
Check the print settings and try to make it compact with the configuration. 
you can also create custom print formats.
