### ISSUE TITLE
Raw Materials supplied in multiple batches for a subcontracted item's Purchase Receipt

### ISSUE THREAD

**Issue by toofun666** [frappe/erpnext#10467]
There is one subcontracted semi-finished item with raw materials supplied to the supplier. One of the raw materials are transferred to the supplier in multiple batches. Now that the purchase receipt is in process, supplied raw materials are listed but lines cannot be broken into different batches so that appropriate batch is consumed by the purchase receipt.

**Comment by nick9822** [comment]
@toofun666 
Please elaborate your issue with screenshots. are you able to manually split item quantities with respect to batches?

**Comment by toofun666** [comment]
The BOM for the subcontracted item is:
subcontracted_item
|- 0,7g item_1
|- 2,3g item_2
Both item_1 and item_2 are batch controlled. Subcontracted_item is also batch controlled. For a purchase order the following is transferred to the supplier:
Stock Entry_1
item_1 25kg batch A
item_2 230kg batch X
Stock Entry_2
item_1 45kg batch B
The same lack of design causes two stock entries to be created against the purchase order.
Now that the subcontracted operation is complete we would like to receive the 100.,000 Nos of subcontracted_item but it is not possible via a single Purchase receipt. There need to be two purchase receipts to consume 25kg of item_1 batch A and another to consume the other batch of item_1.

I hope this helps.

**Comment by yavinmaster** [comment]
Has there been any progress on this issue?  I have discovered the exact same problem in ERPNext: v10.1.48 (master) / Frappe Framework: v10.1.45 (master).

**Comment by jaichavan** [comment]
Does the issue persist? @toofun666

**Comment by toofun666** [comment]
> Does the issue persist? @toofun666

Did not have the chance to use that scenario again. FYI
