### ISSUE TITLE
Invalid Format of md5 signature in Downloads Page

### ISSUE THREAD

**Issue by rolandog** [frappe/erpnext#10478]
The md5 file only has the hash,

> 81ec27db72eaccacc915e1285e01b0d4

But the proper format should be:

> 81ec27db72eaccacc915e1285e01b0d4 ERPNext-Production.ova

**Comment by netchampfaris** [comment]
Source? I don't think this is a problem. You can use the current format to verify the md5 anyway.

**Comment by rolandog** [comment]
Of course, here is a screenshot.

![erpnext-md5-unformatted-md5-vs-formatted](https://user-images.githubusercontent.com/12400926/29629864-e9e1d192-87ff-11e7-8b8a-2723af6ff67b.png)

Maybe it's because I'm using Bash in Windows, even though I've been able to do most things interchangeably; I'll try replicating when I get back from work at a Linux machine.

**Comment by rolandog** [comment]
Sorry for taking too long to validate.

I just tested in my Ubuntu 17.04 box. I can confirm that I get the same message when performing the md5 check:

![screenshot from 2017-09-15 17-56-59](https://user-images.githubusercontent.com/12400926/30506331-abd7442e-9a40-11e7-89e2-ab227bece42b.png)

I would suggest checking these sites for some overview on best practices:

* https://www.qubes-os.org/downloads/
* https://getmonero.org/downloads/
* https://help.ubuntu.com/community/HowToSHA256SUM

Those practices include listing a tutorial on how to verify, having hashes less vulnerable than md5, and files signed by an official signing key, and a public key with which to verify that the files have a good signature.

In ERPNext's case, the content of the md5 file should be the output of the md5sum command:

```
$ md5sum ERPNext-Production.ova
e0081aee3a933525bc2638a6bfce6018  ERPNext-Production.ova
```

But the md5sum could also be available to copy and paste in the downloads section.

**Comment by jaichavan** [comment]
@rolandog Thanks for your kind words.
