### ISSUE TITLE
Allow on submit for valid till date in Quotation.

### ISSUE THREAD

**Issue by Arundhatii** [frappe/erpnext#10479]
Reported by https://frappe.erpnext.com/desk#Form/Issue/WN-SUP27420

Our sales personnel ignored that new field, and let it default to the 1 month after transaction date - and we are now stuck with quotations that have unreasonable "valid to" dates.

**Comment by umairsy** [comment]
Valid Till field should not be allow on submit field. That will defeat the purpose on the field.
