### ISSUE TITLE
convert between UoM

### ISSUE THREAD

**Issue by hwinkel** [frappe/erpnext#1047]
UoM of the same class (weight, time, units etc) should able to convert to each other. I.e. I can buy something in KG and sell it in g. Both is weight, conversion  would be 1000. or time is measured in minutes but sold in hours. Just have a look in OpenERP for inspiration....

**Comment by nabinhait** [comment]
Currently you can purchase an item in any UOM and system maintains inventory in the default stock UOM. In the sales process though, you can only sell the item in the stock UOM. The feature for selling in multiple UOM is in our immediate to do list, you can expect the feature in 1/2 months timeframe.
