### ISSUE TITLE
HR: Attendance

### ISSUE THREAD

**Issue by gulelat** [frappe/erpnext#10475]
Is there a possibility to integrate ERPNext with  Bio-metric attendance devices like fingerprint?

**Comment by conelco** [comment]
Interested to have same information  about fingerprint issue

**Comment by umairsy** [comment]
Hello,

This feature is not available out-of-the-box currently in ERPNext. Since each Bio-metric software as it's own backend system and will need a connector. Do let us know if you would like to sponsor to integrate your current Bio-metric application with the ERPNext.

**Comment by gulelat** [comment]
Great and appreciate your response, yes we need and API or something else
to  integrate and make full to work with HR and finger print of some
specific for employee automated attendance log  pulling? you don't think
so? if you have something to say about this things please I want to hear
from you.

Gulelat Abebe
SOEEC (Computer Science Eng.)
Adama Science and Technology University
Adama, Ethiopia
Phone +251913357309

**Comment by gulelat** [comment]
Great and appreciate your response, yes we need and API or something else
to  integrate and make full to work with HR and finger print of some
specific for employee automated attendance log  pulling? you don't think
so? if you have something to say about this things please I want to hear
from you.

Gulelat Abebe
SOEEC (Computer Science Eng.)
Adama Science and Technology University
Adama, Ethiopia
Phone +251913357309

**Comment by philliy** [comment]
xas

**Comment by philliy** [comment]
you dont need api you can use webhook in erpnext to integrate it add nessesery columns in ur database to ur doctypes and it will work any questions write me 
filimongebru@live.com

**Comment by gulelat** [comment]
thank you
but how? little detail if give me please?
___________________________________
Gulelat Abebe
SOEEC (Computer Science  & Eng.)
Adama Science and Technology University
Adama, Ethiopia
Phone +251913357309

**Comment by philliy** [comment]
we have one application wich is called gize works in frappe frame work
basically we cant share our code with u but we can help you how here is how you can do it

we use zk finger print attendance system
in erpnext there is a doctype which is called webhook so the mashine uses
tcpip to connect to the webhook so client id ip adress and port adress
can be filled there using the api translator sdk you can call each column of
your database to your attendance module in the hr .u also need to create
some fields same with the zk used data stracture then you can fetch the data to your erpnext attendance report
here is one example if you can understand the concept its pretty easy ...
https://www.youtube.com/watch?v=hLFfDlFtDK4
________________________________

**Comment by karthikeyan5** [comment]
This is now possible in V12...

Related Links:

1. [A Note on Biometric Integration in ERPNext](https://github.com/frappe/push-biometric-erpnext/wiki/A-Note-on-Biometric-Integration-in-ERPNext)
2. [ERPNext Auto Attendance Introduction](https://erpnext.com/docs/user/manual/en/human-resources/auto-attendance)
3. [Documentation for ERPNext Auto Attendance Settings in Shift Type](https://erpnext.com/docs/user/manual/en/human-resources/shift-management#2-features)
4. [Python Script to poll for biometric logs and push to ERPNext via API](https://github.com/frappe/push-biometric-erpnext) (Refer to repo’s readme for more info).
