### ISSUE TITLE
Task created inside projects doesnt inherit the company

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#10477]
The tasks created inside project doctype doesnt inherit the company that the project belongs, so when I apply user permissions users can see the project but not the tasks.

**Comment by umairsy** [comment]
In the new Task, when Project is selected, Company should be fetched from the Project master.

**Comment by chdecultot** [comment]
Hi,
I just re-tested it and the company is correctly fetched into each new task.

Therefore I'm closing this issue.
