### ISSUE TITLE
None of the links work on erpnext/erpnext/docs/user/manual/en/customize-erpnext/kanban-board.md

### ISSUE THREAD

**Issue by asmith1** [frappe/erpnext#10476]
It brings me to a github "Page Not Found" page

**Comment by umairsy** [comment]
Hello,

Links seems to be broken. Are you looking for the following link?

https://erpnext.org/docs/user/manual/en/customize-erpnext/kanban-board?

**Comment by asmith1** [comment]
Oops! Yes, thank you!
