### ISSUE TITLE
Project Templates

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#10488]
Hi,

It would be really helpful for us to have Project Templates in ERPNext. The 'Duplicate' feature is helpful in some scenarios but a proper template (similar to what we have for Appraisals in the HR module) would add a lot more value 

With this feature, we can create any repetitive group of tasks (like weekly work schedules etc) as Project Templates. Every user/employee can then automatically create a Project (along with all associated Tasks) on a weekly basis or as required

There should also be optional restrictions that do not allow users to delete or add Tasks in the Projects generated from Templates

Also, since this feature would make Projects much more versatile in its application, the Project Type options will not suffice. We should have a Project Category/Group option instead and it should be a tree structure just like Item Groups. I'll open a separate issue for this

Thanks

**Comment by umairsy** [comment]
Thanks. Have heard about this feature suggestion multiple times. How about creating a Github Issue for it, with Bounty. Let's see if we can crowd-source this feature.

For now, please duplicate an existing Project to create new one faster.

**Comment by kennethsequeira** [comment]
Project Templates added in v12

https://docs.erpnext.com/docs/user/manual/en/projects/project-template
