### ISSUE TITLE
While Importing BOM Items, from "Get Items from BOM" in Material Request creates a Blank Entry.

### ISSUE THREAD

**Issue by aaimaawebs** [frappe/erpnext#10496]
I had noticed that, While Importing BOM Items, from "Get Items from BOM" in Material Request creates a Blank Entry.

Let's have a look at a screenshot.
![bug-material-request-when-ge-items-from-bom](https://user-images.githubusercontent.com/25567939/29561624-c6c3c7d0-8753-11e7-9f61-243101f1dc70.PNG)

**Comment by tundebabzy** [comment]
Fixed in #10555
