### ISSUE TITLE
Tax Details for each item needed for ITEMISED PURCHASE REPORT and GST ITEMIZES PURCHASE REGISTER

### ISSUE THREAD

**Issue by agwldeepak** [frappe/erpnext#10492]
The GST Itemized Purchase Register does not show the tax (CGST, SGST OR IGST) , tax rate and the Tax Amount. It will be great if this feature can be added at the earliest since lot of manual work has to be done by the accountant if this is not there. 
Pretty much go through every bill manually and update the values in the Excel Sheet exported from the system.

**Comment by nabinhait** [comment]
This has been added in today's release
