### ISSUE TITLE
Alternate/Substitute Line Items in BOM for sub contract manufacturing cycle (Paid)

### ISSUE THREAD

**Issue by jigneshpshah** [frappe/erpnext#10499]
Please let me know the quotation for the said paid feature.
 
Use case is for alternate line items in subcontracting in manufacturing 

Alternate/Substitute Line Item is an item which is alternate/substitute aginst a particular line item for a BOM (based on application/end usage).

Example : BOM (Finished Good) = FG PC-Corei5, Monitor 18.5inch
BOM Line Items - qty 
1) Intel Processor Corei5- 1
2) Monitor Samsung 18.5 (Alternate Items - LG, Dell ) 
2) Keyboard - HP (Alternate items TVS Gold, Microsoft) 
3) Mouse Optical -Logitech ( Alternate Items iBall, Dell)

While adding line items in BOM we need to add alternate line items against a particular line item and that group of alternate should be linked by BOM Line Item Number# (e.g. BL2), but its effect should be handled across all relevant doctypes, reports, modules for e.g.  BOM costing ,BOM Browser, Purchase Order, Material transfer for sub contracting, Purchase Receipt 

Please find the images/screenshot attached depicting the desired changes for the alternate item feature in some of the prominent screens of the cycle.

**1) BOM**
![1_a_bom_sc](https://user-images.githubusercontent.com/4900815/29563382-edc7895a-875a-11e7-925a-6ea33fb48e72.PNG)

**2) BOM Browser**
![1_b_bombrowser-alternate](https://user-images.githubusercontent.com/4900815/29563384-f148497a-875a-11e7-8d02-f3c0c439db38.PNG)

**3) BOM Stock Report**
![1_c_bomstockreport-alternate](https://user-images.githubusercontent.com/4900815/29563421-293a9df6-875b-11e7-9374-eac48ac8d28f.PNG)

**4) Purchase Order to subcontracting supplier**
![2_po_rawmaterial_sc](https://user-images.githubusercontent.com/4900815/29563443-3d2ab936-875b-11e7-94a1-5638d13666db.PNG)

**5) Material Transfer for PO**
![3_material trasfer_to default_samsung_sc](https://user-images.githubusercontent.com/4900815/29563445-3e4b7832-875b-11e7-95e6-bfaf295007f7.PNG)

**6) Material Transfer after changing from the substitute item mentioned in the BOM.**

![3_material trasfer_to_changedell_sc](https://user-images.githubusercontent.com/4900815/29563449-42518e62-875b-11e7-9c9e-4024579403ce.PNG)

**7) Validation while doing material transfer of the alternate line item.**
![4_materialtransfer_validation_error_dell_sc](https://user-images.githubusercontent.com/4900815/29563455-469022a4-875b-11e7-85ec-423cca958603.PNG)

**Comment by creamdory** [comment]
This will be a great feature. Though some few suggestions to add as well:


1. We can have alternative/substitute items visible in the lines which will be automatically pulled from the list of current items in a system from a parameter (ex. same item features and belongs on the same kind)
2. Accounting must be also considered in this scenario as this are only substitute items and will not constitutes the entire BOM, thus the total material cost in Production Order.
3. This should be visible in Production Order, Purchase Order, Purchase Receipt, Stock Entry.
4. We should also need to take note that Substitute Items are not Variants of an item as it is totally a different thing from the production/manufacturing perspective.

**Comment by tundebabzy** [comment]
Hi @jigneshpshah 
You can start a bounty on bounty.erpnext.com

**Comment by dottenbr** [comment]
We definitely want this too, we can do this if we get some guidance from the core team about how to tackle this.

**Comment by creamdory** [comment]
@nabinhait Can we have something to start on this one? Newmatik team is really interested to start a development for this.

**Comment by rmehta** [comment]
@creamdory i think first step would be to propose a solution. What @jigneshpshah proposed is just the start

A minimum viable start would be.

1. Line item in BOM could have a property - "Alternative to"
2. When production order is started, if there is only one alternative present, the system can pick it, else it will add all the options on the Stock Entry. The user can then delete the rows that are not wanted.
3. In the item table, we can have some indication that the item is an alternative and not the main item.
4. For material requests that are generated from Production Order, we can also add all the alternatives and the user can delete unwanted (the UI should indicate alternatives clearly)

@creamdory If you are getting started, keep pushing your code in a PR and send animated GIFs. We are happy to help

cc @dottenbr

**Comment by creamdory** [comment]
@rmehta This is dully noted. We will send PR once we have discussed the integration of the features above.

**Comment by kickapoo** [comment]
@rmehta I will start this one !!!, should we need a discuss topic or we are ok?

**Comment by kickapoo** [comment]
@rmehta 
Using your pointer, I want to start the PR with 
3. In the item table, we can have some indication that the item is an alternative and not the main item.

So, in our case ( @dottenbr  please verify), isn't a clear the main or the alternative. 
So for example and alternative can be a main also , a use case example:

- ITEM 1: BAV99 
- ITEM 2: BAV99BRW-7-F 

Both Items are alternatives to each other and main at the same time (customer might ask that production order should be only with ITEM 2). 

The way I am thinking to tackle this is (simplified explanation) :
Have childtable for substitute items and also update the substitute item's childtable. So a both way update.

**Comment by nabinhait** [comment]
@kickapoo I agree, main item can also be a alternative item and vice-versa. I think child table for alternative items will be good.

Entering multiple alternative items for a main item in BOM Item table is a challenge, we don't have `child-table-under-child-table` for this. Is it required to mention alternative items in BOM? Any proposed design for that? As we are already maintaining alternative items in Item master, we can directly fetch from there while doing Material Transfer.

**Comment by nabinhait** [comment]
@kickapoo Discuss topic with proposed design is always good for developing such feature. We can get many ideas from the community to make it better.

**Comment by kickapoo** [comment]
@nabinhait 
1 . Is it required to mention alternative items in BOM? , Yes and i was thinking to add a checkbox in BOM like "bom lines has alterinatives" 
2. Any proposed design for that? I trying to make one and goes to the second about discuss, I will open :) , there is an old one from 2016 but I will create a new one.

**Comment by kickapoo** [comment]
@nabinhait Sorry for now not having a discuss post yet. I was asked to w8 for a re-design.

**Comment by creamdory** [comment]
@nabinhait , please take a look at this discuss post that our team, together with @kickapoo , has been working on https://discuss.erpnext.com/t/new-feature-bom-components-alternative/31915 . Thanks!
