### ISSUE TITLE
Report Builder Total Error

### ISSUE THREAD

**Issue by LifeP** [frappe/erpnext#10491]
I created a Pending Invoice summary using report builder.
This is used to send summary of invoices for reconciliation at the end of a period.
However it shows a random extra line row 12 without any invoice number
Also the “show total” row 13 is messed up.

I created another report from scratch. Turns out the row 12 is total. (which is wrong anyway)
Observation : row 13 is twice of row 12
There seems to be some error in show total logic.

<img width="1064" alt="screen shot 2017-08-21 at 5 02 03 pm" src="https://user-images.githubusercontent.com/16747599/29556555-d38b3454-8743-11e7-9477-82aedc035c4e.png">

Row 12 showing even when add total row is unticked

**Comment by Zlash65** [comment]
![report-view](https://user-images.githubusercontent.com/11695402/30228424-42477500-94fb-11e7-842b-5346a74f453a.gif)
Seems like an issue when viewing long list of data. Show_total creates a row upto that length of list, and if we click on more i.e to get the whole list, another row is added at the end of the list while the previously partial list total still remains and the final total includes the summation of lists data + partail total.

![report-view 1](https://user-images.githubusercontent.com/11695402/30228508-b957f55c-94fb-11e7-94bc-a1a47ad2371e.gif)
Also, I think 'show total' and 'show all data' starts functioning as some sort of toggle, if the 'show total' is not clicked and 'show more data' is clicked, still the total is displayed

**Comment by Zlash65** [comment]
https://github.com/frappe/frappe/pull/4186
