### ISSUE TITLE
GST Itemised Purchase Register  report - Total Tax column blank. No value updated.

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#10490]
In the Itemised Purchase Register report, value in the Total Tax column is not updated for an item.

![screen shot 2017-08-22 at 1 41 53 pm](https://user-images.githubusercontent.com/910238/29555269-b96aa02c-873f-11e7-90b4-d01c55eaa71b.png)

Also, can we have separate column for each tax type, just like in each GST Purchase Tax Register?

**Comment by nabinhait** [comment]
@umairsy Individual and total tax is already there in the report. In which account it is not showing?

**Comment by nabinhait** [comment]
Fixed via #10494
