### ISSUE TITLE
No support for XAF and XOF Currency

### ISSUE THREAD

**Issue by edwil13x** [frappe/erpnext#10505]
Hello Guys,
i had noticed that ERPNext does not integrate the [XAF](https://fr.wikipedia.org/wiki/ISO_4217#XAF) and the [XOF](https://fr.wikipedia.org/wiki/ISO_4217#XAF) currencies. I searched those currencies into [erpnext_currencies.pdf](https://github.com/frappe/erpnext/files/1243510/erpnext_currencies.pdf) that i have created from my erpnext local installation  at (http://localhost:8080/desk#List/Currency/List)

**Comment by tundebabzy** [comment]
Hi @edwil13x 
Can you contribute this?

**Comment by edwil13x** [comment]
Hello, i would like to help.

**Comment by edwil13x** [comment]
@tundebabzy  try to found a solution into the code without success. I am new on python so if you could fix this, it would be great.
Regards.

**Comment by tundebabzy** [comment]
I will

**Comment by tundebabzy** [comment]
@edwil13x Hi, the link to XOF points to a page for XAF. Is that intentional?

**Comment by tundebabzy** [comment]
Hi @edwil13x 
XAF and XOF has been added and will be live soon. Please follow frappe/frappe#4101

**Comment by edwil13x** [comment]
Thanks ;)
