### ISSUE TITLE
Kanban View i.e. for Project Management or Document Status

### ISSUE THREAD

**Issue by hwinkel** [frappe/erpnext#1050]
Please integrate a Kanban view widget usable for different scenarios like order status, document status, production status, task status. Kanban views are really great to overlook for all this scenarios. Simply check OpenERP to get an impression. runbot.op___rp.com

**Comment by loailabani** [comment]
Is there any plans to implement this!

**Comment by netchampfaris** [comment]
Currently in development:
https://github.com/frappe/frappe/issues/2172

**Comment by rmehta** [comment]
Now merged!
