### ISSUE TITLE
GST - Multiple Addresses for Different Companies

### ISSUE THREAD

**Issue by PawanMeh** [frappe/erpnext#10502]
Scenario

1. Create Company A with two addresses say A1, A2
2. Create Company B with two addresses say B1, B2
3. Create Sales Invoice with Company A, Address A1 and save in 'Draft'
4. Change to Company B, you will see address is not blanked out ( it still has address of company A )
5. Even after manually changing the address to say B1, you get an error message ( see attached video for more details )

![multiple company issue](https://user-images.githubusercontent.com/20460498/29568205-3d08d4d0-876d-11e7-8b09-8977483b4030.gif)

6. Similar issue could exist on Delivery Note as well.

**Comment by nabinhait** [comment]
@PawanMeh That validation is coming because company is different in linked Sales Order / Delivery Note.

**Comment by PawanMeh** [comment]
Ok,  will double check this tomorrow.  Also,  shouldn't address be blanked out if company changes?

**Comment by PawanMeh** [comment]
Will raise a new issue and new PR as suggested by Rushabh
