### ISSUE TITLE
Cancelled Enteries should appear red/gray in Ledger so user is not confused

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#10531]
@netchampfaris use case for new datatable!

**Comment by nabinhait** [comment]
@rmehta Cancelled entries will not be shown in any ledger?

**Comment by rmehta** [comment]
if the first submission is before the report date, then you will have to show cancellation... because then the submission is part of opening, you will see cancelled entry and new entry.

**Comment by nabinhait** [comment]
@rmehta I did not understand the use case. We don't maintain Stock Ledger Entry and GL Entry for cancelled entries, delete the entries of original submission as well. How is it part of opening balance? Why do we show the cancelled entries?

**Comment by rmehta** [comment]
So I saw this in a user account. Will need to check! It was showing cancelled too...

**Comment by nabinhait** [comment]
I think that was a separate problem, the Stock Entry is cancelled after creating the support ticket. I am checking into it, closing this issue.
