### ISSUE TITLE
Add the BGN currency for Bulgaria

### ISSUE THREAD

**Issue by alex-g-s** [frappe/erpnext#10532]
Can you add the currency for Bulgaria? 
Its official code is: BGN
It is named:
- in English: “Bulgarian Lev” or short "Lev"
- in Bulgarian language is “Български лев” or short "лев".
In plural it is named: 
- in English: "Bulgarian Leva" or short "Leva" 
- in Bulgarian “Български лева” or short "лева".

Symbol for amount fields, printouts, etc:
- in English "lv."
- in Bulgarian "лв."

Fraction unit is named:
- in English: "st." from "stotinki"
- in Bulgarian: "ст." from "стотинки"

Fraction units in 1 currency unit:
100 st. = 1 lev.

Smallest Currency Fraction Value: 0.01

**Comment by tundebabzy** [comment]
Hi @alex-g-s 
BGN has been added and will be live soon. Please follow frappe/frappe#4101
