### ISSUE TITLE
Permission Manager - Submit, Cancel and Amend permission is assigning for non-submitable doctype as well

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#10533]
Item is a non-submitable doctype. However, from the Permission Manager, users are able to assign permission of Submit, Cancel and Amend on Item master.

We have a validation check that if a Doctype is non-submitable, then certain permissions should not be assigned. Seems like that check is not working.

![screen shot 2017-08-24 at 12 18 27 pm](https://user-images.githubusercontent.com/910238/29653217-934e0ad6-88c6-11e7-8ea9-5df6dda52c1e.png)

**Comment by rohitwaghchaure** [comment]
Fixed via https://github.com/frappe/frappe/pull/4448
