### ISSUE TITLE
Material Request > Quantity field in Get Items from BOM Pop-up

### ISSUE THREAD

**Issue by jigneshpshah** [frappe/erpnext#10536]
Desired 
Step 1: Create new Material Request
Step 2: Click on GetItemsfromBOM button
Step 3: Below Pop-up comes , which can have BOM Quantity field. Let's say MR is for 500 pcs (BOM), then it should load all the line items quantity by multiply as per BOM Specification.

![nf_getitemsfrombom_mr](https://user-images.githubusercontent.com/4900815/29655842-ee43035c-88cf-11e7-8b93-320b67a4856e.png)

Also in child item table , if we can show existing stock of the items based on "For warehouse" column , it would help in taking informed decision.

**Comment by rmehta** [comment]
@jigneshpshah please use github tagging! tag not required in title 😄
