### ISSUE TITLE
In LEAD please move Territory field

### ISSUE THREAD

**Issue by somicoito** [frappe/erpnext#10539]
In LEAD doctype would it be possible to move the field "TERRITORY" so that is has the same position as in Customer Doctype?
<img width="1179" alt="schermata 2017-08-24 alle 11 24 15" src="https://user-images.githubusercontent.com/26325987/29659889-e587e6ca-88bf-11e7-97f3-882073963363.png">
<img width="1182" alt="schermata 2017-08-24 alle 11 24 57" src="https://user-images.githubusercontent.com/26325987/29659899-eab01ae6-88bf-11e7-9f6c-44a3db75b23e.png">

**Comment by raghubuilds** [comment]
In Lead open the drop down Menu > Customize 

Scroll down a little. You can see the list of all fields in the form , drag them by placing your mouse cursor at serial number and move according to your requirements.

**Comment by somicoito** [comment]
Thank you @raghubuilds !
In standard hosted plan it is not possible to arrange standard fields.
I think this is not my special need, this should be the "out of the box" default position of the field.
Don't know if you agree with me.

**Comment by somicoito** [comment]
Hi @umairsy ! Is it a no?

**Comment by umairsy** [comment]
@rohitwaghchaure  can you please review if we can move Territory field in the standard application?
