### ISSUE TITLE
Unable to finish Erpnext setup : UnicodeDecodeError

### ISSUE THREAD

**Issue by geeksoul-me** [frappe/erpnext#10540]
**Version number**: '8.9.1'

**Steps to Reproduce:**

1.  Install erpnext with `bench install erpnext`
2. In browser, proceed with setup process, until Company name is entered.
3. On pressing next, an error will be displayed:

`Traceback (most recent call last):
File “/home/frappe/frappe-bench/apps/frappe/frappe/app.py”, line 56, in application
response = frappe.handler.handle()
File “/home/frappe/frappe-bench/apps/frappe/frappe/handler.py”, line 21, in handle
data = execute_cmd(cmd)
File “/home/frappe/frappe-bench/apps/frappe/frappe/handler.py”, line 52, in execute_cmd
return frappe.call(method, **frappe.form_dict)
File “/home/frappe/frappe-bench/apps/frappe/frappe/init.py”, line 922, in call
return fn(*args, **newargs)
File “/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/account/chart_of_accounts/chart_of_accounts.py”, line 108, in get_charts_for_country
if (fname.startswith(country_code) or fname.startswith(country)) and fname.endswith(".json"):
UnicodeDecodeError: ‘ascii’ codec can’t decode byte 0xc3 in position 19: ordinal not in range(128)`

**Possible cause of issue:**
There is a file called `fr_plan_comptable_général.json` in the folder `erpnext/erpnext/accounts/doctype/account/chart_of_accounts/verified`.

`os.listdir()` is throwing a error when reading this file name, I deleted this file and was able to proceed with the setup.

First reported at: https://discuss.erpnext.com/t/unicodedecodeerror-ascii-codec-cant-decode-byte-0xc3-in-position-19-ordinal-not-in-range-128/27424/13

**Comment by krnkris** [comment]
I don't have this file:

fr_plan_comptable_général.json

Issue exists as of:

https://discuss.erpnext.com/t/unicodedecodeerror-ascii-codec-cant-decode-byte-0xc3-in-position-19-ordinal-not-in-range-128/27424

**Comment by krnkris** [comment]
Ups there is some new info.

May this help to find a solution.

-------------------------------------------------------

Error Report

Python 2.7.6: /home/frappe/frappe-bench/env/bin/python (prefix: /home/frappe/frappe-bench/env)

Időbélyeg:
    2017-08-24 06:53:38.106237
Relapszusos
    1

Kivétel
args 	('ascii', 'fr_plan_comptable_g\xc3\xa9n\xc3\xa9ral.json', 19, 20, 'ordinal not in range(128)')
encoding 	'ascii'
end 	20
message 	''
object 	'fr_plan_comptable_g\xc3\xa9n\xc3\xa9ral.json'
reason 	'ordinal not in range(128)'
start 	19
A helyiek
_get_chart_name 	
charts 	[]
country 	u'Hungary'
country_code 	u'hu'
fname 	'fr_plan_comptable_g\xc3\xa9n\xc3\xa9ral.json'
folder 	u'verified'
folders 	(u'verified',)
path 	u'/home/frappe/frappe-bench/apps/erpnext/erpnext...ounts/doctype/account/chart_of_accounts/verified'
Visszakövet

/home/frappe/frappe-bench/apps/frappe/frappe/app.py: 56
54
55 		if frappe.local.form_dict.cmd:
56 			response = frappe.handler.handle()
57
58 		elif frappe.request.path.startswith("/api/"):

/home/frappe/frappe-bench/apps/frappe/frappe/handler.py: 21
19
20 	if cmd!='login':
21 		data = execute_cmd(cmd)
22
23 	if data:

/home/frappe/frappe-bench/apps/frappe/frappe/handler.py: 52
50 	is_whitelisted(method)
51
52 	return frappe.call(method, **frappe.form_dict)
53
54

/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py: 922
920 		del newargs["flags"]
921
922 	return fn(*args, **newargs)
923
924 def make_property_setter(args, ignore_validate=False, validate_fields_for_doctype=True):

/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/account/chart_of_accounts/chart_of_accounts.py: 108
106
107 			for fname in os.listdir(path):
108 				if (fname.startswith(country_code) or fname.startswith(country)) and fname.endswith(".json"):
109 					with open(os.path.join(path, fname), "r") as f:
110 						_get_chart_name(f.read())

**Comment by krnkris** [comment]
Other way:

UnicodeDecodeError('ascii', 'fr_plan_comptable_g\xc3\xa9n\xc3\xa9ral.json', 19, 20, 'ordinal not in range(128)')
-------------------------------------
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 56, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 922, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/account/chart_of_accounts/chart_of_accounts.py", line 108, in get_charts_for_country
    if (fname.startswith(country_code) or fname.startswith(country)) and fname.endswith(".json"):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 19: ordinal not in range(128)

------------------------------

{
 "args": "('ascii', 'fr_plan_comptable_g\\xc3\\xa9n\\xc3\\xa9ral.json', 19, 20, 'ordinal not in range(128)')", 
 "encoding": "'ascii'", 
 "end": "20", 
 "message": "''", 
 "object": "'fr_plan_comptable_g\\xc3\\xa9n\\xc3\\xa9ral.json'", 
 "reason": "'ordinal not in range(128)'", 
 "start": "19"
}

----------------------------------------

{
 "_get_chart_name": "", 
 "charts": "[]", 
 "country": "u'Hungary'", 
 "country_code": "u'hu'", 
 "fname": "'fr_plan_comptable_g\\xc3\\xa9n\\xc3\\xa9ral.json'", 
 "folder": "u'verified'", 
 "folders": "(u'verified',)", 
 "path": "u'/home/frappe/frappe-bench/apps/erpnext/erpnext...ounts/doctype/account/chart_of_accounts/verified'"
}

---------------------------------

[
 {
  "call": "(request=)", 
  "dump": {
   "frappe. handler": "", 
   "frappe.handler. handle": "", 
   "global frappe": "", 
   "response": "None"
  }, 
  "file": "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", 
  "func": "application", 
  "lines": {
   "54": "", 
   "55": "\t\tif frappe.local.form_dict.cmd:", 
   "56": "\t\t\tresponse = frappe.handler.handle()", 
   "57": "", 
   "58": "\t\telif frappe.request.path.startswith(\"/api/\"):"
  }, 
  "lnum": 56
 }, 
 {
  "call": "()", 
  "dump": {
   "cmd": "u'erpnext.accounts.doctype.account.chart_of_accounts.chart_of_accounts.get_charts_for_country'", 
   "data": "None", 
   "global execute_cmd": ""
  }, 
  "file": "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", 
  "func": "handle", 
  "lines": {
   "19": "", 
   "20": "\tif cmd!='login':", 
   "21": "\t\tdata = execute_cmd(cmd)", 
   "22": "", 
   "23": "\tif data:"
  }, 
  "lnum": 21
 }, 
 {
  "call": "(cmd=u'erpnext.accounts.doctype.account.chart_of_accounts.chart_of_accounts.get_charts_for_country', from_async=False)", 
  "dump": {
   "frappe. call": "", 
   "frappe. form_dict": "{'country': u'Hungary', 'cmd': u'erpnext.account...counts.chart_of_accounts.get_charts_for_country'}", 
   "global frappe": "", 
   "method": ""
  }, 
  "file": "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", 
  "func": "execute_cmd", 
  "lines": {
   "50": "\tis_whitelisted(method)", 
   "51": "", 
   "52": "\treturn frappe.call(method, **frappe.form_dict)", 
   "53": "", 
   "54": ""
  }, 
  "lnum": 52
 }, 
 {
  "call": "(fn=, *args=(), **kwargs={'cmd': u'erpnext.accounts.doctype.account.chart_of_accounts.chart_of_accounts.get_charts_for_country', 'country': u'Hungary'})", 
  "dump": {
   "args": "()", 
   "fn": "", 
   "newargs": "{'country': u'Hungary'}"
  }, 
  "file": "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", 
  "func": "call", 
  "lines": {
   "920": "\t\tdel newargs[\"flags\"]", 
   "921": "", 
   "922": "\treturn fn(*args, **newargs)", 
   "923": "", 
   "924": "def make_property_setter(args, ignore_validate=False, validate_fields_for_doctype=True):"
  }, 
  "lnum": 922
 }, 
 {
  "call": "(country=u'Hungary')", 
  "dump": {
   "country": "u'Hungary'", 
   "country_code": "u'hu'", 
   "fname": "'fr_plan_comptable_g\\xc3\\xa9n\\xc3\\xa9ral.json'", 
   "fname. endswith": "", 
   "fname. startswith": ""
  }, 
  "file": "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/account/chart_of_accounts/chart_of_accounts.py", 
  "func": "get_charts_for_country", 
  "lines": {
   "106": "", 
   "107": "\t\t\tfor fname in os.listdir(path):", 
   "108": "\t\t\t\tif (fname.startswith(country_code) or fname.startswith(country)) and fname.endswith(\".json\"):", 
   "109": "\t\t\t\t\twith open(os.path.join(path, fname), \"r\") as f:", 
   "110": "\t\t\t\t\t\t_get_chart_name(f.read())"
  }, 
  "lnum": 108
 }
]

**Comment by krnkris** [comment]
OK here is the solution:

Please rename the 
fr_plan_comptable_général.json
to
fr_plan_comptable_general.json

on terminal 
mv fr_plan_comptable_général.json fr_plan_comptable_general.json

Please update the file name on the Production Master + Develop.
Thank you!

**Comment by krnkris** [comment]
It is done by:

https://github.com/frappe/erpnext/pull/10601
