### ISSUE TITLE
Update Customer Group / Territory in transactions when they are updated in the master

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#10542]
Since Customer Group, Territories are used for user permissions, we will have to keep the redundancy.

- [x] when customer group, territory is changed, update all linked transactions
- [x] patch

**Comment by Shalmanest** [comment]
We had updated the customer groups recently to get  better order and quotation reports based on customer grouping. The sales analytics report shows the update of customer group for all order transaction this year but the reports generated from sales order still reflect the old customer group for the linked transactions . Updating each transaction is not feasible and look forward to have this reflected in the reporting level.

**Comment by manassolanki** [comment]
Also the customer support issue WN-SUP27532
