### ISSUE TITLE
Can't add "Chart of Accounts" page to desk

### ISSUE THREAD

**Issue by theopen-institute** [frappe/erpnext#10548]
At present, it is not possible to add the "Chart of Accounts" page to the desk as an icon. This seems inconsistent, since most other pages and reports can be added.

**Comment by dhav-d** [comment]
you cannot add the Sales Analytics report too to the desktop

**Comment by umairsy** [comment]
Chart of Accounts is actually an Accounts master which is (mostly) prepared at once, and not much accessed later. For now, Add to Desktop option is not available for pages. Sales Analytics report is actually a Page.

**Comment by theopen-institute** [comment]
> Chart of Accounts is actually an Accounts master which is (mostly) prepared at once, and not much accessed later.

I disagree. The Chart of Accounts is the easiest way I've found to quickly see balances of liquid assets, total accounts receivable/payable, and the "big picture" of inflow and outflow categories for a given accounting period.

Thanks for assigning this, though! Considering how important various pages can be, it'd be great to have quick access to them from the desk.
