### ISSUE TITLE
OAuth2 Bug

### ISSUE THREAD

**Issue by aldoblack** [frappe/erpnext#10549]
There is a bug on OAuth.
When I try to pass '+' between scopes it returns this error:
`{"message":"InvalidScopeError(u'(invalid_scope)  <oauthlib.Request url=\"http://[URL]/api/method/frappe.integrations.oauth2.authorize?client_id=19ee6f84cb&scope=all%2Bopenid&response_type=code&redirect_uri=http:%2F%2F127.0.0.1:8000\", http_method=\"GET\", headers=\"{u\\'X-Use-X-Accel-Redirect\\': u\\'True\\', u\\'Accept-Language\\': u\\'en-US,en;q=0.8,sq;q=0.6\\', u\\'X-Frappe-Site-Name\\': u\\'energychoice\\', u\\'X-Forwarded-For\\': u\\'[REMOVED]\\', u\\'Connection\\': u\\'close\\', u\\'Accept\\': u\\'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8\\', u\\'User-Agent\\': u\\'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36\\', u\\'Host\\': u\\'[URL]\\', u\\'X-Forwarded-Proto\\': u\\'http\\', u\\'Cookie\\': u\\'io=tDwMskYM-3LkmAaIAAB9; user_image=\"https%3A//secure.gravatar.com/avatar/7b7bc2512ee1fedcd76bdc68926d4f7b%3Fd%3Dretro\"; user_id=Administrator; system_user=yes; full_name=Administrator; sid=f8eea22aa9ca8deb2763aea0391419decb0ccfe1a7f4cf81fe3ee071\\', u\\'Upgrade-Insecure-Requests\\': u\\'1\\', u\\'Accept-Encoding\\': u\\'gzip, deflate\\'}\", body=\"\">',)"}`

This is the URL:
http://[URL]/api/method/frappe.integrations.oauth2.authorize?client_id=19ee6f84cb&scope=all+openid&response_type=code&redirect_uri=http://127.0.0.1:8000

So if I replace, + with space (eg. scope=all openid), it works.

The thing is I am using `rauth` library and it generates the url with '+' . 

**NOTE: I replace the domain and ip with [URL] and [REMOVED] for security purposes**.

**Comment by revant** [comment]
Somehow at my end
Postman, rauth and ScribeJava are working as expected

**Comment by aldoblack** [comment]
FIX: The issue is that you should not be logged in as Administrator. It was not mentioned anywhere.
