### ISSUE TITLE
Pricing Rule: discount should not overwrite price list 

### ISSUE THREAD

**Issue by paryushan** [frappe/erpnext#10556]
Hi

Request you to have feature of pricing rule discount should not overwrite price list. 

I mean for Eg. while making quotation Item List price should be visible as Rate and discount column should be shown separately and after deducting discount from Rate (Rate - %discount) amount should be shown.

I have attached the file for your reference, our current quotation format.
![screen shot 2017-08-25 at 11 17 20 pm](https://user-images.githubusercontent.com/31346412/29726267-b36080ac-89ec-11e7-86c4-041df2a6b5b6.png)

whereas erpnext quotation is printing like this after applying 20% discount while making quotation :- 
![screen shot 2017-08-25 at 11 19 51 pm](https://user-images.githubusercontent.com/31346412/29726328-e2035682-89ec-11e7-9330-bcebaa47219b.png)
 
Please do the needful

Thank you 

Paryushan Jain

**Comment by umairsy** [comment]
Hello Paryushan,

Please add Price List Rate field for the before Discount Amount.
