### ISSUE TITLE
Automating Process Flow/ Linking

### ISSUE THREAD

**Issue by LifeP** [frappe/erpnext#10552]
**Applications** - 

- [ ] 1. Sales Invoice/Delivery Notes - When we create new delivery note/sales invoice, it automatically deducts pending products from sales orders.
- [ ] 2. Manufacture - We want to manufacture items and automatically reduce subassemblies/raw material from stages.
- [ ] 3. Sales/ Purchase Returns - Insert negative invoice to Automatically add stock and link credit.

**Probable Solution**

0. Once the user has put in items and qty in Delivery note,
1. On save/submit, check for sales order item_code in all pending sales order items for the customer.
2. if delivery note item_code matches, automatically assign sales order number in the (delivery note item) field.

(there'll be a couple of more steps like separating out delivery_note items when the qty is more than in one sales order row and some validation checks ofcourse)

Could use something on the lines of function - 
allocate_party_amount_against_ref_docs: function(frm, paid_amount) 
in 
erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.js

This would help in reducing workflow for data entry. For example, if user wants to create delivery note; First we need to get all items from sales order and then remove items not being sent or adjust quantity. 
With the proposed solution - The user simply enters quantity returned and system gets sales orders and quantities where existing.

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.
