### ISSUE TITLE
On Quotation, "Opportunity" is Listed Twice under "Get items from"

### ISSUE THREAD

**Issue by asmith1** [frappe/erpnext#10554]
When you create a new quotation, save it, and don't manually refresh the page, "Opportunity" gets listed twice under the "Get items from" dropdown.

**Comment by umairsy** [comment]
Can you please share the screenshot of GIF indicating an issue?

**Comment by joolsr** [comment]
I think I saw this on a recent update. Have you tried clearing the cache ?

ie bench clear-cache

Occasionally for larger updates I have seen screen oddities such as this

**Comment by kennethsequeira** [comment]
Closing the issue as no further updates have been received on this and the issue is no more replicable as off v12.
