### ISSUE TITLE
When adding an Address to a Lead, the DocType element is not Linked automatically

### ISSUE THREAD

**Issue by guilledd** [frappe/erpnext#10558]
A minor issue for me, maybe no so minor for others.

When you create a new Lead, and then add a new address for it, the Address Form does not Load the DocType Link Automatically. You need to link it manually.

Unless I am missing something, I think it should be linked automatically.

**Comment by umairsy** [comment]
The lead ID is updated on saving an Address.

**Comment by Zlash65** [comment]
![address](https://user-images.githubusercontent.com/11695402/30215431-98be3370-94cd-11e7-8b30-dbee4c341478.gif)
Isn't it linked automatically only ?

**Comment by guilledd** [comment]
I will try to test again. What ERPNext version did you use @Zarrar

**Comment by Zlash65** [comment]
I'm on v8.11.0 , although I think this auto-filled up feature has been there for quite sometime already, don't know why it didn't happened for you. You can check it again and see if its still breaking.. @guilledd

**Comment by Zlash65** [comment]
https://github.com/frappe/frappe/pull/4138
