### ISSUE TITLE
Bulk Update

### ISSUE THREAD

**Issue by troin** [frappe/erpnext#10560]
Please provide a way to update item tax rates or hsn code in bulk in case of variants
As GST is getting settled many product HSN code needs to be reassigned to items it would be better if on changing HS Code in template all variant item lists too get updated with an option to do so

**Comment by umairsy** [comment]
You can use data import tool to add/over-write values in the existing items.

https://youtu.be/Ta2Xx3QoK3E?t=5m2s

**Comment by troin** [comment]
Problem is with 5000 lines restriction
