### ISSUE TITLE
Multiple filter applied on list view once clicked

### ISSUE THREAD

**Issue by aherbhagya** [frappe/erpnext#10561]
Hello Team,
I am raising this issue with Reference:-  htttps://discuss.erpnext.com/t/multiple-filter-applied-once-clicked/27461
![user 2](https://user-images.githubusercontent.com/15160560/29739484-b3f61ab6-8a5c-11e7-87e4-835e4efa1bcf.png)

**Comment by umairsy** [comment]
Hi,

Can you please share the GIF replicating this issue?

**Comment by aherbhagya** [comment]
![out-2](https://user-images.githubusercontent.com/15160560/29774090-db102b2e-8c1d-11e7-8322-e506126901e8.gif)

**Comment by tundebabzy** [comment]
Hi @aherbhagya 
I can't reproduce this. See the gif below:
![peek 2017-09-15 16-04](https://user-images.githubusercontent.com/818803/30489727-ed194588-9a2f-11e7-8bcc-71534ca8588b.gif)

Perhaps it has already been fixed so try `bench update`. Or it could be a side effect of some customisation done.
