### ISSUE TITLE
Default batch number selection

### ISSUE THREAD

**Issue by ajinkyagadewar** [frappe/erpnext#10562]
How can we use the FIFO method for batch number while doing the sales invoice? 

Current Scenario:
In case of Pharma/FMCG vertical, complete purchase and sales is dependent on batch and expiry date. Currently, ERPNext have the provision to setup batch number against each item while receiving the product. So from purchase perspective this is good. While doing sales invoice, we have to manually select the batch and add the quantity in it.

Expected Scenario:
While doing the sales invoice, item should automatically fetch the batches as per FIFO method. In case if the first available batch have less quantity it should pickup next available batch and so on. 

Can we do this?

**Comment by ajinkyagadewar** [comment]
Any timelines on this issue?

**Comment by mdwala** [comment]
Hi @ajinkyagadewar Happy to see you using ERPNext in Pharma business.
We are also in business of diets which has expiry and batches, and other business of wholesale medicine(pharmacy).
My personal view is (unfortunately) there isn't much concentration from any contributors & core team and also not many users using "Has Batch No" items, these can be main reasons for not much improvements anything related to "Batch No".
I couldn’t convince one party to go for ERPNext cloud once they found out by using free account, of these things about not auto selecting batches.
For your reference other issue related to batch
[11004](https://github.com/frappe/erpnext/issues/11004)
[11003](https://github.com/frappe/erpnext/issues/11003)
[9643](https://github.com/frappe/erpnext/issues/9643)
[8714](https://github.com/frappe/erpnext/issues/8714)

Let's feel sad together :(

**Comment by tundebabzy** [comment]
@mdwala , @ajinkyagadewar 
What is the correct way to treat this situation from the Sales Invoice:
Batch A has 1 unit of item X remaining and Batch B has 100 units of item X remaining. An invoice is to be raised for 50 units of Item X. What batch number should be auto-fetched?

**Comment by DavidMenting** [comment]
I think @ajinkyagadewar sketched the desired behavior in his issue already:
"In case if the first available batch have less quantity it should pickup next available batch and so on."

The oldest batch with enough units to fulfil the requirement should be picked, in this case Batch B.

**Comment by tundebabzy** [comment]
Oh OK. Thanjs

**Comment by mdwala** [comment]
Hi @tundebabzy @DavidMenting @ajinkyagadewar 
On case @tundebabzy asked, if only one expiry for both batches than FIFO (First In First Out) can work.

But if both batches have different expiry dates, then it should follow FEFO (First Expire First Out) with no relation of which one purchased earlier or after. Expiry date is all we needs to worry about.

If First expiry batch is not having sufficient quantity it should (auto) pick rest quantity from next expiry batches.

**Comment by tundebabzy** [comment]
Ok then. So the workflow we be something like:

If: Item has expiry date, return oldest batch with sufficient quantity and soonest expiry date
else if: return oldest batch with sufficient quantity
else: return blank

**Comment by mdwala** [comment]
@tundebabzy   "Sufficient quantity" is overkill. As a supplier and retailer in Diet Food & Medicine business, if we don't have sufficient quantity in first expiring batch, we give whatever quantities we can give from first expiring batch, and then rest from 2nd expiring batch ...and follows...
If we wants to give single batch for all quantity, we change as per our need (which gives another requirement of having field in Sales Invoice Item table "remaining batch qty")

**Comment by tundebabzy** [comment]
There is only one field for batch number. While we can have another field for remaining_batch but what if the order consumes 3 batches, or 4 or 5?

**Comment by tundebabzy** [comment]
Ok. I see that there can be multiple batches in the POS. I'll investigate that

**Comment by DavidMenting** [comment]
These are actually two separate issues. I think, having automatic batch selection of a batch of sufficient size is already very useful and shouldn't be too hard to implement.

**Comment by tundebabzy** [comment]
> These are actually two separate issues. I think, having automatic batch selection of a batch of sufficient size is already very useful and shouldn't be too hard to implement.

Yeah. And quite important too. I'll be implementing the automatic batch selection of a single batch number using 'FEFO' for non-POS Sales Invoice. When I'm through with that, I'll investigate the POS

**Comment by mdwala** [comment]
@tundebabzy @DavidMenting 
To clear:
* Satisfy batch qty on single batch 
   1. is not "FEFO" anymore, as satisfy batch can be farthest expiring
   2. Auto fetch will only work if Satisfy batch found, so "No auto fetch" and so most of the time validation error.
   3. If decided to implement in this way, also think what if no single batch qty satisfy full qty?
* Satisfy batch qty on multiple batch
   1. FIFO doesn't need for batch item, just FEFO.
   2. Should build the way its been used/require by multiple users. May be poll on discuss?

By the way forgot to say thanks @tundebabzy for your input on this dead issue. Didn't expect that!

Thanks again......

**Comment by tundebabzy** [comment]
@mdwala It seems we are talking about a different scenario from the issue raised in the ticket. Can you open a fresh issue or direct me to a similar one so that we can continue discussing from there.

**Comment by mdwala** [comment]
Did earlier [](https://github.com/frappe/erpnext/issues/11004)
But no one responded it.
No issue, I will leave this here.

**Comment by hpema** [comment]
Hi Folks,

We are using a similar concept called LOT at our company. Im not familier of how this works in your industry but we are using LOT (Batch) to control costs. Currently the incoming price and outgoing price of an item that has a batch in erpnext is different. I logged a ticket https://github.com/frappe/erpnext/issues/7191 that describes the use case and I think there are some changes since then. 

I have tested the serialised items in v9 and the costs are correctly recorded based on the serial number picked. So I have done a test where I receive item at 3 difference prices. And no matter which item I deliver if I pick the correct serial number then the ourgoing cost will match the incoming cost.

I think a slight adjustment in the current operation can greatly enhance erpnext. I tried but am still struggling to find the right way to code this - and also afraid to break something. 

I think if we can allow a series to be created like in serial number and the number gets generated automatically then that makes picking the lots a little easier to read by the picker of stock when delivery is generated.

To fullfil the quantity issue we can just allow the user to select more then one lot to fullfil the order.

Hope my rambling is not confusing anyone ;)

My goal is that when we receive stock a lot and cost is associated to all stock movement - incoming and outgoing. This cost is what the all the ledger transactions will use.

If I can get guidance on what to change and look into to learn more how the general ledger is generated I can try to get this done - but its been almost a year and I still struggle to figure out the code (not doing this full time so)....

I hope im making sense.

regards

**Comment by tundebabzy** [comment]
@hpema 
Your suggestion is interesting. Please can you add your comment to #7191 since it's related to it. Once I close this out, I'll pick it up.

**Comment by tundebabzy** [comment]
> While doing the sales invoice, item should automatically fetch the batches as per FIFO method. In case if the first available batch have less quantity it should pickup next available batch and so on.

> Can we do this?

Done by #11454. ERPNext will use FEFO (First Expiring First Out) which is like FIFO just that the soonest to expire will be picked first even if it's the last to come in.

**Comment by tundebabzy** [comment]
@ajinkyagadewar also take note that except "Update Stock" is checked in the Sales Invoice, the batch number will not be fetched

**Comment by ajinkyagadewar** [comment]
Understood. Thanks.

**Comment by mobentec** [comment]
@tundebabzy With v10, is it still not possible to include multiple batches of a single item within one Delivery Note?

If not, are there any plans to allow for creating Delivery Notes that details the correct item quantity (as dictated by the Sales Order), however also show the associated mixed of batches that are being allocated to that Sales Order/Sales Invoice/Delivery Note/Customer?

**Comment by tundebabzy** [comment]
At the moment there is none. Please open a new issue to request for this.
