### ISSUE TITLE
BUG Row Delete acting weird

### ISSUE THREAD

**Issue by LifeP** [frappe/erpnext#10573]
In delivery note we use get items from sales order and then select & delete items not being delivered. It was working fine until today when we updated to v8.9.1 
Now on selection some selected rows don't delete while other unselected get deleted.

**Comment by umairsy** [comment]
![child-issue](https://user-images.githubusercontent.com/910238/29767362-c2af3b38-8bff-11e7-80b8-59c987f007eb.gif)
