### ISSUE TITLE
email account dashboard is blank after upgrade to ERPnext v8.9.2

### ISSUE THREAD

**Issue by vittitrade** [frappe/erpnext#10579]
After upgrade to the ERPnext v8.9.2 not able to view the the email account dashboard. 
<img width="1222" alt="email account notification" src="https://user-images.githubusercontent.com/18444784/29784502-c7b55f44-8c41-11e7-99f2-abf520b28676.png">

**Comment by joolsr** [comment]
try and clear the cache

ie bench clear-cache

**Comment by vittitrade** [comment]
This didn’t help

**Comment by rmehta** [comment]
@vittitrade can share the javascript console?

**Comment by vittitrade** [comment]
desk.min.js?ver=1503985116.0:1472 Unable to handle success response
desk.min.js?ver=1503985116.0:1473 ReferenceError: email_defaults is not defined
    at eval (eval at setup (form.min.js?ver=1503985116.0:2620), <anonymous>:200:10)
    at Class.setup (form.min.js?ver=1503985116.0:2620)
    at _f.Frm.setup (form.min.js?ver=1503985116.0:172)
    at _f.Frm.refresh (form.min.js?ver=1503985116.0:439)
    at Class.load (form.min.js?ver=1503985116.0:87)
    at form.min.js?ver=1503985116.0:82
    at Object.callback (desk.min.js?ver=1503985116.0:6792)
    at Object.callback [as success_callback] (desk.min.js?ver=1503985116.0:1345)
    at _ (desk.min.js?ver=1503985116.0:1369)
    at Object.<anonymous> (desk.min.js?ver=1503985116.0:1469)
(anonymous) @ desk.min.js?ver=1503985116.0:1473

are you looking for this console finding.

**Comment by mbauskar** [comment]
@vittitrade,

Just checked the email account and seems to work fine please check the screenshot

<img width="1030" alt="screen shot 2017-09-01 at 10 33 52 am" src="https://user-images.githubusercontent.com/11224291/29955962-4aa85016-8f01-11e7-8c22-fe394606f790.png">

also, Email Account doctype don't have a dashboard did you made any customization? if Yes, then please share the code so that we can check and replicate the issue.

**Comment by vittitrade** [comment]
Namaskara Makarand,

Please find the screen shot of the page error. We have not done any customisation on the Erpnext. When we try to open the email account page this is what we get.

**Comment by mbauskar** [comment]
@vittitrade,

Can not replicate, is `email_defaults` is used in the customized form `eval` or `defaults` property?

**Comment by vittitrade** [comment]
Namaskara Makarand,

We have not used any customised forms. Have configured it as default configuration. Will be able to share you a login ID to verify the same.

regards
Shreyas.

**Comment by mbauskar** [comment]
@vittitrade,

Can you send me PM me on discuss.erpnext.com

**Comment by mbauskar** [comment]
@vittitrade,

The issue is due to invalid variable name in the custom script in sendgird_integration app, there is already pull request available to fix the issue https://github.com/semilimes/sendgrid_integration/pull/4, but it seems the repo is inactive for some time.

**Comment by vittitrade** [comment]
thank you @mbauskar. Have removed the sendgrid integration and able to see the email accounts now.
