### ISSUE TITLE
Disabled document not validated on save/submit

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#10571]
As per the current system, checking Disabled Warehouse only restrict that document in the autosuggest. However, if user enters the complete value manually, then it is accepted, which should not be allowed.

I disabled a Warehouse.

![screen shot 2017-08-28 at 11 32 45 am](https://user-images.githubusercontent.com/910238/29761009-a0d4c980-8be4-11e7-8537-0a1610b79660.png)

Though in the Stock Entry, that Warehouse was not showing in the autosuggest, I could enter a value manually, and save-submit stock entry. It allowed save and submission for the disabled warehouse.

![screen shot 2017-08-28 at 11 33 46 am](https://user-images.githubusercontent.com/910238/29761032-c7478eea-8be4-11e7-9005-c00cbd234fbd.png)

**Comment by utkarsh-goswami** [comment]
https://github.com/frappe/frappe/pull/4195

**Comment by tundebabzy** [comment]
#10571
