### ISSUE TITLE
Remove C-Form Feature

### ISSUE THREAD

**Issue by PrakashH** [frappe/erpnext#10577]
- There is C Form Doctype

- C-Form Applicable field in Sales Invoice form. Now onwards it is not applicable for Indian customer due to GST. 

![screen shot 2017-08-28 at 5 25 29 pm](https://user-images.githubusercontent.com/4570016/29772454-89f87a72-8c16-11e7-89c2-4d9302fbea9f.png)

**Comment by djpalshikar** [comment]
What will happen to the old invoices which had C-form in them? People are still liable to pay to submit C-Forms,

**Comment by PrakashH** [comment]
It can affect on old invoices. Not urgent. But can do it later.
