### ISSUE TITLE
How to set item price

### ISSUE THREAD

**Issue by ianpkano** [frappe/erpnext#10588]
I have 95,000 items, I need to set at least 2 prices for each and 3 for some others, how can I do this in bulk? I have the item price file but it is not logical, or not understood by me, I need to have a record with one item that has 2-3 prices associated to it. I have to do this for 95,000 records (Items), please help

**Comment by tundebabzy** [comment]
Hi @ianpkano 
Let's discuss this on the forum (https://discuss.erpnext.com)
