### ISSUE TITLE
Non customizability of status when a document has to affect the status of other document

### ISSUE THREAD

**Issue by zubair2930** [frappe/erpnext#10589]
Hi Everyone

when purchase order is submitted, the status of the document turns TO RECEIVE AND BILL
I want it to close/complete and stop showing notifications after we submit the Purchase Receipt

However, it seems impossible to implement it as there is no option to customize the status of PO depending upon the status of Purchase Receipt

Please also note that we are using the hosted version of ERPNext

**Comment by umairsy** [comment]
Yes. This status are updated based on %Billed and %Received against Purchase Order. This status is **very important** as it is actionable and gives instance update on an order.

For an alternative, try workflow, however, this filters should not be by-passed. Rather you should ensure that transactions against Purchase orders are fulfilled as required. To short-close Purchase Order, you can Close it manually as well.

**Comment by zubair2930** [comment]
@umairsy 
Actually, we do not want to prepare invoices and our work is finished when we prepare the purchase receipt

AND we do not want it to appear in notifications as well.

We have been closing Purchase receipt and purchase order manually already. It is tedious and impractical on a large scale

However, we want it to SOMEHOW close it automatically after purchase receipt is created.  

This is also not possible by using Workflow. It would be great if this was solved from your side. This inability to customise is being a drawback of ERPNext
