### ISSUE TITLE
[Feature Request] Update the date of "Accounts Frozen Up To" to posting date of latest Period Closing Voucher automatically

### ISSUE THREAD

**Issue by addymuliady** [frappe/erpnext#10587]
Once a user do a Period Closing Voucher,

The "Accounts Frozen Up To" date will be updated based on the PCV posting date.

- [ ] Create a checked field (by default uncheck) "Freeze accounts upon Period Closing Voucher" in Global Settings
- [ ] Add script to check if this field is checked, when doing Period Closing Voucher, Accounts Frozen Up To will be updated based on posting date of Period Closing Voucher

**Comment by umairsy** [comment]
Hello,

For a Fiscal Year, you can create multiple period closing vouchers as well. Generally users create posting in the old Fiscal Year event after creation of Period Closing Voucher.

**Comment by addymuliady** [comment]
Hi @umairsy 

Thanks I do realise that. That is wjy it is an option. This is to safeguard the integrity of booked profit.
