### ISSUE TITLE
Notification Icons Not Updating Properly

### ISSUE THREAD

**Issue by jayfiro** [frappe/erpnext#10599]
Notification icons only update when the page is reloaded.

Please see this possibly related post: `https://discuss.erpnext.com/t/notification-icons-not-updating-in-a-timely-manner/10538`
 
![help](https://user-images.githubusercontent.com/23268734/29855964-b851fd28-8d1d-11e7-89d7-e2f7d3c983f8.jpeg)
![purchasing](https://user-images.githubusercontent.com/23268734/29855969-bb07dede-8d1d-11e7-971d-60a865377a7a.jpeg)

**Comment by pratu16x7** [comment]
They do update without a reload. However, quoting the [discuss](https://discuss.erpnext.com/t/notification-icons-not-updating-in-a-timely-manner/10538) post, the latency could use some work.
![notif no bug](https://user-images.githubusercontent.com/5196925/29865303-d7266c6e-8d92-11e7-9979-b53b7e3c6151.gif)
