### ISSUE TITLE
Website Portal Homepage issue/bug

### ISSUE THREAD

**Issue by mohnishthakurscs** [frappe/erpnext#10602]
![error in homepage](https://user-images.githubusercontent.com/21141792/29860091-6e17f91e-8d82-11e7-8c86-a00de5acef10.png)

![error in homepage 1](https://user-images.githubusercontent.com/21141792/29860108-762a4c88-8d82-11e7-8b23-0ad0f6299ec3.png)

So when i am deleting the product then it gets deleted from the inside field view but when i save or refresh then again that product comes in and cannot get deleted. please provide the solution as per the above screenshot.

**Comment by umairsy** [comment]
Hi,

I couldn't replicate this issue in my test account. When I delete an item and then try saving, I receive validation message like this.

![screen shot 2017-09-04 at 1 01 04 pm](https://user-images.githubusercontent.com/910238/30016083-36b37c30-9171-11e7-8027-fd9c6900819c.png)

For further support, please post your queries on the discuss forum, till it is validated. Also, ensure that your ERPNext account is upgraded to the latest version.

https://discuss.erpnext.com
