### ISSUE TITLE
Accentuated chars on an Email From get removed

### ISSUE THREAD

**Issue by joolsr** [frappe/erpnext#10609]
Hello

I received an email from a Toñi Gómez, into my Email Inbox, but when I try to add them as a Contact via the button, the 'n' with the tilde and the accentuated 'o' get removed entirely from the entries in the name fields.

**Comment by joolsr** [comment]
Please note I have a support contract with ERPNext for my own ERPNext server.

**Comment by Zlash65** [comment]
@joolsr Can you share a screenshot/gif maybe ? Can't seem to recreate what you're facing.
![email](https://user-images.githubusercontent.com/11695402/30036467-44ec5dc0-91d1-11e7-9af2-22c6c2f4bac5.png)
My version  of Toñi Gómez seems to be adjusting just fine.

**Comment by joolsr** [comment]
![missing-accented-chars](https://user-images.githubusercontent.com/934876/30039071-ff287484-91c3-11e7-9857-830c62caa816.png)

**Comment by joolsr** [comment]
ie an email is received but the name is truncated in the Communication and the contact name.

**Comment by joolsr** [comment]
Right. I just tried this again with another name Carlos Frias with an accent on the 'i'. when i saved the contact first it was fine with the I with the accent. then I made an opportunity and the linked Communication was still fine. Then I went back to the Contact and the 'i' has disappeared.
So it appears that the contact is saved correctly, then something happens afterwards to remove that character. Check if your test name still has the char in their name.

**Comment by Zlash65** [comment]
Still not able to re-create your issue. I tried saving contacts with different accented names. And they still seem to be the same and not truncated at all.

**Comment by joolsr** [comment]
![peek 2017-09-07 17-52](https://user-images.githubusercontent.com/934876/30175602-0786cff6-93f7-11e7-8f84-8650d05ecd03.gif)
Please see the gif above taken on my joolsr.erpnext.com instance ie on a Frappe server. This proves that this issue seems to occur on Frappe hosted servers too as well as my own.

The email came from full name of 'Tomáš Mořkovský' but you can see what happens to his name when added as a contact from the Email Inbox, which loses the accentuated chars

**Comment by joolsr** [comment]
Hello, are you still not able to recreate the problem? I sent you an email as above so you can test against this email address. Please let me know if you need any more info from me

**Comment by Zlash65** [comment]
https://github.com/frappe/frappe/pull/4123
