### ISSUE TITLE
Problem with user limits

### ISSUE THREAD

**Issue by sistemascarroceriasapezcom** [frappe/erpnext#10606]
Hello, we have paid for a subscription for 5 users and anyway we have a error that says that we have reached the maximum limit of users. Could you help us with this? 
carroceriasapez.erpnext.com is our domain.
![error erpnext](https://user-images.githubusercontent.com/31474967/29870527-54ef5a28-8d5e-11e7-8bd3-a518d7b5217f.png)

**Comment by sistemascarroceriasapezcom** [comment]
This happen when I try to send quotation email...

**Comment by manassolanki** [comment]
Hi @sistemascarroceriasapezcom ,
Please send a email to support@erpnext.com for any support related to the frappe cloud.
Closing this issue here, you will get proper resolution there.
