### ISSUE TITLE
Delivered Qty (Sales Invoice Item) filter is not working properly

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#10610]
Hi,

I have quite a number of invoices which are yet to be delivered. When I set a filter for 'Delivered Qty (Sales Invoice Item) = 0'  I got only 2 invoices of which one of them was actually delivered. Testing this same filter on an earlier V8 instance seems to be working fine so something might have broken during recent updates

Please fix

Thanks

**Comment by umairsy** [comment]
Can you please share the screenshot of the exact field of the Sales Invoice Item on which filter was applied?

**Comment by Olawale1** [comment]
Hi @umairsy 

Please find screenshot below:

![delivered qty filter in list view](https://user-images.githubusercontent.com/9269337/30104135-a268597e-92ec-11e7-9cc1-10487c354635.png)

It doesn't work properly in List View but it seems to be okay in the report

Please help fix

Thanks

**Comment by jaichavan** [comment]
Hello, @Olawale1 does the issue persist in the latest upgrade? [ v11.0.3-beta.34 () (staging) ]

**Comment by jaichavan** [comment]
Hello, @Olawale1 @umairsy 
Just tested in my trial account[ v11.0.3-beta.34 () (staging) ] only to find there is no longer any such issue. Attaching screenshots for reference:
1. Report Builder View: Sales Invoice ( Filter: Delivered Qty = 0 )

![screenshot 2019-01-19 11 59 01](https://user-images.githubusercontent.com/40264279/51423195-3824b780-1be2-11e9-87e7-68aa977af7b1.png)

2. List View: Sales Invoice ( No Filter)

![screenshot 2019-01-19 11 59 20](https://user-images.githubusercontent.com/40264279/51423198-45da3d00-1be2-11e9-94fe-6b373d7ea7b4.png)

3. List View ( Filter: Delivered Qty = 0 )

![screenshot 2019-01-19 11 59 37](https://user-images.githubusercontent.com/40264279/51423203-525e9580-1be2-11e9-8009-101129beb00d.png)
