### ISSUE TITLE
POS setting for compulsory submission of synced invoices

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#10617]
Hi,

Please add an option in POS Settings for compulsory submission of synced invoices. If this option is checked, the user should be prompted to allow negative stock. Other criteria that could also stop an invoice from being submitted also need to be addressed accordingly or validated before submission in the POS screen

This will help in addressing cases where regulation doesn't allow invoices from completed transactions to be editable... at least not by the regular sales users. Both online and offline users will require this feature

Thanks

**Comment by umairsy** [comment]
Hi,

If it is a fairly large feature, please create a Bounty for it. Also, you can consider sponsoring this feature to raise it's priority. It will be great to see feature contributions coming for such generic use-cases.

https://erpnext.org/bounties
