### ISSUE TITLE
Advance payment against recurring invoice

### ISSUE THREAD

**Issue by deep3vedi** [frappe/erpnext#10614]
For Advance payment taken against recurring invoices, there should be some mechanism that validate recurring invoice against any advance payment entry made for that customer. currently for manual invoice creation we can pull the advance payment and allocate the amount which is not possible in case of auto-generation of invoice through recurring invoice.

**Comment by rohitwaghchaure** [comment]
Hi @deep3vedi 

We have did internal discussion with the team on this issue and come to the solution on this is, you have to disabled option submit on creation and so system will create invoice in draft mode. Draft mode invoice has an option to pull advance payment

**Comment by deep3vedi** [comment]
Hi @rohitwaghchaure ,

Thanks for the update. In method described by you, it will still require human intervention to fetch the advance and submit it every time it is created. So option of recurring invoice will have no meaning, if it require human intervention.

**Comment by deepeshgarg007** [comment]
@deep3vedi There is a check in Invoices to allocate the advances automatically. You can add a custom script to enable this based on the conditions for recurring invoices. Hope this helps
