### ISSUE TITLE
Print Format - Setting "Align Labels to the Left" applies on all the format, and not reversable

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#10613]
WN-SUP27675

The Print Format doctype has a field "Align Labels to the Left". If you check this field, then this setting is applied on all the Print Formats, even Standard ones.

Even if you uncheck this field, the labels are still left aligned.

![screen shot 2017-08-31 at 11 33 47 am](https://user-images.githubusercontent.com/910238/29908713-42becffe-8e40-11e7-90ec-7e375e28071c.png)

**Comment by rmehta** [comment]
So I had changed default alignment to left, as it looks better. Should have fixed the style settings. Maybe change the settings to "Align labels to Right" ?
