### ISSUE TITLE
Receive material in the different warehouses

### ISSUE THREAD

**Issue by lifestylesofas** [frappe/erpnext#10627]
HI, 

I AM RECEIVING FINISHED GOODS FROM PACKING DEPARTMENT AND TAKING INTO STOCK RECEIPT IN FINISHED GOODS WAREHOUSE AFTER THAT THE SAME MATERIAL I HAVE TO TRANSFER TO MY DIFFERENT WARE HOUSES BUT THE PROBLEM IS I HAVE TO DO THE ENTRIES TWICE ONE IN STOCK RECEIPT AND THAN AGAIN WHILE TRANSFERRING TO DIFFERENT WAREHOUSES IN STOCK TRANSFER. 

CAN IT BE POSSIBLE THAT STOCK RECEIPT LINK TO STOCK TRANSFER.

**Comment by lifestylesofas** [comment]
any update

**Comment by lifestylesofas** [comment]
i am not getting any updates regarding my issue.

**Comment by umairsy** [comment]
As discussed over phone, please duplicate Material Receipt entry and create Material Transfer entry.
