### ISSUE TITLE
erpnext.org - Customization Job publishing issue

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#10625]
If a member publishes a customization job without a Title, then the system generates ID for it. Though this job is visible in the /erpnext-jobs list, won't open when clicked. Even if Title is added later-on, the job won't open on the portal.

![screen shot 2017-08-31 at 3 58 28 pm](https://user-images.githubusercontent.com/910238/29919047-6710088a-8e65-11e7-915b-4a97dd74b9f4.png)

**Comment by vishdha** [comment]
https://github.com/erpnext/foundation/pull/42
