### ISSUE TITLE
[Bug] Delete multiple in table malfunction

### ISSUE THREAD

**Issue by snvora** [frappe/erpnext#10624]
Following GIF shows how multiple delete is malfunctioning. Initially Item with PO Sr No 5 is required in table. and it gets deleted as can be seen. 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/10496564/29918581-8c47ccde-8e63-11e7-82c5-98c72be0bf54.gif)

**Comment by rmehta** [comment]
This is fixed in latest release, can you check and confirm?

**Comment by snvora** [comment]
Works Fine :-) +1
