### ISSUE TITLE
Permissions Issue

### ISSUE THREAD

**Issue by saurabh6790** [frappe/erpnext#10621]
https://discuss.erpnext.com/t/erpnext-issues-version-8-9-1/27727

---
- Role Permission manager automatically changed for all users When I changed user permission for any users.
- When set users permission for doctype its take too much time with a prompt with updating messages.

**Comment by jaichavan** [comment]
This issue has been resolved in the latest upgrade. Please check: v11.0.3-beta.34 () (staging)
