### ISSUE TITLE
Top margin disappears in PDF Print

### ISSUE THREAD

**Issue by KanchanChauhan** [frappe/erpnext#10637]
If you have letterhead in print, the top margin disappears.

**HTML Preview**
<img width="837" alt="screen shot 2017-09-01 at 10 04 35 am" src="https://user-images.githubusercontent.com/16913064/29955427-273aa452-8efd-11e7-92fe-9567891dfe95.png">

**PDF Preview**
<img width="822" alt="screen shot 2017-09-01 at 10 04 46 am" src="https://user-images.githubusercontent.com/16913064/29955428-2ae6d81e-8efd-11e7-9d04-a59c815815ee.png">

**Comment by joolsr** [comment]
Thanks for this. I add worked around this but best to fi at source ;-)
