### ISSUE TITLE
Stock levels bulk update

### ISSUE THREAD

**Issue by ianpkano** [frappe/erpnext#10636]
When inputting a bulk stock update it doesn't accept it as submitted...which defeats the object because that means you have to submit every stock you uploaded....Is there a solution?

**Comment by rmehta** [comment]
You can check "submit after save" in the data import tool. Please ask questions at https://discuss.erpnext.com

**Comment by ianpkano** [comment]
Import Failed
Ignored row (#21) None
Error for row (#21) : 'dict' object has no attribute 'submit'
Ignored row (#22) None
Error for row (#22) : 'dict' object has no attribute 'submit'
Ignored row (#23) None
Error for row (#23) : 'dict' object has no attribute 'submit'
Please correct the format of the file and import again

**Comment by ianpkano** [comment]
That's what I get when checking the submit after save

**Comment by rmehta** [comment]
What document type are you uploading? Stock Entry?

**Comment by ianpkano** [comment]
Its not the document issue anymore, its to do with lot sizes, I cannot update stock entries with over 1,000 records...

**Comment by ianpkano** [comment]
Basically, I solved the problem, and deleted all the stock records, I then uploaded them again, but this time in lots of a 1,000...because your system does not allow for updates!!!

I have items, I want to update all the items with suppliers...it cant be done! Your system wont let it happen.

**Comment by ianpkano** [comment]
Internal Server Error

**Comment by ianpkano** [comment]
This is what I got after updating stock levels

**Comment by umairsy** [comment]
Duplicate issue.
