### ISSUE TITLE
Progress bar not closing after completion of uploading file in the Stock reconciliation

### ISSUE THREAD

**Issue by ianpkano** [frappe/erpnext#10635]
It doesn't accept the csv file it downloaded to upload after inputing the relevant info.

**Comment by rmehta** [comment]
Any screenshot, error message? https://github.com/frappe/erpnext/wiki/Issue-Guidelines

**Comment by ianpkano** [comment]
No error message, it just doesn't finish the procedure...I test with one
item only and it just remains in upload mode.

**Comment by rohitwaghchaure** [comment]
Hi @ianpkano 

I've checked on local account and it's working properly

**Before stock reconciliation, stock balance report**
![screen shot 2017-09-04 at 11 50 13 am](https://user-images.githubusercontent.com/8780500/30014059-c7f9c456-9167-11e7-8028-6e97e771cde5.png)


**Stock Reconciliation**
![stock_reconcillation](https://user-images.githubusercontent.com/8780500/30014067-d2535f8e-9167-11e7-8447-f015e378758d.gif)

**After stock reconciliation, stock balance report**
![screen shot 2017-09-04 at 11 51 42 am](https://user-images.githubusercontent.com/8780500/30014081-e43eb766-9167-11e7-8657-5001fd18f8cf.png)

**Comment by rohitwaghchaure** [comment]
Progress bar not closing issue has fixed via https://github.com/frappe/frappe/pull/4044, soon we'll release the fix
