### ISSUE TITLE
Stripe integration amount problem

### ISSUE THREAD

**Issue by maxtorete** [frappe/erpnext#10645]
Hi all,

I'm playing with Stripe Gateway integration and it has a problem with decimals. In the Stripe API request, Erpnext send the amount as float, when it should be a integer with the currency’s smallest unit amount (cents in EUR), according to Stripe documentation https://stripe.com/docs/currencies#zero-decimal.

`{"reference_doctype": "Payment Request", "description": "Payment Request for SOR-00268", "title": "Company Name", "order_id": "PR00001", "payer_name": "POS", "currency": "EUR", "payer_email": "mymail", "amount": "1.23", "reference_docname": "PR00001", "stripe_token_id": "token"}`

It charges only 1€, as the amount in the request should be 123 instead 1.23.

Best regards,
Juan

**Comment by maxtorete** [comment]
I checked Stripe checkout and it makes the conversion to cents, so that's not the problem. This is the Request POST Body in Stripe:

`{
  "currency": "EUR",
  "amount": "100",
  "description": "Payment Request for SOR-00268",
  "source": "token"
}`

**Comment by maxtorete** [comment]
I found the problem, it was on file /apps/frappe/frappe/integrations/doctype/stripe_settings/stripe_settings.py, in this line: 

"amount": cint(self.data.amount)*100

As it rounds the amount before the multiplication, so it looses its decimals. 

Kind regards,
Juan

**Comment by mf86** [comment]
I can confirm this is an issue, and the fix by Juan works.

**Comment by tundebabzy** [comment]
Hi @maxtorete @mf86 
Please send in a pull request for this

**Comment by mf86** [comment]
@tundebabzy @maxtorete  So I'm not a developer, and not really familiar with how GitHub works. Could you please advise on how to do this?

**Comment by maxtorete** [comment]
Hi @tundebabzy ,

I made the pull request (it is my first one, I hope it is all fine). The pull request is #4168

**Comment by tundebabzy** [comment]
Thanks @maxtorete
I'm closing this issue and we can follow the progress of the PR on frappe/#4168

**Comment by calciosf** [comment]
@tundebabzy I don't think this issue should not be followed on frappe/#4168.  This is not a related issue to that closed issue from 2015.  I might be wrong here.

**Comment by tundebabzy** [comment]
Hi @calciosf 
The ref should have been frappe/frappe#4168. Sorry for the mixup

**Comment by calciosf** [comment]
@maxtorete thanks for posting this solution.  I was able to edit the stripe_settings.py per your instructions. 

Can you indicate how to import flt?  You said this was a requirement and I am assume that this requires some python commands.  Can you share this step?   Much appreciated!

**Comment by maxtorete** [comment]
Hi @calciosf, you have to import flt in stripe_settings.py too. You can check the needed changes in this commit: https://github.com/frappe/frappe/pull/4168/commits/5f86884031fd925a6c055ff5c19d0b13f786130d
