### ISSUE TITLE
Updating files

### ISSUE THREAD

**Issue by ianpkano** [frappe/erpnext#10647]
I cannot update files .I can only add new records. When I try to update a file using the bulk update feature it ignores all updates.

**Comment by umairsy** [comment]
By Files, are you referring to existing documents/records? Or Attachments?

**Comment by ianpkano** [comment]
Breakdown of meaning:
1. when updating files in bulk update, adding code doesn't work and the system doesn't apply the changes. I tried directly in the server, it works for small queries, but once doing large actions the server freezes.
2. Updating via import file feature doesn't work.
3. Uploading new data via import file will not work using the same file name if you uploaded and got error messages, then repaired the file and try again. 
4. The error messages are fine, the red error messages for lines with errors should be consolidated, you don't need the good lines in between...when uploading 2,000 records it can be tiring to scan through so many lines when all that is important are the red ones.

**Comment by umairsy** [comment]
> when updating files in bulk update, adding code doesn't work and the system doesn't apply the changes. I tried directly in the server, it works for small queries, but once doing large actions the server freezes.

Can you please share the screenshot of this issue? Bulk Update tool is only meant for updating values in the specific field of the existing document. As requested earlier, please post your queries first of the discuss forum only.

https://discuss.erpnext.com
