### ISSUE TITLE
Event Domain

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#10643]
- [ ] Event master (Web page)
- [ ] Attendees
- [ ] Registration and ticketing
- [ ] Registration types/plans
- [ ] Checkout (using Payment Gateway)

**Comment by yashodhank** [comment]
Few more features would make it more useful.

- [ ] Choosing event from list
- [ ] Go to "Check In."
- [ ] Choosing
- [ ] Choosing
- [ ] Choosing
- [ ] Choosing
- [ ] Choosing
- [ ] Barcode/QRCode Generating to be sent to Participants
- [ ] Barcode/QRCode Scanning from Mobile App to Verify participants at venu.

**Comment by manassolanki** [comment]
Also, can have a look on the https://www.eventbrite.com/ for more ideas.
