### ISSUE TITLE
Option for 'In Words' field to show Outstanding Amount instead of Grand Total

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#10651]
Hi

Some organizations (and most clients) prefer to display the Outstanding Amount in words rather than the Grand Total. This is especially true in cases where Advance Payment has been made by the customer

Please add this option

Thanks

**Comment by umairsy** [comment]
Hi,

You can insert an HTML to get Amount in Words for the specific Currency field.

https://discuss.erpnext.com/t/print-amount-in-words/15681/2?u=umair

https://frappe.github.io/erpnext/current/api/utils/frappe.utils.data#frappe.utils.data.money_in_words

Hope this helps.

**Comment by Olawale1** [comment]
Hi @umairsy 

Thanks for this but the 2nd link seems to be broken
