### ISSUE TITLE
Made to Order in Shopping Cart

### ISSUE THREAD

**Issue by raghuzor** [frappe/erpnext#10657]
I am trying to set up shopping cart. I manufacture 'made to order' Items. I have unchecked “maintain stock” in the items, I also set the website warehouse blank and with that I was hoping the Shopping cart would allow ordering but I see that it still displays “Not it stock”.

**Comment by rmehta** [comment]
For non stock items, stock should not be seen

**Comment by mghoneem10** [comment]
what about this issue coz i`m also trying to implement the same module 'made to order'  will it be included in v10 or check for another scenario  ?
