### ISSUE TITLE
Round up after Discount not available

### ISSUE THREAD

**Issue by taherkhalil** [frappe/erpnext#10653]
Currently the rounding method is round down - 
In retail business we like to round up to the nearest currency fraction not down.
It would be helpful if there was a **global setting where you can set option to round numbers up or down.** 
![image](https://user-images.githubusercontent.com/20456072/29997294-5f9d303c-9018-11e7-814f-fcd2fedec07d.png)
smallest currency fraction is set to 0.25 , so the amount should be rounded up to 26.25 rather than 26.

**Comment by umairsy** [comment]
Linked to https://github.com/frappe/erpnext/issues/10617

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.
