### ISSUE TITLE
Add Timesheet buttons in Tasks table [Project DocType]

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#10650]
Hi

When you open up a row from the Tasks table in the Project DocType, you only find a 'View Task' button. There should also be `'Make Timesheet'` and `'View Timesheets'` buttons in order to improve the User Experience. Currently, the user needs to first click the View Task button which opens up the full Task form before proceeding to Timesheets and even then, there's only a View option!

Thanks

**Comment by Olawale1** [comment]
Hi @vishdha 

Trust you're doing great. Any progress here?

Thanks

**Comment by Zlash65** [comment]
I don't think 'Make Timesheet' makes any sense ? Since project and task both are fields in the child table of timesheet, having a button to make a timesheet will route to timesheet could be done but then filling up project and task field in the child table seems rather pointless. What say ?

**Comment by Olawale1** [comment]
Hi @Zlash65 

Trust you're doing great. Why would that be pointless? Think of yourself as an employee who is part of a number of Projects in the office. Now each of those Project documents on the ERP contains a table with Tasks that are assigned to you for which you have to make regular Timesheet Entries

The most user friendly way by far is to just expand the Task row and click on Make Timesheet to create a log of what you've done concerning that Task. It is bad UX to have to manually open a new Timesheet document then manually input the Project and Task for which you are making the Timesheet entry. It's also very prone to errors if you're working in a projects based organization where you have to make a lot of such entries

Thanks

**Comment by Zlash65** [comment]
![task-buttons](https://user-images.githubusercontent.com/11695402/34005974-b40dbc94-e122-11e7-8658-7f8acc7d79cc.gif)
The button essentially routes to a new timesheet which is the same as typing 'New Timesheet' in the search bar, hence having a button seems redundant

**Comment by Olawale1** [comment]
Hi @Zlash65 

What about adding Default Project / Task fields to the Timesheet DocType similar to Default Source / Target Warehouse fields in Stock Entry?

Kind regards,

**Comment by vishdha** [comment]
https://github.com/frappe/erpnext/pull/12100
