### ISSUE TITLE
Change Project Type field to Project Category/Group

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#10677]
Hi 

Projects are a very versatile tool in ERPNext and cover a wide range of applications even within the same organization. It would be helpful to have a Project Category (or Group) field that functions like Item/Customer Group (with tree structure) rather than the current Project Type select field

This will enable users properly categorize and view Projects as required

Thanks

**Comment by umairsy** [comment]
Hi,

You can create a Custom Select field (say Project Type) for categorizing Projects. If needed, you can also add a Custom Doctype for Project Type, and add it's link field in the Project master.
