### ISSUE TITLE
Parent Portal

### ISSUE THREAD

**Issue by manassolanki** [frappe/erpnext#10672]
- [ ] Parent Portal will include the following website views
     - [x] Newsletter
     - [ ] Attendance
     - [ ] Guardian's Details
     - [ ] Student's Details
     - [ ] Assessment Plan
     - [ ] Assessment Plan Result
     - [ ] Student Leave Application
- [ ] User should be able to signup and assign the Guardian's role automatically after signup. There should also be a "Invite Guardian" button.

**Comment by yashodhank** [comment]
Some Additional Features will be very helpful as follows:

- [ ] Online fee payments - Pay fees for tuition, library, hostel, meals, lab, transport, or sports.
- [ ] Directory - Get students, teachers and staff information with real-time updates
- [ ] Homework - Review assignments and get alerts if a child misses an assignment.
- [ ] Push notifications - Using parent monitoring app get notifications on attendance, homework, grades
- [ ] Timetable View - timetable schedule of students for various classes of courses on particular day or for a week and periods, as well as examination schedule.
- [ ] Lesson plans - Access the classroom resources including lesson plans, curriculum guide, standards, and schedules from anywhere and add comments. Monitor classroom instructions and get reports.
- [ ] Admission - Keep parents automatically informed through each step of admission process, from inquiries and application to admission and course enrolment
- [ ] Transportation - View vehicle routes and timings for location. Submit request for assigning transport including details of bus routing and pick up/drop address. View vehicle/driver details.
- [ ] Integrated Email & Messaging - Get automatic email notifications, reminders and SMS alerts on attendance, homework, parent-teacher meetings, fee payments, exams, awards, health and events.
- [ ] Assignments - View details of homework assignments submitted by the student. Check pending, late, incomplete and failed assignments and view instructor details.
- [ ] Fee payments - Access details of various fees categories, invoice and submit payments online. Track payment status in real-time. Get notifications on advance Payments, future charges, etc.
- [ ] News & Events - View school notices, announcements and upcoming events in the calendar, and purchase tickets. Stay informed of the latest news, school holidays, community events, etc.

**Comment by joolsr** [comment]
Just out of Interest, at my Daughter's High School in the UK, we have a Parent Portal which is next to useless, not even with https! And when you login there is very little that you can interact with. Our school uses the company Cap Gemini to administer this poor system and probably pay £1000's every year in fees which is poor when you consider they could implement your whole amazing system and for so much less .....
