### ISSUE TITLE
POS: No warning message on stock zero

### ISSUE THREAD

**Issue by vladucoju** [frappe/erpnext#10683]
Hi,
i am using POS for the first time. I read a lot about features, bugs bounty and till now everything was ok. 
I set up POS profile to update stock in SI, and after i test one invoice with item quantity larger than stock, POS didn't show any warning. I finished my invoice regularly. I was confused. After that i enter into the created SI, and found that update stock was untick (stock wasn't updated). How is this posible when i put update stock in a profile. This is a serious problem for small stores. Easiest solution is to pop up mesage when choosing 0 stock item, and don't let the cashieer to continue. You should also put only stock >0 to be visible. When cashier search the item let it pop up message 0 stock for item.

**Comment by umairsy** [comment]
Similar issues https://github.com/frappe/erpnext/issues/10682
