### ISSUE TITLE
[Feature Request] RFQ By Customer

### ISSUE THREAD

**Issue by addymuliady** [frappe/erpnext#10684]
Hi

I am working towards creating a DocType to track requests for quotation by customers.

**Related Documents (From RFQ By Customers >> Make Quotation)**

- [ ] Quotation
- [ ] RFQ to Supplier

**Related DocType Fields**

- [ ] Add a "No Quote" checkbox field of item line in "Quotation". This is to cater to send to customer a quotation with a mixture of quoted and no quote items.

- [ ] **Add DocType Fields**
- Company
- Customer
- Posting Date
- Expected Delivery Date
- Status - Open,Pending,Quoted,Fully Quoted, No Quote, Cancelled, Manual Closed

Open - RFQ received but no action is yet taken (when user create and saves the document)

Pending – (Status will be reflected upon “Submit” of "RFQ to Supplier” or user should be able to select manually to allow RFQ to be sent to supplier outside ERPNext system)

Quoted – RFQ is partially quoted (example: 2 out of 5 line items are quoted) (System generated Status will be reflected upon partial line items quoted in the Customer Quotation linked to it)

Fully Quoted - All line items in RFQ have been quoted (System generated Status will be reflected upon all line item quoted in the Customer Quotation linked to it)

No Quote – No quote for all line items in RFQ

Cancelled – RFQ is cancelled by customer

Manual Closed – RFQ is manually closed by user

- Workflow State
- Item Table - Item Code, Quantity

- [ ] **Report**
Filter by Company, Date Range, Status/Workflow State

**Validation**

- [ ] Upon "Submit" of Quotation, to check line items and update "RFQ by Customer" status to either "Quoted" or "Fully Quoted"
- [ ] Upon "Submit" of "RFQ for Supplier", update "RFQ by Customer" to "Pending"

**Comment by lamphannguyen** [comment]
How about this issue,
We have the same issue when both customer and supplier also user ERPNext, but supplier only submit RFQ by Customer and no way to make Quotation from RFQ after success to get deal.
