### ISSUE TITLE
Not enough Stock when doing SI 

### ISSUE THREAD

**Issue by Helkyd** [frappe/erpnext#10682]
When the user prepares a Sales Invoice and adds the items, the system should RED (QTD and Item name or bullet) color the item with not enough stock available... this will calls his attention to not submit if the item is a STOCK enabled.
This could be done when or while on Draft.
On the below first item has 1kg in stock so item (QTD and Item name or bullet) should be RED and when saving DRAFT screen message.
![image](https://user-images.githubusercontent.com/20396898/30060762-99f1ac38-923c-11e7-8d7b-b94782b3bb24.png)

This because when the user saves and trying to submit the message comes saying not enough and if he tries to add KGs in stock the SI will not accept due to some time or date controls..

**Comment by LifeP** [comment]
what is the exact error on adding stock?

**Comment by Helkyd** [comment]
Item A current stock 2kg
POS client paid for 2.5Kg 
POS sits on draft,  client gone and paid.
Admin checks SI and sees that was not enough stock for the item reason why!  
So he enters more Kg to the warehouse and when trying to submit again the SI denied... Solution is to untick update stock and later reconciliation
