### ISSUE TITLE
Customize Form & Customize DocType for Item/stock is reseting back to originals after 2-3 days

### ISSUE THREAD

**Issue by Hussam-cleopatra** [frappe/erpnext#10695]
Hi,
Whenever we customize DocType stock and its related form then after few days it is getting back to its default status as if we did nothing!
Any reason behind that ?

**Comment by tundebabzy** [comment]
Hi
It seems you are modifying the inbuilt doctype. If that is the case, `bench update` will wipe out any changes you made.

Please note that we treat such questions on our forum (https://discuss.erpnext.com). We can continue the discussion there if you like

**Comment by Hussam-cleopatra** [comment]
Hi,Yes would like to continue in discuss.erpnext.com but how?Now; for my case & to customize forms permanently what should we do? create a new custom form?Regards,Hussam


-------- Original Message --------
Subject: Re: [frappe/erpnext] Customize Form & Customize DocType for
Item/stock is reseting back to originals after 2-3 days (#10695)
