### ISSUE TITLE
Serial No Popup Window - Warehouse Issue

### ISSUE THREAD

**Issue by akshay83** [frappe/erpnext#10692]
When using update-stock in Sales Invoice and Inserting Serial Nos through the popup dialog, the Serial No value does not seems to be considering selected warehouse. ie. It is listing all the serial nos with respect to the item code, irrespective of warehouse.

We are on following version
ERPNext: v8.x.x-beta (564e8b7) (develop)
Frappe Framework: v8.x.x-beta (20145b2) (develop)

**Comment by umairsy** [comment]
Please report your query on ERPNext community forum. When replicated and validated as bug, we can create a Github Issue for it.

https://discuss.erpnext.com

About an issue, also share screenshots/GIFs.
