### ISSUE TITLE
Setting Item Standard Selling Price leads to Server Error

### ISSUE THREAD

**Issue by bglazier** [frappe/erpnext#10694]
I'm getting a server error "Something Went Wrong" following bench update done last night when trying to set Standard Selling Price on ITEM form.

Anybody else getting this?

**Comment by Zlash65** [comment]
Working for me just fine. Maybe give `bench migrate` a try ?

**Comment by umairsy** [comment]
Please post technical queries on ERPNext community forum.

https://discuss.erpnext.com
