### ISSUE TITLE
[Enhancement] Blank Shipping Address when Creating Documents

### ISSUE THREAD

**Issue by javierwonghf** [frappe/erpnext#10703]
Documents such as PO, SO, SI, PI etc. etc. all pull shipping address once you select a Customer or Supplier. This is because of https://github.com/frappe/erpnext/blob/dab1172a18c9d7ff41c5e8216d76bfe60fabc7b6/erpnext/public/js/utils/party.js#L6

The design isn't very ideal to some businesses whom have a Customer or Supplier with multiple shipping addresses and whom do not want to default a Shipping Address and instead wants the user to select it. There is no simple way in JS to intercept it since all these run on async.

I can modify the function but would like to gather opinion on how we should provide this functionality. 

1. Should we just have a JS variable flag that can be programmatically set perhaps like a `var do_not_set_shipping_address` and let `get_party_details` read this flag and determine whether it should set the shipping address? Users wont be able to set this through the UI and will need to do Custom Scripts to achieve this... or

2. Should we have a setting in "Buying Settings" "Selling Settings", "Stock Settings" and "Account Settings" that allow the admin to set whether the shipping address should be populated for each document i.e. SO, PO, PI, SI, DN etc. - this could be quite messy but users could set this on the UI

What do you guys think?

**Comment by umairsy** [comment]
Will suggest you to post such opinion polls on the community forum as we have more members active on the forum.

https://discuss.erpnext.com

**Comment by bohlian** [comment]
@umairsy no luck with the forum. https://discuss.erpnext.com/t/enhancement-blank-shipping-address-when-creating-documents/28159.

I think perhaps maybe you guys as the core devs can give it a thought and suggest a common design that we can all agree to. Then I can develop the necessary and send the PR. It is a genuine problem.
