### ISSUE TITLE
Update in name series behaving unexpectedly 

### ISSUE THREAD

**Issue by jigartarpara** [frappe/erpnext#10708]
I set one series this POACPL/.#####./.fiscal_year where fiscal_year is X doc-type's field for which this series is defined

problem:
when i set this value to 1000 from UPDATE SERIES section in Naming Series
it'll successfully updated 
but when new document created of X doc-type with above series it will continue with default value which start from 0 
when i checked table tabSeries in database it's showing me unexpected result which is following 

| POACPL/                                                                |      21 |
| POACPL/00002/                                                          |    1000 |
| POACPL/00003/                                                          |    1000 |
| POACPL/00004/                                                          |    1000 |
| POACPL/00005/                                                          |    1000 |
| POACPL/00006/                                                          |    1000 |
| POACPL/00007/                                                          |    1000 |
| POACPL/00008/                                                          |    1000 |
| POACPL/00009/                                                          |    1000 |
| POACPL/00010/                                                          |    1000 |
| POACPL/00011/                                                          |    1000 |
| POACPL/00012/                                                          |    1000 |
| POACPL/00013/                                                          |    1000 |
| POACPL/00014/                                                          |    1000 |
| POACPL/00016/                                                          |    1000 |
| POACPL/00019/                                                          |    1000 |
| POACPL/00021/                                                          |    1000  

so when ever i update this series from UPDATE SERIES section in Naming Series it'll update 
POACPL/ count to increase by one which 22 and create one another series with updated count POACPL/00022/  and value which i added in backend
Please guide for there

**Comment by umairsy** [comment]
Hello,

The example provided above indicates that it is not picking value from the Fiscal Year field at all. The current value specific should have been applied for ####, but it seems that it is applied on the last value in the Naming Series. Can you afford to set Naming Series like POACPL/.fiscal_year/.##### and then check if it works fine for you?

For more support on this query, please start a new post on the community forum.

https://discuss.erpnext.com
