### ISSUE TITLE
erpnext leave application hours

### ISSUE THREAD

**Issue by shenoshadow** [frappe/erpnext#10707]
erpnext has days and halfdays leave

can we add hours and minutes

for example

2 hours leave

**Comment by umairsy** [comment]
Hi,

This feature is not available for now. Perhaps you can use Timesheet to track hours worked by an employee.

https://erpnext.org/docs/user/manual/en/projects/timesheet/timesheet-against-project?

Hope this helps.

**Comment by iMoshi** [comment]
This really needs to happen :) 

@shenoshadow have you ever found a solution?

**Comment by ansiabdo** [comment]
This feature should be exist in this great system
