### ISSUE TITLE
Print format problem of custom Doc Types

### ISSUE THREAD

**Issue by SecASecA** [frappe/erpnext#10709]
Hello,

I've been having problem with the print format of custom doc types i create.
I'm just copying what i wrote to the forum post which i have created sometime ago.

https://discuss.erpnext.com/t/print-format-problem-of-custom-doc-types/21803

> I would like my colleagues to create Technical Specification documents using a predefined template on Erpnext. To do so, i have created a custom DocType called "Technical Specification".
> 
> I have realized that the print format does not show the headers of the sections. To explain briefly i have created a new doc type called Test_Doc and took screenshots.
> 
> As text editor gives us more flexibility, i would like to use text editor for my inputs of the technical specification documents.

<img width="1175" alt="screen shot 2017-03-27 at 17 01 00" src="https://user-images.githubusercontent.com/26192194/30174404-a84e78c4-9403-11e7-8c5e-699d7e567675.png">
<img width="1176" alt="screen shot 2017-03-27 at 17 01 39" src="https://user-images.githubusercontent.com/26192194/30174409-aa40b52a-9403-11e7-8292-afb4f0b6503a.png">

**Comment by umairsy** [comment]
In the Print Format master of that Print Format, ensure that field "Show Section Headings" is checked. In the Print Format Builder, click on "Edit Properties" button to check Print Format Master.

**Comment by umairsy** [comment]
![screen shot 2017-09-12 at 6 57 34 pm](https://user-images.githubusercontent.com/910238/30328243-66ca1c0e-97ec-11e7-97dc-ade436d2b776.png)

**Comment by SecASecA** [comment]
Dear @umairsy,

Thank you for your reply. 
But this is not the solution of the problem i was mentioning.

If you can check the screenshot i have shared, the section headers are named as Section_1 and Section_2. They are well shown in the print format.

But the problem is related to the **headers**. In my example Header_1 and Header_2 are not shown in the print format.

To explain briefly;

In the DocType builder, if i select **text editor** as the type of the row, then the **label** is hidden in the print format. When i change text editor to something else, like "text" or "Small Text",  then it works.

Could you check please?
