### ISSUE TITLE
Multi-currency issues: Grand Total different than Net Total

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#10717]
Company base currency - VND (Vietnam)
Supplier Currency - EUR

In the Purchase Invoice, value for the Grand Total and Net Total is different.

![image00114712d](https://user-images.githubusercontent.com/910238/30210140-f16dd972-94b8-11e7-9a86-674465484c0c.png)

If I multiplied Grand Total in EUR with exchange rate, then value received is Outstanding amount. However, Grand Total in VND is calculated based on the Net Total + other charges in the VND only. My guess is that it doesn't check/calculate with the exchange rate, hence the difference. Please check if that's the case.

**Comment by nabinhait** [comment]
This issue is because of different precision et for net_total and grand_total field. Replied via support ticket in details.
