### ISSUE TITLE
Gross profit report Brand column empty

### ISSUE THREAD

**Issue by Suprazz** [frappe/erpnext#10718]
I edited the Brand field for few items so I can classify them easily in the gross profit report but the column stays empty. Even after a refresh or clear cache. 
Maybe it's because my item was already sold and not with this brand name at the time of the invoice?

And if I select to Group by Item code, the column item group is not available.

**Comment by umairsy** [comment]
Hello,

The Brand will be updated in the new transactions only. In the old transactions, since there was no Brand updated in the master, was not fetched into transactions.
