### ISSUE TITLE
Allow batch editing of items parameters in the report builder.

### ISSUE THREAD

**Issue by Suprazz** [frappe/erpnext#10719]
In the report builder, we can display what we what and on the cells in the column, it's possible to double click to edit the value (eg: change the item group).

We can select multiple cells but we cannot edit multiple at once.

**Comment by umairsy** [comment]
In the report builder, you can only edit fields which are also editable from the form. If Item Group is a read-only field in a form, then it will be non-editable in the report view as well.

From a report, you can edit only one value at a time. For multiple editing, please open main form/document.

**Comment by Suprazz** [comment]
It's not possible to display multiple items in the main form/document. So we must use the report builder or something like that. It would be a very nice feature to have something that allow multiple modification of different items at the same time.
