### ISSUE TITLE
Sales funnel text overlap

### ISSUE THREAD

**Issue by drthilina** [frappe/erpnext#10711]
Hi,
    In the sales funnel the top text are overlapping, please see below,
![image](https://user-images.githubusercontent.com/29944021/30199832-0c95777c-9492-11e7-8386-a0dabe0621b5.png)

Is this a bug or can I change it myself?

BR

**Comment by joolsr** [comment]
I've seen this sometimes myself so believe its probably a bug. I think its beacuse you have Opportunities and Leads both on zero, so the text overlaps the other Doctypes shown with same value

**Comment by mosabamf** [comment]
+1

**Comment by drthilina** [comment]
![image](https://user-images.githubusercontent.com/29944021/38234506-ae8319da-373b-11e8-9215-17843130bfe5.png)
The issue is still persistent

**Comment by enoy19** [comment]
+1

Version:
ERPNext: v13.0.1 (version-13)
Frappe Framework: v13.0.2 (version-13)

In my case, the text overlaps and the canvas size is too small:

![image](https://user-images.githubusercontent.com/24529735/116990746-d49bf680-acd3-11eb-825d-2a20c22c80e3.png)
![image](https://user-images.githubusercontent.com/24529735/116990831-f2695b80-acd3-11eb-89ad-1cfd27923c66.png)

Client: Google Chrome.
