### ISSUE TITLE
Data Import Refactor

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#10712]
- [x] Dashboard for import
- [x] Queue imports, run in background
- [x] If error, download error records only

**Comment by snvora** [comment]
In addition,
Ability to import tags, and file attachments
could be useful.

**Comment by giuseppelamatrice** [comment]
What do you think of this: If there is problem we can delete import?

**Comment by manassolanki** [comment]
Duplicate Timout Issue - https://github.com/frappe/frappe/issues/3445

**Comment by adityaduggal** [comment]
Attachments done to data import tool should not be saved in Home folder instead they should also go into Home/Attachments/ like any other attachment.

Putting the attachments of Data Import tool in Home folder just creates clutter on the home folder and makes it difficult to browse for the folders which are created in the home folder.
