### ISSUE TITLE
Total Row in Gross Profit report shows wrong percentage when filtered

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#10720]
Hi

The Total Row in the Gross Profit report doesn't update when it is filtered and therefore shows the wrong information:

![gross profit percent total issue 1](https://user-images.githubusercontent.com/9269337/30222358-d486793a-94be-11e7-964e-c8a022890017.png)

![gross profit percent total issue 2](https://user-images.githubusercontent.com/9269337/30222372-deee6c84-94be-11e7-92fb-f96e43887cb3.png)

As seen in the screenshots above, the other fields in the Total Row get updated properly when the report is filtered except the 'Gross Profit %' field which remains static

Kindly fix asap

Thanks

**Comment by tundebabzy** [comment]
It seems this is already fixed. The Gross Profit Margin column figures change as expected for me:
![peek 2017-11-29 17-05](https://user-images.githubusercontent.com/818803/33384988-cf5ec1e8-d527-11e7-9926-b265c81e455c.gif)

![screenshot from 2017-11-29 17-08-12](https://user-images.githubusercontent.com/818803/33385164-3cae1370-d528-11e7-83b0-adba440d38fb.png)

![screenshot from 2017-11-29 17-09-25](https://user-images.githubusercontent.com/818803/33385172-40858f6e-d528-11e7-92b8-7ea4b730a7ff.png)
