### ISSUE TITLE
[Enhancement] Amendment of SO and PO without requiring to cancel them

### ISSUE THREAD

**Issue by snvora** [frappe/erpnext#10728]
It is quite common that it may take several weeks to fulfill an order. In such scenario, a lot of terms may change, eg price. Also many times additional quantity of similar products, or additional products may be ordered.

**In existing scenario**, if any document is linked to other document, cancelling of document is not possible. So altogether new PO/SO is required to be created for small quantities. For changes in price, cancellation of all linked documents becomes necessary. 

**Eg:** We create Material Request from SO and in turn PO from Material request. Now suppose if we require to change price of certain product in SO, we shall be required to cancel PO, Material request to amend price in SO.

Amendment is common feature for people dealing with manufacture. We require amendment in 6 / 10 SO's .

**Comment by umairsy** [comment]
Please support/followup for this feature from this Github Issue.

https://github.com/frappe/erpnext/issues/10204
