### ISSUE TITLE
Tax table in invoice print taking more space

### ISSUE THREAD

**Issue by mbauskar** [frappe/erpnext#10724]
In invoice, the tax rate is shown in one line and amount is on new line resulting invoice print to be lengthy.

**Comment by maheshengg** [comment]
Pls check if this can be resolved at earliest

**Comment by umairsy** [comment]
Hi,

Can you please share the screenshot indicating an issue? In my test account, Tax rate and amount both correctly shown in a single row only.

![screen shot 2017-09-11 at 12 38 22 pm](https://user-images.githubusercontent.com/910238/30262366-41650900-96ee-11e7-835b-5e02e8a8366f.png)

**Comment by maheshengg** [comment]
Please check the tax breakup table, eating much vertical space of the invoice.

![image](https://user-images.githubusercontent.com/1590079/30270868-c8f1e010-970b-11e7-9d17-935c822fd311.png)

**Comment by nabinhait** [comment]
Fixed the issue and released.

**Comment by maheshengg** [comment]
Looks like solved. Now dont change this again.
