### ISSUE TITLE
Delivery note to billing issue.

### ISSUE THREAD

**Issue by Arundhatii** [frappe/erpnext#10726]
Reported via https://frappe.erpnext.com/desk#Form/Issue/WN-SUP27806

When create a Delivery advice for example 10 units and then create Sales Return for 4 units.
When creating Sales invoice from Delivery note it shows all 10 on invoices for billing instead of 6 units.
![delivery note issue](https://user-images.githubusercontent.com/20164097/30246723-8d0751e4-961f-11e7-839f-1af5f0588992.gif)

**Comment by tundebabzy** [comment]
Hi @Arundhatii 
As expected, the Delivery Note has no knowledge about the Sales Return. However, the user should be able to add the details from the Sales Return to the invoice.

When fix is merged, users will be able to add the sales return to the created invoice:
![peek 2017-09-12 17-25](https://user-images.githubusercontent.com/818803/30364994-45e66c78-985e-11e7-9399-629c27dd28c4.gif)
