### ISSUE TITLE
Itemwise Taxes in Purchase Order

### ISSUE THREAD

**Issue by deepaknaik007** [frappe/erpnext#10738]
Hi,

Have followed the process given in the document, which says Item tax precedes the tax in PO document.
Still its not getting showing the itemwise tax break up or calculation.

Deepak N

**Comment by nabinhait** [comment]
If you are setting item tax in Item master, after making the transactions, then the rate will not affect those transactions. But if you make any new transactions, the rate mentioned in Item Tax table will be applied there.

**Comment by umairsy** [comment]
Request you to post this query on the ERPNext community forum.

https://discuss.erpnext.com

Please also provide screenshots indicating the issue.
