### ISSUE TITLE
incorrect sales order status - overdue is shown

### ISSUE THREAD

**Issue by alfredhy** [frappe/erpnext#10748]
<img width="1184" alt="default" src="https://user-images.githubusercontent.com/30999458/30310675-3934c7b2-97c4-11e7-8e24-8d96419f0781.png">

my system have four sales orders shown the status wrong. 

SO-00003 and SO-00002 are paid already
SO-00009 and SO-00013 are still waiting to pay but not overdue yet.

It is under frappe cloud account
My account is esilktrade

**Comment by umairsy** [comment]
Hello,

Currently, logic of Overdue status is based on the Expected Delivery Date field in the Sales Order. If order is not completed delivered and billed by Expected Delivery Date, then it's status is updated as Overdue.
