### ISSUE TITLE
Fail to delete custom report

### ISSUE THREAD

**Issue by alfredhy** [frappe/erpnext#10749]
<img width="1216" alt="default" src="https://user-images.githubusercontent.com/30999458/30310813-f66e2c24-97c4-11e7-9b91-6552a187bf7b.png">

I created an custom report but cannot delete

**Comment by umairsy** [comment]
Please go to Reports list (from Search Bar) and delete report from the list.

**Comment by Ashuar** [comment]
done the same but not working
