### ISSUE TITLE
 Something went wrong Server Error: Please check your server logs or contact tech support.

### ISSUE THREAD

**Issue by Herbert6917** [frappe/erpnext#10746]
When I click in the Brand Field while I add a new item I get the above message.  I am using the online version and I do not think I have server logs.  This does not happen with an existing item

**Comment by mbauskar** [comment]
@Herbert6917,

Can you share the error traceback from the browser's console?

**Comment by Herbert6917** [comment]
Yes. Please explain how.

**Comment by adam-je** [comment]
Try bench --site [sitename] migrate

**Comment by Herbert6917** [comment]
Hi I am on the hosted version.  I do not think I can run "bench --site [sitename] migrate".  If I can please explain how.

**Comment by adam-je** [comment]
You shouldnt be able to or need to on the hosted version. You can contact the support team if any issues. How's your experience so far, any kinks?

**Comment by mbauskar** [comment]
@Herbert6917,

You can get the error traceback from browser's console please check the following link to open the console and share the error traceback.

 https://stackoverflow.com/questions/66420/how-do-you-launch-the-javascript-debugger-in-google-chrome.

**Comment by Herbert6917** [comment]
I think I have contacted support a few times on this issue and this is where it got me. I have had to start over with new accounts about 3 times because of issues like this that never got resolved.  I do not code so I have to rely on answers from you guys. Sometimes I get them and other times no replies or no one understands my questions.  I started last winter and am still trying. I am learning slowly but then I hit a wall like this and loose my momentum and forget some of what I learned. I think I'm almost at the point where I will have a basic set up with my data and can experiment with live data. I just want to know why I can't continue adding new items on this account.
 Thank you
Herb

FOR DUCK, LOCTITE, SHURTECH AND OUR PAINT AND HARDWARE CATALOGS CLICK HERE.

New United Distributing Co. Inc.   6917 Carnegie Ave.  Cleveland Ohio  44103  800-800-7343  Fax 216-881-4073 newunited.biz

**Comment by Herbert6917** [comment]
Hi jaichavan,
Thanks for checking in on me.  Its only been a year and 4 months.  My how time flies!  After not trying for 9 months or so I am again entering data and customizing.  It seems that importing data can confuse the software if you do too many  in a day.  If I wait a day or so it starts to work again.  Also I am breaking the imports up and only using a few headings at a time.  I have seen easier methods of uploading CSV files and have had a hard time figuring out what some headings in the templates mean.  Once I get the data uploaded I will try to hire someone to help with the work flows and make sure the Accounting accounts are set up correctly.
Thank you again.
