### ISSUE TITLE
Bom replace Tool

### ISSUE THREAD

**Issue by Helkyd** [frappe/erpnext#10757]
Based on this https://discuss.erpnext.com/t/update-from-8-11-1-importerror-module-import-failed-for-bom-replace-tool/28096

No directory bom replace tool under manufacturing/doctype !!

**Comment by umairsy** [comment]
In the Manufacturing module check:

Tools > BOM Update Tool

![screen shot 2017-09-13 at 10 59 00 am](https://user-images.githubusercontent.com/910238/30361136-ea653cfc-9872-11e7-91c3-1792ee79d4b3.png)
