### ISSUE TITLE
cannot show to do list

### ISSUE THREAD

**Issue by alfredhy** [frappe/erpnext#10750]
<img width="1206" alt="default" src="https://user-images.githubusercontent.com/30999458/30310986-d7a04790-97c5-11e7-8fb1-12134e6bfdf9.png">

I have one task under to do list but cannot find in my list. The task is allocated by me. 

Account: esilktrade

**Comment by umairsy** [comment]
Remove filters (Open) and (User) and then check.

Request you to post such queries on ERPNext community Forum.

https://discuss.erpnext.com
