### ISSUE TITLE
Limit localized print formats to a specific country (or region)

### ISSUE THREAD

**Issue by chdecultot** [frappe/erpnext#10767]
Hi,

It would be really nice to limit specific print formats, like GST invoices, to a specific country or region, the same way regional modules are limited.

For example, the country is set to France in my settings, so I shouldn't have the possibility to print a GST invoice, since I can't set it up and it's not applicable in this country, but it appears in the available print formats:

![image](https://user-images.githubusercontent.com/4903591/30365429-0499141e-9868-11e7-9bc6-4e2f7879cfb9.png)

It would be nice if it could be limited to India only for example. It can be confusing for end users.

**Comment by deepeshgarg007** [comment]
@chdecultot I think this should be resolved now. In the latest versions, this has been separated into regional apps
