### ISSUE TITLE
Incorrect Sales Order Status - Overdue - fail to delete DN

### ISSUE THREAD

**Issue by alfredhy** [frappe/erpnext#10764]
This order has already delivered and paid
Here is the order List,
<img width="1194" alt="default" src="https://user-images.githubusercontent.com/30999458/30363911-954a2e4a-9894-11e7-8329-872065df8b7b.png">
This is the order details:
<img width="1191" alt="default" src="https://user-images.githubusercontent.com/30999458/30363960-ca6f8958-9894-11e7-97f4-ca06d6394269.png">
<img width="989" alt="default" src="https://user-images.githubusercontent.com/30999458/30363985-e2dcec56-9894-11e7-9196-f5030a4c1b1e.png">
This is the delivery note list, it is strange the delivery note has four records created. It supposed to be one record
<img width="1209" alt="default" src="https://user-images.githubusercontent.com/30999458/30364019-00fcd69c-9895-11e7-94ab-d27514b34bd1.png">

I tried to delete the record but fail
<img width="1185" alt="default" src="https://user-images.githubusercontent.com/30999458/30364193-bf6636f0-9895-11e7-906e-7f9bc7fb78ae.png">

**Comment by umairsy** [comment]
Hi,

Sales Order's screenshot suggests that third item in the list is still pending for delivery/billing. Please check.

If a Delivery Note is already submitted, you won't be able to delete it right away. You must cancel it first and then delete.

https://www.youtube.com/watch?v=et7TKXiOycQ

Please post your functional and technical queries on the ERPNext community forum first.

https://discuss.erpnext.com
