### ISSUE TITLE
Fail to remove desktop icon

### ISSUE THREAD

**Issue by alfredhy** [frappe/erpnext#10761]
I deleted a custom report but the icon still shows on the desktop, which cannot remove or hide
<img width="1153" alt="default" src="https://user-images.githubusercontent.com/30999458/30361847-bdb587c0-988b-11e7-8d45-703094dddc73.png">

<img width="1170" alt="default" src="https://user-images.githubusercontent.com/30999458/30361805-8cab4714-988b-11e7-903c-32b2d4fff407.png">

**Comment by umairsy** [comment]
Please post this query on the ERPNext community forum.

https://discuss.erpnext.com
