### ISSUE TITLE
[Bug] Due date calculation in Purchase invoice

### ISSUE THREAD

**Issue by snvora** [frappe/erpnext#10773]
Should be from date of Supplier invoice Date instead of posting date

**Comment by maheshengg** [comment]
Option required, depending on users.  Users may also calculate from the date of posting date

**Comment by snvora** [comment]
Hi,

Date of Receipt of Material == Posting date of Purchase receipt
Date when Invoice is verified and booked == Posting date of Purchase Invoice.

As part of credit terms, generally 2 types are more prevalent, 
- From the date of invoice
- From the date of receipt of material.

So maybe posting date in purchase invoice may not be relevant for determining due date.

**Comment by snvora** [comment]
This Issue gets resolved in V10. Hence closing. Thanks

**Comment by snvora** [comment]
Not yet resolved.

**Comment by tundebabzy** [comment]
@snvora #12180 suffices right?

**Comment by snvora** [comment]
Closed with #12874
