### ISSUE TITLE
unknown column  in Print Format patch

### ISSUE THREAD

**Issue by clarkejj** [frappe/erpnext#10774]
Here's the problem report with trace: 

https://discuss.erpnext.com/t/error-on-applying-executing-frappe-patches-v7-1/28204

Rushab says the fix should be added in the patch file itself

**Comment by clarkejj** [comment]
I suspect the fix is to replace this in the patch:

frappe.reload_doctype('Print Format')

with say this:

frappe.db.sql ("""ALTER TABLE `tabPrint Format` ADD align_labels_left INT""")

**Comment by nabinhait** [comment]
Pushed a fix in hotfix branch.
https://github.com/frappe/frappe/commit/4d4e5dcc02b5e1056a1be00d72c5abcd92e3e11c
