### ISSUE TITLE
protected fields

### ISSUE THREAD

**Issue by MRHAWKES** [frappe/erpnext#10776]
I need to enter credit card information on the Sales order but do not want it printed nor do I want the data accessed without a specific field password.  Is that possible?

**Comment by rohitwaghchaure** [comment]
Using customize form you can hide the field on the print

Goto customize form > select doctype as Sales Order > goto field > enable field Print Hide

![screen shot 2017-09-18 at 12 14 35 pm](https://user-images.githubusercontent.com/8780500/30531571-da6aaf0a-9c6c-11e7-93ba-29ea66a688de.png)

Q: Not do I want the data accessed without a specific field password
You need to write your own custom script, for more help make post on [forum](https://discuss.erpnext.com/)
