### ISSUE TITLE
beta.erpnext.com asking for login id & password

### ISSUE THREAD

**Issue by mdwala** [frappe/erpnext#10780]
[beta.erpnext.com](url)

is asking login id & password! It should work same way as demo.erpnext.com(without any id password)

![login issue](https://user-images.githubusercontent.com/24455908/30414056-b8a0f344-9932-11e7-9f36-1d16db9391a6.png)

**Comment by umairsy** [comment]
Fixed. Please check beta.erpnext.com now.

Thanks for indicating this issue.

**Comment by adam-je** [comment]
Its working for me
