### ISSUE TITLE
Project wont Reflect General Ledger if linked via Purchase Invoice

### ISSUE THREAD

**Issue by MaxMorais** [frappe/erpnext#10797]
Hi Guys!

- When one Puchase Invoice is linked with a Project, the information of the project is not reflected on the General Ledger

Demo - 
https://demo.erpnext.com/desk#Form/Purchase%20Invoice/PINV-00018

![nan duskin pinv 00018](https://user-images.githubusercontent.com/1288676/30440476-01bc363c-994d-11e7-8958-c4cef0b710c6.png)

![general ledger](https://user-images.githubusercontent.com/1288676/30440485-0ee925a4-994d-11e7-8164-002db74afa85.png)

**Comment by umairsy** [comment]
Hello @MaxMorais,

In the purchase transaction, the Project field in the Item table is what is considered and rendered in the General Ledger report. This is because we might make a consolidated purchase for the items belonging to different Projects.

**Comment by aptech-admin** [comment]
Hi @umairsy , 

This issue is still not resolved and, in my opinion, is very important.  Could we investigate this again please?

Thank you

**Comment by bern-lefebvre** [comment]
Hi @umairsy, 

After trying many scenario, here's my finding:
- When doing this cycle: Sales Order (Drop Ship) > Purchase Order (put Project on the item line) > Purchase Invoice, Project is reflected on the G/L
- Any other scenario, Project is NOT reflected on the G/L

Is there a particular reason why is it working only in the case of a Drop Ship?

Thank you
