### ISSUE TITLE
Sales Order gives "Delivery Date cannot be after Sales Order Date" error

### ISSUE THREAD

**Issue by asmith1** [frappe/erpnext#10795]
When submitting a sales order, we sometimes experience this error, when the delivery date is set for after (or the same as) the sales order date, so this is not a real error. Pressing submit multiple times/redoing the sales order solves the problem.

**Comment by umairsy** [comment]
Hi,

As you rightly indicated, it is a notification alert for the user, and not a mandatory fix required. If user is okay with it, he/she can proceed with the submission.
