### ISSUE TITLE
Fetching default bom on purchase receipt

### ISSUE THREAD

**Issue by saurabh6790** [frappe/erpnext#10794]
WN-SUP27901
---
- While creating Purchase Receipt for subcontracting item, system fetching default BOM instead of fetching BOM Specified on Purchase Order.

**Comment by snvora** [comment]
Hi,

2 ways i can think of - to create purchase receipt are as follows,
- New Purchase receipt --> Give name of supplier --> Get items from purchase order.
- Open relevant purchase order --> Make Purchase receipt.

I feel you tried 1st option. Please try 2nd option, does the problem still persist?
