### ISSUE TITLE
Factur-X/ZUGFeRD 2.0: electronic invoicing standard for Germany & France

### ISSUE THREAD

**Issue by chdecultot** [frappe/erpnext#10812]
Hi,

Some Odoo Developers have created a Python Library to allow the generation of invoices with the new Factur-X standard for France and Germany.

It could be interesting to integrate it with ERPNext in a near future:

https://github.com/akretion/factur-x

**Comment by lasalesi** [comment]
ZUGFeRD capabilities for ERPNext have been built into ERPNextSwiss:

https://github.com/libracore/erpnextswiss/tree/master/erpnextswiss/erpnextswiss/zugferd

Currently, it supports creating sales invoices with ZUGFeRD content. The ZUGFeRD wizard is under development (drop a ZUGFeRD file on ERPNext and automatically create a purchase invoice from it.

More information on https://github.com/libracore/erpnextswiss/wiki/ZUGFeRD-(and-FacturX)

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.
