### ISSUE TITLE
Issuing "Return / Credit note" from Sales Invoice to automatically issue "Sales Return" from Delivery Note.  

### ISSUE THREAD

**Issue by stepsibg** [frappe/erpnext#10821]
Right now, if any item is returned by the customer we make "Return / Credit Note" from Sales invoice and then go to delivery note and make a "Sales Return".

Is there a way we issue sales return and delivery sales return is automatically credited against it because all the documents are linked and serial numbers are provided?

**Comment by umairsy** [comment]
This feature is not available for now. However, if you make a delivery entry from the Sales Invoice itself, by checking Update Stock field, then you will be able to make a common return and credit note entry as well. If delivery and invoice entries are separate, and return entries will be separate as well.

**Comment by stepsibg** [comment]
@umairsy Can we support this feature by paying it?

**Comment by umairsy** [comment]
Sure. You can create a bounty for this feature.

https://erpnext.org/bounty

**Comment by stepsibg** [comment]
Bountry created.

https://erpnext.org/bounties/issuing-%22return-/-credit-note%22-from-sales-invoice-to-automatically-issue-%22sales-return%22-from-delivery-note.
