### ISSUE TITLE
Translation Issue in cheque print template doctype

### ISSUE THREAD

**Issue by Mohd200** [frappe/erpnext#10829]
Good Day Everyone.
There is an HTML doc field that I need to translate into Arabic.
I tried to use the Translation DOC TYPE but it was useless.
I would be much appreciative to anyone who could help me.

![capture13](https://user-images.githubusercontent.com/32062135/30539506-6667019e-9c7b-11e7-98c3-89f2753b0d1e.PNG)

![1235468949](https://user-images.githubusercontent.com/32062135/30539514-783e019c-9c7b-11e7-8e8a-2ad555d1b044.PNG)

**Comment by umairsy** [comment]
Please post your functional and technical queries on ERPNext community forum.

https://discuss.erpnext.com

To be able to translate, this field should have a label. If added, Custom Translation feature should work. For more support, please post this on the community forum.
