### ISSUE TITLE
[ Feature Request ] New DocType for Call and Appointment

### ISSUE THREAD

**Issue by giuseppelamatrice** [frappe/erpnext#10825]
"To do" is not best way to manage **call** and **appointment**.

I suggest to do this:
- [ ] create "call" doctype: (
call type: in/out; 
call purpose: demo/support/commercial
contact name: John Smith
releted to: campaign (Google AdWords)
call details: current call / completed call / schedule call
call duration: 36m 46s
note: best interest save time to manage document

- [ ] create "appointment" doctype: 
title: get document
location: Corso Garibaldi 3, 20143 Milan, Italy
from: 18/09/2017 13:00 
to: 18/09/2017 14:00
Partecipant: Me
releted to: lead/contact/opportunity (ex. Giuseppe Lamatrice)

- [ ] add "call" on lead and customer app
- [ ] add "appointment" on lead and customer app

--------------------------------------------------------------------------------------
**Call example:**
![image](https://user-images.githubusercontent.com/4445879/30536254-62a667fe-9c65-11e7-984a-8a7037ac8415.png)

--------------------------------------------------------------------------------------

**Appointment example:**
![image](https://user-images.githubusercontent.com/4445879/30536568-96fdfd54-9c66-11e7-9953-de0cfff7e728.png)

--------------------------------------------------------------------------------------

**Customer example:**
![image](https://user-images.githubusercontent.com/4445879/30537472-0f8efdd8-9c6a-11e7-8ee2-77645af79976.png)

**Comment by joolsr** [comment]
When you send an email. If you unclick, 'Send as Email' at the bottom, you will see that you can set Communication medium, and a lot of the functionality is (albeit quite hidden) here already

**Comment by giuseppelamatrice** [comment]
It is more convenient read all information on lead/customer in one page.

**Comment by joolsr** [comment]
Yes agreed. I was just pointing out that the functionality bis there but it needs significant reformatting to make it work as required

Julian

⁣Sent from BlueMail ​

**Comment by umairsy** [comment]
Just checking, would providing an option to create Timesheet from Lead/Opportunity/Quotation help for tracking appointment?

**Comment by giuseppelamatrice** [comment]
It is better use different doctype:
- task: for to do list (ex. Fix computer)
- call: for manage call in/out (ex. Proposition to hot lead)
- event: for manage event (ex. First meet With customer) 

Task, call, event are similar but there are different information (see screenshot attached).

**Comment by giuseppelamatrice** [comment]
I propose to add 2 fields on "to do" tool: 
- [ ] partner type  (lead / opportunity / customer / supplier)
- [ ] partner (partner name)

And same fields on "calendar" tool.

**Comment by sbkolate** [comment]
@giuseppelamatrice 
ToDo is working for US.
On top of ToDo we developed feature to add interaction. If you think its generic, then I can send pull request.

Please check screenshot in following pdf.

https://drive.google.com/file/d/0B7hi3l0nL56dSHJ3SllQY2oxcjA/view?usp=sharing

**Comment by giuseppelamatrice** [comment]
@sbkolate 
Good. I think "to do" is too generic.
I propose to implement "Call" DocType and "Appointment" DocType as attached screenshot.

In this way we can:
- split task from other things;
- organize calls and appointments on other apps (e.g. customer, supplier).

**Comment by joolsr** [comment]
@sbkolate great piece of work. I need to look at more carefully but I think this would be a great benefit to be added to core ;-)

**Comment by joolsr** [comment]
@sbkolate For the 'Type of Interaction', what types are available?

Also - small note - on the Message box that says 'Interaction Submited Successfully', please note that Submitted on your PDF is spelt wrongly. ie it should be submi_tt_ed not submi_t_ed 

Great piece of work  :-)

**Comment by sbkolate** [comment]
@joolsr  @giuseppelamatrice 
Type of interaction we added Skype, Whatsapp, WebEx, call, Visit
I will fix message.

We have added popup for interaction, its creating communication and ToDo, So ToDo will give reminder for next call/ interaction
If expense claim is added then only it create expense claim. 

@giuseppelamatrice Interaction is similar to your call doc, and for reminder we are using ToDo.

For adding core, I will work on mockup and feature request.

**Comment by joolsr** [comment]
@sbkolate I'm wondering if we should also add to the types of interaction 'Email'. Now I know this sounds counter intuitive as emails should be received into the Opportunity and history. But we have the situation occasionally that emails are received that may not be forwarded into ERPNext by a colleague and thus it could be useful to have this extra interaction type added.

That said, I appreciate this could be quite confusing for newcomers to ERPNext so if anyone has any further input on this I'd be pleased to hear it.

**Comment by basdereus84** [comment]
> That said, I appreciate this could be quite confusing for newcomers to ERPNext so if anyone has any further input on this I'd be pleased to hear it.

Maybe call it "Email outside ERPNext" ?

This would be a very useful feature. I've posted a feature request a couple of months ago to be able to set a follow up for a quotation and sales order as well, just the way it currently works with leads and opportunity. This would be a very nice addition/integration for that. I hope it makes it to the core.

**Comment by sbkolate** [comment]
Hello,

Is this generic request?
We have one post on forum, to see all related communication.

https://discuss.erpnext.com/t/how-to-view-all-related-communication-with-a-contact-lead-customer-or-supplier/33421 

If its generic, then I can send pull request to add Interaction/ Appointment/ Meeting Details
It will also enable to add expense claim for meeting and reports to see all interaction.

Thanks,
Sam

**Comment by basdereus84** [comment]
Although I don't think your solution will allow us to see all related communication as I was asking for in my forum post, I do think it would be a very nice addition to the CRM module of ERPNext. 

I did some playing around with Odoo 11 and the ability to schedule and view calls, meetings etc. with contacts seems to be far better integrated into Odoo. I think your solution is good step to get this same type of integration into ERPNext.

**Comment by joolsr** [comment]
As I mentioned before a few times there IS a somewhat hidden feature with everything you want. The ability to add phone calls, messages, etc is there but its really, really hidden. See video below:-

![peek 2018-02-05 16-06](https://user-images.githubusercontent.com/934876/35814780-d2b95ff0-0a8e-11e8-8bf6-7d8643661417.gif)

I think this functionality in terms of the underlying capabilities is fine, but its a far better method to show Phone messages and different forms of Communications. Its almost as is it was hidden on purpose ... 

But the doctype supports what you need to an extent so we should improve upon the GUI rather than teh infrastructure IMHO ..

**Comment by basdereus84** [comment]
@joolsr I agree with you that the function to log a call or visit is ridiculously hidden away in the send email window. I think that this solution presented by @giuseppelamatrice adds more than only a way to log a phone call. I see it as a way to easily log but also to schedule calls, meetings etc.
If you look at this video from Odoo 11: https://www.youtube.com/watch?v=r1Wq2ka1DMU You'll see that you can schedule events from a record. 

We have the similar ability by using the "Assign to" function but it's very limited. You can only add one todo for each user. If you change the message inside the ToDo record it's not trackable from within the record from which you created the todo in the first place. It's also not possible to get an overview of the scheduled events for a certain record.

**Comment by joolsr** [comment]
@basdereus84 Just a  note to say that you obviously feel strongly about improving CRM and email facilities. Why don't you join the ERPNext Community CRM/Email group of which I'm a member so you can add your voice and help improve the application ? We will meet virtually tomorrow at 7.30am GMT 

I cant remember how you join as such but you need to speak with Antonius Tara who is mainly heading things for now

**Comment by joolsr** [comment]
If you want to join us for the meet tomorrow, let me know and I'll add you to the group

**Comment by sbkolate** [comment]
@basdereus84 We have another doctype as interaction, it will enable so see all communication and reminders to users to take follow ups with communication.

**Comment by chdecultot** [comment]
Hi guys,

I just pushed a PR to Frappe to provide the basis for this feature.
I have also added a new DocType called "Call" in ERPNext. Some proposed fields are still missing because I wait for Frappe's validation before going further.

Please don't hesitate to review this proposal and give some feedbacks.

Thanks!

**Comment by chdecultot** [comment]
Hi Joolsr,

Thanks for your kind words.
I am still working on it and actually based on the first feedbacks I have received, I have changed my mind regarding creating new Doctypes for Call and Appointment.

Whereas I do think that it could be better managed by having its own documents, the current design of Frappe/ERPNext would not allow a user to see all his events/calls/appointments in a single calendar. Which is a huge UX problem.

It is already an issue experienced with the ToDo/Event doctypes and I think we should be careful about introducing further siloed information.

Therefore, I am currently trying to tweak the Event doctype to allow the creation of categories (Call, Meeting,...) and improve the general experience with this doctype.

The general design of Frappe's PR #6113 is still similar as what you can see in the Gifs.

If you have any comment, proposition regarding how we could enhance the UX of the integration between events/interactions in the CRM please don't hesitate !

And yes, let's hope it could be rapidly merged into the core once it is finalized.

Have a nice day!

**Comment by joolsr** [comment]
Hi again Charles Henri @chdecultot 

Yes, its obvious you've got a good handle on this. I wasn't aware of the issues of viewing different types of date related doctypes on the same calendar for one user but it did occur to me that a calendar view is kind of essential and expected. 
I'll keep an eye on your updates and if you have a staging server I can access to try your branch I'm happy to.
I think you've linked to the wrong issue number above BTW I couldn't see that it was related .. ;-)
