### ISSUE TITLE
patch 'make_subscription_from_recurring_data' reports ValueError: Unknown string format with validate_next_schedule_date

### ISSUE THREAD

**Issue by clarkejj** [frappe/erpnext#10833]
Rushabh advises: add this to GitHub Issues and tag as “bug”

https://discuss.erpnext.com/t/migrate-error-v8-7/28267

(How do I label it as a 'bug' the right hand side Assignees, Labels etc are greyed out...?)

**Comment by rohitwaghchaure** [comment]
Fixed via https://github.com/frappe/erpnext/pull/10827
