### ISSUE TITLE
Issue with adding attachment in Email. 

### ISSUE THREAD

**Issue by Arundhatii** [frappe/erpnext#10837]
Adding an attachment in Email have a issue. Though the drag an drop is working fine. Refer the gif.

![attach issue](https://user-images.githubusercontent.com/20164097/30574153-c3ae0ea2-9d15-11e7-9b7f-55b6e51401bd.gif)

![screen shot 2017-09-18 at 11 34 56 pm](https://user-images.githubusercontent.com/20164097/30574187-f9afebe2-9d15-11e7-8eb5-d171d5c624f4.png)

**Comment by manassolanki** [comment]
Working fine now.
