### ISSUE TITLE
Fleshing out Campaign Form

### ISSUE THREAD

**Issue by lxnow** [frappe/erpnext#1083]
Expand the campaign form which is currently just a text box.  There are two levels of improvements that can be made: workflow and the form content.

**Form Content**
The following fields should be included as standard:
- Doc numbering series
- Customer (link doc)
- Starting date
- Ending date
- Budget (currency)
- Objective (data or link to a new objective form list)
- Type of Activity (data or link to a new _activity type_ form list)
- Campaign title (data)
- Campaign details (data)
- Brands covered (multi-select or checkboxes or table)
- Product groups covered (multi-select or checkboxes or table)
- Products covered (multi-select or checkboxes or table)
- Remarks
- Approval Status

**Workflow**
A propose-review-approve/reject workflow similar to how expense reports are done:
1. User submit campaign proposal
2. Approver role reviews and approves campaign proposal, making edits as necessary
3. Approval = submit status
4. Disapproval = disapproved/cancel
5. Approved campaigns can then later be referenced for accounting entries and customer reviews

Essentially, it's a simple multi-user record-keeping tool. 

Most of these can be done by a combination of custom fields and Workflow engine even on SAAS version of ERPNext. However, the key thing is to make Campaign forms submittable, i.e. locked down, to avoid further edits in the future.

**Comment by Arundhatii** [comment]
Closing the issue for now as no further discussion or similar requirement is raised. Please feel free to reopen if it is still relevant.
