### ISSUE TITLE
Multiple Company - Address defaulting does not work as expected

### ISSUE THREAD

**Issue by PawanMeh** [frappe/erpnext#10840]
In case of multiple companies, Sales Invoice does not default the address when company is changed.

![multiple company issue](https://user-images.githubusercontent.com/20460498/30578686-d84b87be-9d32-11e7-8be8-b25258fe2dd5.gif)

**Comment by PawanMeh** [comment]
PR #10844 has been sent for this.

**Comment by tundebabzy** [comment]
merged
