### ISSUE TITLE
Issue with Account Receivable and Payable Report.

### ISSUE THREAD

**Issue by Arundhatii** [frappe/erpnext#10856]
Reported via https://frappe.erpnext.com/desk#Form/Issue/WN-SUP27767

The Account Receivable report is showing the data even for those Customers for which there is not pending transaction. It is happening for only for the customer with Zero Balance.

Please refer the gif. 
![a c rec issue](https://user-images.githubusercontent.com/20164097/30608177-2805656a-9d95-11e7-904d-dea986af0883.gif)

**Comment by tundebabzy** [comment]
Hi @Arundhatii 
Can you confirm that this problem still exists? It's working well on my setup

**Comment by tundebabzy** [comment]
is this still an issue?
