### ISSUE TITLE
Flexible tax rules required in ERPNext

### ISSUE THREAD

**Issue by dawoodjee** [frappe/erpnext#10862]
Some countries have complex tax requirement such as tax bands. Similar to HR taxation, whereby when income exceeds a specific thresholds, an amount is chargeable. E.g.:

Income                                $10,000.00

- Flat sales tax 16%:              $160
- First $150 @ $0:                $0
- $150.1 to $300 @$30:       $30
- $300.1 to $600 @$60:       $60
- $600.1 to $900 @$70:       $70
- $900.1 and above @$10%: $10
                                        -----------
So total sales taxes due is:      $330
                                        =======

The most practical way to design this into ERPNext is replicating the rule-based deductable method used in Salary Structure's Deductions (see image below). Since this functionality works well from there. Putting this in Tax rules.

![tax rules](https://user-images.githubusercontent.com/7912989/30643752-78d4016a-9e10-11e7-9d99-72ed0931ae8c.JPG)

Is this functionality possible or is there any related projects?

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.
