### ISSUE TITLE
Items filter based on item group

### ISSUE THREAD

**Issue by AlaaBadry** [frappe/erpnext#10864]
how to filter item based on selection of item group so when select item group **in item group filed** the items only belongs to this group will appear in **item name filed**

**Comment by joezsweet** [comment]
You've to override query, please have a look at manual:

https://frappe.io/docs/user/en/guides/app-development/overriding-link-query-by-custom-script

and 

http://discuss.erpnext.com

P.S. next time post this kind of request to the forum.

**Comment by AlaaBadry** [comment]
I posted before on discuss.erpnext.com and one of foundation told me to make an issue here 
https://discuss.erpnext.com/t/items-filter-based-on-item-group/28266

**Comment by joezsweet** [comment]
Se lo  ..did you try using the link I sent you?

**Comment by AlaaBadry** [comment]
Thanks for your support
I did but no one of them solve my issue

**Comment by joezsweet** [comment]
Where did u explain?

**Comment by AlaaBadry** [comment]
I mean the examples in the link you send to me all is depended on static value but the filter i need based on custom field type link and i don't know how i can filter it based on selection of the other field so i need when select for example item group services i got the only items belongs to service group that is it

**Comment by joezsweet** [comment]
If i'm getting ur point correctly, you just have to change static value to `frm.doc.item_group` (if u need to filter by `Item Group`) ..

**Comment by AlaaBadry** [comment]
i'm sorry for inconveniencing your but could you post the complete code to do that because i have 2 days stack in this issue

**Comment by joezsweet** [comment]
It's kind of hard to do, without knowing on what doctpype you need to apply, please share all details

**Comment by AlaaBadry** [comment]
doctype : Event 
custom field 1 called : Course Family (link to Item group )
custom field 2 called : Course Name (link to Item )

For your information in my customization i will use item group as a course family and item as a course name

**Comment by AlaaBadry** [comment]
Dear @joezsweet 
Any update

**Comment by joezsweet** [comment]
try to set a custom script in `Event` doctype, like:
```
frappe.ui.form.on ("Event", {
   course_family: function(frm) {
        cur_frm.set_query("course_name", function() {
           return {
               "filters": {
                   "item_group": frm.doc.course_family
               }
           };
       });
   }
});
```

**Comment by AlaaBadry** [comment]
Thanks a million Its working 
Kindly please explain the code

**Comment by joezsweet** [comment]
have a look at the manual:

https://frappe.io/docs/user/en/guides/app-development/overriding-link-query-by-custom-script

**Comment by AlaaBadry** [comment]
Dear Joezweet , 
i'm highly appreciate your effort but no explanation there however  i need to know how i can add the same filter to another fields in the same document  
Thanks in advance

**Comment by joezsweet** [comment]
You need to hire a developer then ..

**Comment by AlaaBadry** [comment]
Did you mean online developer and what this cost
