### ISSUE TITLE
Customer credit limits

### ISSUE THREAD

**Issue by turner-james** [frappe/erpnext#10861]
At present, ERPNext includes Customer Sales Orders in the calculation of the available credit (against the customer credit limit) that the customer has access to.

I understand that this is a useful function for many users - to enable them to be alerted to credit limitations right when Sales Orders are generated, rather than waiting for the point of delivery to find out that they are unable to supply the customer because of unavailable credit limit.

However, this does not work for some industries - including our own. We are a brick manufacturer, and we receive BULK SALES ORDERS from customers - for quantities of product that may stretch many months over the duration of a building project. The customer will be making payments every month, to ensure that they stay within their credit limit - but we need to be able to accept sales orders that will be in excess of their credit limit.

My suggestion is to build in a feature that simply allows ERPNext users to decide whether or not to include Sales Orders in the calculation, or whether to only include delivery notes and sales invoices. So, those companies who would like to be notified at Sales Order stage can remain so, but those who want the limit to be enforced at delivery note or sales invoice stage can choose so.

Bounty offered: https://erpnext.org/bounties/customer-credit-limits:-new-feature-to-include-or-exclude-sales-orders-from-calculation

**Comment by tundebabzy** [comment]
Yeah. Good idea. We can add this as a setting similar to what we are doing with exchange rates

**Comment by addymuliady** [comment]
We do have this requirement too. Put it up as a bounty?

**Comment by tundebabzy** [comment]
Yes. Bounty will be sweet

**Comment by turner-james** [comment]
I have created a bounty for this - it is very urgent for us:
https://erpnext.org/bounties/customer-credit-limits:-new-feature-to-include-or-exclude-sales-orders-from-calculation

**Comment by turner-james** [comment]
100% of the bounty offered has now been backed. Any developer URGENTLY available to work on this?

**Comment by jigneshpshah** [comment]
hi @tundebabzy , 
I think , It would make more sense if we add in Account Setting section,
as it already have Credit Controller setup there.
![image](https://user-images.githubusercontent.com/4900815/31613212-0ceddaf8-b2a0-11e7-8677-f52b05118505.png)

**Comment by jigneshpshah** [comment]
Setting checkbox will be "Shift credit limit check from Sales Order (default) to Delivery note"

**Comment by jigneshpshah** [comment]
The flag/checkbox to "Shift credit limit check to Delivery Note (default, is at Sales Order)" will be placed in Customer > Credit Limit section as it will cover all use cases (customer specific and generic).

Default value of the checkbox will be unchecked (false).

![customerlevelcreditlimitcheck](https://user-images.githubusercontent.com/4900815/31650253-1ff59cb4-b334-11e7-9f88-e8ade56d5b24.png)

**Comment by turner-james** [comment]
For Customers, having credit limit check at delivery time, it should reflect in the Customer Credit balance report.

The report should show correct outstanding. i.e.  when credit limit is bypassed at  sales order level , sales order value should not get reflected as outstanding amount.

**Comment by jigneshpshah** [comment]
True. 

We can include the "Shift out the Credit Limit check from sales order" check box  coulmn in customer credit balance report to know which customers are having credit limit check at delivery  time, and for those customers can omit "Sales Order" (To Deliver and To Bill) amount from outstanding.
 
For such customers Outstanding Amount will be updated on submition of Delivery Note.

**Comment by jigneshpshah** [comment]
PR code to be submitted by @ashish-greycube


Please refer design flow chart as below.

![bypass credit limit check from sales order](https://user-images.githubusercontent.com/4900815/31937233-6db285c8-b8d1-11e7-8655-7152db8d035c.png)


Animated gif explaining the "Bypass Customer Credit Limit" check feature
and "Customer Credit Balance Report" in action.

Outstanding Amount is not updated on submission of "Sales Order".
It is updated during full/partial payment against "Sales Order" and/or after submitting "Delivery Note". (as per the case)

![bypass](https://user-images.githubusercontent.com/4900815/31937244-723c81b6-b8d1-11e7-8831-f7a5b6e1ff10.gif)



Test Case :
Automated test cases passed for both scenarios.

1) With Credit Limit check Bypass at Sales Order 
![testwithbypass](https://user-images.githubusercontent.com/4900815/31937253-7a804a74-b8d1-11e7-8137-a150a912a0fa.jpeg)


2) With Credit Limit check without bypass at Sales Order (default)

![testwithoutbypass](https://user-images.githubusercontent.com/4900815/31937266-8175f8c4-b8d1-11e7-8974-f09a87ce5451.jpeg)

**Comment by ashish-greycube** [comment]
Hi @turner-james  @jigneshpshah @PawanMeh 
code is checked in https://github.com/frappe/erpnext/pull/11312

**Comment by tundebabzy** [comment]
Hi @ashish-greycube 
I made some comments on the PR

**Comment by turner-james** [comment]
@tundebabzy I can confirm that I have verified and I am completely satisfied with the functionality of this new feature as developed by @jigneshpshah and @ashish-greycube

**Comment by ashish-greycube** [comment]
New pull request is done with help of @nabinhait  comments. Thanks for your time.
https://github.com/frappe/erpnext/pull/11610
(1)Individual names in comments are removed
(2)Report name hardcoding is removed and instead flag is used
(3) Patch is removed
(4)We need not check credit limit while making Delivery Note from Sales Invoice. @turner-james  has agreed to this
(5)We need to check both (a)outstanding_based_on_so and (b)outstanding_based_on_bypassed_so
while running customer credit limit report

Case: bypass_credit_limit_check_at_sales_order is set 1 for a customer. He has two sales order
(1)Sales order with no advance paid and (2)Sales order with advance paid.

(a)outstanding_based_on_so, this will catch value of (2)Sales order with advance paid. and
(b)outstanding_based_on_bypassed_so will catch value for (1)Sales order with no advance paid

**Comment by tundebabzy** [comment]
merged in #11610
