### ISSUE TITLE
One Click Schedule Creation

### ISSUE THREAD

**Issue by Hadi-Ti** [frappe/erpnext#10871]
Dear Team,

Thanks for this wonderful application from your side in the Open Source Community. I came across in a requirement that to create the schedule with one click after setting up courses and teacher and rooms.  Please see the suggestions i receive today.

1. Create Schedule with one Click
2. Add Complex Custom Print formats
3. Generate Schedule on weekly basis. and for each subject's class timing, and day can be shuffled.

Please reply me if this can be done. I am thinking of some customization for this. and if this can be added in future features it will create value.

Regards,

Ghulam Sarwar

**Comment by rmehta** [comment]
@Hadi-Ti thanks for your kind words

Can you write out exact specs for your requirements? If you have questions, please post them on https://discuss.erpnext.com

**Comment by Hadi-Ti** [comment]
Dear RMEHTA,

Thanks for your question. Please see the details below for the requirement.

The client is Govt Organization and they generate a schedule for training of graduate on weekly basis. Below are major requirements from them;

1. They have regular academic terms within their academic year
2. Each term has courses for each term.
3. They have teachers for each term
4. they have indoor lecture theaters and outdoor activities places
5. They generate a schedule for one week and then regenerate it again for next week. In each week schedule is different from the past week. for example, one course is on 8:00 AM to 9:00 AM on Monday, Tuesday, Wednesday, Thursday. But in next week this course will be at different times and even days can be different and they do this with all the courses they have in their current terms. 
6. After setting up all the constraints they want to generate all the schedule for one week with a click.
7. This practice continues during the whole academic term.
8. So the client creates one-week schedule and then regenerate it randomly for next week and so on.
9. The client has complex print layouts that is also a challenge.
Regards,

Ghulam Sarwar

**Comment by rmehta** [comment]
@Hadi-Ti you will need to specify each requirement clearly with screenshots / mockups, then start a job / bounty on https://erpnext.org
