### ISSUE TITLE
Make Variant does not copy UOM properties [BUG]

### ISSUE THREAD

**Issue by Tropicalrambler** [frappe/erpnext#10887]
When you have created a master and configured it accordingly, upon making a variant, many field will copy over, however the UOM items specified in the Master Template  do not copy over and must be manually set.  
For example, in Item Master Template, Stock UOM is
Unit  = 1
Box = 10
Box has 10 Units.

Behavior should be:
On Item Master with Variants > Press Make Button > Select Variant > Choose Variant name
New Item variant sheet opens
UOM should show:
Unit = 1
Box = 10

Manual modification of item variant is possible, but unrelated to this issue. This simply streamlines the creation of individual Item Variants for users.

**Comment by mbauskar** [comment]
@Tropicalrambler,

For variants items, the Conversion details will be fetched from its template

**Comment by Tropicalrambler** [comment]
mbauskar,  you are right, details should be fetched from template, however they are not fetching!

**Comment by tundebabzy** [comment]
Please follow progress on #11261
