### ISSUE TITLE
Duplicating document with purchase UOM different than stock UOM changes the rate/ price [BUG]

### ISSUE THREAD

**Issue by Tropicalrambler** [frappe/erpnext#10889]
# Description
You enter a Supplier quotation with an item. This item's **Stock UOM** is **Nos.**. The quotation  is entered using a **Purchase UOM** of "**Box of 10**". The price for this item is expressed in terms of the **Purchase UOM**: $10.00.  Thus for a quantity of 1 Box of 10, the total cost is $10, making the **Stock UOM** = $1.00 per item for 10 items.
You save and then validate this specific supplier quotation.
So far, everything is OK.
Now, you select this specific supplier quotation and you **_duplicate it._**
A new supplier quotation is created, where you can modify the specific fields.
When you reach the Quotation Item list, the item above is listed as:
Qty: **1**
UOM: **Box of 10**  (This is the correct purchase UOM)
Stock UOM: **Nos.**
Unit of Measure Conversion Factor: **10**  (10 Units of Stock UOM per Purchase UOM "Box of 10")
Price List Rate: **$1.00**
# Problem
As you can see, all the data is correct, however, the Price List Rate is listed as $1.00 for 1 "Box of 10" Purchase UOM, which in this case changes the subtotal of that line to $1.00, instead of $10.00.  Therefore, consistency is the important thing here: Either load the Stock UOM field values with the corresponding Price List Rate, or multiply Price List Rate by conversion factor entered, so that it reflects the Price for the Purchase UOM.
# Proposal for solution
Given that the functionality of **"Duplicate"** helps in reducing data entry, I propose that when duplicating, the Price List Rate gets multiplied by the Conversion Factor of Stock UOM to Purchase UOM. I suggest it uses the item-configured conversion factor to maintain integrity. With this, each time you **duplicate**, you really are retaining all the configuration of the previously entered, correct quotation.
# Solution extension
This problem and solution applies to the following 8 DocTypes:
1. Supplier Quotation
2. Purchase Order
3. Purchase Receipt
4. Purchase Invoice
5. Seller Quotation
6. Sales Order
7. Delivery Note
8. Sales Invoice

**Comment by harshit-30** [comment]
Please create another issue if it is replicable after v13.10.
