### ISSUE TITLE
Problem about erpnext installation

### ISSUE THREAD

**Issue by mugishahub1994** [frappe/erpnext#10884]
am running this command bench install-app erpnext, but am getting this error 
Error: No such command "install-app".

**Comment by yashodhank** [comment]
You must enter run `bench --site site1.local install-app erpnext` only from bench directory. if you run it outside ex. /frappe-bench directory you will get an error message as you are not inside specific bench in which commands has to exected.
Always ask such questions/search answers on http://discuss.erpnext.com
Github issues are only used for posting bugs and issues.
