### ISSUE TITLE
Can someone please check to see if there is a bug with the auto re-order?

### ISSUE THREAD

**Issue by alearns** [frappe/erpnext#10880]
I have a raw material that is listed under the CCA group under the Production Warehouse that continues to generate a Material Request. The CCA group has the shelf numbers as child warehouses and the raw material sits on several different shelves, so I have the check in group as the Production Warehouse and the Request for set to A1, please see screenshots below.

![](https://discuss.erpnext.com/uploads/default/original/2X/e/e96fd517d8327e5bbe47393e9e6bb6e4a6b17ef5.png)

![](https://discuss.erpnext.com/uploads/default/original/2X/d/d7130575d4308a76d28a1610eb72ec37458406ef.png)

![](https://discuss.erpnext.com/uploads/default/original/2X/6/60366169a61c8100f8293ca1397d82a35497c721.png)

It should generate the Material Request based on the check in group, and collectively for the raw material there is at least 25 in stock and at least 25 in A1. Is it a problem the item is being housed in multiple warehouses?

**Comment by umairsy** [comment]
Hi,

You can maintain Item stock in the multiple Warehouses. As per the above setting, if an item's stock in all the warehouses under Production Warehouse Group is less than Re-order level, then only Material Request will be created for the Purchase.

If you don't want to consider the stock in the Group Warehouse, and want to check only in the Request For warehouse (A1), then leave Check In Group field as blank.

For functional and technical queries, please post your queries first on the ERPNext community forum.

https://discuss.erpnext.com

Hope this helps.

**Comment by alearns** [comment]
Hi, @umairsy 

Thank you for your help. However, I have the Re-order level structured as you had suggested and you can verify this by looking at my screenshots. My issue is that even though the stock quantity in the Production Warehouse is more than the Re-order level, it is still generating a Material Request.

**Comment by vwithv1602** [comment]
@umairsy 
There seems to be some bug. Let us say the safety stock is 10 and my current stock is 9. Auto re-order functionality should order for let say 10 which is my minimum order qty. This happens as expected. The only problem is it is happening every day. i.e., when I see for material request after 10 days, it will create 10 material request (duplicates) which is an issue. This should create material request only if not created already.
@alearns Please let us know if this problem has been solved and let us know what you have figured out. We are facing the problem now with multiple material requests generated everyday for several items.

Any help from others would be greatly appreciated.
