### ISSUE TITLE
[REPORT] Purchase Invoice calculation

### ISSUE THREAD

**Issue by vladucoju** [frappe/erpnext#10882]
Hello,

i could't find purchase calculation in ERPNEXT. . This is something that must be generic like purchase invoice report.
Example is shown in picture

![capture](https://user-images.githubusercontent.com/9590909/30770704-6e564a62-a037-11e7-9ae2-cebefc014177.PNG)

**Comment by mohnishthakurscs** [comment]
Hello,
Yeah of course it is there in Accounts --> Purchase register, so go to that and you can see the generic report for the same. Also sending the screen shot for the better understanding.
Thanks,

![screenshot](https://user-images.githubusercontent.com/21141792/30801267-61750c00-a200-11e7-9541-99e2c6793929.png)
![screenshot0](https://user-images.githubusercontent.com/21141792/30801274-6331ca56-a200-11e7-8639-b91073ffbb65.png)

**Comment by vladucoju** [comment]
Thank you for response @mohnishthakurscs, I saw this already but it should exist in purchase Invoice, and be there like a print format for every PI. Also i couldn't find sum in same line (vat 19% , sum below 1.68).

**Comment by mohnishthakurscs** [comment]
Well, You can go to Purchase Invoice --> Reports on left corner --> select purchase register for the particular invoices and then it will take you to the purchase register page for all PI.  Thanks

**Comment by vladucoju** [comment]
That isn't that what i wan't. Thanks anyway. This is also good info.

**Comment by umairsy** [comment]
Hello,

Just checked Itemwise Purchase Register Report (based on Purchase Invoice). The totals are shown correctly for the tax columns as well.

![screen shot 2017-09-27 at 7 27 31 pm](https://user-images.githubusercontent.com/910238/30917606-0960d4de-a3ba-11e7-9012-62a17578344f.png)

Can you please specifically list the columns missing in this report? Also, each report has a standard print format, but not customized one for this report.

**Comment by vladucoju** [comment]
Hello @umairsy ,

this report is ok. I talked about type of print PI with calculation directly on document. I agree that this report has almost all columns that i mentioned in my preview. I think natural place for that print is directly on invoice. This is excelent for other reports. In this report is mising total below every row. Example:

qty  price    vat       . . .
5        10     19%     . . .
          50     59.5      . . . 
____________________________________
qty  price    vat       . . .
5        10     19%     . . .
          50     59.5      . . . 

Also there should be column margin.

**Comment by vladucoju** [comment]
I will close this. Found better software with this option included.
