### ISSUE TITLE
Change Perm Level using Upload functionality of customize form not working.

### ISSUE THREAD

**Issue by jay-parikh** [frappe/erpnext#10893]
- Trying to update fields Perm Level using upload feature but somehow it’s Perm Level for fields are not getting updated via upload feature.
Here is a form post for more reference
[https://discuss.erpnext.com/t/download-upload-functionality-of-customise-form/21840/2](https://discuss.erpnext.com/t/download-upload-functionality-of-customise-form/21840/2)
![image](https://user-images.githubusercontent.com/3703266/30795164-d5bf14fa-a1e9-11e7-89c1-e512069bae27.png)
![licecap-sample](https://user-images.githubusercontent.com/3703266/30796071-1cbc3550-a1ee-11e7-924d-62b83b9f800e.gif)

**Comment by jay-parikh** [comment]
@umairsy 
Issue has been fixed. Please see below gif.
![10893](https://user-images.githubusercontent.com/3703266/31853709-d0e6e932-b6aa-11e7-995e-27f595a93c1d.gif)

Here is the Pull Request.
https://github.com/frappe/frappe/pull/4357

**Comment by tundebabzy** [comment]
frappe/frappe#4397
