### ISSUE TITLE
Updating costing in the Task and Project, even if "Bill" is not checked

### ISSUE THREAD

**Issue by agerken** [frappe/erpnext#10907]
[Updating costing in the Task and Project, even if "Bill" is not checked](https://github.com/frappe/erpnext/issues/9824)

This issue is NOT resolved. I'm STILL having the exact same issue. Costing DOES NOT forward over to task/project. @umairsy

**Comment by tundebabzy** [comment]
Hi @agerken 
I have reopened the linked issue
