### ISSUE TITLE
If you have done Setup Progress in English and later you switch language, it is throwing error

### ISSUE THREAD

**Issue by KanchanChauhan** [frappe/erpnext#10908]
Looks like encoding or translation issue. Unfortunately cannot dig deeper at this moment.

<img width="1031" alt="screen shot 2017-09-26 at 12 19 30 am" src="https://user-images.githubusercontent.com/16913064/30833743-9c77cdba-a250-11e7-8c4d-4d0de3b81805.png">

Sent in a PR https://github.com/frappe/erpnext/pull/10909. It solved the issue but not sure if it is the right way to do it. Please review.

**Comment by KanchanChauhan** [comment]
@pratu16x7 Any progress on this, all our users use German language and everyone is facing this issue. It is kind of urgent.

**Comment by pratu16x7** [comment]
#10911

**Comment by applepipe** [comment]
thank you @KanchanChauhan this solved my issue https://github.com/frappe/erpnext/issues/10835
