### ISSUE TITLE
Pricing rule Margin percentage decimal point not affected by Global setting

### ISSUE THREAD

**Issue by drthilina** [frappe/erpnext#10917]
Hi,
   I've set the decimal precision to 4 places but it is not working for pricing rule MARGIN percentage.
![image](https://user-images.githubusercontent.com/29944021/30858907-3809fe68-a2df-11e7-9aef-37c36c4a1eb1.png)

Is it a bug?

BR

**Comment by mbauskar** [comment]
@drthilina,

Pushed a fix https://github.com/frappe/erpnext/pull/10923

Margin Rate Or Amount precision is set to 2 in Sales Order Item, for now, you can remove the precision then the system will take the precision of the field from `System Settings`.
