### ISSUE TITLE
Exchange rate error on new record for any doctype which have exchange rate

### ISSUE THREAD

**Issue by KanchanChauhan** [frappe/erpnext#10913]
All the doctypes which have Exchange Rate are getting below issue even if you try to create new one. Currency in Global defaults is RON and Company currency is EURO. Currency Exchange rate also exists.

<img width="1153" alt="screen shot 2017-09-26 at 10 30 13 am" src="https://user-images.githubusercontent.com/16913064/30850467-ea236f10-a2a5-11e7-9a2b-af1f42e36376.png">

<img width="678" alt="screen shot 2017-09-26 at 10 51 06 am" src="https://user-images.githubusercontent.com/16913064/30851344-a93b4e98-a2a8-11e7-8eee-72394dd029e1.png">

**Comment by tundebabzy** [comment]
Hi @KanchanChauhan 
Please give steps to reproduce this issue as I can't seem to reproduce this. Also, are you on develop branch?

**Comment by KanchanChauhan** [comment]
@tundebabzy  Yes I am on develop. To reproduce, just have Currency in Global defaults is RON and Company currency is EURO. After that create Sales Invoice or Purchase Invoice.

**Comment by tundebabzy** [comment]
@KanchanChauhan 
We recently introduced "Currency Exchange Settings" for companies that need to ensure that exchange rates are always up to date. Open Account Settings and check if the check box for "allow stale exchange rates" is checked (that's the default). If it isn't check it and save and things should be back to normal.

![screenshot from 2017-09-26 11-21-12](https://user-images.githubusercontent.com/818803/30855629-833964aa-a2ad-11e7-87be-42c3cb7f0bec.png)

**Comment by KanchanChauhan** [comment]
@tundebabzy It is checked. :(

**Comment by tundebabzy** [comment]
@KanchanChauhan 
Issue is fixed by #10944
