### ISSUE TITLE
Administrator can't access documents anymore after restricting a user to one company

### ISSUE THREAD

**Issue by chdecultot** [frappe/erpnext#10919]
Hi,

I have restricted a user to access only one company in an account.

Everything works fine for this user and he can access all documents linked to this company without issues.

The problem is that the Administrator don't have any permission for this company anymore.
![image](https://user-images.githubusercontent.com/4903591/30863445-60ac928a-a2d1-11e7-9a7a-c977361c8ed7.png)

I think the Administrator should not be impacted by a change in users permissions.

Steps to replicate:
1. Create a new user permission and restrict the access for a user to one company
2. Check permitted documents for the Administrator

**Comment by Zlash65** [comment]
![user-permission](https://user-images.githubusercontent.com/11695402/31997660-6b1a4d1c-b9aa-11e7-9f0c-5090fe5de005.gif)
Working just fine for me. Maybe you did something else ?

**Comment by chdecultot** [comment]
Hi Zlash65,

I just encoutered the same issue with another workflow:

1. Assigned a user to a specific company in "User Permissions"
2. Removed the assignment for that particular user

Results: 
- The user is not able to access any document in the system
- The Administrator has also no access to any document in the system


In your example you uncheck the box 'Apply for all Roles of this User'.

I have the feeling, that when checked and the user permission is later reversed, the permission is stil applied to all roles for this user.

**Comment by Zlash65** [comment]
Yep that seems to be the case. Deleting the permission would then bring in another issue of reverting in the sense that one user can be restricted from different different doc - clubbing. So reverting it solely on the basis of the deleted permission is wrong. But yeah something about admin not getting affected should be kept in place.
