### ISSUE TITLE
V9_Import Data Tool_V9.0.2_frappe framework

### ISSUE THREAD

**Issue by mohnishthakurscs** [frappe/erpnext#10927]
@rmehta  @nabinhait 

As per the said words, I have taken the latest pull and updated the site as well, but still, an issue persists. Below is the screenshot for the same. Reference Issue closed: #10926

![v9 issue](https://user-images.githubusercontent.com/21141792/30905892-c4f4a846-a393-11e7-9e76-9b9f5a37af5c.png)
![v9 issue 1](https://user-images.githubusercontent.com/21141792/30905939-eab91044-a393-11e7-844a-f6688e2ee04c.png)
The file size is 22 kb and it is in .xlsx format.

**Comment by rmehta** [comment]
Can you share your JS console?

**Comment by mohnishthakurscs** [comment]
@rmehta 
Please find the JS console:
localStorage cleared
desk.min.js?ver=1506503214.0:98 Cleared App Cache.
desk.min.js?ver=1506503214.0:129 localStorage cleared
jquery.min.js:4 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ jquery.min.js:4
desk.min.js?ver=1506503214.0:1512 POST http://localhost:8000/ net::ERR_EMPTY_RESPONSE
send @ jquery.min.js:4
ajax @ jquery.min.js:4
frappe.request.call @ desk.min.js?ver=1506503214.0:1512
frappe.call @ desk.min.js?ver=1506503214.0:1406
refresh_notifications @ desk.min.js?ver=1506503214.0:12361
(anonymous) @ desk.min.js?ver=1506503214.0:12348
![screenshot from 2017-09-27 15-33-06](https://user-images.githubusercontent.com/21141792/30907819-632abb36-a399-11e7-9086-42e4b6ef9a77.png)

**Comment by rmehta** [comment]
pushed another fix https://github.com/frappe/frappe/pull/4198

**Comment by rmehta** [comment]
@mohnishthakurscs can you check if this is fixed?

**Comment by mohnishthakurscs** [comment]
@rmehta 
Yeah the issue has been resolved, it is working now and data is able to get imported but the thing is every time I have to reinstall my modules and then have to check it if the data is there then reinstalling will not be an ideal solution.Hope I am getting clear with my thought in regards to this. Hope to rectify this issue. Thanks for the support rushabh.

**Comment by manassolanki** [comment]
@mohnishthakurscs You don't have to reinstall any module in order to import the data via the data import tool. I am closing the issue as this is resolved, please reopen if you are still getting some problem
