### ISSUE TITLE
upgrades failing after recent merge to v9

### ISSUE THREAD

**Issue by sathishpy** [frappe/erpnext#10922]
I tried to update to install my app changes and ended up with

This update will cause a major version change in Frappe/ERPNext from 8 to 9.
This would take significant time to migrate and might break custom apps. Please run `bench update --upgrade` to confirm.
()
You can stay on the latest stable release by running `bench switch-to-master` or pin your bench to 8 by running `bench switch-to-v8`

At this stage, I don't want to upgrade without testing the changes locally, so thought of staying with the current version. So ran,

frappe@myhost:~/frappe-bench$ bench switch-to-master
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 11, in <module>
    load_entry_point('bench', 'console_scripts', 'bench')()
  File "/home/frappe/.bench/bench/cli.py", line 40, in cli
    bench_command()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/.bench/bench/commands/update.py", line 143, in switch_to_master
    switch_to_master(upgrade=upgrade, apps=['frappe', 'erpnext'])
  File "/home/frappe/.bench/bench/app.py", line 308, in switch_to_master
    switch_branch('master', apps=apps, bench_path=bench_path, upgrade=upgrade)
  File "/home/frappe/.bench/bench/app.py", line 275, in switch_branch
    raise MajorVersionUpgradeException("Switching to {0} will cause upgrade from {1} to {2}. Pass --upgrade to confirm".format(branch, version_upgrade[1], version_upgrade[2]), version_upgrade[1], version_upgrade[2])
bench.app.MajorVersionUpgradeException: Switching to master will cause upgrade from 8 to 9. Pass --upgrade to confirm

I was expecting that will keep the version at 8, but it was trying to upgrade, which is certainly confusing. So tried 

frappe@myhost:~/frappe-bench$ bench switch-to-v8
Usage: bench [OPTIONS] COMMAND [ARGS]...

Error: No such command "switch-to-v8".

Surprisingly, I saw similar issue reported for earlier upgrade in https://discuss.erpnext.com/t/error-no-such-command-switch-to-v7/21958

**Comment by rmehta** [comment]
@sathishpy there is no v8 branch.

CC @nabinhait

**Comment by jmatsushita** [comment]
I ran into the same problem. This probably means that installations that currently want to stay on v8 cannot update currently.

**Comment by jmatsushita** [comment]
Just testing `bench switch-to-branch v8.x.x` but I have a version tagged `v8.11.6` and diffing with the branch seems to have a lot of difference...

**Comment by jmatsushita** [comment]
Ok looking at `git log` it seems that the differences are mostly hot fixes. So I'm reassured.

**Comment by rmehta** [comment]
Great. closing this for now.
