### ISSUE TITLE
Concatenating fields when multiple documents are fetched (e.g. PR to PI)

### ISSUE THREAD

**Issue by lxnow** [frappe/erpnext#1092]
We create a Purchase Invoice from multiple Purchase Receipts.

The desired behavior is to have a field called "Customer Document
Reference" from Purchase Receipt to be transferred into the Purchase
Invoice as read only.

If multiple Purchase Receipts are transferred, however, the field is
overwritten by the last data fetch. Is it possible to concatenate the
field rather than over-writing?

**Comment by Arundhatii** [comment]
Closing the issue for now as no further discussion or similar requirement is raised. Please feel free to reopen if it is still relevant.
