### ISSUE TITLE
[Feature Request] Follow Up section in Quotation

### ISSUE THREAD

**Issue by basdereus84** [frappe/erpnext#10921]
I think it would be a good idea to have a follow up section in Quotation just like we have now under Opportunity.

Maybe someone has a good argument why this not available yet, as to me it seems that you would also want to follow up a quotation or get a reminder within X days after submission if you didn't get a response from the customer, to contact him.

**Comment by joolsr** [comment]
+1

**Comment by nikesh03** [comment]
rather than the follow up with every customer , can we just not get a auto followup with email every week and is the opportunity is lost then leading to a form where they can describe what went wrong . if the opportunity is live then keep sending mails every week / month .

**Comment by basdereus84** [comment]
An automatic follow up would be a good idea, just like we now can set a reminder if an incoming email is not replied within a certain time.

However, I think we should have both: An automatic follow up reminder after one week (adjustable) unless another date has been set.

There are situations that you want to follow up a quotation or opportunity sooner because you know it's an urgent project and the customer is going to make a decision in 2 days or the other way around, for instance, the customer is for two weeks on hollidays, so you want to follow up in 2.5 weeks instead of 1.

**Comment by joolsr** [comment]
I think the above ideals are sensible but equally I think these follow ups should be configurable ie enbaled or disabled. In our industry on some quotes we need to follow up in days, some in weeks, some in months and some could be in a year or more .... so flexibility is key

**Comment by basdereus84** [comment]
@joolsr 

> However, I think we should have both: An automatic follow up reminder after one week (adjustable) unless another date has been set.

Your proposing to have another option added to the two senarios I mentioned which is "No Follow up"?
So we would get these three options:

Follow up date:

- Automatic follow up (default), unless one of the other two options are selected (time set in general settings)

- Follow up on a manually specified date

- No follow up

Follow up by:

- Default by the document owner unless another user is selected

**Comment by joolsr** [comment]
@basdereus84 Yes that sounds sensible. We may make some use of the manual follow ups too, but a no follow up would be useful.

**Comment by joolsr** [comment]
Up to a point some of this can be done with feedback triggers, but this would only send a promt about the quote after a period rather than record any feedback I believe

**Comment by basdereus84** [comment]
@joolsr 
Could you explain how I should deal with this by using feedback triggers? As I don't expect that there will be a follow-up function implemented soon, this might be worth trying.

Another option could be adding a custom date field and set the value with a custom script. The script should also set a task to follow up. As at this moment I have no idea how to write a custom script, your suggestion might be an easy workaround.

**Comment by joolsr** [comment]
@basdereus84 This is not something I've tried but should in theory be what you need. Have you looked at https://erpnext.org/docs/user/manual/en/setting-up/feedback/setting-up-feedback ? 

Also you can probably do much the same with this https://erpnext.org/docs/user/manual/en/setting-up/email/email-alerts
They even describe this as useful for quote follow ups. The emails alerts are deceptively powerful, so I would think that you should have enough levers to get this to work reasonably well
