### ISSUE TITLE
V9_Import Data Tool

### ISSUE THREAD

**Issue by mohnishthakurscs** [frappe/erpnext#10926]
Hello, I am trying to use import data tool to import data from instance for testing ERPNext, But I am facing certain problems while importing – “File upload disconnected”.

Any suggestion please advise, as this is happening in latest version V9. Please find the screenshot as well. The File size is 22 kb and it is in .xlsx format.

![screenshot from 2017-09-27 12-18-04](https://user-images.githubusercontent.com/21141792/30901055-fc71d0ec-a383-11e7-9125-8b6481f03cfd.png)

Please find the JS console view as well for further clarification.

localStorage cleared
desk.min.js?ver=1506493425.0:98 Cleared App Cache.
desk.min.js?ver=1506493425.0:129 localStorage cleared
jquery.min.js:4 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ jquery.min.js:4

Seeking an advice on this, please. 

Thanks 
Mohnish

**Comment by nabinhait** [comment]
This has been fixed in latest release.
