### ISSUE TITLE
Accounts Payable shows wrong data from A/R if no Purchase Invoices exist

### ISSUE THREAD

**Issue by mwaigichuhi** [frappe/erpnext#10938]
This issue is present even in latest v9.x but first noted it in v8.

It may be related to an error seen in the blank A/P (or any blank report) as below:

`Unable to handle success response`   `desk.min.js:1473:4`

This happens if A/R data exists but not A/P data. The mentioned behaviour changes correctly once the A/P data i.e. Purchase Invoices and/or Payment Entry are made

See screen shot below:
![erpnext-ap-issue](https://user-images.githubusercontent.com/6260482/30911787-a4e5e0d4-a392-11e7-88d2-705b9efdcf44.png)

**Comment by adityaduggal** [comment]
Similar to #10856

**Comment by tundebabzy** [comment]
Hi @mwaigichuhi 
From a clean install, I created two sales invoices and a Receive-Payment Entry but couldn't reproduce this issue. When I created a Purchase Invoice, the report is as expected. Is there any more information that I can use to reproduce the problem?

**Comment by tundebabzy** [comment]
seems like this is no longer an issue
