### ISSUE TITLE
No batch item in demo.erpnext.com

### ISSUE THREAD

**Issue by mdwala** [frappe/erpnext#10948]
In reference to earlier issue
[https://github.com/frappe/erpnext/issues/10781](url)

1. No item with "Has Batch No" in [beta.erpnext.com](url)
2. No batch Id permission in [beta.erpnext.com](url) & [demo.erpnext.com](url)

Edit: Elaborated the issue.
![2](https://user-images.githubusercontent.com/24455908/30952719-06aa30e8-a43a-11e7-9538-b467a06da553.png)
![1](https://user-images.githubusercontent.com/24455908/30952718-06a9e5d4-a43a-11e7-8ca3-f604185bb70e.png)

**Comment by umairsy** [comment]
Hello,

Can you please elaborate your query with an example? Also, the link for the Github Issue needs to be corrected.

**Comment by mdwala** [comment]
Hi Umair,

In demo.erpnext.com, there are no items with "Has Batch" selected, thus cannot try demo entries with Batch IDs

**Comment by mdwala** [comment]
@umairsy 

Got item, but then - No permission to create Batch
![untitled](https://user-images.githubusercontent.com/24455908/30952110-7652c91c-a437-11e7-9c76-852c20292ad3.png)

**Comment by umairsy** [comment]
Thanks for reporting. Please elaborate issues with detailed steps and screenshots, so that eveyone checking issue is on the same page. We will update you once it is fixed.

@saurabh6790 please give Create permission on Batch to demo user. Also, new Batch Item with nice name will be helpful.

**Comment by mdwala** [comment]
Also No batch item and permission on 
[beta.erpnext.com](url)

I was opening beta.erpnext.com from first, didn't check demo.erpnext.com

![untitled](https://user-images.githubusercontent.com/24455908/30952216-f91e84c6-a437-11e7-918a-85829526a7c5.png)

**Comment by rohitwaghchaure** [comment]
@mdwala 

Added batch item in demo.erpnext.com, bet.erpnext.com, also given permission to demo user create new batch, please check

**Comment by mdwala** [comment]
Thanks.....
@umairsy @rohitwaghchaure
