### ISSUE TITLE
Data Import/Export Template includes empty linked rows

### ISSUE THREAD

**Issue by jmatsushita** [frappe/erpnext#10942]
When exporting for instance Purchase Invoices without any column from Puchase Invoice Items, the resulting excel file still includes empty rows for all of the missing children.

Cheers,

Jun

**Comment by umairsy** [comment]
Replicating:

A field from child table not included:

![screen shot 2017-10-23 at 6 17 06 pm](https://user-images.githubusercontent.com/910238/31889748-821bfc0a-b81e-11e7-9f22-b5bb97b2469d.png)

Still, excel file has columns added for child table ID (~).

![screen shot 2017-10-23 at 6 18 26 pm](https://user-images.githubusercontent.com/910238/31889767-93fab15a-b81e-11e7-90d5-81f8ec856bf7.png)

**Comment by tundebabzy** [comment]
This is not a bug. It is working as designed. When the exporter cycles through all the available children and it finds anything marked to be not be included, it simply puts the "~". When the importer sees the "~", it knows it is dealing with either an empty table row or field row.
