### ISSUE TITLE
Post Code (Zip Code) field in Tax Rule missing?

### ISSUE THREAD

**Issue by AnthonyVV** [frappe/erpnext#10947]
Hello,

We have a master tax file that contains all specific taxes based on Zip Codes (California - USA). 
It would great to be able to assign a Tax Rule based on (Ship) Post Code/Zip Code.
Seems to be missing? Maybe I'm not implementing correctly?

Thanks!

ERPNext: v9.0.2 (master)
Frappe Framework: v9.0.5 (master)

![postcode](https://user-images.githubusercontent.com/31705838/30943275-d39dacce-a3a4-11e7-8339-2636d4e9dd5e.PNG)

**Comment by sushantnadkar** [comment]
This feature is already merged in the core with the following pr:
https://github.com/frappe/erpnext/pull/14639
