### ISSUE TITLE
psutil missing from requirements

### ISSUE THREAD

**Issue by bcornwellmott** [frappe/erpnext#10946]
> 
> Your bench was upgraded to version 9
> Traceback (most recent call last):
>   File "/usr/local/bin/bench", line 9, in <module>
>     load_entry_point('bench==2.1.0', 'console_scripts', 'bench')()
>   File "/home/frappe/bench-repo/bench/cli.py", line 40, in cli
>     bench_command()
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __ca                       ll__
>     return self.main(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
>     rv = self.invoke(ctx)
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in inv                       oke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invo                       ke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invo                       ke
>     return callback(*args, **kwargs)
>   File "/home/frappe/bench-repo/bench/commands/update.py", line 58, in update
>     _update(pull, patch, build, bench, auto, restart_supervisor, requirements, n                       o_backup, force=force, reset=reset)
>   File "/home/frappe/bench-repo/bench/commands/update.py", line 94, in _update
>     post_upgrade(version_upgrade[1], version_upgrade[2], bench_path=bench_path)
>   File "/home/frappe/bench-repo/bench/utils.py", line 606, in post_upgrade
>     redis.generate_config(bench_path=bench_path)
>   File "/home/frappe/bench-repo/bench/config/redis.py", line 37, in generate_con                       fig
>     "maxmemory": config.get('cache_maxmemory', get_max_redis_memory()),
>   File "/home/frappe/bench-repo/bench/config/redis.py", line 70, in get_max_redi                       s_memory
>     import psutil
> ImportError: No module named psutil

I got this error after upgrading to v9. Not a big deal as I just ran sudo pip install psutil, but it probably should be listed in the requirements for whichever app uses it (bench?) so that people don't get this error.

**Comment by pratu16x7** [comment]
Update: `psutil` listed in bench `requirements.txt` as of now.
