### ISSUE TITLE
Clicking on "New Account" should automatically take to chart of accounts

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#10950]
Currently it takes to the Account form and throws an error message

**Comment by Zlash65** [comment]
But Chart of Accounts is in Tree view and the route resolve depends on 'save' [tree entry does not have save option and uses a different way to save and render nodes] to get back to where it was routed right ? Taking it to chart of Accounts will not route back to where it was clicked from..?

**Comment by rmehta** [comment]
So we need to add it to the treewidget

Maybe throw a global event "doc-insert" so we can catch it from anywhere?

**Comment by pratu16x7** [comment]
Which 'New Account' button are we talking about? If it is the list view one, it does take to the Chart of Accounts as of now.
![jan-19-2018 17-21-04](https://user-images.githubusercontent.com/5196925/35149731-41d94da0-fd3d-11e7-8125-3629a704ed64.gif)

It could, however, open the quick entry for new account, but the tree view also gives a good context for account creation.

**Comment by Zlash65** [comment]
"New Account" for example from Journal Entry DocType. It opens a form view of Account which throws error that go to charts of accounts to create a new account. Even closing that dialog box and filling the form won't do the cut.
![account-route-issue](https://user-images.githubusercontent.com/11695402/35150535-c23be8ec-fd40-11e7-9e86-ca2a60315775.gif)

**Comment by rmehta** [comment]
Remove validation, let user create in form.

**Comment by rmehta** [comment]
https://github.com/frappe/erpnext/pull/13509
