### ISSUE TITLE
Cash Flow statement

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#1095]
Please add Cash Flow Statement in Accounts module.

**Comment by fikrut** [comment]
ya cash flow statement report is a basic thing please try to add it!

**Comment by umairsy** [comment]
specimen of cash flow statement 

![screen shot 2015-09-10 at 3 07 10 pm](https://cloud.githubusercontent.com/assets/910238/9785149/b8b9b4b8-57cd-11e5-96c8-69539565bcdf.png)
![screen shot 2015-09-10 at 3 07 27 pm](https://cloud.githubusercontent.com/assets/910238/9785152/ba5bf7f4-57cd-11e5-82eb-509b0eb0d261.png)

**Comment by fikrut** [comment]
Dear Umair
is this mean you have added cash flow statement on ERP next?
please say me yes it was my priority need.
thanks

On 1/14/16, Rushabh Mehta <notifications@github.com> wrote:
> Closed #1095.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/frappe/erpnext/issues/1095#event-514871428


-- 
Fikremariam Teshome
Labora International Trading PLC
Software Development Expert
Addisababa,Ethiopia
fikerjayz@gmail.com

**Comment by anandpdoshi** [comment]
Yes cash flow statement has been released

**Comment by fikrut** [comment]
thanks so much..that is the great addition i was waiting for.thanks again

On 1/15/16, Anand Doshi <notifications@github.com> wrote:
> Yes cash flow statement has been released
>
> Sent from my phone
>
>> On 15-Jan-2016, at 6:12 PM, fikrut <notifications@github.com> wrote:
>>
>> Dear Umair
>> is this mean you have added cash flow statement on ERP next?
>> please say me yes it was my priority need.
>> thanks
>>
>> On 1/14/16, Rushabh Mehta <notifications@github.com> wrote:
>> > Closed #1095.
>> >
>> > ---
>> > Reply to this email directly or view it on GitHub:
>> > https://github.com/frappe/erpnext/issues/1095#event-514871428
>>
>>
>> --
>> Fikremariam Teshome
>> Labora International Trading PLC
>> Software Development Expert
>> Addisababa,Ethiopia
>> fikerjayz@gmail.com
>> —
>> Reply to this email directly or view it on GitHub.
>>
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/frappe/erpnext/issues/1095#issuecomment-171954807


-- 
Fikremariam Teshome
Labora International Trading PLC
Software Development Expert
Addisababa,Ethiopia
fikerjayz@gmail.com
