### ISSUE TITLE
Cannot fully access school module [in Arabic]

### ISSUE THREAD

**Issue by dalwadani** [frappe/erpnext#10966]
After the setup and choosing Education as the domain, the school module is incomplete as seen here:
![screen shot 2017-09-28 at 16 14 10](https://user-images.githubusercontent.com/4618082/30974771-603745e6-a468-11e7-9d17-31c021d592d7.png)

It seems like an issue in the user's role.

**Comment by manassolanki** [comment]
Hi @dalwadani ,
Could you please share the role permission of the user. I have tested this after setting up a fresh account and I am not getting any issue.

**Comment by dalwadani** [comment]
This is not a fresh install. I updated from V8.
Here is a screenshot of the enabled roles:
![image](https://user-images.githubusercontent.com/4618082/31012551-1983d11c-a50a-11e7-90bc-3b5efbec190a.png)

I tried accessing the student list by url: /desk#List/Student/List
However, I get "Sorry! You are not permitted to view this page."

**Comment by manassolanki** [comment]
You have to choose the "Education" as the domain in the setup wizard itself (first setup after installing the site) to make school domain visible.

**Comment by dalwadani** [comment]
Yes

**Comment by manassolanki** [comment]
I have tried on the frappe cloud itself. I am not able to replicate. Please reinstall the site and try again it will work.

**Comment by dalwadani** [comment]
Thanks for your time.
This issue is not in frappe cloud. I have multi-tenant hosting and I upgraded to the latest version. I created a new site and in the setup wizard I choose Education as a domain. However, as can be seen in the first screenshot, the school module does not show properly.

**Comment by dalwadani** [comment]
I was able to find the source of this issue. It was caused by the setup wizard.
I get this error when the language of the setup wizard is chosen to be Arabic. I created a new site and set the language to English and the issue disappeared.
Hope this helps.

**Comment by Zlash65** [comment]
![school-issue](https://user-images.githubusercontent.com/11695402/33985476-b7b005b0-e0e0-11e7-8ec0-f991e5fc7f90.gif)
Did a fresh install with Arabic language selected in setup wizard. Everything seems to be working just fine.

**Comment by nabinhait** [comment]
@dalwadani Closing the issue for now, please reopen if you are still getting the issue.
