### ISSUE TITLE
Expense Approver can not Approve Expenses

### ISSUE THREAD

**Issue by derekmontgomery** [frappe/erpnext#10967]
ERPNext: v8.11.4 (master)

Frappe Framework: v8.10.8 (master)

Expense Approval uses a Custom Script, to advance the status of an Employee Expense submission.  It requires the Expense Approver to review the form and the attached documents (expense receipts) and then update the status from Draft to Approved.  The process works for other Expense Approvers.  But not for one Expense Approver in particular.  His name is Lukas Torngren.  He has the same role definition as others (he has the highest level of role permissions, including System Administrator).  He is listed as an Expense Approver, and his name appears on the list of Expense Approvers and his name is selected by the Expense Approval Request person ... but when he tries to update the status of an Expense Claim request, the field is greyed out and he can not change the status.

We don't know what else to do.

**Comment by tundebabzy** [comment]
Hi @derekmontgomery 
To troubleshoot this, please add a screenshot and most importantly, check if there's any error traceback and post here

**Comment by tundebabzy** [comment]
Hi @derekmontgomery 
Sorry for the snag. Let's troubleshoot this on the forum (https://discuss.erpnext.com). There'll also be more eyes there.
