### ISSUE TITLE
Email Inbox - Sent Emails not replicating

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#10971]
Received from Customer via WN-SUP27971

Replicating in gadgets.erpnext.com for ID frappetest@gmail.com

![screen shot 2017-09-29 at 11 22 58 am](https://user-images.githubusercontent.com/910238/31002511-c668a86e-a508-11e7-976e-288062d0c2eb.png)

**Comment by nabinhait** [comment]
@umairsy Is this still a valid issue? If yes, please reopen.
