### ISSUE TITLE
V9_latest pull request update needs reset everytime

### ISSUE THREAD

**Issue by mohnishthakurscs** [frappe/erpnext#10974]
Hi,
In the latest version V9, every time taking latest updates then it is asking for the bench update --reset. So whenever any new changes made or any pull needs to be taken then these commands need to be made.Earlier when there is bench update command fire then automatically update and latest pull comes but now need to use bench update --reset on every pull.

kindly assist to this issue on the latest. Below is the screenshot for the reference use.

![screenshot from 2017-09-29 11-01-53](https://user-images.githubusercontent.com/21141792/31005241-73c30660-a515-11e7-85a5-ae623b3a1516.png)

Thanks 
Mohnish

**Comment by tundebabzy** [comment]
Hi @mohnishthakurscs 
Next time the issue pops up, run `git status`. It will show the offending source files. Copy them and post a new topic on the forum. With the information, we will be able to troubleshoot the issue better.
