### ISSUE TITLE
In the Email Account, Allow Append To as "Lead"

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#10979]
For now, Lead cannot be selected as Append To option. Customers often requests Lead to have as an option in Append To.

![screen shot 2017-09-29 at 3 09 01 pm](https://user-images.githubusercontent.com/910238/31010376-430b0adc-a528-11e7-97e5-bc4977752019.png)

**Comment by mbauskar** [comment]
@umairsy,

If Email Account append to is set as Opportunity then the system will create both `Lead` and `Opportunity`.

If still we need Lead in Append To please let me know.

**Comment by umairsy** [comment]
Yes, we also need option to just create Lead, and no Opportunity.
