### ISSUE TITLE
Error report - Message from console not update in the Error Prompt

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#10972]
The error message from the browser should be updated with the error prompt and user should be able to report it by sending email.

![screen shot 2017-09-29 at 11 43 25 am](https://user-images.githubusercontent.com/910238/31003109-7e1a0c1c-a50b-11e7-87f7-6958ddcbb33c.png)

**Comment by vishdha** [comment]
Checked this issue with @rohitwaghchaure. Traceback details appear in the dialog box.
