### ISSUE TITLE
Doubled permissions

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#10988]
Hello,

Delivery notes permissions are duplicated, but with different permissions in each selection.

<img width="530" alt="screen shot 2017-09-29 at 11 11 55 am" src="https://user-images.githubusercontent.com/18335894/31020308-fd8e5262-a508-11e7-91ed-a79f1867243f.png">

**Comment by umairsy** [comment]
Hello,

Please elaborate your query with the use-case and more detailed screenshot, so that we can support you better. For further support, please post this query on discuss.erpnext.com
