### ISSUE TITLE
Enabling Domain doesn't enable Roles for that Domain

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#10985]
WN-SUP28161

After enabling Healthcare Domain, module and roles doesn't enable.

This is perhaps for the Roles created for Healthcare, value in not updated in "Restrict To Domain".

![healthcare](https://user-images.githubusercontent.com/910238/31015279-dcd4a9c0-a53c-11e7-89ac-894486770294.gif)

After manually enabling Role and assigning to the user, Healthcare Module showup correctly.

**Comment by Zlash65** [comment]
When domain is only set for Manufacturing, still 'Student' and 'Patient' roles are enabled. Shouldn't they be disabled too at first and when the Domain is set to enable Education/Healthcare at that time they should be enabled ?
