### ISSUE TITLE
shopping car API

### ISSUE THREAD

**Issue by kyabroudi** [frappe/erpnext#10999]
have some quest can anyone help !!
1- /erpnext.shopping_cart.cart.update_cart
whats the using of “with_items” property it has no effect?!

2- api/method/erpnext.shopping_cart.cart._get_cart_quotation
calling this API return error
"Not Permitted
You do not have enough permissions to complete the action"

3- how to Create/Update Customer Address using Rest Api?

4- some API need power user access like getting Items using (api/resource/Item) , how to shopping cart user get access to list all items with their details ?!

**Comment by rmehta** [comment]
@kyabroudi please post questions at https://discuss.erpnext.com
