### ISSUE TITLE
Error with seach bar when typing out the full word, comes back with error.

### ISSUE THREAD

**Issue by nickolander** [frappe/erpnext#10990]
So for some reason it only likes when you type two letters of the word and then select from the drop down. If I type out the full word and then search it comes back error.
![erpnextmainpageerror2](https://user-images.githubusercontent.com/20309100/31030580-ae7e5d78-a50a-11e7-800c-7667c7547e6a.jpeg)

**Comment by tundebabzy** [comment]
Hi @nickolander
What is the output from the console?

**Comment by nickolander** [comment]
We did a bench up date on erpnext and it is working now. Thanks
