### ISSUE TITLE
Cannot attach image in email modal in Firefox 

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#10991]
![cant-insert-image-intoemail](https://user-images.githubusercontent.com/140076/31042496-54cf8136-a5c7-11e7-8ccf-96a3ea4a8d85.gif)

via @joolsr

**Comment by joolsr** [comment]
This also occurred in Chromium too. Both most recent versions running on Manjaro Linux

**Comment by joolsr** [comment]
This works now, but when the image is included in the email a msg is popped up to say

'File Upload Disconnected. Please try again.' which is a bit disconcerting
