### ISSUE TITLE
Bench Site - If system manager logs in for third time, send automated email to them

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#11016]
For now, we are contacting active sites based on the database use, and offering them a session. We can automate this process by sending an email based on the activity in the site, like 

- Sites active for last 3 days continuously
- Sites which exceeds 10 MB database space.

------

Message content:

Hi <name of system manager>,

This for your interest in ERPNext.

I am Umair, a Customer Support Manager at ERPNext. We will be glad to conduct an online session of 30 mins to get you started with ERPNext implementation. If interested, please let us know your availability. You can reach us on support via:

Phone: +91-22-251-55-66-7
Email: support@erpnext.com
Skype: "erpnext"

Looking forward to hearing from you.

**Comment by rmehta** [comment]
Please don't maintain this here, add this in frappe/central. that list is also actively maintained
