### ISSUE TITLE
Leave allocation

### ISSUE THREAD

**Issue by HayamMahmoud** [frappe/erpnext#11017]
Hello ,
I created new leave type for our technical team 10 days per month , I’m making the new allocation on the first day every month ( today is 1-October so I created the allocation for this month today and will end on 30-sep) is there any option on the ERP to make this allocation automatically every end of the month.

Or if we can make it per year and divide it monthly automatically ( on 1-Jan , create the allocation with total 118 days)

**Comment by OneiricIT** [comment]
@HayamMahmoud perhaps add a note to the below existing request.

https://github.com/frappe/hrms/issues/209

**Comment by umairsy** [comment]
Hello Hayam,

This feature is not available for now. Perhaps subscription-like features should be helpful to address it.

**Comment by kennethsequeira** [comment]
Can be configured with earned leave.
