### ISSUE TITLE
Need to Generate a Barcode in ERPNEXT

### ISSUE THREAD

**Issue by AravindPranera** [frappe/erpnext#11027]
Now there is a facility for Barcode scanning items, but there is no facility to generate a barcode in ERPNEXT itself.

**Comment by joezsweet** [comment]
You can integrate this: 

https://github.com/lindell/JsBarcode

**Comment by rmehta** [comment]
@AravindPranera yes, we plan to work on this during the conference next week!

**Comment by AravindPranera** [comment]
Noted Rushabh.


Thanks,
Aravind.

Pranera Services & Solutions.
Tiruppur.

**Comment by achillesrasquinha** [comment]
How about a QR Codes instead of Bar Codes? I can think of thousand advantages to have QR Codes over Bar Codes...unless the entire inventory relies on Bar Codes alone.

**Comment by joezsweet** [comment]
@achillesrasquinha what about product barcodes? printing?

**Comment by achillesrasquinha** [comment]
@joezsweet Hmm, well we could include majorly used systems for now. We'll be showing a demo to generate Bar Codes. Might end up using the lib you mentioned. :smile:
