### ISSUE TITLE
Cannot cancel Sales Invoice linked to Subscription

### ISSUE THREAD

**Issue by Baco9** [frappe/erpnext#11032]
I want to amend a sales invoice, but when I try to cancel it, I get the error:

> Cannot delete or cancel because Sales Invoice 2017-0122 is linked with Subscription SUB-00107

When I try to delete the linked subscription, I get the error:

> Subscription SUB-00107: Submitted Record cannot be deleted.

I tried stopping and disabling the subscription, but that doesn't seem to make a difference.  I’m using ERPNext v9.0.6.

Initially reported on the forum: https://discuss.erpnext.com/t/cannot-cancel-sales-invoice-linked-to-subscription/28975

**Comment by tundebabzy** [comment]
#11033
