### ISSUE TITLE
error when creating a new patient appointment

### ISSUE THREAD

**Issue by system19** [frappe/erpnext#11036]
Latest develop branch of frappe/erpnext throws this error when creating a new patient appointment

`"Deprecation warning: use moment.updateLocale(localeName, config) to change an existing locale. moment.defineLocale(localeName, config) should only be used for creating a new locale See http://momentjs.com/guides/#/warnings/define-locale/ for more info."`

![patient appointment error](https://user-images.githubusercontent.com/7428077/31157463-dee125cc-a906-11e7-81f6-197c8740325e.jpg)

http://momentjs.com/guides/#/warnings/define-locale/ states:

### Define Locale Override
Use moment.updateLocale(localeName, config) to change an existing locale. 
moment.defineLocale(localeName, config) should only be used for creating a new locale

This deprecation warning is thrown when you attempt to change an existing locale using the defineLocale function. Doing this will result in unexpected behavior related to property inheritance. moment.updateLocale will properly replace properties on an existing locale.

Any idea where the Locale gets changed/added/set

**Comment by rmehta** [comment]
Seems to be related to domain activation. A fix coming soon for this.

**Comment by system19** [comment]
Thanks @rmehta . This only started happening since 9.0 update. It worked previously.

**Comment by system19** [comment]
A fresh install selecting the latest Healthcare domain during setup fixes this issue.
