### ISSUE TITLE
[BUGs] +improvement-  online POS issues v9

### ISSUE THREAD

**Issue by taherkhalil** [frappe/erpnext#11035]
https://discuss.erpnext.com/t/pos-issue-after-upgrade-to-version-9/28955/5

Error with Discount , item search ,barcode entry, pay screen.

**Comment by taherkhalil** [comment]
ALSO discount field calculation is wrong if you change the % once entered .
![image](https://user-images.githubusercontent.com/20456072/31128888-b036b3a0-a85b-11e7-9878-57e022531f9e.png)

50 of 6.5 is not 1.625 - even though the final total is right..happens when you change the % after initially entering it

**Comment by rohitwaghchaure** [comment]
Hi @taherkhalil 

Thanks for reporting an issue
We have fixed this issue, kindly pull latest update and check
I am closing this issue, feel free to reopen if issue persist

**Comment by taherkhalil** [comment]
The multiple entries showing when searching for a item still persists.
![image](https://user-images.githubusercontent.com/20456072/31174877-d5cf793e-a915-11e7-93cf-ad7cea95b29a.png)
![image](https://user-images.githubusercontent.com/20456072/31175091-b47ef54c-a916-11e7-9d9a-c70ab7dd597e.png)

**Note: One price is of the Variant(actual selling product) and other is of the Template(which is not to be shown)**
template price should not be shown even if it is **same** or different..

_also quick entry feature through barcode is still not there_
