### ISSUE TITLE
Wrong Bank Entry Computation for Salary Processing

### ISSUE THREAD

**Issue by flexy2ky** [frappe/erpnext#11030]
Hello,

I am having weird issue.

My Bank Entry completes successfully. However, the GL entries for deductions are wrong. The Base Pay is debited from Salary GL and Credited to the deductions GL rather than the specified deductibles. Please See screenshots of my Salary Structure and the GL Entry for Payroll bank entry:

![image](https://user-images.githubusercontent.com/32480024/31117134-9f7c8624-a820-11e7-9554-687015846829.png)
![image](https://user-images.githubusercontent.com/32480024/31117154-c1a99f16-a820-11e7-9b17-396eb5fccdf1.png)
As you can see, the bank entry does not credit the required amount in the requisite Ledger even though the pay structure specifies what amount should be debited from the salary ledger and credited to the respective ledgers.  This issue was only notices during the September salary processing as the august salary processing did not have this error, suggesting that this is a back-end issue. 

I would appreciate it if someone can help fix this issue as the only workaround has been to skip the bank entry on the Human Resources module and manually post the Salary and Bank Journals which means extra steps for salary processing to be complete.

**Comment by tundebabzy** [comment]
Fixed. Please update your setup.
