### ISSUE TITLE
[New] Production Plan

### ISSUE THREAD

**Issue by rohitwaghchaure** [frappe/erpnext#11044]
- [ ] Make new doctype Production Plan.

- [ ] Add fields get items from sales order/material request and filters like item. customer, from date, to date.

- [ ] Add child table to show data of sales order/material request.

- [ ] Add child table with columns item code, default bom no, planned qty, pending qty and pull items data from the sales order/material request.

- [ ] Add button Make Production Order, create PO against an items available in the child table.

- [ ] Add button Make Material Request, create MR against an items in the child table.

- [ ] Progress bar of the production orders with status (Pending, Work In Progress, Completed)

- [ ] Documentation and Test Cases (UI & Server)

**Comment by LifeP** [comment]
May I suggest consolidation of multiple sales orders for same product?

**Comment by applepipe** [comment]
adding my 2cents:

- Create production orders for shortage qty, not the total qty on order (option)
- Filter orders by delivery date

**Comment by hokgt** [comment]
Hi @rohitwaghchaure , 

I want to make suggestions to the Production module: 

**Better production module for multi-level BOM product** 
- Integrated ID for each multi-level BOM item Production Order to detect Production Order relation
- Automatically generate child Production Order from top level of multi-level Production Order
- BOM versioning : User may change BOM version for same item in one Production Order for production result

**Production Schedule and Management**
- Drag and drop Production Order in calendar view
- Create down time (time consumed for non-production activities such as machine maintenance etc), loss time (time consumed for non-productive activities). Down time and loss time created can be plug to production schedule.
- Calculate production productivity of each workstation and site productivity
- Calculate OEE (Overall Equipment Effectiveness) for site based on workstation availability to result

**Managing production by site**
Site has purpose to manage production result movement and stages of production (production routing). Similar with workflow but its including stock movement. 
- Merge workstation and operation
- Each site may have multiple workstations
- Material reservation for next route
- Production result from one site to replenish next site

**Simplified production item**
- Production Order based on item variants (user don't to create multiple item for different variants for production)

Thank you and if you need discussion regard to the suggestions, please contact me.
