### ISSUE TITLE
Invalid Request Error, if multiple browser tabs are open of same ERPNext account

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#11058]
<img width="1440" alt="screen shot 2017-10-05 at 10 21 20 am" src="https://user-images.githubusercontent.com/910238/31213137-7ed0969c-a9c2-11e7-9798-f69483337773.png">

Trying to replicate again to get detailed console log. If anyone gets this error, please provide log from browser's console.

**Comment by tundebabzy** [comment]
Hi @umairsy .
The problem is not with using multiple tabs in the browser. It mostly happens when ERPNext pings for notifications and doesn't get a valid reply. For example, when server is shut down, mariadb is not online, etc.
