### ISSUE TITLE
No option to get back to online mode (POS)

### ISSUE THREAD

**Issue by pablo2017multiofertas** [frappe/erpnext#11057]
I change the POS module to offline. Now I want to get back to online mode, but there is not an option on the menu dropdown list.

**Comment by mbauskar** [comment]
@pablo2017multiofertas,

You can toggle the POS module to Offline to Online from the POS Settings document.
<img width="997" alt="screen shot 2017-10-05 at 12 19 08 pm" src="https://user-images.githubusercontent.com/11224291/31214138-87d66b4a-a9c7-11e7-8d13-312ab8fda57b.png">
