### ISSUE TITLE
Searching/Filtering by Parent Group.

### ISSUE THREAD

**Issue by AnthonyVV** [frappe/erpnext#11055]
Hello,

Just noticed this issue (bug, or as intended) on 9.1 but it's been carried over since 2014, issue #2138
The only place where filtering by parent node works is in Stock Balance.
The same functionality should be enabled for Stock Summary, Item. maybe other places as well. 
Some may say it's not as important, and this is possibly true, but it's not as intuitive as one might expect.

Thanks.

![item group](https://user-images.githubusercontent.com/31705838/31196648-58b81346-a903-11e7-9c20-af34074ab41f.PNG)
![item](https://user-images.githubusercontent.com/31705838/31196658-5cad1e24-a903-11e7-89c1-136625fcf9c6.PNG)
![stock summary](https://user-images.githubusercontent.com/31705838/31196665-5fe516b4-a903-11e7-89d9-61d6003f433c.PNG)
![stock balance](https://user-images.githubusercontent.com/31705838/31196759-bada95bc-a903-11e7-8db3-36d0b914d2bf.PNG)

**Comment by Olawale1** [comment]
+1

I was just going to post this issue! This should be standard behaviour for all nested sets. The main advantage of having a tree structure is being able to do things at the group level. I believe the most critical things are:

1. Filtering by Group
2. Setting Permissions by Group

I really hope these come soon

Cheers!

**Comment by lowercase00** [comment]
Same issue here.
Is there anyway to solve this by customize code?

**Comment by bab1ch** [comment]
This seems like very important feature. We're considering sponsoring it. Anyone willing to join in?

**Comment by giuseppelamatrice** [comment]
+1 it's very important analytcs function

**Comment by madid87** [comment]
Any possibility of solving this issue in the next release?

**Comment by zbisho** [comment]
This is a badly needed feature any news or ETA

**Comment by f-9t9it** [comment]
So this feature was never worked on ? @ankush  

@schilgod Can you share the commit that you mentioned this issue in and does it add functions as expected?

**Comment by ankush** [comment]
Fixed in upcoming v15. https://github.com/frappe/frappe/pull/21156

**Comment by Islamation** [comment]
I'm using v14 and I can't upgrade right now, Can I do it in item list by adding client script?
and I need to know the script, Please
