### ISSUE TITLE
[BUG] Online POS not rendering on secound click without refresh 

### ISSUE THREAD

**Issue by taherkhalil** [frappe/erpnext#11051]
Steps to replicate:
1. Click on POS icon (in online mode)
2.Do any transaction or _don't do anything_ 
3.click on erpnext icon to go to desktop.
4.Go to any other module then come back and click POS icon
5.or directly click POS icon from desktop(2nd time)

screen does not render
![image](https://user-images.githubusercontent.com/20456072/31175506-23803b12-a918-11e7-9554-a9c2cd6bb79f.png)
Only renders again after refresh.
working on local server on ubuntu 14.04 -tried on both morzilla and chrome.

**Comment by rohitwaghchaure** [comment]
Hi @taherkhalil 

Thanks for reporting an issue, we're looking into it.
For a while to fix the issue, kindly set the link as "point-of-sale" in POS desktop icon

![screen shot 2017-10-04 at 6 22 18 pm](https://user-images.githubusercontent.com/8780500/31176605-0a81afec-a931-11e7-8e7a-64636f21c8e3.png)

**Comment by taherkhalil** [comment]
@rohitwaghchaure  
How can i set the desktop links through GUI like above image 
i set the link in desktop.py - did not solve the issue.

**Comment by rohitwaghchaure** [comment]
@taherkhalil 

We have fixed this, kindly save pos settings so it will update the link field of POS desktop icon.
To see desktop icon add https://gadgets.erpnext.com/desk#List/Desktop Icon/List in the URL.
