### ISSUE TITLE
Upload Logo Image not getting uploading.

### ISSUE THREAD

**Issue by aaimaawebs** [frappe/erpnext#11082]
Facing issue of not getting upload any logo/image at setup-wizard, even while creating a fresh install.  Even tested with various other browsers. Upload Button not working on setup-wizard/2 and setup-wizard/4 screens.

Here is the GIF screenshot for same: 

![](http://g.recordit.co/wtHzxRwunD.gif)

**Comment by tundebabzy** [comment]
This is fixed in frappe/frappe#4246. It will soon be merged in
