### ISSUE TITLE
Error while saving a New bounty. 

### ISSUE THREAD

**Issue by Arundhatii** [frappe/erpnext#11081]
Reported via https://frappe.erpnext.com/desk#Form/Opportunity/ENQ-17-18-01428

![screen shot 2017-10-05 at 8 46 56 pm](https://user-images.githubusercontent.com/20164097/31235158-5c48dba6-aa0e-11e7-91f2-ba860e14e3cd.png)

**Comment by mbauskar** [comment]
fixed in https://github.com/erpnext/foundation/pull/50

**Comment by rmehta** [comment]
@Arundhatii please post these issues in erpnext/foundation
