### ISSUE TITLE
Items not populating into production order 

### ISSUE THREAD

**Issue by alearns** [frappe/erpnext#11085]
Hi, 

As shown below, my parent BOM has 25 items required for production (disregard item 6302-000011 as it is a labor cost and not an actual item). 

![bommaterialexploded](https://user-images.githubusercontent.com/31016634/31252115-2ac8c7a0-a9ee-11e7-82fc-cf0cee9dc156.PNG)
![bommaterialexploded2](https://user-images.githubusercontent.com/31016634/31252126-30fb9eb8-a9ee-11e7-8ad6-1956a1f4e9b5.PNG)

All child BOMs are submitted and all items are in stock, but when I create a Production Order for this product only 20 items are populated. I cannot figure out why this would happen. The missing items seem to be random; they're from different child BOMs. Please see the screenshot below of the Production Order. 

![porequireditems](https://user-images.githubusercontent.com/31016634/31252335-e09e10a8-a9ee-11e7-9cce-3962009de852.PNG)

Thank you for your help!

**Comment by tundebabzy** [comment]
Does this happen **only** when the BOM contains a lot of items?

**Comment by alearns** [comment]
We are still in the process of integrating ERP with our company, so this is the first product with a completed set of BOMs we have tried issuing a Production Order against.

**Comment by tundebabzy** [comment]
https://discuss.erpnext.com/t/items-not-populating-into-production-order/29136/5
