### ISSUE TITLE
[Bug] v9 online POS-Net total changing with grand total on discount

### ISSUE THREAD

**Issue by taherkhalil** [frappe/erpnext#11087]
On discount in online POS net total changes with grand total which should not happen ..
It should be Net total - discount amount = grand total .
![image](https://user-images.githubusercontent.com/20456072/31254011-9dd9863a-aa2f-11e7-936e-c34c57b90234.png)
initial price
![image](https://user-images.githubusercontent.com/20456072/31254025-ac73b972-aa2f-11e7-899e-634c66b5a269.png)
after discount..
it wil lead to belive that the discount calculation is wrong.

regards,

**Comment by rohitwaghchaure** [comment]
Hi @taherkhalil 

Seems you have not set discount based on in the POS Profile
![screen shot 2017-10-06 at 9 38 18 am](https://user-images.githubusercontent.com/8780500/31262637-1b93ee86-aa7a-11e7-9ec0-b2b6ed7a8ad2.png)


It's working properly in latest version
**Before Discount**
![screen shot 2017-10-06 at 9 36 38 am](https://user-images.githubusercontent.com/8780500/31262647-322ae46a-aa7a-11e7-8925-97798c159f9b.png)

**After Discount**

![screen shot 2017-10-06 at 9 37 18 am](https://user-images.githubusercontent.com/8780500/31262653-3d5b9334-aa7a-11e7-9b6e-0e2a82b61315.png)
