### ISSUE TITLE
[FIX-needed]  Discount on total not working in Offline POS v9

### ISSUE THREAD

**Issue by taherkhalil** [frappe/erpnext#11084]
I have set discount on grand total in POS profile but not able to apply discount.
![image](https://user-images.githubusercontent.com/20456072/31251287-17cc0cec-aa26-11e7-8ac7-6578c55480ee.png)

The grand total bar does not expand on clicking
![image](https://user-images.githubusercontent.com/20456072/31251160-b996d95e-aa25-11e7-9930-a6edf6d9155d.png)
.
Please fix and make discount on total like online mode or v8 offline mode.
regards.

**Comment by rohitwaghchaure** [comment]
@taherkhalil 

Thanks for reporting an issue
We have fixed it https://github.com/frappe/erpnext/pull/11089, soon we'll release the fix

**Comment by taherkhalil** [comment]
still persists
