### ISSUE TITLE
[Healthcare] Not able to add test name

### ISSUE THREAD

**Issue by AminulBD** [frappe/erpnext#11091]
Hello,

First of all thank you so much and congratulation for awesome software. 

I'm experimenting with the healthcare section one by one but I've trouble to adding new row while lab test creation. Here is the screencast of the problem http://d.aminul.net/zuUiH/2ChFmIaC

Please check.

Regards.

**Comment by rkurungadam** [comment]
Hi @AminulBD You have to define the lab test compnents in Lab Test Template. Once you select template in Lab test and save all rows will be fetched. You won't be allowed to make changes in Lab Test, only result entries can be updated. For a list of common templates refer this repo https://github.com/ESS-LLP/erpnext-medical-data, please go through the readme on how to import.
Thanks

**Comment by AminulBD** [comment]
@rkurungadam you mean while creating lab test staff can't add new test in the test field right? but you should have an option to add test without selecting template.

**Comment by rkurungadam** [comment]
@AminulBD yes, will mark the field readonly, so add row button won't appear. You can add any additional  information in Custom Result section.
