### ISSUE TITLE
&nbsp on print format

### ISSUE THREAD

**Issue by Kriskeuuuh** [frappe/erpnext#11099]
Hi, at once &nbsp came up on my print format between zipcode and city. Is there a way I can fix this?
I did not change anything.

**Comment by mbauskar** [comment]
@Kriskeuuuh,

Can not replicate, seems to work just fine can you please share the screenshot or steps to recreate the issue

**Comment by Kriskeuuuh** [comment]
When I create a document like a bill for example, the adress should be (zipcode)(space)(city)
Instead of the space there comes (&nbsp). Like "2000&nbspAntwerp" should be "2000 Antwerp"

![image](https://user-images.githubusercontent.com/19347907/31736464-26643972-b445-11e7-9356-0e6ff0c529d7.png)

**Comment by umairsy** [comment]
please use Address Template feature for defining the alignment of address values.

https://erpnext.org/docs/user/manual/en/setting-up/print/address-template

**Comment by Kriskeuuuh** [comment]
Thank you, I managed to solve the issue. ; was missing after &nbsp in the address template.
Because I did not change this by myself, it was impossible to find it. Possibly other users with the template "Belgium" have the same issue.
