### ISSUE TITLE
Expenses Included In Valuation Should be Assets Account Type

### ISSUE THREAD

**Issue by Fredoluka** [frappe/erpnext#11096]
Greatings to the team.The landing cost feature is great.For a company into a serious importation, the feature as it is presently in the ERPnext is not useable because the Expense Included in Valuation can only be created as an expense.It cannot be created as an asset.
In a serious importation company,the amount accumulated in the account runs into several million dollar pending arrival of the stock.Since management account is prepared monthly,that accumulated amount will make mess of the monthly management account since those expenses does not belong to the month.
REQUEST
Make it possible to be created as an asset account so that it can be selectable in  Company Set up under Expenses Included in Valuation.
Here is the link to the forum discuss
https://discuss.erpnext.com/t/expenses-included-in-valuation-should-be-assets-account-type/29092

**Comment by tundebabzy** [comment]
This seems to be fixed.
