### ISSUE TITLE
POS RATE CHANGE

### ISSUE THREAD

**Issue by farhanayyaz1** [frappe/erpnext#11101]
rate of the item to be modified from list directly in POS instead of button for rate its confusing

**Comment by rohitwaghchaure** [comment]
Hi @farhanayyaz1 

Better you maintain rates in the item price, so you don't need to update in the POS Cart.

**Comment by farhanayyaz1** [comment]
Dear,


I know but we are selling to retailer and wholesaler both so it's easy to make the invoice in POS. And I think before it had an option for the rate change.




First Moon Electronics Trading.

SHIPPING MARK:  MFB

TEL:00971-4-2284525

FAX: 00971-4-2242179

Mobile Dubai: 00971-52-9291514

P.O.BOX: 86527,DUBAI-UAE

Address: SH#47,Baglaf Bldg,Nakheel Road,Dubai-UAE

________________________________
