### ISSUE TITLE
Add Mexican SAT CFID & XML  invoice, and TAx support and electronic accountin

### ISSUE THREAD

**Issue by Conestrait** [frappe/erpnext#11108]
# **i want to pay this function...
[Contabilidad electrónica.pdf](https://github.com/frappe/erpnext/files/1364743/Contabilidad.electronica.pdf)
**

 i need erpnext   be compatible  and compliant with mexican  tax laws ,  im attaching  al <links and pdf.

CONTABILIDAD ELECTRÓNICA  : http://www.sat.gob.mx/fichas_tematicas/buzon_tributario/Paginas/contabilidad_electronica.aspx
​

Te invitamos a conocer el minisitio de Contabilidad electrónica.

El envío de la información es a través del Buzón Tributario, por lo que es necesario que hayas confirmado el correo electrónico que proporcionaste y que se encuentre vigente tu firma electrónica. También puedes hacer ahora el envío en la sección Trámites de este Portal.

Antes de enviar tu información valida tus archivos en el validador de forma y sintaxis.

Contabilidad en medios electrónicos, Anexo Técnico​.​

Contabilidad en medios electrónicos, Anexo Técnico​ 2017.​

​​
 
  
La contabilidad electrónica se refiere a la obligación de llevar los registros y asientos contables a través de medios electrónicos e ingresar de forma mensual su información contable a través de la página de Internet del SAT.
 
Para dar cumplimiento formal al ingreso mensual de información contable, únicamente se enviará la balanza de comprobación y el catálogo de cuentas con el código agrupador del SAT que permita su interpretación.

Adicionalmente, los contribuyentes deben tener la posibilidad de generar información electrónica de sus pólizas contables y auxiliares para entregarla al SAT, sólo cuando:

El SAT ejerza facultades de comprobación directamente al contribuyente o a terceros relacionados (compulsas)
El contribuyente solicite una devolución o realice una compensación.
 
Los contribuyentes del Régimen de Arrendamiento, Servicios Profesionales e Incorporación Fiscal quedan relevados del envío de Contabilidad Electrónica, siempre y cuando registren sus operaciones en el módulo de contabilidad de la herramienta electrónica “Mis cuentas”.
 

¿Existe un validador de archivos xml para el envío de la información contable?

Sí, existe un validador de forma y sintaxis contabilidad electrónica

¿Cuáles son las características de la información que se enviará al SAT sobre la contabilidad electrónica?
La información contable se integrará con cortes mensuales en archivos xml con el detalle de la contabilidad electrónica conforme a lo establecido en el (2,933 KB) Anexo 24​ de la Resolución Miscelánea Fiscal 2015.
 
¿Cómo se envía la información contable? 
 
La información se enviará en archivos comprimidos con formato zip  a través del Buzón Tributario o en la sección Trámites de este Portal; el envío debe hacerse con firma electrónica vigente. 
 
Asimismo, para los meses subsecuentes se estará a lo siguiente:
 
El catálogo de cuentas deberá enviarse por primera vez junto con la balanza de comprobación y cuando se modifiquen o adicionen  las cuentas de mayor o las subcuentas que fueron reportadas.
 
La balanza de comprobación:
Tratándose de personas morales y personas físicas, dentro los primeros 3 o 5 días hábiles respectivamente, al segundo mes posterior al que corresponde la información y así sucesivamente.

Los contribuyentes que coticen en Bolsa enviarán sus archivos mensuales dentro los primeros 3 días hábiles, al segundo mes posterior al trimestre que corresponda.

Las personas morales y las personas físicas del Sector Primario que optaron por presentar sus declaraciones semestralmente, podrán enviar sus archivos mensuales dentro de los primeros 3 y 5 días hábiles respectivamente al segundo mes posterior al semestre que corresponda.
  
Preguntas frecuentes
 
 
Marco jurídico
Artículo 28 del Código Fiscal de la Federación
 
Artículos 33 y 34 del Reglamento del Código Fiscal de la Federación
 
(242 KB) Extracto de las Reglas de Contabilidad electrónica de la Resolución Miscelánea Fiscal para 2015

(949 KB) Primera Resolución de Modificaciones a la Resolución Miscelánea Fiscal 2015 (Extracto de la publicada en el Diario Oficial de la Federación el 03 de marzo 2015).
(2,933 KB) Anexo 24​ de la Resolución de modificaciones a la Resolución Miscelánea Fiscal 2015.
(106 KB) Segunda Resolución de Modificaciones a la Resolución Miscelánea Fiscal 2015 (Extracto de la publicada en el Diario Oficial de la Federación el 14 de mayo de 2015)
​​(126 KB) Tercera Resolución de Modificaciones a la Resolución Miscelánea Fiscal 2015 (Extracto de la publicada en el Diario Oficial de la Federación el 02 de julio de 2015)

​​Documentos técnicos 2017
- Catálogo de cuentas  (XSD) (XSLT)
- Balanza de comprobación  (XSD) (XSLT)
- Pólizas del periodo (XSD) (XSLT)
- Auxiliar de folios de comprobantes fiscales (XSD) (XSLT)
- Auxiliar de cuenta y subcuenta (XSD) (XSLT)​
- Sello Digital Contabilidad Electrónica (XSD) (XSLT)​

Documentos técnicos
- Catálogo de cuentas  (263 KBEstándar) (XSD) (XSLT)
- Balanza de comprobación  (272 KB Estándar) (XSD) (XSLT)
- Pólizas del periodo  (772 KB Estándar) (XSD) (XSLT)
- Auxiliar de folios de comprobantes fiscales  (516 KB Estándar) (XSD) (XSLT) 
- Auxiliar de cuenta y subcuenta  (402 KB Estándar) (XSD) (XSLT)
- Sello Digital Contabilidad Electrónica (139 KB Estándar) (XSD) (XSLT)

Catálogos:
- (542 KB)Código Agrupador de Cuentas del SAT
- (95 KB)Catálogo de monedas
- (75 KB) Catálogo de bancos
- (54 KB) Cátalogo de métodos de pago​

Validador de forma y sintaxis contabilidad electrónica

Resolución Miscelánea Fiscal 2015
(678 kB) Resolución (parte 1)
(1,054 kB)Resolución (parte 2)
(688 kB) Resolución (parte 3)
  
(161 KB) Séptima Resolución de Modificaciones a la Resolución Miscelánea Fiscal para 2014 
 
Quinta Resolución de Modificaciones a la Resolución Miscelánea Fiscal para 2014
(686 KB) Quinta Resolución parte 1
(151 KB) Quinta Resolución parte 2

Convertidor de Excel a XML

Video
Infografía
Comunicado de prensa
Solamente 203 mil 807 contribuyentes obligados a iniciar envío de información contable a partir de enero.

**Comment by tundebabzy** [comment]
Hi @Conestrait 
You can start and fund a bounty for this on https://erpnext.org/bounties

**Comment by rmehta** [comment]
@Conestrait Really hard to budget for this, but if we can start with say $2000, we can do the core functionality. Does that work?

**Comment by roy11111** [comment]
In the near future, I would be willing to have this option in your hosted paid plan, This is a very nice niche option for Mexico as most paid accounting/erp software here is 90's junk, but this only feature makes them unavoidable. You will get a lot of interest from Mexican companies/developers if some effort is put on having a basic version of CFDI on core as an option.

**Comment by epochc** [comment]
@conestrait, @roy11111: Would you two please collaborate, put your heads together and make a proposal to the Foundation that if we together build this feature, what else would we need to do to get say a 100 new installations of ERPNext in the next one year?

If we put a comprehensive plan that includes:

Establishing the Mexico chapter of ERPNext
Holding MeetUps of user community and developers
Some basic Social Media campaigns (Facebook inserts, Web Banners, LinkedIn Inserts. Please don't plan on anything too big or grandiose - we don't have the money for that)

So, if we build these features, establish a chapter and do some basic marketing:

How many new Installations do you think we will get in Mexico in the next 1 year?
How many ERPNext Foundation members do you think we will get in the next 1 year? (Check out https://erpnext.org/members)

Tough questions, but can we begin with some numbers however imperfect they are?

Thanks

Jay

**Comment by roy11111** [comment]
Those are great ideas:

This is how I see this being successful (perhaps a chicken and egg situation here, not sure if it makes sense to you).

1) Arrange erpnext.com page for Mexico localization similar to what QuickBooks (https://quickbooks.intuit.com/mx/ ) tried to do in our country but failed to supply electronic accounting (they didn't want to develop and only did CFDI interface via a third party but no electronic accounting). Make it clear that software is localized for our country. IRS (SAT) Electronic accounting will be mandatory within a few months and everybody will start to panic about getting some decent and nice software.

2) Focus offering on cloud anual (or monthly markup) contract in MXN with some kind of local mexican very basic phone/email support included. This support can be supplied by a third party and can have several levels of support/start up assurance packages customer would be willing to pay. Ideally use redundant servers at Dallas (quickest latency for all Mexico and not bad for US). Make it easy and price transparent for third parties to help promote the installations.

3) Fit an Spanish only forum for all Latin America/Spain customers, where volunteers are willing to create a nice community on erpnext.com In Latin America, most people feel better in their native language and a lot of us don't speak english at all. So it has to be language friendly. Google-SEO will find us easily and people will come to try. This will also promote a Mexico Chapter, easy communication and meetings. 

4) Product needs a better translation to Mexico Spanish, and so the User Manual. People like me can freely help with that. In our case, this is essential for product assimilation.

5) QB has limited functionally in comparison of ERPNext, they are charging $120 usd per year for 5 users as compared with ERPNext $300. I don't see an issue for a mexican SMB company to afford $300 or more for year if their operations are solved. To develop confidence initially in very small businesses, Evaluate the possibility for SaaS to charge for "module-function" but leave open all modules. Mexican will feel confortable to pay more if they use more in a software they already trust. I.E.  request for quotation, manufacturing, projects, HR, POS, etc may be some functionally that can be used/surcharged later.

6) If this is fit together and we have an approachable product compatible with Mexico, we may get around 100 customers first year perhaps; some small, some medium sized. Perhaps initially only 10-20% would become ERPNext Foundation members, people who want priority enhancements. but second year maybe can go 10 times that, as competition has been very slow to catch up in years.

What are your thoughts?

**Comment by roy11111** [comment]
Just some clarification here:
a) Electronic Invoicing in Mexico is not new, it has been mandatory since several years ago. Here you can't just print an invoice with any format like ERPNext because is illegal, it has to be electronically "sealed" via an api IRS approved provider who does that via REST. I don't know the specifics of this, but understand that is a easy process, as to send the invoice data and receive in exchange a hash code with a "seal" XML file; then you can use any nice format and add those hash codes at the bottom and send the XML/PDF pair via customer registered email. "delivery slips" can be done without that electronic sealing process, though.

b) What is added this time is electronic accounting, I'm not very familiar with this concept but understand is a "monthly batch" of income/outcome "cash flow report"  and "trial balance report". This may be done manually by uploading those formats in the IRS portal or perhaps via REST API also. This has to comply with special format and I imagine they also use XML for this if you upload manually or enclose that in the API if you do that with a software click.

Those would be the basic specifics , with some exceptions perhaps all this information is already managed in ERPNext so mostly matter of interfacing/formatting.

**Comment by roy11111** [comment]
Please, in case this initiative gets traction somehow,  count on me for doing whole user manual translation and also code Spanish translation as a volunteer.

**Comment by krnkris** [comment]
In Hungary from this year
it is mandatory to send INVOICES (from today with more than 100.000,-Ft VAT, but near future all INVOICES) direct to IRS.

Please find discussion:

https://discuss.erpnext.com/t/how-to-make-xml-invoice-send-it-automatically-hungary-onlineszamla/29458

We can't use ERPNext for invoicing until the program not send automatically all invoices in regular basis.

**Comment by clarkejj** [comment]
https://discuss.erpnext.com/t/announcement-erpnext-version-10-will-be-released-on-25th-december-2017/31401/33

"We’re integrating the XML files from Mexican electronic invoices and the procedure to get the certificates for issuing invoices according to govmnt regulations."

Is this issue request done and complete or ongoing?

https://discuss.erpnext.com/t/factura-electronica-cfdi/3678/29

**Comment by Geramy** [comment]
Hi guys, what is the progress on this feature? Has CFDI been integrated into ERPNext yet, what is the plan?
Does it need more funding? How do we accelerate this feature?

**Comment by saimonsays199128** [comment]
Any update on this?

**Comment by cesarrm23** [comment]
Any update on this?

**Comment by Geramy** [comment]
Updates, how much is in the fund and how much more is required?

**Comment by Geramy** [comment]
Ping

**Comment by Geramy** [comment]
@ankush did this feature get bumped or did it give finished? Who is the maintainer of this feature?

**Comment by ankush** [comment]
@Geramy AFAIK we do not have a huge presence in Mexico. If someone from Mexico wants to partner with us for localization please write to us. https://erpnext.com/contact-form 


"Localise ERPNext for Your Country": https://www.youtube.com/watch?v=TPERj6eZ6nM

**Comment by Geramy** [comment]
I am in Mexico and use ERP Next, I’ll look in to this. Thank you.
