### ISSUE TITLE
Once clicked on "Attach", it doesnt show the option to "Browse" to the required file, while using Stock Reconciliation feature to update stock

### ISSUE THREAD

**Issue by abhinav666** [frappe/erpnext#11100]
Hi,
I am suddenly not able to attach the CSV File for stock updation in stock reconcilation
Once clicked on "Attach", it doesnt show the option to "Browse" to the required file.
I have imported data before. Just not able to do it now.
Please help, being stuck here since yesterday is stopping me to do any work at all of my outlets.
Thanks

**Comment by tundebabzy** [comment]
Fixed in frappe /frappe#4249. It will be merged ASAP

**Comment by tundebabzy** [comment]
Fixed in frappe/frappe#4249. It will be merged ASAP
