### ISSUE TITLE
Background Image Upload not operative [BUG]

### ISSUE THREAD

**Issue by Tropicalrambler** [frappe/erpnext#11104]
Possible bug in ERPNext v9

My Settings > Background Image > Attach

When image is selected for uploading, the **Upload** button seems not to be operating, thus not allowing user to set background image. Even if you attach an image to the doctype using Frappé framework, and select it from existing attachments, it still will not set the background image. Frappé framework's attach function is operating normally.   Tested on Chrome, Firefox and Safari. Same results.

**Comment by tundebabzy** [comment]
There is a problem with uploads (frappe/frappe#4246) for which a PR for a fix has been sent. Any traceback

**Comment by tundebabzy** [comment]
Hi @Tropicalrambler 
Are you still experiencing this?

**Comment by vishdha** [comment]
![car](https://user-images.githubusercontent.com/6947417/32776629-2b598dbe-c959-11e7-94c8-46cd780896db.png)
Hi @Tropicalrambler
It's working on latest Version
