### ISSUE TITLE
[BUG] Multiple prices for item showing in online POS -   preventing quick barcode entry 

### ISSUE THREAD

**Issue by taherkhalil** [frappe/erpnext#11103]
- In online POS there are 2 prices displayed for each item which is preventing quick entry.
![image](https://user-images.githubusercontent.com/20456072/31286575-45d35ef0-aac7-11e7-9019-2e119fe040ab.png)
**ofline POS - single price, quick entry through barcode..**

![image](https://user-images.githubusercontent.com/20456072/31286604-604e5b90-aac7-11e7-85b3-ebcd70a1c253.png)
**Online POS for the same item showing multiple entries ,_notice barcode quick entry disabled_** 

- It also sometimes shows different prices but enters the actual price in cart on clicking either.
![image](https://user-images.githubusercontent.com/20456072/31287169-0acd37ac-aac9-11e7-804a-d37ff6c684f5.png)
33 is actual price , enters 33 on pressing either.

so after troubleshooting the hell out of it i finally came up with the reason.
**REASON:**

- **PRICE list based on _TEMPLATE_**
1. you create a template with a default standard selling rate .
2.Then you create a variant and give a standard selling rate for the variant (same or different) -_this is the actual price which should be considered for sale of that variant as standard selling_

In the template a standard selling price list is created for the template- **which should not supposed happen as the template is NOT considered for sale**
 And also in the variant the standard price list is created - expected behavior 

---- SO while in POS both these selling rate are displayed but only the variant rate is considered....
the display of the "template created price list" causes the issue.

please look into it and resolve.

**Comment by rohitwaghchaure** [comment]
Hi @taherkhalil 

Regarding multiple item showing for one barcode issue has fixed can you please pull latest code and check.
Regarding price issue, did you defined selling price list in the POS Profile?

**Comment by taherkhalil** [comment]
Hi @rohitwaghchaure ,
pulled the latest code from develop branch - up-to date..
Selling price list is defined as "standard Selling" in POS profile .
![image](https://user-images.githubusercontent.com/20456072/31308263-5107dcfa-ab7c-11e7-827d-f6cafe854bf3.png)

**Issue still persists** 
 There are no errors on console when entering barcode
the only warnings in console  are at refresh and customer selection.

> Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/  
> base_amount: could not find docfield in method precision() 
> TypeError: this.container is null[Learn More]  
> base_amount: could not find docfield in method precision() 
> TypeError: this.container is null[Learn More]  
> Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.  desk

but i don't think it impacts in anyway.
Cant understand the exact reason at my end , the only thing is that if i delete the standard selling price list from the template then only 1 price is shown but still doesn't enable quick entry.

please check.

**Comment by taherkhalil** [comment]
also the [Fix] Discount field not displaying in offline POS #11089 issue still seems to be persisting at offline POS - 
Is it just in my case ?
I am testing all this on local Ubuntu 14.04 .
.
here is snap on my complete pos profile ,,only 1 :  

![image](https://user-images.githubusercontent.com/20456072/31308360-6c3e5326-ab7e-11e7-8d4a-230be4284a01.png)
![image](https://user-images.githubusercontent.com/20456072/31308363-7086c33c-ab7e-11e7-8b40-360325bb5298.png)

please advice. 
regards,

**Comment by taherkhalil** [comment]
@rohitwaghchaure - any updates?

**Comment by rohitwaghchaure** [comment]
@taherkhalil 

We have released the fixes of POS, can you please check

**Comment by taherkhalil** [comment]
@rohitwaghchaure 

No not yet , 
most all other POS issue fixed :+1:    but not this one..
Has no issues with single items i.e items without variant/template ....goes smoothly with barcode as it has only single price list.
Check out test shots after latest pull ..
created new item template and variant with different selling price and one same..
![image](https://user-images.githubusercontent.com/20456072/31442481-42e2396a-ae9f-11e7-80af-ec0d69a7bc6b.png)
![image](https://user-images.githubusercontent.com/20456072/31442486-462adafa-ae9f-11e7-89b8-cfa6b60021d1.png)
![image](https://user-images.githubusercontent.com/20456072/31442492-4a2e8d86-ae9f-11e7-86d4-32e14e8f3c8a.png)
![image](https://user-images.githubusercontent.com/20456072/31442591-93a333ae-ae9f-11e7-873f-214507bfcdd1.png)

selecting any -one will put the actual variant price in cart (atleast thats right) - but it shouldn't show multiple in first place.

the quick resolution is to create templates without a price but shouldn't the template price be as default when all variants (maybe 10,50or more) have same price so you don't need to add individually in all...-- 
**ideally each Barcode should have one price in one price list**
_**are you able to replicate the issue?**_

Appreciate all your effort and hardwork - 
hope you find a resolution quick.

thanks,

**Comment by rohitwaghchaure** [comment]
System only shows the rates of price list defined in the POS Profile, it only supports single price list not multiple.
As we have fixed this issue, I am closing the issue. Feel free to reopen if issue persists
