### ISSUE TITLE
Payment entry showing wrong difference amount for party type supplier and payment type Pay

### ISSUE THREAD

**Issue by rohitwaghchaure** [frappe/erpnext#11110]
![screen shot 2017-10-08 at 12 20 53 pm](https://user-images.githubusercontent.com/8780500/31314652-4b2cb894-ac23-11e7-8342-fea14f8837d9.png)

Paid Amount = 10000
Allocated = 7000
Bank Chanrges = 3000
Difference amount should be zero

**Comment by tundebabzy** [comment]
#11135
