### ISSUE TITLE
Error in the Address fetched in Sales Order.

### ISSUE THREAD

**Issue by Arundhatii** [frappe/erpnext#11129]
Reported via https://frappe.erpnext.com/desk#Form/Issue/WN-SUP28330
If customer is having two address Shipping and Billing. The billing address in fetched in the sales order document. This works fine if the Shipping address is checked as preferred Shipping address.
Refer the gif attached. 

![billing address issue](https://user-images.githubusercontent.com/20164097/31334224-06e63f8c-ad0b-11e7-8052-793736c407be.gif)

**Comment by tundebabzy** [comment]
#11145
