### ISSUE TITLE
Error on Upload in Stock Reconciliation.

### ISSUE THREAD

**Issue by Arundhatii** [frappe/erpnext#11123]
Reported via https://frappe.erpnext.com/desk#Form/Issue/WN-SUP28328
Refer the gif attached.
![upload error in stock reco](https://user-images.githubusercontent.com/20164097/31331755-4b5592e4-ad01-11e7-9d36-cbe27aec9a2d.gif)

**Comment by tundebabzy** [comment]
Fixed and merged in frappe/frappe#4247
