### ISSUE TITLE
Calculating Margin Amount instead of % Discount

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#11120]
In the item's table, if Item already has Price List Rate, and user edits Basic Rate, then % Discount was auto-calculated. Now, instead of % Discount, Margin %/Amount is calculated. Is this design intentional or is it an issue?

![screen shot 2017-10-09 at 1 27 41 pm](https://user-images.githubusercontent.com/910238/31329063-e72547e8-acf5-11e7-9eee-182f21fd0ebe.png)

**Comment by Olawale1** [comment]
Hi,

I believe 'Discount on Price List Rate' should be more appropriate for this. Margin should be calculated against Valuation Rate (not Price List Rate)

There may however be a setting where the user can select if Margin should be calculated against Valuation Rate or Price List Rate. If Price List Rate is selected, then the user must specify the exact Price List to be used. I think this may be beneficial to lots of people

Cheers!

**Comment by rmehta** [comment]
@umairsy If its > 0, it will be margin, else discount.

Please re-open if you still think this is a bug

**Comment by Olawale1** [comment]
@rmehta 

Trust you're doing great. It's important the field is labelled as "Margin on Price List Rate" else it could be misleading and confusing

Also, the label "Discount (%) on Price List Rate with Margin" needs clarification. Maybe the wording needs to be changed?

Cheers!
