### ISSUE TITLE
Access-Control-Allow-Origin when using rest api

### ISSUE THREAD

**Issue by kyabroudi** [frappe/erpnext#11121]
I have website on my localhost and erpnext hosted as domain.erpnext.com

I’ve tested login api using postman and works fine but when trying through angular it return error

`No ‘Access-Control-Allow-Origin’ header is present on the requested resource
`

so Ive read a solution about installing Access-Control-Allow-Origin chrome extension but gives me another error like this
`
“{“message”:“Incomplete login details”,“exc”:”[“Traceback (most recent call last):\n File \”/home/frappe/benches/bench-2017-10-05/apps/frappe/frappe/app.py\", line 54, in application\n init_request(request)\n File \"/home/frappe/benches/bench-2017-10-05/apps/frappe/frappe/app.py\", line 116, in init_request\n frappe.local.http_request = frappe.auth.HTTPRequest()\n File \"/home/frappe/benches/bench-2017-10-05/apps/frappe/frappe/auth.py\", line 53, in init\n frappe.local.login_manager = LoginManager()\n File \"/home/frappe/benches/bench-2017-10-05/apps/frappe/frappe/auth.py\", line 107, in init\n if self.login()==False: return\n File \"/home/frappe/benches/bench-2017-10-05/apps/frappe/frappe/auth.py\", line 126, in login\n self.authenticate(user=user, pwd=pwd)\n File \"/home/frappe/benches/bench-2017-10-05/apps/frappe/frappe/auth.py\", line 197, in authenticate\n self.fail(_(‘Incomplete login details’), user=user)\n File \"/home/frappe/benches/bench-2017-10-05/apps/frappe/frappe/auth.py\", line 228, in fail\n raise frappe.AuthenticationError\nAuthenticationError\n"]"}"`

Ive tested the api with postman it works fine 
so any help ?!

**Comment by rmehta** [comment]
@kyabroudi you need to set the security policy in your angular app.
