### ISSUE TITLE
POS Incorrect Total Amount when we add or remove product from cart.

### ISSUE THREAD

**Issue by jp96** [frappe/erpnext#11138]
Bug in POS Incorrect Total Amount when we add or remove product from cart. Payment mode pop-up in pos shows wrong Total Amount.

Steps as below:
1. Add an item-1 in cart having 2 qty.
2. Add another item-2, item-3 in cart having 1 qty.
3. Click Pay to get payment mode pop-up check Total Amount value which will be correct.
4. Don't submit but close pop-up.
5. Remove item-2 or item-3 from cart. Which will change Total Amount but correct Total Amount is not getting updated on pop-up.

In addition to Total Amount field, corresponding fields **Paid Amount** and **Outstanding Amount** are also not getting updated.

![pos total amount](https://user-images.githubusercontent.com/3703266/31372769-fa8f31c6-adb4-11e7-8660-4580e71ea3a8.gif)

For **Paid Amount** and **Outstanding Amount**
![pos outstanding amount](https://user-images.githubusercontent.com/3703266/31373213-d01d6294-adb6-11e7-90b3-15c6a7150570.gif)

**Comment by rohitwaghchaure** [comment]
@jp96 

This issue is f[ixed](https://github.com/frappe/erpnext/pull/11147), can you please pull latest code and check
