### ISSUE TITLE
Link Single Opportunity to multiple customer

### ISSUE THREAD

**Issue by paryushan** [frappe/erpnext#11134]
Hi-

Can somebody be able to help me to add multiple customer to single opportunity.

We are a product supplier (Central Air Conditioning Products) to Project Industry. We have multiple agency attached to one Project (Opportunity) i.e Architect, Civil Construction Company, Client Etc.

Also during Tendering stage we have to quote one opportunity to many civil construction company (customer) and in later stages the tender get awarded to one civil construction company (Customer).

Currently we are duplicating single opportunity for different customer quoting same project.

we want work out on solution that we can link multiple customer to one opportunity to avoid many duplications.

kindly help.

Regards

Paryushan Jain

**Comment by tundebabzy** [comment]
Hi @paryushan 
This should be on our forum. We use github for bugs and feature requests. (https://discuss.erpnext.com)
