### ISSUE TITLE
Problem with Shopify Sync

### ISSUE THREAD

**Issue by Ganinakris** [frappe/erpnext#11149]
Hi, for some reason some of the products don't sync with Shopify. Why? Please see attached file. This product doesn't appear on the web after sync and exact the same product but  Bracelet does!
<img width="1197" alt="screen shot 2017-10-11 at 9 05 12 am" src="https://user-images.githubusercontent.com/29830158/31418985-55665af8-ae63-11e7-9d25-aa1e53000702.png">

**Comment by ankush** [comment]
This two-way integration has been deprecated. Closing.
