### ISSUE TITLE
Employee Advance

### ISSUE THREAD

**Issue by nabinhait** [frappe/erpnext#11141]
- [ ] Employee Advance
	- Series
	- Employee
	- Employee Name (auto fetch)
	- Posting Date
	- Approver
	- Approval Status (enable for approver)
	- Purpose
	- Advance amount
	- Paid amount
	- Claimed Amount
	- Status
	- Company (fetch from employee)
	- Advance Account (fetch from company)
	- Mode of Payment 
	
- [ ] Make Payment Entry
	- via Journal Entry / Payment Entry
	- Debit Employee Advance account and credit bank/cash
	- Update paid amount in advance form

- [ ] Expense Claim
	- Add a child table for advance
	- Fetch advances on change of Employee
	- validate allocated amount
	- Changes in gl entries
	- Update claimed amount in advance form

- [ ] Test Case
- [ ] Documentation

<img width="703" alt="screen shot 2017-10-11 at 8 07 28 pm" src="https://user-images.githubusercontent.com/836784/31447569-f23351d6-aebf-11e7-909e-71963b0a7f9f.png">

**Comment by SOLOSOFTMA** [comment]
i think advance could also related to payslip which get deducted automatiqualy like loan for the same month.

regards
