### ISSUE TITLE
Subcontracting bug

### ISSUE THREAD

**Issue by Goeppert** [frappe/erpnext#11144]
Hi there,  

Please take a look at this bug in the subcontracting workflow:
https://vimeo.com/237442960
Use password:  ERP

**Comment by umairsy** [comment]
Hello,

In the Purchase Order (which is not cancelled), the BOM selected for an item (BOM-GPRT000034-001) has 13 qty mentioned for the raw-material, hence Supplied Qty in the Purchase Order was calculated correctly. I believe you have revised BOM and amended Purchase Order after which it has worked fine?
