### ISSUE TITLE
[Bug] POS billing - Outstanding amount not updating

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#11150]
WN-SUP28359

Steps:

1. I selected items in the POS Invoice and then check Pay option.
1. Then I closed Pay option, and applied discount on the items.
1. Then I open Pay again, but it shown old price only. It didn't get refreshed based on the changes made in the item's price.

![screen shot 2017-10-11 at 11 19 24 am](https://user-images.githubusercontent.com/910238/31424201-95b78fec-ae76-11e7-8dbc-a7f2bf5db1db.png)

**Comment by rohitwaghchaure** [comment]
Fixed via https://github.com/frappe/erpnext/pull/11147
