### ISSUE TITLE
[BUG] Can't set value 0 to Billing Hours in Timesheet

### ISSUE THREAD

**Issue by paulator** [frappe/erpnext#11153]
When I create a new line in a Timesheet and enter some data to get a valid value in Hours and I select the checkbox "Billing", the value of Billing Hours is set to the value of the Hours.

-> This is ok.

When I change the value of Billing Hours to any other value and save the Timesheet, the changed value is saved.

-> This is ok.

But if I want to set Billing Hours to 0 and save the Timesheet and complete reload the Timesheet and open the Line, the Billing Hours is not 0! It is set to the last persisted value.

-> This is not ok.

I would expect to persist 0 as value for Billing Hours.

**Comment by rohitwaghchaure** [comment]
@paulator 

Disabled option Bill if you wan't to keep billing hours as zero
![screen shot 2017-10-11 at 3 22 43 pm](https://user-images.githubusercontent.com/8780500/31434262-81e5ead6-ae99-11e7-89a7-cbc7ba713ce6.png)

**Comment by paulator** [comment]
I can do it. But if I activate Bill again, It will be set to the persisted value again. Is it not allowed to set the value to 0?

**Comment by tundebabzy** [comment]
Hi @paulator 
> I can do it. But if I activate Bill again, It will be set to the persisted value again. Is it not allowed to set the value to 0?

Yes it is not allowed. If the timesheet is billable and number of hours is set to 0, we set billable_hours to the same value as worked_hours. You can check #9535 and #10139 for some background.

**Comment by hamzahabeeeeb** [comment]
it still says hours sould be more than 0 when the billable is unchecked

**Comment by hamzahabeeeeb** [comment]
any resolution as of now?
