### ISSUE TITLE
Items Delete not working

### ISSUE THREAD

**Issue by Admakbs** [frappe/erpnext#11155]
Dear Team 
this is my machine link https://smat.erpnext.com/desk#
i tried to delete items in my machine but unfortunately when i marked it all i could not see a delete button, the system still showing me a new button, i know creating new button should convert to delete button when I mark it all 

![stockerror](https://user-images.githubusercontent.com/29948389/31436345-5486340a-ae8b-11e7-8ebb-b8c0e45f4c1f.png)

**Comment by rohitwaghchaure** [comment]
Hi @Admakbs 

I have checked on local account and it's working properly. Can you share version details of your apps?

![screen shot 2017-10-11 at 4 35 12 pm](https://user-images.githubusercontent.com/8780500/31437274-55582714-aea2-11e7-8ed3-5e3c4f8cce02.png)

**Comment by mbauskar** [comment]
@Admakbs,

Please check if the User has the delete permissions for Item document.

<img width="924" alt="screen shot 2017-10-11 at 4 35 32 pm" src="https://user-images.githubusercontent.com/11224291/31437265-4dbd41d8-aea2-11e7-844c-6cb9b8439da1.png">

**Comment by Admakbs** [comment]
Thank you, it is working good now
