### ISSUE TITLE
Ability to select odd or even saturday while making holiday list

### ISSUE THREAD

**Issue by ashish-greycube** [frappe/erpnext#11158]
In india especially banks and semi-govt organizations, give holiday on alternate saturday. They choose either odd or even saturday. i.e. odd saturday means for each month saturday falling on 7th/21st etc is off. At present "Get weekly off Dates" doesn't have choice for odd or even saturday.
I am not sure if this functionality is useful for other countries else it should be tied with county
Example screen shot is below. Dropdown can have Saturday/Odd Saturday/Even Saturday
![image](https://user-images.githubusercontent.com/29812965/31439726-d526e61c-aeaa-11e7-8918-5032109de089.png)

**Comment by tundebabzy** [comment]
Can you contribute such a feature even though it doesn't seem generic enough to me. If you can, assign yourself.

**Comment by ashish-greycube** [comment]
You are right...It is not that much generic.
...It is mostly used by in india especially banks and some private sector companies who wish to work on alternate Saturday....I am not sure about usefulness of this feature

**Comment by tundebabzy** [comment]
Let's close this then
