### ISSUE TITLE
Dropbox backup fail error

### ISSUE THREAD

**Issue by liveonstore** [frappe/erpnext#11152]
Backup Upload FailedOops, your automated backup to Dropbox failed.Error message:  Traceback (most recent call last):   File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py", line 45, in take_backup_to_dropbox     did_not_upload, error_log = backup_to_dropbox()   File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py", line 98, in backup_to_dropbox     upload_file_to_dropbox(filename, "/database", dropbox_client)   File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py", line 149, in upload_file_to_dropbox     file_size = os.path.getsize(encode(filename))   File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/env/lib/python2.7/genericpath.py", line 57, in getsize     return os.stat(filename).st_size OSError: [Errno 2] No such file or directory: './erpnext/private/backups/20171011_121632-erpnext-database.sql.gz' | Backup Upload FailedOops, your automated backup to Dropbox failed.Error message:  Traceback (most recent call last):   File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py", line 45, in take_backup_to_dropbox     did_not_upload, error_log = backup_to_dropbox()   File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py", line 98, in backup_to_dropbox     upload_file_to_dropbox(filename, "/database", dropbox_client)   File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py", line 149, in upload_file_to_dropbox     file_size = os.path.getsize(encode(filename))   File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/env/lib/python2.7/genericpath.py", line 57, in getsize     return os.stat(filename).st_size OSError: [Errno 2] No such file or directory: './erpnext/private/backups/20171011_121632-erpnext-database.sql.gz' |   | Backup Upload FailedOops, your automated backup to Dropbox failed.Error message:  Traceback (most recent call last):   File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py", line 45, in take_backup_to_dropbox     did_not_upload, error_log = backup_to_dropbox()   File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py", line 98, in backup_to_dropbox     upload_file_to_dropbox(filename, "/database", dropbox_client)   File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py", line 149, in upload_file_to_dropbox     file_size = os.path.getsize(encode(filename))   File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/env/lib/python2.7/genericpath.py", line 57, in getsize     return os.stat(filename).st_size OSError: [Errno 2] No such file or directory: './erpnext/private/backups/20171011_121632-erpnext-database.sql.gz' |   | Backup Upload FailedOops, your automated backup to Dropbox failed.Error message:  Traceback (most recent call last):   File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py", line 45, in take_backup_to_dropbox     did_not_upload, error_log = backup_to_dropbox()   File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py", line 98, in backup_to_dropbox     upload_file_to_dropbox(filename, "/database", dropbox_client)   File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py", line 149, in upload_file_to_dropbox     file_size = os.path.getsize(encode(filename))   File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/env/lib/python2.7/genericpath.py", line 57, in getsize     return os.stat(filename).st_size OSError: [Errno 2] No such file or directory: './erpnext/private/backups/20171011_121632-erpnext-database.sql.gz'
-- | -- | -- | -- | -- | --
Backup Upload FailedOops, your automated backup to Dropbox failed.Error message:  Traceback (most recent call last):   File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py", line 45, in take_backup_to_dropbox     did_not_upload, error_log = backup_to_dropbox()   File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py", line 98, in backup_to_dropbox     upload_file_to_dropbox(filename, "/database", dropbox_client)   File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py", line 149, in upload_file_to_dropbox     file_size = os.path.getsize(encode(filename))   File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/env/lib/python2.7/genericpath.py", line 57, in getsize     return os.stat(filename).st_size OSError: [Errno 2] No such file or directory: './erpnext/private/backups/20171011_121632-erpnext-database.sql.gz' |   | Backup Upload FailedOops, your automated backup to Dropbox failed.Error message:  Traceback (most recent call last):   File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py", line 45, in take_backup_to_dropbox     did_not_upload, error_log = backup_to_dropbox()   File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py", line 98, in backup_to_dropbox     upload_file_to_dropbox(filename, "/database", dropbox_client)   File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py", line 149, in upload_file_to_dropbox     file_size = os.path.getsize(encode(filename))   File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/env/lib/python2.7/genericpath.py", line 57, in getsize     return os.stat(filename).st_size OSError: [Errno 2] No such file or directory: './erpnext/private/backups/20171011_121632-erpnext-database.sql.gz' |   | Backup Upload FailedOops, your automated backup to Dropbox failed.Error message:  Traceback (most recent call last):   File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py", line 45, in take_backup_to_dropbox     did_not_upload, error_log = backup_to_dropbox()   File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py", line 98, in backup_to_dropbox     upload_file_to_dropbox(filename, "/database", dropbox_client)   File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py", line 149, in upload_file_to_dropbox     file_size = os.path.getsize(encode(filename))   File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/env/lib/python2.7/genericpath.py", line 57, in getsize     return os.stat(filename).st_size OSError: [Errno 2] No such file or directory: './erpnext/private/backups/20171011_121632-erpnext-database.sql.gz'
 
Backup Upload FailedOops, your automated backup to Dropbox failed.Error message:  Traceback (most recent call last):   File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py", line 45, in take_backup_to_dropbox     did_not_upload, error_log = backup_to_dropbox()   File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py", line 98, in backup_to_dropbox     upload_file_to_dropbox(filename, "/database", dropbox_client)   File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py", line 149, in upload_file_to_dropbox     file_size = os.path.getsize(encode(filename))   File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/env/lib/python2.7/genericpath.py", line 57, in getsize     return os.stat(filename).st_size OSError: [Errno 2] No such file or directory: './erpnext/private/backups/20171011_121632-erpnext-database.sql.gz' |   | Backup Upload FailedOops, your automated backup to Dropbox failed.Error message:  Traceback (most recent call last):   File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py", line 45, in take_backup_to_dropbox     did_not_upload, error_log = backup_to_dropbox()   File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py", line 98, in backup_to_dropbox     upload_file_to_dropbox(filename, "/database", dropbox_client)   File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py", line 149, in upload_file_to_dropbox     file_size = os.path.getsize(encode(filename))   File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/env/lib/python2.7/genericpath.py", line 57, in getsize     return os.stat(filename).st_size OSError: [Errno 2] No such file or directory: './erpnext/private/backups/20171011_121632-erpnext-database.sql.gz'
  | Backup Upload FailedOops, your automated backup to Dropbox failed.Error message:  Traceback (most recent call last):   File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py", line 45, in take_backup_to_dropbox     did_not_upload, error_log = backup_to_dropbox()   File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py", line 98, in backup_to_dropbox     upload_file_to_dropbox(filename, "/database", dropbox_client)   File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py", line 149, in upload_file_to_dropbox     file_size = os.path.getsize(encode(filename))   File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/env/lib/python2.7/genericpath.py", line 57, in getsize     return os.stat(filename).st_size OSError: [Errno 2] No such file or directory: './erpnext/private/backups/20171011_121632-erpnext-database.sql.gz'

**Comment by munimaubdullah** [comment]
Which Version of ERPNext are you using? Dropbox has changed their API, Please update ERPNext this fixed in current version.

**Comment by liveonstore** [comment]
i m using new 9.0 version & its not working for me

**Comment by saurabh6790** [comment]
fixing via ```https://github.com/frappe/frappe/pull/5375```
