### ISSUE TITLE
Issue - The print icon disappeared for draft - Sale order and Purchase Order 

### ISSUE THREAD

**Issue by alfredhy** [frappe/erpnext#11169]
We found that the print icon is disappeared in the draft version. Previously we can print the draft version for review

<img width="983" alt="default" src="https://user-images.githubusercontent.com/30999458/31478266-c94140bc-af41-11e7-9f04-b80de28bba9e.png">

**Comment by munimaubdullah** [comment]
Is it checked or unchecked?
![print](https://user-images.githubusercontent.com/6562529/31555339-7d1b2bcc-b062-11e7-9b25-116b48662455.png)
