### ISSUE TITLE
[Glitch/BUG] Offline POS Discount  amount field inaccurate and not reseting at new cart

### ISSUE THREAD

**Issue by taherkhalil** [frappe/erpnext#11167]
Offline POS discount field calculates wrong discount when entered percentage and only when refreshed it calculates accurately ..
also enter a percentage and then change the percentage --incorrect calculation.
also on new cart the old values entered in percentage and amount field persist which should be cleared .
![image](https://user-images.githubusercontent.com/20456072/31453076-7e1452b0-aeb9-11e7-88e2-3a91428343b5.png)
accurate calculation only after refresh .
![image](https://user-images.githubusercontent.com/20456072/31453086-8e6e39dc-aeb9-11e7-92f1-2d31f22de28f.png)
change percentage from 10 to 20--incorrect calculation .
![image](https://user-images.githubusercontent.com/20456072/31453102-a12bd70a-aeb9-11e7-9c6e-9c92ed09bbb0.png)
after new cart , same percentage value remain in field ..

**Comment by taherkhalil** [comment]
@umairsy 
Could you please at  the least resolve the clearing of field on new cart?

Thanks

**Comment by rohitwaghchaure** [comment]
@taherkhalil 

Thanks for reporting an issue, we have fixed this issue and soon we'll release it
