### ISSUE TITLE
Salary Process Detail ADDR Null

### ISSUE THREAD

**Issue by Helkyd** [frappe/erpnext#11164]
Based on this 
https://discuss.erpnext.com/t/salary-process-missing-salary-detail-abbr/29304

**Comment by PawanMeh** [comment]
This does not seem an issue in the latest version

![salary_slip](https://user-images.githubusercontent.com/20460498/31602736-9b47f8a8-b27b-11e7-898f-0c508b40f5a2.png)

**Comment by Helkyd** [comment]
This was merged ...can be closed. 
:)
