### ISSUE TITLE
Security bug in erpnext application

### ISSUE THREAD

**Issue by psdhatti707** [frappe/erpnext#11170]
Reported a security bug in the erpnext application at info@erpnext.com but not received any reply, please give me the right contact to report it.

**Comment by saurabh6790** [comment]
Please sent it to saurabh@erpnext.com

**Comment by psdhatti707** [comment]
Hi,

Thanks for the update, I am looking forward for a CVE for the
vulnerability, can you provide more information on same.

--

*Thanks and Regards*

*Prakash Dhatti*
