### ISSUE TITLE
Salary Slip Cancel Tool

### ISSUE THREAD

**Issue by Helkyd** [frappe/erpnext#11174]
Based on this 
https://discuss.erpnext.com/t/salary-slip-submitted-but-needs-to-be-re-processed/29307

This tool is required for companies with more 100+ employees...

**Comment by tundebabzy** [comment]
Hi @Helkyd 
I just discovered that this feature has been requested for since 2015. Please can you chip in on #3191 since the issue there covers this particular use case.
