### ISSUE TITLE
Packed items (table) in Sales Invoice

### ISSUE THREAD

**Issue by brentglover** [frappe/erpnext#11184]
Customizing Delivery Note and adding packed items (table) shows the singular product bundle item and all items in product bundle.

Customizing Sales Invoice and adding packed items (table) shows nothing just the singular product bundle item.

Tried again with custom HTML using...

`%- for item in doc.packed_items -%}

{{ item.item_code }} - {{item.item_name}}

{%- endfor -%}`

Same results - shows for delivery note but not for sales invoice.

Brent

**Comment by brentglover** [comment]
Update:

Print Hide is NOT ticked in Customize Form and same results - Good for DN, no show for SI

**Comment by umairsy** [comment]
Can you please share the screenshots?
