### ISSUE TITLE
Allow contribution of COA directly from ERPNext instances

### ISSUE THREAD

**Issue by Tropicalrambler** [frappe/erpnext#11183]
During the talk by @nabinhait at the ERPNext convention, Jay suggested that perhaps it would be a good idea for users to contribute their COA directly from within ERPNext.  Fantastic idea!   You setup your own accounts in ERPNext,  then at some point,  you desire to share them. A functionality such as a button or menu item should allow you to submit this instance of COA to accounts.erpnext.com. Only items required should be credentials, and perhaps a Title of this submission.

User should also have the capacity to choose:
[]Only Parent accounts
[]Amount of levels chosen

**Comment by Tropicalrambler** [comment]
I will elaborate on this further down the road as the conference winds down. (around end of October)

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.
