### ISSUE TITLE
Data Import - Double Import Action After Importing

### ISSUE THREAD

**Issue by OneiricIT** [frappe/erpnext#11180]
ERPNext v9.1.4 (master)
Frappe v9.1.6 (master)

When performing an import, the data is uploaded normally however shortly after it is imported again per below. Note the import button appears to be pressed although mouse cursor was not over it or clicked, and no keyboard entry made at that time. 

![2017-10-13_15-04-51](https://user-images.githubusercontent.com/22227933/31529998-ca9fc6ee-b028-11e7-94c9-9d21565a65d8.gif)

**Comment by umairsy** [comment]
Hi,

We recently pushed a fix for this bug. Please update your ERPNext account and try data import once again. If issue still prevails, share relevant details and reopen this issue.
