### ISSUE TITLE
Fiscal Calendar DocType

### ISSUE THREAD

**Issue by jwrober** [frappe/erpnext#11187]
I would like to propose a new doctype called Fiscal Calendar. The purpose of this document is to allow an administrator to populate a calendar of various event dates that are important. There should be an option for each event to set a notification based on a group or something.  Some examples:

- Fiscal Month Start
- Fiscal Month End
- Fiscal Quarter Start
- Fiscal Quarter End
- Pay Day
- Link to Holiday Schedule
- Estimated Taxes Due (support for more than one tax type)

Then employees can "subscribe" to the calendar. The idea is for employees to see on their calendar when paydates are or my accounting/finance folks to know when the fiscal periods begin/end or when taxes are due or whatever.

This new doctype would work closely with the existing Fiscal Year doctype.

Thanks

**Comment by tundebabzy** [comment]
Something like #9846?

**Comment by jwrober** [comment]
I see that PR #9846 was closed but another was merged in later. I certainly agree that having the pay dates as part of the calendar are important. However I also see a need for other activities to occur on a whole mess of other dates that have nothing to do with payroll cycles.

In thinking about this some more, you probably don't even need another major doctype, just a child doctype to handle the table of dates in the main fiscal calendar.

**Comment by tundebabzy** [comment]
> just a child doctype to handle the table of dates in the main fiscal calendar

Hmm. Good idea. I'm really interested in what you come up with.

> I see that PR #9846 was closed but another was merged in later.

Yeah. What I did was basically to open up those fields for manual entry with no validation as possibly 99% of companies have their fiscal year starting on the first day of the month.

**Comment by tundebabzy** [comment]
Hi @jwrober 
Have you come up with anything. Or perhaps, you can start a discussion about this on the forum.

**Comment by jwrober** [comment]
@tundebabzy - sorry did not realize you were looking for more commentary. What is it you are wanting to know or for me to add? Happy to do it, just not sure what you need.

**Comment by tundebabzy** [comment]
Just a detailed proposal with use cases and scenarios will be fine.

**Comment by jwrober** [comment]
https://discuss.erpnext.com/t/fiscal-calendar-doctype/30027

**Comment by jwrober** [comment]
Looks like the discuss post didn't get a lot of activity. Did the information I provide give you the context you needed for this git issue to be worked on? Happy to provide more details if you need it.
