### ISSUE TITLE
Serial No does not belong to Warehouse Stores - SC Did not cancel - Serial No is in the said warehouse  

### ISSUE THREAD

**Issue by shanmukhasai6** [frappe/erpnext#11189]
I am getting this error while cancelling the material receipt

![image](https://user-images.githubusercontent.com/30374799/31561689-4e83c418-b076-11e7-8076-a2ca1d982424.png)

Serial No is in the said warehouse

![image](https://user-images.githubusercontent.com/30374799/31561703-532015a8-b076-11e7-9ca3-9b422ef434d7.png)

Please help this error is stopping me in proceeding with my work

**Comment by umairsy** [comment]
Hello,

Works fine in my test instance.

![screen shot 2017-10-23 at 6 10 02 pm](https://user-images.githubusercontent.com/910238/31889425-68510c1c-b81d-11e7-97b2-aceb50d35450.png)

Can you check is Serial No. was transferred to delivered at last date? In the Serial No. master, check Menu > Links for the transactions where this Serial No. is linked. 

If issue still prevails, please provide more details and re-open this issue.
