### ISSUE TITLE
Restoring a deleted document not working

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#11188]
![screen shot 2017-10-13 at 11 54 07 pm](https://user-images.githubusercontent.com/910238/31560650-c3b0d1d0-b072-11e7-9254-3fff384b2feb.png)

**Comment by mbauskar** [comment]
@umairsy,

Maybe rather than restoring the Cancelled documents we can have an option of `Restore and Amend`

**Comment by tundebabzy** [comment]
frappe/#4379
