### ISSUE TITLE
erpnext.org link to India service providers raises Uncaught Server Exception

### ISSUE THREAD

**Issue by clarkejj** [frappe/erpnext#11185]
Here's the user report
https://discuss.erpnext.com/t/error-in-erpnext-org-website/29369/2

**Comment by Yakulu** [comment]
I guess you may report it on [foundation website](https://github.com/erpnext/foundation/issues) repository.

**Comment by clarkejj** [comment]
Thanks Yakula!

Closed this and reported issue here https://github.com/erpnext/foundation/issues/65
