### ISSUE TITLE
Spanish Translation.

### ISSUE THREAD

**Issue by josmeldiaz21** [frappe/erpnext#11194]
There is some issue when spanish translation is selected, in the Health care Domain. 

Algo salió mal
Error de servidor: Se recomienda consultar los registros o contacte el soporte técnico.
 I think the SQL query has been translated too.  In the frappe.log file I got this.

ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '# **_seleccione * de tabPatient donde name = &#39;PID-00001&#39'_** at line 1")

**Comment by rkurungadam** [comment]
Hi, Just noted we used _ while constucting sql query in some places, @rmehta shall I push to hotfix branch?

**Comment by mbauskar** [comment]
@josmeldiaz21,

Can you share the full traceback?

@rkurungadam yes, please send the PR on hotfix :thumbsup:

**Comment by josmeldiaz21** [comment]
Hi, @mbauskar Im pretty new on this, I see that the code is fixed already. But can I ask what do you mean with full traceback?.

@raghukamath Thanks for reply.

**Comment by tundebabzy** [comment]
@josmeldiaz21 issue is now fixed

**Comment by josmeldiaz21** [comment]
@rkurungadam @mbauskar @tundebabzy Thanks.
