### ISSUE TITLE
Customer Portal - Invoices list diplay issue

### ISSUE THREAD

**Issue by gbard** [frappe/erpnext#11202]
Hello,

There is a display problem when I'm logged into the Customer Portal and looking at the Sales Invoice list from the left menu. I can see the list of all invoices but the table is so wide I can scroll for a while before seeing the 2nd and the 3rd (invoice total) collumn...

**Comment by mbauskar** [comment]
@gbard,

Invoices List seems to work just fine, Can you please share some screenshot?
<img width="1034" alt="screen shot 2017-10-16 at 11 30 49 am" src="https://user-images.githubusercontent.com/11224291/31597372-960c3e46-b265-11e7-83c1-24d31e6db313.png">

**Comment by gbard** [comment]
Here is what I get. French Language (fr).
ERPNext: v9.1.5 (master)
Frappe Framework: v9.1.7 (master)
Same thing in Chrome and Edge

![ss_portal](https://user-images.githubusercontent.com/11325063/31609415-14127f5e-b242-11e7-8da8-488703a3c1bc.jpg)

**Comment by gbard** [comment]
I'm still having this issue... anyone has an idea why the page width is this wide for me?

**Comment by gbard** [comment]
I'd like to reopen this issue since I still have this same issue. I'm using latest version and after digging a bit here is what I found:

![display_bug01](https://user-images.githubusercontent.com/11325063/36576488-09f612fe-181f-11e8-958f-b6073f56ad46.jpg)

![display_bug02](https://user-images.githubusercontent.com/11325063/36576501-13ee861a-181f-11e8-95ad-f0db395ff5f1.jpg)

As you can see, the width for page-content-wrapper is set to 7608.33px but I have no idea why.... As I said, I made no changes to any files.

@umairsy In your example, next to the Order number, the second column is used to display a "item-preview" ... some sort of preview of the sale invoice/order lines... In your example there is just a "iPhone 6" but in my example, there is multiple items with long names:. This is one of the "item-preview" I have in the list:

<div class="small text-muted items-preview ellipsis">COLLE HAIRBORN - STEP BY STEP , SAC ÉCHANTILLON (100), ROULLETE  3/4" X 108" BRUN, ROULETTE 3/4" X 108 " TRANSPARENT, TAPE EN U (36) BLEU , SOLVANT (UNITÉ), SEALANOL KIT, SOIN LAVANT CAS DE PELLICULES 200ML, SERUM COMPLEX PREPARATEUR 50ML, SOIN LAVANT CAS DE CHUTE 200ML, STYLING LINE CREME COIFFANTE 75ML, DAILY SOIN LAVANT RACINES GRASSES POINTES SECHES 1L, SUN BAUME PROTECTEUR SOLAIRE 200ML, SUN SOIN SPRAY PROTECTEUR SOLAIRE 150ML, SUN SOIN SPRAY PROTECTEUR SOLAIRE 150ML, BLONDE SOIN LAVANT LUMIERE 250ML, BLONDE SPRAY BIPHASE HYDRATANT 150ML, NUTRI BAUME NUTRITION 1L, OR &amp; ARGAN LAQUE ILLUMINANTE 500ML, OR &amp; ARGAN LAQUE ILLUMINANTE 500ML</div>

I think the problem might be because of that... Would it be possible to replace the "items-preview" column by something else like the invoice paid amount or the invoice balance... or simply remove the "items-preview" column?

My guess is that you will be able to reproduce the issue by creating a dummy invoice that includes multiple items with longer names.

Would someone mind trying to replicate this issue?

Thanks!

**Comment by gbard** [comment]
Yes, it does

Le lun. 14 janv. 2019 01 h 23, Jai Chavan <notifications@github.com> a
écrit :

**Comment by jaichavan** [comment]
Hello, @gbard 
I tried to replicate with long Item Names, seems to be working as expected. The first inline Item Name is being fetched. 

![GI-11202](https://user-images.githubusercontent.com/40264279/56469447-98342f80-6457-11e9-97c9-1746b5b72a50.gif)

Version details:

![image](https://user-images.githubusercontent.com/40264279/56469461-bd28a280-6457-11e9-9142-473ff960da7b.png)

Request you to upgrade your account to this version and let us know if the issue persists. For now, closing this thread ;)
