### ISSUE TITLE
Bug - Incorrect Total and Qty in Online POS Cart

### ISSUE THREAD

**Issue by jay-parikh** [frappe/erpnext#11209]
Adding items to cart by clicking quickly and multiple times causing incorrect Qty and Total.

Steps as below:

1. Add items to cart by clicking quickly and multiple time which causes Qty field not getting updated correctly.
2. Grand Total showing incorrect value.
3. Remove all items from cart one by one clicking (-) minus sign in Qty field.
4. Check Grand Total. Which should be non zero but showing some value.
5. Goto Menu and open form view, which is showing items which have been removed from Cart.

![qty](https://user-images.githubusercontent.com/3703266/31616023-25df725c-b2a9-11e7-9ec0-9625718949ee.gif)
![formview](https://user-images.githubusercontent.com/3703266/31616039-2e049cc8-b2a9-11e7-8976-a52361a36737.gif)

**Comment by jay-parikh** [comment]
@rohitwaghchaure @umairsy 
I got the solution and it's working. Sending PR - [https://github.com/frappe/erpnext/pull/11335](https://github.com/frappe/erpnext/pull/11335) for this issue.

Here is working gif:
![bug - incorrect total and qty in online pos cart 11209](https://user-images.githubusercontent.com/3703266/31998462-9b368044-b9ad-11e7-9f81-9218c5e0acd1.gif)

**Comment by jay-parikh** [comment]
@rohitwaghchaure Issue still exist and not resolved. I have tested with your fix today and still facing an issue. See gif
![image](https://user-images.githubusercontent.com/3703266/32219298-b9f72984-be53-11e7-863a-0294be3b2b15.png)

**Comment by tundebabzy** [comment]
#11470
