### ISSUE TITLE
Stock Reconciliation Tool. Instructions to enter data, like given from Data Import Tool

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#11207]
WN-SUP28432

Just like other CSV files, this csv file (for stock reconcile) don’t have instructions that from which row user have to put the data. Hope to see some instructions which will be helpful for new users.

**Comment by PawanMeh** [comment]
Have tried to address this as part of frappe repository issue:#4344

**Comment by tundebabzy** [comment]
Follow progress on frappe/frappe#4344
