### ISSUE TITLE
Soil Texture Doctype 

### ISSUE THREAD

**Issue by codingCoffee** [frappe/erpnext#11212]
- Soil Type (calculated based on the following)
    - Silt composition
    - Sand composition
    - Clay composition
- Bulk Density
- Field Capacity
- Wilting Point
- Hydraulic Conductivity
- Organic Matter

**Comment by Tropicalrambler** [comment]
The Soil types will eventually have to be plotted in a ternary plot as such:
https://help.plot.ly/ternary-scatter-plot/

**Comment by codingCoffee** [comment]
@Tropicalrambler if the % composition of any two of either clay, sand or silt is put in as an input, the soil type is automatically calculated. So is plotting really required??

**Comment by codingCoffee** [comment]
- [ ] Add Ternary Plot

**Comment by agritheory** [comment]
![image](https://user-images.githubusercontent.com/18033666/32994702-fb62efea-cd38-11e7-9a29-590cffe570e7.png)
Shouldn't the first field here  be a link to a Land Unit?

**Comment by codingCoffee** [comment]
@agritheory yes it should, will fix it up

**Comment by rmehta** [comment]
this seems done!
