### ISSUE TITLE
Crop Cycle Doctype

### ISSUE THREAD

**Issue by codingCoffee** [frappe/erpnext#11211]
- ISO-8061 week standard (could be a choice)
- start date
- end date
- Type of cycle
    - weekly
    - monthly
    - trimester
    - semi-annually
    - annually
- Expected Yield
- Link to BOM

Agri Tasks
- Production cut
- Final cut
- Irrigation
- Fertiliser Application
- Cleaning
- Fungicide Application
- Pesticide Application

And each agri task should have the following
- start date
- end date
- yield
- expense incurred

**Comment by agritheory** [comment]
ISO-8061 week standard is common in the greenhouse and market-vegetable industries but not used in others. I recommend a choice.

**Comment by agritheory** [comment]
Type of cycle - choose matching periodicity. I recommend days or weeks. The others will not be used

**Comment by agritheory** [comment]
Format Verb tense to Frappe standard (current tense)
Tasks

Production cut
Final cut
Irrigation
Fertiliser Application
Cleaning
Harvest - how is this intended to be different from Production cut or Final cut?
Fungicide Application 
Pesticide Application

**Comment by agritheory** [comment]
Expected Yeild

Yield is consistently spelled incorrectly in your issues, that could be a nasty bug to chase if it makes it into code

**Comment by agritheory** [comment]
Inputs (crops, seeds, fuel, etc.. )

What is the proposed structure for this? I would link a Cost Center instead and/or a BOM instead and leverage existing code.

**Comment by codingCoffee** [comment]
@agritheory 
Having a choice is a good idea for the dates
Bananas have a crop cycle of 9-12 months, so I guess it's good to have those options
- [x] Verb tense formatted to Frappe standard. Harvest was not required, my bad!
- [x] 'Yield' has be fixed, thanks for mentioning!
Inputs changed to link to BOM

**Comment by vishalseshagiri** [comment]
Assign please

**Comment by codingCoffee** [comment]
- [ ] Scrap the `Agriculture Task` Doctype and create a `Agriculture BOM` Doctype which includes fields from both `BOM` and `Tasks`

**Comment by Tropicalrambler** [comment]
A Crop Cycle should have a `Yearly` or `Less than a year` option.
Crops such as carrots, lettuce, etc.  have discrete crop cycles lasting less than a year.
Crops such as Mango, Oranges, etc. have lengthy crop cycles of 20 years or more  (some cases have been reported of 75+ year old trees still in commercial production).  For these crops, user can select the Yearly crop Cycle option, at which point ERPNext can tally when the crop cycle opens and when it ends in a yearly period.  This helps in proper accounting, and coincides with the accounting cycle.

**Comment by Tropicalrambler** [comment]
Add intercropping functionality, grouping crop cycles in tree fashion.  (To be discussed on October 31 meeting.)
