### ISSUE TITLE
landed cost voucher cannot get item from purchase receipt

### ISSUE THREAD

**Issue by luqmanhikmattulloh** [frappe/erpnext#11221]
Hi,
I cannot get items from purchase receipt on landed cost voucher page.
I show nothing and cannot get save the voucher?
is there any missing step I do?
I do  material request--> Purchase order --> Purchase receipt -->Purchase Invoice--> landed cost voucher.
Pls help
Thanks
luqman

**Comment by umairsy** [comment]
Hello,

Works fine my test instance.

![lcv](https://user-images.githubusercontent.com/910238/31888270-fe8e3826-b818-11e7-934d-4bc66c9fd48e.gif)

Please post this issue on discuss.erpnext.com with the ERPNext version and screenshots indicating an issue.
