### ISSUE TITLE
PO botton to draw last purchae price has gone

### ISSUE THREAD

**Issue by robertbecht** [frappe/erpnext#11227]
The botton to fetch last purchae price is no longer available...On safe a number of prices a fetched...Does not work properly...

Really annoying....the fetch previous price worked perfect...the fetch on safe not..fetches randomly some prices and skips others...
![image](https://user-images.githubusercontent.com/1532439/31792690-2a09a098-b51d-11e7-866e-8857a6b329e4.png)

**Comment by robertbecht** [comment]
Hi, this worked fine for many years and now does not anymore...bring the fetch prices back...plse

**Comment by kennethsequeira** [comment]
Button added back under tools:

Screenshot of version 12 PO

![image](https://user-images.githubusercontent.com/33246109/79049989-a7058a80-7c44-11ea-8400-1db96c3e2352.png)
