### ISSUE TITLE
Duplicate Sales Invoice Issue in POS V9

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#11225]
Hi ,

Steps to replicate:

1. Create a POS sale for an item that is not in stock
2. Wait for Invoice to get synced (Invoice will be in Draft due to shortage of stock)
3. Make a new sale with the same item

The following error pops up and stops the sync from progressing:

"Duplicate name Sales Invoice SINV-xxxxx"

Please help fix asap

Thanks

**Comment by rohitwaghchaure** [comment]
Hi @Olawale1 

Thanks for reporting an issue, we have identified and fixed the issue and soon we'll release it

**Comment by Olawale1** [comment]
Hi @rohitwaghchaure 

I just noticed that this issue affects invoices even when they are not in Draft! Hope the fix takes care of that scenario too!

By the way, hope this will be merged very soon as it's holding up sync of sales!

Thanks
