### ISSUE TITLE
Employee Leave Balance Deduction Error

### ISSUE THREAD

**Issue by flexy2ky** [frappe/erpnext#11222]
Hi @tundebabzy , 

There's seemingly a bug with the employee leave balance. 

When a leave is approved, the days approved is not deducted from the total available leave days hence the employee still has the full number of leave days prior to previous leave approval. This error shows up regardless of whether the leave approval is processed using workflow or direct. The issue has been on for over a month.
Here's a link to the support thread.

[https://discuss.erpnext.com/t/hr-leave-balance-issue/27717/9](url)

Kindly help fix.

Thanks.

**Comment by tundebabzy** [comment]
Hi @flexy2ky 
I couldn’t reproduce this issue. Are you sure the employee’s leave allocation has not been changed? Can you show a screenshot of the Leave Allocation list capturing the document relating to the said employee?

**Comment by flexy2ky** [comment]
@tundebabzy please see screenshot of document as requested:

![allocation](https://user-images.githubusercontent.com/32480024/31818194-f81b64e6-b58e-11e7-9fe3-8354af5c6d1e.JPG)

I have screenshots of employee application approval, leave balance report showing employee still has leave days already applied for and approved as well as a new leave application showing employee still has 10 days left in spite of only being allocated 10 days which had previously been approved in my post on Discuss.

I would have assumed i may have missed a configuration if i was the one that raised the issue in the forum. But i joined the forum after seeing the post while searching for answers to my issue and apparently some users have experienced the same issue a month or so before me.

**Comment by tundebabzy** [comment]
Fixed. Trail: https://discuss.erpnext.com/t/hr-leave-balance-issue/27717/25
