### ISSUE TITLE
Primary addresses and contacts

### ISSUE THREAD

**Issue by aboganas** [frappe/erpnext#11248]
When `is_primary_address` or `is_shipping_address` is checked in Address Doctype, then this address becomes primary for every Doctype that links to it (e.g. Customer) also similar for selecting `is_primary_contact` in contact doctype.  
However, this is not valid. For example, customer A and B use Company_1 as one of their addresses, but only customer A  wants Company_1 to be his primary address. In current design, Company_1 will become primary address for both customer A and B

I suggest instead of selecting `is_primary_address` or `is_shipping_address` in the address doctype, it should be moved to the customer doctype (similar for primary contact). Also customer should only have one primary for each `address_type`, and if there is only one address for a given address_type then this address should be auto selected as primary

**Comment by umairsy** [comment]
Hello,

Currently, Address DocType is not designed for the use-case where same address applies to two customers. Generally, each Customer has separate and unique address. The child table is useful if your Customer also happens to be your supplier. The quickest resolve/work-around for this use-case would be to create a separate address master for each Customer. Given you use-case, for Customer B, you can choose to not check "Is Primary" in the Address master.
