### ISSUE TITLE
Report Summary

### ISSUE THREAD

**Issue by nasirshah67** [frappe/erpnext#11240]
Need report type which will show summery for a certain activity. we have report which in detail, below example show a sample summery report.

![report sunmmery](https://user-images.githubusercontent.com/32841502/31701771-5301b640-b3db-11e7-8c2c-edf37298ab70.jpg)

Need this type of summery report for all report that are currently available.

Thank You

**Comment by nasirshah67** [comment]
Dear Team

can some one update when the solution for above will be available?

**Comment by deepeshgarg007** [comment]
@nasirshah67 We have group by feature in list views now. Please check
