### ISSUE TITLE
BOM - Update costs is not working properly

### ISSUE THREAD

**Issue by ojanovsky** [frappe/erpnext#11256]
Hello,

I have the same problem with costs calculating in BOM.
ERPNext 9.1.6

I have one item as part01 with Valuation Rate = 20 in Material group.
I have one item as product01.
When I create BOM for product01, select Rate Of Materials Based On = "Value rate "and I add part01 into Materials, error message is shown.
Message: Valuation Rate not found for Item part01 .

For click on Update costs, message is similar.

What I do wrong?

**Comment by umairsy** [comment]
Hello,

Did you also add some opening stock for the part01 with valuation at 20? Only if stock ledger entry is found for an item, the valuation rate is fetched from there. Re-open if issue still exists.

**Comment by ojanovsky** [comment]
Hello,
You are rigth. I don't have any receipt of item and initial amount is zero.
Thank you for your explanation.

Ondrej
