### ISSUE TITLE
Supplier Quotation View List

### ISSUE THREAD

**Issue by nasirshah67** [frappe/erpnext#11250]
Dear Team

Procurement user enter quotes that are received from supplier, since supplier is not connected to our ERP so  procurement user will enter quotes. Quotes are mostly created against Material Request. 
With the current format, if 1st quote is created then this quote will that no. of lines equivalent to the no. of items in the quote.  For example if the quote has 10 items then  the quote will show 10 rows which is not proper way.(check the below image)

![quotation view list](https://user-images.githubusercontent.com/32841502/31755849-59ea6f5a-b4a9-11e7-93de-446a28f5fb55.png)

Please make it a single quotes line even there are multiple items inside quote, this will facilitate user to overview multiple quotes.

Thank You

**Comment by nasirshah67** [comment]
Dear Team

can some one update when the solution for above will be available?

**Comment by umairsy** [comment]
Hello Nasir,

The feature of multiple rows being shown in the list view was added based on customer's demand. Let's see if your feature suggests draws any traction. Hope you will understand that to keep ERPNext generic, we need to design feature in the way that it can address maximum use-cases. As an alternative option, you can also check report view. If there is no column picked from the child table, then you will only see one row for each transaction.

**Comment by rmehta** [comment]
If you have a child item in the list view, this is the only option, maybe some indicator to show that this is a repeat item would be fine.
