### ISSUE TITLE
Adding custom filed to Sales Invoice not work

### ISSUE THREAD

**Issue by dufani1** [frappe/erpnext#11269]
I added the signature custom filed to sales invoice but the filed dose not appear in the invoice form although the custom field is updated properly in sales invoice doctype.
Please advise…
ERPNext 9.1.6

**Comment by umairsy** [comment]
Hello,

This works fine in my test account.

Is section in which custom field added visible? Was there any condition defined for field visibility? Perm level set for the field, do you have permission on that perm level?

Please post this query on discuss.erpnext.com
