### ISSUE TITLE
[POS] Item search not working properly

### ISSUE THREAD

**Issue by chdecultot** [frappe/erpnext#11273]
Hi,

When making a search for an item in the POS interface (online), the behaviour is quite strange.

I am trying to search for an item called "chemin de ronde - 2013" but when I enter "chemin" in the search box, the system only retrieves a few of the items starting with "chemin":
![image](https://user-images.githubusercontent.com/4903591/31852220-53dc05fc-b674-11e7-8ccb-8cd2130c7a92.png)

I need to add the wildcard and look for "201..." to get all results:

![image](https://user-images.githubusercontent.com/4903591/31852224-693496d0-b674-11e7-8e01-e5c277125053.png)

This behaviour is quite unconsistent, because there is no reason (as far as I understand it) for the system not to display all results starting with "chemin" in my first search.

Is there any explanation for this or is it a bug ?

Thanks in advance.

Best regards,

Charles-Henri

ERPNext: v9.1.7 (master)
Frappe Framework: v9.1.9 (master)

**Comment by rohitwaghchaure** [comment]
Hi @chdecultot 

I have checked on local account and it's working properly, I have created same item codes in my local account.

![pos_items_search](https://user-images.githubusercontent.com/8780500/31880639-c2db2b1e-b7fe-11e7-9b78-e71d4d57bf8d.gif)

**Comment by chdecultot** [comment]
Ok... strange...

I will try to understand where the problem comes from then.

Thanks a lot for your time @rohitwaghchaure !
