### ISSUE TITLE
Title field - Not allowing to set value in the Option field

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#11272]
![imagebaa289](https://user-images.githubusercontent.com/910238/31851797-cc664544-b68a-11e7-99ab-9aaa7643d572.png)

**Comment by shreyashah115** [comment]
User will be allowed to add options for only a set of fields, i.e. 'Read Only', 'HTML' and  'Select', its a condition added to avoid any backend changes to the python controller. As the field Title is a data field, its not allowed.

**Comment by shreyashah115** [comment]
Will add an exception for `title_field`

**Comment by tundebabzy** [comment]
#4369
