### ISSUE TITLE
Error When refresh with language  :Arabic 

### ISSUE THREAD

**Issue by essamacc** [frappe/erpnext#11277]
When I changed the language to Arabic from "My Setting" an error issue in Arabic say that review your server logs.

**Comment by tundebabzy** [comment]
@essamacc 
Open your browser's console. When that message appears, there will be a traceback in the browser console. Please post the traceback here

**Comment by ahmadRagheb** [comment]
what version do you have ?

**Comment by jaichavan** [comment]
Hello, @essamacc this issue has been addressed and resolved in new version
ERPNext: v11.0.3-beta.34 () (staging)
Frappe Framework: v11.0.3-beta.48 () (staging)

I changed language from "en" to "ar" (Arabic) in System Settings. Attaching screenshot for your reference:

![image](https://user-images.githubusercontent.com/40264279/51366458-a8143e80-1b0b-11e9-9bcd-ed184749c639.png)

Hope this _helps_.
