### ISSUE TITLE
V9 Offline POS Issues - Allow User to Delete

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#11286]
Hi 

When the 'Allow User to Delete' option is checked in the POS Profile, the user still cannot delete Draft transactions from the customer queue

Please fix asap

Thanks

**Comment by umairsy** [comment]
Does role assigned to the user includes Delete permission applied on the Sales INvoice?

**Comment by Olawale1** [comment]
Hi @umairsy 

Trust you're doing great. Yes, the user has Delete permission on Sales Invoice

Thanks

**Comment by rohitwaghchaure** [comment]
@Olawale1 
It's working properly, seems wrong pos profile is loaded. Can you please check pos profile is coming properly
![delete_pos](https://user-images.githubusercontent.com/8780500/31908489-ac44173e-b854-11e7-89af-9ff134b07cef.gif)

**Comment by Olawale1** [comment]
Hi @rohitwaghchaure 

Thanks for your response. The POS Profile is loading correctly but here's what I discovered:

1. There are 2 companies setup on the system
2. The issues appear to be somehow linked to the permission for Company
3. Setting User Permission for Company (in User Permission Manager) seems to have resolved the issues

Why doesn't Company setting in POS Profile take care of this?

Thanks

**Comment by rohitwaghchaure** [comment]
Hi @Olawale1 
System pulls the default company form the global defaults, we need to give provision to user to change the company from the POS. We'll add this feature in next version
Thanks
