### ISSUE TITLE
V9 Offline POS Issues - Wrong Stock Qty

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#11288]
Hi,

The 'Stock Qty' in POS is supposed to show available balance of items in the Warehouse specified in the user's POS Profile. This worked perfectly in V8. Now the Stock Qty only shows balance in the Default Warehouse in Item Master. This is very wrong and is causing issues for POS Users in different locations

Please fix asap

Thanks

**Comment by Olawale1** [comment]
Please note the following:

1. There are 2 companies setup on the system
2. The issues appear to be somehow linked to the permission for Company
3. Setting User Permission for Company (in User Permission Manager) seems to have resolved the issues

Why doesn't Company setting in POS Profile take care of this?

Thanks

**Comment by rohitwaghchaure** [comment]
System pulls the default company form the global defaults, we need to give provision to user to change the company from the POS. We'll add this feature in next version
