### ISSUE TITLE
to edit quotation ‘Valid till’ field to 10 days rather than the default(one month)

### ISSUE THREAD

**Issue by psw1209** [frappe/erpnext#11299]
Anyone can help me on how to edit quotation ‘Valid till’ field to 10 days rather than the default(one month).

Thanks

**Comment by joolsr** [comment]
On the Quotation form you can select the date for each quote that you want it to be valid for. I'm not sure how you can edit the default which is one month as you say

**Comment by kennethsequeira** [comment]
![image](https://user-images.githubusercontent.com/33246109/79049873-c64fe800-7c43-11ea-801b-44ec6b52c4f2.png)

Setting added in Selling Settings from Version 11.
