### ISSUE TITLE
Error in saving Patients Appointment

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#11296]
When creating patients appointments, save button is not shown. It's not intuitive that Appointment is created on Book action.

Following is the error when I book the appointment.

![screen shot 2017-10-24 at 11 31 57 am](https://user-images.githubusercontent.com/910238/31926883-02b7f0c2-b8af-11e7-98f3-46318a5e608b.png)

**Comment by umairsy** [comment]
Also getting the issue when creating Consultant against the Patient appointment.

![screen shot 2017-10-24 at 12 04 50 pm](https://user-images.githubusercontent.com/910238/31927895-a1d649d4-b8b3-11e7-9868-fcb2e0fa1235.png)

I created a Sales Invoice from Patient Appointment master but then canceled and amended in it. Neither in the original or amended sales invoice found link with the Patient Appointment or Consultation Doctype.

**Comment by tundebabzy** [comment]
#11080 if merged might help with some of these issues
