### ISSUE TITLE
Markup Column / Field Needed

### ISSUE THREAD

**Issue by nasirshah67** [frappe/erpnext#11300]
Dear Team
Kindly create a column/field named as MARKUP in quotation. User will enter markup value that will be on items sale.

![markup column](https://user-images.githubusercontent.com/32841502/31929089-3176019e-b8a3-11e7-8657-42e649454afc.jpg)

![markup field](https://user-images.githubusercontent.com/32841502/31929101-3afc86b6-b8a3-11e7-9f03-131b39c3e3f8.jpg)

This customization can be created like discount section or a column can be inserted in item table while feeding item rate.

Thank You

**Comment by nasirshah67** [comment]
Dear Team

Please provide feedback for request.

Thank You

**Comment by umairsy** [comment]
There is already a feature of applying Margin on the price list rate of an item. It should be suffice to address the Markup feature's requirement.
