### ISSUE TITLE
Partial Delivery Note Facility 

### ISSUE THREAD

**Issue by nasirshah67** [frappe/erpnext#11303]
Dear Team
Create facility to edit the quantity in delivery note.  If the item quantity in delivery note is less than the ordered quantity then delivery note will be a partial delivery. 

Need this facility if the ordered quantity is large & customer is asking delivery for the items that finished out of the agreed quantity. No new delivery note can be created if the partial delivery notes quantity is already equal to ordered quantity of the same sales order. 

For example ordered quantity is 100 items while only 30 items are ready, so delivery will be made for 30 items out of 100, when other 70 items are ready then 2nd delivery will be made. Now if user try to create 3rd delivery note from the same sales order, system must not allow.

Thank You

**Comment by umairsy** [comment]
Hi,

This features is already available in ERPNext, probably from very first version. You can very much edit qty in the Delivery Note for partial shipment. Also, on next delivery note, only pending qty to be despatched will be updated.

If you need further support on this feature, please post your query on the community forum.

https://discuss.erpnext.com
