### ISSUE TITLE
Permission Error when saving Consultation

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#11301]
![save-issue](https://user-images.githubusercontent.com/910238/31929179-8e8ab518-b8b8-11e7-85e0-66d283e6f96f.gif)

**Comment by rkurungadam** [comment]
Hi @umairsy  
Submitting consultation is only allowed to the user related to physician. Can you please try this after selecting the user in Physician document.
Thanks

**Comment by netchampfaris** [comment]
@rkurungadam Do you think we should not have such restriction. Any Physician should be able to submit consultations.

**Comment by rkurungadam** [comment]
We kept the validation so that a physician cannot submit another physicians consutation, though editting is possible. Documents changes are tracked now, so removing this is also fine.

**Comment by netchampfaris** [comment]
Also, the Patient Appointment is Saved and Submitted in one go. We should let the Physician edit it and submit it at later time.

**Comment by rkurungadam** [comment]
Patient Appointment is not submittable doctype its only saved, may be fields are readonly. We can allow edits, also validation are missing for Appointments. Will update soon..

**Comment by umairsy** [comment]
Also, one of the Customer reported the issue that, once Consultation is created, Patient Appointment status is updated as closed.

![image533028](https://user-images.githubusercontent.com/910238/32099840-9dfc2c38-bb2f-11e7-8020-427d4bd9ae85.png)

If I try to modify the Appointment (date, additional notes, etc) I cannot see the "Save" button.  Also the status shown is incorrect, It always shows "Not saved".

![image6d2ccf](https://user-images.githubusercontent.com/910238/32099833-9b48a976-bb2f-11e7-979b-599594fbf306.png)

**Comment by rkurungadam** [comment]
So they want to close Appoinments manually?
not sure why its showing not saved, also I am getting a bug "field appointment not found in Sales Invoice".

**Comment by rkurungadam** [comment]
So lets remove validation in consultation, there is a custom field added for healthcare domain in Sales invoice causing the bug, not sure if this is needed as Appoinment has referance to Sales Invoice. also Physician and Patient referance from Invoice would be helpful see #11373

**Comment by netchampfaris** [comment]
@rkurungadam Any progress?

**Comment by rkurungadam** [comment]
@pjamsheer will update soon.

**Comment by umairsy** [comment]
Hi Guys,

We need to fast-track resolution for this issue. It has been open for quite a long time now. Let's identify the todos and assign it.

**Comment by manassolanki** [comment]
Any further update on this.

**Comment by umairsy** [comment]
@rkurungadam as discussed internally, it will be best to remove the check of Physician - User link. Let the permission for the Physician also controlled based on standard permissions feature on a Consultant Doctype. If needed, they can also customize it from Role Permissions manager.
