### ISSUE TITLE
Country chart of account not installed after the setup wizard

### ISSUE THREAD

**Issue by chdecultot** [frappe/erpnext#11304]
Hi,

I have just retested the issue described in the following thread and there is indeed a bug:
https://discuss.erpnext.com/t/default-chart-of-account-is-set-instead-of-country-chart-of-account/29523

When following the setup wizard, the chart of account for the country is correctly selected in the wizard (hidden field), but then it seems it is not passed as an argument in setup-wizard.py and therefore not installed after the first install:
![image](https://user-images.githubusercontent.com/4903591/31928998-7629e5de-b89a-11e7-8f33-9a6739301332.png)

In setup-wizard.py, the data is not passed: 
![image](https://user-images.githubusercontent.com/4903591/31928832-e26f04dc-b899-11e7-96c3-1f23648e92a7.png)

If it is not hidden, the country specific chart of account is correctly passed as an argument and correctly installed:
![image](https://user-images.githubusercontent.com/4903591/31929064-b6048aba-b89a-11e7-8ca4-6164e076c40d.png)

![image](https://user-images.githubusercontent.com/4903591/31929629-0ee571d8-b89d-11e7-9a73-028711a991ed.png)

**Comment by pratu16x7** [comment]
Looks like this is no longer an issue: (tested on France - Plan Comptable Général)
<img width="701" alt="screen shot 2017-12-12 at 12 57 45 pm" src="https://user-images.githubusercontent.com/5196925/33872260-218b4004-df3c-11e7-9e1f-39f0994ba946.png">
