### ISSUE TITLE
Workflow change: Amending a document increments the number of the old document, new one retains original number

### ISSUE THREAD

**Issue by Dbonejones** [frappe/erpnext#11318]
ERPNext should work like this for amending a document:

- there is a dedicated field for document versions, that increments, as well as the naming series
- When you cancel and amend a document, ERPNExt increments that field AND adds that number to the OLD DOCUMENT.
- the new amended document retains the original naming series number and links should point to it automatically.

Example:
An original document is created, SO-1234. The document automatically also has a new "version" field with the value 1 (hidden if preferred, but it should be on print formats).
Other documents are created that reference SO-1234.
The document is then cancelled and amended. The old document is changed to SO-1234-1. The new document is SO-1234, and in the version field, 2. Links continue to reference SO-1234.

https://discuss.erpnext.com/t/drafts-and-submitting/18488
https://discuss.erpnext.com/t/amended-document/9533
https://discuss.erpnext.com/t/how-to-amend-a-document-without-having-to-amend-all-downstream-docs/4519

**Comment by kennethsequeira** [comment]
This has been added in v14/develop.
