### ISSUE TITLE
Money in Words utility displays wrong currency when dealing with non-default currencies

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#11324]
Let's assume Default (Base) currency is INR

**Expected Behaviour**

When applied to a currency field with value of $1000, display "USD One Thousand only"

**Actual Behaviour**

Instead of the above, it displays "INR One Thousand only" which is very wrong!

**Steps to reproduce:**

Apply money_in_words utility to any currency field that is not in default currency

Please help fix

Kind regards,

**Comment by Olawale1** [comment]
Hi @tundebabzy

Trust you had a great weekend. Any update here? Have you been able to identify the issue?

Cheers!

**Comment by tundebabzy** [comment]
Oh! I didn't realise you cross posted this issue. I replied on the issue on Frappe. That issue belongs there. Please, let's continue the discussion there.

**Comment by Olawale1** [comment]
I thought so too though I was advised at a point to post it here. Will continue on the other thread as suggested

Thanks
