### ISSUE TITLE
sometime same Invoice ID appear twice in payment entry

### ISSUE THREAD

**Issue by tun-tun-aung** [frappe/erpnext#11320]
![sometime same invoice appear twice in payment entry](https://user-images.githubusercontent.com/32463398/31970059-ceee167a-b93c-11e7-80fd-3d8d850672b5.jpg)

**Comment by tundebabzy** [comment]
I can confirm this. Not desirable at the same time not harmful

**Comment by rohitwaghchaure** [comment]
Issue is not replicating on local account, @tun-tun-aung are you still facing this issue?

**Comment by tun-tun-aung** [comment]
Hi Rohitwaghchaure,

I think that issued was solved, never come up.

-----------
Best Regards,
Tun  Tun  Aung
M:+95-9-5500 976
-----------///------------

  C-22, e-Condo, No.4, Zay North St., Dagon TSP., Yangon, 11191, Myanmar.
          Web  :   www.yd-mm.com     |     Email  :   sales@yd-mm.com
  Tel:    +95 - 9 - 730 42 914 ,     +95 - 1 - 376 180 ,     +95 - 9 - 254
201 769
------------------------------------------------------------------------------------------------

**Comment by tundebabzy** [comment]
I experience it intermittently. When it happens and I refresh the page, it doesn't replicate. Let's close this and reopen if it reoccura
