### ISSUE TITLE
[Feature Request] Allow leave applications to be created for previous allocation periods

### ISSUE THREAD

**Issue by bcornwellmott** [frappe/erpnext#11342]
Currently, once you allocate leave for a future time period, new applications for the previous time period are not allowed. For example: If I give all my employees 10 days of vacation in 2017 at the start of the 2017 year, then give them 10 days in 2018 (mid 2017), they will no longer be able to apply for leave in 2017. The error message indicates that once new leave is allocated, leave for the previous period cannot be applied for.

This is a problem, because it means that new leave allocation has to occur at the start of the period (instead of well before the period). This means that if I have employees that want to book off days in 2018, they are not able to until the start of 2018 (which means their boss doesn't get any notice). Alternatively, if I allocate them their 2018 vacation in the middle of 2017, they aren't allowed to take any more vacation in 2017.

This seems like an awfully complex system with a major flaw, which should be easily addressable.

**Comment by Olawale1** [comment]
+1

**Comment by tundebabzy** [comment]
@bcornwellmott 

It seems like someone fixed this or it wasn't there before. Here are the steps I took to reproduce this:
- Create leave allocation for 1/1/2018 - 31/12/2018
- Approve leave allocation in 2018
- Create leave allocation for 1/1/2017 - 31/12/2017
- Approve leave application in 2017

![screenshot from 2017-11-29 08-11-16](https://user-images.githubusercontent.com/818803/33362667-ce1c0ce0-d4dd-11e7-850a-31b19333eedd.png)

Works as expected. I'm closing this for now but feel free to reopen if I'm missing some steps
