### ISSUE TITLE
New Charts graph has no line / bar legend

### ISSUE THREAD

**Issue by OneiricIT** [frappe/erpnext#11346]
ERPNext: v9.2.1
Frappe: v9.2.1

Latest Chrome version

New Charts do not display legend as to what coloured bar / line represents - example shown below from demo.erpnext.com.

Also note when Accumulated Values selected on last image, see line go sub $0 and run off page.

![image](https://user-images.githubusercontent.com/22227933/32037369-bf98fff2-ba70-11e7-9b76-bb081cc7b437.png)

![image](https://user-images.githubusercontent.com/22227933/32037439-0d174cb6-ba71-11e7-9e1a-76a0db2d9682.png)

**Comment by Olawale1** [comment]
Hi,

It's also important to get some information when the cursor hovers over the chart 

Ability to switch between Line and Bar chart please

Thanks

**Comment by pratu16x7** [comment]
@OneiricIT  Thanks for reporting. We're pushing a fix for this soon.

**Comment by pratu16x7** [comment]
Supported in v1

<img width="913" alt="screen shot 2018-03-12 at 2 33 08 pm" src="https://user-images.githubusercontent.com/5196925/37274378-5dea2292-2602-11e8-8b23-73950939ba64.png">
