### ISSUE TITLE
[Bug] Parent Account can be a child

### ISSUE THREAD

**Issue by bcornwellmott** [frappe/erpnext#11341]
I just had an interesting issue where a large number of my accounts in the Chart of Accounts disappeared. After looking into it, I discovered that our book keeper was modifying the structure of the CoA and had accidentally set the parent of a CoA to one of it's children. Obviously a mistake on her part, but we probably should have a validation to prevent that, because it's not the most obvious mistake to discover once it's happened.

**Comment by tundebabzy** [comment]
Hi @bcornwellmott 
There is validation for such a case. Can you give specifics with which I can use to reproduce the issue?

![screenshot from 2017-10-26 13-08-56](https://user-images.githubusercontent.com/818803/32052136-2b7b5048-ba4f-11e7-907f-524658111105.png)

**Comment by tundebabzy** [comment]
ping!! @bcornwellmott

**Comment by tundebabzy** [comment]
Closing for now. Reopen if needed
