### ISSUE TITLE
Modules Access in user settings will not amend after saving

### ISSUE THREAD

**Issue by Sullson** [frappe/erpnext#11351]
While changing some user settings in Setup > User > someuser I am stuck upon a problem with amending Modules Access. I can change everything no problem, but when I deselect one or more modules in Modules Access and press save, it comes back to selecting all of them.

I am working on development mode bench with supervisor. This happens for every user I create and try to amend.

**Comment by kietmak** [comment]
Same problem with my production and development environment. 
Kindly suggest the solution.
-Ashfaq

**Comment by jaichavan** [comment]
Hello, @Sullson @kietmak does the issue persist?

**Comment by jaichavan** [comment]
Hello, @Sullson @kietmak 
This issue _no longer persists_, as seen:

![GI-module-users](https://user-images.githubusercontent.com/40264279/56470326-8310ce00-6462-11e9-8d28-96c68fac6b04.gif)

**Version details:**

![image](https://user-images.githubusercontent.com/40264279/56470353-d08d3b00-6462-11e9-8b2f-e7228412a792.png)
