### ISSUE TITLE
In Accounts receivable Ledger Credit notes are deducted against the Invoices rather showing in the Customer Outstanding report as a negative value.

### ISSUE THREAD

**Issue by Arundhatii** [frappe/erpnext#11365]
Reported by https://frappe.erpnext.com/desk#Form/Issue/WN-SUP28619
In Accounts receivable Ledger Credit notes are deducted against the Invoices rather showing in the Customer Outstanding report as a negative value.

![screen shot 2017-10-27 at 3 43 24 pm](https://user-images.githubusercontent.com/20164097/32099387-b8004972-bb2d-11e7-8fd6-603940076746.png)

**Comment by manassolanki** [comment]
Not a valid issue.
