### ISSUE TITLE
Deprecate Civil Contracting App and collaborate on Construction Management

### ISSUE THREAD

**Issue by revant** [frappe/erpnext#11362]
https://github.com/revant/civil_contracting

We've stopped using this app since a year.
I don't plan to develop or maintain it further.

### Most used feature in brief

Worker Sheet Doctype.

It has a child table to record
1. Workstation (for type of worker mason, helper, etc.)
2. Worker Name (for outstanding wages)
3. Hourly rate of labour
4. Qty of Hours spent on the site for Worker Sheet's date
5. Total : no. of hours x rate per hour.

- At parent level it calculates total outstanding wages and cash wage paid on that date.
- On submit. Make Journal Entry button is visible.
- On Make JE : It fills up a is_local Journal entry form affecting
outstanding wages and wages (in case of monthly/weekly paid labour)
or Wages and cash (in case of immediate payment)
- User Saves and Submits Journal Entry.

This helps to track attendence and outstanding wages based on attendence.
(Not in ERPNext attendence just a child table on worker sheet)

Labour may or may not be tracked. 

This is not worth going in PR, just for information and exploration checkout the repo.

### "Domain Expertise"

List of things labour + services business may need. (e.g Construction contractors, AC Contractors, Plumbing Contractors, etc)

1. Record of Labour `Employee` already there.
2. Attendance in Hours. 8hrs shift are regular, can be less in case of half day, can also be overtime or even 1 hr only. Somehow leverage Timesheets. _Solution:_ Supervisors can generate timesheets for shift or attended time with a tool? 
3. Labour Rate per hour. leverage timesheet?
4. Attendance is taken for each `Project` (Job/Site) with `Cost Center`. Again leverage timesheet?

Note :
- Labour earns wages and not salary. Different GL Account?
- Labour can be paid advance, cash or paid later.
- Unlike monthly salary, Labour can only interact for one hour and needs to recieve cash payment.
- It is not good practice to do business without keeping track of humans the business interacts with. It doesn't take time to create an Employee record, we can always make it even easier.

### Proposal
Now ERPNext has Timesheets based on projects which may solve the purpose.

Only difference is Adding separate timesheet for each employee is more data entry job for a supervisor who intends to just take attendence, calculate half day or over time. for each project.

Add some functionality/dialog on project to select labour and take attendence in hours.
generate timesheet in backend filling in these hours
Default hours can be set to 8 somewhere

Please share suggestions. @Zlash65 @almeidapaulopt

**Comment by Olawale1** [comment]
Hi @revant

Trust you're doing great. Anything happening on this front?

Kind regards,
