### ISSUE TITLE
Attachment

### ISSUE THREAD

**Issue by HayamMahmoud** [frappe/erpnext#11379]
Hi,
There is no provision for only restrict the Use to delete the Attachment

In case I attached document, and apply User permission on attachment for documents 
User with a read permission on particular document ( can't delete the attachment) 

but when we apply user permission with  a write to another document , he be able to delete any attachment.

We need to prevent any user to delete documents , please advise?

**Comment by umairsy** [comment]
Please followup for this feature via this github issue.

https://github.com/frappe/erpnext/issues/9127
