### ISSUE TITLE
v9 online/offline POS printing and valuation rate issue

### ISSUE THREAD

**Issue by tundebabzy** [frappe/erpnext#11385]
source:frappe/frappe#4404

#### Expected Behaviour
1. POS should not have print button remain after invoice is submitted, print button should be disabled after clicking or new invoice generated after printing, ie, merge print and new button into something like Conclude, so that on print, print window closes and a new invoice is generated. We modified the js file to do this in previous versions and it is a lot faster and safer, reducing risk of multiple printing.
2. Items with zero valuation cannot be sold even though negative stock is selected. negative stock is used by some to allow sales of butchery, confectionery, other packed items like fruits, so purchases are entered for the bulk in expense accounts (taking care of valuation); and sales are posted from zero valuation against income account, allowing you to see expense, income and profit. once negative stock is active, valuation rate should not be compulsory as many shops deal with paper for some supplies and then list the items with their prices and sell, this is something we cant enforce for many reasons, like staff shortage, some shops have 2 people handling over 10000 lines of items!!! please remove the compulsory valuation, also if you set default to 1 in allow zero valuation (so that cashier doesnt need to switch to form view, open item and select - not acceptable, time-wasting, customer will walk away); when we set this in customize form for sales invoice item, it also makes the selling price zero, which is not correct
#### Steps to reproduce:

1. create an item,  no valuation rate, assume bulk purchase like meat, allow negative stock, sell item, item will not sell even though negative stock is allowed

Frappé version: 9
cc: @noetico

**Comment by noetico** [comment]
Update; it seems setting default of 1 stops the valuation rate requirement without affecting selling price, seems it was a browser caching issue. I will update again on this issue.
