### ISSUE TITLE
Serial Number In the Invoice

### ISSUE THREAD

**Issue by mtyspider** [frappe/erpnext#11386]
I have trying to find where do i mark so , if an item has a serial number when issued in a invoice, the serial number is also printed. right now the serial numbers just helps for searching an item ,but when its old the serial number is not printed in the invoice. where do i set that? I found some issues around but that means to mess around with the formats. Which the code doesnt look very similar to tyhe one i have.

**Comment by tundebabzy** [comment]
Hi @mtyspider 
Thanks for using ERPNext. We use github to report bugs and feature requests. Please ask questions on the forum - https://discuss.erpnext.com
