### ISSUE TITLE
How to set an alarm with the lead 

### ISSUE THREAD

**Issue by yousefbakir** [frappe/erpnext#11380]
Hi All,

How to receive a notification to contact the lead on a specific date and time ?

**Comment by umairsy** [comment]
For now, you can set alert on the Next Contact Date field. If you also want to consider time, then please insert date-time field in the Lead and then setup Email Alert based on it.

https://erpnext.org/docs/user/manual/en/setting-up/email/email-alerts

For more support on ERPNext, please post your queries on the discuss forum.

https://discuss.erpnext.com
