### ISSUE TITLE
SubTotal in Taxes and Charges Template

### ISSUE THREAD

**Issue by vorasmit** [frappe/erpnext#11396]
Since this template is for taxes and charges, subtotal may be regularly required for users using this template for both taxes and charges.

Also it may be required in reports, so as to give statutory details. ( eg- GSTR in India )

**Current Scenario :** 
Download report -> Add new column for Subtotal -> Add  Fields to get sub-total -> File returns.

**Problems faced in current scenario:**
Declaring same in invoice is not possible currently.
No standard report and manual intervention can lead to error.

**Possible solution:**
Taxes and charges template can be modified in following manner:
- Add charge_type as subtotal (current options - actual, on net total etc. ) - which gives subtotal upto that row.
- This can be added anywhere and any no. of times by user. Making it a standard practice and solving problem.

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.
