### ISSUE TITLE
To Do

### ISSUE THREAD

**Issue by HayamMahmoud** [frappe/erpnext#11394]
Hello,

Please how to make the “Assigned By” in the To Do default value is the “To Do Owner” ?
And how to make the “Allocated to” field default value is blank ?

In case I don’t want the user to close the one that I assign to him, In other meaning I want the one who open the Todo to be the only one that can close it

**Comment by tundebabzy** [comment]
Hi @HayamMahmoud 
Thanks for using ERPNext. Please open a new thread for this on out forum - https://discuss.erpnext.com as we use github for bug reporting and feature requests
