### ISSUE TITLE
Add Stock in store and Stock in warehouse in Sales Order 

### ISSUE THREAD

**Issue by lifestylesofas** [frappe/erpnext#11405]
HI, 

I want that while creating sales order, i should see whats is there in store in one column and warehouse stock in one column. IN this way its easy for users to make sales orders and the moment we make sales invoice the stock should reduced either from store if its there or from warehouse stock.

**Comment by lifestylesofas** [comment]
waiting for reply

**Comment by Arundhatii** [comment]
As discussed, this may require client side scripting, request you to please post this on the community forum. 
Please find the link for
