### ISSUE TITLE
Unable to view Item Image in Stock Entry Print Format

### ISSUE THREAD

**Issue by addymuliady** [frappe/erpnext#11412]
Hi,

ERPNext: v9.2.2 (master)
ERPNext Shopify: v2.0.14 (master)
Frappe Framework: v9.2.3 (master)

1. Image cannot be viewed in print format of Stock Entry. Somehow, image link to Shopify CDN.
3. Also unable to link image in Item Master to attached image which was uploaded.

https://discuss.erpnext.com/t/items-sync-with-shopify-not-showing-image-on-documents/17256

![image](https://user-images.githubusercontent.com/21187126/32271693-12a95786-bf36-11e7-8c59-2c554498b45f.png)

**Comment by netchampfaris** [comment]
Fixed https://github.com/netchampfaris/frappe/commit/49b63d76802dfc82b5b272d9954c46f733829a56
