### ISSUE TITLE
Video clips in Docs

### ISSUE THREAD

**Issue by lm-dg** [frappe/erpnext#11421]
Thank you very much for video clips provided to help new users(newbies) like me!

The only suggestion I would like to make is to play them on-demand.
Example of on-demand manual page is located at
https://erpnext.org/docs/user/manual/en/customize-erpnext/articles/making-custom-reports-in-erpnext
Example of perpetual manual page is located at
https://erpnext.org/docs/user/manual/en/customize-erpnext/kanban-board

**Comment by chdecultot** [comment]
Hi @lm-dg,

The difference between the two is that the first example is a Youtube video, whereas the second one is a GIF.
I don't think you can play GIFs on demand as you suggest.

What is the problem with GIFs exactly ?

**Comment by lm-dg** [comment]
Thank you for the message Charles-Henri,

The issue is that new users may find it difficult to read couple of lines
of text between 2 playing GIFs.
Also, new users may not be as fast to follow GIFs, but have no chance to
pause where they wish to pause.

regards,
