### ISSUE TITLE
Multiple Tables in Report Builder

### ISSUE THREAD

**Issue by Mohd200** [frappe/erpnext#11425]
Good Day Everyone.

I am facing an issue with the Report Builder of a certain Custom DocType.
This Custom DocType has multiple Child Tables, and I put them in the Report. But they don’t appear as if they were separate, they appear as if they were connected somehow.
The last table I placed on the (Pick Columns) list act as it were the child table of the previous child table on the (Pick Columns) list.

![capture](https://user-images.githubusercontent.com/32062135/32322316-2dc4162e-bfd5-11e7-8256-521a7d68f40d.PNG)

The Highlighted text is the original data on the child tables. and the text that are not, is repeated.
The second (Full Name) on the picture is the last table on the (Pick Columns) list as mentioned above.

![1](https://user-images.githubusercontent.com/32062135/32322309-26dbe17a-bfd5-11e7-91ee-a61d40b845d6.PNG)

This only to show you that even if you change positions, it is still the same condition.

![2](https://user-images.githubusercontent.com/32062135/32322305-2064a94e-bfd5-11e7-99d3-b379120c24b5.PNG)

In this picture, I added one more child table of the DocType into the Report.
As shown in the picture, the first child table has only 2 Rows, the second table only has 1 Row, and the third table has 4 Rows.
My objective is to make every child table “independent” so to speak, and to not get any repeated data.
If anyone could help me with my Problem in any way, I would be appreciative.

Thank You :smile:

**Comment by netchampfaris** [comment]
Showing independent Child Tables in ReportView is tricky. Please check the new Report which is merged into develop, and provide feedback.

**Comment by Mohd200** [comment]
Dear @netchampfaris 
Have you Fixed the Issue?

**Comment by raghavendradl1998** [comment]
Hello everyone 

how can i show data in  single row

![Employee](https://user-images.githubusercontent.com/75833108/153168346-a8ba1dde-4930-420c-bf8d-01a8c5ee74ef.jpeg)

i'm appending the child table data with parent table data
