### ISSUE TITLE
Scrap item is not added if backflush setup is: Material transferred for manufacture

### ISSUE THREAD

**Issue by Dadodadolontong** [frappe/erpnext#11439]
Hi,

When the manufacturing backflush setup is Material transferred for manufacture, the scarp item is not added to the list.

https://github.com/frappe/erpnext/blob/76ce074c63ea38025d2021300f46b6e6800f5e73/erpnext/stock/doctype/stock_entry/stock_entry.py#L549

**Comment by umairsy** [comment]
Scrap items are added in the Manufacture Entry, as it is one of the outcome after the completion of the production process. The transfer entry will only have raw-material items.

For more support, please post your queries on https://discuss.erpnext.com
