### ISSUE TITLE
PO numbers are not matching  

### ISSUE THREAD

**Issue by PriyankShah79** [frappe/erpnext#11444]
In my account, I have made 1Po no is:- PO-00035
and next number should be:-PO-00036?
But when I am trying to create new PO the number of new Po is showing directly:-PO-00037.

**Comment by vishdha** [comment]
Update Naming Series
Step to follow
1. Search Naming Series in the search bar.
2.Select  [Select Transaction] >> Purchase Order
3.Under Update Series Section select [prefix] >> PO -
4. Change Current Value to 35 and update

**Comment by PriyankShah79** [comment]
I am not getting Update series section where is it?

**Comment by umairsy** [comment]
Please check if PO #36 is in the cancelled stage. Here is the help on Naming Series and current value updation.

https://www.youtube.com/watch?v=IGyISSfI1qU

https://erpnext.org/docs/user/manual/en/setting-up/articles/naming-series-current-value

For functional support, please post your queries on https://discuss.erpnext.com
