### ISSUE TITLE
[Feature Request] Improvements for ERPNext and Frappé Blogs

### ISSUE THREAD

**Issue by kennethsequeira** [frappe/erpnext#11442]
Currently, the ERPNext Blog page is missing key features of a usual blog. I suppose the addition of these features will improve the overall user experience for the readers.

1. Share button.
2. Meta description of blog/article for search engines as well as Social Media sites.
3. Keywords. 
4. Search bar.
5. Preview feature for the authors.

These will not only be beneficial for the readers but will also improve the visibility of the blogs with search engines.

**Comment by giuseppelamatrice** [comment]
Is useful to SEO add on <head> of webpage this:
- [ ] <meta name="description"  content="something" /> 
- [ ] <meta name="keywords" content="something" />

**Comment by achillesrasquinha** [comment]
Hi @kennethsequeira, did you check that the blog feature has these settings already? For the ones that do, have it ticked.

**Comment by kennethsequeira** [comment]
@achillesrasquinha these are the only blog settings available and I doubt they are of any help in the context of the issue 
![screenshot from 2017-11-14 20-07-46](https://user-images.githubusercontent.com/33246109/32785449-94b23e78-c977-11e7-825e-de42f65472c7.png)

Honestly, the blog module can benefit a lot from a [Yoast SEO](https://wordpress.org/plugins/wordpress-seo/) like plugin. 

There can be a lot of features taken from Wordpress. Not just the *Blog*, but even the *Website* module can benefit a lot from these features.

**Comment by kennethsequeira** [comment]
@achillesrasquinha need a YOAST like plugin which can create Meta tags and Open Graphs individually for the Blog pages at least.

@netchampfaris we could use some functionalities specified from here as well #11545

**Comment by robertbecht** [comment]
Thanks, @saurabh6790 for pointing me to this site.

Most of the issues are mentioned earlier in this thread...
Missing and deserving attention is the SiteMap file (xml)....It contains a lot of noise...
there are two obvious options:   allow the upload of a sitemap (eg created with an specialized website/software) or (better I believe) more control of the user how the sitemap is created and the option to give a relative ranking (0 to 1) to indicate importance

**Comment by kennethsequeira** [comment]
https://github.com/frappe/frappe/pull/4948
