### ISSUE TITLE
bench update didn't recognize translated field

### ISSUE THREAD

**Issue by hokgt** [frappe/erpnext#11448]
When I update 9.1.* to 9.2.4, error occurred while updating with below message: 

"frappe.exceptions.LinkValidationError: Could not find Parent Item Group: All Item Groups" 

then I dug to the db, I found out that "All Item Groups" field name has been translated to Indonesian language (not English) and bench update didn't recognize the translation. Although can be fixed with updating new record the bench can recognize, bench itself should anticipate the translation. 

Please refer to this link for more detail : 
https://discuss.erpnext.com/t/could-not-find-default-item-group-products/29951

**Comment by tundebabzy** [comment]
@hokgt Which of the patches threw the error?

**Comment by hokgt** [comment]
Hi @tundebabzy, sorry I don't get what you mean by patches. Do you mean the which part of the code showing error? If it is then below was the error I got:

frappe.exceptions.LinkValidationError: Could not find Parent Item Group: All Item Groups.

Sorry if I mistaken your question, I'm new to ERPNext and still learning.

**Comment by tundebabzy** [comment]
While running bench update, you will see the patches that are being executed with some text like "executing erpnext.patches.v9.some_patch_name". If you

**Comment by nabinhait** [comment]
@hokgt Is this still a valid issue? If yes, please reopen the issue, closing it for now.

**Comment by hokgt** [comment]
I can't try it again because I replace old instance with fresh install instance but bench update with fresh install no problem
