### ISSUE TITLE
[Feature Request] Discussion board to get quick response from employees

### ISSUE THREAD

**Issue by 900cut** [frappe/erpnext#11457]
Hello everyone. To use ERPN more succesfully we’d like to have discussion board functionality.
The functionality significantly reduces time needed to create policy, solve a problem. It increases teamwork in the company.
For example:
1. We inform our employees about new policy or just piece of news that effects a lot of them. The discussion board is a place there we can fastly collect all questions and issues and answer them in the same topic or collect them and publish Q&A document that covers them;
2. If a problem discovered but it isn’t clear where all factors that create it and the discover doesn’t even know all participants that acts the way that creates the problem. We can publish the topic in a management board and find who creates, why creates, how to change business process that avoid the problem and all interested parties won’t suffer the solving problem way;
3. If we work out a policy, product description or instruction when with functionality of a discussion board we can on a very initial stage fastly collect all comments and suggestions. And then the document can be workflowed to get prove by management;
4. We’d like to have that functionality for our employee to post any suggestion, open issue, any question to the management - to be more open and solve concerns.

Hope we get good traction for the suggestion and we will have that function in ERPN. Thank you!

**Comment by vlad-um** [comment]
A useful service for problematization and discussions.

**Comment by joolsr** [comment]
A good idea, but would you be better off using something mature and fully featured such as [Discuss](https://www.discourse.org/) instead? To build such a tool would take a long time. To build something somewhat simpler with fewer features much quicker in my opinion
