### ISSUE TITLE
Possible Critical bugs on ERPNext V9 Online POS 

### ISSUE THREAD

**Issue by noetico** [frappe/erpnext#11453]
1. **Automatic Submission:** Cashier is scanning items and suddenly the screen freezes for say 5 seconds and when it returns the sale is SUBMITTED automatically, **no tender screen, no submit confirmation!** This means remaining items have to be done on a new invoice. 
2. Many times, at random, the + and - signs to increase quantity do not work and quantity doesn't change, using the text box to set the quantity also doesn't work, this occurs especially when there are more than 5 items in the grid, setting an item to zero does not delete it, the pos page needs to be reloaded to make progress, essentially; she restarts scanning customer’s items, serious issue!
3. The total for scanned items may not update on adding or removing items, page needs to be reloaded. Removing an item may not trigger the cart total to recalculate
4. POS may add the same item multiple times, as unique line items. essentially its erratic sometimes

**Comment by jay-parikh** [comment]
+1

**Comment by noetico** [comment]
Just an update, I have an invoice which was mailed in with the strangest thing I have seen; highly embarrassing for me, a basic pos operation and the v9 pos fails so frequently at it.
[SINV-203165.pdf](https://github.com/frappe/erpnext/files/1447669/SINV-203165.pdf)

**Comment by Olawale1** [comment]
Hi @noetico

Trust you're doing great. Just by looking at the pdf I'm guessing you're referring to the repeated line item but it would help if you highlighted the specific issue(s) with the invoice. Not sure I'm getting that from your post

Cheers!

**Comment by noetico** [comment]
The issue is; one item can be entered twice in different lines. If you enter an item more than once, you should see as qty of 2 on the invoice. Meanwhile this was entered once. Regardless of what causes this; its clearly a problem and there are many complains. I will be at the store today to check things out and revert here.

Sent from my BlackBerry 10 smartphone.
From: Olawale1
Sent: Tuesday, November 7, 2017 10:11
To: frappe/erpnext
Reply To: frappe/erpnext
Cc: Kent; Mention
Subject: Re: [frappe/erpnext] Possible Critical bugs on ERPNext V9 Online POS (#11453)



Hi @noetico<https://github.com/noetico>

Trust you're doing great. Just by looking at the pdf I'm guessing you're referring to the repeated line item but it would help if you highlighted the specific issue(s) with the invoice. Not sure I'm getting that from your post

Cheers!

**Comment by noetico** [comment]
** I updated it within the issues. Item 4**

**Comment by rohitwaghchaure** [comment]
@noetico 
We have recently fixed issues related to online POS, can you please pull the latest code and check
Thanks

**Comment by noetico** [comment]
Thanks so much Sir. Thanks.

Sent from my BlackBerry 10 smartphone.
From: rohitwaghchaure
Sent: Thursday, November 9, 2017 09:58
To: frappe/erpnext
Reply To: frappe/erpnext
Cc: Kent; Mention
Subject: Re: [frappe/erpnext] Possible Critical bugs on ERPNext V9 Online POS (#11453)



@noetico<https://github.com/noetico>
We have recently fixed issues related to online POS, can you please pull the latest code and check
Thanks

**Comment by noetico** [comment]
Hello @rohitwaghchaure thanks again, I just tried to update and I have this error:

...
doc.pos_profile_name = doc.user + ' - ' + doc.company
TypeError: unsupported operand type(s) for +: 'NoneType' and 'unicode'

What do I need to update to allow these operands work?

**Comment by noetico** [comment]
Ok Sir, some update @rohitwaghchaure The search is still entering items quickly while the user is still trying to type... check it, its matching item name like item code, so searching is a problem (pics attached). 

I'm trying to type 'sample' to test the search, on entering s, the item jumps into the cart, on typing faster 'sa' it jumps in, I went faster and intentionally added a wrong text like 'samo' rightly it said no data, but attempting to correct, taking off the o, instantly puts in the item again, you understand Sir, the search I think should allow the user hit enter, populate the item grid with results then the user selects, for scanning, since the scanner puts a new line (enter); that should select and enter the unique item that matches the barcode or no data if none (as usual scanning should instantly enter the only matching item with the scanned barcode).

![screen shot 2017-11-09 at 11 26 53 am](https://user-images.githubusercontent.com/15412145/32601164-103793e8-c542-11e7-8a98-b6fd86957a7d.png)
![screen shot 2017-11-09 at 11 27 04 am](https://user-images.githubusercontent.com/15412145/32601186-1d0b353e-c542-11e7-9d04-7cfa1fbdd350.png)

![screen shot 2017-11-09 at 11 27 26 am](https://user-images.githubusercontent.com/15412145/32601254-4b380e5a-c542-11e7-88de-a53badce9f37.png)

**Comment by Fredoluka** [comment]
@noetico i updated some minutes ago and i hard same problem you narrated above,how do you revert back to the your former status pending the resolution of the ' unsupported operand type(s) for +: 'NoneType' and 'unicode'' problem.

**Comment by noetico** [comment]
Hello Fred;

Have you got an error?

What I did was skip that pos_profile patch and then did bench migrate. ‎If you don't know where the patches are; check apps/erpnext/erpnext/patches.txt, that should be 2nd to last line, about that. Add a # so you can progress with bench migrate

Sent from my BlackBerry 10 smartphone.
‎

**Comment by noetico** [comment]
I don't know if it's a crucial patch; it doesn't appear to be, but will be good to have ‎a solution soon so we can apply it.

Sent from my BlackBerry 10 smartphone.
From: Fred Oluka
Sent: Thursday, November 9, 2017 12:47
To: frappe/erpnext
Reply To: frappe/erpnext
Cc: Kent; Mention
Subject: Re: [frappe/erpnext] Possible Critical bugs on ERPNext V9 Online POS (#11453)



@noetico<https://github.com/noetico> i updated some minutes ago and i hard same problem you narrated above,how do you revert back to the your former status pending the resolution of the ' unsupported operand type(s) for +: 'NoneType' and 'unicode'' problem.

**Comment by noetico** [comment]
@rohitwaghchaure  Please note this behavior described above is exactly how v6 pos behaves **and its perfect** so I think we may just look at how to improve on that pattern for this version

**Comment by rohitwaghchaure** [comment]
@noetico @Fredoluka 

Regarding patch, I have fixed the [issue](https://github.com/frappe/erpnext/pull/11501) and soon we'll release it.

@noetico Regarding search issue we'll discuss separately in [thread](https://github.com/frappe/erpnext/issues/11502)

**Comment by Olawale1** [comment]
Thanks @rohitwaghchaure 

Cheers!

**Comment by noetico** [comment]
Thanks Rohit! We'll be looking forward. I will also be checking the thread so we can discuss the search, when you're free and available.


Sent from my BlackBerry 10 smartphone.
From: rohitwaghchaure
Sent: Friday, November 10, 2017 08:21
To: frappe/erpnext
Reply To: frappe/erpnext
Cc: Kent; Mention
Subject: Re: [frappe/erpnext] Possible Critical bugs on ERPNext V9 Online POS (#11453)



@noetico<https://github.com/noetico> @Fredoluka<https://github.com/fredoluka>

Regarding patch, I have fixed the issue<https://github.com/frappe/erpnext/pull/11501> and soon we'll release it.

@noetico<https://github.com/noetico> Regarding search issue we'll discuss separately in thread<https://github.com/frappe/erpnext/issues/11502>

**Comment by noetico** [comment]
The troubled client has been upgraded, many years thanks @rohitwaghchaure and the rest of the team.

**Comment by rohitwaghchaure** [comment]
Closing this issue, feel free to reopen if issue persists
