### ISSUE TITLE
bench export-fixtures create unwanted file

### ISSUE THREAD

**Issue by hiousi** [frappe/erpnext#11456]
using `bench export-fixtures` create a erpnext/fixtures/web_form.json file
This file is not in the erpnext official repo, the result is that `bench update` can not work and requires to do a `bench update --reset`

**Comment by joezsweet** [comment]
Hi there, 

comment out:

https://github.com/frappe/erpnext/blob/f15a8409eb232171ec490069bfb94ba123a398af/erpnext/hooks.py#L54

**Comment by hiousi** [comment]
changing erpnext/erpnext/hooks.py by commenting the line you suggest will produce exactly the same result. Bench update will not work without --reset

Sorry, @joezsweet but your suggestion does not resolve the issue.

**Comment by hiousi** [comment]
@kennethsequeira  please re-open

**Comment by joezsweet** [comment]
Ok do this from bench folder:

```
rm -rf apps/erpnext/erpnext/fixtures/* 
bench update
```

**Comment by hiousi** [comment]
@joezsweet sure, but the file will be recreated next time you use export-fixtures.

one way is to remove fixtures = ["Web Form"]  in hooks.py 
OR
add a parameter to bench  export-fixtures to export for only certain apps (eg living erpnext fixtures un-exported)

I can submit a PR but, the question is, why this line  is here???

**Comment by joezsweet** [comment]
Feel free to send a PR

**Comment by hiousi** [comment]
https://github.com/frappe/erpnext/pull/11612

**Comment by kennethsequeira** [comment]
@hiousi I suppose the issue can be closed now right?
