### ISSUE TITLE
Missing invoices

### ISSUE THREAD

**Issue by jeremyw111** [frappe/erpnext#11455]
I did an assembly on an item only to notice I had more inventory than I was supposed to.  So I looked back and the invoice and delivery for that item previously was completely missing...

**Comment by joezsweet** [comment]
and?

**Comment by jeremyw111** [comment]
That's it, how do previous transactions just disappear?  They don't show up as deleted or anything.

**Comment by joezsweet** [comment]
Well, what to say? ..for some reason seems transaction are not saved ..did u check logs?

**Comment by jeremyw111** [comment]
I did check logs.  I know that at the time it was saved for sure, but all history of at lest 2 different  transactions just completely disappeared

**Comment by joezsweet** [comment]
could u create another erpnext installation and recover from backup? ..so you can investigate ..

**Comment by umairsy** [comment]
Please provide exact steps indicating transactions created in the ERPNext.

Did you create Items?

How were the assembly created? Did you create BOM or Production Order?

Did you create Sales Invoice or Delivery Note for the Items?

Also check Tools > Activity logs for the detailed log of posting made in your ERPNext account.

Request you to get support on this query over community forum. If it is validated as a bug or feature request, then only it should be posted as a Github Issue.

https://discuss.erpnext.com

**Comment by jeremyw111** [comment]
There are invoices that are completely missing, as though I never made them.  Assemblies aren't the problem as those assembled items are still in the system (which is how I realized these invoices are missing)
