### ISSUE TITLE
Manufacturing User role hidden in Distribution domain, hence cannot create Production Orders

### ISSUE THREAD

**Issue by McDizzy** [frappe/erpnext#11458]
Moving live system from erpnext 9.1.2 to 9.2.4 causes an issue. After update, production order creation no longer allowed for any user including admin. Selecting production order no longer shows the "New" button in the interface. I believe the issue is with the DB data set. I created a new instance of 9.2.4 tested that production orders can be created. Then imported my data set...Stopped working. Any ideas on a fix would be appreciated. Until then I will roll back to my 9.1.2 instance for now.

**Comment by netchampfaris** [comment]
@McDizzy This is a valid bug. Relevant [discussion](https://discuss.erpnext.com/t/i-have-no-new-button-in-production-order-and-cannot-create-a-production-order-from-any-attempt/30222)
