### ISSUE TITLE
[BUG] Wrong selection of items on a list

### ISSUE THREAD

**Issue by lowercase00** [frappe/erpnext#11476]
While trying to clean my notifications noticed an error.
When I select all, the delete button disappears, and when I deselect them the delete button reappears.
Screen shots attached.

EDIT:
Just noticed it happens whenever there is this format of list.
And only happens when you select "all", and when you do, the "delete" button does not work.
But when you select one by one it works fine.

![erpnext bug error snaphot 1](https://user-images.githubusercontent.com/21188280/32477521-07cdd0f6-c366-11e7-8854-bd3273779e42.jpeg)
![erpnext bug error snaphot 2](https://user-images.githubusercontent.com/21188280/32477522-0805b462-c366-11e7-8e00-c623b710b9b5.jpeg)

**Comment by joezsweet** [comment]
I guess it is on Safari, Google Chrome works fine. Can you test?

**Comment by umairsy** [comment]
Not replicating in my test account as well. As suggested above, can you please confirm if it is a cross-browser issue?

**Comment by lowercase00** [comment]
Confirmed, only happens in Safari - Chrome works fine for me as well.

**Comment by kennethsequeira** [comment]
Hi, since the issue seems to have been resolved, we are closing this issue.
