### ISSUE TITLE
Student type ahead search on group not working in v9

### ISSUE THREAD

**Issue by jwrober** [frappe/erpnext#11479]
From here - https://discuss.erpnext.com/t/student-type-ahead-search-on-group-not-working-in-v9/29734

In the student group doctype, in the student table, the type ahead search does not work on the name. It does if you know the ID of the student, but not the name. I am using the "student group based on activity" option.

**Comment by manassolanki** [comment]
@jwrober  Thank you for explaining in details 👍 , I have pushed a fix for the same.
