### ISSUE TITLE
[Data Import] Misleading Error Message

### ISSUE THREAD

**Issue by lowercase00** [frappe/erpnext#11474]
Hi,

I just wanted to suggest to be able to see a more assertive error on importing files.
After a few hours getting the error related to **Import Format**, I discovered that the error was in the **Import Content**.

Even though it was my fault, the system made me look for the error in the format of the file (I ended up exporting thousands of .csv encryptions), when in reality it was just a matter of linking fields correctly (content).

Thanks a lot.

**Comment by umairsy** [comment]
Hello,

Can you please be more specific about the change required in the format to make it work? It will help us resolve this issue faster.

**Comment by lowercase00** [comment]
I was uploading the file in the correct format CSV, but I was missing the "Parent Group" info for some lines (as they were already parents) - which is a content issue.

The thing is, the template file also has blank Parent Group information for the lines which are also parents, so the process ends up a bit misleading.

It would be great to have more specific warnings:
Eg:
"Missing 'Parent Group' information for line XX"
"Link not found for 'Company' for line XX"
"You have uploaded a XLSX file, please upload a CSV file"
"CSV file not recognized - make sure it is sepparated by comma ','"

(The last one might sound absurd, but in my country, the number format is "." for thousands and "," for decimals and when you export CSV the columns are separated by ";", so you have to manually replace the items - not very easy to find out as is not that obvious that CSV files depend on number format configuration of the system)

**Comment by Zlash65** [comment]
"Link not found for 'Company' for line XX" - This type of error for link field is already handled.
"You have uploaded a XLSX file, please upload a CSV file" - Uploading through XSLX is valid.
"Missing 'Parent Group' information for line XX" - Can you provide steps to reproduce this..
