### ISSUE TITLE
Can’t login; OTP recovery not available

### ISSUE THREAD

**Issue by bithons** [frappe/erpnext#11478]
After resetting my mobile phone is the Google Authenticator removed. The problem is ERPnext asks for this verification code but I can’t get it anymore.

Resetting the two-step verification is not possible on ERPnext. Adding the ERPnext OTP to Google Authenticator is also not possible because the link I got from mail is expired.

I am not able to login ERPnext, how can I solve this problem, this is a big issue. This can also been seen as a feature request because, what if this happens to other people or again to me? I also want to say that most online services has a recovery option, for example; Microsoft services or Google services.

**Comment by felixvarghese** [comment]
OTP is not enabled on the Administrator Account. Login using Administrator and disable OTP and get your account setup again.

If you are not the administrator, contact your administrator to help.
