### ISSUE TITLE
Exchange rate is grayed and not editable in payment entry...

### ISSUE THREAD

**Issue by Suprazz** [frappe/erpnext#11473]
Something is wrong with the latest update (less than 1 week old). I cannot edit the exchange rate in the payment entry like I used to do when completing a payment entry. I also noticed the issue in the PI.

![image](https://user-images.githubusercontent.com/3640711/32456753-b4dfabd8-c2f4-11e7-8378-868b2a2c8545.png)

**Comment by addymuliady** [comment]
@tundebabzy might be able to advice?

**Comment by deepak727** [comment]
Hi

This is also not editable in sales invoice......

**Comment by tundebabzy** [comment]
A fix for a similar issue was recently released. Please make sure you are on the latest release. Also make sure that "Allow Stale Rates" is checked in Accounts Settings

**Comment by Suprazz** [comment]
I'm on the EPRNext hosted version. Still not able to change this value with the "Allow stale rates" checked.

**Comment by Suprazz** [comment]
Correction: you need to UNCHECK Allow stale rates to have access to the exchange rate settings again.
