### ISSUE TITLE
Gantt chart not working

### ISSUE THREAD

**Issue by KanchanChauhan** [frappe/erpnext#11482]
No colors and no pop-ups if there is custom list view settings.

<img width="665" alt="screen shot 2017-11-08 at 10 09 38 am" src="https://user-images.githubusercontent.com/16913064/32532174-6cbcf43e-c46e-11e7-93cf-e60cd61671bb.png">

<img width="454" alt="screen shot 2017-11-08 at 10 21 24 am" src="https://user-images.githubusercontent.com/16913064/32532193-9a1bd2ba-c46e-11e7-98ec-f1eef3cf5285.png">

**Comment by netchampfaris** [comment]
If either the start date or end date is not set, the bars won't be plotted correctly.

**Comment by KanchanChauhan** [comment]
When start date and end date is set, it does not show at all. :P

**Comment by KanchanChauhan** [comment]
It happens only if there is custom listview settings.

**Comment by netchampfaris** [comment]
Currently custom list_view settings in custom apps will override the default list_view settings. So either we merge the custom settings with the default ones, or we replace them.

**Comment by netchampfaris** [comment]
To modify existing listview_settings you can use the default settings and override them.

```
// custom list view settings

const default_settings = frappe.listview_settings['Task'];

frappe.listview_settings['Task'] = Object.assign(default_settings, {
    fields: default_settings.push('custom_field'),
    filters: [['Task', 'status', '=', 'Overdue']]
})


```

**Comment by netchampfaris** [comment]
If you are replacing the existing `doctype_list.js` file with your own version using hooks, you will have to copy the existing settings and modify it. You also have to maintain it through version upgrades.
