### ISSUE TITLE
[Non-Profit Module] Web Form for Chapter

### ISSUE THREAD

**Issue by revant** [frappe/erpnext#11485]
- Only Members can create a chapter
- Chapter Head unique
- In Web Form, for Chapter head field select user who creates chapter as chapter head
- Chapter not published from web form inputs
- After approval it will be published. (Approver can check publish checkbox)
- No Chapter Members to be added in chapter in Web Form. 
    - Approver can add users during approval.
- Member Users can list self under a chapter. Add `Join Chapter` button on chapter web view
- `Join Chapter` adds the user on the Chapter as Chapter Member
- If member-user is already member of any chapter
    - `Join Chapter` button is NOT visible.
    - Only Leave Chapter button available on Chapter of Member/user 
- Validations : 
     1. Chapter head cannot be member of any chapter.
     2. Member cannot list on multiple chapters.

**Comment by Olawale1** [comment]
Hi @revant 

Thanks for outlining these points. I'm a bit concerned about the validations though. I think both points would be better implemented as options in settings so the System Manager can either restrict a Chapter head from being a member of any Chapter or restrict Members from listing on multiple Chapters or both

I can see lots of use cases for allowing Members to list on multiple chapters; same goes for allowing Chapter heads to be members of Chapters as well. The system has to be as flexible as possible to accommodate different use-cases 

Cheers!

**Comment by revant** [comment]
Agree,
System must be flexible.
If there's a non profit settings page. Add it there.

Or just keep it flexible for first cut if its going to be released soon.

**Comment by vishdha** [comment]
https://github.com/erpnext/foundation/pull/95
