### ISSUE TITLE
Disabled Letter Head fetching in transactions by default

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#11496]
WN-SUP28904 and WN-SUP28979

In the Sales Invoice, Letter Head is set by default.

The Letter Head has been disabled. No default Letter Head has been set in Company. No default or Property Setter created for the Letter Head field as well. Still, default Letter Head is set in the Sales Invoice.

Even if it is set, but in the Print Format, Letter Head is unchecked. However, when check PDF for the invoice, Letter Head is added. If value is removed from the Letter Head field, then it doesn't show-up in the PDF as well.

**Comment by rohitwaghchaure** [comment]
Fixed via https://github.com/frappe/frappe/pull/4484/files
