### ISSUE TITLE
Fee discount for children of employees and siblings

### ISSUE THREAD

**Issue by zefanja** [frappe/erpnext#11497]
We like to use ERPNext as our SIS, but there is one thing we currently don't know how to do in ERPNext.

In our school children of employees get a percentage discount. In addition all parents (including children of employees) can get another percentage discount, if they have 2 or more kids in our school. 

It would be nice, if we can do that in ERPNext. In addition to apply a fee to a student you should be able to apply a discount. 

Example:
First child of an employee. In the Fee module I select the correct fee structure and after that I can apply a discount from a list, say "Employee First Child".

**Comment by umairsy** [comment]
Hello,

You can create new Student Category and apply it for the related students. For these students, you can create separate Fee Structure based on the discounts.

https://www.youtube.com/watch?v=_ZkvyVnWgYk

**Comment by zefanja** [comment]
Hello @umairsy,

Maybe I haven't understand it right, but if I follow your suggestion I have to create several fee structures (based on the discounts) for every program, right? There is no way to have percentage discounts?

I'm asking, because we have quite a lot of programs and different discounts. That will be a lot of possible combinations...

**Comment by umairsy** [comment]
Did you try this?

![screen shot 2017-11-15 at 5 56 49 pm](https://user-images.githubusercontent.com/910238/32836049-84511286-ca2e-11e7-83a9-f9e009a5a7ea.png)

This Fee Structure will only be applicable to the Students for whom Student Category is selected as "Employee Student".

**Comment by zefanja** [comment]
@umairsy Yes, I know that is possible, but I don't want total discounts, I like to have %-based discounts. [I've posted more details in the forum](https://discuss.erpnext.com/t/education-domain-fee-module-redesign/25973/25?u=zefanja).

**Comment by ilyesderp** [comment]
Hi @umairsy , Please can you add this feature as soon as possible because it is a basic feature that all private schools need.

**Comment by aymangabir** [comment]
Hi All

I hope everyone is safe and doing well.

Any news about this demanding family discount feature? 

I believe Mr @umairsy suggestion to create (student Category) will end us with numerous number of categories (discount scenarios * Batches * classes).
