### ISSUE TITLE
Should not track changes if value of field is the same

### ISSUE THREAD

**Issue by addymuliady** [frappe/erpnext#11494]
Hi, 

ERPNext: v9.2.2 (master)
Frappe Framework: v9.2.3 (master)

I did a custom script.

`frappe.ui.form.on("Employee", "onload", function(frm, cdt, cdn){
var d = locals[cdt][cdn];
var now = frappe.datetime.nowdate();
var total_days = frappe.datetime.get_day_diff( now , d.date_of_birth);
var total_years = Math.floor((total_days).toFixed(2) / 365.25); 
frappe.model.set_value(cdt, cdn, "age", total_years);
    refresh_field("age");
});
`

In track changes, if there aren't any change, it shouldn't reflect in audit trail.

![image](https://user-images.githubusercontent.com/21187126/32582886-f7f8a8fa-c52b-11e7-9fea-b63f2795ab63.png)

**Comment by umairsy** [comment]
Just tried to replicate. It doesn't add log if there are no changes. There must have been some changes, may be space or enter, hence audit log was added. Click on the log for more details.
