### ISSUE TITLE
[Feature Request] "OR" Filter and Sorting

### ISSUE THREAD

**Issue by lowercase00** [frappe/erpnext#11503]
Hey all.

I would like to suggest the implementation of sorting capabilities for any column on a list. Currently, sorting is only possible for "Last Modified On" option. It would be great to be able to sort by any column - the front end would be only a small up/down arrow right next to the name of the column (similar to Excel filters).

Second, it would be great to be able to filter by more than one field ("OR" filtering). Now, if you apply two filter for example, for two Item Groups  it shows nothing - I assume it is because it is looking for items that have **both** ("AND" filtering) item groups.

This is related to issue [11055](https://github.com/frappe/erpnext/issues/11055), and could be a workaround for the filtering by parent group issue.

**Comment by clarkejj** [comment]
https://discuss.erpnext.com/t/how-to-filter-tasks-on-both-open-or-overdue-tasks/28033

**Comment by clarkejj** [comment]
lowercase00 are you aware of this OR filter on a single param https://discuss.erpnext.com/t/how-to-filter-tasks-on-both-open-or-overdue-tasks/28033

or does your request refers to more than one _different_ parameter?

**Comment by daraul** [comment]
Is this going to happen? I want to be able to filter a list where a date is either in the future, or not set.
