### ISSUE TITLE
Report issue. If Language is Spanish, value not fetched in some fields.

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#11505]
When accessing ERPNext in Spanish, then values in the first two columns are not fetched.

![image5cdfa5](https://user-images.githubusercontent.com/910238/32646086-cbfe5c46-c610-11e7-8f65-e04b82a3bcca.png)

Whereas same values are fetched correctly when Language is English.

![screen shot 2017-11-10 at 12 09 12 pm](https://user-images.githubusercontent.com/910238/32646089-d035daa0-c610-11e7-8c48-54d4604fc8f4.png)

**Comment by tundebabzy** [comment]
Javascript is not able to fetch translation of "Posting Date"
