### ISSUE TITLE
Set valuation rate based on historical reference while making Stock Ledger Entries, instead of making GLE

### ISSUE THREAD

**Issue by rohitwaghchaure** [frappe/erpnext#11539]
- While calculating valuation rate based on valuation method for an incoming entry, if incoming_rate is zero and `allow_zero_valuation_rate` is not checked, set valuation_rate based on existing SLE or Item master valuation rate or Price list rate.
- Currently it does only for outgoing entry. And for incoming entry, while posting GLE, it sets valuation rate if missing, but does not repost future entries, which leads to problem.

**Comment by Olawale1** [comment]
Hi,

This is quite a significant issue that needs urgent attention. Stock Ledger and General Ledger are showing totally different values for stock movement!

Thanks

**Comment by rohitwaghchaure** [comment]
Fixed via https://github.com/frappe/erpnext/pull/11986
