### ISSUE TITLE
pos profile active in sales invoice

### ISSUE THREAD

**Issue by farhanayyaz1** [frappe/erpnext#11532]
can the pos profile be active on sales invoice even if the invoice is not cash invoice? As when making sales invoices which are credit, the accounts picked are default accounts on the item but those should be picked up as per user profile like the cost of goods sold, sales and warehouse.

**Comment by rohitwaghchaure** [comment]
@farhanayyaz1 
Enable **Include Payment (POS)** in sales invoice, system picked up data like goods sold, sales and warehouse from the user's pos profile

**Comment by farhanayyaz1** [comment]
then have to include payment mode also.


________________________________

**Comment by umairsy** [comment]
@farhanayyaz1 discussed this Issue based on our call. please create multiple companies and link them with the user, so that each user gets default account fetched from the Company master.

**Comment by farhanayyaz1** [comment]
dear, I check the separate company option but will have to change many things for that.

is it possible to change accounts like the cost of goods sold after submit?
________________________________

**Comment by umairsy** [comment]
No. As per the very basic accounting fundamentals, accounts posting is done on submission on the invoice. Once submitted, amendment in the Accounts should be prevented as it won’t have impact on the Journal Entry. Only option would be to completely cancel and amend the Invoice/Journal Entry to make changes which will have impact on the Journal Entry as well.

- - 
Thanks and regards,
Umair Sayed
erpnext.com

**Comment by farhanayyaz1** [comment]
how can I create bounty as you said earlier for development of using POS profile to be used on all sales invoices?



First Moon Electronics Trading.

SHIPPING MARK:  MFB

TEL:00971-4-2284525

FAX: 00971-4-2242179

Mobile Dubai: 00971-52-9291514

P.O.BOX: 86527,DUBAI-UAE

Address: SH#47,Baglaf Bldg,Nakheel Road,Dubai-UAE

________________________________

**Comment by umairsy** [comment]
https://erpnext.org/bounties <https://erpnext.org/bounties>

- - 
Thanks and regards,
Umair Sayed
erpnext.com
