### ISSUE TITLE
Production Order - Raw-materials Qty calculations

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#11536]
WN-SUP28944

As per the BOM, 1 qty is required for manufacturing 1 unit of an item. However, in the BOM, required Qty for the BOM is not calculated correctly.

FG: Finished goods
RM: Raw materials

![screen shot 2017-11-13 at 12 17 56 pm](https://user-images.githubusercontent.com/910238/32712987-3ed00234-c86d-11e7-91d0-cf38958d908d.png)

Error occurs if you edit the value in the Qty to Manufacture field. On saving a Production Order, the value in the child table seems to be not revising sometime. Though, in my test account, required Qty was revising correctly on save and submit. Issue occurring in the client's Purchase Order record. Check Issue for more details.

**Comment by pratu16x7** [comment]
https://github.com/frappe/frappe/pull/4488

**Comment by tundebabzy** [comment]
@umairsy Please confirm
