### ISSUE TITLE
Rename "Production Order" to "Work Order"

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#11554]
To enhance ERPNext for construction, it would be better to rename Production to Work Order. In construction projects, the user will create a BOM (BOQ) against each major sub-project. All the BOMs will be linked via Tasks. Then the user can create a "Work Order" against the Task and track time and material against the Work Order.

Example. If the user wants to plan for "Excavation" as a part of a project, they can create a Task and BOM for Excavation for planning, in execution stage, they can create a Work Order and then execute it from there

- [x] Add BOM link in Task
- [x] Create Work Order against Task
- [ ] Update time + cost in Task

**Comment by neckos** [comment]
Hi

I see that Production Order is renamed to Work Order, but cannot find any of
- "Add BOM link in Task"
- "Create Work Order against Task"
?

**Comment by heyberting** [comment]
Why was this closed?
