### ISSUE TITLE
Clarify labels in shipping rule

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#11556]
From Value, To Value for what?

- [x] Give option to select "Net Total", "Grand Total", "Weight", "Qty"
- [x] Add Weight to all child tables
- [x] Add Total Weight to all transactions

<img width="876" alt="screen shot 2017-11-14 at 12 46 38 pm" src="https://user-images.githubusercontent.com/140076/32767572-f7f564a8-c939-11e7-84fe-b2d620ad8173.png">

**Comment by vishdha** [comment]
https://github.com/frappe/erpnext/pull/11672
