### ISSUE TITLE
Date Filter - Between condition - Data filtered outside defined Date Range as well

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#11562]
WN-SUP28990

Searching for dates between 10th Nov to 14th Nov, it is showing 9th Nov in the Communication Screen

![image00117a1af](https://user-images.githubusercontent.com/910238/32773642-dba68492-c94f-11e7-91c1-4819f7613d97.jpg)

**Comment by manassolanki** [comment]
Fixed via https://github.com/frappe/frappe/pull/4497

**Comment by manassolanki** [comment]
@umairsy Could you please tell some report where this is replicating? 
The fix isn't yet updated in master or cloud.

**Comment by umairsy** [comment]
frappe/central

**Comment by netchampfaris** [comment]
Cannot replicate on central as well
