### ISSUE TITLE
Include code in CSS file

### ISSUE THREAD

**Issue by giuseppelamatrice** [frappe/erpnext#11578]
https://github.com/frappe/erpnext/blob/50616da9050a425a53f7b1fb82d5efe5b9a32164/erpnext/templates/pages/home.html#L40

**Comment by tundebabzy** [comment]
Hi @giuseppelamatrice 
Do you mean that the CSS should not be inlined in the HTML?

**Comment by umairsy** [comment]
Please elaborate your query, and feel free to reopen if needed. If you need a technical assistance, then posting it on community forum will be helpful. https://discuss.erpnext.com

**Comment by giuseppelamatrice** [comment]
Yes, it's more clean code.
