### ISSUE TITLE
HealthCare - Cannot Book More Than One Appointment For A Day For A Doctor

### ISSUE THREAD

**Issue by kennethsequeira** [frappe/erpnext#11582]
The Physician has entered 15 minutes per patient as an entry. Hence, if an appointment is booked for 12 PM, the next appointment slot available should be starting from 12:15 and so on.

However, once a patient has booked a slot for 12 PM, no new appointments can be made for the day. 

![peek 2017-11-15 12-29](https://user-images.githubusercontent.com/33246109/32823031-6f9000dc-ca01-11e7-9437-f516ca417285.gif)

Ideally, I should be able to select any slot listed in the Physician's schedule from 12:15:00 to 13:30:00 (as that is the schedule for the day)

![image](https://user-images.githubusercontent.com/33246109/32823112-c09ae29e-ca01-11e7-8ae9-26efe667bbda.png)

**Comment by rkurungadam** [comment]
You should use Add Time Slots button in Physician Schedule to add multiple slot for a day. Time per Appointment field in physician is not used, it was left out when Appointment document was redesigned. Will update soon.
Thanks

**Comment by kennethsequeira** [comment]
Thank you for the response.

However, I feel that if the **Time Per Appointment** field can be utilized, it can automate the process more, since adding multiple time slots can become cumbersome. I guess this is something that can be looked into and maybe improved in the future

Thanks a lot @rkurungadam !

**Comment by kennethsequeira** [comment]
Hi Ranjit, spoke to @rmehta regarding this issue. We believe this is more of a UI/UX problem then a functional one as the functionality is very well present. When a new user lands on the Schedule Page for the first time, he'll inadvertently click on **Add Row** instead of **Add Time Slots**.

It would be better in case we can change the placement of the button or highlight the timeslot button so the user straight up starts creating slots instead of facing the issue (usability one like I did).

![screen shot 2017-11-23 at 5 49 31 pm](https://user-images.githubusercontent.com/33246109/33173416-0aff4176-d07a-11e7-87e9-6da9883bdf8b.png)

I suppose this can be looked into. Thank you!

**Comment by rkurungadam** [comment]
Hi,
We can make the child able readonly, so the add row button won't appear.
Thanks for your input.

**Comment by kennethsequeira** [comment]
Thank you 😄

**Comment by rmehta** [comment]
Lets add the button to the grid, should not be so hard 😉

**Comment by system19** [comment]
Agreed
