### ISSUE TITLE
Hub fixes March 2018

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#11587]
- [ ] Fix navigation (awesomebar / icon)
   - [ ] New Icon
   - [ ] Fix icon (like "Explore") - can switch off from Hub Settings
- [x] Product View
   - [x] Broken Images
- [x] Category
   - [x] Bootstrap more categories (alibaba?)
   - [x] Crowd source categories - let anyone set if no one has set
   - [x] Feature items for each category (ratings)
- [x] Company View
   - [ ] Default Category (Hub Settings)
   - [x] List view
   - [x] Company wise listing of products
   - [x] Company search
   - [ ] Set Company Introduction + Logo to show in company page
- [x] Company page for Frappe with logo
   - [ ] In app listing for service providers

**Comment by pratu16x7** [comment]
tracked over at: https://github.com/frappe/erpnext/pull/13325
