### ISSUE TITLE
[Feature Request] Drafts in Email

### ISSUE THREAD

**Issue by kennethsequeira** [frappe/erpnext#11583]
Can we get a "Save As Draft" Feature for emails? Sometimes We need more time to frame a mail and whatever is typed will be lost in case the page refreshes.

This feature can improve the usability of the system a lot!

**Comment by umairsy** [comment]
You can save it as Comment (within a document) or as a Standard Reply and pull-up later on

**Comment by basdereus84** [comment]
I think this actually a good request.
Of course, you can use a comment as a workaround but there are situations that you don't know that would like to save it as a draft on forehand. So an option to save it as a draft or even better that ERPNext would save it automatically as a draft until the email has been sent (like almost every email client does) would be a good option in my opinion.
