### ISSUE TITLE
Backend Error when add JavaScript in head block

### ISSUE THREAD

**Issue by giuseppelamatrice** [frappe/erpnext#11604]
In Europe it's mandatory add cookie banner on website.
I added this code in <head></head> generate from https://cookieconsent.insites.com/download and backend it's crashed: 

<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.css" />
<script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.js"></script>
<script>
window.addEventListener("load", function(){
window.cookieconsent.initialise({
  "palette": {
    "popup": {
      "background": "#000"
    },
    "button": {
      "background": "#f1d600"
    }
  }
})});
</script>

![image](https://user-images.githubusercontent.com/4445879/32855911-779556be-ca43-11e7-8ea7-7a2ef32c542b.png)

**Comment by umairsy** [comment]
Hi,

Is this hosted ERPNext account? If yes, please share URL of your account. If it is self-hosted, request you to start a post on the community forum.

https://discuss.erpnext.com / https://discuss.frappe.io

**Comment by giuseppelamatrice** [comment]
My ERPNext account is https://lamatricegiuseppe.erpnext.com

**Comment by umairsy** [comment]
Not able to add this as administrator as well. Seems we will have to remove it from database, but I am afraid, your ERPNext account is on free plan.

**Comment by giuseppelamatrice** [comment]
Please don't remove it. I used it for demo at University of Economy:  http://www.nadivia.com/blog/eventi/loccupabilit%C3%A0-degli-neo-laureati-di-economia-nel-mercato-italiano

**Comment by umairsy** [comment]
Of course we won't. However, resolving this issue will require dedicated efforts on our part which unfortunately is not covered for the account on the Free plan. I have escalated it to the expert to see what could be done.

**Comment by giuseppelamatrice** [comment]
No problem. Umair thank you very much.

**Comment by pratu16x7** [comment]
@giuseppelamatrice You need to add these in the header section of the website, accessible via Website Settings:

![screen shot 2017-11-16 at 3 34 54 pm](https://user-images.githubusercontent.com/5196925/32885561-d9a2997a-cae3-11e7-9cdc-fd1e4311e527.png)
![screen shot 2017-11-16 at 3 34 41 pm](https://user-images.githubusercontent.com/5196925/32885566-dc0e6d24-cae3-11e7-9c0f-fd9119471f37.png)

Website Script is for generic JS code you'd like to run and takes in whatever you would put _inside_ an `<script>` tag.

**Comment by giuseppelamatrice** [comment]
@pratu16x7 I added code into in Website Settings (in "HTML HEADER & ROBOTS" section) but ERPNext backend crashed :(

**Comment by pratu16x7** [comment]
Screenshots? JS Console trace? Will be difficult to debug otherwise.

**Comment by giuseppelamatrice** [comment]
![schermata 2017-11-16 alle 11 57 12](https://user-images.githubusercontent.com/4445879/32887776-5cbde1bc-cac5-11e7-8156-365766fb1adc.png)


![schermata 2017-11-16 alle 11 58 16](https://user-images.githubusercontent.com/4445879/32887823-7ba7fd6a-cac5-11e7-9917-f34ee5a6d182.png)

**Comment by bilalbayasut** [comment]
I have exactly the same problem and it seems it hasn't resolved yet

**Comment by giuseppelamatrice** [comment]
Remove your code added with your smartphone.
