### ISSUE TITLE
Item based taxation with multiple tax accounts

### ISSUE THREAD

**Issue by mehmetalianil** [frappe/erpnext#11607]
I often have to enter Purchase invoices with items that have %6 and %21 tax rates. (Say, services and drink consumption together in one invoice) If I use the itemwise taxation in its current state, it applies the %21 tax, but with a %6 rate. That puts the amount for the %6 VAT to the account meant for the %21 VAT. 

What I propose is to extend the itemwise taxation feature to include individual handling of different tax accounts. 

https://discuss.erpnext.com/t/item-wise-taxation-that-populates-both-relevant-tax-accounts/30302
https://discuss.erpnext.com/t/item-wise-tax-does-not-break-up-correctly/30288

**Comment by umairsy** [comment]
In the Sales/Purchase Tax and Charges master, select all the tax accounts which could be applied to the Items, but keep the tax rate as zero. Ensure that tax rates are updated in the Item master. If Account updated in the Sales/Purchase Tax and Charges master matches with the Account in the Item master, then rate will be fetched from the Item master.

https://youtu.be/a8Eh4zLIrkU?t=3m51s

https://erpnext.org/docs/user/manual/en/accounts/item-wise-taxation

Hope this helps.
