### ISSUE TITLE
Update an Healthcare ERPNext Domain.

### ISSUE THREAD

**Issue by josmeldiaz21** [frappe/erpnext#11622]
I wanted to update my ERPNext with
`sudo bench update --reset
`
and I got this.
`frappe.exceptions.UniqueValidationError: (u'Item Group', u'Laboratory', IntegrityError(1062, "Duplicate entry 'laboratory' for key 'route'"))`

what can I do for this?

**Comment by system19** [comment]
Don't use sudo with `bench update --reset`
