### ISSUE TITLE
Moving the completion slider in gantt view shows error popup saying "Progress % for a task cannot be more than 100"

### ISSUE THREAD

**Issue by raghukamath** [frappe/erpnext#11636]
When you move the progress slider in gantt chart page. The users gets a popup saying "Progress % for a task cannot be more than 100." 

The percentage is not above 100% as the popup says.

Attached is a screenshot of the popup
![screenshot-2017-11-17 task gantt 1](https://user-images.githubusercontent.com/9101092/32945620-2236bca8-cbba-11e7-8dda-ae3b0bd6bc2a.png)

**Comment by netchampfaris** [comment]
Fixed in this commit
https://github.com/frappe/frappe/commit/7595fb75bae4000d75eac635407b14ea6023d1af
