### ISSUE TITLE
UAE VAT Implementation

### ISSUE THREAD

**Issue by nabinhait** [frappe/erpnext#11632]
- Add "Permit No" in Sales/Purchase Invoice
- Add custom field for "Reverse Charge Applicable" in sales/purchase invoice
- Add "Tax Code" in Item master and Sales / Purchase Invoice Item table
- Bootstrap "VAT" and "Excise" tax account and tax template
- Create 2 print formats simple and detailed tax invoice as mention by Sami below.
- In report hard-code Software Vendor details
- Post GL Entry for each Item level ???
- Make 4 reports
      - VAT Return
      - Excise Return
      - FTA VAT Audit File ([Test Data for VAT FAF.xlsx](https://github.com/frappe/erpnext/files/1481804/Test.Data.for.VAT.FAF.xlsx))
      - FTA Excise Tax Audit File ([Test Data for Excise Tax FAF.xlsx](https://github.com/frappe/erpnext/files/1481806/Test.Data.for.Excise.Tax.FAF.xlsx))

**Comment by nabinhait** [comment]
Requirement Doc

[Requirements Document for Tax Accounting Software v 0.2.0.docx.pdf](https://github.com/frappe/erpnext/files/1481812/Requirements.Document.for.Tax.Accounting.Software.v.0.2.0.docx.pdf)

**Comment by aiqual** [comment]
Yesterday the FTA released the latest version of Tax Accounting Software requirements document, together with an updated output file in XML schema format (as opposed to previous CSV format). 

The FTA noted that "this xml schema is for reference purpose only - It can be used to get an idea of the data fields, formats and repeating groups that are allowed."

I attached both files so all concerned can start analyzing and finding if there are any additional gaps between ERPNext and the FTA. 

As next step I will try to classify these gaps as either "Must Have" or "Nice to Have" so we can start tackling the highest priorities first.

If you have any questions regarding the requirements please let me know and I can engage with the FTA to get clarifications. 

[Requirements Document for TAS v 1.4.0.pdf](https://github.com/frappe/erpnext/files/1486654/Requirements.Document.for.TAS.v.1.4.0.pdf)
[GXY-SDS-018-PSR-VAT Return XML Data structure Worksheets_En_v0.0.1.xlsx](https://github.com/frappe/erpnext/files/1486655/GXY-SDS-018-PSR-VAT.Return.XML.Data.structure.Worksheets_En_v0.0.1.xlsx)

**Comment by aiqual** [comment]
To facilitate understanding of all requirements and their priority, I did an analysis on the "Requirements Document for TAS v 1.4.0.pdf" and summarized key points in attached Excel file. I hope it will make it more clear what the key requirements are. I also proposed a 2 phases approach where the "Must Have" features are given priority.

[Breakdown of UAE VAT Requirements for ERPNext v20171124.xlsx](https://github.com/frappe/erpnext/files/1500980/Breakdown.of.UAE.VAT.Requirements.for.ERPNext.v20171124.xlsx)

**Comment by stepsibg** [comment]
It will also help us in Saudi Arabia.

**Comment by OneiricIT** [comment]
> Add "Tax Code" in Item master and Sales / Purchase Invoice Item table
Add "Tax Rate" in Sales / Purchase Invoice Item table, set default rate as per template
If Tax Rate mentioned Sales / Purchase Invoice Item table, give it higher priority in calculation

@nabinhait does this achieve per my post below?

https://discuss.erpnext.com/t/item-tax-override-for-sales-purchases-development/31040

**Comment by aiqual** [comment]
I have some additional details about the most important document for VAT compliance: the Tax Invoice.

According to the  FTA, there will be two kinds of invoices for VAT in the UAE:
A) Simplified Invoice
B) Detailed Invoice

Supply for less than the specified amount of AED 10,000 will use a simplified VAT invoice – specifically for supermarkets and retail industry. However, supply for more than the specified amount will have to be a detailed invoice.

**Simplified VAT invoice** should include the below:
===============================
1- “tax invoice” in a prominent place
2- Name, address & TRN of supplier
3- Date of issue
4- Description of goods or services
5- Total amount payable
6- Total VAT chargeable

The **Detailed VAT Invoice** for supplies above AED 10,000 should include all the below:
=======================================================
1- “tax invoice” in a prominent place
2- Name, address & TRN of supplier
3- Name, address & TRN of recipient (if they are a registered)
4- A sequential or unique identifying invoice number
5- Date of issue
6- Date of supply if different to the date of issue
7- Description of goods or services 
8- Unit price, quantity or volume supplied, rate of tax and amount payable in AED (for each line item in invoice)
9- Value of any discount offered
10- Gross value payable in AED
11- Tax amount payable in AED
12- Statement relating to reverse charge if applicable

**Comment by aiqual** [comment]
I received from the FTA a document detailing how the VAT Return Report looks like. Please see attached. This is essential to have as it used for filing the VAT return every month or quarter. 

Here are the report sections:

**Title: Value Added Tax Return**
_includes some header information_

**Section 1: VAT on Sales and all other Outputs**
_includes these 9 sub-sections:_
1 
   1a Standard rated supplies in Abu Dhabi
   1b Standard rated supplies in Dubai
   1c Standard rated supplies in Sharjah
   1d Standard rated supplies in Ajman
   1e Standard rated supplies in Umm Al Quwain
   1f Standard rated supplies in Ras Al Khaimah
   1g Standard rated supplies in Fujairah

2 Tax Refunds provided to Tourists under the Tax Refunds for Tourists Scheme
3 Supplies subject to the reverse charge provisions
4 Zero rated supplies
5 Supplies of goods and services to customers registered for VAT in other GCC implementing states
6 Exempt supplies
7 Goods imported into the UAE
8 Adjustments and additions to goods imported into the UAE
9 Totals

**Section 2: VAT on Expenses and all other Inputs**

10 Standard rated expenses
11 Supplies subject to the reverse charge provisions
12 Totals

**Section 3: Net VAT due**

13 Total value of due tax for the period
14 Total value of recoverable tax for the period
15 Net VAT payable (or reclaimable) for the period
16 Do you wish to request a refund for the above amount of reclaimable VAT?

**Section 4: Additional Reporting Requirements**

See attachment for details
[VAT return.pdf](https://github.com/frappe/erpnext/files/1546537/VAT.return.pdf)

**Comment by aiqual** [comment]
Attached is the same VAT return file, with addition of extra comments "Tooltip" to further clarify each field.
[VAT Return with Tooltip.pdf](https://github.com/frappe/erpnext/files/1554126/VAT.Return.with.Tooltip.pdf)

**Comment by tundebabzy** [comment]
#11923

**Comment by rohitwaghchaure** [comment]
@aiqual  @stepsibg 

Excise tax is also applicable in the Saudi Arabia or there is only VAT tax?
If yes, is there any case where both vat and excise will be applicable on the invoice or only one tax(vat or excise) at a time will be applicable?

**Comment by iteahmad** [comment]
@aiqual Hello, Would you please tell me where did you get the **GXY-SDS-018-PSR-VAT Return XML Data structure Worksheets_En_v0.0.1** from?

**Comment by aiqual** [comment]
@iteahmad I got it from the UAE Federal Tax Authority, they have team supporting ERP software providers.

**Comment by nabinhait** [comment]
Created a separate issue for required report VAT / Excise Return and Audit #12891. Please continue the discussion on that thread.

Closing this issue.

**Comment by zohaibeq** [comment]
Kindly let me know to show VAT invoice in Dual amount AED & USD as pr FTA format. Thanks!

**Comment by zohaibeq** [comment]
also conversion rate is show on invoice as per FTA format in UAE. Specially USD currency
