### ISSUE TITLE
one sales order, several same invoices

### ISSUE THREAD

**Issue by omnison** [frappe/erpnext#11660]
![2017-11-20 11 34 59](https://user-images.githubusercontent.com/7886153/33007459-43e23d48-cde8-11e7-8c60-f57e6079f68c.png)

**Comment by shreyashah115** [comment]
Can you provide steps to reproduce this?

**Comment by omnison** [comment]
i just "make " invoice in sales order.

**Comment by tundebabzy** [comment]
fixed in frappe/frappe#4763
