### ISSUE TITLE
Report goes the wrong way

### ISSUE THREAD

**Issue by ci2014** [frappe/erpnext#11669]
Hello there,

doesn't this chart of Minutes to first response in the Support app go to the wrong direction (right to left, instead of left to right)?

![image](https://user-images.githubusercontent.com/8351245/33042279-88d68b94-ce41-11e7-94ee-fb1fe0450fdf.png)

EDIT:

When we change the query, to give us the results ascending, it's the correct way:

![image](https://user-images.githubusercontent.com/8351245/33042628-c5b03fe6-ce42-11e7-9c69-336196b82bf0.png)

However, now the chart is correct (as someone would expect it to be), but the report itself starts with the oldest, which is obviously not what the author of this code was intending.

Do we need a different query for the chart? Is there a way to fix the chart by adding a parameter and make it sort the other way, than the sql query itself does?

![image](https://user-images.githubusercontent.com/8351245/33042655-e592376a-ce42-11e7-8f28-6b6f9f362f5e.png)

**Comment by deepeshgarg007** [comment]
Can't find this report anymore. Closing
