### ISSUE TITLE
Company Defaults Unable to Change

### ISSUE THREAD

**Issue by jondayfoods** [frappe/erpnext#11684]
We have two companies which were setup in this order:
1. USA
2. Canada

Therefore ERP is defaulting to using the USA company. This is no longer the primary company, though, still operational. I cannot find a way to change the default company in ERP.

Would highly recommend for there to be an option to change default company.

**Comment by rohitwaghchaure** [comment]
@jondayfoods 

Goto Setup > Settings > Global Settings > Change Default Company
![screen shot 2017-11-22 at 11 02 44 am](https://user-images.githubusercontent.com/8780500/33111545-b18ab180-cf74-11e7-8e2e-84d27db6cf62.png)


Closing issue, feel free to reopen if issue still persists
