### ISSUE TITLE
Error in fetching name

### ISSUE THREAD

**Issue by pranalithorve** [frappe/erpnext#11686]
it showing error in console
jquery.min.js:4 POST http://35.189.48.8/ 404 (NOT FOUND)
![screenshot from 2017-11-22 10-17-28](https://user-images.githubusercontent.com/33888016/33110793-6acdb82c-cf70-11e7-8fd2-be40be89adc7.png)

**Comment by umairsy** [comment]
Please post your technical queries on the ERPNext community forum. If you have already discussed this on the forum, share it's link here. Create Github Issue only if issue is validated as a Bug or if it is a feature suggestion.

https://discuss.erpnext.com
