### ISSUE TITLE
OSError [Errno 5] Input/output error: In generate html to pdf in python.

### ISSUE THREAD

**Issue by sunbarve** [frappe/erpnext#11699]
Traceback (most recent call last):
File /home/ubuntu/upruf/model/user_details.py, line 2290, in saveApplication
pdfkit.from_string(maketemplate, path + username + '.pdf')
File /usr/local/lib/python3.5/dist-packages/pdfkit/api.py, line 72, in from_string
return r.to_pdf(output_path)
File /usr/local/lib/python3.5/dist-packages/pdfkit/pdfkit.py, line 164, in to_pdf
sys.stdout.write(stderr)
OSError: [Errno 5] Input/output error while handling path /v1/saveapplication

**Comment by umairsy** [comment]
Hi,

Request you to post this issue in the community forum first. If it is validated as a bug in ERPNext, we could track it as a Github Issue.

https://github.com/frappe/erpnext

If you have already discussed on the forum, please share the discussion link here.
