### ISSUE TITLE
Default letter head on the PDF sent in Emails even if letter head is not selected. 

### ISSUE THREAD

**Issue by Arundhatii** [frappe/erpnext#11692]
Reported via https://frappe.erpnext.com/desk#Form/Issue/WN-SUP29164
Refer the attachment 
![letter head issue](https://user-images.githubusercontent.com/20164097/33129602-72e60df2-cfb6-11e7-9b9d-db20360861bb.gif)

**Comment by riyasrawther** [comment]
After update my emails does not contain any Letterhead

**Comment by naqeeb0098** [comment]
i have issue in version 14 when i send any documnet in email my defualt letter head is send even i have disable the letter head and remove the deault option but stiill i m facing this issue......can any one tell me proper solution
