### ISSUE TITLE
Online POS: Model getting freeze/fade in.

### ISSUE THREAD

**Issue by asharamseervi** [frappe/erpnext#11697]
This might be a critical bug. I'm not able to elaborate in words, so I tried to record the video. Please go through that, what exactly happening.

If POS is activated as online, it getting freeze/fade in every model. However, functionality working. In addition to that, there are two errors on my console, kindly refer screenshot:

![erpnext-bug-online-pos-1](https://user-images.githubusercontent.com/5942572/33150801-31c49682-cffb-11e7-936a-6b0d7ca97698.PNG)

While, hacking. I got, if I delete below model class from element, till next screen everything will work fine & then, same weird thing happen on another screen:
`<div id="freeze" class="modal-backdrop fade in"><div class="freeze-message-container"><div class="freeze-message"><p class="lead"></p></div></div></div>`

If you can't reproduce this issue, I have recorded a small video, please look into this: https://youtu.be/gprnwYdg86A

**Comment by rohitwaghchaure** [comment]
@asharamseervi 

Thanks for reporting an issue, we have fixed the issue, kindly pull latest code and check.
Closing the issue, fell free to reopen is issue still persists
