### ISSUE TITLE
Missing Links between DocTypes

### ISSUE THREAD

**Issue by addymuliady** [frappe/erpnext#11696]
1. In Opportunity, it shows link to Quotation but in Quotation, there is no link to Opportunity

![image](https://user-images.githubusercontent.com/21187126/33149803-07c5996a-d00c-11e7-822a-3398f07b6769.png)

![image](https://user-images.githubusercontent.com/21187126/33149871-4c9d3b56-d00c-11e7-956e-62367b758833.png)

2. Sales Order - Make from Quotation but there is no Link.

![image](https://user-images.githubusercontent.com/21187126/33150172-48b8ee80-d00d-11e7-8197-2e1a94e06e00.png)

**Comment by addymuliady** [comment]
Hi @kennethsequeira 

Just wondering why these aren't classified as bugs?

**Comment by kennethsequeira** [comment]
Need to check if this is by design or a bug.

**Comment by kennethsequeira** [comment]
Not a bug. Please check how LinkedWith works.

https://erpnext.org/docs/user/manual/en/using-erpnext/articles/check-link-between-documents

**Comment by addymuliady** [comment]
Thanks @kennethsequeira !

**Comment by kennethsequeira** [comment]
You're welcome 😄  @addymuliady
