### ISSUE TITLE
erpnext.patches.v8_10 creating a Database timeout

### ISSUE THREAD

**Issue by kickapoo** [frappe/erpnext#11707]
Executing erpnext.patches.v8_10.update_gl_due_date_for_pi_and_si

Is creating pymysql.err.InternalError: (1205, u'Lock wait timeout exceeded; try restarting transaction')

**Comment by rmehta** [comment]
This is not a patch issue, this happens because you may have other things in parallel.

**Comment by kickapoo** [comment]
@rmehta  it say **Executing patch**  erpnext.patches.v8_10.update_gl_due_date_for_pi_and_s

I also tested in local. Please check it again.

**Comment by tundebabzy** [comment]
@kickapoo please use `SHOW ENGINE STATUS` to confirm where the record lock is coming from.
