### ISSUE TITLE
Problem with Quoting Items from different Price Lists 

### ISSUE THREAD

**Issue by lm-dg** [frappe/erpnext#11720]
I am trying to setup separate Selling Price Lists for each supplier, each with thousands of items. I have encountered the following problem in ERPnext v9.25.
Eg. Item1 in PriceList1  and  Item2 in PriceList2
During quotation:
1.	I select PriceList1 then add Item1
2.	I select PriceList2 then add Item2

When I save the quotation I get Message: “Item Price added for Item1 in Price List PriceList2”

This creates a problem of wrong items in the wrong price lists, mixes items and suppliers where items end up in wrong supplier price list.
Further testing showed that this is true for Quotation and Sales Order.

Use-case in the example below.
•	T-Shorts are from T-Short-Supplier with variants of size and color (PriceList-T-Short-Supplier)
•	Shorts are form Shorts-Supplier with variants of size, color, male/female (PriceList-Shorts-Supplier)
•	Soaps are from Soap-Supplier with variants of fragrance, shape (PriceList-Soap-Supplier)

Quotation can be any number and combination of item variants.

During quotation I select Price List in the “Currency and Price List” section then Add Row to add an Item. The Price List is one of the three above.  This process is repeated to form complete quotation.

This works except the last selected price list is updated with all items in the table from other price lists once Quotation is saved.

It would be also very useful if drop-down Items Code where from selected Price List only, rather than all items.

Please assist.
Regards,
Gene May

**Comment by joezsweet** [comment]
Only an idea ..what about to idea to change Price List structure to a tree one? so that will be possible to inherit from parents if price is not defined in actual price list?

**Comment by lm-dg** [comment]
@joezsweet Thanks for the quick reply. Tree structure for Price Lists doesn't appear in the search bar. In my case tree Price List structure would not help, because products are not related, just quoted together. I am not developer but only a user of ERPNext.

regards,
Gene May
