### ISSUE TITLE
Adding <iframe> HTML code in About Us settings doesn't work

### ISSUE THREAD

**Issue by dvdl16** [frappe/erpnext#11728]
Hi

This is confirmed working in:
ERPNext: v8.0.33 (master)
Frappe Framework: v8.0.55 (master)

But now that we have:
ERPNext: v9.1.4 (master)
Frappe Framework: v9.1.6 (master)
it doesn't work

To replicate, go to Website > About Us Settings, in Company Introduction change the text editor to "Code View", and paste the following
`<iframe src="https://www.w3schools.com"></iframe>`
Then click on save.

It's as if it goes through an HTML parser and doesn't want to allow iframes

**Comment by umairsy** [comment]
Please reporting technical queries on community forum first.

https://discuss.frappe.io
