### ISSUE TITLE
POS Session ID required

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#11747]
Hi,

We need to have a Session ID (and maybe Terminal ID) attached to each POS transaction. The Session ID allows us to identify the transactions made by a particular user within the defined session. It also let's us know when a transaction is created in a different browser from other transactions since it will have a different session ID

I know @chdecultot put a lot of effort into this before the release of Online POS but I'm not sure of the current status

Thanks

**Comment by umairsy** [comment]
How about defining terminal ID based on the ID selected in the POS Profile?

**Comment by Olawale1** [comment]
Hi @umairsy

Trust you're doing great. I'm not sure that helps much since the ID for the profile will remain the same across different browsers and tabs. For Terminal ID you need a unique identifier for each access point (which is a browser page in the case of ERPNext)

With Session ID, we may not need Terminal ID so much since each session on a different browser page will have a separate ID. This is very important for forensic audits of POS Sales. It helps users trace and identify sales coming from different interfaces or access points

Thanks

**Comment by chdecultot** [comment]
Hi @Olawale1,

Yes I started working on this issue a while ago and stopped due to the refactor of the POS. I plan to make a new proposal soon but I don't find anytime for it for the moment... I keep you updated!
