### ISSUE TITLE
[Bug] - Payment Request Print Error

### ISSUE THREAD

**Issue by kennethsequeira** [frappe/erpnext#11742]
While creating a Payment Request in my test account, in both the draft and final pdf, the code got printed in the PDF. 

![screen shot 2017-11-27 at 2 39 59 pm](https://user-images.githubusercontent.com/33246109/33258876-f819d1f2-d380-11e7-8f4d-46f279637fac.png)

**Comment by tundebabzy** [comment]
#11830

**Comment by kennethsequeira** [comment]
Thanks @tundebabzy  😄
