### ISSUE TITLE
Enable/Disable Discount in POS using POS Profile

### ISSUE THREAD

**Issue by jay-parikh** [frappe/erpnext#11748]
There is no option to enable / disable Discount for POS User using POS Profile. I was stumble on this thread [Enable POS Discount](https://discuss.erpnext.com/t/enable-pos-discount/16881/4) and it seems this was available in versions 7 but in current version 9 there is no provision to enable / disable Discount for POS.

**Comment by umairsy** [comment]
In a POS profile, if you check this field, then Discount defined in the Pricing Rule will be applied, else no.

![screen shot 2017-11-28 at 11 28 51 am](https://user-images.githubusercontent.com/910238/33304533-6f00aa9e-d42f-11e7-910d-5e23167fc46b.png)

**Comment by jay-parikh** [comment]
@umairsy Thanks for your help but I believe we have some gap in understanding. I am asking about a feature to enable / disable discount from POS Keypad. Which was exist in earlier version 7.
This is  an excerpt from reference discuss post i have mentioned in previous comment.

>  you need to check Allow Discount in the POS profile. We have added this feature because some user want to disable the extra discount for POS.

The checkbox to "Allow Discount in POS Profile" is missing from Version 9. When it's unchecked it will hide Discount from POS Keypad.
![image](https://user-images.githubusercontent.com/3703266/33307068-3cffae08-d43b-11e7-9300-eec27e82e3e2.png)

Hope this makes sense. Can you please open this issue?

**Comment by jay-parikh** [comment]
@rohitwaghchaure Here is the pull request for the same.
[Enable/Disable Discount in POS using POS Profile #12739](https://github.com/frappe/erpnext/pull/12739)
