### ISSUE TITLE
Missing Invoices in V9 POS [Critical]

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#11745]
Hi,

We were doing a reconciliation of POS Sales in the last one week and discovered at least 3 Sales for which receipts were printed from the POS but they never got synced to the Sales Invoice list. There is no visible error message and nothing in the Customer Queue

Please help look into this urgently! Missing Invoices are totally unacceptable

Thanks

**Comment by rohitwaghchaure** [comment]
@Olawale1 

Are you using offline POS? If yes, user had cleared the cache of the browser?
As currently we're storing the data in the localstorage, if user clears the cache of the browser, browser removes the data from the localstorage too. To fix this issue soon we're starting working on the indexeddb to store offline data

**Comment by Olawale1** [comment]
Hi @rohitwaghchaure

Trust you're doing great. The cashiers don't seem to recall clearing the cache at any point in time! Is there something else that could be responsible for this?

Working on the indexeddb is long overdue. I'm glad it's finally getting some attention. I hope this is treated with the urgency it deserves

Kind regards,

**Comment by Olawale1** [comment]
Hi @rohitwaghchaure 

Trust you're doing great. We just discovered another 2 invoices that did not get synced from sales made last weekend. The browser cache was not cleared

Please help look into this urgently 

Thanks

**Comment by rohitwaghchaure** [comment]
@Olawale1 
Can you please check the error log list and share the complete traceback of an error related to pos?

**Comment by Olawale1** [comment]
Hi @rohitwaghchaure 

Trust you're doing great. As mentioned earlier, the browser cache history has not been cleared. Please find below some of the errors found in the log
`
Traceback (most recent call last): File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/sales_invoice/pos.py", line 483, in submit_invoice si_doc.submit() File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 778, in submit self._submit() File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 767, in _submit self.save() File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 256, in save return self._save(*args, **kwargs) File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 307, in _save self.run_post_save_methods() File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 831, in run_post_save_methods self.run_method("on_submit") File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 702, in run_method out = Document.hook(fn)(self, *args, **kwargs) File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 965, in composer return composed(self, method, *args, **kwargs) File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 948, in runner add_to_return_value(self, fn(self, *args, **kwargs)) File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 696, in <lambda> fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs) File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 132, in on_submit self.make_gl_entries() File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 596, in make_gl_entries update_outstanding=update_outstanding, merge_entries=False) File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/general_ledger.py", line 19, in make_gl_entries save_entries(gl_map, adv_adj, update_outstanding, from_repost) File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/general_ledger.py", line 88, in save_entries make_entry(entry, adv_adj, update_outstanding, from_repost) File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/general_ledger.py", line 100, in make_entry gle.run_method("on_update_with_args", adv_adj, update_outstanding, from_repost) File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 702, in run_method out = Document.hook(fn)(self, *args, **kwargs) File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 965, in composer return composed(self, method, *args, **kwargs) File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 948, in runner add_to_return_value(self, fn(self, *args, **kwargs)) File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 696, in <lambda> fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs) File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/gl_entry/gl_entry.py", line 32, in on_update_with_args self.validate_account_details(adv_adj) File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/gl_entry/gl_entry.py", line 89, in validate_account_details .format(self.voucher_type, self.voucher_no, self.account)) File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 319, in throw msgprint(msg, raise_exception=exc, title=title, indicator='red') File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 309, in msgprint _raise_exception() File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 282, in _raise_exception raise raise_exception(encode(msg)) ValidationError: Sales Invoice YINV-001264: Account Sales - YR cannot be a Group`

**Comment by Olawale1** [comment]
`Traceback (most recent call last): File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/sales_invoice/pos.py", line 483, in submit_invoice si_doc.submit() File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 778, in submit self._submit() File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 767, in _submit self.save() File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 256, in save return self._save(*args, **kwargs) File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 307, in _save self.run_post_save_methods() File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 831, in run_post_save_methods self.run_method("on_submit") File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 702, in run_method out = Document.hook(fn)(self, *args, **kwargs) File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 965, in composer return composed(self, method, *args, **kwargs) File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 948, in runner add_to_return_value(self, fn(self, *args, **kwargs)) File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 696, in <lambda> fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs) File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 132, in on_submit self.make_gl_entries() File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 606, in make_gl_entries update_gl_entries_after(self.posting_date, self.posting_time, warehouses, items) File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/stock_controller.py", line 349, in update_gl_entries_after voucher_obj = frappe.get_doc(voucher_type, voucher_no) File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 634, in get_doc return frappe.model.document.get_doc(*args, **kwargs) File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 68, in get_doc return controller(*args, **kwargs) File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 31, in __init__ super(SalesInvoice, self).__init__(*args, **kwargs) File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/accounts_controller.py", line 19, in __init__ super(AccountsController, self).__init__(*args, **kwargs) File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 103, in __init__ self.load_from_db() File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 140, in load_from_db frappe.throw(_("{0} {1} not found").format(_(self.doctype), self.name), frappe.DoesNotExistError) File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 319, in throw msgprint(msg, raise_exception=exc, title=title, indicator='red') File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 309, in msgprint _raise_exception() File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 282, in _raise_exception raise raise_exception(encode(msg)) DoesNotExistError: Sales Invoice YINV-001255 not found`

**Comment by Olawale1** [comment]
`Traceback (most recent call last): File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/sales_invoice/pos.py", line 483, in submit_invoice si_doc.submit() File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 778, in submit self._submit() File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 767, in _submit self.save() File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 256, in save return self._save(*args, **kwargs) File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 307, in _save self.run_post_save_methods() File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 831, in run_post_save_methods self.run_method("on_submit") File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 702, in run_method out = Document.hook(fn)(self, *args, **kwargs) File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 965, in composer return composed(self, method, *args, **kwargs) File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 948, in runner add_to_return_value(self, fn(self, *args, **kwargs)) File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 696, in <lambda> fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs) File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 132, in on_submit self.make_gl_entries() File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 587, in make_gl_entries gl_entries = self.get_gl_entries() File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 621, in get_gl_entries self.make_item_gl_entries(gl_entries) File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 699, in make_item_gl_entries gl_entries += super(SalesInvoice, self).get_gl_entries() File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/stock_controller.py", line 67, in get_gl_entries sle = self.update_stock_ledger_entries(sle) File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/stock_controller.py", line 98, in update_stock_ledger_entries self.doctype, self.name, currency=self.company_currency, company=self.company) File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/stock_ledger.py", line 464, in get_valuation_rate frappe.throw(_("Valuation rate not found for the Item {0}, which is required to do accounting entries for {1} {2}. If the item is transacting as a zero valuation rate item in the {1}, please mention that in the {1} Item table. Otherwise, please create an incoming stock transaction for the item or mention valuation rate in the Item record, and then try submiting/cancelling this entry").format(item_code, voucher_type, voucher_no)) File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 319, in throw msgprint(msg, raise_exception=exc, title=title, indicator='red') File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 309, in msgprint _raise_exception() File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 282, in _raise_exception raise raise_exception(encode(msg)) ValidationError: Valuation rate not found for the Item YUD-PHON-04043, which is required to do accounting entries for Sales Invoice YINV-001093. If the item is transacting as a zero valuation rate item in the Sales Invoice, please mention that in the Sales Invoice Item table. Otherwise, please create an incoming stock transaction for the item or mention valuation rate in the Item record, and then try submiting/cancelling this entry`

**Comment by Olawale1** [comment]
`Traceback (most recent call last): File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/sales_invoice/pos.py", line 483, in submit_invoice si_doc.submit() File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 778, in submit self._submit() File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 767, in _submit self.save() File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 256, in save return self._save(*args, **kwargs) File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 307, in _save self.run_post_save_methods() File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 831, in run_post_save_methods self.run_method("on_submit") File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 702, in run_method out = Document.hook(fn)(self, *args, **kwargs) File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 965, in composer return composed(self, method, *args, **kwargs) File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 948, in runner add_to_return_value(self, fn(self, *args, **kwargs)) File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 696, in <lambda> fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs) File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 129, in on_submit self.update_stock_ledger() File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/selling_controller.py", line 346, in update_stock_ledger self.make_sl_entries(sl_entries) File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/stock_controller.py", line 265, in make_sl_entries make_sl_entries(sl_entries, is_amended, allow_negative_stock, via_landed_cost_voucher) File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/stock_ledger.py", line 38, in make_sl_entries update_bin(args, allow_negative_stock, via_landed_cost_voucher) File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/utils.py", line 120, in update_bin bin.update_stock(args, allow_negative_stock, via_landed_cost_voucher) File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/doctype/bin/bin.py", line 46, in update_stock }, allow_negative_stock=allow_negative_stock, via_landed_cost_voucher=via_landed_cost_voucher) File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/stock_ledger.py", line 107, in __init__ self.build() File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/stock_ledger.py", line 117, in build self.raise_exceptions() File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/stock_ledger.py", line 379, in raise_exceptions frappe.throw(msg, NegativeStockError, title='Insufficent Stock') File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 319, in throw msgprint(msg, raise_exception=exc, title=title, indicator='red') File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 309, in msgprint _raise_exception() File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 282, in _raise_exception raise raise_exception(encode(msg)) NegativeStockError: 4.0 units of <a href="#Form/Item/INN-HAL2GLD" style="font-weight: bold;">Item INN-HAL2GLD - TD</a> needed in <a href="#Form/Warehouse/xxxxxx - YR" style="font-weight: bold;">Warehouse xxxxxxxx - YR</a> to complete this transaction.`

**Comment by taherkhalil** [comment]
Hello,
Same issue occurred with me..
pos invoices were deleted.
cache was not cleared and system didn't show any errors.
.
It would also be helpful if you could implement off-line type customer creation with mobile and email on the online mode as well..it would facilitate a easier transition to the online pos mode.
.
missing invoices is a major issue .. plz resolve with haste..

**Comment by olamide2** [comment]
@taherkhalil 

are you using the offline PoS?

**Comment by Olawale1** [comment]
Hi @rohitwaghchaure 

Trust you're doing well. We need some updates on this please. We discovered another 2 invoices that didn't get synced last week!

I checked and noticed that the Customers got created shortly after the transaction (as expected) but the Sales Invoices didn't get created and they are not in the queue!

This needs to be solved on high priority please

Thanks

**Comment by olamide2** [comment]
Olawale1 

Are you using the offline PoS?

**Comment by Olawale1** [comment]
Hi @olamide2 

Trust you're doing great. Yes we are. Online POS is totally not an option for the particular store in question. We've actually been enjoying the V8 offline POS for the most part. The V9 offline POS is however where the issue of missing invoices is occurring 

Cheers

**Comment by olamide2** [comment]
Hi @Olawale1 

Thanks for the response. How do you handle the offline situation where a cashier can make a sale without taking payment?

I set up global credit limit to be =N=1, this only prevents the invoice from being submitted but it is saved as draft and the cashier can print. Nothing at the printing point even shows that their is a problem. In a fast paced environment this is a big deal

When using the online mode the transaction is not even saved and the cashier gets a prompt stating that payment is needed.

How do you manage this situation when using the off line mode?

Regards

**Comment by olamide2** [comment]
And if I do not set the credit limits, the cashiers can create loads of accounts receivables which is going to be difficult to track

**Comment by Olawale1** [comment]
Hi @olamide2 

So far we have only dealt with this by policy and ensuring reports tally at the end of each day. It's much better to be able to control this at application level and I'm glad it's now being worked on

Kind regards,

**Comment by taherkhalil** [comment]
@olamide2 , yes  using offline , 

@rohitwaghchaure , @Olawale1 , 

I am still facing this issue -- 
has this been resolved ?

If i am correct there was some research going on into using another type of storage for offline POS rather than the Browser Cache !

Has that been implemented , 
i have seen no recent updates for offline POS in the recent version .

.
@umairsy , @rohitwaghchaure  , 
please update ,
