### ISSUE TITLE
POS doesn't validate Item's valuation rate when selling 

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#11744]
In the Selling Setting, we have this configuration feature.

![screen shot 2017-11-27 at 4 59 49 pm](https://user-images.githubusercontent.com/910238/33264649-7cdf433c-d394-11e7-9a3a-8ca11603dc44.png)

It works just fine in the Sales Invoice creation from Sales Invoice view. But it doesn't validate when creating Sales Invoice from POS view, even if selling price is less than item's valuation.

![screen shot 2017-11-27 at 4 59 49 pm](https://user-images.githubusercontent.com/910238/33264682-98356b84-d394-11e7-9ff0-e24b869313c3.png)

**Comment by tundebabzy** [comment]
Hi @umairsy 
This is not replicating on latest hotfix.

![screenshot from 2017-12-02 18-16-03](https://user-images.githubusercontent.com/818803/33517983-d461feae-d78d-11e7-9d81-44b23d6cf9d3.png)

Perhaps there is an edge case that we look at?
