### ISSUE TITLE
POS Print Format not applying

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#11754]
In the POS Profile, default Print Format is set. But why do we have work online in the field label (in POS)? Does it not apply to Offline invoices?

Here is the demo of the issue.

https://imgur.com/a/ve5oJ

**Comment by rohitwaghchaure** [comment]
@umairsy 
No print in dialog: This feature is merged in develop branch
Print format is printing properly check URL in the GIF it's showing as print format GST POS Invoice

Not replicating issue
