### ISSUE TITLE
Can't Delete Email Account

### ISSUE THREAD

**Issue by jepicode** [frappe/erpnext#11753]
I'm trying to delete email account, but It said : 
Cannot delete or cancel because Email Account xxxx@gmail.com is linked with Unhandled Email 3915f72ec3

**Comment by umairsy** [comment]
Please disable User as it is linked with other transactions. You will be able to create new User in it's place. Disable user is not counted as a user.

**Comment by jepicode** [comment]
@umairsy sorry because I'm newbie in erpnext. I already deleted the account with that email, but when I trying to delete the email again, still showing that error message.

**Comment by umairsy** [comment]
It is a validation. you cannot delete that Email Account because it is linked with some other master.

**Comment by jepicode** [comment]
@umairsy May I know, How I know what's linked with that email?
