### ISSUE TITLE
[CRITICAL] Sales & Purchase Invoices - Currency Exchange Rates Not Fetched

### ISSUE THREAD

**Issue by addymuliady** [frappe/erpnext#11752]
ERPNext: v9.2.16 (master)
Frappe Framework: v9.2.16 (master)

I am sorry mates @tundebabzy @nabinhait , these issues are very critical as I have updated ERPNext on a live site that I have to tag you both. 

- Function was ok in prior version (v9.2.2)
- Allow Stale Exchange Rate is CHECKED.
- Exchange Rates are set proper.

1. Create new Sales/Purchase Invoice
2. Set Posting Date
3. Select Customer/Supplier of different currency
4. You will see that exchange rates are not fetched as pic below
5. Rate should be based on party Account Currency instead of Company Currency

_Exchange Rate List_
![image](https://user-images.githubusercontent.com/21187126/33302574-04f1d6f6-d438-11e7-99a9-cfc574f385ba.png)

_Did not fetch exchange rate_
![image](https://user-images.githubusercontent.com/21187126/33302393-a4130afe-d436-11e7-8625-aa1c18b4f541.png)

**Comment by tundebabzy** [comment]
@addymuliady 
I'm still not able to reproduce this :(  It's working as expected for me

**Comment by tundebabzy** [comment]
@addymuliady 
Any more information would be appreciated. It seems like somehow ERPNext isn't updating the form with the Party currency. For now, I can't even guess what might be wrong and it's not replicating on my end. By the way, are you on master branch?

**Comment by addymuliady** [comment]
Hi @tundebabzy,

Yes I am on master. Are you on the latest version?

**Comment by addymuliady** [comment]
I was on 9.2.2. Then bench update to 9.2.16.

9.2.2 was working well

**Comment by tundebabzy** [comment]
@addymuliady I'm on 9.2.17
Can you post a screenshot of the Customer. You can block out the confidential stuff

**Comment by addymuliady** [comment]
Here you go @tundebabzy 

![image](https://user-images.githubusercontent.com/21187126/33353450-e6a1bc6e-d4e8-11e7-831d-0f83af9fda33.png)

![image](https://user-images.githubusercontent.com/21187126/33353477-039469d4-d4e9-11e7-83b6-7dcd54a304e3.png)

**Comment by tundebabzy** [comment]
@addymuliady 
Do you have any customizations? Still not reproducible here

**Comment by addymuliady** [comment]
Hi @tundebabzy 

Yup I do have custom apps installed.

I am on multitenant and those sites which does not have the custom apps installed still show the same error.

**Comment by addymuliady** [comment]
Hi @tundebabzy 

I did a bench update and all is well now.

Thank you for your time!
