### ISSUE TITLE
Assessment Plan - Naming Should not be based on Assessment Name

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#11757]
There should not be Assessment Name field at all. The ID for assessment plan could be generated based on Naming Series. The Title for Assessment Plan can be generated based on values in multiple fields like Course, Assessment Date, Room etc.

**Comment by manassolanki** [comment]
@umairsy Already name is set as per the naming series for the assessment plan. The assessment plan name is only for the user if as they can set that according to their use case.
