### ISSUE TITLE
Bug - dropbox backup

### ISSUE THREAD

**Issue by sp9leo** [frappe/erpnext#11760]
After updating to 9.15 my dropbox backup started giving error.

Error message: 

> Traceback (most recent call last):
>   File "/home/idefix/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py", line 45, in take_backup_to_dropbox
>     did_not_upload, error_log = backup_to_dropbox()
>   File "/home/idefix/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py", line 107, in backup_to_dropbox
>     upload_from_folder(get_files_path(is_private=1), "/private/files", dropbox_client, did_not_upload, error_log)
>   File "/home/idefix/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py", line 125, in upload_from_folder
>     for root, directory, files in os.walk(path):
>   File "/home/idefix/frappe-bench/env/lib/python2.7/os.py", line 284, in walk
>     if isdir(join(top, name)):
>   File "/home/idefix/frappe-bench/env/lib/python2.7/posixpath.py", line 80, in join
>     path += '/' + b
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 7: ordinal not in range(128)

**Comment by tundebabzy** [comment]
@sp9leo 
Please paste the name of the file(s) in your backup that contain unicode characters. I can use that to test a fix for this.

**Comment by sp9leo** [comment]
I don't know which file is causing issues. Commonly used characters in my language, that are probably causing troubles are č, š and ž

**Comment by tundebabzy** [comment]
The error seems to concern the filename with ž. Can you post the filename?

**Comment by sp9leo** [comment]
Sure. here you go.
MamaraŽ_Oblika_Inventura_6cm.ai
another one: MamaraŽ_Kelih 6cm in križ 2cm.ai

**Comment by achillesrasquinha** [comment]
Fixed at https://github.com/frappe/frappe/pull/5325
