### ISSUE TITLE
Communication Screen Issue

### ISSUE THREAD

**Issue by epochc** [frappe/erpnext#11771]
Here's how the communication screen is being served on Ubuntu Desktop + Chrome and Firefox after a recent update. Please rectify at the earliest.

Thanks

Jay

![image](https://user-images.githubusercontent.com/18049961/33358942-b87df696-d4f1-11e7-9de4-393cb4edd600.png)

**Comment by umairsy** [comment]
Hello,

Communication is a backend record which is auto-created when you send an email or post a comment on any document. You can take Stock Ledger Entry as another example of the record created in the backend.

For more support/queries, let's continue over forum.

**Comment by epochc** [comment]
Wait a second. What about that other screen that we used to have that went To; Sent or Received and Communication Description and then you could link that to a doctype.

I mean, let's say I can a contact. How do I record that communication on ERPNext?

Thanks

Jay

**Comment by umairsy** [comment]
If you email a Contact from the Contact master itself, communication will be auto-created. Also, the Dynamic Links we have, (Document Type and Document ID) will be updated as Contact and Contact ID respectively.

Here is an example of Communication created based on the email sent from Quotation.

![screen shot 2017-11-29 at 12 41 45 pm](https://user-images.githubusercontent.com/910238/33362523-ce2dfe3a-d502-11e7-96e3-c2af85bf1ca3.png)

**Comment by epochc** [comment]
Cool! Thats awesome. But I'm talking about Phone Calls, Meetings, etc. Not E-Mails. I understand that these links are automatically created for documents, but let's say I have submitted a proposal and I make call to the Prospect and invite him for a demo and factory visit.

How do I record this interaction? If you tell me communication is not the correct vehicle for it, great, what other vehicles exist on ERPNext? Or aren't there any vehicles for now?

Thanks

Jay

**Comment by umairsy** [comment]
Jay,

Apart from Email, it's comments which are tracked as Communication as well. No vehical to track communication such as Phone calls. Meetings etc. could be tracked as Calendar Event.

In the Communication master, there are multiple Communication Types, but not sure if they are used anywhere.

![screen shot 2017-11-29 at 6 39 16 pm](https://user-images.githubusercontent.com/910238/33376665-a0885cc8-d534-11e7-9556-892436410b01.png)

Those who have done web-PBX integration (as presented in the conference) have used Communication to make a log for each call.
