### ISSUE TITLE
exports._errnoException reached when bench start

### ISSUE THREAD

**Issue by vin89423** [frappe/erpnext#11775]
I have a clean installed bench & erpnext app on my server.
When i start my bench with `bench start` command, The web server has booted fine.
After some process, the web server stopped because watch.1 reach an error.

Seem the error come from `erpnext/accounts/report/profitability_analysis/profitability_analysis.js`

The following is my error log.
[error.log](https://github.com/frappe/erpnext/files/1512950/error.log)

**Comment by umairsy** [comment]
Technical queries/issues on the community forum please.

https://discuss.frappe.io
https://discuss.erpnext.com
