### ISSUE TITLE
Can't save sales order, delivery note and sales invoice

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#11793]
Hello,

After last update (v9.x.x-develop (95ee765) (develop)), a message pops-up when I try to save a sales order like the screenshot below, no field is mentioned, the console shows no errors.

<img width="750" alt="screen shot 2017-11-29 at 8 27 50 pm" src="https://user-images.githubusercontent.com/18335894/33402652-57ad96e8-d544-11e7-8f65-8a7e7e65c258.png">

**Comment by rohitwaghchaure** [comment]
@applepipe 

We have fixed this issue, can you please pull latest update and check
Closing this issue, feel free to reopen if issue still persists
