### ISSUE TITLE
Item net_weight data deleted

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#11791]
Hello,

After the last update (v9.x.x-develop (95ee765) (develop)), I've noted that the field net_weight was removed and weight_per_unit was created, but all the data is now 0. Do users need to restore a backup, export net_weight and import the info as weight_per_unit?

**Comment by vishdha** [comment]
https://github.com/frappe/erpnext/pull/11798

**Comment by vishdha** [comment]
this patch will fetch data from the net_weight field to weight_per_unit.
