### ISSUE TITLE
Batch Stock Items, having serial number can't be moved without inserting Serial Number

### ISSUE THREAD

**Issue by asharamseervi** [frappe/erpnext#11792]
An item, having serial number & batch, can't be moved to other warehouses, because of no input of field for serials.

To reproduce, Create an item with serials & batch. Now using Stock Entry, Material Receipt in any one warehouse. Let's assume 100 serial items are at X Warehouse, and have to move 50 Serial Items to Y Warehouse.

This will work well, while again using Stock Entry, and Material Transfer to Y Warehouse from X. It'll ask about Batch No. if item is having Batch, and as selected FIFO, first 50 Serials will be transferred to Y Warehouse. Perfect.

But, Same feature is there, in `Stock > Batch` and select same item having bath & serials. There will be shown, 50 serials in Y Warehouse, while another 50 in X. But, using MOVE button, it only asks for Warehouse where to transfer/move. We'll select warehouse, but `**MandatoryError: Row #1: Please specify Serial No for Item XYZ**` will be prompt, _only because Batch/Serial not selected._

**Comment by tundebabzy** [comment]
Fixed in #11813
