### ISSUE TITLE
Quickbooks data import to ERPnext account

### ISSUE THREAD

**Issue by TetraComSA** [frappe/erpnext#11808]
Dears,

I have the attached data that I have it exported from QuickBooks, and I would like to import it into our primary account @ (tetra.erpnext.com). But before importing, I have created a demo account @ (tetra1.erpnext.com) and would like to test the importing process there before having it officially on my primary company.

I was unable to import "Purchase invoice" that has items "Non stock" even all data "Mandatory and non mandatory" were properly filled.

ANY HELP PLZZZ

Regards,
Yahya
[All transactions 28-11-17.xlsx](https://github.com/frappe/erpnext/files/1518008/All.transactions.28-11-17.xlsx)

**Comment by kennethsequeira** [comment]
Hi @TetraComSA, request you to mail this issue to the support team at support@erpnext.com. You can also post this query on https://discuss.erpnext.com/ where you can expect a quick reply from the community members. 
Also, I request you to add screenshots of the error log that is generated which will help us to narrow down on the issue.
