### ISSUE TITLE
Ignore stock check for the service item - Design Level Change

### ISSUE THREAD

**Issue by jigneshpshah** [frappe/erpnext#11806]
#### Expected Behaviour
When a service item is created it should be ignored against stock check.

#### Actual Behaviour
Shopping Portal shows "Not in stock" for service item 
![image](https://user-images.githubusercontent.com/4900815/33367959-40df5344-d516-11e7-954a-f6ffaf14434c.png)

#### Steps to reproduce:

1. Create Service Item
![image](https://user-images.githubusercontent.com/4900815/33368041-7d4d623a-d516-11e7-97c3-5558f5a93298.png)

2.  Allow service item to be shown in website
![image](https://user-images.githubusercontent.com/4900815/33368065-91a6f714-d516-11e7-8dff-5bdc6afd9a69.png)

3. See item on website, it will show as "Not in stock". Stock status should not come for service item.

![image](https://user-images.githubusercontent.com/4900815/33368157-e645cba6-d516-11e7-8b76-8833cbad439d.png)

ERPNext: v9.2.17 (master)

Frappe Framework: v9.2.18 (master)

Discuss Forum Link
 https://discuss.erpnext.com/t/how-to-remove-not-in-stock-or-in-stock-indication-for-a-service-item-in-the-shopping-cart-portal/31127/2

**Comment by JeffKnorr** [comment]
My suggestion would be that if "Maintain Stock" is UNchecked on the Item, that the Stock check shouldn't be performed on the website.  This would also be beneficial for Drop Shipped Items as well as any service items.  I'm very new to ERPNext development.  If someone could help give me a few pointers as to where to make the changes, I'd be able to give it a try. Thanks!

**Comment by jigneshpshah** [comment]
It seems it is addressed in PR  #12294
