### ISSUE TITLE
ERPnext demo - Cannot add items

### ISSUE THREAD

**Issue by rokayattila** [frappe/erpnext#11801]
Hi! I try to create invoices, test the stock function, etc, however I am not able to add any items, so it is not possible to test the functions. I think there is some problems with the runing demo.

**Comment by kennethsequeira** [comment]
Can you give any more details on the issue? Are you running the demo locally? Any error consoles?

**Comment by rokayattila** [comment]
I run the demo here: https://demo.erpnext.com/desk. The item list is empty (https://demo.erpnext.com/desk#List/Item/List) and I am cannot add new ones.

**Comment by kennethsequeira** [comment]
@rokayattila 
![screen shot 2017-11-30 at 6 00 43 pm](https://user-images.githubusercontent.com/33246109/33430961-6fa22d72-d5f8-11e7-813f-78e88a550a8f.png)

The demo version has very few user privileges. It only gives you the look and feel of the system. I suggest you make a trial account on ERPNext cloud which is free for 30 days. Else you can always run it on your local system.

https://erpnext.com/pricing
