### ISSUE TITLE
No means to remove tables in pages

### ISSUE THREAD

**Issue by joolsr** [frappe/erpnext#11809]
Using ERPNext: v9.2.18 (master)
Chromium 62.0, Firefox 57
It is impossible to remove a table that has been added in a page, unless you go into the HTML.

![cannot-remove-table](https://user-images.githubusercontent.com/934876/33447460-4ac135fe-d5fb-11e7-94c7-edd70d1768a2.gif)

**Comment by joolsr** [comment]
I note tables are now not available after refreshing my Communication doctype so i will close this Issue

**Comment by joolsr** [comment]
Confusing I now note that tables cannot be added to emails but are available in the editor in Issues, so will reopen

**Comment by Zlash65** [comment]
![remove-table](https://user-images.githubusercontent.com/11695402/33470239-3e9e4f04-d68d-11e7-805a-ecb1a65038d4.gif)
You can also set the cursor at the end of the table and just hit backspace to remove it.

**Comment by joolsr** [comment]
Hi

When i do the same it doesn't work for me. This is using Chromium

**Comment by joolsr** [comment]
No errors in the console either ...

**Comment by joolsr** [comment]
In FF I can't even position the cursor at the end of the table

**Comment by joolsr** [comment]
When I try the same using demo.erpnext.com I still get the same problem using Chromium. 
![delete-tables](https://user-images.githubusercontent.com/934876/33478712-2dbf9090-d682-11e7-9e45-35821a91fc96.gif)

**Comment by achillesrasquinha** [comment]
Hi, as @Zlash65 has pointed out. Can you move the cursor at first to the rightmost of the table? Try Backspacing twice. What version of Chromium is this. I am able to do this on my local instance and it works fine.

**Comment by joolsr** [comment]
Hi @achillesrasquinha . I've tested it again now and i can remove the table in the manner you describe. Version 62.0.3202.94 (Developer Build) (64-bit)

As such I can delete tables which is good however I do think it should be easier and more obvious on how to do this. But for now I will close this issue. But I am sure it didn't work for me when I tried this a few times last week however ....

**Comment by joolsr** [comment]
Ahh, the difference is hitting backspace TWICE. In the video above I posted I was just hitting backspace the once it seems from looking at it closely
