### ISSUE TITLE
Only Priority Notification Count has to be shown instead of auto-generated notification.

### ISSUE THREAD

**Issue by asharamseervi** [frappe/erpnext#11811]
It is irritating, when Auto-generated comments, in communication, shows up in Notification Numbers. We have to look/checkit at these, to check either some important notification is there or what.

Whenever, some changes in documents or at many points auto-generated comments are generated. In earlier versions, that was not at least visible in Notification Numbers, also we can't delete it. `Sorry! You cannot delete auto-generated comments`

I can see, Improved chat is releasing in next version(v10), it may be considered some tweaks on Communication feature, not to notify in chat for every change. **Only Priority Notification Count has to be shown like Orders, Chat, Errors, Workflows etc, except these documents auto-generated notification.**

![erpnext-communication-improvement-issue](https://user-images.githubusercontent.com/5942572/33451067-bcb60184-d633-11e7-9883-74f7f7002299.PNG)
![erpnext-communi-chat-improvement-issue](https://user-images.githubusercontent.com/5942572/33451076-c6cd0f46-d633-11e7-8cb6-e06433c8a056.PNG)

**Comment by joolsr** [comment]
I have noticed this problem too. I have added the tag CRM as the CRM community team of which I am a member is also looking at fixing some issues relating to email too.
