### ISSUE TITLE
Can't reply inline to an email

### ISSUE THREAD

**Issue by joolsr** [frappe/erpnext#11810]
Using Chromium 62.0
Firefox 57.0
ERPNext: v9.2.18 (master)
Frappe Framework: v9.2.19 (master)

When replying to an email, you can't reply inline as the cursor can't be positioned outside of the quoted section.
Instead you must top post which is not good netiquette and is harder to read a conversation where points need to be addressed inline to an email
![cant-peply-to-email-inline](https://user-images.githubusercontent.com/934876/33448908-2925a782-d5ff-11e7-83fa-56c9d7190522.gif)

**Comment by achillesrasquinha** [comment]
Hi, would like to work on this. I'm not sure whether I clearly understand the issue though. I don't think the same can be done with GMail. Or can we?

**Comment by joolsr** [comment]
Hi @achillesrasquinha 
I use gmail and yes you can reply in inline such as I describe above. 
![peek 2017-12-08 10-10](https://user-images.githubusercontent.com/934876/33761225-23619f8e-dc00-11e7-8dc5-8e70385413f8.gif)

**Comment by joolsr** [comment]
Hi @achillesrasquinha 
Would you be able to look at this again? I'm happy to help explain the bug further if required as it's a serious impediment to a faster workflow.
