### ISSUE TITLE
Batch printing of A/P checks

### ISSUE THREAD

**Issue by cradford** [frappe/erpnext#11814]
If a company processes a significant volume of A/P invoices navigating to each vendor and then selecting the invoices to pay and then printing a check is too time consuming and would preclude ERPNext as a viable ERP solution. I have a client that I'd like to present ERPNext to that generally prints between 200 and 300 checks twice a week.

This process typically starts by entering parameters to indicate the 'due date' through which open invoices should be selected (typically the day before the next check run will occur) and an optional parameter to include whether to base the selection on the 'due date' or the 'discount date' or the earlier of the two. Sometime an option to 'take expired discounts' is also offered.

The next step is to create a temporary file referencing the invoices that meet the criteria.

A report that will list the items and show the total amount that will be paid to each vendor will be required.

The ability to edit the temporary file to reduce the amount to pay or to delete (or set a flag to skip) an invoice to be paid is required.

Situations where open 'debits' more than offset open payables must be handled so as to avoid processing a 'negative' check.

When the payment file has been approved checks should print with an attached remittance advice listing the invoices being paid and the amounts paid and any 'terms' deductions. If there are more invoices being paid than will fit on the attachment the attachment should indicate 'see attached' rather than listing the invoices.

After the checks have printed a second report should list - for each check that showed 'see attached' - all of the invoices being paid in a format similar to that used for the remittance attachment.

My client has had excellent results with using plain 'safety paper' and printing the entire check using a MICR cartridge rather than 'pre-printed' checks which require careful tracking of check numbers.

When all checks and extra remittance advices have been printed the last step is to record all of the checks in the payment journal and to update the invoices with the amounts paid and any discounts taken.

**Comment by agritheory** [comment]
Hey Cy @cradford, we've got this working in a custom app and are planning to contribute it later this summer/ early fall.

**Comment by ghost** [comment]
This is also a deal breaker for us. Is there anything further on this? And could it be incorporated into the core framework?

**Comment by Ponyooooo** [comment]
Is the batch printing of cheques already available in the ERPNext?

**Comment by reubenromandy** [comment]
I am wondering if any progress has been made on this issue, or perhaps it is already available and I'm just not seeing it. I will have to develop this feature for my company if we choose to continue integrating ERPNext and it isn't available. If that happens I will contribute back.

**Comment by emcneal** [comment]
Is there an update on this? It is also very crucial for us as we begin using ERPNext.

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.

**Comment by blewsky** [comment]
Why was this issue closed? It doesn't seem it is solved in v.13.10
Please reopen.

EDIT: Here the discussion on the forum: https://discuss.erpnext.com/t/easier-way-accounts-payable-payment-entry/39006/24
