### ISSUE TITLE
Project Management

### ISSUE THREAD

**Issue by 27ashujain** [frappe/erpnext#11829]
Hi,
In projects I want to create a field "End Date" and it must be mandatorily filled before marking the status of project to completed.
In case i check the box "is mandatory" I will have to fill it in the beginning only, but I want it to be filled compulsorily before completing the project.

**Comment by umairsy** [comment]
You will have to write a custom script to make this field a conditionally mandatory. Please post this query for the forum for further support.

https://discuss.frappe.io
