### ISSUE TITLE
Multiple document print not working

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#11827]
Hello,

Selecting multiple documents to print generates a pdf with the multiple blank pages with {{ body }}

I've tested with production order (default print format and custom) and sales orders, but I think other documents may be affected.

<img width="1404" alt="screen shot 2017-12-01 at 4 05 22 pm" src="https://user-images.githubusercontent.com/18335894/33496513-a6cc0e80-d6b1-11e7-9d53-fbd443538aef.png">

**Comment by umairsy** [comment]
It works fine in my test account. Are you facing this issue for the custom print format or the standard? Is this a standard doctype or custom made?

**Comment by applepipe** [comment]
Hello @umairsy 

I'm facing this issue with the custom format and the standard, it is a standard doctype.

wkhtmltopdf version is 0.12.4

**Comment by applepipe** [comment]
Hello @umairsy, I've forgot to mention that I'm testing the developer branch

ERPNext: v9.x.x-develop (a263ff2) (develop)
Frappe Framework: v9.x.x-develop (eb2c775) (develop)

**Comment by applepipe** [comment]
@umairsy 

I've checked the host_name in the site config, its configured to https://localhost, but 
I've tried without the S, and with the local network address, but no luck.

Any hint where I can look to try and solve this?
