### ISSUE TITLE
Invalid return against purchase invoice Error

### ISSUE THREAD

**Issue by vwithv1602** [frappe/erpnext#11834]
While making a return in Purchase Invoice the following error is thrown.

![image](https://user-images.githubusercontent.com/29653756/33527349-0568f9ca-d875-11e7-926a-af50012519a0.png)

**Comment by tundebabzy** [comment]
Hi. Please give more information

**Comment by vwithv1602** [comment]
My bad. Raised this issue just in case my pull-request got rejected and also thinking that it might help others when they search for the same..

**Pull request**: https://github.com/frappe/erpnext/pull/11835
**Commit**: https://github.com/vwithv1602/erpnext/commit/7241d18d71ad3a68de77c6726646312ad3310c1e
**Forum Topic**: https://discuss.erpnext.com/t/return-debit-note-in-purchase-invoice-error/30878

Need to close after pull request (#11835) got approved.
