### ISSUE TITLE
FETCHING DATA FROM ADDRESS TEMPLATE TO SALES INVOICE PRINT FORMAT

### ISSUE THREAD

**Issue by janmoravecfw** [frappe/erpnext#11851]
Hi everyone, 

yes, I know, this is the point which has been discussed here for a long time. But I tried to solve it without success. I have a custom field "ico" under the Contact module - setup - address template, Here is only one template for Czech Republic where we need to print TaxID and Company identification number also.
I made change of code in address template:
 
{{ address_line1 }}<br>{% if address_line2 %}{{ address_line2 }}<br>{% endif -%}{{ city }}<br>
{% if state %}{{ state }}<br>{% endif -%}
{% if pincode %}{{ pincode }}<br>{% endif -%}
{{ country }}<br>
{% if phone %}Phone: {{ phone }}<br>{% endif -%}
{% if fax %}Fax: {{ fax }}<br>{% endif -%}
{% if email_id %}Email: {{ email_id }}<br>{% endif -%}
{% if ico %}IČO: {{ ico }}<br>{% endif -%}

Then I would like to fetch or view the ICO in the print format of the sales invoice. I made my own print format where I'm trying to display the whole address with ICO number but without success. If I display the address of customer, the ICO number is not here, still missing.

Please help me, thank you.

**Comment by kennethsequeira** [comment]
Hi, request you to post this issue in the discuss forum https://discuss.erpnext.com since it's more functional in nature. However, in case you feel to reopen the issue, do go comment again.
