### ISSUE TITLE
Serial Number and Batch Number Labels

### ISSUE THREAD

**Issue by ddavidebor** [frappe/erpnext#11852]
The following issue, which I plan to address is to:

- Add a page format compatible with ever-present and cheap dymo labelwriter 450 label printers
- Add a custom print template for serial numbers and batch number to be printed on adhesive label

The reason is the following: 

When you manufacture a product with individual serial numbers, you generally want to stick a label with it somewhere. The templating functions are pretty great.

Not sure if and how barcodes/qcode generation could be implemented... 

Davide

**Comment by elvise** [comment]
+1

**Comment by ddavidebor** [comment]
@elvise ideas, requirements or hands welcome

**Comment by ddavidebor** [comment]
A few notes: 
* implementing the barcode is astonishingly easy with JsBarcode. 
* the page format cannot be specified manually. 

Not sure how to make a standard enough format to be good for a PR. For now I am working on two:
1. Warehouse label format
2. product label format

The first is to be applied to the outside of the box. has more information and two barcodes: one for the item name, one for the item serial number. All the barcodes can be read with a 2D barcode reader. It also has manufacturing date and time (or will, after #11914 is fixed)

The second is to be applied to the product: it's smaller, cuter, and has a QR code (smaller footprint) that nowadays everybody knows can be read with a smartphone.

**Comment by ddavidebor** [comment]
I am closing this because for this to work decently it would require multiple page formats to be selectable on a per-print or per-template bases

**Comment by fthobe** [comment]
@ddavidebor Hey, we managed to find a workaround using the Dymo Web SDK 
https://github.com/riCompro/Dymo-Web-Label-Printer

You can print labels fetching via scripts the parameters you want to print on a label.

**Comment by fthobe** [comment]
@jaichavan Hey, maybe this can be implemented? It's straight HTML and jscript.
