### ISSUE TITLE
Selecting Parent Item group doesnt load child group Items

### ISSUE THREAD

**Issue by adam-je** [frappe/erpnext#11859]
In stock summary and POS (AFAIK) and probably other features. Selecting one Item Group does not load contents of child item groups. I think it should. E.g. 

All Items groups
- Metals - is group
 -- Cups
 -- Plates
- Plastics - is group
  -- Spoons
  -- Cups2

Selecting **plastics** will not load contents of **Spoons or Cups2**. I have to manually check subgroups.

**Comment by umairsy** [comment]
For now, you should select specific Item Group (child) to have item's item loaded. For the feature of filtering items based on Parent Item group, please check following Github Issue.

https://github.com/frappe/erpnext/issues/11055
