### ISSUE TITLE
doc status not changed automatically when reply

### ISSUE THREAD

**Issue by omnison** [frappe/erpnext#11854]
![2017-12-05 10 19 51](https://user-images.githubusercontent.com/7886153/33592807-131372b2-d9a6-11e7-95b5-ad694b9bf9eb.png)

I found, my erpnext, the status cannot be changed automatically when replied.

**Comment by achillesrasquinha** [comment]
Hi, which version is this on? Unable to replicate the error.

**Comment by omnison** [comment]
Installed Apps

ERPNext: v9.2.19 (master)

Frappe Framework: v9.2.20 (master)

mankem: v0.0.1 (master)

**Comment by achillesrasquinha** [comment]
This isn't a bug actually, there are cases where not all would prefer automatic updates within the internal organisation. We had this before but it has been removed for now. What can be done is have a configuration elsewhere than helps you automatically update.

For now, having this closed. Feel free to reopen or open a discussion at discuss.erpnext.com
