### ISSUE TITLE
Not allowing change in password

### ISSUE THREAD

**Issue by SonalR** [frappe/erpnext#11869]
Messages I get when I try. Have to log in using forgot password every time

<img width="1440" alt="screen shot 2017-12-07 at 12 35 22 pm" src="https://user-images.githubusercontent.com/4785299/33702839-562c77fa-db4b-11e7-8623-36ee370d706d.png">

<img width="1440" alt="screen shot 2017-12-07 at 12 35 00 pm" src="https://user-images.githubusercontent.com/4785299/33702847-66c0f1b8-db4b-11e7-890a-d0900028c700.png">

**Comment by kennethsequeira** [comment]
Can you create a gif of how this is occurring?

**Comment by SonalR** [comment]
here....https://giphy.com/gifs/3oxHQCQlk2yzaDa25y/html5

**Comment by kennethsequeira** [comment]
Following it up on mail.
