### ISSUE TITLE
[BUG] Customer General ledger total missing

### ISSUE THREAD

**Issue by vladucoju** [frappe/erpnext#11866]
Hello,

on latest update i noticed that on general ledger is mising total. Please someone fix this.
![capture](https://user-images.githubusercontent.com/9590909/33660234-714034be-da83-11e7-9e79-5e7ffdd99cca.JPG)

**Comment by vladucoju** [comment]
Closing (Opening + Total) not translated on other languages. It is shown on english only.

**Comment by kennethsequeira** [comment]
@vladucoju can u confirm if this is the exact same problem as #11893 
if so you can follow that thread for updates and we can close this. You can also move your language issue to the same thread.

**Comment by vladucoju** [comment]
Yes, that is the same problem. You can close this thread.

**Comment by kennethsequeira** [comment]
Closing this issue. If you feel it needs to be reopened in the future, feel free to comment.
