### ISSUE TITLE
Stock Ledger Report Issue

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#11871]
Hi,

I'm facing an issue in my account where the Stock Ledger Report is not returning any data even though there are stock ledger entries. I have two companies setup in the account but this issue only affects one of them! I've checked permissions and everything seems to be in order. There are no restrictions showing at the bottom of the page and there are no errors in the console log

![stock ledger report issue 01](https://user-images.githubusercontent.com/9269337/33705992-c2246eb8-db32-11e7-81fb-fe952b8fe003.png)
![stock ledger report issue 02](https://user-images.githubusercontent.com/9269337/33705995-c3aaa8ba-db32-11e7-8d76-784f707338cb.png)

Please help with this

Thanks

**Comment by Zlash65** [comment]
Did you check the date format in the "System Settings" of erpnext ? I was able to replicate it too and it turned out the date were actually in mm-dd-yyyy format which made the between dates reversed and hence was unable to fetch any data. Check the date format and try re-applying filters properly.

**Comment by Olawale1** [comment]
Hi @Zlash65 

Thanks for the suggestion but the date format is actually correctly set as dd-mm-yyyy. There are 2 companies setup in the account and the other one works fine!

Kind regards,

**Comment by umairsy** [comment]
Can you please check the status of Stock Ledger entries, just to check if they are not submitted?

**Comment by Olawale1** [comment]
Hi @umairsy 

Thanks for your response. They are not cancelled and there are thousands of entries for that company!

**Comment by Olawale1** [comment]
I also tried updating to the latest version yesterday but it's still the same

**Comment by Olawale1** [comment]
Hi @umairsy  

I just made some more discoveries which may be linked to this issue. I observed that the last Stock Entry (Material Receipt) created for this company did not have any accounting ledger postings created even though it was submitted! Upon further investigation, I noticed that no serial numbers were created for any of the items received even though they are all serialized items!

I tried cancelling and amending but still the same outcome... no accounting entries and no serial numbers created. I then created a new Stock Entry with one serialized item and submitted it. The accounting entry was generated but no serial number created (even though a pop-up message said it had been created!)

Any ideas what's going on here please?

Thanks

**Comment by Olawale1** [comment]
Hi @umairsy 

Thanks a great deal for your help. The permissions somehow got changed after the update. I’ve updated them and the Ledger is visible now

Thanks again!
