### ISSUE TITLE
Failed switching to payment entry from paid expense claim form via View->Bank Entries

### ISSUE THREAD

**Issue by szufisher** [frappe/erpnext#11872]
Steps to reproduce the error
1. set up the default account for a expense claim type
2. create a new expense claim, choose your own user account as approver, then SAVE, select Approved as approve status, click submit
3. click make payment button, input reference, and date, save and submit the payment
4. go back to the expense claim form, reload the page, the expense status is paid now, then click view->Bank entries button
5. system routed to journal entry/list instead of payment entry/list which failed switch to the desired payment entry

Here the extracted code from /erpnext/hr/doctype/expense_claim/expense_claim.js line 87 ~ 95
if (cint(doc.total_amount_reimbursed) > 0 && frappe.model.can_read("Journal Entry")) {
				cur_frm.add_custom_button(__('Bank Entries'), function() {
					frappe.route_options = {
						"Journal Entry Account.reference_type": me.frm.doc.doctype,
						"Journal Entry Account.reference_name": me.frm.doc.name,
						company: me.frm.doc.company
					};
					frappe.set_route("List", "Journal Entry");
				}, __("View"));

need to be changed as 
			if (cint(doc.total_amount_reimbursed) > 0 && frappe.model.can_read("Payment Entry")) {
				cur_frm.add_custom_button(__('Bank Entries'), function() {
					frappe.route_options = {
						"Payment Entry Reference.reference_doctype": me.frm.doc.doctype,
						"Payment Entry Reference.reference_name": me.frm.doc.name,
						company: me.frm.doc.company
					};
					frappe.set_route("List", "Payment Entry");
				}, __("View"));

already successfully tested in my own site www.erpnext.xin

as I am not real developer, have almost no successful experience contribute code via Github, can anyone help to do the pull?

**Comment by umairsy** [comment]
Issue replicating.

**Comment by shreyashah115** [comment]
@umairsy Fixed via #11874
