### ISSUE TITLE
Multiple Payroll Currencies

### ISSUE THREAD

**Issue by mafrica** [frappe/erpnext#11877]
We like many international companies we pay local staff in local currency and secondees in USD.  While ERPNext has general features for multi-currency handling it lacks the the ability to produce a salary slip in anything other than the default company currency. Can this please be rectified.

**Comment by peshgathoni** [comment]
@mafrica , how did you go about this issue ? Any workaround ?

**Comment by kennethsequeira** [comment]
Added in v13.
