### ISSUE TITLE
Shopify ERP sync issues

### ISSUE THREAD

**Issue by Nehamirpuri** [frappe/erpnext#11884]
As you are aware we are one of the Shopify and ERPNext user,below is list of daily challenges faced (majority is sync related )

Post Sync - ERP

Post the sync of items from ERP to Shopify being performed, we consistently notice the following non-shopify fields in ERP are getting incorrectly updated by the sync. The following field are getting replaced with inaccurate data causing a lot of extra manual work (i.e. update the field back to original field data pre-sync).Examples of such fields in ERP are:-
a) Default warehouse.
b) Default supplier
c) Custom fields created by us in the item master.
We require only the shopify to be updated and not the ERP (if not related to sales orders executed via the web).

Hide items with Qty <=0 - same as stated by bglazier

Post Sync - Shopify

An item on being synced in the first instance gets reflected in shopify accurately. But post the occurence of multiple ERP-shopify syncs through the day,its observed that additional unwanted images get added to the shopify item within the master and it requires for manual intervention by way of review of all items for the identification of additional images and manual deletion of unwanted images linked to the shopify item.

Shopify has “compare at field” for prices where it shall show discounted price and original price,this has to be updated manually as this field does not exists in ERP making it very tedious.

3.Shopify has filter tags (based on design,shade,fabric type etc.)which helps the customer to identify products. Currently these have manually inserted into shopify at an item level as there is no option to add tags(which need to be reflected in shopify) at an item level in ERP and have the tags automatically reflected in shopify post sync.Refer to https://boacasa.com for examples for kind of tags.

4.Shopify has collection field in which one manually updates the name of the product category (under which the products are displayed in the website).Currently this needs to done manually in shopify item master post syncing.Require for this field to be reflected in ERP,so no manual updates to be done post sync.

Attached is the shopify image highlighting (above items 1-4).
![2017-11-27 1](https://user-images.githubusercontent.com/10804667/33754165-fd9cd410-dc10-11e7-8f2e-584444ad36c3.png)

**Comment by Nehamirpuri** [comment]
@umairsy : Hi umair what is the udpate on this github issue created?

**Comment by Nehamirpuri** [comment]
@jaichavan : Hi Is there any link you can provide where I can check the enchanments done?

**Comment by jaichavan** [comment]
@Nehamirpuri Yes, here you go:

https://erpnext.com/docs/user/manual/en/erpnext_integration/shopify_integration
