### ISSUE TITLE
[V10] Payment Entry Term not selectable in the Sales Invoice

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#11888]
Steps:

1. Created Payment Term
2. Create Payment Template
3. Tried selecting Payment Template in the new Sales Invoice 

![screen shot 2017-12-08 at 3 50 16 pm](https://user-images.githubusercontent.com/910238/33761586-98960c7a-dc2f-11e7-9306-e97edfc67259.png)

As a new user, I found it difficult to understand the difference between Payment Term and Payment Term Template. Also, in the Payment Entry Template, validation on the Due Date at each row should be validated in front-end, while data entry itself.

Payment Term should show option to create Payment Term Template against it.

**Comment by nabinhait** [comment]
fixed via https://github.com/frappe/erpnext/commit/d10014bdebc3df0a7000babb981882d6793ccdc2
