### ISSUE TITLE
Error when click on Update button

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#11899]
Steps:

1. Created Sales Invoice
2. Created Payment Entry
3. Came back to Sales Invoice

In the Sales Invoice, it shows Update button. But when click on Update button, shows an error message.

![update](https://user-images.githubusercontent.com/910238/33765368-870ca842-dc3e-11e7-8381-8ebcffd4636b.gif)

Should it recall Reload function? If I just Reload manually (from Menu), then value is updated correctly.

**Comment by nabinhait** [comment]
The problem is the form gets **dirty** when we come back to the form from any other form.

**Comment by tundebabzy** [comment]
Yes. The payment schedule table is the problem. It seems a new one is created after clicking the browser back button.

**Comment by nabinhait** [comment]
@tundebabzy Is it? I thought it is a generic problem with any form.

**Comment by tundebabzy** [comment]
Actually, not really the back button. See this gif

![peek 2017-12-20 11-33](https://user-images.githubusercontent.com/818803/34203175-717a6b00-e57a-11e7-9537-2f4a16dd30a0.gif)
