### ISSUE TITLE
Add Row in General Ledger Report

### ISSUE THREAD

**Issue by PrakashH** [frappe/erpnext#11893]
Add Row in General Ledger Report to show the closing balance equal to Total Debit - Total Credit or Total Credit - Total Debit.  

Now

![screen shot 2017-12-08 at 4 31 34 pm](https://user-images.githubusercontent.com/4570016/33763289-e9a5129a-dc35-11e7-990a-aa4a875b9caf.png)

Before

![screen shot 2017-12-08 at 4 32 46 pm](https://user-images.githubusercontent.com/4570016/33763304-f52ece44-dc35-11e7-8cde-94e7335658ca.png)

**Comment by vladucoju** [comment]
I created issue for the same problem #11866 
Hope this will be fix soon. This is very important view.
