### ISSUE TITLE
[V10] Delivery Trip - UI suggestions

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#11890]
**Fulfillment User Role**

 New Role called Fulfillment User is added. Only this Role has Permission on Delivery Trip doctype. Initially, a standard role like Stock User and Manager should also have permission on Delivery Trip DocType, so that they can easily discover this feature. Also, Fulfillment User's role should be auto-assigned to user (?) based on some existing roles assigned.

**Delivery Note Selection**

In the Delivery Trip, Delivery Note selection should be mandatory.

Also, there should be an easier way for selecting Delivery Note in the child table. Perhaps a selection option from modal like this.

![screen shot 2017-12-08 at 4 05 51 pm](https://user-images.githubusercontent.com/910238/33762536-d02e36be-dc32-11e7-9567-c2235bc4530f.png)

Currently, selection of Delivery Note is under child table of Delivery Trip, that too in the end, with no intuitive UI.

**Comment by itsyogesh** [comment]
Hey @rohitwaghchaure @nabinhait, I created something called [Projectwise](https://projectwise.in). Its a platform for open-source projects to find design help. Can I add the repo in the list of projects that require design help ?
