### ISSUE TITLE
Item - Template Item Creation - Table to select Attributes not visible

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#11894]
1. I created a new Item from the Quick View. But Quick View doesn't have the option to specify Item as a template Item.

2. In enabled "Template Item" from the Form View of Item master.

3. On checking "Has Variants" field, another field called "Variant Based On" is shown, but not editable. It has the default value as "Item Attribute". This field is not editable because property "Set Only Once" is checked for it.

4. The child table for selecting Item Attributes is also not visible, because:
4.1 Property Hidden is checked for child table "attributes". This property should not be checked.
4.2 Property "Set Only Once" is also checked

![screen shot 2017-12-08 at 4 50 21 pm](https://user-images.githubusercontent.com/910238/33763810-ef4eaec0-dc37-11e7-80a9-91407a5dd906.png)

Because of this issue / workflow, user is not able to select value in the field Variant Based On and Attributes (table). However, if user creates new Item from the Form view only, then it works just fine.

**Comment by pratu16x7** [comment]
So we've thought of a workaround for this, that by default, we'll have the decisive checkboxes of whether it's a batch item, serialised item or and valuation method in the default case that 'Maintain Stock' is checked initially. If it is unchecked on purpose, then in this case we have the other restriction checks of whether it is an asset or template. In case of template, we ask the user to edit in full page.

**Comment by pratu16x7** [comment]
Update:

We have a very meaningful limit set within any quick entry:
<img width="467" alt="screen shot 2017-12-23 at 1 26 39 am" src="https://user-images.githubusercontent.com/5196925/34310984-8ee6dbb2-e780-11e7-8680-c1a28a055339.png">

It is important to stick to it for consistency from a UI point of view. Overriding it in the item dialog with the additional fields caused the model to lengthen beyond viewport, defeating the purpose of 'quick':
<img width="1047" alt="screen shot 2017-12-23 at 1 34 39 am" src="https://user-images.githubusercontent.com/5196925/34311104-82fe0e8c-e781-11e7-921b-f2e257bc4149.png">

As we should be including all or no affected fields, I think the best solution would indeed be to let the users edit in the form by default for all one-time features, at least until we can recreate all of the form's behaviour in quick entry: https://github.com/frappe/frappe/issues/4673

The 'Edit in full page ...' button at the bottom is quite clear on this. Let's prefer the full form for now.
