### ISSUE TITLE
ERPNext User Manual - Sales Person Target Allocation Gif Not Viewable

### ISSUE THREAD

**Issue by kennethsequeira** [frappe/erpnext#11903]
https://erpnext.org/docs/user/manual/en/selling/setup/sales-person-target-allocation

1.3 Target Distribution gif is not viewable

https://erpnext.org/docs/assets/im/selling/sales-person-target-distribution.gif

Gif present here 

https://github.com/frappe/erpnext/blob/develop/erpnext/docs/assets/img/selling/sales-person-target-distribution.gif

Second non viewable image

https://erpnext.org/docs/assets/img.selling/erpnext/target-distribution.png

**Comment by umairsy** [comment]
Fixed. Consolidated PR coming soon.
