### ISSUE TITLE
Multiple branches in School

### ISSUE THREAD

**Issue by ajinkyagadewar** [frappe/erpnext#11909]
Hello:

How can we configure school for multiple branches/schools with a feature to transfer student from one branch to another branch?

**Comment by manassolanki** [comment]
If you want to implement the different company structure, that feature is not currently in the ERPNext Education. But you can create the Student Batch name for every branch and can create the student groups. Now if you want to change the branch of any student you only have to change the Batch of that student in the program enrollment.

For more functional queries, please post on discuss.
https://discuss.erpnext.com/c/schools
