### ISSUE TITLE
Add custom html column and cell to table print

### ISSUE THREAD

**Issue by ddavidebor** [frappe/erpnext#11915]
While implementing some barcode functionality I hit a roadblock.
There is currently no way of making custom cells in the tables when printed. Only the columns can be selected:

![image](https://user-images.githubusercontent.com/9055742/33800064-45e6d350-dd39-11e7-982b-46b494fd49cc.png)

It would be of great aid if there was a way to add custom column with a jinja2  template. This would allow to implement a barcode print of a field of every line extremely quickly.

This is already possible for any type but the table.

```
<svg class="barcode"
  jsbarcode-format="auto"
  jsbarcode-value="{{item.barcode}}"
</svg>
```

**Comment by taha-azzan** [comment]
Try This Code, May Helps You.


<tr>
<td width="5%"  style="background: #D9D9D9">No.</td>
<td width="15%" style="background: #D9D9D9">Item Code</td>
<td width="25%" style="background: #D9D9D9">Description</td>
</tr>

{%- for row in doc.items -%}

<tr>
<td width="5%" >{{row.idx}}</td> 
<td width="15%">{{row.item_code}}</td>
<td width="25%">{{row.description}}</td>
</tr>

{%- endfor -%}



Description:
* {%- for row in doc."name of the table" -%} 

* {{row."name of the row in table"}} 



BR

**Comment by ddavidebor** [comment]
Hi, thank you very much.
