### ISSUE TITLE
Item Barcode field getting copied.. even when no value is added

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#11918]
Steps:

1. I created Template Item. No value in the Barcode field.
2. Then I tried creating Variant against a Template. It is showing this validation message.

![screen shot 2017-12-11 at 10 40 29 am](https://user-images.githubusercontent.com/910238/33816632-41b1ec84-de60-11e7-8265-c6c4920fae93.png)

Seems like it is trying to generate barcode for the null value as well? Just a hint.

**Comment by pratu16x7** [comment]
Had been due to customised field instead of type "Data".
<img width="663" alt="screen shot 2017-12-11 at 12 23 46 pm" src="https://user-images.githubusercontent.com/5196925/33819036-3eea9db2-de6e-11e7-8d77-af964bd29393.png">
