### ISSUE TITLE
Add new line when pressing two times "enter"

### ISSUE THREAD

**Issue by ddavidebor** [frappe/erpnext#11913]
In a item field, like the one in the image:

It would be nice if pressing two times **enter** a new line would be created. I understand pressing it one time is to confirm an input in an interactive field. But in any keyboard the **tab** key (used for this feature now) is on the top left corner, while the number pad (used to input the quanitites) is on the right side.

If this feature were to be added, the following workflow could be used:
* click the first item field
* enter barcode
    * the barcode reader automatically presses **enter** or **tab**, depending on configuration. item is thus confirmed
* user enters quantity with the number pad
* user confirm quantity with **enter** on the number pad
* user adds a new line with **enter** on the number pad, second click

![image](https://user-images.githubusercontent.com/9055742/33799086-e87db260-dd24-11e7-8198-535b8267a956.png)

**Comment by tundebabzy** [comment]
Nice. I really really think this would greatly improve the user experience particularly in speed of data entry.
@ddavidebor , I have to close this because this actually belongs in Frappe repo. Can you open it there instead? Sorry for giving you extra work to do. :)

**Comment by ddavidebor** [comment]
https://github.com/frappe/frappe/issues/4600
