### ISSUE TITLE
Stock Receipt allowed at zero valuation

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#11920]
1. When we create a new Stock Entry (Material Receipt) and select a warehouse where the item has not been received previously, the valuation rate is not fetched!

2. Also, in the scenario above, we are still able to submit the Stock Entry with zero value without selecting the 'Allow Zero Valuation Rate' option.

![screen shot 2017-12-11 at 11 22 09 am](https://user-images.githubusercontent.com/910238/33817464-bfb8daca-de65-11e7-83a9-aeeceba986c6.png)

**Comment by nabinhait** [comment]
its not a bug, same workflow is there for current version as well. If "Allow Zero Rate" is not check, system sets incoming rate from historical SLE or Item master or buying Price List. If not find anywhere it give a validation message.

**Comment by umairsy** [comment]
Valuation rate was not found in the Item or historical SLE as well. As indicated in the screenshot, no valuation or basic rate fetched whatsoever.
