### ISSUE TITLE
Support/improve multiple branches in ERPNext

### ISSUE THREAD

**Issue by sathishpy** [frappe/erpnext#11926]
Currently ERPNext has a Branch doctype in Human Resource module, which isn't really ideal to setup multiple branches of a company.  Concept of branch in HR is needed, but it is for a different purpose. Like a company might have multiple groups of employees like HR, finance, logistics etc. Here department is perhaps better suited word than branch. In order to support the concept of multiple branch offices, we need a new doctype called 'Company Branch' or 'Branch Office' in Accounts module. The existing doctypes 'Cost Center' and 'Warehouse' should have this additional attribute of branch along with Company.

These changes will allow adding a new field called Branch Office for 'Sales Invoice', 'Purchase Invoice/Receipt' and 'Journal Entry'. By default, all the items in these doctypes will be set to the cost center and warehouse of the specified branch. However it still retains the ability to change warehouse/cost center at individual item level.  Optionally, we could collapse the branch section by default and show it only when there are more than one branch office configured.

**Comment by olamide2** [comment]
We could also include the idea of assigning users to branches

**Comment by sathishpy** [comment]
True. Perhaps we should look at making the 'branch office' as an mandatory field where ever we have the company field. When the initial company is setup, it should automatically create the 'Main' branch similar to main cost center. By default everything will automatically map to the 'Main' branch of the company. However when a new branch is setup, we have the option to change the branch to doctypes like warehouse, cost-center, invoices, purchase receipt, journal entry and employees/users. Not sure whether this will make it easier to create all the accounting reports like 'general ledger' filter transactions based on 'branch office'

**Comment by olamide2** [comment]
This is not a bad idea at all
