### ISSUE TITLE
Improve Validation Message in the Payroll Entry

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#11937]
![screen shot 2017-12-11 at 6 16 56 pm](https://user-images.githubusercontent.com/910238/33831807-9172bee4-de9f-11e7-871b-1d280054e404.png)

**Comment by tundebabzy** [comment]
It's actually an error message. I could change the wordings to a slightly longer, possibly more explanatory sentences.

**Comment by tundebabzy** [comment]
#11944
