### ISSUE TITLE
Payroll Entry

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#11936]
Provide Payroll Entry status in the indicator

1. Salary Slip in Draft
2. Salary Slip Submitted
3. Bank / Payment Entry pending
4. Bank Entry Completed, or just Payroll Completed

In the Toolbar button, make next step button as Primary, if possible. Currently, it doesn't give a starting point.

![screen shot 2017-12-11 at 6 06 15 pm](https://user-images.githubusercontent.com/910238/33831685-05670b08-de9f-11e7-8d3d-66d8c4fbe899.png)

If Salary Slip submission fails, then validation first indicates about email not being sent, and then shows error message related to the failure of the Salary Slip submission. The cause of the Failure should be shown up in the order. Maybe email related validation should be shown after Salary Slip is submitted Successfully.

![screen shot 2017-12-11 at 6 07 48 pm](https://user-images.githubusercontent.com/910238/33831726-392cc8ec-de9f-11e7-8555-c02a8092ba1f.png)

**Comment by tundebabzy** [comment]
#11968
