### ISSUE TITLE
Can't make a sale with POS

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#11940]
Hello,

After last updated the error opening the POS was fixed, but when I try to make a sale (select item after selecting customer), the screen becomes grey and the console shows this error:

<img width="571" alt="screen shot 2017-12-11 at 1 39 45 pm" src="https://user-images.githubusercontent.com/18335894/33839294-f0e3926c-de78-11e7-98f9-b1821ee4e6f7.png">

**Comment by rohitwaghchaure** [comment]
Hi @applepipe 

I am trying to replicate the issue on local account but not able to replicate it.
The error showing on the console log is not related to POS, so this is not an issue. Can you check the server error log? If you're using production account please check web.log and web.error.log under folder frappe-bench/logs

run command tail -f web.error.log to check error under log

**Comment by tundebabzy** [comment]
It seems that for some reason, the POS can't fetch item images. That shouldn't cause the page to stop building right?

**Comment by rohitwaghchaure** [comment]
@tundebabzy 

Issue is not with the item image, I think there is some issue with the server side and it's not showing in the console log

**Comment by applepipe** [comment]
hello @rohitwaghchaure,

here is the output of tail -f web.error.log 
[2017-12-12 09:56:03 +0000] [1523] [INFO] Listening at: http://127.0.0.1:8000 (1523)
[2017-12-12 09:56:03 +0000] [1523] [INFO] Using worker: sync
[2017-12-12 09:56:03 +0000] [1627] [INFO] Booting worker with pid: 1627
[2017-12-12 19:51:15 +0000] [1523] [INFO] Handling signal: term
[2017-12-12 19:51:15 +0000] [1627] [INFO] Worker exiting (pid: 1627)
[2017-12-12 19:51:15 +0000] [1523] [INFO] Shutting down: Master
[2017-12-12 19:51:47 +0000] [1522] [INFO] Starting gunicorn 19.6.0
[2017-12-12 19:51:47 +0000] [1522] [INFO] Listening at: http://127.0.0.1:8000 (1522)
[2017-12-12 19:51:47 +0000] [1522] [INFO] Using worker: sync
[2017-12-12 19:51:47 +0000] [1626] [INFO] Booting worker with pid: 1626

**Comment by rohitwaghchaure** [comment]
@applepipe 

Goto pos page and when screen freeze, run command on server tail -f web.error.log and check web.log tail -f web.log.
Also check is there any error log related to pos.

**Comment by applepipe** [comment]
@rohitwaghchaure 

The command was run after the screen freezes, I ran the same command again and the output is the same, on the web.log I can't see no errors related to POS, no lines are added after the screen freezes.

**Comment by rohitwaghchaure** [comment]
@applepipe 
OK thanks for the details, the selected item has batch or serial no?

**Comment by applepipe** [comment]
@rohitwaghchaure 

no batch or serial, I saw the issue 11999 but in my case I can't select the item, even if it has no picture

**Comment by rohitwaghchaure** [comment]
@applepipe 

Do you have any customisations on sales invoice or pos?

**Comment by applepipe** [comment]
@rohitwaghchaure 

No customizations on POS, but I have some customizations on sales invoice, custom fields and custom scripts, the invoice itself works fine

**Comment by applepipe** [comment]
tested now and with the last update the error was solved
