### ISSUE TITLE
Full screen mode when editing only makes window taller not wider

### ISSUE THREAD

**Issue by joolsr** [frappe/erpnext#11942]
Using demo.erpnext.com
ERPNext: v9.x.x-develop (02ac901) (develop)
Frappe Framework: v9.x.x-develop (ec33e82) (develop)
Chromium Version          62.0.3202.94 
Firefox                             57.0.1

**To replicate**
On an opportunity, Click 'New Email' (Reply to email gives the same problem too)
Wish to use full screen mode to edit an email.
Click the full screen button in the editor toolbar
This problem is also seen on the Issues.

The window lengthens, but does not widen. This used to work and provide true full screen editing capability. Perhaps it should also be in one of the unit tests ? I note that for other screens such as To do that using the full screen button does provide full screen editing. Likewise on some modal views there is a 'Edit in Full page' link which works fine too. Perhaps the emails creation view should have this too?

![full-screen-email](https://user-images.githubusercontent.com/934876/33845270-cc348bd4-de9a-11e7-8e54-bf1169d24591.gif)

**Comment by rmehta** [comment]
There is an ideal for reading text. Reading very wide text is cognitively harder to the human eye as you have to scan left to right.

Also in the world of 140 characters, we should not encourage long emails. No one reads emails longer than 5 sentences anyways.

https://lifehacker.com/280193/limit-your-email-messages-to-5-sentences
https://guykawasaki.com/the_effective_e/
https://www.themuse.com/advice/are-your-emails-too-long-hint-probably

**Comment by joolsr** [comment]
I appreciate your explanation Rushabh

But something that you haven't taken into account is when you have a long email conversation with customers. The usability gets degraded as you have to scroll up and down the screen much more than you should with just a very narrow modal view ...

**Comment by achillesrasquinha** [comment]
That modal is surely small sized, forget normal. Lol.

**Comment by karlosTM** [comment]
How do you get the full screen option at all? 
I use v14 and it doesn't show at all. Would love to have it as an option, even if limited width.

![image](https://github.com/frappe/erpnext/assets/74450285/ba26408d-5d63-4004-a7c8-6b1146638b97)
