### ISSUE TITLE
feature request to add Modification of ERPNEXT to support the Engineering Procurement and Construction Management (EPCM) Market

### ISSUE THREAD

**Issue by draedonconsulting** [frappe/erpnext#11945]
I am currently in the process of adding new doctype and reports to ERPNext as well as additional fields to existing doctypes to support common processes and procedures employed by the EPCM (Engineering Procurement Construction Management) market. I will be building upon the existing Projects module to add EPCM style Project Controls budgeting and forecasting, material expediting and material availability forecasting.

The project controls changes will add the following doctypes; Control Package, Execution Package, Control Account, Work Package, Cost Type, WBS, Sub Project, Project Change Notice and Project Change Notice Details.

I will also be making the “Project” link in the Material Request Item doctype an enterable field. Currently it is set as readonly.

The Material Request and Purchase Orders will need to have a discipline field added plus their respective detail doctypes will need to reference the new Control Account doctype.

I am looking for help to ensure I am following the ERPNext contribution procedures.

Do I need to request a feature to get the ball rolling? I am already working in development mode and have the Project Controls doctype already created.

**Comment by kennethsequeira** [comment]
@Zlash65

**Comment by draedonconsulting** [comment]
Will have to recreate a development environment and recreate the doc types.  Any best links for setting up a new fresh erpnext development server.  Looking to use a vm

**Comment by rmehta** [comment]
@draedonconsulting sorry for the late reply but you can use docs at https://frappe.io/docs
