### ISSUE TITLE
Data Import Tool issue

### ISSUE THREAD

**Issue by vwithv1602** [frappe/erpnext#11954]
I’ve downloaded Item Attribute (with data containing default attributes - color,size) and tried to upload the same file without changing anything. I got the below error.

> {u’item_attribute_values’: [{u’attribute_value’: u’Green’, u’parenttype’: u’Item Attribute’, u’parentfield’: u’item_attribute_values’, u’abbr’: u’GREEN’, u’doctype’: u’Item Attribute Value’}]}
desk.min.js?ver=1512993594.0:1701 Traceback (most recent call last):
File “/home/vamc/frappe-bench/apps/frappe/frappe/core/page/data_import_tool/importer.py”, line 324, in upload
validate_naming(doc)
File “/home/vamc/frappe-bench/apps/frappe/frappe/core/page/data_import_tool/importer.py”, line 179, in validate_naming
autoname = frappe.get_meta(doc[‘doctype’]).autoname
KeyError: u’doctype’

I'm using the latest versions

> frappe 9.2.22
> erpnext 9.2.21

I faced the similar problem with other doctypes that are having child tables. So I feel, there is some issue with doctypes having child tables.

**Comment by Zlash65** [comment]
![data-import-issue](https://user-images.githubusercontent.com/11695402/33878375-3cf4120c-df51-11e7-9fd4-9f777b5e50e1.gif)
Working fine for me. Tried for the same data as yours. Might be something else you entered in the csv or so... Can you provide exact steps and data you entered ?
```{u'item_attribute_values': [{u'attribute_value': u'Green', u'parenttype': u'Item Attribute', u'parentfield': u'item_attribute_values', u'abbr': u'G', u'doctype': u'Item Attribute Value'}], u'from_range': 0, u'name': None, u'increment': 0, u'numeric_values': 0, u'attribute_name': u'Test Color', u'to_range': 0, u'doctype': u'Item Attribute'}```

**Comment by umairsy** [comment]
Please discuss functional and technical issues on the community forum.

https://discuss.erpnext.com

**Comment by vwithv1602** [comment]
Hi @umairsy,
I've already created a thread in the erpnext forum ([link](https://discuss.erpnext.com/t/data-import-tool-issue/31523)). I posted this here as this seems to be an issue. If this is not an issue, please kindly reply on the forum what mistake I have committed. 
But if this is an issue, it shouldn't be closed without a fix right?

@Zlash65 , try to add another color along with Green. For multiple records it is throwing error. And as Umair said better to discuss it on the forum ([link](https://discuss.erpnext.com/t/data-import-tool-issue/31523)).
