### ISSUE TITLE
Refactor shipping rule based on net weight

### ISSUE THREAD

**Issue by nabinhait** [frappe/erpnext#11958]
- Remove weight related calculation from taxes_and_totals.py
- Write a separate function `calculate_net_weight` which will calculate net_weight based on stock_qty and weight_per_unit
- On calculation of net_weight, apply shipping rule and after that calculate `calculate_taxes_and_totals`
- Trigger `calculate_net_weight` on `stock_qty` and `weight_per_unit` and `items_remove`

**Comment by vishdha** [comment]
https://github.com/frappe/erpnext/pull/12001
