### ISSUE TITLE
Re-align fields in the Account Settings

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#11957]
![screen shot 2017-12-12 at 4 16 49 pm](https://user-images.githubusercontent.com/910238/33880551-ffc6d49e-df57-11e7-8323-36b1da700a2a.png)

**Comment by vishdha** [comment]
![account](https://user-images.githubusercontent.com/6947417/33979071-bf25ebd8-e0c8-11e7-98f7-8d53209bc173.png)
It showing some input in above section.
Not able to replicate this issue.

**Comment by umairsy** [comment]
Yes, it was related to Write permission.

Issue closed.
