### ISSUE TITLE
Taxes - Recalculate total on removal of a row

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#11964]
In a sales or purchase, if tax table has multiple rows, and if one of it is removed, then on removal, the values for the total taxes and other charges is not recalculated.

**Comment by shreyashah115** [comment]
@umairsy Can't replicate.
![anim](https://user-images.githubusercontent.com/17617465/33928280-794b78a2-e00b-11e7-9f9b-a8e1898872b2.gif)

**Comment by nabinhait** [comment]
I think it was not happening that time because of some other issue, closing it.
