### ISSUE TITLE
[BUG] - Error message on cancel document

### ISSUE THREAD

**Issue by vladucoju** [frappe/erpnext#11963]
Hello,

i have problem after updating to latest version. I am not able to cancel document created from POS. Error is shown on the picture

![untitled](https://user-images.githubusercontent.com/9590909/33882903-0d87f57c-df3a-11e7-82ea-59a1133061af.png)

Is there any slolution to delete this document?

**Comment by umairsy** [comment]
Please post such queries on the community forum first.

https://discss.erpnext.com

**Comment by vladucoju** [comment]
I post it on this topic

[https://discuss.erpnext.com/t/unable-to-submit-purchase-invoice-debit-and-credit-not-equal-for-this-voucher/2213/18](url)
