### ISSUE TITLE
Bench update error ERPNext: v9.2.22  Frappe Framework: v9.2.21

### ISSUE THREAD

**Issue by jasonbrowne** [frappe/erpnext#11969]
Installed Apps

ERPNext: v9.2.22

Frappe Framework: v9.2.21

FreeBSD 11.0-RELEASE-p1

Team,

I am getting the following error after attempting to run bench update:

(12:27 frappe@ERPNext-Demo1 frappe-bench) > bench update
INFO:bench.utils:updating bench
INFO:bench.utils:git pull
Already up-to-date.
remote: Counting objects: 211, done.
remote: Total 211 (delta 149), reused 150 (delta 149), pack-reused 61
Receiving objects: 100% (211/211), 34.24 KiB | 0 bytes/s, done.
Resolving deltas: 100% (173/173), completed with 83 local objects.
From https://github.com/frappe/frappe
   01a955eb4..7506c49dc  develop               -> upstream/develop
   2d9b988b9..4d4fb7231  hotfix                -> upstream/hotfix
   2d9b988b9..4d4fb7231  master                -> upstream/master
 * [new branch]          netchampfaris-patch-1 -> upstream/netchampfaris-patch-1
   628e17799..70b69c6d7  staging               -> upstream/staging
   2ce0f70c9..6fc2a309e  v8.x.x                -> upstream/v8.x.x
 * [new tag]             v9.2.23               -> v9.2.23
 * [new tag]             v9.2.22               -> v9.2.22
INFO:bench.utils:./env/bin/pip install Pillow
Requirement already satisfied: Pillow in ./env/lib/python2.7/site-packages
Requirement already satisfied: olefile in ./env/lib/python2.7/site-packages (from Pillow)
INFO:bench.app:pulling frappe
INFO:bench.utils:git pull  upstream develop
From https://github.com/frappe/frappe
 * branch                develop    -> FETCH_HEAD
Updating 01a955eb4..7506c49dc
Fast-forward
 .eslintrc                                          |   1 -
 .gitignore                                         |   6 +-
 .travis.yml                                        |   4 +-
 frappe/__init__.py                                 |   2 +-
 frappe/build.js                                    |   2 +
 frappe/core/page/data_import_tool/importer.py      |  22 ++++-
 frappe/core/page/modules_setup/modules_setup.html  |   4 +-
 frappe/docs/user/en/guides/desk/making_charts.md   |   3 +
 .../user/en/guides/desk/making_charts_in_c3js.md   |  35 --------
 frappe/docs/user/en/guides/desk/making_graphs.md   | 100 ---------------------
 .../user/en/guides/integration/google_gsuite.md    |  44 ++++-----
 .../email/doctype/email_account/email_account.py   |   2 +-
 .../doctype/dropbox_settings/dropbox_settings.py   |   4 +-
 frappe/patches/v9_1/move_feed_to_activity_log.py   |  37 ++------
 frappe/public/css/desk.css                         |  51 ++---------
 frappe/public/js/frappe/form/footer/assign_to.js   |   4 +-
 frappe/public/js/frappe/form/grid.js               |  16 ----
 frappe/public/js/frappe/misc/utils.js              |   4 +-
 frappe/public/js/frappe/ui/page.js                 |  35 +++++++-
 frappe/public/js/legacy/client_script_helpers.js   |   2 +-
 frappe/public/js/legacy/form.js                    |   8 +-
 frappe/public/less/desk.less                       |  60 +++----------
 .../templates/print_formats/standard_macros.html   |   2 +-
 frappe/utils/data.py                               |  14 ++-
 frappe/utils/help.py                               |  30 ++++---
 frappe/www/me.html                                 |   2 +-
 package.json                                       |   1 +
 27 files changed, 170 insertions(+), 325 deletions(-)
 create mode 100644 frappe/docs/user/en/guides/desk/making_charts.md
 delete mode 100644 frappe/docs/user/en/guides/desk/making_charts_in_c3js.md
 delete mode 100644 frappe/docs/user/en/guides/desk/making_graphs.md
INFO:bench.utils:find . -name "*.pyc" -delete
INFO:bench.app:pulling erpnext
INFO:bench.utils:git pull  upstream develop
remote: Counting objects: 529, done.
remote: Compressing objects: 100% (225/225), done.
remote: Total 529 (delta 409), reused 413 (delta 299), pack-reused 0
Receiving objects: 100% (529/529), 2.70 MiB | 0 bytes/s, done.
Resolving deltas: 100% (409/409), completed with 191 local objects.
From https://github.com/frappe/erpnext
 * branch                develop    -> FETCH_HEAD
   4cfbeebde..0f97eda7c  develop    -> upstream/develop
Updating 4cfbeebde..0f97eda7c
Fast-forward
 .travis.yml                                        |   6 ++
 erpnext/__init__.py                                |   2 +-
 .../account/tests/test_account_with_number.js      |   2 +-
 .../opening_invoice_creation_tool.py               |  30 ++++---
 .../opening_invoice_creation_tool_item.json        |  62 +++++++++++++-
 .../accounts/doctype/pos_profile/pos_profile.js    |   5 --
 .../accounts/doctype/pos_profile/pos_profile.json  |  34 +-------
 .../accounts/doctype/pos_profile/pos_profile.py    |  12 +--
 .../doctype/purchase_invoice/purchase_invoice.json |  32 ++++++-
 .../purchase_invoice/test_purchase_invoice.js      |   2 +-
 .../doctype/sales_invoice/sales_invoice.py         |  11 ++-
 .../tests/test_sales_invoice_with_margin.js        |   2 +-
 .../tests/test_sales_invoice_with_payment.js       |   1 -
 .../doctype/shipping_rule/shipping_rule.json       |   4 +-
 erpnext/assets/doctype/asset/asset.json            |   4 +-
 erpnext/assets/doctype/asset/asset.py              |  14 ++-
 .../test_purchase_order_with_last_purchase_rate.js |  10 ++-
 erpnext/buying/doctype/supplier/test_supplier.js   |   1 -
 erpnext/config/desktop.py                          |  40 +++++----
 erpnext/config/hr.py                               |   4 +-
 erpnext/config/stock.py                            |   7 +-
 erpnext/controllers/accounts_controller.py         |  15 ++--
 erpnext/controllers/taxes_and_totals.py            |   5 +-
 .../crm/doctype/lead/tests/test_lead_individual.js |  43 ++++++++++
 .../test_lead_organization.js}                     |  46 ++--------
 erpnext/crm/doctype/opportunity/opportunity.py     |   2 +-
 erpnext/docs/assets/img/agriculture/agri_desk.png  | Bin 0 -> 56258 bytes
 .../docs/assets/img/agriculture/agri_doctypes.png  | Bin 0 -> 19948 bytes
 .../assets/img/agriculture/crops_and_land/crop.png | Bin 0 -> 151132 bytes
 .../img/agriculture/crops_and_land/crop_cycle.png  | Bin 0 -> 96141 bytes
 .../img/agriculture/crops_and_land/land_unit.png   | Bin 0 -> 482391 bytes
 .../img/agriculture/crops_and_land/projects.png    | Bin 0 -> 156664 bytes
 .../diseases_and_fertilizer/disease.png            | Bin 0 -> 60264 bytes
 .../diseases_and_fertilizer/fertilizer.png         | Bin 0 -> 130903 bytes
 .../docs/assets/img/project/project_costing.png    | Bin 73354 -> 42483 bytes
 erpnext/docs/assets/img/regional/uae/__init__.py   |   0
 .../assets/img/regional/uae/detailed-invoice.png   | Bin 0 -> 148991 bytes
 .../assets/img/regional/uae/simplified-invoice.png | Bin 0 -> 79463 bytes
 .../docs/assets/img/regional/uae/tax-code-item.png | Bin 0 -> 39722 bytes
 .../assets/img/regional/uae/tax-id-company.png     | Bin 0 -> 57446 bytes
 .../assets/img/regional/uae/tax-id-customer.png    | Bin 0 -> 60252 bytes
 .../assets/img/regional/uae/uae-tax-templates.png  | Bin 0 -> 62636 bytes
 .../docs/assets/img/regional/uae/vat-invoice.gif   | Bin 0 -> 1305484 bytes
 .../user/manual/en/agriculture/analytics/index.md  |  12 +++
 .../manual/en/agriculture/crops_and_land/crop.md   |  50 +++++++++++
 .../en/agriculture/crops_and_land/crop_cycle.md    |  30 +++++++
 .../manual/en/agriculture/crops_and_land/index.md  |  15 ++++
 .../manual/en/agriculture/crops_and_land/index.txt |   3 +
 .../en/agriculture/crops_and_land/land_unit.md     |  31 +++++++
 .../agriculture/diseases_and_fertilizer/disease.md |  24 ++++++
 .../diseases_and_fertilizer/fertilizer.md          |   5 ++
 .../agriculture/diseases_and_fertilizer/index.md   |   7 ++
 .../agriculture/diseases_and_fertilizer/index.txt  |   2 +
 erpnext/docs/user/manual/en/agriculture/index.md   |  22 +++++
 erpnext/docs/user/manual/en/agriculture/index.txt  |   3 +
 erpnext/docs/user/manual/en/projects/project.md    |   6 +-
 .../en/regional/united_arab_emirates/index.txt     |   1 +
 .../regional/united_arab_emirates/uae-vat-setup.md |  45 ++++++++++
 .../assessment_group/test_assessment_group.js      |  23 +----
 erpnext/hooks.py                                   |   3 +-
 erpnext/hr/doctype/branch/test_branch.js           |   3 +-
 erpnext/hr/doctype/department/test_department.js   |   3 +-
 erpnext/hr/doctype/designation/test_designation.js |   3 +-
 erpnext/hr/doctype/employee/employee.py            |   2 +-
 .../test_employee_loan_application.js              |   2 +-
 .../employment_type/test_employment_type.js        |   3 +-
 erpnext/hr/doctype/expense_claim/expense_claim.js  |  21 +++--
 .../expense_claim_type/test_expense_claim_type.js  |   2 +-
 erpnext/hr/doctype/payroll_entry/payroll_entry.py  |  16 +++-
 .../hr/doctype/payroll_entry/test_payroll_entry.js |  18 +++-
 erpnext/hr/doctype/salary_slip/test_salary_slip.js |   6 ++
 erpnext/hub_node/__init__.py                       |  20 +++--
 .../doctype/operation/test_operation.js            |   6 +-
 .../doctype/production_order/production_order.js   |   2 +
 .../doctype/production_order/production_order.py   |  55 ++++++++----
 .../production_order/test_production_order.js      |   6 +-
 .../doctype/volunteer_type/test_volunteer_type.js  |  14 +--
 erpnext/patches.txt                                |   3 +-
 .../v10_0/setup_vat_for_uae_and_saudi_arabia.py    |  11 +++
 .../doctype/activity_type/test_activity_type.js    |   3 +-
 erpnext/projects/doctype/project/project.json      |  66 ++++++++++----
 erpnext/projects/doctype/project/project.py        |  39 ++++++---
 erpnext/projects/doctype/project/test_project.js   |  23 +++++
 erpnext/projects/doctype/task/task_tree.js         |  10 ++-
 .../projects/doctype/task/tests/test_task_tree.js  |  21 ++---
 erpnext/public/build.json                          |   2 -
 erpnext/public/js/controllers/taxes_and_totals.js  |  10 ++-
 erpnext/public/js/controllers/transaction.js       |  12 ++-
 erpnext/public/js/setup_wizard.js                  |   2 +-
 .../print_format/detailed_tax_invoice/__init__.py  |   0
 .../detailed_tax_invoice/detailed_tax_invoice.json |  22 +++++
 .../simplified_tax_invoice/__init__.py             |   0
 .../simplified_tax_invoice.json                    |  22 +++++
 erpnext/regional/saudi_arabia/__init__.py          |   0
 erpnext/regional/saudi_arabia/setup.py             |  14 +++
 erpnext/regional/united_arab_emirates/__init__.py  |   0
 erpnext/regional/united_arab_emirates/setup.py     |  73 ++++++++++++++++
 .../doctype/restaurant/test_restaurant.js          |   9 ++
 .../quotation/tests/test_quotation_with_margin.js  |   2 +-
 erpnext/selling/doctype/sales_order/sales_order.py |  15 ++--
 ...t_sales_order_with_bypass_credit_limit_check.js |   6 +-
 .../tests/test_sales_order_with_margin.js          |   2 +-
 ...ales_order_without_bypass_credit_limit_check.js |   3 +-
 .../selling/page/point_of_sale/point_of_sale.js    |   2 +
 erpnext/setup/doctype/company/company.json         |  33 ++++++-
 erpnext/setup/doctype/company/company.py           |   2 +-
 .../setup/setup_wizard/data/country_wise_tax.json  |  46 ++++++++++
 erpnext/stock/doctype/batch/batch.py               |   2 +-
 .../test_delivery_note_with_margin.js              |   2 +-
 .../stock/doctype/delivery_trip/delivery_trip.js   |  10 +++
 .../stock/doctype/delivery_trip/delivery_trip.py   |  13 +--
 erpnext/stock/doctype/item/item.json               |  32 ++++++-
 .../stock/doctype/item_price/test_item_price.js    |   4 +-
 .../item_variant_attribute.json                    |  52 ++++++++++-
 erpnext/stock/doctype/stock_entry/stock_entry.js   |  24 +++++-
 erpnext/stock/doctype/stock_entry/stock_entry.py   |   2 +-
 .../stock_reconciliation/stock_reconciliation.py   |   2 +-
 erpnext/stock/get_item_details.py                  |   2 +-
 erpnext/stock/report/item_price_stock/__init__.py  |   0
 .../report/item_price_stock/item_price_stock.js    |  14 +++
 .../report/item_price_stock/item_price_stock.json  |  44 ++++++++++
 .../report/item_price_stock/item_price_stock.py    |  95 +++++++++++++++++++++
 erpnext/tests/ui/tests.txt                         |  48 -----------
 erpnext/tests/ui/tests2.txt                        |  46 ++++++++++
 124 files changed, 1339 insertions(+), 366 deletions(-)
 create mode 100644 erpnext/crm/doctype/lead/tests/test_lead_individual.js
 rename erpnext/crm/doctype/lead/{test_lead.js => tests/test_lead_organization.js} (55%)
 create mode 100644 erpnext/docs/assets/img/agriculture/agri_desk.png
 create mode 100644 erpnext/docs/assets/img/agriculture/agri_doctypes.png
 create mode 100644 erpnext/docs/assets/img/agriculture/crops_and_land/crop.png
 create mode 100644 erpnext/docs/assets/img/agriculture/crops_and_land/crop_cycle.png
 create mode 100644 erpnext/docs/assets/img/agriculture/crops_and_land/land_unit.png
 create mode 100644 erpnext/docs/assets/img/agriculture/crops_and_land/projects.png
 create mode 100644 erpnext/docs/assets/img/agriculture/diseases_and_fertilizer/disease.png
 create mode 100644 erpnext/docs/assets/img/agriculture/diseases_and_fertilizer/fertilizer.png
 create mode 100644 erpnext/docs/assets/img/regional/uae/__init__.py
 create mode 100644 erpnext/docs/assets/img/regional/uae/detailed-invoice.png
 create mode 100644 erpnext/docs/assets/img/regional/uae/simplified-invoice.png
 create mode 100644 erpnext/docs/assets/img/regional/uae/tax-code-item.png
 create mode 100644 erpnext/docs/assets/img/regional/uae/tax-id-company.png
 create mode 100644 erpnext/docs/assets/img/regional/uae/tax-id-customer.png
 create mode 100644 erpnext/docs/assets/img/regional/uae/uae-tax-templates.png
 create mode 100644 erpnext/docs/assets/img/regional/uae/vat-invoice.gif
 create mode 100644 erpnext/docs/user/manual/en/agriculture/analytics/index.md
 create mode 100644 erpnext/docs/user/manual/en/agriculture/crops_and_land/crop.md
 create mode 100644 erpnext/docs/user/manual/en/agriculture/crops_and_land/crop_cycle.md
 create mode 100644 erpnext/docs/user/manual/en/agriculture/crops_and_land/index.md
 create mode 100644 erpnext/docs/user/manual/en/agriculture/crops_and_land/index.txt
 create mode 100644 erpnext/docs/user/manual/en/agriculture/crops_and_land/land_unit.md
 create mode 100644 erpnext/docs/user/manual/en/agriculture/diseases_and_fertilizer/disease.md
 create mode 100644 erpnext/docs/user/manual/en/agriculture/diseases_and_fertilizer/fertilizer.md
 create mode 100644 erpnext/docs/user/manual/en/agriculture/diseases_and_fertilizer/index.md
 create mode 100644 erpnext/docs/user/manual/en/agriculture/diseases_and_fertilizer/index.txt
 create mode 100644 erpnext/docs/user/manual/en/agriculture/index.md
 create mode 100644 erpnext/docs/user/manual/en/agriculture/index.txt
 create mode 100644 erpnext/docs/user/manual/en/regional/united_arab_emirates/index.txt
 create mode 100644 erpnext/docs/user/manual/en/regional/united_arab_emirates/uae-vat-setup.md
 create mode 100644 erpnext/patches/v10_0/setup_vat_for_uae_and_saudi_arabia.py
 create mode 100644 erpnext/projects/doctype/project/test_project.js
 create mode 100644 erpnext/regional/print_format/detailed_tax_invoice/__init__.py
 create mode 100644 erpnext/regional/print_format/detailed_tax_invoice/detailed_tax_invoice.json
 create mode 100644 erpnext/regional/print_format/simplified_tax_invoice/__init__.py
 create mode 100644 erpnext/regional/print_format/simplified_tax_invoice/simplified_tax_invoice.json
 create mode 100644 erpnext/regional/saudi_arabia/__init__.py
 create mode 100644 erpnext/regional/saudi_arabia/setup.py
 create mode 100644 erpnext/regional/united_arab_emirates/__init__.py
 create mode 100644 erpnext/regional/united_arab_emirates/setup.py
 create mode 100644 erpnext/stock/report/item_price_stock/__init__.py
 create mode 100644 erpnext/stock/report/item_price_stock/item_price_stock.js
 create mode 100644 erpnext/stock/report/item_price_stock/item_price_stock.json
 create mode 100644 erpnext/stock/report/item_price_stock/item_price_stock.py
 create mode 100644 erpnext/tests/ui/tests2.txt
INFO:bench.utils:find . -name "*.pyc" -delete
Updating Python libraries...
INFO:bench.utils:./env/bin/pip install --upgrade pip
Requirement already up-to-date: pip in ./env/lib/python2.7/site-packages
INFO:bench.utils:./env/bin/pip install -q -r /usr/home/frappe/bench-repo/requirements.txt
INFO:bench.utils:./env/bin/pip install -q -r ./apps/erpnext/requirements.txt
INFO:bench.utils:./env/bin/pip install -q -r ./apps/frappe/requirements.txt
Updating node libraries...
INFO:bench.utils:npm install
frappe@ /usr/home/frappe/frappe-bench
`-- babel-plugin-transform-object-rest-spread@6.26.0
  `-- babel-plugin-syntax-object-rest-spread@6.13.0

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (cu
rrent: {"os":"freebsd","arch":"x64"})
npm WARN frappe@ No description
Backing up sites...
Patching sites...
Migrating site1.local
Executing erpnext.patches.v10_0.setup_vat_for_uae_and_saudi_arabia in site1.local (1bd3e0294da19198)
Success
Updating DocTypes for frappe        : [========================================]
Updating DocTypes for erpnext       : [========================================]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 94, in <module>
    main()
  File "/usr/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/usr/home/frappe/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/home/frappe/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/home/frappe/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/home/frappe/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/home/frappe/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/home/frappe/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/home/frappe/frappe-bench/env/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/home/frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 24, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/usr/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 222, in migrate
    migrate(context.verbose, rebuild_website=rebuild_website)
  File "/usr/home/frappe/frappe-bench/apps/frappe/frappe/migrate.py", line 37, in migrate
    sync_desktop_icons()
  File "/usr/home/frappe/frappe-bench/apps/frappe/frappe/desk/doctype/desktop_icon/desktop_icon.py", line 317, in sync_desktop_icons
    sync_from_app(app)
  File "/usr/home/frappe/frappe-bench/apps/frappe/frappe/desk/doctype/desktop_icon/desktop_icon.py", line 353, in sync_from_app
    desktop_icon.save()
  File "/usr/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 256, in save
    return self._save(*args, **kwargs)
  File "/usr/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 279, in _save
    self.insert()
  File "/usr/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 217, in insert
    self._validate_links()
  File "/usr/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 724, in _validate_links
    frappe.LinkValidationError)
  File "/usr/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 323, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/usr/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 309, in msgprint
    _raise_exception()
  File "/usr/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 282, in _raise_exception
    raise raise_exception(encode(msg))
frappe.exceptions.LinkValidationError: Could not find _doctype: Data Import

Cheers,

Jason

**Comment by manassolanki** [comment]
Fixed via https://github.com/frappe/erpnext/pull/11974
