### ISSUE TITLE
email problem 

### ISSUE THREAD

**Issue by khsh90** [frappe/erpnext#11970]
i can't add my gmail account and my private company email to erp next email account , where is the problem

**Comment by umairsy** [comment]
Please post your functional queries on the ERPNext community forum.

https://discuss.erpnext.com

For now, here is the help on how to setup Email Inbox.

https://erpnext.org/docs/user/manual/en/setting-up/email/email-inbox

Further support via forum please.

**Comment by tundebabzy** [comment]
Hi @khsh90
Thanks for using ERPNext. We usually answer questions on our forum and use github mainly for bugs. Please visit https://discuss.erpnext.com.
