### ISSUE TITLE
Backup download does not work properly using custom domain

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#11983]
Suppose I have a hosted account abc.erpnext.com and it has custom domain erp.abc.com and I always use custom domain for daily use. Now, when I download backup, system send the download URL using abc.erpnext.com. But I logged into the site using erp.abc.com. Hence, it gives permission error while dowloading the backup.
Ideally, it should allow to download, irrespective of which domain I use to logged into the account.

**Comment by saurabh6790** [comment]
Not able to replicate the issue. 

Any specific request or issue reported by any one?

**Comment by umairsy** [comment]
Yes, there was support issue which had the custom domain and this issue was occurring for that user.

**Comment by nabinhait** [comment]
Seems like it has been fixed already. Please reopen if exists.
