### ISSUE TITLE
Batch Problem in POS

### ISSUE THREAD

**Issue by Mohd200** [frappe/erpnext#11999]
Greetings.
Whenever I use POS on a certain Item Which has Batch, the the page crashes.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/32062135/33946759-a3bb1188-e033-11e7-80d5-a12ab148143d.gif)

Can anyone Please help me with my problem?
Thank You.

**Comment by rohitwaghchaure** [comment]
@Mohd200 

Can you please share the version of erpnext app. Based on GIF, it seems that customer has not set when you select it from the dropdown, please correct if I'm wrong. If possible can you share the error on the browser's console log.

**Comment by Mohd200** [comment]
Hello @rohitwaghchaure and thank you for replying.
My apologies, the video was cut short. Here is the full version:

![dec_14_2017_12_22_pm](https://user-images.githubusercontent.com/32062135/33986130-b7200d9c-e0cd-11e7-82f1-8027b7eb6f0b.gif)

And here is the version as well:

![export 1](https://user-images.githubusercontent.com/32062135/33986166-d2e8ad36-e0cd-11e7-86e4-edd48de3ec38.png)

Here is the Console:

libs.min.js?ver=1511787374.0:12 Uncaught (in promise) TypeError: Cannot read property 'getBoundingClientRect' of null
    at m._setMeasurements (libs.min.js?ver=1511787374.0:12)
    at new m (libs.min.js?ver=1511787374.0:12)
    at Class.init (list.min.js?ver=1511787374.0:1153)
    at new Class (desk.min.js?ver=1511787374.0:37)
    at Class.make_tags (form.min.js?ver=1511787374.0:4573)
    at Class.make (form.min.js?ver=1511787374.0:4517)
    at _f.Frm.render_form (form.min.js?ver=1511787374.0:499)
    at form.min.js?ver=1511787374.0:591
    at <anonymous>
m._setMeasurements @ libs.min.js?ver=1511787374.0:12
m @ libs.min.js?ver=1511787374.0:12
init @ list.min.js?ver=1511787374.0:1153
Class @ desk.min.js?ver=1511787374.0:37
make_tags @ form.min.js?ver=1511787374.0:4573
make @ form.min.js?ver=1511787374.0:4517
_f.Frm.render_form @ form.min.js?ver=1511787374.0:499
(anonymous) @ form.min.js?ver=1511787374.0:591
Promise resolved (async)
_f.Frm.setnewdoc @ form.min.js?ver=1511787374.0:588
_f.Frm.refresh @ form.min.js?ver=1511787374.0:448
get_frm @ VM240:357
frappe.model.with_doctype @ VM240:347
callback @ desk.min.js?ver=1511787374.0:5511
callback @ desk.min.js?ver=1511787374.0:1425
_ @ desk.min.js?ver=1511787374.0:1449
(anonymous) @ desk.min.js?ver=1511787374.0:1550
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
z @ jquery.min.js:4
(anonymous) @ jquery.min.js:4
XMLHttpRequest.send (async)
send @ jquery.min.js:4
ajax @ jquery.min.js:4
frappe.request.call @ desk.min.js?ver=1511787374.0:1536
frappe.call @ desk.min.js?ver=1511787374.0:1429
with_doctype @ desk.min.js?ver=1511787374.0:5485
resolve @ VM240:346
make_sales_invoice_frm @ VM240:341
frappe.run_serially @ VM240:326
Promise resolved (async)
(anonymous) @ desk.min.js?ver=1511787374.0:665
frappe.run_serially @ desk.min.js?ver=1511787374.0:663
make_new_invoice @ VM240:325
frappe.run_serially @ VM240:54
Promise resolved (async)
(anonymous) @ desk.min.js?ver=1511787374.0:665
frappe.run_serially @ desk.min.js?ver=1511787374.0:663
make @ VM240:45
PointOfSale.frappe.require @ VM240:40
eval_assets @ desk.min.js?ver=1511787374.0:146
(anonymous) @ desk.min.js?ver=1511787374.0:131
callback @ desk.min.js?ver=1511787374.0:175
callback @ desk.min.js?ver=1511787374.0:1425
_ @ desk.min.js?ver=1511787374.0:1449
(anonymous) @ desk.min.js?ver=1511787374.0:1550
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
z @ jquery.min.js:4
(anonymous) @ jquery.min.js:4
XMLHttpRequest.send (async)
send @ jquery.min.js:4
ajax @ jquery.min.js:4
frappe.request.call @ desk.min.js?ver=1511787374.0:1536
frappe.call @ desk.min.js?ver=1511787374.0:1429
fetch @ desk.min.js?ver=1511787374.0:165
execute @ desk.min.js?ver=1511787374.0:130
frappe.require @ desk.min.js?ver=1511787374.0:79
PointOfSale @ VM240:39
frappe.db.get_value @ VM240:14
callback @ desk.min.js?ver=1511787374.0:5979
callback @ desk.min.js?ver=1511787374.0:1425
_ @ desk.min.js?ver=1511787374.0:1449
(anonymous) @ desk.min.js?ver=1511787374.0:1550
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
z @ jquery.min.js:4
(anonymous) @ jquery.min.js:4
XMLHttpRequest.send (async)
send @ jquery.min.js:4
ajax @ jquery.min.js:4
frappe.request.call @ desk.min.js?ver=1511787374.0:1536
frappe.call @ desk.min.js?ver=1511787374.0:1429
get_value @ desk.min.js?ver=1511787374.0:5971
frappe.pages.point-of-sale.on_page_load @ VM240:11
trigger_page_event @ desk.min.js?ver=1511787374.0:9659
init @ desk.min.js?ver=1511787374.0:9648
Class @ desk.min.js?ver=1511787374.0:37
(anonymous) @ desk.min.js?ver=1511787374.0:9615
callback @ desk.min.js?ver=1511787374.0:9600
callback @ desk.min.js?ver=1511787374.0:1425
_ @ desk.min.js?ver=1511787374.0:1449
(anonymous) @ desk.min.js?ver=1511787374.0:1550
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
z @ jquery.min.js:4
(anonymous) @ jquery.min.js:4
XMLHttpRequest.send (async)
send @ jquery.min.js:4
ajax @ jquery.min.js:4
frappe.request.call @ desk.min.js?ver=1511787374.0:1536
frappe.call @ desk.min.js?ver=1511787374.0:1429
with_page @ desk.min.js?ver=1511787374.0:9593
(anonymous) @ desk.min.js?ver=1511787374.0:9611
with_doctype @ desk.min.js?ver=1511787374.0:5478
show @ desk.min.js?ver=1511787374.0:9610
frappe.route @ desk.min.js?ver=1511787374.0:2183
startup @ desk.min.js?ver=1511787374.0:12086
load_startup @ desk.min.js?ver=1511787374.0:12055
init @ desk.min.js?ver=1511787374.0:12051
Class @ desk.min.js?ver=1511787374.0:37
frappe.start_app @ desk.min.js?ver=1511787374.0:12035
(anonymous) @ desk.min.js?ver=1511787374.0:12046
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
ready @ jquery.min.js:2
J @ jquery.min.js:2
2desk.min.js?ver=1511787374.0:8586 base_amount: could not find docfield in method precision()
2desk.min.js?ver=1511787374.0:8586 base_amount: could not find docfield in method precision()
libs.min.js?ver=1511787374.0:12 Uncaught (in promise) TypeError: Cannot read property 'getBoundingClientRect' of null
    at m._setMeasurements (libs.min.js?ver=1511787374.0:12)
    at new m (libs.min.js?ver=1511787374.0:12)
    at Class.init (list.min.js?ver=1511787374.0:1153)
    at new Class (desk.min.js?ver=1511787374.0:37)
    at Class.make_tags (form.min.js?ver=1511787374.0:4573)
    at Class.make (form.min.js?ver=1511787374.0:4517)
    at _f.Frm.render_form (form.min.js?ver=1511787374.0:499)
    at _f.Frm.refresh (form.min.js?ver=1511787374.0:454)
    at erpnext.min.js?ver=1511787374.0:583
    at <anonymous>
m._setMeasurements @ libs.min.js?ver=1511787374.0:12
m @ libs.min.js?ver=1511787374.0:12
init @ list.min.js?ver=1511787374.0:1153
Class @ desk.min.js?ver=1511787374.0:37
make_tags @ form.min.js?ver=1511787374.0:4573
make @ form.min.js?ver=1511787374.0:4517
_f.Frm.render_form @ form.min.js?ver=1511787374.0:499
_f.Frm.refresh @ form.min.js?ver=1511787374.0:454
(anonymous) @ erpnext.min.js?ver=1511787374.0:583
Promise resolved (async)
(anonymous) @ desk.min.js?ver=1511787374.0:665
frappe.run_serially @ desk.min.js?ver=1511787374.0:663
callback @ erpnext.min.js?ver=1511787374.0:578
callback @ desk.min.js?ver=1511787374.0:1425
_ @ desk.min.js?ver=1511787374.0:1449
(anonymous) @ desk.min.js?ver=1511787374.0:1550
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
z @ jquery.min.js:4
(anonymous) @ jquery.min.js:4
XMLHttpRequest.send (async)
send @ jquery.min.js:4
ajax @ jquery.min.js:4
frappe.request.call @ desk.min.js?ver=1511787374.0:1536
frappe.call @ desk.min.js?ver=1511787374.0:1429
erpnext.utils.get_party_details @ erpnext.min.js?ver=1511787374.0:572
customer @ VM249:902
runner @ form.min.js?ver=1511787374.0:2558
(anonymous) @ form.min.js?ver=1511787374.0:2585
Promise resolved (async)
(anonymous) @ desk.min.js?ver=1511787374.0:665
frappe.run_serially @ desk.min.js?ver=1511787374.0:663
trigger @ form.min.js?ver=1511787374.0:2590
(anonymous) @ form.min.js?ver=1511787374.0:261
(anonymous) @ desk.min.js?ver=1511787374.0:5766
each @ jquery.min.js:2
runner @ desk.min.js?ver=1511787374.0:5764
(anonymous) @ desk.min.js?ver=1511787374.0:5783
Promise resolved (async)
(anonymous) @ desk.min.js?ver=1511787374.0:665
frappe.run_serially @ desk.min.js?ver=1511787374.0:663
trigger @ desk.min.js?ver=1511787374.0:5787
(anonymous) @ desk.min.js?ver=1511787374.0:5739
Promise resolved (async)
(anonymous) @ desk.min.js?ver=1511787374.0:665
frappe.run_serially @ desk.min.js?ver=1511787374.0:663
set_value @ desk.min.js?ver=1511787374.0:5750
_set @ form.min.js?ver=1511787374.0:1234
_f.Frm.set_value @ form.min.js?ver=1511787374.0:1244
on_customer_change @ VM240:98
onchange @ VM240:580
(anonymous) @ control.min.js?ver=1511787374.0:188
Promise resolved (async)
(anonymous) @ desk.min.js?ver=1511787374.0:665
frappe.run_serially @ desk.min.js?ver=1511787374.0:663
set @ control.min.js?ver=1511787374.0:182
(anonymous) @ control.min.js?ver=1511787374.0:196
Promise resolved (async)
validate_and_set_in_model @ control.min.js?ver=1511787374.0:195
parse_validate_and_set_in_model @ control.min.js?ver=1511787374.0:172
(anonymous) @ control.min.js?ver=1511787374.0:1121
dispatch @ jquery.min.js:3
$event.dispatch @ report.min.js?ver=1511787374.0:3010
r.handle @ jquery.min.js:3
i.fire @ libs.min.js?ver=1511787374.0:2
select @ libs.min.js?ver=1511787374.0:2
mousedown @ libs.min.js?ver=1511787374.0:2
2desk.min.js?ver=1511787374.0:8586 base_amount: could not find docfield in method precision()
2desk.min.js?ver=1511787374.0:8586 base_amount: could not find docfield in method precision()
2desk.min.js?ver=1511787374.0:8586 base_amount: could not find docfield in method precision()
2desk.min.js?ver=1511787374.0:8586 base_amount: could not find docfield in method precision()
2desk.min.js?ver=1511787374.0:8586 base_amount: could not find docfield in method precision()
2desk.min.js?ver=1511787374.0:8586 base_amount: could not find docfield in method precision()
2desk.min.js?ver=1511787374.0:8586 base_amount: could not find docfield in method precision()
2desk.min.js?ver=1511787374.0:8586 base_amount: could not find docfield in method precision()
VM842:220 Uncaught (in promise) TypeError: Cannot read property 'get_value' of undefined
    at selected_batches.grid.grid_rows.map (<anonymous>:220:49)
    at Array.map (<anonymous>)
    at Class.onchange (<anonymous>:216:51)
    at control.min.js?ver=1511787374.0:188
    at <anonymous>
selected_batches.grid.grid_rows.map @ VM842:220
onchange @ VM842:216
(anonymous) @ control.min.js?ver=1511787374.0:188
Promise resolved (async)
(anonymous) @ desk.min.js?ver=1511787374.0:665
frappe.run_serially @ desk.min.js?ver=1511787374.0:663
set @ control.min.js?ver=1511787374.0:182
(anonymous) @ control.min.js?ver=1511787374.0:196
Promise resolved (async)
validate_and_set_in_model @ control.min.js?ver=1511787374.0:195
parse_validate_and_set_in_model @ control.min.js?ver=1511787374.0:172
(anonymous) @ control.min.js?ver=1511787374.0:1121
dispatch @ jquery.min.js:3
$event.dispatch @ report.min.js?ver=1511787374.0:3010
r.handle @ jquery.min.js:3
i.fire @ libs.min.js?ver=1511787374.0:2
select @ libs.min.js?ver=1511787374.0:2
mousedown @ libs.min.js?ver=1511787374.0:2
VM842:220 Uncaught (in promise) TypeError: Cannot read property 'get_value' of undefined
    at selected_batches.grid.grid_rows.map (<anonymous>:220:49)
    at Array.map (<anonymous>)
    at Class.onchange (<anonymous>:216:51)
    at control.min.js?ver=1511787374.0:188
    at <anonymous>

**Comment by Mohd200** [comment]
Any Updates??

**Comment by rohitwaghchaure** [comment]
Hi @Mohd200 

We are working on this issue, as we have to make some changes in the design level, it will take some time to fix this issue. Currently you can only select one batch for one item from the POS.

**Comment by rohitwaghchaure** [comment]
Hi @Mohd200 
Have fixed this issue and we'll release the fix in next version
