### ISSUE TITLE
NGO - In Chapter, use Volunteer instead of User

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#11991]
In NGO module, Voluteer and Member is not used anywhere. We should use it in Chapter atleast.

![screen shot 2017-12-13 at 4 48 52 pm](https://user-images.githubusercontent.com/910238/33937030-c8d645a2-e027-11e7-8438-700f1e7fe993.png)

**Comment by vishdha** [comment]
https://github.com/frappe/erpnext/pull/12003
