### ISSUE TITLE
Multiple Barcodes

### ISSUE THREAD

**Issue by Mohd200** [frappe/erpnext#11995]
Good Day To All.
I am working in a Retail shop, and the Items that I sell are sold by Piece or Box or any other type of UOM.
Every UOM type of the same Item has a different Barcode.
Is there a way for an Item to have multiple Barcodes, and each of those Barcodes represents its own UOM type and Price Rate? 
It will make the POS a lot easier.

Thank You

**Comment by joezsweet** [comment]
Have a look to Product Bundle

**Comment by Mohd200** [comment]
Could you please explain how to implement Product Bundle in this scenario??

**Comment by joezsweet** [comment]
Feel free to read tutorial at: 

https://erpnext.org/docs/user/manual/en/selling/setup/product-bundle

https://www.youtube.com/watch?v=yk3kPrRyRRc

Please, use forum at [discuss.erpnext.org](discuss.erpnext.org) for further questions

**Comment by aakvatech** [comment]
Since we have multiple barcodes per product, is there a way to now link the UOM to barcodes so that scanning complete package automatically loads the correct UOM for that item?
