### ISSUE TITLE
On submitting the Sales Invoice, make group buttons are repeating

### ISSUE THREAD

**Issue by manassolanki** [frappe/erpnext#12009]
Steps to replicate:

1. Submit the sales invoice
2. Click on the print
3. Click on the edit
4. Click on the make button

![image](https://user-images.githubusercontent.com/20757311/33986028-57e443ec-e0e2-11e7-91cf-d41af4ba0e4a.png)

**Comment by netchampfaris** [comment]
Cannot replicate.
