### ISSUE TITLE
User not able to edit the comment

### ISSUE THREAD

**Issue by manassolanki** [frappe/erpnext#12012]
![image](https://user-images.githubusercontent.com/20757311/33987591-7633b0d0-e0e7-11e7-8162-35a9a28dd7ab.png)

**Comment by joolsr** [comment]
I originally submitted same bug here https://github.com/frappe/frappe/issues/3111 
Please note just adding Amend privileges to the users who need this permission works but creates another bug where emails are shown as editable. Not a problem in itself but when showing certain text only emails would totally destroy the formatting of the email making them unreadable. My referenced bug mentions all this. I'm happy to test as I am part of the CRM team in the Community

**Comment by elvise** [comment]
@joolsr i think is good create new communication from the app, right now only system manager can create it

**Comment by manassolanki** [comment]
@joolsr If the communication is of the type "Comment" and user is the creator of that communication records. Then he should be able to edit and save the communication

**Comment by joolsr** [comment]
@manassolanki many thanks for the fix ;-)
