### ISSUE TITLE
Russian-speaking localization

### ISSUE THREAD

**Issue by tzaripov** [frappe/erpnext#12015]
Good day! We represent the ERPNext frappe implementation team in Russia. In the process of implementation, we faced the problem of localization of terms in your product. When we try to manually localize terms by editing files:
/home/frappe/frappe-bench/apps/erpnext/erpnext/translations
/home/frappe/frappe-bench/apps/frappe/frappe/translations ru.csv
After the system is updated, the files are overwritten and all the work done is lost.
After contacting the support team, we received a reply that the terms need to be changed only on the portal https://translate.erpnext.com/view?lang=ru. But it’s very inconvenient for us to change terms in this way, because the terms are arranged in alphabetical order and are not divided into modules, while the translation of the same term can vary depending on context and declension. In the Russian language, various declensions and the endings of words change in different cases, if we use only one word form - the system will be uncompetitive in our market, as it will not be adapted for users.
In addition, on this portal some terms are in agreement for several months, for us it is not acceptable for long, since we need to translate most of the terms in a short period of time in order to launch the system in several Russian companies.
You can customize the work of localizing terms so that we give you a list of terms in the table form for the modules, and you replace the files with the Russian translation?
We perform translation by a fairly large team and our work can be useful for the distribution of your product in Russia.
We hope for an early resolution of this issue.
thanks a lot!

**Comment by umairsy** [comment]
Hello,

Thanks for your interest in localizing ERPNext for Russia.

As discussed earlier, the platform https://translate.erpnext.com/view?lang=ru will be best so that other community members can also contribute.

Once you have done contribution on the site, let us know. We will upgrade and merge it on demand.
