### ISSUE TITLE
Monthly Progress or sales target indicator is not apparent. 

### ISSUE THREAD

**Issue by ghost** [frappe/erpnext#12018]
The monthly sales target or progress indicator is currently shown in the notificationdropdown menu besides the company name. This doesn't have a tooltip or any details suggesting that this is a monthly target indicator, this can also be missunderstood as limit of user accounts in ERPNext cloud, or percentage completed in setup or something else by the new user. A solution is to make a tooltip explaining it or giving infomation like "25% monthly target achived" etc. Also it seems this space is not fully utilised, this bar can be shown beneth the company name rather fitting it in the remaining space in one line after the name.

** To Reproduce**
Click on the notification menu and check the target progress bar.

Attaching a screenshot showing the progress bar (right above the mouse pointer)
![screenshot_20171214_215811](https://user-images.githubusercontent.com/9101092/34003624-c302a4b4-e11b-11e7-8890-6cbc6bb325c5.png)

**Comment by somicoito** [comment]
+1
