### ISSUE TITLE
Salary Slip Emails get sent without successful Submission

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#12017]
Hi,

We used the Process Payroll tool to create Salary Slips. We then tried submitting them using the same tool. The submission did not go through because of some missing account heads in some of the Salary Components but the emails got sent to all employees and not even with Draft heading in the print format! Emails should not be sent unless Salary Slips are successfully submitted

Please fix this urgently

Thanks

**Comment by Olawale1** [comment]
Hi,

This issue is still in the current version. Please look into it 

Thanks

**Comment by jaichavan** [comment]
The issue couldn't be replicated in the latest version [v11.0.3-beta.34 () (staging)], I think it has been addressed and resolved. Can you confirm, @Olawale1 ?
