### ISSUE TITLE
Error when session expired

### ISSUE THREAD

**Issue by nabinhait** [frappe/erpnext#12032]
<img width="1003" alt="screen shot 2017-12-15 at 1 40 03 pm" src="https://user-images.githubusercontent.com/836784/34032752-7c3636b8-e19d-11e7-8d69-b06fd0f2d2fb.png">

**Comment by netchampfaris** [comment]
https://github.com/frappe/frappe/pull/4635

**Comment by netchampfaris** [comment]
Cannot replicate.
