### ISSUE TITLE
Opening Invoice Creation Tool Issues

### ISSUE THREAD

**Issue by nabinhait** [frappe/erpnext#12038]
- [x] Make "Posting Date", "Due Date", "Temporary Opening Account" as mandatory
- [x] If I enter date in format "2017-01-01", after uploading it becomes "20-01-2001"
- [x] As Party Type is set automatically based on Invoice Type, "Party Type" column should not be in downloaded template. Otherwise, user can enter Customer and supplier in same template.

**Comment by achillesrasquinha** [comment]
` If I enter date in format "2017-01-01", after uploading it becomes "20-01-2001"`

Cannot be guessed easily, issue within the last `frappe.datetime.user_to_str` (depends on system settings).
