### ISSUE TITLE
Error in Setup Wizard (after account creation)

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#12041]
![screen shot 2017-12-15 at 4 24 08 pm](https://user-images.githubusercontent.com/910238/34039150-8b0b167e-e1b4-11e7-8a6a-40906ec3c33a.png)

None of the items were created

**Comment by pratu16x7** [comment]
Unable to replicate on local setup:
<img width="679" alt="screen shot 2017-12-19 at 12 04 46 pm" src="https://user-images.githubusercontent.com/5196925/34143844-d474b236-e4b4-11e7-8c0e-e207fa58ebdd.png">

with all number of item cases.
