### ISSUE TITLE
In Address, Title and Party Details are not auto-updated

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#12044]
Steps:

1. Created customer
2. Creating Address
3. Address Title, which should be Customer ID not auto-updated.
4. Also, Customer ID not updated in the Reference (party) table.

Title:

![screen shot 2017-12-15 at 4 42 29 pm](https://user-images.githubusercontent.com/910238/34039843-366374f6-e1b7-11e7-8541-a4666c6f53b5.png)

Customer Reference;

![screen shot 2017-12-15 at 4 42 34 pm](https://user-images.githubusercontent.com/910238/34039853-3bcf7688-e1b7-11e7-8174-733a8aa8c7ca.png)

**Comment by rohitwaghchaure** [comment]
Seems issue is fixed, working properly.

![address_gif](https://user-images.githubusercontent.com/8780500/34043909-ec739f76-e1c8-11e7-9dab-2f0dd40996ba.gif)

Address Title, which should be Customer ID not auto-updated.
**It comes on save of customer**

**Comment by rohitwaghchaure** [comment]
Closing issue, feel free to reopen if issue still persists
