### ISSUE TITLE
Payment terms missing advance payment

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#12059]
Payment terms should have the option to sell with payment before the invoice. So I can prevent delivery notes or invoices against a sales order without confirmed payment.

**Comment by kennethsequeira** [comment]
You could look into Retail module (POS) for this.

**Comment by applepipe** [comment]
It doesn't suit my needs, I have a factory, orders are processed in weeks to be ready and the payment should be confirmed before delivery, POS doesn't work this way.

**Comment by kennethsequeira** [comment]
So if I am getting this straight, you want to enter payment before generating an invoice and later block the creation of unauthorized invoices or DN until the payment is confirmed right?

If you can give a detailed use case and there are multiple users who need this, we can tag it for feature request. You can still create Invoices with 'Unpaid' status. Once payment is received you can  create a DN against it. 

I'd request you to put up this on https://discuss.erpnext.com and see what feedback you get from the community.

**Comment by applepipe** [comment]
I think it is easy to explain in steps:

1. Customer call us and we make a sales order, in this phase price and payment terms are negotiated, if the customer is not already a customer or his history of payment is not very good they have to pay before delivery
2. Approved orders are processed, production orders are raised.
3. When everything is ready, payment is confirmed and invoice and delivery notes are made, the items leave the factory

I need to prevent the creation of the invoice and delivery note while the "advance payment" is not made against the sales order, that is should be negotiated in step 1 inside the payment terms.
