### ISSUE TITLE
Payment schedule error

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#12057]
Hello,

I'm testing the new payment terms, and when I've tried to make a sale with 5.47 grand total and 3 different due dates (33.34% + 33.33% + 33.33%), the amount of each term is 1.82 but a message saying that the total of the payment terms must be equal to the grand total.

I've tried to make a script to add 0.01 cent on the first payment while the sum of payments < grand total, it writes extra cents, but still can't save because of the same error message.

<img width="647" alt="screen shot 2017-12-15 at 1 55 37 pm" src="https://user-images.githubusercontent.com/18335894/34049799-d83bdd4e-e19f-11e7-97c0-2af900a783bf.png">

**Comment by tundebabzy** [comment]
Please add a screen shot

**Comment by applepipe** [comment]
hello @tundebabzy 

Here is my item table with just 1 item with total 5,47 

<img width="950" alt="screen shot 2017-12-15 at 3 21 02 pm" src="https://user-images.githubusercontent.com/18335894/34052947-b125f3c8-e1ab-11e7-81dc-2686b1fd2a54.png">

And here is the payment schedule

<img width="961" alt="screen shot 2017-12-15 at 3 21 10 pm" src="https://user-images.githubusercontent.com/18335894/34052971-cd006e02-e1ab-11e7-87f2-cd546dbc0fa4.png">

If I try to save the order, the message on the first post shows and I'm not able to save

**Comment by applepipe** [comment]
I've tested with price 5,48 now, it saves but the total of the payment amount is 5,49, the ideal solution is to add the difference to the first payment or remove on the last

**Comment by applepipe** [comment]
This is the code I used to try to solve this:

frappe.ui.form.on("Quotation", "validate", function(frm, cdt, cdn) {
total_das_parcelas = 0;
$.each(frm.doc.payment_schedule || [], function(i, d) {
  total_das_parcelas += flt(d.payment_amount);
});
while (total_das_parcelas < frm.doc.grand_total){
  cur_frm.doc.payment_schedule[0].payment_amount = (cur_frm.doc.payment_schedule[0].payment_amount + 0.01);
$.each(frm.doc.payment_schedule || [], function(i, d) {
  total_das_parcelas += flt(d.payment_amount);
});
}
while (total_das_parcelas > frm.doc.grand_total){
  cur_frm.doc.payment_schedule[0].payment_amount = (cur_frm.doc.payment_schedule[0].payment_amount - 0.01);
$.each(frm.doc.payment_schedule || [], function(i, d) {
  total_das_parcelas += flt(d.payment_amount);
});
}
});


But it didnt work on validate

**Comment by tundebabzy** [comment]
#12096

**Comment by MorezMartin** [comment]
Hello,
Error seems to persist
Total Payment Amount in Payment Schedule must be equal to Grand / Rounded Total
https://nextcloud.mh-receptions.com/s/CkQnEo9rP9gWrqR
Do i create a new issue ?
