### ISSUE TITLE
Payment schedule should generate payment slips

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#12058]
After some testing on the new payment terms I have a suggestion:

Each line on the payment schedule should generate another document like a "payment slip" so that we can eventually change dates, and consider on them the mode of payment, or even change the status when it is registered on the bank, this is the document that should be paid, it is also common to suspend the slips, or even amend its content.

The slips can be used to "sell a long receivable" to the bank, receiving the total minus interests, taxes and fees.

This is very common in brazil, its not something that applies only in my case, and I think that this is also applicable to other countries in some way.

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.
