### ISSUE TITLE
Domain change after initial configurations

### ISSUE THREAD

**Issue by meltedmoon** [frappe/erpnext#12068]
Hi ERPNext team,
We can see that you gave option to change the company domain at any time. But what we are experienced that we changed our domain to Schools (Education). I was not showing all tools and modules under school module.
So we had to reinstall a fresh copy to select the School domain to get all those tools and modules related to Education.
Thanks for such a nice ERP.
Regards.

**Comment by kennethsequeira** [comment]
@Zlash65 close the issue when the fix is merged

**Comment by meltedmoon** [comment]
Thanks for information
