### ISSUE TITLE
Task's kanban view keeps deleted data

### ISSUE THREAD

**Issue by Muvuk** [frappe/erpnext#12066]
Helo,

first of all, thank you for your work. This erpnext sofware is really awsome. (compared with odoo as well ;)

I tried to delete kanban views based on this:
https://discuss.erpnext.com/t/how-to-delete-a-kanban-board/23082

But the thing is, If i delete every tasks and projects too and then I open task's page, Ii still get data about the deleted project and there is no option to delete kanban views. ex: ERPNext Implementation

Maybe I get it wrong. 
If I create kanban on task page, I actually create a project or not? This thing is a mess for me. 

![screenshot at 2017-12-16 22-46-07](https://user-images.githubusercontent.com/5338127/34074628-8d3c23f2-e2b3-11e7-86de-ae16350a02e7.png)
![screenshot at 2017-12-16 22-45-49](https://user-images.githubusercontent.com/5338127/34074629-8d5f6fb0-e2b3-11e7-90f8-e0a6effad0d9.png)
![there-is-no-project](https://user-images.githubusercontent.com/5338127/34074630-8d7dff84-e2b3-11e7-9768-7cf40e70071e.png)

Thank you for your help.

**Comment by Zlash65** [comment]
![kanban-delete](https://user-images.githubusercontent.com/11695402/34076747-36609c3a-e316-11e7-9862-de931bc57d61.gif)
To delete the kanban, you need to delete it from `Kanban Board` list and its equivalent Project. Then reload and see if it still shows up?
