### ISSUE TITLE
Error logging in after upgrade

### ISSUE THREAD

**Issue by binary64** [frappe/erpnext#12067]
Hi I just upgraded my ERPNext, and then did a new-site, but I get the error (attached)
![image](https://user-images.githubusercontent.com/1680627/34074831-b1ef1226-e2af-11e7-8ca7-c513c9d7ddfc.png)

**Comment by kennethsequeira** [comment]
Hi, request you to post this issue on https://discuss.erpnext.com where you can expect replies from community members.
