### ISSUE TITLE
POS item added to the cart displays price as zero

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#12074]
Hello,
 
Items added to the cart on POS displays price as zero, the total is not displayed with correct value too.

<img width="314" alt="screen shot 2017-12-17 at 1 58 23 pm" src="https://user-images.githubusercontent.com/18335894/34081370-af7a750c-e332-11e7-8543-740f7e529f96.png">

Changing qty or applying discount makes the price appear.

**Comment by rohitwaghchaure** [comment]
@applepipe 

Thanks for reporting an issue, we have identified and fixed the issue and soon we'll release it
