### ISSUE TITLE
Payroll Workflow Suggestions

### ISSUE THREAD

**Issue by hballan** [frappe/erpnext#12070]
I reviewed the workflow for payroll in the new beta version. The main issue, I have with how the workflow works is that once salary slips are submitted it is impossible to go back and correct them if you find an error. This becomes a problem as the number of employees grows. So let’s say you are processing payroll for 100 employees and after creating and reviewing all the salary slips you submit them and create the journal entry, then you realize that there was an error in one of the employees. There should be a way to be able to go back to that particular employee make the necessary correction and resubmit. As the workflow is now it is impossible to do that and you have to completely delete all and start from the beginning. 

The current production version ERPNExt 9 is slightly better in this regard as if you find a mistake you can at least go back and return all the slips one by one to draft status make the necessary correction and resubmit. Even though the process is tedious to go back and individually return the slips to draft status at least you can do so. There should be an option to return the slips to draft status in bulk. But at least in version 9 you can do that. In the beta version  you can’t do this and you have to completely delete all the slips and start from the beginning.

Since in the beta version there is a “payroll document” that is linked to many “salary slips”, it should be easy to allow the user to amend the “payroll document” returning all the slips back to draft status in bulk so that you can make the correction and resubmit the slips. When you process payroll for a large number of employees specially when there are many components that are variable and change from month to month that need to be entered manually, data entry errors are bound to occur and there should be an easy way to fix them. 

Also in the beta version there still seems to be no way for you to select the “naming series” that will create the “Journal Entry” upon submission of slips. It just uses the first naming series for Journal Entry doc type as default. When you have a database with multiple companies this is a problem since you need to have a separate naming series for each company. An easy way around this is to allow the user to select the naming series before creating the “Journal Entry” or to simply add a “Series for Payroll (Journal Entry)” option for each company the same way it is added for “Fixed Asset Depreciation Settings”

**Comment by shreyashah115** [comment]
Hi @hballan, in the Payroll Entry DocType which you're referring to, when you submit the payroll, it only creates the salary slips in draft mode, you can view the salary slips, and then there's a custom button to submit them if you don't need any more corrections. Please review it once again, and let us know if you have any more queries.

**Comment by hballan** [comment]
Yes I am aware of the above, although submitting slips individually doesn't create the journal entry which is a separate problem on it's own. The journal entry is only created if you submit slips in bulk through the process payroll screen. Also there are a few issues here:

1. First, You can review the slips in draft mode and then submit them however if you need to modify any of the values in the components and save the slip if the component is in the salary structure then the value in the salary structure always overrides the manually modified slip value. We have a lot of employees that earn incentive bonuses these values vary every month and need to be entered manually. The workaround now is to go in and modify the variable value in the salary structure for all employees before generating the slips. A very easy fix for this is to stop the salary slip from reverting to the salary structure on saving, that way you can generate slips for all employees in one shot and go in to the slips modify the variable components and save. 

2. Second, if you go to the salary register report to try to review the draft slips before posting they don't show up as the salary register only shows submitted slips. It would be very helpful to allow a filter on the salary register report to show either draft slips or submitted slips, that way before posting you can run this report and verify the amount by component before submitting and creating the journal entry. I have contacted support about this and they suggested making a custom report which I did but unfortunately the report can only show "Gross Pay" "Total Deductions" and "Net Pay" it cannot show the individual salary components per column like the salary register which is more detailed. This is very easy to implement is extremely useful for review before posting.

3. Third, as they is no way to review currently in the salary register before posting if you go ahead and post the slips and then realize after reviewing the journal entry that there is an error it is very difficult to fix. In current version ERPNext 9, you have to delete the journal entry, go back to the salary slips and cancel them all one by one, no way to do it in bulk, so they revert to draft status, do the necessary correction and resubmit all. In the Beta version that support showed me ERPNext 10, the process is worse as slips are tied to payroll document and if you cancel the payroll document there is no way to resubmit it, so you basically have to redo the entire payroll process from the beginning. In the new version when you cancel a Payroll Document it should return it to draft status and flip all salary slips associated with it to draft status so that you can go to the one with the error fix it and resubmit the payroll generating a new correct journal entry.

The thing is if you have standard salary structures that don't change much this is not a major issue for you. But in most companies things aren't like this, many companies offer incentive programs and there are variable salary components that change from month to month, such as absence, overtime ect... The salary structure should be viewed as a template to speed up generation of slips, but the user should have the flexibility to modify the draft slip in any way he wants by adding components, removing components, changing values before saving and submitting. Also in any decent size organization, when you processing more than say 50 employees data entry errors are bound to occur and you need a simple workflow where you can go back and amend the slips and resubmit specially that ability to review the slips in draft mode before submitting through the salary register is not available which would greatly reduce errors.

These suggestions are really critical and very easy to implement they would be very beneficial to the everyone using ERPNext to process payroll and will greatly improve workflow.

**Comment by clarkejj** [comment]
see also https://github.com/frappe/hrms/issues/613

**Comment by PawanMeh** [comment]
These concerns have been addressed in version 11, Draft Salary Slips show up in Payroll Register and also "Employee Incentive" feature has been added. These can be reviewed and a new issue can be opened if these are found inadequate.

**Comment by PawanMeh** [comment]
These concerns have been addressed in version 11, Draft Salary Slips show up in Payroll Register and also "Employee Incentive" feature has been added. These can be reviewed and a new issue can be opened if these are found inadequate.
