### ISSUE TITLE
Cannot select previously created Contacts as Customer primary contact

### ISSUE THREAD

**Issue by joolsr** [frappe/erpnext#12076]
Using beta.erpnext.com

**To replicate
![peek 2017-12-17 21-14](https://user-images.githubusercontent.com/934876/34083891-8c75ff62-e36f-11e7-9ea1-673b8caea350.gif)
**

I created two contacts for a customer.
But when i try and select either of these contacts in the Customer they are not availavle, even though they are visible on the same screen.

**Comment by rohitwaghchaure** [comment]
@joolsr

Kindly enable is primary contact checkbox in the contact.

Closing issue, feel free to reopen if issue still persists

**Comment by joolsr** [comment]
I've checked again and see what you mean. Sorry for the false report
