### ISSUE TITLE
Setup Already Complete!!There were errors.

### ISSUE THREAD

**Issue by debanjangithub** [frappe/erpnext#12073]
I have created site , started with bench start  , however when I am going to create my company detail through browser I am getting following error

Setup Already Complete!!There were errors.

Need your help team

**Comment by tundebabzy** [comment]
Hi @debanjangithub
Thanks for using ERPNext. We use github for bugs. Please ask or search this question on the forum (https;//discuss.erpnext.com) . You are more likely to quickly get an answer there.
