### ISSUE TITLE
File Upload error

### ISSUE THREAD

**Issue by FlexsoftsTech** [frappe/erpnext#12075]
Hello
Please help me, i got this error ( Error for row (#22) : u'name') while i am trying to upload items by excel file

**Comment by nabinhait** [comment]
@FlexsoftsTech In which version you are getting this error?

**Comment by umairsy** [comment]
Request you to share this query on the ERPNext community forum first. If it is validated as bug, we can check into it.

Just for once if issue is related it #12089
