### ISSUE TITLE
Data Import - If Successful, uncheck field "Show only errors"

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#12087]
![screen shot 2017-12-18 at 4 35 01 pm](https://user-images.githubusercontent.com/910238/34103154-b6810a70-e411-11e7-9542-aae41a09a413.png)

**Comment by manassolanki** [comment]
@umairsy 
This is intentional, if there are thousands of row it will take time to show a long list which isn't required at all onload. If a user wants to see the success log, he can uncheck the field and can view it.

**Comment by umairsy** [comment]
Just all if all the record are imported, then it's not very intuitive that If you want to see successful records, then you will have to uncheck field "Show only errors".
