### ISSUE TITLE
Data Import - uName error

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#12089]
When trying to import file with child tables (like Quotation), getting following error. Tried in both CSV and excel format.

![screen shot 2017-12-18 at 4 49 45 pm](https://user-images.githubusercontent.com/910238/34103711-c756bb4a-e413-11e7-856f-bf2a96be796c.png)

Here is the excel file.

[Quotation5.1.xlsx](https://github.com/frappe/erpnext/files/1567674/Quotation5.1.xlsx)

**Comment by Zlash65** [comment]
Also 
![data-import](https://user-images.githubusercontent.com/11695402/34106458-49ab8102-e41e-11e7-90eb-8d22c0712cec.gif)
Whenever I attach a file, it throws error that file has already been attached.
And after that it shows status as success even though import failed
![data-import-2](https://user-images.githubusercontent.com/11695402/34106546-a3877bc2-e41e-11e7-8824-d05d791ee9d3.gif)
