### ISSUE TITLE
PDF name blank

### ISSUE THREAD

**Issue by ramareflectionindia** [frappe/erpnext#12080]
Blank pdf id generating during invoice pdf generation.

Kindly suggest

**Comment by tundebabzy** [comment]
@ramareflectionindia 
Please add screenshot/animated gif

**Comment by jaichavan** [comment]
Does the issue persist in the latest version, **v11.0.3-beta.34 () (staging)** ??

**Comment by jaichavan** [comment]
Hello, @ramareflectionindia tried to validate this in my test account, but no such error:

![GI-SI-pdf-blank-name](https://user-images.githubusercontent.com/40264279/56471075-96746700-646b-11e9-94dd-f1df7c84107e.gif)

Version details:

![image](https://user-images.githubusercontent.com/40264279/56471080-ac822780-646b-11e9-897c-0e91f66672a5.png)


Closing this thread now, if an issue arises feel free to reach out ;)
