### ISSUE TITLE
Functionality to freeze grids

### ISSUE THREAD

**Issue by Mishaal1021** [frappe/erpnext#12108]
Hi,

When reviewing any reports that are in grid format, the system doesn’t allow the user to freeze pane or to move/delete/add columns. Also, in some reports, the filter for date range is not available. This makes it really difficult for user to use ERP to review data within the system. The only way around it is to export the report in excel and modify it. 

I would kindly request that you consider this request – at least to allow users to freeze pane in standard grid reports. See example of delivery order trends report attached. This report, as useful as it is, cannot be used to review information for the current month of November. As you can see below, once I scroll to right to view November, my customer info disappears. At the very least, the first two columns should be frozen by default for this report, and other similar reports to increase usability. 

Regards,
[DNs.docx](https://github.com/frappe/erpnext/files/1571576/DNs.docx)

Mishal

**Comment by tundebabzy** [comment]
Hi @Mishaal1021
We are working on what we call DataTables. Once  added, you will be able to sort columns, remove columns, rearrange columns, edit cells and other cool stuff. It's close to release and it should solve the usability problems of the present reports. 

You can view the progress on frappe/frappe#4577

Based on this, I'm closing this issue but feel free to reopen if there are further concerns

**Comment by Mishaal1021** [comment]
@tundebabzy 

Excited for that upgrade. Quick question/comment - will we be to save these at a user or global level? Similar to JD Edwards, where each user can have different saved templates based on the information they need to review.

**Comment by strixaluco** [comment]
@Mishaal1021 
Yes, you can save customized reports: https://erpnext.org/docs/user/manual/en/customize-erpnext/articles/making-custom-reports-in-erpnext
