### ISSUE TITLE
Unallocated Amount field didn't update

### ISSUE THREAD

**Issue by PrakashH** [frappe/erpnext#12111]
Unallocated Amount didn't update in Payment Entry if some amount is adjusted in the write-off account.

![screen shot 2017-12-19 at 7 22 37 pm](https://user-images.githubusercontent.com/4570016/34160636-b7f71a2e-e4f3-11e7-9dd0-c6741ec57e31.png)

**Comment by nabinhait** [comment]
@PrakashH Fixed, please test and confirm.
