### ISSUE TITLE
'Standard Selling Rate' in Item Master Does Not Update Selling Standard Price 

### ISSUE THREAD

**Issue by kennethsequeira** [frappe/erpnext#12129]
The Standard Selling Rate Field in Item master is a text field which gives the user the impression that the pricing can be changed from there. But change has to be made from **Price List**

The text field serves no purpose other than entering the price while creating the item and even that is for just creating the valuation rate. If you enter valuation rate, the selling price field is rendered obsolete.

![item-standard-selling](https://user-images.githubusercontent.com/33246109/34245059-4c861cca-e64e-11e7-90fc-ac7f7293f352.gif)

Proposed Solutions:
* link the field to Standard Selling Price for the Item so user can change the price from Item Master itself

* make it a 'View Only' and pull the rate from the Price List. 

* Change the label to something else which makes more sense.

https://discuss.erpnext.com/t/item-standard-selling-rate-vs-selling-price-list/31812

**Comment by nabinhait** [comment]
Made the standard rate field hidden after saving the item record.

**Comment by kennethsequeira** [comment]
Issue still not resolved. Let the issue remain open until then.

https://github.com/frappe/erpnext/issues/12744

**Comment by aleoses** [comment]
Hi @kennethsequeira does this feature would be done at all?

**Comment by heatherpotter** [comment]
This is badly needed. Has it been completed yet? There should not be a field on Item master that isn't ever updated.

**Comment by KenyanGeek** [comment]
This is a big problem i had to do every item manually wasting a lot of time @kennethsequeira the workarounds with Data import are not helpful
