### ISSUE TITLE
Suggestions on Make To Order

### ISSUE THREAD

**Issue by nabinhait** [frappe/erpnext#1212]
Material request from sale order/production order/production planning tool
1. From production order, we should be able to "request material". right
   now, only material transfer is there.
   (scenario : some item transfered earlier got spoiled so, addiional qty
   required or some substitute, not in BOM may be required, some item not in
   store/sock need to be purchased to complete that production order etc)
2. in the production planning tool, if for a sale order, production order
   is already created for that sale order, the it should be listed. then
   material request, should be possible from here, so that both sale order
   and production orders are linked to material request, material transfer,
3. If already a purchase request exist for that item for some other sale
   order or production order, when we click "Create material request", it
   says nothing to request.
   we should be able to request and reserve for each sale order and
   production orders.
- From Mustafa

**Comment by umairsy** [comment]
@nabinhait can we close this?

**Comment by umairsy** [comment]
given the latest updates in V8, closing. Reopen if needed.
