### ISSUE TITLE
Leaderboard doesn't have a company selection

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#12122]
Leaderboard uses default company, but with multiple companies without one being the default (could lead users to errors) it gives an error.

**Comment by pratu16x7** [comment]
Screenshots? Leaderboard doesn't seem to be dependent on a company, so can't see a way to replicate this.

**Comment by applepipe** [comment]
Hello @pratu16x7 

![untitled](https://user-images.githubusercontent.com/18335894/34320038-5575e0f6-e7d7-11e7-9842-572463b3dbc2.gif)

It happens just opening the leaderboard without a company set as default on a multi company setup

**Comment by applepipe** [comment]
https://github.com/frappe/erpnext/issues/12181

**Comment by vishdha** [comment]
https://github.com/frappe/erpnext/pull/13001
