### ISSUE TITLE
COA - group account does not accumulate

### ISSUE THREAD

**Issue by federicocalvo** [frappe/erpnext#12137]
Hi! I have a problem that I'm not finding a solution to.

Some parent accounts do not add up children accounts.

![captura de pantalla 2017-12-21 a la s 09 41 03](https://user-images.githubusercontent.com/7256766/34256394-da12561e-e633-11e7-92e7-9d7757e19078.png)

We were changing the parents of some accounts and that's when the problem arose.

We try to restart bench, bench cache, bench static, but without results.

Any idea if this is a bug or can I fix it in any way?

Thank you.

**Comment by manassolanki** [comment]
Hi  @federicocalvo , Please post your help queries on discuss forum. If you found a replicable bug, please reopen the issue with the steps to replicate.
