### ISSUE TITLE
Print format for KSA Sales Invoices

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#12132]
- Add Delivery Date field
- Add Tax Rate and Amount in the Item table
- Create Print Format as "Saudi Arab B2B Invoice"

English

![screen shot 2017-12-21 at 1 05 30 pm](https://user-images.githubusercontent.com/910238/34245380-aab6e436-e64f-11e7-96be-3a1f8c07412a.png)

Arabic

![screen shot 2017-12-21 at 1 05 36 pm](https://user-images.githubusercontent.com/910238/34245382-ae117b64-e64f-11e7-84bb-47a6dcce5123.png)

**Comment by ushashmi** [comment]
Item Tax Rate and Tax amount is also required to be shown in UAE VAT invoice. Can we also have these two fields in item table of UAE Invoice

**Comment by FlexsoftsTech** [comment]
if tax zero in master also should be zero in Sales invoice, the system should calculate tax item row-wise now
