### ISSUE TITLE
ERPNext Easy Install script for v.9 doesn't work on CentOS7.4 VPS

### ISSUE THREAD

**Issue by fernandobender** [frappe/erpnext#12138]
...but it does on Ubuntu 16.04.
here's the story.

dear fellows,

i'm reporting what i've experienced yesterday.
i tried to install ERPNext v9 through easy install as described here https://github.com/frappe/bench
i tried it
1. as root. using
python install.py --production --user frappe
2. as non root sudo privileged user, using
sudo python install.py --production
Both yield the same error.
which is a little after password requests for mariadb & admin, it switches to frappe user.
then the script breaks.

i've solved it by trying with Ubuntu 16.04
it worked flawlessly on the same VPS specs (512Mb RAM + 2Gb cache @ DigitalOcean)
sorry if that was reported before, but afaik, it wasn't.

I humbly, kindly, suggest to limit the scope of Easy Install to Ubuntu as it is working. Cases other than that can be tackled with manual install. in my view, it makes sense that easy install is scope limited and works fast. it seems to me as an intermediate step between the VM upload and the manual install.

Tremendous product. Quite charming to use. Great thanks! @rmehta and team.

**Comment by umairsy** [comment]
Please report this issue on the community forum.

https://discuss.erpnext.com
