### ISSUE TITLE
different batch in Material Transfer for Manufacture

### ISSUE THREAD

**Issue by risk2k** [frappe/erpnext#12144]
Currently when you create a Stock Entry by using the Material Transfer for Manufacture function in a Production Order it proposes to transfer the exact quantity  to the Target Warehouse (e.g. Work in Progress).
Often we need to move items from the BOM from different batch, as a result we have to manually add more lines of goods from other parties.
At the end of production, this has to be repeated again.

Is it possible to copy in essence all the lines together with the batch numbers in the Stock Entry at the finish of production?

**Comment by risk2k** [comment]
When i have 50 included items in BOM - hard to choose different batches for several items.

**Comment by umairsy** [comment]
Hello,

You can use batch-selector for selecting multiple batches of an item in a single view, without adding a separate row for the item.

![screen shot 2017-12-26 at 3 04 22 pm](https://user-images.githubusercontent.com/910238/34353444-26ee092e-ea4e-11e7-9009-860d9a0721b7.png)

**Comment by risk2k** [comment]
always insert by one item when in bom 50? 100& items? - good joke. for make finish manufacturing need 1 hour for print manually items,  verify....  very bad answear

**Comment by risk2k** [comment]
i see batch selector only when insert new row with product

**Comment by pratu16x7** [comment]
How should the batch numbers be selected by default, without manual input for multiple items?

**Comment by risk2k** [comment]
Maybe I'm wrong, but from those that were transferred to this production.

**Comment by risk2k** [comment]
and open batch selector only for item if transfered for manufacturing several batches.
