### ISSUE TITLE
[Paid Development][Feature Request] BOM Stock Report for Exploded BOM

### ISSUE THREAD

**Issue by djpalshikar** [frappe/erpnext#12148]
We regularly use BOM Stock Report. It is very useful. Would like to have a check BOX which shows the stock report of the exploded BOM. I am willing to sponsor it.

**Comment by asharamseervi** [comment]
@djpalshikar Kindly write your expectation in detail, so anyone will easily pick and contribute, might you get it without payments. So, Kindly write complete expectation, what & how will happen, and how it will be useful for others. Thanks.

**Comment by djpalshikar** [comment]
As such it is pretty straightforward. The following screenshot should help, let me know if there is a specific doubt:
![bom_stock_report_text](https://user-images.githubusercontent.com/23133635/34319117-91d1bce6-e7ff-11e7-8396-8ac7b5db264b.png)
