### ISSUE TITLE
Required HR features - Loan - Salary Slip - Calculation method

### ISSUE THREAD

**Issue by FlexsoftsTech** [frappe/erpnext#12146]
Required Features in HR
1- Showing up total salary Earning type in salary slip, if there is absence deduction or any other deductions type should be in deductions side (no need to see default amount in earning side)
2- automatically deduct loan based payment dates in a loan application and adding a button to skip loan deduction for a certain month and once user select to skip loan deduction and the system should create new deduction date in the loan application, also it is important to add loan status if deducted or pending or skipped 
3- creat to a field in HR setting to set default deduction type for loan and absence to be picked up automatically in salary slip when the employee has a deduction amount
4- create options for a number of working days per-month if fixed days (in KSA always 30 days for absence calculation) or actual month days number, if the client select fixed number of working days (30) system should consider all the days in attendance file upload

**Comment by aakvatech** [comment]
2- automatically deduct loan based payment dates in a loan application and adding a button to skip loan deduction for a certain month and once user select to skip loan deduction and the system should create new deduction date in the loan application, also it is important to add loan status if deducted or pending or skipped


I am working on this, need help to make test cases and polish up the solution.

**Comment by aakvatech** [comment]
1- Showing up total salary Earning type in salary slip, if there is absence deduction or any other deductions type should be in deductions side (no need to see default amount in earning side)

This is partially possible by not deducting leave without pay on any earning. Create a deduction based on leave_witout_pay days

**Comment by aakvatech** [comment]
5. Am adding Loan Repayment Not From Salary doctype too in order to allow ad-hoc loan repayments made outside the salary.

**Comment by aakvatech** [comment]
> 2- automatically deduct loan based payment dates in a loan application and adding a button to skip loan deduction for a certain month and once user select to skip loan deduction and the system should create new deduction date in the loan application, also it is important to add loan status if deducted or pending or skipped

Do you also see a need to adjust the monthly amount upwards or downwards at times? If so then the rescheduling is more complex but probably necessary. In our part of the world that is very common.
