### ISSUE TITLE
POS Not Validating Serial Number at time of Sale

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#12147]
Hi,

The offline POS is not validating serial numbers at the point of sale! Now we have several errors blocking the sync. All those errors refer to duplicate serial numbers as shown below:

"Serial number 10908xxxxx already referenced in Sales Invoice SINV-xxxxx"

Please fix urgently 

Thanks

**Comment by rohitwaghchaure** [comment]
Hi @Olawale1 

Kindly remove the sales invoice from the serial no 10908xxxxx. I am trying to replicate this issue on local account but not able to replicate it. I did following steps

1. Created sales invoice from the offline POS for the serial no ABC00010

1. Tried to add serial no ABC00010 again in the new sales invoice but not able to add it because it's already delivered

Can you please share steps to replicate the issue

**Comment by Olawale1** [comment]
Hi @rohitwaghchaure 

Thanks for your response. Steps to replicate

1. Create sales invoice from the offline POS for the serial no ABC00010
2. Immediately click on 'reload' option under menu (while the sales invoice is still in customer queue)
3. Select a new Customer and add serial no ABC00010 again in the new sales invoice 

Both invoices will now appear in the queue. One will get synced while the other gives errors as described above

Thanks

**Comment by jaichavan** [comment]
Hello, in the latest version [ v11.0.3-beta.34 () (staging) ], there is no such issue, that I could replicate.. The system doesn't let you fetch the serial number that has already been used in the sales invoice (through Offline POS) Attaching screenshots from my test account for your reference:
1. POS Invoice for an item with serial number IRL_BH1750_LIM000032 :

![image](https://user-images.githubusercontent.com/40264279/51364714-130d4780-1b03-11e9-9c40-f87460ede683.png)

Item Serial Number whose invoice is made via POS - IRL_BH1750_LIM000032

![image](https://user-images.githubusercontent.com/40264279/51364968-0806e700-1b04-11e9-9a60-4812e17e3348.png)


2. When I clicked on Reload and tried to create another Sales Invoice, and creating new invoice, then it's not allowing to fetch same serial number, as below:

![image](https://user-images.githubusercontent.com/40264279/51364960-f8879e00-1b03-11e9-87e2-56fdda74ee4d.png)

Hope this helps. Thanks for reporting!!
