### ISSUE TITLE
Error opening company on develop branch

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#12143]
Hello,

I get this error everytime I try to open company on develop branch, I have a multi company setup

<img width="631" alt="screen shot 2017-12-22 at 10 00 26 am" src="https://user-images.githubusercontent.com/18335894/34297448-5a41f80a-e6ff-11e7-81dc-ccb618c5fae9.png">

This is the error on console:
<img width="452" alt="screen shot 2017-12-22 at 10 00 45 am" src="https://user-images.githubusercontent.com/18335894/34297450-5b85504a-e6ff-11e7-960c-6dd1e59cee33.png">

**Comment by umairsy** [comment]
This issue seems to be related to customizations in your ERPNext account. Please post this issue the community forum.

https://discuss.erpnext.com

**Comment by applepipe** [comment]
hello @umairsy 

I don't have any customisations in company doctype, the only thing is that I use pt-BR as language, this error happens before list view. I don't have any custom app either.

**Comment by applepipe** [comment]
please reopen
