### ISSUE TITLE
Error on purchase invoice, cannot read taxes_and_charges

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#12140]
Hello,

After the last update I'm not able to make a purchase invoice, this is the error on console:

"Failed to load resource: the server responded with a status of 403 (FORBIDDEN)
jquery.min.js:4 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ jquery.min.js:4
erpnext.min.js:1845 Uncaught (in promise) TypeError: Cannot read property 'taxes_and_charges' of undefined
    at erpnext.min.js:1845
    at <anonymous>"

**Comment by tundebabzy** [comment]
Hi @applepipe 
Please add some context, screenshots/gif

**Comment by applepipe** [comment]
Hello @tundebabzy 

Just by hitting the new button to make a new purchase invoice the error appears in the console.

Here is a gif:
![untitled](https://user-images.githubusercontent.com/18335894/34262715-4aa134fc-e654-11e7-9b9c-9422c4f23bc4.gif)

**Comment by tundebabzy** [comment]
I can't reproduce this on latest develop.

![peek 2017-12-21 17-08](https://user-images.githubusercontent.com/818803/34264029-c19dda66-e671-11e7-82e1-976df8dc56bc.gif)

Try bench migrate and bench build again. Please reopen if need be.

**Comment by applepipe** [comment]
I'm on develop branch, just updated now but the error persists

ERPNext: v9.x.x-develop (45cb791) (develop)

Frappe Framework: v9.x.x-develop (d5ad0ff) (develop)

**Comment by joezsweet** [comment]
Do you have some custom code?

**Comment by applepipe** [comment]
Hello @joezsweet

I do have some add_fetch on the document, but nothing related to taxes or anything that read or writes on that field.

**Comment by applepipe** [comment]
This was apparently solved with latest updates

**Comment by applepipe** [comment]
I was wrong, it is still giving this error

**Comment by tundebabzy** [comment]
Can you test if this also has to do with workflow

**Comment by applepipe** [comment]
hello @tundebabzy I've disabled all workflows, apparently it is not realted

**Comment by tundebabzy** [comment]
Hi @applepipe 
Does this still persist?

**Comment by applepipe** [comment]
Hello @tundebabzy I've tested again and it's working fine now
