### ISSUE TITLE
[Bug] Stock entry(type Manufacture) from BOM, raw material item not being added

### ISSUE THREAD

**Issue by djpalshikar** [frappe/erpnext#12142]
If a new Stock Entry - type Manufacture is created from a BOM, and the BOM includes an item which has "Supply Raw Materials for Purchase" enabled; item is not fetched in the items table. This is similar to issue #11746 .
![stock_entry_for_manufacture](https://user-images.githubusercontent.com/23133635/34297027-94389b9a-e73b-11e7-9cf1-e1a2fcbad80f.gif)

**Comment by umairsy** [comment]
Hello,

Rohit has pushed a fix based on my earlier Issue reported.

https://github.com/frappe/erpnext/pull/11996
