### ISSUE TITLE
Print Format Issue

### ISSUE THREAD

**Issue by MANOJMAINKAR** [frappe/erpnext#12159]
It is observed that for customize print  format we use to get document status as 'Draft' in actual printouts earlier and now it is not appearing even if in print setting , checked - Always add "Draft" Heading for printing draft documents.

For last so many years it was working fine with all print formats  , we are facing the same issue from last few months , may be due to changes /updates in package .

**Comment by umairsy** [comment]
Now, it has been made configurable from Print Settings. Ensure that field "Always add "Draft" Heading for printing draft documents" is checked in Print Settings.

**Comment by MANOJMAINKAR** [comment]
It is not working , for our customize print formats created earlier .
For years we use to get 'Draft' heading earlier. 

On 26-12-2017 03:14 PM, Umair Sayed wrote: 

> Now, it has been made configurable from Print Settings. Ensure that field "Always add "Draft" Heading for printing draft documents" is checked in Print Settings. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/frappe/erpnext/issues/12159#issuecomment-353947023
[2]
