### ISSUE TITLE
Replace relative date with real posting or real last modification date in list view

### ISSUE THREAD

**Issue by gbard** [frappe/erpnext#12152]
I think it would be better to use the real dates in list view than to use the "relative date" ex: "2 days ago". It's easier to find Sales Invoices or other documents when you can see the real posting/last modification date. To solve the issue I added {posting_date} to the default document title because I wanted to also diplay the doc.name and territory to my Sales Invoices listing and since we are limited to 5 collumn I couldn't add everything I want without this trick...

Let me know if you agree with me!

**Comment by clarkejj** [comment]
see also https://github.com/frappe/erpnext/issues/8283

**Comment by tundebabzy** [comment]
closing in favor of #8283
