### ISSUE TITLE
[Bug?] Purchase Receipt: from Draft to Not Saved on page reload

### ISSUE THREAD

**Issue by joezsweet** [frappe/erpnext#12155]
Hi there,

on `Purchase Receipt`, document status change from `Draft` to `Not Saved` on reload, without any modification, see gif:

http://g.recordit.co/Vpx9tjNCnA.gif

ERPNext: v9.x.x-develop (45cb791) (develop)
Frappe Framework: v9.x.x-develop (d5ad0ff) (develop)

Can someone double check and confirm?

**Edit**: _checked in beta.erpnext.com and got same problem._

**Comment by Zlash65** [comment]
Not just `Purchase Receipt`, this happens in all those doctypes where time field has been used. Upon opening a doc it shows "not saved" becuase in the time field 'hh:mm:ss' is loaded and not milliseconds which accounts for a dirty form. After a reload the millisecond part gets loaded and it shows the correct status.

**Comment by joezsweet** [comment]
I see, how can we fix that?

**Comment by joezsweet** [comment]
@Zlash65 any news on this? Hint on how to fix?

**Comment by nabinhait** [comment]
Fixed this on latest release.
