### ISSUE TITLE
Brand image in website setting 

### ISSUE THREAD

**Issue by dufani1** [frappe/erpnext#12154]
Hii,
When I am trying to reinstall brand image I am getting the following message even after removing the image and clear browser cache. And the brand dose not appear.

![untitled](https://user-images.githubusercontent.com/23026263/34325349-c1179c62-e897-11e7-939d-f0b125ab9c6a.png)

**Comment by manassolanki** [comment]
Hi @dufani1 ,
Please update your repo, the issue has been fixed recently.

**Comment by dufani1** [comment]
Thanks I will check
