### ISSUE TITLE
New asset maintenance bug: error when click Sell Asset : the resource you are looking for is not available

### ISSUE THREAD

**Issue by szufisher** [frappe/erpnext#12166]
error when click Sell Asset : the resource you are looking for is not available
frappe and erpnext version : v10
steps to reproduce
1. create new asset and submit
2. click the Sell Asset, there is the error message in the popup window,

Per the browse console, and further check the asset.js, the path name should be changed from 
accounts to assets, because the asset module has been moved from accounts module to its own module.

Here the extract of the code with context.

method: "erpnext.accounts.doctype.asset.asset.make_sales_invoice",

to method: "erpnext.assets.doctype.asset.asset.make_sales_invoice",
make_sales_invoice: function(frm) {
		frappe.call({
			args: {
				"asset": frm.doc.name,
				"item_code": frm.doc.item_code,
				"company": frm.doc.company
			},
			method: "erpnext.assets.doctype.asset.asset.make_sales_invoice",
			callback: function(r) {
				var doclist = frappe.model.sync(r.message);
				frappe.set_route("Form", doclist[0].doctype, doclist[0].name);
			}
		})
	},
already verified in my local instance.

**Comment by rohitwaghchaure** [comment]
@szufisher 

Thanks for reporting an issue, we've fixed this and soon we'll release it
