### ISSUE TITLE
Payment Terms in Delivery Note

### ISSUE THREAD

**Issue by snvora** [frappe/erpnext#12167]
If delivery note is made prior to sales invoice, then payment terms do not get carried forward from sales order to sales invoice.

**Comment by umairsy** [comment]
Can you please mention the order in which transactions were made?

Also, is Due Date happening to be different in Delivery Note and Sales Invoice?

**Comment by tundebabzy** [comment]
@snorva
By design, payment terms are not copied into related documents except the source document has specified a payment terms template. The reason is that the payment terms schedule is calculated based on the dates in the source document. Copying the data ensures that the payment terms will almost always be wrong in the derived document especially recurring documents.

**Comment by snvora** [comment]
Hello,

I am not sure my problem is correctly conveyed.

Let me explain this in detail.

A customer has default payment term as N45 (45 days from date of invoice). For specific order, payment term is N30. So while creating order, we say N30 in payment terms.

Now we first create delivery note from sales order. Then from delivery note we create sales invoice. (This is the flow which many might be following.)

In sales invoice, we expect to see N30 as payment term and due date calculated accordingly. But instead we find N45 as payment term.

So I suggested to add payment term to delivery note. Hope you get the problem?

**Comment by tundebabzy** [comment]
I now understand. Delivery note looks like a very inappropriate place to choose payment terms. Why not create the invoice from the linked sales invoice?

**Comment by snvora** [comment]
@tundebabzy 

> create the invoice from the linked sales invoice?

Did u mean create invoice from sales order?

We are in trading business. So, first stores check with quantity, verify goods being delivered and load them on truck, and prepare delivery note with transporter details like transporter name, vehicle number, lorry receipt number etc.

From this we create Invoice, so invoice is made with all details like
- Transporter details
- Associated delivery document reference.
As invoice is final document, there references are important for customer.

This  will  not be possible if sales invoice is created first.

Well, I am sure this process would surely be followed by a lot of erpnext users as many of them are in trading and manufacturing business and this is generally the process followed.

I completely understand that delivery note is not the right place for payment terms, as stores have nothing to do with payment terms.

**I can suggest alternative way of implementing this.**
- In file `delivery_note.py` code for `make_sales_invoice` could be updated to fetch payment terms in sales invoice from sales order.
**Or**
- Payment terms fields are hidden in delivery note. They are just being used to carry payment terms from Sales order to Sales Invoice.

I m not a coder, so I don't know if this is feasible or the right way to do this. What do you have to say?

**Comment by tundebabzy** [comment]
> In file delivery_note.py code for make_sales_invoice could be updated to fetch payment terms in sales invoice from sales order.

We always avoid doing stuff like this.

> Payment terms fields are hidden in delivery note. They are just being used to carry payment terms from Sales order to Sales Invoice.

I think we can implement this. We'll give users the option of specifying Payment Terms Template **only**. It will also be hidden from print view. I think this should work without any brain twisting.

**Comment by tundebabzy** [comment]
Implemented in #12293

**Comment by snvora** [comment]
Great Work Brother...! :-)
