### ISSUE TITLE
Disabled Reports showing in global search

### ISSUE THREAD

**Issue by snvora** [frappe/erpnext#12169]
Some reports may be disabled, which should not come in global search.

**Comment by umairsy** [comment]
Can you please share the example / screenshot / GIF etc.? This will help us get the context better and resolve it faster, where needed.

**Comment by snvora** [comment]
Say, we have custom report for GST. So we disabled a report as follows


![capture](https://user-images.githubusercontent.com/10496564/34372815-47f4c7f2-eafd-11e7-9fea-bf3130250914.PNG)



**After that, when we search in global search for report we get following results**



![image](https://user-images.githubusercontent.com/10496564/34372870-abd2f7d0-eafd-11e7-8a09-ab06e9e67821.png)





![capture_1](https://user-images.githubusercontent.com/10496564/34372836-65a6d8a8-eafd-11e7-8ee3-c62042eb295e.PNG)

**Comment by jaichavan** [comment]
Hello, @snvora 
The report in question, GST Itemised Sales Register is _operational_. Attached screenshot from v11.0.3-beta.34 () (staging)

![image](https://user-images.githubusercontent.com/40264279/51364095-f40db600-1b00-11e9-8941-4e5aa626231a.png)
 
Closing the issue, thanks for reporting!!
