### ISSUE TITLE
Last Purchase Price in Item Price Report not showing values when Purchase invoice with update stock done

### ISSUE THREAD

**Issue by savadibrahim** [frappe/erpnext#12162]
![last purchase price](https://user-images.githubusercontent.com/12373609/34339962-6f1f77da-e9a1-11e7-81d6-225108a33439.png)

When Purchase Invoice is made without PO or Purchase Receipt,last purchase price is not getting updated

**Comment by umairsy** [comment]
Can you please check if Last Purchase Rate is updating correctly in the Item master? Please also share the version of your ERPNext account.
