### ISSUE TITLE
Standard Print Format Spacing

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#12175]
![screen shot 2017-12-26 at 4 10 41 pm](https://user-images.githubusercontent.com/910238/34354903-9da7a7f6-ea57-11e7-96e3-c1b1427bd3e0.png)

**Comment by netchampfaris** [comment]
Maybe need a redesign to Standard Formats ?

**Comment by netchampfaris** [comment]
Issue is due to changed custom label. Closing.
