### ISSUE TITLE
Production Order from Sales Order not may choose products for create Production Orders

### ISSUE THREAD

**Issue by risk2k** [frappe/erpnext#12179]
When i create Production Order from Sales Order - i not may choose not all product( always create Production Orders for all items in Sales Order.

You need to be able to select the rows for which you want to create production orders.

When pressed, a list of all the lines goes out without the ability to delete the row (the Delete button is there, but pressing it does not affect anything)

**Comment by tundebabzy** [comment]
Hi @risk2k 
Please show a screenshot

**Comment by risk2k** [comment]
![111](https://user-images.githubusercontent.com/34770567/34359280-4ae27002-ea5f-11e7-86d2-e6c675829842.JPG)


Its form when i press create Product Order from Sales Order
Red button - delete 
When i check anything and press delete - it's not delete, may make only product orders for each product in list
