### ISSUE TITLE
No Multiple mode of payment for purchase invoice/receipt -[BUG] Landed cost voucher cant be created if made multiple payment entry(different MOP) for that transaction

### ISSUE THREAD

**Issue by taherkhalil** [frappe/erpnext#12176]
Refer:
https://discuss.erpnext.com/t/make-payment-through-multiple-mode-of-payments-in-purchase-reciept-invoice-and-lcv-mode-of-payment/31980

purchase invoice should be able to pay with multiple mode of payment just like  **sales invoice** 
and should be a option to choose payment mode /account for Landed cost voucher payments.

Seems like a very basic and generic feature , surprised no one pointed it out.
Thanks

**Comment by taherkhalil** [comment]
@umairsy , could you please comment if not being able to create a LCV for invoice if multiple partial payments of different mode are made ,  is a **BUG** or was it intended to prevent some scenario?

Thanks for all the hard work

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.
