### ISSUE TITLE
UOM list missing link to Item master

### ISSUE THREAD

**Issue by ushashmi** [frappe/erpnext#12183]
While making Purchase order/SO/Invoice etc., the UOM list should show the UOMs which are associated with that item master only. Currently the whole list of UOM is generated if we want to change the default UOM to Purchase/Sale UOM.

**Comment by umairsy** [comment]
Currently, UoMs are not filtered based on the configuration in the Item master. Even if UoM is not mentioned in the Item, you can use it on the fly and mention Conversion Factor.
