### ISSUE TITLE
Sr No column does not reset after sorting

### ISSUE THREAD

**Issue by nabinhait** [frappe/erpnext#12186]
<img width="582" alt="screen shot 2017-12-27 at 11 42 27 am" src="https://user-images.githubusercontent.com/836784/34372486-244e5a18-eafb-11e7-94ed-c97153c10d07.png">

**Comment by netchampfaris** [comment]
@nabinhait This was intentional 😅. Should the Serial order also be reset after sorting?

**Comment by tundebabzy** [comment]
I think users should be able to sort the serial numbers so that users can get the table back to its initial state (without sorting)
