### ISSUE TITLE
Sales invoice, purchase order & purchase receipt saved as draft via REST API

### ISSUE THREAD

**Issue by akhileshkhanduri** [frappe/erpnext#12197]
hello guys
we are integrating erpnext with a mobile application and using erpnext Rest apis to communicate with eptnext platform, issue arise when we send Sales invoice, purchase order or purchase receipt but it doesn't get submitted automatically instead it is saved as draft so we have to go erpnext console to submit them. 

Here is the Json we are using, can you guys tell me what am i doing wrong here
{
	"naming_series": "SINV-TA",
	"customer": "C362264",
	"customer_name": "C362264",
	"is_pos": "1",
	"company": "Test-Akhilesh",
	"posting_date": "2017-12-23",
	"due_date": "2017-12-23",
	"currency": "INR",
	"selling_price_list": "Retail-Selling",
	"price_list_currency": "INR",
	"discount_amount": 0,
	"apply_discount_on": "Grand Total",
	"cash_bank_account": "Cash - TA",
	"write_off_amount": 0,
	"debit_to": "Debtors-Retail - TA",
	"remarks": "via b2b mobile app",
	"customer_group": "Individual",
	"submit_on_creation": "1",
	"against_income_account": "Sales - TA",
	"paid_amount": 360,
	"mode_of_payment": "Cash",
	"is_opening": "No",
	"status": "Paid",
	"amount_received": "360",
	"amount_returned": "0.0",
        "update_stock": 1,
	"items": [{
		"item_code": "f-r-02",
		"item_name": "Orange",
		"qty": "2",
		"rate": "80.0",
		"expense_account": "Sales Expenses - TA",
		"cost_center": "Main - TA",
		"warehouse": "FG - TA",
		"parenttype": "SalesInvoice",
		"parentfield": "items"
	}, {
		"cost_center": "Main - TA",
		"qty": "2",
		"warehouse": "FG - TA",
		"item_code": "f-r-01",
		"item_name": "Orange Big",
		"rate": "100.0",
		"expense_account": "Sales Expenses - TA",
		"parenttype": "Sales Invoice",
		"parentfield": "items"
	}],
	"payments": [{
		"mode_of_payment": "Cash",
		"amount": 360,
		"account": "Cash - TA"
	}]
}

**Comment by joezsweet** [comment]
Can you share the code?

**Comment by joezsweet** [comment]
I think you need to first save and then submit

**Comment by akhileshkhanduri** [comment]
can you please assist me how to do that?

**Comment by joezsweet** [comment]
please post at https://discuss.frappe.io
