### ISSUE TITLE
[New Feature] enhancement proposal for the new asset maintenance module

### ISSUE THREAD

**Issue by szufisher** [frappe/erpnext#12196]
After trial run the new asset maintenance module  in V10, I got the following enhancement proposals

1.  New fields to be added

- Sub No. : this is to track multi linked asset as one big set of asset, e.g a set of big machine with many different component, there will be a main asset number, but for components, they can be identified as subno.
- Assigned To : this is the person who is currently use / manage this asset
- Cost Center :  for booking
- Serial No. , this is the inventory number as barcode attached to the physical asset
- Manufacturer
- Model
- Location : this is not the same as warehouse, it is where the asset physically located.

2. Add asset movement, asset scrap and sales invoice(Sell asset) into dashboard

3. enhance the asset movement doctype as following,
( for asset movement, except tracking the physical location change, the most important thing is to track the changed responsibility (responsible person) and cost center for accounting booking.)
- add the following fields 
   - from assigned to
  - to assigned to
- from location
 - to location
  - from cost center
  - to cost center

- make the above added fields available in the dialog box for input

- add workflow to allow approve by both from and to cost center's owner for the asset movement

4. add one asset history sheet report to combine all asset transactions in one single report

**Comment by rmehta** [comment]
Should be fixed with v11
