### ISSUE TITLE
Error on purchase order list view when work flow is enabled 

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#12207]
After today's update when I try to open purchase order list it doesn't load and shows an error on the console, here is the gif:

![untitled](https://user-images.githubusercontent.com/18335894/34381049-29ca27a0-eaed-11e7-9779-7863e4a3c008.gif)

**Comment by applepipe** [comment]
This is happening with item too

**Comment by tundebabzy** [comment]
Works well for me.

![peek 2017-12-27 23-14](https://user-images.githubusercontent.com/818803/34394767-bd5e2782-eb5b-11e7-87b8-2e89713ebbfe.gif)

Make sure javascript and css assets were built and loaded properly

**Comment by applepipe** [comment]
hello @tundebabzy 

I ran bench build again, nothing changed, updated now and the same error persists, I don't have any custom app or any customisation besides some add_fetch.

**Comment by applepipe** [comment]
@tundebabzy I think is something related do workflows, every document that I have a workflow has this error, disabling it allows me to see list

**Comment by tundebabzy** [comment]
OK. That's a good start.

**Comment by creamdory** [comment]
We are experiencing the same with our Doctypes with workflows.

**Comment by shreyashah115** [comment]
@tundebabzy I am able to replicate this.

**Comment by bohlian** [comment]
Experiencing the same problem. Its related to the new List View https://github.com/frappe/frappe/blob/d9483acbdd60129b980f3390afd25ee397f75512/frappe/public/js/frappe/list/base_list.js

it isnt able to do a push on the workflow_state

`list.min.js?ver=1516099101.0:1327 Uncaught (in promise) TypeError: Cannot read property 'push' of undefined
    at ListView._add_field (list.min.js?ver=1516099101.0:1327)
    at ListView.set_stats (list.min.js?ver=1516099101.0:1337)
    at <anonymous>`

**Comment by creamdory** [comment]
This has been fixed. Just pulled the above commit and tested.
