### ISSUE TITLE
[Critical] Accounts not getting effected on sale of a stock item for free.

### ISSUE THREAD

**Issue by taherkhalil** [frappe/erpnext#12208]
Even if sold for free , stock in hand and cost of goods sold should get effected resulting in loss.
review topic for more detail
https://discuss.erpnext.com/t/critical-accounts-not-getting-effected-when-sold-item-for-free/32036

Thanks,

**Comment by umairsy** [comment]
Let's discuss over Discuss forum first. Only if it is validated as bug or doable enhancement, should be reported on Github. If needed, we can reopen it in future.
