### ISSUE TITLE
[Bug?] Default Purchase Uom not considered in buying cycle?

### ISSUE THREAD

**Issue by joezsweet** [frappe/erpnext#12205]
Hi there,

i'm getting an error while loading a `Purchase Receipt`: 

```
{
 "etype": "<class 'erpnext.utilities.transaction_base.UOMMustBeIntegerError'>", 
 "evalue": "UOMMustBeIntegerError('Quantity (14.18) cannot be a fraction in row 41',)", 
 "exception": {
  "args": "('Quantity (14.18) cannot be a fraction in row 41',)", 
  "http_status_code": "417", 
  "message": "'Quantity (14.18) cannot be a fraction in row 41'"
 }, 
```

It seems validation it is not taking in account `Default Purchase UOM`, it is set as `KG` and  not be an whole number:

<img width="1229" alt="schermata 2017-12-27 alle 12 39 42" src="https://user-images.githubusercontent.com/11652845/34380653-6e037726-eb03-11e7-8a0a-7cf78f825de7.png">

In this case `Default Stock Uom` is a `Nos.` (whole number), i'd expect in purchase cycle `Default Purchase UOM` should be taken.

Versions:
ERPNext: v9.x.x-develop (ff2fb65) (develop)
Frappe Framework: v9.x.x-develop (833259c) (develop)

**Comment by nabinhait** [comment]
Are you still getting this issue? Can't replicate the issue in my local.
The validation is nothing to do with default purchase UOM. It is based on the UOM selected on Purchase Receipt Item table.
