### ISSUE TITLE
Error on delivery note list view

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#12210]
Hello,

After last update I get this error everytime I try to view delivery notes in a list, this is the error on console:

"desk.min.js?ver=1514376935.0:7356 Uncaught TypeError: Cannot read property 'replace' of undefined
    at strip_html (desk.min.js?ver=1514376935.0:7356)
    at ListView.get_subject_html (list.min.js?ver=1514376935.0:2241)
    at ListView.get_column_html (list.min.js?ver=1514376935.0:2188)
    at list.min.js?ver=1514376935.0:2121
    at Array.map (<anonymous>)
    at ListView.get_left_html (list.min.js?ver=1514376935.0:2120)
    at ListView.get_list_row_html (list.min.js?ver=1514376935.0:2132)
    at list.min.js?ver=1514376935.0:2049
    at Array.map (<anonymous>)
    at ListView.render (list.min.js?ver=1514376935.0:2048)
strip_html @ desk.min.js?ver=1514376935.0:7356
get_subject_html @ list.min.js?ver=1514376935.0:2241
get_column_html @ list.min.js?ver=1514376935.0:2188
(anonymous) @ list.min.js?ver=1514376935.0:2121
get_left_html @ list.min.js?ver=1514376935.0:2120
get_list_row_html @ list.min.js?ver=1514376935.0:2132
(anonymous) @ list.min.js?ver=1514376935.0:2049
render @ list.min.js?ver=1514376935.0:2048
(anonymous) @ list.min.js?ver=1514376935.0:1537
(anonymous) @ jquery.min.js:2
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
z @ jquery.min.js:4
(anonymous) @ jquery.min.js:4
XMLHttpRequest.send (async)
send @ jquery.min.js:4
ajax @ jquery.min.js:4
frappe.request.call @ desk.min.js?ver=1514376935.0:1556
frappe.call @ desk.min.js?ver=1514376935.0:1449
refresh @ list.min.js?ver=1514376935.0:1526
(anonymous) @ desk.min.js?ver=1514376935.0:8067
(anonymous) @ list.min.js?ver=1514376935.0:1858
Promise.then (async)
show @ list.min.js?ver=1514376935.0:1853
BaseList @ list.min.js?ver=1514376935.0:1175
ListView @ list.min.js?ver=1514376935.0:1845
(anonymous) @ list.min.js?ver=1514376935.0:2768
callback @ desk.min.js?ver=1514376935.0:5525
callback @ desk.min.js?ver=1514376935.0:1445
_ @ desk.min.js?ver=1514376935.0:1469
(anonymous) @ desk.min.js?ver=1514376935.0:1570
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
z @ jquery.min.js:4
(anonymous) @ jquery.min.js:4
XMLHttpRequest.send (async)
send @ jquery.min.js:4
ajax @ jquery.min.js:4
frappe.request.call @ desk.min.js?ver=1514376935.0:1556
frappe.call @ desk.min.js?ver=1514376935.0:1449
with_doctype @ desk.min.js?ver=1514376935.0:5499
make @ list.min.js?ver=1514376935.0:2752
show @ desk.min.js?ver=1514376935.0:9789
show @ list.min.js?ver=1514376935.0:2784
(anonymous) @ desk.min.js?ver=1514376935.0:27
frappe.route @ desk.min.js?ver=1514376935.0:2201
startup @ desk.min.js?ver=1514376935.0:12337
load_startup @ desk.min.js?ver=1514376935.0:12306
init @ desk.min.js?ver=1514376935.0:12302
Class @ desk.min.js?ver=1514376935.0:37
frappe.start_app @ desk.min.js?ver=1514376935.0:12286
(anonymous) @ desk.min.js?ver=1514376935.0:12297
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
ready @ jquery.min.js:2
J @ jquery.min.js:2
desk.min.js?ver=1514376935.0:7356 Uncaught TypeError: Cannot read property 'replace' of undefined
    at strip_html (desk.min.js?ver=1514376935.0:7356)
    at ListView.get_subject_html (list.min.js?ver=1514376935.0:2241)
    at ListView.get_column_html (list.min.js?ver=1514376935.0:2188)
    at list.min.js?ver=1514376935.0:2121
    at Array.map (<anonymous>)
    at ListView.get_left_html (list.min.js?ver=1514376935.0:2120)
    at ListView.get_list_row_html (list.min.js?ver=1514376935.0:2132)
    at list.min.js?ver=1514376935.0:2049
    at Array.map (<anonymous>)
    at ListView.render (list.min.js?ver=1514376935.0:2048)
strip_html @ desk.min.js?ver=1514376935.0:7356
get_subject_html @ list.min.js?ver=1514376935.0:2241
get_column_html @ list.min.js?ver=1514376935.0:2188
(anonymous) @ list.min.js?ver=1514376935.0:2121
get_left_html @ list.min.js?ver=1514376935.0:2120
get_list_row_html @ list.min.js?ver=1514376935.0:2132
(anonymous) @ list.min.js?ver=1514376935.0:2049
render @ list.min.js?ver=1514376935.0:2048
(anonymous) @ list.min.js?ver=1514376935.0:1537
(anonymous) @ jquery.min.js:2
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
z @ jquery.min.js:4
(anonymous) @ jquery.min.js:4
XMLHttpRequest.send (async)
send @ jquery.min.js:4
ajax @ jquery.min.js:4
frappe.request.call @ desk.min.js?ver=1514376935.0:1556
frappe.call @ desk.min.js?ver=1514376935.0:1449
refresh @ list.min.js?ver=1514376935.0:1526
(anonymous) @ desk.min.js?ver=1514376935.0:8067
refresh_list_view @ list.min.js?ver=1514376935.0:1666
onchange @ list.min.js?ver=1514376935.0:1766
(anonymous) @ control.min.js?ver=1514376935.0:188
Promise.then (async)
(anonymous) @ desk.min.js?ver=1514376935.0:683
frappe.run_serially @ desk.min.js?ver=1514376935.0:681
set @ control.min.js?ver=1514376935.0:182
validate_and_set_in_model @ control.min.js?ver=1514376935.0:199
parse_validate_and_set_in_model @ control.min.js?ver=1514376935.0:172
(anonymous) @ control.min.js?ver=1514376935.0:341
dispatch @ jquery.min.js:3
$event.dispatch @ report.min.js?ver=1514376935.0:3033
r.handle @ jquery.min.js:3
desk.min.js?ver=1514376935.0:7356 Uncaught TypeError: Cannot read property 'replace' of undefined
    at strip_html (desk.min.js?ver=1514376935.0:7356)
    at ListView.get_subject_html (list.min.js?ver=1514376935.0:2241)
    at ListView.get_column_html (list.min.js?ver=1514376935.0:2188)
    at list.min.js?ver=1514376935.0:2121
    at Array.map (<anonymous>)
    at ListView.get_left_html (list.min.js?ver=1514376935.0:2120)
    at ListView.get_list_row_html (list.min.js?ver=1514376935.0:2132)
    at list.min.js?ver=1514376935.0:2049
    at Array.map (<anonymous>)
    at ListView.render (list.min.js?ver=1514376935.0:2048)"

I'm testing develop branch to report bugs

**Comment by joezsweet** [comment]
probably this: https://github.com/frappe/frappe/pull/4703 will fix

**Comment by applepipe** [comment]
Apparently it is fixed, I don't know if this is related to https://github.com/frappe/erpnext/issues/12228 but for now I'm closing
