### ISSUE TITLE
Print hide Rounded Total field in GST Print format

### ISSUE THREAD

**Issue by PrakashH** [frappe/erpnext#12219]
Print hide the Rounded Total field in GST Print format when there is no rounded value.

![screen shot 2017-12-28 at 11 00 06 am](https://user-images.githubusercontent.com/4570016/34401275-d6d3c096-ebbf-11e7-8789-a371641dd26e.png)

**Comment by harsh0214** [comment]
Will setting "Print Hide If No Value" for rounded total field in Sales Invoice work?

![screenshot from 2017-12-28 20-30-56](https://user-images.githubusercontent.com/25837158/34414295-84f4db1c-ec0e-11e7-9b9e-eec204cf4fe4.png)
