### ISSUE TITLE
Check button disappeared in Firefox

### ISSUE THREAD

**Issue by tundebabzy** [frappe/erpnext#12218]
![peek 2017-12-27 22-36](https://user-images.githubusercontent.com/818803/34394033-0e8b6fca-eb57-11e7-884b-72d9c40a163f.gif)

![screenshot-2017-12-27 selling settings](https://user-images.githubusercontent.com/818803/34394631-c8dfd764-eb5a-11e7-95df-076ea2edd9dd.png)

Things normal on Chrome.

OS: Ubuntu
Browser: Firefox 57.0.1 (64-bit)
Affected branch: develop

**Comment by strixaluco** [comment]
Looks like the issue is `left: -999999px;` value in this line:
https://github.com/frappe/frappe/blob/7595fb75bae4000d75eac635407b14ea6023d1af/frappe/public/less/desk.less#L899

**Comment by netchampfaris** [comment]
eea0943c4ced4b6754be2cc06793d7cd54311b38
