### ISSUE TITLE
Amend purchase order after posting purchase receipt

### ISSUE THREAD

**Issue by TetraComSA** [frappe/erpnext#12216]
Dears,

I have PO that has been partially received, and after a while, we decided to change and amend the quantities available in the purchase order. Unfortunately, we found no way to amend the PO. It seems we have to cancel the purchase receipt then you will be able to amend the PO. Is there any better way?

Regards
Yahya

**Comment by tundebabzy** [comment]
@TetraComSA 
Unfortunately, you have to delete every document that is linked to the PO
