### ISSUE TITLE
New Data Import Functionality Does Not Work

### ISSUE THREAD

**Issue by jotapira** [frappe/erpnext#12217]
Hello, I am trying to import new products as I had always done, but now with the new functionality of importing the data it is not working, when I select the file that I want to import and I give it import start it stays in a state 'in progress' and does not pass nothing does not show me any error only stays in that state 'in progress' indefinitely.

**Comment by jasonbrowne** [comment]
I am also experiencing this problem, with out any errors showing just my screen stuck at in progress.
![bad-import](https://user-images.githubusercontent.com/19347811/34506278-36ca63b4-efe0-11e7-9033-2a819c80e379.png)

**Comment by djpalshikar** [comment]
I can confirm the same. In my case the following happens:
1. Status of in progress is shown, but data is actually imported successfully
2. Status of in progress is shown, but no error is shown neither is data imported

**Comment by manassolanki** [comment]
Hi @djpalshikar 
Data Import is done via the background worker so if the status of the data import is "In Progress" and doesn't change then please check your scheduler.

Feel free to reopen if the issue persists.

**Comment by djpalshikar** [comment]
I am on frappe cloud. Do I have access to scheduler?

**Comment by manassolanki** [comment]
On frappe cloud, it shouldn't be a problem of the scheduler. Could you please try again and can check the status of data import after reloading the page? How much data are you trying to import?

**Comment by djpalshikar** [comment]
The issue occurred when I imported about 160 records.
I imported a Material Request 13 days ago. The material request showed up in about 2-3 hrs, the status in in the Data Import Tool is  showing "In Progress".

**Comment by manassolanki** [comment]
I have seen your account. Most of your import fail is because of the wrong data. I also found some issue for which I have sent a fix (https://github.com/frappe/frappe/pull/4960). This will be updated in your account soon.
