### ISSUE TITLE
Material request list without status

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#12226]
List view on material requests are missing status after last update

<img width="433" alt="screen shot 2017-12-28 at 9 46 04 am" src="https://user-images.githubusercontent.com/18335894/34409921-0768944a-ebb4-11e7-955a-c5dfb9ff590a.png">

**Comment by kennethsequeira** [comment]
Can you provide the frappe and erpnext versions for this?

**Comment by applepipe** [comment]
Hello @kennethsequeira it was fixed with last update on develop branch
