### ISSUE TITLE
Can't see documents on list view on purchase receipt, delivery notes and others

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#12228]
Hello,

After yesterdays update, I'm not able to see documents on list view in delivery notes, sales orders, and others, I had to disable "Apply user permissions" to be able to see documents.

Company allowed
<img width="186" alt="screen shot 2017-12-28 at 10 23 47 am" src="https://user-images.githubusercontent.com/18335894/34410777-b3150e9a-ebb9-11e7-80ad-863eda1a9ed0.png">

Document permissions with user permission marked
<img width="961" alt="screen shot 2017-12-28 at 10 23 25 am" src="https://user-images.githubusercontent.com/18335894/34410786-c0d40e96-ebb9-11e7-9dd1-c2502360cf50.png">

Only rule on user permissions
<img width="218" alt="screen shot 2017-12-28 at 10 23 35 am" src="https://user-images.githubusercontent.com/18335894/34410794-cb11a26a-ebb9-11e7-981c-728642c8f102.png">

User permissions
<img width="582" alt="screen shot 2017-12-28 at 10 23 09 am" src="https://user-images.githubusercontent.com/18335894/34410803-da685f6a-ebb9-11e7-8526-506574ea31d4.png">

**Comment by umairsy** [comment]
Please post this issue on discuss.erpnext.com. Only if validated as bug, it should be reported here.

https://discuss.erpnext.com
