### ISSUE TITLE
[BUG][Critcal] Sales/Purchase return for Different UOM

### ISSUE THREAD

**Issue by KT-snorlax** [frappe/erpnext#12222]
Stock UOM is Unit and conversion rate for boxes is given as 10.

If you sell in boxes (10unit for each) , then return comes in unit you cannot make return,
even though in actual sold 10 units by selling 1 box as per stock UOM , i cannot make return for 4 units as invoice only sees sold qty and not actual qty.

Return should be considered on the **actual** quantity sold/ purchased as per Stock irrespective of the UOM.

refer 2nd part of https://discuss.erpnext.com/t/sales-purchase-return-for-different-uom-and-bulk-return/32005

Hope to see a quick resolution ,
Thanks

**Comment by KT-snorlax** [comment]
@nabinhait , Any update on this?

**Comment by KT-snorlax** [comment]
@umairsy , Any update on this please

**Comment by KT-snorlax** [comment]
@nabinhait 
extremely sorry to keep insisting , could you please address this issue with a little more priority 
, other requirement are also stuck because of this.
i have to do a very long workaround for this.

Thanks for the efforts so far.

**Comment by rohitwaghchaure** [comment]
@KT-snorlax 

We have [fixed](https://github.com/frappe/erpnext/pull/13132) this issue and currently fix is under review and we'll release the fix once the PR is merged.
