### ISSUE TITLE
[Enhancement][Feature Request]- Bulk return entry for a supplier /customer

### ISSUE THREAD

**Issue by ghost** [frappe/erpnext#12223]
Currently we can only return the exact amount of pieces bought/sold , 

For distributors , we receive goods in bulk over multiple invoices and stock checking is done at certain intervals or during sale.
If there are many items to be returned to a **specific supplier** which were brought from multiple invoices say for e.g 12 different items to be returned at varied quantity which were got from multiple invoices it becomes a tedious task to go in and return individual items from each invoice.

Instead there should be a way to bulk return items to a supplier , That way it makes **Tracking of return** also easier as you can track items returned by supplier.
As currently there is very little reports for returns -
Companies track returns by item-e.g most returned item , returned item with most cost ,to 
which supplier we returned what items and most returned, most returned brand . etc.

Please look into it ,
Thanks

**Comment by KT-snorlax** [comment]
Is it something that can be implemented as core essential enhancement or do i need to do a paid development.

How much would it cost for a simple bulk return and report?

Thanks,

**Comment by KT-snorlax** [comment]
@umairsy  or   @rmehta ,
Could you please comment on the pricing and if its possible by 1st week of jan?

Seems like a easy fix for you guys to enable bulk return and its report , i.e what items are returned to what supplier , item with highest quantity or total amount(cost) returned.

didn't know who to ping for pricing and completion things.
Thanks,

**Comment by adnanmunir83** [comment]
workaround for your issue is, batter to open a customer with the same name as supplier.  make an excel template to import the returns as sale at buying price.  it's the best workaround till this option is not available.

let me know if you need assistance.

**Comment by KT-snorlax** [comment]
@adnanmunir83 ,
here is a scenario for customer return,
according to your suggestion if a customer returns a item , i will create a supplier with the same name and buy it from him with the selling price.

Now here is the problem . what if the customer hadn't paid for those items in start - **accounts receivable** 
Now he returned some items from the multiple receipts and will only pay for the items he kept...
If i make payment for that , it will still show me outstanding,,,even if i buy from him.
How to handle this ..

Any suggestions?

**Comment by KT-snorlax** [comment]
@rmehta , @nabinhait ,
Extremely sorry to keep bugging you , but this is an important feature i require , i am willing to pay for its development as well , and contribute it directly to core....

Any update , suggestion , time-line estimation would be appreciated,

Thanks

**Comment by rmehta** [comment]
@KT-snorlax have you tried connecting with a service provider? https://erpnext.org/erpnext-jobs

Easiest fix would be to make a tool that will automatically create the reverse transactions in the background. I would budget $1000-1500 for a pull request.

**Comment by KT-snorlax** [comment]
@rmehta  , Thanks , for a positive reply, 

will do so , but i think it will need the **issue with the UOM**(basic issue) to be solved before that , as the tool wouldn't be able to make a return even in background where returns are  of some items of box(Unit) if invoice is made in box.

Thanks
