### ISSUE TITLE
Validation when I Replied to Rushabh's message

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#12238]
Since Rushabh has sent me a message, I am already in that room. right?

![screen shot 2017-12-29 at 11 27 30 am](https://user-images.githubusercontent.com/910238/34430455-5a3f5500-ec8b-11e7-98b9-6dec965f7e1c.png)

Also, the validation dialog should not have Submit button.

**Comment by umairsy** [comment]
Also, clicking on Submit button doesn't have any impact.

**Comment by achillesrasquinha** [comment]
Closing this. Both solved at [https://github.com/frappe/frappe/pull/4756](Frappe - #4756) and [https://github.com/frappe/frappe/issues/4719](Frappe - 4719)
