### ISSUE TITLE
Frappe chat error

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#12234]
Console shows this error when login:

send @ jquery.min.js:4
assets/frappe/sounds/chat-noticication.mp3 Failed to load resource: the server responded with a status of 404 (Not Found)
 Failed to load resource: the server responded with a status of 500 (INTERNAL SERVER ERROR)

**Comment by j209** [comment]
+1

**Comment by achillesrasquinha** [comment]
Whoops! `chat-noticication` spelling error. :smile:
Sending fixes.

**Comment by applepipe** [comment]
fixed
