### ISSUE TITLE
Employee status shows undefined in list view

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#12233]
Hello,

After todays update on developer branch the status on the employee (apparently on production order too) list view is displayed as undefined, no custom apps or any core modification, just bench update --reset.

**Comment by umairsy** [comment]
Please share the screenshot. Also, can you create some test Production Planning Tool and then check for the value?

**Comment by applepipe** [comment]
hello @umairsy 

Both documents displays status on the list view as undefined like the screenshot below
<img width="230" alt="screen shot 2018-01-02 at 8 53 53 am" src="https://user-images.githubusercontent.com/18335894/34481677-9ded4c64-ef9a-11e7-8dd4-6511e03eeac5.png">

When created with production planning tool the production order displays status as draft like it was supposed to be

**Comment by applepipe** [comment]
It was fixed today apparently, closing

**Comment by anduren** [comment]
fuck。

在 2018-01-08 23:47:48，applepipe <notifications@github.com> 写道：


It was fixed today apparently, closing
