### ISSUE TITLE
Discuss Frappe/ERPNext  Auto Invoice in duplicate and adding VAT without beign in the Original invoice Developers Bug

### ISSUE THREAD

**Issue by Ooops-404** [frappe/erpnext#12235]
Hi Guys,

I’m posting this as a bug because its something that started happening out of nowhere to an invoice cyle that had been going on for quite a while.

Details: I have a supplier to which I pay a monthly fee, so for well over an year now that ERP next auto generates the invoice/submit it for payment. The payments are actually done via a paytpal subs so I only go in to ERP to “officialize” the payment a couple times of so a year.
So today, I was going to settle all that and I noticed that for the past two months ERP next did auto generate the invoice as expected, but two things happened.

It created the same invoice twice and it added VAT. The later is odd because the original invoice didn’t have VAT, and it never happened before.

**Comment by tundebabzy** [comment]
Hi. 
Please add screenshots

**Comment by Ooops-404** [comment]
The last 2 moths of the cycleM
![image](https://user-images.githubusercontent.com/9021875/34418425-fb0dfc3e-ebf5-11e7-8702-6b1a41455963.png)

Note: You'll notice there are two invoices per months instead of 1 per month.

Other invoices from the same cycle. (2 months)
![image](https://user-images.githubusercontent.com/9021875/34418416-e5b9f1b2-ebf5-11e7-9017-ddba18ce2776.png)

Note: You'll notice that the total is different, basically, now ERPnext started to add VAT to the invoice. It shouldn't.

**Comment by rohitwaghchaure** [comment]
@Ooops-404 
I have checked on local account and it's working properly. I have created an invoice without tax and set monthly subscription for it. Then system has created auto invoice which don't have tax and worked properly.
In above screenshots grand total showing same value and posting date also different, which meant tax has not added.

**Comment by Ooops-404** [comment]
@rohitwaghchaure 

The grand total includes VAT and in the images above you can see that September invoice is 3.30, while December invoice is 4,06.
The 4.06 is the sum of 3.30 + 23% VAT, which equals 4.06. 
As you can see in the picture below.

![image](https://user-images.githubusercontent.com/9021875/34434004-15ae3ca4-ec7b-11e7-87c4-86bdb4d3b605.png)


Take a look at this subscricription;

![image](https://user-images.githubusercontent.com/9021875/34434113-c226ede6-ec7b-11e7-9693-43debcce5091.png)



As you can see each subscription is associated with one document, so why would the invoices of any single subscription have different values?

**Comment by rohitwaghchaure** [comment]
@Ooops-404 

I have tried to replicate the issue on local account but not able to replicate, can you PM me your accounts details(application URL, system user login credentials ) on discuss.erpnext.com(my id rohit_w).

**Comment by jaichavan** [comment]
Hello, @Ooops-404 
Can you confirm if the issue persists in latest version? [ v11.0.3-beta.34 () (staging) ]
