### ISSUE TITLE
Docs are not getting marked as Read

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#12239]
Earlier, title for the list in the Documents where in Bold only if they were unread. Once read, Title won't remain bold. Now, even if I read the document, title for it remain Bold, not indicating if it was already Read or not.

![screen shot 2017-12-29 at 11 34 55 am](https://user-images.githubusercontent.com/910238/34430554-4ef5f2f2-ec8c-11e7-9026-d896921bbe18.png)

**Comment by netchampfaris** [comment]
Fixed in https://github.com/frappe/frappe/commit/ef3a3fce9f84e69e20449a0ff959c4a28b3bbac4
