### ISSUE TITLE
PoS Payment Process

### ISSUE THREAD

**Issue by olamide2** [frappe/erpnext#12236]
**The Problem** 

The current PoS does not require cashiers to take full payment for transactions made via PoS. This is a security loophole for most retailers

**My Current Work Around**

A work around I have used is to set the company credit limit to 1. This makes it mandatory for all invoices to be paid for in full else the invoice will not be created at PoS.

**The Limitation In The Work Around** 

This work around however only works for the online mode of PoS, it does not work when the offline mode is activated.

And the offline mode is really important for a fast paced retail environment 

If the offline mode is activated and the credit limit is set to 1, all "credit" sales at PoS will be saved as draft, even though the offending cashier would have printed the receipt and "concluded" the transaction. This is not acceptable.

**My Recommendation**

Have an option in the PoS Profile that makes it compulsory for PoS transactions to be paid for in full before the invoice can be submitted, make the submit button greyed out till full payment is made. With this we can create a profile for cashiers with this option ticked to ensure they cannot create credit transactions and then a separate profile for Managers where credit sales are needed.

This is seriously needed.

**Comment by exar888** [comment]
hi we have the same issue here. is it solved? @olamide2
