### ISSUE TITLE
Chat - No notification on receipt of message

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#12240]
I sent a message to Prakash

![screen shot 2017-12-29 at 11 51 01 am](https://user-images.githubusercontent.com/910238/34430770-9c26b050-ec8e-11e7-87c5-4725534f884c.png)

In the Prakash's account, there was not notification or pop-up.

![image 2017-12-29 11 50 02](https://user-images.githubusercontent.com/910238/34430793-ac8ae83a-ec8e-11e7-93c1-c906a493e139.jpg)

**Comment by achillesrasquinha** [comment]
Does the `chat-notification` ring occur on new messages?
