### ISSUE TITLE
Add Employee to the party dropdown to the trial balance party wise 

### ISSUE THREAD

**Issue by sumitdas4u** [frappe/erpnext#12243]
please add the Employee to the party dropdown to the trial balance party wise so we can get the expense claim unpaid details.

**Comment by umairsy** [comment]
Trial Balance is generally meant for seeing Balance Sheet or Profit and Loss statement as on given date.

You can create a custom report based on Expense Claim and filter it on a given Employee.

https://www.youtube.com/watch?v=TxJGUNarcQs
