### ISSUE TITLE
iOS ERPNext App Update?

### ISSUE THREAD

**Issue by bfhshumayun** [frappe/erpnext#12251]
Hello! With all the latest changes to ERPNext in v10, I was wonder when the ERPNext App will be updated to support v10?

I found that when 2-factor authentication is enabled, the App gets stuck after signin on the Blue ERPNext logo, disabling 2-factor authentication the app works fine. The current version released in Apple's App store is 0.0.6.

**Comment by umairsy** [comment]
The current ERPNext iOS and Android app work just fine for ERPNext version 10 as well. I am able to access our own ERPNext account on the mobile just fine. Mobile app doesn't require any update or changes for version 10.
