### ISSUE TITLE
Unable to create invoice due to new payment terms feature

### ISSUE THREAD

**Issue by sathishpy** [frappe/erpnext#12254]
I had to create a new invoice for yesterdays transaction. So used 'edit posting date' to update the invoice date, which promptly updated the payment due date as well to '13-01-2018'. However trying to save the document resulted in error 'due date shouldn't be after 13-01-2018'. The error message was confusing as the due date is updated properly. However checking this further, I realized that the newly added payment terms hasn't updated its due date along with main 'payment due date'. Most of the people don't use payment terms feature, so we shouldn't make their life difficult to change the date manually.

**Comment by robertbecht** [comment]
related???  https://github.com/frappe/erpnext/issues/12263

**Comment by tundebabzy** [comment]
Hi, please give me steps on how to reproduce this. Also, what branch are you on?

**Comment by tundebabzy** [comment]
Possibly fixed in #12288. Please reopen if issue if issue still persists in 10.0.5
