### ISSUE TITLE
[bug] Filter in list view

### ISSUE THREAD

**Issue by snvora** [frappe/erpnext#12253]
Options for filter getting hidden below list

![capture](https://user-images.githubusercontent.com/10496564/34452148-ccbdd826-ed5e-11e7-944a-27fce06879ee.PNG)

Erpnext Version:10.0.0
Chrome Browser

**Comment by umairsy** [comment]
Working fine on my test build. Chrome.

![screen shot 2018-01-02 at 3 16 35 pm](https://user-images.githubusercontent.com/910238/34480025-f935bf54-efcf-11e7-8704-ec398afc1d44.png)

Can you please update and check again?
