### ISSUE TITLE
Automated GSTR filing

### ISSUE THREAD

**Issue by Mahi-tsc** [frappe/erpnext#12256]
Do we have any solution of automated GST return filing directly from ERP Next since ERP Next has almost all the columns needed for filing returns

**Comment by vishdha** [comment]
@Mahi-tsc Yes, We working on it. We are creating GSTR1 and GSTR2 Report.

**Comment by siddhpant** [comment]
When can we expect automated filing to be out?

**Comment by Mahi-tsc** [comment]
Any further update on this requested feature?? We need GSTR 3B report.

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.
