### ISSUE TITLE
Contact in the Form View (Point of Sale)

### ISSUE THREAD

**Issue by franciscobuendiao** [frappe/erpnext#12250]
Using Online mode, could be changed the Contact in the Form View, but only if the Sales Invoice is saved first. Otherwise when the Contact is changed, this happens (see Contact field) and Sales Invoice can’t be saved…

![giphy](https://user-images.githubusercontent.com/25084259/34440242-80202f72-ec79-11e7-8016-88a219ec8b2a.gif)

**Comment by rohitwaghchaure** [comment]
@franciscobuendiao 
Have fixed this issue and we'll release the fix in next version
