### ISSUE TITLE
Update Virtual Machine with Frappe/ERPNext v10 on build.erpnext.com

### ISSUE THREAD

**Issue by asharamseervi** [frappe/erpnext#12261]
Though, we had great work on Frappe/ERPNext v10 and desperately waiting for its final release. Finally, it's launched. We had added/changed/updated a lot in this version. We're waiting to learn more and get hands dirty with v10.

Although, understand it takes time to update/migrate everything, and updates to VM will also be released soon, but can't wait for more. There are many dears who also desperately waiting for VM as well, Kindly update production/develop erpnext .ova file at build.erpnext.com. :)

**Comment by asharamseervi** [comment]
Hello @saurabh6790 and @umairsy, any update on this? Is there any guideline so we can create itself till it's not ready, kindly help.

**Comment by asharamseervi** [comment]
@rmehta No one is concerned about this!!  Can we expect these VM with the release of v10.1?

**Comment by raghukamath** [comment]
@asharamseervi please be patient, after the release the team may be busy in fixing issue related to migration. This is not ignored , it is just that they have too much in their plate.

**Comment by asharamseervi** [comment]
Hey @raghukamath, It's almost 3 months since the release of v10. Many of us, faced a lot of issues with VM due to a lot of changes is going to Frappe & ERPNext core. This is a very good sign but still not focusing VM to just release the product with a newer version.
I also believe that there is stable version also released so far, and fixed a lot of issues. Now, time to release latest VM accordingly. Hope concern is listened by Frappe Team.

**Comment by krnkris** [comment]
Of course new VM image with Ubuntu 64 bit + ERPNext v 11  would be awesome

**Comment by codingCoffee** [comment]
@asharamseervi terribly sorry for the delay. We're working on it right now

**Comment by system19** [comment]
I have a Centos7 Virtual box VM that is running the current ERPNext & Frappe I can upload to be Frappe team to check/use if they want?

**Comment by codingCoffee** [comment]
Hey  @asharamseervi, we have updated the VM builds. Please check the same. Closing this issue now.

**Comment by asharamseervi** [comment]
Hey @codingCoffee, I downloaded both Production & Develop and tested. There are some issues with those VMs, kindly anyone confirm these.

- Develop VM: There is no login page accessible, on localhost:8080. Eventhough, there is no "Sorry! We will be back soon" page.
- Production VM: Login page is accessible, on localhost:8080 but not able to login via username: Administrator & password: admin. Giving error of _AuthenticationError_:  Invalid Login. Try again.

**Comment by krnkris** [comment]
I just download virtual image VM
It is 64-bit + ubuntu 16.04, thank you well doe!
-------------------------------
Please revise the download page because it indicate Ubuntu 14.04
+
The login is with 
User name: Administrator
Password: Frappe
------------------------------- 

    Develop VM: There is no login page accessible, on localhost:8080. Eventhough, there is no "Sorry! We will be back soon" page.
    Production VM: Login page is accessible, on localhost:8080 but not able to login via username: Administrator & password: Frappe.

**Comment by asharamseervi** [comment]
Hey @krnkris, Thanks for letting us updated passwords. While the password is "frappe" instead of "Frappe".
Kindly test dev version as well, I'm not able to get login screen in that.

**Comment by codingCoffee** [comment]
@asharamseervi the Production build is working fine. The username is `Administrator` and the password is `frappe`.

The develop build has issues. Will try to get it fixed.

**Comment by sahilburman** [comment]
Downloaded new production build VM.
Ran bench update.
Command Got stuck at:
![image](https://user-images.githubusercontent.com/1945140/37506381-96ddfe92-290f-11e8-99ce-1c9210af746d.png)

**Comment by asharamseervi** [comment]
Hey @codingCoffee, I can confirm that I'm with @sahilburman and facing same issues at my instance.

**Comment by krnkris** [comment]
Confirm, same issue on develop:
Command Got stuck at:
INFO:bench.utils: sudo supervisorctl restart frappe-bench-workers: frappe-bench-web:

**Comment by codingCoffee** [comment]
Have identified the issue, and working on a fix. In the meantime, use
```
sudo systemctl restart supervisor
```
before running

```
bench update
```

**Comment by codingCoffee** [comment]
Have updated the builds, fixed admin password, fixed broken MD5 links.

username: `Administrator`
password: `admin`

Feel free to reopen issue if any problems persist.
