### ISSUE TITLE
POS transaction doesn't submit

### ISSUE THREAD

**Issue by osamaoughli** [frappe/erpnext#12268]
Hi all, 

I am receiving this message on submitting my transaction from POS 👍 

Sales Invoice SINV-RET-00006: Cost Center is required for 'Profit and Loss' account SALES - F. Please set up a default Cost Center for the Company.

I am sure the default cost center is already done, for customer and item also, .... please support

**Comment by tundebabzy** [comment]
Please add a screenshot

**Comment by rohitwaghchaure** [comment]
@osamaoughli 

Do you have multiple company in your account? Did you set cost center in the POS Profile?
Customer master has not an option to set default cost center, company, item(Default Selling Cost Center), pos profile has an option to set default cost center

**Comment by umairsy** [comment]
Please ensure that Income Account is mentioned in the Company and POS Profile.

For continued support, post this issue on discuss.erpnext.com
