### ISSUE TITLE
required by date

### ISSUE THREAD

**Issue by robertbecht** [frappe/erpnext#12263]
This (new) field is a nuissance....It is not set as mandatory...but still required to fill...
Entered a large PO...
![image](https://user-images.githubusercontent.com/1532439/34457591-b5e3d98c-edb5-11e7-9832-b9323ddb5e53.png)

No matter how i move the dates...had to reinter every thing...It kept on telling mee...see screenshot....

I have hidden the field....and did a test for one item....same message...
Very annoying...why should this field be mandatory???

**Comment by sathishpy** [comment]
Right. This is a duplicate of #12254

**Comment by tundebabzy** [comment]
Yeah. Lets close this in favour of #12254 .
