### ISSUE TITLE
Filtering Sales Invoice against Sales Order lists Sales Invoice's items in ROW

### ISSUE THREAD

**Issue by jaywks** [frappe/erpnext#12265]
**Clicking Sales Invoice from Sales Order**

![so](https://user-images.githubusercontent.com/16625441/34460177-ec0395c8-ee20-11e7-8062-91d1cf31672c.PNG)
**will give us this result, instead of showing 1 Invoice, it lists 5 invoices because that invoice has 5 items.**

![sinv](https://user-images.githubusercontent.com/16625441/34460183-27aa7470-ee21-11e7-9c21-1a8168536655.PNG)

**Comment by tundebabzy** [comment]
Hi @jaywks 
What branch and version is this happening with?

**Comment by tundebabzy** [comment]
confirmed on hotfix

**Comment by jaywks** [comment]
ERPNext: v10.0.4 (master)

Frappe Framework: v10.0.5 (master)

**Comment by tundebabzy** [comment]
Please follow up on #frappe/frappe#4763
