### ISSUE TITLE
Report header issue in rtl direction

### ISSUE THREAD

**Issue by j209** [frappe/erpnext#12266]
erpnext v10.0.4
frappe v10.0.5
There is an issue in report header in rtl mode.
![new_report_issues](https://user-images.githubusercontent.com/18129232/34460673-6a81c204-ee2a-11e7-92f8-0eb7fa6a2e55.png)

**Comment by j209** [comment]
I think if direction in .data-table element set to "ltr" it will be fixed.(for right to left cultures.)
![fixed](https://user-images.githubusercontent.com/18129232/34460743-e5750082-ee2c-11e7-8ed2-5757c424319a.png)

**Comment by kennethsequeira** [comment]
Can you give the ERPNext and Frappe versions for this?

**Comment by j209** [comment]
Erpnext 10.0.4
frappe  10.0.5

**Comment by j209** [comment]
data-table support rtl out of the box
[data-table rtl sample](https://datatables.net/extensions/fixedcolumns/examples/styling/rtl)
