### ISSUE TITLE
landed cost voucher says stock balance will be negative

### ISSUE THREAD

**Issue by osstechnolab** [frappe/erpnext#12274]
There's an issue on the posting of landed cost voucher.  It says below:

> Stock balance in Batch GS-1701-13 will become negative -9300.0 for Item 56343 at Warehouse Vancouver Main - SPI

Why is this appearing?   I think landed cost voucher only update valuation rates and GL Entries, not the stock balance.  Items received when LCV is posted might have been issued.

**Comment by umairsy** [comment]
Please post this issue on the community forum first discuss.erpnext.com. If it is validated as a bug, then we can re-open this issue here.
