### ISSUE TITLE
Cashier shift closing

### ISSUE THREAD

**Issue by mhbu50** [frappe/erpnext#12273]
1.    A cashier can close his shift, so he will get the amount of cash that should be available in a drawer, and he can insert amount of cash that is actually available in the drawer.
2.    Print cash reconciliation report with shift duration in hours, shift starting date time, shift ending date and time, store name and username of the cashier, cashier name, and total sales.

**Comment by ashish-greycube** [comment]
https://github.com/frappe/erpnext/pull/12334

**Comment by bghayad** [comment]
Hello @mhbu50
There is not any progress about this issue?
Regards
Bilal

**Comment by mansonkibe** [comment]
There is not any progress about this issue?
