### ISSUE TITLE
Chart of Accounts. New account not creating

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#12275]
Steps:

1. Enter details for the new account in the dialog
2. When clicking on "Create New" button, there is no impact

![screen shot 2018-01-01 at 11 20 26 am](https://user-images.githubusercontent.com/910238/34465819-0c9f7de0-eee6-11e7-9b09-8a836084c266.png)

**Comment by tundebabzy** [comment]
Hi @umairsy 
It seems this has been fixed. See animated gif below (tested on develop):

![peek 2018-01-08 23-00](https://user-images.githubusercontent.com/818803/34694567-d893136c-f4c7-11e7-9ce2-d7c2efba43a2.gif)
