### ISSUE TITLE
Error in password change for user

### ISSUE THREAD

**Issue by Hadi-Ti** [frappe/erpnext#12284]
Hello,

I have upgrade ERPnext today and it gives the error on user password change.

App Versions
{
	"erpnext": "10.0.4",
	"frappe": "10.0.5"
}
Route
Form/User/sghulam@cf4it.com
Error Report
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 939, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/user/user.py", line 561, in test_password_strength
    from frappe.utils.password_strength import test_password_strength as _test_password_strength
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/password_strength.py", line 6, in 
    from zxcvbn import zxcvbn
ImportError: cannot import name zxcvbn
Request Data
{
	"type": "POST",
	"args": {
		"new_password": "Saft12345@cf4it",
		"cmd": "frappe.core.doctype.user.user.test_password_strength"
	},
	"url": "/"
}
Response JSON
{}

**Comment by achillesrasquinha** [comment]
Did you try
`bench setup requirements`?

**Comment by Hadi-Ti** [comment]
I tried it but the problem is same

**Comment by Hadi-Ti** [comment]
I have development  server as well with same updated system and its working fine. Should i try to replace files from the dev server to the production server

**Comment by umairsy** [comment]
Works fine in my test instance as well. Closing this issue. Please report it on discussion forum for continued support.

https://discuss.erpnext.com

**Comment by Hadi-Ti** [comment]
I update again and try to and try to save the password. error is below.

App Versions
{
	"erpnext": "10.0.5",
	"frappe": "10.0.6"
}
Route
Form/User/sghulam@cf4it.com
Error Report
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 256, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 290, in _save
    self.run_before_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 859, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 755, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1024, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1007, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 749, in 
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/user/user.py", line 55, in validate
    self.password_strength_test()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/user/user.py", line 427, in password_strength_test
    result = test_password_strength(self.__new_password, '', None, user_data)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/user/user.py", line 561, in test_password_strength
    from frappe.utils.password_strength import test_password_strength as _test_password_strength
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/password_strength.py", line 6, in 
    from zxcvbn import zxcvbn
ImportError: cannot import name zxcvbn

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 939, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 256, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 290, in _save
    self.run_before_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 859, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 755, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1024, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1007, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 749, in 
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/user/user.py", line 55, in validate
    self.password_strength_test()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/user/user.py", line 427, in password_strength_test
    result = test_password_strength(self.__new_password, '', None, user_data)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/user/user.py", line 561, in test_password_strength
    from frappe.utils.password_strength import test_password_strength as _test_password_strength
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/password_strength.py", line 6, in 
    from zxcvbn import zxcvbn
ImportError: cannot import name zxcvbn
Request Data
{
	"type": "POST",
	"args": {
		"doc": "{\"user_image\":\"\",\"last_name\":\"Sarwar\",\"last_active\":\"2017-12-31 15:36:01.275101\",\"simultaneous_sessions\":1,\"creation\":\"2017-12-31 15:35:29.767040\",\"send_password_update_notification\":0,\"mute_sounds\":0,\"full_name\":\"Ghulam Sarwar\",\"owner\":\"Administrator\",\"last_known_versions\":\"{\\\"frappe\\\": {\\\"version\\\": \\\"8.0.58\\\", \\\"description\\\": \\\"Full stack web framework with Python, Javascript, MariaDB, Redis, Node\\\", \\\"branch\\\": \\\"master\\\", \\\"title\\\": \\\"Frappe Framework\\\"}, \\\"erpnext\\\": {\\\"version\\\": \\\"8.0.37\\\", \\\"description\\\": \\\"ERP made simple\\\", \\\"branch\\\": \\\"master\\\", \\\"title\\\": \\\"ERPNext\\\"}}\",\"__onload\":{\"all_modules\":[\"Accounts\",\"Agriculture\",\"Assets\",\"BOM\",\"Buying\",\"Chapter\",\"Contacts\",\"Core\",\"Course\",\"Course Schedule\",\"CRM\",\"Crop\",\"Crop Cycle\",\"Customer\",\"Data Import\",\"Desk\",\"Disease\",\"Donor\",\"Education\",\"Email Inbox\",\"Employee\",\"Expense Claim\",\"Fees\",\"Fertilizer\",\"File Manager\",\"Grant Application\",\"Healthcare\",\"HR\",\"Hub\",\"Instructor\",\"Integrations\",\"Issue\",\"Item\",\"Land Unit\",\"Lead\",\"Leaderboard\",\"Learn\",\"Maintenance\",\"Manufacturing\",\"Member\",\"Non Profit\",\"Opportunity\",\"Plant Analysis\",\"POS\",\"Production Order\",\"Profit and Loss Statement\",\"Program\",\"Project\",\"Projects\",\"Purchase Order\",\"Restaurant\",\"Room\",\"Sales Invoice\",\"Sales Order\",\"Schools\",\"Selling\",\"Setup\",\"Soil Analysis\",\"Soil Texture\",\"Stock\",\"Student\",\"Student Applicant\",\"Student Attendance\",\"Student Attendance Tool\",\"Student Group\",\"Supplier\",\"Support\",\"Task\",\"Timesheet\",\"ToDo\",\"Volunteer\",\"Water Analysis\",\"Weather\",\"Website\"]},\"thread_notify\":1,\"first_name\":\"Ghulam\",\"modified_by\":\"Administrator\",\"background_style\":\"Fill Screen\",\"new_password\":\"*****\",\"idx\":15,\"last_login\":\"2017-12-31 15:35:53.428212\",\"unsubscribed\":0,\"block_modules\":[],\"docstatus\":0,\"email\":\"sghulam@cf4it.com\",\"username\":\"ghulam\",\"roles\":[{\"modified_by\":\"Administrator\",\"name\":\"5adb669d2e\",\"parent\":\"sghulam@cf4it.com\",\"creation\":\"2017-12-31 15:35:30.180296\",\"modified\":\"2018-01-02 12:51:42.160390\",\"doctype\":\"Has Role\",\"idx\":1,\"parenttype\":\"User\",\"role\":\"System Manager\",\"owner\":\"Administrator\",\"docstatus\":0,\"parentfield\":\"roles\"},{\"modified_by\":\"Administrator\",\"name\":\"41645980bd\",\"parent\":\"sghulam@cf4it.com\",\"creation\":\"2017-12-31 15:35:29.767040\",\"modified\":\"2018-01-02 12:51:42.160390\",\"doctype\":\"Has Role\",\"idx\":3,\"parenttype\":\"User\",\"role\":\"Accounts Manager\",\"owner\":\"Administrator\",\"docstatus\":0,\"parentfield\":\"roles\"},{\"modified_by\":\"Administrator\",\"name\":\"288794e24e\",\"parent\":\"sghulam@cf4it.com\",\"creation\":\"2017-12-31 15:35:29.767040\",\"modified\":\"2018-01-02 12:51:42.160390\",\"doctype\":\"Has Role\",\"idx\":4,\"parenttype\":\"User\",\"role\":\"Accounts User\",\"owner\":\"Administrator\",\"docstatus\":0,\"parentfield\":\"roles\"},{\"modified_by\":\"Administrator\",\"name\":\"59a29e2d5f\",\"parent\":\"sghulam@cf4it.com\",\"creation\":\"2017-12-31 15:35:29.767040\",\"modified\":\"2018-01-02 12:51:42.160390\",\"doctype\":\"Has Role\",\"idx\":5,\"parenttype\":\"User\",\"role\":\"Analytics\",\"owner\":\"Administrator\",\"docstatus\":0,\"parentfield\":\"roles\"},{\"modified_by\":\"Administrator\",\"name\":\"75a3c9b2db\",\"parent\":\"sghulam@cf4it.com\",\"creation\":\"2017-12-31 15:35:29.767040\",\"modified\":\"2018-01-02 12:51:42.160390\",\"doctype\":\"Has Role\",\"idx\":6,\"parenttype\":\"User\",\"role\":\"Auditor\",\"owner\":\"Administrator\",\"docstatus\":0,\"parentfield\":\"roles\"},{\"modified_by\":\"Administrator\",\"name\":\"22825b2d5f\",\"parent\":\"sghulam@cf4it.com\",\"creation\":\"2017-12-31 15:35:29.767040\",\"modified\":\"2018-01-02 12:51:42.160390\",\"doctype\":\"Has Role\",\"idx\":7,\"parenttype\":\"User\",\"role\":\"Blogger\",\"owner\":\"Administrator\",\"docstatus\":0,\"parentfield\":\"roles\"},{\"modified_by\":\"Administrator\",\"name\":\"9f2f19c9b2\",\"parent\":\"sghulam@cf4it.com\",\"creation\":\"2017-12-31 15:35:29.767040\",\"modified\":\"2018-01-02 12:51:42.160390\",\"doctype\":\"Has Role\",\"idx\":8,\"parenttype\":\"User\",\"role\":\"Expense Approver\",\"owner\":\"Administrator\",\"docstatus\":0,\"parentfield\":\"roles\"},{\"modified_by\":\"Administrator\",\"name\":\"f8e8f00966\",\"parent\":\"sghulam@cf4it.com\",\"creation\":\"2017-12-31 15:35:29.767040\",\"modified\":\"2018-01-02 12:51:42.160390\",\"doctype\":\"Has Role\",\"idx\":9,\"parenttype\":\"User\",\"role\":\"Fleet Manager\",\"owner\":\"Administrator\",\"docstatus\":0,\"parentfield\":\"roles\"},{\"modified_by\":\"Administrator\",\"name\":\"75faefa222\",\"parent\":\"sghulam@cf4it.com\",\"creation\":\"2017-12-31 15:35:29.767040\",\"modified\":\"2018-01-02 12:51:42.160390\",\"doctype\":\"Has Role\",\"idx\":10,\"parenttype\":\"User\",\"role\":\"HR Manager\",\"owner\":\"Administrator\",\"docstatus\":0,\"parentfield\":\"roles\"},{\"modified_by\":\"Administrator\",\"name\":\"fd5c232819\",\"parent\":\"sghulam@cf4it.com\",\"creation\":\"2017-12-31 15:35:29.767040\",\"modified\":\"2018-01-02 12:51:42.160390\",\"doctype\":\"Has Role\",\"idx\":11,\"parenttype\":\"User\",\"role\":\"HR User\",\"owner\":\"Administrator\",\"docstatus\":0,\"parentfield\":\"roles\"},{\"modified_by\":\"Administrator\",\"name\":\"d21b714334\",\"parent\":\"sghulam@cf4it.com\",\"creation\":\"2017-12-31 15:35:29.767040\",\"modified\":\"2018-01-02 12:51:42.160390\",\"doctype\":\"Has Role\",\"idx\":13,\"parenttype\":\"User\",\"role\":\"Item Manager\",\"owner\":\"Administrator\",\"docstatus\":0,\"parentfield\":\"roles\"},{\"modified_by\":\"Administrator\",\"name\":\"e7efecfaa1\",\"parent\":\"sghulam@cf4it.com\",\"creation\":\"2017-12-31 15:35:29.767040\",\"modified\":\"2018-01-02 12:51:42.160390\",\"doctype\":\"Has Role\",\"idx\":14,\"parenttype\":\"User\",\"role\":\"Knowledge Base Contributor\",\"owner\":\"Administrator\",\"docstatus\":0,\"parentfield\":\"roles\"},{\"modified_by\":\"Administrator\",\"name\":\"c6517d85f4\",\"parent\":\"sghulam@cf4it.com\",\"creation\":\"2017-12-31 15:35:29.767040\",\"modified\":\"2018-01-02 12:51:42.160390\",\"doctype\":\"Has Role\",\"idx\":15,\"parenttype\":\"User\",\"role\":\"Knowledge Base Editor\",\"owner\":\"Administrator\",\"docstatus\":0,\"parentfield\":\"roles\"},{\"modified_by\":\"Administrator\",\"name\":\"4987176550\",\"parent\":\"sghulam@cf4it.com\",\"creation\":\"2017-12-31 15:35:29.767040\",\"modified\":\"2018-01-02 12:51:42.160390\",\"doctype\":\"Has Role\",\"idx\":16,\"parenttype\":\"User\",\"role\":\"Leave Approver\",\"owner\":\"Administrator\",\"docstatus\":0,\"parentfield\":\"roles\"},{\"modified_by\":\"Administrator\",\"name\":\"69cc8251db\",\"parent\":\"sghulam@cf4it.com\",\"creation\":\"2017-12-31 15:35:29.767040\",\"modified\":\"2018-01-02 12:51:42.160390\",\"doctype\":\"Has Role\",\"idx\":17,\"parenttype\":\"User\",\"role\":\"Maintenance Manager\",\"owner\":\"Administrator\",\"docstatus\":0,\"parentfield\":\"roles\"},{\"modified_by\":\"Administrator\",\"name\":\"a0130b6715\",\"parent\":\"sghulam@cf4it.com\",\"creation\":\"2017-12-31 15:35:29.767040\",\"modified\":\"2018-01-02 12:51:42.160390\",\"doctype\":\"Has Role\",\"idx\":18,\"parenttype\":\"User\",\"role\":\"Maintenance User\",\"owner\":\"Administrator\",\"docstatus\":0,\"parentfield\":\"roles\"},{\"modified_by\":\"Administrator\",\"name\":\"bffbedaaa0\",\"parent\":\"sghulam@cf4it.com\",\"creation\":\"2017-12-31 15:35:29.767040\",\"modified\":\"2018-01-02 12:51:42.160390\",\"doctype\":\"Has Role\",\"idx\":21,\"parenttype\":\"User\",\"role\":\"Newsletter Manager\",\"owner\":\"Administrator\",\"docstatus\":0,\"parentfield\":\"roles\"},{\"modified_by\":\"Administrator\",\"name\":\"d395764db5\",\"parent\":\"sghulam@cf4it.com\",\"creation\":\"2017-12-31 15:35:29.767040\",\"modified\":\"2018-01-02 12:51:42.160390\",\"doctype\":\"Has Role\",\"idx\":22,\"parenttype\":\"User\",\"role\":\"Projects Manager\",\"owner\":\"Administrator\",\"docstatus\":0,\"parentfield\":\"roles\"},{\"modified_by\":\"Administrator\",\"name\":\"5fb2cd76ce\",\"parent\":\"sghulam@cf4it.com\",\"creation\":\"2017-12-31 15:35:29.767040\",\"modified\":\"2018-01-02 12:51:42.160390\",\"doctype\":\"Has Role\",\"idx\":23,\"parenttype\":\"User\",\"role\":\"Projects User\",\"owner\":\"Administrator\",\"docstatus\":0,\"parentfield\":\"roles\"},{\"modified_by\":\"Administrator\",\"name\":\"8f53c6f034\",\"parent\":\"sghulam@cf4it.com\",\"creation\":\"2017-12-31 15:35:29.767040\",\"modified\":\"2018-01-02 12:51:42.160390\",\"doctype\":\"Has Role\",\"idx\":24,\"parenttype\":\"User\",\"role\":\"Purchase Manager\",\"owner\":\"Administrator\",\"docstatus\":0,\"parentfield\":\"roles\"},{\"modified_by\":\"Administrator\",\"name\":\"00924f531c\",\"parent\":\"sghulam@cf4it.com\",\"creation\":\"2017-12-31 15:35:29.767040\",\"modified\":\"2018-01-02 12:51:42.160390\",\"doctype\":\"Has Role\",\"idx\":25,\"parenttype\":\"User\",\"role\":\"Purchase Master Manager\",\"owner\":\"Administrator\",\"docstatus\":0,\"parentfield\":\"roles\"},{\"modified_by\":\"Administrator\",\"name\":\"4dc140d0d4\",\"parent\":\"sghulam@cf4it.com\",\"creation\":\"2017-12-31 15:35:29.767040\",\"modified\":\"2018-01-02 12:51:42.160390\",\"doctype\":\"Has Role\",\"idx\":26,\"parenttype\":\"User\",\"role\":\"Purchase User\",\"owner\":\"Administrator\",\"docstatus\":0,\"parentfield\":\"roles\"},{\"modified_by\":\"Administrator\",\"name\":\"d7722b6e58\",\"parent\":\"sghulam@cf4it.com\",\"creation\":\"2017-12-31 15:35:29.767040\",\"modified\":\"2018-01-02 12:51:42.160390\",\"doctype\":\"Has Role\",\"idx\":27,\"parenttype\":\"User\",\"role\":\"Quality Manager\",\"owner\":\"Administrator\",\"docstatus\":0,\"parentfield\":\"roles\"},{\"modified_by\":\"Administrator\",\"name\":\"05ddd7351d\",\"parent\":\"sghulam@cf4it.com\",\"creation\":\"2017-12-31 15:35:29.767040\",\"modified\":\"2018-01-02 12:51:42.160390\",\"doctype\":\"Has Role\",\"idx\":28,\"parenttype\":\"User\",\"role\":\"Report Manager\",\"owner\":\"Administrator\",\"docstatus\":0,\"parentfield\":\"roles\"},{\"modified_by\":\"Administrator\",\"name\":\"71e111231c\",\"parent\":\"sghulam@cf4it.com\",\"creation\":\"2017-12-31 15:35:29.767040\",\"modified\":\"2018-01-02 12:51:42.160390\",\"doctype\":\"Has Role\",\"idx\":29,\"parenttype\":\"User\",\"role\":\"Sales Manager\",\"owner\":\"Administrator\",\"docstatus\":0,\"parentfield\":\"roles\"},{\"modified_by\":\"Administrator\",\"name\":\"ce5cc282c4\",\"parent\":\"sghulam@cf4it.com\",\"creation\":\"2017-12-31 15:35:29.767040\",\"modified\":\"2018-01-02 12:51:42.160390\",\"doctype\":\"Has Role\",\"idx\":30,\"parenttype\":\"User\",\"role\":\"Sales Master Manager\",\"owner\":\"Administrator\",\"docstatus\":0,\"parentfield\":\"roles\"},{\"modified_by\":\"Administrator\",\"name\":\"0c7347f89f\",\"parent\":\"sghulam@cf4it.com\",\"creation\":\"2017-12-31 15:35:29.767040\",\"modified\":\"2018-01-02 12:51:42.160390\",\"doctype\":\"Has Role\",\"idx\":31,\"parenttype\":\"User\",\"role\":\"Sales User\",\"owner\":\"Administrator\",\"docstatus\":0,\"parentfield\":\"roles\"},{\"modified_by\":\"Administrator\",\"name\":\"60effa9421\",\"parent\":\"sghulam@cf4it.com\",\"creation\":\"2017-12-31 15:35:29.767040\",\"modified\":\"2018-01-02 12:51:42.160390\",\"doctype\":\"Has Role\",\"idx\":32,\"parenttype\":\"User\",\"role\":\"Stock Manager\",\"owner\":\"Administrator\",\"docstatus\":0,\"parentfield\":\"roles\"},{\"modified_by\":\"Administrator\",\"name\":\"64c02cbd3c\",\"parent\":\"sghulam@cf4it.com\",\"creation\":\"2017-12-31 15:35:29.767040\",\"modified\":\"2018-01-02 12:51:42.160390\",\"doctype\":\"Has Role\",\"idx\":32,\"parenttype\":\"User\",\"role\":\"Academics User\",\"owner\":\"Administrator\",\"docstatus\":0,\"parentfield\":\"roles\"},{\"modified_by\":\"Administrator\",\"name\":\"a23415848a\",\"parent\":\"sghulam@cf4it.com\",\"creation\":\"2017-12-31 15:35:29.767040\",\"modified\":\"2018-01-02 12:51:42.160390\",\"doctype\":\"Has Role\",\"idx\":33,\"parenttype\":\"User\",\"role\":\"Stock User\",\"owner\":\"Administrator\",\"docstatus\":0,\"parentfield\":\"roles\"},{\"modified_by\":\"Administrator\",\"name\":\"2822b0cc08\",\"parent\":\"sghulam@cf4it.com\",\"creation\":\"2017-12-31 15:35:29.767040\",\"modified\":\"2018-01-02 12:51:42.160390\",\"doctype\":\"Has Role\",\"idx\":35,\"parenttype\":\"User\",\"role\":\"Support Team\",\"owner\":\"Administrator\",\"docstatus\":0,\"parentfield\":\"roles\"},{\"modified_by\":\"Administrator\",\"name\":\"d4a67dbe25\",\"parent\":\"sghulam@cf4it.com\",\"creation\":\"2017-12-31 15:35:29.767040\",\"modified\":\"2018-01-02 12:51:42.160390\",\"doctype\":\"Has Role\",\"idx\":37,\"parenttype\":\"User\",\"role\":\"Website Manager\",\"owner\":\"Administrator\",\"docstatus\":0,\"parentfield\":\"roles\"}],\"last_ip\":\"178.80.103.102\",\"defaults\":[],\"logout_all_sessions\":1,\"send_me_a_copy\":0,\"user_emails\":[],\"doctype\":\"User\",\"login_after\":0,\"send_welcome_email\":1,\"name\":\"sghulam@cf4it.com\",\"language\":\"en-US\",\"user_type\":\"System User\",\"gender\":\"\",\"login_before\":0,\"enabled\":1,\"modified\":\"2018-01-02 12:51:42.160390\",\"frappe_userid\":\"6db4d6421e981c66101af013b53d3938a6f56fe\",\"__last_sync_on\":\"2018-01-02T10:46:49.992Z\",\"__unsaved\":1}",
		"action": "Save",
		"cmd": "frappe.desk.form.save.savedocs"
	},
	"btn": {
		"jQuery224096782386533551111": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 792,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"freeze_message": "Saving",
	"url": "/"
}
Response JSON
{
	"_server_messages": "[\"{\\\"message\\\": \\\"Did not save\\\"}\"]"
}

**Comment by manassolanki** [comment]
`zxcvbn` Please pip install this library. This should be automatically installed if you do `bench update`

**Comment by Hadi-Ti** [comment]
in my development server this is working fine
