### ISSUE TITLE
BOM update tool does not update Grandparent's Exploded BOM

### ISSUE THREAD

**Issue by djpalshikar** [frappe/erpnext#12286]
![screenshot-2018-1-1 bom update tool](https://user-images.githubusercontent.com/23133635/34468180-7a9bd634-ef29-11e7-887c-9aed447a720c.png)

The BOM update tool only updates all BOMs where Current BOM is explicitly mentioned. It does not trigger a change further up above the Grandparent.

**EDIT**: Also while Great Grand Parents Tree when expanded gets updated, the exploded BOM table does not get updated.

I don't see any valid use case for this behaviour.

ERPNext v10.0.4 (master)
Frappe Framework: v10.0.5 (master)

**Comment by umairsy** [comment]
Didn't replicate it in my test build. Closing issue for now.

**Comment by umairsy** [comment]
As received from Dhananjay:

I have edited the issue. There was a mistake I made. The problem occurs with the Great-Grand-Parent's BOM.

Please consider re-opening the issue. If you can access Sapcon's account, I have created a BOM for testing to show you the same: BOM-GGP-001.

**Comment by djpalshikar** [comment]
@rohitwaghchaure can you confirm if this has been released to Frappe hosted accounts
