### ISSUE TITLE
Delivery Note Report Enhancement Request

### ISSUE THREAD

**Issue by Hadi-Ti** [frappe/erpnext#12285]
Dear I have request for the change in report format. 

see the image attached. it is a master child report. How i can make such reports in ERPnext Report Builder.

Regards,

Sarwar
![delivery note report](https://user-images.githubusercontent.com/1536351/34467851-440eefd2-ef0d-11e7-87a4-2f8e14b7bef2.png)

**Comment by umairsy** [comment]
Here is the help on how to create reports in ERPNext.

https://erpnext.org/docs/user/manual/en/customize-erpnext/articles/making-custom-reports-in-erpnext

Please post your queries on the community forum first.

https://discuss.erpnext.com
