### ISSUE TITLE
ImportError: cannot import name zxcvbn

### ISSUE THREAD

**Issue by Hadi-Ti** [frappe/erpnext#12298]
Wehn changing password from the user profile this error come.

**Comment by manassolanki** [comment]
Please update your dependencies.

**Comment by Hadi-Ti** [comment]
dear thanks for this. can you list the dependencies which needs update. I have done all possible efforts.

I have updated my erpnext from the ver 9 to 10
after this i receive this error

**Comment by manassolanki** [comment]
You can use the following command for updating this specific requirement (from frappe-bench folder)
`./env/bin/pip install zxcvbn-python`

These are the list of requirement for frappe.
https://github.com/frappe/frappe/blob/master/requirements.txt

For more discussion, please post on discuss.erpnext.com

**Comment by adnanmunir83** [comment]
for Many users it's folder rights issue and the above command is not working. 
Try following commands.
inside frappe-bench>
First uninstall this.  it's already installed but without rights.
sudo -H ./env/bin/pip uninstall zxcvbn-python

now install it again.
sudo -H ./env/bin/pip install zxcvbn-python
