### ISSUE TITLE
Barcode generation in Asset Management

### ISSUE THREAD

**Issue by Muzzy73** [frappe/erpnext#12297]
The fixed asset management module can read pre-printed barcode and add it to the item. However, it does not have capability to create new barcode to track office inventory such as furniture, fixtures, office equipment etc. Such items do not have specific barcode. Process is as follows.

1. Enter Asset information,
2. Create barcode for the item.
3. Print barcode.
4. Fix barcode on item.
5. Handheld device reads the barcode for asset location change, asset reconciliation or disposing.

**Comment by Muzzy73** [comment]
Closing as it is WIP within our company.

**Comment by rijulmanch** [comment]
@Muzzy73 Any progress with this?

**Comment by BeatLink** [comment]
Sorry to beat a dead horse but this issue is 4 years old. Are there any updates?
