### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable when creating a Purchase Invoice (API) 

### ISSUE THREAD

**Issue by manuelgrdz14** [frappe/erpnext#12299]
Expected Behaviour
I am expecting the API to upload a Purchase Invoice when making a POST call to the route: 
     base_url + /api/resource/Purchase Invoice

Actual Behaviour
I am receiving this error after I updated from ERPNext v9 to ERPNext v10 when making the POST call:
[ERROR] Error handling request /api/resource/Purchase%20Invoice
Traceback (most recent call last):
File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 135, in handle
self.handle_request(listener, req, client, addr)
File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
respiter = self.wsgi(environ, resp.start_response)
File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/werkzeug/local.py", line 228, in application
return ClosingIterator(app(environ, start_response), self.cleanup)
File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/werkzeug/wrappers.py", line 302, in application
return f(*args[:-2] + (request,))(*args[-2:])
File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 88, in application
response = handle_exception(e)
File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 143, in handle_exception
if frappe.local.is_ajax or 'application/json' in frappe.get_request_header('Accept'):
TypeError: argument of type 'NoneType' is not iterable

Steps to reproduce:
I am sending a request to baseurl + /api/resource/Purchase Invoice similar to this (some information has been changed):

-SEE UPDATED JSON BELOW IN A MORE RECENT COMMENT-

'{"bill_no":1,"bill_date":"2017-11-29","supplied_items":[],"total":"173.14","grand_total":"200.00","base_grand_total":"200.00","advances":[],"discount_amount":0,"party_account_currency":"MXN","price_list_currency":"MXN","supplier":"GENERIC SUPPLIER","doctype":"Purchase Invoice","taxes":[{"doctype":"Purchase Taxes and Charges","cost_center":"Principal - DEF","charge_type":"Actual","description":"IVA ACREDITABLE o PAGADO A PROVEEDORES","add_deduct_tax":"Add","account_head":"IVA ACREDITABLE o PAGADO A PROVEEDORES - DEF","base_tax_amount":"26.86","tax_amount":"26.86","parenttype":"Purchase Invoice","parentfield":"taxes","category":"Total"}],"taxes_and_charges_added":0,"total_taxes_and_charges":0,"base_taxes_and_charges_added":0,"base_total_taxes_and_charges":0,"additional_discount_percentage":0,"base_net_total":0,"taxes_and_charges_deducted":0,"items":[{"landed_cost_voucher_amount":0,"qty":"12.51","item_tax_rate":"{}","rate":"13.84","cost_center":"Principal - DEF","rm_supp_cost":0,"page_break":0,"discount_percentage":0,"amount":"173.14","conversion_factor":1,"warehouse":"Sucursales - DEF","docstatus":0,"uom":"LTR","doctype":"Purchase Invoice Item","description":"GENERIC PRODUCT","item_tax_amount":0,"item_code":"XXXXXX","item_name":"GENERIC PRODUCT","idx":1,"item_group":"Productos","expense_account":"Stock recibidas, pero no facturada - DEF","parenttype":"Purchase Invoice","parentfield":"items"}],"apply_discount_on":"Grand Total","total_advance":0,"base_paid_amount":0,"paid_amount":0,"credit_to":"POLIZA DE SEGURO POR PAGAR - DEF","cfdi":"XXXXXXX","is_opening":"No","is_paid":0,"is_return":0,"is_subcontracted":"No","against_expense_account":"Stock recibidas, pero no facturada - DEF","naming_series":"PINV-","currency":"MXN","base_taxes_and_charges_deducted":0,"update_stock":1,"repeat_on_day_of_month":0,"recurring_type":"Monthly","docstatus":0,"parent":"","parentfield":"","parenttype":"","cash_bank_account":"","return_against":"","tc_name":"","language":"es-MX","set_posting_time":0,"ignore_pricing_rule":0,"write_off_cost_center":"","select_printing_heading":"","_assign":"","buying_price_list":"Compra estándar","plc_conversion_rate":1,"submit_on_creation":0,"write_off_amount":0,"notify_by_email":0,"idx":0}'

**Comment by manuelgrdz14** [comment]
This is a problem I have had since v10, and I need it to be solved. Please stop ignoring this issue as I have seen newer issues been adressed by you.

**Comment by adnanmunir83** [comment]
send this parameter as well. supplier_name, and make sure te supplier which you are sending, exists.  
try to change supplier with a shorter name and send the request. it should work.

**Comment by manuelgrdz14** [comment]
Thank you very much for your response. I added supplier_name to my json (along with other fields)

This is the updated json I am sending:
{ data: 
        {
            "bill_no": 1,
            "bill_date": "2018-01-04",
            "supplied_items": [],
            "total": "173.14",
            "grand_total": "200.00",
            "base_grand_total": "200.00",
            "advances": [],
            "discount_amount": 0.0,
            "party_account_currency": "MXN",
            "price_list_currency": "MXN",
            "supplier": "SUPPLIER",
            "supplier_name": "SUPPLIER",
            "doctype": "Purchase Invoice",
            "taxes": [{ 
                   "doctype": "Purchase Taxes and Charges",
                   "cost_center": "Principal - XXX",
                   "charge_type": "Actual",
                   "description": "IVA ACREDITABLE o PAGADO A PROVEEDORES",
                   "add_deduct_tax": "Add",
                   "account_head": "IVA ACREDITABLE o PAGADO A PROVEEDORES - XXX",
                   "base_tax_amount": "26.86",
                   "tax_amount": '26.86',
                   "parenttype": "Purchase Invoice",
                   "parentfield": "taxes",
                   "category": "Total" } ],
            "taxes_and_charges_added": 0,
            "total_taxes_and_charges": 0,
            "base_taxes_and_charges_added": 0,
            "base_total_taxes_and_charges": 0,
            "additional_discount_percentage": 0,
            "base_net_total": 0,
            "taxes_and_charges_deducted": 0,
            "items": [{
                   "landed_cost_voucher_amount": 0,
                   "qty": "12.51",
                   "item_tax_rate": "{}",
                   "rate": "13.84",
                   "cost_center": "Principal - XXX",
                   "rm_supp_cost": 0,
                   "page_break": 0,
                   "discount_percentage": 0,
                   "amount": "173.14",
                   "conversion_factor": 1,
                   "warehouse": "Sucursales - XXX",
                   "docstatus": 0,
                   "uom": "XXX",
                   "doctype": "Purchase Invoice Item",
                   "description": "PRODUCT",
                   "item_tax_amount": 0,
                   "item_code": "XXXX,
                   "item_name": "PRODUCT",
                   "idx": 1,
                   "item_group": "PRODUCTOS",
                   "expense_account": "Stock recibidas, pero no facturada - XXX",
                   "parenttype": "Purchase Invoice",
                   "parentfield": "items"
             }],
            "apply_discount_on": "Grand Total",
            "total_advance": 0,
            "base_paid_amount": 0,
            "paid_amount": 0,
            "credit_to": "Stock recibidas, pero no facturada - XXX",
            "cfdi": XXXX,
            "is_opening": "No",
            "is_paid": 0,
            "is_return": 0,
            "is_subcontracted": "No",
            "against_expense_account": "Stock recibidas, pero no facturada - XXX",
            "naming_series": "PINV-",
            "currency": "MXN",
            "base_taxes_and_charges_deducted": 0,
            "update_stock": 1,
            "repeat_on_day_of_month": 0,
            "recurring_type": "Monthly",
            "docstatus": 0,
            "parent": "",
            "parentfield": "",
            "parenttype": "",
            "cash_bank_account": "",
            "return_against": "",
            "tc_name": "",
            "language": "es-MX",
            "set_posting_time": 0,
            "ignore_pricing_rule": 0,
            "write_off_cost_center": "",
            "select_printing_heading": "",
            "_assign": "",
            "buying_price_list": "Compra estándar",
            "title": "SUPPLIER",
            "plc_conversion_rate": 1,
            "submit_on_creation": 0,
            "write_off_amount": 0,
            "notify_by_email": 0,
            "idx": 0,
            "payment_schedule": []
        }
}

I made sure that the supplier exists in the DB, but the error that I am getting seems to be the same as before.

Purchase Invoice is the only doctype that rises an exception, so I think I might be doing something wrong, but also the error in the logs seems a little bit too odd to me. 

frappe version: 10.0.6 (master)
erpnext version 10.0.5 (master)

**Comment by Nihantra-Patel** [comment]
Hi @manuelgrdz14,

**We no longer provide support for version 13 or older.**

Kindly upgrade to version 14 or 15, then refresh and check again because lots of bugs fixed in the new version.

Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!
