### ISSUE TITLE
Customer portal Invoices display bug

### ISSUE THREAD

**Issue by gbard** [frappe/erpnext#12306]
I'm having a display bug in the Customer Portal (Invoices list).

![erpnext_cust_portal_invoices_bug](https://user-images.githubusercontent.com/11325063/34509328-cbbb49b2-f016-11e7-9754-7fa56dd38d8d.gif)

Any idea why? No changes to any core files...

**Comment by gbard** [comment]
Anybody else facing this issue?

**Comment by umairsy** [comment]
Working fine in my test account.

![screen shot 2018-02-12 at 4 08 55 pm](https://user-images.githubusercontent.com/910238/36092921-130a0f5c-100f-11e8-8e42-1c85e2b89abe.png)

Request you to post it on the dicuss for now. If validated as bug, we can re-open this issue.

**Comment by gbard** [comment]
I'd like to reopen this issue since I still have this same issue. I'm using latest version and after digging a bit here is what I found:

![display_bug01](https://user-images.githubusercontent.com/11325063/36576488-09f612fe-181f-11e8-958f-b6073f56ad46.jpg)

![display_bug02](https://user-images.githubusercontent.com/11325063/36576501-13ee861a-181f-11e8-95ad-f0db395ff5f1.jpg)

As you can see, the width for page-content-wrapper is set to 7608.33px but I have no idea why.... As I said, I made no changes to any files.

@umairsy In your example, next to the Order number, the second column is used to display a "item-preview" ... some sort of preview of the sale invoice/order lines... In your example there is just a "iPhone 6" but in my example, there is multiple items with long names:. This is one of the "item-preview" I have in the list:

<div class="small text-muted items-preview ellipsis">COLLE HAIRBORN - STEP BY STEP , SAC ÉCHANTILLON (100), ROULLETE  3/4" X 108" BRUN, ROULETTE 3/4" X 108 " TRANSPARENT, TAPE EN U (36) BLEU , SOLVANT (UNITÉ), SEALANOL KIT, SOIN LAVANT CAS DE PELLICULES 200ML, SERUM COMPLEX PREPARATEUR 50ML, SOIN LAVANT CAS DE CHUTE 200ML, STYLING LINE CREME COIFFANTE 75ML, DAILY SOIN LAVANT RACINES GRASSES POINTES SECHES 1L, SUN BAUME PROTECTEUR SOLAIRE 200ML, SUN SOIN SPRAY PROTECTEUR SOLAIRE 150ML, SUN SOIN SPRAY PROTECTEUR SOLAIRE 150ML, BLONDE SOIN LAVANT LUMIERE 250ML, BLONDE SPRAY BIPHASE HYDRATANT 150ML, NUTRI BAUME NUTRITION 1L, OR &amp; ARGAN LAQUE ILLUMINANTE 500ML, OR &amp; ARGAN LAQUE ILLUMINANTE 500ML</div>

I think the problem might be because of that... Would it be possible to replace the "items-preview" column by something else like the invoice paid amount or the invoice balance... or simply remove the "items-preview" column?

My guess is that you will be able to reproduce the issue by creating a dummy invoice that includes multiple items with longer names.

Would someone mind trying to replicate this issue?

Thanks!
