### ISSUE TITLE
UOM Conversion Factor is greyed when there is no item selected in PI

### ISSUE THREAD

**Issue by Suprazz** [frappe/erpnext#12304]
The field is greyed but required.

![image](https://user-images.githubusercontent.com/3640711/34498205-96cb4470-efce-11e7-8e84-2f25a89ce425.png)

**Comment by rohitwaghchaure** [comment]
Hi @Suprazz 

It will be editable when your UOM is different than the Stock UOM. Why conversion factor is showing as zero? It should be 1 if stock uom and uom is same.

**Comment by Suprazz** [comment]
By default it's set to 0. So there are 2 solutions. Ungray the field or set the default value to 1.

**Comment by tundebabzy** [comment]
Hi @Suprazz 
Do you have any custom scripts? The default for UOM is 1. There is also validation is you try to set the default to be below 0.

![screenshot-2018-1-3 item w umit - item w umit](https://user-images.githubusercontent.com/818803/34532835-fbe9353a-f0b7-11e7-85fd-4e4b27bafdb4.png)

**Comment by Suprazz** [comment]
No I dont.
The ERPNext guys can take a look at my account if it's required. I'm with the hosted erpnext.

**Comment by umairsy** [comment]
Please post your functional queries on the community forum.

https://discuss.erpnext.com
