### ISSUE TITLE
Avoiding replacing space with %20 in href title tag?

### ISSUE THREAD

**Issue by joezsweet** [frappe/erpnext#12300]
Hi there, 

would be possible to avoid replacing space with %20 in href title tag?

`<a class="ellipsis" href="#Form/Item/000008458" title="MULINO%20BIANCO%20PAN%20DI%20STELLE%20350G%2096PZ%201/4PL">MULINO BIANCO PAN DI STELLE 350G 96PZ 1/4PL</a>`

**Comment by netchampfaris** [comment]
https://github.com/frappe/frappe/pull/4747
