### ISSUE TITLE
Autoname for Batch DocType

### ISSUE THREAD

**Issue by mtlapointe** [frappe/erpnext#12302]
Hello,
I would like to be able to use a Naming Series with the Batch DocType. Following standard procedure for using a naming series (add naming_series to DocType and set it in the autoname field) did not work, so I dug into the code and see there is an autoname() function that defaults to using a hash (or Batch ID if set).

Would it be possible to modify the code in the Batch DocType to use a naming_series if it exists? I would attempt myself, but I am still very new to Frappe/ERPNext. 

Thanks!

**Comment by tundebabzy** [comment]
Hi,
do you have a particular use case which will make this good to merge to core?

**Comment by mtlapointe** [comment]
Hi Tundebabzy,

Sure thing. We are an aerospace company and are required to track the batch/lot of almost everything we purchase for tractability. The Batch DocType works great for this, but the automatic batch name (random hash) isn't very useful for us. A sequential number, like a naming series, would be much better for tracking.  We also have to separate batches by project, so ideally we would have this captured in the Batch name.  In other words, for each project, we would setup a new batch naming series (ex. BC-JOB1-###, BC-JOB2-###, etc.). 

It looks like you used to be able to use a naming series with batch, according to this old forum post: (https://discuss.erpnext.com/t/batch-naming-series/9781)
However, I think when automatic batch ID was added back in April 2017 this functionality went away. 

Looking back in open issues, looks like someone else also requested to be able use a naming series:
https://github.com/frappe/erpnext/issues/4567

**Comment by mtlapointe** [comment]
Thank you!!!!!
