### ISSUE TITLE
Data Import does not move pass in inprogress

### ISSUE THREAD

**Issue by jasonbrowne** [frappe/erpnext#12305]
While importing items one has to refresh the screen to get a progress bar to show.
Further the import stalls at in progress
![bad-import](https://user-images.githubusercontent.com/19347811/34506244-e7c3f032-efdf-11e7-8701-d478267a14c1.png)

**Comment by jasonbrowne** [comment]
![where-house-error](https://user-images.githubusercontent.com/19347811/34506888-7c7f8e8e-efe5-11e7-92ac-0b1d594f04b2.png)

**Comment by jasonbrowne** [comment]
I even tested by exporting a warehouse csv and trying to import it back in.
Same issue no progress with no errors showing.

**Comment by manassolanki** [comment]
Please update your bench and try again. Feel free to open the issue incase of error (also comment the error traceback from the Error Log)

**Comment by jasonbrowne** [comment]
Still no errors reported for each import other than request time out.
Is there a way we can revert back to the old data import tool.
![request-time-out](https://user-images.githubusercontent.com/19347811/34531591-ac2169b4-f067-11e7-82bf-09e96cc1f1fa.png)

**Comment by jasonbrowne** [comment]
![nothing1](https://user-images.githubusercontent.com/19347811/34531660-eb3fdbbc-f067-11e7-97ad-0a521463a6a9.png)

 Neither import shows errors

**Comment by jasonbrowne** [comment]
![same-import-prohlem](https://user-images.githubusercontent.com/19347811/34532015-5acda116-f069-11e7-8c90-c32afed4dc79.png)
Have ran bench update, and still unable to import. No errors showing for import.
Open Source Applications for the Web

Website: https://frappe.io

Source: https://github.com/frappe
Installed Apps

ERPNext: v10.0.5

Frappe Framework: v10.0.6

**Comment by JmHeijting** [comment]
I have the same issue as described by JasonBrowne.
Running:
ERPNext: v10.1.18 (master)
Frappe Framework: v10.1.16 (master)

The issue occures when importing payment entries. The import tool states 'in progress', but the entries are imported.
