### ISSUE TITLE
Stock Reconciliation Difference Amount

### ISSUE THREAD

**Issue by ushashmi** [frappe/erpnext#12318]
The total difference amount of stock reconciliation is not calculated properly. Especially whenever there are negative amounts for any items in the grid. 

![sr](https://user-images.githubusercontent.com/25934387/34552357-68eb0b5e-f13a-11e7-9c57-3471ab836dbf.png)

**Comment by adnanmunir83** [comment]
we are also facing the same issue..

**Comment by shreyashah115** [comment]
Fixed via #11925
