### ISSUE TITLE
E-mail attachment language in "Attach Document Print"

### ISSUE THREAD

**Issue by itsdaveit** [frappe/erpnext#12312]
When I try to send an Sales Invoice E-Mail with the attached document print function, the PDF File attached is always in english, even if i select other languages like german. 

Meanwhile the text of the E-Mail itself is translated correctly. 
The PDF generation button uses the chosen language corectly, too.

**Comment by RANSoftRA** [comment]
Same here. I have also posted a question about this in the discuss portal.

https://discuss.erpnext.com/t/wrong-translation-in-pdf-sales-invoice-mail/32751

**Comment by RANSoftRA** [comment]
Seems like updating to ERPNext 10.0.8, Frappe 10.0.9 fixes this issue.

**Comment by itsdaveit** [comment]
fixed by:
https://github.com/frappe/frappe/commit/410e6cadd79e66f043a1733d08b2b57d6a5c00de

**Comment by sternbj** [comment]
I have same issue some years later. What can I do?
