### ISSUE TITLE
Re opening Data Import does not move pass in inprogress #12305 as its not resolved 

### ISSUE THREAD

**Issue by jasonbrowne** [frappe/erpnext#12315]
Still unable to import anything with new data importer.
Ran bench update this morning and still unable to import items, warehouses, etc.
Gui does not show any errors nor do i see any errors in the gui, or the logs.

![logs](https://user-images.githubusercontent.com/19347811/34536651-b0687d6a-f07a-11e7-82c3-6eb4c069540d.png)

Source: https://github.com/frappe
Installed Apps

ERPNext: v10.0.5

Frappe Framework: v10.0.6

![same-import-prohlem](https://user-images.githubusercontent.com/19347811/34536446-0080a7d8-f07a-11e7-94d5-7553f78b0b49.png)

Even tried exporting and reimporting and that does not work.

**Comment by jasonbrowne** [comment]
![gui-log](https://user-images.githubusercontent.com/19347811/34536849-50377184-f07b-11e7-8f45-1f1d38671de6.png)

**Comment by franciscobuendiao** [comment]
See versions, should have
ERPNext: v10.0.5 (master) and Frappe Framework: v10.0.6 (master).

**Comment by jasonbrowne** [comment]
Open Source Applications for the Web

Website: https://frappe.io

Source: https://github.com/frappe
Installed Apps

ERPNext: v10.0.5

Frappe Framework: v10.0.6

**Comment by jasonbrowne** [comment]
ran  switch-to-master 
verified on master 
tried new import same issue

**Comment by manassolanki** [comment]
Hi, Could you please comment the Error Log created by the given doctype.

**Comment by jasonbrowne** [comment]
The gui provides no errors and from the command line i can not find errors for a particular doctype. 

(11:19 frappe@ERPNext-Demo3 logs) > ls
auto_update_log.log             redis-queue.log
backup.log                      redis-socketio.error.log
bench.log                       redis-socketio.log
node-socketio.error.log         schedule.error.log
node-socketio.log               schedule.log
patches.txt                     web.error.log
redis-cache.error.log           web.log
redis-cache.log                 worker.error.log
redis-queue.error.log           worker.log

**Comment by jasonbrowne** [comment]
did not see any failed jobs
![back](https://user-images.githubusercontent.com/19347811/34586412-bba655c4-f158-11e7-9c81-36463b6eb737.png)

I was able to import from the command line

rt Item.csv e@ERPNext-Demo3 frappe-bench) > bench import-csv --submit-after-impor
Inserted row for "Item: MBSD-2016-TICKET-CVDS"Document successfully saved
Inserted row for "Item: MBSD-2016-TICKET-CO"Document successfully saved
Inserted row for "Item: MEM-ATP-16GB- D3-1600-E/R"Document successfully saved
Inserted row for "Item: HBA-TRUENAS- 9207-8I"Document successfully saved
Inserted row for "Item: SSD-ID-32GB- MLC-D150Q"Document successfully saved
Inserted row for "Item: SYS-ES- DSS316IX-DUAL- NODE"Document successfully saved
Inserted row for "Item: CPU-INT-XE- 2.10-15M-V2"Document successfully saved
Inserted row for "Item: TRUENAS-ES- BEZEL"Document successfully saved
Inserted row for "Item: DS-SR"Document successfully saved
Inserted row for "Item: *TRUENAS-Z30-HA/001"Document successfully saved
Inserted row for "Item: HBA-TRUENAS- 9207-8E"Document successfully saved
Inserted row for "Item: MBSD-2016-TICKET-COV"Document successfully saved
Inserted row for "Item: TRUENAS-Z30-HA/001-EXT"Document successfully saved
Inserted row for "Item: MBSD-2016-TICKET-COS"Document successfully saved
Inserted row for "Item: Shiny NVMe"Document successfully saved
Inserted row for "Item: BOM-*TRUENAS-Z30-HA/001-001"Document successfully saved
Inserted row for "Item: *TRUENAS-Z30-HA/001-EXT"Document successfully saved
Inserted row for "Item: Z35-TRUENAS"Document successfully saved
Inserted row for "Item: Z35-Drive"Document successfully saved
Inserted row for "Item: MBSD-2016-TICKET"Document successfully saved
Inserted row for "Item: Z35-CHASSIS"Document successfully saved
Inserted row for "Item: MBSD-2016-TICKET-SD"Document successfully saved
Inserted row for "Item: Registration"Document successfully saved
Inserted row for "Item: FreeBSD 2016 DevSummit - Ticket"Document successfully saved
Inserted row for "Item: PPR 445"Document successfully saved
Inserted row for "Item: *TRUENAS-Z30-HA/001-001 - With Product List"Document successfully saved
Inserted row for "Item: *TRUENAS-Z30-HA-S"Document successfully saved
Inserted row for "Item: SAMPLE"Document successfully saved
Inserted row for "Item: FIRSTBUNDLE"Document successfully saved
Inserted row for "Item: PPR 47"Document successfully saved
Inserted row for "Item: New Bundle"Document successfully saved
Inserted row for "Item: FreeNAS Certified 1U"Document successfully saved
Inserted row for "Item: Registration Dev Summit"Document successfully saved
Inserted row for "Item: RAM Bundle"Document successfully saved
Inserted row for "Item: "*TRUENAS-Z30-HA-D""Document successfully saved
Inserted row for "Item: *TRUENAS-Z30-HA"Document successfully saved
Inserted row for "Item: *TRUENAS-Z30"Document successfully saved
Inserted row for "Item: *TRUENAS-Z30-HA-D-NEW"Document successfully saved
Inserted row for "Item: *TRUENAS-Z30-HA-DNU"Document successfully saved
(13:41 frappe@ERPNext-Demo3 frappe-bench)

**Comment by jasonbrowne** [comment]
The BOMs also import successfully from the command line while not from the gui.

(15:56 frappe@ERPNext-Demo3 frappe-bench) > bench import-csv BOM.csv 
Inserted row for "BOM: BOM-*TRUENAS-Z30-HA/001-001"Document successfully saved
Inserted row for "BOM: BOM-*TRUENAS-Z30-HA/001-002"Document successfully saved
Inserted row for "BOM: BOM-Z35-TRUENAS-001"Document successfully saved

**Comment by jasonbrowne** [comment]
Was also able to import my chart of accounts via the command line, so I am convinced its the gui that is failing.

ales_Taxes_and_Charges_Template.csv    package.json
(17:00 frappe@ERPNext-Demo3 frappe-bench) > bench import-csv Account.csv       
Error for row "20000 - Liabilities - iX"Root cannot be edited.
Updated row for "Account: 21000 - Current Liabilities - iX"Document successfully updated
Updated row for "Account: 23000 - Payroll Deductions & Liabilities - iX"Document successfully updated
Updated row for "Account: 23100 - Payroll Employer Taxes - iX"Document successfully updated
Updated row for "Account: 23110 - Payroll Taxes - Federal - iX"Document successfully updated
Updated row for "Account: 23112 - Payroll Taxes - Foreign - iX"Document successfully updated
Updated row for "Account: 23111 - Payroll Taxes - State - iX"Document successfully updated
Updated row for "Account: 23200 - Employee Payroll Taxes - iX"Document successfully updated
Updated row for "Account: 23230 - Employee - State - iX"Document successfully updated
Updated row for "Account: 23240 - Employee - Foreign - iX"Document successfully updated
Updated row for "Account: 23220 - Employee - Local - iX"Document successfully updated
Updated row for "Account: 23250 - Employee - Other taxes withheld - iX"Document successfully up

**Comment by manassolanki** [comment]
Hi @jasonbrowne There is a doctype named "Error Log" which records the error happened during the data import. For opening the error log please check the given link
`erp.mysite.com/desk#List/Error Log/List`

**Comment by jasonbrowne** [comment]
I have created the task to import but it shows no progress or errors. Would be nice to see the errors as they are made on the same screen as the import like the old importer did. 

![import](https://user-images.githubusercontent.com/19347811/34702954-597cc16c-f4a5-11e7-8c2e-ac8b32c3b3f5.png)
![in-prog](https://user-images.githubusercontent.com/19347811/34702955-59905aec-f4a5-11e7-8baf-aaa305d4fee4.png)
![no-log](https://user-images.githubusercontent.com/19347811/34702956-59a4ad3a-f4a5-11e7-9678-6ab5de9b6661.png)
![bad-import](https://user-images.githubusercontent.com/19347811/34702957-59ba23f4-f4a5-11e7-8477-a685698fe86b.png)

**Comment by manassolanki** [comment]
Hi @jasonbrowne 
As per your email on the support, I assume that these will be resolved after fixing your rescheduler. If there are still some known issues, please let us know we will be more than happy to fix those.

**Comment by binary64** [comment]
I have the exact same issue. How do I fix rescheduler?

**Comment by binary64** [comment]
Maybe related to this error I see when trying to import:

```{'retry': 0, 'log': <function log at 0x7f83914d3d70>, 'site': u'x.co.uk', 'event': u'data_import', 'method_name': u'upload', 'method': <function upload at 0x7f8391f326e0>, 'user': u'x@x.co.uk', 'kwargs': {'from_data_import': u'Yes', 'data_import_doc': u'Import on 22-01-2018 07:34:29', 'user': u'x@x.co.uk'}, 'async': True, 'job_name': u'<function upload at 0x7fa7296add70>'}
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 95, in execute_job
    method(**kwargs)
TypeError: upload() got an unexpected keyword argument 'user'```

**Comment by manassolanki** [comment]
@binary64 Have you done any changes in the code.

I am not able to replicate, please reopen if the issue still persists

**Comment by binary64** [comment]
I think perhaps the scheduler wasn't running. Would be nice to have a banner alert about that.

**Comment by reansey** [comment]
I am also got the problems, cannot import data
{'retry': 0, 'log': <function log at 0x7f4a11170ed8>, 'site': 'ibilling.erp', 'event': u'data_import', 'method_name': u'upload', 'method': <function upload at 0x7f4a11a1f668>, 'user': u'reansey@gmail.com', 'kwargs': {'from_data_import': u'Yes', 'data_import_doc': u'Import on 14-05-2018 15:06:22', 'user': u'reansey@gmail.com'}, 'async': True, 'job_name': u'Import on 14-05-2018 15:06:22'}
Traceback (most recent call last):
  File "/home/reansey/ibilling/apps/frappe/frappe/utils/background_jobs.py", line 97, in execute_job
    method(**kwargs)
  File "/home/reansey/ibilling/apps/frappe/frappe/core/doctype/data_import/importer.py", line 477, in upload
    data_import_doc.save()
  File "/home/reansey/ibilling/apps/frappe/frappe/model/document.py", line 260, in save
    return self._save(*args, **kwargs)
  File "/home/reansey/ibilling/apps/frappe/frappe/model/document.py", line 300, in _save
    self.validate_update_after_submit()
  File "/home/reansey/ibilling/apps/frappe/frappe/model/document.py", line 688, in validate_update_after_submit
    self._validate_update_after_submit()
  File "/home/reansey/ibilling/apps/frappe/frappe/model/base_document.py", line 576, in _validate_update_after_submit
    frappe.UpdateAfterSubmitError)
  File "/home/reansey/ibilling/apps/frappe/frappe/__init__.py", line 327, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/home/reansey/ibilling/apps/frappe/frappe/__init__.py", line 313, in msgprint
    _raise_exception()
  File "/home/reansey/ibilling/apps/frappe/frappe/__init__.py", line 286, in _raise_exception
    raise raise_exception(msg)
UpdateAfterSubmitError: Not allowed to change Import Status after submission
