### ISSUE TITLE
Taxes and Charges from PO is not copied in PI

### ISSUE THREAD

**Issue by Suprazz** [frappe/erpnext#12311]
The issue is new with the recent update (v10).

When I create a charge in the Taxes and Charges table when I create an invoice from the PO, the default values of the PI overwrite it. In my case, it replace my shipping charge with 2 taxes.

**Comment by tundebabzy** [comment]
Hi @Suprazz 
Please add screenshots or animated gif to explain this?

**Comment by Suprazz** [comment]
This is a dummy PO
![image](https://user-images.githubusercontent.com/3640711/34532969-2ff000b6-f086-11e7-94b5-e69c12dbd42e.png)
This is what the invoice look like:
![image](https://user-images.githubusercontent.com/3640711/34532980-3ca8e7fa-f086-11e7-8b40-5a485339667a.png)

So, I have to remove the taxes and put shipping fee again.

**Comment by rohitwaghchaure** [comment]
@Suprazz 

Thanks for reporting an issue, we have identified and fixed the issue and soon we'll release  it
