### ISSUE TITLE
Wrong Invoice State

### ISSUE THREAD

**Issue by pagliaso** [frappe/erpnext#12325]
Hello,

I have just updated to new version 10, and one of the first issues I am experimenting is that in the List of Invoices Table, the list shows the state of the invoice incorrectly.

So I can see there a green Invoice that appears as paid, even though the Invoice has still a peding amount.

Nothing more by now, many thanks and kind regards from Spain

**Comment by umairsy** [comment]
Please post this issue on the discuss forum. If it is validated as the bug, we can reopen this issue.
