### ISSUE TITLE
Rename option in tree view

### ISSUE THREAD

**Issue by nabinhait** [frappe/erpnext#12326]

**Comment by JrenzP** [comment]
This is also an issue for me. Got me a lot of problems in terms of time efficiency.

**Comment by achillesrasquinha** [comment]
Just wondering, would a dialog be necessary to rename? Can't we display a popper right there that considers input? Somewhat like [XEditable](https://vitalets.github.io/x-editable/)?

**Comment by Muhammadsaif7** [comment]
I do not want this emails.
