### ISSUE TITLE
Shopping Cart Enhancements

### ISSUE THREAD

**Issue by nabinhait** [frappe/erpnext#12322]
- [ ] Mode of Payments selection
     - Cash on Delivery option
     - Option to choose the payment gateway
- [ ] Delivery Schedule
- [ ] Coupons / Gift Cards
     - [ ] Coupon Code Master
     - [ ] Based on the amount/quantity
     - [ ] Flat or percentage based
     - [ ] Underlying linked with the Pricing Rule
     - [ ] Max number of uses
     - [ ] Expiration 
- [ ] Loyalty Points
    - [x] Customer Enrollment in the Loyalty Program
    - [x] Collection from the Sales Invoices
    - [x] Expiry Date
    - [ ] Redemption

**Comment by Olawale1** [comment]
Hi,

This is a very good enhancement. I trust that these features will be built into the relevant DocTypes so that they are not only limited to the Shopping Cart. Features like Coupons / Gift Cards and Loyalty Points should be available via POS / Sales Invoice as well

Thanks

**Comment by rmehta** [comment]
https://github.com/frappe/erpnext/issues/12786

https://github.com/frappe/erpnext/issues/12787

**Comment by dawoodjee** [comment]
+1 for cash on delivery, much more useful in places without readily usable Payment Gateways
