### ISSUE TITLE
V10: Sales Invoice rounded total blanked on edit

### ISSUE THREAD

**Issue by lasalesi** [frappe/erpnext#12336]
**Actual behvaiour:**
The rounded total value is set to 0 when changing contents of a sales invoice.

**Expected behaviour:**
The rounded total should be the rounding value.

**Steps to reproduce:**
* Take a ERPNext v10.0.5 (master)
* Create a new sales invoice
* Use a tax which gives a total that needs rounding
* Observe rounded total value (is present and correct)
* Now, change quantity in the item table
* Observe that rounded total value disappears.

![grafik](https://user-images.githubusercontent.com/26505250/34568788-2eb32944-f167-11e7-99e6-f38a3d17395c.png)

**Affected version**
ERPNext 10.0.5 (was still good in 9.x)

**Comment by lasalesi** [comment]
It seems that when the value was set to 0 and the document saved again, the correct rounded total is set.

![grafik](https://user-images.githubusercontent.com/26505250/34569262-83c953e4-f168-11e7-9189-a1d3296403ca.png)

**Comment by OneiricIT** [comment]
Same issue here, however I find it when I duplicate an invoice (which has disable rounded total checked) and save, then change the tax charges template and save again - the disable rounded total is unchecked.

**Comment by umairsy** [comment]
@lasalesi yes, the rounded total is calculated on save only. @OneiricIT can you please share the GIF of this issue?

**Comment by OneiricIT** [comment]
@umairsy I have actually since disabled rounded total as I do not use, so unable to share a gif. It should be reproducible based on the steps listed above unless it has been fixed....

**Comment by lasalesi** [comment]
I think we can close this if it is calculated on save.
