### ISSUE TITLE
Account numbers are auto-assigned when renaming the account pre-numbered

### ISSUE THREAD

**Issue by JrenzP** [frappe/erpnext#12332]
I suggest that you put a feature where you can opt out the assignment of account numbers.
Or at least put an option to drag the accounts for the desired position in Chart of Accounts / Account Tree

**Comment by umairsy** [comment]
You can already do that. In the Account master, change the Parent for an Account to change its location.

In the Account naming, if you just leave Account Name blank, then it will not have any impact in the naming.
