### ISSUE TITLE
Enhancement Overlapping Text in Sales Funnel

### ISSUE THREAD

**Issue by djpalshikar** [frappe/erpnext#12330]
![screenshot-2018-1-4 sales funnel](https://user-images.githubusercontent.com/23133635/34566209-c3e506a6-f183-11e7-8637-8707a467b4e3.png)

**Comment by Olawale1** [comment]
This issue has been there for a long time. Hope it finally gets fixed. Thanks for reporting it...

Kind regards,

**Comment by djpalshikar** [comment]
@umairsy please close this. It is duplicate , my bad. #10711 is already referring to the same thing.
