### ISSUE TITLE
Problem with sales report not pulling qty ordered

### ISSUE THREAD

**Issue by mwind1** [frappe/erpnext#12339]
See attached. The qty ordered equals 0 but the delivered qty for pos column is working
![ordered qty not showing up](https://user-images.githubusercontent.com/35116494/34584715-e24ac25c-f16a-11e7-8c46-425ddd879751.jpeg)

**Comment by umairsy** [comment]
Ordered Qty for an item refers to the total qty of items ordered to the Supplier for the purchasing at the time of creating that Sales Order. Hence Ordered Qty there is just for the reference and should not be compared with the Delivered or Billed Qty, which is updated based on Delivery Note and Sales Invoice created against that Sales Order.
