### ISSUE TITLE
Add Employee Advance to Transactions in Authorisation Rule

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#12343]
Hi,

Please add the Employee Advance document to the list of Transactions in the Authorisation Rules. This is a very important part of the workflow in most organisations!

There is also still a similar pending issue for Expense Claims https://github.com/frappe/erpnext/issues/8546

Both documents need authorisation levels applied to them urgently

Thanks

**Comment by PawanMeh** [comment]
v11 workflow has the ability to specify conditions, I think this should suffice to meet the requirements. If this is inadequate, the issue can be re-opened.

![workflow_v11](https://user-images.githubusercontent.com/20460498/47252282-c82a5800-d45f-11e8-9c67-2d849d76eaf8.png)
