### ISSUE TITLE
Valuation Rate Issue affecting Gross Profit Report [V10]

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#12341]
Hi,

When trying to view the Gross Profit report after upgrading to V10 we encountered the following error:

"Valuation rate not found for the Item XXXXXXX, which is required to do accounting entries for None . If the item is transacting as a zero valuation rate item in the None, please mention that in the None Item table. Otherwise, please create an incoming stock transaction for the item or mention valuation rate in the Item record, and then try submiting/cancelling this entry"

1. When we checked the incoming entry (Material Receipt) for this item, the 'Allow Zero Valuation Rate' button was checked so why this error? Is it from the Sales Invoice which has been submitted already? I wouldn't expect issues from the Sales Invoice document since the Item was already marked as a Zero Value item when it was brought in

2. Why does the error message refer to 'None' instead of showing the actual document ID from where the issue is emanating?

Please help fix these urgently as the Gross Profit report is quite an important report!

Thanks

**Comment by Olawale1** [comment]
Please help fix this issue... we have not been able to view the Gross Profit report for a week now! We have several existing Sales Invoices that contain Items which were brought in with zero value (Allow Zero Valuation Rate was checked when the items were received because they were supplied free of charge). Some of these items are serialized and some aren't. We need this resolved as quickly as possible 

Thanks

**Comment by Olawale1** [comment]
Steps to replicate:

1. Create and Submit a Material Receipt (Stock Entry) for an item and tick the 'Allow Zero Valuation Rate' checkbox 

2. Create and Submit a Sales Invoice for the same item (without ticking the Allow Zero Valuation Rate checkbox)

There are 3 issues here:

1. When you try to open the Gross Profit report, you encounter the error described above

2. The Sales Invoice doesn't automatically recognize that the item is a Zero Valuation item

3. The Sales Invoice doesn't validate the valuation rate at the point of Submission! This allows users to keep submitting invoices only to end up with errors when they want to check the Gross Profit report... not a very nice user experience 

Thanks

**Comment by rohitwaghchaure** [comment]
Fixed via https://github.com/frappe/erpnext/pull/12516
