### ISSUE TITLE
Purchase Invoice - Due Date reverts to first time value on save

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#12340]
On saving Purchase Invoice, the value of Due Date is changing automatically to Posting Date of the invoice.

![due-date](https://user-images.githubusercontent.com/910238/34598266-a5bfce70-f211-11e7-8da1-62a76a994df3.gif)

**Comment by pratu16x7** [comment]
Changing to whatever was set the first time.

**Comment by tundebabzy** [comment]
#12382
