### ISSUE TITLE
[bug] Delivery and Billing Status

### ISSUE THREAD

**Issue by snvora** [frappe/erpnext#12354]
This is the way in which issue may be replicated.

We have two items to be delivered in sales order.
1. A - 2,50,000 mm
2. B - 2 Nos

First delivery is made of product A of 250000 mm. Invoice for the same is prepared.

Now Order showing status as only to bill although product B is yet to be delivered. Its not possible now to make delivery note for product B.

**Issue**
Maybe we need to work on fractions of qty delivered and amount billed. Although it shows upto 2 decimals, it should check more decimals.

**Comment by umairsy** [comment]
Issue replicating. For the reference, check SO %SO-00087 in gagets account

@snvora thanks for reporting this issue.
