### ISSUE TITLE
VAT Invoices for UAE

### ISSUE THREAD

**Issue by Mishaal1021** [frappe/erpnext#12353]
Hi,

With respect to the VAT implementation, one of the requirements is to show tax amount for each item. I noticed that this has been accommodated in ERP Version 10, but is there any way to customize it a little.

Although, it shows as a table, there is no way to customize this table. See below:

 

Ideally we would like the tax amount for each item to be part of the item table. If that is not possible, and we are required to do separate table, we would like to be able to customize it to include same description as above. Any assistance would be appreciated. 

Regards,
![tax invoice](https://user-images.githubusercontent.com/29452673/34637994-fe7e7ee0-f2d3-11e7-82be-27326a80c146.jpg)

**Comment by adnanmunir83** [comment]
it's already Fixed.   check the this invoice in version "Release v10.0.3" or above.

**Comment by Mishaal1021** [comment]
Hi,

I am using version v10.0.6, but it still doesn't seem to be fixed. If you can attach the template - would really appreciate it. Essentially, we are looking for a format similar to attached examples. 
[Supplier Invoices VAT Format.pdf](https://github.com/frappe/erpnext/files/1609851/Supplier.Invoices.VAT.Format.pdf)

**Comment by Mishaal1021** [comment]
As a temporary work around, I have added two extra field in “Sales Invoice Item”: “Tax” and “Amount with Tax”.

I am not trying to create custom scripts to add formulas in there, such that:

Tax = doc.amount * .05
Amount with Tax = doc.amount + doc.tax

But since I am new at this, I am really struggling with the custom script – below is the failed attempt at it:

frappe.ui.form.on("Sale Invoice Item", "tax", function(frm, cdt, cdn){
    var d = locals[cdt][cdn];
    frappe.model.set_value(cdt, cdn, "tax", d.amount * 0.05);
});

I will post this on github as well, but any assistance you could provide would be really appreciate. Also, I think this is a very simple and quick fix, and would request you include it in the core at the earliest. 

Having two tables: 1 for item and 1 for tax break-down is not the best solution for UAE VAT implementation as it makes invoices much longer. I have attached some sample supplier invoices here for your reference as well.

Your quick response would be really appreciated.

**Comment by adnanmunir83** [comment]
i can find it in my list. here is the screenshot for that

![image](https://user-images.githubusercontent.com/26667854/34651228-eefe9f22-f3e6-11e7-95c0-2174f850d2f6.png)

if you want to customize it according to the attached Invoices, that is also possible with little more effort in Custom HTML.

**Comment by umairsy** [comment]
@nabinhait please review if we could incorporate the feature of itemised tax details in the item table itself.

**Comment by nabinhait** [comment]
@Mishaal1021 As mentioned by @adnanmunir83 the tax rate and amount is already part of invoice item table in the latest version. Also we have introduced a new print format called "Tax Invoice" which shows taxes in Item table. As tax rate and amount is now part of item table, you can easily customize your print format as per your requirements.

Closing this issue.
