### ISSUE TITLE
Add Payment Details to Sales Payment Report

### ISSUE THREAD

**Issue by PawanMeh** [frappe/erpnext#12357]
![sales_payment_summary](https://user-images.githubusercontent.com/20460498/34640045-8df084e6-f311-11e7-983a-d04959d61da0.gif)

**Comment by Olawale1** [comment]
Hi @PawanMeh 

Trust you're doing well. Are you still working on this?

Cheers!

**Comment by olamide2** [comment]
Hello @nabinhait 

Can you confirm that this has been merged?

We are on the current version of ERPNext and we have the old version of this report showing as below

![image](https://user-images.githubusercontent.com/23294026/36314792-2f565d3a-1336-11e8-8610-ceee8f2b4c46.png)

**Comment by nabinhait** [comment]
@olamide2 There was one commit missing in master branch. I have pushed it into hotfix today, it will be released to master by tomorrow.
