### ISSUE TITLE
Sales Payment Summary Report Not Working properly 

### ISSUE THREAD

**Issue by olamide2** [frappe/erpnext#12350]
The Sales Payment report is designed to show Sales by Date/user/Payment method

While we are able to see sales by date and user, but it adds up all sales by payment method together. This makes it impossible to see the total sales inflow per payment method as needed for end of day reconciliation purposes.

See sample report below where sales by Cash and cheque is lumped together with no seperation

![image](https://user-images.githubusercontent.com/23294026/34627578-68e0e340-f261-11e7-8edc-794ee3f60018.png)

**Comment by PawanMeh** [comment]
Closing this one, the report is enhanced now and Pull Request is sent. You can follow the progress of this issue on https://github.com/frappe/erpnext/issues/12357
