### ISSUE TITLE
Header not adjusting in mobile browser

### ISSUE THREAD

**Issue by jibon57** [frappe/erpnext#12367]
First of all thanks for the excellent software. I am facing problem with mobile browser. Here is the screen shorts:
1)
![271515326923_ pic](https://user-images.githubusercontent.com/6080277/34649261-cf1f9dd4-f3d5-11e7-8d56-3f436231be7d.jpg)

2)
![261515326921_ pic](https://user-images.githubusercontent.com/6080277/34649264-dab311e4-f3d5-11e7-846d-fc106eb68b32.jpg)

3)
![251515326919_ pic](https://user-images.githubusercontent.com/6080277/34649265-deab7e08-f3d5-11e7-8496-498ab27bff59.jpg)

**Comment by joezsweet** [comment]
You need tp complete setup ..the green bar will disappear and will fix your prob

**Comment by jibon57** [comment]
@joezsweet thank you !!
