### ISSUE TITLE
Accounting Numbering in COA should Determine the Account Position in the Financial Statement

### ISSUE THREAD

**Issue by Fredoluka** [frappe/erpnext#12360]
Kudos to the team and the community for the newly rolled out version 10.One of the much awaited features that was rolled out with version 10 is the account number.One of the main function of account number is to determine the positioning of an account in the finacial statement.But i discovered this is not the case in version 10.Just for example if you give the following numbering in the COA:
1000-Cash
2000-Bank
3000-Debtors
4000-Stock
and you go to balance sheet to see the positioning of the above,it will never be arranged  in the above manner.In fact the number never show in the balance sheet.Or maybe i am missing something.Kindly help @tundebabzy @nabinhait

**Comment by Olawale1** [comment]
This is very important. Order of liquidity is one of the requirements of IFRS and it's almost like the whole point of account numbers!

Cheers!

**Comment by jof2jc** [comment]
+1
Account number should be showing up on all financial statements. Now only appear on General Ledger

**Comment by mhbu50** [comment]
Account number is very important in GCC country especially Saudi Arabia
