### ISSUE TITLE
Pos Barcode auto search not working

### ISSUE THREAD

**Issue by skarthik3** [frappe/erpnext#12363]
Hi 

In pos when ever we enter the bar code in the search item it returns no data 

![1](https://user-images.githubusercontent.com/35178177/34644475-5fc16a4e-f35d-11e7-875c-8725e4846b69.png)

but if we make changes to item group in item group text box it will fetch the correct item. 

![screen2](https://user-images.githubusercontent.com/35178177/34644515-1c985d58-f35e-11e7-90de-014ac0936a52.png)

I think it should auto populate when we enter the bar code 

Thank you.

**Comment by rohitwaghchaure** [comment]
Hi @skarthik3 

Auto populate will make lot of issue, better you remove the item group for barcode search.

**Comment by skarthik3** [comment]
Hi

I agree and know auto search  make lot of issues but if we just type bar code and press enter without item group it shows "no data" but if i enter item code it will work.

**Comment by umairsy** [comment]
Seems to be working fine in my test account. Please check again.

![barcode](https://user-images.githubusercontent.com/910238/36097261-3f7a0202-1020-11e8-8d4f-ec23cb1f89a1.gif)

If issue is still replicating, feel free to reopen the issue.
