### ISSUE TITLE
Detailed billing of time worked on projects.

### ISSUE THREAD

**Issue by dumiller** [frappe/erpnext#12369]
Most of our clients require detailed billing on cost-plus projects. The information from the employee's timesheets needs to be extrapolated and put on the invoice. The following invoice should be able to be put on the sales invoice created from a project using timesheets.

Date Worked
Hours Worked
Task Type Completed
Employee Name
Description of work done.

This is an example of projected billing options from another application we have used in the past and show the types of options required for detailed billing.

<img width="513" alt="screen shot 2018-01-07 at 10 01 46 pm" src="https://user-images.githubusercontent.com/19696594/34659489-6c0d0b20-f3f6-11e7-9841-6c2bff80fa1e.png">

**Comment by umairsy** [comment]
You can create Sales Invoice from Timesheet, with Timesheet details fetched into Sales Invoice, in the Timesheet table.

https://erpnext.org/docs/user/manual/en/projects/timesheet/sales-invoice-from-timesheet
