### ISSUE TITLE
Mode of Payment 

### ISSUE THREAD

**Issue by skarthik3** [frappe/erpnext#12361]
Hi 

When I create/edit mode of payment set account type to general

In default account only two type of accounts namely cash account and bank account populates. Is that normal because for credit cards we do not debit bank account or cash account directly we debit account receivable and then pass a journal entry against it 
for example a customer paid me Rs. 100 by card I debit card receivable Rs100 
i pass a journal entry as credit card receivable 100 debit bank rs98 debit card expense a/c Rs 2(being his fee/commission)
Thank you in advance awesome product.

Also How to donate money to the project

**Comment by umairsy** [comment]
You can create third Mode of Payment as Credit Card, and may be select your Bank Account in it.

You will have to manually split the actual payment received from the Bank and add rest of the amount under Deductions table of the Payment Entry.

**Comment by umairsy** [comment]
Thanks for your interest in making payment.

You can contribute to this project from ERPNext Foundation.

https://erpnext.org/members

**Comment by skarthik3** [comment]
Hi 

I think you misunderstood me
For Credit card default option should be debtors account receivable but it does not allow us to select debtors
