### ISSUE TITLE
Unique Id tracker suggestion 

### ISSUE THREAD

**Issue by skarthik3** [frappe/erpnext#12372]
Hi 

I have observed that all ids start  with 001 and increment hence forth for example sales invoice unique id will at sinv001 and it increments to sinv002 so on but we can change the unique id to be of the format sinyyyymmddid eg sinv20180108001 and the id resets every day so the length of the id will stay constant. 

This will be advantageous.

**Comment by umairsy** [comment]
This is configurable. In the Naming Series, you can enter ddmmyyyy in th naming series.

https://discuss.erpnext.com/t/you-can-use-custom-field-in-naming-series-along-with-yy-mm-dd-option/10865/24
