### ISSUE TITLE
Daily Work Summary Email

### ISSUE THREAD

**Issue by PrakashH** [frappe/erpnext#12376]
Currently, What did you work Today? email is going to active Employees only. It should go to active employees and users too.

Use case: We have some foundation employee added as a User in frappe.erpnext.com. But to have daily time log triggered to them, will also need to add them as Employee. Will be better if Daily timelog summary is emailed based on Active Users, and not based on Employee.

**Comment by Olawale1** [comment]
I'm sure this will come with some kind of adjustable settings... I can imagine that most ERPNext users don't want this going out to All Users!

Maybe having a setting where you can select applicable roles would be better

Cheers!

**Comment by rmehta** [comment]
- [ ] Convert Daily Work Summary to a table
- [ ] Add table for users
- [ ] Select Holiday List
- [ ] Patch to convert current settings to a table
