### ISSUE TITLE
[Docs] Image links are broken for ERPNext Help 

### ISSUE THREAD

**Issue by Alchez** [frappe/erpnext#12374]
From the **[Beta](https://beta.erpnext.com/)** server:

> Documentation > ERPNext > User Manual > English > Stock > Material Request

![image](https://user-images.githubusercontent.com/13396535/34665263-84dd21e6-f485-11e7-8a84-c1b33a1e34b8.png)

From the **[Demo](https://demo.erpnext.com/)** server:

> Documentation > ERPNext > User Manual > English > Stock > Material Request

![image](https://user-images.githubusercontent.com/13396535/34665304-b1f3e8b8-f485-11e7-850b-3cf3f462464b.png)

**Comment by umairsy** [comment]
@kennethsequeira please review and fix.

@Alchez thanks for reporting.
