### ISSUE TITLE
Cannot change invoice title after the associated supplier has acquired a tax number.

### ISSUE THREAD

**Issue by mehmetalianil** [frappe/erpnext#12373]
I change titles often, even after a while I have submitted the invoice.
With v10, and I guess tax ID becoming more integrated in, I noticed that editing title is not allowed, giving the following message: 

Not allowed to change Tax Id after submission

As if, the event triggered by the edit on the Title force checks all entries and whether they are still the same, (since the document is already submitted) and fetches the associated supplier and realizes that the Tax ID has changed, and calls off.

**Comment by umairsy** [comment]
You can link Document TItle with some other field instead of Tax ID.

https://erpnext.org/docs/user/manual/en/customize-erpnext/document-title

**Comment by mehmetalianil** [comment]
The form Purchase Invoice only has {supplier_name} as its display default.
