### ISSUE TITLE
Leaderboard as analysis

### ISSUE THREAD

**Issue by pratu16x7** [frappe/erpnext#12389]
Let's get around to doing this right. Thanks to @nabinhait, there are some metrics that could make the Leaderboard a good analysis tool:

- Customer: Total Sales (by `base_net_total` in Sales Invoice), Receivable Amount
- Supplier:  Total Purchases, Payable Amount (from Accounts Payable)
- Item: Sales Value (and quantity), Purchased Value (and quantity), available stock value (quantity)
- Sales Partner and Sales Person: Total Sales, Target qty(budget), Communications (sales orders/invoices)

Gross Profit could also be one of these.

**Comment by Olawale1** [comment]
My thoughts exactly! And yes, Gross Profit should definitely be included 

Kind regards,

**Comment by vishdha** [comment]
fixed via https://github.com/frappe/erpnext/pull/13001
