### ISSUE TITLE
Heat Map not working 

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#12387]
![screen shot 2018-01-09 at 12 12 08 pm](https://user-images.githubusercontent.com/910238/34708327-25cbc29e-f538-11e7-905d-bafda5ac3a68.png)

**Comment by djpalshikar** [comment]
This is true for items as well.

**Comment by joepa37** [comment]
For education module as well.

**Comment by joepa37** [comment]
Data seems to be correctly.
![screen shot 2018-01-16 at 7 40 17 am](https://user-images.githubusercontent.com/15274305/34991815-a686a7c0-fa90-11e7-8426-dfe48c223b07.png)

**Comment by joepa37** [comment]
> Timestamp convertion seems to be the problem...

![screen shot 2018-01-18 at 5 02 02 pm](https://user-images.githubusercontent.com/15274305/35126001-53c9d9b6-fc71-11e7-8003-be0e84886038.png)

> Actually is giving the date at 6:00 AM

![screen shot 2018-01-18 at 4 55 56 pm](https://user-images.githubusercontent.com/15274305/35125765-777314aa-fc70-11e7-8fdd-9d07fb20c14b.png)

> When change the query to convert at 12:00 AM

![screen shot 2018-01-18 at 5 04 49 pm](https://user-images.githubusercontent.com/15274305/35126096-b7dbd26a-fc71-11e7-9c84-ea0320317fe1.png)

> It actually works

![screen shot 2018-01-18 at 5 05 52 pm](https://user-images.githubusercontent.com/15274305/35126167-ef4a92e0-fc71-11e7-9a2d-e303a9786221.png)

**Comment by bghayad** [comment]
Hello @umairsy 
Do you have information if this problem resolved?
Because I am running ERPNext version 10.1.13 and still problem is existed.
Regards
Bilal

**Comment by bghayad** [comment]
Hello;
I did upgrade and the version is ERPNext: v10.1.18 (master), but still the heatmap is not showing any transactions on it.
Regards
Bilal
