### ISSUE TITLE
[bug] Sales order link to purchase order not working

### ISSUE THREAD

**Issue by snvora** [frappe/erpnext#12388]
Steps to replicate issue
1. Create sales order.
2. Create material request from the sales order.
3. Create purchase order from the material request.

Expected Behaviour (Not Working)
1. The dashboard in sales order should show a link to the purchase order.
2. Ordered Qty in Items table in sales order should get updated for respective items ordered.

**Comment by vishdha** [comment]
fixed via https://github.com/frappe/erpnext/pull/12633
