### ISSUE TITLE
Documentation: Broken Youtube video

### ISSUE THREAD

**Issue by mist-01** [frappe/erpnext#12392]
The video on [this page](https://erpnext.org/docs/user/manual/en/customize-erpnext/articles/making-custom-reports-in-erpnext) is broken.  Please update the page so I can watch the video :-)

![image](https://user-images.githubusercontent.com/2146048/34712273-b0c8896a-f53b-11e7-814b-dfc6b81ad107.png)

**Comment by manassolanki** [comment]
@mist-01  Please send a PR.

**Comment by mist-01** [comment]
Looks like someone got to it before me: https://github.com/frappe/erpnext/commit/82bd3302ee7d7a2418d671313729d96d85468c67#diff-9f34405b1178410b8c968937294468c4

It just needs to be re-published.
