### ISSUE TITLE
New Documents Should Not Be Renamable Until Name Has Been Set

### ISSUE THREAD

**Issue by tundebabzy** [frappe/erpnext#12394]
Example:
![peek 2018-01-09 11-00](https://user-images.githubusercontent.com/818803/34715325-7daff2fc-f52c-11e7-924e-2d86793f7cb8.gif)

Branch: hotfix

**Comment by harsh0214** [comment]
Have made a Pull Request for the same on Frappe repo

https://github.com/frappe/frappe/pull/4830
