### ISSUE TITLE
[erpnext.org] no field for service provider member to specify website URL

### ISSUE THREAD

**Issue by clarkejj** [frappe/erpnext#12409]
I did not find any field in the service provider page where I can specify (my) website URL - This issue added to erpnext.com  issues list since I could not find a corresponding issues list for erpnext.rog)

Attached are 2x screen shots to illustrate 
1) entry form page for service provider with no field to specify URL?
2) listing page with the website URL unspecified

![screenshot from 2018-01-09 14-39-01](https://user-images.githubusercontent.com/11706903/34745447-c805a15a-f54d-11e7-8558-03c89de90d38.png)
![screenshot from 2018-01-09 14-58-45](https://user-images.githubusercontent.com/11706903/34745448-c828b21c-f54d-11e7-96ce-a953ac7cb6e0.png)

**Comment by vishdha** [comment]
https://github.com/erpnext/foundation/pull/110
