### ISSUE TITLE
Filter not working to see related documents

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#12404]
Hello,

When I'm on the item doctype and try to see related sales, the filter to see only related is not created like before.

This can be reproduced on beta.erpnext.com, just go on any document that have a related document (sales order with delivery note, item with sales order, etc) and try to see the related documents.

Gif:
![untitled](https://user-images.githubusercontent.com/18335894/34731688-3b56d72c-f54a-11e7-97db-0ee7a4287ca0.gif)

**Comment by ci2014** [comment]
@applepipe Thats only on the first try, right? On the second try (when you go back and click on sales order again) it will work (!?)

**Comment by applepipe** [comment]
@ci2014 

No, it just adds another filter on another line but doesnt work, this happens on developer branch but can also be reproduced in beta.erpnext.com

**Comment by umairsy** [comment]
Seems to be working fine in my test account.

![itm](https://user-images.githubusercontent.com/910238/36098775-3b90d070-1026-11e8-9124-f10fb17758bd.gif)

If issue is still replicating, feel free to reopen it.
