### ISSUE TITLE
Template to Variant Updation - Review defaults in Item Variant Settings

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#12402]
As per the latest updates, in the Item, there are many fields which are set only once. Also, there are fields in which value cannot be changed once transactions are created. Such fields should not be added in the Item Variants Settings.

Following is the issue reported by one of the User. Valuation Method should not be there in the Variant Settings. Please review other fields updated by default as well.

![screen shot 2018-01-09 at 8 05 09 pm](https://user-images.githubusercontent.com/910238/34725989-b1a2d57e-f578-11e7-801e-fbb8003dde66.png)

**Comment by somicoito** [comment]
Hi Umair, I agree with you but I might need a field to be copied to a variant on creation, i.e. "has serial number". After creation I can't change the value but I might want to make variants with serial number...

**Comment by rohitwaghchaure** [comment]
Closing this issue, have already removed set only once property for the field has serial no,has batch no, maintain stock in item doctype

**Comment by savadibrahim** [comment]
where do you find has_batch_no in item variant settings?

**Comment by savadibrahim** [comment]
i couldnt find it

**Comment by asem89** [comment]
Similar problem - Has Serial No field is not copied with Variant change.
There is no field "has_serial_no" to add to Item Variant Settings.

This still doesn't work on 2.10.2019 ...

**Comment by asem89** [comment]
Still cannot set has_serial_number to be copied from Template Item to Item Variants.

**Comment by asem89** [comment]
@rohitwaghchaure could you change also this? So that has_serial_number gets copied from Template to Variant?

We use it to create sometimes dozens of Items. It's a waste of time to click on Has serial number for every each of them.
