### ISSUE TITLE
Unable to Open Opportunities (Since Today's Update)

### ISSUE THREAD

**Issue by KDSNicole** [frappe/erpnext#12403]
When I click on Opportunity from the CRM page or the Customer's page I am unable to open the Opportunities. I get this error...

Not found
DocType Sales Sales - Calabria Cabinetry Maintenance not found
The resource you are looking for is not available

I am not trying to select a resource I am just trying to open an Opportunity

**Comment by Olawale1** [comment]
Same issue here! Ours says 'DocType Product Services not found'

Please fix urgently... this is affecting CRM operations significantly

Thanks

**Comment by KDSNicole** [comment]
I agree. This is putting a damper on productivity. We are all making lists of items we have to go back in and input later.

**Comment by joolsr** [comment]
Please confirm which version you are running ie is this a v10 bug ?

**Comment by KDSNicole** [comment]
Yes this started as soon as our system upgrade to V10

**Comment by joolsr** [comment]
Thanks at least I know to hold off updating for a while as I will need this fixed too

**Comment by KDSNicole** [comment]
Any update? This is affecting our work glows and our productivity!

**Comment by opsninja1** [comment]
Need to know when this is going to be fixed......

**Comment by joolsr** [comment]
Hi Nicole
If you're a paying customer for their hosted service, best to email support@erpnext.com as it will raise a ticket with them. Also don't forget you can call them in India .

**Comment by KDSNicole** [comment]
So what is the point of these Help pages then? When you are in ERP and you click on Help it has the option to report your issue. So why bother reporting it this way or even offering this to us if no one does anything with these?

**Comment by joolsr** [comment]
The trouble is that Frappe who provide the hosted service get loads of bug reports. They heavily prioritise their own customers, which is fair enough but you must really make it clear you are a paying customer with your account number as otherwise it can very occasionally go under the radar. Usually they are very responsive and fix things fast. But please email the main support email address or call them direct as I think they just havent picked up on this fault report ..

**Comment by KDSNicole** [comment]
I appreciate the added information. I have already emailed the address you provided. Much appreciated!

**Comment by KDSNicole** [comment]
Never heard back from them. Has anyone else?

**Comment by rmehta** [comment]
>  DocType Sales Sales - Calabria Cabinetry Maintenance not found

This is clearly an issue with your customization.

**Comment by opsninja1** [comment]
Please elaborate?
