### ISSUE TITLE
Indicator not showing in the sales order, delivery note item

### ISSUE THREAD

**Issue by rohitwaghchaure** [frappe/erpnext#12413]
![screen shot 2018-01-10 at 12 18 42 pm](https://user-images.githubusercontent.com/8780500/34759253-9c5cc764-f600-11e7-8ff0-85101b99d0fc.png)

**Comment by OneiricIT** [comment]
Hi @rohitwaghchaure / @vishdha,
I have found it only appears in Sales Order when just created and not saved, and then when saving it disappears.

Also can you please confirm - the indicator also appears on non-stock items as orange. Should non-stock items really have an indicator, as it is misleading to end users who might think it is out of stock?

Frappe: 10.0.10
ERPNext: 10.0.9

![image](https://user-images.githubusercontent.com/22227933/35011669-1c4e32dc-fb5b-11e7-9865-33f618c651ca.png)
