### ISSUE TITLE
GUI Download Backup List not Populated

### ISSUE THREAD

**Issue by mafrica** [frappe/erpnext#12425]
I am running 9.2 from a Virtual Machine under Windows Server Essentials 2016 host.

I have generated a number of backups using “bench backup” which can be seen here: ...._sorry trouble pasting the image_

However they do not show on the GUI:

Note also that using the “Download Files Backup” button sends an email with only partial URL eg:

Hello, 
Please use following links to download file backup.
Public Files Backup: http://erpnext.vm/backups/20180109_115239-erpnext_vm-files.tar
Private Files Backup: http://erpnext.vm/backups/20180109_115239-erpnext_vm-private-files.tar

To implant the server domain name it is necessary to declare “host_name” in site_config.json . I do not think that this is covered in the installation documentation.

**Comment by mafrica** [comment]
Curiously the download list has now appeared but with the truncated URL...

eg /backups/20180109_134850-erpnext_vm-database.sql.gz

**Comment by umairsy** [comment]
Database files are not meant to be readable. If needed, you can restore it in the other ERPNExt account and make it use of it.

Closing this issue for now. For more support, feel free to raise your query on the discuss forum.
