### ISSUE TITLE
"Knowledge Base - Help Article" can't be hide to Purchase Users

### ISSUE THREAD

**Issue by franciscobuendiao** [frappe/erpnext#12432]
“Knowledge Base - Help Article” can’t be hide to Purchase Users.
Tested in three accounts.

![help 1](https://user-images.githubusercontent.com/25084259/34795380-c0b88334-f617-11e7-8a20-6882dadd8a72.jpg)

![help 2](https://user-images.githubusercontent.com/25084259/34795387-c8bc0204-f617-11e7-87ef-3fbd4b8dbe28.jpg)

![help 4](https://user-images.githubusercontent.com/25084259/34795404-d29e5e0c-f617-11e7-85f9-fbf662ee56fb.jpg)

![help 3](https://user-images.githubusercontent.com/25084259/34795417-dad5da46-f617-11e7-8166-587d7737c93a.jpg)

**Comment by umairsy** [comment]
Please check if User "Guest" has read permission on the Help Article.
