### ISSUE TITLE
Customize form - Current time (hh mm ss) support for naming_series

### ISSUE THREAD

**Issue by JrenzP** [frappe/erpnext#12438]
I currently have _SINV.YY.MM.DD.-.####_ for the naming series of my Sales Invoice. And it's perfectly fine as of now. But I want to somewhat encrypt the series by adding _hours minutes and seconds (hh mm ss)_ in it.

I spent a whole day searching for an answer to make this work:
_SINV.MM.-.YY.hh.DD.#.ss.mm_ .

I don't know about coding that much.
Any idea?

**Comment by JrenzP** [comment]
Anyone?

**Comment by tundebabzy** [comment]
You can't do this out of the box. You will need to code for this editing the `make_autoname` function in frappe. You can open an issue on the frappe repo to request for this. If you can't code it don't worry, someone will pick it up
