### ISSUE TITLE
Costing orders on imported products

### ISSUE THREAD

**Issue by lucalan66** [frappe/erpnext#12437]
We have a distributions and reselling company located in Colombia.

We buy products from suppliers on USD (usually), then, when the order arrive to Colombia we need to get the cost of each product having usd/cop rate, shipping fees, and taxes to get prices in COP.

We distribute porcentual all extra cost between all items depending of it's price in its original currency (this case USD). And that would be final item cost in COP.

**Comment by tundebabzy** [comment]
Use the Landed Cost Voucher
