### ISSUE TITLE
On Canadian Set Up, the French Chart of Accounts Template is applied as default

### ISSUE THREAD

**Issue by nateriches** [frappe/erpnext#12456]
Previous to version 10, this did not occur when setting up a Canadian Company + CAD as the base currency.

**Comment by nateriches** [comment]
I'm not sure if this is fixed now, but I did a fresh install and it seemed to have loaded correctly?

**Comment by nateriches** [comment]
No, it's not. Did another fresh install and it used the French set. Makes no sense?

**Comment by bdavidsonbgd** [comment]
I have the same issue. I ended up rolling back to a previous snapshot to set it back up under "United States" for Country, with Currency as "Canadian", and my local timezone. As they are "Root Accounts" there seems to be no other way to change the names...

**Comment by bdavidsonbgd** [comment]
It seems you can go to "Global Settings" to switch the "Country" back to Canada. I am only using this for very basic accounting, so this workaround works for me, but may not work for everyone, especially those in need of full accounting support.

**Comment by Nathaniel401** [comment]
I tried what @bdavidsonbgd did, however something seemingly deep internally didn't change, as when I define things such as Tax Purchase/Sale Templates it prompts for a USD-CAD FX rate when I set up with a U.S. focused install and then switch to Canada/CAD. I think the real only solution for those needing a deep accounting support would be to manually re-name/adjust all the account headings.

**Comment by nateriches** [comment]
Hi all, this still has not been fixed.

**Comment by clarkejj** [comment]
To install the Standard (English Canada) COA this worked for me - first remove the French COA from verified/

mv ./apps/erpnext/erpnext/accounts/doctype/account/chart_of_accounts/verified/ca_plan_comptable_pour_les_provinces_francophones.json ./apps/erpnext/erpnext/accounts/doctype/account/chart_of_accounts/unverified/ca_plan_comptable_pour_les_provinces_francophones.json

Then 'bench reinstall' that runs the setup wizard that installs the Standard English Canada COA.

Note that this creates a fresh database instance.

**Comment by vrms** [comment]
@clarkejj 

> To install the English Canada COA this worked for me - first remove the French COA from verified/
>
> `mv ./apps/erpnext/erpnext/accounts/doctype/account/chart_of_accounts/verified/ca_plan_comptable_pour_les_provinces_francophones.json ./apps/erpnext/erpnext/accounts/doctype/account/chart_of_accounts/unverified/ca_plan_comptable_pour_les_provinces_francophones.json`
>
> Then 'bench reinstall' that runs the setup wizard that installs the Standard English Canada COA

if I am not completely on the wrong end I'd expect that you can only setup the standard chart of accounts (which is in English) but bot any chart with a structure for Canada.

**Comment by kennethsequeira** [comment]
Closing the issue, as:

1. Under the new setup-wizard since v11, on the selection of country, one can choose the chart of account template. Earlier the CoA could not be chosen.

2. Since v12, [Chart of Account importer](https://docs.erpnext.com/docs/user/manual/en/setting-up/chart-of-accounts-importer) has been added so users can import their own chart within the system after setup.
