### ISSUE TITLE
Customized Print Format Not showing properley when Attach document print in email

### ISSUE THREAD

**Issue by mertberber** [frappe/erpnext#12455]
When I send email from a document lets say from Sales Invoice, The attach document print does not show the customized print format correctly due to extensive Customization scripts.

I can print PDF without any issues but when I send email by using Attach document print, the invoice does not show correctly in the email as an attachment which I also cc to myself to check it out.

**Comment by mainul94** [comment]
![attatch_pdf](https://user-images.githubusercontent.com/9250275/36262047-900874ca-1290-11e8-9114-2ebfd3a2ea6c.png)
![link_pdf](https://user-images.githubusercontent.com/9250275/36262048-90553864-1290-11e8-9a6d-fdf10bb4264b.png)

**Comment by ewqiop** [comment]
Fixed this for myself. To save someone some hassle check the html being passed to pdfkit.from_string and you will see that the url to bootstrap et al. is incorrect. It constructs the URL using site1.local as opposed to the domain. 

Performed the following to fix from frappe-bench directory: 
mv sites/site1.local sites/actual.domain
bench setup add-domain --site actual.domain actual.domain
bench setup nginx
sudo service nginx restart
bench restart

PDFs attached to email are now displayed correctly.

**Comment by clarkejj** [comment]
This email attachment issue occurs on v11 and python 3.5 but not on 2.7 https://discuss.erpnext.com/t/smtplib-smtpdataerror-501-bsyntax-error-line-too-long/46570/6
