### ISSUE TITLE
Attach Document Print option when sending e-mail should not be auto selected

### ISSUE THREAD

**Issue by mertberber** [frappe/erpnext#12454]
when I send an email to a customer from doc type lets say Sales Invoice, due to heavy customization the attached document print does not show the document correctly when sent by email, so I need to save the invoice as PDF first then I need to come back to that invoice and send out an email, when I do that the email form automatically selects Attach document print which I don't want in my case since I am already attaching the document due to the issues I mentioned above. So if I forget to uncheck the Attach document print option it will send 2 documents. I suggest this Attach document Print option needs to have a setting so if you prefer you can use this feature, if not then you should be able to turn off this feature so it will not come automatically selected when you create email from any kind of doctype.

**Comment by lasalesi** [comment]
There should be a global default setting (instance specific, e.g. in the System Settings) to define the default value for "attach_document_print"...
