### ISSUE TITLE
Stuck in "Sorry!  We will be back soon." message after system freeze.

### ISSUE THREAD

**Issue by JrenzP** [frappe/erpnext#12468]
I tried to install the "Shopify" app while I'm in the localhost:8080; then the system froze after I clicked the install and I had to restart my laptop.

After that, I opened the Virtual Machine and everything goes fine until I found out that I'm stuck at "Sorry! 
We will be back soon."
message.

What should I do?

![image](https://user-images.githubusercontent.com/30467646/34903849-ec4edeb2-f874-11e7-9c5d-0338b38aaa23.png)

**Comment by ankush** [comment]
The message is indication that migration isn't finished.

The app is deprecated now. Closing.

**Comment by JrenzP** [comment]
This is more than 3 years!
Glad you still answered though.

Thank you!

JrenzP

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by JrenzP** [comment]
This is more than 3 years!
Glad you still answered though. 

Thank you!

JrenzP

**Comment by saru2020** [comment]
for me, it got resolved after running `bench migrate` (though it failed)
