### ISSUE TITLE
Error making a sale on POS

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#12467]
Hello,

I'm having issues making a sales invoice on POS while testing developer branch, this is the error that prevents the creation of the invoice:

> Traceback (most recent call last):
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
>     response = frappe.handler.handle()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
>     data = execute_cmd(cmd)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
>     return frappe.call(method, **frappe.form_dict)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 939, in call
>     return fn(*args, **newargs)
>   File "/home/frappe/frappe-bench/apps/erpnext/erpnext/selling/page/point_of_sale/point_of_sale.py", line 99, in submit_invoice
>     doc.submit()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 831, in submit
>     self._submit()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 820, in _submit
>     self.save()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 256, in save
>     return self._save(*args, **kwargs)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 279, in _save
>     self.insert()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 218, in insert
>     self.run_before_save_methods()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 862, in run_before_save_methods
>     self.run_method("validate")
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 755, in run_method
>     out = Document.hook(fn)(self, *args, **kwargs)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1029, in composer
>     return composed(self, method, *args, **kwargs)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1014, in runner
>     add_to_return_value(self, f(self, method, *args, **kwargs))
>   File "/home/frappe/frappe-bench/apps/erpnext/erpnext/regional/india/utils.py", line 67, in set_place_of_supply
>     address = frappe.db.get_value("Address", address_name, ["gst_state", "gst_state_number"], as_dict=1)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 445, in get_value
>     order_by, cache=cache)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 489, in get_values
>     out = self._get_values_from_table(fields, filters, doctype, as_dict, debug, order_by, update)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 621, in _get_values_from_table
>     as_dict=as_dict, debug=debug, update=update)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 172, in sql
>     self._cursor.execute(query, values)
>   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 166, in execute
>     result = self._query(query)
>   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 322, in _query
>     conn.query(q)
>   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 856, in query
>     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
>   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1057, in _read_query_result
>     result.read()
>   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1340, in read
>     first_packet = self.connection._read_packet()
>   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1014, in _read_packet
>     packet.check_error()
>   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 393, in check_error
>     err.raise_mysql_exception(self._data)
>   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
>     raise errorclass(errno, errval)
> InternalError: (1054, u"Unknown column 'gst_state' in 'field list'")

**Comment by rohitwaghchaure** [comment]
@applepipe 

Seems regional issue, did you recently changed the country in your company?

**Comment by applepipe** [comment]
@rohitwaghchaure 

It started to happen after an update, no changes made on company or custom scripts

**Comment by rohitwaghchaure** [comment]
@applepipe 

Thanks for the details.
We've identified and [fixed](https://github.com/frappe/erpnext/pull/12481) the issue and soon we'll release it
