### ISSUE TITLE
Uploading different file with same name replaces the file

### ISSUE THREAD

**Issue by djpalshikar** [frappe/erpnext#12470]
Steps to reproduce:
* Attach a File with name "**file.pdf** " to an Item. 
* To another item attach a different file with the same name "**file.pdf**".
* The new **file.pdf** replaces the old file everywhere

**Comment by tundebabzy** [comment]
This is expected since the files are being uploaded to the same location. At the same time, each document with an attachment just contains a reference to the location of the file. 

However, I think it's a good idea that each document should have its own folder.

**Comment by djpalshikar** [comment]
Ideally if a same name exists, the system should create a new name for the file. e.g. file-1.pdf

**Comment by saurabh6790** [comment]
@djpalshikar  If file hash is different then the system creates two different records. As per me, if file hash is same then no need to keep separate versions.

**Comment by djpalshikar** [comment]
@saurabh6790 this is expected behaviour. But it is not what is happening. The system is replacing the files even they have different content.

**Comment by djpalshikar** [comment]
@saurabh6790 I think I now see why this is happening. Strangely in case of some files the, I have found empty ContentHash, after upload.
![screenshot-2018-1-23 fuel-level-transmitter pdf - ff8aea2f79](https://user-images.githubusercontent.com/23133635/35284853-def7bed6-0081-11e8-808b-94b01da18bfe.png)

**Comment by saurabh6790** [comment]
Seems an issue! Will check this.

**Comment by realvinay** [comment]
We are facing the same issue.

**Comment by realvinay** [comment]
We have been able to pin this down to socket io, this issue happens when files are uploaded through socket io, if socket io fails and falls back to http POST hashes and file sizes are always recorded, and this issue never happens.

If we stop socket IO service, this issue doesn't occur.

**Comment by shridarpatil** [comment]
@realvinay I am working on this will send a PR.
