### ISSUE TITLE
Improved Financial Reporting in ERPNext

### ISSUE THREAD

**Issue by olamide2** [frappe/erpnext#12477]
There is a need to make the financial/Accounting  reporting in ERPNext more flexible and in line with basic financial standards.

The following are the issues I can identify with the current set up

1. The Profit and Loss account is not in line with standards. For example one cannot determine the gross margin by simply looking at the P&L, you have to export to excel and deduct direct costs from sales manually. This is cumbersome and needs to be corrected.

At a glance reader should be able to see Gross profit and Net Profit as well as Total Expenses for each period

2. The Balance sheet arrangement of assets/liabilities is not in the order of liquidity, this is one of the requirements of accounting standards

3. We need to be able to filter for financial statements according to any period we need. For example if I need the P&L for November 2017, I should be able to filter for just this month. The current approach requires scrolling right and left to get the month I want and by the time I get to November I cannot see the column that has the relevant GLs, all I see is numbers without knowing what the numbers represent unless I export to excel. We should also be able to generate P&L for any specific period (week or even day) by simply picking a start and end date.

**I believe request 3 is self explanatory enough**

It will be awesome if this issues can be addressed cause as it stands the financial statement reporting in ERPNext is almost un-useable.

Regards

**Comment by giuseppelamatrice** [comment]
+1

**Comment by ushashmi** [comment]
+1

**Comment by dhav-d** [comment]
+1

**Comment by Eddiy** [comment]
+1

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.
