### ISSUE TITLE
[BUG] python install.py --production throwing error

### ISSUE THREAD

**Issue by skarthik3** [frappe/erpnext#12471]
TASK [Create new site] *********************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["bench", "new-site", "site1.local", "--admin-password", "123458", "--mariadb-root-password", "123456"], "delta": "0:00:01.784200", "end": "2018-01-13 23:47:05.648048", "failed": true, "rc": 1, "start": "2018-01-13 23:47:03.863848", "stderr": "ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)", "stderr_lines": ["ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)"], "stdout": "Database not installed, this can due to lack of permission, or that the database name exists.\nCheck your mysql root password, or use --force to reinstall", "stdout_lines": ["Database not installed, this can due to lack of permission, or that the database name exists.", "Check your mysql root password, or use --force to reinstall"]}
	to retry, use: --limit @/tmp/.bench/playbooks/production/install.retry

PLAY RECAP *********************************************************************
localhost                  : ok=71   changed=42   unreachable=0    failed=1

**Comment by tundebabzy** [comment]
Hint:
> Database not installed, this can due to lack of permission, or that the database name exists.\nCheck your mysql root password, or use --force to reinstall

**Comment by nateriches** [comment]
Jumping in here; @tundebabzy I had the same issue as the OP, and had done these installs for almost 1.5 years on fresh instances, never had this issue before. I was able to resolve it, but something had to have changed in the install script and/or the third party providers the script calls upon to install the required components.

**Comment by skarthik3** [comment]
Hi tunedebabzy 

Thank you for your quick reply. 

I know I did a manual install and it is working but something changed in the install script i was not able to pin point exactly the problem in the install script that is why I raised the issue I will try and pinpoint the issue in the install script.

Thank you.

**Comment by georgeappiah** [comment]
@nateriches, I'm having this issue as well. Would you mind sharing what changes you did to get the installation to work?

Thanks.

**Comment by osstechnolab** [comment]
We are also having this error. Any idea on how to install?

**Comment by skarthik3** [comment]
Hi 

What i did was i compared manual installation notes with install.py file which can be opened using text pad and ran all the commands manually by logging in as root

**Comment by umairsy** [comment]
Please post technical queries on the community forum.

https://discuss.erpnext.com
