### ISSUE TITLE
Sales Invoice: Customer is required against Receivable account 

### ISSUE THREAD

**Issue by ekpott** [frappe/erpnext#12473]
I keep getting error when creating a sales invoice even if all the details have been correctly filled

![image](https://user-images.githubusercontent.com/7124097/34913371-fe681b3c-f8fa-11e7-893d-61623296aa2c.png)

**Comment by tundebabzy** [comment]
Hi @ekpott 
The invoice is trying to post to Sales account. It seems you have set the `Account Type` field of Sales Account to 'Receivables' in your chart of account. Set the Account Type field to blank and that will fix it.
