### ISSUE TITLE
Feature Request - How to create and schedule popup alerts for reminders?

### ISSUE THREAD

**Issue by raghukovvuru** [frappe/erpnext#12485]
Hello all,
In our ERPNext system, is there any way to create a popup reminder alerts that can be set according to our requirements?

Use Case: We generally file tenders for projects, we created a custom doctype named Tender with all the necessary fields. For this we need popup alerting system which alerts the users 4-5 days before the tendering date.

For example: Tender last date is 15-01-2018 and we set alerts on 10-01-2018, which should be shown as a popup alert.

Searched this forum for this but we couldn’t get the desired results.

**Comment by joolsr** [comment]
In V10 you can use a calendar view for any defined doc type. Here you can set a reminder which will send an email  at midnight of the day of the event

**Comment by saurabh-bhosale** [comment]
@raghubuilds On extending to what @joolsr said, calendar reminder is the way to go and if that doesn't match your requirements, and you still wish to have popup reminders then you can explore the Note doctype. 

You will have to automate the creation of a note which has the provisions that might be helpful for you. I've also shared a gif to show the same. This note creation can be done 5 days prior to tendering date(with the required checks and notification expiry date) in the daily scheduler calls of your ERPNext app. Hope this helps.


![issue_solution](https://user-images.githubusercontent.com/25682214/35036781-6b6c9fbc-fb9b-11e7-948d-9eeef6bddd54.gif)

**Comment by Topiya** [comment]
@raghukovvuru Did you get any solution regarding the same? I am looking for a same functionality.
