### ISSUE TITLE
Permission Error after logging in on beta.erpnext.com

### ISSUE THREAD

**Issue by nabinhait** [frappe/erpnext#12486]
<img width="1185" alt="screen shot 2018-01-15 at 1 56 29 pm" src="https://user-images.githubusercontent.com/836784/34933242-159cb5cc-f9fc-11e7-808b-27ace883badd.png">

**Comment by achillesrasquinha** [comment]
This issue made me fix everything that frappe has faults with. Right from redis overflow to supervisor failures.

**Comment by achillesrasquinha** [comment]
I've never been so frustrated to fix on any issue.
