### ISSUE TITLE
Primary contact can not be unlinked from customer

### ISSUE THREAD

**Issue by chdecultot** [frappe/erpnext#12489]
Hi,

With the new "Primary contact" structure, we can't unlink a primary contact from a customer without replacing it:

(Here I tried to remove the primary contact and save)
![image](https://user-images.githubusercontent.com/4903591/34935920-d69fef4a-f9df-11e7-80c8-f48d6ab5a5b7.png)

It prevents us from deleting the contact and also from deleting the customer from the system.
It makes sense to enforce at least one primary contact for each customer, but we should be able to delete customers from the system if needed.

**Comment by joolsr** [comment]
I managed to replicate this when using Leads rather than Customers on v10
