### ISSUE TITLE
Data Import/Update Utility

### ISSUE THREAD

**Issue by epochc** [frappe/erpnext#12493]
While updating new records:

Not working with CSV file. The Specific Error is in the attachment.

![image](https://user-images.githubusercontent.com/18049961/34942063-40c5e3fc-fa1c-11e7-8d1a-e5febbf6647a.png)

New records are getting imported with the Excel file. However, when you are trying to update records both Excel and CSV are failing.

Here's the error on CSV:

![image](https://user-images.githubusercontent.com/18049961/34942420-97827088-fa1d-11e7-8419-89734e5bbac1.png)

and here's the error on Excel:

![image](https://user-images.githubusercontent.com/18049961/34942484-e27343d8-fa1d-11e7-874b-3ab502b510d4.png)

This error is repeating for all different templates I tried - Serial Number, Item, etc.

Thanks

Jay

**Comment by manassolanki** [comment]
Hi @epochc 
Please reopen if the issue still persist
