### ISSUE TITLE
Link to Product Page gives 404

### ISSUE THREAD

**Issue by MichaelPinkowski** [frappe/erpnext#12497]
I hope I am doing this correctly...  On my hosted (cloud) version of ERPnext, there is a button/link on the home page that says "View All Products".  Clicking on it in Version 9 would take me to a page that showed all products.  Clicking on it now gives a 404 error.

**Comment by jaichavan** [comment]
Probably the route for the button, "View All Products" wasn't set correctly in your account at that time. There shouldn't be any other reason for this issue to occur. In the current version, when "View All Products" is clicked, it takes the user to the "/products" which has been defined appropriately in Website module.
Hope this _helps_ thanks for reporting the issue!
