### ISSUE TITLE
When deleting a custom field, the "Insert After" field of other fields referring to deleted field does not get updated.

### ISSUE THREAD

**Issue by jevonearth** [frappe/erpnext#1249]
To reproduce, 
Create a new custom filed called A
Create a new custom field called B and set the "Insert After" drop down to A.
Verify that both fields appear on the form.
Delete field A
See that A does not appear on the form (it was just deleted)
See that B does not appear on the form (it should display where A used to be).

**Comment by rmehta** [comment]
This issue is redundant with the new update (where standard fields are not movable)
