### ISSUE TITLE
Batch Autoname by Chosen Naming Series

### ISSUE THREAD

**Issue by mtlapointe** [frappe/erpnext#12502]
Hello,
In response to a request I originally made (#12302), Batch was recently updated to have the option to use a Naming Series instead of the default hash (see #12461). This change allows use of a single Naming Series prefix set in the Stock Settings. 

However, in my original ticket, I suggested allowing the option for multiple Naming Series options to be used. For my particular case, I would want the user to select from several Naming Series options and then autoname the Batch according to that selection, rather than just one fixed prefix. It seems like this would be more inline with the default Frappe doctype behavior. 

I hope that makes sense... please let me know if there is any confusion.

**Comment by tundebabzy** [comment]
This won't be easy because this functionality is not available out of the box. Presently, naming series can only be maintained for 1 prefix say 'PREFIX-' per doctype.

Would you be willing to fund this?

**Comment by mtlapointe** [comment]
Hi Tundlebabzy,
I was able to add this functionality to Purchase Order DocType.  I simply went to Setup > Naming Series, and then added more options to the Purchase Order transaction type. Is that not the default behavior? I can try to experiment with the code by getting rid of the autoname method in Batch to see what happens.
