### ISSUE TITLE
Can't delete tag assigned to an Item

### ISSUE THREAD

**Issue by nimaeis** [frappe/erpnext#12501]
Clicking on the "x" next to the tag for an Item does not delete it (checked in Chrome and Microsoft Edge).

**Comment by davidrheinbay** [comment]
Having the same problem - @nimaeis did you solve it?

**Comment by parsimonyERP** [comment]
We created the tag "19' Sumit" on a customer record and realized that we had misspelled "summit".  When we click on the "X" to delete the tag, we get no action and there is nothing recorded in the console.  I have seen this addressed in earlier messages and closed as Solved.  But I haven't seen it addressed in v11.

I feel fairly certain that it is the apostrophe that is causing the issue.

ERPNext: v11.1.4 (master)
Frappe Framework: v11.1.4 (master)
