### ISSUE TITLE
Duplicate make 'Packing Slip' in Delivery Note

### ISSUE THREAD

**Issue by OneiricIT** [frappe/erpnext#12508]
On current v10 Frappe and ERPNext, but test also performed on demo.erpnext.com

From Sales Order, create Delivery Note. 

After saved, proceeding to create Packing slip from 'Make' button produces duplicate entries. I have also seen duplicate entries if there are more options on the buttons.

![image](https://user-images.githubusercontent.com/22227933/34981951-2ea573a4-fafd-11e7-86ee-eb2672f3aa0a.png)

**Comment by tundebabzy** [comment]
@OneiricIT 
are you on version 10.0.10?

**Comment by OneiricIT** [comment]
Hi @tundebabzy, thanks for quick response.

Sorry on ERPNext: v10.0.7 for two separate servers, demo on ERPNext: v9.x.x-develop (4b0dd8a) (develop)

**Comment by OneiricIT** [comment]
@tundebabzy just updated dev server (on master branch) to ERPNext: v10.0.0.9 and Frappe: v10.0.0.10 - same issue.

**Comment by tundebabzy** [comment]
Fixed in #4858

**Comment by OneiricIT** [comment]
Thanks @tundebabzy
