### ISSUE TITLE
Delivery Note: Filter showing 'row' entries of items instead of just Delivery Note

### ISSUE THREAD

**Issue by OneiricIT** [frappe/erpnext#12509]
Frappe: 10.0.10
ERPNext: 10.0.9

When filtering in Delivery note against "Against Sales Order" (which is default filter set when in Sales order and selecting related Delivery Note link) the results show row entries based on the items in the Delivery Note. See gif below as example.

![2018-01-16_20-53-43](https://user-images.githubusercontent.com/22227933/34982962-16d44e0a-fb00-11e7-9ad1-ca1d227c20bf.gif)

**Comment by sp9leo** [comment]
Same happens when you open timesheets from project doctype. It displays individual timesheet rows.

**Comment by tundebabzy** [comment]
Hi. This is fixed by frappe/frappe#4763.
