### ISSUE TITLE
Item - Stock Entry creation permission

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#12512]
In the Item master, there is open to add stock in the Warehouse. If user is not given permission on the creation of Stock Entry, then option to add stock in the Warehouse should not work. Currently, it does show the pop-up to enter details and then shows the error message.

![paste_1516043588](https://user-images.githubusercontent.com/910238/34987365-e86500d8-fae0-11e7-888e-cf26983d2df0.png)

**Comment by Jacksoneasyway** [comment]
Hi: Umair

This is Jackson
still waiting for your suggestion on above issue
How could we restrict the window of 'add' show up.

**Comment by Jacksoneasyway** [comment]
for the user where i did the screen shot, I didn't even give him the permission on the stock entry document.
please support to solve this last problem, before we go-ahead for subscription.

looking forward to your comment.

**Comment by Jacksoneasyway** [comment]
Hi: Guys
I really don't understand how are you Guys supporting your USER, 

No body give a word for this matter? 

what happens if we have some problem during the work after we pay?

**Comment by tundebabzy** [comment]
Hi @Jacksoneasyway 
This will be fixed ASAP

**Comment by tundebabzy** [comment]
#12642
