### ISSUE TITLE
Junior Accountant role and access

### ISSUE THREAD

**Issue by TetraComSA** [frappe/erpnext#12523]
Hello,

We hired new junior accountant and we want him to have access on all transactions but with the following limits:

No GL report to read or view.
No access to see transactions posted by other users.
No access on any financial statement.
Would you please help me out…!!

Regards
Yahya

**Comment by tundebabzy** [comment]
Hi @TetraComSA 
Let's discuss this on the forum (https://discuss.erpnext.com)
