### ISSUE TITLE
Add Fields at Assessment Result Tool

### ISSUE THREAD

**Issue by esamcrouz** [frappe/erpnext#12526]
i have added the following fields at assessment result tool , 
- Assessment Name
- Assessment Group
- Parent Assessment Group
But when submitting the results , these fields didn't migrated to the assessment result .
Can any one help ?

**Comment by manassolanki** [comment]
Hi @esamcrouz 
Please create a post on discuss.erpnext.com for help. (with school tag added). More people can help you there.
