### ISSUE TITLE
New Feature: Sales Invoice - Discount Amount - Cost Center

### ISSUE THREAD

**Issue by dhav-d** [frappe/erpnext#12527]
If we could have the value of discount linked up to a cost center for each invoice, the users can allocate the value to a cost center for that "Promotional" discount value offered/provided for.

I think this a very small tweak and a lot of value for users utilizing cost centers optimally.

**Comment by vladucoju** [comment]
This is also a big step for create right trading book.that option is now available from warehouse GL, but changing price value register and maintaining as a cost is very important. Thanks for suggestion dhav-d.
