### ISSUE TITLE
Add functionality to allow file upload resuming

### ISSUE THREAD

**Issue by Tropicalrambler** [frappe/erpnext#12528]
When user is uploading a large file, it might get disconnected due to network issues, separate from ERPNext and Frappe functioning.  Similar to a download manager like GetRight or Folx, an upload resuming feature would allow the session to be interrupted abruptly, and the partial file stored on ERPNext server.  Once user has the ability to resume his or her download, he initiates it again as a "new" download, and ERPNext, through file metadata gathered in the first attempt, detects it is the same file and simply resumes the upload where it got disconnected.  I think this would allow users in remote areas or whose internet plan is costly, to save from re-sending data.

**Comment by palashjhabak** [comment]
I am new to erpnext. I thought contributing (of course with contributing guidelines in mind) could be a good way to understand the product better and this requested feature in my opinion will really be useful if implemented. 

Can someone give me some pointers about how to approach it ? Or if anyone else is interested in working for this feature together, that would be really nice too. 

Thanks,
Palash
