### ISSUE TITLE
[sponsor] Select Price List at Item Level

### ISSUE THREAD

**Issue by skarthik3** [frappe/erpnext#12536]
Hi 

I know item price lets me maintain multiple buying and selling prices but I am not able to select multiple of them during invoicing

Example Lets say there are two products A and B 

A has three price lists P1,P2 and standard price
B has two price lists P1 and standard

When I am invoicing in sales invoice(pos) both product A and B if I select P2 price list  because that is the price I want to charge for product B the price of A will not populate since there is no P1 price list associated with it.

Can a system be designed such that we are able to choose the price list at each item line level so each item can be populated at its respective prices

Leave the default price list empty so when are invoicing we have to choose a price list for the rate to populate this will help us to identify if more than one price list exists for the product when we press the drop down button.

**Comment by OnlyC** [comment]
Did you solve this @skarthik3 ?
I'm facing the same.

**Comment by Chintan1812** [comment]
Hello,
Is this feature been worked on? If selecting price list at item level was possible, it would solve a very huge problem of ours and many others.
