### ISSUE TITLE
[BUG] price list still populating after deleting the item

### ISSUE THREAD

**Issue by skarthik3** [frappe/erpnext#12538]
price still populating in sales invoice after deleting the item please find the below screen shots 
<img width="957" alt="upload" src="https://user-images.githubusercontent.com/35178177/35096528-85c2e40c-fc72-11e7-8091-c63112451b8d.png">

**Comment by umairsy** [comment]
Please post this issue on the community forum first. Indicate the steps, so that I can reply replicating in my test instance as well.

https://discuss.erpnext.com

If validated as a bug, we can reopen this issue.
