### ISSUE TITLE
Draft Status in print format

### ISSUE THREAD

**Issue by MANOJMAINKAR** [frappe/erpnext#12548]
It is observed that for customize print format we use to get document status as ‘Draft’ in actual printouts for draft documents. Now it is not appearing even if in print setting , checked - Always add “Draft” Heading for printing draft documents.

For last so many years it was working , we are facing the same issue from last few months , may be due to changes /updates in package .

**Comment by umairsy** [comment]
Draft (text) is showing just fine in your print formats!??

![screen shot 2018-02-14 at 11 40 28 am](https://user-images.githubusercontent.com/910238/36190057-f48722cc-117b-11e8-93e9-27c813071832.png)

**Comment by MANOJMAINKAR** [comment]
Check for customize print format like Purchase Order GST for which it
was working fine till last month 

On 14-02-2018 11:41 AM, Umair Sayed wrote:

> Draft (text) is showing just fine in your print formats!?? 
> 
> [1] 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].
 

Links:
------
[1]
https://user-images.githubusercontent.com/910238/36190057-f48722cc-117b-11e8-93e9-27c813071832.png
[2]
https://github.com/frappe/erpnext/issues/12548#issuecomment-365506640
[3]
