### ISSUE TITLE
Has Batch No. and Serial No. field should not be set only once

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#12542]
As per the recent update, fields Has Batch No. and Serial No. should not be Allow on Submit. As earlier, it will helpful if changing value in these fields is allowed till Stock Ledger Entry is not created for them. 

Use-case:

1. When placing an order for the item, user is not sure if supplier will send that item with serial no.

2. Has Batch No. and Serial No. fields are not visible in the quick entry view, hence user doesn't have scope to enter value in these fields, if created from quick entry itself.

**Comment by djpalshikar** [comment]
I think there is merit in considering allowing to edit Has Batch No. and Has Serial No. even after Stock Entries. 
If in future if we want to enable Batch No. and Serial No. for our Manufactured Items the workaround is very lengthy - 

> 
    Duplicate the items and make the original item inactive.
    Rename the old item, so that the same name can be used for future transactions.
    Create new BOMs wherever the old item is being used
    Use BOM update tool to replace the all the Old BOMs

https://discuss.erpnext.com/t/enabling-batch-numbers-after-making-stock-entries/31887/3?u=dhananjay

**Comment by somicoito** [comment]
@djpalshikar I also would like to be able to allow on submit "has serial number", we often need to do this change...
