### ISSUE TITLE
Misalignment standard filter if filter contains multiple rows of fields

### ISSUE THREAD

**Issue by basdereus84** [frappe/erpnext#12555]
When the standard filter in list view has more fields and therefore needs multiple rows to display, the rows are not aligned properly (margin-left).

![image](https://user-images.githubusercontent.com/28436537/35142791-b2664c82-fcff-11e7-842b-c811a203bb65.png)

**Comment by netchampfaris** [comment]
We should not allow more than 4 Standard Filters in ListViews
