### ISSUE TITLE
There is no Kanban view for an existing Project, with existing Tasks

### ISSUE THREAD

**Issue by ronniegarcia** [frappe/erpnext#12560]
Hello,

ERPNext: v10.0.7 (master)
Frappe Framework: v10.0.8 (master)

I have an existing Project, with existing Tasks within it.
I would like to display the Kanban view for the Tasks.
The Kanban link in the left menu doesn't show my Project name, there is only a link to "New Kanban"
If I try to create a New Kanban with the same name as my existing Project, it says that the Project already exists. If I use another name, it creates a new Project.

I tryed to refresh my browser, as there are some display bugs with this, with no success.

What is the way to display a Kanban view for an existing Project with Tasks ?

![capture d ecran 2018-01-19 a 12 27 16](https://user-images.githubusercontent.com/954986/35149573-ea3a287e-fd16-11e7-854f-be0201e3e36f.png)
![capture d ecran 2018-01-19 a 12 27 41](https://user-images.githubusercontent.com/954986/35149576-eca3ad10-fd16-11e7-9823-8adc5d11c756.png)

Thanks
Ronnie

**Comment by netchampfaris** [comment]
Kanban works with tasks not Projects. If you want all the tasks in a Project in a Kanban Board, then create a Kanban Board for tasks. Then use the filters to set the Project. Now that Kanban Board will show tasks of that Project.

**Comment by netchampfaris** [comment]
@ronniegarcia 

Hey, I added a Kanban Board button in the Project form. Now it will take you to the Kanban Board where the tasks of this project will be listed.

![image](https://user-images.githubusercontent.com/9355208/37653207-0fe7e17a-2c64-11e8-804c-8cd75d707378.png)
