### ISSUE TITLE
cannot save INVOICE- 

### ISSUE THREAD

**Issue by hussains52** [frappe/erpnext#12579]
HELLO
I JUST SIGNED UP FOR FREE TRIAL VERSION AND CREATED A TEST CUSTOMER AND ADDED TWO ITEMS

BUT I CANNOT SAVE MY FIRST SALES INVOICE.

CAN YOU CHECK THE REASON FOR https://fakhree.erpnext.com.

**Comment by kennethsequeira** [comment]
@hussains52 can you give the steps to reproduce this?

Also, what is the message you get when trying to save an invoice? Can you attach screenshots/gif for the same? It will help us to narrow down the problem

**Comment by tundebabzy** [comment]
closing this as there's no movement. Reopen with requested information.
