### ISSUE TITLE
Material request UOM is not automatically fetched from the Production Order

### ISSUE THREAD

**Issue by andiyan1** [frappe/erpnext#12571]
When we make material request from production order, we can fetch the material request item child fields but the UOM Conversion Factor fields are not automatically fetched.

So we will have to edit all the UOM from every each item we fetch

![screen shot 2018-01-19 at 15 28 33](https://user-images.githubusercontent.com/7466361/35181946-f88077d4-fdfd-11e7-8eb4-46dd99b87715.png)

**Comment by shreyashah115** [comment]
Fixed via #12567
