### ISSUE TITLE
If Cost Center is group then filter doesn’t work

### ISSUE THREAD

**Issue by giuseppelamatrice** [frappe/erpnext#12575]
**Cost Center Tree**
![presentazione senza titolo 0](https://user-images.githubusercontent.com/4445879/35183182-28a8633e-fde2-11e7-92a0-50160f9c775c.jpg)

**Create Purchase Invoice 1 and link to cost center**
![presentazione senza titolo 1](https://user-images.githubusercontent.com/4445879/35183183-28c91386-fde2-11e7-9db5-0f888c654165.jpg)

**Create Purchase Invoice 2 and link to cost center**
![presentazione senza titolo 2](https://user-images.githubusercontent.com/4445879/35183184-28e7f8dc-fde2-11e7-9ba8-a2c6ed68c45f.jpg)

**Create Purchase Invoice 3 and link to cost center**
![presentazione senza titolo 3](https://user-images.githubusercontent.com/4445879/35183185-29053438-fde2-11e7-85d3-2479e444b4bc.jpg)

**Purchase Invoice Report**
![presentazione senza titolo 4](https://user-images.githubusercontent.com/4445879/35183186-29250e5c-fde2-11e7-82f1-a5cbf5288ae8.jpg)

**Apply Filter on Cost Center child**
![presentazione senza titolo 5](https://user-images.githubusercontent.com/4445879/35183187-29429bb6-fde2-11e7-9fff-a7a5999c0b24.jpg)

**Apply Filter on Cost Center Group**
![presentazione senza titolo 6](https://user-images.githubusercontent.com/4445879/35183188-2968c746-fde2-11e7-9413-de6efc261933.jpg)

**Comment by ushashmi** [comment]
If you change your filter a little bit and instead of "equal" put "like". The system will bring u all the PIs where cost center has building word

At the same time I agree with you that parent filter should also work

**Comment by giuseppelamatrice** [comment]
**Filter "like%" doesn't work.**

![presentazione senza titolo 7](https://user-images.githubusercontent.com/4445879/35198565-f6ea7d0e-fef0-11e7-8c25-d8672925261b.jpg)

**Comment by ushashmi** [comment]
While testing the filters in new version i discovered that if you edit/change the existing filter by clicking on that filter, the system dont edit the same filter it adds one more filter and also keeps the old filter. 

Everytime you change the existing filter system keeps adding the new filter and also keeping the old filters.

**Comment by giuseppelamatrice** [comment]
I think that the fastest way is create a Query Report by SQL.

**Comment by umairsy** [comment]
Thanks for elaborating your query. Not only for the cost center, but this could be enhanced for all the tree masters in the ERPNext. Let's continue discussion on this via https://github.com/frappe/erpnext/issues/11055 issue.
