### ISSUE TITLE
Product Bundles not correct in Packing Slip

### ISSUE THREAD

**Issue by OneiricIT** [frappe/erpnext#12586]
ERPNext: v10.0.9 (master)
Frappe Framework: v10.0.10 (master)

When creating a Packing Slip against a Delivery Note which has a Product Bundle item, the Packing Slip pulls the Product Bundle in as is without actually replacing it with the items making up the Product Bundle. Example screenshots below. 

Further, if the Delivery Note has only a Product Bundle, the packing Slip cannot even be saved as the item by design is a non-stock item.

![image](https://user-images.githubusercontent.com/22227933/35208547-25e31902-ff9d-11e7-95c3-c903d51c9e63.png)

![image](https://user-images.githubusercontent.com/22227933/35208602-5a2ee24a-ff9d-11e7-95a6-f0915d10e775.png)

**Comment by umairsy** [comment]
The product Bundle item itself is a non-stock item, but only bundled items are the stock items, hence only they should be packed.

Please elaborate your use-case where you also need the non-stock product bundle items in the Packing Slip.

**Comment by OneiricIT** [comment]
Precisely, however the packing slip is not displaying the bundled items (stock items), it only shows the bundles item (non stock item).

**Comment by OneiricIT** [comment]
@umairsy further see below screenshots from demo.erpnext.com

Product Bundle created using Autocad item.

![image](https://user-images.githubusercontent.com/22227933/35250415-92d45db8-002a-11e8-9063-6a0286aacc34.png)

Delivery Note created with Product Bundle Autocad.

![image](https://user-images.githubusercontent.com/22227933/35250425-a361b662-002a-11e8-8a7b-0dff68475939.png)

Packing slip then created from Delivery Note - only brings over the autocad product which is incorrect.

![image](https://user-images.githubusercontent.com/22227933/35250462-d860b0ac-002a-11e8-97df-6f321f306e18.png)

**Comment by yadavyk** [comment]
(https://github.com/frappe/erpnext/pull/26105)
