### ISSUE TITLE
Currency Exchange Rate GBP->GBP=1

### ISSUE THREAD

**Issue by binary64** [frappe/erpnext#12597]
![image](https://user-images.githubusercontent.com/1680627/35211456-6d2b202e-ff4e-11e7-9c50-eaadda7b951a.png)
When I create new Invoice, I see the above problem. I don't want to have to enter '1' every time. Can it not detect that the From and To currency is the same, and hide all those fields?

**Comment by kennethsequeira** [comment]
Unless the price list currency and selling currency are different, you need not be setting that field. The exchange rate is automatically set to 1 and is read-only. 

What version of ERPNext and Frappe are you using?

**Comment by tundebabzy** [comment]
@binary64 This issue seems to have stopped. My Sales Orders are now fetching the exchange rate as expected. Run `bench update` and report back if it still persists.

**Comment by binary64** [comment]
Fantastic! It fixed it.

Just a tiny side issue is when I click Sales Invoice > New > back > New > back > New .. each time, the "New Sales Invoice 5" .. the 5 keeps incrementing (Even though nothing was saved).. From memory this didn't happen before.. although i might be mistaken

**Comment by tundebabzy** [comment]
It has been that way for long :-). Has to do with automatic naming of documents especially when trying to go back to a document that doesn't already have a name. Glad the issue has disappeared.
