### ISSUE TITLE
Deleting 500 error logs takes too long (imho)

### ISSUE THREAD

**Issue by binary64** [frappe/erpnext#12593]
In Error Logs > show 500 rows > select all > delete ... takes about 1.5 minutes

I like how the progress bar seems to show progress per every single delete.

But I would prefer to see it do a `DELETE FROM table WHERE IN (1,2,3,4...,500)` (all in 1 hit)

**Comment by achillesrasquinha** [comment]
`frappe.delete_doc` is more than just about Deleting Items, it considers a lot more (Permissions, Cleanups, etc.). 

What is true is that this can be profiled to be optimised.

**Comment by rmehta** [comment]
@binary64 on the Error Log list view. Go to "Menu > Clear Error Logs" - just runs a delete 😉

**Comment by binary64** [comment]
Wow! "Clear Error Logs" took approx 0.000001 secs to delete them all.

But surely this is still a "bug", since there is 2 ways to do things, 1 is super fast, 1 is super slow. It seems a bit cruel to keep the user waiting 1 minute for the slow version
