### ISSUE TITLE
Cost-Center (Dimensional) Trial Balance and Other Financial Reports

### ISSUE THREAD

**Issue by jk2081** [frappe/erpnext#12596]
This is in continuation to related issue of improved financial reporting and has been discussed extensively as part of the Accounting module group discussions. Essentially, we would like to be able generate cost-center/geography/customer (all being part of a set of so-called dimensions) wise trial balance and other financial reports.

Currently Sage Intacct does this through dimensional reporting. A video explaining the use case is here:
https://www.youtube.com/watch?v=6JwlGdysQBE&feature=youtu.be

I think we are well on our way on there with the cost-center field being part of the GL. Perhaps a good first step would be to make cost-center tagging a must for all GL entries in a system-wide setting and use that to generate the reports. This can be then extended to other popular dimensions.

**Comment by jk2081** [comment]
Some information on how Quickbooks does this based on work from Liyakat from the accounting team.

##Definition of what information we would like to track. 
I Suggest start with cost-center on line-item level.

![screen shot 2018-01-23 at 7 47 55 pm](https://user-images.githubusercontent.com/608306/35280614-b76ea042-0076-11e8-845e-63cf15852514.png)

##On the Doctype, how it would show up

![screen shot 2018-01-23 at 7 48 36 pm](https://user-images.githubusercontent.com/608306/35280660-dc5118fe-0076-11e8-8280-d7b21742b95d.png)

![screen shot 2018-01-23 at 7 48 47 pm](https://user-images.githubusercontent.com/608306/35280688-ef1f96cc-0076-11e8-9dec-598914bb78e8.png)

##On How it would enable different Reports

![screen shot 2018-01-23 at 7 48 56 pm](https://user-images.githubusercontent.com/608306/35280714-033de1e0-0077-11e8-8d36-9ce469dce2e0.png)

**Comment by jk2081** [comment]
On further discussion, it seems like the major gating factor is the current lack of tagging of cost center/warehouse on Balance Sheet items such as Debtors, Creditors, Employee Loans, Advances, Stock etc


One suggested approach to remedy this is to have a cost-center master wherein cost-center specific sub-ledgers can be selected as the default accounts for that cost center and users can be restricted by cost center or select a cost center at login time so that all transactions are tagged accordingly.

That way these reports would be possible. 

Please do note that inventory related balance sheet items such as stock details can be queried from the warehouses/stock ledger.

**Comment by PawanMeh** [comment]
I think from an accounting standpoint, balance sheet transactions generally do not have attributes like cost center etc. they are more needed on P&L side for operational purposes. 

I am not sure if this requirement is only about adding cost center filters on certain reports where it is not present or it is to add these to balance sheet account transactions.

**Comment by vladucoju** [comment]
Erpnext is a unique model. We should use some features from other erp solutions as a example, not to copy everything. I think we must talk about generic features. To fix main problems. I will mention some:

- discount as a cost on general ledger.

- discount in sales reports

- item price change register (system to create record when there is stock on item and price change is created. This should be a cost and should  be visible  in gl too.)
This are generic problem and we should fix this. I have posts many questions about problem like this but no one is anwering?
-

**Comment by ushashmi** [comment]
Instead of restricting only to cost centers can we look in to incorporating Analysis Codes (T codes) like Infor Sun Financials? Without any restriction of being applied to any document type and General Ledger Account Codes including Balance Sheet and P&L.

**Comment by sanjay-hercules** [comment]
We are planning to implement Business Unit (Branch) functionality which will facilitate branch-wise accounting by using single chart of account. User would be able to select default bank, warehouse accounts and letterhead at BU level.

BU can be created under Division and Territory (Location/Region). All financial reports will have filter of BU/Division/Location.

We will share design document shortly for review.

**Comment by kossanah** [comment]
This is a great news.
It will be helpful to make easy to track branch-wise expenses, allocate a branch petty cash.

**Comment by PawanMeh** [comment]
Company tree maybe a better way to go in this case as business units are equivalent to company in ERPNext.  You have cost center and department too that you can use as other dimensions.

**Comment by sanjay-hercules** [comment]
Yes Pawan, BU will be having tree structure like Company >> Region >> Division >> BU.
We are planning to keep Cost Center and Department independent of BU.

**Comment by sanjay-hercules** [comment]
Dear All, please find attached and review draft version of BU implementation document.
[business_unit_draft_v1.0.docx](https://github.com/frappe/erpnext/files/1895589/business_unit_draft_v1.0.docx)

Please let us know your feedback on this.

**Comment by rmehta** [comment]
@sanjay-hercules lets use "Department", now that it is a tree.

We will need to add department wherever cost center is present.

Lets open a new issue for this. Also best to avoid attaching word docs in issues as they are not searchable 😉

**Comment by sanjay-hercules** [comment]
**1   Objective**
The main objective of implementation of Business Unit in ERPNext is to facilitate branch accounting using single chart of account. 

This will help user to :

- maintain single chart of account for a company and its branches
- record transactions at BU level
- maitain bank/cash, payable, receivable, warehouse at BU level
- make inter branch transfer of stock and fund
- generate branch-wise financial statements and other reports 

Currently in ERPNext branch accounting functionality is not available, however user can use Cost Center as a branch to record income and expenses at Cost Center level. But if user want to maintain branch-wise bank, warehouse, receivable and payable then it is not possible by using Cost Center. In this case, he/she has to create company as a branch which makes branch-wise data presentation and consolidation difficult.

**2   Assumptions**
- Business Unit name will unique.
- If a Region (Territory) and Division are tagged to Business Unit then same can’t be changed if any transaction recorded undet that business unit.
- Document (i.e. Sales/Purchase Order/Invoice) will be created under single business unit and system will not allow user to select items or taxes from multiple business unit.

**3   Tagging**
A business unit can be tagged under a region or a division or both. This tagging will help user to see region and divison wise summary of transactions and financial reports.

**4   Hierarchy**
![image](https://user-images.githubusercontent.com/34718633/38615837-b27086ac-3daf-11e8-9246-e9baa7da52d6.png)

![image](https://user-images.githubusercontent.com/34718633/38615850-bcab7a1e-3daf-11e8-8db9-27ecf5f74c49.png)


**5   Setup**
User is required to setup Region and Division before setting up of a Business Unit.

5.1   Region (Territory)

- A region can be termed as Area/Location/Territory where a business unit is situated. It should be independent of Company.
- We can use existing Territory document.

![image](https://user-images.githubusercontent.com/34718633/38615914-ec494418-3daf-11e8-995c-f04fceff9125.png)

_Note : Territory Target should be defined at company level._

5.2   Division

- A division of a business, sometimes called a business sector, is one of the parts into which a business, organization or company is divided. It should be independent of Company. For example, Maruti Automobiles has Sales and Service divisions.
- A new doctype will to be created with below details:
![image](https://user-images.githubusercontent.com/34718633/38615994-29f3e110-3db0-11e8-826f-ce5b2f52f780.png)

![image](https://user-images.githubusercontent.com/34718633/38615967-12559ad0-3db0-11e8-8986-2a43065c6c10.png)

5.3   Business Unit

- A business unit is an organization or organizational subset that is independent with regard to one or more accounting or operational functions.
- In business, a strategic business unit (SBU) is a profit center which focuses on product offering and market segment. An SBU may be a business unit within a larger corporation, or it may be a business unto itself or a branch.
- A busines unit can be tagged to a Region or Divisoin or both.

A new doctype will to be created with below details:
![image](https://user-images.githubusercontent.com/34718633/38616067-57e9ea4c-3db0-11e8-9855-79d72edbc139.png)

**Comment by rmehta** [comment]
I think we can use department in the GL, now that we are converting it into a tree structure.

https://github.com/frappe/erpnext/pull/13567

**Comment by sanjay-hercules** [comment]
below is draft version of BU doctype where BU is tagged to territory and department (division):
![business_unit_v_1 0](https://user-images.githubusercontent.com/34718633/38733959-8378b250-3f41-11e8-9566-28e9583dcc12.gif)

**Comment by sanjay-hercules** [comment]
Please review above and let me know if it is okay.

**Comment by rmehta** [comment]
@sanjay-hercules how is this linked to the GL? Can you start a PR?

**Comment by sanjay-hercules** [comment]
@rmehta I have not yet done GL linking part. I don't think department can be used at level 3 because in our case it should be at lowest level. Also branch is currently being used in various HR documents so instead of creating Business Unit we can enhance Branch for this purpose.

![bu_structure](https://user-images.githubusercontent.com/34718633/38788083-71bc0746-414f-11e8-9010-24dc1f8dec8d.png)

**Comment by sanjay-hercules** [comment]
I think it would be better if we go with above approach. 
In this case, GL Entry will have reference of :
Company (already there)
Region
Division
Branch
Department

**Comment by rmehta** [comment]
@sanjay-hercules but the sub depts could be departments too, right like

Branch X - HR
Branch Y - HR

etc?

**Comment by ushashmi** [comment]
great job @sanjay-hercules 

Instead of restricting to one standard structure which is applicable to few companies can we look in to incorporating Analysis Codes (T codes) like Infor Sun Financials? Without any restriction of being applied to any document type and General Ledger Account Codes including Balance Sheet and P&L. 

A company can define their own analysis codes depending upon their business and operational requirements. The analysis codes can be ranged from T1-T10 where in T1 can be Business Units, T2 Can be Division, T3 can be Cost Center, T4 can be Project, T5 can be Employees etc. etc.
 
The good thing about T codes (Analysis codes) is that they can be molded to any company’s operational and business requirements. Additionally, the analytical reports can be easily generated which can be used for strategic decision-making purposes. 

For reference you can check [https://docs.infor.com/sunsystems/6.3.x/en-us/ssolh/lsm1457708075704.html](url)

**Comment by sanjay-hercules** [comment]
No @rmehta , department couldn't be considered as branch because branch is a revenue generating unit which can have its own payable/receivable/stock/bank accounts.

**Comment by rmehta** [comment]
Why not just give those properties to department too? its just a way of naming things.

**Comment by sanjay-hercules** [comment]
@rmehta department is a functional unit where is branch is an operational unit of a company. Also if we use those properties in department then how can an employee be tagged in HR Dept of Branch X?

**Comment by sanjay-hercules** [comment]
@ushashmi , that link is not working.

**Comment by ushashmi** [comment]
Here is a link 

https://docs.infor.com/sunsystems/6.3.x/en-us/ssolh/lsm1457708075704.html

**Comment by pm-at** [comment]
@sanjay-hercules: Works if you copy-paste the url in browser.

**Comment by sanjay-hercules** [comment]
![cc_change](https://user-images.githubusercontent.com/34718633/39959491-188c9bea-5630-11e8-8c5d-b70b7146a513.gif)

**Comment by sanjay-hercules** [comment]
![cost_center_changes](https://user-images.githubusercontent.com/34718633/39959780-9cdfa9b0-5634-11e8-9a64-60e6eef891e1.gif)

**Comment by sanjay-hercules** [comment]
demo of above changes as below
![cost_center_changes](https://user-images.githubusercontent.com/34718633/39967150-25870bce-56d4-11e8-8c0b-b66e049846e8.gif)

**Comment by jk2081** [comment]
@sanjay-hercules Would a user be able to select or set a cost center at login so that a default cost center could be set in the transactions. I know that this would eliminate a lot of clicks and potential incorrect entries.

**Comment by sanjay-hercules** [comment]
@jk2081 No, this change will not make cost center available in login page. You can setup default cost center at user level  through **User Permission**.

**Comment by jk2081** [comment]
Closing this as @sanjay-hercules has sent a PR and it has been merged for release in v11.

**Comment by nabinhait** [comment]
#17769
