### ISSUE TITLE
"Please clear the selected Payment Terms Template" Error (but not really error..)

### ISSUE THREAD

**Issue by binary64** [frappe/erpnext#12594]
So I Bulk Updated all my Customers Payment Terms Template. It works. My invoices now show the payment terms template just fine. But when I click Invoices > New > then select a Customer .. I see a `Please clear the selected Payment Terms Template` error popup. I click OK on it to dismiss it, and everything seems to work fine. In other words, the error shouldn't be showing as I cannot see any error.

**Comment by binary64** [comment]
I have some clues.

I just read https://discuss.erpnext.com/t/please-clear-the-selected-payment-terms-template/33117

@saurabh6790  points out that manually changing the Payment Due Date to a different date would show a (similar) error message. However, on my system (latest develop), if I change the date to make it different, i see the error, but when i change the date back to match the Customers Payment Terms Template, then it *still* shows the error.

This might be related to my (very similar) error of "Please clear the selected Payment Terms Template"

The truth is, I don't want to clear the selected Payment Terms Template, as it's perfect :)

**Comment by tundebabzy** [comment]
Hi @binary64 
I've not been able to reproduce this. Can you add an animated gif so we can see what exactly is going on

**Comment by binary64** [comment]
This seems fixed now, after bench update showed me this:

```
Executing erpnext.patches.v10_0.set_default_payment_terms_based_on_company in erp.jcitbournemouth.co.uk (8f1968933d056513)
Success
```

which seems related

Thank you
