### ISSUE TITLE
Missing GL Entry for Stock Entries

### ISSUE THREAD

**Issue by adnanmunir83** [frappe/erpnext#12592]
after the Upgrade to Version 10 from Version 8.  we experienced strange and weird behavior for "Stock Entries". 

Below is the List which was working fine on version 8.  but having issue with Version 10.

1. Stock entry is Missing it's GL entry.  we found this issue when there was difference in TB Stock value and Stock Balance Report for any warehouse.  
below are the images for correct GL entry and missing GL entry for SE.
**Normal SE**
![normal se gl](https://user-images.githubusercontent.com/26667854/35210334-392d214c-ff6b-11e7-9c5d-cf95a5d94926.jpg)

**Stock Entry is Submitted**
![se status submittied](https://user-images.githubusercontent.com/26667854/35210342-44bec394-ff6b-11e7-8bc9-485a82b09ede.jpg)

**Missing GL Entry for Submitted SE**
![missing gl entry for se](https://user-images.githubusercontent.com/26667854/35210407-7d65925e-ff6b-11e7-8f34-82a8d4aa0c9c.jpg)

2.. Request Time out while submitting Stock Etnry in Version 10 having 400 Items.  where as  in version 8 we used to Submit Stock entry of 600 Items without any issue.  we changed the parameters for SQL and Http request to 600 Sec. but still after this time again same error, "request timed out".

all this happen only in Version 10.

**Comment by umairsy** [comment]
The screenshot provided indicates that Purpose is Material Transfer, but there is no target warehouse field above the Item table. Have you customized it?

Please share the screenshot of the stock Ledger entry for this Stock Entry on discuss.erpnext.com

Also, ensure that in the Company master, Perpetual Inventory Valuation is enabled. Then only, system will create GL Entry for the Stock Entry.

Further communication on the community forum, please.
