### ISSUE TITLE
[Enhancement Request] Process Payroll & Salary Structure

### ISSUE THREAD

**Issue by addymuliady** [frappe/erpnext#12625]
- [ ] **Add" Value Date" field**
-This will add a "Value Date" in salary slips, which tells the bank on which date the transaction will proceed
-Editable in Salary Slip
-To show in "Salary Slip Print Format"

- [ ] **Add "Non-Earning/Deductible" Type in Salary Component**
-Salary Component which is not an Earning of Employee salary. For example, Employer's contribution to pension scheme or levies and fees.

- [ ] **Add "Non-Earning/Deductible" Section in Salary Structure**

- [ ] **Add "Non-Earning/Deductible" Section in Salary Slip Print Format**

**Comment by pm-at** [comment]
@addymuliady; Were you able to implement any solution for Employer's contribution?
