### ISSUE TITLE
Email Alerts to SMS

### ISSUE THREAD

**Issue by aakvatech** [frappe/erpnext#12624]
As an administrator
I want to configure Email Alert with optional checkbox for SMS
So that I can configure Email Alerts with the checkbox and a hooks script would identify the Mobile number of the contact and send out an SMS as well from Contact DocType and send the body of email to the mobile number of contact as an SMS based on the settings defined in SMS Settings.

**Comment by maheshengg** [comment]
Me Too Looking forward for updates on this

**Comment by umairsy** [comment]
@revant can we add this to bounty?

**Comment by aakvatech** [comment]
I can try to work on this, but need some guidance. Firstly, is the idea correct and can I attempt it in that manner or is it undoable if we approach it in the manner indicated.

**Comment by umairsy** [comment]
Please followup for this feature request via https://github.com/frappe/erpnext/issues/8591
