### ISSUE TITLE
Add to invoice by item as well as Purchase Order

### ISSUE THREAD

**Issue by dboobisMF** [frappe/erpnext#12623]
Current system requires you to add the whole PO to the invoice when using the "Get Items From" option on a new invoice. Often there is need to only add a selection of items from an order to an invoice, so with the existing workflow users have to add the whole PO then remove unwanted lines. This is counterintuitive.

I would like to be able to select the individual lines to import per PO (as well as keeping the option to select the whole PO if required). This could also be implemented for Purchase Receipt, Sales Order and Delivery doctypes.

**Comment by umairsy** [comment]
It works this way already.

![po](https://user-images.githubusercontent.com/910238/36190744-f123692a-117f-11e8-9d8c-75764630b4df.gif)

For future reference, please post your queries on the community forum. If it is validated as a bug or suggestion, it can be shifted here.

https://discuss.erpnext.ocm

**Comment by dboobisMF** [comment]
This isn't quite what I was suggesting. If you have multiple POs on one invoice, this process does not work.

This was posted on the forums first (https://discuss.erpnext.com/t/add-to-invoice-by-item-as-well-as-purchase-order/33059/2) but I'll keep that in mind.

**Comment by dboobisMF** [comment]
@umairsy can this please be reopened as this is a legitimate request that was raised on the forums and redirected here? As explained above, there are situations where the current process does not work but that would be covered by this change.
