### ISSUE TITLE
Sales Order and Sales Invoice List is not viewable

### ISSUE THREAD

**Issue by amitsaxena01** [frappe/erpnext#12634]
The list view in Sales Order and Sales Invoice list is not viewable. It shows error message : Field item_code is not selectable. The stack trace is:
Uncaught (in promise) TypeError: Cannot read property 'df' of undefined
    at _class.set_values (list.min.js?ver=1516611726.0:220)
    at _class.setup (list.min.js?ver=1516611726.0:172)
    at new _class (list.min.js?ver=1516611726.0:111)
    at _class._push_new_filter (list.min.js?ver=1516611726.0:599)
    at _class.push_new_filter (list.min.js?ver=1516611726.0:570)
    at _class.add_filter (list.min.js?ver=1516611726.0:549)
    at _class.add_filters (list.min.js?ver=1516611726.0:517)
    at list.min.js?ver=1516611726.0:1690
    at <anonymous>
set_values @ list.min.js?ver=1516611726.0:220
setup @ list.min.js?ver=1516611726.0:172
_class @ list.min.js?ver=1516611726.0:111
_push_new_filter @ list.min.js?ver=1516611726.0:599
push_new_filter @ list.min.js?ver=1516611726.0:570
add_filter @ list.min.js?ver=1516611726.0:549
add_filters @ list.min.js?ver=1516611726.0:517
(anonymous) @ list.min.js?ver=1516611726.0:1690
Promise rejected (async)
show @ list.min.js?ver=1516611726.0:1912
BaseList @ list.min.js?ver=1516611726.0:1234
ListView @ list.min.js?ver=1516611726.0:1904
(anonymous) @ list.min.js?ver=1516611726.0:2833
callback @ desk.min.js?ver=1516611726.0:5629
callback @ desk.min.js?ver=1516611726.0:1471
_ @ desk.min.js?ver=1516611726.0:1495
(anonymous) @ desk.min.js?ver=1516611726.0:1596
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
z @ jquery.min.js:4
(anonymous) @ jquery.min.js:4
XMLHttpRequest.send (async)
send @ jquery.min.js:4
ajax @ jquery.min.js:4
frappe.request.call @ desk.min.js?ver=1516611726.0:1582
frappe.call @ desk.min.js?ver=1516611726.0:1475
with_doctype @ desk.min.js?ver=1516611726.0:5603
make @ list.min.js?ver=1516611726.0:2817
show @ desk.min.js?ver=1516611726.0:9946
show @ list.min.js?ver=1516611726.0:2849
(anonymous) @ desk.min.js?ver=1516611726.0:27
frappe.route @ desk.min.js?ver=1516611726.0:2228
startup @ desk.min.js?ver=1516611726.0:12544
load_startup @ desk.min.js?ver=1516611726.0:12513
init @ desk.min.js?ver=1516611726.0:12509
Class @ desk.min.js?ver=1516611726.0:37
frappe.start_app @ desk.min.js?ver=1516611726.0:12493
(anonymous) @ desk.min.js?ver=1516611726.0:12504
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
ready @ jquery.min.js:2
J @ jquery.min.js:2

**Comment by umairsy** [comment]
Works fine in the master and develop build. Request you to post this issue on the community forum.

https://discuss.erpnext.com
