### ISSUE TITLE
Stock Entry - Fetch Warehouse Address

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#12636]
Use-case:

In the case of sub-contracting, the material are transferred from our warehouse to sub-contractors warehouse. As per the local taxation requirement, companies need a proper format of Material Transfer entry, with from and to warehouse address, party involved and tax applied.

If we fetch address of Source and Target Warehouse in the Stock Entry, that will help user a lot in creating a statutory print format around it.

**Comment by krishnanhemanth** [comment]
I am presently using Stock entry as Delivery Challan to supply material to subcontract
The Delivery Challan fetches the Subcontract details
The Delivery challan is a document supplied along with the material
I create a PO with relevant charges and Taxes... then Create a StockEntry which doubles up as my Delivery challan
Hence Both the criteria is fullfilled
Regards
Hemanth
