### ISSUE TITLE
Lab tests not linked to Consultation

### ISSUE THREAD

**Issue by mudux** [frappe/erpnext#12643]
#### Domain: Healthcare.
There should be linkage between Lab tests and their respective Consultation.

This should also appear on the dash board of each doctype.

**Comment by system19** [comment]
Lab requests from the Doctor can currently be pulled from a consultation when creating a new Lab Test . Maybe they should get saved to the patients file as a medical record after the Lab Test is complete?

**Comment by mudux** [comment]
@system19 On point right there.
There should be a PMR linked with reference doctype  and reference no of the consultation doctype.

___Currently none exists.___
