### ISSUE TITLE
IMPORTANT! POS bug: Duplicate sale and premature conclusion (automatically)

### ISSUE THREAD

**Issue by noetico** [frappe/erpnext#12645]
Hi friends; 
This had been brought to my attention last year after upgrading to v9 from v6 in a high volume retail store, now also occurring at a fresh site. observing htop at the terminal, sometimes there's no spike on processor or ram but the system will freeze and then return. 

**Observation 1**: System can periodically freeze while cashier is scanning items at POS, on becoming responsive, sale is automatically submitted! I have also seen this first hand.
**Observation 2**: System can post a sale twice (I also doubted this, but I saw it myself) sometimes time frame between sale is less than 2 seconds which is impossible for one person to do. See screenshots; sale is by the same person and its barely 1 second between them! I think this is so urgent please; another very delicate point for pos module. Please @rohitwaghchaure @rmehta Have a look at the screenshots.

May I add that this occurs more than 5 times daily, I saw 2 just within 1 hour visiting the store.

Images attached:
![img-20180124-wa0002](https://user-images.githubusercontent.com/15412145/35351912-ab648eca-0142-11e8-998d-d1673a89927e.jpg)
![img-20180124-wa0003](https://user-images.githubusercontent.com/15412145/35351914-ac3652a2-0142-11e8-87a5-3878a069dd46.jpg)

**Comment by mudux** [comment]
I have endured a similar problem with POS..knowing that POS in not erpnexts strongest suit.

We have had to ask our cashiers to slow down to accommodate POS. or a times work through the duplicates and then return them.

**Comment by noetico** [comment]
@mudux thanks for the reply, yes, slowing down actually makes it better, its worse with the 'fast' and good cashiers; but speed is the best thing for pos and retail! so for them its not an option, they deal with more than 900 sales invoices on the average day.

 I will sing the old song again, these never, ever occured in v6 in about 2+ years of usage, and still doesnt occur, we still have over 15 on v6, only those on v9 and 10 (about 3) have this issue.

**Comment by noetico** [comment]
I think just a little attention to the online pos should tidy it up

**Comment by rohitwaghchaure** [comment]
@noetico 

Observation 1: System can periodically freeze while cashier is scanning items at POS, on becoming responsive, sale is automatically submitted! I have also seen this first hand.
Observation 2: System can post a sale twice (I also doubted this, but I saw it myself) sometimes time frame between sale is less than 2 seconds which is impossible for one person to do.
**Are you facing above issues in online POS?**

**Comment by noetico** [comment]
‎Thanks a lot Rohit

We have this issue with online pos. Currently serious at 2 locations especially one with heavy transactions; up to 900 daily sales invoices.

I greatly appreciate your attention to this, please this is crucial to the functionality and trustworthiness of the pos module. It's urgent Sir.

Sent from my BlackBerry 10 smartphone.
From: rohitwaghchaure
Sent: Thursday, January 25, 2018 08:27
To: frappe/erpnext
Reply To: frappe/erpnext
Cc: Kent; Mention
Subject: Re: [frappe/erpnext] IMPORTANT! POS bug: Duplicate sale and premature conclusion (automatically) (#12645)



@noetico<https://github.com/noetico>

Observation 1: System can periodically freeze while cashier is scanning items at POS, on becoming responsive, sale is automatically submitted! I have also seen this first hand.
Observation 2: System can post a sale twice (I also doubted this, but I saw it myself) sometimes time frame between sale is less than 2 seconds which is impossible for one person to do.
Are you facing above issues in online POS?

**Comment by Olawale1** [comment]
Hi @rohitwaghchaure 

Trust you're doing well. Is there any progress on this? See screenshot of a transaction that got posted 5 times below! This is getting very tiring... 
![pos multiple invoice issue 2-1](https://user-images.githubusercontent.com/9269337/36371203-b151e926-1561-11e8-971d-048576fc0c7b.png)

Kind regards,

**Comment by rohitwaghchaure** [comment]
@Olawale1 
Have made some changes in the code, can you please pull the latest update and check. Closing this issue, feel free to reopen if issue still persists

**Comment by noetico** [comment]
Thanks @rohitwaghchaure great work. We'll update and let you know.
