### ISSUE TITLE
Sub-contracting - Allow Editing Raw-material Qty

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#12653]
Usecase:

As per the BOM 100 Kg of Material is required for manufacturing of 10 units. However, in the Material Receipt, you should be able to receive 9 unites (against Sales Order), but have total 100 Kg consumed.

Currently, in Purchase Receipt, it auto-calculated the qty of raw-material based on the BOM. So, if finished item Qty is set as 9, the qty of raw-material is reset/reduced accordingly. User wants functionality to edit the raw-material qty and let total 100 get consumed.

**Comment by djpalshikar** [comment]
@umairsy I am sponsoring a similar request, #12150 . 
#1250 should take into account the case mentioned above.
