### ISSUE TITLE
Product bundle doesn't work well with delivery 

### ISSUE THREAD

**Issue by sathishpy** [frappe/erpnext#12655]
I created a product bundle containing two products with it default inventory location set to Finished Goods. I used it to create the Sales Invoice, which worked ok. However when making the delivery, it reported product isn't available, though stock summary said it is there. On taking another look, I observed it is expecting the items in stores, though the individual item inventory is set to Finished goods.

**Comment by LifeP** [comment]
This is something I find to be a functional necessity and is available in o.... out of the box.
