### ISSUE TITLE
Missing + link sometimes

### ISSUE THREAD

**Issue by binary64** [frappe/erpnext#12661]
Hi,

Found a small bug, that is really easy to test/reproduce:

Close Chrome
Load ERPNext and login
Open an invoice eg http://erp/desk#Form/Sales Invoice/SINV-00010 
Notice next to the `Payment Entry` link there is a "+" button
Now press f5
Notice how the "+" button has now disappeared

I'm on very latest develop

**Comment by umairsy** [comment]
In my test build, it doesn't show + for Payment Entry at all.
