### ISSUE TITLE
Cant view leave applications list

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#12669]
Hello,

I'm using developer branch for testing and report bugs and after executing the patch erpnext.patches.v10_0.workflow_leave_application I get this error on console every time I try to open the leave application list:

"Uncaught (in promise) TypeError: Cannot read property 'push' of undefined
    at ListView._add_field (list.min.js?ver=1516026628.0:1324)
    at ListView.set_stats (list.min.js?ver=1516026628.0:1334)
    at <anonymous>"

* I have a workflow enabled on this document

**Comment by xantipass** [comment]
I had same error.
User cannot view desk#List/Leave Application/List by error:

>  Uncaught (in promise) TypeError: Cannot read property 'push' of undefined
>     at ListView._add_field (list.min.js?ver=1515124934.0:1348)
>     at ListView.set_stats (list.min.js?ver=1515124934.0:1357)
>     at <anonymous>
But the Administrator user still working with no error?
Is there any mistake in Permission?

**Comment by kennethsequeira** [comment]
@applepipe Frappe and ERPNext develop versions please 😁

**Comment by applepipe** [comment]
@kennethsequeira 

I'll include on every bug report from now on

ERPNext: v9.x.x-develop (9f29f60) (develop)
Frappe Framework: v9.x.x-develop (d37875a) (develop)
