### ISSUE TITLE
POS credit card payments not included in Bank Reconciliation

### ISSUE THREAD

**Issue by dwork** [frappe/erpnext#12660]
(v10) Bank reconciliation includes only payment entries and journal vouchers, which renders the process problematic for POS. Credit Card payments make during POS entry and Sales Invoice w/POS payment are not included in the Bank Reconciliation process -- we process our credit cards directly into our bank account. A work-around would be to set up an "uncleared credit card" account and then make a journal entry to transfer the payments, but cumbersome.

**Comment by umairsy** [comment]
Also linked to Support Issue WN-SUP30820
