### ISSUE TITLE
Field from Restaurant module shown in Pricelist form

### ISSUE THREAD

**Issue by ryuliantoro** [frappe/erpnext#12679]
The Restaurant Menu field (from Hospitality domain) is always displayed in Pricelist form (Stock module).
The Domain chosen is not Hospitality.

![screenshot 2018-01-28 01 05 16](https://user-images.githubusercontent.com/13296444/35478187-ecc4f012-0408-11e8-91cb-017ef1a6d70b.jpg)
![screenshot 2018-01-28 01 05 41](https://user-images.githubusercontent.com/13296444/35478188-ecfcb3e4-0408-11e8-9c06-f698c129886a.jpg)

**Comment by tundebabzy** [comment]
frappe/frappe#4931
