### ISSUE TITLE
[data-import] Failed docstatus in case of successful import

### ISSUE THREAD

**Issue by pratu16x7** [frappe/erpnext#12675]
WN-SUP30618

<img width="1096" alt="screen shot 2018-01-27 at 1 22 54 pm" src="https://user-images.githubusercontent.com/5196925/35469933-a8144f92-0365-11e8-98f3-80080acf902c.png">

**Comment by Siddhisawant8** [comment]
@pratu16x7 : Since your import was successful, after importing Go to the previous page, and Reload.
the status will be changed to success automatically.

**Comment by manassolanki** [comment]
Actually, if it is from the cached page, it will not older otherwise it will update.
