### ISSUE TITLE
Crowdin erpnext crowdin project

### ISSUE THREAD

**Issue by phbrgnomo** [frappe/erpnext#12672]
Hi everyone,

i found these project on Crowdin 
https://crowdin.com/project/erpnext-translations
https://crowdin.com/project/frappe-translations

I would like to know if it is an official way to translate frappe or erpnext projects

Ty

**Comment by kennethsequeira** [comment]
Hey @phbrgnomo 

https://translate.erpnext.com/ is the only way to translate ERPNext officially as far as I know.

You can contribute with others from the community over there 😄
