### ISSUE TITLE
[POS profile] : Ability to make Sales Return.

### ISSUE THREAD

**Issue by mudux** [frappe/erpnext#12682]
#### General Idea
Its common place that POS users have limited access to certain aspects of transactions.

One very key part would be the ability to make sales return, which is a preserve of authorized personnel.

An addition to the POS profile should be made to enable or disable this functionality via omitting the button for this action on page load.

**Comment by kennethsequeira** [comment]
Added in v13

![image](https://user-images.githubusercontent.com/33246109/139879839-a3d5451d-645b-4eba-b857-7d3fb94b7456.png)
