### ISSUE TITLE
Auto exchange rate pulling today's value regardless of document date

### ISSUE THREAD

**Issue by dboobisMF** [frappe/erpnext#12686]
ERPNext seems to be pulling the current exchange rate regardless of the document date stated. In the below example (where our company currency is GBP and the document currency is EUR), I have set the document date to 01/09/17, where the rate should be 0.92075 as per the source. However, as you can see it is being set as 0.87335 which is the current prevailing rate provided by fixer.io.

![image](https://user-images.githubusercontent.com/16403515/35503621-8f579dbe-04d8-11e8-9a0c-3a44c4dc2c7c.png)

This is not acceptable behaviour, exchange rates can fluctuate wildly over time and setting the wrong rate can change valuations significantly. Please see if this can be rectified.

**Comment by dboobisMF** [comment]
Looking at the code, this might only be an issue for documents that don't hit the General Journal. This is still bad as this means individual documents could be getting revalued throughout the order/receipt/invoicing process.

**Comment by tundebabzy** [comment]
Hi @dboobisMF 
Please add steps to reproduce

**Comment by dboobisMF** [comment]
I found this while working on a Purchase Order.

1) Change the date to some time in the past
2) Change the currency to something other than the base
3) Change the date back to today

On my install the exchange rate does not change (although I just tested on demo.erpnext.com and it did). For reference, my base currency is GBP and I have tried both EUR and USD. I have tried with "Allow stale exchange rates" ticked and unticked.

**Comment by tundebabzy** [comment]
What version are you on?

**Comment by dboobisMF** [comment]
![image](https://user-images.githubusercontent.com/16403515/35559097-b9de0fb8-05a1-11e8-8896-16a8993b9087.png)

**Comment by tundebabzy** [comment]
@dboobisMF 
I haven't been able to replicate this. There are newer versions able so I have a feeling that running `bench update` will fix your issue. I'm closing for now but feel free to open if the issue persists.

> Looking at the code, this might only be an issue for documents that don't hit the General Journal.

What part are you referring to?

**Comment by dboobisMF** [comment]
I was looking at the following from erpnext\setup\utils.py:

	def get_exchange_rate(from_currency, to_currency, transaction_date=None):
	if not (from_currency and to_currency):
		# manqala 19/09/2016: Should this be an empty return or should it throw and exception?
		return

	if from_currency == to_currency:
		return 1

	if not transaction_date:
		transaction_date = nowdate()

	currency_settings = frappe.get_doc("Accounts Settings").as_dict()
	allow_stale_rates = currency_settings.get("allow_stale")

	filters = [
		["date", "<=", get_datetime_str(transaction_date)],
		["from_currency", "=", from_currency],
		["to_currency", "=", to_currency]
	]

	if not allow_stale_rates:
		stale_days = currency_settings.get("stale_days")
		checkpoint_date = add_days(transaction_date, -stale_days)
		filters.append(["date", ">", get_datetime_str(checkpoint_date)])

	# cksgb 19/09/2016: get last entry in Currency Exchange with from_currency and to_currency.
	entries = frappe.get_all(
		"Currency Exchange", fields=["exchange_rate"], filters=filters, order_by="date desc",
		limit=1)

	if entries:
		return flt(entries[0].exchange_rate)

	try:
		cache = frappe.cache()
		key = "currency_exchange_rate:{0}:{1}".format(from_currency, to_currency)
		value = cache.get(key)

		if not value:
			import requests
			api_url = "http://api.fixer.io/{0}".format(transaction_date)
			response = requests.get(api_url, params={
				"base": from_currency,
				"symbols": to_currency
			})
			# expire in 6 hours
			response.raise_for_status()
			value = response.json()["rates"][to_currency]
			cache.setex(key, value, 6 * 60 * 60)
		return flt(value)
	except:
		frappe.msgprint(_("Unable to find exchange rate for {0} to {1} for key date {2}. Please create a Currency Exchange record manually").format(from_currency, to_currency, transaction_date))
		return 0.0

I have updated to the latest release and it's still not working as expected. I have never even seen the exception message.
