### ISSUE TITLE
Can’t edit chart of accounts on chart.erpnext.com

### ISSUE THREAD

**Issue by krnkris** [frappe/erpnext#12698]
As discussed in:

https://discuss.erpnext.com/t/charts-erpnext-com-doesnt-work/33219

**Comment by kennethsequeira** [comment]
@krnkris has the issue been resolved?

**Comment by ilyesderp** [comment]
No, not yet.

**Comment by ilyesderp** [comment]
@kennethsequeira no, it hasn't been solved yet.

**Comment by krnkris** [comment]
Please refer to:

https://github.com/frappe/erpnext/issues/13126

**Comment by barhamed** [comment]
now the page has an error message
![sans titre](https://user-images.githubusercontent.com/23336631/37269948-0b4542f4-25cd-11e8-99e3-dd1aa68abf87.png)

**Comment by barhamed** [comment]
the fork is fixed by @rmehta but the download and the creat a new charts isn't yet

**Comment by krnkris** [comment]
The fork is works, but somehow fork a base chart instead what shows on the display.

**Comment by krnkris** [comment]
Related to:
https://github.com/frappe/erpnext/issues/13126#issuecomment-374333487

**Comment by krnkris** [comment]
Fixed as of:
https://github.com/frappe/erpnext/issues/13126#issuecomment-374333487
