### ISSUE TITLE
Stock Entry creation (From Item DocType) does not set UOM

### ISSUE THREAD

**Issue by cgpurbaugh** [frappe/erpnext#12711]
When creating a stock entry to move stock from the item doctype, clicking add more items redirects to the Stock Entry.  If the user attempts to save, then an error appears showing that the UOM is not set.

ERPNext V: 10.0.17
Frappe V: 10.0.16

**Comment by jaichavan** [comment]
Hello, @cgpurbaugh I'm not able to replicate the issue on the latest version [ ERPNext: v11.0.3-beta.34 () (staging) ]
Can you please recheck and confirm if it still _persists_?

**Comment by cgpurbaugh** [comment]
It has been fixed.
