### ISSUE TITLE
[Bug] Outstanding Amount not getting updated in Payment Entry

### ISSUE THREAD

**Issue by jay-parikh** [frappe/erpnext#12713]
Steps to replicate:
1. Create Purchase Invoice / Sales Invoice.
2. Make Payment Entry.
3. Make partial payment by adding partial payment to "Paid Amount (INR)" field.
4. Check "Outstanding (INR)" in Reference table, which is not getting updated.

![partial payment against pi](https://user-images.githubusercontent.com/3703266/35568222-18a47bee-05ee-11e8-9b03-5173dacb22ea.gif)

**Comment by kennethsequeira** [comment]
I can replicate this.

However, when you make the next payment, the outstanding amount is fine. The amount is also updated in the linked Sales Invoice. 

This seems more of a UI/UX problem since the Outstanding Amount isn't supposed to be deducted against the allocated amount in the same payment entry.

**Comment by helios-ventures** [comment]
We are also facing the same challenge.

Our Domain is Education (Newly Launched University).

When collecting student fees, the system doesn't auto update the fee balance against the collected and the set total fee.

I'd really appreciate any help on this.

There's this post about this issue : https://discuss.erpnext.com/t/outstanding-balance-and-overdue-balance-for-student/29641/4 .

I doubt a patch was released to counter this bug.

**Comment by jay-parikh** [comment]
can we have any update on this issue?

**Comment by tundebabzy** [comment]
@jay-parikh 
The outstanding amount field shows the outstanding amount in the reference document. I have pushed #12975 so that once the Payment Entry is submitted, the Payment Entry reference is also updated to show the correct outstanding amount.

**Comment by Jamesmueke** [comment]
We are also facing the same challenge.

Our Domain is Education (Newly Launched University).

When collecting student fees, the system doesn't auto update the fee balance against the collected and the set total fee.

I'd really appreciate any help on this.

There's this post about this issue : https://discuss.erpnext.com/t/outstanding-balance-and-overdue-balance-for-student/29641/4 .

I doubt a patch was released to counter this bug.
was this fixed

**Comment by mohamadosama** [comment]
I had the same problem today, and could over come it after finding out the reason which can be considered as a bug to be fixed. I use **version 12.**

**Solution: When you create a payment entry, you have to do the following steps in order:**

1. add information except the allocation (the reference invoice)
2. Save (don’t submit)
3. Add the reference (invoice number and allocation amount)
4. Submit

**If you do it by this order, the allocation will be saved, and the invoice will be connected with the payment.**

**Comment by nabinhait** [comment]
@mohamadosama Can you list down the steps which does not update outstanding amount in reference docs?

**Comment by mohamadosama** [comment]
> @mohamadosama Can you list down the steps which does not update outstanding amount in reference docs?

In the Purchase invoice, if you click on the plus sign (+) for creating a payment entry based on that invoice:
- You will have all the invoice data added to the payment entry including the outstanding invoice in the references section.
- By clicking "Save" everything will be saved well, except for the Purchase invoice in the references, as it will be removed.
- If you ignore this and submit, the entry will be saved without the reference to the invoice.
The only way to have the Reference invoice submitted is to save once, and then add the invoice, and then save again, and it won't be removed before submitting it correctly.
