### ISSUE TITLE
Permissions for Sales Returns & Credit Notes

### ISSUE THREAD

**Issue by turner-james** [frappe/erpnext#12723]
We have sales users who can access Delivery Notes and Sales Invoices (ie. read, write, create, submit).

However, for important financial control purposes, we do not want them to be able to create a Sales Return (negative Delivery Note) or a Credit Note (negative Sales Invoice). 

As per the standard permissions, the option to create sales return and credit note entry depends upon permission on Delivery Note and Sales Invoice respectively. 

This is a problem, because it could enable fraud: a user creates a sales invoice or delivery to generate documentation to despatch goods from our yard. Then the user credits the sales invoice and keeps the money received from the customer.

 I would like to suggest urgent customizable permission for creating sales returns / invoice credit transactions.

**Comment by olamide2** [comment]
I second this,was just thinking of creating a github issue when I saw this.

Urgently needed

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.
