### ISSUE TITLE
Issue creating new batch number from stock entry forms; autofill OR autofetch problem

### ISSUE THREAD

**Issue by mobentec** [frappe/erpnext#12725]
Production order --> Manufacture stock entry, when needing to enter in a new batch number for the line item listed in the table, we start typing in numbers, and then hit enter.  It then pops up a modal window which autofills the newly entered number into the "Item" field instead of the "Batch ID" field.

It should be placed into the Batch ID field and the item code should be auto populated from the item which was listed in the item line item table.

**For the line item _BrownRibbon,_ we typed out testbatchnumber in the batch number field and then hit enter.**
![autofillissue](https://user-images.githubusercontent.com/6663120/35636242-8744b308-067e-11e8-81e8-a1816875f1ce.jpg)

**As you can see below, the text we typed out gets placed into the wrong field plus the item name is not autofetched.**
![image](https://user-images.githubusercontent.com/6663120/35635874-70105882-067d-11e8-9476-11c5433ce5f8.png)

**Comment by shreyashah115** [comment]
This has been fixed, not able to replicate. 

![stock-entry-batch](https://user-images.githubusercontent.com/17617465/37905241-da18338a-311b-11e8-8438-bab14b55f4e7.gif)
