### ISSUE TITLE
Fix Checkbox alignment in Firefox (various places)

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#12727]
See the screenshot here:

https://github.com/frappe/erpnext/pull/12670

Alignment of checkbox

<img width="166" alt="screen shot 2018-03-08 at 10 27 58 am" src="https://user-images.githubusercontent.com/140076/37133812-7d631e98-22bb-11e8-8952-25fda08d87ec.png">

### Also in Firefox for mac

<img width="346" alt="screen shot 2018-03-08 at 10 29 24 am" src="https://user-images.githubusercontent.com/140076/37133852-a55214b8-22bb-11e8-94cc-e60132398293.png">

**Comment by tundebabzy** [comment]
Ubuntu Firefox
