### ISSUE TITLE
Wrong dates created for salary slip

### ISSUE THREAD

**Issue by theopen-institute** [frappe/erpnext#12732]
When using the new Payroll Entry doctype, ERPNext currently creates incorrect start dates for my employee's Salary Slips. For example, when I create a Payroll Entry for the period 01-Jan-2018 to 31-Jan-2018, the salary slips come back starting 16-Jan-2018 (incorrect)  and ending 31-Jan-2018 (correct).

Based on previous discussions (see here: https://github.com/frappe/erpnext/issues/9513), this seems to be related to the fact that my fiscal year begins on the 16th of July.

**Comment by nabinhait** [comment]
Fixed via https://github.com/frappe/erpnext/commit/a645f36b2ba2c5ceb170cc68d448e30a19a55c4b#diff-487dc65648153da8bd267f415c5edda9R159
