### ISSUE TITLE
Request: Add Item Rename Permissions to Disable Item Renaming

### ISSUE THREAD

**Issue by bibinqcs** [frappe/erpnext#12731]
Hi,

I propose we add an option in the front end to disable renaming Items, unless the user has the designated role to do so.

Essentially I highlight this, as recently I noticed that when an item is renamed, it is updating in all documents, even invoices issued to customers in the past. 

Thank you

**Comment by snvora** [comment]
Hi,

I think your concern is regarding renaming Item Code.

> Essentially I highlight this, as recently I noticed that when an item is renamed, it is updating in all documents, even invoices issued to customers in the past.

Are you using Item Code in Invoice print format?
I think it is designed in this way only, to maintain links to an item with your invoice. So every time you rename item code, corresponding item code will update in respective the invoice and other places.

If you wish to disallow this to specific users, it is currently possible. In user doctype--> you can disable role Item Manager for restricting any updates to item master.

**Comment by hiousi** [comment]
item name renaming do the same. 
Why not allowing to rename item_code and item_name without altering old invoices?

**Comment by bibinqcs** [comment]
Usually in the print format I use description or Item name, and hence I never noticed this before.
Recently I had a scenario where I had to use item code, item name, and description. Thats when I noticed the issue.

**Comment by bibinqcs** [comment]
I am closing this Issue as this can be achieved using permissions
