### ISSUE TITLE
Unable to open Frappe + ERPNext (Develop) v10 Desk on Safari 11.0.2

### ISSUE THREAD

**Issue by gentiger** [frappe/erpnext#12735]
Hi all,

I have tried to open frappe desk (version) on Safari 11.0.2, however when loading the desk is throwing error message "SyntaxError: Unexpected token '...'. Expected a property name." when loading desk.min.js, control.min.js. There is no issue when open in Chrome. Seems is specific Safari issue

**Comment by kennethsequeira** [comment]
Hi, 

I was able to log in to an ERPNext account using safari (MacOS). Can you record a gif/screenshot of the error as well? Also, on what OS is the problem occurring?

**Comment by gentiger** [comment]
Frappe and ERPNext Version: <img width="1185" alt="screen shot 2018-02-01 at 9 57 45 pm" src="https://user-images.githubusercontent.com/9399857/35682334-4c8eac00-079b-11e8-8a4d-484dbffe3de0.png">

I am using MacOS High Sierra (10.13.2), it seems is not MacOS specific because my mobile client also having the same issue  Seems to me the most latest Frappe code [https://github.com/frappe/frappe/blob/005cfe3dc89d6586b7b3b19a0e6ed989eec666f4/frappe/public/js/frappe/ui/capture.js](url) have "..." which caused the issue.

<img width="1326" alt="screen shot 2018-02-01 at 10 14 30 pm" src="https://user-images.githubusercontent.com/9399857/35682923-52aaef20-079d-11e8-80ac-7d5380e6e4bf.png">

**Comment by kennethsequeira** [comment]
Can see this on Develop branch as well

![screen shot 2018-02-01 at 9 02 57 pm](https://user-images.githubusercontent.com/33246109/35686904-7429eb10-0793-11e8-9c31-a960eb764a4e.png)

**Comment by kothagunda** [comment]
same issue on firefox. Is there a workaround to get it installed pls.

**Comment by kennethsequeira** [comment]
@kothagunda fresh install or otherwise?

**Comment by kothagunda** [comment]
Its fresh install. I opened a discussion topic here. 
https://discuss.erpnext.com/t/cannot-go-to-desk-after-fresh-install

**Comment by kennethsequeira** [comment]
@kothagunda the current fresh install problem you are facing is caused due to some recent updates. The issue raised here was pertaining to only the Safari browser.

**Comment by hfaridgit** [comment]
Have same problem with firefox and fresh install of ERPNext version 10.1.4

**Comment by hfaridgit** [comment]
There is a syntax error in desk.min.js at line 12621   }!function(a)
it should be };!function(a)

Don't know why or is it from building the js files or it is a real coding error??

**Comment by kothagunda** [comment]
My issue got resolved, by running those commands specified. 
 https://discuss.erpnext.com/t/cannot-go-to-desk-after-fresh-install

**Comment by hfaridgit** [comment]
My issue got solved by modifying desk.min.js manually and putting missing line termination ";" in three lines.
And also erpnext.min.js has a missing line termination.
Now it works fine.

**Comment by achillesrasquinha** [comment]
Closing this. Works perfectly on Safari 11.0.3

When in doubt. Always `bench update`.
