### ISSUE TITLE
Sales Payment Summary

### ISSUE THREAD

**Issue by EddieDee** [frappe/erpnext#12730]
Hi,
 
 My accountant was getting crazy because all sales where so high and cashiers where only delivering half of the money the system was telling we sold. 

After some digging I found out the Sales payment summary is summing all payments without subtracting the change amount.

Let's say you are a client and you expend US$ 7, then you pay with a bill of US$10
So the cashier give you the 3 back.

The system is summing all 10s instead of the 7 as sales.

Regards,

**Comment by rohitwaghchaure** [comment]
@eagoweb 

Have checked on local account and it's working properly. Have created sales invoice using POS which is as below
![screen shot 2018-02-01 at 7 43 23 pm](https://user-images.githubusercontent.com/8780500/35682942-6f352a80-0788-11e8-9a6a-c75a13601c9e.png)

Invoice amount was 2100 and customer pay 2101 and cashier has returned 1 to the user.

In the report it's showing properly
![screen shot 2018-02-01 at 7 43 34 pm](https://user-images.githubusercontent.com/8780500/35682996-991d78de-0788-11e8-8478-8cccdbc2f051.png)

Did you added change amount in the sales invoice? It's applicable only for POS

**Comment by eagoweb** [comment]
Hi @rohitwaghchaure thanks for the input.

 I am still getting same problem with POS, but I am going to update to the latest erpnext this week before I try again because maybe I have a wrong code somewhere.

Regards,

I will update this myself when I am ready during this week

**Comment by eagoweb** [comment]
After upgrading, all is good sorry for the troubles @rohitwaghchaurenow I'll see how can I get the details of the different payment methods owner. This can be closed.

**Comment by jforv** [comment]
@rohitwaghchaure I've been experiencing the same thing as @eagoweb. Here my capture from my account on Erpnext.com.

![1](https://user-images.githubusercontent.com/20097635/40631125-51bfc4b8-62a7-11e8-80cf-983333476a6d.png)
![2](https://user-images.githubusercontent.com/20097635/40631126-51cff1ee-62a7-11e8-9f22-4fb412f3db4e.png)
![3](https://user-images.githubusercontent.com/20097635/40631129-5f7ba860-62a7-11e8-8a6c-5535fabbe19b.png)

**Comment by eagoweb** [comment]
Hey @jforv same happened to me, I though it was solved! wow, I got confused!, but let's see because @rohitwaghchaure got it working, but dunno how, I've tried different methods, maybe a fix?

**Comment by eagoweb** [comment]
@tundebabzy Can you re-open this please?

**Comment by eagoweb** [comment]
Thanks @tundebabzy, I hope @rohitwaghchaure  can review this again at POS even at erpnext.com

**Comment by eagoweb** [comment]
please help @rohitwaghchaure

**Comment by zkhan44499** [comment]
hi 
still same problem i am facing as well. i had updated to the new version but the same result. The total is showing how much we enter as total cash, not actual sale amount.

**Comment by jaichavan** [comment]
Hello, @EddieDee @zkhan44499 @jforv @tundebabzy 
This issue has been addressed and resolved in latest version [ ERPNext: v11.0.3-beta.34 () (staging) ]
Attaching screenshots for your reference:
1. POS Invoice ( Item price = Rs. 99.000 ), Amount paid = Rs. 100.00, Change = 1.00

![image](https://user-images.githubusercontent.com/40264279/51407995-61fac180-1b83-11e9-9a56-baba13e2e6a0.png)


2. Sales Invoice in list:

![image](https://user-images.githubusercontent.com/40264279/51407946-4394c600-1b83-11e9-807e-f289237a1908.png)

3. Report "Sales Payment" :

![image](https://user-images.githubusercontent.com/40264279/51407827-f6b0ef80-1b82-11e9-8ee4-ad43e42899b6.png)

Hope this _helps_. Thanks for reporting!
