### ISSUE TITLE
Item Standard Selling Rate does not update Standard Selling Rate within Standard Price List

### ISSUE THREAD

**Issue by mobentec** [frappe/erpnext#12744]
After an item has been created and submitted, updating the Standard Selling Rate field within the Item Form **does not automatically update the Standard Selling Rate within the Standard Selling Price List** that was created at the time of item creation.

![2018-02-01 at 17-01-37](https://user-images.githubusercontent.com/6663120/35705831-97b7e4d2-0771-11e8-9172-4d013f018ce8.png)

**Comment by kennethsequeira** [comment]
To update the Standard Selling Rate after setting it for the first time, use the Price List. The rate is not updated from the Item Master after setting it initially. 

Try updating the selling rate from **Item Price**. 

> Stock > Item Price

Or access it from the dashboard in the item master.

**Comment by mobentec** [comment]
@kennethsequeira This is why  I made a post here, is so the team can make it so that when the field within the Item Master is changed, that it also update the Item Price within it's Item Price Standard Price List.

Or, we should make the field read only after submit since changing it does not change it in the price list...

**Comment by kennethsequeira** [comment]
@mobentec this would be a duplicate issue. It would be best to follow up on the #12129 and bring the attention of the devs over there.

**Comment by mobentec** [comment]
@kennethsequeira Sounds good.  Sorry about the duplicate ticket! :-)
