### ISSUE TITLE
Missing encoding of % sign in account names

### ISSUE THREAD

**Issue by rasos** [frappe/erpnext#12743]
In the Austrian default account scheme, we have accounts like: 
`4000 Erlöse 20 %`
It is not possible to edit this account, as the URL is 
`http://erpnext.company.com/desk#Form/Account/4000%20Erl%C3%B6se%2020%20%%20-%20FG`
but it should be
`http://erpnext.company.com/desk#Form/Account/4000%20Erl%C3%B6se%2020%20%25%20-%20FG`
The percent sign % always needs to be encoded to %25.

**Comment by rohitwaghchaure** [comment]
Fixed via
https://github.com/frappe/frappe/pull/5442
