### ISSUE TITLE
[POS] After accessing once, it does not work when going back from separate area

### ISSUE THREAD

**Issue by OneiricIT** [frappe/erpnext#12745]
Tested on latest master frappe / erpnext, then tested on demo.erpnext.com. Used Firefox and Chrome.

Access POS from initial screen or under Accounts module - loads. Note the initial URL is /desk#pos which redirects to /desk#point-of-sale

Clicking out to a different area, then back via either front page POS shortcut / in Accounts module / global search 'Open POS' then shows a blank screen. Note the URL stays at /desk#pos and does not redirect like prior. Refreshing the page, or reloading via user manual and it works.

If using global search 'Open Point of Sale' it works each time without a problem as it goes directly to /desk#point-of-sale.

![2018-02-02_10-02-00](https://user-images.githubusercontent.com/22227933/35708055-5cb61ef0-0800-11e8-95a6-b6026ad0b06e.gif)

**Comment by kennethsequeira** [comment]
Can replicate this on master.

**Comment by rohitwaghchaure** [comment]
@OneiricIT 
We have identified and fixed the issue and we'll release the fix of this issue in next week.
