### ISSUE TITLE
Need warehouse wise stock in Stock Entry Document

### ISSUE THREAD

**Issue by AravindPranera** [frappe/erpnext#12748]
While doing stock entry, kindly display the stock details warehouse wise and from the warehouse selection by user display the Batch wise stock details, instead of below

![image](https://user-images.githubusercontent.com/28756911/35732660-52d85de0-0840-11e8-9ac6-474bf2d94374.png)

Currently the user has to know the stock in the warehouse by checking the Batch wise balance report. So, Kindly do needful.

Thanks.

**Comment by rohitwaghchaure** [comment]
@AravindPranera 
We have fixed this issue and will be release in version 11

**Comment by AravindPranera** [comment]
Noted Rohit.

Thanks,
Aravind

*Pranera Services & Solutions Private Limited*
*1A, Sastri Nagar,Angeripalayam Road,*
*Near SP Office,**Tiruppur - 641602.*
*Mob : 9786473999.*
*ba@praneraservices.com <ba@praneraservices.com> | www.praneraservices.com
<http://www.praneraservices.com>*
