### ISSUE TITLE
{bug} For Item (non-stock), cannot place order from shopping cart

### ISSUE THREAD

**Issue by jigneshpshah** [frappe/erpnext#12751]
**Environment**

ERPNext: v10.0.19 (master)
Frappe Framework: v10.0.20 (master)

**Current Behavior :**
Not able to place order on shopping cart , when  Item is non-stock.  It gives below error
![image](https://user-images.githubusercontent.com/4900815/35763254-3630a498-08ce-11e8-8a52-edb628da0673.png)

**Expected Behavior  :** 
It should allow to place the order, without validating for stock quantity, as it is non-stock item.

**Workaround :** 
To make the service item , as Maintain Stock.

**Comment by rohitwaghchaure** [comment]
@jigneshpshah 
Thanks for the detailed information, we've fixed the issue and by next week we'll release it
