### ISSUE TITLE
cannot search batch directly from global search

### ISSUE THREAD

**Issue by alpkaan83** [frappe/erpnext#12750]
Hello, İn global search i enter Batch Code, but when press enter, it doesnt find anything. even if i check global search in batch_id. how can i enable this. i want to use barcode scanner in global search for batch open automatically. erpnext is latest version

**Comment by tundebabzy** [comment]
>  Batch Code

Do you mean barcode? Barcodes are not searchable from global search by default. You can try using the customise form and check the 'In Global Search' checkbox for the `barcode` field

![screenshot-2018-2-5 customize form](https://user-images.githubusercontent.com/818803/35815164-2bec998a-0a98-11e8-989c-aee87e292703.png)

**Comment by alpkaan83** [comment]
no you misunderstand. i dont want to search barcode number, i want to use batch no for barcode reader, forget about barcode. batch numbers cant find in global search even if enabled global search in options.
