### ISSUE TITLE
Add filter informations to Employee Leave Balance PDF/print Report (date from, date to, company)

### ISSUE THREAD

**Issue by ronniegarcia** [frappe/erpnext#12764]
Hello,

PDF or printed reports are made to be stored outside of ERPNext or shared with other people.
Actually, when exported to PDF or printed, the Employee Leave Balance Report does not mention the filter informations used to make the report : date from, date to, company
Thus, the PDF/printed report is not very useful when it is taken out of context.

It would be great to print the filter informations in the PDF/printed report.
(This issue could concern other reports as well)

Thanks

ERPNext: v10.0.18 (master)
Frappe Framework: v10.0.19 (master)

**Comment by umairsy** [comment]
The existing report builder will soon be replaced with the new data-table tool of Frappe. 

https://github.com/frappe/datatable

Request you to add this feature suggestion in the Github Repo mentioned above.
