### ISSUE TITLE
Enable/Disable products section

### ISSUE THREAD

**Issue by aakvatech** [frappe/erpnext#12761]
Some homepages may not require the products to be displayed and so there should be a way to disable products section in a homepage.

**Comment by tundebabzy** [comment]
Do you mean there should be a way to disable the 'products' route in website i.e `[web_address]/products`

**Comment by umairsy** [comment]
please elaborate your query with an example, so that other members can also engage and collaborate on this.

**Comment by aakvatech** [comment]
Do close this issue as it has been taken care of in the v12 homepage. In v12 homepage the products only appear if you click on Explore button, which was the preffered option.
