### ISSUE TITLE
[Bug] Online POS wrong calculation for Paid Amount and Outstanding Amount

### ISSUE THREAD

**Issue by jay-parikh** [frappe/erpnext#12766]
Steps to reproduce:
1) Create Item with Selling price 1777.59
2) Open Online POS
3) Add product having 2 qty
![image](https://user-images.githubusercontent.com/3703266/35791095-c6baf34e-0a6b-11e8-8247-14ad15208656.png)
4) Check Grand Total = 3,555.18 and Rounded Total = 3,555.00
5) Click Pay to open Payment dialog
![image](https://user-images.githubusercontent.com/3703266/35791102-cdae696a-0a6b-11e8-9878-f8796bf71224.png)
6) Close Payment dialog, don't submit.
7) Now make changes to item added in cart. Decrease qty to 1
![image](https://user-images.githubusercontent.com/3703266/35791107-d37d6b52-0a6b-11e8-840d-1924f47ad842.png)
8) Click Pay to open Payment dialog
![image](https://user-images.githubusercontent.com/3703266/35791111-d9a0e4fa-0a6b-11e8-8524-945f63417691.png)
9) Change Amount = 0.41 and Outstanding Amount = 0.41 How can it be???
10) Try to submit Sales Invoice, Invoice is being saved as UnPaid.
![image](https://user-images.githubusercontent.com/3703266/35791115-dffdf428-0a6b-11e8-93d6-82c016ce5884.png)

Gif for this issue:
![bug paid amount and outstanding amount](https://user-images.githubusercontent.com/3703266/35791120-ee0b318e-0a6b-11e8-8873-7b7444580283.gif)

**Comment by tundebabzy** [comment]
Fixed in #12773
