### ISSUE TITLE
E-Mail Alert Attachments still in EN despite default print language is DE

### ISSUE THREAD

**Issue by ARAGATO** [frappe/erpnext#12762]
As posted in this thread
https://discuss.erpnext.com/t/e-mail-alert-attachments-still-in-en-despite-default-print-language-is-de/33414
I am still facing the issue of english language in attached pdf documents despite print language is set to 'de'.

In this Issue
https://github.com/frappe/erpnext/issues/12312
the issue was already presented, however it is not 100% congruent to mine.

In that issue, the language was wrong in the print preview. That is not the case for me. Everything is correct in the print preview. However, the pdf document, which is being generated by an email alert is in the wrong language. 

As presented in my erpnext discussion thread, print settings for the invoice as well as for the customer is set to 'de'. I have set an email alert that sends out invoice emails when a sales invoice is submitted. The pdf attached to that generated email is unfortunately in english.

**Comment by MaxMorais** [comment]
@ARAGATO it's related with https://github.com/frappe/frappe/pull/4838

**Comment by ARAGATO** [comment]
Alright Max, I'll wait for frappe/frappe#4838 to be solved.
