### ISSUE TITLE
[BUG]Items with Quotes(") or percentage (%) in naming are not recognized by online POS or item master

### ISSUE THREAD

**Issue by taherkhalil** [frappe/erpnext#12769]
Suddenly in the latest version items are not getting recognized , on further analysis found that all items which were initially created with a % or " in thier names are not getting detected in POS and cant access in item master . 

More details are on https://discuss.erpnext.com/t/items-with-quotes-or-percentage-are-not-recognized-by-online-pos-or-item-master/33471

Thanks

**Comment by rohitwaghchaure** [comment]
@taherkhalil 
I have checked on local account and it's working properly, can you pull latest code and check

## With double quotes(")
#### Item Master
![screen shot 2018-02-19 at 12 56 20 pm](https://user-images.githubusercontent.com/8780500/36366525-9146e2a4-1574-11e8-97c8-ee2fa02005ec.png)

#### In POS
![screen shot 2018-02-19 at 12 56 09 pm](https://user-images.githubusercontent.com/8780500/36366558-b789339a-1574-11e8-848e-4ee9754ba0a6.png)

## With percentage(%)
![screen shot 2018-02-19 at 12 56 48 pm](https://user-images.githubusercontent.com/8780500/36366523-8c77d01c-1574-11e8-937b-137b112c37bc.png)

#### In POS
![screen shot 2018-02-19 at 12 57 02 pm](https://user-images.githubusercontent.com/8780500/36366565-bd061b44-1574-11e8-8da0-2f0ed35ce653.png)

## Same item code which you've used
#### Item Master
![screen shot 2018-02-19 at 1 01 22 pm](https://user-images.githubusercontent.com/8780500/36366667-253f9186-1575-11e8-99c9-cd905f8b0de3.png)

#### In POS
![screen shot 2018-02-19 at 1 01 42 pm](https://user-images.githubusercontent.com/8780500/36366674-2e9c686c-1575-11e8-853d-86da3d636099.png)


Closing the issue feel free to reopen if issue still persists
