### ISSUE TITLE
Cannot remove Communication Item tag which contains spaces

### ISSUE THREAD

**Issue by aleksas** [frappe/erpnext#12776]
When tagging communication items, everything is fine (tagging, removing tag) unless the tag contains space. 

If tag contains space, clicking `x` on the tag doesn't do anything.

![image](https://user-images.githubusercontent.com/594470/35814893-e568cf62-0a9f-11e8-906e-4cc39da85a89.png)

ENV:
* ERPNext: v10.0.19 (master)
* Frappe Framework: v10.0.20 (master)

Discussion: [LINK](https://discuss.erpnext.com/t/cannot-remove-communication-item-tag-which-contains-spaces/33503)

**Comment by cgpurbaugh** [comment]
I'm having the same problem, seems to be for all tags.

**Comment by harsh0214** [comment]
@aleksas @cgpurbaugh Fixed this in frappe pull https://github.com/frappe/frappe/pull/5015
