### ISSUE TITLE
[bug] Webform : Not able to set default value for field type checkbox 

### ISSUE THREAD

**Issue by jigneshpshah** [frappe/erpnext#12771]
**Environment** 
**ERPNext: v10.0.19 (master)

Frappe Framework: v10.0.20 (master)**

Current Behavior  : 
 Step 1 : Create a webform with any doctype ( having field checkbox)
Step 2: Set the checkbox as mandatory and default value = "1" as below
![image](https://user-images.githubusercontent.com/4900815/35797387-92bbb596-0a85-11e8-86f1-bb527d436816.png)
 
Step 3 : View on website ,Also check the view - source code for the checkbox element
![image](https://user-images.githubusercontent.com/4900815/35797648-5144971c-0a86-11e8-9c6e-47ea2640d937.png)

Expected Behavior : 
The default value set in the checkbox field of the webform , should reflect on the website.

**Comment by shreyashah115** [comment]
It works fine if you don't set it as mandatory. Why would you make a checkbox mandatory?

**Comment by jigneshpshah** [comment]
Using checkbox for user to "Agree to policy/Terms & condition".

**Comment by shreyashah115** [comment]
I don't think it'd work even if you are able to display the default value as 1 and make it mandatory because user can check, uncheck and after that the mandatory check doesn't work anymore. Because, the field has its value as 0 or 1 which is enough for the mandatory check.
Instead just set the dafault value and add a custom script to not allow the user to go ahead if its not checked?

**Comment by jigneshpshah** [comment]
True, which is the best place according to you, to write custom script for specific webform, as there is no script section as we have in webpage.

**Comment by shreyashah115** [comment]
Sorry, that was a solution for DocTypes. Currently, there's no way to add a custom script to Web Forms.

**Comment by tundebabzy** [comment]
I'm closing this as this is not a problem with ERPNext/Frappe. @jigneshpshah you might be able to get some inspiration from the forum
