### ISSUE TITLE
Charts in Reports (extensions)

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#12781]
- [x] Button for Charts so its more visible
- [x] Change X axis
- [x] Multiple Y axis

**Comment by albertusgeyser** [comment]
Sound interesting. Any images of workings and looks of Charts?

**Comment by joolsr** [comment]
About a year back the only thing I really didnt like about ERPNext was the lack of Graphs in many Reports . This really is a game changer - very, very impressive !

**Comment by albertusgeyser** [comment]
When will charts be available in Production?

**Comment by netchampfaris** [comment]
@albertusgeyser 
We don't have a release date yet for v11.
