### ISSUE TITLE
Report Enhancements with Datatable for Query and Script Reports

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#12783]
- [x] Replace SlickGrid with DataTable
- [x] Feature parity
  - [x] Tree Structure
  - [x] Print / PDF
  - [x] Export
  - [x] Precision
  - [x] Chart

Extra Features
- [x] Hide columns and remember preference for user
- [x] Print filters

**Comment by turner-james** [comment]
Thankyou for initiating this! Let us hope that these enhancements will solve some of our problems to create acceptable customer statements from the General Ledger report.

**Comment by netchampfaris** [comment]
https://github.com/frappe/frappe/pull/5054

**Comment by snvora** [comment]
Great Step towards improving on reports...

Individual column filter is quick, easy and handy. Its widely used for random queries in everyday business. We hope to see that in new reports as well.

Eg:
![capture](https://user-images.githubusercontent.com/10496564/37700607-3a256468-2d12-11e8-82a3-7fbf1c5ba792.PNG)

**Comment by netchampfaris** [comment]
@snvora We have this feature in the new reports. To activate it you have to click on a cell and press `Ctrl/Cmd + F`

Maybe we should keep it enabled by default?

**Comment by snvora** [comment]
Thank you for the update :-)


> Maybe we should keep it enabled by default?

We use column filters more often rather than using the default report as such(like in more than 85% of reports queried). I am not aware of industry standard. If it's used often, its advisable to keep it as default.
