### ISSUE TITLE
Subscriptions Management Enhancements

### ISSUE THREAD

**Issue by Ooops-404** [frappe/erpnext#12797]
As per @umairsy request, I'm creating this issues as a feature request.

Originally posted in ERPNext forum: https://discuss.erpnext.com/t/manage-subscriptions-as-a-subscription-not-as-a-recurring-invoice/32105

The current system is messy, why not something closer to what programs like WHMCS, ClientExec, Blest, PayPlans or OSMembership do?

They all use the same core method which can be resumed in this way.

Client -> Subscriptions
Each client can have multiple subscriptions
Each subscription keeps an history of invoices.

How subscriptions are done.
-> Create a service
(options like)
-- Is it recurring?
-- Fee per billing term
-- Billing terms possible (x days, monthly, year, lifetime)
-- Trial term? (if yes, define the timeline)

How to Manually update a service
-> Client -> Subscription -> details (change whatever as an overwrite)

**Comment by binary64** [comment]
+1 to your exact plan! I love it.

Would this include Client Portal function to cancel a service, but have 2 options in the backend:
1. Continue service until end of term (or XX days notice)
2. Cancel immediately and pro-rata the difference.

**Comment by ryuliantoro** [comment]
Agree.
The existing subscription module/feature now points to subscribing to alert (payment, dll).
This should be renamed to Notifications.

And use the Subscribe for such as customer subscription.

**Comment by rmehta** [comment]
@Ooops-404 please try and add some mockups etc with specific design suggestions if you want this to be taken up with more interest.

**Comment by MichaelPinkowski** [comment]
+1

**Comment by littlehera** [comment]
Hi @Ooops-404 , sound's like a great idea! 
Also, Subscription should generate the invoice (not the other way around). Is their a team currently working on this one? We'd like to coordinate with them in order to make a PR for this feature.

**Comment by renzodemie** [comment]
Hello @Ooops-404 we are also planning to modify the current Subscription Doctype.

Here is the details of what we want to do: https://discuss.erpnext.com/t/subscription-modifications/34139
