### ISSUE TITLE
Loyalty Program

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#12790]
- [x] In Customer, select "Loyalty Program"
- [x] In Sales Invoice, fetch "Loyalty Program"
- [x] Issue "Loyalty Point" on Sales Invoice
- [x] Mode of Payment "Loyalty Point" in POS and Shopping Cart and Payment Entry

**Comment by jaqobk** [comment]
hi..
is this implemented in the latest release or not yet.?

**Comment by Muzzy73** [comment]
Is there any way of migrating loyalty points from previous system into ERPNext. Customers have many points which they want to redeem but we are not able to upload it without making new invoice.

**Comment by erpwala** [comment]
Hi all,
one little doubt
if more than 100 batches for the same item then how we can select or click???
or can we scan or type those batches in it ??
