### ISSUE TITLE
Batch & Item are not reflected properly during Batch creation

### ISSUE THREAD

**Issue by hdtmartin** [frappe/erpnext#12798]
During Stock Entry (Material Receipt), when creating a New Batch from the Batch field using "+Create a new Batch", the succeeding create window does not contain the correct values. The Item field contains the Batch field, instead of the Item to which the Batch should be created. On the other hand, the Batch field is blank when it should contain the new Batch to be created.

Kindly do a quick fix.

Thanks!

![se issue](https://user-images.githubusercontent.com/26181150/35891835-2d7af9fa-0be1-11e8-91ac-8c24f6de6dec.png)
![se issue2](https://user-images.githubusercontent.com/26181150/35891836-2dad88ca-0be1-11e8-9230-7ad1b617de5e.png)

**Comment by umairsy** [comment]
Not replicating in my test account.

![screen shot 2018-02-12 at 1 23 48 pm](https://user-images.githubusercontent.com/910238/36087348-0394ffb2-0ff8-11e8-991f-3305aa57f5e7.png)

If it is still replicating in your account, feel free to reopen this issue.

**Comment by hdtmartin** [comment]
Hi umairsy,

Thanks for looking into this.

However, it is still replicating in my account.

Hope you can fix it soonest as users are getting annoyed with it since they need to interchange the batch into the item field for every transaction they have to enter.

**Comment by rohitwaghchaure** [comment]
@hdtmartin 
No replicating issue in local account, do you have any local customizations in the batch or stock entry?
Kindly check is there any default value has been set in the item for the doctype Batch using customize form

**Comment by rohitwaghchaure** [comment]
Closing the issue as it's not replicated, feel free to reopen if issue still persists

**Comment by hdtmartin** [comment]
Hi Rohit,

Thanks for looking into this.

We don't have any local customization in the doctype batch or stock entry. However, this continue to bug our users.

I have attached here a recorded screen of the issue for your perusal. Should you need access into our environment just let me know, so I can give you account to peep into the issue.

![batchissue](https://user-images.githubusercontent.com/26181150/36402666-24bc2e6c-161b-11e8-9472-ce80f3566c86.gif)

Thanks!

**Comment by hdtmartin** [comment]
@umairsy @rohitwaghchaure 

This is still bugging us... 

Thanks for looking into this. Let me know if I need to create a new issue for this.

Regards,
Harold

**Comment by rohitwaghchaure** [comment]
@hdtmartin 

I have again checked and it's working properly, is there any user permission created in your account for doctype Item?

**Comment by hdtmartin** [comment]
There is no user permission created in doctype Item.

BTW, I have created a new instance https://jbme.erpnext.com. You may test from here using the following credentials:

Account ID: guest@gmail.com
Password: 12345

To replicate the issue, do the following:

a) Create a new Stock Entry.
b) Purpose: Material Receipt
c) Set Target Warehouse: Finished Goods
d) Set Item Code: Test Item
e) Set Qty: 1
f) Go to Batch No.
g) Input Batch: 12345 (or any Batch Number you may want).
      Don't forget to do this step before proceeding to the next step.
h) Click '+Create a New Batch' from the drop down menu.
i) Check on the next window. You will see that the batch number you have entered in step g is put under Item field instead of Batch ID field.

**Comment by hdtmartin** [comment]
@rohitwaghchaure 

Were you already able to replicate the issue? Thanks for your patience.

**Comment by hdtmartin** [comment]
Hope to get a feedback on this. This is still a concern of our users.

Thanks!

**Comment by rohitwaghchaure** [comment]
@hdtmartin 

Thanks for sharing the detailed steps, we've identified and [fixed](https://github.com/frappe/erpnext/pull/13281) the issue and we'll release the fix of this issue in next update. I am closing this issue now

**Comment by hdtmartin** [comment]
Thanks for your help @rohitwaghchaure! This will surely be a relief for our users.
