### ISSUE TITLE
ERPNext - Docs Generator Enhancement 

### ISSUE THREAD

**Issue by kennethsequeira** [frappe/erpnext#12794]
- [ ] Sectioning the docs (Create # hyperlink like GitHub)
- [ ] Breadcrumbs
- [ ] GitHub like sidebar for better navigation
- [x] Ability to search the documentation

**Comment by kennethsequeira** [comment]
https://github.com/frappe/frappe/pull/5558

**Comment by rmehta** [comment]
Seems fixed
