### ISSUE TITLE
Issue while creating User in ERPNext V10.0.19

### ISSUE THREAD

**Issue by ziagithub2018** [frappe/erpnext#12804]
Actual behavior: When I create a user with role supplier, then this user is being adds to customer list.
Expected behaveior: Created user with role of supplier should be listed in supplier list.

Example: 
created user: "user test"
applied role: "supplier"
if you check list of supplier their is no "user test"
"user test" is in the list of customer

![user](https://user-images.githubusercontent.com/36146142/35914424-dbca71c2-0c20-11e8-970c-4c48602c9d3c.PNG)

![role](https://user-images.githubusercontent.com/36146142/35914421-daa661ca-0c20-11e8-87b3-4c9f990415b5.PNG)

![supplier](https://user-images.githubusercontent.com/36146142/35914422-db391a10-0c20-11e8-8837-6021958c06df.PNG)

![customer](https://user-images.githubusercontent.com/36146142/35914420-da18dc4c-0c20-11e8-897f-08602c191913.PNG)

**Comment by kennethsequeira** [comment]
Supplier role does not add a user to the supplier list. You will need to add the Supplier manually through the Supplier master. 

The user you are creating will be able to submit RFQs to the system by default. Check the Portal Settings.

![screen shot 2018-02-08 at 11 42 55 am](https://user-images.githubusercontent.com/33246109/35958145-4795f4f4-0cc5-11e8-9817-3ac6e10fdf36.png)

**Comment by ziagithub2018** [comment]
Dear **kennethsequeira,**  Thank you for responding me! 
![portal](https://user-images.githubusercontent.com/36146142/35963066-28acd948-0cd1-11e8-9103-7ea85069baf6.PNG)


If supplier role does not add supplier to the list of supplier why it adds to customer list?  
If I add supplier manually, then what is the relation between created user (has supplier role) and the supplier which I create manually? 

My  portal setting is also OK (same as your screen shot).

**Comment by kennethsequeira** [comment]
@ziagithub2018 I tried replicating the issue by assigning user the role of **Supplier** but could not replicate it. Can you check if no other role is not assigned.

**Comment by ziagithub2018** [comment]
Mr. kennethsequeira Thanks for replying me!  I got the the problem
