### ISSUE TITLE
Automatic series select for Sales Invoices

### ISSUE THREAD

**Issue by turner-james** [frappe/erpnext#12815]
Our default series for Sales Invoices is INV-#####.

However, when it is a Sales Return, we need the series CN-##### to be utilised. The user has to manually change the series from INV to CN.

Is there a way  to automate the use of the CN series if the Sales invoice is a RETURN?

(The manual method to date has caused a number of our Sales Returns to be numbered as Sales Invoices (INV)!)

**Comment by snvora** [comment]
+1
We face similar issue

**Comment by kennethsequeira** [comment]
Return can be created against Sales Invoice or Delivery Note. It creates the same transaction (INV or DN)  with **Is Return** checkfield. There is no individual Sales Return Transaction at the moment. 

The workaround is probably what you have done, that is to create a naming Series CN for Sales Invoice and select that for Return. Perhaps you can also check the following field.

![screen shot 2018-02-08 at 10 51 38 am](https://user-images.githubusercontent.com/33246109/35956853-1eb5da92-0cbe-11e8-8927-49a4a9aa65a2.png)

But the downside to it is that user will have to select the naming series even when creating an invoice.

The only other way is to create an individual Transaction for it which comes with CN naming series.

**Comment by snvora** [comment]
@kennethsequeira 
It's a valid point. Not everyone may be using multiple series.

@turner-james 
Naming series can be made dependent on "is_return" from customising form easily.

**Comment by turner-james** [comment]
@snvora Thanks! Do you have any custom script to suggest - ie. if "is_return==1" then "naming_series==CN-#####". I just need someone to suggest the exact code I can use in the custom script for Sales Invoices?

**Comment by umairsy** [comment]
Closing this issue as it is not fixable in the ERPNext. Feel free to continue the discussion here or on the discuss forum.
