### ISSUE TITLE
not able to install fsevents

### ISSUE THREAD

**Issue by KaruguDev** [frappe/erpnext#12820]
After executing `bench update` my local erpnext is unable to run because of the above and the reason is show below

![image](https://user-images.githubusercontent.com/9849488/35958344-5c4f843c-0cb1-11e8-9607-0d5b03c3d922.png)

**Comment by binary64** [comment]
Well I don't know how to solve that, but how about install ERPNext on a supported platform, something like Debian 8. You could install Vagrant, or Docker, or Parallels, or pay $5/month for a VPS.

**Comment by binary64** [comment]
sudo?

**Comment by umairsy** [comment]
Please post this issue on the community forum.

https://disuss.erpnext.com

If validated as issue, we can re-open this issue.
