### ISSUE TITLE
Loan Management for the Members (non-profit)

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#12822]
Currently, Loan Application and Employee Loan is available for the Employees only. We will need to enable it for the Members as well. The Members are tracked in the non-profit module of ERPNext. Following are the re-write needed to make Employee Loan Application and Employee Loan compatible with the Members as well.

**Employee Loan Application**

- [x] Rename  "Employee Loan Application" to just  "Loan Application".
- [x] Add a dynamic link field. In the Doctype link field, show only two options, Employee and Member. Better if we can control visible of Member based on the activation of the non-profit module.

- [x] Patch for renaming doctypes and fieldnames

**Employee Loan**

- [x] Rename  "Employee Loan" to just  "Loan"
- [x] Just like in Loan Application, add a dynamic link field in the Employee Loan Doctype as well.
- [x] If Employee Loan is created for a Member, then hide field "Repay from Salary."

The loan and interest accounts selected in the Employee Loan will be based on the user's preference. Perhaps, in the Member master, we can give a link field for the Member Loan Account? Or there could be common Loan Account for the Party Type "Member".

**Disbursement and Repayment Entry**
- [x] Add a new button "Make Repayment Entry" to create a Journal Entry for repayment of loans. This button should be visible if party type is Member or in case of Employee, "Repay from Salary" is unchecked.
- [x] In repayment entry, credit loan account and interest account and debit bank account.
- [x] In the Disbursement / Repayment Entry, set Member as Party Type and party, against the Loan Account.

**Comment by kothagunda** [comment]
Awesome feature. This is very important for a Cooperative model.

**Comment by rohitwaghchaure** [comment]
We can rename field Employee Loan Account > Loan Account in the Loan Grants, no need to specify member loan account in the member master.

**Comment by kothagunda** [comment]
Can the Member docType dashboard display the basic loan info (total loan, balance) which were taken in the current fiscal year.

**Comment by umairsy** [comment]
In the Member's master, there will be a separate section added for Sales and Purchase details of that Member. In future, we can update sales and purchase related details of the members in these sections itself. If have data available right there, creating report and dashboard etc. should be simpler. Just a thought.

**Comment by kothagunda** [comment]
Hello @shreyashah115   is this feature now available in develop branch. If not, when will it be available. Pls let us know.
