### ISSUE TITLE
Unusable pop/imap with custom port

### ISSUE THREAD

**Issue by aleksas** [frappe/erpnext#12825]
IMAP server I have to use has a custom port for imap connection. For some reason pop/imap settings do not have the ability to set custom port parameter while smtp has.

Adding imap/pop custom port textfield would solve the issue.

env:
* ERPNext: v10.0.19 (master)
* Frappe Framework: v10.0.20 (master)

![image](https://user-images.githubusercontent.com/594470/35963735-53e0e324-0cbe-11e8-893e-db9a202b1320.png)

**Comment by umairsy** [comment]
Can you first check on the community forum if other users has faced same issue and handled it?

https://discuss.erpnext.com

**Comment by aleksas** [comment]
I did check community forum first, found nothing. Here is the [post](https://discuss.erpnext.com/t/unusable-pop-imap-with-custom-port/33648) - no responses.

**Comment by aleksas** [comment]
[New related discussion](https://discuss.erpnext.com/t/unusable-pop-imap-with-custom-port/33648)
