### ISSUE TITLE
bench start issue

### ISSUE THREAD

**Issue by shankargurutarikere** [frappe/erpnext#12826]
![screenshot 66](https://user-images.githubusercontent.com/31584520/35964588-3110c3da-0cde-11e8-91a9-05d897c2583a.png)

I have added site and installed erpnext app.I tried to start the bench using the command bench start.
I am getting this error.

**Comment by vishdha** [comment]
try bench setup procfile

**Comment by shankargurutarikere** [comment]
I have tried the commands that you have given still getting the same error.

**Comment by shankargurutarikere** [comment]
As per the discussion in the forum i am getting the error because the following files are configured.

redis_cache.conf
redis_queue.conf
redis_socketio.conf

I am not having any information regarding these files, Please tell me how can i access & configure these files.
