### ISSUE TITLE
Patient Barcode generation

### ISSUE THREAD

**Issue by mafrica** [frappe/erpnext#12834]
I will be operating a mixed paper and IT based medical records system for some years.  It would greatly help accuracy of data entry if I was able to print a series of patient data collection documents with an embedded barcode that links to the patient record.

I read that progress is being made in adding this feature in the context of product codes and the like but I am unclear if this is or will be available in Healthcare?

**Comment by umairsy** [comment]
If you want the barcode generated based on the value in the field, then you should be able to achieve it using the new field of type Barcode.

https://www.youtube.com/watch?v=aZYMOchuLJo

Also, in the Print Format, you can have specific field value being generated as a barcode. You might have to write additional HTML for it.

For further support on this, please post your query on the ERPNext community forum.

https://discuss.erpnext.com
