### ISSUE TITLE
description not in "copy fields to variant" table, but variant descriptions are rewrited

### ISSUE THREAD

**Issue by hiousi** [frappe/erpnext#12838]
When saving a master item, its variants description are rewrited despite the fact "description" is not in  "copy fileds to variant" table of item variant setting

to reproduce:
- remove "description" from  "item variant setting", save
- change a variant description, save the doc
- go to master item. Save.
- back to variant, description is changed with a list of <div>attributes : values.</div>

solution:
check the presence of "description" in item variant setting, before rewrite..
around line 208 of  erpnext/erpnext/controllers/item_variant.py

**Comment by umairsy** [comment]
This is a standard feature. In the variants item, the values of the Item Attribute is updated in the Item description for the reference of the customer/supplier.

**Comment by hiousi** [comment]
attribute is not copied to variant if attribute is not in "copy fileds to variant"
should I make a feature request for "description" to work the same as others attributes?
thank you
