### ISSUE TITLE
Credit Notes in the Advance Payment table

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#12846]
If Credit Note / Sales Return Entry is found for the Customer, then it should be fetched into the Advance Payment Entry table, so that it can be adjusted against the new Sales Invoice.

**Comment by federicocalvo** [comment]
Hi @umairsy, any new on this in V11?

would be related to these threads:
https://discuss.erpnext.com/t/correct-way-to-refund-a-customer-payment/33914/6
https://discuss.erpnext.com/t/allocate-credit-note-debit-note-to-another-sales-invoice-purchase-invoice/29329/11 

regards!

**Comment by ibrasec** [comment]
Any updates regarding this issue !

**Comment by AndyOverLord** [comment]
Hi there, 

Any news on this issue? I found in the methods of get_advance: 
we have get_advance_journal_entry and get_advance_payment_entry, is it possible and accounting-wise compatitble to add "get_advance_credit_note" in there?

That question will simply be "How do we recoginze the negative amount in sales invoice as credit?".

**Comment by Jacksoneasyway** [comment]
facing the same problem, waiting for answer

**Comment by Ponyooooo** [comment]
Is this feature request already release? We need to include the advance payment of credit note on the new sales invoice so that it will deduct the amount on the total outstanding print of the invoice for the client. I hope you can advise me about this. Thank you

**Comment by Mitchy25** [comment]
Why isn't this being considered? We have negative sales invoices that cant be allocated...

**Comment by f-9t9it** [comment]
@umairsy 
Can we know what happened to this issue ?
It is marked as completed but against which PR it was marked completed or maybe you can point me the solution

https://discuss.erpnext.com/t/allocate-credit-note-debit-note-to-another-sales-invoice-purchase-invoice/29329/29?u=fkardame
I have posted in forum but no one have replied on it so cross posting it here. 
Apologies for cross posting.
