### ISSUE TITLE
New docs aren't showing in list until I click 'Refresh' button or F5 the page

### ISSUE THREAD

**Issue by binary64** [frappe/erpnext#12840]
Latest develop version
I go to Projects > New > "test1" > Save
But I don't see the newly inserted item until I f5

Seems related to https://discuss.erpnext.com/t/page-and-doctype-loading-issue/16638/4

**Comment by binary64** [comment]
It only seems to affect doctypes with Quick Add like Projects and ToDo, but not Tasks or Leads..

**Comment by nabinhait** [comment]
We could not replicate the issue. Please reopen with exact steps if you still getting the error.
