### ISSUE TITLE
Bench start problem

### ISSUE THREAD

**Issue by shankargurutarikere** [frappe/erpnext#12841]
![screenshot 66](https://user-images.githubusercontent.com/31584520/36012199-97daf29e-0d82-11e8-9a71-39d3a65b9366.png)

As per the discussion in the forum i am getting the above error because the following files are not configured.

redis_cache.conf
redis_queue.conf
redis_socketio.conf

I am not having any information regarding these files, Please tell me how can i access & configure these files.

**Comment by umairsy** [comment]
Request you to post it on the erpnext community forum.

https://discuss.erpnext.com
