### ISSUE TITLE
Can not upload bulk stock reconciliation list via excel sheet (No reaction at all by the system). 

### ISSUE THREAD

**Issue by Denizbay** [frappe/erpnext#12850]
Any suggestions for non-programmers. Thank you!

**Comment by binary64** [comment]
Is this on erpnext.com, or self-hosted? If self-hosted, please give environment details

**Comment by Denizbay** [comment]
its erp-hosted, thank you.

**Comment by manassolanki** [comment]
Hi, in the stock reconciliation, you can only use the CSV file formats. (No support for the excel files)

**Comment by Denizbay** [comment]
nice one! but it also does not work in csv format

**Comment by manassolanki** [comment]
Please comment the steps to replicate the issue along with the screenshot and reopen the issue.
