### ISSUE TITLE
Error in retrieving email (from Gmail) - too many values to unpack

### ISSUE THREAD

**Issue by nimrodflores** [frappe/erpnext#12857]
We have configured a Gmail account inbox in our ERP - v10.0.13 (master)

From time to time, we get the following errors in the Error Log list.

Title: `receive.get_messages`

Error:
```
Error in retrieving email.
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/receive.py", line 242, in retrieve_message
    raw, header, ignore = message
ValueError: too many values to unpack
```

Community forum discussion reference: [[here](https://discuss.erpnext.com/t/email-pulling-error-too-many-values-to-unpack-from-gmail/28688)]

**Comment by umairsy** [comment]
Request you to post this issue on the community forum first.

https://discuss.erpnext.com

If it is validated as a bug on our side, we can re-open this issue.

**Comment by nimrodflores** [comment]
@umairsy , I've opened this issue upon the suggestion of a forum moderator back in the community forums. You probably missed the link to the forum thread I included in my opening post.

**Comment by rmehta** [comment]
Fixed via https://github.com/frappe/frappe/pull/5369
