### ISSUE TITLE
Multiple Barcodes

### ISSUE THREAD

**Issue by albertusgeyser** [frappe/erpnext#12855]
Good Day

Could you add Multiple Barcodes per product code in similer way as serial numbers are done?
We are invoicing variable kilograms linked to a barcode.

Example:

Product 1:

Barcode 201800001 - 25.00 Kg
Barcode 201800002 - 26.00 Kg

To select 2 items to delivery note: Total Items: 2 / Total Kg's: 51.00

To Invoice: 51.00 Kg @ Price

We are currently using Serial Numbers with custom fields for Kilograms, but can only invoice:

1x Unit @ Price

Thank You

Albertus Geyser

**Comment by umairsy** [comment]
Albertus,

This is not configurable for now. Please create two separate Item Code for each variant. You can also use Variants feature to manage it.
