### ISSUE TITLE
Handle a 'Left' Employee Gracefully when Others Report To That Employee

### ISSUE THREAD

**Issue by josmeldiaz21** [frappe/erpnext#12856]
I Updated to V10, I am having this message when I try to modify employee

> Item cannot be added to its own descendents.

[https://discuss.erpnext.com/t/cant-modify-employee-item-cannot-be-added-to-its-own-descendents/33060](https://discuss.erpnext.com/t/cant-modify-employee-item-cannot-be-added-to-its-own-descendents/33060)
This is the Issue.
![da600c67624f152c360b7ba7c46bd332018959a2](https://user-images.githubusercontent.com/4724780/36037414-170f6774-0d93-11e8-87ae-c39842b483a2.gif)
Version.
![e0f2c1d3fe94b7fb494f2a8be198db5f81014432](https://user-images.githubusercontent.com/4724780/36037459-38c95ba4-0d93-11e8-88d7-52d1b2aed421.png)

Log
`Traceback (most recent call last):
File “/home/frappe/frappe-bench/apps/frappe/frappe/app.py”, line 62, in application
response = frappe.handler.handle()
File “/home/frappe/frappe-bench/apps/frappe/frappe/handler.py”, line 22, in handle
data = execute_cmd(cmd)
File “/home/frappe/frappe-bench/apps/frappe/frappe/handler.py”, line 53, in execute_cmd
return frappe.call(method, **frappe.form_dict)
File “/home/frappe/frappe-bench/apps/frappe/frappe/init.py”, line 939, in call
return fn(*args, **newargs)
File “/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py”, line 22, in savedocs
doc.save()
File “/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py”, line 256, in save
return self._save(*args, **kwargs)
File “/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py”, line 307, in save
self.run_post_save_methods()
File “/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py”, line 887, in run_post_save_methods
self.run_method(“on_update”)
File “/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py”, line 755, in run_method
out = Document.hook(fn)(self, *args, **kwargs)
File “/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py”, line 1024, in composer
return composed(self, method, *args, **kwargs)
File “/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py”, line 1007, in runner
add_to_return_value(self, fn(self, *args, **kwargs))
File “/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py”, line 749, in 
fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
File “/home/frappe/frappe-bench/apps/erpnext/erpnext/hr/doctype/employee/employee.py”, line 60, in on_update
self.update_nsm_model()
File “/home/frappe/frappe-bench/apps/erpnext/erpnext/hr/doctype/employee/employee.py”, line 57, in update_nsm_model
frappe.utils.nestedset.update_nsm(self)
File “/home/frappe/frappe-bench/apps/frappe/frappe/utils/nestedset.py”, line 40, in update_nsm
update_add_node(doc, p or ‘’, pf)
File “/home/frappe/frappe-bench/apps/frappe/frappe/utils/nestedset.py”, line 64, in update_add_node
validate_loop(doc.doctype, doc.name, left, right)
File “/home/frappe/frappe-bench/apps/frappe/frappe/utils/nestedset.py”, line 181, in validate_loop
frappe.throw((“Item cannot be added to its own descendents”), NestedSetRecursionError)
File “/home/frappe/frappe-bench/apps/frappe/frappe/init.py”, line 323, in throw
msgprint(msg, raise_exception=exc, title=title, indicator=‘red’)
File “/home/frappe/frappe-bench/apps/frappe/frappe/init.py”, line 309, in msgprint
_raise_exception()
File “/home/frappe/frappe-bench/apps/frappe/frappe/init.py”, line 282, in _raise_exception
raise raise_exception(encode(msg))
NestedSetRecursionError: Item cannot be added to its own descendents`

**Comment by josmeldiaz21** [comment]
Some body can help us with this issue?

**Comment by Tropicalrambler** [comment]
Same here. Will look into it with our resources. Should not be happening.

**Comment by Olawale1** [comment]
Any update on this? Just encountered the same issue!

Kind regards,

**Comment by Olawale1** [comment]
We just updated to the latest version and this issue still persists! Can someone look into this or provide a workaround please? 

Kind regards,

**Comment by Olawale1** [comment]
Okay, I think I may have found the cause of the issue. The Employee was reporting to another Employee who had 'Left' the organization. Clearing the 'Reports To' field seems to have solved the issue

There should be a way for the system to handle this gracefully! An Employee's status should NOT be allowed to be changed to 'Left' if there are other Employees reporting to him/her

Thanks

**Comment by jaichavan** [comment]
Hello, @Olawale1 we will review and cater to this need in upcoming versions, hope you understand that there are many such feature requests in our path to an excellent product, and will always be! Thanks for pointing out.

**Comment by bhagyalaxmipn** [comment]
Hi Team,

I am getting the same error "Item cannot add to its own decendants" for 3 of the employee when i am adding any employee in its reports to field
Please suggest me what need to be done now.
For eg:- For employee A i need to add employee B as his reportee . but while doing this above error is coming
if i am removing reports to field as balnk then ERP is saving but i any how need to add employee B  in reports to fied for Employee A 
Please suggest.
