### ISSUE TITLE
GST Invoice reason_for_issuing_document defaulting to Sales Return

### ISSUE THREAD

**Issue by amitsaxena01** [frappe/erpnext#12859]
While creating a GST sales invoice in field reason_for_issuing_document defaults to "01-Sales Return" even if it is not a sales return. This field is required only in case Credit Note or Debit Note is issued. Moreover the field is not visible to make any changes.

**Comment by umairsy** [comment]
Is it a custom field?

If it is a select field, then ensure that first option in the list is blank.

**Comment by amitsaxena01** [comment]
@umairsy It is no customization, it is from the develop. https://github.com/frappe/erpnext/blob/develop/erpnext/regional/report/gstr_1/gstr_1.py
https://github.com/frappe/erpnext/blob/develop/erpnext/regional/india/setup.py

**Comment by umairsy** [comment]
Sorry for the issue. I see that for this field, default value set is 01-Sales Return. We will check into it on priority and update you when fixed.

**Comment by nabinhait** [comment]
removed that default value

**Comment by amitsaxena01** [comment]
@umairsy @nabinhait 
It still is not working. In sales and purchase invoices reason_for_issuing_document is still marked "01-Sales Return". The issues here are 
1. This is the field that is required for Credit Notes and Debit notes in GST GSTR 1A report and should not be shown on Sales/ Purchase Invoice
2. The default value of the same should be blank. There is no blank value in the list.
3. If it has to be in Sales/Purchase Invoice, it should be mandatory only if it is sales return otherwise it should not be mandatory.

-Amit

**Comment by nabinhait** [comment]
pushed a fix in develop branch

**Comment by nabinhait** [comment]
Which commands you use to update your system? If you are manually pull the changes, then you need to run `bench migrate`.
I have written a patch to remove the default and the field from mandatory. 
https://github.com/frappe/erpnext/blob/develop/erpnext/patches/v10_0/added_extra_gst_custom_field_in_gstr2.py#L13
