### ISSUE TITLE
Connecting Shopify to ERPNext

### ISSUE THREAD

**Issue by ziagithub2018** [frappe/erpnext#12862]
Problem in Shopify website: 
When I search ERPNext in Shopify app store it gives me "No matches for 'erpnext'."

Problem in ERPNext: 
I have already installed old version of shopify, I want to remove it and reinstall new, but when I click on remove button it gives me a popup like "Queued for backup and removing erpnext_shopify" but nothing happens. 

Please help !!

![erpnext](https://user-images.githubusercontent.com/36146142/36072734-6e10fbe0-0f42-11e8-87cc-0c8c60af39bb.PNG)

![shopify](https://user-images.githubusercontent.com/36146142/36072735-6e446a3e-0f42-11e8-962a-e3a657fb0422.PNG)

**Comment by ziagithub2018** [comment]
Mr. umairsy !

can you please tell me the solution, you just added to the integration label, I couldn't find similar issue in there. 
please! its very argent for me.

thank you

**Comment by saurabh6790** [comment]
@ziagithub2018  We are merging Erpnext Shopify app into ERPNext itself. But it will take couple of weeks.

If you are on self-hosted system, 
```
bench get-app erpnext_shopify https://github.com/frappe/erpnext_shopify
bench --site testsite install-app erpnext_shopify
```

And then setup shopify sync by following **Connect by creating a Private App** section http://frappe.github.io/erpnext_shopify/user/
