### ISSUE TITLE
I cannot delete a user

### ISSUE THREAD

**Issue by khaledYusufEG** [frappe/erpnext#12867]
I have a user was linked to an employee, I removed the user ID from the employee details screen, but I am still getting the below error message. The employee is still working in the company but with no longer as a  user on ERPNext, just an employee.
We are going to assign a new user to another existing employee..

Error message:
Cannot delete or cancel because User muhammad.haggag@lavaloon.com is linked with Employee EMP/0013

**Comment by PawanMeh** [comment]
Maybe you have some transactions done with the user id linked to the employee ID. If that is the case and you want to inactivate the user, you can uncheck the enabled checkbox.

![enabled_screen_shot](https://user-images.githubusercontent.com/20460498/36084009-cc38e0f6-0fde-11e8-8804-2c08dc2f267a.png)

**Comment by ziagithub2018** [comment]
Mr. khaledYusufEG !
When we create users and make them employee and those employees can be parents of another node.
If you want to delete, you should start from child to parent
1 - delete child
2 - delete parent
3 - delete parent of parent.
If you go to employee or user; in the top right corner there is a menu in that list there is a link if click on that link will show you the linked children. 

![capture](https://user-images.githubusercontent.com/36146142/36084049-dc31deac-0fd6-11e8-8158-2f7621cbee46.PNG)

**Comment by khaledYusufEG** [comment]
Thanks a lot
