### ISSUE TITLE
Website search engine is not working in ERPNext

### ISSUE THREAD

**Issue by ziagithub2018** [frappe/erpnext#12864]
When I search an item name or item code in the search box of product page nothing happens. 
Am I missed anything?

please help me.

![iph](https://user-images.githubusercontent.com/36146142/36073053-b93c7cb6-0f47-11e8-811e-3dc62f393474.PNG)

**Comment by PawanMeh** [comment]
I think the search works more on "like" behaviour than exact match. It would also search within the description of the item.

**Comment by ziagithub2018** [comment]
Mr. PawanMeh  thanks for replying me!
I'm sorry I couldn't get you, could you please tel me what to do to solve the problem 
when I type name or code of an item, items should be filtered.

**Comment by ziagithub2018** [comment]
hello !
Does any body can help me, Please !

**Comment by vishdha** [comment]
It's Working perfectly. Can you mention which version of Erpnext and Frappe you are using?

**Comment by ziagithub2018** [comment]
ERPNext v10.0.23
I just downloaded v10.1.4 here is samething (not working)
I don't know what is wrong. is there anything which I miss in Item registeration?

**Comment by shreyashah115** [comment]
Works fine. Hope you pressed 'Enter' or clicked on the search icon after filling up the search field?
![website-rep](https://user-images.githubusercontent.com/17617465/38073168-888f121c-3347-11e8-92a0-d2da92c1a862.gif)

**Comment by R-Gourav** [comment]
I am also getting the same problem search bar on website made through erpnext14, is not working on only item name but its working on web-item-001,etc. please give me a solution.
