### ISSUE TITLE
[feature-request] do not copy description to variant when description is not in "copy fields to variant"

### ISSUE THREAD

**Issue by hiousi** [frappe/erpnext#12877]
if "description" is not in setting "copy fields to variant" table, do not overwrite variant's description when saving the master template.

**Comment by umairsy** [comment]
Are you referring to the Item Attribute value updated in the Variants Items? If yes, that's something not copied from the Template, but updated on-save of the Variant Item itself. This is important for the Print Format which is shared with the Customer with variant details.

**Comment by hiousi** [comment]
Saving the variant do not overwrite its own description.
Saving the template always overwrite the variant's description. it adds a series of <div>attribute: attribute_value</div>
