### ISSUE TITLE
No Accruals in Account type

### ISSUE THREAD

**Issue by ekpott** [frappe/erpnext#12875]
@tundebabzy, How can Accruals be added as an option in Account Type

![screenshot](https://user-images.githubusercontent.com/7124097/36090809-002a6ef4-0fe2-11e8-9026-06a0cf047a81.png)

**Comment by umairsy** [comment]
If you set Receivable or Payable as account type, it will be treated as accrual account. For further support, please post your functional queries on the community forum.

https://discuss.erpnext.com
