### ISSUE TITLE
Add Account Receivable/Payable field in the Opening Invoice Creation Tool

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#12870]
Currently, it posts entries in in the default account like Debtor (for Account Receivable) and Creditor (for Accounts Payable). However, if a user customizes the Chart of Accounts and removes the Debtor and Creditor Account, then they get an error when updating invoices from Opening Invoice Creation Tool.

Please add a link field for the user to select Account Receivable or Payable account in the Opening Invoice Creation Tool.

**Comment by rohitwaghchaure** [comment]
![screen shot 2018-02-12 at 6 07 15 pm](https://user-images.githubusercontent.com/8780500/36097670-ed17dc3a-1021-11e8-8b2c-e1720af90124.png)

As user added the deleted chart of accounts in the default value of Credit To, they are not able to make an invoice from invoice creation tool
