### ISSUE TITLE
Standalone debit / credit note

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#12871]
Allow negative (return) Sales / Purchase Invoices without any reference.

Its outstanding will be maintained in the negative invoice itself.

https://github.com/frappe/erpnext/issues/8769

Implementation:

- [ ] remove validation that does not allow negative invoice without reference
- [ ] add test case

**Comment by jk2081** [comment]
I believe there may be some fields required to make it GST ready

**Comment by addymuliady** [comment]
I agree with @jk2081 ... will need to make provision for taxes as taxes are received to a different account, not income account

**Comment by creamdory** [comment]
Hi @rmehta , all!

We are currently in need of this feature and we would like to ask if this has been in development? If not, we would like to help though we must be clear of the requirement. Our suggestion is this:

- [ ] Add a "Type" select field with options "Sales Invoice" and "Credit Note" fro Sales Invoice and "Purchase Invoice" and "Debit Note" for Purchase Invoice.
- [ ] Remove validations that does not allow negative amount/grand total basing from the "Type".
- [ ] Add test cases.

If this is okay, we can jumpstart this one as we needed this asap.

Thanks!

Dori

**Comment by rmehta** [comment]
@nabinhait can you check?

**Comment by nabinhait** [comment]
@creamdory Thanks for your interest to work on this.

But @rohitwaghchaure has already started the development and he will send the PR within a week.

**Comment by creamdory** [comment]
That is great to hear @nabinhait ! Thanks a lot! 👍

**Comment by rohitwaghchaure** [comment]
@creamdory Have sent [PR](https://github.com/frappe/erpnext/pull/14269) for the same, kindly check

**Comment by creamdory** [comment]
@rohitwaghchaure , saw your PR and it is perfect! Hope to have that merged soon. Thanks a lot! :D
