### ISSUE TITLE
[feature-request] Abstraction layer for tax module

### ISSUE THREAD

**Issue by hieueastagile** [frappe/erpnext#12881]
Hi,

We are working on customizing the tax module of ERPNext, though we have done it by overriding a few current functionalities, we still find it isn't the correct way. So we are wondering if we can improve the tax module a bit and make it more extensible?

As we looked at the code in erpnext repository, it seems that ERPNext team are using the client-side code to calculate and update the taxes based on the predefined rules which retrieve from server side. This works for most of the cases but if the tax flow are something more customized, this approach might not work well. Can we move all the logic to the server side and make it able to inject a specific endpoint to be tax calculator? (or somehow abstract both client-side and server-side?) This will offer the ability to integrate the other tax services into ERPNext (for example: TaxJar or Avalara...). We think that something like this should work:
```python
# `transaction` should contain the information about the buyer, seller, lines of item, shipping rule (if any)
@whitelist
def calculate_tax(transaction):
   # we inject the tax service here somehow?
   tax_service = get_tax_service()
   return tax_service.caculate(transaction)
```

Can you guys take a look and let us know if it's possible? We are willing to help to open a few PR to get this done under your guidance.

Thank you and best regards.

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.
