### ISSUE TITLE
Optionally allow overlap on Timesheet

### ISSUE THREAD

**Issue by aleksas** [frappe/erpnext#12893]
In my company salary is calculated based on time spent at work in combination with time spent on differently valued projects. So consequently there is a need to *Optionally allow overlap on Timesheet*.

If I understand correctly in my scenario timesheet should allow activity overlap for the same timesheet, because that is what I was trying to do (see below).

![image](https://user-images.githubusercontent.com/594470/36145162-29fbbc24-10b9-11e8-9ec5-fea654f354bf.png)

But since I'm rather new to erpnext it maybe reasonable even in my scenario to also allow overlap between different timesheets.

See also:
[Discussion from May '17](https://discuss.erpnext.com/t/how-to-make-overlapping-for-timesheet/24054) and [recent discussion](https://discuss.erpnext.com/t/optionally-allow-overlap-on-timesheet/33824).

**Comment by tundebabzy** [comment]
See #13018

**Comment by sahilburman** [comment]
Need this, how to allow overlapping?

**Comment by tundebabzy** [comment]
Go to Projects Settings. Note that it hasn't been released yet (ETA about 2 weeks)
