### ISSUE TITLE
Address not shown in print format in Customer and Supplier

### ISSUE THREAD

**Issue by Hadi-Ti** [frappe/erpnext#12899]
Hello

Dear All,

Address and contact is not diplaying in Customer and supplier master when view print format.

I have made it by creating custom format usinh html but it shoul dbe there by default.

Thanks

Sarwar

![electrotel electrotel-supplier](https://user-images.githubusercontent.com/1536351/36150805-f5cc03ce-10d5-11e8-8ea1-e1e4ef515e49.png)
![electrotel electrotel-print](https://user-images.githubusercontent.com/1536351/36150807-f5f2fd8a-10d5-11e8-9fc5-13d8133ae768.png)

**Comment by umairsy** [comment]
Please post this issue on the community forum. https://discuss.erpnext.com

Also share the screenshot of Print Format Builder indicating the fields selected in the Print Format.
