### ISSUE TITLE
UAE VAT reports

### ISSUE THREAD

**Issue by nabinhait** [frappe/erpnext#12891]
- VAT Return
 - Excise Return
 - FTA VAT Audit File ([Test Data for VAT FAF.xlsx](https://github.com/frappe/erpnext/files/1481804/Test.Data.for.VAT.FAF.xlsx))
 - FTA Excise Tax Audit File ([Test Data for Excise Tax FAF.xlsx](https://github.com/frappe/erpnext/files/1481806/Test.Data.for.Excise.Tax.FAF.xlsx))

**Comment by jaichavan** [comment]
[VAT 201.xlsx](https://github.com/frappe/erpnext/files/2973540/VAT.201.xlsx)

#WN-SUP41105
