### ISSUE TITLE
Shopify setting Cannot be saved

### ISSUE THREAD

**Issue by ziagithub2018** [frappe/erpnext#12911]
I have installed erpnext shopify v2.0.25 in erpnext v10.0.21. 
when I save shopify setting it gives me an error popup  "Access token or Shopify URL missing in erpnext" I don't know what is the problem. 
and also I can't remove installed shopify when click on remove to reinstall it gives me this popup "Queued for backup and removing erpnext_shopify" i have waited for so long it didn't remove.

can anyone please help.

![capture](https://user-images.githubusercontent.com/36146142/36195025-aec577a8-1189-11e8-84db-fdf3b5e5494b.PNG)

![capture2](https://user-images.githubusercontent.com/36146142/36195193-577e27a0-118a-11e8-9021-c7cebf7ad641.PNG)

**Comment by umairsy** [comment]
The Shopify app from the Installer has been discontinued. You need not do it now.

For the first screenshot, please report issue on the community forum.

https://discuss.erpnext.com
