### ISSUE TITLE
[Bug Report][Human Resources] can't submit payrolls in "Payroll Entry"

### ISSUE THREAD

**Issue by ilyesderp** [frappe/erpnext#12919]
At the end of the month, when we want to make payrolls for all the employees we use Payroll Entry feature, it creates the payrolls successfully but when i click on submit payroll it doesn't submit and nothing happens, it's clearly a Bug.
In the console i get this error message:

Uncaught ReferenceError: submit_salary_slip is not defined
at eval (eval at setup (form.min.js?ver=1518450914.0:2636), :56:6)
at HTMLButtonElement._action (desk.min.js?ver=1518450914.0:3359)
at HTMLButtonElement.dispatch (jquery.min.js:3)
at HTMLButtonElement.$event.dispatch (report.min.js?ver=1518450914.0:3020)
at HTMLButtonElement.r.handle (jquery.min.js:3)
(anonymous) @ VM652:56
_action @ desk.min.js?ver=1518450914.0:3359
dispatch @ jquery.min.js:3
$event.dispatch @ report.min.js?ver=1518450914.0:3020
r.handle @ jquery.min.js:3

**Comment by shreyashah115** [comment]
Hi, we're not able to replicate this. It works just fine. Can you please tell us which version are you using?

**Comment by ilyesderp** [comment]
I'm Running ERPNext: v10.0.21 (master) and Frappe Framework: v10.0.22 (master).
Are you sure you understood me correctly? I will explain just to be sure: what i want is to submit all payrolls at once using Payroll Entry but "submit salary slip" button doesn't work, here is a screen shot:
![capture du 2018-02-14 18 13 51](https://user-images.githubusercontent.com/10146310/36218278-1a73a342-11b4-11e8-9fcb-bb9d63a60ab7.png)

**Comment by shreyashah115** [comment]
Tested on master, works perfectly. Closing the issue.

![payroll-validate](https://user-images.githubusercontent.com/17617465/36242289-093b7aa4-1241-11e8-9d25-718a1a26b994.gif)

**Comment by ilyesderp** [comment]
I fix it by updating the browser, sorry for the inconvenience.
