### ISSUE TITLE
Barcode Generation Error

### ISSUE THREAD

**Issue by kennethsequeira** [frappe/erpnext#12915]
With the current defaults present, we cannot generate the Barcode in ERPNext.

![screen shot 2018-02-14 at 3 53 16 pm](https://user-images.githubusercontent.com/33246109/36199837-c3d6ae2a-11a0-11e8-975f-59f4bd81494e.png)

Steps:

1. Enter barcode in item.
2. Customize form > Change field type of barcode from **data** to **Barcode**

![screen shot 2018-02-14 at 3 53 16 pm](https://user-images.githubusercontent.com/33246109/36199907-01091d14-11a1-11e8-8816-072d89be1cf8.png)

Only way to generate the SVG is to enable developer mode.

**Comment by umairsy** [comment]
Also, after saving an item, barcode value becomes something like this.

<img width="1014" alt="screen shot 2018-03-30 at 3 59 49 pm" src="https://user-images.githubusercontent.com/910238/38135023-81038e0a-3433-11e8-80b5-7e093082fcfe.png">

**Comment by pratu16x7** [comment]
Added a companion value field #5510

**Comment by bghayad** [comment]
Hello @pratu16x7 

`The ideal option would be to have two fields, one for value, the other for svg.`
So how to set the value field using js code? Because using frm.set_value is not working because it is setting the svg and not the value and that is wrong.

Regards
Bilal

**Comment by karthikeyan5** [comment]
> Also, after saving an item, barcode value becomes something like this.
> 
> <img alt="screen shot 2018-03-30 at 3 59 49 pm" width="1014" src="https://user-images.githubusercontent.com/910238/38135023-81038e0a-3433-11e8-80b5-7e093082fcfe.png">

this has been fixed with https://github.com/frappe/frappe/pull/7604
