### ISSUE TITLE
check sales invoice before submission

### ISSUE THREAD

**Issue by robertbecht** [frappe/erpnext#1291]
May be one could display the total and paid amount close to the safe/submit boron for reference.
Your doc’s are a kind of long, and this prevents the need to scroll down to check.

Another check/warning or processing option  could be something like “do you want the difference to become an outstanding amount or a write off”. This could be part of the box that as confirmation before submission

**Comment by rmehta** [comment]
@robertbecht is this still relevant? Feel free to re-open if you think its important.
