### ISSUE TITLE
Mac OS 10.13 Install Error

### ISSUE THREAD

**Issue by daniellorick** [frappe/erpnext#12922]
From the terminal:

"Sorry, the installer doesn't support macos 10.13. Aborting installation!
Install on macos 10.12 instead"

How can I adapt the installer to work on 10.13?

**Comment by kennethsequeira** [comment]
Did you use this script?
https://github.com/frappe/frappe/wiki/The-Hitchhiker%27s-Guide-to-Installing-Frapp%C3%A9-on-Mac-OS-X

**Comment by daniellorick** [comment]
I didn't see this documentation. It doesn't say that my version has been
tried and tested, but I will give it a go to see if it works.

Thank you,

Daniel

**Comment by kennethsequeira** [comment]
Either way @daniellorick, the steps and error log would help us to see what went wrong.

**Comment by daniellorick** [comment]
The Hitch hikers guide still led me to some errors. Today I am going to
uninstall everything, and try to go again at it with a fresh download.

**Comment by kennethsequeira** [comment]
@daniellorick if you face the errors again please post the error log. It'll be very helpful to debug!

**Comment by daniellorick** [comment]
Okay,

I'm new to a lot of this, but I will post things that I find.

Thank you,

Daniel

**Comment by rmehta** [comment]
@daniellorick please post installation issues at https://github.com/frappe/bench/issues
