### ISSUE TITLE
'Invoice' title needs to be replaced with 'Tax Invoice' for UAE companies

### ISSUE THREAD

**Issue by NBSys** [frappe/erpnext#12927]
Dear All,

How I can change the customer invoices title from 'Invoice' to 'Tax Invoice' in ERPNext?  I am very new to the system please assist if anyone can throw me some lights!!

Thanks and regards,
Prasad

**Comment by kennethsequeira** [comment]
@NBSys simply change the print format as shown below:

![tax_invoice](https://user-images.githubusercontent.com/33246109/36242568-b1edac98-1242-11e8-8706-2345907ef92d.gif)

It would be best to post these type of functional queries on the [community forum](https://discuss.erpnext.com) rather than GitHub. We use GitHub to primarily track issues, bugs, and feature requests.

**Comment by NBSys** [comment]
Dear Kenneth,

 

Thanks for sharing the information and didn’t know that it was quite easy! 😊

 

With best regards,

 


PRASAD T




 

Operations 

NIOBIZ Systems, P.B.No.78544

Dubai, UAE


M

T

E

W

+971 56 464 9216

+971 4 357 3820

contact@niobiz.com  

www.niobiz.com

 

	

 

 

CONFIDENTIALITY: This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error please notify the system manager. This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.

WARNING: Although the company has taken reasonable precautions to ensure no viruses are present in this email, the company cannot accept responsibility for any loss or damage arising from the use of this email or attachments.
