### ISSUE TITLE
[POS] Rounding issue and Unpaid Invoices Problem

### ISSUE THREAD

**Issue by OneiricIT** [frappe/erpnext#12926]
Hi,

ERPNext: v10.0.19 (master)

Frappe Framework: v10.0.20 (master)

Rounding enabled to $0.05

Created Sales invoice, added item with rate of $209.90 plus Tax of 10% on top totaling $230.89. Rounded Total is correct being $230.90. I create Payment entry against invoice, paid amount being $230.90. The invoice shows as Paid and all OK.

I go through POS - same customer - same item with same rate and same Tax totaling $230.89. Rounded Total correct being $230.90. On payment entry, it set the change amount to be 0.01 automatically which is not correct - but in any case, leaving that and submitting, the invoice shows as unpaid with Outstanding amount being $0.01 - looking further down the invoice, it shows the Change amount being $0.01 against the cash account (default for change). So in this instance, the automatic entry of change being $0.01 in payment entry is incorrect.

I then do exactly the same POS entry, except I delete the Change amount which then sets the Write off Amount to -$0.01. I submit this, check the invoice and again it is unpaid with $0.01 owing. There is a $-0.01 entry in the write off amount in the sales invoice.

So there is definitely an issue in the POS to do with rounding and indicating the invoices are unpaid. Also it does not matter if it is a discount or rate causing the rounding.

Can someone please advise? I cannot test on demo.erpnext.com.

Transaction performed through POS
![image](https://user-images.githubusercontent.com/22227933/36236776-11a22f3e-124c-11e8-97c9-970aa16a6be9.png)

Transaction performed through Sales Invoice ('Include Payment (POS) is not ticked)
![image](https://user-images.githubusercontent.com/22227933/36236791-27cf9bde-124c-11e8-8830-8ae4e6a87c01.png)

**Comment by rohitwaghchaure** [comment]
@OneiricIT 

This issue already [fixed](https://github.com/frappe/erpnext/pull/12773) in v10.0.20, pull latest update and check.

Closing this issue, feel free to reopen if issue still persists
