### ISSUE TITLE
Customer name does not appear in General Ledger

### ISSUE THREAD

**Issue by FlexsoftsTech** [frappe/erpnext#12937]
Dear Team
9 Persons of our clients in Saudi Arabia contacted me today regarding for party does not fetch data once they select Customer or any other party type
i tried it Arabic & English Interface in ERPnext 

![party does not appear](https://user-images.githubusercontent.com/33314211/36249665-70bb1bca-124c-11e8-89d7-7f32d18377c3.png)

**Comment by Zlash65** [comment]
The issue you're referring to has been fixed and merged https://github.com/frappe/frappe/pull/5012

**Comment by FlexsoftsTech** [comment]
@Zlash65 Thank you, Sir, for your clarification, still i cannot see party in the same client's instances 
is it required any actions in setup?
