### ISSUE TITLE
Bug in Purchase order After click Group same items.

### ISSUE THREAD

**Issue by maheshlangote1** [frappe/erpnext#12952]
When ever you add multiple same item with different Rate . Group Same Itesm in PO then it print the first item rate instead of average rate . 
![bug_po](https://user-images.githubusercontent.com/32509321/36258645-79af69e0-1281-11e8-9f39-3a7d96093565.png)

![bug_pf](https://user-images.githubusercontent.com/32509321/36258674-8da87720-1281-11e8-9a51-a46dbfb45523.png)

**Comment by kennethsequeira** [comment]
Couldn't replicate. What ERPNext & Frappe versions are you on? I'm using ERPNext: v10.0.23 (master)

Frappe Framework: v10.0.24 (master)

![screen shot 2018-02-15 at 7 41 47 pm](https://user-images.githubusercontent.com/33246109/36260888-b9d1879a-1288-11e8-8d87-337f72ceb7e4.png)

**Comment by jaichavan** [comment]
Hello, @maheshlangote1 does the issue still persist?
