### ISSUE TITLE
Refactor warehouse_account mapping

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#12955]
- [ ] In warehouse, if account is set, propagate it to all child accounts
- [ ] If account is blank, take default from company
- [ ] in new warehouse, if account is not set, set it from parent
- [ ] Don't build warehouse_account_map (query it from warehouse table, since the account name has been propagated to all children)
   - [ ] replace `warehouse_account_map` with `get_warehouse_account` (and cache it at request level)
- [ ] Patch to set `account` in Warehouse based on its parent

**Comment by nabinhait** [comment]
Fixed via #13454 , though did not implemented as per the above steps.
