### ISSUE TITLE
Leaderboard miscalculation and currency conversion error

### ISSUE THREAD

**Issue by niharRaut** [frappe/erpnext#12953]
- Total Amount shown on Customer Leaderboard calculates total amount of all invoices, not just submitted but also of cancelled status invoices.
-  Total Amount on Customer Leaderboard are shown in company's default currency but the currency conversion with customer's currency is not calculated. Meaning value is not picking from "Grand Total (Company Currency)"

**Comment by kennethsequeira** [comment]
@niharRaut erpnext and frappe versions?

**Comment by niharRaut** [comment]
Installed Apps
ERPNext: v10.0.23 (master)

Frappe Framework: v10.0.24 (master)

**Comment by Siddhisawant8** [comment]
@kennethsequeira I'll take up this issue

**Comment by vishdha** [comment]
https://github.com/frappe/erpnext/pull/12948
