### ISSUE TITLE
System not allows to rename the Item Attribute Value If variant is exist

### ISSUE THREAD

**Issue by saurabh6790** [frappe/erpnext#12967]
![notabletorenameitemattributevalue](https://user-images.githubusercontent.com/3784093/36297262-bde3d29a-1317-11e8-9549-b48d9712f241.gif)

**Comment by vishdha** [comment]
Hi @saurabh6790 It is not allowed because it's linked with variants. Even if I set allow rename in variant settings if the checkbox is 1 it will allow renaming item attribute value for a new variant but for the previous variant item whose stock ledger generated cannot be modified.

**Comment by cosimot** [comment]
Hi @vishdha ! I am actually allowed to change abbreviation but not attribute value, it is strange as abbreviation has more impact than attribute value, which is a description in fact...

**Comment by cosimot** [comment]
I think If changing abbreviation gives no problem also changing attribute value should not be a problem

**Comment by vishdha** [comment]
Hi @cosimot Why do you want to rename. You can directly add new attribute value.

**Comment by cosimot** [comment]
Hi @vishdha ! Correct typos or (in my case) changing from uppercase to lowercase. Can’t create a new attribute with same abbreviation. People can change their mind/needs or make mistakes!
