### ISSUE TITLE
[Bug] Deleting Child Table rows doesn't work

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#12964]
Issue replicating in gadgets.erpnext.com, in Portal Settings.

![portal-setting-issue](https://user-images.githubusercontent.com/910238/36295352-25a29a5c-130d-11e8-91d0-3b4cb0b3b548.gif)

**Comment by umairsy** [comment]
Also, there is no option to delete row manually as there is no Delete option in the modal.

![screen shot 2018-02-16 at 11 34 27 am](https://user-images.githubusercontent.com/910238/36295417-75d8fe62-130d-11e8-8a5d-1ab809011579.png)

**Comment by Zlash65** [comment]
![portal-settings](https://user-images.githubusercontent.com/11695402/37598037-181f730c-2ba7-11e8-9e48-da8aabbd75c0.gif)

Deleting a row from Portal Settings wont do any good as it'll sync back everything when migrate happens. Instead uncheck the Enable checkbox for the rows that need not be shown in the portal. Sync skips the enable checkbox and hence the settings would stick.
