### ISSUE TITLE
Issue in print style

### ISSUE THREAD

**Issue by ziagithub2018** [frappe/erpnext#12977]
In ERPNext v10.0.21
I wanted to change the style of all prints, i went to module 'printting/print style/modern', by mistake I didn't duplicate that, I unchecked standard option then saved now when try to print Sales order it gives me error, I'm not able to check the standard option back and save it. 
Please help me how to solve this problem.

![capture](https://user-images.githubusercontent.com/36146142/36338315-34fc5db4-13c9-11e8-8680-8f7a79285f55.PNG)

![capture5](https://user-images.githubusercontent.com/36146142/36338391-506fc4d0-13cb-11e8-86a7-d5076b67e147.PNG)

**Comment by umairsy** [comment]
Please post this issue on the ERPNext community forum, with a complete error report.

https://discuss.erpnext.com
