### ISSUE TITLE
VAT (Feature request) purchase invoice and sales invoice (KSA)

### ISSUE THREAD

**Issue by TetraComSA** [frappe/erpnext#12973]
@umairsy 

Hello,

We are based in KSA and we need to have the following feature urgently available in ERPnext.

**1. VAT per line individualy (Purchase invoice "applicable for service and inventory"/Sales invoice).**

**2. Sometimes, we receive couple of invoices from the same supplier that:**

1. Some are complete with VAT (Per line).
2. Some without VAT.

So, we want to book one voucher for both invoices above where we highly recommend having a feature that gives us an option either to apply VAT to the whole voucher equally or per line item.

<img width="728" alt="screen shot 2018-02-16 at 10 08 23 pm" src="https://user-images.githubusercontent.com/33566237/36324590-fc9acd2e-1365-11e8-975f-c23741a5b156.png">

**Comment by rohitwaghchaure** [comment]
@TetraComSA 
This is already implemented in the erpnext, below are two items in which one item has 5% vat and another has 0%
![screen shot 2018-02-17 at 12 08 47 pm](https://user-images.githubusercontent.com/8780500/36338670-6e9e2e0a-13db-11e8-85e3-4fc2ed8133f2.png)

**Comment by TetraComSA** [comment]
Hello @rohitwaghchaure @umairsy 

Thanks for your reply. I sent this request to ERPnext support and their reply was "this feature is not available". It seems the support team doesn't fully aware of their product. 

@rohitwaghchaure Can you please show us how manage it as I'm still beginner user....!! I tried to do it but the percentage was not accurate and also I want to know how to apply VAT for non-inventory purchase invoice...!!

Thanks again for your support.

**Comment by mhbu50** [comment]
@TetraComSA you have to define Sales Taxes and Charges Template and Purchase Taxes and Charges Template then add them in item master

**Comment by rohitwaghchaure** [comment]
@TetraComSA 
Can you please share the GIF? Will create same items and tax in my local system and will create the GIF  which shows you how to apply individual taxes in purchase invoice.

**Comment by TetraComSA** [comment]
@rohitwaghchaure 
Hello Dear, I appreciate your interaction and response. Sorry didn't understand about sharing the GIF? what you want to do exactly....!!

@mhbu50 Thanks. But I wanna have this option available to select while creating the purchase invoice (Stock or service).

**Comment by mhbu50** [comment]
@TetraComSA  after define Sales Taxes Template you have to define ITEM TAX in item master.
then when you create purchase invoice it will fetch all values

**Comment by TetraComSA** [comment]
@mhbu50 Thanks. But this is related to items (Stock). What if I have a service invoices from my supplier......!! There will be no item code to define or select.

**Comment by TetraComSA** [comment]
@rohitwaghchaure Please I need to have similar to your purchase invoice format. I tried to create items (non-stock) and I defined the tax related. When I create the purchase invoice it doesn't fetch the tax automatically, it seems I have to scroll down and select the TAX AND CHARGES field where it adds the 5% to all items.....
