### ISSUE TITLE
PoS duplicates invoices

### ISSUE THREAD

**Issue by olamide2** [frappe/erpnext#12971]
I am currently running ERPNext PoS in a high traffic environment with 8 concurrent PoS users.

I just noticed that some invoices are getting duplicated.

Cashier submits an invoice but two invoices are posted by the system within seconds of each other.

This affects 1 out of 15 records

The invoice numbers also follow each other (546, 547)

What could be responsible for this and how do we correct it?

I noticed that some other members are experiencing this issue and have discussed it on discuss.erpnext.

What can be done?

**Comment by saurabh-bhosale** [comment]
@olamide2 Can you share where shall I try to recreate this issue, Online POS or Offline POS?

**Comment by olamide2** [comment]
Online 
-------- Original message --------From: saurabh-bhosale <notifications@github.com> Date: 16/02/2018  15:40  (GMT+01:00) To: frappe/erpnext <erpnext@noreply.github.com> Cc: olamide2 <olamideshodunke@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [frappe/erpnext] PoS duplicates invoices (#12971) 
@olamide2 Can you share where shall I try to recreate this issue, Online POS or Offline POS?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/frappe/erpnext","title":"frappe/erpnext","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/frappe/erpnext"}},"updates":{"snippets":[{"icon":"PERSON","message":"@saurabh-bhosale in #12971: @olamide2 Can you share where shall I try to recreate this issue, Online POS or Offline POS?"}],"action":{"name":"View Issue","url":"https://github.com/frappe/erpnext/issues/12971#issuecomment-366253080"}}}

**Comment by Olawale1** [comment]
Hi @saurabh-bhosale 

This is not restricted to online POS, it's affecting offline as well!
![pos multiple invoice issue 1](https://user-images.githubusercontent.com/9269337/36333058-24abcb38-1375-11e8-9098-2dd89fbe07ad.png)

Thanks

**Comment by htharigo** [comment]
Can anyone help me with this problem
