### ISSUE TITLE
ERPNext connection with shopify via shopify private app

### ISSUE THREAD

**Issue by ziagithub2018** [frappe/erpnext#12979]
I have connected ERPNext with shopify by creating a private app in shopify account, but the problem is; data sync from shopify to erpnext but not vice versa. I have checked the option of 'sync with shopify' in the item details.

has any one done this before please share that.

Thanks

**Comment by umairsy** [comment]
Please post your queries on the discuss forum first. If it is validated as a bug or feature request, then only create Github Issue for it.
