### ISSUE TITLE
Taxes and Charges table not copying when converting purchase receipt to purchase invoice 

### ISSUE THREAD

**Issue by Tropicalrambler** [frappe/erpnext#12974]
On a purchase receipt a taxes and charges template is loaded manually and filled in manually. Purchase receipt is saved, adjusting the inventory and entering the valuation for inventory.

When user clicks "make" to convert purchase receipt to purchase invoice, the new purchase invoice copies the items and other data from the purchase receipt, BUT it does NOT copy the taxes and charges table.
   
**Expected Behavior**
Given that data is already entered in taxes and charges table, this data should copy over automatically.

**Comment by vishdha** [comment]
Hi @Tropicalrambler Can you specify on which version are you getting this error?
I replicate at my end it works perfectly fine

**Comment by nabinhait** [comment]
Can't replicate, seems like it has been fixed already. Please reopen if you are still getting the error.
