### ISSUE TITLE
DId a bench update ERPNext Mobile getting Application Error net:err_file_not_found (file:///ndex.html)

### ISSUE THREAD

**Issue by Rgottsch1** [frappe/erpnext#12987]

**Comment by sahilburman** [comment]
Getting the same issue after updating to V10.

**Comment by umairsy** [comment]
What is the OS of your mobile? On my mobile, after iOS upgrade, ERPNext started working fine once again.

**Comment by strixaluco** [comment]
Can't replicate on ERPNext 10.1.6, Frappe 10.1.2 and Android 5.0.2/MIUI 9.2.2.0

**Comment by sahilburman** [comment]
My error is coming after enabling 2Fauth

**Comment by Zlash65** [comment]
For Android, the app has been updated on Play Store which fixes this issue and also supports 2Factauth.

For ios, the app should be live in a week or so I guess. Its undergoing reviewing on their store.
