### ISSUE TITLE
Credit card default account should be debtors

### ISSUE THREAD

**Issue by skarthik3** [frappe/erpnext#12989]
For Credit card default account should be debtors account receivable but it does not allow us to select debtors
![image](https://user-images.githubusercontent.com/35178177/36353840-96111a9e-14f1-11e8-89e2-e47ccb532a78.png)

**Comment by umairsy** [comment]
Here, you can only select an Account of Type Bank of Cash for now. We will have to allow selection of the Receivable account for you to be able to select a Debtor account. 

Perhaps you can move the account of Credit Card under Account Receivable group. Seeing the group total will give you an estimation of total receivable.

**Comment by tundebabzy** [comment]
See #13029

**Comment by skarthik3** [comment]
thanks
