### ISSUE TITLE
Setting Desktop Icons

### ISSUE THREAD

**Issue by Rgottsch1** [frappe/erpnext#12986]
Some of the modudule access were name changes or removed that I had as desktop icons. Human Resources is now HR, Tools is no longer listed, Explore no longer listed in module access under user.  They cannot be removed from desktop icons, says "Human Resources not found.  THe application is not available:

**Comment by umairsy** [comment]
Which version are you working on? Please share the screenshot of the issues.

**Comment by Rgottsch1** [comment]
New version of ERPNext resolved.
