### ISSUE TITLE
ERP Internal Server Error 

### ISSUE THREAD

**Issue by alearns** [frappe/erpnext#12996]
PLEASE HELP! 

Upon opening my company's ERP Next site there is a message of "Internal Server Error." I'm assuming that is internal server error is from ERP Next's side. Can anyone tell me if this is being worked on as of 2/19/18? 

Thank you!

**Comment by umairsy** [comment]
Please post your query with the URL of your ERPNext account on the community forum.

https://discuss.erpnext.com

**Comment by clarkejj** [comment]
Here's the discussion umair https://discuss.erpnext.com/t/internal-server-error/34046/5

From their initial report alearns has not reported back whether self hosted with a  log entry traceback fro example...

**Comment by KenyanGeek** [comment]
@alearns try the following:

sudo nano /etc/systemd/system/mysqld.service

On the file change

#LimitNOFILE=16364
LimitNOFILE=40000

Then enter the following commands

sudo mysqld --tc-heuristic-recover=ROLLBACK
sudo service mysql start

Your application should now be up and running!!

**Comment by Muzzy73** [comment]
@KenyanGeek 
Thank you for the information. I did as you mentioned and the site came up.

**Comment by PedroKtu** [comment]
Hi, i try this solution but i have this response.---

starting as process 8989 ...
Aborted

Someone can help!

Tnks!!!1

**Comment by AliShaatani** [comment]
This Path in my machine is empty
 /etc/systemd/system/mysqld.service

Could the path had been changing for the the newer releases ?

I'm using V14

**Comment by innovatorfarman** [comment]
Yeah
