### ISSUE TITLE
Update  VM virtual image to UBUNTU 16.04 64 bit OS - yarn install Chromedriver not supported on 32-bit Linux + Python 3.6  not supported in UBUNTU 14.04

### ISSUE THREAD

**Issue by krnkris** [frappe/erpnext#12999]
As discussed in:

https://discuss.erpnext.com/t/update-problem-yarn-install-in-vm-virtual-image/34036

**Comment by sahilburman** [comment]
+1 on this, running system on a vm, face the issue on every bench update query

**Comment by krnkris** [comment]
Pyton 3.6 not supported in UBUNTU 14.04 if ERPNext will be ported to Python on the next releases.

**Comment by krnkris** [comment]
Thank you ERPNext team,
64-bit + UBUNTU 16.04 updated
