### ISSUE TITLE
Item Group permissions not working in Stock Balance Report

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#12995]
Hi,

A user only has permission to view certain Item Groups but when he opens the Stock Balance report, he can see all Item Groups!

Please fix

Thanks

**Comment by umairsy** [comment]
Can you please share if permissions has been applied on the report as well?

**Comment by Olawale1** [comment]
Hi @umairsy,

The permission I'm aware of for reports is role permission which only determines whether or not a user role can access the report. I have given that permission else the user would not have been able to view the report at all!

Thanks

**Comment by Olawale1** [comment]
By the way, the user is also restricted to seeing only Items where the Item Group is permitted. This works fine in the Item List but in the Stock Balance report he can see all items!

**Comment by Zlash65** [comment]
https://github.com/frappe/erpnext/pull/13069
