### ISSUE TITLE
Payment Exchange Rate is mandotary

### ISSUE THREAD

**Issue by federicocalvo** [frappe/erpnext#12998]
Hello, I detected an inconvenience which has not registered any threads in the forum, and I have tried several ways and instances to see if the problem was me.

When I make a payment, with a different currency than the default, and all the accounts are in this currency, it forces me to place a change of currency, which always generates a difference at the time of validating.

![captura de pantalla 2018-02-19 a la s 12 34 33](https://user-images.githubusercontent.com/7256766/36385897-c7c98f54-1572-11e8-8ad7-d1aa5720581b.png)

My currency is ARS, if I have a debit account in USD, the payment is in USD, and the target account is in USD, there should at no time be any conversion.

![captura de pantalla 2018-02-19 a la s 12 34 16](https://user-images.githubusercontent.com/7256766/36385940-eac57efa-1572-11e8-81cd-85d5ae326cb1.png)

Thanks!

**Comment by umairsy** [comment]
There will be conversion rate field for currency exchange rate, because the base currency for your account is ARS. Hence, if you select any account other than ARS currency, then Currency Exchange Rate would be fetched for it.

**Comment by federicocalvo** [comment]
@umairsy thanks for the comment. 

But if all the accounts involved in this payment are in USD, what I get is USD.

Therefore, the difference that it generates (which is because at the time of making the invoice, the conversion may have been different)is in excess since you do not get paid or take that money, you would only have to enter the USD that is charged on the invoice.

Greetings
