### ISSUE TITLE
Healthcare Patient Appointment Save Button Issue

### ISSUE THREAD

**Issue by mist-01** [frappe/erpnext#13016]
![appointment-error](https://user-images.githubusercontent.com/2146048/36466454-be3cac8c-16f3-11e8-83db-3ad1e4c3fe70.gif)

When I first create an appointment, there is no Save button.  However, if I clear the cache by using the "reload" option, the Save button appears.  Although the save button appears, I don't seem to be able to save.  Any changes I make to the doc are not persisted.

Arrived is a custom field.  Notes is not.  Both seem to save without error until I clear the cache at which point their values are gone.  Since Notes is a built in field and is not marked as readonly, I would expect my values to persist after clicking save.

It seems to me that the bug could be one of two things: First, maybe the doctype is meant to be readonly and the save button should never appear.  Otherwise, it seems that the save button is not working correctly.

I am running a fresh install of ERPNext on Ubuntu 16.04 installed via the install script.  I made a couple customizations to Patient Appointment, but before making the screencast, I "reset to defaults" on the customize page of Patient Appointment.

**Comment by kennethsequeira** [comment]
Could replicate on ERPNext: v10.0.23 (master) Frappe Framework: v10.0.25 (master).

**Comment by mist-01** [comment]
Can someone speak to what the intended behaviour is here?  Is the doctype supposed to be readonly?
