### ISSUE TITLE
ERPnext Chat issue on mobile devices

### ISSUE THREAD

**Issue by janecekmato** [frappe/erpnext#13013]
Hello, i have issue to show chat on mobile devices. When screen width is resized on pc or when i go through mobile phone, chat not showing properly and bottom half of screen is white. See screenshot. Its same on demo account at erpnext.com and virtual machine installed on my pc.  I tried find same bug report but not found similiar. 
<img width="395" alt="snimka obrazovky 2018-02-20 o 23 43 47" src="https://user-images.githubusercontent.com/12688336/36453465-626007ca-1698-11e8-9d32-8305a85ed0a6.png">

**Comment by achillesrasquinha** [comment]
The previous chat will be removed in favour of https://discuss.erpnext.com/t/erpnext-chat/33173
