### ISSUE TITLE
Telephony services' Integration in ERPNext

### ISSUE THREAD

**Issue by saurabh-bhosale** [frappe/erpnext#13012]
**Brief:**
Introduce a section named **Telephony Services** under **_'ERPNext Integrations'_** Module to integrate cloud telephony platforms that provide REST API support for their telephony services. **_Exotel_** is one such platform that can be integrated in ERPNext.

**General Objective:**
Use this integrated telephony service in ERPNext to:
1. log incoming calls as communications,
2. make outgoing calls,
3. capture post-call details

**Use case:**
1. Allows the Call Center/Helpline team of any Enterprise to effectively use ERPNext, by allowing them to create Lead/Issues directly from incoming calls.
2. Can be used in any Domain; to name a few, Services, Agriculture, Hospital domain in ERPNext can use it for making leads, Issue/queries and appointments respectively.

**Planned PR chunks:**
1. Exotel integration.
2. CRM Dashboard.

**Checklist:**
- [x] Exotel Integration     
  - [x]  Exotel Settings DocType for entering Exotel credentials(Exotel SID and Exotel Token).
  - [x] Whitelisted methods for:
    - [x] Incoming/Inbound Calls
    - [x] Outgoing/outbound Calls
    - [x] Post-call API to fetch,store call audio link from exotel
  - [x] Modify Communications to incorporate/handle Communications with communication_medium as _'Phone'_

- [ ] CRM Dashboard
  - [x] CRM Settings Doctype to enable/disable popup notifications on an incoming call.
  - [ ] _'Search priority'_ table on CRM Settings to set Doctype search priority to search the contact on every call (to make it flexible for use in different ERPNext domains).
  - [x] Manual search bar for contact number.

**Comment by kothagunda** [comment]
Very useful feature. Good going.

**Comment by dottenbr** [comment]
German provider offering API https://www.sipgate.io/en

**Comment by me2ne** [comment]
it's only for Exotel  or work with any asterisk base ip pbx

**Comment by jk2081** [comment]
Is this working?

**Comment by henrynewman** [comment]
Any Twilio integration coming up?

**Comment by rmehta** [comment]
Done via call popup (v12)
