### ISSUE TITLE
Uncaught Server Exception : adjust_qty_for_expired_items 

### ISSUE THREAD

**Issue by CPsol** [frappe/erpnext#13019]
![weberror](https://user-images.githubusercontent.com/36692638/36470743-ea758840-1726-11e8-8e36-6c6fca565329.png)
this what i did i got this error first install a server then change the port number then i explore more inside erpnext then put some sample items then i tried to update it last day you can see my post https://discuss.erpnext.com/t/bench-update-error-bench-utils-commandfailederror-git-pull/34061/5 
then

 after i found the way to update it. this pop up on my sample website button when i click products…

Uncaught Server Exception
Traceback (most recent call last):
File “/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py”, line 39, in render
data = render_page_by_language(path)
File “/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py”, line 133, in render_page_by_language
return render_page(path)
File “/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py”, line 149, in render_page
return build(path)
File “/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py”, line 156, in build
return build_page(path)
File “/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py”, line 169, in build_page
context = get_context(path)
File “/home/frappe/frappe-bench/apps/frappe/frappe/website/context.py”, line 28, in get_context
context = build_context(context)
File “/home/frappe/frappe-bench/apps/frappe/frappe/website/context.py”, line 89, in build_context
ret = context.doc.get_context(context)
File “/home/frappe/frappe-bench/apps/erpnext/erpnext/setup/doctype/item_group/item_group.py”, line 69, in get_context
limit=context.page_length + 1, search=frappe.form_dict.get(“search”)),
File “/home/frappe/frappe-bench/apps/erpnext/erpnext/setup/doctype/item_group/item_group.py”, line 109, in get_product_list_for_group
data = adjust_qty_for_expired_items(data)
File “/home/frappe/frappe-bench/apps/erpnext/erpnext/setup/doctype/item_group/item_group.py”, line 121, in adjust_qty_for_expired_items
qty = stock_qty_dict.stock_qty[0][0]
IndexError: tuple index out of range

**Comment by tundebabzy** [comment]
See #13045

**Comment by CPsol** [comment]
Other Solution. for this issue unchecked the Has Batch box in every product. Please see the image below
![sol](https://user-images.githubusercontent.com/36692638/36720087-ee847d82-1be1-11e8-849a-59d42af0a284.png)
