### ISSUE TITLE
Employee Advances - Summary Report 

### ISSUE THREAD

**Issue by shreyashah115** [frappe/erpnext#13024]
https://github.com/frappe/frappe/issues/5049

**Comment by erpuser** [comment]
Hi Shreya - Can you please confirm if this has this been updated in ERPNext? Thanks

**Comment by kennethsequeira** [comment]
@erpuser this has been merged into the develop branch #13040. It should be out in the next major release.

**Comment by kennethsequeira** [comment]
@erpuser #13040. This has been merged in the develop branch and should be out in the next major release.

**Comment by erpuser** [comment]
@kennethsequeira - Thank you for the update.
