### ISSUE TITLE
Customize Grid Table

### ISSUE THREAD

**Issue by effendyrizal** [frappe/erpnext#13020]
I want to create a new doctype as below
![foruma](https://user-images.githubusercontent.com/36693554/36471128-f363d396-171f-11e8-828e-4e1d67296d30.PNG)

so I’ve tried creating a new doctype and child table for my doctype
![formb](https://user-images.githubusercontent.com/36693554/36471911-b8b2166a-1722-11e8-9385-efed4f79b077.png)

but I have a problem,
I want to add more than 10 columns in the child of this table, and resize this coloumn width

I tried to fill in the column width but it remains unchanged
![apem](https://user-images.githubusercontent.com/36693554/36473037-ff471a64-1725-11e8-9947-e1c2f009d74a.PNG)

Could you guide my how to implement it?
or do you have any solution with my problem to add coloumn and resize coloumn width ?

Thank you

**Comment by rmehta** [comment]
The best way to implement this is using a custom HTML control. I don't think it makes sense to support this out of the box.
