### ISSUE TITLE
Merge Contact / Client / Address / etc. feature

### ISSUE THREAD

**Issue by gbard** [frappe/erpnext#13028]
This is a feature request!

In Odoo we loved the fact that we could select duplicates in list view and then "Merge" the two records and remove the duplicate.

This could be useful!

Thanks!

**Comment by dhav-d** [comment]
add Lead Source list into CRM > Setup
it exists somewhere untraceable currently can access in lead creation form

**Comment by gbard** [comment]
Not sure I understand what you mean. BUT! I found out that if we rename something and use an existing name, we can check "Merge with existing" and it does the trick. Would be easier to select the items in the list and click on a "Merge" button.

Thanks!

**Comment by joolsr** [comment]
You cannot Merge Opportunities though which would be very useful as they do get duplicated when auto created by a sales@ type mailbox
