### ISSUE TITLE
[Feature Request] Get Document Items Tool

### ISSUE THREAD

**Issue by giuseppelamatrice** [frappe/erpnext#13030]
# **Goal**
Create "Get Document Items" tool for transfer items from more documents to one document.

## **How ERPNext work:**
Creating Delivery Note from Sales Order with "Get Items button", I need to:
- manual update of quantity to deliver;
- manual delete of items that I don't want to deliver.
 
![erpnext - richieste alla community](https://user-images.githubusercontent.com/4445879/36499304-23b0b066-1741-11e8-92b2-8534d08193c3.jpg)

## **How ERPNext will work** 
For increase efficiency, I propose to:
- create a new button called "Get Document Items" 
- create a new modal for select items and insert new quantity to transfer in new document. 
In this way user update quantity to Deliver only.

![erpnext - richieste alla community 1](https://user-images.githubusercontent.com/4445879/36499307-24dc86e0-1741-11e8-9d9c-36003a86b917.jpg)

Great!

**Comment by giuseppelamatrice** [comment]
@kennethsequeira this tool is useful to all document (sales, purchase, production, ecc...)

**Comment by kennethsequeira** [comment]
@giuseppelamatrice tagged based on the description. I'll amend it just for stock then!

**Comment by sharmanakul** [comment]
closing it as this has already been incorporated inmany doctypes
