### ISSUE TITLE
How can a User Set their own Permissions?

### ISSUE THREAD

**Issue by Mohd200** [frappe/erpnext#13044]
I have Multiple users and multiple companies, and each day they work on a different company.
The Use Case Is:
The Accountant is working on multiple companies, creating invoices and new accounts under one specific company, then goes to work on a different DocType or Report. After that, the accountant does the same work cycle under a different company.
Which is why Filtering is not highly effective in this situation.

How can the users set their own User Permissions and not interfere with the other users’ permissions?
P.S: Can it be accomplished without involving the Administrator, or creating a new user just for User Permissions?

Thank You

**Comment by umairsy** [comment]
This is not configurable for now. Permissions are very critical and must be controlled by a system manager only. For multiple locations, you can create separate login ID for each and share with the same user if needed.

If User use Share functionality, then other user will be able to access that doc., even if no permission is assigned.

https://erpnext.org/docs/user/manual/en/setting-up/users-and-permissions/sharing
