### ISSUE TITLE
Member ID should be set on Member's Name of Naming Series

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#13048]
Currently, Member's ID is generated based on Email ID of the member. However, there could be a member who won't have email id.

- [x] Member naming based on Naming Series

**Comment by kothagunda** [comment]
Very useful for farmer members who don't have emails

**Will there still be any mandatory link from member to user doctype?**

Currently when a member is chosen as party type in a JE, the email shows up as the party.  And we can filter GL entry table based on email. 
Now i guess with this change we should be able to filter GL entry using the naming series, right?
Find attached the current screenshots during JE and GL entry. 

![je](https://user-images.githubusercontent.com/30433779/36656398-3e9b0088-1aee-11e8-9fbc-1cf7f00b5f3c.png)
![gl](https://user-images.githubusercontent.com/30433779/36656402-442ee0a0-1aee-11e8-8c95-c272d8ceada9.png)
