### ISSUE TITLE
Allow Production Order to be created with items that have valuation rate as 0

### ISSUE THREAD

**Issue by vijaywm** [frappe/erpnext#13052]
Use case:

Book is manufactured with paper supplied by client. 

- Create raw material with standard rate = 0 , valuation rate = 0
- Make Stock Entry (Receipt) for material received from client
- Create a Product & BOM for the Product with raw material created above
- Create Production order for the BOM, raw material created in step 1
- Start Production Order & make Stock Entry

![image](https://user-images.githubusercontent.com/4676890/36553471-66751ab8-1822-11e8-9def-1150d5ef40a3.png)

Cannot create Production order as required item has 0 valuation rate.

Required an option for 0 valuation rate in Production Order Item similar to Stock Entry Item

![image](https://user-images.githubusercontent.com/4676890/36555576-72422b3c-1828-11e8-9ccb-4ec792a08665.png)

If the field **allow_zero_valuation_rate** is created in Production Order Item, existing method in stock_entry.py will allow Stock Entry to be created when the flag is set to 1.

**Comment by osstechnolab** [comment]
I think this should be an Item setup?  There will always be items with 0 valuation rate such as obsolete items, items from scrap, etc.
