### ISSUE TITLE
[Bug] Item Image & Description not fetched in BOM Tree View

### ISSUE THREAD

**Issue by kennethsequeira** [frappe/erpnext#13075]
ERPNext: v10.1.4 (master)

Frappe Framework: v10.1.1 (master)

![screen shot 2018-02-23 at 8 14 32 pm](https://user-images.githubusercontent.com/33246109/36599809-89e18d60-18d6-11e8-8091-d7bfd5968827.png)

**Comment by Zlash65** [comment]
![bom-x](https://user-images.githubusercontent.com/11695402/36659551-dabce164-1afa-11e8-9718-7525b78c7c8b.gif)

Doesn't appear to have any error I think. Can you check it again ?

**Comment by kennethsequeira** [comment]
https://github.com/frappe/erpnext/pull/13099
