### ISSUE TITLE
Typing barcode numbers in POS search field

### ISSUE THREAD

**Issue by ryuliantoro** [frappe/erpnext#13073]
On POS page, when typing the barcode numbers in the search item field doesn't filter the items and find the matched barcode numbers. 
This will be a useful alternative when typing the name of item doesn't result to the intended item. 

![screenshot 2018-02-23 20 59 12](https://user-images.githubusercontent.com/13296444/36597722-a033e800-18dc-11e8-9146-9881182c3e99.jpg)

**Comment by kennethsequeira** [comment]
Working as intended. Please provide your ERPNext and Frappe versions too. I was able to search the item by typing the barcode.
