### ISSUE TITLE
[Bug] Sales And Purchase Analytics Graphs Not Generated

### ISSUE THREAD

**Issue by kennethsequeira** [frappe/erpnext#13084]
Sales Analytics works with "Months" filter initially. If you select Daily or Weekly No graph is generated. If you go back to Months again, no graph is generated.

![sales-purchase-graph](https://user-images.githubusercontent.com/33246109/36628844-29b9811a-1974-11e8-80fd-9c7b6c1d5498.gif)

ERPNext: v10.1.4 (master)
Frappe Framework: v10.1.1 (master)

**Comment by nabinhait** [comment]
We have intentionally did not show charts for weekly and daily. Because, the data is not shown properly, due to large number of columns.

**Comment by kennethsequeira** [comment]
@nabinhait if you check the gif, reports for purchase do not have graphs at all. Not sure if that is intentional.

Anyway, graphs are not generating if you select Daily, Weekly, and then go to Monthly, Yearly, Quartely.
