### ISSUE TITLE
Automatic Email Attached PDF does not contain letterhead

### ISSUE THREAD

**Issue by riyasrawther** [frappe/erpnext#13088]
After update the email with attached PDF does not contain any letterhead

commit 6a23461b4200daf4bafd4cbb54337d054f16da58
Author: Saurabh <saurabh6790@gmail.com>
Date:   Mon Feb 19 11:25:14 2018 +0530

    [fix] Send email with no letterhead if print letterhead is unchecked on print preview (#4816)
    
    * [fix] send email with no letterhead if print letterhead is unchecked on print priview

**Comment by riyasrawther** [comment]
After this update the email is being sent without letterhead

**Comment by umairsy** [comment]
There was some fix made on this front. Can you please update and check now?
