### ISSUE TITLE
Error in https://translate.erpnext.com/

### ISSUE THREAD

**Issue by krnkris** [frappe/erpnext#13083]
Error https://translate.erpnext.com/

Based on:

https://discuss.erpnext.com/t/error-in-https-translate-erpnext-com/34205

**Comment by kennethsequeira** [comment]
@krnkris a fix has been pushed. Can you verify if this is solved?

**Comment by krnkris** [comment]
Not yet

**Comment by krnkris** [comment]
Please update...

**Comment by lasalesi** [comment]
Still search function not working and letter slider missing...

**Comment by wojosc** [comment]
Also noticed this problem today. Stuck on the * page after login.

**Comment by krnkris** [comment]
Fixed by @achillesrasquinha

THX.
