### ISSUE TITLE
Allow zero valuation rate in BOM

### ISSUE THREAD

**Issue by ishanloya** [frappe/erpnext#13082]
At present when I add items to a BOM, there is a prompt 'Valuation rate not found for item _itemcode_'. If perpetual inventory is not being used, then the system should allow a zero valuation rate and not prompt the user each time a new item is added to the BOM.

![error](https://user-images.githubusercontent.com/17540310/36627141-7c1671a8-1964-11e8-95e2-25f35598bd77.png)

**Comment by creamdory** [comment]
@ishanloya , you just have to unchecked "Perpetual Inventory" in "Company" setting:

<img width="1223" alt="screen shot 2018-03-16 at 07 59 39" src="https://user-images.githubusercontent.com/21003054/37507695-306bc9c4-28f0-11e8-8d48-9e366edc59f8.png">

Though Valuation is Zero, it will allow you to submit BOM. The pop-up is just a warning message.

Unchecked "Perpetual Inventory" will allow you Start of Production Order with Zero Valuation Items.

![zero valuation](https://user-images.githubusercontent.com/21003054/37508348-f6cf62f4-28f2-11e8-9871-1fee9d8d6783.gif)

Checked "Perpetual Inventory" will NOT allow you Start of Production Order with Zero Valuation Items.

![zero valuation non perpetual](https://user-images.githubusercontent.com/21003054/37508374-0c0706cc-28f3-11e8-9e1f-1515cfb2d245.gif)

**Comment by ishanloya** [comment]
Hi @creamdory, we have perpetual inventory unchecked. When adding several sub items to a BOM, this can be a problem even though it's just a warning message since it displays each time an item is added to the BOM. So you can imagine that for a BOM with 100 items, it would be shown 100 times. As a workaround, we have entered valuation rate as 0.000001.
