### ISSUE TITLE
Send Purchase Order to Supplier Account

### ISSUE THREAD

**Issue by ziagithub2018** [frappe/erpnext#13081]
Hello
When Create purchase order I want to send that to supplier account. 
I have added a route in portal setting but the page purchase order does not exist. 
I'm looking at your help
Thank you

ERPNext: v10.0.21 (master)
Frappe Framework: v10.0.22 (master)

Portal setting
![portal](https://user-images.githubusercontent.com/36146142/36625494-2f36be4a-193e-11e8-85de-8e5114b6a697.PNG)

Supplier account
![account](https://user-images.githubusercontent.com/36146142/36625498-3f2fb95a-193e-11e8-8481-3c1454e9c361.PNG)

**Comment by umairsy** [comment]
It is based on Email ID selected in the Email ID of Contact. If a Supplier Signup with the same ID, then he/she will be able to view all the orders.
