### ISSUE TITLE
[Education] module, problem with "Fee Schedule" and "Student Category"

### ISSUE THREAD

**Issue by ilyesderp** [frappe/erpnext#13086]
In Education module when we create a new Fee Schedule, the Student Category of Fee Structure is not taken into account, and fees are created for all the students even if they are not part  of the student category.
Which means that right now, the only thing we can do using Fee Schedule is to create Fees for student Lots with the same fee structure.
@umairsy @manassolanki  please can you fix this?

**Comment by manassolanki** [comment]
hi @ilyesderp 
We have fixed the issue, please update your repo once PR will be merged.
