### ISSUE TITLE
Colors not display in calender

### ISSUE THREAD

**Issue by patilpuja** [frappe/erpnext#13092]

**Comment by joolsr** [comment]
Please provide further details, and ERPNext version as this isn't enough to go on

**Comment by umairsy** [comment]
Works fine in my test account.

![screen shot 2018-03-19 at 6 19 47 pm](https://user-images.githubusercontent.com/910238/37596429-248f74a2-2ba2-11e8-9b01-806664d7c02a.png)

Closing issue for now. Reopen if issue still replicates in the production instance.
