### ISSUE TITLE
Merge Guardian and Student link tables

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#13100]
Currently there is a child table for Student in Guardian and child table for Guardian in Student. This is redundant and leads to duplicate records.

Keep the child table only in one and write a patch to merge Guardian records if "Email Id" / "Mobile Number" and "Guardian Name" is same.

**Comment by manassolanki** [comment]
hi @rmehta 
There is a child table of guardian in students but not of students (child table) in the Guardian. In the guardian's form, that child table of students is populated on load and doesn't contain any data.
