### ISSUE TITLE
[BUG]  CRM user role permission for lead details report?

### ISSUE THREAD

**Issue by maheshlangote1** [frappe/erpnext#13104]
I have create few lead as CRM user , but when i click on report it display all lead report (Including other user, manger created report). my expected output is only display own report . So please help me hot to resolve it .
Please see the following attachment .
![lead_issue1](https://user-images.githubusercontent.com/32509321/36684785-6e475800-1b47-11e8-9b4e-680e2c60dce1.png)

![lead_issue](https://user-images.githubusercontent.com/32509321/36684793-77fd3f0e-1b47-11e8-9653-32a504463346.png)

**Comment by umairsy** [comment]
You will have to apply permission on the lead first. If they are able to view limited leads, they will see limited data in the reports as well.

https://erpnext.org/docs/user/manual/en/setting-up/users-and-permissions
