### ISSUE TITLE
LImit in creating one Delivery Note for one Sales Order

### ISSUE THREAD

**Issue by harrisonle** [frappe/erpnext#13107]
Follow below guideline "Set permlevel as 1 to the Qty, Rate field in sales order item, sales invoice item, delivery note item and using role permissions manager set the read and write permission to the manager role and other roles set read permission for permlevel 1. With this changes only manager role change the Qty/Rate and no other roles and therefore against each quotation there will be one SO and so on." but not show in priting the quantity .

**Comment by umairsy** [comment]
In the Delivery Note Item table, enable "Unique" property for the Sales Order link field.
