### ISSUE TITLE
sales invoice cancellation

### ISSUE THREAD

**Issue by pbtest15** [frappe/erpnext#13114]
one particular invoice, if we cancel, it says Cancelling and the screen remains the same for hours and nothing happens..

**Comment by kennethsequeira** [comment]
Can you share the error console? Also, the frappe and ERPnext versions would help.

**Comment by pbtest15** [comment]
ERPNext version v6.27.22
Frappe Framework v6.27.21
![screenshot 2018-02-27 15 37 06](https://user-images.githubusercontent.com/18395736/36722828-9cfd54be-1bd4-11e8-912f-ac490ece3658.png)

**Comment by kennethsequeira** [comment]
@pbtest15 perhaps the [forum](https://discuss.erpnext.com) will be a better place to post this? ERPNext is currently in Version 10.1 It would be best to update to the latest versions.

Also please post your browser console log there so members can help you. 

https://webmasters.stackexchange.com/questions/8525/how-do-i-open-the-javascript-console-in-different-browsers
