### ISSUE TITLE
How To Rename A Module In Erpnext?

### ISSUE THREAD

**Issue by shahid03351206668** [frappe/erpnext#13122]
In my scenario i want to rename a module "Contact" to "Operation Management"
please help me up & advise.
proper guiding persons will be highly appreciated.
Thanks in advance. :)

**Comment by ibrasec** [comment]
you could post your question on this forum https://discuss.erpnext.com/

**Comment by shahid03351206668** [comment]
I've posted but couldn't find enough.

**Comment by strixaluco** [comment]
As @ibrasec wrote, you should post this kind of questions to the forum and solution is already there: https://discuss.erpnext.com/t/updated-doctype-def-cleared-cache-bench-restart-still-not-refleceted/22580/8
