### ISSUE TITLE
GST POS Invoice not printing Customer Details.

### ISSUE THREAD

**Issue by shanmukhasai6** [frappe/erpnext#13134]
![image](https://user-images.githubusercontent.com/30374799/36786856-e161b45e-1cad-11e8-8ac9-ec0ac9296b8e.png)

GST POS Invoice not printing Customer Details after update to v 10

**Comment by saurabh-bhosale** [comment]
@shanmukhasai6 In newer updates, GST POS Invoice prints Customer's address only if the Invoice amount is greater than ₹ 50,000

**Comment by shanmukhasai6** [comment]
This is needed to be changed..

As some products need the customer address and details for the warranty proof of purchase to work.

**Comment by saurabh-bhosale** [comment]
@rohitwaghchaure To resolve this concern, what would be a good way to go ahead with? 
1. Have a checkbox _show customer details_ on POS Profile only for Indian Companies so that whoever needs the address can check this and go ahead with it.
2. Remove the condition limit of 50k from GST POS Invoice.

**Comment by saurabh-bhosale** [comment]
@shanmukhasai6 Can you consider the option of making a custom print format that is the exact clone of GST POS Invoice for your POS operations? 

In your custom print format you can remove the validation of 50k that is applied in newer versions.
