### ISSUE TITLE
Created doctype is missing, option custom is checked and erpnext v10 is in production mode 

### ISSUE THREAD

**Issue by ziagithub2018** [frappe/erpnext#13138]
Hello everyone

I'm not able to find created form when I create doctype
ERPNext is in production mode and the option ‘custom’ is checked i’m not able to uncheck that, when I create new doctype under any module ex; SETUB, and I applied the roles; doctype is created in the doctype list but I couldn't find the created form.
erp version is 10.^
please anyone can  help me

created doctype
![doctype](https://user-images.githubusercontent.com/36146142/36831124-052b7014-1d44-11e8-9d86-f4b4f80d3433.PNG)

Applied Role
![role](https://user-images.githubusercontent.com/36146142/36831139-1187b750-1d44-11e8-8875-bb2677c84fc5.PNG)

**Comment by umairsy** [comment]
To replicate this issue, I just added a Custom Doctype in the Setup module It. Appeared for me correctly at the bottom of Setup module.

![screen shot 2018-03-19 at 6 39 05 pm](https://user-images.githubusercontent.com/910238/37597253-e92ca3f0-2ba4-11e8-8459-bc95daf64d69.png)

Please check if you have roles assigned as defined in the Doctype. Closing this issue as it is not replicating for now.
