### ISSUE TITLE
Purchase order with zero rate?

### ISSUE THREAD

**Issue by toykraft** [frappe/erpnext#13131]
Why the system allows purchase order with zero rates? How to stop?

![screen shot 2018-02-28 at 5 19 15 pm](https://user-images.githubusercontent.com/35722521/36786202-877df850-1cab-11e8-9fb2-ffcbe16cf9e0.png)

**Comment by umairsy** [comment]
Incase you are receiving sample item etc. If you have approval/workflow mechanism, it should be addressed.
