### ISSUE TITLE
Groups not identifying properly in trial balance(Beta version)

### ISSUE THREAD

**Issue by rohitwaghchaure** [frappe/erpnext#13143]
**Issue**
![screenshot 16](https://user-images.githubusercontent.com/8780500/36887412-21e2f474-1e17-11e8-94fe-4a7575b27d6e.png)

**Stable version**
![screen shot 2018-03-02 at 12 35 44 pm](https://user-images.githubusercontent.com/8780500/36887421-2bcbd000-1e17-11e8-84f1-df584ff676b9.png)

**Comment by netchampfaris** [comment]
https://github.com/frappe/frappe/commit/2de3a6aacbf587b4ae7541032d09ccb022a2f77d
