### ISSUE TITLE
Pycache Modifications

### ISSUE THREAD

**Issue by kennethsequeira** [frappe/erpnext#13140]
Cache files are automatically modified/generated for frappe and ERPNext. Creates a problem when using `bench update`

![screen shot 2018-02-28 at 11 24 03 pm](https://user-images.githubusercontent.com/33246109/36837342-24f3a40c-1d62-11e8-9ea2-af71e2f72efc.png)
![screen shot 2018-02-28 at 11 26 05 pm](https://user-images.githubusercontent.com/33246109/36837344-252a39ea-1d62-11e8-8a42-800a910027b9.png)

**Comment by achillesrasquinha** [comment]
Is this always @kennethsequeira ? Can you just try this once again?

**Comment by kennethsequeira** [comment]
Yup, still happening 🤕

**Comment by achillesrasquinha** [comment]
Closing. Fixed.
