### ISSUE TITLE
[Feature / script request] Link user/employee to Activity Type

### ISSUE THREAD

**Issue by joopdo** [frappe/erpnext#13145]
Today I setup Activity types ('General' and 'Programmer') and Activity costs per employee in erpnext.

The behavior that I want is that Employee X can only see Activity Type 'Programmer', not 'General'.

My question

Is it possible (maybe with custom script?) to default to a activity type from General to Programmer for the employee name = X?

**Comment by umairsy** [comment]
You can achieve with using Role Permissions and User Permission Manager.

https://www.youtube.com/watch?v=8Slw1hsTmUI
