### ISSUE TITLE
[BUG] - Kanban view not showing tasks

### ISSUE THREAD

**Issue by madid87** [frappe/erpnext#13153]
Hi,
The view below shows kanban view of a project.
![bug_1](https://user-images.githubusercontent.com/33371535/36934328-ffbf2724-1ee7-11e8-9c47-038eeb107ae3.jpg)

It looks there are only three tasks with status "Open" and one with status "Working". The truth is that tasks are missing from view and they only show when I select 100 Tab below.
![bug_2](https://user-images.githubusercontent.com/33371535/36934333-20cab62c-1ee8-11e8-828a-198f4e974e3d.jpg)

**Comment by christophKi** [comment]
My kanban ony shows "undefined".

![bildschirmfoto 2018-03-04 um 13 26 23](https://user-images.githubusercontent.com/29779413/36945523-cce1f0b6-1faf-11e8-9776-547c0b044434.png)

**Comment by umairsy** [comment]
Works fine in my test account (screenshot below). @netchampfaris could it be related to translation.

![screen shot 2018-03-19 at 6 43 51 pm](https://user-images.githubusercontent.com/910238/37597470-8eea62b4-2ba5-11e8-9ea6-b9769d004f6d.png)

**Comment by christophKi** [comment]
No, still the same issue. Project kanban and tasks kanban works. I will check the database with an test installation and also import the database into an test installation. Maybe through this steps i will finde the issue. 
![bildschirmfoto 2018-03-19 um 22 14 29](https://user-images.githubusercontent.com/29779413/37622829-15eb64d0-2bc3-11e8-8b9f-d51598ba255f.png)

**Comment by netchampfaris** [comment]
@christophKi I could replicate the issue. Sent a fix.

**Comment by netchampfaris** [comment]
@madid87 Hi, the kanban list is paged, so you will have to click 100 or 500 to see all tasks

**Comment by madid87** [comment]
@netchampfaris I dont' undestand what that means. The Kanban view is not showing tasks unless you click 100 even though the column is only 30% full. How can this not be a bug?

Ivan

**Comment by christophKi** [comment]
Same here. Yesterday i pulled the newest version of erpnext. Still the same issue. 
If I click "500", there are just more undefined boxes. 
![image](https://user-images.githubusercontent.com/29779413/37702037-8b021e88-2cf1-11e8-88b8-679676f9ee8d.png)
Christoph
