### ISSUE TITLE
"PROMPT FOR EMAIL ON SUBMISSION OF" for Sales Invoice is broken

### ISSUE THREAD

**Issue by christophKi** [frappe/erpnext#13156]
Today I updated to ERPNext v10.1.4. 
When I submit the invoice, the "PROMPT FOR EMAIL ON SUBMISSION OF" does not come up.
It worked before the update and also does, when I submit a quotation.

**Comment by rohitwaghchaure** [comment]
@christophKi 
We have fixed this issue, kindly pull latest update and check
