### ISSUE TITLE
SEO functionallity webpage....

### ISSUE THREAD

**Issue by robertbecht** [frappe/erpnext#13159]
Header and description Webpage @rohitwaghchaure 

1. The description text is not copied to the description tag

2. Copying to header this:
meta name="description" content="essay over voordelen en nadelen van vers vlees voeding
meta name="keywords" content="voordelen vers voer hond, nadelen vers vlees hond

is changed in this after save...
meta name="description"
meta name="keywords"...so content is automatically removed on save

Overall believe we can learn from the big players...see eg
https://www.wix.com/blog/2014/09/12-seo-boosts-for-your-wix-website/

**Comment by kennethsequeira** [comment]
Added support to the blogs already, should be able to extend to the whole web module as well. https://github.com/frappe/frappe/pull/4948

**Comment by robertbecht** [comment]
Great....Feel free to use our website (dogsloveit) as testing
material....(as long as u dont mess up :) )

**Comment by umairsy** [comment]
Related issue - https://github.com/frappe/erpnext/issues/11442

**Comment by gmplab** [comment]
+1

**Comment by kennethsequeira** [comment]
@robertbecht 

The redesigned website module should take care of your requirements: https://erpnext.com/docs/user/manual/en/website/web-page#28-meta-tags
