### ISSUE TITLE
Total amount not showing in JE

### ISSUE THREAD

**Issue by Mohd200** [frappe/erpnext#13157]
Good Afternoon,
I am having a problem in the print form in Journal Entry.
Whenever I create a JE I'd want to print it. It shows in the Total Amount (in the print form "Standard") as 0.0
I tried it a second time with Identifying a party type, then it showed The Total Amount in the print form.
Not every JE has a party involved, so how can the Total Amount appear in the print form??
P.S. I made a customized print format and it's the same result.

**Comment by umairsy** [comment]
Then you can use Total Debit and Credit Field. You can change the label in the Print Format as per your need.

A net Total field is specific to the party where the value is calculated based on the total of the invoice.
