### ISSUE TITLE
Datatable - Sr. No. column and scrolling issues

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#13168]
![screen shot 2018-03-05 at 5 28 44 pm](https://user-images.githubusercontent.com/910238/36974025-2c7ad218-209b-11e8-8aea-853942fbab83.png)

**Comment by netchampfaris** [comment]
FIxed https://github.com/frappe/frappe/commit/50ee863914f5b0cb593e2223bc200af1092478d3
