### ISSUE TITLE
Linking Material Requests to Purchase Receipts/Purchase Invoices

### ISSUE THREAD

**Issue by Mohammedhilal** [frappe/erpnext#13164]
In ERP Next, is there a way of linking the Material Requests to Purchase Receipts/Purchase Invoices, as many cash purchases don’t have a Purchase Order. For such purchases, the status of their respective Material Requests is still “Pending”, due to no linkage between the documents (Material Requests - Purchase Receipts/Purchase Invoices).

**Comment by ahmed-madi** [comment]
What should the status of the Material Request be if Purchase Receipt or Purchase Invoice is submitted, 
is it should be "Billed" if the Purchase Invoice is submitted and "Received" if the Purchase Receipt is submitted? and when they cancelled should the status back to "Pending" ?, I'm really interested in such feature

**Comment by sharmanakul** [comment]
@ahmed-madi in case of cash purchase, i guess, it makes more sense to create a purchase invoice than the purchase receipt. And if the stocks are to be updated then that can be done from purchase invoice as well. 

Can you validate?

**Comment by wojosc** [comment]
Hi @sharmanakul this is already possible, right? (In Purchase Invoice)
![grafik](https://user-images.githubusercontent.com/22279621/142830166-f025e3f1-f89f-441f-9f07-5e2ec96d85e5.png)

**Comment by wojosc** [comment]
> In ERP Next, is there a way of linking the Material Requests to Purchase Receipts/Purchase Invoices, as many cash purchases don’t have a Purchase Order. For such purchases, the status of their respective Material Requests is still “Pending”, due to no linkage between the documents (Material Requests - Purchase Receipts/Purchase Invoices).

you should make sure to always have your Sales Orders and Purchase Orders in place if you can do so...

**Comment by sharmanakul** [comment]
@wojosc , i was asking for the direct linkage of MR with the Purchase Invoice.
why do you think the user should create PO against the MR.

The Original Poster wanted to avoid creating the PO against the Material Request.

**Comment by wojosc** [comment]
@sharmanakul and that's what I'm trying to say: Find a way to create the POs... :)
