### ISSUE TITLE
Leaderboard values are wrong

### ISSUE THREAD

**Issue by delinatie** [frappe/erpnext#13173]
Hello,

I made an invoice to a customer for 1457.06 € total. The leaderboard shows me a value of 1571.53 € for this customer for this timeframe. It should be 1457.06 €.

Any ideas why the correct value is not displayed?

Thank you

**Comment by olamide2** [comment]
I noticed that the leaderboard includes cancelled transactions.

Can you confirm if you have cancelled transactions for that customer

**Comment by delinatie** [comment]
Yes, I do have cancelled transactions. But those shouldn’t be included in the leaderboard?

**Comment by delinatie** [comment]
I’m also seeing errors in the P&L statements, and the balance. How can I rectify this? I believe it has to do with errors in stock and receipts.

**Comment by nabinhait** [comment]
Can't replicate the issue in my local. Can you please post some screenshots?

Or check if there are any future transactions (posting_date > today) made on the system?

Please reopen if you still getting the wrong value.
