### ISSUE TITLE
Flow error purchase?

### ISSUE THREAD

**Issue by delinatie** [frappe/erpnext#13171]
Hello,

I've noticed following behavior, which seems odd to me.

I make a purchase order based on a sales order. This purchase order is then received. From this purchase receipt I make a purchase invoice to close the flow.
The purchase receipt status gets updated to closed, however the purchase order status stays on 'to receive & bill'. Shouldn't this also get updated to closed?
I've also noticed that the percentage of received goods does not match reality. In this case, I accepted 5% more than ordered, and the purchase line says 83.85% received.

Where does it go wrong?

Thank you

**Comment by delinatie** [comment]
What is the correct procedure to close a purchase order when there are items missing in the delivery? Just close it?

**Comment by umairsy** [comment]
Can you check if Purchase Order ID was updated in the Purchase Invoice child table? Only if that happens, Purchase Order status will be updated.

Closing is the only option if you want to short-close the sales order.

Will be best to post functional queries like these on the discuss.erpnext.com, if it is validated as a bug or feature request, it should be created as a Github Issue here.
