### ISSUE TITLE
Chapter's web view. List of Members not published on the Website

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#13188]
Members selected in the Chapter

![screen shot 2018-03-06 at 3 30 29 pm](https://user-images.githubusercontent.com/910238/37026118-74bfec08-2153-11e8-981d-9ccc9e6ab027.png)

Members not listed in the web view

![screen shot 2018-03-06 at 3 30 44 pm](https://user-images.githubusercontent.com/910238/37026137-7ff3aa24-2153-11e8-964a-725612417dcd.png)

**Comment by shreyashah115** [comment]
@umairsy It's not actually a bug, is the enabled field in Chapter Member checked? It was caused because that field wasn't checked by default, have added the necessary fixes.
