### ISSUE TITLE
Use of item attributes w/o item variant settings

### ISSUE THREAD

**Issue by delinatie** [frappe/erpnext#13181]
Hello,

Would it be possible to use the item attributes functionality without activating the item variants setting?

I would like to use the attributes to define characteristics of the product itself, like:
- which primary, secondary & tertiary packaging material is used
- which allergens the product contains
- what colour it has
- what the flavour of the product is
- ...

Thank you for your advice.

Thomas

**Comment by umairsy** [comment]
No. You will have to enable Has Variants and select Item Attributes, and then create Variants finally.
