### ISSUE TITLE
Feature Request - Leave Allocation Tool using Date of Joining

### ISSUE THREAD

**Issue by bibinqcs** [frappe/erpnext#13184]
The option to allocate leaves with Start and End dates based on Date of joining of the Employee

**Comment by umairsy** [comment]
I believe it does factor in the joining date of the employee. Can you please also elaborate the usecase or steps following which you found this issue? It helps us get the context and set the priority.

**Comment by bibinqcs** [comment]
In the Leave Allocation Tool, 
At present we have the input start date which works if we set a static date say 1st of Jan. The issue is risen when we have to allocate based on the employee date of joining, in which case the cycle resets every year based on the day the employee joined the firm.
At present if we need to achieve this it is a complete manual process, if we have an option to select whether the leave allocation is based on date of joining software could copy the date of joining as the allocation start date and to date a year later.

**Comment by bibinqcs** [comment]
I am closing this, as this has been achieved with **Leave Policy Assignment** in v13 which has the option of _Assignment based on_ both Leave Period or Date of Joining
