### ISSUE TITLE
Add 0 value items in FIFO stack

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#13185]
these are not added currently

**Comment by rohitwaghchaure** [comment]
Fixed via
https://github.com/frappe/erpnext/pull/13432
https://github.com/frappe/erpnext/pull/13129

**Comment by schilgod** [comment]
Hi @rohitwaghchaure , @rmehta , @nabinhait 
Is this change only for FIFO valuation method? 
If yes,  The code should check for valuation method in #13432 

Because we use Moving Average and we are facing issue with valuation rate returning 0 because of this change.
