### ISSUE TITLE
patient cancel - delete option

### ISSUE THREAD

**Issue by shenoshadow** [frappe/erpnext#13190]
in healthcare - patient
there is no cancel or delete option 
to delete or cancel patients

**Comment by rkurungadam** [comment]
There is a hidden field 'disabled' in patient, you can customize patient to unhide it. Disabled patients are filtered out.

**Comment by shenoshadow** [comment]
i did that but its still a readonly field
i attempteted to uncheck the readonly 
But i got a message saying
You cannot unset 'Read Only' for field Disabled

**Comment by shenoshadow** [comment]
So i created a new custom filed and follow your suggestions

**Comment by rkurungadam** [comment]
Cannot reproduce the error, "You cannot unset 'Read Only' for field Disabled". Patient doctype can be customized to make field visible, please confirm.
Thanks

**Comment by shenoshadow** [comment]
you are true brother . thx a lot
