### ISSUE TITLE
Data Import Tool Error

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#13194]
Error when the user is trying to import

![screen shot 2018-03-06 at 5 50 22 pm](https://user-images.githubusercontent.com/910238/37031982-e1e3cbe8-2166-11e8-8b6a-1d04a43f1031.png)

Error when I tried to import file. I downloaded a new template, pasted data in the required columns and created import.

![screen shot 2018-03-06 at 6 04 17 pm](https://user-images.githubusercontent.com/910238/37032512-cf8d1a2e-2168-11e8-8265-3ca19ef60df6.png)

**Comment by umairsy** [comment]
Check issue no. WN-SUP31430 for the reference.

**Comment by manassolanki** [comment]
Issue fixed
