### ISSUE TITLE
Error in patch update_status_for_multiple_source_in_po

### ISSUE THREAD

**Issue by sagarvora** [frappe/erpnext#13191]
See:
https://github.com/frappe/erpnext/blob/develop/erpnext/patches/v10_0/update_status_for_multiple_source_in_po.py#L11

The sql query does not consider the possibility that 
**one sales order might have multiple sales order items with same item code**

This results in the following error:
pymysql.err.InternalError: (1242, u'Subquery returns more than 1 row')

Similar error may arise in subsequent query in same patch.

**Comment by sagarvora** [comment]
Possible duplicate of #13174

**Comment by aleoses** [comment]
Hi @sagarvora any updates of this issue?

**Comment by sagarvora** [comment]
Hi, there's a pending PR: https://github.com/frappe/erpnext/pull/13166
