### ISSUE TITLE
TypeError: Cannot read property 'js/libs.min.js' of null

### ISSUE THREAD

**Issue by umaepoch** [frappe/erpnext#13215]
While running bench update, I am facing this issue:

> frappe@ production /home/uma/frappe-bench/apps/frappe
> FRAPPE_ENV=production node rollup/build.js

Production mode
/home/uma/frappe-bench/apps/frappe/rollup/build.js:69
	const input_files = get_build_json('frappe')[libs_path];
	                                            ^

TypeError: Cannot read property 'js/libs.min.js' of null
    at build_libs (/home/uma/frappe-bench/apps/frappe/rollup/build.js:69:46)
    at Object.<anonymous> (/home/uma/frappe-bench/apps/frappe/rollup/build.js:23:1)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:387:7)
    at startup (bootstrap_node.js:153:9)

npm ERR! Linux 4.13.0-32-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "production"
npm ERR! node v6.13.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! frappe@ production: `FRAPPE_ENV=production node rollup/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the frappe@ production script 'FRAPPE_ENV=production node rollup/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the frappe package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     FRAPPE_ENV=production node rollup/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs frappe
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls frappe
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/uma/frappe-bench/apps/frappe/npm-debug.log

And, when I run bench start, I am getting these errors:

 > frappe@ watch /home/uma/frappe-bench/apps/frappe
16:40:34 watch.1          | > node rollup/watch.js
16:40:34 watch.1          | 
16:40:42 web.1            | 127.0.0.1 - - [07/Mar/2018 16:40:42] "POST / HTTP/1.1" 200 -
16:40:46 watch.1          | path.js:7
16:40:46 watch.1          |     throw new TypeError('Path must be a string. Received ' + inspect(path));
16:40:46 watch.1          |     ^
16:40:46 watch.1          | 
16:40:46 watch.1          | TypeError: Path must be a string. Received undefined
16:40:46 watch.1          |     at assertPath (path.js:7:11)
16:40:46 watch.1          |     at Object.resolve (path.js:1152:7)
16:40:46 watch.1          |     at get_rollup_options_for_css (/home/uma/frappe-bench/apps/frappe/rollup/config.js:107:18)
16:40:46 watch.1          |     at get_rollup_options (/home/uma/frappe-bench/apps/frappe/rollup/config.js:27:10)
16:40:46 watch.1          |     at Object.keys.map.output_file (/home/uma/frappe-bench/apps/frappe/rollup/watch.js:49:44)
16:40:46 watch.1          |     at Array.map (native)
16:40:46 watch.1          |     at get_watch_options (/home/uma/frappe-bench/apps/frappe/rollup/watch.js:46:4)
16:40:46 watch.1          |     at apps_list.map.app (/home/uma/frappe-bench/apps/frappe/rollup/watch.js:20:24)
16:40:46 watch.1          |     at Array.map (native)
16:40:46 watch.1          |     at watch_assets (/home/uma/frappe-bench/apps/frappe/rollup/watch.js:19:12)
16:40:46 watch.1          | 
16:40:46 watch.1          | npm ERR! Linux 4.13.0-32-generic
16:40:46 watch.1          | npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "watch"
16:40:46 watch.1          | npm ERR! node v6.13.1
16:40:46 watch.1          | npm ERR! npm  v3.10.10
16:40:46 watch.1          | npm ERR! code ELIFECYCLE
16:40:46 watch.1          | npm ERR! frappe@ watch: `node rollup/watch.js`
16:40:46 watch.1          | npm ERR! Exit status 1
16:40:46 watch.1          | npm ERR! 
16:40:46 watch.1          | npm ERR! Failed at the frappe@ watch script 'node rollup/watch.js'.
16:40:46 watch.1          | npm ERR! Make sure you have the latest version of node.js and npm installed.
16:40:46 watch.1          | npm ERR! If you do, this is most likely a problem with the frappe package,
16:40:47 watch.1          | npm ERR! not with npm itself.
16:40:47 watch.1          | npm ERR! Tell the author that this fails on your system:
16:40:47 watch.1          | npm ERR!     node rollup/watch.js
16:40:47 watch.1          | npm ERR! You can get information on how to open an issue for this project with:
16:40:47 watch.1          | npm ERR!     npm bugs frappe
16:40:47 watch.1          | npm ERR! Or if that isn't available, you can get their info via:
16:40:47 watch.1          | npm ERR!     npm owner ls frappe
16:40:47 watch.1          | npm ERR! There is likely additional logging output above.
16:40:47 watch.1          | 
16:40:47 watch.1          | npm ERR! Please include the following file with any support request:
16:40:47 watch.1          | npm ERR!     /home/uma/frappe-bench/apps/frappe/npm-debug.log
16:40:47 system           | watch.1 stopped (rc=0)

**Comment by pragex** [comment]
I have the same problem.

**Comment by netchampfaris** [comment]
@umaepoch Hi, please check if you have the "js/libs.min.js" entry in your `build.json`

**Comment by netchampfaris** [comment]
@umaepoch This has been fixed in the latest develop.
