### ISSUE TITLE
[bug] item weight details.

### ISSUE THREAD

**Issue by snvora** [frappe/erpnext#13223]
E.g.: 
Item A.
Stock UOM = Mtrs
UOM = Kg
So, in below example 11.6 Mtr = 19.14 Kgs

![capture](https://user-images.githubusercontent.com/10496564/37135622-19cd5d2c-22c4-11e8-888c-322957c55ccd.PNG)

Item Weight Details come up as below.

![capture_1](https://user-images.githubusercontent.com/10496564/37135643-33578c4a-22c4-11e8-87cc-1f2f16767d81.PNG)

Note: 1 Kg = 0.60606 Mtrs and 1 Mtrs = 1.65 Kg as can be seen from above clippings.

**ISSUE**
- Item weight details that are specified in Item should adjust with the conversion factor. i.e. `total weight` should be equal to the `weight per unit * qty * Conversion Factor`.
- Item weight should be linked to UOM Conversion table in item master. Currently in above example. we have stock UOM as Mtrs. So we had to specify item weight a 1.65 Kg and UOM conversion of KG as 0.6060606. Well, logically they both should be linked as 0.60606 = 1/1.65.

![capture](https://user-images.githubusercontent.com/10496564/37136113-323036bc-22c6-11e8-8803-d774e9c6e281.PNG)

Hope Issue is clear.

**Comment by shreyashah115** [comment]
The issue has been fixed.
