### ISSUE TITLE
Itemised GST register showing blank !

### ISSUE THREAD

**Issue by toykraft** [frappe/erpnext#13238]
Itemised GST register is showing blank !
![screen shot 2018-03-08 at 2 44 09 pm](https://user-images.githubusercontent.com/35722521/37142827-31feb3ee-22df-11e8-8244-1a690da74b3e.png)

**Comment by kennethsequeira** [comment]
Working on my end 

![screen shot 2018-03-09 at 4 55 33 pm](https://user-images.githubusercontent.com/33246109/37205417-bb735ffe-23ba-11e8-895a-814d000f05e7.png)

**Comment by umairsy** [comment]
Please post this issue on the discuss forum at first. If it is validated as a bug, we can reopen it again.
