### ISSUE TITLE
Add Memo/Note to a transaction in POS screen

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#13245]
Hi,

Ideally, there should be a way to include a Memo/Note with a transaction via the POS screen. This information (Memo/Note) should then appear in the Sales Invoice as a Comment

Please add this as soon as possible

Thanks

**Comment by Olawale1** [comment]
Another possibility is to create a new field in the Sales Invoice DocType for Memo/Note where this information can be mapped from the POS Screen

Thanks

**Comment by saurabh-bhosale** [comment]
@Olawale1 Yes, that sure is a way to resolve your issue. It will work this way, https://github.com/frappe/erpnext/pull/12465 I am about to make the said UI changes and reopen this PR soon.

**Comment by Olawale1** [comment]
Hi @saurabh-bhosale 

Thanks a great deal for this! Looking forward to the updated PR soonest

Cheers!

**Comment by Olawale1** [comment]
Hi @saurabh-bhosale 

It's been more than a month now. Any update on this?

Cheers
