### ISSUE TITLE
Ability to select the default month while creating the Salary Slip

### ISSUE THREAD

**Issue by manassolanki** [frappe/erpnext#13247]
HR setting can have one more option for selecting the "preferred default month" for processing the Payroll

**Comment by maheshengg** [comment]
Hi Manas, just an acknowledgement that I am following this issue, and am looking forward for this refinement that will make HR module lovable, likable, and more workable. Thanks !!

**Comment by maheshengg** [comment]
I feel this is not a feature-request but module improvement.
