### ISSUE TITLE
Suggestion for Fleet Management

### ISSUE THREAD

**Issue by ryuliantoro** [frappe/erpnext#13266]
Just a few suggestion from me in relation to the Fleet Management and Asset Management modules:

- [ ] Take the Fleet Management out of HR module and put it into Asset Management module.
Remove the Employee field from Vehicle doctype. So the Vehicle doctype is clean and only filled with vehicles information.

- [ ] Create new DocType called Vehicle Assignment to hold the assignment of vehicles to employees (the removed field above). Including the period of assignment and other terms and conditions.

- [ ] Give the role permissions of Vehicle Assignment to HR and Fleet Manager to create etc.

- [ ] This doctype can also be the request form from employee to request the use of the vehicle (in case of vehicle pooling) - permission to create and submit.

- [ ] These new forms of Fleet Management can be the same or separate with Equipment Management.

**Comment by PawanMeh** [comment]
This seems like a custom requirement. However, if you wish to enhance the Fleet Management module, kindly update the issue with few mock-ups / wireframe designs with fields you want to see etc and re-open.

**Comment by tefosn** [comment]
This is a good suggestion. Fleet management does not belong in HR
