### ISSUE TITLE
In education module Income account can't be fetched

### ISSUE THREAD

**Issue by ilyesderp** [frappe/erpnext#13267]
Hi @manassolanki @umairsy 
In Education module when we create new Fee we can't fetch income account, we have to go to chart of accounts and copy the desired account and go back to Fee and paste it, here is a screen shot:
![incomaccount](https://user-images.githubusercontent.com/10146310/37247562-3fb22edc-24bd-11e8-9a71-c2e3b1dc6304.png)

**Comment by Zlash65** [comment]
The Account that you want to fetch, is `account_type` set to `Income Account` ?
<img width="443" alt="screen shot 2018-03-13 at 3 06 45 pm" src="https://user-images.githubusercontent.com/11695402/37333791-3422d976-26d0-11e8-89ba-b64720c42d85.png">

**Comment by ilyesderp** [comment]
hi @Zlash65 
I fixed the issue, i was using the wrong account type that's why it didn't fetch
Sorry for the inconvenience
