### ISSUE TITLE
Multiple Cost Centers for Expense Claim

### ISSUE THREAD

**Issue by ushashmi** [frappe/erpnext#13264]
Currently we can only assign one cost center with expense claim. However, in practice one expense claim have claims associated with more than one cost center.

Is it possible to have cost center field available in every line of expense claim detail?

We tried adding a linked custom field of cost center which recorded the data but the impact is not transferred to General Ledger. So the custom field is of no use. 

Appreciate if cost center field will be available in each line and accounting entry is posted per line item

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.
