### ISSUE TITLE
Compliance with GST in Malaysia

### ISSUE THREAD

**Issue by alancheongkl** [frappe/erpnext#13268]
Will start develop a Module under GST-Malaysia to compliance with the local government GST requirements. The detail technical documents as attached.[
[GUIDE_ON_ACCOUNTING_SOFTWARE_08032018.pdf](https://github.com/frappe/erpnext/files/1828769/GUIDE_ON_ACCOUNTING_SOFTWARE_08032018.pdf)
](url)

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.
