### ISSUE TITLE
Bank Reconciliation: Convert to doctype and Include Reconciliation of Party accounts as well

### ISSUE THREAD

**Issue by adityaduggal** [frappe/erpnext#13261]
Hi,

There have been many cases where in several pages have been converted to doctypes in ERPNext like the below examples:

1. Data Import Tools changed to Doctype (for good)
1. Process Payroll changed to Doctype (for good)

Now I think its time we change Bank Reconciliation tool to a doctype, the benefits are enlisted below:

1. Suppose an organisation has many bank accounts then doing reconciliation of each bank account is a transaction an a user can attach the Bank Statement for that period for which he is trying to do reconciliation with each transaction. Currently with the tool this is not possible.

1. Organisations not only do reconciliation of bank accounts but also reconciliation of the Accounts of Supplier and Customer. If we make a doctype called "Account Reconciliation" then we can definitely do the reconciliation of the Party Types as well and attach the statement of customer's or supplier with the transaction. typically speaking this is a year end exercise which atleast our organisation does every year or quarter depending upon the quantum of transactions with a Party.

1. We could also make the transaction link it with a Subscription so that the system reminds us of the transaction every quarter or month or year as per the subscription

All the above are possible only if we convert the bank reconciliation tool into a doctype and make the requisite changes in the bank reconciliation report.

The following changes would need to be made in the BR Tool on conversion of it to a doctype:

- [ ] Convert Bank Reconciliation from Single to a Normal Doctype (Change Name to Generic One)
- [ ] Add fields for Party Type and Party Name
- [ ] Add Bank Reconciliation Doctype to Subscription for ability to create the BR automatically
- [ ] Change the Bank Reconciliation Statement Report to include Reconciliatoin for Party as well.

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.
