### ISSUE TITLE
Default Purchase UOM when Material Request Type is Purchase

### ISSUE THREAD

**Issue by ushashmi** [frappe/erpnext#13271]
We need to use default purchase UOM when material request type is Purchase. This works perfectly fine in Purchase Order but doesn't work for material request. 

I believe the code in erpnext/stock/get_item_details.py has this provision but for some reason its not working. 

Appreciate if this can be looked in

**Comment by ushashmi** [comment]
Is there any update on this?

**Comment by ushashmi** [comment]
Hi All 

Can someone look into this please

**Comment by rohitwaghchaure** [comment]
@ushashmi 

We have fixed this issue and will be release in version 11
