### ISSUE TITLE
Link error in report builder

### ISSUE THREAD

**Issue by Suprazz** [frappe/erpnext#13285]
I'm using the report builder to display the list of Purchase orders that I'm waiting for.
The first column is the ID of the PO so when I click on it, it opens the PO.

But sometimes, it displays the page you're looking for cannot be displayed.
It happens quite often in multiple different report builder.
Here is the wrong and good link. I dont know why is the link not builded correctly:
Wrong link when I click on the PO id: https://myerpnextaddress/desk#Form/Sales%20Order/PO-00336

Good link to the PO: https://myerpnextaddress/desk#Form/Purchase%20Order/PO-00336

I dont know why the Purchase was replaced by sales but this is the issue, and it happens from time to time.
I'm using google Chrome. Maybe it's a cache issue?

**Comment by Suprazz** [comment]
yes frequently. I'll try to find a way to replicate the issue

**Comment by Suprazz** [comment]
it's linked with the custom report when you do filtering.
How to reproduce:
1. Open purchase order custom report. 
2. Filter on one supplier
3. Go back
4. Open Sales order custom report
5. Filter on one customer
6 click on the sales order number in the ID colum to open it.
The page that will try to open will be /desk#Form/Purchase%20Order/SO-XXXXX instead of /desk#Form/Sales%20Order/SO-XXXXXX

Refresh the page by hitting F5. Filter again sales order with customer and it will work correctly

**Comment by luzpaz** [comment]
@Suprazz can you still recreate this issue ?

**Comment by Suprazz** [comment]
No it seems fixed!
