### ISSUE TITLE
[New Feature Proposal] Demand Driven Material Requirements Planning(DDMRP)

### ISSUE THREAD

**Issue by szufisher** [frappe/erpnext#13286]
Refer to this discussion post
https://discuss.erpnext.com/t/demand-driven-mrp-revolutionary-approach-to-planning/34387

**Comment by szufisher** [comment]
![overall structure](https://user-images.githubusercontent.com/12823863/38133592-77a5eba0-3442-11e8-8cfc-efacfd9d7cd4.png)

**Comment by rmehta** [comment]
needs to have detailed changes in design

https://github.com/frappe/erpnext/wiki/Preparing-a-Contribution-Proposal
