### ISSUE TITLE
When I change Roles in one Role Profile the changes effect to other Role Profile as well 

### ISSUE THREAD

**Issue by ziagithub2018** [frappe/erpnext#13299]
I have created two Role Profile named “Sales Suppervisor” and “Buying Suppervisor”, Why I cant apply two different Role? when I change “Sales Suppervisor” Role, the Role of “Buying Supperviser” also changes.
ERPNext v10.1.4
Please help me if I’m missing anything.
![1](https://user-images.githubusercontent.com/36146142/37385843-8d7a781e-2773-11e8-9d62-38e4d22e475b.PNG)
![2](https://user-images.githubusercontent.com/36146142/37385860-99c22356-2773-11e8-81b9-556d1ca64e65.PNG)

**Comment by rmehta** [comment]
You can only apply one role profile at a time. Maybe create a third one if you want a union of two role profiles
