### ISSUE TITLE
[bug] Outstanding amt in Payment Entry

### ISSUE THREAD

**Issue by snvora** [frappe/erpnext#13301]
**Issue:**
Outstanding amount getting updated on submit. As an effect Print format showing the incorrect outstanding amount.

**Before submit:**
![capture](https://user-images.githubusercontent.com/10496564/37386660-62521910-277f-11e8-87e6-3c41f1470b7b.PNG)

**After Submit:**
![capture_1](https://user-images.githubusercontent.com/10496564/37386678-71745002-277f-11e8-9378-210f2481fc9a.PNG)

ERPNext: v10.1.7 (master)

**Comment by tundebabzy** [comment]
See #12713 #12975

**Comment by snvora** [comment]
okay. I get it. Its designed to be that way.

Thanks :-)
