### ISSUE TITLE
[Bug] In French setup wizard

### ISSUE THREAD

**Issue by ilyesderp** [frappe/erpnext#13306]
Hi,
When i do a fresh install of ERPNext in french, in setup wizard when i try to create items i get an error, but i can create them after finishing setup wizard
I'm using ERPNext 10.1.13

**Comment by Zlash65** [comment]
How do you create items from setup wizard ?
As far as I know, setup wizard doesn't have a slide for adding items right ?

Those slides are visible through User Progress after the setup wizard.
Can you provide steps to replicate this ?

**Comment by ilyesderp** [comment]
Hi @Zlash65,
I'm using ERPNext 10.1.13, I meant User Progress after setup wizard, when i get to items when i create an item i get the bellow error:
![capture du 2018-03-19 16 42 20](https://user-images.githubusercontent.com/10146310/37606017-ce5d6cfe-2b94-11e8-8171-421dc9ed2b20.png)
this error message means: "Can not find Article Group: Products" which i think is translation related
