### ISSUE TITLE
Something went wrong Server Error: Please check your server logs or contact tech support.

### ISSUE THREAD

**Issue by Herbert6917** [frappe/erpnext#13317]
I am logged in online and get this message.  What should I do?

**Comment by achillesrasquinha** [comment]
Do what it states. Lol.

**Comment by achillesrasquinha** [comment]
To check the server logs, please check the log folder.

**Comment by Herbert6917** [comment]
I am using the online version.  I do not know where the logs are and I am not sure where tech support is either.

**Comment by umairsy** [comment]
Error logs are here.

<img width="1088" alt="screen shot 2018-03-30 at 12 26 06 pm" src="https://user-images.githubusercontent.com/910238/38127843-8e8a130a-3415-11e8-81da-27b5e17b1428.png">

If you have hosted ERPNext account with subscription, please post your issue on support@erpnext.com

**Comment by Herbert6917** [comment]
I do not have any error logs there.  See my screen shot.
![image](https://user-images.githubusercontent.com/16352068/38151338-bde38382-3430-11e8-9f18-8149b71397c0.png)
