### ISSUE TITLE
[Bug] We can't change language in System Settings

### ISSUE THREAD

**Issue by ilyesderp** [frappe/erpnext#13331]
When we change language from french to english in System Settings and after saving nothing happens and the language of the system stays french even tho it says english in System Settings.
I'm usin ERPNext version 10.1.13

**Comment by krnkris** [comment]
May be related to:
https://github.com/frappe/erpnext/issues/13351

**Comment by ilyesderp** [comment]
Hi @krnkris,
I don't think it is related.

**Comment by Zlash65** [comment]
Is this still an issue ?
Can you pull the latest and change the language and perform a hard reload and see if its effective or not ?

I tried it on my local machine and everything seems to be working.
