### ISSUE TITLE
Success Modals

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#13347]
- [x] Possible next actions
  - [x] Print
  - [x] Email
  - [x] New
- [x] Congratulations on the first transaction
- [x] Alert box like `frappe.show_alert` in the bottom right
  - [x] Dismissable
- [x] Only show success alert if current route is Form
- [ ] Permission based next actions
- [ ] "Don't show next time" check in the alert box
- [ ] Store settings based on user

**Comment by mhbu50** [comment]
@rmehta I think this features should be in frappe, not ERPNext!

**Comment by rmehta** [comment]
@mhbu50 yeah it will be in frappe ! but its better to maintain issue log in one place 😉

**Comment by mhbu50** [comment]
@rmehta That good news :smiley:, I said so because of I afraid to be like naming series.
In one of my frappe project's, I need to use naming series and I couldn't unless to get ERPNext get installed :flushed:
