### ISSUE TITLE
Translations for pt-BR not working on master after update

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#13351]
After updating today, translations arent working, the whole system is in english now, no errors are shown on console.

I'm using pt-BR as default language, it happened before and the "-" was the problem 

ERPNext: v10.1.13 (master)
Frappe Framework: v10.1.6 (master)

**Comment by krnkris** [comment]
Is this not related to:

https://github.com/frappe/erpnext/issues/13351

**Comment by Zlash65** [comment]
Is this still an issue ?
Can you pull the latest and change language and perform a hard reload and see if its effective or not ?

I tried it on my local machine and everything seems to be working
