### ISSUE TITLE
New Stock Entry Purpose: "Material Consumption for Manufacture"

### ISSUE THREAD

**Issue by creamdory** [frappe/erpnext#13368]
## Current State

Currently the only way you can book raw materials against a production order (consuming them) is by finishing a full or partial quantity of a production order. This does not reflect reality in which you will have to be able to consume raw materials against a production order while not yet finishing the product and keeping it as work in progress.

Instead of finishing a set quantity of an item within a production order and consuming the necessary raw materials (1:1), it would be best to allow feature to consume materials for manufacturing of a production order without booking a finished quantity. This may be necessary if certain operations are finished and require for materials to be consumed without creating a final product yet.

## Goal

- [x] Add new Stock Entry Purpose : "Material Consumption for Manufacture". 
This purpose acts like "Material Issue" but with attached Production Order. The consumed QTY must be recorded as well. Please see issue related here https://github.com/frappe/erpnext/issues/13369
- [x] Alter Stock Entry Validation for this purpose.
- [x] Add "Material Consumption" button in "Production Order/Work Order". Must appear if the production order is started. When the button is click, it should create Stock Entry with purpose "Material Consumption for Manufacture". User can use whether to click "Material Consumption" button or "Finish" button.

**Comment by djpalshikar** [comment]
When the user finishes the production order eventually, all the "Material Consumption for Manufacture" entries should affect "Stock valuation" of the manufactured item in some way.
