### ISSUE TITLE
Sales of Fixed Asset with Zero value - error on invoice value DR & CR values 

### ISSUE THREAD

**Issue by Midi1985** [frappe/erpnext#13366]
I have a transaction related to a fixed asset sale. The book value of the fixed asset is Zero (0) & I want to sell this at a cost determined by the management. When clicked on the “Sell Asset” of the particular item, it goes to a new invoice & CR a/c is shown as “Gain/Loss on Asset Disposal” & DR to Debtors. I inserted the amount of the sales value, filled other mandatory fields & clicked submit. then it says DR & CR values are not matching & difference is so & so amount (the rate of the item that i put)

Please help to resolve this

**Comment by Midi1985** [comment]
Can anybody advise weather this issue is fixed or not?

**Comment by rohitwaghchaure** [comment]
Hi @Midi1985 

I am trying to replicate the issue but not able to replicate it, can you please help me with the steps to replicate the issue, if possible please share the screenshots

**Comment by rohitwaghchaure** [comment]
As this issue is not replicated I am closing it now, feel free to reopen the issue if it's still persists and also please share the steps to replicate the issue.

**Comment by Midi1985** [comment]
Hi sorry its been so lng but the problem still persists
Pls find attached screenshot of the error. Truly appreciate re-opening the case & assisting on the same
![erpnext](https://user-images.githubusercontent.com/37651163/46257693-b68c0b00-c4c6-11e8-9bf5-0870c60b0594.PNG)

**Comment by Midi1985** [comment]
Hi sorry its been so lng but the problem still persists
Pls find attached screenshot of the error. Truly appreciate re-opening the case & assisting on the same
