### ISSUE TITLE
General Ledger is not running in Develop

### ISSUE THREAD

**Issue by umaepoch** [frappe/erpnext#13372]
Hi,

While running General Ledger report, getting this error in the browser console:

TypeError: erpnext.get_presentation_currency_list is not a function. 

I can see that this function is called inside general_ledger.js file.

What should be done to resolve this issue?

Regards
Uma

**Comment by umaepoch** [comment]
Hi,

Further on this, when I commented the line with options: erpnext.get_presentation_currency_list inside general_ledger.js file, the report works fine, but without a filter on currency.
Is this a new change? I had run a bench update yesterday and it had gone through properly. So, what could be the issue?

Thanks
Uma

**Comment by achillesrasquinha** [comment]
Try a `bench build`? And let me know if exists. It isn't replicating.

**Comment by umaepoch** [comment]
Hi,

Thanks for the response. I ran 
**bench setup requirements** 
and then 
**bench build,**  and everything seems to work fine now.

Thanks
Uma
