### ISSUE TITLE
Add option to export chart of accounts to .xls or .pdf file

### ISSUE THREAD

**Issue by williamjmorenor** [frappe/erpnext#13375]
Should be great to be able to get a report of the chart of accounts in .xls of .pdf file.

Some use cases are:

1. External Auditors ask for the report of the chart of accounts.
2. You need to give the report to new users 

This report is like the Balance report but with out numeric data.

**Comment by unmesh87** [comment]
COA file can be imported using Data import tool. Select Document type "Account" and click on download template button. On pop up dialog, user can select file type(CSV or Excel), with or without data. Checking if its same what you requested.

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.
