### ISSUE TITLE
URGENT!!! "Not saved", can't Validate

### ISSUE THREAD

**Issue by franciscobuendiao** [frappe/erpnext#13389]
Just updated to
ERPNext: v10.1.14 (master)
Frappe Framework: v10.1.9 (master)

Quotations, Sales Order, Sales Invoice, every document, if it isn't validate immediately, the status keeps as "Draft" (Not saved).

**Comment by franciscobuendiao** [comment]
Cloud accounts at ERPNext host have
ERPNext: v10.1.13 (master)
Frappe Framework: v10.1.6 (master)

**Comment by OneiricIT** [comment]
Same issue - everything is 'not saved'. Have to save the document first, then after changes are made select save then reload.
