### ISSUE TITLE
Landed Cost Voucher cannot be saved

### ISSUE THREAD

**Issue by kmhassan** [frappe/erpnext#13385]
Hi - anyone experiencing issues with Landed Cost Voucher?

Worked seamlessly until yesterday. Now, on the new Landed Cost Voucher page, after pulling Purchase Receipt details and inputting additional cost details when I press Save, it doesn't do anything. Tried reloading, etc, etc but no luck.

Installed Apps
ERPNext: v10.1.14 (master)
Frappe Framework: v10.1.7 (master)

**Comment by nabinhait** [comment]
Fixed it on the latest release
