### ISSUE TITLE
syncing the left and write part of the POS screen

### ISSUE THREAD

**Issue by robertbecht** [frappe/erpnext#1338]
When entering a invoice with many items one looses control (visual) of what is entered. One needs to scroll down, to see, or change quantity.

Two solutions occur to me: 
1) The  lowest record remains onscreen ( I guess this is difficult to code)
2) Allow an inversion of the item list, so the latest entry is on top

rgds robert

**Comment by joezsweet** [comment]
Closing now, please check last POS redesign and reopen if needed
