### ISSUE TITLE
Error Popup Cannot use sub-query or function in fields

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#13381]
When opening `Project Update` with no projects listed you get this error message:

![project update bug](https://user-images.githubusercontent.com/9136094/37831452-d56a7442-2ea5-11e8-9f5c-eaba630a006c.gif)

**Comment by ammarharara95** [comment]
I have made a pull request to frappe repo
https://github.com/frappe/frappe/pull/5278
if you want to solve it from ERPNext, you have to change the doctype name since it has **update** in its name, which makes it blacklisted when querying anything in it.
