### ISSUE TITLE
Can't update customer or invoice data for recurring invoices (subscriptions)

### ISSUE THREAD

**Issue by cudokmark** [frappe/erpnext#13397]
Hello,

We use subscriptions on some of our sales invoices to invoice our customers monthly, quarterly or half yearly. Unfortunately changes in customer data or invoice data aren't processed on the next invoice. For example:

- Customer address is changed. ERPnext doens't update the adress fields on the next invoice.
- Terms (text) are updated, ERPnext doens't update the terms.
- We made a new price rule for the customer, ERPnext doesn't update the item price on the next invoice. This is necessary for indexing prices.

Is there a way to force ERPnext to user new date or is this something that has to be fixed in ERPnext/Frappe?

Thanks.

**We use:**
ERPNext: v10.0.7 (master)
Frappe Framework: v10.0.8 (master)

**Comment by harshit-30** [comment]
Please use our [discuss forum](discuss.erpnext.com) for functional queries.
