### ISSUE TITLE
Bug in submit

### ISSUE THREAD

**Issue by fproldan** [frappe/erpnext#13408]
The documents can't be submitted after a change in field or child table

Steps to replicate:
- Create a new draft invoice and save, the validation button appears.
- Edit a field or child table and save, **the validation button does not appear anymore.**

ERPNext: v10.1.14 (master)
Frappe Framework: v10.1.9 (master)

Related post: https://discuss.erpnext.com/t/child-table-error-latest-v10/35243/2

**Comment by nabinhait** [comment]
We have fixed this yesterday.
Please reopen if you still get the error after updating to the latest.
