### ISSUE TITLE
Delivery Note Reference on Sales Invoice

### ISSUE THREAD

**Issue by Mishaal1021** [frappe/erpnext#13405]
Hi,

For Sales Invoices, usually the delivery note reference is required to be printed on the Sales Invoice. This is not a standard field in ERP, however, we have added it as "link - to Delivery Note" so that it can be printed on the Sales Invoice. This seems to work fine where there is 1 Delivery Note and 1 Sales Invoice. However, very frequently, we have multiple delivery notes that make 1 single invoice. I have tried few changes, but I can not get more than 1 Delivery Note to show on the Sales Invoice. Any assistance would be appreciated.

Regards,
Mishal

**Comment by umairsy** [comment]
Support Issue WN-SUP31913
