### ISSUE TITLE
Job Opening is breaking layout when entering HTML to Job Description

### ISSUE THREAD

**Issue by kaitorecca** [frappe/erpnext#13413]
Dear team,

Please check the List View of Frappe, as I enter the job description pasting from Word into Job Opening (Human Resource module), the layout is breaking as follow. 

As Job Description is in default list of Job Opening, I need to remove this field out of List View to make system work again.

![img_27032018_113639_0](https://user-images.githubusercontent.com/24359044/38016836-8095bff0-329a-11e8-8823-bdfdbfd9f748.png)

**Comment by netchampfaris** [comment]
Fixed in the latest develop

![image](https://user-images.githubusercontent.com/9355208/38309594-15831d2c-3838-11e8-831a-317cd1297b5f.png)
