### ISSUE TITLE
Bug in edit of project's child tasks table

### ISSUE THREAD

**Issue by fproldan** [frappe/erpnext#13426]
Hello,
We have experienced a bug in the project’s tasks child table when we edit it.

The step to reproduce is to have a project with two or more tasks.
In the project page edit the name for an instance of one task and save. The changed is saved and reflected.
Now edit the name of another task and save, the change doesn’t save.

In order to edit other tasks, you must reload the page!

ERPNext: v10.1.15 (master)
Frappe Framework: v10.1.13 (master)

![mar-28-2018 13-37-40](https://user-images.githubusercontent.com/4945122/38044986-b657aff8-3291-11e8-8870-084fa30a37ed.gif)

**Comment by umairsy** [comment]
Issue replicating in my test instance. Thanks for reporting.

**Comment by shreyashah115** [comment]
Hi @fproldan, we were not able to replicate the same on our local instance. Please reopen if the issue still persists.
