### ISSUE TITLE
Salary Slip Letterhead Issue

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#13440]
Hi,

Salary Slips automatically emailed to employees after successful submission via Payroll Entry do not contain the Letterhead! Emailing the salary slips individually from the system however works fine

Please fix urgently

Thanks

**Comment by rohitwaghchaure** [comment]
Hi @Olawale1 

Thanks for reporting an issue, have identified and fixed the issue and we'll release the fix in next week
