### ISSUE TITLE
Various Frappe tool apps: Popup error message - Chat token will be truncated: max 140 chars allowed

### ISSUE THREAD

**Issue by clarkejj** [frappe/erpnext#13441]
This same popup message occurs in several application tool instances as reported here 

https://discuss.erpnext.com/t/error-message-popu-on-chart-translation-frappe-website-max-chars-allowed-140/35331

**Comment by achillesrasquinha** [comment]
Oh, fixing!

**Comment by achillesrasquinha** [comment]
Thanks for pointing this out. :smile:

**Comment by achillesrasquinha** [comment]
In case of such errors, you can have it assigned to me.

**Comment by achillesrasquinha** [comment]
Fixed.

**Comment by clarkejj** [comment]
Thanks for your prompt attention to this!
