### ISSUE TITLE
[BUG] Online POS blank page on latest update

### ISSUE THREAD

**Issue by vladucoju** [frappe/erpnext#13448]
Hello,

after latest update i can't open pos page. Page is switching beetwen pages in the url pos/point-of-sale. Some kind of loop beetwen pages.

**Comment by rohitwaghchaure** [comment]
@vladucoju 
Are you using beta version or stable version?

**Comment by rohitwaghchaure** [comment]
Hi @vladucoju 

We have identified and fixed the issue, can you pull latest update and check
I am closing this issue, feel free to reopen if issue still persists
