### ISSUE TITLE
[BUG] "Stock Frozen Upto" in Stock Settings

### ISSUE THREAD

**Issue by creamdory** [frappe/erpnext#13455]
"Stock Frozen Upto" in Stock Setting is getting date today and cannot be updated. It always sets a date even deleting value. Getting below error during transaction that affects inventory.

![frozen stock](https://user-images.githubusercontent.com/21003054/38137069-c88a5c1a-3422-11e8-9b1b-c6f8fc35b75a.jpeg)

**Comment by kickapoo** [comment]
@nabinhait Any thoughts what cause this ? Even any idea so we can search on it?

**Comment by rohitwaghchaure** [comment]
@creamdory 
Kindly pull latest update and check

**Comment by rohitwaghchaure** [comment]
I am closing this issue, feel free to reopen if issue still persists
