### ISSUE TITLE
Error while installing erpnext manually

### ISSUE THREAD

**Issue by palashjhabak** [frappe/erpnext#13453]
Hi everyone,

I am getting a node module (chalk) error while installing erpnext manually using bench. I am using it on ubuntu 16.04. Can someone help ? Did anyone also get this issue or I am the chosen one :P 

Thanks in advance 

![image](https://user-images.githubusercontent.com/4964924/38135964-cca8398c-3438-11e8-9e31-837619f49d71.png)

**Comment by achillesrasquinha** [comment]
`bench setup requirements` should do the job.

**Comment by palashjhabak** [comment]
@achillesrasquinha hey thanks for the prompt reply. let me try it and update. :)

**Comment by achillesrasquinha** [comment]
if success, please close

**Comment by achillesrasquinha** [comment]
Please read the github.com/frappe/frappe/wiki Hitchhiker's Guides. Closing this.
