### ISSUE TITLE
Need to add supplier information to RFQ

### ISSUE THREAD

**Issue by ahmaeed123** [frappe/erpnext#13468]
![step-01](https://user-images.githubusercontent.com/37976215/38172438-25cac908-35b5-11e8-925e-674e4ce9a93e.jpg)
![step-02](https://user-images.githubusercontent.com/37976215/38172440-2aba3a20-35b5-11e8-8aba-d01d90098188.jpg)

Dears,
Greetings,

i tried to add supplier information from customize page , when i add it its not appear on pdf ?

**Comment by umairsy** [comment]
In RFQ, supplier is selected in the child table. please use that table for selecting supplier, address and contact value.
