### ISSUE TITLE
item tax not applied correctly amount wrong and calculation wrong

### ISSUE THREAD

**Issue by imllc** [frappe/erpnext#13460]
The 10.24 should be added to 129.00 not subtracted and further the amount is not correct it should be 140.13 or 11.13 in account setting show inclusive tax is off:

![wrongtax](https://user-images.githubusercontent.com/22771472/38163230-9fb6d59c-34be-11e8-94f6-dafd1af62435.JPG)

https://discuss.erpnext.com/t/sales-tax-deducted-from-total-instead-of-added-to-total-error/35334?u=imllc

**Comment by imllc** [comment]
This is now corrected but it doesn’t explain why we had to go in and toggle off Is this Tax included in Basic Rate? or why after working for a year it suddenly got turned on in the first place.

**Comment by umairsy** [comment]
Enable Track Changes for the tax template master, so that you can track who made changes.

https://erpnext.org/docs/user/manual/en/using-erpnext/document-versioning
