### ISSUE TITLE
Some Variables Doesn't Get Called Up in POS Print Format

### ISSUE THREAD

**Issue by ekpott** [frappe/erpnext#13462]
While other variables like {{ item.serial_no }} shows up, variables like {{ item.manufacturer_part_no }} doesn't show up in the POS print format.

![image](https://user-images.githubusercontent.com/7124097/38164859-d58c46fe-3502-11e8-9e12-37ebdcd7ef06.png)

![image](https://user-images.githubusercontent.com/7124097/38164988-9f1c655c-3504-11e8-8639-6458ac359f4a.png)

**Comment by umairsy** [comment]
Please post it on the discuss forum at first. If validated as a bug, we can reopen this issue.

https://discuss.erpnext.com
