### ISSUE TITLE
Expense Account in Stock Entry as per Item's Default Expense Account

### ISSUE THREAD

**Issue by Mishaal1021** [frappe/erpnext#13479]
Hi,

When we consume stock items, there is usually an expense related entry, hence we assign Default Expense Accounts for each Item.

This is great when item is directly sold to customer or when production module is being used. However, many times, stock items are issued for normal business. For instance printing supplies or consumable items for production floor. When we issue these thru a stock entry, the expense account for printing supplies and for consumables is different for accounting purposes. However, the system picks up the default "Difference Account" that is set at the company level. 

I would like to request that this be changes to Default Expense Account for each item to be more reflective. So far, we have been manually over-riding this, and have tried to add script in “Default” section or in “Options” section, but since Accounts data field is link, my changes do not get saved and/or reflected. I would really appreciate if this can be changed at the back end as I am sure most people will benefit from this. 

If there is a work-around for it, please let me know as well. 

Will appreciate your support on this. 

Regards,

Mishal

**Comment by sanjay-hercules** [comment]
try to define expense account at item level and check if it works.
![image](https://user-images.githubusercontent.com/34718633/38292687-3e1dfd0a-3802-11e8-887d-96241eb3260e.png)

**Comment by umairsy** [comment]
Mishal,

This feature is not configurable for now. Tagging as a feature suggestion.

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.
