### ISSUE TITLE
Product Bundle child table in Quotation

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#13473]
Ref.: WN-SUP32020

We are working on using the Quotation feature.

We wish to use Product Bundles in Quotations and have it display the list of items in the bundle to bring clarity to the scope of supply.

**Comment by prakashk22** [comment]
Hey Umair, When can we expect this feature.?

**Comment by Ponyooooo** [comment]
Do the quotation has this already? can this be linked to sales order also, wherein the product bundle be populated on the packed items of the sales order?
