### ISSUE TITLE
Problem: Within the  Chart of Accounts object there is no standard clone button.

### ISSUE THREAD

**Issue by jasonbrowne** [frappe/erpnext#13487]
Problem: Within the  Chart of Accounts object there is no standard clone button.

Cloning an account, would open an overlay with the account’s data pre-filled in all the account fields. You can edit some of the values in the fields and save the cloned account as a new account. This saves you from manually entering data when accounts share similar information

**Comment by umairsy** [comment]
You can duplicate button for Accounts?

**Comment by jasonbrowne** [comment]
Do not see duplicate button?

**Comment by jaichavan** [comment]
Hello, @jasonbrowne thanks for reaching out with the suggestion, we will definitely review and undertake the development of this if it's feasible for the project and user experience. Stay tuned!

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.
