### ISSUE TITLE
[BUG] POS freeze when  rate button pushed

### ISSUE THREAD

**Issue by vladucoju** [frappe/erpnext#13488]
Hello,

I try to change rate on first item and pos get freezed. I am on latest version.

**Comment by rohitwaghchaure** [comment]
Hi @vladucoju 

Thanks for reporting an issue, we have identified and fixed the issue. Kindly pull latest update and check

**Comment by Maree27** [comment]
@rohitwaghchaure  I still have the issue in version 14 when i  clear the Discount % field and click outside the item detail on POS and want to put some value it freeze
