### ISSUE TITLE
Stuck with "access denied for user erpnext@localhost" at import during installation.

### ISSUE THREAD

**Issue by essadek** [frappe/erpnext#13486]
_(I have posted the same on (https://discuss.erpnext.com/) but without feedback.)_

Running this command : 
` bench new-site froid.local --db-name erpnext --mariadb-root-username root --mariadb-root-password A_PASSWORD --install-app erpnext --verbose --force`

I get this : 

> Created user erpnext
> Created database erpnext
> Granted privileges to user erpnext and database erpnext
> Starting database import...
> **ERROR 1045 (28000): Access denied for user 'erpnext'@'localhost' (using password: YES)**
> Imported from database /home/frappe/frappe-bench/apps/frappe/frappe/data/Framework.sql
> Database not installed, this can due to lack of permission, or that the database name exists.

I have tried everything like elevating privileges for user 'erpnext'. 
The problem is that I can import the sql file using the same, but `bench` fails to do so : 
`mysql -u erpnext -p erpnext <  /home/frappe/frappe-bench/apps/frappe/frappe/data/Framework.sql  --socket=/var/mariadb-data/mariadb.sock`

**I doubt the granted privileges to the new user are not taking effect, otherwise how to explain the error is not raised for the user ‘root’.**

Note that I have Mariadb installed side-by-side with Mysql

**Comment by codingCoffee** [comment]
We're not able to replicate the issue. I would suggest going for a vanilla install using the easy install script instead of trying to install over an already installed mariadb/mysql server

**Comment by essadek** [comment]
Finally some comments for my issue. I have to confirm that I 've tried everything even giving the user all privileges to all db from all hosts just to see what's wrong.
This issue has taken me couple of days, but we have moved to another the server and hopefully the installation will go smoothly.
We can't use the easy install as we have a production server which use Mysql, so I have to install Mariadb manually.
