### ISSUE TITLE
Asset - documentation

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#13490]
- [x] "Auto booking of asset depreciation option in Account settings" in Fixed Asset management  manual documentation.

**Comment by kennethsequeira** [comment]
Will need to create documentation for **Fixed Asset Management** first. Right now there is only a single video available on the topic.

https://www.youtube.com/watch?v=I-K8pLRmvSo

**Comment by nabinhait** [comment]
https://github.com/frappe/erpnext/blob/develop/erpnext/docs/user/manual/en/asset/assets.md
