### ISSUE TITLE
Feature Request Button or switch to allow for the removal of party / party type for journal entries.

### ISSUE THREAD

**Issue by jasonbrowne** [frappe/erpnext#13502]
Problem: Our accountants do do not want party / party type in journal entries.
Removing the columns is helpful but does not change the issue that party / party type is still required for adding journal entries.

Solution: Button or switch to allow for the removal of party / party type for journal entries.

**Comment by umairsy** [comment]
If making payments is handled from Payment Entry only, then hiding Party and Party Type in the Journal Entry should be fine. Force user to make Payment Entry for the payment against party, and use invoices for other posting like updating payable / receivables.
