### ISSUE TITLE
Purchase Receipt from Material Request

### ISSUE THREAD

**Issue by Mishaal1021** [frappe/erpnext#13506]
Hi,

So currently, the system is great, and it allows you to create Purchase Order from Material Request. However, often times, material request may be for small valued items, and do not require a Purchase Order as per company policy. In this case, we should be able to create a purchase receipt directly from Material Request so that the system reduces the items requested every time we receive material without a PO, but against a material request. 

This feature would really enhance the stock and buying modules and assist us a great deal. 

Regards,

Mishal

**Comment by umairsy** [comment]
For now, add a Custom Field of "Material Request" in the Purchase Receipt Item table. So  you will atleast have value Material Request ID copied from Purchase Order to Purchase Receipt.

**Comment by LifeP** [comment]
+1

**Comment by Mishaal1021** [comment]
@umairsy  yes, we have added that field in both purchase receipt and purchase invoice, and even manually linking where Purchase Order is not issued for small valued items. However, the issue becomes that Material Request still stays pending, and has to be manually closed. Mostly its fine, but for purposes of partial orders, it becomes difficult.
