### ISSUE TITLE
[Paid Development] ERPNext customisation implementing GST Malaysia

### ISSUE THREAD

**Issue by kaviarasu88** [frappe/erpnext#13504]
Hi, Looking for a developer, for ERPNext customisation implementing GST Malaysia

**Comment by saurabh-bhosale** [comment]
@kaviarasu88 There is already some work being done on this. You can check with @alancheongkl for [Compliance with GST in Malaysia](https://github.com/frappe/erpnext/issues/13268)

**Comment by umairsy** [comment]
Manage via https://github.com/frappe/erpnext/issues/13268
