### ISSUE TITLE
New Pricing Update on the Website

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#13508]
- [x] Remove P100 user plan
- [x] Design display of P5 plan and Enterprise plan, without card. but it will include the pointers. $168/month.
- [x] Keep the Functional Support plan for self-hosted as it is.

**Comment by raghukamath** [comment]
# Points in respective section

## p5 plan 
* $168/month (for 5 users combined right?)
* 5 Users
* Add User at $12.5/month
* 5 GB Space
*  5,000 Emails
* Priority Support
* Bug Fix Guarantee
* All Modules
* All Domains
* Auto-Upgrades
* Automated Backups
* Custom Domain
* Mobile App

## Enterprise plan
* $10000/year
* Unlimited Users
* Unlimited Space
* Unlimited Emails
* Priority Support
* Bug Fix Guarantee
* All Modules
* All Domains
* Auto-Upgrades
* Automated Backups
* Custom Domain
* Mobile App
* Custom Reports
* Custom Print Formats
* Dedicated Engineer
* Feature Development

Are these points correct? Any more suggestions? 

 I am thinking of putting two sections side by side just that they wont have boxes around, is this correct? (below is the very rough mock of what I am thinking)

![pricing](https://user-images.githubusercontent.com/9101092/38290937-1fa5a71c-37fb-11e8-9894-4c69a3b8ce1c.png)


Thanks

**Comment by umairsy** [comment]
Can we drop the columns and have separate section for hosted and enterprise plan?

With the new enterprise plan, we will remove the existing plan of $3000 as well.

**Comment by raghukamath** [comment]
This is a new mock based on the feedbacks

![pricing-update](https://user-images.githubusercontent.com/9101092/38800470-f79ed5b6-4184-11e8-8832-187f6b38b6fd.png)
