### ISSUE TITLE
Calculation Script

### ISSUE THREAD

**Issue by Mishaal1021** [frappe/erpnext#13507]
Hi,

Is there any way to show a sum formula in the field – either thru a formula script or otherwise. Please see below. Will appreciate your support on this.

For instance, total sqm field should calculate the total quantity where UOM=sqm. The same should be done for Total Pcs column. 

![calculation](https://user-images.githubusercontent.com/29452673/38289479-7a642322-37e7-11e8-8bfd-fd056d881b8e.jpg)

**Comment by rmehta** [comment]
You can do this via custom scripts!

https://erpnext.org/docs/user/manual/en/customize-erpnext/custom-scripts/custom-script-examples
