### ISSUE TITLE
Workflow give edit permission to multiple role for single state

### ISSUE THREAD

**Issue by jigartarpara** [frappe/erpnext#13515]
If I add multiple role permission for single state of document
then only first permission will work and others will be ignored

state Only Allow Edit For
Approved Project User
Approved Finance manager

for above case, if the document is in the approved state then only project user able to change document
but finance manager will unable to change document

**Comment by umairsy** [comment]
In the Workflow, we will be adding conditions, just like in Email Alert, which shall give you more flexibility.

For the above case, if Finance Manager also has the role of Project User assigned, then even Finance Manager will be able to do editing where required. This should work even now.

**Comment by Xyuni** [comment]
This isn't fix even in ver 11? Why must workflow state only allow one role to edit a document under any state? IT does not make much sense!

**Comment by Olawale1** [comment]
Hi @umairsy 

Trust you're doing great. Can you please re-open this or should we create another one? The issue is still there so this shouldn't have been closed in the first place!

Thanks
