### ISSUE TITLE
V11 Testing

### ISSUE THREAD

**Issue by nabinhait** [frappe/erpnext#13513]
**V11**

ERPNEXT
---------------------------------------

- [ ] Quality Inspection Template
- [ ] Item Alternative
- [ ] Refactored Expense Claim
- [ ] Refactored Leave Application
- [ ] Multiple barcode per item
- [ ] Shareholder and related documents

- [ ] New Subscription
- [ ] Hub
- [ ] Existing Subscription renamed to Auto Repeat
- [ ] Daily Project Update
- [ ] Restaurants module
- [ ] Prorated Asset Depreciation
- [ ] Setup Wizard Updates
- [ ] Improved UX for Delivery Trip
- [ ] Health Insurance for Employee
- [ ] Currency filter on pricing rule
- [ ] Transaction Log for France

- [ ] Subcontracting
- [ ] Reserve raw materials for sub-contracting
- [ ] Single stock transfer entry for multiple sub-contracted items
- [ ] Provision to include exploded items while making transfer entry of raw materials

- [ ] Renamed documents
     - [ ] Production Order -> Work Order
     - [ ] Production Planning Tool -> Production Plan
     - [ ] Offer Letter -> Job Letter
     - [ ] Employee Loan -> Loan (Members can also apply for loan)

- [ ] Reports
    - [ ] Customisable Cash Flow Reports
    - [ ] Employee Advance Summary
    - [ ] Presentation currency in General Ledger
    - [ ] Exploded view for BOM Stock Report
 
- [ ] POS
    - [ ] Allow draft mode print in online POS
    - [ ] Allowed print before pay
    - saved the invoice before print

- [ ] Patient Appointment
    - [ ] Check appointment day is holiday or physician on leave
    - [ ] Service unit based scheduling and booking

- [ ] Payment Gateway Integration
     - [ ] Braintree
     - [ ] Gocardless

FRAPPE
---------------------------------------

- [ ] Dynamic Frappe Charts with Report Builder
- [ ] NEW Frappe Chat
- [ ] New ListView + DataTable
- [ ] Python 3 fixes
- [ ] New User Permissions

**Comment by pratu16x7** [comment]
😮
