### ISSUE TITLE
[ux] 3 buttons inside Project Task child table is not looking good

### ISSUE THREAD

**Issue by nabinhait** [frappe/erpnext#13532]
<img width="1220" alt="screen shot 2018-04-05 at 1 11 36 pm" src="https://user-images.githubusercontent.com/836784/38353113-1779aeca-38d3-11e8-8ed2-16b4e72af99a.png">

Might be inline

**Comment by Olawale1** [comment]
Hi @nabinhait 

Could you please elaborate on buttons being inline?

Thanks
