### ISSUE TITLE
[GST] supplier reconsiliation with GSTR 2A

### ISSUE THREAD

**Issue by vorasmit** [frappe/erpnext#13547]
**Overview:**
As we file GSTR1 with outward supplies, in a similar manner our supplier also files GSTR1. Returns filled by them are reflected in our GSTR2A Report. It can be used to reconcile with our purchases.

Matching of Invoices is crucial to claiming GST credit. So Supplier compliance becomes necessary. And hence it's essential to track non-compliance to avoid financial loss.

**Proposed Feature:**
- Separate doctype to Import GSTR 2A in ERP Next.
- Automatic matching of invoices based on supplier GSTIN + Supplier invoice no / supplier tax in invoice / transaction value.
- Find an Exact match, Approximate match, and not matching of invoices. 
- Manually match invoices not matched, and accept values where there is an approximate match.
- Update supplier invoice status as return filled or return submitted but not filled, from data in GSTR2A
- Get the report for Purchase recorded in books but not in GSTR 2A --> to identify supplier non-compliance
- Also Get the report for Purchase not recorded in books but there in GSTR 2A --> to identify missing purchase invoice.
- Communicate non-compliance to suppliers --> block payments unless complied.

**Sample screenshots from Cleartax reconciliation tool.**

Import of GSTR 2A
![import of gstr2a](https://user-images.githubusercontent.com/10496564/38406679-cf92e146-3993-11e8-82a1-c3984db6fd3c.PNG)

Reconciliation
![reconciliation](https://user-images.githubusercontent.com/10496564/38406687-d9de2390-3993-11e8-84f1-de3043ad33e5.PNG)

Link to Video: https://youtu.be/ivbMD3LlPFA

**Comment by decentrajan** [comment]
Hi i have a issue with gstr2a api. please correct the api, where is mistake for cdnr..
if i use this api for b2b it works perfect.. but in cdnr it shows error

https://return.gst.gov.in/returns/auth/api/gstr2a/ctin?rtn_prd=042018&section_name=CDNR

**Comment by pharsharao** [comment]
https://return.gst.gov.in/returns/auth/api/gstr2a/ctin?rtn_prd=042018&section_name=CDNR -where did you get this API ? its not available on [developer portal ](https://developer.gst.gov.in/apiportal/taxpayer/returns) . Thanks in advance.

**Comment by pharsharao** [comment]
> 
> 
> Hi i have a issue with gstr2a api. please correct the api, where is mistake for cdnr..
> if i use this api for b2b it works perfect.. but in cdnr it shows error
> 
> https://return.gst.gov.in/returns/auth/api/gstr2a/ctin?rtn_prd=042018&section_name=CDNR

https://return.gst.gov.in/returns/auth/api/gstr2a/ctin?rtn_prd=042018&section_name=CDNR -where did you get this API ? its not available on [developer portal ](https://developer.gst.gov.in/apiportal/taxpayer/returns). Thanks in advance.

**Comment by karthikeyan5** [comment]
@vorasmit, this app has a few of the proposed features you mention... 

Do take a look, if it might be useful for you... 

https://github.com/aerele/reconciler

Also, what is the number of transactions you handle per month?
