### ISSUE TITLE
URGENT! Warehouse in POS Profile not fetched to Sales Invoice 

### ISSUE THREAD

**Issue by franciscobuendiao** [frappe/erpnext#13546]
Warehouse in POS Profile is not fetched to Warehouse on Packed Items table.

**Comment by umairsy** [comment]
It's working fine in my test account. Warehouse in the POS Profile was correctly given preference over Warehouse in the Item master.

**Comment by franciscobuendiao** [comment]
Umair, it's only fetching to Items Table.
But it's not fetching to **_Packed_** Items table.

Just updated to:
ERPNext: v10.1.28 (master)
Frappe Framework: v10.1.28 (master)
