### ISSUE TITLE
VAT on Gross Profit

### ISSUE THREAD

**Issue by Benchaccountant** [frappe/erpnext#13548]
I want to hear about the solution on a case which is stated below:

We have a product whose
Sale price is 100
Purchase price is 80 

Normally we charge VAT on gross value of sales and purchases. 

VAT on sales is 5
VAT on purchase is 4
Net amount of 1 becomes liability to be paid to the Govt 

However, when there’s a profit margin scheme we do the same sales and purchases for VAT purposes as follows :

Vat on sale is 0
Vat on purchase is 0
But, vat would be on gross profit
 i.e. (100-80)*5%
Which is equal to 1

So if we can add this feature into the system which is known as profit margin scheme.

**Comment by generare** [comment]
Yes, we have been searching for the same thing, I just didn't know this term that it is called "profit margin scheme". This is applicable in many countries when there are used goods bought from one individual / company and sold to another one. In that case you charge VAT only for the profit amount.

**Comment by grynn-in** [comment]
The current feature (how purchase and sales VAT) is achieved can achieve this outcome out of the box. You have to set up the purchase and sales VAT charges template. Adding highly specified feature that works in only one instance does not create good solutions.

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.
