### ISSUE TITLE
[Feature Request] GSTR - 3B report

### ISSUE THREAD

**Issue by djpalshikar** [frappe/erpnext#13541]
It is need for calculating GST amount due for the month. A good reference for India would be 
https://help.tallysolutions.com/docs/te9rel61/Tax_India/gst/Form_GSTR-3B.htm

**Comment by intelliant01** [comment]
Related discussion - https://discuss.erpnext.com/t/india-only-gstr3b-report/35373

**Comment by test2a** [comment]
i guess dont bother with the report if you havent started already because the govt is going to introduce new returns from january next year. So long

**Comment by rushikesherp** [comment]
Formats received from one of the service providers for the GSTR3 and GSTR3B returns. Attaching them here for reference. 
[GSTR3.pdf](https://github.com/frappe/erpnext/files/2473071/GSTR3.pdf)
[GSTR-3B-Format-FinApp.pdf](https://github.com/frappe/erpnext/files/2473072/GSTR-3B-Format-FinApp.pdf)

**Comment by deepeshgarg007** [comment]
@djpalshikar GSTR-3B report have been added in ERPNext v12
Closing this issue

**Comment by test2a** [comment]
@deepeshgarg007 do you know if anyone is working on the new return scheme because the same is mandatory from 1 july ?

**Comment by Ravn10** [comment]
Can we include GSTR-3B report in ERPNEXT Version 11 .
