### ISSUE TITLE
Show pending leaves as an HTML table in leave application

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#13557]

**Comment by saurabh-bhosale** [comment]
@rmehta Which one of these is expected for pending leaves HTML in Leave Application:
1. HTML showing total leave allocated for the selected leave type and the remaining leaves for that employee.
2. HTML should show all types of leaves with allocated and pending leaves for the selected employee
or
3. Leaves that are open and not yet approved?

**Comment by rmehta** [comment]
leaves allotted per leave type. a HTML table with leave types columns

- leave type
- allotted
- used
- pending approval
- available

The goal is that the employee must have a clear idea of her leave position before applying.

**Comment by sanjay-hercules** [comment]
To leave approver, it should show leave applied by other employees during leave period.
![image](https://user-images.githubusercontent.com/34718633/38596398-f0dedd08-3d6e-11e8-91bf-66b604423903.png)
