### ISSUE TITLE
Customer Statement Aging Report

### ISSUE THREAD

**Issue by albertusgeyser** [frappe/erpnext#13565]
Good Day

Could you please include Customer Statement Aging Report in ERPNext as discussed:
https://discuss.erpnext.com/t/customer-statements/35614

We need to send Statements to customers by printing and posting or by emailing Statements to them.
Example of statement can be found here:
http://www.enteryourhours.com/SoftwareReference/Aging_Report_and_Statements.aspx

Thank You Very Much.
Albertus Geyser

**Comment by LifeP** [comment]
Custom App for the same -
https://github.com/jaywks/statement_of_account_aging

**Comment by hifyaan** [comment]
yes agree with heatherpotter
an absolute must in any org
no erp is complete without customer and suplliers statments

**Comment by casesolved-co-uk** [comment]
#22901 does the job
