### ISSUE TITLE
Notification click not working

### ISSUE THREAD

**Issue by gadiel** [frappe/erpnext#13560]
on release https://github.com/frappe/erpnext/tree/v10.1.20

when clicking notification, nothing happens, no console error neither

![image](https://user-images.githubusercontent.com/1625685/38445929-d33fb002-39b2-11e8-8763-1e22238091f3.png)

**Comment by gadiel** [comment]
![image](https://user-images.githubusercontent.com/1625685/38446186-fc38657a-39b3-11e8-9877-59c7d3b37dc3.png)

**Comment by Zlash65** [comment]
https://github.com/frappe/frappe/pull/5423
