### ISSUE TITLE
Can not Submitte Stock Reconsiliation

### ISSUE THREAD

**Issue by FlexsoftsTech** [frappe/erpnext#13569]
Dear Team 
i can not sbmitte stock reconsiliation, Scenario is weird 
when i press on submitte system submitteing it and when refresh page transaction get back to draft, no error show up
Here is my version details:
Installed Apps
ERPNext: v10.1.20 (master)

Frappe Framework: v10.1.19 (master)

**Comment by umairsy** [comment]
Hi,

Still facing this issue? Any error message in the browser console or error message?

**Comment by nabinhait** [comment]
Can't replicate, seems like has been fixed. Please reopen if you are still facing the issue.
