### ISSUE TITLE
Grouping Items for Sales Invoice

### ISSUE THREAD

**Issue by Mishaal1021** [frappe/erpnext#13566]
Hi,

I saw that there was a pull request done to group like options on purchase order https://github.com/frappe/erpnext/pull/6513

This is a very useful feature - any way this can be replicated to Sales Invoices. For many companies, including the companies I work with, there are multiple deliveries made - but a consolidated sales invoices is made on a monthly basis. 

@rohitwaghchaure @umairsy 

Regards,

Mishal

**Comment by umairsy** [comment]
This feature has been added in ERPNext hotfix branch. It should be merged into master branch in our next release, may be in a day or two.
