### ISSUE TITLE
[Paid Feature] Delivery notes (Cost per item) within report builder

### ISSUE THREAD

**Issue by TetraComSA** [frappe/erpnext#13573]
@umairsy @kennethsequeira 

Dears,
Please quote us your best rate for the following:
1. While issuing Delivery note, we would like to see the **cost** of every item within trx and report builder. Why? We need to have the estimated cost of every Delivery note we place. 
2. We know that we can get it from stock ledger as soon as the trx posted, but we need to have it within Delivery note area.
3. Cost of every items needs to be according to the warehouse (Not valuation rate).

![image](https://user-images.githubusercontent.com/33566237/38492793-c3a806e2-3bf8-11e8-8c5b-ec8a3d5f2d80.png)

Regards,
Yahya

**Comment by umairsy** [comment]
Hi,

Can you please elaborate on cost should be based on Warehouse and not based on Valuation Rate?

**Comment by TetraComSA** [comment]
Hello Umair,

Example:
**Warehouse 1** is having item code X (Qty 1) (Cost SR10)
**Warehouse 2** is having item code X (Qty 1) (Cost SR13)
Total: (Qty 2) (Valuation rate SR11.5).

Example of Delivery note to place:

- DN-00001 Warehouse selected 1 (Qty 1) (Here the cost of this item has to be SR10) Not the above valuation rate SR11.5
- DN-00002 Warehouse selected 2 (Qty 1) (Here the cost of this item has to be SR13) Not the above valuation rate SR11.5

So, Delivery note (Cost of items) needs to be linked to the cost of that item within that warehouse we select in the delivery note.

Regards,
Yahya

**Comment by umairsy** [comment]
Yahya,

Can you check what is the valuation rate set for the item? Is it FIFO or moving average? If you want to fetch the item's rate based on it's purchase rate, then you should set it as FIFO.

@rohitwaghchaure  @nabinhait can we make valuation rate field visible in the Delivery Note item table? Could it become a generic feature?

**Comment by TetraComSA** [comment]
Hello Umair,

Under stock setting, the method is set to FIFO. However, I think there are some items were set to Average in the master items.... Is that going to be affected by somehow....!!
