### ISSUE TITLE
Project Doc does not capture already accounted costs

### ISSUE THREAD

**Issue by Jaliya** [frappe/erpnext#13577]
In the ERPNext, in the project Doc we capture all the costs of a Project. Cost of material we capture via Purchase Invoices and via Stock Entry. Cost of Labour we capture via Timesheets. Expenses via Expense Claims. But we have failed to capture or allocate already accounted costs to Project Cost.
The most common example is Transport Costs when you do small projects or number of projects simultaneously. Petrol is pumped to vehicles without relating it to a particular project. But we should have a way to allocate cost to a Project according the number of Km ran for that project. Now there is no way to do so in the Project Doc.
There are many such costs for which payments have been made some time or long time back. Some examples are cost of reusable scaffolding, use of company owned machinery. If we don’t make a payment now, Project Doc has no way to capture that cost.
I hope solving this is not a complicated issue. Only thing need is something like timesheet which is not connected to the main accounting process and a cell in the “Costing & Billng” section in the Project Doc.
It will solve many problems face by  Project Module users to capture fully the project costs and find the  Margins left.

**Comment by ewqiop** [comment]
I don't get how this is an issue.

The example of allocating petrol for vehicles to a specific job can be achieved through expense claims. Use of company owned machinery can be tracked by setting up the company supplying the equipment as a supplier and having them invoice you for the use of the equipment (a rental agreement). Cost of reusable scaffolding could be done the same way as it's the same example but specific. All these transactions will be tracked against a Project. 

Where or what is the issue?

**Comment by umairsy** [comment]
For now, you will have to breakup this Expense Entry into multiple rows for the expense and select separate Project/Cost Center in each row.

**Comment by Jaliya** [comment]
Dear Umair,You may have understood the issue differently. Transport cost may include not only fuel coat but also cost of lease payment, maintenance cost of vehicle and so on which were accounted or will be accounted at different time points. So there is no way to apportion those costs to different projects. Presently if there is a purchase invoice that cost can be allocated to the project. What we want is to allocate a calculated cost to a project. The component of that calculated cost say cost of 30km transport has been accounted at different time points.RegardsJaliyaOn 10 Apr 2018 10:28, Umair Sayed <notifications@github.com> wrote:For now, you will have to breakup this Expense Entry into multiple rows for the expense and select separate Project/Cost Center in each row.

**Comment by ewqiop** [comment]
The cost/expense has already been realised in your scenario. You can recover against it by adding a line to the Sales Invoice that covers the "calculated" cost.
