### ISSUE TITLE
[BUG] Discount is not calculated in Purchase Invoice

### ISSUE THREAD

**Issue by vladucoju** [frappe/erpnext#13583]
Hello,
after latest update discount is not calculated in purchase invoice item. Rate has same value as price list rate. Discount is not calculated in rate.

**Comment by umairsy** [comment]
Can you please share the screenshots as how Discount was applied. In the Item table, discount is applied on the Price List rate only.

**Comment by vladucoju** [comment]
![capture](https://user-images.githubusercontent.com/9590909/38552653-1629236e-3cbd-11e8-9dc3-11864dc3d31d.PNG)

**Comment by vladucoju** [comment]
Yes, i know. This works ok since last update.

**Comment by vladucoju** [comment]
I updated Erpnext today but there is still this error. When i change price in rate field percentage is populating discount field correctly. But from price list it is like in picture above. Nothing changes.

**Comment by vladucoju** [comment]
Hello @umairsy ,
i made some test meanwhile, and i found that my custom app made this problem. That app works perfect since i made update yarn. My script is bellow. Can someone help me to resolve this

This is my script
import frappe
import json
from frappe import _
from erpnext.stock.get_item_details import process_args, validate_item_details, get_valuation_rate, get_basic_details, get_party_item_code, get_price_list_rate, get_pos_profile_item_details, get_bin_details, get_pricing_rule_for_item, get_serial_no, add_days, get_default_bom, get_gross_profit
from frappe.utils import flt, cint
from erpnext.manufacturing.doctype.production_order.production_order import *
from erpnext.selling.doctype.sales_order.sales_order import make_production_orders

@frappe.whitelist()
def calculation_by_discount(item):
price = json.loads(item).get(‘price_list_rate’)
discount = json.loads(item).get(‘discount_percentage’)
tax = eval(json.loads(item).get(‘item_tax_rate’))

tax_rate = sum(tax.values()) if len(tax.values()) > 0  else 0.0

tax_amount = (tax_rate * price) / 100
sales_price = price - (15.97 * price ) / 100
purchase_price = price - (15.97 * price ) / 100
discount_amount = (discount * sales_price) / 100

# tax_amount = (tax_rate * price) / 100
# sales_price = (price) - (15.97 * (price + tax_amount)) / 100
# purchase_price = (price) - (15.97 * (price + tax_amount)) / 100
# discount_amount = (discount * sales_price) / 100

try:
	margin_percent = (sales_price - (sales_price - discount_amount)) / (sales_price - discount_amount) * 100
except ZeroDivisionError:
	margin_percent = 0.0

margin_value = margin_percent * (sales_price - discount_amount) / 100

values = {'sales_price': sales_price, 'purchase_price': purchase_price, 'margin_percent': round(margin_percent, 2), 'margin_value': round(margin_value, 2)}

return values

**Comment by vladucoju** [comment]
Tonight, i update erpnext, and discount is working again. My script is not populating custom fields. Some conflict with yarn update.

![capture](https://user-images.githubusercontent.com/9590909/38834145-d9be7176-41c7-11e8-828e-9bfe8ba26805.PNG)
