### ISSUE TITLE
Adding incoterm to quotation and invoice

### ISSUE THREAD

**Issue by HNaga** [frappe/erpnext#13580]
Can we add ncoterm to quotation and invoice?

**Comment by umairsy** [comment]
This feature is not available for now. Can you share it's example here? 

If they are the standard text which goes which with transaction, you can capture it in the Terms and Condition template in the ERPNext.

**Comment by HNaga** [comment]
incoterm 
EXW ex-works
FCA free carrier
FAS free alongside ship
FOB free on board
CFR cost and freight
CIF (COST insurance and freight)
CPT – Carriage Paid to (duty paid)
CIP Carriage and Insurance paid to
DAF (Delivered at Frontier)
DES (Delivered ex-ship)
DEQ (Delivered EX quay)
DDU (delivered duty unpaid)
DDP (delivered duty paid)


please refer to 
https://www.linkedin.com/pulse/incoterms-2017-exw-fca-fas-fob-cfr-cif-cpt-cip-daf-des-john-kingsley/
