### ISSUE TITLE
Asset linked to Purchase and Serialized Assets

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#13594]
### Allow non stock Serial No

- [x] Allow user to set both asset and has serial no if is_fixed_asset=True
- [x] Link Asset Maintenance to Serial No

### Purchase Receipt
- [x] Asset Location
- [x] On PR submission - check auto creation of non stock Serial No and asset
- [x] On PR cancel
     - [x] delete Serial No
     - [x] delete asset if in draft
     - [x] remove PR link from asset if submitted
- [x] Auto creation of Asset on Purchase Receipt
     - [x] Create Asset (in Draft)
     - [x] Naming Series field (in Item set asset series)
     - [x] Create Serial Nos (as per standard flow)
     - [x] Link asset to serial no
     - [x] On deletion of asset, validate PR is cancelled
     - [x] Create Asset Movement for Serial No
- [ ] In case asset item is a Product Bundle, create asset records for RM items if marked as is_fixed_asset.

### Accounting Entry
- [x] Debit valuation amount to CWIP (Capital Work in Progress) account and credit "Asset Received but not billed" (ARBNB)account on submission of PR
- [x] Credit Creditors account and debit "Asset Received but not billed" (ARBNB)account on submission of Purchase Invoice and credit "Expenses "
- [x] Make CWIP, ARBNB and Expenses Included In Asset Valuation account in standard chart of accounts
- [x] Add account type "CWIP" and set default CWIP account in company based on account type.
- [x] Add account type "Asset Received but not billed" and set default ARBNB account in company based on account type.
- [x] Validate above 2 account while making PR
- [x] Set Valuation Rate for Item (Net Amount + Tax Amount where tax category is Valuation or Valuation and Total)

```
Purchase Receipt
-----------------
item 100
tax1 (val+total) = 10
tax2 (val) = 5
tax3 (total) = 8

CWIP = 115(Dr)
ARBNB = 115(Cr)


Purchase Invoice
------------------

Creditors = 118 (Cr)
ARBNB = 115(Dr)
Tax = 18 (Dr)
Expenses Included In Asset Valuation = 15 (Cr)
```

### Asset
- [x] In Use Date (must be after submission date)
- [x] Gross Purchase Amount (Set it from PR, based on valuation rate)
- [x] Custodian (linked to employee)
- [x] Insurance details
     - [x] Policy number
     - [x] Insurer
     - [x] Insurance period – start and expiry date
     - [x] Insured value
     - [x] Comprehensive Insurance
- [x] Post accounting entries via scheduler on in-use date
     -  [x] Debit Fixed Asset account defined in asset category
     -  [x] Credit CWIP account
- [x] Depreciation
     - [x] Depreciation Method, Frequency, Number of Depreciation, Value after depreciation and start date should be set based on **Finance Book** (Child Table)
     - [x] Add the above table in Asset Category as well for defaulting
     - [x] Create schedule for all finance books, add finance book column in schedule table
     - [x] Create schedule from depreciation start date. But set depreciation amount for the first period based on put-to-use date using pro-rata.
    - [ ] Set Finance Book in Journal Entry for depreciation (auto)
    - [x] Introduce new method WDV

### Asset Category
- [x] Add CWIP Account in default accounts child table

### Location (Tree)
- [x] Patch based on warehouse for existing customers (only run if submitted asset record exists)
- [x] Replace Warehouse with Location in Asset and Asset Transfer document

### Asset Movement
- [x] Purpose, Date, Asset, Serial No,  Qty, Source Location, Target location, From Employee, To Employee
- [x] Either Location or employee is mandatory
- [x] Validate serial no with asset and qty
- [x] Update location in asset or serial no (if serialised asset)
- [x] Allow group node of location

### Asset Adjustment
- [x] Finance Book, Asset, Date, Current Value (fetch based on value after depreciation on selected finance book), New Value, Company, Journal Entry
- [x] Book fixed asset expenses for diff value against accumulated depr account via Journal Entry
- [x] Reschedule for future depreciations

### Sale of Asset
- [x] Serial No in sale

#7469 
#5766

**Comment by umairsy** [comment]
Could multiple Serial No. linked to one Asset, incase of large Asset item broken into multiple Serialised units?

**Comment by jma4227** [comment]
Hey, I don’t know if anyone is still following this , but has this been removed from v12?

**Comment by jimmielightner** [comment]
I'm trying to assign a serial number to fixed assets in v13 and it doesn't work. Once I tick the "is fixed asset" box on a new item, the "Serial and Batches" section becomes blank. I think this might be a regression @rmehta

**Comment by elan-k** [comment]
> 
> 
> I'm trying to assign a serial number to fixed assets in v13 and it doesn't work. Once I tick the "is fixed asset" box on a new item, the "Serial and Batches" section becomes blank. I think this might be a regression @rmehta

The same issue identified in V12 as well. 

Installed Apps :
ERPNext: v12.21.0 (HEAD)
Frappe Framework: v12.18.1 (HEAD)
