### ISSUE TITLE
Inter company Journal Entry

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#13599]
- [x] In account, add check for "Inter Company Account"
- [x] Type of Journal Entry "Inter Company Journal Entry"
- [x] Only allow selection of Inter Company Accounts
- [x] Once Inter company JE is submitted, show button for "Make Inter Company Journal Entry"
  - [x] Link both Journal Entries (doubly linked)
  - [x] Ensure sub of debits/credits is equal in both journal entries
  - [x] Once paired entry is made, don't show button
- [x] Before submitting inter-company entry validate that a paired entry exists in the other company in draft or submitted state.

**Comment by snvora** [comment]
Hello,

I see the objective of this as to link inter-company transactions and validate them.

But a lot of transactions may happen between related companies including purchase, sale, lending, borrowing, i.e. through payment entries.

Do we plan on implementing that?
