### ISSUE TITLE
Exchange Rate Revaluation

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#13604]
- [x] New DocType Exchange Rate Revaluation
- [x] Posting Date
- [x] Company
- [ ] Rate Type
- [x] Get Entries (button)
     - [x] Child table will load all multi-currency B/S accounts
- [x] Child table columns
  - [x] account
  - [x] balance in base currency
  - [x] balance in alternate currency
  - [x] current exchange rate
  - [x] new exchange rate (Based on Rate Type)
  - [x] new balance in base currency
  - [x] difference
- [x] Total gain/loss
- [x] button "Make Journal Entry"
- [x] Create journal entry of type "Exchange Rate Revaluation"
  - child table will change values in base currency and not alternate currency
  - one row for each debtor/creditor account
  - sum will be booked in "unrealized exchange gain/loss"

### Exchange Rate Type
eg. Average, Selling, Buying
- [ ] Checkbox for Selling and buying

**Comment by saurabh-bhosale** [comment]
Resolved in https://github.com/frappe/erpnext/pull/13932
