### ISSUE TITLE
Finance Book in GL Entry

### ISSUE THREAD

**Issue by nabinhait** [frappe/erpnext#13601]
- [x] Add Finance Book doctype
- [x] In Journal Entry, add a field to select "Restrict to Finance Book" (non-mandatory)
- [x] Post Finance Book in GL Entry, if blank it should be considered for all finance book
- [x] Add filter for Finance Book in all General Ledger, AR/AP and financial statements
  - [x] General Ledger
  - [x] AR/AP
  - [x] Financial Statements

**Comment by umairsy** [comment]
Will just adding Finance Book in the Journal Entry sufficient?

**Comment by gaurav-naik** [comment]
Should there be a Finance Book field on Sales and Purchase doctypes too? Wherever there's Company?

**Comment by nabinhait** [comment]
@gaurav-naik As of now, let's add it only in Journal Entry form. We can add it to different forms later if required.

**Comment by chdecultot** [comment]
Hi @nabinhait, @gaurav-naik,

Is the purpose of a Finance Book supposed to be similar to Accounting Journals ?
For example in Odoo: https://hibou.io/docs/odoo-11-accounting-3/journals-85

I'm looking for the best way to extract GL entries by accounting journals for statutory reports purposes and maybe I could use the Finance Books if the purpose is identical.

Thanks a lot for your input!

**Comment by heyberting** [comment]
> @gaurav-naik As of now, let's add it only in Journal Entry form. We can add it to different forms later if required.

In some countries like ours, there are expenses that are not recognized by tax officers. Thus, some items in the purchase invoice should have the Finance Books option as well. What could be the workaround with this?
