### ISSUE TITLE
Importing Purchase Order

### ISSUE THREAD

**Issue by rabar89** [frappe/erpnext#13603]
Hi. Our purchase orders have a lot of items in it. We have more than 200 items per purchase order. So it's very difficult for us to make a purchase order every time. Even for the importing with your template it takes much time. So can we make the importing function with our invoice template? Is it possible to change the importing template to our invoice structure?

**Comment by umairsy** [comment]
This is not configurable for now. You will have to follow standard template for importing purchase invoices only.

**Comment by BadarMahmood** [comment]
Hi I have been having a similar issue. I Just cannot seem to import a PO with even 2 lines. Also the data import fails to pick the rate even in single line PO's. Maybe its something very simple that i am missing. Is there a template that you can recommend or a vide that shows just how it is done?
