### ISSUE TITLE
Attendance Request

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#13620]
- [x] Employee
- [x] From Date
- [x] To Date
- [x] Reason (Work From Home, On Duty)
- [x] Explanation

---

- on submission, create Attendance

**Comment by pjamsheer** [comment]
- add attendaces for all days between from to dates (except for dates in holiday list, approved leaves)
- add Request reference in Attendance 
- On Cancel Cancel all attendace with reference to Request

**Comment by pjamsheer** [comment]
#13662 - PR
