### ISSUE TITLE
dictionary contains duplicate keys

### ISSUE THREAD

**Issue by robvdl** [frappe/erpnext#13639]
* in config/desktop.py the dictionary key "type" and "icon" are duplicated a lot
* in gross_profit.py the dictionary key "territory" is duplicated
* in purchase_order.py the dictionary key "source_dt" is duplicated
* in report_data_map.py the dictionary key "Work Order" is duplicated

**Comment by umairsy** [comment]
Please post it on the community forum at first.

https://discuss.erpnext.com
