### ISSUE TITLE
Shift Planning

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#13634]
### Shift Type

- [x] Start Time, End Time
- [x] Holiday List

### Shift Assignment

- [x] Shift Type
- [x] Company
- [x] Employee
- [x] Date
- [x] Present

### Shift Request

- [x] Assign / Cancel
- [x] Employee
- [x] Company
- [x] Shift Type
- [x] From Date
- [x] To Date

---

- [x] on submission, create Shift Assignment

**Comment by PawanMeh** [comment]
Opened separate #13996 issue for remaining documentation and tests. Closing this as it was merged.
