### ISSUE TITLE
Sales Invoices paid in full remain red and recorded as overdue

### ISSUE THREAD

**Issue by clarkejj** [frappe/erpnext#13631]
This occurs on the online erpnext.com hosted version.

ERPNext: v10.1.20 (master)
Frappe Framework: v10.1.21 (master)

Reported here https://discuss.erpnext.com/t/the-counter-at-account-sales-invoice-still-remains-red/35731/8

**Comment by PawanMeh** [comment]
@clarkejj, could you check this on the latest version and re-open if this is still an issue?
