### ISSUE TITLE
Selectable Time of Auto Transmittal for Auto Email Reports

### ISSUE THREAD

**Issue by maheshengg** [frappe/erpnext#13655]
user case 
Two Simple Reports have been created and are put into auto-email report.
one is DAILY-INWARD & other is DAILY OUTWARD set as "daily" and "html" , Currently these reports are recd at 00.00 hrs IST (midnight) , whereas the could be desired to be recd as auto report at 19.00 IST same day. how can this be achieved?

It is suggested that the time to sending autoemail report should be made selectable. That is currently users can select the frequency but not the time when it is desired to be received. 

This would be a good feature and beneficial to all.

![image](https://user-images.githubusercontent.com/1590079/38765047-f4257e70-3fd7-11e8-9230-5a2449637439.png)

**Comment by matmyers** [comment]
I'm a student developer new to this project, and I would like to try adding this feature. I found the code for sending emails, however, I'm having trouble understanding where the data from the html form for this report page is being passed to the backend. Does anyone know which file contains the code for the html form?

**Comment by kennethsequeira** [comment]
Duplicate: https://github.com/frappe/erpnext/issues/13981
