### ISSUE TITLE
Human Resource salary slip creation logic

### ISSUE THREAD

**Issue by adamtong1110** [frappe/erpnext#1366]
I found there is some confusing issues in Human Resource.

When you create a "Employee", there is "Date of Joining", "Offer Date", "Confirmation Date".

I found that it is good that you cannot create salary slip with month before "Date of Joining", but what is the use of "Offer Date" and "Confirmation Date"?
![employee](https://f.cloud.github.com/assets/1941183/2027186/9b043940-88ab-11e3-878b-95737c15c50f.png)

I expect you cannot create salary slip for an employee before the "Confirmation Date", because, by my interpretation, e.g. an employee joined my company at 1-1-2013, but I gave the offer on 15-1-2013, but this offer is confirmed on 1-2-2013, then I expect I cannot create salary slip for this employee for Jan, 2013. Is it right? But seems the system doesn't check this logic.

Also, for the Salary Structure, there is a "From Date", I expect it means the effective date of this salary structure for a particular employee, right?
![salary_structure](https://f.cloud.github.com/assets/1941183/2027197/e2694fc8-88ab-11e3-8298-f365d01c367c.png)

If the "from date" means the effective date, I expect I cannot make salary slip before this "from date" because this salary structure is not effective, right?

However, I found the system doesn't check this logic too.

Could you kindly advice me whether I am wrong to use it or the system is not capable to check those logic?

Thank you

**Comment by cgpurbaugh** [comment]
Has this been resolved?
