### ISSUE TITLE
Shipping rule in Delivery note overwrite value of sales order

### ISSUE THREAD

**Issue by Suprazz** [frappe/erpnext#13676]
If I use a Shipping rule in my sales order and I modify the shipping value, when I create the delivery note, the value from the sales order is erased and replaced by the original value of the shipping rule.

**Comment by jaichavan** [comment]
Hello, @Suprazz 
Just tried to replicate this in my test account, only to find out it has been addressed and fixed. Attaching screenshots for your reference:
1. Shipping Rule (Amount: INR 1,000)

![screenshot 2019-01-19 01 09 19](https://user-images.githubusercontent.com/40264279/51409333-7f318f00-1b87-11e9-8fb1-9ffa46c37c4f.png)

2. Sales Order ( Updated Shipping rule amount to INR 2,000 )

![screenshot 2019-01-19 01 11 42](https://user-images.githubusercontent.com/40264279/51409359-98d2d680-1b87-11e9-9f67-4071de4787b0.png)

3. Delivery Note ( Delivery fetching updated amount of Shipping rule, ie INR 2,000 )

![screenshot 2019-01-19 01 11 22](https://user-images.githubusercontent.com/40264279/51409374-a8eab600-1b87-11e9-8291-2d64217b3f43.png)

Thanks for reporting this to us!
