### ISSUE TITLE
Default Price List is not auto-fetching in Sales Invoice 

### ISSUE THREAD

**Issue by PrakashH** [frappe/erpnext#13682]
Default Price List is not auto-fetching in Sales Invoice. 

Steps: 
1) Open New Sales Invoice form
2) Select Customer
3) Scroll and Check CURRENCY AND PRICE LIST section

![screen shot 2018-04-17 at 2 24 12 pm](https://user-images.githubusercontent.com/4570016/38859186-1b67b51e-424b-11e8-83c8-c374b462ff4c.png)

**Comment by Zlash65** [comment]
https://github.com/frappe/erpnext/pull/13923
