### ISSUE TITLE
Export Single Document to Excel

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#13684]
Hi,

Exporting Single Documents to Excel is a common feature in most enterprise systems but somehow it's missing/overlooked in ERPNext. This is very useful for some documents like Quotations 

Please add this

Thanks

**Comment by Mishaal1021** [comment]
Hi,

I second that. We should be able to export directly from the voucher. If not, we should have filters in Data Import doctype. For instance, if we ever have to update items in certain item group, system will export all items - and we have to manually  delete them. 

Regards,

Mishal

**Comment by kennethsequeira** [comment]
Can be done via **Data Export** which was added in version 11.

![image](https://user-images.githubusercontent.com/33246109/62824729-c92fa000-bbbf-11e9-8b22-82f09ba74272.png)

**Comment by ablishek** [comment]
Although @kennethsequeira solution would allow you to export to Excel, it’s not the same as a proper document. 

In many businesses it’s standard to give both PDF and Excel format for the Invoices or Purchase Orders as the other party would then use it to import into their own system. Doing it this way can cause an incorrect column to appear. It would be less error prone to take the document already generated with the specified columns and issue an excel. There are many online packages that take PDF to Excel or HTML to Excel. I personally use something like this, but it would be more future proof if ERPNext could include such functions right next to the PDF Button.
