### ISSUE TITLE
Cannot change password for user

### ISSUE THREAD

**Issue by SonalR** [frappe/erpnext#13686]
cannot send user passwowrd intimation or change it for him.

Cannot intimate him about his user account being created. Get this screen no matter how fresh my screen is
<img width="1440" alt="screen shot 2018-04-17 at 5 28 37 pm" src="https://user-images.githubusercontent.com/4785299/38868555-0cba27b2-4265-11e8-9aab-4dd9f3b3e028.png">

**Comment by jaichavan** [comment]
Hello, @SonalR does the issue still _persist_?
