### ISSUE TITLE
Dashboard on Student Group

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#13690]
Add a Dashboard on Student Group, the quick links. Currently it is missing.

<img width="1188" alt="screen shot 2018-04-17 at 7 05 41 pm" src="https://user-images.githubusercontent.com/910238/38873019-60672c40-4272-11e8-9476-4035f15f4223.png">

**Comment by ruchamahabal** [comment]
Dashboards added to all the forms in: https://github.com/frappe/erpnext/pull/22727

**Comment by ruchamahabal** [comment]
Dashboards added to all the forms in: https://github.com/frappe/erpnext/pull/22727.
Closing.
