### ISSUE TITLE
Alternative Item in the BOM and Work Order Level

### ISSUE THREAD

**Issue by creamdory** [frappe/erpnext#13704]
## Current State

Alternative Items are set in the "Item Alternative" list. In the Manufacturing workflow for the current design, the alternative can only be chosen in the Stock Entry Level. This means that the BOM and the Work Order is already created. In reality, this is not the case. These are the problem we have encountered in our business flow:

1) There are some "Customer" specific alternatives and in some cases the original item and the alternative item is not even with the same technical description. Thus, you cannot set it as an official alternative for the item in the "Item Alternative" list. Therefore, the selection should not be limited only from the general "Item Alternative" setup.

2) Alternatives are BOM specific and not general. Though we have a general "Item Alternative" list, this must still be override in the BOM level. This alternative set-up will be for the specific BOM only.

3) BOM Alternative set-up should be the basis of the alternative the user can select in the Wok Order.

4) "Allow Alternative Item" must be per BOM line and should not be for the entire BOM to limit users to only allow alternative for specific lines.

## Goal

- [x] In the BOM, "Allow Item Alternative" must be set per Item and not in the entire BOM. It means that, we need to transfer below checkbox in the line:

<img width="1183" alt="bom1" src="https://user-images.githubusercontent.com/21003054/38918698-c98673da-42ee-11e8-98cd-c76bd9e0b06e.png">

- [x] Setting of item alternative in the BOM Line with the following features:

- Must be able to select from the alternative of the item already exist in the "Item Alternative" list.
- If preferred alternative is not in the list, must have the choice to select from the Item Doctype list.
- Alternative in this case is One-way.
- Alternative set in BOM WILL NOT be auto-saved in "Item Alternative" list.
- Indicator that the BOM Item has alternative setup.

- [x] Selection of Alternative in Work Order with the following features:

- User can select from the alternative of the item set-up in BOM
- Must have indicator that the Work Order Item is an alternative and not the original BOM item.

**Comment by creamdory** [comment]
Hi @nabinhait  and @rohitwaghchaure , we are developing an enhancement of Item Alternative feature in ERPNext. Can you check the requirements above if this is clear? We are working on the PR for this.

**Comment by kickapoo** [comment]
First level of BOM implementation 
 - In BOM level if Allow Alternative Item is set when is allowed to set Alternative Items in BOM Line (BOM Item)
- If selected Item "has alternative" in Item when ready only field in BOM Item is updated to indicate this and user can select from Alternative Item List as well
- Custom Html field selected to render the dialog feature because native Table field in a child of child modal created problems (table field in the second modal can deactivate the first modal)


Lagging Mac, Lagging gif. More Detailed gif soon
![2018-04-26 13 30 47](https://user-images.githubusercontent.com/5064612/39300984-4998b476-4956-11e8-9003-7c92b8399052.gif)

**Comment by kickapoo** [comment]
Updated usage
![2018-04-27 12 28 58](https://user-images.githubusercontent.com/5064612/39355887-200dd052-4a17-11e8-8157-7d6bd1d25617.gif)

**Comment by kickapoo** [comment]
First impact with Work Order , prototyping.

![2018-05-02 14 01 24](https://user-images.githubusercontent.com/5064612/39519968-86a2cc52-4e11-11e8-9e40-18879cb7b178.gif)

**Comment by creamdory** [comment]
@kickapoo I personally like the design. Go job! 

@dottenbr @nabinhait @rohitwaghchaure any comments/inputs on this?

**Comment by kickapoo** [comment]
Improvement on BOM Item UI.
![2018-05-08 10 47 38](https://user-images.githubusercontent.com/5064612/39744886-58eca9d0-52ae-11e8-8f13-7a85ccee9088.gif)

**Comment by kickapoo** [comment]
Work Order selection
![2018-05-08 11 51 18](https://user-images.githubusercontent.com/5064612/39747639-7de85d1c-52b6-11e8-93fd-0b5e55de836e.gif)

**Comment by creamdory** [comment]
@kickapoo I will help in testing this in my local.

**Comment by kickapoo** [comment]
@dottenbr @nabinhait @rohitwaghchaure .

**Comment by rohitwaghchaure** [comment]
@kickapoo Good job

We added Alternate Item button in the stock entry at the parent level so user can easily view that option and can select alternative item for more than one items at a time
![screen shot 2018-05-10 at 12 13 01 pm](https://user-images.githubusercontent.com/8780500/39855970-bbf3f94a-544b-11e8-959d-406d295675bf.png)

Is there any reason to keep "Switch to Alternative Item" button in the work order at inline item?

**Comment by kickapoo** [comment]
@rohitwaghchaure 

The reason I went to this is that is more "explicit" for the end User in Word Order lvl. Imagine you have 100 items with 100 Alternative to each one. What will happended went "Select Alternative Item" is clicked.

Also, the "Select Alternative Item" give you the "add row" . In Work Order lvl it should not be open additing alternative item (of course with permission etc can be set but), only in the BOM lvl a Item that is "to manufacture" should change its "bom lines".

At least my specs where at this direction.

**Comment by krishnanhemanth** [comment]
Hi
I have raised an issue something similar
https://github.com/frappe/erpnext/issues/14350
Regards
Hemanth
