### ISSUE TITLE
Cost Center Number

### ISSUE THREAD

**Issue by nabinhait** [frappe/erpnext#13717]
Similar to account number

**Comment by deepak-mnt** [comment]
@nabinhait  we can implement this feature to all the trees because users also want similar functionally on warehouse tree too

**Comment by jasonbrowne** [comment]
This is a great feature that I believe will allow ERPNext to better compete with the major ERP packages out there. Our accountants, etc have been wanting this functionality very badly.

**Comment by jasonbrowne** [comment]
This is great news!

**Comment by giuseppelamatrice** [comment]
+1
