### ISSUE TITLE
Request: track email / newsletter opens and link clicks

### ISSUE THREAD

**Issue by namankumar** [frappe/erpnext#13727]
Hello,

I strongly suggest that all emails sent by ERPNext have the capability to track how many times it was opened and how many times the links within it were clicked (or how many times a document was viewed). This information is best displayed on the Leads / Customer or Contacts page.

This feature is very important for marketing and CRM as it provides insight into engagement metrics.

If this is not in the plan, I suggest a plugin / extension with Mautic, which is an open source software for email marketing, among other things.

Best,
Naman

**Comment by parsimonyERP** [comment]
+1

**Comment by voarsh2** [comment]
It has my support

**Comment by tillmo** [comment]
:+1:

**Comment by grijalva10** [comment]
Is there any update on this feature?

**Comment by tillmo** [comment]
I still think that this is a good feature. This thread is stale only because noone seems to take care of the implementation.

**Comment by tienhm0202** [comment]
I can be a good integration with [pytracking](https://github.com/powergo/pytracking)

Just add:

1. Format function to modify email content before sending
2. APIs endpoint to handle event tracking (basically open and click)
