### ISSUE TITLE
Rate and Quantity Contract / Blanket Order

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#13733]
Fixed price + max qty contracted, purchase orders will be released periodically against a rate contract

### 
- [x] Selling or Buying
- [x] Customer and Supplier + Billing Address
- [x] From / To Date
- [x] Item table (item, forcasted qty and rate[mandatory], order qty)
- [x] terms and conditions

###

create sales and purchase order from the blanket order

**Comment by dottenbr** [comment]
https://github.com/frappe/erpnext/issues/14675
