### ISSUE TITLE
Report: Batch - Source Document Name Column

### ISSUE THREAD

**Issue by jayfiro** [frappe/erpnext#13758]
In Report Builder for Batch, if one chooses Source Document Name as a column, the source document cannot be accessed and a _DocType reference_doctype not found_ error occurs. This seems to be happening because the link takes us to ~/desk#Form/reference_doctype/PREC-02044 rather than ~/desk#Form/Purchase%20Receipt/PREC-02044 in this case. 

![report_batch](https://user-images.githubusercontent.com/23268734/39099763-99364914-464d-11e8-8ac5-9a255e072a09.png)

![report_batch_error](https://user-images.githubusercontent.com/23268734/39099765-9cff3d80-464d-11e8-879d-465e9404be4d.png)

**Comment by rohitwaghchaure** [comment]
Hi @jayfiro 

Pickup column Source Document Type in the report and check
![to_check_route](https://user-images.githubusercontent.com/8780500/39581550-76b8cc12-4f09-11e8-9260-a5f3d9259fec.gif)
