### ISSUE TITLE
Trial Balance for Party Report

### ISSUE THREAD

**Issue by mosabamf** [frappe/erpnext#13756]
In this report "Trial Balance for Party" you can only select "Customer or Supplier" in Party Type while it should be available for all party types in the system "Employee, student, ...etc"

![image](https://user-images.githubusercontent.com/21178114/39093112-9051d622-4609-11e8-8e54-63fce8923e83.png)

**Comment by mosabamf** [comment]
+1

**Comment by nabinhait** [comment]
Fixed via #13831
