### ISSUE TITLE
ImportError: Module import failed for Leave Application (erpnext.hr.doctype.leave_application.leave_application Error: No module named employee_leave_approver.employee_leave_approver)

### ISSUE THREAD

**Issue by essadek** [frappe/erpnext#13751]
`ImportError: Module import failed for Leave Application (erpnext.hr.doctype.leave_application.leave_application Error: No module named employee_leave_approver.employee_leave_approver)`

The above error is occurring on a manual install, I have tried with `bench update --build` but doesn't change a thing.
erpnext 10.1.23
frappe 10.1.24
mysql  Ver 15.1 Distrib 10.0.32-MariaDB,
Debian 8

**Comment by fabyc** [comment]
I get same error in a fresh installation of ERPNext in a new server. I just downloaded it and tried to install it in a new site.

erpnext 10.1.23
frappe 10.1.24
mysql  Ver 15.1 Distrib 10.2.14-MariaDB
Ubuntu 16.04.4

Thanks

**Comment by shreyashah115** [comment]
Thanks for reporting the error. It has been fixed, will be merged soon.

**Comment by essadek** [comment]
After updating frappe/erpnext yet another error stopped the installation : 

ImportError: Module import failed for POS Profile (erpnext.accounts.doctype.pos_profile.pos_profile Error: No module named cache_manager)

Is this another bug ?!
