### ISSUE TITLE
When I sync to Shopify stock availability for items automatically get checked 

### ISSUE THREAD

**Issue by ghost** [frappe/erpnext#13767]
1m
Dear all
I have connected ERPNext with Shopify through private app,
when I register items in ERPNext I un-check their stock availability but after sync to Shopify stock availability of all items automatically get checked in ERPNext.
I don’t know where is the problem

ERPnex v10.1.17
please help me if anyone knows the issue
thanks

Before sync when I register
![stock uncheck](https://user-images.githubusercontent.com/36146142/39125527-14f4ec0c-46b4-11e8-9075-3ed350449dd5.PNG)
After sync 
![stock checked](https://user-images.githubusercontent.com/36146142/39125543-25301380-46b4-11e8-8b2c-d049e34fc9a5.PNG)

**Comment by adityaduggal** [comment]
Since this issue is related to a private app its better to be posted on forums does not seem like an erpnext issue.
