### ISSUE TITLE
PDF not generating for Report

### ISSUE THREAD

**Issue by nabinhait** [frappe/erpnext#13779]
![report pdf](https://user-images.githubusercontent.com/836784/39186743-1184e1ae-47e9-11e8-9ab2-d6d025ebdecc.gif)

**Comment by Zlash65** [comment]
![pdf](https://user-images.githubusercontent.com/11695402/39292069-ae4d54b6-4952-11e8-9da5-49b7b6e671e7.gif)

**Comment by SaiFi0102** [comment]
I have set the 'always show popup' so I can't click on the blob link and the report and the new tab closes immediately. This doesn't seem to be fixed yet.
