### ISSUE TITLE
[BUG] Purchase Order getting linked to unrelated Stock Entries

### ISSUE THREAD

**Issue by djpalshikar** [frappe/erpnext#13777]
Steps to Recreate

1. Click Stock Entry on any Purchase Order- 0001

2. The Stock Entry list appears with filter as Purchase Order = "PO-0001". It could also be a blank list.

3. Create a new unrelated stock entry of any type other than Subcontracting - for e.g. Transfer Stock Entry. Submit it.

4. Now check the Purchase Order again. It will show the stock entry linked to the Purchase Order.

Stock Entry should **only be** linked to a Purchase Order only in case of Subcontracting.

WN-SUP32519

**Comment by djpalshikar** [comment]
I can confirm that the bug affects V11 also.

**Comment by deepeshgarg007** [comment]
@djpalshikar Closing this issue, if this is still replicable in lastest version 13 or above please reopen a new issue
