### ISSUE TITLE
Reports created using Report Builder is not showing Filters section

### ISSUE THREAD

**Issue by nabinhait** [frappe/erpnext#13780]
<img width="1170" alt="screen shot 2018-04-24 at 6 01 17 pm" src="https://user-images.githubusercontent.com/836784/39186942-89e0a4b2-47e9-11e8-8ee7-20ff807721aa.png">

**Comment by Zlash65** [comment]
![pdf](https://user-images.githubusercontent.com/11695402/39292069-ae4d54b6-4952-11e8-9da5-49b7b6e671e7.gif)
