### ISSUE TITLE
[POS] TRASLATION FIX 

### ISSUE THREAD

**Issue by vladucoju** [frappe/erpnext#13799]
Hello, 
there is no option to translate some pos fields over the translation portal. I marked fields in picture below

![translate](https://user-images.githubusercontent.com/9590909/39250533-4c39a3d0-48a1-11e8-9feb-eb731157ca76.png)

**Comment by mhbu50** [comment]
@vladucoju I fixed this issue and get merged

https://github.com/frappe/erpnext/pull/14765

You can close this now

**Comment by vladucoju** [comment]
Great work @mhbu50
