### ISSUE TITLE
BUG - 'Is Purchase Item' not getting filtered out in Sales Order & Sales Invoice

### ISSUE THREAD

**Issue by bibinqcs** [frappe/erpnext#13793]
Hi All,

Just noticed a bug in the items table in sales order and sales invoice, item code link field does not filter items with 'is purchase item' checked.

Thank you

**Comment by umairsy** [comment]
Can you please check if "Is Sales Item" is also checked for that Item?

**Comment by bibinqcs** [comment]
It was a custom script error.
