### ISSUE TITLE
Option to calculate Finished Good Item Cost, based on Source Raw Materials 

### ISSUE THREAD

**Issue by kothagunda** [frappe/erpnext#13815]
We are using Stock Entry features Repack and Manufacture. In these documents, we add source raw material (with source WH) and final finished good (with target WH).

But the finished good base rate is fetched from valuation rate of the item, and the document shows that Total Difference value is not 0, (incoming - outgoing). As raw material rates keep changing and valuation of finished goods dont always match with raw material sum.

It would be good if the base rate is automatically calculated from the source raw materials so that the difference value is 0. This way the valuation rate of the finished goods get the right value when raw materials rate change.

As a work around what we are doing is that, we are adding all the source raw materials cost and setting this value in the finished good base amount, every time we create a new repack/manuf.

Example:
Assume Finished good FG is made of raw materials R1 and R2 whose valuation rate is 100 and 50 respectively. Assume that the valuation rate in the system for FG is currently 200/-. Now if i create a stock entry with manuf, it shows difference amount of 50/-.I would think that the FG rate in this document should be calculated based on R1 and R2 valuation rates. As this is the genuine rate.

May be a checkbox should be given in the manuf/repack docs, to set the finished good basic rate to the sum of raw materials, so that difference amount = 0. 
Then if there are any additional charges that can be added below in the additional charges section.

Creating the issue based on comments from @umairsy 
https://discuss.erpnext.com/t/in-repack-manuf-calculate-finished-good-rate-from-source-raw-materials/36152/4

**Comment by Coolblogsab** [comment]
I think this feature already exists.

Check my comment at https://discuss.erpnext.com/t/in-repack-manuf-calculate-finished-good-rate-from-source-raw-materials/36152/6

**Comment by kothagunda** [comment]
Yeah @Coolblogsab , you are right. If i use that checkbox, the finished good basic amount is automatically calculated from the source raw materials and updated so that the difference value is 0.

I think it would help if the name of the checkbox could be updated to something like "calc base rate from source items"
