### ISSUE TITLE
Restrict online sales only to certian locations

### ISSUE THREAD

**Issue by kothagunda** [frappe/erpnext#13813]
Hello
As suggested by @umairsy , opening this issue.

https://discuss.erpnext.com/t/how-to-restrict-online-sales-only-in-our-city-limits/36221

1. In erpnext online shop, it would be good if we could have functionality to restrict sales only for shipping addresses to a certain range of zip codes (or district, or state, or country). Because for various reasons, we may not be able to deliver out of city/state/country etc.

2. It would also be nice if we could have separate restrictions on separate  item groups. For example, perishables like vegetables we may restricted to city limits. For processed foods and other bulk items, we may allow out of state also. 

Pls consider this enhancement.

**Comment by saurabh2804** [comment]
Were you able to implement any workaround for this. Only allowing certain Addresses in the shipping address may be done, but how did you do the item group wise restriction?

**Comment by kothagunda** [comment]
@saurabh2804 We had to enable developer mode, add a new address-new docType which has only certain zips in dropdown to restrict the customers to a certain zip codes.

Did not do the item group use-case though.

**Comment by saurabh2804** [comment]
Are you still looking to implement the item group use-case?

**Comment by kothagunda** [comment]
No. Not as of now.
