### ISSUE TITLE
Moving Comment Section on Pages

### ISSUE THREAD

**Issue by RSKROGER** [frappe/erpnext#13819]
Are we able to move the comments section on certain documents to the top of the page? 
 
For example, are we able to move this section on top of a sales order so that our users can see all the comments before they see the order details?

**Comment by rohitwaghchaure** [comment]
Click on comments(top left), 
![comments](https://user-images.githubusercontent.com/8780500/39516497-bdcefc38-4e1a-11e8-9dfa-0321eb9cbc5e.gif)

**Comment by RSKROGER** [comment]
Hi Rohit,

I understand that it will not look visually too appealing; however, it would be very helpful to have the option to move it to the top on certain documents. 

For example, if an order is placed with specific details that anyone working on it should know, it would be important that the comments are the first thing the user sees. This will ensure that important details aren't missed.

Would it be possible to develop this as an option for users?

**Comment by jaichavan** [comment]
Hello, @RSKROGER 
Your concern of viewing comments can be addressed with the current UX/UI because it's the first thing that any user will perceive when a document is opened. You can ensure amongst your team to always check comments when any document is opened, as a standard practice.

**Comment by Ravn10** [comment]
Well it can better be placed in right sidebar as its empty.

**Comment by RSKROGER** [comment]
Hi Jai,

Can you please elaborate on the current UX/UI? Perhaps you have a screenshot you can share with regards to the update?

Please let me know.

**Comment by RSKROGER** [comment]
@jaichavan

**Comment by jaichavan** [comment]
The current UX is the one which Rohit has mentioned in the previous comment. As said before, you can ensure amongst your team to **always check comments** when any document is opened, as a standard practice.
