### ISSUE TITLE
Purchase order purchase invoice stock adjustment

### ISSUE THREAD

**Issue by Albatros79** [frappe/erpnext#13826]
hello everyone 
My problem is 
 for example when we have 5 purchase order containing same product and total of those 5 purchase order makes 20 pcs. when the manufacturer send those items to me with one invoice (20 pcs) it is not reducing it from purchase orders and it is regarded as a new purchase without a purchase order.

could you fix it?

Best Regards

**Comment by kennethsequeira** [comment]
You can make a single purchase receipt for all the sales orders by simply using **Get Items from** button.

![image](https://user-images.githubusercontent.com/33246109/39427861-f61a37ca-4ca2-11e8-8213-7f5c5e746fe6.png)

Here you can select all pending Orders against a supplier. After you make the receipt you can make a single invoice and process payment against it.

Would request you to post such questions on the Forum: https://discuss.erpnext.com
