### ISSUE TITLE
Stock availability of items get checked automatically after sync to shopify

### ISSUE THREAD

**Issue by ghost** [frappe/erpnext#13825]
Hello everyone!
in our case we don't have warehouse, we just sale for suppliers, so I don't check stock availability of items in ERPNext v10.1.17, but if items already exist in Shopify, after sync stock availability gets checked automatically in ERPNext.
I don't know what I'm missing, please help me,

**Comment by ankush** [comment]
This feature is removed from core and doesn't apply to new connector: https://github.com/frappe/ecommerce_integrations
