### ISSUE TITLE
Gross Margin ignores Stock Entry

### ISSUE THREAD

**Issue by HNaga** [frappe/erpnext#13829]
self.gross_margin = flt(self.total_billed_amount) - (flt(self.total_costing_amount) + flt(self.total_expense_claim) + flt(self.total_purchase_cost))

it ignores total_consumed_material_cost
This assumes the all stock entries are rated to Purchase orders linked to the project.
I think the formula should consider total_ourchase_cost linked to the project and Stock Entries  linked to the project with (Purchase orders not linked to the project)

Purchase Order for 100,000 e.g unit of raw material  R 1(used with other materials to produce a certain products) to cover production of 1 or 3 months (Not linked to a project)

**Comment by nabinhait** [comment]
Currently in Stock Entry, there is no way to identify from which PO, the items came from.

**Comment by HNaga** [comment]
that mean that margin will remain wrong?

**Comment by franciscobuendiao** [comment]
@nabinhait isn't necessary to know from which PO items came, but to know to which Project will take effect.

@HNaga wrote and it is correct:
https://discuss.erpnext.com/t/project-gross-margin-is-this-calculated-correctly/36213

Also, I have noticed that if any Stock Entry is deleted, the amount at 'Total Consumed Material Cost  (via Stock Entry)' field, is not updated.

**Comment by HNaga** [comment]
@nabinhait  it.s necessary to know PO if PO is linked to the project otherwise it should take the consumed stock value which is linked to the project

I see that Project Cost needs many fixes
it should consider Journal entries linked to the project
it should consider shipping , transportation cost
consumed stock value as mention 
depreciation and amortization share
