### ISSUE TITLE
"Invite as User" - You are not permitted to access this page.

### ISSUE THREAD

**Issue by franzos** [frappe/erpnext#13828]
A customer that has been invited via "Invite as User" ends up on "You are not permitted to access this page." at the URL https://domain.com/desk.

1. Create customer
2. Add contact
3. Invite as user (email gets send out)
4. Complete Registration > Set Password
5. You are not permitted to access this page. (https://domain.com/desk)

- Deleting "/desk" from the URL redirects back to "/desk"
- Manually navigating to "/me" works

ERPNext: v10.1.23 (master)
Frappe Framework: v10.1.23 (master)

This is a fresh set-up and I haven't messed around with the website settings yet. What could be causing this? Thanks in advance!

**Comment by joolsr** [comment]
I *think* a PR has been recently added to Develop that will fix this and other related issues.

**Comment by surajshetty3416** [comment]
Seems that this [PR](https://github.com/frappe/frappe/pull/4661) has fixed the issue on develop
