### ISSUE TITLE
Incorrect password on Downloads page

### ISSUE THREAD

**Issue by tarsiswt** [frappe/erpnext#13823]
The [Downloads](https://erpnext.com/download) page claims that default credentials for the application are Administrator/frappe when in fact they are Administrator/admin.

**Steps to reproduce**

1. Download VM image from the [Downloads](https://erpnext.com/download) page
2. Import into VirtualBox
3. Boot up the Image
4. On the host system point browser to http://localhost:8080
5. Fill in form with Administrator as user and frappe as password
6. Get error message "Invalid Login. Try again."
7. This time fill in Administrator as user and admin as password to get logged in

**Comment by jaichavan** [comment]
Hello, @tarsiswt 
Thanks for reporting. We have updated our page. For your reference: **https://erpnext.org/download**
