### ISSUE TITLE
Changelog/audit log of changes to document

### ISSUE THREAD

**Issue by lxnow** [frappe/erpnext#1383]
Maintain a changelog or audit log of changes made to every saved and submitted document, including:
- change in status
- addition of comments, deletion of comments
- change in value for fields that are changeable after submit
- attachments added or removed
- printed (to PDF)
- emailed (to recipient)
- any other changes I might be missing here

Can ignore draft documents.

The audit log will only record values that actually changed, i.e.

old value: docstatus == 1
new value: docstatus == 2

or another example:

old value: custom_field == "xyz"
new value: custom_field =="abc"

or another example:

old value: no email
new value: emailed to person@x.com

Naturally, the log would maintain a system and user-independent date and time stamp and which user made the changes

**Comment by umairsy** [comment]
Feature added in version 8.
