### ISSUE TITLE
Email Notification To and CC autocomplete - permission issue or bug

### ISSUE THREAD

**Issue by deepak727** [frappe/erpnext#13848]
Hi

I have already created this thread in erpnext community.

Please refer the following link.

https://discuss.erpnext.com/t/email-notification-to-and-cc-autocomplete-permission-issue-or-bug/36239

The main agenda of this thread is I am able to see the email address of the restricted contacts in email pop form.

If this is happening with others as well then it is a security loophole which should be fixes ASAP.

Regards,
Deepak Singh

**Comment by Zlash65** [comment]
The fix will be released with v11 as it went through a no. of fixes and have become stable enough now.
