### ISSUE TITLE
Website Product grid "show not in stock"

### ISSUE THREAD

**Issue by amitsaxena01** [frappe/erpnext#13852]
The product list in the website keeps showing "Not in Stock" although both Enable Shopping Cart and Show Quantity in Website are unchecked in the Shopping Cart Settings.

**Comment by manassolanki** [comment]
hi @amitsaxena01 
This is functioning properly for stock and non-stock items. The message "Not in Stock" is visible for the stock items when there isn't any sufficient stock.

#### Coffee Mug (Stock Item) when available in stock
![image](https://user-images.githubusercontent.com/20757311/39886446-20773d6c-54ad-11e8-817d-78b1837fc685.png)

#### Coffee Mug (Stock Item) when there isn't sufficient stock
![image](https://user-images.githubusercontent.com/20757311/39886508-4692cbba-54ad-11e8-8774-db5be4450bd8.png)

####Note: iphone and kindle are non-stock items

If you are expecting some other functionality, please let us know.

I am closing the issue for now, if the issue still persist, feel free to reopen it.

**Comment by amitsaxena01** [comment]
@manassolanki If the "Enable Shopping Cart" and "Show Quantity in Website" are **unchecked** then the user only wants to display the product and doesnot want to inform about the availability of the products. In that case it should not show either "Not in Stock" or "In Stock" which the website currently shows.

-Amit
