### ISSUE TITLE
[v11][Testing] Hub

### ISSUE THREAD

**Issue by nabinhait** [frappe/erpnext#13861]
- [x] Icon missing [1]
- [x] Deselection of category (add Category as filter too?)
- [x] Clicking on company takes me to a form, should filter by company
- [x] Can't open product page [2] (too much recursion in JS console)
- [x] Does not show title in product

![screen shot 2018-05-24 at 10 57 36 am](https://user-images.githubusercontent.com/140076/40468947-91ae4bf2-5f4c-11e8-857d-1eda9ef5928f.png)

![screen shot 2018-05-24 at 12 20 56 pm](https://user-images.githubusercontent.com/140076/40469084-01b380c0-5f4d-11e8-998c-6d560de06c7f.png)

**Comment by pratu16x7** [comment]
https://github.com/frappe/erpnext/pull/14281
