### ISSUE TITLE
Product Bundle in purchase cycle

### ISSUE THREAD

**Issue by nabinhait** [frappe/erpnext#13879]

**Comment by erpuser** [comment]
We are trying to create a Product Bundle wherein using the following field:

DocType:    Asset
Column Labels:    ID
Column Name:    name
Mandatory:    Yes
Type:    Data (text)

However, in the Product Bundle Item Table there is no option of choosing the above field. It only provides Item Code as selection whereas we am looking for the above field.

Please suggest how this could be added to the Product Bundle Table
