### ISSUE TITLE
[v11][Testing] New ListView

### ISSUE THREAD

**Issue by nabinhait** [frappe/erpnext#13876]

**Comment by netchampfaris** [comment]
https://github.com/frappe/frappe/pull/5581

**Comment by surajshetty3416** [comment]
- [ ] Not able to add more filters if ID filter is already set

**Comment by Zlash65** [comment]
- [ ] wildcard hint gets appended for wildcard applicable operator selection
- [ ] tag overflow from sidebar to the list view
