### ISSUE TITLE
[v11][Testing] Reports

### ISSUE THREAD

**Issue by nabinhait** [frappe/erpnext#13870]
- [ ] Customisable Cash Flow Reports
- [ ] Employee Advance Summary
- [ ] Presentation currency in General Ledger
- [ ] Exploded view for BOM Stock Report
- [ ] General Ledger - Group by party and Filter based on multiple party
- [ ] Consolidated Financial Statements

**Comment by Zlash65** [comment]
- [ ] presentation currency once set could not be changed - fixed
