### ISSUE TITLE
[v11][Testing] Dynamic Frappe Charts with Report Builder

### ISSUE THREAD

**Issue by nabinhait** [frappe/erpnext#13874]
- [ ] Query Report

**Comment by Olawale1** [comment]
Hi

Will Query Reports be available to ERPNext Cloud users in V11?

**Comment by nabinhait** [comment]
Do you mean Query Report creation from non-admin login? In that case, the answer is no.

**Comment by Zlash65** [comment]
Also,

![chart issue](https://user-images.githubusercontent.com/11695402/42027891-6b32045c-7ae8-11e8-99ac-2a81bdc6d537.gif)

- [ ] Percentage chart gets appended when toggled console on off
- [ ] If chart is toggled on and then toggled off, then toggling it back on does not show the option to configure it again.
