### ISSUE TITLE
Sales register table view with thick columns

### ISSUE THREAD

**Issue by paramjitrohits** [frappe/erpnext#13894]
Hi, I am using the latest ERPNext (developer branch), but when I try to use Sales Register view, earlier when I could see the columns clearly, now the columns appear super thick (in terms of height), with a lot of blank space underneath the text. Does this seem like a newly introduced bug? Please help me solve this. Thanks.

**Comment by clarkejj** [comment]
A screenshot would help illustrate your issue

**Comment by paramjitrohits** [comment]
Just give me some time. Will do it by tomorrow.

**Comment by paramjitrohits** [comment]
Hey, so sorry for the delay! Was away from home. Here is a screenshot. Please let me know if you need further reports.

![thick rows in erpnext](https://user-images.githubusercontent.com/36928406/40226523-80eb0ed8-5aa9-11e8-9005-0b897db59b05.png)

**Comment by paramjitrohits** [comment]
Well, my system points to `python3` via the `python` command. It seems this bug is also related to the py2 to py3 migration. I temporarily fixed it by moving my system symlinks of python to point to python2 and bench updating.
