### ISSUE TITLE
Upload Historical Data Using Same Document Sequences 

### ISSUE THREAD

**Issue by mikladious** [frappe/erpnext#13895]
Hello, 

Please advise how to upload transactional historical data considering the following; 
1- Data Source [ERPNext-Production instance] 
2- Data Target Application [ERPNext - New PROD] 
3- Document sequences should be the same especially for external entities, such Suppliers and Customers
3-A Suppliers may include Purchase Orders, Purchase Invoice...etc.
3-B Customers may include Quotation, Sales Orders, Sales Invoice...etc.

This is a step of data cleansing and reimplementation.
Expecting your appreciated support and feedback.

Regards,
Magdy

**Comment by kennethsequeira** [comment]
@mikladious 

Have a look at [Data Import Tool](https://erpnext.org/docs/user/manual/en/setting-up/data/data-import-tool.html).

And please post these queries on the [community forum](https://discuss.erpnext.com).
