### ISSUE TITLE
In department leave approvers and expense approvers showing all the users

### ISSUE THREAD

**Issue by rohitwaghchaure** [frappe/erpnext#13906]
![screen shot 2018-05-03 at 3 49 43 pm](https://user-images.githubusercontent.com/8780500/39571598-9f12d59c-4ee9-11e8-9f18-402c30071198.png)

- [ ] Show list of users who has role Leave Approver in the leaver approvers and Expense Approver in the expense approvers

**Comment by shreyashah115** [comment]
@rohitwaghchaure, it is supposed to be like this instead of role based.
