### ISSUE TITLE
Not able to get leave approver name in dropdown

### ISSUE THREAD

**Issue by worldofsmarty** [frappe/erpnext#13914]
While applying the leave i was getting an error of HR Settings, Later i fixed by giving permission for HR Setting for that group. 

Secondly i am not getting any leave approver names in the dropdown list. I dont know how to get those i have checked all the settings pertaining to that and i guess all are in place, infact i have not modified a single settings from the default.

Am I doing anything wrong

Have attached the screenshots for the reference
![screen shot 2018-05-03 at 10 28 40 pm](https://user-images.githubusercontent.com/5152491/39592344-1603828e-4f24-11e8-9414-69aa0362fe75.jpg)

![screen shot 2018-05-03 at 10 26 29 pm](https://user-images.githubusercontent.com/5152491/39592345-163f429c-4f24-11e8-9b40-7dd9e28f3d5c.png)

![screen shot 2018-05-03 at 10 19 44 pm](https://user-images.githubusercontent.com/5152491/39592346-167be418-4f24-11e8-8024-2a4079a8fa6a.jpg)

**Comment by shreyashah115** [comment]
Hi @worldofsmarty, which version are you on? If on develop, there have been some changes to the flow of Leave Approval. You need to set the Leave Approvals in the Department doc for the Employee you are making a Leave Application for.

**Comment by madhu6759** [comment]
Hi @shreyashah115, In my case, I have updated my ERPNEXT v8 to v11.But now I am getting an error in Leave approver.I cant able to view the leave approver user even i have enabled in HR settings
