### ISSUE TITLE
Missing default accounts in Company doctype

### ISSUE THREAD

**Issue by ryuliantoro** [frappe/erpnext#13938]
In the Company doctype there are some fields that hold the default account (from CoA). But some fields are missing the value. I see from the company.py that those accounts are not coded to fill the fields.
I tried to add those accounts to the fields and raise a PR. But perhaps since I'm not a programmer my PR got rejected.

Maybe some one can do the coding for it? The PR is [#13937](https://github.com/frappe/erpnext/pull/13937)

**Comment by Zlash65** [comment]
https://github.com/frappe/erpnext/pull/13937
The PR seems to have been merged. Closing the issue.
