### ISSUE TITLE
GSTR-2 report erroneously bifurcates IGST of Purchase invoices into CGST and SGST

### ISSUE THREAD

**Issue by intelliant01** [frappe/erpnext#13963]
GSTR-2 `Script report` erroneously bifurcates IGST of Purchase invoices into CGST and SGST. 

**Steps to replicate:**
Create and submit an inter-state purchase invoice between 2 GST registered entities. Ensure that the a tax charge under account head IGST has been added.
Check the GSTR 2 report.

**Actual:**
The IGST amount has been incorrectly bifurcated under CGST and SGST. The bifurcated amounts are also incorrect (slightly less than half of the IGST).

**Expected:**
For the submitted invoice, it should have IGST amount and no bifurcation should have happened.

![gstr2_error](https://user-images.githubusercontent.com/2577060/39760085-085f1c98-52f2-11e8-91d4-9e89f4e1dddc.gif)

ERPNext: v10.1.28 (master)
Frappe Framework: v10.1.28 (master)

**Comment by PawanMeh** [comment]
![gstr2-fixed](https://user-images.githubusercontent.com/20460498/47209500-2565d100-d3ae-11e8-81a7-2ee323b67731.png)
