### ISSUE TITLE
Freeze accounting entries based on number of days

### ISSUE THREAD

**Issue by erpuser** [frappe/erpnext#13969]
We are in the midst of closing our books 

Currently ERPNext does not allow restricting accessing entries or inputting data on the basis of date - 

1. A point in time. For eg- 31/03/2018 - We would like to restrict access to data of previous year for most employees once the books are finalised. Only certain keys members will be provided access to historical data. 

2. On the basis of the number of days. For eg - 60 days from the present date.

We have for both cases.

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.
