### ISSUE TITLE
Stripe Elements update

### ISSUE THREAD

**Issue by heatherpotter** [frappe/erpnext#13966]
Stripe Elements is the replacement for Stripe Checkout popup. Can ERPCloud be updated so the pay now screen uses Elements instead of Checkout?

https://stripe.com/elements
https://stripe.com/docs/stripe-js/elements/migrating

It doesn't appear that is would take much effort to do.

**Comment by epe** [comment]
Thanks for noting. Stripe Integration should also be updated to be able to choose from the different payment methods Stripe offers. See here: https://discuss.erpnext.com/t/stripe-payment-methods/39764

**Comment by chdecultot** [comment]
Hi,

Stripe Elements have been implemented in Frappe and are available in v11:
https://github.com/frappe/frappe/pull/5602


I propose to close the PR and you can maybe open a new issue specific to the different payment methods.
