### ISSUE TITLE
Type to search in fields does not follow Translation/Localisation

### ISSUE THREAD

**Issue by epe** [frappe/erpnext#13977]
Search Term is not searched in users language.

Example: 
Use Erpnext in German and go to New Data import page  (desk#Form/Data Import/Import....) 
Click Doctype Field and enter Search string 

When entering "Item" , the Field correctly shows "Artikel - Lager"   which is the german translation. 
When entering Artikel (Item in german) it doesnt find anything. 
Problem: German user doesnt know or search in english language.

**Comment by epe** [comment]
Same happens in Item Master >  Foreign Trade Details > 	Country of Origin Field:

English: Netherlands 
German: Niederlande

If I type Neth.. I find: Niederlande
A german speaking (maybe not-at-all english speaking user) would never  be able to select Niederlande if he doesnt know the translation!

![menu_174](https://user-images.githubusercontent.com/1019288/40047388-a371a15a-582f-11e8-84d1-023c906a39fa.jpg)
![menu_175](https://user-images.githubusercontent.com/1019288/40047394-aac3ad72-582f-11e8-8f16-38f0eab17077.jpg)

**Comment by kennethsequeira** [comment]
Confirming the error in translation

![image](https://user-images.githubusercontent.com/33246109/40048525-189e39fa-5850-11e8-8b9f-a292cee2c5fc.png)

![image](https://user-images.githubusercontent.com/33246109/40048576-3719d0ba-5850-11e8-8976-bc48256ee983.png)

**Comment by yeisonvargasf** [comment]
https://github.com/frappe/frappe/pull/5745 will solve this issue.
