### ISSUE TITLE
Print Profit and Loss Statement

### ISSUE THREAD

**Issue by franciscobuendiao** [frappe/erpnext#13972]
Please include:
**Cost Center** isn't printed and it's important. 
![profit_and_loss_statement_3](https://user-images.githubusercontent.com/25084259/39819251-9907fd98-5368-11e8-9ce2-a3a2cfd9555e.jpg)

**Currency Precision** is set to 2 on System Settings.
![system_settings](https://user-images.githubusercontent.com/25084259/39818938-bb5bd6e0-5367-11e8-8163-729cda721bf5.jpg)

And so it's applied at Profit and Loss Statement report.
![profit_and_loss_statement](https://user-images.githubusercontent.com/25084259/39819039-06c53da6-5368-11e8-83b8-27a288bc15a6.jpg)

But not when printing...
![profit_and_loss_statement_2](https://user-images.githubusercontent.com/25084259/39819141-4dfde2d6-5368-11e8-90f1-638c2aeb9dd5.jpg)

**Comment by harshit-30** [comment]
Please create another issue if it is replicable after v13.10.
