### ISSUE TITLE
Tool for multi account creatin - is it possible ?

### ISSUE THREAD

**Issue by Netoperz** [frappe/erpnext#13974]
Hello, i have got one little question, we have a few student projects that want to use ERP , all that projects are from a few universities  and from different classes , so we need one main account, and than possibility to give acess to the "administrators" of the "local" branches to give local instances of erpNEXT to the student teams.

So it is something alike the reseller tool you may have. That is the closest thing i can think about as a solution.
Is there a way to run it locally on our main server in main univercity in cracov ? Is it opensource or is it only your properitary software ?

We have got another ERP that has got those functions, but it's a bit buggy and build on old angular so hard to manage and not very good thing for mobile devices.
Having that kind of functionality here would be a blessing.
If it is somewhere and i did not noticed that than i'm sorry for taking Your time to asking stupid questions.
So please tell me how can i get that to wor and is it possible with ERPnext or not ?

thx

**Comment by Netoperz** [comment]
I think that i'm looking for multi tennant configuration as far as i can see checking the doc's.

**Comment by kennethsequeira** [comment]
@Netoperz 

You will be basically creating new "sites" using the `bench new-site <sitename>` command. Each of these will be a new instance of ERPNext which each class/student group can access and will be independent of each other.

Perhaps you would like to move this discussion to the community forum: https://discuss.erpnext.com
