### ISSUE TITLE
PDF formate Option in Auto Email Report

### ISSUE THREAD

**Issue by rkr00t** [frappe/erpnext#13999]
In Auto Email Reports by default, we have report Format as HTML, XLSX & CSV. 
How to add PDF option in this. this is a good feature to send reports in PDF format for a better view on mobile devices and tablets.
![Auto Email Report PDF](https://user-images.githubusercontent.com/9102676/39955953-58554744-55f5-11e8-879a-38f0b5039f67.png)

**Comment by Mishaal1021** [comment]
Any update on this?

**Comment by cyberdee** [comment]
this will be great! can add the TOTAL row also when sending in pdf...

**Comment by Double-Click-ERP** [comment]
Any update on this?

**Comment by TurkerTunali** [comment]
That would be nice.
