### ISSUE TITLE
Multiple Purchase Receipt created against Purchase Order. 200% qty received.

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#13990]
For a single purchase order (PO 00006), we have made a purchase receipt (PREC 006) for full quantity & kept in a draft mode(Just saved it and not submitted). We have made another purchase receipt (PREC 007) against the same PO 00006 & even that is also in saved in draft mode.

Next, when we submitted those two purchase receipt which were in  drafts (PREC 006 and PREC 007), the system allowed us to submit the Purchase Receipts. This leads to double the Qty received in stock and also multiple Purchase Invoices in full quantity against one Purchase Order.

**Comment by nabinhait** [comment]
@umairsy Can you replicate it in your test account?

**Comment by umairsy** [comment]
Didn't replicate.

<img width="1246" alt="screen shot 2018-09-07 at 7 43 15 pm" src="https://user-images.githubusercontent.com/910238/45223930-4da1e080-b2d6-11e8-9500-7c72dcba05d0.png">
