### ISSUE TITLE
[v11] Error on viewing Patient medical record

### ISSUE THREAD

**Issue by shreyashah115** [frappe/erpnext#14008]
<img width="1045" alt="screen shot 2018-05-14 at 11 55 14 am" src="https://user-images.githubusercontent.com/17617465/39981314-bdcd9652-576d-11e8-88be-7913947d6462.png">

```
VM2270:117 Uncaught (in promise) TypeError: frappe.ui.BaseList is not a constructor
    at <anonymous>:117:18
    at Object.with_doctype (model.js:97)
    at draw_page (<anonymous>:116:15)
    at o.change (<anonymous>:22:5)
    at base_control.js:168
```

**Comment by palashjhabak** [comment]
@shreyashah115 since you have closed this, do you by any chance have solution for this?

**Comment by cyberdee** [comment]
Hi... the latest version V11 is still having the same issue... any solutions? or this will be available on the next patch?

**Comment by Umer2560** [comment]
ads

**Comment by Umer2560** [comment]
Hii...
I have fixed this error by adding these 2 lines to js/list.min.js under frappe/public/build.json.
"js/list.min.js": [ ...
		"public/js/frappe/ui/filters/filters.js",
		"public/js/frappe/ui/base_list.js",
]
Don’t forget to bench build.
