### ISSUE TITLE
List View - Select All Delete Issue

### ISSUE THREAD

**Issue by hokgt** [frappe/erpnext#14007]
It happen on all list view, when user press select all, delete button should be appear but it is not appear until user uncheck one of the record in the list and recheck it again in order to have select all dan delete the records. 

Delete button only appear after unchecking the record, whether uncheck select all or uncheck one of the record. So even there is no single record selected, delete button is still there and when we press the button, nothing happen. 

1. When I make selection and no delete button appear
<img width="1156" alt="screen shot 2018-05-14 at 13 21 01" src="https://user-images.githubusercontent.com/15005756/39981203-bf94d534-5779-11e8-808a-830bffca4519.png">

2. When I deselected one of the record, delete button appear
<img width="1168" alt="screen shot 2018-05-14 at 13 21 57" src="https://user-images.githubusercontent.com/15005756/39981226-d9137fba-5779-11e8-936d-bd2358a5e724.png">

3. Reselect and it's working
<img width="1159" alt="screen shot 2018-05-14 at 13 22 41" src="https://user-images.githubusercontent.com/15005756/39981242-eecc84be-5779-11e8-9250-9cbe18e4e19d.png">

**Comment by hokgt** [comment]
<img width="600" alt="screen shot 2018-05-23 at 05 59 43" src="https://user-images.githubusercontent.com/15005756/40394662-8fd7af20-5e4e-11e8-9857-3d2e593fe7cd.png">

Whether on premise or erpnext cloud subscription has the same problem. Above is version from erpnext subscription and i'm using browser safari.

**Comment by shreyashah115** [comment]
Not able to replicate.
