### ISSUE TITLE
analyse the expenses (direct - indirect) according to cost centers on production

### ISSUE THREAD

**Issue by hhfarid** [frappe/erpnext#1400]
We need to analyse the expenses (direct - indirect) according to cost centers, and then distribute it over the full production of a period (Month), which was produced during the period share of expenses (direct - and indirect).

Then Create a Journal entry as shown:
![cc1](https://f.cloud.github.com/assets/1675845/2102551/3fd2fffa-8f60-11e3-97da-f0ee0ebfa87c.jpg)
![cc2](https://f.cloud.github.com/assets/1675845/2102553/49601846-8f60-11e3-9e84-294650c4e103.jpg)

**Comment by joezsweet** [comment]
Closing now, please reopen with a better description of the feature and a mockup of what's needed, thx
