### ISSUE TITLE
Print Format - If Item Code are same, then merge them into one row

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#14003]
Print Format - If Item Code are same, then merge them into one row

For the sake of maintaining reference to the previous document, you can have separate rows in the table. but for the ease of understanding of the third party, it will be good to merge them in one row.

**Comment by umairsy** [comment]
@umaepoch I recollect you have some experience on developing on such print format?

**Comment by umaepoch** [comment]
@umairsy 

Yes, I had used groupby. Check out this link on discussion forum.

https://discuss.erpnext.com/t/how-to-combine-same-item-in-a-single-row/29894/14

**Comment by umairsy** [comment]
@umaepoch thanks for sharing the link. We are discussing about adding this as a generic feature in the Print Settings.

@rohitwaghchaure  your inputs on the Uma's response and how it could be helpful in productizing will be helpful.

**Comment by umairsy** [comment]
Feature already available in Purchase Order and Sales Order.

https://github.com/frappe/erpnext/issues/14115
