### ISSUE TITLE
[Paid Development] - MS project integration

### ISSUE THREAD

**Issue by ahmedmgc** [frappe/erpnext#14022]
Hi,
We are a construction firm looking to implement ERPnext and some limitations have been putting us back. 

Hence, I am looking for a project management tool integration with ERPnext in such a way that would:

1) Enable ERPnext to pull all the relevant information out of a MS project file (or any other project managament software)

2) Seamlessly updates the relevant fields in the project file using user input forms in ERPnext.

**Comment by clarkejj** [comment]
Hi additional alternative options you might consider are these:
https://erpnext.org/erpnext-jobs
https://erpnext.org/bounties

**Comment by clarkejj** [comment]
"you may be able to get some momentum behind a community project"

ahmedmgc how about post what you seek on discuss.erpnext.com, with a link that points to this discussion https://github.com/frappe/erpnext/issues/14022
