### ISSUE TITLE
Option to copy Date of Sales order to Sales Invoice

### ISSUE THREAD

**Issue by Tropicalrambler** [frappe/erpnext#14033]
Currently, when you use the Make button to create a sales invoice form a sales order, the date in the new sales invoice is todays date.

It would be great to have an option in account configuration or elsewhere to configure the default date in the new sales invoice to equal the date from the sales order.

**Comment by jayfiro** [comment]
This feature would also be helpful when creating Purchase Invoice from PO or Purchase Receipt.

**Comment by rmehta** [comment]
@Tropicalrambler this is an anti pattern. The order and invoice are two separate events. I think in most cases the date should be the date of actual creation. It is also the date on the ledger posting.
