### ISSUE TITLE
password sent unexpected

### ISSUE THREAD

**Issue by epe** [frappe/erpnext#14045]
In my erpnext development instance  (latest erpnext production VM Image)  I changed the  language setting in my user settings and receive the following message and receive an email with my erpnext users password in plaintext.
![bildschirmfoto von 2018-05-15 12-17-14](https://user-images.githubusercontent.com/1019288/40051790-49bf4330-583c-11e8-9f35-1385d850d393.png)

Both are not very desirable. 
- erpnext should never need to store user passwords in plaintext!?
- Password should not be mailed when user changes their language setting.

**Comment by kennethsequeira** [comment]
Couldn't replicate

Provide your ERPNext and Frappe versions as well. 

The password is emailed only if you check the following when updating the password.

ERPNext does not store the password in plaintext.

![image](https://user-images.githubusercontent.com/33246109/40061145-e449ef98-5875-11e8-8697-a20988bf87fb.png)

**Comment by kennethsequeira** [comment]
Did you change your password by any instance when changing your language?

**Comment by epe** [comment]
No, and I was able to replicate the same when changing the users language again.

**Comment by epe** [comment]
Now it also replicated on the production server. Same as the screenshot above and the email arrived..

**Comment by shreyashah115** [comment]
@epe Can you make a gif of it showing the password update field and checkbox and then saving it?

**Comment by epe** [comment]
I didnt change anything else.
Just changed the Language Setting "de" -> "en" and confirmed. 


Sorry not sure  what you mean to make a gif of? 
Can't make a screenshot of the emailed password.

**Comment by kennethsequeira** [comment]
Record a gif of what happens when you change the language. We don't need to see the emailed password.
