### ISSUE TITLE
[Bounty $20] Add Billed Quantity field in Sales Order Item table

### ISSUE THREAD

**Issue by lxnow** [frappe/erpnext#1406]
This field represents the quantity already billed (invoiced). It complements the Billed Amt that already exists. When implemented, it should ideally be populated retroactively when added.

Will be useful to know the status of an order in one glance without having to search for the related invoice.

**Comment by umairsy** [comment]
You can get this data from report Pending Ordered Qty to Deliver.

**Comment by joezsweet** [comment]
Closing now, please reopen if needed
