### ISSUE TITLE
Custom Report: Daily Unbilled Order Items with Stock and no Stock

### ISSUE THREAD

**Issue by lxnow** [frappe/erpnext#1407]
Need functionality that does the following: send out a daily email alert that shows sales order items that were not billed due to (a) out of stock in specified warehouse locations, and (b) sales order items that were not billed but were in-stock in specified warehouse location.

Report has two components: (1) the actual reports, and (2) be included in the daily email notifications based on schedulers.  As these two components can be treated independently, I will describe them separately.
## Reports

Logic of reports:
1. Look at all sales invoices posted that day
2. Look at all the sales orders linked to invoices from step 1
3. Get all items and quantity in the sales orders from step 2 that are still _not billed_
4. Get the _total_ end-of-day inventory balance of the items in step 3 from _user-specified_ warehouses (1 or more) **from the previous day**
5. Show 1st report with the following fields:
   - item code
   - quantity still not billed
   - warehouses end of day _total_ balance from step 4
   - customer from sales order
   - sales order ID
6. Show 2nd report with the following fields:
   - item code
   - _total_ quantity still not billed from step 3, totaled
   - warehouses end of day _total_ balance from step 4
## Daily Schedule

This 2 reports described above are attached in email and sent out to specified recipients as part of the standard ERPNext notification system.

**Comment by umairsy** [comment]
Please try Auto Email Report. Closing this issue for now. Feel free to reopen if needed.
