### ISSUE TITLE
Refactor Default Naming Series

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#14085]
Default naming series for all doctypes should be the module abbreviation + doctype abbreviation + year + number

For example

Leave Application -> HR-LAP-2018-00001
Sales Invoice -> SA-INV-2018-00001
Material Request -> PU-MR-2018-00001
Salary Structure -> HR-SALSTR-2018-00001
Expense Claim -> HR-EXP-2018-00001

Write a patch that if the user has already started a series, then the old series is continued via property setter

----

- [ ] Update Naming Series
- [ ] Write Patch

**Comment by mhbu50** [comment]
Could you make it optional?

**Comment by rmehta** [comment]
it will only be done for series that have not been started!

**Comment by snvora** [comment]
Hi,

We have developed very well for maintaining multiple companies.

I propose it's better to maintain company wise naming series, to avoid manually selecting naming series all the times.
