### ISSUE TITLE
Subcontracting - Scrap Return

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#14094]
For now, sub-contracting doesn't take Scrap (as mentioned in the BOM) into consideration. Sub-contracting Purchase Receipt should have provision for the receipt of scrap as well.

**Comment by kartikkamdar21** [comment]
Hello, is there any update on this? We are facing this issue and ERPNext still does not seem to have any provision for this.

**Comment by precihole** [comment]
Hello, yes we also facing same issue. any updated?
