### ISSUE TITLE
Group same Items - Add in Purchase Receipt, Sales Quotation, Delivery and both Invoices

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#14115]
Feature already available in Purchase Order and Sales Order.

Also, rate should be averaged when items are merged.

**Comment by umairsy** [comment]
@deepak727 based on our discussion have created new Github Issue for this. Here is what we are thinking about sponsoring.

INR 20,000 for extending this feature in all the sales and purchase transactions.

[Individual membership](https://erpnext.org/members) in ERPNext Foundation.

Please let us know.

**Comment by deepak727** [comment]
Thanks
