### ISSUE TITLE
Customization question

### ISSUE THREAD

**Issue by garybsimon** [frappe/erpnext#14126]
Hi there.

I have some technical questions.
We have a development server and created some modification in the master code (in project > project.py)
The problem is, when this code is in the file, then I cant update or upgrade.
So my question is, how can I add custom codes, without a modification of the master code?
Is there any way to attach this custom code to the project.py ???

Please explain me the soution without a pain in the ass variation :)

Thank you.

B.r.: Gary

**Comment by LifeP** [comment]
The correct forum for this would be discuss.frappe.io
Good Luck

**Comment by garybsimon** [comment]
Ok Thank you.
