### ISSUE TITLE
Stock availability on website showing not in stock yet I have stock

### ISSUE THREAD

**Issue by OMNW** [frappe/erpnext#14125]
On the website, when I look at the stock, it shows I dont have stock but when I click the item and select the variant it shows that there's stock in the variant

**Comment by kennethsequeira** [comment]
![image](https://user-images.githubusercontent.com/33246109/40361132-f1b10250-5de5-11e8-9ed3-da682ee1b9be.png)

![image](https://user-images.githubusercontent.com/33246109/40361155-ff2e3bdc-5de5-11e8-88a4-4fc06364e49a.png)

**Comment by OMNW** [comment]
I think the issue has to do with item variants. The template for all variants does not have stock as per ERPNext design. Templates don't hold stock as per ERPNext design. The design should either change such that the template should hold the sum total in Qty for all the variants it should not be editable  or in the website if the variants have stock then the item has stock in the site

**Comment by netchampfaris** [comment]
This will be fixed in the new refactor of Website Module: https://github.com/frappe/erpnext/pull/15965
