### ISSUE TITLE
Work Order unicode error

### ISSUE THREAD

**Issue by neckos** [frappe/erpnext#14138]
Getting error about unicode @
https://github.com/frappe/erpnext/blob/develop/erpnext/manufacturing/doctype/work_order/work_order.py  def add_timesheet_detail

Suppose in python3 have to be changed:

`if isinstance(timesheet, unicode):` --> `if isinstance(timesheet, str):`

`if isinstance(args, unicode): `--> `if isinstance(args, str):`

**Comment by rmehta** [comment]
Maybe use `six` for this

Feel free to send a pull :)
