### ISSUE TITLE
Purchase receipt from Item not pulling item

### ISSUE THREAD

**Issue by Tropicalrambler** [frappe/erpnext#14131]
The purchase receipt link from the item is NOT pulling the item, one has to enter it manually.

**Comment by kennethsequeira** [comment]
Replicated

ERPNext: v10.1.33 (master)
Frappe Framework: v10.1.31 (master)

![purchase-reciept-bug](https://user-images.githubusercontent.com/33246109/40300069-caaf4026-5d05-11e8-805e-9bcfefcc3141.gif)

**Comment by kennethsequeira** [comment]
@Tropicalrambler 

It is pulled. You will need to select the customer/supplier to see it.
