### ISSUE TITLE
Work order, plan_days TypeError v11

### ISSUE THREAD

**Issue by neckos** [frappe/erpnext#14140]
Error in https://github.com/frappe/erpnext/blob/develop/erpnext/manufacturing/doctype/work_order/work_order.py  

`if date_diff(from_time, original_start_time) > plan_days:
TypeError: unorderable types: int() > str()`

Make plan_days to int? `int(plan_days)`

**Comment by adityahase** [comment]
@neckos Can you please share steps to replicate this?
