### ISSUE TITLE
Attendance linking to payroll

### ISSUE THREAD

**Issue by rkurungadam** [frappe/erpnext#14141]
### Company

- [ ]  Consider Attendance for Payroll

### Payroll 

- [ ] If checked calculate payroll by total no of working days - (LWP + Attendance marked absent other than LWP days)

**Comment by mghoneem10** [comment]
any updates regarding this issue ??

Will it be considered in V11 ?

**Comment by rkurungadam** [comment]
@mghoneem10  refer #14482
thanks

**Comment by hereabdulla** [comment]
is this below point satisfied?
 
- If checked calculate payroll by total no of working days - (LWP + Attendance marked absent other than LWP days)
