### ISSUE TITLE
Payment from Sales Invoice

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#14168]
Once the Sales Invoice is submitted, it should have following options for enabling faster payment.

1. The button should be visible from web link and PDF as well.
2. After Clicking the button the user will land on paypal payment page.
3. On the paypal payment page the total amount along with currency(currency can be USD, AUD, EUR, which is there in the system i.e. erpnext and paypal), of the invoice and invoice number should be fetched.
4. After the payment completion the user should divert to the specified web address i.e. our website or something else (this can be optional feature)

**Comment by umairsy** [comment]
@rohitwaghchaure  we have @deepak727 as a sponsorer for this feature. Let's validate this feature request and update accordingly.

**Comment by deepak727** [comment]
Hello Team,

Any update on this feature request, I mean is it doable ?

Regards

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.
