### ISSUE TITLE
Stock Maintenance of Items Automatically Gets Checked After 2nd Sync to Shopify 

### ISSUE THREAD

**Issue by ghost** [frappe/erpnext#14174]
Dear ERPNext Developers and Users
I have posted this issue 4 to 5 times but no one replied me, please guide me if anyone know something about this issue.

My issue is; when I register item I un-check the stock maintenance, and sync to shopify, for the first sync which item gos to shopify there is no problem but for the second sync, stock maintenance for that particular item in ERPNext get checked automatically. I’m stacked in this problem, don’t know what to do please help me.

ERPnext v10.1.33

Thank you,
![stock checked](https://user-images.githubusercontent.com/36146142/40342737-98b0df20-5da1-11e8-8827-7c685848be1a.PNG)

**Comment by ankush** [comment]
Integration removed from core and invalid now.
