### ISSUE TITLE
Reserved (Block) Quantity

### ISSUE THREAD

**Issue by AhmedSmart** [frappe/erpnext#14177]
Dear ErpNext Developer

I think this features is very important and it will improve your amazing Erp.

Right Now when we submit the sales order, we can check the reserved quantity for the items in the report "Stock Projected Qty" only.
 
what we want is when we submit sales order for customer the quantity for the item in sales order can not invoice for other customer 
 
For Example :
 
I have customer “A” and customer “B”  and I have 10 Pcs “IPHONE X”
 
I create sales order for customer “A” with “ 8PCs IPHONE X”
 
The system should block this 8 pcs from IPHONE X to customer “A” 
 
When I want to invoice 5PCs To Customer “B” the system should not accept and promote massage the you have only 2Pcs available because the other is reserved for customer “A”

**Comment by rkr00t** [comment]
It’s because you allowed Allow Negative Stock in stock settings. Just change the option.

**Comment by AhmedSmart** [comment]
Sorry Maybe you did't get my point. 

This option already disable "Allow Negative Stock in stock settings"

I talk with Mr Rohit Regrading this feature he said to me it's not there in the ErpNext and he suggest to me to open Github issue

Thank you for your reply

**Comment by itskaps** [comment]
any update?

**Comment by sapna-kcs** [comment]
any update if this is existing feature?
current on ecommerce website, order is placed and paid for an item
Why does item show 'Not in Stock'

**Comment by azriotech** [comment]
Team ERPNext, this is a very important feature we missed here on ERPNext. Is there any progress on this front?
