### ISSUE TITLE
[Proposal] Item Tax Template

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#14187]
The goal of this proposal is to refactor Item specific taxes. Currently ERPNext does not allow to set row-level taxes in the order/invoice items. By making an `Item Tax Template` that will be linked to Item.

## Item Tax Template

- [x] `Item Tax Template` (doctype)
  - [x] `Item Tax Category` (doctype)
  - [x] Child table with tax account, percent
- [x] Set default Item Tax Template in Item

#### Example

Name: "In state GST 9"

Tax Category: "In State"

| Tax Account  |  Rate |
| ------------   |  ----- |
| CGST |                 9 |
| SGST  |                9 |

### Setup in Item

In `Item`, allow to set the default tax template

#### Example:

| Tax Category | Tax Template |
|-|-|
| In State | In State GST 9 |
| Interstate | Interstate GST 18 |

### Add Tax Category in Customer Address

In Address, add Tax category (example "In State", or "Interstate")

## Usage in Order/Invoice

- [x] The default `Item Tax Template` gets picked up in an Order/Invoice based on Customer and Item
- [x] Calculate taxes and charges table based on Item Tax selected in each row
- [x] Show sum of all row-level taxes in the `Taxes and Charges` table

#### Conflict with `Taxes and Charges Template`

If `Item Tax Template` is used, `Taxes and Charges Template` will not be applicable

(inspired from FrappeJS)

**Comment by karannshah** [comment]
With this would we be able to select the tax slab for a given item in a sales/purchase invoice? So instead of creation 3 transportation charges like 1) Transport - No GST (specifically for RCM cases), 2) Transport 5% (for Goods and Transport Agent as vendors) and 3) Transport 12% (if I am providing transport through my vehicles)...I can just create one Transport Item and create 3 tax slabs Nil, 5% and 12% - and these will become selectable at line item level?

**Comment by agritheory** [comment]
@Tropicalrambler has been working on this though it may be more specific to Guatemala.

**Comment by karannshah** [comment]
@agritheory Thanks Tyler. @Tropicalrambler would love to understand your solution design for this problem. And if we can be of any help in accelerating the building of this feature.

**Comment by SaiFi0102** [comment]
I have volunteered to work on this issue and I would appreciate your feedback @karannshah and @Tropicalrambler

**Comment by karannshah** [comment]
Absolutely @SaiFi0102.  Can you write to me on karan@shipmnts.com?

**Comment by SaiFi0102** [comment]
My take on this issue: https://discuss.erpnext.com/t/proposal-tax-category-item-tax-template-and-item-wise-taxes/42979

**Comment by SaiFi0102** [comment]
https://github.com/frappe/erpnext/pull/16324

**Comment by SaiFi0102** [comment]
https://github.com/frappe/erpnext/pull/16377 Merged
