### ISSUE TITLE
Failed to open Frappe Desk

### ISSUE THREAD

**Issue by vbaidak** [frappe/erpnext#14182]
After recent upgrade, Frappe Desk is not loading showing the following errors in browser's console:

```
SyntaxError: expected expression, got '<<'[Learn More]
libs.min.js:9086
TypeError: frappe._ is undefined[Learn More]
capture.js:14
TypeError: frappe.views.Factory is undefined[Learn More]
list_factory.js:7
TypeError: frappe.views.Factory is undefined[Learn More]
formview.js:6
TypeError: frappe._ is undefined[Learn More]
capture.js:14
TypeError: frappe.views.Factory is undefined[Learn More]
report_factory.js:4
TypeError: frappe.breadcrumbs is undefined[Learn More]
```

**Comment by doun** [comment]
It's because some guy merged wrong Js file. I forgot the full path, but u can check the js console to find something like >>>> HEAD

**Comment by kennethsequeira** [comment]
@vbaidak do a git pull in the frappe directory and do a `bench migrate`. That should solve the issue.

**Comment by vbaidak** [comment]
Thanks for reply,

Issue has been fixed - I've just run ```bench udpate```
