### ISSUE TITLE
Sales Order or Sales Invoice: Please select a Batch for Item item_name. Unable to find a single batch that fulfills this requirement

### ISSUE THREAD

**Issue by jayfiro** [frappe/erpnext#14196]
Issue posted on this Discuss ERPNext [post](https://discuss.erpnext.com/t/error-when-creating-sales-order-please-select-a-batch-for-item-item-name-unable-to-find-a-single-batch-that-fulfills-this-requirement/32781).

Also, creating of sales order should allow for negative projected balance for item in question.

This also happens when creating a new Sales Invoice even if Update Stock is not checked.

**Comment by unnicv** [comment]
I am receiving the following message for the child items in a bundle.  Please select a Batch for Item 4488990. Unable to find a single batch that fulfills this requirement

**Comment by unnicv** [comment]
There is enough qty. in the specified warehouse

**Comment by unnicv** [comment]
Anybody have some solutions

**Comment by Romanos18** [comment]
Is there any follow up on this one?
