### ISSUE TITLE
Sales person in Sales Register and Accounts Receivable

### ISSUE THREAD

**Issue by Basawa-SELCO** [frappe/erpnext#14198]
The Sales Person and Sales Partner name is important for 2 reports and it doesnt seem to be included in the Standard reports:

- Sales Register
- Accounts Receivable (Sales person is important since the responsibility of recovery lies with the Sales person)

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.
