### ISSUE TITLE
Total Unclaimed Advances field is needed in Employee Advance Form

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#14209]
Hi,

There should be a 'Total Unclaimed Advances' field in the Employee Advance form. What I am referring to is a field that shows the total balance in the Employee Advance Account. For example, Employee A has made some requests for advance in the past which comes to a total of $10,000 (which has been paid). Out of this amount, he has only claimed $2,000 which means that there is still $8,000 un-retired in his Advance Account

Now Employee A makes a new request for $3,000 but the supervisor or management may not want to approve until he has accounted for (retired) the balance of $8,000 in his Advance Account. It is therefore very important to have a field in the Employee Advance form that shows the balance in the employee's advance account so that a decision can be taken on whether to approve or not

Hope this is clear enough?

Thanks

**Comment by jaichavan** [comment]
Hello, @Olawale1 
You can create a new custom field for the purpose of keeping track of advances taken against allocated Advance. Refer the below link to learn more:
https://erpnext.org/docs/user/manual/en/customize-erpnext/custom-field

**Comment by Olawale1** [comment]
Hi @jaichavan

I trust you're doing well. I am well aware of custom fields. If you read carefully, you'll notice that what I explained above is more than just adding a custom field

Kindly re-open the issue 

Thanks

**Comment by jaichavan** [comment]
The requested feature can be well accommodated with custom scripts and fields. Have you attempted to make any custom script for the same? @Olawale1
