### ISSUE TITLE
Multi user login in single browser window causes connection issues due to fail2ban

### ISSUE THREAD

**Issue by kothagunda** [frappe/erpnext#14206]
Hello
We have an issue with our v9 erpnext server. When we login as 2 different users in the same browser window (2 different tabs), the connection fails. As the IP is banned due to fail2ban.

Since our staff use same machine for logins, on in morning and another in afternoon shift. If first person forgets to logout, and second person logins again in the same browswer, on a diff tab, the IP is blocked and all our machines are locked out of the server.This is stopping us from working on the site.

**As a enhancement/development to fix this issue:**
Sree Harsha suggested, that its better that, when we try to login again, it should not take us to login page, or atleast user is forced to logout, before allowing him/her to login again.

This is a very bad user experience. Because, when this happens, we try to debug thinking the server is down, or our ISP has issues. Not knowing our IP is banned.

![image](https://user-images.githubusercontent.com/30433779/40472307-b4873472-5f56-11e8-8cd2-79e3371b12ba.png)

See above  image, i already logged in (see top right). But if i go to login URL  , it allows me to login again, as a diff user. This is causing the issue.

Related topic that has been created in discussion forum.
https://discuss.erpnext.com/t/multi-user-login-in-single-browser-window-causes-connection-issues/36827

**Comment by rmehta** [comment]
Its not due to fail2ban! it's because the session cookies get shared across browser tabs (that is the way browsers are designed!)

**Comment by kothagunda** [comment]
Nice. So it will be available in v11 i guess. Thank you.
