### ISSUE TITLE
GST India territory option in masters

### ISSUE THREAD

**Issue by test2a** [frappe/erpnext#14210]
Right now, if we make a sale/ purchase invoice, there is a head "address and contact" that contains teritory option. This is right Now to be filed each and every time.
My suggestion is to allow us to set first the company territory in masters and later, at the time of creation of supplier/customer, we should be given option to set the default territory and as a result, if the other party has the same territory as the company, it should auto select in state gst and if different, out state gst.

**Comment by test2a** [comment]
i wrote that comment on the forum and was asked to file for a feature request here.. sigh

**Comment by umairsy** [comment]
Please go with the tax rule work-around as suggested by Dhananjay.

https://discuss.erpnext.com/t/gst-india-supplier-customer-tax-details/36908/3?u=umair
