### ISSUE TITLE
Request Time Out in BOM Update Tool

### ISSUE THREAD

**Issue by rohitwaghchaure** [frappe/erpnext#14227]
Getting an error request time out while updating BOM
![screenshot-2018-5-22 bom update tool](https://user-images.githubusercontent.com/8780500/40541041-e47f7d74-6037-11e8-9b8c-8a29ef8f71a5.png)

Note: The old BOM is the part of around 100 bom items
Need to refactor the code

**Comment by djpalshikar** [comment]
@rohitwaghchaure :
There similar issue with Rename tool here #14229 .
If updating all BOMs at once is taking time and consuming resources you could consider the following:
- Update BOMs as a scheduled operation and carry out replacement only for x no. of BOMs at a time
- The progress of BOM update tool can be indicated: 150 out 10000 replaced
- If possible BOM update tool can be made into a Doctype like Data Import Tool

**Comment by djpalshikar** [comment]
Another option for BOMs:
- We could generate the exploded BOMs dynamically for transactions, as opposed to storing them in 'Exploded Table', it could ease out the burden of the BOM update tool.

- We could provide a check-box in Manufacturing Settings- 'Generate Exploded BOMs during Transactions' to enable this feature.

**Comment by nagarajannxweb** [comment]
Getting same error but we have linked only in 15 BOM Items

**Comment by jaichavan** [comment]
Hello, please check inline replies:
 @djpalshikar Thanks for the suggestions! We have already shortlisted and will merge what's best for the BOM updation.
@nagarajannxweb Issue shortlisted, will be resolved as early as possible.

Thanks for your cooperation.

**Comment by ophl55** [comment]
Hello.

I'm having the same issues. The replacement of a BOM that is linked to 100+ other BOMs takes already 3 days. This is really a problem since there are many BOMs more to update.

Another point is that emails send over the system get stucked in the job queue.

**Comment by surajshetty3416** [comment]
https://github.com/frappe/erpnext/pull/19236 This optimizes the BOM update tool
