### ISSUE TITLE
[refactor][major] Begin deprecating Grid Reports 

### ISSUE THREAD

**Issue by pratu16x7** [frappe/erpnext#14226]
- [ ] _**Stage 1** (immediate measures):_
Disable them for 'larger than a threshold' datasets.

- [ ] _**Stage 2** (rewrite):_
Rewrite them as server side Script Reports.

**Warning:** Large reports ahead:
- [ ] Production Analytics
- [ ] Sales Analytics
- [ ] Purchase Analytics
- [ ] Support Analytics

**Comment by djpalshikar** [comment]
>  Stage 1 (immediate measures):
 Disable them for 'larger than a threshold' datasets.
As an immediate measure could you do something similar to https://github.com/frappe/erpnext/pull/14193. This has helped us with Itemwise Recommended Re-Order Level Report.

**Comment by deepeshgarg007** [comment]
Removed grid reports completely from version-12. Closing
