### ISSUE TITLE
Total Weight in Stock Entry

### ISSUE THREAD

**Issue by Mishaal1021** [frappe/erpnext#14235]
Hi,

With the weight_per_unit field added, its great that most of the documents have total weight field as a standard field.

However, one of the key vouchers "Stock Entry" does not have this as a standard field. Please consider adding this, as it adds a lot of value for manufacturing industries. 

Regards,

Mishal

**Comment by jaichavan** [comment]
Hello, @Mishaal1021 
We shall consider your suggestion and see how it can be accommodated in the system. Thanks.
