### ISSUE TITLE
Purchase Receipt from Purchase Order Error

### ISSUE THREAD

**Issue by amitsaxena01** [frappe/erpnext#14234]
In the build ERPNext: v11.x.x-develop (7663bb9) (develop), Frappe Framework: v11.x.x-develop (c34f059) (develop) when we try to make a purchase receipt from purchase order we are getting the following error:

Traceback (most recent call last):
File “/home/erp_healthcare/frappe-bench/apps/frappe/frappe/app.py”, line 62, in application
response = frappe.handler.handle()
File “/home/erp_healthcare/frappe-bench/apps/frappe/frappe/handler.py”, line 22, in handle
data = execute_cmd(cmd)
File “/home/erp_healthcare/frappe-bench/apps/frappe/frappe/handler.py”, line 53, in execute_cmd
return frappe.call(method, **frappe.form_dict)
File “/home/erp_healthcare/frappe-bench/apps/frappe/frappe/init.py”, line 942, in call
return fn(*args, **newargs)
File “/home/erp_healthcare/frappe-bench/apps/frappe/frappe/model/mapper.py”, line 27, in make_mapped_doc
return method(source_name)
File “/home/erp_healthcare/frappe-bench/apps/erpnext/erpnext/buying/doctype/purchase_order/purchase_order.py”, line 362, in make_purchase_receipt
}, target_doc, set_missing_values)
File “/home/erp_healthcare/frappe-bench/apps/frappe/frappe/model/mapper.py”, line 107, in get_mapped_doc
map_child_doc(source_d, target_doc, table_map, source_doc)
File “/home/erp_healthcare/frappe-bench/apps/frappe/frappe/model/mapper.py”, line 202, in map_child_doc
map_doc(source_d, target_d, table_map, source_parent)
File “/home/erp_healthcare/frappe-bench/apps/frappe/frappe/model/mapper.py”, line 123, in map_doc
map_fields(source_doc, target_doc, table_map, source_parent)
File “/home/erp_healthcare/frappe-bench/apps/frappe/frappe/model/mapper.py”, line 172, in map_fields
map_fetch_fields(target_doc, df, no_copy_fields)
File “/home/erp_healthcare/frappe-bench/apps/frappe/frappe/model/mapper.py”, line 184, in map_fetch_fields
source_fieldname = fetch_df.fetch_from.split(".")[1]
AttributeError: ‘NoneType’ object has no attribute ‘split’

**Comment by ahmed-madi** [comment]
https://github.com/frappe/frappe/pull/5611 this pull request fixed the problem
