### ISSUE TITLE
Ability to Freeze Pane in Script Reports

### ISSUE THREAD

**Issue by Mishaal1021** [frappe/erpnext#14237]
Hi,

When reviewing any script report that are in grid format, the system doesn’t allow the user to freeze pane or to move/delete/add columns. Also, in some reports, like financial statements, the filter for date range is not available. This makes it really difficult for user to use ERP to review data within the system. The only way around it is to export the report in excel and modify it.

I would kindly request that you consider this request – at least to allow users to freeze pane in script report.

Regards,

Mishal

**Comment by jaichavan** [comment]
Hello, @Mishaal1021 
We will consider your valuable suggestions and see how they can be accommodated in the system in the future versions, thanks.

**Comment by Mishaal1021** [comment]
Hi,
1.For the financial statements, in Version 10, we had option to “Expand All/Collapse All”. I can not find this in Version 11. This was incredibly useful, and would appreciate if it can be added to V11.

2.Also, I would again like to request this report by month. It is very difficult as the system doesn’t even allow us the PDF the report as there are too many columns. If we could just have the filter by dates, instead of by Fiscal Year only,

3.When reviewing any script report that are in grid format, the system doesn’t allow the user to freeze pane or to move/delete/add columns. Also, in some reports, like financial statements, the filter for date range is not available. This makes it really difficult for user to use ERP to review data within the system. The only way around it is to export the report in excel and modify it.

4.We are also using Budgets in ERP request you to kindly link this budget in income statement which will help us to see the variances at one place as of now we are combining two reports manually in excel to see the variance. this feature will save lots of time. 

I can guarantee you that it will assist a lot of the users.

**Comment by ShantanuIBSL** [comment]
Hi,
Can we freeze one Column panel in report like in excel it would be very helpful for scrip reports where there are lot of data?
