### ISSUE TITLE
Logo design contribution

### ISSUE THREAD

**Issue by saifulfrank** [frappe/erpnext#14240]
Hi
I want to make a logo for this projects if you have any requirements then let me know.its totally free for open source projects.

**Comment by agritheory** [comment]
@saifulfrank Check out the Frappe Charts library as well. They've split out and generalized the charts capabilities it is one of the most graphically-intese parts of ERPNext. They may be more obvious places to contribute there. 
https://github.com/frappe/charts

**Comment by saifulfrank** [comment]
that's also your project!
So do want a logo for that?

**Comment by agritheory** [comment]
@saifulfrank I'm a community contributor. The maintainer of the charts library is the guy you want to talk to, he's a Frappe core team member and the UI lead.
