### ISSUE TITLE
Operation planned time on Production Order and Timesheet activity timing are not generated based on workstation hours

### ISSUE THREAD

**Issue by homa-safe** [frappe/erpnext#14260]
I have my workstation hours set from 9am to 5pm and the Allow Overtime option is NOT checked.
![erpnext-1](https://user-images.githubusercontent.com/18667132/40626880-66b113ea-6289-11e8-8677-983b1e136e88.jpg)
When I create a production order for that workstation, planned time for operations gets generated back to back and it does not consider the workstation hours.
![erpnext-2](https://user-images.githubusercontent.com/18667132/40626928-ade5b162-6289-11e8-9038-626f29f74ca2.jpg)
The same issue on the Timesheet activity timing which is created out of  this production order
![erpnext-3](https://user-images.githubusercontent.com/18667132/40626954-d7dc6ca4-6289-11e8-9e3c-03b173b9c9e8.jpg)

Please advise!
Thanks,

**Comment by umairsy** [comment]
In the Manufacturing Settings, have you enabled "Overtime"?

**Comment by umairsy** [comment]
Please post such queries on the ERPNext community forum first.

https://discuss.erpnext.com
