### ISSUE TITLE
Payroll Flexible Component calculation incorrect

### ISSUE THREAD

**Issue by PawanMeh** [frappe/erpnext#14285]
1. Create Pro Rata Salary Component

![flexi_component](https://user-images.githubusercontent.com/20460498/40712781-2373656c-641c-11e8-8303-1ff676d95334.png)

2. Create Salary Structure with only one component. Salary of the employee is 50,000/-

![salary_structure](https://user-images.githubusercontent.com/20460498/40712815-3877d1be-641c-11e8-9176-bc91cfd65d6b.png)

3. Check Preview of Salary Slip

![salary_slip_preview](https://user-images.githubusercontent.com/20460498/40712881-63c9b328-641c-11e8-9805-a5d77dff8caf.png)

Amount Shown is : 4246.58 per month which when pro-rated for 12 months would be 50,958.96, which is greater than the salary of the employee as well as the Max benefit amount of 50,000 for this component. To make the calculation amount uniform, maybe we should consider 30 days a month as a standard.

**Comment by Olawale1** [comment]
Hi @PawanMeh

Thanks for your detailed testing and feedback. Are you sure months with fewer working days won't absorb the excesses and thereby make the final figure 50,000?

I think the amount probably varies based on number of working days and not fixed as you seem to suggest

Pls confirm. Thanks 

Kind regards,

**Comment by PawanMeh** [comment]
@Olawale1 , thanks for your detailed feedback. Awaiting for v11 latest release to test.

**Comment by rkurungadam** [comment]
Flexi calculation considers LWP as well as "Include holidays in Total no. of Working Days" in HR Settings to calculate the amount per day, so the amount dispersed as pro rata will be based on working days and leaves.

**Comment by PawanMeh** [comment]
@rkurungadam , I am closing this issue for now, I am retesting most of the functionality as part of issue #14384, you can look at the comments on that issue for new issues. This issue raised was not related to LWP as there were no leaves for the employee.
