### ISSUE TITLE
Income Tax calculation in Payroll not working

### ISSUE THREAD

**Issue by PawanMeh** [frappe/erpnext#14289]
1. Set up tax component and use in salary structure
![it_slabs_in_component](https://user-images.githubusercontent.com/20460498/40715705-180d43f2-6424-11e8-92e8-8361b9541237.png)

![income_tax_component](https://user-images.githubusercontent.com/20460498/40715728-2777a148-6424-11e8-8251-4569154fb7a2.png)

2. There is no income tax calculation impact and it also shows -ve tax.

![salary_slip_tax](https://user-images.githubusercontent.com/20460498/40715757-451e016a-6424-11e8-81d8-b79e11e16a21.png)

**Comment by ekpott** [comment]
This is similar to an issue I had been discussing in the community. https://discuss.erpnext.com/t/salary-structure-error/36227

**Comment by rkurungadam** [comment]
@PawanMeh Can you update to latest develop and confirm? also check if you have components marked Tax Applicable which are not Flexible Benefit in Salary Structure.

**Comment by PawanMeh** [comment]
@rkurungadam , I am closing this issue for now, I am retesting most of the functionality as part of issue #14384, you can look at the comments on that issue for new issues.
