### ISSUE TITLE
Missing translatable text in wizard

### ISSUE THREAD

**Issue by mhbu50** [frappe/erpnext#14293]
![image](https://user-images.githubusercontent.com/11526423/40721495-47359dc0-6422-11e8-88ea-17b1f70a4570.png)

**Comment by jaichavan** [comment]
Hello, @mhbu50 the sign-up and configurations / set up of the site have been completely changed in v11 after the new pricing launched. Hence, this issue no longer prevails with that context in mind. Thanks for reaching out.
