### ISSUE TITLE
Hub / Marketplace Discovery

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#14309]
Make Hub / Marketplace more discoverable

- [ ] Link in "Explore Page"
- [ ] Menu when you click on home icon (show all modules + hub ?)
- [x] Remove Marketplace links in Hub Settings, Rename "Products" to "Marketplace", Remove "Hub" Icon

**Comment by pratu16x7** [comment]
<img width="970" alt="screen shot 2018-06-04 at 3 38 43 pm" src="https://user-images.githubusercontent.com/5196925/40911835-82b6edb0-680d-11e8-9352-e4314caf2ca2.png">

**Comment by rmehta** [comment]
Yeah, a little bit too busy!
