### ISSUE TITLE
'npm audit' reports security vulnerabilities

### ISSUE THREAD

**Issue by clarkejj** [frappe/erpnext#14306]
Re this https://discuss.erpnext.com/t/during-last-update-production-npm-audit-gives-11-vulnerabilities-with-1-critical-and-4-high-problem/37063/3

Does Frappe have a process in place to update say production master to apply the recommended security patches and would you please do so.

Presumably erpnext.com and other users are exposed until an npm audit reports no vulnerabilities. 

thanks

**Comment by codingCoffee** [comment]
https://github.com/frappe/frappe/pull/5645
https://github.com/frappe/frappe/pull/5644
Fixed by @netchampfaris

**Comment by clarkejj** [comment]
Thank you for resolving this codingCoffee!

**Comment by codingCoffee** [comment]
@netchampfaris did the heavy lifting. I barely had anything to do with it, other than closing the issue :P
