### ISSUE TITLE
BOM - Allow Multiple rows for same item

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#14304]
Currently it doesn't allow adding same item in multiple rows of BOM.

BOM - Allow Multiple rows for same item

Reference: WN-SUP33501

**Comment by sharmanakul** [comment]
a use-case for this is mentioned here with work arounds. https://discuss.erpnext.com/t/multiple-lines-of-same-item-on-the-bom/18039

**Comment by sharmanakul** [comment]
In BOM, multiple rows for the same items can be added. However, they get consolidated in the work order.
Expected behaviour - if the same item is added separately in the BOM then it should remain that way in the work order as well.
