### ISSUE TITLE
Feature Request: Tagging keywords for documents

### ISSUE THREAD

**Issue by RSKROGER** [frappe/erpnext#14318]
It can take a very long time to find certain documents that pertain to certain customers, suppliers, issues or keywords. It would be very helpful and beneficial if we could tag documents using a similar hashtag system that twitter uses. 

Adding a # feature will allow users to quickly find documents pertaining to certain issues. 

Adding a hashtag feature that could be searched through in the system would be very beneficial to all users. This will make searching through the ERP a lot faster. 

It would be important to have a summary screen where we could see all the documents tagged with certain keywords.

We currently just write information in the comments of any particular document, but, searching for it can be tedious.

**Comment by Zlash65** [comment]
Why not use Tags ?

In the sidebar you have a section for tag. Add tag for any document and this tag becomes visible in the sidebar for the list view of the DocType that document belongs to. Clicking on them filters the list accordingly too.

Tags wont be available for global search though, but it could be used to filter out document in list.

**Comment by RSKROGER** [comment]
Excellent, that worked out really well. Please consider implementing a global search feature for them. This way, we can see all the document types attached with certain tags.
