### ISSUE TITLE
No Holidaylist Half Day Work off Option

### ISSUE THREAD

**Issue by Muhaahm** [frappe/erpnext#14353]
Issue: Feature Request

Hello,
There is a weekly Off option in the holiday list part.But in our case we have Sunday and half Saturday off. It seems that there is no half day off option it is urgent for our company please add this option .

Thanks and Regards

**Comment by jigneshpshah** [comment]
Are you paying them for Half Day or full day for Saturday ?

If you are paying them for full day for Saturday.

 I think it can be handled by putting only sunday as week off and consider normal attendance of saturday. 


The purpose of Half day is to give the effect in payroll/leaves.
