### ISSUE TITLE
[v11] Leave Management

### ISSUE THREAD

**Issue by nabinhait** [frappe/erpnext#14378]
- [x] Multiple Leave Types
	- [ ] Optional Leave
	- [ ] Earned Leave
	- [ ] Parental Leave
- [x] Leave Period
- [x] Leave Policy
- [x] Leave Encashment 
- [ ] Compensatory Leave
- [ ] Refactored Leave Application
	- [ ] Approver based on department > patch
	- [ ] Leave balance

**Comment by PawanMeh** [comment]
#14498
