### ISSUE TITLE
[v11] [test] Tree view of following docs

### ISSUE THREAD

**Issue by nabinhait** [frappe/erpnext#14388]
- Company
- Department
- Supplier Group (renamed from supplier type)
- Location (Bootstrapped based on Warehouse)

**Comment by Zlash65** [comment]
- Company
[ ] Add child from root node
[ ] Filter shows is_group enabled companies only
[ ] Screen freeze while creating Company
[ ] Rename Working from tree view
[ ]  Parent node delete should throw error that child node exists -> Fixed
