### ISSUE TITLE
[v11][Test] Payroll

### ISSUE THREAD

**Issue by nabinhait** [frappe/erpnext#14384]
- Salary Structure
	- Submittable
	- Salary Structure Assignment, instead of child table of employee
- Payroll Period
- Additional Salary
- Employee Tax Exemption
- Employee Benefits
- Formula on salary component
- Automated tax calculation for based on tax slab (India)

**Comment by PawanMeh** [comment]
#14289, #14285

**Comment by ekpott** [comment]
Will the automated tax calculation also address this issue from the community?

https://discuss.erpnext.com/t/salary-structure-error/36227

**Comment by PawanMeh** [comment]
#14555

**Comment by PawanMeh** [comment]
#14568

**Comment by PawanMeh** [comment]
#14569

**Comment by PawanMeh** [comment]
#14682

**Comment by PawanMeh** [comment]
#14683

**Comment by PawanMeh** [comment]
#14713

**Comment by PawanMeh** [comment]
#14714

**Comment by PawanMeh** [comment]
#14717

**Comment by PawanMeh** [comment]
#14749

**Comment by PawanMeh** [comment]
#14766
