### ISSUE TITLE
v11][test] Enhanced Fixed Asset Management

### ISSUE THREAD

**Issue by nabinhait** [frappe/erpnext#14404]
- CWIP Accounting
- Serialised asset
- Improved workflow for managing assets
- Multiple depreciation schedule based on finance book
- Asset value adjustment
- Improved Asset Movement between location or employee
	- Issue
	- Receive
	- Movement

**Comment by PawanMeh** [comment]
#14463

**Comment by PawanMeh** [comment]
#14522
