### ISSUE TITLE
Issue with offline pos

### ISSUE THREAD

**Issue by jaqobk** [frappe/erpnext#14417]
My offline pos not working but online pos works fine for all users and this error I found it in the browser console when I tried to open the offline pos

> Traceback (most recent call last):
> File “/home/frappe/frappe-bench/apps/frappe/frappe/app.py”, line 62, in application
> response = frappe.handler.handle()
> File “/home/frappe/frappe-bench/apps/frappe/frappe/handler.py”, line 22, in handle
> data = execute_cmd(cmd)
> File “/home/frappe/frappe-bench/apps/frappe/frappe/handler.py”, line 53, in execute_cmd
> return frappe.call(method, **frappe.form_dict)
> File “/home/frappe/frappe-bench/apps/frappe/frappe/init.py”, line 942, in call
> return fn(*args, **newargs)
> File “/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/sales_invoice/pos.py”, line 26, in get_pos_data
> frappe.throw(_(“POS Profile is required to use Point-of-Sale”))
> File “/home/frappe/frappe-bench/apps/frappe/frappe/init.py”, line 327, in throw
> msgprint(msg, raise_exception=exc, title=title, indicator=‘red’)
> File “/home/frappe/frappe-bench/apps/frappe/frappe/init.py”, line 313, in msgprint
> _raise_exception()
> File “/home/frappe/frappe-bench/apps/frappe/frappe/init.py”, line 286, in _raise_exception
> raise raise_exception(msg)
> ValidationError: POS Profile is required to use Point-of-Sale

kindly any one help as offline mode is very critical to us and am strugling with this now and seems like this is beyond my knowledge

**Comment by kennethsequeira** [comment]
The error says you need a POS profile to operate your point-of-sale. 

Have you created a POS profile for that warehouse?

**Comment by jaqobk** [comment]
Yes I have a pos profile for each user where by i have 5 user and three
users uses one pos profile while the other two has each pos profile.
The online pos workd fine i only have issue with offline pos when enabled i
get that error

**Comment by jaqobk** [comment]
Mine started working yesterday after I did bench update.
Try it also i want to believe your issue will be solve too.
