### ISSUE TITLE
ERPnext revert my changes on custom DocType

### ISSUE THREAD

**Issue by garybsimon** [frappe/erpnext#14426]
Hi there,

I have a problem with my test server.
The sympthom is the following:

- I have created a custom app for my erpnext install.
- Developer mode is on
- This app has custom doctype's
- I have added some fields to this doctype
- I have run bench migrate and then bench restart && bench clear-cache

The results:
- The modifications are gone and the DocType has been reverted to it's original unmodified version.

What's the cause? 
How can I fix this issue?

My system is: Ubuntu 16.04 LTS
All package has been updated and Erpnext and Frappe is the latest master version.

Thanks.

**Comment by mepoohsta** [comment]
How do you fix this issue? After bench update I have same issue. @garybsimon

**Comment by SonicCodes** [comment]
How did you fix it, I have the same issue and I can't risk re creating the doctypes. @garybsimon

**Comment by realespee** [comment]
How did you guys solve this, please help
