### ISSUE TITLE
Email Control for Workflow (Toggle Option)

### ISSUE THREAD

**Issue by worldofsmarty** [frappe/erpnext#14437]
Issue: Feature Request

This is the request for providing a toggle option to send the email for each of the workflow transaction triggers. We can possibly have an option for enabling email sending to each of the workflow individually.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by joolsr** [comment]
You will need to check but I know that some of this type of functionality relating to workflow and chnages and sending email due to wf changes has just been added to the Develop branch

**Comment by worldofsmarty** [comment]
Yes. For example we have created a workflow for project management as shown in the image attached. And now if any new task is created all the employees are receiving the email notification. So it will be better for the developers to consider adding the toggle option of sending notification for certain workflows.

For example in HR department workflow with notification works really well. But for the project management, it does not. It will just bombard the mail box with each task created.

![workflow](https://user-images.githubusercontent.com/5152491/41215752-6ec9b334-6d6f-11e8-8730-450050befd52.JPG)

**Comment by worldofsmarty** [comment]
Still the mails are triggering. Have unchecked the send email checkbox. But then also the mails are triggering. Have attached the screenshots for your reference.

![image](https://user-images.githubusercontent.com/5152491/41269898-bd938b6e-6e25-11e8-8231-025786f21b0b.png)

![image](https://user-images.githubusercontent.com/5152491/41269913-d7d2a898-6e25-11e8-8fd8-193d28d23a97.png)


![image](https://user-images.githubusercontent.com/5152491/41269928-f57865fe-6e25-11e8-8b50-db20ba9524c0.png)
