### ISSUE TITLE
Add a Small Text field to Purchase Order doctype to store a static copy of Shipping Address

### ISSUE THREAD

**Issue by jevonearth** [frappe/erpnext#1443]
The Purchase Order doctype needs a ship_to_address_display field that will contain a independent/immutable copy of the Shipping Address for the PO.

The Purchase Order object has a similar field called address_display which is used for the vendor address.

Linking to the shipping address is not good enough, because a linked address can be updated after a PO is submitted. The PO must contain its own immutable copy of the shipping address.

I also think that the default PO print templates should be updated to make use of this new proposed field.

**Comment by David-at-GitHub** [comment]
Good evening, is there any status update on this issue? I agree with @anandpdoshi , each Document in Sales and Purchase should have a Ship-To and a Bill-To address, set by the default, but changeable.
