### ISSUE TITLE
Leave Type Error while saving

### ISSUE THREAD

**Issue by worldofsmarty** [frappe/erpnext#14434]
While saving the leavetype it throws this error "Rounding cannot be "0.500000". It should be one of "0.5", "1.0" "

Do you guys have any idea how this is appearing out of nowhere. As this is the first time m receiving this error.

Thanks again for your amazing application.

Attached is the screenshot for your reference
![leavetype error](https://user-images.githubusercontent.com/5152491/41188085-e7189c24-6bd5-11e8-8bde-80302ef98148.JPG)

Issue: Bug report

Our project, as you've probably heard, is getting really popular and truth is we're getting a bit overwhelmed by the activity surrounding it. There are just too many issues for us to manage properly.

**Do the checklist before filing an issue:**
 - [ ] Have a usage question? Ask your question on  [Discuss Forum](https://discuss.erpnext.com). We use [Discuss Forum](https://discuss.erpnext.com) for usage question and GitHub for bugs.
 - [x] Can you replicate the issue? 
 - [ ] Is this something you can debug and fix? Send a pull request! Bug fixes and documentation fixes are welcome

**Describe the bug** :chart_with_downwards_trend: 

**To Reproduce** :page_with_curl:

**Expected behavior** :chart_with_upwards_trend:

**Screenshots** :crystal_ball:

**Desktop (please complete the following information):** :cyclone:
 - OS:
    - [ ] Linux
    - [ ] macOS
    - [x] Windows
    - [ ] Others? Please mention: 
 - Browser:
    - [ ] Safari
    - [x] Chrome
    - [x] Firefox
    - [ ] Other? Please mention: 

**Smartphone (please complete the following information):** :iphone: :computer:
 - Device:
    - [ ] iPhone
    - [ ] Android
 - Browser:
    - [ ] Safari
    - [ ] Chrome
    - [ ] Firefox
    - [ ] Other? Please mention: 

**Version Information**
- Which branch are you on?
    - [x] `master` :star2: 
    - [ ] `develop` :fire:
- Frappe Version: 
- ERPNext Version: 

**Additional context** :page_facing_up:

**Possible Solution** :bookmark_tabs:
Any idea what might be causing the issue. Or if you have a proposed solution to the problem,

**Please don't be intimidated by the long list of options you've to fill. Try to fill out as much as you can. Remember, the more the information the easier it is for us to replicate and fix the issue** :grin:

**Comment by rkurungadam** [comment]
Hi, Can you check the value of field "Rounding" in Earned Leaves Section, it will show up when you check "Is Earned Leave" checkbox.
Thanks

**Comment by worldofsmarty** [comment]
But have not selected this leave as earned leave. The checkbox is unchecked

**Comment by worldofsmarty** [comment]
Let it be any leave... We are getting this error when we click on save.

**Comment by worldofsmarty** [comment]
Yeah it resolved the issue by adding any value i.e. 1 to the earned leave section. But if earlier earned leave was not checked, then also it was taking the rounding in consideration.

**Comment by rkurungadam** [comment]
Field rounding is a Select Type field, values 0.5, 1.0. please migrate your db to get this reflected.
thanks
