### ISSUE TITLE
Duplicate Price List does not copy item prices

### ISSUE THREAD

**Issue by jayfiro** [frappe/erpnext#14441]
When an existing price list is duplicated via Menu > Duplicate in Price List List, the newly created price list does not contain any item prices.

The expected behavior is that all price list items in the price list being duplicated are copied into the new price list.

OS: macOS v10.13.4
Browser: Opera v53.0.2907.68
Frappe Version: v10.1.36 (master)
ERPNext Version: v10.1.37 (master)

**Comment by Zlash65** [comment]
The duplicate feature does not work that way. It just duplicates the current document so that user does not have to enter everything. For example, in case of adding an item, the form is too big and to save time it can be duplicated to save a new item that only differs from the first one in few fields.

Maybe you can raise a feature request regarding your query.

**Comment by jayfiro** [comment]
You mentioned that "It just duplicates the current document so that user does not have to enter everything." When I duplicate it just creates a new empty price list. Please see screenshots.

Here, I have already created price list 2018JUN11_POs.
![opera snapshot_2018-06-11_183833_freshgo erpnext com](https://user-images.githubusercontent.com/23268734/41260789-ed6cdc48-6da6-11e8-8fc3-9f8225525e3f.png)

Now this is the screen that comes up when I duplicate 2018JUN11_POs.
![opera snapshot_2018-06-11_183910_freshgo erpnext com](https://user-images.githubusercontent.com/23268734/41260794-efb035cc-6da6-11e8-8850-57e422512737.png)

This in turn creates an empty price list.
![opera snapshot_2018-06-11_183933_freshgo erpnext com](https://user-images.githubusercontent.com/23268734/41260801-f27c9f16-6da6-11e8-9232-ae94fe47f3e2.png)

What am I missing here that is supposed to be copied?
