### ISSUE TITLE
Asset creation from Purchase Receipt

### ISSUE THREAD

**Issue by PawanMeh** [frappe/erpnext#14463]
Steps:

1. Create a Item and mark it as an asset item
2. Create a PO for the same item with say quantity 5
3. Create a Purchase Receipt for the PO and you will get a message as shown below

![asset_creation_from_purchase_receipt](https://user-images.githubusercontent.com/20460498/41229894-540a3fe2-6d9b-11e8-9440-d564be65fbe8.png)

No asset is created and also an error message appears about warehouse locations.

4. Video for replication

![asset_creation_from_purchase_receipt](https://user-images.githubusercontent.com/20460498/41229918-6b9603d0-6d9b-11e8-9e6e-46206afeac3a.gif)

5. Version Details
      ERPNext: v11.x.x-develop (7048925) (develop)
      Frappe Framework: v11.x.x-develop (944626e) (develop)

**Comment by rohitwaghchaure** [comment]
Have fixed this issue, kindly pull latest update and check
