### ISSUE TITLE
new item Variant attributes cannot accept value 0

### ISSUE THREAD

**Issue by perkasajob** [frappe/erpnext#14462]
Issue: Bug report
v10.1.37 (master)

created new variant from item template, set one of the attribute value as 0 (range is 0 to 500). 
the new created item variant, cannot be saved, the error message shows : please specify the attribute value A, as it checked, the value 0 is set correctly, as well as in cur_frm.doc.attributes

**Comment by Zlash65** [comment]
Closing the issue as its fixed now. https://github.com/frappe/erpnext/pull/14509
