### ISSUE TITLE
[Proposal] Purchase or Sales Discount Terms

### ISSUE THREAD

**Issue by agritheory** [frappe/erpnext#14472]
**Problem Statement**
It is common practice in the US and other countries for a supplier to offer a payment discount if the remittance is within an accelerated period. The most common example I am aware of is "2/10 Net 30", where the buyer is given a 2% discount. While that may sound trivial, the businesses that are organized enough to take advantage of it are getting an annualized discount of 20.41% in the 2/10 Net 30 example, [source](https://finance.zacks.com/calculate-effective-annual-percentage-rate-forgoing-cash-discount-9258.html). 

**How?**
This requires changes to the doctypes Payment Terms Detail and Payment Term for data storage, validation and fetches in Payment terms Template and additional validation steps in Payment Entry and a new field in Payment Entry Deductions. I also added company defaults for purchase and sales discount percentage bookings. I have found that these are most often called out with their own account in the CoA, not to round off or COGS., "Purchase Discounts" and "Sales Discounts" usually contra expense and income accounts respectively.  

**Example Workflow**:
Let's change a Payment Term from Net 30 to 2/10 Net 30 and completing the two new columns all in the rightmost column: 
![payment term w discount](https://user-images.githubusercontent.com/18033666/41258024-db7fe1e2-6d9c-11e8-8596-edc5134e13f3.png)

We're basically repeating the same information here in Payment Terms Template:
![ptt w discount](https://user-images.githubusercontent.com/18033666/41258044-e9c61384-6d9c-11e8-8406-a42f881fdec0.png)

And let's have a look in context of a purchase invoice for an ERPNext Foundation Membership:
![supplier and item in pi](https://user-images.githubusercontent.com/18033666/41258070-ffa3ec1c-6d9c-11e8-839e-958390d61737.png)

![ptt in pi](https://user-images.githubusercontent.com/18033666/41258088-085a644e-6d9d-11e8-8d9d-5faf01e69797.png)

Other than defining in the discount variables, the workflow has been pretty much the same as it would be without those.  So onto Payment Entry where the core functionality is:
![payment entry with discount](https://user-images.githubusercontent.com/18033666/41258110-17dc20a6-6d9d-11e8-9c2f-62cf30b43a09.png)

The discount(s) are designed to load with a callback when party, paid_to, paid_from are populated and the document is in a draft state. The amount paid is automatically changed in the references to the discounted amount and the difference is posted to deductions. Deductions and references can be added manually. It does not recalculate deductions based on manually adding entries to references and I'm not sure that it should. 

**Current status:** 
Open for discussion. There are a lot models for how this could work but this is the one that I found that I thought had the fewest changes and matched the most use cases that I could think of. 

[Link to the commit to browse the code changes](https://github.com/agritheory/erpnext/commit/1c1a88ee3caf6ec0db8e1bcf17e87cddb21233dc)

**Comment by agritheory** [comment]
@nabinhait Based on the scope of this change, it'd be great to get some feedback from you.

**Comment by rmehta** [comment]
@agritheory best to discuss this over a PR

Quick comment: `calc_discount` should be called on `validate` (as there are lots of users who use the API to push invoices), also maybe break it into smaller functions and tests

**Comment by agritheory** [comment]
The reason that I wanted to do the proposal first (besides that the guidelines say to do it that way) was to get a feel from people on how this is handled in other countries or accounting conventions. I'm confident in my understand of how it works here, but these things aren't universal. 

> Quick comment: calc_discount should be called on validate
In addition to where it is being called now? That makes sense in API context. 

I agree it's a little large as-is, this started as a custom script. I'll make a few changes and then make a PR.

**Comment by rmehta** [comment]
Its a good idea to discuss the design here, but if you are want a code review, its best to do it over a PR, so you will know test results, linting etc. !

**Comment by agritheory** [comment]
OK, I'll do both in parallel.

**Comment by agritheory** [comment]
@rmehta I'm traveling for the next two weeks and don't expect to be able to get this in as a PR in that time. Expect a PR the week of 7/2/18, closing in the meantime. If someone wants to pick up discussion on this, go ahead and tag me on the forum or watch for the PR.

**Comment by heatherpotter** [comment]
This looks very good and would suit our needs @agritheory 

It would also be ideal if this worked for both payables and receivables. Some of our best customers have a discount setup with us as well so we offer them 2%-10/net 30 as well. The discount amount we give to the customer should be allocated to the right GL account as well. We have a separate one for "discounts" so that we can see how much we are giving as a discount. 

Finally, it would be great to be able to incorporate this into a report so we can run a payables report and see exactly what we should pay by a certain date and get a discount. 

Thanks for your great work on this!

**Comment by agritheory** [comment]
> Finally, it would be great to be able to incorporate this into a report so we can run a payables report and see exactly what we should pay by a certain date and get a discount.

This discount terms functionality is the first in a series of contributions along these lines and honestly, the least least impressive but it is foundational to the other two. The third is wizard that works like QuickBooks "Pay Bills" view but better, IMHO.

**Comment by agritheory** [comment]
> It would also be ideal if this worked for both payables and receivables.
It currently works with payables and receivables. The example I used was a payable.

> Finally, it would be great to be able to incorporate this into a report so we can run a payables report and see exactly what we should pay by a certain date and get a discount.

We've built a tool like QuickBooks "Pay Bills" view, so the report and action are all on one page.
