### ISSUE TITLE
Cost of Goods Sold AH selected in Item Difference Account in Manuf STE

### ISSUE THREAD

**Issue by kothagunda** [frappe/erpnext#14473]
Issue: Cost of Goods Sold AH selected in Item Difference Account in Manuf STE

The behaviour is given below.
https://discuss.erpnext.com/t/cost-of-goods-sold-ah-selected-in-item-difference-account-in-manuf-ste/37323

When doing a new STE manufacture (purpose), when we select a source or target item, the difference account head chosen in the item is usually "stock adj". But sometimes the difference account is chosen as "Cost of Goods sold" AH.

Why does this happen. Since "Cost of Goods Sold" is a P&L AH and should be touched automatically when a Sale happens, by the system, i am expecting it should not be touched in the STE manuf entries. 

Image of stock adj acct selected in item when a new STE with manuf is created
![image](https://user-images.githubusercontent.com/30433779/41272283-27e0653a-6e32-11e8-8961-bda82493e217.png)

Image of Cost of Goods selected in item when a new STE with manuf is created
![image](https://user-images.githubusercontent.com/30433779/41272273-1ea24ccc-6e32-11e8-871e-7a43d414ff53.png)

I thought may be the default WH in an item if different from the WH where the manuf is happening is causing it may be the issue. But its not.

But i have seen, that if i choose the items from a BOM, the AH becomes Cost of Goods sold, instead of Stock Adj. 

**Expected behavior** :chart_with_upwards_trend:
Stock Adjustment should be picked instead of Cost of Goods Sold.

**Version Information**
ERPNext: v9.1.4 (master)
Frappe Framework: v9.1.6 (master)

**Possible Solution** :bookmark_tabs:
rohit_w suggested that a code change to be made.
https://discuss.erpnext.com/t/cost-of-goods-sold-ah-selected-in-item-difference-account-in-manuf-ste/37323/5?u=kothagunda
System pick up the default expense account from the item master and if there is no expense account in item master, then it pickup the default expense account(Default Cost of Goods Sold Account) from the company master. I think instead of default expense account we should pickup the stock expense account head from the company. Can you please create the github issue for the same?

**Comment by Olawale1** [comment]
Hi ,

This issue is still in V12! Please help fix asap

Kind regards,

**Comment by Olawale1** [comment]
The Default Stock Adjustment account in Company master should be picked and NOT the Default Expense Account set in the Item master

Thanks

**Comment by ryuliantoro** [comment]
This issue is not fixed in ERPNext version 12.25
Just today I got question from a client about this when he saw anomaly in financial report after using the system for several months.

**Comment by ryuliantoro** [comment]
No… the Default Expense Account in Item is not set (empty).

In Company:
Default Cost of Goods Sold Account —> set to COGS account
Stock Adjustment Account —> set to Stock Adjustment account

I found this code in stock_entry_utils.py:
```
if not args.expense_account and s.is_opening == "No":
		args.expense_account = frappe.get_value('Company', s.company, 'stock_adjustment_account’)
```
It show it should take stock adjustment account instead of cogs, but it doesn’t obey.

**Comment by lxnow** [comment]
Was this fixed?
