### ISSUE TITLE
Quotations - Items table

### ISSUE THREAD

**Issue by FIROZE-ELEGANCE** [frappe/erpnext#1448]
Is it possible to incorporate a field of available stock on the quotation items table,
just like it is there in the delivery note?
The reason we needed a prompt on stock level at the point quotation is to
avoid us quoting for items out of stock..or actually indicating to a
customer that..yes we are quoting for you but pls note the item us out
stock and could be available in such and such a time..
2nd issue Is to actually guide the sales team to preferably quote what is in
stock..and shy from whats about to run out!
Or to give priority to the deadstock..or to guide them to sell on FIFO
basis.

I hope you understand us..

Thx and kind rgrds.

**Comment by rmehta** [comment]
Fixed
