### ISSUE TITLE
Workflow actions button not showing up in develop

### ISSUE THREAD

**Issue by PawanMeh** [frappe/erpnext#14504]
1. Version information

ERPNext: v11.x.x-develop (`a6b346f`) (develop)
Frappe Framework: v11.x.x-develop (`e180b41`) (develop)

2. Replication instructions
    a. Create a user with employee role and system manager role
    b. Create workflow and leave application as shown in the video & you will see no workflow actions available. You will see them appear with Admin ID

![leave_workflow_issues](https://user-images.githubusercontent.com/20460498/41347431-467067ac-6f27-11e8-92f7-dc1745320bbf.gif)

**Comment by Zlash65** [comment]
Have you enabled `allow self approval` checkbox in the Workflow you created ?

If the workflow provides self based action the checkbox need to be explicitly enabled or else it won't be able to see the actions even though they are mentioned in the workflow.
