### ISSUE TITLE
Add filter not working if we use 2 same fields parameter

### ISSUE THREAD

**Issue by nikzzastic** [frappe/erpnext#14514]
On using let say city="a" and city="b", it's saying " no lead found" but data is there. Same happening with any same filter condition. But when using two different conditions like city="a" and name="xyz" its giving output. But now with name="abc" and name="def". 
![screenshot from 2018-06-13 14-47-08](https://user-images.githubusercontent.com/33477525/41370641-d1618114-6f65-11e8-96f7-933ba2f30134.png)

**Comment by Zlash65** [comment]
When you apply filter as 'city=a & city=b' it tries to look for a record where both this condition is true. 

Instead you should search like - 'city in a,b' i.e, using the in filter which would return result for both a and b.

**Comment by nikzzastic** [comment]
Thanks 

I got that but one more suggestion, when I was using equals a drop-down suggestion automatically appears but on using "IN" i had to write the name by my self. How to activate this functionality for "IN" .
