### ISSUE TITLE
How to send SMS Automatically like Email Alerts?

### ISSUE THREAD

**Issue by harikishorsingh060** [frappe/erpnext#14529]
I have already  Configure SMS Setting. but i have not found any docs where set SMS alerts.

**Comment by djpalshikar** [comment]
Currently you cannot do it. There is #8591 which is still pending.

**Comment by harikishorsingh060** [comment]
@djpalshikar any update

**Comment by djpalshikar** [comment]
You can comment on #8591 and may be try to follow up or sponsor there.
If possible please close this issue, as it seems duplicate.
