### ISSUE TITLE
[v11] Payroll Entry

### ISSUE THREAD

**Issue by manassolanki** [frappe/erpnext#14523]
- [x] Handle if large no of salary slip has to be submitted via the payroll entry (use scheduler)
- [ ] Email the salary slip in the last after the successful submission of all salary slips.

**Comment by Olawale1** [comment]
Thanks for opening this @manassolanki

From time to time we have been experiencing the issue of Salary Slips getting emailed before they are successfully Submitted. It's good to know this won't be carried over into V11

Cheers!

**Comment by Olawale1** [comment]
This really should be fixed even in the current version. We just tried submitting payroll and experienced the same issue yet again! Now employees have received salary slips twice and the payroll isn't even successfully submitted yet! 

Kind regards,
