### ISSUE TITLE
Multi-book in consolidated financial report

### ISSUE THREAD

**Issue by PawanMeh** [frappe/erpnext#14525]
1. Created entries in both company and tax books for depreciation

![consolidated_balance_sheet](https://user-images.githubusercontent.com/20460498/41410419-12d6223a-6ff7-11e8-9f40-2396b0adb1f8.gif)

2. As you can see, the tax book shows only depreciation entries of the tax book but it does not show all other entries from the default book, which is "company" and is set at the company level. In actual scenario, it should show the default book transactions and only depreciation transactions from the tax book

**Comment by test2a** [comment]
Hello. Ive been trying to find a way to create Indian companies act, 2013 style Schedule 3 financial statement format but I don't know were to start. I read somewhere on the forum that it can be done by HTML and CSS but where do I start? Is there a format builder or do I have to get a plain notepad? Where to get the names of heads? Also schedules and notes to accounts. They should form a part of the balance sheet.

**Comment by rohitwaghchaure** [comment]
I have checked into my local account and found that when I have selected Company Finance Book, then system shows the gl entries made in the respective finance book as well the gl entries which has no finance book. But when I have selected "non default company finance book" then system has shows only the gl entries which has booked in the respective finance book. Which is the right.
@nabinhait can you please check this
