### ISSUE TITLE
Account receivable report - Invoice Amount, Paid Amount not fetching

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#14536]
Issue: Bug report

Steps:

1. I created multiple Sales Invoices, with different Due Date, to check aging in the receivable report.
2. In the report, it didn't fetched Invoices and Paid Amount for the invoices.
3. Also, it didn't update the amount in the aging columns.

Screenshots:

Invoice and Paid Amount not updated

<img width="1218" alt="screen shot 2018-06-15 at 4 29 13 pm" src="https://user-images.githubusercontent.com/910238/41464982-cfc6440c-70b9-11e8-841b-4b00fd8f7d55.png">

Invoice Due Date is a future date. Why is it updating aging days in negative. Also, no values updated in the columns.

<img width="1227" alt="screen shot 2018-06-15 at 4 35 02 pm" src="https://user-images.githubusercontent.com/910238/41465072-29a33e58-70ba-11e8-9d04-50a967c1ac72.png">

**Comment by rohitwaghchaure** [comment]
I am able to replicate the issue in my local account, but in data value is showing but not in the report

Response Data
![screen shot 2018-06-15 at 4 51 05 pm](https://user-images.githubusercontent.com/8780500/41465591-6928ee4a-70bc-11e8-8cef-04432ad479ab.png)


**Report View**
![screen shot 2018-06-15 at 4 51 22 pm](https://user-images.githubusercontent.com/8780500/41465603-72c4b074-70bc-11e8-9de7-9ab424e301b8.png)

**Comment by Zlash65** [comment]
https://github.com/frappe/erpnext/pull/14546
This fixes the data not being rendered issue.
