### ISSUE TITLE
[v11-develop] new address creation breaks

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#14538]
- open customer
- create new address
- does not set "link name"
- does not show up in customer

**Comment by chdecultot** [comment]
Hi @rmehta ,

I opened a ticket a while back on the same topic and @Zlash65 was not able to replicate it either: https://github.com/frappe/frappe/issues/5208

I have the feeling it is linked to the routing system and it is maybe depending on the browser's ?
I have seen this behavior mostly on Safari web browsers but also a couple of times on Chrome also.

Hope it helps!
