### ISSUE TITLE
Dynamic link not opening from the report

### ISSUE THREAD

**Issue by rohitwaghchaure** [frappe/erpnext#14556]
![screen shot 2018-06-18 at 12 16 25 pm](https://user-images.githubusercontent.com/8780500/41522527-f0bce580-72f3-11e8-96b8-a62c0f013e1f.png)

When I clicked on PREC - 00064
![screen shot 2018-06-18 at 12 16 19 pm](https://user-images.githubusercontent.com/8780500/41522540-fe82fde4-72f3-11e8-8ecc-cf5f88a09fa3.png)

**Comment by jaichavan** [comment]
This issue has been fixed. For your reference -

![issue-dynamic-link](https://user-images.githubusercontent.com/40264279/56792094-60960080-6826-11e9-93ac-9200c1e9ef83.gif)

Version details:

![Screenshot 2019-04-26 11 38 32](https://user-images.githubusercontent.com/40264279/56792165-963ae980-6826-11e9-99c0-22ff1772f147.png)
