### ISSUE TITLE
Birthday Reminders Still being Sent 

### ISSUE THREAD

**Issue by harikishorsingh060** [frappe/erpnext#14550]
We have turned off Birthday Reminders via HR Settings.
and We have Commented the following line from daily scheduler from hook.py file:
“erpnext.hr.doctype.employee.employee.send_birthday_reminders”,

**Comment by jaichavan** [comment]
Hello, @harikishorsingh060 wasn't able to replicate the issue in the latest version, can you please check and revert if it still _persists_?

**Comment by ruchamahabal** [comment]
https://github.com/frappe/erpnext/pull/27365
