### ISSUE TITLE
Company wise default letter head

### ISSUE THREAD

**Issue by snvora** [frappe/erpnext#14579]
Issue: Feature Request

Currently, we can set only one default letterhead, so manually letterhead needs to be changed every time.

Company wise default letterhead could make things easier.

**Comment by shreyashah115** [comment]
Isn't this what you're looking for?

<img width="716" alt="screen shot 2018-06-19 at 11 07 33 am" src="https://user-images.githubusercontent.com/17617465/41578676-077f3bac-73b1-11e8-8bfd-3f4a0bab2c7d.png">

**Comment by snvora** [comment]
Thanks,

Sorry for bothering.
