### ISSUE TITLE
Purchase Invoice - add total field for validation

### ISSUE THREAD

**Issue by jevonearth** [frappe/erpnext#1460]
On the Purchase Invoice, please add a new "Total" field that will be filled in manually by the user. The purpose of the total field is to compare the manually entered value with the total calculated from all lines + tax. 

When the user submits the payable invoice, validate that the totals match. The example shows a total entered, but the user forgot to specify the correct tax code (23% in this example).

I'm attaching a screenshot from another accounting system to help illustrate the concept.
![image](https://f.cloud.github.com/assets/1114943/2358269/311e1f6a-a60a-11e3-940c-451f7575d3e3.png)

**Comment by umairsy** [comment]
No similar feature request from another user. For now, please manage validation with the Custom Script.
