### ISSUE TITLE
Issue with dropbox backup

### ISSUE THREAD

**Issue by jaqobk** [frappe/erpnext#14619]
Am facing an issue with dropbox back up. It has been working but from my last bench update it stopped working and now am getting this error instead.
Backup Upload Failed
Oops, your automated backup to Dropbox failed.

Error message:

Traceback (most recent call last):
File “/home/frappe/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py”, line 47, in take_backup_to_dropbox
did_not_upload, error_log = backup_to_dropbox(upload_db_backup)
File “/home/frappe/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py”, line 115, in backup_to_dropbox
upload_from_folder(get_files_path(), 0, “/files”, dropbox_client, did_not_upload, error_log)
File “/home/frappe/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py”, line 124, in upload_from_folder
if is_fresh_upload():
File “/home/frappe/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py”, line 206, in is_fresh_upload
file_name = frappe.db.get_value(“File”, filters={‘uploaded_to_dropbox’: 1}, field=‘name’)
TypeError: get_value() got an unexpected keyword argument 'field’
Please contact your system manager for more information.

can anyone help me on this as am very interested in automatic dropbox backups.

Thank you.

**Comment by rohitwaghchaure** [comment]
Hi @jaqobk 
Fixed via https://github.com/frappe/frappe/pull/5703
Kindly pull latest update and check

**Comment by jaqobk** [comment]
I pulled the latest bench update and now facing a new error..

Backup Upload Failed

Oops, your automated backup to Dropbox failed.

Error message:

/privateslide_seven.png - Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py",
line 150, in upload_from_folder
    upload_file_to_dropbox(filepath, dropbox_folder, dropbox_client)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py",
line 161, in upload_file_to_dropbox
    file_size = os.path.getsize(encode(filename))
  File "/home/frappe/frappe-bench/env/lib/python2.7/genericpath.py",
line 57, in getsize
    return os.stat(filename).st_size
OSError: [Errno 2] No such file or directory: '/privateshop-homepage.css'

/privateshop-homepage.css - Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py",
line 150, in upload_from_folder
    upload_file_to_dropbox(filepath, dropbox_folder, dropbox_client)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py",
line 161, in upload_file_to_dropbox
    file_size = os.path.getsize(encode(filename))
  File "/home/frappe/frappe-bench/env/lib/python2.7/genericpath.py",
line 57, in getsize
    return os.stat(filename).st_size
OSError: [Errno 2] No such file or directory: '/privateslide_seven.png'

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py",
line 48, in take_backup_to_dropbox
    if did_not_upload: raise Exception
Exception

Please contact your system manager for more information.
Please help.
