### ISSUE TITLE
HSN code in Stock Entry

### ISSUE THREAD

**Issue by Basawa-SELCO** [frappe/erpnext#14610]
HSN code is available in print format for Delivery Note and Sales Invoice. But for Stock Entry, HSN code in not available in Standard Print Format. This is important and we need the HSN code printed for transporting material.

**Comment by shreyashah115** [comment]
You can add a custom field `gst_hsn_code` to Stock Entry Detail table and add a custom script to fetch the hsn code on selection of item code.

<img width="1256" alt="screen shot 2018-06-21 at 12 31 43 pm" src="https://user-images.githubusercontent.com/17617465/41703576-752170e8-7551-11e8-967b-f09785cd22d6.png">

<img width="1047" alt="screen shot 2018-06-21 at 12 47 42 pm" src="https://user-images.githubusercontent.com/17617465/41703577-7555a8fe-7551-11e8-9878-15c3e4394816.png">

Now just make a new Print Format and customize it to view the hsn field in it.

Pasting the script as well.
```
frappe.ui.form.on("Stock Entry Detail", "item_code", function (frm, cdt, cdn) {
var d = locals[cdt][cdn];
    frappe.db.get_value("Item", {"name": d.item_code}, "gst_hsn_code", function(value) {
    	d.gst_hsn_code = value.gst_hsn_code;
    });
});
```
