### ISSUE TITLE
URL encoding is broken when dealing with attachment filenames

### ISSUE THREAD

**Issue by jevonearth** [frappe/erpnext#1461]
Tested against v3.8.9

To reproduce:

Create a file name called "foo#bar.txt". Make sure to put some text in the file, as ERPNext seems to validate for zero byte files.

Upload the file to any DocType in ERPNext that accepts attachments.
After uploading file, click on attachment link, and observe error page.

URL Appears incorrectly as:

```
http://erp.example.org/files/foo#bar.html
```

URL Should be encoded something along the lines of:

```
http://erp.example.org/files/foo%23bar.html
```

**Comment by strixaluco** [comment]
Can't replicate in ERPNext: v7.2.29 / Frappe Framework: v7.2.28
