### ISSUE TITLE
Source Warehouse field in Stock Entry needs an auto filter to apply

### ISSUE THREAD

**Issue by stephanehausherr** [frappe/erpnext#14626]
Issue: Feature Request

Warehouses created to manage storage location in a lab as follow
Electronics Lab
ELEC-B001
…
ELEC-B034
SMT Assembly

1. In Item, add an Item (ELE-RES-1806025) with Allow Atlernative Item checked - Stock = 0
2. In Item, add a second Item (ELE-RES-1806009) - Stock = 1000 in ELE-B030
3. In Item Alternative, add an Item Alternative to to link the first Item with the second Item
4. Create a BOM with ELE-RES-1806025 needed.
5. Start a Work Order

ERPNext will automatically create a Stock Entry for Material Transfer for Manufacture.

In the Stock Entry, the Default Target Warehouse is set to SMT Assembl. And the Default Source Warehouse is left blank.

Before Saving the document, the Source Warehouse needs to be filled for each Item. The issue is that with my current Warehouse structure it is very difficult to edit the Source Warehouse.

ERPNext is listing all my ELEC-BXXX warehouse but I don’t know in which Warehouse I have stock.

Would make more sense that ERPNext show me only the Warehouses in which I have stock, maybe sorted by so the first filtered Items is the first stock I should used.

![stock entry](https://user-images.githubusercontent.com/40456240/41708205-366bab18-7540-11e8-9f20-30a516a27b32.png)

**Comment by mobentec** [comment]
This would be very helpful.  When might this be implemented?
