### ISSUE TITLE
Sales Invoice Creation too slow

### ISSUE THREAD

**Issue by rishinikhil** [frappe/erpnext#14624]
Dear Team,

When we create Sales Invoice, it is taking too much time. We have more than 50 items at an average in one Sales Invoice.

It takes 5 seconds to add row after you click on the add row button and 10 seconds after we write the item SKU in the row. Overall in a minute we are able to add just 4 items.

This happens as soon as the Sales Invoice crosses around 30-50 items. The whole process of adding 4 items a minute is highly irritating and frustrating. 

I think the issue is a big UX issue and because of following reasons:
1. We heavily use barcode scanner to add SKUs to Invoice, and POS is not a solution for us as it has limited functionalities.
2. The JS/page which fetches line items from item master becomes too heavy and consumes a lot of time.
3. There is no way by which I can add multiple items in one go via upload/download, like in Stock reconciliation child items table.
4. We cannot use Add Multiple like in Sales Order as we use Barcode Scanner to add SKUs, add multiple makes you search item and then you select item, it equally time taking.
5. There is no way by which we can move to the next row directly after we scan the item, the barcode scanners append the enter/return key after the SKU.

I propose the following solutions:
1. Easiest, quickest and temporary way to resolve the issue is to allow the upload option like in Stock Reco form. I will scan the items in an excel sheet and then upload it to the Child Table. It will take time, but it will be atleast better than adding 4 items a minute. Please note that I can upload only the SKUs, not their respective pricing in the upload sheet, the pricing will be fetched from the price list assigned to the customer or selected in the Sales Invoice.

2. Optimize your UX and the page, which allows the user to directly move to next row after the item is scanned. The user need not wait for the page to fetch the item details.

This problem renders the complete ERP useless, please provide a solution immediately. This issue has been raised multiple times in the forum, but I dont think you guys have been able to provide concrete solution so far.

**Comment by jaichavan** [comment]
Hello, @rishinikhil 
The Upload option for uploading bulk data into the Items child table has been enabled in Sales Invoice.
Hoping that has made the task less tedious.

**Comment by rishinikhil** [comment]
@jaichavan I dont think the resolution as helped. 
The upload asks me to enter all columns data - item name, description, price list rate etc.

That means i have to manually write all the data, instead of the data being pulled from masters. This is not feasible at all. Essentially, the solution done is next to useless.

Logically, this upload should only take lets, say the item_code from me and then fill the data after upload from masters automatically.
