### ISSUE TITLE
V11 Staging Error in Calendar view when Filtering on 'Assigned to me'

### ISSUE THREAD

**Issue by joolsr** [frappe/erpnext#14632]
Issue: Bug report

**Do the checklist before filing an issue:**
 - [x] Have a usage question? Ask your question on  [Discuss Forum](https://discuss.erpnext.com). We use [Discuss Forum](https://discuss.erpnext.com) for usage question and GitHub for bugs.
 - [x ] Can you replicate the issue? 
 - [ ] Is this something you can debug and fix? Send a pull request! Bug fixes and documentation fixes are welcome

**Describe the bug** :chart_with_downwards_trend: 
Note : I have cloned my existing v10 production instance and then upgraded to V11 Develop branch. Thus I have the exact same data in my Production and Develop instances. Any differences with same data is likely to indicate a bug.

In my V10 Production instance - I see no errors. v10.1.37 (master). Frappe Framework: v10.1.36 (master)
In my V11 Develop instance,  When I go to Events and Calendar view, If I select 'Assigned to me' then I get an error 'Filter must have 4 values (doctype, fieldname, operator, value): [u'Event', u'_assign', u'like', u'%julian.robbins@elite-antennas.com%', False]'

**To Reproduce** :page_with_curl:
1. Go to 'Event Calendar'
2. Click on '.Assigned to Me...'
3. See error - 'Filter must have 4 values (doctype, fieldname, operator, value): [u'Event', u'_assign', u'like', u'%julian.robbins@elite-antennas.com%', False]''

**Expected behavior** :chart_with_upwards_trend:
in v10, no error. In v11 error as above.

**Screenshots** :crystal_ball:

**Desktop (please complete the following information):** :cyclone:
 - OS:
    - [x ] Linux
    - [x ] macOS
    - [x ] Windows
    - [ ] Others? Please mention: 
 - Browser:
    - [ ] Safari
    - [x ] Chrome
    - [x ] Firefox
    - [ ] Other? Please mention: 

**Smartphone (please complete the following information):** :iphone: :computer:
 - Device:
    - [ ] iPhone
    - [ ] Android
 - Browser:
    - [ ] Safari
    - [ ] Chrome
    - [ ] Firefox
    - [ ] Other? Please mention: 

**Version Information**
- Which branch are you on?
    - [ ] `master` :star2: 
    - [x ] `develop` :fire:
- Frappe Version: 
- ERPNext Version: 

**Additional context** :page_facing_up:
This can be easily replicated on beta.erpnext.com

**Possible Solution** :bookmark_tabs:
Any idea what might be causing the issue. Or if you have a proposed solution to the problem,

**Please don't be intimidated by the long list of options you've to fill. Try to fill out as much as you can. Remember, the more the information the easier it is for us to replicate and fix the issue** :grin:

**Comment by joolsr** [comment]
![peek 2018-06-21 22-41](https://user-images.githubusercontent.com/934876/41746974-3bd5ecee-75a4-11e8-9a9f-5df94772df37.gif)

**Comment by joolsr** [comment]
@nabinhait Hello Nabin
Apologies for asking you directly, but just to mention this is a real, identifiable, and fully reproducible on beta.erpnext.com V11 Develop Bug. Not the highest priority I accept but should be allocated to fix at some point ;-)

**Comment by joolsr** [comment]
Still results in an error with latest v11 in Staging as of 6th Sep 2018 .. @netchampfaris Can you help?

**Comment by joolsr** [comment]
Same error as https://github.com/frappe/erpnext/issues/14632

**Comment by Anurag810** [comment]
![assign to me](https://user-images.githubusercontent.com/32095923/50571937-eb687080-0ddb-11e9-87d9-f001434da048.gif)


It is working on my instance which is also on v11 .
