### ISSUE TITLE
Balance sheet for Multiple company 

### ISSUE THREAD

**Issue by mukul10842** [frappe/erpnext#14638]
Issue: Feature Request

**Is your feature request related to a problem? Please describe.**
I have multiple company. In which one is parent company. I am not getting all company details in single balance sheet

**Describe the solution you'd like**
 If we create 3 company in which one parent company. If we create balance sheet then balance sheet will be different or can I get all 3 company details in single balance sheet

**Describe alternatives you've considered**
In tally  and SAP we can create multiple company and get all details of each company in parent company balance sheet
**Additional context**

**Comment by Muzzy73** [comment]
This feature is expected V11 that would be released soon.

**Comment by kennethsequeira** [comment]
Solved here: https://erpnext.org/releases/version-11/features/accounting
