### ISSUE TITLE
Add Correspondence Feature

### ISSUE THREAD

**Issue by 12345678max** [frappe/erpnext#1464]
we want communication to be present at the dash board of customer. it will be work as a letter head as well as all correspondence can be done by customer thru this . it will be very useful .

generally regular correspondence are required with customer during finalisation of any order . there will be record of it. further we can print and submit hard copy of it customer just like quotation etc.This will be very useful feature of erpnext.

then erpnext will be paperless job for any sme and industry.

**Comment by umairsy** [comment]
feature already available in ERPNext V7.
