### ISSUE TITLE
New Sales Return without Sales invoice

### ISSUE THREAD

**Issue by outerlook** [frappe/erpnext#14652]
I`ve noticed most people work with sales return **against specific** sales invoices. But for some particularities of my workflow, credit notes may come with **no knowledge** of which document it belongs...

Is there any way of doing this: **create a credit note without an invoice to be against**?

Sorry if this is already under development, I tried to find any open issue of it!

I can't use any sales invoice of that customer as a workaround because there may be more items on the credit note than on the invoice...

**Comment by LifeP** [comment]
https://discuss.erpnext.com/t/how-to-create-sales-return-purchase-return-sales-refund-purchase-refund-etc/7571/8

**Comment by outerlook** [comment]
#14269 will solve this! Thanks @LifeP
