### ISSUE TITLE
when sending new letter to customer will show 'UnicodeEncodeError' 

### ISSUE THREAD

**Issue by Albert-Hugo** [frappe/erpnext#14661]
Issue: Bug report

http://localhost/desk#Form/Newsletter/New%20Newsletter%201
1. Go to 'http://localhost/desk#'
2. Click on 'selling'
3. Click on 'tools'
4. Click on 'Newsletter'
5. Click on 'New ' to create a new Letter 
6. then input the 'Newsletter List'  with a Chinese character 
7. fill other mandatory fields
8. Click on 'test' button

**Expected behavior** :chart_with_upwards_trend:
it should show a message: Scheduled to send to xx@xx.xx

**Screenshots** :crystal_ball:
![image](https://user-images.githubusercontent.com/33504588/41815916-ac8f5512-77aa-11e8-884b-f5cee83727b5.png)

**Desktop (please complete the following information):** :cyclone:
 - OS:
    - [ 10.13.5] macOS

   - Browser:
    - [ 67.0.3396.87] Chrome

**Comment by kennethsequeira** [comment]
@Albert-Hugo was this issue solved? 

If not, would require the full traceback, the ERPNext and Frappe versions.

**Comment by kennethsequeira** [comment]
Closing this issue as no feedback was received.

Will reopen if more info is provided/validated
