### ISSUE TITLE
Expense list display issue

### ISSUE THREAD

**Issue by JanisGilham** [frappe/erpnext#14674]
Hello,

We are experiencing an issue with some employees are able to see all expense reports for the company.  I have not been able to find any additional permissions given to these users to allow them to see the expense list.  

Thanks

**Comment by joolsr** [comment]
If you are a cloud hosted customer of Frappe you will get a quicker response if you email their support directly.

**Comment by kennethsequeira** [comment]
@JanisGilham 

Try posting this on the forum first: https://discuss.erpnext.com or to your hosting provider.

If validated as a bug the issue can be reopened. Also state your frappe and erpnext versions.
