### ISSUE TITLE
Reverse Charge in Purchase Invoice[GST India]

### ISSUE THREAD

**Issue by djpalshikar** [frappe/erpnext#14684]
Issue: Feature Request

Some supplier categories in India are exempt from filing GST returns, and a equivalent reverse charge has to be paid by the buyer.

Therefore, the GST charges should not reflect on the ledger of the Supplier but should affect the related GST ledgers.

Currently there is no way to handle Reverse Charge in Purchase Invoice, and reverse charge has to be handled using Purchase Invoice.

Making a small change to **Purchase Taxes and Charges Template** should fix this:

In the field , "Consider Tax or Charge for", should have another option : **Reverse Charge**. If a charge is added here, the amount should **not** be added to Total and should **not** affect the ledger of the Supplier.
It should affect the reverse charge ledger as per configuration.

**Comment by djpalshikar** [comment]
Similar Features Request #14349 , #10894

**Comment by deepeshgarg007** [comment]
@djpalshikar All the GST-related things are moved to the India Compliance app. Please raise this on https://github.com/resilient-tech/india-compliance/pulls if this is still valid
