### ISSUE TITLE
Item name after item code missing on some important places

### ISSUE THREAD

**Issue by outerlook** [frappe/erpnext#14692]
Hi! I noticed there are some places I think it would be good to have the same behaviour as this sales invoice case...

Expected (Sales Invoice)
![image](https://user-images.githubusercontent.com/12937160/41932554-9f701656-7957-11e8-8199-5eb83da0c569.png)

I think is missing on:
Purchase Invoice
![image](https://user-images.githubusercontent.com/12937160/41932611-c795be92-7957-11e8-8a6c-202b0d676a94.png)

Stock Analysis report
![image](https://user-images.githubusercontent.com/12937160/41932643-e5325fe6-7957-11e8-8a05-db620627f6b8.png)

Stock entry
![image](https://user-images.githubusercontent.com/12937160/41932700-18294d1a-7958-11e8-970b-d5ca9300a5e5.png)

**Comment by Zlash65** [comment]
#### Purchase Invoice
<img width="412" alt="screenshot 2018-10-24 at 4 12 36 pm" src="https://user-images.githubusercontent.com/11695402/47425360-bde1c400-d7a7-11e8-8ce6-0bbde047ae42.png">

#### Stock Entry
<img width="548" alt="screenshot 2018-10-24 at 4 12 09 pm" src="https://user-images.githubusercontent.com/11695402/47425377-c6d29580-d7a7-11e8-8004-806276f8eed4.png">

Seems to be working fine and as for the report - now that the datatable is in place, it'd be added to its list of issues.

Closing it for now, please reopen it if still persist.
