### ISSUE TITLE
[V11] Purchase Receipt, Asset link field should be read-only

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#14728]
For the serialized asset, in the Purchase Receipt, there is field for Asset ID selection. This field should be read-only and visible once Asset ID is created and updated for the Purchase Receipt Item.

<img width="1195" alt="screen shot 2018-06-28 at 4 42 02 pm" src="https://user-images.githubusercontent.com/910238/42031163-e45de6e8-7af2-11e8-9e8b-3ebb61f29a1b.png">

Since it is editable now, I could select exist Asset for the new purchase. However, in the new purchase, new Asset ID was not created.

**Comment by rohitwaghchaure** [comment]
Have fixed https://github.com/frappe/erpnext/pull/14727
