### ISSUE TITLE
[V11] Workflow - Approve button not shown

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#14729]
Workflow with the condition:

<img width="1328" alt="screen shot 2018-06-28 at 4 48 16 pm" src="https://user-images.githubusercontent.com/910238/42031299-6abe63a2-7af3-11e8-9ee4-4774eaf3aac6.png">

When saving a Quotation, first state is applied. But it doesn't show button to Approve it.

@PawanMeh could you review it once?

**Comment by PawanMeh** [comment]
@umairsy , do you have "Allow Self Approval" checked in your workflow set up?

![screen shot 2018-06-28 at 4 58 36 pm](https://user-images.githubusercontent.com/20460498/42031734-f0a7264c-7af4-11e8-8d69-4ba611f48eea.png)

**Comment by umairsy** [comment]
No. But didn't work, even if it was checked.

**Comment by PawanMeh** [comment]
@umairsy , it is working fine in my latest develop. Below is screen shot of workflow

![1-quotation_approval](https://user-images.githubusercontent.com/20460498/42070557-9d93ca0c-7b74-11e8-8f36-90cf6f76ae2f.png)

![2-quotation_approval](https://user-images.githubusercontent.com/20460498/42070565-a60794de-7b74-11e8-844f-a49489e7b76d.png)

Testing video

1. Below 1000 sales user can approve 

![sales_user_under_1000](https://user-images.githubusercontent.com/20460498/42070676-2cbce100-7b75-11e8-92d0-eace2602244e.gif)


2. Above 1000 sales manager is allowed to approve

![sales_user_above_1000](https://user-images.githubusercontent.com/20460498/42070683-369bd3e8-7b75-11e8-8130-630fd55ad836.gif)

**Comment by surajshetty3416** [comment]
Fixes in https://github.com/frappe/frappe/pull/5926
