### ISSUE TITLE
Asset Maintenance Task

### ISSUE THREAD

**Issue by Crikeyy** [frappe/erpnext#14739]
Unable to access Asset task doctype
1. Go to '.Assets - Asset Maintenance Log. Add the asset name.
2. Add the asset name.
3. Go to task... There is no option to add new task. 
3. Search for asset task or asset task list in awesome bar and you are unable to find either. There is no access to the doc type asset task.
https://user-images.githubusercontent.com/34661344/42039168-aacaff0a-7ae4-11e8-9150-10e783de47a9.png

 - OS:
    - [ ] Linux
    - [ ] macOS
    - [* ] Windows
    - [ ] Others? Please mention: 
 - Browser:
    - [ ] Safari
    - [* ] Chrome
    - [ ] Firefox
    - [ ] Other? Please mention: 

**Smartphone (please complete the following information):** :iphone: :computer:
 - Device:
    - [ ] iPhone
    - [ ] Android
 - Browser:
    - [ ] Safari
    - [ *] Chrome
    - [ ] Firefox
    - [ ] Other? Please mention: 

**Version Information**
- Which branch are you on?
    - [* ] `master` 
    - [ ] `develop` 
- Frappe Version: 10.1.40
- ERPNext Version: 10.1.37

**Comment by shreyashah115** [comment]
@Crikeyy 

Tasks in Asset Maintenance Logs are fetched from the tasks you have added in Asset Maintenance document. It is a child table hence, you can't create a new Task from the Asset Maintenance Log, you will have to add it to the Task table in the Asset Maintenance and only those values will be fetched. Also, as it is a child table, it will not be shown in the search bar as well.

Hope you get the point.
