### ISSUE TITLE
[V11] Salary Component - Control checking for Benefit claims

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#14737]
In the Salary Component, checking of some fields should be based on value in other fields. Cases below.

<img width="1198" alt="screen shot 2018-06-28 at 6 41 36 pm" src="https://user-images.githubusercontent.com/910238/42036442-2b14e32e-7b03-11e8-8b83-7a6d78093368.png">

If "Pay Against Benefit Claim" and "Create Separate Payment Entry Against Benefit Claim", then field "Only Tax Impact (Cannot Claim But Part of Taxable Income)" should not be allowed to check.

Also, the vice-versa of above use-case should be true.

Also, if "Statistical Component" is checked, then whole section of Flexible Benefits and Accounts should be hidden.

**Comment by umairsy** [comment]
Also check if we need both "Do not include in total" and "Statistical Component".

**Comment by rkurungadam** [comment]
Statistical Component is not added to Salary Slip at all, while Do not include in total is added. Statistical Component will be required but not sure about a use case for Do not include in total, please confirm if we can remove this.
