### ISSUE TITLE
Stock Ledger Entry Table should retain the Valuation Rate

### ISSUE THREAD

**Issue by adityaduggal** [frappe/erpnext#1473]
Currently the valuation rate is reset to ZERO in stock ledger entry table is the quantity of the item a particular Warehouse becomes ZERO, I propose that the valuation rate should not be reset to ZERO even if the quantity becomes zero.

**Comment by joezsweet** [comment]
@adityaduggal could please double check this issue with last version?

**Comment by adityaduggal** [comment]
@joezsweet I have actually created a new doctype valuation_rate in my custom app which is used for referencing the valuation rate. So basically the costing team would add the valuation rate for an item and then the stock entries and stock reconciliation takes the values from that doctype.

Currently there is no way to define the valuation rate for an item and the system expects a person doing stock entry to enter the valuation rate which is kind of unexpected from a person who is only responsible for stock and not its valuation.

**Comment by joezsweet** [comment]
Closing this one, thx
