### ISSUE TITLE
[V11] Frappe - child table - Row deletion issue

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#14731]
When deleting row from child table, instead of removing that row, it updates the column heading in it.

![row-deletiomn](https://user-images.githubusercontent.com/910238/42031513-190dc754-7af4-11e8-86aa-0ff195e7805a.gif)

Here is the message from console:

grid.js:133 Uncaught TypeError: Cannot read property '__checked' of undefined
    at grid.js:133
    at Array.map (<anonymous>)
    at init.get_selected (grid.js:133)
    at HTMLButtonElement.<anonymous> (grid.js:102)
    at HTMLButtonElement.dispatch (jquery.min.js:3)
    at HTMLButtonElement.r.handle (jquery.min.js:3)

**Comment by Olawale1** [comment]
Hi @umairsy 

Trust you're doing well. Was this fixed only in V11? We are facing this exact same issue on V10

ERPNext: v10.1.81 (898977b) (v10.x.x)
Frappe Framework: v10.1.71-8 (92dc1e0) (v10.x.x)

Kindly help extend fix to V10

Thanks

**Comment by umairsy** [comment]
Olawale,

Will be best to upgrade to V11, as with this, there are many other crucial fixes in V11.
