### ISSUE TITLE
[V11] Travel Request - No calculation for Total Amount

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#14762]
Please automate the calculation in the Total Amount field. This doctype doesn't have any js of py script. Request overall review as well.

<img width="1198" alt="screen shot 2018-06-30 at 1 30 42 am" src="https://user-images.githubusercontent.com/910238/42112433-678d677e-7c05-11e8-91d8-0daf256b5ae8.png">

**Comment by deepeshgarg007** [comment]
@umairsy Move this to HRMS repo, closing this for now
