### ISSUE TITLE
heat map issue

### ISSUE THREAD

**Issue by jaqobk** [frappe/erpnext#14774]
hi

am reporting an issue and am trying to set global defaults to show heat map on dashboard which has not been showing any activities there and all boxes are greyed. unfortunately there seems to be no that deafult setting to choose discrete or continous.. how can I enable this to show.. am using master branch and updated last week on thusday.

**Comment by crescent28** [comment]
Can you please let me know which version are you using?

**Comment by jaqobk** [comment]
solved
