### ISSUE TITLE
On-time Delivery and Shipping Report

### ISSUE THREAD

**Issue by MattGenx** [frappe/erpnext#14804]
Issue: Feature Request

**Is your feature request related to a problem? Please describe.**
For many manufacturing companies, quality metrics become a vital role in measuring and improving current system procedures.  Two of the most common metrics that need to be measured is on time deliverables being shipped and received.   I have found the ERPnext does not have any reporting to capture this data.  I have tried to create my own fields that copy the "delivery date" from the Sale Order Item table to a new "Delivery date" on Delivery Note Item table with no luck.

**Describe the solution you'd like**
I would like to see some type of report that can compare the delivery date on a Sales Order Item or Purchase Order Item to the Posting date on a Delivery Note or Purchase Receipt.   This will tell us what items are shipped late or received late compared to the acknowledged ship date or received date.

**Describe alternatives you've considered**
Alternatives can be anything that would provide data needed to compare when items are shipped / received to when they were originally acknowledged.  

**Additional context**

**Comment by LifeP** [comment]
Deliverables is a key metric even for service and IT industries.

**Comment by MattGenx** [comment]
Even more reason to have this type of reporting available :)
