### ISSUE TITLE
Validation Issue: In Sales Invoice customer po_no is overwritten by Null po_no from Sales Order

### ISSUE THREAD

**Issue by FinForceConsulting** [frappe/erpnext#14812]
Hello!
I noticed small issue with validation between SO and SI, while fetching Customer PO No.

I have SO, in which I did not mention po-no, but in the connected SI, since the customer po_no is 'Data' filed, I tried entering po_no at SI and saved it.

Surprisingly, po_no does not get saved as it validates the po_no mentioned at connected SO level (which in my case is blank). However, same logic/validation does not apply to po_date and that is getting saved at SI level from entered value.

Now to capture po_no in SI, I have to put it into connected SO and save it. On saving SI again, it fetched from SO, which I just entered.

I feel there is an issue with validation here. If there is SO po_no exist take that, if not accept what is getting entered as SI po_no. In addition, a message to User notifying the po_no being captured from SO would be useful.

**Comment by kennethsequeira** [comment]
Replicated
