### ISSUE TITLE
Regarding Marking Attendance for all the employees 

### ISSUE THREAD

**Issue by parvati-hoogar** [frappe/erpnext#14818]
Hello, this is Parvati Hoogar,
1)There is an issue in marking attendance for all the employees, If employee has applied for leave for future dates, if same is approved on the pre-date then I'm getting as leave is been approved & marked attendance simultaneously but when I check in the attendance tool its marked but as the present actually it should be marked as absent.
2)Post dated employees are also shown in the attendance sheet Ex: If I'm marking attendance for the active working employees, then only active employees list should be shown in the attendance instead of that I'm getting whole list post dated employees as well resigned employees details. plz check & let me know.
![screenshot from 2018-07-05 15-48-26](https://user-images.githubusercontent.com/40623491/42317818-ea294fa4-806a-11e8-8356-53c7664d8647.png)

**Comment by Solufyin** [comment]
Hello @parvati-hoogar 

For point 1 ) the attendance is shown as marked, which is correct. Marking attendance shows employees is either marked as present, absent or on leave. i.e. when employee fillup the Leave application and submit the record and approved it by Leave approver at that time automatically system will generate the Attendance entry but there state is as on leave.
when we are check the status form the Employee Attendance Tool, its shows the entry of the attendance. So it is not a issue.

For Point 2) It is also working fine with the staging branch.

We tested both points with latest staging branch.
ERPNext: v11.0.3-beta.15 () (staging)
Frappe Framework: v11.0.3-beta.14 () (staging)

So, we can close this issue.

Thanks

**Comment by philliy** [comment]
when we try to mark attendance it says "Attendance can not be marked for future dates" time was correct according to time zone too but .... can anyone help pls
