### ISSUE TITLE
Finance/Service Charge added automatically

### ISSUE THREAD

**Issue by heatherpotter** [frappe/erpnext#14842]
In our industry and many others, a service charge is added to a customer's account automatically upon no payment after a certain time period. Typically, it's net 30 or net 15 so if their invoice isn't paid in those terms, a % charge is added to the invoice. We have always issued this as a new invoice of sorts - we named it SC#####. This invoice was auto-created in our old system based on the terms. We would run a report of all service charges monthly and occasionally, we might go in and cancel or remove one if there was an error or problem with shipment, pricing dispute, etc..  but the SC invoice was created automatically for us. This would be a nice feature to have. 

Almost all of our customers incur service charges but we do have a few select ones that do not so having a check box on the customer doctype for "Service Charges" is necessary. For us, all of our service charges are the same 1.5% of the invoice past due balance.

I am willing to pay for this feature.

Thanks!
Heather

**Comment by Synertic** [comment]
Hi, this is a must. I'm not a coder but there is the way I think it should be done.

Set Payment terms on customer account ( net15, net30 etc)
At the same in credit limit and payment terms add a check box for Applying late fees. When enabled a late fee box appear and we can select the late fee that we want to apply. A drop-down menu like the payment terms will be nice.  That way we can set a default late fee or other king of late fees. We need % base fee or fix amount late fees. Also the choice to make those fees taxable or not.

We need to apply the late fee on past late fees.

In the back end the system will check every day if the customer has overdue invoices and calculate the fee base on the late fee selected and calculate the amount for all late invoice from the billing date (not the due date) to the current day. This amount will be saved and visible from the client account and on the accounting menu with sales invoices (extra links named "Pending Late Fee").

From that menu we can choose to delete some fee or bill those fees.
Add option to add a fee on next invoices, bill fees on separate invoices or just show late fees on client monthly statements.

We have to see each fee are from which invoice. 
Description like: Late fee from invoice INV-123245 2018-12-19, 60 days past due (how many days from billing date)

Don't forget to make those fees calculate every month. If a client has an invoice past 5 months, we have to charge interest for those 5 months.

thank you

**Comment by pifabs** [comment]
anyone working on this?

**Comment by HarryPaulo** [comment]
@heatherpotter u still want this?

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.

**Comment by HarryPaulo** [comment]
This request is working in progress on this PR

https://github.com/frappe/erpnext/pull/27528

**Comment by harshit-30** [comment]
Thanks @HarryPaulo :) can you please ask @barredterra to link this issue with the PR
