### ISSUE TITLE
Need a Barcode Generator in ERPNext itself

### ISSUE THREAD

**Issue by AravindPranera** [frappe/erpnext#14852]
Kindly develop a feature of generating a Barcode system for Doc Id and Item in ERPNext itself.

**Comment by agritheory** [comment]
Hey @AravindPranera this is a neat idea, if you can add some additional explanation or maybe some images from another system that's using this it will help build this out.
@kennethsequeira could we use the db document hash to generate the barcode/QR code? Though maybe that's a bad idea for security reasons. Certainly that random hash function is a good place to start.

**Comment by AravindPranera** [comment]
@kennethsequeira Kindly let me know the status of this request.

**Comment by xickomesquita** [comment]
> Hey @AravindPranera this is a neat idea, if you can add some additional explanation or maybe some images from another system that's using this it will help build this out.
> @kennethsequeira could we use the db document hash to generate the barcode/QR code? Though maybe that's a bad idea for security reasons. Certainly that random hash function is a good place to start.

https://barcode.tec-it.com/en/?data=ABC-abc-12341234-ABC-abc
