### ISSUE TITLE
Opening Invoice Creation Tool Field mapping

### ISSUE THREAD

**Issue by heatherpotter** [frappe/erpnext#14865]
The opening invoice creation tool is a big time saver but the inability to enter a supplier invoice number caused us great grief in putting our invoices in. The ability to pull in supplier invoice number is a necessity for bookkeeping and cross checking your payments and records.

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.
