### ISSUE TITLE
Black Rectangle box appearing

### ISSUE THREAD

**Issue by mattmcleans** [frappe/erpnext#14866]
Hey,

Erp invoice was working fine yesterday (9/7/18) and over night something has changed and now we have a black rectangle box across the top of the invoice sheet blocking out customer details.

I need this fixed immediately.

**Comment by kennethsequeira** [comment]
Can you post this on https://discuss.erpnext.com? 

If this is confirmed as a bug, we'll reopen this issue.

Also, provide the version of the software you are using and a screenshot of the current print where the details are blocked.

**Comment by mattmcleans** [comment]
![20180711_110410 modified](https://user-images.githubusercontent.com/41099779/42599382-643f0068-85a2-11e8-85b0-7fdae57ab636.jpg)

Software?  We have a mix of PC's and Macs but that doesnt change the outcome.
Yes i will post on Discusserp
