### ISSUE TITLE
[Bug] Bank Account Not Created Buy Default

### ISSUE THREAD

**Issue by kennethsequeira** [frappe/erpnext#14877]
Fresh Setup. Finished passing setup wizard, the bank account was not added by default

![screen shot 2018-07-11 at 6 10 01 pm](https://user-images.githubusercontent.com/33246109/42571812-aeb0614a-8535-11e8-8047-48b489ab9cbd.png)

ERPNext: v11.x.x-develop (21d3352) (develop)

Frappe Framework: v11.x.x-develop (db3a950) (develop)

**Comment by shreyashah115** [comment]
Not able to replicate, tried it on a new site.

<img width="458" alt="screen shot 2018-07-16 at 9 18 21 am" src="https://user-images.githubusercontent.com/17617465/42742561-35804c3e-88d9-11e8-9ccc-dc820033a60a.png">
