### ISSUE TITLE
Sell items in POS with multi Unit of Measure

### ISSUE THREAD

**Issue by HORKimhab** [frappe/erpnext#14887]
Hello, Community!
Problem is to sell items in POS with multi Unit of Measure. 
![discuss erpnext002 1](https://user-images.githubusercontent.com/41143106/42619812-48c3b694-85e3-11e8-9652-384ca503689c.png)

Thank you.

**Comment by Olawale1** [comment]
Hi ,

Any porogress here? This would be a really useful feature

Thanks

**Comment by satishmalkar94** [comment]
Hi,
Is any progress here?Regarding the multiple UOMs?
