### ISSUE TITLE
Webpage to show all items in a single page along with add to cart option

### ISSUE THREAD

**Issue by kothagunda** [frappe/erpnext#14883]
**Background** : We are an organic farmers cooperative who have started to use ERPNext starting this fiscal year. We have also started the portal www.sahajaaharam.org. The very first feedback we received was that the number of clicks/pages user has to go through to add just one item is 5 clicks. 

**Problem**: Since ours is a groceries/vegetables products portal, users will generally select 10-15 items in a checkout. So the customers have a hard time doing 5 clicks and visiting 5 pages for each item. Below are the steps user has to take
1. Click on Item Group
2. Click on item. (generally its the template)
3. Click on the variant you want to choose.
4. Click on view cart and then increase the number of qty you need.
5. Again go back to item groups for adding next item.

**Suggested Solution :** 
So were wondering if we could have a all products page. Where it will show individual item variants. And will have the option to add it to the cart right away . Below is an example of how open food network deals with this issue.

https://openfoodnetwork.org.uk/stroudco/shop 

![image](https://user-images.githubusercontent.com/30433779/42611577-71f3a4fe-85b4-11e8-81e7-d0d707504f16.png)

**Design** :
1. Shopping cart settings should have some settings to show such all items page.
2.  There should be filters on that page to choose products of only a particular item group, **or multiple item groups**, or all item groups.
3. Need to have an option to show only items whose stock is available.
4. Directly adding item to shopping cart, and also increase qty should be provided.
5.  Pagination option should be considered, to take latency/performance into consideration.

**Comment by rasos** [comment]
Agree that the churn rate could be lowered with fewer clicks. I would like to add a point:     
6. Improve image view: Allow to select which area of the image is used for preview. Currently it is a quadratic centered subset of the image, which often cuts relevant information.

**Comment by sugurujay** [comment]
@kothagunda even i am also looking for same features, to reduce the number of clicks per pages for the user

**Comment by kothagunda** [comment]
Lets hope that it would be picked up for development.

cc @kennethsequeira
