### ISSUE TITLE
Always showing Opportunity Status not saved: 

### ISSUE THREAD

**Issue by navdeepghai1** [frappe/erpnext#14880]
Every time when I try to open opportunity. It's only showing **not saved** status of opportunity.
I also reviewed the code:
**It's because of below code :** 
opportunity.js and line no 150 
```
cur_frm.cscript.onload_post_render = function(doc, cdt, cdn) {
        if(doc.enquiry_from == 'Lead' && doc.lead)
                cur_frm.cscript.lead(doc, cdt, cdn);
}
```
If I use workflow for Opportunity  then User's aren't not able to see actions buttons because of not saved status.
refresh function also triggering two times while loading the Opportunity form first time.

**Comment by kennethsequeira** [comment]
Is this a custom script? This issue is not reproduced on my test account.

Also post your ERPNext and Frappe apps version.

**Comment by navdeepghai1** [comment]
@kennethsequeira 

I will share more info on it.

For Instance:
>> When new enquiry came from new customer then user used to create Lead and then Opportunity from lead.
>> Once user create  opportunity from lead, on post creation of opportunity from lead whenever user modify  the opportunity information without modifying the lead form.
Then after modification of opportunity when user reload the opportunity or revisit the opportunity form then It's always showing opportunity status as not saved.

>> I  know why, because while loading the opportunity form for first time the code below will be trigger.
```
cur_frm.cscript.onload_post_render = function(doc, cdt, cdn) {
        if(doc.enquiry_from == 'Lead' && doc.lead)
                cur_frm.cscript.lead(doc, cdt, cdn);
}
```
>> The code above  maps the lead form  fields values with the oppportunity form fields values and override the Opportunity form fields values with lead form fields values if it's changed in opportunity.

>> If we don't use workflow then we have the save button to save the form, but while using workflow we are not able to save button and not even workflow action button.

**Comment by jaichavan** [comment]
Hello, @navdeepghai1 not able to replicate the issue on my test / local setup. Can you please check and revert (with version number) if the issue _persists_?

**Comment by navdeepghai1** [comment]
@jaichavan 

I'll share one scenario with you,  for instance:

>> 1. User has created the lead (0001) with **Sam** as name of the person.

>> 2. Now when user create opportunity from lead (0001) then opportunity form get mapped with lead automatically and mapped the person name in lead with customer name in opportunity.
 
>> 3. Every time when user open the opportunity it's mapped the lead form with opportunity(if it's created from lead).

>> 4. If user changed the person name in lead from **Sam to Sam Smith** and open the opportunity after saving the lead form then opportunity status will become not saved, because it's getting mapped with lead every time(on load) and in lead user has changed the person name which is getting mapped in opportunity with customer name(it's happening if common fields values in lead form are not matching with opportunity form).



If user didn't define the workflow for opportunity then user can easily save it with write permissions and make quotation from it.
Now imagine if user don't write permissions for opportunity and want to create quotation from it(because he has read permissions) then user won't be able to create quotation, because he/she has to save it to create the quotation(otherwise it'll show the message, please save the unsaved changes).

In workflow it's really annoying for users.
