### ISSUE TITLE
Purchase Return restricted only to default UOM

### ISSUE THREAD

**Issue by ushashmi** [frappe/erpnext#14886]
After upgrade to version 10.1.42 and Frappe Framework: v10.1.39 we are facing issue in purchase return. 

While returning items which were purchased ( through Purchase Receipt) in different UOM, system is not allowing to return the exact quantity which was purchased. It get restricted only to default UOM. Please find below the use case; 

Default UOM: KG
Purchase UOM: BAG with Conversion Factor: 25
Quantity Receipt= 10 BAGs means 250 KGs

While making a return, system dont allow to return 10 BAGs it only returns 10 KG only. 

Requesting ERPNEXT team to fix the issue ASAP.

**Comment by adnanmunir83** [comment]
you are right. in Initial version of V10 this issue wasn't there.  i just test this case at the latest release of V10 and it's giving error.

**Comment by kennethsequeira** [comment]
Replicated.

![image](https://user-images.githubusercontent.com/33246109/42619177-e7d39312-85d4-11e8-95cb-1d55bb3ec027.png)

Steel wire - stock UOM Meters

PREC UOM - rolls (1 roll = 10m)

Validation while making return

**Comment by deepeshgarg007** [comment]
Unable to replicate on hotfix branch
Closing the issue, please reopen if issue still exists.

![purchase return](https://user-images.githubusercontent.com/42651287/49339031-382c2080-f651-11e8-8b52-43546e2b8c92.gif)
