### ISSUE TITLE
Billing Address cannot be changed

### ISSUE THREAD

**Issue by cyruschiu123** [frappe/erpnext#14882]
The Billing address in the delivery note has fixed and cannot be changed....how to change the billing address?

**Comment by merlinsquash** [comment]
You'll have to cancel the delivery note and amend to insert the desired billing address.

Also, this question will recieve faster answers on the ERPNext forum not here. !

**Comment by shreyashah115** [comment]
Closing this, hope its resolved else post it on discuss.erpnext.com
