### ISSUE TITLE
[HELP!] PoS customization -> Sales Person name for each line item

### ISSUE THREAD

**Issue by kmhassan** [frappe/erpnext#14894]
Hi - hope this finds you well.

I am desperately looking for a way to add name of Sales Person against each line item when a sales in done through POS screen. It's not possible to assign different log in ID for each Sales Person as it significantly increases sales completion time (plus long wait for the customer as the Sales Person logs into the system, plus at times a single invoice may have contribution from multiple sales people, plus usually the POS and cash in supervised by the Store Manager)

Sales Personnel in the shop floor are remunerated based on the number of items they sale, and currently it's a nightmare reconciling the numbers at the end of the month.

Is there a SUSTAINABLE way to do this so the customization survives subsequent bench updates? Will appreciate if you could provide step by step guidance for a novice.

Thanks in advance and looking forward.

**Comment by PawanMeh** [comment]
Please contact [service providers](https://erpnext.org/service-providers) for any customization related queries or ask on [discuss](discuss.erpnext.com)
