### ISSUE TITLE
pdf-reports-hyperlink

### ISSUE THREAD

**Issue by albertusgeyser** [frappe/erpnext#14898]
Good Day

Would it be possible to add Hyperlinks option in reports (Delivery Notes, Invoices . . . ) to enable for instance to open specific document (doctype item) by clicking hyperlink in pdf.

Would be nice for instance to send document in pdf format to customers or suppliers and for them to open document in erpnext to see more info about specific document.

https://discuss.erpnext.com/t/pdf-reports-hyperlink/38459

Thank You

Albertus Geyser

**Comment by kennethsequeira** [comment]
This is already possible:

![image](https://user-images.githubusercontent.com/33246109/42750976-e27235ba-8906-11e8-98ab-bd2690091958.png)

Just add the text accordingly in the doctype which will be reflected on print:

![image](https://user-images.githubusercontent.com/33246109/42751020-fbd6f0cc-8906-11e8-94bc-c2e2d4b7f93e.png)
