### ISSUE TITLE
Reserved Qty for Subcontracting not reducing after Purchase Receipt

### ISSUE THREAD

**Issue by djpalshikar** [frappe/erpnext#14897]
If  an Item has been added to Subcontractor's warehouse by either a Purchase Receipt or a Stock Entry for Transfer(without linking it to a purchase order) ; the Reserved Qty for Subcontracting for that item does not decrease even after Purchase Receipt.

Please see screenshots for confirmation:

![screenshot_2018-07-13 report stock entry](https://user-images.githubusercontent.com/23133635/42683753-d86cb0c0-86ab-11e8-95d3-02fa1b287e29.png)
Stock Entry: 00248 only transferred 100 nos, the other 400 were delivered to supplier via Purchase Receipt.

![screenshot_2018-07-13 diode-tvs-33v-smc - diode-tvs-33v-smc](https://user-images.githubusercontent.com/23133635/42683839-18861340-86ac-11e8-8190-9b5bc1a6290e.png)

 400 nos seen as Reserved Qty, where as Purchase Receipt for the item have been made.

After Purchase Receipt is made Reserved Qty should be updated accordingly.

**Comment by djpalshikar** [comment]
@rohitwaghchaure any update on this ?

**Comment by PawanMeh** [comment]
I think the process is to transfer the material to the supplier using the Transfer dialogue box always as it will be  linked to the PO in question

![po_subcontract](https://user-images.githubusercontent.com/20460498/50279642-4d39e980-0470-11e9-83b9-a783fb9dfb41.png)

After this when you create a Purchase receipt against the Subcontracted PO it should reduce the transferred material. If the transferred material is not linked to a PO, the system does not know against which PO it has to reduce the quantity.

**Comment by djpalshikar** [comment]
1. @PawanMeh if submission of Purchase Receipt is being allowed, it should be reducing stock at the supplier's warehouse.
                                               **Else**
2. There should be an error message stating that there is "Insufficient stock for Item #n at Supplier Warehouse transferred via Purchase Order xxx "

I feel **1** is a better option, it provides flexibility and is consistent  with previous versions of ERPNext

**Comment by PawanMeh** [comment]
If you use Make button from the sub contracted PO, then purchase receipt will have the PO linked when you are receiving the finished sub-contracted Items. In that case it should deduct the materials from the reserved warehouse. (If they were transferred using the above Transfer modal in the first place)

**Comment by djpalshikar** [comment]
I can live with the bug. If you would like to close it, please go ahead.

**Comment by PawanMeh** [comment]
I don't think it's a bug unless you can provide the exact replication steps after following above steps.

**Comment by djpalshikar** [comment]
The steps you mentioned will not re-produce it. Although I feel it does qualify as a bug as the system lets you do something that results in erroneous data, which in this case is the extra "Reserved Qty".

I think there are two possible solutions:

- Purchase Receipt should not be allowed as the not enough material has been transferred via the Purchase Order (this is as per the process you mentioned)
- If Purchase Receipt is allowed based on the stock available at Supplier warehouse, the reserved qty should be reduced as per what has been reduced from Supplier's warehouse. **(Preferred)**

**Comment by djpalshikar** [comment]
The steps to replicate:

1. Transfer Partial Material via the Purchase Order(make button)
2. Create a Stock Entry for Transfer, do not link it with Purchase Order, transfer material to Supplier;s Warehouse. Make sure adequate material is available at the Supplier's warehouse.
3. Create a Purchase Receipt, receive 100% qty. The Reserved Qty for the items transferred via separate stock entry will not reduce.

**Comment by PawanMeh** [comment]
For point no.2 mentioned, if you are transferring material for subcontract you need to select purpose of sub-contract in the Stock Entry and enter the PO. Otherwise system has no way to know that this material is for which PO. So it is probably a user entry error from your end. 

![sub_contract_stock_entry](https://user-images.githubusercontent.com/20460498/50372041-e2fa8380-05ec-11e9-8a38-bfeb8230e2fe.png)

**Comment by djpalshikar** [comment]
Can you not get the Purchase Order reference from the Purchase Receipt Item(While making the Purchase Receipt) ?

**The use case for Transferring Material directly:**
We often buy Material from "Vendor A" and ship it to "Vendor B" our subcontractor's warehouse directly. Hence material is some items are not transferred via the Purchase Order.

**Why I feel this is important to users:** 
if the above process is being followed by users(which is plausible), it will be very difficult to trace why Reserved Qty is building up, since the corresponding Purchase Orders will be completed.

Even if a subcontracted Purchase Order is closed manually the system reduces Reserved Qty.

**Comment by deepeshgarg007** [comment]
Closing this since we have a separate sub contracting flow now

**Comment by djpalshikar** [comment]
@deepeshgarg007 the separate flow that your are talking about is in V14 ? In V13 I did not notice  a different work flow.
