### ISSUE TITLE
Delete task linked to project 

### ISSUE THREAD

**Issue by sunguyentb** [frappe/erpnext#14907]
I get isssue, can not delete project  "Nhap"
![image](https://user-images.githubusercontent.com/21275955/42742898-3458437e-88e9-11e8-8bef-dd871b519b6b.png)

![image](https://user-images.githubusercontent.com/21275955/42742788-2367a510-88e8-11e8-8252-7ed21ec58635.png)

and simlar to detelet project "Nhap"

![image](https://user-images.githubusercontent.com/21275955/42742806-43fa9d14-88e8-11e8-9cc8-a00f663a8357.png)

Please help how can fix??

I get the newest project.py file updated 13-Jul-18 (Erpnext 10.1.42-0)

The before issue: https://discuss.erpnext.com/t/cant-delete-task-from-the-project/13284

**Comment by jaichavan** [comment]
Hello, @sunguyentb thanks for reaching out! Tried to replicate in the latest version [ ] but couldn't, it's working as expected - Deletion can be done from Project itself! Attaching GIF for your reference:

![delete-task-from-project](https://user-images.githubusercontent.com/40264279/51441540-b6737d80-1cf8-11e9-9674-bde460e63b3d.gif)

**Comment by 1kidvidiot** [comment]
The delete doesnt work. Still have same problem latest update. Cant delete task, cant delete project
