### ISSUE TITLE
Mandatory field to be displayed based on condition

### ISSUE THREAD

**Issue by bghayad** [frappe/erpnext#14903]
Hello;
Displaying the mandatory field currently is not related to display condition. It is important to change this and make mandatory field being displayed or hidden based on the condition.
Can we add this feature?
Regards
Bilal

**Comment by Zlash65** [comment]
You can do so using Custom Script.

Let's say you have a field 'field1' that needs to be mandatory based on a condition and there is field 'field2' that is the part of the condition. Let's assume the doctype is 'Sales Order'

```
frappe.ui.form.on('Sales Order', {
	onload: function(frm) {
		frm.set_df_property('field1', 'reqd', (field2 > 50) ? 1 : 0)
	}
});
```

The condition is short for -
```
if(field2>0) { return 1;} else { return 0;}
```

**Comment by kennethsequeira** [comment]
@bghayad any update on this?

**Comment by bghayad** [comment]
Hello @kennethsequeira 
Sorry for delaying in reply.
Using frm.set_df_property is helping but not too much. Why? Because: if the original document was having a mandatory field and I was need to hide the field or making it not mandatory using frm.set_df_property, then: when I need to save the document, it will popup a message that it is required to enter a value in the field.
But it is working in opposite way: if the field is not mandatory and I was need to set it mandatory using frm.set_df_property, then it is working fine.
Also, if the field is not mandatory and I need to use the frm.set_df_property to make the field hidden or to display the field if it is already hidden, then frm.set_df_property is working fine.
Lastly: If the field i mandatory and having default value, then I can use frm.set_df_property to hide it. But in this case, I have to use a default value for the mandatory field which will be a useless, specially if the field is link field, so in this case, I have to create a value in this link field to be used for default value and this is really not professional behavior !
Regards
Bilal

**Comment by agritheory** [comment]
You could use the depends on field in the doctype to show/ hide. or use set_df_property to show hide based on the same logic in zlash's example:
`frm.set_df_property('field1', 'hidden', (field2 > 50) ? 1 : 0)`
`frm.set_df_property('field1', 'reqd', (field2 > 50) ? 1 : 0)`

**Comment by bghayad** [comment]
@agritheory 
Are you sure and did you check if this is working fine with the field that is mandatory?
For me: I tried it and I faced what I mentioned above.
Regards
Bilal

**Comment by harshal2530** [comment]
I m facing the same issue   its there any update  


regards
Harshal Nirmal

**Comment by kennethsequeira** [comment]
This has been added in develop/v13:

![image](https://user-images.githubusercontent.com/33246109/88287755-61129500-cd10-11ea-8832-d337d1d50d58.png)
