### ISSUE TITLE
TDS Redesign

### ISSUE THREAD

**Issue by nabinhait** [frappe/erpnext#14915]
**Tax Withholding Category**
- [x] Threshold on single transaction
- [x] Threshold on Cumulative Invoiced Amount for the Fiscal Year
- [x] Remove "Book on Invoice"
- [x] Remove "Withhold Cumulative Tax Amount On First Invoice After Threshold"
- [x] Bootstrap all TDS sections (for India)

**Supplier**

- [x] Move all tax withholding fields from child table to parent

**Purchase Invoice**
- [x] Add a checkbox "Apply tax withholding amount"
- [x] If checked, calculate tax amount based on invoiced amount and tax deducted on all previous invoices for the FY.

**TDS Payable report**

**Comment by karannshah** [comment]
@nabinhait is this something you are looking at releasing in version 11? Are there any estimated timelines?

**Comment by karannshah** [comment]
@nabinhait  TDS calculations are incorrect for invoices crossing threshold amount. Please see the images I have added here. https://github.com/frappe/erpnext/issues/15438
