### ISSUE TITLE
Current GSTR1 CSV & Excel format is not compatible with GST Offline Tool 

### ISSUE THREAD

**Issue by PrakashH** [frappe/erpnext#14912]
Getting error 'Data Invalid'

![gstr-error](https://user-images.githubusercontent.com/11695402/42746703-d0d5f1da-88f6-11e8-996c-5602e34abbe0.PNG)

**Comment by bhanu1222** [comment]
Please check the spreadsheet.Either all rows have invalid data or the wrong section file is copied/uploaded
