### ISSUE TITLE
[bug] Timesheet - creation via webform doesn't work

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#14928]
Steps:

1. Created a webform for Timesheet
1. When fill form from website and Save, there is no message or response. Error message in the browser console as follows.

<img width="1314" alt="screen shot 2018-07-17 at 11 45 09 am" src="https://user-images.githubusercontent.com/910238/42799826-eaf2f0d4-89b6-11e8-9109-4ff718308424.png">

**Comment by deepeshgarg007** [comment]
Issue not replicated.
 Working fine for me.

![screen shot 2018-10-14 at 1 32 01 pm](https://user-images.githubusercontent.com/42651287/46914109-befc3f80-cfb6-11e8-8cc1-a3685944e0e8.png)
