### ISSUE TITLE
Issue in Sales Invoice for listing the stock qty by Warehouse and Batch wise pop up

### ISSUE THREAD

**Issue by AravindPranera** [frappe/erpnext#14927]
When I try to do Sales Invoice for the item which has a batch in beta.erpnext.com to check the improvement in listing the stock qty by Warehouse and Batch wise pop up in version 11, getting a error like below. Please kindly do needful.

![image](https://user-images.githubusercontent.com/28756911/42799632-2f0e1894-89b6-11e8-86db-d982129ce3b3.png)

**Comment by jaichavan** [comment]
Hello, @AravindPranera was able to successfully create a Sales Invoice for a batched Item. Attaching GIF for your reference:

![stock-batch-invoicing-on-beta](https://user-images.githubusercontent.com/40264279/51442651-06f0d800-1d05-11e9-8ff0-7ba8bd9198e7.gif)
