### ISSUE TITLE
[Feature Request] New Query Report: Sales Order Items not requested for Manufacturing 

### ISSUE THREAD

**Issue by djpalshikar** [frappe/erpnext#14953]
Our Sales Cycle is as follows:
Quotation - > Sales Order -> **Material Request For Manufacture** -> (Production Order) ... -> Sales Invoice

**The sales team is not able to easily track if there are Sales Orders for which no Material Request has been created. They have to go one by one to check this**

I propose a report with following columns(In this order):
- Row No.
- Sales Order ID(Only Submitted, Pending, Overdue SO should be shown)
- Sales Order Item Code
- Material Request ID **(Only shows if Sales Order Qty > Material Request Qty)**
- Sales Order Qty
- Material Request Qty **(Only shows if Sales Order Qty > Material Request Qty)**

Net a totals row for Qty items and the usual filters

**Comment by djpalshikar** [comment]
@Mangesh-Khairnar just following up for a tentative date.

**Comment by Mangesh-Khairnar** [comment]
It will be completed within next week, work on it is almost done.

**Comment by Mangesh-Khairnar** [comment]
PR for this query request feature. #15652

**Comment by Mangesh-Khairnar** [comment]
The pull request for this query report was closed given the existence of a report "Pending SO Items for Purchase Request". I have refactored the report "Pending SO Items for Purchase Request" to a script report at #16188. It has similar functionality as this issue request.
