### ISSUE TITLE
[update bug] item_code field cannot be set as unique

### ISSUE THREAD

**Issue by vladucoju** [frappe/erpnext#14958]
Hello,

i passed severall bugs trying to update to latest version. Now i have this error

frappe.exceptions.ValidationError: item_code field cannot be set as unique in tabItem, as there are non-unique existing values

In one database there is set item_code as unique. I can't remove this.

**Comment by kennethsequeira** [comment]
Specifying the ERPNext and Frappe versions will help to check

**Comment by vladucoju** [comment]
nstalled Apps

ERPNext: v11.x.x-develop (9f97c97) (develop)

Frappe Framework: v11.x.x-develop (cccfa66) (develop)

**Comment by joolsr** [comment]
There's been some commits relating to item groups in the last couple of days so please update again as these may have fixed your problem

**Comment by vladucoju** [comment]
I just updated it again but same error. Try to remo unique from database table but after i update it he recreate it again.

**Comment by vladucoju** [comment]
Hi,  this error is fixed but now i have new error
 internalerror-1054-u-unknown-column-department-in-field-list

**Comment by vladucoju** [comment]
Hi @kennethsequeira , update passes error with department that i mention in another topic. Now again i have same error
frappe.exceptions.ValidationError: item_code field cannot be set as unique in tabItem, as there are non-unique existing values

**Comment by vladucoju** [comment]
I still have this error after latest update. It is stuck on one database. There is unique id item_code. I delete him from database but update is populating him again. Any other solution? Could i delete that database, update system, restore database and patch?

**Comment by vladucoju** [comment]
Hello, I still can't update system. One database produce this problem. That database has more tables than other databases. I try to delete database, update system (succesuffuly), restore backup, and when try to migrate give me same error. @kennethsequeira , could you help me with this? Otherwise i must export/import data to new database. I am on developer branch.

**Comment by nabinhait** [comment]
@vladucoju You have to remove `unique` property directly from database.
