### ISSUE TITLE
[V11] Timesheets - To time is not working

### ISSUE THREAD

**Issue by UnReal933** [frappe/erpnext#14951]
There is a problem with "To time" in timesheets:

Hour can't be selected:

![timesheet-bug](https://user-images.githubusercontent.com/11376452/42872674-d1133c92-8a7d-11e8-9d59-4dccba115ead.gif)

Like you see, changing the starting date change the hour and the finishing date, which is not correct.

**Comment by Zlash65** [comment]
This was fixed a while back, what version are you using ?

Was this on beta.erpnext.com ?

**Comment by UnReal933** [comment]
I was using Staging branch (but I can't update anymore ?)

Yes it was on beta.erpnext.com wednesday, but not anymore.

**Comment by Zlash65** [comment]
Well its been fixed and I noticed it happening on beta.erpnext.com as well, updating it to latest fixed the issue.
