### ISSUE TITLE
Purchase Order email has no letterhead

### ISSUE THREAD

**Issue by Arlus** [frappe/erpnext#14961]
Ever since upgrading from ERPNext v8 to ERPNext v10, the PDFs in purchase order emails seems to lack the letterhead. I have tried the commonly suggested fixes like adding the host_name to site_config.json all to no avail.
What could be causing this?

**Comment by joolsr** [comment]
You would be better to post this in the forum's with full version number and server details.

Adding the hostname is most likely related . Are you sure it is in the correct format ?

**Comment by Arlus** [comment]
The host_name is set okay. In the PO email, the pdf attached has no letterhead. I realized I could see the PO with letterhead when I click the "view in browser" link in the email. However, a permission issue is raised when I click on "view in browser" from a browser not logged in to ERPNext. This means that the stakeholders we are emailing the POs to will be receiving the PO with no letterhead.

**Comment by Arlus** [comment]
I posted the issue on the forum https://discuss.erpnext.com/t/letterhead-issue-in-purchase-order-email/38967
