### ISSUE TITLE
ERPNext TypeError: the JSON object must be str, not 'bytes'

### ISSUE THREAD

**Issue by sagartiparadi** [frappe/erpnext#14964]
Created one whitlist service to accept data in post request. So I am getting error as below.

Please help.

Server Error

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 59, in application
    init_request(request)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 119, in init_request
    make_form_dict(request)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 127, in make_form_dict
    args = json.loads(request.data)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

**Comment by kennethsequeira** [comment]
Please post this technical query on the forums:

ERPNext - https://discuss.erpnext.com

Frappe - https://discuss.frappe.io

The thread can be reopened again if it's validated as a bug which needs fixing. Ensure to post your ERPNext and Frappe versions so members can guide accordingly.

**Comment by barankaraboga** [comment]
I had exactly same error. I opened topic in erpnext forum. I hope it will help you : [https://discuss.erpnext.com/t/bug-frappe-api-encoding-case-typeerror-the-json-object-must-be-str/40359]

**Comment by taj-meltedmoon** [comment]
the link is down. can i know how to solve this? i m having the same issue
