### ISSUE TITLE
Chat close button doesn't work in mobile view [V11]

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#14974]
Hi,

When chat is opened in mobile view, the 'Close' button doesn't work; clicking on it doesn't exit the chat screen. Also, when chatting with an individual user, the 'Back' button on the mobile phone (Android) doesn't return to the previous screen where all users are listed

Please look into this

Thanks

**Comment by kennethsequeira** [comment]
Duplicate: https://github.com/frappe/frappe/issues/5683
