### ISSUE TITLE
Purchasing account entry inconsistencies and proposed solutions

### ISSUE THREAD

**Issue by SaiFi0102** [frappe/erpnext#14980]
There are multiple problems I've identified in ERPNext regarding the GL Entries for the Buying module and I've been working on them. I'm posting this issue to discuss my proposed changes. Let me know if it's a good idea or a bad idea.

- Problem 1: Expenses Included in Valuation is recorded upon submission of Purchase Receipt. If there are Purchase Receipts which have not yet been billed with Purchase Invoices then the accounting balances show a profit (or negative expense). This is because the Stock Expenses account group has not yet been offset by debiting the Taxes and Charges account heads yet.
- Solution 1: Do not credit Expenses Included in Valuation during Purchase Receipt. Instead credit the whole amount of stock's value to Stock Received But Not Billed. THEN upon submission of Purchase Invoice debit Stock Received But Not Billed and credit the Creditors account and Expenses Included in Valuation. The Taxes and Charges entries can be made as the usual.
![screenshot from 2018-07-21 23-57-22](https://user-images.githubusercontent.com/328330/43039562-730a9bb2-8d49-11e8-84af-980b1dde8735.png)

- Problem 2: Users can make Purchase Receipts with a different Exchange Rate and Purchase Invoice with another Exchange Rate. This makes it possible that the Stock account may get debited with a different value and Creditors account may get credited with another value leaving the Stock Received But Not Billed with the amount difference between them.
- Solution 2: Keep allowing the user to use a different exchange rate in the Purchase Invoice. However ERPNext should check if there is a difference between the Grand Totals and make a readjustment entry similar to the LandedCostVoucher.update_landed_cost() function to readjust the account balances and stock valuation.
![screenshot from 2018-07-21 23-29-07](https://user-images.githubusercontent.com/328330/43039568-8d1e0304-8d49-11e8-9a07-7d08aca42287.png)

- Problem 3: Taxes and Charges considered for Valuation-only during Purchase Invoice do not make the complete and necessary GL entries. The user is expected to make a Journal Entry to bill for or to pay for the Valuation-only charges manually. The difference can show up as profit in Stock Expenses if the user forgets to make the JV because the Expenses Included in Valuation account get credited but debit tax/credit party entry is not made. Also it becomes difficult to find which tax entry has not yet been billed.
- Solution 3: Add an additional "payable_to" field to Purchase Taxes and Charges which is only used for Valuation-only charges. And upon submission of Purchase Invoice the necessary Journal Entries should be made automatically.

- Problem 4 (solved): The Landed Cost Voucher doesn't bill the party to whom the taxes and charges are payable to.
- Solution 4: I've already made a draft modification to ERPNext to make LCV a payable document, however, I'm still adding more functionality. https://github.com/SaiFi0102/erpnext/tree/Payable-LCV

**Comment by harshit-30** [comment]
Please create another issue if it is replicable after v13.10.

**Comment by harshit-30** [comment]
@SaiFi0102 hey, this is quite an old issue and I am marking this as closed. If you feel the need to raise it - please let me know here and I'll make sure to address it.

Thanks for being a valuable member of the ERPNext Community. 😊

**Comment by nathanso** [comment]
Hi @harshit-30 , I have run across Problem 1 mentioned by Saifi. To elaborate further, our company are invoiced based on the number of receipts we received at the end of the month. Each Receipt have a different Tax and charges (based on qty received which varies per receipt), and when I consolidate them into 1 purchase invoice, it only fetches the Tax and Charges  from the first Receipt selected and not the rest.
