### ISSUE TITLE
Text editor label not appear in print format

### ISSUE THREAD

**Issue by dufani1** [frappe/erpnext#14989]
When try to make text editor appearing in print format, I noted that the label of text editor not appearing in print format.

**Comment by dufani1** [comment]
Hi @kennethsequeira  my version ERPNext: v10.1.43 and Frappe Framework: v10.1.42
 
![untitled](https://user-images.githubusercontent.com/23026263/43354783-9f0fd4ee-9252-11e8-9c96-7071b0fe5084.png)

**Comment by kennethsequeira** [comment]
@dufani1 can you post this first on the forum? https://discuss.erpnext.com

You can expect better response from there. GitHub is used by us to identify bugs and feature requests.

I'm closing this issue at the moment. If this is identified as a issue, will reopen the thread.

**Comment by dufani1** [comment]
@kennethsequeira I already posted this topic in Forum... and I made the issue here to draw attention of problem and contribute to make the software better.
https://discuss.erpnext.com/t/text-editor-label-not-appear-in-print-format/38801
