### ISSUE TITLE
Production order does not autopopulate with items from Sales order

### ISSUE THREAD

**Issue by jasonbrowne** [frappe/erpnext#15006]
Problem: When creating a new production order off of a sales order, material request, etc the Production order does not auto-populate the production order with items from the sales order.

Solution:

1) Offer a chance to get items from the sales order. At which point you could select the item that was your BOM, or get ITEMs from the material request that are BOMs.

![productionorder](https://user-images.githubusercontent.com/19347811/43230691-28414996-901e-11e8-9b8a-43a57ab8cc83.png)

**Comment by kennethsequeira** [comment]
What flow are you following? And which version of ERPNext are you on?

The production order auto-populates when you create it from the Sales Order using the **Make** button.

**Comment by jasonbrowne** [comment]
Tested in 11 beta online box in V11. Worth a play on beta.erpnext.com and it works so this can be closed

**Comment by kennethsequeira** [comment]
@jasonbrowne thanks for the update.
