### ISSUE TITLE
Running into SyntaxError: Unexpected token (80:2) while upgrading ERPNext

### ISSUE THREAD

**Issue by jasonbrowne** [frappe/erpnext#15007]
Installed Apps
ERPNext: v10.1.43

Frappe Framework: v10.1.42

Keyfetcher: v0.0.1

Ktp Kayako Ticket Puller: v0.0.1

Salesforce Catcher: v0.0.1

![syntexerror](https://user-images.githubusercontent.com/19347811/43232353-42afaf96-9025-11e8-9e92-76e920e17e25.png)

**Comment by system19** [comment]
Can confirm same issue here with ERPNext: v10.1.43, Frappe Framework: v10.1.42

**Comment by Zlash65** [comment]
This issue has been fixed. Pull the latest develop and run `bench build`.

Closing the issue. if error still persists reopen the issue.
