### ISSUE TITLE
I lost the encryption of previous database 

### ISSUE THREAD

**Issue by ziagithub2018** [frappe/erpnext#15008]
hello all
when I removed the previous erpnext I didn’t know anything about Encryption key.
now when I create new user I get the following error.
![11](https://user-images.githubusercontent.com/36146142/43241532-07630d0c-90b1-11e8-8c2e-389d16cdba76.PNG)
please guide me, what to do,
I can do anything manually if required to be done.
just need to know.

**Comment by kennethsequeira** [comment]
@ziagithub2018 please post this on the forum: https://discuss.erpnext.com. In case it is a bug or a problem with the code, issue will be re-opened.
