### ISSUE TITLE
Unable to select filter in General Ledger

### ISSUE THREAD

**Issue by amitsaxena01** [frappe/erpnext#15010]
In General Ledger, if we select filter specially account following error is thrown:
VM294:42 Uncaught TypeError: frappe.query_report.get_filter_value is not a function
    at get_query (<anonymous>:42:39)
    at o.set_custom_query (link.js:289)
    at HTMLInputElement.<anonymous> (link.js:150)
    at utils.js:633

ERPNext: v11.x.x-develop (7395421) (develop)

Frappe Framework: v11.x.x-develop (d46fd09) (develop)

**Comment by merlinsquash** [comment]
I think this is possibly related to deprecation of frappe.query_filters_by_name

**Comment by Zlash65** [comment]
Fixed now. Please reopen the issue if it still persist
