### ISSUE TITLE
Incorrect direction in the Support Module Documentation

### ISSUE THREAD

**Issue by FinForceConsulting** [frappe/erpnext#15020]
I found the direction of attachment of file is mentioned on the "Right" side, but in the current version it is on the left side of the user's screen

https://erpnext.org/docs/user/manual/en/support/issue
![image](https://user-images.githubusercontent.com/31281816/43283587-f0a53ae6-9136-11e8-8928-c159e882256e.png)

![image](https://user-images.githubusercontent.com/31281816/43283689-2ed8ff6e-9137-11e8-9f44-53790b64c636.png)

**Comment by kennethsequeira** [comment]
Merged the change. The only thing left is to deploy it.
