### ISSUE TITLE
Subscription - Replace Subscriber with Customer master - Deprecate Subscriber master

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#15028]
Which ever fields are needed in the Subscription master, if at all needed in feature, add in the Customer master itself.

In in the Subscription Plan Details, fetch values from Subscription Plan and show more columns.

<img width="1230" alt="screen shot 2018-07-27 at 6 30 33 pm" src="https://user-images.githubusercontent.com/910238/43322026-2a0a0930-91cb-11e8-8079-05a1892bdb09.png">

**Comment by tundebabzy** [comment]
Actually we need the Subscriber doctype to capture things that are subscription related as time goes on. For example, users should be able to use coupons in subscriptions. Coupons can added on subscription basis or on subscriber basis. If the user chooses to add a coupon on subscriber basis, Customer doctype doesn't seem the right place to add it. Another potential addition is account balance. Users should be able to view a Subscriber's balance on account without going through the subscriptions. Customer doctype will also not be a good place for it.

Based on that, even though it sounds counter intuitive, Subscriber is essentially different from a customer and it will not be a good idea to deprecate Subscriber for Customer.

**Comment by Olawale1** [comment]
> If the user chooses to add a coupon on subscriber basis, Customer doctype doesn't seem the right place to add it

hi @tundebabzy , why do you say so? I don't see any problem with issuing a coupon to a Customer

Cheers

**Comment by umairsy** [comment]
Yes, coupons etc. will be issued to Customer only. Let's deprecate Subscriber and use Customer only.

**Comment by tundebabzy** [comment]
At this point I think I need to reconsider my approach. Perhaps we should
remove the `Subscriber` doctype and link `Subscriptions` directly to
`Customer`.

Added to my to-do list as well

**Comment by Olawale1** [comment]
Hi @deepeshgarg007

What's the status of this? Was it done or was it discarded?

Thanks
