### ISSUE TITLE
Write Permission Issue

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#15053]
Hi,

We have a scenario where we want the Accounts User to edit only the accounts related fields in an item form. We have set these fields to permission level 2 and given the Accounts User role Write Permission on level 2

Issue:

The Accounts User cannot edit those fields unless we also give him Write Permission on level 0!

Is this a bug?

Kind regards,

**Comment by jaichavan** [comment]
Hello, @Olawale1 
No, it's not a bug, that's how the system is supposed to work.

**Comment by Olawale1** [comment]
In addition to the original issue posted, we also discovered that if there are fields on permission level 1 which are mandatory, then the Accounts User cannot save any changes to the Employee form unless he/she is given Read permission on level 1!

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.
