### ISSUE TITLE
Earned Leave allocation 

### ISSUE THREAD

**Issue by amet123** [frappe/erpnext#15063]
How we applicable earned leave per month 1.5 which is after 20 days work employee earned 1 leave and further 10 days working he earned .5 leave.

**Comment by kennethsequeira** [comment]
Please post the functional issues on the forum: https://discuss.erpnext.com.

GitHub is primarily used for tracking bugs and feature requests.

**Comment by amet123** [comment]
@kennethsequeira now i find bug check
https://github.com/frappe/hrms/issues/186
