### ISSUE TITLE
Submit all production orders at once with common WIP warehouse

### ISSUE THREAD

**Issue by satishguptajaipur** [frappe/erpnext#1506]
When a number of production orders are created using Production Planning Tool, each production order has to be submitted manually by mentioning WIP warehouse in each order. Ideally all production orders with common warehouse should get submitted automatically by mentioning the WIP warehouse only once.

**Comment by Arundhatii** [comment]
Closing the issue for now as no further discussion or similar requirement is raised. Please feel free to reopen if it is still relevant.
