### ISSUE TITLE
Education Module not showing the Student form etc

### ISSUE THREAD

**Issue by emlagus** [frappe/erpnext#15069]
Hi,

Education module not showing the student, course, etc forms
Appreciate your reply

![education_module](https://user-images.githubusercontent.com/28524844/43519737-a48988c8-95a1-11e8-99f4-5b42e9f76e58.jpg)

**Comment by Zlash65** [comment]
Check in `Role` DocType wether roles related to education has been enabled. If they are enabled, check in your user settings (in `User` DocType for your own user) wether this roles are enabled for you.

**Comment by emlagus** [comment]
Hello Sir,

I logged in using Administrator, I presumed administrator have access to every thing.

Grateful to you if you could share with step by step or image screenshot regarding to your recommendation.

Ed

**Comment by kennethsequeira** [comment]
@emlagus review your permissions once:

https://erpnext.org/docs/user/manual/en/setting-up/users-and-permissions/role-based-permissions

Please move this thread to the community forum: https://discuss.erpnext.com

In case this is confirmed as a bug on our end, the issue can be reopened.
