### ISSUE TITLE
[REPORTS] General ledger print without party option

### ISSUE THREAD

**Issue by vladucoju** [frappe/erpnext#15067]
Hello,

i would suggest one option in general ledger report.

I use allocate Payment Amount in payment entry. In General ledger print  for customer party column populates that entry with linked invoices. This is ok, but many customers don't wan't to see that because they must print lot of pages. That look like this

![untitled](https://user-images.githubusercontent.com/9590909/43515462-dcae1490-9582-11e8-81d2-b3300f678b8c.png)

Some opion with check will be good solution to have option to print without party column

![untitled2](https://user-images.githubusercontent.com/9590909/43515555-06835a46-9583-11e8-98d2-128a92e00b99.png)

This will save a lot of space on paper.

**Comment by harshit-30** [comment]
@vladucoju we have the option to pick columns as desired. 🙂  
![image](https://user-images.githubusercontent.com/46772424/144132828-4e085994-8c0f-45ed-8b1e-161fbcbf8358.png)

Marking this as closed for now, do comment if this is not what you expected.

**Comment by vladucoju** [comment]
Hi @harshit-30, i leave this project 3 years ago. Concept was excelent but you didn't finished core problems, and polish the ERPNEXT. Hope today is much better support for clients. I choose www.datalab.eu as my new project, and now i am working with that in my country successfully www.datalab.me
