### ISSUE TITLE
Stock taxation by date/ history

### ISSUE THREAD

**Issue by test2a** [frappe/erpnext#15073]
This is primarily an India specific issue with regards to GST but others might be having this issue.
So, the basic idea is that the item remains the same. You buy it at your cost, add profit and add tax and sell it. Usually the purchase tax and sale tax rate is same and it all works.
But, because the government now decides to change tax rate on the item, its final value changes and so does your tax rate but your cost price and profit should remain the same.
The issue at hand is right now on beta.erpnext.com at least, I havebt found a way to set tax rate of an item by date. So, say from 5 Aug 2018, this item currently in 12% tax rate should become 18%.
Right Now I have to either change the entire tax rate for the item which jeopardizes the existing entries, costing or second,create a new item with new rate and then do stock transfer.

**Comment by kennethsequeira** [comment]
I'm not sure that after submitting the invoices there is an impact of the change of tax on the accounting. Is it possible for you to check this on a local installation and verify?

What accounting entries you feel are impacted by the current method? Where do changes need to be made?

**Comment by test2a** [comment]
@kennethsequeira thanks for answering back. the issue we have at hand is lets take the recent GST council decision that changed tax rates of a hundred items. they said, from 27 july, the item previously in say 28% category would from that day forward be charged at 18%. 
the issue is if we simply shift the tax rate on the date, how would we be knowing what was the previous tax rate or the switch unless there is some sort of record. Tally software uses a "tax history" where we can set the date of the change of tax rate and the software would pick up that new rate or change automatically. 
the issue i am having and thats preventing me from using it in production on basically 50+ clients i work on is that i have found erpnext does not work well with multiple items having multiple tax rates set. see #15019 what i think it is doing and i may be wrong here but erpnext treats sales/purchase tax as how we calculate tax on salary, because it uses

- Actual

- on net total

- on previous row amount

- on previous row total

when instead if we selected " in state gst" for example, it should calculate taxes based on item tax rate first individually and then total of similar taxes. say 3 items of 12% should get clubbed and so on. Hope i made sense, i'll be happy to clarify any point :-)

**Comment by kennethsequeira** [comment]
@test2a 

I'd suggest you also post this issue on the forum (maybe Monday?) and ask them to upvote this feature! 

I'm sure there are tonnes of people who would have to like this in the system and have related suggestions.

**Comment by test2a** [comment]
@kennethsequeira  done. check this
https://discuss.erpnext.com/t/issue-stock-taxation-by-date-history/39375

**Comment by test2a** [comment]
any updates on this?

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.
