### ISSUE TITLE
Manual sync is removed and auto sync is not working in ShopifyERPNext 

### ISSUE THREAD

**Issue by ghost** [frappe/erpnext#15075]
Hi everybody

In new ERPnext update manual sync is deleted from shopify setting, I have saved the configuration info from shopify into shopify setting and waiting for sync. there is no way to know whether its working or not, its more than 3 hours I’m waiting.

please let me know if I'm missing anything

**Comment by federicocalvo** [comment]
Hi! The manual sync button and the Reset last sync date button are not see any more.

And the sync not found.

**Comment by ankush** [comment]
This was removed from core. I'll be adding "force/manual sync" on the app soon. 
https://github.com/frappe/ecommerce_integrations
