### ISSUE TITLE
Report "Total By" field

### ISSUE THREAD

**Issue by heatherpotter** [frappe/erpnext#15088]
I'm using ERPNext Cloud and the reports are very limiting to our business. It would be nice to have a "Total By" field where you can select a field to total subsections by. For instance, for A/P, it would be nice to total by "Supplier" and have it subtotal under each supplier. Or, total by "date" and it would total everything by date. For A/R, total by "Customer" would be a good thing. It's basically the same as sorting but then it also totals. 

![ap total by](https://user-images.githubusercontent.com/8241286/43689462-b849a740-98c0-11e8-9525-2f6b78d39587.png)

**Comment by heatherpotter** [comment]
I'm willing to pay for this if I can get it into the application as well. Let me know.

**Comment by lxnow** [comment]
+1 on this request. Also the ability to sub-total other reports, e.g. subtotal by product for sales, or subtotal sales by customer

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.
