### ISSUE TITLE
AR - AP Report

### ISSUE THREAD

**Issue by MANOJMAINKAR** [frappe/erpnext#15083]
Hi ,

We need to get project/cost centre wise outstanding/payable report from system.

It will be better if you add project /cost centre fields in AR/AP report to get project wise receivable / payable amount.

**Comment by MANOJMAINKAR** [comment]
Any one is in a position to give the solution

**Comment by bobzz-zone** [comment]
Hi, maybe you can try to use cost centor on your posting and get the gl for the csot center....

i never tried that also, but if that wont do the only solustion is develop it to your needs...

Thanks

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.
