### ISSUE TITLE
Warehouse Capacity Limit

### ISSUE THREAD

**Issue by Mohd200** [frappe/erpnext#15096]
Good Day Everyone.

Does ERPNext has the feature of a Limited Warehouse Capacity?
I wish to activate this feature, where it would keep track of the vacancy of the Warehouse.

Case Scenario:
I Bought a shipment of crates, and I want to find out which of my warehouses has the capacity to store my shipment before sending it to the Warehouse.

Q: If one the warehouses does not have enough vacancy, Could I divide the quantity of the procured Item between more than 1 Warehouse?

Q: If the feature works, Would it alert me like the Re-order Level, that the warehouse has reached its capacity?

Thank You

**Comment by Mohd200** [comment]
Any Updates??

**Comment by yadavyk** [comment]
Please refer : [Putaway Rule](https://docs.erpnext.com/docs/v13/user/manual/en/stock/putaway-rule)
