### ISSUE TITLE
Landed Cost Voucher  - Purchase Invoice does not pull PINVs

### ISSUE THREAD

**Issue by parsimonyERP** [frappe/erpnext#15098]
When entering a new Landed Cost Voucher, the expected action is that after selecting "Receipt Document Type" and choosing Purchase Invoice, then moving to the next field "Receipt Document" there would be a list of PINVs to choose from.  However, no PINVs are available and one is required.

Doing the same thing but selecting "Purchase Receipt" in the Receipt Document Type DOES retrieve a list of PRECs to choose from.
<img width="956" alt="lcv-pinv error" src="https://user-images.githubusercontent.com/38265755/43751523-14a97122-99b2-11e8-9b85-6ee20c361e45.png">

**Comment by kennethsequeira** [comment]
Working as intended 

![image](https://user-images.githubusercontent.com/33246109/43761615-3d2f0c7e-9a43-11e8-8af4-a6df38202a70.png)

Can you 
1. review permissions
2. state the frappe and erpnext IDs
