### ISSUE TITLE
Fee module not showing the paid amount

### ISSUE THREAD

**Issue by rkr00t** [frappe/erpnext#15129]
In Education, Fee module not showing the paid amount after making payment. It only shows the Total amount and the outstanding amount.
![image](https://user-images.githubusercontent.com/9102676/43998211-de952e7c-9e0d-11e8-852a-7fcf013066e2.png)

**Comment by scmmishra** [comment]
Check fees.js and fees.py

A similar function is required
```
calculate_total_amount: function(frm) {
		var grand_total = 0;
		for(var i=0;i<frm.doc.components.length;i++) {
			grand_total += frm.doc.components[i].amount;
		}
		frm.set_value("grand_total", grand_total);
	}
```

**Comment by crescent28** [comment]
![fees payment](https://user-images.githubusercontent.com/41110073/47899911-0b91b700-dea1-11e8-9630-348a2cc02867.png)
