### ISSUE TITLE
Show record summary to confirm submission / cancellation

### ISSUE THREAD

**Issue by anandpdoshi** [frappe/erpnext#1512]
For Eg.
When submitting Sales Invoice, show that the Grand Total is Rs. X, Paid amount is Rs. Y, has 5 different items with a total quantity of 103 etc. - a summary of derived / calculated values. It could lead to prevention of mistakes or earlier catching of bugs.

**Comment by sbkolate** [comment]
(+1) 

Instead of "Permanently Submit SO-00##?"

It will help if you add following info or write article for  "How to do this with custom script?":
Customer name:
Grand Total
Paid Amount
Total Item Qty
Reserved Warehouse
Current Stock In reserved Warehouse

**Comment by joezsweet** [comment]
@sbkolate @tardi Is this still needed? Closing now, please reopen with more details and mockup.
