### ISSUE TITLE
Does anyone connected and sync successfully ERPNext v11.xx with Shopify using WEBHOOKS?

### ISSUE THREAD

**Issue by ghost** [frappe/erpnext#15125]
Hllow @everyone 
When ERPNext v11.xx came and Shopify introduced Webhooks, does anyone connected these two successfully to sync data?

**Comment by generare** [comment]
where can you get the version 11? Trying to just search for that...

**Comment by ziagithub2018** [comment]
If you install a new erpnext, that will be in v11.xx in branch develop.  branch master is in v10.1.45 which way of connecting to shopify is changed in this version as well.

I'm struggling since 3 weeks ago with this problem.

**Comment by federicocalvo** [comment]
Hi, the same case here.
