### ISSUE TITLE
AttributeError: 'Meta' object has no attribute 'permissions'

### ISSUE THREAD

**Issue by ziagithub2018** [frappe/erpnext#15130]
Hello 
When I create item variant I get the following error
could anyone please help?
branch develop and master has both this bug
```
Traceback (most recent call last):
  File "/opt/bench/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.handler.handle()
  File "/opt/bench/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/opt/bench/frappe-bench/apps/frappe/frappe/handler.py", line 56, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/opt/bench/frappe-bench/apps/frappe/frappe/__init__.py", line 1007, in call
    return fn(*args, **newargs)
  File "/opt/bench/frappe-bench/apps/frappe/frappe/client.py", line 35, in get_list
    limit_start=limit_start, limit_page_length=limit_page_length, ignore_permissions=False)
  File "/opt/bench/frappe-bench/apps/frappe/frappe/__init__.py", line 1235, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(None, *args, **kwargs)
  File "/opt/bench/frappe-bench/apps/frappe/frappe/model/db_query.py", line 87, in execute
    result = self.build_and_run()
  File "/opt/bench/frappe-bench/apps/frappe/frappe/model/db_query.py", line 99, in build_and_run
    args = self.prepare_args()
  File "/opt/bench/frappe-bench/apps/frappe/frappe/model/db_query.py", line 118, in prepare_args
    self.build_conditions()
  File "/opt/bench/frappe-bench/apps/frappe/frappe/model/db_query.py", line 292, in build_conditions
    match_conditions = self.build_match_conditions()
  File "/opt/bench/frappe-bench/apps/frappe/frappe/model/db_query.py", line 406, in build_match_conditions
    role_permissions = frappe.permissions.get_role_permissions(meta, user=self.user)
  File "/opt/bench/frappe-bench/apps/frappe/frappe/permissions.py", line 164, in get_role_permissions
    applicable_permissions = list(filter(is_perm_applicable, doctype_meta.permissions))
AttributeError: 'Meta' object has no attribute 'permissions'
```

**Comment by saeedmurrad** [comment]
Hello, I am facing same issue please help us we will be thankful to all community..

**Comment by jaqobk** [comment]
facing the same issue on my website for products displayed there.....

**

> Traceback (most recent call last):
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 45, in render
>     data = render_page_by_language(path)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 139, in render_page_by_language
>     return render_page(path)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 155, in render_page
>     return build(path)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 162, in build
>     return build_page(path)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 187, in build_page
>     html = frappe.get_template(context.template).render(context)
>   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
>     return self.environment.handle_exception(exc_info, True)
>   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "/home/frappe/frappe-bench/apps/erpnext/erpnext/./templates/generators/item.html", line 1, in top-level template code
>     {% extends "templates/web.html" %}
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/./templates/web.html", line 6, in top-level template code
>     {%- if page_or_generator=="Generator" %}source-type="Generator" data-doctype="{{ doctype }}"{% endif %}
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/./templates/base.html", line 37, in top-level template code
>     {% block body %}
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/./templates/base.html", line 63, in block "body"
>     {% block content %}{% endblock %}
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/./templates/web.html", line 49, in block "content"
>     {%- block page_content -%}{%- endblock -%}
>   File "/home/frappe/frappe-bench/apps/erpnext/erpnext/./templates/generators/item.html", line 16, in block "page_content"
>     {% set slideshow_items = frappe.get_list(doctype="Website Slideshow Item",  fields=["image"], filters={ "parent": doc.slideshow }) %}
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1235, in get_list
>     return frappe.model.db_query.DatabaseQuery(doctype).execute(None, *args, **kwargs)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/db_query.py", line 87, in execute
>     result = self.build_and_run()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/db_query.py", line 99, in build_and_run
>     args = self.prepare_args()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/db_query.py", line 118, in prepare_args
>     self.build_conditions()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/db_query.py", line 292, in build_conditions
>     match_conditions = self.build_match_conditions()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/db_query.py", line 438, in build_match_conditions
>     role_permissions = frappe.permissions.get_role_permissions(meta, user=self.user)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/permissions.py", line 164, in get_role_permissions
>     applicable_permissions = list(filter(is_perm_applicable, doctype_meta.permissions))
> AttributeError: 'Meta' object has no attribute 'permissions'

**

kindly help

**Comment by tsuga** [comment]
Is this problem solved?

**Comment by SettupillaiPrabhakaran** [comment]
I have the same issue please check that

**Comment by nash22t** [comment]
I have the same issue please check that

**Comment by amecreate** [comment]
Got the same error message in desk when:
1. Create child table with permission level
2. Add permission rules in the parent doctype
3. Try to access the child table (frappe.db.get_list) with an account that does not have sufficient permission

erpnext 13.42.0
frappe 13.44.0

**Comment by lxnow** [comment]
What do you mean add permission rules in parent doctype?

**Comment by barathprathosh** [comment]
I have the same issue, while open Account Receivable report. Any solution.
