### ISSUE TITLE
Proposal: Rename the "Accounts" module to "Accounting"

### ISSUE THREAD

**Issue by williamjmorenor** [frappe/erpnext#15155]
Hello

I want to propose to remane the "Accounts" module to "Accounting", this way we can have a uniform way to name modules like "Selling", "Buying", "Manufacturing".

This may looks trivial, but in spanich the name of the module follow the same name convention of the Accounts Tree that it is not intuitive.

Regards
Willliam Moreno Reyes

**Comment by kennethsequeira** [comment]
@williamjmorenor if this is simply a translation-related problem, you can update the same on the portal as well: https://translate.erpnext.com.

Would also suggest posting this on the forum to gather consensus: https://discuss.erpnext.com
