### ISSUE TITLE
[v11] Timesheet Timer Not Working

### ISSUE THREAD

**Issue by OneiricIT** [frappe/erpnext#15162]
Test on latest develop stages and also on beta.erpnext.com - timer does not work in timesheets as below

![2018-08-17_14-34-15](https://user-images.githubusercontent.com/22227933/44247895-e048e580-a22a-11e8-8382-51c0d0768f3c.gif)
.

**Comment by incognitozen** [comment]
+1

**Comment by benjizhai** [comment]
+1. It used to work but no longer after bench update

**Comment by OneiricIT** [comment]
@benjizhai what version had you been on prior to update which worked?

**Comment by benjizhai** [comment]
I don't remember the exact version as it was on an old server, but the dev branch was less than 2 months old.

**Comment by jaichavan** [comment]
Hello, thanks for reporting the issue. We shall look forward to resolving it as early as possible. We thank you for your patience and cooperation.

**Comment by shreyashah115** [comment]
Sorry about the issue! It has been fixed here - #16110

**Comment by rushikesherp** [comment]
This has been fixed by @shreyashah115. It has also been merged. 
https://github.com/frappe/erpnext/pull/16110#event-1989430178
