### ISSUE TITLE
Purchase Invoice - Fetch item via Barcode 

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#15164]
In the Purchase Invoice, if field "Update Stock" is checked, then we can provide "Barcode" field for easy fetching of items.

**Comment by olamide2** [comment]
Same for Purchase order and Purchase Receipt

**Comment by flexy2ky** [comment]
Has this feature been included? I can query items using barcode in Sales invoice but it's not possible in Purchase invoice even though i added the field using customize form.

**Comment by kennethsequeira** [comment]
@flexy2ky 

Closing the issue as the field has been added in v11

![image](https://user-images.githubusercontent.com/33246109/54288335-50ef8f00-45cd-11e9-9dcd-e2865c46aae8.png)
