### ISSUE TITLE
Kanban doesn't save filters.

### ISSUE THREAD

**Issue by woohoou** [frappe/erpnext#15160]
The kanban is not capable to auto-save filters, and when I open the Inspector I got this error.

> VM1091:1058 Uncaught TypeError: Cannot read property 'get_filters' of undefined
>     at <anonymous>:1058:60

The bug is presented at the version:
**ERPNext: v10.1.48 (master)
Frappe Framework: v10.1.45 (master)**

**Comment by jaichavan** [comment]
Hello, @woohoou 
There seems to be no issue while saving Kanban filters anymore. [ v11.0.3-beta.34 () (staging) ]
Can you please check and revert is issue persists?

**Comment by ankush** [comment]
<img width="1044" alt="Screenshot 2022-04-18 at 7 04 23 PM" src="https://user-images.githubusercontent.com/9079960/163815825-ffd87b1a-1cec-4e30-8d26-43336de780f5.png">


works fine on v13 / develop
