### ISSUE TITLE
Cannot close overdue asset maintenance log

### ISSUE THREAD

**Issue by Simiil** [frappe/erpnext#15166]
When an asset maintenance log is overdue, setting the status to completed does not work.

**Steps to reproduce**
1. Have an overdue `Asset Maintenance Log`
2. Set status to `Completed` and set the completion date
3. Save

**Expected Behavior**

The asset maintenance log is now completed

**Actual Behavior**

Saving sets the Status to `Overdue` and throws the Error `Please select Maintenance Status as Completed or remove Completion Date`.

If the status is set to `Completed` and no completion date is set, saving just resets the status to  `Overdue` without error

**Information**

ERPNext: v10.1.48 (master)
Frappe Framework: v10.1.45 (master)

**Comment by federicocalvo** [comment]
Hi, i have de same issue.

ERPNext: v10.1.58 (master)
Frappe Framework: v10.1.51 (master)

**Comment by jaichavan** [comment]
Hello, @Simiil @federicocalvo this issue has been addressed and resolved in the current version, or as per @federicocalvo said, it works fine in version11.0.3-beta.19
Request you to upgrade your instance @Simiil to use this feature. Attaching GIF for your reference:

![asset-maintenance-log](https://user-images.githubusercontent.com/40264279/51443520-e9753b80-1d0f-11e9-9827-7e68ae151e3e.gif)

**Comment by RiffRaff2009** [comment]
Hi, I see this ticket was closed in August 2018, but we're having the same issue in version 11.

ERPNext: v11.1.77 (version-11)
Frappe Framework: v11.1.69 (version-11)
