### ISSUE TITLE
Journal Entry mysterious validation

### ISSUE THREAD

**Issue by SaiFi0102** [frappe/erpnext#15177]
I'm trying to make a reverse Journal Entry for an advance payment to a Supplier but I can't create a Journal Entry referencing the previous Journal Entry because of a validation error at: https://github.com/frappe/erpnext/blob/1ff23158995eb6deafe8df0fa4776649da7c8bba/erpnext/accounts/doctype/journal_entry/journal_entry.py#L177

I can't understand the reason for this validation. Is this correct and intended behavior? If I remove this validation to make my return payment Journal Entry, will it create an issue for any other feature in ERPNext?

**Comment by kennethsequeira** [comment]
@SaiFi0102 can you please post this on the [forum](https://discuss.erpnext.com) first?

In case this is a bug on our end or the validation needs improvement, the issue will be reopened.

Do post such functional queries on the forum first.
