### ISSUE TITLE
Restaurant: What if the Internet connection disconnected? Is there offline mode?

### ISSUE THREAD

**Issue by bghayad** [frappe/erpnext#15176]
Hello;

If the restaurant has branches and the server in the headquarter and the Internet connection disconnected, is there a way to continue the orders and the payments offline until the connection come back? 
What is the solution for this case?
Regards
Bilal

**Comment by olamide2** [comment]
Are you able to use the Restaurant module ?

**Comment by Muzzy73** [comment]
In offline mode you should be able to use it similar to retail pos. You can test it by ticking offline mode in POS Setting.

If your question has been responded then please close this Issue.

**Comment by dulhaver** [comment]
This is exactly the type of problem/questions to be discussed and solved on the [Forum](discuss.erpnext.com) I believe. Not an issue for here. Closing this therefore

**Comment by ashrafayad** [comment]
you can edit dom.js file search for is_online function and return true in all cases and run "bench build" it will work.
