### ISSUE TITLE
Linking to sales invoice and delivery note

### ISSUE THREAD

**Issue by KunalK09** [frappe/erpnext#15196]
There is no linking to sales invoice and delivery note in version 11 like below for website users
![deliverynote](https://user-images.githubusercontent.com/42600320/44464169-b1ba7880-a637-11e8-9f0e-67484523abdc.png)

**Comment by KunalK09** [comment]
Is there any update regarding this ?

**Comment by KunalK09** [comment]
Hi, Rohit Is there any update regarding this?

**Comment by harshit-30** [comment]
We have it now:
![image](https://user-images.githubusercontent.com/46772424/88333304-a1dccf00-cd4d-11ea-8696-dfdf9add5a35.png)
