### ISSUE TITLE
Supplier Mandatory Error

### ISSUE THREAD

**Issue by KunalK09** [frappe/erpnext#15192]
In supplier, i am getting auto fetched value in mandatory fields which i don't want ? Like in sales order mandatory fields are blanks .

![supplier](https://user-images.githubusercontent.com/42600320/44462869-8a61ac80-a633-11e8-9f72-19b6183e7fcd.png)
Which should be like this !!
![supplier](https://user-images.githubusercontent.com/42600320/44462069-e8d95b80-a630-11e8-97b8-6c094e5a768b.png)

**Comment by kennethsequeira** [comment]
Please post a screenshot so we can understand the issue better

**Comment by kennethsequeira** [comment]
You can remove default supplier group in **Buying Settings** and the Supplier Type via **Customize Form**

The country is chosen by default as the company country.
