### ISSUE TITLE
Purchase process ecommerce without login

### ISSUE THREAD

**Issue by federicocalvo** [frappe/erpnext#15198]
Hello, I highlight this functionality that is in one issue of 2015, but that is among several orders in that same issue.

> Review the whole login process so that customers can purchase without the need to create a login to our backend. This does not work reliably in my testing at the moment

It is a fundamental point for a customer to consider ecommerce if it comes from someone else like shopify, prestashop, etc. that do not limit the user to logging in, so they do not scare him for sale.

The only logic I can think of is, like the other ecomeerce, that the address and contact fields are on a single screen (which would then create the contact, user, customer and address) so you don't have to register.

We can order a bounty as we can collaborate and many others would join in.

Regards!

**Comment by parsimonyERP** [comment]
+1

**Comment by federicocalvo** [comment]
@ankush you should close this issue because I think it was announced that you are going to fix it at the time of launching the ecommerce refactoring.

**Comment by ankush** [comment]
@federicocalvo it didn't make it to this one but it's there on the roadmap with high priority: https://github.com/orgs/frappe/projects/26
