### ISSUE TITLE
Function doc.due_date==nowdate() is invalid in Email Alert trigger

### ISSUE THREAD

**Issue by incognitozen** [frappe/erpnext#15201]
Hi,

It appears that when trying to create a feedback trigger in ERP, the function 

    doc.due_date==nowdate()

is invalid.

The function is given as an example in the right-hand side window.
![project project](https://user-images.githubusercontent.com/32048201/44495149-20d4b300-a6b2-11e8-8676-3616555dd8fb.png)

The conditions given as examples next to the condition box are
Condition Examples:

doc.status=="Closed" doc.due_date==nowdate() doc.total > 40000

**Comment by kennethsequeira** [comment]
@incognitozen 

still facing this issue?

**Comment by incognitozen** [comment]
Yes

**Comment by kennethsequeira** [comment]
due_date is not a valid field in the selected doctype. Hence the issue is occurring.
