### ISSUE TITLE
ERPNEXT POS Invoice Price Issues

### ISSUE THREAD

**Issue by ismailsamih** [frappe/erpnext#15205]
In case of creating a POS invoice with the following existing conditions:-
- Customer selected in POS invoice is set to a certain customer group with a default price list.
-The price list does not exist for the item being entered.
Then the price is set to Null (ZERO) in the invoice without any warning/Error message.
 
Requirement : Need to have an error message if the price is not defined in the allocated price list.

**Comment by umairsy** [comment]
You can allow user to edit item price from POS Setting as well. Else, you should ensure that item price is entered for sure.

**Comment by ismailsamih** [comment]
Good Day,I do not believe this is the right solution. You are kindly requested to provide a real solution as requested earlier.Regards,Ismail AbuDahabThe Prime Technology Systems Zayed the first Street, FGB Building C88 Block A Office 2201 Abu Dhabi, UAE P.O.Box:47609Tel : +971 2 6819020Fax : +971 2 6819030email: Ismail.Samih@primeae.comWebsite : www.primeae.com


-------- Original Message --------
Subject: Re: [frappe/erpnext] ERPNEXT POS Invoice Price Issues (#15205)
