### ISSUE TITLE
Can I install erpnext without bench? 

### ISSUE THREAD

**Issue by lncan** [frappe/erpnext#15229]
Hello everybody! I want to install ERPNext without bench. Is it possible to install frappe/ERPNext without frappe/bench? If yes, please let me know. Thanks all.

**Comment by mhbu50** [comment]
No, You can not

**Comment by lncan** [comment]
@mhbu50 Yes. But in ERPNext installation process, i inspected 'bech' command like bench init, bench get-app, bench install-app and see 'bench' command include of commands like python, pip, yarn. So I hope it can be installed without bench. I don't want to be depended on bench.

**Comment by lncan** [comment]
@mhbu50 I use 'ps aux' command to inspect it.

**Comment by chdecultot** [comment]
Hi,

Why do you want to install ERPNext without Bench ?
Bench is a crucial part of the Frappe/ERPNext eco-system and handles a lot of configuration for you.

To be honest I don't think you can install Frappe without Frappe (unless you almost recreate it, which would be quite questionable...)

Good luck!

**Comment by chdecultot** [comment]
Closing this issue as it is more a question and it as been asked on the discuss forum.
