### ISSUE TITLE
Education Program Track 

### ISSUE THREAD

**Issue by africlouds** [frappe/erpnext#15225]
The education module groups courses into programs (eg Primary 1, Primary 2, etc) and a student enrolls in a particular program. Programs in ERPNext are independent of each other.

However, most education systems organize programs in a group of programs that need to be taken in a sequence to achieve a certain goal or degree. For example, for a student to complete Primary School, a student has to complete programs Primary 1 up to 6 and in that order.

My proposal is to add the following:

**Proposed Doctypes**

1. **Program Track:** An object that groups Programs in a sequence. For example: Primary groups Programs P1, P2 ...P6. There is a many-to-many relationship between Program Tracks and Programs since a Program can be part of several tracks. For example, the Program Accounting and Finance (Level 1 and 2) can be part of Program Tracks Accounting and Finance after splitting in Level 3
2. **Program Track Enrollment:** An object that links a Student or Student Applicant to a  Program Track. By default, a student would enroll into the 1st program in a track (Level 1) unless the student is transfered from another school. 

 Example: Agriculture Program Track, 4 years, each semester having its own program

![program-track](https://user-images.githubusercontent.com/20293015/44648524-98bc1980-a9e1-11e8-976c-4be15855101d.png)

**Note:**

1. A student can only enroll in programs that belongs to a  **Program Track** they are enrolled in
2. Student can enroll into a program if they have successfull completed the previous level
3. Student can shift tracks
4. The school senate/council decides if a student has successfully completed a program after deliberation and based on known criteria

**Comment by scmmishra** [comment]
Hey @africlouds 
Thanks for the request. We can work on it! However we need to clear some confusion here.
A program is an absolute entity in itself, a student enrols into one of the programs when the take admission in the college. So such a hierarchy can exists inside a program, that can handle the cases for multiple semesters 
So a program can have multiple courses, each belonging to a particular semester, and the rest of the logic can follow.

**Comment by fderyckel** [comment]
Maybe we can also clear this at a course level.  
For instance, you can only take Stat201 if you have already taken Stat101.  We should be able to have some logic there by adding a field "pre-requisite course" in the course doctype. 
Then if any course has a pre-requisite, it should check in past enrollment course that it had that course and succeed it.
