### ISSUE TITLE
Auto Email Report - Schedule to be sent at specific hour.

### ISSUE THREAD

**Issue by sachinhub** [frappe/erpnext#15256]
Auto Email Report currently support sending emails 'Daily', 'Weekly' or 'Monthly'. 

Proposal is to introduce another option - 'At Hour' and specify the hour at which report will be emailed - 

<img width="892" alt="screen shot 2018-08-30 at 12 54 27 pm" src="https://user-images.githubusercontent.com/8121864/44836200-e8098080-ac53-11e8-9f96-9f6e25096c8b.png">

If selected, this can be taken up during the code sprint.

**Comment by umairsy** [comment]
Similar to: https://github.com/frappe/erpnext/issues/13981

**Comment by Mishaal1021** [comment]
Hi,

Any update if ERPNext is considering this improvement, and expected timeline for this?

**Comment by mubeenmazhar** [comment]
Any update?
