### ISSUE TITLE
[Aug 2018] Datatable issues

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#15254]
- [x] Dropdown button on column header overlay (image 1)
- [x] Dropdown overflow (image 2)
- [x] Control Styling (Image 2)
- [x] Accept on blur (not "return") this is the most common behaviour
- [x] Accept checkbox on click

<img width="226" alt="screen shot 2018-08-29 at 4 19 38 pm" src="https://user-images.githubusercontent.com/140076/44828714-d5cd1980-ac36-11e8-8eb6-3d8e91bc3a8e.png">

<img width="210" alt="screen shot 2018-08-30 at 9 24 57 am" src="https://user-images.githubusercontent.com/140076/44828741-f006f780-ac36-11e8-8f71-befd8f86d2c1.png">

**Comment by joshreeder** [comment]
- [ ] "Sort by" function will reorganize list until you change visible amount (20, 100, 500)
- [ ] "Sort by" function will reorganize list until any user in the system saves a document for the doctype you are viewing. Example: open Sales Invoice/Report Builder: "Sort by Customer"; in another window create and save an invoice. datatable view will revert back to original sort. (hugely frustrating)
- [ ] "Sort by" data list not printable or exportable, reverts to unsorted data.
- [ ] Editable fields in a submittable document are not editable.

**Comment by agritheory** [comment]
- [ ] Optional two-way binding
- [ ] Option to change bg color when data changes from original
- [ ] Tab to complete and move to next cell (to the right, not down, though maybe this should be configurable)

**Comment by joshreeder** [comment]
> * ab to complete and move to next cell (to the right, not down, though maybe this should be configurable)

As long as cell is editable... In fact, editable cells could have slightly different visual. Noneditable data is 90% black and editable text is black, or something like that.

**Comment by Tropicalrambler** [comment]
+1 on TAB to move to next cell.  
Wild idea: TAB behavior should be configurable, so that user might use TAB inside for certain columns, and once no more data exists, it moves to next cell?
+1 on right arrow to move to next cell from editing, without having to press enter. +1 On enabling configuration capability for these settings as well.

**Comment by netchampfaris** [comment]
https://github.com/frappe/datatable/pull/72
