### ISSUE TITLE
upgrading from ERPNext: v10.1.49 to 11

### ISSUE THREAD

**Issue by jasonbrowne** [frappe/erpnext#15274]
We are currently running  ERPNext: v10.1.49.

In an attempt to upgrade to v11 I have tried the following:

frappe-bench$ bench switch-to-develop
frappe-bench$ bench switch-to-branch develop
bench update --patch
 bench update --upgrade     
produces the following error:

Error: no such option: --upgrade

Cheers,
Jason

**Comment by jasonbrowne** [comment]
It would also be nice to be able to upgrade via the WebGui.
Simple drop-down button asking if you want to update / upgrade erpnext.

**Comment by Muzzy73** [comment]
https://discuss.erpnext.com/t/how-to-upgrate-erpnext-app-to-v11-branch-develop/40251

Maybe this would help. Please close this Issue as GitHub is mainly used for major issues. Queries can be answered on the forum. Thanks for understanding b

**Comment by jasonbrowne** [comment]
Here is a pastbin link to the steps we have tried, but are still unable to upgrade past erpnext 10.1.49 to v11.
https://pastebin.com/XCvJL29N
