### ISSUE TITLE
"Additional Discount" in Sales Invoice erased when save or submit (v10.1.49)

### ISSUE THREAD

**Issue by franciscobuendiao** [frappe/erpnext#15288]
ERPNext: v10.1.49 (master)
Frappe Framework: v10.1.46 (master)

**_Additional Discount Amount (Company Currency)_**, **_Additional Discount Percentage_** and **_Additional Discount Amount_**, are erased when saving or submitting Sales Invoice.

No errors in console.

**Comment by shreyashah115** [comment]
This has been fixed.
