### ISSUE TITLE
Field level higher than 2 not working from doctype page!!!

### ISSUE THREAD

**Issue by dufani1** [frappe/erpnext#15297]
I created doctype in my custom app (not custom doctype) and I noted that the field level higher the 2 not working.
Fields that have level higher than 2 not appearing in doctype even though I gave level permissions.
**Edit:** it working just if I add it to **Role Permissions Manager**

![untitled](https://user-images.githubusercontent.com/23026263/44974692-b7319000-af60-11e8-81b8-23f825c45b9c.png)

![untitled1](https://user-images.githubusercontent.com/23026263/44974913-56ef1e00-af61-11e8-83a3-3102692efdca.png)

**Comment by umairsy** [comment]
Hi,

Request such queries on the ERPNext community forum at first. If they are validated as a bug, we can reopen this issue.

https://discuss.erpnext.com

**Comment by neelbhanushali** [comment]
@dufani1 @umairsy 

was this posted to https://discuss.erpnext.com?
kindly put down a link to it here
