### ISSUE TITLE
Bench migrate error

### ISSUE THREAD

**Issue by jaqobk** [frappe/erpnext#15294]
Hi, 
am facing this error when I try to bench update and cant even login to my system.. kindly help.

> Backing up sites...
> Patching sites...
> Migrating fr.jaydcosmetics.co.ke
> Executing erpnext.patches.v11_0.merge_land_unit_with_location in fr.jaydcosmetics.co.ke (523db71e0e0fc041)
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
>     "__main__", fname, loader, pkg_name)
>   File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
>     exec code in run_globals
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 97, in <module>
>     main()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
>     click.Group(commands=commands)(prog_name='bench')
>   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 697, in main
>     rv = self.invoke(ctx)
>   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
>     return callback(*args, **kwargs)
>   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
>     return f(get_current_context(), *args, **kwargs)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 25, in _func
>     ret = f(frappe._dict(ctx.obj), *args, **kwargs)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 222, in migrate
>     migrate(context.verbose, rebuild_website=rebuild_website)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/migrate.py", line 39, in migrate
>     frappe.modules.patch_handler.run_all()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 29, in run_all
>     if not run_single(patchmodule = patch):
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 63, in run_single
>     return execute_patch(patchmodule, method, methodargs)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 83, in execute_patch
>     frappe.get_attr(patchmodule.split()[0] + ".execute")()
>   File "/home/frappe/frappe-bench/apps/erpnext/erpnext/patches/v11_0/merge_land_unit_with_location.py", line 53, in execute
>     }).insert(ignore_permissions=True)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 249, in insert
>     self.run_post_save_methods()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 898, in run_post_save_methods
>     self.run_method("on_update")
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 765, in run_method
>     out = Document.hook(fn)(self, *args, **kwargs)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1041, in composer
>     return composed(self, method, *args, **kwargs)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1024, in runner
>     add_to_return_value(self, fn(self, *args, **kwargs))
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 759, in <lambda>
>     fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
>   File "/home/frappe/frappe-bench/apps/erpnext/erpnext/assets/doctype/location/location.py", line 30, in on_update
>     NestedSet.on_update(self)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/nestedset.py", line 185, in on_update
>     update_nsm(self)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/nestedset.py", line 42, in update_nsm
>     update_move_node(doc, pf)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/nestedset.py", line 94, in update_move_node
>     validate_loop(doc.doctype, doc.name, new_parent.lft, new_parent.rgt)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/nestedset.py", line 181, in validate_loop
>     frappe.throw(_("Item cannot be added to its own descendents"), NestedSetRecursionError)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 339, in throw
>     msgprint(msg, raise_exception=exc, title=title, indicator='red')
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 325, in msgprint
>     _raise_exception()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 298, in _raise_exception
>     raise raise_exception(msg)
> frappe.utils.nestedset.NestedSetRecursionError: Item cannot be added to its own descendents
> 

I have tried bench migrate and got the same error... 
did bench setup socket.io
bench setup redis
restarted supervisor and nginx
on checking supervisor all are running..
I also tried with both root and frappe user but still the same error on both.
what could be wrong.
also note I have multitenants setup

**Comment by clarkejj** [comment]
see discussion here https://discuss.erpnext.com/t/error-on-bench-update-and-am-confused-v11-patch-nestedsetrecursionerror-item-cannot-be-added-to-its-own-descendents/40318

**Comment by jaqobk** [comment]
this was solved
