### ISSUE TITLE
 [v10.1.49-master] [BUG] item dashboard: stock movement calendar problem

### ISSUE THREAD

**Issue by yunielroque** [frappe/erpnext#15292]
August calendar month is missing, it is also confusing because months are not limited.

Previos Calendar (OK):
![screenshot from 2018-09-01 13-41-08](https://user-images.githubusercontent.com/17571055/44948527-b37cfc80-adec-11e8-9ee4-8c547ed1a13f.png)

Current Calendar (PROBLEM):
![screenshot from 2018-09-01 13-43-34](https://user-images.githubusercontent.com/17571055/44948548-24bcaf80-aded-11e8-91e8-edc315358fe1.png)

**Comment by parsimonyERP** [comment]
👍 The previous calendar/heat-map was much easier to read.

**Comment by umairsy** [comment]
Could you please also share the records indicating data in august, but not reflecting in the dashboard?
