### ISSUE TITLE
[Bug] Cannot Save Additional Discount Amount in Forms

### ISSUE THREAD

**Issue by kennethsequeira** [frappe/erpnext#15290]
- Reported in Quotation and Sales Invoice.
- When amount is added in additional discount section and saved, it goes back to zero

![additional-discount](https://user-images.githubusercontent.com/33246109/44945883-2303e380-ae0f-11e8-887e-96262925952d.gif)

**Comment by shreyashah115** [comment]
@kennethsequeira which version?

**Comment by kennethsequeira** [comment]
@shreyashah115 checked in v10 master.
