### ISSUE TITLE
Sales Analytics - Performance and Customer Filter

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#15319]
If there are may customers, report takes very long to load.

Also, scrolling and searching customer becomes difficult. We should have filter for Customer.

**Comment by adnanmunir83** [comment]
in Sales Analytics, if we are using Num Series in Items,  during this report, Item Name is not appearing.  that is also a key element for analysis.

Please Consider this as well.

**Comment by snvora** [comment]
Hi,

We face a similar problem in lots of reports. Default filters are not always what we are looking for. This results in unnecessary initial processing.

How about for all reports, it confirms filter before loading.

What do you think?

**Comment by pratu16x7** [comment]
https://github.com/frappe/erpnext/issues/14226

**Comment by djpalshikar** [comment]
For me all analytics reports(Sales, Purchase, Production, Stock) are timed out. This issue(#13664) was created after it was first reported.

Using filters can be a good temporary fix if it can be done quickly.

**Comment by RSKROGER** [comment]
Yes, it's important to add filters but the speed of the report needs to be improved as well. The more data that we add, the slower the system is responding.

**Comment by RSKROGER** [comment]
Hi,

 

I saw this issue was closed but the performance issues are still occurring in ERPNext and customer filters have not been added. 

 

Please advice.

 

Roger
