### ISSUE TITLE
I cannot process Return for any item without referring to the original Sales Invoice

### ISSUE THREAD

**Issue by abhinav666** [frappe/erpnext#15333]
I cannot get this to work. I dont see the "Is Return/Credit Note" option when making a new Sales invoice.
Why would that be? I think this feature has been integrated in all latest versions of ERPNext. I am on a paid version of ERP Next ver 10.1.51 (master).

Please HELP, since I need this urgently, we do frequent returns and exchange.

**Comment by abhinav666** [comment]
Hoping to get some help on this???

**Comment by umairsy** [comment]
In version 11, the feature for standalone Debit/Credit Note as been added. In V10, you can create it via Journal Entries.
