### ISSUE TITLE
Module import failed for Amazon MWS Settings  when bench update

### ISSUE THREAD

**Issue by ahmedzaqout** [frappe/erpnext#15359]
module = load_doctype_module(self.name, self.module)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/modules/utils.py", line 187, in load_doctype_module
    raise ImportError('Module import failed for {0} ({1})'.format(doctype, module_name + ' Error: ' + str(e)))
ImportError: Module import failed for Amazon MWS Settings (erpnext.erpnext_integrations.doctype.amazon_mws_settings.amazon_mws_settings Error: No module named 'amazon_methods')

**Comment by PawanMeh** [comment]
https://github.com/frappe/erpnext/pull/15349 fix is pushed for this. It appears to an issue on Python 3.
