### ISSUE TITLE
make_gl_entries is called twice

### ISSUE THREAD

**Issue by SaiFi0102** [frappe/erpnext#15361]
When submitting a Purchase Invoice I noticed that make_gl_entries is called twice, however, there is no duplicate. Is this normal?

I tried to produce a stack trace, but I didn't know how to so I printed a stack of functions called:

make_gl_entries, make_gl_entries, on_submit, , runner, composer, run_method, run_post_save_methods, _save, save, _submit, submit, savedocs, call, execute_cmd, handle, application, application, application, __call__, __call__, __call__, debug_application, execute, run_wsgi, handle_one_request, handle, handle, __init__, finish_request, process_request_thread, run, __bootstrap_inner, __bootstrap

----------------------------------------------

make_gl_entries, make_gl_entries, update_gl_entries_after, make_gl_entries, on_submit, , runner, composer, run_method, run_post_save_methods, _save, save, _submit, submit, savedocs, call, execute_cmd, handle, application, application, application, __call__, __call__, __call__, debug_application, execute, run_wsgi, handle_one_request, handle, handle, __init__, finish_request, process_request_thread, run, __bootstrap_inner, __bootstrap

**Comment by umairsy** [comment]
Can you please share the value in the transaction? Will be great if you could report it in https://discuss.erpnext.com. Once it is validated as a bug, we can reopen this issue here.
