### ISSUE TITLE
[Bug] Cannot Download Files as ZIP

### ISSUE THREAD

**Issue by kennethsequeira** [frappe/erpnext#15373]
- Open **File**
- Menu > Import  .zip

![image](https://user-images.githubusercontent.com/33246109/45282319-35a9a700-b4f8-11e8-8b7e-d5601b028638.png)

![image](https://user-images.githubusercontent.com/33246109/45282353-3fcba580-b4f8-11e8-9d5c-f9dbea07b92e.png)

ERPNext: v10.1.51 (master)

Frappe Framework: v10.1.46 (master)

**Comment by kennethsequeira** [comment]
@Zlash65 never mind. Got this sorted

**Comment by EliZABZ** [comment]
@Zlash65 - May you advise how you sorted this issue?
