### ISSUE TITLE
Purchase/Sales Tax not reflected in Journal Entry

### ISSUE THREAD

**Issue by Mohd200** [frappe/erpnext#15370]
Good Day Everyone,

I have an Issue with the Purchase and Sales Register. There are regular cases where I Buy/Sell Items from/to small Suppliers/Customers every once in awhile, but never buy/sell from/to the same small Supplier/Customer.
(BTW: Taxes are involved in the Matter and is the Essence of the Report).
Therefore, I don’t create a PO or PINV/SO or SINV, instead I create a Journal Entry. Now, in the JE, I arrange and enter the Data Appropriately Accounting-wise, and it works correctly.

However, when I wish review my Purchases and the Taxes of those Purchases/Sales and the Taxes of those Sales, I open the Purchase/Sales Register, which displays only the PINV/SINV, and not the Purchases/Sales I made through the JE.

**_What I need is:_**
Purchase/Sales Register Report or any other similar Report, to Display all of the PINV/SINV and the Purchases/Sales made by JE, Taxes included.

Thank You

**Comment by umairsy** [comment]
It will be best to create a generic customer and supplier for this case. You can also make invoices, with payment entry right from Invoice itself.
