### ISSUE TITLE
Exception: redis_queue missing in common_site_config.json

### ISSUE THREAD

**Issue by lncan** [frappe/erpnext#15377]
Hello everybody. I'm using supervisor to start server. But when i read logs, i found same 'Exception: redis_queue missing in common_site_config.json' fault in worker.error.log and scheduler.error.log. But when I read common_site_config.json file in sites, 'redis_queue' still be there. Anybody has idea to fix this? Thank you. 

Here is my common_site_config.json file:
```
{
 "auto_update": false,
 "background_workers": 1,
 "file_watcher_port": 6787,
 "frappe_user": "frappe",
 "gunicorn_workers": 1,
 "rebase_on_pull": false,
 "redis_cache": "redis://localhost:13000",
 "redis_queue": "redis://localhost:11000",
 "redis_socketio": "redis://localhost:12000",
 "restart_supervisor_on_update": true,
 "restart_systemd_on_update": false,
 "serve_default_site": true,
 "shallow_clone": true,
 "socketio_port": 9000,
 "update_bench_on_update": true,
 "webserver_port": 8000
}

```

**Comment by yashodhank** [comment]
You already have posted it on discussion forum.
https://discuss.erpnext.com/t/exception-redis-queue-missing-in-common-site-config-json/40609
Kindly refrain from opening issue here, unless you do your troubleshooting using existing discussions on forum.

if there is bug, feel free to reopen it later.
