### ISSUE TITLE
Pick list feature at the time of delivery note

### ISSUE THREAD

**Issue by Salmanmulani** [frappe/erpnext#15388]

**Comment by rushikesherp** [comment]
Salman can you please provide further explanation?
If you mean choosing the name of from warehouse in transaction, which I believe was one user's request, then that is covered in existing delivery note screen

**Comment by Salmanmulani** [comment]
This is related to loading of material at the time of delivery.

Warehouse user will have a list of items which he needs to pick for
delivery.

**Comment by umairsy** [comment]
Duplicate https://github.com/frappe/erpnext/issues/9763
