### ISSUE TITLE
Storno invoice for Sales Return

### ISSUE THREAD

**Issue by BebeMix** [frappe/erpnext#1538]
We can create an invoice to sell:
- stock qty - sell 5 products
- money - sell 20x5 = 100 usd

In case of a sales return, now we need to create 2 documents (stock entry and credit note) and it is anoying for the customers that requests.

We need to be able to make a storno in one transaction:
- stock qty - "-1" product
- money - 20x"-1" = "-20" usd

Mihai

**Comment by rmehta** [comment]
Fixed with #3582
