### ISSUE TITLE
Purchase order not loading

### ISSUE THREAD

**Issue by joshiparthin** [frappe/erpnext#15406]
I am using following version: 

```
$ bench version
erpnext 10.1.52
foundation 0.0.1
frappe 10.1.47

```

while loading Purchase order it turns blank:
<img width="1414" alt="screen shot 2018-09-15 at 11 45 11 am" src="https://user-images.githubusercontent.com/6594877/45583295-daebc300-b8dc-11e8-98da-31ad38c650b7.png">

JS Console says following error: 
```
Uncaught (in promise) TypeError: Cannot read property 'extend' of undefined
    at eval (eval at setup (script_manager.js:155), <anonymous>:409:65)
    at init.setup (script_manager.js:155)
    at _f.Frm.setup (form.js:108)
    at _f.Frm.refresh (form.js:428)
    at FormFactory.load (formview.js:85)
    at formview.js:79
    at model.js:163
    at new Promise (<anonymous>)
    at Object.with_doc (model.js:160)
    at FormFactory.show_doc (formview.js:60)
```

VM540:409 Uncaught (in promise) TypeError: Cannot read property 'extend' of undefined
points to: 

```
erpnext.buying.BuyingController = erpnext.TransactionController.extend({
	setup: function() {
		this._super();
	},

```
where the error is. 

Regards, 

Parth

**Comment by rohitwaghchaure** [comment]
Have you did any customizations? If yes please revert and check

**Comment by mkumar9699** [comment]
Dear Rohit,


No. I did not do any customization.


Thanks

Mithilesh Kumar

________________________________

**Comment by mkumar9699** [comment]
Sorry. Please ignore it.

________________________________

**Comment by joshiparthin** [comment]
@rohitwaghchaure @joolsr  no. No customizations here. Still the same error.
