### ISSUE TITLE
New form modifying the submitted form in previous route

### ISSUE THREAD

**Issue by SaiFi0102** [frappe/erpnext#15403]
To reproduce this problem just watch the GIF
![bug](https://user-images.githubusercontent.com/328330/45562967-5873ec80-b865-11e8-8b22-45adf836ffa7.gif)

**Comment by shreyashah115** [comment]
Which version are you on?

**Comment by SaiFi0102** [comment]
Latest develop branch: both erpnext and frappe

**Comment by crescent28** [comment]
Hello, 

I tried replicating this issue and it seems to be working fine on the following versions: 

ERPNext: v10.1.68 (master)
Frappe Framework: v10.1.59 (master)

**Comment by SaiFi0102** [comment]
@crescent28 Did you try it on v11?

**Comment by SaiFi0102** [comment]
@crescent28 You can reproduce this problem on demo.erpnext.com
Try it on any Sales Invoice: https://demo.erpnext.com/desk#Form/Sales%20Invoice/SINV-00003 for example. Please reopen this issue.
