### ISSUE TITLE
Integrate Whatsapp for business

### ISSUE THREAD

**Issue by vorasmit** [frappe/erpnext#15412]
API is available

https://www.whatsapp.com/business/api

- [ ] Configure messages/templates

- [ ] Mobile no as country code + mobile number

- [ ] Choose communication prefrence for contact

- [ ] Contact Group (say supplier / customer / employee)

- [ ] Group Notification (say holiday)

- [ ] Supply Intimations (like email of invoice)

- [ ]  Pre timed messages (like birthday/anniversery wishes)

It has got wide application.

**Comment by idolaru** [comment]
Note, we should add features for Leads and Event doctypes as well.

**Comment by africlouds** [comment]
Isn't better to do the integration at Frappe level, as an extra Channel on the Notification doctype. That way it could be accessible from any module built on Frappe

**Comment by federicocalvo** [comment]
Hi @SaiFi0102 @idolaru @vorasmit , let's start with the analysis of how to perform the functionalities, and we would like them to be active both for testing and feedback, and who from the Frappe team tag to help us in the task of getting on the right track.

- The first @vorasmit  would need to add the functionality you are mentioning @idolaru 
- And we have to define which is the best platform to perform the API integration. Among them we know (twillo, nexmo and messagebird). It is a question of evaluating prices or if someone has a reference, in case nobody answers it we will choose it based on an analysis.

The API of whatssapp is not possible to use it in a direct way without asking for a permission, that we do not know who gives them and who does not. And the requirements to host the solution are very high, closing the solution only a few.

We look forward to hearing from you!

**Comment by idolaru** [comment]
Hi hi,
From my side - I wish to see the development up and running and hopefully added to the core as it's finished and properly working.

I am happy to provide to do testing, bring up ideas, feedback but more than this I can't really assist....

I will be unavailable for the upcoming 2 weeks but once I get back connected on the internet I will catch up with the development and see what we need.

**Comment by Najjjar** [comment]
Hello,

This is Ahmad Najjar from SehaCloud, we're using erpnext in the healthcare setup (Hospitals, and Healthcare centers)

I'm interested in this feature if it will cover the requirements for the healthcare sector, specially that patient needs to have reminders about their appointments, Medications, Lab Results, Healthcare Education, ect..) Currently my team is working on a notification engine that use SMS, IVR, in addition to erpnext notification engine.... if we could add whatapp on this that will help us alot and it will reduce the cost of the healthcare organizations.

Inform me what type of information that you need to give you the full picture about the healthcare business scenarios, I've specific workflows for each stage (Business flow, Patient Journey Flow) see the below example
![image](https://user-images.githubusercontent.com/57355171/68121690-10080a00-ff11-11e9-97aa-2a765bc81c27.png)

![image](https://user-images.githubusercontent.com/57355171/68121720-22824380-ff11-11e9-9020-3dc3e78c35b3.png)

I think those cases are a limitless, so it is butter to think about something reconfigurable in the system for all documents.

Let's have a discussion about this feature, and inform me how I can help to make it live.

Thank you

**Comment by tecnofoodmx** [comment]
We'd love to support this initiative. We reccomend the following functionalites:
- accesing WhatsApp chat from erpnext chat (several erpnext users/ salespersons to the same WhatsApp number)
- creating leads and contacts from chat contact.
-sending notifications to WhatsApp contact (sales invoice, payment entry, etc).

Please let us know how to cotribute

**Comment by Tristan370** [comment]
Is there any update on the Whatsapp business integration?

**Comment by 5p4r70n** [comment]
any updates ???

**Comment by federicocalvo** [comment]
@Tristan370 @5p4r70n reed the PR https://github.com/frappe/erpnext/issues/19196
the app is made more than a year ago, but you will not deserve it, so you can use the PR or look for the post we made in discuss with separate app

**Comment by franknyarkoh** [comment]
This idea is great. I support it fully

**Comment by umairsy** [comment]
It has been partly done with twilio app integration. It allows sending Whatsapp messages from ERPNext.

https://frappecloud.com/marketplace/apps/twilio
