### ISSUE TITLE
ETB (Ethiopian Birr) required in Currency Master within ERPNext

### ISSUE THREAD

**Issue by rushikesherp** [frappe/erpnext#15417]
Currently ETB (Ethiopian Birr) does not exist in Currency Master.
It should be default currency for county Ethiopia.
We should also be able to fetch the exchange rates for ETB as in other currencies during transactions.

**Comment by kennethsequeira** [comment]
Added:

https://github.com/frappe/frappe/blob/8a9897e156e70faa6c06da190d9bd2ee0a745e59/frappe/geo/country_info.json#L821
