### ISSUE TITLE
[V11] Wrong tax withholding amount calculated in purchase invoice

### ISSUE THREAD

**Issue by wispmac** [frappe/erpnext#15438]
Our current version is:
ERPNext: v11.x.x-develop (63a58a6) (develop)
Frappe Framework: v11.x.x-develop (48e18a1) (develop)

When we create a new purchase invoice, wrong tax withholding amount is calculated. For Example, if the net amount of the invoice is INR 75000.00 and GST calculated is INR 13500.00, the TDS (Tax withholding) @ 10% should be INR 7500.00. System is calculating INR 8850.00. i.e. it is calculating on Net Amount + GST (INR 88500.00). Actually it should be calculated on Net Amount only (INR 75000.00)

![image](https://user-images.githubusercontent.com/2329537/45736694-54e7b900-bc09-11e8-911f-b927b5e21102.png)

**Comment by PawanMeh** [comment]
Unable to replicate the issue. Maybe something missing in your witholding setup?

![witholding_tax](https://user-images.githubusercontent.com/20460498/45741280-cd07ac00-bc14-11e8-8c1f-5cf55e247b1c.gif)

**Comment by karannshah** [comment]
@PawanMeh I'm facing an issue with cumulative threshold. I've created a new tax withholding category  and have assigned it to a supplier Lufthansa airlines. 

The first purchase invoice I created with 90,000 INR - the system calculated correct TDS at 0.5% (equal to INR 450) as configured in the withholding category.

But is the second purchase invoice - I added an amount greater than the cumulative threshold (I have set threshold at 10 lakhs and I created an invoice of INR 12 lakhs). In this case the system calculated TDS at 0.5% equal to INR 6000. Ideally in this scenario the system should have calculated TDS on INR 12 lakhs like

9,10,000*0.5% + 2,90,000*2% =  10,350 - instead it computed it as INR 6000

2 issues where need your help 
1) once cumulative threshold is crossed how is TDS being computed in ERPNext. 
And 2) I observed all TDS rates in Purchase Invoice appeared as Zero percent though they were computed right. Even in the GIF you have uploaded if you notice TDS rate row - it appears as 0% but TDS is computed correctly. 
<img width="1440" alt="screen shot 2018-10-15 at 3 49 52 pm" src="https://user-images.githubusercontent.com/14230707/46945778-6a7ac200-d093-11e8-9aa7-4f758fbeb1ec.png">
<img width="1440" alt="screen shot 2018-10-15 at 3 48 28 pm" src="https://user-images.githubusercontent.com/14230707/46945779-6a7ac200-d093-11e8-8bc7-d0231c814ae0.png">
<img width="1440" alt="screen shot 2018-10-15 at 3 48 48 pm" src="https://user-images.githubusercontent.com/14230707/46945780-6a7ac200-d093-11e8-8a1e-dbbd6cf10f09.png">
<img width="1440" alt="screen shot 2018-10-15 at 3 49 40 pm" src="https://user-images.githubusercontent.com/14230707/46945782-6b135880-d093-11e8-871a-c2b5d9c0519e.png">

**Comment by karannshah** [comment]
@nabinhait TDS calculations are happening incorrectly for invoices crossing threshold amount

**Comment by umairsy** [comment]
Can you please update your ERPNext account and check if this issue prevails. We can reopen it if valid.

**Comment by karannshah** [comment]
@umairsy still prevails for cumulative threshold calculation.

**Comment by karannshah** [comment]
> Can you please update your ERPNext account and check if this issue prevails. We can reopen it if valid.

Still the issue prevails.

**Comment by spachori94** [comment]
@umairsy @PawanMeh The issue still prevails. And in gif, you have uploaded TDS Rate is being shown as 0% which is wrong. I have configured TDS withholding category as 2%. The calculation is being done on Invoice Amount + GST which is wrong and in TDS Payable report the TDS % too is being reflected as 0. Please help us in resolving the issues

**Comment by PawanMeh** [comment]
Have tried with 1% TDS and applied witholding and GST. Seems to work fine. TDS shows 0 as percentage but applies 1% as per configuration. This is as per current design in ERPNext.

![TDS_1](https://user-images.githubusercontent.com/20460498/57606807-52b2e000-7587-11e9-97df-ff0fa18ce1f7.png)


![TDS_2](https://user-images.githubusercontent.com/20460498/57606809-52b2e000-7587-11e9-95fa-01eee7891214.png)
