### ISSUE TITLE
[V11] Error "Could not find _doctype: Land Unit" while setting/changing desktop icons

### ISSUE THREAD

**Issue by wispmac** [frappe/erpnext#15433]
Our current version is:
ERPNext: v11.x.x-develop (63a58a6) (develop)
Frappe Framework: v11.x.x-develop (48e18a1) (develop)

After the latest update, cannot change/set desktop icons. We get error: "Could not find _doctype: Land Unit" whenever the save button is clicked

![image](https://user-images.githubusercontent.com/2329537/45687448-82caf000-bb6c-11e8-8c5e-43403a80b5ff.png)

**Comment by umairsy** [comment]
Works fine in my test account. Please upgrade and check again. Closing issue for now. Reopen if needed.
