### ISSUE TITLE
Stock Entry for Transfer of Material to start Work Order does not fetch items, V11.

### ISSUE THREAD

**Issue by azharul-islam** [frappe/erpnext#15469]
<img width="1274" alt="screen shot 2018-09-21 at 7 42 04 pm" src="https://user-images.githubusercontent.com/38819502/45895353-a181ee80-bdd9-11e8-8a21-f00ff7bc7fb8.png">
<img width="1420" alt="screen shot 2018-09-21 at 7 47 15 pm" src="https://user-images.githubusercontent.com/38819502/45895355-a34bb200-bdd9-11e8-942b-9b357de4b2f9.png">

I followed the same steps as I used to in v10, however items did not populate and a red box appeared around it (see screenshot). Also, when I tried to add items manually, i received the error "wrong fieldname  None in add_fetch config of custom script"

**Comment by Mitchy25** [comment]
Im also getting this error since updating to V11

**Comment by azhar-aa1207560** [comment]
I just switched the branch to Staging and the error now is gone. Looks like staging is a more stable v11.

**Comment by seroonlinecampus** [comment]
How did you change to staging

**Comment by azharul-islam** [comment]
@seroonlinecampus run command `bench switch-to-branch staging`
That should do it. Make sure you see message that says something like "branch converted for () erpnext, frappe"
If erpnext wasn't converted successfully, you will have to do it manually.

`cd frappe-bench/apps/`
`rm -r erpnext` (Remove ERPNext folder. You will have to press "y" and Enter couple of times)
`cd frappe-bench/`
`bench get-app erpnext https://github.com/frappe/erpnext --branch staging`
Then, make sure to run `bench update.` 💯

**Comment by Mitchy25** [comment]
FYI - This didn’t fix the issue for me :(

**Comment by Mitchy25** [comment]
Azharul - Did you do an install from scratch? If yes, what guide did you follow? I installed via one of the playbooks and I think it could be causing issues

**Comment by seroonlinecampus** [comment]
Hello azharul-islam How can i install back version 10.1.52 from github, i personally feel alot is still missing in the new version. the guide am using is https://github.com/frappe/frappe/wiki/Guide:-Manual-Install-ERPNext-on-Ubuntu-17.xx-&-18.xx
If i can get a way to install the earlier version i will be happy.

**Comment by azharul-islam** [comment]
You can switch to master branch by using the same steps above. Just replace "staging" with "master". Master branch still had v10 last I checked. 

I'd avoid downgrading though if the database already has some data as I don't think bench update has scripts to revert db schemas back to v10 schemas.

**Comment by seroonlinecampus** [comment]
I just wanted to do a clean install of the last version so I put master, Thanks let me try.

**Comment by kennethsequeira** [comment]
Closing the issue as the Stock Entry is now working correctly. 

If any sort of issue in encountered again, you can open a new issue along with the ERPNext and Frappe versions.
