### ISSUE TITLE
Italian Electronic Invoice mandatory from January 2019 - Fattura Elettronica

### ISSUE THREAD

**Issue by mascor** [frappe/erpnext#15468]
**Reference (document issued by Italian Government):**
https://www.agenziaentrate.gov.it/wps/wcm/connect/a8316033-6124-4667-99d8-ed143dc72c20/Provvedimento_30042018+.pdf?MOD=AJPERES&CACHEID=a8316033-6124-4667-99d8-ed143dc72c20

**Requirements:**
- generate, at the end of the day, a unique XML file that exports all the selected Sales Invoice;
- the user will be able to select the invoices for a period and select using row checkboxes;
- user click on "Export XML Invoices" and will be able to download the XML file containing the selected invoices;

**For details about XML Schema see here:**
http://www.fatturapa.gov.it/export/fatturazione/en/normativa/f-2.htm

The final product can be part of the Italian Localization or a Frappe Custom App

**Plan:**
- We will wait till 28th of September for tips or updates from the community
- From the first week of October we will start to implement it.
- We will try to complete development before 12th of October
- Complete test before the end of October

**Future implementation:**
This is the first step, an evolution of this process will be the capability to:
- apply Digital Signature using smart card reader;
- automatically send to SDI web service;

**Comment by mascor** [comment]
I created a repository for a Custom App:
https://github.com/mascor/erpnext_fattura_elettronica
will be completed before the end of October

**Comment by cosimot** [comment]
How many ERPnext users are in Italy? Because we will all need this...
Per il ciclo passivo pensavi di "pescare" le fatture in PDF dallo SDI? 
Sarebbe carino riuscire a importare le fatture di acquisto in .xml per velocizzare le registrazioni...

**Comment by mascor** [comment]
Hi, the situation is this:
- we created a Frappe Custom App that you can install to your site to test the Export Function
- there are a lot of scenarios to implement in the Custom App because a lot of fields required by the Italian Government are used only in particular cases;
- Tomorrow we will merge the actual branch to develop branch: https://github.com/mascor/erpnext_fattura_elettronica
- After testing this Custom App in several Sites with a different setup, we will start to work on the pull request for the localization;

We hope to complete the development of the first release this week and we will initiate the pull request for localization by the end of next week. After then the Frappe Team will discuss about merging this pull request in the core.

If anybody wants to participate in testing phase can write me an email using this address:
massimiliano.corvino @ gmail.com

**Comment by erickrojasfigueroa** [comment]
@mascor Excelent!

**Comment by reipes** [comment]
Hi,
i tried to install the module fatturazione elettronica. The installation seems to be ok since it i appears in nexterp. I tried to generte an invoice following the instructions but when i export the xml i get this error:

GET /api/method/erpnext_fattura_elettronica.export_invoices.generate_single_invoice?invoice_name=ACC-SINV-2019-00001 HTTP/1.1" 404 -
and 
in the browser I get an error Method not found.

Also strange is that I don't see in my  erp the doctype
EFE XML Export

What did I miss?

best regards

**Comment by mascor** [comment]
> Hello @reipes , the ERPnext team is directly developing the E-invoice for the Italian localization in the Core. It will be ready in max 2 weeks and it will be accessible to all ERPnext users.
> This is how it will be done.
> #16259

The situation is:
- we developed a custom app to manage XML Export from Erpnext. The custom app works and export correct XML files using ERPNEXT and FRAPPE version 10;
- this week Frappe Team asked us to convert our app into the Italian Localization;
- we will try to complete soon as possible the localization;

I'm going to close this issue. For the future please refer to this:
https://github.com/frappe/erpnext/issues/16259
