### ISSUE TITLE
Error upgrading from 10.1.53 v to 11 

### ISSUE THREAD

**Issue by Osamashanawany** [frappe/erpnext#15474]
pymysql.err. Operational error (2003,can't connect to  mysql server on u ' local host'[ Error 111] connection refuesd

**Comment by yashodhank** [comment]
@Osamashanawany This question is not related to ERPNext, don't open issues without asking question on discussion forum or doing google search for help!

Possible Solution:
`[Error 111] connection refused`, which in turn means that your MySQL daemon only listens to the localhost interface.
To alter it you may want to look at the bind-address value in the [mysqld] section of your my.cnf file.
