### ISSUE TITLE
Workflow to allow  “Inspection Required on manufacturing”

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#15472]
The following workflow is not implemented in the system:

Finished products are manufactured (serialized units)
Quality Inspection is created for each serialized finished product after manufacturing (manufacture stock entry) -à finished products items have “Inspection Required before Delivery” enabled.
Delivery note is created against finished products (serialized) units
 
Step 3 is currently not possible since the system is asking for quality inspection in delivery note “Submit”.

We use the workaround to des-activate “Inspection Required before Delivery” item by item to perform Delivery Note.

Need to create a new workflow to allow  “Inspection Required on manufacturing”

**Comment by xickomesquita** [comment]
Or "after manufacturing"... beeing semantic dumb !@% here... 
Also have some other request for create a possibility of Inspect after each or some steps, in workflow manufacturing...

As well as inspect after receiving materials.... Actually is possible as default only before..

![image](https://user-images.githubusercontent.com/38265198/74947985-69ba1480-53da-11ea-847d-92f7928871d0.png)
