### ISSUE TITLE
Rate Change on Exchange Rate revision

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#15489]
As suggested by the ERPNext User.

1. When a person is preparing a quotation then its ideal that the Selling price changes according to the change in the exchange rate but in case of Delivery Note or Sales Invoice this logic would not work since already the prices are locked in a Sales Order.

1. Also in Sales Order if the selling price or the price in USD or foreign currency changes this could be an issue since the quotation could be for certain price and later when the conversion rate changes the final price would remain the same and hence I guess there is a need for the logic to be manually controlled atleast in case of quotations.

**Comment by joolsr** [comment]
I fully agree with that stated above
