### ISSUE TITLE
[Demo] Domain specific ERPNext demo sites

### ISSUE THREAD

**Issue by pratu16x7** [frappe/erpnext#15488]
Manufacturing and Services (more to come)

- [ ] Masters creation
- [ ] Transactions
- [ ] Update state of random transactions, at various stages

- Humans and items relatable, IMAGES, online datasets.
- Take on a particular (and interesting!) use case to make it easier to create a flow Eg. Hogwarts for Education

**Comment by kennethsequeira** [comment]
Live on: https://erpnext.com/demo for Manufacturing, Retail, and Services.
