### ISSUE TITLE
Console log: Uncaught TypeError when clicking company

### ISSUE THREAD

**Issue by Yemeni** [frappe/erpnext#15480]
Uncaught TypeError: Cannot read property 'position' of undefined when clicking the company in the company list after installation

Steps to reprodouce:
1. make new erpnext installation 
2. complete the setup
3. go to http://:8000/desk#List/Company
4. click on the company
5. the bug happens (also with Administrator account)

Version number tried on:
ERPNext: v11.x.x-develop (63ebeb4) (develop)
Frappe Framework: v11.x.x-develop (ffcc3fc) (develop)

**EDIT:**
Tried it also in version:
ERPNext: v11.0.3-beta.2 () (staging)
Frappe Framework: v11.0.3 () (staging)

bug:
chrome console log
```
libs.min.js?ver=1537732776.0:11305 Uncaught TypeError: Cannot read property 'position' of undefined
    at libs.min.js?ver=1537732776.0:11305
    at Array.map (<anonymous>)
    at ChartComponent.animateElements (libs.min.js?ver=1537732776.0:11304)
    at ChartComponent.update (libs.min.js?ver=1537732776.0:11180)
    at libs.min.js?ver=1537732776.0:10809
    at Map.forEach (<anonymous>)
    at AxisChart.render (libs.min.js?ver=1537732776.0:10808)
    at AxisChart.update (libs.min.js?ver=1537732776.0:10771)
    at libs.min.js?ver=1537732776.0:10748
```
firefox console log
```
[Show/hide message details.] TypeError: d is undefined[Learn More] libs.min.js:11305:5
animateElements/newPos<
http://...:8000/assets/js/libs.min.js:11305:5
map self-hosted:292:17 animateElements
http://...:8000/assets/js/libs.min.js:11304:17
update
http://...:8000/assets/js/libs.min.js:11180:23
render/<
http://...:8000/assets/js/libs.min.js:10809:50
forEach self-hosted:3884:9 render
http://...:8000/assets/js/libs.min.js:10808:4
update
http://...:8000/assets/js/libs.min.js:10771:4
draw/<
http://...:8000/assets/js/libs.min.js:10748:6

```
![image](https://user-images.githubusercontent.com/4777388/45933239-9245a100-bf91-11e8-86d1-18e0081bb1f5.png)

**Comment by kennethsequeira** [comment]
Looks like it was fixed:

![image](https://user-images.githubusercontent.com/33246109/48068791-ca2f3d80-e1f9-11e8-9416-c859dfe89ca2.png)

**Comment by kennethsequeira** [comment]
@Yemeni can't do that, unfortunately 😅.

However, do upgrade and check.

**Comment by Yemeni** [comment]
> @Yemeni can't do that, unfortunately 😅.
> 
> However, do upgrade and check.

https://github.com/frappe/erpnext/pull/15854 
here is the fix, it's moved to frappe framework here:
https://github.com/frappe/frappe/pull/6453
