### ISSUE TITLE
Cannot see Calendar - v11, staging branch

### ISSUE THREAD

**Issue by azharul-islam** [frappe/erpnext#15486]
I also checked beta.erpnext.com and the same issue exists there.
![erpnext-calendar-issue](https://user-images.githubusercontent.com/38819502/45969578-c7f39400-c03c-11e8-995d-67fa79dcd7b0.gif)

**Comment by TaiLouis** [comment]
Hi @azharul-islam . did you see any old version have this feature? Maybe Frappe didn't create calendar view for this page yet. You can search  Calendar View and create new Calendar View for your own.

**Comment by Anurag810** [comment]
fixed by #6607 will be merge soon
