### ISSUE TITLE
Print Without Amount option in Delivery Note doesn't hide Discount Amount 

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#15494]
Hi,

The 'Print Without Amount' option in the Delivery Note doesn't hide the Discount Amount field! All fields related to Amount should be hidden 

Please help fix this 

Thanks

**Comment by kennethsequeira** [comment]
Exists in ERPNext: v10.1.58 (master)

Frappe Framework: v10.1.51 (master)
