### ISSUE TITLE
[Proposal] Support Enhancements and Service Levels (SLA)

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#15493]
- Support Team (Employee Group)
    - Issue Criticality (new doctype)
        - Keywords (for auto selection)
    - Service Level
        - Issue Criticality 
        - Employee Group
        - Applicable Hours (from / to)
        - For holiday or working day 
        - Holiday list 
        - Response time (time / unit) example (3, days) or (3, hours)
        - Resolution time (time / unit) example (3, days) or (3, hours) 
    - Support Contract Template
        - Service Level (child table)
    - Support Contract
        - Default Contract (check)
        - Customer (if not default)
        - Support Contract Template
        - Service Level (child table)
        - Start / End Date
    - Issue 
        - Issue Criticality (select default based on keywords, or global default)
        - Service Level (auto selection basis of criticality and customer)
        - Service level status (fulfilled / not fulfilled)
        - Hours to respond (auto calculate every few mins)
        - Hours to resolve 
---

**Comment by netchampfaris** [comment]
https://github.com/frappe/erpnext/pull/16828
