### ISSUE TITLE
[bug] overlapping table headers with content from the above row when creating pdf

### ISSUE THREAD

**Issue by ioweb-gr** [frappe/erpnext#15504]
Hi, 

I'm again facing the issue with overlapping content in table headings when creating a pdf from a quotation. I haven't been able to resolve it with styles.

![image](https://user-images.githubusercontent.com/20220341/46076890-a0fda500-c197-11e8-95db-7baddaab885b.png)

**Comment by ioweb-gr** [comment]
I have tracked this to be a bug with wkhtmltopdf tracing back to 2014. I think if it hasn't been solved after 5 years it will never be solved https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1524. This in turn seems to be traced back to a core third party component from webkit and a relevant issue is here https://bugs.chromium.org/p/chromium/issues/detail?id=24826. 

Proper formatting of pdf documents is an important issue for any company that requires repeating headers in invoices and the invoices need to show detailed descriptions as they can span many lines. 

I personally wouldn't consider a company that sends documents like this a serious company and I haven't seen it in any local competitor ERPs obviously using other libraries. I mean in simple terms I would think, "these guys can't fix their own system, how can they fix mine?" 

Perhaps it's possible to consider adding another alternative library for PDF creation instead of wkhtmltopdf.

**Comment by hadishakir** [comment]
Adding the below code to print format custom css resolved it for me 
`
@media print {
    .print-format [data-fieldtype="Table"] {
        overflow: visible !important;
    }
}
`

**Comment by earljessee** [comment]
@hadishakir Was this ".print-format" class on the body? Table? Containing Element?

**Comment by hadishakir** [comment]
@earljessee html body div.print-format-gutter div.print-format

**Comment by moe01324** [comment]
Seems like this issue is still valid. :(

Neither an update to latest wkhtmltopdf (12.6) nor any of the multiple suggestions within https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1524 solved my issue. 

Anybody else had the issue and found a workaround?

**Comment by francisjervis** [comment]
I just encountered and resolved this issue. For me, it was tables wrapped in a Boostrap table-responsive div that were overlapping & removing that fixed it.

**Comment by ankush** [comment]
Issue with html to PDF conversion. Nothing much we can do, there's new print format builder that uses weasyprint instead of wkhtml that seems to be working better for these edge cases. Closing for now.

**Comment by ioweb-gr** [comment]
@ankush How do we enable the weasyprint instead of wkhtml?
