### ISSUE TITLE
Enhancement - No Lead Information field present

### ISSUE THREAD

**Issue by joolsr** [frappe/erpnext#15508]
Issue seen on using current Master or V11 Staging and verified on beta.erpnext.com

Using the Leads functionality, there is not a field to record rough notes on a potential requirement or interest. When we exhibited at a show recently, we entered all contact with show visitors as Leads but we could only add a quick note of their interest in the Communication rather than on the Lead. 
This meant that it was difficult to get a report with Lead, Company, and potential interest as the recording of the potential interest was made in the Communication field linked to the Lead and not on the Lead doctype itself.

This is a very simple enhancement where one new Text field is required, and the Leads Report can be tweaked to include this too. I am not a developer so cannot create a PR myself.
 @chdecultot Would you be able to help here after your sterling work to improve the CRM capabilities for events, and meetings ?

**Comment by chdecultot** [comment]
Hi @joolsr,

I do agree that a "Note" or "Information" text field is missing in the lead. I have had the same experience as you.
It is true we could use the "comment" section but it is, in my opinion, great for quick contextual comments, but not great for general comments regarding the Lead itself.

What about adding a new text editor field in a new collapsible section below the follow-up section ?
Something like that:

![image](https://user-images.githubusercontent.com/4903591/46090628-6bfe4c00-c1b1-11e8-824a-878cb952d072.png)


Let's see how it could be included in the lead details report if the text is quite long, but it should be possible.

Let me know your thoughts and I'll be happy to make a PR for this.

**Comment by joolsr** [comment]
Thanks Charles for your ideas. This was more or less my thinking too re the text editor field. When we recorded notes on Leads they were generally quite short, say a few lines long at most. If you could use a smaller text editor it may work. But your plan with the collapsible section is fine. 
The report needs to show this info where it may be wrapped in a column so that it should fit nicely on a A4 page ..

**Comment by chdecultot** [comment]
Hi @joolsr,

I just submitted a PR.
Because of the multiple use cases, I prefer to propose the usage of a text editor instead of a small text.
It shouldn't be an issue for you I guess.

Please take a look at the report. I used a big text, but you can imagine how it would be with a few lines.

Let me know if that's ok for you.

Have a nice evening!

**Comment by joolsr** [comment]
Yes this looks great as it is. many thanks again

**Comment by joolsr** [comment]
I think we can close this now
