### ISSUE TITLE
Insufficient permissions for Marketplace Settings Marketplace Settings

### ISSUE THREAD

**Issue by cruseros** [frappe/erpnext#15500]
Every time I enter into ERP I got this message "Insufficient permissions for Marketplace Settings Marketplace Settings".

I am using Google Chrome. Other colleagues report same situation.

![image](https://user-images.githubusercontent.com/39415541/46065711-1dca5800-c173-11e8-9cbd-d23bbdf5e622.png)

I did not add anything in my user configuration and I could not find any option to disable it.

Regards.

**Comment by unmesh87** [comment]
@cruseros,

Go to Setup >> Permissions >> Role permissions manager. Or directly search in Awesome Bar.

![screenshot from 2018-10-25 14-25-43](https://user-images.githubusercontent.com/20383222/47488416-f6de6f00-d861-11e8-98ad-61bda8b13b0d.png)

- Select : Document type >> Marketplace settings.

- Select : Role(for which market place is allowed)

At the bottom of the page, find  button "**Restore Original Permissions**".
