### ISSUE TITLE
Automatic Material Requests: Sending them to specific user

### ISSUE THREAD

**Issue by RSKROGER** [frappe/erpnext#15511]
Hi,

Automatic re-order material requests and transfers should be assignable to specific users or specific roles. Ideally, you should be able to assign a specific product category or specific item to a user or role. Therefore, the user responsible for a product or product category will get the automatic material requests sent directly to them when a purchase or transfer is needed.

Can we get this feature implemented?

Regards,

Roger

**Comment by yadavyk** [comment]
Please refer this : [Automatic Material Request](https://docs.erpnext.com/docs/v13/user/manual/en/stock/stock-settings#10-automatic-material-request)
