### ISSUE TITLE
Asset Tree

### ISSUE THREAD

**Issue by Katsuchiyo** [frappe/erpnext#15528]
Hi,

I'm new to ERPNext, but the software looks amazing! A lot of functionalities, which are open for free to everyone. Since I've got a background in EAM (Enterprise Asset Management) I'm especially interested in the Maintenance module.

When maintaining Assets I'm used to build an "Asset Tree". Unfortunately, I noticed it isn't currently possible. Is it possible to create an Asset Tree manual by code? Does anyone else encountered this issue and does have a solution?

Thanks, Simon

**Comment by yashodhank** [comment]
@Katsuchiyo Welcome to community!
Kindly follow community guideline for posting issues.
Ask questions and seek assistance at https://discuss.erpnext.com
Thanks
