### ISSUE TITLE
Company Sales Chart NOT rendering properly when Goal is set to 0

### ISSUE THREAD

**Issue by SaiFi0102** [frappe/erpnext#15537]
When goal is not set or set to 0 then the Company Form Dashboard Chart doesn't render properly until an update (for example by a resize event) is run. See the GIF:

![companychart](https://user-images.githubusercontent.com/328330/46257196-5a79b480-c4cf-11e8-97e3-bda279abb50d.gif)

Debugger:
![image](https://user-images.githubusercontent.com/328330/46257217-97de4200-c4cf-11e8-9d7b-89546895db98.png)

**Comment by surajshetty3416** [comment]
Looks like the issue has been fixed
![company_chart](https://user-images.githubusercontent.com/13928957/56803816-59c8b700-6841-11e9-9ca0-d5eb423e5698.gif)
