### ISSUE TITLE
Variant items could not auto listed in the required items

### ISSUE THREAD

**Issue by kyholdings** [frappe/erpnext#15535]
Hi Everyone

I have tried several time to make work order from sales order.
But it looks like all variant items could not auto listed in the required items of work order.

Who could help me to fix such issues?

Thanks and best wishes

RE: Installed Apps
ERPNext: v11.0.3-beta.2 () (staging)

Frappe Framework: v11.0.3 () (staging)

**Comment by sharmanakul** [comment]
checked on v13.14

created a BOM with variant item as required item
created sales order for the BOM
created work order from the sales order.

Result
the variant item appeared in the work order required item table.
