### ISSUE TITLE
Trial Balance for Party Report

### ISSUE THREAD

**Issue by mosabamf** [frappe/erpnext#15549]
Dears Support

Good morning

This is an issue in the report "Trial Balance for Party" you can only view party types "Customer, Supplier" while it should fetch all Party types Standard and Customized Ones, 

May you please support?

Thanks

![image](https://user-images.githubusercontent.com/21178114/46279738-46cf5c00-c56a-11e8-82f2-c9a12d07d2e5.png)

**Comment by PawanMeh** [comment]
Check the latest version, re-open if it is still an issue

![tb](https://user-images.githubusercontent.com/20460498/47280895-2c7f2000-d5f6-11e8-9fe6-6ab885dae7ed.png)
