### ISSUE TITLE
[Bug] Print format style settings state changed when switched to custom and back

### ISSUE THREAD

**Issue by azharul-islam** [frappe/erpnext#15558]
v11.0.3 (staging)

![screen-recording-2018-10-02-at-10 45 10-am](https://user-images.githubusercontent.com/38819502/46335693-f1aa4d80-c630-11e8-89d9-a5d5d3219583.gif)

**Comment by shreyashah115** [comment]
@azharul-islam It's not a bug actually, if you enable Custom Format, the style settings are not applicable.
