### ISSUE TITLE
Stock Entry Cancellation Bug for Serialized Items

### ISSUE THREAD

**Issue by vwithv1602** [frappe/erpnext#15553]
After a serialized item is delivered to a customer, cancellation of Stock Entry which was done previously is possible. But this shouldn't be allowed as the item is not available with us. After canceling the Stock Entry, the serial number (initially with empty warehouse as it got delivered) has warehouse assigned and is further allowing all the operations like repacking or material transfer.

Steps to replicate:

1. Create a Stock Entry Repack for a serialized item. Say serial number is **S001** and entry id is **STE-00001** and it is in a warehouse **Stores**
2. Create a Delivery Note by putting that serial number **S001**
3. Check **Warehouse** in **Serial No** List and it will be empty as it got delivered.
4. Cancel **STE-00001**. (This is allowing but shouldn't allow)
5. Check **Warehouse** again in **Serial No** List and it shows **Stores**
6. Now, we can do further operations on this serial no which physically doesn't exist with us.

What should be done (as per my knowledge):
Once, the serialized item is delivered, do not allow cancellation of the previous Stock Entries.

**Comment by vwithv1602** [comment]
While doing a repack, did you choose the same warehouse or different warehouse?
Please choose the same warehouse to replicate.
The repack entry made before creation of DN should be something like this. (You may ignore the barcode field - first column. It just auto populates the item code and source warehouse)
![image](https://user-images.githubusercontent.com/29653756/46448364-183cc580-c7a4-11e8-80dc-31cfb292d984.png)

**Comment by rkurungadam** [comment]
Yes, Repack Entry has same warehouse
