### ISSUE TITLE
Purchase invoice can't submit if Update Stock is checked 

### ISSUE THREAD

**Issue by Suprazz** [frappe/erpnext#15564]
If in a invoice we check Update Stock and we have stock item in the invoice and other lines that don’t include the item number (simply an expense that pass on the same invoice) the submit fail.

So we can't update stock with this invoice if there are "non item" lines.

**Comment by crescent28** [comment]
Do you mean this that you do not add an item in the next rows and only add the rates? 
![screen shot 2018-10-18 at 11 42 00 am](https://user-images.githubusercontent.com/41110073/47134579-e14dd000-d2ca-11e8-8125-a84b83cf6372.png)

**Comment by Suprazz** [comment]
No. If you select update stock and then, on the line number one I add an item with item code, and on row 2, don’t put an item code, just the item name, when you try to submit the invoice it gives you an error like this: 
![image](https://user-images.githubusercontent.com/3640711/47155486-d6874100-d2b2-11e8-8633-fb841aece545.png)

![image](https://user-images.githubusercontent.com/3640711/47155495-dab35e80-d2b2-11e8-8b2d-dfa73cc9fcff.png)

If update stock is unchecked, it's possible to save the invoice and everything is fine.

**Comment by Salmanmulani** [comment]
Item field is a Mandatory field so if you don't want this error message to popup then please uncheck mandatory field for Item field in customize form for Purchase invoice. Also please check below GIF for more help.

![git](https://user-images.githubusercontent.com/42264299/47212197-26e6c780-d3b5-11e8-98c8-b74eea295475.gif)

**Comment by Suprazz** [comment]
It's not the solution. Yes it still need to be mandatory. It's juste a problem when you mix in the same invoice, lines with item code and lines with no item code.
