### ISSUE TITLE
No permission for Employee

### ISSUE THREAD

**Issue by khalid040414** [frappe/erpnext#15568]
I DONT KNOW WHAT HAPPENED, HOW COME I DONT HAVE PERMISSION TO CREATE EMPLOYEE
AND THE EMPLOYEE NUMBER INCREASE AND  CANNOT SEE THE EMPLOYEE LIST

**Comment by yashodhank** [comment]
@khalid040414 First ask such questions before opening new issue to avoid delays and unnecessary loss of time for devs. if bug is confirmed on discuss then feel free to open new issue with all details.
go to https://discuss.erpnext.com
