### ISSUE TITLE
UOM Issue - Flowing from BOM to Production Order and to Stock Entry

### ISSUE THREAD

**Issue by nick9822** [frappe/erpnext#15563]
When we add an item in the BOM table it fetches default UOM and we have an option to change the UOM. So if we change the UOM we should be able to use it in Production Order/Work Order and associated Stock Entries.

Actual Behavior:
It allows us to change the UOM in BOM but its not carrying those UOMs to the Production Order/Work Order. Required Items in Production order/Work Order also dont have UOM field. When we do Stock Entry it refers to the Required Items table in Production Order/Work Order and it fails to find UOM there so it puts the default UOM set on the item.

Expected Behavior:
It should carry UOM to Production Order/Work Order. Production Order/Work Order should have the UOM field mapped with the BOM Items UOM. So we create Stock Entry it can UOM to look for.

**Comment by nick9822** [comment]
@djpalshikar Thanks for the response. What you are saying is correct, but this is not always the case in the manufacturing where BOM could be made in different UOMs than default one. So here there should be conversion of qty in case of different UOMs.

**Comment by djpalshikar** [comment]
I agree, you are right.

**Comment by nick9822** [comment]
Sorry for the inconvenience. I am closing this, as conversion is in place, we had missing UOM's in Item.
