### ISSUE TITLE
Debian 9 PDF format 

### ISSUE THREAD

**Issue by ShehataGhattas** [frappe/erpnext#15562]
Dear team, i have been noticed that since i install the app on debian 9 it has an issue with PDF format , every thing look great and the file preview on the browser look good but once PDF generated is look bad no letterhead not format, the the below images
https://1drv.ms/f/s!AgoqEeylXZ4k9TFeYtMOcvDv6jbm

**Comment by joolsr** [comment]
I'm guessing here but believe PDF creation is made via the wkhtmltopdf library. In the past this library has had to be modified as certain versions did not always create PDF's correctly. 
You may want to try a newer WKhtml version. Its not something likely to be wrong with ERPNext really a limitation in respect of the os version you are using. 

Please post on the forums as you may get a better response

**Comment by ShehataGhattas** [comment]
Thanks @joolsr .
i have done upgrade for wkhtmltopdf  and now every thing is perfect thanks for your support.

**Comment by joolsr** [comment]
Very pleased to help. It was only a guess but obviously can good one 😉
