### ISSUE TITLE
 Español (México) - ERPNext Translator

### ISSUE THREAD

**Issue by franciscobuendiao** [frappe/erpnext#15575]
Following messages are not listed in https://translate.erpnext.com/view?lang=es-MX

In "Quoted Item Comparison"

Tools: Herramientas
![comparacion_de_articulos_de_cotizacion](https://user-images.githubusercontent.com/25084259/46422830-c2f8a980-c6fa-11e8-8509-250bfa2f7664.jpg)

(1) Set Default Supplier: Establecer Proveedor Predeterminado
(or 2, just) Set Default Supplier: Establecer Proveedor
![comparacion_de_articulos_de_cotizacion_2](https://user-images.githubusercontent.com/25084259/46423116-6cd83600-c6fb-11e8-9976-bc9d56053153.jpg)

Using "Translations" in Setup module, can't translate: Supplier Addresses And Contacts
![supplier_addreeses_and_contacts](https://user-images.githubusercontent.com/25084259/46423473-364eeb00-c6fc-11e8-9fa2-ad544e04e3dc.jpg)

**Comment by federicocalvo** [comment]
Hola Francisco, nosotros estamos constantemente actualizando el español ES, y somos de argentina, porque ya había usuarios que lo estaban actualizando.

No es conveniente que sigamos un solo ES por más que haya pequeñas diferencias así tenemos un buen español en ERPNext?

Saludos!
Federico

**Comment by franciscobuendiao** [comment]
> No es conveniente que sigamos un solo ES por más que haya pequeñas diferencias así tenemos un buen español en ERPNext?

De acuerdo! 
Al menos las 2 primeras, "Tools" y "Set Default Supplier" no aparecen en ningún catálogo en español.

Saludos.

**Comment by kennethsequeira** [comment]
Hey guys!

You're all welcome to contribute via the new translation portal which has been up for some time now: https://translate.erpnext.com

**Comment by federicocalvo** [comment]
Hi @kennethsequeira , i am waiting a response for this precisely https://github.com/frappe/erpnext/issues/18607
