### ISSUE TITLE
printing "Statement of Account" - error in comment of payment entry

### ISSUE THREAD

**Issue by vrms** [frappe/erpnext#15599]
- I have a **Sales Invoice** for a customer worth **$15,354.72**
- Customer sends a **50% payment** of amount **$7,677.36**
- Even though on my side local bank fees are being deducted and likewise a smaller amount ($7,669.02) actually hits my bak account **I am allocating the entire remittance sum against the Invoice** and write off the difference (as bank fees expense).
----
- This all works correctly in terms of accounts and values. 
- Only when I am generating a "Statement of Account" for that customer (printing the General Ledger filtered by that Customer) inside the comment box for the Payment Entry there is a mistake in regards to the amount allocated against the Sales invoice. The actual amount received on the bank account ($7,669.02) is mentioned while the remittance ammount ($7,677.36) should be mentioned.

 ![grafik](https://user-images.githubusercontent.com/7608112/46538918-802f0100-c8b5-11e8-9e9c-ba2362bb811d.png)

- as mentioned this does not falsify any actual numbers but certainly may cause irritation at some point

**Comment by deepeshgarg007** [comment]
@vrms this issue has been fixed. If the issue still exists please reopen
