### ISSUE TITLE
V11 pdf file don't apply css and image

### ISSUE THREAD

**Issue by gmplab** [frappe/erpnext#15598]
step:
1.Use https://beta.erpnext.com demo v11,
2. open sale order SO-00002
3. the preview as well.
3. Click the "PDF" button.
[SO-00002.pdf](https://github.com/frappe/erpnext/files/2450395/SO-00002.pdf)

**Comment by gmplab** [comment]
<img width="553" alt="s01" src="https://user-images.githubusercontent.com/1935044/46537745-a029e900-c8e4-11e8-8ab0-2df80a95c9f6.png">

**Comment by asanodaria** [comment]
it's reproducible.
![image](https://user-images.githubusercontent.com/36321437/47412352-2c635980-d789-11e8-8989-33c13cdc514f.png)

**Comment by gmplab** [comment]
install libssl1.0-dev package solve the problem
