### ISSUE TITLE
Companies have a gender

### ISSUE THREAD

**Issue by barredterra** [frappe/erpnext#15609]
ERPNext: v10.1.56 (master)
Frappe Framework: v10.1.50 (master)

## Problem
DocType CRM > Lead contains a "gender" field that is displayed even if organization_lead is checked. 

## Expected
Organizations do not have a gender. `gender` should not be visible.

## Fix
`gender` field should have `"depends_on":"eval:!doc.organization_lead",`

**Comment by crescent28** [comment]
![crm lead](https://user-images.githubusercontent.com/41110073/46866763-4a06f980-ce40-11e8-91fe-90dd50ea9753.png)
