### ISSUE TITLE
Import DataTable Using Custom Script

### ISSUE THREAD

**Issue by harikishorsingh060** [frappe/erpnext#15604]
I have installed Frappe datatable from the erpnext documentation. my issue is that datatable not showing proper.
frappe.require([ 
         "/assets/frappe/css/frappe-datatable.css",
          "/assets/frappe/css/hljs.css",
         "/assets/frappe/js/lib/clusterize.min.js",
         "/assets/frappe/js/lib/Sortable.min.js",
         "/assets/frappe/js/lib/highlight.pack.js",
         "/assets/frappe/js/lib/frappe-datatable.js"
         "/assets/dist/frappe-datatable.css",
         "/assets/frappe/css/hljs.css",
         "/assets/frappe/css/index.css",     
]);

**Comment by kennethsequeira** [comment]
@harikishorsingh060 the description of the issue is very vague.

Kindly be more precise in describing what exactly is the issue here.

Also, try posting this on the forum first, if required the issue can be reopened.

https//discuss.erpnext.com

https://discuss.frappe.io
