### ISSUE TITLE
[ENH Proposal] Plaid integration & Bank reconciliation redesign

### ISSUE THREAD

**Issue by chdecultot** [frappe/erpnext#15600]
The below document is an initial proposal for an integration with [Plaid](https://plaid.com/) and an enhancement to the current reconciliation tools.

**Current functionality**

ERPNext currently proposes two methods for bank reconciliation:
1. Manual method through the DocType “Bank Reconciliation”
This method fetches all non-reconciled payments and gives the possibility to define a clearance date for each.
It allows quick data processing, but there is no link with an actual bank statement entry.

2. Bank statement import through the document “Bank Transaction Entry”
This is a new feature of version 11.
It gives the possibility to import a bank statement in csv or xlsx format and proposes three options:
- Match transactions to invoices
- Create a new payment 
- Reconcile payments.

This new interface has several issues among which:
- The UX still needs some work: there are no error/indicator messages (I had to debug to find out the date format in my settings was incorrect) and the whole document interface is hard to understand.
- It doesn’t provide an easy interface for reconciliation: you have to know the document to be reconciled in order to select it - That doesn’t match with a normal usage in production.

**Goal**

There is a need to integrate Plaid into ERPNext to be able to automatically synchronize one or several bank accounts by importing their bank statement entries into ERPNext.

This import should be considered similar to a manual bank statement upload and allow an easy reconciliation of existing payments in the same interface for an optimized UX.

**Proposal**

In order to achieve this goal, I am proposing two steps:
**1. Separate the reconciliation tool from the bank transaction entries**

 a. Use or create different DocTypes for:
  - Bank
  → Has one or several bank accounts

  - Bank Account
   Recaps all bank accounts detained by a company
    → Directly linked to Company
    → Directly linked to a GL Account
    →  Directly linked to one or several Mode of Payments

   - Bank Transaction Entry
   Aggregate all transaction entries for all bank accounts
   The creation of a Bank Transaction Entry can be done manually, through a bank statement import or via a synchronization tool (Plaid, etc…)
   → Directly linked to a Bank Account
   → May have optional fields activated based on the synchronization tool chosen (to store specific information linked to Plaid or another synchronization tool)
   → Directly linked to the payment entries/journal entries after clearance

→ Adding a new DocType for Bank Accounts gives the possibility to change the Mode of Payment DocType to link it to a Bank Account instead of a GL Account directly (Not in the scope of this proposal, but would be a UX enhancement).

 b. Redesign the current Bank Statement Transaction Entry Doctype

In my opinion, the current bank statement transaction entry doctype is not user friendly and difficult to use in production.

With a proper separation of data, we could move this DocType to a Page (more flexible) with two main steps:
1. Data import
The first step should consist in being able to import data for a specific bank account and between two dates (similar to the actual Bank Reconciliation).

The user should be able to import a csv/xlsx bank statement or launch a synchronization run from this first step.
All imported data will be stored in the Bank Transaction Entry.

Design example (The straight line) shows the limit between each step.
The next step is only displayed when the previous step mandatory action are completed.
![image](https://user-images.githubusercontent.com/4903591/46536135-dac45f00-c8ad-11e8-919c-2ec0566f6d26.png)

2. Reconciliation
Once all transaction entries have been imported, the page should provide a section to allow several actions for each transaction entry:
      a. Reconcile existing payment entries
      b. Create a new payment entry/journal entry (automatically cleared)
      c. Match with a sales/purchase invoice => create the corresponding payment entry (automatically cleared) .

 The clearance information will be stored in the payment entry, identically to the existing system, but a reference to the linked payment entry will be added in the bank transaction entry.

I see two options using Frappe’s current components:
a. One table with the bank transactions - One table with the payment entries
Users select the matching transactions in each table and then click on a “Match” button:
Matched transactions are automatically removed from the table.
![image](https://user-images.githubusercontent.com/4903591/46536175-fa5b8780-c8ad-11e8-9671-d4595b39d560.png)

An additional modal dialog should be configured to handle non straightforward cases (multi to multi assignments/ Amounts not matching/ etc...)

b. The other option is to have only the above first table and propose the payment entries in a table within the child entry (Not a child table, just a custom HTML display):
![image](https://user-images.githubusercontent.com/4903591/46536230-2414ae80-c8ae-11e8-90ab-f1d70f3f7528.png)

Please let me know which option you prefer or if your have any other design idea.

ERPNext will therefore have two tools: the Bank Reconciliation for manual reconciliation and the Bank Statement Transaction Entry for semi-automatic reconciliation.

We need to find an agreement on the Doctype/Page names to be used. 
What about the following renaming:
* Bank Reconciliation → Manual Bank Reconciliation ?
* Bank Statement Transaction Entry → Bank Reconciliation or Bank Reconciliation Dashboard ?

**2. Integrate Plaid with ERPNext**

The plaid integration will be quite straightforward with the following output

a. A “Plaid Settings” DocType will allow configuring your Plaid integration. Users should be able to allow an automatic synchronization at a defined interval (every hour or every day).

b. The Plaid API credentials will be stored in a dedicated doctype but the system will also read them from site_config.json (to allow Frappe and Parsimony to propose to use their API credentials and rebill only part of the price to their users).

c. All transactions will be synchronized as Bank Transaction Entries to be used in the redesigned Bank Transaction Tool to be available for reconciliation.

d. Synchronization errors should be sent to the general error log or a dedicated log gathering error and success messages (To be defined during development)

@parsimonyERP
@rmehta : I allow myself to tag you since you already discussed this issue with Michael. Would you or @nabinhait be available for a call to discuss this feature over the next days/weeks ? It would be really great to design this feature correctly before I start any development (if you're ok with it of course!)

**Comment by parsimonyERP** [comment]
@chdecultot I think that this is an excellent write-up.  Plaid offers the ability to bring in bank, credit card, and brokerage transactions from ~95% of US banks and the 5 largest banks in Canada.  This is a feature that everyone on QBO and Xero has gotten used to and will be looking for if they upgrade to a full-featured ERP system.  Thanks for the great write-up we would love to see this project more forward.

**Comment by OneiricIT** [comment]
@chdecultot great stuff - just a thought with bank rec, to have beginning and ending statement balance shown. I am looking forward to the option to not have to enter the clearing date against each transaction and simply check a box 👍

**Comment by chdecultot** [comment]
Hi @OneiricIT,

Yes I do agree that having a beginning and ending statement balance shown would be nice. I'll keep it in mind for the final design.

**Comment by kennethsequeira** [comment]
@chdecultot can we close this since it has been merged? 😄
