### ISSUE TITLE
Income variance report

### ISSUE THREAD

**Issue by asbasawaraj** [frappe/erpnext#15617]
Currently, a budget can be set for cost center and expense ledger combination and planned vs actual expenses can be analyzed using 'Budget Variance Report'.

Similarly, a feature to set a target for an income center and income ledger along with a report for planned vs actual income analysis (similar to budget variance report)is needed.

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.

**Comment by kingraphaii** [comment]
Hi @asbasawaraj , checking on v14 dev, seems the feature isn't available yet?
