### ISSUE TITLE
Permission issues creating Opportunity from Lead

### ISSUE THREAD

**Issue by gmaheshkumar** [frappe/erpnext#15624]
Dear Team,
I;m not able to create "Opportunity" from "Lead" in CRM module. System is throwing  "Not permitted"  error with an error message "Insufficient permission for Opportunity". However I'm able to create "Opportunity" from "Customer". Screenshots attached. 

Another strange thing I noticed is that my error log list is empty

I have administrator privileges

Thanks,
Mahesh
![image](https://user-images.githubusercontent.com/25460331/46607951-7d841400-cb20-11e8-8bbc-738cdf75f30b.png)

![image](https://user-images.githubusercontent.com/25460331/46607878-3a29a580-cb20-11e8-8850-81f24196c749.png)

**No error log**
![image](https://user-images.githubusercontent.com/25460331/46608013-ca67ea80-cb20-11e8-98a2-0e3b3485aef7.png)

**Version**
![image](https://user-images.githubusercontent.com/25460331/46608048-f2efe480-cb20-11e8-9064-630780707879.png)

**Comment by gmaheshkumar** [comment]
Permission problem seems to be resolved, I have reset the permission for "Opportunity" in role permission manager. 
Error log problem still exists

**Comment by joolsr** [comment]
Dear Mahesh
You would not actually see these sort of 'errors' in the error log. The error log shows error codes or when there are issues receiving/sending email for example. Permissions issues are no really errors as sometimes you will want to make these very tight for certain roles and/or individuals.
