### ISSUE TITLE
GST POS Invoice preview error

### ISSUE THREAD

**Issue by crescent28** [frappe/erpnext#15641]
Traceback issue while generating Sales invoice preview from POS

![pos invoice preview error](https://user-images.githubusercontent.com/41110073/46720310-d1603b80-cc8d-11e8-87e3-43878107b70c.png)
![gst pos invoice](https://user-images.githubusercontent.com/41110073/46720518-65ca9e00-cc8e-11e8-868e-85a1a79bec2d.gif)

**Comment by shreyashah115** [comment]
Not able to replicate,

<img width="1321" alt="screenshot 2018-10-24 at 12 41 37 pm" src="https://user-images.githubusercontent.com/17617465/47412754-33d73280-d78a-11e8-9eff-fbd6cd2deb85.png">

Please post the entire error traceback generated and open the issue again.

**Comment by asanodaria** [comment]
I got the jinja code in GST POS Invoice print format

[image](https://user-images.githubusercontent.com/36321437/47412761-38035000-d78a-11e8-9d00-3c0e7b7e785e.png)

**Comment by asanodaria** [comment]
https://beta.erpnext.com

Installed Apps
ERPNext: v11.0.3-beta.11 () (staging)

Frappe Framework: v11.0.3-beta.10 () (staging)

**Comment by shreyashah115** [comment]
@asanodaria That't not a bug, too actually, the beta.erpnext.com site's default country is set as United States and the GST POS Invoice print format is only applicable to country India, so you can ignore it.

**Comment by asanodaria** [comment]
@shreyashah115 That's true. But as an and user, we should not show <code> to user on screen.

**Comment by shreyashah115** [comment]
@asanodaria I agree. We shall fix it soon.
