### ISSUE TITLE
ERPNext v11.x.x integration with Shopify

### ISSUE THREAD

**Issue by ziagit** [frappe/erpnext#15649]
Hi everybody
It looks that shopify_erpnext app is no longer required to install , its built in erpnext itself.
but there is not any doc about how to set up.
I checked erpnext in github
master branch is in v10...
develop branch is in v12...
staging branch is in v11...
I switched to staging, then coppied all the credentials of private app from shopify and set them to shopify setting in erpnext.
now what I should do. do I need to configure webhooks in shopify? if so please how?
if not, why it not syncing?
thanks

issue in forum
https://discuss.erpnext.com/t/erpnext-shopify-integration/41654

**Comment by kennethsequeira** [comment]
Shopify Integration Documentation (v11 and above): https://docs.erpnext.com/docs/user/manual/en/erpnext_integration/shopify_integration
