### ISSUE TITLE
[v11] Problem with patch refactor_naming_series

### ISSUE THREAD

**Issue by adityaduggal** [frappe/erpnext#15645]
Hi,

We are getting this error on the patch in erpnext, this has been mentioned in forums and also in the comments as below:

1. See comments of https://github.com/frappe/erpnext/commit/a626d967c0938cc4498cfe2de809a440da7fc7fc
1. https://discuss.erpnext.com/t/many-many-error-when-switch-to-stage-and-migrate/40961/6

**Comment by shreyashah115** [comment]
Hi Aditya, have sent a fix for this. #15651
