### ISSUE TITLE
Show different UoMs in webshop

### ISSUE THREAD

**Issue by rasos** [frappe/erpnext#15655]
We have defined a cloud service package with two UoMs

- 1 Month
- 1 Year (factor 12)

as described here https://erpnext.org/docs/user/manual/en/selling/articles/Selling-in-different-UOM

However, in the ERPnext webshop, only the first UoM is shown with the article. Is there a way to show all UoM options? 

In the shopping cart, in the row of the article, the UoM is not shown, so the user does not know if the quantity chosen is per month or per year. How could this be achieved? 

![fairappsuomwebshop](https://user-images.githubusercontent.com/485723/46796057-f6b37f00-cd4b-11e8-9d80-0750aff0b881.png)

**Comment by parsimonyERP** [comment]
👍  Good observation.  We need this too.
