### ISSUE TITLE
[ERPNext V11 Bug] : Set Desktop Icons: When Unselect some of the already selected (set on desktop) items and save then it removes all icons from Desktop

### ISSUE THREAD

**Issue by asanodaria** [frappe/erpnext#15654]
Set Desktop Icons: When Unselect some of the already selected (set on desktop) items and save then it removes all icons from Desktop

Version:
ERPNext: v10.1.56 
Frappe Framework: v11.0.3 () (staging)

@umairsy 

![show_desktop_icons](https://user-images.githubusercontent.com/36321437/46795189-2a4fd280-cd67-11e8-974a-e1383eecb1b0.gif)

**Comment by umairsy** [comment]
Works fine on https://beta.erpnext.com. Can you please upgrade your ERPNext account to the latest version and check again?
