### ISSUE TITLE
Sales of Fixed Asset with Zero value - error on invoice value DR & CR values

### ISSUE THREAD

**Issue by Midi1985** [frappe/erpnext#15676]
I have a transaction related to a fixed asset sale. The book value of the fixed asset is Zero (0) & I want to sell this at a cost determined by the management. When clicked on the “Sell Asset” of the particular item, it goes to a new invoice & CR a/c is shown as “Gain/Loss on Asset Disposal” & DR to Debtors. I inserted the amount of the sales value, filled other mandatory fields & clicked submit. then it says DR & CR values are not matching & difference is so & so amount (the rate of the item that i put)
ls find attached screenshot of the error
![erpnext](https://user-images.githubusercontent.com/37651163/46915343-f36dfc80-cfb2-11e8-869d-19a1da9325e0.PNG)

**Comment by umairsy** [comment]
Can you please share the screenshot of the asset? Will be great if you could post it on the discuss forum. If it is validated as a bug, you could report it here, or reopen this same issue.

**Comment by Midi1985** [comment]
Dear,

Please find attached Screenshot as said & kindly resolve the issue.

**Comment by Midi1985** [comment]
I have never received a solution for my bug even after making lots of queries & sending screenshots. Lloking forward to a quick reply from Github or Erpnext team
