### ISSUE TITLE
Wrong currency symbol in Item Price list view

### ISSUE THREAD

**Issue by aldoblack** [frappe/erpnext#15675]
ERPNext: v10.1.52
Frappe Framework: v10.1.47

I noticed a little bug on Item Price doctype.

When I open the list of Item Price, the Rate is always on dollars **$**, but this is wrong because the last item is on **Euros** . See photo below...
![P1](https://discuss.erpnext.com/uploads/default/original/3X/f/a/fac64fc3fa08506fd0f54d05c4517c8fb42b0cc6.png)

But when I open the the doctype with the Item in **Euros** and go back it lists all the items in **Euros**.
![P2](https://discuss.erpnext.com/uploads/default/original/3X/e/2/e24e20e6e76618adbf94b69b792e3874776ef057.png)

**Comment by umairsy** [comment]
Hello,

Does issue still prevails after refresh? Just trying to validate if issue is related to cache.

**Comment by aldoblack** [comment]
> Hello,
> 
> Does issue still prevails after refresh? Just trying to validate if issue is related to cache.

Yes it does!

**Comment by shreyashah115** [comment]
Not able to replicate.

<img width="947" alt="screenshot 2018-10-24 at 12 29 33 pm" src="https://user-images.githubusercontent.com/17617465/47412183-93ccd980-d788-11e8-8f1d-c5fe3864742d.png">

**Comment by shreyashah115** [comment]
@aldoblack Have you added any custom fields?

**Comment by aldoblack** [comment]
> @aldoblack Have you added any custom fields?

Yes, I have added Custom fields.
