### ISSUE TITLE
Issue in email composer with the new Quill Text Editor

### ISSUE THREAD

**Issue by chdecultot** [frappe/erpnext#15670]
Hi,

In the email composer, if you choose an email template, the default "Dear Mr/Mrs..." should be replaced with your template.

With the new text editor, this text is just pushed to the bottom (below the email template text).

Example with a default template:

![image](https://user-images.githubusercontent.com/4903591/46874422-6eaba300-ce39-11e8-82e3-11569ce338bd.png)

ERPNext: v11.0.3-beta.10 () (staging)
Frappe Framework: v11.0.3-beta.8 () (staging)

**Comment by crescent28** [comment]
Yes right, there is one more issue regarding this new quill that it has removed the option of "Remove Formatting" if the content is pasted from some other source. Earlier version had this feature. 
![quill format](https://user-images.githubusercontent.com/41110073/46934566-d1897e00-d075-11e8-828f-3b9d4aea3969.png)
