### ISSUE TITLE
Manually enter USD to AED conversion rate : Error

### ISSUE THREAD

**Issue by crescent28** [frappe/erpnext#15682]
![screen shot 2018-10-15 at 1 10 09 pm](https://user-images.githubusercontent.com/41110073/46936470-1ca68f80-d07c-11e8-9cf1-c4f4d116f14f.png)

**Comment by shreyashah115** [comment]
Hi @crescent28 The currency exchange API used by the system has no records for currencies USD to AED conversions, hence, you might have to add it manually into the DocType Currency Exchange.
