### ISSUE TITLE
Request: Allow repeating of just header/footer in Print Settings

### ISSUE THREAD

**Issue by wbnn** [frappe/erpnext#15686]
![image](https://user-images.githubusercontent.com/44161644/46945295-12d15c00-d07d-11e8-9264-445242bea2e2.png)

It would be great if the "Repeat header and footer" option would be split into separate options in the Print settings. On the first page of a pdf document I’d like both footer and header, but to save space it would be great if I could repeat just the footer.

**Comment by wojosc** [comment]
+1 for me and many others :)

**Comment by artemartamonov** [comment]
Please reopen it
