### ISSUE TITLE
BUG - Account Receivable / Payable Print and PDF not showing Totals at the bottom

### ISSUE THREAD

**Issue by bibinqcs** [frappe/erpnext#15693]
I noticed a bug in the account receivables / payable, while trying to take a print or make a pdf it does not display the total row. 

refer pull request #15688 

Thank you

**Comment by umairsy** [comment]
It has been merged. Could you please check if it is fixed, so that we could close it?

**Comment by bibinqcs** [comment]
I just tested it and it works
