### ISSUE TITLE
Item page header bar, width between 768px and 991px (inclusive)

### ISSUE THREAD

**Issue by gbm001** [frappe/erpnext#15709]
The title bar of the Item page does funny things between the BS breakpoints at 768px and 991px (inclusive, tested in Chrome 69 and Firefox 62).

At first I noticed this on my test site running a V11 beta (pulled from a tag) plus custom apps, where it looks like this:
![image](https://user-images.githubusercontent.com/4930097/47017297-c6a01d80-d149-11e8-8cb0-dec1d0a639f5.png)
i.e. not too bad except that the blue dot indicator 'enabled' has dropped to the next line.

So I tried it on my other test site running pure develop, and it looks like this:
![image](https://user-images.githubusercontent.com/4930097/47017438-2a2a4b00-d14a-11e8-8ede-7faa2c07841a.png)
and here (probably due to the extra little 'new site' progress bar and/or the Help dropdown) the top bar has spilled over 2 lines and obscured the top of the item page.

**Comment by crescent28** [comment]
@gbm001 Can you provide the resolution that you are trying to check for the Title bar?

**Comment by gbm001** [comment]
I'm not sure I've understood your question right, but this happens whenever the width of the window is between 768px and 991px (inclusive). You may need a long item title.

**Comment by deepeshgarg007** [comment]
@gbm001 Closing this issue. If the issue still persists in latest version-13 or above then please reopen a new issue
