### ISSUE TITLE
Serial No. - Supplier not updated if Serial No. inwarded via Purchase Invoice.

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#15710]
I noticed that the supplier field under the serial no doctype doesn’t update if you use purchase invoice to update your stock. Although it works perfectly if purchase receipt is used, we were hoping that we can avoid using the purchase receipt altogether and opt to use purchase invoice as our main receiving document.

Replicating in gadgets.erpnext.com
Ref: https://discuss.erpnext.com/t/supplier-field-under-serial-no-doctype-not-updating/41842

**Comment by jigneshpshah** [comment]
Working on 
ERPNext: v10.1.61 (master)

Frappe Framework: v10.1.54 (master)

![image](https://user-images.githubusercontent.com/4900815/47426511-0a7ace80-d7ab-11e8-99f5-7bde156d1728.png)

Kindly close it.
