### ISSUE TITLE
Sales Analytics by Item does not export Item [BUG]

### ISSUE THREAD

**Issue by Tropicalrambler** [frappe/erpnext#15713]
Expected Behavior:  When exporting sales analytics listed by Item only, a .csv file is made available with all the items, quantity or value of sale, and a monthly rhythm.

Actual behavior: No items are downloaded when filtering by "Item"
<img width="1369" alt="screen shot 2018-10-16 at 9 36 42 am" src="https://user-images.githubusercontent.com/16600935/47028664-0a356000-d127-11e8-8992-8c9281a921df.png">

ERPNext: v10.1.48 (master)
Frappe Framework: v10.1.45 (master)

**Comment by deepeshgarg007** [comment]
Fixed #15589
