### ISSUE TITLE
Create Sales Order, Sales Quotation, Purchase Order, Purchase Quotation from Item List View [ENHANCEMENT]

### ISSUE THREAD

**Issue by Tropicalrambler** [frappe/erpnext#15715]
Actual Behavior:  User selects several Items for sale with filters in List View (or report view). If user wants to create a Sales Order or Sales Quotation for these items, as well as Purchase Order or Purchase Quotation user must manually enter each one.

Expected Behavior:  User selects several Items for sale with filters in List View (or report view). If user wants to create a Sales/Purchase Order or Sales/Purchase Quotation for these items, user just clicks a **Make** button and items are added to a Sales/Purchase Quotation or Sales/Purchase Order with a quantity of 1 of each, ready to add a customer and modify quantities.

- [ ] Add Make button to List View, with two items:
"Quotation With Selected"
"Sales Order With Selected"
"Purchase Quotation With Selected"
"Purchase Order With Selected"

- [ ] Add programming to select items listed in view as per active filters, and create a new Sales Quotation or Sales Order, as well as Purchase Quotation and Purchase Order, with one of each item.  User must enter customer or supplier at the very least, so user can save the created document.

- [ ] Validate that only sales items are added to sales type doctypes, and purchase items are added to purchase type doctypes. Only show a message notifying that "Item x, y, z was not added to Sales order because it is not a sales item"  however, the other items have been added in the background without slowing the user down.

**Comment by parsimonyERP** [comment]
👍

**Comment by sharmanakul** [comment]
how likely is it that all the items, which you want to select for the transaction, are on the same page?

**Comment by djpalshikar** [comment]
Some of the behavior has been accomplished by allowing for Copy-Paste from reports. This may not bee needed now
