### ISSUE TITLE
Sales Analytics Improvements - Add Item Name and Make Sortable

### ISSUE THREAD

**Issue by Tropicalrambler** [frappe/erpnext#15714]
Expected Behavior: When looking at Sales Analytics by Item or Item Group, the Item Code **and** Item name should be shown.
Also, each column header should allow sorting by ascending or descending.

Actual Behavior: Only Item code is shown in one column.
Columns cannot be sorted. User must export the data to sort outside in excel.

Fixes:

- [ ] Add Item Name column
- [ ] Add Sorting controls to column header

ERPNext: v10.1.48 (master)
Frappe Framework: v10.1.45 (master)

**Comment by parsimonyERP** [comment]
👍

**Comment by nabinhait** [comment]
Fixed via #15589
