### ISSUE TITLE
Option to turn off nagging notification of new version

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#15722]
Hi

There should be a way to turn off the notification of new version for System Managers completely and the default frequency should be once a month or every week at the most. This is a serious nag especially when you have no interest in updating!

https://discuss.erpnext.com/t/how-to-turn-off-nagging-notification-about-new-version/41097

Thanks

**Comment by codingCoffee** [comment]
Closing fixed in https://github.com/frappe/frappe/pull/6275/
