### ISSUE TITLE
Billable hours in Timesheet not working.

### ISSUE THREAD

**Issue by adammgerken** [frappe/erpnext#15729]
I'm not sure what changed, nothing cosmetic but my Timesheets no longer count hours as billable when the check box is checked.

In this screen shot the first two worked fine, but adding 7 more hours did not update the billable amount:
![image](https://user-images.githubusercontent.com/44243323/47110912-16e9af00-d220-11e8-9dc3-367127f7704d.png)

**Comment by adammgerken** [comment]
![image](https://user-images.githubusercontent.com/44243323/47110830-e144c600-d21f-11e8-9526-0f984679f68f.png)

**Comment by umairsy** [comment]
Was billable checked for that 4th row as well. The calculations for total hours looks fine in the screenshot attached.

Will be great if you could report it on https://discuss.erpnext.com. If it is validated as a bug, we can report it.

**Comment by adammgerken** [comment]
Sorry, the issue is the Total Billable Amount isn't updating this time sheet is all the same activity which has a $100 billing rate.

There is no 4th row.

If I do add a 4th row, that's the one that doesn't add to the Total Billable Amount. Looks like the last row doesn't work.

![image](https://user-images.githubusercontent.com/44243323/47155954-fb2fe880-d2b3-11e8-9bb3-db3cbb496c33.png)

![image](https://user-images.githubusercontent.com/44243323/47155986-0edb4f00-d2b4-11e8-9847-86064e221572.png)

**Comment by adammgerken** [comment]
@umairsy This is definitely an issue. It's not adding the "Billable Amount" of the last line of the time sheet. All of these lines are "Engineering" which is billed at $100/hr.

![image](https://user-images.githubusercontent.com/44243323/47385621-8bb56100-d6d8-11e8-9e72-207de293cf23.png)
