### ISSUE TITLE
Multi Company Naming Series

### ISSUE THREAD

**Issue by snvora** [frappe/erpnext#15720]
Currently naming series is set in general, applicable to all companies.

As a general practice, it should be different for different companies,

- It should be possible to set company wise default naming series and series value for each doctype.
- While dealing with doctypes, like sales invoice, it should auto-select default naming series and series value based on company chosen.

**Comment by Zlash65** [comment]
We recently changed a lot of naming series for DocTypes to make it make it more generic and changing it again to tackle multi company seems hassling.

Besides ERPNext grants the power of great customization and with a little tweak this feat can be achieved.

- First, go to the DocType for which you want different series based on company and open its Customize Form.
- Next, below the field of Company, add another field and name it 'Abbr'. Keep this field hidden and add `company.abbr` in its fetch_from input.
- Now in the naming_series field's options add another entry in new line ( taking Sales Invoice as example) `SINV-.abbr.-.####` and set this as default.

Thats it. So every time you make a new Sales Invoice and select different company, the naming series will automatically adjust for it.

![image](https://user-images.githubusercontent.com/11695402/47201840-de211580-d398-11e8-9ddf-89c08a6989b2.png)

**Comment by snvora** [comment]
Thank you for your suggestion. 
I feel its Great Solution and smart implementation.
Closing Issue.

**Comment by MahmoudRadwan1** [comment]
how I can add company.abbr in its fetch_from input.

**Comment by ahmedhafiz** [comment]
hello Dear , currently i have more than 15 company and i need to segregate the serial for each one kindly update the steps more clearly

**Comment by michaeleino** [comment]
What is the impact of changing for invoices/journal entries naming series for a running year??
Anyone can confirm??
