### ISSUE TITLE
Workflow Action remains open after final approval [v11]

### ISSUE THREAD

**Issue by flexy2ky** [frappe/erpnext#15721]
I am getting a “Workflow Open” pile up in Workflow Action [v11] even though the workflow state in the doctype has changed to “Approved”.
 I processed a leave application using approval workflow set up for Leave Applications. While the leave approval process completed successfully, i find that in workflow action in setup, the workflow action for each leave marks the leave application as open. when i click the workflow action, it takes me to the leave application where the leave status clearly shows Approved.

Here's the workflow action:

![image](https://user-images.githubusercontent.com/32480024/47072725-8e064f80-d1ee-11e8-89ae-43e9584757f8.png)

However, when you click any of the workflow to check the status, you see that it's shown as "Approved":
![image](https://user-images.githubusercontent.com/32480024/47072859-e0e00700-d1ee-11e8-89f3-717247f251e0.png)

Here's a screenshot of my workflow state setup:

![image](https://user-images.githubusercontent.com/32480024/47073030-3f0cea00-d1ef-11e8-91c5-04124627b856.png)

How can this be fixed?

**Comment by umairsy** [comment]
Hi,

Thanks for reporting it.

Can you please mention the Workflow State field mention in the workflow master. Even though I selected "Status" as a field to be updated, it created new Custom Field. Perhaps that's the reason for this mis-match.

Another issue I faced.

 I Created Workflow for Leave Application. Simple one.

<img width="1233" alt="screen shot 2018-10-18 at 1 24 16 pm" src="https://user-images.githubusercontent.com/910238/47139321-22e57780-d2d9-11e8-9845-da0380c61afe.png">

In the Leave Application, it doesn't show Actions button at all.

<img width="1205" alt="screen shot 2018-10-18 at 1 24 51 pm" src="https://user-images.githubusercontent.com/910238/47139350-355fb100-d2d9-11e8-8e47-fd509bbd1e11.png">

@nabinhait  @PawanMeh

**Comment by flexy2ky** [comment]
Hi,

> Can you please mention the Workflow State field mention in the workflow master.
I cannot say for sure i understand what you mean by this but below is the workflow state setup for the workflow already shown in my previous post:
![image](https://user-images.githubusercontent.com/32480024/47142305-8d3aef80-d2ba-11e8-8257-457b75862e33.png)
Final approval is given at rule 4 at which point the status is changed to approved.

Note however that this workflow was set up in v10 and i didn't notice this issue. It only showed up when i migrated to v11 staging a few weeks ago and i presume that certain changes to the HR module may have caused this to happen as i can also not remember v10 having a workflow action doctype.

**Comment by rohitwaghchaure** [comment]
Hi @flexy2ky 

Can you please enabled the checkbox Allow Self Approval in workflow transitions rule and check 

![screen shot 2018-10-25 at 3 02 22 pm](https://user-images.githubusercontent.com/8780500/47490740-044a2800-d867-11e8-87b0-3d741bc79665.png)

**Comment by flexy2ky** [comment]
I have done that and tried several applications and the situation remains the same. But as has been highlighted by your suggestion and confirmed by trials, this only occurs when the creator of the document approves.

**Comment by aakvatech** [comment]
This problem still exists. Only one out of several Workflow Actions is marked "Completed", rest of the workflow action records remain "Open".

**Comment by govindsmenokee** [comment]
This is still happening for me in the latest master

**Comment by khadijazaki** [comment]
same happening

**Comment by govindsmenokee** [comment]
@rohitwaghchaure @rmehta  @nabinhait This is still happening and is hindering daily operations as users are getting confused with open workflow actions, even though nothing needs to be done with a doc

**Comment by rmehta** [comment]
@govindsmenokee please don't a-tag people unless its critical. Please fix this issue your self or buy support from frappe to fix it.

**Comment by govindsmenokee** [comment]
Ok sure. But what qualifies as critical?

**Comment by surajshetty3416** [comment]
@flexy2ky  this [PR](https://github.com/frappe/frappe/pull/7684) should the issue

**Comment by flexy2ky** [comment]
I think you are probably right on this one. The cancel transaction was included to cater for instances where a workflow process has been concluded but the transaction needs to be reviewed or discarded entirely. In this case the PR submitted should fix it hopefully. I will wait for it to be merged and I’ll give it a try. Thanks for your effort. It’s much appreciated.
