### ISSUE TITLE
install on Google Compute ubuntu 18LTS fails

### ISSUE THREAD

**Issue by dvdsndr** [frappe/erpnext#15747]
Fresh install on standard GC new server. Get this error in bench. The install screen hangs and the browser gives a 404 on control.min.js.

21:37:39 watch.1          | Rebuilding control.min.js
21:37:41 watch.1          | Error in: /opt/erpnext/erpnext/apps/frappe/node_modules/quill-mention/dist/quill.mention.min.js
21:37:41 watch.1          | SyntaxError: Unexpected token (18:3487) in /opt/erpnext/erpnext/apps/frappe/node_modules/quill-mention/dist/quill.mention.min.js

**Comment by TurkerTunali** [comment]
I also get this error after bench update. I can't start bench on my local after this error.

**Comment by dvdsndr** [comment]
I think It something to do with the use of "import" and "output" in the quill.mention.js 
nodejs does not support these. I assume bench jobs like rebuilding are using nodejs 

20:06:40 watch.1          | Rebuilding control.min.js
