### ISSUE TITLE
formula based tax structure

### ISSUE THREAD

**Issue by test2a** [frappe/erpnext#15745]
Hello. 
This issue currently pertains to Indian GST based tax structure but other regions might also be having some sort of similar structure.
Relevant forum discussion is linked here. 
https://discuss.erpnext.com/t/gst-for-hotel-industry-in-india/41903

This issue can be solved by importing salary structure doctype into the taxes and charges template.

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.
