### ISSUE TITLE
[Feature Enhacement] Purchase Order: Get Items from Open Material Requests

### ISSUE THREAD

**Issue by djpalshikar** [frappe/erpnext#15750]
We regularly use "Get Items from Open Material Requests" to send out Purchase Orders to our vendors.

The following enhancements could cut down a lot of time for us:
- If a  Item is _**disabled**_, **do not stop the fetching** other items from pending material request, as is the case now 

   **Currently, we have to manually enable all items, fetch and then again disable the items**
![screenshot_2018-10-20 new purchase order 1 - new purchase order 1](https://user-images.githubusercontent.com/23133635/47253787-f31fa680-d475-11e8-8382-6da9f29a2636.png)

-  Only fetch items where Purchase is allowed ( is Purchase Item is checked)
   **item can be disallowed for purchase at a later date than that of creating a Material Request**

Referencing #15712 , it could be taken up together.

**Comment by djpalshikar** [comment]
@umairsy please consider taking this up with #15712 .

**Comment by harshit-30** [comment]
Hello, @djpalshikar I assume we can close this Issue now since it doesn't exist now.

**Comment by djpalshikar** [comment]
@harshit-30 I can still reproduce the problem in v12.9.2 (version-12), however I do not think this is a bug.
But yes it can get discomforting. 
I think it can be closed.

**Comment by djpalshikar** [comment]
@harshit-30
