### ISSUE TITLE
Sales Analytics >> Menu >> Export >> Click on Download

### ISSUE THREAD

**Issue by asanodaria** [frappe/erpnext#15773]
Steps taken:
1. Open Sales Analytics report.
2. Go to Menu and click on Export button.
3. Click on Download button with default options ticked
With Groups
With Ledgers
Result: Getting error of "Uncaught TypeError: Cannot read property 'getLength' of undefined..."

![image](https://user-images.githubusercontent.com/36321437/47410473-8e20c500-d783-11e8-9ed6-8d1ea940a1d5.png)

**Comment by deepeshgarg007** [comment]
Grid reports will be deprecated soon and all the analytics reports are rewritten in which all the issues will be fixes #15713
