### ISSUE TITLE
[V11] JS Errors after last update. Our work is stuck.

### ISSUE THREAD

**Issue by wispmac** [frappe/erpnext#15770]
Our current version is:
ERPNext: v11.0.3-beta.13 () (develop)
Frappe Framework: v11.0.3-beta.12 () (develop)

After the latest update today, cannot get the Desktop. Login works fine but getting JS errors after login. Now our work is stuck. Screenshot attached below:

![image](https://user-images.githubusercontent.com/2329537/47350529-af29dd00-d6d3-11e8-945b-9a80eb6ddc83.png)

**Comment by shreyashah115** [comment]
This has been [fixed](https://github.com/frappe/frappe/pull/6303). Please pull the latest changes.
