### ISSUE TITLE
[Suggestion] Scrap management in production cycle

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#1578]
Currently production work doesn't take care of scrap/waste material left at the end of production cycle.

**Comment by ylmkls** [comment]
Can we insert Item's BOM Qty in this report so a comparison can be made.
Manufacturing >> Standard Reports >> Issued Items Against Production Order

In this way, there is some data for comparison and taking action

**Comment by nabinhait** [comment]
**BOM**
- Table for produced scrapped items
  - Item Code (FG item code can also be a scrapped item)
  - Qty
  - Rate
  - Amount

**Production Order**
- Scrap Warehouse

**Stock Entry to update FG Item**
- Raw materials will be issued from WIP warehouse
- FG Item will be received in Target Warehuse
- Scrapped items will be received in Scrap Warehouse mentioned in Production Order

**Comment by soloincc** [comment]
Will the scrap item have a different rate as compared to the FG? In my previous implementation, I thought this would have been the same.

**Comment by nabinhait** [comment]
Yes, scrap items can have different rate than FG item, depending on the quality of outputs.

**Comment by soloincc** [comment]
ok. Does the scrap items have to go to a separate table? I am thinking, we can add the scrap parameters in the BOM table and then for each production, we indicate in the manufactured items table how many are FG and how many are scrap. They can be 2 separate entries in the "tabProduction Order" table or a single entry in the table.

**Comment by rmehta** [comment]
@nabinhait can you make a quick mockup of the screens?

**Comment by soloincc** [comment]
Hi @rmehta  @nabinhait see some screenshots here ==> https://www.flickr.com/photos/76947898@N03/albums/72157671745082945

**Comment by soloincc** [comment]
@rmehta @nabinhait What did you make of the screens? Are they ok?

**Comment by nabinhait** [comment]
@soloincc I will make a mockup tomorrow and share with you.

**Comment by nabinhait** [comment]
![bom with scrap](https://cloud.githubusercontent.com/assets/836784/17367187/ab7615ee-59ac-11e6-9b98-a7c5f7a32d18.png)
![pro order](https://cloud.githubusercontent.com/assets/836784/17367191/af02de0e-59ac-11e6-9454-0ed71bf2c656.png)
![stock entry](https://cloud.githubusercontent.com/assets/836784/17367193/af67a99c-59ac-11e6-8ed6-eb10680910d9.png)

**Comment by soloincc** [comment]
Hi @nabinhait looks good. From the screenshots, the most important thing I see is that scrap items can be in form of FG or RM(SCRAP1) which both go to the Scrap Warehouse. I will work on this and update you guys of the progress in due course

**Comment by rmehta** [comment]
@soloincc any update? Let us know if you need any help. We want to push this in 7.1
