### ISSUE TITLE
[bug v11 staging] attach or drag & drop image to Company Logo works, but image is not displayed 

### ISSUE THREAD

**Issue by clarkejj** [frappe/erpnext#15802]
Steps to reproduce:
1) Select a Company doctype
2) Drag and drop and/or attach image file to Company Logo does not result in the image being displayed in view form.  The file upload succeeds and the file name is listed, and it can be deleted too.

**Comment by deepeshgarg007** [comment]
Unable to replicate the issue
![logo](https://user-images.githubusercontent.com/42651287/48836848-d8f52300-eda9-11e8-8fdd-19495a97530d.gif)
Can you please provide details on which version are you facing this issue

**Comment by krnkris** [comment]
File permissions checked under the OS?
It can cause this kind of problems.

Hope this helps.
