### ISSUE TITLE
Allowing Overbilling in Sales Invoices

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#15809]
Currently if you are trying to "overbill", meaning that you want to bill the rate in the invoice higher than what you have set as a rate in the sales order and delivery note, this will throw an error. Instead it is weirdly connected to the stock settings "Limit Percent" which determines what percentage of excess items you are allowed to book. These things should be separated!

We often have situations where customers order and ask us to determine the price after delivery. So we put a fictional or estimate price in the sales order causing the delivery note to pull that price. Now we do our profitability calculation and determine what the product really costs.

Example: in sales order we set 100 pieces of an item to cost 10 USD a piece. After we are done we notice that it should cost 20 USD a piece so we "overbill" by 100%.

Todo in "Accounts Settings":
- [x] Add checkbox "Allow Overbilling" with explanation "Allow invoices to be billed for a higher rate than set in sales invoice and delivery note"
- [x] Add field "Limit Overbilling Percent" with explanation "Percentage you are allowed overbill based on the delivery note rate."
- [ ] Modify `erpnext/controllers/accounts_controller.py` around line 545 to properly handle this new functionality.

![image](https://user-images.githubusercontent.com/9136094/47480960-c7266b80-d84f-11e8-9e48-a71db228509d.png)

ESO Internal comment: when merged in core delete our fork commit https://github.com/frappe/erpnext/commit/1f85f0d3aa68641032a189ca04a698151d6d0e99

**Comment by dottenbr** [comment]
@kickapoo when working on this the [module maintainers](https://github.com/frappe/erpnext/wiki/Module-Maintainers) as contact-persons for this open source contribution are @nabinhait and @PawanMeh

**Comment by kickapoo** [comment]
@nabinhait @PawanMeh @creamdory  Can you please help me to break it down to pseudo code?

I dont understand how it should be related with Item tolerance 

related code
https://github.com/frappe/erpnext/blob/develop/erpnext/controllers/accounts_controller.py#L540
```
tolerance, item_tolerance, global_tolerance = get_tolerance_for(item.item_code,
																					item_tolerance, global_tolerance)

max_allowed_amt = flt(ref_amt * (100 + tolerance) / 100)
if total_billed_amt - max_allowed_amt > 0.01:
    --> error message
```

**Comment by PawanMeh** [comment]
@creamdory @kickapoo Could you check if the checkbox "Maintain Same Rate Throughout Sales Cycle" unchecked? I do not think the system should force you to use the same rate throughout the Sales cycle, is that your issue?

![sales_settings](https://user-images.githubusercontent.com/20460498/47644610-a08c6b80-db94-11e8-8611-c8f93861230e.png)

**Comment by kickapoo** [comment]
@PawanMeh I double check this and unchecking / checking the options dont seem to change anything 

I need to break the "tolerance" to work is the new settings in Accounts (https://github.com/frappe/erpnext/blob/develop/erpnext/controllers/status_updater.py#L345)

- As the issue states "Instead it is weirdly connected to the stock settings "Limit Percent" which determines what percentage of excess items you are allowed to book" , this need tranfer to Accounts Settings

-  Allow each Item has 
<img width="433" alt="screenshot 2018-10-29 14 12 55" src="https://user-images.githubusercontent.com/5064612/47649074-c27df200-db84-11e8-914d-3299709925c3.png">

**Comment by federicocalvo** [comment]
Hi! any news for this? is very useful when you make an invoice, then a credit note, and you have to re-invoice the sales order for example

**Comment by ankush** [comment]
![Screenshot 2021-09-20 at 2 52 42 PM](https://user-images.githubusercontent.com/9079960/133980661-8245dcb8-7dc2-4184-8797-78ce420c0a7c.png)


This is now possible from accounts setting. Almost the same way described in feature request (0.0% instead of checkbox though)
