### ISSUE TITLE
Chat not working on latest Dev

### ISSUE THREAD

**Issue by dvdsndr** [frappe/erpnext#15803]
Getting browser error. Also looks like recent quill fix may need more work

![screen shot 2018-10-24 at 8 53 02 pm](https://user-images.githubusercontent.com/13637075/47469478-17111e00-d7cf-11e8-89ec-a88793d9da4b.png)

**Comment by jigneshpshah** [comment]
Please mention  Issue as below
Environment Version
ERPNext
Frappe Framework

Actual Behavior
Steps

Expected Behavior
Steps

**Comment by umairsy** [comment]
Replicating on my local site as well.

<img width="1224" alt="screen shot 2018-10-30 at 10 31 03 am" src="https://user-images.githubusercontent.com/910238/47696958-f3b2fc80-dc2e-11e8-9fe7-50fd6cbae62e.png">
