### ISSUE TITLE
[Bug - V11] Delivery Note: Get items from function loading duplicate items in Items child table

### ISSUE THREAD

**Issue by asanodaria** [frappe/erpnext#15807]
Steps to reproduce:

1. Create sales order
2. Create Delivery note for this sales order from Make button
3. Click on "Get items from" pop up button.

Actual Result: It loads all the item(s) from sales order again even if item(s) exists in items child table.

Expected Result: When getting from SO, it should load only those items which are not exist in items child table with Sales Order's items table's value.

![delivery-note-get-itemsfrom-so](https://user-images.githubusercontent.com/36321437/47480309-a0ffcc00-d84d-11e8-9cd1-a49a7d511527.gif)

**Comment by asanodaria** [comment]
ERPNext: v11.0.3-beta.11 () (staging)

Frappe Framework: v11.0.3-beta.10 () (staging)

**Comment by Anurag810** [comment]
it is already validated on submit to check quantity.
![screenshot 2018-11-26 at 3 44 39 pm](https://user-images.githubusercontent.com/32095923/49007784-521dbd00-f192-11e8-8884-70cc01a15906.png)
