### ISSUE TITLE
Landed Cost Voucher: Distribute Charges Based On Item weight (I pay 300usd for implementation)

### ISSUE THREAD

**Issue by yunielroque** [frappe/erpnext#15832]
Hello, I am surprised that this basic functionality is not available in ERPNext 10

**Comment by yunielroque** [comment]
I am willing to pay 300usd for the implementation of this functionality so that it is available to all ERPNext users in the next update

**Comment by SaiFi0102** [comment]
Can be closed: https://github.com/SaiFi0102/custom_lcv

**Comment by tiagos30** [comment]
Has this been included on the official version? 

If not, @SaiFi0102 how can I incorporate your code? Does your code allow for volumetric voucher attribution?

**Comment by SaiFi0102** [comment]
I'm not sure what you mean @tiagos30 
This is not meant to be for the official, it's only a customized replica of the LCV

**Comment by tiagos30** [comment]
How can I implement it on my instance of erpnext?

**Comment by SaiFi0102** [comment]
You'll have to install the app on your bench. I wrote this for version 10 which is quite old. Email me at saif@mocha.pk or message me on Telegram saifi0102 and we can figure it out
