### ISSUE TITLE
Incorrect GST Calculation for Sales Invoice - SEZ, Without Payment of Tax

### ISSUE THREAD

**Issue by karannshah** [frappe/erpnext#15834]
@umairsy In Without Payment of Taxes or Zero Rated Supply - Tax amount should appear in printing but should not be added to total. Currently even for Without Payment of Tax - the total as well was outstanding shows amounts inclusive of tax. 

<img width="1437" alt="screen shot 2018-10-26 at 1 03 47 am" src="https://user-images.githubusercontent.com/14230707/47525673-7b111080-d8bb-11e8-976f-6eb989cfd2e6.png">
<img width="1436" alt="screen shot 2018-10-26 at 1 03 53 am" src="https://user-images.githubusercontent.com/14230707/47525674-7ba9a700-d8bb-11e8-9567-bce2d935ed8b.png">
<img width="1437" alt="screen shot 2018-10-26 at 1 04 06 am" src="https://user-images.githubusercontent.com/14230707/47525675-7ba9a700-d8bb-11e8-8f03-a29efffabc61.png">

Further, If I have 4-5 items in sales invoice with 2  different tax rates - tax calculation for without payment of tax fails. please see the image below.

<img width="950" alt="screen shot 2018-10-26 at 1 07 57 am" src="https://user-images.githubusercontent.com/14230707/47525856-e0fd9800-d8bb-11e8-93ca-4d226440116f.png">

**Comment by test2a** [comment]
@karannshah check this forum post i made last time about the issues in erpnext with regards to the Indian GST localization.
https://discuss.erpnext.com/t/cess-tax-on-tobaco-products/40719/15?u=test2a
seems i missed the SEZ and their issues. feel free to go through the issues pointed out and if you have any other pressing errors or stuff you would like to get corrected.

I have offered to help with production testing erpnext with only specific intention of testing accounting GST implementation module and the error like you mentioned are a priority. The government has already announced the dates of the new return formats and we need to be ready for that as well. 

If you have any more inputs, that would be awesome

**Comment by karannshah** [comment]
> @karannshah check this forum post i made last time about the issues in erpnext with regards to the Indian GST localization.
> https://discuss.erpnext.com/t/cess-tax-on-tobaco-products/40719/15?u=test2a
> seems i missed the SEZ and their issues. feel free to go through the issues pointed out and if you have any other pressing errors or stuff you would like to get corrected.
> 
> I have offered to help with production testing erpnext with only specific intention of testing accounting GST implementation module and the error like you mentioned are a priority. The government has already announced the dates of the new return formats and we need to be ready for that as well.
> 
> If you have any more inputs, that would be awesome

Will absolutely add my inputs

**Comment by karannshah** [comment]
@jigneshpshah we may have to check this for other categories also. Like Export without payment of tax.

**Comment by karannshah** [comment]
@umairsy would there be any updates on making Sales Invoices GST compliant? Without tax cases are not working. Can I help in any way here?

**Comment by karannshah** [comment]
@umairsy no, item's rate does not include tax. 

before I reply in detail can you help me understand what happens in ERPNext Sales Invoices under different Invoice Types and Export Type. 

In ERPNext What happens to GST calculations and what happens to Invoice Print when Invoice Type = "SEZ" or "Export" and Export Type = "Without Payment of Tax" / "With Payment of Tax"? 

<img width="1267" alt="screen shot 2018-11-08 at 1 00 45 pm" src="https://user-images.githubusercontent.com/14230707/48183905-548cb400-e356-11e8-9049-31bc31f77cd8.png">

**Comment by karannshah** [comment]
@umairsy looking forward to learn about how to manage invoice type like SEZ and Export from ERPNext. This will give you a better idea of Export without payment of taxes. 
https://cleartax.in/s/gst-export-bond-and-lut

**Comment by harshit-30** [comment]
Please create another issue if it is replicable in v13.10.
