### ISSUE TITLE
Payment Entry against Payment Terms (Due Date and Due Amount)

### ISSUE THREAD

**Issue by rebin2002** [frappe/erpnext#15831]
Hello,

I have a problem I want to explain.

I have created payment terms and made them one payment term template.
the term is 
Installment1 : 25% after 0 days
Installment2 : 15% after 30 days 
Installment3 : 15% after 60 days
Installment4 : 15% after 90 days
Installment5 : 15% after 120 days
Installment6 : 15% after 150 days

So when I make Sales invoice, I will apply the term template and it works, Then I created a custom field in Payment Entry as Link Field and put (Payment Term) in the option, So In Payment Entry when I receive one installment amount I choose which Installment the customer is paying, for example Installment1.
Then I check accounts receivable for that Customer, the amount deducted from total amount.
BUT as I have created a custom report for showing due amounts and due dates for each Installment (Payment Schedule) or for the Payment Terms, its not showing that the INSTALLMENT1 is PAID, still INSTALLMENT1 is available in the report, also available in the Custom field which I created in Payment Entry form.
So what I see, the Payment Terms has no connection for clearing due amounts in accounting!

Please help me to solve this problem, as I want to know due amounts and dates of each installment and each customer.

Thank you.

**Comment by rebin2002** [comment]
@nabinhait Could you please help on that?

**Comment by rebin2002** [comment]
@tundebabzy Could please check this issue for me? as I have read, you and @nabinhait worked on such issues. Thanks

**Comment by umairsy** [comment]
@nabinhait based on the efforts and time estimate, could you mention the sponsorship amount for this feature? @rebin2002 would be interested in sponsoring.

**Comment by nabinhait** [comment]
@rebin2002 What you have suggested was the actual design and first implementation was that only . But it was complicating the whole things how we process gl entries and stuff. We need to split GL Entries for Accounts Receivable into multiple to tag them with payment gl entries. And there were som many such complexity. Thats why we had decided to discard the implementation.
What we can do is, in AR/AP report, may be we can show outstanding based on payment terms and reconcile payments based on FIFO. For me FIFO makes sense, because why would a customer pay 2nd instalment first before paying 1st?

**Comment by rebin2002** [comment]
@umairsy 
@nabinhait 
Could you give me a solution please? its urgent. Thanks

**Comment by rebin2002** [comment]
Dear Nabin,

I have made the payment USD300, I'm very urgent for this report, I hope you
can do it sooner than your specified time.

Best regards,
*Rebin Khoshnaw*
Chairman
Clarmin Company for General Trading Ltd.
Mob:   009647504550295
www.clarmin.com
Add: Doctors Street, 44001
Erbil, IRAQ

**Comment by fsayfitdinov** [comment]
Hi @rebin2002,

**Comment by fsayfitdinov** [comment]
What is more to this issue, I cannot print out the installment days in a table form in sales invoice. How to include it?

**Comment by barredterra** [comment]
@nabinhait @rebin2002 I guess this issue can be closed by now?
