### ISSUE TITLE
Can’t send Email after Workflow [BUG?]

### ISSUE THREAD

**Issue by franciscobuendiao** [frappe/erpnext#15848]
Only the role whom submitted a document, has _Email_ option available from dropdown Menu.

https://discuss.erpnext.com/t/cant-email-after-workflow/42025

ERPNext: v10.1.64 (master)
Frappe Framework: v10.1.56 (master)

**Comment by thomasgks** [comment]
Facing same issue, Waiting for the solution.

**Comment by deepeshgarg007** [comment]
@franciscobuendiao  Closing this issue. If the issue still persists in the latest version-13 or above then please reopen a new issue
