### ISSUE TITLE
complete po still in this filter

### ISSUE THREAD

**Issue by pornchalat** [frappe/erpnext#15843]
![20181028erpnext-prob](https://user-images.githubusercontent.com/35266090/47613053-2a1b3b00-daba-11e8-8b24-0e78ccab63b3.png)

**Comment by asbasawaraj** [comment]
Please reopen this issue with full details... 

Check guidelines at https://github.com/frappe/erpnext/wiki/Issue-Guidelines

I cannot replicate this issue in my local...

Could be related to your second filter with Documents Status
