### ISSUE TITLE
Delete completely some modules from erpnext app

### ISSUE THREAD

**Issue by lncan** [frappe/erpnext#15850]
Hi guys, I'm a beginer in erpnext. I installed erpnext app on local and now, i want to delete 'Agriculture' module and anything related it. So, Can i do it? Thank you.

**Comment by Zlash65** [comment]
Can you post a screenshot of `Domain Settings` when searched from search bar.

If Agriculture's checkbox is checked, uncheck it and save it. This should delete all the custom fields related to it and should disable the roles for it too. Thus you won't see anything pertaining to that.

**Comment by eriksurya** [comment]
Under domain setting, you can manage all the domains, one of them is Agriculture.

**Comment by SalahAdDin** [comment]
> Under domain setting, you can manage all the domains, one of them is Agriculture.

What if I want to uninstall/disable CRM or other modules?
