### ISSUE TITLE
Serial No Duplication

### ISSUE THREAD

**Issue by nagarajannxweb** [frappe/erpnext#15862]
Completed a manufacture entry of an Item A has a Serial No 1234 and made an invoice to a customer. After that by mistake if the user again creates a stock entry of the same item and same serial number it allows to create the entry.

**Comment by umairsy** [comment]
Issue replicating in gadgets.erpnext.com

**Comment by deepeshgarg007** [comment]
@nagarajannxweb we are unable to replicate the issue. If you are still able to replicate then please provide some more details on how to replicate the issue and reopen
