### ISSUE TITLE
Unable to modify get_query for customer link field

### ISSUE THREAD

**Issue by lasalesi** [frappe/erpnext#15876]
**Objective**: custom doctype, link field "customer", apply a custom get_query for a customer link field (e.g. only allow enabled customers to be linked).

**Code**: custom script

    refresh: function(frm) {
        cur_frm.fields_dict['customer'].get_query = function() {
            return {
                filters: { 'disabled': 0 }
            }
        }
    }

**Expected behaviour**: only enabled customers should appear in the list.

**Actual behaviour**: all customer appear, filter has no effect/is ignored.

**Observed in**: ERPNext: v10.1.54 (master), Frappe Framework: v10.1.49 (master)

See also https://discuss.erpnext.com/t/unable-to-make-custom-script-work-query-filter-not-sent-to-db/21892/6

**Comment by Olawale1** [comment]
Hi ,

Any update here?
