### ISSUE TITLE
General Ledger "Group by Party"

### ISSUE THREAD

**Issue by hballan** [frappe/erpnext#15884]
In the general ledger, please add "Group by Party" in the same way that we have "Group by Account" this is super important to be able to reconcile Accounts Payable of Suppliers and Accounts Receivable of Customers with the Ledger accounts.

**Comment by kennethsequeira** [comment]
Group by Party option has been added in ERPNext from version 11:

![image](https://user-images.githubusercontent.com/33246109/80955725-5b966480-8e1d-11ea-8512-2eae1ee4aae8.png)
