### ISSUE TITLE
Client-side permission errors when adding Item Barcode to Item page

### ISSUE THREAD

**Issue by gbm001** [frappe/erpnext#15886]
Hi,

![image](https://user-images.githubusercontent.com/4930097/47850507-5c37e000-ddcd-11e8-9d49-c4d16bb4dfdc.png)
![image](https://user-images.githubusercontent.com/4930097/47850592-b769d280-ddcd-11e8-9325-437827f30c9d.png)

When typing in the Item Barcode quick entry table 'Barcode' field on the Item page, the above type of message is displayed (although I don't think it actually stops you doing anything. I have tried logging in as the Administrator and as an all-powerful (I think) system user.

So far I have traced it to the key_up handler on the input, which calls setup_autoname_check in frappe/frappe/public/js/frappe/form/controls/data.js which then calls frappe.db.get_value. The arguments for frappe.db.get_value are 'Item Barcode', the value of the input, and the callback. Calling frappe.db.get_value from the console:
`frappe.db.get_value('Item` Barcode', '1234', 'name', function(r) {console.log(r);})`
triggers the same permissions error (that's as far as I've got).

To reproduce:
Create a new ERPNext site. Create a new item. Start typing in the quick entry table for Item Barcode (after pressing 'Add Row'). Error messages are displayed.

Version: Latest git from develop branch for frappe and erpnext.

I have my suspicions that it is related to the issue with the API leaking child table information https://github.com/frappe/frappe/issues/5770, and the consequent need to pass a 'parent' parameter.

**Comment by gbm001** [comment]
Replacing this code:
```
// check if name exists
                        frappe.db.get_value(this.doctype, this.$input.val(),
                            'name', (val) => {
                                console.log('CHECKING IF NAME EXISTS2');
                                if (val) {
                                    this.set_description(__('{0} already exists. Select another name', [val.name]));
                                }
                                console.log('CHECKING IF NAME EXISTS2');
                            });
                        this.last_check = null;
```

with this code:
```
// check if name exists
                        var that = this
                        frappe.call({
                            method: 'frappe.client.get_list',
                            args: {
                                doctype: this.doctype,
                                filters: {
                                    name: this.$input.val()
                                },
                                parent: this.frm.doctype
                            },
                            callback: function (r) {
                                if (r.message && r.message.length > 0) {
                                    that.set_description(__('{0} already exists. Select another name', [r.message[0].name]));
                                }
                            }
                        });
                        this.last_check = null;
```
fixes it for now but I'd consider it a bodge.

Another fun and exciting bug: if you create an Item Barcode, save the Item, then add another Item Barcode and give it the same barcode (not allowed) and try and save the Item, it gives you an error `Item ITEM-xxxxx already exists` rather `Item Barcode XXXXXXXX already exists` :)

**Comment by gbm001** [comment]
I've also realised this is probably a Frappe, not an ERPNext, issue...

**Comment by umairsy** [comment]
Will be great if you could raise this issue on https://discuss.erpnext.com. If validated as bug, we can reopen this issue.

**Comment by gbm001** [comment]
https://github.com/frappe/frappe/pull/6570
