### ISSUE TITLE
Cannot fork COA in https://charts.erpnext.com

### ISSUE THREAD

**Issue by auliabismar** [frappe/erpnext#15897]
![firefox_2018-11-03_07-10-37](https://user-images.githubusercontent.com/13597589/47945882-e56b2600-df37-11e8-82b6-03add6314bf1.png)

**Comment by tooclean2320** [comment]
I’ve never been to that site or thread... can you please block me

**Comment by krnkris** [comment]
@tooclean2320 

You just unsubscribe.

Hope this helps.

**Comment by Muzzy73** [comment]
I aslo tried. Didn't work. Had to start a new CoA. Taking time to build it for Bahrain region.

**Comment by Nofal-Mami** [comment]
Hi,
Just now I have tried fork button for Tunisia COA, page get frozen, no response and no error message.

Any update please.
Rgds
Nofal

**Comment by nabinhait** [comment]
charts.erpnext.com has been deprecated, hence closing
