### ISSUE TITLE
Default installation instance ERPNext 11 has misconfigured material request field

### ISSUE THREAD

**Issue by lxnow** [frappe/erpnext#15898]
Material request field under stock entry table should be checked as "shown in filter" under customize forms, since there is a default option to trace the stock entry from the Material Request form. Clicking that stock entry link will lead to an error in unable to filter using MR number due to the incorrect configuration.

**Comment by umairsy** [comment]
please share screenshots and complete error message.

**Comment by lxnow** [comment]
Sorry I'm unable to recreate at the moment. Will close for now.

**Comment by lxnow** [comment]
I've recreated this issue on ERPNext: v10.1.68 (master) hosted on ERPNext.com

1. Create a Material Request, then issue a Stock Entry against it. Submit STE. Open same MR then trace-"forward" the related STE by clicking on the STE link as so:
![1](https://user-images.githubusercontent.com/5035210/48398669-69a18280-e75c-11e8-8fff-ea9a01e852da.JPG)

2. You will get the error as the **material_request** field is hidden by default.
![2](https://user-images.githubusercontent.com/5035210/48398674-6dcda000-e75c-11e8-838c-7d002a881dda.JPG)

3. You can unhide the **material_request* field under Stock Entry Detail table Doctype through Customize Form, but a newbie shouldn't have to go through this.
![3](https://user-images.githubusercontent.com/5035210/48398676-6efecd00-e75c-11e8-924c-edad41d27829.JPG)
