### ISSUE TITLE
Customer Portal Search bar

### ISSUE THREAD

**Issue by KunalK09** [frappe/erpnext#15890]
We made some changes in customer portal we added customer po and po date in the customer portal so how can we search po and po date in the search bar as we do it for sales order Can you guide us on how to implement this??
![customer](https://user-images.githubusercontent.com/42600320/47895893-ccf40080-de90-11e8-9418-5131c0c170b7.png)

**Comment by szufisher** [comment]
go to sales order form view, click the menu->customize
locate to the customer PO and date field, open the sub form like below, tick the global search check box.
![image](https://user-images.githubusercontent.com/12823863/48041217-3177ce00-e1b7-11e8-8900-8a2668bc69b9.png)

**Comment by umairsy** [comment]
Hi Global Search is meant for the search from Awesome Bar. It doesn't apply on the website portal search.
