### ISSUE TITLE
serious bug with pdf creation - bootstrap layout is broken

### ISSUE THREAD

**Issue by ioweb-gr** [frappe/erpnext#15896]
I upgraded today to the latest version and noticed that PDF creation is not working properly. 

While I press print and load my custom format I can see the proper image layout like this

![image](https://user-images.githubusercontent.com/20220341/47933140-6399df00-dedc-11e8-81b1-68283d44ddc1.png)

But the pdf ends up like this
[BLK-00057.pdf](https://github.com/frappe/erpnext/files/2543660/BLK-00057.pdf)

It's as if bootstrap is no longer loaded.

**Comment by ioweb-gr** [comment]
OK I'm even more confused now. When I stop supervisor and run `bench start` and try the same action it works correctly. I've tried clearing cache multiple times but it doesn't seem to have an effect. Any ideas?

**Comment by tooclean2320** [comment]
Unsubscribe tooclean541@gmail.com 


PLEASE OR I’ll report the 100’s of emails im receiving hourly, with no unsubscribe button to press.

**Comment by ioweb-gr** [comment]
> 
> Unsubscribe tooclean541@gmail.com PLEASE OR I’ll report the 100’s of emails im receiving hourly, with no unsubscribe button to press.

What are you talking about? We never send bulk emails and newsletters. Our outgoing email count for today was 36 emails total. Anyway don't pollute an issue thread with this. Feel free to contact us for any issues at abuse ( a t ) ioweb.gr and don't forget to include full email headers to investigate further.

**Comment by deepeshgarg007** [comment]
Please follow Bug Reporting guidelines.
Version/Environment is important while reporting the bug,
https://github.com/frappe/erpnext/wiki/Issue-Guidelines#bug-report-guidelines

**Comment by ioweb-gr** [comment]
Sorry about that. I didnt' mark it but I upgraded right after commit  dcb71a61ad46c72a646db2dd91a27ba0b98d050b so the last version bump was  11.0.3-beta.17

About my environment specs 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"
10.1.37-MariaDB-1~xenial mariadb.org binary distribution
nginx version: nginx/1.10.3 (Ubuntu) 

Hope it helps. 
I will try to update again this weekend to last version and see if the problem is fixed again and mark versions again.

**Comment by clarkejj** [comment]
"OK I'm even more confused now. When I stop supervisor and run bench start and try the same action it works correctly. I've tried clearing cache multiple times but it doesn't seem to have an effect. Any ideas?"

Your environment seems to be the issue, so best move this to discuss.erpnext.com for forum traffic attention and response
