### ISSUE TITLE
Settings -> Error log = Message: The seen field is not selectable.

### ISSUE THREAD

**Issue by krnkris** [frappe/erpnext#15904]
If I click on Error log
immediately a message appears:
"The seen field is not selectable."

After page reload in the top bar menu, then I can reach the issues.
Someone else has the same issue?

Installed Apps
ERPNext: v10.1.66 (master)
Frappe Framework: v10.1.58 (master)
![kepernyokep 2018-11-04 22-51-12](https://user-images.githubusercontent.com/7963250/47970339-56b7ef80-e084-11e8-8d9c-8ce8cf6d92c4.png)

**Comment by Mitchy25** [comment]
Also having this issue on:

ERPNext: v11.0.3-beta.15 () (develop)
Frappe Framework: v11.0.3-beta.19 () (develop)

**Comment by Mitchy25** [comment]
I've since fixed this by going to the Error Log customisation screen and editting the Seen variable to be visible (Hidden was checked).

**Comment by krnkris** [comment]
@Mitchy25
Thank you, it solve the broblem.
After this change, I put back 
the Error Log customization to
Default, and still no problem.

**Comment by krnkris** [comment]
After 
bench update
the error occurs again.
It is a bug.

**Comment by krnkris** [comment]
+1

https://github.com/frappe/frappe/issues/6374

**Comment by krnkris** [comment]
Do you get the same error or we can close this subject?

**Comment by krnkris** [comment]
It seem to be resolved as of 
Installed Apps

ERPNext: v10.1.73 (master)

Frappe Framework: v10.1.66 (master)
