### ISSUE TITLE
Delete Action raise problem!

### ISSUE THREAD

**Issue by OmarJaber** [frappe/erpnext#15907]
https://github.com/frappe/erpnext/blob/f3f997f232f8eaa677a517ed81488c110be9cdad/erpnext/utilities/transaction_base.py#L148

I have a problem when I try to delete for example employee or department
It didn't recognize the **ref_type** 
Any suggestion please, I have installed the last version and make an update before inserting this issue

Regards

**Comment by rmehta** [comment]
Can you share the full trace and step to reproduce please.
