### ISSUE TITLE
[BUG] Invoice printing Problem

### ISSUE THREAD

**Issue by yunielroque** [frappe/erpnext#15905]
When exporting invoice the system freezes

Here I leave a video that describes the problem:

https://youtu.be/_HClBVvAfI4

Another video:
https://youtu.be/FI7Fj-IFSZw

**Comment by yunielroque** [comment]
The problem was the Letter Head that had a photo that had been removed from the system.

**Comment by yunielroque** [comment]
I think a validation should be done for that case because the system goes down forever, I think that's not right.

**Comment by umairsy** [comment]
Could you please report it on discuss.erpnext.com?? If validated as bug, we can re-open it. Seems to be working fine in our test instance.
