### ISSUE TITLE
Show 30/60/90 on Print Format Accounts Receivable

### ISSUE THREAD

**Issue by heatherpotter** [frappe/erpnext#15906]
If the print format is landscape, then the 30/60/90 range should show on the print format. It's a pain to have to export to excel and print just to see that on display for management. 

It would be nice to be able to edit the print format of accounts receivables so that management gets just the columns they need and not the unnecessary.

**Comment by rushikesherp** [comment]
> If the print format is landscape, then the 30/60/90 range should show on the print format. It's a pain to have to export to excel and print just to see that on display for management.
> 
> It would be nice to be able to edit the print format of accounts receivables so that management gets just the columns they need and not the unnecessary.

Dear Heather,

Accounts receivables is a standard script report and not a report created using report builder. Thus only a few fields are visible in the print. However you can check the checkbox "Show PDC print". This adds the summary of receivables ageing to the print format. Hope this helps!
![image](https://user-images.githubusercontent.com/40016931/48043100-d344ee00-e1aa-11e8-8898-4073ca7f2447.png)

**Comment by heatherpotter** [comment]
Yes, the 30/60/90 summary up top is nice but I meant the actual amount per customer in 30/60/90. I want the 30/60/90 like you get when you export to excel.
