### ISSUE TITLE
html5lib.treebuilders._base.TreeBuilder

### ISSUE THREAD

**Issue by sharpec** [frappe/erpnext#15900]
bench update from

ERPNext: v10.1.51 (master)
Frappe Framework: v10.1.46 (master)

to latest Erpnext 10.1.66
return
```
File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'
```

source:
https://discuss.erpnext.com/t/migrate-site-to-v11-and-html5lib-error-object-has-no-attribute-base/41305
https://discuss.erpnext.com/t/error-during-update-to-10-1-66/42419
https://discuss.erpnext.com/t/bench-update-error-with-this-week-update/41974

**Comment by rasos** [comment]
I can confirm, update is not possible to v10.1.68.
