### ISSUE TITLE
File Manager not working. Error : Field folder is not selectable.

### ISSUE THREAD

**Issue by beeriz** [frappe/erpnext#15914]
When clicking on "File Manager" I'm getting an error. I can't view any folder, or create new ones.

ERPNext: v11.0.3-beta.11 () (develop)
Frappe Framework: v11.0.3-beta.21 () (develop)

![2018-11-05_23-17-07](https://user-images.githubusercontent.com/13268158/48030356-12465580-e151-11e8-98af-1e1d53d3f006.gif)

Any idea what's causing this?

**Comment by rushikesherp** [comment]
This Error does not come up on 11.0.3 (staging). Checked on beta.erpnext.com. The file icon can be selected

**Comment by rushikesherp** [comment]
However getting a different error on beta.erpnext.com.
 Unable to upload the file. Could be due to permissions for demo user.
![image](https://user-images.githubusercontent.com/40016931/48042246-c920f080-e1a6-11e8-8c4a-39119dc929a9.png)

**Comment by beeriz** [comment]
> This Error does not come up on 11.0.3 (staging). Checked on beta.erpnext.com. The file icon can be selected

staging and develop are pretty much the same? 
Should I wait for a fix ? 

Thanks

**Comment by Mitchy25** [comment]
This is now a known issue. To fix:

1. Open File List
2. Customise the File Doc
3. Open up the 'Folder' row
4. Unselect the 'Hidden' checkbox
5. Update
6. Refresh Cache

**Comment by krnkris** [comment]
This hidden problem found in other menu as well:

https://github.com/frappe/erpnext/issues/15904

**Comment by krnkris** [comment]
Do you get the same error or we can close this subject?

**Comment by krnkris** [comment]
it seem to be resolved as
Installed Apps

ERPNext: v10.1.73 (master)

Frappe Framework: v10.1.66 (master)

**Comment by krnkris** [comment]
please close this subject.
