### ISSUE TITLE
Microsoft OneDrive Backup Integration

### ISSUE THREAD

**Issue by hballan** [frappe/erpnext#15922]
In the same way that there is the option to backup to DropBox and Amazon S3 Cloud, please add the feature to be able to backup to Microsoft OneDrive.

**Comment by hballan** [comment]
Any update on this feature request. I would really be helpful to add the backup to Microsoft OneDrive integration feature.

**Comment by FatCatTuxedo** [comment]
Would also like this as many of us use office 365 so have onedrive

**Comment by rareza35** [comment]
Any posible integration option to OneDrive Office 365?

**Comment by rareza35** [comment]
I waiting reponse over OneDrive integration. Many people use office 365 at schools.
