### ISSUE TITLE
Opportunity Type default in Opportunity not localized

### ISSUE THREAD

**Issue by barredterra** [frappe/erpnext#15923]
## Problem

https://github.com/frappe/erpnext/blob/ea42980de69bf71c83f80d8b59781054e5aa6e32/erpnext/crm/doctype/opportunity/opportunity.json#L291
The default for opportunity_type in the Opportunity DocType is hardcoded to "Sales". 

## Reproduce

* Set up your system in German (or any language except English). 
* Try to create a new opportunity by REST API, leaving opportunity_type empty

```js
request({
  method: 'POST',
  url: 'https://demo.erpnext.com/api/resource/Opportunity',
  headers: { 
     Accept: 'application/json',
     'Content-Type': 'application/json' 
  },
  body: { status: 'Open', lead: 'LEAD-00001', enquiry_from: 'Lead' },
  json: true
})
```

Get the following error:

```js
_server_messages: [{
    message: "Could not find Opportunity Type: Sales", 
    indicator: "red"
}]
```
## Cause

By default **there is no Opportunity Type "Sales"** because it was correctly translated to the system language, "Vertrieb" in the case of German.

## Solution

Localize default value, if possible, or remove it.

---
Tested with:

ERPNext: v10.1.64 (master)
Frappe Framework: v10.1.56 (master)

(Still present in `develop` branch as of 2018-11-06)

**Comment by rasos** [comment]
The default contact when sending a "General" message is of type "Sales". So I had to add an extra opportunity type "Sales" even this appeared already translated in the Opportunity Type List.

**Comment by barredterra** [comment]
Right, so default functionality is failing for systems in other languages than English.

**Comment by barredterra** [comment]
@crescent28 can you please add a note why you closed this?
