### ISSUE TITLE
It does not show variable attributes table when creating product in v11

### ISSUE THREAD

**Issue by erickrojasfigueroa** [frappe/erpnext#15934]
When you create a product, then when you mark the product option with variations, it does not show the table to add attributes.

Tested in:
ERPNext: v11.0.3-beta.15 () (staging)
Frappe Framework: v11.0.3-beta.15 () (staging)

![image](https://user-images.githubusercontent.com/17947029/48138505-73b21580-e272-11e8-84b0-88658e96da0f.png)

**Comment by mnatalia** [comment]
It works from my side
Tested in:
ERPNext: v11.0.3-beta.19 () (staging)
Frappe Framework: v11.0.3-beta.22 () (staging)
![item](https://user-images.githubusercontent.com/9428212/48187976-34082e00-e345-11e8-92cf-3312bd0201a8.png)

**Comment by erickrojasfigueroa** [comment]
Please test in language spanish, there the error appears.

**Comment by mnatalia** [comment]
Please check my screenshot I used spanish and it works

**Comment by erickrojasfigueroa** [comment]
My test was in

ERPNext: v11.0.3-beta.15 () (staging)
Frappe Framework: v11.0.3-beta.15 () (staging)

I will go back to Test in

ERPNext: v11.0.3-beta.19 () (staging)
Frappe Framework: v11.0.3-beta.22 ()

**Comment by erickrojasfigueroa** [comment]
Going back to try and work correctly, tested in, thank you

ERPNext: v11.0.3-beta.19 () (staging)
Frappe Framework: v11.0.3-beta.22 () (staging)

**Comment by mnatalia** [comment]
@erickrojasfigueroa so, please close your issue

**Comment by erickrojasfigueroa** [comment]
SOLVED
**IMPORTANT** 
when import productos se debe declarar el valor de la COLUMN "variant_based_on" to "Item Attribute", 
if this is not done then the product from the erpnext can not be enabled to the product to support variants
