### ISSUE TITLE
Serial No : Validation in Stock Entry

### ISSUE THREAD

**Issue by kalaisaranA** [frappe/erpnext#15936]
Need  serial number validation in stock entry

**Comment by kennethsequeira** [comment]
@kalaisaranA please elaborate on what kind of validation you require and the use case.

**Comment by nxdevelopment** [comment]
Stock Entry allows same Serial Number items (duplication of serial no). Even though the product is sold (contain Delivery Note),again the another product with same serial number is given it generate the new product with previous serial_no.In this Serial No list the creation document no is rewritten. So it allows repeation/duplication of serial number. It is one of issue. Detailed description is given below
Initally on work order:
![screenshot_2018-11-19 pdt - mfg-wo-2018-00014](https://user-images.githubusercontent.com/44566832/48706346-fa2b0780-ec21-11e8-99de-d6666e29fc0d.png)
2.when Product started to Manufacturing .Serial no created for 1st product-
![screenshot_2018-11-19 manufacture - mat-ste-2018-00049 1](https://user-images.githubusercontent.com/44566832/48706468-64dc4300-ec22-11e8-8f18-ea7022dc0b84.png)
3.The deliverynote  and document creation  in Serial no A55-

![screenshot_2018-11-19 nxweb - mat-dn-2018-00007 1](https://user-images.githubusercontent.com/44566832/48707786-8d663c00-ec26-11e8-8e2c-0a1a43fa2dce.png)

![screenshot_2018-11-19 a555](https://user-images.githubusercontent.com/44566832/48706592-b8e72780-ec22-11e8-8e4c-91f12e5aabab.png)
4.Again the another product started to manufactured with same serial number -
![screenshot_2018-11-19 manufacture - mat-ste-2018-00050](https://user-images.githubusercontent.com/44566832/48706772-43c82200-ec23-11e8-8dcf-56abff72cadc.png)
5.The Generation of same Serial No in list -
![screenshot_2018-11-19 a555 1](https://user-images.githubusercontent.com/44566832/48706838-73772a00-ec23-11e8-8c41-c05da6d444c0.png)

How it is possible same serial Number for 2products??????

These are detailed explanation of serial number duplication .Kindly refer the screenshot. 
Requirement : when same serial number is repeated in stock entry it must throw msg as " Already Referenced in Document " and not allow to rewrite in document.

Modified file :https://github.com/frappe/erpnext/pull/16020/commits/b5170a46381c8d8b27567b61e3d2104b9455e801

After modification  :  RESULT 
![peek 2018-11-07 16-28](https://user-images.githubusercontent.com/44566832/48707187-a372fd00-ec24-11e8-8d85-a5e7b4813b1c.gif)

**Comment by kennethsequeira** [comment]
When the serial number is in stock, the validation triggered:

![image](https://user-images.githubusercontent.com/33246109/48713728-16856f00-ec37-11e8-8fbc-e12f48926e45.png)

The same triggered on making delivery and making a receipt of the serial number for another product:

![image](https://user-images.githubusercontent.com/33246109/48714223-3bc6ad00-ec38-11e8-9a1f-056f717c6bef.png)

I used: 
ERPNext: v10.1.72 (master)
Frappe Framework: v10.1.62 (master)

On which version have your tried? That will help in targetting and sending a fix for this.

@kalaisaranA @nxdevelopment

**Comment by nxdevelopment** [comment]
Thanks for reply @kennethsequeira 
I am using Version :
ERPNext:  v11.x.x-develop
Frappe Framework: v11.x.x-develop

Kindly just try this workflow where i saw the issue in this one:
     create a serial no SR0100 for product1 and make Sales Invoice and Payment .
     Refer the SR0100 in serial no list.
     Again for another product in stock entry let create SR0100 serial no ,it just allow creation of  the     serial number 
     Refer SR0100 serial no in serial no list and creation  document(stock entry link) in serial number list is over written.

**Comment by kalaisaranA** [comment]
Thanks for reply @kennethsequeira
I am using Version :
ERPNext: v11.x.x-develop
Frappe Framework: v11.x.x-develop
