### ISSUE TITLE
[Proposal] Order Ledger

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#15944]
Motivation: The code + data structure for maintaining order status is very complicated and does not cover all use-cases. Currently to track delivery status, the line-item id of the `Sales Order` is tracked in the `Delivery Note Item`. This kind of linking is problematic for several reasons and makes cancellation very difficult.

In the new design, these links will no longer be maintained in the line-items. These will be maintained in a special table called "Order Ledger" and the delivery and payment status of an Order will be inferred form this table. This will also ease tracking of cancellations and returns multiple times and clubbing and separation of order fulfilment.

### Sales Ledger Entry

- [x] Sales Order (link)
- [x] Delivery Note (link)
- [ ] Sales Invoice (link)
- [ ] Action (Order / Delivery / Billing)
- [ ] Item
- [ ] Qty (can be negative for cancellation / change)
- [ ] Amount (can be negative for cancellation / change)

### Purchase Ledger Entry

- [ ] Material Request (link)
- [ ] Purchase Order (link)
- [ ] Purchase Receipt (link)
- [ ] Purchase Invoice (link)
- [ ] Action (Request / Order / Receipt / Billing)
- [ ] Item
- [ ] Qty (can be negative for cancellation / change)
- [ ] Amount  (can be negative for cancellation / change)

### Logic

- [ ] Create Sales Ledger Entry, Purchase Ledger Entry on all relevant transactions (submission and cancellation)
- [ ] Update Order based on Ledger
 - [ ] Billing status (Not billed / Partly Billed / Fully Billed / Cancelled)
 - [ ] Fulfilment status (Not Delivered / Partly Delivered / Fully Delivered / Cancelled)
- [ ] Update `Ordered Items to Bill` and `Ordered Items to Deliver` reports (similarly for Purchase)
- [ ] Update `Reserved / Ordered Qty` in `Bin` based on Order Ledger

**Comment by harshit-30** [comment]
If this is still required, let's discuss if we want to reopen it.
