### ISSUE TITLE
It shows All zero in print format for Account receivable Summary

### ISSUE THREAD

**Issue by alfredhy** [frappe/erpnext#15971]
It shows values on web view but it shows zero when print or pdf. 
Web format
<img width="1152" alt="default" src="https://user-images.githubusercontent.com/30999458/48402756-62cc3d00-e767-11e8-9141-21ef1ab13de0.png">

Print format
<img width="779" alt="default" src="https://user-images.githubusercontent.com/30999458/48402702-39131600-e767-11e8-862c-2cb7ec378c9c.png">

Can you please help to fix it? 

Thanks,
Alfred

**Comment by deepeshgarg007** [comment]
Fixed #15976

**Comment by alfredhy** [comment]
<img width="1166" alt="default" src="https://user-images.githubusercontent.com/30999458/48544410-807fda80-e8fe-11e8-977f-6a9ee8f67142.png">
