### ISSUE TITLE
Version 11 can't make P.O from Material Request

### ISSUE THREAD

**Issue by hithamIsmail** [frappe/erpnext#15977]
can't make Purchase order from make button in Material Request Document but i can make suppliers Quotation and ask for quotation

**Comment by jodeq** [comment]
Linked to this issue : https://github.com/frappe/erpnext/issues/15949

**Comment by rushikesherp** [comment]
> can't make Purchase order from make button in Material Request Document but i can make suppliers Quotation and ask for quotation

Dear HithamIsmail,

Can you please check if this is indeed the duplicate of #15949. If yes,  Can you please close this?
