### ISSUE TITLE
Filters added on incorrect search : Unable to remove them without Page refresh

### ISSUE THREAD

**Issue by rushikesherp** [frappe/erpnext#15988]
Type a random word in Search bar when on a list view, and click on Find <Random Word> in Doctype
![image](https://user-images.githubusercontent.com/40016931/48530624-7b02a000-e8be-11e8-934a-9e3158c1a88c.png)
A blank filter gets created
![image](https://user-images.githubusercontent.com/40016931/48530649-92da2400-e8be-11e8-997b-87f521d0459c.png)
Try to remove that filter, Same error pops up again
if you click on refresh. Same error pops up again and additional blank filter gets created.
![image](https://user-images.githubusercontent.com/40016931/48530688-cc129400-e8be-11e8-8c04-69ee59f5bb72.png)

**Comment by rushikesherp** [comment]
Tested on 
Installed Apps
ERPNext: v10.1.68 (master)
Frappe Framework: v10.1.59 (master)

**Comment by rohitwaghchaure** [comment]
Fixed https://github.com/frappe/frappe/pull/6439
