### ISSUE TITLE
[Feature Request] Daily Budget Settings

### ISSUE THREAD

**Issue by kennethsequeira** [frappe/erpnext#15993]
In some industries/workplaces, a department/team has budget requirements on a daily basis.

The requirement is a simple setting which would allow users to enter a daily budget. If the limit is crossed for the day, the system will simply trigger a pop-up message saying that the _Daily Budget has been crossed_.

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.
