### ISSUE TITLE
Accounts Receivable Summary Report shows 0 in print

### ISSUE THREAD

**Issue by alfredhy** [frappe/erpnext#15994]
#15971 Still not fixed. 

Web version 
<img width="1159" alt="default" src="https://user-images.githubusercontent.com/30999458/48544907-a3f75500-e8ff-11e8-8090-2275e2610d44.png">

Print version
<img width="785" alt="default" src="https://user-images.githubusercontent.com/30999458/48544956-c25d5080-e8ff-11e8-8105-c9427ae9b8ce.png">

**Comment by kennethsequeira** [comment]
Issue is fixed in 11.0.3-beta.24. What version are you on?

**Comment by alfredhy** [comment]
Here is my version,
Installed Apps
ERPNext: v10.1.72 (master)
Frappe Framework: v10.1.62 (master)
