### ISSUE TITLE
Pimp multi-select in ERPNext dialogs on the UI

### ISSUE THREAD

**Issue by mseibert** [frappe/erpnext#16007]
Today a multi select in ERPNext is cumbersome and does not have a great UI. This is how the status quo works: https://cl.ly/fdcdf82041b3

![status-quo-multiselect](https://user-images.githubusercontent.com/3379670/48623592-626fb400-e9aa-11e8-8771-0b87e99df637.gif)

This is how a modern version of a multi-select works in Atlassian Jira: https://cl.ly/ec09d071148a

![multi-select-in-atlassian-jira](https://user-images.githubusercontent.com/3379670/48623626-774c4780-e9aa-11e8-9487-96c436346347.gif)

The internet is full of awesome samples how multi select can be solved. Like here: https://mdbootstrap.com/docs/jquery/forms/multiselect/

Can we get this pretty and usable UI ported to ERPNext somehow?

I do understand, that the table version as it is today offers additional options. And I can imagine, that you can use them in some cases. But in the cases that we have had, I have encountered people who just wanted a more intuitive and simple solution.

**Comment by PawanMeh** [comment]
Maybe you can do something like using "Add Multiple" button or leverage it's functionality to build what you wish

![add_multiple](https://user-images.githubusercontent.com/20460498/48936289-82662100-ef30-11e8-8223-c41ac52f74da.gif)

**Comment by mseibert** [comment]
@asbasawaraj showed me an implementation of @netchampfaris already.

https://cl.ly/5746dc7da774/table_multiselect.gif

I am waiting for a documentation on how to implement and use as part of the ERPNext docs now.

**Comment by asbasawaraj** [comment]
Thank you @mseibert for sponsoring this feature development.

Here is the link to documentation
https://erpnext.org/docs/user/manual/en/customize-erpnext/articles/table-multiselect

And here is the link to the announcement to the community on the forum.
https://discuss.erpnext.com/t/table-multiselect-feature-sponsored-by-seibert-media/44412
