### ISSUE TITLE
No permissions on child tables

### ISSUE THREAD

**Issue by gbm001** [frappe/erpnext#16008]
As described at:
https://discuss.erpnext.com/t/permissions-bugs-easy-access-to-child-tables-for-any-logged-in-user/42648/6
and previously reported through the Report Security thing with no response:

Child tables can be accessed trivially by any logged in user either using the whitelisted frappe.model.db_query.get_list function, or by using the frappe.client.get_list function and passing a parent doctype that does not match the child doctype being accessed (such as Communication, which all users have permission to access).

For example, in the JS console:

```javascript
frappe.call({
    method: 'frappe.model.db_query.get_list',
    args: {
        doctype: 'Purchase Receipt Item', limit: 20,
        fields: ['item_code', 'item_name', 'amount', 'description']
    },
    callback: function(r) {console.log(r.message);}
});
```
or
```javascript
frappe.call({
    method: 'frappe.client.get_list',
    args: {
        doctype: 'Purchase Receipt Item',
        fields: ['item_code', 'item_name', 'amount', 'description'],
        parent: 'Communication'
    },
    callback: function(r) {console.log(r);}
})
```

**Comment by gbm001** [comment]
I believe access to child doctypes has to be based on parent permission, and so any access to a child doctype should be roughly like this:
- Get the child doctype entry (without checking permissions)
- Get the parent and parent doctype from the child doctype entry
- Check permissions on the parent
- Raise permissions error as appropriate

Essentially a better check_parent_permission (at least for client queries) would fix get_list. The function db_query should probably not be white-listed in its current form?

**Comment by kennethsequeira** [comment]
@gbm001 will be communicating on this further via email
