### ISSUE TITLE
Issue with Quickbooks Migrator when running "rebuild_global_search"

### ISSUE THREAD

**Issue by chdecultot** [frappe/erpnext#16012]
Hi,

When trying to run `bench rebuild_global_search` on v11 I systematically get the following error:

`pymysql.err.ProgrammingError: (1146, u"Table '_database_.tabQuickBooks Migrator' doesn't exist")`

ERPNext: v11.0.3-beta.24 () (staging)
Frappe Framework: v11.0.3-beta.29 () (staging)

**Comment by gbm001** [comment]
I also get this error.

**Comment by gbm001** [comment]
Fixed in bench console by re-creating the table:

    from frappe.model.db_schema import DbTable
    qbtab = DbTable('QuickBooks Migrator')
    qbtab.create()
    frappe.db.commit()

**Comment by adityahase** [comment]
Duplicate of https://github.com/frappe/erpnext/issues/15856

**Comment by adityahase** [comment]
@gbm001 It shouldn't have fixed it like this
