### ISSUE TITLE
Shopify stock sync

### ISSUE THREAD

**Issue by taherkhalil** [frappe/erpnext#16011]
using 
ERPNext: v10.1.72 (master)
ERPNext Shopify: v2.0.26-3 (c607eb1) (develop)
Frappe Framework: v10.1.62 (master)

i created a private app and added a product in shopify and its stock , the item got created inside the erpnext upon sync but the stock is not getting reflected inside erpenext  , even though i have ticked the `sync shopify stock ` check .

Also is there a way to sync stock from erpnext to shopify  , i.e if stock is reduced inside erpnext , it will reduce inside shopify as well ?
i need this stock sync feature , please let me know if its available ,

willing to fund this if its not already there 
@saurabh6790 
Thanks .

**Comment by taherkhalil** [comment]
I updated to version 11 in staging branch and waited for it to sync again after an hour as manual sync was no longer there , but it did not sync at all .

**Comment by kennethsequeira** [comment]
The [shopify app](https://frappe.github.io/erpnext_shopify/) referenced has been discontinued. Since version 11, it is available in-app and the sync is one-way (Shopify to ERPNext order syncing).
