### ISSUE TITLE
Ascending/Descending Order Error

### ISSUE THREAD

**Issue by Mohd200** [frappe/erpnext#16021]
Good Day Everyone,

I have customized the '**Priority**' Docfield in "**Task**" DocType to a Standard Filter, So I can Ascend/Descend the order of Tasks based on the value of 'Priority'.
However, once I have done the customization on the "**Task**", I found that the order is not the same as the order of the Docfield. (Like, _Low-Medium-High-Urgent_). Instead, I find it to be in Alphabetical order, as in **_(High-Low-Medium-Urgent)_** in Descending order, and in Ascending order **_(Urgent-Medium-Low-High)_**.

**How can I make the Ranking Order goes _(Low-Medium-High-Urgent)_, just like the original order?**

If I have missed something or should there be the need to explain more, Please let me know.
Thank You

**Comment by kennethsequeira** [comment]
@Mohd200 kindly post such customization queries on the forum: https://discuss.erpnext.com
