### ISSUE TITLE
Account Tree Auto Expanding when adding children

### ISSUE THREAD

**Issue by Tropicalrambler** [frappe/erpnext#16023]
Actual Behavior:

When adding children to group account in chart of accounts tree view, all of the accounts automatically expand.

Expected Behavior:

When adding children to group account, only the group account to which the children is being added should expand. All other accounts should retain their expanded/collapsed state.

More on this:

When user is in the process of creating many accounts manually, they will set up the tree view to expand only the group account which contains the accounts under which they desire to create the new children. When they click "Add Child", the dialog pops up, account name and number is entered along with other data needed.  Upon clicking "**Create New**", the account is created, but any other accounts at the same level of the parent account, if they have children, will see those children expanded. In the creation context it is inconvenient to have this because the accounts just pop further down, forcing the user to scroll down to find the newly created account. 

I favor the static presence of the created account, where the other accounts (at same level as parent account of child just created) do not expand. This allows users to go through the process of creating a handful of accounts much faster, providing a better UX experience.

**Comment by harshit-30** [comment]
Please create another issue if it is replicable after v13.10.
