### ISSUE TITLE
Sales Invoice - Fetch Item via Barcode doesn't work

### ISSUE THREAD

**Issue by Salmanmulani** [frappe/erpnext#16032]
- Copied Barcode from Item name
- Pasted in the Barcode field
- Item doesn't fetch

https://imgur.com/a/KUAQnBD

**Comment by Zlash65** [comment]
![image](https://user-images.githubusercontent.com/11695402/48891886-9f342300-ee62-11e8-8b6d-2d5e019ba6bd.png)

Use the child table for barcode as a single item can have multiple forms of barcode. The barcode field is obsolete now and will be removed with a patch to copy its data from the field to child table.

**Comment by aldrenalin** [comment]
It appears that the obsolete barcode field has not been removed as of the current Release, V11.1.4.

**Comment by harshit-30** [comment]
@Salmanmulani It works now!
