### ISSUE TITLE
Prepared Report - System user cannot configure

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#16057]
When I try to set standard report like Account Receivable as a prepared report, it doesn't work due to this validation. Should we have separate setting for Prepared Report?

<img width="1222" alt="screenshot 2018-11-22 at 1 14 56 pm" src="https://user-images.githubusercontent.com/910238/48888497-e74e4800-ee58-11e8-9945-9e7e74a72c43.png">

**Comment by nabinhait** [comment]
It is automated, if any report takes more than 20/30 seconds, it automatically enables prepared report mode.
Otherwise, we have to do it in standard product.
