### ISSUE TITLE
Physician - Time per appointment and Patient appointment time permits double booking

### ISSUE THREAD

**Issue by MrPeters93** [frappe/erpnext#16068]
Physician A has a schedule with 15 minute time slots and an appointment time of 15 minutes.
Patient A gets booked in the time slot 09:00 and the appointment gets marked for a duration of 30 minutes.
Patient B can still get booked in the time slot 09:15 even though Patient A's appointment will overlap this time.

A potential solution to this is either allow the choice of number of time slots the appointment will use up or the ability to select X amount of minutes and automatically use up the required amount of slots.
An other solution is to use up the time slots requierd when one changes the amount of time a patient appointment will use up but this could result in the booking of an appointment while changing the setting if two users are booking appointments at the same time.

PS: First time reporting an issue here and I checked if an issue of similar topic were up but I did not find one. Let me know if additional information is required.

**Comment by akurungadam** [comment]
Thanks for reporting. Looks like you are on ERPNext master, could you please post the version you are trying out with? The Appointment booking process has gone through some enhancements and most of it is available as part of the v11 staging branch. Please note that #16066 is yet to be merged and contains many of the major changes in this area. 

As for your suggestion, yes we are also trying to implement another way where in practitioners can make their availability published for a period with an option to set the number of encounters (or the duration) the practitioner will do in each of the available days / slots. 

And yes, do post issues here; you can follow [this](https://github.com/frappe/erpnext/wiki/Issue-Guidelines) if you haven't already looked it up.  If in doubt please get on [discuss](https://discuss.erpnext.com)

**Comment by MrPeters93** [comment]
Correct, I'm on v10.1.73 (master).

Thanks for the detailed reply and for the information!
