### ISSUE TITLE
frappe.rename_doc() does not update Global Search Strings

### ISSUE THREAD

**Issue by SaiFi0102** [frappe/erpnext#16062]
Reopening https://github.com/frappe/erpnext/issues/15771 since it isn't solved.

I copied an instance of ERPNext and applied frappe.rename_docs and changed abbreviation of company and none of the global search strings have been updated.

# Ex 1:
Changed names DN-CT-2018-##### to DO-CT-2018. Global Search Strings still show incorrect links to DN.
![dos](https://user-images.githubusercontent.com/328330/47373442-507d5700-d705-11e8-884b-0535a98ba222.png)
![dns](https://user-images.githubusercontent.com/328330/47373443-507d5700-d705-11e8-810a-db27983ec94a.png)

# Ex 2:
Renamed company and abbreviation. None of the related docs are updated in global search strings.
![tatc](https://user-images.githubusercontent.com/328330/47373453-583cfb80-d705-11e8-8f81-6a9a3f3823c5.png)
![capitaltraders](https://user-images.githubusercontent.com/328330/47373454-583cfb80-d705-11e8-9e97-2c7399886d79.png)

**Comment by deepeshgarg007** [comment]
@SaiFi0102 Company Abbr is not allowed to be renamed anymore in the latest versions so this is not applicable now, closing this issue
