### ISSUE TITLE
Task Depends on not removed from Gantt chart

### ISSUE THREAD

**Issue by dufani1** [frappe/erpnext#16064]
Hiiii..
I noted that the (task depends on arrows) still existed after removing from task form.
Version is 10.1.72
I reloaded list many times... but the arrows not removed.
![untitled](https://user-images.githubusercontent.com/23026263/48918127-534da200-ee93-11e8-89ae-ebf341475470.png)

**Comment by joolsr** [comment]
I think this may be related to the Gantt chart lib update as some other parts of Gant charts got broke at same time. There is a fix just released or soon to be to force an update if the Gantt chart lib

**Comment by valentincauro** [comment]
+1
