### ISSUE TITLE
Clicking on the Reset button in the Portal settings changes the labels of the Title column to another Language

### ISSUE THREAD

**Issue by rushikesherp** [frappe/erpnext#16085]
Steps to reproduce.

1) Go to the Portal settings page.
2) Change the Default role at the time of signup.
2) Click on the reset button.

![image](https://user-images.githubusercontent.com/40016931/48997190-1b857980-f175-11e8-92b5-3c3458717f3c.png)

![image](https://user-images.githubusercontent.com/40016931/48997250-4ff93580-f175-11e8-92c5-8e5d477c18f9.png)
 
Tested on 
ERPNext: v10.1.72 (master)
Frappe Framework: v10.1.62 (master)

**Comment by deepeshgarg007** [comment]
Closing this issue. If the issue still persists in the latest version-13 or above then please reopen a new issue
