### ISSUE TITLE
Cannot Create variants 

### ISSUE THREAD

**Issue by Ravn10** [frappe/erpnext#16116]
ERPNext: v10.1.72 (master)
Frappe Framework: v10.1.64 (master)
Showing permission error even when logged in by Administrator user 

<img width="1212" alt="screenshot 2018-11-28 at 1 51 06 pm" src="https://user-images.githubusercontent.com/29272682/49140233-c5057000-f319-11e8-8c1b-83bddc91cdf2.png">

**Comment by saqibrazzaq** [comment]
Same issue in the latest release. Even with Administrator user, cannot add a variant.

ERPNext: v10.1.73 (master)
Frappe Framework: v10.1.65 (master)

**Comment by cgpurbaugh** [comment]
I can also confirm that this is a problem in the latest release.

**Comment by ophl55** [comment]
The same for me:
https://github.com/frappe/erpnext/issues/16075
