### ISSUE TITLE
Trial Balance Accumulated Depreciation Opening Balances Appear as -ve entries on Opening Dr, instead of as +ve values on Opening Cr-ERPNext: v11.0.3-beta.10 () (staging)

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#16135]
This is more of a clarification, is there a reason this is the case?

![capture](https://user-images.githubusercontent.com/1822868/49326411-15234300-f563-11e8-8cb7-805855437f6b.PNG)

**Comment by clarkejj** [comment]
Please raise this for discussion on the forum and add a link here thanks

**Comment by muchai** [comment]
Ok. Will do that.

**Comment by muchai** [comment]
https://discuss.erpnext.com/t/trial-balance-accumulated-depreciation-opening-balances-appear-as-ve-entries-on-opening-dr-instead-of-as-ve-values-on-opening-cr/43474
