### ISSUE TITLE
Item Variants Error

### ISSUE THREAD

**Issue by rtea** [frappe/erpnext#16157]
Hello

I am getting an error every time I try to create an Item variant.  I need to get it fixed ASAP to set up new products. I have seen there are some fixes to this issue but I have no idea how to implement them.  Can anyone give me an idiots guide on how to fix this issue the simplest way possible? Is there an update I can install as I don't really understand how I amend the source code as I just use ERPnext in the browser.

Can anyone help me please?

Thanks

Ross

**Comment by agritheory** [comment]
Hey Ross @rtea, what versions of Frappe and ERPNext are you running, and on what operating -system? The "About" link will give you a pop up with details. 

![image](https://user-images.githubusercontent.com/18033666/49480958-bbd34200-f7f6-11e8-84c8-5dc806eafc70.png)

**Comment by agritheory** [comment]
Those are the latest versions. Where is your installation hosted?

**Comment by rtea** [comment]
I just use the web portal to do everything so not set up any special hosting, so I suppose that means default settings?

	Website: https://frappe.io

	Source: https://github.com/frappe

**Comment by agritheory** [comment]
Web portal as in erpnext.com? If that's the case you need to raise a ticket with them. https://erpnext.com/contact

**Comment by rtea** [comment]
Ok, thank you. I will do that!
