### ISSUE TITLE
Three doctype combine in One doctype

### ISSUE THREAD

**Issue by Audrey014** [frappe/erpnext#16162]
Good morning, can you help me for my logical thinking or ways because on this form I have three doctype here that combine in 1 doctype. I will explain by A,B AND C doctype. The c is a table, and I will create the B, the B is the form also that have C that answered by B Form. Then in A Doctype I want to appear the doctype B that has doctype C table that already answered by B. Can you help me?

**Comment by joolsr** [comment]
Hello Audrey014

It would be much better if you can submit your help request on the forum instead. There are many more people taking part in the forums who can help.

I will close this issue as it is not an Issue with ERPNext per se.

Thanks
