### ISSUE TITLE
[Staging][BUG] Customer master fields not loading 

### ISSUE THREAD

**Issue by azhar-aa1207560** [frappe/erpnext#16183]
RPNext: v11.0.3-beta.26 () (staging)

Frappe Framework: v11.0.3-beta.34 () (staging)

<img width="1252" alt="screen shot 2018-12-10 at 4 05 16 am" src="https://user-images.githubusercontent.com/25772511/49705638-e1b27980-fc30-11e8-9642-00aafe72f2f0.png">

Just updated to the latest staging. Now when I create new customers, this happens. None of the fields load.

**Comment by sagarvora** [comment]
Hello,

Try refreshing (Ctrl + Shift + R on Chrome / Firefox)
If the issue still persists, check the console for errors. Post those here.

**Comment by sagarvora** [comment]
@shubhamgupta123 Thanks, I have identified the error and will send a PR soon.
