### ISSUE TITLE
failed to load items in Item List View

### ISSUE THREAD

**Issue by jvfiel** [frappe/erpnext#16181]
![selection_681](https://user-images.githubusercontent.com/4990791/49699482-cfbedf80-fc0c-11e8-82a4-9ac56b670d68.png)

![selection_680](https://user-images.githubusercontent.com/4990791/49699471-b87ff200-fc0c-11e8-802f-0b9952405163.png)

**Comment by shreyashah115** [comment]
@jvfiel Which version are you on? Also, is the field `disabled` hidden on your Item's form?

**Comment by heatherpotter** [comment]
I think it's a bug. I get the same thing every time I open ITEMS. I haven't selected or changed anything. I get the same error twice and no items show in the list view ever.

**Comment by jvfiel** [comment]
Hi @shreyashah115 , tried unhiding "disabled" field still getting the same error.

**Comment by shreyashah115** [comment]
@jvfiel You will have to disable the 'Report Hide' property for `disabled` field and the error shall not pop up again.
