### ISSUE TITLE
Issue on Sales of asset

### ISSUE THREAD

**Issue by Midi1985** [frappe/erpnext#16193]
I have a transaction related to a fixed asset sale. The book value of the fixed asset is Zero (0) & I want to sell this at a cost determined by the management. When clicked on the “Sell Asset” of the particular item, it goes to a new invoice & CR a/c is shown as “Gain/Loss on Asset Disposal” & DR to Debtors. I inserted the amount of the sales value, filled other mandatory fields & clicked submit. then it says DR & CR values are not matching & difference is so & so amount (the rate of the item that i put)
ls find attached screenshot of the error

**Comment by Midi1985** [comment]
![erpnext](https://user-images.githubusercontent.com/37651163/49786609-730b1400-fd35-11e8-85db-53771e6d341f.PNG)

**Comment by deepeshgarg007** [comment]
@Midi1985 I was unable to replicate the issue. Can you please provide some more information to replicate the issue and on which version are you facing this issue?

**Comment by Midi1985** [comment]
Dear Deepesh,

We have one of the fixed assets that was totally depreciated by the end of last year & this year the value of the asset is zero. Then we sold this asset at a cost for which I want to use the option “sale asset” under the same item. When I did, the link goes to an invoice & the income accounts automatically goes to “gain/ loss on sales of assets”. When I submit this, an error causes saying that the debit & credit values are not matching.

Attached screenshot for your ref.

 

Looking forward to your assistance,

**Comment by deepeshgarg007** [comment]
@Midi1985   Closing this issue. If the issue still persists in the latest version-13 or above then please reopen a new issue
