### ISSUE TITLE
Mass attendance upload tool takes employee data from 1st of every month instead of DOJ

### ISSUE THREAD

**Issue by reema30** [frappe/erpnext#16200]
If an employee joins on 19th of a month, his attendance should be calculated from that day. But while mass uploading attendance, the template takes from day 1 of the month instead of DOJ. You come to know only when import fails.

**Comment by reema30** [comment]
@palashjhabak - yes tried. So when I do manually for a particular day before employee's DOJ, it does not show his name. The problem is only for mass upload of attendance.

**Comment by reema30** [comment]
Another issue for the same.. An employee has joined on 1 Jan 19. Screenshot attached. But when I download attendance template for bulk update for period 1 Dec 18 to 31 Dec 18, his name appears when he had not even joined.
![screen shot 2019-01-03 at 12 43 03 pm](https://user-images.githubusercontent.com/45488333/50626938-22af5c80-0f57-11e9-9e0c-5333695ee73e.png)

**Comment by sahil28297** [comment]
fixed https://github.com/frappe/erpnext/pull/16279
