### ISSUE TITLE
After upgrading to ERPNext: v11.0.3-beta.30 (staging) visual notification disappear

### ISSUE THREAD

**Issue by giodc** [frappe/erpnext#16229]
After upgrading to ERPNext: v11.0.3-beta.30 (staging) all the number of items and notification on top right disappear, for example the Support do not display anymore the number of issue there, in Project and task also there is no number of active project and task, both on doctype and on the notification on top right. 

top right, no items appear anymore

![screen shot 2018-12-17 at 10 48 53 am](https://user-images.githubusercontent.com/2741044/50101904-667d3480-01e9-11e9-8bc0-72784e4927b5.png)

no item appear, also on Desk, no more item number appear on screen

![screen shot 2018-12-17 at 10 49 07 am](https://user-images.githubusercontent.com/2741044/50101928-739a2380-01e9-11e9-9f91-47e613b1d5a5.png)

Installed Apps
ERPNext: v11.0.3-beta.30 () (staging)
Frappe Framework: v11.0.3-beta.37 () (staging)

**Comment by clarkejj** [comment]
This reports fixed in beta.38 https://discuss.erpnext.com/t/notification-bar-not-showing/43586/11

**Comment by clarkejj** [comment]
Reports confirm this now works as expected
