### ISSUE TITLE
[Proposal] Split POS into smaller files

### ISSUE THREAD

**Issue by barredterra** [frappe/erpnext#16237]
At the moment, the [Point of Sale](https://github.com/frappe/erpnext/blob/develop/erpnext/selling/page/point_of_sale/point_of_sale.js) page is a giant 1700 lines JS file. I propose to make a separate file for each class which creates a structure like this:

├── point_of_sale.js (entry point, 30 lines)
├── point_of_sale.json
├── point_of_sale.py
└── src
&nbsp;&nbsp;&nbsp;&nbsp;├── point_of_sale.js
&nbsp;&nbsp;&nbsp;&nbsp;├── number_pad.js
&nbsp;&nbsp;&nbsp;&nbsp;├── payment.js
&nbsp;&nbsp;&nbsp;&nbsp;├── pos_cart.js
&nbsp;&nbsp;&nbsp;&nbsp;└── pos_items.js

This could be a first step in refactoring POS to make it more modular, configurable and maintainable. 
Please let me know what you think about this.

**Comment by SaiFi0102** [comment]
and maybe even try to merge functionalities between offline and online POS
