### ISSUE TITLE
Add validation for credit note amount against sales invoice

### ISSUE THREAD

**Issue by deepeshgarg007** [frappe/erpnext#16244]
Credit note amount should not be greater than paid amount for a particular invoice

For Eg:If a sales invoice has a grand total of Rs 100 and a payment of Rs 30 has been made against that invoice then credit note amount against that invoice should be less than or equal to Rs 30

Currently there are no validations for it.

**Comment by harshit-30** [comment]
@deepeshgarg007 is there any update on this?
