### ISSUE TITLE
demo.erpnext.com requires login!?

### ISSUE THREAD

**Issue by clarkejj** [frappe/erpnext#16240]
See this discussion https://discuss.erpnext.com/t/https-demo-erpnext-com-requires-login/43642

**Comment by clarkejj** [comment]
now works thanks!

**Comment by rohitbanerjee** [comment]
> now works thanks!

What was the solution? The problem still persists ..

**Comment by kennethsequeira** [comment]
demo.erpnext.com re-factored to erpnext.com/demo
