### ISSUE TITLE
The child tables of Supplier Scorecard does not have a preconfigured fetch

### ISSUE THREAD

**Issue by Don-Leopardo** [frappe/erpnext#16255]
I was trying to create a Supplier Scorecard, but there are some hidden fields that are mandatory and does not have the correspondent "fetch" option presetted. Although the main problem is with the "variables" child table, the other child tables are missing some "fetch" options too (all of them really).
And I see that is_custom, in Supplier Scorecard Scoring Variable, is mandatory, is that intended?

ERPNext: v10.1.75 (master)
Frappe Framework: v10.1.68 (master)

Here are some gifs:
Creation and Supplier Scorecard Scoring Standing:
![First child table](https://media.giphy.com/media/4PXO1w2s9kl5i9a6na/giphy.gif)

Supplier Scorecard Scoring Criteria:
![Second child table](https://media.giphy.com/media/w7lHY5MgsSoq4Yw4I7/giphy.gif)

Supplier Scorecard Scoring Variable:
![Third child table](https://media.giphy.com/media/t6JygL94z2LGFvEIoj/giphy.gif)

Missing fields error:
![Final error](https://media.giphy.com/media/7WFKwxB0ow6OZDmPIp/giphy.gif)

**Comment by fproldan** [comment]
+1
