### ISSUE TITLE
Quality Inspection Submit stage validation is missing. DN/PR is allowed to be in Submit stage with QI in Draft

### ISSUE THREAD

**Issue by FinForce** [frappe/erpnext#16250]
I have set up Quality Inspection ('QI') criteria at item level for 'Inspection Required before Delivery'. On creation of Delivery Note ("DN"), it requires me to put QI report. From the Item table inside DN, I click 'more arrow" and go to 'Warehouse and Reference' section. Under this on "Quality Inspection" field, I click on 'Create new Quality Inspection'

The new window of Creation Quality Inspection is opened, I fill in all the required details & click 'Save". Quality Inspection windows are closed without requiring a Submit of QI report.

Also, if for some reason User comes back to the Item line and unselect the QI report tagged above and assign it again, it will not show in the drop down unless the QI report is into Submit stage.

In my scenario, I could submit my DN with one item having QI in Submit stage and another item with QI in draft stage. See the screenshot below.

![image](https://user-images.githubusercontent.com/31281816/50274160-866b5d00-0462-11e9-9caf-576931216ff0.png)

Here is the list of QI reports. For Row# 2 in item table under DN, it's into the Submitted stage and Row# 3 into Draft

![image](https://user-images.githubusercontent.com/31281816/50274327-fe398780-0462-11e9-8757-0f4c63a0c387.png)

**Issue Summary:** Validation of checking the QI into the Submitted stage is missing before permitting DN submission.

**Comment by FinForceConsulting** [comment]
The above issue I noticed in v10, I have an instance of ERPNext: v10.1.74 (master).

I tried replicating this same on v11 and it does waits for the 'Submit' of QI document and then attaches it

**Comment by Anurag810** [comment]
Fixed by #16289 will be merge soon
