### ISSUE TITLE
Error on inputting user password-Ver11

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#16261]
On input of user password, the system pops up the below error, but the password is still changed, and emailed appropriately.

![image](https://user-images.githubusercontent.com/1822868/50371783-7a9ea880-05d2-11e9-9150-35dc84331f4d.png)

**Comment by kennethsequeira** [comment]
Couldn't replicate this in my v11 test site.

Kindly check **Error Logs** in your site and review. You can also post the error on the [forum](https://discuss.erpnext.com) where members can assist to debug this. 

Please also post the exact versions of ERPNext and Frappe so members can help to debug.
