### ISSUE TITLE
Set Desktop Icons does not respond, i.e. open the page, as it used to before-v11.0.3-beta.30

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#16262]
![image](https://user-images.githubusercontent.com/1822868/50371810-fac50e00-05d2-11e9-88a6-622fdddd0899.png)

**Comment by muchai** [comment]
![image](https://user-images.githubusercontent.com/1822868/50371801-d10be700-05d2-11e9-9253-edc0d01e71b4.png)

**Comment by muchai** [comment]
![image](https://user-images.githubusercontent.com/1822868/50371804-dcf7a900-05d2-11e9-8154-fde68d305b1b.png)

**Comment by pipech** [comment]
It has been fixed and merged to staging-fixes.

https://github.com/frappe/frappe/issues/6660
