### ISSUE TITLE
V11 bug Asks for attributes when creating variant based on manufacturer

### ISSUE THREAD

**Issue by ovresko** [frappe/erpnext#16280]
After creating item model nd variant based on manufacturer when i hit make variant it asks for manufacturer and number -> fill & make -> it shows a message asking for at least one attribute in attributes table. is it mandatory to fill attributes while using based on manufacturer ?
it works fine when using quick edit and check make variant.

**Comment by vrms** [comment]
I confirm this still remains on

- ERPNext: v11.1.18 (master)
- Frappe Framework: v11.1.18 (master)

**Comment by ovresko** [comment]
I found the problem
so far the problem is here https://github.com/frappe/erpnext/blob/af309473f8c81a3a705b4cc869dd202d18266aaa/erpnext/stock/doctype/item/item.js#L375

// code
```
show_modal_for_manufacturers: function(frm) {
var dialog = new frappe.ui.Dialog({
fields: [
{fieldtype:‘Link’, options:‘Manufacturer’,
reqd:1, label:‘Manufacturer’},
{fieldtype:‘Data’, label:‘Manufacturer Part Number’,
fieldname: ‘manufacturer_part_no’},
]
});
```
where in the Dialog, here the fields are missing the fieldname: ‘manufacturer’ like manufacturer_part_no has.
final code should be
```

var dialog = new frappe.ui.Dialog({
    			fields: [
    				{fieldtype:'Link', options:'Manufacturer',
    					fieldname: 'manufacturer', reqd:1, label:'Manufacturer'},
    				{fieldtype:'Data', label:'Manufacturer Part Number',
    					fieldname: 'manufacturer_part_no'},
    			]
    		});
```
add fieldname: ‘manufacturer’, and bench build and should be fixed
I hope someone can push this fix asap

**Comment by sharmanakul** [comment]
Hi @ovresko i checked it on v13.14 and on creating item based on the manufacturer, i am not prompted to provide attribute. Please reopen if the issue still persists.
