### ISSUE TITLE
V11 error chat, Uncaught TypeError: Cannot read property 'seen'

### ISSUE THREAD

**Issue by ovresko** [frappe/erpnext#16281]
can't use chat 
console error:
Uncaught TypeError: Cannot read property 'seen' of null
    at Object.onclick [as click] (chat.js:1994)
    at HTMLAnchorElement.s (hyper.min.js:1)
onclick @ chat.js:1994
s @ hyper.min.js:1

**Comment by clarkejj** [comment]
See also https://discuss.erpnext.com/t/server-error-on-using-chat-v11-upgraded-to-v12/51143
