### ISSUE TITLE
V11 bug in item wise  price list view

### ISSUE THREAD

**Issue by ovresko** [frappe/erpnext#16292]
Error when trying to edit/view prices per item in item details, when click on repports item price per list.

![image](https://user-images.githubusercontent.com/32199620/50450998-9d61f180-0931-11e9-893c-b93fc3a249d2.png)

**Comment by saurabh6790** [comment]
Seems its a Report. Please edit Item Price via Item Price document's list view or report view.

**Comment by ovresko** [comment]
> Seems its a Report. Please edit Item Price via Item Price document's list view or report view.

Thank you, but it's not only in this view i found it in multiple repports 
example : sales order trends

![image](https://user-images.githubusercontent.com/32199620/50451596-50801a00-0935-11e9-9610-38c48b7989af.png)

i did rebuild also
