### ISSUE TITLE
need instalation process step by step for cpanel

### ISSUE THREAD

**Issue by mdamin1129** [frappe/erpnext#16305]
someone please advise me how to install frappe/erpnext in self-hosting (server) through cpanel.

**Comment by joolsr** [comment]
Hi

This isn't really an Issue so to speak therefore I will close this.

Please post your query on the forum instead.

NB it's likely that you will not be able to install on a clanel installation as you need full SSH access and the ability to run long running processes such as python to run ERPNext.

You really need a full virtual machine such as a small Linode.com, and not just low cost web hosting as this will not permit you to install and run the application.

**Comment by dinulk** [comment]
what is the reason for this
Warn : bench is installed in editable mode
