### ISSUE TITLE
Overseas GST providers are not recognized

### ISSUE THREAD

**Issue by anandvenkatanarayanan** [frappe/erpnext#16300]
GST regime allows a new class of providers called "Non Resident service providers". More explanation is provided here: 
https://cleartax.in/s/gstr-5a 

Since they have no presence, there is no state of supply and they are instead given a GST number that starts with 99. For instance, Adobe uses Digital River to manage subscriptions in india, and the GSTIN number for Digital river is **9917IRL29003OSG**

This is a valid GSTIN number and can be verified as valid from the GST Portal (See screenshot attached)
<img width="1226" alt="image" src="https://user-images.githubusercontent.com/6889702/50502379-dd85b900-0a84-11e9-9138-10555c713382.png">

ERPNext however thinks that this is an invalid GST number, which is inaccurate. See Screenshot
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/6889702/50502412-0b6afd80-0a85-11e9-8a11-667b71749aef.png">

This ought to be fixed.

**Comment by test2a** [comment]
sure. this should be a quick fix as all they have to do is add the "99" as a state code for the "Non Resident service providers" . the rest of the validation rules should be fine

**Comment by deepeshgarg007** [comment]
@anandvenkatanarayanan fixed via https://github.com/frappe/erpnext/pull/17866
Closing this issue
