### ISSUE TITLE
Filter by Account in Receivable/Payable Summary Aging Reports

### ISSUE THREAD

**Issue by hballan** [frappe/erpnext#16320]
Please add ability to filter by account in the Receivable/Payable Summary Aging Reports

**Comment by FinForceConsulting** [comment]
@hballan 
please share the screenshot of the current report you looking at and what/where filters you need?

These points would help address the issue better (from the https://github.com/frappe/erpnext/wiki/Issue-Guidelines
- Version Number
- Actual behavior
- Expected behavior
- Screenshots: Screenshots are a great way of communicating the issues. Try adding annotations or using LiceCAP to take a screencast in gif.

**Comment by hballan** [comment]
It would be extremely helpful and simple to implement to add a simple by account filter to the AR/AP Summary Aging Reports. Please see attached screenshots. 

![ap](https://user-images.githubusercontent.com/34502442/50629922-a82f0e80-0f4f-11e9-87ed-ed47b9955d73.PNG)
![ar](https://user-images.githubusercontent.com/34502442/50629923-a82f0e80-0f4f-11e9-9d64-30b85dc5e683.PNG)
![billing](https://user-images.githubusercontent.com/34502442/50629924-a82f0e80-0f4f-11e9-9818-ff2fa1f01a96.PNG)

**Comment by hballan** [comment]
Here is the version info

![image](https://user-images.githubusercontent.com/34502442/50630131-9f8b0800-0f50-11e9-9ee8-35e7f0e1691d.png)

**Comment by FinForceConsulting** [comment]
In my version, I see several filtering options marked with arrows.
- ERPNext: v11.0.3-beta.32 () (staging)
- Frappe Framework: v11.0.3-beta.46 () (staging)


![image](https://user-images.githubusercontent.com/31281816/50632027-8abc6d80-0f6c-11e9-816a-e96009d8f9ab.png)

**Comment by hballan** [comment]
Yes, the only thing you have extra over my version is the [Supplier Group] as version 10 only has [Supplier] filter. But what I am requesting is to have an additional filter for [Account] this would be super useful and is very easy to implement.

**Comment by hballan** [comment]
What I mean by account is [GL Account] to make it clear

**Comment by FinForceConsulting** [comment]
In Accounts Payable report the only GL you would see is 'Purchase' & In Accounts Receivable report the GL would be "Sales".  Why would you like to filter them? please help me understand.

**Comment by hballan** [comment]
Because we are using the party field through JVs to link to employees to keep track of employee loans, to do quarterly distribution of prepaid expenses by supplier and quarterly distribution of unearned income by customer. This allows us to breakdown prepaid expense by Supplier, unearned income by Customer and to handle employee loans using one account and then filtering by party in the GL. The way we have set this up is very useful and saves a lot of time.

These entries should not show up in the Receivable/Payable summary as they are not related to billing, but the way things are now there is no way to exclude these. So simple way to filter them out is to just filter by GL Account.

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.
