### ISSUE TITLE
Multiple Currency in Journal Entry

### ISSUE THREAD

**Issue by Green-Iraq** [frappe/erpnext#16349]
Multiple Currency in Journal Entry for Expenses
In our company we are using two currencies; IQD and USD. Sometimes the same expense account we spend in both currencies. Let's say we have an expense account named "Telephone Bills". One time we spend 100USD against this account. Another time we make 25000IQD against this same account. Is there any way to add two currencies to such account? If not, how to deal with this?

**Comment by kennethsequeira** [comment]
You can't deal with the same account in two currencies. Either you:

1. Post all expenses in local currency

2. Create a separate account head for expenses under USD currency and make the postings there.

For more details: https://docs.erpnext.com/docs/user/manual/en/accounts/multi-currency-accounting

If any more queries on the same remain, open a new thread on the [forum](https://discuss.erpnext.com).
