### ISSUE TITLE
Payroll in V11

### ISSUE THREAD

**Issue by hballan** [frappe/erpnext#16343]
I have been testing ERPnext V11 Beta and although there are some nice improvement in the payroll workflow there are still major issues which can be easily addressed that would make an enormous difference.

Payroll is probably one of the most complex functions in any company and there are all sorts of local laws this why many accountant always recommend getting a local package that complies with the regulations in your region and to simply enter the JV from that system in your main accounting software.

It is extremely important for the payroll workflow to be as flexible as possible so it can handle all these scenarios and that can be easily done by just not letting the [Salary Structure] override the [Salary Slip] on saving. Payroll is always reviewed and signed off on so there is no need for the rigidity in the workflow.

We have many components as part of our payroll for tax withholding, employee loans, overtime, bonuses. Ideally what we would like to do is have one [Salary Structure] per job position which contains all the possible components properly linked up to the GL for that position. This should be used as a template just to speed up the creation of slips and you must have the ability to override it manually for the individual monthly slips.

The workflow would look something like this:
1. You run the payroll entry, it creates the slips
2. You go through the slips individually making all the month specific adjustments, like entering adding overtime, deducting absence, deducting loans, adding bonuses, removing entirely some components if they don't apply for that particular month and finally save the slips
3. You submit the payroll entry and the corresponding JV is created.

The problem is that ERPNext doesn't allow you to modify the slips before posting the payroll entry. Any change you make to the slips always reverts back to the salary structure on saving. This is really annoying as of V10 we now have to do all these month changes from the salary structure itself for this to work and it gets really cumbersome constantly changing salary structures and moving employees from structure to structure. And after testing V11 it's even worse as now the [Salary Structure] document can't be simply modified and saved it has to be cancelled amended and then resubmitted.

Please please please consider this simple easy to implement change it would make life sooooo much easier. At the least have it as a simple option that the slip can be manually modified before submitting without reverting back to the salary structure for users who want this flexibility. For users who don't have this variability in components in their payroll and don't need the flexibility they can just turn this option off and have the [Salary Structure] be strictly enforced.

Oh and a simple thing which is critical please allow us to select the [Naming Series] before creating the [Payroll Journal Entry], as of V10 there is no way to do this it just uses the first naming series available as default and it gets confusing specially when you have multiple companies. This can be easily added on the [Payroll Entry Screen] before submitting.

**Comment by aakvatech** [comment]
Apart form allowing the Salary Structure Earnings and Deductions tables Allow on Submit, I think the structure works well.

The Additional Salary doctype allows for additions to be done in such a way that any number of time the salary slip is regenerated, it picks up all the changes.

I would recommend the below updated to be incorporated to increase flexibility.

update `tabDocField` set allow_on_submit = 1 where parent = 'salary structure' and fieldname in ('earnings', 'deductions', 'total_earning', 'total_deduction', 'net_pay');

**Comment by musaddiqsajjad** [comment]
Facing the same issue, it is imperative that the above suggestions be incorporated into the standard payroll workflow.

A lot of organizations need ad hoc changes for Salary Slip before submitting and JV creation.

EDIT: This comment is null and void, ad hoc changes are carried forward to both Accrual Journal Entry for Payroll Payables and Bank Entry through Payroll Entry.

Tested in version v13.0.0-beta.6 (version-13-beta)
