### ISSUE TITLE
Save different Print Template for Sales Invoice

### ISSUE THREAD

**Issue by Kipperlenny** [frappe/erpnext#16367]
If I create a Sales Invoice, click on the print icon and change the Template Dropdown - I have no Button to save this dropdown selection. I can go back to edit the invoice, but this does not save my dropdown Selection.

![save](https://user-images.githubusercontent.com/563328/50861378-c4400f00-1398-11e9-8d63-b49413e6208b.JPG)

How can we create an invoice with a different Invoice Print Template?

The **Template Selection during Invoice Creation should be saved for this invoice**. The E-Mail PDF should also use this Template Selection.

**Comment by kennethsequeira** [comment]
@Kipperlenny you can always make a custom template default in the print format:

![image](https://user-images.githubusercontent.com/33246109/56865097-b534a980-69e7-11e9-8e86-14f794e85589.png)

**Comment by Kipperlenny** [comment]
I don't want to make one template DEFAULT for all invoices - I want to save ONE template for ONE invoice.
See my screenshot, on the left site the dropdown selection does not get saved if I click on "Edit" again (on top right).
