### ISSUE TITLE
Descending sort for naming series does not work for list view

### ISSUE THREAD

**Issue by azharul-islam** [frappe/erpnext#16366]
![ezgif-5-84be23a61e46](https://user-images.githubusercontent.com/38819502/50849370-e4b39d80-1387-11e9-9650-dc084a9dda31.gif)

ERPNext: v11.0.3-beta.34 () (staging)
Frappe Framework: v11.0.3-beta.48 () (staging)

**Comment by Zlash65** [comment]
![sort-by-name](https://user-images.githubusercontent.com/11695402/51188012-10440400-1903-11e9-8f33-2a8ee31202ee.gif)

ERPNext: v11.0.3-beta.34 () (staging)
Frappe Framework: v11.0.3-beta.49 () (staging)

Seems to be working just fine.

**Comment by kennethsequeira** [comment]
still existing in 
ERPNext: v11.1.14 (master)
Frappe Framework: v11.1.14 (master)

**Comment by ankush** [comment]
sort by name instead? `series` field is naming series, not the name so it's pretty much same on all invoices unless you use multiple series 😄 This is mostly just confusion IMO.
