### ISSUE TITLE
Lab Test process only done after receiving the payment 

### ISSUE THREAD

**Issue by sugurujay** [frappe/erpnext#16373]
Hello, In healthcare domain, a patient is eligible for lab test only when the patient is done invoice payment. Else it should show a pop up/message that payment is not done. How can be achieved this ?

**Comment by akurungadam** [comment]
Healthcare Settings allows you to configure automatic creation of Lab Tests on Sales Invoice Submit. You can also disallow users creating Lab Tests manually using Role Permissions. That should satisfy your use case.
