### ISSUE TITLE
Leave allocation issue

### ISSUE THREAD

**Issue by reema30** [frappe/erpnext#16381]
I have created new leave policy for jan - dec and assigned it to all employees. But allocated leave not showing on employees dashboard. Screenshots attached.

![screen shot 2019-01-11 at 12 19 51 pm](https://user-images.githubusercontent.com/45488333/51018355-4dc02e80-159d-11e9-9e3d-3a60bf266eb1.png)

![screen shot 2019-01-11 at 12 19 22 pm](https://user-images.githubusercontent.com/45488333/51018398-70eade00-159d-11e9-9519-aa8fb43f76fc.png)

![photo_2019-01-11_12-36-10](https://user-images.githubusercontent.com/45488333/51018443-9e378c00-159d-11e9-9edb-5c12671de2f0.jpg)

**Comment by jigneshpshah** [comment]
Have you made leave period active ?
