### ISSUE TITLE
Mass attendance template is not marking every employees leave note

### ISSUE THREAD

**Issue by reema30** [frappe/erpnext#16382]
There are 7 approved leave applications in the month of dec. But the mass attendance template is taking only 1 leave application instead of 7. Screenshots attached.

![screen shot 2019-01-03 at 2 10 56 pm](https://user-images.githubusercontent.com/45488333/51018817-f753ef80-159e-11e9-9eb8-0962abf3e571.png)

![screen shot 2019-01-03 at 2 17 46 pm](https://user-images.githubusercontent.com/45488333/51018836-03d84800-159f-11e9-8d95-0f04c086341c.png)

**Comment by ruchamahabal** [comment]
fixed: https://github.com/frappe/erpnext/pull/19102

**Comment by ruchamahabal** [comment]
fixed: https://github.com/frappe/erpnext/pull/19102
