### ISSUE TITLE
v11 Profitability report based on cost center not working

### ISSUE THREAD

**Issue by ovresko** [frappe/erpnext#16395]
I've created multiple cost center accounts, allow cost center in entry of balance sheet account is checked under Account Settings.
PDV profile cost center: in Profitability report all values are null,
Sales Invoice: same thing only Principal take affect
GL entries has correct cost center set.
what am i doing wrong ?

**Comment by harshit-30** [comment]
Please create another issue if it is replicable after v13.10.
