### ISSUE TITLE
v11 Sales Invoice and Delivery Note not getting mapped

### ISSUE THREAD

**Issue by Audacityy** [frappe/erpnext#16414]
when you follow this flow "Sales Order > Sales Invoice > Delivery Note -- Workflow 1", 
the Report Builder tool in **Delivery Note** fetches the 'Against Sales Invoice' column, **BUT** 

as soon as you change the flow i.e "Sales Order > Delivery Note > Sales Invoice -- Workflow 2", 
it fails to fetch that column. 
![image](https://user-images.githubusercontent.com/46772424/51298420-77200500-1a4a-11e9-9524-77c0cc7a6122.png)

**Comment by kennethsequeira** [comment]
@Audacityy 

It's the same in v10:

![image](https://user-images.githubusercontent.com/33246109/52617819-0e01a500-2ec3-11e9-9bac-dc58f9bb178b.png)

The **Against Sales Invoice** field is meant to capture the sales invoice ID only when the Delivery Note is created from a Sales Invoice. Data is fetched based on a past entry at the time of submission. 

When you're following workflow 2, you'll see that the relevant information is added in the Sales Invoice report:

![image](https://user-images.githubusercontent.com/33246109/52618080-d1827900-2ec3-11e9-83f6-f29dbd825b70.png)

Read the following for more clarity: https://erpnext.org/docs/user/manual/en/using-erpnext/articles/check-link-between-documents
