### ISSUE TITLE
Bug: Customer quick entry doesn't filter parent customer groups

### ISSUE THREAD

**Issue by chdecultot** [frappe/erpnext#16420]
Hi,

When registering a new customer through the quick entry dialog, the customer group field is not filtered and displays all customer groups, even the parents.

Parents tree groups should be not be selected in transactions and when using the standard registration form for users they are not proposed in the dropdown. 
It is so because a query is correctly defined at form setup to filter all parents: `frm.set_query('customer_group', {'is_group': 
0});`

This query should be also picked up in the quick entry form to be consistent.

**Comment by nabinhait** [comment]
Quick entry form does not support JS script, hence it does not work. Closing the issue

**Comment by kingraphaii** [comment]
> Quick entry form does not support JS script, hence it does not work. Closing the issue

@nabinhait I acknowledge your response, just stumbled upon this as well, has there been plans to implement this
