### ISSUE TITLE
A common error which ERPnext is facing "'record series' already Exists error "

### ISSUE THREAD

**Issue by Kaimera1** [frappe/erpnext#16426]
![already exists error](https://user-images.githubusercontent.com/46051637/51384348-816afd80-1b35-11e9-9600-c95d0b46e199.JPG)

please help with this issue, this is also existing for sales order and purchase orders. 

**Situation:**

Stock reconciliation is blocked totally by this error this error states that the next series number already exists in the system when actually it has not been created in the system.

**Assumption:**
I have noticed at time a single instance of click on some module access points at times takes in as a double click. My assumption is that there are two instances being created at the same time that does not save, it literally sounds crazy, but its just a feeling i have. Please check this issue cause i have read issues of the same sort dating back to 2016 and 2017.

**Work arounds done before:**

when we faced this issue for sales orders we could bypass this by using a different account to make the amendment required for the sales order with out getting the record already exists error. Another thing i notices that the sales order that faces this error cannot have a delivery note and sales invoice made for it and only the last account who managed to process the sales order to delivery note could make the invoice if given access to.

**Stuck faced:**

None of the above work around can be applied to stock reconciliation. please help

**Comment by umairsy** [comment]
You can correct the naming series current value from Naming Series tool

https://erpnext.org/docs/user/manual/en/setting-up/articles/naming-series-current-value

**Comment by Kaimera1** [comment]
thanks
