### ISSUE TITLE
[Critical] receivable summary report, cannot see total invoiced amount and outstanding amount

### ISSUE THREAD

**Issue by azharul-islam** [frappe/erpnext#16437]
<img width="547" alt="screen shot 2019-01-21 at 11 23 20 am" src="https://user-images.githubusercontent.com/38819502/51461437-1f95d800-1d6f-11e9-8e7c-2504e41fb861.png">

ERPNext: v11.0.3-beta.34 () (staging)
Frappe Framework: v11.0.3-beta.49 () (staging)

Recently added new fiscal year. Not sure if that caused any bug.

**Comment by kennethsequeira** [comment]
@azharul-islam issue seems to be resolved on later updates 

![image](https://user-images.githubusercontent.com/33246109/53965133-99630480-4116-11e9-83a3-627271ba8125.png)

Checked on:

**ERPNext: v11.1.13 (master)
Frappe Framework: v11.1.13 (master)**

Can you check and confirm the same?

**Comment by azharul-islam** [comment]
Resolved now. Thank you

Sent from my iPhone

On Mar 7, 2019, at 5:52 PM, Kenneth Sequeira <notifications@github.com<mailto:notifications@github.com>> wrote:


@azharul-islam<https://github.com/azharul-islam> issue seems to be resolved on later updates

[image]<https://user-images.githubusercontent.com/33246109/53965133-99630480-4116-11e9-83a3-627271ba8125.png>

Checked on:

ERPNext: v11.1.13 (master)
Frappe Framework: v11.1.13 (master)

Can you check and confirm the same?
