### ISSUE TITLE
Value cannot be changed for Variant Based On

### ISSUE THREAD

**Issue by swapnil3701** [frappe/erpnext#16441]
while creating new item variant iam facing this issue

Value cannot be changed for Variant Based On
![screenshot from 2019-01-21 19-30-16](https://user-images.githubusercontent.com/45786856/51479064-3b22d200-1db3-11e9-8405-8e561b85b74f.png)

**Comment by kennethsequeira** [comment]
@swapnil3701 was this issue fixed on any subsequent update?

**Comment by kennethsequeira** [comment]
insufficient steps to replicate. No response yet. Can re-open or open a new issue with more info.

**Comment by jvfiel** [comment]
I believe there are a couple facing this issue
https://discuss.erpnext.com/t/error-saving-items/47488/2
https://discuss.erpnext.com/t/value-cannot-be-changed-for-variant-based-on/47383

**Comment by jvfiel** [comment]
Please reopen

**Comment by kennethsequeira** [comment]
@jvfiel 

This issue was a very old one hence closed.

A PR is opened for fixing the issue faced currently: https://github.com/frappe/erpnext/pull/17136

**Comment by jvfiel** [comment]
I think

```
def validate_attributes(self):
		if not self.variant_based_on:
			self.variant_based_on = 'Item Attribute'
```

should be

```
def validate_attributes(self):
		if not self.variant_based_on and self.has_variants:
			self.variant_based_on = 'Item Attribute'
```

**Comment by Annacl1** [comment]
I have the same error when editing item and we haven't variants at all in item list. 
I noticed
- the same item I changed 8 days ago (28.03.2019) and all was Ok, we did not make any changes during this time for this item (and other old items). 
- we have items added 3 days ago, I can change them all without error. But all older items have error - Value cannot be changed for Variant Based On.

**Comment by soodghit** [comment]
we have the same issue

**Comment by alpkaan83** [comment]
i have the same error
