### ISSUE TITLE
[Proposal] Improvements to supplier scorecard

### ISSUE THREAD

**Issue by sagarvora** [frappe/erpnext#16444]
Proposed changes:
- [x] Remove `variables` child table from scorecard DT: not needed
- [x] Remove unnecessary fields from Variable child table for Period doctype.
- [x] Hide max_score and formula from `criteria` child table in Scorecard DT
- [x] Set `weight` in Criteria DocType to not mandatory, change position to end.
- [x] Remove `beta` status from all DocTypes.
- [x] Add button to fetch all existing criterias
- [x] Copy criteria formula to Period DocType.
- [x] Make Period doctype submittable, auto submit.

No changes to be made to Standing child table: will be auto-populated by default.

**Comment by Olawale1** [comment]
I would love to see the scorecard feature extended to work with Employees too... this would be very beneficial to a much wider range of ERPNext users

Cheers!
