### ISSUE TITLE
Field docstatus is not selectable - Error message

### ISSUE THREAD

**Issue by kalaisaranA** [frappe/erpnext#16450]
Error message - "Field docstatus is not selectable"  is thrown  when  doctype viewed from Notification.After refreshing the doctype ..only it displays the document.Screenshot is attached for reference.
![screenshot_2019-01-22 journal entry](https://user-images.githubusercontent.com/41562031/51527452-7fb57880-1e5a-11e9-9fe6-cff7191f162f.png)

**Comment by kennethsequeira** [comment]
@kalaisaranA is this still an issue or was solved later on updates?

**Comment by kennethsequeira** [comment]
Closing as no further updates provided on the version, traceback, and updates in general.
