### ISSUE TITLE
Unable to Restore Deleted document in Journal Entry

### ISSUE THREAD

**Issue by kalaisaranA** [frappe/erpnext#16486]
Hi Everyone,
     When i try to Restore the deleted document  in Journal Entry it throws following error 
![screenshot_2019-01-24 acc-jv-2019-00017 - 749a8b3377 1](https://user-images.githubusercontent.com/41562031/51675608-2ab06880-1ffa-11e9-9c23-99321dfed93f.png)

and  even cancelled document are  not restored as draft. How to fix this bug??...

**Comment by harshit-30** [comment]
Please create another issue if it is replicable after v13.10.
Thanks for raising the issue and being a valuable member of the ERPNext Community. :)
