### ISSUE TITLE
Make Sales Order Option unavailable for Quotation valid till today

### ISSUE THREAD

**Issue by jigneshpshah** [frappe/erpnext#16502]
Environment
ERPNext: v11.0.3-beta.37 () (staging)
Frappe Framework: v11.0.3-beta.51 () (staging)

Steps To Reproduce : 
1) Submit Quotation with valid till = today
2) Click on Make (blue) button , unable to see **_Sales Order_** Option

Expected Behavior 
Should be able to see Sales Order Option under Make button

Actual Behavior
Make > Sales Order Option not available for such quotation.

![image](https://user-images.githubusercontent.com/4900815/51782725-6c085b80-2153-11e9-8452-ce51607ec7c9.png)

![image](https://user-images.githubusercontent.com/4900815/51782722-5eeb6c80-2153-11e9-8665-5939f596dbbf.png)

**Comment by deepeshgarg007** [comment]
@jigneshpshah this issue is fixed in v11
![image](https://user-images.githubusercontent.com/42651287/56785708-faa07d80-6813-11e9-8107-f43091fb8c70.png)
