### ISSUE TITLE
Algerain accounting plan on ERPNEXT

### ISSUE THREAD

**Issue by Faouzz** [frappe/erpnext#16510]
Hello,

attached our algerain accounting plan, includes accounts reference, could some one help me to add it ERPNEXT ?
Thanks in Advance

[Plan Comptable Algeria.xlsx](https://github.com/frappe/erpnext/files/2802153/Plan.Comptable.Algeria.xlsx)

**Comment by FinForce** [comment]
please post your requirement on https://erpnext.org/erpnext-jobs

Someone in your territory might be able to help you with accounting module adoption. On the GitHub issue list developer centric matter like Bugs, Feature request, product enhancement to be posted.
