### ISSUE TITLE
v11 Sales Invoice  Issue Customer Group

### ISSUE THREAD

**Issue by dineshpanchal93** [frappe/erpnext#16519]
![image](https://user-images.githubusercontent.com/21578167/51961153-d38b1780-2481-11e9-9cd7-7dcee52ef16c.png)

**Comment by noetico** [comment]
While this is being fixed; get ahead by passing the following directly to mysql database.
`UPDATE tabCustomer SET customer_group = "All Customer Group"`
This fills all current customers with the value; so you can get operations going; afterward you can update particular customers or wait for the update.

**Comment by dineshpanchal93** [comment]
Yes Thank you it has been resolved
