### ISSUE TITLE
[Feat. Req. ver4.0] Connect a Website-user to a specific customer

### ISSUE THREAD

**Issue by rbuhre** [frappe/erpnext#1651]
Is it possible to tie a Website user to a specific customer?

The reason for asking is that it would be interesting to get new Support Tickets to the correct account based on which cutomer the user belongs to. This would maybe open up the possibility for multiple users from the same customer to share tickets.

I know that in the Customer Issue section it is possible to connect the Issue to a serial number, would it be possible to add that for Customer Ticket as well. Or maybe expose the Customer Issue to the Website.

Regards
Rickard

**Comment by rmehta** [comment]
Fixed via Contact
