### ISSUE TITLE
dead slow

### ISSUE THREAD

**Issue by renjithvr1980** [frappe/erpnext#16512]
dead slow.
save process not happening.

**Comment by FinForce** [comment]
Please post your concern on Discuss.erpnext.com with more details like the screenshot, your data/transaction volume, which version of ERPNext & Frappe you are using and the server where the capacity of hosting plan.

If you provide these details larger group in the community including users and non-developers would also be able to help you.

I'm closing this issue, for now, do reopen it if you find some specific bug in the system
