### ISSUE TITLE
Auto Repeat for all DocTypes

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#16525]
Hi ,

The Auto Repeat feature is currently limited to only a few documents but it was actually intended as a general purpose tool. It is particularly important for documents like Projects, Tasks, and ToDos

https://discuss.erpnext.com/t/use-auto-repeat-for-projects-tasks-and-todos/44908

Please complete the process of restructuring so that it can be used for other DocTypes. There could also be an 'Allow in Auto Repeat' checkbox available via Customize Form so that a System Manager can determine which documents are available for Auto Repeat

Thanks

**Comment by kennethsequeira** [comment]
Available since v12:

https://docs.erpnext.com/docs/user/manual/en/automation/auto-repeat
