### ISSUE TITLE
Possible barcode scanning BUG in POS version 11 and no data on scanning

### ISSUE THREAD

**Issue by noetico** [frappe/erpnext#16549]
So recently I made some upgrades and also shared how; but I have seen a bug with one installation; and funny enough its the one from latest v10 to 11. POS appears to have returned to some issues we dealt with as follows:

1. Scanning barcode shows result in item grid instead of loading to cart; barcode match should enter the item to customer's cart immediately as usual not show up as a search result requiring the cashier to select; slowing the sales process down.
2. Some/many items come up with no data even though the barcodes are working correctly and confirmed correct in item list. This appears to be random

Update was made on the 30th 01, 2019 if that will be helpful

Will also post on github for overview.

**Comment by nextchamp-saqib** [comment]
This has been reworked with v13 POS, hence closing the issue.
