### ISSUE TITLE
In cloud, help is not working.

### ISSUE THREAD

**Issue by Herbert6917** [frappe/erpnext#16543]
![image](https://user-images.githubusercontent.com/16352068/52061576-99cb1700-253c-11e9-8b55-a4374aff21db.png). Clicking on help next to user name at top of screen there is no place to enter a search term and clicking on displayed terms just goes to "Not Found" page. 
![image](https://user-images.githubusercontent.com/16352068/52061764-1231d800-253d-11e9-8b41-0085f0d2de84.png)

**Comment by kennethsequeira** [comment]
@Herbert6917 the issue seems to be fixed. Can you confirm?

**Comment by Herbert6917** [comment]
Thank you it is working now.

**Comment by Herbert6917** [comment]
Sorry, I notice the search box still does not exist.

**Comment by kennethsequeira** [comment]
Please check: https://erpnext.org/docs/user/manual/en

Or open a new issue with a specific description regarding docs search. Closing the thread for now.
