### ISSUE TITLE
v11 report builder's buttons doesnt show up

### ISSUE THREAD

**Issue by Muvuk** [frappe/erpnext#16552]
helo,

as you can see on the gif. Report builder buttons doesnt show as it needed. 

![190201-1523](https://user-images.githubusercontent.com/5338127/52128568-95365980-2635-11e9-9e16-58a2636893b2.gif)

I see on your demo, it shoud change list's button (menu, refresh, new) to report buttons, like menu, refresh, pick columns,set sort, show total)

https://www.youtube.com/watch?v=TxJGUNarcQs

**Comment by asmit3141** [comment]
It is very broken in V11. Is there a way to revert to the V10 report builder?

**Comment by kennethsequeira** [comment]
@asmit3141 Not broken. 

As a redesign, these options were moved inside the Menu button in V11:

![image](https://user-images.githubusercontent.com/33246109/56864730-756bc300-69e3-11e9-8971-17c78329602b.png)
