### ISSUE TITLE
Make Button Quotation Error

### ISSUE THREAD

**Issue by VDIPL** [frappe/erpnext#16557]
Hai All.,Hope all are good.Thanks in advance.I am doing a fresh instance and successfully done without any installation errors. I started my instance and i am making lead from lead i am making opportunity and from opportunity i am making Quotation through make button, but i am not getting loaded to the quotation page.When i check error through console form.min.js?ver=1549091741.0:1 Uncaught TypeError: Cannot read property 'get_selected' of undefined this was the error.
Same from Quotation to Sales order it is not Working,
![screenshot from 2019-02-02 13-19-13](https://user-images.githubusercontent.com/43987785/52161589-44823780-26ed-11e9-9341-614a920f2898.png)
Kindly find the attachment for further reference.

**Comment by kennethsequeira** [comment]
@VDIPL 

The process is working fine in v10, 11, and 12 right now hence closing the issue.

When creating a new issue next time, do mention the Versions of ERPNext and Frappe.
