### ISSUE TITLE
[Feat. Req. Ver4.0] Project: Time Log and Reporting

### ISSUE THREAD

**Issue by rbuhre** [frappe/erpnext#1655]
Hi,

It would be very interesting to see an overview how much time has been reported on projects/tasks closer tied to a Customer.

Example:
- I'm reporting time via the Time Log on a Project/Task
- When the Time Log is saved (not necessarily Submitted), Project Managers and Sales Team should be able to see time reported on a project/task from a Project or Customer perspective
- This would help our sales and project managers to actually plan and invoice customers

The structure that I see in my head is something like the following:
 - Project
    - All project details (as it looks today)
        + Time Log Section
            + Each Time Log entry for project (Draft/Submitted)
            + Possibility to select Submitted Time Log Entries and create a Time Log Batch
        + Compare Estimated time with time reported in Time Logs
        + Overview how much time has been invoiced

Under the Customer view it would be interesting to have something similar to the "Total Billing This Year"/"Unpaid" but for Time Logs "Reported Hours"/"Billed Hours".

Time Log Batch:
The process of making Time Log Batches should be easier.
I'm making 50 Time Log Entries per month in 3-4 different projects.
Each project needs its Batch, but there is no easy (if any) way to select all Time Logs for a Project and create a Batch.

When a Batch is converted to an Invoice, there should be an option to see each Time Log entry with its Notes.

Hope the above is understandable... :)

I have to add that ERPNext is great and it has great potential to grow with more features without getting complicated for the user.

**Comment by rmehta** [comment]
Added Time Logs to projects. For reporting please raise separate Issues
