### ISSUE TITLE
[Bug] [v11] List View taking too much time to refresh

### ISSUE THREAD

**Issue by vorasmit** [frappe/erpnext#16565]
- Current List view is taking too much processing to refresh.
- It hangs when 500 items loaded.

ERPNext: v11.1.0 (master)
Frappe Framework: v11.1.0 (master)
Chrome Browser

**Comment by joshreeder** [comment]
It hangs at 100 as well, it also crashes Chrome when new items come in in mass. I have Error Log List view open. I am getting 87 errors every 4 minutes from events trying to sync with gCalendar and it will crash Chrome and I can't even close the tab.

**Comment by joshreeder** [comment]
@netchampfaris specifically if you load 100 or 500 records and then the records list updates in any way. New records, delete one or more records, it will crash Chrome.
