### ISSUE TITLE
[Bug][v11] Attach Document in email is not auto selected

### ISSUE THREAD

**Issue by vorasmit** [frappe/erpnext#16566]
- While sending emails, attach document print is not selected by default.
- Working fine with chrome browser. faced problem with Firefox.

ERPNext: v11.1.0 (master)
Frappe Framework: v11.1.0 (master)
Firefox

**Comment by joolsr** [comment]
We've seen this too on V11. The browser difference s will explain why some users experience the problem and others didn't

**Comment by ChipwizBen** [comment]
Also a problem on V12. Invoice emails are regularly sent out accidentally without the invoice attached due to this bug.
