### ISSUE TITLE
xmlsign does not work

### ISSUE THREAD

**Issue by abdufarag** [frappe/erpnext#16574]
I was trying to create a custom app for Electronic signature but It did not work, I was using xmlsig and tested as stand alone python script and worked perfect but from inside Erpnext it showing always error "No Method Found".

**Comment by barredterra** [comment]
We'd need more details and your code to help you. Please create a post on discuss.frappe.io .

**Comment by kennethsequeira** [comment]
Kindly post customization related queries on [ERPNext](https://discuss.erpnext.com) or [Frappe](https://discuss.frappe.io) Forums.
