### ISSUE TITLE
ERPNext Stuck on updating

### ISSUE THREAD

**Issue by shanmukhasai6** [frappe/erpnext#16579]

**Comment by shanmukhasai6** [comment]
ERPNext stuck

browser screen showing - updating

![screenshot from 2019-02-05 17-52-51](https://user-images.githubusercontent.com/30374799/52273178-10b64480-296f-11e9-9409-7ceefdaf3c95.png)

**Comment by PawanMeh** [comment]
Refer this [thread](https://discuss.erpnext.com/t/stuck-in-update-erpnext/45261/2) on discuss
