### ISSUE TITLE
[bug][v11] data table sorting refreshes column filters

### ISSUE THREAD

**Issue by vorasmit** [frappe/erpnext#16578]
Replicate issue in the following manner

- Open any report
- Add Column Filters
- Sort any column
- Column filters get removed and need to be re-entered.

This was not the problem with old tables

**Comment by madid87** [comment]
I can confirm this! Sorting is not usable any more. 

Another related issue with reports is that all columns cannot be shown, see the snap below.   

![image](https://user-images.githubusercontent.com/33371535/54417044-5b12aa00-4701-11e9-97fd-c7cfdce4a852.png)

No matter what I change the horizontal scroll will always hide the column at the edge. My screen resolution is 1920x1200.

**Comment by harshit-30** [comment]
Is it still replicable @vorasmit ?

**Comment by vorasmit** [comment]
This issue seems to be resolved. Thanks.
