### ISSUE TITLE
[BUG] Work Order 'loses' Stock Entry and dashboard status after submitting Job Card

### ISSUE THREAD

**Issue by tristanvigar** [frappe/erpnext#16580]
Details of bug can be found at https://discuss.erpnext.com/t/bug-work-order-loses-stock-entry-during-production-of-bom-item-erpnext-v11-1-3-master/45232

**Comment by tristanvigar** [comment]
Unable to replicated in another environment. These seems to be specific to one seemingly broken environment.

**Comment by tristanvigar** [comment]
I've seen this behaviour in another environment that was isolated from the first case. I'm not sure what is triggering this behaviour though.

**Comment by ankush** [comment]
fixed long time back https://github.com/frappe/erpnext/pull/16575
