### ISSUE TITLE
Calling Terms and Conditions

### ISSUE THREAD

**Issue by isma3elyahya** [frappe/erpnext#16592]
Greetings to everyone

You’ve created the Terms and Conditions, but when you choose them do not meet the requirements.
Look at the picture, table is empty

any solution?
![capture](https://user-images.githubusercontent.com/45967278/52352483-4e7da080-2a35-11e9-94b0-60db1b009fe5.JPG)

**Comment by kennethsequeira** [comment]
Closing, since already replied on the [discuss](https://discuss.erpnext.com/t/calling-terms-and-conditions/45300/3) thread.
