### ISSUE TITLE
Profit and Loss Statement

### ISSUE THREAD

**Issue by mikezareno** [frappe/erpnext#16594]
In Accounts-> Profit and Loss Statement, 
Getting Message:
**End Year cannot be before Start Year**

ERPNext: v11.1.4 (master)

Frappe Framework: v11.1.4 (master)

**Comment by barredterra** [comment]
That's on purpose. You can create a PL statement for the time between 2018 and 2019 but not backwards from 2019 to 2018.

Maybe we should set both the default start and end year to be the current year. Then a user could edit the start year without getting an error message.

**Comment by mikezareno** [comment]
That was the behavior in v 10, but it seems the defaults were reset to
something illogical in v 11. Ideally, it would default to the start and end
dates of the active fiscal year

**Comment by fadizenaty** [comment]
Hi friends, 
i have upgraded to version 12 from 11 but unfortunately getting the same message "End Year cannot be before Start Year", any suggested solution?

**Comment by asifmohtesham** [comment]
@fadizenaty 
I am getting the same error on my system.

**Comment by barredterra** [comment]
Financial reports are shown for the current [Fiscal Year](https://erpnext.com/docs/user/manual/en/accounts/fiscal-year). If you want this year's reports by default, you can create a new **Fiscal Year** and set it as default.
