### ISSUE TITLE
POS:  Scan or Type  Barcode results in "No Data"

### ISSUE THREAD

**Issue by who-has-seen-the-wind** [frappe/erpnext#16602]
Attempting to type a barcode,  results in "No data" in items display.
A barcode scan should also fail, since a scan of 1111 from standard barcode readers would be 1111 followed by CR (carriage return). 
(Testers without a barcode scanner can test by pasting a  barcode into the search box.)

![screenshot_item1](https://user-images.githubusercontent.com/26367673/52438130-6f91d000-2acd-11e9-9c7b-81814af43363.png)
![screenshot_posbarcode](https://user-images.githubusercontent.com/26367673/52438131-6f91d000-2acd-11e9-90ba-f14f698824b9.png)

--------------------
Platform:
Ubuntu 18.04.1 LTS, dual boot, localhost
"Easy Install" script, using Production
ERPnext v11.1.4
Bench v11.1.4
Firefox browsing to localhost
Logged into ERPnext as an administrator

**Comment by aldrenalin** [comment]
This issue turns out to be related to 
[Sales Invoice - Fetch Item via Barcode doesn't work](https://github.com/frappe/erpnext/issues/16032)

Where it was described that 
> Use the child table for barcode as a single item can have multiple forms of barcode. The barcode field is obsolete now and will be removed with a patch to copy its data from the field to child table.

So, it appears that the obsolete barcode field was not removed in the V11.1.4 Release.

**Comment by ankush** [comment]
Not reproducible anymore.
