### ISSUE TITLE
Unable To Delete Chat History [V11]

### ISSUE THREAD

**Issue by flexy2ky** [frappe/erpnext#16606]
Following the release of Chat as a standalone messaging app in V11, i discovered that there is no way to delete chat history with any user. I believe this feature should be added as it is standard for all messaging apps to be able to delete any chat history with any user.

Is it possible to add this feature? Thanks

**Comment by vrms** [comment]
Why would you want to be able to delete the history, if I may ask? Is it in order to remove what has been said, or in order to gain an empty chat without the previous messages?

I believe it can be beneficial to keep the history and being able to search it (maybe that would be a missing feature).

**Comment by flexy2ky** [comment]
There are so many reasons why one should be able to delete chat history, not least for privacy reasons. Being able to archive a message thread is one thing and being able to delete a message thread is another. 

Why I specifically need to be able to delete a message thread with another user is immaterial as the context of the request is not about me but about the general idea of being able to delete a chat thread should a user choose to. This is a basic feature of every chat software out there that I know of, be it open source, free, paid or enterprise. So all I ask is for a basic feature common with such a program to be added.

**Comment by grynn-in** [comment]
I think for good reasons it should not be deleted. For example if some uses threat or bad language then it is a good record. It is a business management software not a chat software. Great feature.

**Comment by Olawale1** [comment]
Maybe the system admin could have the option to enable/disable the delete feature so that each user can choose what works best in their own organization?

Cheers

**Comment by ankush** [comment]
chat not part of frappe or erpnext anymore: https://github.com/frappe/chat/issues
