### ISSUE TITLE
When creating new Ware house - Default Account head is not displayed

### ISSUE THREAD

**Issue by joshiparthin** [frappe/erpnext#16618]
When we create a new account, a default account head is not displayed... 

In transactions we have Stock in Hand in the GL, but cannot see in the warehouse screen. 

![image](https://user-images.githubusercontent.com/6594877/52518263-f5e51800-2c6d-11e9-8e4d-50fb29ab2080.png)

**Comment by Zlash65** [comment]
So, you can either specify a specific account to a warehouse or have a default one. If the `Account` field is empty in Warehouse, it simply means its picking up the default inventory account that is set in the Company master.

<img width="958" alt="screenshot 2019-02-12 at 11 47 37 am" src="https://user-images.githubusercontent.com/11695402/52615755-4356c480-2ebc-11e9-9a74-0ffa5b5846c4.png">

**Comment by joshiparthin** [comment]
Yes in the ledger it shows correct. But user should be aware this is the default warehouse. I think its better if default warehouse set in company master if displayed automatically.

**Comment by rmehta** [comment]
Fixed via: https://github.com/frappe/erpnext/pull/17126
