### ISSUE TITLE
First installation user Administrator

### ISSUE THREAD

**Issue by reliteweb** [frappe/erpnext#16620]
For some time I have not been able to access the configuration and special settings reserved for this user. My system administrator to give me access to the setup had to create a new administrative role that would continue to access only the basic settings with the exclusion of development.
I must therefore repair the administrative user of the first installation.
Advance that we have already reset the permissions but without success.

**Comment by reliteweb** [comment]
I want to specify that with Administrator access and that the swcth in Frappe bench / sites / site1.local is set site_config.json "developer_mode": 1,.
The strangest thing is that I do not even access the "setup" icon

**Comment by barredterra** [comment]
Please ask questions on [discuss](https://discuss.erpnext.com). GitHub is for bug reports and development.

**Comment by reliteweb** [comment]
Ok
