### ISSUE TITLE
Attendance can not be marked for future dates

### ISSUE THREAD

**Issue by philliy** [frappe/erpnext#16631]
when we try to mark attendance it says "Attendance can not be marked for future dates" time was correct according to time zone too but .... can anyone help pls

**Comment by vrms** [comment]
this is phrased as a question suitable for the Forum. If you believe this is a bug and **not** due to incorrect usage, can you kindly rephrase the issue in a more issue like style, like ...

### expected behavior
....

### actual behavior


.....

**Comment by kennethsequeira** [comment]
Closing as no further updates provided on the issue.
