### ISSUE TITLE
Unable to see variant item on shopping portal

### ISSUE THREAD

**Issue by jigneshpshah** [frappe/erpnext#16637]
Environment
ERPNext: v11.1.4 (master)
Frappe Framework: v11.1.4 (master)

Steps to Reproduce
1) Create a Template Item with variants & sufficient stock.
2) See on website . Unable to see/select  variants of the template item
![image](https://user-images.githubusercontent.com/4900815/52559473-5ebdc300-2e1b-11e9-805e-686225fbe71c.png)

3) Will receive the below error in browser console

![image](https://user-images.githubusercontent.com/4900815/52559127-6c267d80-2e1a-11e9-9a77-df5da421b259.png)

drill down error, further leads to the below code.
```
function get_item_code() {
	var variant_info = window.variant_info;
	if(variant_info) {
		var attributes = get_selected_attributes();
		var no_of_attributes = Object.keys(attributes).length;

		for(var i in variant_info) {
			var variant = variant_info[i];

			if (variant.attributes.length < no_of_attributes) {
				// the case when variant has less attributes than template
				continue;
			}

			var match = true;
			for(var j in variant.attributes) {
				if(attributes[variant.attributes[j].attribute]
					!= variant.attributes[j].attribute_value
				) {
					match = false;
					break;
				}
			}
			if(match) {
				return variant.name;
			}
		}
		throw "Unable to match variant";
	} else {
		return window.item_code;
	}
}

```

### Shopping Cart Settings
![image](https://user-images.githubusercontent.com/4900815/52559618-c116c380-2e1b-11e9-8897-f6e1ba953c94.png)

**Comment by gmplab** [comment]
#17916 
Also have similar issue in V12

**Comment by rasos** [comment]
Still an issue with v12, see also duplicate report https://github.com/frappe/erpnext/issues/17916

**Comment by pirminkager** [comment]
I am also trying to show variants in the web shop. Is this still an issue or am i missing some settings?

**Comment by pirminkager** [comment]
i found that there is another setting necessary to show the configure button to select between variants.
![image](https://user-images.githubusercontent.com/22398209/100891280-66030480-34b9-11eb-9700-3b9ee8e63f4d.png)
