### ISSUE TITLE
Calculation of departure days-Leave Application

### ISSUE THREAD

**Issue by isma3elyahya** [frappe/erpnext#16646]
Hello Everyone

Does the ERPNext system collect the number of departure hours and deductions from the annual leave days?
For example, the official hours are 8 hours and there is an employee requesting 3 departures for a total of 8 hours. Is it counted as a day off?

If yes! How using the feature?

**Comment by kennethsequeira** [comment]
@isma3elyahya please post this on the community forum: https://discuss.erpnext.com

We use Github issues to track bugs and feature requests.
