### ISSUE TITLE
Supplier Invoice No is Not Updated  in GSTR-2 Report

### ISSUE THREAD

**Issue by nxdevelopment** [frappe/erpnext#16649]
Purchase Invoice number  is updating in the field- Invoice Number of GSTR-2 report instead of Supplier Invoice Number.Kindly refer the screenshot -GSTR2 Report.
![screenshot_2019-02-12 gstr-2 1](https://user-images.githubusercontent.com/44566832/52631980-42d32380-2ee6-11e9-9d44-796c160a9162.png)

**Comment by vrms** [comment]
with **_"Supplier Invoice Number"_** you mean **_"GSTIN of Supplier"_** as per the left column in the screenshot?

**Comment by dj12djdjs** [comment]
If this is still relevant please re-open at
https://github.com/resilient-tech/india-compliance
