### ISSUE TITLE
Default Payable Account at Supplier: 'Company' None. v11.1.4

### ISSUE THREAD

**Issue by franciscobuendiao** [frappe/erpnext#16641]
Hello,

In new 'Default Payable Account' section at Supplier, doesn't recognize any company.
ERPNext: v11.1.4 (master)
Frappe Framework: v11.1.4 (master)

Trace error:
> Traceback (most recent call last):
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
>     doc.save()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 260, in save
>     return self._save(*args, **kwargs)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 296, in _save
>     self.run_before_save_methods()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 876, in run_before_save_methods
>     self.run_method("validate")
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 772, in run_method
>     out = Document.hook(fn)(self, *args, **kwargs)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1048, in composer
>     return composed(self, method, *args, **kwargs)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1031, in runner
>     add_to_return_value(self, fn(self, *args, **kwargs))
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 766, in <lambda>
>     fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
>   File "/home/frappe/frappe-bench/apps/erpnext/erpnext/buying/doctype/supplier/supplier.py", line 51, in validate
>     validate_party_accounts(self)
>   File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/party.py", line 292, in validate_party_accounts
>     frappe.db.get_default("Company"),  "default_currency")
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 693, in get_cached_value
>     doc = get_cached_doc(doctype, name)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 678, in get_cached_doc
>     doc = get_doc(*args, **kwargs)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 721, in get_doc
>     doc = frappe.model.document.get_doc(*args, **kwargs)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 69, in get_doc
>     return controller(*args, **kwargs)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 104, in __init__
>     self.load_from_db()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 141, in load_from_db
>     frappe.throw(_("{0} {1} not found").format(_(self.doctype), self.name), frappe.DoesNotExistError)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 351, in throw
>     msgprint(msg, raise_exception=exc, title=title, indicator='red')
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 337, in msgprint
>     _raise_exception()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 310, in _raise_exception
>     raise raise_exception(msg)
> DoesNotExistError: Company None not found

![error_company](https://user-images.githubusercontent.com/25084259/52583674-c95c0800-2df5-11e9-9269-434a8ea787ac.jpg)

**Comment by harshit-30** [comment]
Please create another issue if it is replicable after v13.10.
Thanks for raising the issue and being a valuable member of the ERPNext Community. :)
