### ISSUE TITLE
What happened to In app Help?

### ISSUE THREAD

**Issue by Herbert6917** [frappe/erpnext#16657]
At,    [https://frappe.io/blog/erpnext-features/in-app-help-in-erpnext](https://frappe.io/blog/erpnext-features/in-app-help-in-erpnext) there is an explanation of How to use help.  It has lost the search box now.  What happened to it?  It was useful at times.
![image](https://user-images.githubusercontent.com/16352068/52645493-e1439280-2eae-11e9-8f0a-1b729ed7284b.png)

![image](https://user-images.githubusercontent.com/16352068/52645614-19e36c00-2eaf-11e9-8659-d00000c53eb3.png)

**Comment by vrms** [comment]
+1 missing the in app help, but ...

1. the link you have provided just shows the issues of the frappe repository. Can you please specify the document you wanted to refer to?
2. the way you phrased this issue makes it more suitable as a Topic on the forum. So it may be helpful to rephrase this issue in terms of `expexted behaviour`, actual behavior` 
(there is one [related Topic yet](https://discuss.erpnext.com/t/search-in-documentation/45422/6) btw)

**Comment by Herbert6917** [comment]
This is the image I was trying to include, from the article written by Faris Ansari.  It shows the search bar that has currently been removed and the article explaining its useful functions that are suddenly not available anymore.  Is this intentional or not? Also I have been updated to version 11.1.5 master since yesterday. I will repost this in the topic you suggested.  Thank you.


![image](https://user-images.githubusercontent.com/16352068/52733134-f2b09b80-2f8f-11e9-8cf5-0d3f3be3edd7.png) I will re post this on the related topic.

**Comment by kennethsequeira** [comment]
In-app help was removed. 

Clicking on Documentation under help will take one to the documentation website: https://docs.erpnext.com/docs
