### ISSUE TITLE
Loyalty program js error in portal invoice detail

### ISSUE THREAD

**Issue by jigneshpshah** [frappe/erpnext#16665]
Environment
ERPNext: v11.1.4 (master)
Frappe Framework: v11.1.4 (master)

Steps to Reproduce
1) Go to Web Portal> Invoices
2) Click on any invoice for detail , below error comes in console
Cannot set property 'onblur' of null
![image](https://user-images.githubusercontent.com/4900815/52697628-cd279000-2f97-11e9-922e-caafed12cd07.png)

which further leads to below
![image](https://user-images.githubusercontent.com/4900815/52697664-e6c8d780-2f97-11e9-8f74-3f8e3fc27bb5.png)

**Comment by harshit-30** [comment]
Please create another issue if it is replicable after v13.10.
