### ISSUE TITLE
Payment entry from Purchase Invoice does NOT catch Project from PO line

### ISSUE THREAD

**Issue by vrms** [frappe/erpnext#16662]
I want to check profitability on Project base and encounter one problem with payment entries created from a Purchase Invoice.

The item in my PO is linked to a certain project

### expected behavior 
when I use "Make Payment" from that PO, the Project which is connected to the item lines in the PO should be fetched in the payment entry automatically

### actual behavior
the connected Project is **not** fetched automatically in the PE and has to be selected manually

**Comment by harshit-30** [comment]
Thanks for reporting this @vrms

**Comment by ruthra-kumar** [comment]
PR https://github.com/frappe/erpnext/pull/29182
