### ISSUE TITLE
[Version 11] DocType Employee Loan not found in Permission Manager

### ISSUE THREAD

**Issue by bedosk** [frappe/erpnext#16678]
When I open permission manager - desk#permission-manager
I get the error DocType Employee Loan not found

see more at https://discuss.erpnext.com/t/version-11-doctype-employee-loan-not-found/45080

**Comment by janecekmato** [comment]
Hi, i got same issue for different doctypes. It seems like custom perm was not changed during update. So old DocTypes names are still there. I created python function for that. Maybe it help you:

`def change_custom_perms():
    
    old_doctype = "Supplier Type"
    new_doctype = "Supplier Group"

    all = frappe.get_all("Custom DocPerm", filters={"parent": old_doctype}, fields=["*"])
    for a in all:
        frappe.db.set_value("Custom DocPerm", a.name, 'parent', new_doctype)`

**Comment by grey2254** [comment]
> Hi, i got same issue for different doctypes. It seems like custom perm was not changed during update. So old DocTypes names are still there. I created python function for that. Maybe it help you:
> 
> ```
> def change_custom_perms():
> 
>     old_doctype = "Supplier Type"
>     new_doctype = "Supplier Group"
> 
>     all = frappe.get_all("Custom DocPerm", filters={"parent": old_doctype}, fields=["*"])
>     for a in all:
>         frappe.db.set_value("Custom DocPerm", a.name, 'parent', new_doctype)
> ```

Where do i place the above code

**Comment by janecekmato** [comment]
anywhere, ideally in your custom app, and then you should run bench execute  dotted.path.to.your.function

**Comment by rmehta** [comment]
"Employee Loan" has now been renamed to "Loan"
