### ISSUE TITLE
In Sales Order, effects of change in item table are not reflected in real time in payment terms table

### ISSUE THREAD

**Issue by joshiparthin** [frappe/erpnext#16683]
In sales order screen, when we change qty or rate in items table, tax and grand total are re-calculated but does not recalculate the payment amount in the payment terms table. However correct values appear when we save the document. But not reflecting the values before save may be confusing. 

v11.1.5 (master)

![so_payment_terms_update_amount](https://user-images.githubusercontent.com/6594877/52862515-7074d280-315b-11e9-9dd4-8869a6111b10.gif)

**Comment by sharmanakul** [comment]
when you change the quantity/rate then on saving the sale order, the values in payment terms get updated.
