### ISSUE TITLE
Products page redirect to contact 

### ISSUE THREAD

**Issue by MostafaFekry** [frappe/erpnext#16702]
Hey,

When i add items and show them on website and going to products website page unfortunately the page redirects to contact us web page instead of showing the item details.

Note this problem occurred in v. 11.1.5 and 11.1.6 (master)

Any clarifications please?

**Comment by MostafaFekry** [comment]
> Hey,
> 
> When i add items and show them on website and going to products website page unfortunately the page redirects to contact us web page instead of showing the item details.
> 
> Note this problem occurred in v. 11.1.5 and 11.1.6 (master)
> 
> Any clarifications please?

**Comment by jamesutter** [comment]
I am having this issue too, can you please reopen, or explain the fix?

**Comment by jottunn** [comment]
confirming this issue on fresh install
ERPNext: v11.1.14 (master)
Frappe Framework: v11.1.14 (master)

**Comment by ovresko** [comment]
Found a workaround
Go to Shopping Cart Settings
enable + Set modatory fields (series, company ...)
Save  and reload website
