### ISSUE TITLE
General Ledger (consolidated) view

### ISSUE THREAD

**Issue by heatherpotter** [frappe/erpnext#16715]
I would like to see the ability to add "Group by Account (Consolidated)" to this drop down. This would allow you to have a report with just the debits and credits totaled for the time period you are looking at in GL. 
![screenshot 2019-02-18 16 30 30](https://user-images.githubusercontent.com/8241286/52980092-1e6fbf00-339e-11e9-94dc-0638e80d4408.png)

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.
