### ISSUE TITLE
Why can‘t delete Sales Partner ？

### ISSUE THREAD

**Issue by CypressAutumn** [frappe/erpnext#16718]
In Sales Partner List and Sales Partner Interface Menu, I can’t find the path to delete a sales partner.

**Comment by CypressAutumn** [comment]
Oh, It's not a issue. It is a Role Permission Setting. This option is not default.

**Comment by vrms** [comment]
this issue does not comply with the [Issue Guidelines](https://github.com/frappe/erpnext/wiki/Issue-Guidelines) and it comes as a support request. 

And the question was kind of answered on the [topic on the forum](https://discuss.erpnext.com/t/why-can-t-delete-sales-partner/45745) (which ideally you'd have put a link to here). Closing this now.
