### ISSUE TITLE
Payment Entry Currency Bug

### ISSUE THREAD

**Issue by bghayad** [frappe/erpnext#16713]
Hello;
If the cash account currency (for the mode of payment) in USD and the company currency in different currency (like LBP), it does not do the conversion as shown in the below images (Received Amount USD is same as Paid Amount LBP and the Received amount in LBP differs than Paid Amount in LBP) and all of these values are not arranged (not related) to the values in the table of the references. 

Also if I entered new value for Paid Amount (LBP) then it does not update the Received Amount in (USD) based on the currency conversion.

![payment_currency_bug](https://user-images.githubusercontent.com/27868094/52959599-3eec4900-339f-11e9-95a1-a85ba602eef1.jpg)

![payment_currency_bug_2](https://user-images.githubusercontent.com/27868094/52959608-44e22a00-339f-11e9-8993-cb58b6a43efc.jpg)

Regards
Bilal

**Comment by harounasow** [comment]
Hello,
I am new to erpnext and frappe and i would like to contribute through resolving this ifrst issue. Could you please tell me which version of erpnext are you using ?

**Comment by bghayad** [comment]
The problem is existed with erpnext version 10 and version 11.
Anyway, I tested it recently on erpnext version 11.1.6 and the problem is existed also.

Regards
Bilal

**Comment by harounasow** [comment]
ok @bghayad, 
I am able to reproduce the issue, plus i noticed that if the paiment needs USD/LBP and we already have LBP/USD it still complain about USD/LBP. I guess it is better to have a separate issue for this one too.
So i am on it. Thanks

**Comment by bghayad** [comment]
Very good @harounasow 
Can you help also in this issue please?
https://github.com/frappe/erpnext/issues/16712

Because it is critical and related to the Chart of Account.

Regards
Bilal

**Comment by bghayad** [comment]
Hello @harounasow 
Hope you are doing fine.
Any news?
Regards
Bilal

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.
