### ISSUE TITLE
Sorting the accounts in Chart of Accounts in ERPNext version 11

### ISSUE THREAD

**Issue by bghayad** [frappe/erpnext#16712]
This problem appears if the chart of account will be created from **json** file and not from .py file. And if it is required to be reproduced, **then it can be tested by selecting france chart of account which use the file fr_plan_comptable_general.json.**

The accounts are not sorted based on the account number or based on the alphanumeric of the account number and account name.

Below is the image of how the accounts are appearing in version 11 and this problem is not existed in version 10.

![chartofaccount_accounts_sorting](https://user-images.githubusercontent.com/27868094/52958216-4827e680-339c-11e9-9d91-f8f3af5a67e7.jpg)

**Comment by vrms** [comment]
I confirm the behavior as per this issue

![image](https://user-images.githubusercontent.com/7608112/53298362-09c37900-382d-11e9-8d74-b768a915f07b.png)

at least the chikdren seem to be sorted numerically.

![image](https://user-images.githubusercontent.com/7608112/53298374-54dd8c00-382d-11e9-83a2-7475359dcdde.png)

Can it be ERPNext sorts as per root account type rather then the numbers of the account groups?

**Comment by vrms** [comment]
I also see the same behavior with my own companies CoA (which also originates from a .json file):

- Root Groups are not sorted numerically
- Children are sorted numerically

my french is too bad to say whether the Root account Group sorting follows the same principle in both cases

**Comment by Nofal-Mami** [comment]
I confirm sorting is not working if account type is a group, but if account is a leaf sorting is fine. I have tested this issue and reported in the forum.

**Comment by bghayad** [comment]
@crescent28 
Can you help by classifying this issue to be bug so to be taken into consideration to work on it to be resolved because Chart of Account is very important and critical.
Regards
Bilal

**Comment by bghayad** [comment]
Hello @crescent28  @vrms @Nofal-Mami 
How can we speed up to fix this?
Or at least if someone can advise from where it is possible to modify the code and resolve this bug?
Regards
Bilal

**Comment by Nofal-Mami** [comment]
here discusson link
https://discuss.erpnext.com/t/sorting-by-account-number-not-working/45493/5

**Comment by bghayad** [comment]
Thank you @Nofal-Mami 
@creador30 Please note that until now I am not able to user version 11 because of this problem which consider very important because it is related to chart of account which is important. 

Regards
Bilal

**Comment by bghayad** [comment]
Hello;
Any update on this?
The problem is preventing us from using version 11.
Regards
Bilal

**Comment by bghayad** [comment]
Hello @jaichavan 
Can you help please?
Regards
Bilal

**Comment by bghayad** [comment]
Hello;
I have created fix for this problem at this pull request #17563
