### ISSUE TITLE
Balance Sheet,, Cash Flow, and Profit and Loss Statement Can't run

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#16727]
Just displays the below

![image](https://user-images.githubusercontent.com/1822868/53034349-070b0180-3484-11e9-86e5-6cffdb8ad75c.png)

ERPNext: v11.1.7 (master)

Frappe Framework: v11.1.7 (master)

**Comment by pdussail** [comment]
Im having the same problem, does the same in general ledger view....please help
ERPNext: v11.1.7 (master)
Frappe Framework: v11.1.7 (master)

**Comment by jigneshpshah** [comment]
I am having same issue 
https://discuss.erpnext.com/t/release-notes-version-11-1-7/45807/2

**Comment by jigneshpshah** [comment]
Issue Resolved after upgrade to 
ERPNext: v11.1.9 (master)

Frappe Framework: v11.1.8 (master)
