### ISSUE TITLE
Issue status "hold" in Support Module

### ISSUE THREAD

**Issue by EmmanuelHernande** [frappe/erpnext#16729]
Hi, first time posting for frappe/erpNext.

Whenever we raise an issue and then change the status to "Hold" lets say when we the agent is waiting for a customer response or a manager response etc etc, the frame time during which the issue is in "Hold" status still counts in the Support analytics to close the issue.

Example:

An issue is raised on 19 Feb 2019 at 10:00:00 .  On the same day the status is changed to Hold, from 11:00:00 to 12:00:00. At 12:00:00 the status is changed to "Open" again. At 13:00:00 the status is changed to "Closed".

We would expect time from opening to closed in supports analytics to be 2 Hours, since the status was "Hold" for 1 hour. But its showing 3 hours.

ERPNext: v10.1.76 (master)
Frappe Framework: v10.1.68 (master)

Thanks in advance for your kind help.

Emmanuel.

**Comment by harshit-30** [comment]
This has been implemented, read more about it [here](https://docs.erpnext.com/docs/v13/user/manual/en/support/service-level-agreement#34-pause-sla-on-statuses).
