### ISSUE TITLE
EMAIL broken - LATEST UPDATE

### ISSUE THREAD

**Issue by heatherpotter** [frappe/erpnext#16742]
In the latest update on ERPNext Cloud, you can no longer go to Menu>Email in any doctype. It's broken and never pops up on multiple browsers and different users.

Also, PDF formatting is broken as well.

**Comment by joolsr** [comment]
Yes I had the same. In the Frappe repo someone has published how it can be fixed if you are happy to change core code. Shouldn't be needed though
I went back to an earlier snapshot instead but still lost time ..

How come the new cypress UI tests didn't pick up something as simple as that?

**Comment by heatherpotter** [comment]
I'm on ERPNext Cloud so this isn't an option for me, unfortunately.

**Comment by joolsr** [comment]
Best contact support directly. Bad bug really.

**Comment by katombe** [comment]
i had same problem too. is any solution?

**Comment by vecoreda** [comment]
An Issue related to this is open in Frappe Issues. As I mentioned there, but in this case on ERNext v11.1.9 (master), this problem arises. The result is that no mail is being sent from ERPNext, even those automatically produced.

**Comment by joolsr** [comment]
Should be fixed with this commit https://github.com/frappe/frappe/pull/6971
