### ISSUE TITLE
Multi Company

### ISSUE THREAD

**Issue by brentglover** [frappe/erpnext#16755]
Hi

Have setup a second company on Hosted ERPNext.  Company exists and I can see it in the COA but it says "insufficient permission for account".  I cannot see the second company showing under accounts/company.

I have checked my rights and all looks ok (though I can find nothing on rights relative to a second company) there any pointers on something simple I am missing?

Thanks

Brent

**Comment by vrms** [comment]
seems you are seeking user support/help on how to use ERPNext. 
Please kindly post a Topic on the [forum](https://discuss.erpnext.com/) instead.
