### ISSUE TITLE
[BUG] Custom Field Signature on Mobile

### ISSUE THREAD

**Issue by Daradaal** [frappe/erpnext#16757]
The signature field does not work on the mobile version (android 7 and android 5) of ERPNEXT.
During the signature (drawing), the drawing disappears when the signature is released.
On the other hand via a web page the signature works perfectly.

**Comment by Olawale1** [comment]
Hi,

We are facing the exact same issue and this makes it difficult to use the functionality in the field as the mobile app is more suited to this purpose

Kindly help fix this

Thanks

**Comment by Olawale1** [comment]
Any update on this?

**Comment by tecnofoodmx** [comment]
Same problem here. any update?

**Comment by deepeshgarg007** [comment]
@Daradaal Mobile app is deprecated now, closing this issue
