### ISSUE TITLE
[Bug] Asset depreciation issues

### ISSUE THREAD

**Issue by chdecultot** [frappe/erpnext#16756]
Hi,

During the implementation of finance books, several issues have been introduced:

1. If you select a manual depreciation schedule, the table is not editable anymore.
That's because, the system looks at the field `depreciation_method` which is an hidden section `section_break_33`.
![image](https://user-images.githubusercontent.com/4903591/53230304-abf52c80-3686-11e9-897b-e14dcc088487.png)

It should instead look at the `depreciation_method` within the finance book section.
With the current state, we cannot edit the schedule if it doesn't fit the expected values...

2. The prorated depreciation doesn't work properly anymore:
![image](https://user-images.githubusercontent.com/4903591/53230591-51100500-3687-11e9-9878-014932285a35.png)

It should end the schedule at 28/06/2021 and not create an entry for 31/12/2019.

**Comment by federicocalvo** [comment]
Hi @chdecultot ! Is this error still present?

Regards!

**Comment by thida-bcn** [comment]
Fixed Asset Monthly Depreciation is not correct
Schedule 1 year, monthly
![image](https://user-images.githubusercontent.com/62122640/76577128-ae752f00-64f2-11ea-9532-9897a1ef289e.png)
![image](https://user-images.githubusercontent.com/62122640/76577139-ba60f100-64f2-11ea-8d3c-b9d8f202720f.png)
for 2 year, monthly
![image](https://user-images.githubusercontent.com/62122640/76577157-c77de000-64f2-11ea-97be-150fa613315d.png)
![image](https://user-images.githubusercontent.com/62122640/76577164-ccdb2a80-64f2-11ea-8f39-b0c29aef6290.png)

**Comment by karamakcsc** [comment]
Hi @chdecultot ! Is this error still present?

Regards!
