### ISSUE TITLE
Unable to open Cash Flow Statement

### ISSUE THREAD

**Issue by barredterra** [frappe/erpnext#16769]
### How to Reproduce

From  `desk#Tree/Account` (Chart of Accounts), click on `Financial Statements` > `Cash Flow Statement`.

### Error

Leads to an empty page with the following error in the browser console:

```
Uncaught (in promise) TypeError: Cannot read property 'ref_doctype' of null
    at query_report.js:145
```

https://github.com/frappe/frappe/blob/bfc25ad1e5abcd6bdf14127213d9fb3a5b3ad85d/frappe/public/js/frappe/views/reports/query_report.js#L145

### Version
ERPNext: v11.1.4 (master)
Frappe Framework: v11.1.4 (master)

**Comment by kennethsequeira** [comment]
replicated in 
**ERPNext:** v11.1.13 (master)
**Frappe Framework:** v11.1.13 (master)

![image](https://user-images.githubusercontent.com/33246109/54218588-e4fd2000-4513-11e9-9e4e-9589d28eb2f2.png)

**Comment by hrwX** [comment]
#### Works in V12
![Screenshot 2019-08-07 at 11 54 05 AM](https://user-images.githubusercontent.com/7310479/62599550-21d61300-b90a-11e9-821a-036b392d6e6d.png)

**Comment by barredterra** [comment]
@hrwX wasn't v11 supposed to get maintained as well?
