### ISSUE TITLE
[v11] Bank Account - 'Party Type' should only allow to choose Party Types, not any Doctype

### ISSUE THREAD

**Issue by vrms** [frappe/erpnext#16767]
When creating a Bank Account there is an option to connect it with a Party (Customer, Supplier, Employee). In the dropdown field `Party Type` **only Parties should be available as options to choose from**. Instead any Doctype is being listed in the dropdown menu.

### Installed Apps
ERPNext: v11.1.6 (master)
Frappe Framework: v11.1.6 (master)

### Expected Behavior
when creating a new bank account you should be able to choose the `Party Type` **only** from existing Party Types (Customer, Employee, Supplier by default)

### Actual Behavior
you can choose **any** DocType in the `Party Type` selection dropdown

---

![erpnext bank account party type bug 2019-02-24 11-26](https://user-images.githubusercontent.com/7608112/53298057-32953f80-3828-11e9-9d8d-00faaa99cf50.gif)

**Comment by franciscobuendiao** [comment]
Remains at:
ERPNext: v11.1.13 (master)
Frappe Framework: v11.1.13 (master)

**Comment by harounasow** [comment]
Hello, 
I will investigate this issue.
