### ISSUE TITLE
[v11.1.10] It is not possible to download sales invoice template with data

### ISSUE THREAD

**Issue by ophl55** [frappe/erpnext#16776]
**ERPNext: v11.1.10 (master)
Frappe Framework: v11.1.10 (master)**

It is not possible to download sales invoice template with data using the data import tool.

![unbenannt](https://user-images.githubusercontent.com/5788712/53341495-f4714c00-390b-11e9-8af4-7d10ecd8eec2.PNG)

**Comment by FinForce** [comment]
@ophl55 When you select the action option as 'Update record', it will allow you to download 'with data'

![image](https://user-images.githubusercontent.com/31281816/53482965-70070080-3aa6-11e9-9a71-6b337d728d1e.png)

**Comment by ophl55** [comment]
Ah okay, thank you for your response. I missed that.
