### ISSUE TITLE
[v11.1.10] It is not possible to download Address template with Data

### ISSUE THREAD

**Issue by ophl55** [frappe/erpnext#16775]
**ERPNext: v11.1.10 (master)
Frappe Framework: v11.1.10 (master)**

It is not possible to download Address template with Data.

![unbenannt](https://user-images.githubusercontent.com/5788712/53336645-347e0200-38ff-11e9-89f2-8dd56b9d9260.PNG)

**Comment by FinForce** [comment]
Duplicate issue #16776
