### ISSUE TITLE
[v11.1.10] Expense claim approver link not working

### ISSUE THREAD

**Issue by adfluidics** [frappe/erpnext#16778]
Hi!

Since the upgrade, when wanting to save an expense claim for approval, it is no longer possible to choose an expense approver. I have checked and several of our users are still approvers, so that's not the reason.

![image](https://user-images.githubusercontent.com/47985186/53352118-82f0c800-3922-11e9-8ad8-9758dfd7e896.png)

Hope you can solve this pretty soon!
Thanks =)

**Comment by jigneshpshah** [comment]
Expense Approver is to be set at each Department Level, have you set it there ?
![image](https://user-images.githubusercontent.com/4900815/53488178-8ebfc400-3ab3-11e9-8845-deaa79cfa618.png)

and check your HR Settings for Expense Approver
![image](https://user-images.githubusercontent.com/4900815/53488214-a8f9a200-3ab3-11e9-94ec-6f92ca1835ea.png)

**Comment by adfluidics** [comment]
Great, this works!
Sorry, I didn't know that it had to be approved per department as it worked without that beforehand. But it makes sense!
Thanks for your help
