### ISSUE TITLE
warning package-lock.json found.

### ISSUE THREAD

**Issue by lbazan** [frappe/erpnext#16791]
INFO:bench.utils:yarn install
yarn install v1.13.0
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.

**Comment by joolsr** [comment]
I'm afraid this happens. I've often seen this. It's not a fault with ERPNext. You need to simply 

rm package-lock.json

And then run bench update again and thus will be cleared.

**Comment by lbazan** [comment]
thanks!
