### ISSUE TITLE
Reports allignment issue in Arabic Interface

### ISSUE THREAD

**Issue by FlexsoftsTech** [frappe/erpnext#16796]
Dear Team, all reports do not work probably on Arabic interface, there issue in columns name alignment with columns content and total amount showing Zero even though there is amounts in the columns, in English interface it is working fine, this issue happening in all reports
kindly this is very urgent, we receiving daily questions about this issue
![reports issue](https://user-images.githubusercontent.com/33314211/53488034-3500cf00-3a9e-11e9-9313-63a8eae29b92.png)

**Comment by FlexsoftsTech** [comment]
Dear @umairsy this is a very critical issue for Arabic Users we should give it high priority 
it is here for 2 days and till now there is no reaction
we getting too many calls daily

**Comment by FlexsoftsTech** [comment]
Version:
ERPNext: v11.1.13 (master)
Frappe Framework: v11.1.13 (master)

**Comment by FlexsoftsTech** [comment]
@netchampfaris Could you please address this, it been here for a long time and its effects on Arabic Clients
will highly appreciate your help
Report Name is General Ledger, anyhow I faced it on all reports

**Comment by jigneshpshah** [comment]
It is RTL CSS Issue, applicable for all RTL Languagues e.g. Arabic, Hebrew.

Does Datatable supports RTL , @netchampfaris ?

**Comment by deepeshgarg007** [comment]
This issue has been fixed via PR https://github.com/frappe/datatable/pull/64

**Comment by j209** [comment]
Hi
This issue has not been fixed.
frappe:12.x.x
erpnext:12.x.x.
Datatable:1.13.5
![image](https://user-images.githubusercontent.com/18129232/62039364-cff80380-b20c-11e9-826b-65d6999f764c.png)
