### ISSUE TITLE
Email Notification Message Wont Save

### ISSUE THREAD

**Issue by Mitchy25** [frappe/erpnext#16802]
When adding a new Notification via email, the 'message' field does not save the user input.

The 'message' field remains with the text 'Add your message here'. Upon saving, this field's value is overwritten with 'Add your message here'.

**Comment by Mitchy25** [comment]
UPDATE: The message **does** update in the .json file, but does not display on the Notification form.

**Comment by dawoodjee** [comment]
I also keep getting these emails with **Add your message here**

Several of them and cant tell what is causing them

**Comment by Mitchy25** [comment]
Fixed
