### ISSUE TITLE
How to add HR module to ERPNEXT under development Server

### ISSUE THREAD

**Issue by madhu6759** [frappe/erpnext#16808]
I have installed a development ERPNEXT application in my ubuntu 18.04.In my server how to add HR module in ERPNEXT.

**Comment by jigneshpshah** [comment]
it comes out of the box , no need to install separately.

**Comment by niveditalocal** [comment]
can u pls share the link to download the HR module in ERPNext?

**Comment by jigneshpshah** [comment]
https://github.com/frappe/hrms

**Comment by niveditalocal** [comment]
Dear Team,

 

Greetings for the day.

 

We are currently using your trial version of Erpnext and wanted to subscribe for Rs. 1800/ month plan for unlimited users.

 

Kindly advise us how to proceed with it.

 

Waiting to hear from you.

 

Nivedita Phalke

Sales Co-ordinator

 




VINAYAK INGREDIENTS (INDIA) PVT. LTD.

+91 22 40560406

 ***@***.*** 

 www.vinayakcorporation.com <http://www.vinayakcorporation.com/> 

116, Cama Industrial Estate, Sunmill Compound, 

    Lower Parel (W), Mumbai - 400013, INDIA

**Comment by jigneshpshah** [comment]
https://frappehr.com/pricing
