### ISSUE TITLE
'Select Default Supplier' in Quoted Item Comparison v11.1.10 Not Working

### ISSUE THREAD

**Issue by franciscobuendiao** [frappe/erpnext#16801]
'Select Default Supplier' tool in 'Quoted Item Comparison' is not working.

ERPNext: v11.1.10 (master)
Frappe Framework: v11.1.10 (master)

![quoted_item_comparison_01](https://user-images.githubusercontent.com/25084259/53520992-9e7fde00-3a9c-11e9-82f0-a902422755b1.jpg)
![quoted_item_comparison_02](https://user-images.githubusercontent.com/25084259/53520994-9e7fde00-3a9c-11e9-8f28-24abed889804.jpg)

**Comment by jaichavan** [comment]
The purpose of this tool is to set Default Supplier in the "Quoted Item Comparison" report, unlike the Item master itself. Closing this issue.

**Comment by franciscobuendiao** [comment]
Until v10, this tool set the "Default Supplier" at item Master. I'm using ERPNext since v7.

What's the purpose to only set it at "Quoted Item Comparison" report?
