### ISSUE TITLE
[Bug V 11.1.13] Item Price DocType "Make a new Item Price" button appeared in List view is not working

### ISSUE THREAD

**Issue by asanodaria** [frappe/erpnext#16825]
"Make a new Item Price" button is not working appearing in List View.

![make a new item price button](https://user-images.githubusercontent.com/36321437/53685434-a2338f00-3d40-11e9-9fde-7e2f481b8538.gif)

**Comment by kennethsequeira** [comment]
@asanodaria 

Please switch to **List View** you are in the report view

![new-item-price](https://user-images.githubusercontent.com/33246109/54142098-f92a1a00-444c-11e9-895c-b27a8d5918ff.gif)

However, it is a bug as the button is showing and still not triggering any action. It rather should be hidden.

**Comment by scmmishra** [comment]
The issue has been fixed.
