### ISSUE TITLE
[Bug] Pricing rule - Item discount, other than zero not accepted.

### ISSUE THREAD

**Issue by drthilina** [frappe/erpnext#16832]
I’ve put up a pricing rule to only change the margin, The “Pricing or Discount” option is selectable (blank, discount, Price) and I kept it blank (meaning off).

![image](https://user-images.githubusercontent.com/29944021/53722056-a966b400-3e8a-11e9-8c9b-7bd5ad7c0c93.png)

What I expect to achieve is when a Sales Doc is created, for every line item, a certain margin will get applied automatically, while I get to give a discount as I please.

But no matter what I tired, the Discount resorts to “0” when saving the document. I believe this is a bug.

**Comment by harshit-30** [comment]
Please create another issue if it is replicable in v13.10.
