### ISSUE TITLE
Unused Leaves Text Box un-editable-v11.1.11

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#16833]
![image](https://user-images.githubusercontent.com/1822868/53723810-9697b380-3e79-11e9-963a-adf816ddc618.png)

**Comment by muchai** [comment]
In addition, the Add unused leaves from previous allocations and Unused leaves should be editable On Submit.

**Comment by kennethsequeira** [comment]
It was the same in v10 as well. No changes to the field

![image](https://user-images.githubusercontent.com/33246109/53964186-d62dfc00-4114-11e9-8b15-114f85e8b037.png)

What would be the login/reason to make it editable?

Same for making the options editable on submit

**Comment by muchai** [comment]
I wish to withdraw this, better it be uneditabe.
