### ISSUE TITLE
[v11] kanban not populating

### ISSUE THREAD

**Issue by adfluidics** [frappe/erpnext#16831]
Hi! 

I used the Kanban Board in V10 to see my quotations (for example) per status, which is one of the standard suggested parameters. 

In V11, when I choose to create my Kanban Board "Quotation Status" based on "Status", the board appears completely empty.
![image](https://user-images.githubusercontent.com/47985186/53721581-d784cd80-3e63-11e9-8ddf-27b41381534f.png)
![image](https://user-images.githubusercontent.com/47985186/53721590-e1a6cc00-3e63-11e9-8f73-7bd2b18b5572.png)

Thanks for your help!

**Comment by vrms** [comment]
please test the kanban with other doctypes and report about this, so it can be identified whether this is a general kanban problem

**Comment by adfluidics** [comment]
Hi,

I tested the following forms, always depending on the status.

Was already setup and works for:
- Sales Order
- Sales Invoice
- Order Status

New board, that works:
- Purchase Receipt
- Purchase Invoice

So it doesn't seem to be a general Kanban problem. I also went back to my quotation status kanban, but I still have the same problem.

**Comment by vrms** [comment]
I tried to reproduce this, but can't do it.

![Peek 2019-03-09 12-03 kanban](https://user-images.githubusercontent.com/7608112/54070696-7abe5400-4263-11e9-9758-e622b86b7735.gif)

what you see in the second half of the gif though is that I can not switch to the kanban view once I have switched back to list view. I can, however, acces it through >Kanban >show board

**Comment by adfluidics** [comment]
Hi,

Shame you can't reproduce it...

I can access the kanban directly from the quotation menu:
![image](https://user-images.githubusercontent.com/47985186/54185084-7767da00-44a8-11e9-9165-f06048a5a259.png)
If I go to Kanban > Show board, it works too, but I get to my same faulty kanban.

I tried deleting my "Quotation Status" kanban from the Kanban list, then creating a new one, but it is still faulty. I'm not sure what else I can try...

**Comment by madid87** [comment]
I can confirm that there is a problem.

We use the Opportunity Kanban in the same way and since upgrading to V11 only "Open" column in populated, the rest are empty!

**Comment by ci2014** [comment]
Same problem here with Priority status (custom field) in Issue Doctype.

**Comment by rdraju** [comment]
+1
Can confirm the same. "To Do" Kanban Board works. It doesn't update for Custom DocTypes.

**Comment by rdraju** [comment]
Setting "In List View" option of the column used for the board seemed to resolve the issue for me.

**Comment by rdraju** [comment]
Some additional digging showed that the board works fine in my case. Just that there is a limit of 20 docs in the initial get and if all those happen to be from a single status, it looks as if only that column is populated. A negative filter on dominating column shows data in other columns. Since Kanban relies on ListView it is not straight forward to get certain count of all columns. A better approach is needed to populate all columns with minimum count.

**Comment by ankush** [comment]
This seems to work fine now. Tested on quotes as well as others with >20 documents of similar category.
