### ISSUE TITLE
[v11] Data Import "Bank Account" does not work

### ISSUE THREAD

**Issue by vrms** [frappe/erpnext#16850]
following up on this [Topic from the Forum](https://github.com/frappe/erpnext/issues/16850#issue-417655081)

## Installed Apps
ERPNext: v11.1.13 (master)
Frappe Framework: v11.1.13 (master)

## Expected behavior
you should be able to import entries for the "Bank Account" Doctype with the "Data Import Tool" from .csv files

## actual behavior

when u create a "New Data Import" it is impossible to select the "Bank Account" in the Doctype Selector. 
This happens even if you have checked the "import" box in the "Roles Permission Manager" for the "Accounts Manager" Role in the "Bank Account" Doctype (which by default is unchecked) **and** your current user has the "Accounts Manager" Role

![erpnext bank account import bug 2019-03-06 08-03](https://user-images.githubusercontent.com/7608112/53862381-7be34d00-3fe7-11e9-9299-39fb61e3475e.gif)

Furthermore I believe the "Accounts Manager" Role should have the permission to import the "Bank Account" by default

**Comment by vrms** [comment]
seems you have to check the “Allow Import (via Data Import Tool)” option in the Doctype Settings (which by default is unchecked for ‘Bank Account’ DocType) in order to make this work.

So this changes the content of my issue here ... 

**“Allow Import (via Data Import Tool)” in the Doctype Settings (which by default is unchecked for ‘Bank Account’ DocType) should be checked by default**

**Comment by harshit-30** [comment]
Please create another issue if it is replicable in v13.10.
