### ISSUE TITLE
[Feature Request] - Improvements to Stock Ageing Report

### ISSUE THREAD

**Issue by asbasawaraj** [frappe/erpnext#16873]
- [ ] Add a checkbox labelled 'Show Ageing Warehouse-wise' and if checked add warehouse column and display warehouse-wise ageing
- [ ] Add Quantity Column
- [ ] Change label of filter 'To Date' to 'As on Date' (Report should be updated based on the date entered here irrespective of warehouse checkbox is chosen or not)

![stock_balance_improved](https://user-images.githubusercontent.com/11595602/54417774-23b7f380-4729-11e9-8feb-e24fe36896f5.png)

**Comment by adityaduggal** [comment]
Perfect @asbasawaraj Please proceed with the report. I would also reply by email.

**Comment by adityaduggal** [comment]
This issue is closed since this feature is already a part of the master branch
