### ISSUE TITLE
Returned invoices without against voucher no  are not showing in Account Receivable  and Payable report

### ISSUE THREAD

**Issue by navdeepghai1** [frappe/erpnext#16879]
In Account Receivable and Payable report return invoices are not reflecting.

If user create debit/credit invoice without any against voucher no then it's not showing in Account payable and receivable report.

In beta user can create credit/debit note without against voucher no but it should be reflect in acount payable and receivable report also in paid amount column(as a advance amount).

**Comment by federicocalvo** [comment]
Confirm this issue.

**Comment by navdeepghai1** [comment]
@federicocalvo 

# 1
**Return Invoice without any ref(return against):**
![return1](https://user-images.githubusercontent.com/30634335/54255286-e27ce380-4570-11e9-9b7b-45b3459749ec.png)
![return2](https://user-images.githubusercontent.com/30634335/54255312-ff191b80-4570-11e9-9fc0-014a701f2989.png)

# 2
**GL Entries for Invoice:**
![return3](https://user-images.githubusercontent.com/30634335/54255323-093b1a00-4571-11e9-8f0a-dc619e87db7f.png)

# 3
**Account Receivable Report**: you can see in picture attached below  as it's not showing returned invoice.
![return4](https://user-images.githubusercontent.com/30634335/54255349-240d8e80-4571-11e9-81f5-36265457b59b.png)

# 4
**After adding these lines of codes in Account Receivable Report**: It's showing the returned voucher(**# 5**).
![return5](https://user-images.githubusercontent.com/30634335/54255395-5ae3a480-4571-11e9-9a5b-4f422c907a5e.png)

# 5
**Showing returned  invoice**
![return6](https://user-images.githubusercontent.com/30634335/54255424-7c449080-4571-11e9-8751-613048163763.png)

I just fixed the issue by adding these lines of code in Account Receivable report and it's working fine for me.
Reason why we made these changes? 
Because Balance of Debtors in **balance sheet**  is not matching with the oustanding balance of all the invoices.

I just wanted to report it you so that you can modify the report according to the customizations you've made for self returned invoice.

NOTE:
Same issue  for Purchase Invoices also.

**Comment by federicocalvo** [comment]
@navdeepghai1 excelent information. 

I wait for this in the core, but the issue steel tag TO VALIDATE. @crescent28

**Comment by harshit-30** [comment]
Please create another issue if it is replicable after v13.10.
Thanks for raising the issue and being a valuable member of the ERPNext Community. :)
