### ISSUE TITLE
TDS Enhancements

### ISSUE THREAD

**Issue by epochc** [frappe/erpnext#16888]
I propose the following changes to the Tax Deducted at Source (TDS) Feature - this is an India Government requirement for purchase of services.

1.  Tax withholding Category: I propose we move it from the Supplier Master to the Purchase Invoice Item level. Why? It’s possible that the Services Supplier could provide a suite of services to the organization that are under different Tax Withholding Categories

2.  TDS on Purchase Receipt: While some might argue that TDS being a service, the underlying item needs to be set up as a Non-Stock item and when setup as a non-stock item makes it conflicting to do a Purchase Receipt, there are two very strong reasosn why you would still want to enable that:

2.1: Unless you do a Stock Transaction (Purchase Receipt or Purchase Invoice with Update Stock Checked), the PO doesn’t disappear from the Pending PO list
2.2: In most organizations the person responsible for the delivery of services and the person responsible for making the purchase invoice are two different people. So the person certifying that the services have been delivered to the organization can do a Purchase Receipt and the accounts person can do the Purchase Invoice

So we just replicate the TDS features on the Purchase Invoice to the Purchase Receipt

3. TDS on Purchase Order: The TDS rule says that TDS needs to be deducted and remitted to the government the earlier of: 3.1 Invoice, 3.2: Payment

Therefore the TDS process collapses when advance payments need to be made. So, here’s the proposal for #3:

We extend the TDS feature to the Purchase Order. However when a Payment Entry is made for say X amount connected against this PO, TDS is deducted from X and the supplier is given X*(1-R) where R is the TDS deduction rate and R*X is an entry made against the account used in the Tax withholding Category

And as the Purchase Receipt/Invoice is made against this PO, the account balances move to the downstream documents

4. Tax Withholding Category: There are inconsistencies in the way ERPnext is calculating withholding based on the data entered in Tax Withholding Category:

4.1: If the values in the Single Transaction Threshold and Cumulative Transaction Threshold are left blank (or 0), the formula computes and deducts TDS for any amount.
4.2 Formula for deduction: The Formula for deduction is higher of: 4.2.1: SUM(A)>Cumulative Transaction Threshold, TDS for Transaction = SUM(A)R-Sum(TDS) .OR. AR

Where A is the Net Total of the particular Purchase Invoice/Receipt, SUM(A) is the cumulative Invoicing that has happened by the Supplier for the particular Tax Withholding Category and SUM(TDS) is the sum of TDS deducted for the particularsupplier for the Tax Withholding Category, R is the Tax Withhoding Rate for the particular Tax Withholding Category

Is everybody okay about it?

Is there somebody already working on this? If yes, how can we help her/his efforts?

If no, shall I get my developer to do a pull request to fix this?

Thanks

Jay

**Comment by test2a** [comment]
I am confused here. I may be wrong but just saying.

When you purchase an item or a service, you have to deduct tds on payment to THAT supplier. Payments are done usually against tax invoices although it can be done on any expense but still.

If I purchase item from x, I will be getting an invoice from x. For me it should not matter if person y does the delivery on x's behalf.

You mentioned two different people. Why? What am I missing here?

Bring in indirect tax, gst in the picture and please explain it

We currently have 2 different TDS  in india taxation. Income tax tds and gst tds. Both have to be applied in many cases.
I had written back in October on the forums a long list of india taxation improvements but out of that only eway bill is being worked on I think. There is also works on gstr 3B I guess but the point is, erpnext needs a lot of work to be taxation compliant. 

Right now after the recent clarification, say doing a govt contract work, income tax tds and gst tds apply on receipt of payment against tax invoice.
Same for our deducting income tax tds on expenses incurred including services and such.

**Comment by epochc** [comment]
@test2a : Not sure if you referred to the two people in Point #2 of my post. If yes, I was just saying within an organization, many times, the person/group/team responsible for the delivery of the services as per the requirements of the PO could be a different person/group/team that's tasked with the responsibility of making the purchase invoice. With that background, I was justifying my proposal to extend the TDS to the Purchase Receipt document.

Does that clear your confusion somewhat?

Thanks

Jay

**Comment by test2a** [comment]
@epochc
oh silly me. I read that in a different way. My bad. Anyways, I think the tds should be at both levels. Master as well as purchase invoice levels. Why?

I buy services or products that require me to deduct tds on payment but not all suppliers fall in that category. So I allow tds entries on a particular supplier and later during payment, I would deduct tds against whichever section I want. For suppliers that dont cross the threshold, tds option shouldnt be there. Less chances of accidentally deducting tds and then having to reverse entire process. 

Beside,  are we clear that tds should not interfere with our gst input tax credit?

Lastly, I had put up a feature request long time ago about taxes having staggered or slab wise rates like we have for salary. That would be helpful for industries like hotels which pay taxes based in invoice value.
