### ISSUE TITLE
Requesting updated VM build with v11.

### ISSUE THREAD

**Issue by asharamseervi** [frappe/erpnext#16904]
Hello Community,

v11 is finally here & seems many bottom-line issues had fixed. Though, v11 seems promising and codebase almost got revamped with python v3. Can we get an updated VM build with optimized configs?

This is a seamless way to get started for non-ops guys, please focus on this as well.

**Comment by krnkris** [comment]
Would be usefull for testing. Please release it with python 3, because python 2.7 EOL ends on 1/1/2020. Please let us know the update date on
https://erpnext.org/download

**Comment by asharamseervi** [comment]
Any updates or ETA..??

**Comment by kennethsequeira** [comment]
Closing the issue.

Latest VM builds for develop and production (version 12) are available on http://build.erpnext.com/

**Comment by krnkris** [comment]
Only the URL not working.

**Comment by kennethsequeira** [comment]
@krnkris updated the link. It is http://build.erpnext.com
