### ISSUE TITLE
[v11] "Opening Invoice Creation Tool" - only works in default currency

### ISSUE THREAD

**Issue by vrms** [frappe/erpnext#16902]
Installed Apps
ERPNext: v11.1.14 (master)
Frappe Framework: v11.1.14 (master)

---

### Expected Behavior

you can create Opening Invoices for Customers/Suppliers with any billing currency

### Actual Behavior

if you have a Supplier/Customer with a billing currency other then your company default currency the "Opening Invoice Creation Tool" is not able to create such opening invoices.

it makes no difference whether you have the non-default-currency party in the same operation together with default-currency parties, or in a separate operation

### how to reproduce

- create a Customer with a billing currency other then the Company default currency
- create a receivable account in that non-default currency
- open the "Opening Invoice Creation Tool"
- select one or more of the non-default currency Customers
- click "Create Invoices" button
- get the [error message](https://discuss.erpnext.com/uploads/default/optimized/3X/1/8/18ad6c662207f64b7239585bd30e14ca1c308195_1_690x141.png)

----

more details & screenshots can be found in [this Topic on the forum](https://discuss.erpnext.com/t/v11-opening-invoice-creation-tool-only-working-for-default-currency/46634/2)

**Comment by Olawale1** [comment]
hope this gets fixed soon

Kind regards,
