### ISSUE TITLE
[BUG] Fixed Currency Exchange not working

### ISSUE THREAD

**Issue by Mitchy25** [frappe/erpnext#16903]
We are trying to use an AUD to USD fixed currency exchange rate for each Financial Year. When creating a purchase order and purchase invoice, the currency exchange rate is calculated automatically and ignores the set fixed rate.

In Currency Exchange:
![image](https://user-images.githubusercontent.com/42224026/54164447-8a3ad880-44c1-11e9-9029-f6508eabbc97.png)

This equates to roughly 1.3698 AUD per USD.

In Purchase Order:

![image](https://user-images.githubusercontent.com/42224026/54164475-a474b680-44c1-11e9-8bff-fa81026c478b.png)

**Comment by bcornwellmott** [comment]
A couple questions:
- What is the transaction date for the purchase order? It needs to be posted after the exchange rate.
- Do you have 'Allow Stale Currency Rates' checked off (in Account Settings)? If not, it will look up the exchange rate if the posted date and the fixed date are too far apart.

Also, it looks to me like your fixed exchange rate is for AUD to USD, whereas the exchange rate for your purchase order is from USD to AUD. I believe you need to have the correct "direction" defined for a fixed exchange rate lookup to work.

Please confirm.

**Comment by Mitchy25** [comment]
> What is the transaction date for the purchase order? It needs to be posted after the exchange rate.

Date of Purchase Order:

![image](https://user-images.githubusercontent.com/42224026/54165214-a2f8bd80-44c4-11e9-8b83-2d6d11c1e610.png)

Date of Currency Exchange:

![image](https://user-images.githubusercontent.com/42224026/54165236-b146d980-44c4-11e9-8312-9b76d96859a9.png)

> Do you have 'Allow Stale Currency Rates' checked off (in Account Settings)? If not, it will look up the exchange rate if the posted date and the fixed date are too far apart.

'Allow Stale Currency Rates' is on.

>Also, it looks to me like your fixed exchange rate is for AUD to USD, whereas the exchange rate for your purchase order is from USD to AUD. I believe you need to have the correct "direction" defined for a fixed exchange rate lookup to work.

I have added the USD to AUD as well as AUD to USD.

**Comment by Mitchy25** [comment]
> Also, it looks to me like your fixed exchange rate is for AUD to USD, whereas the exchange rate for your purchase order is from USD to AUD. I believe you need to have the correct "direction" defined for a fixed exchange rate lookup to work.

This fixed it 👍
