### ISSUE TITLE
[BUG] Timesheet Hours will be reset to 0 when “Standard Working Hours” in Company is set.

### ISSUE THREAD

**Issue by barredterra** [frappe/erpnext#16900]
### Version
erpnext 11.1.11
frappe 11.1.11

### Issue

When attempting to add `hours` to a `Timesheet Detail` row, the hours revert back to zero, whether entering directly in the hours field, or selecting an end time. 

When entering hours in the hours field, it appropriately adjusts the end time, but then the hours reverts to `0`. This causes the system to not add time, nor can `Timesheet` be submitted. However, if the “Timer” function is employed, the time is properly submitted and the hours stay populated.

The following setting in `Company`, causes `Timesheet Detail`'s `hours` field to revert to “0”:
Section `Default Values`, field `Standard Working Hours`: When set to anything other than `0.000` this field breaks `Timesheet`.

### Reproduce

* Enter any value in `Company`'s `Standard Working Hours` and save. 

When the value is reverted back to zero, you can go back to the timesheet, change something on the timesheet and click “Save” the values will reappear and the timesheet can be properly submitted.

### Workaround

If you have set the `Standard Working Hours` in your `Company`, simply clear that.

Copied from https://discuss.erpnext.com/t/timesheet-hours-only-work-with-timer-feature-v11-when-standard-working-hours-set/46305

**Comment by madmath03** [comment]
Can confirm this is still relevant (and quite a pain) with latest v11:
```
ERPNext: v11.1.73 (HEAD)
Frappe Framework: v11.1.66 (HEAD)
```

Removing Standard Working Hours from Company "_solves_" the issue... but a proper fix for this would be better.

**Comment by daengagiel17** [comment]
For the last version, seems not solve this issue. Can you help me?
