### ISSUE TITLE
Bug in Loan DocType

### ISSUE THREAD

**Issue by Mohd200** [frappe/erpnext#16912]
Dear All,
Good Day,

I am Using the Latest Version 11 of ERPNext, and I have found a bug in the HR Module.
Specifically, in the “Loan” DocType. Please allow me to demonstrate.

1- Once I have Submitted the “Loan Application”, I clicked on “Loan” Button to create the Loan.
![Capture](https://user-images.githubusercontent.com/32062135/54280451-9a79b300-45a8-11e9-9f75-029aa7d5d140.PNG)

2- A new Loan page is opened, so I continue to fill the DocFields. I clicked on “Repay from Salary” to make the Repayment Method go through the Payroll.
![Capture2](https://user-images.githubusercontent.com/32062135/54280473-a796a200-45a8-11e9-8af5-794fbe2313f4.PNG)

3- Most of the Data is automatically Filled by the Data filled in “Loan Application”.
I filled the Repayment Method and The Accounting Information.
![Capture3](https://user-images.githubusercontent.com/32062135/54280634-f9d7c300-45a8-11e9-9359-ef5ec8d43f91.PNG)

4- As shown in the Screenshot, the Table for the repayment is empty while the status of the Loan Record is still “New”.
![Capture4](https://user-images.githubusercontent.com/32062135/54280731-36a3ba00-45a9-11e9-882d-91b1409f48a6.PNG)

5- After Clicking “Save”, the Table appears to be empty and the Total Payment field as well.
![Capture5](https://user-images.githubusercontent.com/32062135/54280768-4cb17a80-45a9-11e9-99a7-5dedb6900f86.PNG)

6- I clicked on “Submit” to find out if the table would be activated once it is Submitted.
But nothing changed, rather the table was hidden.
![Capture6](https://user-images.githubusercontent.com/32062135/54280816-69e64900-45a9-11e9-8817-3fa250819bde.PNG)

I have tried the exact steps on Version 10 of ERPNext, and it works perfectly, even with the “Repay from Salary”.
Please inform me if I have missed a step to activate the Repayment Method through Payroll.
If I have done all the Steps correctly, then Please Help me Fix this Bug.
Thank You.

Here's The Link of the issue on Discuss ERPNext:
[https://discuss.erpnext.com/t/bug-in-loan-doctype/46714](url)

**Comment by aakvatech** [comment]
When I select Disbursed the loan repayment schedule is updated and the amounts are updated.

**Comment by aakvatech** [comment]
Also upon submit the relevant disbursemnt journal can be created by a hook for now. Need help to get it into the core.

**Comment by dufani1** [comment]
What about this bug? still existed?
