### ISSUE TITLE
Problems with new company

### ISSUE THREAD

**Issue by sistemascarroceriasapezcom** [frappe/erpnext#16916]
Hi, I have this problem. Create a new company but I do not have access to this. The company does not see it in the list of companies. What permission do I need to have?

**Comment by Mitchy25** [comment]
Are you logged in as Administrator?

**Comment by sistemascarroceriasapezcom** [comment]
Yes Mitchy25! We pay for a plan of ErpNext. Not is in a local web server. ErpNext provide us the service.

**Comment by crescent28** [comment]
@sistemascarroceriasapezcom if you are paid subscriber of ERPNext, please send this query at support@erpnext.com for faster resolution with your account details.
