### ISSUE TITLE
V11.1.14 Can't create Item Variant based on Manufacturer

### ISSUE THREAD

**Issue by franciscobuendiao** [frappe/erpnext#16924]
ERPNext: v11.1.14 (master)
Frappe Framework: v11.1.14 (master)

```
Traceback (most recent call last):
  File &quot;/home/frappe/frappe-bench/apps/frappe/frappe/app.py&quot;, line 61, in application
    response = frappe.handler.handle()
  File &quot;/home/frappe/frappe-bench/apps/frappe/frappe/handler.py&quot;, line 21, in handle
    data = execute_cmd(cmd)
  File &quot;/home/frappe/frappe-bench/apps/frappe/frappe/handler.py&quot;, line 56, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File &quot;/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py&quot;, line 1026, in call
    return fn(*args, **newargs)
  File &quot;/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/item_variant.py&quot;, line 35, in get_variant
    frappe.throw(_(&quot;Please specify at least one attribute in the Attributes table&quot;))
  File &quot;/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py&quot;, line 353, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator=&apos;red&apos;)
  File &quot;/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py&quot;, line 339, in msgprint
    _raise_exception()
  File &quot;/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py&quot;, line 312, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Please specify at least one attribute in the Attributes table

```

Creating variants upon a template only works with attributes.

**Comment by crescent28** [comment]
@franciscobuendiao This is not an issue since you have to select an attribute for a Variant which distinguishes or enables the Items and its variants to be classified on a parameter. Thus, either you have to add attributes to the Template or do not select Item Has Variants.

**Comment by vrms** [comment]
@crescent28 
> you have to select an attribute for a Variant which distinguishes or enables the Items and its variants to be classified on a parameter. 
I think you are mistaken here. You can create Variants based on Attribute (then what you say applies) or based on Manufacturer. Then there is no Attribute which you can use. So the issue here is an issue.
it seems to be a duplicate of https://github.com/frappe/erpnext/issues/16280 though

**Comment by ovresko** [comment]
> @franciscobuendiao This is not an issue since you have to select an attribute for a Variant which distinguishes or enables the Items and its variants to be classified on a parameter. Thus, either you have to add attributes to the Template or do not select Item Has Variants.

This is not accurate, you don't need item attribute in variante based on manufacturer. i've posted this issue also a year ago twice, even now anyone can test this just create model based on manufacturer then create variante from that model, you can't.
