### ISSUE TITLE
When deleting item "item is linked with BOM New BOM 1" but no BOM created

### ISSUE THREAD

**Issue by rcapuz** [frappe/erpnext#16922]
When deleting item it throws "Cannot delete or cancel because Item _XYZ_ is linked with BOM New BOM 1" but no BOM is created.

I already search for "Links" in the Item and it prompts "Not Linked to any record".

Thanks in advance

**Comment by jtarun4625** [comment]
Any Update same error here .

**Comment by kramteo** [comment]
I face the same issue. Is there any solution?

**Comment by chaicai333** [comment]
same issue here facing

**Comment by sharmanakul** [comment]
Hello @rcapuz , the item cannot be deleted because you may have used it as raw material in a BOM. please check.
