### ISSUE TITLE
[bug] Changing UOM does not work properly

### ISSUE THREAD

**Issue by cupuno** [frappe/erpnext#16938]
After upgraded to version 11.1.11, changing UOM does not work in Sales Order and Purchase Order, only “UOM Conversion Factor” and “Qty as per Stock UOM” will change, other fields such as “Price List Rate”, “Rate” and “Amount” remain unchanged.

It seems that this bug also existing in Invoice, or other doctypes which have UOM fields.

refer to post:
https://discuss.erpnext.com/t/changing-uom-not-work-in-sales-order-and-purchase-order/46851

**Comment by SaiFi0102** [comment]
Solution is in PR https://github.com/frappe/erpnext/pull/16544

**Comment by sharmanakul** [comment]
Checked it on v13.14, seems like this has been resolved.
![chrome-capture (1)](https://user-images.githubusercontent.com/88872881/142971226-6b45566a-51bf-4d5a-a2be-7fd6a042ad10.gif)
