### ISSUE TITLE
Pricelist

### ISSUE THREAD

**Issue by AliKhafaji** [frappe/erpnext#16957]
Hello Everyone!

I am moving from Odoo to ERPNext, and i have a question about customizing ERPNext.

Can we customize the pricelist?

in a way that pricelist will **automatically** be created for that customer when changing the product price on the quotation or invoice, For it to be done only 1 time then the product fix price will be set for that customer for feature sales?

**Comment by kennethsequeira** [comment]
@AliKhafaji best to post functional questions on the forum: https://discuss.erpnext.com
