### ISSUE TITLE
Unable to switch between companies on chart of accounts (V11)

### ISSUE THREAD

**Issue by lasalesi** [frappe/erpnext#16958]
**Expected behavhiour:**
If multiple companies are active in an ERPNext installation, it should be possible to switch between the different chart of accounts using the company drop-down on the top left.

**Actual behaviour:**
Only the first created company is selectable

![grafik](https://user-images.githubusercontent.com/26505250/54636212-38c4b780-4a86-11e9-83e6-9696c88c1963.png)

**Steps to reproduce:**
* create multiple companies
* open chart of accounts and try to select another company (list will not show them)

**Observed in:**
ERPNext: v11.1.14 (master)

**More details:**
* https://discuss.erpnext.com/t/chart-of-accounts-missing-for-multi-company-in-v11/46209/2

**Comment by parsimonyERP** [comment]
+1. We are seeing this in v11.1.14 also.

**Comment by lasalesi** [comment]
Current behaviour: chart of account does not work at all (ERPNext: v11.1.4 (master), 2019-03-27)

Error: TypeError: "erpnext.utils.get_tree_options is not a function"

**Comment by lasalesi** [comment]
TypeError is resolved in ERPNext: v11.1.18 (master) (2019-04-01), but switching between companies is still not possible...

**Comment by lasalesi** [comment]
On a fresh installation, switching between companies works. Seems to be related to the upgrade path, still in upgraded mutli-company implementations it fails...

**Comment by lasalesi** [comment]
There is a workaround:
* open /desk#List/User Permission/List
* add individually the user and access to Company <target company>

Still, there is an issue as this will not allow for role-based access...

**Comment by crescent28** [comment]
This seems to be solved in version 12 now, @lasalesi upgrade your account.
