### ISSUE TITLE
Login Page not showing login fields like username and password

### ISSUE THREAD

**Issue by JunkyardCat** [frappe/erpnext#16962]
Self Hosting Locally with no internet doesn't show the login fields on the login page

**Comment by crescent28** [comment]
@JunkyardCat It is not possible to use ERPNext without internet. Please let us know a valid issue with a screenshot / gif else allow me to close the issue.

**Comment by JunkyardCat** [comment]
@crescent28

Can you tell me why it became like this?  Some users were also surprised that it doesnt work without internet.

**Comment by JunkyardCat** [comment]
@crescent28 

can i ask why you guys shifted to online only for erpnext?

**Comment by netchampfaris** [comment]
Fixed here: https://github.com/frappe/frappe/pull/7151

**Comment by gmplab** [comment]
#17735 #16979

**Comment by shahicoservices** [comment]
Hello guys, I''m having this issue right now. I''m trying to read thru the discussion but I am unable to find the solution. Can someone enlighten me and show me the solution please. I''m really sorry I''m just new to frappe and just starting to learn.

![Blank login](https://user-images.githubusercontent.com/61452347/78887668-ed9e8d80-7a68-11ea-9f1b-d8e5134842fa.JPG)

thanks in advance.

Blank login
