### ISSUE TITLE
Cannot import / export some builtin DocTypes

### ISSUE THREAD

**Issue by JoyceBabu** [frappe/erpnext#16971]
Not all builtin DocTypes can be imported / exported. Some can only be exported, whereas some can only be imported. Is this an omission, or by design?

| DocType | Import | Export 
-----------| -------| --------
Leave Type | Yes | No
Letter Head | No | No
Holiday List | Yes | No
Leave Policy | No | Yes

**Comment by JoyceBabu** [comment]
I just noticed that even though 'Leave Type' does not appear in the drop down, it still works when I type the DocType name correctly.

**Comment by kennethsequeira** [comment]
@JoyceBabu what version are you on?

Make sure that the user has **Export** permission granted so it is picked up in data export.

**Comment by kennethsequeira** [comment]
Closing as no further updates provided.

Doctypes will be available in the Import/Export dropdowns if permission is granted via [Role Permission Manager](https://docs.erpnext.com/docs/user/manual/en/setting-up/users-and-permissions/role-based-permissions)
