### ISSUE TITLE
[v11.1.14] Can not remove icon from dektop

### ISSUE THREAD

**Issue by ophl55** [frappe/erpnext#16988]
**ERPNext**: v11.1.14 (master)
**Frappe Framework**: v11.1.14 (master)

I can not remove some icons from desktop. 

![image](https://user-images.githubusercontent.com/5788712/54845366-6fded700-4cd9-11e9-98a7-fe30827648b6.png)

**Comment by ophl55** [comment]
I updated the system. Same error in v11.1.16

**Comment by crescent28** [comment]
@ophl55 Replicated this on my instance and it seems to be adding or removing the desktop icons fine. Please verify again.

**Comment by Muzzy73** [comment]
Please check user permissions as it maybe blocked from there.

**Comment by ophl55** [comment]
@Muzzy73 thanks for your reply. Can you please specify the user permissions to check? my user is system manager. shouldn't it work fine than?

the issue is still there. meanwhile I updated to verison v11.1.31.
