### ISSUE TITLE
Cannot create customers

### ISSUE THREAD

**Issue by pinster68** [frappe/erpnext#16982]
<img width="1280" alt="Screen Shot 2019-03-22 at 9 49 34 am" src="https://user-images.githubusercontent.com/48811162/54790306-c3293900-4c89-11e9-9cdd-4add06036e99.png">

I cannot create any New Customers.  It was working fine but now I get a weird message about Represents Company Must be Unique.  Screen shot is attached.    This is a regular retail customer, internal Customer is NOT ticked.

This is a very serious issue, I can't create any new Customers. A number of users in the forum have the same issue.

Installed Apps
ERPNext: v11.1.15 (master)
Frappe Framework: v11.1.15 (master)

Thanks
Joe

**Comment by nafifi** [comment]
Same issue for me. It happened all of a sudden..
ERPNext: v11.1.14 (master)
Frappe Framework: v11.1.14 (master)

**Comment by hastelloy** [comment]
It's same for creating Suppliers.

----------------------------
Installed Apps
ERPNext: v11.x.x-develop (80ff296) (develop)
Frappe Framework: v11.x.x-develop (a50aeb2) (develop)

**Comment by nafifi** [comment]
The only workaround I could find for now is to use SQL statement to clear the field represents_company : 
update `tabCustomer` set `represents_company`= NULL;
This allows me to create a new customer.. But you'll need to execute this statement after every new customer that you create..

**Comment by Olawale1** [comment]
Hi ,

This problem occurs when the user has a 'User Permission' for 'Company' in their user profile... and this really should be the case for all users

What seems to happen is that the 'Represents Company' field gets populated with the value of 'Company' in the user's permission. The normal way around this is to make sure the 'Ignore User Permission' field is checked for the 'Represents Company' field (this can be done via Customize Form)

The issue however is that the 'Ignore User Permission' option doesn't seem to work in Quick Entry so you'll either have to keep clicking on the 'Edit in Full Page' option each time you want to create a customer or turn off Quick Entry for the Customer DocType (which can also be done via Customize Form)

Cheers

**Comment by gbm001** [comment]
This is still causing our company issues...

**Comment by crescent28** [comment]
@pinster68 This issue does not persist in version 12, you can upgrade to the latest instance
