### ISSUE TITLE
Ability to Freeze panes in Script Reports

### ISSUE THREAD

**Issue by Mishaal1021** [frappe/erpnext#17005]
Hi,
1.For the financial statements, in Version 10, we had option to “Expand All/Collapse All”. I can not find this in Version 11. This was incredibly useful, and would appreciate if it can be added to V11.

2.Also, I would again like to request this report by month. It is very difficult as the system doesn’t even allow us the PDF the report as there are too many columns. If we could just have the filter by dates, instead of by Fiscal Year only,

3.When reviewing any script report that are in grid format, the system doesn’t allow the user to freeze pane or to move/delete/add columns. Also, in some reports, like financial statements, the filter for date range is not available. This makes it really difficult for user to use ERP to review data within the system. The only way around it is to export the report in excel and modify it.

4.We are also using Budgets in ERP request you to kindly link this budget in income statement which will help us to see the variances at one place as of now we are combining two reports manually in excel to see the variance. this feature will save lots of time.

I can guarantee you that it will assist a lot of the users.

**Comment by ankush** [comment]
Tracked here: https://github.com/frappe/datatable/issues/163
