### ISSUE TITLE
v11 Wrong date on New Shift Assignment from calender view creation

### ISSUE THREAD

**Issue by monolithonadmin** [frappe/erpnext#17002]
Helo,

If you open New Shift Assignement in ERPNext and switch to calender (default) view, then click into one day, and then double click in whole day area, the New Shift Assignments form opened, but it shows a wrong date. It always set date one day later. 
![chrome-capture](https://user-images.githubusercontent.com/5338127/54885710-9474b380-4e7f-11e9-81c4-d6fb441edb70.gif)

**Comment by ruchamahabal** [comment]
Not applicable anymore since shift assignment schema was changed
