### ISSUE TITLE
patient appointment can not save .They are showing error (Please set a default Holiday List for Employee )

### ISSUE THREAD

**Issue by kushluv** [frappe/erpnext#17016]

**Comment by pjamsheer** [comment]
This is not an error, just a validation message and this message show only for the Healthcare Practitioner, who is linked with an Employee. Please set a default Holiday List for the Employee linked to the Healthcare Practitioner or delete the reference of Employee from Healthcare Practitioner document.

**Comment by Muzzy73** [comment]
I agree with @pjamsheer. Any appointment based software always asks availability of staff to make a booking.
