### ISSUE TITLE
Multiple General Ledger Dimensions

### ISSUE THREAD

**Issue by jaichavan** [frappe/erpnext#17026]
Currently, Cost Center and Project can be used to do profitability analysis for a company. We want to redesign the structure to create it configurable (at time of creation of Account) so that multiple dimensions exist for granular analysis of every transaction and financial statements/reports

**Comment by parsimonyERP** [comment]
+1

**Comment by Muzzy73** [comment]
Features request can be expedited by opening a paid enhancement on ERPNext job page. Service providers who be happy to create it for you for a reasonable payment.

**Comment by peshgathoni** [comment]
+1

**Comment by karannshah** [comment]
+1

**Comment by rmehta** [comment]
fixed via #17769
