### ISSUE TITLE
V11 Batch is absent in naming series list

### ISSUE THREAD

**Issue by alpkaan83** [frappe/erpnext#17068]
i cant find the batch in naming series list. it was present on v10 but in 11.1.17 there isn't. i want to make sequent id's auto on batch number.

**Comment by kennethsequeira** [comment]
It is available in the item master:

![image](https://user-images.githubusercontent.com/33246109/55280308-de5f0d00-5349-11e9-8d0e-e71b9c2836da.png)

**Comment by alpkaan83** [comment]
I write the lot frefix in main item. It says changes applied to variants. But nothing changes in variants

--
Android için myMail uygulamasından gönderildi

Cumartesi, 30 Mart 2019, 09:44PM +03:00 gönderen: Kenneth Sequeira notifications@github.com<mailto:notifications@github.com>:


It is available in the item master:

[image]<https://user-images.githubusercontent.com/33246109/55280308-de5f0d00-5349-11e9-8d0e-e71b9c2836da.png>
