### ISSUE TITLE
[V11] base64 image is converted to file

### ISSUE THREAD

**Issue by crckmc** [frappe/erpnext#17089]
When entering HTML code in an e-mail that contains an embedded base64 image the base64 string gets decoded to a file which is then referenced by the code.

This behaviour is really problematic as the whole reason for embedding the picture is that no external content should have to be loaded when e.g. the customer is viewing the e-mail.

This also doesn't work with a local running ERPNext instance as the file is then only accessible in our local network and won't show in any mail opened in another network.

This is a repost of https://github.com/frappe/frappe/issues/7158 because I don't know if the issue is more related to erpnext or frappe.

**Comment by kennethsequeira** [comment]
@crckmc this is a framework issue. Since you've already posted this in Frappe, will be closing this thread.
