### ISSUE TITLE
Custom app not appear on desk v12.x.x-develop

### ISSUE THREAD

**Issue by perkasajob** [frappe/erpnext#17112]
v12.x.x-develop

My custom apps does not appear on desk cards and neither on list of show/hide cards, but I can still access using search bar, but it seems takes unusually very long time.

**Comment by masifi** [comment]
I have the same issue with v12, I created a custom app, then created a module that contains different DocTypes. I can't add the module or any of the DocTypes to a new desk.

**Comment by seacow188** [comment]
I have the same issue with V12. It bothered me long time. My custom app shows on desk in previous vesion like V11, but not showing on desk in V12. Can anyone help?

**Comment by seacow188** [comment]
I have the following set up:
1. ERPNext on develop mode and on V12, and ERPNext installed on site: site1.local
2. I created a customized app, called myapp, installed myapp to the same site: site1.local
3. I have created a new doctype in myapp: medince_process
Now, I want my customized app to show on desk, but it never shows. 
1. My customized app, desktop.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from frappe import _

def get_data():
	return [
		{
			"module_name": "Myapp",
			"color": "grey",
			"icon": "octicon octicon-file-directory",
			"type": "module",
			"label": _("Myapp")
		}
	]
2. I haven't made any change in the hook.py yet.

I don't know the logic to make the customized app show on desktop, on version 11 it works fine. But, on V12 (I knew all the desktop UI changed), but has no way to get the customized app show on desk. 

Can anyone help here?

**Comment by gaurav1katiyar2011** [comment]
Same Issue I am also facing. 
I m doing as below :- 
1) Migrated from 6 to 12 
2) create new app
3) create new site
4) install newly created app into newly created site
5) it successfully installed but not listed in desk

**Comment by SAIRAMRAJU** [comment]
I am also facing the same issue.  In 11 , the Custom app was visible in the Desk.  Where as in 12 I am unable to locate the Custom app.  Where as the Doc types are available in the Search bar.

**Comment by gaurav1katiyar2011** [comment]
@SAIRAMRAJU Goto to Menu-->Set Desktop Icon--> Select preferred Icon and save the setting. it works for me

**Comment by catrielmuller** [comment]
@gaurav1katiyar2011 Sorry can you sent me where i can create a new card for my custom module, Thanks

**Comment by gaurav1katiyar2011** [comment]
@catrielmuller please find below screenshot to set icon on desktop
![image](https://user-images.githubusercontent.com/23612057/62442704-a5b9bf00-b793-11e9-9b22-1cd65b91be0d.png)

![image](https://user-images.githubusercontent.com/23612057/62442734-bd914300-b793-11e9-89c6-5e73fbec6512.png)

**Comment by tgunaratne** [comment]
I guess "Set Desktop Icons" is no longer there in v12. Instead, it has "Show/Hide Cards". 

I am also facing the same issue where my module is not shown in the desktop after upgrading from v11.x to v12. Based above questions I am not the only one facing this issue and would appreciate if someone could help us.

I created the following forum post.
https://discuss.erpnext.com/t/custom-module-links-doesnt-show-in-the-desktop-after-v12-upgrade-from-v11-xx/51813

**Comment by sau6402** [comment]
We are also facing the same issue.
Why do we need to edit the JSON file, it should be readily available at the UI level itself.

Can someone please help me edit those 2 .py files. I am unable to do them.

**Comment by dawoodjee** [comment]
Also had this issue

Solved it here https://discuss.erpnext.com/t/custom-app-not-showing-on-desk-of-v12/51256/8?u=adam26d

**Comment by kennethsequeira** [comment]
Since v12 re-design, the icons/shortcuts have to be separately configured to appear on desk by making a separate desktop.py file under the app.

Answered in the thread mentioned by dawoodjee

**Comment by dawoodjee** [comment]
Cant these be auto generated and then edited by the user as needed?

**Comment by kennethsequeira** [comment]
Can't be auto-generated as-off V12. 

There are more changes coming to the desk which are currently on the develop branch and are being actively updated. You can check the following threads for more info on the same:

https://discuss.erpnext.com/t/redesigning-desk/59105

https://github.com/frappe/frappe/projects/3

In the newer design, the card information has to be added in a JSON file. Eg: https://github.com/frappe/erpnext/blob/develop/erpnext/agriculture/desk_page/agriculture/agriculture.json
