### ISSUE TITLE
Conversion UOM not shown in Order DocType 

### ISSUE THREAD

**Issue by Hadi-Ti** [frappe/erpnext#17115]
Dears When i use multiple UOM with items. it works properly but the main order doctype do not show the UOM converted however i manage this in print format. Please look into the matter and make it work in order doctype as well.

![image](https://user-images.githubusercontent.com/1536351/55456142-f5725900-55ee-11e9-8629-ab0c289f68d7.png)

These are different UOMs

**Comment by Hadi-Ti** [comment]
in Print format

![image](https://user-images.githubusercontent.com/1536351/55456194-1fc41680-55ef-11e9-9acb-ccea0739006e.png)

**Comment by kennethsequeira** [comment]
@Hadi-Ti please post customization relates issues and queries on the community forum: https://discuss.erpnext.com.

We use Github to manage bugs and feature requests.
