### ISSUE TITLE
Error for item absent variants - Value cannot be changed for Variant Based On

### ISSUE THREAD

**Issue by Annacl1** [frappe/erpnext#17147]
I have error "Value cannot be changed for Variant Based On" when editing item and we haven’t variants at all in item list.
I noticed
- the same item with an error today I changed 9 days ago (at 28.03.2019) and all was OK, we did not make any changes during this time for this item (and other old items).
- we have items added 4 days ago (at 01.04.2019), I can change them all without error. But all older items have error - Value cannot be changed for Variant Based On.

![Screen Shot 2019-04-05 at 13 10 34](https://user-images.githubusercontent.com/49288415/55621526-6f007780-57a6-11e9-9bad-0674b4f6d168.png)
![Screen Shot 2019-04-05 at 13 10 50](https://user-images.githubusercontent.com/49288415/55621535-73c52b80-57a6-11e9-9f15-e77d026ed006.png)

The same problem at User Forum without solution:
https://discuss.erpnext.com/t/error-saving-items/47488
https://discuss.erpnext.com/t/value-cannot-be-changed-for-variant-based-on/47383/2

**Comment by chlarsen** [comment]
The same, here - happens on latest stable version. 
I do have variants, and the error occurs, when I wish to add a variant using existing attributes. 
Example: I have items entered as variants to template A in colours blue and yellow, i.e. items A-BL and A-Y. I want to add another variant, say, A-BR for brown, and get this error. This is a pretty disastrous showstopper, as I cannot commit any inventory, nor do invoicing, etc. Any ideas what I am missing here?

**Comment by saurabh6790** [comment]
Fixing in https://github.com/frappe/erpnext/releases/tag/v11.1.20

**Comment by chlarsen** [comment]
Great! Thank you!
