### ISSUE TITLE
Member cannot login to their account : user do not have document access

### ISSUE THREAD

**Issue by Catyung0217** [frappe/erpnext#17158]
Dear All,

We have received a lot of our platform users report that they cannot login to their account.
Just happneded in yesterday , our admin did not change anything on setting or touch anything on the premission.

Here is the error message, when the members tried to log in: 
"user do not have document access"

Does anyone has the solution ?

Cheers!

Cat

**Comment by clarkejj** [comment]
Thanks for reporting but you best post this on discuss with version details, a screenshot with error message or traceback. The idea is to share with others for help to identify and resolve this.

**Comment by maxwelljvogel** [comment]
Also experiencing issue.

**Comment by clarkejj** [comment]
Here is another that concerns a report that is perhaps related https://discuss.erpnext.com/t/not-allowed-for-report-client-sales-report-user-do-not-have-document-access/47788

**Comment by kennethsequeira** [comment]
Closing as @maxwelljvogel confirmed that the issue was patched: https://discuss.erpnext.com/t/not-allowed-for-report-client-sales-report-user-do-not-have-document-access/47788/4?u=kennethsequeira
