### ISSUE TITLE
Trial Balance-Equity

### ISSUE THREAD

**Issue by isma3elyahya** [frappe/erpnext#17179]
Hello,

**I have a problem is when we add the budget in the opening entries by journal entry, the equity is entered creditor but in the trial balance showing in debtor.**

How can i fixed this issue?

![Trial issue 2](https://user-images.githubusercontent.com/45967278/55777300-36171a00-5aa8-11e9-99cd-ac4b80fb0198.PNG)
![Trial issue](https://user-images.githubusercontent.com/45967278/55777301-36171a00-5aa8-11e9-8884-3a23a9af9885.PNG)

**Comment by olamide2** [comment]
Confirmed that this is happening.

Looks like a bug

**Comment by isma3elyahya** [comment]
@nabinhait Please, Did you know why?

**Comment by deepeshgarg007** [comment]
@olamide2 @isma3elyahya Unable to replicate. Please reopen is this is still happening
