### ISSUE TITLE
Projectwise and Itemwise purchase report

### ISSUE THREAD

**Issue by Thomasvdw** [frappe/erpnext#1720]
Dear Sir/Madam, 

Looking for a projectwise and itemwise purchase report (costs of each item, listed per project, with totals). Report in 'Purchase Order Trends' does not do this correctly. 

Kind regards, 

Thomas

**Comment by Arundhatii** [comment]
Can be achieved by creating a custom report similar to that of Item-wise Purchase History and picking the Project column in the custom report.
