### ISSUE TITLE
UOM in material request cannot be changed if default purchasing uom

### ISSUE THREAD

**Issue by cgpurbaugh** [frappe/erpnext#17212]
A default purchasing UOM must be set in the item to replicate

If a user creates a new Purchase Request for an item, its' uom will default to the 'Default Purchasing UOM'.  the user can change the field, but it will revert back once the line item is closed.

This field should either be made read-only if there is a default purchasing uom, otherwise if the user changes it, those changes should be persistent.

**Comment by sharmanakul** [comment]
On v13.14, I tried this use-case:
1 created purchase request
2 default purchasing UOM was fetched
3 I was able to change the UOM in the child table
4 On saving the purchase request, the UOM didn't revert to default purchase UOM in the child table.

please open the issue if it still persists for you.
