### ISSUE TITLE
Allow items from material requests to be added to separate POs based on Vendor [Proposal]

### ISSUE THREAD

**Issue by tristanvigar** [frappe/erpnext#17233]
**Feature Goal/Use Cases:**

We have a use case where it makes the **most sense to consolidate as many items for a PO from a similar vendor as possible** (**If we consolidate to a weekly order from vendors, we see enhanced discounts from some vendors**).

The would be to add a **"Allocate to PO by Supplier"** button/option under "Make" in the Material Request screen. A prerequisite of this would be to add a Vendor (based on Item Prices that exist for this Item) to the Item line in the Material Request. Using "Allocate to PO by Supplier" would check line by line to see if a PO for the Vendor referenced in the Item line exists. If so, option to add Material Request Item to PO would be available. If not, a new Purchase Order for that Supplier would be created with the line item attached to that the new Purchase Order.

**Additional DocTypes/Fields:**

This wouldn't require any new DocTypes. This would simply need to leverage existing doctypes and operate as a series of validation checks before creating a Purchase Order based on the **Business Logic** section of proposal.

**Discovery**

This can be found using the **Make** button in the Material Request screen.

**Business Logic/Calculations/Validations/Logs**

- Dropdown for Supplier selection in Line Item based on Item Price entries in Purchasing Price List for Suppliers. If SupplierA and SupplierB have a Purchase Item price for ItemA, SupplierA and SupplierB should show in dropdown.

- Once Suppliers are set by end user, "Allocate to PO by Supplier" checks per line to establish who the selected Supplier is and checks if a **Draft** state PO exists for that Supplier. If Yes, add item to **Draft** PO. If No, create new PO in **Draft** state for Supplier and add Item to that PO.

This should be done iteratively to ensure 5 items that should be on the same PO are not created separately on 5 separate POs.

**Could anybody from Frappe comment on if this feature would be useful in ERPNext or if the use case is too narrow?**

**Comment by tristanvigar** [comment]
My own use case would see this implemented in v11.1.18.

**Comment by tristanvigar** [comment]
I've found out this feature exists but not in the way I had anticipated. To achieve the functionality above, do the following:

In Item master, under **Sales, Purchase and Accounting Defaults**, set **Default Supplier** for item.

In Purchase Order, use **Get Items from Open Material Requests** to pull all items marked with a Default Supplier entry of the Supplier name referenced in Purchase Order. 

The Material Request number is attached per line item on the Purchase Order. This can be used to remove items that, for one reason or another, aren't appropriate to add to that PO. This maintains the Material Request status of "Pending"

Hopefully somebody else will benefit from this information. Thanks!

**Comment by mitchfromtoronto** [comment]
I'm sorry to bother you but I have a project for you and don't know how to reach you so trying on here.
Can you please email me ?
My name is Mitchell Ribeiro and I live in Toronto Canada
mitchfromtoronto@gmail.com
It's to do with some Python programming that I am in need of
If you'd like you can call me
1-416-532-1890
Looking forward to communicating with you
Thanks
