### ISSUE TITLE
[bug] v.11 in Cloud: Round function still doesn't work properly with precision more than 2

### ISSUE THREAD

**Issue by mayamihaylova** [frappe/erpnext#17276]
Currency values are rounding to 2 even though precision is 6 for all prices like 0.001930, with 0 for the last digit after decimal point.
In other words, when the last digit after decimal point is 0, value is rounded to 2 digits after decimal point. When last digit after decimal point is > 0 round function works OK.

Example: BOM
There are differences in information in the BOM Item Detailed screen before and after submission. Before submission the rate field is correct, but after submission isn't.

This problem is appeared in the following versions:
1. ERPNext: v10.1.18; Frappe Framework: v10.1.16
2. Cloud **ERPNext: v11.1.21 (master)** Frappe Framework: v11.1.22 (master)

It could be related with issue #17271.

![Currency precision](https://user-images.githubusercontent.com/48950151/56360706-1d1c1080-61ee-11e9-8a52-b29b7e1528e0.PNG)

![NewBOM in cloud](https://user-images.githubusercontent.com/48950151/56360776-4d63af00-61ee-11e9-8b6b-d637c55779b4.PNG)

![BOM Item Detailed in cloud](https://user-images.githubusercontent.com/48950151/56360790-52c0f980-61ee-11e9-9451-f81ed3b20b7b.PNG)

![BOM Item Detailed Submitted in cloud](https://user-images.githubusercontent.com/48950151/56360797-56ed1700-61ee-11e9-9f9f-8abf0ac5a540.PNG)

**Comment by deepeshgarg007** [comment]
@mayamihaylova   Closing this issue. If the issue still persists in the latest version-13 or above then please reopen a new issue
