### ISSUE TITLE
[bug] Incorrect Rate calculation in BOM for some Items when the Currency Precision more than 2

### ISSUE THREAD

**Issue by mayamihaylova** [frappe/erpnext#17271]
I've changed the Currency Precision to 6 and defined all Items Value Rate with this precision.
When I've created BOM and I've added all Items, random of them was showed in BOM Item Table correctly with the right precision, but the others was rounded.
This is a big problem when there are the very small components and their rates need more than 2 currency precision like 0.00123.
There are differences in information in the BOM Item Detailed screen before and after submission.
Before submission the rate field is correct, but after submission isn't.
 (ERPNext: v10.1.18; Frappe Framework: v10.1.16)
The following screenshots illustrated the described problem.
Could you anybody help me, please?

![New BOM](https://user-images.githubusercontent.com/48950151/56279377-a52be880-6110-11e9-9340-5d482a884b41.PNG)

![BOM Item Detailed Screen](https://user-images.githubusercontent.com/48950151/56279575-0ce23380-6111-11e9-82d0-c3aa5e23d6eb.PNG)

![BOM Item Detailed Screen Submitted](https://user-images.githubusercontent.com/48950151/56279581-1075ba80-6111-11e9-85df-a53ac8775cd9.PNG)

**Comment by deepeshgarg007** [comment]
@mayamihaylova   Closing this issue. If the issue still persists in the latest version-13 or above then please reopen a new issue
