### ISSUE TITLE
contact us form not working

### ISSUE THREAD

**Issue by lbazan** [frappe/erpnext#17270]
Hi erpnext team

All the emails and notifications work success but the contac us page not working...

Thanks!

![image](https://user-images.githubusercontent.com/3780147/56242435-e616f500-605d-11e9-92cf-7d26b7fa7cdb.png)

**Comment by kennethsequeira** [comment]
@lbazan 

What version was this on?

Right now the contact form is working well on v10, v11, and v12

Do check by updating to the latest version.
