### ISSUE TITLE
Allow to add items in manufacturing process which are not part of bom items

### ISSUE THREAD

**Issue by dineshpanchal93** [frappe/erpnext#17275]
Issue
We need solution of Multiple Stock Entry “Material Transfer to Manufacture” of against one Production order(Qty 1 ). and final we make Manufacture entry of that Production order, it will fetched all the items from Stock entry against related to Production order.

Right now, we can able to create only one Stock entry against production order.
when we trying to add more stock entry against production order. gives me an error
“Material Transferred for Manufacturing (2.0) cannot be greater than planned quantity (1.0) in Production Order PRO-0002”

**Comment by Priteshzeal** [comment]
![image](https://user-images.githubusercontent.com/47026433/56400987-56975f00-6274-11e9-8cca-d5ef03348a8d.png)

https://erpnext.com/docs/user/manual/en/manufacturing/setup/manufacturing-settings

**Comment by kennethsequeira** [comment]
@dineshpanchal93 kindly post functionality related questions on the forum: https://discuss.erpnext.com

Github issues are used specifically to track new feature requests and bugs.
