### ISSUE TITLE
[bug] Campaign Efficiency report only works in english

### ISSUE THREAD

**Issue by Don-Leopardo** [frappe/erpnext#17282]
**Description:**
The Campaign Efficiency report only works in english. When you change the language setting, the report stops working.
Testing this, I discovered that almost every calculated value in the report was missing the float conversion and showing 0 when it was less than 1. 

**System Version:**
ERPNext: v11.1.5 (master)
Frappe Framework: v11.1.5 (master)

**Steps to recreate the bug:**
- Generate some data
- Configure the language in english
- Look at the Campaign Efficiency report
- Some values may appear set in 0 (being it an incorrect value)
- Configure the language in a different one (tested in spanish: es)
- Look at the Campaign Efficiency report (it should be empty)

**Screenshots:**
In english:
![Captura de pantalla 2019-04-18 a la(s) 12 09 14](https://user-images.githubusercontent.com/46027152/56376203-a0813600-61dd-11e9-9ead-057fa4b7945e.png)
In spanish:
![Captura de pantalla 2019-04-18 a la(s) 12 08 32](https://user-images.githubusercontent.com/46027152/56376212-a37c2680-61dd-11e9-889e-b6ab04bc2f25.png)

**Note:** I'm working on a PR for this issue.

**Comment by gdrubich** [comment]
Having the same issue.

**Comment by fproldan** [comment]
Fixed in PR https://github.com/frappe/erpnext/pull/17284
