### ISSUE TITLE
dict' object has no attribute 'make_payment_via_journal_entry

### ISSUE THREAD

**Issue by sumeetagra** [frappe/erpnext#17304]
Traceback
 /home/frappe/frappe-bench/apps/frappe/frappe/app.py: 61

59 
60 		if frappe.local.form_dict.cmd:
61 			response = frappe.handler.handle()
62 
63 		elif frappe.request.path.startswith("/api/"):
 /home/frappe/frappe-bench/apps/frappe/frappe/handler.py: 21

19 
20 	if cmd!='login':
21 		data = execute_cmd(cmd)
22 
23 	# data can be an empty string or list which are valid responses
 /home/frappe/frappe-bench/apps/frappe/frappe/handler.py: 56

54 	is_whitelisted(method)
55 
56 	return frappe.call(method, **frappe.form_dict)
57 
58 
 /home/frappe/frappe-bench/apps/frappe/frappe/__init__.py: 1027

1025 	newargs = get_newargs(fn, kwargs)
1026 
1027 	return fn(*args, **newargs)
1028 
1029 def get_newargs(fn, kwargs):
 /home/frappe/frappe-bench/apps/frappe/frappe/model/mapper.py: 41

39 
40 	for src in json.loads(source_names):
41 		target_doc = method(src, target_doc)
42 	return target_doc
43 
 /home/frappe/frappe-bench/apps/erpnext/erpnext/stock/doctype/purchase_receipt/purchase_receipt.py: 467

465 			"add_if_empty": True
466 		}
467 	}, target_doc, set_missing_values)
468 
469 	return doclist
 /home/frappe/frappe-bench/apps/frappe/frappe/model/mapper.py: 113

111 
112 	if postprocess:
113 		postprocess(source_doc, target_doc)
114 
115 	target_doc.set_onload("load_after_mapping", True)
 /home/frappe/frappe-bench/apps/erpnext/erpnext/stock/doctype/purchase_receipt/purchase_receipt.py: 419

417 		doc = frappe.get_doc(target)
418 		doc.ignore_pricing_rule = 1
419 		doc.run_method("onload")
420 		doc.run_method("set_missing_values")
421 		doc.run_method("calculate_taxes_and_totals")
 /home/frappe/frappe-bench/apps/frappe/frappe/model/document.py: 772

770 
771 		fn.__name__ = str(method)
772 		out = Document.hook(fn)(self, *args, **kwargs)
773 
774 		self.run_notifications(method)
 /home/frappe/frappe-bench/apps/frappe/frappe/model/document.py: 1048

1046 
1047 			composed = compose(f, *hooks)
1048 			return composed(self, method, *args, **kwargs)
1049 
1050 		return composer
 /home/frappe/frappe-bench/apps/frappe/frappe/model/document.py: 1031

1029 		def compose(fn, *hooks):
1030 			def runner(self, method, *args, **kwargs):
1031 				add_to_return_value(self, fn(self, *args, **kwargs))
1032 				for f in hooks:
1033 					add_to_return_value(self, f(self, method, *args, **kwargs))
 /home/frappe/frappe-bench/apps/frappe/frappe/model/document.py: 766

764 
765 		if hasattr(self, method) and hasattr(getattr(self, method), "__call__"):
766 			fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
767 		else:
768 			# hack! to run hooks even if method does not exist
 /home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py: 50

48 
49 	def onload(self):
50 		super(PurchaseInvoice, self).onload()
51 		supplier_tds = frappe.db.get_value("Supplier", self.supplier, "tax_withholding_category")
52 		self.set_onload("supplier_tds", supplier_tds)
 /home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/accounts_controller.py: 35

33 		if self.get("__onload"):
34 			self.get("__onload").make_payment_via_journal_entry \
35 				= frappe.db.get_single_value('Accounts Settings', 'make_payment_via_journal_entry')
36 
37 		if self.is_new():###

**Comment by scmmishra** [comment]
Please share the detailed steps on reproducing the error.

`accounts_controller` is the core of most of accounting transactions in ERPNext, so any problem in this should be breaking a lot more things making it's too broad to investigate just by looking at the traceback. However in most of my local instances, I am not facing any issues.

P.S. Please try to post a better formatted and complete traceback, along with versions of both Frappe and ERPNext you are using.

**Comment by scmmishra** [comment]
@sumeetagra a gentle follow up on this. Can you help me replicate the bug, otherwise I should close this issue as invalid.

**Comment by kennethsequeira** [comment]
Closing the issue as no further updates provided.
