### ISSUE TITLE
SARS VAT201 Report in ERPNext

### ISSUE THREAD

**Issue by jaichavan** [frappe/erpnext#17328]
Most South African accounting systems have a VAT 201 report that has to be submitted to the South African Revenue Service...this is with respect to getting this report through ERPNext.

#ENQ-17-18-09600

**Comment by extremeshok** [comment]
https://www.sars.gov.za/AllDocs/OpsDocs/Guides/GEN-ELEC-04-G01%20-%20Guide%20for%20completing%20the%20Value%20Added%20Tax%20VAT201%20Declaration%20-%20External%20Guide.pdf

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.
