### ISSUE TITLE
Module names doesn't appear 

### ISSUE THREAD

**Issue by medberroug** [frappe/erpnext#17334]
I have this issue where Module names doesn't appear in the desk : 
![image](https://user-images.githubusercontent.com/16431066/56517176-d8fd7880-652b-11e9-9e0e-838528c94e70.png)
thank you community

**Comment by rmehta** [comment]
Please share your branch / version. Works for me on latest develop

<img width="979" alt="Screenshot 2019-04-26 at 11 16 28 AM" src="https://user-images.githubusercontent.com/140076/56785948-ce393100-6814-11e9-8330-8c15b3ddd01a.png">

**Comment by medberroug** [comment]
I'm suing *ERPNext:* v11.1.20 (master)

*Frappe Framework:* v12.x.x-develop () (develop)

**Comment by jpilz** [comment]
Missing some Module names also:

ERPNext: v11.1.44 (master)
Frappe Framework: v12.x.x-develop () (develop)

**Comment by heunghingwan** [comment]
same
ERPNext: v11.1.47 (master)
Frappe Framework: v12.x.x-develop () (develop)

![image](https://user-images.githubusercontent.com/11424817/61343273-c02d0680-a87f-11e9-8f3c-60b96af6e7d4.png)

**Comment by heunghingwan** [comment]
showing undefined in here:
![image](https://user-images.githubusercontent.com/11424817/61343385-1f8b1680-a880-11e9-87ef-8d1c7bd7ceef.png)
if click on the module, it will reappear:
![image](https://user-images.githubusercontent.com/11424817/61343498-87d9f800-a880-11e9-9107-386239f405a8.png)
after click save, it will show again:
![image](https://user-images.githubusercontent.com/11424817/61343541-af30c500-a880-11e9-9f70-b418b1d1bca9.png)
if reload, it will disappear:
![image](https://user-images.githubusercontent.com/11424817/61343583-e1422700-a880-11e9-803b-5b4b985bdc2c.png)
