### ISSUE TITLE
Can't create re-direct item from the Sales order in the Delivery note.

### ISSUE THREAD

**Issue by chiangfive** [frappe/erpnext#17355]
Hi There~
Our team has a problem~ when we make deliver note can't get the item from our sales order...
the get item form is missing... How can I solve this problem?

**Comment by kennethsequeira** [comment]
@chiangfive 

What version of ERPNext are you using?

A fix for a related issue was added some days back: https://github.com/frappe/erpnext/pull/17345

Kindly provide more details for the issue to be replicated.

**Comment by kennethsequeira** [comment]
Closing this as no further details were provided.
