### ISSUE TITLE
Redirected to contact page after adding an item to any item group

### ISSUE THREAD

**Issue by khuongtu** [frappe/erpnext#17353]
Hello,
I am a new user to ERPNext. I have a production installation on my self-hosted server, version 11.1.22.

Currently I am running into a redirect-to-contact-page issue as follow:

_When I add a new [item] to an [item group], the link to that [item group] always redirects to contact page. However the full link to the [item] still works perfectly._

For example:
I added item "chair_01" under parent group "products", then set "Show in website" flag. After that I reload the Home Page, then click Product tab and it redirects to the Contact Page.

The same issue also happens when I try adding item to other item groups.

Anyone know the fix for this issue, please help!

**Comment by ovresko** [comment]
Found a workaround
Go to Shopping Cart Settings
enable + Set modatory fields (series, company ...)
Save  and reload website

**Comment by khuongtu** [comment]
Hello Ovresko,
Thank you very much for the workaround. I am now able to load my product page seeing the items.
