### ISSUE TITLE
Plaid Settings: cannot link new bank account

### ISSUE THREAD

**Issue by barredterra** [frappe/erpnext#17365]
### Reproduce:

1. Open `Plaid Settings`
2. Check "enabled" and save
3. Click "Link a new bank account"

### Error

Overlay opens and disappears again.

```
Error: Invalid key: key cannot be missing.
    at error (LazyLink.js:1)
    at LazyLink.js:1
    at LazyLink.js:1
```

![screencast](https://user-images.githubusercontent.com/14891507/56670898-f2313100-66b3-11e9-90d4-a77b621b96fd.gif)

### Versions
ERPNext: v11.1.22 (hotfix)
Frappe Framework: v11.1.22 (master)

@chdecultot

**Comment by chdecultot** [comment]
It looks like you haven't registered any Plaid key. Have you ?

I'll add a better error handler for this.

**Comment by barredterra** [comment]
Where can i do this? It didn't ask me for a key.

**Comment by chdecultot** [comment]
The api keys need to be added in site_config.json before using the Plaid integration.
I have just created a PR with an error message indicating it. Thanks!
https://github.com/frappe/erpnext/pull/17366

I also realized that the link for the Plaid integration documentation did not exist on erpnext.com. I submitted another PR for that.
In the meantime you can check the doc directly at this URL:
https://erpnext.com/docs/user/manual/en/erpnext_integration/plaid_integration

**Comment by barredterra** [comment]
Thanks!
