### ISSUE TITLE
Not able to see employees in employee list

### ISSUE THREAD

**Issue by RPPL001** [frappe/erpnext#17370]
Not able to see employees in employee list. However "User Persmissions" shows employees

**Comment by chiangfive** [comment]
I got the same problem..

**Comment by crescent28** [comment]
Please check the user permissions applied for the user who cannot see the Employee list: 

Go to User list -> Select User -> Go to Permissions -> Delete the permissions applied on employee. 

This should allow you to get the Employee list.

**Comment by Froos11** [comment]
I'm unable to remove the user due to route history, but, no transctions are there in the system since i have delted them.
