### ISSUE TITLE
Employee data missing after submit

### ISSUE THREAD

**Issue by chiangfive** [frappe/erpnext#17371]
Hi, Support team..

After I create a new employee’s ready and submit… but the employee that I created is missing…
I can’t find my employee data in the employee database…always shows 1 only...
![螢幕快照 2019-04-25 上午8 15 31](https://user-images.githubusercontent.com/25191021/56701588-7e823900-6732-11e9-8daa-57fb359991cd.png)

**Comment by ketansdesai** [comment]
This is because of restricted user permission, you can learn more about the same [here](https://erpnext.com/docs/user/manual/en/setting-up/users-and-permissions).
