### ISSUE TITLE
GST center

### ISSUE THREAD

**Issue by test2a** [frappe/erpnext#17409]
i propose there be a central place at least at the time being for Indian Taxation scenario starting with a GST Tax Center  page where according to the already selected tax preferences like monthly GSTR-1 or Quarterly GSTR-1, composition or regular scheme, there be a page which should hold at least the following items
1. upcoming return to be filed (including due date) 
2. details of past returns filed 
3. unreconciled GSTR-2A with books entries.
3. sales/purchases, debit/credit notes booked/reported (in case of any last minute adjustments in returns)
4. GST reporting in respect of rule 42,43
5.  GST ITC classification report (inputs, capital goods, services)
6. HSN summary report
7. docs issues report
8. tax paid
9. any RCM entries raised and paid in books
10. tax ledgers (cash register/credit register/liability register) for reconciliation with portal
11. eway bills raised, cancelled, received, booked, etc
12. any credit/debit note reported without original invoice data
13. advances on which taxes have been collected/not collected/adjusted/not adjusted
14. details of invoices amended( and if the same was reported)
15. taxes not collected on any expenses (like commissions)
16. invoices incorrectly recorded in books( like item tax rate is 12% but sales recorded at 28%)
Essentially a singular place for indirect taxation of a business to see and monitor changes and correct differences in time. Analytics for doing proper taxes of a business and with time this page  should become a very important page for big businesses who **need** to be up to date with taxation matters because its their statutory duty.

All these have to be done individually and realistically items are forgotten and once a business goes big, these items get too mundane and chances of mistakes grow

**Comment by siddhpant** [comment]
+1

**Comment by umairsy** [comment]
Please refer to the latest GST enhancements and update the pending items. Closings as it's inactive for a while.
