### ISSUE TITLE
[Proposal] To allow ZERO Quantity Items

### ISSUE THREAD

**Issue by tukutela** [frappe/erpnext#17400]
For my client and I'm sure many others, the limitation stopping zero quantity items on Sales and Purchase transactions is seriously limiting, and stopping any updates of those environments to V11. Could we please have a Checkbox on "Account Settings" to allow them?

**Comment by tukutela** [comment]
#17401 Added PR

**Comment by villiger** [comment]
This is important to me.

**Comment by tukutela** [comment]
I've also sent a note to [the forum](https://discuss.erpnext.com/t/feature-request-v11-0-zero-quantity-sales-items/49263), if you are reading this please add a +1.

**Comment by chromonav** [comment]
+1

**Comment by jcagbay** [comment]
+1

**Comment by dwatson-bnovate** [comment]
+1
This would be very useful to show "optional items" as described in this other forum post: https://discuss.erpnext.com/t/how-to-add-optional-sales-items-in-quotation/16722/10. I have noticed salespeople coming from other systems are used to having this feature.

**Comment by moe01324** [comment]
+1 from me!

**Comment by larrydevops** [comment]
+1, There seem to be no progress on this...

**Comment by acb1981** [comment]
+1

**Comment by deepeshgarg007** [comment]
@tukutela Can you please mention the use case and reopen the issue? Currently, the system is not designed to handle 0 qty line item rows. I am pretty sure it can be handled within the existing system

**Comment by zifeo** [comment]
@deepeshgarg007 This would allow us to create sales order with some optional items (quantity = 0 on first customer review and the quantity may increase as customer picks this item). Maybe there is another flow for that, can you advise or re-open?

**Comment by daanlenaerts** [comment]
My usecase would be exactly the same: adding optional lines to a quote.

**Comment by edouardflowasia** [comment]
Interested also for retainers quotation so customer approve the hourly rate
