### ISSUE TITLE
Delivery date on sales order shouldn't depend on the items table.

### ISSUE THREAD

**Issue by techdev-5** [frappe/erpnext#17410]
The delivery_date field on the sales order can't be changed after sales order creation unless you also update the delivery date field in the items table first.
You shouldn't have the delivery date field on the order depend on the items table. It should either be independant or the items table should depend on it instead.

**Comment by agritheory** [comment]
This can be solved with a custom script, which, pleased be warned, _does_ change the default behavior of the Sales Order, though that's what you're asking for. Changing the default behavior would like result in the workflow(s) of others being broken or unexpectedly changing, so a custom script here is likely the best way to go. 

```JavaScript
  frappe.ui.form.on('Sales Order', {
    delivery_date: function(frm){
      if(frm.doc.delivery_date != undefined){
        for(let i in frm.doc.items){
          frappe.model.set_value("Sales Order Item", frm.doc.items[i].name, "delivery_date", frm.doc.delivery_date);
        }
      }
    }
  })

**Comment by techdev-5** [comment]
This does fix the issue.
Thanks.
