### ISSUE TITLE
[Release v11.1.23] - Docs links are not working anymore (URGENT blocking issue)

### ISSUE THREAD

**Issue by alessionobile** [frappe/erpnext#17411]
Hey guys,

We just upgraded to the last ERPNext release. We cannot access any doc anymore as the links in the doc list is not working anymore! All kind of links within the frappe-list component are not working. Including the headers.

Here a screenshot

![link-not-working](https://user-images.githubusercontent.com/1752276/56898792-38aad500-6a92-11e9-9ef5-96adff30d951.jpg)

The link should be clickable, but it is not... hence i can't open any doc anymore! And it happens all over the places :dagger: 

Any solution?

**UPDATE**
It's a small CSS issue. Short term fix described here
https://github.com/frappe/erpnext/issues/17411#issuecomment-487584848
We'll wait for an official fix from the @frappe team

**Comment by RJPvT** [comment]
I have the same problem!

**Comment by jvfiel** [comment]
same issue.

**Comment by kennethsequeira** [comment]
@alessionobile @jvfiel can you post the console log? Looking at this urgently

**Comment by alessionobile** [comment]
https://github.com/frappe/frappe/commit/094520c4c92d159c93f8b416fcfa9b0ae37cf68d#diff-c3062b7a251b496bbb4957982625579dR114

This is the error @kennethsequeira 

If i remove the following piece of CSS, it starts working again ;)

No issues in console as it's a pure CSS issue

&::before {
		content: '';
		position: absolute;
		top: 0;
		right: 15px;
		bottom: 0;
		left: 15px;
		border: 1px solid @border-color;
	}

**Comment by jvfiel** [comment]
I can confirm no issue on .js @kennethsequeira but I havent tried .css as per @alessionobile

**Comment by alessionobile** [comment]
@kennethsequeira i can confirm that by removing that css "hack" fixes the issue. Applied it on my servers and re-executed bench update. Now is functioning again

**Comment by TetraComSA** [comment]
Please fix, this is a series issue....

**Comment by jvfiel** [comment]
@alessionobile should you create a PR?

**Comment by alessionobile** [comment]
@jvfiel I notified @sahil28297 regarding the issue. As he appears to be committing that change. I think it is best for him to fix it properly as he might have had some reasons to put that hack in place.

If you wanna fix it fast in your env, you could just edit the file locally and then wait them to release a new version

**Comment by jvfiel** [comment]
thanks! @alessionobile

**Comment by alessionobile** [comment]
@jvfiel https://github.com/frappe/frappe/releases/tag/v11.1.25

Seems it's good to bench update!

**Comment by RJPvT** [comment]
Just did a bench update and it appears to be fixed

**Comment by sahil28297** [comment]
@alessionobile fixed with this release https://github.com/frappe/frappe/releases/tag/v11.1.25

**Comment by alessionobile** [comment]
thanks for the quick fix @sahil28297 . Much appreciated!
