### ISSUE TITLE
Credit notes and payment reconciliation

### ISSUE THREAD

**Issue by Don-Leopardo** [frappe/erpnext#17417]
Well, the idea is that the **credit notes** should appear in the **payment reconciliation** tool to be used against pending invoices.
I am working on a PR for this, I've already done the standalone credit note case. This is, when you have a standalone credit note and a pending invoice and you match them with the payment reconciliation tool.
But I've reached a stale point, I don't understand how does the credit notes generated against a payed invoice works. For what I can see, after the return is made, the payed invoice's outstanding amount becomes negative and the outstanding amount of the credit note is equal to zero.
So, we should be able to use the "payed" invoice (with negative outstanding amount) against another invoice, but, the question is, what should we do with the GL entries? I tryed to treat the "payed" invoice like a standalone credit note and it didn't work, so, I need some help to understand what's going on and what should I do.

**Related Issues:**
https://github.com/frappe/erpnext/issues/17248
https://discuss.erpnext.com/t/allocate-credit-note-debit-note-to-another-sales-invoice-purchase-invoice/29329

I'm going to tag some members of the Accounts working group using [this](https://discuss.erpnext.com/t/best-practice-to-handle-multi-currency-supplier-and-customer/35355/10) comment as an excuse.
@agritheory @clarkejj @umairsy @SaiFi0102

**Comment by SaiFi0102** [comment]
Hi Don. It's nice to see someone new working on the accounting system of ERPNext, so welcome. I know what you mean, there doesn't seem like there's a straight forward solution for that case, however, you can take a look at my proposal on which I am working on for v12 which can solve this problem: https://discuss.erpnext.com/t/proposal-payment-reconciliation-improvement/46873/

**Comment by Don-Leopardo** [comment]
Hello @SaiFi0102, that's a very nice solution to the problem, what's the actual status of it?
Anyways, I was wonder if there is a chance to do something for the meantime, like, a solution for v11, at least a partial one. What do you think?

**Comment by SaiFi0102** [comment]
I'm working on some other features right now, hopefully in a month or 2 I'll create a PR for my that. The only way I can think of for v11 to reconcile something like that is to create a Journal Entry that references both, a credit/debit note and an invoice. Maybe you could automate that.

I'll probably develop my feature for both v11 and v12

**Comment by Don-Leopardo** [comment]
@SaiFi0102 Hi there, I just remembered this, do you have some news?

**Comment by SaiFi0102** [comment]
Not yet

**Comment by Don-Leopardo** [comment]
@SaiFi0102 How is it going?

**Comment by SaiFi0102** [comment]
Hey Don. I won't be working on this feature anytime soon. Let me know if I can help you in any other way :)

**Comment by kennethsequeira** [comment]
https://github.com/frappe/erpnext/pull/18034
