### ISSUE TITLE
Quick actions after submit disappear too quickly

### ISSUE THREAD

**Issue by fproldan** [frappe/erpnext#17414]
Any insight of where the code of this feature is will be apreciated in order to make a PR that fix it.

![Apr-29-2019 12-32-15](https://user-images.githubusercontent.com/4945122/56907583-f2964700-6a7a-11e9-8212-4ed0be8a71dc.gif)

**Comment by barredterra** [comment]
You can set the timeout in the DocType `Success Action`. No need to change the code.
