### ISSUE TITLE
Quotation broken in latest release v11.1.23

### ISSUE THREAD

**Issue by azharul-islam** [frappe/erpnext#17420]
I cannot select an address. I get “Please set customer” error

I understand the customer field type was changed to dynamic link and field name was changed to “party_name”. However not everything has been refactored properly. For example, Contact Person field has depends on value “eval:doc.customer”. This expression will now never evaluate to "true".
<img width="1041" alt="Screen Shot 2019-04-30 at 12 26 08 AM" src="https://user-images.githubusercontent.com/38819502/56928397-57838880-6adf-11e9-9daf-c271a0f3a884.png">

**Comment by sammish** [comment]
I Have Same issue I cannot create Quotation to Sales order 
![aaa](https://user-images.githubusercontent.com/12432802/56951302-1cfe0800-6b40-11e9-8919-afacc5231839.PNG)

**Comment by JaneshP** [comment]
Since the update, I too can't see any information about the customers (e.g. Address, contact etc) in the quotations.

Looks like only Quotations are affected. Sales orders seem to pick the customer information. Need a quick fix for this, please. We had to stop all the quotations in the company.

**Comment by sammish** [comment]
@JaneshP @azharul-islam do you get solution. i am totally blocked

**Comment by JaneshP** [comment]
@sammish No solution yet for the V11.1.23 issue yet.

**Comment by JaneshP** [comment]
I followed this, as I had a snapshot.
https://discuss.erpnext.com/t/missing-data-from-quotation-pdfs/48490

**Comment by lasalesi** [comment]
+1 also affected by this issue.

Since the link type has been changed, the customer dashboard does not work properly: linked quotations and opportunities are not shown:
![grafik](https://user-images.githubusercontent.com/26505250/57068171-3e422e00-6cd1-11e9-9e9a-c10134227bc5.png)

Clicking the (+) symbol or the link does not filter the route to the list or form.

This is on master, please urgently fix.

**Comment by lasalesi** [comment]
Should be fixed with #17455 

More details on https://discuss.erpnext.com/t/quotation-broken-in-latest-release-v11-1-23/48441/2

**Comment by saurabh6790** [comment]
Fixing via https://github.com/frappe/erpnext/pull/17455

**Comment by sammish** [comment]
currently issues is there if you are using customer with customer code. Please need support 

![image](https://user-images.githubusercontent.com/12432802/57087468-ca237c80-6d08-11e9-9998-ec3990c844db.png)

**Comment by rohitwaghchaure** [comment]
@sammish 
We have identified and fixed the issue and tomorrow we'll release the [fix](https://github.com/frappe/erpnext/pull/17469)

**Comment by sammish** [comment]
@rohitwaghchaure there is existing issue if customer with customer code 

https://github.com/frappe/erpnext/issues/17468

**Comment by sammish** [comment]
@rohitwaghchaure thank you
