### ISSUE TITLE
Linked delivery note not appear in sales invoice dashboard (ERPNext cloud hosing) 

### ISSUE THREAD

**Issue by dufani1** [frappe/erpnext#17443]
Hiii
Why linked delivery note not appear in sales invoice dashboard ?

![Untitled111](https://user-images.githubusercontent.com/23026263/57015222-db3e9180-6c13-11e9-92b4-c4582deb95eb.png)

**Comment by kennethsequeira** [comment]
@dufani1 

What version are you on?

Also, did you create the Delivery Note from the Sales invoice or the order?

I created a new DN from the invoice and it is reflected in the dashboard:

![image](https://user-images.githubusercontent.com/33246109/57056320-60cb4b80-6cbf-11e9-9f00-90c7d44d90e0.png)

**Comment by dufani1** [comment]
@kennethsequeira
I am erpnext cloud user and my version is 11.1.24.
The invioce in sales cycle always created after delivery  note, and we create invioce from delivery note and we noted that the delivery note not reflected  in sales invoice  dashboard.
Thanks..

**Comment by rohitwaghchaure** [comment]
@dufani1 This is a know issue
When you make delivery note from the sales invoice, then delivery note link is shows in the sales invoice dashboard(see below 
![Screen Shot 2019-05-02 at 5 20 22 pm](https://user-images.githubusercontent.com/8780500/57073385-9a6f7700-6cfe-11e9-9eb1-895e4e857b97.png)
attachment)

Same when you make sales invoice from the delivery note, then sales invoice link shows in the delivery note dashboard(see below attachment)

![Screen Shot 2019-05-02 at 5 16 45 pm](https://user-images.githubusercontent.com/8780500/57073291-45336580-6cfe-11e9-9eec-94db56fd51ed.png)

**Comment by NightsOfCoding** [comment]
@rohitwaghchaure when sales invoice is created from delivery note link should be shown in both sales invoice and delivery note right. why if sales invoice created from delivery note link shown in delivery note for sales invoice but not int sales invoice dashboard linked delivery note.
