### ISSUE TITLE
Holiday List Calendar View

### ISSUE THREAD

**Issue by auliabismar** [frappe/erpnext#17463]
In version 11 this issue is back
https://github.com/frappe/erpnext/issues/7845

**Comment by auliabismar** [comment]
I'm not sure why is this closed. I tried in latest version, the issue is still there

Installed Apps

ERPNext: v11.1.33 (master)

Frappe Framework: v11.1.30 (master)
![Screenshot_2019-05-27 Holiday List Calendar](https://user-images.githubusercontent.com/13597589/58426383-82ed9900-80c6-11e9-8f05-6becfd41dac9.png)

**Comment by nabinhait** [comment]
The issue has been fixed in hotfix branch, yet not released to master branch.

**Comment by auliabismar** [comment]
Glad to know, thanks!
