### ISSUE TITLE
Bug on Human Resources?

### ISSUE THREAD

**Issue by killmasta93** [frappe/erpnext#17470]
Hi,
I was wondering if someone could tell me if this is an issue with permission or just a bug?
As on the photos you can see the person has permission for leave approval but when a user tries to send a leave it shows blank?

Thank you

![Screenshot at 2019-04-28 18-36-29](https://user-images.githubusercontent.com/13953629/57116061-5b4e1f80-6d18-11e9-86bd-fb943b712160.png)
![Screenshot at 2019-04-28 18-36-49](https://user-images.githubusercontent.com/13953629/57116063-5be6b600-6d18-11e9-83c7-b2b1d75cad40.png)

**Comment by kennethsequeira** [comment]
@killmasta93 if you're on v11, or above you need to first:

1. Add employee in a department in the Employee doctype
2. Assign a Leave Approver in the Department 
3. Check the scenario again

Check the section titled **Setting Up Leave Approver**: https://erpnext.com/docs/user/manual/en/human-resources/leave-application

**Comment by killmasta93** [comment]
Thanks for the reply, see picture below the user is in the employee doctype and the picture above i checked the leave approver

Thank you

![Screenshot at 2019-05-04 11-22-25](https://user-images.githubusercontent.com/13953629/57181935-652e6a80-6e5f-11e9-9b81-94f7e7e898e1.png)

**Comment by killmasta93** [comment]
Bump? anyone else having this issue?

**Comment by sudhanva0597** [comment]
@killmasta93 , It's not just about permissions.
As @kennethsequeira mentioned,
You need to set up leave approver for a department that the employee belongs to.
Once done you will be able to see that user in drop down list in leave application.
This assumes you are on v11 or higher.
There is no bug. I have tested it and it works fine.

**Comment by killmasta93** [comment]
Thanks for the reply, correct i went to settings at the bottom click on department, to the HR, and leave  Approvers i added them see picture 

![Screenshot at 2019-05-17 21-02-40](https://user-images.githubusercontent.com/13953629/57963247-3dbbb100-78e7-11e9-889e-0fd18ea92740.png)

**Comment by sudhanva0597** [comment]
@killmasta93 Did you add the employee to the department ?
Which version are you on ?

**Comment by killmasta93** [comment]
Thanks for the reply, current version is
 ERPNext: v11.1.21 (master)
Frappe Framework: v11.1.22 (master)

yes correct i did add it 
![Screenshot at 2019-05-21 11-06-40](https://user-images.githubusercontent.com/13953629/58112170-95dd0680-7bb8-11e9-9b6b-c48aad17748b.png)
