### ISSUE TITLE
Tally Migration Issue

### ISSUE THREAD

**Issue by Swad** [frappe/erpnext#17479]
Got this error while importing day book data. Had around 50 similar issues.

Exception
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/erpnext_integrations/doctype/tally_migration/tally_migration.py", line 299, in get_vouchers
    vouchers.append(function(voucher))
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/erpnext_integrations/doctype/tally_migration/tally_migration.py", line 347, in voucher_to_invoice
    "doctype": doctype,
UnboundLocalError: local variable 'doctype' referenced before assignment

EDIT:

Checked the code and there is no else condition. We have other voucher types which are not handled.

```
if voucher.VOUCHERTYPENAME.string in ["Sales", "Credit Note"]:
...
elif voucher.VOUCHERTYPENAME.string in ["Purchase", "Debit Note"]:
..
```

No else condition.

Below Voucher type from Tally xml data are not handled. (Not limited to the below list)

- Stock Journal
- Delivery Note
- Receipt Note
- GST Purchase (This is a custom voucher type)
- GST Sales (This is a custom voucher type)
- Proforma Invoice (This is a custom voucher type)

**Comment by adityahase** [comment]
1. We have decided not to handle vouchers affecting inventory for the time being. If you wish to contribute, we are more than happy to collaborate with you.

2. There is no way to handle Custom Vouchers without complicating the implementation.

**Comment by adityahase** [comment]
https://github.com/frappe/erpnext/pull/18430
