### ISSUE TITLE
BUG: Item Pricing Rules + POS Bugs

### ISSUE THREAD

**Issue by ablishek** [frappe/erpnext#17488]
ERPNext: v11.1.24 (master)
Frappe Framework: v11.1.26 (master)
there are few urgent bugs that require attention:

**Pricing Rule**: On All Product Category, any sale of 2 or more gets a discount. My intention is to give any customer a 10% discount for buying more than one item, not buying two of the same item.

**Case**: I am selling two products (two rows). Water Bottle and Chewing Gum.

According to the pricing rules, both items should have received a 10% discount.

**First Bug**: The discount is only applied to a particular row in the POS. So for example if I buy two Water Bottles, then I get 10% off. Since I have applied the discount on product group, the system should count the totals of that product group in the invoice, rather than on a particular row.

**Second Bug**: Lets say I go ahead an buy 2 water bottles, the system takes the discount up to 10%. But I can reduce the quantity and the discount remains. It should have disappeared once I went down. If a cashier figures this out, they can increase the quantity to the desired amount, and then reduce it giving the customer the discount.

Can this be fixed?

**Comment by dulhaver** [comment]
is this related to https://github.com/frappe/erpnext/issues/19010? @abhi-cognitivo
