### ISSUE TITLE
v11.1.23 - Salary Slip earning and deductions getting rounded

### ISSUE THREAD

**Issue by OneiricIT** [frappe/erpnext#17501]
ERPNext v11.1.23

Per https://discuss.erpnext.com/t/v11-1-23-now-rounding-all-salary-slip-formula-values/48631 and https://discuss.erpnext.com/t/salary-slip-rounding-in-v11/48623/2

in commit https://github.com/frappe/erpnext/commit/b890492dc07474dbee5d09fa9a9e42d40f74bf58 all formulas are being rounded. 

If rounding is a requirement, there should be a HR / payroll checkbox setting which would enable or disable rounding in Salary Slips - like 'Disable Rounded Total' in Global Defaults.

**Comment by lasalesi** [comment]
+1 
I agree, normally, decimal places are required and should not be rounded.

**Comment by OneiricIT** [comment]
looks like fixed in recent commit
