### ISSUE TITLE
bug: bank entry incorrect for salary slip with loan repayment

### ISSUE THREAD

**Issue by jigneshpshah** [frappe/erpnext#17504]
**Environment :** 
ERPNext: v11.1.25 (master)
Frappe Framework: v11.1.26 (master)

**Steps :** 
1) Create Loan with Repay from Salary Slip for any Empployee
2) Create Payroll Entry , Submit Salary Slip from Payroll Entry 
3) Payroll Payable JV as below gets created

![image](https://user-images.githubusercontent.com/4900815/57221942-8a1d0c00-701e-11e9-8171-ac14595b572e.png)

4) Make Bank Entry from Payroll Entry , Bank  Entry creates Journal Entry in draft stage with incorrect Payroll Payable amount as below

![image](https://user-images.githubusercontent.com/4900815/57221979-9ef99f80-701e-11e9-9f24-0e20fda2ff39.png)

**Expected Behavior** 
For Bank  Entry via Payroll Entry the Payroll Payable and the Bank/Cash amount should be as shown in the step 3

**Actual Behavior** 
The Payroll Payable amount doesn't considers the loan repayment.

**Comment by harshit-30** [comment]
Please create another issue if it is replicable after v13.10.
