### ISSUE TITLE
Issue email smtp

### ISSUE THREAD

**Issue by killmasta93** [frappe/erpnext#17516]
Hi,
I was wondering if someone could shed some light on the issue im having. Currently a did a fresh install of ERPNext but having issue with email. I put in the email settings but for some odd reason it wont save it. when i create a user it says please configure the email settings which i did when i check it did not save it. then after i try to save the email settings it starts to lagg and i get this in the logs

[2019-05-04 21:13:19 +0000] [1608] [CRITICAL] WORKER TIMEOUT (pid:2300)
[2019-05-04 21:13:19 +0000] [2300] [INFO] Worker exiting (pid: 2300)
[2019-05-04 21:13:19 +0000] [2376] [INFO] Booting worker with pid: 2376

and i check the logs i see this

 root@crm:/home/frappe/frappe-bench/logs# tail -f web.log 
 File "/home/frappe/frappe-bench/apps/frappe/frappe/email/smtp.py", line 86, in get_outgoing_email_account
  frappe.OutgoingEmailError)
File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 352, in throw
  msgprint(msg, raise_exception=exc, title=title, indicator='red')
   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 338, in msgprint
  _raise_exception()
 File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 311, in _raise_exception
  raise raise_exception(msg)
OutgoingEmailError: Please setup default Email Account from Setup > Email > Email Account

I then try to create email domain and keeps just showing the example.com
as i checked the logs adn found this too

`00:00:23 Result is kept for 500 seconds
00:00:23 short: frappe.utils.background_jobs.execute_job(event=u'daily', is_async=True, job_name=u'erpnext.crm.doctype.contract.contract.update_status_for_contracts', kwargs={}, method=u'erpnext.crm.doctype.contract.contract.update_status_for_contracts', site=u'site1.local', user=u'Administrator') (3d3808f0-2ad6-40a9-a830-14d1ebaa4571)
00:00:23 short: Job OK (3d3808f0-2ad6-40a9-a830-14d1ebaa4571)
00:00:23 Result is kept for 500 seconds
00:00:23 short: frappe.utils.background_jobs.execute_job(event=u'daily', is_async=True, job_name=u'erpnext.projects.doctype.project.project.update_project_sales_billing', kwargs={}, method=u'erpnext.projects.doctype.project.project.update_project_sales_billing', site=u'site1.local', user=u'Administrator') (01851506-f3a3-4a5c-85d8-16fa91f8c00d)
00:00:23 short: Job OK (01851506-f3a3-4a5c-85d8-16fa91f8c00d)
00:00:23 Result is kept for 500 seconds
00:00:23 short: frappe.utils.background_jobs.execute_job(event=u'daily', is_async=True, job_name=u'erpnext.projects.doctype.project.project.send_project_status_email_to_users', kwargs={}, method=u'erpnext.projects.doctype.project.project.send_project_status_email_to_users', site=u'site1.local', user=u'Administrator') (f00cd5d2-e4db-41e0-ab58-4de5c542090f)
00:00:23 short: Job OK (f00cd5d2-e4db-41e0-ab58-4de5c542090f)
00:00:23 Result is kept for 500 seconds
`

![Screenshot at 2019-05-08 00-02-23](https://user-images.githubusercontent.com/13953629/57350715-c33fa400-7124-11e9-9b2f-f49846dece01.png)

![Screenshot at 2019-05-04 20-10-52](https://user-images.githubusercontent.com/13953629/57350510-f3d30e00-7123-11e9-81ea-f2e1aa44efbf.png)
![Screenshot at 2019-05-04 20-21-14](https://user-images.githubusercontent.com/13953629/57350511-f46ba480-7123-11e9-8626-a5d273cd373e.png)
![Screenshot at 2019-05-04 20-22-28](https://user-images.githubusercontent.com/13953629/57350512-f46ba480-7123-11e9-985c-2800221279a3.png)

**Comment by killmasta93** [comment]
solved it was an issue of the firewall

**Comment by leggettc18** [comment]
Care to clarify what issue exactly? I'm running into a similar issue now and can't seem to find it.
