### ISSUE TITLE
Software Inventory

### ISSUE THREAD

**Issue by prashantbelvalkar** [frappe/erpnext#17527]
can i directly move the software inventory in child entity.
as i am testing i am unable to move software inventory in child entity where as i am able to move computer inventory to child entity.

**Comment by kennethsequeira** [comment]
@prashantbelvalkar please post functional queries on the forum: https://discuss.erpnext.com.

GitHub is used to track bugs and feature requests. On the forum, you will have access to users from around the world who can help you with the scenario. Also, do elaborate your query more so others can assist you accordingly.
