### ISSUE TITLE
[Bug] Currency symbol not correct in Exchange Rate Revaluation table

### ISSUE THREAD

**Issue by dufani1** [frappe/erpnext#17525]
Hiiii
ERPNext V 11.1.28
I noted that the currency symbol not correct in Exchange Rate Revaluation table. Please see below:

![rong sonpol](https://user-images.githubusercontent.com/23026263/57374047-40593080-719a-11e9-8ec7-d9fcface2dcb.png)

**Comment by dj12djdjs** [comment]
Closing as this was in version-11 and is now documented in version-13

https://github.com/frappe/erpnext/issues/31901
