### ISSUE TITLE
Pricing Rules are not queried correctly after removing 'customer' and adding 'party_name' in Quotation

### ISSUE THREAD

**Issue by mnour** [frappe/erpnext#17547]
Hi

  On our production environment we used to work with version 11.1.21, and after upgrading to version 11.1.25, we noticed that all of our pricing rules are not working correctly at all.

After digging deep we found that the main issue behind this is the removal of 'customer' field and replacing it with 'party_name' for doctype Quotation.

This affected the query constructed in 'erpnext.accounts.doctype.pricing_rule.pricing_rule' method 'get_pricing_rules', there the fields checks to add the relevant query part(s) are based on the availability of 'customer' field.

There are two places that needed to be fixed:

1. JavaScript Code: Namely 'erpnext/public/js/controllers/transaction.js', which has been fixed by ERP Next team and it has published in a new release, namely the latest release of ERP Next v11.1.28

2. Python/Backend Code: That part was still not working in our case, cause we are using ERP Next from both UI Client and via its APIs, and the APIs part was still not working. After yet another deep digging and remote debugging we found the issue and we will issue a PR.

Hope the ERP Next team takes a look at the PR, review it as soon as they can, and include it in another release.

Thanks

**Comment by nabinhait** [comment]
Fixed via https://github.com/frappe/erpnext/pull/17760
