### ISSUE TITLE
Bug - Auto repeat

### ISSUE THREAD

**Issue by TetraComSA** [frappe/erpnext#17557]
teraksa.erpnext.com
Dears,

While creating new Auto Repeat, the schedule not showing after saving/submitting...!! Please fix

<img width="1171" alt="Screen Shot 2019-05-10 at 2 04 00 PM" src="https://user-images.githubusercontent.com/33566237/57523058-a07fdc00-732c-11e9-944d-d272e60f03f3.png">

**Comment by scmmishra** [comment]
You need to submit the document to view the schedule.

**Comment by kennethsequeira** [comment]
@TetraComSA 

You need to submit the document for the schedule to be generated.

The schedule is generated based on the date of submission:

![image](https://user-images.githubusercontent.com/33246109/57601247-9a326f80-7579-11e9-8f31-e2068f828c04.png)

Kindly confirm the same.
