### ISSUE TITLE
Webshop should not require address

### ISSUE THREAD

**Issue by rasos** [frappe/erpnext#17559]
In webshops with virtual goods a delivery address does not make sense. Also most clients do not want to reveal a billing address and a phone number, which is currently required. This is a GDPR issue. 

I suggest to remove the mandatory address dialog in the webshop. Customers still are able to enter it.

**Comment by rasos** [comment]
Could we get this merged into ERPnext 12? @rmehta

**Comment by rmehta** [comment]
If you can send a correct fix with test coverage.

**Comment by rasos** [comment]
We patch it manually after each upgrade and it works fine, tested.

I don't think it requires a setting, as the webshop order page always offers a dialogue to enter an address. Deleting lines 58+59 in cart.py simply does not make entering an address field mandatory.
