### ISSUE TITLE
Website Product links

### ISSUE THREAD

**Issue by amitsaxena01** [frappe/erpnext#17560]
In Version 12, for a website example.com  having an item group with route /products/ig1 and an item with route /products/ig1/item1.
If we goto the product listing for an item group , example.com/products/ig1,  it display the items there. On clicking the link to product on this page sat item1, url used is  example.com/products/ig1/products/ig1/item1 instead of example.com/products/ig1/item1. As a result a Page on Available error is shown.

**Comment by gmplab** [comment]
#17916
