### ISSUE TITLE
Education : Student Login

### ISSUE THREAD

**Issue by atharvaunde59** [frappe/erpnext#17564]
Hello @ERPNext,
I have a doubt!
I deployed the latest ERPNext Educational Module. From the dashboard, I added a student.
Now I want to give login access to the student to check his performance and attendance. How to do it? as am unable to find any way to do so.
In setup>user I added a user with student role (email id in user and student info is same) now being able to log in but can't see any information.
Any help will be appreciated!﻿

**Comment by kennethsequeira** [comment]
@atharvaunde59 would be best to post this question on the forums: https://discuss.erpnext.com.

We use Github for tracking bugs and feature requests.

**Comment by Bwengu** [comment]
Can we have a feature where a student can be able to access the system to check the following;
1. Academic progress
2. fees payments and balances
3. make appeals (when have issues of grades etc)
4. full personal profile  or details (registration number, enrollment date, programe enrolled
5. API dashboard 

If we have a developer willing to take this as a freelancer, I am willing to sponsor him/her
Thank you.
