### ISSUE TITLE
bug: inter-company invoice warehouse validation error

### ISSUE THREAD

**Issue by jigneshpshah** [frappe/erpnext#17588]
#### Environment

ERPNext: v11.1.28 (master)
Frappe Framework: v11.1.27 (master)

#### Steps
 1) Setup Inter company as explained [here ](https://erpnext.com/docs/user/manual/en/accounts/inter-company-invoices)

![Inter Company Transaction](https://user-images.githubusercontent.com/4900815/57641042-9c281d00-75d1-11e9-9330-0a270a76bc89.jpg)

2) Create Sales Invoice  with update stock  = true and submit

3) Make > Inter Company Invoice , it leads to the above error message

#### More Info :
As explained in the image , Apple is selling iPhone from its Store-AP to Store-iS of iStore , but somehow the above validation message pops-up , after step-2. (Make -> Inter Company Invoice).

It seems the receiving (accepted) warehouse [Store-iS] of Purchase Invoice of Company iStore,  is by 
mistake set to the Source Warehouse [Store-AP] of Sales Invoice of Company Apple, which is incorrect.

### Expected Behavior : 
It should **not** copy the Source Warehouse of Sales Invoice to the Accepted Warehouse of Purchase Invoice.

**Comment by harshit-30** [comment]
Please create another issue if it is replicable after v13.10.
