### ISSUE TITLE
[Bug] Preparing Report progress bar and required filters

### ISSUE THREAD

**Issue by Don-Leopardo** [frappe/erpnext#17584]
There is an error when a report has required filters empty by default: the Preparing Report progress bar pops up anyway and when the progress bar finishes it does not close itself.
Gif:
![preparing](https://user-images.githubusercontent.com/46027152/57622324-b6c3ad00-7563-11e9-8e2a-1895ff907863.gif)

**Comment by SonicCodes** [comment]
I think you should catch the error and close the progress based on your needs.
