### ISSUE TITLE
I receive the same error in Bitnami Erpnext installation on azure

### ISSUE THREAD

**Issue by roma131313** [frappe/erpnext#17614]
Hi! I receive the below error log. Also for a period of time erpnext server link was showing a internal 500 error. I had to restart the VM. Can you please advise if I have to do something to stop these error logs?

	
Title	
frappe.limits.update_site_usage

Error	

{'event': u'hourly', 'retry': 0, 'log': <function log at 0x7f8afba6c7d0>, 'site': u'erpnext', 'job_name': u'frappe.limits.update_site_usage', 'method_name': u'frappe.limits.update_site_usage', 'method': <function update_site_usage at 0x7f8afc0fd1b8>, 'user': u'Administrator', 'kwargs': {}, 'is_async': True}
Traceback (most recent call last):
  File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 103, in execute_job
    method(**kwargs)
  File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/limits.py", line 243, in update_site_usage
    with open(os.path.join(frappe.get_site_path(), 'site_data.json'), 'w') as outfile:
IOError: [Errno 13] Permission denied: u'./erpnext/site_data.json'

**Comment by clarkejj** [comment]
Please post this here https://discuss.erpnext.com/

**Comment by kennethsequeira** [comment]
@roma131313 please post all installation related issues in the forum as requested.
