### ISSUE TITLE
"Purchase Receipt" marked as 'open' in Supplier Dashboard even if it is completed

### ISSUE THREAD

**Issue by vrms** [frappe/erpnext#17626]
When a Purchase Order not has been 'closed' with all required documents (Invoice, Payment, Receipt) it shows up with Red Dots in several location of ERPNext

This red dot should disappear whether the documents are submitted to the system and likewise indicate that this is "done"

In the Suppliers Dashboard however this (disappearing of the red dot) does not work for "Purchase Receipt" as shown in the screenshots below. 

- The same behavior happens in the "Purchase Order" & "Supplier" Dashboards.
- Neither clearing the browser cache, nor running `bench clear-cache` or `bench clear-website-cache` make the red dot go away.
- I see this as a reoccurring behavior, so I believe it is a bug and not a single hiccup

### Supplier Dashboard
![image](https://user-images.githubusercontent.com/7608112/57830484-90478100-77b2-11e9-9eaf-a6d58b766d58.png)

![RCT-02](https://user-images.githubusercontent.com/7608112/57830513-a5bcab00-77b2-11e9-8450-0523337746aa.PNG)

**Comment by deepeshgarg007** [comment]
@vrms Closing this issue. If the issue still persists in the latest version-13 or above then please reopen a new issue
