### ISSUE TITLE
Depends on tasks Issue 

### ISSUE THREAD

**Issue by AkramMutaher** [frappe/erpnext#17647]
There an issue in tasks when adding a child task automatically add it in depends on task (hidden field) in the parent task and this column type in database data type and maximum character 140 

so when adding more than 8 child tasks I get an error message 

> Task TASK-2019-00244: 'Depends on Tasks' (TASK-2019-00245,TASK-2019-00246,TASK-2019-00247,TASK-2019-00248,TASK-2019-00249,TASK-2019-00250,TASK-2019-00251,TASK-2019-00252,TASK-2019-00253,) will get truncated, as max characters allowed is 140

please make that field type as small text or text to accept more than 140 characters

**Comment by AkramMutaher** [comment]
![Capture](https://user-images.githubusercontent.com/45880595/57888777-c250f580-783b-11e9-9454-336656c01f4e.JPG)

**Comment by FinForce** [comment]
You can go into Customise form >> Task Depends On table >> Increase Length. The 140 char limit is a configurable thing.

![image](https://user-images.githubusercontent.com/31281816/57965210-e6f1be00-795e-11e9-94cc-904c42d53271.png)

**Comment by AkramMutaher** [comment]
> You can go into Customise form >> Task Depends On table >> Increase Length. The 140 char limit is a configurable thing.
> 
> ![image](https://user-images.githubusercontent.com/31281816/57965210-e6f1be00-795e-11e9-94cc-904c42d53271.png)

thanks, it's solved
