### ISSUE TITLE
Delivery Note - bug in status Filter

### ISSUE THREAD

**Issue by adfluidics** [frappe/erpnext#17654]
Hi,

I've got a delivery note that is marked as completed, but that continues to show when I filter "Status not in Completed". I also have a notification that shows on my desktop, probably linked to this same problematic delivery note.

![image](https://user-images.githubusercontent.com/47985186/57914150-682d5000-788e-11e9-99af-4ad9c47f587f.png)

Thanks for correcting this bug, it is quite frustrating!

ERPNext: v11.1.30 (master)
ERPNext Support: v0.0.1 (master)
Frappe Framework: v11.1.28 (master)

**Comment by clarkejj** [comment]
Be sure to post this issue on discuss.erpnext.com to raise notice.

Link to discuss and this issue for folks add comments plus a fix contribution.

**Comment by clarkejj** [comment]
Here's a similar Purchase Receipt case https://discuss.erpnext.com/t/purchase-receipt-has-notification-but-all-receipts-are-completed/48531/16
