### ISSUE TITLE
System always stop work even pending when in warehouse tree.

### ISSUE THREAD

**Issue by chiangfive** [frappe/erpnext#17689]
Hi support team,
When our team is edit in the warehouse tree, our system always stop and the whole system will pending for few minutes.. would you please check this is might be a bug?

**Comment by kennethsequeira** [comment]
@chiangfive you might want to post this on the user forum first to ascertain if it is a bug or not: https://discuss.erpnext.com

Also do post your frappe and erpnext versions. A gif or screenshots of what is the issue might help others in assisting.
