### ISSUE TITLE
[BUG] Notification Issue on Purchase Receipt

### ISSUE THREAD

**Issue by JunkyardCat** [frappe/erpnext#17683]
Purchase receipt has notification but all receipts are completed
![purchase receipt](https://user-images.githubusercontent.com/22941307/58024769-840e4b80-7b45-11e9-8fe5-de55229da288.jpg)

im already at the latest, cleared cache then logged out then in and still nothing

**Comment by clarkejj** [comment]
https://discuss.erpnext.com/t/purchase-receipt-has-notification-but-all-receipts-are-completed/48531

**Comment by ankush** [comment]
This should get fixed with  https://github.com/frappe/erpnext/pull/25109
