### ISSUE TITLE
[Feature Request] IBAN and BIC as bank details

### ISSUE THREAD

**Issue by barredterra** [frappe/erpnext#17685]
In Europe, everyone uses the IBAN and, optionally, the SWIFT-BIC for Bank payments. (Instead of account number, etc.)

> As of February 1, 2016, the IBAN replaced the existing national account numbers for transfers in the EU.

Therefore,

- [x] SWIFT-BIC should be a field of DocType `Bank`
- [x] `Bank Account` should not rely on _GL Account_ as a mandatory field -> Checkbox "Is Company Account"
- [x] It should be possible to hide all bank details except IBAN for European entities -> Customize Form

Further, 

- [x] `Customer` and `Supplier` should link to `Bank Account`

```html
<p>DE68<span class="ml-1">2105</span><span class="ml-1">0170</span><span class="ml-1">0012</span><span class="ml-1">3456</span><span class="ml-1">78</span></p>
```
---

![IBAN usage](https://upload.wikimedia.org/wikipedia/commons/c/cd/IBANMap-World6.svg)
IBAN Usage, blue = _participating_ ([CC-BY-SA 3.0](https://creativecommons.org/licenses/by-sa/3.0), by [Gfis](https://de.wikipedia.org/wiki/Benutzer:Gfis))

**Comment by wojosc** [comment]
Hi @barredterra ,

these two points can be marked as solved
![grafik](https://user-images.githubusercontent.com/22279621/131254112-2c427ace-934f-4754-b4cf-8a993ff4d123.png)

![grafik](https://user-images.githubusercontent.com/22279621/131254132-40b35861-de9a-48e2-9431-b7747c9af0ad.png)

![grafik](https://user-images.githubusercontent.com/22279621/131254151-bab4355d-5377-4d59-8f27-9f2347ab7431.png)

![grafik](https://user-images.githubusercontent.com/22279621/131254172-42fe109d-3c09-43f2-a6ac-edb8ff9d1e22.png)

Grüße

**Comment by wojosc** [comment]
keep open

**Comment by barredterra** [comment]
Created separate issues for #35721 and #35722
