### ISSUE TITLE
[Bug] In words not updating when updating the items qty after submit

### ISSUE THREAD

**Issue by JunkyardCat** [frappe/erpnext#17695]
using erpnext v11.1.31
updating the qty of the item PO after i have submitted it doesnt seem to update the In words amount. I have already reload and logged out and logged in

![firefox_2019-05-22_12-43-44](https://user-images.githubusercontent.com/22941307/58147950-57fee180-7c8f-11e9-9324-70ea7f62857f.jpg)

**Comment by clarkejj** [comment]
https://discuss.erpnext.com/t/in-words-not-updating-when-updating-qty-after-submitted/49191/3

**Comment by Himanshu-Gurjar** [comment]
Any update on this ?

**Comment by ankush** [comment]
This is fixed in v12 and v13.

Ref: https://github.com/frappe/erpnext/pull/24602/
