### ISSUE TITLE
[BUG] General Ledger Group by Voucher not ordering by posting_date

### ISSUE THREAD

**Issue by Don-Leopardo** [frappe/erpnext#17707]
### Issue:
In the general ledger, when you use the option "Group by Voucher", the entries aren't ordered by posting_date.
![Captura de pantalla 2019-05-22 a la(s) 15 03 06](https://user-images.githubusercontent.com/46027152/58197488-c305e380-7ca2-11e9-9cea-6867bad2adf4.png)

### Tracking the error:
To track this error I analiced ​​the changes suffered by the `gl_entries` and the` gle_map` variables in the function `get_data_with_opening_closing`.
https://github.com/frappe/erpnext/blob/daa8db4d9584a6e6930e854ba00bd24af2b39b87/erpnext/accounts/report/general_ledger/general_ledger.py#L200-L207
The result of the analysis was that the `gl_entries` variable has the ordered data as espected. And the method `initialize_gle_map` is the one that deorders it. This method is the one that reagroup the entries by `voucher_no` but when doing so it overwrites the order gived by the SQL query.
https://github.com/frappe/erpnext/blob/daa8db4d9584a6e6930e854ba00bd24af2b39b87/erpnext/accounts/report/general_ledger/general_ledger.py#L254-L270

### Cheap solution:
The structure of `gle_map` is this:
```
{

    voucher_no: {
        'entries': list_of_entry_dicts,
        'totals': list_of_totals
        },
    ...
    ...
}
```
So we can add the smallest `posting_date` of the entries list to the voucher dict to have something like this:
```
{
    voucher_no: {
        'entries': list_of_entry_dicts,
        'totals': list_of_totals,
        'posting_date': smallest_posting_date
        },
    ...
    ...
}
```
And then proceed to reorder it by `posting_date`.

This is a cheap solution because it consists in a lot of `if` and `for` statements to determine if it's the "Group by Voucher" case or not. I think that this can be resolved in other way, maybe reestructuring the original query to include a `group by`.

**Comment by Don-Leopardo** [comment]
@SaiFi0102 I can see that you know better about this (#15169). Can you provide some information or validate the bug report?

**Comment by SaiFi0102** [comment]
I think I faced this problem and solved it by replacing a normal dict `{}` with `OrderedDict()` here https://github.com/frappe/erpnext/blob/daa8db4d9584a6e6930e854ba00bd24af2b39b87/erpnext/accounts/report/general_ledger/general_ledger.py#L264

**Comment by Don-Leopardo** [comment]
That's going to order by voucher_no and not posting_date

**Comment by SaiFi0102** [comment]
That's going to order by (voucher_no, posting_date) both, give it a try

**Comment by Don-Leopardo** [comment]
Yes, my bad. I was thinking in a dict ordered by its key name. Is it ok to make a PR of this change?

**Comment by SaiFi0102** [comment]
Sure go ahead
