### ISSUE TITLE
Customer item code not showing in sales order

### ISSUE THREAD

**Issue by fotocreaman** [frappe/erpnext#17711]
When I create a sales order the customer item code is not set for an item. In quotation it is working.

I'm using 
ERPNext: v11.1.32 (master)

Frappe Framework: v11.1.30 (master)

Full Size View: v2.0.0 (master)

Poll: v0.0.1 (master)

**Comment by deepeshgarg007** [comment]
@fotocreaman   Closing this issue. If the issue still persists in the latest version-13 or above then please reopen a new issue with proper steps to replicate
