### ISSUE TITLE
Shopify integration failed

### ISSUE THREAD

**Issue by JavierPascual** [frappe/erpnext#17718]
With all fields configured, our ERPNext is not syncing with Shopify when sells occurs. There is some internal bug?

**Comment by kennethsequeira** [comment]
@JavierPascual have you checked the Shopify Logs?

**Comment by JavierPascual** [comment]
No, I don't. Where can I see it? Thanks!

**Comment by kennethsequeira** [comment]
@JavierPascual check for **Shopify Log** in your account:

![image](https://user-images.githubusercontent.com/33246109/58463794-25069300-8152-11e9-9b60-7e2b1de0e689.png)

All sync logs are captured here. This should help you to debug the issue. 

Would be best that you post the issue on discuss so forum members can guide you to solve the issue as well: https://discuss.erpnext.com

**Comment by kennethsequeira** [comment]
Closing this issue as there was no follow leading to tag it as a bug.
