### ISSUE TITLE
[CRITICAL] : Leave Without Pay not Working  ERPNext: v11.1.30 (master) to ERPNext v11.1.33 (Master)

### ISSUE THREAD

**Issue by sammish** [frappe/erpnext#17721]
After Updation Leave without pay not working . Please fix 

![image](https://user-images.githubusercontent.com/12432802/58248807-d0d06d00-7d65-11e9-8b03-6effd42b6b8f.png)

![image](https://user-images.githubusercontent.com/12432802/58248863-f2c9ef80-7d65-11e9-9541-9ab42edbe7c0.png)

![image](https://user-images.githubusercontent.com/12432802/58249032-71bf2800-7d66-11e9-9b87-e70503d9d3d3.png)

**Comment by nabinhait** [comment]
@sammish which branch you are using?

**Comment by sammish** [comment]
@nabinhait master

**Comment by sammish** [comment]
@umairsy @nabinhait Please release patch. currently very critical our environment because month of end.
