### ISSUE TITLE
[Feature Request] Allow different Levels in BOM Explosion

### ISSUE THREAD

**Issue by ophl55** [frappe/erpnext#17738]
**Requirement:**
Possibility to use different, defined levels in BOM explosion. 

**Simplified example BOM:**

![image](https://user-images.githubusercontent.com/5788712/58338564-3bf27000-7e48-11e9-83ea-9a2f98121525.png)

**Scenario:**
In this example the BOM of the product contains the sub-assemblies _Item 1_ and _Item 2_.
To manufacture the product _Item 1_ (1st level) shall be consumed. Item 2 shall be transparent so that _Item 2.1_, _Item 2.2_ and _Item 2.3_ (2nd level) are consumed directly. 

**Problem:**
Currently the system only allows to use the first level or the last level (called multi-level). But the last level is not always what you need e.g. if you have multiple stages of subcontracting. The production planning should allow a higher granuality in defining the level resolution of boms. 

Right now the production planning only offers two ways of resolution:

1. Use 1st level: _Item 1_ and _Item 2_
2. Use multi-level: _Item 1.1.1_, _Item 1.1.2_, _Item 1.2_, _Item 1.3_, _Item 2.1_, _Item 2.2_, _Item 2.3_

**Possible Solution:**
Define a check-box in the BOM that indicates whether the BOM can be exploded or not. If the BOM does not allow further explosion the item should be treated as a leaf. The resolution should stop in that case. 

In the scenario mentioned above, _Item 1_ would not allow further explosion.
The explosion stops at _Item 1_ while _Item 2_ is still transparent.

![image](https://user-images.githubusercontent.com/5788712/58338576-43197e00-7e48-11e9-8b81-d3bed24ae9e7.png)

**Comment by ophl55** [comment]
The feature request is also discussed here: 

https://discuss.erpnext.com/t/feature-request-allow-different-levels-in-bom-explosion/49183

**Comment by rkr00t** [comment]
@karthikeyan5 @umairsy 
Can anyone review this Feature Request

**Comment by cosimot** [comment]
Hello @ophl55 , your scenario is not correct. 
The correct way to get what you need is making a second BOM (which is allowed) where at 1st level you have Item 1, Item 2.1, 2.2 and 2.3.
When you make purchase or production order you choose the BOM you want.
We do this this way and for us it works great.

**Comment by ophl55** [comment]
Hello @cosimot . Your solution sound like a pragmatic workaround for certain use cases. But in my opinion it is still a workaround as you are forced to maintain the same structure two times eventhough all the required information exist already in one BOM (unique source of truth).

In my use case I have around 2.000 variants. The BOM of each variant has around five levels. The first level consists of 10 BOMS. Unfortunately your workaround is not a good solution for my use case.

**Comment by rcapuz** [comment]
I have the same use case as @ophl55 . @karthikeyan5 @umairsy have you check this Feature request?

**Comment by bcornwellmott** [comment]
This feature currently exists (or at least used to in v10), so long as the Default Material Request type for the part has been set. If you change the default material request type to Production vs Purchased. Then you just need to process the production material requests for those sub-assemblies to generate any lower level purchased components you'll need.

**Comment by ophl55** [comment]
@bcornwellmott Thank you for your reply. I tried to test what you have described but I couldn't get it to work as desired. Perhaps I misunderstood so maybe you can explain the feature again using the example above? 

To remember: I don't want to process a lot of material transformations manually. I want to define that some BOMs are transparent and some are not.

**current feature 1: allow multi-level (not matching my use case)**

![image](https://user-images.githubusercontent.com/5788712/59146595-936c1080-89f0-11e9-8932-e61ff1abb322.png)


**current feature 2: allow first level only (not matching my use case, because too many manual bookings are required)**

![image](https://user-images.githubusercontent.com/5788712/59146624-d9c16f80-89f0-11e9-80c5-03e5b18e4bed.png)


**what I need:**

![image](https://user-images.githubusercontent.com/5788712/59146632-f65da780-89f0-11e9-9922-1ca6d96e9515.png)

**Comment by cosimot** [comment]
@ophl55 In terms of manufacturing bypassing a level is not correct.  I have seen your scenario but still can’t get why you need this feature. Why would you need a transparent level if you can make a specific bom? Because you make some items in a way and others in another way? So same item made in 2 ways?

**Comment by ophl55** [comment]
@cosimot as i said i have a lot of variants with multiple levels. I use some of the sub-assemblies for encapsulation. They are kind of pseudo sub-assemblies that work as a container for other items. i could use these items direcly in the BOM of the product. But it is much easier to maintain the whole structure if some items are encapsulated in container BOMs.

For example: I have 2.000 variants of the product that use the BOM of Item 2 which is used as a container. If I now have to update items in the BOM of Item 2 I can just update the BOM of Item 2 and use the BOM Update Tool to update all of the 2.000 product variants. That is very easy for me to realize.

In contrary if i don't use Item 2 as a container and instead I have Item 2.1, Item 2.2 and Item 2.3 directly in the BOM of each variant, than I have to update the BOM of all 2.000 variants "manually". That is not easy to realize.

As i said your workaround is good in certain use cases, especially if the complexity of the BOMs is low. In my use case there are more than a hundred of items used for only one variant distributed over multiple levels. 

I think that the scenario i have described is typical for manufacturing businesses. But maybe I am getting something wrong and there is a better way to get the job done in ERPNext.

I hope I was able to answer your question.

**Comment by cosimot** [comment]
I think i start to understand, the “containers” are for items that are in common for the variants?
Bom’s levels are used differently in all the ERPs, every level is a manufacturing step, so if you need a way to handle variant BOM I also have same issue so I am interested in a customization as well. There might be a different approach we could copy from another ERP. Did I understand well?

**Comment by ophl55** [comment]
@cosimot yes exactly. I'm using the "containers" in all variants.

**Comment by cosimot** [comment]
@ophl55 and outside the containers you place what is not common for all variants?

**Comment by ophl55** [comment]
@cosimot yes exactly.

**Comment by djpalshikar** [comment]
@ophl55 if granularity is what you want just make sure that your subassembly BOMs are not set as default. In that case BOM document gives you the option to explode the BOM.

**Comment by LaureanoBlonsky** [comment]
@ophl55 I had the same problem as you and resolved it like @bcornwellmott said:
> This feature currently exists (or at least used to in v10), so long as the Default Material Request type for the part has been set. If you change the default material request type to Production vs Purchased. Then you just need to process the production material requests for those sub-assemblies to generate any lower level purchased components you'll need.

I explain if someone find himself in the same situation:
In your example, you need to "stop" the cascading on Item1
So you go the the Item1 master and on the category "Inventory" you change "Default Material Request Type" to "Manufacture"
![Screenshot (80)](https://user-images.githubusercontent.com/7193076/78509544-022b0f00-7765-11ea-88aa-a1c6081b3410.png)

I didn't understand what @djpalshikar suggested, If its making an Item without a default BOM, I couldn't make it. If an Item has one or more BOMs active, it selects one to be the default and you cant edit it. (V12). Anyway, with the other solution above Im happy! It is a pity that the documentation doesn't explain these things (maybe it does and I missed it)

**Comment by cosimot** [comment]
but "default material request" is for making automatic Work Orders or Purchase Orders. In fact I made all the tests myself and it doesn't stop cascading.
The idea is very good but can't replicate what @ophl55 say. Can you by chance give us a step by step guide on what you do?
<img width="356" alt="Schermata 2020-04-06 alle 12 07 12" src="https://user-images.githubusercontent.com/26325987/78547304-29361f00-77ff-11ea-8e94-0a9d9c3b5603.png">

<img width="930" alt="Schermata 2020-04-06 alle 12 03 20" src="https://user-images.githubusercontent.com/26325987/78547166-ee33eb80-77fe-11ea-9828-76ff13369283.png">
<img width="1098" alt="Schermata 2020-04-06 alle 12 02 56" src="https://user-images.githubusercontent.com/26325987/78547172-f0964580-77fe-11ea-96a5-342df41c1d3e.png">

**Comment by ophl55** [comment]
@LaureanoBlonsky @cosimot thanks for the info! I will check it asap.

**Comment by djpalshikar** [comment]
@LaureanoBlonsky you could create BOM without making it default till about a couple of months back. However some of the new versions have made it compulsory for at least one BOM to be set as default.

I have discussed this issue  @rohitwaghchaure, he may come up with a long term solution. In the meantime I am working around the validation:

1. Created a "Server Script" which bypasses the default validation 
It can let you set the "is_default" field to 0.
2020-04-06 Set BOM Default](https://user-images.githubusercontent.com/23133635/78559872-c2caf400-7832-11ea-90f9-128fc7bbf6b4.png)

2. The Server Script is an API which is being called through a python client. However you could also use some custom client script in BOM to call the above server script.

The above solution has worked fine with me.

**Comment by cosimot** [comment]
@rohitwaghchaure I think it is good if we can work on BOM for variants like I said some times in the past. It seemed a good idea also to @umairsy .
Many of us use a lot of variant and a solution to avoid making a BOM for each variant is useful I think.
I have used Odoo a lot and they have solved this very well. 
Basically the concept is the following.
If an Item has variants you could either make a specific BOM for a specific Variant, or you can make a master BOM valid for all variants. In the items of the BOM you can specify where these items goes.

![BOM Master Item](https://user-images.githubusercontent.com/26325987/78667448-37f10480-78d9-11ea-99e9-10d40789a7f2.jpg)

**Comment by LaureanoBlonsky** [comment]
> but "default material request" is for making automatic Work Orders or Purchase Orders. In fact I made all the tests myself and it doesn't stop cascading.
> The idea is very good but can't replicate what @ophl55 say. Can you by chance give us a step by step guide on what you do?

Hey, look... I have a working example. But now trying it again with better names, just to show you, it doesnt work. **But fortunately I still have the one that works**... Look at it, to see If we can se whats happening... seems like a bug? (images are yellow because I use a red filter at night :) )

I have a testing Item "PedidoCS1_1" with its BOM:
![BOM_Pedido](https://user-images.githubusercontent.com/7193076/78731244-8b814380-7915-11ea-9bf2-3714e78ee7b0.png)
The thing is this: The highlighted Item "PruebaBOM_sinDefault" **DOES HAVE A BOM with items**...

In the BOM Tree, If I select it:
![BOM_Default](https://user-images.githubusercontent.com/7193076/78732191-51657100-7918-11ea-8ef8-77ff38f86d4e.png)

In the list:
![BOM_List](https://user-images.githubusercontent.com/7193076/78731598-8b357800-7916-11ea-85a1-a05d28837a5d.png)

Inside the BOM:
![BOM_Pedido_Adentro](https://user-images.githubusercontent.com/7193076/78731352-def39180-7915-11ea-9b48-802c8fa1d7ce.png)

When I make a WorkOder with "Use Multi-Level BOM" checked:
![Pedido_WorkOrder](https://user-images.githubusercontent.com/7193076/78731496-47427300-7916-11ea-847f-138ba8343796.png)

You can see that doesnt cascade to the PruebaBOM_sinDefault items. But in the first image you see that even in the BOM Tree ERP thinks it has no child items... and the vertical lines of the graphic arent present too... that seems like a bug (no console errors).

This is the BOM Tree for the one i started for you. I setted "Manufacture" in **Item1.1** but acts differently than **PruebaBOM_sinDefault**  (cascade items in BOM Tree and in WorkOrder)
![BOM_Tree_2](https://user-images.githubusercontent.com/7193076/78731771-0139df00-7917-11ea-89f6-40cbe5fff98b.png)

What do you think?... I needed that feature too and I though we had it... Or Am I missing something?

**Comment by LaureanoBlonsky** [comment]
@cosimot  @ophl55  Okey... I figured it out. This is what happens:

If you create the parent **Parent Item BOM**, before creating the **Item Childs BOMs**, then if you add Child BOMs, the Parent doesn't get updated, so will keep thinking his child doesn't have BOMs. That is what I suppose happened in my "successful" first case.

So it has nothing to do with the "Default Material Request type". I think we can go with the workaround proposed by @djpalshikar 

Sorry if I made you waste your time...

**Comment by ophl55** [comment]
Hey guys.

I finally came up with a solution. Thanks to the workaround of @djpalshikar I had a good starting point. 

### Problem
I can confirm that the workaround of @djpalshikar helps to stop the BOM explosion in Work Orders. 
But there is one big drawback with that workaround concerning Purchase Orders for subcontracted items. Since you unset the default BOM for the item the system needs you to enter the BOM for each subcontracted item manually in the Purchase Order. That is just not practical.

### Solution
So what I have done is I added a flag called **Allow BOM explosion** in the **BOM Item** doctype. I extended **erpnext/manufacturing/doctype/bom/bom.py**  to check for that flag. 

If the flag is set to true the system acts as before and traverses to the BOM tree. 
The new functionality comes into play if the flag is false. In that case the module uses the item directly as if it were a leaf. 

Here is how it looks like for a submitted BOM:
![image](https://user-images.githubusercontent.com/5788712/93666681-6bd37700-fa80-11ea-9bb6-94595353824b.png)

And here the exploded items of the submitted BOM:
![image](https://user-images.githubusercontent.com/5788712/93666750-f7e59e80-fa80-11ea-954d-9fe2093b37fe.png)

Analog to the "Include Item in Manufacturing" I have also added a flag to the Item Master. While creating/changing a BOM in a first step the system looks up the value set in the Item Master, but you are free to change the value in the BOM Item child table afterwards.
![image](https://user-images.githubusercontent.com/5788712/93666826-662a6100-fa81-11ea-8fd1-9ba9ce47fea9.png)

### Example
For better comprehension let's imagine a realistic example. Let's have a look at the following BOM structure:
![image](https://user-images.githubusercontent.com/5788712/93666857-ab4e9300-fa81-11ea-95a8-5340e1e6fd90.png)

The **Product Variant** Item consists of two sub-assemblies. They are like containers and may be reused in other Product Variants. 
**Container 1** consists of **Raw Material 1** and **Subcontracted Item**. While doing the material tranfers for the work order I want to reduce the stock for **Subcontracted Item**. I don't want to reduce the stock of **Raw Material 2** and **Raw Material 3** since they get reduced during the processing of the purchase order.

So  I set the **Allow BOM Explosion** flag for the **Subcontracted Item** to 0. 

As you can see the exploded items of **Product Variant** is pretty much what I expect of the system to do:
![image](https://user-images.githubusercontent.com/5788712/93666954-9faf9c00-fa82-11ea-8b0f-fcd18bd7883c.png)

The Work Order generated using the Production Plan looks like this:
![image](https://user-images.githubusercontent.com/5788712/93666986-d1c0fe00-fa82-11ea-90af-9c0a5a8ade8f.png)

Note that I have checked the **Use Multi-Level-BOM** flag and still **Subcontracted Item** will be used instead of **Raw Material 2** and **Raw Material 3**.

**Comment by ophl55** [comment]
@LaureanoBlonsky @rkr00t @bcornwellmott @djpalshikar @szufisher 

What do you think about the solution? In my opinion it is pretty straight forward and the feature is badly required.
Maybe someone of frappé can have a look and check. If it's fine we can try to include it into the core. 

There are only a few lines of code to add and as far as I can see it there are no other side-effects. E.g. the BOM-Update Tool and Purchase Orders with Subcontracting are still working as expected...

**Comment by ophl55** [comment]
Another big benefit is that now information like planned, reserverd and projected qty are much more usable because they are now mapped to the actual items instead of "virtual containers".

**Comment by djpalshikar** [comment]
hi @ophl55, the suggest solution was supposed to be standard, @rohitwaghchaure from Frappe Tech is building this, however there may be some delay. It will worthwhile if you can take this up with him, he may be able to pull in your changes quickly.

**Comment by ophl55** [comment]
@rohitwaghchaure I've read the contribution guidelines. But I think I will need some guidance since it may be my first pull request for erpnext. Can we get in contact to discuss how to proceed with the feature request?

**Comment by sahil48** [comment]
Is there any update on this issue?

**Comment by ophl55** [comment]
I'm using my workaroung in a production system. I've never received any feedback from frappe so far.

**Comment by djpalshikar** [comment]
@ophl55 BOM Exploded Table is stored as a separate table, there is no use trying to control explosion dynamically .
There are two possible solutions -
- @rohitwaghchaure was going to add "Do not explode BOM checkbox" to the BOM Item table
- As another temporary workaround, you can add  a new checkbox "Default for subcontracting" the BOM for you subcontracted item. You can fetch this BOM based on a server side /client side script.
        
I have followed @rohitwaghchaure a couple of times, not sure if is working on it now

**Comment by ophl55** [comment]
> @ophl55 BOM Exploded Table is stored as a separate table, there is no use trying to control explosion dynamically .
> There are two possible solutions -

That is what my workaround is doing. The checkbox is for the BOM Item. The result is that the BOM Exploded Table is set accordingly. Further on the system works with the BOM Exploded table. No dynamic calculations for the BOM explosion.

**Comment by sahil48** [comment]
@rohitwaghchaure 

Do you have any feedback on this issue and work you may have done on this?
