### ISSUE TITLE
[CRITICAL] Login screen is without the login form

### ISSUE THREAD

**Issue by siddhpant** [frappe/erpnext#17735]
I switched to the develop branch from master, and after due procedures when I proceed to login, there's no login form.

![image](https://user-images.githubusercontent.com/25429745/58324984-1b291b00-7e46-11e9-93cc-846b1df31091.png)

The console has this error:
```
Uncaught ReferenceError: io is not defined
    at Object.init (frappe-web.min.js:1)
    at frappe-web.min.js:1
    at frappe-web.min.js:1
    at Array.forEach (<anonymous>)
    at Object.trigger_ready (frappe-web.min.js:1)
    at HTMLDocument.<anonymous> (frappe-web.min.js:1)
    at HTMLDocument.dispatch (jquery.min.js:3)
    at HTMLDocument.r.handle (jquery.min.js:3)
    at Object.trigger (jquery.min.js:4)
    at HTMLDocument.<anonymous> (jquery.min.js:4)
```
----

Firefox screenshot:
![image](https://user-images.githubusercontent.com/25429745/58324973-119fb300-7e46-11e9-9912-97f9c4161645.png)

The console shows the following error:
```
ReferenceError: io is not defined frappe-web.min.js:1:139691
    init http://localhost/assets/js/frappe-web.min.js:1
    Rollup http://localhost/assets/js/frappe-web.min.js:1
    trigger_ready http://localhost/assets/js/frappe-web.min.js:1
    forEach self-hosted:262
    trigger_ready http://localhost/assets/js/frappe-web.min.js:1
    Rollup http://localhost/assets/js/frappe-web.min.js:1
    jQuery 7
        dispatch
        handle
        trigger
        trigger
        each
        each
        trigger
    Rollup http://localhost/assets/js/frappe-web.min.js:1
    jQuery 4
        i
        fireWith
        ready
        J
```

**Comment by siddhpant** [comment]
Here's the apparent culprit:
![image](https://user-images.githubusercontent.com/25429745/58325441-5a0ba080-7e47-11e9-9be8-2a2ec062e39c.png)

**Comment by siddhpant** [comment]
Changing `io.connect` to `frappe.socketio.connect` fixes the problem for now, but please have a look at it. I can't see GSTR 3B and also some cards don't have anything written on them.

**Comment by africlouds** [comment]
Is there a permanent solution? Having the same issue today

**Comment by gmplab** [comment]
#16979 same issue.

**Comment by siddhpant** [comment]
@africlouds Change it and save. That's permanent enough for now.

**Comment by rmehta** [comment]
Please run `bench build` again.

**Comment by siddhpant** [comment]
Ok

**Comment by siddhpant** [comment]
Pulled the latest from branch, built. Issue resolved for me.

@africlouds , @gmplab please confirm so I can close this issue.

**Comment by siddhpant** [comment]
Closing due to lack of confirmation.
