### ISSUE TITLE
Default Supplier

### ISSUE THREAD

**Issue by brentglover** [frappe/erpnext#17731]
Installed Apps
ERPNext: v11.1.33 (master)
Frappe Framework: v11.1.30 (master)

Don't have the default supplier field any more under items/supplier details showing since the upgrade this morning.  Only show Delivered by DropShip and manufacturer.  Also cant see it there any more under customize item form.

Thanks
Brent

**Comment by f-9t9it** [comment]
It is available in Item defaults table. Kindly check before raising an issue.

There is a table.
![image](https://user-images.githubusercontent.com/39218579/58322696-68978f00-7e2a-11e9-8f05-108960ce082d.png)
![image](https://user-images.githubusercontent.com/39218579/58322724-7b11c880-7e2a-11e9-9dbf-e8b8e2be4e49.png)

You can make this field in list view .

**Comment by kennethsequeira** [comment]
@brentglover in V11, all defaults have been moved in the item default table.
