### ISSUE TITLE
Plan to release version 12

### ISSUE THREAD

**Issue by onlinebizsoft** [frappe/erpnext#17752]
I had some testing on version 12 and I must say it is much better than version 11. Not sure when it would be released?

**Comment by kennethsequeira** [comment]
@onlinebizsoft whenever a separate branch is created, the announcement would be made on the forum: https://discuss.erpnext.com

**Comment by onlinebizsoft** [comment]
@kennethsequeira I know but I mean there is any roadmap (estimation date) for the release?

**Comment by kennethsequeira** [comment]
@onlinebizsoft nothing concrete so far.
