### ISSUE TITLE
great framework but looks cluttered, minimise options?

### ISSUE THREAD

**Issue by voordev** [frappe/erpnext#17784]
Great framework but looks cluttered.
I want to use ERP next for simple CRM.

I see all kind of options in the menu for modules I don't even going to use.
This looks so cluttered! And the platform looks so promising. Im willing to convert even to a full paying account but not with all this clutter in place.

How to disable all kinds of menu options like 'manufacturing' 

I propose there will be a 'module' section and you can turn it on/off for every module.
Or is there a way to remove all this clutter differently?

Kind regards

**Comment by yashodhank** [comment]
@voordev Welcome and Thanks for your feedback but this is not the place to ask the questions.
Please use this platform to report bugs you may encounter.
Framework related bug reports goes to https://github.com/frappe/frappe and ERPNext bug reports can be posted to: https://github.com/frappe/erpnext

Please use https://discuss.erpnext.com to search, ask, discuss more about ERPNext.
