### ISSUE TITLE
[bug] quotation base on lead

### ISSUE THREAD

**Issue by cereneto** [frappe/erpnext#17782]
In a quotation for lead, on item_code change, this error is triggered.

![erpnext bug](https://user-images.githubusercontent.com/18381023/58504620-09eb5180-8159-11e9-9154-257a6fefd97a.gif)

![image](https://user-images.githubusercontent.com/18381023/58504441-9cd7bc00-8158-11e9-85c1-753be129eb0d.png)

I've fix it by adding this line in erpnext/accounts/doctype/pricing_rule/pricing_rule.py - get_pricing_rule_for_item 
` if args.get("customer") and not frappe.db.exists("Customer", args.customer): return {}`

and this line in erpnext/stock/get_item_details.py - get_party_item_code
`if args.get("customer") and not frappe.db.exists("Customer", args.customer): return `

But I'm not sure if it's the best way to fix it.

Best regards

**Comment by kennethsequeira** [comment]
Issue was fixed since.
