### ISSUE TITLE
Stock Entry -- Error Message

### ISSUE THREAD

**Issue by yycyjqc** [frappe/erpnext#17783]
Hi,

I tried to upload the file into the stock entry, it kept getting the error message "xxx is not a stock Item". However, I can find the exact same products on the item. How can I fix this?

Let me know if you need more details from me.

Thanks!

**Comment by rvbd** [comment]
Did you check "Maintain Stock" on the item itself?

![image](https://user-images.githubusercontent.com/1558550/58561613-ab55ce80-8251-11e9-9def-c42446787656.png)

**Comment by yycyjqc** [comment]
> Did you check "Maintain Stock" on the item itself?
> 
> ![image](https://user-images.githubusercontent.com/1558550/58561613-ab55ce80-8251-11e9-9def-c42446787656.png)

Thanks for reminding me, I went back to the items and they were checked.

Not sure what happened here.
