### ISSUE TITLE
Adding inline help popup

### ISSUE THREAD

**Issue by onlinebizsoft** [frappe/erpnext#17848]
There are many fields or terms which might be confusing to end-users. We should add some kind of inline help icon which would be very useful to understand without searching in whole the manual.

For example
![image](https://user-images.githubusercontent.com/22501570/58928844-5c8ec400-877e-11e9-963d-c5ec867dd57a.png)

**Comment by kennethsequeira** [comment]
@onlinebizsoft you can add your recommendations here or simply add a 👍 on the issue: https://github.com/frappe/erpnext/issues/2600
