### ISSUE TITLE
In Release v11.1.35, the bank reconciliation statement is not including the opening balance carried over from the prior year.

### ISSUE THREAD

**Issue by EliZABZ** [frappe/erpnext#17846]
ERPNext: v11.1.35 (master)
Frappe Framework: v11.1.30 (master)

In Release v11.1.35, the bank reconciliation statement is not including the opening balance carried over from the prior year.

For more detail, refer to post

https://discuss.erpnext.com/t/bank-reconciliation-statement-opening-not-updating/48104

**Comment by EliZABZ** [comment]
@jigneshpshah  - Do you know if anyone has started investigating this issue?

**Comment by jigneshpshah** [comment]
No idea , i just tagged the issue for easy categorization.

**Comment by EliZABZ** [comment]
@jigneshpshah  - Thank you for taking the time to categorize this issue.

By chance do you know if I can escalate the issue further? 

I've logged the ticket but it seems no one is investigating

**Comment by jigneshpshah** [comment]
If you are on erpnext.com cloud , you may contact support/nabin (account module).. if you are on your own then you need to fix it or get it fixed by some developer.
