### ISSUE TITLE
Fields Rearranging On Save (Customer)

### ISSUE THREAD

**Issue by Mitchy25** [frappe/erpnext#17865]
Whenever I rearrange fields in the Customer Form (Via 'Customise Form'), they seem to rearrange after I click update. I have a feeling that it may have something to do with column_break0 which is a standard field (Thus cant be deleted **or hidden?!**).

I've tried Bench Migrate (Doesnt change anything).

![ERPNext Customer](https://user-images.githubusercontent.com/42224026/59002319-1d3ba280-8866-11e9-8361-63fc6c5ce0db.gif)

**Comment by merlinsquash** [comment]
Did you unknowingly change the order of a standard field ?

**Comment by Mitchy25** [comment]
> Did you unknowingly change the order of a standard field ?

I have probably changed the order of standard fields because I wanted to put them elsewhere. Is this what is causing the issue? Why do standard fields have a preset position that cant be changed?

**Comment by merlinsquash** [comment]
> Why do standard fields have a preset position that cant be changed?

[This was done in 2016](https://discuss.erpnext.com/t/users-will-not-be-able-to-re-arrange-standard-fields/10893)

> Is this what is causing the issue?

I think so yes. Worst part is it does not throw an error and stop process. It lets the customization happen and jumble up all the fields.

**Comment by Mitchy25** [comment]
Thanks Merlin,

I think at the very least it should log a message to the console to let the user know why it is occuring.

**Comment by kennethsequeira** [comment]
@Mitchy25 you might want to add an issue in the [Frappe](https://github.com/frappe/frappe/issues) repository for this.
