### ISSUE TITLE
v12 Variant product didn't show on website

### ISSUE THREAD

**Issue by gmplab** [frappe/erpnext#17916]
I have some Variant products made from Product Template.
In v12 Variant product didn't show on the website, the website only shows the Product Template.

the Variant Products are available in search. But if we click the Variant Product's URL, it will show the template product page.

@netchampfaris Maybe it's caused by new bs4 website.

**Comment by gmplab** [comment]
![20190809145705](https://user-images.githubusercontent.com/1935044/62760190-fe4fcb80-bab5-11e9-83e7-88e9c411ca98.jpg)
V12: in the product page, click "configure" button, In the drop-down menu, there is no variant item value.

**Comment by gmplab** [comment]
#18678

**Comment by rasos** [comment]
Same here, after migrating from v11 to v12 variants are not shown anymore in web shop, if I click on configure I just get an empty drop-down.

![Bildschirmfoto_2019-09-24_15-42-37](https://user-images.githubusercontent.com/485723/65517478-130be580-dee3-11e9-9cf5-8a307607b0ab.png)

Test here: https://erp.fairkom.net/disc-space-s4s6q

**Comment by rasos** [comment]
@scmmishra this strange behaviour seems not to be related to the route like in #18769

**Comment by rasos** [comment]
We still see at a variant the JS error: `ReferenceError: None is not defined`		
which is related to `window.socketio_port = None;`

**Comment by rasos** [comment]
Tested again with new item and variants, still not fixed in 12.3. 
Not being able to offer variants is a showstopper for the webshop @rmehta
