### ISSUE TITLE
Fix : Bank Reconciliation Doctype Not showing Accounts Module

### ISSUE THREAD

**Issue by sammish** [frappe/erpnext#17976]
Bank Reconciliation Doctype Not showing Accounts Module 

![Bank Reco1](https://user-images.githubusercontent.com/12432802/59736342-e0a67880-9261-11e9-81e2-6d4febfdc296.gif)

**Comment by sammish** [comment]
@nabinhait Please check this issue

**Comment by umairsy** [comment]
Hello,

In V11, the link is renamed as "Update Bank Transaction Dates".

<img width="1194" alt="Screenshot 2019-06-19 at 10 47 45 AM" src="https://user-images.githubusercontent.com/910238/59738770-00e53000-9280-11e9-83a6-cfffe58e69d6.png">

**Comment by sammish** [comment]
@umairsy hum , sorry...... I am not check very well.
