### ISSUE TITLE
Product Bundle in Purchase Cycle

### ISSUE THREAD

**Issue by bhavishyasharma** [frappe/erpnext#17985]
Hi everyone!

I have implemented the bundle in Buying Cycle. The valuation of child items is calculated based on the weightage which is defined in the ProductBundle

Steps:

1. Add weightage field to Product Bundle.
![image](https://user-images.githubusercontent.com/15744297/58901508-f32b9880-871e-11e9-8178-165c60f1dac6.png)
2. Add weightage field to Packed Item.
3. Add rate and amount fields to Packed Item.
![image](https://user-images.githubusercontent.com/15744297/58902099-1571e600-8720-11e9-9ecd-6b67fcbe0be5.png)

4. Add packed_items to Purchase Order, Purchase Receipt, Purchase Invoice.
<img width="1322" alt="Screenshot 2019-06-04 at 23 18 59" src="https://user-images.githubusercontent.com/15744297/58901743-68976900-871f-11e9-88b1-f745c35f96da.png">

5. Pass stock_entry for Purchase Receipt and Purchase Invoice.

Please let me know how to push the code adhering to your development guidelines.

**Comment by kennethsequeira** [comment]
@bhavishyasharma check the following: https://github.com/frappe/erpnext/wiki/Contribution-Guidelines

**Comment by Joepriesto** [comment]
Suggest closing this. Looks to have gone stale.
