### ISSUE TITLE
ITC not populated correctly in GSTR 3B

### ISSUE THREAD

**Issue by siddhpant** [frappe/erpnext#18004]
For example, I made an invoice for GSTR3B generation and the ITC isn't populated correctly.

![image](https://user-images.githubusercontent.com/25429745/59838167-1e8fc380-936c-11e9-95d1-37a145c1f42a.png)

`A - B` is 480 but both `A` and `B` are zero. The `A` must have the 480 in it in the respective columns (All other ITC) in this case, and otherwise too `A` and `B` must have valid positive values. 

Uploading the generated JSON produces an error, viz.:

```
NET ITC Provided is not equal to ITC Available – ITC Reversed. 
If error persists quote error number RET3B91404 when you contact customer care for quick resolution.
```

(Also, it doesn't show/populate anything in the ITC Reversed column when it should at least show 0 for definitiveness.)

**Comment by deepeshgarg007** [comment]
@siddhpant can you share the screenshot of the Purchase Taxes and Charges Table and also the GST DETAILS section which will help me to resolve the issue faster

**Comment by deepeshgarg007** [comment]
@siddhpant 
Fixed both the issues that you have mentioned here

![image](https://user-images.githubusercontent.com/42651287/60568122-8b05bc00-9d89-11e9-94ea-5ce14c7cb638.png)

You can try uploading the json again and let me know if it works or not

Closing this issue

**Comment by siddhpant** [comment]
Okay, I will let you know in a day. I was inactive for some time due to
personal reasons so couldn't reply to this thread. Thanks for
prompt response.

**Comment by siddhpant** [comment]
Working, thanks.

There was a serious server incident so it took me time
