### ISSUE TITLE
Credit/Debit Notes in ERPNext V11

### ISSUE THREAD

**Issue by hballan** [frappe/erpnext#18003]
Credit/Debit Notes in ERPNext V11 don't appear in the [Match Payments with Invoices] screen when we click on [Get Unreconciled Entries]. The only way to use them to close out invoices or purchases is through the [Payment Entry] screen.

**Comment by kennethsequeira** [comment]
This feature is being added v12: https://github.com/frappe/erpnext/pull/18034
