### ISSUE TITLE
[India] [gst] ITC classification during purchases

### ISSUE THREAD

**Issue by test2a** [frappe/erpnext#18015]
Allow the user to classify purchases into any of the three

* inputs
* Capital goods
* services 

At the time of purchases as its a statutory requirement to classify them at the time of filing of annual returns and ones with a lot of purchases, this is going to be a difficult thing to do. 

I propose to add this option on purcahses invoice so that this detail is collected during vouching level.

**Comment by deepeshgarg007** [comment]
@test2a this is already available on V12 under GST DETAILS section inside Purchase Invoice

![image](https://user-images.githubusercontent.com/42651287/60497953-66e7a380-9cd3-11e9-861d-76a332f47d9e.png)

Closing this issue

**Comment by test2a** [comment]
@deepeshgarg007 is there a report to check the breakup of purchases based on these classifications as well?
