### ISSUE TITLE
[Paid Development] Ability to completely modify salary slip before submitting it

### ISSUE THREAD

**Issue by hballan** [frappe/erpnext#18033]
The current Payroll workflow after creating salary slips from a payroll entry the system doesn't allow the user to modify any of the amounts in the salary slip. If you attempt to change any of the amounts or add or remove salary components when you press save the salary slip reverts back to the amounts and salary components setup in the salary structure. 

I would like you to add a setting to allow the user to create a [Salary Component] that is completely flexible this means you can [Remove it] [Add it] [Modify Amount] after the salary slip has been created without any restrictions and without modifying the [Salary Structure] it's based on. I am aware of the [Additional Salary] workflow but it is just too time consuming and complicated.

Since Payroll is complex and country specific, this added flexibility would be greatly appreciated. If some customers don't want this feature for security concerns they can just not use it. 

Many of the Salary Components in our payroll vary every month (Example: Overtime, Absence, Bonuses....) and we need a simple way of modifying the amounts, adding components, removing components before submitting the salary slips.

Under this implementation I can create a salary structure that is completely flexible using this type of salary component. The salary strucutre becomes just a template which the slips are based off each month, then the user can easily go through the slips for each employee and modify the content as needed.

The implementation of this should be super simple, just add a check box on the salary component form [Is Overidable Component] then on the salary slip form when you change any information and press save don't let the code revert the slip back to the salary structure for components that are marked [Is Overidable Component]

The user should be able to create [Salary Structures] that are based on this type of [Salary Component] without any restrictions so we can create fully customizeable [Salary Structures]

Although this is such a simple feature it would give great flexibility to meet the changellenges and complexities of payroll processing. It basically allows a user to have full control if he choose over the salary slip which would make entering the variable components of payroll each month so much faster and easier. I am sure many users of ERPNext would appreciated the simplicity and added flexibility of this feature.

Once this feature is added the workflow for Payroll would be as follows:
1. Create a [Salary Structure] for an Employee with the main [Salary Components] likely to be relevant for him each month, enter approximate amounts, check those components as [Is Overidable Component].
2. Create a [Payroll Entry] which then would create the [Salary Slips]
3. Open each employee slip, review it, modify amounts, add salary components, remove salary components to meet the specifics of each month and save it
4. Submit the Slips

**Comment by kennethsequeira** [comment]
@hballan you should post on the [ERPNext Job Board](https://erpnext.org/erpnext-jobs)

**Comment by Olawale1** [comment]
This is a big issue for organizations with a large workforce and varying salary components

Additional Salary can be used as a sort of workaround but still too tedious when you’re dealing with hundreds or even just 10s of employees. It would make sense to most Payroll Managers to be able to edit the Salary Slips within the ‘Salary Register’ report view while they’re still in Draft. This way, it’s almost like working with a spreadsheet… you can immediately see that the figures are adding up as expected and then you Submit them using the Payroll Entry when everything’s okay

This flexibility is very important for a normal User Experience. Practically every Payroll Manager I’ve encountered are dismayed at how rigid ERPNext is when it comes to making changes in the Payroll

Thanks

**Comment by hballan** [comment]
Yes, exactly my point finally someone gets it. Unfortunetly, I have been in touch with the development team to explain this issue and they refused to modify it. I even offered to pay to sponsor this feature to have them develop it as it seems like such a trivial thing to implement, just let me customize the slips as I please without reverting to the salary structure on saving but unfortunetly they refused that too saying that it is not a universal feature that applies to all customers. I have even tried to explore third party developpers to implement this feature, however the issue is that if you go with a third party developper you have to fork the code and go move hosting platforms which means that the customization will no longer be upgrade friendly. The ERPNext development team suggested that we use the additional salary feature and to use import functionality from an excel sheet in case there are many employees, this seems like such a over complicated solution but unfortunetly it's the only option available at the moment. Maybe if there is enough interest in this functionality we can convince the ERPNext team to implement it as a feature for customers who need it.
