### ISSUE TITLE
General Ledger / report

### ISSUE THREAD

**Issue by farhanayyaz1** [frappe/erpnext#18036]
Please revise teh new option of generating a report that is making things too difficult. If you want to keep both but please keep teh general ledger/reports to be seen directly.

**Comment by kennethsequeira** [comment]
@farhanayyaz1 you can remove it for the reports you don't want via the permission manager for report:

![image](https://user-images.githubusercontent.com/33246109/59998806-f65ed800-967d-11e9-8b43-7bbe1e9b5000.png)

Check on **Disable Prepared Report**
