### ISSUE TITLE
Problem with Spanish translations

### ISSUE THREAD

**Issue by jaimestuardo** [frappe/erpnext#18046]
Hello,

**Installed Apps
ERPNext: v11.1.19 (master)

Frappe Framework: v11.1.20 (master)**

Steps to reproduce the problem:

1. ERPNext in Spanish

1. Load Lead list (/desk#List/Lead/List)

1. Click "Nuevo" button ("New")

1. Enter a name and click "Guardar" button ("Save")

1. Click "Make" drop down (by the way, this word was not translated) and choose "Oportunidad" option ("Opportunity")

1. Click "Guardar" button ("Save"). An error is shown: "No se pudo encontrar Tipo de oportunidad: Sales" ("Could not find Opportunity Type: Sales"). Notice that "Sales" appears in the Opportunity combobox.

1. Change "Sales" in Opportunity combobox to be "Ventas". Then "Guardar".

1. It works.

Above case shows that when creating an Opportunity from the Lead, incorrect Opportunity Type is transfered from one page to the other, cause of the translation.

The exact same problem occurs when loading opportunities from e-mail.

This is the logged error in that case (pull_from_email_account event type):

`{'event': u'all', 'retry': 0, 'log': <function log at 0x7f5571083e60>, 'site': u'erp.desytec', 'job_name': u'pull_from_email_account|Ventas Desytec', 'method_name': u'pull_from_email_account', 'method': <function pull_from_email_account at 0x7f557101eed8>, 'user': u'Administrator', 'kwargs': {'email_account': u'Ventas Desytec'}, 'is_async': True}
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 103, in execute_job
    method(**kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 713, in pull_from_email_account
    email_account.receive()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 301, in receive
    raise Exception(frappe.as_json(exceptions))
Exception: [
 "Traceback (most recent call last):\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py\", line 278, in receive\n    communication = self.insert_communication(msg, args=args)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py\", line 380, in insert_communication\n    self.set_thread(communication, email)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py\", line 431, in set_thread\n    parent = self.create_new_parent(communication, email)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py\", line 507, in create_new_parent\n    parent.insert(ignore_permissions=True)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py\", line 216, in insert\n    self._validate_links()\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py\", line 741, in _validate_links\n    frappe.LinkValidationError)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py\", line 355, in throw\n    msgprint(msg, raise_exception=exc, title=title, indicator='red')\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py\", line 341, in msgprint\n    _raise_exception()\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py\", line 314, in _raise_exception\n    raise raise_exception(msg)\nLinkValidationError: Could not find Opportunity Type: Sales\n"
]`

This is the other logged error (email_account.receive event type):

`Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 278, in receive
    communication = self.insert_communication(msg, args=args)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 380, in insert_communication
    self.set_thread(communication, email)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 431, in set_thread
    parent = self.create_new_parent(communication, email)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 507, in create_new_parent
    parent.insert(ignore_permissions=True)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 216, in insert
    self._validate_links()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 741, in _validate_links
    frappe.LinkValidationError)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 355, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 341, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 314, in _raise_exception
    raise raise_exception(msg)
LinkValidationError: Could not find Opportunity Type: Sales`

There is another translation problem that I think it is related. That's why I included in this same issue:

Steps to reproduce:

1. ERPNext in Spanish

1. Load Customize Form page: /desk#Form/Customize%20Form/Customize%20Form

1. In "Seleccione el Tipo de Formulario" combobox, write "quo" to try to find "Quotation Item"

1. It isn't found. Now try to look for "Pres" ("Presupuesto"). In that case, "Quotation Item, Ventas" is listed

![image](https://user-images.githubusercontent.com/9195659/60022675-4760d300-9662-11e9-888f-2fd429cf4abb.png)

In case above, I am not sure about the solution. The most correct translation of "Quotation" is "Cotización", and in fact, in the whole ERPNext, the translation is correct. Word "Presupuesto" is equivalent to "Budget" in English. So, the first error is how that word was translated. It should be "Ítem de Cotización" ("Quotation Item"). Second, the way of searching should be modified. 

If database table or element is called "Quotation Item", system should allow to search using that name, because that name is used in the fields list. I think this is the best solution.

As an alternative, in the fields list the name could be in the target language (Spanish, in this case). That way, user could know how to search for it in the form type combobox.

Best regards

Jaime

**Comment by barredterra** [comment]
Same as here: frappe/frappe#17010

**Comment by clarkejj** [comment]
See discussion https://discuss.erpnext.com/t/bug-in-features-that-use-translation-in-spanish/49911
