### ISSUE TITLE
OpenLDAP Integration: Upgrade to Python LDAP3 Makes Complex Filtering Impossible

### ISSUE THREAD

**Issue by chlarsen** [frappe/erpnext#18053]
Dear All,
Prior to the required upgrade to the Python LDAP3 module that occurred with the ssecond most recent ERPNext upgrade, I could use:

LDAP SEARCH STRING:
``````
(&(objectclass=inetOrgPerson)(memberOf=cn=[erpnext_instance_user_group],ou=Groups,o=[organisation])(mail={0}))
``````
After the upgrade to LDAP3, the complext search string is not recognised any more, as ERPNext demands that the filter string ends with "{0}", which is of course incompatible with complex filters. So this one works, but does not cut it or me:

LDAP SEARCH STRING:
``````
mail={0}
``````
I think this is a bug in Frappé or ERPNext, as I hae never seen this issue with other apps that need LDAP3. 
Any thoughts?
Thanks a lot,
Chris

**Comment by clarkejj** [comment]
This reports a problem with v11.1.46 with a PR fix https://discuss.erpnext.com/t/ldap-stopped-working-after-update-master-branch-pr-provided/50662/5

**Comment by jon-nfc** [comment]
@chlarsen 

What version of frappe and erpnext are you using? I've been working on a proposal frappe/frappe#13738 currently v13. 

I can confirm my change does accept the filter in your OP.

**Comment by chlarsen** [comment]
Indeed, and thank you! The upgrade to amazing version 13 has solved a lot of issues and reflects the outstanding work that has gone into it. Thank you!

**Comment by jon-nfc** [comment]
> Indeed, and thank you! The upgrade to amazing version 13 has solved a lot of issues and reflects the outstanding work that has gone into it. Thank you!

FYI, it still hasn't been pushed to main repo yet as it's still under development. However I'm glad it will fix your issue. If you wish to keep track please follow frappe/frappe#13738
