### ISSUE TITLE
V11 - Sales Order Delivery Date Field Bug.

### ISSUE THREAD

**Issue by f-9t9it** [frappe/erpnext#18065]
When a user selects delivery date which is before the posting date by mistake and then press save then there is a error message.

But after that when user tries to correct the mistake and press save the delivery date automatically moves back to the wrong date user selected before and then same error message. 

Looks like JS Bug on Delivery Date Field.

**Comment by AleCVERP** [comment]
We have the same problem with V11, please fix this.

**Comment by ishanloya** [comment]
Same issue

**Comment by ankush** [comment]
Delivery date needs to be specified in child table. https://github.com/frappe/erpnext/issues/26373
