### ISSUE TITLE
Demo keeps saying `User demo@erpnext.com does not have doctype access via role permission for document Email Account`

### ISSUE THREAD

**Issue by tom10271** [frappe/erpnext#18089]
I cannot create a new PO at least which block a sequence of feature testings

**Comment by andriusr** [comment]
I have the same message with several users on:
ERPNext: v12.27.0 (version-12)
Frappe Framework: v12.24.0 (version-12)
The system was upgraded several times from v8.0, however, this particular message appeared when upgrade was done from v12.15 to v12.27.
Message appears when user is trying to create New Email from Project and there are already several other emails attached to it.
