### ISSUE TITLE
Need Multi Currency in Payroll

### ISSUE THREAD

**Issue by peshgathoni** [frappe/erpnext#18100]
We like many international companies we pay local staff in local currency and other staff in USD. We need a way to generate payslips in both USD and local currencies

**Comment by abdhasa** [comment]
This is really needed

**Comment by clarkejj** [comment]
You can always sponsor development https://discuss.erpnext.com/t/multiple-currencies-for-single-payroll/31618

**Comment by iamkhalidbashir** [comment]
bump

**Comment by harshit-30** [comment]
Implemented [here](https://github.com/frappe/erpnext/issues/24105).
