### ISSUE TITLE
"Reqd by date" in Purchase order

### ISSUE THREAD

**Issue by Vaibhav-erpnext** [frappe/erpnext#18138]
Below points in Purchase Order.

1. "Reqd By Date" is mandatory. Then it should be highlighted as mandatory as other fields are shown. 

2. User has to enter at the item level instate at the document level(below the date field).

3. If the user entered multiple item lines with different "Reqd By Date" then only first entered date is fetched at the document level. I think it should consider the earliest date.

4 If the user has changed the "Reqd By Date" at the item level then it is not updating at the document level.

5. Once the "Reqd By Date" is updated at the document level, it is not updating if the user changes at the item level.

![Screenshot 2019-07-02 at 3 05 48 PM](https://user-images.githubusercontent.com/49669130/60505281-06f7f980-9ce1-11e9-94a3-797606710ace.png)

![Reqd_By_Date](https://user-images.githubusercontent.com/49669130/60506134-d1541000-9ce2-11e9-8712-9f1115e2fe08.gif)

**Comment by jaichavan** [comment]
It will take the first Required By date, which is correct by logic too. Closing this issue.
