### ISSUE TITLE
Unable to Cancel PO

### ISSUE THREAD

**Issue by harishbabutv** [frappe/erpnext#18157]
Hi Team,

I am unable to cancel existing PO.

I need to modify qty and price in the PO and I thought of cancelling / amending the PO but unable to perform the above.

Please provide me steps to complete the above and do the needful.

Regards
Harish Babu T V
98862 70195

**Comment by kennethsequeira** [comment]
If you're on erpnext cloud(erpnext.com), raise a support ticket else post on the community forum: https://discuss.erpnext.com
