### ISSUE TITLE
Server InternalError: 1054 when opening Customer Profile

### ISSUE THREAD

**Issue by MohammadAhmad1990** [frappe/erpnext#18198]
Hi,
I have done a new installation of the develop branch. I get a pop up message showing server error when ever I open a customer profile.

> InternalError: (1054, u"Unknown column ‘tabService Level Agreement.customer’ in ‘where clause’")

Installed Apps
ERPNext: v12.x.x-develop () (develop)
Frappe Framework: v12.x.x-develop () (develop)

Regards,

![Screenshot from 2019-07-06 12-29-25](https://user-images.githubusercontent.com/7881486/60791183-891e6d00-a17c-11e9-99ba-114a8e7ff3eb.png)

**Comment by clarkejj** [comment]
Issue resolved https://discuss.erpnext.com/t/server-error-when-opening-customer-detail/50499
