### ISSUE TITLE
Is it possible to deploy ERPNext on Heroku？

### ISSUE THREAD

**Issue by yltang52** [frappe/erpnext#18203]

**Comment by kennethsequeira** [comment]
@yltang52 

You might find answers to your question [here](https://discuss.erpnext.com). Kindly refrain from posting queries as Github is to be used for bug tracking.

As for Heroku, ERPNext is designed to run on cloud VPS servers. If Heroku offers something similar for deployment, it may be worth a try, but sticking to a regular service provider such as Amazon AWS, Digital Ocean, Vultr, etc. might be better.
