### ISSUE TITLE
Purchase Receipt for Item for which Sample can be retained

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#18223]
Steps:

1. Created a Batch Item and enabled Retain Sample for it.
2. Creating Purchase Receipt for the Item

Following is the error message when selecting Item Code.

<img width="1339" alt="Screenshot 2019-07-10 at 3 18 57 PM" src="https://user-images.githubusercontent.com/910238/60959716-557f4680-a326-11e9-9510-5e1f0b1c00f6.png">

**Comment by deepeshgarg007** [comment]
Fixed via: https://github.com/frappe/erpnext/pull/18419
