### ISSUE TITLE
Payment Order - Error when click on Generate TXT file

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#18230]
Looking at the error message, I don't know what to fix.

<img width="1289" alt="Screenshot 2019-07-10 at 3 53 49 PM" src="https://user-images.githubusercontent.com/910238/60962104-2c14e980-a32b-11e9-96be-2ba8876fc0f6.png">

**Comment by Mangesh-Khairnar** [comment]
#18645 Feature removed
