### ISSUE TITLE
cant create pos profile

### ISSUE THREAD

**Issue by jetmodel** [frappe/erpnext#18245]
I followed the instruction but I can't create a pos profile. which fields are mandatory? on series I can only chose "select". is it right?

**Comment by papakaizen** [comment]
There is a minor setup prior creating POS Profile :

1. Go to Setup -> (Under Data Section) Naming Series
2. Choose "Sales Invoice" under transaction field
3. Make your own serial number format in "Series List of Transaction" (and delete [select])
4. Update
5. Try to reload (from your name menu; This to clear the cache)
6. Try to create the POS Profile

Hope this can work.

**Comment by jetmodel** [comment]
thanks, it works
