### ISSUE TITLE
Custom script not working in v11 

### ISSUE THREAD

**Issue by GhadaEbrahim** [frappe/erpnext#18249]
This code was working in v10
what is the problem?

frappe.ui.form.on("Attendance", {
to:function(frm, cdt, cdn){
var d = locals[cdt][cdn];
	var hours=minutes=seconds=total=0
	if(d.from && d.to)
	{
		var startTime=moment(d.from, "HH:mm:ss");
		var endTime=moment(d.to, "HH:mm:ss");
		var duration = moment.duration(endTime.diff(startTime));
		var hours = parseInt(duration.asHours());
		var minutes = parseInt(duration.asMinutes())%60;
		var seconds=parseInt(duration.asSeconds())%60;
		console.log(hours + ' hour and '+ minutes+' minutes.' +seconds+'second');

	}
		frappe.model.set_value(cdt,cdn,"total",hours+":"+minutes+":"+seconds);
		frm.refresh_field("total");

},
from:function(frm, cdt, cdn){
var d = locals[cdt][cdn];
	var hours=minutes=seconds=total=0
	if(d.from && d.to )
	{
		var startTime=moment(d.from, "HH:mm:ss");
		var endTime=moment(d.to, "HH:mm:ss");
		var duration = moment.duration(endTime.diff(startTime));
		var hours = parseInt(duration.asHours());
		var minutes = parseInt(duration.asMinutes())%60;
		var seconds=parseInt(duration.asSeconds())%60;
		console.log(hours + ' hour and '+ minutes+' minutes.' +seconds+'second');
		
	}
		frappe.model.set_value(cdt,cdn,"total",hours+":"+minutes+":"+seconds);
		frm.refresh_field("total");

}

})

**Comment by kennethsequeira** [comment]
@GhadaEbrahim kindly post customization related issues on the forum for support: https://discuss.eprnext.com
