### ISSUE TITLE
Breadcrumb missing for Accounting Dimension

### ISSUE THREAD

**Issue by jaichavan** [frappe/erpnext#18265]
![image](https://user-images.githubusercontent.com/40264279/61065715-de2edd00-a421-11e9-8eaf-8a469fdccfaf.png)

**Comment by deepeshgarg007** [comment]
Breadcrumb visible for Accounting Dimension

![image](https://user-images.githubusercontent.com/42651287/61174382-c93a8100-a5bc-11e9-97e6-4e6bab1d28b1.png)

**Comment by jaichavan** [comment]
Check frappetestv12.erpnext.xyz @deepeshgarg007

**Comment by netchampfaris** [comment]
@jaichavan V12 is not released yet. So updates are not triggered for all accounts. I can confirm this breadcrumb issue is fixed.

**Comment by jaichavan** [comment]
ok, leaving this closed on your word ;) @netchampfaris
