### ISSUE TITLE
Multiple fields for enabling/disabling dimension.

### ISSUE THREAD

**Issue by jaichavan** [frappe/erpnext#18268]
"Disable" Checkbox should be removed, it's just redundant. We can't even check/uncheck it. It is updated when the button is clicked. Why do we have it then?

![image](https://user-images.githubusercontent.com/40264279/61067703-ce18fc80-a425-11e9-9cd1-b4225225b5ed.png)

**Comment by deepeshgarg007** [comment]
Fixed via: https://github.com/frappe/erpnext/pull/18340
