### ISSUE TITLE
Validation message isn't very helpful for naive user

### ISSUE THREAD

**Issue by jaichavan** [frappe/erpnext#18269]
![image](https://user-images.githubusercontent.com/40264279/61068906-ca3aa980-a428-11e9-8b3d-e58663e03722.png)

**Comment by rmehta** [comment]
Also department should be bold

**Department** is a mandatory **Accounting Dimension**

**Comment by deepeshgarg007** [comment]
Fixed via https://github.com/frappe/erpnext/pull/18340
