### ISSUE TITLE
Inappropriate message for Bank Guarantee

### ISSUE THREAD

**Issue by jaichavan** [frappe/erpnext#18271]
The popover tells us to create a Bank Guarantee when it is disabled. So, how should I? 😜
The pre-requisite step/document should be added in this message instead of "Bank Guarantee" itself.

![image](https://user-images.githubusercontent.com/40264279/61070598-be50e680-a42c-11e9-85e6-fa192dd92cf8.png)

**Comment by netchampfaris** [comment]
https://github.com/frappe/erpnext/pull/18318
