### ISSUE TITLE
Only Cost Center dimension can be selected in Budget Variance Report?

### ISSUE THREAD

**Issue by jaichavan** [frappe/erpnext#18275]
Steps to replicate:
1) Go to "Budget Variance Report"
2) Select dimension in the "Budget Against" filter
3) The next field still enlists Cost Centers instead of dimension (Department/Project)

![image](https://user-images.githubusercontent.com/40264279/61071827-adee3b00-a42f-11e9-9036-4222717e462a.png)

**Comment by deepeshgarg007** [comment]
Dimension can be selected from the Budget Against select field and for filters will currently have to use inline filters in datatable

![Screenshot 2019-07-15 at 6 58 10 PM](https://user-images.githubusercontent.com/42651287/61219877-c2357f00-a732-11e9-808d-a1faa63fe88f.png)
