### ISSUE TITLE
Accounting dimension missing in Customer Credit Balance

### ISSUE THREAD

**Issue by jaichavan** [frappe/erpnext#18276]
Accounting Dimension: **Department**

![image](https://user-images.githubusercontent.com/40264279/61073532-43d79500-a433-11e9-8719-d32c58daa23b.png)

Just like Cost Center appears here, the accounting dimension, Department, should've too.

![image](https://user-images.githubusercontent.com/40264279/61073477-299db700-a433-11e9-8a1e-037c292b6b75.png)

**Comment by deepeshgarg007** [comment]
Cost Centre filter and dimension filters does not make sense in Customer Credit Balance Report

It calculates outstanding from GL Entry, Sales Order and Delivery Note and no accounting dimensions are available in Sales Order and  Delivery Note

Removed cost centre filter from report via https://github.com/frappe/erpnext/pull/18340
