### ISSUE TITLE
Dimension disabled but still visible in transactions

### ISSUE THREAD

**Issue by jaichavan** [frappe/erpnext#18278]
Below steps to replicate are based on an assumption: You already have an active accounting dimension in your ERPNext account. 
1) Disable this accounting dimension:

![image](https://user-images.githubusercontent.com/40264279/61076824-bc8e1f80-a43a-11e9-9f38-8ece0ae89e08.png)

2) Reload

3) Dimensions still visible in transactions:

Sales Invoice:
![image](https://user-images.githubusercontent.com/40264279/61077029-2f979600-a43b-11e9-897a-cd95efb067a6.png)

The fields can be left empty, they don't obstruct the submission fo the document, but if the dimension is disabled, why are these still here? :-/

Also, post submission of above sales invoice, the field, "e-Way Bill No." is seen under the Dimensions tab:

![image](https://user-images.githubusercontent.com/40264279/61077266-a5036680-a43b-11e9-80f3-dc8e8c041530.png)

**Comment by deepeshgarg007** [comment]
@jaichavan Unable to replicate. Closing
