### ISSUE TITLE
Inconsistency in Stock Entry & Stock Ledger Report

### ISSUE THREAD

**Issue by jaichavan** [frappe/erpnext#18277]
So, we have a Stock Entry, under dimension, "Department"

![image](https://user-images.githubusercontent.com/40264279/61074233-d9bfef80-a434-11e9-81da-b3bdbff74652.png)

Then, we open Stock Ledger report for this entry & add "Department" via Add Column, only to find it empty:

![image](https://user-images.githubusercontent.com/40264279/61074675-e133c880-a435-11e9-9c63-4cf8aeaf97dc.png)

**Comment by deepeshgarg007** [comment]
Unable to replicate. Closing
