### ISSUE TITLE
Invoice Discounting: Indictor / Flag on Sales Invoice that it has been discounted

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#18288]
Currently, looking at the Sales Invoice, we cannot understand if this invoice has been discounted. We should have some indicator which clarifies it? We can use same as a parameter to prevent creation of multiple Invoice discountins for the same invoice.

**Comment by Anurag810** [comment]
It shows under more information.

![Screenshot 2019-08-07 at 12 38 46 PM](https://user-images.githubusercontent.com/32095923/62603986-ad54a180-b914-11e9-94fc-77ed79b10b6d.png)
 I know it is not visible. any suggestion where to put.

**Comment by umairsy** [comment]
I think it has been added in the Indicator already. We can close this.

<img width="1235" alt="Screenshot 2019-08-07 at 1 36 47 PM" src="https://user-images.githubusercontent.com/910238/62606067-058da280-b919-11e9-8f26-4d805b5141f0.png">
