### ISSUE TITLE
Auto-invoicing: Rename Loan Period to Load Period (Days)

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#18283]
Currently, field label doesn't indicate that Loan Period has to be entered in Days. Let's add this term in the label itself.

<img width="1236" alt="Screenshot 2019-07-12 at 11 49 20 AM" src="https://user-images.githubusercontent.com/910238/61106690-846af900-a49b-11e9-9e0e-e4e108c11f78.png">

Period can mean to Days, Weeks, Months... etc..

**Comment by ruchamahabal** [comment]
Already fixed in: https://github.com/frappe/erpnext/pull/18136

![loan_period_days](https://user-images.githubusercontent.com/24353136/62446802-566a9300-b781-11e9-87b2-dff7f312e00d.png)
