### ISSUE TITLE
Two dimension field for same DocType

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#18282]
In the Sales Invoice, under Dimensions section, Project field is there by default. It still allowed me to create Project as a dimension, and inserted another field for it.

Perhaps we should restrict adding Cost Center and Project as a Custom Dimension, as they are dimensions already?

<img width="1183" alt="Screenshot 2019-07-12 at 11 27 38 AM" src="https://user-images.githubusercontent.com/910238/61105752-7c5d8a00-a498-11e9-9f65-6353e9675021.png">

**Comment by deepeshgarg007** [comment]
Fixed via https://github.com/frappe/erpnext/pull/18340
