### ISSUE TITLE
Invoice Discounting: Make Status field Read Only

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#18286]
It should not be editable by the user.

<img width="1226" alt="Screenshot 2019-07-12 at 12 10 18 PM" src="https://user-images.githubusercontent.com/910238/61109686-16c2cb00-a4a3-11e9-97dc-93011cb3bab6.png">

**Comment by ruchamahabal** [comment]
Already fixed in: https://github.com/frappe/erpnext/pull/18136

![status_field_read_only](https://user-images.githubusercontent.com/24353136/62446425-4f8f5080-b780-11e9-95e0-0368c2b9f8ba.png)
