### ISSUE TITLE
Allows creation of multiple Invoice Discounting for a single Sales Invoice

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#18287]
Steps:

1. Created an Invoice Discount for Sales Invoice "ACC-SINV-2019-00006", which is also disbursed.

<img width="1216" alt="Screenshot 2019-07-12 at 12 48 26 PM" src="https://user-images.githubusercontent.com/910238/61109845-8cc73200-a4a3-11e9-914d-e355e162efb8.png">

2. Tried creating another Invoice Discounting for same invoice, and could save one.

<img width="1191" alt="Screenshot 2019-07-12 at 12 49 10 PM" src="https://user-images.githubusercontent.com/910238/61109891-a8323d00-a4a3-11e9-8fc1-ef98905adb8c.png">

**Comment by Anurag810** [comment]
As discussed with @asbasawaraj this not a valid issue. Only one invoice can be discounted once.

**Comment by umairsy** [comment]
@asbasawaraj I could still make two Invoice Discounting for the same invoice (full amount). You think this should be allowed?

**Comment by umairsy** [comment]
@Anurag810 so this is valid issue... right? )

**Comment by Anurag810** [comment]
Yeah, I just replied in the reference of the title. So, blocked Discounting for multiple invoices.

**Comment by Anurag810** [comment]
https://github.com/frappe/erpnext/pull/18629
