### ISSUE TITLE
Dimension mandate failure in Sales Invoice 

### ISSUE THREAD

**Issue by jaichavan** [frappe/erpnext#18280]
Steps to replicate:
1) Create a dimension and only enable it for Balance Sheet accounts:

![image](https://user-images.githubusercontent.com/40264279/61080323-70df7400-a442-11e9-9e44-bf3b3841805e.png)

2) Make a Sales Invoice: The mandate for balance sheet account (in this case, Debtors) should've flagged the empty dimension field, but allowed to submit the invoice.

Note: The validation works correctly for Payment Entry, Journal Entry.

**Comment by deepeshgarg007** [comment]
@jaichavan Unable to replicate. Closing
