### ISSUE TITLE
Invoice Discounting: Error message doesn't indicate which values needs to be corrected

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#18284]
<img width="1334" alt="Screenshot 2019-07-12 at 12 12 00 PM" src="https://user-images.githubusercontent.com/910238/61107852-7ec2e280-a49e-11e9-804d-e49f910d2502.png">

Entry:

<img width="1226" alt="Screenshot 2019-07-12 at 12 12 44 PM" src="https://user-images.githubusercontent.com/910238/61107883-8f735880-a49e-11e9-9274-49056d8e9387.png">

**Comment by umairsy** [comment]
If I jus flop Debtor and Debtor Discount account, then Invoice Discounting is saved just fine.

The field labels are "Credit Account",  "Discounted Account".. "Unpaid Account" are difficult to understand. Perhaps we should add description there. Or set some default accounts, if Invoice Discounting feature is enabled?

Also, should we restrict the selection of Debtor account which is selected in the Sales Invoice? Then only customer will get complete clarity on the Discounted and Unpaid account in the Balance Sheet.

**Comment by umairsy** [comment]
Suggestion for renaming fields:

- Account Receivable Credit Account to "Loan Sanctioned but not Disbursed"
- Account Receivable Discounted Account to "Payment against Bank Loan"

Am not very sure feature name is invoice discounting. Could we call at "Loan against Receivables" or something which indicates the purpose of this feature?

**Comment by Anurag810** [comment]
https://github.com/frappe/erpnext/pull/18629
