### ISSUE TITLE
Breadcrumb missing in Promotional Scheme

### ISSUE THREAD

**Issue by jaichavan** [frappe/erpnext#18299]
![image](https://user-images.githubusercontent.com/40264279/61126073-23f2b080-a4c9-11e9-9efe-9d2770d6dcb7.png)

**Comment by netchampfaris** [comment]
![image](https://user-images.githubusercontent.com/9355208/61199028-00627c80-a6fa-11e9-873a-098168e6fef4.png)

@jaichavan Already fixed. Update v12 to latest.

**Comment by jaichavan** [comment]
@netchampfaris  Perhaps, you can upgrade this instance **frappetestsv12.erpnext.xyz** so we are on the same version ;-)
