### ISSUE TITLE
Retention bonus and employee incentive not getting fetched while creating salary slip

### ISSUE THREAD

**Issue by michellealva** [frappe/erpnext#18308]
Steps to replicate this issue:

1. Create an employee, create a salary structure, assign salary structure to the employee.
2. In HR > Payroll > Retention Bonus (Create a new retention bonus with a date in August).
3. In HR > Payroll > Employee Incentive (Create a new employee incentive with a date in August).
4. Run payroll entry for the month of August and generate Salary Slips.

The created employee incentive and retention bonus do not get fetched in the salary slip.

![Screenshot 2019-07-13 at 9 13 36 PM](https://user-images.githubusercontent.com/50285544/61173640-a8b9f900-a5b3-11e9-8925-efe0b703a844.png)

![Screenshot 2019-07-13 at 9 14 10 PM](https://user-images.githubusercontent.com/50285544/61173641-ac4d8000-a5b3-11e9-979f-da130e791839.png)
![Screenshot 2019-07-13 at 9 16 18 PM](https://user-images.githubusercontent.com/50285544/61173642-af487080-a5b3-11e9-9eaa-61dd23143f2b.png)

**Comment by michellealva** [comment]
@ruchamahabal any progress?

**Comment by ruchamahabal** [comment]
https://github.com/frappe/erpnext/pull/18647
@michellealva you can track the progress of this feature here.
