### ISSUE TITLE
[Keyboard SC] Page level shortcut, Email can cause unwanted issues

### ISSUE THREAD

**Issue by jaichavan** [frappe/erpnext#18302]
Steps to replicate:
1) Try creating any new document (Item, Invoice, etc )
2) We can trigger page level shortcuts here. **Jump** is fine but **_Email_** can cause unwanted trouble.

![keyboard-sc](https://user-images.githubusercontent.com/40264279/61127343-a0d35980-a4cc-11e9-85cb-910e31f32184.gif)

**Comment by netchampfaris** [comment]
https://github.com/frappe/frappe/pull/7893
