### ISSUE TITLE
Data importation permission not working.

### ISSUE THREAD

**Issue by vcnwafor** [frappe/erpnext#18303]
I created a user and made her the HR Manager, but she can't seem to do employee data importation using the importation tool and i have checked all permission settings to be correct.

**Comment by kennethsequeira** [comment]
Closing issue due to lack of concrete information for reproducing the error.

For allowing imports, a role should have access to:

1. Data Import access must be granted to that role (HR manager)

2. "Import" permission must be checked for the doctype, in this case, Employee.

**Comment by kennethsequeira** [comment]
Closing issue due to lack of concrete information for reproducing the error.

For allowing imports, a role should have access to:

1. Data Import access must be granted to that role (HR manager)

2. "Import" permission must be checked for the doctype, in this case, Employee.
