### ISSUE TITLE
Tax category issue while creating address for Supplier

### ISSUE THREAD

**Issue by crescent28** [frappe/erpnext#18322]
While creating PO --> Add supplier --> Add address --> Create new Address --> Tax category added in the Address 

Still the error prompt. 

![image](https://user-images.githubusercontent.com/41110073/61204871-111bee00-a70c-11e9-9393-9b9f69493a76.png)

**Comment by karthikeyan5** [comment]
![PO_bug_no_repro](https://user-images.githubusercontent.com/4847317/61382348-4110f000-a8ca-11e9-97c9-92c778ddaf87.gif)

i am Not able to Reproduce this issue. Please refer the GIF above.

**Comment by karthikeyan5** [comment]
closing this for now, since we are unable to replicate the issue.
