### ISSUE TITLE
[Project Portal] New task via Customer login

### ISSUE THREAD

**Issue by jaichavan** [frappe/erpnext#18335]
Steps to replicate:
1) Create a Project and provide access on the portal to the Customer.
2) Log in with customer credentials and try to create a new task in the Project

![project-portal](https://user-images.githubusercontent.com/40264279/61213641-3f58f800-a723-11e9-95e8-45c06a8d27d4.gif)

**Followup question: Customer doesn't have access to create a task, why is this option visible at all?**

**Comment by netchampfaris** [comment]
Cannot replicate on latest develop. Closing.

**Comment by porrello** [comment]
> Cannot replicate on latest develop. Closing.

I was able to replicate this issue, still can't solve it

**Comment by Katzen48** [comment]
Can replicate this to in version 13.
Why was this issue closed?
