### ISSUE TITLE
Email address not fetching from lead to opportunity in New Email button

### ISSUE THREAD

**Issue by farazk3** [frappe/erpnext#18336]
![image](https://user-images.githubusercontent.com/47382932/61370238-8ecc2f00-a8af-11e9-9b73-88625ad5d9d6.png)
When creating a Lead Email address is added. Once the Lead is converted to Opportunity in New Email button the email address from the Lead is not fetched refer Screenshot.

**Comment by netchampfaris** [comment]
https://github.com/frappe/erpnext/pull/18373
