### ISSUE TITLE
[Projects] Auto project name not fetched

### ISSUE THREAD

**Issue by jaichavan** [frappe/erpnext#18339]
Just like in the case of Expense Claims, and Task, when we try to create "Timesheet" via the project dashboard, the project name is not automatically fetched in the document. Inconsistency matters.

![project-not-auto](https://user-images.githubusercontent.com/40264279/61216389-dd9c8c00-a72a-11e9-8457-1d7ed64e3236.gif)

**Comment by netchampfaris** [comment]
https://github.com/frappe/erpnext/pull/18371
