### ISSUE TITLE
[What is what?] Very confusing Promotional Scheme

### ISSUE THREAD

**Issue by jaichavan** [frappe/erpnext#18333]
What does a "mixed condition" mean? What is "cumulative"? It is very hard to understand what this document does at first glance. Why is pricing rule a mandate for this? What does a scheme do differently that pricing rule doesn't? There is no way to understand with the minimal context. Perhaps, the **addition of some descriptions for these checkboxes and important actions** will help. I was not able to create one :-(

![image](https://user-images.githubusercontent.com/40264279/61212769-cf497280-a720-11e9-966e-91a894d365cf.png)

**Comment by rohitwaghchaure** [comment]
@jaichavan 

Please check below two links and check whether it will helped you to understand promotional schemes. If still not then we need to work on the documentation
https://erpnext.com/docs/user/manual/en/accounts/promotional-scheme
https://erpnext.com/docs/user/manual/en/accounts/pricing-rule
