### ISSUE TITLE
[Projects] Unwanted "," in report for dependent task

### ISSUE THREAD

**Issue by jaichavan** [frappe/erpnext#18342]
Steps to replicate:
1) Create 3 tasks. Make sure 1 of them is dependent on the other two.

![image](https://user-images.githubusercontent.com/40264279/61220773-a6cb7380-a734-11e9-8fa0-80da69b29aed.png)

2) Go to Report Builder: check the field, **Depends on Tasks**

![image](https://user-images.githubusercontent.com/40264279/61220719-87344b00-a734-11e9-9d68-6ba594f2dd10.png)

**Comment by netchampfaris** [comment]
@jaichavan **Depends On Tasks** is a hidden field used for internal logic. It is different from the **Dependent Tasks** child table.

Hidden fields are allowed to be viewed in Reports so that they are exportable.

**Comment by jaichavan** [comment]
Why is the extra comma there? @netchampfaris

**Comment by netchampfaris** [comment]
> @jaichavan **Depends On Tasks** is a hidden field used for internal logic. It is different from the **Dependent Tasks** child table.

As I clearly mentioned, it is a **hidden** field used in internal logic.
