### ISSUE TITLE
Upgrade from v9 to v11

### ISSUE THREAD

**Issue by younisalbadawi** [frappe/erpnext#18347]
Dears,

I have self hosted erpnext version 9.x.x develop. I would lik to switch it to master then upgrade it to v11 master.
How can I achieve this upgrade.? Please advise.

Please not that I tried different methods but no luck.

Regards

**Comment by aakvatech** [comment]
This question should go into discuss

**Comment by younisalbadawi** [comment]
How to move it to discussion as it's first time for me to post in gitub?

**Comment by umairsy** [comment]
You can directly create a new post on https://discuss.erpnext.com

**Comment by younisalbadawi** [comment]
Done thanks.
