### ISSUE TITLE
[Projects] Changing project template after the project creation causes inconsistency

### ISSUE THREAD

**Issue by jaichavan** [frappe/erpnext#18344]
Steps to replicate:
1) Create a new Project, say, Collection with project template "Vessel Repairs". This template has 4 tasks. Project Collection now has 4 tasks.

2) Now, change the template to another one, say, project template, "Fashion Collection"...it will update the project master as well as project templates (counter of how many have been created from that template) BUT IT DOESN'T ALTER THE TASKS! 
Project Collection still has tasks of Vessel Repairs!

![projecttemplate-project](https://user-images.githubusercontent.com/40264279/61224189-c1551b00-a73b-11e9-9af8-f80225a81606.gif)

So, we can either update the tasks as per project template updates (Only subject to: if the tasks/transactions don't exist against this project) OR not allow change after the project has been created from the template.

**Comment by netchampfaris** [comment]
https://github.com/frappe/erpnext/pull/18354
