### ISSUE TITLE
[Projects] Formatting of report in "Portrait" mode

### ISSUE THREAD

**Issue by jaichavan** [frappe/erpnext#18345]
Steps to replicate:
1) Open Projects -> Report: Project wise Stock Tracking
2) Click on Menu -> Print 
3) Select Orientation as Portrait

![report-error](https://user-images.githubusercontent.com/40264279/61225532-640e9900-a73e-11e9-8928-482a9e856cfc.gif)

**Comment by netchampfaris** [comment]
We can't prevent the selection of Portrait as it might be useful in some cases. The least we can do is show a warning.

https://github.com/frappe/frappe/pull/7917
