### ISSUE TITLE
[Projects] Standard Print Format has "user.full_name" instead of the name

### ISSUE THREAD

**Issue by jaichavan** [frappe/erpnext#18341]
The print format for Project doesn't display the full name. Since it is a "standard" format, please consider making it appropriate rather telling me to create a custom print format ;)

![image](https://user-images.githubusercontent.com/40264279/61220081-307a4180-a733-11e9-8460-12b5f3e7d959.png)

**Comment by netchampfaris** [comment]
https://github.com/frappe/erpnext/pull/18343
