### ISSUE TITLE
Manufacturer is missing in Item Master

### ISSUE THREAD

**Issue by harshit-30** [frappe/erpnext#18358]
In v11, we used to enter the Manufacturer of the Item inside the Item Master itself(refer the screenshot below), although the Manufacturer master exists. 
This is v11:
![image](https://user-images.githubusercontent.com/46772424/61286240-18143080-a7e0-11e9-9950-001456e4c511.png)

This is v12:
![image](https://user-images.githubusercontent.com/46772424/61286294-2e21f100-a7e0-11e9-938e-faac40736eb0.png)

**Comment by umairsy** [comment]
In version 12, this has been moved out of item master. Check "Item Manufacturer" doctype.
