### ISSUE TITLE
Letter Head: Based on is Image. But for Footer, it's HTML always

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#18363]
![photo_2019-07-16 17 05 46](https://user-images.githubusercontent.com/910238/61291478-40099100-a7ec-11e9-9338-0c05bef1059c.jpeg)

Even if image is selected, can we show preview right-away? Letter Head is very important doctype and preview of image will be important.

**Comment by rmehta** [comment]
These are not bugs, but missing features

**Comment by umairsy** [comment]
UI of Letter Head doctype is very crucial, specially from "new user on-boarding" perspective. Will be great if we can have better UI which allows preview and re-adjusting image size from UI itself.

**Comment by rmehta** [comment]
@umairsy not denying, but can't be classified as a "bug"

**Comment by netchampfaris** [comment]
@umairsy Using image for the header is a common use case. For the footer, it is usually text.

**Comment by netchampfaris** [comment]
@umairsy Let's focus on critical bugs before releasing v12. Removing this from milestone.
