### ISSUE TITLE
Mandatory fields in Child table to be displayed

### ISSUE THREAD

**Issue by crescent28** [frappe/erpnext#18367]
In Child table for all the doctypes, some mandatory fields are not seen and marked Mandatory ("Red")

The fields are not visible and not fetched until the fields are not prompted unless the forms are being saved. 

It would be better if the fields are displayed out in the form itself. 

![image](https://user-images.githubusercontent.com/41110073/61360072-499e0200-a89b-11e9-921c-50a148e6d72d.png)

**Comment by netchampfaris** [comment]
@crescent28 Which DocTypes? All DocTypes is a little too much to handle. Can you list down the doctypes so that I can fix them one by one?

**Comment by crescent28** [comment]
I will list the doctypes as and when found for the mandatory fields, as of now reported for the PR.

**Comment by Anurag810** [comment]
@netchampfaris it would be fixed for all doctypes.

**Comment by Anurag810** [comment]
it can be handled through customizing the form. then the user will be able to see and edit this through the grid view.
