### ISSUE TITLE
From Date - To date not working in leave application 

### ISSUE THREAD

**Issue by reema30** [frappe/erpnext#18377]
From date - To date in the default filters is not working. It works well when to click add filter. What is the use of these filters then? GIF attached.

![Leave application](https://user-images.githubusercontent.com/45488333/61378711-9eee0980-a8c3-11e9-907f-643d783bf0ec.gif)

Regards,
Reema

**Comment by reema30** [comment]
@scmmishra assigning it to you, since you will be doing solving the same one assigned in Frappe

**Comment by scmmishra** [comment]
@reema30 a fix for this is a work in progress. Will be solved soon. You can follow the PR here: https://github.com/frappe/frappe/pull/8121

**Comment by scmmishra** [comment]
It is possible to add a custom condition for standard filter, but it will be to implicit and might confuse users. The best course of action would be to remove those filters

**Comment by scmmishra** [comment]
Solved https://github.com/frappe/erpnext/pull/18696
