### ISSUE TITLE
'Qty is mandatory' even though Qty=1 when adding items by Barcode in Stock Entry

### ISSUE THREAD

**Issue by asem89** [frappe/erpnext#18372]
Hello,
I think I've found a minor bug in ERPNext v11 Production.

When adding Items to Stock Entry (f.e. Material Receipt) using a Barcode scanner and field 'Scan Barcode' I've encountered an error "Row 1: Qty is mandatory" right after scanning.
Problem is Qty field in table is already 1. 

User has to click on X to dismiss the warning about "Qty is mandatory" and then it can be left as 1 without issues.

In my opinion after scanning two things could/should happen:

1) by pressing ENTER after scanning:
a) fetch the Item by Barcode, 
b) erase "Scan Barcode" field,
c) keep the field selected to scan next Barcodes,
d) let the user fill all the info later.

2) by pressing TAB after scanning:
a) fetch the Item by Barcode,
b) open the Item details for filling Warehouse, Qty, etc, 
b') (please note user cannot confirm the entry in  table is over with ENTER on PC or Confirm on Mobile, he has to go up and click the Checkmark in upper right corner which is a nuisance)
c) after filling Item Details, erase the "Scan Barcode" field,
d) keep the field selected to scan next Barcodes.

Thanks for any insights. Sorry if I'm doing something wrong. Cheers!

**Comment by bghayad** [comment]
Hello @asem89 
I agree with you about this problem. But did you find any solution for it?
Regards
Bilal

**Comment by ankush** [comment]
Use the new "scan barcode" field on main form instead which takes care of correct qty updates for barcode, serial no and batch no too.

<img width="1106" alt="Screenshot 2022-03-28 at 1 48 46 PM" src="https://user-images.githubusercontent.com/9079960/160356241-93ad1a34-fdf8-4dd0-b196-1e769183a4e9.png">
