### ISSUE TITLE
Price List Entry Form and Report - Needs UoM

### ISSUE THREAD

**Issue by manojthandassery** [frappe/erpnext#1839]
When someone is revising the price of an item using the Price List form, he/she has no idea what the UoM for that item is. So easy mistakes can happen as some items may be in grams, and others in KG. Similarly the price list report needs to show the UoM as a column.

**Comment by Arundhatii** [comment]
UI Mock up
![mock up for default unit of measure for price list item](https://cloud.githubusercontent.com/assets/20164097/22148819/5f56e1f6-df36-11e6-8a9a-ffbe3ed8433a.png)

**Comment by SonaliBudhrani** [comment]
+1
