### ISSUE TITLE
[Projects] "Duplicate" Project no longer copies tasks

### ISSUE THREAD

**Issue by jaichavan** [frappe/erpnext#18390]
In v11, if you duplicate a project, the tasks of that project were copied as well. (Task child table) Tasks are not being copied in v12.
Tested on frappe.erpnext.com
Is this because we removed the child table in v12?
**Steps to replicate:**
1) Create a project with 4 tasks
2) Menu -> Duplicate

**Comment by netchampfaris** [comment]
@jaichavan I am not sure if tasks should be implicitly copied for Duplicate Projects. Removing "Duplicate" option also does not seem to be a good idea.
