### ISSUE TITLE
Item Tax Template Issues. Some points requires discussion

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#18394]
Issues verified by Nabin via online session

Item Tax Template:

- [ ] On selection of Tax account, tax rate is not fetched from Account master.
- [ ] Review how Item Tax Template and Tax Category will be patched for the existing user, so that itemised taxation is automated as earlier.
- [ ] Tax Category doesn't work if Company has multiple locations (say Maharashtra and Goa), and one Customer (based on Goa) could have both In-state and Out-state as Tax Categories (based on Company location). For now, we can define only one tax category for the Party.

**Comment by harshit-30** [comment]
@nabinhait I assume we can mark this as closed?
