### ISSUE TITLE
Not able to choose Issue Priority

### ISSUE THREAD

**Issue by harshit-30** [frappe/erpnext#18423]
The Issue Priority field does not allows to choose any other priority except Low.
![image](https://user-images.githubusercontent.com/46772424/61535095-008eaf00-aa4f-11e9-804b-c5e2321b4f34.png)

**Comment by harshit-30** [comment]
Functional issue, solved !

**Comment by AmmarAhmadKhan** [comment]
> Functional issue, solved !

 Hello there I am getting an error. If I set “Priority” while creating an issue manually or by importing, it does not set that “Priority” field, rather it sets the default Priority of SLA as the “Priority” of Issue.
 How can I change that ?
