### ISSUE TITLE
bug: POS Profile cost center set against taxes and charges

### ISSUE THREAD

**Issue by jigneshpshah** [frappe/erpnext#18438]
Environment : 
ERPNext: v11.1.48 (master)
Frappe Framework: v11.1.43 (master)

Step to Reproduce 

Step 1 : Create A POS Profile for a user and set cost center and taxes and charges as shown below
![image](https://user-images.githubusercontent.com/4900815/61590417-812be780-abd6-11e9-9520-1a23db796ac3.png)

Step 2:  Login with that user and Go to Sales Invoice , check"Include Payment (POS)"  true , user gets below error message 
![image](https://user-images.githubusercontent.com/4900815/61590427-d7008f80-abd6-11e9-917e-7f36f26b3741.png)

It seems system is trying to set cost center value against taxes and charges which is incorrect .  Also because of that Taxes and Charges Template for the user is also not getting fetched.

**Comment by rohitwaghchaure** [comment]
@jigneshpshah Thanks for reporting the issue, we have fixed the issue and tomorrow we'll release the fix.
