### ISSUE TITLE
Data Integrity Validation Tool

### ISSUE THREAD

**Issue by anandpdoshi** [frappe/erpnext#1848]
Since some validations were added later, old data might not have integrity. Hence, a tool might help fix these.

It could just be a report or a command line utility / repair tool.

For all records of a specified DocType:
- Check if Link Exists
- Check if Select Options are correct
- Check if Mandatory Fields are populated

**Comment by joezsweet** [comment]
@rmehta this sound more like a frappe framework issue, what about to move there?
