### ISSUE TITLE
v12 - Breaks Mobile and Tablet desktop access

### ISSUE THREAD

**Issue by ruhusobeje** [frappe/erpnext#18487]
We are using ErpNext on mobile and tablet devices at work
After upgrading to v12:

1. We are unable to click on any card on desk to access any module.
2. Scrolling the main page of desk drag-n-drops those cards instead of scroll.
3. The little arrow icon for option is also not clickable.

This also affects mobile apps, nothing is accessible on Mobile app now from desk.
We are fine if mobile app is broken. But for us mobile and tablet access os critical at work for our day to day usage of ErpNext.

**Comment by krnkris** [comment]
+ scroll is only works on the very left side
+ in email site the delete function not works

**Comment by sabranhameed** [comment]
Yes that's right. 

The cards are getting arranged during any scroll. Also the links are not clickable. The links are accessible only by opening in new tab.

**Comment by ruhusobeje** [comment]
@kennethsequeira 
Thanks. I saw you showed a video capture for mobile.
Do you know if there's a way to click icons on the desk in app/mobile?

**Comment by kennethsequeira** [comment]
@ruhusobeje 

just click on them!

If you're referring to scrolling, you will need to currently use the empty space to scroll until the fix is released

Closing the issue as the fix has been merged with https://github.com/frappe/frappe/pull/8067

**Comment by ruhusobeje** [comment]
@kennethsequeira 
ikr, it would have been good if it was that obvious!

The Desk is not clickable at all in app and mobile browsers. 
Like the one pointed on forums recently 
https://discuss.erpnext.com/t/v12-menu-button-not-usable-mobile/51411

Please find attached screen record.


![erpnext](https://user-images.githubusercontent.com/36888881/62414899-a6b1eb80-b5ef-11e9-8cc7-009e9993c80a.gif)

**Comment by krnkris** [comment]
The developers work on it:

https://github.com/frappe/frappe/issues/8067

**Comment by ruhusobeje** [comment]
@krnkris 
Thanks for pointing. I think that pull request is only for disabling scroll.

**Comment by kennethsequeira** [comment]
@ruhusobeje 

have added your gif with another recording here: https://github.com/frappe/frappe/issues/8099

**Comment by krnkris** [comment]
Can confirm, it is just works on IOS:

https://github.com/frappe/frappe/issues/8099#issuecomment-518179657

Installed Apps

ERPNext: v12.0.4 (version-12)

Frappe Framework: v12.0.4 (version-12)

**Comment by ruhusobeje** [comment]
@kennethsequeira 
We just deployed latest version to our servers.
erpnext 12.1.8
frappe 12.0.18
This issue still persists. Sadly, users cannot work from desk on mobile.
