### ISSUE TITLE
illegal template

### ISSUE THREAD

**Issue by cyruschiu123** [frappe/erpnext#18483]
![Screen Shot 2019-07-25 at 3 56 12 pm](https://user-images.githubusercontent.com/23039225/61856721-4cc96b80-aef5-11e9-9e0a-1e5f8978870a.png)

On the print windows, it suddenly showed "illegal template" and fail to download the pdf. Everything is normal 5 mins before. I tried to reload/restart the computer and website it still happens. Please fix the issue.

**Comment by kennethsequeira** [comment]
The issue was fixed some time back. Kindly pull the latest changes and check.
