### ISSUE TITLE
Installation fails due to conflicting pandas version

### ISSUE THREAD

**Issue by NeolithEra** [frappe/erpnext#18526]
## Issue description

Hi, users are unable to run erpnext due to dependency conflict with _**pandas**_ package. 

As shown in the following full dependency graph of **_erpnext_**, **_erpnext_** requires _**pandas**_ (the latest version)，while **_frappe_** requires _**pandas==0.14.1**_.

According to pip’s “first found wins” installation strategy, _**pandas==0.25.0**_ is the actually installed version. However, _**pandas==0.25.0**_ does not satisfy _**pandas==0.14.1**_.

### Dependency tree-------
```
erpnext(version range:)
| +-frappe(version range:)
| | +-click(version range:==3.3)
| | +-django(version range:==1.7.1)
| | +-django-cors-headers(version range:==0.13)
| | +-django-docopt-command(version range:==0.2.0)
| | +-django-health-check(version range:==1.0)
| | +-djangorestframework(version range:==2.4.2)
| | +-docopt(version range:==0.6.2)
| | +-futures(version range:==2.1.6)
| | +-mozilla-logger(version range:==0.2)
| | +-mysql-python(version range:==1.2.5)
| | +-pandas(version range:==0.14.1)
| | +-python-dateutil(version range:==2.2)
| | | +-six(version range:)
| | +-python-memcached(version range:==1.53)
| | +-pytz(version range:==2014.7)
| | +-raven(version range:==5.1.1)
| | +-six(version range:==1.4.1)
| | +-uwsgi(version range:==2.0.8)
| +-unidecode(version range:)
| +-pygithub(version range:)
| +-googlemaps(version range:)
| +-python-stdnum(version range:)
| +-braintree(version range:)
| +-gocardless_pro(version range:)
| +-woocommerce(version range:)
| +-pandas(version range:)
| +-plaid-python(version range:)
| | +-requests(version range:>=2.7.0)
```

Thanks for your help.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Suggested solutions

1.	Fix your direct dependency to be **_pandas==0.14.1_**. I have checked this revision will not affect your downstream projects now.
2.	Ask your upstream project **_frappe_** to loose the version range to **_pandas>=0.14.1_**.

Which solution do you prefer, 1 or 2?

@rohitwaghchaure Please let me know your choice. I can submit a PR to solve this issue.

**Comment by Anurag810** [comment]
Yeah, go-ahead raise a PR it will be reviewed and merged accordingly.

**Comment by heyakyra** [comment]
This is too old and won't allow the app to be installed #22424
