### ISSUE TITLE
Error when trying to access CoAs from Company master

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#18521]
Steps:

1. Open Company
2. View > Chart of Accounts

<img width="1268" alt="Screenshot 2019-07-29 at 6 53 36 PM" src="https://user-images.githubusercontent.com/910238/62052189-a2be4c00-b232-11e9-82bb-a054c450457f.png">

This is pretty consistent when you create a new Company and then accessing it's Chart of Accounts

**Comment by Anurag810** [comment]
@umairsy 
I just Created new company **Selco Foundation** and then tried to Replicate the issue but not able to replicate here is the working GIF
![Working Fine](https://user-images.githubusercontent.com/32095923/62104591-a0550400-b2bd-11e9-858c-4e36fcb43b1f.gif)
Can you please check once
