### ISSUE TITLE
Fifth user

### ISSUE THREAD

**Issue by Alhessan** [frappe/erpnext#18551]
the fifth user is not add on my company profile what ever the email is

**Comment by kennethsequeira** [comment]
@Alhessan please be more precise regarding what this question is about. It doesn't seem like a bug which is what is tracked here.

Perhaps you are better served by posting on the [forum](https://discuss.erpnext.com)

**Comment by Alhessan** [comment]
![tempsnip](https://user-images.githubusercontent.com/22369708/63076617-7d258800-bf3e-11e9-8f07-bedad9e749da.png)

I have 5 users plan on erpnext , I added 4 , then i could not add  the fifth one.

**Comment by kennethsequeira** [comment]
Check if you have multiple sessions on for any of the user:

![image](https://user-images.githubusercontent.com/33246109/63076968-7570de00-bf54-11e9-810d-4ba2f6e334b3.png)

If you haven't increased the sessions, then contact the support team

**Comment by Alhessan** [comment]
I checked them all, none of them has multiple sessions,
How i can contact them??

**Comment by Alhessan** [comment]
@kennethsequeira  thank you sir, solved
