### ISSUE TITLE
Printing & Emailing on Mobile App, and on Mobile Browser & Creating, say, a quotation from lead on Mobile App, and on Mobile Browser - Version 12

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#18554]
The Menu, and Create menu buttons are not responding on mobile app, and on mobile browsers

**Comment by krnkris** [comment]
The Delete not responding as well

**Comment by govindsmenokee** [comment]
Nothing within any of the menu is clickable

**Comment by netchampfaris** [comment]
https://github.com/frappe/frappe/pull/8090

**Comment by muchai** [comment]
This is not resolved yet.

**Comment by krnkris** [comment]
I confirm the drop down Menu buttons not responds.
May be it is not merged and will be only build in to the next version-fix?

**Comment by hfaridgit** [comment]
I have same problem with version 12.0.6 on firefox on linux 16.04 desktop.

**Comment by krnkris** [comment]
Thx @hfaridgit 
https://discuss.erpnext.com/t/version-12-menu-items/51792
it was made 2 days ago. it is not merged jet:
https://github.com/frappe/frappe/commit/4353d21f2e5c781854cea029b6df01819a74a664
