### ISSUE TITLE
IN V12 ,Point Of Sale +Create New Customer Not Coming,Any help please

### ISSUE THREAD

**Issue by venku31** [frappe/erpnext#18562]
![POS](https://user-images.githubusercontent.com/29224707/62347636-f91fd900-b517-11e9-957e-a244ec5790e5.png)

IN V12 ,Point Of Sale +Create New Customer Not Coming,Any help please

**Comment by rohitwaghchaure** [comment]
Fixed https://github.com/frappe/frappe/pull/8154
