### ISSUE TITLE
Getting Python errors in Browser Console

### ISSUE THREAD

**Issue by linuxamination** [frappe/erpnext#18578]
If I try to do an action which is not allowed, it gives me python errors in browser console. The browser console should show js/css client side errors and warnings and not the path of server side files and their location.

I have tried same url in online demo site and it is giving me same python errors in browser console.
https://manufacturing.erpnext.com/desk#Form/User/Guest

https://08c8e6d1-a-62cb3a1a-s-sites.googlegroups.com/site/abridgescreenshots/abridge/erpnext-browser-console-error.png

 It has become a security issue for me as I do not want to disclose server side files name to the client.

Is it something I am doing wrong or you will fix this in next release? Please help.

**Comment by kennethsequeira** [comment]
It's the case of it being a _feature not a bug_.

If the error has been handled, it will show up as a message with the traceback in the console as in your case, or show up the error prompt with an option to report it:

![image](https://user-images.githubusercontent.com/33246109/62593376-1ed02800-b8f4-11e9-8ccb-63da056dffbd.png)

Clicking on the report button shows the whole error traceback while the initial message itself shows the final error message (Something like "error in table xxxxx column yyy not found")

The error tracebacks are key to help to debug an issue and tap unhandled exceptions for the developers and the maintenance team. This has always been the case and it is not a recently introduced bug.

As for users not seeing the server-side files, the whole codebase is available online 😉. 

If you'd like to have a broader discussion around this, I would suggest starting a thread on the ERPNext forum: https://discuss.erpnext.com.
