### ISSUE TITLE
Manufacturing (V12) error

### ISSUE THREAD

**Issue by abdelrahmanfakhry** [frappe/erpnext#18586]
When starting the work order the stock entry created to transfer material from raw warehouse to work in progress warehouse didnt fetch the items from the BOM and gives me this error "All items have already been transferred for this work order

**Comment by rohitwaghchaure** [comment]
@abdelrahmanfakhry can you please share the following details

- Which option you have selected for the "Backflush Raw Materials Based On" in the manufacturing settings?

- Do you have set the operation in the BOM?

**Comment by rohitwaghchaure** [comment]
@abdelrahmanfakhry Fixed https://github.com/frappe/erpnext/pull/18686
