### ISSUE TITLE
Parameters are not showing up while adding webhook

### ISSUE THREAD

**Issue by SunilKrishnan** [frappe/erpnext#18581]
Parameters are not showing up while adding web-hook in the latest code as on 3rd Aug. This is newly introduced bug

Go to New Web hook

Try to add a parameter to sent along with URL. Parameters are not showing automatically

**Comment by SunilKrishnan** [comment]
parameters like expected start date, expected end date are not showing in the drop down list while adding a webhook.  This was working fine in previous release. Its a regression issue.

**Comment by kennethsequeira** [comment]
@SunilKrishnan what version is this popping up on?

**Comment by SunilKrishnan** [comment]
Latest version development

**Comment by SunilKrishnan** [comment]
I have seen this issue as on 6th aug. This is a regression issue. We tried
to installation multiple times

**Comment by niklaserik** [comment]
We're facing the same issue with with version v12.0.7.

**Comment by clarkejj** [comment]
https://discuss.erpnext.com/t/parameters-like-expected-start-date-expected-end-date-are-not-showing-in-the-drop-down-list-while-adding-a-webhook-this-was-working-fine-in-previous-release-its-a-regression-issue/51547

**Comment by revant** [comment]
This should have fixed the issue?

https://github.com/frappe/frappe/pull/9171
https://github.com/frappe/frappe/pull/9172

Re-open issue if it persists
