### ISSUE TITLE
Error when creating quotation from opportunity-ERPNext: v11.1.52 (version-11)

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#18593]
![image](https://user-images.githubusercontent.com/1822868/62447337-d71f9400-b76d-11e9-8e2f-f0ab2176dbf4.png)

**Comment by clarkejj** [comment]
Try this https://discuss.erpnext.com/t/attributeerror-quotation-object-has-no-attribute-customer/49378/11

If that fails copy and paste your traceback to discuss for others to review.
