### ISSUE TITLE
bug: Customer list doesn't populate based on parent territory filter

### ISSUE THREAD

**Issue by jigneshpshah** [frappe/erpnext#18598]
### Environment
ERPNext: v12.0.4(version-12)
Frappe Framework: v12.0.4 (version-12) 

### Use case : To get the list of the customer territory wise

**Actual Behavior  :** 
Customer List doesn't populate based on parent territory selection in the filter
Steps : 

**Territory Tree**
![image](https://user-images.githubusercontent.com/4900815/62460752-7d848d00-b7a0-11e9-93d5-bc50ab4f2699.png)

**Customer List**
![image](https://user-images.githubusercontent.com/4900815/62460871-ca686380-b7a0-11e9-8820-d99367520af6.png)

Apply filter on Customer List for **WEST** Territory in Standard Filter
![image](https://user-images.githubusercontent.com/4900815/62460896-e66c0500-b7a0-11e9-9bec-5e3b7e047b92.png)

OR
Apply filter on Customer List for **WEST** Territory in normal filter.

![image](https://user-images.githubusercontent.com/4900815/62461283-fe905400-b7a1-11e9-9c9b-e2a936b5d941.png)

**Expected Behavior**
Customer List should be populated based on selection of parent value for territory.
 
This applies to all cases, having link doctypes with tree structure.
e.g. Customer Group

**Comment by AndyOverLord** [comment]
Hello, any updates regarding this issue. Had the same problem. Please help.

**Comment by AndyOverLord** [comment]
If we can't fix the bug right now, can we at least empty the default territory filter so that every customer record will be displayed! Thanks, didn't find a way to change the default territory filter.

**Comment by harshit-30** [comment]
Please create another issue if it is replicable after v13.10.
