### ISSUE TITLE
Bank Transactions - Import OFX

### ISSUE THREAD

**Issue by jboilesen** [frappe/erpnext#18602]
ERPNext should import bank transactions from bank statements OFX files to reduce human error in CSV files.

OFX is an international open markup file type designed to describe financial transactions.

**Comment by clarkejj** [comment]
https://discuss.erpnext.com/t/bank-transactions-import-from-ofx/51438

**Comment by dannykapasa** [comment]
Eagerly waiting for this feature, which is a big miss for ERPNext at the moment.

**Comment by jboilesen** [comment]
This issue is the same as #4918
