### ISSUE TITLE
upload statement in bank reconcillation

### ISSUE THREAD

**Issue by parthdt** [frappe/erpnext#18606]
I can't upload a statement in open bank reconciliation page.
Also, the upload and reconcile options pop up twice and sometimes more.
![Screenshot from 2019-08-06 17-46-12](https://user-images.githubusercontent.com/36564245/62539619-49c66780-b873-11e9-8de8-78d1873f3951.png)

Please do help me out.

**Comment by clarkejj** [comment]
See discussion here https://discuss.erpnext.com/t/cant-upload-bank-statements-in-bank-reconcillation/51577

**Comment by pujanthakkar** [comment]
Need Help on this..

**Comment by Mitchy25** [comment]
Console shows an error when the page is trying to show the 'Upload' dialog. Really need this one to work :(

**Comment by AndyOverLord** [comment]
Had the same problem, The console said "frappe.upload is not defined", someone please help.

ERPNext discuss: https://discuss.erpnext.com/t/cant-upload-bank-statements-in-bank-reconcillation/51577

**Comment by Mitchy25** [comment]
Have submitted a pull request that fixes this: https://github.com/frappe/erpnext/pull/19182
