### ISSUE TITLE
Payment Reconciliation - Error - V12

### ISSUE THREAD

**Issue by sethu07** [frappe/erpnext#18620]
Match payment with invoice error, when i click "Get Unreconciled entries". Screenshot attached for reference.
![Screenshot (1)](https://user-images.githubusercontent.com/14884539/62608086-d1b47c00-b91c-11e9-86d5-9e37dbe76831.png)

**Comment by rodrigoinformationsys** [comment]
Same error here.
https://discuss.erpnext.com/t/v12-cant-make-reconciliation-work/51545/4

**Comment by sethu07** [comment]
I think it will come when i select "Supplier" in Party Type.

**Comment by rodrigoinformationsys** [comment]
Removing this line made it work again but probably it isn't the "correct" solution for it.

https://github.com/frappe/erpnext/blob/9335cdd536c6ce6ed0723ed9be62d0baa59fe9e6/erpnext/accounts/doctype/payment_reconciliation/payment_reconciliation.py#L96

**Comment by rodrigoinformationsys** [comment]
So, i think it is already fixed.
https://github.com/frappe/erpnext/pull/18657
