### ISSUE TITLE
Supplier field not populated in Serial No when it is created upon receipt of Asset

### ISSUE THREAD

**Issue by jaichavan** [frappe/erpnext#18624]
Steps to replicate:
1) Create an Item and enable "Is Fixed Asset" & "Serial No" during creation.
2) Create a Purchase Receipt for this item, enter Asset Location, save & submit the document. Upon submission of PR, Asset and Serial No records are auto-created
**However, the Supplier field is not populated in the Serial No record (It should have fetched this from the PR)**

Purchase Receipt:

![image](https://user-images.githubusercontent.com/40264279/62613236-b484ab00-b926-11e9-9ce0-b8da0620d374.png)

Serial No:

![image](https://user-images.githubusercontent.com/40264279/62613510-3543a700-b927-11e9-9c0c-0caeba23972f.png)

**Comment by nextchamp-saqib** [comment]
[Fix](https://github.com/frappe/erpnext/pull/19163)
