### ISSUE TITLE
Split issue doesn't reset SLA

### ISSUE THREAD

**Issue by jaichavan** [frappe/erpnext#18621]
Steps to replicate:
1) Try to split an issue to create a new thread
2) The SLA level (Fulfilled/Failed) of the original issue is also copied in the new issue thread. 

Suggestion: Consider resetting the field called "First Response On" field in the new issue thread that is created upon splitting the original issue

**Comment by deepeshgarg007** [comment]
@jaichavan  Closing this issue. If the issue still persists in the latest version-13 or above then please reopen a new issue
