### ISSUE TITLE
Asset category: Unwanted "Depreciation Start Date" field displayed

### ISSUE THREAD

**Issue by jaichavan** [frappe/erpnext#18622]
This field, "Depreciation Start Date" is displayed in the Asset Category master unnecessarily. It cannot be populated here anyway.

Asset Category:

![image](https://user-images.githubusercontent.com/40264279/62612220-9c139100-b924-11e9-9311-2a8d8eae0304.png)

Upon expanding child table, Finance Books:

![image](https://user-images.githubusercontent.com/40264279/62612294-be0d1380-b924-11e9-8f8c-b884d40195b4.png)

**Comment by deepeshgarg007** [comment]
@jaichavan  Closing this issue. If the issue still persists in the latest version-13 or above then please reopen a new issue
