### ISSUE TITLE
Feature request: Link to items in email reminders

### ISSUE THREAD

**Issue by acumensec** [frappe/erpnext#1863]
I love the daily and weekly reminders. However it would be helpful to provide links to items so that they are easily accessible. For example I get reminders of when to follow up on leads. However if a link to the lead is provided via the email, I can immediately click on it and make updates (e.g. next follow up date)

**Comment by Arundhatii** [comment]
you can use the get_url method to set url in email alert message.

e.g. {{ doc.get_url() }} 
Closing this for now. Please feel free to reopen if its important.
