### ISSUE TITLE
Allow multiple logins per user without counting against max user subscription

### ISSUE THREAD

**Issue by lxnow** [frappe/erpnext#18640]
There are use cases where having a user such as an admin be allowed to do multiple logins under user's security settings. Right now this requires a higher subscription plan (additional user license) which doesn't seem necessary and prohibitive to deployment/ troublehsooting or just plain old multiple simultaneous usage by power users.

![image](https://user-images.githubusercontent.com/5035210/62625626-2d502b00-b958-11e9-8cb8-16dc0bea72d2.png)

**Comment by kennethsequeira** [comment]
@lxnow Github issue is to report software bugs and not the pricing of erpnext. For that, you can contact the [team](https://erpnext.com/contact-us) directly.
