### ISSUE TITLE
v12 - Employee Auto Checkin Not linked to Shift Type

### ISSUE THREAD

**Issue by govindsmenokee** [frappe/erpnext#18674]
When trying to create an employee checkin from shift type screen it is not linking the employee checkin to shift type

**Comment by clarkejj** [comment]
Please also post this to discuss for folks there to benefit too thanks!

**Comment by ruchamahabal** [comment]
Shift in employee checkin is based on the checkin timing. Shift is set in the checkin only if the timestamp falls in the shift period and employee has a valid Shift Assignment / Default Shift set
