### ISSUE TITLE
Production ready question!

### ISSUE THREAD

**Issue by davegreeko2023** [frappe/erpnext#18698]
Hello All,
First time here and many thanks for such a great project. I have two questions regarding frappe and database integration. Do you think the Postgres support is considered production ready? and lastly, has the FrappeJs framework been used in production? I noticed there are no activities related to FrappeJs project on GitHub and last commit was back in February.

Regards,
Dave

**Comment by rmehta** [comment]
Postgres will not work for ERPNext, works for Frappe Framework only.

FrappeJS is under active development (again) and there will be a bunch of updates in the next few weeks.

**Comment by davegreeko2023** [comment]
Thanks for the clarifications. I'm new to both Frappe & ERPNext but exploring both projects was like reading poetry: you can't believe the succinctness and elegance that can be expressed in so little space.

**Comment by dulhaver** [comment]
> Postgres will not work for ERPNext, works for Frappe Framework only.

is there any active development to get frappe/erpnext fully PostgreSQL ready?
