### ISSUE TITLE
v12 - All emails generated by ERPNext contain no body - TESTED: able to successfully send email directly with sendmail from command line

### ISSUE THREAD

**Issue by nostahl** [frappe/erpnext#18690]
We have a fresh easy install ERPNext server that we have setup office 365 email connector too. We are able to send emails now ie from a sales order or lead etc but they arrive with no message body. (email client reports the email has no content)

We have tracked down the entire chain to ERPNext itself as the problem as we are able to successfully send emails via the command line through sendmail directly.

just minutes ago we ran bench update and everything is fresh and still having the same issues.

**Comment by nostahl** [comment]
still at it trying to diagnose this myself. no new news.

**Comment by clarkejj** [comment]
See this discussion https://discuss.erpnext.com/t/email-sent-from-erpnext-arrive-with-no-message-body/51717/19

**Comment by nostahl** [comment]
I've fixed the issue. I'll be writing an article / tutorial on how to setup ERPNEXT and Office 365 integration.

**Comment by RJPvT** [comment]
Where was the problem ? i am running into the same trouble

**Comment by genesis81** [comment]
I'm also have the same problem, any fix?
Greets Marco
