### ISSUE TITLE
Gross Profit is not recalculated on Sales Order Quantity Update

### ISSUE THREAD

**Issue by Mitchy25** [frappe/erpnext#18723]
The calculation of Gross Profit on the Sales Order Item does not re-run when you update the item Quantity via 'Update Items' button at top of Sales Order

Details:

Item Sell Price: $10
Item Cost: $5

* Initially:
   * Quantity Ordered: **10 Units**
   * Sale Price: $10/Unit
   * Total Sale: $100
   * Per Unit Cost: $5
   * Total Cost: $50
   * Gross Profit: $50

* Update Quantity
   * Quantity Ordered: **5 Units**
   * Sale Price: $10/Unit
   * Total Sale: $50
   * Per Unit Cost: $5
   * Total Cost: $50
   * Gross Profit: Should be $0 (But stays at $50)

GIF:

![Gross Profit](https://user-images.githubusercontent.com/42224026/62986231-ae467f80-be8e-11e9-953b-e5b2f6c64877.gif)

**Comment by clarkejj** [comment]
Please report this also on discuss for folks there to tackle and add a link to that here...

thanks!

**Comment by Mitchy25** [comment]
Thanks @clarkejj. Posted to Discuss. Link is: https://discuss.erpnext.com/t/gross-profit-is-not-recalculated-on-sales-order-quantity-update/51832

**Comment by AndyOverLord** [comment]
Any updates regarding this issue. Had a similar problem.

Thanks!
