### ISSUE TITLE
Serial No Redesign

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#1872]
- [ ] Single SLE for each Serial No
- [ ] Valuation / transfer based on SLE
- [ ] Patch to split existing SLE

---
#### Serial No Valuation Repair Tool (temp)
- New App
- [ ] Report where incoming rate != valuation rate for Serial Nos -> Repair via Stock Entry

**Comment by joezsweet** [comment]
@rmehta is this still needed on v. 8?

**Comment by rmehta** [comment]
Yeah this is still pending!

**Comment by rmehta** [comment]
This is still relevant - one major refactor is due.

**Comment by harshit-30** [comment]
Reopening this after having a talk with @ankush 

Cc. @sharmanakul
