### ISSUE TITLE
Version 12 - Auto attendance not working

### ISSUE THREAD

**Issue by pujanthakkar** [frappe/erpnext#18725]
I have created Employee Check In record by Data Import Tool, after successful Import when I go to Shift Type and Click "Mark Auto Attendance" attendance is not being marked.

**Comment by clarkejj** [comment]
Discussion here https://discuss.erpnext.com/t/version-12-auto-attendance-issue/51810

**Comment by pujanthakkar** [comment]
Any update on this

**Comment by Vigneshsekar** [comment]
Hi,

Did you set the following fields appropriately?

Attendance will be marked automatically only after the `Process Attendance After` date. Also, the `Last Sync of Checkin` is until when you would like the check-in logs to be considered.

You might also need to make sure if the employee check-ins are within the shift time + allowed extra time.

After setting them, try to mark the auto attendance. Let us know if that works.

![screenshot](https://user-images.githubusercontent.com/11339902/63343940-dfcab980-c36c-11e9-84a2-1f1c73511ce9.png)

**Comment by camsunit** [comment]
Hi, One our clients is still facing the same issue,   We have updated **Attendance After** and **Last Sync of Checkin**, but not report is generated for attendance. We could see the entries only in CheckIn List

**Comment by mahendrarohit** [comment]
Hi, we also facing problem in "Mark Auto Attendance" 
I create 1) Shift Type (with Process Attendance After and Last Sync of Checkin )
             2) Shift assignment 
             3) Manually enter Employee check in Time as define in Shift Type

**Comment by Ponyooooo** [comment]
Any update with regards to the manually creation of employee checkin? How will the auto creation attendance will work?

**Comment by sinhpn92** [comment]
Hello @mahendrarohit  @pujanthakkar Did you resolve this issue?
