### ISSUE TITLE
Delivering via multiple batch

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#1873]
Currently, only one Batch Id for an item can be selected in Delivery Note / Sales Invoice. Customer might be delivering Sales Order qty from multiple Batches.

When select Batch Id, Actual Qty of item for that Batch should be shown.

**Comment by sbkolate** [comment]
@umairsy @rmehta
I have added custom field in Delivery Note Item and Sales Invoice Item.
When we select Batch No, Actual Qty of item for that Batch will be shows in custom field.
 custom field is "Available Qty of Batch at Warehouse"

Also we can give pop-up window if available qty is less than ordered qty.

Let me know, is this full solution of this issue.

**Comment by umairsy** [comment]
@sbkolate go ahead from our end.

Thanks for your contribution.

**Comment by umairsy** [comment]
Divide item qty in two rows. For the second item, re-select item in the Delivery Note and select another batch no.
