### ISSUE TITLE
Purchase Receipt qty check needs to check rejected qty

### ISSUE THREAD

**Issue by cgpurbaugh** [frappe/erpnext#18741]
When updating Accepted Qty to 0 and Rejected Qty to the full balance, we are unable to save with the error "Item quantity can not be zero".  This validation should check the rejected qty as well.

ERPNext: v11.1.52 (version-11)
Frappe Framework: v11.1.48 (version-11)

**Comment by marination** [comment]
https://github.com/frappe/erpnext/pull/19781 fixed
