### ISSUE TITLE
Issue with chat in V12

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#18748]
Hi ,

Sending a chat message or sometimes, even trying to start a chat, throws the following error:

`TypeError: the JSON object must be str, bytes or bytearray, not 'NoneType'
`

Kindly help fix asap 

Thanks

**Comment by szufisher** [comment]
same error in my case.
Installed Apps

ERPNext: v12.0.6 (version-12)

Frappe Framework: v12.0.6 (version-12)
