### ISSUE TITLE
Error when enabling Hospitality Domain from Domain Settings

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#18756]
<img width="1304" alt="Screenshot 2019-08-16 at 10 14 29 AM" src="https://user-images.githubusercontent.com/910238/63144037-b3cad380-c00e-11e9-9dcd-296370da5cc3.png">

**Comment by scmmishra** [comment]
Hello @umairsy I was successfully able to enable the Hospitality domain on my test account on develop branch. I tired conditions of enabling that domain only, as well as tried enabling it, when other domain was enabled. Can you also add the complete error log from this account for me to debug it.

**Comment by umairsy** [comment]
v12on.erpnext.com is an account on our cloud. Now when I see Domain Settings, Hospitality is checked, but on the Desk, I don't see any icon relevant to that. Can you sign-into this account as admin and check?
