### ISSUE TITLE
Settings for branding ERPNext

### ISSUE THREAD

**Issue by idolaru** [frappe/erpnext#18758]
In our business we begin creating a space for our agents, suppliers and business partners to interact directly and more automatically with our company through ERPNext.

Of course, this brings the necessity of of branding and how we would like to hide in many ways the system that we are using as well as show professionalism hence the question of branding settings such as:

1. Favicon
2. Company logos to replace all ERPNext logos
3. Footer settings for general erpnext views

Feel free to continue the list, perhaps even general colors around the system could be adjusted.

**Comment by barredterra** [comment]
- Favicon can be set in Website Settings
- Whitelabeling: probably not going to happen. See [here](https://frappe.io/blog/general/why-you-should-not-rebrand-erpnext)
- Footer for the customer portal can be set in Website Settings

**Comment by idolaru** [comment]
You miss the point regarding whitelabeling. I am not a company selling software, I am the owner of a company using ERPNext for daily operations.

How do you think it looks when one of my business partners visits our portal and sees logos which are not of my company ? 

And also, why would any of my business partners know what type of system I use ? this can be easily done, whitelabeling for companies who use erpnext as production not for selling.

**Comment by kennethsequeira** [comment]
Closing another the thread. Unncessary discussion on whitelabelling. 

@idolaru here's a fun fact, you're probably not the only company using this for production and not selling. 

As for internal usage, on the desk side, the logo can be updated in the navbar with [this setting](https://github.com/frappe/frappe/pull/11322). You'll find plenty other discussion threads to override the default branding options.
