### ISSUE TITLE
v12 Task Opening - InternalError: (1054, u"Unknown column 'e7c4dfab28' in 'field list'")

### ISSUE THREAD

**Issue by idolaru** [frappe/erpnext#18759]
When opening an already existing task created in v11 - now in v12 the error appears:

InternalError: (1054, u"Unknown column 'e7c4dfab28' in 'field list'")

Installed Apps

ERPNext: v12.0.5 (version-12)

Frappe Framework: v12.0.5 (version-12)

**Comment by Mitchy25** [comment]
This has been merged into version-12-hotfix: https://github.com/frappe/frappe/pull/8184
