### ISSUE TITLE
website Item group page error in V12

### ISSUE THREAD

**Issue by erpcloudsystems** [frappe/erpnext#18769]
i`v upgraded to v 12.0.6 but suddenly 

Website item group page 

Item web page 

has many errors in url and css 

please check

https://mycilek.com/products/teens-rooms/dynamic

**Comment by amitsaxena01** [comment]
This issue was reported vide 
https://github.com/frappe/erpnext/issues/18190
and a pull request for fix was requested vide fix: https://github.com/frappe/erpnext/pull/17665

However nobody cares and it was allowed to close without merge.

-Amit

**Comment by erpcloudsystems** [comment]
and what about the duplication of item group in URL ??

**Comment by backendoadmin** [comment]
I think there is a workaround:

Do not leave empty description fields under WEBSITE SPECIFICATIONS section. If you have an item related description above, that's not enough!.

https://prnt.sc/ov4b49

**Comment by erpcloudsystems** [comment]
what is the relation between them ???

will it fix URL issue ??

**Comment by erpcloudsystems** [comment]
Solved by re edit item group route manually
