### ISSUE TITLE
v12 Event Doctype update - InternalError: (1054, u"Unknown column 'start' in 'field list'")

### ISSUE THREAD

**Issue by idolaru** [frappe/erpnext#18788]
Earlier I was in `set-config developer_mode 1` logged in with the Administrator, activating the Show Preview Popup in the Event Doctype, View Settings.

After saving the setting I went to view the calendar and this error popped up without loading the events: `InternalError: (1054, u"Unknown column 'start' in 'field list'")`

Refreshing the page reloads the calendar and events properly without the error.

Also, the show preview popup does not work!

**Comment by Mitchy25** [comment]
Merged into Version-12-hotfix: https://github.com/frappe/frappe/pull/8184
