### ISSUE TITLE
Medical Record of Patient Not Showing in Healthcare

### ISSUE THREAD

**Issue by Umer2560** [frappe/erpnext#18783]
Hello can any 1 please tell why the medical record of patient not showing in healthcare module of erpnext v.11 and v.12 both..
Thanks in advance....

![Screenshot (3)](https://user-images.githubusercontent.com/33193371/63272112-e695f580-c2b4-11e9-8db2-cc005a7611cc.png)

**Comment by crescent28** [comment]
@ruchamahabal can you check into this issue?

**Comment by crescent28** [comment]
@Umer2560 The Medical Record is now Patient History doctype as below: 
![IMAGE 2020-02-06 14:30:41](https://user-images.githubusercontent.com/41110073/73921390-4167eb80-48ed-11ea-9c38-fab6aabe7352.jpg)
