### ISSUE TITLE
Organizational Chart Page

### ISSUE THREAD

**Issue by Tropicalrambler** [frappe/erpnext#18819]
Create a page style view where users can visualize an automatically-generated organizational chart, with a better visualization than the standard tree view.

This organizational chart can allow changing positions in the chart.
Each employee box allows connection to a card-like pop-up or dialog with further information as per ERPNext held-data. 

User can download information as vcard file, to import directly into Android, iPhone, or other contact management system.  

Links take users to their social media profiles for work or personal (if listed) (Twitter, LinkedIn, Etc.)

**Comment by idolaru** [comment]
Hands up here. A very good idea.

**Comment by kennethsequeira** [comment]
@Tropicalrambler can you post any visual references we can look at since there are no standardized ways of making an org chart.

**Comment by xickomesquita** [comment]
If @Tropicalrambler don't mind:

![image](https://user-images.githubusercontent.com/38265198/74953286-4003ec00-53e0-11ea-8c14-961a1d991b95.png)

![image](https://user-images.githubusercontent.com/38265198/74953315-47c39080-53e0-11ea-812c-b6bd9fdb7d41.png)

![image](https://user-images.githubusercontent.com/38265198/74953359-57db7000-53e0-11ea-86b1-3954cd011ac6.png)

![image](https://user-images.githubusercontent.com/38265198/74953410-63c73200-53e0-11ea-9ef2-ea4eb614b3d4.png)

**Comment by saarthakgupta** [comment]
Hello All,

Just wanted to check if this is something which is available now ? this is a very useful and exciting feature which will help small orgs immensely.

Thank you in advance for your time!
