### ISSUE TITLE
Chart of account importer "UnicodeDecodeError: 'utf8' codec " problem with Arabic language

### ISSUE THREAD

**Issue by yrestom** [frappe/erpnext#18816]
i am on ERPNext: v12.0.6 (version-12)

Frappe Framework: v12.0.6 (version-12)

i have this error msg when i’m trying importing csv file for chart of account with Arabic language in it
`UnicodeDecodeError: 'utf8' codec can't decode byte 0xe3 in position 0: invalid continuation byte`

**Comment by mhbu50** [comment]
@yrestom I think you can close this now, It is solved: 

https://discuss.erpnext.com/t/chart-of-account-importer-unicodedecodeerror-utf8-codec-problem-with-arabic-language/51888/7
