### ISSUE TITLE
Accounting Entry for Customer can only be made in currency: SVC

### ISSUE THREAD

**Issue by MecherDesoft** [frappe/erpnext#18823]
![image](https://user-images.githubusercontent.com/54341195/63569082-12271300-c535-11e9-8b94-ac746f493c4b.png)

**Comment by MecherDesoft** [comment]
Issue solved.

Had to import all CoA again using Import Data to get all the information on accounts, including currency. Already made some tests and it is working.

**Comment by Datacomm-Frontuari** [comment]
> Issue solved.
> 
> Had to import all CoA again using Import Data to get all the information on accounts, including currency. Already made some tests and it is working.

please explain this

**Comment by aff1-cpa** [comment]
Can you explain how you have solved this problem?
