### ISSUE TITLE
Dashboard incorrect link to Payment Entry field

### ISSUE THREAD

**Issue by Mitchy25** [frappe/erpnext#18821]
The Payment Entry field in the Dashboard is looking for documents linked by 'Party Name' instead of 'Party':

![Payment Entry](https://user-images.githubusercontent.com/42224026/63562063-560b2e00-c5b0-11e9-9b0b-e793f15b79e2.gif)

This results in 2 things:

1. The count of total Payment Entries and Open Payment Entries is incorrect
2. When creating a new Payment Entry via the '+' symbol on the Dashboard, the Party is not automatically filled in

**Comment by kennethsequeira** [comment]
@Mitchy25 what version is this occurring on?

**Comment by Mitchy25** [comment]
@kennethsequeira - Think this got merged here: https://github.com/frappe/erpnext/pull/18874

**Comment by kennethsequeira** [comment]
Fixed in current develop and v12 (v12.1.6) branches
