### ISSUE TITLE
Tracking Serial number through repacks OR allowing selecting UOM at sales order, delivery note, or invoice stage

### ISSUE THREAD

**Issue by pauldowd** [frappe/erpnext#1882]
The issue we have is that individual items have serial numbers, but we never sell individual items. We always sell cartons of 6 locally or pallets internationally. However we still need to track all of the individual item serial numbers throughout the entire process.

This is our process, and honestly, a fairly typical process for many businesses that shift stock. The issue here is that we don't want to scan each serial number when we sell, just a carton or pallet serial number. Could you imagine opening 50 cartons on a pallet just to scan all the individual item serial numbers?? This means we are breaking carton seals as well as wasting a large amount of time.

To begin with, we'd have multiple products as so:
  ITEM
  ITEM-CARTON
  ITEM-PALLET
1. Create Batch linked to that item
2. Purchase/Manufacture Stock as individual items which are booked in with their serial numbers and a batch
3. Repack the items to a carton and serialise the carton
4. Repack the cartons to a pallet and serialise the pallet

We then sell either an ITEM, ITEM-CARTON, or ITEM-PALLET

We might also do a warehouse transfer for ITEM-PALLET or ITEM-CARTON

We may at times repack an ITEM-PALLET or ITEM-CARTON into a smaller size. E.g. we warehouse transfer a pallet to our China warehouse, and then we break it down to cartons (repack) and sell cartons to retailers from there.

We need to be able to track an item using its' serial number so that we can find out the batch information as well as track all stock movements whether as an individual item or repacked into cartons or pallets. For example, if a customer rings us up with a product complaint we get their products serial number and want to know its batch details and all stock movements even though we never actually sold that individual item because it was sold as part of a carton.

What happens right now is that the serial number is not tracked after the repack, it just gets used up. This means when we want to find out what store that unit was sold to (we sold the store a repacked carton) it just tells me it was used in creating a carton, and doesn't follow it through to the end sale of the carton. It is feasible to track this manually right now, but I'm not even certain of that. However, once an item has gone through multiple repacks it would be impossible. E.g. ITEM to ITEM-CARTON to ITEM-PALLET (warehouse transfer) to ITEM-CARTON then Sales Order.

There is a forum post on this topic as well: https://groups.google.com/forum/#!topic/erpnext-user-forum/lRArc1fDxEg

I don't believe that a UOM system would work for this because the carton and pallets need to have a serial number so that they can accurately track the individual item serial numbers. UOM is just a sales item qty measure so probably wouldn't provide any tracking.

**Comment by PawanMeh** [comment]
Sales Cycle has UOM conversion in the latest release.

If there is any other open issues, kindly create new issue following [guidelines](https://github.com/frappe/erpnext/wiki/Issue-Guidelines)

**Comment by shanmukhasai6** [comment]
Is it possible to bundle serial numbers as we do product bundles for repack

Will such an idea work
