### ISSUE TITLE
New Journal Entry -> Quick Entry should not require a User Remark

### ISSUE THREAD

**Issue by jazzyjackson** [frappe/erpnext#18822]
This is on a fresh 'free trial' of erpnext.com

If I go to Accounting / Journal Entry / New Journal Entry, I've made a few entries without any user remarks, but I decided to try the Quick Entry. Nice! Except it won't let me save without a user remark. I enter 'ok' and save it, and can then submit the journal entry without that user remark.

If someone can point me to the python that renders this quick entry I'd be happy to make the change and submit the PR. thanks.

Attached screenshot, note the red 'required' style for the User Remark.

![Screen Shot 2019-08-22 at 11 19 06 PM](https://user-images.githubusercontent.com/7675670/63566602-6c26d900-c533-11e9-9591-42d7efb84720.png)

**Comment by clarkejj** [comment]
Hello thanks very much for your report!

I reposted this for the community to benefit and help here https://discuss.erpnext.com/t/new-journal-entry-quick-entry-should-not-require-a-user-remark/54267

**Comment by crescent28** [comment]
@jazzyjackson you can continue the discussion over the discuss post since this doesn't seem an error.
