### ISSUE TITLE
[ver 12] POS don't get serial when make payment 

### ISSUE THREAD

**Issue by lamphanjk** [frappe/erpnext#18834]
Dear all,
We have a big problem with POS in ver 11 and ver 12.
In ver10, I can put serial in search field and it automatically adds to the cart. After that, I can complete this sale order by generating new sale invoice.
But in the new version 11 and version 12, I can not do that. I don’t know where is the problem? It requires serial no when serial has existed. And when we add two serial numbers for one item, the message is NULL.
Please see the video for more detail.
https://www.loom.com/share/033413b7def84cabad576a8607e74ee3

**Comment by clarkejj** [comment]
Thanks for your report - see discussion https://discuss.erpnext.com/t/ver-11-and-ver-12-big-problem-with-pos-serial-issue/52071

**Comment by lamphanjk** [comment]
Any solution ?

**Comment by lamphanjk** [comment]
I still had the same problem in ver 13. Anyone have solution
