### ISSUE TITLE
Support EDI formats

### ISSUE THREAD

**Issue by lu-zero** [frappe/erpnext#1885]
The way different ERPs can talk with each other is EDI standards such as 
- [ ] EDIFACT (Europe & Asia) and 
- [ ] X12 (Americas).

A PO from a customer can be converted into a Sales Order. A Sales Invoice can be converted into Purchase Invoice.

This helps organizations integrate their supply chains even when different ERP systems are used.

ERPNext should support the latest versions or avatars of EDIFACT and x12.

Most large enterprises have an ERP that supports this standard and we can pitch ERPNext to Large Enterprises as a open source tool to achieve tight integration with their supply chain - especially their smaller suppliers that may not have implemented an ERP or may have implemented an ERP that does not support or is not scalable to support these standards.

Here's more information of these two standards:
https://www.ctg.albany.edu/publications/reports/key_concepts%3Fchapter%3D3%26PrintVersion%3D2&ved=0ahUKEwijqZ7P-bTUAhWLpo8KHa4xBz4QFgiGATAS&usg=AFQjCNG6eqyaLpWlWZvs8MTvQgbN1NTPPg&sig2=4yS4wqlyt8kF7v3PSvCiXg

Edit: with addition from @epochc

**Comment by hellojalex** [comment]
here's a post about EDI http://www.iqms.com/products/erp/financial_mgmt/edi_translator.html
is this on the roadmap?

**Comment by revant** [comment]
related python server for exploration
https://bots-edi.github.io

**Comment by epochc** [comment]
Revant: Perfect. I stumbled upon that site too. Plus it's an Open Source and GitHUb project.

Thanks

Jay
