### ISSUE TITLE
Routing table not updating

### ISSUE THREAD

**Issue by santoshbb** [frappe/erpnext#18878]
Routing table is not refreshing.
I am running erpnext version-12,
erpnext 12.0.8
frappe 12.0.8 

![routing table error](https://user-images.githubusercontent.com/10789840/64012105-b6a4e880-cb25-11e9-8b0a-81f59ece64a7.gif)

**Comment by clarkejj** [comment]
https://discuss.erpnext.com/t/routing-table-not-updating/52304

**Comment by clarkejj** [comment]
See similar report https://github.com/frappe/erpnext/issues/19353

**Comment by santoshbb** [comment]
already developed
