### ISSUE TITLE
Chart of Accounts Importer Bug

### ISSUE THREAD

**Issue by MecherDesoft** [frappe/erpnext#18876]
In my chart of accounts, I have several ledger accounts with exactly the same name but each one belongs to a different group account, e.g.: Utilities for Operation Expenses and Sales Expenses group accounts.

When I used the Importer, it only processed the last "Utilities" Account but input it in the first group account causing it to delete data and mess the chart number.

See below:

![Captura](https://user-images.githubusercontent.com/54341195/63997622-444bee00-cabc-11e9-93e5-befb34bd67b1.PNG)

**Comment by MecherDesoft** [comment]
Hello,
Any updates on this issue?

I would recommend using account numbers instead of account names as the primary data. That would solve the conflict of 2 accounts (parent or child) having the same name. Of course, we would have to restrict accounts number to be unique.

**Comment by harshit-30** [comment]
Please create another issue if it is replicable after v13.10.
Thanks for raising the issue and being a valuable member of the ERPNext Community. :)
