### ISSUE TITLE
Solved How to update  from v10 to v11 erpnext vmw  #upgrade #update 

### ISSUE THREAD

**Issue by Ashraf-Elsharqawy** [frappe/erpnext#18880]
Update from V-10 to V-11

1-  change master to mater    pass  cd frappe/app/erp/.git/nano conficg

2- bench switch-to-master

3- bench setup requirements

4- bench update --patch

**Comment by clarkejj** [comment]
Close this as per this discussion https://discuss.erpnext.com/t/how-to-update-erpnext-from-v10-to-v11/52344
