### ISSUE TITLE
Error in loading demo data 

### ISSUE THREAD

**Issue by hari-madhavan** [frappe/erpnext#18883]
When loading demo data it fails with the error 

> if not d.batch_size > 0: 
> TypeError: ‘>’ not supported between instances of ‘NoneType’ and ‘int’

Call stack ( only final section included  )  is as follows .

> File “/home/frappe/frappe-bench/apps/erpnext/erpnext/commands/init.py”, line 45, in make_demo
> demo.make(domain, days)
> File “/home/frappe/frappe-bench/apps/erpnext/erpnext/demo/demo.py”, line 31, in make
> manufacture.setup_data()
> File “/home/frappe/frappe-bench/apps/erpnext/erpnext/demo/setup/manufacture.py”, line 19, in setup_data
> import_json(‘BOM’, submit=True)
> File “/home/frappe/frappe-bench/apps/erpnext/erpnext/demo/setup/setup_data.py”, line 418, in import_json
> doc.insert()
> File “/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py”, line 228, in insert
> self.run_before_save_methods()
> File “/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py”, line 886, in run_before_save_methods
> self.run_method(“validate”)
> File “/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py”, line 786, in run_method
> out = Document.hook(fn)(self, *args, **kwargs)
> File “/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py”, line 1055, in composer
> return composed(self, method, *args, **kwargs)
> File “/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py”, line 1038, in runner
> add_to_return_value(self, fn(self, *args, **kwargs))
> File “/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py”, line 780, in 
> fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
> File “/home/frappe/frappe-bench/apps/erpnext/erpnext/manufacturing/doctype/bom/bom.py”, line 58, in validate
> self.validate_operations()
> File “/home/frappe/frappe-bench/apps/erpnext/erpnext/manufacturing/doctype/bom/bom.py”, line 582, in validate_operations
> if not d.batch_size > 0:
> TypeError: ‘>’ not supported between instances of ‘NoneType’ and ‘int’

**Version** : 12 ( Branch 12.x.x-develop )

**Steps to reproduce** :

1. Create a site with erpnext app ( and frappe ) with version 12.x.x-develop
2. Run `bench make-demo`

**Comment by hari-madhavan** [comment]
One solution to this issue is to include the batch_size into the operations defined in the JSON ( bom.json )  - like this
```
   {
    "operation": "Prepare Frame",
    "time_in_mins": 30.0,
    "workstation": "Drilling Machine 1",
    "batch_size" : 1
   },
```
but I think a better approach would be to have a default value for batch_size as 1 and have the JSON loader use the default value .  Feedback ?

**Comment by clarkejj** [comment]
To post this to discuss too will benefit and inform the whole community who may help expedite a fix!

**Comment by clarkejj** [comment]
Refer to this https://discuss.erpnext.com/t/demo-instance-creation-on-master-fails/52305
