### ISSUE TITLE
Leave Balance for Vacation calculates the wrong sum for current year

### ISSUE THREAD

**Issue by concurrentbug** [frappe/erpnext#18891]
ERPNext: v12.0.8 (version-12)
Frappe Framework: v12.0.8 (version-12)

End-point : api/method/erpnext.hr.doctype.leave_application.leave_application.get_leave_details

This end-point returns the leave balance table on the "New Leave Application", but it shows the wrong balance for "Available Leaves". 

Leave Type | Total Allocated Leaves | Used Leaves | Pending Leaves | Available Leaves
Sick Leave  | 10                                 | 4                  |                         0 | 6
Vacation     | 25                                  | 19                |                        0 | 6
As an example in this case the "Used Leaves" are summed up wrong in the case of "Vacation", but are correct in the case of "Sick Leaves".   If I sum up the leaves manually for the current year, they total up to 13. 

Perhaps the date-range in the sql query is wrong? and wrongly uses the range `DateTime.Today - 12Months to DateTime.Today `? I am not sure.

Thanks for looking into this.

**Comment by clarkejj** [comment]
Thanks for reporting this - to post your observations also to discuss.erpnext will inform and challenge the community to fix this!

**Comment by ruchamahabal** [comment]
Fixed in: https://github.com/frappe/erpnext/pull/29439
