### ISSUE TITLE
[ERPNext 11 & 12] Shopify Connector in non-working state?

### ISSUE THREAD

**Issue by mtaki14** [frappe/erpnext#18898]
After setting up a private shopify app and configuring the API, Password, Shared Secret fields and configuring the mappings the connector is not pulling any new orders. 

The connector doesn't create the webhooks sections in Shopify Settings, which seems to be the issue here.

There is no indication of what is wrong as no shopify logs are being created.

Is this a known issue?

**Comment by mtaki14** [comment]
Just tried on version 12 with the same exact result.

**Comment by clarkejj** [comment]
See discussion https://discuss.erpnext.com/t/shopify-sync-issues/52270

**Comment by mtaki14** [comment]
@saurabh6790 Are there any plans to look into this issue in the near future? It has been going on for a while now.

**Comment by mtaki14** [comment]
Just letting you know that the shopify connector is still not working after the v12.1.6 release which contained a fix for it

**Comment by ankush** [comment]
I've tested current integration on many sites. Seems like this is already fixed. 

The issue about webhooks not registering was related to Shopify not accepting "HTTP" connections. Your server must be able to accept https. 

ref: https://github.com/frappe/erpnext/pull/25630
