### ISSUE TITLE
On latest bench update “‘Meta’ object has no attribute ‘nsm_parent_field’”

### ISSUE THREAD

**Issue by azharul-islam** [frappe/erpnext#18911]
Traceback (most recent call last):
File “/usr/lib/python3.5/runpy.py”, line 184, in _run_module_as_main
“main”, mod_spec)
File “/usr/lib/python3.5/runpy.py”, line 85, in _run_code
exec(code, run_globals)
File “/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/bench_helper.py”, line 97, in 
main()
File “/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/bench_helper.py”, line 18, in main
click.Group(commands=commands)(prog_name=‘bench’)
File “/home/ubuntu/frappe-bench/env/lib/python3.5/site-packages/click/core.py”, line 764, in call
return self.main(*args, **kwargs)
File “/home/ubuntu/frappe-bench/env/lib/python3.5/site-packages/click/core.py”, line 717, in main
rv = self.invoke(ctx)
File “/home/ubuntu/frappe-bench/env/lib/python3.5/site-packages/click/core.py”, line 1137, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File “/home/ubuntu/frappe-bench/env/lib/python3.5/site-packages/click/core.py”, line 1137, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File “/home/ubuntu/frappe-bench/env/lib/python3.5/site-packages/click/core.py”, line 956, in invoke
return ctx.invoke(self.callback, **ctx.params)
File “/home/ubuntu/frappe-bench/env/lib/python3.5/site-packages/click/core.py”, line 555, in invoke
return callback(*args, **kwargs)
File “/home/ubuntu/frappe-bench/env/lib/python3.5/site-packages/click/decorators.py”, line 17, in new_func
return f(get_current_context(), *args, **kwargs)
File “/home/ubuntu/frappe-bench/apps/frappe/frappe/commands/init.py”, line 25, in _func
ret = f(frappe._dict(ctx.obj), *args, **kwargs)
File “/home/ubuntu/frappe-bench/apps/frappe/frappe/commands/site.py”, line 233, in migrate
migrate(context.verbose, rebuild_website=rebuild_website, skip_failing=skip_failing)
File “/home/ubuntu/frappe-bench/apps/frappe/frappe/migrate.py”, line 48, in migrate
frappe.modules.patch_handler.run_all(skip_failing)
File “/home/ubuntu/frappe-bench/apps/frappe/frappe/modules/patch_handler.py”, line 41, in run_all
run_patch(patch)
File “/home/ubuntu/frappe-bench/apps/frappe/frappe/modules/patch_handler.py”, line 30, in run_patch
if not run_single(patchmodule = patch):
File “/home/ubuntu/frappe-bench/apps/frappe/frappe/modules/patch_handler.py”, line 71, in run_single
return execute_patch(patchmodule, method, methodargs)
File “/home/ubuntu/frappe-bench/apps/frappe/frappe/modules/patch_handler.py”, line 91, in execute_patch
frappe.get_attr(patchmodule.split()[0] + “.execute”)()
File “/home/ubuntu/frappe-bench/apps/erpnext/erpnext/patches/v12_0/add_default_dashboards.py”, line 8, in execute
add_dashboards()
File “/home/ubuntu/frappe-bench/apps/erpnext/erpnext/setup/setup_wizard/operations/install_fixtures.py”, line 505, in add_dashboards
dashboard_data = get_default_dashboards()
File “/home/ubuntu/frappe-bench/apps/erpnext/erpnext/setup/setup_wizard/data/dashboard_charts.py”, line 7, in get_default_dashboards
company = frappe.get_doc(“Company”, frappe.defaults.get_defaults().company)
File “/home/ubuntu/frappe-bench/apps/frappe/frappe/init.py”, line 734, in get_doc
doc = frappe.model.document.get_doc(*args, **kwargs)
File “/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py”, line 69, in get_doc
return controller(*args, **kwargs)
File “/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py”, line 104, in init
self.load_from_db()
File “/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py”, line 149, in load_from_db
super(Document, self).init(d)
File “/home/ubuntu/frappe-bench/apps/frappe/frappe/model/base_document.py”, line 69, in init
self.setup()
File “/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/nestedset.py”, line 187, in setup
if self.meta.nsm_parent_field:
AttributeError: ‘Meta’ object has no attribute ‘nsm_parent_field’

https://discuss.erpnext.com/t/on-latest-bench-update-meta-object-has-no-attribute-nsm-parent-field/52448

**Comment by ablishek** [comment]
@sahil28297 & @rmehta 

Please help, our system is down!

**Comment by azharul-islam** [comment]
@sahil28297 & @rmehta 

Please release a fix soon. We aren't able to use the system.

**Comment by amutaher** [comment]
I am facing same ERROR
