### ISSUE TITLE
Error when running accounts receivable and payable reports-version 12.1.0

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#18915]
![image](https://user-images.githubusercontent.com/1822868/64203561-64085b00-ce9c-11e9-9292-1342eef4b713.png)

Applies to the accounts receivable/payable summaries too.

**Comment by clarkejj** [comment]
To vet this as an actual bug, please copy and paste the full error traceback from the server logs plus screenshot and post this first to discuss thanks.

**Comment by muchai** [comment]
The error is in accounts_receivable report, function **prepare_conditions**

It's being called with no params, i.e. **self.add_accounting_dimensions_filters()**

This change fixes the reports (accounts payable/receivable and summaries): **self.add_accounting_dimensions_filters(conditions, values)**
