### ISSUE TITLE
v12 editing doctype - AttributeError: 'NoneType' object has no attribute 'fieldtype'

### ISSUE THREAD

**Issue by idolaru** [frappe/erpnext#18925]
Trying to edit any doctype from the doctype list

Error received: `AttributeError: 'NoneType' object has no attribute 'fieldtype'`

**Comment by ahmadpak** [comment]
This error occur because a blank comment is being added on save of each document. Delete the blank comments when ever you save the document. I have reported this issue here:
https://github.com/frappe/erpnext/issues/18933

**Comment by ahmadpak** [comment]
This issue has been resolved in V12.1.1 please update
