### ISSUE TITLE
[V12] - Ignore Pricing Rules on Row Level

### ISSUE THREAD

**Issue by Mitchy25** [frappe/erpnext#18923]
When we are creating a Sales Order for a customer, sometimes they have an existing pricing rule that applies to one of the rows in the Sales Order, but we may want to override the discount that they are recieving on that specific row.

The only option we have is to 'Ignore Pricing Rules' for the whole Sales Order and manually enter all of the pricing rules for all lines and then adjust the line that we would like to override.

E.g Sales Order:

Line 1: Product ABC - Pricing Discount 5%
Line 2: Product DEF - Pricing Discount 5%
Line 3: Product GHI - Pricing Discount 5%

When I try to give the customer 10% on Line 2, I click Save and the Pricing Rule is reapplied. 

Possible Solutions:

1. Allow the user to 'Delete' the pricing rule from the 'Pricing Rule' table in the Sales Order
2. Create an 'Ignore Pricing Rule' checkbox on the Sales Order Item doctype
3. Check on Sales Order save whether the Discount Field of Sales Order Item has been manually adjusted and if so, dont override it with Pricing Rule.

**Comment by Mitchy25** [comment]
I implemented a checkbox 'Ignore Pricing Rule' on the Sales Order Item/Sales Invoice Item level and wrote a script to ignore pricing for this row.

**Comment by zulfi007** [comment]
@Mitchy25 can you share, how you have implemented this feature in v12

**Comment by Mitchy25** [comment]
@zulfi007 - Sure, you can contact me at hello@techsquid.co.nz
