### ISSUE TITLE
Feature request: User Permissions - View as another user

### ISSUE THREAD

**Issue by idolaru** [frappe/erpnext#18946]
Our business is in complete development and we are learning more and more about different types of user permissions - at the same time we are creating multiple custom docytypes etc.

We have discovered that a feature such as "View As" another user where you would be able to preview a specific doctype to verify permissions etc, would be a great addition to the wonderful ERPNext.

Of course, this feature should exclusively be available to system managers and company administrators.

**Comment by kennethsequeira** [comment]
To check the docs a user can access, you can use the **View Permitted Documents** option:

![image](https://user-images.githubusercontent.com/33246109/64474897-cc0aba00-d198-11e9-8e96-b49bd7a1a35d.png)

![image](https://user-images.githubusercontent.com/33246109/64474913-f6f50e00-d198-11e9-856d-d05ac28ae0a5.png)

There is already an existing issue similar to yours. Request you to add your comments there and also add a 👍 to it:

https://github.com/frappe/erpnext/issues/17615
