### ISSUE TITLE
BackBlaze B2 Backup Integration

### ISSUE THREAD

**Issue by danielchalmers** [frappe/erpnext#18959]
We have the option to use DropBox or S3 for backups, this is a suggestion for adding BackBlaze B2.

https://www.backblaze.com/b2/cloud-storage.html

**Comment by tonto0** [comment]
Do not see this feature implemented, though marked as completed in 2021.  What version is it working in?

**Comment by ankush** [comment]
GitHub didn't have close as "not planned" feature before.


This can be implemented as an app if required. Unlikely to be added to core. 

Consider using https://restic.net/
