### ISSUE TITLE
V12 Missing "All Item Groups"

### ISSUE THREAD

**Issue by RoyIrwan** [frappe/erpnext#18950]
Looks like fresh install of 
`ERPNext: v12.1.0 and Frappe Framework: v12.0.10`
missing "All Item Groups" in Item Group Tree. So I could not add any items because of this.

I confirmed this by installing fresh new server twice. Is this a bug?

Edit: A simple workaround could be found here:
[https://discuss.erpnext.com/t/item-group-empty-on-fresh-install/52512/3](https://discuss.erpnext.com/t/item-group-empty-on-fresh-install/52512/3)

**Comment by bojkic** [comment]
tried fresh installation a few times.... confirmed 

> frappe.exceptions.LinkValidationError: Could not find Parent Item Group: All Item Groups

**Comment by sharky98** [comment]
Looks like Roylrwan was quicker than me to open the issue! I'm the OP on the discussion.
