### ISSUE TITLE
LWP calculation incorrect in Leave Application when Half Day is selected

### ISSUE THREAD

**Issue by vijaywm** [frappe/erpnext#18955]
LWP is calculated wrongly in Leave Applicaiton when Half Day is selected and the leave spans multiple days.
**calculate_lwp** in **salary_slip.py** ignores the "**half_day_date**" field, all days are calculated as half day.

**Comment by clarkejj** [comment]
Please link here and there to discuss to inform users who may be able to help here thanks!

**Comment by vijaywm** [comment]
fix is to change **salary_slip.py** line 258 from 
```select t1.name, t1.half_day``` to 
```select t1.name, case when t1.half_day_date = %(dt)s or t1.to_date = t1.from_date then t1.half_day else 0 end
```

**Comment by vijaywm** [comment]
Pull request for the issue

#19161
