### ISSUE TITLE
[Sponsored] Enhanced Loan Management

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#18997]
This feature extends the standard ERPNext Loan into a new module that can be used for managing any kind of loans (including Term and Demand loans) and also the ability to manage Security against Loans.

- [x] Move Loan Management to separate module
- [x] Enhance Loan Type to include "Demand Loans" and "Term Loans"
- [x] Add loan penalty configuration in Loan Type

### Loan Security Management

- [x] Add new model Loan Security Type
- [x] Add new model Loan Security
- [x] Add new model Loan Security Pledge (with status, for multiple securities)
- [x] Add new model Loan Security Price
- [x] Add new model Loan Security Shortfall
- [x] Add proposed security to Loan Application 
- [x] Ability to create Loan Security Pledge against Loan Application
- [x] Link Loan Security Pledges to Loan after Loan is created
- [x] Validate that one pledge is only applicable to one loan
- [x] Add new model Process Loan Security Shortfall
- [x] Automatically create Loan Security Shortfall based on latest price from Process Loan Security Shortfall
- [ ] Add new model Loan Security Liquidation

### Loan Disbursement, Interest / Penalty Accrual and Repayment

- [x] Add new model Loan Disbursement with status
- [x] Post payment GL entries against Loan Disbursement on submission
- [x] Add new model Loan Interest Accural
- [x] Add new model "Process Loan Interest Accrual"
- [x] When loan interest accrual is processed, automatically create "Loan Interest Accrual" based on Loan and last Loan Interest Accrual with interest and penalty based on Loan Type and penalty rules.
  - [x] Apply on basis of Term loan and Demand loan
- [x] Post ledger for accrued interest and penalty
- [x] Add new model "Loan Repayment"
- [x] Post ledger for repayment

### Loan Closure

- [ ] Create new model Loan Closure
- [ ] Get closure amount for Closure
- [x] Post accrual, closing entries on closure and update Loan status

### General

- [x] Documentation for above features
- [x] Test Coverage for above features

**Comment by iMoshi** [comment]
Would really love this brought to the table :)

**Comment by muchai** [comment]
This is a great module. We will be testing this to see if it can fit, or fit with some enhancements to fit into SACCOs (Savings and Credit Cooperative Society) in Kenya. Current market is dominated by a Microsoft Dynamics NAV add-on.
