### ISSUE TITLE
Create task from inside an event

### ISSUE THREAD

**Issue by idolaru** [frappe/erpnext#19005]
From within an event an user can create a task for that specific event. 

Assigning this task to a specific user for whatever specific necessity or linking it to another existing task.

**Comment by liyakatalilal** [comment]
@idolaru: How is this being reported as Issue without giving any screenshot of where you facing this challenge? If you have come across this challenge in the Project module, please reopen this issue with explanatory screenshots.

If this is more like a 'Feature Request', please post it on discuss.erpnext. From the User forum, you would get more feedback or workarounds. Basis such discussion, suggest more detailed of how to achieve it along with flow diagram or wireframe.
