### ISSUE TITLE
Credit Limit: Don't Allow Sales invoices to be Saved in case Credit Limit is going to be Breached

### ISSUE THREAD

**Issue by adityaduggal** [frappe/erpnext#1904]
Hi,

I guess for Sales Invoices the credit limit should be checked on SAVING rather than on submitting since Sales invoice is a Legal document and is checked by all the Tax authorities. Let me give you a scenario:

Suppose a Customer has pending amount of 1000 in accounts and the CREDIT LIMIT is 2000 only. Now there is a delivery note (2000/-) which is pending for Invoicing (means that ready material is to be dispatched). Now if a user tries to make an invoice of this DN then he/she would be able to make the Sales invoice on the date 01-Jul-2014. Now since the CREDIT LIMIT would be breached the user would not be able to submit the SI. Now if the customer does not make the payment for a month then the SI would remain in draft for 1month.

Suppose if a client has a custom script to make invoices only on the CURRENT date then that SI which has been in draft for 1month would be submitted with a date of 01-Aug-2014 and this would make the series go wrong since if the Bill# 1 is in date of Aug whereas other bills like 2,3,4 would be in date of July.

I guess most of the countries would not allow this kind of ambiguity in the system where Invoice #1 is of later date than Invoice # 2.

I think with Sales Orders and DN maybe we could allow the check only at submission since mostly these are internal usage numbers but I guess Sales Invoices are generally LEGAL documents.

I guess not allowing Saving would be better since if the Credit Controller increases the CL at backend then the SI would be saved immediately without loss of data (I mean without doing a clear cache).

Kindly let me know about your and your team's views on this problem.

**Comment by joezsweet** [comment]
@adityaduggal can you please double check if issue is still there in version 8?

**Comment by adityaduggal** [comment]
Please close this issue
