### ISSUE TITLE
CR+LF in Scan barcode field not adding items already in list.

### ISSUE THREAD

**Issue by ahaudero** [frappe/erpnext#19045]
Hi,

on version: 
ERPNext: v11.1.60 (version-11)
Frappe Framework: v11.1.55 (version-11)

when scanning barcodes with CR+LR in Stock entry it will add the item the if it is not on the list, but the scanning field will not be cleared, have to manually delete the text to scan again. 
if item is on the list it will say quantity increased but it doesn't increase the quantity and won't clear the Scan barcode field.
![item added ste](https://user-images.githubusercontent.com/55280730/64859876-bd565400-d62b-11e9-8b1f-a84210368053.PNG)
![increasedby1](https://user-images.githubusercontent.com/55280730/64859909-d959f580-d62b-11e9-887a-ad1a77471cf5.PNG)

The scan barcode field in all other forms is behaving as expected, so this must be a bug?

This error can be recreated by pressing Enter after typing barcode if one doesn't have a barcode scanner available.

**Comment by ankush** [comment]
Not reproducible on v13/develop. 

carriage return does trigger scan even and erases the field once results are fetched.
