### ISSUE TITLE
Table Multiselect - TypeError: undefined is not an object (evaluating 'e.fields')

### ISSUE THREAD

**Issue by idolaru** [frappe/erpnext#19040]
I have created a custom doctype which is linked inside the Event doctype as Table Multiselect

Unfortunately, I cannot open the table row to edit the table multiselect field and in the browser console this error appears:

```
TypeError: undefined is not an object (evaluating 'e.fields')

get_link_field — table_multiselect.js:137
set_formatted_input — table_multiselect.js:110
(anonymous function) — class.js:53
set_input — data.js:76
n — base_input.js:69
refresh_input — base_input.js:88
refresh — base_control.js:85
attach_doc_and_docfields — layout.js:325
refresh — layout.js:223
render — grid_row_form.js:24
show_form — grid_row.js:524
toggle_view — grid_row.js:510
(anonymous function) — grid_row.js:231
dispatch — jquery.min.js:3:7543
handle — jquery.min.js:3:5626
http://URL RETRACTED/assets/js/awesomplete.min.js.map
```

**Comment by idolaru** [comment]
Confirmed it's not working on safari and neither google chrome.

Here is the google chrome console error:

```
Uncaught TypeError: Cannot read property 'fields' of undefined
    at o.get_link_field (table_multiselect.js:137)
    at o.set_formatted_input (table_multiselect.js:110)
    at o.set_formatted_input (class.js:53)
    at o.set_input (data.js:76)
    at n (base_input.js:69)
    at o.refresh_input (base_input.js:88)
    at o.refresh (base_control.js:85)
    at init.attach_doc_and_docfields (layout.js:325)
    at init.refresh (layout.js:223)
    at GridRowForm.render (grid_row_form.js:24)
```

**Comment by idolaru** [comment]
Correction for the scenario:

Doctype 1 - Dive guide name
Doctype 2 - Dive guide ( child doctype )
Doctype 3 - Itinerary

"Dive guide name" is put in "Dive guide" as a link field. "Dive guide" is put in "Itinerary" as Table Multiselect. "Itinerary" is put in Event doctype as table.

At some times, Editing the itinerary table in the Event doctype works but after saving the event and refreshing the page, the same errors in the browser console appear.

**Comment by idolaru** [comment]
Situation persists. any update information on this matter would be very much helpful.

**Comment by clarkejj** [comment]
Link to discussion https://discuss.erpnext.com/t/table-multiselect-typeerror-undefined-is-not-an-object-evaluating-e-fields/52792/16

**Comment by idolaru** [comment]
Anyone has any idea on this issue ?

I am still unable to use the table multiselect field.

**Comment by dawoodjee** [comment]
Try this workaround:
https://discuss.erpnext.com/t/table-multiselect-typeerror-undefined-is-not-an-object-evaluating-e-fields/52792/30?u=adam26d
