### ISSUE TITLE
Healthcare invoicing. Bug?

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#19054]
When creating a sales invoice, once you select items from the healthcare services, you can't re-select them again. this means that there is no chance to double bill a patient, which is very good. However, with prescription, you can select items several times. This means that you can invoice the patient more than once for the same prescription.

**Comment by akurungadam** [comment]
This allows the facility to dispense medications multiple times, but all services rendered to the patient are billed only once.

**Comment by muchai** [comment]
Makes sense. Thank you for the reply.
