### ISSUE TITLE
SMTP Erpnext - Zoho Error

### ISSUE THREAD

**Issue by liveonstore** [frappe/erpnext#19057]
(553, b'Relaying disallowed as "email add")
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/queue.py", line 406, in send_one
    smtpserver.sess.sendmail(email.sender, recipient.recipient, encode(message))
  File "/usr/lib/python3.6/smtplib.py", line 888, in sendmail
    raise SMTPDataError(code, resp)

**Comment by liyakatalilal** [comment]
@liveonstore
Do explain this issue in more details with description on 1) what you doing, 2) what is the expected outcome and 3) where the system is failing. Also, add a screenshot for ease of reference. 

The details you provided are not sufficient for developers to replicate.

**Comment by henrynewman** [comment]
Is it free or paid Zoho Mail?

**Comment by liveonstore** [comment]
> Is it free or paid Zoho Mail?

Paid Zoho

**Comment by henrynewman** [comment]
Go to the email settings and enable IMAP and POP and give feedback.
