### ISSUE TITLE
formula for income tax of salary

### ISSUE THREAD

**Issue by TheresaHsu** [frappe/erpnext#19087]
Hi support team,

Is there abbreviation for taxable salary?
I have a problem setting the formula for income tax.
In my original plan, the income tax changes with taxable salary.
But I find one of the deduction items doesn't change with payment date so my formula can't get correct figure.
I list out the salary structure as below one for your reference.
EARNING-Basic salary:  is Tax Applicable & depends on Payment Days
DEDUCTION-Labor Insurance: is Tax Applicable & depends on Payment Days
DEDUCTION-National Health Insurance:  is Tax Applicable
DEDUCTION-Income Tax: (Basic Salary depends on payments -Labor Insurance-National Health Insurance)*0.05
Do you have any suggestion?

BR,
Theresa

**Comment by muchai** [comment]
It's TI (Taxable Income), if not there, you can create it, define a formula for it, and use in subsequent salary components.

e.g. https://drive.google.com/file/d/1UFdM2Uo8pJOGcERVxALBgVaXd0gD06Wq/view?usp=sharing
