### ISSUE TITLE
Subscription Renewal Errors

### ISSUE THREAD

**Issue by remeshkvkumar** [frappe/erpnext#19088]
i have paid RS 800 from my credit card for subscription.But invoice is for 400.Renewed on 17/09/2019 .But nexxt Renewal date is 18/09/2019  IN INVOICE.Can you please clarify this mismatches .Pleae let me know which plan is activated currently in my subscription
Account url    powerinfinitytech.erpnext.com

**Comment by clarkejj** [comment]
If this is possibly an **erpnext.com cloud subscription billing question**, best to email support@erpnext.com for a response!?
