### ISSUE TITLE
Automated depreciation in fixed asset ledgers

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#191]
Automated depreciation in fixed asset ledgers

**Comment by rmehta** [comment]
1. Add a depreciation % in account head of type "Fixed Asset"
2. Create a Depreciation Tool that will display a list of accounts and their gross and net blocks and create a Journal Entry for Depreciation.
3. If the fixed asset account is a warehouse, the value of the items (serial nos) in that warehouse should also get depreciated based on the depreciation percent
4. Depreciation Report (for given year)

**Comment by bobzz-zone** [comment]
Hi, im already created an App for this , maybe its usefull for you guys , even its just an simple app that the Deprecated asset is not in inventory , how can i share this ? ( i dunno how PR in github works so far)

**Comment by rmehta** [comment]
Check this: https://help.github.com/articles/using-pull-requests/

It will be much easier to add your contributions via pull requests.

**Comment by sliska** [comment]
Has the automated depreciation feature been developed further? Will it be released in any upcoming versions?

**Comment by sliska** [comment]
Rather than designating an item as a fixed asset, can we designate a warehouse as a fixed asset warehouse?

**Comment by Kickball** [comment]
How is this feature coming along?

**Comment by cgpurbaugh** [comment]
This is in V7, so this issue could be closed.
