### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by ajaypratapyadav** [frappe/erpnext#19118]
I'm trying to connect ERPNext with woocommerce and sync the product and its variant with ERPNext.
![error_ERPNext](https://user-images.githubusercontent.com/31924970/65247614-5266ba80-db0e-11e9-89f4-ba023bbebd1c.png)

But showing me error of **"No JSON object could be decoded"**.

Also i got below error in console 

**WebSocket connection to 'wss://xxx.xxx.com/socket.io/?EIO=3&transport=websocket&sid=xxxxxxxxxx failed: Invalid frame header**

I stuck here, Please help me out in this.

**Comment by clarkejj** [comment]
Please post this also to discuss.erpenxt.com, to inform and benefit all to help resolve this.

Add links to this report there, and your discuss thread here thanks!

Also please copy and paste the traceback, as a screenshot hinders code browsing.

**Comment by ajaydoyenhub** [comment]
@clarkejj I create two topics there yesterday but seem no reply. 

please help me if you can ?

**Comment by clarkejj** [comment]
Instance is running obsolete code!? https://discuss.erpnext.com/t/erpnext-woocommerce-no-json-object-could-be-decoded-error/53118/6

**Comment by clarkejj** [comment]
This 3x related issues closed as no response from user
https://github.com/frappe/erpnext/issues/19146
https://github.com/frappe/erpnext/issues/19159
https://github.com/frappe/erpnext/issues/19118
