### ISSUE TITLE
Error: Value missing for Assessment Plan: Course

### ISSUE THREAD

**Issue by sushanpth** [frappe/erpnext#19132]
Validation error while creating Assessment Plan even when course is selected.

[Discuss Thread](https://discuss.erpnext.com/t/error-value-missing-for-assessment-plan-course/41693)

Also tried in Version 12
`
ERPNext: v12.1.2 (version-12)
`
`
Frappe Framework: v12.0.12 (version-12)
`

![Screen Shot Version 12](https://user-images.githubusercontent.com/5916748/65369860-675c5e80-dc72-11e9-9d83-a071eebf847c.png)

**Comment by flexy2ky** [comment]
Essentially the error is related to the data set to fetch from student_group.course. If you customize the Assessment Plan doctype and modify the course field, changing the fetch from parameters to course.course_name, that will fix the problem.
![image](https://user-images.githubusercontent.com/32480024/71802123-2a6b7a80-305d-11ea-8e34-065706f55535.png)

**Comment by ssemotom** [comment]
@flexy2ky  Thank you for solving  Error: Value missing for Assessment Plan: Course #19132. The guidance given has assisted so much.

**Comment by ssemotom** [comment]
Search for doctype:  Assessment Plan

Select course
Go to Menu, select Customize
Customize Form
Enter Form Type
Assessment Plan
In Fetch From, change student_group.course to course.course_name
