### ISSUE TITLE
sync has terminated

### ISSUE THREAD

**Issue by ajaypratapyadav** [frappe/erpnext#19146]
I have setup ERPNext with woocommerce but i get error on **Order Creation.** 

it's showing "sync has terminated" in console.

**And when i'm trying to fetch Customer data from its id giving error "'str' object has no attribute 'get'"**

I'm using API version 3 . 

![frape_error](https://user-images.githubusercontent.com/31924970/65426293-8b17d400-de2d-11e9-8725-3052f6092cd9.png)

@revant , @vinayak--  please help me in this?

**Comment by clarkejj** [comment]
Instance is running obsolete code!? https://discuss.erpnext.com/t/erpnext-woocommerce-no-json-object-could-be-decoded-error/53118/6

**Comment by clarkejj** [comment]
This 3x related issues closed as no response from user
https://github.com/frappe/erpnext/issues/19146
https://github.com/frappe/erpnext/issues/19159
https://github.com/frappe/erpnext/issues/19118
