### ISSUE TITLE
ERPNext Order creation with woocommerce error

### ISSUE THREAD

**Issue by ajaydoyenhub** [frappe/erpnext#19159]
Hello all,

I implemented ERPNext with Woocommerce which sync order when any order placed.

ERPNext version is 12, and woocommerce_sync is using in ERPNext for syncing purposes.

for simple product its showing all the product sync,

But for variable product it’s giving error and also syncing is not happen and showing error in Woocommerce Log List.

I try to trace the error but seem nothing to work,

please check below attachment for the error log.

![frape_error](https://user-images.githubusercontent.com/55733195/65503522-b90b2000-dee2-11e9-9f1b-61bfb31786dc.png)

can someone please help me out from this ?

@venetanji @rmehta @noussh

**Comment by clarkejj** [comment]
Instance is running obsolete code? https://discuss.erpnext.com/t/erpnext-woocommerce-no-json-object-could-be-decoded-error/53118/6

**Comment by clarkejj** [comment]
This 3x related issues closed as no response from user
https://github.com/frappe/erpnext/issues/19146
https://github.com/frappe/erpnext/issues/19159
https://github.com/frappe/erpnext/issues/19118
