### ISSUE TITLE
Can't reconcile Payment Entries in Bank Reconciliation

### ISSUE THREAD

**Issue by tecnofoodmx** [frappe/erpnext#19165]
When trying to reconcile bank entries with Payment entries I don’t get the reconcile button:
![image](https://user-images.githubusercontent.com/26855372/65559001-78210480-defe-11e9-8d70-76a987874b49.png)

When I reconcile Bank Entries with other documents (such as SINV and PINV) I do get that button:

![image](https://user-images.githubusercontent.com/26855372/65558990-6d666f80-defe-11e9-8456-6debd85988a1.png)

Is it me? or is there a bug?

Thanks in advance!

**Comment by Mitchy25** [comment]
What erpnext and frappe version are you on?

**Comment by Mitchy25** [comment]
Have just fixed this. Will submit PR now

**Comment by Mitchy25** [comment]
PR: https://github.com/frappe/erpnext/pull/19190

**Comment by gwhitney** [comment]
PR 19190 was merged; I think this issue should be closed.
