### ISSUE TITLE
Server Error: TypeError: object of type ‘NoneType’ has no len() in Employee Leave Balance DocType

### ISSUE THREAD

**Issue by alkuhlani** [frappe/erpnext#19160]
Hi,
I get this Error 
`TypeError: object of type ‘NoneType’ has no len()`
in **Employee Leave Balance DocType**
in
ERPNext: **v12.1.4** (version-12)
Frappe Framework: **v12.0.14** (version-12)
Please any help!
![123](https://user-images.githubusercontent.com/11437168/65503882-85be9600-dece-11e9-97e5-0bcef93235f4.PNG)

**Comment by alkuhlani** [comment]
> Hi,
> I get this Error
> `TypeError: object of type ‘NoneType’ has no len()`
> in **Employee Leave Balance DocType**
> in
> ERPNext: **v12.1.4** (version-12)
> Frappe Framework: **v12.0.14** (version-12)
> Please any help!
> ![123](https://user-images.githubusercontent.com/11437168/65503882-85be9600-dece-11e9-97e5-0bcef93235f4.PNG)

**Comment by clarkejj** [comment]
Please post your complete traceback

Discussion here https://discuss.erpnext.com/t/server-error-typeerror-object-of-type-nonetype-has-no-len-in-employee-leave-balance-doctype/53123

Note this pending possible fix https://github.com/frappe/erpnext/pull/18984

**Comment by ruchamahabal** [comment]
Not replicated anymore. Closing.
