### ISSUE TITLE
[Bug v12] Purchase Receipt do not reduce the quantity of RAW materials in the subcontracted item

### ISSUE THREAD

**Issue by mayamihaylova** [frappe/erpnext#19174]
We have an item which is manufactured from Subcontractor and organize this process via Purchase order (PO) with transfer RAW materials to the Subcontractors Warehouse. Our Subcontractor delivers the manufactured items by lots which are not hole quantity from the  PO. 
When we received the each lot, we make a Purchase Receipt (PRE) for the received quantity < ordered quantity. 
In v12 (ERPNext: v12.1.3 (version-12), Frappe Framework: v12.0.13 (version-12)) when I save the PRE the quantity of RAW materials do not reduce and remain equal to the quantity from PO.
In v10 this functionality worked properly.
Note: In v12 this functionality works properly in Purchase Invoice.
The case is illustrated in the following screenshots.
![PO](https://user-images.githubusercontent.com/48950151/65586147-54a49b00-df8c-11e9-90ca-f023acb3dfb9.PNG)
![PRE100](https://user-images.githubusercontent.com/48950151/65586167-5cfcd600-df8c-11e9-8d0b-36db98baf5e9.PNG)
![PINV100](https://user-images.githubusercontent.com/48950151/65586179-6128f380-df8c-11e9-8e6d-9edc2e074736.PNG)

**Comment by mayamihaylova** [comment]
I have repeated the scenario that I described above and in ERPNext: v12.1.6 (version-12);Frappe Framework: v12.0.16 (version-12) in the Purchase Receipt screen there isn't even the table Supplied Items and section Raw Materials Supplied. FYI the functionality in Purchase Invoice is stil working correctly. Please help. We need of this functionality in Purchase Receipt because our suppliers give us many lots of items from one Purchase order with many Purchase Receipts and give us only one Purchase Invoise for this Purchase Order.

**Comment by s-aga-r** [comment]
@mayamihaylova try to replicate the same in v14 and re-open if the issue is still there.
