### ISSUE TITLE
Multiple occurrence of buttons in dropdown button

### ISSUE THREAD

**Issue by joelios** [frappe/erpnext#19186]
**Issue**
![grafik](https://user-images.githubusercontent.com/26505401/65686372-89842100-e064-11e9-8729-09ec529f5a05.png)

**Reproduction**
Go to Customer > Create new Sales Invoice (Klick on "+" at Dashboard) > Klick on "Get Items From"-Button of Sales Invoice

**Comment by kennethsequeira** [comment]
Occurs in version 12 

ERPNext: v12.1.6 (version-12)
Frappe Framework: v12.0.16 (version-12)

**Comment by deepeshgarg007** [comment]
@joelios  Closing this issue. If the issue still persists in the latest version-13 or above then please reopen a new issue
