### ISSUE TITLE
Automatic Email notifications in Project

### ISSUE THREAD

**Issue by ghost** [frappe/erpnext#1918]
Hello,

I'm sure that you guys are very busy in developing ERPNext but if you could think about my feature request to implement in the future, that would be great. 

We think it would be useful if there was an automatic email notification sent by the system in Project and Task whenever a new comment has made or someone else got assigned to the task (or project). 

Only a question beside the request above: What am I doing wrong that the numbers in notification area in the upper right corner just don't want to decreased, however I always click on it and go into the relevant menu or item?

Thanks a lot for your help,
Tivadar

**Comment by Devens** [comment]
In fact, the comment of each transaction (Especially, Opportunity & Project) should be notified to persons with whom the same are shared. 

It can really make the internal communication and followups easy and keep everyone in sync. 

I once again suggest/request to take this on priority.

**Comment by joezsweet** [comment]
@Devens can u please check last version?

**Comment by mbauskar** [comment]
It can be implemented using Email Alerts, ToDo notification is already available. Closing the issue please reopen if issue is not solved
