### ISSUE TITLE
Update Items on Sales Order results in rate changes to unedited lines

### ISSUE THREAD

**Issue by asmit3141** [frappe/erpnext#19188]
When useing the update items feature to add an additional unit to line 5 of a Sales Order the rate on Line 1 on that Sales order was multiplied by the margin amount. This changed the line from 12 units @ 4399.17 to 12 units @ 19,352,696.69.

**Comment by kennethsequeira** [comment]
The issue has been fixed here: 

https://github.com/frappe/erpnext/pull/19173
