### ISSUE TITLE
BOM Tree Structure Issues

### ISSUE THREAD

**Issue by Rajeshk1508** [frappe/erpnext#19199]
Hi 

We have observed that the Link between the Parent Child Items are visible in the Form. I.e in the BOM Browser. However when we try to take the PDf i.e print of the same the Links are not visible.

We would request that the links should be visible even in the PDF.  In addition along with the item code we would also required the Item description and the Quantity  to be visible in the BOM Tree Structure and the in the pdf. where as at Present only the Item Code is visible in the tree structure  and the Item Description are visible at the right hand corner. 

Request you to provide us with the resolution  for the same .

**Comment by clarkejj** [comment]
Thanks for reporting this issue, two requests please:
1. Post this to discuss.erpnext.com - so all the community is informed and benefits, and can expedite responses and possible fixes, thanks
2. Add a link to this post here, and on discuss, a link to your report here

**Comment by crescent28** [comment]
@Rajeshk1508 Request you to post an error in the communication if any or post the same issue at discuss.erpnext.com
