### ISSUE TITLE
Customer not created after saving.

### ISSUE THREAD

**Issue by cedewey** [frappe/erpnext#19197]
I just started the free trial. When I create a new customer, then save it, I do not then see my customer listed at /desk#List/Customer/List

I have no filters applied so they should show up. I have tried creating a customer both within the pop up modal and the full page.

**Comment by kennethsequeira** [comment]
If you're on a trial with erpnext.com, you can report the issue via the in-built support app for a faster response.

Will need a lot more information to replicate this issue. Perhaps check your browser's console to see if it gives any traceback, or record the process as a gif and post it.
