### ISSUE TITLE
V12 - Issue in STOCK BALANCE Report 

### ISSUE THREAD

**Issue by pujanthakkar** [frappe/erpnext#19192]
Every Time I Click “Generate New Report” in the Stock Balance report in Stock Module I get the following error, facing this after updating to V12

Traceback (most recent call last):
File “/home/frappe/frappe-bench/apps/frappe/frappe/desk/query_report.py”, line 264, in get_prepared_report_result
data = json.loads(uncompressed_content)
File “/usr/lib/python3.5/json/init.py”, line 312, in loads
s.class.name))
TypeError: the JSON object must be str, not ‘bytes’

**Comment by clarkejj** [comment]
https://discuss.erpnext.com/t/v12-issue-in-stock-balance-report/52449

**Comment by KaviyaPeriyasamy** [comment]
The issue may be cleared when you try reinstalling the python.

**Comment by nabinhait** [comment]
Can't replicate, can you please give some more information to replicate

**Comment by avaiskhatri** [comment]
@pujanthakkar have you figured out the issue?

**Comment by avaiskhatri** [comment]
> Can't replicate, can you please give some more information to replicate
@nabinhait The errors popups as soon as the report is open. Sharing screenshot for screenshot as well.
![stock_balance](https://user-images.githubusercontent.com/15321796/67204973-1f268c80-f428-11e9-806e-a8bd2a389332.png)

**Comment by pujanthakkar** [comment]
> The issue may be cleared when you try reinstalling the python.

We tried that, not working.

**Comment by pujanthakkar** [comment]
> @pujanthakkar have you figured out the issue?

not yet, but I am wondering why anyone else is not facing this issue as it is a major one.

**Comment by pujanthakkar** [comment]
> Can't replicate, can you please give some more information to replicate

Stock Balance Report does not show anything.

After selecting the filters as soon as we click Generate New Report a error is created in the error log. as attached.

let me know if you need anything else 
<img width="960" alt="2019-11-02 (2)" src="https://user-images.githubusercontent.com/53821822/68071137-7cfa9300-fd9d-11e9-8a47-1e713de27481.png">

<img width="960" alt="2019-11-02" src="https://user-images.githubusercontent.com/53821822/68071113-255c2780-fd9d-11e9-898d-db4a8e39d17d.png">
<img width="960" alt="2019-11-02 (1)" src="https://user-images.githubusercontent.com/53821822/68071114-255c2780-fd9d-11e9-8f8b-6909cff916fc.png">

**Comment by avaiskhatri** [comment]
@pujanthakkar I was thinking the same initiatlly that why others aren't experiencing such issue.
 
What I assume is that we have installed/upgraded the erpnext at wrong time, when the packages/dependency were not fully compatible, as already installed instances were and are working fine.

I have fixed this by updating all depencies and bench to latest, and everything is working fine now.

Hope this works for you as well.

Do post here if you find any alternatives.

Cheers.

**Comment by Nadorml** [comment]
Dears
anyone find solution here ?

**Comment by pujanthakkar** [comment]
Stock balance report requires python version 3.6, we did a upgrade from 3.5 to 3.6 and also updated ubuntu to 18.04 as 16.04 does not support python version above 3.5. 

For me this worked.

**Comment by pujanthakkar** [comment]
> @pujanthakkar I was thinking the same initiatlly that why others aren't experiencing such issue.
> 
> What I assume is that we have installed/upgraded the erpnext at wrong time, when the packages/dependency were not fully compatible, as already installed instances were and are working fine.
> 
> I have fixed this by updating all depencies and bench to latest, and everything is working fine now.
> 
> Hope this works for you as well.
> 
> Do post here if you find any alternatives.
> 
> Cheers.

Yes you are so correct

**Comment by avaiskhatri** [comment]
> @pujanthakkar I was thinking the same initiatlly that why others aren't experiencing such issue.
> 
> What I assume is that we have installed/upgraded the erpnext at wrong time, when the packages/dependency were not fully compatible, as already installed instances were and are working fine.
> 
> I have fixed this by updating all depencies and bench to latest, and everything is working fine now.
> 
> Hope this works for you as well.
> 
> Do post here if you find any alternatives.
> 
> Cheers.

@Nadorml

**Comment by Talleyrand333** [comment]
I have the same issue with generating Stock Balance reports, After clicking on the Generate New Report button,
Python: 3.5
Frappe: 12.5.0
ERPNext: 12.7.0

the prepared reports are not created on the prepared reports list page
instead, going through the error logs I find this error
![April29_6](https://user-images.githubusercontent.com/38866184/80654575-7612bb80-8a74-11ea-88d1-66183d56f729.png)

Has anyone been able to fix this issue yet?

**Comment by clarkejj** [comment]
The 15 Nov post above advises switching to Python 3.6?
