### ISSUE TITLE
V12 contact , add label for each phone  numbers

### ISSUE THREAD

**Issue by me2ne** [frappe/erpnext#19218]
i suggest in phone no of contact add label for each contact so user can select is it mobile number or landline number , of home number or mobile number 2 . ( same as android contact )
so when user want to call we can chose number or when user want to send sms to contact user don't know witch number is mobile witch one is landline .
this problem is for v12 , v11 had separate mobile number in contact

**Comment by crescent28** [comment]
@me2ne You can create a custom field for Mobile no. or Home Number wherever essential.
