### ISSUE TITLE
item kitting

### ISSUE THREAD

**Issue by sheashaa2019** [frappe/erpnext#19219]
ERPNext doesn't support item kitting 
so please mack it feature as required

**Comment by karthikeyan5** [comment]
@sheashaa2019 , have you taken a look at [Product Bundle](https://erpnext.com/docs/user/manual/en/selling/product-bundle) in ERPNext? 

isn't 'Item Knitting' also called 'Product Bundling'?

**Comment by yadavyk** [comment]
@sheashaa2019 , Please refer the [Product Bundle](https://docs.erpnext.com/docs/v13/user/manual/en/selling/product-bundle) feature in ERPNext.
