### ISSUE TITLE
logo not uploading on website in erpnext version 12

### ISSUE THREAD

**Issue by williamsibile** [frappe/erpnext#19220]
Hello All,
Please, i need help in inserting a logo at the website of erpnext version 12, when i upload a logo it does not display at the website interface.
Suggestion will be appreciated.
Thanks in anticipation

**Comment by kennethsequeira** [comment]
@williamsibile where did you upload the logo?

Also, have you posted on https://discuss.erpnex.com?

**Comment by williamsibile** [comment]
The logo was uploaded via the website theme settings, was intended to
appear on the company website as brand logo.

Though, it has been resolved. I had to resize the image and clicked apply
banner image.

Thanks

**Comment by kennethsequeira** [comment]
@williamsibile thanks for the update!
