### ISSUE TITLE
Worker frappe-bench-frappe-web hangs on STARTING

### ISSUE THREAD

**Issue by asem89** [frappe/erpnext#19229]
Hello, I have a problem with our instance of ERPNext since Sunday. Problem started after sudo apt update & upgrade through SSH. What's strange, rollback to LVM snapshot didn't resolve the issue (ERP was fine at time of snapshot creation).
Version-11, Production.

Description:
We cannot login to ERPNext (Sorry! We will be back soon.)
Machine is up and running

Possible problems:
![image](https://user-images.githubusercontent.com/52979388/65969214-b1a8c100-e464-11e9-9517-4f9dcf987a01.png)
web worker is cycling between STARTING and RUNNING 

![image](https://user-images.githubusercontent.com/52979388/65969298-d0a75300-e464-11e9-9b00-5b94deb3dbf5.png)
fail2ban is banning, why? (192.168.0.11 is my ip)

![image](https://user-images.githubusercontent.com/52979388/65969386-f7658980-e464-11e9-8a57-cd7af860d48a.png)
nginx is also having major problems

![image](https://user-images.githubusercontent.com/52979388/65969465-1a903900-e465-11e9-9453-5f90d66ed4b4.png)
gunicorn can't connect

Thank you for any insights. How is it possible, that sudo apt update & upgrade broke the ERP? And it still doesn't work after rolling back to snapshot?

**Comment by fahimalizain** [comment]
Check frappe-bench/logs/web.error.log
Since its cycling between STARTING and RUNNING most probably it is being auto restarted due to a crash. That logs will have more details.

fail2ban might have banned you since none of the requests were successful it went past the threshold. Just do fail2ban-client unban --all

**Comment by asem89** [comment]
Thanks for your response.

Actually, I've already uploaded web.error.log
Here is it once more:
![image](https://user-images.githubusercontent.com/52979388/66028097-a7d29c80-e4fc-11e9-889c-f9307f25b434.png)

As you can see, gunicorn can't connect to 127.0.0.1 on port 80. Why is that?

**Comment by kennethsequeira** [comment]
@asem89 best to post this on the community forum: https://discuss.erpnext.com
