### ISSUE TITLE
Intermittent Item Code [ERPNext: v11.1.61 (version-11)]

### ISSUE THREAD

**Issue by racitup** [frappe/erpnext#19230]
Steps to Reproduce:
- From the Item List create a New Item
- Enter **exactly the same Item Name and Item Code**. Complete all the other fields as required
- Save and Refresh the Item List
- The Item Code column will be **blank**
- The Database will have an Item Code
- Open the Item, go to variants & tick Has Variants
- Create a new Attribute with values
- Go to Make -> Multiple Variants
- Tick some & Make Variants
- I receive the error: **Item Code is required**
Screenshots:
![image](https://user-images.githubusercontent.com/18157195/65979906-11579a00-e46e-11e9-8736-6daa3d6554c1.png)
![image](https://user-images.githubusercontent.com/18157195/65979857-f84ee900-e46d-11e9-909d-366ec1533cda.png)

**Comment by nameduser0** [comment]
Lol, don't bother looking into it and fixing it, just close it 2 years later & *hope for the best* 😄
