### ISSUE TITLE
AttributeError: ‘EmployeeAdvance’ object has no attribute ‘conversion_rate’

### ISSUE THREAD

**Issue by alkuhlani** [frappe/erpnext#19239]
Hi,
I get this error
`AttributeError: ‘EmployeeAdvance’ object has no attribute 'conversion_rate’`
when I click **Payment** in create menu
after I made submit for **Employee Advance**

please any help,
thank you in advance.

==========================
**ERPNext: v12.1.5 (version-12)
Frappe Framework: v12.0.15 (version-12)**

**Comment by nextchamp-saqib** [comment]
@alkuhlani  
~If Employee Advance has Advance Account is Cash Account and doesn't have Mode of Payment set as Cash then you will face this error. You can try setting Mode of Payment until we resolve this issue.~

P.S. If you set default Bank Account then you won't face this issue.

Thanks.
