### ISSUE TITLE
[Paid Development] 

### ISSUE THREAD

**Issue by santoshbb** [frappe/erpnext#19258]
An option should be inserted in Job Card as shown in picture-1. If we click on stock entry (red colored in below picture) it should open stock entry (manufacture) against the job card.
Options are as below

Use Multi level BOM = checked
Stock Entry (Manufacture) = should follow the BOM mentioned in raw material table of BOM as shown in 2nd picture.
Stock Entry (Manufacture) against Job Card should be optional for Work Order

![image](https://user-images.githubusercontent.com/10789840/66264560-45d1aa00-e810-11e9-9fc3-5f5bfa51f009.png)

![image](https://user-images.githubusercontent.com/10789840/66264563-5e41c480-e810-11e9-906e-4d0f663ecf3c.png)

![image](https://user-images.githubusercontent.com/10789840/66426554-c2d06f80-ea1a-11e9-8bc2-766f9b4eabba.png)

Santosh Baburao
Taazur Group
Cell: +966 50 632 5899

**Comment by Muzzy73** [comment]
For any paid development please post it to the job page. You most probably won't get any response here.

**Comment by santoshbb** [comment]
Ok, I do. Thanks.
I am getting calls from developers and working on it.

**Comment by sharmanakul** [comment]
@santoshbb I hope this is already developed. Would you like to open-source this feature and help the community?
