### ISSUE TITLE
 version upgrade to 12 for your account xvalves.erpnext.com

### ISSUE THREAD

**Issue by vaithy27** [frappe/erpnext#19263]
Hello Sir,
This below message is received on 27-09-2019 but till know our account is not upgrade, and we also send emails to your support and sales mail id, but we not received any reply form your side  

(Automatic version upgrade for your account xvalves.erpnext.com requested by vaithy@flowqautomation.com scheduled on 2019-09-27 has failed.

Our engineers will be upgrading your account to version 12 manually before 2019-09-30. If you have any queries, please contact us on support@erpnext.com)

**Comment by kennethsequeira** [comment]
@vaithy27 kindly raise a support ticket for this.
