### ISSUE TITLE
Email Digest: frappe.exceptions.ValidationError: No items to be received are overdue

### ISSUE THREAD

**Issue by yrestom** [frappe/erpnext#19272]
There is an error in the Email Digest it does not sent and I have this error log:
```
 {'method_name': 'erpnext.setup.doctype.email_digest.email_digest.send', 'log': <function log at 0x7fdb4dbae598>, 'retry': 0, 'is_async': True, 'user': 'Administrator', 'kwargs': {}, 'job_name': 'erpnext.setup.doctype.email_digest.email_digest.send', 'event': 'daily', 'method': <function send at 0x7fdb4d8c70d0>, 'site': 'site1.local'}
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 99, in execute_job
    method(**kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/setup/doctype/email_digest/email_digest.py", line 788, in send
    ed_obj.send()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/setup/doctype/email_digest/email_digest.py", line 57, in send
    msg_for_this_recipient = self.get_msg_html()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/setup/doctype/email_digest/email_digest.py", line 102, in get_msg_html
    frappe.throw(_("No items to be received are overdue"))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 360, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 346, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 315, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: No items to be received are overdue
```
I turned off (Purchase Orders Items Overdue) and i save and then pressed send now, it showed me that it sent the e-mail, but after a short time the entire system stopped and it was showing this message:
https://discuss.erpnext.com/uploads/default/original/3X/4/5/455cf52f10dd2b2722dd42ac49fc2f8a17072fe8.jpg

then i use `sudo supervisorctl restart all` to make it work again.

Installed Apps
ERPNext: v12.1.6 (version-12)
Frappe Framework: v12.0.16 (version-12)

Thank you

**Comment by yrestom** [comment]
This is a related discussion :
https://discuss.erpnext.com/t/error-in-the-email-digest-it-does-not-sent-v12/53595

**Comment by RoyIrwan** [comment]
Confirmed, I have exactly the same behavior.

```
Installed Apps
ERPNext: v12.1.6 (version-12)
Frappe Framework: v12.0.16 (version-12)
```

**Comment by Ponyooooo** [comment]
May I know if this issue was resolved on any version? Since we are currently experiencing it on 

ERPNext: v12.12.0 (version-12)
Frappe Framework: v12.10.0 (version-12)

**Comment by fecoderchinh** [comment]
Hello, do we have any update for this issue?

ERPNext: v14.0.0-dev (version-14)
Frappe Framework: v14.0.0-dev (version-14)

**Comment by littlebunyip** [comment]
Same issue here with v14... Wondering why this is closed? Did you find a solution?

ERPNext: v14.3.0 (version-14)
Frappe Framework: v14.11.1 (version-14)
