### ISSUE TITLE
Edit default Cost Centre make issue

### ISSUE THREAD

**Issue by vuongkhanhtoan** [frappe/erpnext#19287]
I tested to change the name of the Cost Centre at root and found out that it make some error when trying to add some more New Domain. New Domain it don't recognize the new name of the Cost Cetre.

**Comment by kennethsequeira** [comment]
@vuongkhanhtoan kindly add more information such as steps to replicate along with screenshots and/or gifs which will explain the issue more clearly.

If it is a functional query you can also post on https://discuss.erpnext.com
