### ISSUE TITLE
New Employee creation issue

### ISSUE THREAD

**Issue by Suprazz** [frappe/erpnext#19285]
I'm trying to create a new Employee for timesheet. 

So I create it and it's never listed under Employee List. If I try to select the new Employee in the time sheet, it's not listed either. I tried a reload and refresh and still not there.
But if I create it again and enter in the Employee doctype I notice the EMP/000X number increase...

**Comment by kennethsequeira** [comment]
@Suprazz check your user permissions. This seems more of a configuration related problem. Also try posting on the community forum: https://discuss.erpnext.com

**Comment by Suprazz** [comment]
I did that with my admin user who has all permissions enabled. I cannot see the other employees in the HR module, employee. But I'm the one who is creating it...
If I go to user permission, create a new permission to Allow Employee, for Value the new Employee, then it works. So it look like a bug to me. Why can't I see the employee list that I created?
