### ISSUE TITLE
Passive Italian eInvoicing

### ISSUE THREAD

**Issue by PawanMeh** [frappe/erpnext#19334]
- [x] Read the XML input files
- [x] Create Supplier, Address, Contacts and Purchase invoices from files
- [x] Attach the processed file to the respective doctype
- [x] Create custom fields
- [x] Create patch for regional doctype

![Passive_Invoicing](https://user-images.githubusercontent.com/20460498/66945290-6b5e7f00-f06c-11e9-99b9-2c166a697b6b.gif)

**Comment by PawanMeh** [comment]
Sent [PR](https://github.com/frappe/erpnext/pull/19335)

**Comment by fthobe** [comment]
Hey, how does this handle pre-existing suppliers and addresses, is there any match?

**Comment by PawanMeh** [comment]
1. If supplier already exists with Tax ID a new supplier is not created (code lines 226-227)
2. If address_line1 and pin code match with an existing address, the same address is used (code lines 298-300)

You may refer to [pull request](https://github.com/frappe/erpnext/pull/19335)

**Comment by fthobe** [comment]
Hey @PawanMeh , thank you for the link to your commit!

It's a great piece of work! There are two issues:

- As mentioned in #39494 the implantation on customer / supplier fields is problematic as such integration is problematic with multiple supplier invoice addresses as foreseen in the Italian invoicing standard. 

To give you multiple examples: 
Franchise: one contract multiple fiscal entities such as McDonald's branches or farmacy chains. It's an issue for many different cases in Italy. The process should contain an option for reverse lookup of the supplier based on address as the fiscal ID could be (but not always) a 1 supplier to many fiscal ID relations. The right point to look for fiscal id is therefor the address. 

- the second problem is the item code, item codes can be different between company and supplier. Therefore the process should contain a reverse lookup on the supplier code of an item. 

What do you think?
