### ISSUE TITLE
Moving Tasks using the Gantt Chart doesn't function correctly

### ISSUE THREAD

**Issue by bitaccesscomau** [frappe/erpnext#19348]
When moving tasks using the Gantt view the task will have its' date set to 1 month ago and task duration to set to 1 day. If the task has tasks dependant on it it will also recursively reset the linked tasks. This is both in the Gantt view and visible on the the task properties itself.

Please see order of actions below with screenshots. (Movement was performed from current day to next calendar day by dragging the centre of the task).

1. Initial task layout.
![Screen Shot 2019-10-19 at 5 59 04 pm](https://user-images.githubusercontent.com/56752183/67139340-e907d200-f29a-11e9-82b2-d03c0f0464ef.png)
2. Movement of task 2 (Initial Scoping Session)
![Screen Shot 2019-10-19 at 5 59 11 pm](https://user-images.githubusercontent.com/56752183/67139346-ff159280-f29a-11e9-950b-70c6ee7dd0b2.png)
3. Refresh
![Screen Shot 2019-10-19 at 5 59 22 pm](https://user-images.githubusercontent.com/56752183/67139348-0a68be00-f29b-11e9-97e1-5f242a0a2c22.png)
4. Movement of Task 1 (Create Work order) + Refresh
![Screen Shot 2019-10-19 at 5 59 42 pm](https://user-images.githubusercontent.com/56752183/67139366-308e5e00-f29b-11e9-9927-07b5b8777564.png)
5. Movement of Task 1 again to test date movement
![Screen Shot 2019-10-19 at 5 59 59 pm](https://user-images.githubusercontent.com/56752183/67139376-53b90d80-f29b-11e9-9fb3-53eff7e9a1a6.png)
6. Final view.
![Screen Shot 2019-10-19 at 6 08 55 pm](https://user-images.githubusercontent.com/56752183/67139403-967ae580-f29b-11e9-94d5-c6dcf8ea3c03.png)

If you require further testing or feedback please let me know.

**Comment by bitaccesscomau** [comment]
This references #17923 with more information.

**Comment by clarkejj** [comment]
Thanks for reporting this - please post your observations on discuss too for all to benefit and respond to help debug this.

To relate both conversations be sure to add cross links here and there too.

**Comment by bitaccesscomau** [comment]
Some additional research has lead me to this pull request: https://github.com/frappe/gantt/issues/128
(More information and issue reference here: https://github.com/frappe/gantt/pull/126)

Seems like it is an issue with mouse events?

I'll try a merge from that link on my instance and report back my findings.

**Comment by clarkejj** [comment]
Good info - I urge you to post a link to this on discuss.ernext.com to inform and engage the community!

**Comment by bitaccesscomau** [comment]
Thanks for your feedback, I have opened this discussion here to gather more input:

https://discuss.erpnext.com/t/moving-tasks-using-the-gantt-chart-doesnt-function-correctly/54205

**Comment by valentincauro** [comment]
Excatly the same issue, really problematic !

**Comment by wojosc** [comment]
I have noticed that there are big differences in the manipulation of tasks in gantt view depending on the browser I use. In Chrome is works to a certain extent: You can move a task and change the length. After that manipulation fails at some point.

In Firefox the task will just jump to some random spot and then be unusable in gantt view.

**Comment by Achder** [comment]
Any updates on this?

**Comment by dvdl16** [comment]
[There is an open PR for this](https://github.com/frappe/gantt/pull/128), but it hasn't been merged yet

**Comment by safwansamsudeen** [comment]
@ankush this can be closed - will be fixed in [the revamp of Frappe Gantt](https://github.com/frappe/gantt/pull/393)
