### ISSUE TITLE
Show/Hide Cards globally not working!

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#19378]
Hi ,

After upgrading an instance to V12, all users have ALL cards appearing on the desk even when they have no permission for any documents within that module! Considering that V12 is already in production use, this is a bug that requires urgent fixing please

Thanks

**Comment by Olawale1** [comment]
Hi,

Migrating environment to python 3 seems to help get the permission based module visibility part working

https://discuss.erpnext.com/t/erpnext-python-3/33492

The global hiding still needs to be looked into though. At least now, not ALL modules are visible to all users

Thanks

**Comment by Olawale1** [comment]
I initially thought migrating the environment to python 3 solved the issue but apparently it didn't!

Why should users see all modules on their desktop when they have no business there? It's not feasible to expect those with a large number of users to do this individually. This really needs to be fixed fast

Thanks

**Comment by clarkejj** [comment]
To post this to discuss will benefit and inform the whole community who may help expedite a fix!

**Comment by Olawale1** [comment]
Thanks @clarkejj 

https://discuss.erpnext.com/t/multiple-issues-with-v12-desktop/54063

**Comment by toofun666** [comment]
The bench-manager application is not showing the cards. You can only access the modules via the Global Search.

**Comment by crescent28** [comment]
@Olawale1 Show/hide seems to be working fine.

**Comment by crescent28** [comment]
https://github.com/frappe/frappe/pull/8692
