### ISSUE TITLE
erpnext is slow after update to latest v12 develop

### ISSUE THREAD

**Issue by onlinebizsoft** [frappe/erpnext#19383]
I was using erpnext v12 develop before v12 were released and all pages were fast. 

Yesterday, I just ran "bench update" to update to latest v12 develop and I found that all pages that navigated from Desk are slow because this request
"api/method/frappe.desk.moduleview.get" - it takes 7-8 seconds every time.

Other pages seems to be normal.

**Comment by zerodiscount** [comment]
My Accounts card has also disappeared after latest update (even though it is enabled under show cards). I have to go to search bar and Open Accounts.

**Comment by Thunderbottom** [comment]
@zerodiscount the fix for showing the accounts card has been pushed here: https://github.com/frappe/erpnext/pull/19409

it should be merged as soon as the tests are done.

**Comment by adityahase** [comment]
@onlinebizsoft We've fixed this with https://github.com/frappe/frappe/pull/8664 and https://github.com/frappe/frappe/pull/8665
