### ISSUE TITLE
Comments wont flow to customer from Quotation in version 11

### ISSUE THREAD

**Issue by Ravn10** [frappe/erpnext#19387]
![image](https://user-images.githubusercontent.com/29272682/67273614-7128ea00-f4dc-11e9-8c14-33a4e5a0e931.png)
The comments wont flow to customer doctype 
i guess this is because of the customer field being renamed to party name in version 11 
kindly fix this issue as all the communication is being lost from customer page 
@nabinhait

**Comment by harshit-30** [comment]
Comments are not designed to flow from one DocType to another. Creating a Customer from Quotation will only transfer the field values and not the comments.
