### ISSUE TITLE
In HR Module Allow to Use Calander Year

### ISSUE THREAD

**Issue by Jaliya** [frappe/erpnext#1938]
Presently ERPNext HR module calander start from the start date of the Fiscal Year. In Sri Lanka Leave Year starts on Jan 1st and Fiscal Year on April 1st. I hope there are many countries having this practice and suggest to implement it at your earliest.

**Comment by rmehta** [comment]
- [ ] keep allocation dates flexible.

**Comment by rmehta** [comment]
@felixvarghese done in 6.6.7 Thanks!
