### ISSUE TITLE
Bug: No module named 'erpnext.accounts.notification.expense_claim_request.expense_claim_request'

### ISSUE THREAD

**Issue by flexy2ky** [frappe/erpnext#19399]
The Error shows up when trying to submit an expense claim. Full traceback below:

> Traceback (most recent call last):
>   File "/home/octo5/frappe-bench/apps/frappe/frappe/email/doctype/notification/notification.py", line 321, in evaluate_alert
>     alert.send(doc)
>   File "/home/octo5/frappe-bench/apps/frappe/frappe/email/doctype/notification/notification.py", line 120, in send
>     self.load_standard_properties(context)
>   File "/home/octo5/frappe-bench/apps/frappe/frappe/email/doctype/notification/notification.py", line 253, in load_standard_properties
>     module = get_doc_module(self.module, self.doctype, self.name)
>   File "/home/octo5/frappe-bench/apps/frappe/frappe/modules/utils.py", line 37, in get_doc_module
>     return frappe.get_module(module_name)
>   File "/home/octo5/frappe-bench/apps/frappe/frappe/__init__.py", line 808, in get_module
>     return importlib.import_module(modulename)
>   File "/home/octo5/frappe-bench/env/lib/python3.6/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
> ModuleNotFoundError: No module named 'erpnext.accounts.notification.expense_claim_request.expense_claim_request'

This bug surfaced after updating to the latest version. Version info below:

ERPNext: v12.1.6 (version-12)
Frappe Framework: v12.0.16 (version-12)

**Comment by clarkejj** [comment]
See https://discuss.erpnext.com/t/error-no-module-named-expense-claim-request/53812

**Comment by clarkejj** [comment]
Resolved by recompiling server- and client-side source code - 
https://discuss.erpnext.com/t/integrated-notifications-center/54220/23
