### ISSUE TITLE
v12.04: Typeerror: unsupported operand type(s) for:- Float and Nonetype

### ISSUE THREAD

**Issue by raymondliew1992** [frappe/erpnext#19397]
## Typeerror: unsupported operand type(s) for:- Float and Nonetype in both "Request Raw Material" & "Production Plan"

I encountered this error when I was trying to create "Request Raw Material" via Sales Order as I have raised in the forum: https://discuss.erpnext.com/t/v12-request-raw-material-typeerror-unsupported-operand-type-s-for-float-and-nonetype/53411

The second time I encounter this error was in "Production Plan" when I selected a warehouse in the "For Warehouse" field as shown in the picture below:

![image](https://user-images.githubusercontent.com/52439119/67448713-6be9ad80-f64a-11e9-964f-b2dd733ee1b9.png)

This error will not appear in Production Plan, if I checked "Ignore Existing Projected Quantity".

## Steps to reproduce the issue for Production Plan

1. Get Items from Sales Order
2. Select two dates (From Date & To Date)
3. Get Sales Order
4. Get Items from Work Order
5. Check "Include Exploded Items"
6. Check "Include Non Stock Items"
7. Select any Warehouse in the Material Request Planning -> For Warehouse

**Comment by deepeshgarg007** [comment]
@raymondliew1992  Closing this issue. If the issue still persists in the latest version-13 or above then please reopen a new issue
