### ISSUE TITLE
Cannot save sales order dates when creating sales order through quotation

### ISSUE THREAD

**Issue by ioweb-gr** [frappe/erpnext#19410]
## Description of the issue
Since upgrading I'm unable to save sales orders with the following error:
`due date cannot be before posting date`

![image](https://user-images.githubusercontent.com/20220341/67568217-46d16980-f734-11e9-84a1-bb083fafe389.png)

## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 12.x.x-develop
frappe 12.x.x-develop
fatal: Not a git repository (or any of the parent directories): .git
```

## Steps to reproduce the issue
I haven't found what is causing it so I can reproduce but for me it happens on all sales orders which are created through a quotation. So I open the quotation and then click on make sales order. After I try to save and it causes this error. 

I can see however that creating a sales order then fetching data from quotation doesn't cause this issue. 

### Observed result
An error message appears

### Expected result
The order is saved correctly 

OS version / distribution, `ERPNext` install method, etc.

Ubuntu 16.04
Easy Install Script

**Comment by clarkejj** [comment]
Hi be sure to post this to discuss, to inform and benefit a wider audience to resolve this thanks!

**Comment by ioweb-gr** [comment]
@clarkejj Hi, I don't see the point of taking this issue to discuss since this looks like a bug and not an issue that just needs configuration

**Comment by clarkejj** [comment]
"since this looks like a bug and not an issue that just needs configuration"

Fair enough suit yourself.  Nor can I see your point here, your reasoning escapes me

**Comment by ioweb-gr** [comment]
@clarkejj No offence meant, my reasoning is fairly simple: 

- This is an issue imho,
- This tab in github is called issues 
- Github issues offer easier tracking for pull requests / comments and references.

In the past i've opened a lot of discussions on discuss regarding bugs which always led to a final response "Please open an issue on github" at an astonishing rate of 100% wasting my time and all the discuss readers' time.

So I will agree that we disagree to where this belongs.

**Comment by ChristopherMeyering** [comment]
I have the same issue.
As far as i was able to debug this one it only happens when the posting date and the due date are in 2020.
This is a showstopper for us!

**Comment by deepeshgarg007** [comment]
@ioweb-gr  Closing this issue. If the issue still persists in the latest version-13 or above then please reopen a new issue
