### ISSUE TITLE
Make possible to create Help Articles with HTML code

### ISSUE THREAD

**Issue by lphm** [frappe/erpnext#19426]
Hello,
I have not found where I can switch Wysiwyg edtor to HTML Editor.
It will be nice to enter sometimes HTML code because we have classes that applied to some text blocks.
Thanks

**Comment by lphm** [comment]
To given an another example : I want to integrate IFRAME into Help article body but I cannot...

**Comment by kennethsequeira** [comment]
@lphm 

You can update the field via customize form:

  
![image](https://user-images.githubusercontent.com/33246109/67957400-8e1b9680-fc1b-11e9-90ca-c62c5ad82cfe.png)

![image](https://user-images.githubusercontent.com/33246109/67957454-a2f82a00-fc1b-11e9-92a3-ece692115fc5.png)
