### ISSUE TITLE
[V12] Cannot change Project status

### ISSUE THREAD

**Issue by asem89** [frappe/erpnext#19425]
## Description of the issue
When trying to change the Project status it reverts back to Open
Please see the attached GIF recording of the bug
![bug  cannot change project status 1](https://user-images.githubusercontent.com/52979388/67679830-46321080-f98a-11e9-8902-232e667a1574.gif)
![bug  cannot change project status 2](https://user-images.githubusercontent.com/52979388/67679831-46321080-f98a-11e9-83e9-564d379348b9.gif)

## Context information (for bug reports)
If I change the default "Open" status to anything else, I cannot create a new Project because project status "Open" hasn't been found

**Output of `bench version`**
```
adr@erpstage:~/frappe-bench$ bench version
erpnext 12.1.8
frappe 12.0.17

```

## Steps to reproduce the issue

1. Please see the attached GIF recording
2. Try to change the Project status

### Observed result
Project reverts to "Open" status
### Expected result
Project changes to desired status
### Stacktrace / full error message

```
There are no error messages displayed nor in logs
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.
Ubuntu 18.04.2

**Comment by asem89** [comment]
Hello? Is it only me who has the bug?
Thank you kindly for any advice.

**Comment by asem89** [comment]
Is there anything a simple user like me could do to help or aid in finding the cause?
We will do what we can.

**Comment by asem89** [comment]
Hello, I have an update:

After updating to:
ERPNext: v12.2.2 (version-12)
Frappe Framework: v12.0.20 (version-12)

The problem is still there. I cannot change status of any Project.

Thank you kindly for your advise.

**Comment by clarkejj** [comment]
Link to forum https://discuss.erpnext.com/t/cannot-change-project-status-link-to-issue-github/55953

**Comment by wojosc** [comment]
Hello @asem89 in v12 they have added some more completion methods. This needs to be set to manual to be able to do what you would like to.
![Peek 2019-12-18 03-21](https://user-images.githubusercontent.com/22279621/71050494-a309a600-2145-11ea-9e60-5867103423f0.gif)

**Comment by wojosc** [comment]
Hi @hrwX, this can be closed. See the link prior to my post.

Best

**Comment by wojosc** [comment]
Hi @nabinhait this can be closed. Thanks.
