### ISSUE TITLE
Validating customer address even though address is present in the document

### ISSUE THREAD

**Issue by nick9822** [frappe/erpnext#19437]
This issue is encountered when there was a Sales Order of a Customer with some shipping address, later the same customer ordered again through another Sales Order with a different shipping address. This customer and some other always have different shipping addresses and we do not create new address every time. 

The problem happens when we create delivery note from the Sales Order, Delivery Note should carry addresses from the Sales Order and it does but in the local mode. Once we save it, it replaces customer address with the current updated address. I am not sure whether its deliberate or a bug but on  Selling Controller line#47 
 https://github.com/frappe/erpnext/blob/bcf107b9f78e6b15065b4ce9694560ec54a2dd28/erpnext/controllers/selling_controller.py#L47 we are validating customer address.
https://github.com/frappe/erpnext/blob/bcf107b9f78e6b15065b4ce9694560ec54a2dd28/erpnext/controllers/selling_controller.py#L374-L383 
Shouldn't we check on line#382 for address_display_field whether it holds any value? `if self.get(address_field) and not self.get(address_display_field):`

JFYI when I tested with this change, it works perfectly for the scenario given.

**Comment by deepeshgarg007** [comment]
@nick9822  Closing this issue. If the issue still persists in the latest version-13 or above then please reopen a new issue
