### ISSUE TITLE
Bug: Arrow Selection rendering is broken

### ISSUE THREAD

**Issue by mariotruss** [frappe/erpnext#19435]
![image](https://user-images.githubusercontent.com/24277433/67760063-e0549000-fa40-11e9-9bdd-2cf207fe63c9.png)
## Description of the issue
For custom DocTypes, select arrow is displayed buggy in creation-dialog.

## Additional information
ERPNext: v12.1.7 (HEAD)
Frappe Framework: v12.0.17 (HEAD)
OSX

**Comment by hrwX** [comment]
Fixed https://github.com/frappe/frappe/pull/8702
