### ISSUE TITLE
Journal Entry creation form Sales invoice does not copy data

### ISSUE THREAD

**Issue by Tropicalrambler** [frappe/erpnext#19439]
When user presses journal entry "+" button from Sales Invoice, user expects the customer data, amount and other information to be copied to journal Entry, only to modify specific fields like date and remarks. 

ERPNext v12.0.16 (version-12)  (And 11)  is not copying that data.

**Comment by crescent28** [comment]
The Date gets fetched in the Journal Voucher, the rest of the fields in JV are not linked. The standard field user remark in the Sales invoice is not linked to the Remark field in the JV.
