### ISSUE TITLE
For warehouse field ignored while Material Request Planning

### ISSUE THREAD

**Issue by AtriDev** [frappe/erpnext#19458]
## Context information (for bug reports)

```
ErpNext version 12
frappe version 12
```

## Steps to reproduce the issue

1. Create new Production plan, Get sales order, Select item to produce.
2. Select Finished Good warehouse in Select Items to Manufacture Section
3. Select Stores as in Material Request Plan Item Section
4. Click on Get Raw material for production.

### Observed result
It shows finished good warehouse in Material Request Plan Item section.

### Expected result
It should show stores warehouse in Material Request Plan Item section.

### Screenshots
<img width="1280" alt="Screenshot 2019-10-30 at 6 34 39 PM" src="https://user-images.githubusercontent.com/56126302/67861370-192a5d00-fb46-11e9-8e47-fcb16061067f.png">

## Additional information
ERP Instance is hosted on ErpNext cloud

**Comment by deepeshgarg007** [comment]
@AtriDev  Closing this issue. If the issue still persists in the latest version-13 or above then please reopen a new issue
