### ISSUE TITLE
Wrong Warehouse fetched during Production Plan

### ISSUE THREAD

**Issue by AtriDev** [frappe/erpnext#19457]
## Context information (for bug reports)

```
ERPNext ==> V12.1.8(Version-12)
Frappe ==> V12.0.17(Version-12)
```

## Steps to reproduce the issue

1. Create new production plan
2. Select sales order
3. Click on Get Items for work-order.
4. Click on Get Raw Materials for Production

### Observed result
Wrong warehouse fetched instead of item default.
<img width="1280" alt="Screenshot 2019-10-30 at 6 06 57 PM" src="https://user-images.githubusercontent.com/56126302/67859795-758b7d80-fb42-11e9-8797-ac5ac84a40c2.png">

<img width="1280" alt="Screenshot 2019-10-30 at 6 07 39 PM" src="https://user-images.githubusercontent.com/56126302/67859814-7fad7c00-fb42-11e9-800b-7eb55be06a9f.png">

### Expected result
Warehouse mentioned in item default must be fetched.

## Additional information

Our instance is on ErpNext cloud.

**Comment by deepeshgarg007** [comment]
@AtriDev  Closing this issue. If the issue still persists in the latest version-13 or above then please reopen a new issue
