### ISSUE TITLE
v12 Customizable Desk categories

### ISSUE THREAD

**Issue by mudux** [frappe/erpnext#19468]
Hello,

_**Proposal**_
That the desk categories be flexible to the point where a user can rename or organise the order of categories to suit one's needs..

In other words having the ability to reorganize the order of the four main categories ('Modules', 'Domains', 'Places', 'Administration') and even be able to rename them altogether.

The reorganisation can be through the same drag and drop mechanism employed within each category. While renaming can be via a dialogue box when a category handle is  clicked

**_Currently_**
There are only four and with rigid order namely :
`module_categories: ['Modules', 'Domains', 'Places', 'Administration']`

**_Use case_**
There are situations one may need _Administration_ to be on top or perhaps instead of _Modules_ category one may want to call it _HMIS_ instead

Thanks

**Comment by kennethsequeira** [comment]
@mudux you can check the upcoming desk features under: https://github.com/frappe/frappe/projects/3

https://discuss.erpnext.com/t/redesigning-desk/59105/57

You can give feedbacks on these threads as to changes and simplification you'd like.

As it is, there won't be any changes to desk in v12 per say, but would be added to future versions.
