### ISSUE TITLE
DATE AND NUMBER FORMAT does not apply for Custom DocTypes

### ISSUE THREAD

**Issue by mariotruss** [frappe/erpnext#19460]
## Description of the issue
In System Setting I have applied setting that lead to number formatting in this way:
![image](https://user-images.githubusercontent.com/24277433/67872437-3b19e480-fb32-11e9-9f35-00a90053918f.png)

In quotations this works perfectly fine, also in Report view.
![image](https://user-images.githubusercontent.com/24277433/67872486-4ec54b00-fb32-11e9-9909-25162eeba48f.png)

I have created a custom DocType without changing the settings and using the currency field type but I can not use the #.###,## format here. It requires still #,###.##
![2019-10-30 16 29 49](https://user-images.githubusercontent.com/24277433/67872747-b11e4b80-fb32-11e9-8614-5a93387769cf.gif)

And in report it's also broken:
![image](https://user-images.githubusercontent.com/24277433/67872822-cb582980-fb32-11e9-9b4e-ba0d2c1398a0.png)
## Context information (for bug reports)
ERPNext: v12.1.7 (HEAD)
Frappe Framework: v12.0.17 (HEAD)
## Related https://github.com/frappe/erpnext/issues/19255

**Comment by xaha24** [comment]
The same problem exists in the current version for all DocTypes. 
erpnext 12.1.8
frappe 12.0.18
The fix https://github.com/frappe/erpnext/issues/19255 might have been wrong. Only the #,###.## format is still working correctly.

![ERPNext-NumberFormat Issue](https://user-images.githubusercontent.com/3277944/67937839-95688300-fbce-11e9-9563-e3ae2bc36495.gif)

**Comment by nextchamp-saqib** [comment]
Could you try this [PR](https://github.com/frappe/frappe/pull/8719) and check if everything works fine?

**Comment by mariotruss** [comment]
I can not judge. There are no image or anything in order to see the result. @thefalconx33

**Comment by nextchamp-saqib** [comment]
@MarioMeetsWorld The global number format doesn't affects formatting of a currency field. Currency fields uses global currency's number format. So you can change currency's number format.

P.S Global number format is used for float fields.

**Comment by mariotruss** [comment]
@thefalconx33 I did not know they are not connected. I changed format in currency and now it works. Thanks both of you. Just asking. If I choose currency a field and change number format for EUR. How does the field know what currency I am using and what format to apply? For example. We use EUR und USD. Both have different formats. How can I control what format is used in a DocType if I can only choose currency but can not which one.

**Comment by xaha24** [comment]
Thanks it solves my problem. 
For sales orders, e.g. you choose explicitly in which currency the order is issued. For 
quotation and invoices, there is also a section "CURRENCY AND PRICE LIST" where you can set the currency.

**Comment by nextchamp-saqib** [comment]
> @thefalconx33 I did not know they are not connected. I changed format in currency and now it works. Thanks both of you. Just asking. If I choose currency a field and change number format for EUR. How does the field know what currency I am using and what format to apply? For example. We use EUR und USD. Both have different formats. How can I control what format is used in a DocType if I can only choose currency but can not which one.

While editing DocType, in any currency field's "options" you can specify a currency.
Eg.

![Screenshot 2019-11-04 at 10 52 27 PM](https://user-images.githubusercontent.com/25369014/68142628-d60d2700-ff55-11e9-95f4-ea409600a843.png)

The "currency" written in the options column of "Net Total "is actually a Link field. So selecting EUR in that link field will make the "Net Total" be formatted into EUR's number format

**Comment by wojosc** [comment]
I'm not sure if it's entirely the same but https://discuss.erpnext.com/t/v12-1-6-decimals-in-currencies-not-working/53486/35 seems to be fixed.

**Comment by toofun666** [comment]
> I'm not sure if it's entirely the same but https://discuss.erpnext.com/t/v12-1-6-decimals-in-currencies-not-working/53486/35 seems to be fixed.

Actually it is not.
