### ISSUE TITLE
Item selection broken after saving without mandatory field.

### ISSUE THREAD

**Issue by mariotruss** [frappe/erpnext#19467]
## Description of the issue
I can not select items after i missed filling them intially and hit save button. This error occurs when saving a DocType that contains items childtable. In this case Quotation. 
![2019-10-31 12 54 14](https://user-images.githubusercontent.com/24277433/67944791-9a80fe80-fbdd-11e9-8331-c5884c7a5031.gif)
## Steps to reproduce the issue
1. Create Quotation or Invoice and save without mandatory items. Error Dialog appears.
2. Try selecting item.
### Observed result
Field will get blank automatically after 1-2 seconds.
Only fix is to refresh with **cmd+r** and reenter everything again.

### Expected result
I can select the item normally.

### Stacktrace / full error message
No JS error in console and all request are working properly (Status: 200).
![image](https://user-images.githubusercontent.com/24277433/67944484-d798c100-fbdc-11e9-8848-fc4108dada80.png)

## Context information (for bug reports)
ERPNext: v12.1.7 (HEAD)
Frappe Framework: v12.0.17 (HEAD)

**Comment by hrwX** [comment]
@MarioMeetsWorld I was not able to replicate this Issue locally. Can you send me the Version number for Frappe and ERPNext.
![quo](https://user-images.githubusercontent.com/7310479/71514177-7aab4580-28c3-11ea-9be9-e40ed93a7ecd.gif)

**Comment by mariotruss** [comment]
Try log into our test instance, maybe that will help to understand.

**Comment by deepeshgarg007** [comment]
@mariotruss  Closing this issue. If the issue still persists in the latest version-13 or above then please reopen a new issue
