### ISSUE TITLE
Item Group Specification in correct order when copied over in Item

### ISSUE THREAD

**Issue by FCPLCRF** [frappe/erpnext#19471]
## Description of the issue
A multiline Website Specification is made in an Item Group but when copied to an Item (within that Group) it is in an incorrect order. It is reproducible and repeatable.
## Context information (for bug reports)

**Output of `bench version`**
```
ERPNext: v12.1.8 
Frappe Framework: v12.0.18 
```

## Steps to reproduce the issue
How I found the Error;
1. Open an Item Group
2. Enter a a number of Specification rows (pay attention to the Row number and Content of the Row)
3. Save it, refresh to be sure its in and correct.
4. Open an Item that has its Group the same as the Group you just entered the Website Specification template
5. Enable Web Show in Website
6. Expand Website Specification to see the entry fields
7. Press 'Copy from Item group'
8. Observe the Row and Content ordering, its different to the template in Item Group Website Specification
9. Save the Edited Item, refresh to make sure its changed and the row number, order is the same as just observed.
9. Go to view Website, pull up the Item with the Website Specification, Observe the Website Specification section. It also (naturally) is correct with respect to the item but incorrect with respect to the Item Group Website Specification template.

### Observed result
From the Item :
![ERPNext V12 Item Website Specification copied from Group](https://user-images.githubusercontent.com/57245184/68002604-9b309800-fca4-11e9-8949-31a0023a883a.png)
and the Website display is:
![ERPNext V12 Item Specification Web Page result](https://user-images.githubusercontent.com/57245184/68002625-b1d6ef00-fca4-11e9-803a-f6ed90acdadc.png)

### Expected result
From the Item Group template:
![ERPNext V12 Item Group Website Specification Entry](https://user-images.githubusercontent.com/57245184/68002638-bd2a1a80-fca4-11e9-8374-5083301044e6.png)

### Stacktrace / full error message
I observed no error on the VM machine output window.
```
(paste here)
```

## Additional information

Running Windows 10, Using VirtualBox 6.0.14, VM., Ubuntu 16.04
Installed Apps
ERPNext: v12.1.8 (version-12)
Frappe Framework: v12.0.18 (version-12)

**Comment by deepeshgarg007** [comment]
@FCPLCRF  Closing this issue. If the issue still persists in the latest version-13 or above then please reopen a new issue
