### ISSUE TITLE
V12.1.8 Customer Portal: Customer unable to submit Issue 

### ISSUE THREAD

**Issue by raymondliew1992** [frappe/erpnext#19472]
## In the Customer Portal, customers could not submit Issue in the customer portal. For more info (screenshots), refer to the forum post: https://discuss.erpnext.com/t/v12-1-8-customer-portal-customer-unable-to-submit-issue/54428

**Comment by deepeshgarg007** [comment]
@raymondliew1992  Closing this issue. If the issue still persists in the latest version-13 or above then please reopen a new issue
