### ISSUE TITLE
bug: on Item change UOM not updated 

### ISSUE THREAD

**Issue by jigneshpshah** [frappe/erpnext#19483]
**Environment :**
ERPNext: v12.1.8 (version-12)
Frappe Framework: v12.0.18 (version-12) 

Item Table of the below doctypes affected : 

1. Sales Order
2. Sales Invoice
3. Delivery Note
4. Purchase Order
5. Purchase Invoice

#### Steps to Reproduce  : 
Step 1: Select Item (e.g. Burger having default_uom as "Nos")
Step 2 : Replace Item with another item having different default_uom ,  e.g. Coke having default_uom as "Litre")
Step 3:  Stock UOM of the item table changes, but UOM doesn't

Below is the gif explaining the same.

![ItemUOM_Error](https://user-images.githubusercontent.com/4900815/68069113-e66ca880-fd81-11e9-9b0d-3f69780af5d4.gif)

#### Actual Behavior : 
Item UOM **_not_** updated on selection of item

#### Expected Behavior : 
Item UOM should get updated on selection of item

PS : It works fine in Stock Entry doctype.

**Comment by ashish-greycube** [comment]
https://github.com/frappe/erpnext/blob/develop/erpnext/stock/get_item_details.py#L255
It might be due to above condition
It doesn't reset UOM if it is already present

**Comment by mobentec** [comment]
We are experiencing the same issue.  What is the fix for the bug @jigneshpshah so clearly documented?
