### ISSUE TITLE
"Illegal characters in SQL query" error is coming in report builder

### ISSUE THREAD

**Issue by amitkumar18** [frappe/erpnext#19481]
"Illegal characters in SQL query" this error is coming while adding a field from child table in report builder.

ERPNext: v11.1.38 (master)
Frappe Framework: v11.1.45 (version-11)

[report builder issue.docx](https://github.com/frappe/erpnext/files/3798653/report.builder.issue.docx)

**Comment by deepeshgarg007** [comment]
@amitkumar18  Closing this issue. If the issue still persists in the latest version-13 or above then please reopen a new issue
