### ISSUE TITLE
Blank Login Screen due to jquery exception

### ISSUE THREAD

**Issue by AtriDev** [frappe/erpnext#19491]
## Context information (for bug reports)

```
Hosted on ERP Cloud
```

## Steps to reproduce the issue

1. Enter url of the site 
2. Click Login

### Observed result
It shows blank screen.

### Expected result
It should load login screen

### Stacktrace / full error message

```
uncaught ReferenceError: io is not defined
    at Object.init (javascript.js:2)
    at highlight.js:860
    at highlight.js:701
    at Array.forEach (<anonymous>)
    at Object.trigger_ready (highlight.js:700)
    at HTMLDocument.<anonymous> (highlight.js:828)
    at HTMLDocument.dispatch (jquery.min.js:3)
    at HTMLDocument.r.handle (jquery.min.js:3)
    at Object.trigger (jquery.min.js:4)
    at HTMLDocument.<anonymous> (jquery.min.js:4)
```

## Reference images.
<img width="1280" alt="Screenshot 2019-11-04 at 1 17 41 PM" src="https://user-images.githubusercontent.com/56126302/68105885-e3022a00-ff05-11e9-9728-ea161392696c.png">

**Comment by AtriDev** [comment]
Here are the steps to reproduce.
1. Login to the erpnext instance.
2. Logout from the erpnext instance.
3. Click on login

**Comment by kennethsequeira** [comment]
Closing the issue as it cannot be replicated further on v12.

Also, if an issue is occurring on ERPNext's cloud, raise a support ticket with them to solve the issue.
