### ISSUE TITLE
Drop-shipping : shipping_address not filled

### ISSUE THREAD

**Issue by MorezMartin** [frappe/erpnext#19503]
## Description of the issue
When using drop shipping option in sales order item, if there is a company address defined (address which is the company address), this address is automatically fetched.
If i delete the company address or untick the box "is company address", customer address is correctly fetched when using dropshipping

## Steps to reproduce the issue

1. Create an address and tick the box is your company address
2. Make a sale order, in a sale order item tick the box drop shipping, submit
3. Make the corresponding purhcase order using create purchase order

### Observed result
The shipping_address field is filled by Company Address

### Expected result
The shipping_address field should be the Customer Shipping Address (shipping_address_name field of Sale Order)

## Additional information

ERPNext: v12.x.x-develop () (develop)
ERPNext France: v0.0.1 (master)
Frappe Framework: v12.x.x-develop () (develop)
Using frappe_docker

It seems to be correctly coded there https://github.com/frappe/erpnext/blob/83b58352cec927b8b8baec9ebf23dd45a3749195/erpnext/selling/doctype/sales_order/sales_order.py
I think a JS script is overriding this, i didn't find it

**Comment by MorezMartin** [comment]
https://github.com/frappe/erpnext/blob/2818b5bbe7990022c3e811ea8a212c48577f3847/erpnext/public/js/controllers/buying.js
`		// no idea where me is coming from
		if(this.frm.get_field('shipping_address')) {
			this.frm.set_query("shipping_address", function() {
				if(me.frm.doc.customer) {
					return {
						query: 'frappe.contacts.doctype.address.address.address_query',
						filters: { link_doctype: 'Customer', link_name: me.frm.doc.customer }
					};
				} else
					return erpnext.queries.company_address_query(me.frm.doc)
			});
		}
		/* eslint-enable */
	},`
Maybe a problem there, but i'm not used to JS

**Comment by deepeshgarg007** [comment]
@MorezMartin  Closing this issue. If the issue still persists in the latest version-13 or above then please reopen a new issue
