### ISSUE TITLE
Feature : Paid Customization (Leave without Pay)

### ISSUE THREAD

**Issue by sammish** [frappe/erpnext#19515]
Senario

1. Add a **"Leave without Pay "** Enable or disable option in **HR Setting** 
![image](https://user-images.githubusercontent.com/12432802/68314486-47b8b280-00c7-11ea-88a6-484c594cbf7c.png)

2. If Enable stop validation message from "Salary Slip" allow to add Leave manually in Leave without pay.
![image](https://user-images.githubusercontent.com/12432802/68314656-91090200-00c7-11ea-828d-738c4b08826c.png)
![image](https://user-images.githubusercontent.com/12432802/68314687-a41bd200-00c7-11ea-80e5-3ded3f434805.png)

**Comment by Mitchy25** [comment]
Hi Sammish,

Send me an email at hello@techsquid.co.nz and I will help you out :)

Mitch
