### ISSUE TITLE
Cost Center field to Disable / Enable, such that cost centers can be frozen.

### ISSUE THREAD

**Issue by Tropicalrambler** [frappe/erpnext#19531]
**Is your feature request related to a problem? Please describe.**
Yes, Cost Centers should have an option to disable, to prevent further use in dialogs.

**Describe the solution you'd like**
Cost centers must have a checkbox where "disabled" can be selected. This prevents cost center from being selectable.

**Describe alternatives you've considered**
Use our own custom field, however this field only allows for reporting or other software uses, it must be coded into search for cost center functionality within the core.

**Additional context**
Accounts can be frozen. Cost centers should also have that capability.

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.
