### ISSUE TITLE
Items "Default Supplier" does not populate the Supplier field PO/PINV

### ISSUE THREAD

**Issue by dulhaver** [frappe/erpnext#19535]
## Description of the issue

There is an item which has a "Default Supplier" assigned to it. So when you click on `"Purchase Oder +"` or `"Purchase Invoice +"` in the items dashboard a new Sales Order/Invoice Should be created with the item table populated with the respective Item **as well as the `Supplier`populated with the Default Supplier** assigned in the Item Master.

This does not work. The "Supplier" field is not populated. Therefore the purpose of the concept "Default Supplier" is not taking effect. So you have to know which Supplier (and in many cases there is only one Supplier for a specific item) is the Supplier who can actually provide you with a particular item.

## Context information (for bug reports)
tested with 
- ERPNext: v11.1.58 (version-11)
Frappe Framework: v11.1.53 (version-11)

- ERPNext: v12.1.6 (version-12)
Frappe Framework: v12.0.16 (version-12)

## Steps to reproduce the issue

1. assign a "Default Supplier" in an Item Master
2. click the `+` in the Item Dashboard for either the "Purchase Order" or the "Purchase Invoice"
3. check whether the Item Table, or the Supplier field are being populated

### Observed result

the Supplier field is not populated. Supplier needs to be chosen manually

### Expected result

Supplier field is populated with the respective Default Supplier

## Additional information

OS: ubuntu 18:04, running inside an LXC Container

## Possible Root cause

the PO/PINV document seems to wait for the Supplier to be selected **before** it accepts any Items. I guess both things (auto-selection of Item [when you create PO/PINV from within the Item] and auto-selection of the Supplier) stand in each others way

**Comment by dulhaver** [comment]
here is a related Topic on the Forum https://github.com/frappe/erpnext/issues/19535

**Comment by dulhaver** [comment]
@PawanMeh can you kindly look into this and at least confirm this is a bug? I may have a customer willing to pay for fixing this, but only whether they have the certainty a PR will become mergable into the hotfix branch, so they benefit from that fix in the core code (`version-12` branch)

**Comment by PawanMeh** [comment]
I am not sure if this is a bug because of the below reasons:

1. You can have multiple suppliers for the same Item, in that case you do not know which supplier to default unless there is a modification in design to establish a priority of suppliers. 

![multiple_suppliers](https://user-images.githubusercontent.com/20460498/69151691-1f867600-0b01-11ea-932a-1306b63798aa.png)

2. I guess the 90% use case is users go to Purchase Invoice and directly create the invoice by selecting a supplier and so on.

This is my analysis from whatever limited knowledge I have on this topic.

**Comment by dulhaver** [comment]
thx @PawanMeh for your comments. And sorry, apparently I have not managed to make myself clear enough

it's not "SUPPLIER DETAIL" Section, but the "SALES, PURCHASE, ACCOUNTING DETAILS" section ...
![image](https://user-images.githubusercontent.com/7608112/69462406-320ae480-0d79-11ea-9a87-35ae805a741b.png)

where you can choose one (only one) "DEFAULT SUPPLIER" on a company level *so different ones whether you have different companies)

![image](https://user-images.githubusercontent.com/7608112/69462473-61b9ec80-0d79-11ea-9ea3-3e2f5b290eea.png)


> You can have multiple suppliers for the same Item, in that case you do not know which supplier to default unless there is a modification in design to establish a priority of suppliers.
1. I don't think it's "default-supplier-exclusive". 
1. imagine you have a situation with thousand items which are only been delivered exclusively by one particular supplier of which you have, let's say 500. That's where you need the Default Supplier to be chosen by default if you not want to force that every single employee knows the correct item/Supplier combination. Or has a record of somewhere else.
1. the SUPPLIER DETAIL is for having a record of a Item Code which may be different at the particular Supplier then the internal Companies Item Code 
1. What else, if not to establish a Item/Supplier bond by pre-selecting the repspective Supplier, would be the functionality of that record be for?

> This is my analysis from whatever limited knowledge I have on this topic.
If you feel you are not the right person to talk to about this here ... would you mind pointing me to any of your fellow Maintainers who may be a more suitable person to discuss this with?

**Comment by PawanMeh** [comment]
If you directly create a purchase Invoice, enter an Item and save, it will pick the default Supplier automatically. So really you do not need all employees to know the default supplier if it is set.

![Default_Supplier](https://user-images.githubusercontent.com/20460498/69474527-3c17fc00-0de8-11ea-9d63-b7fcf9fa4fc4.gif)

Note: In the above case, Supplier is set in the Item test.

**Comment by dulhaver** [comment]
hi @PawanMeh 

thx for the example. This is exactly how I'd expect this to work and I am surprised to see that in action on your side?scenario

here is what happens in my (v11.1.58)  (and I see the same in another v12 instance)

![Default Supplier v11](https://user-images.githubusercontent.com/7608112/69490892-50aecf80-0e8e-11ea-9237-5d54ccdfccd0.gif)

**Comment by dulhaver** [comment]
the `test_item` item above has set the `test supplier` as Default Supplier. All accounts are connected as they should.

As you can see I can not save the Invoice when Supplier is not manually selected.

Can you tell which version you are using where it apparently works?

**Comment by sunhoww** [comment]
I think this desired behavior can be achieve easily with a custom script. To test whether it'll work, you could execute these two lines in the browser console on the **Item** form page

```javascript
let { default_supplier } = cur_frm.doc.item_defaults.find(({ company }) => company === frappe.defaults.get_user_default('company')) || {};
frappe.route_options = Object.assign(frappe.route_options, { supplier: default_supplier });
```

... and then try opening the `"Purchase Invoice +"` link. This code should work on most modern browsers.

**Comment by dulhaver** [comment]
thanks for the comment @sunhoww . I'll certainly test what you suggest.

1. I wouldn't say that this bug should be fixed with a custom script but rather in the code itself though. 
1. Can you kindly confirm what I am reporting here is a reproducible bug in your environment? By suggesting to implement that script you indirectly have confirm this to be a bug somehow. But a clear statement would help the case I am trying to make here. Also a thumbs up on this issue (which is official currency for upvoting on issues here in the ERPNext/frappe context) would be helpful & appreciated.

**Comment by dulhaver** [comment]
>  "Can you tell which version you are using where it apparently works?"

@PawanMeh can you elaborate on this?

**Comment by sunhoww** [comment]
> 2. Can you kindly confirm what I am reporting here is a reproducible bug in your environment?

I don't know whether this should be classified as a bug though. But, it sure is a new feature that is not present in the core code.

> 1. I wouldn't say that this bug should be fixed with a custom script but rather in the code itself though.

How we choose to implement this "feature" (or fix the "bug") is up to us. I would be glad to create a PR to the _erpnext_ repo for this.

**Comment by harshit-30** [comment]
@vrms is this replicable in latest v12 or v13?

**Comment by shirleymayadewi** [comment]
This issue still persists in Version 13. @harshit-30 

Even when Default Supplier is defined for an item, when you click + Purchase Order, the Supplier field isn't automatically filled out. Also, when you create Production Plan using this item, it doesn't let you save the Production Plan because Supplier is needed and it does not pull the Default Supplier information automatically.
