### ISSUE TITLE
Cannot delete or cancel because Company is linked with Shopping Cart Settings

### ISSUE THREAD

**Issue by CarbonCopy0000** [frappe/erpnext#19539]
Tried to delete a company after deleting all transactions.

An error came up saying:
Cannot delete or cancel because Company Carmat Coatings and Allied Products Inc is linked with Shopping Cart Settings

Went to shopping cart which is not enabled.

I still cannot delete the company.

**Comment by deepeshgarg007** [comment]
@CarbonCopy0000  Closing this issue. If the issue still persists in the latest version-13 or above then please reopen a new issue
