### ISSUE TITLE
Purchase recipt -> "% Amount Billed" not working for purchase return and Purchase invoice return/debit note

### ISSUE THREAD

**Issue by jainitya** [frappe/erpnext#19530]
## Context information (for bug reports)

**Output of `bench version`**
```
ERPNext: v11.1.67 (version-11)

Frappe Framework: v11.1.60 (version-11)
```

## Steps to reproduce the issue
Steps to follow

Step 1: Created a purchase Recipt(without any purchase order) for item Mentha Oil quntitiy 300 rate 1.(% Amount billed in More information Section is 0% As Expected)

Step 2 : created purchase invoice2 against this purchase receipt for Item mentha Oil Quantity 100 rate 1(In Purchase receipt % Amount billed in More information Section is 33.33% As Expected)

Step 3 : created purchase invoice2 against this purchase receipt for Item mentha Oil Quantity 100 rate 1(In Purchase receipt % Amount billed in More information Section is 66.66% As Expected)

Step 4 : Make a debit note/Purcahse return of 100 litre “% amount billed”(in Purchase recipt) is still 66% which is expected as 33.33%

Step 5 . Now we have 200 litere of mentha oil remaining to be billed. from this remaining 200 I have make Purchase receipt return of 100 (In Original {first }Purchase receipt % Amount billed in More information Section is still 66.66% while I have returned 100 litre so it should be 50%) 
Please refer below for summery
![image](https://user-images.githubusercontent.com/1884485/68414522-5fbb2f80-01b6-11ea-8b46-25def6a881a2.png)

**Comment by deepeshgarg007** [comment]
@jainitya  Closing this issue. If the issue still persists in the latest version-13 or above then please reopen a new issue
