### ISSUE TITLE
pricing rules do not get removed and restrict some use cases

### ISSUE THREAD

**Issue by ioweb-gr** [frappe/erpnext#19545]
## Description of the issue
I have a product 00007 with price rate 25$ and 3 pricing rules 
qty > 20  -> price 20$
qty > 35 -> price 15$ 

When I add rows of the same item in my quotation / sales order or invoice 
ROW1:  QTY -> 10 
ROW2:  QTY -> 20
ROW3: QTY -> 35

Pricing rules are automatically inserted and updating all the prices. 
So at the moment I enter the 2nd row, my first row price changes to 20$.
When I insert row 3 the price for all rows is changed to 15$.

First of all I would like my discount to be applied on each row and not combine the quantities if possible but I can understand why it does this however in multishipping cases this is restrictive. For example if I ship each qty pack differently I want to have different discounts applied. 

Now to the most serious issue.
Removing the rows doesn't revert the discounts. So after I remove row 3 I still see discounted price at 15$ instead of 20$. Removing row 2 I still see 15$ instead of 25$. 

## Context information (for bug reports)

**Output of `bench version`**
erpnext 12.x.x-develop
frappe 12.x.x-develop

## Steps to reproduce the issue

Please see description

### Observed result
- Discount does not get removed when removing the rows
- Discount calculates the complete total of qty for each item instead of row. There's no way to change this behaviour.

### Expected result
- Discount gets removed if the qty drops below the pricing rule thresholds.

### Stacktrace / full error message
No stacktrace

## Additional information
Ubuntu 16.04 
EasyInstall
Python 3

**Comment by ioweb-gr** [comment]
After further testing I see that it's not calculating the total quantity either. It's just applying the price rules on all items instead of matching rows. I see this by testing the following scenario

ROW1:  QTY 10 yields 25$
ROW2:  QTY 15 yileds 25$  

Total qty is 25 > 20 so I should at least see 20$  price. 

Another example shows
ROW1: QTY 10 yields 20$
ROW2: QTY 20 yields 20$

I would expect one of the following 

ROW1: QTY 10 yields 25$
ROW2: QTY 15 yields 25$
ROW3: QTY 20 yields 20$
because only ROW3 exceeds qty 20

or

ROW1: QTY 10 yields 20$
ROW2: QTY 15 yields 20$ 
because the total qty is 25 > 20

**Comment by ghost** [comment]
Did you get anywhere with solving this? I think we have the same issue with ERNEXT hosting

**Comment by ioweb-gr** [comment]
Hi,
no I wasn't able to track the commit that caused this unfortunately. This needs debugging in order to detect the file which causes this calculation so I can see who commited this change, imho this was a very big change in the ERPNext discount calculation and should be documented better. In the older versions of ERPNext I didn't have this issue. 

In my case only 2 products use price discount rules so I just deleted the rules because of this issue

**Comment by ghost** [comment]
OK, thanks. I have contacted support directly and they are working on it. Major part of our business not working at the moment because of this

**Comment by ioweb-gr** [comment]
I see, please let me know how it went because it's a problem for us too. It's just the nature of our business that doesn't make it impossible to live without but I assume this is very major factor for others. There needs to be versatility in the calculation method.

**Comment by rohitwaghchaure** [comment]
@ioweb-gr Can you please share the screenshots of the Pricing Rule, I would like to check whether you have enabled Mixed Conditions checkbox or not. If it's enabled then kindly disabled it and check.

**Comment by ioweb-gr** [comment]
@rohitwaghchaure No they're not selected because I don't wish the qty of items in each row to be combined. 
![image](https://user-images.githubusercontent.com/20220341/70373649-8920c580-18f2-11ea-8b16-c11a6bfe207a.png)

**Comment by rohitwaghchaure** [comment]
@ioweb-gr we have identified and fixed the issue and we'll release the fix in the next release cycle (20th December). For more details about fix please check below PR link

https://github.com/frappe/erpnext/pull/19598

**Comment by clarkejj** [comment]
pipech identifed several pricing rule bugs from his tests noted here https://discuss.erpnext.com/t/pricing-rule-alot-of-bugs/58460
