### ISSUE TITLE
When viewing projects lists on the website, list formatting is not used.

### ISSUE THREAD

**Issue by maxwelljvogel** [frappe/erpnext#19561]
## Description of the issue
When viewing projects lists on the website, list formatting is not used.

## Context information (for bug reports)
The issue is observed both on my installation and on the demo installations

**Output of `bench version`**
```
erpnext 12.1.8
frappe 12.0.18
```

<img width="1680" alt="Screen Shot 2019-11-12 at 4 39 59 PM" src="https://user-images.githubusercontent.com/24994544/68717237-d6b44780-056b-11ea-9613-210ad8db6b1e.png">

**Comment by deepeshgarg007** [comment]
@maxwelljvogel  Closing this issue. If the issue still persists in the latest version-13 or above then please reopen a new issue
