### ISSUE TITLE
Clicking "more" on website list shows already listed items

### ISSUE THREAD

**Issue by maxwelljvogel** [frappe/erpnext#19562]
## Description of the issue
The more button is visible (not hidden) even when there are no more items to display in that particular list on the website.  If the more button is clicked after all items are listed, duplicates are listed.

## Context information (for bug reports)
This issue occurs on various website lists (projects, invoices, etc)

**Output of `bench version`**
```
erpnext 12.1.8
frappe 12.0.18
```

## Steps to reproduce the issue
Click the "more" button, after all available items are already listed

### Observed result
Duplicates of items already listed appear in the list.  Clicking the "more" button again repeats the result.

### Expected result
The more button should not be visible if all items are already listed 
OR 
a message should appear telling the user that there is no more items to list (I believe this is what happened prior to the issue).

## Additional information
This issue occurs on  both my installation and the demo installations.

<img width="1680" alt="Screen Shot 2019-11-12 at 4 39 59 PM" src="https://user-images.githubusercontent.com/24994544/68717814-50990080-056d-11ea-90e1-5c152cf73081.png">
_Repeat items can be seen in the image above (on the demo site)_

**Comment by deepeshgarg007** [comment]
@maxwelljvogel  Closing this issue. If the issue still persists in the latest version-13 or above then please reopen a new issue
