### ISSUE TITLE
ERPNext installation is failing due to botocore issue 1872

### ISSUE THREAD

**Issue by robvdl** [frappe/erpnext#19587]
## Description of the issue

When you install erpnext it is now failing because botocore is running into a depedency issue for python-dateutil

## Context information (for bug reports)

I've tracked the issue down to botocore, they've been aware of the issue for 10 days and are looking into it. Other projects also affected by this, ocs-ci from rehdat storage and python-cfn-lint.

It looks like other projects like ocs-ci have temporarily pinned python-dateutil until the issue is resolved in botocore.

**Output of `bench version`**
```
Usage: bench [OPTIONS] COMMAND [ARGS]...
Try "bench --help" for help.

Error: No such command "version".
```
(p.s. "bench new-site" is also missing, indicating it didn't finish installing erpnext properly)

## Steps to reproduce the issue

1. Using Ubuntu 18.04 LTS and Python 3.6
2. Create Python 3.6 virtualenv and Install bench - OK
3. Run "bench init erpnext"

### Observed result

Installation starts, then this error:

ERROR: botocore 1.13.17 has requirement python-dateutil<2.8.1,>=2.1; python_version >= "2.7", but you'll have python-dateutil 2.8.1 which is incompatible.

### Expected result

No error, installation should complete without errors.

### Stacktrace / full error message

```
(venv) vagrant@vagrant:~$ bench init erpnext
INFO:bench.utils:virtualenv -q env -p /home/vagrant/venv/bin/python3
Already using interpreter /home/vagrant/venv/bin/python3
Path not in prefix '/home/vagrant/venv/include/python3.6m' '/usr'
INFO:bench.utils:env/bin/pip -q install --upgrade pip
INFO:bench.utils:env/bin/pip -q install wheel
INFO:bench.utils:env/bin/pip -q install six
INFO:bench.utils:env/bin/pip -q install -e git+https://github.com/frappe/python-pdfkit.git#egg=pdfkit
INFO:bench.app:getting app frappe
INFO:bench.utils:git clone https://github.com/frappe/frappe.git  --depth 1 --origin upstream
Cloning into 'frappe'...
remote: Enumerating objects: 2594, done.
remote: Counting objects: 100% (2594/2594), done.
remote: Compressing objects: 100% (2450/2450), done.
remote: Total 2594 (delta 357), reused 860 (delta 93), pack-reused 0
Receiving objects: 100% (2594/2594), 12.36 MiB | 2.97 MiB/s, done.
Resolving deltas: 100% (357/357), done.
installing frappe
INFO:bench.app:installing frappe
INFO:bench.utils:erpnext/env/bin/pip install -q  -e erpnext/apps/frappe 
ERROR: botocore 1.13.17 has requirement python-dateutil<2.8.1,>=2.1; python_version >= "2.7", but you'll have python-dateutil 2.8.1 which is incompatible.
```

## Additional information

Ubuntu 18.04, new Vagrant VM, install Node 12 and yarn, using Python 3.6 virtualenv.

See botocore issue: https://github.com/boto/botocore/issues/1872

Also this has happened before: https://discuss.erpnext.com/t/how-to-fix-this-botocore-requirement/35835/3 it seems the issue has resurfaced, however the issue is with botocore.

**Comment by robvdl** [comment]
It seems the solution for now is to cap dateutil to 2.8.0, the reason why botocore have capped dateutil because they don't want to upgrade setuptools (probably python2 support related sadly).

See: https://github.com/boto/botocore/commit/e87e7a7

If ERPNext doesn't start capping DateUtil to 2.8.0 nobody will be able to install it, this is bad, really bad.

**Comment by lapphan** [comment]
```
bench init --frappe-branch version-12 --python /usr/bin/python3 frappe-bench

INFO:bench.utils:virtualenv -q env -p /usr/bin/python3
Already using interpreter /usr/bin/python3
INFO:bench.utils:env/bin/pip -q install --upgrade pip
INFO:bench.utils:env/bin/pip -q install wheel
INFO:bench.utils:env/bin/pip -q install six
INFO:bench.utils:env/bin/pip -q install -e git+https://github.com/frappe/python-pdfkit.git#egg=pdfkit
INFO:bench.app:getting app frappe
INFO:bench.utils:git clone https://github.com/frappe/frappe.git --branch version-12 --depth 1 --origin upstream
Cloning into 'frappe'...
remote: Enumerating objects: 2598, done.
remote: Counting objects: 100% (2598/2598), done.
remote: Compressing objects: 100% (2451/2451), done.
remote: Total 2598 (delta 368), reused 863 (delta 96), pack-reused 0
Receiving objects: 100% (2598/2598), 12.36 MiB | 1.18 MiB/s, done.
Resolving deltas: 100% (368/368), done.
installing frappe
INFO:bench.app:installing frappe
INFO:bench.utils:frappe-bench/env/bin/pip install -q -U -e frappe-bench/apps/frappe
ERROR: botocore 1.13.23 has requirement python-dateutil<2.8.1,>=2.1; python_version >= "2.7", but you'll have python-dateutil 2.8.1 which is incompatible.
```

I'm facing the same issue when init new bench. I followed the guide in https://github.com/frappe/frappe/wiki/The-Hitchhiker%27s-Guide-to-Installing-Frappe-on-Linux with python3 on Ubuntu 18.04.3.
So I have to wait this bug is fixed before continuing ERPNext installation?

**Comment by robvdl** [comment]
As far as I understand it, unless botocore fix this mess up (which we shouldn't be counting on any time soon). ERPNext *MUST* pin python-dateutil at <=2.8.0 or nobody can install it, still no answer from ERPNext I'm not sure they realised yet how serious this is?

**Comment by robvdl** [comment]
Ok it's been broken for about a month now the ERPNext installation and still no answers on this ticket from ERPNext.

I did a little digging and the requirements.txt in erpnext actually doesn't have boto in there as a dependency, but it is dependent on frappe which pulls in boto3 and pins dateutil to the incompatible version with botocore. So it's actually frappe that has the issue who have pinned python-dateutil to exactly 2.8.1 (the version incompatible with botocore).

One thing you could do is just fork the frappe repo and change the pinned python-dateutil to 2.8.0 and install it from the forked repo instead. A friend of mine was setting up ERPNext about a year ago and he also ended up forking all the repos because apparently it "breaks often" (the build process that is). He ended up forking them all for "reliable builds".

**Comment by lapphan** [comment]
@robvdl You can make a PR to cap python-dateutil to v2.8.0 in frappe repo.
But with v2.8.1 I haven't faced any error except the mentioned log when init bench.
So I think it's not a big issue and I don't think botocore will do any things about this.

**Comment by robvdl** [comment]
It looks like they are pinning things in botocore, there's something about it here (linked to the recent work in setuptools):

https://github.com/boto/botocore/issues/1872#issuecomment-561960651

I actually ran into something similar today where other libraries also had issues with the latest setuptools changes.

**Comment by lapphan** [comment]
@robvdl This issue is fixed.
