### ISSUE TITLE
[bug] Cant close Fiscal Year

### ISSUE THREAD

**Issue by Mitchy25** [frappe/erpnext#19588]
I am trying to close the Fiscal Year 2018/2019. 

Whenever I access the 'Trial Balance' report, it doesn't balance unless I click 'Show unclosed fiscal year's P&L balances'. So clearly, the previous fiscal years are not closed, but I have already submitted the period closing voucher?

Any ideas?

**Comment by deepeshgarg007** [comment]
@Mitchy25 You must have made backdated entries after submitting the Period Closing Voucher. The bug doesn't exists, closing the issue
