### ISSUE TITLE
Work Order Material Transfer Problem - getting InternalError: (1052, u"Column 'qty' in field list is ambiguous") on submit

### ISSUE THREAD

**Issue by Rgottsch1** [frappe/erpnext#19595]
## Getting Error on Submit InternalError: (1052, u"Column 'qty' in field list is ambiguous")

```

```

## Steps to reproduce the issue

1.Stock Entry Screen
2.Choose Material Transfer for Manufacturer
3.Choose work order.

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by diridam** [comment]
Hi, 
I think it's about the query from this File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py", line 1015, in get_transfered_raw_materials

`select
                                item_name, original_item, item_code, sum(qty) as qty, sed.t_warehouse as warehouse,
                                description, stock_uom, expense_account, cost_center
                        from `tabStock Entry` se,`tabStock Entry Detail` sed
                        where
                                se.name = sed.parent and se.docstatus=1 and se.purpose='Material Transfer for Manufacture'
                                and se.work_order= %s and ifnull(sed.t_warehouse, '') != ''
                        group by sed.item_code, sed.t_warehouse`

my error is about item_name column instead of qty column and if i add se.item_name the query will work inside mysql command line.

**Comment by Rgottsch1** [comment]
Is this being worked on to resolve or is something I need to handle on here?  If so, how to resolve?

**Comment by Rgottsch1** [comment]
Reposted with new info.
