### ISSUE TITLE
Bug in job_opining.py

### ISSUE THREAD

**Issue by amutaher** [frappe/erpnext#19592]
## Description of the issue

when creating a job opening depends on  staffing plan get an error message "`Job Openings for designation `**Analaystic** `already open or hiring completed as per Staffing Plan` **Test**"

## UseCase
I create staffing plan Called **Test** for designation **Analaystic** with  `Vacancies=1` and already have one employee with designation **Analaystic** 

## Reason of Issue
https://github.com/frappe/erpnext/blob/642441688687286ba0fce0df1b2319529c723bdd/erpnext/hr/doctype/job_opening/job_opening.py#L45

## Error			

`if self.planned_vacancies <= current_count:`

## Correction 		

`if self.planned_vacancies < current_count:
`

**Comment by amutaher** [comment]
## Other **Bug** related to this issue 

After creating job opening I want to make status=close when clicking Save Button check the same function  `validate_current_vacancies` and show the error message 
"`Job Openings for designation` **Analaystic** `already open or hiring completed as per Staffing Plan `**Test**"

must no check that method on `Update`

**Comment by ruchamahabal** [comment]
https://github.com/frappe/erpnext/pull/31130
