### ISSUE TITLE
Translations list_view is not loading properly

### ISSUE THREAD

**Issue by abhijitkumbharInd** [frappe/erpnext#19616]
**## Description**: When we open the Translation the list we shows some unexpected view. When we click to create a new translation nothing is happening there.

## Steps to reproduce the issue

1. Open Translation
2. Click on new button

**## Observed result:** Translation list view displaying unexpected behaviour. New translation button not working.

**## Expected result:** Translation list view should work normally

**## Stacktrace / full error message (JS Console)**
```
TypeError: Cannot read property 'addClass' of undefined
    at init.add_field (page.js:628)
```

**Comment by clarkejj** [comment]
See report here https://discuss.erpnext.com/t/translations-list-view-is-not-loading-properly/55060

**Comment by abhijitkumbharInd** [comment]
Working fine on v12.4+ hence closing the issue.
