### ISSUE TITLE
Link Title instead of ID

### ISSUE THREAD

**Issue by mariotruss** [frappe/erpnext#19624]
## Problem Statement
When selecting a DocType Entry e.g. Service in another DocType, I want to be able to see relevant information, that helps me select the right entry. Currently, the name aka ID is displayed in Bold and there is only the possibility to configure search fields, that will be displayed underneath.

Let's say I have created a service called "Test" and then decided to rename it to "Test Renamed", the current solution would display the ID in Bold and add the search field, like this:
![image](https://user-images.githubusercontent.com/24277433/69169084-0927ec80-0af8-11ea-9b98-07ec5b0adf71.png)

This works, when the ID is readable. But let's say I have chosen autoname for setting the name. Then, I will have a hash displayed in another DocType, when I want to select the entry. 
![image](https://user-images.githubusercontent.com/24277433/69168613-4c359000-0af7-11ea-853e-0a9ad21c0e7d.png)
Once selected, no one could ever identify what this means:
![image](https://user-images.githubusercontent.com/24277433/69170415-54db9580-0afa-11ea-99b1-29955e96e50c.png)

## Describe the solution you'd like
A new field inside DocType / Form Customization is added called Link Header Field
![image](https://user-images.githubusercontent.com/24277433/69170092-c6ffaa80-0af9-11ea-9f4e-58516c2f1f95.png)

Link Header Field inside the View Settings, will be used for the templating of Bold Text in Selection. This will replace the default display of the "name" aka ID inside all search fields, when trying to link to a DocType entry.
![image](https://user-images.githubusercontent.com/24277433/69169203-44c2b680-0af8-11ea-83ee-d0c645847931.png)

There should be a way to concatenate fields: Lets say First Name=Mario and Last Name=Truss. This should be displayed one string: Mario Truss. 

## Related Issues
https://github.com/frappe/erpnext/issues/19614

**Comment by mariotruss** [comment]
@hrwX

**Comment by mariotruss** [comment]
@hrwX will work with @rmehta on this.

**Comment by asbasawaraj** [comment]
@MarioMeetsWorld Had a chat with @hrwX on this. This is a breaking change and this will be part of v13. @hrwX needs input from @netchampfaris will keep you posted on progress.

**Comment by mariotruss** [comment]
@hrwX Please provide an option to make the Title independent from the Link Title. Sometimes, the DocType Title that I see in the DocType and in List-View, has to be something else, than what I want to be able to see in the Links.

**Comment by e-lobo** [comment]
anything on this ?

**Comment by sgtpepper9907** [comment]
This is a really needed feature

**Comment by mariotruss** [comment]
@e-lobo / @sgtpepper9907: As far as I am concerned the responsible dev stopped working at Frappe. There are still some bugs in the version for example: refeshing issues in the ui, wrong display of ID in Tables, etc.

We stopped investing in ERPNext, so if you are still curious about this feature and want to push it, I'd advise you all to get in touch with @asbasawaraj.

**Comment by Mutantpenguin** [comment]
We really need this too, especially for MultiSelect fields.

@mariotruss What do you mean with "there are still some bugs in the version"? Which version? Is there a feature-branch or MR we could try out?

**Comment by mariotruss** [comment]
@Mutantpenguin: Frappe has given us a beta version of version of it, because we paid for the development of this. But we stopped our collaboration, therefore this has never been fully finished, I guess.

**Comment by sgtpepper9907** [comment]
@asbasawaraj is this still being considered to be released under v13? 
Is there any branch from which we can take on the development?

**Comment by ankush** [comment]
IMHO linking title would be a horrible breaking change. Simpler solution is to use "formatter" to show title instead of name to user.

**Comment by Mutantpenguin** [comment]
I am pretty sure that the reason for this issue here was NOT about "linking" to the title, but rather showing the title and not the name.

Your proposed solution in #14600 would mean somebody hat to create a formatter for every link field.
The proposal here would just be a new field in DocTypes which would automatically be used in all places where there is a link to this DocType.

**Comment by ankush** [comment]
> Your proposed solution in #14600 would mean somebody hat to create a formatter for every link field.


There can just be a default formatter too 🤷 

check possible implementation in https://github.com/frappe/frappe/pull/13848
