### ISSUE TITLE
Can't enable LDAP login, system asking for the already installed ldap3 library 

### ISSUE THREAD

**Issue by derSobi** [frappe/erpnext#19633]
I can't enable LDAP, always getting "LDAP Not Installed / Please Install the ldap3 library via pip to use ldap functionality." error, and the library it's already installed.

Clean install on Debian 10.1 / MariaDB 10.3.18 / Python 3.7.3-2

$ bench version
erpnext 12.1.8
frappe 12.0.18

$ pip list
Package          Version   Location
---------------- --------- ---------------------------
asn1crypto       1.2.0
bench            4.1.0     /home/user/bench-repo
certifi          2019.9.11
cffi             1.13.2
chardet          3.0.4
Click            7.0
cryptography     2.8
entrypoints      0.3
gitdb2           2.0.6
GitPython        2.1.11
honcho           1.0.1
httplib2         0.14.0
idna             2.8
jeepney          0.4.1
Jinja2           2.10.3
keyring          19.2.0
keyrings.alt     3.1.1
ldap3            2.6.1
Mako             1.1.0
Markdown         3.1.1
MarkupSafe       1.1.1
pip              19.3.1
pyasn1           0.4.8
pyasn1-modules   0.2.7
pycairo          1.18.2
pycparser        2.19
pycrypto         2.6.1
pycurl           7.43.0.3
Pygments         2.4.2
PyGObject        3.34.0
python-apt       1.8.4
python-crontab   2.4.0
python-dateutil  2.8.0
python-ldap      3.2.0
pyxdg            0.26
PyYAML           5.1.2
requests         2.22.0
SecretStorage    3.1.1
semantic-version 2.8.2
setuptools       41.6.0
six              1.13.0
smmap2           2.0.5
ttystatus        0.38
urllib3          1.25.7
virtualenv       16.7.7
wheel            0.33.6

**Comment by benknowles** [comment]
In bench directory, run:

` ./env/bin/pip install ldap3`

Bench uses its own Python environment, not the system one.
