### ISSUE TITLE
Asset Value Adjutsment

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#19649]
Make Date field mandatory in Asset Value Adjustment field. Else it gives this error.

<img width="1199" alt="Screenshot 2019-11-21 at 4 51 39 PM" src="https://user-images.githubusercontent.com/910238/69333725-423e9900-0c7f-11ea-8918-c99a11d12768.png">

Also, it allowed me to create Asset Value Adjustment Entry even before the Asset's purchase date.

**Comment by nextchamp-saqib** [comment]
fixed: https://github.com/frappe/erpnext/pull/19666
