### ISSUE TITLE
Landed Cost Voucher for Asset

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#19648]
Steps:

1. Created Purchase receipt with 11 assets. (Asset 1 - 10 qty, Asset 2 - 1 qty)
2. Partially submitted Asset and tried creating Landed Cost Voucher. Received the below message.
3. Submitted all the Assets, still receiving this message.

<img width="1204" alt="Screenshot 2019-11-21 at 4 46 12 PM" src="https://user-images.githubusercontent.com/910238/69333348-7c5b6b00-0c7e-11ea-8f4c-1bd07aa2a493.png">

**Comment by nextchamp-saqib** [comment]
Fixed: https://github.com/frappe/erpnext/pull/19666
