### ISSUE TITLE
Asset: No GL Posting for Asset without CWIP

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#19646]
Asset ID: https://frappetestsv12.erpnext.xyz/desk#Form/Asset/ACC-ASS-2019-00011

Steps:

1. Asset Category doesn't have CWIP enabled
2. Purchase Receipt didn't add value in Fixed Asset account
3. When submitted Asset, then also there was no impact on GL

**Comment by nabinhait** [comment]
Currently fixed asset account updated from purchase invoice in this case. In next cleanup, we will refactor this.
