### ISSUE TITLE
Purchase Receipt: Taxes and Charges Template should have fetched based company filter

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#19643]
Currently, irrespective of the Company selected, it fetches the all the taxes and charges template.

![image](https://user-images.githubusercontent.com/910238/69331469-d78b5e80-0c7a-11ea-8c31-c8b902890807.png)

**Comment by nextchamp-saqib** [comment]
fixed: https://github.com/frappe/erpnext/pull/19682
