### ISSUE TITLE
Asset Transfer: Not able to transfer Asset from Asset Transfer option

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#19651]
Even in the Asset Movement, why Purchase Receipt and Invoice field is mandatory? And what was the error message in the end?

![transfer](https://user-images.githubusercontent.com/910238/69334450-bb8abb80-0c80-11ea-8c3f-4a0ab3920d8f.gif)

**Comment by nextchamp-saqib** [comment]
fixed: https://github.com/frappe/erpnext/pull/19637
