### ISSUE TITLE
Loans are visible to all Employees [Urgent Fix Required]

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#19654]
Hi ,

As a result of using Dynamic Links for the Applicant field in the 'Loan' and 'Loan Application' documents, they are now visible to ALL employees!!!

This requires an urgent fix

Thanks

**Comment by deepeshgarg007** [comment]
@Olawale1 This can still be managed using user permissions. There was a fix made for this Please let us know your use case and reopen the issue
