### ISSUE TITLE
V12.1.8: Table Multiselect field was erased/cleared after Save

### ISSUE THREAD

**Issue by raymondliew1992** [frappe/erpnext#19673]
## As shown below, ‘Belongs to Company’ field is a table multiselect field I created in Customer doctype. Everytime when I save the customer, my selections in the field will be erased.

![image](https://user-images.githubusercontent.com/52439119/69506228-9b047f00-0f68-11ea-806d-882cb23ef782.png)

Also posted in the forum: https://discuss.erpnext.com/t/v12-1-8-table-multiselect-field-was-erased-cleared-after-save/54988/2

## Additional information
ERPNext: v12.1.8
Frappe: v12.0.18

**Comment by barredterra** [comment]
I was able to reproduce this on `develop`.

**Comment by marynvdl** [comment]
I solved this by ensuring that the field in the child table is marked as **In Grid View**.
