### ISSUE TITLE
Cost of Goods Sold valuation is not calculation correctly

### ISSUE THREAD

**Issue by fnrfarid** [frappe/erpnext#19685]
Hi,

Everything were going alright and every report were alright until suddenly stock valuation system got messed up. I purchase an item at 3100 per unit and the valuation rate was 3100 in stock ledger then suddenly the rate went high even though nothing was changed. The valuation method is still FIFO, unit price was same. Now these messed up my Profit and Loss statement report.

I can not find the error neither can I calculate it properly. I’m attaching the stock ledger for that item; if anyone can point out if there’s any explanation, I’d be really really grateful.

For more details, please follow this link
https://discuss.erpnext.com/t/cost-of-goods-sold-valuation-is-messed-up-suddenly/55110

Thanks in advance.

![image](https://user-images.githubusercontent.com/31440952/69604436-a67aa780-1047-11ea-954a-2960b196a466.png)

**Comment by deepeshgarg007** [comment]
@fnrfarid  Closing this issue. If the issue still persists in the latest version-13 or above then please reopen a new issue
