### ISSUE TITLE
Report - Purchase Order items billed not received

### ISSUE THREAD

**Issue by Priyanka-IAS** [frappe/erpnext#1969]
Hi,

Since material from our supplier takes 1-2 months to reach us, I would like to see the following reports in my system:
- Purchase Order items that are billed but not received - meaning the ones that are in transit.
- Purchase Order items to be delivered - Date for delivery due but not billed yet - still waiting for Supplier to ship.

How do I get to these reports?

**Comment by joezsweet** [comment]
@Priyanka-IAS Can you please check `Purchase Order Items To Be Received` in v8?

**Comment by joezsweet** [comment]
Seems to be done in v8 by `Purchase Order Items To Be Received`
