### ISSUE TITLE
[PARTIAL FEATURE/BUG] Cash Flow Mapper is not working (Cash flow report customization)

### ISSUE THREAD

**Issue by Tropicalrambler** [frappe/erpnext#19696]
## Description of the issue
Described functionality of the cash flow mapper and cash flow report is not working as stated.
https://erpnext.com/docs/user/manual/en/accounts/articles/how-to-customise-cash-flow-report
## Context information (for bug reports)
Accounts can be listed and mapped using cash flow mapper functionality, but when report is generated, they accounts do not appear.
**Output of `bench version`**
```
erpnext 12.2.0
frappe 12.0.20
```

## Steps to reproduce the issue
Follow steps as stated here, and the issue repeats.

### Observed result
https://erpnext.com/docs/user/manual/en/accounts/articles/how-to-customise-cash-flow-report

### Stacktrace / full error message
No error messages. This bug is a feature that has not been completed.

## Additional information
This incomplete feature also happens on ERPNext version-11
OS version / distribution, `ERPNext` install method, etc.
Self install ERPNext
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by outerlook** [comment]
Hi! I am facing the same issue. Is there any solution yet?

**Comment by ushashmi** [comment]
I am also facing this issue. Appreciate if this can be looked in

**Comment by ceefour** [comment]
This bug still persists in ERPNext v13.2.0 : https://discuss.erpnext.com/t/cash-flow-mapping-mapper/49312/9?u=hendy

Currently as of v13.2.0:
1. custom Cash Flow Mapper feature is not working properly/fully
2. default Cash Flow Report is incorrect for > 80% of organizations

**Comment by hballan** [comment]
Facing same issue
ERPNext 13.4.1
Frappe 13.4.1
Still the Cash Flow Mapper feature is not functioning

**Comment by hballan** [comment]
Upgraded to
ERPNext 13.5.0
Frappe 13.5.0
Still the Cash Flow Mapper feature is not functioning as designed.
