### ISSUE TITLE
Invoice created in POS does not add taxes when in Offline Mode

### ISSUE THREAD

**Issue by dulhaver** [frappe/erpnext#19707]
## Description of the issue

- When you have marked the **POS to use the Offline Mode** (in POS Settings) ...

![image](https://user-images.githubusercontent.com/7608112/69721648-99c48500-1115-11ea-8084-087311d00de1.png)
  
- ... the Tax associated with a given Item is **not added** on the Total price
  
![image](https://user-images.githubusercontent.com/7608112/69721691-aea11880-1115-11ea-98d4-1f5561c19056.png)

---
  
- however as soon the **"Use POS in Offline Mode" is unchecked** in the POS settings

![image](https://user-images.githubusercontent.com/7608112/69722773-3720b880-1118-11ea-9491-a32401dd5c23.png)

  
- ... the Tax is added as it should

![image](https://user-images.githubusercontent.com/7608112/69721742-d0020480-1115-11ea-9fa5-31f35bcbe235.png)
----
On Top ... when POS is in Offline Mode and you create a 'normal' Sales Invoice and then check the "Include Payment (POS)" box in the Sales Invoice Form, the **Tax also is added as it should**

## Context information (for bug reports)

ERPNext: **v12.1.8** (version-12)
Frappe Framework: **v12.0.18** (version-12)
running inside an LXD container

## Steps to reproduce the issue

1. **check** the "Use POS in Offline Mode" in the POS Settings
1. open POS, choose an Item and finalize the Sale
1. **unckeck** "Use POS in Offline Mode" in the POS Settings
1. open POS, choose the same Item and finalize the Sale
1. **check** the "Use POS in Offline Mode" in the POS Settings
1. create a new "Sales Invoice" and check the "Include Payment (POS)" box

#### When "Use POS in Offline Mode" is checked in the POS Settings 
- the tax amount on top of an Item price is **not** added in a Sale created on the POS.
- the tax amount **is** added on top of the item Price on a Sales Invoice which has the "Include Payment (POS) checkbox checked in the SINV Form

#### When "Use POS in Offline Mode" is unchecked in the POS Settings 

Tax amount is added on top of the Item price, no matter how or where you create your Sales Invoice

### Expected result

Tax amount should **always** be added on top of the Item price, no matter how or where you create your Sales Invoice, not matter whether "Use POS in Offline Mode" is checked or not

## Additional information

OS version: ubuntu 18.04.3 LTS
`ERPNext` install method: Easy Install Script

**Comment by wizardofrobots** [comment]
is this still open?

**Comment by deepeshgarg007** [comment]
@vrms POS offline mode is removed from latest versions, closing this issue
