### ISSUE TITLE
Asset for existing asset

### ISSUE THREAD

**Issue by santoshbb** [frappe/erpnext#19713]
During creation of Asset for existing asset, the Purchase Invoice and Purchase Receipt are mandatory in following version:
When we check "Is existing Asset" the two fields should be disappeared and should not be mandatory.
ERPNext: v12.2.0 (version-12)
Frappe Framework: v12.0.19 (version-12)
I tried with Customize Form, the mandatory field is unchecked.

![image](https://user-images.githubusercontent.com/10789840/69805650-217fc180-11f2-11ea-9d85-cd3f72cbcc22.png)

**Comment by nextchamp-saqib** [comment]
Fixed: https://github.com/frappe/erpnext/pull/19945
