### ISSUE TITLE
Use employee advance with foreign currency 

### ISSUE THREAD

**Issue by Nadorml** [frappe/erpnext#19712]
Dears ERPNEXT Experts

Kindly support , to add feature of  give advance for same employee in multiple currency, as I have employees travel abroad with different advance currency based on targeted countries.

When I’m try to enter , its give me error that currency must be same as company currency which is our of my logic .

Thanks

**Comment by zbisho** [comment]
Just to be clear, from our end we believe that the Employee Expense claim and the Employee advance payment screens should allow for handling foreign currencies, even if the ledger that is generated is converted to company currency with the current exchange rate for example, but we need to record the fact that we payed this specific employee an expense in this particular currency.

**Comment by Nadorml** [comment]
Yes , @zbisho , we are same ,

any solution here ?

**Comment by amutaher** [comment]
It's Important feature

**Comment by Nadorml** [comment]
i hope to add this feature very soon
