### ISSUE TITLE
Manufacturing Module no available in fresh install

### ISSUE THREAD

**Issue by JSinghDev** [frappe/erpnext#19736]
Hi, I created a new ERPNext instance on my local machine using the hitchhiker guide.
I selected manufacturing as my industry and Indian chart of accounts. 

I encountered an error in the end of the setup. I could only proceed forward if I wrote "HDFC" in Bank field ("HDFC Bank" and "ICICI Bank" caused an error). 

I cannot see the manufacturing module anywhere on the dashboard.

**Comment by kennethsequeira** [comment]
@JSinghDev make sure you have selected Manufacturing as a domain during setup. You can cross-check by going to **Domain settings:**

![image](https://user-images.githubusercontent.com/33246109/70555813-cb256200-1ba5-11ea-8117-c2437c9fd39d.png)

If after checking the same, it is still not visible, check the role permission manager and make sure you have assigned yourself **Manufacturing User** & **Manufacturing Manager** roles which control the permissions for manufacturing modules.

For any additional assistance, you can post on the [Community Forum](https://discuss.erpnext.com)
