### ISSUE TITLE
How to create Purchase Return Without Purchase Receipt Reference no

### ISSUE THREAD

**Issue by erpwala** [frappe/erpnext#19754]
I have old stock lying in my Stock and i want to return it to the supplier.
I added those stock as opening stock.

now I want these stocks to return it to the supplier, so how can I process in Erpnext.

How to create Purchase Return Without Purchase Receipt Reference no.

**Comment by kennethsequeira** [comment]
Kindly post functional queries on the [forum](https://discuss.erpnext.com)
