### ISSUE TITLE
Official Docker image on Docker hub

### ISSUE THREAD

**Issue by alexanderadam** [frappe/erpnext#19764]
So I guess nowadays everybody knows about Docker and it's ecosystem so it would probably make sense to have an up to date image on Docker hub that is properly maintained (i.e. [via webhooks like proposed on docker.com](https://docs.docker.com/docker-hub/builds/) or an [autobuild on each release with GitHub Actions](https://medium.com/better-programming/github-actions-for-docker-eaf22bbcc879)).

Currently there is only [an outdated (and very huge) Docker image for development purposes online](https://hub.docker.com/r/frappe/erpnext/tags) and [a bunch of outdated, inofficial (so questionable trustworthy) images](https://hub.docker.com/search?q=erpnext&type=image) on Docker Hub.

This could improve trust, maintenance and probably security [if done right](https://github.com/frappe/frappe_docker/issues/77).
The [README of `frappe_docker` says since a while that you are working on it](https://github.com/frappe/frappe_docker#getting-started) but it doesn't seem to be available yet (although people are using erpnext in Docker anyway - i.e. [1](https://github.com/frappe/frappe_docker/issues/75), [2](https://github.com/frappe/erpnext/issues/19503), [3](https://github.com/frappe/erpnext/issues/16014), [4](https://github.com/frappe/erpnext/issues/12715), [5](https://discuss.erpnext.com/t/erpnext-docker-image-as-an-alternative-to-official-erpnext-docker-repo/43125/43)).

Thank you for keeping up the good work! :pray: 

PS: it would probably also make sense to put the Docker files directly into the official erpnext repository, wouldn't it? :thinking:

**Comment by kennethsequeira** [comment]
added: https://hub.docker.com/u/frappe

Also: https://discuss.erpnext.com/t/official-docker-updates-2020/59224
