### ISSUE TITLE
Purchase Receipt Not able to fetch Batch Wise Stock from Work In Progress

### ISSUE THREAD

**Issue by pujanthakkar** [frappe/erpnext#19778]
While Creating a Purchase Receipt for Material send to Subcontractor, the Batch Wise balance is not fetched from Stock Entry. 

I guess the Field of Raw Material supplied should be editable to encounter this issue so that we can manually add each Item batch wise. Also we can change the quantity for consumption so that we can maintain stock in warehouse.

Check the error Image below 
![2019-12-02](https://user-images.githubusercontent.com/53821822/69959871-17c9c700-152e-11ea-9bfc-d5c8b234ebc3.png)

**Comment by pujanthakkar** [comment]
Many issues are faced in the Purchase Receipt for Material send to Subcontractor module, 

1) Batch Wise Balance is not fetched due to which Error of Qty Becoming Negative pops up and we cannot submit the document as shown in the Image displayed in the comment above

2) Batch No. Shows all data and not of that particular item. as shown in the below image. Please check Item name in the Item supplied and Item name in the Batches displayed in the option. 


![2019-12-02 (2)](https://user-images.githubusercontent.com/53821822/69960469-8e1af900-152f-11ea-81a7-e42895852586.png)
 


Solution will be
![2019-12-02 (1)](https://user-images.githubusercontent.com/53821822/69960070-99215980-152e-11ea-89b6-f29ad48f05f2.png)

Make the Raw Material Supplied Fields editable as in the image above in the purchase receipt so that we can manually enter the stocks transferred which are fetched from the source warehouse just like in Stock entry (Manufacture) Module.

**Comment by pujanthakkar** [comment]
Any update on this ?

**Comment by deepeshgarg007** [comment]
@pujanthakkar  Closing this issue. If the issue still persists in the latest version-13 or above then please reopen a new issue
