### ISSUE TITLE
Pricing Rule error : AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by RickyHutanoto** [frappe/erpnext#19770]
Upon saving a new pricing rule with "Apply on = Transaction"
System show this message : AttributeError: 'str' object has no attribute 'get'

ERPNext version : 12.2.0
Frappe version : 12.0.2

**Comment by khushalti** [comment]
I am looking into it

**Comment by khushalti** [comment]
#19774 I have raised but Travis is failed not able to open Travis details as well

**Comment by khushalti** [comment]
please close this issue this fix has been merged
