### ISSUE TITLE
Can't log in to ERPNext

### ISSUE THREAD

**Issue by derekmontgomery** [frappe/erpnext#19773]
Sometimes users are not able to log in to ERPNext.

The login url is:  https://qrestech.erpnext.com/login

Sometimes the problem occurs when accessing from Google Chrome, sometimes from Microsoft Edge, and sometimes both.

When the problem occurs, the screen looks as follows:

![image](https://user-images.githubusercontent.com/5037126/69945608-34441000-14ea-11ea-9356-c13e317deefc.png)

[printscreen_ERP.docx](https://github.com/frappe/erpnext/files/3910314/printscreen_ERP.docx)

**Comment by kennethsequeira** [comment]
@derekmontgomery raise this with the support team.
