### ISSUE TITLE
[Request] IT Asset Management

### ISSUE THREAD

**Issue by yashodhank** [frappe/erpnext#1978]
Is Asset Management is available out of box with ERPNext? if not, can we add following features to wonderful ERP in near future update/upgrade?

_Asset Management_
- Assign Asset to Location or User
- Custom Asset Fields
- Link Assets to Ticket
- Link Assets to Project
- Link Assets to Task
- Log Ticket by Asset
- Map Asset Locations
- View Asset Details in Ticket
- View Asset History

**What Is IT Asset Management Software?**
This describes a special breed of inventory monitoring software designed specifically to address the unique needs of an IT manager. This means tracking anywhere from one to millions of individual pieces of hard and/or soft technology assets and integrating with servers, networks and service desk as necessary to help troubleshoot problems quickly and efficiently.

Most systems are designed for inventory oversight, including tracking a company’s entire technology services and networking inventory. More advanced systems will automate that and other processes, allow for tighter asset control and management of information needed for service desk resolution and reporting, as well as integrating with other company IT needs (e.g., client management).

Companies that provide outsourced IT services need their system to be able to assign assets to customers and integrate with billing and accounting. It also needs to integrate with clients’ systems, which can be a challenge, so be sure to consider how the software will impact your customers as you peruse your options. SAManage for Zendesk and Netsuite Online are good options to consider.

**Comment by stevecrown** [comment]
That is exactly what I'm looking for - I need to assign assets to my clients. I guess it has been no approach to these kind of module since then! Is there anybody interested in developing a module - I'm able to customize ERPNext but I got no expierience in programming?
Kind regards Stefan
I got a IT Software Services Company (BI & Data mining) and need ERP system for these kind of business. m

**Comment by joezsweet** [comment]
@yashodhank @stevecrown can u please provide a detailed requirements and mockup? Closing for now.

**Comment by jwrober** [comment]
@joezsweet what was this issue closed? I think the top description gives a great example of what is needed.

**Comment by umairsy** [comment]
Most should be manageable with upgraded serialized asset management in ERPNext. Closing. Reopen if needed.
