### ISSUE TITLE
Bug: New Pricing Rules > Item Group not visible

### ISSUE THREAD

**Issue by mimiza** [frappe/erpnext#19829]
Hello sirs.
I am using v12.2.2. I tried to create a new Pricing Rule applied on Item Group, the Child table based on group showed up including the Item Group column. And I can input directly to it on desktop. But in mobile, when I tried to add a new child data, the field Item Group didn't show up.
![Screenshot_2019-12-06-00-47-05-38~2](https://user-images.githubusercontent.com/20904034/70260825-adca4f80-17c3-11ea-9a0f-d75260d5b85d.png)

Thank you for your amazing work and contribution to the world.
Son Nguyen.

**Comment by deepeshgarg007** [comment]
@mimiza  Closing this issue. If the issue still persists in the latest version-13 or above then please reopen a new issue
