### ISSUE TITLE
Socket.io 502 bad gateway Error 

### ISSUE THREAD

**Issue by abdulmutal** [frappe/erpnext#19824]
Please post on our forums:

for questions about using `ERPNext`: https://discuss.erpnext.com

for questions about using the `Frappe Framework`: https://discuss.frappe.io

for questions about using `bench`, probably the best place to start is the [bench repo](https://github.com/frappe/bench)

For documentation issues, use the [ERPNext Documentation](https://erpnext.com/docs/) or [Frappe Framework Documentation](https://frappe.io/docs/user/en) or the [developer cheetsheet](https://github.com/frappe/frappe/wiki/Developer-Cheatsheet)

> **Posts that are not bug reports or feature requests will not be addressed on this issue tracker.**

**Comment by abdulmutal** [comment]
![11](https://user-images.githubusercontent.com/49708818/70222471-f1916a80-176b-11ea-8e8d-d5573fe9fa49.PNG)
 I have the issue in ERPNEXT V12. whenever users login into ERP system the console is flooded with the socket.io 502 Bad Gateway Error. after every 5 seconds the console logs added the 502 bad gateway error .

logs are copied as below

libs.min.js?ver=1575443926.0:12150 GET https://cobberp.com/socket.io/?EIO=3&transport=polling&t=MxLPCLc 502 (Bad Gateway)


i.create | @ | libs.min.js?ver=1575443926.0:12150
-- | -- | --
  | i | @ | libs.min.js?ver=1575443926.0:12150
  | o.request | @ | libs.min.js?ver=1575443926.0:12150
  | o.doPoll | @ | libs.min.js?ver=1575443926.0:12150
  | n.poll | @ | libs.min.js?ver=1575443926.0:12150
  | n.doOpen | @ | libs.min.js?ver=1575443926.0:12150
  | n.open | @ | libs.min.js?ver=1575443926.0:12150
  | n.open | @ | libs.min.js?ver=1575443926.0:12150
  | n | @ | libs.min.js?ver=1575443926.0:12150
  | n | @ | libs.min.js?ver=1575443926.0:12150
  | n.open.n.connect | @ | libs.min.js?ver=1575443926.0:12150
  | (anonymous) | @ | libs.min.js?ver=1575443926.0:12150
  | setTimeout (async) |   |  
  | n.reconnect | @ | libs.min.js?ver=1575443926.0:12150
  | (anonymous) | @ | libs.min.js?ver=1575443926.0:12150
  | (anonymous) | @ | libs.min.js?ver=1575443926.0:12150
  | n.emit | @ | libs.min.js?ver=1575443926.0:12150
  | n.onError | @ | libs.min.js?ver=1575443926.0:12150
  | (anonymous) | @ | libs.min.js?ver=1575443926.0:12150
  | n.emit | @ | libs.min.js?ver=1575443926.0:12150
  | n.onError | @ | libs.min.js?ver=1575443926.0:12150
  | (anonymous) | @ | libs.min.js?ver=1575443926.0:12150
  | n.emit | @ | libs.min.js?ver=1575443926.0:12150
  | i.onError | @ | libs.min.js?ver=1575443926.0:12150
  | (anonymous) | @ | libs.min.js?ver=1575443926.0:12150
  | setTimeout (async) |   |  
  | hasXDR.r.onreadystatechange | @ | libs.min.js?ver=1575443926.0:12150
  | XMLHttpRequest.send (async) |   |  
  | i.create | @ | libs.min.js?ver=1575443926.0:12150
  | i | @ | libs.min.js?ver=1575443926.0:12150
  | o.request | @ | libs.min.js?ver=1575443926.0:12150
  | o.doPoll | @ | libs.min.js?ver=1575443926.0:12150
  | n.poll | @ | libs.min.js?ver=1575443926.0:12150
  | n.doOpen | @ | libs.min.js?ver=1575443926.0:12150
  | n.open | @ | libs.min.js?ver=1575443926.0:12150
  | n.open | @ | libs.min.js?ver=1575443926.0:12150
  | n | @ | libs.min.js?ver=1575443926.0:12150
  | n | @ | libs.min.js?ver=1575443926.0:12150
  | n.open.n.connect | @ | libs.min.js?ver=1575443926.0:12150
  | (anonymous) | @ | libs.min.js?ver=1575443926.0:12150


Please suggest any solution.

**Comment by Thunderbottom** [comment]
what does `supervisorctl status` show?

**Comment by abdulmutal** [comment]
> what does `supervisorctl status` show?

frappe-bench-redis:frappe-bench-redis-cache                 RUNNING   pid 1510, uptime 22:11:54
frappe-bench-redis:frappe-bench-redis-queue                 RUNNING   pid 1509, uptime 22:11:54
frappe-bench-redis:frappe-bench-redis-socketio              RUNNING   pid 1511, uptime 22:11:54
frappe-bench-web:frappe-bench-frappe-web                    RUNNING   pid 1507, uptime 22:11:54
frappe-bench-web:frappe-bench-node-socketio                 RUNNING   pid 1508, uptime 22:11:54
frappe-bench-workers:frappe-bench-frappe-default-worker-0   RUNNING   pid 1504, uptime 22:11:54
frappe-bench-workers:frappe-bench-frappe-long-worker-0      RUNNING   pid 1505, uptime 22:11:54
frappe-bench-workers:frappe-bench-frappe-schedule           RUNNING   pid 1503, uptime 22:11:54
frappe-bench-workers:frappe-bench-frappe-short-worker-0     RUNNING   pid 1506, uptime 22:11:54

**Comment by abdulmutal** [comment]
has been resolved at https://github.com/tlaverdure/laravel-echo-server/issues/273

**Comment by AmmarAhmadKhan** [comment]
> has been resolved at [tlaverdure/laravel-echo-server#273](https://github.com/tlaverdure/laravel-echo-server/issues/273)

@abdulmutal I am not able to import any doctype from data import section of ERPNExt. It gives the error in console which is attached as a picture here. I think there is some file upload API issue.
![image](https://user-images.githubusercontent.com/78144310/107324314-b4400f80-6ac9-11eb-8f46-a7e2621e9099.png)
