### ISSUE TITLE
Pricing List doesn't work when items are at rate of 0€ ( aka FREE ) and/or doesn't update such price on Customer Invoice

### ISSUE THREAD

**Issue by PedroBatista** [frappe/erpnext#19843]
Hi,

I have an item ( A1.01.01.02 ) with a default rate ( Standard PVP ) of 30.0€. I have another pricing list ( **Wildsmile - Premium** ) where the same item is free ( 0.0€ ).

When I'm making an invoice and change the pricing list to **Wildsmile - Premium** , it doesn't update the value to zero. If the item rate is more than zero on the Pricing List, it works as expected. 

ERPNext: v12.2.0 (version-12)
Frappe Framework: v12.0.20 (version-12)

![image](https://user-images.githubusercontent.com/1666441/70343681-cd0ebe80-184f-11ea-9d1b-6b51e702cb17.png)

Thank you.

**Comment by AbubakarManzoor** [comment]
Have you found any solution for this issue ?

**Comment by PedroBatista** [comment]
> Have you found any solution for this issue ?

Unfortunately no. 

ERPNext has some nice ideas but it's foundations are built on sand. Not trying to blame anyone, it is what it is..

**Comment by ankush** [comment]
![image](https://user-images.githubusercontent.com/9079960/117478682-1ac7b300-af7d-11eb-9f55-f94ffab0bb5e.png)


Works as expected on v13. Can you share steps to reproduce the issue?

**Comment by PedroBatista** [comment]
@ankush It was 1 and half year ago, I don't remember the exact details. But I remember the prices were loaded by CSV and when listing them the ones with a rate of 0 were showing correctly, but when registering an invoice it happened what was described above.

But since apparently it works in v13, this issue can be closed if you agree.

**Comment by ankush** [comment]
@AbubakarManzoor if you can share steps to reproduce I can look into it. I'll check on v12 later.
