### ISSUE TITLE
ERP Next is not updating.

### ISSUE THREAD

**Issue by unidow** [frappe/erpnext#19848]
Hi,
ERPnext uasl.erpnext.com is not updating to latest version, even though, I had set a date for updating it. It is currently v11.1.68. Kindly advise.

**Comment by yashodhank** [comment]
Kindly contact ERPNext support team directly. https://erpnext.com/contact-support?new=1
Closing for now as cloud instances managed differently to ensure data safety in case of major upgrades and it may not be a bug.
