### ISSUE TITLE
Month December written wrong in Gantt Chart

### ISSUE THREAD

**Issue by mariotruss** [frappe/erpnext#19842]
![image](https://user-images.githubusercontent.com/24277433/70343637-13681b80-1858-11ea-9160-4cd33a95f988.png)
![image](https://user-images.githubusercontent.com/24277433/70343702-3db9d900-1858-11ea-98c2-975ccc3e472a.png)

**Comment by deepeshgarg007** [comment]
@mariotruss Please provide more info on investigating this issue, closing this for now
