### ISSUE TITLE
Feat(minor) - We can make Nationality Field as Link to Country Master

### ISSUE THREAD

**Issue by khushalti** [frappe/erpnext#19895]
![image](https://user-images.githubusercontent.com/26349035/70598580-27719b80-1c11-11ea-80c7-8ffd516ac15a.png)

Please Let me know if we can

**Comment by jaichavan** [comment]
> ![image](https://user-images.githubusercontent.com/26349035/70598580-27719b80-1c11-11ea-80c7-8ffd516ac15a.png)
> 
> Please Let me know if we can

What do you mean by link of Country?

**Comment by khushalti** [comment]
@jaichavan country is master so instead of putting we can use link to country master i guess
