### ISSUE TITLE
Feature Request: Warning message when stock goes negative

### ISSUE THREAD

**Issue by satishguptajaipur** [frappe/erpnext#1991]
When the stock is NOT allowed to go negative, any transaction which results in stock becoming negative results in a warning message and the transaction is declined.

However, when the stock is allowed to become negative, the warning message is suppressed even if the entry makes the stock negative or increases the negative stock. This deprives the user from the opportunity to know if the negative stock is a result of incorrect transaction or is it indeed the desired transaction. A warning message which ultimately results in the negative stock (for eg. 4 - 6 =  -2   and   -5 - 2 = -7) should give a warning message which will help user avoid any incorrect transactions.

**Comment by umairsy** [comment]
You can manage this by updating re-order level in the item master.
