### ISSUE TITLE
Dark Mode in the ERPNext

### ISSUE THREAD

**Issue by he1tor** [frappe/erpnext#19915]
Folks,

Within ERPNext, there could be a dark mode option, as some companies are applying to their OS and applications. It would help in times when the user needs to stay close to the screen for a long time, the eyes would not be bothered and the reading would be more pleasant.

Follow Discuss ERPNext link https://discuss.erpnext.com/t/dark-mode-in-the-erpnext/55918

**Comment by wojosc** [comment]
As a quick fix you can use Dark Reader. Available for most browsers. Works fine.
https://darkreader.org/

**Comment by jaywks** [comment]
darkreader is good

**Comment by wojosc** [comment]
@he1tor Do you mind closing this? I think my suggestions does the job for now. Also this would be a feature request for frappe and not erpnext as it would be a function of the core frame work.

Thank you.

**Comment by aschl** [comment]
Was introduced in V13 and should be closed.

**Comment by ankush** [comment]
https://github.com/frappe/frappe/pull/12277
