### ISSUE TITLE
Position of labels in filters for reports

### ISSUE THREAD

**Issue by Tropicalrambler** [frappe/erpnext#19920]
Currently, filter fields in any report show the field label as a pop up or as a background on the actual field
if the field has a value, users could be confused about which field they are referring to when changing filter values,  the option should exit to show the label similar to field description in doctypes

https://discuss.erpnext.com/t/why-my-filter-label-is-not-showing-on-my-report/44389/2

**Comment by chronicom** [comment]
I think the simplest and clear way is to add a static label infront of each filter field. I am quite new to Frappe, if someone can guide me to that portion of codes. I can try to implement this.
