### ISSUE TITLE
Fix : is Existing Asset  [Remove Asset Mandatory field Purchase Invoice and Purchase Receipt]

### ISSUE THREAD

**Issue by sammish** [frappe/erpnext#19935]
Hello Frappe 

 **"is Existing Asset"** Kindly allow to create without Purchase invoice and purchase receipt.

![image](https://user-images.githubusercontent.com/12432802/70729935-29248780-1d15-11ea-9d28-77bd35b5989b.png)

**Comment by nextchamp-saqib** [comment]
Fixed: https://github.com/frappe/erpnext/pull/19945
