### ISSUE TITLE
Resume upload on website not uploading

### ISSUE THREAD

**Issue by BernMaina** [frappe/erpnext#19948]
Once you publish a job openning, applicants can go to your website and apply from there. Ones an applicant clicks on apply on the website and proceeds to do fill the application form, the resume upload is not functioning.I have tried with both PDF document and Word documents but none is uploading yet the file sizes are less than the maximum upload size set under job application form .

**Comment by jaichavan** [comment]
Please share steps to replicate, and screenshots if possible. Also, which version is this?

**Comment by BernMaina** [comment]
Sorry i just figured this out.It is working perfectly.
