### ISSUE TITLE
Customize Quick Entry Form

### ISSUE THREAD

**Issue by rabar89** [frappe/erpnext#19952]
Hi,

The quick entry form for creating a new customer makes the process very fast, but there is only one section that is not available and we have to go to Edit in Full Page to enter the details of this section. The section is Accounting, in which we have to select the corresponding accounts for the customer. 
That's why being able to customize the quick entry forms will be very helpful the same as we can customize the doctype forms.

**Comment by kennethsequeira** [comment]
![image](https://user-images.githubusercontent.com/33246109/78173468-7029ba80-7475-11ea-9aa8-7afc96873290.png)

Allow in Quick Entry option added in v12
