### ISSUE TITLE
How out of scope is Typescript coming into Custom Scripts?

### ISSUE THREAD

**Issue by outerlook** [frappe/erpnext#20002]
I really don't know well frappe's architecture to reason about this, but I really miss some type safety on using custom scripts (although they are already super useful).

For example, if you change some API, I really can't figure it out unless something fails here.

With strong typings, maybe errors could be identified on the erpnext custom code editor itself, presenting some `"Script is invalid, expected string on function XXXX on line 32"` error while writing.

**Auto completion** would also be a thing. It would be really easier to discover frappe's API. Imagine a world where **all** this newbie kind issues like _"why my cur_frm.add_fetch isn't working"_ are gone.

 It could **not** be typescript strict, as if the devs using erpnext that are not familiar to Typescript could still use it, without typing their code itself, on their choice.

So,  some re-architecture work would of course be needed, that's the hard part. Writing type definition files isn't complex, but I know it would require some good effort. But outcomes are great, I think the auto documenting part of this would make it more accessible as this huge open source project it already is, right?

You could also be less afraid to change javascript api, as we would be notified when some custom script stops being valid.

Thanks either cases! Unfortunately using typescript on big projects makes us so badly used to the goods of it :P

**Comment by ankush** [comment]
> Custom Scripts

Quite unlikely to get TS support. It will have to be compiled and that adds a lot of extra overhead (calling TSC in production setup). Client scripts are just used for customizations and hence supporting TS won't be a priority. 

Using TS in apps should work fine, build system takes care of compiling and bundling (some assembly required)
