### ISSUE TITLE
Ability to create Dashboard Chart not just from DocType but from Reports too

### ISSUE THREAD

**Issue by raymondliew1992** [frappe/erpnext#20018]
**As per the title, I believe if we have the flexibility to create Dashboard Charts not just from DocType, but from Reports as well, then we can create more meaningful dashboards**

I believe this feature will provide great benefits especially to the top management of a company as they will have a much better overview of the company.

![image](https://user-images.githubusercontent.com/52439119/71163249-a1e09200-2287-11ea-9f12-8d84624a0f5f.png)

P.S. I am not a coder, hence I am not sure if this is possible.

**Comment by SvbZ3r0** [comment]
@ankush I think this is a very valid Feature Request.
I'm currently trying to make a chart to show an Item's purchase price history, so I can monitor pricing trends over the years. I ran into a permission issue when trying to base the chart on `Purchase Invoice Item` despite having Admin permissions. So I had to make a Script Report to get the data I need.
However, this data is better presented in a chart than a list, but there's no easy option to make a chart from data in a report.
