### ISSUE TITLE
V12.2.2 Purchase Receipt Invalid Naming Series (.missing)

### ISSUE THREAD

**Issue by raymondliew1992** [frappe/erpnext#20020]
## Encountered the below error when I am attempting to submit a Purchase Receipt.
![image](https://user-images.githubusercontent.com/52439119/71166930-ad838700-228e-11ea-8a68-9209124ddcc0.png)

ERPNext: v12.2.2
Frappe Framework: v12.0.20

Had the similar problem in the previous v12 version but it was solved in the later version.
https://discuss.erpnext.com/t/v12-stock-entry-manufacture-invalid-naming-series-missing-error-message/52157

**Comment by ankush** [comment]
duplicate https://github.com/frappe/frappe/issues/7934
