### ISSUE TITLE
V12.2.2 or V12.2.3 Unable to post second Landed Cost Voucher

### ISSUE THREAD

**Issue by majidejaz** [frappe/erpnext#20031]
## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 12.2.2
frappe 12.0.20
```

## Steps to reproduce the issue
If you use the newer version please perform the following steps and you will get to know what we are talking about here.

1) Create a purchase invoice
2) Create a landed cost voucher and allocate it to that purchase invoice
3) Create another landed cost voucher, you will not be able to do so, as the system will through this message and you will be stuck. The difference it shows is exactly the same amount on the landed cost voucher, that was entered first.

You cannot cancel any landed cost voucher neither can you are able to create another one.

All data entered validated through normal process without any loss of its integrity.

### Observed result
Debit and Credit not equal for Purchase Invoice **invoice number where first LCV was allocated**. Difference is **value of first LCV allocated.**

<img width="1440" alt="Screen Shot 2019-12-20 at 1 29 06 PM" src="https://user-images.githubusercontent.com/59045925/71244827-d35f6900-232c-11ea-926e-6ed1b418889b.png">

MAT-LCV-2019-00001 was the first LCV posted in sum of 10000.0 to the PINV-2019-00001. Now we are trying to allocate the second LCV it is producing the message as appearing in the above image. Now we cannot create another LCV nor cancel the previous LCV.

### Expected result
Landed Cost Voucher (LCV) should be posted or cancelled. We should also be able to post more LCVs

### Stacktrace / full error message

```
none
```

## Additional information

Mac OSx, Windows 10 etc., `ERPNext` install method **1) Easy from github i.e. frappe/bench, 2) from Bitnami**.

Please see following discussion for more information:
https://discuss.erpnext.com/t/landed-cost-voucher-on-submit-debit-and-credit-not-equal-for-purchase-invoice-pinv-01267-1-difference-is-420-0/55759?u=majid_ejaz

**Comment by clarkejj** [comment]
Please confirm this bug fixed in v12.3.1 to close this issue thanks

**Comment by majidejaz** [comment]
let me check.

**Comment by toofun666** [comment]
Not fixed on my system. Just ran update --reset

**Comment by majidejaz** [comment]
First of all, many thanks for such a speedy response.

This is a quick fix, at least we can move ahead.  **Why did I say this?** We can create only one LCV per purchase document.

So temporarily, if you want to move ahead with your working, you can still move on. All you have to do is create an LCV e.g. "LCV001". if you need to enter another LCV for the same purchase document, cancel LCV001, amend it and submit. This way at least your inventory valuation is maintained properly.

This will keep you going for now until there is a proper fix available for this problem i.e. multiple LCVs for the same purchase document.

I still have to check a few more things i.e. editing old LCVs where we have entered multiple LCVs for a purchase document and then come back with feedback.

In all honesty, this works well for now. :)

_______
erpnext 12.3.1
frappe 12.1.0

**Comment by majidejaz** [comment]
OK,

Now in my opinion, when the changes were made where multiple accounts are now allowed to be in the category of "Expenses included in Valuation", it was not taken into consideration that the system also looks at **Default "Expenses Included In Valuation"** account in company doctype at the time we submit it.

If there are previously booked LCVs and even if you cancel one, the system keeps its value and rather than reducing the value of cancelled LCV in purchase invoice, it updates the same value in the purchase invoice. even if you delete that LCV that amount stays.

In all honesty, when multiple accounts were introduced i.e. "Expense Account" the **Default "Expenses Included In Valuation"** was redundant. it can be there in **company doctype** to pull this account automatically at the time of entering the LCV (not necessarily).

**Conclusion:**
**OLD LCV, prior to the update**
Previously (prior to this fix), entered LCVs can be cancelled, but cannot be submitted after amending it.
At the time of cancelling the LCV, this cancellation does not correctly amend the "Landed Cost Amount" in the purchase invoice.
After introducing multiple "Expense Accounts" in the LCV, **Default "Expenses Included In Valuation"** is redundant in company doctype. Since there are different "Expense Accounts" in valuation category the system should not look at the **Default "Expenses Included In Valuation"** prior to submitting the LCV.

**New LCVs**
We can add only one LCV per receipt document, cancel it, amend it and submit are all ok. However, you cannot add more than one LCV for the same purchase document. We should be able to add more than one LCVs for a purchase document.

I hope it makes sense.

Thanks

**Comment by deepeshgarg007** [comment]
[This](https://github.com/frappe/erpnext/pull/20058) should allow you to create multiple landed cost voucher against a Purchase Document

> At the time of cancelling the LCV, this cancellation does not correctly amend the "Landed Cost Amount" in the purchase invoice.

Although I was unable to replicate this issue. I cancelled an old LCV and it correctly updated the landed cost amount in the purchase document.
