### ISSUE TITLE
Payment Entry exchange rate is reversed

### ISSUE THREAD

**Issue by onlinebizsoft** [frappe/erpnext#20086]
## Description of the issue
When I enter the payment entry, the exchange rate calculation seems to be reversed. My version is v12, it seems to work in v11 (I saw in https://github.com/frappe/erpnext/issues/17553)
## Steps to reproduce the issue

1. Create an invoice in a foreign currency
2. Go to invoice and create payment entry

### Observed result
![image](https://user-images.githubusercontent.com/22501570/71462726-dce24880-27e6-11ea-9760-092c28b415fb.png)

### Expected result
The amount in VND is correct. But the amount in USD should be 300. Currently it is multiplication of amount in VND and the exchange rate (USD to VND)
## Additional information
I use ERPNext develop branch, it were latest update around 10 days ago.

**Comment by onlinebizsoft** [comment]
I have just updated to latest develop and the problem is same.

**Comment by onlinebizsoft** [comment]
@deepeshgarg007 @ruchamahabal this is a bug and I hope you will quickly fix it :)

**Comment by deepeshgarg007** [comment]
@onlinebizsoft Closing this issue, if it still persists in the latest version-13 or higher versions please reopen a new issue
