### ISSUE TITLE
On Journal Entry form, Negative value getting accepted inside Debit and Credit field

### ISSUE THREAD

**Issue by ShraddhaRanjane** [frappe/erpnext#20101]
## Context information (for bug reports)

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1. Login to Admin
2.Go to Journal Entry form
3.Enter Debit and Credit amount as negative
4. Save and Submit
5.Form get submit

### Expected result
Negative Value should not be accepted
### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by toofun666** [comment]
Can you tell us why it shouldn't? After all these years, you are the first one to complain from it? Did you consider the rounding adjustments for tax items that may be in the purchase/sales invoices?
