### ISSUE TITLE
Sales return issues

### ISSUE THREAD

**Issue by Mohammedhilal** [frappe/erpnext#20100]
While creating sales return in ERPNext, the system is not maintaining the line item from which the quantity is being reversed. It is randomly reducing the quantity from any line item of the original delivery note.
For instance:
Delivery note "19-ABC" contain 3 items X, Y & Z with quantity 2 units each. Now, 1 unit of quantity from item Z was returned by the client and to record this negative sales transaction a sales return is created. Instead of reducing the 1 unit quantity from Z (actual return), the ERP is randomly reducing the the returned quantity from items X or Y. 
This is effecting our revenue while booking the sale. This issue needs to be resolved at the earliest.

**Comment by toofun666** [comment]
I am not sure that this is a bug. Please replicate and record the steps exactly so that we may see. Did you check update stock on the return document?
