### ISSUE TITLE
Issue with UOM in BOM

### ISSUE THREAD

**Issue by vikramnarayan** [frappe/erpnext#2011]
We are facing huge issues with UOM while defining BOM for items.

- We buy some products in kgs / tonnes but then use them in gms/ kgs. Same is the case with liquid

- Being in chemical industry small gms difference also make a difference. Hence to ensure better accuracy we are forced to adjust the precision on the quantity field to 4 from 2.

Am attaching a sample BOM for you reference so that you get an idea of how it looks.

The problem is

- Once quantity is defined as precision 4, values shown everywhere comes in 4 decimals. E..g. In Invoice we end up seeing 4 decimals which looks bad

- When the quantiyty is simple like say 500gms it shows 500.0000 which confuses our manufacturing guys and they end up taking wrong quantity.

**Comment by rmehta** [comment]
You can set precision in each document
