### ISSUE TITLE
Bug: Terms and Conditions Doctype terms field lines interpreted as <div>

### ISSUE THREAD

**Issue by toofun666** [frappe/erpnext#20115]
## Description of the issue
Terms and Conditions Doctype terms field lines are interpreted as <div> rather than <p> or none
## Context information (for bug reports)
Terms and Conditions Doctype terms field lines are interpreted as <div> so when they are used in Custom Format with jinja they are uncontrollable in terms of layout.
**Output of `bench version`**
```
erpnext 12.3.1
frappe 12.1.0

```

## Steps to reproduce the issue

1. Create a Terms and Conditions with terms field contaning multiple lines
2. Create a custom Print Format for Sales Invoice doctype with Terms and Conditions terms field
3. Create a Sales Invoice with Terms and Conditions and check the output in Full page and check page HTML source

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by deepeshgarg007** [comment]
@toofun666  Closing this issue, if it still persists in the latest version-13 or higher versions please reopen a new issue
