### ISSUE TITLE
Doctype to Change Desk Theme

### ISSUE THREAD

**Issue by auliabismar** [frappe/erpnext#20127]
**Is your feature request related to a problem? Please describe.**
Website has a tool to change its theme, including foreground and background color, font, etc. Meanwhile we have a bland white desk. In order to change them, we have to add custom app and change the css, and have to bench build and bench restart to test it.

**Describe the solution you'd like**
A tool to control all elements' properties.

**Describe alternatives you've considered**
At least the same functionality like Website Theme for Desk without having to build and restart.

**Comment by umairsy** [comment]
Not applicable as V13 doesn't have provision for theme at all..
