### ISSUE TITLE
Production Plan - Kanban View Error

### ISSUE THREAD

**Issue by raymondliew1992** [frappe/erpnext#20130]
## Production Plan - Kanban Error: DocType undefined not found / The resource you are looking for is not available

Hi everyone, as per the title above, couple of users in the community including myself encounter this error while creating a Kanban for Production Plan. 

I first encountered this error in v12.2.0 but the problem still persist even after I have updated to v12.3.1.

https://discuss.erpnext.com/t/production-plan-kanban-error-doctype-undefined-not-found-the-resource-you-are-looking-for-is-not-available/56097

**Comment by uosis** [comment]
This happens when DocType does not have title field set. The error could be better, or title should be a requirement for creating a Kanban board for a given DocType.
