### ISSUE TITLE
Allow relative url positioning on server. <myhost>/<somepath>/<ERPNext_Root>

### ISSUE THREAD

**Issue by mistergibson** [frappe/erpnext#20132]
**Is your feature request related to a problem? Please describe.**

I need to place/postiion ERPNext behind a relative url path on my site (I have only 1 IP address and several services).

**Describe the solution you'd like**

So, it would be something like: https://my-site.org/some-relative-path/ERPNext-root. It should support this and allow for all web assets (images, css, etc) to load properly, and generally function normally.

**Describe alternatives you've considered**

N/A : it really *should* support this out of the box - it is a common IT problem.

**Additional context**

**Comment by wjl** [comment]
I just asked about this in the forums [here](https://discuss.erpnext.com/t/how-do-i-install-erpnext-into-a-suburl-subdirectory-e-g-https-projects-example-com-erpnext/86051/5). The reply I got made me suspect that ERPNext doesn't actually support this, so I came to file a bug and found this one already filed in from 2019.

To summarize, I said:

- There is an existing machine & desired domain, `https://projects.example.com`.
- I want ERPNext installed in `https://projects.example.com/erpnext/`
- I do NOT want to make a separate machine or domain name like `https://erpnext.projects.example.com` (I know this is the “preferred way”, but isn’t tenable in this case.)
- SSL, etc, is already completely set up and other project services used by various teams are already running and working fine, e.g.
- `https://projects.example.com/bugzilla/`
- `https://projects.example.com/gitlab/`
- `https://projects.example.com/taiga/`
- … etc …

This is very common need, and pretty much every modern webapp has supported this for years (or decades in some cases). I gave these as examples later in the discussion:

- In taiga, this is configured in their docker setup by setting “TAIGA_SUBPATH”: “/taiga” in their docker-compose.yml
- In bugzilla, this is configured by setting urlbase to “/bugzilla” in their localconfig.
- In dockwiki, this is configured by setting basedir to “/docuwiki” in their online admin settings.
- In gitlab, this is configured by setting their relative_url_root to “/gitlab” in several of their config yml files.
- In openproject, this is configured by setting rails_relative_url_root to “/openproject” in their configuration.yml file.
- I could give tons of more examples.
- Of course all of these require some setting in their frontend nginx, but that's the super easy part. The app itself still needs to know this information.
- All of these are well-documented and easy to find with a simple web search, but I've spent hours looking for this kind of information for ERPNext / Frappe, including digging through the implementation details of the official docker containers, the entire set of published erpnext and frappe documentation, etc, with no success.

**This is a really important feature that should easy to implement and should be supported by ERPNext.**

**Comment by wjl** [comment]
As it sounds like this is something that is a limitation of Frappe, I filed this bug and referenced back to this issue: https://github.com/frappe/frappe/issues/15960
