### ISSUE TITLE
Support Ticket auto response Template

### ISSUE THREAD

**Issue by hwinkel** [frappe/erpnext#2014]
If you serve different customers with different language it would be good to have email auto response tickets based on templates. For each support Email address (or based on contact) you can choose the right template to send a templated canned response.

The template must be able to insert variables like $contact.name $ticket.id $project and so on.

A most generic templated auto response is our fundamental blocker to introduce ErpNext for our help desk use case.

**Comment by rmehta** [comment]
Added
