### ISSUE TITLE
bench update

### ISSUE THREAD

**Issue by lbazan** [frappe/erpnext#20143]
INFO:bench.utils:./env/bin/pip install -q -U -e ./apps/frappe
    ERROR: Command errored out with exit status 1:
     command: /opt/bench/erpnext/env/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-gm6n94au/psycopg2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-gm6n94au/psycopg2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-gm6n94au/psycopg2/pip-egg-info
         cwd: /tmp/pip-install-gm6n94au/psycopg2/
    Complete output (23 lines):
    running egg_info
    creating /tmp/pip-install-gm6n94au/psycopg2/pip-egg-info/psycopg2.egg-info
    writing /tmp/pip-install-gm6n94au/psycopg2/pip-egg-info/psycopg2.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-install-gm6n94au/psycopg2/pip-egg-info/psycopg2.egg-info/dependency_links.txt
    writing top-level names to /tmp/pip-install-gm6n94au/psycopg2/pip-egg-info/psycopg2.egg-info/top_level.txt
    writing manifest file '/tmp/pip-install-gm6n94au/psycopg2/pip-egg-info/psycopg2.egg-info/SOURCES.txt'

    Error: pg_config executable not found.

    pg_config is required to build psycopg2 from source.  Please add the directory
    containing pg_config to the $PATH or specify the full executable path with the
    option:

        python setup.py build_ext --pg-config /path/to/pg_config build ...

    or with the pg_config option in 'setup.cfg'.

    If you prefer to avoid building psycopg2 from source, please install the PyPI
    'psycopg2-binary' package instead.

    For further information please check the 'doc/src/install.rst' file (also at
    <http://initd.org/psycopg/docs/install.html>).

    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 11, in <module>

    load_entry_point('bench', 'console_scripts', 'bench')()
  File "/opt/bench/bench-repo/bench/cli.py", line 40, in cli
    bench_command()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/bench/bench-repo/bench/commands/update.py", line 68, in update
    _update(pull, patch, build, bench, auto, restart_supervisor, restart_systemd, requirements, no_backup, force=force, reset=reset)
  File "/opt/bench/bench-repo/bench/commands/update.py", line 91, in _update
    update_requirements(bench_path=bench_path)
  File "/opt/bench/bench-repo/bench/utils.py", line 469, in update_requirements
    install_app(app, bench_path=bench_path)
  File "/opt/bench/bench-repo/bench/app.py", line 171, in install_app
    exec_cmd("{pip} install {quiet} -U -e {app} {no_cache}".format(pip=pip_path, quiet=quiet_flag, app=app_path, no_cache=cache_flag))
  File "/opt/bench/bench-repo/bench/utils.py", line 173, in exec_cmd
    raise CommandFailedError(cmd)
bench.utils.CommandFailedError: ./env/bin/pip install -q -U -e ./apps/frappe

**Comment by Thunderbottom** [comment]
This isn't a bug within bench or frappe, but in fact an issue with missing library on your system. You need to install `postgres-devel` package for your system. If you're using Debian/Ubuntu, it should be fixed by installing `libpq-dev`.

**Comment by Thunderbottom** [comment]
fixed with https://github.com/frappe/frappe/pull/9176

**Comment by Thunderbottom** [comment]
fixed with https://github.com/frappe/frappe/pull/9175
