### ISSUE TITLE
[BUG] Blank comment on task

### ISSUE THREAD

**Issue by jboilesen** [frappe/erpnext#20188]
## Description of the issue
Quilljs add an empty space inside the `<li>` tag (like this `<li_>`). Then, frappe can't show this list.

## Context information (for bug reports)
ERPNext v12

## Steps to reproduce the issue
1. Create a project
2. Create a task
3. Write a comment on task creating a `<li>` list
4. Edit text with some new lines, blocks, bold and italic
5. Save the comment
6. Refresh page. The list should be empty.

### Observed result
Blank list inside comment

### Expected result
List should not be blank

**Comment by wojosc** [comment]
Hi @jboilesen This is a frappe framework issue. I have already opened an issue here: https://github.com/frappe/frappe/issues/9760

Please consider closing this.
