### ISSUE TITLE
Payment against Journal Entry

### ISSUE THREAD

**Issue by chanyork** [frappe/erpnext#20187]
Hello,

I am having issues to input payment against a Journal entry.
The Journal entry was inputed as an Opening Balance where I owe certain amount to a supplier.  

While try to make payment via payment entry so that the Account Payable Reports can reflect it, I am facing issues where the Outstanding amount will always be empty.  Please advice.

![image](https://user-images.githubusercontent.com/28833849/71778823-94e4d200-2fed-11ea-9e5c-a0bc70ba6ddd.png)

**Comment by chanyork** [comment]
Hello Anyone can help on this?

**Comment by kennethsequeira** [comment]
@chanyork please post on the [community forum](https://discuss.erpnext.com).
