### ISSUE TITLE
Supplier contact is not available in Notifications

### ISSUE THREAD

**Issue by tecnofoodmx** [frappe/erpnext#20182]
The supplier contact is not available in the Notifications configuration (V11).

https://discuss.erpnext.com/t/how-to-setup-specific-supplier-in-notifications/50771/3?u=tecnofoodmx

Thanks!

**Comment by nameduser0** [comment]
I've run into similar problems with notifications on Opportunities. My thoughts:

- [ ] Notification Recipients: allow selection of Contact fields and email fields for all doctypes
- [ ] Opportunity Source field: add `Website`
- [ ] Contact Us page: set Opportunity Source = Website

**Comment by wojosc** [comment]
Set Option Email an this will work:
![image](https://user-images.githubusercontent.com/22279621/194953705-9616f0d6-f663-41dd-a862-5fd288c57335.png)

@ankush can probably be closed now. Thanks.
