### ISSUE TITLE
On Payment Entry form-> Getting error:- TypeError: unorderable types: float() >= NoneType()  

### ISSUE THREAD

**Issue by ShraddhaRanjane** [frappe/erpnext#20184]
## Description of the issue
On Payment Entry form, when user click on 'Get Outstanding Invoice' button .it will open popup and click on 'Get Outstanding Invoice' button then got server error as 
'TypeError: unorderable types: float() >= NoneType()'

## Context information (for bug reports)

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1. Create new PI (Purchase Invoice)
2. Hold that Invoice
3. create Payment Entry from that PI
4. on payment entry form- Click on 'Get Outstanding Invoices' button
5. pop up will get open,  click on  'Get Outstanding Invoices' button
6. Server Error :-  TypeError: unorderable types: float() >= NoneType() 

### Expected result
Error should not be display when user click on Get Outstanding Invoice button, Atleast show any valid message

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by deepeshgarg007** [comment]
@ShraddhaRanjane  Closing this issue, if it still persists in the latest version-13 or higher versions please reopen a new issue
