### ISSUE TITLE
On version:-  v12.0.5 (version-12) , Payment entry gets created for holding invoice and without having reference of PI on PE

### ISSUE THREAD

**Issue by ShraddhaRanjane** [frappe/erpnext#20183]
## Context information (for bug reports)

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1. Create new Purchase Receipt (PR)
2. Through that PR ->Create PI
3. In Purchase Invoice ,If user enable flag Hold Invoice
4.It will ask to Set 'Release Date' and set release date
5.Now Submit that invoice
6. 'Create' Button  will appear
7.Create->Payment
8.If you click on payment then only soft message is displaying .like 'ACC-PINV-2020-00004 is on hold till 2020-01-06'.
But Payment Entry form gets open 
9.If you check on Payment entry form , no Reference gets append in child table 
10. Without having Reference of PI ,payment entry gets submitted
### Expected result
First of all, Payment Entry should not be created for Holding invoice. Should throw message while click on create->payment
OR
Otherwise, at least  Reference (of PI) should be shown on Payment Entry form. 

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by Ravn10** [comment]
Also invoices on hold are being included in accounts payable report
Solution:- 
Would be better if we get a check box to include invoices on hold 
in the report
