### ISSUE TITLE
Default value in filters that have "Link" from "Currency" DocType it effects filtering in "Currency Exchange"  DocType.

### ISSUE THREAD

**Issue by afarran3** [frappe/erpnext#20204]
## Description of the issue
Default value in filters that have "Link" from "Currency" DocType it effects filtering in "Currency Exchange" DocType.
## Context information (for bug reports)

**Output of `bench version`**
```
v12.3.1 (development)
```

## Steps to reproduce the issue

Go to "Currency Exchange" and you'll find that the filters is getting the default currency as a default value in every reload an its not right it should be empty in order to see your currency exchange list.

### Observed result
![observed](https://user-images.githubusercontent.com/59407100/71812712-f6a64a00-3088-11ea-999d-e0d9086ccc9e.png)

### Expected result
![expected](https://user-images.githubusercontent.com/59407100/71812678-dbd3d580-3088-11ea-87bd-b35f74124d6c.png)

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by clarkejj** [comment]
Discussion here https://discuss.erpnext.com/t/how-to-change-the-default-value-for-filters-list-views/52004/9
