### ISSUE TITLE
cannot delete batch no

### ISSUE THREAD

**Issue by alpkaan83** [frappe/erpnext#20208]
in v12 latest version, cannot delete batch xxx becouse it is related with stock entry yyy. also cannot delete stock entry yyy becouse it related with batch xxx. in v10 it didnt gave that errors and we could delete everything with stepback technic. but in latest version ve cant delete these wrong entered entries.

**Comment by clarkejj** [comment]
https://discuss.erpnext.com/t/unable-to-delete-batch-starting-in-v12/53271

**Comment by deepeshgarg007** [comment]
@alpkaan83  Closing this issue, if it still persists in the latest version-13 or higher versions please reopen a new issue
