### ISSUE TITLE
Stock Validation Issues

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#20215]
Hi ,

It seems like ERPNext isn't properly validating Stock Transactions which is ultimately leading to quite a lot of data inconsistency. We recently uploaded (and submitted) some Stock Entries via the Data Import tool (on a V12 instance) and now we're discovering a number of issues

1. Some of the Stock Entries are successfully submitted yet they did not create any accounting entries and their Stock Ledger Entries have only the outgoing side of the transaction created!

2. Some Stock Entries are submitted even when it seems as though there isn't enough Stock in the source Warehouse (Negative Stock is NOT allowed on the system)

![Stock Validation Issue 02](https://user-images.githubusercontent.com/9269337/71886680-ebacf180-313c-11ea-81a0-21522456eff4.png)

![Stock Validation Issue 01](https://user-images.githubusercontent.com/9269337/71886714-f6678680-313c-11ea-90da-f5fb068629d9.png)

There should be strict validations regarding creation of ledger entries for Stock Transactions. These kinds of issues are not okay at all!

Please help fix asap

**Comment by jorgeastiazaran** [comment]
We’re having the same issue in V13.15.2
![image](https://user-images.githubusercontent.com/66883580/144293097-0b8692d5-bf5b-4691-904e-2ab365eb6671.png)
