### ISSUE TITLE
Bug in Total value of Purchase analytics Report

### ISSUE THREAD

**Issue by Sunandha-Balasundaram** [frappe/erpnext#20219]
Bug in Total In Purchase analytics Report, If I Select Tree Type as "Item Group"

### **Observed result**
All Item Group is Parent, it is already summing up and showing the correct value of child Item groups. In Purchase Analytics Report, Total is showing by adding the value of All item group as well. Please refer to the screenshot.

![image](https://user-images.githubusercontent.com/55311033/71955100-5c234380-320d-11ea-82d9-970b7e8a58a4.png)

### **Expected result**
The total should not be displayed as similar as Sales Analytics Report
![image](https://user-images.githubusercontent.com/55311033/71955581-aa851200-320e-11ea-80e7-d83f0067398d.png)

## Additional information
ERPNext: v12.2.2 (version-12)
Frappe Framework: v12.0.20 (version-12)

**Comment by deepeshgarg007** [comment]
@Sunandha-Balasundaram  Closing this issue, if it still persists in the latest version-13 or higher versions please reopen a new issue
