### ISSUE TITLE
Plaid Integration Link a new bank account fails

### ISSUE THREAD

**Issue by git-mike-z** [frappe/erpnext#20229]
## Description of the issue
Plaid Add new bank account errors after validating bank oauth login with 

`File "/home/shmadmin/frappe-bench/apps/erpnext/erpnext/erpnext_integrations/doctype/plaid_settings/plaid_settings.py", line 59, in add_bank_accounts
    for account in response["accounts"]:
TypeError: string indices must be integers`

## Context information (for bug reports)

**Output of `bench version`**
erpnext 11.1.71
frappe 11.1.63

```

## Steps to reproduce the issue
From Plaid Settings Doctype, select "Link a new Bank Account". Log in and verify credentials. When window closes, error is generated and bank is not added.

**Comment by racitup** [comment]
Duplicate of #19293

**Comment by git-mike-z** [comment]
Will mark closed and reference [19293](https://github.com/frappe/erpnext/issues/19293)
