### ISSUE TITLE
Insufficient Permission for Assigned Appointment's Event

### ISSUE THREAD

**Issue by raymondliew1992** [frappe/erpnext#20243]
As shown below, one of the staff, Louis was assigned with the appointment created/booked by a customer. The system automatically creates an event for the appointment. However, the assigned staff was unable to access the event despite having the permission set in Role Permission.

![image](https://user-images.githubusercontent.com/52439119/72199174-3ac39100-3473-11ea-8f8d-347b66a0b0bc.png)

The user’s roles are Employee, Leave Approver, Sales User and Sales Manager.

![image](https://user-images.githubusercontent.com/52439119/72199181-56c73280-3473-11ea-974f-e5193d30756e.png)

ERPNext: v12.3.1
Frappe Framework: v12.1.0
https://discuss.erpnext.com/t/insufficient-permission-for-assigned-appointments-event/56370

**Comment by hiweye** [comment]
Same issue on 
ERPNext: v14.2.1 (HEAD)
Frappe Framework: v14.9.0 (HEAD)

The issue is that the event's owner is the guest. The easiest fix would be to set the agent (=user) as owner.
![image](https://user-images.githubusercontent.com/54437773/193428697-26eff8aa-f106-4912-80eb-6e98d66877ac.png)

**Comment by backendoadmin** [comment]
Same issue on
ERPNext: v14.2.1 (HEAD)
Frappe Framework: v14.9.0 (HEAD)

The issue is that the event's owner is the guest. The easiest fix would be to set the agent (=user) as owner.
![image](https://user-images.githubusercontent.com/5338127/193428842-f80d1d70-7768-409c-96e0-fea435b8e0db.png)
