### ISSUE TITLE
Work Order - Finish Entry in case of additional Consumption entry

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#20259]
Testing in https://version12test.erpnext.com/

Work Order: MFG-WO-2020-00001

Steps:

1. Created Work Order for 2 mobile
2. Issued raw-material for 2 mobile
3. Issues one additional box using "Consumption Entry". So, total 3 box for 2 mobile.

![image](https://user-images.githubusercontent.com/910238/72238660-63c75b80-3604-11ea-9504-52b66573d6c8.png)

When creating Finish entry for 2 mobile, based on proportion , it is taking one box. Is it correct? If we can creating Manufacture Entry for full qty, then it should fetch all the raw-materials issued.

**Comment by rohitwaghchaure** [comment]
It seems that you have set the backflush based on the Material Transfer and not BOM, closing issue
