### ISSUE TITLE
[UX] Stock and Account Value comparision

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#20256]
Is this the report we made to track the "mismatch" between specific Warehouse and Warehouse account?

<img width="1207" alt="Screenshot 2020-01-13 at 12 32 52 PM" src="https://user-images.githubusercontent.com/910238/72237568-f2d27480-3600-11ea-8fb6-9aba14aeefa3.png">

Though validation is right, but since we set Stock In Hand as a default Account, it should query all the Warehouses in this case and show us the update.

**Comment by rohitwaghchaure** [comment]
Fixed https://github.com/frappe/erpnext/pull/20277
