### ISSUE TITLE
Picture on/off switch

### ISSUE THREAD

**Issue by OfficeGirl** [frappe/erpnext#2027]
We are thinking of including the product pictures in ERP. Mainly to use them in Quotations for our customers. 

Were I do NOT want the pictures to appear is the Invoices, Sales Orders and Delivery notes - that would only waste paper. 

Is there a way to switch the pictures 'on or off' ?

**Comment by strixaluco** [comment]
Probably I don't clearly understand the matter of issue, but seems that it's irrelevant to modern codebase. Am I right?

**Comment by umairsy** [comment]
This is easily manageable using Customize Form and Print Format builder.
