### ISSUE TITLE
[bug] financial statements (P/L, B/S and cashflow) last column truncated

### ISSUE THREAD

**Issue by szufisher** [frappe/erpnext#20279]
## Description of the issue
Financial statements (P/L, B/S and cashflow) last column truncated
## Context information (for bug reports)

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1. Goto financial statement reports: Balance sheet, or profit and lost, or cash flow

### Observed result
the screenshot is taken from the demo.erpnext.com,  the same result on v12 and v11.  it seems related to datatable?

![image](https://user-images.githubusercontent.com/12823863/72320392-8b89f280-36dc-11ea-9764-e54960d01ecc.png)

### Expected result
the last column content is shown completely without the horizontal scrollbar

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by Olawale1** [comment]
I think this issue affects even other reports apart from Financial Statements. It should be a general fix for the rendering of reports

Thanks

**Comment by jvantslot** [comment]
This one has been lingering for a while.  Any fix for it yet?
