### ISSUE TITLE
[feature request] double click ( drill down ) amount column on financial statement report, jumps to general ledger report

### ISSUE THREAD

**Issue by szufisher** [frappe/erpnext#20280]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
The current financial statement reports( balance sheet, profit and loss and cash flow) shows  G/L accounts' amount in the selected period, it will be a great feature to allow user double click the figure, then auto switch to the general ledger report with filter conditions: company, start and end date, account, currency.

![image](https://user-images.githubusercontent.com/12823863/72321646-677be080-36df-11ea-96f8-9ec535a1203c.png)
Fig 1. double click the highlighted figure

![image](https://user-images.githubusercontent.com/12823863/72321726-95f9bb80-36df-11ea-802e-2cc6d2f9c0f9.png)
Fig 2. switch to general ledger report with pre-filled filtering conditions, need to add the currency as extra filter condition? 

**Describe alternatives you've considered**

**Comment by SPriytesh** [comment]
How can I do this drill down implementation for a custom report
