### ISSUE TITLE
[v11] Warning : Expected Delivery Date should be after Sales Order Date

### ISSUE THREAD

**Issue by asharamseervi** [frappe/erpnext#20338]
## Description of the issue
While creating Sales Order, if we will provide **Delivery Date** prior to the date of Sales Order creating date, it'll raise a warning alert, "Expected Delivery Date should be after Sales Order Date". Obviously, there is nothing wrong.

**Actual Issue:**
Now, after closing warning pop-up, changing **Delivery Date** to post creating date. It'll again alert with the same warning and will revert date which was earlier. While, new date should be updated and document should have saved, but it is still in draft. No console errors found.

## Context information (for bug reports)

**Output of `bench version`**
```
ERPNext: v11.1.72 (version-11)
Frappe Framework: v11.1.64 (version-11)
```

## Steps to reproduce the issue

1. Create Sales Order, select Customer, and Date (let's assume today is 17th January, 2020) and mention **Delivery Date** before the date of 17th January, 2020. Let's say, you have entered 14th January, 2020. And, filled all the mandatory fields, like Items in item table & all.
2. On saving this Sales Order, warning pop-up will appear with message, _"Expected Delivery Date should be after Sales Order Date"_ . This is expected, nothing wrong.
3. While correcting this validation, by updating **Delivery Date** to the same date or post date, let's say 20th January, 2020. But, that validation will appear again, and document will not be saved.
4. Strange is, it get saved sometimes and sometimes not, even with back delivery date for which waning had alerted.

### Expected result
Document should have saved after correcting the date. Hence, it shouldn't revert to previous mentioned date after saving document.

### Stacktrace / full error message

```
No traces in console, just warning pop-up.
Warning : Expected Delivery Date should be after Sales Order Date
```

## Additional information

Ubuntu 18.04

**Comment by deepeshgarg007** [comment]
@asharamseervi  Closing this issue, if it still persists in the latest version-13 or higher versions please reopen a new issue
