### ISSUE TITLE
Popup not showing in Exotel integration

### ISSUE THREAD

**Issue by JenishaJayaraj** [frappe/erpnext#20372]
We have done the setup for Exotel integration in our Erpnext site.
Complete setup is done as per documentation [https://erpnext.com/docs/user/manual/en/erpnext_integration/exotel_integration](https://erpnext.com/docs/user/manual/en/erpnext_integration/exotel_integration). We tried testing, its working got call logs ,but the pop is not showing.

**Comment by 96MayankJain** [comment]
@JenishaJayaraj  is this issue has been resolved? I am facing the same issue in version 13. **Popup is not showing**
