### ISSUE TITLE
In version 12, you cannot deleted batches and stock entries that are linked to each other [BLOCKING ISSUE]

### ISSUE THREAD

**Issue by julsmon** [frappe/erpnext#20394]
Hello, 

If you happen to do a wrong stock entry that consequently creates batches, you are not allowed anymore to delete neither the batches and the stock entry.
When you try and delete the faulty stock entry X the system says:

> You cannot delete stock entry X because it's linked to batch Y

When you try and delete batch Y the system says:

> You cannot delete batch Y because it's linked to stock entry X

Please note that this creates a blocking issue. Errors in warehouse management do happen and it's mandatory to be able to fix them promptly, before making any other entries. Also, this was perfectly possible in V11.

**Comment by julsmon** [comment]
By the way, we're hosted users.

**Comment by julsmon** [comment]
Being fixed: https://github.com/frappe/erpnext/pull/20392

**Comment by kennethsequeira** [comment]
@julsmon if you're hosted on erpnext.com, in future, raise issues directly to the support team
