### ISSUE TITLE
Chart of Accounts Importer Issue [V12]

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#20397]
Hi ,

We are encountering the below error with the Chart of Accounts Importer even though Group Accounts in the template already have the listed account types (Bank, Cash, Stock)

`Please identify/create Account (Group) for type - Cash , Bank , Stock`

I suspect this is because the system toggles the 'Account Type' field as hidden whenever it is a Group Account

Pls help fix this asap

Thanks

**Comment by Olawale1** [comment]
I got past it temporarily by commenting out a few lines of code in the chart_of_accounts_importer.py file as shown below:

```
def validate_account_types(accounts):
	account_types_for_ledger = ["Cost of Goods Sold", "Depreciation", "Fixed Asset", "Payable", "Receivable", "Stock Adjustment"]
	account_types = [accounts[d]["account_type"] for d in accounts if not accounts[d]['is_group'] == 1]

	missing = list(set(account_types_for_ledger) - set(account_types))
	if missing:
		return _("Please identify/create Account (Ledger) for type - {0}").format(' , '.join(missing))

#	account_types_for_group = ["Bank", "Cash", "Stock"]
#	account_groups = [accounts[d]["account_type"] for d in accounts if accounts[d]['is_group'] not in ('', 1)]

#	missing = list(set(account_types_for_group) - set(account_groups))
#	if missing:
#		return _("Please identify/create Account (Group) for type - {0}").format(' , '.join(missing))
```
Hopefully we can get a proper fix soon

Thanks

**Comment by SDLyu** [comment]
We encounter same issue.
I think the condition in chart_of_accounts_importer.py 
```
account_groups = [accounts[d]["account_type"] for d in accounts if accounts[d]['is_group'] not in ('', 1)]
```

should change to

```
account_groups = [accounts[d]["account_type"] for d in accounts if accounts[d]['is_group'] == 1]
```

**Comment by maovidal** [comment]
I had this issue with the types: Cash , Bank , Stock.
I confirm @SDLyu proposal worked for me.
By the way, a huge thank you for this.

**Comment by wojosc** [comment]
I also encountered this problem. @SDLyu  solutions works. Is there already a PR for this solution? Is that necessary?

**Comment by SDLyu** [comment]
This issue seems fixed.
https://github.com/frappe/erpnext/commit/5c2ba0ef9c6e6424af95b841dade3e0b873184aa

**Comment by alkuhlani** [comment]
Same with me

**Comment by alkuhlani** [comment]
Solved with me

**Comment by alkuhlani** [comment]
Also, I have an issue with the numbered accounts
