### ISSUE TITLE
[UX V12] Move linked company selection for Plaid bank account to the first step

### ISSUE THREAD

**Issue by racitup** [frappe/erpnext#20419]
## Description of the issue
When adding a Plaid bank account, at the end of the process you have to select the linked Company. If the Company does not exist, you have a link to create one, but the Plaid bank account information is lost. This means you have to start from scratch. It would make more sense as the first step of adding the Bank Account.

The information requested at the first step should also include the start date for bank transactions found on the Bank Account:
![Screen Shot 2021-01-26 at 20 25 12](https://user-images.githubusercontent.com/18157195/105973185-57ce0080-6084-11eb-8fed-f2b09d9011dc.png)

## Context information (for bug reports)
File requiring change:
erpnext/erpnext_integrations/doctype/plaid_settings/plaid_settings.js
**Output of `bench version`**
```
erpnext 12.3.1
frappe 12.1.0
```

## Steps to reproduce the issue
1. Configure Plaid
2. Select `Link a new bank account`
3. Go through bank account addition process
4. Try to enter a company and select the `Create a new Company` link

### Observed result
Takes you away from the page and the Plaid bank account info is not saved

### Expected result
All information for adding the bank account should already be known and it should save immediately, i.e. Create the Company as the first step of the process.
Note the Company **MUST** also have a 'Bank Account' Account from the Chart of Accounts created and selected:
Account Settings - Default Bank Account

## Additional information
Ubuntu 18.04

**Comment by deepeshgarg007** [comment]
@racitup  Closing this issue, if it still persists in the latest version-13 or higher versions please reopen a new issue
