### ISSUE TITLE
Compact Item Print doesn't show fields correctly

### ISSUE THREAD

**Issue by lxnow** [frappe/erpnext#20421]
Per section 2.2 of [this](https://erpnext.com/docs/user/manual/en/setting-up/print/print-settings), the `Compact Item Print` feature concatenates certain fields to make things look neater. However, based on the following fields selected in Print Format Builder (for docytype Sales Invoice)
![unnamed](https://user-images.githubusercontent.com/5035210/73118200-f44e5600-3f8b-11ea-98f8-0c8b124dbe16.png)
The print format comes out like the following... only four fields shown with no concatenation; in fact it looks more like fields are missing.

![image](https://user-images.githubusercontent.com/5035210/73118210-2069d700-3f8c-11ea-9157-d2f1d639b554.png)

**Comment by manasan3010** [comment]
If you want to use "Compact Item Print" then you need to enable "Description" column in the print format
