### ISSUE TITLE
Remove G Suite related items in Awesomebar /search bar

### ISSUE THREAD

**Issue by lxnow** [frappe/erpnext#20497]
Since G Suite settings are deprecated, might as remove it from the system so users aren't confused (or made hopeful :) !

![image](https://user-images.githubusercontent.com/5035210/73587873-18fe7c80-44fc-11ea-9eb0-2c7e7ea0e580.png)

**Comment by kennethsequeira** [comment]
Closing this as it has been removed from v12, 13, and develop branches at the time.
