### ISSUE TITLE
[BUG] Cannot edit Item Price

### ISSUE THREAD

**Issue by mimiza** [frappe/erpnext#20504]
Hello sirs. After updating to the latest version of ERPNext and Frappe, my system gets a very weird error when trying to update Item Price.

***Installed Apps***
ERPNext: v12.4.2 (version-12)

Frappe Framework: v12.2.1 (version-12)

Please take a look at the picture below.

![Screenshot_2020-02-02-22-06-16-13](https://user-images.githubusercontent.com/20904034/73610423-9ebc1e00-4609-11ea-9484-943911fc8775.jpg)

Thank you for reading.

**Comment by clarkejj** [comment]
Discussion here https://discuss.erpnext.com/t/bug-unable-to-edit-item-price-item-price-appears-multiple-times-based-on-price-list-supplier-customer-currency-item-uom-qty-and-dates/57583

Note this recent fix https://github.com/frappe/erpnext/pull/20347
