### ISSUE TITLE
Manufacturing valuation not accurate!

### ISSUE THREAD

**Issue by sorinpaul** [frappe/erpnext#20514]
Hello!
It appears that there is a problem in stock valuation(FIFO).
Suppose i have an Item1 manufactured, that requires a quantity of 10 pcs of Item2 (raw material).
I buy 6 pcs of Item2 from a supplier with a price of 3$/unit, and 6 pcs from another supplier, at a price of 4$/unit. After updating cost in BOM of Item2, the valuation is 35$ (median price of all quantity in stock).
After starting the work order for 1 piece of Item1, based on BOM, I make material transfer to WIP, a quantity of 10pcs of Item2. Using FIFO, it takes 6pcs at 3$, and 4 pcs at 4$. 6x3$+4x4$=34$.(correct)
The material transfer has an accounting ledger of 34$.
After that, material consumption is correct, at 34$.
But when I make the manufacturing stock entry, it calculates on BOM valuation, at 35$ (wrong)
So, total cost is 34$, but the value that enters on Finished goods warehouse is 35$.
I think that the manufacturing stock entry _must be calculated not on BOM, but on consumption cost_.
Also, if there are multiple entries for raw material, the BOM price will be calculated using a median price of actual stock, which is not correct, because in case FIFO is used, first entries will be consumed, which may have a different price then median price of the stock.
Please correct me if I’m wrong.
ERPNext Version-12-develop

**Comment by clarkejj** [comment]
See discussion here https://discuss.erpnext.com/t/manufacturing-valuation-not-accurate/57584

**Comment by deepeshgarg007** [comment]
@sorinpaul  Closing this issue, if it still persists in the latest version-13 or higher versions please reopen a new issue
