### ISSUE TITLE
Direct Cancel (without Submit)

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#2052]
- [ ] Allow direct cancel if cancel rights exist.
- [ ] Run event `on_cancel_without_submit` instead of `on_cancel`

**Comment by vjFaLk** [comment]
Direct cancel?

**Comment by anandpdoshi** [comment]
@vjFaLk 

Right now, only submitted documents can be cancelled. Cancelled implies the document shouldn't be editable and it is not official anymore.

**Comment by kimsreng** [comment]
Is there anyway to get it work?
