### ISSUE TITLE
Hospitality domain not appearing on Desk

### ISSUE THREAD

**Issue by BernMaina** [frappe/erpnext#20538]
Hi,

i have realised that the Hospitality domain is not showing on desk for version 12. I have tried to do a hard clear cashe but still nothing. Its a fresh install. 

Kindly check and revert.

**Comment by P-Froggy** [comment]
It doesn't show up on purpose, because the hospitality domain is still in beta stage.

**Comment by BernMaina** [comment]
Hope once the module moves to production then it will be visible on desk
