### ISSUE TITLE
Not selecting both yes or no option on dialog it is still creating Material Request.

### ISSUE THREAD

**Issue by abhijitkumbharInd** [frappe/erpnext#20589]
**## Description of the issue**

On Production Plan if a user clicks on create Material Request option one confirm dialog open up.
Saying _Do you want to submit the material request_. If a user doesn't click yes or no then still it creates Material Request in draft mode.

**## Steps to reproduce the issue**

1. Create a Production Plan and submit it.
2. Click on create Material Request button.
3. A popup appears "Do you want to submit the material request".
4. Don't click outside of the dialog box.
5. Still, it is creating a Material Request.

**### Observed result**
Not selecting an option of the dialog box if the user clicks outside the box Material Request gets created.
### Expected result
Material Request should not create unless and until user click on yes (submit MREQ) or no (draft MREQ) button

![Not selecting both yes or no option on dialog it is still creating Material Request](https://user-images.githubusercontent.com/40858925/74581951-d8166580-4fdb-11ea-9efe-f657936d7bf0.gif)

**Comment by lokesh-indictrans** [comment]
Working on it

**Comment by deepeshgarg007** [comment]
@abhijitkumbharInd  Closing this issue, if it still persists in the latest version-13 or higher versions please reopen a new issue
