### ISSUE TITLE
HSN/SAC Error while creating a new item and not selecting the field.

### ISSUE THREAD

**Issue by Darpan24** [frappe/erpnext#20590]
## Context information (for bug reports)

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1.Create a New item
2.Select the field of HSN/SAC
3.Don't select any value for the field and click outside the box leaving the docfield value empty.
4.It throws an error that "GST HSN Code None not found" and "The resource you are looking for is not available"

### Expected result
1. It should not throw an error since it is not a mandatory field if we leave it blank after selecting it.

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by deepeshgarg007** [comment]
@abhijitkumbharInd not able to replicate anymore, closing this issue
