### ISSUE TITLE
Create E-Way bill JSON thows server error.

### ISSUE THREAD

**Issue by abhijitkumbharInd** [frappe/erpnext#20626]
**## Description of the issue**

While generating E-Way bill if a user click on create E-Way bill JSON from submitted Sales Invoice
it throws server error.

**## Steps to reproduce the issue**

1. Create a Sales Invoice.
2. Submit a Sales Invoice.
3. Click on Create E-Way bill JSON

**### Observed result**
On clicking Create E-Way bill JSON it throwing server error.

**### Expected result**
It must show a proper message. e.g. Company GSTIN is required to generate E-Way Bill JSON

**Comment by clarkejj** [comment]
Here's a similar report https://discuss.erpnext.com/t/getting-error-while-creating-e-way-bill-validationerror-company-gstin-is-required/57052
