### ISSUE TITLE
Pay Later in POS Profile

### ISSUE THREAD

**Issue by dexterhussain** [frappe/erpnext#20630]
I am having an issue which I want to solve , I want to deploy ERP at my own shop , we have a mechanism that in our shop sale persons make an invoice but customer doesn't pay it they come to the end of the store and then pay it to cashier, Cashier just loads the number , and if customer goes to multiple places they add items to same invoice and then cashier takes money at the end , How we can achieve this ? If i use the old invoice then in rush hours it takes much time to make invoice any robust way? or any way to delay the payment in POS?

**Comment by dayofmythology** [comment]
I am interested in this feature as well. Is there any workaround for now?
