### ISSUE TITLE
Why i can not select rows and create another document like po from material request after submit v.12

### ISSUE THREAD

**Issue by Ashraf-Elsharqawy** [frappe/erpnext#20651]
![afbb284cffcdb63aa76142572e80fe3401fa5e67](https://user-images.githubusercontent.com/52603121/74672104-3cd8e800-51b5-11ea-8df8-3183d18de3a4.jpeg)

**Comment by deepeshgarg007** [comment]
@Ashraf-Elsharqawy This is not a bug but a feature request, we already have an alternative for this to fetch items selectively. Closing this issue
