### ISSUE TITLE
'Material Request' with type = 'Manufacture' doesn't shows up NON-PURCHASED items in the Items search box.

### ISSUE THREAD

**Issue by mkashif14** [frappe/erpnext#20672]
## Description of the issue
'Material Request' with type = 'Manufacture' doesn't shows up NON-PURCHASED, manufactured and salable items in the Items search box.

## Context information (for bug reports)

**Output of `bench version`**
```
bench_manager 0.0.1
erpnext 12.4.2
frappe 12.2.1
```

## Steps to reproduce the issue

1. Create an 'Item' which has the following setup (along with other required fields)
  a. 'Default Material Request Type' = 'Manufacture'
  b. 'Is Purchase Item' = False
  c. 'Is Sales Item' = True

2. Create a new 'Material Request' where 'Type' = 'Manufacture'

3. In the 'Items' grid, try keying in the 'Item Code' for the item that was created in step #1. You'll observe that the item suggestion list doesn't show the newly created item and it says 'Filters applied for Is Purchase Item = 1' (see snip in the below section)

Although I can key in the complete ItemCode and the screen will accept that as a valid Input

### Observed result
![image](https://user-images.githubusercontent.com/34096765/74741463-d3bfa600-5282-11ea-9add-aeeb6cf57640.png)

### Expected result
I would expect that the Item suggestion list should show non-purchased items as well when the 'Type' = 'Manufacture' is selected.

## Additional information

I don't have any customizations in my environment

**Comment by deepeshgarg007** [comment]
@mkashif14 Why these items need to show up and why this is a bug, can you please explain and then reopen the issue?
