### ISSUE TITLE
Remove Search Filter

### ISSUE THREAD

**Issue by sayemalhasan** [frappe/erpnext#20685]
![serachBar](https://user-images.githubusercontent.com/30211545/74917993-a4c84200-53f2-11ea-904e-aceaceccfab5.png)

As you see in the given **screenshot**… i want to **remove this filter from every doctype**.
How do i can **remove this filter and column section???**

**Comment by barredterra** [comment]
Please use the forum at https://discuss.erpnext.com to ask for help.

The ID column cannot be removed in the report builder. However, you could build a [Query Report](https://frappeframework.com/docs/user/en/guides/reports-and-printing/how-to-make-query-report). There you have a little more flexibility.
