### ISSUE TITLE
Stop printing draft for specific document and print cheque only once

### ISSUE THREAD

**Issue by Ashraf-Elsharqawy** [frappe/erpnext#20697]
could you plz add option to prevent user to print draft invoice only  not all doctype as set in printing setting now    and  user can print payment entry a lot of times  we neet it print cheque once   and one role only that have permission to print more

**Comment by Ponyooooo** [comment]
Also, aside from the draft print, is it possible to have a print counter per doctype? This is to limit the user on printing multiple cheques and invoice which is crucial for all businesses. This is also to audit how many times the employee has an error print.
