### ISSUE TITLE
@comment setting

### ISSUE THREAD

**Issue by ShehataGhattas** [frappe/erpnext#20690]
Dear Developer, 
i do have that system working for me long time but now am facing that when some one do mention fro some one at document comment only the document owner got notified by mail.
but the mentioned person he got nothing i wish you give the support as usual.

**Comment by kennethsequeira** [comment]
@ShehataGhattas ask the user to check their notification settings by clicking on the bell icon and check if it is enabled for mentions:

![image](https://user-images.githubusercontent.com/33246109/75007769-232cee80-549c-11ea-9f90-309614f3ac2b.png)

**Comment by ShehataGhattas** [comment]
i need to know this is applied in which version, because the one i have , is 
erpnext 10.1.54
foundation 0.0.1
frappe 10.1.49
i dont have plane to update to knew version because this one was working perfect long time ago this thing just happened and all setting show allow notification
![image](https://user-images.githubusercontent.com/22128816/75013050-7733d500-5494-11ea-99b9-a7906a240a6a.png)

**Comment by wojosc** [comment]
@ShehataGhattas This was introduces in Version 11/12. I am not quite sure. I think 12...
