### ISSUE TITLE
Tax Window for Sales return and Purchase Return Stock Entries

### ISSUE THREAD

**Issue by Jaliya** [frappe/erpnext#2069]
FEATURE REQUEST.
Please include a window for tax in SALES RETURN and PURCHASE RETURN Stock Entries similar to what you have in PURCHASE RECEIPTS and PURCHASE INVOICES.
Thanks

**Comment by akshay83** [comment]
+1

specially when using VAT

**Comment by umairsy** [comment]
Added in V7 where Sales and Purchase Return entry is created from Sales Invoice and Purchase Invoice respectively.
