### ISSUE TITLE
Bulk Payment Request

### ISSUE THREAD

**Issue by unidow** [frappe/erpnext#20700]
There should be a bulk payment request in ERPNext i.e. processing payment in batches. This will reduce effort in making payments to several vendors.

It is possible that I might not know this. You can help in finding it if it's already there.

**Comment by zuron7** [comment]
I'm new to ERPNext, but is Payment Order what you are looking for?

https://erpnext.com/docs/user/manual/en/accounts/payment-order

**Comment by redstonedesigner** [comment]
Hi,
I've just been linked this issue to triage from CodeTriage.

Is this still an issue?  I've noticed that it's gone stale now for just over a year.

Thanks,
redstonedesigner
