### ISSUE TITLE
Customer List Not Showing

### ISSUE THREAD

**Issue by chanyork** [frappe/erpnext#20711]
My account: chanyork@gmail.com

Issue: Customer List is empty does not populate with the customer that I have.

Cheers,
York

**Comment by chanyork** [comment]
Hello Anyone can pick up this ticket?

**Comment by kennethsequeira** [comment]
Please provide more information surrounding the issue. If you're hosted on erpnext.com, raise a support ticket by emailing to support@erpnext.com or from the [support app](https://erpnext.com/in-app-support).
