### ISSUE TITLE
Trouble with Namingseries for DocType Customer

### ISSUE THREAD

**Issue by wojosc** [frappe/erpnext#20729]
##  Description of the issue
A customer Namingseries for Customer is overridden when creating Customers from Leads or Opportunities.

## Context information (for bug reports)

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1. Change Namingseries and test that a customer is created with the custom namingseries
2. Create Lead
3. Create Customer from Lead (2)
4. Notice that the new customer has standard Namingseries

### Observed result
The custom added Namingseries (in my case K-.#####) is deleted and set back to standard.

### Expected result
Custom set Namingseries should not be overridden from some where else.

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by deepeshgarg007** [comment]
@wojosc I am unable to replicate this, please reopen the issue with more details if this is still replicable
