### ISSUE TITLE
Integration of auto-generated "Publications" section and home page section functionality on the HomePage

### ISSUE THREAD

**Issue by robertbecht** [frappe/erpnext#20744]
In Erpnext 12 under webpage the functionality is currently developed to make a modern good looking home page.
A new doc type homepage sections defines the content of sections. that can either be based on Cards or HTML.
However, there is also an section that is **hard-code and auto generated** named "Publications" that contains the last 3 Blogs.

I feel that these two rather similar functionalities that both generate a section should/could be integrated, so that the website manager has more control. As said, "Publications" has no controls and is fully hard code.

Update: 8 March 2020

Some experimenting with someone with hardly coding background.
At the home page defaults one can copy the generated html code from the webpage using show source code.

In the home page section doc i have created entries Hero, Products where I have copy pasted the code as described in paragraph above and than select Hero Section Based on "Home Page Section"

Using this approach there is almost full control over appearance of the Home Page.
Unfortunately, even when selecting Hero Section Based on "Home Page Section" the Publication Section is AutoCreated.   

In my view there are several ways to to allow maximum functionality>
1. Stick to current approach but add to home page also the now autogenerated "Publications"
**Furthermore add an enable/disable tickmark and !!! important !!! the "section order" number that is also defined in de homepage sections doc.**

2 An alternative would be to make of the Home page doc only a skeleton. Similar to print formats the home page section doc would contain a number of default sections code by frappe like hero, products, publications, and so on.  The user can use these " as they are" or copy and edit.

3. A kind of mix between 1 and 2........In the home page there are sections for Hero, Products, Publications, and so on....an a button "show code" that can be pasted in the home page section doc.
So...similar what I have done now, by copying the code form the generated home page.

In my view the amount of extra coding to implement these suggestions is very minimal...and the result is that the user has full freedom to design the homepage without the current restriction due to hardcoding some of the sections.

see experiment..may change over time  dogsloveit.erpnext.com/home

**Comment by parsimonyERP** [comment]
+1

**Comment by scmmishra** [comment]
Hey @robertbecht Thanks for the suggestions. We'll try to incorporate this in the current roadmap

**Comment by nameduser0** [comment]
I completely agree with the above, and it is related to #21515 too.

My take on it is the hard-coded sections: Products & Blogs should be moved to the Homepage Sections as *special* sections. The `Section Based On` field should be extended with these two extra options which will change the form to have a table referring to either Items (for products) or Blog Posts (for blogs). This will allow you to use the section order for all sections and significantly tidy the home.html template and remove the Products section from the Homepage doctype.

I will give this a go and submit a PR to v13 develop and v12-hotfix

**Comment by Anurag810** [comment]
#22119
