### ISSUE TITLE
Trial Balance Issue in Accumulated depreciation Credit Side

### ISSUE THREAD

**Issue by sammish** [frappe/erpnext#20762]
Dear @nabinhait we have facing issue in our trial balance accumulated depreciation credit amount not refelecting in trail balance. 

We have restored this same database with below version then it was working fine.

![image](https://user-images.githubusercontent.com/12432802/75464448-440fab00-5998-11ea-843b-f5d20c927fab.png)

Current Version 

![image](https://user-images.githubusercontent.com/12432802/75464470-4c67e600-5998-11ea-9daf-15734ee0e438.png)

![Peek 2020-02-27 19-18](https://user-images.githubusercontent.com/12432802/75464336-1dea0b00-5998-11ea-807d-03bc136e8571.gif)

Fixed assent also issue

Fixed asset amount not reflecting in trail balance.
![Peek 2020-02-27 19-45](https://user-images.githubusercontent.com/12432802/75465952-6f939500-599a-11ea-8165-f8e9a7a20e54.gif)

Kindly fix this as a hotfix.

**Comment by nextchamp-saqib** [comment]
I looked into our test account but couldn't find the mismatch. Could you check if you have duplicate Depreciation Entries created?

**Comment by santoshbb** [comment]
Thank  you Saqib,
I have restored the same database in two different versions and reviewed the Trial Balance and General Ledger for same ledger.
Kindly check the below videos for 2 different erp versions :

1st video for Version erpnext=12.4.3, frappe=12.2.1 (working for depreciation)

![TB in old version](https://user-images.githubusercontent.com/10789840/75526759-6a2e5d00-5a23-11ea-93da-71e5c43a1d96.gif)



2nd video for version erpnext=12.5.1, frappe=12.3.0 (Credit amount of depreciation not reflecting in TB)

![TB in new verion](https://user-images.githubusercontent.com/10789840/75526881-aa8ddb00-5a23-11ea-8dd0-3135a2b55a63.gif)

**Comment by santoshbb** [comment]
I hope I am able to convince you with above details.
Same problem we have for Fixed Assets too.
Please find the below image  
![TB](https://user-images.githubusercontent.com/10789840/75537490-4de0ef00-5a28-11ea-97dc-ad2336da2850.png)

**Comment by nextchamp-saqib** [comment]
I can't debug this if I am not able to replicate. I have some test accounts but none of them have this behaviour.

**Comment by santoshbb** [comment]
In below picture total of assets should be 11,000,354 but it is reflecting as 5,876,926, the totaling error?

![image](https://user-images.githubusercontent.com/10789840/75537855-c5af1980-5a28-11ea-8221-bf6d7e0c4e62.png)

**Comment by nextchamp-saqib** [comment]
> In below picture total of assets should be 11,000,354 but it is reflecting as 5,876,926, the totaling error?
> 
> ![image](https://user-images.githubusercontent.com/10789840/75537855-c5af1980-5a28-11ea-8221-bf6d7e0c4e62.png)

I just replicated this particular error. Yes it is an error with calculating total.

**Comment by santoshbb** [comment]
ok,

Could you please suggest me how can I get rid of depreciation issue?
I don't think it could be data manipulation error.
We are actually running with auditing, Can you please check my Trial Balance if I get you connected to ERP.
I kindly request you to extend your help.

**Comment by nextchamp-saqib** [comment]
Please try `bench build` and `bench clear-cache` and let me know. Both of the issue seems to be a totalling issue. 

P.S: Try reverting changes of [this](https://github.com/frappe/erpnext/pull/20411) PR.

**Comment by santoshbb** [comment]
I tried it but same problem

**Comment by nabinhait** [comment]
> 2nd video for version erpnext=12.5.1, frappe=12.3.0 (Credit amount of depreciation not reflecting in TB)

@santoshbb We still cannot replicate the issue. Are you using Finance Book?

**Comment by nabinhait** [comment]
> In below picture total of assets should be 11,000,354 but it is reflecting as 5,876,926, the totaling error?

This is intentional.
Total opening debit (11,000,354) - Total opening credit (5,123,428)= 5,876,926

**Comment by sammish** [comment]
@nabinhait this is pure bugs (Trial Balance Accumulated Depreciation )

You can see from this video . 

There is no closing credit. there is no entry in credit side 

Please check two financial years. 


![ezgif com-optimize (1)](https://user-images.githubusercontent.com/12432802/75673551-4291fb80-5c94-11ea-886e-ad36840a895e.gif)


![Peek 2020-03-02 14-35](https://user-images.githubusercontent.com/12432802/75673602-65241480-5c94-11ea-8744-4c11dd6277ec.gif)

**Comment by santoshbb** [comment]
> > In below picture total of assets should be 11,000,354 but it is reflecting as 5,876,926, the totaling error?
> 
> This is intentional.
> Total opening debit (11,000,354) - Total opening credit (5,123,428)= 5,876,926

Nabin,
This is not intentional. 
I apologize for this. The totaling is currect.
but we have depreciation issue.

**Comment by sammish** [comment]
@nabinhait is there any update.

**Comment by sammish** [comment]
@nabinhait Can you have any comment here. Is this our issue, or this is Bugs?

**Comment by nabinhait** [comment]
> @nabinhait this is pure bugs (Trial Balance Accumulated Depreciation )
> 
> You can see from this video .

I have checked in your cloud account. The amount against accumulated depreciation account is not coming in Trial Balance because those GL entries has been made against Finance Book "Asset Book" and in Trial Balance, you did not select "Finance Book".
In General Ledger it is coming, here it dumps GL for all finance books (if finance book is not selected as filter)

**Comment by sammish** [comment]
@nabinhait You are really helped me. Because I have never thought about this filtering. Anyhow I will try to learn more about the "financial book".
