### ISSUE TITLE
UK based User - GST Features have appeared in our instance

### ISSUE THREAD

**Issue by sarastewart22** [frappe/erpnext#20777]
Apologies if this is the incorrect way to report - see the attached images below which display new fields which have appeared in our production instance of ERPNext. The Developer we work with suggested raising this here. His comments..."I'm afraid there seems to be something amiss with the standard ERPNext updates. Looks like the India GST Features have crept into non-India instances. It will perhaps be corrected in future updates." Images attached. Thank you!
![image](https://user-images.githubusercontent.com/61585734/75546655-ec695200-5a20-11ea-83c6-52005fa9d5f9.png)

**Comment by sarastewart22** [comment]
This has also appeared and I wonder, is this connected?
![image](https://user-images.githubusercontent.com/61585734/75546683-086cf380-5a21-11ea-8646-c5a5911c8256.png)

**Comment by marination** [comment]
@sarastewart22  You will get more active responses on [discuss.erpnext.com](https://discuss.erpnext.com/). Also it seems like the India regional setup was run at the beginning of creating the instance. Any chance India was accidentally selected?
