### ISSUE TITLE
Accounts Receivables Query report doesn't follow user permissions

### ISSUE THREAD

**Issue by lxnow** [frappe/erpnext#20780]
Currently have a restriction on users based on the value of the Sales Partner field. Also have "strict" user permissions applied. This means that users can only a access documents where sales partner value = their user name or as defined. This works well for records viewing and reports via report builder.

However, the Accounts Receivable Query report still shows values related to other documents. Is there a way to limit the view on this? In other words an SQL query report (server side) is not following the user permissions, which is a bit nonsensical. UX solution should be that permissions are followed.

Steps to recreate:

1. user's permission restrictions are set to all documents where sales partner = `John Doe`
2. set permissions  to strict
3. using the user's (John Doe) account, generate an AR query report via Accounts -> Accounts Receivable
4. user is able to successfully generate the report (already has the right read permissions). However, note that there are records here that are not supposed to be viewable because the sales partner value is != `John Doe`. 
5. But if user opens one of the records from the AR report (basically clicking the link to the record), the record will not be displayed to error "restricted field"

**Comment by deepeshgarg007** [comment]
@lxnow I tried to fix/implement this but it doesn't seem possible with the current doctype and report structure.
One invoice can have n number of Sales Person linked to them but the AR/AP report shows one single row for one invoice and the Sales Person field is not a link field but a Data Field showing all the Sales Persons separated by a delimiter.

In order for the report (sales-person) specifically to work with user permissions, the invoices will have to be shown sales-person wise separately which is again a separate feature request.

**Comment by lxnow** [comment]
@deepeshgarg007 thanks for update. However, I think you are referring to "sales people" or sales persons, which is a different field and is part of a child table to the Sales Invoice. This issue refers to the `sales_partner` field which is part of the Sales Invoice parent doctype, so there is only one value for `sales_partner` per Sales Invoice.
