### ISSUE TITLE
Item Default UOM didn't fetch on quick entry

### ISSUE THREAD

**Issue by Delte** [frappe/erpnext#20785]
## Context information (for bug reports)

**Output of `bench version`**
```
ERPNext: v12.5.1 (version-12)

Frappe Framework: v12.3.0 (version-12)
```

## Steps to reproduce the issue

1. Create a Price list
2. Make a Quick Entry on a item
3. check UOM at Report View

### Observed result
Didn't fetch default UOM for item

### Expected result
fetch default UOM for item

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by vasylherman** [comment]
'Fetch from' also does not work on quick entry. As soon as I click on "edit in full page" then my fields  fill correctly.
