### ISSUE TITLE
Pricing Rule of Adding Margin isn't working

### ISSUE THREAD

**Issue by raymondliew1992** [frappe/erpnext#20791]
Kindly refer to the link below:
https://discuss.erpnext.com/t/pricing-rule-add-margin-not-working/58664

ERPNext: v12.4.2 (version-12)
Frappe Framework: v12.2.1 (version-12)

**Comment by dj12djdjs** [comment]
It seems this is still a problem when it comes to applying multiple price rules to a margin.
https://discuss.erpnext.com/t/pricing-rule-w-apply-multiple-pricing-rules-margin/72118
