### ISSUE TITLE
Inventory Reconciliation - Serialized Inventory

### ISSUE THREAD

**Issue by sarangdj** [frappe/erpnext#2079]
Thie request relates to the Inventory Reconciliation feature for Serialized / batched inventory.

Business Scenario
1. Consider Product001 coming in through different suppliers (Supplier A and Supplier B) at different prices and different times. 
2. During the Material Dispatch, you need to select the item from Supplier A to a Customer

ERPNext Scenario
This can be done through Serialized inventory by assigning Batch Nos. to the different lots purchased from Supplier A and Supplier B. However, the problem is, incase you need to reconcile the inventory of Product 001 from Supplier A, you can't use the inventory reconciliation tool, as the inventory becomes Serialized.

Desired Function
It is highly desirable to develop the Serialized Inventory Reconciliation feature to have best of both worlds where you get the ability to define your inventory by lot and you also get to reconcile it through the Inventory Reconciliation feature.

Thanks in advance

Sarang
Systematrix Solutions

**Comment by osslabph** [comment]
Any update on this?

**Comment by rmehta** [comment]
@osslabph as you can see there are no commits linked to this issue. I understand you want to ask the question to bring it to attention. But if you really need it. Make it happen! Asking others to do it for you without any contribution is not how open source works.

**Comment by joezsweet** [comment]
@sarangdj can you please check v8? if feature not there, please provide detailed specification and mockup.

**Comment by kennethsequeira** [comment]
@sarangdj 

do check if the scenario is now possible: https://erpnext.com/docs/user/manual/en/stock/stock-reconciliation#42-for-serialized-items

If not, you can open a new issue with what would the desired feature requirements be.
