### ISSUE TITLE
Undeposited Funds

### ISSUE THREAD

**Issue by sarangdj** [frappe/erpnext#2080]
This feature request relates to an intermediary ledger called undeposited funds where payment intimations are recorded and the funds are transferred to the bank account after payment confirmation.

Business Scenario
A customer makes a payment against an invoice through check (or Credit Card). The payment takes some time to realize in your bank account. 

ERPNext Scenario
At present, the payments are applied to the Checking Bank Account. Incase of an issue with the payment, the bank funds shown in ERPNext may not be accurate. 

Desired Function
A facility to deposit the customer payment intimations to a ledger like undeposited receipts. Once the payments are realized in the bank account, ERPNext will provide a feature where you can select the realized payments and transfer them to the designated Checking Bank Account. Once the deposits are transferred, they shall be set active and a report of this should be available in the system.

**Comment by umairsy** [comment]
For now, please manage this by creating an Account for Undeposited funds. On receipt of payment from customer, Debit this amount. When payment realized in the bank account, create Journal Entry to move funds from Undeposited funds to Bank Account.

**Comment by marekzada** [comment]
Hello, 

I believe this is a welcome feature and it is well described. Oracle Netsuite has such a feature and it would make all accountants/controllers very happy. A deduction/loss for credit card payment fees would make it perfect.
