### ISSUE TITLE
Add button on item dashboard bypasses workflow

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#20827]
![image](https://user-images.githubusercontent.com/1822868/75860306-a6d7cb00-5e0c-11ea-8b34-d450f2e739a1.png)

The above button allow stock entries that bypass the workflow to be created.

**Comment by ankush** [comment]
I think this should just create a draft entry by default and user should submit it. 

Btw it's bypassing full workflow probably because you have rights to submit it?

**Comment by muchai** [comment]
> Btw it's bypassing full workflow probably because you have rights to submit it?
Will test this. Albeit, at the time this was being abused by a stock user. Who would add inventory, just to get a sales process/delivery note to go through.
We used client script/jquery to disable it.
