### ISSUE TITLE
Cannot Filter Purchase Invoice with Status ‘Temporarily on Hold’ in List View

### ISSUE THREAD

**Issue by lokesh-indictrans** [frappe/erpnext#20822]
On purchase invoice list view, When we try to filter purchase invoice with status 'Temporarily on Hold’,  this status is not available to filter. 

![status_error](https://user-images.githubusercontent.com/59611773/75848637-b9500580-5e08-11ea-8834-94dc1b66781c.png)

**Comment by jayfiro** [comment]
[Link to discussion post ](https://discuss.erpnext.com/t/cannot-filter-purchase-invoice-with-status-temporarily-on-hold-in-list-view/58614) for additional information.

**Comment by deepeshgarg007** [comment]
<img width="585" alt="image" src="https://user-images.githubusercontent.com/42651287/197562873-5c269e67-357d-4df2-b27d-b26852d6ab69.png">

This is the condition that is used to show this status, you can apply the same in filters and get the results
