### ISSUE TITLE
Nameerror: name 'frappe' is not defined (in Workflow - in V12.5.2)

### ISSUE THREAD

**Issue by alkuhlani** [frappe/erpnext#20831]
Dear Developers,

I can not use "frappe" keyword in the condition field in WorkFlow,
for example (frappe.session.user==doc.owner) 
I face this error ("nameerror: name 'frappe' is not defined")
it had worked fine in the last versions

Therefore, your solution or feedback is highly appreciated. 

Thank you in advance.

**Comment by clarkejj** [comment]
More notes found here https://discuss.erpnext.com/t/nameerror-name-frappe-is-not-defined-in-workflow-in-v12-5-2/58779/5

**Comment by amutaher** [comment]
Same issue, any progress in this issue?

**Comment by alkuhlani** [comment]
@deepeshgarg007 
Firstly, I'm so sorry about the mention, I understand the policies of mentions of the discussion forum and Github.
secondly, regarding this issue, it still happens in the latest version 
ERPNext: v12.6.0 (version-12)
Frappe Framework: v12.4.1 (version-12)
Has "frappe" been changed or the syntax!

I've really appreciated your support and all the team.

**Comment by alkuhlani** [comment]
Sorry, I think it was a user mistake because I tried another time and it works correctly.

**Comment by darthguru** [comment]
Please could you tell us how you resolved this issue?

**Comment by alkuhlani** [comment]
Sorry, it still happens.

**Comment by alkuhlani** [comment]
> Please could you tell us how you resolved this issue?

Sorry, it still happens.

**Comment by alkuhlani** [comment]
https://github.com/frappe/frappe/pull/9773
https://github.com/frappe/frappe/commit/71570182b82349bd767252f0eac7d11548226465
