### ISSUE TITLE
Asset Maintenance Issue

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#20830]
Hi ,

It appears that the Asset Maintenance Task child table in ERPNext is somehow configured to use the Maintenance Task field as primary key! This then causes an error "Duplicate name Asset Maintenance Task xxxxxxxx" whenever the same maintenance task is used in another Asset Maintenance form. This of course is a major issue because several maintenance tasks are common across several Assets (e.g. Cleaning)

Pls help fix asap

Thanks

**Comment by clarkejj** [comment]
https://discuss.erpnext.com/t/issue-with-asset-maintenance/58777

**Comment by deepeshgarg007** [comment]
@Olawale1 if the issue still persists in the latest version 13 release please reopen a new issue, closing this issue
