### ISSUE TITLE
Adding some Fields in Salary Slip

### ISSUE THREAD

**Issue by alkuhlani** [frappe/erpnext#20832]
**Dear Developers,

First of all, I appreciate your work, ERPNext is the best product for us.
Secondly, I have some humble proposals, which I hope will be taken into consideration in the future**
Add these fields to the salary slip (which are founded in the monthly attendance sheet)
1. Total Present
2. Total Absent
3. Total Late Entries
4. Total Early Exits
5. Total Leaves
6. Leave Without Pay (Already Exist)

**Comment by zuron7** [comment]
If you're looking to just print some existing field, then you can customize the DocType to show the data from the other Doc, right?

**Comment by amutaher** [comment]
We need this feature to calculate total of absent and late for the employee and use it in salary formula to deduct it from salary.

**Comment by alkuhlani** [comment]
> If you're looking to just print some existing field, then you can customize the DocType to show the data from the other Doc, right?

Thank you for your replay, actually, we want these fields to use them in the formula.
I did that by editing the python file, but it's not useful for updating.

**Comment by alkuhlani** [comment]
> We need this feature to calculate total of absent and late for the employee and use it in salary formula to deduct it from salary.

Thank you @AkramMutaher, exactly it same my purpose.

**Comment by Ponyooooo** [comment]
Please also add:
7. Total Overtime

**Comment by alkuhlani** [comment]
@Ponyooooo, Yes it will be great.

**Comment by Anurag810** [comment]
https://github.com/frappe/erpnext/pull/20145
