### ISSUE TITLE
Exchange Rate Revaluation does not consider posting_date selected

### ISSUE THREAD

**Issue by aakvatech** [frappe/erpnext#20840]
## Description of the issue
Exchange Rate Revaluation does not consider posting_date selected. It gets all transactions even of those beyond posting_date.

## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 12.4.2
frappe 12.3.0
```

## Steps to reproduce the issue
Ensure that you have transactions of previous months in a separate currency whereby the exchange rates are different for each currency
1. Create new Exchange Rate Revaluation
2. Select posting date of past 1 month
3. Get the transactions

### Observed result
You will notice that the account codes have balances that do not match that of the Balance sheet because the query brings in all data.

### Expected result
Older transactions should be ignored as the revaluation is for a prior period.

### Stacktrace / full error message
```
Not applicable. It is not an error, but a wrong calculation.
```

## Additional information
      account_details = frappe.db.sql("""
        select
          account, party_type, party, account_currency,
          sum(debit_in_account_currency) - sum(credit_in_account_currency) as balance_in_account_currency,
          sum(debit) - sum(credit) as balance
        from `tabGL Entry`
        where account in (%s) 
        group by account, IFNULL(party_type, ''), IFNULL(party, '')
        having sum(debit) != sum(credit)
        order by account
      """ % ', '.join(['%s']*len(accounts)), tuple(accounts), as_dict=1)

The above excerpt of the code is missing posting_date filter and therefore gets all transactions

OS version / distribution, `ERPNext` install method, etc.
Ubuntu 16.04.5 LTS
Easy Install

**Comment by chanyork** [comment]
Has this been fix?  I try to do a exchange rate revaluation.  It does not seem to be ending correctly.
