### ISSUE TITLE
ERPNext v12 Timesheet Wrongly Computes Hours Worked

### ISSUE THREAD

**Issue by ghost** [frappe/erpnext#20848]
We are trying out ERPNext for a prospect (ERPNext Hosted). We are having an issue with the Project module Timesheet. We realized hours computed are inaccurate.

I entered the time from **8am to 5pm** same day (1st March). This should be 9 hours, but system computes 3 hours.

![Untitled](https://user-images.githubusercontent.com/35927555/75971490-25e30700-5ed2-11ea-970b-dcd2f9b77b0f.png)

**Comment by barredterra** [comment]
Can confirm, same problem for me.
Also any manual correction gets overwritten immediately.

### Versions
ERPNext: v12.6.0 (version-12)
Frappe Framework: v12.4.1 (version-12)

**Comment by barredterra** [comment]
Related: #16900
