### ISSUE TITLE
Employee Data Import

### ISSUE THREAD

**Issue by shivrajvibuthi** [frappe/erpnext#20856]
Hi,

Module: Data Import
Master: Employee
Issue: Date of Birth and Date of Joining - DD/MM/YYYY behaving inconsistently while doing data import from employee data template.
date of birth it takes, dd/mm/yyyy. with the same format, for date of joining it converts the given dd/mm/yyyy data into mm/dd/yyyy form

**Comment by kennethsequeira** [comment]
Closing as this is fixed in later v13 beta releases.
