### ISSUE TITLE
Barcode camera button missing on Stock Entry

### ISSUE THREAD

**Issue by Moorst** [frappe/erpnext#20850]
## Description

The camera button is missing for the barcode fields i some views. This happens both on the apps and web view.

## Steps to reproduce the issue

1. Go to Stock Entry
2. See barcode field
3. Camera button is missing

### Observed result

![Screenshot_20200305-100734](https://user-images.githubusercontent.com/6151408/75975315-30040600-5ed0-11ea-8f47-e33174032700.png)

### Expected result

![Screenshot_20200305-100748](https://user-images.githubusercontent.com/6151408/75975447-70fc1a80-5ed0-11ea-8bd7-898fd05e25f7.png)

## Additional information

Screenshots from Android app v0.0.14

**Comment by jma4227** [comment]
From my knowledge this feature hasn’t worked ever on iOS.. maybe it’s something I’m not doing to activate ?

**Comment by jma4227** [comment]
has someone figured this out?

**Comment by dr-data** [comment]
iOS doesn't work too.

![IMG_9427](https://user-images.githubusercontent.com/9060623/78704515-88e71400-793e-11ea-8118-467d81d5f143.jpg)

**Comment by dr-data** [comment]
Is it related to the domain without SSL?

**Comment by ankush** [comment]
works fine with v13 / v14

<img width="390" alt="Screenshot 2022-03-28 at 2 02 22 PM" src="https://user-images.githubusercontent.com/9079960/160358614-9f6bf85a-cca8-4848-8abb-8a491e3ea547.png">


related fix: https://github.com/frappe/frappe/pull/15309
