### ISSUE TITLE
Trouble with auto-fetching time sheets in Project

### ISSUE THREAD

**Issue by wojosc** [frappe/erpnext#20863]
We use Projects to collect all work done with a customer and like to link every thing used for the project to the projekt. This also includes Sales Orders and Purchase Orders. A problem we have is, that we are not able to bill say additional hardware as is without pulling open time sheets from the project. I'm sure others have this problem also.

We have a fix developed for our system. I think this should also go into core.
https://github.com/tueit/it_management/issues/75#issuecomment-595697948

Futher we will be adding a "Get Items from" button with which I can pull Time Sheets from any Issue, Task or Project when needed.

**Comment by deepeshgarg007** [comment]
@wojosc The link you have mentioned is not visible to us, plus I think this issue is resolved, please reopen if it still persists

**Comment by wojosc** [comment]
> @wojosc The link you have mentioned is not visible to us, plus I think this issue is resolved, please reopen if it still persists

here is the fixed link: https://github.com/phamos-eu/it_management/issues/75#issuecomment-595697948
