### ISSUE TITLE
GL no longer shows company currency for foreign currency parties

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#20869]
Hi ,

The GL report no longer shows entries in company currency alongside party currency (when dealing with foreign currency customer/supplier). What’s the reason for this? It was a very helpful feature when doing analysis

Please help fix

Kind regards,

**Comment by clarkejj** [comment]
https://discuss.erpnext.com/t/gl-no-longer-shows-company-currency-for-parties-using-foreign-currency/58842

**Comment by dalers** [comment]
Hi John, what conclusion might I draw from this?Cheers, DaleOn Mar 15, 2020 8:20 PM, John Clarke <notifications@github.com> wrote:
https://discuss.erpnext.com/t/gl-no-longer-shows-company-currency-for-parties-using-foreign-currency/58842

**Comment by clarkejj** [comment]
That's the question Dale!

**Comment by deepeshgarg007** [comment]
@Olawale1 Can you please explain the issue more in detail and reopen it, I am not able to fully understand the issue.
