### ISSUE TITLE
Report Permission

### ISSUE THREAD

**Issue by Green-Iraq** [frappe/erpnext#20883]
Dear Sir,
I have faced problems while trying to set permission to this user (haiergreenhalabja@gmail.com) certain reports, but I couldn't . I have attached the file below.
Thanks

![Annotation 2020-03-09 152255](https://user-images.githubusercontent.com/46241695/76212598-e857e400-6219-11ea-8aaf-9d7afa4270d9.png)

**Comment by kennethsequeira** [comment]
Kindly elaborate your query and post on the forum: https://discuss.erpnext.com

If you want to set permissions on standard reports, you have to do it role-wise: https://docs.erpnext.com/docs/user/manual/en/setting-up/users-and-permissions/role-permission-for-page-and-report
