### ISSUE TITLE
Add stripe as a payment gateway that can be used for checkout in the shopping-cart module.

### ISSUE THREAD

**Issue by jevonearth** [frappe/erpnext#2088]
Stripe API documentation is available here: https://stripe.com/docs/api

We would like to use stripe as a payment gateway for checkout orders in the shopping-cart module.

**Comment by abhijeetramgir** [comment]
How do we do this?

thanks

**Comment by umairsy** [comment]
Stripe Payment gateway added in ERPNext version 8.
