### ISSUE TITLE
Reserved qty for production not calculated right way

### ISSUE THREAD

**Issue by shieldone** [frappe/erpnext#20882]
## Description of the issue
Based on topic
https://discuss.erpnext.com/t/possible-bug-reserved-qty-for-production/57017

In work order when is checked Skip Material Transfer checkbox, “reserved_qty_for_production” in BIN doctype is not updated after Stock Entry is submitted ( Purpose - Manufacture ). But i thing that it should. Because items consumed in manufacturing are not reserved anymore.

I found that, “reserved_qty_for_production” in BIN doctype is calculated from Work Order Items like:

`sum(item.required_qty - item.transfered_qty)`

But i thing that it should be calculated

`sum(item.required_qty - item.consumed_qty)`

## Steps to reproduce the issue

1. Create Work order and check  "reserved_qty_for_production"
2. Click finish and manufacture some of them
3. Create Stock entry and submit it

ERPNext: v11.1.68 (version-11)
Frappe Framework: v11.1.62 (version-11)

**Comment by deepeshgarg007** [comment]
@janecekmato if this issue still persists in the latest version-13 or higher versions please reopen a new issue, closing this issue
