### ISSUE TITLE
Scan Serial Numbers to increase quantity

### ISSUE THREAD

**Issue by dexterhussain** [frappe/erpnext#20880]
While Making Sale Invoice, If an inventory is serialized, if we scan the serial code of item it opens a box in which you need to add serial number separately but in POS profile only scanning serial id increases quantity, Such feature should be added to sale inovice , delivery note as well to make process faster.

**Comment by dexterhussain** [comment]
I can develop it as well and commit back to erp core if someone can guide me a bit

**Comment by szufisher** [comment]
on my v11 system scan serial no in sales invoice form does added the serial no, but only works for 1 serial number only, scan the serial number multi times will overwrite the existing serial number instead of adding as a new line.
the code is in erpnext.public.js.controllers.transaction.js, 
scan_barcode: function() {
		let scan_barcode_field = this.frm.fields_dict["scan_barcode"];

		let show_description = function(idx, exist = null) {
			if (exist) {
				scan_barcode_field.set_new_description(__('Row #{0}: Qty increased by 1', [idx]));
			} else {
				scan_barcode_field.set_new_description(__('Row #{0}: Item added', [idx]));
			}
		}

		if(this.frm.doc.scan_barcode) {
			frappe.call({
				method: "erpnext.selling.page.point_of_sale.point_of_sale.search_serial_or_batch_or_barcode_number",
				args: { search_value: this.frm.doc.scan_barcode }
			}).then(r => {
				const data = r && r.message;
				if (!data || Object.keys(data).length === 0) {
					scan_barcode_field.set_new_description(__('Cannot find Item with this barcode'));
					return;
				}

				let cur_grid = this.frm.fields_dict.items.grid;

				let row_to_modify = null;
				const existing_item_row = this.frm.doc.items.find(d => d.item_code === data.item_code);
				const blank_item_row = this.frm.doc.items.find(d => !d.item_code);

				if (existing_item_row) {
					row_to_modify = existing_item_row;
				} else if (blank_item_row) {
					row_to_modify = blank_item_row;
				}

				if (!row_to_modify) {
					// add new row
					row_to_modify = frappe.model.add_child(this.frm.doc, cur_grid.doctype, 'items');
				}

				show_description(row_to_modify.idx, row_to_modify.item_code);

				this.frm.from_barcode = true;
				frappe.model.set_value(row_to_modify.doctype, row_to_modify.name, {
					item_code: data.item_code,
					qty: (row_to_modify.qty || 0) + 1
				});

				['serial_no', 'batch_no', 'barcode'].forEach(field => {
					if (data[field] && frappe.meta.has_field(row_to_modify.doctype, field)) {
						frappe.model.set_value(row_to_modify.doctype,
							row_to_modify.name, field, data[field]);
					}
				});

				scan_barcode_field.set_value('');
			});
		}
		return false;
	},

**Comment by szufisher** [comment]
this is my updated version
	scan_barcode: function() {
		let scan_barcode_field = this.frm.fields_dict["scan_barcode"];

		let show_description = function(idx, exist = null) {
			if (exist) {
				scan_barcode_field.set_new_description(__('Row #{0}: Qty increased by 1', [idx]));
			} else {
				scan_barcode_field.set_new_description(__('Row #{0}: Item added', [idx]));
			}
		}

		if(this.frm.doc.scan_barcode) {
			frappe.call({
				method: "erpnext.selling.page.point_of_sale.point_of_sale.search_serial_or_batch_or_barcode_number",
				async: false,
				args: { search_value: this.frm.doc.scan_barcode }
			}).then(r => {
				const data = r && r.message;
				if (!data || Object.keys(data).length === 0) {
					scan_barcode_field.set_new_description(__('Cannot find Item with this barcode'));
					return;
				}

				let cur_grid = this.frm.fields_dict.items.grid;

				let row_to_modify = null;
				const existing_item_row = this.frm.doc.items.find(d => d.item_code === data.item_code);
				const blank_item_row = this.frm.doc.items.find(d => !d.item_code);

				if (existing_item_row) {
					row_to_modify = existing_item_row;
				} else if (blank_item_row) {
					row_to_modify = blank_item_row;
				}

				if (!row_to_modify) {
					// add new row
					row_to_modify = frappe.model.add_child(this.frm.doc, cur_grid.doctype, 'items');
				}

				show_description(row_to_modify.idx, row_to_modify.item_code);

				this.frm.from_barcode = true;
				frappe.model.set_value(row_to_modify.doctype, row_to_modify.name, {
					item_code: data.item_code,
					qty: (row_to_modify.qty || 0) + 1
				});

				['serial_no', 'batch_no', 'barcode'].forEach(field => {
					if (data[field] && frappe.meta.has_field(row_to_modify.doctype, field)) {
						var new_value = (field === 'serial_no' && row_to_modify.serial_no)? row_to_modify.serial_no + "\n" + data[field] : data[field]				
						frappe.model.set_value(row_to_modify.doctype,
							row_to_modify.name, field, new_value);						
					}
				});
				scan_barcode_field.set_value('');
			});
		}
		return false;
	},

changes made:
frappe.call added this parameter
async: false,

special handling of the serial number field
var new_value = (field === 'serial_no' && row_to_modify.serial_no)? row_to_modify.serial_no + "\n" + data[field] : data[field]				
						frappe.model.set_value(row_to_modify.doctype,
							row_to_modify.name, field, new_value);

**Comment by dexterhussain** [comment]
and what if i want to use the same in stock reconsilation module?

**Comment by szfisher** [comment]
by adding scan_barcode field into stock reconciliation doctype, this feature will be auto activated.

**Comment by dexterhussain** [comment]
can you guide me how i can add ? as it is not being added I tried.

**Comment by dexterhussain** [comment]
The issue is just field comes over the table when i scan the barcode the below table doesnt gets any affect

**Comment by jma4227** [comment]
I’m trying to add serial to assets... I’ve figured out how to override the JS in item master so that items that are assets can have serial no. I’m able to add serial numbers to purchase receipts of a fixed asset but unable to link serial no & item asset to auto populate
