### ISSUE TITLE
Accounting Dimensions required in Salary Structure Assignment

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#20896]
Hi ,

Currently, the only way to specify Accounting Dimensions in Payroll is to do it in the Payroll Entry. The issue with this is that the user is forced to create several Payroll Entries when multiple Accounting Dimensions are required. A very common use case is when the organization has multiple branches. Usually it is required to maintain a separate Cost Center for each branch. Currently, the user has to run a separate Payroll Entry for each branch which is quite cumbersome and unnecessary. Same applies when different Business Units or Departments have different Cost Centers

It is much more efficient if Accounting Dimensions can be specified in the Salary Structure Assignment for each Employee. This way, the Payroll can be run once and report to the relevant Accounting Dimensions

Please help look into this

Thanks

**Comment by aakvatech** [comment]
I agree with this requirement.

Essentially it should be defined at salary structure as default. It could also be overridden using default defined at Department Level and Employee level.
It should be brought into Salary Slip during generation.
The accrual JV creation should group the Salary Slips accordingly.

We can help put effort to get the changes done, if there is enough interest.
