### ISSUE TITLE
commit v11 to v11-pre-release

### ISSUE THREAD

**Issue by RJPvT** [frappe/erpnext#20897]
In v11-pre-releasea bug was solved with tasks expireing while in review pending 20 days ago. However this is not comitted to v11 stable

Is it possible to make the commit from v11 pre release to v11 so manual correction is no longer nessecary ?

**Comment by RJPvT** [comment]
@rmehta sorry to tag you directly but i know you have notifications off. Any idea when we can have v11-hotfix implemented in v11 master ? Thanks again!

**Comment by Thunderbottom** [comment]
hey, version-11-hotfix will be merged into version-11 during the next release; which should be in and around a couple of days from now. hope you can wait until then :)
