### ISSUE TITLE
Woocommerce integration fetches wrong company information

### ISSUE THREAD

**Issue by c0db1nar10** [frappe/erpnext#20892]
##Description of the issue
While obtaining a Woocommerce order from the woocommerce site, ERPNEXT starts creating a Sales Order, but it tries to fetch the field Company from the Billing data of Customer as an existing Company on the ERPNEXT instance.

Here's the output from Error Log:

![Screen Shot 2020-03-09 at 11 21 28 AM](https://user-images.githubusercontent.com/51799415/76246449-f8140000-61fa-11ea-82b4-ef41677bf771.png)

## My 2 cents:

I dont think it should behave this way.

Company should be either the default company (as defined on Settings > Global Defaults on ERPNEXT) or we should add a company link field on the Woocommerce Settings form.

Let me know if this is helps and thanks a lot for developing and supporting a wonderful product.

## Additional information
This is related to https://github.com/frappe/erpnext/pull/19487

Installed Apps
ERPNext: v12.0.5 (version-12)
Frappe Framework: v12.3.0 (version-12)

**Comment by tecnofoodmx** [comment]
We have the same issue

**Comment by ruchamahabal** [comment]
This issue was fixed in the PR #19487 by adding a Company field in WooCommerce Settings. The code does not fetch the Company from order data now.
