### ISSUE TITLE
i want to freeze bank acc how can i set role for it

### ISSUE THREAD

**Issue by pornchalat** [frappe/erpnext#20909]
![image](https://user-images.githubusercontent.com/35266090/76444217-33c6e980-63f6-11ea-93d1-723727982440.png)

**Comment by kennethsequeira** [comment]
https://docs.erpnext.com/docs/user/manual/en/accounts/articles/freeze-account

Set the role under Accounts Settings and assign the role to the user that needs to freeze the account:

![image](https://user-images.githubusercontent.com/33246109/78171985-eb3da180-7472-11ea-890e-8a2ed45bb89f.png)
