### ISSUE TITLE
Cannot complete quiz in ERPNext LMS

### ISSUE THREAD

**Issue by jvfiel** [frappe/erpnext#20908]
more details in https://discuss.erpnext.com/t/quiz-on-lms-impossible-to-complete-cannot-read-property-is-complete-of-null/51707/4

**Comment by jvfiel** [comment]
I think I found the issue

https://github.com/frappe/erpnext/blob/version-12/erpnext/education/utils.py

no "activity" being returned.

**Comment by jvfiel** [comment]
def has_super_access():
	"""Check if user has a role that allows full access to LMS
	Returns:
		bool: true if user has access to all lms content
	"""
	current_user = frappe.get_doc('User', frappe.session.user)
	roles = set([role.role for role in current_user.roles])
	return bool(roles & {'Administrator', 'Instructor', 'Education Manager', 'System Manager', 'Academic User'})

**Comment by scmmishra** [comment]
Hi @jvfiel I've fixed the issue, I'm closing the issue
