### ISSUE TITLE
”Delivery Note“ incorrectly displayed as “To Bill" after changing ”Sales Invoice“

### ISSUE THREAD

**Issue by zhangminghao1989** [frappe/erpnext#20938]
## Description of the issue
”Delivery Note“ incorrectly displayed as “To Bill" after changing ”Sales Invoice“
## Context information (for bug reports)

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1.Create ”Delivery Note“ and submit.
2.Create ”Sales Invoice“ with ”Delivery Note“ and submit.
3.Cancel "Sales Invoice", revision and submit.

### Observed result
"Delivery Note" incorrectly displayed as "To Bill",and these items are displayed in the ”Get Items from“ function of ”Sales Invoice“.
### Expected result
"Delivery Note" displayed as "Completed",and these items are not displayed in the ”Get Items from“ function of ”Sales Invoice“.
### Stacktrace / full error message
I think this problem also exists in "Sales Order", "Purchase Order", "Purchase Receipt".
```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.
Debian 10
ERPNext: v12.2.2 (version-12)
Frappe Framework: v12.0.20 (version-12)

**Comment by zuron7** [comment]
Would you be able to test if this bug is there on the latest version of ERPNext also?

**Comment by zhangminghao1989** [comment]
ERPNext: v12.6.0 (version-12)
“Delivery Note" displayed as "Completed", **but**  these items are still displayed in the ”Get Items from“ function of ”Sales Invoice“, Even if it is useless to modify Delivery Note.

**Comment by zhangminghao1989** [comment]
> Would you be able to test if this bug is there on the latest version of ERPNext also?


I found the cause of the problem.This problem occurs when the item rate of "Delivery Note" or "Purchase Receipt" is 0.
