### ISSUE TITLE
(Is default check box) in user permission not work with accounting dimension created fields

### ISSUE THREAD

**Issue by dufani1** [frappe/erpnext#20951]
Hello,
We noted that the Is default check box in user permission not work with accounting dimension created fields?
When we set user permission for location and we checked Is Default the default value not set up automatically in Forms (like Sales Invoice and Purchase Invoice ).

Regards,

**Comment by deepeshgarg007** [comment]
<img width="1343" alt="image" src="https://user-images.githubusercontent.com/42651287/204560053-2ee0788a-3247-4d8b-aa72-9818f0f9ded7.png">

Just checked and working fine as expected for the Sales Invoice form. Closing this issue
