### ISSUE TITLE
Number of Depreciations Booked Field in Asset DocType Does not Support Float Value

### ISSUE THREAD

**Issue by alkuhlani** [frappe/erpnext#20952]
Dear Super Developers,

The Number of Depreciations Booked field does not support float value,
we need this to be a Float, because some asset the Opening Accumulated Depreciation is for not a completed year,

I tried to solve the issue with these steps:
```
1. Change the Opening Accumulated Depreciation type to Float instead of Int
2. Delete the "cint()" of "self.number_of_depreciations_booked" in below code
```
https://github.com/frappe/erpnext/blob/c06ba54f1e394e6074b04dd8468609ae237a2aaf/erpnext/assets/doctype/asset/asset.py#L367

Here an example:
[**The Issue**](https://drive.google.com/open?id=1FtmMcmnYLb8Wkvk_5f8FnGLnkp5vzm77): https://drive.google.com/open?id=1FtmMcmnYLb8Wkvk_5f8FnGLnkp5vzm77
[**After the solution**](https://drive.google.com/open?id=1QQv1bG8wTIj-1HggrDKW_8TE1Fun1iCU): https://drive.google.com/open?id=1QQv1bG8wTIj-1HggrDKW_8TE1Fun1iCU

Thank you in advance.

**Comment by deepeshgarg007** [comment]
@alkuhlani  if this issue still persists in the latest version-13 or higher versions please reopen a new issue, closing this issue
