### ISSUE TITLE
Currency Conversion not recalculating line Items

### ISSUE THREAD

**Issue by creamdory** [frappe/erpnext#20960]
## Description of the issue

We have the `Currency and Price List` section in transaction Doctypes like `Quotation`. It allows user to change currency as he please. When a document is already saved and user change the currency into something else while the document is Draft, it does not recalculate the line and instead set it to zero. See below from Demo site. It should recalculate the line item based on the conversion.

![currency conversion](https://user-images.githubusercontent.com/21003054/76812171-07b0cb80-682f-11ea-9acd-80217b6e3db1.gif)

## Context information (for bug reports)

`Demo Site`
**Output of `bench version`**
```
Installed Apps
ERPNext: v12.x.x-develop () (develop)
Frappe Framework: v12.x.x-develop () (develop)
```

## Steps to reproduce the issue

1. Create Quotation, add line item, set price using the company currency and save.
2. Change `Currency` to another (ex. from USD to EUR)
3. It sets the rate to zero instead of recalculating base on the `Exchange Rate`

### Observed result
It sets the rate to zero.
### Expected result
It should re-calculate the rate and amount base on the `Exchange Rate`
### Stacktrace / full error message

```
N/A
```

## Additional information

Demo Site.

**Comment by deepeshgarg007** [comment]
@creamdory  if this issue still persists in the latest version-13 or higher versions please reopen a new issue, closing this issue
