### ISSUE TITLE
Payment URL css issue

### ISSUE THREAD

**Issue by jvantslot** [frappe/erpnext#20988]
The payment URL looks great when viewed on a computer screen, however when viewed from a mobile device, it has some obvious css issues.

See discuss topic for details

https://discuss.erpnext.com/t/payment-url-issue/59299

**Comment by samjaninf** [comment]
I'm having the same issues in version 13.

**Comment by deepeshgarg007** [comment]
@jvantslot Please test this on latest version-13 or higher releases and reopen the issue if it still persists
