### ISSUE TITLE
We need to enter fractions of a cent USD for prices

### ISSUE THREAD

**Issue by coreyspitzer** [frappe/erpnext#21008]
For example, one part that we order from https://www.digikey.com/ is $0.89404 USD so when we order 1,000 units the price comes out to $894.04.  But in ERPNext we only have the option to list the unit price as $0.89 or $0.90 which makes the total $890.00 or $900.00.

I tried editing the currency settings for USD to allow this, but without luck.

Please help.

**Comment by parsimonyERP** [comment]
First, these questions are answered more quickly and easily at https://discuss.erpnext.com.  (There are just way more users there!)
But I am wondering if you have looked at Settings > Global Defaults. You might look at "Disable Rounded Total"

**Comment by coreyspitzer** [comment]
Thanks for the tip!  The "Disable Rounded Total" option didn't seem to solve the problem, but I'll check out discuss.erpnext.com.

**Comment by marination** [comment]
@rifflabs https://docs.erpnext.com/docs/user/manual/en/customize-erpnext/articles/set-precision this should be helpful. You can set Precision as per your needs.
