### ISSUE TITLE
Deductions based on GrossPay V12 and V13

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#21033]
I have this formula in payroll. 

![image](https://user-images.githubusercontent.com/1822868/77348966-5f799600-6d4b-11ea-816f-782b55109fe8.png)
![image](https://user-images.githubusercontent.com/1822868/77349037-77e9b080-6d4b-11ea-9d81-6607be0539df.png)

The figures do not get calculated anymore, after the latest update (Release v12.6.0)

I suspect this changes (https://github.com/frappe/erpnext/pull/20935) are the cause.

**Comment by muchai** [comment]
Was this the intended purpose of https://github.com/frappe/erpnext/pull/20935?

**Comment by Anurag810** [comment]
your issue is fixed.
https://github.com/frappe/erpnext/pull/20935

use ```gross_pay``` in the formula that .

**Comment by muchai** [comment]
Mind clarifying a bit. The current Abbreviation for Gross Pay is G, should I change this to Gross_Pay, and update formulas using G, to use Gross_Pay?

**Comment by Anurag810** [comment]
No, you don't need to create it separately as **our system calculates gross pay automatically.**
which is stored in a global variable gross_pay, **no need to write abbreviation for it**. you can directly use **gross_pay** variable (in lowercase) **instead of G in formula and condition**

**Comment by muchai** [comment]
I see. Thank you.

**Comment by muchai** [comment]
This solution works. Thank you.
