### ISSUE TITLE
Unable to access Appointment Analytics

### ISSUE THREAD

**Issue by asharamseervi** [frappe/erpnext#21043]
## Description of the issue
In healthcare module, Appointment Analytics is unable to access and producing an error in console, i.e.
`console.trace() TypeError: "erpnext.AppointmentAnalytics is not a constructor"`
`TypeError: frappe.views.TreeGridReport is undefined`

## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 12.6.0
frappe 12.4.1
```

## Steps to reproduce the issue

1. Enable healthcare domain, In Consultation section and click "Appointment Analytics". Nothing will happen, sometimes redirects to blank page.
2. If you notice in console, you'll above mentioned 2 errors.
3. Here, are the screenshot for reference. 
![healthcare-appointment-analytics](https://user-images.githubusercontent.com/5942572/77417414-56400600-6deb-11ea-898f-31e36190bc20.png)

### Stacktrace / full error message

```
TypeError: frappe.views.TreeGridReport is undefined
desk:11:1
    <anonymous> desk:11
    eval dom.js:33
    init pageview.js:46
    show pageview.js:7
    with_page query_string.js:23
    show query_string.js:71
    with_doctype model.js:108
    show query_string.js:65
    route router.js:65
    startup desk.js:12
    init sort_selector.js:190
    start_app sort_selector.js:171
    Rollup sort_selector.js:190
    jQuery 4
TypeError: erpnext.AppointmentAnalytics is not a constructordesk:7:2
    on_page_load desk:7
    trigger_page_event pageview.js:64
    init pageview.js:52
    show pageview.js:7
    with_page query_string.js:23
    show query_string.js:71
    with_doctype model.js:108
    show query_string.js:65
    route router.js:65
    startup desk.js:12
    init sort_selector.js:190
    start_app sort_selector.js:171
    Rollup sort_selector.js:190
    jQuery 4
```

## Additional information

Ubuntu 18.04.4

**Comment by ruchamahabal** [comment]
This was a TreeGrid Report. TreeGrid Reports are deprecated. Hence a new script report has been created for the same in https://github.com/frappe/erpnext/pull/20811

**Comment by asharamseervi** [comment]
Thanks. Closing this.
