### ISSUE TITLE
Stock Update

### ISSUE THREAD

**Issue by FIROZE-ELEGANCE** [frappe/erpnext#2105]
A feature that -When receiving and dispatching an Item (assembling item) with BOM, for the BOM Unit and the Material/parts quantity to be updated accordingly.
Eg. A table with BOM parts 
                                           1. Top, 
                                           2. table Legs (pair) 
                                           3. Drawers
When Receiving 3 tables, the system updates 3 tops, 3 pairs of table legs and 3 drawers
When dispatching 2 tables, the system gives a parking list of 2 tops, 2 pairs of table legs and 2 drawers and
updates the table quantity to 1 table and the parts to 1 top, a pair of table legs and a drawer.
At any time for the system to be able to show the Quantity of the Complete Units(Table) in the warehouse and to be able to check the quantity of the parts( top,table legs& drawers) too.

**Comment by umairsy** [comment]
Please check report Available Stock for Packing Items in Selling module.
