### ISSUE TITLE
I cant see sidebar on my website built on ERPNEXT on mobile browser

### ISSUE THREAD

**Issue by abhinav666** [frappe/erpnext#21086]
## Description of the issue
I cant see sidebar on my website built on ERPNEXT on mobile browser, although it shows fine on desktop

## Context information (for bug reports)

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1.
2.
3.

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by kennethsequeira** [comment]
Please post this on the [community forum ](https://discuss.erpnext.com)with screenshots and what changes were done/how the website was created. This seems more customization related question.
