### ISSUE TITLE
Please help on using Coupon Codes..

### ISSUE THREAD

**Issue by abhinav666** [frappe/erpnext#21120]
## Description of the issue
I am in the middle of making my website and I am stuck while using the coupon codes for provision of discount to customers who shop online through the website.

I have linked the coupon code "SAVE10" to a pricing rule "Code10", where Coupon case based discount is checked. 

After using the coupon code, it shows the column for Discount but there is no discount. The price remains the same and the discount shown is 0, although Discount Percentage is selected at 10%.

I hope I am doing something wrong, please revert with the resolution.

Rgds
Abhinav

## Context information (for bug reports)

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1.
2.
3.

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by clarkejj** [comment]
These two please post to discuss https://github.com/frappe/erpnext/issues/21086

**Comment by deepeshgarg007** [comment]
@abhinav666 If the issue still persists in the latest version-13 or higher releases please reopen a new issue
