### ISSUE TITLE
Improve Reporting by Batch

### ISSUE THREAD

**Issue by RealDesignGraphics** [frappe/erpnext#2113]
I love that you allow us to add a batch number to products and follow them through the system.  However, it is very difficult to start from a batch number and get any information about it utilization. 

I would really like to be able to pull the current amount left in any batch from the batch list screen... it is really fundamental knowledge.  I realize I can do a batch-wise inventory so the information is available, but it doesn't satisfy the need to just be able to easily scan which batches still have product left in them and which ones are almost out (or out altogether!).

I would like to be able to select a batch and find out where it has been used.  This should be relatively easy as you make most of the information available through the "linked" to function. I just need a way to print that out to maintain paperwork and hopefully gather a little more info from the linked tables

I would also like to select a customer and find out which batches have been sent to them. again, the linked to info is very useful, but I guess I want one more layer deep ... it says that SO-XXX is linked to a customer, but what was on SO-XXX? I want to be able to pull a report that starts from a specific customer and lets me know: which sales-orders (really, which products, but I realize that is linked through the SO) what was on those sales orders and the batch numbers associated with those products.  The same report that follows delivery notes would be fabulous too (Customer>DN>Items (and batches) delivered)  
I am assuming that by the time I can get either of these reports, I can pull off extra info from the related tables like dates etc.

Let me know if you need further information

Corinne

**Comment by umairsy** [comment]
Create report using Report Builder to filter Batch ID based on Customer and vice-versa. Feel free to re-open is feature suggestion is still valid and needed.
