### ISSUE TITLE
Invoice Print format - Manufacturer name not appearing

### ISSUE THREAD

**Issue by kfcspl** [frappe/erpnext#21140]
## Description of the issue: In sales invoice we have Item name Description, HSN, MF(Manufacturer) etc 

Description | HSN | MF | Batch | Exp | Pack | Qty | MRP | Rate | GST% | Amount
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
 FEMARA 2.5mg Tabs | 30049099 |   | SMC97 | 12-23 | 1x10 | 6 | 980 | 358.68 | 12% | 2152.08

Earlier it was fetching  MF (Manufacturer details, now its not appearing, its mandatory for Pharma Drugs distributors after some of last updates this issue has arised.

Please advise or arrange solutions.

**Output of `bench version`**
```
(paste here)
```

**Comment by clarkejj** [comment]
Reported here https://discuss.erpnext.com/t/invoice-print-table-value-not-showing-or-captured-in-sales-invoice-and-in-print-format/59894

**Comment by kfcspl** [comment]
thanks we found solution it was manufacturer table name changed
