### ISSUE TITLE
Google Contact sync creates contact duplicates each time it runs

### ISSUE THREAD

**Issue by matteoscordino** [frappe/erpnext#21159]
## Description of the issue
Every time the Google Contact sync is ran, a new contact is created, whether it existed already or not.

e.g. if I have a contact John Smith, I will end up with John Smith-1, John Smith-2, John Smith-3...

With the sync happening periodically, we are now up to 15 duplicate for each contact.
The fact that there is no “find and merge duplicates” functionality makes removing them a painful manual process (it just can’t be done, it would be hundreds of contacts to remove)

## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 12.x.x-develop
frappe 12.x.x-develop
```

## Steps to reproduce the issue

1. configure contact sync following the Erpnext documentation
2. either execute the Google Contact sync manually, or let it be run as a scheduled job for a few days

### Observed result
you will find several duplicates of each contact in your contacts, each with a n increasing `-[0-9]+` suffix

### Expected result
contacts that already exists get left alone (or potentially updated), no new contact is created

### Stacktrace / full error message

```
N/A
```

## Additional information

Debian bullseye running ERPnext in the `pipech/erpnext-docker-debian:dev-py3-latest` Docker container

**Comment by clarkejj** [comment]
Thanks @matteoscordino https://discuss.erpnext.com/t/google-contacts-integration-duplicate-contacts/54628/4

**Comment by matteoscordino** [comment]
Any news on this?

**Comment by clarkejj** [comment]
No, no news it seems

**Comment by paulator** [comment]
This issue happens also on the most recent version:

```
ERPNext: v12.10.0 (version-12)
Frappe Framework: v12.7.1 (version-12)
```

**Comment by clarkejj** [comment]
You can watch this for prospective changes that fix the issue https://github.com/frappe/frappe/blob/develop/frappe/integrations/doctype/google_contacts/google_contacts.py

**Comment by nordurljosahvida** [comment]
Hi @clarkejj, this hasn't been pulled yet, right?

Thanks

**Comment by charleslcso** [comment]
Oh... I guess this is one of the long long standing issues that the Team doesn't bother to fix.

No updates, right?
