### ISSUE TITLE
Handheld UX & Workflows for common tasks

### ISSUE THREAD

**Issue by raveslave** [frappe/erpnext#2116]
For day to day tasks like receiving goods, doing stock transfers, quality control etc. we could really benefit from having simplified UI's that can be run on handheld terminals like cheap android phones or ipod touch equipped with a bar-code reader case.

These views & forms should be adapted for mobile-devices and be very limited in terms of permissions and actions they can do.

As the needs will be different depending on the organization, the most simple way to define and customize these could be using a pre-defined python-class that defines a sequence of steps required for the workflow, connects the models & functions needed along with the simplified form-view and validation wanted.  

If this could be designed directly in the web-admin, even nicer, but I see this as a future task once we have something that works by implementing it more as simple "extension scripts".

The level of simplicity should be like a Super Nintendo start screen, big input fields and button(s) + clear step-by-step progress.

The launch-screen on the handheld devices could have a "fast user switch" menu option, where the next step allows to choose one of the use-cases available for this user. Devices are prepped by an admin by register the device host-name. 

Example work-flow: 1) list of users -> click -> password. 2) list of workflows/actions available. 3) i.e. "Stock transfer": scan barcode -> finds product. Next screen, select: from warehouse, to warehouse, huge input-field (qty), submit -> done!

**Comment by umairsy** [comment]
Hope Quick Entry views has added simplification on this front.

**Comment by raveslave** [comment]
thx, where can I read/see more about  Quick Entry views ?

**Comment by umairsy** [comment]
![quick-entry](https://cloud.githubusercontent.com/assets/910238/25043912/076c0898-2141-11e7-85ab-f1d4eecdab45.gif)

**Comment by raveslave** [comment]
@umairsy ah, got it. 
My idea is more about an isolated UX, separate from the ERPNext Desktop
 - must work on mobile/tablets
 - must run isolated (think kiosk-mode / POS) 
    _so it can be installed on computers near the "incoming goods shelf" etc_
 - possible to break apart the forms into steps incl. instructions
    _i.e. receive goods ➞ huge field to scan tracking number ➞ big buttons to select warehouse ➞ done_
