### ISSUE TITLE
[bug] Can not submit purchase receipt if quality inspection is rejected.

### ISSUE THREAD

**Issue by szufisher** [frappe/erpnext#21212]
<Steps to reproduce the issue
create a new quality inspection template
create a new item and mark it as quality inspection required for purchase, assign a quality inspection template
create and submit a purchase order with the above item
create a new purchase receipt for the above purchase order
create a new quality inspection and assign the above purchase receipt, in child table row, select status rejected, save and submit
update the purchase receipt: change the accepted quantity as 0, rejected qty as the total received quantity, assign rejected warehouse, save and submit
Observed result
there is error message "quality inspection is rejected"

Expected result
purchase receipt can be submitted.
Stacktrace / full error message
(paste here)
Additional information
this applies to both v11 and v12, maybe also for development per the source code logic.

OS version / distribution, Frappe install method, etc.

**Comment by thomasoceguera** [comment]
I'm seeing the exact same issue on our system except that this is a live implementation.    Also seeing many questions regarding this same issue.   Hopefully we can start to see some answers from the dev team.   As always any help would be appreciated Guys!

**Comment by marination** [comment]
@thomasoceguera @szufisher https://github.com/frappe/erpnext/pull/26133
