### ISSUE TITLE
[Feature] Get items from Purchase Invoice, on Sales Invoice

### ISSUE THREAD

**Issue by racitup** [frappe/erpnext#21224]
**Problem**
When consulting for businesses, often you need to buy ad-hoc goods or services to deliver the service, and pass those goods directly to your customer. Often you may pass them on 'at cost'. They are essentially employee expenses but paid by a company credit card, for example hotel bills, and put directly onto a Sales Invoice.
So you need to create a Purchase Invoice, and then add those items directly to a Sales Invoice.
Often the Sales Invoice will already exist, created from a timesheet.

**Describe the solution you'd like**
On the Sales Invoice, there is an action menu `Get items from`. This needs another option: `Purchase Invoice`.
![Screen Shot 2020-04-10 at 00 16 09](https://user-images.githubusercontent.com/18157195/78948559-b52a9e00-7ac0-11ea-996c-85adc11ba6c0.png)

**Describe alternatives you've considered**
Manually creating the item lines again.
There should also be an option to import items from an `Expense Claim` to a Sales Invoice too, for when an employee has paid for the items personally.

**Additional context**
None

**Comment by marination** [comment]
@racitup I am not very clear with the hotel bills bit. Can't that be handled via expense claim ?

**Comment by racitup** [comment]
@marination I've updated the description a bit. Not when the expense is paid on a company credit card.

**Comment by nameduser0** [comment]
😄
