### ISSUE TITLE
Item None not found - on Opening Invoice Creation Tool when in a multi company environment-v12.6.0 (version-12)

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#21223]
![image](https://user-images.githubusercontent.com/1822868/78911692-513bb180-7a8f-11ea-94c9-e9cbf257aacd.png)

**Comment by muchai** [comment]
Works in a single company environment

**Comment by marination** [comment]
@muchai  A GIF perhaps would be more informative

**Comment by muchai** [comment]
> Works in a single company environment

Apologies, @marination just tested on another multi-company environment, and it works.

Below is the error though.

![image](https://user-images.githubusercontent.com/1822868/79122211-cfee6280-7d9f-11ea-97a8-436d0769de24.png)
