### ISSUE TITLE
[Feature Request] UK VAT Return & Making Tax Digital for VAT

### ISSUE THREAD

**Issue by racitup** [frappe/erpnext#21233]
### [Pledge your support for this project here!](https://www.casesolved.co.uk/products/erpnext-features/erpnext-ukvat)
**This integration will allow ERPNext to be published as HMRC Recognised Software on their website.**

## Pre-requisites
Frappe general purpose OAuth2 client (see [here](https://github.com/frappe/frappe/issues/9722))
Multiple Company Tax registrations (see [here](https://github.com/frappe/erpnext/issues/21723)) - Can be implemented with regional-specific custom fields on the Company
Chart of Accounts Map (see [here](https://github.com/frappe/erpnext/issues/21694)) see #25254 

### UK VAT
A VAT return report and digital integration with HMRC that supports all domestic and international goods and service purchase and sales according to UK VAT rules
- Deliver the 9-box UK VAT Return report format, including:
  - Provision for Suppliers and Customers to be marked with regions for specific VAT rules
  - Provision for invoice items to be marked with categories, specifically: Goods, Services and Mobile Phones/Chips
  - A mechanism that applies VAT rates (standard: 20%, reduced: 5%, zero: 0%) and accounts to invoice lines based on the two pieces of information above
  - Transactions not applicable for VAT reporting, e.g. local authority rates, must not have VAT applied and so will not be picked up by the report
  - The 9 boxes must be editable to allow the HMRC submission of special VAT accounting schemes
- OAuth2 & REST-based submission of figures
- Storage of VAT Registration Number (VRN), a 9-digit number

### ERPNext constraints
- Must work on one-off purchase transactions with lines that are not pre-defined as Items
- Must work with the existing ERPNext tax features
- VAT must be captured as normal ledger entries in suitable accounts. This allows existing ledger reports to be used for analysis and debugging
- Tax must **not** be accounted for outside of the CoA; the report must draw its values from General Ledger entries so as to include correcting Journal Entries
- Although there is a "Tax ID" field, the UK has various Tax IDs that relate to a Company (Corporation Tax (UTR), PAYE, VRN, EORI) so the UK will need several IDs
- Although there are Sales/Purchase Taxes and Charges Templates, since they apply a rate to whole invoices and not individual invoice lines, they do not cater for invoices with lines with differing VAT rates and accounting requirements and so cannot be used in the general case or exclusively
- All features should be added as regional customisations in the regional module so as not to pollute the base UI

### Recommendations
- It should be possible for Sales and Purchase VAT to be accounted on separate Accounts, though not essential
- The report should have a drill-down/detail table to allow for analysis
- Item Tax Template should be extended to allow application to Sales and Purchases separately, and ideally the Sales/Purchase Taxes and Charges template should be refactored to apply to line items instead of invoices

## Setup
Boxes 1 to 4 can be generated directly from the Chart of Accounts using standard ERPNext functionality with the following setup:
- Tax Categories for Customers and Suppliers (separately) to identify their region: UK, EU or Rest of World (optional)
- Item Tax Templates set up to apply the correct VAT rate to the correct Account(s), for example:
  - A Reverse Charge Purchase at standard rate requires 20% to be applied to a *VAT on Purchases* Account (used for Box4), and -20% to also be applied to a *VAT on Sales* Account (used for Box1)
  - For common or stock items, Item Groups set up with Items in the correct Group, to automatically apply the correct Item Tax Template based on the Item & Tax Category (optional). Though Item Tax Templates can be applied manually to non-inventory Items

## Additional DocTypes and fields (with fieldtype, etc) if any
See pre-requisites
The CoA Map will need to be extended to include the following functionality:
- Item Tax Template name filter (simple pattern matching similar to SQL like) used to generate tax entries, since it may be necessary to select specific transactions for example Services and Mobile Phone Reverse Charges
- Selection of the related transaction value or tax value for the report
- Sales or Purchase filter to allow VAT to be reported to a single account but maintain report flexibility
- Negative - whether the value should be negated
- Sum multiple entries with the same output field name, allows a report value to be a composite of multiple values

## Discovery (how will the user find the feature you are building)
- Chart of Accounts - View menu: HMRC VAT Returns
- Accounting -> Taxes -> HMRC VAT Returns
- Accounting -> Taxes -> Connect to HMRC
- Company -> HMRC Settings
- User -> Third Party Authentication
## Screen Mockups with buttons and any custom UI (TBD)
- HMRC user permissions definition (scopes); also used as auth fail destination
- (OAuth2 Authorisation flow: out-of-scope)
- VAT Information as tables (auth & VAT return submit success):
  - VAT return obligations (mandatory) with buttons to the VAT report specifying the period and PeriodKey
  - Submitted VAT returns (optional)
  - VAT liabilities (optional)
  - VAT payments (optional)
- VAT Report for a period with 2 use cases:
  - Manual period definition, OAuth2 not required, no submit button
  - Period passed from VAT return obligation button, VAT Return submit button
    - Displays error for failed submissions
### Validations
- Company VRN number existence
- HMRC OAuth2 Provider existence
### Calculations
See Reports section
### Logs
None
## Links to existing DocTypes
Links to VAT Accounts
## Reports
Calculations performed according to this table which is not a complete picture:
[UK VAT return](https://docs.google.com/spreadsheets/d/1wgVkg9sJkeLj5-v0tob5P3kw6Xkh_LVHmBi-HENea2M/edit?usp=sharing)
The report uses Journal Entries specified by the CoA Map for boxes 1 to 4 which are the primary VAT lines
Box 5 is a sum based on boxes 3 & 4
Box 6 to 9 must be generated from the transactions used in boxes 1 to 5, to exclude non-VAT transactions, for example: salaries & exempt purchases

This has not been designed for special VAT accounting schemes, though the 9 boxes on the VAT Return will be editable to allow different schemes to be posted.
[Further information from HMRC](https://www.gov.uk/guidance/how-to-fill-in-and-submit-your-vat-return-vat-notice-70012)

**Comment by barredterra** [comment]
Hi @racitup, some thoughts on your proposal:

> VAT Registration Number (VRN)

Isn't this the same as "Tax ID"?

> Sales VAT Account, Purchase VAT Account

There already exists **Sales/Purchase Taxes and Charges Template** and account type "Tax" for marking VAT accounts.

> Reverse Charge rule applies

Reverse charge can be modeled with **Sales/Purchase Taxes and Charges Template**. For example, this one deducts the taxes I owe to the state because of reverse charge and adds the taxes I can claim back:

![image](https://user-images.githubusercontent.com/14891507/79073816-ea193980-7ce8-11ea-9702-5acf44555c21.png)

**Comment by racitup** [comment]
Hi Raffael,
Thanks for your feedback, it's much appreciated! I've added rationale to my proposal above but also:

> > VAT Registration Number (VRN)
>
> Isn't this the same as "Tax ID"?

Although there is a "Tax ID" field, the UK has various Tax IDs that relate to a Company (Corporation Tax (UTR), PAYE, VRN, EORI) so the UK will need several IDs. The VRN for example is not mandatory for all companies

> > Sales VAT Account, Purchase VAT Account
> 
> There already exists **Sales/Purchase Taxes and Charges Template** and account type "Tax" for marking VAT accounts.
> 
> > Reverse Charge rule applies
> 
> Reverse charge can be modeled with **Sales/Purchase Taxes and Charges Template**. For example, this one deducts the taxes I owe to the state because of reverse charge and adds the taxes I can claim back:
> 

Although there are Sales/Purchase Taxes and Charges Templates, since they apply a rate to whole invoices and not individual invoice lines, they do not cater for invoices with lines with differing VAT rates and accounting requirements and so cannot be used. Setting the VAT Accounts is a configuration setup for a company that will allow the VAT report to find the relevant ledger entries and work.
For example you could have an item of goods not applicable to reverse charge and a service applicable to reverse charge on the same invoice. I'm considering a PR for the Item Tax Template though

**Comment by barredterra** [comment]
> UK has various Tax IDs that relate to a Company

Same for Germany. In this case we could have **Tax ID** as a separate DocType with fields `ID` and `Tax Category`.

---

> Accounting -> Taxes -> Connect to HMRC

I would see **HMRC Settings** as a DocType in the Integrations module.

**Comment by racitup** [comment]
> I would see **HMRC Settings** as a DocType in the Integrations module.

I see all of these additional fields as custom fields added in the regional module. It's not an integration applicable to any other country.

**Comment by racitup** [comment]
@barredterra Though actually, it looks like the Reverse Charge rules apply to the whole of the EU, would some of these changes be useful for Germany? I could see if relevant parts could be inheritable somehow.

**Comment by Paul-STHL** [comment]
Greetings all. I have a working implementation here :

https://github.com/frappe/erpnext/issues/16025#issuecomment-611981655

Comments and feedback invited.

**Comment by racitup** [comment]
> Greetings all. I have a working implementation here :
> 
Good work but I think it's fair to say it doesn't implement a lot of what is required to be merged as a maintainable feature that integrates properly with ERPNext. It was a good decision to keep it as a separate app

**Comment by Paul-STHL** [comment]
> > Greetings all. I have a working implementation here :
> 
> Good work but I think it's fair to say it doesn't implement a lot of what is required to be merged as a maintainable feature that integrates properly with ERPNext. It was a good decision to keep it as a separate app

I like to get a minimally viable product quickly so we can talk about actual things to improve. If you have any constructive feedback on its maintainability, please feel free to offer it any time!

**Comment by racitup** [comment]
> I like to get a minimally viable product quickly so we can talk about actual things to improve. If you have any constructive feedback on its maintainability, please feel free to offer it any time!

See design above

**Comment by nameduser0** [comment]
@deepeshgarg007  Hi Deepesh, could you review this accounting proposal please?

**Comment by nameduser0** [comment]
If anyone is interested in our HMRC support please visit [https://www.casesolved.co.uk](https://www.casesolved.co.uk) It seems one of the founders Umair is upset because we wouldn't give it away for free on their market so is closing the issues 😃
