### ISSUE TITLE
Cannot fetch updated primary contact through customer master

### ISSUE THREAD

**Issue by neerajvkn** [frappe/erpnext#21239]
Description of the issue
When a customer contact is edited, edited values are not updated in the customer master, new values cannot be fetched using link field to customer master

Steps to reproduce the issue
1. Create a customer entry in master with details
2. edit the contact number/email id in contact for the created customer
3. try fetching the email/id using link field to customer master
4. fetched values will be the old values 

Observed result
email id/mobile no which was there before the edit is fetched

Expected result
edited values should be fetched fetched

Additional information
OS : Ubuntu 16.04.6 LTS
Installed Apps
ERPNext: v12.4.2 (version-12)
Frappe Framework: v12.2.1 (version-12)
Hide Help Menu: v0.0.1 (master)
Jkr: v0.0.1 (master)

**Comment by melBoh** [comment]
Hi ! same issue here ;)
ERPNext: v13.35.0 (version-13)
Frappe Framework: v13.35.0 (version-13)

**Comment by deepeshgarg007** [comment]
@neerajvkn You have to reselect the contact name in the customer master for the values to be updated.
