### ISSUE TITLE
Posting date and time- Payment entries

### ISSUE THREAD

**Issue by RomanyMaged** [frappe/erpnext#21240]
I have customized the posting date and time of payment entry to be read only so the system captures the actual date and time the payment entry was made without any user interaction. There was an incident where a user had a problem with their computer date. Consequently, the entries were submitted on the wrong date which was a significant problem given that date and time are very critical in payments

Can the system capture the time based on the time zone of the user to avoid this incident happening again?

Thank you.

**Comment by marination** [comment]
@RomanyMaged  I understand the problem, although this isn't a frequently occurring issue. The system time in most cases is the same as the timezone. Fetching the current time happens almost by the minute, your suggestion will add an overhead to that. The device's Date and Time is crucial to a lot of softwares running on it, it must be kept in check.
This isn't feasible transaction wise.
