### ISSUE TITLE
Sales Invoice remain Unpaid when Payment received & Sales Order completed

### ISSUE THREAD

**Issue by OnlyC** [frappe/erpnext#21259]
## Description of the issue
Sales Invoice remain Unpaid when Payment received & Sales Order completed

## Steps to reproduce the issue

1. Submit Sales Order
2. Create & Submit Delivery Note
3. Create & Submit Sales Invoice
4. Create & Submit Payment Entry

### Observed result
Payment Entry submitted.
Sales Order status: Complete
Sales Invoice status: Unpaid

### Expected result
Sales Invoice status: Paid

## Additional information

ERPNext: v12.x.x-develop () (develop)
Frappe Framework: v12.3.0 (version-12)

**Comment by marination** [comment]
@OnlyC  I ran a cycle and everything works fine. Please check the **outstanding amount** in your Sales Invoice. Also check if **this** Sales Invoice is in the Payment References table of your Payment Entry. 
Sales Invoice status will be Paid only if the **outstanding amount**  is 0.

**Comment by OnlyC** [comment]
Yes, I am sure the Sales Invoice exist in Payment References table. Sales Invoice's Outstanding amount is 0.

Sales Invoice still showing Unpaid.
