### ISSUE TITLE
Doctype for valuation rate is needed which should be Warehouse Wise.

### ISSUE THREAD

**Issue by adityaduggal** [frappe/erpnext#2126]
Hi,

I would like to recommend that there should be a doctype like Item Price for Valuation rate as well.
The doctype would have the following fields:
- Item Code (Item ID)
- Item Description
- Item Name
- Warehouse (not mandatory)
- Valuation Rate
- Valuation Rate Referene (something like Price List, if feasible) (or something like applicable from date since valuation rate generally changes as per the pricing of items)

Now this doctype would help us in following things:
- Stock entries being done by people in manufacturing department would not be concerned with the valuation rate as is the case currently.
- Stock valuation in stock ledger  would fetch the prices as per warehouse from this doctype only.

Reference Tickets for are issue #1707, issue #1473

**Comment by ankush** [comment]
There's now a doctype called "Bin" which does a lot of what's mentioned here.
