### ISSUE TITLE
Filter Loan Application and Loan using User Permissions

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#21271]
At the moment, an Employee can view all(for other employees) Loan Applications, Loans.
This a request for them to be filtered via User Permissions, say like salary slip, and expense claim.

**Comment by marination** [comment]
This can be easily done by applying permissions. You can use Role Permissions Manager. Please read our documentation on [Role Based Permissions](https://docs.erpnext.com/docs/user/manual/en/setting-up/users-and-permissions/role-based-permissions)

**Comment by muchai** [comment]
:), That's what we did (used user permissions). We normally report as areas that need improvement or fixes. Otherwise this is a behavior that would be a surprise/gotcha to a user. Imagine reading the documentation on what the employee role is supposed to see, only later to realize all staff could view all loans?
