### ISSUE TITLE
Accounting Dimensions prevent fields from getting mapped

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#21288]
Hi ,

Let's say for example we create an accounting dimension called 'Business Unit'. Now this value needs to be filled by the Sales Team in Sales Orders and get automatically mapped to Sales Invoice when it is created. We therefore create a custom field in Sales Order with the same name but it doesn't get mapped

If however you disable the accounting dimension, the mapping works so this bug is clearly related to enabling accounting dimensions

Kindly help fix asap

Thanks

**Comment by deepeshgarg007** [comment]
Hi,

I just tried and the issue has already has been fixed, please update your instance and remove the default dimension row from the accounting dimension if present. The default dimension in the row must be blank which is overriding the dimension mapped from Sales Order
  
<img width="1195" alt="Screenshot 2020-04-16 at 10 55 16 AM" src="https://user-images.githubusercontent.com/42651287/79418019-30b0b180-7fd1-11ea-98a5-e4d6e469ac02.png">

**Comment by Olawale1** [comment]
Hi @deepeshgarg007 

Thanks for your feedback. I have checked what you described but this seems to be only a partial fix as it means we won't also be able to make Accounting Dimensions mandatory (for Balance Sheet and/or Profit and Loss Accounts) across all relevant docs

I think a better fix would be to only use the Default Dimension field when a value is set and ignore when blank

Could you pls re-open this or should I create another issue?

Thanks

**Comment by Olawale1** [comment]
Hi @deepeshgarg007 

Awaiting your confirmation on this pls

Kind regards,
