### ISSUE TITLE
Batchwise pricing of items

### ISSUE THREAD

**Issue by sagun-01** [frappe/erpnext#21303]
**Is your feature request related to a problem? Please describe.**
I am setting up ERPnext for Pharmaceuticals. Prices for medicine(item) varies from batch to batch, however prices in ERPnext are item wise, not batch wise. This is leading to problems in purchase and sale, as the selling prices of the previously purchased items is also updated. 

**Describe the solution you'd like**
Instead of item price, i would like a provision for item batch price 

**Describe alternatives you've considered**
Couldn't find any alternate solution in ERPnext

Thank you

**Comment by mujeerhashmi** [comment]
Batch based pricing is a must for pharmacies. Any ideas if this can be achieved with existing features @ruchamahabal or is this part of the road map.

**Comment by mujeerhashmi** [comment]
@nextchamp-saqib this feature is a must for POS to be usable by pharmacies. The healthcare module badly needs this.
