### ISSUE TITLE
Wrong link between doctypes when delivering multiple batches of same item

### ISSUE THREAD

**Issue by adfluidics** [frappe/erpnext#21318]
## Description of the issue
Hi, 
When a client orders for example 10x item A, we sometimes need to send different batches of the same item, e.g. 5x item A - batch 1, 5x item A - batch 2

All three documents are submitted, but not with exactly the same structure: 
- Sales Order & Sales Invoice: 10x item A (in 1 row)
- Delivery Note: 5x item A - batch 1 & 5x item A - batch 2 (in 2 rows since we cannot enter 2 batches in 1 row)

When this happens, there is an issue with the links between the documents:
- The Sales Order has the status "Overdue"
- The Delivery Note has the status "To Bill"

However, the correct quantity has been delivered and billed to the client.

## Context information (for bug reports)
This happens systematically when there is:
- Sales Order & Sales Invoice: 10x item A (in 1 row)
- Delivery Not: 5x item A - batch 1 & 5x item A - batch 2 (in 2 rows since we cannot enter 2 batches in 1 row)

**Output of `bench version`**
```
ERPNext: v12.7.0 (version-12)
ERPNext Support: v0.0.3 (master)
Frappe Framework: v12.5.0 (version-12)
Journeys: v0.0.1 (version-12)
```

## Steps to reproduce the issue

1. Create a Sales Order with 10x Item A
2. Create the Sales Invoice with 10x item A
3. Create a Delivery Note with 5x Item A (row 1, batch 1) + 5x Item A (row 2, batch 2)

### Observed result
System does not consider the order as delivered or billed:
Sales Order is "Overdue"
Delivery Note is "To Bill"

### Expected result
Sales Order should be completed
Delivery Note should be completed

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by marination** [comment]
@adfluidics The status "Overdue" is purely based on the transaction date vs required by date. Also "To Bill" clearly indicates that some payment is pending. Once a payment is done the Delivery Note can be **Completed**.

Regarding splitting the row into 2 rows, instead of just Adding a row, you could **Duplicate** the row.
![Screenshot 2020-04-20 at 7 14 43 PM](https://user-images.githubusercontent.com/25857446/79758700-59230d80-833b-11ea-9391-3436039f2d74.png)
 
In this way the reference will be attached to this new row as well. This should set your Sales Order status to complete if the ordered quantity is delivered.

**Comment by adfluidics** [comment]
As I mentioned before, all transactions have been made.

Meaning that both the statuses Overdue and To Bill should NOT be showing, everything should be shown as Completed/Paid...

Duplicating the row did the trick! Thanks!!

In this case, there is a bug. It should not make the error if we add a row with the same item reference!

**Comment by marination** [comment]
@adfluidics yeah it slipped my mind , adding multiple rows with the same item is not supported.  For now i can only recommend making two Delivery Notes in this case.

**Comment by adfluidics** [comment]
Since duplicating the row works, it's a good workaround for me ! Have 2 delivery notes is a pain in my case as my Commercial Invoice, for border purposes, is based on my Delivery Note.

Thanks for your help in any case!
