### ISSUE TITLE
Link default project to Material Requests, Purchase Order and Purchase Invoice

### ISSUE THREAD

**Issue by vinit320** [frappe/erpnext#21333]
In an R&D scenario, work orders or sales orders cannot be created since its a development job. In such a case, it is required to order raw material for development. As of now, when a material request is made from the project page, each individual item needs to be told what project its been requested for.

This becomes quite tedious since if there are more than 10 materials requested, each item needs to be told individually for what project its been requested for. 

I am aware that you can fill in the item list, download the list, fill up the required fields, and then re-upload the list. But this again is time consuming, and the user may also forget to do the above.

A solution that I propose is to have a default Project field near the Required by Date field. The functionality would be similar to Required By Date field, as in when the user enters the required date, it is automatically populated for all items in the list. The user then has the freedom to enter different dates for certain items. A similar approach can be done for the Project field as well.

**Comment by vinit320** [comment]
Using the above solution, since Material Requests are linked to Purchase Orders, which are further linked to Purchase Invoice, it will automatically create a hierarchy for the same. Also the default Project field need not be mandatory.

**Comment by vinit320** [comment]
Anyone?

**Comment by vinit320** [comment]
Any update on this?

**Comment by xickomesquita** [comment]
I do work orders for my R&D projects... What kind of issue you notice using this?

**Comment by cdiethelm** [comment]
I have the same issue. Would be very helpful to have this auto inserted.

**Comment by ongeto** [comment]
This is still an issue that needs to be addressed.
