### ISSUE TITLE
BUG: User None not Found in Email Digest

### ISSUE THREAD

**Issue by dawoodjee** [frappe/erpnext#21337]
I’m running the latest version of Frappe and ERPNext in production. No customisation or modifications have been done.

I’ve deleted and added users before, this problem started when I setup email digest and added all the users.

![image](https://user-images.githubusercontent.com/7912989/79724531-04a27280-82e8-11ea-8380-8b51dc2ae6e7.png)

I cant login or do anything else. Other sites are fine.

Issue is only fixed by deleting Digest entry from the database

Orriginally posted on the forum: https://discuss.erpnext.com/t/cant-use-erpnext-due-to-user-not-found-error/57337

**Comment by pateljannat** [comment]
This will be fixed with #23949
