### ISSUE TITLE
Represents Company must be unique while creating customer

### ISSUE THREAD

**Issue by Suprazz** [frappe/erpnext#21349]
## Description of the issue
Can't create customer with latest erpnext version. Get the error Represents Company must be unique
## Context information (for bug reports)
I tried to check internal customer and/or uncheck but still doesnt work with the field represents company. Not sure what is going on. It was working well before the upgrade.

**Output of `bench version`**
```

bench_manager 0.0.1
erpnext 12.7.0
erpnext_shopify 2.0.26
erpnextswiss 1.9.1
foundation 0.0.1
frappe 12.5.0
woocommerceconnector 1.3.0

```

## Steps to reproduce the issue

1. Go to customer doctype
2. Create new customer
3. Hit save

### Observed result
error and can'T save customer
### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by kennethsequeira** [comment]
Closing the issue since the answer is provided in the thread:

https://discuss.erpnext.com/t/erpnext-12-7-0-represents-company-must-be-unique/60596
