### ISSUE TITLE
Update resets Is Submittable for a document

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#21341]
When Is Submittable is set by a user, i.e. as opposed to standard. Everytime theirs an update, it  is reset. This happens in version 12, specifically for Item Price doctype.

**Comment by marination** [comment]
Perhaps thats because on the DocType level in ERPNext **Item Price** is not submittable. If you update your instance it is bound to change to what the original repository contains. This is not a bug.

**Comment by muchai** [comment]
That's the issue, but should this be the expected behaviour? Can't one user customize a doctype to be submittable for specific cases?
