### ISSUE TITLE
List View: Filter: Group or Tree based filters

### ISSUE THREAD

**Issue by vorasmit** [frappe/erpnext#21363]
## Description of the issue
Issue is faced in filters of list view. Where filter is based of field like Customer Group / Supplier Group / Item Group / Cost Center / Territory / Warehouse. Wherever there is tree structure used for field this issue is found.

**Issue:**
Where filter is given on group nod, all values applicable in child nods should also be visible in filter.
Eg: where filter is done for "All Customer Groups", values of customers in Child nods i.e "Commercial" should also be visible.

## Steps to reproduce the issue

1. Open Customer List. Check values without filter in customer group and with filter as "All Customer Groups" in customer group.
2. Filter is not correct.

### Expected result
For Parent Group, Values of all Child nods should be incorporated in filter. If Filter is done for "All Customer Groups" Values for customer group as "Commercial" should be visible.

## Additional information
Screenshot **With** Filter

![Annotation 2020-04-22 082010](https://user-images.githubusercontent.com/10496564/79937721-48c47d00-8478-11ea-941d-38e1e2951504.png)

Screenshot **Without** Filter

![Annotation 2020-04-22 082010](https://user-images.githubusercontent.com/10496564/79937852-8e814580-8478-11ea-8cd7-067ca9b81549.png)

OS version / distribution, `ERPNext` install method, etc.
Demo Instance
https://retail.erpnext.com/desk#List/Customer/List

**Comment by abhishekbalam** [comment]
@vorasmit 
To get the functionality you need, use the "Descendants Of" filter.

![img](https://user-images.githubusercontent.com/13928957/81491618-0ee3db00-92ae-11ea-9cac-2f1cbf16eaf6.png)

As [explained](https://github.com/frappe/frappe/issues/6588#issuecomment-626276824) in this issue in Frappe : https://github.com/frappe/frappe/issues/6588

**Comment by vorasmit** [comment]
@abhishekbalam 
Thanks for the update. Frankly, I was not aware of this. But I think it is still an issue after testing it further and it seems that it is faulty design.

It is for these three reasons:

1. This list view is deceiving and it seems to be faulty design. In general, terms, when there is filter for all customer groups, users wonder why he is not finding some customers.

![79937721-48c47d00-8478-11ea-941d-38e1e2951504](https://user-images.githubusercontent.com/10496564/81772601-ece39600-9503-11ea-9da4-f3444851d843.png)

2. When the filter is manually set to Customer "Is Decendents of" All Customer group, you get filter over child values of group nodes. This is perfect as the statement goes, but still we are not getting filter on the group node + child node.

![Annotation 2020-05-11 184215](https://user-images.githubusercontent.com/10496564/81773379-c45c9b80-9505-11ea-89e5-c4bcf62b9a0b.png)

3. While filtering Customer Group is Decedent of ... , we get the option to choose child fields, that is the fields that have no dependents. (Again seems faulty design)

Conclusion:

There should be consistency in standard filters used throughout the ERP. For reports, when you filter on All Customer Groups, it gives expected result but doesn't work well with list view.

![Annotation 2020-05-11 184215](https://user-images.githubusercontent.com/10496564/81773769-b3605a00-9506-11ea-9d0b-5a4ce7832b54.png)

**Comment by guilmori** [comment]
Please put priority on this.

This issue is extremely well documented by @vorasmit, yet it is blatantly ignored after more than a year ...
