### ISSUE TITLE
POS Profile: Filter Customer Group not working

### ISSUE THREAD

**Issue by vorasmit** [frappe/erpnext#21362]
##  Description of the issue
In POS Profile where filter on customer group is chosen, it shows all customers in POS

## Steps to reproduce the issue

1. In POS profile, Choose customer group as Individual
2. Open POS. While choosing customer, all customers are visible.

## Additional information
POS Profie:
https://retail.erpnext.com/desk#Form/POS%20Profile/Demo%20POS%20Profile

![Annotation 2020-04-22 081846](https://user-images.githubusercontent.com/10496564/79935191-eb2d3200-8471-11ea-8d87-0ad1063778e9.png)

POS

![Annotation 2020-04-22 082010](https://user-images.githubusercontent.com/10496564/79935274-229bde80-8472-11ea-92e9-9a11a4d432a4.png)

OS version / distribution, `ERPNext` install method, etc.
Erpnext Demo Instance.

**Comment by ssiyad** [comment]
I can not reproduce this on POS view. Form view is affected though
