### ISSUE TITLE
Filtering by Product Groups Hierarchy

### ISSUE THREAD

**Issue by maaz** [frappe/erpnext#2138]
Filtering products by Product Group Hierarchy does not work.
As an example, for a Product Group hierarchy,
Computers
    > Personal Computer
            > Laptop
                   > Netbook
                   > Chromebook
            > Desktop

If I add products in Netbook category, and add a filter in the list view to search for all products in Laptop category, none of the products show up.

Please prioritize this issue and get it fixed so that when filtering over a parent category, products in all the child categories also show up.

For us, hence, product group hierarchy is pretty useless as we really want to use that as a means to filter/browse products.

Have attached a few screenshots for reference.

![screen shot 2014-09-01 at 11 17 07 am](https://cloud.githubusercontent.com/assets/343018/4118101/8e76b950-329c-11e4-933c-2a7e65a1a2e5.png)
![screen shot 2014-09-01 at 11 16 48 am](https://cloud.githubusercontent.com/assets/343018/4118103/8e7df828-329c-11e4-812b-5b70c6062ce8.png)
![screen shot 2014-09-01 at 11 15 37 am](https://cloud.githubusercontent.com/assets/343018/4118102/8e77a824-329c-11e4-8845-c287a6825140.png)

**Comment by maintanosgr** [comment]
+1

**Comment by RA-dim** [comment]
+1

**Comment by Devens** [comment]
+1

**Comment by rtimagine** [comment]
+1

**Comment by rmehta** [comment]
In db_query, if the doctype is a nested set, and a filter is on the `parent_node` then add lft, rgt filters.

Might just work!

**Comment by joezsweet** [comment]
@maaz  can you please check this on version 8?

**Comment by Olawale1** [comment]
Hi,

Any update on this? Really hope a solution can be achieved soon. It's been almost 3 years and it would greatly help the user experience. Up till now, we're still having to export to Excel in order to filter by a parent group!

Thanks plenty

**Comment by kennethsequeira** [comment]
Can be filtered with the 'Descendants Of'
