### ISSUE TITLE
Delete Company Transactions also delete info on Item Groups

### ISSUE THREAD

**Issue by maovidal** [frappe/erpnext#21393]
## Description of the issue

Performing a "Delete Company Transaction" for a company also deletes the defaults on the "Items Groups" and "Items" for the Cost Center and Expense/Income Accounts.

## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 12.7.1
frappe 12.5.1
```

## Steps to reproduce the issue

1. Have populated some records at the "Item Groups" with information at the "Default" section. ie: Default Buying Cost Center, Default Expense Account, Default Income Account.
2. Have "items" associated to those "Items Groups".
3. Perform a "Delete Company Transactions" from the Company.

### Observed result
All the information regarding the "defaults" for those "Item Groups" as well their associated "Items" is also deleted.

### Expected result
That information should not be deleted as the chat of accounts and the cost centers are preserved.

If that defaults are going to be deleted on this and other sections, it seems that the documentation at the article https://docs.erpnext.com/docs/user/manual/en/setting-up/articles/delete-a-company-and-all-related-transactions should state that.

**Comment by deepeshgarg007** [comment]
Fixed via https://github.com/frappe/erpnext/blob/develop/erpnext/setup/doctype/transaction_deletion_record/transaction_deletion_record.py#L222

**Comment by MohamedAbdulsalam96** [comment]
doctypes to be ignored list is determined consistently in the code..
I'm not sure what can be done with the "Transaction Deletion Record" document In erpnext..

I think it would be very helpful if the addition and amendment to the doctype list that would be ignored through the "Transaction Deletion Record" document were available..
And consider that in the code.
