### ISSUE TITLE
BOM Exploded Items Table uses stock qty and rate to calculate amount

### ISSUE THREAD

**Issue by kardmode** [frappe/erpnext#21400]
## Description of the issue
BOM Exploded Items Table uses stock_qty * rate to calculate amount instead of qty * rate.

## Context information (for bug reports)

```
	def get_exploded_items(self):
		""" Get all raw materials including items from child bom"""
		self.cur_exploded_items = {}
		for d in self.get('items'):
			if d.bom_no:
				self.get_child_exploded_items(d.bom_no, d.stock_qty)
			else:
				self.add_to_cur_exploded_items(frappe._dict({
					'item_code'		: d.item_code,
					'item_name'		: d.item_name,
					'operation'		: d.operation,
					'source_warehouse': d.source_warehouse,
					'description'	: d.description,
					'image'			: d.image,
					'stock_uom'		: d.stock_uom,
					'stock_qty'		: flt(d.stock_qty),
					'rate'			: d.base_rate,
					'include_item_in_manufacturing': d.include_item_in_manufacturing
				}))
```

```
def add_exploded_items(self):
		"Add items to Flat BOM table"
		frappe.db.sql("""delete from `tabBOM Explosion Item` where parent=%s""", self.name)
		self.set('exploded_items', [])

		for d in sorted(self.cur_exploded_items, key=itemgetter(0)):
			ch = self.append('exploded_items', {})
			for i in self.cur_exploded_items[d].keys():
				ch.set(i, self.cur_exploded_items[d][i])
			ch.amount = flt(ch.stock_qty) * flt(ch.rate)
			ch.qty_consumed_per_unit = flt(ch.stock_qty) / flt(self.quantity)
			ch.docstatus = self.docstatus
			ch.db_insert()
```

## Steps to reproduce the issue

1. Create item with different uoms with conversion factor not equal to 1
2. Use item in BOM with uom other than stock uom.
stock_qty and rate will be calculated using conversion factor
3. Save and generate exploded items list.

### Observed result
Amount field value in exploded items table is different than bom items table.

### Expected result
Amount field value in exploded items table to be same as bom items table. qty * rate

## Additional information

ERPNext: v12.7.0 (version-12)
Frappe Framework: v12.5.0 (version-12)

**Comment by martinhbramwell** [comment]
Related: 

[BOM variant calculating absurd quantities for “Materials Required (Exploded)”](https://discuss.erpnext.com/t/bom-variant-calculating-absurd-quantities-for-materials-required-exploded-weird/74919)

erpnext 13.0.2
frappe 13.0.3

**Comment by deepeshgarg007** [comment]
@abhinav666 If the issue still persists in the latest version-13 or higher releases please reopen a new issue
