### ISSUE TITLE
How does the ERPNext marks attendance on daily basis, using punch in & outs

### ISSUE THREAD

**Issue by komalvadavale-09** [frappe/erpnext#21409]
Steps that I have followed:

1. created shift type & enabled auto attendance 

2. shift request to employees

3. Imported check ins & out data

**Comment by Anurag810** [comment]
@komalvadavale-09 yeah you can mark attendance automatically but using Employee  Check-ins Records.
Please refer to the link.
https://frappe.io/kb/hr/using-auto-attendance
