### ISSUE TITLE
v13 doctype location incorrectly restricted to Agriculture domain 

### ISSUE THREAD

**Issue by szufisher** [frappe/erpnext#21418]
## Description of the issue
Location doctype is restricted to agriculture domain, but it is also used by asset master as mandatory field, in other word, if agriculture domain not activated , then there is no way to use the assets module because location doc can not be created anyway.
![image](https://user-images.githubusercontent.com/12823863/80299330-273ffa00-87c6-11ea-98f6-fc779d51b3f1.png)

## Context information (for bug reports)
Installed Apps
ERPNext: v12.x.x-develop () (develop)

Frappe Framework: v12.x.x-develop () (develop)

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1. login as system manager, make sure the agriculture domain not activated
2. create a new asset, try to input location 
3.

### Observed result
New asset can not be created due to mandatory location can not be selected/created on the fly
### Expected result
Location can be created even the agriculture domain not activated.

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by kennethsequeira** [comment]
Should be fixed with: #21659
