### ISSUE TITLE
Link company logo to iOS home screen bookmark icon

### ISSUE THREAD

**Issue by bitaccesscomau** [frappe/erpnext#21417]
When adding a bookmark link to the ERP on the iOS home screen, the icon appears as a preview of the webpage. I would like to link the icon to the currently selected company logo - or if unavailable, the ERPNext logo. This can be done by following the procedure in the link below, unfortunately I'm not well versed enough in Git to be able to do this myself. 

https://www.create.net/support/adding-an-ios-home-screen-icon-for-your-website

**Comment by kennethsequeira** [comment]
@bitaccesscomau no need to use git.

Just upload the image file to the ERP and add the link in the head tag under website settings:

![image](https://user-images.githubusercontent.com/33246109/89559254-0b230e80-d833-11ea-8699-f85590fc749f.png)

This should do the trick for you.
