### ISSUE TITLE
Serial Nos. - Valuation Rate updation

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#2144]
As requested by Irene, Shoukinet.

Provide option to correct/amend stock valuation for serialized items just like it is available for the non-serialized items.

**Comment by nabinhait** [comment]
Stock Reconciliation for Serialized Item

**Comment by joezsweet** [comment]
@umairsy @nabinhait is this still pending for v8?

**Comment by umairsy** [comment]
yes, still pending.

**Comment by jigartarpara** [comment]
Any update here?

**Comment by Ashraf-Elsharqawy** [comment]
Any update here?
