### ISSUE TITLE
V13 Repay from Salary Loans not being picked on payslips

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#21457]
![image](https://user-images.githubusercontent.com/1822868/80455063-bd456300-8933-11ea-8f5d-a0e50b6c0c0c.png)

In addition: Repayment Period in Months, and Monthly Repayment Amount should be visible or invisible based on Repayment Method selection.

**Comment by Anurag810** [comment]
@deepeshgarg007   fixed ??

**Comment by muchai** [comment]
Still the case in -v13.0.0-beta.4

**Comment by muchai** [comment]
Was this resolved please. It means for users using loans for payroll, migrating to v-13 is an issue.
