### ISSUE TITLE
Accounting Dimensions of Parent Doctype Ignored 

### ISSUE THREAD

**Issue by Andriesvn** [frappe/erpnext#21466]
## Description of the issue
Accounting dimensions of parent items such as Sales Invoice | Purchase Invoice are ignored in child items in favor of default dimensions. Changing the parent dimension has no effect on child items.

**Output of `bench version`**
```
bench version
erpnext 12.7.0
frappe 12.5.0

```

## Steps to reproduce the issue

1. Create accounting dimension with multiple values 
2. Pic a Dimension in parent item that is not a default dimension

### Observed result
No child entries are updated and no child entries added afterwards receive the non-default parent dimension.
### Expected result
Child accounting dimensions should be updated to that of the parent.

Attached a fixed version of erpnext/erpnext/public/js/utils/dimension_tree_filter.js
to address this issue.

also removed duplicate items_add and accounts_add events
[dimension_tree_filter.js.txt](https://github.com/frappe/erpnext/files/4544839/dimension_tree_filter.js.txt)

**Comment by deepeshgarg007** [comment]
Hello @Andriesvn 

The Parent Level accounting dimension is for the Balance Sheet Account and the accounting dimensions in the Item Table (child) is for Profit and Loss account so both of them can be different. So there is no point in changing dimensions in child table on dimension change at the parent level

> also removed duplicate items_add and accounts_add events
dimension_tree_filter.js.txt

Also what do you mean by this?  

>

**Comment by Andriesvn** [comment]
Hi @deepeshgarg007 

Both can be different yes, however im assuming you would want the child items | accounts to at-least match the parent when creating a new Parent rather than having the default dimension on all child items all the time. And if no default was specified then they would all be blank. So your profit and loss in that case would be recording inaccurate Accounting dimensions?

> also removed duplicate items_add and accounts_add events
> dimension_tree_filter.js.txt
> 
> Also what do you mean by this?

as you can see, items_add and accounts_add are duplicated here
https://github.com/frappe/erpnext/blob/dcef7a96ef4145c810461890b335184a70cd1c84/erpnext/public/js/utils/dimension_tree_filter.js#L67-L93

**Comment by deepeshgarg007** [comment]
> Both can be different yes, however im assuming you would want the child items | accounts to at-least match the parent when creating a new Parent rather than having the default dimension on all child items all the time. And if no default was specified then they would all be blank. So your profit and loss in that case would be recording inaccurate Accounting dimensions?

The default dimension is added in just the first child row and in all the other rows its copied from the first row, so if you want any other value you can change it in just the first row and it will be copied from first row in other rows. 

And there can be transactions where you don't want any additional accounting dimensions just the standard cost center is enough, so even transactions with blank dimensions also make sense.

I'll remove the duplicate code and raise a PR

**Comment by Andriesvn** [comment]
Im sorry but im having trouble understanding this as Im not an accountant. Could you explain this a bit better to me?
I cant think of any cases where i would want the accounting dimension of the child to differ from parent during Normal operation, only outside of normal operations (of which i cannot think of any at the moment). 

Let me give you an example. Say my accounting dimension is set to "Branch". When creating say a Sales invoice for | at that particular Branch i would want both my Balance Sheet as well as my Profit and loss to correctly Identify that particular Branch`es Accounting dimension without needing to modify the first child item manually every time. 

Could you perhaps give me an example of why the child item is not set to the parent by default so I might understand the reasoning a bit better?
