### ISSUE TITLE
Exchange Rate for non-default currency is not picked correctly

### ISSUE THREAD

**Issue by dulhaver** [frappe/erpnext#21473]
We have a multi currency scenario at hand where exchange rates are fetched by ERPNext. No fixed Currency exchange entry exist on this instance

## Description of the issue
In Multi Currency Transactions (journal Voucher, Sales/Purchase Invoice, Payment ...) the exchange rate for any non-default currency involved in such a transaction is picked from the date when the transaction is created and **not** from the posting_date as it should.

this leads to the `Difference Amount`being generated based upon incorrect exchange rate if the transaction has happened in the past.

Lets look at an example:

- you create a `Purchase Invoice` for April 1st. 
- the payment for this invoice is done on the same day (so the exchange rate applicable for Invoice and payment is actually the same) 
- the Payment entry however is only entered into ERPNext a week later (with the correct posting date which is the same as the Invoice date) 
- the system will apply the exchange rate of April 1st ( the invoice and  payment date to the Invoice document, but a from April 7 for the Payment Entry

A `Difference amount` will occur which actually is not applicable due to the invoice and payment happening at the same day

## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 11.1.71
frappe 11.1.63
```

## Steps to reproduce the issue

1. Create a purchase invoice with a posting date A in a non-default currency
2. wait one week
3. create a payment with the same date A of the purchase invoice
4. compare the exchange rate for foreign currency on the invoice vs the payment entry

### Observed result

the exchange rate is different (actually it is fetched on the day you create the transaction in ERPNext, not the posting_date)

### Expected result

for transactions in a foreign currency on the same posting_date the exchange rate should be the same.

### Solution

I think ERPNext needs to send a GET request to the frankfurter app for the posting_date, not the current rate

**Comment by harshit-30** [comment]
Please create another issue if it is replicable after v13.10.
