### ISSUE TITLE
WooCommerce Integration: Shipping Address Missing

### ISSUE THREAD

**Issue by wrentedspace** [frappe/erpnext#21481]
Hello! I'm working on getting our woocommerce > ERPNext integration set up. It's working beautifully to pull items, customers, and sales orders through, but we also have a problem. Customers' addresses are not coming through properly. I can see their shipping address and billing address (which are different from each other) in WooCommerce on their sales order. However, when the information is imported into ERPNext, only the billing address comes through. I looked at the documentation for the woocommerce integration (this request, in particular: https://github.com/frappe/erpnext/pull/13217/commits/07444bf9262906ede935d3c97acfd0b7df2b4b2a) briefly and it seems like billing details are in the webhook information, but not shipping. The documentation on ERPNext website itself for this integration says "It also creates Address linked to the Customer using the **shipping details** from the order data." I would prefer this to be the case!

I do not have ERPNext server set up on a local machine, we are using the online version. Is there a good way to get BOTH the shipping and billing addresses to be automatically created in ERPNext from a WooCommerce transaction?

Thank you!

Attachment 1: WooCommerce order, with both billing and shipping addresses for customer
![image](https://user-images.githubusercontent.com/57203158/80513097-8def2000-894c-11ea-8dc0-cc27a4bb91ca.png)

Attachment 2: Matching ERPNext customer, generated by integration, with only billing address imported from sales order creation webhook
![image](https://user-images.githubusercontent.com/57203158/80512942-4bc5de80-894c-11ea-80b1-4bad020c7a14.png)

**Comment by scmmishra** [comment]
Solved with #21654
