### ISSUE TITLE
"Shipping rule" in invoices has stopped adding charges

### ISSUE THREAD

**Issue by zzecool** [frappe/erpnext#21507]
We noticed that in invoices if we select a "Shipping rule" there is no charge added in the "Sales Taxes and Charges" field as it used to.

I cant pinpoint when this started exactly but i can give you my running versions to check.

> ERPNext: v12.7.1 (version-12)
> ERPNext Support: v0.0.3 (master)
> Frappe Framework: v12.5.1 (version-12)
> Journeys: v0.0.1 (version-12)

Thanks in advance.

**Comment by SDLyu** [comment]
@zzecool do your party(should be customer) have shipping address? If not, add shipping address first and try again.

**Comment by marination** [comment]
https://github.com/frappe/erpnext/pull/22092 here is a fix. As @SDLyu  said, currently the shipping address is necessary.
