### ISSUE TITLE
[V12 bug] Homepage meta description field hidden

### ISSUE THREAD

**Issue by nameduser0** [frappe/erpnext#21514]
## Description of the issue
By default, ERPNext has the homepage description field set to:  

> This is an example website auto-generated from ERPNext

This field is used to set the html head meta tag: description amongst others. This tag is used by search engines for the website content shown on the search page, so is _vital_ for SEO.

However, if you change the `Hero Section Based On` field in Homepage settings, the description field is hidden from view, but is still used to populate the head tags on the homepage, including a meta property tag which is not overridable by setting meta tags separately.

## Context information (for bug reports)

**Output of `bench version`**
```
ERPNext: v12.7.1 (version-12)
Frappe Framework: v12.5.1 (version-12)
```
https://github.com/frappe/erpnext/blob/e4fca91792fa3eef49a947697f4ea2af7c6a0ca9/erpnext/templates/pages/home.py#L49

![Screen Shot 2020-04-29 at 17 59 26](https://user-images.githubusercontent.com/64409021/80624228-48f9e500-8a43-11ea-9dbd-17a9ca55d2a0.png)

## Steps to reproduce the issue

1. Change `Hero Section Based On` field in Homepage settings to `Homepage Section`

### Observed result
Description field is hidden

### Expected result
Description field should **always** be visible

**Comment by kennethsequeira** [comment]
@casesolved-co-uk can you check again after creating a route meta for the homepage:
https://docs.erpnext.com/docs/user/manual/en/website/website-route-meta

**Comment by nameduser0** [comment]
> @casesolved-co-uk can you check again after creating a route meta for the homepage:
> https://docs.erpnext.com/docs/user/manual/en/website/website-route-meta

This does not fix the meta property tag as I put in the bug report.

In any case, it's bad practice to hide the field that is used to control this essential homepage content.

**Comment by Anurag810** [comment]
#22119
