### ISSUE TITLE
Can't view the list of Tasks added in any project, but can access the individual tasks through direct links to the Task page

### ISSUE THREAD

**Issue by arhamlabs** [frappe/erpnext#21544]
## Description of the issue
As the title says.
Not sure what triggered this. 
E.g.: https://arhamlabs.erpnext.com/desk#List/Task/List shows up empty
But https://arhamlabs.erpnext.com/desk#Form/Task/TASK-2020-00168 is still accessible.

Additionally, Projects added have somehow stopped being visible (they were previously all visible). Adding the document to the User Permissions explicitly makes it visible, but this didn't need to be done earlier.

In either case, this workaround doesn't seem to work for Tasks. Tried adding explicity User Permissions for a task, but it doesn't make it visible. It's also not feasible to do this for every task added in every project. 

```
Version
ERPNext: v12.7.1 (version-12)
ERPNext Support: v0.0.3 (master)
Frappe Framework: v12.5.1 (version-12)
Journeys: v0.0.1 (version-12)
```

**Comment by kennethsequeira** [comment]
@arhamlabs since you're on erpnext.com, you're better off with the issue being solved via a support ticket.

Tasks are no longer visible in the project. This decision was taken long ago due to the sync breaking between the two.
