### ISSUE TITLE
Purchase Receipt

### ISSUE THREAD

**Issue by Rgottsch1** [frappe/erpnext#21557]
## Context information (for bug reports)

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1.
2.
3.

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by Rgottsch1** [comment]
Purchase Receipt not displaying get items button.  Cannot receive items on a PO.

**Comment by kennethsequeira** [comment]
@Rgottsch1 provide more information such as ERPNext and Frappe versions and traceback on the browser if any.

**Comment by kennethsequeira** [comment]
Closing the issue as no steps for replication provided.
