### ISSUE TITLE
v13-Invalid version string: '13.0.0.beta.1' on load

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#21558]
![image](https://user-images.githubusercontent.com/1822868/80858980-0d8b3080-8c66-11ea-983b-d58b73faf0a9.png)

The above happens after initial login, or after a reload.
If one one closes the error message, and clicks on refresh on the browser, the system loads as usual.

**Comment by surajshetty3416** [comment]
@muchai The issue has been fixed. Please update your branches.
https://discuss.erpnext.com/t/frappe-erpnext-version-13-0-0-beta-1-released/61088/17?u=surajshetty
