### ISSUE TITLE
Change Fiscal Year cycle to align with Calendar Year

### ISSUE THREAD

**Issue by zerodiscount** [frappe/erpnext#21553]
## Description of the issue
Companies may need to change their fiscal year cycles. In our case - the fiscal year cycle was Oct1-Sep30 and now the govt is mandating that all companies switch to calendar year cycle for 2021. When attempting to change fiscal year cycle in ERPNext - following are observed:

- Fiscal year cannot exceed or be less than 12 months. So creation of a fiscal year that is 15 months is not permitted. So Fiscal year End Date is meaningless as it automatically forces it to be 12 months from beginning date. 
- Fiscal years cannot overlap - cannot create new one - if not 12 months from previous. So closing a current fiscal year (2020 say) with PCV, disabling it and then creating a new year - that would begin from tomorrow (say) is not permitted - as it continues to recognize that old fiscal year extended till end date (in this case say Sep 30, 2020) 

Based on these restrictions, it seems not possible to change fiscal year to align with a new cycle.

## Context information (for bug reports)

**Output of `bench version`**
```
V12.7.1 (ErpNext), Frappe (5.x)
```

## Steps to reproduce the issue

1. Create new fiscal year - attempt to adjust end date <> 12 months
2. Close current fiscal year prematurely and attempt to create new fiscal year with overlap dates

### Observed result
Cannot align fiscal year to new cycle

### Expected result
Should be able to align fiscal year to new cycle - especially if mandated by law.

**Comment by kennethsequeira** [comment]
Should be fixed with https://github.com/frappe/erpnext/pull/23497
