### ISSUE TITLE
v13- Asset form dashboard and toolbar button not translatable

### ISSUE THREAD

**Issue by szufisher** [frappe/erpnext#21566]
## Context information (for bug reports)

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1.
2.
3.

### Observed result
![image](https://user-images.githubusercontent.com/12823863/80867965-fd0ca180-8cc9-11ea-95e5-4fd1edfba84f.png)

### Expected result
the highlighted label can be translated.

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by ankush** [comment]
https://github.com/frappe/erpnext/pull/28679
