### ISSUE TITLE
Chile Tax System - Tax Electronics Documents' Integration - Requesting Paid Development Quote

### ISSUE THREAD

**Issue by Belenox-ltda** [frappe/erpnext#21574]
## Chile Tax System - Tax Invoice Integration Request

I'm running an Instance of Community ERPNext and I want to use it fully as ERP in our business, for Sales, Management, Customer Support and Web Site integration. I'm from Chile and in the future I would like to offer ERPNext services and support in our country, as an ERPNext's partner...

I'm willing to support the development of a module that would allow us to integrate ERPNext to our country's Tax system, so it would be possible to issue valid Tax Documents in Chile through ERPNext, namely:
-Electronic Tax Invoices ("Factura Electrónica" in spanish in our country)
-Electronic Tax Credit Note ("Nota de Crédito Electrónica")
-Electronic Tax Debit Note ("Nota de Débito Electrónica")
-Electronic Delivery Order ("Guía de Despacho Electrónica")
-Electronic Tax Sales Slip ("Boleta Electrónica de Ventas")

You can find official information about our country's Tax Electronic Document's, validation system and technical docs here:
http://www.sii.cl/ayudas/ayudas_por_servicios/2004-instructivo-2007.html

Also there has been some posts by people interested in ERPNext integration with our local Tax Electronic Documents' System:
-https://discuss.erpnext.com/t/usuarios-erpnext-chile/58601
-https://discuss.erpnext.com/t/factura-electronica-chile/25258
-https://www.freelancer.cl/projects/website-design/factura-electr-nica-chile-para/

I can try to fund this development myself, but if I can't do it alone I can also gather a local community to help to get funds and support...

Finally, I'm also interested in the development of a Prestashop-ERPNext connector, and I can help with some funds to its development...

**Comment by martinhbramwell** [comment]
Desarrollé el primer sistema de software libre de eGobierno en América del Sur en 1999 para el Servicio de Rentas Internas del Ecuador como consultor del CIAT.

Hace un año desarrollé un servicio de firma y envío (al SRI) de documentos comerciales usando NodeJS. Ha estado en producción durante más de un año. Actualmente estoy escribiendo el código para la comunicación bidireccional entre el DocType de "Factura de Ventas" de ErpNext y el servidor NodeJs (incorporado en ErpNext) que ejecuta la aplicación de firma y envío desarrollada previamente.

Deseas conversar?  Te invito a contactarme por [mensaje privado](https://discuss.erpnext.com/u/MartinHBramwell/summary) en el foro.

---

Nota: ejemplo de [mi participación en el foro](https://discuss.erpnext.com/t/solved-curl-example-of-an-attachment-upload-rpc-call/61126/3?u=martinhbramwell) relevante a la mencionada "comunicación bidireccional"
