### ISSUE TITLE
v13-click breadcrumbs for module Accounting and Quality shows only empty page

### ISSUE THREAD

**Issue by szufisher** [frappe/erpnext#21570]
## Context information (for bug reports)

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1.go to desktop
2.click Accounting module, click e.g Journal Entry, create a new Journal Entry 
3. click the breadcrumbs link Accounting next to E logo

Same issue for Quality mudule

### Observed result
![image](https://user-images.githubusercontent.com/12823863/80913881-92676e80-8d7a-11ea-8e8f-6245624d3e6f.png)

### Expected result
show the module page as expected.
### Stacktrace / full error message

```
(paste here)
```

## Additional information
it is related to the desk page module name, for both accounting and quality, the corresponding module name is Accounts , quality management.

OS version / distribution, `ERPNext` install method, etc.

**Comment by scmmishra** [comment]
Thanks for reporting this, we’ll fix this soon with the next release

**Comment by szufisher** [comment]
After renamed the desk page, the issue resolved on my local instance
![image](https://user-images.githubusercontent.com/12823863/81026817-f63e8400-8ead-11ea-8590-e8cb1df8b426.png)

**Comment by scmmishra** [comment]
Fixed https://github.com/frappe/erpnext/pull/21734 and https://github.com/frappe/frappe/pull/10361

**Comment by scmmishra** [comment]
> After renamed the desk page, the issue resolved on my local instance

I would not suggest this, on next migrate the page will be created again, giving you two pages of the same
