### ISSUE TITLE
Creation of Service Team for maintenance visits

### ISSUE THREAD

**Issue by rasika2502** [frappe/erpnext#2157]
Please add an option to create a Service Persons Tree under Service Team (just like how we create a Sales Person Tree under Sales Team (thru the setup of Selling).

Thanks

**Comment by umairsy** [comment]
Closing as there has been no communication or demand from other users. As a work-around, you can add team as a child Sales Person. In the Sales Person master, you can add a child Custom Doctype of Sales Persons.
