### ISSUE TITLE
Year in Naming Series is not getting changed while posting entries in the previous year.

### ISSUE THREAD

**Issue by jalajjsingh** [frappe/erpnext#21596]
Hi, community.

Please guide.

Year in Naming Series is not getting changed while posting entries in the previous year.

It’s not throwing any error but it’s not working in the way the expected.
As we have year in naming series, so if we are making any entry, like sales invoice, in the previous year, say 2019, in naming series the year 2019 should be reflected, but it’s showing 2020 there.

Please post on our forums:

for questions about using `ERPNext`: https://discuss.erpnext.com

for questions about using the `Frappe Framework`: ~~https://discuss.frappe.io~~ => [stackoverflow](https://stackoverflow.com/questions/tagged/frappe) tagged under `frappe`

for questions about using `bench`, probably the best place to start is the [bench repo](https://github.com/frappe/bench)

For documentation issues, use the [ERPNext Documentation](https://erpnext.com/docs/) or [Frappe Framework Documentation](https://frappe.io/docs/user/en) or the [developer cheetsheet](https://github.com/frappe/frappe/wiki/Developer-Cheatsheet)

> **Posts that are not bug reports or feature requests will not be addressed on this issue tracker.**

**Comment by kennethsequeira** [comment]
Naming series picks the current year and not from the posting date. 

For older entries, consider making a new series with the year added.
