### ISSUE TITLE
Not able to reconcile credit note against pending sales invoice

### ISSUE THREAD

**Issue by anasanzari** [frappe/erpnext#21604]
Getting the error: "Please check Multi Currency option to allow accounts with other currency"

ERP Version: v12.5.2

![image](https://user-images.githubusercontent.com/7361062/81059982-a201c700-8ee2-11ea-8aa8-3b81a16ac295.png)

**Comment by deepeshgarg007** [comment]
@anasanzari This issue must be resolved now, closing this issue
