### ISSUE TITLE
[bug] payment entry Get Outstanding Documents button failed fetching the open orders to be billed if leave both the outstanding amount greater/lesser than

### ISSUE THREAD

**Issue by szufisher** [frappe/erpnext#21610]
## Context information (for bug reports)

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1. create a new PO and submit
2. create a new payment entry against the same supplier in the previous PO, input amount, click Get Outstanding Invoice button, in the popup window click Get Outstanding Documents button
3. if input proper greater / less than amount, the unbilled purchase order can be fetched as expected

### Observed result
![image](https://user-images.githubusercontent.com/12823863/81091112-54607b00-8f31-11ea-9e39-fcf28137efee.png)
![image](https://user-images.githubusercontent.com/12823863/81091173-6b9f6880-8f31-11ea-95ab-8043fde71f1a.png)

![image](https://user-images.githubusercontent.com/12823863/81091225-7c4fde80-8f31-11ea-8111-896f8482bb85.png)

frappe popup message : No outstanding invoices found for the supplier  xx which qualify the filters you have specified.
### Expected result
1. when no greater and less than amount specified all the unbilled purchase order can be fetched
2. the button label to be changed from Get Outstanding Invoice to Get Outstanding Document
### Stacktrace / full error message

```
(paste here)
```

## Additional information
the following code from method  get_orders_to_be_billed in payment_entry.py
```
if not (flt(d.outstanding_amount) >= flt(filters.get("outstanding_amt_greater_than"))
			and flt(d.outstanding_amount) <= flt(filters.get("outstanding_amt_less_than"))):
			continue
```

need to be changed something like 
```
outstanding_amt_greater_than =filters.get("outstanding_amt_greater_than")
outstanding_amt_less_than = filters.get("outstanding_amt_less_than")
if outstanding_amt_greater_than and  outstanding_amt_less_than and not (flt(d.outstanding_amount) >= flt(outstanding_amt_greater_than)
			and flt(d.outstanding_amount) <= flt(outstanding_amt_less_than)):
			continue 
```
OS version / distribution, `ERPNext` install method, etc.
at least for both v12 and v13.

**Comment by nabinhait** [comment]
fixed in v14
