### ISSUE TITLE
Change Bank Details and Logo on Invoices

### ISSUE THREAD

**Issue by Mcleansales** [frappe/erpnext#21629]
Hi, we need to change our logo and update our new bank details to our invoices etc.
Can you please tell me how to do this?
Thanks

**Comment by parsimonyERP** [comment]
I think you will get better and faster answers if you post this on [https://discuss.erpnext.com](https://discuss.erpnext.com)

**Comment by kennethsequeira** [comment]
@Mcleansales post on the forum as directed earlier.

Also add details of where you need the changes to be done and appear. It'll make it easier for users to assist you over this.

EDIT: also take a look at letterheads. This is probably what you're after: https://docs.erpnext.com/docs/user/manual/en/setting-up/print/letter-head
