### ISSUE TITLE
Multi-batch same item purchase receipt does not update PO correctly

### ISSUE THREAD

**Issue by cphoa28** [frappe/erpnext#21653]
## Description of the issue

1. PO created with 1 line item:  ITEM-001.  Item is batch controlled.
 
     PO..| Line Item No...| Item Code |...Qty... |...Received Qty
     123.|........1...................| ITEM-001 ..|..1000..| ...... 0
 
2. Create Purchase Receipt, line item has to be split into 2 because ERPNEXT does not allow multi-batch receipts for same line item.

     Receipt ..| line item no.. | Item Code .| Qty | Batch
     abc .........| .....1 ...................| ITEM-001 ...| 300 | batch-001
     abc .........| .....2 ...................| ITEM-001 ...| 700 | batch-002

3.  Purchase Receipt is successful, however, PO received qty is not updated correctly.  Only the 1st line item in the purchase receipt was subtracted.  Furthermore, PO is in partially received state instead of completed.
 
     PO..| Line Item No...| Item Code |...Qty... | ...Received Qty
     123.|........1...................| ITEM-001 ..|..1000.. | ....   300   ===> incorrect.  Should be 1000.  
 

## Context information (for bug reports)
n/a

**Output of `bench version`**
```
Tested on:
ERPNext: v11.1.44 (master)
Frappe Framework: v11.1.39 (master)

Also on:
ERPNext: v12.6.0 (version-12)
Frappe Framework: v12.4.1 (version-12)
```

## Steps to reproduce the issue

1.  Create PO with 1 line item
2.  Create Purchase Receipt with 2 batches

### Observed result
PO line item qty is only partially received even though purchase receipt was for entire qty but split between 2 batches.

### Expected result
PO line item qty should be completely received

### Stacktrace / full error message

```
No error messages
```

## Additional information
Ubuntu 16.04.5 LTS on Digital Ocean Droplet

**Comment by cphoa28** [comment]
Dear ERPNEXT TEAM:  BUmp Up.

The same issue happens on Delivery Note.  If there is a line item that needs to use multiple batches to fulfill the qty, ERPNEXT only updates the Sales Order with the 1st Batch and ignores the rest of the batches.  The Sales Order looks partially fulfilled but in fact it is completely fulfilled.

I believe this should be a major bug.  Using multiple Purchase Receipts or Multiple Delivery Notes just because there are multiple batches is not really a viable workaround (imagine if you have 30 line items on a PO or SO!!).  

Actually the real fix should be to allow multi-batch support for Purchase Receipt and Delivery Note.  As it is, it is already a workaround to break up a line item into multiple duplicate lines just so that we can fill in the different batch numbers.  

Please help!  Customer is suffering this as the workaround is very manual (multi Purchase Receipt and Delivery Notes!)


Chris

**Comment by marination** [comment]
@cphoa28 Hey Chris, this is a known issue that needs a better designed solution that we haven't arrived at yet. Although your case can still be handled, allow me to explain:
- Assume a PO with 3 line items. Each of the rows in the items table has a unique id that isn't visible to the user.
- When you create a Purchase Receipt from this PO, the row or line item is mapped into the Receipt, along with this unique id. Thats how the Receipt knows which row was received.
- If you split this row my merely adding a new row, this id reference is lost.

The best solution here is to **duplicate** the row you are splitting. In this way all the references to the PO are pulled or duplicated into the new row. This will correctly update the Purchase Order.
So avoid **Add Row**, go for **Duplicate** within the row.

As for avoiding manual work, we do understand, we will try to come up with a better approach towards this use case.

**Comment by cphoa28** [comment]
@marination 
This is a confirmed workaround from Procurement Side.  Will test on Sales Side ( Del Note and Sales Invoice with update stock checked against SO).  Super thanks!!!

Chris
