### ISSUE TITLE
No module named 'frappe.core.page.dashboard.dashboard'

### ISSUE THREAD

**Issue by centaur78** [frappe/erpnext#21664]
Hi

Latest update to develop branch getting module not found error for dashboard

![dashboard error](https://user-images.githubusercontent.com/1904802/81431732-b65bf300-9172-11ea-9676-73670ef3d31f.png)

**Comment by centaur78** [comment]
> @centaur78 [This PR](https://github.com/frappe/erpnext/pull/21618) will fix the issue.

Yes @surajshetty3416 I have seen the PR ....but that's 3 days old. I just now did a bench update --reset for added measure along with bench clear-cache as well

Error still the same....

**Comment by surajshetty3416** [comment]
@centaur78 That PR has been merged now... Please try again!

**Comment by centaur78** [comment]
Thanks @surajshetty3416 

The [merged PR](https://github.com/frappe/erpnext/pull/21618), resolved the issue ..  Closing this issue now
