### ISSUE TITLE
[feature request] "update stock" check on purchase invoice

### ISSUE THREAD

**Issue by elevationO** [frappe/erpnext#2168]
An option to update inventory immediately upon the submitted purchase invoice just like sales invoice.

**Comment by jof2jc** [comment]
My idea:
1. Not just "update stock" option...can we add also payment option like on sales invoice? in case we do cash payment for the purchase.
2. May be, POS Profile for purchase invoice might be useful for this case,like POS Invoice.

**Comment by jof2jc** [comment]
Any update on this pls? Tks

**Comment by jof2jc** [comment]
Is there any updates for this issue?
