### ISSUE TITLE
[Feature Request] Making Tax Digital for Income Tax (UK Self-Assessment)

### ISSUE THREAD

**Issue by nameduser0** [frappe/erpnext#21694]
### [Pledge your support for this project here!](https://www.casesolved.co.uk/products/erpnext-features/erpnext-ukincome)
**This integration will allow ERPNext to be published as HMRC Recognised Software on their website.**
## Pre-requisites
Frappe general purpose OAuth2 client

## Feature Goals (Use cases & Requirements)
Around 2021 it is expected that the current Self-Assessment tax return will be replaced with a Making Tax Digital interface like for VAT. The new self-assessment interface will be large and complicated, unlike the VAT interface which is relatively straight-forward by comparison. Here's a brief overview of the interface:

1. View and submit self-assessment income and expenditure with HMRC (Self Assessment API):
    i. Self-employments (sole traders)
    ii. UK property & holiday lettings
    iii. Dividends
    iv. Savings Account interest
    v. Charitable giving
    vi. Final submission
2. Trigger and view Income Tax and National Insurance calculations based on submitted data (Individual Calculations API)
3. View an income tax account including balance, transactions, charges & payments
4. View income and expenditure summaries for specific tax years
5. View and submit brought-forward losses and claim against them
6. View and submit adjustments to previous year assessments

Income for employed individuals is submitted by their employers through PAYE using the RTI interface, so this is not applicable.

### Minimum viable product
The Government Gateway currently provides a lot of the functionality listed above. Due to this support and that we expect a large proportion to only use the basics, the MVP is proposed as items 1 & 2.
The functionality will initially be aimed at Directors, Self-employed and PAYE-employed people with additional items to declare. Other entities such as partnerships and trusts will not initially be covered.

### ERPNext considerations:
- All necessary income and expenditure accounts must be set up in the Chart of Accounts
- Accounting Dimensions should be used to break figures down further, for example to signify allowable and disallowable amounts
- The report must draw its values from General Ledger entries so as to include correcting Journal Entries
- Should use a similar design pattern to MTD for VAT (#21233)

### Recommendations
- Tax ID should be changed to a child doctype to allow Companies to have multiple alphanumeric IDs of different categories, e.g. Company Registration, Government ID, Goods and Services Tax, Income Tax, Corporate Tax, Social Insurance Tax, Customs Tax, Excise Tax. It could be possible for a single company to have multiple IDs of the same type

## Additional DocTypes and fields (with fieldtype, etc) if any
Doctype | Section | Field | Type | Mandatory | Details
-- | -- | -- | -- | -- | --
Company | HMRC Settings | NINO | 9-char Alphanumeric | No | National Insurance number
HMRC Allowable | None | None | None | No | DocType to be used as an accounting dimension. Needs no fields, just a name. Just one entry required: Disallowable. The default should be blank. A tabSingle DocType didn't work
CoA Map |   | Name | Text | Yes | Auto name format: {Title} - {Company Abbrev}
CoA Map |   | Title | Text | Yes | Free-form name. Allows you to specify multiple maps for any purpose if required
CoA Map |   | Company | Link | Yes | Links to a company and allows you to filter the accounts for selection, see further down
CoA Map |   | Purpose | Select | Yes | VAT, Self Employment, Property, Dividends, Savings Interest, Charity. This doctype can be used by other functionality that needs to map the CoA for output in another format. The module that adds the Purpose select option, also knows the output format
CoA Map |   | Fields | Table | Yes | The field mappings
CoA Map Field |   | Name | Text | Yes | Random value
CoA Map Field |   | Parent | Link | Yes | CoA Map Name
CoA Map Field | Chart of Accounts | Account | Link | No | Link to CoA account. Optional because when first created, the map won't have a value here. Also you may not have values for every output field but might want to preserve the whole map for the future
CoA Map Field | Accounting Dimensions | Section (multiple fields) | Link | No | A whole section of Dimensions & filter values using standard ERPNext functionality.If blank, no dimension filters are applied to obtain the value
CoA Map Field | Output Field | Map Section | Text | No | Depends on the application, but MTD - Income Tax would have income and expense sections
CoA Map Field | Output Field | Map Field | Text | Yes | The output field name

## Discovery (how will the user find the feature you are building)

- Chart of Accounts - View menu: HMRC Self-assessment
- Accounting -> Taxes -> HMRC Self-assessment
- Accounting -> Taxes -> Connect to HMRC
- Company -> Tax ID / Registration
- User -> Third Party Authentication

(Maybe also in Integrations for ease of discovery)

## Screen Mockups with buttons and any custom UI (TBD)
- HMRC user permissions definition (scopes); also used as auth fail destination
- (OAuth2 Authorisation flow: out-of-scope)
- Report page that invokes the mappings to generate assessment values for submission. There will be buttons to pre-populate each type of CoA Map with all the necessary Title, Purpose, Map Sections and Fields for a specific CoA/Company
   - Button to navigate to the map for Account & Dimension filter completion
   - Button to run the report
- View previous self-assessment submissions
- Trigger & view Income Tax calculations

### Validations
HMRC OAuth2 Provider existence
### Calculations
Reports
### Logs
None

## Links to existing DocTypes
See table above

## Reports
Custom - Summing journal entries over a specific period according to the CoA maps and filters. See screen section above

## Rationale
Although there could be a lot of data, the reporting requirements are fairly simple, but do need to be fairly flexible to cater for differing requirements and complexities of return.
The CoA Map functionality has been designed to be reusable for other purposes, for example to create custom reports which can be exported to csv from the CoA.
[More information from HMRC](https://www.gov.uk/self-assessment-tax-returns)

**Comment by nameduser0** [comment]
@deepeshgarg007  Hi Deepesh, as an accounting maintainer could you review the proposal please?

**Comment by harshit-30** [comment]
@casesolved-co-uk assuming you have already implemented this, we can close this too?

**Comment by nameduser0** [comment]
If anyone is interested in this feature, please head over to [www.casesolved.co.uk](https://www.casesolved.co.uk) and get in touch
