### ISSUE TITLE
Issue in creating a PO from a SO

### ISSUE THREAD

**Issue by rajatkhandeparkar007** [frappe/erpnext#21696]
1.Create a SO.
2.Create -> PO 
3.Pops up a dialog box to select supplier(Help text: Leave blank to create sales order to all suppliers)

Issues:
1.Supplier is manadatory.
2.Supplier drop down doesnt list the suppliers present in the system

**Comment by deepeshgarg007** [comment]
The supplier field is removed now, closing this issue
