### ISSUE TITLE
[Feature Request] UK Corporation Tax & Companies House return

### ISSUE THREAD

**Issue by nameduser0** [frappe/erpnext#21695]
#### [Pledge your support for this project here!](https://www.casesolved.co.uk/products/erpnext-features/erpnext-company-tax-annual-return-feature)
**This integration will allow ERPNext to be published as HMRC Recognised Software on their website.**

It may be beneficial for some UK businesses to be able to submit their CT600 and Companies House figures directly from ERPNext

HMRC has an [XML API](https://www.gov.uk/government/collections/corporation-tax-online-support-for-software-developers) for this purpose

You are already able to submit these returns via the HMRC Government Gateway, so the functionality may not prove to be desirable.

Comments welcomed!

**Comment by harshit-30** [comment]
Hi @casesolved-co-uk, what are the steps to get published on their website? 
Provide us with an example of what steps one can take to get these reports/figures generated.

**Comment by nameduser0** [comment]
> Hi @casesolved-co-uk, what are the steps to get published on their website? Provide us with an example of what steps one can take to get these reports/figures generated.

This is now an internal project here at [www.casesolved.co.uk](https://www.casesolved.co.uk) Our MTD VAT module is already HMRC Recognised and will be listed on their website soon. Thanks for your interest!
