### ISSUE TITLE
Inconsistent Purchase Process with field Project

### ISSUE THREAD

**Issue by wojosc** [frappe/erpnext#21707]
I have noticed an inconsistency in the design of DocTypes in purchase process. The subtables (...Item) of the following DocTypes are effected:

- Material Request
- Supplier Quotation
- Purchase Order
- Purchase Invoice

Material Request
![grafik](https://user-images.githubusercontent.com/22279621/81784535-4bf1dc80-94fd-11ea-8031-0c6b9cb78c59.png)

Supplier Quotation
![grafik](https://user-images.githubusercontent.com/22279621/81784377-0cc38b80-94fd-11ea-8a6d-88e40d81162e.png)

Purchase Order
![grafik](https://user-images.githubusercontent.com/22279621/81784148-bbb39780-94fc-11ea-9104-e58f4dc1503d.png)

Purchase Invoice
![grafik](https://user-images.githubusercontent.com/22279621/81784904-df2b1200-94fd-11ea-9b69-d024e04c2e0a.png)

As you can see we have sections
Acccount, Accounting Details and Accounting Dimensions which are all more or less similar.

We work alot with the the link-field Project and it feels you have to look for it in a different place everytime.

Please advise on which direction we should go. I'm happy to do the clean up once you let me know which way should be heading or if I'm missing something here. Thanks.

**Comment by deepeshgarg007** [comment]
@wojosc I checked this on the latest version-14 release and the project field in the child tables is under the accounting dimension section. This seems to be solved during one of the cleanups hence closing this issue
