### ISSUE TITLE
Access to fetch at 'http://192.168.1.128/desk' from origin 'null' has been blocked by CORS policy: 

### ISSUE THREAD

**Issue by ChefWu551** [frappe/erpnext#21706]
Hi developers,
    I am so confuse this problem. 
    My erp next is work fine in localhost:
![image](https://user-images.githubusercontent.com/33725817/81782409-58d9f480-952c-11ea-98cd-ba868b9c8020.png)

    But when I fetch the resources it was confuse me, can any way to avoid Cross domain？ please.
![image](https://user-images.githubusercontent.com/33725817/81782322-3a73f900-952c-11ea-8782-bb8f37da584e.png)

   In this page it work:
![image](https://user-images.githubusercontent.com/33725817/81783673-41037000-952e-11ea-9688-f81cbfe0e2db.png)

**Comment by kennethsequeira** [comment]
@ChefWu551 you probably should post this on the [user forum](https://discuss.erpnext.com). There are already multiple threads addressing similar issues.
