### ISSUE TITLE
v12.8.0 "Accounts Payable" - "Payment Term"

### ISSUE THREAD

**Issue by franciscobuendiao** [frappe/erpnext#21722]
## Description of the issue
Clicking on "Based On Payment Terms" only add a blank column.
## Context information (for bug reports)

**Output of `bench version`**
```
ERPNext: v12.8.0 (version-12)
Frappe Framework: v12.5.2 (version-12)
```

## Steps to reproduce the issue

1. "Accounts Payable" report at Accounting
2. Clic on "Based On Payment Terms"
3. Add a blank column, no data

### Observed result
![Account](https://user-images.githubusercontent.com/25084259/81875763-9ba8c600-9546-11ea-9561-9cada35fe319.jpg)

**Comment by deepeshgarg007** [comment]
<img width="1315" alt="image" src="https://user-images.githubusercontent.com/42651287/197682770-1f755329-6605-4182-9f69-5e4e35b6fae4.png">

Works in the latest version, closing
