### ISSUE TITLE
EDI Integration in ERPNext

### ISSUE THREAD

**Issue by jaichavan** [frappe/erpnext#21735]
More information: https://www.ibm.com/in-en/supply-chain/edi-electronic-data-interchange?p1=Search&p4=43700052661678551&p5=b&cm_mmc=Search_Google-_-1S_1S-_-AS_IN-_-%2Bedi_b&cm_mmca7=71700000065070056&cm_mmca8=kwd-20090948177&cm_mmca9=EAIaIQobChMItqDEv4-06QIVjjgrCh3VUgo1EAAYASAAEgKg6fD_BwE&cm_mmca10=427884865599&cm_mmca11=b&gclid=EAIaIQobChMItqDEv4-06QIVjjgrCh3VUgo1EAAYASAAEgKg6fD_BwE&gclsrc=aw.ds

Ref: #OPP-20-21-01252

**Comment by 2xhp** [comment]
Having EDI built into ERPNext would be a major advantage for companies looking at adopting a new ERP.

**Comment by barredterra** [comment]
For reference, there's already [this](https://github.com/frappe/erpnext/blob/a7f42f72565ef1e47629101cabb0ad5e57c62d71/erpnext/regional/italy/e-invoice.xml) for Italy and [this](https://github.com/libracore/erpnextswiss/tree/d6a149233ef80006e9d6a7b15ee9989a8b87e0de/erpnextswiss/erpnextswiss/zugferd) (custom app) for Switzerland.
