### ISSUE TITLE
DEBTORS PAYMENT ANALYSIS REPORT

### ISSUE THREAD

**Issue by abimu** [frappe/erpnext#21755]
We request you to consider adding this attached report in forth coming release 
[Payment analysis.pdf](https://github.com/frappe/erpnext/files/4640704/Payment.analysis.pdf)
[Payment analysis.pdf](https://github.com/frappe/erpnext/files/4640725/Payment.analysis.pdf)

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.
