### ISSUE TITLE
Bank Reconciliation Issues

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#21757]
Basically, there are 2 issues here:

1. The Bank Statement Transaction Entry form (under the Bank Statement section) looks like it’s not finished yet as it doesn’t successfully create any Bank Transactions. If the feature actually isn’t completed, it should be hidden for now

2. The regular Bank Reconciliation tool seems to be conflicting with the Bank Reconciliation form (Update Bank Transaction Dates) under the Banking and Payments section. The tool doesn’t appear anywhere in the Accounts module; you can only access it via the search bar by selecting ‘Open Bank Reconciliaation’

This needs to be fixed as it causes confusion for users trying to do their Bank Reconciliation

Thanks

**Comment by olamide2** [comment]
This is still outstanding in v13 beta

I get the following error message when I try to click on it

![image](https://user-images.githubusercontent.com/23294026/84750121-cf966180-afb2-11ea-9537-8b788374db9c.png)

**Comment by federicocalvo** [comment]
same here!
