### ISSUE TITLE
Get Outstanding Invoice on Payment Entry gets even Credit Notes

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#21766]
Is this the expected behavior, Orr a bug?

**Comment by barredterra** [comment]
Please use the forum at https://discuss.erpnext.com to ask for help.

**Comment by muchai** [comment]
> Please use the forum at https://discuss.erpnext.com to ask for help.

Sure, did so then. However, in this case this was being reported as a bug.

**Comment by barredterra** [comment]
For a bug report, please provide more information about the error and how to reproduce it. A single sentence is usually not enough to get an idea of where the problem lies and how it could be solved. ;)
