### ISSUE TITLE
Same Batch Number for Multiple Items 

### ISSUE THREAD

**Issue by suspatel** [frappe/erpnext#21810]
We are medicine manufacturer,  we manufactures medicine in two phases 1. We prepare batch first, lets assume 100 kg Glucose we allot a batch Number GL01, from this batch in second step we fill several packing sizes  which are finish product like 50gm , 100gm , 200gm... Now we wants to allote same batch number GL01 to all these different packing . BUT IT IS NOT POSSIBLE, is there any solution?

**Comment by TurkerTunali** [comment]
We can create 2 possible workarounds.
1- You may give batch numbers like "GL01-1", "GL01-2", "GL01-3", etc.
2- You may create a "Batch Group" doctype to group several batches in one group. You can also generate batch names based on Batch Group Name. You may select batches in transactions (Stock Entry, Delivery Note, etc) but you can get reports based on Batch Group ID.
Regars.

**Comment by barredterra** [comment]
Closing this for now. Please use the forum at https://discuss.erpnext.com to ask for further help or create a feature request if any particular functionality is still needed.
