### ISSUE TITLE
NameError: name ‘patient’ is not defined /appointment/Healhtcare module. 

### ISSUE THREAD

**Issue by setsero71** [frappe/erpnext#21813]
Hi everyone.

# Description of the issue
 When trying to make my first appointment, at the moment of saving I get this error:

NameError: name ‘patient’ is not defined /appointment/Healthcare module. 

Fresh installation of:
ERRPNext: v12.8.0 (version-12)
Frappe Framework: v12.5.2 (version-12)`

### Observed result
Mentioned error

![Screen Shot 2020-05-20 at 10 09 43 AM](https://user-images.githubusercontent.com/63762057/82466596-a1defb00-9a8e-11ea-94d0-1c86744045f0.png)

### Expected result
Saved

# Additional information
Ubuntu 18.04 LTS server. Easy install method.

**Comment by ruchamahabal** [comment]
This had been fixed in: https://github.com/frappe/erpnext/pull/21429
Closing the issue
