### ISSUE TITLE
Permission Issues on Asset Creation

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#21847]
Hi ,

There are permission errors popping up when a user tries to create an Asset 

1. Creating via Purchase Receipt gives an error like "Not allowed for Company: None. Restricted field: asset_owner_company. User xxxxxxx does not have access to this document. Insufficient Permission for Asset"

2. Creating an Asset directly gives a similar error at the point of submission but this time the Insufficient Permission is for Asset Movement (at Row 1)

The work around is to delete User Permissions that restrict the User to their Company in the Asset and Asset Movement doctypes

Pls help fix 

Thanks

**Comment by deepeshgarg007** [comment]
@Olawale1 Please mention the version of the issue and reopen a new issue if this is still happening in the latest version-13 release or higher versions
