### ISSUE TITLE
Rolling reports

### ISSUE THREAD

**Issue by drthilina** [frappe/erpnext#21888]
Hello Devs,
  I would like to propose to have Rolling reports in ERPNext. Rolling reports will allow time criteria to be selected like "this month", "last month", "last quarter, "Today" or a range between "today" and "last 7 days".

Since **Report Builder** is already there, I believe it would be logical to add only the syntax

![image](https://user-images.githubusercontent.com/29944021/82731882-67dc5600-9d27-11ea-9c92-c06071c74a9e.png)

 
or like

![image](https://user-images.githubusercontent.com/29944021/82731864-43807980-9d27-11ea-8be8-a0a00affc6b9.png)

Cheers if this helps to further improve ERPNext

**Comment by mhbu50** [comment]
@drthilina This done in this PR:

https://github.com/frappe/frappe/pull/10463
