### ISSUE TITLE
[bug]chart of accounts importer via excel with number

### ISSUE THREAD

**Issue by szufisher** [frappe/erpnext#21885]
## Context information (for bug reports)

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1. run chart of accounts importer, download template
![image](https://user-images.githubusercontent.com/12823863/82725520-0ceb3480-9d10-11ea-8a16-5e25e4180dcd.png)

2. click import

### Observed result
![image](https://user-images.githubusercontent.com/12823863/82725497-f3e28380-9d0f-11ea-985c-08eb41790d1c.png)

### Stacktrace / full error message

```
(paste here)
```

## Additional information
![image](https://user-images.githubusercontent.com/12823863/82725547-47ed6800-9d10-11ea-9f6f-244fe8685916.png)

to-be changed as 
![image](https://user-images.githubusercontent.com/12823863/82725538-31471100-9d10-11ea-83c8-359af75fa837.png)

OS version / distribution, `ERPNext` install method, etc.

**Comment by clarkejj** [comment]
See also https://discuss.erpnext.com/t/account-number-is-not-shown-in-balance-sheet-or-trial-balance/42197/6

**Comment by deepeshgarg007** [comment]
@szufisher Reopen a new issue if it still persists in latest v13 release, mostly this is fixed by now
