### ISSUE TITLE
bug: Unable to select payroll period in employee tax exemption declaration

### ISSUE THREAD

**Issue by govindsmenokee** [frappe/erpnext#21926]
## Context information (for bug reports)

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1.
2.
3.

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by kennethsequeira** [comment]
Working on both latest v13 and 12 builds.

Closing as no further description or details have been provided, and the issue is not replicable.
