### ISSUE TITLE
Bulk Action does not trigger Custom Scripts

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#21931]
Hi ,

Bulk Actions don't seem to trigger custom scripts. For example, I have a custom script that’s triggered before Submit of a custom doctype and it works fine when the docs are submitted individually. It however appears that Submitting multiple docs via bulk action in list view doesn’t trigger the custom script! 

Pls help fix

Kind regards,

**Comment by kennethsequeira** [comment]
Custom scripts run when an action is performed on the 'front-end'. This can be solved by writing a server-side script to do the same action.
