### ISSUE TITLE
Blank BOM Doctype/page

### ISSUE THREAD

**Issue by miccolo2020** [frappe/erpnext#21944]
After editing my BOM (Bill of materials Docttype), i noticed i was having a blank page or blank doctype. What could be the issue?

**Comment by kennethsequeira** [comment]
@miccolo2020 

was the issue resolved? 

What steps did you take to edit the BOM?

**Comment by kennethsequeira** [comment]
@miccolo2020 

was the issue resolved? 

What steps did you take to edit the BOM?

**Comment by miccolo2020** [comment]
I have not been able to yet. It just shows a blank page.

**Comment by kennethsequeira** [comment]
@miccolo2020 please share the steps taken so the issue can be replicated/confirmed by members.

**Comment by miccolo2020** [comment]
> @miccolo2020 please share the steps taken so the issue can be replicated/confirmed by members.

i havent being able to resolve it. Can someone share the answers?

**Comment by deepeshgarg007** [comment]
@miccolo2020 Please elaborate on the issue and open a new issue with replicable steps
