### ISSUE TITLE
File name issue with special characters from imap

### ISSUE THREAD

**Issue by backendoadmin** [frappe/erpnext#21964]
We got some attachment from a partner who use Windows and special hungarian characters in filenames. As you can see on this screenshot ERPNext rename it, or sometimes crop the end of the filename (some letters form the end and the extensions are missing in this case). There is no issue, if we upload these files from local computer to ERPNext directly, but if we use imap to handle those emails with attachment the problem occurs.

I tried to create similar file on my machine, but I dont use Windows, so I cannot reproduce this kind of files and the original files are confident so I cant publish them.
![before](https://user-images.githubusercontent.com/5338127/83014561-3f9e7100-a01f-11ea-83ac-63a61de8c280.jpg)

**Comment by backendoadmin** [comment]
It works for me, could you guys merge it or give us feedback, please? 
![after](https://user-images.githubusercontent.com/5338127/83057051-abe89700-a056-11ea-8f74-004f386ce7b5.jpg)

**Comment by wojosc** [comment]
Hi @Muvuk I can see, that your PR is in the right place. Please concider moving your issue to also frappe/frappe instead of erpnext.

Thank you.

**Comment by backendoadmin** [comment]
Thank you for the notice @wojosc 
I think I dont have rigths to do that, there is no transfer option at my side:
https://help.github.com/en/github/managing-your-work-on-github/transferring-an-issue-to-another-repository

Could you transfer it, please? Or should we create a new one?

Thank you.

**Comment by wojosc** [comment]
same here, I do not have any permissions to do that. Best you create a new one and reference it here with the URL when you close this one.

Regards.

**Comment by backendoadmin** [comment]
Moved to https://github.com/frappe/frappe/issues/10544
