### ISSUE TITLE
"Patient Encounter" can be changed to "Patient Consultation".

### ISSUE THREAD

**Issue by mujeerhashmi** [frappe/erpnext#22053]
@ruchamahabal 

The word **"encounter"** is not very appropriate. In a good sense it is to meet unexpectedly but otherwise is a hostile meeting. check the meaning [here](https://www.thefreedictionary.com/encounter). I feel in the context of healthcare it will not be appropriate to use this terminology. We can use **"consultation"** or anything better than this in version-13.

https://github.com/frappe/erpnext/blob/6a93feb9d227a05bf6647fa62c96aabbefc817ce/erpnext/healthcare/doctype/patient_encounter/patient_encounter.json#L334

**Comment by ruchamahabal** [comment]
@mujeerhashmi Yes I get your point but it's a standard term used in the healthcare industry. You can also check other healthcare ERPs. Also, it is the term documented in the HL7 standards. 


Encounter
--
Definition | An interaction between a patient and healthcare provider(s) for the purpose of providing healthcare service(s) or assessing the health status of a patient.

You can check it here: https://www.hl7.org/fhir/encounter-definitions.html

**Comment by mujeerhashmi** [comment]
I get it. Thanks for the references. Do we follow these standards for implementation in ERPNext ?

**Comment by ruchamahabal** [comment]
Yes we do. The module is not completely HL7 compliant but we will work towards it.

**Comment by mujeerhashmi** [comment]
> Yes we do. The module is not completely HL7 compliant but we will work towards it.

Cool. Keep going.
