### ISSUE TITLE
Request timeout error when I try to save an auto repeat doc

### ISSUE THREAD

**Issue by suhanaayisha** [frappe/erpnext#22052]
Description of the issue:

I am not able to edit or make any changes to any document in auto-repeat list. When I try to save a change, the system freezes, and I get a request timed out error.

## Context information (for bug reports)

**Output of `bench version`**
Erpnext :12.5.2
Frappe 12.3.0

## Steps to reproduce the issue

1. Go to Auto-Repeat list.
2. Select any one document from the list.
3. Edit any field, for example, edit the end date and try to save the doc.

### Observed result
<img width="1440" alt="Screen Shot 2020-05-30 at 10 34 40 AM" src="https://user-images.githubusercontent.com/31471461/83321496-2d137a00-a261-11ea-9dc3-231847a78478.png">
<img width="1440" alt="Screen Shot 2020-05-30 at 10 46 38 AM" src="https://user-images.githubusercontent.com/31471461/83321767-00606200-a263-11ea-9239-170de8a0dfa4.png">

### Expected result
I would want it be to actually saved. Right now you can see that it is not saved.
<img width="1440" alt="Screen Shot 2020-05-30 at 10 36 59 AM" src="https://user-images.githubusercontent.com/31471461/83321540-8085c800-a261-11ea-8704-c3d84cbb3f97.png">

### Stacktrace / full error message
<img width="676" alt="Screen Shot 2020-05-30 at 10 36 23 AM" src="https://user-images.githubusercontent.com/31471461/83321523-6b109e00-a261-11ea-98c8-96f3fe221078.png">

**Comment by ruchamahabal** [comment]
Please update your branch to the latest instance of v12. This issue had been fixed in https://github.com/frappe/frappe/pull/10237
