### ISSUE TITLE
Add to cart button missing on v12.9.1

### ISSUE THREAD

**Issue by brian700** [frappe/erpnext#22061]
Hi, i have been listing items on website, enabled shopping cart, set default price list and website warehouse but noticed add to cart button is missing. It was working fine in v11, but after an upgrade, it seems not to disappear. anyone facing this too?
![image](https://user-images.githubusercontent.com/21196836/83339508-46efa400-a2d7-11ea-840b-f521607d54e4.png)

**Comment by marination** [comment]
https://github.com/frappe/erpnext/pull/21903 fixed
