### ISSUE TITLE
Return Sales Invoice cannot be allocated against another Sales Invoice as Credit

### ISSUE THREAD

**Issue by Mitchy25** [frappe/erpnext#22076]
Here is the situation:

1. Customer purchases goods and we record the sale as a Sales Invoice
2. Customer pays for the Sales Invoice in full (E.g. $100)
3. Customer comes back and wants to return an item on the original Sales Invoice (E.g. $25)
4. We issue a partial return on the original invoice (If we get the stock back from them, we select 'Update Stock' else we leave it unticked)

Now when that customer comes back, they wish to use this credit of $25, but it does not allow me to use this Original Invoice as a credit.

The original Sales Invoice has a negative outstanding amount but this is unable to be allocated against any other order.

**Comment by marekzada** [comment]
This would be a welcome feature, application of a credit to **any** open sales invoice. Not just the one it was created from.

**Comment by deepeshgarg007** [comment]
@Mitchy25 You can allocate credit notes against invoices using the payment reconciliation tool, this feature is already there
