### ISSUE TITLE
No Company Selectable in create child - Chart of Accounts - Accounts Tree

### ISSUE THREAD

**Issue by shalinw** [frappe/erpnext#22083]
### **Version 13 Beta 2**
While Creating a New Child in COA, you cant see a Company under which this Child Ledger is to be made, Even the Accounts Tree Does not show Any Company

## Context information (for bug reports)

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1. Go to COA
2. Select Add Child 
3. 

### Observed result
You cant select a Company
### Expected result
Dropdown should contain All Companies in the Site
### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.
![Screenshot_6](https://user-images.githubusercontent.com/66329921/83558208-4bfb6000-a530-11ea-9c23-f71d56ddbbd3.jpg)
![Screenshot_7](https://user-images.githubusercontent.com/66329921/83558215-4e5dba00-a530-11ea-8259-a611519eb413.jpg)

**Comment by kennethsequeira** [comment]
Working correctly with latest beta (4)

![image](https://user-images.githubusercontent.com/33246109/90156141-bf7be200-dda9-11ea-9257-5b570e30a55a.png)
