### ISSUE TITLE
Only E Icon after updating to erpnext 13.0.0-beta.2

### ISSUE THREAD

**Issue by setsero71** [frappe/erpnext#22084]
After updating to 
erpnext 13.0.0-beta.2
frappe 13.0.0-beta.2

After logged successfully, on the website view I got some functionalities but in the desk option only got the E icon. 

Error found in on the console:

[Error] Viewport argument key "minimal-ui" not recognized and ignored. (desk, line 13)
[Error] ReferenceError: Can't find variable: Driver
	Global Code (desk.min.js:1:606991)
[Error] TypeError: undefined is not an object (evaluating 'frappe.templates')
	(anonymous function) (list.min.js:1)
	Global Code (list.min.js:1:154252)
[Error] TypeError: undefined is not an object (evaluating 'frappe.templates')
	(anonymous function) (form.min.js:1:235)
	Global Code (form.min.js:1:721033)
[Error] TypeError: undefined is not an object (evaluating 'frappe.ui')
	(anonymous function) (control.min.js:1:44449)
	Global Code (control.min.js:1:625295)
[Error] TypeError: undefined is not an object (evaluating 'frappe.views.Factory')
	(anonymous function) (report.min.js:1:6485)
	Global Code (report.min.js:1:165684)
[Error] TypeError: frappe.provide is not a function. (In 'frappe.provide("erpnext")', 'frappe.provide' is undefined)
	(anonymous function) (erpnext.min.js:1)
	Global Code (erpnext.min.js:1:154467)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (awesomplete.min.js.map, line 0)

### Stacktrace / full error message

```
After checking the terminal 

bench update
Backing up sites...
INFO:bench.app:pulling frappe
$ git pull  upstream version-13-beta
From https://github.com/frappe/frappe
 * branch                version-13-beta -> FETCH_HEAD
Already up to date.
$ find . -name "*.pyc" -delete
INFO:bench.app:pulling erpnext
$ git pull  upstream version-13-beta
From https://github.com/frappe/erpnext
 * branch                  version-13-beta -> FETCH_HEAD
Already up to date.
$ find . -name "*.pyc" -delete
Updating Python libraries...
$ /home/frappe/frappe-bench/env/bin/pip install -q -U pip
INFO:bench.app:installing frappe
$ /home/frappe/frappe-bench/env/bin/pip install -q -U -e /home/frappe/frappe-bench/apps/frappe 
INFO:bench.app:installing erpnext
$ /home/frappe/frappe-bench/env/bin/pip install -q -U -e /home/frappe/frappe-bench/apps/erpnext 
Updating node packages...
$ yarn install
yarn install v1.22.4
[1/4] Resolving packages...
success Already up-to-date.
$ yarn run snyk-protect
yarn run v1.22.4
$ snyk protect
Successfully applied Snyk patches

Done in 2.31s.
Done in 3.10s.
$ yarn install
yarn install v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
error semver@7.3.2: The engine "node" is incompatible with this module. Expected version ">=10". Got "8.17.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Patching sites...
Migrating site1.local
Updating DocTypes for frappe        : [========================================] 100%
Updating DocTypes for erpnext       : [========================================] 100%
Updating Dashboard for frappe
Updating Dashboard for erpnext
Updating customizations for Address
Updating customizations for Contact
Generating Website Theme Files...
Compiling Python Files...
$ bench build
yarn run v1.22.4
$ FRAPPE_ENV=production node rollup/build.js
Production mode
✔ Built js/moment-bundle.min.js
✔ Built js/libs.min.js

Building frappe assets...

✔ Built js/checkout.min.js
✔ Built js/dialog.min.js
✔ Built js/social.min.js
✔ Built js/web_form.min.js
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade caniuse-lite browserslist`
✔ Built css/frappe-rtl.css
✔ Built css/printview.css
✔ Built js/list.min.js
✔ Built js/chat.js
✔ Built css/report.min.css
✔ Built css/list.min.css
✔ Built frappe/css/email.css
✔ Built css/frappe-chat-web.css
✔ Built css/form.min.css
✔ Built css/web_form.css
✔ Built js/barcode_scanner.min.js
✔ Built js/frappe-recorder.min.js
✔ Built css/desk.min.css
✔ Built js/bootstrap-4-web.min.js
✔ Built js/frappe-web.min.js
**UNRESOLVED_IMPORT : 'driver.js' is imported by frappe/public/js/frappe/ui/driver.js, but could not be resolved – treating it as an external dependency**
**Cannot find some dependencies. You may have to run "bench setup requirements" to install them.

MISSING_GLOBAL_NAME : No name was provided for external module 'driver.js' in output.globals – guessing 'Driver'**
✔ Built css/frappe-web-b4.css
✔ Built js/control.min.js
✔ Built js/data_import_tools.min.js
✔ Built js/form.min.js
✔ Built js/report.min.js
✔ Built js/desk.min.js
✨  Done in 57.056s

Building erpnext assets...

✔ Built js/erpnext-web.min.js
✔ Built js/item-dashboard.min.js
✔ Built css/marketplace.css
✔ Built css/erpnext.css
✔ Built js/erpnext.min.js
✔ Built css/erpnext-web.css
✔ Built js/marketplace.min.js
✨  Done in 15.775s
Done in 74.30s.
$ sudo supervisorctl restart frappe-bench-workers: frappe-bench-web:
frappe-bench-workers:frappe-bench-frappe-schedule: stopped
frappe-bench-workers:frappe-bench-frappe-long-worker-0: stopped
frappe-bench-workers:frappe-bench-frappe-short-worker-0: stopped
frappe-bench-workers:frappe-bench-frappe-default-worker-0: stopped
frappe-bench-web:frappe-bench-node-socketio: stopped
frappe-bench-web:frappe-bench-frappe-web: stopped
frappe-bench-workers:frappe-bench-frappe-schedule: started
frappe-bench-workers:frappe-bench-frappe-default-worker-0: started
frappe-bench-workers:frappe-bench-frappe-long-worker-0: started
frappe-bench-workers:frappe-bench-frappe-short-worker-0: started
frappe-bench-web:frappe-bench-frappe-web: started
frappe-bench-web:frappe-bench-node-socketio: started
________________________________________________________________________________
Bench: Deployment tool for Frappe and Frappe Applications (https://frappe.io/bench).
Open source depends on your contributions, so please contribute bug reports, patches, fixes or cash and be a part of the community
```

OS version / distribution, `ERPNext` install method, etc.
Ubuntu 18.04.
erpnext 13.0.0-beta.2
frappe 13.0.0-beta.2

**Comment by setsero71** [comment]
I run     bench setup requirements

""
bench setup requirements
Updating Python libraries...
$ ./env/bin/pip install -q -U pip
INFO:bench.app:installing frappe
$ ./env/bin/pip install -q -U -e ./apps/frappe 
INFO:bench.app:installing erpnext
$ ./env/bin/pip install -q -U -e ./apps/erpnext 
Updating node packages...
$ yarn install
yarn install v1.22.4
[1/4] Resolving packages...
success Already up-to-date.
$ yarn run snyk-protect
yarn run v1.22.4
$ snyk protect
Successfully applied Snyk patches

Done in 2.29s.
Done in 3.07s.
$ yarn install
yarn install v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
error semver@7.3.2: The engine "node" is incompatible with this module. Expected version ">=10". Got "8.17.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
""
any thought?

Thanks in advance

**Comment by Thunderbottom** [comment]
```sh
error semver@7.3.2: The engine "node" is incompatible with this module. Expected version ">=10". Got "8.17.0"
error Found incompatible module.
```

The error states you need to update node to >=v10. We recommend setting up node 12. To do so, if you are on Ubuntu, you may run:

```bash
$ curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
$ sudo apt install -y nodejs
```

After that is done, you may run `bench setup requirements` and `bench build` on your frappe-bench.

**Comment by setsero71** [comment]
Hi.

Dear Thunderbottom.

Your solution works perfectly. I got a full desk environment.

Thanks
