### ISSUE TITLE
Annoying wordyness in ERPNext-API Error report

### ISSUE THREAD

**Issue by grolode** [frappe/erpnext#22105]
Being in the process of reporting Bugs, here is something I already came along in December 2019:

This is how an API error reply of ERPNext looks like in Plain text:
![grafik](https://user-images.githubusercontent.com/7470674/83728843-185f2980-a647-11ea-9f3e-4a06b9d5a0da.png)

The essential part is contained in the red frame.

I isolate the essential part:

![grafik](https://user-images.githubusercontent.com/7470674/83729056-683df080-a647-11ea-948b-27baefaaa60c.png)

So it's readable without searching through tons of unwanted html formatting code.

![grafik](https://user-images.githubusercontent.com/7470674/83729142-886daf80-a647-11ea-8571-3ca05beef08d.png)

The result is a plain stack trace, that is giving some hint about what is wrong.

This or simlar like this is how a proper success/error message would be expected (this example is in xml, in JSON it's accordingly the same):

<reply-message>
	<severity>error</severity>
	<message-text>The item with the item code "Default Itedm" could not be found.</message-text>
	<context>"item_code":"Default-Itedm"</context>
	<erpnext-stacktrace>
		<p><pre>Traceback (most recent call last):
		  File "/home/frappe/bench-repo/apps/frappe/frappe/app.py", line 60, in application
			response = frappe.api.handle()
		  File "/home/frappe/bench-repo/apps/frappe/frappe/api.py", line 127, in handle
			"data": frappe.get_doc(data).insert().as_dict()
		  File "/home/frappe/bench-repo/apps/frappe/frappe/model/document.py", line 223, in insert
			self._validate_links()
		  File "/home/frappe/bench-repo/apps/frappe/frappe/model/document.py", line 756, in _validate_links
			frappe.LinkValidationError)
		  File "/home/frappe/bench-repo/apps/frappe/frappe/__init__.py", line 364, in throw
			msgprint(msg, raise_exception=exc, title=title, indicator='red')
		  File "/home/frappe/bench-repo/apps/frappe/frappe/__init__.py", line 350, in msgprint
			_raise_exception()
		  File "/home/frappe/bench-repo/apps/frappe/frappe/__init__.py", line 316, in _raise_exception
			raise raise_exception(msg)
		frappe.exceptions.LinkValidationError: Could not find Row #1: Item: Default-Itedm		
	</erpnext-stacktrace>
</reply-message>

**Comment by grolode** [comment]
Sorry, this is what it should look like:
![grafik](https://user-images.githubusercontent.com/7470674/83730296-29a93580-a649-11ea-834a-d5897b8b6753.png)

**Comment by adityahase** [comment]
Setting `Accept` header to `application/json`, solves this problem.
