### ISSUE TITLE
How do I set "Asset Register" in the ERPnext?

### ISSUE THREAD

**Issue by MacDeus** [frappe/erpnext#2210]
I have been asking how do I create an asset register in the system as I have failed to register them in current ERPnext system,
Members, kindly help

Find the attached document/asset register sheet from 
https://groups.google.com/forum/#!topic/erpnext-user-forum/sxI_QfcUqOQ for more details as the github does not support the excel sheet format.
 
Deus

**Comment by nabinhait** [comment]
fixed in v7
