### ISSUE TITLE
Support Employee Hired by multiple companies in same EPRNext server

### ISSUE THREAD

**Issue by Tropicalrambler** [frappe/erpnext#22126]
**Is your feature request related to a problem? Please describe.**
Not a big problem.

**Describe the solution you'd like**
When adding multiple companies on the same ERPNext server, an employee can belong to only the same company. However, there are cases where an employee is hired part time in company A, and part time in company B, both listed in the same ERPNext server.  Currently the solution involves creating separate employee records (including salary structure and salary structure assignment for each). However, we thought it better to have multiple companies listed for an employee. (child table). such that when creating payrolls or salary slips or expense claims, user must select the company for which the expense claim will apply.  Also, a default company out of a list of companies should also be selectable so autofill still works in cases where only one company is listed.

**Describe alternatives you've considered**
Create multiple records for same name and data of same employee, each belonging to a specific company.

**Additional context**
Will be added later.

**Comment by Anurag810** [comment]
@Tropicalrambler we will discuss this to our team and will take it in the road map if feasible.

**Comment by Tropicalrambler** [comment]
Thanks Anurag810. We would love to set up a discussion for this topic anytime this month.  I am currently training recent incoming staff for our company, which will allow us to soon provide source code directly to our fork for pull requests.
