### ISSUE TITLE
Decimal point issue in Quotation, Purchase order & Sales Invoice

### ISSUE THREAD

**Issue by sujith50091** [frappe/erpnext#22145]
## Description of the issue
**Decimal point issue in Quotation, Purchase order & Sales Invoice**

## Context information (for bug reports)
**When we entering the rate of a product two decimal point only its appearing. As per Customs, we can include 4 digit decimal point.**
**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1. Open selling -->Quotation
2. currency set as USD 
3. The rate of a product assumes 370.5689
4. Currently, the rate of a product accept two-digit decimal point ie; 370.57
5. We need the rate of a product 3 or 4 digit decimal point ie; 370.5689 or 370.568

### Observed result
370.57
### Expected result
370.5689 or 370.568
![2020-06-08_00h33_08](https://user-images.githubusercontent.com/66569788/83977825-fef8fe80-a920-11ea-9ba7-c21c1fee9d1d.png)
![2020-06-08_00h32_34](https://user-images.githubusercontent.com/66569788/83977827-015b5880-a921-11ea-9c71-6653774cead8.png)

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by clarkejj** [comment]
You have set precision to 4 decimals places?

https://docs.erpnext.com/docs/user/manual/en/customize-erpnext/articles/set-precision#:~:text=Set%20Precision,or%20for%20a%20specific%20field.

Discussions like this may offer insight https://github.com/frappe/erpnext/issues/1475

**Comment by sujith50091** [comment]
Thanks for the information..Now it's working.

**Comment by clarkejj** [comment]
So what did you do to fix the problem?

Please note that here and close this issue report, thanks

**Comment by sujith50091** [comment]
I Have set the precision 4 in settings
