### ISSUE TITLE
[Bug] V12 - Pricing rule: Discount on Other Item doesn't work

### ISSUE THREAD

**Issue by pipech** [frappe/erpnext#22154]
## Description of the issue
Pricing Rule: Discount on Other Item doesn't work on both frontend and backend.

**In this example we'll set discount base on "Product" item group and it'll discount "Service" item group by 18%**.

### Frontend

- Discount won't apply if discount on other got added first.

![image](https://user-images.githubusercontent.com/24489363/84042552-68374b00-a9cf-11ea-87da-d16263c10776.png)

### Backend
- Sales Invoice with "Raw Material" and "Service", "Service" got discount when docs is saved.

![image](https://user-images.githubusercontent.com/24489363/84040691-1e4d6580-a9cd-11ea-9be3-cf0e860bab5f.png)

- Sales Invoice with only "Service", "Service" still got discount when docs is saved.

![image](https://user-images.githubusercontent.com/24489363/84040957-784e2b00-a9cd-11ea-9994-53f73a1313fa.png)

### Pricing Rule

There are other pricing rules but they are all disabled except this one. 

![image](https://user-images.githubusercontent.com/24489363/84039582-a7fc3380-a9cb-11ea-97be-83c377aa7c86.png)

### Item

![image](https://user-images.githubusercontent.com/24489363/84040441-d62e4300-a9cc-11ea-8c96-df5a8429bdc0.png)

**Output of `bench version`**
```
erpnext 12.9.4
frappe 12.6.1
```

### Frontend

- Recalculate item price everytime item get add, delete or change qty.

### Backend

- Fix pricing rule function

https://github.com/frappe/erpnext/blob/b293e4b110b3fac28372ef2d7ab568384ffaa170/erpnext/accounts/doctype/pricing_rule/utils.py#L87-L104

_get_pricing_rules function might be incorrect.

Example sql generate from _get_pricing_rules function:

	select `tabPricing Rule`.*,
		`tabPricing Rule Item Code`.item_code,
		`tabPricing Rule Item Code`.uom
	from
		`tabPricing Rule`, `tabPricing Rule Item Code`
	where 
		(
			`tabPricing Rule Item Code`.item_code= B or
			(
				`tabPricing Rule`.apply_rule_on_other is not null
				and `tabPricing Rule`.other_item_code=B
			) 
		)

		and `tabPricing Rule Item Code`.parent = `tabPricing Rule`.name

		and `tabPricing Rule`.disable = 0 and
		`tabPricing Rule`.selling = 1  and ifnull(`tabPricing Rule`.warehouse, '') in ('All Warehouses - PRT', 'Stores - PRT', '')  and ifnull(`tabPricing Rule`.company, '') in (Pricing Rule Testing, '') and ifnull(`tabPricing Rule`.customer, '') in (Cust 1 - All Customer Groups, '') and ifnull(`tabPricing Rule`.supplier, '') = '' and ifnull(`tabPricing Rule`.campaign, '') = '' and ifnull(`tabPricing Rule`.sales_partner, '') = '' and ifnull(`tabPricing Rule`.customer_group, '') in ('All Customer Groups', '') and ifnull(`tabPricing Rule`.territory, '') in ('All Territories', '') and 2020-06-08 between ifnull(`tabPricing Rule`.valid_from, '2000-01-01')
		and ifnull(`tabPricing Rule`.valid_upto, '2500-12-31') and ifnull(`tabPricing Rule`.for_price_list, '') in (Standard Selling, '')
	order by
		`tabPricing Rule`.priority desc,
		`tabPricing Rule`.name desc

As you can see it only need to match Discount on Other Item part, it doesn't verify if the transaction have Apply Rule On Item to match.

**Comment by artemartamonov** [comment]
@ankush I have the same. There are no cart price updates when changing a qty. ERP must check all price rules every time when you change a qty.

**Comment by deepeshgarg007** [comment]
@pipech please reopen a new issue if this still persists in latest version-13 release or higher versions
