### ISSUE TITLE
"Payment Entry" status remains as "Submitted" after cancel v12.9.3

### ISSUE THREAD

**Issue by franciscobuendiao** [frappe/erpnext#22156]
## Description of the issue
"Payment Entry" status (field) remains as "Submitted" after cancel
## Context information (for bug reports)

**Output of `bench version`**
```
ERPNext: v12.9.3 (version-12)
Frappe Framework: v12.6.1 (version-12)
```

### Observed result
![Captura de Pantalla 2020-06-08 a la(s) 18 04 59](https://user-images.githubusercontent.com/25084259/84088929-4e880a80-a9b3-11ea-99f5-89b608cd58c6.png)
![Captura de Pantalla 2020-06-08 a la(s) 18 07 35](https://user-images.githubusercontent.com/25084259/84088936-5778dc00-a9b3-11ea-9c6f-123b8fd70f71.png)

**Comment by ankush** [comment]
fixed here: https://github.com/frappe/erpnext/pull/25799
