### ISSUE TITLE
Invoice expiry reminders

### ISSUE THREAD

**Issue by hssudhakara** [frappe/erpnext#22161]
Hello ,

I wanted the below feature in the system .

Whenever we raise the invoices , the products carry a standard warranties for a period of time.
After the expiry of the standard warranty , these products are eligible for AMC's .
We need a system , where in we can set a reminder for the invoices ( May be like 1 year or 2 year ) . System has to generate a reminder ,  in which these invoices are eligible for AMC's.
This feature will help us a lot to keep track of the invoices / customers , where we can generate more revenues from the existing customers through offering AMC's.

Please let us know how to set reminders in the invoices .

Kind regards
H.S.Sudhakara

**Comment by kennethsequeira** [comment]
@hssudhakara check the notification feature: 

https://docs.erpnext.com/docs/user/manual/en/setting-up/notifications

For assistance in setting up for your use case, post on the [forum](https://discuss.erpnext.com)
