### ISSUE TITLE
Print Formats: Ability to disable (Standard) Print formats without logging on with Admin

### ISSUE THREAD

**Issue by adityaduggal** [frappe/erpnext#2217]
Currently the users cannot disable Standard Print formats, they would need to login from admin panel for doing the same which could in turn create problems with github with the json file, hence the users should have the ability to disable the standard print formats just like the Standard Reports.

**Comment by shachiTakalkar** [comment]
You can now make custom print formats default by following steps:
Setup >> Print Format >> "Make Default"
