### ISSUE TITLE
Consolidated Financial Statement Accumulates Values into Wrong Parent Accounts

### ISSUE THREAD

**Issue by Andriesvn** [frappe/erpnext#22180]
## Description of the issue
Consolidated Financial Statements accumulates totals of accounts with parent names such as "1100-1600 - Current Assets" into "1100 - Cash In Hand" account resulting in incorrect parent account balances.

## Context information (for bug reports)
Problem occurs here when finding parent account name:
https://github.com/frappe/erpnext/blob/496b6a28f24b0ca2b2ec8c2da633b02666367179/erpnext/accounts/report/consolidated_financial_statement/consolidated_financial_statement.py#L259

Changing it to:
`account = d.parent_account.split(' - ')[0].strip()`

Resolves the issue

**Comment by clarkejj** [comment]
This CofA import fail may confirm your proposed fix https://github.com/frappe/erpnext/issues/21885

**Comment by clarkejj** [comment]
Here's a similar report https://discuss.erpnext.com/t/consolidated-financial-statements-balance-sheet-is-not-correct/61506/9

**Comment by barry86m** [comment]
Same issue here running erpnext 12.11.2 and frappe 12.9.1

![image](https://user-images.githubusercontent.com/65860880/92420141-a0cef800-f169-11ea-9626-03c5ab576f2d.png)

Middle column (also has rounding error!)
Cash in hand €18,223.79
Stock Assets €9,111.89
-Stock In Hand €9,111.89

Right column
Cash in hand €42.08
Bank Accounts €27.34
-Bank Account €27.34
Stock Assets -€6.30
-Stock In Hand -€6.30
