### ISSUE TITLE
Rounding settings do not affect "Outstanding Amount" in invoices

### ISSUE THREAD

**Issue by grolode** [frappe/erpnext#22214]
In Germany it's essential that the outstanding payment is exactly the total amount.

![grafik](https://user-images.githubusercontent.com/7470674/84478166-23423b80-ac91-11ea-8bf1-ab7757e52f1d.png)

Consequently, the demand of an invoice has to be **exactly** the grand total of the invoice.

![grafik](https://user-images.githubusercontent.com/7470674/84478284-55ec3400-ac91-11ea-8e53-974a500c6ec8.png)

**Comment by deepeshgarg007** [comment]
@grolode Did you refresh and check post that, issue is not replicable, closing this issue
