### ISSUE TITLE
From Sales invoice when we select payment it shows Journal entry instead of Payment entry odule

### ISSUE THREAD

**Issue by kfcspl** [frappe/erpnext#22222]
[Welcome](https://vimeo.com/user117592953/review/428478836/1060f881ab) to ERPNext issue tracker! Before creating an issue, please heed the following:

1. This tracker should only be used to report bugs and request features / enhancements to ERPNext
    - For questions and general support, checkout the manual https://erpnext.com/docs/user/manual/en or use https://discuss.erpnext.com
    - For documentation issues, refer to https://github.com/frappe/erpnext_com
2. Use the search function before creating a new issue. Duplicates will be closed and directed to
   the original discussion.
3. When making a bug report, make sure you provide all required information. The easier it is for
   maintainers to reproduce, the faster it'll be fixed.
4. If you think you know what the reason for the bug is, share it with us. Maybe put in a PR 😉
-->

## Context information (for bug reports)

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1.
2.
3.

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by olamide2** [comment]
This is not a bug.

There is an accounting setting for this 

Go to the Account settings and uncheck this 

Regards

**Comment by kennethsequeira** [comment]
@kfcspl  update the settings under Accounting Settings
