### ISSUE TITLE
problem in layout for RTL language (Arabic)

### ISSUE THREAD

**Issue by EngWail** [frappe/erpnext#22234]
there is problem in RTL language Arabic layout in V13-beta the main module menu is overlap with the module details check the photo attached
![error1](https://user-images.githubusercontent.com/36508407/84575946-ba0a1780-adb9-11ea-8ca8-0adfee1f88ff.jpg)
![error2](https://user-images.githubusercontent.com/36508407/84575952-c1c9bc00-adb9-11ea-8598-0db35845b0c9.jpg)

**Comment by alimahwer** [comment]
I've faced the same issue.

**Comment by surajshetty3416** [comment]
Resolved with https://github.com/frappe/frappe/pull/13669

Please update.
