### ISSUE TITLE
Feature Request: Create "Purchase Receipt" from "Purchase Invoice"

### ISSUE THREAD

**Issue by Priyanka-IAS** [frappe/erpnext#2223]
***\* "Receive Material" button required on Purchase Invoice **

We procure the material from USA/Europe and supply to machining companies in India and in neighbouring countries.
- For ALL incoming material to us, once the material is shipped from our Supplier, we get invoiced (Purchase Invoice). If material is coming to us by SEA, it typically takes 8-10 weeks before we receive it in our warehouse.
- I want to be able to first create the Purchase Invoice. Then, once the material is here, create the Material receipt from this Purchase Invoice - something like a “Receive Material” on the invoice. The reason I cannot simply use the Sales order to receive the material is that a) we usually do not receive complete orders/quantites from the SO, b) the weight/quantity varies +/-15% or more from the Sales order every time. 

Since I already put in the exact quantity shipped/weight of material at the time of entering the Purchase Invoice, I would ideally not like to do the same again in Material Receipt.

Thanks!

**Comment by Arundhatii** [comment]
@nabin can this now be done by creating a PO, then making a Purchase invoice in draft status and then Submitting it using Update stock check box once the material is received.

**Comment by Arundhatii** [comment]
Closing this for now. Please feel free to reopen if it is still relevant.
