### ISSUE TITLE
Twitter and LinkedIn settings not visible

### ISSUE THREAD

**Issue by AnujaDangol** [frappe/erpnext#22236]
I tried to follow the documentation: https://docs.erpnext.com/docs/user/manual/en/CRM/twitter-settings
But in my application, the twitter settings are not visible. Is it available with the opensource version?

**Comment by kennethsequeira** [comment]
@AnujaDangol what are your ERPNext and Frappe Versions?

**Comment by AnujaDangol** [comment]
@kennethsequeira Below are my version

ERPNext: v11.1.47 (master)

Frappe Framework: v11.1.42 (master)

**Comment by kennethsequeira** [comment]
@AnujaDangol 

closing the issue. The social media post option has been added in version 13. You will need to upgrade to use these features.
