### ISSUE TITLE
Item Variants

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#2224]
- [x] Add master Item Attribute, Item Attribute Value
- [x] In Item, set type - "Template / Variant"
- [x] In Item Variant, attribute, attribute_value must be unique
- [x] On Item Save, if template, add / remove variants
- [x] On Item Save, update variants (this is most efficient) - except items tagged as "No Copy"
- [x] In Item search, only non-templates can be selected
- [x] Add to attributes to description
- [x] Block stock entry of template
- [x] If item is template, it must have stock 0
- [x] In `get_item_details` - get price
- [x] Item tax from template
- [x] UOM from template
- [x] Quality specs from template
- [x] Reorder details
- [x] If variant, copy over from parent
- [x] In all queries where tables are used, always check where parent is `name` or `parent_of`
- [ ] Consolidated reports for a template
- [x] BOM for template gets applied to variants (check BOM validation)
- [x] Variant cannot be on website
- [ ] Item Listing on website
- [ ] Item Template page - show main item and variants
- [ ] Add to cart - select variant.
- [x] Message on top of variant / template
- [x] Naming

**Comment by devdesco-ceo** [comment]
I guess one of the best item variant implementation is in Odoo ERP. You can enter supplier source in each variant, purchase and sale pricing, manage attributes, etc. It is easy to create hundreds of subsequent variants, aka standalone items, and managed from within one product variant template with ease!
