### ISSUE TITLE
"Do not include in total" field value for a Salary Component is not picked on Salary Slip despite being ticked on Salary Component Setup-V13

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#22252]
![image](https://user-images.githubusercontent.com/1822868/84663953-800a5400-af26-11ea-893b-558f467f70f9.png)

I.e. A user has to still tick it on the salary slip

This happens when the salary component in question is not part of salary structure

**Comment by onlinebizsoft** [comment]
@muchai please describe the issue in detail like this to get more attention https://github.com/frappe/hrms/issues/108

Can you confirm if the issue is still valid? A lots of issue fixed on the HR module since your post.

**Comment by muchai** [comment]
This was fixed.
