### ISSUE TITLE
Existing asset is not allowed to saved due to purchase receipt amount missing

### ISSUE THREAD

**Issue by aakvatech** [frappe/erpnext#22279]
1. Create a new asset
2. Tick is existing asset
3. Add gross amount (as it is a mandatory field)
4. Save the asset after filling other mandatory fields
5. You get an error "Gross Purchase Amount should be {} to purchase amount of one single Asset."

Version
--------
ERPNext: v12.9.3 (version-12)
Frappe Framework: v12.6.1 (version-12)

https://github.com/frappe/erpnext/blob/054aafa1d7c10ed91798e66de34fbe866943f942/erpnext/assets/doctype/asset/asset.py#L132

**Comment by kennethsequeira** [comment]
@aakvatech check [latest release](https://github.com/frappe/erpnext/releases/tag/v12.10.0). This should be [fixed](https://github.com/frappe/erpnext/pull/22094).
