### ISSUE TITLE
Multi currency payment & Ledger not working properly!

### ISSUE THREAD

**Issue by mubeenmazhar** [frappe/erpnext#22285]
My company currency is PKR and I created a supplier with GBP currency.  At the time of payment it uses PKR instead of GBP. If I change "Account Paid To" from "Creditors" to "creditors (GBP)" (Created by myself with currency GBP), an error occurs that it should be in PKR while submitting.

And I'm not getting the supplier ledger in GBP, as sometimes I have to send them their's in GBP.

ERPNEXT V12, FRAPPE.CLOUD

**Comment by barredterra** [comment]
Can you elaborate on your setup? At the time of creating a **Purchase Invoice** you select an **Account** under "Credit To". If your supplier uses GPB, this **Account** should be in GBP. Then you can also record the **Payment Entry** in GBP.

If the **Account** in "Credit To" is in you company currency (PKR), and the invoice currency is GBP, then the system will calculate the amount in you company currency according to the exchange rate. In this case the liability is recorded in your company currency and the **Payment Entry** should be as well.

You can use [discuss.erpnext.com](https://discuss.erpnext.com/) or [t.me/erpnexthelp](https://t.me/erpnexthelp) to get more help with this.
