### ISSUE TITLE
Change label on "Change Label (via Custom Translation)", is not saved - v13

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#22322]
![image](https://user-images.githubusercontent.com/1822868/85015106-17161c80-b170-11ea-92d4-cfe43da95742.png)

This begun in version 12.9

**Comment by kennethsequeira** [comment]
@muchai can you share the frappe and ERPNext versions of v13 as well?

**Comment by kennethsequeira** [comment]
Also add some example. Check if the translation record was created. It was created in my case on develop branch

**Comment by muchai** [comment]
This is happening in the below versions
ERPNext: v13.0.0-beta.2 (version-13-beta)
Frappe Framework: v13.0.0-beta.2 (version-13-beta)

This started in version in the below versions
ERPNext: v12.9.4 (version-12)
Frappe Framework: v12.6.1 (version-12)

See below, doesn't stick :)
![image](https://user-images.githubusercontent.com/1822868/85136148-e2759400-b247-11ea-8947-fff2323b5c9e.png)

The Translation records is created though.
![image](https://user-images.githubusercontent.com/1822868/85135956-988cae00-b247-11ea-98c2-54edc94e2341.png)
