### ISSUE TITLE
Quick Stock Balance

### ISSUE THREAD

**Issue by Rgottsch1** [frappe/erpnext#22336]
## Context information (for bug reports)

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1.
2.
3.

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by kennethsequeira** [comment]
Closing the issue due to lack of any kind of information provided
