### ISSUE TITLE
Revise Profit and Loss Statement Format

### ISSUE THREAD

**Issue by EMSF** [frappe/erpnext#2234]
Request to revise the P & L report format for both the Financial Statement and Analytics to reflect standard P&L reporting format.  
Also need to make periods standalone columns with the totals in the end column rather than running totals per period as is the current Financial Statement report.

	           Period 1	Period 2	Period 3	      Total
Income	         x	             x	            x		          3x
COGS					
Gross Profit					
Expenses					
Net Profit

**Comment by umairsy** [comment]
Similar issue - https://github.com/frappe/erpnext/issues/2621

**Comment by mschinzvende** [comment]
Was this sorted? It seems like after many years this issue is still there, i stand corrected.

**Comment by nakul80** [comment]
Yes seems this option is still not available.. why was issue closed?
