### ISSUE TITLE
ERPNext version-13 missing add to cart

### ISSUE THREAD

**Issue by doniafrizal** [frappe/erpnext#22361]
version-13 missing add to cart

_Originally posted by @doniafrizal in https://github.com/frappe/erpnext/pull/21903#issuecomment-647000962_

**Comment by kennethsequeira** [comment]
Closing since the same is working for the last two beta releases:

v-13 beta 3 and 4

![image](https://user-images.githubusercontent.com/33246109/90155705-3f557c80-dda9-11ea-84a9-ce2765456554.png)
