### ISSUE TITLE
Last Purchase rate is showing in PO Need to Hide that

### ISSUE THREAD

**Issue by Zohaib542** [frappe/erpnext#22414]
Please post on our forums:

for questions about using `ERPNext`: https://discuss.erpnext.com

for questions about using the `Frappe Framework`: ~~https://discuss.frappe.io~~ => [stackoverflow](https://stackoverflow.com/questions/tagged/frappe) tagged under `frappe`

for questions about using `bench`, probably the best place to start is the [bench repo](https://github.com/frappe/bench)

For documentation issues, use the [ERPNext Documentation](https://erpnext.com/docs/) or [Frappe Framework Documentation](https://frappe.io/docs/user/en) or the [developer cheetsheet](https://github.com/frappe/frappe/wiki/Developer-Cheatsheet)

> **Posts that are not bug reports or feature requests will not be addressed on this issue tracker.**

**Comment by kennethsequeira** [comment]
@Zohaib542 please post on the [forum](https://discuss.erpnext.com) for such queries.

You can use [customize form](https://docs.erpnext.com/docs/user/manual/en/customize-erpnext/customize-form) option to hide the field.
