### ISSUE TITLE
Version-13 Loan Module 

### ISSUE THREAD

**Issue by sammish** [frappe/erpnext#22442]
@nabinhait Please remove Mandatory field Rate of Interest from Loan Module 

![image](https://user-images.githubusercontent.com/12432802/85676719-88ede900-b6cf-11ea-9aba-44611cf60717.png)

**Comment by sammish** [comment]
@nabinhait Please support this request 

![image](https://user-images.githubusercontent.com/12432802/86215384-3146f600-bb85-11ea-9192-f1d57630a998.png)

**Comment by nabinhait** [comment]
@sammish Why should we remove it from mandatory? I think it will accept zero.

**Comment by sammish** [comment]
@nabinhait I tried that. It would not accept Zero

![Peek 2020-07-01 13-58](https://user-images.githubusercontent.com/12432802/86236667-226f3c00-bba3-11ea-9c18-f8859c73f733.gif)
