### ISSUE TITLE
Friends let's create a group and chat for developers in telegrams!!!???

### ISSUE THREAD

**Issue by CtrlPy** [frappe/erpnext#22471]
Friends let's create a group in telegrams and a chat room for developers where we can help each other improve our development tools, please support this offer, that the creators of the frappe would create an official group in telegrams.  support this proposal!!! I wish everyone good and successful :)

**Comment by revant** [comment]
There are 2 groups

- https://t.me/erpnextannounce
- https://t.me/erpnexthelp

**Comment by revant** [comment]
Reopen issue if needed.
