### ISSUE TITLE
Series or Naming Series not picking on doctype-v13

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#22495]
If you you include naming series to a doctype that was using say name as the identifier, the naming series doesn't pick, the document continues using name as identifier.

**Comment by kennethsequeira** [comment]
@muchai please share the steps to replicate along with screenshots describing the issue.

**Comment by muchai** [comment]
Step 1.

Added the field below.
![image](https://user-images.githubusercontent.com/1822868/86108952-7fe48980-bacc-11ea-9b19-e3546f6fbbd4.png)

Step 2.
![image](https://user-images.githubusercontent.com/1822868/86109051-a0144880-bacc-11ea-8368-98fe766116d6.png)

Step 3.
When I create a new record.
![image](https://user-images.githubusercontent.com/1822868/86109404-0731fd00-bacd-11ea-8313-ecf128c02229.png)
