### ISSUE TITLE
v13 beta 3 POS: Select Batch Numbers dialog pops out twice with only one row in the batch entries table

### ISSUE THREAD

**Issue by mujeerhashmi** [frappe/erpnext#22545]
## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 13.0.0-beta.3
frappe 13.0.0-beta.3
```

## Steps to reproduce the issue

1. select batch item in POS

### Observed result
1. Select Batch Numbers dialog pops out twice.
2. Select Batch Numbers dialog does not show all batches of the item in Batch entries table

### Expected result
1. Select Batch Numbers dialog popup should be single.
2. Batch entries table should show all the available batches.

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by mu7arram** [comment]
Hello Mr. Syed 

Would you please explain how did you fix that?

Thank you

**Comment by mujeerhashmi** [comment]
> Hello Mr. Syed
> 
> Would you please explain how did you fix that?
> 
> Thank you

Not using built-in POS.
I have switched to POSAwesome. It supports batch serach now [Check here](https://github.com/yrestom/POS-Awesome/issues/110)
