### ISSUE TITLE
Bulk Edit/Enable/Disable - Feature Request

### ISSUE THREAD

**Issue by devdesco-ceo** [frappe/erpnext#2254]
I would like to request so needed "Bulk Edit/Enable/Disable" feature. It is present in all popular apps, like Prestashop, Magento, OpenERP, etc.

For example, I want to bulk disable/enable several currencies... and I want to do it at once, not editing each entry....

**Comment by cgpurbaugh** [comment]
+1

**Comment by nabinhait** [comment]
Can be done by new "Bulk Update" form
