### ISSUE TITLE
Include Payroll under allow modules for each user

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#22549]
As of now, payroll appears on the sidebar by default.

Also, some payroll reports appear for a user with role employee.

![image](https://user-images.githubusercontent.com/1822868/86317869-2b125180-bc39-11ea-85ce-f6f3d19d84d7.png)

Salary companent appears too, for a user with role employee
![image](https://user-images.githubusercontent.com/1822868/86317945-5c8b1d00-bc39-11ea-92cb-badba569bdac.png)
No need to display this.

Leave type too, no need to display for user employee
![image](https://user-images.githubusercontent.com/1822868/86318018-8a706180-bc39-11ea-8417-59a39483114c.png)

**Comment by Anurag810** [comment]
Thanks for reporting the issue, will update you when it is fixed.

**Comment by muchai** [comment]
This too, the payroll menu appears for all users even if payroll may not be a module under use.
