### ISSUE TITLE
Default Payroll User and Payroll Manager Roles-v13

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#22551]
With the split of HR and Payroll as separate modules, which is very nice btw. Could the roles be split too.

I know users can define these themselves, and we do, just that by default there's a role for each module, hence payroll needs the same too I guess.

**Comment by Anurag810** [comment]
Thanks for your suggestion.
We haven't split the Roles yet. But definitely, we can take this in our HR Roadmap.
