### ISSUE TITLE
Missing vertical scroll bar on General Ledger-v13

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#22561]
![image](https://user-images.githubusercontent.com/1822868/86400902-07d7b880-bcb2-11ea-9839-8589a69bfa76.png)

**Comment by dawoodjee** [comment]
Would be great if we just have one scroll bar for reports / GL, where the table size adapts to fill the screen space and this way we wont need two scroll bars

**Comment by szufisher** [comment]
I confirm almost all query-reports have the same issue, e.g desk#query-report/Purchase%20Receipt%20Trends
