### ISSUE TITLE
If Contract part type is Customer party user cannot be customer contact

### ISSUE THREAD

**Issue by garyritchie** [frappe/erpnext#22560]
## Description of the issue

With Party Type set to _Customer_, I cannot set a Customer contact in the _Party User_ field when _Party Name_ is set to my customer. Instead, it lists my Company users.

## Context information (for bug reports)

ERPNext: v12.10.0 (version-12) \
Frappe Framework: v12.7.2 (version-12)

## Steps to reproduce the issue

1. Create new Contract
2. Set Party Type to Customer
3. Set Party Name to a customer
4. Try to find a customer contact for that customer

### Observed result

Party User only lists my company's users.

### Expected result

I should see a list of Customer contacts

**Comment by deepeshgarg007** [comment]
<img width="1330" alt="image" src="https://user-images.githubusercontent.com/42651287/197703047-3b35b334-7743-4454-a2b0-6094d3135553.png">

I cannot see any contact field here, which field you are talking about, please mention and reopen if needed
