### ISSUE TITLE
"bench run-test" fails on current develop branch

### ISSUE THREAD

**Issue by gwhitney** [frappe/erpnext#22578]
A fresh, newly installed ERPNext instance on a brand-new vanilla Debian 10 box fails `bench run-test`, details below. I was in the process of preparing a pull request (implementing a Description field for the Account DocType, motivated by the volunteer bookkeepers in our organization who need readily accessible detailed guidance on what transactions to put in various accounts, but adding such a field through Customize does not allow our sizable library of Descriptions to be imported in the Chart of Accounts Importer.) I reached the step of `bench run-test` in the PR checklist, and was surprised that there were many failures seemingly unrelated to this small change. So I tried on a completely fresh install from scratch, and indeed, there are many failures as it stands in the repository.

Please advise whether it is OK to submit PRs given that it is currently impossible to complete the PR checklist, or whether there should be a moratorium on non-essential PRs until the test suite is brought back to compliance on develop. (I unfortunately don't really yet have the familiarity with ERPNext to address any significant portion of the failed tests, but if there are a couple that you think are accessible to someone relatively new to ERPNext coding, please let me know and I will be happy to pitch in on trying to rectify some existing test failures if it will help improve the possibility of getting the PR I am interested in into the system.)

Thank you very much.

## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 13.x.x-develop
frappe 13.x.x-develop
```

## Steps to reproduce the issue

1. Initialize a new Debian 10 server.
2. Install the development version of ERPNext by one of the numerous guides on the web.
3. execute `bench --site <SITE-NAME> set-config allow_tests true`
4. execute `bench run-test`

### Observed result
A great deal of output, the last several lines of which are:
```
======================================================================
FAIL: test_invoicing (erpnext.healthcare.doctype.patient_appointment.test_patient_appointment.TestPatientAppointment)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/erpnext/frappe-bench/apps/erpnext/erpnext/healthcare/doctype/patient_appointment/test_patient_appointment.py", line 51, in test_invoicing
    self.assertTrue(sales_invoice_name)
AssertionError: None is not true

----------------------------------------------------------------------
Ran 1303 tests in 1662.195s

FAILED (failures=42, errors=88, expected failures=2)
```

### Expected result

Some sort of success/pass message, perhaps allowing for a small handful of known failures. The message above explicitly reports many more than the expected number of failures.

### Stacktrace / full error message

The entire output of run-test is very long; please advise if it is worthwhile for me to attach it to this issue report.

## Additional information

OS version / distribution, `ERPNext` install method, etc.

Debian 10 'buster' as distributed by Debian; I generally followed the installation process as outlined in the following particular guide, as it is very clear and seems relatively modern:
https://www.rosehosting.com/blog/how-to-install-erpnext-on-ubuntu-20-04/
(Note I only went up to the stage at which the development installation is executing with `bench start` and simply ran the tests in that environment, rather than switching to the production environment as the last section of the guide details.)

**Comment by ankush** [comment]
IMO this is most likely due to state left by tests. Locally they often don't give best results. Solution is to only run a specific test using 

```
bench --site sitename run-tests --module app.dotted.path --test test_name
```
