### ISSUE TITLE
Data warehouseing

### ISSUE THREAD

**Issue by bobzz-zone** [frappe/erpnext#2257]
Hi,

I would like to suugest data warehouseing feature, i think its important to archive data so in the future the data base not being bigger every time, but we can flush some not important data like :
1. Canceled transaction
2. Too old transaction record (for example data that over 5 years )

so we can keep old data as a data backup but it will be flushed from production database to make the database query lighter, because its sure had some effect if the mysql query in 1 milion rows or half a million

Thanks

**Comment by joezsweet** [comment]
You can create a custom report. If you need out of the box, please provide a detailed description and mockup
