### ISSUE TITLE
Cyclic link between Purchase Receipt and Quality Inspection-v13

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#22588]
![image](https://user-images.githubusercontent.com/1822868/86565452-83668d80-bf70-11ea-8d7f-6d8195d3b2eb.png)

![image](https://user-images.githubusercontent.com/1822868/86565504-9ed19880-bf70-11ea-8e20-3787800c2449.png)

**Comment by szufisher** [comment]
as a workaround, 
1. go to purchase receipt , open item form, clear the quality inspection field, then save.
2. go to quality inspection, cancel

**Comment by muchai** [comment]
I used another option I would rather not mention here :)
