### ISSUE TITLE
Opening Invoice creation tool - Bug or Modification

### ISSUE THREAD

**Issue by kfcspl** [frappe/erpnext#22581]
## Description of the issue
Opening Invoice Creation Tool does not show Invoice no. of supplier or customer, if instead of its auto series option to have manual entry or upload so customer ledger should show proper result   
## Context information (for bug reports)

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1. Opening Invoices should have Invoice No. or ref. no. of old systems so customer / supplier can get one statement with all bills details with proper ref., we have added old invoice no. in Item column but it is not visible in payment entry directly nor it showed in outstanding and ageing statement
2. Present system shows OP2021-ref, its auto generated opening invoice series - there is no such invoice no.
3. customers or supplier ask we never have the above ref. invoice series. 

### Observed result
attached screen
### Expected result
it should show proper invoice old ref of client entered in system

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.
12.10.1

**Comment by kfcspl** [comment]
![Screen Shot 2020-07-04 at 12 36 33 PM](https://user-images.githubusercontent.com/52742315/86507187-d1a25200-bdf3-11ea-8945-6df0be03b6e9.png)

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.
