### ISSUE TITLE
Setup fails because werkzeug watchdog reloads

### ISSUE THREAD

**Issue by sezanzeb** [frappe/erpnext#22595]
## Description of the issue

During the setup procedure after setting the company name and such, a loading bar will appear. It then fails and offers a "try again" button. This seems to happen because frappe reloads because some pycache changed (see logs below).

## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 12.10.1
frappe 13.x.x-develop
```

## Steps to reproduce the issue

1. install erpnext
2. start it
3. setup

### Observed result

setup stops

### Expected result

setup works

### Stacktrace / full error message

```
13:29:28 web.1            |  * Detected change in '/home/tobias/Code/erpnext/env/lib/python3.8/site-packages/werkzeug/_reloader.py', reloading
13:29:28 web.1            | INFO:werkzeug: * Detected change in '/home/tobias/Code/erpnext/env/lib/python3.8/site-packages/werkzeug/_reloader.py', reloading
13:29:28 web.1            |  * Detected change in '/home/tobias/Code/erpnext/env/lib/python3.8/site-packages/werkzeug/_reloader.py', reloading
13:29:28 web.1            | INFO:werkzeug: * Detected change in '/home/tobias/Code/erpnext/env/lib/python3.8/site-packages/werkzeug/_reloader.py', reloading
13:29:28 web.1            |  * Detected change in '/home/tobias/Code/erpnext/env/lib/python3.8/site-packages/werkzeug/_reloader.py', reloading
13:29:28 web.1            | INFO:werkzeug: * Detected change in '/home/tobias/Code/erpnext/env/lib/python3.8/site-packages/werkzeug/_reloader.py', reloading
13:29:30 web.1            |  * Restarting with inotify reloader
```

## Workaround

Quick and dirty workaround by modifying `_check_modification` in `erpnext/env/lib/python3.8/site-packages/werkzeug/_reloader.py`:

```
        def _check_modification(filename):
            return
```

Setup finishes now.

## Additional information

Xubuntu 20.04

Since the easy installer does not support ubuntu 20, I manually installed it. During the installation I furthermore encountered the following issues:
- libssl1.0.0 missing. Fixed by dpkg installing this: http://security.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu5.3_amd64.deb
- ERROR: launchpadlib 1.10.13 requires testresources, which is not installed. Fixed with `sudo apt install python3-testresources`
- pandas 0.24.2 not getting compiled. Fixed by modifying requrements.txt to change it to 0.25.2 and running `./env/bin/pip install --only-binary :all: pandas==0.25.2`.

**Comment by clarkejj** [comment]
Hi be aware these are two different code branches - erpnext is on version-12 while frappe is on develop. That may be a general source of odd problems, so perhaps what you are encountering.

erpnext 12.10.1
frappe 13.x.x-develop

**Comment by ankush** [comment]
https://github.com/frappe/frappe/pull/13099
