### ISSUE TITLE
erpnext clone is 846 MiB large

### ISSUE THREAD

**Issue by sezanzeb** [frappe/erpnext#22602]
## Description of the issue

It took 15 minutes to clone 81.7 MB of code because there is some huge pack file

![image](https://user-images.githubusercontent.com/28510156/86755253-c8a6c000-c041-11ea-9ba7-7eb477833e45.png)

## Steps to reproduce the issue

1. git clone https://github.com/frappe/erpnext

### Observed result

huge repo

### Expected result

small repo

**Comment by Thunderbottom** [comment]
try limiting the repository depth to 1:

```sh
$ git clone git@github.com:frappe/erpnext.git --depth=1
```

**Comment by gavindsouza** [comment]
@sezanzeb have you tried cloning the Linux kernel? Maybe give it a try: https://github.com/torvalds/linux

@Thunderbottom's comment is on point, however if you're cloning ERPNext with the intention of 
getting it to run, checkout [bench](https://github.com/frappe/bench), or [frappe_docker](https://github.com/frappe/frappe_docker) which will handle most of the difficulties you may face setting up a Frappe environment.
