### ISSUE TITLE
Patient doctype should have address and contact section

### ISSUE THREAD

**Issue by mujeerhashmi** [frappe/erpnext#22628]
@ruchamahabal @akurungadam 

**Is your feature request related to a problem? Please describe.**
Healthcare is supposed to be Patient centric . As such address and contact details of the patient need to be available in patient doctype and not to be entered in the linked customer doctype.

**Describe the solution you'd like**
It would be great to have the provision of entering address & contact details in the patient doctype just like in healthcare practitioner doctype. And then link them to linked customer doctype as well.

**Comment by akurungadam** [comment]
Yes, the Customer and Patient documents should be linked to the same contact / address. This along with some other enhancements are underway, will be raising a PR this week itself.

**Comment by ruchamahabal** [comment]
This is already added in https://github.com/frappe/erpnext/pull/24860
