### ISSUE TITLE
Values out of Sync error-v13

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#22630]
![image](https://user-images.githubusercontent.com/1822868/87042546-7c53af80-c1fc-11ea-8cc5-cde81b5447d7.png)

What's the cause of the above error? Or what situation leads to the error?

If the only work around is to create the adjustment journal as per the message, shouldn't this journal be created and submitted automatically?

**Comment by xickomesquita** [comment]
> ![image](https://user-images.githubusercontent.com/1822868/87042546-7c53af80-c1fc-11ea-8cc5-cde81b5447d7.png)
> 
> What's the cause of the above error? Or what situation leads to the error?
> 
> If the only workaround is to create the adjustment journal as per the message, shouldn't this journal be created and submitted automatically?

It happens with me as well. I'm using 6 digits to float and 9 digits do currency. I work with a wide spread of UOMs from liters to microliters... so; I need to have it. 

Sometimes, after doing a journal entry, in the next day, I can go foward.

**Comment by laxmantandon** [comment]
![image](https://user-images.githubusercontent.com/24727535/90318482-5d101680-df4e-11ea-9441-9fa96d37cbe1.png)

Same happens to me also. General Ledger is showing same value in both the accounts 
Stock Adjustment - SSIPL  and Stock In Hand - SSIPL, 

Is there any way to find difference..

ERPNext: v13.0.0-beta.4 (version-13-beta)
Frappe Framework: v13.0.0-beta.4 (version-13-beta)

**Comment by azharul-islam** [comment]
Hi, we have this issue too after upgrading from v12 to v13 stable version. 
There are multiple sites and all of them show this error on submitting purchase Invoices

Also the accountants mentioned that the trial balance is going haywire. 

<img width="608" alt="Screen Shot 2021-04-11 at 8 21 03 PM" src="https://user-images.githubusercontent.com/38819502/114314513-b04d5f80-9b03-11eb-9380-2727eb5e6188.png">

**Comment by cchandel** [comment]
Hi,
  We've started facing this issue as well after upgrading from 13.0.2 to 13.1.0.

![values out of sync error](https://user-images.githubusercontent.com/972911/115719951-1b9cfa00-a36c-11eb-9935-3ef98b430408.png)

  Any ideas on how to resolve this?

**Comment by carstenblt** [comment]
Same here. I created the adjustment journal entry. After a few days it asked that I create another journal entry the other way round. So I deleted the first one again...

**Comment by azharul-islam** [comment]
The issue still exists in the latest version of ERPNext 13.2.1

**Comment by lincogn** [comment]
The issue still exists in the latest version of ERPNext v13.4.0

**Comment by carstenblt** [comment]
Maybe remove the "invalid" tag? Or did somebody find a workaround?
