### ISSUE TITLE
Supplier Customer Sales Analytics Report Based on Supplier Items

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#22633]
A report to analyse customer purchases of a particular supplier item(s).

**Comment by harshit-30** [comment]
Kindly share the mock-up of the report you would like to have.

**Comment by muchai** [comment]
![image](https://user-images.githubusercontent.com/1822868/88763105-3a72b500-d17b-11ea-9de6-afc6fd3be2ae.png)

The values are from sales invoices.
The supplier Item link is from the Supplier Details section of item, since an item can have more than one supplier.

**Comment by muchai** [comment]
This query for a query report. Will convert it to a script report with hierarchical groupings.

SELECT itemsupplier.supplier as "Supplier:Link/Supplier:200",
	invoice.customer as "Customer:Link/Customer:200",
	invoiceitem.item_name as "Item:Link/Item:200",
	sum(invoiceitem.qty) as "Quantity:Float:120",
    sum(invoiceitem.amount) as "Amount:Currency:120"
FROM `tabSales Invoice` as invoice
INNER JOIN `tabSales Invoice Item` as invoiceitem ON invoice.name=invoiceitem.parent
INNER JOIN `tabItem Supplier` as itemsupplier ON invoiceitem.item_code=itemsupplier.parent
WHERE invoice.docstatus=1
AND itemsupplier.supplier IS NOT NULL
AND invoice.company = %(company)s    
AND itemsupplier.supplier BETWEEN %(from_supplier)s AND %(to_supplier)s
AND invoice.posting_date BETWEEN %(from_date)s AND %(to_date)s
GROUP BY itemsupplier.supplier,invoice.customer,invoiceitem.item_name
ORDER BY itemsupplier.supplier,invoice.customer,invoiceitem.item_name;
