### ISSUE TITLE
"Quotation List" view

### ISSUE THREAD

**Issue by franciscobuendiao** [frappe/erpnext#22654]
## Description of the issue
"Quotation List" view loads blank if "Quotation to" isn't set as "In Standard Filter"
## Context information (for bug reports)

**Output of `bench version`**
```
ERPNext: v12.10.0 (version-12)
Frappe Framework: v12.7.3 (version-12)
```

### Observed result
https://discuss.erpnext.com/t/issue-on-quotation-list-view/63585/4
![Captura de Pantalla 2020-07-10 a la(s) 12 42 58](https://user-images.githubusercontent.com/25084259/87183136-268a1080-c2ab-11ea-8b84-7a6a7542a9bc.png)

### Expected result
![Captura de Pantalla 2020-07-10 a la(s) 12 44 11](https://user-images.githubusercontent.com/25084259/87183151-2ee24b80-c2ab-11ea-8642-9430e27610a0.png)

### Stacktrace / full error message

```
Uncaught (in promise) TypeError: listview.page.fields_dict.quotation_to is undefined onload desk.min.js:10 setup_view list_view.js:231
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by sharmanakul** [comment]
this may have been an issue in the older version but in the later version, this is resolved.
