### ISSUE TITLE
Text editor removes spaces on Firefox

### ISSUE THREAD

**Issue by leonardorame** [frappe/erpnext#22670]
## Context information (for bug reports)

ERPNext v13.0.0-beta.3
Firefox 78.0.164bit
O.S. Ubuntu 18.04

## Steps to reproduce the issue

On any text editor, for example on Task Description when you type "hello world" the space is removed, resulting in "helloworld". This behavior is not present on Google Chrome, there it work as expected. 

### Observed result

![image](https://user-images.githubusercontent.com/1405017/87307204-8c66da00-c4ef-11ea-91f0-7010fc53b57b.png)

**Comment by leonardorame** [comment]
I think this issue is related to [this bug in Quill](https://github.com/quilljs/quill/issues/468)

**Comment by leonardorame** [comment]
A workaround is typing the text in source code mode (by clicking on the `<>` icon), then when done click again on the same icon.

**Comment by nanoharsha** [comment]
@surajshetty3416 seems to have fixed this issue in this :


https://github.com/frappe/frappe/pull/10984
