### ISSUE TITLE
2 saler order whith additional discount 1 sale invoice

### ISSUE THREAD

**Issue by federicocalvo** [frappe/erpnext#22704]
## Description of the issue
Hi, I have a situation that I don’t see another user asking in either discuss or github.

When we have more than one sales order with additional discount, if we generate a sales invoice and bring these two customer orders, it only takes one of the discounts, it doesn’t accumulate them.

While I’m using version 11 and 12, check all github issues and PR related to the topic in the future.

## Steps to reproduce the issue

1. Create more than one 1 Sale Order, with Aditiona Discount
![screenshot-capacitacion diamo com ar-2020 07 15-15_34_28](https://user-images.githubusercontent.com/7256766/87582503-da770b80-c6b0-11ea-9cd4-c902489bf393.png)

2. Create one sale invoice of this Sale Orders
![screenshot-capacitacion diamo com ar-2020 07 15-15_35_08](https://user-images.githubusercontent.com/7256766/87582547-eb278180-c6b0-11ea-9b99-379f96e0931f.png)

3. Check the result

### Observed result
The invoice  take one discount only
### Expected result
The invoice should be accumulate the discounts 

## Additional information
It should work whether the discount is a percentage, a fixed number, or a coupon

OS version / distribution, `ERPNext` install method, etc.
V11 and V12

**Comment by deepeshgarg007** [comment]
This is not supported yet and not plans to add this in near future either, closing this issue for now
