### ISSUE TITLE
Over Receipt / Delivery should be optional for Material Request

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#22707]
Hi ,

When you make a Purchase Order from Material Request, ERPNext validates quantity and prompts the user to adjust Over Receipt / Delivery Allowance if the quantity being ordered is more. I believe this feature should be optional! 

There is hardly any real life situation where purchases are made strictly in line with quantities specified in individual Material Requests! Orders are made in line with MOQs and the overall needs of the organization

I hope this can be fixed soon

Thanks

**Comment by marination** [comment]
Hi @Olawale1 , what is the problem with the **Over Receipt / Delivery Allowance** option in **Stock Settings** or the Item document ? Won't setting that field just one time make this issue go away ? Just trying to get clarity. I understand your concern, but when you say "should be optional" what do you suggest exactly ?

**Comment by Olawale1** [comment]
Hi @marination 

What I'm suggesting is that validation for Over Delivery/Receipt  should be optional for Material Request. The user should be able to decide which document s/he wants this feature applied on. Right now it automatically applies on all related docs 

The reason why it should be optional especially for Material Requests is that most organisations use it as a tool to allow Employees and Departments tender (and get approvals for) their requirements. The actual procurement of the items however is not necessarily related to the quantity in the Material Requests... There are other considerations involved as I mentioned in my original post

Procurement teams should be able to raise a PO from Material Requests and then alter the quantities (without restrictions) based on the organisation's needs and the supplier requirements 

Cheers
