### ISSUE TITLE
Turning on, then off "Homepage is Products" on the Products settings page does not revert back to Home Page

### ISSUE THREAD

**Issue by dealproc** [frappe/erpnext#22733]
By default, ERPNext provides a landing page for the main index of the site.  If you activate "Home Page is Products" under the Products Settings section, save it, then deactivate the "Home Page is Products" value, the site still acts as-if the feature is enabled.  The expected behavior of this is to revert back to the landing page style for the index page.

**Comment by Thunderbottom** [comment]
I've made a fix for this. Please try and let me know if it works fine.

**Comment by dealproc** [comment]
Thank you.  Is this in the v12 branch, or where can I absorb it to test the functionality out?

**Comment by Thunderbottom** [comment]
The fix is on the develop branch, you may test it out on that branch or wait for the backport to happen.

**Comment by dealproc** [comment]
Thank you.  I will wait for the backport, as I'm trying to determine how to deploy this into Azure.
