### ISSUE TITLE
Error: Purchase Taxes and Charges Row #1: Value missing for: Add or Deduct: by importing company csv

### ISSUE THREAD

**Issue by erpnextbeginner** [frappe/erpnext#22740]
Hello, i Have an Important question, when i want to import my Company file with includes 

name | abbr | organisational_type | language_region | website | phone_no | email | anästesie | mailing | default_currency |

there is always this error: Error: Purchase Taxes and Charges Row #1: Value missing for: Add or Deduct

I have included already the VAT on my ERP next but i dont know what to do. I am not a developer. Please for help.
![image](https://user-images.githubusercontent.com/68509256/87879151-30b5b880-c9e9-11ea-96b1-0954805f3266.png)

**Comment by tolutopea** [comment]
Having the same issue too
