### ISSUE TITLE
[Customer] Default filter "All Customer Groups" is misleading

### ISSUE THREAD

**Issue by ceefour** [frappe/erpnext#22742]
## Description of the issue

In "Customer List", Default filter "All Customer Groups" is misleading.

## Context information (for bug reports)

**Output of `bench version`**
```
v13.beta.3
```

## Steps to reproduce the issue

1. Go to Customer List
2. See that filter is "All Customer Groups" is selected by default

### Observed result

**Only** customers that exactly is in "All Customer Groups" is shown. Customers in, e.g. "Individual" group are hidden.

### Expected result

Having "All Customer Groups" as default for filter is misleading, I think the default for name is misleading.

My suggestion:

1. "Customer List" filter should default to "not filtered by Customer Group at all"
2. Name of "All Customer Groups" should be renamed to something like "Generic" / "Unknown" / "Uncategorized" / "Unspecified" as that would be clearer when used as a filter.

Another alternative behavior is that filtering for a parent customer group would include all its child groups as well, but that is a major behavior change of filters.

## Additional information

OS version / distribution, `ERPNext` install method, etc.

* Kubernetes 1.18
* ERPNext Helm chart 1.0.9
* ERPNext v13.beta.3

**Comment by JohnVeness** [comment]
Presumably (I have not tested) the same problem occurs for other similarly named things, like:

- All Item Groups
- All Supplier Groups
- All Territories

?

**Comment by ceefour** [comment]
@JohnVeness I agree with you. What I have experienced is **All Territories**, which has wrong/non-intuitive behavior, that should be named something like "Unknown/Unspecified/Other Territory" instead.

But I also think that these would be each in its own issue, but overall same/similar theme of usability problem. (I argue this is a usability issue, that makes it harder for people, to understand how ERPNext features work.. Even if one user or admin understands this, this peculiarity needs to be trained to all ERPNext users. I also argue that if this issue is fixed, will increase the usability and ease-of-use of ERPNext, and reduces the amount of training required.)

**Comment by ryuliantoro** [comment]
This behaviour happened since version 12.
I don't know if this issue has been fixed or not (I'm in v.12.16.2)

Other related issue is the All Customer Group can't have empty parent group. When saving it takes one child as its group. So a circular happened.

**Comment by ryuliantoro** [comment]
Too bad that this is reported on v13 beta, and confirmed occur on v12, but the solution only done to v13. I hope this is also backported to v12.
