### ISSUE TITLE
Blank login screen

### ISSUE THREAD

**Issue by nwalke** [frappe/erpnext#22751]
## Description of the issue
When navigating to the login screen after site creation, I just see a blank screen with "Get Updates" box.  The console shows "io is not defined."  Seems eerily similar to #17735.

<img width="1297" alt="Screen Shot 2020-07-20 at 9 57 03 PM" src="https://user-images.githubusercontent.com/1617620/88007867-831fd380-cad4-11ea-98c5-93c99a257d31.png">

## Context information (for bug reports)
I'm using the docker set up so there's no `bench version`.  I am pulling the `edge` tags of both erpnext and frappe.

## Steps to reproduce the issue

1. Run through the production docker set up
2. Have site-creator create a site
3. Try to login

### Observed result
Blank login screen and "io is not defined" error.
### Expected result
A login form would appear.
### Stacktrace / full error message

```
Uncaught ReferenceError: io is not defined
    at Object.init (frappe-web.min.js:formatted:5189)
    at frappe-web.min.js:formatted:5180
    at frappe-web.min.js:formatted:5057
    at Array.forEach (<anonymous>)
    at Object.trigger_ready (frappe-web.min.js:formatted:5056)
    at HTMLDocument.<anonymous> (frappe-web.min.js:formatted:5160)
    at HTMLDocument.dispatch (jquery.min.js:3)
    at HTMLDocument.r.handle (jquery.min.js:3)
    at Object.trigger (jquery.min.js:4)
    at HTMLDocument.<anonymous> (jquery.min.js:4)
```

Happy to provide additional context if it will help, but the error seems unrelated to the docker set up/install method I'm using.

**Comment by kennethsequeira** [comment]
@nwalke 

The issue is still up?

Did you try the methods suggested in the thread, ie, building the assets again?

**Comment by nwalke** [comment]
I deleted everything and brought all the containers back up, ran the site creator last.  That appeared to work and the log in form showed up.  When I submitted my name and email to sign up it gave a python error of no default sender defined.  

I'm going to close this issue because I'm moving on to another product and I think the original issue was an error of set up.
