### ISSUE TITLE
[HR > Employee] If Employee is connected to ERPNext User, Uploading photo fails with "File None does not exist"

### ISSUE THREAD

**Issue by ceefour** [frappe/erpnext#22752]
## Description of the issue

[HR > Employee] If Employee is connected to ERPNext User, Uploading photo fails with "File None does not exist"

## Context information (for bug reports)

**Output of `bench version`**
```
v13.beta.3
```

## Steps to reproduce the issue

1. Create Employee
2. Link to ERPNext User
3. Upload photo -> error here

Or:

1. Create Employee
2. Upload photo
3. Save
4. Link to ERPNext User
5. Save -> error here

### Observed result

Photo is uploaded and saved as attachment, but the photo is not saved as part of Employee's profile photo, with message "File None does not exist"

### Expected result

Photo is uploaded and saved as attachment, and photo is not saved as part of Employee's profile photo.

### Stacktrace / full error message

1. https://youtu.be/aw4Yh3w4lFI
2. https://youtu.be/jg5eaU4oZVk

### Workaround

1. Don't upload photo to Employee record
2. Link Employee to ERPNext User
3. Upload the photo to User record instead
4. This will make Employee record using the User's profile photo

## Additional information

OS version / distribution, `ERPNext` install method, etc.

* Kubernetes 1.18
* ERPNext Helm Chart 1.0.9
* ERPNext v13.beta.3

Maybe related to frappe/frappe#18553

**Comment by fderyckel** [comment]
Still an issue today.

**Comment by fderyckel** [comment]
I believe this might be an issue??
#if self.photo:
		#	if not user.user_image:
		#		user.user_image = self.photo
		#		try:
		#			frappe.get_doc({
		#				"doctype": "File",
		#				"file_name": self.photo,
		#				"attached_to_doctype": "User",
		#				"attached_to_name": self.email
		#			}).insert()
		#		except frappe.DuplicateEntryError:  
		#			pass

**Comment by yadavyk** [comment]
This seems to be working fine now. Can you confirm @ankush / @sharmanakul ?

**Comment by fderyckel** [comment]
Confirmed.  Thank you
