### ISSUE TITLE
Get Unreconciled Entries not considering cancelled GL Entries

### ISSUE THREAD

**Issue by doworks** [frappe/erpnext#22756]
## Description of the issue
In utils.py 
## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 13.0.0-beta.3
frappe 13.0.0-beta.3
```

## Steps to reproduce the issue

1. Payment Reconciliation
2. Get Unreconciled Entries

### Observed result
Cancelled GL Entrties is shown within results

### Expected result
Cancelled GL Entrties must not be returned 

## Additional information
Fix by adding the following line in both queries [invoice_list, payment_entries] in utils.py -> get_outstanding_invoices()
`and is_cancelled = 0`

**Comment by Anuja-pawar** [comment]
The issue seems to be fixed, hence closing it.
