### ISSUE TITLE
Salary change in mid of the month.

### ISSUE THREAD

**Issue by jalajjsingh** [frappe/erpnext#22779]
## Hi All

We are in changing the salary in mid of the month, say from the 16th of July.

Now the payroll and the salary slip should be like that, salary for the first 15 days according to the old salary assignment and for the second 15 days, it should be according to the new salary assignment.

For example, an employee has a salary of 100 rupees for first the 15 days, and 200 rupees for the next 15 days, then the total salary should be calculated as rupees 150.

But the system is considering the last submitted salary assignment and calculating the salary according to that only.

## Context information (for bug reports)

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1.
2.
3.

### Stacktrace / full error message

```

```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by kennethsequeira** [comment]
This is not a bug but a configuration/use case mapping issue. Kindly post on the [forum](https://discuss.erpnext.com) for further help.
