### ISSUE TITLE
Budgeting Feature - CAPEX & Distribution Issues

### ISSUE THREAD

**Issue by THEOSKaris** [frappe/erpnext#22789]
1) ERPNext does not currently cover CAPEX budgeting. The feature should allow budgeting for Balance Sheet accounts like fixed assets. Very important feature.

2). Monthly Distribution:
     a) User ability to manually input monthly budget figures from scratch, and
     b) User ability to override monthly budget figures computed as per **Percentage Allocation**.

**Comment by THEOSKaris** [comment]
ERPNext does not currently cover CAPEX budgeting. The feature should allow budgeting for Balance Sheet accounts like fixed assets. Very important feature.

Monthly Distribution: User should be able to input or edit monthly budget amounts.

**Comment by aakvatech** [comment]
Was this completed already?

**Comment by THEOSKaris** [comment]
No, it's not completed! It was not even considered before it was closed.

**Comment by kishor-desarda** [comment]
_ChatGPT answer for this issue._
 In this case, you can try another approach by setting up a budget for a custom expense account related to capital expenditures and manually adjusting the balance sheet later.

Create a custom expense account for capital expenditures:
a. Go to "Explore > Accounting > Chart of Accounts."
b. Navigate to the "Expenses" group and click "Add Child."
c. Create a new account with an appropriate name, such as "Capital Expenditures" or "Asset Purchases," and set the account type as "Expense Account."
d. Save the new account.

Budget for capital expenses:
a. Go to "Explore > Budgeting and Cost Center > Budget" and click "New" to create a budget.
b. Set the fiscal year, budget against (Cost Center or Project), and select the appropriate cost center or project.
c. In the "Budget Accounts" section, click "Add Row" and select the custom expense account you created earlier (e.g., "Capital Expenditures").
d. Enter the budgeted amount for the fiscal year.
e. Save the budget.

Record capital expenses and adjust the balance sheet:
For every capital expenditure, you need to follow these steps:

a. Record the capital expenditure in the custom expense account created earlier, using a Purchase Invoice or Journal Entry.
b. Create a corresponding Asset record for the capital item in the "Explore > Assets and Liabilities > Asset" section.
c. Create a manual Journal Entry to transfer the value of the capital expenditure from the custom expense account to the appropriate fixed asset account. Debit the fixed asset account and credit the custom expense account.

By following these steps, you can set up a budget for capital expenses in ERPNext and maintain accurate financial statements. Although this approach requires manual adjustments to the balance sheet, it ensures that your capital expenditures are correctly reflected in your financial reports.

Please note that this is a workaround and may not be the most efficient way to manage capital expenditures and budgets in ERPNext. Ideally, the system should provide a more direct way to budget for fixed assets or capital expenditures, but currently, it does not have this feature.
