### ISSUE TITLE
[Feature Request] Add color field in Issue Doctype

### ISSUE THREAD

**Issue by AminovE99** [frappe/erpnext#22786]
**Is your feature request related to a problem? Please describe.**
The color can be used manually by the Support team to define a "meaning" to a color and thus quickly sort them.
Since the field is simply called color, the Kanban board GUI will automatically pick it up and display it.

**Describe the solution you'd like**
I am offer to add `color` field inside `Issue` doctype. We will not have any impact inside system.

**Additional context**
I already created pull request with changes for `version-12`, but it will be awesome to add all this feature to other versions.
https://github.com/frappe/erpnext/pull/22823/

**Screenshoots**
![image](https://user-images.githubusercontent.com/32329685/88169819-41eb0900-cc25-11ea-8cfd-0066a241fc59.png)

Link to forum: https://discuss.erpnext.com/t/feature-erpnext-v12-color-field-inside-issue-doctype/64049

**Comment by nanoharsha** [comment]
Do you think this color could be linked with priority, is that a use case ? 
Wondering where else this could be used ..

**Comment by abimu** [comment]
I welcome colour code

**Comment by AminovE99** [comment]
@nanoharsha I think, that we can investigate a lot of various to link this color field.
For example if we have link it with type of problem(customization Issue, Improvement Issue or Technical Issue).
or link it by owner of Feauture(client or company)
