### ISSUE TITLE
[Education > Fees] When creating Fees from Fee Structure, the Descriptions are not copied

### ISSUE THREAD

**Issue by ceefour** [frappe/erpnext#22781]
## Description of the issue

[Education > Fees] When creating Fees from Fee Structure, the Descriptions are not copied

## Context information (for bug reports)

**Output of `bench version`**
v13.beta.3

## Steps to reproduce the issue

1. In Fee Structure List, create a Fee Structure with description, e.g.

![image](https://user-images.githubusercontent.com/24123/88172758-af119500-cc4b-11ea-8558-52a4b6cc4ef5.png)

2. Create Fees, and use that Fee Structure

### Observed result

Fee Structure rows are copied, **except the descriptions**

![image](https://user-images.githubusercontent.com/24123/88172856-d2d4db00-cc4b-11ea-9c10-72a3ec97d81a.png)

### Expected result

Fee Structure rows copied including descriptions.

### Stacktrace / full error message

```
...
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

* Kubernetes 1.18
* ERPNext Helm chart 1.0.9
* ERPNext 13.beta.3

**Comment by ruchamahabal** [comment]
Fixed in: https://github.com/frappe/erpnext/pull/22792
Thanks for reporting. Closing

**Comment by ceefour** [comment]
Super thanks @ruchamahabal 🙏🙏🙏
