### ISSUE TITLE
Not working installation

### ISSUE THREAD

**Issue by Hbitvof** [frappe/erpnext#22809]
Hi,

Installation on both CentOS and Ubuntu is not working.

Tried it all day with different manuals but failed to succeed.

Please update your install instructions to get the software up and running on a fresh installed server.

**Comment by kennethsequeira** [comment]
@Hbitvof unless you have something specific to share, please post installation-related issues on the [forum](https://discuss.erpnext.com).

Add the method your tried with the error messages/traceback that showed up executing a certain step/command.
