### ISSUE TITLE
Healthcare: Cannot delete healthcare service unit type

### ISSUE THREAD

**Issue by mujeerhashmi** [frappe/erpnext#22810]
Here is the screenshot of the error.

![Selection_019](https://user-images.githubusercontent.com/12420747/88461164-d7ed9080-cebe-11ea-913c-f39616d8d249.png)

https://github.com/frappe/erpnext/blob/b2fccc1d05c7d705455d71f209acb47b18c821bc/erpnext/healthcare/doctype/healthcare_service_unit_type/healthcare_service_unit_type.py#L42

This is the reason. The linked item will never get deleted because it is linked to the existing healthcare service unit type.

**Comment by akurungadam** [comment]
You can delete the Healthcare Service Units of the type and then delete the Healthcare Service Unit Type. As you can see it's linked to the service units.

**Comment by mujeerhashmi** [comment]
> You can delete the Healthcare Service Units of the type and then delete the Healthcare Service Unit Type. As you can see it's linked to the service units.

I do not have any healthcare service units of this type. Just create Healthcare service unit type and delete is not possible.

**Comment by mujeerhashmi** [comment]
#22828 Fix by @ruchamahabal addressed this issue.
