### ISSUE TITLE
Wrong Fiscal Year and missing some VAT rates for Italy

### ISSUE THREAD

**Issue by fromthestone** [frappe/erpnext#22815]
Hi there,
I have noticed in the setup process, from Version 12 on, the fiscal year for Italy region is wrong.
it proposes from 1st of July to 30th of June, instead of the 1st of January to 31st December.

Are also missing some VAT rates that need to create by hand after setup

Please check my PR #22806

**Comment by kennethsequeira** [comment]
Fixed with: https://github.com/frappe/erpnext/pull/23623
