### ISSUE TITLE
Patient Appointment Detail Page issue for Website user

### ISSUE THREAD

**Issue by ashhwani** [frappe/erpnext#22817]
We have created on signup form for the Patient enrollments.
Created one webform of Patient Appointment Type
Now the user is able to login with Patient Role on the website without Desk access.
We are showing Patient Appointments on the sidebar for the website user
User can book a patient appointment page successfully
But issue when we try to see the appointment details then it freezes the webpage.
We can only see the Patient Id as a heading but no appointment information
We have to close the browser tab to work on it again.

**Comment by ruchamahabal** [comment]
@ashhwani Can you share screenshots or gifs so that we understand the issue better?

**Comment by ashhwani** [comment]
@ruchamahabal Thanks for the quick response. We have resolved that issue. The same was due to customisation. I am closing this issue.
