### ISSUE TITLE
Healthcare: No error check for time in InPatient occupancy transfers

### ISSUE THREAD

**Issue by mujeerhashmi** [frappe/erpnext#22826]
## Description of the issue
InPatient Record does not error check Checkout time is less than Check in time.
## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 13.0.0-beta.3
frappe 13.0.0-beta.3
```

Here is the print of InPatient record with checkout time less than checkin time.

![Selection_022](https://user-images.githubusercontent.com/12420747/88568977-69900600-d057-11ea-966d-32d4e2b8c5ab.png)

**Comment by ruchamahabal** [comment]
@mujeerhashmi This should fix it: https://github.com/frappe/erpnext/pull/22829
Closing.
