### ISSUE TITLE
Healthcare: The timestamp in Inpatient record are gibberish

### ISSUE THREAD

**Issue by mujeerhashmi** [frappe/erpnext#22824]
## Description of the issue
When the patient is admitted the timestamp in inpatient record are gibbersih.

## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 13.0.0-beta.3
frappe 13.0.0-beta.3
```

Check Admitted Date Time Field

![Selection_020](https://user-images.githubusercontent.com/12420747/88558918-d00e2780-d049-11ea-8faf-62e2ee21de87.png)

Check Inpatient Occupancy Child Table

![Selection_021](https://user-images.githubusercontent.com/12420747/88558934-d4d2db80-d049-11ea-92e5-7622c833935c.png)

**Comment by ruchamahabal** [comment]
@mujeerhashmi this is a framework constraint

Please make sure you have set the date format and time format in System Settings

![system-settings](https://user-images.githubusercontent.com/24353136/88632745-a567b180-d0d1-11ea-8c86-c54b27eb4643.png)

**Comment by mujeerhashmi** [comment]
> @mujeerhashmi this is a framework constraint
> 
> Please make sure you have set the date format and time format in System Settings
> 
> ![system-settings](https://user-images.githubusercontent.com/24353136/88632745-a567b180-d0d1-11ea-8c86-c54b27eb4643.png)

This solves the issue. Closing
