### ISSUE TITLE
Healthcare: Get Items from healthcare services in Sales Invoice is fetching cancelled appointments

### ISSUE THREAD

**Issue by mujeerhashmi** [frappe/erpnext#22831]
https://github.com/frappe/erpnext/blob/212648044ff7fa64f526e630e9e73155fd4240ad/erpnext/healthcare/utils.py#L43

We will need to fetch only scheduled appointments. May be we will need `'status': 'Scheduled'` filter as well.

**Comment by ruchamahabal** [comment]
fixed in https://github.com/frappe/erpnext/pull/22836 by @akurungadam 
Closing
