### ISSUE TITLE
Accounts Receivable Summary mismatch with General ledger and Customer Ledger Summary-v13

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#22846]
- General Ledger Debit Amount and Customer Ledger Summary Invoiced Amount agree.
- General Ledger Credit Amount and Customer Ledger Summary Paid Amount do not agree, because Paid Amount in CLS includes cancelled entries.
- 
- Invoiced Amount and Paid Amount in Accounts Receivable Summary, do not agree with what's on the GL and Customer Ledger Summary. Could be a reason for this, but it's not clear where the figures in the Accounts Receivable Summary come from.

**Comment by doworks** [comment]
Most of the queries and reports that related to GL Entry are missing [is_cancelled = 0] condition

**Comment by muchai** [comment]
- Outstanding amounts in A/R Summary and Customer Ledger Summary agree

- Outstanding amounts in A/R Summary and Customer Ledger Summary do not agree/tally with Balance amount in General Ledger

**Comment by mujeerhashmi** [comment]
> Most of the queries and reports that related to GL Entry are missing [is_cancelled = 0] condition

I am seeing cancelled entry accounted for in customer ledger summary. This needs to be fixed.
