### ISSUE TITLE
Edit stock balance table

### ISSUE THREAD

**Issue by ghost** [frappe/erpnext#22893]
Hi guys,
I want to edit the table in stock balance(page?). Currently it has too many columns I don't need. I want only item number, name, description, qty, mnf pn...
Why I can't customize table in customize form command? I can only temporarily edit the table.
ERPNext v12 on VM

**Comment by kennethsequeira** [comment]
@Pararera if you're referring to the stock balance report, after removing the column, save the report as a new one:

![image](https://user-images.githubusercontent.com/33246109/89250228-e3b12380-d631-11ea-8f4b-0df47ee77439.png)

In future, post all customization related queries on the [forum](https://discuss.erpnext.com).

**Comment by ghost** [comment]
And, for every report I have to do same job?

**Comment by kennethsequeira** [comment]
@Pararera yes, this is the quickest way to go about.

Like i said, customization queries are better served on the [forum](https://discuss.erpnext.com).
