### ISSUE TITLE
In most doctypes, a user has to click twice on the save button for a record to be saved-v13

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#22890]
![image](https://user-images.githubusercontent.com/1822868/89166119-36cb9d80-d582-11ea-8631-cce3066155d4.png)

**Comment by manasan3010** [comment]
Yeah, this is reproducible for me too. I think this is because of the validation taking place on the first click.
This is causing serious user discomfort

**Comment by vondergrafschaft** [comment]
Yes, very annoying. Definitely needs a fix.
