### ISSUE TITLE
SyntaxWarning: str indices must be integers or slices, not tuple;

### ISSUE THREAD

**Issue by Lymperis79** [frappe/erpnext#22906]
## Description of the issue

/apps/erpnext/erpnext/startup/leaderboard.py:126: SyntaxWarning: str indices must be integers or slices, not tuple; perhaps you missed a comma?
  filters.append(['posting_date', 'between' [date_range[0], date_range[1]]])

## Steps to reproduce the issue

1. run bench update 
2. the error is coming during the update 
3.

``

## Additional information

OS version / distribution, `ERPNext` install method, etc.
i have erpnext version-13-beta-pre-release installed! in ubuntu 20.04

**Comment by marination** [comment]
https://github.com/frappe/erpnext/pull/23249 fixed
