### ISSUE TITLE
TypeError: not all arguments converted during string formatting While Creating Purchase Order on Item selection ERPNEXT V 13 Beta

### ISSUE THREAD

**Issue by nishith121** [frappe/erpnext#22917]
Description of the issue

We are creating Purchase Order in ERPNEXT V13 Beta and receiving error TypeError: not all arguments converted during string formatting on Item Selection. 

![image](https://user-images.githubusercontent.com/69237290/89388438-a7f58700-d721-11ea-9d6d-662ffc9f4252.png)

## Steps to reproduce the issue

1.Maintain all master required to Create Purchase -Customer,Item Code, Warehouse, Tax and Charge Templates,Price list
2.Create New Purchase Order and Select Supplier , Required By Date,Price List, Target Warehouse
3.Add Row of Item from Drop down - Received Error

### Observed result
Error - TypeError: not all arguments converted during string formatting
### Expected result
Purchase Order to Create with any issue

Process is being carried out in Erpnext and Frappe Version 13 Beta

**Comment by michellealva** [comment]
Could not replicate this on the latest version. Please check on the latest version and let us know if the issue persists.

**Comment by zuron7** [comment]
+1

Currently on the following version of ERPnext and having the same issues. 

Installed Apps

ERPNext: v12.16.2 (HEAD)

Frappe Framework: v12.13.0 (HEAD)

**Comment by multidoc** [comment]
I have the same issue but when interting items on a sale order / invoice
when closing a sale order

ERPNext: v14.36.0 (version-14)

Frappe Framework: v14.46.0 (version-14)

Frappe HR: v15.0.0-dev (version-14)

Payments: v0.0.1 (develop)

POS Awesome: v6.1.3 (develop)
