### ISSUE TITLE
HTML Editor Missing - Newsletter

### ISSUE THREAD

**Issue by sivadotblog** [frappe/erpnext#22910]
Create a New Newsletter option

Per ERPNext documentation, there used to be an HTML editor right next to the rich text editor icons. I cannot find that option in my ERP Next software. Is it purposefully disabled? how to enable it?

version
ERPNext: v12.3.1 (version-12)
Frappe Framework: v12.1.0 (version-12)

**Comment by kennethsequeira** [comment]
@sivanandha

The editor you're referring to was replaced in version 11 onwards.
