### ISSUE TITLE
[Bug] Standard Reply in Support Ticket Reply results in 'undefined' when Cleared

### ISSUE THREAD

**Issue by ankitjavalkarwork** [frappe/erpnext#2292]
1. Selected a Standard Reply in Support Ticket Reply window
1. Prints the desired Standard Reply in the Message Text Area
1. Cleared the Standard Reply field
1. Prints 'undefined' in the Text Area

Screen shot after clearing Standard Reply field;
![support_undefined_github_issue](https://cloud.githubusercontent.com/assets/7963818/4590275/c7f1bbf6-505d-11e4-865c-4c788987c552.png)

**Comment by vjFaLk** [comment]
Fixed
