### ISSUE TITLE
Scrap Management in Sub Contracting(Bug Not Working) 

### ISSUE THREAD

**Issue by dexterhussain** [frappe/erpnext#22949]
Dear All,

We are fabric manufacturing unit , we are struggling with new kind of issue , When a fabric is sent for dye some fabric comes as B-Grade that is scrap but it is sold.
I have created BOMs and added Scrap in that but when I am adding Scrap in Purchase Receipt it is showing me no effect , I am adding scrap of 370 Meters in Purchase receipt but it is not deducting it from the raw material.
any solution? The only solution i can think of is to add a new BOM for B-Grade and Consume it but it will seriously affect costing

**Comment by deepeshgarg007** [comment]
@dexterhussain Closing this issue. Please try this https://docs.erpnext.com/docs/v13/user/manual/en/manufacturing/articles/scrap-management on the latest version and reopen if the issue still persists
