### ISSUE TITLE
Ability to "Flush" a batch

### ISSUE THREAD

**Issue by RealDesignGraphics** [frappe/erpnext#2295]
I would like the ability to easily zero out a batch or at least when I select a batch in a stock entry, it tells me exactly how much is left in the batch (not the warehouse) so I can easily enter the info.

**Comment by RealDesignGraphics** [comment]
Is there any word of if this can become possible? There needs to be some more easily accessible tools from a lot/batch perspective not being able to easily pull quantity information from the batch screen (not history ... I just want to know, in a simple format, how many gallons i have left in a batch)

**Comment by umairsy** [comment]
Simply stock-out?
