### ISSUE TITLE
Website on localhost showing underconstruction

### ISSUE THREAD

**Issue by Utesar72** [frappe/erpnext#22962]
Hi, how to solve this issue. Pls help

Thaks in advance.."................."......"..............................

**Comment by Utesar72** [comment]
I mean under development instead of construction

**Comment by barry86m** [comment]
Is this still a problem?

If so, can you provide more details?
- What installation method did you use?
- What output does running `bench version` in the terminal give?
- Do you have any other web servers running?
- Can you provide a screenshot?

If it's not a problem, can you close this issue?

**Comment by kennethsequeira** [comment]
Closing due to lack of description or further correspondence.
