### ISSUE TITLE
UnboundLocalError: local variable 'e' referenced before assignment in New POS-v13.0.0-beta.4

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#22964]
![image](https://user-images.githubusercontent.com/1822868/89728280-d2528780-da34-11ea-8463-e77784bb13a7.png)

- Happens when buttons Complete Order or Save as Draft are clicked.

- Also, when you go to pas orders, it's not obvious how to go back to the cart/or origin location in the cart.

- In addition, other than searching on the global search, there's no menu item/link to the new POS.

**Comment by michellealva** [comment]
Could not replicate this issue, can you please recheck?

**Comment by muchai** [comment]
True. It seems it's specific to a site, just tested on another site, and all works well.

Experienced this on printing though.

When print from the POS final window.
![image](https://user-images.githubusercontent.com/1822868/89759547-173cf380-daf3-11ea-9f1c-dd3dac2a6b70.png)

When you open the PS invoices list, and print from there
![image](https://user-images.githubusercontent.com/1822868/89759511-042a2380-daf3-11ea-8e64-e91303a1026f.png)

**Comment by Vishalcse** [comment]
today, i'm also facing the same issue...anyone help me out to fix this issue.

**Comment by Vishalcse** [comment]
> Could not replicate this issue, can you please recheck?

how can be solve this issue?

**Comment by PatroxGaurab** [comment]
Having the same issue, did you find any ways to resolve it?

**Comment by muchai** [comment]
No solution yet, it's a special case though, since this error was in one site, but in another site, the POS works fine.
Will look into the site with the error for the exact/probable cause.

**Comment by Soltenc2019** [comment]
I have the same problem. Please if someone could solve it?

**Comment by Soltenc2019** [comment]
> ![image](https://user-images.githubusercontent.com/1822868/89728280-d2528780-da34-11ea-8463-e77784bb13a7.png)
> 
> * Happens when buttons Complete Order or Save as Draft are clicked.
> * Also, when you go to pas orders, it's not obvious how to go back to the cart/or origin location in the cart.
> * In addition, other than searching on the global search, there's no menu item/link to the new POS.


I resolved the error message. In sales configuration put the check of "Allow to add the item several times in a transaction"

**Comment by Soltenc2019** [comment]
I resolved the error message. In sales configuration put the check of "Allow to add the item several times in a transaction"

**Comment by nextchamp-saqib** [comment]
@muchai Can you open up Javascript console (Ctrl + Shift + i or Cmd + Option + i) and send a screen shot when the error pops up?

**Comment by muchai** [comment]
@nextchamp-saqib
Failed to load resource: the server responded with a status of 500 (INTERNAL SERVER ERROR)
desk.min.js:1 Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 19, in savedocs
    doc.submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 901, in submit
    self._submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 890, in _submit
    self.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 285, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 307, in _save
    self.insert()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 238, in insert
    self.run_before_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 934, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 831, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1116, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1099, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 825, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/pos_invoice/pos_invoice.py", line 29, in validate
    super(SalesInvoice, self).validate()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/selling_controller.py", line 49, in validate
    self.validate_for_duplicate_items()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/selling_controller.py", line 416, in validate_for_duplicate_items
    if e in check_list:
UnboundLocalError: local variable 'e' referenced before assignment

DevTools failed to load SourceMap: Could not load content for webpack://Quill/node_modules/quill-delta/dist/Delta.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://Quill/node_modules/quill-delta/dist/AttributeMap.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://Quill/node_modules/quill-delta/dist/Op.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://Quill/node_modules/quill-delta/dist/Iterator.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://Quill/node_modules/quill-delta/dist/Delta.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://Quill/node_modules/quill-delta/dist/AttributeMap.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://Quill/node_modules/quill-delta/dist/Op.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://Quill/node_modules/quill-delta/dist/Iterator.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for https://mazao.navari.co.ke/assets/js/awesomplete.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by nextchamp-saqib** [comment]
Fixed with #23896
