### ISSUE TITLE
Spaces removed when creating comments on Firefox

### ISSUE THREAD

**Issue by LtnPjk** [frappe/erpnext#22961]
## Description of the issue
Spaces between words are removed when typing comments
## Context information (for bug reports)

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1. Type new comment in task/project etc. with Mozilla Firefox 79 browser. (Both Windows 10 and Arch Linux have this issue)

### Observed result
Spaces are removed
### Expected result
Spaces remaining
### Stacktrace / full error message

```
(paste here)
```

## Additional information

Windows 10/ Arch Linux, frappecloud ERPnext version 13 beta

**Comment by kennethsequeira** [comment]
@LtnPjk 

share the exact Frappe and ERPNext versions. This was supposed to be fixed some time back: https://github.com/frappe/frappe/pull/10984

**Comment by LtnPjk** [comment]
I updated a few days ago and just tried with firefox again, it works fine now.

ERPNext: v13.0.0-beta.4 (HEAD)

Frappe Framework: v13.0.0-beta.4 (HEAD)
