### ISSUE TITLE
General Ledger : Can't Scroll Up & Down using touchpad/mouse, and Not shown vertical scroll bar

### ISSUE THREAD

**Issue by RevitaRamadhanty** [frappe/erpnext#22969]
## Description
Issue on General Ledger in ERPNext

## Context information (for bug reports)

**Output of `bench version`**
```
ERPNext 13.beta.4
```

## Steps to reproduce the issue

1. Open General Ledger
2. Can scroll left and right, but can't scroll up and down
3. So the alternative we can only use arrow keys to scroll up and down

### Observed result
* Can't scroll down in general ledger using touchpad / mouse
* Vertical Scroll bar is not shown

https://youtu.be/G4U3zryIBko

### Expected Result
* Can scroll down in general ledger using touchpad
* Can show Vertical scroll bar
### Stacktrace / full error message

OS version / distribution, `ERPNext` install method, etc.
ERPNext 13.beta.4

**Comment by asoral** [comment]
Same here
