### ISSUE TITLE
Unable to save domain settings

### ISSUE THREAD

**Issue by roshanjonah** [frappe/erpnext#23005]
Using the latest ERPNext (Edge) versions and unable to save the domain settings. It says no changes are made to the form as in the GIF below. 

![Aug-12-2020 14-47-43](https://user-images.githubusercontent.com/20136098/89969571-d5ef4400-dcaa-11ea-9ef0-307a86249365.gif)

**Comment by jorgeatcabo** [comment]
I have the same problem, I have several weeks trying, I can't save the email domain when the settings are from AWS workmail, but with office365 I can.
