### ISSUE TITLE
fix: AttributeError: 'ProgramFee' object has no attribute 'course'

### ISSUE THREAD

**Issue by aakvatech** [frappe/erpnext#23030]
Error occurs while program enrollment on new student.

This happens on version 12 and not on version 13.

Version 12 uses 
course_list = [course.course for course in program._**get_all_children()]**_

where as version 13 uses
course_list = [course.course for course in program._**courses]**_

https://github.com/frappe/erpnext/blob/80c016a1ada3b4af9d1df47f491d4a3d679d91dc/erpnext/education/doctype/program_enrollment/program_enrollment.py#L74

**Comment by fderyckel** [comment]
Similarly (same line of code I believe)
https://github.com/frappe/erpnext/issues/23197

**Comment by ruchamahabal** [comment]
fixed by @aakvatech in https://github.com/frappe/erpnext/pull/23037. Closing
