### ISSUE TITLE
Supplier Quotation comparison to be added in the standard product

### ISSUE THREAD

**Issue by CHARUDATTAPUROHIT** [frappe/erpnext#23046]
At present only option to compare prices quoted by different suppliers is by using the option Buying --> Quoted Item Comparison.However this option provides comparison of prices for only one item at a time. 
If multiple items exists in a Request for Quotation and the Request for quotation has been quoted by Multiple Suppliers, there is no provision in the system to compare the prices of all items in the Supplier Quotations .

option to compare all items at one go to provided for a Supplier quotation or For a Request for Quotation

**Comment by michellealva** [comment]
Check: https://github.com/frappe/erpnext/pull/23127

**Comment by CHARUDATTAPUROHIT** [comment]
The feature is working as desired. Thanks
