### ISSUE TITLE
ERPNext Version13 SI Customer Name Issue

### ISSUE THREAD

**Issue by sammish** [frappe/erpnext#23056]
Dear Frappe.cloud

We have an issue in Sales Invoice Customer name.

When we select the customer the SI field, the customer name not appeared before save invoice

Please check

![qqq](https://user-images.githubusercontent.com/12432802/90370565-46fd7580-e076-11ea-9975-5c2a8000c65d.gif)

**Comment by sammish** [comment]
@adityahase @nabinhait 

Please look this also

**Comment by marination** [comment]
@sammish Correct me if I'm wrong. If the problem is that **Customer Name in Arabic** is not getting updated, it's a custom field added on your end for which you will have to script and fetch this value. This isn't a bug.

**Comment by sammish** [comment]
@marination**Customer Name in Arabic** which is part of erpnext,  I did not add.

**Comment by marination** [comment]
@sammish yeah didnt notice its a regional field for UAE. This field fetches data from **Customer Name in Arabic** field in the **Customer** doctype. You can check whether this is populated in the Customer you are fetching.

**Comment by sammish** [comment]
@marination This is the error.

![image](https://user-images.githubusercontent.com/12432802/92131111-3d159980-ee0e-11ea-92d7-0fc06f0ea658.png)

**Comment by sammish** [comment]
@marination 
Okay, I think I have customization in SI. 
Let me discuss with Developer.

**Comment by sammish** [comment]
@marination 

I discussed with my developer and he confirmed  the issue from ERPNext .
