### ISSUE TITLE
Write off is lost upon payment entry. Wrong outstanding shown.

### ISSUE THREAD

**Issue by rtdany10** [frappe/erpnext#23068]
## Description of the issue
Write off in sales invoice is lost upon payment entry and the outstanding amount shown is wrong.

## Steps to reproduce the issue
![errorgif](https://user-images.githubusercontent.com/52111700/90506483-fd925080-e171-11ea-93fd-a3a944d0957c.gif)

**Comment by dj12djdjs** [comment]
Ignore previously linked PRs. Unrelated.
