### ISSUE TITLE
[v13] point of sales - cart not getting updated after scanned using barcode scanner

### ISSUE THREAD

**Issue by laxmantandon** [frappe/erpnext#23060]
## Description of the issue
While making pos invoice, After scanning a barcode with barcode scanner, the product is not getting added to cart automatically, i have to press enter key, (it slows down the billing process).

I checked with my barcode scanner its transmitting enter key after barcode and its working fine in v12 point of sale.

## Steps to reproduce the issue
1. in the Search bar type 'Open Point of Sale'
2. in the barcode scan field scan a barcode using a barcode scanner 
3. Observe the cart, its not getting updated, need to press enter extra enter key

![pos enter key issue](https://user-images.githubusercontent.com/24727535/90408095-feb97400-e0c4-11ea-8da6-9db6029a34e5.gif)

ERPNext: v13.0.0-beta.4 (version-13-beta)
Frappe Framework: v13.0.0-beta.4 (version-13-beta)

**Comment by olamide2** [comment]
This is a confirmed bug, we should try and resolve it

**Comment by janakact** [comment]
+1 We also need this feature.

**Comment by staumoepeau** [comment]
Still the same. This is where I am with the version:

ERPNext: v13.0.0-beta.11 (version-13-beta)
Frappe Framework: v13.0.0-beta.10 (version-13-beta)

**Comment by amendsaccounting** [comment]
Any Update on this ?

**Comment by arcadio-nseng** [comment]
was this bug fixed?

**Comment by ssiyad** [comment]
Works fine with `Automatically Add Filtered Item To Cart` checked in `POS Profile`.
