### ISSUE TITLE
V13-Landed Cost Voucher (Account Balance and Stock Value is out of sync. Please create adjustment Journal Entry for amount)

### ISSUE THREAD

**Issue by sammish** [frappe/erpnext#23115]
ERPNext: v13.0.0-beta.4 (HEAD)

Frappe Framework: v13.0.0-beta.5 (HEAD)

![Untitled-Project](https://user-images.githubusercontent.com/12432802/90955244-9da6ed00-e484-11ea-878c-f474741d2a55.gif)

**Comment by sammish** [comment]
@nabinhait @adityahase @deepeshgarg007

**Comment by marination** [comment]
@sammish Check the Report **Stock and Account Value Comparison**, that should tell you which transaction is causing a difference in your Stock Balance and Account Balance

**Comment by sammish** [comment]
@marination 
Hum, This is the Reason.
https://github.com/frappe/erpnext/pull/22366 
Even, If we Change the **time** during the Invoice Time, we will face a lot of stock variance that day.We have to pass Stock entry via JV.

**I am studying right now How to manage the situation real environment.**

If ERPNEXT make as optional that would be more safe for the real environment. Because the migration time we need to more adjustment entries.


Anyhow now okay.

**Comment by sammish** [comment]
@marination Also, We can't make stock adjustment if even **Debit** side Stock In Hand.

Stock In Hand **Credit** we can adjust through the JV.
