### ISSUE TITLE
Become Expense Approver must checklist System Manager

### ISSUE THREAD

**Issue by RevitaRamadhanty** [frappe/erpnext#23134]
## Context information (for bug reports)

**Output of `bench version`**
```
(ERPNext 13.beta.4)
```

## Steps to reproduce the issue
*Ex: Zaky as Expense Approver, Ellena as Employee wants to make expense claim to Zaky as expense approver
1. On user Zaky, if we want him become "Expense Approver" checklist that column
2. But if we only checklist "Expense Approver" only, and if Ellena want to making expense claim to expense approver Zaky, there is nothing in expense claim Zaky
3. So if want expense claim Ellena appear in expense claim Zaky, user Zaky must checklist on column "System Manager"

### Observed result
*Ex: Zaky as Expense Approver
I want make Zaky to be Expense approver for approver some expense claim from other employee, but not only checklist "Expense claim" in user, it must be checklist "System Manager" too, Whereas i'm only want Zaky to be expense approver not can access more in ERPNext as System Manager.

https://www.youtube.com/watch?v=eCN6USNhWp8

### Expected result
*Ex: Zaky as Expense Approver
I want make Zaky only being to Expense Approver for some expense claim from other employee, without making Zaky to be "System Manager".

### Stacktrace / full error message

```
(ERPNext 13.beta.4)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.
ERPNext 13.beta.4

@ceefour

**Comment by kennethsequeira** [comment]
@RevitaRamadhanty please set up the expense approver in department/employee correctly as well. 

Refer the [docs](https://docs.erpnext.com/docs/user/manual/en/human-resources/department#31-leave-and-expense-approvers) when required or post on the [forum](https://discuss.erpnext.com) instead of marking incorrect configs as bugs directly.
