### ISSUE TITLE
PoS opening entry not closed when corresponding PoS Closing entry is submitted v13 -beta 4

### ISSUE THREAD

**Issue by olamide2** [frappe/erpnext#23130]
When a Cashier opens for the day, a PoS opening entry is raised and submitted
When the Cashier closes for the day, a PoS closing entry is raised and submitted 
When the PoS Closing entry is submitted the status of the corresponding PoS opening entry should be changed to closed.

This is not happening at the moment and leads to all opening entries remaining open and causing confusing for the retail staff.

This needs to be fixed

**Comment by deepeshgarg007** [comment]
@olamide2 Please reopen a new issue if this still persists in the latest version-13 or higher releases
