### ISSUE TITLE
Expense Approver, Assign to, Share with

### ISSUE THREAD

**Issue by RevitaRamadhanty** [frappe/erpnext#23135]
## Context information (for bug reports)

**Output of `bench version`**
```
(ERPNext 13.beta.4)
```

## Steps to reproduce the issue
*Ex: Zaky as Expense Approver, Ellena as employee wants to give Expense Claim
1. Open Expense claim on Ellena employee and making new "Expense Claim", and must fill Expense Approver, Assign to, and Share With

### Observed result
After some employee making expense claim and only fill Expense Approver, the expense claim not automatically appear on the expense approver, so i must fill assign to and share with to expense approver.

https://www.youtube.com/watch?v=8YfRuM0ko_M

### Expected result
Expense claim made by some employee and only fill Expense Approver must be automatically appear on expense approver some approver, without fill assign to and share with

### Stacktrace / full error message

```
(ERPNext 13.beta.4)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.
ERPNext 13.beta.4

@ceefour

**Comment by kennethsequeira** [comment]
Set expense approver in department or for the employee.
