### ISSUE TITLE
Option "Create" Payment don't appear on ERPNext

### ISSUE THREAD

**Issue by RevitaRamadhanty** [frappe/erpnext#23133]
## Context information (for bug reports)

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1. Open Sales Invoice
2. After click save, commonly shown option "create"
3. But in this case, option "create" not appear
4. So, if want to make payment entry must make manually

### Observed result
Option "Create" payment not shown after save and submit sales invoice

https://www.youtube.com/watch?v=ED8288EJmE0

### Expected result
There is option "Create" payment  after save and submit sales invoice

### Stacktrace / full error message

```
(ERPNext 13.beta.4)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.
ERPNext 13.beta.4

@ceefour

**Comment by michellealva** [comment]
@RevitaRamadhanty could not replicate this issue in my test account.


![image](https://user-images.githubusercontent.com/50285544/91123447-881b0880-e6ba-11ea-97e7-4d27a9dd0446.png)

**Comment by kennethsequeira** [comment]
@RevitaRamadhanty payment creation option only reflects after submitting the invoice, not in draft as seen in the video.
