### ISSUE TITLE
Employee Leave balance does not filter for company, i.e. it displays all employee leaves despite there being a company filter - v13-5

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#23155]

**Comment by ruchamahabal** [comment]
Cannot reproduce. Company filter is applied to the data

![Kapture 2022-01-31 at 22 02 03](https://user-images.githubusercontent.com/24353136/151833786-a148ca29-4c01-4add-9be6-a2111aa167e4.gif)

Closing.
