### ISSUE TITLE
Wrong qty in STE for manufacturing

### ISSUE THREAD

**Issue by ghost** [frappe/erpnext#23159]
Hi,
found bug in stock entry for manufacturing. If I want to build 450 pcs from work order(work order is for 600 pcs), in STE required qty is for total quantity(not selected).
So, for item 3220-001 requires 105 pcs of item 1000-004. 105 pcs times 450 pcs is 47250 pcs, while system puts 63000 pcs.
63000 pcs are required for 600 pcs of 3220-001 item(105*600).

![Screenshot](https://user-images.githubusercontent.com/43913022/91177717-6e8eb680-e6e4-11ea-8581-e18d528af907.png)

**Comment by deepeshgarg007** [comment]
Please reopen a new issue if this still persists in the latest version-13 or higher releases
