### ISSUE TITLE
V12 & V13 - Payment Entry Report Filter based on status (!= Cancelled) does NOT work. Incorrect Payment Entry Status in Report. 

### ISSUE THREAD

**Issue by zerodiscount** [frappe/erpnext#23181]
## Description of the issue
Payment Entry Report shows incorrect status - shows as submitted when payment entry actual status is cancelled. When you add column "status" to a payment entry report - even cancelled payment entries show up as submitted. Consequently filter based on Status does not work.

## Context information (for bug reports)

**Output of `bench version`**
```
ERPNext: v12.11.1 (version-12)
Frappe Framework: v12.9.0 (version-12)

Also tested on 
ERPNext: v13.x.x-develop () (develop)
Frappe Framework: v13.x.x-develop () (develop)
```

## Steps to reproduce the issue

1. Create Payment Entry. Then Cancel it. Ensure status shows Cancelled. Create another Payment Entry.
2. Open Reports (Payment Entry) - Pick Columns - choose to add Status column to report.
3. Cancelled Payment Entry on report column status will show as Submitted.

### Observed result
Cancelled Payment Entry status (in Report) will show as Submitted. Clicking on the payment entry - and opening it - status will show Cancelled (which is correct) but incorrect in report column. Report Filter !=Cancelled will still show Payment Entries that are cancelled.

### Expected result
Cancelled Payment Entry should show with Status Cancelled in Report.

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by deepeshgarg007** [comment]
![Uploading image.png…]()

Status is shown correctly, closing this issue
