### ISSUE TITLE
Education.  Issue with enrollment date. 

### ISSUE THREAD

**Issue by fderyckel** [frappe/erpnext#23198]
https://github.com/frappe/erpnext/blob/10c7faf090b6cbf91ef94e02b654382a90ed6cb2/erpnext/education/doctype/program_enrollment/program_enrollment.py#L76

The enrollment date is not correct.  It should be the enrollment date from the program enrollment date field.  You can pre-enrolled student in advance.  That's why we have that field.  Adn the enrollment will only take effect the date that is indicated there .

**Comment by fderyckel** [comment]
Adding this will do the trick
enrollment_date = self.enrollment_date

**Comment by ruchamahabal** [comment]
Fixed in: https://github.com/frappe/erpnext/pull/23333. Closing
