### ISSUE TITLE
Letterhead doesn't change on change of company in any transaction-v13-5

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#23196]
If say you pick company A,and then change to company B on a transaction, the letterhead of A still remains on the transaction.

**Comment by kennethsequeira** [comment]
@muchai care to explain how this is a bug? 

A letterhead is not bound to a company so is not expected to change with selection. You can change this writing a custom script so that the value is bound to a company or block user access with permissions.

**Comment by muchai** [comment]
@kennethsequeira 

The scenario is. On documents, say on material request, the system picks the default letterhead. Default as selected on Letterheads.
If no letterhead is selected as default, no letter head is picked on the document.
Thing is, for multi-company scenario, each company can have a default letterhead on the company document.
The expected behavior is the system would pick the default letterhead set for each company in documents.

**Comment by kennethsequeira** [comment]
@muchai you can work around this one by adding a link field for Letterhead in Material Request (or any other document). 

Even though there is a default letterhead, you will be able to change the same manually. For automation, I've already suggested the way of custom script or permissions (or even session defaults) to help with this situation.

This can be requested as an enhancement or UX issue to work out of the box, but not a bug.

**Comment by muchai** [comment]
@kennethsequeira this is in order. Will use a custom script for the same.

I agree, it's an enhancement rather than a bug.

Thank you very much for your reply.
