### ISSUE TITLE
need to create user name and password and need to change domain name through ssh

### ISSUE THREAD

**Issue by meahmedh** [frappe/erpnext#23207]
Please post on our forums:

for questions about using `ERPNext`: https://discuss.erpnext.com

for questions about using the `Frappe Framework`: ~~https://discuss.frappe.io~~ => [stackoverflow](https://stackoverflow.com/questions/tagged/frappe) tagged under `frappe`

for questions about using `bench`, probably the best place to start is the [bench repo](https://github.com/frappe/bench)

For documentation issues, use the [ERPNext Documentation](https://erpnext.com/docs/) or [Frappe Framework Documentation](https://frappe.io/docs/user/en) or the [developer cheetsheet](https://github.com/frappe/frappe/wiki/Developer-Cheatsheet)

> **Posts that are not bug reports or feature requests will not be addressed on this issue tracker.**

**Comment by kennethsequeira** [comment]
Either add the correct description or consider posting on the [forum](https://discuss.erpnext.com).
