### ISSUE TITLE
Conversion from Current Asset to Fixed Asset

### ISSUE THREAD

**Issue by Dilip-Weisdom** [frappe/erpnext#23203]
We manufacture our sub-product from third parties and then assemble it and then rent it out. We do not sell the product.
So I as we manufacture the final product it goes into current asset (a standard accounting process). However as we do not sell the product and instead use it for our own purpose, it should be moved to fixed asset.

There we need a button/process by which one should be able to select a finished product with its serial number and move it to fixed asset. (the same we you allow creating Fixed asset from PI/PO) along with final cost of the product.

**Comment by wojosc** [comment]
I have found a semi elegant work around for this. Check it out here: https://handbuch.tueit.de/books/erpnext-benutzerhandbuch/page/vermogenswerte-mit-seriennummern

If a google-translation won’t work to make it understandable send me a message

**Comment by Dilip-Weisdom** [comment]
sure, let me try it out.
