### ISSUE TITLE
Data Export : does not allow you to select DocType: Issue

### ISSUE THREAD

**Issue by rohitk75** [frappe/erpnext#23208]
Data Export : does not allow you to select DocType: Issue
ERPNext: v13.0.0-beta.4 (version-13-beta)

Frappe Framework: v13.0.0-beta.5 (version-13-beta)
![Data Export](https://user-images.githubusercontent.com/7210284/91646034-2b25a680-ea5c-11ea-8c11-63edbde04a85.png)

**Comment by kennethsequeira** [comment]
Allow **Export** via the role permission system for your role.

**Comment by kennethsequeira** [comment]
Allow **Export** via the role permission system for your role.
