### ISSUE TITLE
Need to academic Term

### ISSUE THREAD

**Issue by fderyckel** [frappe/erpnext#23200]
https://github.com/frappe/erpnext/blob/d4af7d612deda7a27d2086a91a0187fcdf90dcb1/erpnext/education/doctype/program_enrollment/program_enrollment.py#L29

Only academic year is referenced and not academic term

**Comment by fderyckel** [comment]
On top of academic terms, you may want to add these validation errors: 

		term_dates = frappe.get_doc("Academic Term", self.academic_term)
		if self.enrollment_date and getdate(term_dates.term_start_date) and getdate(self.enrollment_date) < getdate(term_dates.term_start_date): 
			frappe.throw(_("Courses enrollment for this program are not within the given term dates."))
		if self.enrollment_date and getdate(term_dates.term_end_date) and getdate(self.enrollment_date) > getdate(term_dates.term_end_date): 
			frappe.throw(_("Courses enrollment for this program are not within the given term dates."))

At the moment, you can enroll a course for an academic year at dates outside that academic year...

**Comment by ruchamahabal** [comment]
fixed in: https://github.com/frappe/erpnext/pull/23333. Closing
