### ISSUE TITLE
All Applications Module

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#2321]
Hi,

Can we please make it possible to hide the All Applications module just like every other module? Currently, when you try to hide it, it remains visible!

Also, when the All Applications Module is visible, can we ensure that users don't see the Setup module (from within All Applications) at all unless they are given permissions that specifically relate to Setup? Right now, all users can view the Setup module through the All Applications module!

Many thanks!

**Comment by Olawale1** [comment]
Hi guys, any update on this please? Its actually a serious issue for some of us! What is the reason why the All Applications module MUST be visible to all users? Please help resolve this. At least give us the choice of hiding it just like all other modules!

**Comment by umairsy** [comment]
Olawale,

Let's assume an HR manager has permission to import Employee, and he can
also do User Permission Setting for other Employee.

In this case, even as HR Manager, who is not a System Manager get's
permission to Setup module. But this access will be restricted to Data
Import and User Permissions only. That user will not be able to access
other functions in Setup module.

Just tried replicating this locating, and found that Setup Icon is still
not visible on the home page. But that user can access Import and
Permission function via options available in the list view page of
documents.

On Thu, Feb 12, 2015 at 3:59 PM, Olawale1 <notifications@github.com> wrote:

> Hi guys, any update on this please? Its actually a serious issue for some
> of us! What is the reason why the All Applications module MUST be visible
> to all users? Please help resolve this. At least give us the choice of
> hiding it just like all other modules!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/frappe/erpnext/issues/2321#issuecomment-74049034>.
>



-- 
Thanks and Regards,
Umair Sayyed
www.erpnext.com

**Comment by Olawale1** [comment]
Hi Umair, Thanks for your response. The scenario you have given is a good one. The HR manager in that case is given permission to modify other users' permissions so he should have access to the setup module The issue is that:1. Users who don't have any permissions to do this still have access to setup from within the All Applications module. Yes, they can't view details of other users permissions but why should they even get there at all? They are also able to view things like lists of roles etc. There is no need for this. They should not see Setup in the list of modules (within All Applications) unless they have a role that permits them to set user permissions 2. We should still have a choice of hiding the All Applications module. Afterall, the fact that I have given a user permission for creating Purchase Order does not stop me from being able to hide the Buying module. Also, if I give a user the role of Sales Manager, it doesn't stop me from being able to hide the Selling Module. Why can't you just give me the right as an administrator to determine whether or not I want the All Applications module to be visible? ‎Thanks                                                                                                                                                                                                                                                                           Kind regards, Olawale Olowu wale@xavierltd.com Tel: 08075390014                                                                                                                                                                                                                                         From: Umair SayyedSent: Thursday, February 12, 2015 1:30 PMTo: frappe/erpnextReply To: frappe/erpnextCc: Olawale1Subject: Re: [erpnext] All Applications Module (#2321)Olawale,

Let's assume an HR manager has permission to import Employee, and he can
also do User Permission Setting for other Employee.

In this case, even as HR Manager, who is not a System Manager get's
permission to Setup module. But this access will be restricted to Data
Import and User Permissions only. That user will not be able to access
other functions in Setup module.

Just tried replicating this locating, and found that Setup Icon is still
not visible on the home page. But that user can access Import and
Permission function via options available in the list view page of
documents.

On Thu, Feb 12, 2015 at 3:59 PM, Olawale1 <notifications@github.com> wrote:

> Hi guys, any update on this please? Its actually a serious issue for some
> of us! What is the reason why the All Applications module MUST be visible
> to all users? Please help resolve this. At least give us the choice of
> hiding it just like all other modules!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/frappe/erpnext/issues/2321#issuecomment-74049034>.
>



-- 
Thanks and Regards,
Umair Sayyed
www.erpnext.com


—Reply to this email directly or view it on GitHub.

**Comment by anandpdoshi** [comment]
Hi Wale. All application listing doesn't show modules that are hidden from setup / show hide modules  

Also in v5, the listing in all applications is not clickable. This should fix your concerns.

**Comment by Olawale1** [comment]
‎Hi Anand, This is good news. Yes, it does address my concerns Many thanks                                                                                                                                                                                                                                                                           Kind regards, Olawale Olowu wale@xavierltd.com Tel: 08075390014                                                                                                                                                                                                                                         From: Anand DoshiSent: Thursday, February 12, 2015 3:45 PMTo: frappe/erpnextReply To: frappe/erpnextCc: Olawale1Subject: Re: [erpnext] All Applications Module (#2321)Hi Wale. All application listing doesn't show modules that are hidden from setup / show hide modules  

Also in v5, the listing in all applications is not clickable. This should fix your concerns. 

Sent from my phone

> On 12-Feb-2015, at 20:07, Olawale1 <notifications@github.com> wrote:
> 
> Hi Umair, Thanks for your response. The scenario you have given is a good one. The HR manager in that case is given permission to modify other users' permissions so he should have access to the setup module The issue is that:1. Users who don't have any permissions to do this still have access to setup from within the All Applications module. Yes, they can't view details of other users permissions but why should they even get there at all? They are also able to view things like lists of roles etc. There is no need for this. They should not see Setup in the list of modules (within All Applications) unless they have a role that permits them to set user permissions 2. We should still have a choice of hiding the All Applications module. Afterall, the fact that I have given a user permission for creating Purchase Order does not stop me from being able to hide the Buying module. Also, if I give a user the role of Sales Manager, it doesn't stop me from being able to hide the Selling Module. Why can't you just give me the right as an administrator to determine whether or not I want the All Applications module to be visible? ‎Thanks  Kind regards, Olawale Olowu wale@xavierltd.com Tel: 08075390014 From: Umair SayyedSent: Thursday, February 12, 2015 1:30 PMTo: frappe/erpnextReply To: frappe/erpnextCc: Olawale1Subject: Re: [erpnext] All Applications Module (#2321)Olawale,
> 
> Let's assume an HR manager has permission to import Employee, and he can
> also do User Permission Setting for other Employee.
> 
> In this case, even as HR Manager, who is not a System Manager get's
> permission to Setup module. But this access will be restricted to Data
> Import and User Permissions only. That user will not be able to access
> other functions in Setup module.
> 
> Just tried replicating this locating, and found that Setup Icon is still
> not visible on the home page. But that user can access Import and
> Permission function via options available in the list view page of
> documents.
> 
> On Thu, Feb 12, 2015 at 3:59 PM, Olawale1 <notifications@github.com> wrote:
> 
> > Hi guys, any update on this please? Its actually a serious issue for some
> > of us! What is the reason why the All Applications module MUST be visible
> > to all users? Please help resolve this. At least give us the choice of
> > hiding it just like all other modules!
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/frappe/erpnext/issues/2321#issuecomment-74049034>.
> >
> 
> 
> 
> -- 
> Thanks and Regards,
> Umair Sayyed
> www.erpnext.com
> 
> 
> —Reply to this email directly or view it on GitHub.
> —
> Reply to this email directly or view it on GitHub.
> 


—Reply to this email directly or view it on GitHub.
