### ISSUE TITLE
Latin Characters Encoding is not working properly

### ISSUE THREAD

**Issue by franciscobuendiao** [frappe/erpnext#23222]
## Description of the issue
Latin Characters Encoding is not working properly
## Context information (for bug reports)

**Output of `bench version`**
```
ERPNext: v12.11.2 (version-12)
Frappe Framework: v12.9.1 (version-12)
```

### Observed result
![Captura de Pantalla 2020-08-31 a la(s) 8 50 43](https://user-images.githubusercontent.com/25084259/91728289-8218a200-eb68-11ea-8266-09560db7292b.png)
![Captura de Pantalla 2020-08-31 a la(s) 8 52 39](https://user-images.githubusercontent.com/25084259/91728292-82b13880-eb68-11ea-969b-e802b674e676.png)
![Captura de Pantalla 2020-08-31 a la(s) 8 55 30](https://user-images.githubusercontent.com/25084259/91728295-8349cf00-eb68-11ea-9abd-0101af52700b.png)

**Comment by ghost** [comment]
I have the same error. UTF-8 characters works well in the body, but not in the subject and in the sender name.
<img width="833" alt="image" src="https://user-images.githubusercontent.com/24222588/95687976-19145780-0c07-11eb-85a3-b86460f6af77.png">
