### ISSUE TITLE
S3 backup settings - no region 'af-south-1'

### ISSUE THREAD

**Issue by StephanusVictor** [frappe/erpnext#23234]
Using frappe_docker with:
ERPNext: v13.0.0-beta.4
Frappe Framework: v13.0.0-beta.4

Within the S3 backup settings form, Region listbox, there is no option for "af-south-1" (Africa (Cape Town)) .  This is a new region, only available from April '20.
Can you maybe allow manual entry, not limited to the list?  
Is the Region really required as the information is already in the "Endpoint URL"?

I just selected a random region and do receive email notifications that the backup was successfully uploaded, but no files are added to my S3 bucket.

**Comment by barry86m** [comment]
This is an issue in frappe rather than erpnext. I've created PRs to add af-south-1 to the list in 12-hotfix and 13-beta branches.

Someone else added it to the frappe develop branch back in July, but it didn't seem to make its way through to the other branches just yet.

**Comment by StephanusVictor** [comment]
Thanks

**Comment by barry86m** [comment]
Can you close this issue, since it's not a problem with erpnext?
