### ISSUE TITLE
Difference in mandatory fields while creating new Item via Dask and Importing Items via Data import tools

### ISSUE THREAD

**Issue by tejasmarvania** [frappe/erpnext#23253]
## Description of the issue
While importing Items using Data import tool, few field are mandatory fields. But if we create Item from Desk, these fields are not mandatory and we can create new Item without filling the values to these fields.

## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 12.11.2
frappe 12.9.1
```

## Steps to reproduce the issue

1. Open Data Import tool and Select Document Type as Item
2. Select "Insert New Records" as import type.
3. Select excel or csv file filled with values.
4. Start Import

### Observed result

Getting following message while importing data.

    Attribute (Attributes) is a mandatory field
    Item Tax Template (Taxes) is a mandatory field
    Ref Code (Customer Items) is a mandatory field
    Item Group (Website Item Groups) is a mandatory field
    Request for (Reorder level based on Warehouse), Re-order Level (Reorder level based on Warehouse) are mandatory fields

### Expected result

We should be able to import item data without filling values into those fields.

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by kennethsequeira** [comment]
@tejasmarvania these are table fields which you've left empty. 

You can delete the columns if you're not adding any data to them and re-import.

**Comment by tejasmarvania** [comment]
@kennethsequeira I have deleted those columns and try to import again. Getting the same error.

Attaching the sample Item File which I am using for import.
[Item.xlsx](https://github.com/frappe/erpnext/files/5199398/Item.xlsx)

**Comment by kennethsequeira** [comment]
@tejasmarvania 

![image](https://user-images.githubusercontent.com/33246109/92691265-f40a9b80-f35f-11ea-8bad-e942cd39773b.png)

From column CJ onwards are all table related data. Since they're empty, you can delete these. If you're adding data to the table you need to add the mandatory columns which were being indicated earlier.

I will suggest import only columns for which you have data and delete all others.

**Comment by kingraphaii** [comment]
Hi, I'm stuck on same error, was this issue every addressed?
