### ISSUE TITLE
Intermediate Leave ledger entries do not take holidays list into account when carry forwarded leave allocation expires between leave application to_date

### ISSUE THREAD

**Issue by koszikot** [frappe/erpnext#23274]
Hello everyone, 

this will be strictly technical report, hopefully you do not mind it.

In hr/doctype/leave_application/leave_application.py there is a method create_ledger_entry_for_intermediate_allocation_expiry which has a bug, just like title says.

**Example:**
I have carry forwarded Leaves that expire on 31-12-2018
I create Leave application from 24-31 December 2018

**What happens:**
Instead of 4 days (25,26 are holdiays in Holiday List) in leave ledger I have entry with 8 days with results in incorrect leave balance visible on Employee Leave Balance Report. Which later results in incorrect number of carry forwarded days for new allocations.

**Reason**:
create_ledger_entry_for_intermediate_allocation_expiry method just tries splits holidays into 2 ledger entries and counts leaves ignoring holiday list:
leaves=(date_diff(expiry_date, self.from_date) + 1) * -1, - this is for the first ledger (does not take into account weekends and other holidays provided in Holidays List)
leaves=date_diff(self.to_date, expiry_date) * -1  - second part of ledger, problem same as above

From 24th till 31st there are 8 days, so in first ledger there will be information about 8 days taken instead of 4 even tho Leave Application itself displays correct information about 4 days.

**Comment by ruchamahabal** [comment]
Fixed in: https://github.com/frappe/erpnext/pull/29439
