### ISSUE TITLE
Query Report BUG: First column link field broken when filtering

### ISSUE THREAD

**Issue by sathouel** [frappe/erpnext#23273]
## Description of the issue
In query Report where the first column is a link field, when we filter the report using the standard input box below the column name then the link of the first column does not show anymore

## Context information (for bug reports)

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1. Create Query report as follow
SELECT
    item.item_code as "Item Code:Link/Item:200",
    item.item_name as "Item Name:Data:200"
FROM tabItem as item
2. show report then filter the report by adding some char within the search box "Item Name" then try to click on Item Code Link .. it's broken

### Expected result
The link field should be clickable after filtering

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by deepeshgarg007** [comment]
@sathouel Which report is this, which file did you pick the query from, and what's the exact issue, nothing is well explained. Closing this issue, please reopen a new issue with proper details
