### ISSUE TITLE
Work Order doubles qty from BOM

### ISSUE THREAD

**Issue by ghost** [frappe/erpnext#23281]
Hi,
found a bug in Manufacturing domain. 
When I want to create Work Order from BOM, it doubles qty from BOM.
Eg. For BOM you need 5 pcs of item A, but Work Order will set qty to 10 pcs.
Conversion factor is 1.

https://discuss.erpnext.com/uploads/default/optimized/3X/a/d/ad1f9ce645b5b9f0bb4162a44bb8df680cbdbc54_2_655x500.png

https://discuss.erpnext.com/uploads/default/optimized/3X/a/a/aa48ddf3f27e3a96a55476a23771b14d592c5b15_2_620x500.png

**Comment by sharmanakul** [comment]
issue not observed in the latest version (v13.16)
