### ISSUE TITLE
Missing scan barcode camera in sales invoice 

### ISSUE THREAD

**Issue by Revathi1230** [frappe/erpnext#23299]
In mobile application there is no scan barcode camera in sales invoice.I have attached the screenshot for your reference.
![Scan barcode](https://user-images.githubusercontent.com/70802934/92470783-9279ee00-f1f4-11ea-9f5f-22d1eafc05f5.png)

Frappe & ERPNext Version 13.0.0 Beta.1

**Comment by arrazka** [comment]
This problem still occurs and has not been resolved
currently I'm using erpnext:

ERPNext: v13.10.0 (version-13)

Frappe Framework: v13.10.0 (version-13)

**Comment by shree0990** [comment]
Hi @Revathi1230 you got any solution?

**Comment by ankush** [comment]
This is just confusion, if you click on the field you'll see the button. 

The button is made permanent in v13 and future releases. https://github.com/frappe/frappe/pull/15309
