### ISSUE TITLE
Form for Expense transactions

### ISSUE THREAD

**Issue by ryuliantoro** [frappe/erpnext#23307]
**Is your feature request related to a problem? Please describe.**
For almost every monetary-related transaction there is a form to input the transaction data, which then trigger the creation of JE or GL. But there is none for general expenses.
I know that expenses can be entered directly using JE. But this is confusing for non-accountant or even most people.

**Describe the solution you'd like**
A special form to input general monetary transaction. We can call it **Expense Entry**.
In basic the form should help to input:
- What transaction (fill-in field for description, e.g Today's lunch with client)
- From where the money is (select source account, e.g. Cash or Credit Card)
- To whom it is paid (fill in receiver account, e.g the Restaurant)
- The amount of the expense.

Then the form will automatically assign From and To as Credit or Debit in the JE along with the respective amount.

**Alternative**
Actually the Payment Entry can be used for this but PE is linked to Invoices so the amount can't be changed.
And the Party is listed parties (Supplier, Customer, Member, etc.) so it can't be used for anonymous receiver (a merchant in shop, restaurant for lunch, etc.)

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.
