### ISSUE TITLE
"Delivery Note" status isn't updated

### ISSUE THREAD

**Issue by franciscobuendiao** [frappe/erpnext#23310]
## Description of the issue
If total amount at Delivery Note is $0, its status is not updated as "Completed" if isn't made Sales Invoice from Delivery Note itself.
## Context information (for bug reports)

**Output of `bench version`**
```
ERPNext: v12.11.2 (version-12)
Frappe Framework: v12.9.1 (version-12)
```

## Steps to reproduce the issue

1. Create Sales Order with item $0
2. Create Delivery Note, save and status is set "To bill"
3. From Sales Order create Sales Invoice
4. **Back to Delivery Note, its status remains as "To bill"**
(This behaviour doesn't happen if amount is more than $0)

**But if...**
1. Create Sales Order with item $0
2. Create Delivery Note, save and status is set "To bill"
3. _Create Sales Invoice from Delivery Note_
4. **Back to Delivery Note, its status is updated as "Completed"**

### Observed result
![Grabación de pantalla 2020-09-11 a la(s) 9 47 35](https://user-images.githubusercontent.com/25084259/92941312-d4ce4580-f415-11ea-8c98-abe2b82535a2.gif)

### Expected result
1. Create Sales Order with item $0
2. Create Delivery Note, save and status is set "To bill"
3. From Sales Order create Sales Invoice
4. Back to Delivery Note, its status should be updated as "Completed"

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by ankush** [comment]
This got fixed a while back when the edge case was added for 0 valued orders.
