### ISSUE TITLE
Pricing Rule - Max Qty limit is passed + 1

### ISSUE THREAD

**Issue by franciscobuendiao** [frappe/erpnext#23312]
## Description of the issue
Setting Pricing Rule applies perfectly at Min Qty setup, but **the Max Qty is always passed + 1**.
## Context information (for bug reports)
https://discuss.erpnext.com/t/pricing-rule-max-quantity/65789

**Output of `bench version`**
```
ERPNext: v12.11.2 (version-12)
Frappe Framework: v12.9.1 (version-12)
```

## Steps to reproduce the issue

1. New Pricing Rule - Cumulative
2. Set Min Qty
3. Set Max Qty
4. Create multiple Sales Invoice
5. At Min Qty level, Pricing Rule is applied
6. At Max Qty level, Pricing Rule is not applied, it's always passed + 1

### Observed result
https://discuss.erpnext.com/t/pricing-rule-max-quantity/65789
### Expected result
Pricing Rule be applied on setup Max Qty

**Comment by deepeshgarg007** [comment]
@franciscobuendiao Please recheck this and reopen a new issue if this still persists in the latest version-13 release
