### ISSUE TITLE
Manual reconciliation tool  missing in erpnext version 13

### ISSUE THREAD

**Issue by sammish** [frappe/erpnext#23330]
Manual reconciliation tool  missing in erpnext version 13 

There is no shortcut ***Banking and Payments*** in Accounts

**Comment by kennethsequeira** [comment]
@sammish 
Please check for 'Bank Clearance'. This is probably what you're referring to as the manual reconciliation tool. 

Also, the shortcuts are frequently changing and you can configure your own. All reconciliations as before are being continued. Be it payment, bank, stock or this one.

**Comment by sammish** [comment]
@kennethsequeira ok👍 let me check.
