### ISSUE TITLE
low code quality

### ISSUE THREAD

**Issue by sezanzeb** [frappe/erpnext#23385]
I would kindly ask you to enforce some higher code quality, especially to have docstrings. In the long run it will only be beneficial to the project. I'm sorry if this ends up sounding a bit rude (possibly especially to the person who wrote the code in the example below) and I'm not trying to hate or bash the people who wrote this. I think having an open source ERP system is great and I would love to see this project grow to something that replaces SAP, but I believe this goal can only be achieved if it maintains a high maintainability. And I think this is next to impossible if erpnext doesn't improve in this regard.

For example, here are some issues in apps/erpnext/erpnext/healthcare/utils.py

- There is not a single function with a docstring in that file, the module docstring is also missing.
- In version 12, there was: `if (method == "on_cancel"):`
- Do you use any long line markings? PEP default is 79 characters. There are lines with a length of 137 and 179 chars.
- weird/missing indentations (I personally prefer the latter two):
```python
		frappe.throw(_('The item referenced by {0} - {1} is already invoiced'\
		).format(item.reference_dt, item.reference_dn))
```
```python
		frappe.throw(
			_('The item referenced by {} - {} is already invoiced').format(
				item.reference_dt, item.reference_dn
			)
		)
```
```python
		frappe.throw(_(
			f'The item referenced by {item.reference_dt} - '
			f'{item.reference_dn} is already invoiced'
		))
```

- get_drugs_to_invoice has an indent level of 6. It could be much more shallow using something like:

```python
def get_drugs_to_invoice(encounter):
	encounter = frappe.get_doc('Patient Encounter', encounter)
        if not encounter:
		return

	patient = frappe.get_doc('Patient', encounter.patient)
	if not patient:
		return
```
also see https://refactoring.com/catalog/replaceNestedConditionalWithGuardClauses.html

- get_appointments_to_invoice needs two spaces on top. This sounds completely irrelevant, but it's just as important as keeping your desk at work tidy, other people may want to work with that code too.

And problems like these apply to pretty much every file in this project.

A quick look into merged PRs:

- Merged before the reviewer approved: https://github.com/frappe/erpnext/pull/23376
- No reviewer assigned at all: https://github.com/frappe/erpnext/pull/23367
- Merged with a broken pipeline: https://github.com/frappe/erpnext/pull/23373

Sorry if this is rude, and according to opinions the code is of better quality than Odoos, but that really doesn't mean it's good. Please consider adding a linter to your pipelines, e.g. pylint, or at least require a high pylint rating for new or changed files. The pylint rating of erpnext is "-8.46/10", which is incredibly low. A good start, and probably the most important measure, would be to require docstrings for every new or changed public function from now on, possibly in the numpy docstyle (https://numpydoc.readthedocs.io/en/latest/format.html). You could generate a proper API documentation from them which would be amazing! And if you quickly want to improve the pylint rating, most of them are probably long line errors. By the way, enforcing shorter lines avoids writing complicated had hard to debug one-line statements.

Take gensim as an example, they require a very high code quality for PRs: https://github.com/RaRe-Technologies/gensim/

Writing clean and beautiful code and architecture makes you think twice about your changes, which in turn may even avoid security bugs.

Thanks for considering this for future contributions. This seems to apply to frappe as well.

**Comment by sezanzeb** [comment]
frappe won't accept code quality improvements: https://github.com/frappe/frappe/pull/11797#pullrequestreview-518414970

Arguing that fixing messy code leads to longer debugging times. That's incredible.

I don't think there is any hope. Good luck, I better invest my time in other open source projects.

**Comment by scmmishra** [comment]
> frappe won't accept code quality improvements: [frappe/frappe#11797 (review)](https://github.com/frappe/frappe/pull/11797#pullrequestreview-518414970)

@sezanzeb thank you for then concern towards our humble project. While I respect the spirit in which you raised a PR, I would decline it too, since it's not meaningful enough. 

To be clear, there is no harm in merging your PR, but we don't want to enable a culture of such changes. We already have enough PRs to review, opening floodgates of opinionated styling fixes is not something we need at this time.
