### ISSUE TITLE
Date feature in production Planning Tool

### ISSUE THREAD

**Issue by brentglover** [frappe/erpnext#2338]
Hi

Am looking to have a date feature added to the production planning tool to allow "staggered" production of items.  We would like to plan production for example for 100 units with 30 one month, 30 the next and 40 the next.  enabling us to maximise on a discount.  This date would need to be carried on through to the production order and the purchase order.

Brent

**Comment by umairsy** [comment]
In the Production Planning Tool, you can update Planned Start Date for an Item.
