### ISSUE TITLE
Payroll Entry does not take Branch as an accounting dimension

### ISSUE THREAD

**Issue by pkrulz** [frappe/erpnext#23400]
## Description of the issue
If Branch is selected as an accounting dimension then it is not automatically passed while passing a payroll. Even if Branch is selected in the Payroll form. The expected behavior would be to automatically take the employee branch from the employee master even if that is not defined in payroll.

## Context information (for bug reports)

**Output of `bench version`**
erpnext 12.11.2
frappe 12.9.1

## Steps to reproduce the issue

1. Create a new accounting dimension using "Branch" as the doctype. Make it compulsory for P&L and Balance Sheet
2. Create an employee. Provide it with a department in employee master.
3. Define any salary structure and assign the salary structure to this employee. 
4. Run Payroll for this employee by filling the form. Save the payroll. One may choose to fill something the branch or not.
NOTE the accounting dimension will show only Project and Cost Centre. Branch is NOT added to accounting dimension.
5. Then click "Generate Salary Slips"
6. Then try to submit Salary Slips.

### Observed result
On clicking submit. The error says. "Accounting Dimension Branch is required for 'Balance Sheet' account 'Payroll Payable' (since the employee salary component is chosen to have Payroll Payable as default account - Image attached)
![image](https://user-images.githubusercontent.com/1046970/93867612-eb627f80-fce6-11ea-8e2e-ec12d980b9de.png)

### Expected result
The Payroll form should have either Branch in Accounting Dimension or should use Branch from the Employees section.
The most preferred behavior is to automatically identify the employee branch from Employee Master and pass the entry accordingly

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.
ERPNext installed via easy_install
OS Ubuntu 18.04 LTS

**Comment by deepeshgarg007** [comment]
@pkrulz This should be resolved now, closing this issue
