### ISSUE TITLE
Cannot create or edit website theme

### ISSUE THREAD

**Issue by anandfursule** [frappe/erpnext#23438]
Cannot create or edit the default website theme

**ERPNext**: v13.0.0-beta.4 (HEAD)
**Frappe Framework**: v13.0.0-beta.5 (HEAD)

**On Frappe Cloud**

## Steps to reproduce the issue

1.Website > Website Theme > New / Edit "Standard" Theme
2.Save

### Observed result: 
The page stays as is, it doesn't save. 
Not Saved 

### Expected result
To be saved

**Comment by kennethsequeira** [comment]
You can't edit the standard theme. If you want to make modifications to it, duplicate the same and then edit it as a new one.
