### ISSUE TITLE
Version-13 Docker Installation error

### ISSUE THREAD

**Issue by mujocloud** [frappe/erpnext#23470]
I’m facing a strange issue installing the develop version of erpnext on docker.
I successfully installed develop version on a base system(no virtualization).
However when I try to use the same steps in Docker I get the following error -
AttributeError: module ‘pandas’ has no attribute ‘core’

I used the same exact python version on the base system and Dockerfile - python 3.6.12.

Please advise.

**Comment by barredterra** [comment]
Why not use the existing images from https://github.com/frappe/frappe_docker?

You may ask for ERPNext and Docker related advice on https://discuss.erpnext.com. GitHub is primarily bug reports ;)
