### ISSUE TITLE
Cost Center in Taxes and Charges Template

### ISSUE THREAD

**Issue by barredterra** [frappe/erpnext#23516]
Multi-Company setup ("Company A" and "Company B").

After updating to v12.12.1, the field "Cost Center" in **Sales/Purchase Taxes and Charges** was filled with "Main - Company A". But the respective **Accounts** and **Sales/Purchase Taxes and Charges Templates** were owned by Company B!

Company B is unable to submit any **Sales/Purchase Invoices** because the cost center does not match. We had to fix this manually in all **Sales/Purchase Taxes and Charges Templates**.

**Comment by deepeshgarg007** [comment]
@barredterra a validation for this has now been added to both the Sales and Purchase Taxes and Charges template level, closing this issue since its resolved now.
