### ISSUE TITLE
More detailed Purchase Analytic tool

### ISSUE THREAD

**Issue by dhav-d** [frappe/erpnext#2351]
Can we have a more detailed Purchase Analytic tool with warehouse tracking?

**Comment by umairsy** [comment]
Are you looking for the purchase report based on Warehouse? The Purchase Analytics report is mainly intended for purchase qty and value based on different criterias like Item Code, Item Group, Brand etc. For the Warehousewise stock, you can refer to other stock reports. Closing this issue for now. Feel free to reopen if needed.
