### ISSUE TITLE
Decimal Differences between cost of raw materials and manufactured goods

### ISSUE THREAD

**Issue by sinaisix** [frappe/erpnext#2352]
The system complains of differences between raw material cost and manufactured finished goods due to decimal place rounding as seen in the screenshot below 
![unnamed](https://cloud.githubusercontent.com/assets/3254773/4791337/1bbd9008-5ddc-11e4-90d3-baddf651cca7.jpg)

Also the system seems to ignore any figure manually inputted in the valuation rate column.

**Comment by nabinhait** [comment]
I think it has been fixed in version 5. @sinaisix please let me know
