### ISSUE TITLE
Contract / Frame Orders

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#2353]
A Frame Contract is an order for a certain amount of pieces and a certain amount of time. Let´s say you know you want to buy 10000 PCS in one Year but you don´t know when you will need them, for that purchases you have to do a frame contract. Mainly for two reasons frame contracts are coming in place:
1.       To save the price for the higher amount
2.       To get parts which are difficult to order or have otherwise a long lead time

Frame Orders come in Place for Purchasing Orders as well as for Sales Orders. In SAP it´s mostly done via a contract number which is linked to a Purchase or Sales Order. When you do a PO or SO the amount from the contract is automaticly shrinking…….

**Comment by umairsy** [comment]
Manageable with Pricing Rule.
