### ISSUE TITLE
Agriculture shows up as first card for a Services and Manufacturing company

### ISSUE THREAD

**Issue by barredterra** [frappe/erpnext#23531]
Agriculture shows up as first card for a Services and Manufacturing company. This is very confusing.

![Bildschirmfoto 2020-10-07 um 13 13 46](https://user-images.githubusercontent.com/14891507/95323803-0b756f80-089f-11eb-8390-d8cd6fd749db.png)

![Bildschirmfoto 2020-10-07 um 13 15 36](https://user-images.githubusercontent.com/14891507/95323913-352e9680-089f-11eb-839c-68a89688af86.png)

### Version

Develop Branch (https://github.com/frappe/erpnext/commit/a9c2401a2d91c26d0ef2d3f8d147c8c82ff606ca)

**Comment by ankush** [comment]
fixed in v14. The domain itself is separated out + workspace is fully customizable now.
