### ISSUE TITLE
Unable to correctly translate due to dual use of english word

### ISSUE THREAD

**Issue by 0xpr03** [frappe/erpnext#23556]
## Description of the issue
I'm trying to fix your german translation for "Manual" into "Manuell" instead of "Handbuch". "Handbuch" is the "Manual-Book", not any kind of manual process. Thus selecting "Manual-Book" as completion method for projects is really irritating.

But if I'd just change "Handbuch" to "Manuell" in german, any translation of "Manual" for linking to the real manual (book) would be invalid..

## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 12.12.1
frappe 12.10.2
```

## Steps to reproduce the issue

1. Try to make a PR correcting the translation for manual in german

### Observed result
Not applicable
### Expected result
Not applicable
### Stacktrace / full error message

```
(paste here)
```

## Additional information
Not applicable

**Comment by 0xpr03** [comment]
Place of invalid "Manual-Book" entry
![image](https://user-images.githubusercontent.com/1280209/95453819-d420c480-096b-11eb-9918-4812f43fea08.png)

**Comment by tstrohmeier** [comment]
+1

**Comment by 0xpr03** [comment]
Same problem with "Left" in HR module. It's translated to "Links" which just means "left side" instead of "Ehemalig" for "left this organization".. So leave/left is clashing with "left side". Highly irritating for an employment status.
