### ISSUE TITLE
3 Typos prevent correct assignments in "erpnext/shopping_cart/cart.py"

### ISSUE THREAD

**Issue by nicolas-harraudeau-sonarsource** [frappe/erpnext#23561]
## Description of the issue
Hello,

While analyzing salt on SonarCloud I saw what looks like three bad assignments due to a typos in `erpnext/shopping_cart/cart.py`: [here](https://github.com/frappe/erpnext/blob/c837b5f48cccfdc5dde91d9ea77a67490a69ca1a/erpnext/shopping_cart/cart.py#L211), [here](https://github.com/frappe/erpnext/blob/c837b5f48cccfdc5dde91d9ea77a67490a69ca1a/erpnext/shopping_cart/cart.py#L215), and [here](https://github.com/frappe/erpnext/blob/c837b5f48cccfdc5dde91d9ea77a67490a69ca1a/erpnext/shopping_cart/cart.py#L284). I think the developer intended to write `=` instead of `==`. It is a pretty common mistake in python. You can see the issues in SonarCloud [here](https://sonarcloud.io/project/issues?id=nicolas-harraudeau-sonarsource_erpnext&issues=AXUIPQRLuWN6bNZuHkQj&open=AXUIPQRLuWN6bNZuHkQj), [here](https://sonarcloud.io/project/issues?id=nicolas-harraudeau-sonarsource_erpnext&issues=AXUIPQRLuWN6bNZuHkQl&open=AXUIPQRLuWN6bNZuHkQl) and [here](https://sonarcloud.io/project/issues?id=nicolas-harraudeau-sonarsource_erpnext&issues=AXUIPQRLuWN6bNZuHkQn&open=AXUIPQRLuWN6bNZuHkQn).

<img width="1603" alt="Screenshot 2020-10-08 at 17 52 40" src="https://user-images.githubusercontent.com/40498978/95483213-422ab300-098f-11eb-93f1-703adae269e3.png">
<img width="1586" alt="Screenshot 2020-10-08 at 17 52 44" src="https://user-images.githubusercontent.com/40498978/95483223-448d0d00-098f-11eb-91b6-c7f5c22e8714.png">

<img width="1586" alt="Screenshot 2020-10-08 at 17 52 48" src="https://user-images.githubusercontent.com/40498978/95483229-45be3a00-098f-11eb-8f46-67a6068bd3b2.png">

## Steps to reproduce the issue

This issue was detected by scanning ERPNext with [SonarCloud](https://sonarcloud.io/).
You can run the same analysis in a few clicks. I used [this configuration file](https://github.com/nicolas-harraudeau-sonarsource/erpnext/commit/19cbb1cfb8f9e2b389d47b26839c3edae685ec2f) to separate properly main code from test code.

## Additional information

In case you have any question, suggestion or if you see a False Positive on SonarCloud you can reach out on [SonarSource community forum](https://community.sonarsource.com/).

A few notes in case you want to use SonarCloud:
* SonarCloud can easily import pylint and flake8 issues in case you want to use a rule SonarCloud does not already provide. Note however that if you select a rule already covered by SonarCloud you might see different issues than what Pylint/Flake8 report. We design our code analyzers to avoid False Positives as much as possible and to detect complex bugs.
* SonarCloud can analyze javascript, HTML and CSS. You can also import reports from ESLint.
* SonarCloud is free for open-source projects.

For full disclosure, I work at SonarSource, the company behind [SonarCloud](https://sonarcloud.io/), [SonarQube](https://www.sonarqube.org/) and [SonarLint](https://www.sonarlint.org/).

**Comment by ankush** [comment]
closed in https://github.com/frappe/erpnext/pull/25372
