### ISSUE TITLE
Invalid Item Tax Template

### ISSUE THREAD

**Issue by nakul80** [frappe/erpnext#23578]
## Description of the issue

Migrated from self host to frappe cloud and getting invalid item tax template error. Tax template exists and is fine.

## Context information (for bug reports)

![image](https://user-images.githubusercontent.com/64956588/95651853-9efea880-0b0a-11eb-9b58-dc97a1ef8bf4.png)

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1.
2.
3.

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by sharmanakul** [comment]
can you confirm if it still exists?
