### ISSUE TITLE
Not able to add pos profile in version-13-beta

### ISSUE THREAD

**Issue by esafwan** [frappe/erpnext#23576]
## Description of the issue
Unable to add the POS profile. Getting below error.

> #### Missing Fields
> Mandatory fields required in POS Profile
> * Warehouse

However, there is not a warehouse field in the form of creating a POS profile. 

## Context information (for bug reports)
**Version used:** version-13-beta
**Method of Installation:** https://github.com/frappe/frappe_docker/blob/develop/docs/single-bench.md

## Steps to reproduce the issue

1. Go POS profile list.
2. Create a new pos profile. 

### Observed result

<img width="1264" alt="Screenshot 2020-10-10 at 12 49 09 PM" src="https://user-images.githubusercontent.com/246454/95648922-6f46a500-0af8-11eb-8eac-331566649512.png">

**Comment by kevinpthorne** [comment]
This was fixed on mine with the latest beta 6
