### ISSUE TITLE
Want to provide erpnext hosted solution.

### ISSUE THREAD

**Issue by uttamsharma** [frappe/erpnext#23581]
Hello, I'm planning to provide hosted solution for erpnext. I'll do these things:
1. I'll fork this repository and modify the logo and name. (Your trademark policies) credits will remain as gpl license. 
2. Provide hosted solution. 
3. Using paid promotion channels for hosted solution (without using the your trademark logos and names. ) 
4. Providing front line support for this tool. 

I'm really thankful for this great product. You done a great work. 
I want to ask is it fine to do these tasks? Is they are according to your usage policy ? 

Thank you 😊

**Comment by test2a** [comment]
i am not an expert in erpnext particularly but erpnext.org shows https://creativecommons.org/licenses/by-sa/3.0/
which means you are free to adapt the software and modify it to your liking but you cannot restrict anymore than what the erpnext has restricted. ie, you cannot put more restrictions to further use. What it means is you have to give your code just like erpnext team has done in the first place.
maybe anyone from the team can shed more light on this

**Comment by kennethsequeira** [comment]
@uttamsharma better not go for whitelabeling. People will find out easily: https://discuss.erpnext.com/t/why-you-should-not-whitelabel-erpnext/20511

The source code is GPLv3. As per the license you must also make your source code available with the same license.

**Comment by uttamsharma** [comment]
@kennethsequeira thanks for your response. It's for hiding erpnext (footer credit will remain) I just want to replace the logos and a different name. 
 Footer credit like powered by erpnext will be placed on almost every page. I'll fork it here at GitHub so providing source code is not a issue. I just want to provide a hosted erpnext with a different name. 
Is it allowed by your (erpnext) terms and conditions? 

Thanks 😊
