### ISSUE TITLE
Validity dates for Currency Exchange rates

### ISSUE THREAD

**Issue by hertera** [frappe/erpnext#2359]
Hi,

We should be able to define validity dates for currency exchange rates. Usually the system should allow daily rates.

Other than this we should be able to define exchange rate types like selling,buying,central bank etc.

**Comment by devdesco-ceo** [comment]
+1
Yes, please... we need to define active FROM - TO dates for every historical currency rate entered in the system that the accounting system might correctly pickup the exchange rate actual for the given date of particular transaction, etc.
I would live without automatic currency updates, but the above concern is very serious.

**Comment by anandpdoshi** [comment]
How about we implement: https://openexchangerates.org. They have a forever free plan too.

**Comment by hifiberry** [comment]
Any news on this? ERPNext looks like a good ERP for small companies. However we deal a lot with different currencies and not having daily exchange rates is a killer for us. Is this planned to change soon?

**Comment by rmehta** [comment]
@hifiberry this is already fixed. What version are you using?

**Comment by rmehta** [comment]
Sponsor! https://erpnext.com/pricing/paid-feature-development

**Comment by umairsy** [comment]
If new Currency Exchange Record is created for a given date, then it will be given priority over other Exchange Rate for the said currency. Please test and confirm if this fulfils your usecase.
