### ISSUE TITLE
Can't reconcile both sides of a bank transfer

### ISSUE THREAD

**Issue by gwhitney** [frappe/erpnext#23660]
## Description of the issue
I create a Bank Entry journal entry to record a transfer from one Bank Account (owned by the company) to another Bank Account (also owned by the company). Say it is from "Savings" to "Checking". Then I get the "Checking" statement (say) and upload it into ERPNext, and do a Bank Reconciliation. When I get to the Bank Transaction for receiving the transfer, I can click on it and the correct Bank Entry transaction comes up and I click Reconcile and voila, the Bank Transaction goes to status Reconciled and all is well and when I am done, the Checking account reconciles perfectly (let's suppose). But now when I get the "Savings" statement and upload it into ERPNext and do the Bank Reconciliation, when I come to the Bank Transaction for sending the transfer, I click on it and there is nothing for it to match. So I cannot complete the Reconciliation. So the Bank Transaction just sits there, confusing the issue for future Bank Reconciliations for the "Savings" account (and potentially offering an erroneous reconciliation if I do another transfer for the same amount and this time the Savings statement comes in first).

ERPNext needs to allow both sides, the Savings account and the Checking account, to reconcile.

## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 13.0.0-dev
frappe 13.0.0-dev
```

## Additional information

OS version / distribution, `ERPNext` install method, etc:

Linux Debian 10 (buster); installed by an on-line guide specifically for Debian

## Analysis

Clearly the underlying issue is as follows: ERPNext marks whether an entry has been reconciled by setting a Clearance Date field on the overall entry. But of course for Journal Entry documents in particular, Clearance is actually a property of a single Journal Entry Account record _within_ a Journal Entry rather than a property of the Journal Entry as a whole. Specifically, it's clear that in the case of a transfer from one institution to another, the Clearance Date of the outgoing funds from one does not necessarily have to be the same as the Clearance Date of the incoming funds in the other, depending on the mode of transfer.

So moving the Clearance Date field from being a field in the Journal Entry to being a field in the Journal Entry Account records would reflect reality better, and would clearly solve the problem: when the Checking account is reconciled, it would only reconcile with one of the two Journal Entry Account lines in the Bank Entry. And so when the Savings statement comes in, the transaction there can reconcile with the other line in that same Bank Entry.

I am willing to make an effort to relocate Clearance Date field along these lines, but it would be a fair amount of work and would not want to devote that time without a sense that this is an approach the developers of ERPNext would support, so that the resulting changes, which will be potentially larger than a typical Pull Request from an outside contributor, would stand a reasonable chance of being accepted. Please can you provide some clarity on the views of the ERPNext maintainers regarding the approach of changing the reconciliation system so that Bank Transactions are reconciled against individual lines in Journal Entry documents rather than against an entire Journal Entry wholesale?

Thank you very much for your thoughts and consideration on this. It's currently very problematic that you can't smoothly reconcile both sides of a bank transfer, which is why I filed this as a bug (rather than say as a feature request).

**Comment by deepeshgarg007** [comment]
@gwhitney This can easily be solved by splitting the entry into two entries. Use an intermediary account and make two entries and you'll be able to reconcile them normally.

**Comment by gwhitney** [comment]
@deepeshgarg007 That is an unacceptable workaround to this deep basic issue in ERPnext's handling of Journal Entry items and reconciliation. The basic "unit" of reconciliation is a line in a journal entry (a Journal Entry Account record), not a journal entry, as this example shows. Having to create a fictional intermediary account for every bank account to handle transfers needlessly complicates our books and creates significant extra work, not to mention it's difficult to communicate to our auditors what all those extra accounts are and makes understanding our books much more difficult, leading to extra expense in the audit. It renders ERPNext unusable for our institution, and I can only presume it is a point of pain for any other users of ERPNext that have multiple bank accounts. A couple of years ago I did in fact put in all of the work to correct the situation and submitted a PR to make the Journal Entry Account records the locus of reconciliation, only to have the PR  invalidated by a different refactor of the reconciliation UI of unclear purpose, and of course I presume that by now that old PR would be next to impossible to rebase.

Nevertheless, if you think about it, any Journal Entry may consist of multiple lines that deal with different outside entities, and those different outside entities will provide distinct confirmations/reports on the occurrence of the events modeled by those lines, so reconciliation has to be against individual lines. ERPNext is a valuable open-source offering in the accounting world, so my offer stands to help with the effort to correct the subtle but very important modeling error in ERPNext as it stands, that reconciliation is considered to be against entire JournalEntries. Please please reopen this issue and commit to correcting it. It is a very significant obstacle to wider adoption of ERPNext. Thank you for your consideration.

**Comment by gwhitney** [comment]
Please also consider the actual bookkeeping work that your proposal to create a fictional intermediary account creates for users of ERPNext: Now rather than simply importing transactions and using them as-is, they must all be reviewed manually by a bookkeeper to find the ones that have to be manually split into two journal entries, and for those that do, the correct intermediary account has to be determined, and the automatically generated entry has to be reversed and the two "split" entries have to be entered. It's really completely impractical in practice. Again, thank you for your consideration and I remain willing to help, as the PR referenced on the right aptly demonstrates. It represented a significant investment of time in ERPNext.

**Comment by chaoxu** [comment]
I must say this is crucial for US customers.

In the US, bank transactions takes time (sadly, unlike most places in the world). A journal entry should have a posting date for each individual account. Split into two journal entries is a very bad hack. I have to train my accountants to use this unintuitive method, and like @gwhitney said, the hack workarounds would simply confuses auditors. 

So this makes bank reconciliation entirely unusable unless I'm willing to allow one of the two bank accounts to never be reconciled.

**Comment by gwhitney** [comment]
Thanks @chaoxu for your supporting information. My position remains that if ERPNext becomes open to correcting this crucial design flaw, I am willing to put coding time into developing a PR or PRs to address it.
