### ISSUE TITLE
Customer doctype field is contradictive: Allow Sales Invoice Creation Without Sales Order

### ISSUE THREAD

**Issue by ceefour** [frappe/erpnext#23679]
## Description of the issue

Customer doctype field label vs name is contradictive: Allow Sales Invoice Creation Without Sales Order

## Context information (for bug reports)

**Output of `bench version`**
```
frappe 13.beta.5
erpnext 13.beta.4
```

## Steps to reproduce the issue

1. Create a new Customer

### Observed result

In **Customer** doctype, the following fields are contradictive / confusing:

* `so_required`: Allow Sales Invoice Creation Without Sales Order
* `dn_required`: Allow Sales Invoice Creation Without Delivery Note

### Expected result

Since changing the field name will break compatibility, I propose to change the labels instead:

* `so_required`: Sales Order is Required to Create Sales Invoice
* `dn_required`: Delivery Note is Required to Create Sales Invoice

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

ERPNext bench using easy install script on Ubuntu 20.04.1 on m6g.medium.

## Notes

* I tried setting `so_required` both checked and unchecked, and was able to create Sales Invoice either way. So maybe the check is not yet enforced ?

**Comment by deepeshgarg007** [comment]
@ceefour Don't think this affects the user in any way and should be classified as a bug
