### ISSUE TITLE
Ability to choose defaults for sending Emails

### ISSUE THREAD

**Issue by adityaduggal** [frappe/erpnext#2367]
Currently when we send the emails there is no way to define the defaults in email sending like:
- Whether the email copy should be sent to Me or not should it be checked by default or not.
- Where to cc the copy of every email

**Comment by adityaduggal** [comment]
Email sending window's customisation should be something similar to Customize form view instead of creating a custom code for changing the default set for email window.

**Comment by jevonearth** [comment]
This has been a long standing gripe for my user. Would love to see this implemented.

I have made a screenshot to help illustrate what I need.

![send-me-a-copy](https://user-images.githubusercontent.com/1114943/28990990-9fb09a44-7937-11e7-9a3c-f8e446211e5b.png)

**Comment by rmehta** [comment]
Should it just save the settings, when it is checked for the user?

**Comment by jevonearth** [comment]
Making the checkbox "sticky" would work for me.

But it may annoy other users who want or have come to expect "Send me a copy" to be unchecked by default. I think it's a judgment call you need to make @rmehta

**Comment by jevonearth** [comment]
Awesome, thank you!
