### ISSUE TITLE
JobCard not showing ganttchart

### ISSUE THREAD

**Issue by amira133** [frappe/erpnext#23684]
## Description of the issue
can not see Gantt chart in Job Card section

## Context information (for bug reports)

**Output of `bench version`**
```
bench  Version: 5.2.1

ERPNext: v12.12.1 (version-12)

Frappe Framework: v12.10.2 (version-12)
```

## Steps to reproduce the issue

1.navigate manufacturing
2.navigate Job Card
3.select Gantt

### Observed result

![1111](https://user-images.githubusercontent.com/27830573/96437907-3488ef00-1213-11eb-8203-83500ca74313.PNG)

## Additional information

Ubuntu 20.04

**Comment by amira133** [comment]
?

**Comment by amira133** [comment]
??

**Comment by sharmanakul** [comment]
hi @amira133 , i checked it on the latest version (v13.16), looks like it has been resolved. I'd recommend to upgrade.

Please confirm at your end.

I'm closing it for now, feel free to reopen if it persists.
