### ISSUE TITLE
Issues with the current Maintenance Schedule

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#23682]
Hi ,

There are some rather important issues that need to be fixed in the current implementation of the Maintenance Schedule doc

1. You can only select one 'Sales Person' for each item to be maintained. This should be a team!
2. There is no link/dashboard on the submitted Maintenance Schedule that shows (and links to) the automatically created Events
3. The created Events are completely invisible to the Creator of the Maintenance Schedule and even the Administrator and System Managers. Only the 'Sales Person' can view the created Events
4. The created Events don't even have the 'Sales Person' included as a participant! Instead, it references the Maintenance Schedule document as a participant (which is quite odd)
5. The created Events can only send a reminder on the morning of the due date! That's totally useless in most cases. It should be configurable to be sent days earlier for adequate preparation to be made for site visit
6. The scheduled dates in the Maintenance schedule cannot be adjusted. There should at least be a field for the user to enter the actual date of carrying out the maintenance
7. The Status of the Maintenance Schedule doesn't indicate when a scheduled maintenance is Overdue! There should also be a way for the user to mark the maintenance as 'Completed' or 'Cancelled'. If they select 'Completed', they must also enter an 'Actual Maintenance Date'. Once a scheduled date is past and the actual maintenance date has not been entered, Status should be 'Overdue'. If the actual maintenance date has been entered either before or after the scheduled date, Status should be 'Completed'. If the maintenance is marked as 'Cancelled', Status should show same
8. The term 'Sales Person' doesn't seem the most appropriate for Maintenance Jobs. It should be something more generic

Hope these can be urgently fixed in order to significantly improve the current user experience with the Maintenance Schedule feature

Thanks

**Comment by rasos** [comment]
This issue should be re-opened, all very good points. It is not clear who can see the maintenance events, even me listed as a sales person  can't see it in the calendar. 

It should be also possible to allow maintenance of items under warranty see https://discuss.erpnext.com/t/maintenance-schedule-not-allowed-for-items-under-warranty/64071
