### ISSUE TITLE
Subscription Management

### ISSUE THREAD

**Issue by ryuliantoro** [frappe/erpnext#23696]
**Is your feature request related to a problem? Please describe.**
Not really a problem but a more intuitive and efficient user interface.

**Describe the solution you'd like**
~~1. Move Subscription Management from Accounting to Selling because it is more to manage selling by subscription, not about recurrent invoicing (which is handled by the system)~~ --> v13 includes subscription of purchase.
2. Make Subscription Settings > Prorate to be per Subscription Plan (instead of global as of now).

**Comment by ceefour** [comment]
I just realized that Subscription is not only about Selling, but also Purchasing, as Party Type can be Supplier, or even custom (Vendor? Freelancer? etc.).

However, point no. 2 about Prorate in Subscription Plan, I think it's more intuitive.

**Comment by ryuliantoro** [comment]
Oh ok.. I still use v12 so I don't see the Purchase side.

![Screen Shot 2020-10-21 at 17 24 31](https://user-images.githubusercontent.com/13296444/96707721-70ae8200-13c2-11eb-82f9-72755ca21dfc.png)

**Comment by barredterra** [comment]
> Make Subscription Settings > Prorate to be per Subscription Plan (instead of global as of now).

@ryuliantoro can you elaborate on this? What is the current state and what would you like to see changed? I noticed that prorate is behaving unexpectedly, but i don't know the details.

**Comment by ryuliantoro** [comment]
The Prorate currently is globally applied to all Subscription Plan.
Applying Prorate to each Subscription Plan enable user to make some Subscrition Plan with prorate and not for others.
