### ISSUE TITLE
Letterhead linked to Company

### ISSUE THREAD

**Issue by ftorreti** [frappe/erpnext#2371]
In the case of multiple companies, it would be useful to have the ability to link a specific letterhead to a company so that when a transaction is made against that company, the correct letterheads appear in the drop down menu with a standard template being selected.

At the moment the only way to address this is to have a custom script to update letter_head field based on change in value in the company field and copy this script across all doc types.

**Comment by troin** [comment]
it would also be very helpful to set name series as per company selected
