### ISSUE TITLE
Multiple issues in Point of Sale(POS) related to stock.

### ISSUE THREAD

**Issue by esafwan** [frappe/erpnext#23710]
## Description of the issue
Stock in Point of Sale(POS) is not working as expected. Two probably related issues:
1. Items can be sold even after the stock is over. The error is only thrown when the closing entry for a POS is done at e.o.d. 
2. When a stock reaches zero. It automatically updates the stock in POS to a positive value, even though no stock was added to the actual warehouse. 
`

## Steps to reproduce the issue

1. Add a product/item with 5 stock. 
2. Open pos & create an order with 5 qty for the particular product and complete the purchase/order. 
3. Now, if you go to the item via item list, and check the stock is still 5. 
4. Now in POS create a new order & again add the same product to the order and complete the purchase. The purchase still 
goes through even though you have already sold all 5 products. 
5. If you check keep the mouse above the item in POS before checking out the second order, it shows qty:5. It looks as POS is reading the stock again from the item entry, where the stock is not updated after the previous purchase.

### Observed result

- POS is not updating stocks properly. 

### Expected result

- POS need to maintain real stock status.
- POS should not auto increase product stock when it reaches zero. 

## Additional information
**ERPNext**: v13.x.x-develop () (develop)
**Frappe Framework**: v13.x.x-develop () (develop)
**OS**: Ubuntu 20.04.1 LTS
**Installation**:  VS Code + Docker (https://github.com/frappe/frappe_docker/tree/develop/development)

**Comment by ssiyad** [comment]
Cannot reproduce
