### ISSUE TITLE
Can't create opportunity directly from email.

### ISSUE THREAD

**Issue by rtdany10** [frappe/erpnext#23724]
![image](https://user-images.githubusercontent.com/52111700/97140746-4f171700-1783-11eb-85bc-00254c34cbce.png)

Throws this error on creating opportunity from email. Tested on both v12 and v13. Same error.

**Comment by deepeshgarg007** [comment]
@rtdany10 Can you please mention more info or steps to replicate this issue and reopen, or may even raise a PR
