### ISSUE TITLE
buyback feature for serial and batch nos.

### ISSUE THREAD

**Issue by dufani1** [frappe/erpnext#23723]
Hello,
Our case as the following:
We sell item A with serial no. B to customer X, then after period of time, we purchase item A with serial no. B from customer X (customer here added as supplier). So system not accept this process.
My question : Why I can not buy this serial no. B again even after make delivery note?
ERPNext not allow receiving the material with the same serial number even we sold this material !!!!!!!

**Comment by aakvatech** [comment]
We have similar situation as well to buy back same item.
