### ISSUE TITLE
The finished Product is not a completly new Item

### ISSUE THREAD

**Issue by melkhishin** [frappe/erpnext#2372]
Dears, I need to find a solution for this issue. In tire retreading we use old tires with unique serial numbers as one of the row materials , the finished product is the same tire with same serial number but after curing process using other row materials.
we tried to use the manufacturing module and found the following issues:

1- finished product can not be one of the row materials.

The only solution for now is to neglect manufacturing module and use stock entries in two steps:
1- material issue all row materials except the tires from work in progress store.
2- material transfer the tires (have serial numbers) from work in progress store to finished goods store.

is there any other solution to use the manufacturing module to achieve our target? Manufacturing module will help us to track the production orders and have good manufacturing reports.

**Comment by neckos** [comment]
Hi
Was this implemented in ERPNext?
