### ISSUE TITLE
Version-13 :Scroll Down Bar Not shown and scroll not working in reports

### ISSUE THREAD

**Issue by sammish** [frappe/erpnext#23738]
Scroll down bar not being shown and also scroll not working in all reports.

![Untitled Project](https://user-images.githubusercontent.com/12432802/97294971-c7eba100-185f-11eb-894d-5bfcf798c39f.gif)

![image](https://user-images.githubusercontent.com/12432802/97295012-d5a12680-185f-11eb-8a2d-a6ab69eb6ed5.png)
I have noticed when we add a column the scroll bar shows up and scroll starts to work
![image](https://user-images.githubusercontent.com/12432802/97295042-e05bbb80-185f-11eb-901c-533fd176bd29.png)

**Comment by sammish** [comment]
@nabinhait @adityahase @deepeshgarg007 Please consider this issue next release

**Comment by bobzz-zone** [comment]
this is reallly important... its hard to scroll without it..please do fix this..
