### ISSUE TITLE
Customer numbers are not created when creating a new customer

### ISSUE THREAD

**Issue by markusrock** [frappe/erpnext#23756]
## Description of the issue

When creating a new customer a customer number should be created automatically, if I understand the system correctly. Unfortunately this does not happen. Instead, either the field remains empty or the default variable is entered (e.g. "C.#####")

I also don't see any field were I could manually add the customer number afterwards

## Context information (for bug reports)

ERPNext: v13.0.0-beta.4 (HEAD)
Frappe Framework: v13.0.0-beta.5 (HEAD)

## Steps to reproduce the issue

1. Create a new customer
2.
3.

### Observed result

No Customer Number visible

I noticed that when I change the synthax of the customer number it creates a empty line in the syntax field. That might be the problem

### Expected result

Automatic Creation of Customer number

### Stacktrace / full error message
No Error

## Additional information

Hosting on Frappe Cloud

This is my first ticket on GitHub I opened, hope I did everything right :) 
![Bildschirmfoto 2020-10-29 um 07 55 17](https://user-images.githubusercontent.com/73632724/97535617-cdf29680-19b3-11eb-81f6-b0c7e4d916b7.png)

**Comment by kennethsequeira** [comment]
@markusrock 

Check Selling settings:

https://docs.erpnext.com/docs/user/manual/en/selling/selling-settings#11-customer-naming-by

PS: Such minor queries better be posted on the [forum](https://discuss.erpnext.com).
