### ISSUE TITLE
Education: Make LMS navigation easier

### ISSUE THREAD

**Issue by mujeerhashmi** [frappe/erpnext#23750]
@ruchamahabal 

**Is your feature request related to a problem? Please describe.**
Navigating back and forth in LMS is frustrating and does not give the structure of the program into courses, topics, and content in a single glimpse.

**Describe the solution you'd like**
A sidebar containing a list of programs that can be expanded to list courses, and each course can be expanded to list topics and in turn, each topic expands to list content. Instead of current hierarchical navigation, Each of the list items can be clicked to navigate to it directly.

**Comment by fderyckel** [comment]
I would also  add in  the sidebar, once you are in the course page, you can see the course progress.
