### ISSUE TITLE
Homepage ERP next

### ISSUE THREAD

**Issue by sabiyamalbari** [frappe/erpnext#23775]
Hero image is not uploading.
Getting 404 error

**Comment by markelayan** [comment]
hello @sabiyamalbari 
please mention all details of the bug such as ERPNext's and frappe versions as well as how to reproduce the error.
If the issue has been resolved, please close your issue in here.
for a faster response time or immediate help from the community, please post your issue on https://discuss.erpnext.com/

**Comment by barredterra** [comment]
Closing this for now. Please open a new issue with a detailed description of the error, stack trace, screenshots, your frappe and erpnext versions, etc.
