### ISSUE TITLE
Birthday notifications are always send

### ISSUE THREAD

**Issue by 0xpr03** [frappe/erpnext#23788]
## Description of the issue
Birthday emails are sent despite being disabled.

## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 12.13.0
frappe 12.11.0
```

## Steps to reproduce the issue

1. Check "do not send birthday notifications"
2. Import Employees entries to HR module with personal + company mail
3. Notifications are still send

### Observed result
Emails are being send.
### Expected result
No emails are being send at all.

OS version / distribution, `ERPNext` install method, etc.
bench install/update method on an current debian.

**Comment by ankush** [comment]
This was fixed 2-3 releases ago.
