### ISSUE TITLE
How can i add new columns 

### ISSUE THREAD

**Issue by almarkae** [frappe/erpnext#23791]
Please post on our forums:
How can I add columns in the invoices table where I add the expiration date, for example, production date, etc.
for questions about using `ERPNext`: https://discuss.erpnext.com

for questions about using the `Frappe Framework`: ~~https://discuss.frappe.io~~ => [stackoverflow](https://stackoverflow.com/questions/tagged/frappe) tagged under `frappe`

for questions about using `bench`, probably the best place to start is the [bench repo](https://github.com/frappe/bench)

For documentation issues, use the [ERPNext Documentation](https://erpnext.com/docs/) or [Frappe Framework Documentation](https://frappe.io/docs/user/en) or the [developer cheetsheet](https://github.com/frappe/frappe/wiki/Developer-Cheatsheet)

> **Posts that are not bug reports or feature requests will not be addressed on this issue tracker.**

**Comment by barredterra** [comment]
As you correctly state in your issue, this question is better suited for the forum. ;)
