### ISSUE TITLE
Please add option for 'Series' in the Opening Invoice Creation Tool

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#23794]
Hi ,

Please add an option for 'Series' in the Opening Invoice Creation Tool. This is especially important in a multi-company setup where each company has different series being used for invoices

Thanks

**Comment by harshit-30** [comment]
@Olawale1 Please follow this request [here](https://github.com/frappe/erpnext/issues/28759).

Closing this, if there is any other requirement please do comment on the above-mentioned issue.
