### ISSUE TITLE
gross profit calculation bug for product bundle

### ISSUE THREAD

**Issue by harsono** [frappe/erpnext#23803]
## Description of the issue
Error calculating the gross profit amount and percentage in the "accounting > profitability: gross profit" report specifically for product bundle.

## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 12.13.0
frappe 12.11.0
```

## Steps to reproduce the issue

1. create product bundle with an item with more than 1 quantity.
For example:
product bundle "BUNDLE1", includes: 2 qty of item "ITEM1"

2. set the selling price to be equal to the selling value of the bundled items.
For example:
"ITEM1" selling price is 1000.
"BUNDLE1" selling price is 2000.

3. create two sales invoices, one sells 2 "ITEM1", and the other sells 1 "BUNDLE1".

4. generate the gross profit report and find that both differ in their gross profit.

## Additional information
OS: ubuntu 18.04 server
installation method: easy install from the installation documentation

**Comment by irfanzck** [comment]
Same issue noticed. Any solutions to this bug?
