### ISSUE TITLE
Some words in POS V13 not translated, even after adding the custom translation.

### ISSUE THREAD

**Issue by AlghryaneeAnees** [frappe/erpnext#23858]
Can't Translation in POS v13.
![Can't Translation in POS v13](https://user-images.githubusercontent.com/26385038/98463430-df158180-21c3-11eb-8982-cadf22506d73.gif)

**Comment by dufani1** [comment]
I am facing the same issue, some words and sentence not translated, even after adding the custom translation.

**Comment by AlghryaneeAnees** [comment]
any update

**Comment by thebachy1** [comment]
Any update?

**Comment by abduelmherig** [comment]
Any update?
