### ISSUE TITLE
[bug] click sales order shortcut from main module page, the breadcrum show retail other than selling

### ISSUE THREAD

**Issue by szufisher** [frappe/erpnext#23874]
## Context information (for bug reports)

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1. from selling module main page
2. click sales order short cut button

### Observed result
![image](https://user-images.githubusercontent.com/12823863/98616730-5bc96c80-2338-11eb-9f3f-e9fdae68b38c.png)

### Expected result
![image](https://user-images.githubusercontent.com/12823863/98616765-700d6980-2338-11eb-8a53-7bb2a27226cf.png)

### Stacktrace / full error message

```
(paste here)
```

## Additional information
frappe.desk.doctype.desk_page.desk_page.py line 32 
change from
return { page[1]: page[0] for page in pages if page[1] }
to
return { page[0]: page[1] for page in pages if page[1] }

OS version / distribution, `ERPNext` install method, etc.

**Comment by markelayan** [comment]
hello @szufisher 
please mention all details of the bug such as ERPNext's and frappe versions as well as how to reproduce the error.
If the issue has been resolved, please close your issue in here.
for a faster response time or immediate help from the community, please post your issue on https://discuss.erpnext.com/
