### ISSUE TITLE
Consolidated Financial Statement shows wrong total on the card

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#23871]
Hi ,

When the "Accumulated Values in Group Company" option is selected, the total values on the card are wrong because it adds the accumulated values to the individual values (which is a duplication). Please see screenshots below:

![Consolidated FS Issue 01](https://user-images.githubusercontent.com/9269337/98587939-2c304b00-22cb-11eb-9074-b375ed714974.png)

![Consolidated FS Issue 03](https://user-images.githubusercontent.com/9269337/98587953-32bec280-22cb-11eb-8031-b0a3d52dcab1.png)

Please help fix this

Thanks

**Comment by deepeshgarg007** [comment]
@Olawale1 This issue should be resolved now, closing this issue
