### ISSUE TITLE
Serial no / batch no Popup is not coming for the serialized and batch items in V12.13.0

### ISSUE THREAD

**Issue by ushashmi** [frappe/erpnext#23876]
After upgrade to new version v12.13.0 the Serial no / batch no Popup is not coming for the serialized and batch items. Appreciate if this can be fixed quickly.

**Comment by barredterra** [comment]
Hi @ushashmi, thanks for reporting. What can we do to reproduce the error?

**Comment by ushashmi** [comment]
Just make one item as serial number or batch no, put some stock and then try to make a sales invoice. Ideally the Serial no / batch no Popup should appear the moment we select that item but its not working. 

Its working perfectly fine at stock entry but for sales invoice and delivery note it is not working

**Comment by ankush** [comment]
can't reproduce on latest v12/v13 versions.
