### ISSUE TITLE
[bug] user login with language other than English filter by No Tags show not result

### ISSUE THREAD

**Issue by szufisher** [frappe/erpnext#23875]
## Context information (for bug reports)

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1. login system with user assigned to non English language
2. goes any doctype list view with existing docs which has no tags set yet
3. click the left side bar tags button, choose the No Tags option

### Observed result
no result list shown
### Expected result
result list with docs Tags not assigned
### Stacktrace / full error message

```
(paste here)
```

## Additional information
frappe.public.js.frappe.list.list_sidebar.js  line 317 add translate function
	if (label == __("No Tags"))

OS version / distribution, `ERPNext` install method, etc.

**Comment by barredterra** [comment]
Hi @szufisher, thanks for reporting. What version of Frappe/ERPNext are you using?
