### ISSUE TITLE
Invalid Method in Data Import

### ISSUE THREAD

**Issue by aymenit2008** [frappe/erpnext#23885]
I get "Invalid Method" in download template in data import after update 
ERPNext: v12.13.0 (version-12)
Frappe Framework: v12.11.0 (version-12)

![image](https://user-images.githubusercontent.com/10696455/98781843-11172580-2408-11eb-9e7e-4f2860c6e8bd.png)

**Comment by alkuhlani** [comment]
Thank you for your issue,
same issue with me.

**Comment by harshit-30** [comment]
Works fine for me, please share the steps or GIF to investigate further
