### ISSUE TITLE
Monthly Attendance Sheet Report for Leaves count not showing 

### ISSUE THREAD

**Issue by yhennie** [frappe/erpnext#23884]
## Description of the issue

 While generating monthly attendance report the leave shows blank or 0 while in total leaves there is amount. 

## Context information (for bug reports)

**Output of `bench version`**
```
Erpnext 13 beta 



```

## Steps to reproduce the issue

1.
2.
3.

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

![Untitled](https://user-images.githubusercontent.com/61680603/98776781-91e71900-242a-11eb-9a3e-5baa737dd3be.png)

**Comment by ruchamahabal** [comment]
Fixed in: 
- v13 - https://github.com/frappe/erpnext/pull/30748 
- v14 - https://github.com/frappe/erpnext/pull/30588
