### ISSUE TITLE
incorrect qty added on Purchase order if user tries to add multiple items

### ISSUE THREAD

**Issue by guruprasadsuryawanshi** [frappe/erpnext#23880]
Description of the issue

On Purchase Order when using add multiple rows qty always set to 1

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/73513833/98685133-01a6c680-238d-11eb-9ea7-24e8d5d0ab3a.gif)

Steps to reproduce the issue
	1 Go to Purchase Order doc
	2 Click on Add Multiple
 	3 select item 
 	4 enter qty

Expected result

An entered qty should be added in the item table.

Version : 
	ERPNext: v12.4.3 (version-12)
	Frappe Framework: v12.2.1 (version-12)

**Comment by rtdany10** [comment]
Any update on this one? Still facing the issue on
```
ERPNext: v12.19.0 (HEAD)
Frappe Framework: v12.16.3 (HEAD)
```

**Comment by rtdany10** [comment]
Adding this custom script is a work around:
```
refresh: function(frm) {
    frm.get_field("items").grid.set_multiple_add("item_code", "qty");
}
```

**Comment by deepeshgarg007** [comment]
Issue seems to be solved in the latest versions, closing this issue
