### ISSUE TITLE
Precision setting for currency field

### ISSUE THREAD

**Issue by ftorreti** [frappe/erpnext#2388]
Currently the precision setting for currency fields is not working properly. 

If a field is set as currency, a drop down menu with custom decimal precision settings appears on the top right allowing for selection of different options beyond what is specified in global settings. 

If the field is set as "Float" the change seems to be working ok. However if the field is set as currency the precision setting does not work. 

Here is the details of what happens:

We have modified the Purchase Order Item and Item Price fields for rate, price list rate and amount to reflect the float precision we need.

When we add a new item in a purchase order, the item rate from the price list is pulled correctly to the right digits (for example: 2.22222).

When we save the price list rate and the rate are automatically saved to only 2 digits (for example: 2.22000)

The above scenario works OK if the item rate is set as Float but according to the description of the Precision drop down menu, this should work also for currency otherwise there is no use for it appearing when the field is set as currency.

**Comment by umairsy** [comment]
Feature to define precision added in Customize Form.
