### ISSUE TITLE
Allow stock updates in real-time without closing the POS 

### ISSUE THREAD

**Issue by alishabab** [frappe/erpnext#23908]
**Is your feature request related to a problem? Please describe.**
Stocks quantity is not updated in real-time for the products sold through POS. It is updated when the user closes the POS.

**Describe the solution you'd like**
I would like that the stocks should be updated as soon as they are sold through POS.

**Describe alternatives you've considered**
I don't have any alternative for now

**Comment by tespheakdeyesoftix** [comment]
Any update on this. When will this feature update.
