### ISSUE TITLE
Having '&' in company name will change to '&amp;'

### ISSUE THREAD

**Issue by liamkinne** [frappe/erpnext#23901]
## Description of the issue

Having an ampersand character in the company name field does not work properly when setting up for the first time.

## Steps to reproduce the issue

1. Create trial account on erpnext.com
2. When setting up, use the '&' character in the company name

### Observed result

On the next page, the `&` becomes `&amp;`

e.g. `G&L Brothers` becomes `G&amp;L Brothers`

### Expected result

'&' to not be changed

**Comment by krush11** [comment]
Hi i would like to work on this issue but as this would be my first contribution to this repo i would need some help regarding which file(s) are causing this bug

**Comment by barredterra** [comment]
In ERPNext I can create a Company named G&L Brothers. This seems to be a problem with erpnext.com only.

![Bildschirmfoto 2020-11-24 um 12 49 53](https://user-images.githubusercontent.com/14891507/100090550-9a404a80-2e53-11eb-82f3-73bb5f2047e8.png)

(version 13 / develop branch)

**Comment by mako365-philippnagel** [comment]
This issue also occurs on instances launched via frappecloud.com
