### ISSUE TITLE
Import Chart of Account from another company at moment to create a new onw

### ISSUE THREAD

**Issue by williamjmorenor** [frappe/erpnext#2391]
I could be nice to import the Chart of Accounts of a Company to another one at moment of create a new one than will use the same Chart of Accounts

**Comment by mhbu50** [comment]
+1

**Comment by nabinhait** [comment]
**Company**
- add a new select field "Create Chart of Accounts Based On" with options "Standard Template" and "Existing Company"
- If "Existing Company" selected, show another field for "Existing Company"
- If "Standard Template" selected, show current existing field "Chart of Accounts" (can be renamed to Chart of Accounts Template)

On saving new company, create chart of accounts based on existing company's chart of accounts.
