### ISSUE TITLE
Unallocated amount is incorrectly calculated in Payment Entry when paying an Invoice in Non Base currency

### ISSUE THREAD

**Issue by palashjhabak** [frappe/erpnext#23936]
## Description of the issue
When a PI / SI is raised in a non Base currency (lets say USD) and we try to pay it through an account in the same none base currency (USD), the unallocated amount is wrongly calculated. Let me try to explain it in detail with an example. Lets say I have a supplier who deals in USD. The Supplier has raised me an invoice of 5000 USD and at the time book booking exchange rate w.r.t my currency was lets say 16. And at a later date I make a manual payment entry with an amount of 10000 USD ( paying from an account with currency USD ) and the exchange rate on that day was 15 which was entered in the PE for. Now unallocated amount in this scenario should be 5000 USD but the current implementation calculates it as 4333 USD. Now it calculates it incorrectly because it adds up all the allocated amount first in the base currency with exchange rate present in the PI and then calculates the unallocated amount in base currency and converts it back to USD with the exchange rate of PE but in reality, it shouldnt matter at all as the unallocated amount should just be 5000 USD as we are paying in USD to a PI raised in USD

## Context information (for bug reports)

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1.
2.
3.

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by fproldan** [comment]
@palashjhabak Hi, were you able to fix it?

**Comment by palashjhabak** [comment]
@fproldan its been a long while since I raised the issue so don't exactly remember but I will check if I did something in my custom app to fix it and let you know. 

PS: apologies for such a late reply

**Comment by dj12djdjs** [comment]
https://github.com/frappe/erpnext/issues/34680

**Comment by dj12djdjs** [comment]
Another example:

1. Setup company with base currency CAD
2. Create a Purchase Invoice at $100.00 value of USD currency using 1.3417 exchange rate.
3. Create Payment Entry of $1000 USD paid $1360.00 CAD at 1.360 exchange rate.
4. Allocated $100 of the $1000 Payment Entry against the $100.00 Purchase Invoice.

**Expected Unallocated Amount:** $900 USD
**Observed Unallocated Amount:** $901.35 USD

**Comment by ruthra-kumar** [comment]
This issue should be fixed post the multi-currency refactor in v14 and above, https://github.com/frappe/erpnext/issues/34680.
