### ISSUE TITLE
Account Name or Number change not immediately reflected in COA Tree View

### ISSUE THREAD

**Issue by Tropicalrambler** [frappe/erpnext#23939]
# Description of the issue
After clicking edit account button from chart of accounts tree view, updating account name or number, and pressing the back button on the browser to return to Chart of Accounts tree view, the name/number change is not shown immediately. User must refresh screen, and navigate to previous position to see the update.  This behavior does **not** happen in Cost Center or Item Group tree view.

### Expected result
Once user modifies account name or number, and navigates back to Chart of Accounts Tree View, it must be immediately shown

### Stacktrace / full error message
ERPNext version 12.13.0

**Comment by deepeshgarg007** [comment]
Not replicable anymore, working fine without refresh as expected. Closing this
