### ISSUE TITLE
Multiple PO for SO for same supplier in item line ( drop shipping section )

### ISSUE THREAD

**Issue by aambernath** [frappe/erpnext#23945]
## Description of the issue
Create PO from SO has an issue, if a PO has been already created for a supplier A and if I try to create another PO for the same supplier A for another line item in the SO, it gives an error

## Context information (for bug reports)

**Output of `bench version`**
erpnext 12.13.0
frappe 12.11.0

## Steps to reproduce the issue

1. Create a PO with 2 items, with same supplier
2. Create a PO with 1 item for supplier
3. Try to create another PO with 2nd item for supplier

### Observed result
PO already create for all items in SO

### Expected result
Creates another PO with the supplier

**Comment by deepeshgarg007** [comment]
@aambernath This should be resolved now, please check. Closing this issue
