### ISSUE TITLE
Item from Sales / Purchase Orders Selection

### ISSUE THREAD

**Issue by ShehataGhattas** [frappe/erpnext#23988]
Dear Community ,
is their any one can help me and et me know why in the new Versions from ERPNEXT I am missing to get the item selection to create invoice for specific lines only either from the Sales / Purchase Orders , Check the below Images and screen shoot
![image](https://user-images.githubusercontent.com/22128816/100055728-5b9b9780-2e35-11eb-9110-0a858d4ae279.png)

**Comment by sharmanakul** [comment]
seems like this was resolved in the later versions.
