### ISSUE TITLE
Allow users to edit only certain documents

### ISSUE THREAD

**Issue by 0xpr03** [frappe/erpnext#24006]
**Is your feature request related to a problem? Please describe.**
I'd like project managers of certain projects to edit their project, that were created for them. Currently it is not possible to let a user view all projects but also only edit certain projects.

**Describe the solution you'd like**
Allow user permissions to give additional permissions instead of only take access to documents.

**Describe alternatives you've considered**
The only workaround is that only some trusted people can change every project and PMs can't do anything.

**Additional context**
I is not sufficient to let project managers create their own projects or only view (and edit) their projects.

**Comment by sharmanakul** [comment]
i'd like to know the use-case in detail for this.

you can provide extra permission to the users through role persmission manager. you can also restrict the access for certain users through user permissions.

**Comment by 0xpr03** [comment]
A past employer had the need to allow many people watching past projects but only the people working on them to edit these projects.
