### ISSUE TITLE
Sales Invoice "create payment" button does not work after updating 

### ISSUE THREAD

**Issue by zahra-erp** [frappe/erpnext#24014]
after updating the version for our customer from 
- ERPNext v12.12.1 to v12.14.0
- Frappe Framework v12.10.2 to v12.12.0

the button of 'create' > 'payment' does not work and gives error

**Server Error: 'NoneType' object has no attribute 'bank'**

**Comment by zahra-erp** [comment]
Any help , please.

**Comment by sharmanakul** [comment]
this has been resolved in the later versions. closing it.
