### ISSUE TITLE
Visual Stimulation

### ISSUE THREAD

**Issue by MarcDadiyo** [frappe/erpnext#24011]
clients and general users of erp next have a good and basic acceptance of erp-next, but perhaps its time for some color and quick demo snip videos of how to use the software when it first loads. Its a very professional and efficient system but the interface needs to draw-in as well. At least on a general user account perspective.

**Comment by barredterra** [comment]
V13 is expected to come with a new design. To see it, install the `rebrand-ui` branches or check this [preview on youtube](https://www.youtube.com/watch?v=hGFCneNdH3I).

Closing this issue for now.
