### ISSUE TITLE
 Stock entry , production order link

### ISSUE THREAD

**Issue by bobzz-zone** [frappe/erpnext#2403]
i want to connect STE that has purpose as Material Issue with production order, i can make the fled appear and can be filled but i cant make it saved

Here my case ,
in the production i cant keep track of each material that used in production , but i can track the result , so i want to track the result daily but i want to enter the materials that prepared for all production in one go, so i think i need to create material issue ,since its not transfered , because i assumed that allocated materials is used from the start, and its also not manufatured because i cant enter all materials that i want to issues because i might issues materials for 1000 items but in one day just getting 100 in result, so if i put it in manufature it will give me error because total materials will be much more than the manufactured items

so i planned to create material issues for 1000 items (for example), but then i can create manufacturing STE that said today i just have 100 items as a result so far

**Comment by umairsy** [comment]
Closing this issue since no update from very long. Feel free to reopen if needed.
