### ISSUE TITLE
V13 - Payment Entry - Multicurrency Payment - Deductions or loss should NOT be only in company currency

### ISSUE THREAD

**Issue by iamkhalidbashir** [frappe/erpnext#24045]
## Description of the issue
While creating Payment Entries in a multicurrency entry, deductions or loss should **NOT be only** in company currency. It should be in the currency of "Account paid to" or the deduction account currency

## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 13.x.x-develop
frappe 13.x.x-develop
```

## Steps to reproduce the issue

1. Create a New Payment Entry
2. Select a Foreign Account
3. Allocate to all outstanding invoices
4. There should be a Difference Amount
5. Click on Set Deductions or loss
6. ERPNext should create a difference entry in deduction account currency instead of company currency

### Observed result
![Screenshot from 2020-12-02 18-49-11](https://user-images.githubusercontent.com/27646811/100882204-bafe4500-34d0-11eb-8982-baa188060197.png)

### Expected result
Should allow a non-comapny currency account 

## Additional information

Reference: https://github.com/frappe/erpnext/issues/10145

**Comment by iamkhalidbashir** [comment]
@abhishekbalam @Anuja-pawar @rohitwaghchaure 
Could you guys look into it?

**Comment by deepeshgarg007** [comment]
@iamkhalidbashir The deduction and loss are ultimately for the company doing the transaction and not for the customer or supplier's info, hence it's only in company's current, any reason why it should be in other currency as well, please explain and reopen
