### ISSUE TITLE
Registering new user - Unable to create new user in ERPNext website

### ISSUE THREAD

**Issue by Skyeits** [frappe/erpnext#24040]
ERPNext website module is throwing error 'Incorrect email or password. Please check your login credentials.' when registering new user
![New User Registration](https://user-images.githubusercontent.com/66351426/100738508-ab60fc80-33fb-11eb-9f5d-14eb3131994f.JPG)

**Comment by sharmanakul** [comment]
hey, seems like this has been fixed.

closing it. please reopen if you are still facing it.
