### ISSUE TITLE
Version-13 Frappe.cloud (Distributed cost center not distributing the cost with assosiated cost center)

### ISSUE THREAD

**Issue by sammish** [frappe/erpnext#24083]
Team, 
We have 3 Cost center

This is distributed cost center 

We have enabled  50% for each cost center 

We made transaction 
Now, the result 

Distributed cost center not distributing the cost with associated cost center

The transaction affecting direct to the cost center

![ScreenRecorderProject12](https://user-images.githubusercontent.com/12432802/101452995-ad691500-393f-11eb-8738-72fa3a46d0d2.gif)

**Comment by sammish** [comment]
@nabinhait @karthikeyan5 @Vigneshsekar 
Please consider this issue.

**Comment by KaviyaPeriyasamy** [comment]
Hello Sammish,
I checked with the same use case as you mentioned above. The cost are correctly distributed to the associated cost centers with the allocated percentage. Do you have any transactions for the non-distributed cost center? If yes means, the ``` percentage``` of the ``` distributed cost center``` amount will be added to the actual amount of the ``` associated cost center```.


![cost_center](https://user-images.githubusercontent.com/36359901/101597068-2f2e7080-3a1c-11eb-9572-c5c96eefcdf9.gif)

**Comment by sammish** [comment]
@KaviyaPeriyasamy 
Actually , I expected Distributed cost center value must be "zero". Because, it self a Distributed cost center not accommodating any value. If the value will appear the Profitability Analysis report, its concept making confusion.

Or, 
Can you add a "Tick" Option upon "Show Distributed value" or " Show Distributed Cost Center"

![image](https://user-images.githubusercontent.com/12432802/101668495-aa664580-3a61-11eb-8fdb-47fd539d366b.png)

Thanks.
