### ISSUE TITLE
[Paid Development]  - Multi Currency Payroll

### ISSUE THREAD

**Issue by joephilar** [frappe/erpnext#24105]
Hi,

Our company has payroll employees in CRC (Costa Rican Colones), which is the Company's Default Currency, as well as others in USD.

We understand that ERPNext doesn't have this functionality yet and we need it in order to implement this module, we are willing to sponsor this development, if the cost is not too high.

Process:
> In the employee registry must indicate the currency and each item must be in terms of said currency.
> In the reports, the detail and the totals must appear in the different currencies used.
> When generating the accounting entry, the impact must consider the exchange rate.
> Accumulated amounts are in the currency indicated by each employee

Why is this important? Here are some similar community requests:
 - https://discuss.erpnext.com/t/multi-currency-payroll/20041
 - https://discuss.erpnext.com/t/multiple-currencies-for-single-payroll/31618
 - https://discuss.erpnext.com/t/employee-salary-in-multicurrency/36455
 - https://github.com/frappe/erpnext/issues/11877
 - https://github.com/frappe/erpnext/issues/18100

Thanks,

Joe

**Comment by marination** [comment]
It has recently been implemented here https://github.com/frappe/erpnext/pull/23519
