### ISSUE TITLE
Uniqeness Checking in Supplier Invoice Number

### ISSUE THREAD

**Issue by maheshengg** [frappe/erpnext#2412]
Problem.

During Entry of Purchase Invoice, many a times, due to error or accidently, it so happens that one bills is being tried by our user/s to be fed twice.

Example, Let us say there is a Invoice no 3411 is already taken up for purchase invoice entry say PUR-ENTRY-1 the same number ( same invoice is also accepted by system ) say PUR-ENTRY-2

We feel there should be a check point at GRN Level as well as Purchase Entry level with following logic.

If supplier = ABC Limited and If Shipment no. is 3411, then, Only one unique GRN (once made, then "no" for same ABC Limited always)

If supplier = ACB Limited and If Supplier Invoice no. 3411 then Only once entry should be taken ( i.e checking if user has already entered 3411 for that supplier )

Needless to say, the Character Matching manipulation like 003411 or A3411 cannot be helped, we understand that, but exact match should not be allowed

Current Limitation : 
Recently, Developers have removed the validation of supplier bill no in purchase invoice. Because, many people do not enter bill no field, in that case they were forced to enter "NA". The logic was, system will not validate in case bill no is "NA". Now this system don't work in case of multilingual, users enters "NA" in their language. And system tries to validate the value and it gived wrong validation. We did not find any easy solution for this, hence decided to drop the feature.

"Shipment No" in Purchase Receipt is a custom field in your account, hence there is no unique validation.

SOLUTION 
To explore possibilities to cater to those who require this feature (like me)
probably you can build this around by the following logic.

Accounts > Set up > Option called as Purchase Invoice Validation Required  YES/NO

If YES,

Validate the Purchase Invoice No. ( for a supplier )

if NO,

Continue as per current

Same: For Custom Fields, ( to configure the field if "uniques" is required or not )

**Comment by nabinhait** [comment]
@maheshengg Enable `Check Supplier Invoice Number Uniqueness` in Accounts Settings
