### ISSUE TITLE
UOM conversion factor not get changed after changing item code in the selling or buying child items table

### ISSUE THREAD

**Issue by faisal-zahoor** [frappe/erpnext#24167]
## Context information (for bug reports)

**Output of `bench version`**
```
version 12
```

## Steps to reproduce the issue

1. Select default UOM for selling other than stock UOM and give it a conversion factor in UOM's  table
2. Create 2 to 3 items with same process
3. In the sales order item add item code and it will work fine and fetch selling UOM and its conversion factor
4. now change the item code and bug is here UOM get changed but conversion factor remain same
5. same for buying cycle

### Observed result
Conversion factor not get changed

### Expected result
When i change item code conversion factor should also get changed as UOM get updated

### Stacktrace / full error message

```
Logical bug
```

**Comment by szufisher** [comment]
same issue on version 13.12.1
how to reproduce
1. in sales order items table, select one item
2. change to another item which has default sales UOM different than basic UOM and conversion factor between sales UOM and basic UOM, system auto fetched the correct sales UOM, but conversion factor not updated as expected.

Our solution

override get_item_details as below

simply remove the conversion_factor from the args, which force the system to fetch conversion factor for the (new) item.

![image](https://user-images.githubusercontent.com/12823863/137339588-b0472167-f766-46c0-90ee-8650cfeb1c40.png)

**Comment by sharmanakul** [comment]
@s-aga-r please check this

**Comment by s-aga-r** [comment]
I think this issue has been resolved. @faisal-zahoor Let me know if I do something different.
 
**Checked-in:**

[Sales Order](https://user-images.githubusercontent.com/63660334/174848931-67358950-4d37-41dc-8de6-f286ba8da888.mov)

[Quotation](https://user-images.githubusercontent.com/63660334/174849097-32ca8e8b-a65e-448f-b7a7-c313033e1d7c.mov)

[Purchase Order](https://user-images.githubusercontent.com/63660334/174849228-bd241d7b-460a-4750-99cf-3d0a05bdfa9b.mov)

[Supplier Quotation](https://user-images.githubusercontent.com/63660334/174849324-c095f058-8a77-4c4c-9f25-df4269d40b78.mov)
