### ISSUE TITLE
Version-13 Frappe.cloud : Employee Checkin entry duplicating 

### ISSUE THREAD

**Issue by sammish** [frappe/erpnext#24165]
Hello Team, 

Employee check entry duplicating automatically. 

I am using MB20_ZKTeco Machine (https://www.amazon.sa/gp/product/B07V46SZW9/ref=ppx_yo_dt_b_asin_image_o00_s00?ie=UTF8&psc=1)

![image](https://user-images.githubusercontent.com/12432802/102452436-68359900-404b-11eb-9016-08253e305ff2.png)

**Comment by sammish** [comment]
@karthikeyan5 @Vigneshsekar @KaviyaPeriyasamy 

Please consider this issue.

**Comment by karthikeyan5** [comment]
@sammish, this should not be possible. There is a [validation to prevent this](https://github.com/frappe/erpnext/blob/3a251ecb267457738cfd85af8b56feded7182317/erpnext/hr/doctype/employee_checkin/employee_checkin.py#L15). 

Suggest you debug further and find how this is happening in your instance alone.

**Comment by sammish** [comment]
Hi, @karthikeyan5 
Thanks for the reply 

I have 3 machines (U350 2Nos) and MB20_ZKTeco (1 Nos)

Whatever fingers coming from the MB20_ZKTeco there is duplicate issue. 
Other device has no duplicate issue, But this issue. (  https://github.com/frappe/biometric-attendance-sync-tool/issues/20 )
