### ISSUE TITLE
Stock Entry and Credit note

### ISSUE THREAD

**Issue by annperera21** [frappe/erpnext#2416]
hi,stock entry  no is  STE-00203  and i made a credit note for that just now and it no is JV-01079.
but when it go back to stock entry STE-00203. it still show make credit note button. why is that. but i already created a credit note for that.in your program we can make many credit note for 1 stock entry.
and there is no link between stock entry and credit note journal entry. please make link between stock entry and credit note journal entry. it is very useful for us.

**Comment by neilLasrado** [comment]
Will be done in v5

**Comment by neilLasrado** [comment]
This issue is solved and merged !
