### ISSUE TITLE
Add multiple manufacturers to Item form

### ISSUE THREAD

**Issue by lemco1982** [frappe/erpnext#2417]
In the Item form, someone is able to enter multiple different suppliers for a specific Item (since the supplier field it is a table) but only one manufacturer.

In my opinion, someone must be able to enter multiple manufacturers (with their specific part number) too as he does for suppliers to be more realistic...

Eg. One 100nF capacitor can be made from different manufacturers like Samsung, EPCOS etc… and can be purchased from different suppliers eg. Digikey, Mouser etc…

**Comment by lemco1982** [comment]
Any update?

**Comment by umairsy** [comment]
You can add Custom child Doctype in the Item master for this.
