### ISSUE TITLE
Setup wizard doesn't work properly on develop branch

### ISSUE THREAD

**Issue by rhuanbarreto** [frappe/erpnext#24190]
## Description of the issue

Running the image from the PWD button brings a working environment but the setup wizard is not working as expected.

![image](https://user-images.githubusercontent.com/283004/102896519-ce188b00-4466-11eb-830e-56c4e6829e6f.png)

Putting a breakpoint on the line, you can see the error:

![image](https://user-images.githubusercontent.com/283004/102896625-fbfdcf80-4466-11eb-81b2-6622d68109ee.png)

Maybe it's a version problem in the pwd.yaml file?

## Steps to reproduce the issue

1. Go to the root of the repository and click on the Try with PWD
2. Wait for the installation to run
3. Run the system on port 80 and login as the default user
4. Fill up all info and on step 3 choose any modules. You can't go forward.

### Expected result

It's expected to go to the next step.

### Stacktrace / full error message if available

Described on the images above.

**Comment by tionebrr** [comment]
Same problem with a frappe-docker install with $VERSION=edge.
What is the last known working version?

**Comment by revant** [comment]
Use v12 for latest stable version

**Comment by revant** [comment]
Workaround found here

https://discuss.erpnext.com/t/we-are-not-moving-to-the-next-step-from-select-your-domains/69249/8

**Comment by RustemHesenov** [comment]
I hope this problem will be solved by the developers asap. But I have some concerns.

I installed ERP Next via docker using the [video](https://www.youtube.com/watch?v=_08L9pubPCY&feature=youtu.be
).


My problem is: How do I update my own server after the problem is fixed? What should I do in the Docker environment?

**Comment by RustemHesenov** [comment]
@revant Why is this issue not marked as a bug yet?

**Comment by revant** [comment]
> My problem is: How do I update my own server after the problem is fixed? What should I do in the Docker environment?

- edit the .env file
- change the FRAPPE_VERSION and ERPNEXT_VERSION to exact tag of new version
- `docker-compose up -d` again

This will pull new images and start the docker containers with new images, It should also run migrations if AUTO_MIGRATE=1 is [set](https://github.com/frappe/frappe_docker/blob/develop/docs/single-bench.md#setup-environment-variables).
