### ISSUE TITLE
Comments from Support team not Visible to Customer on their portal 

### ISSUE THREAD

**Issue by CITYSUPPORT-ANS** [frappe/erpnext#24199]
## Description of the issue
Comments from the Support team/user not visible to Customers on their customer portal.

## Context information (for bug reports)

**Output of `bench version`**
```
Don't know the bench version. ( using ERPNEXT instance from Frappe Cloud )
```

## Steps to reproduce the issue

1. Created Webform 

![image](https://user-images.githubusercontent.com/66312477/102990159-ee1a7e00-453c-11eb-8294-2a89e53708ac.png)

2.  Portal Setting 

![image](https://user-images.githubusercontent.com/66312477/102990317-2a4dde80-453d-11eb-86e7-6276eeda04a1.png)

Custom Sidebar Menu

![image](https://user-images.githubusercontent.com/66312477/102990431-5ff2c780-453d-11eb-9909-be580e6ec7d2.png)

3. Created issue from Customer portal and comment 

![image](https://user-images.githubusercontent.com/66312477/102990641-bcee7d80-453d-11eb-8846-8d9ce8bd1ab7.png)

4. Comment from customer visible to Support team/user 
    but comment from support team/user not visible to the customer.

![image](https://user-images.githubusercontent.com/66312477/102990781-faeba180-453d-11eb-821c-b6fec5baae2c.png)

### Observed result
The customer's comment is visible to the support team but the Support team comment can not visible to the customer.

### Expected result

if the support team comment on a customer's issue, it should be visible to the customer from their customer portal.

### Stacktrace / full error message

```
No Error message found
```

## Additional information

Installed Apps
ERPNext: v13.0.0-beta.6 (HEAD)

Frappe Framework: v13.0.0-beta.8 (HEAD)

**Comment by prinzpiuz** [comment]
any update on this  issue.. I am also facing same issue

**Comment by CITYSUPPORT-ANS** [comment]
No, @prinzpiuz

**Comment by prinzpiuz** [comment]
@CITYSUPPORT-ANS  is it anything related to permission ... i have given, read permission for customer for comment doctype still not working

**Comment by prinzpiuz** [comment]
@CITYSUPPORT-ANS mine is solved after opening each comment from comment list and publishing it also you need to add comment by option to get commented person's name

**Comment by CITYSUPPORT-ANS** [comment]
Incomment DocType check Published 

![image](https://user-images.githubusercontent.com/66312477/107118977-7b761f80-68aa-11eb-825b-9e23a0ed8743.png)

**Comment by kittiu** [comment]
Setting published is one way, but I think the proper way is to add permission for comment to the portal group user (i.e., in this case Innovation User)

![Selection_117](https://user-images.githubusercontent.com/1973598/188774235-c82e8bf8-7b7f-40a4-8cd2-113dabdeedf8.png)
