### ISSUE TITLE
Attachments are visible to all users even if they are marked as private during upload

### ISSUE THREAD

**Issue by musaddiqsajjad** [frappe/erpnext#24212]

**Comment by musaddiqsajjad** [comment]
@adityahase 

@netchampfaris 

I am kindly requesting your support as our organization is heavily impacted by this. Thank you!

**Comment by adityahase** [comment]
@musaddiqsajjad Thank you for reporting this. I've removed the steps to replicate this, at least until we patch this. We request you to not publish this anywhere else for the next 60 days.

Please see http://erpnext.com/security report vulnerabilities. Also, please report this issue using https://erpnext.com/security/report

**Comment by musaddiqsajjad** [comment]
@adityahase This issue is not yet fixed. I've also reported it using the link you provided.

Does it usually take 60 days to resolve a simple access control issue?
