### ISSUE TITLE
v12 to v13 beta-7 migrate issue frappe.exceptions.DoesNotExistError: DocType E Invoice Settings not found

### ISSUE THREAD

**Issue by Suraj787** [frappe/erpnext#24218]
v12 to v13 beta-7 on  migrate issue 
frappe.exceptions.DoesNotExistError: DocType E Invoice Settings not found

**Comment by saurabhnandu** [comment]
if you upgrade to the latest version of v12 and then run migration the issue is fixed. I think the latest version of v12 creates the appropriate E Invoice settings docktype

**Comment by neelbhanushali** [comment]
Duplicate of #24968

**Comment by neelbhanushali** [comment]
Similar to #24968

**Comment by akazyti** [comment]
Skip All Failing and then It will automatically update the doctypes for frappe and erpnext
```
bench migrate --skip-failing
```
