### ISSUE TITLE
AttributeError: 'FiscalYear' object has no attribute 'is_short_year'

### ISSUE THREAD

**Issue by martinhbramwell** [frappe/erpnext#24232]
## Description of the issue

Creation of new fiscal year fails with:

```AttributeError: 'FiscalYear' object has no attribute 'is_short_year'```

## Context information (for bug reports)

```
erpdev@loso:~/frappe-bench-DLS$ bench version
erpnext 13.0.0-beta.7
frappe 13.0.0-beta.9
erpdev@loso:~/frappe-bench-DLS$ 
```

## Steps to reproduce the issue

1. Attempt to add a fiscal year via user interface
2. Attempt to add a fiscal year via API.

### Observed result

```AttributeError: 'FiscalYear' object has no attribute 'is_short_year'```

### Expected result

A new fiscal year

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

```
erpdev@loso:~/frappe-bench-DLS$ sudo -A lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
erpdev@loso:~/frappe-bench-DLS$ 
```

**Comment by barredterra** [comment]
A quick workaround if you don't have server access is to go to Menu > Customize and add a new field:

- Type: Check
- Label: Is Short Year
- Name: is_short_year

**Comment by barredterra** [comment]
Couldn't reproduce the issue. 

https://user-images.githubusercontent.com/14891507/103929131-1e594380-511d-11eb-9bb3-34c6c78004aa.mov

```
> lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic

> bench --version
5.0.0

> bench version  
erpnext 13.0.0-beta.9
frappe 13.0.0-beta.9
```


It looks like the field `is_short_year` is missing in your doctype. This might happen if you pull a newer version without running `bench migrate`.

Please run `bench migrate` to update your DocTypes / database to be at the same version as the related code.
