### ISSUE TITLE
Upgrading to ERPNext version 12 to 13 beta 6 - update_returned_qty_in_pr_dn  patch takes more than 4 hours then times out

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#24234]
![image](https://user-images.githubusercontent.com/1822868/103282217-252ddb00-49e6-11eb-89c0-2ffdd6479a2a.png)

It took more than 4 hours to run this patch, and eventually connection to database was lost.

All other patches ran well.

The database has:
Delivery Notes: 56,575
Returned Delivery Notes: 7,494

Purchase Receipts: 5,192
Returned Purchase Receipts: 73

**Comment by sharmanakul** [comment]
hey, i'm closing it for now considering this might have been resolved or you found some workaround.

please confirm and feel free to reopen if is still persists.

**Comment by muchai** [comment]
Found a workaround. Commented out the line for that patch.:)

**Comment by ankush** [comment]
btw this is anyways fixed via https://github.com/frappe/erpnext/pull/27001
