### ISSUE TITLE
Desk translation page bug ( json.decoder)

### ISSUE THREAD

**Issue by mshanak** [frappe/erpnext#24231]
## Description of the issue
The problem appears when we try to open the translation page in the Desk, the error says that there is a problem in json.decode, attached a screenshot of the problem.
![133666403_147361203618517_48513183886612464_n](https://user-images.githubusercontent.com/964266/103274074-6b287600-49c9-11eb-9af7-97a3779600b4.png)

## Context information (for bug reports)
We try to update the translation for Arabic and Hebrew languages.

**Output of `bench version`**
```
Erpnext v13-beta-6
```

## Steps to reproduce the issue

1. Go to search 
2. search for translation
3. select translation-tool

### Observed result
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

 

 

## Additional information

OS: Centos
distribution: Erpnext v13-beta-6
install method: manual

**Comment by pateljannat** [comment]
@mshanak can you try the translation tool again. The issue has been resolved so the error won't occur.

**Comment by mshanak** [comment]
@pateljannat do i need to run ‘bench update’ ?

**Comment by pateljannat** [comment]
@mshanak yes try that

**Comment by mshanak** [comment]
After running `bench update`,  the page is working now.
The issue is resolved.
