### ISSUE TITLE
Need Website > Web Form > Custom Javascript

### ISSUE THREAD

**Issue by revant** [frappe/erpnext#2423]
Just like adding a "Custom Javascript" is possible for a "Web Page" it should be available for "Web Form"

Example:
While asking for email id in Web Form, Text or Data fieldtype is selected and it is possible for the website visitor to input any text as email, instead of correct format of user@example.com. Custom Javascript can solve the problem for not just email.

**Comment by Arundhatii** [comment]
@revant  is this still relevant? Feel free to re-open if you think its important.
