### ISSUE TITLE
Standard Costing

### ISSUE THREAD

**Issue by CableKing** [frappe/erpnext#2424]
Hello,

Could you please add the capability to do actual manufacturing pricing (not just BOM cost estimation) based on a price list?

This is a very common practice for US corporations and a standard feature in systems like Oracle, SAP, and MS Dynamics. The practice is called standard pricing. In addition to enabling the price list valuation in the item master (for raw materials), it also requires tracking another account, let call it PPV or purchase price variance. PPV is a subset of COGS which tracks the difference between the PO price and the price list.

(I use the Frappe Cloud version.)

Thank you!

Best,
CableKing

**Comment by shachiTakalkar** [comment]
We have implemented the feature of adding the margin on the price list . 
https://frappe.github.io/erpnext/user/manual/en/selling/articles/adding-margin

**Comment by Arundhatii** [comment]
If this is relevant, please Feel free to re-open if you think its important.

**Comment by osstechnolab** [comment]
Hi, 

I think the feature @CableKing  is talking to is the tracking of Purchase Price Variance from Standard Cost.  This one is missing in ERPNext.

Bests,

Jeff
