### ISSUE TITLE
Cancelling a group of BOMs

### ISSUE THREAD

**Issue by CableKing** [frappe/erpnext#2425]
Hello,

Currently there is an option to import and submit a group of BOMs however there is no way to Cancel a group of BOMs. Mass loads lead to mass errors and the only way to remove unwanted BOMs is to submit a ticket to have all BOMs removed and then to re-import everything.

Would it be possible to add a group cancel feature (similar to a the group delete feature)?

Best,
CableKing

**Comment by strixaluco** [comment]
Probably better to keep #3191 open, as this one is its specific duplicate.
