### ISSUE TITLE
Bank Statement uploaded in Bank Reconciliation is repeating in all account 

### ISSUE THREAD

**Issue by 960106** [frappe/erpnext#24250]
I’m having 3 account Saving, Current and Forex Account. When i upload the bank statement in Bank Reconciliation in Saving Account it is reflected in Forex And Current account too. It mean all the 3 account is having Bank reconciliation statement.

I deleted Bank Transaction of Current and Forex account still in the bank reconciliation i find the bank statement.

Thanks in Advance!

**Comment by deepeshgarg007** [comment]
@960106 Please elaborate more on the issue and then reopen
