### ISSUE TITLE
Erpnext 13 - error when creating Item Price

### ISSUE THREAD

**Issue by dnyt84** [frappe/erpnext#24278]
## Description of the issue
When creating a Price for a new Item.

**Output of `bench version`**
```
bench version
erpnext 13.x.x-develop
frappe 13.x.x-develop
I just did a bench update as well
```

## Steps to reproduce the issue
I 1st created a new Item. 
Then I went to Selling -> Item Price
Searched for my Item and then Clicked on "create a new Item Price"
Item Code was filled in already from previous Page
Price List -> "Standard Selling" (i tried Standard Buying as well, same error)
Rate: 390.00

### Observed result
When I click on Save, nothing happens.
### Expected result
Create a new Price for my Item

### Stacktrace / full error message
Uncaught TypeError: e.replace is not a function
    at window.strip_html (common.js:111)
    at frappe.ui.Dialog.get_values (field_group.js:89)
    at HTMLButtonElement.<anonymous> (dialog.js:141)
    at HTMLButtonElement.dispatch (jquery.min.js:3)
    at HTMLButtonElement.r.handle (jquery.min.js:3)
    at Object.trigger (jquery.min.js:4)
    at HTMLButtonElement.<anonymous> (jquery.min.js:4)
    at Function.each (jquery.min.js:2)
    at n.fn.init.each (jquery.min.js:2)
    at n.fn.init.trigger (jquery.min.js:4)
window.strip_html @ common.js:111
get_values @ field_group.js:89
(anonymous) @ dialog.js:141
dispatch @ jquery.min.js:3
r.handle @ jquery.min.js:3
trigger @ jquery.min.js:4
(anonymous) @ jquery.min.js:4
each @ jquery.min.js:2
each @ jquery.min.js:2
trigger @ jquery.min.js:4
(anonymous) @ field_group.js:70
dispatch @ jquery.min.js:3
r.handle @ jquery.min.js:3

## Additional information

OS version / distribution, `ERPNext` install method, etc.
Ubuntu  20.04.1 LTS, MariaDB 10.4.17 (upgraded from ERPNext Image)

**Comment by saudlenok** [comment]
Getting the same issue while trying to assign a task to an employee in Projects Kanban

**Comment by dnyt84** [comment]
I just pulled latest code and it appears to be fixed?

**Comment by ankush** [comment]
Not reproducible anymore. https://github.com/frappe/frappe/commit/51b089e2d6c4add6befb365715a3b20d9db04c7d
