### ISSUE TITLE
Frappe.Cloud : Version-13 Leave Period has no Grant Leaves appearing.

### ISSUE THREAD

**Issue by sammish** [frappe/erpnext#24286]
Dear Team.

Leave Period has no Grant Leaves appearing.
![image](https://user-images.githubusercontent.com/12432802/103519974-79720880-4e87-11eb-90c0-13254a6bd5cd.png)

Frappe.Cloud : Version-13

![image](https://user-images.githubusercontent.com/12432802/103519671-fcdf2a00-4e86-11eb-8bf6-c52a68b9ae6c.png)

**Comment by ChandrahasMuvvala** [comment]
This has been moved to "Leave Policy Assignment"
