### ISSUE TITLE
Purchase Order Update Items Button not updating ordered qty when adding new line item

### ISSUE THREAD

**Issue by sathouel** [frappe/erpnext#24326]
## Description of the issue

When a new line item is added using the "Update Items" button on a submitted Purchase Order, the Ordered quantity does not change in the corresponding Bin Doc

## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 12.13.0
frappe 12.11.0
```

## Steps to reproduce the issue

1. Create Purchase Order with one line item let say item_code_1 then SUBMIT it
2. Use the Update Items Button to add new row in child table with item item_code_2

### Observed result

The bin corresponding to the new row within the child table is not updated.

### Expected result

We expect to see the ordered qty of the corresponding new row updated

**Comment by sathouel** [comment]
The problem is due to the fact that when the new line item are created, the warehouse is not set. Thus the `update_ordered_qty` method of the purchase order controller is not updating it.
I fixed the problem on my instance by setting the warehouse within the `before_update_after_submit` hook

**Comment by deepeshgarg007** [comment]
@sathouel Seems to be working fine in the latest version, closing this
