### ISSUE TITLE
Taxjar - can't disable

### ISSUE THREAD

**Issue by dnyt84** [frappe/erpnext#24335]
Hello,

i am running the latest DEV version of ERPNEXT and Bench.

When I try to disable taxjar it ignores all the checkboxes and I can't remove the API, Tax Account Head and Shipping Account Head

I have all checkboxes unchecked and it still uses taxjar to calculate taxes when creating a sales invoice.

I tried to change the API key to something random and when creating a sales invoice I now get an error popup:
"Not authorized for route 'POST /v2/taxes'"

Should we maybe cache the results so we can use Taxjar even if they are or we have internet problems?

Thank you!

Daniel

**Comment by dnyt84** [comment]
Update

There is no way to just disable Taxjar but you can delete Taxjar settings.
In the Taxjar settings click on Menu -> Delete
This will delete and stop erpnext from using taxjar.

It still should be checked why when unchecking "Enable Tax Calculation" that it still calculates sales tax using taxjar.

**Comment by deepeshgarg007** [comment]
@dnyt84 This should be resolved now, it move to a separate app
