### ISSUE TITLE
Salary Component not fetching in Additional Salary : frappe.cloud- version-13

### ISSUE THREAD

**Issue by sammish** [frappe/erpnext#24344]
Dear All, 

Salary Component not fetching in Additional Salary : frappe.cloud- version-13

![image](https://user-images.githubusercontent.com/12432802/104197044-96817b00-5435-11eb-82cd-49f8f9554752.png)

**Comment by ruchamahabal** [comment]
Have you set up the Company and Account in the child table of the Salary Component. The list is filtered accordingly.

![image](https://user-images.githubusercontent.com/24353136/113096278-81d1a980-9212-11eb-92aa-52ef176e506a.png)

**Comment by sammish** [comment]
I think It's fixed Last release.
