### ISSUE TITLE
Auto repeat frequency based on duration

### ISSUE THREAD

**Issue by ryuliantoro** [frappe/erpnext#24347]
**Is your feature request related to a problem? Please describe.**
The existing auto-repeat frequency can only repeat based on time period (daily, weekly, etc.).
So it can't repeat based on duration of time (every 25 days, every 3 weeks, every 2 month (bimonthly), etc.)

**Describe the solution you'd like**
Additional capability to set the frequency based on duration.

**Describe alternatives you've considered**
Currently there is no alternative for this issue.

**Comment by fderyckel** [comment]
I would love that.   That code could then be refactored in many places within ERPNext: meeting, courses, subscriptions, etc.

**Comment by skjbulcher** [comment]
I believe the restriction is due to the way way auto repeat is implemented in Frappe. I created a feature request that I'd like to document in this issue: https://github.com/frappe/frappe/issues/12172

**Comment by jpubb** [comment]
@ryuliantoro @fderyckel I think a PR has been submitted to cover this....

https://github.com/frappe/frappe/pull/13576

This will allow Auto-Repeats by minutes interval. So you can definie whatever interval you want from there.  

i.e.   **"Every 2 weeks =  every 20160 minutes"**

VERY useful I think.  It would be great if the PR was adopted to core.
