### ISSUE TITLE
Purchase orders marked as recurring on print

### ISSUE THREAD

**Issue by zefrenchemen** [frappe/erpnext#2437]
Hello. New user and very impressed with erpnext up to now. Weird little bug created havoc today : when creating purchase orders, they are - by default- not recurring. That's the way we want it to be, but when printing, or even previewing the PO, it's marked as recurring monthly on the right lower side. If I change monthly to yearly the indication changes accordingly, but never goes away. This happens on all our POs and was noticed only today. I've searched quickly but did not find a pre-made fix. Sorry if this is already in the bug queue.

**Comment by rmehta** [comment]
@zefrenchemen Sorry for the late reply and hope this issue is fixed. You can set "Print Hide" from customize form view
