### ISSUE TITLE
Not permitted to view Import Supplier Invoice

### ISSUE THREAD

**Issue by justmejust** [frappe/erpnext#24387]
## Description of the issue
Not permitted to view Import Supplier Invoice
when trying to go to view Import Supplier Invoice list
the result is an error message (Not permitted to view Import Supplier Invoice)
## Context information (for bug reports)

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1.go to doctype list
2.select Import Supplier Invoice
3.click on go to Import Supplier Invoice list

### Expected result
open the list of Import Supplier Invoice
### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.
ubuntu 18.4 erpnext 13-9 beta

**Comment by deepeshgarg007** [comment]
@justmejust Looks like a permission issue rather than a bug
