### ISSUE TITLE
Filter on Salary structure when picking salary component - v13.0.0-beta.9 (version-13-beta)

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#24407]
![image](https://user-images.githubusercontent.com/1822868/104990437-a567bf00-5a2d-11eb-9260-9322fff8c3f7.png)

https://github.com/frappe/erpnext/pull/23519

Two problems.

- There's nowhere to setup currency for salary component. Note: This filter has been removed in the current develop branch.
- Assumes every salary component will have salary component account set.
- Related to number 2 above, when posting gl from payroll entry, the system still assumes every salary component in salary slip should have salary component accounts setup. Which is not usually the case, for statistical components, they are never to be posted to gl. The system should skip salary components with no salary component accounts, during creation of gl entries from payroll entry. Only error, should be if the resulting gl, doesn't balance.

**Comment by Ponyooooo** [comment]
on the V13 the salary component with Statistical Component is not showing. Can the system still computes the formula even though it is not encoded in the salary structure?
