### ISSUE TITLE
Allowing Negative Batch item  In POS VOUCHER In V13 beta 10

### ISSUE THREAD

**Issue by govindasamyp** [frappe/erpnext#24401]
i am using erpnext 13 beta 10

 POS  allowing For  negative batch Billing ...

               While Doing pos sales transaction , there is no issue on stock inventory...
               when selecting the batch only we are facing the problem...
              
single batch item allowed for multiple pos billing ... 
 while doing pos closing we face the problem ... not able to consolidate the voucher ...

pls do the favour to close...

![image](https://user-images.githubusercontent.com/54254549/104925120-68b3ad80-59c4-11eb-9166-488b8885b50d.png)

## Context information (for bug reports)

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1.
2.
3.

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by abimu** [comment]
we also face the same experience Hope it will be rectified.

**Comment by Jayakuttip** [comment]
me too facing the problem

**Comment by ghost** [comment]
Facing same issue as well. Can someone take a look at this as soon as possible.

Thanks,
Arun
