### ISSUE TITLE
Stock Ledger balance quantity not updating

### ISSUE THREAD

**Issue by rknroot** [frappe/erpnext#24444]
## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 13.0.0-beta.9
frappe 13.0.0-beta.9
```

## Steps to reproduce the issue

1.
2.
3.

### Observed result
![image](https://user-images.githubusercontent.com/9102676/105446538-4f4a8400-5c98-11eb-9c5a-6fd3f5c3254d.png)

### Expected result
Balance Qty must be calculated based on the previous transaction balance Qty, but it's calculating from old data.
### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by muchai** [comment]
Got a similar one.
![image](https://user-images.githubusercontent.com/1822868/108981193-8c41d600-769d-11eb-867c-c32e331be750.png)

Not sure this is fixed in the upcoming release.

**Comment by c0db1nar10** [comment]
We are facing the same issue here

**Comment by ankush** [comment]
In some cases it wasn't updating immediately (but via background jobs) but we have fixed this in last few releases.

If you're still facing this issue create a new issue with steps to reproduce. 

It's worth checking "Repost Item Valuation" record for any failures while doing backdated entries. (Filter by failed status)
