### ISSUE TITLE
[Plaid Integration] API Upgrade 2020-07-23

### ISSUE THREAD

**Issue by nameduser0** [frappe/erpnext#24442]
Plaid has announced a change to their API:
> An integration upgrade is ready
> As of July 23, 2020, the public_key is no longer used for new implementations of Link. View our [migration guide](https://plaid.com/docs/upgrade-to-link-tokens/) to upgrade to link_tokens. Once you've upgraded, head over to [API settings](https://dashboard.plaid.com/team/api) to ensure your public_key is no longer being used. You can also view our [maintenance guide](https://plaid.com/docs/maintain-legacy-integration/) to troubleshoot any public_key issues before you upgrade.

From the migration guide:
> While Plaid does not plan to discontinue support for existing public_key integrations, it is recommended that you upgrade your integration to use a link_token, as it enables enhanced capabilities, and future Plaid development and features will be based on the link_token infrastructure.

**Comment by Alchez** [comment]
@casesolved-co-uk, this is already handled (although it can be improved further for sure) in [version-12](https://github.com/frappe/erpnext/pull/23317) and [develop](https://github.com/frappe/erpnext/pull/23318).

**Comment by nameduser0** [comment]
Cool, thanks. I only checked in the issues.
Yes I have a list of improvements to the banking...

**Comment by barredterra** [comment]
Closing this as it seems to be solved / no issue.
