### ISSUE TITLE
docker usage

### ISSUE THREAD

**Issue by rioshaz** [frappe/erpnext#24443]
hi guys,  i m new ot erpnext...
i have never used docker before and i have just downloaded & installed docker desktop for windows 10 and what should i do next to install erpnext? 

I dont know how docker works and where to find frappe erpnext image image

pls help..

**Comment by barredterra** [comment]
Hi @rioshaz, GitHub is not the place to ask for help. Please check out the forum at https://discuss.erpnext.com . You can find more about frappe_docker at https://github.com/frappe/frappe_docker#getting-started .
