### ISSUE TITLE
[minor] Payment Request "+" button does not pull reference doc

### ISSUE THREAD

**Issue by trentjthomas** [frappe/erpnext#24454]
## Description of the issue
When the plus button is used to create a Payment Request the "reference doc" is not pulled and so the payment request can not be saved. This issue is only a minor bug as anyone can use the blue "Create" button to create a payment request and have it pull in the correct "reference doc" material.

## Steps to reproduce the issue
1. Open a Sales Invoice or Purchase Invoice
2. Click the "+" button next to the Payment Request, to generate a new payment request from this document
3. The reference document (the document it was generated from) was not pulled in and cannot be manually entered

### Observed result
The Payment Request does not have the reference doc filled in and so cannot be saved

### Expected result
The reference doc should have been placed into the pre-generated payment request, as properly happens from the "Create" button (See image below for how you can get around this issue.)

## Additional information
I've reported this issue on the discussion forum as well. It is only a minor issue as the payment request can still be generated.

![NoRef](https://user-images.githubusercontent.com/75241985/105572289-1a2b4980-5d0b-11eb-8d49-d610abdf929f.png)
![NoRefMes](https://user-images.githubusercontent.com/75241985/105572290-1ac3e000-5d0b-11eb-99c6-45ddef87d6e6.png)
![PaymentRequest](https://user-images.githubusercontent.com/75241985/105572291-1b5c7680-5d0b-11eb-8146-cf9f5eb68fee.png)

OS version / distribution, `ERPNext` install method, etc.
ERPNext Version 12, installed manually on CentOS 8

**Comment by deepeshgarg007** [comment]
<img width="1347" alt="image" src="https://user-images.githubusercontent.com/42651287/208245133-e9ec109a-fc2e-4779-bc01-6c075519509b.png">

No (+) button in the latest version
