### ISSUE TITLE
No way of restricting public access to Web Pages and Blog Posts

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#24452]
Hi ,

There doesn't seem to be a way to make a Web Page or Blog Post visible to only logged in users. This is a significant issue for anyone who wants to use the Website module for any kind of member-centric use case. It also might not be too hard a fix (hopefully) considering that this feature is already available for Web Forms

Please help fix this

Thanks plenty

**Comment by moe01324** [comment]
i would also be very interested in that feature

**Comment by moe01324** [comment]
I could sponsor a custom app.
