### ISSUE TITLE
Enhancement: Shipping Rule addition of VAT Tax

### ISSUE THREAD

**Issue by nameduser0** [frappe/erpnext#24476]
## Description
Some countries put VAT on everything on an Invoice including shipping charges. The current shipping rule in ERPNext v12.16.2 can only add a single line to the `Sales Taxes and Charges` underneath existing lines and there is no way to apply VAT to it

## Solution
There appear to be several ways to solve it, something like 1 being the preferred:

1. Add a tick box to the rule for `Include in Net Total for Tax Calculations`
2. Put the shipping charge at the top of the Sales Taxes and Charges list so that other lines apply to it. NOTE: may adversely affect all other instances of ERPNext
3. Add several lines to the Shipping Rule in a similar way to Sales Taxes and Charges Template so that one for VAT can be included

## Workarounds

1. Ignore Shipping Rules and create several Sales Taxes and Charges Templates that add lines for the shipping in your different scenarios and VAT
2. Ignore the Shipping Rules and add non-stock items for shipping

Related discussions:
https://discuss.erpnext.com/t/add-tax-to-shipping-costs/12684
https://discuss.erpnext.com/t/pay-vat-tax-on-shipping-charges/6803

**Comment by nameduser0** [comment]
😄

**Comment by federicocalvo** [comment]
Hi! I have the same situation, and other too in discuss, but with **Include Tax** its worst

https://discuss.frappe.io/t/items-and-shipping-include-taxes/44348/6

@ankush Should I create another issue or could you reopen this one?
