### ISSUE TITLE
Clearing account currency sets it to company currency.

### ISSUE THREAD

**Issue by barredterra** [frappe/erpnext#24477]
## Reproduce

1. Create an **Account** and set the "Currency" field to USD.
2. Make a **GL Entry** against that **Account**.
3. Open the **Account**, clear its "Currency" field and save.

## Expected behaviour

The "Currency" field cannot change if there is an existing **GL Entry**.

## Problem

The "Currency" field gets set to company currency. It is not possible to change it afterwards.

## Possible solution

Swap the if-statements here:

https://github.com/frappe/erpnext/blob/907e2990d064957b336717a77d2013ac5718c564/erpnext/accounts/doctype/account/account.py#L157-L163

---

See [discuss](https://discuss.erpnext.com/t/multi-currency-accounting-changing-currency/70588?u=rmeyer) for the original report.

**Comment by barredterra** [comment]
@rohitwaghchaure I see you fixed a similar issue in Payment Entry. Maybe you could have a look at this one as well?

**Comment by harshit-30** [comment]
Thanks @barredterra, we will update the issue at our earliest.
