### ISSUE TITLE
UAE VAT issue

### ISSUE THREAD

**Issue by mohsinalimat** [frappe/erpnext#24475]
1) When I use UAE VAT then the issue comes in POS and Promotional Scheme.

2) When I select item without tax in pos then involve created but stock is not minus.

I use version 13 beta latest.

![image_2021-01-25_23-40-25](https://user-images.githubusercontent.com/973676/105960756-ab9c1200-60a3-11eb-8227-011cb25488a4.png)
![image_2021-01-25_23-41-25](https://user-images.githubusercontent.com/973676/105960767-adfe6c00-60a3-11eb-9a89-5e70636df721.png)

**Comment by mohsinalimat** [comment]
I have checked in my instance and this code is there but facing same issue.

**Comment by mohsinalimat** [comment]
@nextchamp-saqib this is an issue.

**Comment by nextchamp-saqib** [comment]
@mohsinalimat Can you run `bench --site [your-site-name] migrate` and check?
