### ISSUE TITLE
bug: V12 Bank Reconciliation multiple attempts creates multiple page filters

### ISSUE THREAD

**Issue by nameduser0** [frappe/erpnext#24491]
## Description of the issue
Running `Reconcile this account` multiple times causes multiple filters
May be fixed by #24273 

## Steps to reproduce the issue

1. Open the Bank Reconciliation page
2. Complete the filters
3. Run `Reconcile this account`
4. Run `Reconcile this account` again

### Observed result
Bank Account, Status and Company filters are added again

### Expected result
No additional filters

## Additional information
Caused by `setup_filter_area()` from `base_list.js` being run each time
ERPNext: v12.17.0
Frappe Framework: v12.14.0

**Comment by hasnain2808** [comment]
#24273 is a complete redesign. 
It fixes this issue
