### ISSUE TITLE
Purchase invoice is not automatically linked to a project

### ISSUE THREAD

**Issue by proton-byte** [frappe/erpnext#24507]
## Description of the issue
Currently a purchase invoice is not automatically linked to a project (although the invoice was created using the create function in each case).

## Context information (for bug reports)

**Version**
ERPNext: v12.17.0 (version-12)
Frappe: v12.14.0 (version-12)

## Steps to reproduce the issue

1. Create a Sales Order
2. Create a Project
3. Create a Purchase Order
4. Create a Purchase Invoice

### Observed result

The purchase order is automatically linked to the project but **not** the purchase invoice. It's possible to set the project before posting the invoice, but this does not happen automatically.

### Expected result

The purchase invoice should be linked to the project, as the purchase order is also linked to the project. Therefore, it should also be visible on the project page.
![project-erpnext](https://user-images.githubusercontent.com/17273009/106397375-50548180-640d-11eb-9438-8da2a3baed11.png)

The purchase invoices shown were linked manually. The remaining purchase invoices generated from the purchase orders were not linked automatically.

## Additional information

ERPNext forum post: https://discuss.erpnext.com/t/project-purchase-invoice-link/70603

System information: Docker on CentOS 7.

**Comment by uepselon** [comment]
Hi, are there any updates on this one? It would be great if we can achieve the same functionality as with the Sales Invoice (as expected by the user).

**Comment by uepselon** [comment]
not stale

**Comment by uepselon** [comment]
not stale

**Comment by deepeshgarg007** [comment]
@proton-byte This should be resolved now, please check
