### ISSUE TITLE
Reserved qty error after using update Items Button on Sales Order when deleting row

### ISSUE THREAD

**Issue by sathouel** [frappe/erpnext#24519]
## Description of the issue

When i use the "Update Item" Button within a Sales Order Doc for Deleting an item line, the reserved qty of the corresponding bin is not updated.

## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 12.17.0
frappe 12.14.0
```

## Steps to reproduce the issue

1. Submit Multi line sales order
2. Use the Update Item Button to delete a line item
3. Check the reserved qty of the corresponding Bin

### Observed result

Reserved qty didn't change

### Expected result

Decrease reserved qty of the corresponding bin by the according qty

## Additional information

OS version / distribution, `ERPNext` install method, etc.

## Suggested Solution

The problem is that within the function `update_child_qty_rate` within the accounts_controller.py file the reserved qty is updated only on the parent items *after* update, we have to update it also on the deleted items

**Comment by deepeshgarg007** [comment]
@sathouel Seems to be working fine in the latest versions, closing this
