### ISSUE TITLE
payment link removed after name change in suppliert

### ISSUE THREAD

**Issue by wojosc** [frappe/erpnext#24530]
In DocType Supplier I can see existing Payment Entries...

when changing the name of a supplier...

Payment Entries in Dashboard in DocType Supplier are gone.

Looking into DocType Payment Entry we can see that 
Party Group and Party Name are not refreshed:
![image](https://user-images.githubusercontent.com/22279621/106630688-5ae15900-657c-11eb-857b-da931ce08280.png)

When refreshing with F5 only the party group will be changed. Name is not changed and needs manual input:
![image](https://user-images.githubusercontent.com/22279621/106631547-27eb9500-657d-11eb-9510-2511f592d833.png)

![image](https://user-images.githubusercontent.com/22279621/106631691-45206380-657d-11eb-800a-cb2c239271ae.png)

Payment will then show up again:
![image](https://user-images.githubusercontent.com/22279621/106631743-536e7f80-657d-11eb-83d3-34ab7b1075a0.png)

**Comment by deepeshgarg007** [comment]
@wojosc I changed the supplier name and checked and the Payment Entries in the dashboard were still linked. Obviously the supplier name in already generated entires won't change as this field is not a link field(foreign key) so that is not an expectation. Closing this issue
