### ISSUE TITLE
Sales order to Purchase order not working

### ISSUE THREAD

**Issue by centaur78** [frappe/erpnext#24533]
Hi all

Just did a bench update now.. I am getting the below error while trying to create Purchase order from the Sales order. 

It looks like JS issue "setting_dependancy" not defined..

![setting_dependancy](https://user-images.githubusercontent.com/1904802/106704572-ca4f5b00-6605-11eb-8f4d-265e794f520d.jpg)

Appreciate if someone could look into it

**Comment by ankush** [comment]
I can not reproduce this after merging https://github.com/frappe/frappe/pull/12361 locally.

If you made changes to grid.js locally make sure you have `bench watch` (should be present in Procfile) running to regenerate static assets.

**Comment by centaur78** [comment]
> I can not reproduce this after merging [frappe/frappe#12361](https://github.com/frappe/frappe/pull/12361) locally.
> 
> If you made changes to grid.js locally make sure you have `bench watch` (should be present in Procfile) running to regenerate static assets.

Hi @amenat 

I rather did a `bench clear-cache` and then `bench restart` and finally rebooted the server .. so it should have regenerated the static assets.  right ??

The weird thing is I can create from SO to Sales Invoice, material request, and others... This only happens when I try to create the SO to Purchase Order.... Since its a drop ship order... i can't use the material request route to get PO

**Comment by centaur78** [comment]
Hi @amenat 

My bad ... did the changes again and this time used `bench watch` to regenerate the static assets

issue resolved with this PR https://github.com/frappe/frappe/pull/12361
