### ISSUE TITLE
Multilingual Companies and Contacts

### ISSUE THREAD

**Issue by heikkiheer** [frappe/erpnext#2453]
This would be a nice but not urgent issue:

Default setting could be:

All Companies and Contacts have the language setting of the system.

Each Company or/and Contact could be adjusted to its preferred language.

Example:
A Swiss company runs ERPNext. They have clients in Finnland. The clients in Finnland like to have some personal touch when receiving communication, invoices etc.
To do so the Swiss company sets the Finnish Companies and Contacts in ERPNext to "Finnish". So when they receive i.e. an invoice, the invoice would be called "Lasku".

As there are already multilingual tables for the system language setting it might be possible to use them.

As I am only a halfway intelligent user I ask for forgiveness for my flowery description above.

Cheers
Heikki

**Comment by Eventect** [comment]
+1
We are an Italian company. If we sell in Italy the documents are in Italian, if we sell outside Italy the docs are in English.

**Comment by MZorzy** [comment]
@eventec have you choose another ERP due italian issue ?
