### ISSUE TITLE
SINV return auto-set Mode Of Payment uses party_account_currency, not currency

### ISSUE THREAD

**Issue by gbm001** [frappe/erpnext#24542]
## Description of the issue
PR #20543 automatically sets a Mode of Payment for POS SINV returns. Unfortunately, it does so using an amount calculated in the party_account_currency rather than the currency of the SINV, and thus in our case (where all Customers end up being identified as even if they are paying in EUR, USD etc) the amount calculated is wrong.

See my comments at the end of that PR which fix the issue by using the same calculation for total_amount_to_pay but always in the SINV currency.

## Context information (for bug reports)

We’ve just upgraded from V12.6(ish?) to V12.16 and we can no longer make POS returns on non-default currency.

Our ‘default’ currency is GBP, but we get sales in EUR (and other currencies) which are generally paid by PayPal, so we have accounts PayPal GBP, PayPal EUR etc. We create an SINV with currency EUR, mode of payment PayPal EUR, and all amounts in EUR. This works fine. Let’s suppose the sale is for €1000 which is £900 in ‘base’ currency.
When you go to create a return for the SINV, it gets an error ‘Paid amount + Write Off Amount can not be greater than Grand Total’.

The problem is that taxes_and_total.py, in calculate_outstanding_amount, is calculating a ‘total_amount_to_pay’ using the party_account_currency rather than the SINV currency, and thus calculating 900.00 instead of 1000.00. In update_paid_amount_for_return, this incorrect ‘total_amount_to_pay’ is compared to the (correct) total of payments of 1000.00, and since they don’t match all payments are deleted and (incorrect) payments are created with amount 900.00 and base amount 800-ish.

**Output of `bench version`**
```
erpnext 12.16.2
frappe 12.13.0
(custom apps and traceback from bench version command excluded)
```

## Steps to reproduce the issue

1. Create a Customer so that they will have a party account currency of a currency (can be company currency).
2. Create an SINV with that customer in a foreign currency. Submit it.
3. Create a return for that SINV, also in the foreign currency. Attempt to save it.

### Observed result

Mode of payment entry value is forced to a numeric value based on the total to pay in the party_account_currency currency, but still with the SINV currency, which is the wrong value, which raises a validation error preventing the SINV return from being saved.

### Expected result

Mode of payment entry value is forced to the total to pay in the SINV currency.

### Additional notes

By applying the fix described in my comments in the erroneous pull request, we have restored this functionality. The pull request only provides a 'helper' (which is quite useful when it doesn't break everything) so is not strictly critical code, and the existing validation prevents the 'incorrect' values it generated while broken.

The fix is to change the last few lines of calculate_outstanding_amount in taxes_and_totals.py to:
```
		if self.doc.doctype == 'Sales Invoice' and self.doc.get('is_pos') and self.doc.get('is_return'):
			grand_total = self.doc.rounded_total or self.doc.grand_total
			amount_to_pay = flt(grand_total - self.doc.total_advance
				- flt(self.doc.write_off_amount), self.doc.precision("grand_total"))
			self.update_paid_amount_for_return(amount_to_pay)
```

**Comment by deepeshgarg007** [comment]
@gbm001 This issue should be resolved now, please check
