### ISSUE TITLE
item search on website

### ISSUE THREAD

**Issue by robertbecht** [frappe/erpnext#2454]
Item search worked fine, but no longer. Do not understand how keywords are searched. Some work some dont and i can not find the logic

https://dogsloveit.frappecloud.com/product-groep/diepvries

and search for "konijn" or "eend"  (items with this are listed below) but zero returns

robert

**Comment by strixaluco** [comment]
Couldn't replicate, works fine.
https://dogsloveit.erpnext.com/product_search?search=eend
