### ISSUE TITLE
Page break functionality in PDF printout using Print Format Builder

### ISSUE THREAD

**Issue by musaddiqsajjad** [frappe/erpnext#24547]
**Is your feature request related to a problem? Please describe.**
A lot of businesses use PDF printouts to send documents. Currently there is a disconnect between PDF printing and printing using the "Print" button, for example headers and footers will only be repeated properly in PDF printout.

ERPNext uses wkhtmltopdf to convert HTML content to PDF, which leads to a host of issues making it difficult to customize without moving to fully custom HTML print formats, something that is not possible for many users.

One example is page break. There are many situations in which one would like to start some content on a new page, for example always starting Terms and Conditions (which can be quite long for many businesses) on a new page to avoid cutoffs. (p.s. wkhtmltopdf has a known issue about cutting off text between pages, see [here](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/4938), which would be resolved with a page break feature.)

It would be very beneficial to a lot of users if the print format builder supported page breaks in the PDF printout.

**Describe the solution you'd like**
Adding a way to enter page breaks after fields/sections using print format builder.

**Describe alternatives you've considered**
I have considered fully custom HTML print formats, as well as modifying standard.html (didn't go anywhere).

**Additional context**
A possible solution would be to modify frappe/templates/print_formats/standard.html and add a custom page break class. Especially this section:

```
<div class="row section-break" data-label="{{ section.label or '' | e }}">
                {%- if doc.print_line_breaks and loop.index != 1 -%}<hr>{%- endif -%}
                {%- if doc.print_section_headings and section.label and section.has_data -%}
                <h4 class='col-sm-12'>{{ _(section.label) }}</h4>
                {%- endif -%}
        {% for column in section.columns %}
                        <div class="col-xs-{{ (12 / section.columns|len)|int }} column-break">
            {% for df in column.fields %}
                {{ render_field(df, doc) }}
            {% endfor %}
                        </div>
        {% endfor %}
    </div>
```

can be extended to allow the loop to start fresh on a new page once a page break is triggered.

**Comment by Mohd200** [comment]
Greetings...

Is there any update regarding this Feature ?
