### ISSUE TITLE
Canceling and deleting a draft salary slip should reset loan repayments-v13-beta

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#24543]
To replicate:

- Create an employee loan, disburse, then run loan interest accrual.
- Create a salary slip via payroll entry, or manually. The salary slip will pick the loan.
- Now, delete the salary slip.
- On creating the salary slip again, it won't pick the load repayment.

**Comment by deepeshgarg007** [comment]
Should be fixed by https://github.com/frappe/erpnext/pull/24862
