### ISSUE TITLE
e-Invoicing for Saudi Arabia

### ISSUE THREAD

**Issue by stepsibg** [frappe/erpnext#24552]
Hi,

Saudi Arabia is implementing e-invoicing this year and deadline for the companies is December 2021.

https://gazt.gov.sa/en/RulesRegulations/Taxes/Documents/e-invoicing%20-%20FAQs.pdf

I hope ERPNext will have einvoicing feature in few months to test it.

Thanks

Junaid Hussain
Riyadh, Saudi Arabia
Steps Business Group Security and Safety.

**Comment by SeifK** [comment]
What exactly are you looking for to export from ERPNext?

**Comment by Muzzy73** [comment]
Hi @stepsibg  This is not a small task. I have gone through the initial paper released by KSA government. The KSA community/customer needs to fund this development. It is not Frappe responsibility as I see it. They would do it for a price or if any of their direct customers from KSA request for it.

There are service providers like us who can assist. If interested you can reach any of us service providers to achieve it.

**Comment by spacemudd** [comment]
@Muzzy73 Did you already integrate with GAZT?

**Comment by stepsibg** [comment]
> @Muzzy73 Did you already integrate with GAZT?

not yet, no update from ERPNext. They have many customer from Saudi Arabia they should do it for them.

**Comment by stepsibg** [comment]
We have two more documents here which are attached.
[E-invoicing_Simplified GL.pdf](https://github.com/frappe/erpnext/files/6814805/E-invoicing_Simplified.GL.pdf)
[E-invoicing Regulation EN.pdf](https://github.com/frappe/erpnext/files/6814806/E-invoicing.Regulation.EN.pdf)

**Comment by stepsibg** [comment]
Odoo has implemented it.

**Comment by stepsibg** [comment]
> Hi @stepsibg This is not a small task. I have gone through the initial paper released by KSA government. The KSA community/customer needs to fund this development. It is not Frappe responsibility as I see it. They would do it for a price or if any of their direct customers from KSA request for it.
> 
> There are service providers like us who can assist. If interested you can reach any of us service providers to achieve it.

if know what could be the cost and how soon it can be implemented and tested, we can think of it.

**Comment by Muzzy73** [comment]
Hi @stepsibg Please PM your contact information. We can take it offline.

**Comment by mfns-nawara** [comment]
@stepsibg 

Odoo hasn't implemented this till now.

**Comment by stepsibg** [comment]
> @stepsibg
> 
> Odoo hasn't implemented this till now.

May be this feature is developed by local integrator for Odoo. I have seen them advertising here in Saudi Arabia.

**Comment by stepsibg** [comment]
I have this update from ERPNext

"**Thanks for writing in. We have already added the KSA e-invoicing feature to our roadmap and after following our usual approach of thorough Development and Testing, this feature will be rolled out before December 2021**."
