### ISSUE TITLE
SRS document

### ISSUE THREAD

**Issue by ALT-KIK** [frappe/erpnext#24557]
Is the project have SRS document? 
If not I wanted to create/help to create SRS document

**Comment by SeifK** [comment]
What are the requirements of this document?

**Comment by ALT-KIK** [comment]
It defines:
-A purpose of a project
-An overall description
-Specific requirements

**Comment by SeifK** [comment]
I can setup this document for you free of charge, please contact me at contactme@seifkhaled.com

**Comment by ALT-KIK** [comment]
I wrote to you.

**Comment by ankush** [comment]
Sure. If this is for a college project, I'd suggest doing it with a module of ERPNext. E.g. CRM module would have comparatively little interactions with other modules so you'd find it easier to start with. https://docs.erpnext.com/docs/user/manual/en/CRM

Basics understanding of framework is pre-requisite for understanding rest  of project: https://frappeframework.com/docs/user/en/basics/index
