### ISSUE TITLE
Notification bell doesn't show new notifications. 

### ISSUE THREAD

**Issue by zynabMohammed** [frappe/erpnext#24574]
I keep seeing this issue in many servers, which is the Notification bell doesn't show new notifications . 
V.12

**Comment by jbtruffault** [comment]
I have the same issue here, frappe v 13.19.0

**Comment by t-moe** [comment]
Same here as well.
frappe 13.19.0

**Comment by philippmeixner** [comment]
Problem still exisits in Frappe v14.42.0 / ERPNext v14.32.1

Notifications are send to the user, and when you click the bell icon the list shows unread messages. But the bell icon does not change.
