### ISSUE TITLE
Healthcare: Automated or Easy way to Invoice Patient Encounter

### ISSUE THREAD

**Issue by mujeerhashmi** [frappe/erpnext#24582]
**Is your feature request related to a problem? Please describe.**

There are hospitals that do not take appointments but do direct consultations on daily basis for walk-in patients. We need automated or an easy way of invoicing the patient encounter. We also need a flag to differentiate if it was an outpatient encounter or an inpatient encounter.

**Comment by pjamsheer** [comment]
@mujeerhashmi System will set an Inpatient Record reference in Patient Encounter to differentiate.

**Comment by mujeerhashmi** [comment]
@pjamsheer refer to the discussion in #24572

> > However, we already have a differentiator here. If an Inpatient Record is linked to the Encounter then it is an IP encounter else an OP encounter.
> 
> 
> 
> I also had thought so but when you schedule an admission from an outpatient encounter the `Inpatient Status` and `Inpatient Record` are populated in it.
