### ISSUE TITLE
When creating a delivery note or sales invoice from a Sales order, the note or invoice stays as a draft after submitting

### ISSUE THREAD

**Issue by ThijsRa** [frappe/erpnext#24595]
## Description of the issue
When we create a sales order in ERPnext, we want to process the order by creating a sales invoice or a delivery note. But when we create an invoice or a delivery note, the status won't move from draft after submitting.

## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 13.0.0-beta.11
frappe 13.0.0-beta.10
woocommerceconnector 1.6.0
```

## Steps to reproduce the issue

1. Create a sales order
2. Click on the '+'-icon next to sales invoice or delivery note
3. Fill in the information that you need to process your invoice
4. Click on submit. 
5. ERPnext will say that your request has been submitted successfully
6. Refresh the page
7. You'll see that the status is still "draft" 

### Observed result
Sales invoice or delivery note stays a draft

### Expected result
The status must be paid or unpaid.

### Stacktrace / full error message

```
No stacktraces or errors are found
```

## Additional information

CentOS 7
ERPnext is installed by bench

**Comment by ThijsRa** [comment]
I did some extra testing. Seems that the problem can be found in the external woocommercesync application. When it's enabled I've got the problems as described. When I disable the sync, I can save sales invoices again :).

**Comment by ankush** [comment]
I can confirm on a vanilla install that status for both get committed to DB and stay there after refresh too.

If an external app is intercepting using hooks, we can't do much about it.
