### ISSUE TITLE
Conversion rates on item prices brake when defining supplier/customer

### ISSUE THREAD

**Issue by wojosc** [frappe/erpnext#24590]
We can create Item wise Item Price witch will be converted right when using different UOMs in transactions (Quotation, Sales Order etc.). If no supplier/customer is set in Item Price the conversion set in the table inside Item works as expected.

As soon as we define supplier/customer in Item Price, the conversion in transactions breaks. If we have a further Item Price in which no supplier/customer is set the transaction will use this to calculate the conversion (piece, box, pallet) which is not the right conversion to the base price.
![image](https://user-images.githubusercontent.com/22279621/107367629-d6dd2300-6adf-11eb-9f18-7f7d0c1c1ca9.png)

**Comment by deepeshgarg007** [comment]
@wojosc It will be helpful to investigate this if you mention some values with examples and steps to replicate, haven't seen this happen recently hence closing this issue for now.

**Comment by wojosc** [comment]
@frederictobien please check.
