### ISSUE TITLE
Salary slip picks latest Salary Structure Assignment even if the salary structure is cancelled.-v13 beta 11

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#24601]
TO replicate

Create a salary structure assignment, say on date 1-Jan-2021, and submit it

Now, create another salary structure assignment, on 5-Jan-2021, and cancel it

The salary slip will pick the base on the second salary structure assignment created on 5-Jan-2021

**Comment by onlinebizsoft** [comment]
@muchai the same issue in v12
