### ISSUE TITLE
In Multicurrency-Payment Amount, in Payment Schedule, in Sales Invoice shows wrong currency.-v13 beta 11

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#24619]
![image](https://user-images.githubusercontent.com/1822868/107743067-44c45d00-6d21-11eb-9e30-f3735b7ccf6f.png)

**Comment by zuron7** [comment]
Same bug here. Hosted on Frappe Cloud. V13-beta12

**Comment by Codeaview** [comment]
Same bug too. ERPNext: v13.0.0-beta.14 (version-13-beta) Frappe Framework: v13.0.0-beta.12 (version-13-beta).
Has it been fixed in new versions?

**Comment by zuron7** [comment]
Yes. I am not facing this issue anymore in the latest stable version as of 9th June, 2022.

**Comment by Codeaview** [comment]
Ok, thank you so much! I will upgrade my ERPNext. @muchai, the issue can be closed.
