### ISSUE TITLE
Taking System Time instead of Server Time

### ISSUE THREAD

**Issue by kalepranali044** [frappe/erpnext#24624]
While creating an attendance we had added custom script for 2 button that is Punch in and Punch out. So if the user forget to Punch in or Punch out. The next what they do is change the system time and mark there attendance. We had use the below syntax for date and time

cur_frm.set_value("in_time",frappe.datetime.get_today());
		
So this is taking the system date instead of server. 
Please find he attaches ss. Todays date is 13/02/2020 but it is giving us the system date which is changed to 11/02/2020
![attendance ss](https://user-images.githubusercontent.com/78998751/107844833-e7054300-6dfc-11eb-88e1-cdffae466db7.png)

**Comment by ankush** [comment]
This is not a bug per se. Client side customization using javascript use moment.js hence client system's time.   

You'll have to write server script using Python to get server time. Checkout `frappe.utils` for datetime utility functions. https://frappeframework.com/docs/user/en/desk/scripting/server-script 

If you need more help, you may discuss on community forum https://discuss.erpnext.com
