### ISSUE TITLE
Change in raw material value not reflected in value of produced Item

### ISSUE THREAD

**Issue by Talleyrand333** [frappe/erpnext#24623]
If the value of a raw material changes after the document is created but before it is submitted, ERPNext calculates the new value of the raw material but does not transmit this to the product, instead the difference is posted to the stock adjustment account.

**Steps to Replicate**

1. Set up a simple BOM for Manufacture

2. Create a work order from the newly created BOM, Skip material transfer to warehouse

3. Create  a stock entry with entry type Manufacture from the work order, there should be adequate stock to handle the work order already at the warehouse.
Save the document in draft.

4. Receive a new batch of one of the raw materials stated in the BOM, the aim of this is to increase the valuation rate of that raw material in stock.

5. Submit the stock entry that was created from the work order.

6. Notice that ERPNext calculates the new value of the raw material but does not calculate the new value of the finished item. Instead, this difference is posted to the stock adjustment account. 

It is noteworthy  that all subsequent stock entries created from the same work order use the updated item values for incoming and outgoing

**Comment by ankush** [comment]
So if I understood this right:

1. Manufacture stock entry created in the draft. 
2. Stock entry made for increasing valuation of one of the items in the RM of manufacture entry
3. Now submitting an entry in step 1 doesn't update FG's valuation but posts as difference?

Correct?

**Comment by Talleyrand333** [comment]
Yes correct @ankush , ERPNext v12.7.1 Frappe v12.5.1

**Comment by Nihantra-Patel** [comment]
Hi @Talleyrand333,

Make sure to update your software to the latest versions 14 or 15. This will ensure that everything runs smoothly with the new changes.

Thank You!
