### ISSUE TITLE
Error "pymysql.err.InternalError: (1054, "Unknown column 'export_type' in 'field list'")"

### ISSUE THREAD

**Issue by kartikeymahajan** [frappe/erpnext#24626]
I will try to make new purchase invoice but when I tried to save that invoice they gives error **"pymysql.err.InternalError: (1054, "Unknown column 'export_type' in 'field list'")"** 
Screenshot of this problem attached below.. 
Please give me a proper solution on this problem..
![Screenshot (2)](https://user-images.githubusercontent.com/79058561/107887436-20889c00-6f2c-11eb-9dfe-43cd54fd620f.png)

**Comment by collabosys** [comment]
Hi, I am facing the same issue in V12.
![image](https://user-images.githubusercontent.com/74523457/107937194-9aab3600-6fa9-11eb-8ac3-c8ee691b8101.png)

**Comment by collabosys** [comment]
I am also getting similar issue while raising a Sales Invoice, probably setup issue?

![image](https://user-images.githubusercontent.com/74523457/107944408-101c0400-6fb4-11eb-9a09-059e29cc0524.png)

**Comment by collabosys** [comment]
Hi @kartikeymahajan , did you resolved this issue? if yes, how?

**Comment by kartikeymahajan** [comment]
@collabosys  Not yet

**Comment by ankush** [comment]
Share version details and stack trace as per this template:

https://github.com/frappe/erpnext/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md

You can find stacktrace in browser console or from terminal where bench is running.

**Comment by collabosys** [comment]
Hi @ankush , please let me know the procedure to generate the stack trace, i am new to ERPNext environment.

**Comment by ankush** [comment]
@collabosys  When you get the error as shown in the screenshot in your posts, an error trace is generated which can be found in bench terminal. (If you are running ERPNext in development mode using `bench start`)

OR from browser:
You can also find it in browser console. IF you're using Chrome that's F12 -> Go to Console Tab and you'll find an error trace. Guide for firefox: https://developer.mozilla.org/en-US/docs/Tools/Browser_Console 

Here's is how it looks:
![Screenshot 2021-02-17 at 12 45 17 PM](https://user-images.githubusercontent.com/9079960/108169030-33fb5900-711e-11eb-866e-129860b73a8b.png)

**Comment by collabosys** [comment]
Installed Apps
ERPNext: v12.16.2 (version-12)

Frappe Framework: v12.13.0 (version-12)
Console log is attached.
[localhost-1613547526706.log](https://github.com/frappe/erpnext/files/5993991/localhost-1613547526706.log)

**Comment by collabosys** [comment]
@ankush Hope the attached details will help you

**Comment by kartikeymahajan** [comment]
Hello @ankush  
These is my ERP's version and console details, Please check

**Version :**
ERPNext: v12.17.0 (version-12)
Frappe Framework: v12.14.0 (version-12)

**Console Details :**
Console log in text document format is attached below.
[localhost-1613569011625.log](https://github.com/frappe/erpnext/files/5996007/localhost-1613569011625.log)

**Comment by ankush** [comment]
"export type" is customisation related to Indian GST. If you selected India during setup process it would've setup these fields for you. This is how it looks like on purchase invoice form:
![Screenshot 2021-02-17 at 8 21 59 PM](https://user-images.githubusercontent.com/9079960/108221488-d981ed00-715d-11eb-9159-1e0cc3200502.png)


You can confirm existence of this field searching for this custom field in "Custom Fields list" by going to <yoursiteURL>/desk#Form/Custom%20Field/Purchase%20Invoice-export_type 

Did you face any errors during setup process? If not this is very hard to replicate. 

 I'd suggest reinstalling or doing `bench migrate`.

**Comment by collabosys** [comment]
Hi @ankush Thanks for your pointer. I could resolve the issue by defining Supplier Address.

**Comment by kartikeymahajan** [comment]
Hello @ankush 

The problem was resolved, Thank you so much for giving us proper solution of that error.

Thank you
