### ISSUE TITLE
Process Statement of Account

### ISSUE THREAD

**Issue by DonovanJH** [frappe/erpnext#24655]
Hi I am have used the Process Statement of Account for V13 and there are 2 issues with this bulk statement created.
1. The Statement prints all cancelled transactions which is not ideal or should at least be an check option.
2. The statement printing preferences does not include the "with letter head" option as with other documents so unlike docs this looks rather unprofessional.

Please could you sort out these issues. These are both existing features/functions elsewhere in ERPNext so it should be pretty easy to fix.
Thanks

**Comment by deepeshgarg007** [comment]
@DonovanJH Both issues should be resolved now. Please check
