### ISSUE TITLE
Issue with Journal Entry and Loan Payment Reference

### ISSUE THREAD

**Issue by MrEnjaz** [frappe/erpnext#24659]
Hi All,
I have an issue with repaying a loan with journal entry manually as when I repay the loan the paid amount still zero but when I repay using the **Create Repayment Entry** button it works well. After investigation, I found that there is a hidden field called **Paid Loan** that renders data as JSON when I use the button and I can't fill it manually in the journal entry and I don't know does it effect on the repayment of the loan or not? This issue appeared only on version 12.16 but it was working in version 11. 

**Steps I Used For Repaying A Loan Using Journal Entry :**
1. I have created a loan 
2. I have created a Disbursement Entry for the loan
3. I have created a Repayment Entry for the loan from the journal entry by : 
          1. Selecting "Loan" in the reference type
          2. writing the loan name in the reference name
4. After submitting the journal entry, I have checked the loan and the paid amount stills zero
5. I have checked The Loan Repayment Report and the paid amount also stills zero

**Comment by chrisdent** [comment]
#28733
