### ISSUE TITLE
Stock Reconciliation / Error / Warehouse not found in the system

### ISSUE THREAD

**Issue by rjmb** [frappe/erpnext#2465]
I'm testing ERPNext using...
* ERPNext: v4.12.0
* Frappe Framework: v4.6.1
* Shopping Cart: v0.5.0

Installed from Frappe Brench

----

The system do not save the Stock Reconciliation Data
I get the message mentioned in the title "Warehouse not found in the system"

The Warehouse and Items are OK

Atach some images

![stockreconciliation](https://cloud.githubusercontent.com/assets/10089560/5319276/ec6482aa-7c79-11e4-9b19-5ef916aabee7.png)

![warehouselist](https://cloud.githubusercontent.com/assets/10089560/5319252/ad7a22d4-7c79-11e4-98dd-a76bf58e730c.png)

![chartaccount](https://cloud.githubusercontent.com/assets/10089560/5319251/ad707112-7c79-11e4-8570-b844101c1a37.png)

**Comment by nabinhait** [comment]
Is this issue still exists? Must be some freak issue, could not replicate it.
