### ISSUE TITLE
some accounts doesnot appear when i change language 

### ISSUE THREAD

**Issue by citybirdman** [frappe/erpnext#24650]
when i make a payment entry with account language "ar" and party type "employee", then when i search for some accounts in the field "Account Paid To" these accounts doesn't appear unless i change the language to english (united states)

**Comment by ankush** [comment]
Please share version details and other info as per bug report template. https://github.com/frappe/erpnext/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by ankush** [comment]
I can not reproduce. 

Reopen with additional info as per my previous comment.
