### ISSUE TITLE
Accounting effect of delivery note and sale invoice.

### ISSUE THREAD

**Issue by irfanzck** [frappe/erpnext#24656]
When delivery note and sales invoice are recorded in two different accounting period, the cost of sale is recorded in one period and the revenue is recorded in other. 

Due to the above irregularity, the Gross Profit report (GP) will also be inconsistent with GP as per the profit and loss statement.

This need to be fixed with a control account in place so that when recording a stand alone delivery note or sales invoice, the revenue or cost of sales should not be booked.

**Comment by deepeshgarg007** [comment]
@irfanzck This looks like a feature request rather than a bug, please elaborate more on this feature and then open a new issue.
