### ISSUE TITLE
Generation of Material Requests in Make-to-Stock scenario

### ISSUE THREAD

**Issue by norulz** [frappe/erpnext#2467]
The Production Planning Tool does not currently support generation of a Material Request based solely on a Production Order created in the tool. The "Create Material Request" button is disabled (unless a Sales order exits i.e. Make-to-Order).

On the same note, MTS (make-to-stock) might also be supported by a button in a Production Order providing creation of a Material Request. Even more so the ability to pull Production Order data into a manually created Material Request (by a button in the request form) would be a great function.

Thanks,
David

**Comment by umairsy** [comment]
For Make to Stock item, you can update reorder level in the Item master. Based on the Reorder level and qty, Material Request will be auto-created.
