### ISSUE TITLE
Duplicate Additional Salary when saving Salary Slip

### ISSUE THREAD

**Issue by aakvatech** [frappe/erpnext#24684]
## Description of the issue
Duplicate additional salaries on saving the salary slip where additional salary is without "Overwrite Salary Structure Amount"

## Context information (for bug reports)

**Output of `bench version`**
```
ERPNext: v13.0.0-beta.11 (HEAD)
Frappe Framework: v13.0.0-beta.10 (HEAD)
```

## Steps to reproduce the issue

1. Create Holiday List for the current period
2. Assign default holiday list to the company
3. Create Salary Structure 
4. Create Employee
5. Assign a salary structure to the employee
6. Create Salary component "Incentive" as earnings
7. Create additional salary "Incentive" and uncheck "Overwrite Salary Structure Amount"
8. Create a salary slip for the employee and save it

### Observed result
In earnings, you will see 2 records for Incentive

Incentive		TZS 600.00
Incentive		TZS 600.00

### Expected result
Only 1 record should appear

Incentive		TZS 600.00

**Comment by aakvatech** [comment]
```
	def add_additional_salary_components(self, component_type):
		salary_components_details, additional_salary_details = get_additional_salary_component(self.employee,
			self.start_date, self.end_date, component_type)
		if salary_components_details and additional_salary_details:
			for additional_salary in additional_salary_details:
				additional_salary =frappe._dict(additional_salary)
				# exit if additional_salary.name already exists in self.earnings/deductions
				existing_additional_salary_record_found = 0
				for d in self.get(component_type):
					if d.additional_salary == additional_salary.name:
						existing_additional_salary_record_found = 1
						break
				if existing_additional_salary_record_found:
					continue
				amount = additional_salary.amount
				overwrite = additional_salary.overwrite
				self.update_component_row(frappe._dict(salary_components_details[additional_salary.component]), amount,
					component_type, overwrite=overwrite, additional_salary=additional_salary.name)
```

Above core change in salary_slip.py would fix the issue. However it would be have a more optimal solution as well.

**Comment by aakvatech** [comment]
@michellealva and @AfshanKhan would you be able to take a look at it and see it can be put into version-13-beta ASAP.

**Comment by michellealva** [comment]
@aakvatech could not replicate this. Could you check what is the value of incentive in the salary structure? Is it 600? if that's the case, then since "Overwrite Salary Structure Amount" is unchecked, 2 records will be created, one for the existing salary structure and the other via additional salary

**Comment by aakvatech** [comment]
@michellealva there no record incentive in the earning section salary structure just direct entry into additional salary as incentives are different every month and sometimes there are possibly multiple incentives in a month. If we put multiple incentives then it also doubles the number of records e.g 2 incentives in a month then 4 records in salary slip 2 for each incentive

**Comment by sagarvora** [comment]
@michellealva Please see the GIF in [this PR](https://github.com/frappe/erpnext/pull/24785). A new row is being added every time the Salary Slip gets re-saved.
