### ISSUE TITLE
Intercompany Transactions

### ISSUE THREAD

**Issue by SAJOIJOM** [frappe/erpnext#2469]
If there are intercompany transactions, Currently, there is no option available to post it directly.
It would be great if intercompany- billings, journal vouchers, stock transfers can be addressed.
For each company created, a ledger with that company name has to created in other companies. If in the company A, Sales is being to booked to B, there should be another entry automatically passed as purchase in B from A.

Please advise if it can be done with scripts.

**Comment by SonaliBudhrani** [comment]
+1
