### ISSUE TITLE
Post Dated Cheques

### ISSUE THREAD

**Issue by SAJOIJOM** [frappe/erpnext#2470]
Currently there is no option to enter Post dated entries.
There should be a voucher available as Post dated entries and should not affect the financials.
But this should be shown in GL and should have an option in receivables report to effect or not.

If there is any alternative solution, please suggest.

**Comment by SAJOIJOM** [comment]
Hi, On PDC concept, as we are having multiple bank accounts, we post the PDCs to a PDC ledger. at the time of realizing the cheque, we post it to the concerned bank account. How should we encounted such a scenario?

**Comment by ai-erp** [comment]
hi @SAJOIJOM , i have created a feature suggestion for managing PDCs in below post:
https://github.com/frappe/erpnext/issues/6946

**Comment by Arundhatii** [comment]
Please follow #6946 for PDC Feature development. Closing this for now. 
--
