### ISSUE TITLE
Incorrect Encashable leave count

### ISSUE THREAD

**Issue by komalvadavale-09** [frappe/erpnext#24706]
Description- 
 
1. We have allocated privilege leaves to employee for financial year april 2020 to march 2021

![Screenshot (943)](https://user-images.githubusercontent.com/64304459/108803627-2718b280-75c1-11eb-9414-14bb260dbd9c.png)

2. Employee has used 2.5 leaves out of that

![Screenshot (950)](https://user-images.githubusercontent.com/64304459/108806312-5df1c700-75c7-11eb-92dc-67856a4be87d.png)

3. now when We are trying to encash the privilege leaves, it is showing available balance = 4, ideally it should be 1.5 & employee should get encashment for 1.5 leaves
![Screenshot (949)](https://user-images.githubusercontent.com/64304459/108806336-6e09a680-75c7-11eb-9ec6-2fc4fdf621fb.png)

4. If we submit the record employee is getting encashment for 4 leaves &  leave count in employee dashboard is -2.5

## Steps to reproduce the issue

1. Allocate leaves-(category leave should be encashable)
2. Take some leaves so leave balance will not be equal to allocated leaves
3. now try to create leave encashment for balanced leaves

### Observed result
System is providing encashment for all the allocated leaves, even if employee has used some leaves & does not have that much leave balance
### Expected result
Leave encashmenyt should be done as per balance leaves, not for allocated leaves`

## Additional information
Leave ledger entry:

Type                             To date     entry | From date | To date | Entry
-- | -- | -- | --
Allocated leaves | 01-01-21 | 31-01-21 | 10
Leave application | 10-01-21 | 10-01-21 | -1
Leave application | 26-01-21 | 27-01-21 | -2
 
Existing: | From date | To date | Entry
  | 01-01-21 | 31-01-21 | 7
  | 05-01-21 | 20-01-21 | -1
 
MR | From date | To date | Entry
  | 01-01-21 | 31-01-21 | 10
  | 05-01-21 | 20-01-21 | 0
 
Expected | From date | To date | Entry
  | 01-01-21 | 31-01-21 | 7
  | 05-01-21 | 20-01-21 | 9

**Comment by kkaranbhanushali** [comment]
Facing the same issue.
:(
