### ISSUE TITLE
Feature Request - Safari Push notifications

### ISSUE THREAD

**Issue by DrTrills** [frappe/erpnext#2471]
As more and more organizations use Macs, I think it would be pretty cool to have ERPNext notifications come through the mac notification system. Things like new support tickets, new job candidate etc. will be able to popup when not in ERPNext which I believe will make people more productive as they will see more notifications and more of what is happening in their organization at a quicker rate.

Please see more docu here: https://developer.apple.com/notifications/safari-push-notifications/

Thanks for such a great tool!

Best,

**Comment by gmplab** [comment]
erpnext already have notifications for browser now.
it don't need to just hack for mac.
close it.
