### ISSUE TITLE
Cannot cancel payment entry.

### ISSUE THREAD

**Issue by rtdany10** [frappe/erpnext#24712]
## Description of the issue
Payment entry cannot be cancelled on ERPNext v12.18.0

![image](https://user-images.githubusercontent.com/52111700/108827947-38c37f80-75ec-11eb-9a0f-5a742bf064d0.png)

**Comment by ankush** [comment]
Closed by #24617

**Comment by miteshnandu** [comment]
What we have to do to solve this issue bug. Kindly guide

**Comment by ankush** [comment]
If you want to fix it immediately then cherry-pick the fix commit into your instance. If you're on v12 pick it from `version-12-hotfix`, on v13 you can pick it from `develop` branch. Tutorial: https://www.atlassian.com/git/tutorials/cherry-pick 

Commits are linked in the PR I linked above.

**Comment by miteshnandu** [comment]
I am on frappe cloud, so i am unable to cherry pick the fix, waht to do.

**Comment by miteshnandu** [comment]
Please guide how to solve this problem.

**Comment by ankush** [comment]
It should be available with next release.

**Comment by rtdany10** [comment]
Even I am on FC and my accounts need to be cleared before 31st for GST filing. I can't even cancel Journal Entries :/
Hope the update arrives quick.
