### ISSUE TITLE
Bank Reconciliation Tool - Payment Document (Payment Entries), Payment Entry (Payment Entries) are mandatory fields 

### ISSUE THREAD

**Issue by xickomesquita** [frappe/erpnext#24720]
## Description of the issue

I'm testing in develop branch the bank reconciliation tool, and I'm getting this message:

![image](https://user-images.githubusercontent.com/38265198/108898726-53025b00-75f6-11eb-8236-1ca380d2cfd3.png)

I've used the template, and inserted all the infos to all the fields.

## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 13.x.x-develop
frappe 13.x.x-develop

```

## Steps to reproduce the issue

1. Follow the documentation: https://github.com/frappe/erpnext/pull/24273

**Comment by xickomesquita** [comment]
Somehow the headers are messed up...

**Comment by ankush** [comment]
is the issue resolved? Asking because you closed it.

**Comment by hasnain2808** [comment]
https://github.com/frappe/frappe/pull/12363 should fix this

**Comment by hasnain2808** [comment]
@xickomesquita,

These fields are not marked as mandatory, so ideally you should not see this error.

Since you are facing it can you please give some more info such as

1. The file you are trying to upload
2. The bank transaction doctype  
3. A gif would also be really really helpful

Regards

**Comment by xickomesquita** [comment]
> is the issue resolved? Asking because you closed it.

Hi ankush... Yes... as I said, somehow the headers are messed up. I just configure it again, and its all good.

**Comment by xickomesquita** [comment]
> @xickomesquita,
> 
> These fields are not marked as mandatory, so ideally you should not see this error.
> 
> Since you are facing it can you please give some more info such as
> 
> 1. The file you are trying to upload
> 2. The bank transaction doctype
> 3. A gif would also be really really helpful
> 
> Regards

Hi hasnain, all good?

So, the issue happend because these headers are not configured correctly:

![image](https://user-images.githubusercontent.com/38265198/109600645-2bcaf280-7afc-11eb-8834-d388c1ce900f.png)

After the link, is everything ok. 

Tks,
