### ISSUE TITLE
Disables Tax templates are also applied

### ISSUE THREAD

**Issue by shree0990** [frappe/erpnext#24737]
-We have disabled a sales tax template, but still on change of tax category in sales order or in invoice, the disabled sales tax template is selected and applied.
-We also checked issue... issue is in our customer master. when we set tax category in customer master, and after that going in sales invoice or sales order and when select that particular customer at there disabled taxes and templates applied  of particular tax category.

**Comment by deepeshgarg007** [comment]
@shree0990 This should be resolved in the latest version, please check and reopen if the issue still persists
