### ISSUE TITLE
Sales Tax Template Not Carrying Sales Order to Sales Invoice [ Erp next 13 beta 12]

### ISSUE THREAD

**Issue by govindasamyp** [frappe/erpnext#24747]
sales tax template And other Charges, are not carry over Sales order  To Sales Invoice .

## Context information (for bug reports)

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1.
2.
3.

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by mohsinalimat** [comment]
I have face same issue in 13.1.0

**Comment by mohsinalimat** [comment]
@govindasamyp Issue fix?

**Comment by deepeshgarg007** [comment]
@govindasamyp No taxes are carried forward from order to invoices just the items, the taxes are supposed to be re-applied as per config you have setup
