### ISSUE TITLE
v11 to v12 on migrate issue frappe.exceptions.DoesNotExistError: DocType E Invoice Settings not found

### ISSUE THREAD

**Issue by wikiodisha1** [frappe/erpnext#24757]
v11 to v12 on migrate issue
frappe.exceptions.DoesNotExistError: DocType E Invoice Settings not found

**Comment by shantanoo** [comment]
Similar to #24218 issue? Solution in the issue didn't work. Had hit the similar issue while upgrading to latest version 12.

**Comment by neelbhanushali** [comment]
Similar to #24968 

@shantanoo check this issue. i have added a work around for it.

**Comment by shantanoo** [comment]
Thanks @neelbhanushali
