### ISSUE TITLE
Auto populate item in new Batch from Purchase Receipt

### ISSUE THREAD

**Issue by Priyanka-IAS** [frappe/erpnext#2476]
When I create a New Batch No for each item while making a Purchase Receipt, it should ideally auto-populate the item details from the PR. Instead, we need to re-select the item again in the New Batch page.

This auto population will help save a lot of time and make it easier to make the Batch Nos.

**Comment by umairsy** [comment]
Closing as inactive from long time now.

**Comment by satishmalkar94** [comment]
can any one solve this issue ?
