### ISSUE TITLE
Disable Rounded Total Error / Is not working at Customer Portal Invoice

### ISSUE THREAD

**Issue by rjmb** [frappe/erpnext#2477]
The Global Setting **Disable Rounded Total** is selected.

However the Invoice at the Customer Portal is still rounding the total

![error-disableroundedincustomerportal](https://cloud.githubusercontent.com/assets/10089560/5359895/f88e08e6-7f92-11e4-90e5-9415deedeb42.png)

**Comment by gmplab** [comment]
current version don't have this issue.
close it.
