### ISSUE TITLE
Sales cancellation improvements

### ISSUE THREAD

**Issue by nameduser0** [frappe/erpnext#24777]
## Problem
A website order will create 3 documents:

- Quotation
- Sales Order
- Payment Request

If there is a problem or mistake and you need to cancel and delete these, you need to do each document separately by first Cancelling, then Deleting the document in reverse order due to document linking. This is extremely time-consuming and clunky

## Solution
It should be possible to cancel and/or delete all linked documents in one action from any document, keeping the database tidy

**Comment by dj12djdjs** [comment]
This would be convenient even on all doctypes. It would be good to have a confirmation dialog with nested documents that will be canceled.
