### ISSUE TITLE
Subscription Plan currency not respected when generating Sales invoices

### ISSUE THREAD

**Issue by muhaym** [frappe/erpnext#24781]
## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 12.17.0
frappe 12.14.0
```

## Steps to reproduce the issue

1. Create a subscription plan with a different currency than the default currency.
![image](https://user-images.githubusercontent.com/10905479/109609359-39f72e00-7b51-11eb-8917-596bbe475d01.png)

2. Subscription plan list shows the price with the wrong currency
![image](https://user-images.githubusercontent.com/10905479/109609469-5f843780-7b51-11eb-80fe-93d0a3a981b6.png)
Note that it shows Indian Rupee (Default company currency)

3. When a subscription automatic sales invoice is generated, it uses the wrong currency again (default currency) instead of the currency selected in the first step.
![image](https://user-images.githubusercontent.com/10905479/109609613-93f7f380-7b51-11eb-8292-f0de3e83499d.png)

### Observed result
Subscription Plan given currency is not being used in Subscription plan listing and automatically generated invoices in Subscriptions.
### Expected result
Currency during listing Subscription plan and automatically generated invoices should have the selected currency in the Subscription plan.

**Comment by muhaym** [comment]
@deepeshgarg007 Since you have worked on a subscription, I assume you can check this and validate whether this is actually an issue or a configuration issue. 

Also, auto-generated invoices are by default in a submitted state, which blocks our ability to edit invoices before sending them to customers.

**Comment by barredterra** [comment]
> Also, auto-generated invoices are by default in a submitted state, which blocks our ability to edit invoices before sending them to customers.

#25394

**Comment by barredterra** [comment]
Maybe this is related: #28916
