### ISSUE TITLE
Subscriptions

### ISSUE THREAD

**Issue by DonovanJH** [frappe/erpnext#24788]
This subscription feature worked fairly well for a long time but now its creating incorrect invoices with incorrect values and i cannot even delete these incorrect invoices.

![image](https://user-images.githubusercontent.com/79196266/109647634-34eeaa80-7b62-11eb-8c01-071c97b39c52.png)

The Price List has an amount of 1,250 but when the invoice is created, it shows a rate and the rate is shown as the amount on the invoice. Not sure why this changed but its incorrect. Also I can't delete or even cancel the invoice.

Please rectify.

**Comment by barredterra** [comment]
@DonovanJH do you have "Prorate" enabled in **Subscription Settings**? This was causing issues for me because the calculation was not correct and the resulting price seemed rather random.
