### ISSUE TITLE
AttributeError: ‘StockEntryDetail

### ISSUE THREAD

**Issue by abod2data** [frappe/erpnext#24791]
i faced this truple through migrate my backup in latest update v13. today

-------------------------------------------------------

File “/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py”, line 91, in execute_patch
frappe.get_attr(patchmodule.split()[0] + “.execute”)()
File “/home/frappe/frappe-bench/apps/erpnext/erpnext/patches/v13_0/item_reposting_for_incorrect_sl_and_gl.py”, li
ne 36, in execute
}, allow_negative_stock=True)
File “/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/stock_ledger.py”, line 146, in init
self.build()
File “/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/stock_ledger.py”, line 213, in build
self.process_sle_against_current_timestamp()
File “/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/stock_ledger.py”, line 237, in process_sle_against_cur
rent_timestamp
self.process_sle(sle)
File “/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/stock_ledger.py”, line 339, in process_sle
self.update_outgoing_rate_on_transaction(sle)
File “/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/stock_ledger.py”, line 408, in update_outgoing_rate_on
transaction
self.update_rate_on_stock_entry(sle, outgoing_rate)
File “/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/stock_ledger.py”, line 419, in update_rate_on_stock_en
try
stock_entry.calculate_rate_and_amount(reset_outgoing_rate=False, raise_error_if_no_rate=False)
File “/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py”, line 433, in calc
ulate_rate_and_amount
self.set_basic_rate(reset_outgoing_rate, raise_error_if_no_rate)
File “/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py”, line 445, in set
basic_rate
finished_item_qty = sum([d.transfer_qty for d in self.items if d.is_finished_item])
File “/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/doctype/stock_entry/stock_entry.py”, line 445, in
finished_item_qty = sum([d.transfer_qty for d in self.items if d.is_finished_item])
AttributeError: ‘StockEntryDetail’ object has no attribute ‘is_finished_item’

## Context information (for bug reports)

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1.
2.
3.

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `Frappe` install method, etc.

**Comment by ankush** [comment]
https://github.com/frappe/erpnext/commit/bd10d7c02841cd8d0ab0fcd862a2a60ebe8b9aa3
