### ISSUE TITLE
UOM No Number changing when typing serials

### ISSUE THREAD

**Issue by wojosc** [frappe/erpnext#24803]
When creating a Purchase Receipt from Purchase Order the no of items is changed when trying to enter serial number:
![serial_bug](https://user-images.githubusercontent.com/22279621/109990545-c8aeab00-7d09-11eb-8ea5-f995c9fb84e6.gif)

Work around: create mutliple Purchase Receipts

**Comment by nabinhait** [comment]
This has been fixed in v15
