### ISSUE TITLE
Manufacturing Demo not functional

### ISSUE THREAD

**Issue by mwrsa** [frappe/erpnext#24813]
In the manufacturing demo you cannot do much because the current fiscal year is 2017 and trying to end it causes an error. Could you please look into that? Thank you.

**Comment by ankush** [comment]
Working as expected now.
![Screenshot 2021-09-20 at 8 48 58 PM](https://user-images.githubusercontent.com/9079960/134027926-b26c7ff9-fc38-463b-bb26-4ac1c7e94d4a.png)
