### ISSUE TITLE
Barcode reader not work efficiently in Purchase Receipt Serial No (v12.18.0)

### ISSUE THREAD

**Issue by dufani1** [frappe/erpnext#24822]
Hi,
Barcode reader not work efficiently in Purchase Receipt Serial No, we have to press enter for each new serial no.
Not taking serial no. in each raw.
Please check attached video..

https://user-images.githubusercontent.com/23026263/110466961-15fe9400-80df-11eb-9423-013fffca815e.mp4

**Comment by TurkerTunali** [comment]
Barcode readers has some configurations such that "prefix" and "suffix". You can configure it by reading some custom barcodes. You need to set suffix as somethink like enter key (CH13). Just check the reader's documantation.

**Comment by dufani1** [comment]
@TurkerTunali Thanks and think this is a bug, please check attached video for more info.

https://user-images.githubusercontent.com/23026263/111029652-79056900-8406-11eb-9dff-9293264c8881.mp4

**Comment by HaniTetouha** [comment]
same issue with me on
ERPNext: v12.19.0 (version-12)
Frappe Framework: v12.16.0 (version-12)

**Comment by ankush** [comment]
Two solutions:
1. Configure your barcode reader to send carriage return like @TurkerTunali 
2. Use "scan barcode" field instead of adding serial no directly.
