### ISSUE TITLE
Book discounts separately in ERPNext

### ISSUE THREAD

**Issue by Ahmad-Najjar** [frappe/erpnext#24843]
- ERPNext currently is not considering the discount value in the account's booking, we need a function to cover this part the below are a suggestion to implement it:

![image](https://user-images.githubusercontent.com/68277691/110669598-88ee3480-81dd-11eb-88e2-f3fe8c95ad05.png)

- the discount allowed and received are available in the company setting.
- once we record the discount via items, the total of this discount will be booked in the allowed discount, and the total amount of the revenue will be fixed and it will do the transaction for the discount on expanses.
![image](https://user-images.githubusercontent.com/68277691/110670836-dfa83e00-81de-11eb-9809-43ab7d7ad1b5.png)

![image](https://user-images.githubusercontent.com/68277691/110670211-33feee00-81de-11eb-9d83-15cfea28b681.png)

- the current suggested solution in the Frappe https://frappe.io/kb/accounting/how-to-book-discounts-separately-in-erpnext is a workaround and didn't fit our needs.

**Comment by ankush** [comment]
Discount accounting is there on v13. Upgrade. 

https://github.com/frappe/erpnext/pull/26359

https://docs.erpnext.com/docs/v13/user/manual/en/accounts/articles/discount_accounting

**Comment by Ahmad-Najjar** [comment]
Yes Dear, I closed it because it is available, the date I requested it, it was not available thank you for your efforts.



Dr. Ahmad Najjar

Health Informatics Director/ Nixpend
