### ISSUE TITLE
Cannot delete after cancelling because Sales Invoice is Link to GL Entry

### ISSUE THREAD

**Issue by Ravn10** [frappe/erpnext#24845]
## Context information (for bug reports)

**Output of `bench version`**
```
ERPNext: v13.x.x-develop () (develop)
Frappe Framework: v13.0.0-dev (version-13-redesign-pre-release)
```

## Steps to reproduce the issue

1.Create Sales Invoice and submit.
2.Cancel the Invoice.
3.Now try deleting the invoice.

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by marination** [comment]
Hi @Ravn10  this isn't a bug, but a part of our attempt to make ledgers immutable in version 13. Ledgers will not be deleted like they used to in version 12, on transaction cancellation. We believe this will bring more credibility into the system.
These ledgers of cancelled transactions are also in the cancelled state and are not considered in reports.

It will not be possible to delete the Sales Invoices, but you can always filter your list by making sure that cancelled entries are not included
