### ISSUE TITLE
bug: Sales order's additional discounts are not fetching correctly in the Delivery Note/Sales Invoice

### ISSUE THREAD

**Issue by TurkerTunali** [frappe/erpnext#24869]
## Description of the issue
2 sales orders which have different "Additional Discount %" are merged in the delivery note. But delivery note total is different than the sum of sales orders because of wrongly applied "Additional Discount %".
## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 12.16.2
frappe 12.13.0
```

## Steps to reproduce the issue
1.Create a sales order with 1 item with 100 TL. 
2.Duplicate that sales order and apply additional discount as %50. So we have 1 sales order with 100 TL and second sales order as 50 TL.
3.Create a new delivery note, get items from sales order, select both sales order. 

### Observed result
The new delivery note will have grand total of 100 TL. Because of additional discount is set as %50 for both items.
This is also problematic in sales invoices, purchase receipts and purchase invoices.
### Expected result
Grand total should be 150 TL. ERPNext should apply discount logic in the lines.
### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by TurkerTunali** [comment]
Sales order with no additional discount.
![image](https://user-images.githubusercontent.com/710051/111026836-b3b6d380-83fd-11eb-8d91-5872f1a6cf97.png)

Sales order with %50 additional discount.
![image](https://user-images.githubusercontent.com/710051/111026882-e365db80-83fd-11eb-9dbd-890e880f7d2b.png)

Created delivery note against these 2 sales orders.
![image](https://user-images.githubusercontent.com/710051/111026920-1c05b500-83fe-11eb-9339-a15d38c71de0.png)

**Comment by Nihantra-Patel** [comment]
Duplicate Issue: #41711

It will be investigated in the newer version. So we closed the old issue.
