### ISSUE TITLE
ERPNext v12 to v13 migration issue

### ISSUE THREAD

**Issue by jabir-elat** [frappe/erpnext#24884]
I am trying to update ERPNext v12 to v13.Bench have custom apps and sites/
I am getting error while running…bench update —patch.

There is no issue when trying to upgrade without custom apps.

![1](https://user-images.githubusercontent.com/44110258/111143463-d555bd80-85ab-11eb-8524-9c156583051a.png)
![2](https://user-images.githubusercontent.com/44110258/111143486-dc7ccb80-85ab-11eb-9186-169ab57a1ff3.png)

## Steps to reproduce the issue

First of all have made backup of all sites from previous bench.
Then i freshly installed frappe and erpnext v12 and restored the backed up data.
# update
cd ~/frappe-bench
bench update
 
# update to major release ex. v12 --> v13
# nodejs >= 10 required
cd ~
curl -sL https://deb.nodesource.com/setup_10.x -o nodesource_setup.sh
sudo bash nodesource_setup.sh
sudo apt install nodejs
nodejs -v
 
# now upgrade
cd ~/frappe-bench
bench switch-to-branch version-13-beta frappe erpnext --upgrade
bench update --patch ##got error here
bench migrate
bench update --build

**Comment by LunarisX** [comment]
do bench start
open new tab of terminal and go to your bench directory and then try bench update --patch.

the bench server needs to be running i came to know from experience.

**Comment by jabir-elat** [comment]
not working
still the same error

**Comment by hugoovf** [comment]
![image](https://user-images.githubusercontent.com/69076992/112231534-2e21f780-8c37-11eb-8053-a73e8404637a.png)
I didn't have problems... But my installation is new and I can't login, any solution?
![image](https://user-images.githubusercontent.com/69076992/112231645-5f9ac300-8c37-11eb-9586-37624a75c753.png)

**Comment by jabir-elat** [comment]
> ![image](https://user-images.githubusercontent.com/69076992/112231534-2e21f780-8c37-11eb-8053-a73e8404637a.png)
> I didn't have problems... But my installation is new and I can't login, any solution?
> ![image](https://user-images.githubusercontent.com/69076992/112231645-5f9ac300-8c37-11eb-9586-37624a75c753.png)

do you have custom apps and sites with data on this bench?

**Comment by hugoovf** [comment]
I have nothing

**Comment by neelbhanushali** [comment]
@jabir-elat 

can you put down exact version from which you tried upgrading to v13?
also put down a backup of your site so this can be replicated with exact data.

**Comment by jabir-elat** [comment]
> @jabir-elat
> 
> can you put down exact version from which you tried upgrading to v13?
> also put down a backup of your site so this can be replicated with exact data.

erpnext 12.17.0
frappe 12.15.0
