### ISSUE TITLE
Feature Request - Time Billing @ Billing Rate

### ISSUE THREAD

**Issue by sjudy** [frappe/erpnext#2491]
I am fairly new to this project.  I have one specific need that I have looked high and low for.... professional services time billing.

I would be thrilled if an enhancement could be made to the current Time Billing.  The concept behind this is assumed to be for a professional support organization to be able to capture client time spent for billing purposes, however it is somewhat clunky.  Currently this feature does not require a company, but rather a project.  Not all hourly work is tied to a project (adhoc type activities).  While the Project is valuable information, the customer is really a necessity to be able to bill correctly.  I think COMPANY should therefore be required and make Project optional.

Second, I would suggest the ability to specify the service item (which can obtain the correct selling rate).  

Finally I would suggest that when this is converted to an invoice, that it CARRY this information over (rather than setting the hourly rate, service product and company manually again).  Then it is a simple "input it and forget it".  

If we want to really get crazy, allow batch to import by customer in one shot.  This would allow you to select all the records regardless of customer and the invoices would be created automatically by customer without the need to break them up by individually as the current method requires.  Again, this process will be taking into account the customer, service product, correct rate, default terms as specified in the tied fields from the time record itself.  As such, no user intervention should be required.

A good example of this would be how Odoo is doing HR/Time Recording.  They have their issues too, the use of analytic accounting gets ugly.  I feel this would be a massive improvement on that and to the system as a whole.  Considering the use of an Open Source ERP is not for the faint of heart, attracting IT firms or professional services organizations could be done by providing a great conduit for their own billing purposes, thus spreading word of this product to the other types of business who you want to target as a potential customer.

If at all possible, it would be nice to be able to create a time log from the "Case" form as well.  It is double entry as it currently stands.

Thank you for your consideration

Respectfully,

**Comment by PawanMeh** [comment]
Kindly look into the latest timesheet enhancements in version 8. Timesheet can be used for billing as well as salary in the latest version.

Kindly re-open issue or create a new one with any more suggestions

**Comment by sjudy** [comment]
I just checked out the enhancements and those are really nice.  Just what I was looking for!  Now, if you can get timesheets to integrate with the Support module, that would be a home run for me at least.  This would take customer initiated requests and allow you to convert them to billable items without creating individual tasks.

Thanks for the update!
