### ISSUE TITLE
ERPNext V5 Warehouse Error

### ISSUE THREAD

**Issue by amruthp** [frappe/erpnext#2492]
When a new company is created, default warehouse like Stores, Work-In-Progress and  Finished Goods are not being created. But if you try to Manually create it, it will give error saying, warehouse already exists. 

For more info please look at the post
https://discuss.frappe.io/t/erpnext-v5-warehouse-error/4020

**Comment by rmehta** [comment]
Warehouse account is for assets, the account in Item is for expense (its not expense until you consume it or deliver it)
