### ISSUE TITLE
Select Input on search not working 

### ISSUE THREAD

**Issue by HaniTetouha** [frappe/erpnext#24961]
## Description of the issue
when I try to select any item in search input like selecting a customer name or an item in Sales Invoice the selection is not committed and the field is set empty, as showen in the attached video.

https://user-images.githubusercontent.com/16355884/111865438-976fe500-896f-11eb-8f7f-53c2c1db87cd.mp4

## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 12.19.0
frappe 12.16.0

**Comment by HaniTetouha** [comment]
the problem is in any search input and I have tried many browsers, nothing is working

**Comment by YamanQD** [comment]
Same Issue here
It happened after the new update 12.19.0
Tried clearing the browser's cache, changing the browser, and restarting the server
Nothing works

**Comment by PBIS** [comment]
I'm having the same problem after update 12.19.0. Tried bench rebuild-global-search and restarting the server but that did not help.

**Comment by akhashogji** [comment]
Same issue here

**Comment by haythamk** [comment]
This issue is severe and about crash level, almost nothing is working in the entire ERPNext system after this 12.19 update. I hope that ERPNext developers will promptly take an action toward this.

**Comment by surajshetty3416** [comment]
We [have made the release](https://github.com/frappe/frappe/releases/tag/v12.16.1) for frappe framework with the fix.

Please update to fix the issue.

**Comment by PBIS** [comment]
The update fixed the issue for me. Thank you for addressing this so quickly!
