### ISSUE TITLE
Error in Qty fetched in Delivery Note from Pick List (Multiple UOM)

### ISSUE THREAD

**Issue by manan-ft** [frappe/erpnext#24970]
## Description of the issue
When you create a Delivery Note from Pick List Qty fetched in the child table is Stock Qty where as UOM fetched is UOM (not Stock UOM).
This causes a problem when you have multiple UOMs

## Context information (for bug reports)
This bug represents an issue only when the item has Multiple UOMs

**Output of `bench version`**
```
ERPNext: v13.0.0-beta.11 (version-13-beta)

Frappe Framework: v13.0.0-beta.10 (version-13-beta)
```

## Steps to reproduce the issue
1. Create an Item with Multiple UOMs and Has Batch No
2. Create a Sales Order (and Submit it)
3. Create Pick List from Sales Order and Submit it (ERPNext will fetch Qty based on available batches)
![Screenshot 2021-03-22 at 4 12 04 PM](https://user-images.githubusercontent.com/35499267/111978752-48ba7a80-8b2a-11eb-994e-08b676a54ec6.png)

4. Create Delivery Note from Sales Order
![Screenshot 2021-03-22 at 4 13 00 PM](https://user-images.githubusercontent.com/35499267/111978779-540da600-8b2a-11eb-8241-34fdd6bed10e.png)

### Observed result
Here the Qty fetched is Stock Qty (should be Qty) and UOM fetched is UOM (which is correct)

### Expected result
Qty fetched in Delivery Note should be Qty and not Stock Qty

### Stacktrace / full error message

Not Applicable

## Additional information

NA

**Comment by Anuja-pawar** [comment]
Fixed #25106
