### ISSUE TITLE
Unable to customize Sales Invoice

### ISSUE THREAD

**Issue by fproldan** [frappe/erpnext#24977]
## Description of the issue

When customizing a sales invoice, the following message is displayed and cannot be saved

> Error: Document has been modified after you have opened it (2021-03-22 14:22:26.441159, 2021-03-22 14:22:26.593258). Please refresh to get the latest document.

## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 13.0.0-dev
frappe 13.x.x-develop
```

## Steps to reproduce the issue

1. Go to Sales Invoice List
2. Customize
3. Add a new field

### Observed result
![image](https://user-images.githubusercontent.com/4945122/112031747-70094b80-8b1a-11eb-81fb-94428ee1367c.png)

### Expected result
New field added succesfully

**Comment by dj12djdjs** [comment]
@fproldan If you reload the page, then attempt to add the field. Do you still get the same message?

**Comment by fproldan** [comment]
@dj12djdjs Yes, I tried reloading multiple times. I was able to customize other DocType without problems but in Sales Invoice I always get the same message.

**Comment by dj12djdjs** [comment]
I just tested on fresh install from frappe cloud. Same outcome.

**Comment by dj12djdjs** [comment]
Okay, I've done some digging and found. Only doctypes that have "Track Seen" set to "Yes" have this customization problem.
