### ISSUE TITLE
Calculating absent days of new employee with attendance based salary slip

### ISSUE THREAD

**Issue by usman-alikhan** [frappe/erpnext#25010]
So erpnext payroll settings allow for that if a person does not mark attendance it will be treated as absent and accordingly the salary calculation is affected. However, the issue is that it includes even holidays as absent. 

It works perfectly fine in case of existing employees but in case of fresh employees joining in the middle of the month it minuses their unmarked days from the total payment days resulting in incorrect issue.
I am using v13.

Details of issue here:
https://discuss.erpnext.com/t/salary-calculation-with-absent/73142/2

**Comment by usman-alikhan** [comment]
> Details of issue here:
> https://discuss.erpnext.com/t/salary-calculation-with-absent/73142/2

Can someone help fix this?

**Comment by ruchamahabal** [comment]
@usman-alikhan Your configuration is as follows (reference: [Discuss Thread](https://discuss.erpnext.com/t/salary-calculation-with-absent/73142))

![image](https://user-images.githubusercontent.com/24353136/113163468-d4848300-925d-11eb-8e7d-eb441c5a15ba.png)

You have enabled **Include Holidays in Total no. of Working Days** which means, your holidays would also be considered as Working Days that is eventually your payment days. Also, you have set **Consider Unmarked Attendance As Absent**.

Hence the system considers your unmarked attendance as Absent on holidays which are considered as working days.

Closing this issue. Please reopen if need be.

**Comment by ruchamahabal** [comment]
@usman-alikhan From what I understand from your configuration on the [discuss thread](https://discuss.erpnext.com/t/salary-calculation-with-absent/73142):

![image](https://user-images.githubusercontent.com/24353136/113171045-c25a1300-9264-11eb-9308-de63d255eaa6.png)

You have enabled **Include Holidays in Total no. of Working Days** which means that your holidays won't be excluded from your working days which are eventually your payment days. Also, you have set **Consider Unmarked Attendance as Absent**.

Hence the system considers your unmarked attendance as absent on holidays which are considered as working days. You can disable **Include Holidays in Total no. of Working Days** if you don't want the holidays to be considered as working days.

Please let us know if the case is something else.

**Comment by ruchamahabal** [comment]
Closing for now. Please reopen if need be.

**Comment by usman-alikhan** [comment]
Thanks for your input but  as i said earlier:
It works perfectly fine in case of existing employees but in case of fresh employees joining in the middle of the month it minuses their unmarked days from the total payment days resulting in incorrect issue.

The issue is for new hirees. There appears to be some incorrect formula at back end causing incorrecy result for a person who has joinee in middle of the month.

You can create an employee who joins on say 21st of a month and then check result yoirself.

**Comment by usman-alikhan** [comment]
@ruchamahabal If an employee joins or 21st and its a month with 30 days and pay is usd 1,000 .. salary for the month is calculated as
1000 / 31 x 10
Now lets assume only one weekend (sat & sun) fell in ths period and he took 1 absent.

Then, this means that 2 holidays are included in working days but he is not marked as absent on these holidays. In this case salary should be calculated as:
1000 / 30 x 9 

With settings in my screenshot it follows this logic for existinf employee. But in case of new employee it doesnt follow this logic instead it minuses their entire unmarked days during month (including those before joining) from the payment days calculated.
