### ISSUE TITLE
Carry forward leaves Issue

### ISSUE THREAD

**Issue by komalvadavale-09** [frappe/erpnext#25039]
## Steps to reproduce the issue

1. Allocate the leaves to Year for the Financial year April 2020-March 2021, with the leave type as "Carry forwarded leaves"

![Screenshot (1087)](https://user-images.githubusercontent.com/64304459/112711629-db269980-8eef-11eb-8cb9-1e53cda89b84.png)

![Screenshot (1088)](https://user-images.githubusercontent.com/64304459/112711774-fc3bba00-8ef0-11eb-911e-7bf5969012ba.png)

2. Create new leave period for new financial year- April 2021-March 2022

3. Click at grant leaves & select "Add unused leaves from previous allocations"
![Screenshot (1090)](https://user-images.githubusercontent.com/64304459/112711925-17f39000-8ef2-11eb-852a-a322bc211d97.png)

![Screenshot (1091)](https://user-images.githubusercontent.com/64304459/112711960-55581d80-8ef2-11eb-9415-0ae70bff7b76.png)

### Observed result
while allocating the leaves it is not considering the unused leaves, even if user is having balance unused leaves.

### Expected result
while allocating the leaves it is not considering the unused leaves, even if user is having balance unused leaves.
In the above eg. user is having 4 balance leaves so while allocation of new leaves system should grant New leaves(4)+balance leaves(4)=8, but the system is only allocating 4 (new) leaves.

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by kkaranbhanushali** [comment]
Seems like bug.

**Comment by pateljannat** [comment]
@komalvadavale-09 I am unable to replicate the issue on version-12. 

1. Carry Forward Leave Type

![Screenshot 2021-04-01 at 6 59 53 PM](https://user-images.githubusercontent.com/31363128/113301643-de20f000-931c-11eb-9b29-5dcc04bfc567.png)

2. Previous Leave allocation

![Screenshot 2021-04-01 at 7 01 10 PM](https://user-images.githubusercontent.com/31363128/113302176-6d2e0800-931d-11eb-8225-5a8a4fbce6b5.png)

3. Current Leave Allocation

![Screenshot 2021-04-01 at 7 01 26 PM](https://user-images.githubusercontent.com/31363128/113302192-7028f880-931d-11eb-920a-97544f6d019f.png)

For me, the current leave allocation is considering the unused leaves of the previous allocation.

Did you do anything differently? 

You can check if the Leaves are actually unused from your side. Verify if the dates of the Leave application and Leave Allocation are proper.

**Comment by komalvadavale-09** [comment]
@pateljannat As the the attached screenshot it seems that You are trying to allocated leaves from leave allocation.

We are facing issue with leave allocation from leave period.

**Comment by pateljannat** [comment]
@komalvadavale-09 I allocated the leaves through Leave Period itself. Can you verify and try again if you did everything as per the above-mentioned steps

**Comment by pushkarjsh88** [comment]
@pateljannat Are there further insights on this ?

**Comment by yadavyk** [comment]
This is working fine, hence closing.  @komalvadavale-09, please reopen the issue if still persists for you.
