### ISSUE TITLE
bug: Deductions not coming through onto Salary Slip

### ISSUE THREAD

**Issue by nameduser0** [frappe/erpnext#25036]
Could be related to #24465

Salary Structure:

![Screen Shot 2021-03-26 at 21 58 20](https://user-images.githubusercontent.com/64409021/112697306-2bb1de80-8e7f-11eb-85e0-7e49f36feeb3.png)

Salary Slip:

![Screen Shot 2021-03-26 at 22 04 50](https://user-images.githubusercontent.com/64409021/112697399-58fe8c80-8e7f-11eb-8f97-8e9718ae2db1.png)

## Context information (for bug reports)

**Output of `bench version`**
```
ERPNext: v13.0.0-dev
Frappe Framework: v13.0.0-dev
```

## Steps to reproduce the issue

1. Create Employee, Salary Structure, Assignment
2. Create Payroll Entry & submit

### Observed result
No deduction on salary slip

### Expected result
Deduction

**Comment by nameduser0** [comment]
Appears to be because of the formula, if a basic amount is used, it works.
Please add more automated tests for formulas. Are brackets allowed?

![Screen Shot 2021-03-26 at 22 14 51](https://user-images.githubusercontent.com/64409021/112698077-cf4fbe80-8e80-11eb-86a2-65524ff4e277.png)

**Comment by ruchamahabal** [comment]
@casesolved-co-uk We tried replicating the issue with the exact same components and formulae but it was not replicated. Have you set up any condition for the Professional Tax component because of which it did not show up?

**Comment by nameduser0** [comment]
@ruchamahabal Nope, see below. My branch is up-to-date with develop from 27th March 2021. Just tried it again with the same result.

![Screen Shot 2021-03-31 at 17 39 21](https://user-images.githubusercontent.com/64409021/113180401-9a5cb680-9248-11eb-9845-074b2234ea8c.png)

**Comment by ruchamahabal** [comment]
@casesolved-co-uk We could replicate it. Thanks for reporting. [This](https://github.com/frappe/erpnext/pull/25117) should fix it.
