### ISSUE TITLE
Item code error while creating a multiples variants

### ISSUE THREAD

**Issue by SantiagoX9713** [frappe/erpnext#25037]
## Description of the issue
When trying to create new variants from a template and selecting the attributes of the new variants triggers the following error:
Item Code is required
## Context information (for bug reports)

erpnext 13.x.x-develop
erpnext_telegram_integration 0.0.5
frappe 13.x.x-develop
## Steps to reproduce the issue

1. Create a new item that has variants mustn't be numeric values.
2. Tap Create> Multiple Variants
3. Choose at least two option 

![image](https://user-images.githubusercontent.com/41874407/112703285-01025e80-8e5c-11eb-9dc2-98812584e252.png)

I'm using Ubuntu 18 & install with easy script

**Comment by nabinhait** [comment]
Can't replicate it, do you have any customization on your site?

**Comment by szufisher** [comment]
same issue on latest version-13
ERPNext: v13.0.1 (version-13)

Frappe Framework: v13.0.2 (version-13)

traceback as below
Traceback (most recent call last):
  File "/home/fisher/erpnext/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/fisher/erpnext/apps/frappe/frappe/api.py", line 58, in handle
    return frappe.handler.handle()
  File "/home/fisher/erpnext/apps/frappe/frappe/handler.py", line 30, in handle
    data = execute_cmd(cmd)
  File "/home/fisher/erpnext/apps/frappe/frappe/handler.py", line 70, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/fisher/erpnext/apps/frappe/frappe/__init__.py", line 1145, in call
    return fn(*args, **newargs)
  File "/home/fisher/erpnext/apps/erpnext/erpnext/controllers/item_variant.py", line 189, in enqueue_multiple_variant_creation
    return create_multiple_variants(item, args)
  File "/home/fisher/erpnext/apps/erpnext/erpnext/controllers/item_variant.py", line 205, in create_multiple_variants
    variant.save()
  File "/home/fisher/erpnext/apps/frappe/frappe/model/document.py", line 284, in save
    return self._save(*args, **kwargs)
  File "/home/fisher/erpnext/apps/frappe/frappe/model/document.py", line 306, in _save
    self.insert()
  File "/home/fisher/erpnext/apps/frappe/frappe/model/document.py", line 232, in insert
    self.set_new_name(set_name=set_name, set_child_names=set_child_names)
  File "/home/fisher/erpnext/apps/frappe/frappe/model/document.py", line 422, in set_new_name
    set_new_name(self)
  File "/home/fisher/erpnext/apps/frappe/frappe/model/naming.py", line 55, in set_new_name
    frappe.throw(_("{0} is required").format(doc.meta.get_label(fieldname)))
  File "/home/fisher/erpnext/apps/frappe/frappe/__init__.py", line 424, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable, wide=wide, as_list=as_list)
  File "/home/fisher/erpnext/apps/frappe/frappe/__init__.py", line 403, in msgprint
    _raise_exception()
  File "/home/fisher/erpnext/apps/frappe/frappe/__init__.py", line 357, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Item Code is required

**Comment by rubberfashion** [comment]
same issue on latest version-13
ERPNext: v13.0.1 (version-13)
Frappe Framework: v13.0.2 (version-13)
no custimization

I have the same issue with multiple variants. Clicking on "Make" cause the error.

<img width="982" alt="Screenshot 2021-04-13 105117" src="https://user-images.githubusercontent.com/28510172/114525213-34a7fb80-9c46-11eb-91d5-6f9efe98f4b5.png">

Error:
<img width="416" alt="Screenshot 2021-04-13 105156" src="https://user-images.githubusercontent.com/28510172/114525298-4a1d2580-9c46-11eb-9aa5-f16984f8c2fc.png">
That indicate maybe an error with autogenerating the item code.


Also, when i create a Single variant, select colour: black, size: S
<img width="1003" alt="Screenshot 2021-04-13 105302" src="https://user-images.githubusercontent.com/28510172/114525493-6faa2f00-9c46-11eb-84bd-d65617682723.png">

fill out the "Item Code" and save
<img width="995" alt="Screenshot 2021-04-13 105349" src="https://user-images.githubusercontent.com/28510172/114525664-936d7500-9c46-11eb-9e06-852bd0cad8fd.png">

I can not specify any attribute value:
<img width="758" alt="Screenshot 2021-04-13 104603" src="https://user-images.githubusercontent.com/28510172/114524560-9d42a880-9c45-11eb-841e-918536bd0f5b.png">
<img width="722" alt="Screenshot 2021-04-13 104800" src="https://user-images.githubusercontent.com/28510172/114524751-c400df00-9c45-11eb-9bee-9546db5a9eeb.png">

In the template file i can specify:
<img width="770" alt="Screenshot 2021-04-13 110909" src="https://user-images.githubusercontent.com/28510172/114527860-bbf66e80-9c48-11eb-97b6-5854b99d6218.png">
<img width="828" alt="Screenshot 2021-04-13 110828" src="https://user-images.githubusercontent.com/28510172/114527727-96696500-9c48-11eb-8002-bd9d416c1b4b.png">

**Comment by szufisher** [comment]
this is caused by incorrectly added attribute field into the item variant setting fields list.
related code is at erpnext.controllers.item_variant.copy_attribute_to_variant
allow_fields = [d.field_name for d in frappe.get_all("Variant Field", fields = ['field_name'])]

solution:
make sure both attribute and has_variants 2 fields not among the fields list.
![image](https://user-images.githubusercontent.com/12823863/114667654-4c5cae00-9d32-11eb-97c2-a231cfd7d435.png)

seems patch to delete the attribute field is needed.

**Comment by rubberfashion** [comment]
Hi,
Thank you for reply!! It works! Now the issue is gone.
I deleted the "attribute" field and want to recreate it. I got a empty selection (when i am on page2 - page 1 is working)
page 1:
<img width="967" alt="Screenshot 2021-04-14 110131" src="https://user-images.githubusercontent.com/28510172/114684006-cc721c00-9d10-11eb-9914-3918832651f3.png">
page 2:
<img width="971" alt="Screenshot 2021-04-14 110218" src="https://user-images.githubusercontent.com/28510172/114684127-e9a6ea80-9d10-11eb-96d0-2c77b5318d22.png">
When i want to insert new row field list is empty:
<img width="1117" alt="Screenshot 2021-04-14 104240" src="https://user-images.githubusercontent.com/28510172/114684236-02af9b80-9d11-11eb-9185-64a579398593.png">
I run the instance on a docker container EDGE version 13.x.x.x develop and Traefik.

**Comment by szufisher** [comment]
not understand what is the current problem, you can not add other fields into the field list in item variant setting screen? the 2 fields: attribute and has_variants should not be added back into this list as they are not needed to be copied from template item to variant item.

**Comment by rubberfashion** [comment]
Hi,

Thanks for your help. If i have further issues i will open a new thread.

:)
