### ISSUE TITLE
Target Warehouse is ReadOnly on Packed Items

### ISSUE THREAD

**Issue by MaxMorais** [frappe/erpnext#25031]
## Description of the issue

People that are trying to handle "Leasing", "Comodato" or "Concession of Returnable Items" aren't being able to do the full flow in ERPNext due 2 major reasons

- 1 Target Warehouse field is not available on Paked Items Table
- 2 Feature is not documented at all

## Context information (for bug reports)

https://discuss.erpnext.com/t/new-use-case-how-can-i-get-shipping-crates-tracked-and-returned/72326

**Output of `bench version`**
```
erpnext and frappe-12 and so on
```

## Steps to reproduce the issue

1. Create a Product Bundle Item with a Returnable
2. Create a Sales Order for the Bundle Item
3. Try associate the Target Warehouse on Packed Items Table

### Observed result

Target Warehouse is not available on Packed Items Table

### Expected result

Target Warehouse is available on Packed Items Table

### Stacktrace / full error message

There's no error, but the system doesn't do the transfer for another warehouse

## Additional information

https://discuss.erpnext.com/t/new-use-case-how-can-i-get-shipping-crates-tracked-and-returned/72326

**Comment by Nihantra-Patel** [comment]
Hi @MaxMorais,

Target Warehouse is editable in the Packed Items table. I think you should upgrade to the ERPNext version 14 or 15. This feature is now available on it.

Thank You!

**Comment by MaxMorais** [comment]
@Nihantra-Patel thanks for the Info!

I'm already on v15, I'll try the lending model, and I'll let you know!
