### ISSUE TITLE
Material rate fetch base on different UOM

### ISSUE THREAD

**Issue by laweschan** [frappe/erpnext#25032]
## Description of the issue
item defined
item price defined
define UoM of item, eg. Nos with Conversion Factor is 1, bottle with Conversion Factor 200

when apply purchase request / purchase order
price rate can be fetched, however, it calculate in wrong amount if the order UoM unit set to bottle rather than default UoM (Nos) 

## Context information (for bug reports)

**Output of `bench version`**
```
![Capture03](https://user-images.githubusercontent.com/17445193/112660877-e7c7d500-8e90-11eb-9831-ce90739c471f.PNG)

```

## Steps to reproduce the issue

1.create item
  Default Unit of Measure set to Nos
  set Units of Measure as 
  
![capture01](https://user-images.githubusercontent.com/17445193/112661124-22317200-8e91-11eb-807a-0ae13d29f12f.PNG)

  
2. set item price
    set price list to "standard buying"
    
![Capture04](https://user-images.githubusercontent.com/17445193/112661293-54db6a80-8e91-11eb-9788-7ffee59e381a.PNG)

   assign rate
   
![Capture05](https://user-images.githubusercontent.com/17445193/112661459-7fc5be80-8e91-11eb-8888-a4b91e0cf4b9.PNG)

3.create material request
  
![Capture06](https://user-images.githubusercontent.com/17445193/112661741-cd422b80-8e91-11eb-834a-35d71672f424.PNG)

### Observed result
UOM Conversion Factor correct
Rate Correct
Amount incorrect
   
![Capture7](https://user-images.githubusercontent.com/17445193/112661828-ea76fa00-8e91-11eb-9cb5-c1bebabc4e8c.PNG)

### Expected result
   
Amount formula should be:
=Quantity * Rate * UOM Conversion Factor 
=1 * 2 * 200
= 400

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

Fedora Linux, Manual installation

**Comment by deepeshgarg007** [comment]
@laweschan Unless you have set UOM-specific item prices the rate won't update itself. You will have to update manually in that case, doesn't look like a bug, closing this issue
