### ISSUE TITLE
ERPNext unable to link to Default Currency

### ISSUE THREAD

**Issue by buff0k** [frappe/erpnext#25066]
Hi, running latest development build of ERPNext and for the last week I have been unable to save any forms where there is a currency component. I have deleted the entire bench and reinstalled from scratch twice with the same result. Any field referencing currency values indicate "Company:company:default_currency" and whenever such forms is saved, regardless of changes to currency values, the error: "Could not find Currency: Company:company:default_currency" is displayed.
I have confirmed that Default Currency is set under Global Defaults and have disabled all currencies except for the one I use (ZAR if it makes a difference).

**Comment by ruchamahabal** [comment]
Can you specify a particular doctype where you are facing this and give us the steps to replicate?

**Comment by buff0k** [comment]
> Can you specify a particular doctype where you are facing this and give us the steps to replicate?

Basically any doctype that uses currency, with certainty it is:
Create Tax Slab
Create Payslip

Above is replicated in multiple fresh installs at this stage. Even on a fresh install when attempting to create any of the above I get the same error.
