### ISSUE TITLE
Fetch custom field value from master to child table of transactions

### ISSUE THREAD

**Issue by gohyc** [frappe/erpnext#2506]
Currently we can not use the easy way to populate the field data from the master table to the child table of transactions (like the Items in the Sales Order), i.e. using read only field with the option field - mastertable.field.  We have to use a custom script to populate the data over.

Please make it possible to use the simple option method to populate data from master table to the child table of transactions as well.

**Comment by donblackowiak** [comment]
I would like to vote for this because the work around of using a custom script is clunky, doesn't seem to work nearly as advertised, aka cur_frm.add_fetch('item','item_custom_field_name','sales_invoice_item_custom_field_name') and client scripts won't help for importing data via csv.
