### ISSUE TITLE
GSTR1 B2B is not showing

### ISSUE THREAD

**Issue by Ibrahim0792** [frappe/erpnext#25073]
I have posted 2 sales invoices but in GSTR1 B2B section invoice is not showing. Can able to see in GST sales register
Please check below GSTR1 screenshot

![image](https://user-images.githubusercontent.com/70377739/113096491-e3921380-9212-11eb-8e9f-1e7ef04b6e2c.png)

GST- sales Register Screen shot

![image](https://user-images.githubusercontent.com/70377739/113096641-353a9e00-9213-11eb-85b2-ef8495593d49.png)

**Comment by harshit-30** [comment]
@Ibrahim0792 closing this since you have labeled it as invalid.
