### ISSUE TITLE
Email validation keep raising error while inputting

### ISSUE THREAD

**Issue by thanhdn1989** [frappe/erpnext#25072]
Hi guys,

I did a fresh production installation of Frappe and ERPNext today, and the issue is that when creating user email I keep getting the error for invalid email for every keystroke I made ( means I didn't finish input the email yet, but it keep complain about invalid email)
The setup I used are:
Frappe version 12.16.1
ERPNext version 12.19.0

**Comment by ruchamahabal** [comment]
Hello,

This was fixed in: [https://github.com/frappe/frappe/pull/12670](https://github.com/frappe/frappe/pull/12670)
