### ISSUE TITLE
Inconsistency in Trail Balance 

### ISSUE THREAD

**Issue by arunjose1995** [frappe/erpnext#25088]
Greetings everyone,

Trying to figure what is causing the below issue.

<img width="1142" alt="april-month" src="https://user-images.githubusercontent.com/26113143/113119574-37f6bc80-922e-11eb-952d-f2b76653f844.png">

In the above image if you notice we don’t get to see any Debits or Credits shown up and hence the opening and closing balance remains the same.

<img width="1143" alt="may-month" src="https://user-images.githubusercontent.com/26113143/113119600-404ef780-922e-11eb-8d59-87595627f419.png">

The above image is the next month trail balance sheet. But if you notice in this particular image the opening balance is different. So we are looking at two consecutive months April and May. If the closing balance of april month is so on so the opening balance of the proceeding month should be the same but we find it to be different. This is because of the debits and credits column calculation not being queried properly. We are using version-12 of erpnext. Any help on this would be much appreciated.

Thanks and Regards,
Arunachalam E

**Comment by harshit-30** [comment]
Please create another issue if it is replicable after v13.10.
