### ISSUE TITLE
Contact Page Hangs when the contact has too many communications

### ISSUE THREAD

**Issue by adityaduggal** [frappe/erpnext#2510]
There seems to be a problem with the html view of the communication. The problem is that when we open a contact which has too many communications then the page seems to hang. Possible solutions:
- [ ] Limit the html view to last 10~20 communications only
- [ ] When website footer subscribe me is clicked then system should check the existing users before creating a contact since many a times an existing user clicks on subscribe me and then a new contact is created which is then linked to all the communications sent by that contact which is more like a BUG.

**Comment by Arundhatii** [comment]
seems to be working fine. Closing the issue
