### ISSUE TITLE
add feature to Journal Entry

### ISSUE THREAD

**Issue by Baida-Lala** [frappe/erpnext#25115]
Hi ,
1- Can you tell me Where I can find html and url files of Journal Entry in ERPNext?

2- How can I change the currency symbol from standard field to another symbol that change by select from select link by using client script 

3- Why I Can't change value of standard field permanently  , when we change it from client script (on submit) when we reload the page , all our changes are deleted ?

**Comment by ankush** [comment]
1. https://github.com/frappe/erpnext/tree/develop/erpnext/accounts/doctype/journal_entry
2. don't understand the question. Share screenshot of what you are trying to achieve.
3. share snippet of your code.


This does not seem like a bug, more of a developer query. Please create a post on forums: https://discuss.erpnext.com/c/developers

**Comment by Baida-Lala** [comment]
we want to add multi currency feature to the Journal entry by add select field (Currency Name which is a link from Currency doc) 
when the user select the currency from the list , the symbol of debit and credit change by the symbol of the select .
After that the total change by exchange rate of the currency and reflect the effect on the account tree.

when we used client script 
we did what we want but when reload page all changes were deleted

**Comment by ankush** [comment]
> client script (on submit)

Just a note, `on_submit` executes AFTER submission. Ref: https://frappeframework.com/docs/user/en/api/form 

Also what you are trying to achieve seems to be possible already. I'd suggest asking in forum with detailed description. 

You can create multi-currency journal entries: https://docs.erpnext.com/docs/user/manual/en/accounts/multi-currency-accounting#33-journal-entry

**Comment by Baida-Lala** [comment]
I will check the multi currency feature in the ERPNext again , may I didn't understand it well.
Thank you , Mr. ankush
