### ISSUE TITLE
Negative amount in invoice

### ISSUE THREAD

**Issue by betabank** [frappe/erpnext#2512]
Hi, ERP does not have an option for -ve invoicing yet. Created from the forum:
https://discuss.frappe.io/t/negative-amount-in-invoice/721/4

**Comment by betabank** [comment]
Hi is this feature planned for v5?
Thanks!

**Comment by anandpdoshi** [comment]
This requirement looks more like negative qty invoicing, as in return invoicing. We haven't planned to take this up in v5.0

**Comment by betabank** [comment]
OK, thanks for the update, please bear in mind this is a must for companies that deal with good that involve returnable packaging, containers and so on, beside companies that work with deposits and or guarantees.
In all these scenarios, a 1st invoice is made with the product + packaging and then when the customer returns the packaging/container then a negative invoice should be sent. It cannot be treated as return as usually the 1st invoice is sent and paid and after comes the return.

**Comment by betabank** [comment]
Hi, now that v5 is up and running, do you think this is possible to implement?

**Comment by betabank** [comment]
Hi, is this available in v6? Thank you very much.

**Comment by nabinhait** [comment]
Yes, this has been implemented.

**Comment by betabank** [comment]
Hi, when trying to save a negative bill or delivery note, we still get:

"Incorrect value: Grand Total (Company Currency) must be >= 0.0"
"Did not save"

We were testing with versions:
ERPNext: v6.27.19
Frappe Framework: v6.27.19

**Comment by nabinhait** [comment]
To make a negative invoice, you have to check "Is Return" field.

**Comment by betabank** [comment]
"Is Return" field does not appear in the invoice, but on the delivery note, however in the delivery note, "Is Return" is marked with a prohibition sign and not editable...

**Comment by Synertic** [comment]
Hi, I sent 6 invoices to a client, On one of them I make an Item return for one product.

The client send me a payment for 5 invoices, on the payment detail I have the credit note and the payment of 4 other invoice but not the invoice where the item was return.

I make payment entry for the 4 invoices and the credit note on the same entry.

I still get the last invoice with an outstanding ballance. The outstanding ammount include the credit note.
On the invoice for that client I still get the credit note.


How I can apply the payment to that credit not and get the real outstanding ammount on the last invoice.


Here In Canada the credit note need to be a regular invoice with negative balance. The client send a payment for multiple invoive and include the negative invoice on that payment.

**Comment by LifeP** [comment]
Hi any update on this? We need to take returns for invoices sold on previous system. 
Without referencing to the invoice.

**Comment by gbard** [comment]
We are also strugling with this issue. Any updates?

**Comment by bohlian** [comment]
This PR should help with your issues https://github.com/frappe/erpnext/pull/10665

Waiting for it to be merged.

**Comment by ioweb-gr** [comment]
For anyone looking for it the validation for grand total seems to be here 

frappe-bench/apps/erpnext/erpnext/controllers/accounts_controller.py:82

```python
			if not self.meta.get_field("is_return") or not self.is_return:
				self.validate_value("base_grand_total", ">=", 0)
```
I wish validation rules could be overriden with custom modules. That way we could implement our own custom rules instead of being this restricted.  Posting it here because I was in the same spot today for sales orders
