### ISSUE TITLE
Account None not found on submit of Period Closing Voucher - ERPNext: v13.0.0-beta.13 (HEAD)

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#25135]
![image](https://user-images.githubusercontent.com/1822868/113281908-e3674600-92ee-11eb-8b71-c5ea3619071d.png)

**Comment by muchai** [comment]
This happens when there're accounting dimensions setup.

**Comment by harshit-30** [comment]
Please share proper steps to replicate this issue.

**Comment by muchai** [comment]
This was happening in situations where there were any dimensions defined. We deleted the dimension as it was not in use, and we were able to close the year.
