### ISSUE TITLE
Page bank-reconciliation not found - ERPNext: v13.0.0 (version-13)

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#25151]
The link under accounts should point to bank reconciliation tool I guess.

![image](https://user-images.githubusercontent.com/1822868/113401898-d3ae3700-93ac-11eb-8d07-305a9c12ffb0.png)

**Comment by littlebunyip** [comment]
Same issue here with "Bank Statement Transaction Entry" and "Bank Statement Settings" links also not working. Can navigate to these docs via the search bar.

Also this might be related but for any user not the "Administrator" there is only Bank, Bank Account and Bank Reconciliation Statement available as link cards.
![Screenshot_2021-04-03_06-31-21](https://user-images.githubusercontent.com/17291869/113450028-a0b88180-9446-11eb-82af-63a171d7b096.png)

```
Installed Apps
ERPNext: v13.0.0 (version-13)

Frappe Framework: v13.0.0 (version-13)

Lb Erpnext Dev: v0.0.1 (master)
```

**Comment by Islammoustafa95** [comment]
i'm having the same issue

**Comment by Islammoustafa95** [comment]
still open and not solved

i found out that it only happens after upgrading to v13 and using command `bench build` , if not using that command after upgrading it will not happen.

we need a solution to solve that issue for production sites

thanks

**Comment by hasnain2808** [comment]
Hey,

The Bank reconciliation tool link was updated but the workspace was not updated

This should fix it https://github.com/frappe/erpnext/pull/25670
