### ISSUE TITLE
The email validation of Data field has issues

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#25158]
Hi ,

When you set 'Email' as option for a Data field, the validation occurs too quickly thus not allowing the user to finish typing before throwing errors. The validation should occur when the user clicks outside the field and/or when saving the form and NOT as the user is typing!

Pls help fix asap as this is an important feature

Thanks

**Comment by ankush** [comment]
closed by https://github.com/frappe/frappe/pull/12670
