### ISSUE TITLE
Pos Not Working - ERp Next V 13

### ISSUE THREAD

**Issue by govindasamyp** [frappe/erpnext#25168]
## Context information (for bug reports)

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1.
2.
3.

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by glibersat** [comment]
Can you provide a description of what's "not working" for you?

**Comment by kennethsequeira** [comment]
Closing due to lack of information
