### ISSUE TITLE
Switch to v13, Error: Cannot find module '@snyk/graphlib'

### ISSUE THREAD

**Issue by blackyzero** [frappe/erpnext#25161]
Hello,

I try to switch to v13, but getting following error:
`$ bench setup requirements
Installing applications...
$ ./env/bin/pip install -q -U pip

Installing frappe
$ ./env/bin/pip install -q -U -e ./apps/frappe
$ yarn install
yarn install v1.22.10
[1/4] Resolving packages...
success Already up-to-date.
$ yarn run snyk-protect
yarn run v1.22.10
$ snyk protect
Error: Cannot find module '@snyk/graphlib'
Require stack:
- /opt/services/frapper/frappe-bench/apps/frappe/node_modules/snyk-gradle-plugin/node_modules/@snyk/java-call-graph-builder/dist/call-graph.js
- /opt/services/frapper/frappe-bench/apps/frappe/node_modules/snyk-gradle-plugin/node_modules/@snyk/java-call-graph-builder/dist/java-wrapper.js
- /opt/services/frapper/frappe-bench/apps/frappe/node_modules/snyk-gradle-plugin/node_modules/@snyk/java-call-graph-builder/dist/index.js
- /opt/services/frapper/frappe-bench/apps/frappe/node_modules/snyk-gradle-plugin/dist/index.js
- /opt/services/frapper/frappe-bench/apps/frappe/node_modules/snyk/dist/lib/plugins/index.js
- /opt/services/frapper/frappe-bench/apps/frappe/node_modules/snyk/dist/lib/plugins/get-single-plugin-result.js
- /opt/services/frapper/frappe-bench/apps/frappe/node_modules/snyk/dist/lib/plugins/get-multi-plugin-result.js
- /opt/services/frapper/frappe-bench/apps/frappe/node_modules/snyk/dist/lib/plugins/get-deps-from-plugin.js
- /opt/services/frapper/frappe-bench/apps/frappe/node_modules/snyk/dist/lib/snyk-test/run-test.js
- /opt/services/frapper/frappe-bench/apps/frappe/node_modules/snyk/dist/lib/snyk-test/index.js
- /opt/services/frapper/frappe-bench/apps/frappe/node_modules/snyk/dist/lib/index.js
- /opt/services/frapper/frappe-bench/apps/frappe/node_modules/snyk/dist/lib/analytics.js
- /opt/services/frapper/frappe-bench/apps/frappe/node_modules/snyk/dist/cli/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/services/frapper/frappe-bench/apps/frappe/node_modules/snyk-gradle-plugin/node_modules/@snyk/java-call-graph-builder/lib/call-graph.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

Installing erpnext
$ ./env/bin/pip install -q -U -e ./apps/erpnext
$ yarn install
yarn install v1.22.10
[1/4] Resolving packages...
success Already up-to-date.
$ yarn run snyk-protect
yarn run v1.22.10
$ snyk protect
Successfully applied Snyk patches

Done in 2.25s.
Done in 3.11s.`

I also install,
`$ npm install -g @snyk/graphlib
+ @snyk/graphlib@2.1.9-patch.3
updated 1 package in 0.9s
`

How could i fix it?
Thank you.

**Comment by blackyzero** [comment]
fixed after creating a symlink to frappe node module directory

**Comment by szufisher** [comment]
@blackyzero 
fixed after creating a symlink to frappe node module directory

can you help to provide detailed steps/command ?

thanks.

**Comment by blackyzero** [comment]
After you installed @snyk/graphlib as root,

ln -s /usr/lib/node_modules/npm/node_modules/@snyk/graphlib /opt/services/frapper/frappe-bench/apps/frappe/node_modules/

This issue doesn't happen with fresh install v13.
