### ISSUE TITLE
Making Purchase Receipt from Purchase Invoice

### ISSUE THREAD

**Issue by Priyanka-IAS** [frappe/erpnext#2517]
In our business scenario, we import material from USA and Europe to India by SEA. Hence the Purchase Invoice gets created at the time of shipment from shipper and the Material Receipt is done only 8-10 weeks later once the material physically reaches us. 

I would like to be able to make "Purchase Receipt" from Purchase Invoice at the click of a button. 

The reason I cannot always do this from the Purchase Order is that the exact weight of material shipped usually varies from the Purchase Order. Since the number of items on the PO may be very large, entering these actual values twice ( once for making P Invoice and once for Purchase Receipt) is very tedious.

**Comment by kennethsequeira** [comment]
Added in v13.
