### ISSUE TITLE
Item variant Attribute Value not show in v13

### ISSUE THREAD

**Issue by blackyzero** [frappe/erpnext#25184]
Hello,

The item Attribute Value doesn't show for each Attribute in creating new variant item.
This also mentioned here 

https://discuss.erpnext.com/t/item-variants-attribute-value-not-show/73392/2

Please show me how to fix the issue.

Thank you.

**Comment by blackyzero** [comment]
I did fresh install v13 today, but still getting same error.

**Comment by blackyzero** [comment]
I deploy a trial on erpnext website, the Attribute value column is also missing, but when click on right arrow, i can see it appears on popup windows, and able to create variant item.

It looks like a bug in current release.

Any help to address this issue?
Thank you.

**Comment by rubberfashion** [comment]
I have same issue on a fresh V13 installation, no customizing:

see also: https://github.com/frappe/erpnext/issues/25037

**Comment by ankush** [comment]
Closed in https://github.com/frappe/erpnext/pull/25310
