### ISSUE TITLE
bug: Taxes and Charges Template - Account Head filter not correct

### ISSUE THREAD

**Issue by nameduser0** [frappe/erpnext#25185]
## Description of the issue
It appears the filters for the Account Head on Taxes and Charges Templates have been implemented the wrong way around:

- Purchase - allows Income accounts
- Sale - allows Expense accounts

## Context information (for bug reports)

**Output of `bench version`**
```
ERPNext: v13.0.0-dev
Frappe Framework: v13.0.0-dev
```

## Steps to reproduce the issue

1. Create new Sales Taxes and Charges Template
2. Try to add Income line (Sales)

### Observed result
Not allowed

### Expected result
Should be allowed

**Comment by deepeshgarg007** [comment]
@nameduser0 There are many cases when these accounts have to be used, not a good idea to restrict every field. Accountants want this flexibility. This is intentional so closing this issue
