### ISSUE TITLE
Incorrect Valuation Rate in Stock Ledger and Repost Item Valuation not working for back dated cancelation [Release v13.0.0]

### ISSUE THREAD

**Issue by ushashmi** [frappe/erpnext#25192]
When any back dated stock transaction is cancelled then repost item valuation get stuck in Queued and stock ledger is not getting updated. I have tested this on latest [Release v13.0.0].

Later if we post any new transaction for the same item in current date then the item valuation gets updated only for the new transaction and stock balance value get corrected however, all the previous transactions which were recorded prior to current transaction still show wrong calculation in stock ledger.

![SL](https://user-images.githubusercontent.com/25934387/113514257-a2856080-957e-11eb-832f-be3922fb2f8c.png)

Moreover the valuation rate is not calculating correctly. Please see in below picture
![STL](https://user-images.githubusercontent.com/25934387/113651272-be822280-96a2-11eb-8da5-758af40a41ed.png)

As visible in above ledger the incoming rate is always 2800 however after some back dated cancelations the repost functionality has calculated wrong valuation rate.

**Comment by deepeshgarg007** [comment]
Cannot verify this, closing this issue

**Comment by rashedpro** [comment]
I'm facing the same issue
