### ISSUE TITLE
Employee Advance can't detect **Company:company:default_currency** ERPNext v13

### ISSUE THREAD

**Issue by nak1090** [frappe/erpnext#25215]
## Description of the issue

Employee Advance can't detect **Company:company:default_currency**

We already set up default currency for this company of Employee

## Context information (for bug reports)

![image](https://user-images.githubusercontent.com/13401911/113665309-716c7380-96d7-11eb-8ca1-4a734e5ad9e5.png)

![image](https://user-images.githubusercontent.com/13401911/113665430-a7a9f300-96d7-11eb-9888-8772277abca0.png)

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1.
2.
3.

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

Installed Apps
ERPNext: v13.x.x-develop () (develop)

Frappe Framework: v13.x.x-develop () (develop)

Browser Chorme - MacOS

**Comment by sagarvora** [comment]
This has been fixed here: https://github.com/frappe/erpnext/commit/2fef245607b801896ef4a8f75b26118571a98747#diff-a8f22b3133683f1dfb4d301a4b460453403302029b5ef8fc4c3e9b0f8fb2fe8f

Are you on the latest `version-13` / `develop` branch?
Do you have any customisation that could be causing this? Check the `Property Setter` list for an entry.

**Comment by nak1090** [comment]
You are right. version-13 is fixed the problem. My erpnext branch is develop

**Comment by nak1090** [comment]
So I have a question related to Employee Advance. I don't see button Return [https://docs.erpnext.com/docs/user/manual/en/human-resources/employee-advance#34-return-amount](url)

![image](https://user-images.githubusercontent.com/13401911/114263985-89fbc700-9a12-11eb-91b9-519d6237cf37.png)

**Comment by sagarvora** [comment]
![Screenshot-2021-04-10-143211](https://user-images.githubusercontent.com/16315650/114264614-93ccfc80-9a09-11eb-98cf-33885cf96f65.png)

As visible in above code, the button shows up only when certain conditions are fulfilled. If you think there's a genuine issue here, feel free to open another Github issue for this topic. Closing this issue.
