### ISSUE TITLE
Migration to v13.0.0 gets stuck in purchase_receipt_status step

### ISSUE THREAD

**Issue by cortopy** [frappe/erpnext#25223]
## Description of the issue

I'm running a migration to erpnext v13.0.0 in kubernetes. Most of the migration k8s job run well but it's stuck at this step:

```
Executing erpnext.patches.v12_0.purchase_receipt_status in development-erpnext.disruptor.london (_af9d306811142f05)
```
This is strange because I'm running this migration in an empty sandbox environment I only use for testing. This instance has no purchase receipts

## Steps to reproduce the issue

1. Upgrade helm chart to 3.0.2
2. Let migration job run

### Expected result

For what I can tell in https://github.com/frappe/erpnext/blob/v13.0.0/erpnext/patches.txt, this is the last step of the migration. It should end the migration

## Additional information

ERPNext using helm chart

**Comment by ankush** [comment]
Hi, @cortopy  the patch is not present in `version-13` branch yet (check the txt file you linked), maybe you're using `develop` branch?

Can you tell me which version you were using before migrating?

**Comment by cortopy** [comment]
hey @ankush , you were right. I did miss an environment variable and it was installing develop. However, the migration is now stuck at `Building search index for mysite.com`

I have

```
Updating DocTypes for frappe        : [========================================] 100%
Updating DocTypes for erpnext       : [========================================] 100%
Updating Dashboard for frappe
Updating Dashboard for erpnext
Updating customizations for Address
Updating customizations for Contact
Building search index for mysite.com
```

**Comment by cortopy** [comment]
tried again with 3.0.1 and all working now. Thanks @ankush
