### ISSUE TITLE
PF & ESIC Deduction in ERPNext.

### ISSUE THREAD

**Issue by sunilsrikumar** [frappe/erpnext#2523]
I have PF & ESIC deduction clarification:

**Current system:**
PF Calculation - ERPNext deduct straight forward 12% of basic salary irrespective of PF CAP as per Indian Govt rule. (Provided if we mention 12% as PF in deduction section)
ESIC Calculation - Same goes in case of ESIC also, system deduct 1.75% of gross salary straight way. (Provided if we mention 1.75% of gross salary as ESIC in deduction section)

**How it should be:**
PF Calculation - As per Indian Govt, PF CAP on basic salary is INR 15,000/. Means, if employee basic salary > INR 15,000 then PF deducation should not be more than INR 1800/Month. System calculate PF wrongly when employee takes any LWP.

ESIC Calculation - As per India Govt, ESIC Cap on gross salary is INR 15,000/-. For example - If employee salary is INR 15,000 and he/she earned INR 7000/ as incentives in that month then total ESIC deduction should be 1.75% of INR 15,001 and rest INR 6,999/- should be ESIC free. 

Sunil

**Comment by KanchanChauhan** [comment]
@sunilsrikumar new Salary Structure in v7
