### ISSUE TITLE
Navbar Settings throws errors when trying to Save

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#25241]
Hi ,

The Navbar Settings in V13 throws errors when trying to Save

![Navbar Error 01](https://user-images.githubusercontent.com/9269337/113987854-c4b10400-9846-11eb-9fda-431694bd50cf.png)

Pls help fix asap!

Thanks plenty

**Comment by kennethsequeira** [comment]
Fixed with: https://github.com/frappe/frappe/pull/12744
