### ISSUE TITLE
Lost Quotation status being overwritten by "Expired"

### ISSUE THREAD

**Issue by shinzuco** [frappe/erpnext#25248]
Quotation and Supplier Quotation marked as lost getting overwritten with expired.

Proposed change
	cond = "qo.docstatus = 1 and qo.status != 'Expired' and qo.valid_till < %s"
to
	cond = "qo.docstatus = 1 and qo.status != 'Expired' and qo.valid_till qo.status != 'Lost' < %s"

**Comment by deepeshgarg007** [comment]
Fixed Via: https://github.com/frappe/erpnext/pull/32005
