### ISSUE TITLE
Sales Invoice Submission Delay Fix Suggestion(version-12)

### ISSUE THREAD

**Issue by m4mousa** [frappe/erpnext#25269]
Hi

*this in version-12

If you have very larg stock transactions, sales invoices submission takes about 40 seconds to submit what makes a problem in POS

I checked the code and figured out that a small modification on:
https://github.com/frappe/erpnext/blob/version-12/erpnext/accounts/general_ledger.py
will solve 80% of the problem

in this part of code:
account_bal, stock_bal, warehouse_list = get_stock_and_account_balance(account,
				gl_map[0].posting_date, gl_map[0].company)

			if gl_map[0].voucher_type=="Journal Entry":

if only the condition:
                        if gl_map[0].voucher_type=="Journal Entry"
goes before calling: get_stock_and_account_balance

the delay of sales invoices submission will go away

**Comment by ankush** [comment]
this is fixed in v13
