### ISSUE TITLE
ERPNext v13 doesnt show phone nummber on imported LEAD

### ISSUE THREAD

**Issue by DmitryGreenLeaf** [frappe/erpnext#25268]
The phone number for the LEAD in the system but not shown on the LEAD page
Only one way you can see lead phone number is print preview
Please find screenshots in the attachment
![image](https://user-images.githubusercontent.com/50123441/114256064-a21c1800-9a0b-11eb-9903-24c641a83bf5.png)
![image](https://user-images.githubusercontent.com/50123441/114256123-0e971700-9a0c-11eb-9c53-1ff43b93c4a6.png)

**Comment by deepeshgarg007** [comment]
<img width="1320" alt="image" src="https://user-images.githubusercontent.com/42651287/198017188-219b39b3-97f1-452a-b971-64ad29213e2e.png">

Visible as a linked contact in the latest layout, closing this issue
