### ISSUE TITLE
stock setting isn't found in POS profile after upgrade to version 13

### ISSUE THREAD

**Issue by barakatsoft** [frappe/erpnext#25272]
the stock setting and stock link was lost after the upgrade to v13 , is there any way to restore it back , I can't update/set the stock per POS now ,it reallty break the sales now 

attaching a screenshot for my POS profile : 
https://drive.google.com/file/d/1j4VTWqqrjIZgHuTutMb6qZwAqo6QkzC3/view?usp=sharing
https://drive.google.com/file/d/1cHnwJZKUFUA2RpPXzZ6e91qhe5z3Sexc/view?usp=sharing

- ERPNext: v13.0.1 (version-13)
- Frappe Framework: v13.0.2 (version-13)

your help is trully appreciated 
thank you

**Comment by amet123** [comment]
Name Series also missing v.13

![pos](https://user-images.githubusercontent.com/326649/114278764-e5e44100-9a4e-11eb-84d0-5a86ebeb2f75.png)
