### ISSUE TITLE
Report on C-Forms.

### ISSUE THREAD

**Issue by adityaduggal** [frappe/erpnext#2527]
There is a custom feature for Indian Taxes for C-Forms, but I see there is no functional report for the same.

Kindly please add the report which we are using with great effect for the C-Form since I am not good enough in making a new app for the same.

https://github.com/adityaduggal/rigpl-erpnext/tree/master/rigpl_erpnext/rigpl_erpnext/report/cforms_analysis

**Comment by SonaliBudhrani** [comment]
+1

**Comment by adityaduggal** [comment]
I think we should close this issue since with the advent of GST this report is anyways going to be redundant and hence I am closing this issue.
No point working on a issue which anyways is going to be obsolete
