### ISSUE TITLE
v13 Loan Management: Applicant Type - 'Member' should be visible with non profit module only

### ISSUE THREAD

**Issue by liyakatalilal** [frappe/erpnext#25274]
Hi,

I'm exploring v13. I have enabled only the Manufacturing module now.

On creating New loan application, in the application type, I do not see 'Member' as a drop-down option. Even though it is listed in the document configuration (customize form >> loan application doctype >> field setting)
![Screenshot 2021-04-11 at 11 10 16 AM](https://user-images.githubusercontent.com/31281816/114293809-d8fb3800-9ab6-11eb-9d11-7ebc62b56887.png)
![Screenshot 2021-04-11 at 11 10 50 AM](https://user-images.githubusercontent.com/31281816/114293813-e1537300-9ab6-11eb-8016-d2464b01524a.png)

But, with the same setting when I look at Loan Security Pledge docType, it shows Member in the applicant type.
![Screenshot 2021-04-11 at 11 11 30 AM](https://user-images.githubusercontent.com/31281816/114293869-76566c00-9ab7-11eb-9408-dbc2c01983ec.png)

The disconnect I see is that it shows in one doctype and doesn't show in another.

Note: I tried this after enabling the 'non-profit' module. Then it showed 'Member' as an option for the Loan Application docType. So, if 'Member' as a dropdown option is linked to the non-profit module it should be visible or not visible accordingly at all the docTypes.

ERPNext: v13.0.1 (version-13)
Frappe Framework: v13.0.2 (version-13)

**Comment by deepeshgarg007** [comment]
The loan Management module app has been moved to a separate repo in the latest version to https://github.com/frappe/lending.
Hence closing this issue
