### ISSUE TITLE
Stock Missing : Version-13 

### ISSUE THREAD

**Issue by sammish** [frappe/erpnext#25288]
Hello, Team
We have an issue in both report (Stock Ledger and Stock Balance ) and Item stock missing.

**Stock Ledger Date : 01-08-2020 to 12-04-2021** 
![image](https://user-images.githubusercontent.com/12432802/114353641-ed523a00-9b75-11eb-8b4e-2683369073c7.png)

**Stock Balance Date : 01-08-2020 to 12-04-2021**
![image](https://user-images.githubusercontent.com/12432802/114353495-c7c53080-9b75-11eb-9dee-3678e2c3b019.png)

**50 QTY Missing** 

![image](https://user-images.githubusercontent.com/12432802/114353797-1d99d880-9b76-11eb-9e52-e8553862a95a.png)

**Comment by jorgeastiazaran** [comment]
Hello, we are having a similar issue in V.13.15.2

After a DN, the whole stock in a warehouse was set to from 60 to 0. Only 1 piece was delivered so the expected new value was 59 instead.
Subsequent DN from such warehouse were issued without restrictions. The stock remained at 0. Additionally, no accounting entries were made for such DN's.

There are other Issues reported but have been closed.
[https://github.com/frappe/erpnext/issues/24444#issue-791688108](https://github.com/frappe/erpnext/issues/24444#issue-791688108)

Please Help!

![image](https://user-images.githubusercontent.com/66883580/144294099-be120ee8-5614-4cf3-84b5-ca4c7d8e4857.png)

**Comment by sharmanakul** [comment]
@ankush can you please check this?

**Comment by Ponyooooo** [comment]
are the items above are all serialized items?
