### ISSUE TITLE
Translation issue in Erpnext v13

### ISSUE THREAD

**Issue by mtogiz** [frappe/erpnext#25285]
## Description of the issue
All translated by Google don't show in application
## Context information (for bug reports)
New version of Erpnext
**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1. Install ERPNext V13
2. Choose vi language
3. Most sentences translated by Google Translate don't show.

### Observed result
App dont' show text translated by Google Translate
### Expected result
App should have an option for user to show translated text by Google.

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by mtogiz** [comment]
Additional information: Many texts (even verified translated texts) weren't loaded in other languages (Guidelines, Help Menu, Account Menu,...) but when do Custom Translation it's changed. So maybe it's coding issues

**Comment by thebachy1** [comment]
Any update?
