### ISSUE TITLE
Invoice Number under Payment Reconciliation is not selectable - v13.0.2

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#25291]
![image](https://user-images.githubusercontent.com/1822868/114374037-e33b3600-9b8b-11eb-92c1-77b6485e6ed0.png)

**Comment by zerodiscount** [comment]
Whole section of unpaid / unreconciled invoices at bottom seems missing.

**Comment by asoral** [comment]
Not just this. Notifications email from doctype field is also not
selectable. This is happening with all select type controls with filters

**Comment by jryandechavez** [comment]
Any update on this issue?

**Comment by muchai** [comment]
In ERPNext: v13.1.0 (version-13), get unreconciled entries does not fill the unreconciled entries,, if you click the button, then click add row, it fills the unreconciled entries. Still, not possible to pick the invoice number.
