### ISSUE TITLE
Service Received but Not Billed. What does it refer to?

### ISSUE THREAD

**Issue by iasb1990** [frappe/erpnext#25302]
Hi,
We’ve recently seen the type of account ‘Service Received but Not Billed’. What does it refer to? What kind of accounts should include? Is this new? Because I can’t find it in the documentation. I assume that it has to be similar than ‘Stock Received but Not Billed’, but as services don’t have stock, I don’t know if it’s right…
Thanks in advance!

**Comment by liyakatalilal** [comment]
It is intermittence stage of PI not received but the liability has accrued. Logically what you saying is right that there is no need to track delivery of service, but if one thinks from another perspective it is a feature. Let says it is a period close time and one has not received invoice from supplier for any reason than estimating liability in books could be helpful from this stage.

Which version you finding this?

**Comment by iasb1990** [comment]
Yes, I though that. I'm using v13.0.0-dev.
Thank you!
