### ISSUE TITLE
Purchase Order - Set Target Warehouse don't find the company which users selected

### ISSUE THREAD

**Issue by nak1090** [frappe/erpnext#25307]
## Description of the issue

In the PO, when we chose another Company, the Source of the warehouse don't find the company chose, it finds the base on the default company

![image](https://user-images.githubusercontent.com/13401911/114495869-0f68bc80-9c49-11eb-8e4a-ccd661169c80.png)

## Context information (for bug reports)

**Output of `bench version`**
```

Installed Apps
ERPNext: v13.0.1 (version-13)

Frappe Framework: v13.0.2 (version-13)
```

## Steps to reproduce the issue

1.
2.
3.

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by sharmanakul** [comment]
hey, based on the company selection the warehouses do get filtered. 

please confirm.
