### ISSUE TITLE
How to change default currency for a company?

### ISSUE THREAD

**Issue by mantis1967** [frappe/erpnext#2531]
Is it possible to do some how?

**Comment by mantis1967** [comment]
OK, I will try to use second suggested workaround. How can I add a new company within existing account?

**Comment by umairsy** [comment]
Hello,

Please check following link for help in managing multiple companies in
ERPNext.

https://erpnext.com/kb/setup/managing-multiple-companies

On Sat, Jan 3, 2015 at 1:36 AM, mantis1967 <notifications@github.com> wrote:

> OK, I will try to use second suggested workaround. How can I add a new
> company within existing account?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/frappe/erpnext/issues/2531#issuecomment-68557602>.
>



-- 
Thanks and Regards,
Umair Sayyed
www.erpnext.com
