### ISSUE TITLE
Woocommerce intergration ERPNext V13

### ISSUE THREAD

**Issue by mtogiz** [frappe/erpnext#25311]
## Description of the issue
After setting up along information to intergrate with woocommerce. Place order, woocommerce successfully async on log status. But nothing happened in ERPNext v13 (no item created, no customer, no sales order, no error log)
## Context information (for bug reports)

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1. Intall ERPNext v13 and Woocommerce  4.8.0 (both are live websites)
2. Setup REST API, Webhook and activate sync feature
3. Place an order on Woocommerce

### Observed result
Woocommerce completed hook async succesfully after placing order but nothing happened in ERPNext v13
### Expected result
Item, Customer, Sales order were created or Error log
### Stacktrace / full error message

```
(paste here)
```

## Additional information
Centos 7. And running frappe docker
OS version / distribution, `ERPNext` install method, etc.

**Comment by ankush** [comment]
Can't reproduce this. Me and a colleague of mine both have successfully set up woocommerce integration just following the docs and it works as expected. 

Maybe looking into woocommerce logs will help.
