### ISSUE TITLE
Job Card, start time and end time is "garbage"

### ISSUE THREAD

**Issue by grynn-in** [frappe/erpnext#25322]
## Description of the issue
Job Card is showing From time and to time in garbled format. 
![image](https://user-images.githubusercontent.com/23282682/114621057-8aaf8a00-9cac-11eb-84b7-f08734618c71.png)

## Context information (for bug reports)

**Output of `bench version`**
```
Installed Apps
ERPNext: v13.0.1 (HEAD)
Frappe Framework: v13.0.2 (HEAD)
Nextcloud Integration: v0.0.1 (HEAD)
PDF on Submit: v0.0.1 (HEAD)
```

**Comment by sharmanakul** [comment]
hey, I haven't seen this on the later versions. 

Closing this for now.

**Comment by ankush** [comment]
Yes, this got fixed in framework in last release.
