### ISSUE TITLE
Unable Import - Bank Statement Import

### ISSUE THREAD

**Issue by iasb1990** [frappe/erpnext#25320]
Hi,

I'm trying to import a bank statement using New Bank Statement Import tool, but it fails. It recognizes the fields, 

![Captura de Pantalla 2021-04-13 a la(s) 15 51 48](https://user-images.githubusercontent.com/66756148/114605771-cf1d3480-9c70-11eb-8d63-cb0dea1aeafc.png)

then I went to 'Start Import' but it doesn't import, 

![Captura de Pantalla 2021-04-13 a la(s) 15 57 25](https://user-images.githubusercontent.com/66756148/114606011-1dcace80-9c71-11eb-883f-65389e5e40af.png)

and there isn't any log error. It's seems like it doesn't import the file.

ERPNext: v13.0.1 (version-13)

Frappe Framework: v13.0.2 (version-13)

Thanks in advance!

**Comment by deepeshgarg007** [comment]
@iasb1990 Please check if there are any errors in the browser console and then add the traceback here and reopen the issue if it still persists
