### ISSUE TITLE
Payment Entry ; "Get Outstanding Invoice" Duplicating Invoice in Invoice table : Version-13

### ISSUE THREAD

**Issue by sammish** [frappe/erpnext#25333]
Hello , Team..

Payment Entry Get Outstanding Invoice Duplicating Invoice in Invoice table : Version-13
ERPNext: v13.0.1 (HEAD)
Frappe Framework: v13.0.2 (HEAD)

![image](https://user-images.githubusercontent.com/12432802/114692892-bb7dd680-9d21-11eb-8776-3eedae5d8b0f.png)

**Comment by deepeshgarg007** [comment]
@sammish Please mention the steps to replicate the issue and then reopen if this still persists
