### ISSUE TITLE
pylint is reporting Bad Indentation problem

### ISSUE THREAD

**Issue by guilmori** [frappe/erpnext#25341]
Linter pylint is reporting a tons of Bad Indentation problem on erpnext standard .py files.
I understand this must have something to do with spaces vs tabs indentation config.
Any insight on how to fix this ?

![image](https://user-images.githubusercontent.com/9451512/114768971-9005e680-9d37-11eb-83e2-0444209e9ef0.png)

**Comment by ankush** [comment]
Add/update this in your pylint config.

```
indent-string='\t'
```

**Comment by guilmori** [comment]
> Add/update this in your pylint config.
> 
> ```
> indent-string='\t'
> ```

Thanks, adding this to the .vscode/settings.json did the trick.
`"python.linting.pylintArgs": ["--indent-string", "'\t'"]`
![image](https://user-images.githubusercontent.com/9451512/114865224-f2a2c500-9dbf-11eb-9ddf-7ecfd6744743.png)

Could this be added to the frappe_docker development configuration ?
So that it come pre-configured for erpnext code source style, and every new developer won't have to manually configure this.

**Comment by ankush** [comment]
@guilmori I'll update pylintrc file in this project. It doesn't seem to represent the current formatting convention we follow

https://github.com/frappe/erpnext/blob/develop/.pylintrc
