### ISSUE TITLE
Company Page error erpnext 13.0.2

### ISSUE THREAD

**Issue by bluwebz** [frappe/erpnext#25342]
after upgrading 12 to 13 company pages showing like this. 
![Fotocart (fotocart com bd)](https://user-images.githubusercontent.com/10896324/114808767-ba54b400-9dca-11eb-8df7-a9bb6bcc2568.png)

**Comment by kennethsequeira** [comment]
Closing as issue cannot be replicated in 
ERPNext: v13.9.2 (HEAD)
Frappe Framework: v13.9.1 (HEAD)
