### ISSUE TITLE
Selecting a company doesn't filter for company details in a multi-company environment - v13

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#25357]
For the company filters to work, one has to set default company under user defaults.

Also, still on multi-company environment, if you setup default accounts for different companies, if a user is limited by user permissions to one of the companies, the system raises a user not permitted error.

**Comment by deepeshgarg007** [comment]
@muchai We will need more specifics on this to investigate further, what all permission were given, while accessing what doctype you get the error, please elaborate and reopen the issue.

**Comment by muchai** [comment]
@deepeshgarg007 Closing this is in order. Think it's been fixed by now. Just have one related to user permissions for a company. But will raise it as a separate query.
