### ISSUE TITLE
Filtering while in calendar view doesn't work for Shift Assignment

### ISSUE THREAD

**Issue by ikslavok** [frappe/erpnext#25363]
## This is making this good module unusable. Imagine if you have 3 shops and 12 workers. It's a mess to see who is working when.

**Output of `bench version`**
```
erpnext 13.0.1
frappe 13.0.2
```

## Steps to reproduce the issue

1. Go to HR > Shift Assignment
2. Change the view to the calendar
3. Try to filter results
4. Fail

Other modules work fine. So I think it is ERPNext specific.

**Comment by daanlenaerts** [comment]
I'm noticing the same issue appear in the Shift Assignment module.

**Comment by ruchamahabal** [comment]
Fixed https://github.com/frappe/erpnext/pull/30752
