### ISSUE TITLE
Help links 404

### ISSUE THREAD

**Issue by ghost** [frappe/erpnext#25366]
Some links under Help dropdown(while doc is open - eg. Item) is 404 - eg. link for help about Item Variants - https://docs.erpnext.com/docs/user/manual/en/stock/item/item-variants

![ew](https://user-images.githubusercontent.com/43913022/114987893-facd3400-9e95-11eb-8bb3-f5a5f342c73e.PNG)

**Comment by kennethsequeira** [comment]
should be fixed with: https://github.com/frappe/erpnext/pull/27860
