### ISSUE TITLE
Version 13 Update Bank Statement Errors

### ISSUE THREAD

**Issue by azeemanwar** [frappe/erpnext#25387]
Hi,
After the upgrade from Version 12 to Version 13, following links gives the error:

1. Bank Statement Transaction Entry
2. Bank Statement Settings

This is the error messages:
**Bank Statement Transaction Entry**

Not found
Page bank-statement-transaction-entry not found
The resource you are looking for is not available

**Bank Statement Settins**

Not found
Page bank-statement-settings not found
The resource you are looking for is not available

**Comment by Islammoustafa95** [comment]
Yes and you will get errors if you try to customize the accounting shortcuts 
No way to resolve it

**Comment by azeemanwar** [comment]
Thank you for your response.
When the fix is expected, need to customize the Workspace.

Regards,
Azeem Anwar
050 476 6735

**Comment by Islammoustafa95** [comment]
This issue appears only if you are using the administrator account 
using another account can let you customize workspace with no issue
