### ISSUE TITLE
Currency sign

### ISSUE THREAD

**Issue by ChaosWeb** [frappe/erpnext#2540]
currency sign on prices converted to home currency shows the same. example usd shows peso sign also.
![capture](https://cloud.githubusercontent.com/assets/4564219/5591846/acd2073e-91cd-11e4-942c-aaff4bb6a66b.PNG)

**Comment by nabinhait** [comment]
Are you still getting this issue?

**Comment by cgpurbaugh** [comment]
This is fixed.
