### ISSUE TITLE
Can´t add Webhook data because Fieldname List is empty

### ISSUE THREAD

**Issue by JanMrlth** [frappe/erpnext#25403]
## Description of the issue
I want to pass a Fieldname to a Webhook. 
The Webhook is created for an ITEM. 
In the Fieldname a empty dropdown list appears, that does not allow me to select anything. 

## Context information (for bug reports)

**Output of `bench version`**
erpnext 13.0.1
frappe 13.0.2

## Steps to reproduce the issue

1. Create or Update a Webhookl
2. try to add a Field in Webhook Data

### Observed result
![image](https://user-images.githubusercontent.com/6159907/115366656-ce7f2380-a1c5-11eb-8fbb-58be94ed3017.png)

### Expected result
A list with all the Field Names should appear and let me choose one.

**Comment by ankush** [comment]
This works fine now. Make sure you've selected a doctype first as it depends on it to fetch the fields.
