### ISSUE TITLE
Role based workspace customization

### ISSUE THREAD

**Issue by aschl** [frappe/erpnext#25418]
Workspaces can currently only be customized for individual users but not centrally for different roles. 
This issue has been raised and discussed previously on the forum: https://discuss.erpnext.com/t/role-based-desk-workspace-assign/63208
Quote: "We can’t expect every employee to customize their own workspaces but it would be very helpful if this could be done centrally for the employees (how might be too non-technical to do this) via roles."

It seems to be possible to adjust this via customization in the developer mode (?), however when hosting e.g. with ERPnext/Frappe-cloud this is not straight forward. Can this be activated so an admin/system manager can adjust the workspace doctype?

**Comment by blewsky** [comment]
Why are issues closed if the maintainer team is too slow to validate? This doesn't seem to be a legit reason to me. I think this is besides the point of committing issues.

**Comment by phifa** [comment]
can we reopen this?
