### ISSUE TITLE
Missing Discount Section

### ISSUE THREAD

**Issue by siddjellali** [frappe/erpnext#25427]
## Description of the issue
Discount and Margin are unavailable.
Discount and Margin tab are in DocType “Sales Order Item” but when i try to use it, section is hidden by CSS. 
![image](https://user-images.githubusercontent.com/3965823/115591925-f0b29780-a2d2-11eb-8996-d2bb64dd3ebb.png)
![image](https://user-images.githubusercontent.com/3965823/115591938-f4461e80-a2d2-11eb-84f5-3a9ddd7bfad6.png)

**Output of `bench version`**
```
ERPNext: v13.0.2 (version-13)
Frappe Framework: v13.0.3 (version-13)
```

## Steps to reproduce the issue

1. Create a Sales Order
2. Create a row in Article tab
3. Edit a row 
4. Discount tab is unavaible

### Observed result

Discount tab is hidden by CSS.

### Expected result

Display Discount tab.

**Comment by siddjellali** [comment]
Any idea ? Any lead to help me please ?

**Comment by TecHive-LLC** [comment]
Make sure the item has a list price in the list that you are using.
https://discuss.erpnext.com/t/no-line-wise-discount-available/61820/3

**Comment by siddjellali** [comment]
don't use erpnext anymore.
thanks.

**Comment by backendoadmin** [comment]
Don't forget to set the correct valid from date on price/pricelist as well!
