### ISSUE TITLE
'1118 Row size too large' mysql during migration for `tabSales Invoice`

### ISSUE THREAD

**Issue by shantanoo** [frappe/erpnext#25434]
While upgrading from v12 to v13, ran `bench migrate`. Got following error.

    pymysql.err.InternalError: (1118, 'Row size too large. The maximum row size for the used table type, 
    not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change
    some columns to TEXT or BLOBs')

Table name `tabSales Invoice`.  Tried changing `varchar` to `text` in that table, but running `bench migrate` changes the `text` columns back to `varchar` and migration fails.

**Comment by ankush** [comment]
This is most likely due to extra fields added using customization.

Some ways to handle this: https://docs.erpnext.com/docs/user/manual/en/customize-erpnext/articles/maximum-number-of-fields-in-a-form

**Comment by ankush** [comment]
if you can't revert to old version and fix it, then you might have to change the custom field in `tabCustom Field` so the changes are not reverted during migration.

**Comment by shantanoo** [comment]
@ankush is there a easy way to find out which fields were added during customisation? What is the form field type for creating text field? For `Data` it is using `VARCHAR(140)`.

**Comment by shantanoo** [comment]
Modifying `length` value in `tabCustom Field` table, and modifying the column in the `tabSales Invoice` seem to solve the issue for now.
