### ISSUE TITLE
UOM Conversions In Sales Order, Sales Invoice, Delivery Note

### ISSUE THREAD

**Issue by sbkolate** [frappe/erpnext#2544]
UOM Conversions Facility for Selling, which is allready present in Purchase.

**Comment by wsxedcr** [comment]
I need this feature too, how much would it cost to get this done?

**Comment by PawanMeh** [comment]
@wsxedcr , a contribution of $200 would enable us to make these changes, would it be possible for you to raise this amount?

**Comment by Arundhatii** [comment]
UI Mock up
![new mockup 1](https://cloud.githubusercontent.com/assets/20164097/23895683/9b8ee9ec-08cc-11e7-81c3-8294e9bec388.png)

**Comment by umairsy** [comment]
feature added in version 8. Under testing. To be released soon.
