### ISSUE TITLE
Serial numbers and stock management cannot be activated

### ISSUE THREAD

**Issue by markusrock** [frappe/erpnext#25458]
## Description of the issue
If an article already has a stock movement, "Has serial number" cannot be activated as well as the stock management. When saving the article, the message appears that no changes have been made to the document.

## Context information (for bug reports)

ERPNext: v13.1.0 (HEAD)
Frappe Framework: v13.1.0 (HEAD)
Nextcloud Integration: v0.0.1 (HEAD)

## Steps to reproduce the issue

1. import new article from excel sheet with initial stock >0
2. after import check the box "has serial number"

### Observed result

No change happened

### Expected result

Make article has article with serial number needed

## Additional information

hosted on frappecloud

**Comment by wojosc** [comment]
in Item you'll have to have "Stock" aktivated to be able to use serial numbers:
![grafik](https://user-images.githubusercontent.com/22279621/115877798-21680d80-a448-11eb-9f23-0aa452323263.png)

**Comment by markusrock** [comment]
Sorry, forgot to mention in the ticket itself. The title says it already - I've got the same message when trying to activate the stock management: 
![Screenshot 2021-04-23 152919](https://user-images.githubusercontent.com/73632724/115878314-f07fdc80-a437-11eb-8b3b-aaaf55c28404.jpg)

**Comment by wojosc** [comment]
"If an article already has a stock movement," what do you mean by this? Once stock movement has happend with that specific item you will not be able to set serial or "Lager verwalten" anymore. To change that you would have to cancel all delivery notes etc.

**Comment by markusrock** [comment]
Thanks for the feedback. It seems that some items are now no longer a "serial number item" with us, even though they used to be. Perhaps this was due to the beta version. Since I don't have any traceable info on this, I'll close the ticket and open a new one should I come across anything usable.
