### ISSUE TITLE
rate is not populated properly in sales order, delivery note and sales invoice

### ISSUE THREAD

**Issue by kurogin2020** [frappe/erpnext#25464]
with version 13,
1. mulitple price list present (e.g. stardard selling and selling B)
2. There’s no pricing rule created.
3. somehow rate remained at default (standard selling), even when a specific pricelist is already set at customer settings or selected at document level.

running version: 
ERPNext: v13.1.0 (version-13)
Frappe Framework: v13.1.2 (version-13)

could this be a possible bug ? 

![price list rate 1a](https://user-images.githubusercontent.com/83089542/115913281-9a905080-a49a-11eb-9fec-36d858092b98.png)
![price list rate 1b](https://user-images.githubusercontent.com/83089542/115913298-9e23d780-a49a-11eb-96f5-13419e79e8d8.png)
![price list rate 1c](https://user-images.githubusercontent.com/83089542/115913301-9f550480-a49a-11eb-94cd-aebf49d3e054.png)

**Comment by muchai** [comment]
Assign price list to each customer.

Or customer group, haven't tested this.

The bug is that, the system doesn't pick prices based on price list setup on selling settings.

**Comment by kurogin2020** [comment]
I have the assigned the price list for the particular customer. unfortunately, it didn't work. 
![price list rate 2a](https://user-images.githubusercontent.com/83089542/115971033-6d15d680-a570-11eb-9650-b543593f9381.png)
![price list rate 2b](https://user-images.githubusercontent.com/83089542/115971039-7141f400-a570-11eb-8812-3b5dadb1a962.png)
![price list rate 2c](https://user-images.githubusercontent.com/83089542/115971040-71da8a80-a570-11eb-8697-48c4c57adbc5.png)

**Comment by szufisher** [comment]
confirm the same issue on 
ERPNext: v13.1.0 (version-13)
Frappe Framework: v13.1.2 (version-13)

**Comment by kurogin2020** [comment]
This issue is fixed with the latest update:

ERPNext: v13.1.1 (version-13)
Frappe Framework: v13.1.2 (version-13)
