### ISSUE TITLE
ERPNEXT V13 Workspace List Save

### ISSUE THREAD

**Issue by michaelkaraz** [frappe/erpnext#25472]
There is no save button for workspace editing?

![Capture](https://user-images.githubusercontent.com/6880913/115988908-f4d50280-a5bb-11eb-93d0-a242cfef2125.PNG)

**Comment by nithin933** [comment]
You have to enable developer mode for that site. go into bench folder and punch in `bench set-config developer_mode 1
`

ctrl+shift+r

**Comment by shinzuco** [comment]
You have to enable developer mode for that site. go into bench folder and punch in bench set-config developer_mode 1

ctrl+shift+r

**Comment by shinzuco** [comment]
You have to enable developer mode for that site. go into bench folder and punch in bench set-config developer_mode 1

ctrl+shift+r
