### ISSUE TITLE
issue with installing the requirements.txt

### ISSUE THREAD

**Issue by Kevin-Justin** [frappe/erpnext#25496]
![image](https://user-images.githubusercontent.com/75354764/116331676-d9a80400-a802-11eb-9f7b-ece29aeb6231.png)

**Comment by ankush** [comment]
Hi @Kevin-Justin 

If you were trying to install using `pip install -r requirements.txt` then it will not work. Please follow the installation guide here: https://frappeframework.com/docs/user/en/installation or consider using docker: https://github.com/frappe/erpnext#containerized-installation
