### ISSUE TITLE
Latest update cause error in generating form (Sales Order, Purchase Order, Sales Invoice and Purchase Invoice)

### ISSUE THREAD

**Issue by gohyc** [frappe/erpnext#2550]
Please see the screenshot.
![screen shot 2015-01-05 at 9 01 27 am](https://cloud.githubusercontent.com/assets/7393911/5608288/f1933f0c-94b9-11e4-9c7d-edb9819aee17.png)

**Comment by gohyc** [comment]
I found the problem.

sales_common.js and purchase_common.js

this.frm.doc.grand_total_export = flt(tax_count ?
                        flt(this.frm.doc.grand_total / this.frm.doc.conversion_rate) : this.frm.doc.net_total_export);

There is no ")" at the end.

**Comment by nabinhait** [comment]
fixed it via #2551
