### ISSUE TITLE
Stock Reconciliation Opening balancing Submit Error

### ISSUE THREAD

**Issue by waheedomar017** [frappe/erpnext#25512]
## Context information (for bug reports)

**Output of `bench version`**
```
(13)
```

## Steps to reproduce the issue

1.
2.
3.

### Stacktrace / full error message

```
(When i try to submit stock reconciliation entry for (Opening Balance)
i get this error 

Server Error 
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 's Veh WH - IAL' and item_code in ('09-AN'))\n\t\t\tand timestamp(posting_date, po...' at line 4")
```
Please Resolve this issue ASAP.

## Additional information

OS version Ubuntu 20.04 / distribution, `ERPNext`  easy installed.

**Comment by ankush** [comment]
Can you open the browser console and share full traceback?

howto: https://balsamiq.com/support/faqs/browserconsole/
