### ISSUE TITLE
V13 Employee Information Page not Available

### ISSUE THREAD

**Issue by usman-alikhan** [frappe/erpnext#25527]
There is a standard report “Employee Information” but its not available when try to open.

![image](https://user-images.githubusercontent.com/81390347/116657532-05b0ba00-a9a8-11eb-9c53-f3f39966a89b.png)

**Comment by onlinebizsoft** [comment]
@usman-alikhan where is this menu item located at?

**Comment by onlinebizsoft** [comment]
Try to declare the issue with detail like this
https://github.com/frappe/hrms/issues/108

**Comment by usman-alikhan** [comment]
This is in HR Module at bottom. Other Reports section
![image](https://user-images.githubusercontent.com/81390347/117263996-3db67200-ae6c-11eb-9444-2249a28d11d6.png)
