### ISSUE TITLE
Payment Reconciliation not working in version 13

### ISSUE THREAD

**Issue by mubeenmazhar** [frappe/erpnext#25525]
After updating to version 13, payment reconciliation is not working properly. Pressing “Get Unreconciled Entries” neither load the invoices nor Payment entries. But going back to the page (without reloading it) shows the both invoices and payments. Even then it doesn’t load payments in DROPDOWN section as shown in the picture below.

System: frappe.cloud
ERPNext: v13.1.1 (HEAD)
Frappe Framework: v13.1.2 (HEAD)

![Untitled](https://user-images.githubusercontent.com/47884718/116599457-90aa9980-a941-11eb-8789-f3a0ea305379.png)

**Comment by jryandechavez** [comment]
We are also experiencing this issue
