### ISSUE TITLE
Stock Projected Quantity - Ability to drill down into qty details

### ISSUE THREAD

**Issue by guilmori** [frappe/erpnext#25520]
In the Stock Projected Quantity report.
https://docs.erpnext.com/docs/user/manual/en/stock/projected-quantity

It would be great if the qty cells would be clickable to show the quantity details.

For exemple, clicking on 'Actual Qty' cell would list qty of this item in each warehouses.
'Requested Qty' would list qty of this item in each material requests.
'Ordered Qty' would list qty of this item in each purchase orders.
etc...

**Comment by szufisher** [comment]
great feature to have
