### ISSUE TITLE
Bank Reconciliation Tool Error

### ISSUE THREAD

**Issue by iasb1990** [frappe/erpnext#25523]
Hi,
We’re having some inconvenients with bank reconciliation tool.
First, it doesn’t work if you’re importing with goggle sheet. It recognizes the field, but doesn’t import the file.

![image](https://user-images.githubusercontent.com/66756148/116579896-3c73cb00-a8e9-11eb-8de6-4cb70fc7dc55.png)

![image](https://user-images.githubusercontent.com/66756148/116579922-439ad900-a8e9-11eb-9ed5-dcf88bb3fc01.png)

And this is all.

Error log:

Traceback (most recent call last):
File “/home/diamo/Frappe/apps/frappe/frappe/utils/background_jobs.py”, line 100, in execute_job
method(**kwargs)
File “/home/diamo/Frappe/apps/erpnext/erpnext/accounts/doctype/bank_statement_import/bank_statement_import.py”, line 100, in start_import
import_file = ImportFile(“Bank Transaction”, file = import_file_path, import_type=“Insert New Records”)
File “/home/diamo/Frappe/apps/frappe/frappe/core/doctype/data_import/importer.py”, line 331, in init
frappe.throw(_(“Invalid template file for import”))
File “/home/diamo/Frappe/apps/frappe/frappe/init.py”, line 433, in throw
msgprint(msg, raise_exception=exc, title=title, indicator=‘red’, is_minimizable=is_minimizable, wide=wide, as_list=as_list)
File “/home/diamo/Frappe/apps/frappe/frappe/init.py”, line 412, in msgprint
_raise_exception()
File “/home/diamo/Frappe/apps/frappe/frappe/init.py”, line 366, in _raise_exception
raise raise_exception(msg)
frappe.exceptions.ValidationError: Invalid template file for import

It’s strange because model template have been downloaded from the ERP. The only way that it works is importing files from the device. Both images are exactly the same, but the difference is that from my device it works and from google sheet doesn’t.
After that,

![image](https://user-images.githubusercontent.com/66756148/116580095-6d540000-a8e9-11eb-9814-fb938a27fd1a.png)

The statement from my device has been successfully imported, but I couldn’t find the way to do the reconciliation. The only option I have is “go to transactions list” button, that shows this

![image](https://user-images.githubusercontent.com/66756148/116580029-5c0af380-a8e9-11eb-8a58-ee0fe88b20ef.png)

So, I’ve imported the statement, but I can’t find the way to reconcile automatically those. I can do it individually, but it it’s practical if you have a lot of transactions.

Is anybody using this? Could you explain me how they do, and if I’m doing something wrong or if it’s a bug?

Installed Apps
ERPNext: v13.1.0 
Frappe Framework: v13.1.0 

Thanks in advance!

**Comment by hasnain2808** [comment]
Thanks for sharing the bug report

The issue was replicated. The reason seems that the addition of the bank account column to the uploaded file is breaking when the source is a google sheet.

A fix will be raised soon by someone
