### ISSUE TITLE
Errors With Salary Submit from Payroll Entry

### ISSUE THREAD

**Issue by usman-alikhan** [frappe/erpnext#25548]
in ERPNext When pressing the “submit Salary slip” button on payroll entry, get error that party is required for payable / receivable account. This is resolved if no account type is selected for the ledger account. The salary payable ledger account is a payable account and this error shouldn't arise.

Also, if FY is added as a custom mandatory field in Journal Entry then submitting salary slip from payroll entry gives error that FY is not filed. Although default fiscal year is auto populated when directly opening the Journal Entry. But in this case when journal entry is passed by system using payroll entry, it somehow does not get populated.

![image](https://user-images.githubusercontent.com/81390347/116796357-318d8600-aaf5-11eb-8c7c-c865e7b8cdc4.png)

**Comment by usman-alikhan** [comment]
Relates to V13

**Comment by onlinebizsoft** [comment]
@usman-alikhan please describe the issue in detail like this to get more attention frappe/hrms#108

**Comment by kennethsequeira** [comment]
@usman-alikhan this happens generally when the account in question is of type Payable or Receivable. 

If that is removed from the account and the payroll is re-run, the error should be gone.
