### ISSUE TITLE
Last Selling Price

### ISSUE THREAD

**Issue by aambernath** [frappe/erpnext#2554]
Hi,

```
 As a feature being requested by many in the SME trading domain in and around UAE, I would like to develop the "Last Selling Price" functionality.
```

It would simply display the last sold price for an item for the specific customer. There is another button which upon clicking would show all the items sold to customer and its prices so the user can evaluate the "range of pricing" issued to the specific customer.This is a real world requirement for many here and I would like to know what would be the best way to implement this? Should it be simply a field in the item list? or is there a better way to bring about this functionality. I haven't developed earlier for ERPNEXT but have decided this would be the first and the one I learn with.

  Please advice

**Comment by anandpdoshi** [comment]
This could be done using script report. As an example, see Accounts
Receivable Report:
https://github.com/frappe/erpnext/tree/develop/erpnext/accounts/report/accounts_receivable

**Comment by Arundhatii** [comment]
Seems to be resolved by the suggested custom script, hence closing the issue.
