### ISSUE TITLE
SQL report don't exclude characters

### ISSUE THREAD

**Issue by thejoe8495** [frappe/erpnext#25553]
## Description of the issue
There is an error in SQL Syntax. The script don't exclude the ' character in file: 
https://github.com/frappe/erpnext/blob/a2fcca85a59c590b56f6b98f0fca9206018c43bf/erpnext/stock/doctype/delivery_note/delivery_note.py#L470
I can't find the file where the company is added

## Context information (for bug reports)

**Output of `bench version`**
erpnext 13.2.0
frappe 13.2.0

## Steps to reproduce the issue

1. Fresh install, create a company with an ' like Test's company
2. Create a Delivery Note 
3. Try to create a Invoice with this Delivery note (from delivery note or add Items to an Invoice)

### Observed result
Error in SQL Syntax

### Expected result
Add Items to a existing Invoice or create a new Invoice

### Stacktrace / full error message
"Syntax error in query:",
   "SELECT sum(actual_qty) from \n\t\t(`tabBin` INNER JOIN `tabWarehouse` ON `tabBin`.warehouse = `tabWarehouse`.name) \n\t\tWHERE `tabWarehouse`.company = 'Test's company' and `tabBin`.item_code = 'fernwartung'",
   "Traceback (most recent call last):\n  File \"/opt/bench/erpnext/apps/frappe/frappe/app.py\", line 68, in application\n    response = frappe.api.handle()\n  File \"/opt/bench/erpnext/apps/frappe/frappe/api.py\", line 54, in handle\n    return frappe.handler.handle()\n  File \"/opt/bench/erpnext/apps/frappe/frappe/handler.py\", line 31, in handle\n    data = execute_cmd(cmd)\n  File \"/opt/bench/erpnext/apps/frappe/frappe/handler.py\", line 67, in execute_cmd\n    return frappe.call(method, **frappe.form_dict)\n  File \"/opt/bench/erpnext/apps/frappe/frappe/__init__.py\", line 1175, in call\n    return fn(*args, **newargs)\n  File \"/opt/bench/erpnext/apps/frappe/frappe/model/mapper.py\", line 36, in make_mapped_doc\n    return method(source_name)\n  File \"/opt/bench/erpnext/apps/erpnext/erpnext/stock/doctype/delivery_note/delivery_note.py\", line 470, in make_sales_invoice\n    doc = get_mapped_doc(\"Delivery Note\", source_name, {\n  File \"/opt/bench/erpnext/apps/frappe/frappe/model/mapper.py\", line 127, in get_mapped_doc\n    postprocess(source_doc, target_doc)\n  File \"/opt/bench/erpnext/apps/erpnext/erpnext/stock/doctype/delivery_note/delivery_note.py\", line 425, in set_missing_values\n    target.run_method(\"set_missing_values\")\n  File \"/opt/bench/erpnext/apps/frappe/frappe/model/document.py\", line 858, in run_method\n    out = Document.hook(fn)(self, *args, **kwargs)\n  File \"/opt/bench/erpnext/apps/frappe/frappe/model/document.py\", line 1147, in composer\n    return composed(self, method, *args, **kwargs)\n  File \"/opt/bench/erpnext/apps/frappe/frappe/model/document.py\", line 1130, in runner\n    add_to_return_value(self, fn(self, *args, **kwargs))\n  File \"/opt/bench/erpnext/apps/frappe/frappe/model/document.py\", line 852, in <lambda>\n    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)\n  File \"/opt/bench/erpnext/apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py\", line 406, in set_missing_values\n    super(SalesInvoice, self).set_missing_values(for_validate)\n  File \"/opt/bench/erpnext/apps/erpnext/erpnext/controllers/selling_controller.py\", line 49, in set_missing_values\n    self.set_price_list_and_item_details(for_validate=for_validate)\n  File \"/opt/bench/erpnext/apps/erpnext/erpnext/controllers/selling_controller.py\", line 96, in set_price_list_and_item_details\n    self.set_missing_item_details(for_validate=for_validate)\n  File \"/opt/bench/erpnext/apps/erpnext/erpnext/controllers/accounts_controller.py\", line 350, in set_missing_item_details\n    ret = get_item_details(args, self, for_validate=True, overwrite_warehouse=False)\n  File \"/opt/bench/erpnext/apps/erpnext/erpnext/stock/get_item_details.py\", line 89, in get_item_details\n    out.update(get_bin_details(args.item_code, out.warehouse, args.company))\n  File \"/opt/bench/erpnext/apps/erpnext/erpnext/stock/get_item_details.py\", line 932, in get_bin_details\n    bin_details['company_total_stock'] = get_company_total_stock(item_code, company)\n  File \"/opt/bench/erpnext/apps/erpnext/erpnext/stock/get_item_details.py\", line 936, in get_company_total_stock\n    return frappe.db.sql(\"\"\"SELECT sum(actual_qty) from\n  File \"/opt/bench/erpnext/apps/frappe/frappe/database/database.py\", line 152, in sql\n    self._cursor.execute(query)\n  File \"/opt/bench/erpnext/env/lib/python3.8/site-packages/pymysql/cursors.py\", line 148, in execute\n    result = self._query(query)\n  File \"/opt/bench/erpnext/env/lib/python3.8/site-packages/pymysql/cursors.py\", line 310, in _query\n    conn.query(q)\n  File \"/opt/bench/erpnext/env/lib/python3.8/site-packages/pymysql/connections.py\", line 548, in query\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\n  File \"/opt/bench/erpnext/env/lib/python3.8/site-packages/pymysql/connections.py\", line 775, in _read_query_result\n    result.read()\n  File \"/opt/bench/erpnext/env/lib/python3.8/site-packages/pymysql/connections.py\", line 1156, in read\n    first_packet = self.connection._read_packet()\n  File \"/opt/bench/erpnext/env/lib/python3.8/site-packages/pymysql/connections.py\", line 725, in _read_packet\n    packet.raise_for_error()\n  File \"/opt/bench/erpnext/env/lib/python3.8/site-packages/pymysql/protocol.py\", line 221, in raise_for_error\n    err.raise_mysql_exception(self._data)\n  File \"/opt/bench/erpnext/env/lib/python3.8/site-packages/pymysql/err.py\", line 143, in raise_mysql_exception\n    raise errorclass(errno, errval)\npymysql.err.ProgrammingError: (1064, \"You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 's company' and `tabBin`.item_code = 'fernwartung'' at line 3\")\n"

## Additional information

OS version / distribution, `ERPNext` install method, etc.
Version 13 v13.2.0

PS: Sorry for the stacktrace, the mailreport is also broken ;)

**Comment by ankush** [comment]
This is the problematic query: 

https://github.com/frappe/erpnext/blob/704ec132b7b5a8353906f77332496a1f92ba27c6/erpnext/stock/get_item_details.py#L935-L939 

The solution would be similar to: https://github.com/frappe/erpnext/pull/25167 i.e. remove string formatting and pass values to `frappe.db.sql`.

Reference: https://frappeframework.com/docs/user/en/api/database#frappedbsql

**Comment by thejoe8495** [comment]
It's my second ;) I found all missing mysql excapes with my companyname ;)
