### ISSUE TITLE
Bugs on Accounts Receivable Reports

### ISSUE THREAD

**Issue by fnrfarid** [frappe/erpnext#25550]
In Accounts Receivable reports, if we filter by Sales Person, for a customer, where the sales person has been changed, then the report acts differently. 

For example, Sales Person `Farid` was set to this customer `FARID ENTERPRISE` , and the outstanding amount is 1,325. Later the salesperson is changed to `Mahdi` and the outstanding amount is 137,325 where the amount 1,325 is already included. 

So if we are extract outstanding report by salesperson, this creates a huge confusion cause the outstanding amount is already included to some other report.

My suggestion here would be, to show outstanding by their last salesperson only.

![image](https://user-images.githubusercontent.com/31440952/116806332-0d11c800-ab4e-11eb-9025-0ef1222e10c5.png)
![image](https://user-images.githubusercontent.com/31440952/116806335-113de580-ab4e-11eb-955f-bfdd56544036.png)

**Comment by mubeenmazhar** [comment]
Upon selecting cost center paid amount turns incorrect [https://github.com/frappe/erpnext/issues/26235](26235)

**Comment by deepeshgarg007** [comment]
@fnrfarid Updating the Sales Partner in Customer master won't update the values in the already created Sales Invoice. The report considers the value of Sales Invoices hence you are facing this. Don't think much can be done here. Closing this issue
