### ISSUE TITLE
Select Appraisal template in Appraisal issue

### ISSUE THREAD

**Issue by ashrafulratul** [frappe/erpnext#2556]
I am going to create a new appraisal. when i am select a new appraisal template `Appraisal template goal` data set in `Goal` section. It's okay but if i select the same appraisal template second time or select some other template then previous records are not removed from `Goal` section. Which are not set in appraisal template.

**Comment by yashodhank** [comment]
@ashrafulratul are you still facing this issue? I will reopen if your explain bit more details with screenshots. Thanks
