### ISSUE TITLE
POS Not Working in v13.0.2 | N

### ISSUE THREAD

**Issue by peete-rx** [frappe/erpnext#25584]
## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 13.2.0
frappe 13.2.0
posawesome 1.1.0
```

## Steps to reproduce the issue

1. Create a new POS profile in the Retail Domain
2. Search for "Point of Sale" 
3. Click on "Open Point of Sale"

### Observed result

The Point of Sale opens but doesn't show any of the items available in the Stock section.

### Expected result

Expected to see a list of all the productions in various groups on opening Point of Sale

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

```
OS version - Ubuntu 20.04
Install method - Manual Method using https://github.com/frappe/frappe/wiki/The-Hitchhiker%27s-Guide-to-Installing-Frappe-on-Linux

```

**Comment by wesguirra** [comment]
Just to add something that help:

![image](https://user-images.githubusercontent.com/10504265/117070526-396f4500-ad04-11eb-97c4-2a19af19714e.png)
POS Closing Voucher is not working.
