### ISSUE TITLE
POS Closing Entry Displayed Queue

### ISSUE THREAD

**Issue by IPLAYCH** [frappe/erpnext#25581]
POS closing entry is required to close the POS and update stock ledger but it isnt closing instead it is displaying queued, Kindly find the image attached to further show the issue on https://trendy.frappe.cloud/ which has been lingering for over a month now.
![Capture](https://user-images.githubusercontent.com/83658161/117026960-205e9800-acf4-11eb-8142-be8fc7e07ace.JPG)

## POS Closing entry was closed and saved and submitted but the closing entry displayed (QUEUED) instead of (SUMBITTED)
 We will appreciate your solution as soon as possible.
Thank you.

**Comment by Papitom101** [comment]
This issue has been on for almost one month, an 
![Queuedisplayed](https://user-images.githubusercontent.com/7777594/117062132-fc627d00-ad1a-11eb-95d0-1a17c5c578a4.png)
an urgent solution is highly needed

**Comment by nextchamp-saqib** [comment]
Should be fixed with #25595
