### ISSUE TITLE
Stock Reconciliation - You can select a Batch for another Item

### ISSUE THREAD

**Issue by guilmori** [frappe/erpnext#25583]
In Stock Reconciliation, Items child table, you can select a Batch for another Item, and submit with no error.
For example, add 'Item 1' line, but select an existing batch for 'Item 2' (the batch link dropdown is not filtered on the line item).
Then submit, you will have 'Item 1' qty in warehouse, but 'Item 2' qty in the batch, really messed up.

**Comment by ankush** [comment]
closed by https://github.com/frappe/erpnext/pull/26370
