### ISSUE TITLE
[v13.2] Selling terms are not automatically added to invoices

### ISSUE THREAD

**Issue by akhashogji** [frappe/erpnext#25594]
## Description of the issue
After upgrading to v13, selling terms are no longer automatically fetched while creating a new sales invoice.
The selling term is added as the default for the company.

## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 13.2.0
frappe 13.2.0
```

## Steps to reproduce the issue

1. Create a new sales invoice
2. Check terms

**Comment by deepeshgarg007** [comment]
@akhashogji I checked and this worked fine for me as expected. If there are more steps please add them. Adding a GIF will also be helpful. Closing this issue for now
