### ISSUE TITLE
[v13.2] Email campaign isn't updating status automatically on date change

### ISSUE THREAD

**Issue by wesguirra** [frappe/erpnext#25597]
## Description
I have v13 installed and the email campaign isn't updating status automatically on date change, and as a consequence, the emails are not being sent.

Below, is the image of an email campaign I'm at the finish date already, but the status doesn't change.

![image|689x296](https://discuss.erpnext.com/uploads/default/optimized/3X/8/9/89c47050bd9ceaec6b777551d2bdb12645a73d60_2_689x296.png)

I tried to force schedule with the command below:
```
bench execute erpnext.crm.doctype.email_campaign.email_campaign.set_email_campaign_status
```

Again the status doesn't change.

Actually, to accomplish this task, I'm manually changing the start date to today of the email campaign to change the status, then I trigger the sending of e-mail using the command below.
```
bench execute erpnext.crm.doctype.email_campaign.email_campaign.send_email_to_leads_or_contacts
```

## Context information (for bug reports)

**Output of `bench version`**
erpnext 13.2.0
frappe 13.2.0

## Steps to reproduce the issue

1. Create a contact
2. Create an email template
3. Create a campaign
4. Assign created template to campaign
5. Create an email campaign for the contact with date start to tomorrow

### Observed result
The Email Campaign is created but when the day changes the status still is "Scheduled".

### Expected result
When the day change the status should be "In Progress"

### Stacktrace / full error message
Can't find any log about this

## Additional information
Ubuntu 18.04

**Comment by ruchamahabal** [comment]
@wesleyguirra The End Date is automatically calculated based on your Start Date and maximum days in your campaign schedule.

This is my campaign:

![image](https://user-images.githubusercontent.com/24353136/127356878-c7317dcc-9825-43fb-9431-4738dec401f1.png)

Email Campaign status updated automatically and End Date is also set properly:

![image](https://user-images.githubusercontent.com/24353136/127357023-75b938a3-48a0-4176-b1b2-bb35d4d66f5e.png)

Looking at your screenshots, it looks like the campaign schedule doesn't have the days set properly for when the email should be sent. Can you share your campaign configuration with us?
