### ISSUE TITLE
POS Closing Entry

### ISSUE THREAD

**Issue by alameer51** [frappe/erpnext#25618]
## Context information (for bug reports)

**Output of `bench version`**
```
13.10
```

## Steps to reproduce the issue

1. I tried to close by POS Closing Entry
2. 
3.

### Stacktrace / full error message

```
Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 100, in execute_job
    method(**kwargs)
TypeError: create_merge_logs() got an unexpected keyword argument 'merge_logs'
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by glibersat** [comment]
We used to face the same issue, looks like it was resolved in 13.1.1. Can you try upgrading?
