### ISSUE TITLE
Journal Voucher Type

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#2562]
- [ ] Convert Mode of Payment to Journal Entry Type
- [ ] Make separate types for bank, cash, credit card payment received and payment made (in fixtures, patch)
- [ ] Patch to convert existing "bank entry", "cash entry" - in made and received.
- [ ] Default accounts in Journal Entry Type
- [ ] Set default accounts if type is selected
- [ ] Payment made, received - from company, select default payable and receivable account
- [ ] Set type in Payment Tool
- [ ] In Sales / Purchase Invoice set correct JE type

- [ ] Additional Types
  - Asset Depreciation
  - Exchange Gain or Loss
  - Expense Claim Reimbursement
  - Expense Entry
  - Rent Payment
  - Investment
  - Investment Redeemed

**Comment by neilLasrado** [comment]
Will do this.
