### ISSUE TITLE
user_fullname variable does not get replaced in the password reset template

### ISSUE THREAD

**Issue by mincerray1** [frappe/erpnext#25629]
## Description of the issue
user_fullname variable does not get replaced in the password reset template
![image](https://user-images.githubusercontent.com/8111634/117448929-ee5a6980-af71-11eb-86a0-4d26b5fed709.png)

## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 13.2.1
frappe 13.2.1
```

## Steps to reproduce the issue

1. In the login page, run Forgot Password:
![image](https://user-images.githubusercontent.com/8111634/117449026-0f22bf00-af72-11eb-8265-2b671686b2ef.png)
2. Enter your email and click Reset Password:
![image](https://user-images.githubusercontent.com/8111634/117449077-21046200-af72-11eb-9b2c-d3597e737cd8.png)

### Observed result
The "user_fullname" variable is shown in the email.

### Expected result
Your full name (or simply username?) must be displayed instead.

**Comment by CleoMenezesJr** [comment]
Did you manage to solve this issue?

**Comment by ankush** [comment]
This is solved in latest versions.

https://github.com/frappe/frappe/pull/13958
