### ISSUE TITLE
[v13]Multi-Company issues.

### ISSUE THREAD

**Issue by rtdany10** [frappe/erpnext#25625]
In global defaults, I have the company set as `CompanyA`. Now, UserA should have access only to `CompanyB`. Therefore, I created user permission to limit the access to only `CompanyB`. I also ticked the `Is Default` in user permission.

Now what happens is, when UserA logs in, his default company is still `CompanyA`(fetched from global defaults) and not from user permissions.

This causes issue on various places like dashboards, reports etc as the company filter gets auto populated by the default company.

I tried to set the company field in global defaults to empty. Now when I login, I get an error saying
```
Company None doesn't exists.
```

I believe user permissions should be given higher priority while fetching session defaults.

**Comment by nasirrr** [comment]
Hi. I can confirm this. I have reproduced the error as well. I have posted on the forum too. 
https://discuss.erpnext.com/t/critical-bug-v13-user-permissions-not-saving/82830

On a side note, have you found a fix for it? @rtdany10

**Comment by nasirrr** [comment]
This is the error message. 
![image](https://user-images.githubusercontent.com/93313345/150762619-32bcefd0-ed52-4aa8-88df-7cd606d44c46.png)

@rtdany10 I figured that the error message does not pop up, if the chart is removed from the module homepage. 
E.g: If this Sales order trends chart is removed, then the error will not pop up. Same thing goes for accounting dashboard as well. 
![image](https://user-images.githubusercontent.com/93313345/150763396-2da782e6-dd71-4516-a5fb-267404b6c898.png)

My guess is the charts are taking company from Global default, and if there is no company set, it gives the error. 

Alternatively, if you select the company for chart by clicking on filter(highlighted below in red), then the error won't pop up and the chart would work as designed. 

![image](https://user-images.githubusercontent.com/93313345/150764112-cde92af9-90f4-4478-bc72-5aa5c56af522.png)

**Comment by rtdany10** [comment]
@ankush could you add the validated tag so that stale-bot doesn't close it? Also if possible look into this :sweat_smile: 
Or if you could point me to how global defaults are set, I can send a pull request :sweat_smile:

**Comment by Nihantra-Patel** [comment]
Hi @rtdany10,

The issue has been resolved in the latest versions, 14 and 15. Kindly update your version, refresh, and verify.

Thank You!
