### ISSUE TITLE
Item does not show up in report view if no supplier is defined

### ISSUE THREAD

**Issue by atimalas** [frappe/erpnext#2563]
Item is defined as sub-assembly.
It is a non-purchase and non-sale item. No supplier is defined because the item is assembled in-house.
This item does not show up in the "Report:item" view of the stock module. In the "Item List" the item is visible.
When changing the item to purchase item AND defining a supplier the item shows up in the "Report:item" view.
In my opinion there should be no need to define a supplier when the sub-assembly is manufactured internally.
![erpnext_1_report view_nosupplier0](https://cloud.githubusercontent.com/assets/10433522/5660566/0b4d1818-9722-11e4-85be-d12547adb223.png)
![erpnext_2_item_nosupplier1](https://cloud.githubusercontent.com/assets/10433522/5660569/0b514ef6-9722-11e4-9547-4fbac0a60762.png)
![erpnext_3_item_nosupplier2](https://cloud.githubusercontent.com/assets/10433522/5660567/0b4e4436-9722-11e4-818a-dd749a187ada.png)
![erpnext_4_item_nosupplier3](https://cloud.githubusercontent.com/assets/10433522/5660571/0b53f606-9722-11e4-94cd-5405d5eb43ef.png)
![erpnext_5_report view_wsupplier0](https://cloud.githubusercontent.com/assets/10433522/5660570/0b523852-9722-11e4-9895-11eec8076ec9.png)
![erpnext_6_item_wsupplier1](https://cloud.githubusercontent.com/assets/10433522/5660568/0b4fbfb4-9722-11e4-9b07-6b56cebd7768.png)

**Comment by rmehta** [comment]
It does not show up in report because of the join with the supplier details table. If you remove the supplier and supplier part number columns, the list will appear.

Thanks for reporting, we will fix this in version 5.

**Comment by anandpdoshi** [comment]
This is already fixed in version 5 :smile: 

https://github.com/frappe/frappe/commit/d5072ebb
