### ISSUE TITLE
Invalid Method Message on Login

### ISSUE THREAD

**Issue by hballan** [frappe/erpnext#25643]
Running ERPNext from virtual machine
erpnext 13.2.1
frappe 13.2.2
On login receive Invalid Method notification before loading the desk
![ScreenShot](https://user-images.githubusercontent.com/34502442/117545821-1ad4bb00-b030-11eb-8db3-900eebe5b385.JPG)

**Comment by gdlrsilv3** [comment]
I have the same error

**Comment by addaxagent** [comment]
I have the same error too. Any help?

**Comment by hballan** [comment]
Just upgraded to
erpnext 13.5.0
frappe 13.5.0
and still this issue has not yet been resolved

**Comment by hballan** [comment]
Ok was finally able to resolve this issue. The problem was that I was running an old version of Node 8.x
To check your version run `node --version`
To fix upgrade to Node 12.x
then update using `bench update`
and the problem should be resolved
