### ISSUE TITLE
Total item amount shown does not correspond with items in the system

### ISSUE THREAD

**Issue by atimalas** [frappe/erpnext#2564]
In picture one: 113 items in the system

In picture two the last item is No. 122.

![erpnext_1_item_no_1](https://cloud.githubusercontent.com/assets/10433522/5660718/ce4a26b6-9723-11e4-8329-0bb721bb05db.png)
![erpnext_1_item_no_2](https://cloud.githubusercontent.com/assets/10433522/5660719/d0288b08-9723-11e4-86b2-9a82b3d07095.png)

**Comment by rmehta** [comment]
Same as previous issue. Closing
