### ISSUE TITLE
Purchase Invoice (Is Return/ Debit Note) Bug

### ISSUE THREAD

**Issue by sjain17** [frappe/erpnext#25650]
**1. Incorrect Tax Calculation:**

When we create a purchase invoice with is return check box as true the tax amount gets round up and it's not round off; whereas when we create a regular purchase invoice without is return =1 then it calculates correctly. 

**Case 1: Purchase Invoice (Is return =0)**
I have created a purchase invoice with the amount of INR 8.5 and added 5% TAX, The Tax amount 0.43 which is correct. 

**Case 2: Purchase Invoice (Is return =1)**
I have created a purchase invoice with the amount of INR 8.5 and added 5% TAX, The Tax amount 0.42 which is incorrect. However, before saving it shows 0.43, and once we save it changes to 0.42 again.

**2. Uniqueness Check Fails into Is Return=1 in the purchase invoice.** ERPNext is not checking the uniqueness of the supplier invoice if the document is the debit note; whereas in a regular Purchase Invoice, it works fine.

I am using the below versions. -
ERPNext: v13.0.0 (version-13)
Frappe Framework: v13.0.1 (version-13)

**Comment by bosue** [comment]
1.) To a certain degree I managed to reproduce some perceived flakiness when switching from Bankers’ to Commercial Rounding and the other way around _without clearing the cache_.

When I was testing this, the tax amount oscillated between 0.42 and 0.43, but in the end always settled with 0.43. It‘s not unconceivable though that with different parameters, the end result may be the wrong one.

To avoid this, when switching between Bankers‘ and Commercial Rounding, we should at least clear the cache automatically. 💁🏻‍♂️

2.) With unique supplier invoices turned on in Accounts Settings, at least per today (v16 dev) this feature seems to work perfectly fine, even when reentering a supplier invoice number previously entered in a  Return / Debit Note. ✔️
