### ISSUE TITLE
Duplicating a pre v13 Purchase Invoice sets wrong Item price

### ISSUE THREAD

**Issue by carstenblt** [frappe/erpnext#25659]
## Description of the issue
If you duplicate a Purchase Invoice that was created in v12, the Item price will be overwritten by a price that looks random to me upon saving. This only happens when there is a price in the in the price list for this item. You can then only fix it by setting the "price list" entry to 0.

This does not happen, when you duplicate a Purchase Invoice that was created in v13.

## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 13.2.1
frappe 13.2.2
```

## Steps to reproduce the issue

1. Duplicate a Purchase Invoice that was created using ERPNext v12.
2. Change the item price.
3. Save the Purchase Invoice

### Observed result
The item price changes. E.g. you set the item price to 5 €, after saving it will be 5,67 €.

### Expected result
The item price should stay the same.

**Comment by kanedai** [comment]
same promblem.
