### ISSUE TITLE
ITEM CODE GROUP WISE

### ISSUE THREAD

**Issue by contractorandsons** [frappe/erpnext#2566]
we want to generate groupwise item code.

we have lots of items, so create groupwise item code, we can manage easily.

so how can we create groupwise item code.

```
         ITEM GROUPS      GENERATE CODE
```

e.g. (1) Cabinet Handle   -         CBH0001
       (2) Hinges                 -         HIN0001

so kindly you have any videos or step by step example, please provide for the same asap.

regards,

Shamsuddin

**Comment by umairsy** [comment]
Hello Shamsuddin,

You can have Item Codes generated based on Naming Series. This will require
you creating Naming Series for each Item Group.

You can enable Item Coding based on Naming Series from:

Stock >> Setup >> Stock Settings

Item Naming By = Naming Series

Hope this helps.

On Fri, Jan 9, 2015 at 7:47 PM, contractorandsons <notifications@github.com>
wrote:

> we want to generate groupwise item code.
>
> we have lots of items, so create groupwise item code, we can manage easily.
>
> so how can we create groupwise item code.
>
>          ITEM GROUPS      GENERATE CODE
>
> e.g. (1) Cabinet Handle - CBH0001
> (2) Hinges - HIN0001
>
> so kindly you have any videos or step by step example, please provide for
> the same asap.
>
> regards,
>
> Shamsuddin
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/frappe/erpnext/issues/2566>.
>



-- 
Thanks and Regards,
Umair Sayyed
www.erpnext.com

**Comment by yashodhank** [comment]
Closing as no response/update.
