### ISSUE TITLE
Unable to create Purchase Receipt from Purchase Invoice

### ISSUE THREAD

**Issue by zerodiscount** [frappe/erpnext#25664]
## Description of the issue
Created Purchase Invoice with stock inventory items. Unable to Create Purchase Receipt. The + button is missing and also no option under Create Menu.

## Context information (for bug reports)

**Output of `bench version`**
ERPNext: v13.2.1 (version-13)
Frappe Framework: v13.2.2 (version-13)```
## Steps to reproduce the issue

1.
2.
3.

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by kennethsequeira** [comment]
Feature add
