### ISSUE TITLE
Cannot create topics for courses

### ISSUE THREAD

**Issue by seabilwe** [frappe/erpnext#25661]
## Description of the issue
- I need to create topics for a course but I do not see the add button when I go to Topic even after removing filters.
- When adding the topic directly in course, the topic disappears only the topic name remains.
- I went through the documentation, perhaps I missed something but I don't see anything regarding this.

## Context information (for bug reports)
Add New Button not visible
![image](https://user-images.githubusercontent.com/56301949/117809201-2e656900-b25e-11eb-9780-ad85932333df.png)

## Steps to reproduce the issue

1. Create topic entry
2. No button that allows for topic to be created
3. Creating topic under course, topic disappears

### Observed result
No topic created
### Expected result
Topics created must appear on the list of topics, even when created when creating a course

**Comment by ruchamahabal** [comment]
Please check if you have the appropriate permissions to do so. You need "Create" permission for the New button to be visible

[https://docs.erpnext.com/docs/user/manual/en/setting-up/users-and-permissions/role-and-role-profile](https://docs.erpnext.com/docs/user/manual/en/setting-up/users-and-permissions/role-and-role-profile)

**Comment by seabilwe** [comment]
Thank you @ruchamahabal
