### ISSUE TITLE
Stock Ledger value not syncing with POS available quantity value

### ISSUE THREAD

**Issue by IPLAYCH** [frappe/erpnext#25665]
The value of the available stock on the stock ledger for this particular item is 7 units and on the pos retail module, the value is displaying 0 units.

Kindly help review this.
![Trendy 1](https://user-images.githubusercontent.com/83658161/117843651-e6067500-b276-11eb-99cd-c3e40c9f17aa.JPG)
![trendy 2](https://user-images.githubusercontent.com/83658161/117843668-eacb2900-b276-11eb-992b-3b5cc7f3b560.JPG)

Thank you.

**Comment by deepeshgarg007** [comment]
@IPLAYCH POS invoice item qty only syncs with actual stock once you create the POS closing and consolidate them to a regular Sales Invoice
