### ISSUE TITLE
Finance Book Link to Sales / Purchase Invoice

### ISSUE THREAD

**Issue by usman-alikhan** [frappe/erpnext#25668]
**Is your feature request related to a problem? Please describe.**
Currently the system only maps Journal entries to Finance Book. This limits the utility of this great function. Generally, as accountants, we need to segregate expenses / purchases / sales into separate books for various reasons. 

Even when the custom field for Finance Book is added to other transactions it does not hit the GL Entry and accordingly segregated reports (Balance Sheet, PLS, Cash Flows, etc) can not be generated.

**Describe the solution you'd like**
Creating a link of other doc types (other than Journal Entry) like Sales  Invoice, Purchase Invoice (and perhaps docs like sales order, purchase order, salaries, etc.) would be a great feature taking ErpNext another notch higher.

It would be best if we can generate reports separately for the finance books as well as a aggregate / cumulative report for all the finance books together.

Please consider this feature.

**Comment by nateriches** [comment]
Whole-heartedly agree. The Finance Book system would greatly benefit from it being accessible near the business transaction level of user engagement vs. only being able to do them at the Journal Level.
