### ISSUE TITLE
Enrolment Link Invalid

### ISSUE THREAD

**Issue by seabilwe** [frappe/erpnext#25689]
## Description of the issue
When adding a new student, an email is sent to the student once all info has been added to the students profile. When the student receives the enrolment email and click on the link to submit a new password they got a message saying **‘invalid link’**, even when they opened it in another device they got the same outcome. It also does not allow one to resend the enrolment email.

## Context information (for bug reports)

 ‘Invalid Link'

The Link specified has either been used before or Invalid’ so the student cannot complete the registration

## Steps to reproduce the issue

1. Adding new student with all the students details 
2. Clicking the Save button to send the enrolment email
3. Student receives mail but cannot proceed with registration

### Observed result
- Student cannot continue registration because of invalid link

### Expected result
- Student needs to register completely in order to gain access to contents of the program they are enrolled in

**Comment by pateljannat** [comment]
https://github.com/frappe/erpnext/pull/25825

This PR resolves the issue
