### ISSUE TITLE
User Permission is not working as supposed to do so

### ISSUE THREAD

**Issue by piratedkhan** [frappe/erpnext#25686]
## Description of the issue
i have instance where few of the sales user used to makes sales deliveries and invoices from their respected warehouse. i have made user permission for each user to have access to only the warehouse they need (Screen Shot attached). the situation was handled very nicely with user permissions as i was on V12 but recently i have upgraded to V13 and now when a user with user permission set for warehouse makes a delivery note or invoice with update stock checked it gives error( kindly check error section for screenshot)

## Context information (for bug reports)

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1. i have created few warehouses and few users. each user have access to specific ware house achieved via user permission
[https://discuss.erpnext.com/uploads/default/optimized/3X/c/2/c2daa37b564ada90e3c5bd8cca608355a3deb92a_2_1035x313.jpeg](url)
2. everything working as it supposed to on v12 but after upgraded to V13 it has issues while users making delivery notes or invoices with updated stock checked. Error Screen shot is here [https://discuss.erpnext.com/uploads/default/optimized/3X/b/2/b21a5dadba2a643add617b285b97702fe29ef659_2_1035x504.png](url)
3. deleting the user permission makes user able to make invoices and deliveries again.

### Observed result
My observation on the result is that user permissions ware working fine on version 12 but seem to have issues on v13
### Expected result
I was not expecting the kind of result on v13
### Stacktrace / full error message

```
https://ibb.co/vcMTNP8
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.
Ubuntu 20 / ERPnext V13

**Comment by nasirrr** [comment]
The pics are improperly hyperlinked. Do repost them.
