### ISSUE TITLE
Period Closing Voucher not working with accounting dimensions.

### ISSUE THREAD

**Issue by piratedkhan** [frappe/erpnext#25685]
## Description of the issue
It seems when you try to submit period closing voucher with accounting dimensions  mandatory for balance sheet and trail balance , the period closing voucher will fail to submit. I think period closing voucher need to address this issue.

## Context information (for bug reports)

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1. i have create a accounting dimension based on territory mandatory fields check for balance sheet and trial balance
2. after that i have done the posting entries as normal
3. at the end of the fiscal when i tried to close the period with period closing voucher it failed to do unless you remove the accounting dimension. 

### Observed result
Faild to submit period closing voucher when accounting dimension is set and mandatory for balance sheet and trial balance
### Expected result
Period closing voucher should work seamlessly to handle this kinda situation
### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.
Ubuntu / LTS 20 , Erpnext 13 latest,  also noticed this issue on version 12

**Comment by deepeshgarg007** [comment]
@piratedkhan This should be resolved now in the latest version-14 release, please check and reopen if the issue still persists
