### ISSUE TITLE
Salary Component Filters not working on Salary Structure

### ISSUE THREAD

**Issue by sgtpepper9907** [frappe/erpnext#25707]
## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 13.2.1
frappe 13.2.2
```

## Steps to reproduce the issue

1. Create a new Salary Structure
2. Try to add deductions and earnings
3.  No salary components are found until you remove the company from the salary structure

### Observed result

When Company is set, the components are filtered by the type and company. Since there is no company field in Salary Component, no results are found even when they exist.

![Salary Component Bug](https://user-images.githubusercontent.com/21094671/118153229-48788600-b3db-11eb-8b86-8ae3f8b82f95.gif)

### Expected result

The components are not filtered by company or the company field is added to the components in order to filter them by company

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by pateljannat** [comment]
@sgtpepper9907 Salary Component doctype has a child table called Accounts. This child table has a company field. Set the company here. After that create your salary structure with the company field. The components that fall under this company will appear for earnings and deductions.

**Comment by sgtpepper9907** [comment]
@pateljannat I tried after adding the Account and it worked fine.
Maybe a default account with the default company should be added on creation?
