### ISSUE TITLE
ERPNext: v13.2.1 (version-13) - Item master "Stock Level " section requires additional refresh

### ISSUE THREAD

**Issue by satisharalkar** [frappe/erpnext#25717]
In item master, stock level section does not come automatically. It is required additional refresh to see stock level section.

![image](https://user-images.githubusercontent.com/17386166/118306752-75c25280-b507-11eb-828f-71bde2cd0f2a.png)

You can reproduce this issue by opening the item and then go back to home page. Again open the same item, you will not find the "Stock Level" section.

Now "Refresh" , you can see the "Stock Level" section.

**Comment by ankush** [comment]
Fixed here: https://github.com/frappe/erpnext/pull/25506

**Comment by satisharalkar** [comment]
Thanks Ankush,

I am on latest version and experiencing same issue.

Installed Apps

ERPNext: v13.2.1 (version-13)

Frappe Framework: v13.2.2 (version-13)


Please let me know if there is a workaround for this


Regards,

Satish Aralkar

**Comment by ankush** [comment]
The fix is not released yet. It will be part of next release.

Temporary solution is to do hard refresh (cmd/ctrl+shift+r).

**Comment by satisharalkar** [comment]
Thanks a lot for quick response.
