### ISSUE TITLE
Filtered Financial Statement Issue 

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#25710]
Hi ,

When a Financial Statement (P&L, Balance Sheet...) is filtered by Cost Center, it only shows the section of the statement where there have been transactions. This becomes a problem when only one section of the Balance Sheet or Income Statement has transactions; the statement becomes one-sided!

For example, If you have only some inventory transactions against a Cost Center which have posted transactions against the Stock Adjustment ledger, this means transactions for this Cost Center will only show in the Asset and Expense sections of the Financial Statement (which is fine and expected). The issue is that when you run this report, say, for Balance Sheet, you only see one side (in this case, Asset section) as shown below: 

![Filtered Financial Statement Issue 01](https://user-images.githubusercontent.com/9269337/118246415-d6b34180-b499-11eb-8e99-6abb488ad6ed.png)

This is an Un-balanced report! Ideally, there should be additional lines as shown below:

**Total Liability (Credit)      N0.00
Provisional Profit / Loss (Credit)     N8,194,500.00
Total (Credit)      N8,194,500**

Because of this issue, the Number Card is also incorrectly showing Provisional Profit / Loss as N0.00

![Filtered Financial Statement Issue 02](https://user-images.githubusercontent.com/9269337/118248581-5e01b480-b49c-11eb-9b85-4afcc982512e.png)

Please help fix this as soon as possible!

Thanks a lot

**Comment by deepeshgarg007** [comment]
@Olawale1 I don't think this should be done. Only the transactions with that specific cost center should be shown
