### ISSUE TITLE
v13 Feature Request: Allow pinning of modules in sidebar

### ISSUE THREAD

**Issue by sahil48** [frappe/erpnext#25724]
**Is your feature request related to a problem? Please describe.**

In ERPNext, I use the Manufacturing Domain most frequently. It is frustrating to scroll every single time I want to access it. This is the part I like least about ERPNext v13 compared to v12.

![image](https://user-images.githubusercontent.com/6100774/118400985-e8c7e800-b631-11eb-8d6f-b645ee33a3d9.png)

**Describe the solution you'd like**
Allow modules to be pinned to the top of the sidebar for easy access of most frequently used modules, similar to Quick Access in Windows File Explorer https://www.windowscentral.com/how-use-quick-access-file-explorer-windows-10. It will show at the top of the sidebar, under a heading called pin.

**Describe alternatives you've considered**
I also considered if the modules to be accessible as a shortcut, but I feel this is less appropriate compared to the above solution.

**Comment by sahil48** [comment]
I saw a validate tag added and removed. Is there any update on this?

**Comment by ankush** [comment]
v14 has an extremely configurable workspace, so this feature request is a small subset of that. 
https://github.com/frappe/frappe/pull/13152
