### ISSUE TITLE
Error when open links in UOM

### ISSUE THREAD

**Issue by wojosc** [frappe/erpnext#25738]
When opening Links in DocType UOM I get an error:
![grafik](https://user-images.githubusercontent.com/22279621/118513616-30369d00-b734-11eb-914a-c8e617915878.png)

pymysql.err.OperationalError: (1054, "Unknown column 'tabQuality Review.action' in 'field list'")

Installed Apps

Datanorm Integration: v0.0.1 (main)

ERPNext: v13.2.0 (version-13)

ERPNextFinTS: v0.3.6 (master)

Frappe Framework: v13.2.0 (version-13)

**Comment by deepeshgarg007** [comment]
Can't be seen in the latest version-14 release, closing this issue
