### ISSUE TITLE
Journal Voucher - “Total Debit and Total Credit amount calculation”

### ISSUE THREAD

**Issue by ashrafulratul** [frappe/erpnext#2575]
When i add new journal entry with Debit amount `Total Debit` field set total debit amount autometically and it's work after add some other amounts of entry. `Total Debit and Total Credit` field are calculate autometically.
But when i am delete any journal entry it's not calculate. It must calculate after delete any entry.

Thanks.

**Comment by neilLasrado** [comment]
Thanks for reporting this bug ... will be fixed !!!

**Comment by ashrafulratul** [comment]
Thansk Lasrado.
