### ISSUE TITLE
Loan dashboard attempts to show information outside scope of user permissions

### ISSUE THREAD

**Issue by killarny** [frappe/erpnext#25751]
## Description of the issue

Viewing the out-of-box default loan dashboard as a system user who does not have the Loan Manager role results in a number of errors in a popup:

![image](https://user-images.githubusercontent.com/29001/118736607-fdaea200-b810-11eb-8f7e-80cd4f7a7291.png)

## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 13.3.0
frappe 13.3.0
```

## Steps to reproduce the issue

1. Create a system user.
2. Remove the "Loan Manager" role from that user.
3. Navigate to the Load Dashboard at `/app/dashboard-view/Loan%20Dashboard`
4. Observe the error popup.

### Observed result

A bunch of errors in a popup window, as shown in the screenshot above.

### Expected result

The dashboard should not attempt to show data that the user does not have access to.

### Stacktrace / full error message

See screenshot above.

## Additional information

**OS info**: `Linux 4.15.0-117-generic #118-Ubuntu SMP Fri Sep 4 20:02:41 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
**ERPNext install method**: docker-compose

**Comment by deepeshgarg007** [comment]
@killarny This is meant for an internal employee who is managing the Loans hence Loan Manager permission is essential, why would any other user access this can you please explain?

You can add permission to other roles as well via Role Permission Manager, closing this for now
