### ISSUE TITLE
Price List Rate sets to 0 after creating Sales Return from Sales Invoice

### ISSUE THREAD

**Issue by wikiodisha1** [frappe/erpnext#25750]
Sales Invoice (Is Return / Credit Note) item price list rate sets to 0 instead of the rate in Sales Invoice

**Comment by dcollinetti** [comment]
It also happens when I create a Credit Note by itself ( not originated from a sales invoice)

**Comment by deepeshgarg007** [comment]
Can be replicated in latest version, closing this issue
