### ISSUE TITLE
Wrong employee id is filled in employee link field of the form when employee filter is applied in list view.

### ISSUE THREAD

**Issue by nikhilponnuru** [frappe/erpnext#25780]
## Description of the issue

Employee link field of the form is picking employee id from employee filter in the list view.

This issue can be best described by steps:

Step1: Login (here say the logged in employee is HR-EMP-00002)

Step2: Apply an employee filter in the list view of any of the modules like leave application, expense claim etc.

Here the filter applied is for HR-EMP-00001

<img width="1281" alt="image" src="https://user-images.githubusercontent.com/13184155/119077995-f9ea6d80-ba12-11eb-9c6f-30b71918f4c8.png">

Step 3: Click on 'Add Leave Application' 

Step 4: See that employee field below is filled with details of HR-EMP-00001 from filters but not based on the logged in employee. (i.e HR-EMP-00002 is logged in)

<img width="1266" alt="image" src="https://user-images.githubusercontent.com/13184155/119078235-6ebda780-ba13-11eb-8bd2-301f77905ffb.png">

## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 13.2.0
frappe 13.2.0

```

## Steps to reproduce the issue

1. As described above
2.
3.

### Observed result
Wrong employee details are filled in leave application, expense claim etc.. wherever employee link field is used and a filter of another employee is applied in the list view.

### Expected result
Correct employee details to be shown in every module.

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `Frappe` install method, etc.

Mac os, mojave.

**Comment by nabinhait** [comment]
@nikhilponnuru This is the expected behaviour in the frappe framework. If you filter on a link field in List view and then try to create a new record, the system set the default value of the link field based on the filter value. Here, the system expects that you are processing data for the employee which has been set in the filter.

Closing this.
