### ISSUE TITLE
Lack of Taiwan currency and the name of Taiwan in the country list need to be corrected

### ISSUE THREAD

**Issue by Leon0824** [frappe/erpnext#2583]
According to [ISO 4217] (http://en.wikipedia.org/wiki/ISO_4217#Active_codes), please add TWD into the currency list.
And in the current country list, Taiwan is noted as 'Taiwan, province of China'. Please correct to 'Taiwan'.
Obviously, Taiwan is not a province of China.

Thanks,
Leon

**Comment by rmehta** [comment]
Thanks! Fixed in v5

**Comment by joy12825** [comment]
And in the current country list, Taiwan is noted as 'Taiwan'. Please correct to 'Taiwan , province of China'.
Taiwan is a province of China. @rmehta
