### ISSUE TITLE
UI problem with Leave application - status indicator doesn't convey if the application is submitted or in draft

### ISSUE THREAD

**Issue by nikhilponnuru** [frappe/erpnext#25864]
## Description of the issue

When a leave approver updates the leave status to 'Approved' from 'Open', the leave status in list view and in application updates with green colored 'Approved' indication and it is found that it is hard for some to notice that the leave application is not yet submitted. 

Since submission of the leave application is mandatory to mark the attendance and leave ledger, this creates confusion.

![image](https://user-images.githubusercontent.com/13184155/119931738-9080d680-bf9f-11eb-8a5a-22ad6b9e913f.png)

In List view

![image](https://user-images.githubusercontent.com/13184155/119935348-fd4a9f80-bfa4-11eb-9567-77a763aecedb.png)

Status filter in listview also filters based on 'Approved' or 'Open' but not basing on docstatus.

![image](https://user-images.githubusercontent.com/13184155/119931799-b0b09580-bf9f-11eb-9283-7aaae32af05e.png)

Even though submit button appears on top right corner after save, this confusion still exists.

## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 13.2.0
frappe 13.2.0
```

## Steps to reproduce the issue

This is an UI confusion more than a software issue, so steps to reproduce may not be justified.

1. Create a leave application
2. As an approver, change the status to approved.
3. Now there is a good chance that approver may miss the submit button since on top left it shows green colored 'Approved' indication and listview also has the same.

### Observed result

Confusion among few in submitting the leave application

### Expected result

No UI confusion

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

Mac os, mojave (happens in all OS's and browsers)

**Comment by pushkarjsh88** [comment]
@pateljannat Do we have further insights on this?
