### ISSUE TITLE
Leave Application counts weekends and wont add previous quarters

### ISSUE THREAD

**Issue by DrTrills** [frappe/erpnext#2587]
Hi all,

I am putting in employee leaves and noticed that the system automatically subtracts the weekend into the leave total. I think it would be best if it keps saturday,sunday, and holidays out of the total.

Also, when creating 10 days off in 2015, then adding 10 days in 2014 with roll over, It doesn't update the base of 2015 to 20 days, i need to manually unlock/amend -> save again for it to add the previous year. Not sure if by design or mistake but figured it was worth noting.

Thanks!

**Comment by umairsy** [comment]
Dr.

Please create holiday list:

HR >> Setup >> Holiday List

and update it in the Employee master:

HR >> Documents >> Employee >> (Update Holiday List for each Employee)

Days listed in the Holiday List will not be counted in Leave Application, provide Holiday List is updated in that Employee's master.

**Comment by DrTrills** [comment]
Thanks again for your help! I have created the holiday list but didn't add weekends, now I have added weekends and should be all set. Again, you guys thought of everything! 

Thanks and have a nice weekend
