### ISSUE TITLE
ERPNext V13 | Document Printing : Changing Print Format

### ISSUE THREAD

**Issue by abhioncode** [frappe/erpnext#25889]
First Issue when I updated to version 13 (from 12) is that the default print format selected is ignored. V13 goes back to the default Standard Print Format. When I change this I get the following error:

Server Error
SystemError: returned a result with an error set

Nothing gets stored in Error Log, and opening Inspector this is the error I got:
<img width="1213" alt="Screen Shot 2021-05-30 at 07 19 14" src="https://user-images.githubusercontent.com/85059961/120102101-7964f480-c117-11eb-91b0-2f25bf2f6470.png">

**Comment by rasos** [comment]
We had the same issue after migrating from v12 to v13. I just had to do customizing again the `Sales Invoice` where you can set the default print format https://erp.fairkom.net/app/customize-form in the View settings section.
