### ISSUE TITLE
Project linking in Sales Order created from open Quotation shows error

### ISSUE THREAD

**Issue by liyakatalilal** [frappe/erpnext#25880]
## Description of the issue

I have an open quotation in the system and from that, I am creating a Sales Order for the customer. I have existing Projects of the same customer, which I wish to link to the SO created. While I try linking the existing project to SO, I get this error.

Server Error
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'and (((coalesce(`tabProject`.`company`, '')='' or `tabProject`.`company` in (...' at line 5")

![May-29-2021 18-18-11](https://user-images.githubusercontent.com/31281816/120070902-66680b00-c0aa-11eb-9df2-f126c99f8cbe.gif)

**Output of `bench version`**

ERPNext: v13.3.1 (HEAD)
Frappe Framework: v13.3.0 (HEAD)

## Steps to reproduce the issue

1. Create a Quotation for a customer - The status of the quotation is Open
2. Create Sales Order from the Quotation
3. Go to the 'More Information' section in the SO and link to Project

**Comment by ishanloya** [comment]
I seem to be having the same issue but only for some users. Any luck in fixing it?

**Comment by ishanloya** [comment]
As a temporary fix, you can comment out the following lines in the sales_order.js file and then `bench restart`, `bench clear-cache` and `bench --site <sitename> clear-website-cache`

```
frm.set_query('project', function(doc, cdt, cdn) {
	return {
		query: "erpnext.controllers.queries.get_project_name",
		filters: {
			'customer': doc.customer
		}
	}
});
```

**Comment by pateljannat** [comment]
https://github.com/frappe/erpnext/pull/26145

This PR seems related.

@LiyakatAliLal can you verify if you are still facing the issue

**Comment by Komal-Saraf0609** [comment]
Fixed with https://github.com/frappe/erpnext/pull/26145 PR, so closing the issue.
