### ISSUE TITLE
ERPNext 13 - Missing Language Tags

### ISSUE THREAD

**Issue by abhioncode** [frappe/erpnext#25887]
Side panel inside the modules where we store Assigned To, Attachments, etc do not have the translation tags as those words are translated in the project but still appear in English.

**Comment by sliwkawsieci** [comment]
That is probably the same error like here https://github.com/frappe/erpnext/issues/27877#issuecomment-1046076798 . It doesn't see translations from CSV(which I've check and it has translations) 
Workoround is to create custom translation but any way translations in ERPNEXT looks really baad.....
