### ISSUE TITLE
Creation of Serialized Fixed Assets not Working in v13

### ISSUE THREAD

**Issue by jimmielightner** [frappe/erpnext#25890]
## Description of the issue

When creating a 'new item,' selecting 'is_fixed_asset' tick box automatically hides Serial Numbers and Batches section.

## Context information (for bug reports)

ERPNext v13 (latest Develop branch) and Frappe (latest Develop branch) via Docker

**Output of `bench version`**
```
jimmie@cmh-erp-01:~/frappe_docker$ docker run -v cg_sites-vol:/home/frappe/frappe-bench/sites --network cg_default --user frappe frappe/erpnext-worker:edge bench version
erpnext 13.x.x-develop
frappe 13.x.x-develop
```

## Steps to reproduce the issue

1. Create appropriate asset category, selecting depreciation type and accounts.
2.  Create an "Item Group" you'd like to use to reference your Fixed Assets.
2. Create a "New Item" using the "Edit in Full Page" option (It is not possible to do this using quick create flow - the fixed asset field will become locked and you will not be able to edit it after) 
3. In the "New Item" form, notice that selecting "Is Fixed Asset" tick box immediately removes the ability to select "Has Serial Number"

![ScreenFlow](https://user-images.githubusercontent.com/8285016/120108706-6c0a3300-c134-11eb-8fb4-6fe917550918.gif)

### Observed result

The behavior restricts the user from creating a fixed asset with a serial number, such as a computer or other electronic device.

### Expected result

Selecting "Is Fixed Asset" should not hide or remove the ability to set serial numbers for assets. This functionality was introduced via [https://github.com/frappe/erpnext/issues/13594](https://github.com/frappe/erpnext/issues/13594)

### Stacktrace / full error message

```
```

## Additional information

jimmie@cmh-erp-01:~/frappe_docker$ uname -a
Linux cmh-erp-01 5.4.0-1047-azure #49-Ubuntu SMP Thu Apr 22 14:30:37 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
jimmie@cmh-erp-01:~/frappe_docker$ docker --version
Docker version 20.10.6, build 370c289

ERPNEXT_VERSION=edge
FRAPPE_VERSION=edge

**Comment by elan-k** [comment]
The same issue identified in V12 as well. 

Installed Apps :
ERPNext: v12.21.0 (HEAD)
Frappe Framework: v12.18.1 (HEAD)

**Comment by moufpouf** [comment]
I have got same issue. 
ERPNext: v13.5.0 Frappe Framework: v13.5.0

Anyone found a workaround ?

**Comment by elan-k** [comment]
I have added the Asset Detail Section using the customization of Asset DocType.

![Asset_Details](https://user-images.githubusercontent.com/78781781/122531507-32df2780-d03d-11eb-8e74-98009e4ec940.JPG)

I don't have any specific logic other than identifying asset for the Serial Number Field, so I have simply added the field to the Asset DocType along with other information like Make, Model, Description using the customization option. 

Hope it helps !

**Comment by nabinhait** [comment]
Currently, we don't have serialized Asset feature.  We removed it after a first-cut implementation because depreciation is handle on asset record, hence we need to create individual asset record for each serial no.

**Comment by pedrovde** [comment]
Same here and make or break for our ERPNext implementation

**Comment by wojosc** [comment]
I have found a semi work around for this. Check it out here: https://handbuch.tueit.de/books/erpnext-benutzerhandbuch/page/vermogenswerte-mit-seriennummern

If a google-translation won't work to make it understandable send me a message :)
