### ISSUE TITLE
Wages

### ISSUE THREAD

**Issue by mehulmehta** [frappe/erpnext#2589]
1. Base rate plus allowances based on activity like spraying, weeding, plucking (based on harvest slabs), coffee berry picking (based on kgs harvested) etc.. The same worker is used for all the above activities on different days. So worker 1 is used today for spraying, tomorrow for plucking, day after for coffee etc..
2. We follow an attendance muster were the work is allotted for each worker. Then based on the work completed they get paid. (More details on this later)

**Comment by rmehta** [comment]
#2654
