### ISSUE TITLE
Can't delete a Cancelled stock entry

### ISSUE THREAD

**Issue by FreezeS** [frappe/erpnext#25919]
This is the output of "bench version" (not sure why it shows this, how can I get the real version?)
erpnext 13.x.x-develop
frappe 13.x.x-develop
nhance 0.0.1

I made a mistake in a stock entry and I'm trying to delete it.
First I had to change the type of the 1410 - Stock In Hand account to let me add a journal entry and now I get this error:
![image](https://user-images.githubusercontent.com/2807003/120478744-d978c680-c3b5-11eb-885c-16e96d6ecb8e.png)

As you can see, the entry is shown as Cancelled on the left.

**Comment by dj12djdjs** [comment]
You're on the develop branch. This is an unstable branch for development. If you're working in production switch your branch to version-13
