### ISSUE TITLE
[bug] Accounting Dimension Filter column label missing and pl and bs validation not consider default value first

### ISSUE THREAD

**Issue by szufisher** [frappe/erpnext#25914]
## Description of the issue
1. in Accounting Dimension Filter, the Dimension Value column label from Applicable child table is missing 
2. validating mandatory dimension for pl and bs not take into consideration the default dimension value of the company

## Context information (for bug reports)

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1.
2.
3.

### Observed result
![image](https://user-images.githubusercontent.com/12823863/120441478-2d37df80-c3b7-11eb-8e45-db88aef2c55f.png)

![image](https://user-images.githubusercontent.com/12823863/120441579-4b054480-c3b7-11eb-841f-80dc649f076d.png)

### Expected result
1. the applicable dimension child table should have Dimension Value field label
2. when validate pl and bs account for mandatory dimension, need to take into consideration of the default dimension value set for the company.
### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by deepeshgarg007** [comment]
@szufisher Raise a PR to fix the label issue, this is meant to override the default setting. You can set the same values here if you want the default value to be allowed.
