### ISSUE TITLE
create_member_subscription_order webhook gives issue

### ISSUE THREAD

**Issue by shammi-patne** [frappe/erpnext#25911]
{"exc":"[\"Traceback (most recent call last):\\n  File \\\"/srv/bench/erpnext/apps/frappe/frappe/app.py\\\", line 68, in application\\n    response = frappe.api.handle()\\n  File \\\"/srv/bench/erpnext/apps/frappe/frappe/api.py\\\", line 55, in handle\\n    return frappe.handler.handle()\\n  File \\\"/srv/bench/erpnext/apps/frappe/frappe/handler.py\\\", line 31, in handle\\n    data = execute_cmd(cmd)\\n  File \\\"/srv/bench/erpnext/apps/frappe/frappe/handler.py\\\", line 67, in execute_cmd\\n    return frappe.call(method, **frappe.form_dict)\\n  File \\\"/srv/bench/erpnext/apps/frappe/frappe/__init__.py\\\", line 1173, in call\\n    return fn(*args, **newargs)\\nTypeError: create_member_subscription_order() missing 1 required positional argument: 'user_details'\\n\"]"}

url:
https://website/api/method/erpnext.non_profit.doctype.member.member.create_member_subscription_order

parameters:
{
    "plan_id": "TZ_Standard",
    "fullname": "John Doe",
    "mobile": "7506000000",
    "email": "jane@example.com",
    "pan": "Testing123"
}

**Comment by ankush** [comment]
The format expected is different, check this, it should be single dictionary (object in case of JS):

https://github.com/frappe/erpnext/blob/402205278c718ee66cbb01d23c9772d75652ec4b/erpnext/non_profit/doctype/member/member.py#L138
