### ISSUE TITLE
wrong Cost Center in transactions and taxes when using multi companies

### ISSUE THREAD

**Issue by wojosc** [frappe/erpnext#25918]
When using multi company with multiple chart of accounts and multiple chart of cost centers, the new or child company has the wrong cost centers set by default.

I have found this so far only in tax and tax templates:

![grafik](https://user-images.githubusercontent.com/22279621/120476508-f0fe8200-c3aa-11eb-988a-5fc5ece79ae3.png)

**Comment by deepeshgarg007** [comment]
@wojosc There is a validation for this now to prevent this from happening, closing this issue as this is resolved
