### ISSUE TITLE
Batch Issue - Piling of list

### ISSUE THREAD

**Issue by neilLasrado** [frappe/erpnext#2592]
in forms where batch is used as a link field. the list of batch numbers that appear in the drop down are sorted based on time of creation ( LIFO ) . It must rather be based on expiry date. So the ones expiring
first are shown first and then the later batches. 

Taken from Mehul B. Mehta from Mehta Herbs and Spices via Support Ticket Number #WN-SUP10808

**Comment by RealDesignGraphics** [comment]
I agree

**Comment by sbkolate** [comment]
With small modification in get_batch_no query we can sort batch with expiry

![batch sorted](https://cloud.githubusercontent.com/assets/6648915/6574073/c35c5ea6-c746-11e4-93f1-b01674b38fb2.png)

**Comment by RealDesignGraphics** [comment]
where is that screen shot from?

**Comment by sbkolate** [comment]
Above screen shot shows,  Batch No. sorted based on expiry date. So the ones expiring
first are shown first and then the later batches. 

![batch_qty](https://cloud.githubusercontent.com/assets/6648915/6575280/78475efe-c753-11e4-831a-0525eb817eab.png)

Updated screen shot shows available batch qty at warehouse

Please see this: 

https://discuss.frappe.io/t/available-batch-qty-at-warehouse-in-dn-si-and-batch-sorted-based-on-expiry-date/5021

**Comment by RealDesignGraphics** [comment]
I guess I mean from what screen would I see this?  from the stock module? or from sales?  I assume it is from the new version

**Comment by sbkolate** [comment]
Currently this is in developing mode.
If this merge with v4 you can see result like this is Delivery Note and Sales Invoice.

**Comment by rmehta** [comment]
@sbkolate pull request please !

**Comment by rmehta** [comment]
Lets do v5 only.

**Comment by sbkolate** [comment]
I have allready send pull request for v4.

I will also send pull request for v5.

**Comment by nabinhait** [comment]
@sbkolate Thanks for the PR, merged it. No need to send PR for v5, I will merge it in v5.

Can you please send a pull request for get_batch_no query to sort batch with expiry?

**Comment by cgpurbaugh** [comment]
Can this be closed?
