### ISSUE TITLE
Can't submit a Delivery Note

### ISSUE THREAD

**Issue by FreezeS** [frappe/erpnext#25920]
bench version:
erpnext 13.x.x-develop
frappe 13.x.x-develop
nhance 0.0.1

I'm trying to submit a delivery note and each time it shows success but the note is still in Draft:
![image](https://user-images.githubusercontent.com/2807003/120483144-7ccbda80-c3ba-11eb-85ed-8df179952da5.png)

After I go to Delivery notes:

![image](https://user-images.githubusercontent.com/2807003/120483226-92410480-c3ba-11eb-88eb-e79dc118c33c.png)

The log for it looks like this:

![image](https://user-images.githubusercontent.com/2807003/120483275-a127b700-c3ba-11eb-9f6f-1b7c3b40f03b.png)

**Comment by dj12djdjs** [comment]
I just tested on develop branch. It worked for me. Try pulling and try again.
