### ISSUE TITLE
Default values for filters in query report

### ISSUE THREAD

**Issue by aschl** [frappe/erpnext#25931]
Filters in query reports currently don't allow to set filter defaults.
![image](https://user-images.githubusercontent.com/55256684/120616532-9cfea680-c459-11eb-87cf-9e8f749e223d.png)
![image](https://user-images.githubusercontent.com/55256684/120616571-a720a500-c459-11eb-8123-03353cd5beb0.png)

**Describe the solution you'd like**
Similar to the option field a new field should be added for default. This way one could specify the default value using the UI without the need of custom scripts. This is especially important for users hosting on Frappe Cloud as adding custom scripts is not possible there.
Current alternatives are only custom scripts not available to users on Frappe Cloud e.g.
```
			"fieldname":"to_date",
			"label": __("To Date"),
			"fieldtype": "Date",
			-->"default": frappe.datetime.get_today()
```

**Comment by nazarialireza** [comment]
Same issue here, I'm not able to set default value to filters in query report, is there any solution!?
