### ISSUE TITLE
RFQ doesn't appear in Supplier's Account

### ISSUE THREAD

**Issue by chrisdent** [frappe/erpnext#25964]
When creating a RFQ it doesn't appear in the supplier's portal. 

Clicking on the RFQ option in the menu on the left says: "Nothing to show" The only way to see the RFQ is through the link in the e-mail.

That by the way, if the user is logged out it asks for login but then it doesn't redirect to the RFQ.

**Comment by ankush** [comment]
Seems to work as expected.

- User should be website user with "Supplier Role"
- Supplier should have a linked contact that specifies user ID.

**Comment by ankush** [comment]
![Screenshot 2021-09-16 at 12 34 31 PM](https://user-images.githubusercontent.com/9079960/133565835-ee02b421-ea0b-40a6-940d-630ac1f3947a.png)

![Screenshot 2021-09-16 at 12 34 55 PM](https://user-images.githubusercontent.com/9079960/133565824-8407f585-ac73-4441-919a-1c01da564fee.png)

**Comment by chrisdent** [comment]
I can confirm that now they do appear! =)
