### ISSUE TITLE
Message: invalid method

### ISSUE THREAD

**Issue by SeanFaulkner1** [frappe/erpnext#25980]
Hi,

Whenever I go onto our website or navigate from one page to another I get the message; Invalid Method.

![image](https://user-images.githubusercontent.com/85550953/121152456-225ccf00-c83d-11eb-8e4c-b147a0bbfa95.png)

Can we stop this happening please. I can still navigate to each page fine, but it is annoying having to close this box every time.

Many Thanks,
Sean

## Steps to reproduce the issue

1. visit our website... kerstenuk.com
2.navigate to any page
3.

### Observed result
Message: Invalid Method

### Expected result

No Message, just simple navigation.

**Comment by pateljannat** [comment]
@SeanFaulkner1 There must be an API call to a doctype that you don't have permission to. If you could just check the browser console. There must be some error there. Attach the screenshot of the console here.

**Comment by hballan** [comment]
Ok was finally able to resolve this issue. The problem was that I was running an old version of Node 8.x
To check your version run node --version
To fix upgrade to Node 12.x
then update using bench update
and the problem should be resolved
