### ISSUE TITLE
Add '+' Button is missing in Item Dashboard

### ISSUE THREAD

**Issue by Rameshraj55** [frappe/erpnext#25992]
## Description of the issue
After Updated to ERPNext version 13.4.1 In Item Dashboard '+' icon is missing.

### Observed result
![image](https://user-images.githubusercontent.com/67755006/121290208-da54af80-c903-11eb-9d0e-d36a2c4cd54a.png)

### Expected result
![image](https://user-images.githubusercontent.com/67755006/121290473-4afbcc00-c904-11eb-9712-03c3439b35cd.png)

## Additional information
Observed result ERPNext: v13.4.0 (version-13)
Expected Result ERPNext: v13.0.1 (version-13)

**Comment by ankush** [comment]
Fixed in https://github.com/frappe/frappe/pull/13420 You can confirm by checking error message in browser console. Close the issue if it's duplicate.
