### ISSUE TITLE
Tooltips

### ISSUE THREAD

**Issue by viktor-zhuromskyy** [frappe/erpnext#2600]
Would be really great and helpful to have you guys inplement tooltips on fields names with short description of what is the purpose / function of the field is. It will help users get into knowing the system way quicker!

Your ERPNext rules!

**Comment by jagular** [comment]
There already exist 'Description' for the field - check customize form.
In reaction on your proposal i would say, that tooltips values should be from end user.
Description - default field description values from erpnext install
Tolltips - editable by user for making notes, for what purpose is that field ...

**Comment by anandpdoshi** [comment]
Maybe we can allow you to customise description itself.

**Comment by jwrober** [comment]
This is interesting concept. From a UX perspective makes sense. A person can hover over a field and get the description shown (not editable by user). An admin can update the form to give more description detail as needed. Need to give the users an option to turn it off though. Could get annoying for experienced users to have to deal with the little pop up all the time.

**Comment by onlinebizsoft** [comment]
Example UI

https://user-images.githubusercontent.com/22501570/58928844-5c8ec400-877e-11e9-963d-c5ec867dd57a.png

**Comment by gavindsouza** [comment]
Popovers are implemented at multiple areas across ERPNext in `version 12`. Closing this issue right now. If any specific examples of this arise, please open a new issue for the same. Cheers 🍺
