### ISSUE TITLE
Adding currency for Madagascar

### ISSUE THREAD

**Issue by moufpouf** [frappe/erpnext#26018]
Hello everyone,
Thanks for this great app.

Could you please add currency for Madagascar ? 
Name : Ariary
Symbol : Ar

Many thanks

**Comment by rtdany10** [comment]
> Could you please add currency for Madagascar ?
> Name : Ariary
> Symbol : Ar

For time being, you can add a new document in Currency doctype with the required details.

**Comment by moufpouf** [comment]
Yes sure but as it requires to modify chart of accounts, price list ... , tasks that are not easy for a beginner.

**Comment by rtdany10** [comment]
> Yes sure but as it requires to modify chart of accounts, price list ... , tasks that are not easy for a beginner.
>  

If you don't have any data in the system, you can remove the current company and start a new company with correct country and currency, which will take care of everything else automatically.

**Comment by moufpouf** [comment]
Thanks
Working fine !
