### ISSUE TITLE
Healthcare: Inpatient Medication Order links missing in healthcare workspace.

### ISSUE THREAD

**Issue by mujeerhashmi** [frappe/erpnext#26025]
## Description of the issue
The links to access the following are missing in Healthcare Workspace.
1. Inpatient Medication Orders
2. Inpatient Medication Entry
3. InPatient Medication Order Script Report

**Output of `bench version`**
```
erpnext 13.4.1
frappe 13.4.1
```

**Comment by yadavyk** [comment]
@mujeerhashmi closed with  [27100](https://github.com/frappe/erpnext/pull/27100)
