### ISSUE TITLE
Server Error while commenting with Image!

### ISSUE THREAD

**Issue by CITYSUPPORT-ANS** [frappe/erpnext#26039]
## Description of the issue
Facing a server error alert while commenting with Image. 

## Context information (for bug reports)
We are getting Server Error while commenting with Image in ToDo and Task Doctype, I didn't check with other DocType. 

**Output of `bench version`**
Using Frappe Cloud Instance.

## Steps to reproduce the issue

1. Open Any ToDo.
2. Paste Any Image in the comment section.
3. Press ctrl+Enter or Comment button

### Observed result
- After performing the above steps Internal Server Error Alert came.

### Expected result
- Comment with Image should be done without any error. 

### Stacktrace / full error message

```
TypeError: '>' not supported between instances of 'int' and 'str'
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.
Installed Apps
ERPNext: v13.0.0-beta.13 (HEAD)

Frappe Framework: v13.0.0-beta.11 (HEAD)

![comment_with_screen](https://user-images.githubusercontent.com/66312477/121847629-7ddc0080-cd06-11eb-8c0f-0a63dac56311.PNG)

**Comment by kennethsequeira** [comment]
Closing as this is not replicable in latest v13.
