### ISSUE TITLE
Item name in BOM and Production order

### ISSUE THREAD

**Issue by mehulmehta** [frappe/erpnext#2603]
The BOM and production order in list view shows the item only with the item code. similarly when we click on a particular BOM or production order only the item code is shown. it will be much easier if the item name is also shown. Inside the BOM we have operations and then materials. In the materials again the items are shown only with their codes wheras it will be more user friendly if its with item name as well. Secondly why do we need materials and then materials required (exploded) again. Is it not one and the same. Please correct me if I am wrong.

**Comment by neilLasrado** [comment]
Thanks for your suggestion we will surely add item name
The Material Required (Exploded) section lists all sub assemblies as well. so suppose you have an raw material and you have mentioned an BOM for the raw material as well. The Materials required (Exploded) section will list all the raw materials plus the materials required by the raw materials themselves to be manufactured. 

Hope my explanation is clear.
