### ISSUE TITLE
Dashboard Doctype Link Notifications Count - On Every refresh  "frappe.desk.notifications.get_open_count"

### ISSUE THREAD

**Issue by Rameshraj55** [frappe/erpnext#26042]
## Description of the issue
**API : "frappe.desk.notifications.get_open_count"**
1. Dashboard Doctype Link notifications count raises repeated API request call on every refresh[Dashboard having all Doctypes].
2. API Call creating requests on each and every Child table form rendering and while adding Items. 
3. API requests on Triggers refresh, onload, onload_post_render
4. It slow down the Page Loading and all other Submit Requests.
5. It increases the Unneccesary load to Server.

## Steps to reproduce the issue

1. Create a Quotation and in draft
2. Add Items and Save 
3. Browser: Inspect it by Network 
4. Open the Items Table Inspect it by Network (as many as the number of fields in the child table)
5. Check and Filter the Name by Above Mentioned API

## Context information (for bug reports)
**CLIENT SIDE REPORT**
NOTE: Red Arrowed area refers API Requests and increment in Count
![image](https://user-images.githubusercontent.com/67755006/121864751-df0dcf00-cd1a-11eb-94f9-b3c3443d830c.png)

### Expected result

1. Fixing this API issue 
2. Reducing the Server Load

## Additional information

`ERPNext : 13.4.1 (version-13)` 
`Frappe Framework: v13.4.1  (version-13)`

**Comment by ankush** [comment]
https://github.com/frappe/frappe/pull/13510
