### ISSUE TITLE
bug: Bulk update of the Item Price "Valid Upto" field generates an error

### ISSUE THREAD

**Issue by TurkerTunali** [frappe/erpnext#26047]
## Description of the issue
"Edit" button in the Item Price List view, generates an error for "Valid Upto" field.
Error is "Cannot update 4000a33db2, 576b69e90c"
![ERPNextBugReport](https://user-images.githubusercontent.com/710051/121886774-84767200-cd1e-11eb-832d-ff6e0a1379dd.gif)

The error is valid for ERPNext v13.4.1 and v12.16.2.

## Context information (for bug reports)
Uncaught Error: Cannot update <b>4000a33db2</b>, <b>576b69e90c</b>
    throw messages.js:24
    primary_action bulk_operations.js:189
    jQuery 7
    call request.js:229
    call request.js:98
    primary_action bulk_operations.js:173
    set_primary_action dialog.js:149
    jQuery 9
    set_primary_action dialog.js:142
    make dialog.js:60
    <anonymous> dialog.js:18
    edit bulk_operations.js:149
    action list_view.js:1720
    jQuery 2
messages.js:24:7
    throw messages.js:24
    primary_action bulk_operations.js:189
    jQuery 7
    call request.js:229
    call request.js:98
    primary_action bulk_operations.js:173
    set_primary_action dialog.js:149
    jQuery 9
    set_primary_action dialog.js:142
    make dialog.js:60
    <anonymous> dialog.js:18
    edit bulk_operations.js:149
    action list_view.js:1720
    jQuery 2

**Output of `bench version`**
```
Server-1:
erpnext 12.16.2
frappe 12.13.0
Server-2:
erpnext v13.4.1
frappe v13.4.1
```

## Steps to reproduce the issue

1.Select all records in the Item Price list view. 
2.Click the "Actions" - "Edit" button in the Item Price list view.
3.Select the "Valid Upto" field and set a date.

### Observed result
"Cannot update 4000a33db2, 576b69e90c" message shown and nothing updated in the records.
### Expected result
The selected records should be updated.
### Stacktrace / full error message

```
It doesn't generates and error log in the server. But browser console output is:

Uncaught Error: Cannot update <b>4000a33db2</b>, <b>576b69e90c</b>
    throw messages.js:24
    primary_action bulk_operations.js:189
    jQuery 7
    call request.js:229
    call request.js:98
    primary_action bulk_operations.js:173
    set_primary_action dialog.js:149
    jQuery 9
    set_primary_action dialog.js:142
    make dialog.js:60
    <anonymous> dialog.js:18
    edit bulk_operations.js:149
    action list_view.js:1720
    jQuery 2
messages.js:24:7
    throw messages.js:24
    primary_action bulk_operations.js:189
    jQuery 7
    call request.js:229
    call request.js:98
    primary_action bulk_operations.js:173
    set_primary_action dialog.js:149
    jQuery 9
    set_primary_action dialog.js:142
    make dialog.js:60
    <anonymous> dialog.js:18
    edit bulk_operations.js:149
    action list_view.js:1720
    jQuery 2
```

## Additional information
Ubuntu 20, ERPNext v13 and v12 checked.

**Comment by TurkerTunali** [comment]
"End of Life" field in the Item master works as expected.

**Comment by ankush** [comment]
https://github.com/frappe/erpnext/pull/28242
