### ISSUE TITLE
Healthcare: Automated patient appointment invoicing does not work properly.

### ISSUE THREAD

**Issue by mujeerhashmi** [frappe/erpnext#26067]
## Description of the issue
The Payment fields in the patient appointment do not appear for patients with no previous appointments. 

## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 13.4.1
frappe 13.4.1
```

## Steps to reproduce the issue

1. Enable Automate Appointment Invoicing and Enable Free Follow-ups in Healthcare Settings.
2. Create a New Patient
3. Create a Patient Appointment for the patient created in step 2.

### Observed result
The Appointment is booked without a Sales invoice.

### Expected result
The Payment Fields in the patient appointment should become mandatory if no fee validity is present.

**Comment by ruchamahabal** [comment]
https://github.com/frappe/erpnext/pull/26608
