### ISSUE TITLE
empty fiels New stock entry

### ISSUE THREAD

**Issue by rubberfashion** [frappe/erpnext#26074]
## Description of the issue
Empty fields in New stock entry. When i want to create new Stock entry the error occure
Using V13.5 EDGE latest Docker container, same error in New Stock Reconciliation

<img width="1013" alt="Screenshot 2021-06-16 132951" src="https://user-images.githubusercontent.com/28510172/122211707-4fe1f200-cea7-11eb-8cc6-7d9a0449a7af.png">
<img width="1022" alt="Screenshot 2021-06-16 133801" src="https://user-images.githubusercontent.com/28510172/122212421-18c01080-cea8-11eb-91ad-45e67bff11cf.png">

Error: Empty boxes as the picture it shows
<img width="829" alt="Screenshot 2021-06-16 133328" src="https://user-images.githubusercontent.com/28510172/122211828-72740b00-cea7-11eb-95dd-4e7fac753fe0.png">
<img width="851" alt="Screenshot 2021-06-16 133635" src="https://user-images.githubusercontent.com/28510172/122212238-e6161800-cea7-11eb-8e04-182760fcd1d5.png">

**Comment by ankush** [comment]
Pretty sure you're not on `version-13` branch. `erpnext-web.bundle.js` is part of new build system in v14 (i.e. `develop` branch)

https://github.com/frappe/erpnext/commit/464d838447fe4876df25d2ee328fa6d655ce4d6b#diff-bd2e805926cad5ea95bc17785393baed47d85bfbdfe798b3432327dcbd50e722R18


Most probably you just need to build assets again and see if there are any errors stopping that.

`bench build`

**Comment by rubberfashion** [comment]
Hi, i was using the version=edge for development. 
I now switch to version=v13 in the .env of docker-compose file and everything is fine. 
I am running a docker container. 
Thanks for your answer.
