### ISSUE TITLE
Report download as xls saves to disk as zip file

### ISSUE THREAD

**Issue by timlinux** [frappe/erpnext#26072]
![image](https://user-images.githubusercontent.com/178003/122189309-bc99c400-ce88-11eb-944e-6fd212adac17.png)

![image](https://user-images.githubusercontent.com/178003/122189373-ca4f4980-ce88-11eb-822e-dbac71fdbb9f.png)

![image](https://user-images.githubusercontent.com/178003/122189271-b0ae0200-ce88-11eb-9ff6-8d2bf9ea64ad.png)

Downloaded document is saved as download.zip instead of report.xls

Renaming the file from download.zip to report.xls allows it to be openend in excel properly

**Comment by kennethsequeira** [comment]
Closing as was unable to replicate this and no further movement on the issue. 

Should this be persisting the issue can be re-opened or a new one can be registered.
