### ISSUE TITLE
diacritics, accents in custom field label

### ISSUE THREAD

**Issue by jagular** [frappe/erpnext#2608]
Description: 
Diacritics and accents i mean special symbols in latin aplhabet like (áíéůúřščřďťň), no idea how this can inpact other non latin alphabets like chinese - need to be discussed and tested.

Current feature:
Adding new custom field with label "tróll" containing non permited symbol "ó" end with error message: 
Fieldname {0} cannot contain letters, numbers or spaces
This is ok, i can just recommend change it to something more clear as "special letters" or "letters with diacritics".
After closing this error message, this new custom field is added anyway to the form, but the column in the db (tested for tabCustommer) is not added.

When we try to save new record in custommer form it ends with error:
OperationalError: (1054, "Unknown column 'tr\xc3\xb3ll' in 'field list'")
It has sense, but probably not for end user.

Proposed enhancement:
Option A  - manual (prefered)
As we can expect, that customization will do some more experienced user, this user should be able to understand the naming convention for db columns (automatic validation also needed here, but without automatic correction).
So why not use instead of only one field custom field label, also custom field db column name?
In that case there will be less limitation on custom field label (we can use diacritics) and we can keep restrictions and we have to keep validation on db column name field. Only one inconvenient will be, that user will have to fill 2 fields instead of one, and use brain.

Option B - automatic (for evaluation)
improove posting db column name from custom field label.
Mayby using some conversion tables, functions - currently behind my horizont ...
(not sure about the non latin alphabets ...)

Workaround: just edit in db tabCustom Field / label manualy ...
or
export custom_field with vallues and edit column label and import again ...

Labels: translations, feature request - enhancement proposal
Status: unconfirmed
Severity: medium for languages using diacritis
Priority: low
Versions: ERPnext v4.18.1, Frappe v4.9.3, Cart v0.6.0
Host: mariadb-server v5.5.40-0ubuntu0.14.04.1, nginx v1.4.6-1ubuntu3.1, python v2.7.5-5ubuntu3, redis-server v2:2.8.19-1chl1~trusty1
Client: Firefox 35.0

**Comment by anandpdoshi** [comment]
This
