### ISSUE TITLE
Point of Sale not loading

### ISSUE THREAD

**Issue by hballan** [frappe/erpnext#26082]
Frappe 13.5.0
ERPNext 13.5.0

![image](https://user-images.githubusercontent.com/34502442/122254470-d1507900-ced5-11eb-981d-fac3ea971f90.png)

**Comment by ankush** [comment]
Does `bench build` fix the issue?

**Comment by hballan** [comment]
Ran bench build did not resolve the issue
![image](https://user-images.githubusercontent.com/34502442/122366243-0d321f80-cf64-11eb-8f84-b869953f20fd.png)
![image](https://user-images.githubusercontent.com/34502442/122366305-1ae7a500-cf64-11eb-8821-964cc874e271.png)

**Comment by ankush** [comment]
This is not a bug, some required packages are missing. Install using `bench setup requirements`.

**Comment by hballan** [comment]
Ran bench setup requirements server error remains the same
![image](https://user-images.githubusercontent.com/34502442/122403948-75dec380-cf87-11eb-92c3-35455157d9f6.png)
![image](https://user-images.githubusercontent.com/34502442/122403973-7ecf9500-cf87-11eb-8f07-49478b6facae.png)

**Comment by ankush** [comment]
Refer to the error message. You're using Node 8.x. Recommended version for Frappe/ERPnext is node v12.x.

**Comment by hballan** [comment]
I didn't install Node, this is just the VM box downloaded from erpnext.org

**Comment by hballan** [comment]
Updated to latest version of Node still same problem
![image](https://user-images.githubusercontent.com/34502442/122407430-4d0bfd80-cf8a-11eb-8910-65b60e14beb2.png)
![image](https://user-images.githubusercontent.com/34502442/122407477-55643880-cf8a-11eb-8687-0a94cecc5282.png)

**Comment by hballan** [comment]
Also installed Node v12 as per your recommendation and same issue
![image](https://user-images.githubusercontent.com/34502442/122408246-e3d8ba00-cf8a-11eb-9de9-eb68148c7805.png)

![image](https://user-images.githubusercontent.com/34502442/122408296-ef2be580-cf8a-11eb-89a6-3a186f2ba245.png)

**Comment by ankush** [comment]
You'll have to setup the requirements again. They were not setup before because of incompatible version 😄

**Comment by hballan** [comment]
Yes I did that reran `bench setup requirements` but did not resolve the issue
![image](https://user-images.githubusercontent.com/34502442/122415049-3ff20d00-cf90-11eb-9f20-6a18457ee7bc.png)

![image](https://user-images.githubusercontent.com/34502442/122415117-4e402900-cf90-11eb-8efc-ad582f52923a.png)

**Comment by hballan** [comment]
ran `bench update` and it finally fixed the problem thanx for the help
