### ISSUE TITLE
V5 tables design - suggestions

### ISSUE THREAD

**Issue by neilLasrado** [frappe/erpnext#2609]
1. If tables are read-only, "remove", "Insert above" and "insert below" should not appear.

2. As in V4 the table name does not appear in v5. this can make things confusing like in BOM, we have raw materials and raw materials exploded. Both tables are quite similar and without a name / desc it can be difficult to understand.

3. ctrl+up, ctrl+down works on windows, on mac it must be command + up, command + down ( not sure if this one is relevant)

![screen shot 2015-01-20 at 11 37 55 am](https://cloud.githubusercontent.com/assets/8401344/5812865/f91a009a-a098-11e4-9fad-0e5c7a4d37db.png)

**Comment by rmehta** [comment]
fixed.
