### ISSUE TITLE
ERPNext V13: Payment Reconcile does not show unreconciled Payment Entry List

### ISSUE THREAD

**Issue by SoriyaKH** [frappe/erpnext#26110]
## Description of the issue
Payment Entry to purchase invoices is already submitted. Then I cancel and amend a purchase invoice (that makes the the purchase invoice is unlinked to the payment entry). After submit the purchase invoice. I go to payment reconcile. only the purchase invoice show in the payment reconcile. The payment entry does not show. So we can reconcile the purchase invoice the the payment entry.
## Context information (for bug reports)

**Output of `bench version`**
```
V13
```

## Steps to reproduce the issue

1. Make payment entry to purchase invoice then submit
2. Cancel the purchase invoice that is allected to the above payment entry. Then amend and submit purchase invoice.
3. Go to Payment Reconciliation for the above supplier and try to get the unreconciled items. Only unreconciled purchase invoice shown. There is no unreconciled payment shown.

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by nidhipurohit11** [comment]
We couldn't replicate the issue, please confirm if you are still facing this issue
