### ISSUE TITLE
We can not customize support ticket to add attach field

### ISSUE THREAD

**Issue by fadymsamy** [frappe/erpnext#2611]
We need that Support Ticket Form has a attach field to allow the customers attach any file with the ticket from customer login site.
![no attach](https://cloud.githubusercontent.com/assets/10611722/5814725/57209d68-a097-11e4-92ff-603c57cd50b0.jpg)

**Comment by pdvyas** [comment]
For now, you can use emails. Attachments are pulled in support ticket when made via email. ref: https://erpnext.com/user-guide/support/support-ticket

**Comment by fadymsamy** [comment]
Yes, I know, but we need it.
It is more important for us

Please advise ?!

**Comment by anandpdoshi** [comment]
Maybe you can hire a developer to implement this feature and contribute 
back?

fadymsamy wrote:

**Comment by fadymsamy** [comment]
Ok We have developers. how to implement that? you mean that Custom Script ?!

**Comment by anandpdoshi** [comment]
You will need to modify the erpnext code related to that support ticket 
page.

fadymsamy wrote:

**Comment by fadymsamy** [comment]
is that available for us (customer)?

**Comment by rmehta** [comment]
This is the page:

https://github.com/frappe/erpnext/blob/v5.0/erpnext/templates/pages/ticket.html

The above link is for version 5.0 which is currently in development

**Comment by rmehta** [comment]
Alternatively you can also use web forms

https://erpnext.com/user-guide/website/web-forms
