### ISSUE TITLE
Encrypting Dropbox backup - Suggestion

### ISSUE THREAD

**Issue by capfaris** [frappe/erpnext#2612]
I would suggest adding encryption feature to encrypt the backup files before uploading them to Dropbox as this would provide extra security, the encryption key should be assigned by the user.

**Comment by OneiricIT** [comment]
+1

But for any backup file, irrespective if only to the local host. Data needs to be secured even at rest.

Perhaps the Frappe team could consider automating openssl encrypt / decrypt process when backing up / restoring data?

**Comment by OneiricIT** [comment]
nudge - Any movement on this? Noticed the S3 module by Bai Labs is being integrated - should consider the encryption /decryption process with this too.

https://github.com/frappe/erpnext/issues/10644

**Comment by ankush** [comment]
https://github.com/frappe/frappe/pull/14513
