### ISSUE TITLE
Include a "Partially Paid" status in Sales Invoice

### ISSUE THREAD

**Issue by lxnow** [frappe/erpnext#26137]
Currently, the Sales Invoice form shows the form status as it relates to accounts receivable, including `paid`, `overdue`, `draft`, and so on:

![image](https://user-images.githubusercontent.com/5035210/122847946-2d365a00-d33b-11eb-97e1-8a1059bb7757.png)

For invoices that have been partially paid for but are not yet completely paid, the status is normally kept at `unpaid` or `overdue` depending on the due date. Feature request is to have new statuses called `partially paid` and `partially paid overdue`. This will be helpful for businesses that are trying to get a quick eyeball on the most important invoices that are not yet paid (at all) versus invoices that have been partially paid but still have balance to collect.

`partially paid` == (total due < unpaid amount OR paid amount > 0 but less than total due) AND due_date is <= today()
`partially paid overdue` == (total due < unpaid amount OR paid amount > 0 but less than total due) AND due_date is > today()

**Comment by sagarvora** [comment]
This has been done partly (pun intended) in https://github.com/frappe/erpnext/pull/27625. We didn't introduce a `Partly Paid Overdue` status, but the `Overdue` status was extended to cases when one of the payments in Payment Schedule is overdue.
