### ISSUE TITLE
Item and stock valuation Error

### ISSUE THREAD

**Issue by HaniTetouha** [frappe/erpnext#26154]
## Description of the issue
I am using Erpnext version 13.5.1, and facing an issue with calculating the items valuation rate, I am using FIFO on the stock valuation method setting, it seems that it calculates the valuation as average, as an example, the image below shows an item which has only two purchase prices (117, 143)  but it gives a faulty stock balance value and makes a weird drop on the incoming rate, as shown in the following image:
## Context information (for bug reports)
![Screenshot (8)](https://user-images.githubusercontent.com/16355884/122909169-33d1cb00-d355-11eb-97d3-5ddf6928fbfc.png)

On the third row, the stock qty is 5 but it gives stock valuation as if it is 1 piece (5 pcs * 117 rate, should be 585, but it shows 117).
On the 4th and 5th rows, the valuation rate has become 23 and 70 which is faulty and does not exist in reality.

**Output of `bench version`**
```
erpnext 13.5.1
frappe 13.5.1
```

## Steps to reproduce the issue

1.
2.
3.

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS 20.04/ubuntu, `Frappe` install method, etc.

**Comment by aakvatech** [comment]
Faced this as well

**Comment by THEOSKaris** [comment]
This issue is still not fixed. We set default valuation method to 'FIFO' in Stock Settings. But system adopts an average valuation rate to value outgoing items instead of valuing them in a first-in-first-out manner.

![image](https://user-images.githubusercontent.com/67414153/181284344-e01239d8-9f44-4e26-85ba-faf5ceefa65e.png)

This is a basic accounting feature, and customers/propsects will be very concerned.

**Comment by rohitwaghchaure** [comment]
@THEOSKaris 

Consider you have an Item A which you have purchased first time with Qty as 10 with rate as 100. After two days you have purchased same item with Qty as 5 with Rate as 150.

Now the total stock available is 15 and Balance as 1000 + 750 = 1750

Now here the valuation rate is 1750 / 15 = 116.66

But at the time of issue / consumption system will follow the FIFO. Essentially valuation method applies when we do actual consumption / issue / dispatch. In stock ledger report we have added column called Value Change. If you divide value change / qty then you will get the rate in which it has been dispatched.
<img width="802" alt="Screenshot 2022-11-18 at 7 43 55 PM" src="https://user-images.githubusercontent.com/8780500/202726341-06159539-4a3d-47f0-ab40-5a5cded8b56c.png">

So here valuation rate shows the average value of available stock and not shows the rate at which the materials has been consumed. Maybe we can show one more column like Consumption Rate which will show the rate at which the materials has been consumed

**Comment by rohitwaghchaure** [comment]
Fixed https://github.com/frappe/erpnext/pull/33088
