### ISSUE TITLE
(POS V13) duplicating item on discount

### ISSUE THREAD

**Issue by ferasalmah** [frappe/erpnext#26169]
when i try to add discount on item it duplicate in the cart and there is miscounting in the grand total 
![discount issue](https://user-images.githubusercontent.com/86350034/123077285-3518fb80-d41a-11eb-8165-2a0fab77c864.gif)

**Comment by AlghryaneeAnees** [comment]
ihave same issue

**Comment by Labyrinth-00** [comment]
To add to this issue, you can't remove the first item that was discounted.
