### ISSUE TITLE
Rate UOM

### ISSUE THREAD

**Issue by barredterra** [frappe/erpnext#26177]
## User story

_As a craftsmen working with roof tiles, I only ever know the price per thousand tiles. To avoid manual calculations, I always want to enter this price (per thousand), no matter which stock or transaction UOM I'm using._

### Details

In this industry, rates are always quoted relative to a quantity, say 3500 € per 1000 pieces, even when transacting individual pieces.

(A) The first idea would be to use "pieces" as stock and transaction UOM. In this case we need to manually calculate the rate per piece in each transaction, for each line item.

Let's consider how we can currently enter the rate per 1000 pieces:

(B) Use "1k Pieces" as stock UOM and transaction UOM. In this case we'll always have to multiply the stock level by 1000 to know it in pieces.

(C) Use "Pieces" as stock UOM and "1k Pieces" as transaction UOM. But in reality the transaction is for individual pieces. Just the rate is quoted per 1000 pieces. In this case we need to manually calculate the quantity in "1k Pieces" (divide by 1000).

Currently we always require manual calculations at some point. Multiplying or dividing by 1000 is easy enough, but can still lead to errors like booking 10x or 1/10 of the desired quantity. We want to get rid of manual calculations.

### Item

In the UOM table, add the columns "Rate Conversion Factor" and "Is Default Rate UOM" (can only be set in one row at a time). For, example:

<details><summary>Example</summary>
<p>

**Stock UOM**: Pieces

| UOM     | Conversion Factor | Is Default Rate UOM  |
|---------|------------------:|:--------------------:|
| Pieces | 1  |
| Pallet | 224 |
| 1000 Pieces | 1000  | ✔

Explanation: By default the rate is specified per 1000 Pieces, while being bought/sold in pieces or pallets.

</p>
</details>

### Item Quick Entry

Show additional field "Default Rate UOM". If any value is selected there and it's different from the stock UOM, show an additional field "Conversion Factor".

- **Item Price** will be created for "Default Rate UOM".
- Default Rate UOM, Conversion Factor and Checkbox (enabled) will be added to the item's UOM table.

### Item Price

Add a fields for

- Rate UOM
- Conversion Factor

When creating a new **Item Price** manually, the Default Rate UOM and Rate Conversion Factor from **Item** shall be fetched.

### Transactions

In line items, show additional fields "Rate OUM" (Link to UOM, fetch Default Rate UOM from UOM table in **Item**) and "Rate Conversion Factor" (read only).

- Rate will be relative to Rate OUM
- Fetch the correct rate from **Item Price**, if it exists for the Rate UOM. Otherwise it will be entered manually.
- Multiply the rate with the ratio of Stock UOM to Rate UOM to Conversion Factor to get the line amount

    `amount = quantity * rate / rate_conversion_factor`

<details>
<summary>Example: Default Case (current behavior)</summary>
<p>

| Item Code     | Quantity   | UOM  | Rate  | Rate OUM*   | Rate Conversion Factor* | Rate Per Stock UOM* | Amount
|---------------|----------:|------|------:|--------------|------------------------:|----------------------:|------------------:|
| Roof Tile          | 1230        | Pieces | 3.50  | Pieces              | 1                                    | 3.50                            |                 4305.00 

\* not displayed in grid view.

By default, the Rate UOM is identical to the Stock UOM, the conversion factors are 1 and everything works as before.

</p>
</details>

<details>
<summary>Example: Making use of Rate UOM</summary>
<p>

| Item Code     | Quantity   | UOM  | Rate  | Rate OUM*   | Rate Conversion Factor* | Rate Per Stock UOM* | Amount
|---------------|----------:|------|------:|--------------|------------------------:|----------------------:|------------------:|
| Roof Tile          | 1230        | Pieces | 3500.00  | 1000 Pieces          | 1000                  | 3.50                           |                 4305.00
| Screw               | 1750        | Pieces |   15.00    | Box                | 100                              | 0.015                          |                   262.50

\* not displayed in grid view.

**Row 1**: 1230 Pieces at a rate of 3500.00 per 1000 Pieces.
**Row 2**: 1750 Pieces at a rate of 15.00 per Box, containing 100 Pieces each.

</p>
</details>

This applies to all transactions where items and rates are used.

#### Note on naming

We use "Rate UOM" instead of "Price UOM". The reason for this is that the field for the unit price is called "Rate" everywhere in ERPNext and this rate shall be relative to the "Rate UOM". Naming the fields like this makes it obvious that the "Rate UOM" is the UOM for the Rate field.

### Further Reading

- https://blogs.sap.com/2019/11/08/unit-of-measure-conversion-in-manage-prices-sales-app/
- https://www.ibm.com/docs/en/order-management?topic=im-define-pricing-unit-measure-if-different-from-inventory-unit-measure
- https://docs.oasis-open.org/ubl/csd01-UBL-2.4/mod/summary/reports/UBL-Invoice-2.4.html#Table-Price.Details 

	> `BaseQuantity` -- The quantity at which this price applies.
	> `OrderableUnitFactorRate` -- The factor by which the base price unit can be converted to the orderable unit.

**Comment by ankush** [comment]
Is using a price list that's UOM independent a good workaround for this problem?

**Comment by barredterra** [comment]
@ankush I'm not sure how this would help. Can you elaborate?

**Comment by barredterra** [comment]
I see the issue that this would make item entry more complicated. If we implemented this, we would need an option to toggle this behavior only for companies who really need it.

We have implemented “Rate UOM” in a private custom app for the time being. If anybody wants to contribute this feature, please get in touch for access to the existing code. Closing this issue for now.

**Comment by dj12djdjs** [comment]
@barredterra I also have a requirement for Rate UOM, although I'm not 100% sure your example will fit my requirement. 

In my example, I'm purchasing oil. I'm purchasing 1 case, which will be sold as 3 individual units containing 4.73 liters each.
I'm then being billed $7.70 per liter. 

| Item Code   | Qty  | UOM  | Stock UOM | Qty In Stock UOM | Rate UOM | Qty In Rate UOM | Rate | Amount |
|-------------|------|------|-----------|------------------|----------|-----------------|------|--------|
| 0W16 3/4.73 | 1.00 | Case | Unit      | 3                | Liter    | 14.19L          | 7.70 | 109.26 |

Would your custom app fit this use case?

**Comment by barredterra** [comment]
@dj12djdjs yes, that sounds like the same use case 👍

**Comment by almuallim22** [comment]
@barredterra Hello. I need this private custom feature. Guide me please on how I get code. Thank you
