### ISSUE TITLE
Item Code must be unique - create 2 prices for one item

### ISSUE THREAD

**Issue by rubberfashion** [frappe/erpnext#26200]
Installed Apps
ERPNext: v13.5.1 (version-13)
Frappe Framework: v13.5.2 (version-13)
docker framework.
bench migrate done

Hi, i got an error, when i want to create two prices for one item (with different price lists). I know that this function was OK some weeks ago and i do not know where the issue is.
I use 2 different price lists.
When i want to create 2nd price i got the error:
![grafik](https://user-images.githubusercontent.com/28510172/123252103-36b2f400-d4ec-11eb-8956-720957e35e41.png)
![grafik](https://user-images.githubusercontent.com/28510172/123252174-4a5e5a80-d4ec-11eb-8a05-a6c8a3d1ec76.png)
Fields:
![grafik](https://user-images.githubusercontent.com/28510172/123252237-5a763a00-d4ec-11eb-8984-e67d5cf81148.png)
As i remember i added these field not to have these cryptic numbers:
![grafik](https://user-images.githubusercontent.com/28510172/123252395-84c7f780-d4ec-11eb-9976-51c988afbbe1.png)
I also delete this information, but the error will not disappear.
Any recommendations?

**Comment by rubberfashion** [comment]
I could reproduce the error.
The error occure, when no price elements are set.
Then by setting the Naming field:item_code the item_code get "unique".
When you delete Naming field and deactivate item_code "unique" you will get the same error. It is not possible to reset this and the error occure again and again.
When you delete the index Key Name index_code_2 contrain this will solve the problem.
![grafik](https://user-images.githubusercontent.com/28510172/123286485-3e839000-d50e-11eb-9fa3-788bebbc03e8.png)

**Comment by ankush** [comment]
remove the autoname that you've added. Name is primary key and hence can't be duplicated.
