### ISSUE TITLE
V5 awesomebar error - Shows <b> tags

### ISSUE THREAD

**Issue by DrTrills** [frappe/erpnext#2620]
Latest version of V5 shows

    <b> </b>

tags in calculation, and query 

![screen shot 2015-01-21 at 1 51 44 pm](https://cloud.githubusercontent.com/assets/1430005/5842679/b6b481a8-a174-11e4-8ee1-9ff844b4c33b.png)

![screen shot 2015-01-21 at 1 53 19 pm](https://cloud.githubusercontent.com/assets/1430005/5842701/e9566b80-a174-11e4-865f-033109fe42e4.png)

**Comment by neilLasrado** [comment]
I believe this has been solved.
Was not able to replicate.

**Comment by DrTrills** [comment]
@neilLasrado Just ran an update and it is no longer doing this. Glad this got fixed :)
