### ISSUE TITLE
BOM: Update Cost button does not work unless BOM is submitted

### ISSUE THREAD

**Issue by nameduser0** [frappe/erpnext#26215]
BOM: Update Cost button does not work unless BOM is submitted

Messages complain that valuation rate for sub-item (based on submitted BOM) does not exist when the button is pressed in a draft state. Works if after the BOM you are working on is in submitted state.

Would expect the rate to be updated if it exists in all states.

**Output of `bench version`**
```
ERPNext: v13.5.0 (version-13)
Frappe Framework: v13.5.1 (version-13)
```

**Comment by ankush** [comment]
closed by https://github.com/frappe/erpnext/pull/26279
