### ISSUE TITLE
bug: Work Orders created from multi-level BOM operation sequence order

### ISSUE THREAD

**Issue by nameduser0** [frappe/erpnext#26216]
When a work order is compiled from multi-level BOMs and/or multiple Sales Orders with items containing the same operations, the operations are assembled together in an arbitrary order. This means they must be manually reordered each time a work order is created.

Along with #17872 this makes multi-level BOM work orders and therefore job cards pretty unusable.

**Output of `bench version`**
```
ERPNext: v13.5.0 (version-13)
Frappe Framework: v13.5.1 (version-13)
```

**Comment by ankush** [comment]
This will get fixed by https://github.com/frappe/erpnext/pull/25886
