### ISSUE TITLE
v13 Tools module not available to all roles

### ISSUE THREAD

**Issue by franciscobuendiao** [frappe/erpnext#26262]
## Description of the issue
Tools module isn't available to all roles. User has to have "Accounts Manager" and/or "Accounts User" roles selected.

At first "Tools" module depends on having selected "**Automation**" at User > Allow Modules. There's not even a "Tools" module-def.

## Context information (for bug reports)

**Output of `bench version`**
```
ERPNext: v13.5.2 (version-13)
Frappe Framework: v13.5.2 (version-13)
```

## Steps to reproduce the issue

1. "Accounts Manager" and/or "Accounts User" roles unselected.
![Captura de Pantalla 2021-06-29 a la(s) 20 44 57](https://user-images.githubusercontent.com/25084259/123889628-898d1100-d91b-11eb-99ce-f46ea2ae4ab6.png)

2. "Automation" selected
![Captura de Pantalla 2021-06-29 a la(s) 20 45 32](https://user-images.githubusercontent.com/25084259/123889689-a3c6ef00-d91b-11eb-8b20-ea4cfc89a287.png)

3. "Tools" module not available
![Captura de Pantalla 2021-06-29 a la(s) 20 46 37](https://user-images.githubusercontent.com/25084259/123889732-b6d9bf00-d91b-11eb-8a29-4d399b08d8c0.png)

4. "Accounts Manager" and/or "Accounts User" roles selected.
![Captura de Pantalla 2021-06-29 a la(s) 20 52 45](https://user-images.githubusercontent.com/25084259/123889907-fdc7b480-d91b-11eb-9b4a-430e7af4b781.png)

5. "Automation" selected
![Captura de Pantalla 2021-06-29 a la(s) 20 45 32](https://user-images.githubusercontent.com/25084259/123889689-a3c6ef00-d91b-11eb-8b20-ea4cfc89a287.png)

6. "Tools" module available
![Captura de Pantalla 2021-06-29 a la(s) 20 47 40](https://user-images.githubusercontent.com/25084259/123889986-1b951980-d91c-11eb-9de8-0c997dc24644.png)

### Expected result
"Tools" module available to all roles

**Comment by yadavyk** [comment]
This is fixed, hence closing.
