### ISSUE TITLE
Decimal separator not recognized in setup wizard v5

### ISSUE THREAD

**Issue by Steggur** [frappe/erpnext#2627]
When adding tax accounts during setup wizard.
I have chosen Icelandic and the correct currency and timezone come up.
But when I enter the tax rate 25,5 everything appears OK.
But after the wizard finishes and I look at the particular account the rate is 255?
It seems that ERPNext is expecting . (period) not , (comma) as the decimal separator.
I am wondering if this is the way it should be?

**Comment by anandpdoshi** [comment]
Thanks for reporting this.

I suppose currency and number format should also be asked before you are asked to enter rate / amounts.

We will fix this in v5.
