### ISSUE TITLE
bug: BOM variant creation inserts wrong child links

### ISSUE THREAD

**Issue by nameduser0** [frappe/erpnext#26297]
## Description of the issue
On creation of variant BOMs from template BOMs, ERPNext is linking the parent BOM of a component as a child. This completely breaks all the costing, work orders and job cards.

Template BOM:
![BOM Template](https://user-images.githubusercontent.com/64409021/124244116-814cf580-db16-11eb-9f73-7f29d799c264.png)

Variant BOM:
![BOM Variant Error](https://user-images.githubusercontent.com/64409021/124244134-85791300-db16-11eb-827e-33e57fc3cc9e.png)

## Context information (for bug reports)

**Output of `bench version`**
```
ERPNext: v13.5.0 (version-13)
Frappe Framework: v13.5.1 (version-13)
```

## Steps to reproduce the issue

1. Create template and variant items of product plus components
2. Create template BOM
3. Use menu to create variant BOMs

### Observed result
See screenshots above

### Expected result
No unnecessary nesting, structure should match the template

**Comment by nameduser0** [comment]
@ankush Hi Ankush, do you know if your latest manufacturing/BOM changes released in v13.6.0 have fixed this issue?

**Comment by ankush** [comment]
@casesolved-co-uk No, I don't think those changes had anything to do with variant / template BOM creation.

**Comment by nameduser0** [comment]
@ankush Okay thanks for the quick reply. I'll try to find and fix the bug...

**Comment by nameduser0** [comment]
@ankush can you make sure #26320 gets merged asap please? This is a really horrific show-stopping bug.

**Comment by martinhbramwell** [comment]
+1
