### ISSUE TITLE
fix: Payments shows company currency instead of transaction currency symbol in Payment Reconciliation

### ISSUE THREAD

**Issue by aakvatech** [frappe/erpnext#26293]
## Description of the issue
1. Pass a EUR receipt from export customer in an EUR currency bank account on an INR company.
2. Pass an EUR Sales Invoice
3. Load the customer in Payment Reconciliation doctype and Get Unreconciled Invoices.
4. You will see INR symbol in EUR receipt in Payment Reconciliation Payment child table.

## Context information (for bug reports)
DIfferent currency in Bank Account and Payment Entry (type Receive)

**Output of `bench version`**
erpnext 13.5.0
frappe 13.5.1

## Steps to reproduce the issue
1. Pass a EUR receipt from export customer in an EUR currency bank account on an INR company.
2. Pass an EUR Sales Invoice
3. Load the customer in Payment Reconciliation doctype and Get Unreconciled Invoices.

### Observed result
You will see INR symbol in EUR receipt in Payment Reconciliation Payment child table.

### Expected result
You should ERU symbol in EUR receipt in Payment Reconciliation Payment child table.

### Stacktrace / full error message
n/a

## Additional information
FC

**Comment by aakvatech** [comment]
![image](https://user-images.githubusercontent.com/35020381/124179733-e7f0f580-dabb-11eb-9594-beff47cebbdb.png)

This client script overcomes certain scenario but doesn't help always. The currency field of "Payment Reconciliation Payment" child doctype should be populated correctly when the Get Unreconciled Items is clicked.

**Comment by Anuja-pawar** [comment]
Fixed in https://github.com/frappe/erpnext/pull/27128
