### ISSUE TITLE
Error in POS(point-of-sale) 

### ISSUE THREAD

**Issue by arminazimi** [frappe/erpnext#26308]
I have got this error when I changed my language to fa and now pos doesn’t work but when I change the language to en pos works.
my frappe and erpnext version is 13.3
the error is :
![error](https://user-images.githubusercontent.com/33401832/124343967-80eb4380-db84-11eb-87ea-52ebfaa0de41.png)

**Comment by ankush** [comment]
this is odd error with localstorage exceeding capacity... you can remedy this by force reload. Nothing to do with language I think.
