### ISSUE TITLE
Paid amount is not allocated as appropriated in payment entry. Allocated amount is equal to paid amount. - v13.6.0 (version-13)

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#26313]
![image](https://user-images.githubusercontent.com/1822868/124356116-1508e980-dc1d-11eb-9665-a6c8381eff6d.png)

**Comment by muchai** [comment]
In addition the get outstanding invoices, includes even returned invoices.

**Comment by yadavyk** [comment]
@muchai , could you please share more details like steps to replicate, GIF, version etc. ?

**Comment by muchai** [comment]
This was fixed.
