### ISSUE TITLE
Pos Discount

### ISSUE THREAD

**Issue by tedyswaga** [frappe/erpnext#26325]
POS discounts missing discount as value and when rsate is changed it doesn't update immediately on the payment tab

**Comment by nextchamp-saqib** [comment]
@tedyswaga

Hi,

Can you elaborate how and on what action are you facing the issue? Do you mean, changing the rate after setting the discount causes problem?

**Comment by tedyswaga** [comment]
the default value in  mode of payment doesn't change to the edited rate, if u chate rate from 1500 to 1000 and click on check the default value in Cash is 1500.
Secondly there is no way to input discount as value only in percentage. let say the total sale is 1500 and you want to charge the client 1400 u have to manually calculate the  x/100 * 1500 = 1400, so as to find the discount in %

**Comment by tedyswaga** [comment]
![error](https://user-images.githubusercontent.com/28439380/125830399-dc5547ee-4a77-46ae-a8f9-6125f3c233f2.png)
