### ISSUE TITLE
ERPNEXT V5 Login Issues

### ISSUE THREAD

**Issue by amruthp** [frappe/erpnext#2632]
After the Latest update of ERPNExt V5, I'm unable to Login at all. No Error is displayed.

**Comment by chafor** [comment]
I'm having the same issue with the last update!

**Comment by rmehta** [comment]
We are unable to replicate it. Did you try restarting the bench? Do you see any trace on the bench console?

**Comment by pdvyas** [comment]
Can you check nginx logs for permission denied errors?

**Comment by amruthp** [comment]
You can check the instatallation here 
http://128.199.32.230/login
user: Administrator
pwd: 19DWDK206JFTow7s

After the last update around 4 days ago, login is redirecting to login page again and again. 
No nginx errors.

**Comment by pdvyas** [comment]
Yeah, jQuery doesn't load,

Try
```
cd /home/frappe/frappe-bench
find . -type d -print0 | xargs -0 chmod 0755
find . -type f -print0 | xargs -0 chmod 0644
```
 and try again. Restart nginx to be sure

**Comment by amruthp** [comment]
El perfecto. Works like a breeze :)

**Comment by pdvyas** [comment]
Nice, so need to add `bench fix-perms` command now :)

**Comment by chafor** [comment]
It is working for me to!  Thank you
