### ISSUE TITLE
bug: Stock Reconciliation overwrites values if warehouse is completed after qty and valuation rate [UX]

### ISSUE THREAD

**Issue by nameduser0** [frappe/erpnext#26337]
## Description of the issue
When completing a stock reconciliation from a stock take, the UI expects the user to complete fields in a particular order, otherwise the values they enter will be overwritten, wasting time.

See also #26317

## Context information (for bug reports)

**Output of `bench version`**
```
13.6
```

## Steps to reproduce the issue

1. Create a stock reconciliation set to opening stock
2. Enter item code & qty
3. Pick warehouse

### Observed result
qty is replaced

### Expected result
completed fields are not replaced

**Comment by nameduser0** [comment]
@yadavyk what about this can't you reproduce? What version are you trying?

**Comment by yadavyk** [comment]
@casesolved-co-uk , tried on 13.6.

**Comment by ankush** [comment]
Qty is replaced by qty that is present in the warehouse. Is this really bad UX?

The form order is correct at least. 

Item > warehouse > qty gets updated, you can now modify it to reconcile with real stock. 

We can ignore updating it if it's Non-zero, but that will again be confusing. Not sure there's any good solution UX wise. 

![Screenshot 2021-07-21 at 1 06 05 PM](https://user-images.githubusercontent.com/9079960/126449957-eda25f13-74cf-46bf-abdc-bf59fa7fc037.png)

**Comment by nameduser0** [comment]
As a rule the UX should *NEVER* overwrite user values.
"The customer is always right"
`if not value then fetch`

**Comment by ankush** [comment]
There's no solution that will be foolproof. The best we can do is maintaining updates in form order.

This is still kinda broken in case of batch nos, will send a fix for that.

**Comment by ankush** [comment]
@casesolved-co-uk https://github.com/frappe/erpnext/pull/30445 this might solve your problem... added an option called "scan mode" to disable replacing "qty" and "serial_nos" (those are usually reconciled)
