### ISSUE TITLE
Get Items From in Maintenance Visit

### ISSUE THREAD

**Issue by wojosc** [frappe/erpnext#26336]
Hi everyone!

In Maintenance Visit you are not able to fetch from more than one sales order
![fetch_from_maintenance](https://user-images.githubusercontent.com/22279621/124463541-56230a00-dd93-11eb-8ab2-c1b331fd66dc.gif)

**Comment by wojosc** [comment]
the same is when fetching several at the same time
![fetch_from_maintenance_2](https://user-images.githubusercontent.com/22279621/124463713-92566a80-dd93-11eb-9749-5711d6b6d173.gif)

**Comment by wojosc** [comment]
Hi,

I had a look in https://github.com/frappe/erpnext/wiki/Module-Maintainers and found that @PawanMeh and @hrwX are listed as maintainers for this modul.

We are looking to give this into payed development to get this fixed. @PawanMeh can we maybe have a quick call over this so that funds are allocated sensibly?

Best
Wolfram

**Comment by PawanMeh** [comment]
@wojosc you can check the [pull request ](https://github.com/frappe/erpnext/pull/26924/files). This should fix the issue.
