### ISSUE TITLE
Processed Qty/Amount tracking

### ISSUE THREAD

**Issue by SAJOIJOM** [frappe/erpnext#2633]
There needs to be a customizable option to track the processed qty/amount on any voucher and to report the linked voucher. For example, from an opportunity if multiple quotations are made, and one is finalized and is processed as sales order, we would like to close all the other open quotations against that opportunity. This will allow analysis on the quotations and to do follow up by sales team.

The same feature is useful at the level of Quotations to sales order too.

And if we would like to search for a sales order, and to know what are the linked voucher against it, to audit the un processed one, currently we have to depend on the updation on the status field!

The above requirement is based on a trading company. If it is on a service company, the same changes to amount instead of quantity for easy analyzing.

**Comment by SAJOIJOM** [comment]
And ultimately, if a person need to know what is the status of a sales order, there should be a way to track the last linked voucher number on the series - If the sales order is linked to only purchase vouchers - like materials request and then to purchase order- the status should show "purchase order number". If it is linked to sales side too - like delivery note and sales invoice- it should show "sales invoice number"

**Comment by PawanMeh** [comment]
Latest release has better document linkages, kindly check

![screen shot 2017-05-03 at 3 52 02 pm](https://cloud.githubusercontent.com/assets/20460498/25656866/b2fa15ac-3018-11e7-988f-ad5cadc7048c.png)
