### ISSUE TITLE
repost_item_valuation.repost_entries

### ISSUE THREAD

**Issue by HaniTetouha** [frappe/erpnext#26372]
## Description of the issue

After updating to version 13, we not got many failed jobs in the "Scheduled Job Log" as shown bellow.
And also we now receive message that promote that the Stock and ledger are out of sync and forbids any further transactions till we make a journal entry to balance the Stock and Ledger.

## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 13.6.0
frappe 13.6.0
```
### Stacktrace / full error message

```
Traceback (most recent call last):
  File "/home/user/frappe-bench/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 81, in execute
    frappe.get_attr(self.method)()
  File "/home/user/frappe-bench/apps/erpnext/erpnext/stock/doctype/repost_item_valuation/repost_item_valuation.py", line 132, in repost_entries
    check_if_stock_and_account_balance_synced(today(), d.name)
  File "/home/user/frappe-bench/apps/erpnext/erpnext/accounts/utils.py", line 998, in check_if_stock_and_account_balance_synced
    frappe.msgprint(
  File "/home/user/frappe-bench/apps/frappe/frappe/__init__.py", line 411, in msgprint
    _raise_exception()
  File "/home/user/frappe-bench/apps/frappe/frappe/__init__.py", line 365, in _raise_exception
    raise raise_exception(msg)
erpnext.accounts.utils.StockValueAndAccountBalanceOutOfSync: Stock Value (268169.044) and Account Balance (269865.84) are out of sync for account <b>1420 - مخزن المبيعات - AIT</b> and it's linked warehouses as on 2021-07-03.<br></br>Please create an adjustment Journal Entry for amount <b>-1696.796</b> on <b>2021-07-03</b><br></br>
```

## Additional information

OS 20.04 / ubuntu, `ERPNext` install method manual, etc.

**Comment by nzepa74** [comment]
dfg

**Comment by HaniTetouha** [comment]
Issue still exists

**Comment by HaniTetouha** [comment]
Updated to v13.8.0 and this issue still exists

**Comment by ankush** [comment]
Open "stock and account value comparison" report and see which transactions have differences.

**Comment by HaniTetouha** [comment]
@ankush 
the stock and account value comparison report shows no results

**Comment by HaniTetouha** [comment]
Any updates regarding this issue?

**Comment by ankush** [comment]
This validation is removed in latest release since it was incorrectly flagging differences. 

If you do spot and historical differences from that report, you can make a journal entry to match the account balance to be the same as the stock balance (by posting the difference).
