### ISSUE TITLE
bug in Delivery date

### ISSUE THREAD

**Issue by BOB1212121** [frappe/erpnext#26373]
once i add item with an old date it can't be modified even it canceled and amended again
https://user-images.githubusercontent.com/86354095/124779606-35e57d80-df42-11eb-8f25-f547a79131e2.mp4

**Comment by ankush** [comment]
That field is set to the maximum of all items' delivery dates. So you need to change the delivery date in the child table. This is not a bug, maybe UX can be improved.


https://github.com/frappe/erpnext/blob/7f932cfb30f32224cbf500efa86ea7d87462b543/erpnext/selling/doctype/sales_order/sales_order.py#L101-L112
