### ISSUE TITLE
Item Price not fetched based on Batch

### ISSUE THREAD

**Issue by manan-ft** [frappe/erpnext#26377]
## Description of the issue
Newly introduced Batch Wise Item pricing [https://github.com/frappe/erpnext/pull/24470] is not working for multiple batches

## Context information (for bug reports)
Created two Batches for an Item and received 10 Nos and 6 Nos in two batches at 1500 and 1600 respectively.
Then added Item price for each batch as 2000 and 2200 respectively
When creating a Delivery Note or Sales Invoice with Batch 2, it is not fetching the Rate defined on Item Price for that Batch

**Output of `bench version`**
```

ERPNext: v13.6.0 (version-13)

Frappe Framework: v13.6.0 (version-13)

```

## Steps to reproduce the issue

1. Create an Item 1 with Serial No and Batch No enabled
2. Create `Purchase Receipt` with 10 Qty at 1500 each, Batch 1
3. Create `Purchase Receipt` with 5 Qty at 1600 each, Batch 2
4. Add `Item Price` for Item  1, Batch 1, Selling at 2000
5. Add `Item Price` for Item  1, Batch 2, Selling at 2200
6. Create a `Delivery Note` for Item 1 from Batch 2 and Save the Delivery Note

### Observed result
Rate is not fetched for Batch 2 as defined in Step 5 above

### Expected result
Rate should be fetched from Batch 2 Item Price as defined in Step 5 of Steps to reproduce the issue

### Stacktrace / full error message

```
No error
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

OS: Ubuntu 20
Easy Install Script with some variation to make it work

**Comment by ankush** [comment]
https://github.com/frappe/erpnext/pull/27566
