### ISSUE TITLE
Employee Leave Balance shows wrong balance

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#26395]
The report shows as if leave days were deducted twice, even though twas one application.

Employee Leave Balance Summary shows figures correctly.

Leave Ledger Entry contains one entry after a leave application.

Frankly, a few bugs have popped up in ver 13 in the leave module.

**Comment by muchai** [comment]
In the example below
![image](https://user-images.githubusercontent.com/1822868/124972291-d74bfc80-e032-11eb-96c1-8be9fbe2ad40.png)

It would be expected:

- 18.25 to be under opening balance.
- 10.5  to be under Leave Allocated
- 28.75 to be under Closing Balance
- and nothing under Leave Expired

This problem still affects actual leave days. During Leave Application the system shows previous balance as 10.5, and deducts from 10.5, instead of 28.75.

**Comment by pateljannat** [comment]
@muchai , can you share the filters that you selected in the Employee Leave Balance Report, and also the Leave allocation document

**Comment by muchai** [comment]
@pateljannat 
First I have Leave Type settings as below.
![image](https://user-images.githubusercontent.com/1822868/125159061-b04e1180-e17d-11eb-9439-ea0556a5beda.png)

Then I manually create a Leave Allocation for Year 2020, i.e for days carried over from 2020
![image](https://user-images.githubusercontent.com/1822868/125159362-9b727d80-e17f-11eb-9813-2bbf1e4678ea.png)

Then I create a Leave Policy Assignment for Year 2021 as below.
![image](https://user-images.githubusercontent.com/1822868/125159444-07ed7c80-e180-11eb-9149-92f9c2669205.png)

Which creates the below Leave Allocation.
![image](https://user-images.githubusercontent.com/1822868/125159585-03759380-e181-11eb-9ddf-6165a6b12c39.png)

The Leave Allocation is as follows
![image](https://user-images.githubusercontent.com/1822868/125159612-286a0680-e181-11eb-81d9-95207f141918.png)


Leave Balance Report
![image](https://user-images.githubusercontent.com/1822868/125159766-1e94d300-e182-11eb-9a09-e6d081377cbf.png)

Ok, the system doesn't allow more than 21 days as defined in the leave type, but this should be acceptable. Othewise the employee loses last year leave days. And max cannot be more than 21 days, as earned leave will generate more than 21 days.

The bug report was a bit different, as I was using Date of Joining instead of Leave Period on the Leave Assignment Policy. Using Leave Period, yields days as expected, save that it doesn't allow more than 21 days defined as max days on the leave type.

**Comment by pateljannat** [comment]
@muchai so you are saying the problem is it's showing Opening balance as 21 and not 28.75?

**Comment by muchai** [comment]
@pateljannat Yes, there's the showing Opening balance as 21 and not 28.75.

Plus, see the Employee Leave Balance report after applying for 3 days of annual leave.
![image](https://user-images.githubusercontent.com/1822868/125240559-f24c9400-e2f2-11eb-90d9-85cbb717c7e1.png)

The issue is the report tough, since the Employee Leave Balance Summary displays the correct balance after applying for 3days.
![image](https://user-images.githubusercontent.com/1822868/125240900-67b86480-e2f3-11eb-9aad-c120311f7dea.png)

**Comment by muchai** [comment]
Related bugs:
https://github.com/frappe/erpnext/issues/26393
