### ISSUE TITLE
Earned leave assigns all days for anyone employed after end of the last complete month.

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#26393]
Scenario.

Define annual leave of 21 days, and set it has earned monthly.
Set an employee date of joining as 1st of July 2021
On 8th July 2021, use the leave policy assignment to allocate leave to the employee.
The system allocates the full 21 days

Anyone whose joining date is June 30th or lower, the days are prorated correctly.

**Comment by ruchamahabal** [comment]
Fixed in: https://github.com/frappe/erpnext/pull/29163
