### ISSUE TITLE
Roles in Workflow Causing Documents to Fail Saving

### ISSUE THREAD

**Issue by justinaquinocgg** [frappe/erpnext#26402]
Reported an Issue 

Could not find User: Purchase Request for TEST Laminate, White, Gloss, 4'X8'

## Description of the issue
PROBLEM - We cannot SAVE Material Request (MR). Something about the roles is causing the error. 

SYMPTOMS

## Context information (for bug reports)
![image](https://user-images.githubusercontent.com/68463861/125049772-e6cf5200-e0d3-11eb-9dab-72ae1ba4ef07.png)
1. Replicated in VM when using Backup and Restore. 
2. MR cannot save - it will take a minute or two and then the system will report “Not Saved”
3. HTOP shows the RAM did not increase in usage, never maxing out. 
4. MR was slowing down prior to saving issue. From 5-15 seconds in ideal conditions to 1-2 minutes. 
5. It is the Number of Records (currently at 669) that the Saving began to Fail consistently. 
6. An Error stating the “Could not find User: Purchase Request for TEST Laminate, White, Gloss, 4'X8'
7. We Discovered it was from the Roles. When we switched the Roles to ALL, the system performed very well, saving
8. Purchase Orders are unaffected, they save in 5-15 seconds even at 550 Records. 
9. We applied Innodb_buffer_poolside optimization and MariaDB fine-tuning and no change in problems conditions.
10. We increased the gunicorn from the default and there is no change in the conditions. 
11. We made new Roles and the New Roles works, we can save. 
12. 
**Output of `bench version`**
ERPNext: v12.22.0 (version-12) [Release Note] 
```
ERPNext Version 12.22.0 and Frappe Version 12.19.0 - Release Notes 
Frappe Framework: v12.19.2 (version-12)
```

## Steps to reproduce the issue

1. at 600 Records with Material Request with Manufacturing user
2. Create a Workflow with 4-6 levels of Reviewing and Checking 
3. Attempt to Save

### Observed result
Over time the saving got slower and slower. As we hit 669 records we could not save.
### Expected result
We would be able to Save
### Stacktrace / full error message
https://drive.google.com/drive/folders/1ncmvaGaoCfzPTJS_J3E1cBkNvnxm081g?usp=sharing  
```
(paste here)
```

## Additional information
Ubuntu 18.04 
Frappe Install Method
OS version / distribution, `ERPNext` install method, etc.

**Comment by JRiesgo-05** [comment]
any update on this?
