### ISSUE TITLE
Not able to run any bench command and site showing Internal Server Error

### ISSUE THREAD

**Issue by henrynewman** [frappe/erpnext#26424]
Hello everyone, I tried upgrading to V13 from V12 and after running `bench switch-to-branch version-13 frappe erpnext --upgrade` I get the below error and somehow I cant use bench.

` Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.5/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 142
    db: typing.Union[MariaDBDatabase, PostgresDatabase]
      ^
SyntaxError: invalid syntax

Traceback (most recent call last):
  File "/usr/local/bin/bench", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.5/dist-packages/bench/cli.py", line 48, in cli
    if sys.argv[1] in get_frappe_commands() + ["--site", "--verbose", "--force", "--profile"]:
TypeError: unsupported operand type(s) for +: 'NoneType' and 'list' `

ERP is no longer functional as it is now showing an Internal Sever error message. Seems like I'm not the only one that is experiencing this as other users are stressing this as well in the forum.

**Comment by henrynewman** [comment]
https://discuss.erpnext.com/t/how-to-upgrade-to-v13/73769/5?u=henrynewman

**Comment by ankush** [comment]
You're using python2. Version-13 only supports version 3.6+

Python2 EOL was some time ago and we won't be supporting it. https://www.python.org/doc/sunset-python-2/
