### ISSUE TITLE
FV5: While trying to save new 'Lead' form  it shows  error like "Duplicate name Lead LEAD-00001 Lead LEAD-00001 already exists"

### ISSUE THREAD

**Issue by geetanjalishitole** [frappe/erpnext#2642]

**Comment by neilLasrado** [comment]
Unable to replicate. @geetanjalishitole can you please provide some more details of steps you took / screenshot.

**Comment by geetanjalishitole** [comment]
![leadform_error](https://cloud.githubusercontent.com/assets/10721156/5955424/a8dd8b88-a7c8-11e4-82fa-3a5e06280d70.png)

**Comment by geetanjalishitole** [comment]
When we try to save above form ,got error message 
![error_message](https://cloud.githubusercontent.com/assets/10721156/5955457/0315bc1a-a7c9-11e4-92bd-9f6c79d03216.png)

**Comment by rmehta** [comment]
could not replicate - seems like a local issue.
