### ISSUE TITLE
bug: BOM Item image field not showing on print

### ISSUE THREAD

**Issue by nameduser0** [frappe/erpnext#26437]
## Description of the issue
The BOM Item has two fields related to the image:
`image` [Attach] and `image_view` [Image]

The `image_view` field does not show on the print format. This may be because the first row does not have an image and so the code removes the entire column.

Also, shouldn't this just be a single [Attach Image] field like the BOM?

Workaround: the `image` field does show on the print format

## Context information (for bug reports)

**Output of `bench version`**
```
13.6
```

**Comment by ankush** [comment]
BOM's image field is read-only and picked from the item's image. The confusion is from framework showing upload button when it shouldn't be possible. 

moved to https://github.com/frappe/frappe/issues/14915

**Comment by nameduser0** [comment]
@ankush  No, you didn't read the bug properly. This is a bug with the BOM **ITEM** table. Nothing to do with the BOM.

**Comment by ankush** [comment]
yeah, it seems I mixed two different issues

**Comment by s-aga-r** [comment]
@nameduser0  this is not a bug. The Print Hide is by default checked/enabled for the BOM Item Image field. 

DocType > BOM Item
![image](https://user-images.githubusercontent.com/63660334/199188972-a1a5b7a6-13ca-4e4d-bcda-b61dfa6573f3.png)

You can use the "Customize Form" to uncheck the same.

![image](https://user-images.githubusercontent.com/63660334/199190356-6da6f124-82c2-4522-a09c-9c9c9a236f2d.png)
