### ISSUE TITLE
Modify accounting transactions to be through journal entry instead of direct Ledger

### ISSUE THREAD

**Issue by alaliRuba** [frappe/erpnext#26430]
**Describe the solution you'd like**
      We need to apply the following accounting controlling logic on ERPNEXT: 
       Modify the process of accounting modules’ transactions to be through a journal entry or direct on the General ledger according to business needs. our goal from this modification makes modules’ transactions such as Loan (repayment, Disbursement …) - Sales - Purchasing create journal entry instead of direct General Ledger movements and that aim for:
1. make central accounting module (journal entry) that affects Gl.
2. Reversal capability of a journal entry.

**Describe alternatives you've considered**
In order to achieve that we made the below modification:

**1- Configuration of doctype's transactions accounting**
create customization doctype that includes configurations such as:
1- Document type (loan repayment …)
2- if through journal entry you need to (check include box) or it will be Direct GL
3- we still working on cancellation options

![image](https://user-images.githubusercontent.com/70889651/125193921-a1d42880-e257-11eb-95e6-cd728ee11930.png)

**2- Modify the make_gl_entries** 
we modify the make_gl_entries in global file **general_ledger.py** to create journal entry instead of direct Gl when document type is marked as through journal entry in Configuration.
according to that:
1- journal entry will be created with two customized fields to link document with journal entry (Source Type, Source Type Name)
![image](https://user-images.githubusercontent.com/70889651/125194058-4b1b1e80-e258-11eb-9283-0ea09cc107fa.png)

2- we pass the same (against_voucher, against_voucher_type, party, reference_type, reference_name … ) in other words (**GL_map**) from document to journal entry and then to General ledger
![image](https://user-images.githubusercontent.com/70889651/125194083-66862980-e258-11eb-99d4-53b7ff8be093.png)

we need kindly your help with below @PawanMeh @nextchamp-saqib @deepeshgarg007:
1- in our modification, the voucher number in GL is journal entry name as standard in erpnext.
our concern is there any reports - module - event … in erpnext that build on this link between voucher number in GL and transaction and will be affected by our modification ?
2- is their other approach will be more effective to achieve our goals??

Thanks and Best Regards,

**Comment by nzepa74** [comment]
sds
