### ISSUE TITLE
Expense Claim remains unpaid after allocation of employee advance

### ISSUE THREAD

**Issue by sjain17** [frappe/erpnext#26445]
## Description of the issue

**Expense Claim remains Unpaid even after allocation of employee advance**

## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 13.5.0
frappe 13.5.0
```

## Steps to reproduce the issue

1. Create and Submit Employee Advance of INR 12000 (EAD-HR-2021-0001)
2. Make Payment against employee advance.
3. Create expense claim (EXP-HR-2021-0001) of INR 12300 and allocate advance of 12000 (EAD-HR-2021-0001).
4. Grand Total = INR 230, Total Advance = 12000, Total Claimed Amount = 12300
5. Now submit the expense claim. The status changed to **Unpaid**
6. Create & Submit payment entry of remaining amount i.e.,INR 230 from create button on expense claim.
7. Status of Expense Claim is still Unpaid.

### Observed result
1. Status shows **Unpaid** and create payment button is still visible. However, when tried creating again a payment it shows 0 amount in payment entry.
### Expected result
1. Status of expense should be changed to **Paid**, as the complete payment is done against expense claim (12000 through advance and 230 through payment entry)

### Stacktrace / full error message

```
NO ERROR MESSAGE.
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by Alex092021** [comment]
I am facing same issue
![Expense Claim Status](https://user-images.githubusercontent.com/94236409/142405842-dc1dfc87-bc34-497f-a5b8-cb607c9e6575.gif)

**Comment by santoshbb** [comment]
I am facing the same issue

Installed Apps
ERPNext: v13.14.1 (version-13)
Frappe Framework: v13.14.1 (version-13)

![Expense Claim Status](https://user-images.githubusercontent.com/10789840/142406158-57d9d2d0-7e2e-442e-bbf2-ac1fa7f64ee1.gif)

**Comment by chrisdent** [comment]
> I am facing the same issue
> 
> Installed Apps ERPNext: v13.14.1 (version-13) Frappe Framework: v13.14.1 (version-13)
> 
> ![Expense Claim Status](https://user-images.githubusercontent.com/10789840/142406158-57d9d2d0-7e2e-442e-bbf2-ac1fa7f64ee1.gif)

I'm experiencing the same.
