### ISSUE TITLE
not getting work order finish item in stock entry when item is has batch no true

### ISSUE THREAD

**Issue by smehata** [frappe/erpnext#26449]
erpnext version 13.6.0

def set_batchwise_finished_goods(self, args, item):
		qty = flt(self.fg_completed_qty)
		filters = {
			"reference_name": self.pro_doc.name,
			"reference_doctype": self.pro_doc.doctype,
			"qty_to_produce": (">", 0)
		}

		fields = ["qty_to_produce as qty", "produced_qty", "name"]

		for row in frappe.get_all("Batch", filters = filters, fields = fields, order_by="creation `asc"):`
			batch_qty = flt(row.qty) - flt(row.produced_qty)     **// reason is this condition never True**
			if not batch_qty:
				continue

			if qty <=0:
				break

			fg_qty = batch_qty
			if batch_qty >= qty:
				fg_qty = qty

			qty -= batch_qty
			args["qty"] = fg_qty
			args["batch_no"] = row.name

			self.add_finisged_goods(args, item)

**Comment by carstenblt** [comment]
Yup.
Maybe to clarify:
the Stock Entry to a Work Order will not include the produced item. So basically it is just burning items.

**Comment by smehata** [comment]
> Yup.
> Maybe to clarify:
> the Stock Entry to a Work Order will not include the produced item. So basically it is just burning items.

In the previous version is working  see above code filter condition  is false
because finish work order product batch is created on submit time not the item selection time

path -- erpnext.stock.doctype.stock_entry.stock_entry.StockEntry.set_batchwise_finished_goods
check this method
