### ISSUE TITLE
Backward Compatible table names for old print formats / or run query to search and replace.

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#2645]

**Comment by JackLe1991** [comment]
Error get entries doctype in print format using  "doc.entries". How to fix error in V 5 ?

**Comment by nabinhait** [comment]
@JackLe1991 I will work for the required patch. In the meantime, "doc.items" will solve the above case. You can check all fields which are renamed on below link:
https://github.com/frappe/erpnext/blob/v5.0/erpnext/patches/v5_0/rename_table_fieldnames.py

**Comment by JackLe1991** [comment]
Thank nabinhait.
I dont' understand. 
Print Format in "Payment Receipt Voucher"
I using code.

 <div class="row">
    <div class="col-sm-9 text-left" > 
    </div>
    <div class="col-sm-3" >
      <p>Số: {{doc.name}}</p>
      <p>Nợ: {{doc.entries[0].account|truncate(10,end="")}}</p>
      {%- if frappe.db.get_value("Purchase Taxes and Charges", {"parent": doc.entries[0].against_voucher}, "account_head") -%}
          <p>Nợ: {{frappe.db.get_value("Purchase Taxes and Charges", {"parent": doc.entries[0].against_voucher}, "account_head")|truncate(10,end="")}}</p>
      {%- endif -%}
      <p>Nợ: {{frappe.db.get_value("Purchase Taxes and Charges", {"parent": doc.entries[0].against_voucher}, "account_head")}}</p>
      <p>Có: {{doc.entries[0].against_account|truncate(10,end="")}} </p>
    </div>
  </div>
  
</div>

It run normal on V.4 but It can't run on V5.
Can you help me fix it ?
Thank 
Jack Le

**Comment by nabinhait** [comment]
Just replace `doc.entries` with `doc.accounts`
