### ISSUE TITLE
Add to Cart button disappear when refresh the product page

### ISSUE THREAD

**Issue by kunthawat** [frappe/erpnext#2647]
When I login and visit the product page. The add to cart button show normally. But when I go to another and come back or refresh the page, the add to cart button suddenly disappear. I must close the browser to make the button show again.

I tested in Safari and Firefox on MAC.

This issue made the Erpnext can't use for real business. Please fix this issue ASAP.

Thanks,

This pic show the button before I refresh the page
![screen shot 2558-01-28 at 5 41 06 pm](https://cloud.githubusercontent.com/assets/10155043/5936242/fd19632a-a714-11e4-9754-a71f6e928e08.png)

The button disappear after refresh the page
![screen shot 2558-01-28 at 5 41 20 pm](https://cloud.githubusercontent.com/assets/10155043/5936249/149c2f3c-a715-11e4-8d4b-e4f380bffd3c.png)

**Comment by kunthawat** [comment]
I've investigated the problem and found that the price will reappear again. If I delete a cookies file "selling_price_list". 

Can you please help me to solve this cookie problem?

Thanks,

**Comment by anandpdoshi** [comment]
This was fixed
