### ISSUE TITLE
Asset Entry Error

### ISSUE THREAD

**Issue by imran300** [frappe/erpnext#26481]
Hello ERPNext Team,
While creating first time Asset entry, it gives error.
Screenshot Attached.
![Capture](https://user-images.githubusercontent.com/7050400/125585483-8b53ffad-6b89-49c5-9ad4-b6ed6e5a9c67.PNG)

**Comment by GangaManoj** [comment]
Fixed by https://github.com/frappe/erpnext/pull/27112

**Comment by nidhipurohit11** [comment]
https://github.com/frappe/erpnext/pull/27112
closed with this
