### ISSUE TITLE
bug: Work Order Transfer Material Against not taken from BOM

### ISSUE THREAD

**Issue by nameduser0** [frappe/erpnext#26491]
## Description of the issue
When BOMs are set to `Transfer Material Against` = `Job Card`, Work Orders still default to `Work Order`

Default Work Order fetch_from needs to be updated to `bom_no.transfer_material_against` and all methods that create Work Orders (e.g. from Production Plan) need to be fixed

workaround: customise the Work Order form and set the default to `Job Card`

## Context information (for bug reports)

**Output of `bench version`**
```
13.6
```

## Steps to reproduce the issue

1. Create Production Plan for Item with associated BOM set to: `Transfer Material Against` = `Job Card`
2. Create Work Order

### Observed result
`Transfer Material Against` = `Work Order`

### Expected result
`Transfer Material Against` = `Job Card`

**Comment by nameduser0** [comment]
@yadavyk what is your default for `transfer_material_against` on the Work Order?

**Comment by yadavyk** [comment]
@casesolved-co-uk , default for transfer_material_against on the Work Order is set to Work Order.

**Comment by nameduser0** [comment]
@yadavyk Have amended the description, this may only affect work orders from  production plans

**Comment by ankush** [comment]
I guess you meant that BOM's preferences are being set as default in the new WO, correct?

**Comment by nameduser0** [comment]
@ankush Glad you managed to reproduce. Please can you make sure all my latest production plan PRs are at least looked at if not merged? These are valuable contributions requested by your customers, and I won't continue to contribute if they are ignored. I already maintain my own repository because turnaround of bugs and PRs is practically non-existent on here. ERPNext is losing customers rapidly.

**Comment by guilmori** [comment]
We have the same issue.
Had to fix it in our fork, seeing how long it takes to handle issue here.
