### ISSUE TITLE
can't change "MOP" on invoices

### ISSUE THREAD

**Issue by michaeleino** [frappe/erpnext#26515]
## Description of the issue
Can't change Mode of Payment on return of sales invoices

## Context information (for bug reports)

**Output of `bench version`**
```
$ bench version
erpnext 13.6.0
frappe 13.6.0
```

## Steps to reproduce the issue

1. create paid sales invoice
2. create return of the sales invoice
3. change the MOP and save, it will return to it's default value.

### Observed result
MOP can't be changed on the return of sales invoice

### Expected result
changing MOP should be what changed to. 

OS version / distribution, `ERPNext` install method, etc.
Ubuntu 18.04 ERPnext 13.6.0 using bench restore sqlfile

#24917 may be related

**Comment by michaeleino** [comment]
any help or work around for this issue!?
this really blocks our 12>13 upgrade :( 
still v13 affected 
ERPNext: v13.11.1 (version-13)
Frappe Framework: v13.11.0 (version-13)

**Comment by michaeleino** [comment]
ERPNext: v13.16.1 (version-13)
Frappe Framework: v13.16.0 (version-13)

still affected... are there any plans to fix this ?

**Comment by deepeshgarg007** [comment]
@michaeleino This change was made intentionally, not a bug, closing this issue
