### ISSUE TITLE
V5 Design Suggestion - CheckBox

### ISSUE THREAD

**Issue by neilLasrado** [frappe/erpnext#2652]
![screen shot 2015-01-28 at 6 52 19 pm](https://cloud.githubusercontent.com/assets/8401344/5938222/d8324388-a71e-11e4-9ffe-c12b554933ef.png)

With reference to the above screenshot.
Document is Submitted.
Both is default and with operations are not selected.
But is Default is editable while with operations is not. Yet both look similar.

Suggestion: for a checkbox that is not selected and not editable; box can be replaced with 
a cross mark ( x ) or something similar.

**Comment by neilLasrado** [comment]
@anandpdoshi Your Views please.

**Comment by anandpdoshi** [comment]
Good suggestion
