### ISSUE TITLE
Production plan errors

### ISSUE THREAD

**Issue by platfory** [frappe/erpnext#26533]
## Description of the issue
Can't create production plan for item with BOM. All items added, stock entries created, BOM created, operations, warehouses created. 

## Context information (for bug reports)

**Output of `bench version`**
``` ERPnext  cloud version 13
```

## Steps to reproduce the issue

1. Create a new Production plan, fill in all fields required.
2. In "Material Request Planning" press "Get Raw Materials for Production" -> Error appears + message "Select warehouse for material requests"; also quantity of "Required quantity" is not not the same as in BOM for the item selected for production.
3. After pressing "Material Request Warehouse" - there is no option to select several warehouses, can select only one at a time, but item components stored in different warehouses. Sometimes, when press on warehouse,
<img width="1350" alt="Screenshot at Jul 16 17-15-11" src="https://user-images.githubusercontent.com/87531657/125966300-da23391b-f3e7-45f0-8eaf-9e311ce6b88a.png">
<img width="1338" alt="Screenshot at Jul 16 17-44-24" src="https://user-images.githubusercontent.com/87531657/125966309-a65cea59-3ed3-4aad-9b02-103a7beb68c6.png">
<img width="1325" alt="Screenshot at Jul 16 17-45-02" src="https://user-images.githubusercontent.com/87531657/125966319-4339e146-88ea-4743-ba1a-f115e7130000.png">
 select several warehouses and pressing "get items" - only items from one warehouse uploaded, and again, "Required quantity" is not the same as in BOM for the item selected. 

Please help!

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by rohitwaghchaure** [comment]
@platfory it seems that you have stock already exists, kindly enable checkbox "Ignore Existing Projected Qty" and check
