### ISSUE TITLE
Stock entry issue while doing material transfer against work order

### ISSUE THREAD

**Issue by ulfimlg** [frappe/erpnext#26535]
## Description of the issue
Error in material transfer while transferring material in the work order. Take an example of an item that needs 2 or more items to be manufacture, when you create a work order of that with a "material transfer against work order" setting and try doing stock entry of each item required to manufacture, the work order only allows us to transfer one raw material and not others. 

## Context information (for bug reports)
I was not able to dispatch an order partially in material transfer against Job cards as I will have to finish the complete quantity of work order to complete it, get my item in finish goods and dispatch it. I started using material transfer against the job card, but I saw the bug of material transfer in it. 

**Output of `bench version`**
```
ERPNext 12.21.0
```

## Steps to reproduce the issue

1. Take an item(Phone) that requires more than 2 items(Batteries, Screen, Body) for it to be manufacture. 
2. Create a work order with "Material transfer against work order"
3.  Click "Start", which will create a stock entry of type "Material transfer for Manufecturing" 
4. Delete the Screen and Body in the item table and just let the batteries be in the item table. Submit the Stock entry.
5. Go to work order again and there is no way to make a stock entry for other items.

### Observed result
Only able to transfer material for one raw material

### Expected result
Ability to create n number of material transfers unless expected raw material is transferred

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by ulfimlg** [comment]
Doesn't work in V13 too

**Comment by marination** [comment]
@ulfimlg https://github.com/frappe/erpnext/pull/27486 should solve partial material transfer against Job cards, however this os not available against Work Orders (we dont see a use case as of now).
Would that solve your issue ?

**Comment by ulfimlg** [comment]
@marination I am using the excess/multiple item transfer but it's a workaround, I still think the logic that makes the start button disappear and the logic that tracks % of material transferred should take into account all the materials not just one item. I would love to contribute but have not delved into the ERPNext codebase to get started.
