### ISSUE TITLE
Salary / Wage Caculations

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#2654]
1. Pay based on hour rate.
1. Timesheet for hours worked in a week (daily, monthly, weekly) - also track type of activity.
1. Make Payment JV Directly against Timesheet.

![timesheet](https://cloud.githubusercontent.com/assets/140076/5971445/77e57498-a86b-11e4-9b4b-217d0a341b7f.png)

**Comment by neilLasrado** [comment]
should i take this up once im done fixing capacity planning ?

**Comment by rmehta** [comment]
@neilLasrado - first fix v5 issues.

**Comment by mehulmehta** [comment]
The payment is based on number of days and not hours. So if a person works for three hours he gets paid half day wages. The overtime is per hour for most activities. But for plucking it can be based on kgs or per hour depending on the negotiations with the workers. 
The pluckers get a basic wage plus additional wage per kg if they pluck beyond a certian quantity. How do we incorporate the same? This again will vary for crops - the wage may be one rate for tea and another for coffee.

**Comment by rmehta** [comment]
- Added piece rate
- I think wages should be per hour - if you have daily wages, just convert it into no of hours
- There could be separate activity type for overtime.

**Comment by fderyckel** [comment]
Thanks rmehta.  This is a complex one as they are so many possible models.  
On a farm, we can have permanent workers (fixed salary that follows a scales for workers and for managers it is based on negotiations.)  We also have causal workers, these are paid per days they works.  We usually hired them during harvest, or other seasonal jobs (cutting grasses, plantings, etc.).  Casual workers follow a salary scale.  Finally we also have piece workers.  These are for very specific jobs (digging a trench, repairing a roof, etc.).  For these piece workers, we agree on a price for a specific task.  We pay when the whole task has been completed.

**Comment by rmehta** [comment]
on company where i'm working it's applied this formula

base_actual_work_hours = 7 for 6 day work
base_actual_work_hours = 8 for 5 day work
if actual_work_hours > base_actual_work_hours than overtime calculation started.
the overtime calculation apply this rule:
1. (actual_over_time * 2) - 0,5 on working day
2. holiday has special calculation an apply these rule:
a. first 7 hours = actual_over_time * 2
b. 8th hours = actual_over_time * 3
c. 9th hour on = actual_over_time * 4

yeah, this calculation based on regional regulation (apply in my country, maybe different on some company. but the rules still the same, 200% for fisrt hour, 300% for second hours and 400% for third hours ), may be different for another country.
but we can look at ISO or RSPO standard for the general.

but at the main concept it goes with base_work_our first (40 hours) on each week or in my country 173 hours for a month. More than that would calculated as overtime.

if somebody ask me why actual_base_work_hour recorded from 0, that's because when the company using check clock it goes like that, only the rest of base_work_hours for each day would calculated as overtime. And on some company using check clock based system to record their employee attendance.

I, my selves working on a Palm Oil Plantation on East Borneo. before working on my current position i've been working on the field and on an employee training center. so i've learn many thing about how an agriculture company administration goes.

via https://discuss.frappe.io/t/wage-piece-rate-calculations-suggestions-wanted/4564/3?u=rmehta

**Comment by cilang** [comment]
oh yeah.. forgot to mention....
the value for 1 hours depend on the base salary of the employee it self.

**Comment by mehulmehta** [comment]
I agree with the different way wages are paid for a farm. In our case the overtime is paid per hour and the rate is the basic wage rate/hour. Again it varies from Company to Company and their negotiations. Some people pay per kg etc.. In the case of the tea industry the basic wage is paid for harvesting a basic quantity say 20kgs. For quantites above that rates are calculated on a slap structure. So 20-13kgs one amount is paid, 30-40 another amount etc.. This is a little complicated. How will the system handle the same.

**Comment by tedyswaga** [comment]
How did this work out?
