### ISSUE TITLE
Update Lead Status in Customer should use ignore_permissions

### ISSUE THREAD

**Issue by Simiil** [frappe/erpnext#26556]
The code in:

https://github.com/frappe/erpnext/blob/879024831835e5c0e58977749b8cd2a2295d430b/erpnext/selling/doctype/customer/customer.py#L162

should use the ignore_permissions flag from the docs flags:

```python
lead.save(ignore_permissions=self.flags.ignore_permissions)
```

Currently, customers can not be created from a lead if the calling user has no write permissions on the lead

**Comment by Komal-Saraf0609** [comment]
Corrected in the latest version, so closing the issue.
