### ISSUE TITLE
Update Opportunity status to "Converted" when Sales Order is confirmed.

### ISSUE THREAD

**Issue by SAJOIJOM** [frappe/erpnext#2655]
push script to update a value in a previous document from a current document. To explain - We are using the hosted version of ERP Next and so only custom java scripts can be used for customization.
We have process flow from opportunity to quotation to sales order. Once sales order is submitted, we would like to update the source opportunity custom field as "order processed". this field is allowable on submit.
As per the concept, we believe it has to be done via a custom script by pushing the value from sales order.

**Comment by rmehta** [comment]
Method exists, but not called:

frappe/erpnext/blob/develop/erpnext/selling/doctype/sales_order/sales_order.py#L139
