### ISSUE TITLE
bug: Production Plan does not support material planning for multi-level BOMs with stock at each level

### ISSUE THREAD

**Issue by nameduser0** [frappe/erpnext#26563]
## Description of the issue
Currently the production plan can either deal with 2-level BOMs (non-exploded option) or BOMs that are always made directly from the base materials (exploded items imported from the BOM).

So it does not support, for example, 3-level BOMs where there may be stock of intermediate manufactured parts.

## Context information (for bug reports)

**Output of `bench version`**
```
13.6
```

## Steps to reproduce the issue

1. Create 3 levels of nested BOM, e.g. Assembly, Paint and Manufacture
2. Create qty=20 stock of both the painted and manufactured parts
3. Create production plan for qty=100 of the product. Untick Exploded items
4. Set Warehouse and 'Get Raw Materials for Production'

### Observed result
Only the painted item is brought through onto the Material Request table

### Expected result
qty=20 of the painted parts are used leaving 80 to-paint
qty=20 of manufactured parts are used leaving 60 to be manufactured

**Comment by nidhipurohit11** [comment]
Can you please post a gif of the production plan issue and a picture of BOM tree, so that it will help us to get more clarity.

**Comment by nameduser0** [comment]
No I don't have time. See the PR

**Comment by nameduser0** [comment]
@ankush Please can you reproduce this? As you can see from the PR it is a huge glaring hole

**Comment by nameduser0** [comment]
@ankush Was there any joy fixing this bug?
