### ISSUE TITLE
bug: Production Plan Sales Order and Material Request tables do not auto-complete when adding rows manually

### ISSUE THREAD

**Issue by nameduser0** [frappe/erpnext#26567]
## Description of the issue
Users expect values to auto-complete in the same way that they do when using the buttons

## Context information (for bug reports)

**Output of `bench version`**
```
13.6
```

## Steps to reproduce the issue

1. Create a Production Plan
2. Set to Sales Orders
3. Add Sales Order row

### Observed result
Only link field auto-completes

### Expected result
All fields auto-complete

**Comment by ankush** [comment]
closed by https://github.com/frappe/erpnext/pull/27352
