### ISSUE TITLE
Install ERPNext after wizard is complete

### ISSUE THREAD

**Issue by SDKAAA** [frappe/erpnext#26587]
We would like to suggest to be able to install ERPNext after wizard is complete (and keep the app up-to-date).
**Our usecase:**
We have installed frappe alone and on top of it created custom doctypes and forms and started to use it.
However, after few weeks of usage (including a few thousand records captured into several doctypes) we noticed that ERPNext could be very beneficial to our other activities and would like to install it.
Currently it is not possible to install ERPNext after the wizard has been run (we only tested it in the docker image).

It would be of great advantage if ERPNext could be installed at any time the same way as any other app even if the wizard has been run (and it should remain possible to update ERPNext the same way as updating frappe).
This feature request was initiated following [this thread](https://discuss.erpnext.com/t/installing-erpnext-after-using-frappe-for-some-time/78032/4) in the forum.

**Comment by ankush** [comment]
This check was introduced to fix this https://github.com/frappe/frappe/issues/1488
