### ISSUE TITLE
"Sales Invoice Timesheet" row disabled when adding a new timesheet

### ISSUE THREAD

**Issue by danielmorlock** [frappe/erpnext#26580]
## Description of the issue

When we try to add a new "timesheets" show in a "Sales Invoice" doc, the new row is added but disabled. No further input is possible:

![image](https://user-images.githubusercontent.com/1263320/126466744-3e8a7692-4af8-4a52-b232-eea061beec75.png)

## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 13.7.0
frappe 13.7.0
```

## Steps to reproduce the issue

1. Create a new invoice
2. Try to add a timesheet

### Observed result

Timesheet row disabled, also in HTML:
![image](https://user-images.githubusercontent.com/1263320/126467041-62092edd-cfeb-4a2c-9d78-60f5cbc463ec.png)

If we remove the "disabled" attribute by hand, we can select an activity type etc..

### Expected result

I can select an existing timesheet to be added to the sales invoice.

### Stacktrace / full error message

No logs, no errors :-(

## Additional information

We are using a modified ERPNext Docker deployment running in k8s.

**Comment by danielmorlock** [comment]
also when I click on "Edit", the dialog is just empty:
![image](https://user-images.githubusercontent.com/1263320/126467768-00551ae8-f244-49bd-91b0-8c2936e454f6.png)

**Comment by danielmorlock** [comment]
We can also reproduce the error on frappecloud.com ...

**Comment by danielmorlock** [comment]
After a deeper dive, the added "Sales Invoice Timesheet"-item seems to be read-only.

**Comment by danielmorlock** [comment]
It seems that the "read-only" property was not refactored correctly in this commit  https://github.com/frappe/erpnext/commit/59961f70ee7185b346d72e0173db1030281bfc32

See: 
![image](https://user-images.githubusercontent.com/1263320/126496242-96079b9f-a07d-4c77-8849-222f2a06d626.png)

You should add more tests :-(

**Comment by barredterra** [comment]
This is on purpose. At the top of the Sales Invoice there is a button "Fetch Timesheets" that will populate the table. Adding timesheets directly in the table is no longer possible (removing works, though).

**Comment by danielmorlock** [comment]
This enforces the user to always specify a project in the timesheets (which is currently an optional field). If users enter timesheets without specifying project, the timesheets can't be added to an invoice. I think this brings more problems than it solves or I don't get the idea :-( Furthermore if you want to edit the fetched timesheets, you see an empty window - this can't be on purpose does it?

Please let the user decide where to fetch the timesheets from: Either add more filters to fetch timesheets from or simply make the timesheet field editable again.

Don't get me wrong, I just want to go into a discussion because maybe I don't get the idea behind this change, so let me know. We appreciate your work and think ERPNext is one of the best available open source ERP solutions on the market.

**Comment by nextchamp-saqib** [comment]
@nemesis189 We can hide the section if there are no rows in the table

**Comment by barredterra** [comment]
@danielmorlock

> This enforces the user to always specify a project in the timesheets (which is currently an optional field). If users enter timesheets without specifying project, the timesheets can't be added to an invoice.

If I use the "Fetch Timesheets" button on top of the **Sales Invoice** the "Project" field is optional as well. I can fetch time logs from a date range without specifying a particular **Project**.

![Bildschirmfoto 2022-01-03 um 12 23 24](https://user-images.githubusercontent.com/14891507/147925168-5d47fcac-8be0-411c-8fd3-a5bb7876e2ae.png)

Other than that it's also possible to create a **Sales Invoice** from a single **Timesheet** that doesn't belong to any **Project**.

> Furthermore if you want to edit the fetched timesheets, you see an empty window - this can't be on purpose does it?

I can't reproduce the "empty window", but **Sales Invoice Timesheets** are _read only_ anyways. If you want to change it you'll have to _cancel_ and _amend_ the **Timesheet** itself.

> simply make the timesheet field editable again.

No so simple. The table contains time logs (DocType **Timesheet Detail** mapped to **Sales Invoice Timesheet**), not entire **Timesheets**. You cannot simply select these in a link field. Thats why the table is populated automatically.
