### ISSUE TITLE
auto scroll of POS cart-items-section makes it difficult to edit cart

### ISSUE THREAD

**Issue by zahlenhexe** [frappe/erpnext#26597]
erpNext V13.7.0: 

If there are many items in cart it is difficult to choose a certain item. 
Because the article list is set to auto scroll, it is not possible to click on individual articles, for example to remove them or to enter a discount. 

Especially in firefox the autoscroll event seems to never end. When the autoscroll ends, it is **not** possible to scroll manually. In Chrome its possible to scroll manually. 

As long as the event is running, you cannot scroll manually. 

![itemcart](https://user-images.githubusercontent.com/60541266/126613170-7b71ba50-e4e2-4793-bdd8-458086261602.gif)

**Describe the solution you'd like**
Deactivate autoscroll for container cart-items-section in POS: 

in file apps/erpnext/erpnext/selling/page/point_of_sale/pos_item_cart.js
line 644: ??

```
	scroll_to_item($item) {
		if ($item.length === 0) return;
		const scrollTop = $item.offset().top - this.$cart_items_wrapper.offset().top + this.$cart_items_wrapper.scrollTop();
//		this.$cart_items_wrapper.animate({ scrollTop });
	}
```

**Comment by ma7mod7osam** [comment]
We have the same issue here, this is not a feature request , this is a bug and need to be fixed
