### ISSUE TITLE
print all print formate at once

### ISSUE THREAD

**Issue by somfinso** [frappe/erpnext#26612]
Dear sir /madam,
I am using erpnext version.I was look for possible way to print all print formate at once.

Lest say i have i have following print formate:
sales_Invoice1.
sales_Invoice 2
sales_invoice 3
sales invoice4
I wanna group all four sales_invoice formate together as All_Invoice.
While i print i will choose print formate All_Invoice in where i can generate all four invoice at once which could save man power:
Please do sugest and help me,Your help and suggestion will highly appcrciated
Thank you

**Comment by ankush** [comment]
duplicate https://github.com/frappe/erpnext/issues/26611

**Comment by somfinso** [comment]
I am hopping for suugestion
