### ISSUE TITLE
Repost Item Valuation Issues V-13

### ISSUE THREAD

**Issue by ushashmi** [frappe/erpnext#26625]
We have identified multiple issues with Repost Item Valuation

**1. Purchase Return**
In case of purchase return the item rate field on Purchase receipt document shows the original purchase rate and whole document is valued/calculated on original purchase prices and accounting GLE is also calculated based upon the values derived from purchase receipt document. However the stock ledger entry is getting calculated at Valuation Rate (Which keeps on changing on each backdated transaction) thereby resulting in major difference in accounting GLE and stock ledger Entry.

**2. Subcontracting Purchase Receipt**
The raw materials supplied for subcontracting in a purchase receipt continue getting revalued on each back dated transaction/adjustment however the subcontracted item (Finished Good) on the same purchase receipt values at incoming rate and valuation adjustment for raw material do not impact their incoming rate. Therefore there always is a difference in Stock Ledger Entry and GL entry.

**3. Stock Entry**
We identified abnormal behavior for “Recalculate Incoming/Outgoing Rate” check field on stock ledger entry. Especially in case of multiple lines entry (more than 20+ items) where there are multiple finished goods the check box for “Recalculate Incoming/Outgoing Rate” donot get checked therefore the repost valuation impact is not getting calculated for items where this check box is not checked and eventually the stock entry becomes out of balance.

**4. Items having Batches**
We are facing major challenge in processing repost entry for a transaction (specially stock entry) which have more than 10 items having different batches. There are multiple issues faced while processing repost;
i. The repost gets stuck, system gets extremely slow and we are not able to process any stock related transaction. below error comes quiet frequently
(File “/home/erp/frappe-bench/env/lib/python3.6/site-packages/rq/timeouts.py”, line 64, in handle_death_penalty
‘({0} seconds)’.format(self._timeout))
rq.timeouts.JobTimeoutException: Task exceeded maximum timeout value (1500 seconds)

ii. Abnormal valuation rates and stock value differences get calculated for stock ledger entry which do not balance if we make simple multiplication (QTY * valuation rate = stock value difference)

iii. In some cases stock entry document and stock ledger entry tally but GL entry is having abnormal amounts

Requesting ERPNext team to look into this serious issue

**Comment by azharul-islam** [comment]
How come is there no feedback from ERPNext team on this after months? Incorrect stock valuation is causing issues in one of the most fundamental features of an accounting software

**Comment by manasan3010** [comment]
I know that this accounting bug is very complicated and very hard to trace and fix. But a proper solution should be devised for the backdated stock entries and stock reposting. Enterprises would be very concerned to have a bug like this in their accounting software.  

CC: @nabinhait

**Comment by aakvatech** [comment]
rq.timeouts.JobTimeoutException: Task exceeded maximum timeout value (1500 seconds)

Faced when running Repost Item Valuation. The values remain off. Generally caused during Repack Stock Entry.

**Comment by ankush** [comment]
> rq.timeouts.JobTimeoutException: Task exceeded maximum timeout value (1500 seconds)

> Faced when running Repost Item Valuation. The values remain off. Generally caused during Repack Stock Entry.

You can ignore this. It will continue from where it timed out in next hour.

**Comment by ankush** [comment]
> 1. Purchase Return
> In case of purchase return the item rate field on Purchase receipt document shows the original purchase rate and whole document is valued/calculated on original purchase prices and accounting GLE is also calculated based upon the values derived from purchase receipt document. However the stock ledger entry is getting calculated at Valuation Rate (Which keeps on changing on each backdated transaction) thereby resulting in major difference in accounting GLE and stock ledger Entry.

Can you share some steps to reproduce what you're describing with basic numbers? 


> 2. Subcontracting Purchase Receipt
> The raw materials supplied for subcontracting in a purchase receipt continue getting revalued on each back dated transaction/adjustment however the subcontracted item (Finished Good) on the same purchase receipt values at incoming rate and valuation adjustment for raw material do not impact their incoming rate. Therefore there always is a difference in Stock Ledger Entry and GL entry.

Some steps to reproduce this please, is the valuation rate of FG incorrect or the GLE for FG?




> 3. Stock Entry
> We identified abnormal behavior for “Recalculate Incoming/Outgoing Rate” check field on stock ledger entry. Especially in case of multiple lines entry (more than 20+ items) where there are multiple finished goods the check box for “Recalculate Incoming/Outgoing Rate” donot get checked therefore the repost valuation impact is not getting calculated for items where this check box is not checked and eventually the stock entry becomes out of balance.



AFAIK we have fixed this quite a long time ago. Can you confirm this on latest v13 release? Probably fixed by https://github.com/frappe/erpnext/pull/29517 (and similar PR before)

> 4. Items having Batches
> We are facing major challenge in processing repost entry for a transaction (specially stock entry) which have more than 10 items having different batches. There are multiple issues faced while processing repost;
i. The repost gets stuck, system gets extremely slow and we are not able to process any stock related transaction. below error comes quiet frequently
(File “/home/erp/frappe-bench/env/lib/python3.6/site-packages/rq/timeouts.py”, line 64, in handle_death_penalty
‘({0} seconds)’.format(self._timeout))
rq.timeouts.JobTimeoutException: Task exceeded maximum timeout value (1500 seconds)

Many performance fixes were made over past few months (search `perf` pull requests), we support many installations and this doesn't happen anymore. 

> ii. Abnormal valuation rates and stock value differences get calculated for stock ledger entry which do not balance if we make simple multiplication (QTY * valuation rate = stock value difference)

qty * valuation rate is not necessarily same as stock value difference if you're using FIFO, the rate will be as per FIFO incoming rates. 

> iii. In some cases stock entry document and stock ledger entry tally but GL entry is having abnormal amounts

We have identified most of the issues related to this, last one should be fixed in next release.

**Comment by s-aga-r** [comment]
Fixed in https://github.com/frappe/erpnext/pull/35138
