### ISSUE TITLE
Upgrading ERPNext v12 to v13

### ISSUE THREAD

**Issue by azeemanwar** [frappe/erpnext#26637]
[upgrade.log](https://github.com/frappe/erpnext/files/6877368/upgrade.log)
[patch.log](https://github.com/frappe/erpnext/files/6877369/patch.log)
[migrate.log](https://github.com/frappe/erpnext/files/6877370/migrate.log)
I have been trying to upgrade ERPNext v12 to v13 since it's release, however, I always end up with the errors only. I have tried to create the logs by enabling the logging level to 2, attached are the logs for the experts review. Any guidance on how to upgrade will be highly appreciated.

**Comment by azeemanwar** [comment]
Here is the error message 
![Bench Switch](https://user-images.githubusercontent.com/17431460/126976751-7ab277da-8e8d-4da2-9c55-e5fb4183da02.png)

**Comment by ankush** [comment]
Do `bench migrate --skip-failing` so it will ignore this patch, and once it's done you can rerun it without the "skip" flag to apply the patch.

**Comment by azeemanwar** [comment]
Thanks but I tried that too without luck.

Regards,
Azeem Anwar
050 476 6735

**Comment by azeemanwar** [comment]
Tried bench `bench --site sitename migrate --skip-failing` for each site and ran `bench update --patch` and end up with Invalid Method error
<img width="1151" alt="Screen Shot 2021-07-28 at 2 03 58 PM" src="https://user-images.githubusercontent.com/17431460/127304678-c2c67e63-bce0-4a68-a186-6237ea71a33c.png">

**Comment by azeemanwar** [comment]
**Following commands helped me in upgrading from ERPNext v12 to v13**
`curl -sL https://deb.nodesource.com/setup_12.x -o nodesource_setup.sh`
`sudo bash nodesource_setup.sh`
`sudo apt install nodejs`
`sudo npm install -g yarn`
**login using ERPNext User**
`sudo pip3 install -e /home/frappedirectory/.bench`
`./env/bin/pip install numpy==1.18.5 && ./env/bin/pip install pandas==0.24.2`
`sudo bench setup requirements`
`sudo bench switch-to-branch version-13 erpnext frappe –-upgrade`
`sudo bench migrate --skip-failing`
`sudo bench update --patch`
