### ISSUE TITLE
[BUG] Purchase Order - Doesnt encode URL Properly and fails to open documents

### ISSUE THREAD

**Issue by neerajvkn** [frappe/erpnext#26648]
if there are unicode characters in document name ( like PO#-00001  - '#' in this case ), when trying to open the said document, it will redirect to some broken URL, but if you enter the encoded unicode value( %23 in this case) you can open the document.

Noticed when migrated v12 to v13.

Not sure about other documents.

Installed Apps

ERPNext: v13.7.1 (version-13)
Frappe Framework: v13.7.0 (version-13)
OS - Debian 10 - updated to latest

screenshots and video attached

![erpnext_purchase_order_encoding_issue](https://user-images.githubusercontent.com/60258936/126993959-71e61ae3-d8c4-41cc-8b4e-4f2bd431201f.JPG)

https://user-images.githubusercontent.com/60258936/126995126-dc6f5754-d60a-4f73-931d-da244a210a6c.mp4

**Comment by ankush** [comment]
https://github.com/frappe/frappe/pull/13755
