### ISSUE TITLE
Company Delete Transactions - Fails to Delete Child Table Rows

### ISSUE THREAD

**Issue by dj12djdjs** [frappe/erpnext#26658]
## Description of the issue
The deletion of company transaction details is incomplete because it only deletes the most parent records of transactions.
For example SAL-ORD-001 will be deleted from `tabSales Order` however all items and taxes/charges will remain in the child tables.

**Output of `bench version`**
```
frappe 13.7.0
erpnext 13.7.1
```

**Comment by ankush** [comment]
https://github.com/frappe/erpnext/pull/26239
