### ISSUE TITLE
Creating a new item New button nor responding Erpnext V5

### ISSUE THREAD

**Issue by Steggur** [frappe/erpnext#2666]
I have a new ERPNext V5 installation.
I created a warehouse
Then I created the first item
With no item in the warehouse I was able to press the New button on the image below and create the first Item in the Warehouse
![1](https://cloud.githubusercontent.com/assets/8223600/5998329/03d2407c-aabe-11e4-8705-60eba3ba7a80.JPG)
Now with the first Item created the New button does not respond.
However if I click the item I can go to Menu / New Item to create a new Item.
I am wondering if the New button should work?

**Comment by anandpdoshi** [comment]
This has been fixed.

**Comment by Steggur** [comment]
I am not sure this has been fixed?
After I got your message I did
bench frappe --latest
bench update
bench start
Then I logged in with a browser.
This time I was browsing the Chart of Accounts.
I went to an account of credit 100.000 and pressed "View Ledger"
It showed me the the correct 100.000 entry.
Then I clicked another account of credit 24.000
When I pressed the "View Ledger" I did not get the correct account info but the previous 100.000 account info.
It is the same behavior as yesterday when I was trying to create new items. It is as if the system is not updating itself.
Or maybe I have some wrong settings.
Do you have any suggestions?
