### ISSUE TITLE
Point Of Sale-Version-13.7.0 , On click Recent order return, Item price will reload as price list rate & not Invoice Item price(Discounted sold Price)

### ISSUE THREAD

**Issue by venku31** [frappe/erpnext#26682]
In version 13.7.0
Point of sale , during return from recent order list
After clicking on return, Item price will reload from price list rate not invoice sold rate, and discount_percentage from invoice will not fetching during return

![image](https://user-images.githubusercontent.com/29224707/127265382-cfeb2acf-f612-437d-8d36-b5d8c3642dee.png)
 
![image](https://user-images.githubusercontent.com/29224707/127265523-8c9cfdea-00e3-44cf-8f7a-0cc90421aae1.png)
![image](https://user-images.githubusercontent.com/29224707/127265599-e565f3fd-6abf-4ad3-82dc-43ba3988881a.png)

Thanks & Regards
Venkatesh
Bangalore

**Comment by nextchamp-saqib** [comment]
Cannot replicate the issue now. 

![CleanShot 2022-03-21 at 11 09 28](https://user-images.githubusercontent.com/25369014/159210226-4d922c3e-e634-497b-9864-ab604540fa7b.gif)
