### ISSUE TITLE
Can't change the exchange rate of a Journal Entry Account by hand

### ISSUE THREAD

**Issue by VicentGJ** [frappe/erpnext#26696]
## Description of the issue
It's not possible to set by hand an exchange rate for Journal Entry Accounts in the Accounting Entries table of the Journal Entry doctype. When trying to do so, the system overwrites your input with the exchange rate matching the posting date of the Journal Entry. This behavior is improper because the date of the transactions described in the Journal Entry doesn't have to coincide with the posting date.
## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 13.5.2
frappe 13.5.2
```

## Steps to reproduce the issue

1. Create an account with a different currency to that of your company.
2. Create a new Journal Entry.
3. Add a row to Accounting Entries table and fill the Account field with the one previously created.
4. Click "Edit" at the end of the row.
5. In the "Currency" section try to modify the Exchange Rate field.

### Observed result
ERPnext sets the value back to the exchange rate in effect in the posting date (today).
### Expected result
ERPnext should let me set the exchange rate by hand if I need it.

## Additional information

Ubuntu 20.04 LTS, Installed Frappe and ERPnext with the manual method.

**Comment by deepeshgarg007** [comment]
@VicentGJ I have recently posted a lot of Journal Entries where I manually updated the exchange rate. Doesn't seem replicable. Please add a GIF to show steps to reproduce on the latest version and reopen if the issue still persists
