### ISSUE TITLE
Name error: name 'Base' is not defined at the time of creating Payslips

### ISSUE THREAD

**Issue by HRGanesh** [frappe/erpnext#26702]
While creating salary slip error is showing as Name error: name 'Base' is not defined.

but “base” is defined in the salary component 

![Capture](https://user-images.githubusercontent.com/78947306/127443493-3b2ea4b6-bdc0-4e88-bfca-10cc1d545b1f.PNG)

Please help to solve the issue

**Comment by kennethsequeira** [comment]
Use base instead of Base:

![image](https://user-images.githubusercontent.com/33246109/127616037-415ee384-c191-41bb-a4b6-fe53266537cd.png)

Also, next time remember to add such questions on the [forum](https://discuss.erpnext.com) and not on Github.
