### ISSUE TITLE
Chart of Accounts Importer: varchar(140) for fields in Accounts is too short

### ISSUE THREAD

**Issue by nissekalle0** [frappe/erpnext#26733]
## Description of the issue
The problem has been discussed before but I have not seen an understandable solution to it.
Nordic CoA's have a few longer strings than 140 characters. To be fully compliant with the CoA standard we would like to increase the size to 250 characters.

## Context information (for bug reports)

**Output of `bench version`**
```
Value too big

Account 1340 - Långfristiga fordringar hos intresseföretag, gemensamt styrda företag och övriga företag som det finns ett ägarintresse i - BAS 2020 - CL - CL: 'Account Name' (1340 - Långfristiga fordringar hos intresseföretag, gemensamt styrda företag och övriga företag som det finns ett ägarintresse i - BAS 2020 - CL) will get truncated, as max characters allowed is 140
```

## Steps to reproduce the issue

1. Go to CoA Importer
2. Upload a CoA
3. Import it and you get the above error message

### Observed result
Due to database definition of varchar(140) the length of the fields is giving an error message.
### Expected result
Accept strings 250 characters long
### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.
Ubuntu with latest 13.x version of ERPNext

**Comment by ankush** [comment]
This is not just a change in Account doctype, it will be required everywhere accounts links are present. 

> To be fully compliant with the CoA standard we would like to increase the size to 250 characters.

Can you cite references?  Is there any alternative solution?

**Comment by nissekalle0** [comment]
In Sweden we use a standard of CoA called "BAS yyyy" (yyyy = year) and the longest account name string is taking about 200 characters utf-8.
A solution is to start abbreviating the strings, which is a no or bad solution because then it doesn't comply fully with the standard and like strings might be mixed.
I don't see any other solution than extending the size in every linked field.

**Comment by deepeshgarg007** [comment]
@nissekalle0 Maybe you can add a custom field in the account doctype and maintain the 200 character name there, then wherever you need to display this name you can fetch it based on the account name. In case you have any comments or suggestions please reopen the issue again, closing this for now

**Comment by deepeshgarg007** [comment]
One more hack is to translate the Abbreviated Name with the full name
