### ISSUE TITLE
Ability to edit Amount on Submitted Additional Salary

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#26740]
- Scenario, say you had a recurring additional salary for a period of three months.
- Then after the first month, you're required to update the amount, which should take effect for the coming two months, without affecting the first month salary slip.
- Cancelling an Additional Salary, cancels all salary slips attached to it.
- If the amount becomes editable on Submit, then one can update the amount appropriately, even to zero(which stops the additional salary all together)
- An Additional Salary provides a flexibility to define recurring Earnings/Deductions that are different for different employees, without having to create multiple salary structures for each employee.

**Comment by dj12djdjs** [comment]
This would also help us. We use Timesheet based salary structure. This means we need to duplicate each salary structure for each hourly rate. If we want to add a new Earnings or Deductions component we should cancel all salary structure assignments, all salary structures. Then re create all the salary structures with the new component. Then reassign all the employees to the correct salary structure again. This is very time consuming.

**Comment by muchai** [comment]
Can this get some attention please.

Also, a bit curios why cancelling an Additional Salary, cancels all salary slips attached to it.

**Comment by muchai** [comment]
Please keep it open.

**Comment by muchai** [comment]
How does one re-open or activate this?
I see only the one who closed can re-open. Please re-open it.
