### ISSUE TITLE
Changes to Company abbreviation don't propagate properly to Cost Centers, Tax templates, Warehouses etc.

### ISSUE THREAD

**Issue by blewsky** [frappe/erpnext#26746]
## Description of the issue
Changing the abbreviation for a Company, changes the abbreviations appended in the Chart of Accounts but not to Cost Centers. 

## Steps to reproduce the issue
1. Rename company abbreviation using `Abbr.` Field in Company Doctype. This is the pop-up:
![image](https://user-images.githubusercontent.com/87971956/127698327-5521149c-8289-4a88-82b2-5beebe57ab10.png)
2. Save changes, wait until changes affect the entries in the database and reload company page.
2. (Check Chart of Accounts. The abbreviations added to each Account name are changed.)
3. Go-to Cost Centers. The Cost Centers still have the old abbreviations.

### Observed result
- Abbreviations in the name of `Cost Center` are not changed according to the change in `Company` doctype.
- To make things worse: It doesn't work to rename the Cost Centers manually to match the new abbreviations. 

### Expected result
Changes to the abbreviation in `Company` doctype should directly propagate correctly and affect the abbreviation used in the name of all `Cost Center` entries.

## Additional information
ERPNext: v13.7.0 (HEAD)
Frappe Framework: v13.7.0 (HEAD)

**Comment by blewsky** [comment]
It seems this problem is bigger than previously thought. The company abbreviations are also not correctly propagated to the Tax Templates and Warehouses. The weird thing is, that some Warehouses etc. are renamed correctly and others not. It seems this "feature" (= renaming a company abbreviation) should be overhauled and checked for bugs. A company can potentially have many Accounts, Warehouses, Tax templates etc. that can be affected by the renaming of the company abbreviation.  Not having proper names after a change in the abbreviation, can create confusion or other bugs. Therefore, I think this is a serious issue that should be fixed.

Personally, I think it is not a good practice to add the company abbreviation automatically to all these dependent fields for two reasons:
1. Propagating changes is very error-prone (as we can see here).
2. People might want a different naming procedure
(e.g. I dislike the space characters between the doctype name and the company abbreviation others might want to hide the company abbreviation because they don't need it.)

**Comment by blewsky** [comment]
Related discussion in the forum:
https://discuss.erpnext.com/t/renaming-company-abbreviation-is-broken-how-to-fix-cost-center-names/78628

**Comment by blewsky** [comment]
The problem probably stems from the functions [`enqueue_replace_abbr()'  ](https://github.com/frappe/erpnext/blob/11475487fb352e5aff2348341d2bd4c6c4833d17/erpnext/setup/doctype/company/company.py#L396) or ['replace_abbr()'](https://github.com/frappe/erpnext/blob/11475487fb352e5aff2348341d2bd4c6c4833d17/erpnext/setup/doctype/company/company.py#L402) in the Company doctype. It seems that two recent changes to the code in V13.7 (https://github.com/frappe/erpnext/pull/26462) and V13.6 (https://github.com/frappe/erpnext/pull/26203) are responsible for this behavior.

**Comment by blewsky** [comment]
@nextchamp-saqib : Can you comment on this from the perspective of the two recent PRs?

**Comment by blewsky** [comment]
Any updates on this? Would be great to get feedback from @nextchamp-saqib ?
Otherwise, it could make sense to revert the changes made in https://github.com/frappe/erpnext/pull/26462 and https://github.com/frappe/erpnext/pull/26203 as it seems that they weren't thoroughly tested enough to be rolled out.

**Comment by nextchamp-saqib** [comment]
@blewsky Sorry for the late response. 
There seem to be various issues with this feature and I will try to refactor it to address the problems. 

However, I can confirm that the problem didn't arise after the 2 recent PRs.

**Comment by blewsky** [comment]
Hi @nextchamp-saqib, any updates on this issue? Could you track where this bug originates from?

**Comment by ankush** [comment]
Closing this in line with linked PR ^

This feature is very dangerous on large datasets and doesn't have any real blocking use cases.

**Comment by blewsky** [comment]
The problem still persists even with the @nextchamp-saqib 's PR. 
The abbreviation is added automatically after the cost center. ERPnext still adds the old abbreviation it must have still stored somewhere.
