### ISSUE TITLE
CoA Importer: Not understandable error messages by import

### ISSUE THREAD

**Issue by nissekalle0** [frappe/erpnext#26749]
## Description of the issue
Attach a CoA file works fine. Preview shows all accounts and the whole tree as it should be but still two error message I don't understand.

## Context information (for bug reports)

**Output of `bench version`**
```
TypeError: install_country_fixtures() missing 1 required positional argument: 'country'
Set default inventory account for perpetual inventory

```

## Steps to reproduce the issue

1. Create a CoA.csv file
2. Attach it
3. Import it and the error messages appear

### Observed result
errors as above and no import
### Expected result
no errors and normal import
### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.
erpnext 13.x and your Ubuntu VM

**Comment by deepeshgarg007** [comment]
@nissekalle0 Unable to reproduce this error. Please share the file that you are trying to attach and reopen the issue if the error still persists.
