### ISSUE TITLE
Field supplier_type not found

### ISSUE THREAD

**Issue by Steggur** [frappe/erpnext#2674]
I have translated Distributor as Dreifingaraðili in Icelandic.
When I create a new supplier I choose Supplier type as Dreifingaraðili
![1](https://cloud.githubusercontent.com/assets/8223600/6022774/3b745f66-abb7-11e4-9543-c1068f0e0046.JPG)
Then when I go and create a PO I get the error: Field supplier_type not found
I noticed that when I switch between English and Icelandic Dreifingaraðili does not change back to Distributor as it should when I select English it remains Dreifingaraðili.
I am wondering what is causing this?

**Comment by Steggur** [comment]
I have also tried to create a new Supplier Type and use it but I get the same error when creating a PO.
I have also tried other system types and they do not work either.

**Comment by neilLasrado** [comment]
@Steggur this is a party model related issue. https://github.com/frappe/erpnext/issues/2677
I saw your thread after i created this issue.

**Comment by Steggur** [comment]
So now this is confirmed from two sources.
