### ISSUE TITLE
CoA Importer: Does not accept same Account Name of two accounts with unique ID field created

### ISSUE THREAD

**Issue by nissekalle0** [frappe/erpnext#26744]
## Description of the issue
CoA Importer does not accept the following:
- two Accounts records with same Account Name but different Account Number create a unique ID field
- -> error
## Context information (for bug reports)

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1. Create two fields with the same Account Name but different Account Number fields
2. Import the file
3.

### Observed result
Error
### Expected result
The ID field is created from both Account Name and Account Number so it is unique. Therefore there shouldn't be any error.
### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by deepeshgarg007** [comment]
@nissekalle0 This has nothing to do with the COA importer. This is a design decision that has been taken at the account master level. Usually, account numbers are used to uniquely identify accounts and no two account numbers for a company can be the same hence the error. Doesn't look like a bug to me.
