### ISSUE TITLE
When an account class is a group of f.i. Equity and Liability then it is not possible to leave Root Type empty

### ISSUE THREAD

**Issue by nissekalle0** [frappe/erpnext#26751]
## Description of the issue
When a CoA has an account class which is a combination of Equity and Liability it is not possible to leave field Root Type empty because all account records need to have a Root Type.
## Context information (for bug reports)

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1.
2.
3.

### Observed result
an error missing Root Type if empty
### Expected result
Create a new Root Type called for example View
### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by deepeshgarg007** [comment]
@nissekalle0 This is by design, you cannot have a group root type, not a bug, closing this issue
