### ISSUE TITLE
loan repayment doesn't show in accounting ledger

### ISSUE THREAD

**Issue by citybirdman** [frappe/erpnext#26754]
## Description of the issue
when i make a loan and repay it from salary the loan repayment doesnt show in accounting ledger and doesnt make an effect

I made loan with term loan type and checked on repay from salary checkbox ... when I make loan repayment and submit it .. it doesn't show in general ledger ... figured out that this repayment doesn't have any gl enties
## Context information (for bug reports)

**Output of `bench version`**
erpnext 13.7.1
frappe 13.7.0
bench core 5.4.0

**Comment by chrisdent** [comment]
#28733
