### ISSUE TITLE
Unable to use Kanban view in Lead List

### ISSUE THREAD

**Issue by aditsanghvi** [frappe/erpnext#26758]
Kanban view in lead list is not responding at all. this issue is been faced after an update 

Software Version
ERPNext: v13.7.1 (version-13)
Frappe Framework: v13.7.0 (version-13)

software is installed in Amazon Web Services

## Steps to reproduce the issue

1. Lead List (list view)
2. Try opening Kanban View
3. Page Still shows List View

**Comment by ankush** [comment]
https://github.com/frappe/frappe/pull/13788
