### ISSUE TITLE
Email Digest

### ISSUE THREAD

**Issue by mehulmehta** [frappe/erpnext#2676]
Currently we can create email digest only for users registered with the erp. can we have a system wherein we can send the email digest as an email to others in the organisation who are not users in the erp. this will help just for reporting purposes especially to top management who are not daily users of the erp.

**Comment by anandpdoshi** [comment]
Why not add them as users?

**Comment by mehulmehta** [comment]
Because then we need to make sure about permissions, what they can access
etc.. Or sometime when a concerned person is not in office for few days and
the reports need to be sent to an interim person in charge.

Regards,
Mehul B. Mehta

**Comment by anandpdoshi** [comment]
You can create a user without any roles. So they won't be able to access anything other than notes calendar etc.

**Comment by mehulmehta** [comment]
ok thats cool

Regards,
Mehul B. Mehta
