### ISSUE TITLE
term loans that is repayed from salary doesn't show in general ledger

### ISSUE THREAD

**Issue by citybirdman** [frappe/erpnext#26777]
## Context information (for bug reports)

**Output of `bench version`**
```
5.4.0
```

## Steps to reproduce the issue
1. make term loan that is repayed from employee salary
2. make loan repayment for this employee 
3. submit this loan now click on view > ledger

### Observed result
 nothing is showing or any data for accounts with this loan repayment number ... also this loan repayment doesn't show any where neither in filter with accounts nor filter with employee
### Expected result
1- expected to see first line that is from the "deptors" and from the employee
2- another line expected to see the another transaction for money to the other account like: "cash" account
![Screenshot 2021-08-02 at 11-05-12 ACC-LOAN-2021-00182](https://user-images.githubusercontent.com/66416615/127836061-2b5caf70-a375-46e8-94e2-de20a6480f20.png)
![Screenshot 2021-08-02 at 11-06-26 LM-REP-0095](https://user-images.githubusercontent.com/66416615/127836059-b10c1014-b4b6-4a97-9fc4-35f59221e8a4.png)
![Screenshot 2021-08-02 at 11-06-50 General Ledger](https://user-images.githubusercontent.com/66416615/127836055-563876ac-750d-4442-b868-350eadd9fa0e.png)

## Additional information

OS version: ubuntu / distribution: 18.04, `ERPNext` install method: manual, frappe framework version:3.7.0, ERPNext version:3.7.1 .

**Comment by 9050nasser** [comment]
im facing same issue

**Comment by chrisdent** [comment]
#28733
