### ISSUE TITLE
Saving a time sheet reverts all the times entered to the current time and date. 

### ISSUE THREAD

**Issue by amyburness** [frappe/erpnext#26770]
## Description of the issue
In time sheets when save button is clicked the system changes all the times set to the current date and time. if the page is reloaded then it is correct but if save is clicked again it over rights the times with the current time. 
## Context information (for bug reports)
Creating time sheets takes twice as long. 

https://user-images.githubusercontent.com/77841514/127815459-88817b67-0cb7-4efb-b3b6-f29e881f6620.mp4

Uploading 2021-08-02 08-39-53.mp4…

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1.open time sheet 
2.add a column
3.add all nessisary information like times, description and project
4. click save
5. observe time and date automatically changes

### Observed result
Observe time and date automatically changes current time and date
### Expected result
for the time sheet to have the time and date set int the form. 
### Stacktrace / full error message
there is no error message 
```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by deepeshgarg007** [comment]
Not replicable right now, we use to use timesheets heavily and if such an issue existed we would have come to know by now. 
Also in the GIF, I can see even after clicking on save the form remains dirty, this looks like a custom script issue.
