### ISSUE TITLE
Filter for Blanket Order field

### ISSUE THREAD

**Issue by JenishaJayaraj** [frappe/erpnext#26772]
Description:

Need filter in Blanket order field that is present in documents like Sales Order and Purchase Order. Since we are selecting Customer and Supplier in Blanket Order itself, it would be efficient if there is a filter for Customer in Sales Order and Supplier in Purchase Order.  So that even if we create a Sales Order or Purchase Order separately without Blanket order, we can select correctly with a filter.

We are using below version:

ERPNext: v13.7.0 (version-13)

Frappe Framework: v13.7.0 (version-13)

Thanks!

**Comment by frederictobien** [comment]
Hi 
I would also be highly interested in a real functional blanked orders. For both selling and buying.
Same like sales order and purchase order.
