### ISSUE TITLE
Address and Tax template in Blanket Order

### ISSUE THREAD

**Issue by JenishaJayaraj** [frappe/erpnext#26771]
Description :

Need address and tax templates in Blanket order. It would be better if we have address and taxes in Blanket Order like Sales Order etc. Since we are creating Sales Order and Purchase Order from Blanket Order, it will be efficient if address and tax is available in Blanket order itself, so that we need not select again.

We are using below version:

ERPNext: v13.7.0 (version-13)

Frappe Framework: v13.7.0 (version-13)

Thanks!

**Comment by frederictobien** [comment]
Hi
I would also be highly interested in a real functional blanked orders. For both selling and buying.
Same like sales order and purchase order.
