### ISSUE TITLE
After Update where i can put my print format code or client script code?? 

### ISSUE THREAD

**Issue by vaibhav007-droid** [frappe/erpnext#26788]
**### The boxes are not visible after update(where i can put my code)??** 

1)
![Screenshot from 2021-08-03 13-54-30](https://user-images.githubusercontent.com/62324376/127983286-127aeb53-1570-4b70-b19e-564af62c1fd0.png)

2)
![Screenshot from 2021-08-03 13-54-10](https://user-images.githubusercontent.com/62324376/127983308-abf22e72-369f-446a-a918-741b62e3ec9f.png)

How this will resolve??

**Comment by ankush** [comment]
Can't reproduce this issue. 

Open the browser console and see if there are any errors. Most likely your assets haven't been generated. Try `bench build`.

**Comment by vaibhav007-droid** [comment]
Hello thanks for the reply @ankush,

I tried this multiple times but it doesn't make any sense just the process will finished as normally and nothing can be happened.

**Comment by ankush** [comment]
Check browse console for error. That's all I can say based on limited info. Can't reproduce this on both stable/dev branch.
