### ISSUE TITLE
Product bundle items are not fetching from Sales Order ,while creating Pick List.

### ISSUE THREAD

**Issue by Guna1011** [frappe/erpnext#26787]
![Screenshot 2021-08-03 at 12 57 53 PM](https://user-images.githubusercontent.com/75108603/127976490-722e55c9-54f0-4232-b860-74f902ff9bb8.png)

**Feature Requested**

- Product bundle's child item need to be fetch in  pick list instead of parent.

**Solution**

- Product bundle items are not fetching in pick list from sales order .It showing insufficient stock.Because pick list take only **parent item, which is non stock item**. 
- So while creating pick list  from sales order with bundle items consider product bundle's child item and it should be added in pick list item table.

**Comment by Nihantra-Patel** [comment]
It's solved in the latest version, so check it.


https://github.com/frappe/erpnext/assets/141945075/0c2dce22-d5d4-474b-855b-6add196023b3
