### ISSUE TITLE
UOM Conversion Factor Mismatch in Purchase Invoice

### ISSUE THREAD

**Issue by azeemanwar** [frappe/erpnext#26789]
## Description of the issue

We started using ERPNext from v12, recently we have identified that sometimes the system populates wrong conversion factor in the purchase invoices which ultimately leads to wrong stocks. This issue hasn't been observed in the Sales Invoices. We ran a query to check the mismatches using following SQL
`select c.company, c.posting_date, c.name, a.idx, a.item_code, a.uom, a.base_rate, a.conversion_factor invoice_conversion_factor, b.conversion_factor item_conversion_factor
from `tabPurchase Invoice Item` a join `tabUOM Conversion Detail` b on a.item_code = b.parent and a.uom = b.uom
join `tabPurchase Invoice` c on a.parent = c.name
where a.conversion_factor <> b.conversion_factor
and c.docstatus = 1
order by c.company, c.posting_date, c.name, c.idx;`

## Context information (for bug reports)
Happening only in Purchase Invoices, the issue is rare, cause of the issue hasn't been identified so far and can't say on how to reproduce the issue

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue
Can't say how the issue is happening
1.
2.
3.

### Observed result
Sometimes, the Conversion Factor gets wrong value in the Purchase Invoice
[Conversion Factor Mismatch.xlsx](https://github.com/frappe/erpnext/files/6922496/Conversion.Factor.Mismatch.xlsx)
### Expected result
Should get the exact conversion factor from the Item Units of Measurement

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.
Ubuntu 18 TLS, ERPNext v12.23.0, Frappe v12.20.0

**Comment by deepeshgarg007** [comment]
@azeemanwar Please add steps to replicate the issue and then reopen
