### ISSUE TITLE
User Type: Employee Self Service Unable to add row under Allowed Modules

### ISSUE THREAD

**Issue by tjomtek** [frappe/erpnext#26790]
## Description of the issue
Unable to "add row" as per erpnext documentation.
![AddRow](https://user-images.githubusercontent.com/77873407/127985306-1cc6398a-6720-4db6-a057-522af9c122d7.png)
 for employee self service
## Context information (for bug reports)
Under Allowed Modules the 'add row' option is not showing.
I have developer_mode set to 1
![MySitePage](https://user-images.githubusercontent.com/77873407/127985760-7a2c9727-dcfd-44ea-a260-32ba879dc7c1.png)

**Output of `bench version`**
```ERPNext: v13.7.1 (version-13)

Frappe Framework: v13.7.0 (version-13)
(paste here)
```

## Steps to reproduce the issue

1.Navigate to users
2.click on user type
3.click on employee self service, scroll down to Allowed Modules

### Observed result
unable to add row under allowed modules
### Expected result
that i am ablw to add row to insert a module for the self employee service
### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by ankush** [comment]
This is by design. ESS is supposed to be a limited user type.
