### ISSUE TITLE
Error while installing erpnext on a site using postgresql

### ISSUE THREAD

**Issue by ishanloya** [frappe/erpnext#26795]
When installing erpnext on a fresh instance of a site using postgresql, I have run into the following issue:

```
Installing erpnext...
Updating DocTypes for erpnext       : [=====================                   ] 53%An error occurred while installing erpnext:
column "route(500)" does not exist
```

**Comment by ishanloya** [comment]
#18028 seems related

**Comment by ankush** [comment]
Postgres is not supported for ERPNext yet. Ref: https://github.com/frappe/erpnext/issues/18028#issuecomment-761971845

https://github.com/frappe/frappe/pull/13705 this will speed up Postgres support.
