### ISSUE TITLE
[V5]Attachments not uploaded successfully

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#2680]
1. Attached excel file in the Sales Order. 
1. Check and found that File record is also created. 
1. When click on File location, it shows "Not Found" error.

Replicating same issue when try attaching image logo in the Letter Head's text editor.

**Comment by pdvyas** [comment]
Seems like a deployment issue, can you try again?

**Comment by umairsy** [comment]
Tried replicating, and found another issue. original issue has been fixed.

attached file in the record via drag and drop. File was uploaded correctly, but they were not listed in the form I attached them. After I reloaded page, they were listed under attachments as expected.
