### ISSUE TITLE
[V5] Transaction Heading not intuitive in History and when fetching data from one form to another

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#2681]
As per current design, we have party name (customer/supplier) updating as transaction title, in place of transaction id. This is creating following usability issues while creating entries.

![screen shot 2015-02-04 at 2 07 17 pm](https://cloud.githubusercontent.com/assets/910238/6037705/79b9c19c-ac7c-11e4-8023-9772aa763c22.png)

1. When I convert Quotation into Sales Order, I cannot identify if fetching has been completed, and I am on Sales Order now, because transaction title remains same.

2. Also when I check browser history for the previous transaction, it only list Customer Name, instead it should list Transaction Id in the history. Since I have transactions made for the same party, and not transaction id, it becomes difficult to locate specific transaction.

Suggestion: Perhaps for the unsaved transaction, we can have (say) unsaved Sales Order 1 as its title. This will also help me identify that my data has been migrated to new transaction. Also will make locating atleast unsaved transctions in the Browser History.

**Comment by rmehta** [comment]
fixed.
