### ISSUE TITLE
item_code not set when creating item using document naming rules

### ISSUE THREAD

**Issue by roxn** [frappe/erpnext#26813]
## Description of the issue
When using document naming rules to add prefix with 5 digit number for item name, the item_code field is not set or remains empty when creating new items. name and item_name fields are set, but not item_code.
The issue with that is, when creating item templates, the item_code for created variants will start with None-Attr1-Attr2 instead of name-attr1-attr2 and this will hit item_code field constraints when different items have same attribtues. This is not visible as such from the normal interface until it hits the constraint and items with same attributes can no longer be added.

## Context information (for bug reports)

**Output of `bench version`**
erpnext 13.8.0
frappe 13.8.0

## Steps to reproduce the issue

1. Add document naming rule to add prefix (TE-) plus 5 digits when using certain item group. (item_group=test)
2. create new item test1 with item group test.
3. Create any item attribute as test.
4. Activate test item variants with test attribute.
5. Create one variant item.

### Observed result

Check database item table how the test items were created. The variant item's item_code field shows None-Attr1 and template item item_code is empty.

### Expected result

item_code for template item needs to be set

### Stacktrace / full error message

hitting item_code unique contraint

## Additional information

Vanilla Docker Installation

**Comment by deepeshgarg007** [comment]
@roxn This isn't replicable anymore. Item Code is a mandatory field, so saving the item without the item code is not possible. Please share a GIF of how you generated the item and reopen the issue
