### ISSUE TITLE
Production Plan Status Showing "in Progress" even all the work orders are completed

### ISSUE THREAD

**Issue by casakthiveln** [frappe/erpnext#26822]
## Description of the issue
Production Plan Status Showing "in Progress" even all the work orders are completed

## Context information (for bug reports)

**Output of `bench version`**
```
V 13.8.0
```

## Steps to reproduce the issue

1.
2.
3.

### Observed result
![ezgif com-gif-maker](https://user-images.githubusercontent.com/63579207/128329768-47854f7c-db72-4024-8dbf-af9fea4ba912.gif)

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by dvdl16** [comment]
[This line](https://github.com/frappe/erpnext/blob/version-13/erpnext/manufacturing/doctype/production_plan/production_plan.py#L300) should be changed:

```python
		if self.total_produced_qty > 0:
			self.status = "In Process"
			#if self.total_produced_qty == self.total_planned_qty:
			if self.total_produced_qty >= self.total_planned_qty:
				self.status = "Completed"
```

**Comment by marination** [comment]
@dvdl16 can you raise a PR for this?

**Comment by casakthiveln** [comment]
Thank you all.....
