### ISSUE TITLE
[V5] Sales Order - Error when select Customer

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#2683]
Error message:

![screen shot 2015-02-04 at 2 59 31 pm](https://cloud.githubusercontent.com/assets/910238/6037927/97ea5e22-ac7e-11e4-85b9-6863374ec785.png)

Checked Customer's contact. Contact ID has arabic characters in it. Could that be the issue?

**Comment by neilLasrado** [comment]
duplicate https://github.com/frappe/erpnext/issues/2677 i believe

**Comment by umairsy** [comment]
I guess not. Lets keep it separate for now.

On Wed, Feb 4, 2015 at 3:18 PM, Neil Trini Lasrado <notifications@github.com
> wrote:

> duplicate #2677 <https://github.com/frappe/erpnext/issues/2677> i believe
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/frappe/erpnext/issues/2683#issuecomment-72826661>.
>



-- 
Thanks and Regards,
Umair Sayyed
www.erpnext.com

**Comment by rmehta** [comment]
fixed
