### ISSUE TITLE
[V5] Next Step options in transaction (listed under Menu) not updated

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#2684]
Steps1:

1. Saved and submitted Sales Order.
2. Created Delivery Note against Sales Order.
3. Came back to Sales Order. 

In the Menu list, it doesn't list option to create more Delivery Note and Sales Invoice option. It only shows options like new, duplicate, Links etc.

**Comment by umairsy** [comment]
replicated issue with next steps in the Lead as well.

**Comment by umairsy** [comment]
This issue is still occurring. Updating of next steps under Menu is not consistent. 

Please Open this issue again.

**Comment by umairsy** [comment]
Even after the recent update on next step button bar, options are not loaded properly when I switch from the transaction, and come back on it.

Also breadcrumb is not updated correctly. Please check attached screenshot for the same.

![screen shot 2015-02-23 at 11 10 37 am](https://cloud.githubusercontent.com/assets/910238/6323253/f66d67b4-bb4c-11e4-8efd-37895b71d8c4.png)

**Comment by anandpdoshi** [comment]
Is this still happening?
