### ISSUE TITLE
[V5] Location of dialog box to select items

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#2685]
Its a suggestion, and not a bug.

1. Dialog box should always open in the middle of the form. Check below link for the context :)

http://imgur.com/yTxIexi

2. In the dialog box, we should have "Done" option at the bottom, near "Insert Below" as well. Because after entering all the item details, use is mostly at the end of the item form/dialog box.

**Comment by rmehta** [comment]
you can click anywhere outside for done....
middle may not work because you will need scrolling
