### ISSUE TITLE
Unable to change the status of the task to Completed 

### ISSUE THREAD

**Issue by aditsanghvi** [frappe/erpnext#26862]
## Description of the issue
When I change the status of the task to completed it shows an error

**Output of `bench version`**
```
ERPNext version: 13.8.0

```

### Observed result

![image](https://user-images.githubusercontent.com/61310502/128696818-4dd34ec3-2e89-4299-aec1-f46ee0828956.png)

### Stacktrace / full error message

![Untitled](https://user-images.githubusercontent.com/61310502/128696723-5a4b29f9-bf2e-4a6f-9bef-45399d8fa2fe.png)

**Comment by ankush** [comment]
We don't use "under process" anywhere in ERPNext, this is probably your customization. 

Reopen with steps to reproduce, if necessary.

**Comment by aditsanghvi** [comment]
> We don't use "under process" anywhere in ERPNext, this is probably your customization.
> 
> Reopen with steps to reproduce, if necessary.

I have not made any custom changes
![image](https://user-images.githubusercontent.com/61310502/128700616-70aadd5e-d690-4fd8-8a3e-b96c85e6156f.png)

this is my status list
and its default

and when I put status as Completed it shows this error

![Untitled](https://user-images.githubusercontent.com/61310502/128700683-15d1b410-8a15-4ffa-b943-0126075e292f.png)
