### ISSUE TITLE
add summary row for the grid table show the columns summation and make this optional  for every column

### ISSUE THREAD

**Issue by HoFaks** [frappe/erpnext#26869]
add summary and total row for the grid table show the columns summation and make this optional  for every column
![datatable-column-total-sum-output](https://user-images.githubusercontent.com/33111711/128766304-0a5fda62-1dda-4720-84f1-78d7f3b30ca2.jpg)

**Comment by ankush** [comment]
Don't get what's required, this is already present in reports?

**Comment by HoFaks** [comment]
yest its alredy present in reports for datatable
but wen need it for datagrid in form (Document)

many thanks

**Comment by sharmanakul** [comment]
many forms on the purchase and sales side have fields that summarize total quantity and total amount.

Are there any specific forms on which you want such types of summary?
