### ISSUE TITLE
Unable to change the status of the task to Completed

### ISSUE THREAD

**Issue by aditsanghvi** [frappe/erpnext#26864]
## Description of the issue
When I change the status of the task to completed it shows an error and I have not customized anything.
Here is my all my status
![image](https://user-images.githubusercontent.com/61310502/128702444-395fc3a0-32d5-487e-9972-bd8f3a685e14.png)

**Output of `bench version`**
```
erpnext 13.8.0
frappe 13.8.1
```

### Observed result
![Untitled](https://user-images.githubusercontent.com/61310502/128702323-eb1a602b-38bf-4e21-992c-dedb07bb33c5.png)

**Comment by ankush** [comment]
The validation is coming from the "select" field validation, so somewhere you must've defined "Under Process" as select type option and that's where this is coming from. 

Search your custom doctypes or property setters to find where it's defined (don't edit any of them!)

![Screenshot 2021-08-09 at 5 39 06 PM](https://user-images.githubusercontent.com/9079960/128703846-815a11ea-129a-4b03-ad7d-50c95e7003bc.png)



---
Highly unlikely to be a bug. "Under Process" <-- this is not used anywhere in ERPNext or Frappe.
 
![Screenshot 2021-08-09 at 5 34 32 PM](https://user-images.githubusercontent.com/9079960/128703332-b9d92830-c26e-4589-8fe9-550ab6cfc529.png)

**Comment by aditsanghvi** [comment]
> ion is coming from the "select" field validation, so somewhere you must've defined "Under Process" as select ty

Solved thanks for support
