### ISSUE TITLE
Basic Rate (as per Stock UOM) on Material Transfer for Manufacture is different from Rate on Work Order and BOM - v13.8.0 (version-13)

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#26874]
For item. 5-20mm Ballast
Rate Of Materials Based On, is set to use last Purchase Rate
On BOM and Work Order rate is 690.00, then for Stock Entry ends up picking 630.09.

**On BOM**
![image](https://user-images.githubusercontent.com/1822868/128826942-81bfe4a4-5fdb-4e38-b7db-db5978ff7c5d.png)

**On Work Order**
![image](https://user-images.githubusercontent.com/1822868/128827102-dfdbcfd2-c047-4243-996b-f32417d399e2.png)

Stock **ledger**
![image](https://user-images.githubusercontent.com/1822868/128827482-6205dad3-2e4d-42bc-80dd-3212fb9a2f28.png)

Stock **Entry**
![image](https://user-images.githubusercontent.com/1822868/128827675-a9942acf-4b33-46d7-a0c3-ca7a4b7ada96.png)

**Comment by ankush** [comment]
BOM rate is for costing defined at time of creating the BOM. 

Stock Entry uses your stock valuation rate depending on FIFO/Moving average valuation method that you're using.

**Comment by muchai** [comment]
That's in order.

Just don't understand, the work order was for 8th July.
Stock entry created on 5th Aug

Of the valuation rates since July 7th, why pick the one on 10th of July, or does it pick the valuation rate of the target warehouse?

![image](https://user-images.githubusercontent.com/1822868/128857897-b59b3fce-7afd-4768-97f3-2c231f7fd951.png)

**Comment by ankush** [comment]
It picks the rate from the specified source warehouse.

**Comment by muchai** [comment]
The source warehouse on stock entry
![image](https://user-images.githubusercontent.com/1822868/128860871-1a682028-0254-42c8-9c32-2dea3a3ee139.png)
Last stock ledgers for the item in the warehouse.
![image](https://user-images.githubusercontent.com/1822868/128860963-9735b912-9812-4475-b4ae-07697f86c333.png)

Also, one cannot edit the Basic Rate (as per Stock UOM) on the stock entry, it's editable, but it always goes back to the old figure.

Plus if it always uses valuation rate, what the use of the below on the bom. Shouldn't this be what informs the user of the expected rates?
![image](https://user-images.githubusercontent.com/1822868/128861297-a93027ea-9e71-4ceb-a6df-879586134740.png)

Also, this is something that seemed to have occurred after updating to ERPNext: v13.8.0 (version-13)

**Comment by muchai** [comment]
Is this confirmed not as the expected output? The figures seem a bit arbitrary.

**Comment by muchai** [comment]
Looked through the functionality/code. Doesn't seem like a bug.

Just curious though, if the BOM is set to use Last Purchase Rate, why is the Stock Entry using valuation rate as the rate?

Made the change to accommodate this. Albeit, it's based on our customers need. Not sure of the correct standard.

**Comment by ankush** [comment]
>if the BOM is set to use Last Purchase Rate, why is the Stock Entry using valuation rate as the rate?

BOM rates are only for costing purposes IIRC. You can update it to sync up but stock transactions will use its own valuation logic to keep things consistent. Imagine inward stock valued at $100, but user adds BOM rate as $90, should that make it $90? Where to account for the difference of $10?
