### ISSUE TITLE
[V5] Print button not showing after document is saved and submitted.

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#2688]
Observed in Sales Order.

I save and submitted Sales Order, but print option didn't appear next to Menu button. It does work fine after a page reload.

![screen shot 2015-02-04 at 3 40 21 pm](https://cloud.githubusercontent.com/assets/910238/6038765/f8ec8f0e-ac85-11e4-8ca2-ff7be0711143.png)

**Comment by rmehta** [comment]
fixed
