### ISSUE TITLE
Trying to Start Job results in Error "AttributeError: 'dict' object has no attribute 'employee'"

### ISSUE THREAD

**Issue by cphoa28** [frappe/erpnext#26895]
## Description of the issue
When trying to start manufacturing job, error pops up: AttributeError: 'dict' object has no attribute 'employee'

## Context information (for bug reports)

**Output of `bench version`**
```
![image](https://user-images.githubusercontent.com/20081843/128957614-b1ef3f09-3f20-486e-ad6d-bac27ce74d24.png)
```

## Steps to reproduce the issue

1. Open Job Card (status = draft)
2. Click "Start Job"

### Observed result
Error Pops up:  AttributeError: 'dict' object has no attribute 'employee'

### Expected result
Not sure since 1st time using Job Cards.  Assume timer will start and then maybe a "Stop Job" icon shows?

### Stacktrace / full error message

```
Does not show up on error logs ( am looking in Frappe Log)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic
Node Version:  v10.24.0
Python3 Version:  v3.6.9
NPM version:  6.14.11
Yarn version:  1.19.1
Install Method:  upgraded from V12 via bench update --upgrade

**Comment by cphoa28** [comment]
Bench Version = 5.0

**Comment by cphoa28** [comment]
Erpnext Version:  v13.7.1 (Version-13)
Frappe Framework Version:  v13.7.0 (Version-13)

**Comment by ankush** [comment]
This was fixed in latest version. LMK if you're still facing this.
