### ISSUE TITLE
Primary NAVBAR labels dont show on cell phone or smaller screens

### ISSUE THREAD

**Issue by msalim79** [frappe/erpnext#26903]
## Description of the issue
Primary NAVBAR labels don't show on cell phone
## Context information (for bug reports)

**Output of `bench version`**
```
ERPNext: v13.8.0 (version-13)
Frappe Framework: v13.8.1 (version-13)
Bench Version 5.4.1
```

## Steps to reproduce the issue

1.Select Primary NavBar in Wesite Settings
2.Observe that if view on a cell phone the labels are not visable
3.Please see screen shots

### Observed result
Narbar lables not visable on a cell phone, although if you tap on the area a drop down does show.
### Expected result
Show\Adjust for cell phone screen
### Stacktrace / full error message

```
Non no errors
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.
ubuntu 20.04 bear metal, self installed
![IMG-4389](https://user-images.githubusercontent.com/30749464/128985042-188ef541-4b4f-41b5-83c9-3f63d4a0be1a.jpg)
![61447](https://user-images.githubusercontent.com/30749464/128985056-3e8444dd-6ab4-4c17-b1d3-a176ac4d9ba3.jpg)
![NavBarTemplate](https://user-images.githubusercontent.com/30749464/128985076-8a971964-9084-48a9-8520-f1ad99b3f73a.png)
![TopRightBurgerIcon](https://user-images.githubusercontent.com/30749464/128985086-a4acbe8c-c748-42b5-89b6-c712246ebae7.png)

**Comment by msalim79** [comment]
As seen on the last screen shot , there is a small outline of a button which is only visible if you hover over it, but no visible to the naked eye

**Comment by yadavyk** [comment]
Fixed with : https://github.com/frappe/frappe/pull/14356
