### ISSUE TITLE
New ERPNext Solutions request

### ISSUE THREAD

**Issue by davidjeba** [frappe/erpnext#26902]
Can we have a business focussed solution template instead of industry focussed solution template?

**Global Inventory Engine**
- stayable inventory -hotel, AirbnB etc
- storable inventory - warehouse, rental space, storage units etc
- sellable/resellable inventory - 3rd party inventory based on qty
- downloadable/streamable inventory - digital products 
- taskable (hireable/on-contract) inventory - fiverr like services

**Global Distribution Engine**
- stayable inventory -> distribute to hotels.com, booking.com, airbnb.com etc
- storable inventory -> distribute to sparefoot.com, neighbor.com etc
- sellable/resellable inventory -> distribute to amazon, flipkart etc
- downloadable/streamable inventory -> distribute to themeforest, codecanyon, instagram, facebook, tiktok etc
- taskable (hireable/on-contract) inventory -> distribute to indeed.com, linkedin.com, etc

**Comment by sharmanakul** [comment]
hi @davidjeba , they all seem like epic level of features. 
Would you like to detail out some of these or may be create some post of the [discuss](https://discuss.erpnext.com/) forum. This will help us in assessing the traction and prioritization.
