### ISSUE TITLE
Transaction Pricing Rule get applied even if it a based-on coupon

### ISSUE THREAD

**Issue by lovinmaxwell** [frappe/erpnext#26948]
## Description of the issue

- Pricing Rule created for coupon gets applied to all transactions without coupon is applied

## Steps to reproduce the issue

1. Create Pricing Rule for Coupon Based select Apply on Transaction, Price or Product Discount - Price
2. In Any Document [Quotation,..] which applies the pricing rule, by default discount is applied to all without the Coupon.

**Comment by nameduser0** [comment]
I think a fix is also needed in `apply_pricing_rule` so that non-transaction based pricing rules can be applied via coupons. The `Coupon Code Based` tick box is still available on those pricing rules but does nothing.
