### ISSUE TITLE
Mark Sales Invoice as Overdue when first payment becomes overdue

### ISSUE THREAD

**Issue by barredterra** [frappe/erpnext#26969]
**Is your feature request related to a problem? Please describe.**

In **Sales Invoice** we can specify a payment schedule. For example, 50 % after 14 days, 50 % after 30 days. Currently the latest date in the payment schedule is used as the invoice's due date. Only when the last payment becomes overdue, the invoice status changes to "Overdue".

However, we regard a **Sales Invoice** as overdue based on the scheduled payments. Once the first payment is overdue, we want to create a **Dunning**, reminding the customer that he is late on this payments.

**Describe the solution you'd like**

- The status of a **Sales Invoice** depends on the payment schedule instead of due date
- Set status to "Overdue" once a scheduled payment is overdue
- Introduce a new status "Partially Paid" that is displayed when payments have been received according to the payment schedule.
- ~Extend **Dunning** to consider only overdue payments and calculate overdue days correctly. Probably it would make sense to copy the **Sales Invoice**'s payment schedule to the **Dunning**.~ -> Create a new Issue for this

**Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.

**Additional context**

The option "Allocate Payment Based On Payment Terms" is set in **Payment Terms Template**.

**Comment by mymi14s** [comment]
👍
