### ISSUE TITLE
Respective Customer name not get displayed			

### ISSUE THREAD

**Issue by ShraddhaRanjane** [frappe/erpnext#2697]
Module:- Selling->Opportunity
1.Create new customer
2.Go to “Opportunity” form-> Select “Opportunity From” as Customer 
3.Select respective customer.
4.Name not get displayed inside “Customer / Lead Name”field. And at the time of selecting customer displaying error message like “Field selling_price_list not found.”

**Comment by rmehta** [comment]
which version?

**Comment by ShraddhaRanjane** [comment]
I am testing demo version i.e "http://staging5.erpnext.com" .
I have attach PNG file
![opportunity](https://cloud.githubusercontent.com/assets/10768627/6074950/5c5baad8-adef-11e4-9e9f-452c49c0b8c0.png)

**Comment by rmehta** [comment]
fixed
