### ISSUE TITLE
 If we try to save 'Item Price' form with valid data then error message is displaying.

### ISSUE THREAD

**Issue by geetanjalishitole** [frappe/erpnext#2703]
If we try to save 'Item Price' form with valid data then error message is displaying as 
“Duplicate name Item Price RFD/00001
Item Price RFD/00001 already exists
 Did not save”

**Comment by neilLasrado** [comment]
This is because you cannot have two price list with same name.
I have made price list name as 'no copy' so that it does not get copied when price list is duplicated

**Comment by jazzyjackson** [comment]
I arrived at this issue with confusion as I certainly did not have two price lists with same name...

Thanks to [this thread ](https://discuss.erpnext.com/t/solved-naming-series-for-item-price/15676/7) I realized I had item price list with ID numbers imported from an old install, when I should have deleted the column.

You can fix this issue by exporting your price list, deleting the data in the name (id) column, deleting your item prices, and importing the modified CSV file. I made a video of the process here

https://youtu.be/1WC0_J4Ba9w
