### ISSUE TITLE
Support Settings - Display Bug

### ISSUE THREAD

**Issue by garthvs** [frappe/erpnext#27048]
## Description of the issue
After changing the value for "Close Issue After Days" in "Support - Support Settings" the system still displays the original value of 7 days. "Auto close Issue after 7 days"

## Version information
Ubuntu 20.04
erpnext 13.x.x-develop
frappe 13.x.x-develop

## Steps to reproduce the issue
1. As Administrator
2. Select "Support"
3. Select "Support Settings"
4. Change the value of "Close Issue After Days" to 30
5. Select "Save"

### Observed result
"Auto close Issue after 7 days"

### Expected result
"Auto close Issue after 30 days"

**Comment by ankush** [comment]
I think it's just a bad description that's added to the field. Not a bug.

https://github.com/frappe/erpnext/blob/ece446ffe5fb3512c1d86b5182b0aa1c0473ea34/erpnext/support/doctype/support_settings/support_settings.json#L40
