### ISSUE TITLE
Cannot delete after cancelling because Sales Invoice is Link to GL Entry

### ISSUE THREAD

**Issue by Muaimi** [frappe/erpnext#27073]
## Context information (for bug reports)

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1.
2.
3.

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by nidhipurohit11** [comment]
There is a checkbox in "Account Settings" >> "Delete Accounting and Stock Ledger Entries on deletion of Transaction". This should be checked for the required action. 

If you still can't delete the invoice then reopen this.
