### ISSUE TITLE
Trying to delete Sales Invoice "Deletion is not permitted for country Nepal"

### ISSUE THREAD

**Issue by Sthaaz** [frappe/erpnext#27079]
I am trying to delete the entry of the Sales Invoice in the Account Section. Where i get error **Deletion is not permitted for country Nepal**

**Comment by ankush** [comment]
By design and compliance requirement. 

https://github.com/frappe/erpnext/blob/2b875bbf52f0010c306f9aea721d23f8aa7350fb/erpnext/regional/__init__.py#L9-L12
