### ISSUE TITLE
Salary Component Problem - v13.9.2 (HEAD)

### ISSUE THREAD

**Issue by THEOSKaris** [frappe/erpnext#27088]
In v13.9.2, expense accounts cannot be selected in Salary Component:
![image](https://user-images.githubusercontent.com/67414153/130468662-25cd55d4-d358-423a-a6dd-ee9611d6870f.png)

But these accounts are already added in the Chart of Accounts:
![image](https://user-images.githubusercontent.com/67414153/130467951-cb2abc1d-6e00-4c76-a8db-4a80c9e9ce6a.png)

**Comment by pateljannat** [comment]
This has been fixed with https://github.com/frappe/erpnext/pull/27089

**Comment by dj12djdjs** [comment]
This is still a problem on V13.10.2

**Comment by THEOSKaris** [comment]
@dj12djdjs you are right. This issue is still not resolved.
