### ISSUE TITLE
POS "New Customer" Should be at the top.

### ISSUE THREAD

**Issue by pifiu** [frappe/erpnext#2710]
On the POS screen when you are entering a customer and he is not there, you need to scroll all the way to the bottom of the customer list to find the "create new customer". I think it would be more ideal if its in the very top as a first entry. The more customers you have and more you have to scroll it seems inneficient right now.

On a similar but different request. Is it possible that if a customer is not in the customer list, that when the search result does not find him/her, that if you press the "create new customer" that the name you entered into the search query transfers over to the new customer "name" field? This seems more efficient and perhaps able to cut down the time of retyping names.

**Comment by rmehta** [comment]
thanks added in v5.
