### ISSUE TITLE
Data Export - Opportunities

### ISSUE THREAD

**Issue by jramns** [frappe/erpnext#2711]
Hi,

I have implemented Frappe-Bench and have installed ERPNext.

I have created opportunities but there are some discrepancies on screen between some of the fields (I noticed this in "Next Contact By", there could be others too) between the Data Export (Setup - Data -Import/Export, Data - Opportunities Download with Data) file and the one I see onscreen for a few (not all) records.

Would you please help and have this fixed as it is creating annoyances in managing opportunities and doing sales reviews.

Thanks

Jay

**Comment by rmehta** [comment]
Can you specify the "discrepancies"?

**Comment by jramns** [comment]
Hi,

Some of the fields are offset in the downloaded report. On-screen, it's
correct, but the report does not align the rows and the columns correctly,
at least for some of the records.

If you want, I can let you access the system and walk you through the
"discrepancies" I noticed.

Thanks

Jay

**Comment by rmehta** [comment]
Its best if you can specifically post what the problem is.

**Comment by jramns** [comment]
I understand. Here's what I observed. For some of the records the "Next
Contact By" value inaccurate. When I delete those records and recreate new
ones, the new ones are fine but the problem moves elsewhere.

How do I provide you meaningful information so that you guys can figure out
what's wrong?
