### ISSUE TITLE
URGENT !!! Status field error on submit in Quotation

### ISSUE THREAD

**Issue by nakul80** [frappe/erpnext#27134]
## Description of the issue
URGENT !!! Error while submitting Quotation
## Context information (for bug reports)

**Output of `bench version`**
```
Status cannot be "Open". It should be one of "", "Draft", "On Hold", "To Deliver and Bill", "To Bill", "To Deliver", "Completed", "Cancelled", "Closed"
```

## Steps to reproduce the issue

1. submit quotation
2.
3.

### Observed result
Status cannot be "Open". It should be one of "", "Draft", "On Hold", "To Deliver and Bill", "To Bill", "To Deliver", "Completed", "Cancelled", "Closed"
### Expected result
no error
### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by ankush** [comment]
These are statuses for a Sales Order. Somewhere you're automatically creating a sales order with wrong status. 


This is probably your customization and not ERPNext issue.
