### ISSUE TITLE
POS image/text overlap - style fix possibly needed

### ISSUE THREAD

**Issue by norulz** [frappe/erpnext#2713]
When preparing an SO using the POS function there is difficulty in reading the item's descriptions as the text placed with a large gap below the image and it is also overlapped by following row's image. See attached image

Editing pos.js (in folder ......./erpnext/accounts/doctype/sales_invoice/pos.js) fixed the issue with the following change:

Line 262 "height: 94px" instead of 140px. (this worked for me).
Line 257 should also most likely be changed so that  "max-height" is something suitable. 

![erpnext-02](https://cloud.githubusercontent.com/assets/6072089/6111895/f1d59220-b094-11e4-84a1-0a22c6f26f47.jpg)

**Comment by pifiu** [comment]
can this be addressed? This happens in the POS and also in the product view in the shopping cart.

**Comment by anandpdoshi** [comment]
Fixed in v5.0

**Comment by pifiu** [comment]
the shopping cart issue as well?
