### ISSUE TITLE
Prior to saving a new Production Plan, the button "Get Sub Assembly Items" is not working

### ISSUE THREAD

**Issue by guilmori** [frappe/erpnext#27142]
## Description of the issue
On creation of new Production Plan, prior to saving the Production Plan, the button "Get Sub Assembly Items" is not working, and is creating a new Production Plan record in the database every time it is clicked
## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 13.8.0
frappe 13.8.1
```

## Steps to reproduce the issue

1. Create a new Production Plan
2. Select an Item to Manufacture having sub-assembly in its BOM
3. DO NOT SAVE the Production Plan
4. Click "Get Sub Assembly Items" button

### Observed result
Nothing is added in the "Sub Assembly Items" grid, and if you look in the database, a new Production Plan was inserted, but the screen page is still showing the new-production-plan.
Click a second time on "Get Sub Assembly Items" button, and a second Production Plan is inserted in the database.
### Expected result
"Sub Assembly Items" grid should be filled and the page should show the newly inserted Production Plan.

## Additional information
![image](https://user-images.githubusercontent.com/9451512/130795333-a8e900d9-de53-4fa8-af97-5a0920199ae7.png)

**Comment by guilmori** [comment]
Removing this self.save() seems to resolve the issue
https://github.com/frappe/erpnext/blob/8880d132275d7e65f01998984aa3ccaedf05a606/erpnext/manufacturing/doctype/production_plan/production_plan.py#L527

**Comment by ankush** [comment]
https://github.com/frappe/erpnext/pull/27537
