### ISSUE TITLE
Accounting Dimension Name not showing properly with new DocType

### ISSUE THREAD

**Issue by alphabetway** [frappe/erpnext#27144]
![image](https://user-images.githubusercontent.com/61770703/130800240-44d573dc-4556-4653-a1b8-45d7a4ff914c.png)
1. Creating a new DocType named 'Segment'.
2. Add a 'New Accounting Dimension' with the newly created Reference Document Type above.
3. Add new item into 'Segment' Accounting Dimension.
4. Noticed 'Segment Name' fields are showing strange characters rather than the names.

**Comment by alphabetway** [comment]
Will this be a quick fix?

![image](https://user-images.githubusercontent.com/61770703/132642379-bb79ee28-719d-4648-a49d-15021f27ac0d.png)

**Comment by harshit-30** [comment]
@nidhipurohit11 can you share the steps to replicate it?

**Comment by nidhipurohit11** [comment]
The name can be set from Custmize form.
