### ISSUE TITLE
REMOTE_ADDR behind nginx

### ISSUE THREAD

**Issue by catroot** [frappe/erpnext#2715]
If covered by nginx ip is always server local and all sessions gets mapped to local server ip.
This is because of ignore the X-Forwarded-For header, which nginx sends to the frappe backend.
I have found in auth.py a line with
                    frappe.local.request_ip =  frappe.get_request_header('REMOTE_ADDR') \
                                or frappe.get_request_header('X-Forwarded-For')  or '127.0.0.1'
In this case, 'X-Forwarded-For' value will be assigned only if 'REMOTE_ADDR' header is absent, but it always present. Correct code will be
    frappe.local.request_ip =  frappe.get_request_header('X-Forwarded-For') \
                                or frappe.get_request_header('REMOTE_ADDR') or '127.0.0.1'

and several lines in sessions.py wich maps session to ip, doing it without any carry about 'X-Forwarded-For' header at all. Ugly... 
Pls fix. Thx!

**Comment by catroot** [comment]
as such, in stdout i see server ip in requests... and no site hostname... will be nice to fix client ip here too and printout a hostname of requested site.

01:22:21 web.1        | 192.168.8.8 - - [10/Feb/2015 01:22:21] "GET /desk HTTP/1.1" 200 -
01:22:21 web.1        | 192.168.8.8 - - [10/Feb/2015 01:22:21] "GET /assets/frappe/css/splash.css HTTP/1.1" 304 -
01:22:21 web.1        | 192.168.8.8 - - [10/Feb/2015 01:22:21] "GET /assets/css/frappe.css HTTP/1.1" 304 -
01:22:21 web.1        | 192.168.8.8 - - [10/Feb/2015 01:22:21] "GET /assets/frappe/js/lib/jquery/jquery.min.js HTTP/1.1" 304 -
01:22:21 web.1        | 192.168.8.8 - - [10/Feb/2015 01:22:21] "GET /assets/js/frappe.min.js HTTP/1.1" 304 -
01:22:21 web.1        | 192.168.8.8 - - [10/Feb/2015 01:22:21] "GET /assets/js/frappe.min.js HTTP/1.1" 304 -
01:22:21 web.1        | 192.168.8.8 - - [10/Feb/2015 01:22:21] "POST / HTTP/1.1" 200 -
01:22:22 web.1        | 192.168.8.8 - - [10/Feb/2015 01:22:21] "GET /assets/frappe/css/font/fontawesome-webfont.woff?v=3.2.1 HTTP/1.1" 304 -
01:22:22 web.1        | 192.168.8.8 - - [10/Feb/2015 01:22:22] "POST / HTTP/1.1" 200 -
01:22:22 web.1        | 192.168.8.8 - - [10/Feb/2015 01:22:22] "POST / HTTP/1.1" 200 -
01:22:22 web.1        | 192.168.8.8 - - [10/Feb/2015 01:22:22] "POST / HTTP/1.1" 200 -
01:22:52 web.1        | 192.168.8.8 - - [10/Feb/2015 01:22:52] "POST / HTTP/1.1" 200 -

**Comment by pdvyas** [comment]
Nice catch! Can you send a pull request.

Also, the stdout you sent is for a debugging server and is logged by werkzeug (and I don't have control over it's format, correct me if I am wrong)..

**Comment by catroot** [comment]
Pulled ok. Seems to be correct.
werkzeug doesn`t allow to define stderr log format. ((
Also, running gunicorn via supervisor lost all static content returning 404 err on all static requests and doesn`t write access and error logs for served requests at all.

this is my supervisor.conf:
[program:frappe-web]
command=/home/frappe/frappe-bench/env/bin/gunicorn -b 0.0.0.0:8000 -w 2 -t 120 frappe.app:application
autostart=true
autorestart=true
stopsignal=QUIT
stdout_logfile=/home/frappe/frappe-bench/logs/web.log
stderr_logfile=/home/frappe/frappe-bench/logs/web.error.log
user=frappe
directory=/home/frappe/frappe-bench/sites
log-syslog=true

web.log remains empty, error log contains some startup information.

**Comment by catroot** [comment]
Now, with gunicorn, serving static content via nginx allows site to function correctly, but it`s a piece of a duct tape.

**Comment by jwrober** [comment]
@catroot - what is this trying to fix? Is it still an issue 2 years later?
