### ISSUE TITLE
Issue in Stock Balance Report

### ISSUE THREAD

**Issue by amutaher** [frappe/erpnext#27151]
Stock Balance Report shows some values in Balance Value column which Balance Qty = 0 for some items as shown below.

![image](https://user-images.githubusercontent.com/45880595/130844970-5196c025-b8bb-4b73-8ffd-8b128a8f30d1.png)

**Comment by amutaher** [comment]
https://discuss.erpnext.com/t/how-to-validate-stock-balance-report-when-report-shows-0-balance-qty-but-nonzero-balance-value/79277

**Comment by ankush** [comment]
upgrade to v13 and share output of "stock ledger invariant check" report's data for this item and warehouse in CSV format, else it's not possible to debug this for us.
