### ISSUE TITLE
Can't Login | "Uncaught TypeError: $(...).dropdown is not a function" error, there is no login box.

### ISSUE THREAD

**Issue by QuakeString** [frappe/erpnext#27216]
Can't login because there is no login dialog.
There is no login dialog after clicking the "login" button

I'm on ERPNext 13 production branch ( upto date)
I get to see the error from debug windows
//
Uncaught TypeError: $(...).dropdown is not a function
    Rollup website.js:608
    jQuery 7
    Rollup website.js:603
    jQuery 4
//
I don't understand this meaning.
$bench --version 
5.0.0-dev

OS: Ubuntu 20.04 focal
Kernel: x86_64 Linux 5.4.0-80-generic
Shell: bash 5.0.17

Installed ERPNext using easy_installation_script

here is the screenshot
![Screenshot_20210829_174006](https://user-images.githubusercontent.com/5375918/131250666-7289e142-eee8-42ee-90a7-724f2a8fd97c.png)

**Comment by ankush** [comment]
`bench build`, `bench migrate` and force refresh solves this issue?

**Comment by QuakeString** [comment]
`bench update` and clean browser cache solved my issue

**Comment by ankush** [comment]
Then most likely it was an assets issue, did you manually update using `git pull` maybe?
