### ISSUE TITLE
Stock Ageing report showing incorrect data

### ISSUE THREAD

**Issue by rtdany10** [frappe/erpnext#27225]
![WhatsApp Image 2021-08-30 at 11 57 22 AM](https://user-images.githubusercontent.com/52111700/131295093-5d198c68-fbfe-4a77-b95b-7a3a899644c8.jpeg)

I believe non-serialized items' data are correct. But for serialized items, the report shows erroneous data.
ERPNext v13

**Comment by ankush** [comment]
Steps to reproduce:

1. Create any stock item with serial no series that's pure numbers. 
2. Make some stock entries ~1-month-old and open this report.

**Comment by rtdany10** [comment]
> serial no series that's pure numbers.

This is optional. The report will show incorrect data in ageing column if the item is serialized.
If the serial number is purely numbers, it will show huge value cause the serial number will be treated as quantity and added up.
If the serial number is not purely numbers, flt(serial_no) returns zero and nothing will be added.

Either way, the ageing columns of serialized items will show wrong data.
