### ISSUE TITLE
Rounding not upper in ERPNext

### ISSUE THREAD

**Issue by betabank** [frappe/erpnext#2723]
Hi, the issue is described here. Basically the round must be upper only when the decimal is 5-9 but 0-4 should be rounded down:
https://discuss.frappe.io/t/tax-round-calculation-bug/4708

**Comment by gohyc** [comment]
Any update on this issue as I have to manually (and very often) change the tax amount in database in order for by sales department to proceed with the orders.

**Comment by anandpdoshi** [comment]
This was fixed in v4 itself.
