### ISSUE TITLE
POS modify "Change Amount" and "writeoff"

### ISSUE THREAD

**Issue by michaeleino** [frappe/erpnext#27245]
**Is your feature request related to a problem? Please describe.**
suit the cash transaction with actual payments happens on the POS.

**Describe the solution you'd like**
as of V13 there is no way now to modify the “Change Amount” or "writeoff amount" ?
for ex. sale for 16 OR 14, customer pay 20, cashier will return 5, so there is a +/- 1 for write-off
or even sale for 19, customer pay 20, and no change will be returned
How to do this from POS ? it was available on previous versions!

**Describe alternatives you've considered**
open the form view of the invoice to set change/write-off amounts which is really odd on a POS cashier. 

**Additional context**
this feature was already available on previous version earlier than v13!
https://discuss.erpnext.com/t/feature-erpnext-v13-new-point-of-sale-beta-testing/61093/157?u=michaeleino

**Comment by michaeleino** [comment]
@ankush can you please help on this, are there any work around on this ?
may be it should be available to be enabled/disabled ...

**Comment by ankush** [comment]
Hi, that label was only for housekeeping. I don't know much about POS. 😅 

@nemesis189 ?

**Comment by nemesis189** [comment]
We have been working on a write off feature but it's taking some time due to some complications in it's logic. Once those get cleared we can maybe take your help to test it out for some actual scenarios maybe

**Comment by michaeleino** [comment]
sure, i would welcome to test it :) 
this same feature was working just fine on version-12 , i believe you may use the same logic of calculations 
thanks for the response

**Comment by michaeleino** [comment]
#reactivate
Is there any progress for this ?
