### ISSUE TITLE
Cannot create Customer or Opportunity from Lead

### ISSUE THREAD

**Issue by garthvs** [frappe/erpnext#27257]
## Description of the issue
When trying to create a Customer or Opportunity from inside a Lead the system responds with "Lead not found"

## Version information
Ubuntu 20.04
erpnext 13.x.x-develop
frappe 13.x.x-develop

## Steps to reproduce the issue
1. Create a Lead
2. Save Lead
3. Go back into the Lead
4. Click the Create dropdown
5. Select Customer or Opportunity

### Observed result
"Lead not found"
"The resource you are looking for is not available"

### Expected result
A new Customer or Opportunity is created

**Comment by ankush** [comment]
Not reproducible. You seem to be using pre-v13 release development branch. I'd recommend upgrading.
