### ISSUE TITLE
X and Z reports - end of day cash reconciliation for POS?

### ISSUE THREAD

**Issue by pifiu** [frappe/erpnext#2731]
Please see this original thread for a full explanation:

https://discuss.frappe.io/t/x-and-z-reports-end-of-day-cash-reconciliation-for-pos/4671

Basically it is a cash register reconciliation process.

**Comment by pifiu** [comment]
what can be done to move this feature forward? It seems to crucial for anyone who uses the POS. Without it, users are encouraged to reconcile the registers using another system that is not ERP or generating excel sheets to serve this function.

**Comment by chandutalluri** [comment]
hi rmehta 
please update POS cash register reconciliation process. it is very encouragement for small retailers.

**Comment by pifiu** [comment]
what is the status of this?

**Comment by ahmad18189** [comment]
Is there new development here ? 
if not please if any one can provide me with the best scenario and I will implement it and make pull request

**Comment by pifiu** [comment]
I think I was very detailed in the scenarios in the link on the first post. It provides screenshot and steps in order to use it.

**Comment by olamide2** [comment]
Is there anyway to push this forward ?? Without this feature I wonder how people are using ERPNext in retail

**Comment by dalers** [comment]
Does anyone do end-of-day balancing in a retail or other environment with daily cash/cheque/credit-card payments? How?

Thanks.

**Comment by ahmad18189** [comment]
Iam finishing Alpha virsion of X and Z report for POS .. I will push it in friday

**Comment by xdelios** [comment]
So is there any update on that?

**Comment by jwrober** [comment]
Duplicate. See Issue #7582
