### ISSUE TITLE
While Printing all Item Description shows the same even with default standard template

### ISSUE THREAD

**Issue by appayatechnologies** [frappe/erpnext#27329]
I am using Frappe Cloud based ERPNext Solution, While printing an Invoice or PO all the Item description is showing same whereas the item code and rates & taxes are correct, The description is always the description of first Item

I have attached herewith both the views, invoice creation where its is showing correct and in print (pdf) showing all the item description same
[Sales Invoice_Issue.odp](https://github.com/frappe/erpnext/files/7104073/Sales.Invoice_Issue.odp)
[SINV-21-00001.pdf](https://github.com/frappe/erpnext/files/7104076/SINV-21-00001.pdf)

**Comment by ankush** [comment]
This _looks_ like a custom print format... maybe there's bug in jinja code you have? 

Default formats work just fine, so this is not a bug. 


You can use community forums for discussing customizations: https://discuss.erpnext.com/

**Comment by appayatechnologies** [comment]
Even I use default its the same, Pl don't just brush aside saying look at your code, I have attached herewith the print developed with default Standard format available. 
[SINV-21-00004.pdf](https://github.com/frappe/erpnext/files/7111262/SINV-21-00004.pdf)
![image](https://user-images.githubusercontent.com/70690057/132120705-a5903e0d-7455-4bb5-8a54-580db7beab43.png)
