### ISSUE TITLE
Make Payment button disappears when adding products to POS transaction

### ISSUE THREAD

**Issue by pifiu** [frappe/erpnext#2732]
You can replicate this even on your online demo. More often than not when a product is added the button disappears. If you add more quantity sometimes it returns or sometimes it does not. It's a very fundamental part of the POS transaction wouldn't you say?

![pay button there](https://cloud.githubusercontent.com/assets/2664750/6161127/67477928-b23a-11e4-8f1a-43f9231fe6fe.PNG)
![pay button not there](https://cloud.githubusercontent.com/assets/2664750/6161130/6a546680-b23a-11e4-90c1-650d2de4fe33.PNG)

**Comment by system19** [comment]
I am getting the exact same disappearing make payment button issue as well.
Has anyone come up with a work around?

**Comment by rf489** [comment]
It seems to be generating inline css of display:none. My workaround was adding to the frappe.css file:
.make-payment{display:block !important;} and it seems to be working fine now.

**Comment by nabinhait** [comment]
Fixed in new pos
