### ISSUE TITLE
Duplicated Contact Name on patient creation using already existing customer

### ISSUE THREAD

**Issue by NoxOdonell** [frappe/erpnext#27335]
## Description of the issue
When creating a new patient with an already created customers it shows the following error
![image](https://user-images.githubusercontent.com/90055445/132029543-91005d49-8154-46cf-8d32-f172f8f300d0.png)

## Context information (for bug reports)
when you create a customer an then you fill up all fields from patient information, when saving it says "duplicated contact name", i changed the name of contact and saved and it worked, customer creation saves a contact and patient creation tries to save a new contact with the same name
**Output of `bench version`**
```

bench_manager 0.0.1
erpnext 13.10.0
frappe 13.10.0

```

**Comment by ChillarAnand** [comment]
Continued at https://discuss.erpnext.com/t/duplicated-contact-name-on-patient-creation-using-already-existing-customer/79840
