### ISSUE TITLE
[Paid Development] comission for payment entry on salesperson.

### ISSUE THREAD

**Issue by jorux** [frappe/erpnext#27336]
i would like to  commision my salespersons for any payments entries they do. the requirements would be:
1. payments commisions have a different rate than normal comissions, so a new field would be needed.
2. adding the report for such commisions in the document type, for the sales person commision summary report.

this is pretty much all. 
![imagen](https://user-images.githubusercontent.com/22998084/132033783-b1df8d44-9411-499a-b399-369d6d97559d.png)

**Comment by sharmanakul** [comment]
hey @jorux, i hope this got developed. If not, then post on the job board https://erpnext.org/erpnext-jobs
