### ISSUE TITLE
Issue with Greek Language

### ISSUE THREAD

**Issue by Sarakenidis** [frappe/erpnext#27337]
Hello all,

I have a issue with the setup-wizard or when i change the language user. When i am trying to configure my settings to change the language from English to Greek (el), it doesn’t displays the most Report & Masters for any modules.

I had installed a month ago another one erpnext and it works fine.

Please help me to fix that issue.

Thanks,
SK

**Comment by sharmanakul** [comment]
hi @Sarakenidis , has this been resolved?
