### ISSUE TITLE
Multiple payment methods/Split payment methods in POS

### ISSUE THREAD

**Issue by pifiu** [frappe/erpnext#2733]
I had bumped issue https://github.com/frappe/erpnext/issues/1204 but I could only access it by direct link so I was not sure if it was being looked into.

If a customer wants to pay their total with multiple forms of payment - credit card, cash, check, etc.

Is it possible to implement this? It should be very simple, just split the payments into the different accounts desired. It is a very simple feature to implement. Can you make a sprint run of all of these small POS issues for v5?

**Comment by pifiu** [comment]
will this make it to 5.0?

**Comment by Ananapple** [comment]
bump

**Comment by rmehta** [comment]
Coming in v7
