### ISSUE TITLE
STOCK REPORT ERROR

### ISSUE THREAD

**Issue by GKHRAJU** [frappe/erpnext#27347]
In stock balance we are finding negative value for the stock balance.

![image](https://user-images.githubusercontent.com/90170642/132161552-8113f93e-9d4c-4093-88b6-b72be2153328.png)

**Comment by sharmanakul** [comment]
Did you 'allow negative stock' in the stock settings?

https://discuss.erpnext.com/t/negative-balance-value/61006/3

Feel free to reopen if it still persists.
