### ISSUE TITLE
homepage hero image not working in V13

### ISSUE THREAD

**Issue by gdlrsilv3** [frappe/erpnext#27340]
the hero image is not working in V13, because the CSS is not filled correctly see below. I got this when I was debugging via developer tools.

![bugHeroImageERPNEXTV13](https://user-images.githubusercontent.com/47467528/132080103-b8fa5602-fb49-4bc5-8181-844dfa53d68a.jpg)

.hero-image {
    background-image: url({{ homepage.hero_image }});
    background-size: cover;
    padding: 10rem 0;

**Comment by Olawale1** [comment]
Hi @ankush 

Trust you're doing great. Seems this is still not fixed. Hope it can be resolved soon

Thanks plenty

**Comment by littlebunyip** [comment]
Is still an issue on version ERPNext: v13.36.1 (version-13)

**Comment by ruchamahabal** [comment]
https://github.com/frappe/erpnext/pull/31699
