### ISSUE TITLE
Include search fields in Project Link to other Transaction

### ISSUE THREAD

**Issue by Ponyooooo** [frappe/erpnext#27345]
## Description of the issue
1. Search field of a Project Link is not visible to other transactions except when linking only to a Sales Order.

![image](https://user-images.githubusercontent.com/60758795/132143111-40fa91a3-cc6b-41e7-907a-29afb5074acd.png)

But search field is not visible on Delivery Note Sales Invoice and the Buying Modules.

![image](https://user-images.githubusercontent.com/60758795/132143152-7f6e632f-82a5-47a2-a68b-dd6f1e9f1520.png)

![image](https://user-images.githubusercontent.com/60758795/132143170-1b0cd343-a277-415d-b4a6-d5c118ea42a4.png)

![image](https://user-images.githubusercontent.com/60758795/132143180-cf5682b0-f74d-4376-866a-874789660882.png)

## Context information (for bug reports)

**Output of `bench version`**
```
ERPNext: v13.9.2 (HEAD)
Frappe Framework: v13.9.1 (HEAD)

this is also a bug on V12
```

**Comment by ankush** [comment]
ref:  

https://github.com/frappe/erpnext/blob/ece446ffe5fb3512c1d86b5182b0aa1c0473ea34/erpnext/selling/doctype/sales_order/sales_order.js#L71-L78

https://github.com/frappe/erpnext/blob/ece446ffe5fb3512c1d86b5182b0aa1c0473ea34/erpnext/controllers/queries.py#L320
