### ISSUE TITLE
Error in Download and Upload Functionality

### ISSUE THREAD

**Issue by somfinso** [frappe/erpnext#27350]
I am able to download doc field..problem is when i am uploading csv..Is setting a field upload but when i click on update..Is reseting back...uploaded field are not getting updated..

Suggestion will be highly apcreciated since i need many doc csv from erpnext

**Comment by sharmanakul** [comment]
please refer to the documentation here https://docs.erpnext.com/docs/v13/user/manual/en/setting-up/data/data-import

remember to check if you are entering valid values. For example: correct value for customer name, item group, item names etc.

I'm closing it for now. But feel free to discuss the issue further.
