### ISSUE TITLE
Issue in creating demo site.

### ISSUE THREAD

**Issue by rakshithrddy** [frappe/erpnext#27351]
Hi,

I tried to create a demo site in my local and it failed with the mandatory field exception.
![image(1)](https://user-images.githubusercontent.com/36509967/132173394-6c7a8cf8-20ce-4bb3-9390-7e8ba133b267.png)

**Comment by sharmanakul** [comment]
hey @rakshithrddy , were you able to complete the setup? 
I hope you have already referred to the documentation on this. 
Feel free to post such issues on https://discuss.erpnext.com/. You will surely find help there. 😊
