### ISSUE TITLE
V5 - allow user to change workstation in production order

### ISSUE THREAD

**Issue by neilLasrado** [frappe/erpnext#2737]

**Comment by umairsy** [comment]
Scenario:

Considering for each machine separate Work Station will be created. All these machine does the same operation.

While production planning, if any on Work Stations is already loaded, I should be able to complete same operation on another Work Station. Hence, in the Production Order, user should be able to change Work Station for an operation.

**Comment by neilLasrado** [comment]
- [ ] make workstation editable in production order.
- [ ] make operation time editable in production order. (Operation time may change depending on workstation)
- [ ] ask user if he wants to re-plan operations. 
- [ ] if yes, re plan operations ahed. update planned timings etc

**Comment by neilLasrado** [comment]
Solved via pull request at https://github.com/frappe/erpnext/pull/2759
