### ISSUE TITLE
BOM for Fixed Asset creates hard-stop (Can't create stock entry or changed item type)

### ISSUE THREAD

**Issue by JomoliTech** [frappe/erpnext#27370]
## Description of the issue
Creating a BOM for a fixed asset results in an irreversible scenario.
Inventory is tied up, can't be reversed and the Work Order cannot be completed.

## Context information (for bug reports)
I needed to create a Fixed Asset out of multiple items I purchased.
I was able to create a BOM for the fixed asset and click "use in manufacturing".
Everything worked great until I reached the end of the Work Order and I'm stuck at an irreversible point.

I can't create the item, because I can't change it's Type from Fixed Asset to stock.
And the Stock Entry doesn't let me complete the Entry because the item isn't a Stock type.

**Output of `bench version`**
```

```

## Steps to reproduce the issue

1. You can create a Fixed Asset item: Computer-001
2. You can create a BOM for that fixed asset item in manufacturing: BOM Computer-001
3. You can go through all of the steps of manufacturing that item but one you click "Finish" you encounter a hard stop.

### Observed result

Message
Computer-001 is not a stock Item
### Expected result

Fixed Asset item is created

### Stacktrace / full error message
N/A nothing crashed

## Additional information
Linux Ubuntu 20.04 Desktop, EPR Next manual configuration
OS version / distribution, `ERPNext` install method, etc.

##Reason Guess:
Fixed Asset is an arbitrary check for stock entry.

**Comment by yadavyk** [comment]
This is a no stock item (fixed asset)

![image](https://user-images.githubusercontent.com/32797974/141232511-48293b36-6502-4b43-89c6-892132c7e646.png)

From here, a BOM can be initiated : 

![image](https://user-images.githubusercontent.com/32797974/141232572-68794b5a-a0dd-4983-a084-78e8d1746d7d.png)

Despite the filter of "maintain stock =Yes' in the field Item in BOM doctype : 

![image](https://user-images.githubusercontent.com/32797974/141232667-68defb0b-ac58-4060-b998-7ac969f57663.png)

Solution
On initiaing the BOM creation process from a fixed asset/no-stock item, the item field in BOM should be blank and an error message "<item> is not a stock item, BOM cannot be created."

Filter bom item code field such that:
No non stock item (with exception of template items)

**Comment by yadavyk** [comment]
Fixed with : https://github.com/frappe/erpnext/pull/27560

**Comment by JomoliTech** [comment]
This is the wrong fix.  The fix should be "create asset" when done.
