### ISSUE TITLE
Creating multiple items unnecessarily because of BOM levels

### ISSUE THREAD

**Issue by xickomesquita** [frappe/erpnext#27371]
## Description of the issue

When creating a multilevel production plan, the system creates the same item multiple times.

## Context information (for bug reports)

Creating items that contain the same raw materials in their composition, for part of each item, in addition to different raw materials, such as:

Item A - 3 units
       Subitem A - 15 units
       Subitem C - 10 units
       Subitem D - 25 units

Item B - 5 units
       Subitem A - 20 units
       Subitem Z - 15 units
       Subitem W - 12 units

The system creates a list as follows:

Subitem A - 15 units
Subitem A - 20 units
Subitem C - 10 units
Subitem D - 25 units
Subitem Z - 15 units
Subitem W - 12 units
Item A - 3 units
Item B - 5 units

**Output of `bench version`**
```
ERPNext: v13.7.0 (version-13)
Frappe Framework: v13.7.0 (version-13)
```

## Steps to reproduce the issue

1. Create some BOMs with some multi-level items i.e.

Bom X
-- Bom
   -- Bom
   -- Bom
   -- Item a
   -- Item b

2. Create a Production Plan with BOM X
3. Generate Work Orders

### Observed result

**Subitem A - 15 units
Subitem A - 20 units**
Subitem C - 10 units
Subitem D - 25 units
Subitem Z - 15 units
Subitem W - 12 units
Item A - 3 units
Item B - 5 units

![image](https://user-images.githubusercontent.com/38265198/132261580-ef46122e-3bd0-4908-86f0-b238cb8bc365.png)

### Expected result

**Subitem A - 35 units**
Subitem C - 10 units
Subitem D - 25 units
Subitem Z - 15 units
Subitem W - 12 units
Item A - 3 units
Item B - 5 units

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by sharmanakul** [comment]
hi @xickomesquita, you probably missed on the checkbox 'consolidate items' in the production plan.(on v13.15)

i'm closing this issue for now, feel free to reopen if there are any queries related to this.
