### ISSUE TITLE
Unpaid Expense Claim Report filter not liked with Employee

### ISSUE THREAD

**Issue by DaizyModi** [frappe/erpnext#27384]
## Description of the issue
In a report 'Unpaid Expense Claim', Filter for Employee is not linked with Employee Doctype. So it is not showing the list of employees.

## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 13.10.0
frappe 13.10.0
5.3.0
```

**Comment by ruchamahabal** [comment]
Fixed in: https://github.com/frappe/erpnext/pull/27530
