### ISSUE TITLE
TypeError: 'NoneType' object is not iterable while creating delivery note

### ISSUE THREAD

**Issue by jagannathmajumder** [frappe/erpnext#27388]
## Context information (for bug reports)

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1.
2.
3.

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by ankush** [comment]
After you get this error, can you go to the browser console and share the traceback?

How to:
Firefox: https://developer.mozilla.org/en-US/docs/Tools/Browser_Console
Chrome: https://developer.chrome.com/docs/devtools/console/

**Comment by ankush** [comment]
Closing, as this info isn't enough to identify issue. Add additional info for reproducing issue and I'll reopen.
