### ISSUE TITLE
Gross Profit: Incorrect Valuation Rate Depending on Sales Flow

### ISSUE THREAD

**Issue by dj12djdjs** [frappe/erpnext#27400]
## Description of the issue
ERPNext selling documentation notes there are 5 ways to process sales.
```
                   / ----- > Delivery Note
1. Sales Order -> |
                   \  ----- > Sales Invoice

2. Sales Order -> Delivery Note -> Sales Invoice
3. Sales Order -> Sales Invoice -> Delivery Note
4. Sales Invoice -> Delivery Note
5. Delivery Note -> Sales Invoice
```

![image](https://user-images.githubusercontent.com/29856401/132581192-b0551393-b186-45ff-838a-88e649575889.png)

If you process sales using methods 2 - 5 gross profit valuation rate is correct. However, using method 1 results in some sort of "last known" valuation rate as shown in issue: #27297 

My findings per sales flow are explained below:

1. Material Receipt: Item B  1000Nos x $0.98
2. ACC-SINV-2021-00007: Valuation rate is correct. (This is the first sale so method doesn't matter.)
3. Material Receipt: Item B  100Nos X $2.50.
4. ACC-SINV-2021-00008: Valuation rate is correct using method 2.
5. Material Receipt: Item B  100Nos X $3.00.
6. ACC-SINV-2021-00009: Valuation rate is incorrect using method 1.
7. ACC-SINV-2021-00010: Valuation rate is correct using method 3.

The problem happens when Sales Invoice and Delivery Note are not directly linked to each other.

![image](https://user-images.githubusercontent.com/29856401/132582553-99c025e8-f295-44e5-9503-a5b1855a2788.png)

## Context information (for bug reports)

**Output of `bench version`**
```
develop
version-13
version-12
```

## Proposed Resolution:

1. Perhaps when sales invoice or delivery note is submitted it will link dn_detail by looking it up through sales order.
2. Modify gross profit report to look for delivery note through sales order during processing.

**Comment by aakvatech** [comment]
Seen this as well on v13, but not sure if it was due to old data of v13 beta or whether it still is a problem.

**Comment by dj12djdjs** [comment]
@aakvatech it's definitely still a problem. I tried it with fresh data on a fresh install.

**Comment by dj12djdjs** [comment]
It seems I may have initially been wrong method 3 and 4 as they don't seem to be working now. I think I've narrowed it down if Sales Invoice Item does not contain delivery_note, or dn_detail field Gross Profit does not calculate properly.

**Comment by dj12djdjs** [comment]
@ankush This can be validated. Please see details below:
```
ERPNext: v13.16.0 (HEAD)
Frappe Framework: v13.16.0 (HEAD)
```
1. Default Valuation Method: Moving Average

2. Stock Ledger
![image](https://user-images.githubusercontent.com/29856401/145686217-4f425535-0d7c-421a-83a3-4d1a07218396.png)

3. Gross Profit
![image](https://user-images.githubusercontent.com/29856401/145686147-7e233cee-fff5-45d1-b110-761886cae1a1.png)

The discrepancy is caused by the details in the original post.

**Comment by ankush** [comment]
Sorry for confusion. The labels are just bulk added for stale issue cleanup.

**Comment by dj12djdjs** [comment]
@ankush Got it thank you. I noticed the frappe team has started prioritizing issues into milestones. I think inaccurate gross profit reporting is pretty important. What would need to be done to get this issue into a milestone? I submitted a PR months ago along with a test case to prevent this. I never received any comment about it.

**Comment by deepeshgarg007** [comment]
@dj12djdjs Please let us know if this [PR](https://github.com/frappe/erpnext/pull/32866) fixes your issue. If not please reopen the issue
