### ISSUE TITLE
[V5] Material Receipt Entry - Not allowing to submit for batch item

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#2740]
When attempt to submit Stock Entry, it ask for Batch ID. It has been provided already.

------------------------

![screen shot 2015-02-12 at 5 10 18 pm](https://cloud.githubusercontent.com/assets/910238/6166831/1973b2e8-b2da-11e4-9d91-64c14f661270.png)

**Comment by neilLasrado** [comment]
@umairsy  unable to replicate ... can you please re-check ?

**Comment by umairsy** [comment]
Replicating while creating Material Request for the Batch Item.

On Fri, Feb 13, 2015 at 12:53 PM, Neil Trini Lasrado <
notifications@github.com> wrote:

> @umairsy <https://github.com/umairsy> unable to replicate ... can you
> please re-check ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/frappe/erpnext/issues/2740#issuecomment-74214893>.
>



-- 
Thanks and Regards,
Umair Sayyed
www.erpnext.com

**Comment by neilLasrado** [comment]
Issue is Solved.
