### ISSUE TITLE
"Field company_address not found." Error when creating a new Purchase Order or Purchase Invoice

### ISSUE THREAD

**Issue by Nathaniel401** [frappe/erpnext#27419]
## Description of the issue
Upon creating a new Purchase Order, or a Purchase Invoice, an error pops up indicating that the field "company_address" is not found. This happened after upgrading to the latest release.

## Context information (for bug reports)
 I do suspect this new problem as come from changes made to fix issue #27217: https://github.com/frappe/erpnext/pull/27217

## Steps to reproduce the issue

1. Create a new Purchase Order, or Create a new Purchase Invoice

### Observed result
Error modal with the content: "Field company_address not found."

### Expected result
No error, and the page loads as usual.

ERPNext: v13.10.2 (version-13)
Frappe Framework: v13.2.1 (version-13)

**Comment by guilmori** [comment]
Same problem here

**Comment by vamagithub** [comment]
Linked PR #27441
