### ISSUE TITLE
Item Image not visible on mobile

### ISSUE THREAD

**Issue by hankjordan** [frappe/erpnext#27429]
## Description of the issue

On the mobile version of the Item page, the Item Image is not visible.

## Context information (for bug reports)

ERPNext Edge on Docker

**Output of `bench version`**
```
erpnext  v13.x.x-develop
frappe  v13.x.x-develop
```

## Steps to reproduce the issue

1. Create a new Item
2. Open the Item
3. Open the Sidebar

### Observed result

No Item Image

### Expected result

Item Image Visible

### Stacktrace / full error message

```
N/A
```

## Additional information

This appears to be caused by the ```hidden-sm hidden-xs``` classes on the sidebar. Removing the classes causes further issues, however - the upload modal becomes obscured by the sidebar which does not retract. This occurs by default on a vertically aligned tablet screen.

This issue causes the mobile and tablet versions of the page to be unable to change the Item Image.

**Comment by marination** [comment]
@hankjordan moved to frappe framework as it is a framework issue https://github.com/frappe/frappe/issues/15139
