### ISSUE TITLE
Define Item Attributes on Item Group

### ISSUE THREAD

**Issue by guilmori** [frappe/erpnext#27428]
Similar to the Item Attribute used with Item Variants, I would like to define Item Attributes on an Item Group.
When we create an Item and select the Item Group, the attributes in the Item Group would be shown for the user to input a value.
Each attribute could be marked as mandatory/optional in the Item Group.

I may do this development if time permits, I was wondering if anyone else would benefits from this feature ?

**Comment by sharmanakul** [comment]
hi @guilmori , did you validate it with any user? Let me know if I miss something because i don't see how it is going to be useful to the user.
