### ISSUE TITLE
Disabled users still appear in mention's drop down list

### ISSUE THREAD

**Issue by YamanQD** [frappe/erpnext#27426]
## Description of the issue

When typing "@" in the comments of a document to mention a user, disabled users still appear in the drop down list of users

**Used version`**
```
ERPNext: v13.9.1 (version-13)

Frappe Framework: v13.9.0 (version-13)
```

## Steps to reproduce the issue

1. Open a user's page and uncheck "Enabled"
2. Open an arbitrary document and go to the comments section
3. Type "@" and start typing the disabled user's name

### Observed result

The user appears in the drop down list of users to mention.

### Expected result

The user doesn't appear in the list.

**Comment by vamagithub** [comment]
Is this Solved? @ankush

**Comment by ankush** [comment]
Yes, https://github.com/frappe/frappe/pull/14017 

Part of last release.
