### ISSUE TITLE
Payment Entry

### ISSUE THREAD

**Issue by kunleoduntan** [frappe/erpnext#27432]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dj12djdjs** [comment]
https://docs.erpnext.com/docs/v13/user/manual/en/accounts/payment-entry ?

**Comment by ankush** [comment]
Update description and let us know if this needs to be reopened.

**Comment by kunleoduntan** [comment]
Payment entry can only be made against the following
 

1. When receiving money from customer
2. When making payment to supplier
3. When making inter account transfer
I like to suggest payment entry should also allow for expense entry instead of using journal entry.

**Comment by kunleoduntan** [comment]
![Payment Batch](https://user-images.githubusercontent.com/90121650/134454420-7f6483c4-c14c-4d9b-82c0-67703d027346.png)
![chrome_jd4K0WRtXA](https://user-images.githubusercontent.com/90121650/134454548-529a7024-d3f7-4684-94ff-2690693ca2c6.png)

I also like to suggest payment entry could also be entered in batch mode and in a single line for a complete transaction with actions buttons like what we have in the attached picture.
This enable non accounting personnel to be able to post and also be reviewed by someone before being updated.
