### ISSUE TITLE
Creating existing, partially depreciated assets with correct depreciation is impossible

### ISSUE THREAD

**Issue by blewsky** [frappe/erpnext#27431]
## Description of the issue
Creating/uploading existing, partially depreciated assets is broken. When saving/submitting the asset, 1. the "“Depreciation Posting Date”  is dropped, 2. “Expected Value After Useful Life” is changed to a wrong number. Therefore, the depreciation schedule ends up being calculated wrong. This way it is impossible to create existing, partially depreciated assets with a correct depreciation schedule.

## Steps to reproduce the issue

1. Importing the Assets via Data Import with “Calculate Depreciation” = 0 and “Is Existing Asset” = 1, and the respective amount for “Opening Accumulated Depreciation”
2. Entering the Gross Purchase Amount for past Available-for-use and Purchase Dates.
3. Selecting “Calculate Depreciation” and “Allow Monthly Depreciation”, adding “Number of Depreciations Booked”
4. Adding Finance book details (Depreciation method etc.), setting “Expected Value After Useful Life” = 0
5. Saving the Draft. Then ERPnext computes the depreciation schedule gets automatically. The schedule looks fine. The first bug is, that the “Depreciation Posting Date” is empty again and the “Value After Depreciation” is a wrong number (should be 0 in my understanding).
6.. I add the missing “Depreciation Posting Date” and save the Draft. After saving, the “Expected Value After Useful Life” is changed (in my case to exactly the amount of the “Opening Accumulated Depreciation” ) and thus the depreciation schedule is somehow changed to meet the new “Expected Value After Useful Life”. I can fix the “Expected Value After Useful Life” again and set it to 0. If I save the Draft again it will add another time the “Opening Accumulated Depreciation” to it and so on. I don’t see any way to keep the right depreciation schedule for future depreciations.

### Expected result
After saving/submitting, field values should not be changed, dropped by ERPnext. Creating/uploading existing, partially depreciated assets is broken. Otherwise it's impossible to start with a correct opening balance when porting to ERPnext.

## Additional information
More information on this problem and more detailed discussion in the forum:
https://discuss.erpnext.com/t/how-to-add-existing-partially-depreciated-assets/79989

ERPNext: v13.10.2 (HEAD) (also tested on v.13.9.2)
Frappe Framework: v13.10.0 (HEAD)

**Comment by hans-permana** [comment]
hi @nextchamp-saqib , I saw that this issue is being fixed in v13, is there any chance that this fix is also ported back to v12? We have encountered the same issue in v12.
