### ISSUE TITLE
Birthday Reminder keep getting sent out

### ISSUE THREAD

**Issue by adityoR007** [frappe/erpnext#27448]
## Description of the issue
Birthday reminder keep getting sent out even though the Birthday checkbox is not checked

## Context information (for bug reports)

**Output of `bench version`**
```
frappe v13.10.0
```erpnext v13.10.0
```

## Steps to reproduce the issue

1. Create an Employee and fill in the Date of Birth
2. Go to HR Settings -> Reminders -> uncheck the Birthday checkbox
3. Wait until the Employee Date of Birth match the system date

### Observed result
When an employee has a birthday on that date, the system giving the Birthday Reminder via Email to all of users

### Expected result
When the Birthday checkbox is uncheck, the system should not giving out email to all users

## Additional information

**Comment by ankush** [comment]
Fixed here: https://github.com/frappe/erpnext/pull/27365

part of next release
