### ISSUE TITLE
HR Settings: reminders cannot be turned off (solution included)

### ISSUE THREAD

**Issue by zongo811** [frappe/erpnext#27450]
## Description of the issue
When you turn off Reminders in "HR > Settings" they are sent anyway. Affects reminders for Birthday, Work Anniversaries & Holidays.

## Context information (for bug reports)
Reason for this is in the way the values of the Check-fields are read in **apps/erpnext/erpnext/hr/doctype/employee/employee_reminders.py**:
````
	to_send = int(frappe.db.get_single_value("HR Settings", "send_birthday_reminders") or 1)
	if not to_send:
		return
````
Should be 
````
	to_send = int(frappe.db.get_single_value("HR Settings", "send_birthday_reminders") or 0)
````
because currently **to_send** always contains 1 (true) regardless of the value read from the DB.
Apply this fix to all lines with "to_send = int(frappe.db.get_single_value("HR Settings"..."

**Output of `bench version`**
```
erpnext 13.10.2
frappe 13.10.0
```

## Steps to reproduce the issue

1. Set the birthday of an Employee so it happens today
2. In "HR Settings" disable birthday reminder
3. Run apps/erpnext/erpnext/hr/doctype/employee/employee_reminders.py

### Observed result
Birtday reminder is send.

### Expected result
Birtday reminder is not send.

### Stacktrace / full error message

```
-
```

## Additional information
OS version / distribution: Debain Buster

**Comment by ankush** [comment]
Duplicate https://github.com/frappe/erpnext/issues/27448
Fixed here https://github.com/frappe/erpnext/pull/27365 

Part of next release.
