### ISSUE TITLE
Chat is not working on v13-develop

### ISSUE THREAD

**Issue by abolinhas** [frappe/erpnext#27468]
Hi all, 
I installed v13-develop on debian 11, everything seems working except the chat. On website i enable the Chat feature, but when I reload the frontpage, i get this error.

chat.bundle.css not found
chat.bundle.js not found.

Output of bench version

ERPNext: v13.develop
Frappe Framework: v13.develop

![imagem](https://user-images.githubusercontent.com/3245485/133244498-0bef400a-e93d-4dc9-a22b-ef2b96e8af7f.png)

**Comment by ankush** [comment]
chat is moved to separate project

https://github.com/frappe/chat
