### ISSUE TITLE
[V5] Missing NIO Currency for Nicaragua

### ISSUE THREAD

**Issue by williamjmorenor** [frappe/erpnext#2746]
NIO (Nicaragua) Currency is not available when I try to create a new company.

**Comment by williamjmorenor** [comment]
Nicaragua is allready in 

https://github.com/frappe/frappe/blob/v5.0/frappe/geo/country_info.json

But in the demo I can shoose NIO when I tried to create a new company

**Comment by rmehta** [comment]
You have to enable the currency.
