### ISSUE TITLE
Production Plan Status Showing "Completed" but Work orders are Still not yet completed

### ISSUE THREAD

**Issue by casakthiveln** [frappe/erpnext#27480]
## Description of the issue
Production Plan Status Showing "Completed" but Work orders are not yet Started and completed. When a single work order is completed, the production plan updating its status as "Completed".
## Context information (for bug reports)

**Output of `bench version`**
```
ERPNext: v13.11.0 (version-13)

Frappe Framework: v13.11.0 (version-13)


```

## Steps to reproduce the issue

1.
2.
3.

### Observed result
![Plan](https://user-images.githubusercontent.com/63579207/133237167-62d1b746-9e21-4abf-a7da-ecba9c302ee1.gif)

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by casakthiveln** [comment]
Please see this thread. After this change the above issue raised.
https://github.com/frappe/erpnext/issues/26822#issue-961643072

**Comment by ankush** [comment]
@casakthiveln 

Can you please let us know whether some work orders over-produced and hence total produced qty was more than total required qty?

If that is the case then we can work out a better solution.

**Comment by casakthiveln** [comment]
@ankush 
First i thank you for allocating your time for this issue.
My Company is dealing with Dip Tea Bag Production like Lipton Tea,
One box of Finished goods will require 100 Tea bags and we are preparing a production plan.
This FG will have two sub-assembly
1. Convertion of Tea into Tea bags (in Machine)
2. Packing of 100 Tea bags per box (Manual Labour)

But while running the machine we will have process wastage of 2%. So, my machine counter will show 102 tea bags but our actual good production is 100.

So, after submitting the job card for 102 tea bags, in work order we are transferring material for 102 tea bags and finishing the work order with actual planned production which will add the cost of process loss to good production. please see below

![Untitled](https://user-images.githubusercontent.com/63579207/133764194-709532d6-47f7-4fb5-a6b9-45a5e34481ab.png)

Now what happening, After competition of one work order (Sub-Assembly) with the said over production, the production plan status change to "Completed" but one work order is still yet to complete to finish the plan. it is not considering whether all work orders under the plan are completed or not.

Before the fix for #26822 , The production plan status is showing "in Process" even all work orders are completed.

Pls help in this regard. Thanks in advance.

**Comment by casakthiveln** [comment]
@ankush 
This is happening only if work orders have job card. If job card quantity is more than work order quantity then after completion of that particular work order, the production plan status is updated as "Completed"

**Comment by casakthiveln** [comment]
Please update any solution

**Comment by casakthiveln** [comment]
@ankush pls update any solution... this is causing problems in our process

**Comment by casakthiveln** [comment]
@ankush boss pls help

**Comment by casakthiveln** [comment]
@ankush pls help to resolve this

**Comment by ankush** [comment]
Hello, will try and get it merged in the next release. No guarantees though 😅
