### ISSUE TITLE
Cannot delete Sales Invoice

### ISSUE THREAD

**Issue by Sthaaz** [frappe/erpnext#27507]
**Steps to Reproduce:**

- **Selecting** a Sales Invoice and deleting it pop-up an error Message "Deletion is not permitted for country Nepal".

**Version Number:**
ERPNext: v13.9.2 
Frappe Framework: v13.9.0

**Comment by ankush** [comment]
Not a bug. Regional compliance requirement as mentioned in linked discuss post above.
