### ISSUE TITLE
Leads

### ISSUE THREAD

**Issue by prashantam** [frappe/erpnext#2751]
![screen shot 2015-02-13 at 3 26 09 pm](https://cloud.githubusercontent.com/assets/1320876/6185487/d8640fee-b394-11e4-84f4-28ba915685cd.png)
How do I import my leads from Indiamart (through emails) into Erpnext?
I have set up the email from Sales Email settings.. still I have not received any direct lead contacts.
Kindly advice.

**Comment by rmehta** [comment]
should work - @umairsy can you take this offline?
