### ISSUE TITLE
Bug with Purchase Order Status

### ISSUE THREAD

**Issue by ghost** [frappe/erpnext#27514]
Hi,
there is a bug with purchase order status. I've created purchase receipt from purchase order. After receiving materials, purchase order's status stays on "to receive and bill" while purchase receipt document status is "completed".
Purchase receipt was canceled and amended(since I made mistake). Maybe that is cause?

ERPNext: v12.22.0 (version-12)
Frappe Framework: v12.19.2 (version-12)

**Comment by ghost** [comment]
I found what is the problem/cause. Here is SS of purchase receipt.

![image](https://user-images.githubusercontent.com/43913022/133428929-0678711a-e156-46fe-a2e6-be08f8a5bb23.png)

And here is SS of purchase order received qty(for one item).

![image](https://user-images.githubusercontent.com/43913022/133429100-f2e42070-b50a-4ecf-9cb6-8d90a4c0d426.png)


Same problem is with purchase invoice. System takes only one entry of component and ignores all other entries of same component.

**Comment by sharmanakul** [comment]
hey @Pararera , i tried replicating the issue
1. Created Purchase order and then received all the items in the full quantity. Status for both the order and the receipt was 'to bill'
2. Created purchase order and then received only one item in full quantity (first row), others partially received. Status for receipt was ' to bill' and for order, 'to receive and bill'

I'm closing this issue for now, feel free to reopen and provide the steps to replicate.

**Comment by ghost** [comment]
I will post three screenshots.


![1](https://user-images.githubusercontent.com/43913022/148213381-d0b8956a-b72a-427d-8c05-048653c296ee.PNG)
Shows receipt, remember 37pcs from first row.


![2](https://user-images.githubusercontent.com/43913022/148213384-fe5b4a26-2e07-49ef-8044-a4fef6eb2c69.PNG)
Shows order, ordered 50pcs for 2000-079 item.


![3](https://user-images.githubusercontent.com/43913022/148213385-8b371730-c483-4a1d-9bf8-b6871cdeddda.PNG)
Details from order for item 2000-079. Ordered 50pcs, but received 37pcs. Sum qty from receipt for item 2000-079 and you will get 50pcs.
System thinks that all qty will be placed on same warehouse.

**Comment by sharmanakul** [comment]
@Pararera I will suggest you upgrade to v13.

**Comment by ghost** [comment]
> @Pararera I will suggest you upgrade to v13.

No, we do not want to upgrade to v13 because of several reasons:
- It is not few clicks and open beer. Last time I did upgrade on private ERP, it failed.
- All docs are made based on v12
- v13 UI is awful compared to v12. I've tried v13 on private machine and I was "WTF?!?!". Actually, best UI had v11.
