### ISSUE TITLE
Sales return of products with serial numbers generate stock

### ISSUE THREAD

**Issue by perotom** [frappe/erpnext#27517]
## Description of the issue
When you create a sales return from a delivery note with products that have a serial number and you forget to put in the serial numbers, totally new serial numbers will be generated.

## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 13.10.2
frappe 13.10.0
```

## Steps to reproduce the issue

1. Create a delivery note
2. Add qty: 2 of product with serial number
3. Enter serial number of products in item pop-up.
4. Save and submit delivery note
5. Create a sales return
6. Change qty to 1. In the item pop-up no serial number will be given
7. Save and submit sales return

### Observed result
System will create new stock and serial numbers.

### Expected result
If product has serial number if must be checked that this product was in the delivery note before. No additional stock must be generated!

**Comment by cacarios** [comment]
Hi Thomas,

Isn't that on purpose? For bookkeeping, re-entering the product is considered a new transaction. You should be able to either re-enter the product and link it to an existing serial number or change ERP Next settings to allow you to delete any transactions linked to the delivery note.

**Comment by perotom** [comment]
But isn't it a little bit dangerous for sales returns?
Imagine you create a sales return and accidentally forget to enter the serial numbers of the devices the customer returned. Suddenly totally new stock was created in the system with new serial numbers but in real-life no stock was made.
I think there should be a check for: For every item with a serial number in a sales return, the serial numbers must be mandatory.
Right now: new stock will be created in a sales return which makes only sense with products without serial numbers.

**Comment by perotom** [comment]
@cacarios Is it somehow clear what I mean?

**Comment by ankush** [comment]
<img width="589" alt="Screenshot 2022-01-14 at 4 14 35 PM" src="https://user-images.githubusercontent.com/9079960/149503084-8eed125d-2326-4865-b7c0-cc00e4ed840d.png">


can't reproduce, currently return only seem to be able to re-activate a delivered serial no;
