### ISSUE TITLE
KeyError: 'shopping_cart' after upgrading to 13.11.0

### ISSUE THREAD

**Issue by enoy19** [frappe/erpnext#27550]
## Description of the issue
After upgrading from 13.10.X to 13.11.0 I am not able to access the "Shopping Cart Settings" anymore. 

## Context information (for bug reports)
* Run in a Docker Swarm (Single node)
*  ENV-Variables
    * AUTO_MIGRATE=1
    * ERPNEXT_VERSION=v13
    * FRAPPE_VERSION=v13

**Output of `bench version`**
```
erpnext 13.11.0
frappe 13.11.0
```

## Steps to reproduce the issue

1. Fresh install of 13.10
2. Deactivate the Shopping Cart + Products Page
3. Update to 13.11.0 by recreating the frappe-bench-v13 Docker-Swarm-Stack with the latest version 
4. Open app/shopping-cart-settings (Settings > Shopping Cart Settings)

### Observed result
![shopping_cart_bug](https://user-images.githubusercontent.com/24529735/133615188-6114b1e0-60c9-4be8-a63f-e30edf1d7b30.jpg)

### Expected result
Reaching the shopping cart settings

### Stacktrace / full error message

```
not available
```

## Additional information

Linux / Ubuntu 20.04.3 LTS, [Docker Swarm](https://github.com/frappe/frappe_docker/blob/develop/docs/docker-swarm.md)

**Comment by enoy19** [comment]
Settings were moved to:
E Commerce Settings

https://github.com/frappe/erpnext/pull/24603

**Comment by arjunkr92** [comment]
Getting following message in login screen and KeyError: 'shopping_cart'  if you click on shopping cart settings.

`Failed to get method for command erpnext.shopping_cart.doctype.shopping_cart_settings.shopping_cart_settings.is_cart_enabled with No module named 'erpnext.shopping_cart.doctype.shopping_cart_settings.shopping_cart_settings'`

**Comment by enoy19** [comment]
@arjunkr92 search for "E Commerce Settings"
![ecommercesettings_search](https://user-images.githubusercontent.com/24529735/133810935-e9e24b54-e9ea-4899-a9a5-fccbf976735a.jpg)

There you should find the old settings.

Also, the following is the PR for the E-commerce Refactoring: https://github.com/frappe/erpnext/pull/24603
...and [here](https://docs.google.com/document/d/17s6VxWeihTImSG2toR5Ma1jNq9nNAaYueP-dimNdQ4I/edit?usp=sharing) you can find the Unofficial E-commerce guide.

**Comment by marination** [comment]
@arjunkr92 This is a stale JS assets issue or a build issue. Try rebuilding.
