### ISSUE TITLE
Allocated amount in reference in Payment Entry API Error

### ISSUE THREAD

**Issue by chrisdent** [frappe/erpnext#27556]
We were making Payment Entries through APIs normally. 

In the last 2 versions we receive this error:
total_outstanding = sum(d.allocated_amount for d in self.get('references'))\\nTypeError: unsupported operand type(s) for +: 'int' and 'str'\\n\"]"}

Typing on the site the same information as it is in the API it goest through ok. The error comes out only on the API. We are sending a number, but apparently the api is trying to make a concatenation and there goes an error.

The Error is specifically in the Allocated amount inside the reference section in Payment Entry API.

**Comment by pifabs** [comment]
Can you show an example payload that triggers this error?

**Comment by chrisdent** [comment]
Yes! thanks for helping

this is the JSON that calls the payment entry, and that used to work perfectly.
{"payment_type":"Receive","party_type":"Customer","party":"customer-name","party_name":"customer-name","submit_on_creation":"1","docstatus":1,"mode_of_payment":"Stripe","paid_to":"Stripe-Stripe - compa","paid_amount":9.39,"received_amount":9.39,"paid_to_account_balance":0,"paid_from":"Debtors - compa","deductions":[{"account":"Stripe Service Charges - compa","cost_center":"Main - compa","amount":"0.61"}],"title":"customer-name","remarks":"","source_exchange_rate":1,"target_exchange_rate":1,"base_received_amount":"10.00","reference_no":"6148b8877039b","reference_date":"2021-09-20","references":[{"reference_doctype":"Sales Invoice","reference_name":"ACC-SINV-2021-00759","total_amount":"10.00","outstanding_amount":"10.00","allocated_amount":"10.00"}]}

This is the traceback:
{"exc":"[\"Traceback (most recent call last):\\n  File \\\"/home/erpnext/frappe-bench/apps/frappe/frappe/app.py\\\", line 68, in application\\n    response = frappe.api.handle()\\n  File \\\"/home/erpnext/frappe-bench/apps/frappe/frappe/api.py\\\", line 140, in handle\\n    doc = frappe.get_doc(data).insert()\\n  File \\\"/home/erpnext/frappe-bench/apps/frappe/frappe/model/document.py\\\", line 238, in insert\\n    self.run_before_save_methods()\\n  File \\\"/home/erpnext/frappe-bench/apps/frappe/frappe/model/document.py\\\", line 971, in run_before_save_methods\\n    self.run_method(\\\"validate\\\")\\n  File \\\"/home/erpnext/frappe-bench/apps/frappe/frappe/model/document.py\\\", line 860, in run_method\\n    out = Document.hook(fn)(self, *args, **kwargs)\\n  File \\\"/home/erpnext/frappe-bench/apps/frappe/frappe/model/document.py\\\", line 1158, in composer\\n    return composed(self, method, *args, **kwargs)\\n  File \\\"/home/erpnext/frappe-bench/apps/frappe/frappe/model/document.py\\\", line 1141, in runner\\n    add_to_return_value(self, fn(self, *args, **kwargs))\\n  File \\\"/home/erpnext/frappe-bench/apps/frappe/frappe/model/document.py\\\", line 854, in <lambda>\\n    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)\\n  File \\\"/home/erpnext/frappe-bench/apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py\\\", line 83, in validate\\n    self.validate_payment_type_with_outstanding()\\n  File \\\"/home/erpnext/frappe-bench/apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py\\\", line 140, in validate_payment_type_with_outstanding\\n    total_outstanding = sum(d.allocated_amount for d in self.get('references'))\\nTypeError: unsupported operand type(s) for +: 'int' and 'str'\\n\"]"}

**Comment by Anuja-pawar** [comment]
> "references":[{"reference_doctype":"Sales Invoice","reference_name":"ACC-SINV-2021-00759","total_amount":"10.00","outstanding_amount":"10.00","allocated_amount":"10.00"}]}

Could it be because amount is being passed as a string ? 
It should be int or float, right

**Comment by chrisdent** [comment]
thanks @Anuja-pawar.

This fixed the issue.
