### ISSUE TITLE
 Feature Request: New sales order action from Communication Detail

### ISSUE THREAD

**Issue by betabank** [frappe/erpnext#2755]
Hi,

we think it would be very useful that in the Communication detail would be an action to create a sales order linked to this communication. Once the incoming emails are integrated in ERPNext, this provides better tracking within the sales processes.

From forum:
https://discuss.frappe.io/t/new-sales-order-action-from-communication-detail/4754

**Comment by gmplab** [comment]
It already can create lssue / lead / opportunity from Communication
