### ISSUE TITLE
Feature request: Delivery date in Sales invoice

### ISSUE THREAD

**Issue by betabank** [frappe/erpnext#2756]
Hi,

we think the delivery date should be transported to the Sales Invoice from the Sales Order or from the Delivery Note. This date is mandatory in invoices, at least in Europe and probably in more countries so we think it makes sense to add by default this field in ERPNext.

To see the customization problem to get the delivery date in the invoice, please see the discussion:
https://discuss.frappe.io/t/delivery-date-script/3761

**Comment by betabank** [comment]
Hi, is this planned for an upcoming version?
Thanks!

**Comment by nabinhait** [comment]
A single Sales Invoice can be made against multiple sales order/deliver note. Thats why we can't add "Delivery Date" field in Sales Invoice parent form. We can add it in child table, but that will not look good in print format. Hence it will be bettr if you customize it.
