### ISSUE TITLE
Rename Batch not working

### ISSUE THREAD

**Issue by guilmori** [frappe/erpnext#27573]
## Description of the issue
When we rename a Batch, only the batch_id field gets updated, the name field remains with old value

## Context information (for bug reports)

**Output of `bench version`**
```
13.10.0
```

## Steps to reproduce the issue

1. Open Batch page
2. Click on the title to open the rename dialog
3. Change the batch name and hit rename

### Observed result
Only the batch_id field gets updated, the name field remains with old value

### Expected result
Both fields should be updated

**Comment by guilmori** [comment]
As a temporary fix, I did the following customization in Batch doctype
1- In Form Settings section, set Allow Rename checked
2- In View Settings section, remove "batch_id" from Title Field (Title Field is now empty)

**Comment by guilmori** [comment]
Why `Stock Ledger Entry.batch_no` is of fieldtype Data and not Link ?
It won't get renamed...

**Comment by ankush** [comment]
This is intentional. Changing `name` of batch is not allowed.

**Comment by guilmori** [comment]
So what if a batch number has been mistyped?

**Comment by ankush** [comment]
Either amend the transaction that introduced it or create a new batch and move stock.

**Comment by guilmori** [comment]
Then clicking on the title should not open the rename dialog, this is confusing for users.
