### ISSUE TITLE
Company Name (based on session default) next to ERPNext logo in the desk.

### ISSUE THREAD

**Issue by HakeemAzma** [frappe/erpnext#27572]
**Describe the solution you'd like**
To display the company name as well as logo based on the current session default somewhere on the screen in desk. I'm thinking it could be next to the ERPNext logo. 

**Additional context**
![image](https://user-images.githubusercontent.com/39662310/133827743-8cf56d05-ee2d-41fd-8a7b-1b2b74765785.png)

**Comment by ankush** [comment]
Can be done by adding a little bit of custom js in `app_include_js` https://frappeframework.com/docs/user/en/python-api/hooks#desk 

This has been asked many time before. It won't be allowed in vanilla ERPNext for branding purposes.
