### ISSUE TITLE
Deleting a product image - allow one to re-add it without uploading it again.

### ISSUE THREAD

**Issue by pifiu** [frappe/erpnext#2757]
If I upload the main image for a product and then decide to delete it to select another image, and then go back to the original, I have to delete each one and re-upload it. It would be easier if the images can just be re-selected instead of re-uploaded.

In the bottom of the product page there is an "attachments"  section with the links to the file names for all of the uploads associated with this product. If they are there wouldn't it be easier to just re-select one of those instead of constantly re-uploading?

**Comment by rmehta** [comment]
Was not planning to get this through, but was fixing another issue related to attachments, so now this is fixed in v5 :smile:
