### ISSUE TITLE
Asset Deprecation Problem - ERPNext v13.11.0

### ISSUE THREAD

**Issue by THEOSKaris** [frappe/erpnext#27579]
**WHEN ASSET DOCUMENT IS IN 'DRAFT' STATE**
![image](https://user-images.githubusercontent.com/67414153/133892098-67bed84f-4b13-4dcc-addd-d102faeb549a.png)

Depreciation amount for first month is different from other months. Depreciation amount should be N100,000.
![image](https://user-images.githubusercontent.com/67414153/133892266-d69dd2ea-b267-41a8-bd21-575fca6125e4.png)

**WHEN ASSET DOCUMENT IS SUBMITTED**
![image](https://user-images.githubusercontent.com/67414153/133892517-64944d65-cc63-4045-9f43-7426c6ef4470.png)

Depreciation amounts change when document submitted.  Depreciation amount should be N100,000.
System says asset is fully depreciated. Thus, monthly depreciation account journals are not generated.
![image](https://user-images.githubusercontent.com/67414153/133892613-25691066-37ca-4001-9710-62b03fddea7f.png)

This seems to be a system bug.

**Comment by aakvatech** [comment]
@THEOSKaris why was this closed?
