### ISSUE TITLE
Cannot customize Sales Order

### ISSUE THREAD

**Issue by rtdany10** [frappe/erpnext#27588]
![image](https://user-images.githubusercontent.com/52111700/133961390-02db2d6e-cbfc-43b0-a42d-45ac8b57024b.png)

https://github.com/frappe/erpnext/blob/a158b825fc3db0ab835a13d7a3290e071a8b8998/erpnext/selling/doctype/sales_order/sales_order.json#L575

**Comment by ankush** [comment]
what are you trying to change it to?

**Comment by ankush** [comment]
Supported on develop and v13 both https://github.com/frappe/frappe/blob/b2f78de243d47a534b761f133cd9d27376148e25/frappe/model/__init__.py#L76


https://github.com/frappe/frappe/blob/2d72f8016f0ed544663dfbba5ddda64ba1173ae6/frappe/model/__init__.py#L76

**Comment by ankush** [comment]
Tested, works fine. Maybe you need to pull the latest version of Frappe. 

Or share some steps to reproduce 😅

**Comment by rtdany10** [comment]
> Tested, works fine. Maybe you need to pull the latest version of Frappe.

Unsure why my Frappe app wasn't updated. It's not included in excluded-apps.
Still running on v13.4. Will update and check, thanks :)
