### ISSUE TITLE
Bug in coupon code handling

### ISSUE THREAD

**Issue by pifabs** [frappe/erpnext#27591]
## Description of the issue
I have an issue when using coupon code in quotation doc. The problem is that the pricing rule linked to the coupon I am using still applies even though I have already removed the coupon code in the quotation.
## Context information (for bug reports)

**Output of `bench version`**
erpnext 12.5.0
frappe 12.3.0

## Steps to reproduce the issue

1. Create pricing rule
![image](https://user-images.githubusercontent.com/47163292/133965713-b5b1a3e0-3409-4737-89e6-13b435380ea9.png)
![image](https://user-images.githubusercontent.com/47163292/133965733-6595e2bb-3710-4904-9e4c-144678a7ee97.png)

2. Create coupon and select the pricing rule you have created in the above step
![image](https://user-images.githubusercontent.com/47163292/133965772-1221f8a0-7ac5-43f7-94bf-9f5c87e884f0.png)

3. Create quotation and apply set the coupon you have created in the above step
4. Save quotation but do not submit. 
![image](https://user-images.githubusercontent.com/47163292/133966849-f42231fe-3b78-4e01-b042-a5c70d9605d1.png)

5. Now try to remove the coupon and save the quotation.
![image](https://user-images.githubusercontent.com/47163292/133966910-0949df39-846c-4f0c-aafd-8574e370f1f9.png)

### Observed result
After step 4, discount based on coupon should reflect in "Additional Discount Percentage" and/or "Additional Discount Amount" field(s)
After step 5, The discounts should remain in the  "Additional Discount Percentage" and/or "Additional Discount Amount" field(s)

### Expected result
After step 5, Since we are using the pricing rule in the context of coupon, pricing rules bound to a coupon should not apply in quotation, sales order and sales invoice
### Stacktrace / full error message
No error displayed

## Additional information

OS version / distribution, `ERPNext` install method, etc.
Ubuntu LTS 18.04

**Comment by yadavyk** [comment]
https://github.com/frappe/erpnext/pull/27608
