### ISSUE TITLE
Can't obtain items from Purchase Order in Purchase Receipt

### ISSUE THREAD

**Issue by chrisdent** [frappe/erpnext#27618]
While trying to get items from Purchase order in Purchase Receipt the following error appears:

TypeError: make_purchase_receipt() takes from 1 to 2 positional arguments but 3 were given

ERPNext: v13.11.0 (version-13)

**Comment by casakthiveln** [comment]
Update to v13.11.1 it is already sorted out

#27563

**Comment by chrisdent** [comment]
Confirmed. Is fixed in 13.11.1
