### ISSUE TITLE
SMS Setting Field sms_gateway_url (Data) can not accomodate string - Works on Converting to Small Text

### ISSUE THREAD

**Issue by chechani** [frappe/erpnext#27619]
SMS gateway URL in some cases not fit into length of 140 characters and once converted to small text, it works
So SMS Gateway URL filed should be changed from Data to Small Text to reolve this issue for all

## Context information (for bug reports)

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1.
2.
3.

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by bhavesh95863** [comment]
https://github.com/frappe/frappe/pull/14273

**Comment by ankush** [comment]
https://github.com/frappe/frappe/pull/14273
