### ISSUE TITLE
Cannot send New Email from Issue

### ISSUE THREAD

**Issue by FiloSpaTeam** [frappe/erpnext#27617]
## Description of the issue
Actually if i receive an Issue and i try to send New Email from Activities in the bottom section, the system reply me: "Service Level Agreement None not found". I checked all the DocType related to Issue but there is no default value as None. 

## Context information (for bug reports)

**Output of `bench version`**
```
bench_manager 0.0.1
erpnext 13.11.1
frappe 13.11.0
frappe_s3_attachment 0.0.1
nextcloud_integration 0.0.1
```

## Steps to reproduce the issue

1. Open Issue List
2. Receive a new Issue from Email Account linked to Issues
3. Click New Email
4. Send Email
5. Cannot Send

### Expected result
Send email as just some day ago (before the upgrade)

### Stacktrace / full error message

```
Service Level Agreement None not foundThe resource you are looking for is not available
```

## Additional information

Ubuntu 20.04 LTS + ERPNext installed without Docker

**Comment by FiloSpaTeam** [comment]
Fixed resetting with:
```
bench --force reload-doc core doctype communication
bench --force reload-doc core doctype communication_link
```

**Comment by FiloSpaTeam** [comment]
Need to reopen, after some hours the problem come back

**Comment by itg-dave** [comment]
I have the same problem using the docker setup.

**Comment by FiloSpaTeam** [comment]
Seems that rebooting regularly the server helps, but hey this not certainly a solution

**Comment by FiloSpaTeam** [comment]
The problems still there with version:
```python
bench_manager 0.0.1
erpnext 13.12.1
frappe 13.12.1
frappe_s3_attachment 0.0.1
nextcloud_integration 0.0.1
```

**Comment by devdattakane** [comment]
We are facing the same problem.

**Comment by FiloSpaTeam** [comment]
Seems working with latest release :) Closing

**Comment by FiloSpaTeam** [comment]
Need to reopen. After upgrade to version-14 the problem came back! :(

**Comment by FiloSpaTeam** [comment]
Bump

**Comment by FiloSpaTeam** [comment]
After v14.2 the problem still there...

**Comment by deepeshgarg007** [comment]
<img width="1312" alt="Screenshot 2022-10-27 at 8 53 18 PM" src="https://user-images.githubusercontent.com/42651287/198331739-fa28b389-db8b-4724-b444-34bd3f3ccbb4.png">
 
I checked and was able to send the email without any issues, I don't have any SLAs defined either
<img width="1338" alt="Screenshot 2022-10-27 at 8 53 34 PM" src="https://user-images.githubusercontent.com/42651287/198331894-cd3eabe1-eefa-4f34-b5de-d49481f4f524.png">

Please share traceback of the error and reopen

**Comment by FiloSpaTeam** [comment]
![Schermata del 2022-10-27 17-26-32](https://user-images.githubusercontent.com/2974561/198332786-9c40da2e-a025-46a0-8d7e-b91b6867a650.png)
![Schermata del 2022-10-27 17-26-50](https://user-images.githubusercontent.com/2974561/198332789-fbeba1b1-ff76-408b-8838-17e91b7cbecd.png)
![Schermata del 2022-10-27 17-27-11](https://user-images.githubusercontent.com/2974561/198332790-b4903d54-7cd8-4e16-8611-50a92d840fba.png)

The error appears after i click on "New Email" or "Reply" inside an Issue and try to send
