### ISSUE TITLE
No E-Mail from Issue when not using SLA

### ISSUE THREAD

**Issue by wojosc** [frappe/erpnext#27627]
When trying to send an E-Mail from an issue the system will report, that there is no Service Level Agreement "None". We are not using SLAs.

When activating SLA or just putting a SLA in the field in issue the e-mail will be sent.

Please look into this, thank you.

Best
Wolfram

**Comment by akitibala** [comment]
hi @wojosc , can you please help in understanding the issue with  steps (if possible with screenshots) for reproducing ?

**Comment by wojosc** [comment]
good morning @akitibala here you go
![SLA Issue](https://user-images.githubusercontent.com/22279621/135574107-25ed3d1d-2ed8-4d7f-a993-b6844fecae99.gif)
:

**Comment by wojosc** [comment]
j

**Comment by deepeshgarg007** [comment]
Same as https://github.com/frappe/erpnext/issues/27617
Closing this issue marking as duplicate
