### ISSUE TITLE
Work Anniversary Alerts

### ISSUE THREAD

**Issue by bibinqcs** [frappe/erpnext#27631]
## Description of the issue

ERPNext is sending work anniversary alerts even though the setting is turned off, also it is sending Alerts for Zero years 😅 
Attaching screen shots of the email alerts and HR  settings screen

![work_anniversary](https://user-images.githubusercontent.com/17405044/134162614-f2d746e0-f2f3-4655-9bab-3c8f889d5ad4.PNG)

![work_anniversary_2](https://user-images.githubusercontent.com/17405044/134162641-3d474475-a60d-4015-9d5e-308896119ad8.PNG)

I did an update to the latest version hoping that would resolve this issue, I will close the issue if the update resolves the issue.

## Additional information

OS: Ubuntu 20.04
ERPNext: v13.11.1 (version-13)
Frappe Framework: v13.11.0 (version-13)
Bench: 5.6.0

**Comment by ankush** [comment]
https://github.com/frappe/erpnext/blob/394645872ad238479755467185d0d69146d7cdfd/erpnext/hr/doctype/employee/employee_reminders.py#L185-L189
