### ISSUE TITLE
Production Plan - purchase uom conversion is not applied in material request items

### ISSUE THREAD

**Issue by guilmori** [frappe/erpnext#27637]
## Description of the issue
Production Plan - purchase uom conversion is not applied in material request items

**Output of `bench version`**
```
v13.11.0
```

Wrong indentation on this line:

https://github.com/frappe/erpnext/blob/e5a062ceb6ab6565dc8cbc7bc3bd4a1c1aa8c344/erpnext/manufacturing/doctype/production_plan/production_plan.py#L705

Please fix and make a unit test.

**Comment by rohitwaghchaure** [comment]
Fixed https://github.com/frappe/erpnext/pull/32654
