### ISSUE TITLE
SSL certificate expiration for the website https://translate.erpnext.com

### ISSUE THREAD

**Issue by dubinet** [frappe/erpnext#27641]
The SSL certificate for the website https://translate.erpnext.com has expired.
So we come to the following error:

requests.exceptions.SSLError: HTTPSConnectionPool(host='translate.erpnext.com', port=443): Max retries exceeded with url: /api/method/translator.api.get_strings_for_translation/?language=sk&start=0&page_length=100&search_text=&FrappeClient=%3Cclass+%27frappe.frappeclient.FrappeClient%27%3E&translator=%3Cfrappe.frappeclient.FrappeClient+object+at+0x7f7a6dec19a0%3E (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1131)')))

**Comment by ankush** [comment]
resolved now. 

A permanent solution for this is in the works.
