### ISSUE TITLE
Fixed price for work orders and job cards

### ISSUE THREAD

**Issue by cacarios** [frappe/erpnext#27643]
Dear ERP Next/Frappe team, community and maintainers,

**Is your feature request related to a problem? Please describe.**
Instead of having hourly rates, there are service providers/employees that work with a set price. Supposing that you have a custom furniture business, your company hire freelancer woodworkers and furniture fitters, and you pay them a set price, instead of an hourly rate, to keep your business running, you need to calculate how much you need to pay to each freelancer.

**Describe the solution you'd like**
The feature suggestion would be to allow both hourly rates and set prices in work orders and job cards. Working with a set price would make the quotation process easier as companies could precisely define the amount to be paid for a service without going over budget. Linking an employee with a job card/work order would allow one to filter who produced what and pay employees accordingly.

**Describe alternatives you've considered**
A set price field would be included both in work orders, BOM and job cards. When calculating the cost of a BOM, this value would be part of the total cost. In salary component, the user may create a component summing up the values of all work orders/job cards produced linked to an employee, allowing the company to pay per production.

**Comment by sharmanakul** [comment]
hi @cacarios, how critical is this feature for you? Have you tried discussing/validating it with others?
