### ISSUE TITLE
Python is cross-platform then why cannot we setup it on windows without virtual machine and ubuntu

### ISSUE THREAD

**Issue by Muhammadinaam** [frappe/erpnext#27652]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Python is cross-platform then why cannot we setup it on windows without virtual machine and ubuntu

**Comment by ankush** [comment]
Frappe is a "full-stack" framework and that means it requires certain additional dependencies compared to typical frameworks. Most if not all frappe apps are deployed on Linux, hence only mac/Linux is supported as a dev envirornment. 

Making assumptions about underlying OS has also simplified development a bit.
