### ISSUE TITLE
STOCK COUNT ON POS NOT IN SYNC WITH STOCK LEDGER

### ISSUE THREAD

**Issue by Papitom101** [frappe/erpnext#27651]
## Description of the issue
Some of the items on the POS are not the actual amount of stock quantity available on the stock ledger
## Context information (for bug reports)
The highlighted item on the POS stock
![image](https://user-images.githubusercontent.com/7777594/134722271-ba04656f-c72e-4f2d-b7fb-7df92765c632.png)
![image](https://user-images.githubusercontent.com/7777594/134723001-69385515-46f4-4f0a-a79e-2030d0bce676.png)
![image](https://user-images.githubusercontent.com/7777594/134723617-22cb342f-24fe-483a-a575-95f94487ba8f.png)
The stock levels of the highlighted items differs from the quantity shown on the POS, what could cause this issue?
**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1.
2.
3.

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by ankush** [comment]
POS doesn't immediately update stock, this is kinda expected behavior. Were those items being sold in that session?

**Comment by sharmanakul** [comment]
@Papitom101 closing this issue based on the comment above.
