### ISSUE TITLE
High permission level doctype field still appears in standard report

### ISSUE THREAD

**Issue by YamanQD** [frappe/erpnext#27669]
## Description of the issue
We want items valuation rate field to be hidden for all users except system administrators.
We changed valuation rate's permission level to 5 in all doctypes, and it no longer appears in documents.

However, if one of the users generates a standard report, "stock balance" or "stock ledger" for example, the valuation rate column still appears in the report.  

### Expected result
Valuation rate column should be hidden in standard reports, and cannot be manually added without sufficient permissions. 

**Used version**
```
ERPNext: v13.11.0 (version-13)

Frappe Framework: v13.11.0 (version-13)
```

**Comment by szufisher** [comment]
can you provide some screen shot to explain in more detail, based on which we can reproduce the issue. thanks.

**Comment by YamanQD** [comment]
## To reproduce the issue
1. Go to customize form
2. Select the "Item" form
3. Change perm level of the valuation rate field to 5
4. Go to role permission manager
5. Select "Item" doctype
6. Add a new rule: (Role: System Administrator, Permission Level: 5)
7. Login using an account that doesn't have the System Administrator role
8. Go to Stock Balance Report and generate a report

### Noted result
The generated report has a column with the name "Valuation rate" and it's populated with the valuation rates of items

### Expected result
The report shouldn't have a valuation rate column, since the user doesn't have sufficient permissions to access it

## Screenshots
 
![image](https://user-images.githubusercontent.com/58234003/135226226-16dca5a3-3449-45de-84c5-49933d2d8563.png)
![image](https://user-images.githubusercontent.com/58234003/135226334-594d8dd3-da28-4bed-8ca7-4fb4f6a1ebb8.png)
![image](https://user-images.githubusercontent.com/58234003/135226359-00203668-d7c7-43b8-8e02-261d14b5de09.png)

![image](https://user-images.githubusercontent.com/58234003/135226418-f68af276-a500-4f05-8829-360c6cfb3d68.png)
![image](https://user-images.githubusercontent.com/58234003/135226456-67febf41-eb23-4cd3-b18a-84f6ed5d2a36.png)

![image](https://user-images.githubusercontent.com/58234003/135226699-78f3570f-2218-45e7-8b55-cbb6928cd55b.png)


@szufisher

**Comment by YamanQD** [comment]
Hello @szufisher 
Any update on this?
Note that the same problem occurs with the "report-view" of a doctype
Fields that have a high permission level and normally don't appear in the document because of insufficient permissions, still appear in the report-view of that doctype.
I hope this can be fixed soon.
Thank you.

**Comment by szufisher** [comment]
you can refer my app https://gitee.com/yuzelin/zelin_permission

in hooks.py 
override_whitelisted_methods = {
	"frappe.desk.query_report.run": "zelin_permission.override.run_wrapper",
	"frappe.desk.query_report.get_data_for_custom_field":"zelin_permission.override.get_data_for_custom_field_wrapper"
}

for more details check override.py
