### ISSUE TITLE
Arabic language and RTL stlye.css not worhing probablly

### ISSUE THREAD

**Issue by ahmad-91** [frappe/erpnext#27671]
welcome 
i hope solve RTL fault in desk page itsnt work probably 
plz we need arabic language 
i used your cloud free trail at now and this issue still appear 
i attache pic for the fault 
when select any module from right side is nothing appear  on left panel 
![Uploading issue.png…]()

**Comment by ankush** [comment]
image is missing. 
Also, there were few RTL fixes in framework recently. Please confirm if this is still an issue / create new one.
