### ISSUE TITLE
Issue with BOM Operation being a child table of both BOM and Routing

### ISSUE THREAD

**Issue by guilmori** [frappe/erpnext#27692]
## Description of the issue
BOM and Routing doctype both have a child table using BOM Operation
Javascript frappe.ui.form.on('BOM Operation', ...) gets triggered in both routing.js and bom.js form

## Steps to reproduce the issue

1. Put some javascript breakpoint on events within the frappe.ui.form.on('BOM Operation') of both routing.js and bom.js
2. Visit Routing List and go within one Routing
3. Visit BOM List (without refreshing the browser), go within one BOM
4. For example, if you update Workstation in BOM Operation, and you had a breakpoint set in both routing.js and bom.js, you will see both breakpoint gets hit. If you change time_in_mins, you will see a javascript error because the child script of routing.js is executing out of the context of its parent doctype.

### Expected result
This seems to have been overlooked by those who engineered this. This can create nasty bugs.
Sharing the same child table in multiple parent doctypes is quite dangerous.

**Comment by ankush** [comment]
is anything actually broken or this is just observation on reuse?

Just to be clear, reusing the same table is absolutely not a problem. Having duplicate code is a much worse problem than reuse like this.

**Comment by guilmori** [comment]
> is anything actually broken or this is just observation on reuse?
> 
> Just to be clear, reusing the same table is absolutely not a problem. Having duplicate code is a much worse problem than reuse like this.

I am not sure what else to add...
Have you tried the outlined steps ? Do you get a javascript error if you update time_in_mins?

If you go into Routing page prior to going into BOM page, the frappe.ui.form.on('BOM Operation', ...) that was done in routing.js is still active and will execute while in the BOM page (and vice versa).

The is not a question of reuse at all, this behavior make no sense and will certainly introduce bug like now it crashes when you update time_in_mins in BOM page if you visited Routing page previously.

Events registered on a child table using frappe.ui.form.on('BOM Operation', ...) within the Routing page should only execute while in the Routing page, not when I'm in the BOM page.

**Comment by guilmori** [comment]
Thanks stale bot !
