### ISSUE TITLE
incorrect autoname - suffix colon : missing in naming_series

### ISSUE THREAD

**Issue by jigneshpshah** [frappe/erpnext#27705]
https://github.com/frappe/erpnext/blob/c800ff50689fe4778360430a7783e7848f81705f/erpnext/e_commerce/doctype/website_item/website_item.json#L5

@marination  , autoname should be **naming_series:**

as a result it is not picking the default series WEB-ITM-.####.

because of this patch fails  for case : if item name  is same but different item_code.

Also it will give duplicate item name validation, if user will try to enter  same Website Item Name for different item_code. 
the route will differentiate the item.

I think , system is intended and  should allow same item_name but can have different item_code.

it is because of the above suffix colon missing,  it is not allowing.

**Comment by marination** [comment]
@jigneshpshah Heres the fix https://github.com/frappe/erpnext/pull/27720
The website item creation patch will be re-run in the fix.
