### ISSUE TITLE
Website homepage missing

### ISSUE THREAD

**Issue by zenicolas** [frappe/erpnext#27709]
<img width="1433" alt="Screenshot 2021-09-30 at 08 50 04" src="https://user-images.githubusercontent.com/26570996/135394831-a4e22896-e3b3-483b-be4c-0e1e814c665b.png">

https://user-images.githubusercontent.com/26570996/135402712-5850bc8c-43b8-4c67-8e37-99bdc004afbf.mov

Homepage is not redirecting to the predefined route. 

Home link works fine and shows the correct web page.

**Comment by rioshaz** [comment]
@zenicolas  create a redirect route from  "/" to "home"( or your specific choice of page)

redirect is available in wbsite settings.

**Comment by jrd2017** [comment]
I have the same issue with the docker version.  I'm currently using v13.16.0 for Erpnext and Frappe. Currently, get the message:

 Error 404 There's nothing here
The page you are looking for has gone missing.

I will really appreciate any help.  Thanks

**Comment by zenicolas** [comment]
@jrd2017 try the redirect method that worked for me.

@rioshaz thank you for the advice it solved my issue

**Comment by jrd2017** [comment]
@zenicolas  Do you have any literature on how to do the redirection?  I'm an amateur on programming. I'm not sure how the docker files work.  Thanks!

**Comment by rioshaz** [comment]
@jrd2017 when u go to website settings u can see route setting that's where u put redirection, you dont need any programming skills for this

**Comment by jrd2017** [comment]
Thanks... It worked.. I didn't know about that dropdown menu part..
