### ISSUE TITLE
ERPNext Docs - Stock Depreciation Entry Links Broken

### ISSUE THREAD

**Issue by tjomtek** [frappe/erpnext#27711]
## Description of the issue
In the Attachment file, the file link is missing 
## Context information (for bug reports)
https://docs.erpnext.com/docs/v13/user/manual/en/stock/articles/creating-depreciation-for-item#step-1

V13 of the documentations 
![depreciationofitems](https://user-images.githubusercontent.com/77873407/135410585-5eb58e48-3e87-46a5-8b86-1e2de81a2a7b.png)

**Comment by nidhipurohit11** [comment]
Fixed
