### ISSUE TITLE
Migrate fails at "Executing erpnext.patches.v12_0.update_vehicle_no_reqd_condition" (v12 to v13 on frappecloud.com)

### ISSUE THREAD

**Issue by elan-k** [frappe/erpnext#27714]
## Description of the issue
Migration Fails While upgrading the site from V12 to V13 on frappecloud.com. 

Error at "Executing erpnext.patches.v12_0.update_vehicle_no_reqd_condition"

### Stacktrace / full error message
![image](https://user-images.githubusercontent.com/78781781/135440207-6e7773cc-f1cf-4870-9be8-ccff51cffb95.png)
![image](https://user-images.githubusercontent.com/78781781/135440268-a553bd28-ef87-4c61-a3dc-3cc32a346623.png)

## Context information (for bug reports)
The backups from the existing site (V12) and using the same to create the new site creation (V13) on frappecloud.com, which will migrate the site from V12 to V13 as per the guide provided (https://frappecloud.com/docs/sites/version-upgrade).

Related Issue #https://github.com/frappe/erpnext/pull/27195 

## Additional information
Hosted On frappecloud.com
ERPNext V12.22.0

**Comment by elan-k** [comment]
Thank you @shadrak98 for your response on the PR https://github.com/frappe/erpnext/pull/27195

But we have hosted our site with frappecloud.com, where we don't have access to the console and database. [Note: Getting the help from the support team on executing commands on the console]

I have taken the backups from the existing site (V12) then uploaded the same to the new site (V13), which will migrate the site to V13 as per the guide provided (https://frappecloud.com/docs/sites/version-upgrade). 

But it fails at,

**_"Executing erpnext.patches.v12_0.update_vehicle_no_reqd_condition"_**

Is there any suggestion on our scenario here?

Thanks in Advance!

**Comment by elan-k** [comment]
As @shadrak98 mentioned, running the following on the console

frappe.reload_doc('accounts', 'doctype', 'sales_invoice', force=True)

Get the following error in the migrating step again : 
Executing erpnext.patches.v13_0.check_is_income_tax_component 22-06-2020 ...
....
...
..
frappe.exceptions.DoesNotExistError: DocType POS Invoice not found

so I was trying to reload the "POS Invoice" DocType using the following

frappe.reload_doc('accounts', 'doctype', 'pos_invoice', force=True)
frappe.reload_doc('accounts', 'doctype', 'pos_invoice_item', force=True)

but getting the following error on the console, 
![image](https://user-images.githubusercontent.com/78781781/136765581-492c1aa2-c478-458b-9241-0681f4b385b5.png)

Also, I don't have "POS Invoice" Doctype, I do have only "Sales Invoice" DocType in our instance. 

Getting confessed with this error!

@shadrak98 : Plz help us to resolve this so that we can upgrade to V13. It looks like POS_Invoice DocType is part of V13.

Version Details :
ERPNext: v12.25.0 (HEAD)
Frappe Framework: v12.22.2 (HEAD)

**Comment by elan-k** [comment]
Why this thread has been closed without any remarks?

Comment should be added to guide the community members in the right direction. I'm could not find any value in this closing of the thread and why should we create a thread here if this can be closed like this?

@ankush : ?

**Comment by ankush** [comment]
https://github.com/frappe/frappe/issues/14335 
https://github.com/frappe/erpnext/pull/27897 


context: I've bulk closed several issues which I know have been fixed.

**Comment by elan-k** [comment]
Ok... Got it.

Thank you for your quick response.
