### ISSUE TITLE
[V5] Server Error message when Save Lead

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#2771]
This error message only comes if I select another user in the "Next Contact By" field. When I save Lead with this field blank, it saves just fine.

http://pastebin.com/iQ1RXGuA

![screen shot 2015-02-18 at 1 04 44 pm](https://cloud.githubusercontent.com/assets/910238/6243757/c3c71c06-b76e-11e4-8124-6bdb7facb04e.png)

**Comment by rmehta** [comment]
fixed
