### ISSUE TITLE
[V5] Opportunity title - Not clear

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#2773]
Attached is an image of Opportunity made for Lead. In the Opportunity, it shows Lead ID as Opportunity title. I found it confusion, and assumed this Opportunity to be Lead. 

We should update Lead Name or Lead's Organisation name as Opportunity title.

![screen shot 2015-02-18 at 1 16 11 pm](https://cloud.githubusercontent.com/assets/910238/6243888/f175ef22-b770-11e4-9827-975a53f0e4c0.png)

**Comment by rmehta** [comment]
fixed.
