### ISSUE TITLE
Item-Wise Sales History Report is Blank (Selling Module)(ERPNext: v13.11.1)

### ISSUE THREAD

**Issue by THEOSKaris** [frappe/erpnext#27736]
No matter the filter one applies, the Item-Wise Sales History report in Selling module does not display.
![image](https://user-images.githubusercontent.com/67414153/135704312-62229e90-0a23-453f-b5bd-a28203a25c20.png)

**Comment by THEOSKaris** [comment]
If you try to generate the **Item-Wise Sales History Report** in Selling Module, it returns blank. I am not sure what more details I can provide.

**Comment by Anuja-pawar** [comment]
It seems to be working, checked multiple instances..
![Screenshot 2021-10-22 at 1 08 20 AM](https://user-images.githubusercontent.com/60467153/138345527-484acf19-645b-4f0f-88f8-872302efae8c.png)

You can check if there are any Sales Order for the filters you've applied.. 
If you've Sales Order, check if there's any error in the browser console
