### ISSUE TITLE
Event Streaming issue ERPNext: v13.11.1 (TYPEERROR)

### ISSUE THREAD

**Issue by dufani1** [frappe/erpnext#27730]
I can not save Event Producer on Consumer site and got the following error:

![cosumer site](https://user-images.githubusercontent.com/23026263/135602463-2596e239-c29d-4166-a230-23b32237945b.png)

**Comment by ankush** [comment]
duplicate of https://github.com/frappe/event_streaming/issues/13



Please don't create duplicate issues.
