### ISSUE TITLE
Statistical Component

### ISSUE THREAD

**Issue by kunleoduntan** [frappe/erpnext#27737]
Please post on our forums:

for questions about using `ERPNext`: https://discuss.erpnext.com

for questions about using the `Frappe Framework`: ~~https://discuss.frappe.io~~ => [stackoverflow](https://stackoverflow.com/questions/tagged/frappe) tagged under `frappe`

for questions about using `bench`, probably the best place to start is the [bench repo](https://github.com/frappe/bench)

For documentation issues, use the [ERPNext Documentation](https://erpnext.com/docs/) or [Frappe Framework Documentation](https://frappe.io/docs/user/en) or the [developer cheetsheet](https://github.com/frappe/frappe/wiki/Developer-Cheatsheet)

> **Posts that are not bug reports or feature requests will not be addressed on this issue tracker.**

**Comment by kunleoduntan** [comment]
Hello, feel that when you make a salary component statistical, it will not show on the pay slip while calculation can be based on it. It is noticed that the formula or calculation inserted to the component don’t work when the component doesn’t appear on the pay slip.

Question
How can I make use of the formula or calculation in a statistical component without appearing on the pay slip.
Thank you

**Comment by sharmanakul** [comment]
@pushkarjsh88 please validate and update the status.
