### ISSUE TITLE
Edit Item Stock level show duplicate record

### ISSUE THREAD

**Issue by tespheakdeyesoftix** [frappe/erpnext#27747]
Hi, 
When ever Edit Item page is render or I press reload the Stock Level section always render new section as show as image below
![Screenshot 2021-10-02 203729](https://user-images.githubusercontent.com/23375032/135718782-ef9b7465-dc12-4533-adf8-57a2a5ec616c.png)

**Comment by ankush** [comment]
This only seems to be broken on `develop` branch... most likely because of changes from tabs 😅
