### ISSUE TITLE
[V5] Error on submitting BOM

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#2777]
Steps:

1. Submitted BOM.
1. Cancelled that BOM. Didn't find Amend option.
1. Duplicated that BOM to create new BOM.
1. On submitting this BOM, getting this error message.

![screen shot 2015-02-18 at 2 49 13 pm](https://cloud.githubusercontent.com/assets/910238/6244769/981d6510-b77d-11e4-8416-46c8279c7e0f.png)

**Comment by rmehta** [comment]
Cannot replicate.
