### ISSUE TITLE
V13 Item Tax always zero

### ISSUE THREAD

**Issue by perotom** [frappe/erpnext#27770]
## Description of the issue

Item tax template is not used to add item tax. 

## Context information (for bug reports)

Flag "Automatically Add Taxes and Charger from Item Tax Template" in settings is set.

**Output of `bench version`**
```
erpnext 13.11.1
frappe 13.11.0
```

## Steps to reproduce the issue

1. Create a sales invoice 
2. Add item and set tax item template.

### Observed result
Item rate and Net item rate is the same. No tax will be added to the invoice.

### Expected result
Item tax added to the invoice. Should work like https://docs.erpnext.com/docs/v13/user/manual/en/accounts/item-tax-template
**Note: Docs are outdated. There is no tax category anymore**

## Additional information
Other related bugs might be:
https://github.com/frappe/erpnext/issues/26103
https://github.com/frappe/erpnext/issues/21616

**Comment by ankush** [comment]
Tax rate will be shown as 0 as you can have multiple tax rates in the same transaction;  but do you see tax breakup in the table below?

**Comment by perotom** [comment]
I don't see the tax breakups. Here are my details:
Item details:
![Screenshot 2021-10-04 at 12 11 32](https://user-images.githubusercontent.com/3322872/135833690-649bdd2e-5c08-49a9-8640-178f4cc920c9.png)

Invoice:
![Screenshot 2021-10-04 at 12 12 28](https://user-images.githubusercontent.com/3322872/135833704-b975477f-8e47-4c7e-b0b2-494aafb0668f.png)

**Comment by perotom** [comment]
@ankush Do you need any additional data? Am I missing something?

**Comment by sharmanakul** [comment]
@harshit-30 please address this.

**Comment by harshit-30** [comment]
@perotom this works fine in my test instance, try posting the query on our discuss forum - our members will help you debug the issue. 

Try refreshing ERPNext before you create a Sales Invoice. 
Item Master: 
![image](https://user-images.githubusercontent.com/46772424/144979778-3ff75427-2114-4775-b4c3-79b28c458ffb.png)


Sales Invoice: 
![image](https://user-images.githubusercontent.com/46772424/144980038-e2b87138-b9e1-4353-9d60-e4386c9a6595.png)


Marking this as closed, if this is replicable - please comment.
