### ISSUE TITLE
Error Message at installation  of Frappe Version 5

### ISSUE THREAD

**Issue by geetanjalishitole** [frappe/erpnext#2778]
I have run command following command 
-mkdir frappe_five
-cd frappe_five
-virtualenv .
-source ./bin/activate
-git clone https://github.com/frappe/bench bench-repo
-pip install -e bench-repo
-bench init frappe-bench && cd frappe-bench
-vim config.json
-modify '"shallow_clone": true' to '"shallow_clone": false'
-save and close the file
-bench get-app erpnext https://github.com/frappe/erpnext
-bench update --bench
-bench migrate-to-v5
but error message displayed after run the last command  "bench migrate-to-v5"
Error message shown in link http://pastebin.com/C1GaU1TA

**Comment by pdvyas** [comment]
Could not replicate, could be a temporary problem with Pypi. Does it still now work?
