### ISSUE TITLE
POS Error 

### ISSUE THREAD

**Issue by soome-Rs** [frappe/erpnext#27816]
When a sales invoice is created and the payment method is cash, the process is done correctly, but the problem is when the invoice is returned and the method of payment for the return is determined Cash is not debited from the cash account, but is transferred to the bank account

![pos](https://user-images.githubusercontent.com/4391256/136016589-72519208-801b-40fc-aaf6-c860d897c690.png)
![pos 2](https://user-images.githubusercontent.com/4391256/136016604-2c02caf1-6553-4312-8ffe-cb8324d2bf01.png)
![pos 3](https://user-images.githubusercontent.com/4391256/136016612-33242f8f-295d-4e61-a13d-88f9ad937e4f.png)

**Comment by sharmanakul** [comment]
Hi @soome-Rs , unable to replicate the issue. I'm getting the correct cash account while returning on the POS invoice. 

I'm closing the issue for now. Feel free to reopen if it still persists for you.

checked on v13.14.

**Comment by soome-Rs** [comment]
Hi Sharmanakul 

Sorry i trying in  v13.15.2  It's still not Fix it
