### ISSUE TITLE
Delivery Note Status Displays "TO BILL" Even When It is Fully Invoiced - ERPNext: v13.11.1 (HEAD)

### ISSUE THREAD

**Issue by THEOSKaris** [frappe/erpnext#27818]
![image](https://user-images.githubusercontent.com/67414153/136019577-93905935-4a5f-4c2d-915e-888f9832d4a0.png)

**Comment by ankush** [comment]
Most likely due to missing links in row level values. Check each lines' billing status and total billed value.
