### ISSUE TITLE
menu items not visible for users without analytics, employee self service or translator roles

### ISSUE THREAD

**Issue by reubenromandy** [frappe/erpnext#27826]
## I've created many users with various roles. But on the sales invoice screen (and other screens) they did not have the left menu items to attach documents, nor did they have anything in the menu drop down except SEND SMS, they didn't have a print icon and no connections box showed up for them on any screen. 
I had created my  own user as system administrator and given myself all roles just for the heck of it.
After much messing around with roles I found that if I have Translator, Employee Self Service or Analytics checked for any user they get all those UI elements to show up. This has to be a bug since those three roles are not core roles to the system, and having to enable them for an accounts/sales user to be able to print an invoice doesn't seem right.

## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 13.12.0
frappe 13.12.0
```

## Steps to reproduce the issue

1. Make a user
2. don't assign them any of the roles (Employee Self Service, Analytics, Translator)
3. Open a sales invoice using that user. 

### Observed result
Much of the normal UI is missing including the print icon and all items off the menu except SEND SMS
### Expected result
page displays all those things.
### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by dawoodjee** [comment]
Thank you for reporting, this helped me pin-point the cause of the same issue on my site, i.e v14.37.0 (version-14)

**Comment by mark17000** [comment]
This bug definitely shouldn't have been closed. I'm having the same problem.
