### ISSUE TITLE
[V5] Production Order - Material Transfer entry not updating BOM items correctly

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#2782]
Issues observed in demo account of version 5 (staging5).

Steps:

- Created BOM. Listed 3 items as raw-material, each having 1 qty.
- Created Production Order using that BOM.
- When create Material transfer entry against Production Order, one BOM item is not fetched, While for other item, wrong qty is fetched.

Reference: Try creating Material Transfer entry against Production Order No. PRO-00008

**Comment by neilLasrado** [comment]
Will fix it !
