### ISSUE TITLE
Repost Item Valuation fails with pymysql.err.InterfaceError: (0, '')

### ISSUE THREAD

**Issue by rtdany10** [frappe/erpnext#27839]
![image](https://user-images.githubusercontent.com/52111700/136225867-ef6313cf-5f04-4199-b9b5-9ed30b439b30.png)

```
ERPNext: v13.11.1 (HEAD)
Frappe Framework: v13.11.0 (HEAD)
```

Instance on Frappe Cloud.

Not sure if this is related, but Stock Balance shows wrong amount for Balance Value. Could the failed reposting be the culprit?
![photo_2021-10-06_20-13-30](https://user-images.githubusercontent.com/52111700/136226501-2f75d686-c42c-445f-a033-781051eaf3d3.jpg)

**Comment by ankush** [comment]
This doesn't have anything to do with reposting. Before starting a background job we commit the transaction, that commit failed. 

Looks like one-off network error.

Pending reposting will happen in next run (hourly). If such network errors are appearing too frequently then you should report to Frappe Cloud support team.
