### ISSUE TITLE
Error in module 'erpnext.regional.south_africa.setup during initial setup of ERPNext V13

### ISSUE THREAD

**Issue by johnlongland** [frappe/erpnext#27849]
## Description of the issue
Just after fresh V13 install and before any transactions or configuration is done , there is an error in the error_log

## Context information (for bug reports)
Tried various installation methods ( manual and script ) to see if that has an effect but all installation method
yields the same result

**Output of `bench version`**
```
(erpnext 13.12.0
frappe 13.12.0
)
```

## Steps to reproduce the issue

1. Install V13 ERPNext
2. Log in as Administrator and enter all info .. country, currency, company, language etc
3. ERPNext completes its own setting up
4. Without entering any other transactions or configurations, there is an error on the error_log

### Observed result
Error on error_log

### Expected result
No error in the error_log

### Stacktrace / full error message

```
(Traceback (most recent call last):
  File "/home/<ERPNEXT-USER>/frappe-bench/apps/erpnext/erpnext/setup/setup_wizard/operations/taxes_setup.py", line 110, in update_regional_tax_settings
    frappe.get_attr(module_name)(country, company)
  File "/home/<ERPNEXT-USER>/frappe-bench/apps/frappe/frappe/__init__.py", line 1190, in get_attr
    return getattr(get_module(modulename), methodname)
AttributeError: module 'erpnext.regional.south_africa.setup' has no attribute 'update_regional_tax_settings')
```

## Additional information
When I install a fresh V13 server but set the country as India, the error does not occur
Running on Digital Ocean droplet 2 CPU 4G-RAM

OS version / distribution, `ERPNext` install method, etc.
node -v && npm -v && python3 -V && pip3 -V && yarn -v
v12.22.6
6.14.15
Python 3.8.10
pip 21.2.4 from /usr/local/lib/python3.8/dist-packages/pip (python 3.8)
1.22.15

Ubuntu 20.04 LTS
Server version: 10.4.21-MariaDB-

**Comment by franzos** [comment]
We're seeing something similar:

```
erpnext - upstream/version-13
frappe - upstream/version-13
```

This usually happens on quotes, sales orders and the likes.

```
Traceback (most recent call last):
  File "apps/erpnext/erpnext/setup/setup_wizard/operations/taxes_setup.py", line 109, in update_regional_tax_settings
    frappe.get_attr(module_name)(country, company)
  File "apps/frappe/frappe/__init__.py", line 1199, in get_attr
    return getattr(get_module(modulename), methodname)
AttributeError: module 'erpnext.regional.germany.setup' has no attribute 'update_regional_tax_settings'
```

Country is set to Germany.

**EDIT**

- I can confirm that `update_regional_tax_settings` does not exist in module `erpnext.regional.germany.setup`. [Link](https://github.com/frappe/erpnext/blob/version-13/erpnext/regional/germany/setup.py)
- Same issue for South Africa [Link](https://github.com/frappe/erpnext/blob/version-13/erpnext/regional/south_africa/setup.py)

It looks like `taxes_setup.py` only checks whether the path exists:

```python
def update_regional_tax_settings(country, company):
	path = frappe.get_app_path('erpnext', 'regional', frappe.scrub(country))
	if os.path.exists(path.encode("utf-8")): # <--------------
		try:
			module_name = "erpnext.regional.{0}.setup.update_regional_tax_settings".format(frappe.scrub(country))
			frappe.get_attr(module_name)(country, company)
		except Exception as e:
			# Log error and ignore if failed to setup regional tax settings
			frappe.log_error()
			pass
```

[Link](https://github.com/frappe/erpnext/blob/version-13/erpnext/setup/setup_wizard/operations/taxes_setup.py#L106)

**Comment by tjomtek** [comment]
For South Africa ensure that the company "VAT Setting" is added after fresh install
![SAVatSettings](https://user-images.githubusercontent.com/77873407/148169726-37f21506-0c15-44c4-8fa0-d5763c2236a2.png)
