### ISSUE TITLE
Create Sales Invoices from Delivery Note : Missing dashboard link to Delivery note

### ISSUE THREAD

**Issue by FHenry** [frappe/erpnext#27874]
Reopen  #27359 close by merge, but merge was reverted by #23570
So the bug still occurs until a fix is develop

**Comment by sharmanakul** [comment]
![image](https://user-images.githubusercontent.com/88872881/141494308-6223edd2-4d85-46e0-bd39-e0c3253b8174.png)
numbers are not displayed next to the link.

**Comment by FHenry** [comment]
I fix it with a hook on custom app, for one of my integration the use case is more relevant with it.

**Comment by wojosc** [comment]
Hi,

I am not sure if we are all on the same issue here. I have the case, that I created a DN from SO
![grafik](https://user-images.githubusercontent.com/22279621/157233316-3fbf34cc-dee8-4dd5-9d61-ac1989ec2c94.png)

then created SI from DN. On DN I can see the links to SO and SI
![grafik](https://user-images.githubusercontent.com/22279621/157233477-ce009220-8c92-4f09-86fd-881c838cab62.png)

On the Sales invoice there is no backlink to DN though
![grafik](https://user-images.githubusercontent.com/22279621/157233575-124fe33f-7b8d-4691-ad23-bd29fce9c326.png)

Although the link exists on item level on the SI
![grafik](https://user-images.githubusercontent.com/22279621/157233664-1b510196-1caa-4470-8acf-e4025616fe6a.png)

thank you

**Comment by FHenry** [comment]
Yes the link is into line details, but connexion dashboard is a more direct link. Users don't want to click on each lines details (but in version-13, it's more easy to add column into items table)
