### ISSUE TITLE
Timesheet Timer goes to an inconsistent state on clicking "Complete"

### ISSUE THREAD

**Issue by matteoscordino** [frappe/erpnext#27878]
## Description of the issue

In Timesheet Timer, clicking on "Complete" results in:

-  a "No changes in document" popup
- the "Save" button not being shown (it remains "Submit") and 
- the "Start Timer" button not being shown (it stays "Resume Timer").

However, editing the row shows the "Completed" checkbox checked (so the buttons I mentioned should say "Save" instead of "Submit" and "Start Timer" instead of "Resume Timer")

This can be worked around by making any minor change to the row, which will then enable the "Save" button and "Start Timer" button.

It's still pretty dangerous because if you don't notice you can easily leave the document unsaved, with the result that you probably bill the wrong amount of time.

## Context information (for bug reports)

**Output of `bench version`**
```
frappe@39103186755b:~/bench$ bench version
erpnext 13.11.1
frappe 13.11.0
```

## Steps to reproduce the issue

1. Start a Timesheet timer
2. Click on "Complete" to stop it

### Observed result

The UI is not updated, and the fact that the timer has stopped is not saved

### Expected result

The UI is updated, showing "Save" instead of "Submit" and "Start Timer" instead of "Resume Timer".

Ideally the document would be also saved automatically, but that's just my preference.

### Stacktrace / full error message

```
N/A
```

## Additional information

ERPNext running in docker container from image `pipech/erpnext-docker-debian:v13-py3-latest`

```$ docker -v
Docker version 20.10.5+dfsg1, build 55c4c88
```
Host OS: Debian Bullseye

**Comment by sharmanakul** [comment]
validated on v13.14

**Comment by mkreckovic** [comment]
Reproducible on v13.16.1
