### ISSUE TITLE
[V5] Purchase Order - %Received and %Billed is not updated

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#2787]
Please check attached image for the reference. In the item table, Received Qty and Billed Amount is updated correctly in Item row.

![screen shot 2015-02-18 at 8 56 03 pm](https://cloud.githubusercontent.com/assets/910238/6250007/00cecf08-b7b1-11e4-851d-6202c2da25c2.png)

**Comment by rmehta** [comment]
removed the bars :smile:
