### ISSUE TITLE
Regional [GST India]: Move GST Category and Export Type to Address.

### ISSUE THREAD

**Issue by vorasmit** [frappe/erpnext#27880]
**Current Scenario:** 
GST Category and Export type are fields in customer and supplier.

This restricts the customer/supplier to only one GST category. There are cases where customer can have multiple GST Category.
Eg:
In our scenario, multiple customer have one of its office located in SEZ and other office in Non-SEZ zone. They have different GSTIN for this purpose. 

GSTIN for Taxpayer Type: Registered Regular

![image](https://user-images.githubusercontent.com/10496564/136647178-f1d3d1f3-3d11-49ef-ab21-b878e1fd77d9.png)

GSTIN for Taxpayer Type: SEZ

![image](https://user-images.githubusercontent.com/10496564/136647207-d1b64105-3aea-473c-856f-03186a4b5e2c.png)

**Solution:**
Moving these fields to Address would be more logical.
This information, (i.e taxpayer type/ GST Category) is linked to GST Number. When GST Number is part of address, it makes more sense for this to be part of Address.

**Alternatives Tried:**
Create multiple customer. (Not the correct way to handle this)

- Well it is just one customer. They process payments/invoices for this from one centralised office. However, they have factories at multiple locations for strategic reasons.

**The true issue**
We expect to set defaults for customer, about their registration details, so that we do not have to make this corrections for each invoice, that is made, and in turn generate accurate returns.

With this, there are very good chances of errors and incorrect returns.

**Comment by rtdany10** [comment]
@vorasmit Tax Category and GSTIN are already present in Address. Please check the same.

**Comment by vorasmit** [comment]
Hi,

Tax category is different.

I am asking this for GST Category.
![image](https://user-images.githubusercontent.com/10496564/136649290-faae34b7-893c-454d-82a4-a5335ec4699a.png)

![image](https://user-images.githubusercontent.com/10496564/136649323-47555067-a8f7-4c06-b3a9-10b74c52a49e.png)
