### ISSUE TITLE
[V5] When mouse hoover on report column, weird signs appear

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#2789]
In Chrome:

![report weird signs](https://cloud.githubusercontent.com/assets/910238/6262575/338ea078-b82c-11e4-8478-b3fb487660ca.gif)

In Safari

![report weird signs safari](https://cloud.githubusercontent.com/assets/910238/6262576/3a35b0f6-b82c-11e4-9b07-f9c92c31c04d.gif)

**Comment by rmehta** [comment]
fixed
