### ISSUE TITLE
[V5] Missing History and Bookmark buttons in desktop menu

### ISSUE THREAD

**Issue by donblackowiak** [frappe/erpnext#2790]
In V4 the History and Bookmark pull down menus are extremely useful.  I just upgraded a test site to V5 and I do not see them anywhere.  Nor do I see a way to add them back to the menu.

**Comment by anandpdoshi** [comment]
Bookmarks have been moved to "Stars" that are per doctype.
When you click on the awesomebar search, it shows recent document's list
