### ISSUE TITLE
Translation files are not up to date

### ISSUE THREAD

**Issue by leventesen** [frappe/erpnext#27908]
Translation files ("lang.csv") are not up to date.

Latest commit is 11 months ago, but there are approved translations in the portal since 11 months ago.

Isn't that strange?

Probably the PR bot isn't working once a week.

**Comment by sliwkawsieci** [comment]
I was thinking about it too latly. But anyway if you will update that csv manually it still doesn't show all translations ... It is a big mess with translations ...

**Comment by niklaskorz** [comment]
There are lots of strings that are translated on https://translate.erpnext.com but are not translated in the software. For example the search bar:

<img width="499" alt="grafik" src="https://user-images.githubusercontent.com/590517/149634475-a20f1f08-14ac-451f-a1c6-4432203ebade.png">

As you can see on https://translate.erpnext.com/app/translated-message/882da8c8bf, this was translated and verified 10 months ago but somehow never made it into this repository.

**Comment by ankush** [comment]
WIP: https://github.com/frappe/translator/pull/212
