### ISSUE TITLE
"Selling" doctypes wrong linked to "Retail" workspace on "List view" v.13.12.0

### ISSUE THREAD

**Issue by franciscobuendiao** [frappe/erpnext#27911]
## Description of the issue
Doctypes like "Customer" or "Sales Order" from "Selling" module are linked to "Retail" workspace at "List view". 

When click on app (workspace) name, redirects to "Retail" that doesn't have any of these docs as Shortcuts or Master.

## Context information (for bug reports)
"Active Domain" set to "Retail".

**Output of `bench version`**
```
ERPNext: v13.12.1 (version-13)
Frappe Framework: v13.12.1 (version-13)
```

## Steps to reproduce the issue

1. "Customer" list view
2. "Quotation" list view
2. "Sales Order" list view
3. "Sales Partner" list view

Etcetera...

### Observed result
![Captura de Pantalla 2021-10-11 a la(s) 12 15 44](https://user-images.githubusercontent.com/25084259/136829752-d6a6b0ad-3477-4818-8082-89988f549d90.png)

![Captura de Pantalla 2021-10-11 a la(s) 12 16 03](https://user-images.githubusercontent.com/25084259/136829766-13bbfa27-881d-4fbe-946a-a8ae77bd5ec8.png)

![Captura de Pantalla 2021-10-11 a la(s) 12 16 15](https://user-images.githubusercontent.com/25084259/136829789-6de83d92-bad9-4f9a-b40f-f3077bb13568.png)

![Captura de Pantalla 2021-10-11 a la(s) 12 16 32](https://user-images.githubusercontent.com/25084259/136829809-0447d540-9b84-48a8-aee8-a18546823b64.png)

**Comment by andriusr** [comment]
I had the same issue on 14.31.0 (frappe). The system was upgraded from v12, probably there were some issues with upgrade. I have managed to get back Selling after rebuilding Sellling workspace, and cleaning web server caches using bench commands:
bench --site site1.local clear-cache
bench --site site1.local clear-website-cache
sudo systemctl restart supervisor
