### ISSUE TITLE
New BOM Creation - item filter not Working

### ISSUE THREAD

**Issue by casakthiveln** [frappe/erpnext#27936]
## Description of the issue
While creating new BOM, item filter not working for item field.
## Context information (for bug reports)

**Output of `bench version`**
```
ERPNext: v13.12.1 (version-13)

Frappe Framework: v13.12.1 (version-13)
```

## Steps to reproduce the issue

1.
2.
3.

### Observed result
![bom](https://user-images.githubusercontent.com/63579207/137092363-88fb1f5f-d886-4a4e-9fa7-a399e4d4c48b.gif)

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by ankush** [comment]
This is fixed, next release on ~20th.

https://github.com/frappe/erpnext/pull/27890
