### ISSUE TITLE
Pricing Rule errors in V13

### ISSUE THREAD

**Issue by iasb1990** [frappe/erpnext#27933]
Hello,

I'm trying to use pricing rule but it doesn't work to me.

1. If I try to use pricing rule to apply a discount/charge in other item, it always apply the charge/discount, even when the 'filter' item/item group it isn't. I found this post about what it seems to be same error in V12 https://github.com/frappe/erpnext/issues/22154
There isn't another pricing rule which could be doing that. 

![Captura de Pantalla 2021-10-13 a la(s) 15 57 42](https://user-images.githubusercontent.com/66756148/137196325-8a2b6ba1-feee-44ff-a94e-91401754fa57.png)
![Captura de Pantalla 2021-10-13 a la(s) 15 58 03](https://user-images.githubusercontent.com/66756148/137196334-d61b258c-d4ae-4ddb-bb31-40bcb85421a7.png)
![Captura de Pantalla 2021-10-13 a la(s) 15 58 40](https://user-images.githubusercontent.com/66756148/137196340-a589cd4b-61f1-4ccd-89b7-bb53ab3797d0.png)

2. It doesn't work in transactions. The pricing rule doesn't apply. Again, I found this post about what it seems to be a similar error in V12 https://github.com/frappe/erpnext/issues/22159
3. In case of pricing rule apply on item group (price, not quantity) and party type customer category, it does work for manual sales invoice, but it doesn't in case of automatic subscription sales invoices. I don't understand why in one case it does work and in other it doesn't. 

Is anyone having same issues? I'm pretty sure that it isn't working appropriately.

ERPNext V13.11
Frappe 13.11

https://github.com/frappe/erpnext/issues/27933 

Thanks in advance!

**Comment by federicocalvo** [comment]
same here!
