### ISSUE TITLE
Ablity to redirect "Report an Issue" and User Forum in the HELP Menu

### ISSUE THREAD

**Issue by tjomtek** [frappe/erpnext#27949]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when end users attempt to log something on git and or try the user forum, and their instance is customized for their business[...]

**Describe the solution you'd like**
The Administrator should be able to redirect the "report an issue" to the local support team and also be able to disable the user forum link.
**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here
![help](https://user-images.githubusercontent.com/77873407/137138591-f4ca54fc-ab5b-4eab-ab3f-1565f0590421.png)
.

**Comment by pstuhlmueller** [comment]
@tjomtek , just configure within "Navbar Settings" the dropdowns and its route as required.
