### ISSUE TITLE
Make POS intro screen nicer

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#2795]
Show a nice POS icon?

![screen shot 2015-02-19 at 5 53 33 pm](https://cloud.githubusercontent.com/assets/140076/6266485/51069e56-b860-11e4-808c-906c8c8ab862.png)

**Comment by pifiu** [comment]
can you elaborate? the POS could use some tweaking and slightly improved interface.

**Comment by pifiu** [comment]
are you able to explain what was changed in #2795?
