### ISSUE TITLE
[V5] Total Count for a Document - Missing in V5

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#2796]
In V4, on the module page, total count of records are shown for each document. This is missing in V5.

In version 4:
![screen shot 2015-02-19 at 5 57 05 pm](https://cloud.githubusercontent.com/assets/910238/6266578/66869316-b861-11e4-9a08-488c64e43e89.png)

In version 5:
![screen shot 2015-02-19 at 5 57 26 pm](https://cloud.githubusercontent.com/assets/910238/6266582/6e0a9290-b861-11e4-81fa-4f0d4ba4bfd1.png)

**Comment by anandpdoshi** [comment]
This is removed as per new design.
