### ISSUE TITLE
Add Print Hide in Salary Component

### ISSUE THREAD

**Issue by chrisdent** [frappe/erpnext#27974]
We have a provisioning Salary component that is a compensation when the employee leaves the company. This should not be shown in the monthly printed Salary slip.

We can do this with Jinja but this feature would be nice for everyone.

**Comment by dj12djdjs** [comment]
@chrisdent this feature already exists using the "Do Not Include in Total" checkbox.
_Do Not Include in Total: Selecting this checkbox ensures that the Salary Component is not included in the Total Salary. It is used to define the component which is part of the CTC but not payable (e.g. Usage of Company Cars)._
https://docs.erpnext.com/docs/v13/user/manual/en/human-resources/salary-component#22-additional-properties

**Comment by chrisdent** [comment]
@dj12djdjs thanks!

Although it helps checking the "Do Not Include in Total" the component still gets printed on the Salary Slip. It would be nice to choose which salary components are printed in the salary slip.

**Comment by dj12djdjs** [comment]
> @dj12djdjs thanks!
> 
> Although it helps checking the "Do Not Include in Total" the component still gets printed on the Salary Slip. It would be nice to choose which salary components are printed in the salary slip.

You should be able to customize what components will show in the salary slip using a custom print format.

If the UI doesn't provide the tools, you can write your own markup for the salary slip, choosing what components you want to be printed.
