### ISSUE TITLE
[V5] milestone:"ERPNext 5.0" Add/Update User Errors

### ISSUE THREAD

**Issue by donblackowiak** [frappe/erpnext#2799]
I am running the latest updates of V5 on a system that I updated from V4 starting with a backup of our https://apumano.frappecloud.com account.  

The user module is now working. Under Setup > User I see the list of users.  But when I click a user, the fields are mostly blank including email and name. I can complete those fields and click save without seeing any errors.  However nothing is saved.

Additionally, I see no link to set the roles for a user.

I was unable to verify this by checking http://staging5.erpnext.com as the setup module is disabled.

![screen shot 2015-02-19 at 8 30 52 pm](https://cloud.githubusercontent.com/assets/4634803/6280127/c69185b2-b876-11e4-9de4-b02e6d258515.png)
![screen shot 2015-02-19 at 8 30 15 pm](https://cloud.githubusercontent.com/assets/4634803/6280128/c69576b8-b876-11e4-9271-896a2c052440.png)

**Comment by rmehta** [comment]
fixed.
