### ISSUE TITLE
Leave encashment from date issue in query in version ERPNext version 12

### ISSUE THREAD

**Issue by irtzamazhar** [frappe/erpnext#28020]
![image](https://user-images.githubusercontent.com/24386185/138061553-ce1daef5-5576-4f49-9a32-4549cfbc3a92.png)

In file expnext/erpnext/hr/doctype/leave_encashment/leave_encashment.py on line number 82 leave_allocation query is not correct and not get the from date. While on line 70 from date is using and due that from date is not working.

**Comment by shoaibrehmat88** [comment]
In your file replace following code with 
`	def get_leave_allocation(self):
		leave_allocation = frappe.db.sql("""select name, to_date, total_leaves_allocated, carry_forwarded_leaves_count from `tabLeave Allocation` where '{0}'`

this one
`	def get_leave_allocation(self):
		leave_allocation = frappe.db.sql("""select name, from_date, to_date, total_leaves_allocated, carry_forwarded_leaves_count from `tabLeave Allocation` where '{0}'`
