### ISSUE TITLE
Condition Code on Datetime field type

### ISSUE THREAD

**Issue by Mohd200** [frappe/erpnext#28073]
Good day everyone…

I’m trying to create a new Notification on Employee Checkin Doctype.
The purpose of the notifications is it would send alerts whenever the “Time” field is registering beyond a certain time (E.g: Time = +08:00 a.m.) no matter the date.
![3](https://user-images.githubusercontent.com/32062135/138585046-fc1aa1dc-b8e0-4097-92d2-ac44ecff0dce.PNG)

In Notification, the Send Alert On option is “Custom”.
![1](https://user-images.githubusercontent.com/32062135/138584961-88f4df20-964d-414d-8fa7-188e219fe461.PNG)

However, I’m facing a problem with the condition code, an error message appears saying: (The Condition ‘doc.time > dd/mm/yyyy 08:00:00’ is invalid)
![2](https://user-images.githubusercontent.com/32062135/138585049-ef3050f1-a548-4c61-81ba-d98990c3ea90.PNG)

Can anyone please provide some assistance?

You may find the issue on ERPNext Forum:
https://discuss.erpnext.com/t/condition-code-on-datetime-field-type/81642

Thank you :D

**Comment by ankush** [comment]
That's not valid python condition. Use `frappe.utils.get_time`.
