### ISSUE TITLE
Incremental Leave Policy

### ISSUE THREAD

**Issue by mastewalm** [frappe/erpnext#28078]
In my organization we have an incremental leave policy which will increment every year by one or two based on employee grade. For Example, if the starting leave allocation is 14 days' for an employee, next year, based on his/her grade it will increment 1 or 2 days and next year's allocation becomes 15 or 16. But there is also a limit to total allocation per year. 45 or 50 days is the final allocation per year based on the grade level. Is there any option to do that on ERPNext?

**Comment by conncampbell** [comment]
For such a specific use case, I'd track this manually in a spreadsheet then manually allocate leave to each employee every year.

**Comment by conncampbell** [comment]
Perhaps a better feature request would be for a custom server script for leave allocation policies.  That way you could customize your own allocation with a python script.

**Comment by mastewalm** [comment]
Thank you for your response

**Comment by sharmanakul** [comment]
@mastewalm would you like to define a user story for your use case? We will see where it can fit in our roadmap.

**Comment by mastewalm** [comment]
Yes, please!
