### ISSUE TITLE
Retail POS - Hide Images

### ISSUE THREAD

**Issue by tjomtek** [frappe/erpnext#28079]
![HideImagePOS](https://user-images.githubusercontent.com/77873407/138674047-bc909649-9808-463a-9d4e-f7070ebebc95.png)

## Description of the issue
Checked "Hide images" under Configuration tab
## Context information (for bug reports)

**Output of `bench version`**
``13.12.1
(paste here)
```

## Steps to reproduce the issue

1.Followed steps to create POS Profile
2.Logged in as pos user having 'hide image' set as true.
3.
![HideImagePOS](https://user-images.githubusercontent.com/77873407/138673900-ad7d81ab-ad6b-4b85-b39d-d364346d1e57.png)


### Observed result
The Image dissapeared, however the border still shows, looks like a broken image
### Expected result
If 'Hide Image' is set to True then items should show as 'list view'
### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.
In CLoud Self-Install v13.12.1

**Comment by harshit-30** [comment]
@nemesis189 can you validate this issue?

**Comment by nemesis189** [comment]
@tjomtek The image you attached above is the expected behaviour, if 'Hide Images' is checked then the first letters of the item name is displayed instead of the image. Please attach an image of the problematic part, maybe mark it clearly to avoid confusions.
