### ISSUE TITLE
Dates in Company

### ISSUE THREAD

**Issue by barredterra** [frappe/erpnext#28089]
In the **Company** DocType we have three date fields:
 
- Date of Establishment,
- Date of Incorporation and
- Date of Commencement

Do we really need all three of them? What's the difference and who needs this information?

**Comment by sharmanakul** [comment]
In the context of India:
Incorporation Date is the date when a company gets itself registered with the Registrar of Companies (ROC) and a certificate of incorporation is issued by ROC.
The date of commencement of business is the date on which the first transaction for business is done.
All rules in force are applicable from the date of incorporation as the legal status of the company has been registered on the date of registration/incorporation.
Both may be required by the auditors.

I'm not really sure about the 'Date of Establishment'.
