### ISSUE TITLE
POS invoice format not showing print dialog box - alternatives to POS printing?

### ISSUE THREAD

**Issue by pifiu** [frappe/erpnext#2808]
See this thread for details:

https://discuss.frappe.io/t/thermal-printing-for-pos-receipts/4840/3

"During the selection between Standard and POS Invoice format, the Standard option launches the printing dialog and you're able to select the printer and print without a glitch, but for the POS Invoice format it goes right into HTML without a printing option and the unclear or no receipt printing starts there for POS receipts"

Easy fix.

How about implementing jzebra for POS printing or just overall printing? It would be nice to print to thermal printers packing slips, invoices, etc.

**Comment by rmehta** [comment]
Never tried it. Do you have any experience with this?

**Comment by pifiu** [comment]
not implementing it, but this is the site: https://code.google.com/p/jzebra/ 


How about the issue witht he POS view? Can that be addressed?

**Comment by pifiu** [comment]
is it possible to address some of the print issues before v5?

For example when printing a POS invoice in chrome or opera VS internet explorer, there seem to be minor issues that would only take slight tweaking to get it to work correctly.

Issues right now:

In chrome, you need to set margins to "no margins" for it to print correctly but then the edges are cut off. On IE this is not required and it prints fine. If you set the correct margins in chrome it works fine, but on a POS transaction who is really going to take the time to do that.

In chrome and opera, everything looks bold. It's marginally visible but the difference is there.

Lastly the POS view does not bring up the print dialog as originally stated in the initial post, you need to CTRL+P to get the dialogue to show up.

**Comment by rmehta** [comment]
Can you fix those and send a pull-request?

**Comment by rydersaint** [comment]
I don't to throw a spanner in the works however POS printers are very specialize. A lot of them function in there own style. Especially when is come to Asians languages would it not be better to stick with PDF page size templates and trigger the print dialog ?

**Comment by pifiu** [comment]
That is not true. You can easily send print text and they should all render fine. The ones that do not are the ones that are not standard and those should be few and far between. For example epson tm-t88xx is just about as standard as it could possibly get. Just about every modern retail store that prints thermal receipt paper uses one of these.

**Comment by rydersaint** [comment]
If you say so that is fine.
I am not a huge windows user.
With most of Apples revenue being mostly iPhone (**Support for AirPrint). 
I think it is better to let the operating systems look after the printing as it must come from all types of operating systems and well as all types of printers. 
The only standard I see here is the print dialog.
This is where I think erpnext should support too.
As simple really is best.
Of course this is just my opinion.

Kind regards

**Comment by system19** [comment]
I agree that the OS should handle the printer. The epson tm-t88xx is very well supported in most OS. It sounds like the ERPNext POS Doctype print format needs to be simplified. Most POS printers require a very simple text only data feed. Maybe a "Print" button with javascript could strip out the excess html on the POS Doctype page? If not then maybe send print data to another temp and very basic Doctype page while its printing. I have seen this in other POS applications. You just go to a all white page with the receipt being printed shown in the desired format. The user then clicks a button to return to the POS screen when the receipt has printed?

**Comment by mhbu50** [comment]
+1

**Comment by vladucoju** [comment]
+1
