### ISSUE TITLE
Allow Items Not Batched and/or Not Serialized to be changed to Batched and/or Serialized after stock transaction

### ISSUE THREAD

**Issue by sahil48** [frappe/erpnext#28086]
**Is your feature request related to a problem? Please describe.**
In many cases for our manufacturing, it is difficult to determine if a part should be batched or serialized ahead of time. Sometimes, after hearing complaints regarding a component, it becomes necessary to start tracking the product, despite it being used in previous transactions.

**Describe the solution you'd like**
We would like to be able to toggle batching or serialization on for an item after transactions have taken place. It is not necessary to revert items that have been batched or serialized to unbatched or unserialized.

**Describe alternatives you've considered**
We had tried to create a new item that is batched and replace the existing item that is unbatched. This is cumbersome, and also, links to existing BOMs for the unbatched item become problematic because we want to use the same item code. Additionally, the history for batched and unbatched version of the item cannot be viewed at one time.

**Comment by ankush** [comment]
Because of stock ledger implementation this isn't really possible right now without huge changes.
