### ISSUE TITLE
Opening Entry Journal sets foreign currency accounts as Company Currency

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#28113]
Hi,

When an 'Opening Entry' type Journal Entry is created, it automatically populates the accounts table with all ledgers but doesn't take the account currency into consideration. All ledgers (including those in Foreign Currency) are set as company currency

Pls help fix

Thanks

**Comment by Olawale1** [comment]
Hi,

I'm not sure this is fixed yet

Thanks

**Comment by Olawale1** [comment]
Still awaiting fix

**Comment by deepeshgarg007** [comment]
@Olawale1 This automatic account fetching logic has been remove as it was causing more problems than it was solving, this issue is not applicable anymore
