### ISSUE TITLE
[V5] Stock Reconciliation - Value in the Difference Account not validated

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#2815]
In the version 4, When updating stock balance for an item for the first item, value in the Difference Account field is validated. It allows only an account from the Balance Sheet (like temporary account), and not from P&L.

Attached is the Stock Reconciliation in V5. For items, this is the first stock reconciliation, hence it should not have allowed Stock Adjustment account as a Difference Account. And should have shown validation for the Balance Sheet account.

![screen shot 2015-02-23 at 11 40 57 am](https://cloud.githubusercontent.com/assets/910238/6323493/4ca454c2-bb51-11e4-8f7b-77f98b4715aa.png)

**Comment by rmehta** [comment]
Checked - this validation works, can you try again?

**Comment by umairsy** [comment]
tested. works fine.

On Wed, Mar 4, 2015 at 12:09 PM, Rushabh Mehta <notifications@github.com>
wrote:

> Checked - this validation works, can you try again?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/frappe/erpnext/issues/2815#issuecomment-77104772>.
>



-- 
Thanks and Regards,
Umair Sayyed
www.erpnext.com
