### ISSUE TITLE
[V5] Stock Entry - Target Warehouse Error

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#2816]
Steps:

1. Stock Entry >> New
2. Purpose = Subcontract
3. Select BOM of sub-contracting Item
4.  Entered Manufacturing Qty
5. Clicked on "Get Items".
6. Update "Target Warehouse" in the parent field, above item table. On selection of Target Warehouse, same was correctly updated in all items as well.
7. Clicked on "Save". Attached is the error message which says Target Warehouse is required in item.

![screen shot 2015-02-23 at 11 51 37 am](https://cloud.githubusercontent.com/assets/910238/6323581/d453d0e0-bb52-11e4-97a6-4295bd4b182c.png)

**Comment by rmehta** [comment]
can't replicate
