### ISSUE TITLE
Multiple Subscription Invoices being raised every hour

### ISSUE THREAD

**Issue by nextchamp-saqib** [frappe/erpnext#28179]
Introduced with https://github.com/frappe/erpnext/pull/27783

Problem:
- Create a subscription and enable _Generate Invoice At Beginning Of Period_ and _Generate New Invoices Past Due Date_
- Now click on _Fetch Subscription Updates_ and notice the _Current Invoice End Date_
- Clicking on _Fetch Subscription Updates_ creates invoices but doesn't update the _Current Invoice End Date_

<details>
<summary>GIF</summary>
<br>
<img src="https://user-images.githubusercontent.com/25369014/139640252-06c882b2-daed-423b-a680-d60581372281.gif">
</details>

**Comment by nextchamp-saqib** [comment]
@hrwX @sagarvora  Please validate/check

**Comment by hrwX** [comment]
@nextchamp-saqib Can you check the PR now, was an issue with the way `is_current_invoice_generated` was checking the date for Active subscriptions.
