### ISSUE TITLE
[V5] Purchase Receipt - Column numbering starting with 0 for Raw Materials Supplied table

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#2818]
Steps:

1. Made Purchase Order for sub-contracting.
2. Converted Purchase Order into Purchase Receipt.
3. Updated Supplier Warehouse.
4. Saved Purchase Receipt. Items were correctly updated in the Raw Material Supplier table.

Check attached screenshot.

![screen shot 2015-02-23 at 12 03 47 pm](https://cloud.githubusercontent.com/assets/910238/6323674/4892e314-bb54-11e4-9b82-0f5c1db72ccb.png)

**Comment by rmehta** [comment]
fixed
