### ISSUE TITLE
Sales Order - Duplications are not allowed bug

### ISSUE THREAD

**Issue by michalls01** [frappe/erpnext#28188]
We need to enter Service Items (Non stock) to Quotations, Sales Orders and Sales Invoices multiple times. We are also using "Additional Notes" for a short description.

However, when creating a Sales Order from Quotation (or in Sales Order DocType alone), a **"Duplicate Item Exists  - Duplications are not allowed" error message pops up and the Quotation is not stored.** 

**In "Sales Setting", this is checked - "Allow Item to be Added Multiple Times in a Transaction"**

The behaviour is correct in Quotations and Sales Invoice, there you can add the same Items multiple times.

It seems there is a relations to this issue https://github.com/frappe/erpnext/issues/7210#issue-195453802 

ERPNext: v13.13.0 (HEAD)
Frappe Framework: v13.13.0 (HEAD)

**Comment by sharmanakul** [comment]
@michalls01 I tried to replicate the issue on my v13.14.0 (HEAD). 
I was able to submit quotations and sales orders even with the service items entered multiple times in the table.
