### ISSUE TITLE
[V5] Material Transfer Entry against Production Order - GL Entry not correct

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#2819]
GL Entry made against Material Transfer entry didn't consider the valuation of the Serialized Item. GL entry was only made for the other two non-serialised items.

![screen shot 2015-02-23 at 12 34 12 pm](https://cloud.githubusercontent.com/assets/910238/6323996/e1f6c88c-bb58-11e4-9f0a-4002d5115061.png)

**Comment by rmehta** [comment]
fixed.
