### ISSUE TITLE
item not transfered from warranty claim to maintenance visit

### ISSUE THREAD

**Issue by wojosc** [frappe/erpnext#28209]
Hi Team,

when filling a warranty claim with serialnumber the data is fetched as expected
![grafik](https://user-images.githubusercontent.com/22279621/139912584-9c60d9da-9f89-49f5-a12f-b9284cd17205.png)

then, when creating a Maintenance Visit from Warranty Claim via the button...
![grafik](https://user-images.githubusercontent.com/22279621/139912693-a0fec14b-f0c4-4dad-b718-f1023899948b.png)

The Item Table in Maintenance Visit is not filled/transfered
![grafik](https://user-images.githubusercontent.com/22279621/139912790-c7ab7d7e-d192-4ed6-810a-ee0823b0d0f1.png)

When using "Get items from"..
![grafik](https://user-images.githubusercontent.com/22279621/139912889-c7dc6e73-55aa-4136-bf86-fcf2c90a53cd.png)

I can fetch the Items from the Warranty Claim
![grafik](https://user-images.githubusercontent.com/22279621/139912937-381b0fba-92cb-40e0-b955-0cb2ad04023b.png)

And the Items will be filled
![grafik](https://user-images.githubusercontent.com/22279621/139913006-b709d38b-53de-477f-823b-3b778ea09068.png)

Appendix:
1. There is no Backlink to Warranty Claim 👎 
2. in the Item table the "work done" field is mandetory which forces me "to do work" befor beeing able to save :/ 
![grafik](https://user-images.githubusercontent.com/22279621/139913342-03dce928-ec53-4fb4-b43d-0177e5a500cc.png)

**Comment by sharmanakul** [comment]
Create a link such that the item information are fetched in the table from the warranty claim.
Bring the field 'work done' in the list view in the child table 'Purposes'.

**Comment by noahjacob** [comment]
@sharmanakul It's working fine when I checked.
![maintenance_map](https://user-images.githubusercontent.com/43572428/150917956-92b34ce5-a0ae-40af-8307-787122cc31e2.gif)

**Comment by yadavyk** [comment]
@wojosc ,this seems to be fixed now. Checked on V13.19.0. Can you confirm ?
