### ISSUE TITLE
[V5] Manufacturing Entry - Valuation of Raw-Material Item not added in the valuation of Manufacturing Item

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#2820]
Steps:

1. Created Production Entry.
2. Created Material Transfer Entry against it.
3. Create Time Log against Operation.
4. Creating partial Manufacturing entry against Production Order.

In the Manufacturing entry, for determination of valuation of FG item, it only considered actual Operations Cost, and didn't add value of raw-material items into valuation of FG item.

![screen shot 2015-02-23 at 12 53 58 pm](https://cloud.githubusercontent.com/assets/910238/6324117/49ef2554-bb5b-11e4-89ca-932f3c1a01bf.png)

**Comment by rmehta** [comment]
fixed.
