### ISSUE TITLE
Salary Structure : Salary Structure Salary Structure not found

### ISSUE THREAD

**Issue by nnitinp** [frappe/erpnext#28201]
Salary Structure : Salary Structure Salary Structure not found
The resource you are looking for is not available 
I want to delete this Salary Structure

_Originally posted by @nnitinp in https://github.com/frappe/erpnext/issues/28200#issuecomment-957502616_

**Comment by haithamsha** [comment]
This a dynamic text you can edit it from translation-tool.

**Comment by sharmanakul** [comment]
@nnitinp please try to provide steps and details when posting an issue.
