### ISSUE TITLE
UAE VAT 201 Report is showing wrong currency

### ISSUE THREAD

**Issue by nidhipurohit11** [frappe/erpnext#28212]
## Description of the issue ##
UAE VAT 201 Report >> Selected a company with currency as AED, but this report is showing data with rupee symbol. 

## Steps to reproduce the issue ##

1. Created a company (Currency AED, Country United Arab Emirates), and a customer >> added UAE address for both.
2. In UAE VAT Settings >> Add VAT account heads and save.
3. Create a sales invoice, select the created company and customer >> select 2 items, and set a VAT tax template 
4. Now go to UAE VAT 201 Report, select the same country, the data is displayed with rupee symbol. 

### Observed result ###
UAE VAT 201 Report >> Selected a company with currency as AED, but this report is showing data with rupee symbol. 

![Screenshot 2021-11-02 at 10 44 15 PM](https://user-images.githubusercontent.com/82337328/139919136-934f2d8a-5ac9-4d2d-a68b-038d6912a1b3.png)

### Expected result ###
UAE VAT 201 Report should show the correct currency symbol (of the company). 

## Additional information ##
Test Site

**Comment by support-gennextsystems** [comment]
what is your default currency?

UAE vat fetches from `frappe.format(amount, 'Currency')` which is fetched from Global default currency.

**Comment by kunhimohamed** [comment]
what is your default currency?

UAE vat fetches from `frappe.format(amount, 'Currency')` which is fetched from Global default currency.
