### ISSUE TITLE
[V5] In Production Order - field Material Transferred for Qty should not be copied

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#2821]
Steps:

1. Opened new Production Order. It was already completed.
2. Menu >> Duplicate >> 
3. New Production Order form also copied value from "Material Transferred for Qty".

This field should not be copied, and should always be updated based on actual transfer entry made against Production Order.

**Comment by neilLasrado** [comment]
FIxed

**Comment by rmehta** [comment]
Ideally production order should not be copied. fixed
