### ISSUE TITLE
Asset Depreciation Refactor

### ISSUE THREAD

**Issue by harshit-30** [frappe/erpnext#28231]
### Depreciation Entry Posting Failure

When the posting of one Depreciation Entry fails:

1.  The posting of all subsequent Entries gets halted.
2.  There's no way to find out which Asset caused this.

To prevent this from happening,

1.  Submit Depreciation Entries in a try-catch block.
2.  If Depreciation Entry posting fails, update the User and specify the name of the Asset responsible for it.

### Allow Monthly Depreciation

This is redundant, since the user could just set Frequency of Depreciation to one, to ensure that the Asset gets depreciated monthly. Plus, the Depreciation Schedule code would be much simpler without it.

1.  Remove the toggle and all associated code.
2.  Write patch- For all Assets with Allow Monthly Depreciation enabled, set Frequency of Depreciation to one and change Number of Depreciations to (Frequency of Depreciation x Number of Depreciations).

### Categorise Asset code better

Most of the code pertaining to depreciation is in asset.py, but a lot of the code in depreciation.py doesn't have much to do with depreciation.

1.  Move all depreciation-related code to depreciation.py
2.  Move everything else to asset.py

### Improve UX

There's wayy too much room for improvement here, the design isn't intuitive at all. It's pretty hard to make sense of the Asset form without reading the docs first, especially the depreciation part.

1.  Replace Frequency of Depreciation with 'How Often Should This Asset Be Depreciated?'. This should be a Select field with the following options: Monthly, Quarterly, Half-Yearly, Yearly(or should it just be Every Month, Every Two Months, Every Three Months...Every Eleven Months, Every Year?).
2.  Add new field- How Long Will This Asset Continue To Depreciate?/When Should This Asset Stop Depreciating?(find better names). Enable list view.
3.  Make Number of Depreciations read-only and calculate its value based on the two aforementioned fields and disable list view/make it hidden.

Note: This will probably require making major changes to Asset Repair's code as well.

### prepare_depreciation_schedule() code cleanup

This is a bit of a mess right now and all these changes will probably make it worse.

1.  Cleanup code.
2.  Run tests after each major change and then rewrite them once I'm done.

**Comment by GangaManoj** [comment]
Completed (in the Assets app).
