### ISSUE TITLE
Improve Asset auto-creation (WIP)

### ISSUE THREAD

**Issue by harshit-30** [frappe/erpnext#28232]
![](/files/dyaGryu.png)

When creating a Fixed Asset Item, if _[Auto Create Assets on Purchase](Auto Create Assets on Purchase)_ is enabled, the Asset docs are created automatically on submitting a Purchase Receipt for it. The number of Assets docs created = quantity specified for the Fixed Asset Item in the Items table of the PR, since each of the Assets created are distinct entities which follow its own Depreciation Schedule and could be sold on its own.

### **Problems:**

1.  There's no indication of this anywhere, so people are often surprised when they find a large number of new Assets when they've only submitted a single PR.
2.  Even though only one Asset can be created automatically from a PR where the quantity of the Fixed Asset Item is one, any number of Assets can be created manually from this PR later, which isn't consistent with the idea of creating distinct Assets for each Fixed Asset Item being purchased.
3.  The Asset docs thus created are all in the Draft state and they'd have to be manually submitted one by one, which could be tedious if there are a large number of such docs.
4.  A lot of people don't seem to be aware of the existence of the CWIP accounting toggle under Asset Category, but they're surprised when they see/don't see the CWIP accounting entries.

### **Potential Solutions:**

1.  Display appropriate warnings.
    1.  If _Auto Create Assets on Purchase_ is enabled: On saving the PR, display warning stating that Number of Assets created = Quantity of Item, and inform the user that this could be disabled by unchecking _Auto Create Assets on Purchase._
    2.  If _Auto Create Assets on Purchase_ is disabled: On saving the PR, display warning stating that Assets need to be created manually since _Auto Create Assets on Purchase_ is disabled, and that they could be created automatically by enabling it.
2.  Introduce validation on Asset creation: Do not let the user create more Assets than the number specified in the PR.
3.  If _Auto Create Assets on Purchase_ is enabled, introduce a checkbox in the Warehouse and Reference section(maybe create a new section?) of the Items table for PR, to check if it's a Depreciable Asset, and also an Available For Use Date field. Then introduce an additional checkbox, either after the main _Auto Create Assets on Purchase_ checkbox in Item or in this section of the Items table in PR, asking if the auto-created Asset docs should be submitted or left in the Draft state. If this is enabled, then make all those fields mandatory. The remaining fields(for the Depreciation Schedule) should be fetched from the Asset Category doc, so also display an appropriate message if those are missing, if it's a Depreciable Asset.
4.  Display message on saving:
    1.  If CWIP is enabled for that Asset Category, display message stating that CWIP accounting entries will be made on purchase of the Asset, along with instructions on how to prevent this.
    2.  If CWIP is not enabled for that Asset Category, display message stating that CWIP accounting entries will not be made on purchase of the Asset, along with instructions on how to enable it, if they wish to create such entries.

![](/files/KGOi4bN.png)

_Suggestion(check feasibility):_

Some of the users don't seem to be too happy with how multiple Asset docs are created for each PR, if qty > 1. Perhaps we could introduce a Quantity field in the Asset doc, which would correspond to the qty field in the PR? And decrement this number when any Assets of this type get sold? Of course, this would only work for non-depreciable Assets(the Quantity field could be hidden for depreciable Assets).

**Comment by muchai** [comment]
Great write-up. In addition to these improvements. If you attach an asset to an asset category, and it so happens there're no accounts set for the asset category, user is unable to submit the purchase invoice related to that asset. There's always an error message, but it never really describes the problem. Only way is to use debug to locate the source of the error during purchase invoice submission, something most users aren't versed with.

**Comment by GangaManoj** [comment]
@muchai hi, thanks for bringing that to our attention. I'll create a fix for that asap.

**Comment by GangaManoj** [comment]
Closing this as we've changed the creation flow entirely.
