### ISSUE TITLE
Subscription with "Generate Invoice At Beginning Of Period" creates new sales invoice on every run

### ISSUE THREAD

**Issue by jacotec** [frappe/erpnext#28236]
## Description of the issue

Any kind of subscription (yearly, monthly) which has the flag "Generate Invoice At Beginning Of Period" set (for paying in advance) creates a new invoice automatically every run and on every click at "Fetch Subscription Updates".

## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 13.13.0
frappe 13.13.0
german_accounting 0.0.1
```

## Steps to reproduce the issue

1. Create a new monthly or yearly subscription, assign it to a customer 
2. Have "Generate Invoice At Beginning Of Period" and "Submit Invoice Automatically" checked
![image](https://user-images.githubusercontent.com/3321655/140059848-b50c9905-6464-466e-a1b4-a2ae6f0b198f.png)

3. Save the subscription to have it active.
4. Click three times on "Fetch Subscription Updates"
5. You'll see three sales invoices created by the subscription (one per click)
![image](https://user-images.githubusercontent.com/3321655/140060680-ee18108c-a03c-484e-afb6-5d97ad9aee1b.png)

6. In addition, every full hour a new invoice is added as well (I guess this is the interval in which ERPNext checks if any subscriptions needs to be processed)

### Observed result

On every check - automatically or manually triggered - a new invoice is created regardless of the subscription interval.

### Expected result

One invoice should be created with the first check run (automatic or manually triggered). After that the next invoice should be created once the configured subsription period is over to get the invoice for the next upcoming subscription period.

### Stacktrace / full error message

```
N/A
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

Ubuntu 20.04,, installation via Script.

**Comment by ankush** [comment]
Duplicate of https://github.com/frappe/erpnext/issues/28179 ?

Please confirm and close the issue.

**Comment by jacotec** [comment]
@ankush Yap, that's related and the commit seems to fix it. Sorry for overlooking the duplicate.
