### ISSUE TITLE
Postman reports API ssl certificate expired

### ISSUE THREAD

**Issue by dcolley** [frappe/erpnext#28239]
## Description of the issue
I'm testing the REST API with Postman

## Context information (for bug reports)
Simple test to https://my_domain.frappe.cloud/api/method/frappe.auth.get_logged_user with apiKey and apiSecret

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1. Open postman
2. Enter the url
3. Enter your credentials at Authorization header as per the documentation

### Observed result
Postman report ssl expired error
![image](https://user-images.githubusercontent.com/1845970/140095699-36a594e0-dd88-40aa-bfe3-89a263cc460e.png)

### Expected result
The API should respond without SSL error

### Stacktrace / full error message
```
GET https://*****.frappe.cloud/api/method/frappe.auth.get_logged_user
Error: certificate has expired
Network
agent: "Desktop Agent"
Request Headers
Authorization: token b452280a8d6cd58:402d8d37176a6b6
User-Agent: PostmanRuntime/7.28.3
Accept: */*
Cache-Control: no-cache
Postman-Token: 7bed0727-2338-45f7-901d-b6be3750c322
Host: tun-dev.frappe.cloud
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
```

## Additional information
When I override the SSL check on Postman I get the expected result from the API
![image](https://user-images.githubusercontent.com/1845970/140096193-801192f9-d751-4981-9075-9e03c1999cae.png)
... you can turn this off, then the api call works.

However, we can't turn this off in production

**Comment by ankush** [comment]
<img width="896" alt="Screenshot 2021-11-03 at 9 41 59 PM" src="https://user-images.githubusercontent.com/9079960/140098978-41013eb5-6103-41bd-b4a1-de54889b7250.png">
 


Works fine. Maybe some issue with your site, do you see a certificate error in the browser? is your system time correct?

If it still persist get in touch with Frappe Cloud's support: https://frappecloud.com/support 



Closing, as this isn't related to ERPNext or Frappe.

**Comment by dcolley** [comment]
Thanks @ankush 

I found it's a known Postman issue with Letsencrypt certificates
https://github.com/postmanlabs/postman-app-support/issues/10338 

I managed to get around the problem by switching from Desktop to Cloud Agent
![image](https://user-images.githubusercontent.com/1845970/140159127-c9e8065d-5b8d-4737-920d-a0be0141e230.png)
