### ISSUE TITLE
Documenthistory bug

### ISSUE THREAD

**Issue by majubewi** [frappe/erpnext#28246]
## Description of the issue

When a logged in User with his Session is renaming a document, in this case a Contract, it will show his name and the renaming action in the history of the document.

Bug:
When a different user or e.g. the admin logs in the history of the document say the currently logged-in user had changed the document.

## Context information (for bug reports)
Experienced on one of our servers in one case.

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1. Create a Contract
2. Change the name of the contract and look up the history of the document
3. Login with different user and look up the history of the document

### Observed result
The Person renaming of the document is always the user currently logged in with his session.

### Expected result
The Person who change the name should be in the history

### Stacktrace / full error message
No error / just observation

## Additional information

Ubuntu 18.04, ERPNext 13.13

**Comment by ankush** [comment]
https://github.com/frappe/frappe/pull/14519
