### ISSUE TITLE
[V5] Manufacture Entry - General Ledger posting not correct

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#2824]
As per the standard, on submission of Manufacture entry, General Ledger posting is done only for the operations cost. In the attached Production Order, Operations Cost is only 91. But General Ledger entry against Production Order is made for 950. Please check attached screenshots.

Manufacture Entry:

![screen shot 2015-02-23 at 2 39 44 pm](https://cloud.githubusercontent.com/assets/910238/6325227/9156e6ca-bb6a-11e4-9cc8-bf47b2d2a587.png)

General Ledger:

![screen shot 2015-02-23 at 2 40 15 pm](https://cloud.githubusercontent.com/assets/910238/6325230/9ae445ca-bb6a-11e4-9e5b-a31682a5caa3.png)

**Comment by rmehta** [comment]
fixed
