### ISSUE TITLE
Task colours not copied from Project Template to Project instance

### ISSUE THREAD

**Issue by nameduser0** [frappe/erpnext#28259]
## Description of the issue
Task colours not copied from Project Template to Project instance

## Context information (for bug reports)

**Output of `bench version`**
```
ERPNext: v13.9.2
Frappe Framework: v13.9.1
```

## Steps to reproduce the issue

1. Create Project Template & Tasks with colours
2. Create Project from Template

### Observed result
Task colours are blank

### Expected result
Task colours are copied

**Comment by deepeshgarg007** [comment]
<img width="1331" alt="image" src="https://user-images.githubusercontent.com/42651287/202422503-a8d3bd90-5396-46e7-8e22-9bbbabb9d210.png">

Tried verifying this and the color do get copied from the template, closing this
