### ISSUE TITLE
Monthly Subscription generates Sale Invoices hourly  

### ISSUE THREAD

**Issue by jHetzer** [frappe/erpnext#28253]
## Description of the issue
All my subscriptions with only monthly subscription plans are generating new sale invoices hourly for the current month. Also if i press "Fetch Subscription Update" a new Invoice gets created for the same month.

Only if I uncheck "Generate Invoice At Beginning Of Period" this behavior stops 

## Context information (for bug reports)

![image](https://user-images.githubusercontent.com/28366175/140609043-a45416c1-714e-4560-866c-434c3bff01fc.png)

**Output of `bench version`**
```
erpnext 13.13.0
frappe 13.13.0
erpnextfints 0.4.1
```

## Steps to reproduce the issue

1. Create a monthly subscription plan
2. Assign the subscription plan to a new subscription
3. Check "Generate Invoice At Beginning Of Period"
4. Press "Fetch Subscription Update" multiple times

### Observed result
Many Sale Invoices for the same customer and same month

### Expected result
Only one Sale Invoice for one subscription per month

### Stacktrace / full error message

```
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.
```
frappe@erpnext:~/13-frappe-bench$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```
Python version
```
frappe@erpnext:~/13-frappe-bench$ bench console
Apps in this namespace:
frappe, erpnext, erpnextfints
In [1]: import sys
In [2]: sys.version
Out[2]: '3.7.3 (default, Jan 22 2021, 20:04:44) \n[GCC 8.3.0]'
```
Pip
```
frappe@erpnext:~/13-frappe-bench$ bench console
Apps in this namespace:
frappe, erpnext, erpnextfints
In [1]: pip --version
pip 21.3.1 from /home/frappe/13-frappe-bench/env/lib/python3.7/site-packages/pip (python 3.7)
Note: you may need to restart the kernel to use updated packages.
```

**Comment by ankush** [comment]
https://github.com/frappe/erpnext/issues/28179
