### ISSUE TITLE
[V5] Item Variant - Hard to locate Item Code of a variant

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#2825]
When open Item master of a variant, its difficult to locate its Item Code. Can we show an Item Code field where variants Item Code will be shown.

![screen shot 2015-02-23 at 3 45 50 pm](https://cloud.githubusercontent.com/assets/910238/6326069/d7282048-bb73-11e4-863e-595560a50a3a.png)

**Comment by rmehta** [comment]
fixed by name
