### ISSUE TITLE
Employee Checkin Always takes punch time from default value on field

### ISSUE THREAD

**Issue by abdouz** [frappe/erpnext#28258]
## Description of the issue
Employee checkin always takes the punch time from the default value set on Employee Checkin (time) field, currently the default value is "Now" when changing this to another value the other value (default) is always set and the sent value on creation from API is always ignored with no reason.

## Context information (for bug reports)
This issue happens on API call, for creation from the Desk interface it works as expected.

## Steps to reproduce the issue

1. Connect using FrappeClient API to ERPNext
2. Create new Employee Checkin passing necessary parameters (employee, employee_name, time, log_type)
3. The Employee Checkin Record always ignores passed (time) and gets the default one on the field.
4. If we remove the default value a mandatory exception is thrown however a value is passed!.
5. If we set a new default value, it is used and will refuse to duplicate.

### Observed result

The doctype Employee Checkin insert from API call always ignores the (time) value passed and drops to the default of its value.

### Expected result

The passed (time) value should be used

## Additional information

Ubuntu 20.04, ERPNext [13]
![check_in_bug](https://user-images.githubusercontent.com/1107178/140649279-2035e4a7-9a22-4b95-a7b1-1d98bcb2fe14.gif)

**Comment by ankush** [comment]
<img width="1078" alt="Screenshot 2021-11-07 at 8 42 12 PM" src="https://user-images.githubusercontent.com/9079960/140650812-286d2d76-7a65-406e-b265-1f8fff3e8540.png">


works fine from API. Maybe you've some server script forcing the current time? as `time` field?

**Comment by abdouz** [comment]
@ankush kindly further explain?, this is a clean install!

**Comment by ankush** [comment]
Same. I also have clean install of `version-13` and `develop` branches. This works fine on both of them. So you probably have some customization/config that's overriding the time field, or discarding your input value. 

There's nothing different about creating it from API, internally the same code is run. 


This is where defaults are populated: https://github.com/frappe/frappe/blob/5fb905ca31688a94ed3294397ff8cca51f40ff80/frappe/model/create_new.py#L128-L140 


API just uses `get_doc`: https://github.com/frappe/frappe/blob/5fb905ca31688a94ed3294397ff8cca51f40ff80/frappe/api.py#L136-L140 
 

Can you reproduce it from python console using `get_doc`? 


You'll just have to debug it to find what's causing it, try printing input to `get_doc`; `time` field before and after `_set_defaults` method runs in `Document.py`.

**Comment by abdouz** [comment]
@ankush I figured it out, the user should have level 1 write permission on Employee Checkin to be able to write (time) field, I have no explanation, but this may help others searching.

If you created a user with Level 0 Write Permissions on Employee Checkin, you won't be able to write to (time) field and it will be taken from the default automatically, so you should make Level 1 Write Permissions for the user.
