### ISSUE TITLE
[V5] Updating Item Name for a variant

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#2826]
Item Name for a variant should be set  just like Item Description is set Description, in the combination of:

Item Description (of template item) + Item Attribute + Value

Different Item Name will help user identify variant from the list as well. Currently this is how list looks for a variants. All the variants have same item name.

![screen shot 2015-02-23 at 3 55 20 pm](https://cloud.githubusercontent.com/assets/910238/6326121/7106f5cc-bb74-11e4-8a20-e236d720b0e3.png)

**Comment by rmehta** [comment]
fixed
