### ISSUE TITLE
Create Project Template from existing Project

### ISSUE THREAD

**Issue by nameduser0** [frappe/erpnext#28261]
**Is your feature request related to a problem? Please describe.**
The project template function is difficult to use because you need to remember the start and end of each task to plan new tasks around previous ones. The gantt view does not work on task templates

**Describe the solution you'd like**
One good way to create a project template would be to copy an existing (proven) project. There is a `duplicate project` button but you may wish to save as a template.

**Describe alternatives you've considered**
None

**Comment by umairsy** [comment]
@casesolved-co-uk thanks for recommending. Planning to contribute it by any chance? perhaps the better solution would be to enable Gantt for template, rather than creating redundancy.

**Comment by nameduser0** [comment]
@umairsy 
This is why ERPNext will not be a market leader, you ignore your customers and treat their ideas with contempt 😄🤷

**Comment by umairsy** [comment]
We do, hence we have a feature to Duplicate the Projects itself. It also re-creates the tasks linked to that Project. So, all you have to do just tag that Project as a Template and keep duplicating. It's just that it doesn't function in

It's unfair to use the product, provide services on top of it, and then bad-mouth!! Feature is there. Not exactly the 100% you expect it to be.

**Comment by nameduser0** [comment]
I'm not bad-mouthing the product, I'm providing constructive criticism on both the product and it's management. It's your problem that you can't take feedback, not mine.

What if you want to create a master template from an existing project and modify it for later use? Very rarely will you have identical projects.
