### ISSUE TITLE
Raw Material to Finished Goods at the Job Card level

### ISSUE THREAD

**Issue by sharmanakul** [frappe/erpnext#28264]
**Is your feature request related to a problem? Please describe.**
Allow conversion of raw materials into semi-finished goods/finished goods at the job card level.

**Describe the solution you'd like**

- Assign input items which will be required for an operation in the work order
- Assign Output item will will be generated after execution of the operation (job card)
- Update the Job Card, with details of raw-material consumed and output availed
- Start next job card only if the input items for it are available.
- Want to use output item of a job card as an input in the next job card
- Provide sequencing to each operation in the work order and start operations (job cards) in that order.
- When the job cards are completed, update the stocks for the finished item.
- Quickly visualize the inputs of an operation.
- Mark the Job Card as completed.
- Once all job cards are completed, mark Work Order as completed.
- Update the scrap qty and move it to the scrap warehouse

**Comment by guilmori** [comment]
Is there any estimated date for this feature to be available ?
Are we talking weeks or months ?

**Comment by sharmanakul** [comment]
hi @guilmori , i guess it should be released by v13.17 or v13.18. I'll keep on updating here.

**Comment by guilmori** [comment]
> hi @guilmori , i guess it should be released by v13.17 or v13.18. I'll keep on updating here.

Please let me know if you need some hands, I can help with development.

**Comment by rohitwaghchaure** [comment]
https://github.com/frappe/erpnext/pull/38341
