### ISSUE TITLE
[V5] For a Variant Item, Variant section should be disabled/hidden

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#2827]
Since a Variant Item cannot have more variants, Variant section in the Item form should be hidden for it.

![screen shot 2015-02-23 at 4 02 37 pm](https://cloud.githubusercontent.com/assets/910238/6326245/b16bacd8-bb75-11e4-849c-808aa04c18b6.png)

**Comment by rmehta** [comment]
fixed
