### ISSUE TITLE
[V5] On updating Template Item, Variant items didn't update

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#2828]
Steps:

1. I checked "Show in Website" for a template item.
2. Saved Item. On save, message says that variant items has been updated as well.
3. When check variant items, "Show in Website" field was not updated in it.

You can replicate it in staging5 account, for item - SBL89

**Comment by rmehta** [comment]
variants will never be shown in website - user will select variant at time of "add to cart"
