### ISSUE TITLE
Create Invoice for Each Payment Term

### ISSUE THREAD

**Issue by Mohd200** [frappe/erpnext#28297]
Hello Everyone and Good Day

My company requires to issue multiple Sales Invoices from the Sales Order, where each of the Sales Invoices match a Payment Term of the Payment Schedule. However, this feature isn't available, therefore, we create multiple invoices by dividing up the quantity of the Items, and that is extremely ineffective.

It would be more effective to have the option to create a Sales Invoice based on the portion of the next payment on the Payment Schedule.

Case scenario:
Sales Order has 4 Payment Terms, therefore, 4 Sales Invoices will be created. each Invoice will be created when the next Payment Term is due, and sent to the Customer stating the agreed upon amount.

Hope this Loom Video helps:
[https://www.loom.com/share/6fe524511a0b48788d320ca5fa7061a0](url)

Thank you :)

**Comment by mhbu50** [comment]
@harshit-30

**Comment by mhbu50** [comment]
@harshit-30 Any plan for this?

**Comment by harshit-30** [comment]
@mhbu50 you can follow [here](https://github.com/frappe/erpnext/issues/28758).

**Comment by harshit-30** [comment]
@mhbu50 @Mohd200 I need a suggestion here. Let's say - I have a Sales Order of amount $1000 with **one** item with **two** Payment Term.

For first payment term, we will have to issue an invoice and another for the second payment term. 
Question: 
What qty and rate will you display in the invoice?

**Comment by Mohd200** [comment]
Good day

@harshit-30 

Thank you for your effort in this matter.
Regarding your question, if the invoices will be based on the Items then the outcome will be that one of the invoices will be "Before Delivery" (0 Qty of Item - Rate will be 1st Payment term portion), and the other invoice will be "After Delivery" (full Qty of Item - Rate will 2nd Payment term portion).

However, 2 Payment terms can be resolved in the way of issuing a Proforma Invoice where the 1st payment term can be an advanced payment. But the issue lies in more than 2 payment terms with 1 Item.

The general idea is (Case Scenario), to create a Sales Order with 1 Item (No Advance Payments), for example, with +2 Payment Terms. Each invoice would have the Qty of the Item with the full rate, but the Payment amount of the invoice would be the Payment Term's Portion.

Another Case Scenario, Sales Order with 10 Items and +2 Payment Terms. First Invoice ("Before Delivery") would have some of the Items with their full rate, the Grand Total is the same as the Sales Order, but the Payment amount of the invoice would be the Payment Term's Portion. Second Invoice ("After Delivery") would be the same Items (Qty and Rate) as the First Invoice, where the Grand Total is the same as the Sales Order, but the Payment amount of the invoice would be the Payment Term's Portion.

Please acknowledge that the case scenarios provided are examples and not fixed scenarios.
Hopefully this simplifies things for you, let us know if you need more info.

Thanks

**Comment by mhbu50** [comment]
Up

**Comment by mhbu50** [comment]
@harshit-30 Any update?

**Comment by deepeshgarg007** [comment]
@mhbu50 @Mohd200 https://github.com/frappe/erpnext/pull/29137 we have added a report for this requirement

**Comment by Mohd200** [comment]
@deepeshgarg007 
Thank you for your efforts on this topic.

This report displays the Payment Terms set in the PO/SO,
However, our need is to create 1 invoice for each of the mentioned Payment Terms, where the Grand Total of the Invoice is the Payment Amount of the Payment Term.
The example shown in [#29137](https://github.com/frappe/erpnext/pull/29137) shows 2 SOs with multiple Payment Terms.

Our case scenario would be:
The first SO with 2 Payment Terms, will create 2 invoices with the Grand Total of 7,200 (As shown in the example).

In the second SO with 3 Payment Terms, will create 3 invoices, the first invoice's Grand Total will be 3,200 (As shown in the example). The 2nd and 3rd invoice's Grand Total will be 6,400 (As shown in the example).

My question is, will this be applicable with this new feature ?
Looking forward to hearing from you on this...

**Comment by ajlaaghazali** [comment]
Up

**Comment by oderao** [comment]
Any update on this?
