### ISSUE TITLE
[V5] POS - Error when creating payment entry against POS Invoice

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#2830]
Error message says Amount Paid field is missing value. No field with this name is visible in the POS invoice.

By default, value of Grand Total should be updated as Amount Paid.

![screen shot 2015-02-23 at 4 41 48 pm](https://cloud.githubusercontent.com/assets/910238/6326806/6ded4038-bb7b-11e4-9336-3d52d9d1f90a.png)

**Comment by umairsy** [comment]
same error message when creating POS Invoice from form view.

**Comment by pifiu** [comment]
how did you receive the message? Can you go into detail to try and resolve it?

**Comment by gentle-** [comment]
I'm running into this issue as well. Just updated the bench 5 minutes ago.
Steps:
1. choose sales invoice
2. add 1 item to basket. qty = 25
3. Click Pay button
4. select payment method
5. Click Pay button
6. receive error.

**Comment by chabito79** [comment]
I'm having the same issue...Do you know if it has been fixed? Thanks!
