### ISSUE TITLE
Exit Interview Workflow in HR

### ISSUE THREAD

**Issue by pushkarjsh88** [frappe/erpnext#28313]
**_Problem Statement:-_**

The HR module in ERPNext does not have a dedicated workflow for scheduling and conducting exit interviews for the candidates who resign from their service with the organisation. Since Exit Interviews are quite prevalent in the industry, it becomes a must have feature in ERPNext which will allow users to automate this workflow seamlessly. The collected data can help employers and their HR team to learn more insights about employee resignations.

**_Expected Solution:_**

A dedicated workflow to be designed in the HR module which will allow users (based on the user rights) to schedule and conduct exit interviews for their resigned employees and register feedback for further reference.

**_Who is the end user? Define persona(s)._**

HR Personnel / HR Manager
Reporting Manager
Top Management of the organisation

**Comment by ruchamahabal** [comment]
https://github.com/frappe/erpnext/pull/28741
