### ISSUE TITLE
[V5] POS - Item Code not updating based on Barcode value

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#2831]
Please check attached file to replicate this issue.

Not able to edit Item Qty, hence not able to remove row from the POS Invoice as well.

![pos-barcode2](https://cloud.githubusercontent.com/assets/910238/6326999/42a278a6-bb7d-11e4-8d4d-26c0525fa657.gif)

**Comment by rmehta** [comment]
fixed. thanks for the gif animations - saves a lot of time!
