### ISSUE TITLE
Field name overlaps with selected company / warehouse in Total Stock Summary Report 

### ISSUE THREAD

**Issue by yadavyk** [frappe/erpnext#28329]
## Description of the issue

Open and view the Total Stock Summary Report, the field name and the selected company/warehouse overlap

## Screenshot 

![UI for Total Stock Summary](https://user-images.githubusercontent.com/32797974/141101421-772de8f5-73f1-4dd4-bfc5-c7194512dcb3.png)

**Comment by ankush** [comment]
this is caused by 

https://github.com/frappe/erpnext/blob/dd1c9dcecea0defe2b719fdb1ea3920f2c17bb22/erpnext/stock/report/total_stock_summary/total_stock_summary.js#L17-L28

**Comment by ankush** [comment]
IMO this report can just be dropped completely, it's so basic it can be reconstructed using report builder on Bin doctype. 

All the info is already present in other report. 😅
