### ISSUE TITLE
Subscription keeps generating invoices every hour 

### ISSUE THREAD

**Issue by arun-lmnas** [frappe/erpnext#28328]
## Description of the issue
Invoices keep generated every hour for the same subscription. The subscription plan is monthly one. However till date close to  200 invoices were generated for the same subscription. This is happening post last minor release upgrade.

## Context information (for bug reports)

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1. Create a subscription plan with monthly frequency
2. Uncheck cancel at end of period 
3. Uncheck Automatically submit invoice

### Observed result
Invoices will get generated every 1 hour in draft mode under the same subscription
### Expected result
Only one invoice should get generated in draft mode
### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by ankush** [comment]
fixed via https://github.com/frappe/erpnext/pull/28187
