### ISSUE TITLE
How to connect ERPNext with Azure AD

### ISSUE THREAD

**Issue by vigneshwaranl92** [frappe/erpnext#28335]
Am trying to figure out Azure AD integration with ERPNext.
I see the integration filed for LDAP, but how do i get the details of DN, OU and search base from Azure AD.

**Comment by ankush** [comment]
discuss.erpnext.com

**Comment by hujaifaibneomar** [comment]
Error issues remove and development support and solutions

**Comment by hujaifaibneomar** [comment]
Support and development all issues remove
