### ISSUE TITLE
Manufacture entry set source warehouse to WIP even if Skip Transfer is checked

### ISSUE THREAD

**Issue by guilmori** [frappe/erpnext#28336]
My work order has Skip Transfer checked.
![image](https://user-images.githubusercontent.com/9451512/141217601-e46446d0-51df-4ce3-ae43-dc30db0f6840.png)

When I create Manufacture stock entry, default source warehouse is still set to Work In Progress
![image](https://user-images.githubusercontent.com/9451512/141217758-faf3799c-df5e-40e3-b8d2-5a9821a2dffd.png)

I would have expected the source warehouse to be the item's default warehouse (ie: Stores)

**Comment by guilmori** [comment]
I wonder what the checkbox "Backflush Raw Materials From Work-in-Progress Warehouse" does ?
I was assuming:
CHECKED -> Default Source Warehouse is Work In Progress
UNCHECKED -> Default Source Warehouse is the item's default

**Comment by sharmanakul** [comment]
@guilmori did you, by any chance, set the WIP warehouse in the work order?  If you have set a default WIP warehouse in the manufacturing settings then it gets populated from there in the work order

**Comment by guilmori** [comment]
> @guilmori did you, by any chance, set the WIP warehouse in the work order? If you have set a default WIP warehouse in the manufacturing settings then it gets populated from there in the work order

Yes I have a default WIP warehouse in the manufacturing settings, because some jobs use it.
Production uses WIP, Packaging doesn't.

I tried removing the WIP warehouse in the Work Order, but I soon as I save, it brings back the default one from manufacturing settings.

So just for test, I removed manufacturing settings, I was able to save Work Order without setting a WIP warehouse. But then when I try to submit the Job Card, there is a validation on another WIP warehouse field being mandatory in the Job Card...

**Comment by guilmori** [comment]
FYI, I changed erpnext source code and now it works as I would expect.
I understand this may be a breaking change for others who pick from WIP but don't handle transfer to WIP through  the Work Order.
![image](https://user-images.githubusercontent.com/9451512/141490643-6e887257-e197-48d9-9dce-68f29f2f9d5a.png)

**Comment by carstenblt** [comment]
@s-aga-r The original bug is still not fixed
#32918 makes sure the WIP warehouse is not set as the default warehouse in the Stock Entry. However the from_warehouse is still replaced in the individual item lines of the Stock Entry.

**Comment by s-aga-r** [comment]
@carstenblt 

>However the from_warehouse is still replaced in the individual item lines of the Stock Entry.

There is no field named `from_warehouse` in the Stock Entry Detail, you mean `s_warehouse`? If yes then it's the expected behaviour. The Stock Entry Items `Source Warehouse` gets set to the Items Default Warehouse.

ref: https://github.com/frappe/erpnext/issues/28336#issue-1050467382

> I would have expected the source warehouse to be the item's default warehouse (ie: Stores)

**Comment by carstenblt** [comment]
> @carstenblt
> 
> > However the from_warehouse is still replaced in the individual item lines of the Stock Entry.
> 
> There is no field named `from_warehouse` in the Stock Entry Detail, you mean `s_warehouse`? If yes then it's the expected behaviour. The Stock Entry Items `Source Warehouse` gets set to the Items Default Warehouse.
> 
> ref: [#28336 (comment)](https://github.com/frappe/erpnext/issues/28336#issue-1050467382)
> 
> > I would have expected the source warehouse to be the item's default warehouse (ie: Stores)

I guess you are right, it may make sense to do it that way. However all of this is not very intuitive...
