### ISSUE TITLE
CRM add new lead

### ISSUE THREAD

**Issue by ekariz** [frappe/erpnext#28339]
## Description of the issue
Full name of lead picks company name
## Context information (for bug reports)

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1.Open CRM
2. add lead
3. enter company name, 

### Observed result
It get copied to full name field (locked)
### Expected result
first name + mid name + last name
### Stacktrace / full error message
 
OS version / distribution, `ERPNext` install method, etc.
Install on ubuntu 20 
ERPNext v13.x.x-develop () (develop)
Frappe Framework: v14.x.x-develop () (develop)

![Screenshot from 2021-11-11 08-18-18](https://user-images.githubusercontent.com/5812903/141241939-290e87d7-9259-4445-833b-89ed7d6f6516.png)

**Comment by pushkarjsh88** [comment]
@ekariz I did not encounter this while re-creating the scenario. Do let know if you are still facing the same.

**Comment by anupamvs** [comment]
@ekariz This is the expected result. If the company/organization name is set we consider it a lead from the organization.
