### ISSUE TITLE
KSA E-Invoicing QR-Code has broken.

### ISSUE THREAD

**Issue by sammish** [frappe/erpnext#28342]
Hello, Team 

I have updated my multiple site and I have found the issue in my two site the QR code is broken 
![image](https://user-images.githubusercontent.com/12432802/141265442-e4e2901c-4eaf-4289-bbb7-593499355bb9.png)
I have used ( img class="qr-code" src={{doc.qr_code}}) 

Instead of this If I use ( img src="{{doc.qr_code}}" ) QR code will be appear but when we scan the result as per below 

![image](https://user-images.githubusercontent.com/12432802/141265530-b450f1f7-2256-4fff-974d-f9619dbbb2b1.png)

How to fix this ? Need some help...

![ScreenRecorderProject9](https://user-images.githubusercontent.com/12432802/141265614-2e77f426-bd66-429e-9d35-4c51dff52c4b.gif)

@Mohammed_Redha @Mohammad_Ahmad_Zulfi @ahmadpak

**Comment by sammish** [comment]
https://user-images.githubusercontent.com/12432802/141265961-9127d8b1-6afa-4cc2-9c10-4b094c638018.mp4

**Comment by sammish** [comment]
Genrated URL : https://erp.marsaaljazira.com/Sales%20Invoice/MAJ%20/%20SINV-21-00034?format=QRPrint&_lang=en&key=7f859a70c17838839e67006dc0ce82f6ae79c663a1aefc9340ea4e4b

**Comment by ahmadpak** [comment]
@sammish Please check your print format for the two sites.

**Comment by sammish** [comment]
I have found the solution

I have used the before “ Naming Series “ like SBM / SINV-21-00142

I have changed the Naming Series to SBM-SINV-21-00001 

Now Issue solved 

“ / “ not support

![image](https://user-images.githubusercontent.com/12432802/141653313-48f4aeb2-40ce-461b-8fc7-2fd4133b1ca3.png)

**Comment by zahidshuja** [comment]
After upgrading to erpnext new version, my scan is not working anymore. when I scan it's not showing the invoice . Before migration it was working fine.
