### ISSUE TITLE
Tab button doesn't work correctly. Should to go "From Time" to "To Time" in Course Scheduling Tool

### ISSUE THREAD

**Issue by GoldenScrew** [frappe/erpnext#28347]
## Description of the issue

When you place your cursor in the field "From Time" and then pres Tab key|button on your keyboard cursor should be in the field "To Time" but cursor going to "Course Start Date" field.

## Context information (for bug reports)

**Output of `bench version`**
```
ERPNext: v13.13.0 (version-13)
Frappe Framework: v13.13.0 (version-13)
```

## Steps to reproduce the issue

1. Go to Course Scheduling Tool .../app/course-scheduling-tool 
2. Place your cursor in the "From Time" field.
3. press "Tab" key on your keyboard.

### Observed result

Your cursor will be in the "Course Start Date" field.

### Expected result

Your cursor should be in the "To Time" field.

### Stacktrace / full error message

```
no error.
```

## Additional information

Google Chrome.

**Comment by ankush** [comment]
Okay, I see it now. 

You can fix this by changing field order similar to the course schedule. We don't manually define tab order anywhere. 


https://user-images.githubusercontent.com/9079960/141300740-428fa1af-1ffd-4ebf-b6f1-c2d407518649.mov

**Comment by GoldenScrew** [comment]
> Okay, I see it now.
> 
> You can fix this by changing field order similar to course scheduling tool. We don't manually define tab order anywhere.
> 
>  Screen.Recording.2021-11-11.at.6.18.43.PM.mov

But I can't save this doctype after editing. I have status of document "Not saved", and I haven't Save button.

https://user-images.githubusercontent.com/3992823/141308742-b2527899-137a-4ec4-b159-767e61a8cf16.mp4

I think so I need enable developer mode. So If I will enable develop mode and change this, when I will update erpnext, will it save or no?

**Comment by ankush** [comment]
I'd advise against doing it on production sites. Developer mode disables caching in many places hence it can cause slow performance. 

If you just want it fixed on your site you can use "Customize Form" to change field order. If you want to send a fix, use a separate instance.

**Comment by GoldenScrew** [comment]
> I'd advise against doing it on production sites. Developer mode disables caching in many places hence it can cause slow performance.
> 
> If you just want it fixed on your site you can use "Customize Form" to change field order. If you want to send a fix, use a separate instance.

I can't use Customize Form for **Course Schedule Tool**, I haven't it in List (see screenshot). I think the tool write not correct and users can't customize it.

I am very want to fix it and other bugs and use updates in the future.
![QIP Shot - Screen 065](https://user-images.githubusercontent.com/3992823/141315241-45021d9f-1417-47ac-9519-76c45d8c22d2.png)

**Comment by ankush** [comment]
Ah sorry my bad. It's a "Single" doctype so can't be customized like that.

**Comment by ankush** [comment]
Hi, since this was a short fix I just sent a PR https://github.com/frappe/erpnext/pull/28353 

If you want to contribute yourself you should ideally set up a separate bench because reusing the production site is not advisable. 

Thanks again for pointing it out 👍
