### ISSUE TITLE
[V5] Sign Up option not working on the login page

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#2835]
After I provide name and Email ID, and click on Sign Up button, get no response. Seems like Sign Up button itself is inactive.

After testing, I disabled shopping cart and sign up option for staging5.

![screen shot 2015-02-23 at 7 43 33 pm](https://cloud.githubusercontent.com/assets/910238/6329198/48785c0c-bb94-11e4-8ce5-0920e7581c68.png)

**Comment by rmehta** [comment]
can't replicate
