### ISSUE TITLE
Work Order with Skip Transfer and Operations won't update status on completion of Job Card

### ISSUE THREAD

**Issue by guilmori** [frappe/erpnext#28354]
Work Order is checked to Skip Transfer
![image](https://user-images.githubusercontent.com/9451512/141316669-1495af6b-a266-4f9d-ab41-1ec82252c0a9.png)

Work Order has operations, so it creates Job Cards on submit.

When we submit the first Job Card (to complete), the Work Order status remains to Not Started.
![image](https://user-images.githubusercontent.com/9451512/141317399-ffd4860a-6748-48fd-83a9-b7d65287997e.png)

I guess the Work Order Status logic is only relying on Stock Entry made, and there isn't any yet in this case because on the Skip Transfer.

**Comment by rohitwaghchaure** [comment]
@guilmori The Work Order status is not depends on Operations therefore it remains as "Not Started". Maybe we can add better flow in the upcoming versions.
