### ISSUE TITLE
Server error while opening point of sale erpnext v13.14.0

### ISSUE THREAD

**Issue by fadilsiddique** [frappe/erpnext#28378]
I have hosted a new site with erpnext and frappe installed in frappe cloud and restored sql database of a site that worked fine on my local server. Now when i open point of sale it shows a pop-up of server error pymysql.err.OperationalError:(4078,"illegal parameter data types varchar and row for operation ‘=’’’). I’ve attached screenshot of the erro
![Screenshot from 2021-11-12 17-58-11](https://user-images.githubusercontent.com/48912196/141468734-42298011-4e7c-4c66-8f74-0187b6d5c0e7.png)
r.

**Comment by ankush** [comment]
fixed https://github.com/frappe/erpnext/pull/28323

will be part of next patch release soon.
