### ISSUE TITLE
13.14.1 update, doc link problem.

### ISSUE THREAD

**Issue by kanedai** [frappe/erpnext#28382]
## Description of the issue
When I update erpnext&frappe from 13.14 to 13.14.1（bench update --reset）, error in terminal:
![334](https://user-images.githubusercontent.com/4647923/141605837-d8e8c874-ebce-42ed-9fb1-1a326cf34463.jpg)

After the update is done, click any doc ( quotation, sales order, etc,) error:
![33](https://user-images.githubusercontent.com/4647923/141605827-44a15c82-fa63-405f-8624-5a18677c4727.jpg)

I have 2 servers, 1st one "bench update --reset" works, 2nd one does not work,  the only difference list below:

1st one: bench --version: 5.0
2nd one: bench --version:5.6( I update the bench a few days ago, using the cmd: sudo pip3 install  -U frappe-bench.

-------

When I upgraded the bench version to 5.6 on 1st server, the same error happened.

**Comment by kanedai** [comment]
I have 2 servers

**Comment by kanedai** [comment]
Pls close this issue,  it is caused by permission problems

**Comment by barredterra** [comment]
@kanedai did you try `bench build --force`? I think `validate_link` was changed in this release and the JS files have to be rebuilt to work with the new behavior. Usually `bench update` should take care of this, but maybe it failed in your case.

**Comment by eanfs** [comment]
same problem, 
how to run bench update on docker container
