### ISSUE TITLE
Dummy "Delivery Note" created by "Administrator" everyday

### ISSUE THREAD

**Issue by anishshirwant** [frappe/erpnext#28383]
## Description of the issue
ERPNext auto creates 2 delivery notes and keeps it in the draft form everyday as can be seen on the screenshot (The first 2 items).
These are created by "Administrator" account and are not initiated by anyone.

## Context information (for bug reports)
![Screenshot 2021-11-13 at 11 37 34 AM](https://user-images.githubusercontent.com/8413365/141608034-0aaa0a49-fab4-4fcd-9db7-be94762e2e27.png)
![Screenshot 2021-11-13 at 11 45 55 AM](https://user-images.githubusercontent.com/8413365/141608262-2aff5b79-9eb1-4dbd-9ad8-2d8613e341f3.png)

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1.
2.
3.

### Stacktrace / full error message

```
(paste here)
```

## Additional information
Hosted with "Managed Hosting" with ERPNext

**Comment by ankush** [comment]
You probably have some background job/automation integration that's creating it?

Note down the creation time of document, go to ,"scheduled job log" doctype and see which action ran right before the document was created.

**Comment by kennethsequeira** [comment]
@anishshirwant i would suggest to look at any customizations done or Auto Create being run for these. This doesn't seem like a bug. 

Please let us know what results you get after trying these suggestions.

**Comment by ankush** [comment]
Reopen / comment if required. Closing because this doesn't seem like a bug.

**Comment by anishshirwant** [comment]
Hello Frappe/ERPNext team,

Thank you for your quick response.

I have looked at scheduled jobs and have note found any jobs that are creating the delivery note.

The document is created each day at a different time.
It was created on “16-11-2021 00:02:07”
It was created on “15-11-2021 00:03:16”
and so on

It is mostly created between 2am to 5am everyday. 2 delivery notes are created to a customer and stored in draft form.

I am not running any custom background jobs/automation integration on the system.

I am attaching how the activity log for the “Administrator” looks and I am also attaching the "scheduled job log” for the time that the entries were created.

Regards,
Anish Shirwant
