### ISSUE TITLE
[V5] Print Format Builder - Columns as defined not rendering in the Print Format

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#2840]
Steps:

1. Created new Print Format called "Purchase Bill"
1. In the first section, added 3 columns.
1. In the print format, for the first section, only one column is shown.

Print Format Builder:

![screen shot 2015-02-23 at 11 40 37 pm](https://cloud.githubusercontent.com/assets/910238/6333730/76bbeafe-bbb5-11e4-918b-bd4ea9de380f.png)

Print format:
![screen shot 2015-02-23 at 11 40 52 pm](https://cloud.githubusercontent.com/assets/910238/6333735/826695d4-bbb5-11e4-88e3-529476ef31fd.png)

**Comment by umairsy** [comment]
When I check Print Format in the Print Format Builder again, it didn't show second and third columns at all. Perhaps these columns were not updated when I first created print format.

**Comment by rmehta** [comment]
works now...
