### ISSUE TITLE
Payment Entry Receive from Shareholder

### ISSUE THREAD

**Issue by usman-alikhan** [frappe/erpnext#28401]
Payment Entry can not be made to "Receive" amount from shareholder e.g. loan from shareholder/director.

 ![image](https://user-images.githubusercontent.com/81390347/141851310-770bf78e-615f-41da-924a-aa4637cbf2b1.png)

**Comment by sharmanakul** [comment]
this is a duplicate issue of https://github.com/frappe/erpnext/issues/28393
