### ISSUE TITLE
BOM Update Tool and Update Cost not work

### ISSUE THREAD

**Issue by komalk1992** [frappe/erpnext#28404]
Hi,

BOM Update Tool and Update Cost not work in BOM

**ERPNext: v13.14.1 (version-13)
Frappe Framework: v13.14.1 (HEAD)**
URL: https://princecare.frappe.cloud

please check video.

![BOM-Update-Tool-Google-Chrome-20](https://user-images.githubusercontent.com/85679229/141921821-097a34e6-2c3e-4c83-89f4-dcca18ce51c6.gif)

**Comment by ankush** [comment]
> Check Stock Balance report and see what's valuation rate shown there.


The valuation rate is picked from the stock ledger. If that valuation rate isn't changed you won't notice the difference in BOM cost. This seems to work as expected and there were no recent changes to this functionality that could've broken it. 

Closing for now. Reopen or add comment with steps to reproduce for further investigation.
