### ISSUE TITLE
KSA VAT Settings not found

### ISSUE THREAD

**Issue by rtdany10** [frappe/erpnext#28410]
On Frappe Cloud. Updated ERPNext for KSA E-Invoicing.
Couldn't find the settings, so I tried changing the country inside Company and got this error:
![image](https://user-images.githubusercontent.com/52111700/141980141-b2385dd7-715a-41aa-8a9d-fab52e0b4d62.png)

Error Log:
![image](https://user-images.githubusercontent.com/52111700/141980223-fdcb24b3-4437-46f9-9e2a-2cc8848cb562.png)

ERPNext: v13.14.1 (version-13)
Frappe Framework: v13.14.1 (HEAD)

**Comment by rtdany10** [comment]
For some reason, I have South African VAT Settings enabled.
![image](https://user-images.githubusercontent.com/52111700/142006854-78825df5-3181-44f1-b442-d4fd40700625.png)

**Comment by harshit-30** [comment]
@ahmadpak

**Comment by fkalpana** [comment]
Same here 
Page ksa-vat-setting not foundThe resource you are looking for is not available

On debug 
21:01:01 web.1            | 78.100.208.147 - - [22/Nov/2021 21:01:01] "POST /api/method/frappe.desk.desktop.get_desktop_page HTTP/1.1" 200 -
21:01:02 web.1            | 78.100.208.147 - - [22/Nov/2021 21:01:02] "GET /api/method/frappe.desk.reportview.get_list?filters=%7B%22name%22%3A%22Administrator%22%7D&fields=%5B%22*%22%5D&doctype=Dashboard+Settings&limit=20&_=1637614849833 HTTP/1.1" 200 -
21:01:02 web.1            | 78.100.208.147 - - [22/Nov/2021 21:01:02] "GET /api/method/frappe.desk.form.load.getdoc?doctype=Dashboard+Chart&name=Profit+and+Loss&_=1637614849834 HTTP/1.1" 200 -
21:01:02 web.1            | 78.100.208.147 - - [22/Nov/2021 21:01:02] "POST /api/method/frappe.desk.query_report.get_script HTTP/1.1" 200 -
21:01:02 web.1            | 78.100.208.147 - - [22/Nov/2021 21:01:02] "GET /api/method/frappe.client.get_js?items=%5B%22assets%2Ferpnext%2Fjs%2Ffinancial_statements.js%22%5D&_=1637614849835 HTTP/1.1" 200 -
21:01:03 web.1            | 78.100.208.147 - - [22/Nov/2021 21:01:03] "POST /api/method/erpnext.accounts.doctype.accounting_dimension.accounting_dimension.get_dimensions HTTP/1.1" 200 -
21:01:03 web.1            | 78.100.208.147 - - [22/Nov/2021 21:01:03] "POST /api/method/frappe.desk.query_report.run HTTP/1.1" 200 -
21:01:03 web.1            | 78.100.208.147 - - [22/Nov/2021 21:01:03] "GET /api/method/frappe.client.get?doctype=Dashboard+Chart&name=Profit+and+Loss&filters=&_=1637614849836 HTTP/1.1" 200 -
21:01:12 web.1            | 78.100.208.147 - - [22/Nov/2021 21:01:12] "POST /api/method/frappe.deferred_insert.deferred_insert HTTP/1.1" 200 -
21:01:42 web.1            | Traceback (most recent call last):
21:01:42 web.1            |   File "/opt/bench/frappe-bench/apps/frappe/frappe/app.py", line 68, in application
21:01:42 web.1            |     response = frappe.api.handle()
21:01:42 web.1            |   File "/opt/bench/frappe-bench/apps/frappe/frappe/api.py", line 55, in handle
21:01:42 web.1            |     return frappe.handler.handle()
21:01:42 web.1            |   File "/opt/bench/frappe-bench/apps/frappe/frappe/handler.py", line 31, in handle
21:01:42 web.1            |     data = execute_cmd(cmd)
21:01:42 web.1            |   File "/opt/bench/frappe-bench/apps/frappe/frappe/handler.py", line 67, in execute_cmd
21:01:42 web.1            |     return frappe.call(method, **frappe.form_dict)
21:01:42 web.1            |   File "/opt/bench/frappe-bench/apps/frappe/frappe/__init__.py", line 1208, in call
21:01:42 web.1            |     return fn(*args, **newargs)
21:01:42 web.1            |   File "/opt/bench/frappe-bench/apps/frappe/frappe/desk/desk_page.py", line 32, in getpage
21:01:42 web.1            |     doc = get(page)
21:01:42 web.1            |   File "/opt/bench/frappe-bench/apps/frappe/frappe/desk/desk_page.py", line 13, in get
21:01:42 web.1            |     page = frappe.get_doc('Page', name)
21:01:42 web.1            |   File "/opt/bench/frappe-bench/apps/frappe/frappe/__init__.py", line 886, in get_doc
21:01:42 web.1            |     doc = frappe.model.document.get_doc(*args, **kwargs)
21:01:42 web.1            |   File "/opt/bench/frappe-bench/apps/frappe/frappe/model/document.py", line 75, in get_doc
21:01:42 web.1            |     return controller(*args, **kwargs)
21:01:42 web.1            |   File "/opt/bench/frappe-bench/apps/frappe/frappe/model/document.py", line 113, in __init__
21:01:42 web.1            |     self.load_from_db()
21:01:42 web.1            |   File "/opt/bench/frappe-bench/apps/frappe/frappe/model/document.py", line 156, in load_from_db
21:01:42 web.1            |     frappe.throw(_("{0} {1} not found").format(_(self.doctype), self.name), frappe.DoesNotExistError)
21:01:42 web.1            |   File "/opt/bench/frappe-bench/apps/frappe/frappe/__init__.py", line 439, in throw
21:01:42 web.1            |     msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable, wide=wide, as_list=as_list)
21:01:42 web.1            |   File "/opt/bench/frappe-bench/apps/frappe/frappe/__init__.py", line 418, in msgprint
21:01:42 web.1            |     _raise_exception()
21:01:42 web.1            |   File "/opt/bench/frappe-bench/apps/frappe/frappe/__init__.py", line 372, in _raise_exception
21:01:42 web.1            |     raise raise_exception(msg)
21:01:42 web.1            | frappe.exceptions.DoesNotExistError: Page ksa-vat-setting not found
21:01:42 web.1            | 
21:01:42 web.1            | 78.100.208.147 - - [22/Nov/2021 21:01:42] "POST /api/method/frappe.desk.desk_page.getpage HTTP/1.1" 404 -
21:02:32 web.1            | 127.0.0.1 - - [22/Nov/2021 21:02:32] "GET /api/method/frappe.realtime.get_user_info?sid=b5fb3b408317e242d0f9bdd01aa334f9e57e495f576f87cc2ca16ef4 HTTP/1.0" 200 -

**Comment by fkalpana** [comment]
Issue resolved after 
bench get-app ksa_vat https://github.com/ahmadpak/ksa_vat.git
bench --site xxx.erpgulf.com install-app ksa_vat
bench --site xxx.erpgulf.com migrate

**Comment by rtdany10** [comment]
> Issue resolved after `bench get-app ksa_vat https://github.com/ahmadpak/ksa_vat.git `

KSA VAT is a standard part of ERPNext now. It should come by default without installing this app.

**Comment by harshit-30** [comment]
@rtdany10 can we mark this as closed?

**Comment by rtdany10** [comment]
> @rtdany10 can we mark this as closed?

Not yet. I still don't have KSA VAT Settings.
Maybe installing the custom app might work, but, that isn't the right method.

**Comment by harshit-30** [comment]
What steps did you take? It works fine for me. You explaining the config of your system might help us replicate it.

**Comment by rtdany10** [comment]
> What steps did you take? It works fine for me. You explaining the config of your system might help us replicate it.

I'm on Frappe Cloud, hence no code customization. Updated the system after KSA E-Invoicing was introduced. No custom fields were generated, neither the QR Code.

**Comment by rtdany10** [comment]
Hi, seems like it's fixed. Was able to access the settings after last update. Thanks :)
