### ISSUE TITLE
Submit Required Project Module

### ISSUE THREAD

**Issue by ruchin78** [frappe/erpnext#2841]
I need to have Submit step in Project

**Comment by umairsy** [comment]
Ruchin,

Project is not a submittable document. You can manage it with multiple
Status in the workflow.

On Tue, Feb 24, 2015 at 10:12 AM, ruchin78 <notifications@github.com> wrote:

> I need to have Submit step in Project
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/frappe/erpnext/issues/2841>.
>



-- 
Thanks and Regards,
Umair Sayyed
www.erpnext.com

**Comment by ruchin78** [comment]
Yes, I know it is not a submittable document, that is the reason I want to know how to do this. I am attaching my screenshot with it
![image](https://cloud.githubusercontent.com/assets/11055625/6343717/ce90fea0-bc13-11e4-8315-9f550cf11da5.png)
Please let me know, how can I do this.
I want created, submit for approval then Approved or Reject

**Comment by umairsy** [comment]
Ruchin,

Github Issue is only for the technical issues and feature suggestions. Please post your functional queries on the forum or on support.

**Comment by ruchin78** [comment]
I have already submitted my query on  https://discuss.frappe.io
Now, can you please reply my queries instead of wasting time of sending
reminders mails as I have already received a mail from Rushabh.

*Regards*
*Ruchin Sharma*
*ERP Specilist*
*miSport Manufacturing Pvt. Ltd.*
*+91 9718555281*
*skype id:ruchinsharmagur*

**Comment by rmehta** [comment]
You can restrict workflow states based on roles.
