### ISSUE TITLE
Allow Stale Exchange Rates displays Stale Days opposite of expected behaviour

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#28437]
When it's ticked it doesn't show Stale Days
![image](https://user-images.githubusercontent.com/1822868/142197714-e425e8fd-682f-4b9d-a9c5-839bcc399585.png)

When ticked, it shows Stale Days
![image](https://user-images.githubusercontent.com/1822868/142197785-f09560f3-078a-4367-922c-c2797d0525aa.png)

**Comment by ankush** [comment]
This seems to be intentional but I agree this behaviour is bit weird and labels are confusing.

https://github.com/frappe/erpnext/blob/402205278c718ee66cbb01d23c9772d75652ec4b/erpnext/setup/utils.py#L83-L86
