### ISSUE TITLE
PDF issue

### ISSUE THREAD

**Issue by mithubindia** [frappe/erpnext#28444]
Letter head created using html containing image ( off course logo.png file attached.  But while creating invoice / quote / sales order - pdf gets created without any logo image,  Tried with *.jpg also.  If I create letterhead only with image,  pdf created, contains no image also the formatting disappears.
Tried with production, development , edge versions.
Only official docker image with stable version 12.26 produces a correct pdf.
Tried on multiple operating systems ( Ubuntu 20.04, Debian 11, Cent os 7 ) with same results.
However, if I print the document with browser, image appears but , headers do not repeat.
Please help.

**Comment by yashodhank** [comment]
@mithubindia kindly ask such questions on https://discuss.erpnext.com/ also try searching on forum for related existing discussions. 
Share details such as screenshots, logs, version, type of deployment etc. as much as possible for others to help you.
Thank you
