### ISSUE TITLE
[V5] Print Format Builder - Not able to edit existing print format

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#2845]
Steps:

1. In the field "Select Print Format to Edit", I selected custom built "Purchase Bill" print format.
2. Clicked on Edit. 

Attached is the error message when click on Edit.

![screen shot 2015-02-24 at 12 17 47 pm](https://cloud.githubusercontent.com/assets/910238/6344519/b7f89e9e-bc1f-11e4-9d59-59e254b9987a.png)

**Comment by rmehta** [comment]
cannot replicate, please state steps....
