### ISSUE TITLE
Callback from Call Log Screen

### ISSUE THREAD

**Issue by mohsinalimat** [frappe/erpnext#28453]
Hello,
I am facing below issue on callback button from call log and I also integrate Exotel.

Uncaught TypeError: frappe.phone_call.handler is not a function

![Screenshot 2021-11-18 at 4 42 42 PM](https://user-images.githubusercontent.com/973676/142405898-1735d52a-0260-4fae-b932-a9a78e0750c3.png)

**Comment by chechani** [comment]
Hello,
I am facing below issue on callback button from call log and I also integrate Exotel.

Uncaught TypeError: frappe.phone_call.handler is not a function

**Comment by jango-blockchained** [comment]
Solved: frappe.phone_call.handler Error

YOU NEED TO BE LOGGED IN AS EMPLOYEE, NOT AS ADMINISTRATOR!

Greetz

**Comment by shamilnk** [comment]
> Hello, I am facing below issue on callback button from call log and I also integrate Exotel.
> 
> Uncaught TypeError: frappe.phone_call.handler is not a function
> 
> ![Screenshot 2021-11-18 at 4 42 42 PM](https://user-images.githubusercontent.com/973676/142405898-1735d52a-0260-4fae-b932-a9a78e0750c3.png)

Feature is Not For Exotel. its for Twillio
