### ISSUE TITLE
Customer Master >> GST Category should get changed to "Unregistered" in mentioned scenario

### ISSUE THREAD

**Issue by nidhipurohit11** [frappe/erpnext#28465]
Customer master shows a field GST Category. The value here depends on GSTIN no present in the address.
When GSTIN no is present then GST Category should be "Registered Regular" else it should be "Unregistered"

## Steps to reproduce the issue

1. I created a customer (by default it shows the GST category as "Unregistered")
2. Then I created an address into it and did not give any GSTIN no (the category is still showing as Unregistered)
3. Now edited the address and entered a valid GSTIN, the customer master is now showing category "Registered Regular" which is correct.
4. But now I edited the address again and removed GSTIN no from it, but the customer master is still showing GST Category as "Registered regular". 

It should it get changed back to Unregistered again. 

![Screenshot 2021-11-19 at 6 47 39 PM](https://user-images.githubusercontent.com/82337328/142629382-b4fa687a-38e8-4e91-88de-be50b2694042.png)

![Screenshot 2021-11-19 at 6 47 58 PM](https://user-images.githubusercontent.com/82337328/142629410-58a3fd8a-3632-4439-8401-1864b9dd411f.png)

### Observed result - 
After removing GSTIN no from address the GST category is shown as Registered Regular

### Expected result - 
It should get changed to Unregistered again.

**Comment by deepeshgarg007** [comment]
Moved to India Compliance app, not valid anymore

**Comment by Shankarv19bcr** [comment]
.
