### ISSUE TITLE
Leave encashment amount as formula

### ISSUE THREAD

**Issue by chrisdent** [frappe/erpnext#28473]
Would be nice to have leave encashment as formula, let's say:

1) Fixed value ( as it is today): you type the amount.
2) As formula: base/work_days. So if a month has 30 work days, to get the leave encashment amount the base would be divided in 30. If month has 31 it would be divided into 31.

**Comment by pushkarjsh88** [comment]
@chrisdent Is this a uniform policy across domains? Are there any additional use cases?

**Comment by chrisdent** [comment]
Well this can create one salary structure for people that are hired with the same salary components completely independent of the amount of the base salary, using the base in the salary structure in the formula in the salary component.

Reducing significantly the amount of salary structures.

So yes. =)

**Comment by chrisdent** [comment]
Well, also the hour rate by formula. =)

Or what it could be awesome: Copy these constants to salary structure assignment and do the calculations from Salary structure assignement.
