### ISSUE TITLE
After Update, Incorrect Sales invoice Report

### ISSUE THREAD

**Issue by mubeenmazhar** [frappe/erpnext#28494]
I always create a report with following columns:
ID – Customer – Item (Sales Invoice Item) – Rate (Sales Invoice Item) – Weight (Sales Invoice Item) – Amount (Sales Invoice Item)

With following filters:
Document status = Submitted

But after the last update it is only showing one item from each table, even if there are multiple items based on filter are available.

**Comment by santoshbb** [comment]
Please make things easy to understand by attaching snapshots, code and videos if possible

**Comment by mubeenmazhar** [comment]
@santoshbb  ** Sales Invoice have follinwing items:**
![S1](https://user-images.githubusercontent.com/47884718/142904044-088719c9-94d2-4aa4-bce8-27ee60f26a5d.png)


** But sales invoce eport is ony showng one item**
![R1](https://user-images.githubusercontent.com/47884718/142903977-7dceb13f-4274-4c08-b5b0-17829747374d.png)
![R2](https://user-images.githubusercontent.com/47884718/142903997-ab03406e-c95a-4c88-965a-31014619b6af.png)

**Comment by mubeenmazhar** [comment]
> Please make things easy to understand by attaching snapshots, code and videos if possible

I tried `bench update` command but it didn't fix the problem.

**Comment by mubeenmazhar** [comment]
I just received the notification for latest update to `Version: 13.15` and after update ( `bench update` ), the issue is resolved.
Thanks @santoshbb
