### ISSUE TITLE
BOM Tree Broken 

### ISSUE THREAD

**Issue by yadavyk** [frappe/erpnext#28498]
## Description of the issue

When you open BOM in tree view , the UI appears broken 

## Screenshot 

![image](https://user-images.githubusercontent.com/32797974/142851286-c9f21d8b-b512-4d44-9ff6-1d1afd2215c0.png)

## Context information 

ERPNext: v13.14.1 (version-13)
Frappe Framework: v13.14.1 (version-13)

### Observed result

The BOM Tree view appears broken 

### Expected result

The BOM Tree view should appear appropriately

**Comment by bhavesh95863** [comment]
https://github.com/frappe/erpnext/pull/28512
