### ISSUE TITLE
[V5] Pdf printview shows more fields than regular printview 

### ISSUE THREAD

**Issue by PrakashH** [frappe/erpnext#2851]
Find below screen shots:
Pdf printview
![selection_451](https://cloud.githubusercontent.com/assets/4570016/6347267/8a692904-bc3c-11e4-8efa-91e4c8901aa4.png)

Normal  printviewview 
![selection_450](https://cloud.githubusercontent.com/assets/4570016/6347289/bd6bc3c0-bc3c-11e4-9a65-e3ab6bfe5f62.png)

**Comment by umairsy** [comment]
Also Transaction Name (Quotaton) and Id (QTN-00122) is moved from right to left in the print format.

**Comment by rmehta** [comment]
seems fixed

**Comment by anandpdoshi** [comment]
Fixed using https://github.com/frappe/frappe/commit/9ad0af2bac241598be19a56047e836f234c4ec47
