### ISSUE TITLE
incoming call not working

### ISSUE THREAD

**Issue by mohsinalimat** [frappe/erpnext#28518]
incoming call not working and from call log callback not working.

**Comment by bhavesh95863** [comment]
@mohsinalimat  if you can share more details it will be easy to recreate the issue. Recently I implemented it for one of my client and it was working fine.

**Comment by mohsinalimat** [comment]
Incoming call screen not appear and also in console and network debug not found any url.


This is Callback button from call log screen.
https://github.com/frappe/erpnext/issues/28453

**Comment by mohsinalimat** [comment]
I used exotel integration for calling and call log. And what about your integration?

**Comment by bhavesh95863** [comment]
I used same Exotel

**Comment by mohsinalimat** [comment]
> @mohsinalimat if you can share more details it will be easy to recreate the issue. Recently I implemented it for one of my client and it was working fine.

Can you please guide me?

**Comment by mohsinalimat** [comment]
@bhavesh95863 Can you please guide me?

**Comment by mohsinalimat** [comment]
> @mohsinalimat  if you can share more details it will be easy to recreate the issue. Recently I implemented it for one of my client and it was working fine.

@bhavesh95863 I am facing issue in version-13.
