### ISSUE TITLE
When change party then taxes not apply

### ISSUE THREAD

**Issue by komalk1992** [frappe/erpnext#28537]
Hi,

When I change party then taxes and charges not come from item tax template.
This issue is for all transactions (Sales Order, Delivery Note, Sales Invoice, Purchase Order, Purchase Invoice ...... etc.).

**ERPNext: v13.15.0 (HEAD)
Frappe Framework: v13.15.0 (HEAD)**
URL: https://princecare.frappe.cloud

Please check video

![Accounts-Settings-Google-Chrome (1)](https://user-images.githubusercontent.com/85679229/143185470-28ff7866-e6da-464b-a54a-1f7bc7e12d22.gif)

**Comment by deepeshgarg007** [comment]
@komalk1992 I see you are using the tax category so this could be a config issue. Can you please mention the master configuration that you have done and then reopen the issue

**Comment by komalk1992** [comment]
**@deepeshgarg007**  Customer master, supplier master, and address master
