### ISSUE TITLE
[V5] Print Icon visibility issue

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#2853]
Print Icon (to check print preview) doesn't show if I visit same document multiple times. It shows correctly when I reload page. Somewhat same issue exist with Next Step button as well. Attached is the issue found in Purchase Order.

Note: Attached is GIF image. Will take sometime for completing loop.

![print icon](https://cloud.githubusercontent.com/assets/910238/6347883/669b36ca-bc41-11e4-9bf0-ae9dfc637c3f.gif)

**Comment by rmehta** [comment]
related to other client script errors, please post the js trace if you find it again.

**Comment by umairsy** [comment]
please reopen.
