### ISSUE TITLE
Documentation UI broken

### ISSUE THREAD

**Issue by nidhipurohit11** [frappe/erpnext#28542]
Document URL - https://docs.erpnext.com/docs/v13/user/manual/en/customize-erpnext/document-title

![Screenshot 2021-11-24 at 1 38 10 PM](https://user-images.githubusercontent.com/82337328/143199251-652e6699-37b0-4ce3-9a8e-b9447e8302ed.png)

**Comment by hasnain2808** [comment]
@nidhipurohit11 
Nothing's wrong with documentation UI. The image does not exist, just replace it

**Comment by ankush** [comment]
Fixed, also report wiki app related bugs / potential bugs to https://github.com/frappe/wiki
