### ISSUE TITLE
Reports on "Incorrect Data Report" are wrong linked v.13.15.0

### ISSUE THREAD

**Issue by franciscobuendiao** [frappe/erpnext#28569]
## Description of the issue
Links to reports at "Incorrect Data Report" section are wrong linked. On click, instead of show the report, it opens the "Report" **doctype**.

"Stock and Account Value Comparison" it's also at "Other Reports" section.
## Context information (for bug reports)

**Output of `bench version`**
```
ERPNext: v13.15.0 (version-13)
Frappe Framework: v13.15.0 (version-13)
```

### Observed result

![Captura de Pantalla 2021-11-25 a la(s) 20 26 54](https://user-images.githubusercontent.com/25084259/143517770-19765a7f-4e04-44a7-ba52-8fb20ba2e169.png)

![Captura de Pantalla 2021-11-25 a la(s) 20 30 23](https://user-images.githubusercontent.com/25084259/143517845-6fffef81-60e7-4596-b603-2ac363b5f98f.png)

### Expected result
![Captura de Pantalla 2021-11-25 a la(s) 20 31 50](https://user-images.githubusercontent.com/25084259/143517981-37d2f86b-f6b0-4a56-ada2-0179498c8f8c.png)
![Captura de Pantalla 2021-11-25 a la(s) 20 32 04](https://user-images.githubusercontent.com/25084259/143517982-8c7fc82c-11ea-4860-a38c-0bd4e2cc7a8a.png)
![Captura de Pantalla 2021-11-25 a la(s) 20 32 21](https://user-images.githubusercontent.com/25084259/143517983-6d93bd0b-958a-404a-8bf2-e5f59170f33a.png)

**Comment by ankush** [comment]
These links are removed fully from workspace now, they're not used often so not suitable for main workspace of stock. 

https://github.com/frappe/erpnext/pull/28519
