### ISSUE TITLE
Duplicated items in purchase order when getting from material request

### ISSUE THREAD

**Issue by ValentinaPruvost** [frappe/erpnext#28567]
## Description of the issue

When you select more than 1 item from the Material request, they appear in the items table multiplied as many times as items selected. Each item should appear once.

Example: if you select 2 items, they appear twice. If you select 3, they appear three times

![duplicated items when getting from material request](https://user-images.githubusercontent.com/42679775/143460340-76faf60a-9c4a-466e-bcaa-af8668c53826.gif)

It only happens with items from the same Material request.

## Context information (for bug reports)

**Output of `bench version`**
```
erpnext v13.12.1
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by bhavesh95863** [comment]
https://github.com/frappe/frappe/pull/15101
