### ISSUE TITLE
Error thrown for multiple statuses in query 

### ISSUE THREAD

**Issue by yadavyk** [frappe/erpnext#28578]
## Description of the issue

The following error is thrown for multiple statuses in query in Purchase Order Analysis Report 

![image](https://user-images.githubusercontent.com/32797974/143546631-5d3cee3c-5d90-4b15-9926-5842976c2e95.png)

Context information

ERPNext: v13.14.1 (version-13)
Frappe Framework: v13.14.1 (version-13)

**Comment by ankush** [comment]
fixed in latest release: https://github.com/frappe/erpnext/pull/28193
