### ISSUE TITLE
Field not permitted in query: Instructor_name

### ISSUE THREAD

**Issue by staumoepeau** [frappe/erpnext#28587]
## Description of the issue
On the Education Module -> Course Schedule
When you choose an Instructor the Instructor Name will be fetched from the field instructor. The bug occur because it should be lower case **instructor_name** not **Instructor_name** as shown on the screenshot

## Context information (for bug reports)
The fetch field is shown on the pic

https://drive.google.com/file/d/1wUYb_1i2ADVV-17pQxt8YJrzS2or910k/view?usp=sharing

https://drive.google.com/file/d/11uToj81GHYY7TDjZuiebuVjVVoZmhLzR/view?usp=sharing

**Output of `bench version`**
```
erpnext 13.13.0 - 13.15.0
frappe 13.13.0 - 13.15.0

```
## Additional information
I change the Capital **I** on the **Instrcutor_name** to instructor_name and that solves the problem.

**Comment by ankush** [comment]
fixed via https://github.com/frappe/erpnext/commit/ca8dec0cf2d8a74eed1db939f5865f7536431a25
