### ISSUE TITLE
How to use the same batch number on different materials

### ISSUE THREAD

**Issue by JasonFu06** [frappe/erpnext#28591]
Please post on our forums:

for questions about using `ERPNext`: https://discuss.erpnext.com

for questions about using the `Frappe Framework`: ~~https://discuss.frappe.io~~ => [stackoverflow](https://stackoverflow.com/questions/tagged/frappe) tagged under `frappe`

for questions about using `bench`, probably the best place to start is the [bench repo](https://github.com/frappe/bench)

For documentation issues, use the [ERPNext Documentation](https://erpnext.com/docs/) or [Frappe Framework Documentation](https://frappe.io/docs/user/en) or the [developer cheetsheet](https://github.com/frappe/frappe/wiki/Developer-Cheatsheet)

> **Posts that are not bug reports or feature requests will not be addressed on this issue tracker.**

**Comment by ankush** [comment]
This is not supported currently. You'll have to prefix/suffix batch number with some identifier for item. e.g. `BATCH0001-ITEM`
