### ISSUE TITLE
[V5] User able to access records he is not permitted to

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#2860]
Steps:

1. Added a user.
2. Assigned all the roles, except Manufacturing User and Manufacturing Manager.

This user is able to access all the Production Orders.

Note: I temporarily assigned (via Shared With) one Production Order to this user, but then remove remove permission on that Production Order as well.

**Comment by pifiu** [comment]
I would say this is pretty important.

**Comment by rmehta** [comment]
Production Order is also set for Material User. Please check.
