### ISSUE TITLE
Code Refactor and Cleaning

### ISSUE THREAD

**Issue by MahmoudRizk** [frappe/erpnext#28615]
**Is your feature request related to a problem? Please describe.**
Duplicated Code needs to be cleaned.

**Describe the solution you'd like**
Delete the duplicated code.

**Additional context**
Link to the code: https://github.com/frappe/erpnext/blob/2bed4140f33d1160b9b37a3a5c9aac104926d85c/erpnext/hr/doctype/employee/employee.py#L91-L109

**Comment by ankush** [comment]
Since you've identified the issue, would you like to send PR for this as well?
