### ISSUE TITLE
Can´t create new company when installation was run in different language than english

### ISSUE THREAD

**Issue by chrisdent** [frappe/erpnext#28655]
Couldn´t create new company when installation was run in spanish. 

Error: Could find "All departments"

**Comment by sharmanakul** [comment]
hey @chrisdent, I ran the installation in Norwegian and was able to create a new company.
Can you try again and take the screenshot of the console if it still persists for you?

**Comment by sharmanakul** [comment]
closing the issue. feel free to open if it still is a problem.
