### ISSUE TITLE
Can't cancel POS invoice

### ISSUE THREAD

**Issue by kamalghanima** [frappe/erpnext#28652]
when cancel POS Invoice i get this error
![image](https://user-images.githubusercontent.com/55703964/144054499-e65aa966-0847-43e6-9be3-6ebca460835b.png)

console shows this errors
![image](https://user-images.githubusercontent.com/55703964/144054611-ad008a51-9176-479c-a5b1-0f927e594abc.png)

**Comment by harshit-30** [comment]
@nemesis189 can you validate this?

**Comment by sharmanakul** [comment]
i was able to cancel the POS invoice.

**Comment by sharmanakul** [comment]
@kamalghanima can you please reconfirm?

**Comment by sharmanakul** [comment]
@kamalghanima i'm closing the issue, feel free to reopen if it persists.
