### ISSUE TITLE
[V5] When change Language - Internal Server Error

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#2865]
Steps:

1. My Setting
2. Selected language (non-english)
3. Message shows refreshing. And then Internal Server Error shows up.

Error message in the browser console of Firefox.

The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol.

**Comment by rmehta** [comment]
can't replicate
