### ISSUE TITLE
Accounting Onboarding - Buttons with video is showing blank popup 

### ISSUE THREAD

**Issue by nidhipurohit11** [frappe/erpnext#28668]
## Description of the issue
While checking the new onboarding on Accounts module >> "Review Chart of Accounts" and "Updating Opening Balance" shows the "Watch Tutorial" button. When clicked then "Learn more about..." appears, clicking which a popup comes with a blank screen. 

## Steps to reproduce the issue

1. Go to the Accounts module >> Onboarding section will be displayed.
2. Click on "Review Chart of Accounts"/ "Updating Opening Balance"
3. Click on the "Watch Tutorial" button.
4. Below it "Learn more about Chart of Accounts"/ "Learn how to update opening balances" button appears.
5. Click these buttons shows a blank popup.

### Observed result
![Screenshot 2021-12-01 at 4 43 17 PM](https://user-images.githubusercontent.com/82337328/144228779-a2ab4019-7184-44a1-a6af-453bf1c8126a.png)

![Screenshot 2021-12-01 at 4 43 59 PM](https://user-images.githubusercontent.com/82337328/144228798-5554d598-eb56-4a30-aeed-1c067387cb15.png)

### Expected result
These options should show relevant information. 

## Additional information

ERPNext: v13.15.2 (HEAD)
Frappe Framework: v13.15.0 (HEAD)

**Comment by kennethsequeira** [comment]
Looks like this is fixed in:

ERPNext: v13.16.1
Frappe: v13.16.0
![coa-vid](https://user-images.githubusercontent.com/33246109/145969068-1cbc41f6-3345-4910-a1c1-d9e9a15da52f.gif)
