### ISSUE TITLE
Invalid options property given to field "Item Name" in doctype "Packing Slip Item".

### ISSUE THREAD

**Issue by Subramani830** [frappe/erpnext#28694]
Hi All,
I am in the version Frappe: v13.15.0 and Erpnext: v13.15.2.
In the child doctype "Packing Slip Item", the field "Item Name" has the value set for Options  property as "item_code.item_name". 

![image](https://user-images.githubusercontent.com/75359186/144436597-3f6e904c-cbbe-42dc-b257-81e7489d3224.png)

Hence it is not allowing to create a custom field and shows the error "Item Name is an invalid Data field."

![image](https://user-images.githubusercontent.com/75359186/144436310-71125426-0698-4641-81a1-55c455902cb1.png)

Thanks

**Comment by ankush** [comment]
Introduced via https://github.com/frappe/erpnext/pull/14310

value of the option should actually be in fetch_from .
