### ISSUE TITLE
Feature request: Item - Price - Quantity

### ISSUE THREAD

**Issue by ftoth** [frappe/erpnext#2869]
I am still trying to find solution for this: To see in one place Item - default sales price - quantity on default stock
The detailed version could be item - purchase price (average or FIFO) - sales price - quantity on stock - free quantity
This is essential when one should to give sales information on the phone and should make quick decisions.
Or, there might be a report with possibilities to choose price list, warehouse and get item list with possibility to filter item (by ID or name), and to show average purchase price, sales price, quantity and non-reserved quantity.

**Comment by PawanMeh** [comment]
Similar report is available in the latest versions of v10 now, if there are any more gaps you can raise a new issue after trying this report.

![item_price_stock_1](https://user-images.githubusercontent.com/20460498/49210422-12014900-f3e3-11e8-90dc-bc5120c4a830.png)
