### ISSUE TITLE
Duplicate Cards and shortcuts

### ISSUE THREAD

**Issue by sahalMoidu** [frappe/erpnext#28696]
## Description of the issue
Shortcuts and Cards appear twice on subsequent visit of a module page. Given is the example for accounts module
![image](https://user-images.githubusercontent.com/6101879/144541422-7db33b5c-4118-463e-b593-d61717b7c7f4.png)
![image](https://user-images.githubusercontent.com/6101879/144541448-15b65560-f7f1-4b9b-b438-778b378e68f1.png)

## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 13.x.x-develop
frappe 14.x.x-develop
```

## Steps to reproduce the issue

1.Login to erpnext
2.Go to accounting home 
3. Goto another module like HR
4. Return to Accouting home

### Stacktrace / full error message

```
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.
Ubuntu 20.04 , 
ERPNext Easy Install

**Comment by hiteshpaliya22** [comment]
Hey, did you find any solution/workaround for this? I am also facing the same issue. 
I have ERPNext installed using the docker method!

**Comment by hj83** [comment]
Same here, having the same issue. Appreciate if you have any solution for this. thanks

**Comment by sahalMoidu** [comment]
@hiteshpaliya22 , @hj83  if you guys are looking for using erp next in production install the stable version.

This is a bug in dev branch

**Comment by hj83** [comment]
Thanks for your reply! may i know which is the stable version that i should install? was installed with version-13. thanks

**Comment by sahalMoidu** [comment]
The latest stable release is
https://github.com/frappe/erpnext/releases/tag/v13.16.1

**Comment by hj83** [comment]
Thanks! will try it out!

**Comment by sharmanakul** [comment]
I think this is working fine for now. 
Closing it for now, please comment if it still persists.
