### ISSUE TITLE
incorrect google calender syncing issue

### ISSUE THREAD

**Issue by Ambikeygupta** [frappe/erpnext#28707]
Hi,
I connected my Google Calendar with the erpnext account.
Case 1: On the sync calendar, events are getting synced from google calendar to the erpnext account. But the start date and end date are not correct.

Case 2: Event created in erpnext, on sync, created in google calendar as well.
But, if I sync the calendar again from the google calendar list, the events are modified and their start date and end dates are changed to random.

**Comment by PauDur** [comment]
yes, it looks like a bug... https://discuss.erpnext.com/t/incorrect-google-calendar-syncing/79953

**Comment by backendoadmin** [comment]
Sync issue from Google Calendar with wrong from to date&time to ERPNext still occurs. (it uses current date&time)
ERPNext: v14.2.1 (HEAD)
Frappe Framework: v14.9.0 (HEAD)

Full-day event sync works in both directions and event sync from ERPNext to Google Calendar with precise date&time works too.
