### ISSUE TITLE
The text of path is superimposed on each other text of Column in File Manager.

### ISSUE THREAD

**Issue by GoldenScrew** [frappe/erpnext#28706]
## Description of the issue

The text of path is superimposed on each other text of Column in File Manager.

## Context information (for bug reports)

**Output of `bench version`**
```
ERPNext: v13.13.0 (version-13)

Frappe Framework: v13.13.0 (version-13)
```

## Steps to reproduce the issue

1. Go to File Manager ../app/file/view/home
2. Create many subfolders.
3. Let's go to last folder.

### Observed result

The text of path with names of each folder is superimposed on each other text of Column like Size and Created.
![QIP Shot - Screen 087](https://user-images.githubusercontent.com/3992823/144559232-d2c2713b-ee97-40b9-95d8-b0ee13eb8c74.png)

### Expected result

Shortcut name of path.

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

**Comment by yadavyk** [comment]
This seems to be working fine now in V 13.17.0. Can you please update to V 13.17.0 ?
