### ISSUE TITLE
Drag and drop function doesn't work in Course Schedule Calendar

### ISSUE THREAD

**Issue by GoldenScrew** [frappe/erpnext#28727]
## Description of the issue

Try to drag an drop some Course Schedule in Calendar on monthe, week or day.
It is seems like works, but after reloading of page falls into back.

## Context information (for bug reports)

**Output of `bench version`**
```
ERPNext: v13.13.0 (version-13)

Frappe Framework: v13.13.0 (version-13)
```

## Steps to reproduce the issue

1. Go to Course Schedule Calendar /app/course-schedule/view/calendar/default
2. Choose Calendar View.
3. Drag some course schedule and drop it to another time or day.
4. Reload page.

### Observed result

After reloading of page course schedule falls into back.

### Expected result

New time or date should be save in Course Schedule.

### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

https://user-images.githubusercontent.com/3992823/144697982-a83d759c-dae4-4969-96a3-b1d66d3fecdd.mp4

**Comment by Dev-aosama** [comment]
Any Updates in this issue !?

**Comment by mohammedyusufshaikh** [comment]
> Any Updates in this issue !?

Will be raising a fix today

**Comment by GoldenScrew** [comment]
> > Any Updates in this issue !?
> 
> Will be raising a fix today

Still doesn't works on ERPNext: v13.18.0 (version-13), Frappe Framework: v13.18.0 (version-13). I updated for this solution :D

**Comment by ankush** [comment]
I dont think it was backported 😄 

https://github.com/frappe/erpnext/pull/29114 this has no backports.
