### ISSUE TITLE
loan repayment doesn't show in accounting ledger

### ISSUE THREAD

**Issue by sagaaro** [frappe/erpnext#28733]
when i make a loan and repay it from salary the loan repayment doesnt show in accounting ledger and doesnt make an effect

I made loan with term loan type and checked on repay from salary checkbox ... when I make loan repayment and submit it .. it doesn't show in general ledger ... figured out that this repayment doesn't have any gl enties
ERPNext: v13.14.1 (version-13)

**Comment by chrisdent** [comment]
I added a Salary component with formula total_loan_repayment and check the do not include in total. It works. But it substracts the amount of the loan repayment on the Net Pay, giving an incorrect Net Pay. Maybe it would help to add a new field named: Amount Due: where it substracts the total_amount_repayment and Net pay would be the Total salary booked -including loan repayments- for this employee from the beginning of the year (payroll period or fiscal year) up to the current salary slip's end date.
