### ISSUE TITLE
Error: No module named 'redisearch' while installing ERPNext.

### ISSUE THREAD

**Issue by rtdany10** [frappe/erpnext#28730]
**Issue:**
Ran `bench get-app erpnext` and then `bench install-app erpnext`
Cannot install ERPNext.
```
Installing erpnext...
Updating DocTypes for erpnext       : [=================== ] 99%
An error occurred while installing erpnext:
Module import failed for Website Item (erpnext.e_commerce.doctype.website_item.website_item 
Error: No module named 'redisearch')
```

Ran `bench setup requirements` and tried again but to no avail.
Tried installing redisearch via pip(and pip3) in the venv but no effect.
```
frappe@ubuntu:~/frappe-bench$ ./env/bin/pip install redisearch
Requirement already satisfied: redisearch in ./env/lib/python3.7/site-packages (2.0.0)
Requirement already satisfied: redis>=2.10 in ./env/lib/python3.7/site-packages (from redisearch) (3.5.3)
Requirement already satisfied: hiredis>=0.2.0 in ./env/lib/python3.7/site-packages (from redisearch) (2.0.0)
Requirement already satisfied: six>=1.10.0 in ./env/lib/python3.7/site-packages (from redisearch) (1.15.0)
Requirement already satisfied: rmtest>=0.2 in ./env/lib/python3.7/site-packages (from redisearch) (0.7.0)
```

Error log when I try to run the file:
```
frappe@ubuntu:~/frappe-bench$ ./env/bin/python ./apps/erpnext/erpnext/e_commerce/redisearch.py
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/e_commerce/redisearch.py", line 6, in <module>
    from redisearch import AutoCompleter, Client, IndexDefinition, Suggestion, TagField, TextField
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/e_commerce/redisearch.py", line 6, in <module>
    from redisearch import AutoCompleter, Client, IndexDefinition, Suggestion, TagField, TextField
ImportError: cannot import name 'AutoCompleter' from 'redisearch' 
(/home/frappe/frappe-bench/apps/erpnext/erpnext/e_commerce/redisearch.py)
```
At the same time, from inside venv, I can import those without any issues.
```
(env) frappe@ubuntu:~/frappe-bench$ python3
Python 3.7.5 (default, Feb 23 2021, 13:22:40) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import redisearch
>>> from redisearch import AutoCompleter, Client, IndexDefinition, Suggestion, TagField, TextField
>>> exit()
```

**Solution:**
I suspect naming issues. The file is also named redisearch and the package is also named redisearch.

As suspected, the issue was with the name. I renamed the file to `rsearch.py` and tried.
```
frappe@ubuntu:~/frappe-bench$ source env/bin/activate
(env) frappe@ubuntu:~/frappe-bench$ python3 ./apps/erpnext/erpnext/e_commerce/rsearch.py
(env) frappe@ubuntu:~/frappe-bench$ 
```

Runs without any issues.
Please look into this @marination @NagariaHussain @ankush

**Comment by ankush** [comment]
Very similar to https://github.com/frappe/frappe/pull/14093 

Probably just need to rename the file and fix all the references. 

@rtdany10 interested in fixing this? :grinning:

**Comment by rtdany10** [comment]
> @rtdany10 interested in fixing this? grinning

Haha, I was planning to send a fix right away, but [github doesn't tell me where all this file/module is referenced](https://github.com/frappe/erpnext/search?q=redisearch) and I have no idea where all this file is imported or used. I shall open a PR and try rename wherever I find it, but might need help from you guys. :)

**Comment by ankush** [comment]
github is only showing results from `develop` branch. Since this affects v13 only you'll have to search it locally :P 

I think the usage of it is quite limited. Just used in e-commerce search.

**Comment by rtdany10** [comment]
> github is only showing results from `develop` branch. Since this affects v13 only you'll have to search it locally :P
> 
> I think the usage of it is quite limited. Just used in e-commerce search.

In that case, you can unassign @aaronmenezes  
I shall send a PR shortly :smile:
