### ISSUE TITLE
[V5] Alignment of total fields in the form

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#2874]
For the ease of user, we should have total fields of Customer currency and base current consistently on fixed side.

Current Net Total fields are aligned as:

Base currency (Left)............................. Customer Currency (Right)

Tax Totals:

Customer Currency............................. Base Currency

Totals section:

Base Currency.................................... Customer Currency

**Comment by rmehta** [comment]
screenshot?

**Comment by umairsy** [comment]
![screen shot 2015-03-02 at 4 48 30 pm](https://cloud.githubusercontent.com/assets/910238/6439818/becd1d6c-c0fc-11e4-9950-e7ad9d9295d3.png)

![screen shot 2015-03-02 at 4 48 40 pm](https://cloud.githubusercontent.com/assets/910238/6439821/c463601a-c0fc-11e4-822a-b6d292bd2aa5.png)

![screen shot 2015-03-02 at 4 48 48 pm](https://cloud.githubusercontent.com/assets/910238/6439825/cbc5c906-c0fc-11e4-89e7-5bb373c3f05c.png)
