### ISSUE TITLE
Generate Invoice based on Payment Terms

### ISSUE THREAD

**Issue by harshit-30** [frappe/erpnext#28758]
Here are the points to be considered or challenges when creating a payment against a Payment Term:
**Challenge:** 
Since the Amount in the Sales Invoice is determined based on Rate and Qty, in order to do 50% billing for an invoice (for eg.) we will have to set either qty to 50% of rate to 50%. Resetting Qty may not be ideal, as it can lead to an issue if “Update Stock” is also checked. We cannot deliver 0.50 TV. Even now, we change the item’s Qty to get the pending invoice amount in the invoice.

**Payment Terms:**
If an invoice is made against a Payment Term, then there should be no other Payment Term fetched from Sales Order. Currently, we fetch all the payment terms of the sales order into the invoice.

**Benefits**
This design will help us extra a reports like:
**Sales Order pending to be billed for a specific term**
**Sales Order outstanding as per the payment terms**

**Comment by harshit-30** [comment]
@ruthra-kumar working on this?

**Comment by ruthra-kumar** [comment]
@harshit-30 For now, Report has been developed to calculate status of Payment Terms at runtime. You can check the progress https://github.com/frappe/erpnext/pull/29137

**Comment by mhbu50** [comment]
@harshit-30 Any update on this?
