### ISSUE TITLE
[V5] Sales Order to Material Request not working

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#2875]
Following is the result after I click on Make Material Request button in the submitted Sales Order.

![screen shot 2015-02-26 at 5 46 57 pm](https://cloud.githubusercontent.com/assets/910238/6391755/acdc1574-bddf-11e4-8b8d-9783fee05643.png)

**Comment by umairsy** [comment]
Same error when open new "Material Request" form from Buying  >> Material Request  >> New

**Comment by neilLasrado** [comment]
Error message on console - Uncaught TypeError: Cannot read property 'grid' of undefined
