### ISSUE TITLE
Add 'Old Invoice No.' field in Opening Invoice Creation Tool

### ISSUE THREAD

**Issue by harshit-30** [frappe/erpnext#28759]
To record the legacy system's naming series of invoices, Opening Invoice Creation Tool should have the ability to record and generate invoices with the same numbers to ease the reconciliation of payments made and received. 

**Proposed Solution:**
1. Insert a new field called "Old Invoice No." below "Is Opening Invoice" field.
2. Show Old invoice. no. only if Is Opening is "Yes".
3. Add a column (optional) in the Opening Invoice creation Tool for old invoice no.
4. Map the new column with the new field suggested.

**Comment by nemesis189** [comment]
PR for feat: https://github.com/frappe/erpnext/pull/28844

**Comment by nextchamp-saqib** [comment]
Closed with #28844

**Comment by nextchamp-saqib** [comment]
Closed with #28844
