### ISSUE TITLE
[V5] Tax Masters do not accept zero for a rate anymore

### ISSUE THREAD

**Issue by gentle-** [frappe/erpnext#2876]
In order to prefer Item Tax over the 'generic' Tax, one needs to set up 0 as a rate in the Tax Master (both purchasing and sales).

I now find that the Tax Master form does not accept 0 as a rate anymore. Purchasing still has it (for over a week now, and that still works), but it will not accept updates as a new validation pops up to tell me that zero rates are not allowed:

![selection_012](https://cloud.githubusercontent.com/assets/10958563/6399695/764b50a0-bdf4-11e4-9377-1dad861acdb1.png)

Entering the rates, will result in double Tax rates applied to the Sales Order for example and the Item Tax is ignored.

**Comment by gentle-** [comment]
I had to set the rate-column to null in the DB to get the effect I wanted. If I do that, the logic that the item tax will overwrite the tax master still works.

I don't have a good feeling about how this works... A setting that explicitely tells the system to use Item Tax over the Tax Master would be nicer, I guess, although I can't imagine the impact that has on the current logic...

**Comment by gentle-** [comment]
Nope, it didn't work.
When I now want to save the Sales Order, it pops the same pop-up as above. I'm stuck. :(

**Comment by nabinhait** [comment]
Removed the validation.
