### ISSUE TITLE
get_item_details() args.warehouse results in 0 actual_qty when group node is supplied

### ISSUE THREAD

**Issue by dj12djdjs** [frappe/erpnext#28766]
https://github.com/frappe/erpnext/blob/ef53eb7fcda8a58c62a11aef3c8a7dc16f5e3f0b/erpnext/stock/get_item_details.py#L29

If args.warehouse is a group node then https://github.com/frappe/erpnext/blob/ef53eb7fcda8a58c62a11aef3c8a7dc16f5e3f0b/erpnext/stock/get_item_details.py#L988 will return actual_qty 0

# Expected Result
return the sum of projected_qty, actual_qty, and reserved_qty  for all nodes under the specified group.

**Comment by ankush** [comment]
I agree with expected results, I've been meaning to fully allow use of group warehouse in places like sales order / purchase order (as they don't affect stock ledger)

Other than that, do you have any use case where this is required?

**Comment by dj12djdjs** [comment]
For our case, we organize our warehouse like such
```
+-- All Warehouses
      +-- Store 1
             +-- Row
                   +-- Height
                         +-- Bin
      +-- Store 2
             +-- Row
                   +-- Height
                         +-- Bin
     +-- Store 3
             +-- Row
                   +-- Height
                         +-- Bin

```

So when we create a quotation it will default to the item's default location. Which is set to the lowest level where it is easiest for  the picker to grab. For example it will default to Store 1 - 97-07-58 which will have 10pcs. When sales person opens the grid row and will see the actual_qty and projected qty and will note that stock is low and there isn't much qty on order. When in reality there is another 100pcs at Store 1 - 80-24-80 and 200pcs(On Order) in Store 1 - Receiving.

**Comment by ankush** [comment]
Ah, we also have WMS in works that will provide first class support for shelf/rack/bin setup. Anyway, that will take time. In meantime it makes sense to have this.

**Comment by ankush** [comment]
I've done a version of this for e-commerce integrtations, might help: 

https://github.com/frappe/ecommerce_integrations/blob/e12db27931dc553ff14ccfd5622fb40014ddb369/ecommerce_integrations/controllers/inventory.py#L36-L72 


Basically for group warehouse instead of checking `= warehouse` do `in (%s)` with descendants.

**Comment by dj12djdjs** [comment]
bump
