### ISSUE TITLE
Packing List doesn't auto clear on deleting product bundle 

### ISSUE THREAD

**Issue by yadavyk** [frappe/erpnext#28762]
## Description of the issue

On the sales order creation form add a product bundle and save; a packing list appears. Try deleting the product bundle. The packing list doesn't get auto cleared. 

Screen Recording : 

![image](https://user-images.githubusercontent.com/32797974/144848621-5336fe4c-e5fc-4707-8cf7-d6445335746d.png)

### Observed result : 

The packing list still appears even after deleting product bundle. 

### Expected result : 

The packing list should be auto cleared on deleting product bundle. 

## Context Information : 

ERPNext: v13.15.2 (version-13)
Frappe Framework: v13.15.0 (version-13)

**Comment by nextchamp-saqib** [comment]
Does the Packing List table gets cleared on Save? @yadavyk

**Comment by yadavyk** [comment]
> Does the Packing List table gets cleared on Save? @yadavyk

@nextchamp-saqib, here are the cases : 

CASE 1 - In the Items' Table if we have one item and one product bundle and save, packing list will appear. If that product bundle is deleted and then save is hit the packing list will get cleared. 

![Product Bundles case1](https://user-images.githubusercontent.com/32797974/150122266-fdc56e92-ec1d-4485-8020-9098d9d37607.gif)

CASE 2 - In the Items' Table if include one product bundle and hit save, packing list appears. Now delete the product bundle and hit save, the packing list doesn't get cleared. 

![Product Bundles case2](https://user-images.githubusercontent.com/32797974/150122575-add8e29b-c0cb-4044-955a-4d100ba06eef.gif)

**Comment by nextchamp-saqib** [comment]
@yadavyk Okay, seems to be a UX issue, rather than a bug. 

For Case 2:
The same behavior is with Pricing Rule too and more (i guess)
We could fix this by adding JS triggers, but IMO we shouldn't do it since we plan to get rid of JS in the long run. 

@ankush Please comment

**Comment by ankush** [comment]
2nd one is only because save didn't actually happen due to mandatory error.


@nextchamp-saqib Instead of adding more JS 💩 we can call the remote method that's running in `validate`?

**Comment by nextchamp-saqib** [comment]
@ankush I am not sure if I get it,

The `validate` isn't called yet, the "Missing Field" msgprint is a JS validation

**Comment by ankush** [comment]
I meant we can call the method that updates packing list via JS triggers 😅

**Comment by GangaManoj** [comment]
@ankush idk if that's the best idea because that method uses a lot of db calls AND they're all in a loop.

**Comment by deepeshgarg007** [comment]
This looks like an Invalid Issue, closing this
