### ISSUE TITLE
On Job Card, updating the 'Qty To Manufacture' after Material Transfer does reset the Transferred Qty in the Raw Materials table

### ISSUE THREAD

**Issue by guilmori** [frappe/erpnext#28778]
## Description of the issue
On Job Card, updating the 'Qty To Manufacture' after Material Transfer does reset the Transferred Qty in the Raw Materials table

**Output of `bench version`**
```
13.16
```

## Steps to reproduce the issue

1. Job Card 'Qty To Manufacture' is 10
2. Hit Material Transfer button, 
3. Enter 'For Quantity' = 8 and submit stock entry
4. Back in Job Card, 'Transferred Qty' in Raw Materials table shows correct qty for 8 FG
5. Still in Job card, set 'Qty To Manufacture' to 8
6. The Raw Materials table is recalculated and all  'Transferred Qty' is lost

### Observed result
![image](https://user-images.githubusercontent.com/9451512/145071251-4c89653a-2396-42a6-aed3-53335c5d7919.png)

![image](https://user-images.githubusercontent.com/9451512/145071349-387f995d-38a5-42ee-823b-dc0d0d35c6b4.png)

**Comment by sharmanakul** [comment]
@aaronmenezes please check.
