### ISSUE TITLE
[V5] Translation initial login screen

### ISSUE THREAD

**Issue by Steggur** [frappe/erpnext#2880]
With a fresh install of V5.
I finished running the wizard.
Then I am redirected to the login.
http://192.168.10.80/login#login
Some items are correctly translated but others can not be found in the csv files or do not translate.
This is the list of items that can not be found in the csv files for translation.
Contact
Blog
Sign Up / Login
Email address
Sign in
Not a user yet? Sign up
Forgot Password?

**Comment by Steggur** [comment]
Also POS does not translate on main menu

**Comment by rmehta** [comment]
fixed setup wizard. please raise new issue for POS
