### ISSUE TITLE
Adding salary component to salary structure

### ISSUE THREAD

**Issue by mastewalm** [frappe/erpnext#28808]
previously I created a salary component and salary structure and created a salary slip. a new deductible component came into existence in my company and when I want to apply it the system could not allow me. Once a salary structure is submitted and linked it cannot be updated. So, I think there should be a mechanism to add new earnings or deduction.

**Comment by kennethsequeira** [comment]
You just need to create a new salary structure and new assignment rule. 

This is not a bug.

**Comment by mastewalm** [comment]
So every time a new component comes up, I have to create a new salary
structure and a new assignment rule. Is that an efficient way for such a
great system? Isn't there any method to add to an existing one? Or is there
a way to create a formula for salary structure by checking employee grade?
For example, condition: employee grade = L1 then Basic Salary = 2000 in
condition and formula space.

**Comment by kennethsequeira** [comment]
@mastewalm every time there is a salary structure change, you just need to duplicate the existing one and do the assignment. 

Perhaps you should re-word this as a feature request/enhancement then out and out tagging this as a bug

**Comment by mastewalm** [comment]
Thank you for the clarification.
