### ISSUE TITLE
Customer Link Field Need In Work Order

### ISSUE THREAD

**Issue by sowndharya998** [frappe/erpnext#28826]
Need customer field  in Work Order  because is to be easy to filter the customer-related work orders
ERPNext: v13.7.0 (version-13)
Frappe Framework: v13.7.0 (version-13)
![Screenshot 2021-12-11 at 3 37 24 PM](https://user-images.githubusercontent.com/75109236/145672900-81a82a0b-55d8-4db3-8071-8447652ca4ec.png)

**Comment by ankush** [comment]
Can be done easily with customization. 

Add a new field called customer, add `fetch from` that will populate value from Sales Order's field.
