### ISSUE TITLE
[V5] bench frappe --get_untranslated is /home/erp/en runs with error now

### ISSUE THREAD

**Issue by Steggur** [frappe/erpnext#2883]
bench frappe --get_untranslated is /home/erp/en does not work now, worked before on V5.

The error is:
OSError: [Errno 2] No such file or directory: ''/home/erp/frappe-bench/apps/frappe/frappe/desk/report/todo'

**Comment by pdvyas** [comment]
fixed

**Comment by pdvyas** [comment]
fixed
