### ISSUE TITLE
Expense Claim Return Advanced Amount

### ISSUE THREAD

**Issue by Mohd200** [frappe/erpnext#28834]
Good Day Everyone

I would like to request adding an extra feature in Expense Claim, **in the case of Employee Advance paid to Employee**.

Several times, whenever the Employee claims an Employee Advance for expenses purposes, the expenses does not cover the entire Advance Paid Amount, therefore, in this case, the Employee is obligated to return the remaining Advanced Amount after registering all the expenses in the Expense Claim.

Allow me to give a Case Scenario:
Employee received the Advanced payment, which created from Employee Advance, Total of 2500, next, Employee created an Expense Claim to register all the expenses, however, the Total Sanctioned Amount of the expenses equals 1750, less than the Total Advanced Amount. Now, the Employee is obligated to return the remainder of the Advanced Amount, which equals 750. 

The Requested Feature is, a sub-button under "Create" button called "Return". The function of the "Return" button is to create a new Payment Entry, or a new Journal Entry, in purpose of returning the remaining of the Advanced Amount. The new Payment Entry, or new Journal Entry, would be directly linked to the Expense Claim with all of the Employee's details and the payment would automatically summon the remaining of the Advanced Amount from the Expense Claim.

Thank you :)

**Comment by santoshbb** [comment]
This feature is already available, you need to go through "Employee Advance" feature. The return of advance from Employee is  possible from Salary deduction or Journal Entry.

![image](https://user-images.githubusercontent.com/10789840/145705604-7cd1bb6e-6fb1-48d6-ba39-9e84d0223c19.png)

**Comment by Mohd200** [comment]
Thank you for replying @santoshbb 

Regarding the Return button in Employee Advance, it doesn't acknowledge the Expense Claim, meaning if the Expense Claim is submitted, the Journal Entry created from "Return" button summons the entire Advance Amount regardless of the Expense Claim.
As for the repayment from Salary, I'm afraid it's not always practical.
Is there any other solutions ?

**Comment by santoshbb** [comment]
Hi,

Actually the feature is as per your expectation. please consider below snapshots, i have created 20,000 QAR as employee advance, and created expense claim for 3,000 QAR, the balance should be 17,000 QAR, please see the journal entry after I click on Return


![image](https://user-images.githubusercontent.com/10789840/145705942-8fc8e5e9-f725-4784-988b-8dbd22746415.png)


![image](https://user-images.githubusercontent.com/10789840/145705963-44ef9e10-bc4b-423f-bdf4-0189a2452c95.png)

**Comment by santoshbb** [comment]
![image](https://user-images.githubusercontent.com/10789840/145706021-63321247-9e4d-4997-b23b-e709b0db80de.png)

**Comment by Mohd200** [comment]
Thanks again for your help @santoshbb 

Could you show me your Expense Claim page ?
Because I just checked my Employee Advance page and the Claimed Amount is 0.
Could this be a bug in Expense Claim ?

Thank you

**Comment by santoshbb** [comment]
I advise before creating an issue, should be discussed in forum. 
If the "Claimed Amount" in Employee Advance is 0, obviously it will take total amount in return Journal Entry. 

Kindly check if you are deducting advance amount from expense claim,

![image](https://user-images.githubusercontent.com/10789840/145706423-b95608fc-d4ab-4bcf-ad3c-b221ab8113a7.png)
