### ISSUE TITLE
Gross Profit Report incorrect

### ISSUE THREAD

**Issue by vachanlohia** [frappe/erpnext#28837]
### Information about bug

The gross profit report is not coming correct. While matching with the Profit & loss statement - the sales figure is matching item wise, but the COGS isn't matching item wise

### Version

v13

### Module

accounts

### Version

Frappe Framework: v13.16.0 (HEAD)
ERPNext: v13.16.1 (HEAD)

### Installation method

FrappeCloud

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dj12djdjs** [comment]
Might be related to https://github.com/frappe/erpnext/issues/27400 and https://github.com/frappe/erpnext/issues/27297

**Comment by mro-admin** [comment]
created a pull request that can potentially fix it. Still waiting for feedback https://github.com/frappe/erpnext/pull/28724

**Comment by dj12djdjs** [comment]
Same here https://github.com/frappe/erpnext/pull/27420   It's been quite some time. I know this fixed my issue with Gross Profit report.
