### ISSUE TITLE
Opporunity card on home not working 

### ISSUE THREAD

**Issue by rioshaz** [frappe/erpnext#28846]
### Information about bug

when we do a hard reset n then click on opportunity card it doesnt load ,, but if we click on any other card and then come back to home workspace then again click opportunity card it works fine..  

this has happened after the latest update..

console error : 
<img width="661" alt="image" src="https://user-images.githubusercontent.com/54880467/145824880-46eeceb8-0c15-459f-8e41-bd44756e3f27.png">

### Version

v13

### Module

selling

### Version

13.16.01
13.16

### Installation method

manual install

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anupamvs** [comment]
@rioshaz I am not able to replicate the issue.
Can you add GIF/ video? Closing for now.
