### ISSUE TITLE
custom reports deleting

### ISSUE THREAD

**Issue by tatweer2020** [frappe/erpnext#28856]
### Information about bug

Use the Digital Ocean platform, and when creating a custom report, it does not continue to be saved constantly and disappears after a short period

### Version

v12

### Module

buying

### Version

ERPNext: v12.5.0 (version-12)
Frappe Framework: v12.3.0 (version-12)

### Installation method

manual install

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ankush** [comment]
That's very old version. First upgrade and then confirm if bug still exists.
