### ISSUE TITLE
Custom field not updating and populating in reports

### ISSUE THREAD

**Issue by pifiu** [frappe/erpnext#2885]
Steps to reproduce the issue:

New custom field is created:
![1](https://cloud.githubusercontent.com/assets/2664750/6432883/f2a45836-c02e-11e4-9e5e-179213245454.JPG)

Customized "Item Price" form to add field as Data - Tried Read only too.

![2](https://cloud.githubusercontent.com/assets/2664750/6432897/6a0e17d6-c02f-11e4-9bb8-1d77e26d65e6.JPG)

Custom script for doct type "item price" as follows:

![3](https://cloud.githubusercontent.com/assets/2664750/6432910/f0c5b810-c02f-11e4-956a-8620d958ffd2.JPG)

Report showing blank:

![4](https://cloud.githubusercontent.com/assets/2664750/6432945/b909bdc6-c030-11e4-82ab-7ff09b01ca98.JPG)

Detailed view upon entering RFD:

![5](https://cloud.githubusercontent.com/assets/2664750/6432949/cded6ddc-c030-11e4-8219-2833907da731.JPG)

See this thread for initial information: https://discuss.frappe.io/t/custom-field-from-item-in-supplier-price-list/4863

**Comment by rmehta** [comment]
`add_fetch` will only work for new documents (that are created via browser). This is not optimal, but right now thats the design.

**Comment by pifiu** [comment]
so what is the solution?

**Comment by Spicerlad** [comment]
Has this issue been resolved as its important to me at this time.
