### ISSUE TITLE
[v5] Bom - with operations issue

### ISSUE THREAD

**Issue by neilLasrado** [frappe/erpnext#2887]
Case 1:
In BOM doc, with operations does not toggle operations table if raw material is added to the raw material table.

Steps: 
1. Selected 'with operations' in BOM. Operations table appeared. 
2. Added Raw materials in the raw material table.
3. Removed 'with operations' check.
4. Operations table did not disappear.

Case 2:
When 'with operations' was selected in BOM table and a blank row was added before removing check on 'with operations'. Validation errors were raised on save.

Steps:
1. Selected 'with operations' in BOM. Operations table appeared. 
2. Added a blank row (with no data) to operations table.
3. Removed the 'with operations' check. Operations table disappeared.
4. Added raw materials in the raw materials table. Tried saving doc.
5. Validation Errors were raised - operation number, description mandatory(cause- Blank Operation row)
6. Tried 'with operations' to remove the blank row. But operation table did not appear.

**Comment by nabinhait** [comment]
fixed
