### ISSUE TITLE
[V5] Setup Wizard - Uploaded image not showing preview

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#2888]
In the setup wizard, uploaded images in the following link.

1. Profile Image
1. Letter Head
2. Logo

After attaching file, images are not shown in the setup wizard.
![screen shot 2015-03-02 at 12 36 30 pm](https://cloud.githubusercontent.com/assets/910238/6436615/ff545978-c0d8-11e4-9e8f-63ad43a8d320.png)

**Comment by neilLasrado** [comment]
also setup wizard related issue:
https://github.com/frappe/erpnext/issues/2858

**Comment by rmehta** [comment]
fixed
