### ISSUE TITLE
Work Order -> Job Card Time Log Issue 

### ISSUE THREAD

**Issue by sowndharya998** [frappe/erpnext#28897]
Job Card Against Work Order

- WorkOrder Has 10 Qty .
- Bom has 3 Operation and operation batch size 1 and operation time 10min.
- Submit the work order it create 30 job Card.
- In Job Card -> Time Log table->Time In mins was calculate for 10qty operation time for single jobcard.
- Operation Time should calculate  1qty operation time for single jobcard.
![Screenshot 2021-12-16 at 5 46 28 PM](https://user-images.githubusercontent.com/75109236/146370538-996f471f-6d22-4230-97fa-76a251f5a724.png)

![Screenshot 2021-12-15 at 11 51 08 AM](https://user-images.githubusercontent.com/75109236/146370218-5c49ff08-a9a0-435d-b139-6dbe9bc3e9a8.png)
### Information about bug
![Screenshot 2021-12-15 at 11 51 58 AM](https://user-images.githubusercontent.com/75109236/146370327-d40a82c2-e410-40e4-9bed-b83f31d3ecc4.png)

 

### Version

v13

### Module

manufacturing

### Version

ERPNext: v13.16.1 (version-13)

Frappe Framework: v13.16.0 (version-13)

### Installation method

manual install

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by s-aga-r** [comment]
Hi @sowndharya998 

I tried this in v13/14 and the results are different when I submit the Work Order only 3 Job cards get created as I have 3 Operations in the BOM. Please let me know if I missed something.

- BOM

  ![image](https://user-images.githubusercontent.com/63660334/189468613-f13f783c-ac6b-4c62-a241-9534287f4bba.png)

- BOM Operations and Items

  ![image](https://user-images.githubusercontent.com/63660334/189468634-af362d2a-a0c7-4977-aa44-447d608dcb54.png)

- Work Order Operations

  ![image](https://user-images.githubusercontent.com/63660334/189468640-4f225231-7af4-493f-99eb-29395fe7728e.png)

- Job Card Quantity to Produce

  ![image](https://user-images.githubusercontent.com/63660334/189468666-d3478ba6-b6db-4010-9fb4-053bad84e2a7.png)

**Comment by rohitwaghchaure** [comment]
@sowndharya998 by default the batch size is 1 and the BOM you have created to manufacture Single Unit of Finished Goods   therefore system has set the operation time as 100. This is by design and not an issue.
