### ISSUE TITLE
[v5] HR - Salary Slip - calculation error

### ISSUE THREAD

**Issue by neilLasrado** [frappe/erpnext#2889]
In Salary Slip,

In the earnings and deductions table if 'depends on LWP' is checked the amount is reduced. But if it is again unchecked the amount is not Increased.

![screen shot 2015-03-02 at 1 15 40 pm](https://cloud.githubusercontent.com/assets/8401344/6437035/b2c08856-c0de-11e4-982a-b6cfd39bb175.png)
![screen shot 2015-03-02 at 1 16 13 pm](https://cloud.githubusercontent.com/assets/8401344/6437038/bb8cfe24-c0de-11e4-8fe4-061f202d7082.png)
![screen shot 2015-03-02 at 1 16 26 pm](https://cloud.githubusercontent.com/assets/8401344/6437039/c475f220-c0de-11e4-9fcb-e062514ce8f6.png)

**Comment by nabinhait** [comment]
fixed
