### ISSUE TITLE
[v5] HR - Salary Structure Error

### ISSUE THREAD

**Issue by neilLasrado** [frappe/erpnext#2890]
In HR Module salary structure has a from date and to date.
If a salary structure does not exist for a user, system generates Error msg stating please create salary structure first.
But Salary slip can be created for a month beyond the to date of the salary structure

**Comment by nabinhait** [comment]
Add Salary Structure link field to Salary Slip.
In salary slip, first select Month and year, then based on input select Salary structure.
Validate dates and if active.
Salary Structure field should be editable.
