### ISSUE TITLE
Sales and Purchase Invoice >> Should display default warehouses even when update stock is unchecked 

### ISSUE THREAD

**Issue by nidhipurohit11** [frappe/erpnext#28900]
### Information about bug

1. Create a Purchase Invoice, do not check 'Update Stock'
2. Add more than 1 item, and save
3. The 1st item details shows accepted warehouse details, and other items not
4. To avoid the confusion where exactly the item will be accepted, can show Default Warehouse above the item table (as in Sales/Purchase Order)

5. Same for the Sales Invoice form. 

![Screenshot 2021-12-15 at 2 40 18 PM](https://user-images.githubusercontent.com/82337328/146157166-79b42ee1-c14a-476a-9639-7b9fbfb381e8.png)

![Screenshot 2021-12-15 at 2 43 10 PM](https://user-images.githubusercontent.com/82337328/146157613-5f81f609-4499-482e-b0ca-8413c288d21c.png)

### Version

v13

### Module

buying

### Version

ERPNext: v13.16.1 (HEAD)
Frappe Framework: v13.16.0 (HEAD)

### Installation method

FrappeCloud

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deepeshgarg007** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/42651287/201104573-a4d5fad2-51f5-4faa-9313-f415aea61d1e.png">

Checked and all the items had a warehouse set though it's not displayed until the "update stock" is checked.
Showing one default warehouse at the parent might be misleading as different items can have different warehouse
