### ISSUE TITLE
Can't change filter for Purchase Invoice Item expense head

### ISSUE THREAD

**Issue by perotom** [frappe/erpnext#28918]
### Information about bug

The following filter works on the field `discount_account` but not for `expense_account`.

```
frappe.ui.form.on('Purchase Invoice', {
    setup: function(frm) {
        frm.set_query("expense_account", "items", function(doc, cdt, cdn) {
            return {
            	filters: [
            		['Account', 'account_number', '>=', 5000],
            		['Account', 'account_number', '<', 6000],
            		['Account', 'is_group', '=', 0]
            	]
            };
        });
	}
})
```

Anyone an idea what's going on?

### Version

v13

### Module

buying

### Version

ERPNext: v13.15.2 (version-13)
Frappe Framework: v13.15.0 (version-13)

### Installation method

easy-install

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by perotom** [comment]
Seems like after typing it will find the needed items but the initial drop down list contains items outside the filter range.

**Comment by ankush** [comment]
Please don't open issues for customization help. Use https://discuss.erpnext.com/
