### ISSUE TITLE
KSA VAT Report Calculation Error when using tax templetes

### ISSUE THREAD

**Issue by hamzahali** [frappe/erpnext#28915]
### Information about bug

@ahmadpak 
When using tax templetes vat is not being reflected in KSA VAT Reports
<img width="1206" alt="Screenshot 2021-12-16 at 3 05 15 PM" src="https://user-images.githubusercontent.com/2484423/146345994-37fe78fe-766a-420a-a077-2d16f725a692.png">

The Vat comes in Charts of accounts but not in KSA VAT reports, 
It comes only if we select item tax. 

Video
https://www.awesomescreenshot.com/video/6401231?key=3665f063c3ad99fec54a5bf63309e23b

### Version

v13

### Module

regional

### Version

ERPNext: v13.16.1 (HEAD)

Frappe Framework: v13.16.0 (HEAD)

### Installation method

FrappeCloud

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rtdany10** [comment]
@hamzahali I was able to replicate the issue. It seems like you need to provide Item Tax Template in the Item table of Invoice for it to be included in the report(which isn't necessary and should be fixed?).

@ahmadpak

**Comment by ahmadpak** [comment]
It is compulsory to mention Item tax template. Otherwise there will be
conflict in different cases. The report separates information as per the
item tax template. The same item could have multiple tax templates. For
example 15% 5% and 0%
If we do not mention the item tax template we won’t be able to
differentiate it.
Some times the same invoice can have different items with different tax
applications

**Comment by hamzahali** [comment]
@ahmadpak
The rate assigned in the Item Tax Template will get preference over the standard tax rate assigned in the Taxes and Charges table. Ref: https://docs.erpnext.com/docs/v13/user/manual/en/accounts/item-tax-template 


So there should be no conflicts. **Putting item tax templates should not be compulsory, we can add item tax when we need then its different for 15% default.** We should be able to use Sales Taxes and Charges Template because it saves a lot of time, but current programming does not counts it in ksa vat reports. Atleast we can program ksa vat report such that its includes Sales Taxes and Charges Template. Any tip to implement this @ahmadpak thanks in advance 
![Screenshot_2021-12-20-22-52-45-473_com chrome beta](https://user-images.githubusercontent.com/2484423/146808020-639cb5c0-147c-4e0d-824c-8dac5d928032.jpg)

Cc

**Comment by rtdany10** [comment]
.
