### ISSUE TITLE
Not able to view Land category in Agriculture Domain

### ISSUE THREAD

**Issue by amankumar222** [frappe/erpnext#28912]
### Information about bug

Initially, I used to see the land in the agriculture Domain but now there is only Location field and no Land field. Please suggest how can i see the land feature in the agriculture domain.
![issue](https://user-images.githubusercontent.com/67682185/146341010-f82358b1-4e47-4ec0-8faf-91fca31b5d18.PNG)

### Version

v13

### Module

agriculture

### Version

13.14.1
13.14.1

### Installation method

manual install

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ankush** [comment]
You can customize and add it yourself by clicking on "customize" button. 

No one has touched this module in months, it was probably never there and you had it customized.

**Comment by amankumar222** [comment]
Hi Ankush, 
I did try to customize and checked various other means to solve it but couldn't. 
Request you to please take a screenshot of steps to do it or just write it step by step to view the Land unit.
Please help me out here.

**Comment by ankush** [comment]
https://github.com/frappe/erpnext/blob/develop/erpnext/patches/v11_0/merge_land_unit_with_location.py

after v11 land unit and locations are merged

**Comment by ankush** [comment]
use https://discuss.erpnext.com/ for customization queries.
