### ISSUE TITLE
Company is mandatory error on making multiple companies

### ISSUE THREAD

**Issue by hamzahali** [frappe/erpnext#28914]
### Information about bug

Company is mandatory error on making multiple companies
I resolved all by selecting company in each of the charts,
Even if I give user default company, it doesn't work, have to assign company manually to each chart. 
<img width="1301" alt="Screenshot 2021-12-16 at 2 49 53 PM" src="https://user-images.githubusercontent.com/2484423/146343469-4f6f10b8-ef2b-4de5-a48e-9f1a86bcb998.png">
s

It comes on every page that has a chart
Even it comes for every user, but error will be different for them. 
**Company is mandatory**
<img width="1297" alt="Screenshot 2021-12-16 at 2 52 08 PM" src="https://user-images.githubusercontent.com/2484423/146343879-99e3a5e3-52ad-4789-a344-77fba7b8a9ec.png">

Video
Company None not found bug on User restricted to Company.
https://www.awesomescreenshot.com/video/6401268?key=7a245d63b394ec378d5018c0c43ff0df

I resolved all by selecting company in each of the charts, 
Even if I give user default company, it doesn't work, have to assign company manually. 

### Version

v13

### Module

accounts, selling

### Version

ERPNext: v13.16.1 (HEAD)

Frappe Framework: v13.16.0 (HEAD)

### Installation method

FrappeCloud

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rajkis** [comment]
I have had the same issue with ERPNext v14. I went on to select a company name as a default company in ERPNext Settings > Global Defaults > Default Company data field. The error message seems to have disappeared ever since.
