### ISSUE TITLE
[v5] Appraisal & Appraisal Template

### ISSUE THREAD

**Issue by neilLasrado** [frappe/erpnext#2892]
A. Appraisal Template

In Appraisal template value of the field 'total points' always tends to be 100. ( Its sum of Weightage of all KRA which has a validation that it must be 100 ).
Hence storing the value makes no sense. ( suggestion - remove the field)

B. Appraisal

In goals table in appraisal doc, score col is of type currency. hence currency symbol is displayed along with it. It must be float.  

Also score field is editable if doc is submitted. But system generates validation error on update if score is changed.

C. Design Suggestion

We could have a new field similar to slider where user can slide a pointer from left to right based on performance. ( satisfactory to Excellent )

**Comment by rmehta** [comment]
fix it.

**Comment by neilLasrado** [comment]
Will do it !!!
