### ISSUE TITLE
"update items" on orders doesn't update `idx`

### ISSUE THREAD

**Issue by ankush** [frappe/erpnext#28942]
1. create and submit sales order with >2 item
2. drop one of middle items
3. child table index number is wrong.

<img width="129" alt="Screenshot 2021-12-17 at 2 15 28 PM" src="https://user-images.githubusercontent.com/9079960/146515942-c4a65490-1a79-4fc8-911a-b10bb37daece.png">

**Comment by sunnyjain15699** [comment]
Would like to work on this. Can I get the ticket  ?

**Comment by ankush** [comment]
@sunnyjain15699 sure go ahead. 

ref: this function does "update items" 

https://github.com/frappe/erpnext/blob/6eeea0a77a0fbb9d014831250c7f1e917b769903/erpnext/controllers/accounts_controller.py#L1945
