### ISSUE TITLE
Public Attachements are not found (404) when using custom external port

### ISSUE THREAD

**Issue by 0FiRE0** [frappe/erpnext#28971]
### Information about bug

I have encountered an issue of receiving an `HTTP 404 Error Not Found` when loading static assets and attachments (like images ...etc.).
![image](https://user-images.githubusercontent.com/19993814/146843627-e8244f54-aaaf-4e28-a638-bf05e742d474.png)
Even when opening the picture in a seperate browser tab.
![image](https://user-images.githubusercontent.com/19993814/146828348-685d2ee2-10cb-437d-9a54-25c65bd6e7c7.png)

After investigation, it turned out that the issue was caused because of using a custom port in the URL _(port 800 in our case)_, where nginx is resolving the site name as the full hostname with the port number in the file path when selecting the "public" folder:

Snapshot from the nginx configuration file:
![image](https://user-images.githubusercontent.com/19993814/146841881-ead25569-d4ba-44f6-a6be-a66051f26895.png)

_In this case, the resulted file path will be `sites/hello4.local:800/public/files/.....` instead of `sites/hello4.local/public/files/.....`_
The value `$http_host` should be changed to `$host` _(or any other alternative variable)_ in order to eliminate having the `port` number in the folder path when loading the static file.

**Testing:**
As a proof of the solution, I have tried adjusting the `Host` header in the HTTP Request manually from the browser and removed the port number, and the image was loading successfully.

**Before:**
![image](https://user-images.githubusercontent.com/19993814/146842640-f3e82b54-2eda-4c99-b551-f249ea92d417.png)

**After:**
![image](https://user-images.githubusercontent.com/19993814/146842894-3dbe776d-99f4-4909-94ba-522e1a76d479.png)

Thank you in advance for resolving the issue.

### Version

v13

### Module

All (nginx)

### Version

Frappe version - v13.16.0
ERPNext version - v13.16.1

### Installation method

docker

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0FiRE0** [comment]
Just for providing more details, please note that `Port 800` is exposed in the host through Traefik from the `docker-compose.yml` file, and mapped to its internal `Port 80`.
![image](https://user-images.githubusercontent.com/19993814/146844559-b6e5bd39-31b4-49c0-94fa-3bec1acb71f6.png)

**Comment by 0FiRE0** [comment]
Could you please have a look at it.
The solution is already provided in the bug ticket https://github.com/frappe/erpnext/issues/28971#issue-1085277206

**Comment by revant** [comment]
it's part of the container, I'll push a fix soon.
