### ISSUE TITLE
Customer Group based Item Name & Description

### ISSUE THREAD

**Issue by cdiethelm** [frappe/erpnext#28999]
Hello 

### Feature request
A nice feature in the items would be specific customer item names and descriptions which would be used in sales invoice, sales order or quotation. 

### Implementation
A similar but smaller feature already exists in Items -> Customer details but only for reference codes.
My idea would be to extend that with name and description and remove the mandatory mark from the reference code.

Also the current feature doesnt work at the moment with the customer group alone. The customer itself must be inserted.   
![image](https://user-images.githubusercontent.com/46853231/147098871-f4a2a7a6-b182-4c21-8aaf-0120c3850ec2.png)

In the sales invoice, sales offer and quotation, it would look like this:
![image](https://user-images.githubusercontent.com/46853231/147099929-776c11f5-7129-42bf-bb60-702455344ec9.png)

In the current state, the print format has to be modified to show the customer specific reference code. It would be nice if it would copy the customer specific names to the standard item code , name and description in the sales invoice.  
So if a specific item name exists for that customer group, copy it to the sales invoice item name. Else use the default item name. 

### Why

Customers generally dont know the technical names we have. Therefore, we usually simplify them.
Example: 
iPhone 13 (128 GB NvME, Blue, 6.10 ", SIM + eSIM, 12 Mpx, 5G) -> iPhone 13 (128 GB, Blue, 6.10)
Also our descriptions need to be shorter in the sales invoices and usually there is some technical reference in there too which is not needed for sales invoices. 

As this feature is already widely available in other ERPs, I think this would be a great and powerful addition to ERPNext.

**Comment by sharmanakul** [comment]
Hi @cdiethelm , so you are saying if a specific name for an item is provided for a particular customer, then that name should be used in the print formats?
If i could trouble you a bit, could you please create a [discuss](https://discuss.erpnext.com/) post for this and see what the community has to say about it. This will help in validating and prioritizing the feature.

**Comment by cdiethelm** [comment]
Hello @sharmanakul, I ment an item description will be fetched from the item master to the "Sales Invoice" / "Sales Order" / "Quotation" item table. This would be applied for a particular customer or a customer group. (Same functionality as with the Ref Code, extended to more fields). 

Ive just created a discussion for this.
[https://discuss.erpnext.com/t/customer-specific-item-description/84932](https://discuss.erpnext.com/t/customer-specific-item-description/84932)
