### ISSUE TITLE
[V5] Add to Cart button not showing on the website

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#2899]
Steps:

1. Create few items, defined Item Price for them.
2. Following is the shopping cart setting.

![screen shot 2015-03-02 at 5 32 38 pm](https://cloud.githubusercontent.com/assets/910238/6440347/292fc34e-c102-11e4-836b-68b65e0da783.png)

We have value in the item master correctly matching with values in the Shopping Cart Setting. Still Add to Cart button is not shown for the items.

![screen shot 2015-03-02 at 5 20 01 pm](https://cloud.githubusercontent.com/assets/910238/6441978/3bf16ce8-c112-11e4-9ad2-04ae20f52a22.png)

**Comment by anandpdoshi** [comment]
This was fixed
