### ISSUE TITLE
Opening Inovice Creation with Accounting Dimension does not add Accouting Dimension in Sales Inovice.

### ISSUE THREAD

**Issue by nkyadav1** [frappe/erpnext#29002]
### Information about bug

- Add Business Unit
- Add Opening Invoices does not allow to create invoice gives error Business Unit is Required.

### Module

accounts

### Version

Frappe version - 13.16.0
ERPNext Version - 13.16.1

**Comment by sharmanakul** [comment]
Have you added a custom field for business unit in invoice creation tool? is it an accounting dimension? Have you created a corresponding custom field in the sales invoice?

**Comment by nkyadav2** [comment]
@sharmanakul Yes, I have create a new accounting dimension Business unit. 
On Adding Accounting dimension fields gets added in all accounting relatedTransactions and Opening invoice creation tool.

**Comment by nkyadav1** [comment]
It is accounting dimension
