### ISSUE TITLE
Bulk assignment for additional salary

### ISSUE THREAD

**Issue by mastewalm** [frappe/erpnext#29003]
1. If additional salary can have bulk assignment that would make it easier for use 
2. Since salary component is selected when additional salary is created and if there is a formula in the selected salary component why not fetch the amount based on that? why amount mandatory?
3. On user creation or setup, there is select all and unselect all option for Role selection. why not the same option for Module selection? The same for Module Profile list.

**Comment by sharmanakul** [comment]
@mastewalm i'd request you to create separate requests. It helps in categorizing and prioritizing.
