### ISSUE TITLE
Non Stock Items are not filtered correctly in POS

### ISSUE THREAD

**Issue by vr-greycube** [frappe/erpnext#29008]
### Steps to reproduce the issue

Create several service items; Maintain Stock = 0 in Item
Open POS

### Observed result
Few Items with Maintain Stock unchecked are visible in POS item selector. Alternate items i.e. 2,4,6 are not filtered.

### Expected result
All service items except Product Bundle items should be filtered.

### Bug
Cannot remove item from list while iterating the list.

```
def filter_service_items(items):
	for item in items:
```
should be
```
def filter_service_items(items):
	for item in list(items):
```

The same bug is also in these places:

- https://github.com/frappe/erpnext/blob/498d933e9ce7c18d6c595d2e0f575645dc020d81/erpnext/stock/report/stock_ledger/stock_ledger.py#L239
- https://github.com/frappe/erpnext/blob/498d933e9ce7c18d6c595d2e0f575645dc020d81/erpnext/education/doctype/program_enrollment_tool/program_enrollment_tool.py#L47
- https://github.com/frappe/erpnext/blob/498d933e9ce7c18d6c595d2e0f575645dc020d81/erpnext/erpnext_integrations/taxjar_integration.py#L216
- https://github.com/frappe/erpnext/blob/498d933e9ce7c18d6c595d2e0f575645dc020d81/erpnext/payroll/doctype/payroll_entry/payroll_entry.py#L481

### Module

selling

### Version

version-13

**Comment by nemesis189** [comment]
@vr-greycube A request was made to allow non stock items in pos as it was available in previous version, so non stock items might not be filtered at all 
PR: https://github.com/frappe/erpnext/pull/28998
It's not final, needs to be reviewed and improved on.

**Comment by nextchamp-saqib** [comment]
Closed with https://github.com/frappe/erpnext/pull/29556
