### ISSUE TITLE
invoice not getting currency when  created from Subscription base on Subscription Plan Currency

### ISSUE THREAD

**Issue by MohammedAlNazili** [frappe/erpnext#29029]
### Information about bug

After creating a subscription plan based on different company default currency and adding a subscription for customer and price base one price list.
when creating invoices it passes the default currency and the balance show not correct

**Subscription Plan**
![1](https://user-images.githubusercontent.com/56793163/147381493-c23d7d89-1bf2-4d73-91f6-604b5c8db801.png)
**Item Price**
![2](https://user-images.githubusercontent.com/56793163/147381495-d1bb6d49-eeb8-4f4c-b07c-b1cf0582a439.png)
**Sales Invoices**
![3](https://user-images.githubusercontent.com/56793163/147381498-46cde96b-a7ee-4811-81d9-028c6ec85282.png)

### Module

accounts

### Version

ERPNext: v13.17.0 (version-13)

Frappe Framework: v13.17.1 (version-13)

### Installation method

manual install

**Comment by deepeshgarg007** [comment]
Fixed via https://github.com/frappe/erpnext/pull/28916
