### ISSUE TITLE
Can not rename the warehouse

### ISSUE THREAD

**Issue by komalk1992** [frappe/erpnext#29039]
### Information about bug

Hi,

Can not rename the warehouse.
Please add rename option.

Please check and update it.

![warehouse](https://user-images.githubusercontent.com/85679229/147436352-cdf9700e-9999-4ded-ad2b-add9f61a168e.png)

### Module

stock

### Version

Frappe Framework: v13.17.1 (HEAD)
ERPNext: v13.17.0 (HEAD)

URL: https://princecare.frappe.cloud

**Comment by ankush** [comment]
This was intentionally removed. You can cancel transaction and delete warehouse OR transfer stock and disable old warehouse instead of reaming. We'll add a tool to quickly do this in future.

**Comment by dj12djdjs** [comment]
@ankush Is there a link to an issue why this was removed? I've used the warehouse renaming before and I didn't notice it causing any issues.

**Comment by komalk1992** [comment]
**@ankush**  This is not a problem in one warehouse but rename option does not appear in all warehouses.

**Comment by ankush** [comment]
Yes, the warehouse rename option was intentionally removed. Please don't open more issues for this.

https://github.com/frappe/erpnext/pull/28712
