### ISSUE TITLE
[V5] proposal to slightly change the item lay-out on the Purchase Order form

### ISSUE THREAD

**Issue by gentle-** [frappe/erpnext#2904]
Original
![selection_014](https://cloud.githubusercontent.com/assets/10958563/6460048/3d69d308-c194-11e4-9ba1-9756603d6a82.png)

Proposal
![selection_013](https://cloud.githubusercontent.com/assets/10958563/6460052/458659b2-c194-11e4-8bc9-b9aea6cfcf90.png)

By switching the Stock UOM and the Purchase UOM it's more intuitive from a user perspective.
Also: the UOM conversion factor field should not be editable in this form.

**Comment by nabinhait** [comment]
yes... I also noticed that, will fix it.

**Comment by nabinhait** [comment]
fixed the alignment

**Comment by gentle-** [comment]
:+1:
