### ISSUE TITLE
Can't create account

### ISSUE THREAD

**Issue by JasonFu06** [frappe/erpnext#29048]
### Information about bug

When add a child account, system display not company infomation

![image](https://user-images.githubusercontent.com/93484850/147499339-497fa7b8-53a7-4bf7-ab31-b11811f20da9.png)

### Module

accounts

### Version

FRAPPE : 13.17.1
ERPNEXT : 13.17

### Installation method

manual install

**Comment by harshit-30** [comment]
@nextchamp-saqib can you check this?

**Comment by konradbr** [comment]
I am still experiencing this issue in the current version (as of 2023):

`ERPNext: v14.27.3 (version-14)
Frappe Framework: v14.39.0 (version-14)`

A workaround is to use the tree view for the chart of accounts — there adding is possible.
