### ISSUE TITLE
Multi currency payroll entry not working

### ISSUE THREAD

**Issue by dufani1** [frappe/erpnext#29049]
### Information about bug

Multi currency payroll not working we got the message (Please check Multi Currency option to allow accounts with other currency)
Please see attached gif file.

### Module

accounts

### Version

ERPNext: v13.16.1 
Frappe Framework: v13.16.0 
![multi currency payroll issue](https://user-images.githubusercontent.com/23026263/147507356-8390fa6c-526b-458c-8d54-4d573dd9906b.gif)

### Installation method

FrappeCloud

**Comment by ruchamahabal** [comment]
Hello,

It looks like there is some issue in configuration. Even though you have selected a different currency in the payroll entry, all your accounts are in the same foreign currency: salary component accounts, payroll payable, etc.

While making journal entry for salary slip submission it's flagged as multi-currency if any of the accounts have different currency than others.

**Comment by dufani1** [comment]
@ruchamahabal thanks and we are facing this issue in all customers sites... on FC
