### ISSUE TITLE
[V5] Purchase receipt shows two timestamps, saves one.

### ISSUE THREAD

**Issue by gentle-** [frappe/erpnext#2905]
I'm guessing this time stamp is redundant? It doesn't save the bottom one, only the top one is saved...
See Posting Time:

![selection_015](https://cloud.githubusercontent.com/assets/10958563/6460301/4ce0f7a6-c196-11e4-8654-3bbc9e8e6b20.png)

**Comment by neilLasrado** [comment]
Please refresh and check. Cant replicate.

**Comment by gentle-** [comment]
Hmm, I can't reproduce it either anymore... let's close it.
