### ISSUE TITLE
Add 'Pay Now' button to Sales Quote that brings user to creditcard payment screen.

### ISSUE THREAD

**Issue by jevonearth** [frappe/erpnext#2906]
This is a feature request that follows on from, and assumes that  #2090 is implemented.

The request is that we get the same payment flow on Sales Quotes as we would have on Sales Invoices. 
- A sales person sends a quote to a prospect
- The prospect opens the quote (attached PDF, or randomized link to erpnext)
- Prospect wants to proceed so clicks an "Accept& Pay Now" button
- Prospect is taken to a payment form, with quote number reference number, and totals already filled in
- Prospect enters details, clicks pay, credit card is charged
- ERP marks Sales Quote as accepted, and creates a new payment received record.
## Why do this at the quote level? Just send the prospect a Sales Invoice!

Following this thinking, for some types of businesses, they may send many Sales Invoices, and a majority of Sales Invoices will not be paid, which makes the books look bad (high rate of  delinquency). 
Sending a quote, having a prospect email back saying "Yes!" then sending another Invoice adds a lot of friction to the process. The above feature suggestion, I believe, addresses these needs nicely.

**Comment by rmehta** [comment]
We do this all the time. Its a Quote with a print heading "Pro Forma Invoice" unless the payment is made.

**Comment by jevonearth** [comment]
Great, yes 'Pro-Forma' is essentially what we do. Any comment on the appitite to implement this feature @rmehta ?
Let me know if you have any questions about our use case. :)

**Comment by abhijeetramgir** [comment]
How do we do this?

**Comment by gmplab** [comment]
Now erpnext already intergrated with payment method.
