### ISSUE TITLE
[V5] Warehouse were not auto-created for the new account

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#2907]
For account windmills.beta.erpnext.com, Warehouses (stores, Finished Goods , Work in Progress) were not auto-created.

![screen shot 2015-03-04 at 11 24 18 am](https://cloud.githubusercontent.com/assets/910238/6478845/0cc9e6ac-c261-11e4-973b-da0d7a7bb581.png)

Though they were created just fine for eastwind.beta.erpnext.com after Setup Wizard completion, and on creation of new Company.

**Comment by umairsy** [comment]
Country of a company was set as "United States of America". Chart of Account for this Company as 6 core groups.

![screen shot 2015-03-04 at 11 35 08 am](https://cloud.githubusercontent.com/assets/910238/6478928/896698b2-c262-11e4-9850-902a7a9ca970.png)

**Comment by umairsy** [comment]
When creating Warehouse manually, it ask for the Parent Stock Account. It was not set by default was well. When I am trying to create group account for the Stock Asset, following is the error message. It should not ask for the Warehouse when creating Group Account.

![screen shot 2015-03-04 at 11 36 14 am](https://cloud.githubusercontent.com/assets/910238/6478986/9b983e40-c263-11e4-89a1-ad9336314999.png)

**Comment by nabinhait** [comment]
us chart still not verified

**Comment by rmehta** [comment]
@nabinhait remove un-verified charts.

**Comment by nabinhait** [comment]
fixed.
