### ISSUE TITLE
[V5] New Account/Instance - Tax ledgers not created as provided in the Setup Wizard

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#2908]
Company's Country - USA

1. In the Setup Wizard, define tax accounts.
2. In the Chart of Account, ledgers were not created for those tax accounts.

![screen shot 2015-03-04 at 12 01 35 pm](https://cloud.githubusercontent.com/assets/910238/6479147/50ce86aa-c266-11e4-9392-16411b0447c5.png)

**Comment by nabinhait** [comment]
USA chart not finalised... need to identify the tax group

**Comment by nabinhait** [comment]
fixed
