### ISSUE TITLE
Creating Item problem

### ISSUE THREAD

**Issue by forgeturbo** [frappe/erpnext#29091]
### Information about bug

Installed erpnext V13.17.1 twice with Docker. When creating a item there is no module for website showing at the bottom. Can only see show in Hub. 

### Module

ecommerce

### Version

V13.17.1

**Comment by dj12djdjs** [comment]
@forgeturbo At the top of the item page there is an "Actions" button which leads to "Publish in Website" see https://docs.erpnext.com/docs/v13/user/manual/en/e_commerce/website_item

**Comment by forgeturbo** [comment]
Hi,

fount it and works well, thanks for the help.

Regards
Reinier

**Comment by dj12djdjs** [comment]
@forgeturbo Glad to hear that helped. Could you please close the issue?

**Comment by forgeturbo** [comment]
Hi again,

i forgot to ask how i can setup SSL certificate. I installed erpnext with Docker and was easy to do. The problem im finding is on Chrome i am unable to open Erpnext but on Edge browser i have no problems. I am using the production v13.17 currently because i found the developer v13.x.x unstable. I have looked around and they say Certbot cannot be used within Docker so not sure what i can do to set it up.

Again thanks for the help, i am not very good with Ubuntu and setting up Erpnext.

Regards
Reinier

**Comment by dj12djdjs** [comment]
@forgeturbo I've never used docker install. I would recommend looking on https://discuss.erpnext.com/ If you can't find what you're looking for just make a post. https://discuss.erpnext.com/ along with https://t.me/erpnexthelp are the best places to find help.

**Comment by forgeturbo** [comment]
Hi,

thanks will do so.

Regards
Reinier
