### ISSUE TITLE
Auto GST Setup for new company`

### ISSUE THREAD

**Issue by harshit-30** [frappe/erpnext#29106]
### Information about bug

Only for India domain: 

If we create any transaction after tagging item tax template to an item, by default all the 9 ledgers get added in the taxes and charges section. In order to resolve this, we need to currently go to accounts setting, enable and disable 'Automatically add taxes and charges from Item tax template'. 

Please make it default for the Indian region to avoid this step.

### Module

accounts

### Version

13

### Installation method

FrappeCloud

**Comment by nextchamp-saqib** [comment]
Auto Fetching of Taxes is already turned off for Indian customers

https://github.com/frappe/erpnext/blob/498d933e9ce7c18d6c595d2e0f575645dc020d81/erpnext/regional/india/setup.py#L1038

cc: @deepeshgarg007

**Comment by nextchamp-saqib** [comment]
"Automatically add taxes and charges from Item tax template" is already disabled for new accounts
