### ISSUE TITLE
UAE VAT Settings >> Account heads of other companies are also getting displayed 

### ISSUE THREAD

**Issue by harshit-30** [frappe/erpnext#29109]
### Information about bug

UAE VAT Settings >> Selected a company
On searching for its account heads, other companies heads are also shown in dropdown

![image](https://user-images.githubusercontent.com/46772424/147921466-c953fc08-21a2-473f-9323-b689dc564e70.png)

### Module

accounts

### Version

13

### Installation method

FrappeCloud

**Comment by rtdany10** [comment]
Similar issue for KSA. Addressed via #29121
