### ISSUE TITLE
[13.17] [KSA VAT] [Saudi Arabia] QR-Code not generating even after submission of Invoice

### ISSUE THREAD

**Issue by nasirrr** [frappe/erpnext#29116]
### Information about bug

QR Code is not generating after updating ERPNext from v13.16.2 to v13.17

The QR field remains as shown below. 
![image](https://user-images.githubusercontent.com/93313345/147952886-250b9840-9ed6-4b2c-854c-86076a284164.png)

Steps to Reproduce - 

Install ERPNext 13.16.2
Create a company with Saudi Arabia as country.
Update to version ERPNext 13.17.0
Create Invoice
Submit

### Module

accounts

### Version

![image](https://user-images.githubusercontent.com/93313345/147953005-ce78f4b5-252c-47bf-b71f-81f24843ba04.png)

### Installation method

FrappeCloud

**Comment by nasirrr** [comment]
@rtdany10 Perhaps can you have a look at it? Maybe PR [#28799](github.com/frappe/erpnext/pull/28799) caused this?

**Comment by rtdany10** [comment]
@nasirrr this seems to be a custom print format. Make sure you use the correct fieldname. Fieldname was changed in last update.

Can you also share the screenshot of standard KSA VAT print format?

**Comment by nasirrr** [comment]
> @nasirrr this seems to be a custom print format. Make sure you use the correct fieldname. Fieldname was changed in last update.
> 
> Can you also share the screenshot of standard KSA VAT print format?

I was using a custom print format and fieldname was the culprit. Changed it and works flawlessly. Thanks @rtdany10 
Attaching the Standard KSA VAT print format for your reference. 

![image](https://user-images.githubusercontent.com/93313345/148016656-3686488a-5352-4091-9086-912d37db2737.png)
