### ISSUE TITLE
Items keep adding into the cart even if they are not available in stock

### ISSUE THREAD

**Issue by harshit-30** [frappe/erpnext#29111]
### Information about bug

Steps to Reproduce:

Go to point of sale.
Add items into the cart.
Notice if the available quantity of the item is 2 it will still keep on adding the item in the cart. (It gives an error but increases the number of item in the cart).

Expected Result:
Although we are getting the error, the item gets added in the cart.If the item is not available it should not get added in the cart as well.

Refer SS:

![image](https://user-images.githubusercontent.com/46772424/147924037-3aa672e3-19fd-44ab-98cc-eee0b31494a8.png)

### Module

accounts

### Version

13

**Comment by nemesis189** [comment]
Fix PR: https://github.com/frappe/erpnext/pull/29126
