### ISSUE TITLE
Issue with Coupon Code Renaming 

### ISSUE THREAD

**Issue by harshit-30** [frappe/erpnext#29123]
### Information about bug

As per explanation: 
The Coupon Code field here is not updated when the form is updated.
Fix this.
If it is intentional, change description.
![image](https://user-images.githubusercontent.com/46772424/148031675-9a04b5eb-eeea-46aa-991c-f4249bdd72fd.png)

Issue : When a coupon code is renamed via Edit button from list view the name isn't updated on the coupon code page. Also on the coupon code page, the name field isn't editable. User can't edit the name of the coupon code from the form, it can only be done via Edit right now. 

Steps to reproduce : 

Open an existing coupon code or create one
Try renaming the coupon code

Observed Result : The coupon code name doesn't get updated on the form.

Expected Result : The coupon name should get updated on the form upon renaming and to rename the coupon code the coupon code field on the form should be made editable.

### Module

selling

### Version

13

**Comment by nextchamp-saqib** [comment]
This is not replicable. Please post a Gif if it is replicable

@harshit-30 @yadavyk

**Comment by yadavyk** [comment]
@nextchamp-saqib , please find below GIF : 

![image](https://user-images.githubusercontent.com/32797974/149128934-c11d7cd8-9155-4dc9-8046-f06ce012debd.png)

**Comment by harshit-30** [comment]
@yadavyk your GIF doesn't work for me.
