### ISSUE TITLE
Taxes from Item Tax Templates does not get calculated and added to the document.

### ISSUE THREAD

**Issue by harshit-30** [frappe/erpnext#29122]
### Information about bug

Steps to Replicate:
Item should not have any item tax template assigned.
Create a Sales Invoice/ Purchase Invoice/ Purchase Order/ Sales Order.
Select the item and edit row and add any Item Tax Template for that particular Item.
Even after Saving the Taxes are not added.

Expected Result:
Taxes should be calculated and added in the document.

Refer the screen recording attached.
![image](https://user-images.githubusercontent.com/46772424/148027987-88a4cadd-68c7-4714-b794-3e77706e1df4.png)

![image](https://user-images.githubusercontent.com/46772424/148028012-0c9ead9a-1187-4537-91ff-bb1da541ea52.png)

### Module

accounts

### Version

13

**Comment by nitniyo** [comment]
Hey Team any update when will this be released ?
