### ISSUE TITLE
Stock Entry : Transfer of Warehouse information to Child table is broken

### ISSUE THREAD

**Issue by johnlongland** [frappe/erpnext#29157]
### Information about bug

Stock Entry

When entering items manualy by using a mouse and clicking on the item field all is working well.
The problems start when using a barcode scanner
I did the following tests:

Test 1 (no barcode scanner)
Create New Stock Entry
Complete Warehouse fields
This auto-completes the first row of Item Table
Click on Item field and complete Item code. Detail is fetched
Click Add Row button. This auto-completes the next row with Warehouse information. Click on Item Code and
enter detail. Detail is fecthed
All seem to be working well

Test 2 (no barcode scanner)
Clear Item Table:
Click on Add Row. Warehouse info is NOT auto-loaded into first row BUT
when I click on the Item Code column, it auto-loads the Warehouse info.
From here on the same as Test 1

The problem is when using barcode scanner
Test 3 (barcode scanner)
Create New Stock Entry
Complete Warehouse info
First row of Item Table is auto-completed with Warehouse Info
Scan Item barcode. It fetches info and completes entries in table row
Scan 2nd Item : Only Item detail is loaded into the second row, no warehouse info
Scan 3rd Item : Only Item detail is loaded into the 3rd row , no warehouse info

Test 4 (barcode scanner)
Clear Item table
Click Add Row : No warehouse info is loaded into the first row
Scan 1st Item : ALL item info PLUS warehouse info is auto-loaded into the row
Scan 2nd Item : Only Item detail loaded but no warehouse detail
Scan 3rd Item : Only Item detail loaded but no warehouse detail

Test 5 (barcode scanner)
Clear Item table
Click Add Row : No warehouse detail loaded into first row
Scan Item : ALL item detail PLUS warehouse detail is loaded
Click Add Row : warehouse detail is auto loaded
Scan Item ; Item detail is added to warehouse detail in row on table
Click Add Row : warehouse detail is auto loaded 
Scan Item : Item detail added to warehouse detail 

Remarks:
I only have experience in C-code so I am still struggling with JS/Python, but I had a look at the code.
With my limited knowledge it seems that the problem could be solved if an additional trigger entry
can be made, because when the warehouse info is transfered , it does it correctly. Its just that it doesn't always 
happen. I tried copying some code around in an effort to create that trigger, but it did more harm than 
anything and that is because of my lack of experience. I did have backups of the files, so all is good.

I was looking at the following triggers: ( in stock_entry.js)
set_warehouse_in_children
scan_barcode

### Module

stock

### Version

ERPNext: v12.26.0 (version-12)

Frappe Framework: v12.23.0 (version-12)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
No Error messages and no log-entries.
Just incorrect behaviour observed
```

**Comment by ankush** [comment]
I know this one. Current solution is to enter the warehouse info after all items are scanned. This doesn't increase the work, just reorders it 😅 

code for reference:

https://github.com/frappe/erpnext/blob/06ff6b374ae028dc92e7e209fbca6d181ede9a6f/erpnext/public/js/controllers/transaction.js#L372-L394

**Comment by ankush** [comment]
fixed in https://github.com/frappe/erpnext/pull/30445 

specifically this commit: https://github.com/frappe/erpnext/pull/30445/commits/95e38b8b1cec64aac9e7abd56f0bdbfb38011bb9
