### ISSUE TITLE
Payment Entry cancellation gives error 'Docytype Bank Reconciliation not found'

### ISSUE THREAD

**Issue by nakul80** [frappe/erpnext#29164]
### Information about bug

Payment Entry cancellation gives error 'Docytype Bank Reconciliation not found'

I have recently moved from v12 to v13.

![22-01-05 10_54_12-Shree Ganesh Services - MI_PAY_2201_0010](https://user-images.githubusercontent.com/64956588/148494107-7491bf90-a087-43ea-ba8d-d7f08c35df04.png)

### Module

accounts

### Version

Frappe Framework v13.17.1

ERPNext v13.17.0

### Installation method

FrappeCloud

**Comment by nakul80** [comment]
Didnt get any reply from frappe or community. Tried an alternative method which actually worked but im not sure if its the best option. I couldnt wait any longer as it was concerning bank entries.

So, I duplicated the 'Bank Reconciliation Tool' Doctype into 'Bank Reconciliation' Doctype. This helped skip this error. I think its a bug due to change in BR backend between v12 and v13. 

Hope frappe team to check this out and resolve.
@frappe-bot @umairsy

**Comment by umairsy** [comment]
@sharmanakul @harshit-30 can you try and replicate this please?

**Comment by sharmanakul** [comment]
@umairsy @nakul80 just checked it on v13.17 and I was able to cancel the payment entry.

**Comment by harshit-30** [comment]
@nakul80 can you please share the steps on how we can replicate this?

**Comment by nakul80** [comment]
this is what happened in my case:-

   1. My accounts person made a mistake by showing a cheque payment to a
   vendor but debited and credited the same bank ledger.
   2. The weird thing is that the vendor balance got adjusted and bank
   balance remained the same.
   3. So when he tried to cancel it gave the error which is displayed above.
   4. I thought that since the old doctype name was Bank Reconciliation,
   cancellation of payment entry looked for this doctype and threw this error.
   5. I couldn't find the code wherein cancel function of payment entry
   refers to doctype Bank Reconciliation
   6. After waiting for a few days where my bank account was unbalanced, I
   opened DocType list, chose Bank Reconciliation Tool and duplicated it from
   the menu and named as Bank Reconciliation.
   7. After this I was able to cancel the Payment Entry.
   8. Currently, I still have that duplicated Doctype and I have not tried
   deleting it and cancelling payment entries.


Regards,
Nakul
