### ISSUE TITLE
During submit of purchase receipt make_item_gl_entries assumes negative stock is sold.

### ISSUE THREAD

**Issue by dj12djdjs** [frappe/erpnext#29162]
### Information about bug

**Overview**
While creating GL entries for Purchase Receipt, it is possible for a "divisional loss adjustment" to be made.
If the Purchase Receipt Item is being posted into a Warehouse with negative stock,  _assuming the negative stock has been sold_ the difference is posted to COGS. 

**Steps to Reproduce**
1. Stock Valuation Method: Moving Average
2. Allow Negative Stock
3. Receive 1pc into Warehouse A at $10.00
4. Material Transfer 2pc from Warehouse A to Warehouse B (This will leave Warehouse A with -1, and Warehouse B with 2)
5.  Receive 2pc into Warehouse B at $20.00

You will see in General Ledger the $10.00 difference will be posted to COGS even though these goods haven't been sold.

**Source of Posting**
https://github.com/frappe/erpnext/blob/498d933e9ce7c18d6c595d2e0f575645dc020d81/erpnext/stock/doctype/purchase_receipt/purchase_receipt.py#L357-L382

**Other Info**
I know it doesn't make sense to transfer stock that will make warehouse negative, this is only to replicate the bug.
I found it because most of the time our staff will post to Receiving warehouse when shipment is received. Then warehouse workers will create material transfers into the corresponding location as they stock the received goods.
The problem occurs when office staff notices they made a mistake in purchase receipt, they cancel it, make the amendments. If the user doesn't check "Edit Posting Date and Time" before the form is saved the stock will be posted into Receiving Warehouse after the other material transfers resulting in negative stock values. Therefor posting the difference into COGS.

### Module

accounts

### Version

ERPNext: v13.17.0 (HEAD)
Frappe Framework: v13.17.1 (HEAD)

### Installation method

FrappeCloud

**Comment by Nihantra-Patel** [comment]
Kindly upgrade to version 15, then refresh and check again because lots of bugs fixed in the new version.
