### ISSUE TITLE
SN's auto fetch ignores batch number 

### ISSUE THREAD

**Issue by ghost** [frappe/erpnext#29160]
### Information about bug

Auto fetch for serial numbers in delivery note(not tested for other docs) does not include(ignores) batch number in search.

So, I have an item(batch and sn are turned on). Qty of the item is separated in two batches since item was manufacuted in two series. Half SNs belong to batch A, other half belong to batch B, but they are on same warehouse.

In delivery note I want to include whole qty and since item has two batch numbers, I have to insert same item twice.
For first row(table Items in delivery note) I choose batch A and in serial number part I click on auto fetch. System fetches serial numbers that belong to batch A - **that's okey**.
In second row I choose batch B and click on auto fetch button. System ignores batch number and selects serial numberbs that belong to batch A - **that's wrong**.

This bug is pain in the ass with large number of batches and serial numbers.
Since serial number is unique, why batch number is needed for items with SN?

### Module

stock

### Version

ERPNext: v12.22.0 (version-12)
Frappe Framework: v12.19.2 (version-12)

### Installation method

easy-install

**Comment by sharmanakul** [comment]
Validated on latest version as well:
Selected the batch in the child table:
![image](https://user-images.githubusercontent.com/88872881/148334072-fcffb646-54e6-4a6f-b21a-15c356aaab44.png)
Fetched the serial numbers: (note that there is no info on batch)
![image](https://user-images.githubusercontent.com/88872881/148334134-f80c9d30-b6dd-4dec-91bb-ec38826f6a05.png)
CLicked on insert, the batch number is changed.
![image](https://user-images.githubusercontent.com/88872881/148334195-ec5825fc-8458-4d75-b149-8e32a4f7fea6.png)

**Comment by sharmanakul** [comment]
Validated on the latest version.

**Comment by ghost** [comment]
When it will be released?

**Comment by ankush** [comment]
This was released a while back in v13, won't be ported to v12 now.

**Comment by ghost** [comment]
> This was released a while back in v13, won't be ported to v12 now.

Lol, I reported for v12. Why it won't be ported?

**Comment by silvio3105** [comment]
> This was released a while back in v13, won't be ported to v12 now.

Why?

**Comment by silvio3105** [comment]
Can someone port this back to v12?

**Comment by silvio3105** [comment]
?
