### ISSUE TITLE
[V5] Calender Event should coloured based on Event Type

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#2917]
As per current version:

Public Event - Green
Private Event - Blue

In V5:

![screen shot 2015-03-04 at 2 21 32 pm](https://cloud.githubusercontent.com/assets/910238/6480482/34048e5c-c27a-11e4-925d-8ffcbd4e5c8a.png)

**Comment by RealDesignGraphics** [comment]
Any chance we can get manufacturing events to also show on the calendar?

**Comment by neilLasrado** [comment]
@RealDesignGraphics  Yes .... This feature is introduced in v5.
