### ISSUE TITLE
Money exchange rate precision 

### ISSUE THREAD

**Issue by dofrance** [frappe/erpnext#2918]
The system not allow precision of exchange rate more than 3, some currency need more than 3
Already adjust Setup -> Customize Form -> Currency Exchange -> field -> Exchange rate -> precision: 9 => not work
https://discuss.frappe.io/t/money-exchange-rate/4941/6

**Comment by nabinhait** [comment]
Allowed Exchange rate upto 9 decimal

**Comment by dofrance** [comment]
It not work for V5 Beta

**Comment by dofrance** [comment]
It still not work for V5

**Comment by nabinhait** [comment]
Can't replicate in our test account. May be you should delete all "Property Setter" record for "exchange rate" field.

**Comment by dofrance** [comment]
Hi Nabinhait,
Where can I delete that? thank you
