### ISSUE TITLE
Make Leave Policy renamable

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#29190]
Please have Leave Policy doctype as renamable.

**Comment by sharmanakul** [comment]
@muchai would you like to elaborate it? I want to understand the rationale for doing so. Please help me in understanding how it would be beneficial to the users

**Comment by muchai** [comment]
Let me explain with an example.
**The Leave Policy below, is meant for the gender that would be entitled to Paternity Leave, besides other Leaves.**
![image](https://user-images.githubusercontent.com/1822868/149546634-51276af1-c9a1-43e8-8d41-c9273d3fccf9.png)

**The Leave Policy below, is meant for the gender that would be entitled to Maternity Leave, besides other Leaves.**
![image](https://user-images.githubusercontent.com/1822868/149546736-c138f693-2f0f-4bae-a896-151c845b5192.png)

At the time of leave policy assignment, it becomes a bit difficult to differentiate which is which, as below. A rename enables a user to use a more descriptive name. One can add a descriptive name via a custom field. You see the problem though. Probably introduce a Description field instead of enabling renaming.
![image](https://user-images.githubusercontent.com/1822868/149547257-3cbee21f-6d5d-4460-8324-0f6484e58a65.png)

**Comment by sharmanakul** [comment]
you can use a little bit of customization here through Customize Form.
Add a custom field in leave policy, say, Leave policy name, 
![image](https://user-images.githubusercontent.com/88872881/149713296-0a71cc5a-d018-4455-8fbb-4130fe494994.png)

and also add that to the view settings 
![image](https://user-images.githubusercontent.com/88872881/149713359-9ab95669-5229-4b97-8f0c-63f5851c6b6b.png)
 this improves your list view as well. 
![image](https://user-images.githubusercontent.com/88872881/149713428-29824b71-1814-4cf4-b353-18d65bd60a3f.png)

Now, when you go to Leave Policy Assignment, you can distinctly identify your leave policies
![image](https://user-images.githubusercontent.com/88872881/149713545-79282d35-cece-47c0-b04a-52e2d94a9d3d.png)

I hope this helps.

**Comment by sharmanakul** [comment]
i'm also closing it, feel free to reopen if this didn't serve your purpose.

**Comment by muchai** [comment]
This is normally what we do. Add a custom field. This has to happen for every new site though. Please consider to have such a  field as part of standard fields.
