### ISSUE TITLE
Invoice's Exchange Rate value inconsistent with franfurter's API one

### ISSUE THREAD

**Issue by tantoinet** [frappe/erpnext#29198]
### Information about bug

On an invoice date of 2021-04-07, posting time 00:00:00, company's currency GBP and invoice's currency EUR, the fetched exchange rate is 0.864280000.
However, calling the frankfurter's API (https://api.frankfurter.app/2021-04-07?from=EUR&to=GBP) returns: {"amount":1.0,"base":"EUR","date":"2021-04-07","rates":{"GBP":0.86065}}

Changing invoice's currency to USD leads to the same issue (ERPNext fx 0.728089000 whilst frankfurter's one is 0.72421)

Note: Accounting -> Multi Currency -> Currency Exchange and Exchange Rate Revaluation are left empty (default system install)

### Module

selling

### Version

ERPNext: v12.28.0 (version-12) + 13.18
Frappe Framework: v12.25.0 (version-12)

### Installation method

docker

**Comment by kennethsequeira** [comment]
This is not a bug. 

The API was changed from Frankfurter to Exchangerate.host. 

https://github.com/frappe/erpnext/blob/54cb62c7bfa91e5452412c05be2650169f6f7b65/erpnext/setup/utils.py#L101

Ref: https://github.com/frappe/erpnext/pull/26763

**Comment by ankush** [comment]
Also now it's configurable from currency exchange settings!

@tantoinet @kennethsequeira
