### ISSUE TITLE
ZeroDivisionError: float division by zero on the POS

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#29192]
### Information about bug

![image](https://user-images.githubusercontent.com/1822868/148537085-eeb90613-5222-41c2-9a4c-b756a030b580.png)

### Module

accounts

### Version

ERPNext: v13.18.0 (version-13)
Frappe Framework: v13.18.0 (version-13)

### Installation method

easy-install

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 68, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 67, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1208, in call
    return fn(*args, **newargs)
  File "apps/erpnext/erpnext/selling/page/point_of_sale/point_of_sale.py", line 115, in get_items
    item_stock_qty = get_stock_availability(item_code, warehouse)
  File "apps/erpnext/erpnext/accounts/doctype/pos_invoice/pos_invoice.py", line 481, in get_stock_availability
    return get_bundle_availability(item_code, warehouse)
  File "apps/erpnext/erpnext/accounts/doctype/pos_invoice/pos_invoice.py", line 492, in get_bundle_availability
    max_available_bundles = available_qty / item.qty
ZeroDivisionError: float division by zero
```

**Comment by Hafnianusha** [comment]
> ### Information about bug
> 
> ![image](https://user-images.githubusercontent.com/1822868/148537085-eeb90613-5222-41c2-9a4c-b756a030b580.png)
> ### Module
> 
> accounts
> ### Version
> 
> ERPNext: v13.18.0 (version-13) Frappe Framework: v13.18.0 (version-13)
> ### Installation method
> 
> easy-install
> ### Relevant log output / Stack trace / Full Error Message.
> 
> ```shell
> Traceback (most recent call last):
>   File "apps/frappe/frappe/app.py", line 68, in application
>     response = frappe.api.handle()
>   File "apps/frappe/frappe/api.py", line 55, in handle
>     return frappe.handler.handle()
>   File "apps/frappe/frappe/handler.py", line 31, in handle
>     data = execute_cmd(cmd)
>   File "apps/frappe/frappe/handler.py", line 67, in execute_cmd
>     return frappe.call(method, **frappe.form_dict)
>   File "apps/frappe/frappe/__init__.py", line 1208, in call
>     return fn(*args, **newargs)
>   File "apps/erpnext/erpnext/selling/page/point_of_sale/point_of_sale.py", line 115, in get_items
>     item_stock_qty = get_stock_availability(item_code, warehouse)
>   File "apps/erpnext/erpnext/accounts/doctype/pos_invoice/pos_invoice.py", line 481, in get_stock_availability
>     return get_bundle_availability(item_code, warehouse)
>   File "apps/erpnext/erpnext/accounts/doctype/pos_invoice/pos_invoice.py", line 492, in get_bundle_availability
>     max_available_bundles = available_qty / item.qty
> ZeroDivisionError: float division by zero
> ```

has this fixed? i am getting the same error
