### ISSUE TITLE
Unable to log in help requests

### ISSUE THREAD

**Issue by parthmhjn2** [frappe/erpnext#29202]
### Information about bug

While raising a ticket, it gives the following result ->

```
Invalid Date
None is not a valid date string.
```

However there is no date paramterer here.

![Date](https://user-images.githubusercontent.com/17584928/148673223-5643d1a1-4a74-4681-b267-349f7e2d4b00.png)

### Module

accounts, stock, buying, selling, ecommerce, manufacturing, HR, projects, support, assets, integrations, quality, regional, portal, agriculture, education, non-profit

### Version

Installed Apps
Ecommerce Integrations: v1.5.0 (HEAD)

ERPNext: v13.17.0 (HEAD)

ERPNext Support: v0.2.1 (master)

Erpnext Telegram Integration: v1.0.1 (HEAD)

Frappe Framework: v13.17.1 (HEAD)

PDF on Submit: v13.2 (version-13)

POS Awesome: v3.1.1 (HEAD)

### Installation method

FrappeCloud

**Comment by harshit-30** [comment]
@parthmhjn2 please reach out to the Frappe team for this, this bug is from the private repo and the community can't help you here.
