### ISSUE TITLE
Bug - Workspace shortcuts dont show color for filtered value

### ISSUE THREAD

**Issue by rioshaz** [frappe/erpnext#29206]
### Information about bug

When making shortcuts in the workspace the color field doesn't work..
<img width="785" alt="image" src="https://user-images.githubusercontent.com/54880467/148704622-3c6f08e3-8efe-429f-9c10-b325e187a043.png">

the color dosnt show up...
<img width="742" alt="image" src="https://user-images.githubusercontent.com/54880467/148704639-7af4b0cd-5fb6-49b1-afaa-d6943bfcf338.png">

### Module

selling

### Version

13.9
13.9

**Comment by vandarkent100** [comment]
Any updates on this?
Seems like the issue is still ongoing.
