### ISSUE TITLE
We can not delete Product Bundle

### ISSUE THREAD

**Issue by dufani1** [frappe/erpnext#29215]
### Information about bug

We can not delete Product Bundle
ERPNext v13.17.0 

### Module

stock

### Version

ERPNext v13.17.0 

![product bundle issue](https://user-images.githubusercontent.com/23026263/148763033-9ea243ba-d539-4d75-8ff6-3768040b8899.gif)

**Comment by ankush** [comment]
Not enough info, why you can't? what error message are your getting?

**Comment by dufani1** [comment]
@ankush please help we just test the product bundle but when we try to delete it this test bundle, we can not and we have to cancel all linked documents

**Comment by ankush** [comment]
like it says in the error message you can not delete a product bundle if it's linked with transactions. This is not a bug.
