### ISSUE TITLE
Work space customization error

### ISSUE THREAD

**Issue by hieutrluu** [frappe/erpnext#29213]
### Information about bug

1. git clone https://github.com/frappe/frappe_docker
2. cp .env.local .env
3. docker-compose up
4. setup System
5. Go to ERPNext APP
6. Click the "Edit" button next to CreateWorkspace -> Edit work space
7. Click "Save customization" button
8. Error "Could not find Row # 4: Link To: Shopify Settings"

![image](https://user-images.githubusercontent.com/32662977/148736849-e194170b-ba59-4d8e-9368-27796fbaa7ff.png)

### Module

integrations

### Version

erpnext 13.x.x-develop
frappe 14.x.x-develop

### Installation method

docker

**Comment by ankush** [comment]
Hello, you can manually remove the offending row as the doctype doesn't exist anymore. 

https://github.com/frappe/erpnext/pull/28519
