### ISSUE TITLE
Success Message doesn't appear on successful invoice creation through Opening Invoice Creation Tool

### ISSUE THREAD

**Issue by yadavyk** [frappe/erpnext#29214]
### Information about bug

Issue : when an invoice is created using Opening Invoice creation tool, the success message doesn't appear on hitting "Create Invoice" button 

Expected Behaviour : 

![gv8rrz7](https://user-images.githubusercontent.com/32797974/148737733-b94b7106-8ce1-4689-bdc5-96c343d42703.png)

Reference : https://frappe.io/app/pre-release-test/PRT-30-12-21-330929

### Module

accounts

### Version

13.18.0

**Comment by deepeshgarg007** [comment]
<img width="1361" alt="image" src="https://user-images.githubusercontent.com/42651287/159277527-2a63ccb9-21db-4c3b-806b-bd46309c63df.png">

Worked as expected, not able to replicate, closing
