### ISSUE TITLE
Change Doctype

### ISSUE THREAD

**Issue by dgram** [frappe/erpnext#29226]
**Is your feature request related to a problem? Please describe.**
I want to implement in erpnext a GTD (get things done) implementation. For this it's neccessary to change doctypes on the fly. Because of the doctype implementation i think it should be possible to implement.

**Simple GTD usecase example:**
I have the following doctypes
- Inbox
    Here i want to collect all ideas, notices all what get into my brain

Steps
1. Collect Ideas, notices, todos etc. in **Inbox**
2. Go through the list and decide which type the entry should be (i.e. **notice**, **todo**, **project** etc.)
3. Change the item to the desired type

**Nice to have features**
- Drag & Drop doctype changing
   Ideally, doctype can be changed by drag & drop them to the specific table (something like [notion.io](https://www.notion.so/))
- Reuse field datas with same fieldname (i.e. inbox has a field with type & todo has a field with type)
   if they could matched by field type, it would be nice if the data can be reused by new doctype

I hope the description is clearly enough

**Comment by dj12djdjs** [comment]
This sounds like it could be done with a single project using kanboard view?

**Comment by sudo-vaibhav** [comment]
almost all of the above problems like @dj12djdjs suggested can be solved using the features already present in frappe/erpnext, I suggest you read https://frappeframework.com/homepage

Also if you are looking for ideas and suggested approaches, head over to https://discuss.erpnext.com/ . It's a better place than Github to get use-case specific help.
