### ISSUE TITLE
Search in Top Bar doesn't return any results.

### ISSUE THREAD

**Issue by waligorar** [frappe/erpnext#29229]
### Information about bug

From Website Settings, I checked "Include Search in Top Bar". Then from website I entered a product name and received message "No matching records. Search something new". I also tried to search for words in a blog post and a webpage with the same message. What is wrong with this search field?

![erpnext-search-bug-1](https://user-images.githubusercontent.com/31345847/148833794-0b8fd70a-50aa-46d4-81f5-732e4207b7eb.png)
![erpnext-search-bug-2](https://user-images.githubusercontent.com/31345847/148833796-7a56dd6a-0103-4a85-90a0-76422017d45b.png)
![erpnext-search-bug-3](https://user-images.githubusercontent.com/31345847/148833798-a8907b3a-178c-4440-b373-bf9b67cc2c3e.png)

### Module

ecommerce

### Version

ERPNext: v13.12.1 (version-13)
Frappe Framework: v13.12.1 (version-13)

Running VM Image downloaded from Bitnami.

No code changes.

**Comment by harshit-30** [comment]
@waligorar update to the latest version and try it again? It works for me, check here: 

![image](https://user-images.githubusercontent.com/46772424/148900743-50948083-6200-4ae8-9b26-c048d0e18524.png)

![image](https://user-images.githubusercontent.com/46772424/148900903-ce57789e-b1b3-4fa6-871f-cc73f7a37dd9.png)
