### ISSUE TITLE
[V5] Item Variants - Item Price created for the template item should be applicable for all the Variants

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#2922]
Currently Item Price created for the template item is not applied for the variants items.

**Comment by rmehta** [comment]
It is - where did you find price is not fetched?

**Comment by umairsy** [comment]
Sorry as issue was not described in detail.

Issue is only in the item listing in POS View. Though on selecting item, rate from template item is fetched correctly.

![screen shot 2015-03-05 at 3 55 13 pm](https://cloud.githubusercontent.com/assets/910238/6503177/818b392e-c350-11e4-977f-51df1209be7c.png)

**Comment by rmehta** [comment]
fixed

**Comment by GoldenScrew** [comment]
> fixed

I have now same problem in v13.
