### ISSUE TITLE
Campaign Naming by Naming Series doesn't work 

### ISSUE THREAD

**Issue by yadavyk** [frappe/erpnext#29239]
### Information about bug

Issue : In CRM Settings, when campaign naming by naming series is enabled and campaigns are created , they're still created by campaign name. 

Reference : https://github.com/frappe/erpnext/pull/27788

Screenshot : 

![image](https://user-images.githubusercontent.com/32797974/148922523-1b1e8c42-12bd-489b-af6a-b240939b6771.png)

![image](https://user-images.githubusercontent.com/32797974/148922907-5dfea817-b8aa-4f43-a904-8fbdb7cc0cf4.png)

![image](https://user-images.githubusercontent.com/32797974/148922786-2da8afd0-862f-4868-8d68-1288da06d2a2.png)

As seen from the screenshot the naming series field appears unpopulated 

Test instance : https://v14-pre-release.frappe.cloud

### Module

CRM 

### Version

V14

**Comment by rmehta** [comment]
Few more issues:

- Why is "Campaign Naming" in Lead section?
- What about Lead Naming?
