### ISSUE TITLE
[V5] adding letter head crashes complete system

### ISSUE THREAD

**Issue by gentle-** [frappe/erpnext#2923]
I created a new letter head, and added a single png file (company logo).
After saving and returning to the Desk, it's completely blank.

The login page still works.

if I go to /desk#Module%2FBuying, the page renders, but without the top line (with the breadcrumb path, user icon, etc), but after having a menu displayed; choosing any of the menu entries, the result is a blank page.

**Comment by gentle-** [comment]
I had to remove two rows to get it up and running. So I could also reproduce it.
The problem is caused by the row that holds approx 65534 characters.

    select defvalue from tabDefaultValue where defkey='default_letter_head_content'

So I'm guessing the picture is messing things up. It isn't properly uploaded (can't find it in /frappe-bench/apps/erpnext/erpnext/public/images . I expected it there). But that's just a suggestion, please help me in fixing this issue.

**Comment by gentle-** [comment]
It's even weirder.

If you create a new letter head, add an image, it embeds the image in the record in the tabDefaultValue table, defvalue column (which is a text column and probably isn't large enough)
It does something like:
    <img src="data:image/png;base64;filename=cool-company-logo.png,iVBOR

System grinds to halt.

If I then do this:
    delete from tabDefaultValue where defkey='default_letter_head_content'
And re-open the letter head, the image is still there. If I just save the record. the tabDefaultValue table is updated again. The defvalue now is
    <img src="/files/cool-company-logo.png" height="169" width="347">

it's not embedded anymore...

**Comment by anandpdoshi** [comment]
Don't use embedded images. Use a link to an uploaded file. That should
solve the problem.

**Comment by anandpdoshi** [comment]
also images uploaded using the text editor are extracted and saved as files, and converted to links.

**Comment by gentle-** [comment]
@anandpdoshi I'm just using the functionality provided by the application, I don't explicitely tell the application to embed or to link.

**Comment by anandpdoshi** [comment]
Ok. Can you share the letterhead? I tried and it doesn't malfunction with
the image I used.

**Comment by gentle-** [comment]
It happens with all images I use. I made one just for you:
![cool-company-logo](https://cloud.githubusercontent.com/assets/10958563/6502898/0509d9fa-c328-11e4-9113-9eeeb52fed5d.png)

You have to do it exactly like this:
1. create a new letterhead, enter the name
2. check "Is Default"
3. attach the image
4. press "Save" only once.

Now the Desk is going to be blank, you might have to do --clear_cache to get the effect (ctrl-f5 does the trick for me)

If you now check the database, you'll notice the image is embedded.
Delete that record, and --clear_cache to get the desk back.

If you do this:
1. create a new letterhead, enter the name
2. check "Is Default"
3. attach the image
4. press "Save" **twice**

By pressing Save twice, the image is linked, not embedded.
Also, if you don't mark it as Default, the issue does not appear.

**Comment by anandpdoshi** [comment]
@gentle- Thanks a lot for the detailed steps. This nailed the problem and I was able to fix it :+1:

**Comment by gentle-** [comment]
Confirmed, it now works without issue. Thanks
