### ISSUE TITLE
Recurring Invoice Print Format

### ISSUE THREAD

**Issue by adgency** [frappe/erpnext#2925]
How can I choose which print format is going to be used for a Recurring Invoice?
Because even though I have set up my custom pritn format and use it for my invoices, in the Recurring Invoice it prints with the standart one.

**Comment by nabinhait** [comment]
- [ ] Add "Print Format" field in recurring section. Show only print formats for that doctype.
- [ ] Send selected print format in email

**Comment by nabinhait** [comment]
@neilLasrado You have to create recurring print format for all the doctypes as per old hard-coded print format. And then you need to write a patch to set that print format in all existing recurring documents.
