### ISSUE TITLE
Buttoncolor in Opportunity

### ISSUE THREAD

**Issue by wojosc** [frappe/erpnext#29258]
### Information about bug

The "Create" Button not blue
![grafik](https://user-images.githubusercontent.com/22279621/149123645-82d513fd-0277-45bb-810c-042ae8455c43.png)

### Module

CRM

### Version

ERPNext: v13.16.1 (version-13)

Frappe Framework: v13.16.0 (version-13)

**Comment by rahulrana0105** [comment]
@wojosc @ankush @deepeshgarg007 @rohitwaghchaure  https://github.com/frappe/frappe/pull/24807   can you look in this?

**Comment by ankush** [comment]
https://github.com/frappe/frappe/pull/24807#issuecomment-1936930773

**Comment by khushali-beehyv** [comment]
Hi @ankush We want to contribute to frappe. Is there a messaging community in frappe to discuss & acknowledge before picking up any task to confirm valid tickets ?

**Comment by wojosc** [comment]
[discuss.frappe.io](https://discuss.frappe.io/)
