### ISSUE TITLE
[V5] toolbar missing

### ISSUE THREAD

**Issue by gentle-** [frappe/erpnext#2926]
On my local installation (updated daily) I'm missing the toolbar. This prevents me from making invoices, based on purchase receipts or delivery notes, for example. Toolbar is missing in both purchasing and selling (haven't checked other modules).

Comparison between local install and staging5.erpnext.com:

erpnext.com:
![selection_016](https://cloud.githubusercontent.com/assets/10958563/6505920/108a0c04-c347-11e4-8dfa-834b7a5ac780.png)

Local
![selection_017](https://cloud.githubusercontent.com/assets/10958563/6505921/11ff1368-c347-11e4-9b0e-3dc561938564.png)

**Comment by rmehta** [comment]
fixed.

**Comment by gentle-** [comment]
Confirmed, visible again :+1:
