### ISSUE TITLE
Refresh button on Company page doesn't work 

### ISSUE THREAD

**Issue by yadavyk** [frappe/erpnext#29279]
### Information about bug

Issue : The refresh button on Company form doesn't work. 

![Issue](https://user-images.githubusercontent.com/32797974/149344166-7aaa1871-8145-47d2-aa46-17cc42706aef.gif)

Expected Behaviour : The button should reload/refresh the page 

### Module

accounts

### Version

V 13.18.0

**Comment by deepeshgarg007** [comment]
@yadavyk this looks like the print format view of the company doctype. What are we trying to refresh here? Nothing seems wrong. Please reopen if its valid after elaborating
