### ISSUE TITLE
billing_summary.py filters.project should be filters["project"]

### ISSUE THREAD

**Issue by charleslcso** [frappe/erpnext#29284]
### Information about bug

In erpnext/erpnext/projects/report/billing_summary.py, line 126 should be filters [ "project" ], not filters <dot> project.

### Module

other

### Version

frappe 13.18
erpnext 13.18

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
if "project" in filters:
		# timesheet_details_filter["project"] = filters.project    <- bug
		timesheet_details_filter["project"] = filters["project"]
```

**Comment by ankush** [comment]
why is this a bug? can you share an actual error causes by this. filters is a `_dict` which allows accessing keys as attribute.

**Comment by charleslcso** [comment]
@ankush I didn't realise you have replied me until just now. 

Yes, filters is a dict, but project in filters is a list.

Here is the error. 
![Screenshot 2022-01-25 at 11 28 22 AM](https://user-images.githubusercontent.com/520537/150905799-b73c57eb-f94b-4417-bac3-aad728772ecc.JPG)


![Screenshot 2022-01-25 at 11 40 59 AM](https://user-images.githubusercontent.com/520537/150906857-998c3c81-4273-40ac-bf5c-e7a52fb653bb.JPG)
