### ISSUE TITLE
SLA status is not getting updated when the doctype status is automatically updated

### ISSUE THREAD

**Issue by sharmanakul** [frappe/erpnext#29288]
### Information about bug

1. Create SLA for opportunity. SLA fulfilment is marked at Opportunity status 'Quotation'
![image](https://user-images.githubusercontent.com/88872881/149482296-53e84157-4307-4d95-a3a6-0de291d9cec1.png)

2. create Opportunity
3. Now create Quotation against it. On creating Quotation, Opportunity status is updated as 'Quotation'
4. However SLA status is not updated. It should have been fulfilled 
![image](https://user-images.githubusercontent.com/88872881/149483140-6ce551a5-9efd-432b-af31-20d53942056c.png)

Please note if i manually change the status of the opportunity then the SLA status is updated.

### Module

selling

### Version

v14

**Comment by ankush** [comment]
hint, this is hardcoded from issue doctype. The headline alert is misleading in that regard. 

https://github.com/frappe/erpnext/blob/8e425252c413dc40bdbd07c567adf430bf8efe0e/erpnext/public/js/utils.js#L889
