### ISSUE TITLE
Cancel Sales Invoice Fails after E Commerce v13 upgrade

### ISSUE THREAD

**Issue by jowami** [frappe/erpnext#29295]
### Information about bug

Upgraded to from v13.2.0 to v13.8.0 after which one is unable to cancel and amend an invoice that has been submitted. erpnext.selling.doctype.sales_receipt.sales_receipt module and doctype does not exist in erpnext but is linked to the sales_invoice hence the error.

### Module

selling

### Version

Frappe version: 13.8.0
ERPNext version: 13.8.0

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "13.18.0",
	"frappe": "13.18.0"
}
```
### Route
```
Form/Sales Invoice/ACC-SINV-2022-00002
```
### Trackeback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/modules/utils.py", line 205, in load_doctype_module
    doctype_python_modules[key] = frappe.get_module(module_name)
  File "apps/frappe/frappe/__init__.py", line 975, in get_module
    return importlib.import_module(modulename)
  File "env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'erpnext.selling.doctype.sales_receipt.sales_receipt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 68, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 67, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1208, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/linked_with.py", line 43, in get_submitted_linked_docs
    linked_docs = get_linked_docs(doctype, name, linkinfo)
  File "apps/frappe/frappe/desk/form/linked_with.py", line 170, in get_linked_docs
    link_meta_bundle = frappe.desk.form.load.get_meta_bundle(dt)
  File "apps/frappe/frappe/desk/form/load.py", line 81, in get_meta_bundle
    bundle = [frappe.desk.form.meta.get_meta(doctype)]
  File "apps/frappe/frappe/desk/form/meta.py", line 29, in get_meta
    meta = FormMeta(doctype)
  File "apps/frappe/frappe/desk/form/meta.py", line 39, in __init__
    self.load_assets()
  File "apps/frappe/frappe/desk/form/meta.py", line 53, in load_assets
    self.load_templates()
  File "apps/frappe/frappe/desk/form/meta.py", line 198, in load_templates
    module = load_doctype_module(self.name)
  File "apps/frappe/frappe/modules/utils.py", line 207, in load_doctype_module
    raise ImportError('Module import failed for {0} ({1})'.format(doctype, module_name + ' Error: ' + str(e)))
ImportError: Module import failed for Sales Receipt (erpnext.selling.doctype.sales_receipt.sales_receipt Error: No module named 'erpnext.selling.doctype.sales_receipt.sales_receipt')

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doctype": "Sales Invoice",
		"name": "ACC-SINV-2022-00002"
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.linked_with.get_submitted_linked_docs"
}
```
### Response Data
```
{
	"exception": "ImportError: Module import failed for Sales Receipt (erpnext.selling.doctype.sales_receipt.sales_receipt Error: No module named 'erpnext.selling.doctype.sales_receipt.sales_receipt')"
}
```
Developer mode output:

09:13:34 web.1            | Traceback (most recent call last):
09:13:34 web.1            |   File "apps/frappe/frappe/modules/utils.py", line 205, in load_doctype_module
09:13:34 web.1            |     doctype_python_modules[key] = frappe.get_module(module_name)
09:13:34 web.1            |   File "apps/frappe/frappe/__init__.py", line 975, in get_module
09:13:34 web.1            |     return importlib.import_module(modulename)
09:13:34 web.1            |   File "env/lib/python3.6/importlib/__init__.py", line 126, in import_module
09:13:34 web.1            |     return _bootstrap._gcd_import(name[level:], package, level)
09:13:34 web.1            |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
09:13:34 web.1            |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
09:13:34 web.1            |   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
09:13:34 web.1            | ModuleNotFoundError: No module named 'erpnext.selling.doctype.sales_receipt.sales_receipt'
09:13:34 web.1            | 
09:13:34 web.1            | During handling of the above exception, another exception occurred:
09:13:34 web.1            | 
09:13:34 web.1            | Traceback (most recent call last):
09:13:34 web.1            |   File "apps/frappe/frappe/app.py", line 68, in application
09:13:34 web.1            |     response = frappe.api.handle()
09:13:34 web.1            |   File "apps/frappe/frappe/api.py", line 55, in handle
09:13:34 web.1            |     return frappe.handler.handle()
09:13:34 web.1            |   File "apps/frappe/frappe/handler.py", line 31, in handle
09:13:34 web.1            |     data = execute_cmd(cmd)
09:13:34 web.1            |   File "apps/frappe/frappe/handler.py", line 67, in execute_cmd
09:13:34 web.1            |     return frappe.call(method, **frappe.form_dict)
09:13:34 web.1            |   File "apps/frappe/frappe/__init__.py", line 1208, in call
09:13:34 web.1            |     return fn(*args, **newargs)
09:13:34 web.1            |   File "apps/frappe/frappe/desk/form/linked_with.py", line 43, in get_submitted_linked_docs
09:13:34 web.1            |     linked_docs = get_linked_docs(doctype, name, linkinfo)
09:13:34 web.1            |   File "apps/frappe/frappe/desk/form/linked_with.py", line 170, in get_linked_docs
09:13:34 web.1            |     link_meta_bundle = frappe.desk.form.load.get_meta_bundle(dt)
09:13:34 web.1            |   File "apps/frappe/frappe/desk/form/load.py", line 81, in get_meta_bundle
09:13:34 web.1            |     bundle = [frappe.desk.form.meta.get_meta(doctype)]
09:13:34 web.1            |   File "apps/frappe/frappe/desk/form/meta.py", line 29, in get_meta
09:13:34 web.1            |     meta = FormMeta(doctype)
09:13:34 web.1            |   File "apps/frappe/frappe/desk/form/meta.py", line 39, in __init__
09:13:34 web.1            |     self.load_assets()
09:13:34 web.1            |   File "apps/frappe/frappe/desk/form/meta.py", line 53, in load_assets
09:13:34 web.1            |     self.load_templates()
09:13:34 web.1            |   File "apps/frappe/frappe/desk/form/meta.py", line 198, in load_templates
09:13:34 web.1            |     module = load_doctype_module(self.name)
09:13:34 web.1            |   File "apps/frappe/frappe/modules/utils.py", line 207, in load_doctype_module
09:13:34 web.1            |     raise ImportError('Module import failed for {0} ({1})'.format(doctype, module_name + ' Error: ' + str(e)))
09:13:34 web.1            | ImportError: Module import failed for Sales Receipt (erpnext.selling.doctype.sales_receipt.sales_receipt Error: No module named 'erpnext.selling.doctype.sales_receipt.sales_receipt')
09:13:34 web.1            | 
09:13:34 web.1            | Traceback (most recent call last):
09:13:34 web.1            |   File "apps/frappe/frappe/modules/utils.py", line 205, in load_doctype_module
09:13:34 web.1            |     doctype_python_modules[key] = frappe.get_module(module_name)
09:13:34 web.1            |   File "apps/frappe/frappe/__init__.py", line 975, in get_module
09:13:34 web.1            |     return importlib.import_module(modulename)
09:13:34 web.1            |   File "env/lib/python3.6/importlib/__init__.py", line 126, in import_module
09:13:34 web.1            |     return _bootstrap._gcd_import(name[level:], package, level)
09:13:34 web.1            |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
09:13:34 web.1            |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
09:13:34 web.1            |   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
09:13:34 web.1            | ModuleNotFoundError: No module named 'erpnext.selling.doctype.sales_receipt.sales_receipt'
09:13:34 web.1            | 
09:13:34 web.1            | During handling of the above exception, another exception occurred:
09:13:34 web.1            | 
09:13:34 web.1            | Traceback (most recent call last):
09:13:34 web.1            |   File "apps/frappe/frappe/app.py", line 68, in application
09:13:34 web.1            |     response = frappe.api.handle()
09:13:34 web.1            |   File "apps/frappe/frappe/api.py", line 55, in handle
09:13:34 web.1            |     return frappe.handler.handle()
09:13:34 web.1            |   File "apps/frappe/frappe/handler.py", line 31, in handle
09:13:34 web.1            |     data = execute_cmd(cmd)
09:13:34 web.1            |   File "apps/frappe/frappe/handler.py", line 67, in execute_cmd
09:13:34 web.1            |     return frappe.call(method, **frappe.form_dict)
09:13:34 web.1            |   File "apps/frappe/frappe/__init__.py", line 1208, in call
09:13:34 web.1            |     return fn(*args, **newargs)
09:13:34 web.1            |   File "apps/frappe/frappe/desk/form/linked_with.py", line 43, in get_submitted_linked_docs
09:13:34 web.1            |     linked_docs = get_linked_docs(doctype, name, linkinfo)
09:13:34 web.1            |   File "apps/frappe/frappe/desk/form/linked_with.py", line 170, in get_linked_docs
09:13:34 web.1            |     link_meta_bundle = frappe.desk.form.load.get_meta_bundle(dt)
09:13:34 web.1            |   File "apps/frappe/frappe/desk/form/load.py", line 81, in get_meta_bundle
09:13:34 web.1            |     bundle = [frappe.desk.form.meta.get_meta(doctype)]
09:13:34 web.1            |   File "apps/frappe/frappe/desk/form/meta.py", line 29, in get_meta
09:13:34 web.1            |     meta = FormMeta(doctype)
09:13:34 web.1            |   File "apps/frappe/frappe/desk/form/meta.py", line 39, in __init__
09:13:34 web.1            |     self.load_assets()
09:13:34 web.1            |   File "apps/frappe/frappe/desk/form/meta.py", line 53, in load_assets
09:13:34 web.1            |     self.load_templates()
09:13:34 web.1            |   File "apps/frappe/frappe/desk/form/meta.py", line 198, in load_templates
09:13:34 web.1            |     module = load_doctype_module(self.name)
09:13:34 web.1            |   File "apps/frappe/frappe/modules/utils.py", line 207, in load_doctype_module
09:13:34 web.1            |     raise ImportError('Module import failed for {0} ({1})'.format(doctype, module_name + ' Error: ' + str(e)))
09:13:34 web.1            | ImportError: Module import failed for Sales Receipt (erpnext.selling.doctype.sales_receipt.sales_receipt Error: No module named 'erpnext.selling.doctype.sales_receipt.sales_receipt')
09:13:34 web.1            | 
09:13:34 web.1            | 127.0.0.1 - - [15/Jan/2022 09:13:34] "POST /api/method/frappe.desk.form.linked_with.get_submitted_linked_docs HTTP/1.0" 500
```

**Comment by ankush** [comment]
There's no doctype called "Sales Receipt"; check doctype list for any such doctype (maybe it's custom but being treated as standard.

**Comment by jowami** [comment]
Fixed, thanks.
