### ISSUE TITLE
POS: Error on removing item from cart

### ISSUE THREAD

**Issue by HaniTetouha** [frappe/erpnext#29297]
### Information about bug

Hello,

When returning a Sales Invoice from POS Interface with arabic as system language and when select item from cart and press delete I receive the following message
```
Please select a field to edit from numpad
```
I receive this error only when setting the system language to arabic, it works fine with english

### Module

accounts, selling

### Version

Frappe version - v13.18.0
Erpnext version - v13.18.0

### Installation method

manual install

**Comment by chrisdent** [comment]
fixed with pull #29181
