### ISSUE TITLE
Inconsistent naming for Work Order Wise Consumed Materials Report 

### ISSUE THREAD

**Issue by yadavyk** [frappe/erpnext#29293]
### Information about bug

Issue - The name as per https://github.com/frappe/erpnext/pull/28500 for this report is “Work Order Wise Consumed Materials” , however it appears as “Work Order Consumed Materials” under reports section. 

![Work Order Report Name ](https://user-images.githubusercontent.com/32797974/149523260-a837142c-9478-42bb-a488-b5444161350e.png)

### Module

manufacturing

### Version

V14

**Comment by rohitwaghchaure** [comment]
Fixed docs https://docs.erpnext.com/docs/v13/user/manual/en/manufacturing/reports/work-order-consumed-materials
