### ISSUE TITLE
Stock reports have more precision than can be modified

### ISSUE THREAD

**Issue by RealDesignGraphics** [frappe/erpnext#2929]
![batch wise balance history screenshot](https://cloud.githubusercontent.com/assets/8544220/6527915/27ac4620-c3e4-11e4-9ce4-e6824b3a1a89.png)

As you can see, there is a greater precision in the actual stock balance than can be achieved through a stock entry.  I am trying to clear out batches that are no longer in inventory and this makes it impossible.

**Comment by nabinhait** [comment]
Fixed. Please update and check again.
