### ISSUE TITLE
Point of sale numpad error and wrong translation in valuefield

### ISSUE THREAD

**Issue by thejoe8495** [frappe/erpnext#29311]
### Information about bug

In Point of Sale the numpad target field is translated. So the PoS cant used in other languages.

The Line
https://github.com/frappe/erpnext/blob/0fb6f9306f6cb3f6022dca0c2a0f945160a508a1/erpnext/selling/page/point_of_sale/pos_number_pad.js#L28
generate this line:
`<div class="numpad-btn col-span-2" data-button-value="menge" title="Ctrl+M">Menge</div>`
but need to generate this:
`<div class="numpad-btn col-span-2" data-button-value="qty" title="Ctrl+M">Menge</div>`

I removed the translation in this rows
https://github.com/frappe/erpnext/blob/dfe2140f70ba955ada3aad12b45d2ef7714edf85/erpnext/selling/page/point_of_sale/pos_item_cart.js#L133
and add it here from
https://github.com/frappe/erpnext/blob/0fb6f9306f6cb3f6022dca0c2a0f945160a508a1/erpnext/selling/page/point_of_sale/pos_number_pad.js#L28
to
`return a2 + '<div class="numpad-btn ${class_to_append}" data-button-value="${fieldname}">' + __(number) + '</div>';`

and it work ;)

### Module

selling

### Version

erpnext 13.18.0 version-13 (dfe2140)
frappe 13.18.0 version-13 (fa6da72)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
On a click on "Menge" it need to focus the quantity field, but it generate a error "Bitte wähle ein Feld aus numpad aus" that means click on a button in numpad.
```

**Comment by chrisdent** [comment]
fixed with pull #29181
