### ISSUE TITLE
[V5] Translation of chart of accounts is not working properly

### ISSUE THREAD

**Issue by gentle-** [frappe/erpnext#2931]
I *think* this is an issue, but I might not understand it correctly. bear with me.

The translations were merged today and I made sure the chart of accounts were (almost) all translated through the portal. But the COA is still showing only English words. I took one example to see if could find out what went wrong:

apps/erpnext/erpnext/accounts/doctype/account/chart_of_accounts/standard_chart_of_accounts.py +158,Shareholders Funds,Eigen Vermogen

The file standard_chart_of_accounts.py does not exist in this path:
    apps/erpnext/erpnext/accounts/doctype/account/chart_of_accounts/
it does exist here:
    apps/erpnext/erpnext/accounts/doctype/account/chart_of_accounts/verified
(translation also applies to line 158)

I tried changing the path in the nl.csv file, but it doesn't work (including --clear_cache)
Other translations that are done similarly do work.

**Comment by pdvyas** [comment]
The position in the translation file does not matter.

For the correct chart of accounts, you will have to run the setup wizard
with correct language as the language (and the strings) should be present
while inserting the chart of account records.

**Comment by gentle-** [comment]
Fair enough. Thanks for clarifying.
