### ISSUE TITLE
[V5] Desk module translations erratic

### ISSUE THREAD

**Issue by gentle-** [frappe/erpnext#2932]
The Desk is not translating the modules properly. Buying is always Buying and never translated, whatever I do. Some modules are correctly translated, like "All Applications" or "Notes".

Stock however showed something interesting, it suddenly was translated when I came back from a document. Whatever I try, I can't reproduce it. Fortunately there's proof:

![selection_019](https://cloud.githubusercontent.com/assets/10958563/6547552/71b3d1a4-c5db-11e4-8ed8-b876e35f5e1a.png)

After pressing F5:
![selection_020](https://cloud.githubusercontent.com/assets/10958563/6547553/7a52df76-c5db-11e4-85e5-9080dafa2f4e.png)

I tried adding/removing applications from the desk, reordering them and just clicking around in the application to get lucky, in vain...

Update: I noticed that Setup is also translated and afterwards not anymore. Something is wrong here...

**Comment by rmehta** [comment]
Fixed
