### ISSUE TITLE
Dead links in Bank Reconciliation statement

### ISSUE THREAD

**Issue by deepakc21** [frappe/erpnext#29336]
### Information about bug

The links in the "against account" column in the "Bank reconciliation statement" leads to nowhere.
Please refer the screenshots attached herewith. When I click on the account name (marked red in the first screenshot) it redirects me to an error page(screenshot 2).
![15](https://user-images.githubusercontent.com/97949896/149920043-6cc2ee16-4181-49b4-9944-b4d65b75e81f.jpg)
![16](https://user-images.githubusercontent.com/97949896/149920269-af35c5da-0a9a-4349-b1ad-4044a71db286.jpg)

### Module

accounts

### Version

ERPNext: v13.18.0 (HEAD)
Frappe Framework: v13.18.0 (HEAD)

### Installation method

FrappeCloud

**Comment by ankush** [comment]
share URL that's routed to when you click on link; that will help understanding issue. 

Mostly against account links can't work because there are multiple accounts in same text field. 

Edit:

after discussing with @deepeshgarg007: in this case it's party name so account link won't exist for sure.

**Comment by deepeshgarg007** [comment]
@deepakc21 as Ankush has already mentioned there are cases where nonlink values (values other than account) are added in that case the link won't work, for the rest it should. If the case is otherwise please reopen
