### ISSUE TITLE
getting error on setup wizard V5 

### ISSUE THREAD

**Issue by chandutalluri** [frappe/erpnext#2933]
Massage

Setting this address Template as default as there is no other default 
Duplicate name activity manufacturing
Another transaction is blocking this one. please try again in a few seconds

v5 updated  time and date 13:57 09-03-2015
with same repeated error 
is v5 reedy and running for production please tel word about that 
Reg 
Chandu

**Comment by chandutalluri** [comment]
Hi R Mehta 
in my instant same error was repeated still today
or 
is it fixed or am missing something

**Comment by nabinhait** [comment]
@chandutalluri Are you still getting the issue?
