### ISSUE TITLE
POS: not able to select another item through the side panel

### ISSUE THREAD

**Issue by sharmanakul** [frappe/erpnext#29338]
### Information about bug

Selected an item, provided value and batch no.
![image](https://user-images.githubusercontent.com/88872881/149929743-6c7b8bad-2be2-4da6-b17f-80d070df5527.png)

Please notice in the image above that I'm trying to add another item (body lotion) in the cart.
HOwever, as I click on the item. I'm taken to the catalogue page and required to reselect the item
![image](https://user-images.githubusercontent.com/88872881/149930033-50963fa5-3ac6-4872-b580-5d4f4df62b6d.png)

### Module

other

### Version

v13.18

**Comment by rmehta** [comment]
@nemesis189 28 days? whats the update?

**Comment by nemesis189** [comment]
@sharmanakul unable to replicate on my instance, was able to successfully add an item

**Comment by nemesis189** [comment]
@sharmanakul tried adding

**Comment by nemesis189** [comment]
@sharmanakul it happens when you try to add serialized/batch item next, since it needs the serial no/batch no to be selected. UX issue.
Will have to close the Item Detail section first and then add it

**Comment by rmehta** [comment]
Can we fix the UX issue then?

**Comment by sharmanakul** [comment]
1. The user shouldn't be navigated to the other screen while selecting the item from the side-bar.
2. If the user selected an item with batch/serial, then let him allow to select that from the same screen.
<img width="1222" alt="image" src="https://user-images.githubusercontent.com/88872881/153994851-ea34e797-5b9e-4617-9a5b-eee9d8a6e0bc.png">
