### ISSUE TITLE
Message: Not permitted on each page after update from 13.13 to 13.18

### ISSUE THREAD

**Issue by GoldenScrew** [frappe/erpnext#29345]
### Information about bug

After update from 13.13 to 13.18 I have the error
`message: Not permitted.`

after some time on each page.
![QIP Shot - Screen 128](https://user-images.githubusercontent.com/3992823/149954435-08aa7e1e-af1c-4740-ba79-49cc9337f8b5.png)

### Module

accounts

### Version

ERPNext: v13.18.0 (version-13)
Frappe Framework: v13.18.0 (version-13)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Not permitted.
```

**Comment by ankush** [comment]
this is due to old assets as explained in previous issue: https://github.com/frappe/erpnext/issues/29344#issuecomment-1015493865
