### ISSUE TITLE
Password missing in Email Account. After enter password endless loading.

### ISSUE THREAD

**Issue by GoldenScrew** [frappe/erpnext#29346]
### Information about bug

Password missing in Email Account. After enter password endless loading.
![QIP Shot - Screen 131](https://user-images.githubusercontent.com/3992823/149960798-6be3801c-5e63-4119-9725-68a36c62a4f3.png)

https://user-images.githubusercontent.com/3992823/149960845-56605091-4947-4b6d-befb-560fe50c4bd3.mp4

But emails send with no problem.
This problem was also on v. 13.13

### Module

accounts, stock, buying, selling, ecommerce, manufacturing, HR, projects, support, CRM, assets, integrations, quality, regional, portal, agriculture, education, non-profit, other

### Version

ERPNext: v13.18.0 (version-13)
Frappe Framework: v13.18.0 (version-13)

### Relevant log output / Stack trace / Full Error Message.

```shell
Password missing in Email Account
```

**Comment by nasirrr** [comment]
This issue still persists.

**Comment by zeeshankhalid31** [comment]
I am still facing this issue. application show this dialog on every single page.

**Comment by rinconsupport** [comment]
I am still facing the same issue. 
version: 
ERPNext: v13.42.1 (version-13)
Frappe Framework: v13.45.0 (version-13)

**Comment by SatinderpalSingh** [comment]
I am also facing the similar issue: 
![Screenshot from 2023-09-22 14-06-04](https://github.com/frappe/erpnext/assets/2088760/032f2530-266c-4563-bfd6-1dc5719936b3)
