### ISSUE TITLE
Validations only apply to first incorrect serial no

### ISSUE THREAD

**Issue by yadavyk** [frappe/erpnext#29348]
### Information about bug

Scenario : Suppose an item A with auto generated serial number enabled is created. The validation isn't thrown for multiple existing serial numbers created manually 

Reference : https://github.com/frappe/erpnext/pull/29292

Steps to reproduce : 

1. Create an Item A with serial number enabled and set a pattern say SE.##
2. Create a purchase receipt for qty : 2 and enter serial number manually say SE23 and SE24
3. Create another purchase receipt for qty : 10 and enter serial number manually say SE21 , SE22, SE23, SE24, SE25, SE26, SE27, SE28, SE29, SE30
4. Save the purchase receipt and try submitting it. 

Observation : The validation that a serial number already exists is thrown for serial number SE23 

Expected : The validation should have been thrown for both existing serial numbers SE23, SE24

Screen Recording : 

![Serial Number Issue](https://user-images.githubusercontent.com/32797974/149973236-c35c1ea9-9c11-49b8-8144-e819d615df0c.gif)

### Module

manufacturing

### Version

V 13.19

**Comment by ankush** [comment]
Can you confirm this once again? There's an automated test for exact scenario you're describing... How is that passing 🥲

**Comment by ankush** [comment]
Ok i see it now, you're manually adding the serial no; so the error is indeed correct. We shouldn't skip serial number entered by the user and instead let them know it's received already.

The linked PR only fixes auto generation of serial numbers.

**Comment by ankush** [comment]
This validation is ONE GIGANTIC 100+ line long for loop: https://github.com/frappe/erpnext/blob/742ab2cf5a556e3b7a6f9eb851234e7d667d3bd4/erpnext/stock/doctype/serial_no/serial_no.py#L209-L318 

I honestly don't think it's worth validating all the serial nos. At least not before refactoring the absolute horror that is this function.

**Comment by ankush** [comment]
Not sure how this is critical? It's always been like this. 

More over MOST validation in ERPNext are like this. We stop at first failure with `frappe.throw` everywhere.

**Comment by ankush** [comment]
Thought a bit more about this, doesn't make much sense to validate everything if the first validation fails 😅
