### ISSUE TITLE
POS: UI: discount based on pricing rule is displayed at the very last stage.

### ISSUE THREAD

**Issue by sharmanakul** [frappe/erpnext#29354]
### Information about bug

1. POS profile: disable ignore pricing rule
2. Apply pricing rule on an item
3. Open POS, select item with pricing rule
4. Change qty and amount such that the pricing rule is applicable.
5. Checkout -> Discount is not displayed
6. Complete order -> Discount is not displayed
7. Confirm -> Discount is shown
![image](https://user-images.githubusercontent.com/88872881/150085721-05ba92d5-9984-4cdc-89a5-30e4c3b53a62.png)

IMO, this is a bad UI, discount is displayed at the time of checkout itself.

### Module

accounts

### Version

v13.18

**Comment by nemesis189** [comment]
Fix: https://github.com/frappe/erpnext/pull/29597

**Comment by sharmanakul** [comment]
@nextchamp-saqib i was checking the PR https://github.com/frappe/erpnext/pull/29597
this issue still persists.

**Setup**:
Pricing rule for an item: 10% discount for minimum qty 5
POS profile 'ignore pricing rule' is unchecked.
**Transaction**
In POS UI, I select the item with 20 qty. 
<img width="994" alt="image" src="https://user-images.githubusercontent.com/88872881/154276462-23f139fc-8ddb-4bc5-9ec6-36e1c0366f25.png">

Click on Checkout. Some calculation has been performed here (probably that's why the figure 9000 is showing), but explicit discount is not displayed.
<img width="1268" alt="image" src="https://user-images.githubusercontent.com/88872881/154276680-b5d2146c-8d3a-4c58-878e-830491409d0a.png">


However, when you click on 'Complete Order', the generated invoice does not show any discount.
<img width="520" alt="image" src="https://user-images.githubusercontent.com/88872881/154276910-ba45b50c-8aec-4396-b7d6-7aaf6b95ddc4.png">

**Comment by sharmanakul** [comment]
discount applied should also be highlighted at this stage like (10% off)

<img width="1320" alt="image" src="https://user-images.githubusercontent.com/88872881/154483949-b1e3aee6-375c-483d-bf39-9d4dcdc82634.png">

**Comment by sharmanakul** [comment]
1. Select the item and click on Checkout
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/88872881/154485390-fa946092-1ac2-44b1-bfd9-34542303077b.png">
2. On checking out, you'll notice that the item rate is updated.
<img width="986" alt="image" src="https://user-images.githubusercontent.com/88872881/154485522-10173a63-ec30-4898-8c1d-3e93408fad88.png">
3. click on the item in the left bar and you are navigated to the below screen in which the discount percentage and the applicable item rate is displayed.
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/88872881/154485746-8811bba1-0e01-4aae-aaf8-871443eeff56.png">
4. However if you edit the quantity here such that the pricing rule does not remain applicable, the item rate on the right side is updated but the discount percentage is still displayed.
<img width="1049" alt="image" src="https://user-images.githubusercontent.com/88872881/154486068-31ab7bb8-26ed-4075-a25b-cc5db7ad25a8.png">

**Comment by sharmanakul** [comment]
let me know if i need to create another issue for the above comment. keeping it open for now just for the sake if tracking.
