### ISSUE TITLE
Zh-TW Translation haven't update, while the translation tool app already had lots of Community Contribution.

### ISSUE THREAD

**Issue by Daniel-Choy** [frappe/erpnext#29358]
### Information about bug

First, when we set the "Language" in "My setting" to "zh-tw",
Some of the terms get so confused, for example "Stock" in the MODULES should mean 庫存:stock in warehouse, instead of 股票:stock in stock maket.

We try to contribute translation, but we didnt see any update.

and also, zh-tw now are using the zh-cn translation. it shouldn't be the same.

### Module

stock

### Version

ERPNext 13

### Installation method

FrappeCloud

**Comment by ankush** [comment]
WIP: https://github.com/frappe/translator/pull/212
