### ISSUE TITLE
Sales Invoice with return checked and include payment issues

### ISSUE THREAD

**Issue by mro-admin** [frappe/erpnext#29363]
### Information about bug

When a sales invoice is created with the include payment is checked and a return is created from it. The payment method changes to the default payment method according to the pos profile which is not the payment method from the invoice the return is created from.

This seems like it is being caused by line 620 in erpnext.controllers.taxes_and_totals_py where a call to self.update_paid_amount_for_return is made with this code

```
		default_mode_of_payment = frappe.db.get_value('POS Payment Method',
			{'parent': self.doc.pos_profile, 'default': 1}, ['mode_of_payment'], as_dict=1)

		if default_mode_of_payment:
			self.doc.payments = []
			self.doc.append('payments', {
				'mode_of_payment': default_mode_of_payment.mode_of_payment,
				'amount': total_amount_to_pay,
				'default': 1
			})

		self.calculate_paid_amount()
```

Seems like an unnecessary call. Will create a PR if im correct but i want input from someone else

### Module

accounts, other

### Version

Frappe Framework: v13.18.0 (version-13)
ERPNext: v13.18.0 (version-13)

**Comment by deepeshgarg007** [comment]
https://github.com/frappe/erpnext/pull/23599

Already a PR was merged a while back to resolve this. In other cases its intentional
