### ISSUE TITLE
In “landed cost voucher” doc type,“Account” column is missing in  “Taxes and charges” section 

### ISSUE THREAD

**Issue by ShraddhaRanjane** [frappe/erpnext#2937]
Module- Stock ->Tools->Landed Cost Voucher

step:-
1. Go to Stock Module
2. go to “Tools”
3. go to “Landed Cost Voucher” and create new
4. go to “Taxes and charges” section
5. “Account” column is not available betwwen Description and Amount column

This is available in version -4

**Comment by nabinhait** [comment]
Deprecated that column, it was useless.
