### ISSUE TITLE
bank statement import: currency symbol in the fields

### ISSUE THREAD

**Issue by sharmanakul** [frappe/erpnext#29386]
### Information about bug

on uploading bank statements through Bank Statement Import if some other currency is used, then for the fields withdrawal and deposit, correct symbols are displayed. But compnay currency symbol is displayed for the field 'unallocated amount'
![telegram-cloud-photo-size-5-6289823105429909201-y](https://user-images.githubusercontent.com/88872881/150475288-ae478c5d-764a-4e7b-9d56-33eb8c4e0b7c.jpg)

### Module

accounts

### Version

v13

**Comment by ruchamahabal** [comment]
This seems to be a framework issue. Currency is formatted for submitted documents or if the field is read-only but not for the ones in Draft state. Unsure.

**Comment by sharmanakul** [comment]
yeah, my bad. the currency symbols appear after submitting the doc.

**Comment by mohsinalimat** [comment]
@sharmanakul 

This is same issue? which I solved with below PR?

 https://github.com/frappe/erpnext/pull/29050

**Comment by sharmanakul** [comment]
^ through this PR, only the column for currency was added.
The issue was raised only after checking the PR.

**Comment by mohsinalimat** [comment]
Okay
