### ISSUE TITLE
[V5] Customer Price List not updated in the transaction

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#2938]
Steps:

when creating SO and then selecting a customer, the price list fetched.
But when from customer form, getting into Sale Order of that customer, then
create the Sale Order, it doesn't automatically fetch the price list.

Customer >> Sales Order (option available in the Customer master itself) >> New

When following this navigation, customer is updated correctly in the transaction, but customer's Price List is not updated.

Note: This issue existed in version 4 as well.

**Comment by neilLasrado** [comment]
Same also happens with Quotation, Delivery Note and Sales Invoice.

**Comment by nabinhait** [comment]
fixed
