### ISSUE TITLE
[V5] Workstation master - Warehouse field should be removed or made non-mandatory

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#2939]
In the Workstation master, Warehouse field should be removed or either set as non-mandatory. This is because:

- Warehouse in the workstation is not used for stock keeping. For the capacity planning, we can check for workload on the Workstation itself, and not on its warehouse.

- Warehouse in the workstation master confuse user with Warehouses in the Production Order.

**Comment by neilLasrado** [comment]
Also - not keep shifts mandatory in workstation masters for workstations that do not have shifts

**Comment by neilLasrado** [comment]
Issue is Solved.
