### ISSUE TITLE
[V5] Production Order - Material Transferred for Qty not updated

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#2940]
Steps:

1. Created Production Order.
1. Created Material Transfer entry against Production Order.
1. Came back to Production Order to check "Material Transferred for Qty".

Production Order is not showing Material Transferred for Qty. Also tried after reloading browser tab.

![screen shot 2015-03-10 at 1 54 18 pm](https://cloud.githubusercontent.com/assets/910238/6571414/2bd1ddbc-c72e-11e4-9992-25d5b0bc01f9.png)

**Comment by neilLasrado** [comment]
Issue is Solved.
