### ISSUE TITLE
Encoding error in the German user interface

### ISSUE THREAD

**Issue by yassinehamzaGit** [frappe/erpnext#29412]
### Information about bug

Reports & Masters on all modules is translated to Berichte & amp;   Meister 
=> It should be Berichte & Meister 

### Module

accounts, stock, buying, selling, ecommerce, manufacturing, HR, projects, support, CRM, assets, integrations, quality, regional, portal, agriculture, education, non-profit

### Version

Latest version

### Installation method

FrappeCloud

**Comment by carstenblt** [comment]
I would argue "Meister" is also a terrible (or let's say plain wrong) translation for Masters. "Vorlagen" might be more fitting. "Berichte & Vorlagen".
