### ISSUE TITLE
When changing the shipping warehouse, the price will change automatically

### ISSUE THREAD

**Issue by JasonFu06** [frappe/erpnext#29418]
### Information about bug

1. Create new sales invoice & purchase invoice
2. System show default warehouse
3. get sales order & purchase order
4. the selling price is correct
5. when change other warehouse, the selling have been change to other
 

### Module

buying, selling

### Version

Frappe - 13
ERPNEXT - 13.18

### Installation method

manual install

**Comment by JasonFu06** [comment]
![SI_ERROR](https://user-images.githubusercontent.com/93484850/150680555-078156ff-3c0c-4baf-ac44-324f2c40e1b2.jpg)

**Comment by JasonFu06** [comment]
![SI_ER1](https://user-images.githubusercontent.com/93484850/150680717-b872534b-b743-410b-9100-a66b2c11aeac.jpg)
![SI_ER2](https://user-images.githubusercontent.com/93484850/150680730-426d3f47-78fd-4f78-9a7c-f745d0874892.jpg)

**Comment by ankush** [comment]
You probably have pricing rule that's dependent on warehouse.
<img width="792" alt="Screenshot 2022-01-24 at 7 47 37 PM" src="https://user-images.githubusercontent.com/9079960/150799570-84532b7b-6273-4add-94e9-0bfb596cd553.png">

1.35 / 1.5 = 10% discount. 
 

Add more info if you still think this is a bug.
