### ISSUE TITLE
Maintenance Visit: Item table not populating when get items -> Maintenance Schedule

### ISSUE THREAD

**Issue by sensoware** [frappe/erpnext#29414]
### Information about bug

1) creating the Maintenance visit: Item table not populating when clicking get items -> Maintenance Schedule
2) If selecting get items -> Sales order
3) Its not updating the maintenance  schedule table 
    
![erp-maintenance-sch](https://user-images.githubusercontent.com/98246757/150664651-3fbb0018-4fac-4b52-9c16-62173aedfe31.JPG)
 

### Module

support

### Version

ERPNext: v13.18.0 (HEAD)
Frappe Framework: v13.18.0 (HEAD)

### Installation method

FrappeCloud

**Comment by deepeshgarg007** [comment]
@sensoware This issue should be resolved now, please check and reopen if you are still facing this issue
