### ISSUE TITLE
Translation is visible in report but not in the dashboard chart used in HR workspace

### ISSUE THREAD

**Issue by Sle3perX** [frappe/erpnext#29429]
### Information about bug

I have generated a custom dashboard chart from the standard report 'Employee Leave Balance'. 
![image](https://user-images.githubusercontent.com/13370572/150771153-bb6497d6-5e01-4a29-93e8-821eb92e86b2.png)

I have build my own workspace and linked that dashboard chart for users to see their allocated leaves, leaves taken and the closing balance.
![image](https://user-images.githubusercontent.com/13370572/150771322-5967bf6b-be04-4850-ab25-14e253161f9d.png)

As you can see we want to display the workspace in german language.
Sadly i have not found a way to change the language in the linked dashboard chart.

When i try to translate the standard 'Employee Leave Balance' report, i can change the language of the columns. Marked yellow in the picture.
![image](https://user-images.githubusercontent.com/13370572/150771013-1a02328d-b1b8-47f6-bf07-7c9cc8c89eff.png)

But that is not transfered over to the dashboard chart.
I have tried rebuilding erpnext with frappe. Cleared the cache and tried to change the source code where the report is made but that did not change the language where i want it changed.

### Module

HR

### Version

erpnext 13.18.0
frappe 13.18.0

### Installation method

manual install

**Comment by infinity-sys** [comment]
Any solution found for this issue?, 
it is closed as completed?
