### ISSUE TITLE
Breadcrumb in Item

### ISSUE THREAD

**Issue by wojosc** [frappe/erpnext#29427]
### Information about bug

Missing the modul "Stock" in breadcrumb of Item
![grafik](https://user-images.githubusercontent.com/22279621/150756468-a3203019-e513-4625-b1c4-bea0ba444910.png)

Realtes to: https://github.com/frappe/erpnext/issues/29347

### Module

stock

### Version

ERPNext: v13.18.0 (HEAD)

Frappe Framework: v13.18.0 (HEAD)

### Installation method

FrappeCloud

**Comment by sharmanakul** [comment]
Not sure why is it like this at your end. It is showing correctly at my end.
![image](https://user-images.githubusercontent.com/88872881/150766980-466e7dfc-2a23-42e1-898e-3a737431f56f.png)

**Comment by wojosc** [comment]
@sharmanakul I'm using firefox. You?

**Comment by sharmanakul** [comment]
I first checked it on Chrome and now on Firefox after you mentioned it. Breadcrumbs in both browsers are fine.

**Comment by wojosc** [comment]
@sharmanakul I just checked. It's related to the Modul permissions. If the Modul is not actived then the path won't show:
![grafik](https://user-images.githubusercontent.com/22279621/150768954-6105e436-3c42-4a42-a33f-eb3e97f24608.png)
