### ISSUE TITLE
Sales Order/Material Request sorting in Production Planning 

### ISSUE THREAD

**Issue by mohammedyusufshaikh** [frappe/erpnext#29445]
**The Issue**

- Currently in the production planning doctype fetching of sales order/material does not have a sorting feature using which we can give priority to certain parameters while fetching. 

**The Solution**

- Adding a sorting section where users can select the parameters on which the sales order/material request has be fetched such as delivery date and order value

**Comment by szufisher** [comment]
Maybe priority field on sales order item and material request item as the default sorting criteria.

also like schedule day, the priority field can be at document header level to auto populate all items.
