### ISSUE TITLE
Certificate template builder inside Education module for student and employee.

### ISSUE THREAD

**Issue by tsothun** [frappe/erpnext#29455]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tsothun** [comment]
Dear team, it would be nice if you can add certificate template builder inside Education module, so after student or employee pass the exam they can get certificate out of system.

**Comment by johnlongland** [comment]
Good day
I would like to add my voice to this request. Could I ask that it be made available on the V12 as well . I am currently using V12.28.

I have already did my own code modifications to achieve this but I have only copied code and really hacked it so it is not of a standard to generate a pull-request.

I basically added a secondary button in "student_report_generation_tool.js .....

        refresh: function(frm) {
                frm.disable_save();
                frm.page.clear_indicator();
                frm.page.set_primary_action(__('Print Report Card'), () => {
                        let url = "/api/method/erpnext.education.doctype.student_report_generation_tool.student_report_generation_tool.preview_report_card";
                        open_url_post(url, {"doc": frm.doc}, true);
                });
                frm.page.set_secondary_action(__('Print Certificate'), () => {
                        let url1 = "/api/method/erpnext.education.doctype.student_report_generation_tool.student_report_generation_tool.preview_certificate";
                        open_url_post(url1, {"doc": frm.doc}, true);
                });
        },


I then added a "def" to student_report_generation_tool.py

def preview_certificate(doc):
( which really is a copy of the "preview_report_card" with a change to reference the new HTML template)

And created an HTML file.....
student_certificate_generation_tool.html ...  with the HTML code for my certificate.

I shall attached a screen-shot of the new-look Student Report Generation Tool page...
I shall alos upload the certificate.

Please excuse the black blocks but I felt that I should black out the company logo that this was for.
![cert](https://user-images.githubusercontent.com/66208349/152643128-bf94a42c-fd96-407e-bd76-037668b82895.JPG)
![doc](https://user-images.githubusercontent.com/66208349/152643211-f19c1096-77cc-4a38-8afd-eb232b9e7f40.JPG)
