### ISSUE TITLE
billing_summary.py filters.project should be filters["project"] - to continue

### ISSUE THREAD

**Issue by charleslcso** [frappe/erpnext#29464]
@ankush I didn't realise you have replied me until just now. 

Yes, filters is a dict, but project in filters is a list.

Here is the error. 
![Screenshot 2022-01-25 at 11 28 22 AM](https://user-images.githubusercontent.com/520537/150905799-b73c57eb-f94b-4417-bac3-aad728772ecc.JPG)

![Screenshot 2022-01-25 at 11 40 59 AM](https://user-images.githubusercontent.com/520537/150906857-998c3c81-4273-40ac-bf5c-e7a52fb653bb.JPG)

_Originally posted by @charleslcso in https://github.com/frappe/erpnext/issues/29284#issuecomment-1020765262_

**Comment by ankush** [comment]
@charleslcso still not understanding from where/how salary slip is calling a function you pointed out which exists in an unrelated report. 

Can you click on "Copy error to clipboard" and share it here?

**Comment by charleslcso** [comment]
Just confirmed that I was using hooks to override the method, and the new sequence of action triggered the error. 

It won't happen if the original code is used. 

Sorry about this.
