### ISSUE TITLE
Value $ difference between Stock Entry and Stock Ledger when issuing multiple batches

### ISSUE THREAD

**Issue by guilmori** [frappe/erpnext#29468]
### Information about bug

Here are the steps to reproduce.

Create new Item-1, `Has Batch No` = Yes, `Valuation Method` = FIFO
Create a Purchase Receipt, Item-1, qty:10, batch-50, 50$
Create a Purchase Receipt, Item-1, qty:10, batch-30, 30$

Here is the Stock Ledger Entry for this item.
Stock_queue is showing 10 @ 50.00$ and 10 @ 30.00$
All good.
![image](https://user-images.githubusercontent.com/9451512/151211624-dac0f3f6-3971-4a48-8109-30421fcbd112.png)

Next, create a Stock Entry - Material Issue
Add line 1 - Item-1, qty:10, batch-50
Add line 2 - Item-1, qty:10, batch-30

Now look at the rates one each item lines, both lines are showing 50$, although second line should be at 30$.
Total Outgoing value shows 1000$ even though I have only 800$ of value in stock. 
![image](https://user-images.githubusercontent.com/9451512/151211874-98b532da-29c9-47d2-bff9-a3cfb7c48c59.png)

When we submit the Stock Entry, the Stock Ledger is showing the correct amounts.
![image](https://user-images.githubusercontent.com/9451512/151212157-f08c512d-6100-42ec-bd4a-1e38b4241c45.png)

Please fix the Stock Entry screen to pick the right amount when issuing multiple batches.
Thanks

### Module

stock

### Version

v13.16.0

### Installation method

manual install

**Comment by ankush** [comment]
Thanks for the detailed steps. I haven't ran it but I am guessing this is valid. 

The reason is:

1. Rate shown to you while issuing are at the time of creating that row based on FIFO (not based on batch yet)
2. When it's submitted, it's processed sequentially and rates should be updated back to stock entry. This isn't happening right now. 
3. This will likely get fixed by https://github.com/frappe/erpnext/pull/26914

**Comment by guilmori** [comment]
Even after submit, the rates and total amount in Stock Entry remains wrong.
Stock Ledger is ok.

We are going live next week, and because of this bug, we are switch valuation method from FIFO to Moving Average (multiple batches consumption is frequent in our domain).
I really wish we could use #26914 
Any idea of the date of release ?
And if we go live with Moving Average, will it be possible for an easy switch to the batch-wise once it is made available ?

Thanks!

**Comment by ankush** [comment]
Changing valuation isn't allowed after you start using it in stock transactions. While it's very difficult to show FIFOed rates on the transaction, it should be possible to update correct values after submitting. 

https://github.com/frappe/erpnext/blob/1ee17b43d5e65b2fc4796de2a33fdbe3ea86d45a/erpnext/stock/stock_ledger.py#L481-L482

Currently, updates are not done if the transaction isn't backdated. Maybe we'll have to make some kinda provision here to handle the case you've described. 

Just removing first line of code above will start back-updating rates (might also make things very slow in other cases 😄 )


> I really wish we could use #26914
> Any idea of the date of release ?

Most likely v14 as it's kind of a breaking change.

**Comment by ankush** [comment]
@guilmori can you try the linked PR above in a test environment? We are planning to push this change in v14 release.

**Comment by guilmori** [comment]
> @guilmori can you try the linked PR above in a test environment? We are planning to push this change in v14 release.

Great!
I'll try to find some time to try this out.
I really like the fact it is going to work on future batches no matter the actual valuation method (if I understand correctly).

**Comment by ankush** [comment]
> I really like the fact it is going to work on future batches no matter the actual valuation method (if I understand correctly).



Yeah this was the original plan but after some deliberation, we decided not to enable this for moving average users. Since there's no reliable way to transition for items which have moving average valuation rates. 


So batch-wise valuation will work for FIFO and LIFO only for now.

**Comment by ankush** [comment]
https://github.com/frappe/erpnext/pull/29517 This should fix the problem on v13 too (although it won't happen immediately because it's a kinda slow process so it's moved to background, should finish in ~1 hour)
