### ISSUE TITLE
Employee Onboarding & Separation Improvements 

### ISSUE THREAD

**Issue by yadavyk** [frappe/erpnext#29470]
### Information about bug

Reference : [26738](https://github.com/frappe/erpnext/pull/26738)

Issues - 

EMPLOYEE ONBOARDING : 

1. Employee Onboarding link missing from Employee’s connections form. 
2. When an employee is created from Job Offer, the offer date should be mapped as is from the Job Offer record itself. Right now there’s no such mapping 

![Test case 3](https://user-images.githubusercontent.com/32797974/151291865-ed291a90-a985-44ab-b7ac-66623f7e229a.gif)

3. If we create employee onboarding for an employee then the details like designation, department, grade and holiday list should be fetched for that employee as per the same mentioned in the Employee record. Also employee name linkage is missing in employee onboarding record on save. 

![Test case 4](https://user-images.githubusercontent.com/32797974/151291931-e8d55618-b23b-46d8-affa-13efa7d0637f.gif)

4. On cancellation of employee onboarding, all the related projects and tasks get deleted altogether. The user has no way to find out if these projects or tasks got deleted.  We can add a confirmation message, like something that says "If you cancel this employee onboarding record, related projects and tasks will be deleted permanently. Do you want to cancel ?" An example : 

![message example](https://user-images.githubusercontent.com/32797974/151314910-71dc7bfb-e43f-4ae7-a957-a117a0a8dfc3.gif)

5.  On cancellation of employee onboarding, if I amend the same and try to create afresh it still says that an employee onboarding record exists. So workaround is to delete the cancelled document and then create again. However let’s say for Sales Order user can still create record for same customer without having to create new record altogether. 

![cancel onboarding handling](https://user-images.githubusercontent.com/32797974/151315770-a073e5e3-dda2-4540-b781-9c8a64217e64.gif)

Expected behaviour : While validating it should check for document status as cancelled and then let the user proceed accordingly instead of preventing the user

6. In the project created against employee onboarding, under Start and End Dates section, there's a field called "Actual Time (in hrs)". This time is calculated based on timesheets. A small message indicating on what basis this is calculated would be helpful 

![image](https://user-images.githubusercontent.com/32797974/151316807-943d8e26-11ee-4f4d-a403-cd96becf23fd.png)

EMPLOYEE SEPARATION  : 

1. Can we completely remove the Required for Onboarding checkbox from activities child table in Employee Separation Template? This doesn't make sense to be present in the separation doctypes 

![image](https://user-images.githubusercontent.com/32797974/151317423-1a130d6e-1b4a-4e6c-a0b7-b5c0d6408487.png)

2. On creation of employee separation, projects and tasks are created. When viewing tasks in Gantt, all tasks are shown appropriately but in calendar view one task is missing 

![Incorrect task count](https://user-images.githubusercontent.com/32797974/151317488-abee40a0-f602-45c4-8c90-bf13edafae00.gif)

Test instance : https://v14-pre-release.frappe.cloud/

### Module

HR

### Version

V14

**Comment by ruchamahabal** [comment]
> On cancellation of employee onboarding, if I amend the same and try to create afresh it still says that an employee onboarding record exists. So workaround is to delete the cancelled document and then create again. However let’s say for Sales Order user can still create record for same customer without having to create new record altogether.

This will need some handling in the framework. Even if I trigger this confirmation via `msgprint` + server/client_action, the standard confirm cancellation message will still be shown. Seeing 2 confirmations before cancellation will be irritating. Will cover this in the next iteration. For now I have added a toast to just inform the user about the deletion:

https://user-images.githubusercontent.com/24353136/151655591-20560080-59a0-4966-9ecc-d85bd1ae35a6.mp4

> On creation of employee separation, projects and tasks are created. When viewing tasks in Gantt, all tasks are shown appropriately but in calendar view one task is missing

Checked on the test site. The separation was for the employee "Rajesh" and all tasks are visible in the calendar. I guess you were checking them for "Amit"
<img width="1313" alt="calendar" src="https://user-images.githubusercontent.com/24353136/151655616-c3a7192f-1080-4dab-9232-b818d49d3f17.png">

**Comment by ruchamahabal** [comment]
> If we create employee onboarding for an employee then the details like designation, department, grade and holiday list should be fetched for that employee as per the same mentioned in the Employee record. Also employee name linkage is missing in employee onboarding record on save.

These fields are meant to be fetched from the Employee Onboarding Template field, they were not being fetched on template selection. Moved it to the "fetch from" configuration in the doctype. 

If the employee is already created, then populating these fields doesn't make sense because we need them for employee creation. Hence, not fetching it from 2 sources.

**Comment by yadavyk** [comment]
> > On creation of employee separation, projects and tasks are created. When viewing tasks in Gantt, all tasks are shown appropriately but in calendar view one task is missing
> 
> Checked on the test site. The separation was for the employee "Rajesh" and all tasks are visible in the calendar. I guess you were checking them for "Amit" <img alt="calendar" width="1313" src="https://user-images.githubusercontent.com/24353136/151655616-c3a7192f-1080-4dab-9232-b818d49d3f17.png">

The separation is created for both employees Rajesh and Amit with equal number of tasks i.e there are 6 tasks. However for Rajesh all 6 tasks are visible on calendar but for Amit only 5 tasks are visible

**Comment by ruchamahabal** [comment]
So the calendar view had an "Open" filter set by default and the "Schedule exit interview" task was in "Working" status so it was not showing up. Removed the filter and it showed up:

https://user-images.githubusercontent.com/24353136/151656463-fd255142-8576-4767-aee8-617a1af6e057.mp4
