### ISSUE TITLE
Item level tax template not fetching on sales invoice

### ISSUE THREAD

**Issue by shibinrajumathew** [frappe/erpnext#29483]
### Information about bug

**Issue 1:** On Item master, tax template added but sales invoice not fetching. This same issue also with tax template applied on item group.

To  reproduce 

1. Add tax template to one item in stock.
2. Add new sales invoice and add previous item ( add tax template column in Item table).
3. No tax template will show or no suggestion.
4. On Tax calculation also no tax amount shown.

For Issue with group tax

1. Add tax template to a group.
2. Add item to the group
3. Generate sales invoice
4. No tax template or tax amount

**Issue 2:** Another issue is with multiple item with different tax rate.

 Expected result: sum of all tax of individual item + individual item total amount.
 Real result: Only one tax is use for all item.

### Module

accounts

### Version

 F:13.19
 E:13.19

### Installation method

manual install

**Comment by basant-in** [comment]
I still see this as an issue for tax setup at item group. Anyone can help how to fix this?

**Comment by shibinrajumathew** [comment]
Create tax template and assign tax template to item group.

**Comment by shibinrajumathew** [comment]
Create tax template with company, account head and then try too assign to group

**Comment by shibinrajumathew** [comment]
Create tax template with company, account head and then try too assign to group

**Comment by shibinrajumathew** [comment]
Create tax template with company, account head and then try too assign to group
