### ISSUE TITLE
Allow delete not available on POS Profile

### ISSUE THREAD

**Issue by ngoploti** [frappe/erpnext#29486]
### Information about bug

Allow delete not available on POS Profile
And Remove Button is not working in POS Screen. When you click on remove button on POS Screen, it always asks to select a line to edit on the Cart.

### Module

accounts, selling

### Version

Frappe version 13.9
ERPNext version 13.9

**Comment by sharmanakul** [comment]
@ngoploti you can delete pos profile as long as you haven't made any transactions.

Could you please explain the second issue a bit more because the 'remove' button is working fine at my end as one item always remains selected.
