### ISSUE TITLE
Request: Additions in table Customer and Supplier (companies and persons) 

### ISSUE THREAD

**Issue by star39** [frappe/erpnext#2950]
As in many countries mentioning VAT/GST/Sales Tax Number, Income Tax Number and registration Number are mandatory in invoices, Please add in tables Customer (Company) and Supplier (Company)
1. VAT/Goods and Services Tax/Sales Tax Number (can be blank)
2. Income Tax Number (can be blank)
3. Registration number Company

It is often mandatory for companies to mention customer's IC/Passport Number, Gender, Nationality, Birthdate and Social Security Number
Please add in tables Customer (Person) and Supplier (Person):
1. Gender
2. Birthdate
3. Nationality
4. Ic/Passport Number
4. Social Security Number

Thanks in advance

Frans van der Star

**Comment by neilLasrado** [comment]
You can add a custom field for this. There are many countries where this is not mandatory. 
Please let me know if adding custom field helps.

**Comment by star39** [comment]
Thanks will give a try

**Comment by star39** [comment]
Indeed within extra information this can be added, but I am wondering will it be much nicer if those data can be filled in designated fields? The same with in setting your own company.

**Comment by nabinhait** [comment]
Please add those fields by creating custom fields and fetch them in transactions using small custom script. To know more about custom field and custom script, please check following links:

https://erpnext.com/user-guide/customize-erpnext/custom-field
https://kb.frappe.io/kb/customization/fetch-custom-field-value-from-master-to-all-related-transactions
