### ISSUE TITLE
ERPNext : Tax in sales invoice

### ISSUE THREAD

**Issue by estud** [frappe/erpnext#2951]
Hi! I have made a TAX rule according to my needs but I am having difficulty in producing it in the sales invoice. 
the sales_invoice doc does not have excise duty and VAT mentioned individually.
Also, I want to print 'total excise duty in words'.
Please refer to the image attached. For now, I have labeled them as a3, a4 etc. Can anyone guide me from here? 
The image is a screenshot of custom print format of my sales invoice. 
![screenshot-192 168 1 8 2015-03-11 11-46-31](https://cloud.githubusercontent.com/assets/10169894/6612630/c9505082-c8a5-11e4-8ae5-a8292dc18da1.png)

**Comment by PawanMeh** [comment]
This seems like a custom print format requirement, kindly post on [discuss](discuss.erpnext..com), someone maybe able to guide you.
