### ISSUE TITLE
Cannot disable Salary Structure

### ISSUE THREAD

**Issue by barredterra** [frappe/erpnext#29546]
### Information about bug

**Salary Structure** has a field _Is Active_, that is used in filters and queries. However, there is no way to set it to "No" (inactive).

User Story: I have an existing **Salary Structure**, but after a couple of months a **Salary Component** changes. I create a new **Salary Structure** and assign it to the **Employee**. How can I disable the old **Salary Structure** that is no longer needed?

### Module

HR

### Version

ERPNext / Frappe v13.16

### Installation method

easy-install

**Comment by Ponyooooo** [comment]
on the V13 the salary component with Statistical Component is not showing. Can the system still computes the formula even though it is not encoded in the salary structure?

**Comment by barredterra** [comment]
@Ponyooooo try posting your question on discuss.erpnext.com
