### ISSUE TITLE
[V14] HR module - Home page error

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#29550]
### Information about bug

Error message when accessing the home page

<img width="1110" alt="Screenshot 2022-02-01 at 12 17 34 PM" src="https://user-images.githubusercontent.com/910238/151924328-2a034965-39ec-4f8d-90c1-bd22d5c37523.png">

### Module

HR

### Version

ERPNext 14

**Comment by ruchamahabal** [comment]
@umairsy seems to be working fine for me. It was showing up on all workspaces yesterday (probably there was a framework issue)

![image](https://user-images.githubusercontent.com/24353136/151924808-c458d257-1a7c-4dc2-84fc-a866f019866f.png)

**Comment by umairsy** [comment]
reload brought it back. Hope it's fixed in the core. Thanks @ruchamahabal
