### ISSUE TITLE
"Create >> Work Order" option visible for Cancelled BOMs

### ISSUE THREAD

**Issue by nidhipurohit11** [frappe/erpnext#29569]
### Information about bug

Created BOM for an item and then canceled it. Still getting an option to create a work order from it, which if clicked asks for BOM.

![Screenshot 2022-02-01 at 5 19 45 PM](https://user-images.githubusercontent.com/82337328/151964864-a9da9e1e-09a3-4ddc-bc2a-d3768ee805f3.png)

Instead this option should not be visible for the canceled BOM. Also, + sign can be removed from connections for other dependent doctypes too.

### Module

manufacturing

### Version

ERPNext: v13.19.0 (HEAD)
Frappe Framework: v13.19.0 (HEAD)

### Installation method

FrappeCloud

**Comment by ankush** [comment]
> Instead this option should not be visible for the canceled BOM. Also, + sign can be removed from connections for other dependent doctypes too.


This kinda weird cause frameworks adds these by default and dashboards can't conditionally remove it AFAIK.
