### ISSUE TITLE
Sales Order NO in Purchase order Item selection

### ISSUE THREAD

**Issue by adgency** [frappe/erpnext#2957]
I have this scenario, 
client makes a sales order of 10 boxes of a product A.
We create a delivery note.
We keep track of batch numbers in the warehouse of all the products. And of course one product can have more batch numbers. 
And we want to add 5 boxes of product A from batch ALFA and 5 boxes of product A from batch BETA.
This means adding two rows of the same product but with a different batch. Which is perfectly fine. 
But in order for the row item to be associated with the sales order, we need to populate the table with the From Purchase Order button. 
This is ok with only one product, but with more products, it gets VERY confusing and creates a space for an error.

Is it somehow possible to either duplicate an item row in the delivery note (thus keeping the Sales Order NO), or edit the Sales order Number in the manually added Row?

Thank you

**Comment by umairsy** [comment]
It will be simplified this https://github.com/frappe/erpnext/issues/8617
