### ISSUE TITLE
Unallocated amount is inaccurate on multi-currency Payment Entry

### ISSUE THREAD

**Issue by Archais** [frappe/erpnext#29595]
### Information about bug

The issue is that when you are processing a payment entry in a currency other than base, the unallocated_amount can end up being inaccurate, especially with higher exchange rates, e.g. 210 : 1.

In my example of the issue we are running a base currency of USD and we are receipting payment in ZWL. The customer has paid us ZWL$1,160,250.00 at an exchange rate of 210:1 (represented in ERPNext as 0.004761905) which evaluates to USD$5,525.00. This part is accurate, however because ERPNext does the allocations in base currency then converts back to the selected currency to give you your unallocated_amount, we get a value of ZWL$1,160,249.94. So we are losing ZWL$0.06 on the transaction but there is no USD difference because when converted it is less than USD$0.01. Thus there is a loss in value of the customer's money without the value going anywhere.

### Module

accounts

### Version

Frappe version - 13.19.0
ERPNext version - 13.19.0

### Installation method

manual install

**Comment by fproldan** [comment]
👍🏻
