### ISSUE TITLE
'Salary structure' and 'salary slip' get made for employee before 'Date of joining'.

### ISSUE THREAD

**Issue by geetanjalishitole** [frappe/erpnext#2959]
Module:- HR
Steps:- 
1. Create new employee. Keep "Date Of Joining" as - 1 Feb 2014
2. save form 
3."Make salary Structure" for that employee by selecting 'From date - 1 Jan 2014' And "To Date- 31Jan 2014
4. Save form
5.check salary structure form get save .

**Comment by neilLasrado** [comment]
Was able to replicate... will add a validation...
