### ISSUE TITLE
'Timezone' Problem:- At the time of submitting "Delivery Note". 

### ISSUE THREAD

**Issue by ShraddhaRanjane** [frappe/erpnext#2960]
Scenario:-
Suppose ,I am living in India(Pune)
1. In system Setting :- I have set TimeZone= 'America_New York'  and save
2. I made Stock Entry For item "Y" with purpose -'Material Receipt' For qty=5 by using Todays date i.e 16 March 2015 
3. Now made 'sale order' ->in that 'Delivery date' - also kept 16 March 2015 and save form
4.And made 'Delivery Note' 
5. At the time of submitting "Delivery Note" .It giving error like:-
Negative Stock Error (-2.0) for Item Item Y in Warehouse Stores - I on 2015-03-16 5:15:17.666850 in Delivery Note DN-00011
Did not save

**Comment by nabinhait** [comment]
It is not related to timezone. Check the time entered in Material Receipt, it should be before the time entered in Delivery Note. The message should show the time as per timezone "America_New York".
