### ISSUE TITLE
UX: Inducing ideal practice on the sales/purchase side for linkages among the documents.

### ISSUE THREAD

**Issue by sharmanakul** [frappe/erpnext#29608]
Consider that a sales invoice is created against a sales order. Now in the event that the user splits any of the items in the sales invoice item table, the newer row of the item does not get linked with the sales order.

Now consider another use case in which the user directly creates a sales invoice without creating the sales order. Even though there may exist some sales orders which are corresponding to the same customer and items, the sales invoice does not get linked with the sales orders.

In both the cases above, the sales orders are just left hanging and the status of the sales orders do not get updated.

**Possible Solution:**

When a user directly create sales invoice/delivery, inform him something on these lines:
“This invoice is not linked to any Sales Order. For better tracking of deliveries and payments, we recommend making an invoice from a Sales Order or linking one. Click here to create a new Sales Order”
Also if he chooses not to proceed with the sales order, then inform the user of the related transaction settings.
![image](https://user-images.githubusercontent.com/88872881/152290042-456ce190-2dc3-4258-96bf-1248f9340c34.png)

**Comment by jalajc** [comment]
@sharmanakul Thanks for taking this up.
Infact, this has been a daunting tasks for my team to link sales invoices, delivery notes to sales_order.

1. I would infact suggest a button or some quick UX field to update the linking. One more thing...
2. So if, say I update this linking from backend which is very very complicated ( as linking works both at Sales Order,Sales Invoice, Delivery Notes as well as their Item levels), the invoice percentage as well as delivery percentages are not updated.
...so with update of linking of documents, invoice and delivery percentage should also get updated.

**Comment by OMNERP** [comment]
@jalajc 
I dont think that it is about linking an existing sales invoice/Delivery note with an exiting sales order. I guess it is just popping up some alert on the UX.

But if the option to link the SI/DN to existing Sales order is provided then it would be a great achievement indeed. hoping to see this feature in the near future.
