### ISSUE TITLE
Update of documentation related to creating opening stock for serialized items

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#29612]
It now seems possible to create opening stock/and adjustments using Stock Reconciliation.

There's documentation : https://docs.erpnext.com/docs/v13/user/manual/en/stock/articles/opening-stock-balance-entry-for-serialized-and-batch-item

That says this can only be done via Stock Entry of Type Material Receipt

**Comment by Ponyooooo** [comment]
@muchai I am also confused with this. have you confirmed it with any of the ERPNEXT? If it is true that stock reconciliation can already be used for opening stocks that are serialized or with batch numbers?
