### ISSUE TITLE
New Expense Claim

### ISSUE THREAD

**Issue by mariafurqan** [frappe/erpnext#29617]
### Information about bug

While adding the expense approver name, the name removes by itself and is not given the option of adding the name of the approver. 

![image](https://user-images.githubusercontent.com/58623315/152313823-c3c07d16-3691-41b2-8092-7d623686f7ba.png)

### Module

HR

### Version

http://ec2-18-205-155-1.compute-1.amazonaws.com:8000/app/expense-claim/new-expense-claim-1

**Comment by sharmanakul** [comment]
@Sadiyahh you will have to set the expense approver in the employee master. 
![image](https://user-images.githubusercontent.com/88872881/152325180-a233ba0e-8047-4971-a3df-4b948f476c96.png)

OR in the deparment
![image](https://user-images.githubusercontent.com/88872881/152325255-0d345ab9-ff36-4e1d-82a5-c4791578bcae.png)

and then link the department with the employee

**Comment by mariafurqan** [comment]
Thank you
