### ISSUE TITLE
Batch Split error AttributeError: 'StockEntry' object has no attribute 'shift'

### ISSUE THREAD

**Issue by andrewhartono** [frappe/erpnext#29620]
### Information about bug

Error when creating split batch

![batch split 2](https://user-images.githubusercontent.com/3880725/152325624-ff10cf32-daea-4b31-9f7c-f31939ad8555.jpg)

![batch split 1](https://user-images.githubusercontent.com/3880725/152325678-d46824d9-1914-4771-8605-f9d7ae691c3f.jpg)

AttributeError: 'StockEntry' object has no attribute 'shift'

### Module

accounts, stock, buying

### Version

ERPNext: v13.19.0 (HEAD)

ERPNext Support: v0.2.1 (master)

### Installation method

FrappeCloud

**Comment by ankush** [comment]
`shift` doesn't exist anywhere in batch / stock entry code. 

When this happens click on "copy error to clipboard" / report and share content here.

**Comment by andrewhartono** [comment]
```
### Request Data
```
{
	"type": "POST",
	"args": {
		"item_code": "ajoss1",
		"batch_no": "B840C3D",
		"qty": 2,
		"warehouse": "Warehouse1 - ACH"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/erpnext.stock.doctype.batch.batch.split_batch"
}
```
### Response Data
```
{
	"exception": "AttributeError: 'StockEntry' object has no attribute 'shift'"
}
```

**Comment by andrewhartono** [comment]
@ankush since the issue is closed, should i open new issue or continue with this threat? can it be opened again?

**Comment by ankush** [comment]
@andrewhartono share the full traceback, please. The message you shared doesn't contain the traceback. 


Is it possible that this is error from your customization? (like servicer script maybe?)

**Comment by andrewhartono** [comment]
@ankush i use frappecloud so there is no customization
Frappe Framework: v13.23.0 (HEAD)
ERPNext: v13.23.3 (HEAD)
how to get the full traceback? there is no error log on this error

**Comment by deepeshgarg007** [comment]
@andrewhartono Just checked this and it worked fine for me, please add more info to replicate and reopen if the issue still persists
