### ISSUE TITLE
OKR

### ISSUE THREAD

**Issue by dgram** [frappe/erpnext#29633]
**Is your feature request related to a problem? Please describe.**
To better plan business goals & manage company wide goals it would be a pretty nice feature to have implemented the OKR (objective key results system).

I think this would describe the case perfectly: https://en.wikipedia.org/wiki/OKR

A good start will be a similarity to the project progress (task progress), track how much of the goals have been achieved.

If the feature request resonates, i'm open for an discussion about the features.

**Comment by sharmanakul** [comment]
hi @dgram , thanks for creating the request.

I'd suggest you start defining your use-case and the user story. Once that is ready, then the community can help in validating. I saw there is already a discuss post on this.

**Comment by blewsky** [comment]
bump

**Comment by ankush** [comment]
1. Not suitable for ERPNext. Someone can make a separate Frappe app for this. 
2. Kinda achievable by project or quality module. It's not called "OKR" but it has similar functionality to capture key results. 

context: https://www.youtube.com/watch?v=207S3celYqA
