### ISSUE TITLE
Unclear Error Message in Sales

### ISSUE THREAD

**Issue by wojosc** [frappe/erpnext#29644]
### Information about bug

When addid multiple rows of the same item in a sales invoice you get an error on save
![grafik](https://user-images.githubusercontent.com/22279621/152575191-9f7de3f9-632b-4bfa-8c0d-303e05b29278.png)

This can easily be configured in Sales Settings.

The Error Message should be more clear with a hint to the Selling Settings Page.

### Module

selling

### Version

ERPNext: v13.16.1 (version-13)

Frappe Framework: v13.16.0 (version-13)

**Comment by wojosc** [comment]
keep open

**Comment by wojosc** [comment]
keep open.

**Comment by deepeshgarg007** [comment]
@wojosc This issue should be solved via https://github.com/frappe/erpnext/pull/31639
