### ISSUE TITLE
price list error while making PO from material request

### ISSUE THREAD

**Issue by neilLasrado** [frappe/erpnext#2964]
When converting a Material Request to a Purchase Order, the default Supplier is applied correctly, however the default Price List for that supplier is not - instead, Standard Buying is applied (see picture).
In the example, the Roberd's Price List should be applied.
The issue does not occur when creating a new Purchase Order from scratch (without converting from Material Request).
When converting from a Quote to a Purchase Order, the issue does not occur either.

Taken via discuss https://discuss.frappe.io/t/default-price-list-issue-when-converting-from-material-request/4997

**Comment by nabinhait** [comment]
fixed.
