### ISSUE TITLE
Item's Rate is updated automatically to the defualt value after changing the date in Sales Invoice

### ISSUE THREAD

**Issue by MujtabaMohsin** [frappe/erpnext#29640]
### Information about bug

Hello, I'm making a new sales invoice manually and after saving it, I tried to change the date of the sale invoice but what happens is that the rate of the items I added goes back to the original (default item price) after changing the date as you can see in the photo below:
https://i.postimg.cc/0jM3KCb9/1.png

### Module

accounts, stock

### Version

ERPNext: v13.19.0 (version-13)
Frappe Framework: v13.19.0 (version-13)

**Comment by OMNERP** [comment]
Yes. The rate is changing automatically to the price list rate regardless of even the sales order rate. This is bug and need to be rectified.

**Comment by swistakm** [comment]
This has been closed by stale bot but it is a valid issue that haven't been fixed.
