### ISSUE TITLE
Project Template improvements

### ISSUE THREAD

**Issue by dgram** [frappe/erpnext#29658]
While working with project templates, i crystallized some features, which make the working with project templates much more efficiently and clearer. (described below)

1. Naming
Make name as a subject, so we can rename the project name, instead make the name(id) as naming series.

2. Restrictions
Project Templates should be assigned to companies and/or departments. While having an overview over all proejct templates as an ceo, department managers should only see and manage their specific departments templates.

3. Project to Project Template
While we have in projects all the features, needet to plan a project within there tasks efficiently (while the features are missing in project templates, see points below), it can be a nice feature to make project templates from projects itself.

4. Project Template Tree View
A part of planning the processes of a company, it would be nice to have the possibility to let plan and show the project templates (sops, audits, templates) as an tree view.

   For example:
   - **Marketing** (group)
       - **SEO** (group)
          - SEO Audit (project)
          - etc. etc.

5. Empty Project
To make an overview of all project templates while brainstorming, it would be nice to add project templates without defining tasks. My workflow essentially is, first to brainstorm & define the project templates as an overview business wide.

6. Task handling
    - View Gantt-Chart
While its possible to view and plan projects by gantt-chart, i find it's essential to have the feature for the project templates (but instead of set the date directly in template gantt-chart it should be set the "day" of -start & -end). This feature would make the planning so much more effectively and clearer.

    - View Task Tree View
Next in my oppinion (i love the tree view to plan), it could also be great to have the task tree view for project templates, this would make it also an great overview. (what i discover, it makes it a little bit hard, when forgetting to check the "template-checkbox", eventually this can be checked by default when in project-template?)

**Comment by prononext** [comment]
It would be really nice to see this project template improvements. 
Espacially so that it is not needed to ceate real task which have a influence on reporting. Template Tasks for the Template Project is needed. 

Also a planning functionality like Tree-View ang Ghant and some timing functionality for the Project-Template Tasks is needed so that this does not have to be set manually after creating from template. 

Looking forwared to see this growing.

**Comment by prononext** [comment]
**Please reopen this.**
