### ISSUE TITLE
Table breaks between two pages in print format for the Right-to-left languages

### ISSUE THREAD

**Issue by MujtabaMohsin** [frappe/erpnext#29672]
### Information about bug

Hello, I'm facing a problem while printing the items' table, that the table breaks between the two pages when there are many items and it needs multiple pages. 
this issue only occurs if the print format's default language is **Right-to-left** like (Arabic). 
However, when, as you can see in the photo below.
I used Page Break but still the same issue. I tried adding some CSS styles but also the same.

![8987c1a9b5f82aa745803cf05c37cbd020b5ebf9](https://user-images.githubusercontent.com/64940728/152698981-332e8647-8552-4332-8b94-59608d0cbebf.png)

![7468adff94962ad93fae30ebbd647e413e4d7f45_2_1035x481](https://user-images.githubusercontent.com/64940728/152698986-b035397b-5ad2-41f4-8ded-8c34242001ca.png)

### Module

other

### Version

ERPNext: v13.19.0 (version-13)
Frappe Framework: v13.19.0 (version-13)

### Installation method

manual install

**Comment by taha-azzan** [comment]
Any Update
