### ISSUE TITLE
Request to change from close on sales order to halt

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#29676]
![image](https://user-images.githubusercontent.com/1822868/152747250-72bf39eb-e694-44f3-8eef-a232c5e70ec0.png)

Request to change the above to halt from close

Close can mean to close a/the deal

Saw users getting confused on the purpose of the feature, i.e. assuming it meant the sale had been closed/won.

**Comment by ankush** [comment]
"close" or the common term "Short close" is used to refer to orders that are closed before completion. idk how halt makes sense here, that's similar to "hold". 

Also "close" is consistent with the rest of the transactions.

**Comment by muchai** [comment]
Was aiming for a word that wouldn't be misconstrued to mean: **to close a deal**: to sign or to complete a business negotiation or contract.

Halt may be the wrong alternative.
