### ISSUE TITLE
Quantity variation allowance in production order with referece to sales order

### ISSUE THREAD

**Issue by acrosmehul** [frappe/erpnext#2970]
In my process I always need to add some extra quantities in production order than sales order. But while featching items from sales order I can not make production order for more than sales order quantities.

I am suggesting for quantities variation allowance in production order.

**Comment by nabinhait** [comment]
- [ ] Add "Over Production Allowance Percentage" field in Manufacturing Settings
- [ ] Validate PRO ORDER qty against SO qty considering allowance percentage

**Comment by sagar30051991** [comment]
I think this(Add "Over Production Allowance Percentage" field in Manufacturing Settings) functionality is not working.I have created SO for 10 QTY and at the time of Production Order Start add the 15Qty.it will not allow adding more than the manufactured qty(SO Qty).
I Add "Over Production Allowance Percentage" is 50 in Manufacturing Settings.
