### ISSUE TITLE
Onboarding steps in the workspace 'Home'

### ISSUE THREAD

**Issue by sharmanakul** [frappe/erpnext#29720]
### Information about bug

In the step 3 of onboarding
<img width="766" alt="image" src="https://user-images.githubusercontent.com/88872881/153128481-8d16816c-9778-4288-8a9d-6f569068c49a.png">

click on 'Learn more about data migration', a blank modal appears:
<img width="810" alt="image" src="https://user-images.githubusercontent.com/88872881/153128675-c416dccb-379b-43b3-9e48-aea2ef982bea.png">

### Module

other

### Version

v14

**Comment by ankush** [comment]
fixed via https://github.com/frappe/frappe/pull/16890
