### ISSUE TITLE
Accidentally changed the module of Users doc type

### ISSUE THREAD

**Issue by a157147899** [frappe/erpnext#29772]
Hi guys,

As the title says that I accidentally changed the module of Users doctype to a custom module which even the administrator doesn't have permission, now I can't access 'DocType' to change it back and almost all the other modules are not permitted to access. I guess it's because the Users is the core of the whole system, everything is validated based on it.

Got the error constantly after login in as administrator.
![image](https://user-images.githubusercontent.com/1812136/153745083-c6d5c71f-4cfc-4e5a-805f-24d608ade124.png)

Question: Is there any way I can change it back? Or I will have to change it from the database directly.

Suggestion: It might be worth adding some limits/validations to prevent users from doing this.

Any help would be much appreciated.

**Comment by ankush** [comment]
use https://discuss.erpnext.com/
