### ISSUE TITLE
Link field items in Webform not getting translated

### ISSUE THREAD

**Issue by mf0wzi** [frappe/erpnext#29785]
### Information about bug

I have a link field in a web form that contains data in English I also added the translation for those items in the translation list for the languages. the translation works perfectly on the desk but the webform link field does not show the translated items 
please find the picture below showing what I mean

![ERPnext link](https://user-images.githubusercontent.com/30725615/153858915-d8fd90a1-f912-4b67-a594-dc1f69528bb0.jpg)

![ERPnext link](https://user-images.githubusercontent.com/30725615/153859116-7371a2d8-db87-4863-9e17-94419a5133f3.jpg)

### Module

portal, other

### Version

Frappe Version:- v13.20.1 
ERPNext Version:- v13.20.1 

### Installation method

manual install

**Comment by sliwkawsieci** [comment]
version 14 has the same issue
