### ISSUE TITLE
Pricing Rule get reset for Sales Invoice / Credit notes

### ISSUE THREAD

**Issue by erpcloudsystems** [frappe/erpnext#29798]
### Information about bug

Pricing Rule for Sales Invoice is working well
but for  return / Credit Notes it gets reset after make qty in negative
please see action in video 

https://www.youtube.com/watch?v=7Pf5JLofvnk

and following are the pricing rule settings

![pr1](https://user-images.githubusercontent.com/11355558/153995826-660e76e9-2b76-4188-81eb-c30cb0ca3776.png)

![pr2](https://user-images.githubusercontent.com/11355558/153995848-7b13ce18-4a1c-490d-9ba1-6c56d821eeb0.png)

![pr3](https://user-images.githubusercontent.com/11355558/153995879-2cd2da38-cc1b-4c46-ac79-66845680fa57.png)

### Module

selling

### Version

ERPNext: v13.20.1 (version-13)

Frappe Framework: v13.20.1 (version-13)

### Installation method

easy-install

**Comment by erpcloudsystems** [comment]
its still exist

**Comment by nabinhait** [comment]
fixed in latest version
