### ISSUE TITLE
GSTR1 B2C, 5A,5B,7 Shows Empty

### ISSUE THREAD

**Issue by Sudhegan** [frappe/erpnext#29796]
### Information about bug

GSTR1 - B2C Large and Small Invoices Shows Nothing and It does not Include in GSTR3B, but in "GST Itemised Sales Register" Shows the  missing B2C  Details

### Module

accounts

### Version

erpnext - version 13.20.1
frappe - version 13.20.1

### Installation method

manual install

**Comment by kvt** [comment]
I faced same problem. when I linked address with company, it started showing in report.

**Comment by Sudhegan** [comment]
address are already linked with company but nothing shows up

**Comment by mohsinalimat** [comment]
I am facing issue like below link.

https://github.com/frappe/erpnext/issues/30465

**Comment by Sudhegan** [comment]
so my understanding is a customer without GSTIN doesn't shows up in B2C Large or small Invoices, but it is not correct

**Comment by deepeshgarg007** [comment]
@sudhegan The customer must have at least the GST State form them to show up in the B2C report, other customers are using it and it works fine for them so surely there is some config issue
