### ISSUE TITLE
Print Format Depend on a Select Field

### ISSUE THREAD

**Issue by nipunanr** [frappe/erpnext#29801]
It is better if can add feature to select the print Format depend on a Select Field value. Yes, It can select when printing. But with the workload, wrong print formats gets print. In our case, we have many fields hiding and showing depending on the select field. So it will be easy it can change the print format according to Select field value.

**Comment by szufisher** [comment]
it is kind of default print format based on python based condition, I ever implemented this feature, but not accepted into core
https://github.com/frappe/frappe/pull/15350
