### ISSUE TITLE
Project Costing

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#2980]
- [ ] New DocType `Activity Cost`
- [ ] Fields: Employee, Activity Type, Billing Rate, Internal Rate

---

Time Log:

- [ ] Add Billing Rate and Internal Rate
- [ ] Link to Project
- [ ] update total cost in Project / Task

---

In Project

- [ ] Add `Total Activity Cost`, sum of all time logs
- [ ] Add `Total Expense Claims`
- [ ] Add custom button `Show Time Logs`
- [ ] Add `Activity Budget`

---

- [ ] In Expense Claim, add Employee link
- [ ] In Expense Claim, add Project
- [ ] Update total project activity cost

**Comment by neilLasrado** [comment]
- [ ] New DocType Activity Cost
- [ ] Fields: Employee, Activity Type, Billing Rate, Internal Rate

-----------------------------------------------------------------------------------
Time Log:

- [ ]  Add Billing Rate and Internal Rate
- [ ]  Link to Project
- [ ]  update total cost in Project / Task

----------------------------------------------------------------------------------
In Project

- [ ] Add Total Activity Cost, sum of all time logs
- [ ] Add Total Expense Claims
- [ ] Add custom button Show Time Logs
- [ ] Add Activity Budget

------------------------------------------------------------------------------------
In Expense Claim

- [ ]  In Expense Claim, add Employee link
- [ ]  In Expense Claim, add Project
- [ ]  Update total project activity cost
