### ISSUE TITLE
Brazilian Chart of Accounts

### ISSUE THREAD

**Issue by MaxMorais** [frappe/erpnext#2982]
You can get it here!

https://gist.github.com/MaxMorais/56c1a55c1ddab5e92035

PS: I know that the names starting with numbers, isnt beautifull, but is a legal requirement, and it is fully compatible with the reports that needs be sended to the gov!

Good job!

**Comment by vrms** [comment]
this does not look like actually being an issue. Therefore I'm closing this.
If you want to reopen please kindly elaborate
