### ISSUE TITLE
Purchase receipt Showing error

### ISSUE THREAD

**Issue by WConsult** [frappe/erpnext#2983]
Hi, I am setting a new erp account but with a glitch. I raised a PO and then did a purchase receipt. Upon submitting the receipt I got an error saying No accounting entries were made. What did I miss in the set up.

**Comment by nabinhait** [comment]
System did not found accounting ledger for the warehouse selected in the Purchase Receipt. If there are ledger exists for each warehouse, open those record and check account type value, it should be Warehouse.

**Comment by WConsult** [comment]
The accounting ledger exist. Please help check www.fx.xbs360.com Username: gbenga@sapphirevirtual.com Password: gbenga01.Please help resolve. Thank you.Gbenga.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Nabin HaitSent: Friday, 20 March 2015 11:44To: frappe/erpnextReply To: frappe/erpnextCc: WConsultSubject: Re: [erpnext] Purchase receipt Showing error (#2983)System did not found accounting ledger for the warehouse selected in the Purchase Receipt. If there are ledger exists for each warehouse, open those record and check account type value, it should be Warehouse.

—Reply to this email directly or view it on GitHub.

**Comment by nabinhait** [comment]
Please do not post login credential here.. Github is publicly available to anyone.

**Comment by nabinhait** [comment]
Master Name is not correct in the accounting ledger. Please reselect and save again.
