### ISSUE TITLE
Incorrect pricing rule filtering on selecting first item when item is added twice 

### ISSUE THREAD

**Issue by yadavyk** [frappe/erpnext#29831]
### Information about bug

Issue : When a promotional scheme such as Buy 1 Get 1 is created and used in SO and the corresponding item is added twice on another row , the free item is fetched only for first row entry

Steps to reproduce : 

1. Create a Buy 1 Get 1 Promotional Scheme for Item A with item B as free. A corresponding pricing rule would be created
2. Created a SO with this item A and free item B should be added
3. Now add item A again on another row 
4. Item B should have been added as free item. However it isn't added. However an additional pricing rule entry for same pricing rule is made in the Pricing Rule section 

Screen Recording : 

![Test case 3](https://user-images.githubusercontent.com/32797974/154252751-edf9a764-9864-488e-9be5-f3b7fd4de967.gif)

Observed Behaviour : The free item is added only once for first row entry 

Expected Behaviour : The free item should have been added for the second row entry as well and pricing rule shouldn't appear twice. 

### Module

selling

### Version

V13.21.0

**Comment by nextchamp-saqib** [comment]
This will be fixed later, I don't think I'll make it for the v14 beta release

Also, this exact scenario is not practical
The workaround now is to just increase the quantity and not add another item
