### ISSUE TITLE
Purchase Order Item Rate is manipulated by exchange rate.

### ISSUE THREAD

**Issue by dj12djdjs** [frappe/erpnext#29840]
### Information about bug

When creating a purchase order, changing the currency, or changing the exchange rate will manipulate the rate input by the user.

**Example 1:**
You've created a purchase order, added all the items, qty, and rates. You realize the currency is incorrect. You then change the currency. This will effect all the rates input by the user making the document total incorrect.

https://user-images.githubusercontent.com/29856401/154300956-cc24899b-c46c-42db-a2a6-5643cfe8c074.mp4

**Example 2:**
When modifying the exchange rate. The rate will be manipulated.

https://user-images.githubusercontent.com/29856401/154301331-34b81474-3ca9-4be8-9d3d-a54048e4eff1.mp4

**Expected Behavior:**
1. When changing the currency, the rate input by user should remain the same. Only the rate in company currency should be changed.
2. When changing the exchange rate. Only the rate in company currency should be changed.

**Additional Details:**
This occurs on Purchase Invoice as well. This is where it becomes an annoyance.
When we create a purchase invoice from purchase order, sometimes the purchase order is from months back. We set the purchase invoice with the latest exchange rate and all the prices are updated making it not match the physical invoice. 

### Module

buying

### Version

ERPNext: v14.0.0-dev (HEAD)

Frappe Framework: v14.0.0-dev (HEAD)

### Installation method

FrappeCloud

**Comment by dj12djdjs** [comment]
bump

**Comment by dj12djdjs** [comment]
https://github.com/frappe/erpnext/issues/34680

**Comment by ruthra-kumar** [comment]
@dj12djdjs 
Closing this. Do re-open if it persists in latest v15.
