### ISSUE TITLE
Production plan is getting 'completed' even though some quantity is pending

### ISSUE THREAD

**Issue by sharmanakul** [frappe/erpnext#29845]
### Information about bug

1. Created Production Plan
2. Independently added two items with planned qty as 40 and 30 respectively.
3. Submitted
4. Two work orders were created against the production plan
5. In both the work orders, qty to manufacture was changed to 30 and 20 respectively
6. Finished the work orders.
7. Navigate to the production plan

<img width="1300" alt="image" src="https://user-images.githubusercontent.com/88872881/154416104-d033cf49-4243-4f89-a86e-0fe2aa63c4f8.png">

### Module

manufacturing

### Version

v13

**Comment by ankush** [comment]
This is very weird because of overproduction 🥲 I think combining two conditions should give ideal results. 

produced_qty >= planned_qty for ALL items AND all work orders are completed.
