### ISSUE TITLE
Purchase Order not Saved

### ISSUE THREAD

**Issue by ruchin78** [frappe/erpnext#2984]
Hi,
I am not able to save the purchase order made with the reference of Material Request where Minimum Order quantity is defined for the Purchase Order.

I have created a purchase order for item X with 30 quantity with reference to Material Request ABC
Item Quantity in Material Request is 30
Minimum Order Quantity in Item Master is also 30
While Saving system says 
"Item #310-000014: Ordered qty can not less than item's minimum order qty (defined in item master)."

Whereas I can save the PO if I create the same without Material Request's reference.
I am using ERPNext: v4.24.1.

Please resolve this issue.

**Comment by nabinhait** [comment]
Fixed via #2985
