### ISSUE TITLE
Issue with Payment Terms Status for SO report

### ISSUE THREAD

**Issue by centaur78** [frappe/erpnext#29843]
### Information about bug

Hi @ruthra-kumar 

I have just tried the report based on you PR #29137 but if you look any invoice prior to May 2021 shows as overdue and Payment Amount and Paid Amount as zero ( where these are already invoiced and paid in full )???

![image](https://user-images.githubusercontent.com/1904802/154406243-f6ab5ab7-1e3f-49d9-8086-9220a8b56590.png)

### Module

other

### Version

Develop Branch

**Comment by centaur78** [comment]
Hi @ruthra-kumar 

Upon further testing as in the above image.. for example

SO21-00010 has a base amount of RO 649.118 and subsequent SI21-00021 also has the invoiced amount as RO 649.118.

Though the payment was in advance... it was partial paid with base amount as R.O 637.643. So there is a difference of RO 11.475.

But the status above shows as Completed ???

Is this how its supposed to show ?

**Comment by ruthra-kumar** [comment]
@centaur78  The Report only considers associated invoices for calculating payment term statuses. In your example case, as you mentioned the invoiced amount is equal to the Sales Order amount, the status is considered as 'Completed'.

> but if you look any invoice prior to May 2021 shows as overdue and Payment Amount and Paid Amount as zero ( where these are already invoiced and paid in full )???

There are no such date restrictions. Most likely case, is the SO's with overdue statuses doesn't have any invoice created for them.

**Comment by centaur78** [comment]
Hi @ruthra-kumar 

> Most likely case, is the SO's with overdue statuses doesn't have any invoice created for them.

All SO have sales invoice with payment associated with them.  This goes all the way back to 2019 from the start of the company as you see below..

![image](https://user-images.githubusercontent.com/1904802/155544468-fd523cc8-d544-4e79-b944-926785f1d622.png)
![image](https://user-images.githubusercontent.com/1904802/155542972-6e00b0ee-2e37-4fd3-9f7c-f401cebd9ee6.png)
![image](https://user-images.githubusercontent.com/1904802/155543296-dad90686-3301-4614-938a-040e50d8facc.png)

I can understand 1 or 2 invoices having some kind of issue... but 45 invoices ???
