### ISSUE TITLE
Accounting Dimension Error in Payment Entry

### ISSUE THREAD

**Issue by abdulansari2007** [frappe/erpnext#29864]
### Information about bug

I have created sales order as an Accounting Dimension but while making a payment entry, the following error pops up when we click in the sales order feild on payment entry form. No solutions till now.

### Module

accounts

### Version

Frappe version 13.20.1
Erpnext version 13.20.
![Untitled](https://user-images.githubusercontent.com/98683711/154490449-80bbd593-c4af-4466-80eb-6eee84aae263.jpg)
1

### Installation method

easy-install

### Relevant log output / Stack trace / Full Error Message.

```shell
%% is not a valid date string.
```

**Comment by deepeshgarg007** [comment]
@abdulansari2007 Sales Order as an accounting dimension doesn't make much sense. Voucher No is by default added in the GL entries when payment is made against a sales order. Not a good idea to use transactions as an accounting dimension. They will conflict with the queries if added as an accounting dimension. Much cannot be done here. Closing this issue
