### ISSUE TITLE
TypeError: super(type, obj): obj must be an instance or subtype of type

### ISSUE THREAD

**Issue by gskishan** [frappe/erpnext#29875]
### Information about bug

Hi,
   
   Reflecting the below error while creating or amending a quotation after version updated to 13.20.1
"TypeError: super(type, obj): obj must be an instance or subtype of type"

Request team to provide the solution for above error.

Thanks & Regards

### Module

selling

### Version

13.20.1

### Installation method

FrappeCloud

**Comment by ankush** [comment]
this is an issue with a custom app monkey patching things on your bench. Unrelated to ERPNext.
