### ISSUE TITLE
Wrong GL Entry for Delivery note for manufacturing items

### ISSUE THREAD

**Issue by AlaaBadry** [frappe/erpnext#29889]
### Information about bug

All Details is described here 
https://discuss.erpnext.com/t/wrong-gl-entry-for-delivery-note-for-manufacturing-items/86225

### Module

accounts, stock

### Version

ERPNext: v13.16.0 (version-13)
Frappe Framework: v13.16.0 (version-13)

### Installation method

easy-install

**Comment by ankush** [comment]
@AlaaBadry can you go to the "stock ledger invariant check" report and select item - warehouse and share the generated report as CSV?

**Comment by AlaaBadry** [comment]
@ankush did you mean stock ledger report no report named 'stock ledger invariant check'

Here is the stock ledger

![Screenshot from 2022-02-21 16-39-33](https://user-images.githubusercontent.com/26534497/154976658-d1122621-86e5-434c-b9d1-fbf215ac6ebf.jpg)

**Comment by AlaaBadry** [comment]
@ankush any update
