### ISSUE TITLE
[V5][Urgent] Cannot save any entry in version 5

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#2989]
Steps:

1. New Sales Order.
1. Entered details.
1. Clicked on Save

Page just gets freezed on save. Same issue replicated when tried creating Purchase Receipt. I presume it exist in every form.

Error message:
![screen shot 2015-03-23 at 1 54 32 pm](https://cloud.githubusercontent.com/assets/910238/6776479/0426dbdc-d165-11e4-9a8e-f3cf1d3be1ff.png)

**Comment by rmehta** [comment]
check latest

**Comment by nabinhait** [comment]
fixed
