### ISSUE TITLE
Unable to enrol students

### ISSUE THREAD

**Issue by madappally** [frappe/erpnext#29890]
### Information about bug

Unable to enrol students

### Module

education

### Version

ERPNext: v13.20.1 (version-13)
Frappe Framework: v13.20.1 (version-13)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
### Trackeback

Syntax error in query:
UPDATE `tabStudent` SET `joining_date`=((datetime.date(2022, 2, 20),),),`modified`=%(param1)s,`modified_by`=%(param2)s WHERE `name` IN (%(param3)s)
```

**Comment by foranastes** [comment]
```
def update_student_joining_date(self):
		table = frappe.qb.DocType('Program Enrollment')
		date = (
			frappe.qb.from_(table)
				.select(Min(table.enrollment_date).as_('enrollment_date'))
				.where(table.student == self.student)
		).run(as_dict=True)

		if date:
			frappe.db.set_value("Student", self.student, "joining_date", date[0].enrollment_date)
```
date[0].enrollment_date returns `datetime.date(2022, 2, 3)` instead of date. Is that the problem?

**Comment by foranastes** [comment]
I found a way to fix it by changing

**Comment by madappally** [comment]
**Temporary workaround**
Add [0][0] to the end of date variable in [https://github.com/frappe/erpnext/blob/version-13/erpnext/education/doctype/program_enrollment/program_enrollment.py](url)
```date = frappe.db.sql("select min(enrollment_date) from `tabProgram Enrollment` where student= %s", self.student)```
To  ```date = frappe.db.sql("select min(enrollment_date) from `tabProgram Enrollment` where student= %s", self.student)[0][0]```
