### ISSUE TITLE
Item Group based and coupon code based Pricing Rules don't work 

### ISSUE THREAD

**Issue by yadavyk** [frappe/erpnext#29901]
### Information about bug

Issue : When using the coupon code based pricing rule on POS, it doesn't get applied 

Steps to reproduce : 

1. Create a Pricing Rule which is coupon code based and Item Group based 
2. Try applying that on POS 

Pricing Rule : 

![image](https://user-images.githubusercontent.com/32797974/154906621-b0bfd0b9-e859-44d4-9e37-c3bc27994342.png)
 
Coupon Code : 

![image](https://user-images.githubusercontent.com/32797974/154906738-1626f76d-e464-492d-a476-3ba2c7960f15.png)

Expected : Discount should have been applied and rate should have been updated dynamically 

### Module

accounts

### Version

V13.21.0

**Comment by nextchamp-saqib** [comment]
The problem exists with all the Transactions - Quotation, Sales Order, POS Invoice, and all the transaction that has coupon code field. 
I'll work on this later

**Comment by yadavyk** [comment]
@nextchamp-saqib @ankush  this is still pending. Anyone fixing it?

**Comment by deepeshgarg007** [comment]
<img width="606" alt="image" src="https://user-images.githubusercontent.com/42651287/205639820-420cb6ae-7025-4fc5-9999-20edbc520951.png">

Working on develop now, closing this
