### ISSUE TITLE
Disturbed modal while opening the POS

### ISSUE THREAD

**Issue by sharmanakul** [frappe/erpnext#29929]
### Information about bug

<img width="579" alt="image" src="https://user-images.githubusercontent.com/88872881/155062886-cceec3b6-88f6-4b1d-815b-1d11eb0b0f39.png">

### Module

accounts

### Version

v14

**Comment by yadavyk** [comment]
This is a framework issue. Reference : https://github.com/frappe/frappe/issues/15673
