### ISSUE TITLE
OR filter 

### ISSUE THREAD

**Issue by Pazdo** [frappe/erpnext#29936]
**Is your feature request related to a problem? Please describe.**
Sometimes I need to have filters set with OR connection, for example in kanban view for Tasks I would like to see Unassigned Tasks and Assigned tasks to me, but when I set filter Assigned is not set and assigned is like %mail% nothing will show as expected from AND filter.

**Describe the solution you'd like**
In filter in list view / kanban view etc. I would add option to set type operand between filters AND/OR

**Additional context**
This is my problem, as I would like to have OR operand between two filters
<img width="389" alt="image" src="https://user-images.githubusercontent.com/6991040/155087230-6e0815af-bd91-4344-897b-ffdbea70daf5.png">

**Comment by ankush** [comment]
duplicae of https://github.com/frappe/frappe/issues/5732
