### ISSUE TITLE
mark location on geolocation map from latitude and longitude value

### ISSUE THREAD

**Issue by Ambikeygupta** [frappe/erpnext#29971]
### Information about bug

hello, I want to mark the location on the geolocation map from latitude and longitude values.   i have a doctype named live location with 4 field -
1)user  --  link field with user    field name is --- user 
2)latitude  -- data field   --  field name is --- latitude 
3)longitude --  data field  --  field name is--- longtitude
4)location  -  geolocation field.

when I put the value of latitude and longitude it automatic  mark on the map. (geolocation) 
please help me to solve this.   
--  will be done server script or custom script for this ??? and what will it ?
any help will be appreciated. 

### Module

selling

### Version

13.19
13.19

### Installation method

easy-install

### Relevant log output / Stack trace / Full Error Message.

```shell
hh
```

**Comment by albadri92** [comment]
You may find something useful from this 
https://www.youtube.com/watch?v=fj6WJI3Z2Ew
