### ISSUE TITLE
[Selling Settings]Maintain Same Rate Throughout Sales Cycle doesn't work

### ISSUE THREAD

**Issue by rtdany10** [frappe/erpnext#29976]
### Information about bug

Same rate is not enforced even after enabling the setting. One can easily change the rates.

https://user-images.githubusercontent.com/52111700/155473701-94575e87-f0b0-411f-81a7-b59ec7f1f1de.mp4

### Module

Selling / Accounts

### Version

ERPNext: v13.21.0 (HEAD)
Frappe Framework: v13.21.0 (HEAD)

### Installation method

FrappeCloud

**Comment by ankush** [comment]
IIRC this setting applies to quotation yet.
