### ISSUE TITLE
while selecting “Against Journal Entry” link field showing error like “Server Error: Please check your server logs or contact tech support”

### ISSUE THREAD

**Issue by ShraddhaRanjane** [frappe/erpnext#2998]
Module- Stock ->Stock entry-> Purpose-Sales Return ->Make Credit Note

1. go to stock module
2. go to "Stock Entry" doc type
3. select Purpose -Sales Reurn
4.save and submit it
5. Make Credit Note
6. Go to table grid ->open that->select respective 'Account'- i.e Bank Account
7.go to "References"  section
8. now select/click inside "Against Journal Entry"  link field
9.Showing error "Server Error: Please check your server logs or contact tech support."
 (filters["account"], filters["party"], "%{0}%".format(txt), start, page_len))
 KeyError: u'party'

**Comment by nabinhait** [comment]
fixed.
