### ISSUE TITLE
Setup Wizard for Separated Domains

### ISSUE THREAD

**Issue by ruchamahabal** [frappe/erpnext#29982]
### Setup Wizard

The separated domains (Healthcare, Agriculture, Non-Profit) still show up in the setup wizard even if the app is not installed:

<img width="630" alt="Select your Domains" src="https://user-images.githubusercontent.com/24353136/155554869-410a6126-9eec-4e90-8cf6-d8f1f8f4f411.png">

Needs to be handled in app-specific setups

### Domain Settings

Same goes for Domain Settings

<img width="1296" alt="image" src="https://user-images.githubusercontent.com/24353136/155555109-3642f561-6d68-4bf9-a6df-5035f67fa822.png">

### Module

agriculture, non-profit, other

### Version

ERPNext Version 14 Beta / Develop

**Comment by ankush** [comment]
https://github.com/frappe/erpnext/pull/30820
