### ISSUE TITLE
ROLE PERMISSION for Page and Report do not have sufficient privileges to hide add column in derivative report

### ISSUE THREAD

**Issue by kidsyn** [frappe/erpnext#29999]
### Information about bug

Role Permission for Page and Report do not have sufficient privileges to hide add column in derivate report

Example in scenario where a staff should not view stock valuation, a derivate report is generated from stock balance report and valuation columns are removed and the original stock balance report is hidden from the user staff. However the staff is still able to view valuations by using add column. Permission manager has control either to stop querying a report/ printing or export and cannot have control on the report page drop down. This is a flaw in the permission manager as whole

![006f5144f56d02ee4d1159f1e80b3f1b80b34789](https://user-images.githubusercontent.com/65041616/155779754-28a8c063-203b-4d50-a283-273bbefe8879.png)

Reference : https://discuss.erpnext.com/t/report-permissions/83917/6

### Module

accounts, stock, buying, selling, manufacturing, HR, projects, support, CRM, assets, integrations, quality, regional, portal

### Version

ERPNext: v13.21.0 (version-13)

Frappe Framework: v13.21.0 (version-13)

### Installation method

manual install

**Comment by NEW-MTC-ERP1** [comment]
This issue has an important impact, needs to be solved
