### ISSUE TITLE
BOM item is appearing in the RM child table

### ISSUE THREAD

**Issue by sharmanakul** [frappe/erpnext#29990]
### Information about bug

When I start a BOM from the Item connections, then the same item is also populated in the raw material child table.

### Module

manufacturing

### Version

v14

**Comment by ankush** [comment]
This is because of Framework change: 

https://github.com/frappe/frappe/pull/15787 

Will have to somehow ignore it in case of BOM.

**Comment by ankush** [comment]
@shariquerik any way to trigger link fields that are auto-populated? If not let's remove auto-populating of fields because current behavior is worse than having to type it manually 😓

**Comment by ankush** [comment]
tracking at https://github.com/frappe/frappe/issues/16401
