### ISSUE TITLE
Adding Custom Web page to Home landing page does not show after user is login

### ISSUE THREAD

**Issue by mf0wzi** [frappe/erpnext#30005]
### Information about bug

Add a custom web page to web site's home page stops working after the user is logged in 

Before Login:

![home](https://user-images.githubusercontent.com/30725615/155871689-b317b76d-38ce-4964-b9d2-b81dc1ec1d99.jpg)

After Login:

![Screenshot 2022-02-27 at 09-48-43 404](https://user-images.githubusercontent.com/30725615/155871696-efc1d343-aedc-4b52-9e89-64c3ce8629e2.png)

### Module

portal, other

### Version

ERPNext: v13.21.0 (version-13)
Frappe Framework: v13.21.0 (version-13)

**Comment by tbe** [comment]
We have the same issue. This is very annoying for us and our customers.
