### ISSUE TITLE
WordPress Woocommerce sync

### ISSUE THREAD

**Issue by G-Driver** [frappe/erpnext#3001]
Is there any change to get ERPnext working with WordPress WooCommerce?

**Comment by partzsch** [comment]
would love to see that too

**Comment by abdeldayem** [comment]
what about Magento?

**Comment by dzulhelmi** [comment]
This feature is highly requested, but only available only for Spotify

**Comment by davidventernet** [comment]
I'd like to see this feature being implemented as well, perhaps as a WordPress Plugin.

**Comment by mhbu50** [comment]
+1

**Comment by techyidiots** [comment]
HI,

We have the woocommerce-erpnext plugin ready if you want to use it.

http://jamaliinfo.com/downloads/woocommerce-erpnext-connector/

	1.  it will sync products both ways
	2. orders from woocommerce to erpnext (If COD- it will create sales order and if paid, it will create sales invoice) 
	3. customers from woocommerce to erpnext only if the customer has placed an order in woocommerce site.

**Comment by techyidiots** [comment]
Hi All,

We have the plugin ready.

http://jamaliinfo.com/downloads/woocommerce-erpnext-connector/

it will sync products both ways
orders from woocommerce to erpnext (If COD- it will create sales order and if paid, it will create sales invoice)
customers from woocommerce to erpnext only if the customer has placed an order in woocommerce site.

We can work on your custom requirements as well.

**Comment by dzulhelmi** [comment]
Can you make the sync to be auto sync @techyidiots ?

**Comment by revant** [comment]
https://github.com/frappe/erpnext/issues/12873

**Comment by epe** [comment]
not sure where the best place is to ask questions about the integration. 
Is it possible to choose, which items and which pricelist will be shown in woocommerce?

**Comment by PawanMeh** [comment]
[Woo-commerce integration](https://erpnext.org/blog/erpnext-features/integrating-erpnext-with-woocommerce) is available in latest versions.
