### ISSUE TITLE
BOM in draft state should not be fetched in work order and production plan

### ISSUE THREAD

**Issue by sharmanakul** [frappe/erpnext#30011]
### Information about bug

I already had a BOM for an item, created another for the same item and left it in the draft state.

Now this BOM in the draft state is fetched in the production plan (PP), and there is no validation hence the PP gets submitted.

Similarly, in the work order, the drft BOM is fetched. However, there are valiations in place to stop the submission of the work order.

Expectation: the draft BOM should not be fetched and shold not be available for selection as well.

### Module

manufacturing

### Version

v13

**Comment by ankush** [comment]
Fixed it for now. Though I can imagine a use where BOM isn't final yet so for "production plan" draft one is used. In such cases, BOM can be replaced during work order too 🤔 or typed manually (we don't erase manually written value even in case of filters AFAIK)
