### ISSUE TITLE
The salary amount is not calculating correctly

### ISSUE THREAD

**Issue by iamejaaz** [frappe/erpnext#30031]
### Information about bug

https://user-images.githubusercontent.com/67804911/156124694-fb416a50-6bef-4046-8160-1858d613d0c5.mp4

- I am Calculating Salary slip based on Time sheet
![image](https://user-images.githubusercontent.com/67804911/156125082-1bc14535-2774-4991-ad37-0ba453744ba0.png)
- When I select Employee in the Employee Field, by default it is showing 15,000 in the Amount field which is wrong because I have worked only 13 hours. You can see in the video and in the image below.
![image](https://user-images.githubusercontent.com/67804911/156125269-3aa74461-78e0-4a25-9614-d7e77abf1333.png)
- After when I delete and add the same component it is showing the correct amount, based on my total working hours.
![image](https://user-images.githubusercontent.com/67804911/156126302-48251c70-4419-42ff-b9b3-2568a99f9481.png)
### Module

HR

### Version

erpnext 13.x.x-develop
frappe 14.x.x-develop

**Comment by ruchamahabal** [comment]
@ejaazkhan This is working fine for me:

![Kapture 2022-05-19 at 11 30 49](https://user-images.githubusercontent.com/24353136/169221027-bbb22118-7f42-4c54-9087-f4ddb52551ee.gif)

Maybe in the salary structure, you have added an Earning component same as the salary component for the timesheet? If that's the case, you don't need to add that component separately in the earnings table. The salary component set for the timesheet will be added to earnings on salary slip creation:

<img width="1319" alt="image" src="https://user-images.githubusercontent.com/24353136/169221387-20507139-5850-4d3b-b67f-af2d7f6709b4.png">

**Comment by iamejaaz** [comment]
> Maybe in the salary structure, you have added an Earning component same as the salary component for the timesheet? If that's the case, you don't need to add that component separately in the earnings table. 

Okay, Thanks...
