### ISSUE TITLE
Kanban view doesn't update on card transfer

### ISSUE THREAD

**Issue by Pazdo** [frappe/erpnext#30074]
### Information about bug

On dragging card from one collumn to another  there is need to reload view, otherwise card stays in same column

### Module

projects

### Version

erpnext 13.3.1
frappe 13.3.0

**Comment by ankush** [comment]
Which doctype you're referring to?

**Comment by Pazdo** [comment]
Mark it as fixed, the problem was naming in task, Having space in task name broke the refresh.
