### ISSUE TITLE
UAE Regional Setup Fails

### ISSUE THREAD

**Issue by knimer** [frappe/erpnext#30082]
### Information about bug

Immediately after finishing the Setup Wizard - which included selecting the UAE and all relevant parameters - the following error was in the Error Log List:

````
Traceback (most recent call last):
  File "apps/erpnext/erpnext/setup/setup_wizard/operations/taxes_setup.py", line 109, in update_regional_tax_settings
    frappe.get_attr(module_name)(country, company)
  File "apps/frappe/frappe/__init__.py", line 1204, in get_attr
    return getattr(get_module(modulename), methodname)
AttributeError: module 'erpnext.regional.united_arab_emirates.setup' has no attribute 'update_regional_tax_settings'
````

My findings until now:

- In the Taxes list there is NOTHING
- AED currency is available and enabled
- Not sure about the Chart of Accounts
- UAE VAT Settings List is empty
- UAE VAT 201 Report is available
- Tax Category List is Empty
- Item Tax Templates list is correct and shows UAE VAT
- Tax Rule List is empty

 

### Module

regional

### Version

ERPNext: v13.21.0 (version-13)
Frappe Framework: v13.21.0 (version-13)

### Installation method

manual install

**Comment by a2hb** [comment]
Same issue faced.

**Comment by knimer** [comment]
Just adding that another install with v13.22.1 had the same issue.

**Comment by husbas** [comment]
The issue persists.

**Comment by hatimohsin** [comment]
Still same.

**Comment by deepeshgarg007** [comment]
This has been moved to a separate repo from v15 and should not be an issue hence closing this issue
https://github.com/8848digital/KSA
