### ISSUE TITLE
Stock Ledger and Stock Balance are not showing after updataion of version ERPNext: v13.21.1

### ISSUE THREAD

**Issue by softbhushan** [frappe/erpnext#30112]
### Information about bug

Stock Ledger and Stock Balance are not showing after updataion of version v13.21.1

### Module

stock

### Version

Frappe Framework: v13.21.0 (version-13)
ERPNext: v13.21.1 (version-13)

### Installation method

easy-install

**Comment by ankush** [comment]
working just fine for me. Can you open browser console (F12) and share if any error are there?

**Comment by thida-bcn** [comment]
if there any backdate transactions
when you enter backdate transactions, system need to repost valuation and this process will run hourly, so you have to wait at least 1 hr to check that reports after editing stock with backdate transactions
