### ISSUE TITLE
[V5] Discount Amount - System Crash when enter Discount Amount

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#3011]
Steps:

1. New Sales Order
2. Entered Item details with rates, and taxes
3. Apply Discount on = Net Total
4. Entered Discount Amount

When enter discount amount, Save button freezes. Other fields are still editable. No error message.

![screen shot 2015-03-25 at 5 45 29 pm](https://cloud.githubusercontent.com/assets/910238/6824320/06a8470c-d317-11e4-9f41-123a737c01f9.png)

**Comment by rmehta** [comment]
cannot replicate. must be fixed.
