### ISSUE TITLE
POS Error: AttributeError: 'NoneType' object has no attribute 'options'

### ISSUE THREAD

**Issue by andrewhartono** [frappe/erpnext#30128]
### Information about bug

Open Point of Sale, every entry item will trigger this server error: 

AttributeError: 'NoneType' object has no attribute 'options'

it can only enter 1 item, after error can not input other item, can not checkout.
please resolve it soon, the point of sale can not even be used.

### Module

accounts, selling

### Version

Frappe Framework: v13.22.0 (HEAD)
ERPNext: v13.22.0 (HEAD)

### Installation method

FrappeCloud

**Comment by carstenblt** [comment]
#30129 Same issue.

**Comment by andrewhartono** [comment]
The error actually triggers on every form that need to choose items and item quantity such as:
purchase order, purchase receipt, purchase invoice, sales order, delivery note, sales invoice, etc.

**Comment by ankush** [comment]
@andrewhartono can you update to the latest release and confirm if this is resolved? https://github.com/frappe/erpnext/releases/tag/v13.22.1

**Comment by andrewhartono** [comment]
@ankush Thank you for your fast respond, but sadly i use public frappecloud site so i can only wait their update to get latest release and confirm the solution.

**Comment by ankush** [comment]
FrappeCloud autodeploys should trigger soon. 😅

**Comment by andrewhartono** [comment]
@ankush Thank you the update has been deployed and the error has been solved.
