### ISSUE TITLE
Account User Restrictions

### ISSUE THREAD

**Issue by Respectfulkid** [frappe/erpnext#3014]
Hi guys,

I'd like to be able to create certain restrictions on some account users. For example, a regular sales representative in my organization shouldn't have access to my bank account's balance. They should only have access to the A/R of the accounts they manage.

Is there any thoughts on implementing something like this?

All the best,

Roger

**Comment by neilLasrado** [comment]
@Respectfulkid hello this is very much possible to configure in ERPNext. Github serves as a platform for reporting Issues. Please post functional queries at https://discuss.frappe.io/

**Comment by Respectfulkid** [comment]
Hi @neilLasrado , thanks for your feedback. I've gone ahead and created the querie here:

https://discuss.frappe.io/t/user-account-restrictions-modification-requested/5209?u=respectfulkid
