### ISSUE TITLE
Mark Attendance from Employee List

### ISSUE THREAD

**Issue by asr17** [frappe/erpnext#3016]
please make this feature short, admin can enter Attendance for multiple employees in one go, using check box or something like that

**Comment by rmehta** [comment]
- [ ] Add menu item
- [ ] Write server side method to create attendance records

Reference: https://github.com/frappe/erpnext/blob/develop/erpnext/projects/doctype/task/task_list.js#L3

**Comment by vjFaLk** [comment]
[Fixed](https://github.com/frappe/erpnext/commit/07364f5ece4764fc58df16c43d9d208896cead79)
