### ISSUE TITLE
Feature Request: Salesperson Commission Plans

### ISSUE THREAD

**Issue by 403808** [frappe/erpnext#3018]
Deleted.

**Comment by rmehta** [comment]
@403808 thanks for the detailed explanation. A few suggestions.

1. This is a really long list. Can you break this up into sections?
1. For each section, use numbered lists for feature requests, so that they can be referred easily
1. Tag each feature request based on its importance on a scale of 1-5
1. If possible make mockups using a tool like - http://pencil.evolus.vn/ or https://balsamiq.com/

**Comment by hpema** [comment]
Hi,

I have built an entire commission system on a platform we use at the office and would like to contribute and see it ultimately appear in ERPNext, as I am getting to love this erp system.

My challenge right now is that I do not fully understand the code base, and im missing a crucial component in ERPNext called 'Lot costing'. If I can figure out how to get the 'costing' model correct, either myself or with your teams help (obviously im contributing it back to the team ;)), I can then start to look at porting my commission system into ERPNext.

To add here, its great to work out the rules as mentioned above as our rules are also similar. So making something generic would be possible. I just think more brains will be required to make sure its usable to other businesses. But saying that I think it will be hard to encompass all features of all businesses. Our system is also closely related to the HR module where we keep the cost to company of our sales team, and they only qualify if they make this cost to company value on summing all GP on invoices.

Im going to read again the explanation above and see if I can translate and correlate to what we have and add here.

Looking forward to when we go live with ERPNext ;).

**Comment by 403808** [comment]
@hpema, that's great.

You mention in your post that you're getting to love ERPNext.  It appears to be a great platform, but what you'll really start to love is the people behind it (I have nothing to do with them BTW... I'm just a customer who has "bothered" them with LOTS of questions - like "how can we get a commissions app?" :).  I have to say, right from the start I have been VERY impressed with the level of support I've received from these guys.  So, if your experiences equal mine, you'll be very happy developing on this platform (and they'll be very helpful).

Anyhow, I am not a developer (so I can't help there) but I do have a pretty good understanding of what I would like to see a ERPNext commission system do and would be very happy to share ideas, help with testing, etc.  Tell me what you need.

**Comment by rmehta** [comment]
@hpema @403808 thank you all for your kind words :)

We would love the help you get the contribution in place. We really believe in building a complete product for the community rather than a bunch of paid extensions.

A good way to design would be to propose wire frames and a design proposal. A pull request would also be the GitHub way to discuss.

**Comment by hpema** [comment]
Great, maybe we can start with unpacking what is required to have a great commission system and get some kind of requirements together as we go along? Not sure if this will be the right place, but here goes.

Im not clear as to what wireframe is but I will jot down what I think is required.

1)	Depending on what type of commission is going to be applied as stated by 403808 in terms of calculation, we will use the different parts of the invoice to get the numbers. We use GP and work out a % of GP as the commission. This means that the GP has to be accurate. This means that the cost has to be accurate. Now I know that ERPNext only has 2 cost valuation methods and I would like to propose another - which I mentioned way then in the beginning when I started looking at ERPNext. Our current ERP system has whats called 'LOT' cost method. Its not the best and I think I have a smarter way of looking at cost, but I need someone to look at it from different perspective.
a.	Cost is stored in pools of the cost of the item. When receipted, the item quantity is added to the pool of cost of the same item. If the cost is different another pool of that cost is created and the quantity increased of that pool
b.	When picking, the pools are presented and the user has an option to pick from which ever pools or costs are available, even from multiple pools to supply the quantities needed, eg. If 10 are required we can pick 2 from pool A, 3 from pool B and 5 from pool C.
c.	Warehousing can be challenging and stock-take might be too, but I think if just quantities are presented and checked it could make this method viable.
d.	On documents the total cost is easily calculated by summing, and an average for display purposes can be used on the form, but the exact costs will be used in the Journal.

2)	We also then have an allocation of Customer to Sales Person for a given period. So the invoice will be checked against this data for the invoice date. There should be a configuration for which date to use – Invoice date or Order date.
a.	Some customer have a split between sales persons. The total GP on the invoice will then be proportioned by the percentage of each sales person and this calculation is what reflects against the target of the sales person. We give the sales persons targets for the year. But again this should be configurable for quarter, weekly, yearly, etc. We use yearly.
b.	We also give different commission % for different product categories. Now we have multiple categories for our products, but 3 categories for commission calculations – commodity, enterprise and networking. This can be changed or adjusted by discussion.
i.	Each of these categories has a target and might not be the same for each sales person.
c.	Some splits are only for 1 category, eg. Sales person 1 only does commodity for the customer and another does enterprise. In some cases there is a joined effort, and the percentage is split for the various categories.

3)	Once the calculation is done and we have the percentage of GP to pay and who to pay when store this data, not paying out yet until the invoice is paid by customer. If the customer pays on time all is well, but if the customer does not pay within the terms set we then start to penalise the sales person. For every 30 days past the due date we remove % of commission. This also can be some kind of configuration.

4)	We do the commission Run at the beginning of each month. We telly up the last month, and if the GP on invoices for the sales person is higher than (the cost to company/12*1.1) then the sales person is due that commission for that month. We also hold back 3% of the commission for risk and pay out 2% when the sales person makes 80% (or whatever the sales manager determines as a criteria with the sales person) on all item categories and a further 1% based on activities of the sales person and their engagement with customers.
5)	A report is generated for commission that is due which means all invoices that have been paid minus penalties from past months what criteria to pay has been achieved.

Wow, lengthy, sorry for that, but its just to get the discussion started, like 403808 has done ;)

So I would suggest starting with the cost valuation – if possible. If we need to start a new thread for this, that might be a good idea. Using this costing method we can also apply FIFO and moving averages where needed, but have the actual cost as the base.
Just as an example why we cannot use moving average.

1)	We purchase the same product from our vendor for different customers with different costs. Depending on the customer size the vendor give preferential pricing and we are forced to use this batch of products for that customer and are audited at times to make sure that we are doing so. So itemA can have a different cost even though we bought them at the same time from the vendor. And the customers can have different sales persons. If we use average cost then we will be penalising one sales person and rewarding another by the difference of price. In some cases the GP would show negative. Obviously the one gaining is not going to complain, but the one loosing? There might be roundabouts where the roles are reversed, but I think it’s harder to manage this type of effects through HR then it is to just get the cost right.
a.	In the past we use to export all the data required for commission into a separate system (which we still do but no longer worry that much on cost), and adjust the costs based on purchase invoices of that item for that project for that customer, then do the commission run.
b.	We currently still have a separate commission system as our current ERP system has not been configured with all the rules for commission.
Hope im making sense.
Please share your thoughts.

Regards

**Comment by 403808** [comment]
HI, I just wanted to follow up to see what we need to do to take this to the next step.  Thanks

**Comment by rmehta** [comment]
@403808 @hpema 

Can you list what would be the absolute minimum requirements, in brief, point-by-point manner?

Our goal would be to first build a generic structure that would fulfill 80% of use cases. Maybe the finer rules can be built via customizations.

**Comment by hpema** [comment]
Hi Rushabh,

I think if you agree I would like to suggest we work on figuring out how to get the exact cost of the items that are requiring commission to be paid. I think working on an “exact cost” valuation method will be a better long term option as there might be other places where the cost valuation will come into play.

So what do I mean by exact cost?

1)	All items are stored with and grouped together by the code and cost
2)	I will be able to pick from a list of costs for the same item
3)	The cost of items for journals will be the some of the qty x cost of each item
4)	Stock value will be the cost x qty of each item.

This method for me makes far more sense than the average option…but im not sure how this will affect warehousing and manufacturing. All I can say is that it makes it easier to calculate commissions cause I will know the cost of the item at any given time, even after transactions of the same items are moving through the stock system – the average won’t be affected as there is not average.

I think it’s almost like batching but with cost value instead. All this can happen without the user knowing and won’t affect the current batch system. I don’t know how much is involved in adding this type of valuation method – but I think it will be advantageous to look into it.

Once we have the cost then the other rules will apply. Will send that in another email in a structured form.

Regards
Hemant

**Comment by rmehta** [comment]
@hpema I am not sure we want to take this up right now. Its best for you to customize it.

**Comment by cgpurbaugh** [comment]
Can this be closed?

**Comment by 403808** [comment]
yes
