### ISSUE TITLE
Enable Custom Fields in Naming Series

### ISSUE THREAD

**Issue by raveslave** [frappe/erpnext#3019]
Extend the "Autoname rules" to allow retrieve and insert a value from a document / custom field.
##### Background:

Some companies prefers to make use of "short-codes" for suppliers, i.e. WN for company "Web Notes" that later can be used in naming series for quick identication.
##### Example:
- A custom field "Vendor ID" is created under Document: Supplier.
- Then under Naming Series, we should allow something like
  - PO-.YY.MM.-.{vendor_id}.-.#####
  - Resulting in "PO-1503-WN-00001"

**Comment by superlack** [comment]
I am hoping this becomes something out of the developer mode spectrum.
