### ISSUE TITLE
"Ignore pricing rules" is set in sales invoices created from sales orders

### ISSUE THREAD

**Issue by carstenblt** [frappe/erpnext#30196]
### Information about bug

When creating a sales invoice from a purchase order the "ignore pricing rules" option is activated automatically, even if it is not set in the purchase order. So the draft is created with the correct prices, however submitting the invoice recalculates with the wrong prices.

Creating a sales invoice directly (without creating a purchase order first) doesn't have the option set.

Happened when upgrading from v13.20.1 to v13.22.1.

### Module

selling

### Version

Frappe v13.22.0
ERPNext v13.22.1

**Comment by carstenblt** [comment]
Actually what I think happens is, that prices are recalculated when submitting the invoice, even if they have been adjusted manually.

**Comment by ankush** [comment]
@carstenblt is this still happening on v13.23? IIRC fix was made for this issue: https://github.com/frappe/erpnext/pull/30269
