### ISSUE TITLE
Collapsible Section Break with empty label are not collapsible

### ISSUE THREAD

**Issue by jireh-sg-leo** [frappe/erpnext#30197]
### Information about bug

Version: 13

Steps to reproduce:

1. In a doctype, add a "Section Break" and check "Collapsible", leave the "Label" field empty.
2. From javascript console, execute the following statement (replace `section_break_xxx` with the correct field name):
```
cur_frm.fields_dict['section_break_xxx'].collapse(1)
```
3. It will not collapse. Visually, there's no section heading and collapse icon.
4. Changing "Label" to a single space " ", it will display the collapse icon, and the section is collapsible.
5. Repeat the same javascript, and it works.

Expected behaviour:

1. Section should be collapsible without a label. This allows us to programmatically show/hide sections without having to show a label and the collapse icon, for a more compact presentation.

### Module

other

### Version

Frappe: 13.14.1
Erpnext: 13.12.1

### Installation method

easy-install

**Comment by ankush** [comment]
Wouldn't it look bad if labels aren't there? What do we even show as section title? 😅 

<img width="822" alt="Screenshot 2022-03-15 at 12 09 00 PM" src="https://user-images.githubusercontent.com/9079960/158321123-da5f3ac0-be76-4712-a53c-104e4a738d93.png">

This looks very weird. You can just erase label using JS if you want to instead.
