### ISSUE TITLE
Issues with TODO in v5

### ISSUE THREAD

**Issue by pagliaso** [frappe/erpnext#3021]
Hi,

I have just created a new thing TO DO in v5, and I have noticed the following issues:

1.- The code does not follows the previous naming series TD######, and is instead some letters and numbers (see attached picture)

2.- The breadcrumbs does not work very well. It is okay when I create the TO DO, but if I come back later, there is any more a correct route from ERPNExt to TODO.

3.- It seems that there is no TODO Transaction in setup naming series.
![todo_1](https://cloud.githubusercontent.com/assets/2955272/6891531/424b1dae-d6bc-11e4-95b7-67903328e4e2.jpg)

Thanks and regards,

**Comment by anandpdoshi** [comment]
This is a design change

1. ToDo’s don’t need to have a series. Hence 3. There is no series called To Do now.

2. Bread Crumbs are usually meant for going back. So if you are inside To Do Form you wil be able to see To Do to go back to To Do List. But to go forward, you can use New or click on a To Do In the list.

Thanks,
Anand.

**Comment by pagliaso** [comment]
Hi, 

Thank you Anand!

I was being stupid and blind with breadcrumbs, I don't know if because of the fact that I do not have the icons on the dashboard yet, and I have to use the search bar for everything and I am a bit disorientated without them. But with your simple explanation of how the breadcrumbs are supposed to work, I understand now they are working very well indeed.

Thank you and kind regards,

**Comment by anandpdoshi** [comment]
Are you using vm and upgraded it to v5?

I think there’s a bug in vm that’s causing the blank desktop and we are looking into it.

-Anand.

**Comment by pagliaso** [comment]
Hi Anand,

Is vm virtual machine? 

No, I had ERPNExt installed on a VPS in production mode, and updated to v5.

Many thanks and kind regards,
