### ISSUE TITLE
Explore CI check for a;ll supported Python versions.

### ISSUE THREAD

**Issue by Abhirup-99** [frappe/erpnext#30221]
**Is your feature request related to a problem? Please describe.**
ERPNext fails with Python 3.10. The change could have been caught with CI.

**Describe the solution you'd like**
Add Github actions to check compilation for Python 3.10.

**Describe alternatives you've considered**

**Additional context**

**Comment by ankush** [comment]
Our CI used to take 40+ minutes and after parallel tests it takes ~20 minutes. It's not feasible to run test on multiple versions. 

3.10 support is known issue and will get fixed soon: https://github.com/frappe/erpnext/issues/29236
