### ISSUE TITLE
Capability for providing job estimates with incoming and final inspections is not standard

### ISSUE THREAD

**Issue by arpanzen** [frappe/erpnext#3024]
We are a service jobshop and most of the time we receive material through 'Returnable Party Gate Pass' for which we have to provide an estimate. The Format of Estimate is such that half of it is an inspection report for the incoming material and the other half is a quotation. After the customer approves this estimate we receive his work order and we process the material and send an outgoing inspection report. The report contains both incoming and outgoing inspection values.
The later part is similar to standard selling cycle only that the item stock transfer is from the same warehouse in which the item was earlier received.

We hope you provide this functionality in your standard software to help small job shops like us.
Thanks

**Comment by rmehta** [comment]
Can you provide a mockup of what your form looks like using a tool like http://pencil.evolus.vn/ or https://balsamiq.com/

**Comment by arpanzen** [comment]
Sorry for not replying for long. I have worked a way round this issue as per your suggestions. What we are now doing is that we prepare a stock entry and take the material for service. Then we prepare an inspection report in quality inspection in Stock modeule and finally we prepare a quote which is linked with stock entry in quotation and quality inspection in quaotation items. This way we could accumulate all data for an estimate. Only problem being faced is that we have to make data entries in all forms which could lead to operator error or data not being same. We were not able to copy data from one form to other using custom script.

**Comment by rmehta** [comment]
@arpanzen can you post your query on the forum https://discuss.frappe.io
