### ISSUE TITLE
Unable to view individual reports.

### ISSUE THREAD

**Issue by nirmal1520** [frappe/erpnext#30247]
### Information about bug

We have created a few users and unable to view the individual report. In fact, we are unable view their daily, weekly, or monthly reports, 

Also, we would like to know how much hours has been spend by the users on particular projects.

### Module

CRM

### Version

Installed Apps
Email Delivery Service: v0.0.1 (main)

ERPNext: v13.22.1 (HEAD)

Frappe Framework: v13.22.1 (HEAD)

Project Payroll: v0.0.1 (HEAD)

Wiki: v0.0.1 (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
No error, but unable to see these options. 

We have created a few users and unable to view the individual report. In fact, we are unable view their daily, weekly, or monthly reports, 

Also, we would like to know how much hours has been spend by the users on particular projects.
```

**Comment by ankush** [comment]
> We have created a few users and unable to view the individual report. In fact, we are unable view their daily, weekly, or monthly reports,

what do you mean by "view user's report"?
