### ISSUE TITLE
Auto reminder functionality through tasks

### ISSUE THREAD

**Issue by arpanzen** [frappe/erpnext#3026]
We were looking for an auto reminder functionality in an ERP such that the person next in line is generated an auto reminder notifying that the previous person has completed his task and he can do his bit to complete the workflow. This functionality can help the user stay updated so that he can login and check his tasks and can easily plan his priorities. Also we can provide an Execute task button on the task itself so that he is taken directly to the record with auto filled values and only some values can be filled and record submitted. 

We have been using this functionality in our small custom program and it was very helpful with new operators who dont know the workflow in detail.

**Comment by deepeshgarg007** [comment]
@arpanzen You can configure this using notification based on task status, as soon as a task status is marked as completed a notification can be triggered to notify relevant people.
