### ISSUE TITLE
error occurs when save purchase order

### ISSUE THREAD

**Issue by omnison** [frappe/erpnext#3027]
Ordered qty can not less than item's minimum order qty (defined in item master).

But i set item min quantity in master as 100, and quantity in Po is 9000.

How to fix it.

**Comment by anandpdoshi** [comment]
Check if you are comparing using the same UOM.

Say you defined 100 quantity in Kgs, but in Purchase Order you are using
Gms, and you state 9000 Gms, then it is less than 100 Kgs!

-Anand.

**Comment by omnison** [comment]
same UOM:MT

**Comment by nabinhait** [comment]
@omnison Are you still getting this error?
