### ISSUE TITLE
[V5] Awesome Bar - Help on Search label is not updated

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#3028]
In the Awesome Bar, "Help on Search" is not updating. It shows "Undefined".

![screen shot 2015-03-31 at 12 38 22 pm](https://cloud.githubusercontent.com/assets/910238/6913926/4643f966-d7a3-11e4-9a49-1631aa0a31a0.png)

**Comment by rmehta** [comment]
fixed

**Comment by umairsy** [comment]
Also when showing history:

![screen shot 2015-03-31 at 2 22 59 pm](https://cloud.githubusercontent.com/assets/910238/6915463/dbde6746-d7b1-11e4-9a9a-7a4f9b2c574b.png)

**Comment by anandpdoshi** [comment]
Fixed.
