### ISSUE TITLE
Link field Debit To filling without having set a standard

### ISSUE THREAD

**Issue by wojosc** [frappe/erpnext#30299]
### Information about bug

The target is to unset a standard for the Debit To field in Sales Invoice so that if no Account is set in the master data it will stay empty in Sales Invoice and hint as it is mandetory.

Although all standards are removed (the ones I know of) a Account is still set. This can lead to wrong entries by mistake, as I am not hinted, that an Account is missing.
(in the Purchse process vis-versa it works as expected, if no standards are set, it will stay empty)
![debit_account_setting_in_sales_invoice](https://user-images.githubusercontent.com/22279621/158905026-bdb9c76d-3654-4ca9-aca1-44f00e1e5143.gif)

### Module

accounts

### Version

ERPNext: v13.22.1 (HEAD)

Frappe Framework: v13.22.1 (HEAD)

### Installation method

FrappeCloud

**Comment by deepeshgarg007** [comment]
@wojosc If the customer already has transactions with a specific account then it might be fetched from the GL entries too, after removing the defaults please check with a new customer and reopen

**Comment by wojosc** [comment]
> @wojosc If the customer already has transactions with a specific account then it might be fetched from the GL entries too, after removing the defaults please check with a new customer and reopen

Thank you @deepeshgarg007 I have just tested this. Indeed it is not set when there has been no transaction and is auto-set once a transaction has been made. before I have removed the standards from Company Master.

This Issue can stay closed.

Thank you for your help!

**Comment by wojosc** [comment]
I have just done a further test on this. Once we have created a transaction on customer/supplier all the following transaction on the same will link the account that was chosen on the first transaction.

Meaning if I link Account A in transaction 1 and link Account B in transaction 2 it will once again link Account A when creating transaction 3.

https://doku.phamos.eu/link/1071#bkmrk-konteneinstellungen
