### ISSUE TITLE
[V5] Website - Item Listing - Issue in URL

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#3031]
Steps:

1. I am on the Website home page. Have "Tops" an Item Group listed on the  Top Bar of website.
1. Click on Tops. (domain/tops)
1. Click on Item. (domain/tops/item-code)
1. Again click on Tops on the Top Bar. (domain/tops/tops)

When again tries getting back on Tops listing, it says page missing. URL for the page is updated as domain/tops/tops.

![url](https://cloud.githubusercontent.com/assets/910238/6917148/a8185684-d7bf-11e4-9277-cbfe665e1f2d.gif)

**Comment by rmehta** [comment]
In your website settings in top bar items, add

`/tops` instead of `tops`
