### ISSUE TITLE
Do not remove item from list while iterating the list

### ISSUE THREAD

**Issue by nextchamp-saqib** [frappe/erpnext#30325]
Originally raised with #29008 by @vr-greycube

### Bug
Cannot remove item from list while iterating the list.

```
def filter_service_items(items):
	for item in items:
```
should be
```
def filter_service_items(items):
	for item in list(items):
```

The same bug is also in these places:

- https://github.com/frappe/erpnext/blob/498d933e9ce7c18d6c595d2e0f575645dc020d81/erpnext/stock/report/stock_ledger/stock_ledger.py#L239
- https://github.com/frappe/erpnext/blob/498d933e9ce7c18d6c595d2e0f575645dc020d81/erpnext/education/doctype/program_enrollment_tool/program_enrollment_tool.py#L47
- https://github.com/frappe/erpnext/blob/498d933e9ce7c18d6c595d2e0f575645dc020d81/erpnext/erpnext_integrations/taxjar_integration.py#L216
- https://github.com/frappe/erpnext/blob/498d933e9ce7c18d6c595d2e0f575645dc020d81/erpnext/payroll/doctype/payroll_entry/payroll_entry.py#L481

### Module

other

### Version

v13

### Installation method

manual install

**Comment by ankush** [comment]
This is so trivial, let's close this ASAP 🙈 

and lets also expand the existing semgrep rule for this:

https://github.com/frappe/semgrep-rules/blob/develop/rules/frappe_correctness.yml#L142
