### ISSUE TITLE
System auto-suggest a batch with 0 quantity

### ISSUE THREAD

**Issue by guilmori** [frappe/erpnext#30339]
### Information about bug

Why truncate decimals when validating batch qty ?

I need 0.4 kg, and the system select a batch with 0 qty.

https://github.com/frappe/erpnext/blob/01fd3adedf289aa18947310f06a1b6b38ba7ecd6/erpnext/stock/doctype/batch/batch.py#L262

### Module

stock

### Version

v13.16.0

### Installation method

manual install

**Comment by ankush** [comment]
makes sense. This should be `flt` and not `cint`. Can you send a PR?
