### ISSUE TITLE
Item price resets on document date change

### ISSUE THREAD

**Issue by YamanQD** [frappe/erpnext#30341]
### Information about bug

After creating a sales invoice and adding an item to the items table, the item's (pricelist price) appears in the "Rate" column by default
But if you change the "Rate" price manually, and then change the "Date" of the document, the price resets to the default "pricelist price".

What's expected is that the modified "Rate" of the item stays the same even after the date of the document is changed.

### Module

selling

### Version

ERPNext: v13.20.1 (version-13)

Frappe Framework: v13.20.1 (version-13)

**Comment by YamanQD** [comment]
This bug persists even after updating to version:
```
ERPNext: v13.23.3 (version-13)
Frappe Framework: v13.23.0 (version-13)
```
I'm hoping it can be fixed in the next update because it's creating problems.
Thank you very much for your hard work

**Comment by lxnow** [comment]
Can validate this behavior still exists in v13.28.0
