### ISSUE TITLE
Issue in stock reorder . it creates only purchase request even though we set manufacture .Please Help

### ISSUE THREAD

**Issue by kamal-star** [frappe/erpnext#30354]
### Information about bug

[Issue in stock reorder . it creates only purchase request even though we set manufacture .Please Help](https://discuss.erpnext.com/t/issue-in-stock-reorder-it-creates-only-purchase-request-even-though-we-set-manufacture-please-help/87527)

### Module

stock

### Version

all

### Installation method

easy-install

**Comment by nabinhait** [comment]
Can't replicate
