### ISSUE TITLE
Consolidated Financial Report : Income GL account doesn't roll-up

### ISSUE THREAD

**Issue by lxnow** [frappe/erpnext#30369]
### Information about bug

GL income/sales account is a child of another parent GL income/sales account. When generating a P&L report, we expect these child account(s) to roll-up totals into parent account. This works fine on the normal Profitability report. However, for the *Consolidated* Financial Statement, Profit and Loss, the child account is ignored and does not show.

To test: 
- create child income account
- roll it under parent main income account
- make transactions
- run report

### Module

accounts

### Version

13.23.0 erpnext
13.23.0 frappe

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
n/a
```

**Comment by deepeshgarg007** [comment]
@lxnow Can you please check this and let me know if this still persists? Please also let us know the site name as well so that we can further investigate the issue
