### ISSUE TITLE
On Stock Entry form when i select purpose as “Sales Return” then respective sales invoice number not get displayed/serach 

### ISSUE THREAD

**Issue by ShraddhaRanjane** [frappe/erpnext#3038]
Steps:- 
I have created sales order, sales invoice, delivery note and Make payment entry.
and when i go to stock entry and select purpose as "Sales Return" then respective
'sales invoice number' not get displayed

**Comment by umairsy** [comment]
Shraddha,

Only Sales Invoices having "Update Stock" field checked are shown in the
Sales Return entry.

On Wed, Apr 1, 2015 at 6:47 PM, ShraddhaRanjane <notifications@github.com>
wrote:

> Steps:-
> I have created sales order, sales invoice, delivery note and Make payment
> entry.
> and when i go to stock entry and select purpose as "Sales Return" then
> respective
> 'sales invoice number' not get displayed
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/frappe/erpnext/issues/3038>.
>



-- 
Thanks and Regards,
Umair Sayyed
www.erpnext.com

**Comment by ShraddhaRanjane** [comment]
Ok...
Thanku
