### ISSUE TITLE
bug: shopping cart svg icon still black on dark navbar

### ISSUE THREAD

**Issue by nameduser0** [frappe/erpnext#30390]
### Information about bug

Other css rules are invoked for the navbar text color when the navbar class `bg-dark` is used.
These rules do not apply to the cart icon which remains dark against a dark background:

![Screen Shot 2022-03-23 at 20 24 35](https://user-images.githubusercontent.com/64409021/159789313-6bc3bed3-d825-4007-ae5e-7c6a001add27.png)

```
.navbar.bg-dark .nav-link {
    white-space: nowrap;
    color: #F9FAFA;
}
```

```
<a class="nav-link" href="/cart">
<svg class="icon icon-lg">
<use href="#icon-assets"></use>
</svg>
<span class="badge badge-primary shopping-badge" id="cart-count">1</span>
</a>
```

Setting `--icon-stroke` messes with all other icons, so the svg somehow needs to be transitioned like the image/list icons on the product list page, but based on the bg-dark theme option.

### Module

ecommerce

### Version

13.19.0

**Comment by Nihantra-Patel** [comment]
Hi @nameduser0,

We no longer provide support for version 13 or older. Also, if you change the navbar, you need to add CSS based on your theme or design. ERPNext might not handle every situation, so you'll need to customize everything yourself or set up everything in your custom app.

Kindly upgrade to version 14 or 15, if you want (We no longer provide support for version 13 or older.)


Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!
