### ISSUE TITLE
Item Rate changes after saving

### ISSUE THREAD

**Issue by kanedai** [frappe/erpnext#30392]
### Information about bug

When I make a quote, modify the rate, save it, and the Rate will change to another value (this problem in the early V13 in 2021)
<img width="320" alt="image" src="https://user-images.githubusercontent.com/4647923/159829582-c7233b35-344a-4a5e-a273-200e69b6f986.png">
<img width="309" alt="image" src="https://user-images.githubusercontent.com/4647923/159829631-1534ddad-762d-48b6-a261-3c5b6cac0d28.png">

### Module

accounts

### Version

Frappe - 13.23.0
Erpnext - 13.23.1 (latest version)

**Comment by backendoadmin** [comment]
Duplicated:
https://github.com/frappe/erpnext/issues/30375

**Comment by aakvatech** [comment]
![image](https://user-images.githubusercontent.com/35020381/159976815-78b26d3a-d4d4-4895-b472-fa81c4fdb76f.png)

discount_percentage is calculated by (discount_amount / price_list_rate) and applying the precision (usually 2 or 3 decimals) = rounded discount_percentage
Then item rate is calculated by calculating an incorrect discount_amount from the (price_list_rate * rounded discount_percentage) and then deducting the incorrect discount_amount from price_list_rate

**Comment by backendoadmin** [comment]
I think its fixed with https://github.com/frappe/erpnext/pull/30406
