### ISSUE TITLE
Item needs link to related Website Item

### ISSUE THREAD

**Issue by nameduser0** [frappe/erpnext#30391]
**Is your feature request related to a problem? Please describe.**
No way to jump to an Item Website Item.

**Describe the solution you'd like**
The Item has various menus at the top including `View`. This should have an option to jump to the related `Website Item` **if it exists**.

**Additional context**
The Website Item info used to be on the same Item page, so users will be used to this easy access

**Comment by ankush** [comment]
https://github.com/frappe/erpnext/pull/30578
