### ISSUE TITLE
'Add to Cart' button dislocated for '/all-products' page list view for mobile view.

### ISSUE THREAD

**Issue by fossdot** [frappe/erpnext#30411]
### Information about bug

I was configuring E-commerce for a site - https://koraj-bhasha.frappe.cloud/all-products. I found an issue with UI on /all-products page list view for mobile view.
Add to cart button has been replaced for mobile view.

I can see the issue with ERPNext's e-commerce demo account at as well.
![photo_2022-03-25_12-31-20](https://user-images.githubusercontent.com/25725389/160070730-755a7411-2356-4f8f-a27e-64fba7d83dca.jpg)
![photo_2022-03-25_12-31-25](https://user-images.githubusercontent.com/25725389/160070724-27e369f7-2ce4-4aec-a80a-5e4da56b822f.jpg)

### Module

ecommerce

### Version

ERPNext: v13.23.0 (HEAD)
Frappe Framework: v13.23.0 (HEAD)

### Installation method

FrappeCloud

**Comment by mmoorree** [comment]
I am experiencing the same issue on mobile view in /all-products and /category-list

![add-to-cart-erpnext-error](https://github.com/frappe/erpnext/assets/19202288/0a71b3de-7535-4079-8445-a479b2392b78)

Frappe Hosted.
ERPNext: v14.41.1 (HEAD)
Frappe Framework: v14.51.0 (HEAD)

**Comment by mmoorree** [comment]
Same issue on product (item) page too.

![Screenshot_20231011-191000](https://github.com/frappe/erpnext/assets/19202288/503ec434-8988-4e86-bb32-16c949f9f26f)

**Comment by Nihantra-Patel** [comment]
Kindly upgrade to version 15, then refresh and check again because lots of bugs fixed in the new version.

If have an issue then raise the issue in the webshop.

![image](https://github.com/user-attachments/assets/f3341637-9148-4172-b3bc-59e7f7c6dfc2)
