### ISSUE TITLE
Not allowed to change Total Leaves Allocated after submission

### ISSUE THREAD

**Issue by gohyc** [frappe/erpnext#3042]
Sometimes we need to change the leave allocation after it has been submitted.  At the moment, we can not update the allocation directly in the document.  And we are also not allowed to cancel and amend the allocation if there are already approved leave.  We can not ask the users to cancel all the approved leave and redo the leave allocation again.

**Comment by rmehta** [comment]
Yeah removing the validation. Now you can cancel and amend leave allocations

**Comment by mojuneja** [comment]
Getting the validation error while cancelling leave allocation "Leave allocation HR-LAL-XXXX-XXXXX is linked with leave application HR-LAP-XXXX-XXXX1, HR-LAP-XXXX-XXXX2, HR-LAP-XXXX-XXXX3, HR-LAP-XXXX-XXXX4, HR-LAP-XXXX-XXXX5, HR-LAP-XXXX-XXXX6".
