### ISSUE TITLE
[V5] Issues in rich text editor

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#3044]
Couple of issues encountered in the rich text editor.

![rich-text-issues2](https://cloud.githubusercontent.com/assets/910238/6962915/efa269a2-d956-11e4-8e05-887803485ae0.gif)

1. When try applying heading on already typed text, it applies it on another text.
2. Option to Bold text not working.
3. Insert Link option not working.
4. Center Align option not working.
5. Indenting options not working.

**Comment by adityaduggal** [comment]
The error which is coming while adding a links is as below:

Uncaught TypeError: Cannot read property 'toString' of undefinededitor.min.js:155 (anonymous function)jquery.min.js:3 n.event.dispatchreport.min.js:189 $event.dispatchjquery.min.js:3 r.handle

**Comment by rmehta** [comment]
fixed
