### ISSUE TITLE
[V5] - Custom Form - Error message when navigate from List View

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#3045]
Steps:

1. On Item list.
1. Menu >> Customize
1. Customize Form page is loaded. Error message says: "Field Doctype Not Found". Item details are fetched correctly in the Customise Form.

![customize-form-error3](https://cloud.githubusercontent.com/assets/910238/6963135/052cb4ba-d959-11e4-80d8-4f05d47bec3f.gif)

**Comment by rmehta** [comment]
fixed
