### ISSUE TITLE
Tasks inside group task in tree view doubling up

### ISSUE THREAD

**Issue by wojosc** [frappe/erpnext#30467]
### Information about bug

If you filter for a task group in the tree view of task and open a group the tasks will show double. All the tasks that are shown in the the group are the same as in the orignal tree view. This goes on for ever. Loop?
![task_doubling_in_tree_view](https://user-images.githubusercontent.com/22279621/160556513-831c9ba7-a045-40b5-9f86-675acd2d79b6.gif)

### Module

projects

### Version

ERPNext: v13.23.3 (HEAD)

Frappe Framework: v13.23.0 (HEAD)

### Installation method

FrappeCloud

**Comment by nabinhait** [comment]
Fixed in latest version
