### ISSUE TITLE
Add Accounting Dimension  to Profitability Analysis

### ISSUE THREAD

**Issue by thida-bcn** [frappe/erpnext#30482]
At Profitability Analysis Report, we would like to get Based on 'Accounting Dimension'
Example,
If I had added Business Unit as Accounting Dimension, we would like to choose 'Business Unit' as Based on
Thanks
![image](https://user-images.githubusercontent.com/62122640/160653408-4956fa39-673a-4ec9-b66b-54584f28378f.png)

**Comment by thida-bcn** [comment]
I supposed Accounting Dimension should be able to choose at Profitability Analysis

**Comment by deepeshgarg007** [comment]
Fixed Via: https://github.com/frappe/erpnext/pull/36107
