### ISSUE TITLE
How to apply credits from vendors

### ISSUE THREAD

**Issue by stephaniecarnes** [frappe/erpnext#30480]
### Information about bug

I need a little guidance with a Supplier that we paid an invoice with a
check in 2021. Then later we returned everything. The company gave us a
credit on the account and is using the credit to pay down 3 different
Purchase Invoices. How do we apply the credit to the invoices? I have
searched the internet and the help documents but I cannot find the
answer to this? Please advise.

### Module

buying

### Version

ERPNext 13

**Comment by dj12djdjs** [comment]
You can use Payment Reconciliation for matching payments to invoices. https://docs.erpnext.com/docs/v13/user/manual/en/accounts/payment-reconciliation

It's better to use https://discuss.erpnext.com/ for help questions.
