### ISSUE TITLE
Request to edit the abbreviation of the company as per our wish. Currently when we create a new company, only at that time we can change the abbreviation of the company,after we save the company name ,its not able to change the abbreviation.

### ISSUE THREAD

**Issue by ArunaDevraj** [frappe/erpnext#30490]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ankush** [comment]
this was intentionally removed: https://github.com/frappe/erpnext/pull/27766 


in v14 there's a new feature to show title field value instead of the name, which makes renames like these unnecessary. 

Also this acronym is not used in any business logic whatsoever.

**Comment by bosue** [comment]
@ArunaDevraj: Resolved in https://github.com/frappe/erpnext/pull/36412.
