### ISSUE TITLE
Dependent Tasks in Task DocType do not renew their status

### ISSUE THREAD

**Issue by majubewi** [frappe/erpnext#30498]
### Although a task has been marked as complete ...

Although a task in picture number 1 has been marked as complete in the status field. The task above does not support that status change in the dependent status table in picture number 2.

Picture number 1
![grafik](https://user-images.githubusercontent.com/11473213/160839237-be14b16d-9b42-4c43-8728-6fa0bb8e9bf5.png)

Picture number 2
![grafik](https://user-images.githubusercontent.com/11473213/160838922-58d6ab05-158f-4abf-88bb-7ba65d351b7f.png)

### Module

projects

### Version

frappe.cloud

### Relevant log output / Stack trace / Full Error Message.

```shell
no log output
```

**Comment by oliver19820323** [comment]
have you got the solution for this , i face the same issue . Thank you

**Comment by oliver19820323** [comment]
> ### Information about bug
> ### Although a task has been marked as complete ...
> Although a task in picture number 1 has been marked as complete in the status field. The task above does not support that status change in the dependent status table in picture number 2.
> 
> Picture number 1 ![grafik](https://user-images.githubusercontent.com/11473213/160839237-be14b16d-9b42-4c43-8728-6fa0bb8e9bf5.png)
> 
> Picture number 2 ![grafik](https://user-images.githubusercontent.com/11473213/160838922-58d6ab05-158f-4abf-88bb-7ba65d351b7f.png)
> 
> ### Module
> projects
> 
> ### Version
> frappe.cloud
> 
> ### Installation method
> _No response_
> 
> ### Relevant log output / Stack trace / Full Error Message.
> ```shell
> no log output
> ```

have you got the solution for this , i face the same issue . Thank you

**Comment by Nihantra-Patel** [comment]
As such, the Depend Task table does not have a field called Status. Not even in version 14 and version 15. Hence it appears that you have customized it yourself.

https://github.com/frappe/erpnext/blob/version-14/erpnext/projects/doctype/task_depends_on/task_depends_on.json
