### ISSUE TITLE
Autocomplete option in Tags

### ISSUE THREAD

**Issue by vikramnarayan** [frappe/erpnext#3049]
Hello Vikram,

Thanks for the detailed explanation.

For now, master is not maintained for the Tag. Request you to post a Github Issue for this.

https://github.com/frappe/erpnext/issues

-- 
Thanks and Regards,
Umair Sayyed
www.erpnext.com

On 2nd April 2015, 3:08am, vikram.narayan@agrilife.in wrote:

HI,

We are using the tag feature for more efficient tracking of our orders. However we find that due to spelling mistakes, difference in space wording etc, and so many tags are getting generated. 

E.g. We have a tag 'ready for dispatch' which some have written 'ready despatch' or just 'ready' and so end up having like 3 tags instead of 1.

As a small unit we dont get the best of talent who are good at spellings and so what would help is if we can get an autocomplete option so that as a user starts typing the tag name it will prompt automatically and he / she can choose. 

This will help reduce such manual errors.

Thanks,
Vikram

**Comment by vikramnarayan** [comment]
Attached are some of the tags we have. But as I mentioned earlier spelling issues happen due to which different tags get generated. In the attached screenshot, you will find that spelling mistakes exist like Lable / Labels 
![tags](https://cloud.githubusercontent.com/assets/4680031/6985679/836cc61c-da53-11e4-8fcf-df61164e44e9.jpg)

**Comment by vikramnarayan** [comment]
HI Rushabh,

I see that you have closed this issue saying enhancement. Please see attached screenshot. You will see 2 tage of 'Fully ready'. If I want to filter on the one as 'Fully Ready' the system shows me all 24 (23+1). How am I to know which has been wrongly tagged especially when it comes as 2 tags like this. 

Please look at addressing this problem soon as checking on this is causing a lot of back and forth internally.

Thanks,
VIkram
![image](https://cloud.githubusercontent.com/assets/4680031/7203339/93ba1b16-e537-11e4-8a5f-0baeac9dba67.png)

**Comment by vikramnarayan** [comment]
Hi Rushabh,

This tag cleanup everyday is becoming a daily task for me. Please check today's screenshot. Check out the number of spelling error I have on RM Due. Please look at providing this asap. 
![tag 1](https://cloud.githubusercontent.com/assets/4680031/7235582/9c0b040c-e7ac-11e4-910f-1445edb2446a.JPG)


Vikram

**Comment by anandpdoshi** [comment]
This issue is fixed in version 5
