### ISSUE TITLE
bug: base_operating_cost default set to 5 in BOM Operation doctype

### ISSUE THREAD

**Issue by nameduser0** [frappe/erpnext#30501]
### Information about bug

On importing a BOM with a simple Operation, base_operating cost is set to 5 (five)

https://github.com/frappe/erpnext/blob/b981fae5a410785df10e8b06a4681c3ef550d252/erpnext/manufacturing/doctype/bom_operation/bom_operation.json#L112

| Item | Quantity | Item Code (Items) | Qty (Items) | Operation (Operations) | With Operations | Company | Currency | Conversion Rate | UOM (Items) | Rate (Items) |
| -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- |
| ItemParent | 1 | ItemChild | 1 | Cell A | 1 | YourCompany | GBP | 1 | Nos | 0 |

![Screen Shot 2022-03-30 at 20 27 25](https://user-images.githubusercontent.com/64409021/160915225-b55552d4-f519-44d1-8889-921cc9530ff3.png)

## Workaround:
Customise the `BOM` doctype, switch the customise page to `BOM Operation` and set the default to blank

### Module

manufacturing

### Version

v13.19.0

**Comment by rickydjunaidy** [comment]
+1, I also encountered this problem, i'd like to know why they set default to 5.
