### ISSUE TITLE
bug: creating Work Order from Production Plan must be made in Default Company else 'Warehouse Finished Goods - ABC does not belong to company None'

### ISSUE THREAD

**Issue by nameduser0** [frappe/erpnext#30505]
### Information about bug

There is a check when creating Work Orders from a Production Plan that the `For Warehouse` belongs to the Global Default - Default Company. It is quite possible that multiple companies could be using the same instance with separate warehouses and doing manufacturing at the same time.

The Work Order should be created for the Company set in the Production Plan.

![Screen Shot 2022-03-30 at 22 15 56](https://user-images.githubusercontent.com/64409021/160932281-c781ef17-c001-4f5b-9149-e10e0b5aff63.png)

### Module

manufacturing

### Version

v13.19.0

**Comment by marination** [comment]
@casesolved-co-uk Steps to replicate? I couldn't replicate this on v13 or develop.

**Comment by racitup** [comment]
@marination I really don't see the utility in locking me out of my own issue. I am not able to edit. Details updated below

### Information about bug

There is a check when creating Work Orders from a Production Plan that the `For Warehouse` belongs to the Global Default - Default Company. It is quite possible that multiple companies could be using the same instance with separate warehouses and doing manufacturing at the same time.

The Work Order should be created for the Company set in the Production Plan.

![Screen Shot 2022-03-30 at 22 15 56](https://user-images.githubusercontent.com/64409021/160932281-c781ef17-c001-4f5b-9149-e10e0b5aff63.png)

Steps to reproduce:

- Create two Companies, A and B, set A as global default
- Ensure there are sub-assembly Items and BOMs
- Ensure warehouse defaults are set to Company B for Items
- Create a Production Plan and Work Orders for Company B

Notice Work Orders for anything other than the top-level product are set to Company A, not Company B

### Module

manufacturing

### Version

v13.19.0
