### ISSUE TITLE
Live preview of naming series

### ISSUE THREAD

**Issue by markandpathak** [frappe/erpnext#30519]
**Is your feature request related to a problem? Please describe.**
Issue is non-technical users can not get idea how actual series will be generated. Myself found few errors in named series formatting (like "." or visible "#" etc.).  It will be helpful if while entering any series, a live preview appears just below it so that we can know how series will be generated.  

**Describe the solution you'd like**
There should be instant live preview below the filed where named series is being entered.

**Comment by ankush** [comment]
@markandpathak checkout https://github.com/frappe/erpnext/pull/31141
