### ISSUE TITLE
Callback from Call Log Screen Exotel

### ISSUE THREAD

**Issue by chechani** [frappe/erpnext#30526]
### Information about bug

Hello,
I am facing below issue on callback button from call log and I also integrate Exotel.

Uncaught TypeError: frappe.phone_call.handler is not a function
![image](https://user-images.githubusercontent.com/6291292/161062385-e7637c66-15e6-4ffa-af1c-236fcaf20c1b.png)

### Module

integrations, other

### Version

Frappe version - 14 beta 2
ErpNext version - 14 beta 2

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
call_log__custom_js:7 Uncaught TypeError: frappe.phone_call.handler is not a function
    at eval (call_log__custom_js:7:22)
    at HTMLButtonElement.o (page.js:577:19)
    at HTMLButtonElement.dispatch (jquery.js:5430:27)
    at HTMLButtonElement.o1.handle (jquery.js:5234:28)
eval	@	call_log__custom_js:7
o	@	page.js:577
dispatch	@	jquery.js:5430
o1.handle	@	jquery.js:5234
```

**Comment by ankush** [comment]
It seems this isn't implemented for exotel. 

Only twilio: https://github.com/frappe/twilio-integration/blob/1538de561f5341f38370bb28fc77710843f4128f/twilio_integration/public/js/twilio_call_handler.js#L92
