### ISSUE TITLE
Missing detail in Time Sheet error

### ISSUE THREAD

**Issue by wojosc** [frappe/erpnext#30546]
### Information about bug

when trying to submit a time sheet I get an error message which speaks for it's self
![image](https://user-images.githubusercontent.com/22279621/161332870-960d1d9d-78ed-4f50-a6f9-da6a200a6005.png)

It would be very helpful though, if the message would also show the line where the error happens!

### Module

projects

### Version

ERPNext: v13.23.3 (HEAD)

Frappe Framework: v13.23.0 (HEAD)

### Installation method

FrappeCloud

**Comment by nabinhait** [comment]
Now, end_date is auto set based on child table data, closing this issue.
