### ISSUE TITLE
On “Employee”  form , All special chars  are accepting in 'Class / Percentage' field.

### ISSUE THREAD

**Issue by geetanjalishitole** [frappe/erpnext#3054]
Steps-
1.Go to 'Employee'  form->'Educational Qualification' datagrid
2.Enter @#$$%$7667 in 'Class / Percentage' field.
  Expected - Special chars should not allow in  'Class / Percentage' field. (except special char dot (.))

**Comment by vrms** [comment]
there is no `Class / Percentage` field in `Edicational Qualification` (any more. maybe there has been one). 
I assume this issue is obsolete and close it therefore
