### ISSUE TITLE
If you start a transaction from the item doctype, item details are not filled on the transaction

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#30561]
### Information about bug

- Open an item
- Click on add Sales Order/Purchase Order, or downstream transactions
- The Item details, name, UOM, rate, Item Tax are not filled on the item section of the Sales Order or Purchase Order

### Module

stock, buying, selling

### Version

ERPNext: v13.23.3 (HEAD)
Frappe Framework: v13.23.0 (HEAD)

### Installation method

FrappeCloud

**Comment by ankush** [comment]
duplicate of https://github.com/frappe/frappe/issues/16401
