### ISSUE TITLE
GST Error - Wrong GST calculations for item tax template based tax calculation depending on the sequence in which Supplier and items are updated

### ISSUE THREAD

**Issue by swapniljariwala** [frappe/erpnext#30583]
### Information about bug

Detailed description on this thread: https://discuss.erpnext.com/t/default-igst-rule-is-not-working/88104/3

I defined tax template for an Item, supplier has two GST address one in state and other out state. I have enabled to override item tax in GST settings. I have made tax rate 0 in `Configuring Purchase Taxes and Charges Template`

Scenario 1 : Happy flow
Step 1: Add purchase order
Step 2 : Add an item, required by date, qty and rate
Step 3: Choose supplier (Default GST is out state - Gujrat)
Step 4: Update the supplier’s maharashtra address (In state)

Result: Working as expected

Scenario 2 : Sad flow:

Step 1: Add purchase order
Step 2 : Choose supplier (Default GST is out state - Gujrat)
Step 3: Update the supplier’s maharashtra address (In state)
Step 4: Add an item, required by date, qty and rate

Result: Unexpected, All taxes being added to the PO

### Module

accounts, buying

### Version

Both 13

### Installation method

docker

### Relevant log output / Stack trace / Full Error Message.

```shell
Detailed screenshot of the issue on the mentioned thread:
https://discuss.erpnext.com/t/default-igst-rule-is-not-working/88104
```

**Comment by swapniljariwala** [comment]
Source of error is probably different ways in which taxes are dealt in below APIs

api/method/erpnext.stock.get_item_details.get_item_details ->
```Python
{
item_tax_rate: "{\"Output Tax SGST - DC\": 6.0, \"Output Tax CGST - DC\": 6.0, \"Output Tax IGST - DC\": 12.0, \"Input Tax SGST - DC\": 6.0, \"Input Tax CGST - DC\": 6.0, \"Input Tax IGST - DC\": 12.0, \"Input Tax SGST RCM - DC\": 6.0, \"Input Tax CGST RCM - DC\": 6.0, \"Input Tax IGST RCM - DC\": 12.0}"
item_tax_template: "GST 12% - DC"
}
```

api/method/erpnext.controllers.accounts_controller.get_taxes_and_charges
```Python
{'message': [{'account_currency': None,
              'account_head': 'Input Tax SGST - DC',
              'add_deduct_tax': 'Add',
              'base_tax_amount': 0.0,
              'base_tax_amount_after_discount_amount': 0.0,
              'base_total': 0.0,
              'category': 'Total',
              'charge_type': 'On Net Total',
              'cost_center': 'Main - DC',
              'description': 'Input Tax SGST',
              'included_in_paid_amount': 0,
              'included_in_print_rate': 0,
              'item_wise_tax_detail': None,
              'rate': 0.0,
              'row_id': None,
              'tax_amount': 0.0,
              'tax_amount_after_discount_amount': 0.0,
              'total': 0.0},
             {'account_currency': None,
              'account_head': 'Input Tax CGST - DC',
              'add_deduct_tax': 'Add',
              'base_tax_amount': 0.0,
              'base_tax_amount_after_discount_amount': 0.0,
              'base_total': 0.0,
              'category': 'Total',
              'charge_type': 'On Net Total',
              'cost_center': 'Main - DC',
              'description': 'Input Tax CGST',
              'included_in_paid_amount': 0,
              'included_in_print_rate': 0,
              'item_wise_tax_detail': None,
              'rate': 0.0,
              'row_id': None,
              'tax_amount': 0.0,
              'tax_amount_after_discount_amount': 0.0,
              'total': 0.0}]}
```

**Comment by swapniljariwala** [comment]
Track owners, please take a look - @marination , @rohitwaghchaure , @nextchamp-saqib

**Comment by swapniljariwala** [comment]
Hi @deepeshgarg007 

Let me know if you need any more information.

Thanks
Swapnil

**Comment by swapniljariwala** [comment]
@deepeshgarg007 Any updates on this.

**Comment by rakshitsukanta** [comment]
I am experiencing similar problem in manual installation v13. Every time I have to delete all the taxes from purchase invoice and again add the correct one from Purchase Taxes and Charges Template. Please test and look into this matter.

**Comment by swapniljariwala** [comment]
@deepeshgarg007 Any updates on this?

**Comment by deepeshgarg007** [comment]
<img width="1353" alt="Screenshot 2022-09-15 at 8 09 25 PM" src="https://user-images.githubusercontent.com/42651287/190433151-448eac36-7eeb-43d9-b996-0c8b9b075590.png">

@swapniljariwala if this is enabled, it will fetch all taxes mentioned in the item tax template, the entire config seems to be incorrect, disable this follow the approach mentioned in https://docs.erpnext.com/docs/v13/user/manual/en/accounts/articles/gst-for-multiple-branches

Just avoid source state in Tax Category if you have just one branch, two tax categories will be enough for you
