### ISSUE TITLE
Batch Expiry Alerts :  Important feature which will be helpfull for those who stock items with batch expiries.

### ISSUE THREAD

**Issue by OMNERP** [frappe/erpnext#30590]
In the current versions there is no specific feature which alerts the user of batches that are about to expire or have already expired. The only option present is the batch item expiry report. This report shows list of all batches and the expiry date and days to expire regardless of if the that batch item is in stock or not. And that too one has to generate report everyday which is not an ideal situation.
This would also be very useful for healthcare module where the hospital pharmacy has to store medicines and they have batch expiries.

What is propose is to have solution where there are alerts/notification for batches that are about to expire in 30/60/90 days and items that have already expired just for the batches which are in stock.

These alerts/notifications can be like card either on main dashboard or stock dashboard. A card for each criteria that shows number of batches about to expire in 30/60/90 days. When you click the card it shows all the batch details in the form of a report with the expiry dates and the remaining days to expire. Below is attached example.

![Expiry Template](https://user-images.githubusercontent.com/93649421/161909979-136250a1-09c5-4805-a8c8-f8bc9a7caf32.png)

**Comment by ankush** [comment]
This can be done on v14 with custom workspace cards 😄 


Better alerts for batches near expiry is something worth again can already be achieved by standard notifications so I don't see why we should have a specific feature for this.


Example

 
<img width="1371" alt="Screenshot 2022-04-07 at 8 00 24 PM" src="https://user-images.githubusercontent.com/9079960/162223164-8600644c-a831-42fa-a5fd-c43b31ee92bc.png">


You can also set custom filters on the report and auto-send it with "auto email report".
