### ISSUE TITLE
bug: Sales Order - Create Subscription - Makes Auto-Repeat not Subscription

### ISSUE THREAD

**Issue by nameduser0** [frappe/erpnext#30609]
### Information about bug

Intuitively you expect a `Create Subscription` action to create a Subscription and not an Auto-Repeat, especially since the Sales Order doctype is already set to Auto-Repeat and so has a `Repeat` action in the normal menu.

Appears to also be the same issue with the `Sales Invoice`.

### Module

selling

### Version

v13.24.0

**Comment by deepeshgarg007** [comment]
@nameduser0 Can you please explain from where you created this subscription and how can we replicate it at our end and reopen the issue
