### ISSUE TITLE
bug: legacy Subscription code should be fixed in a patch and removed

### ISSUE THREAD

**Issue by nameduser0** [frappe/erpnext#30617]
### Information about bug

There shouldn't be any code that deals with missing database data like this

https://github.com/frappe/erpnext/blob/8e425252c413dc40bdbd07c567adf430bf8efe0e/erpnext/accounts/doctype/subscription/subscription.py#L348

### Module

accounts

### Version

v13.24.0

**Comment by deepeshgarg007** [comment]
@nameduser0 One instance could have multiple companies and which subscription is for which company was not identifiable at that moment and this was the best way to handle this as a fallback and would have worked for most users. I understand that this is not the ideal way but there was no other way possible. If you have any suggestions please suggest and reopen the issue
