### ISSUE TITLE
Telephony Module should be moved to Frappe

### ISSUE THREAD

**Issue by nameduser0** [frappe/erpnext#30615]
**Is your feature request related to a problem? Please describe.**
It appears that the Telephony Module is in ERPNext only because it relies on the `Employee Group` for incoming call groups.

This overly restricts its use.

What if people on the phones are not employees?
What if someone wanted to integrate with another call service and run the telephony module separate from ERPNext, for example as a phone service provider for customers?

**Describe the solution you'd like**
- Move the Telephony module to Frappe, or separate completely?
- Create a new Group to replace `Employee Group` e.g.`Phone User Group`. `User` groups would seem like the obvious choice, especially since Employee Groups largely just fetch the User ID from the employee anyway
- Normalise the naming: `Voice Call` `Incoming Call` `Call Log` `Contact Phone` all seem to need the word `Phone` for discoverability

I also think the Exotel integration should be split out separately like Twilio was, and should not be in ERPNext

**Comment by ankush** [comment]
They'll all move out to separate apps eventually. 

context: https://www.youtube.com/watch?v=207S3celYqA

**Comment by nameduser0** [comment]
Telephony is still listed as "ERPNext Core" at 16:00

**Comment by ankush** [comment]
Some more modules are planned for removal after that video 😄
