### ISSUE TITLE
customer list opens quotation

### ISSUE THREAD

**Issue by aktp123** [frappe/erpnext#30616]
### Information about bug

hello guys just started using ERP next. I just found that while clicking customer list it opens quotation list please help 
thanks

### Module

other

### Version

ERPNext: v13.20.1 (version-13)

Frappe Framework: v13.20.1 (version-13)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
http://178.62.28.32:6565/app/home
```

**Comment by marination** [comment]
@aktp123 A GIF would help, this is not replicable

**Comment by ankush** [comment]
Reopen with more info. Quotation/Customer workspace shortcut seems to work as expected.
