### ISSUE TITLE
POS RETURN

### ISSUE THREAD

**Issue by tjomtek** [frappe/erpnext#30627]
### Information about bug

Processing a pos return at the till , if the customer paid more and the system calculated change , on return of that transaction the system seems not to know how to handle the tx.
e.g If customer bought an item for R2584 , but gave the teller R2600 and got some change back , when the teller process a return for that tx the following happens :

1. Select tx for return as seen in img below : 
![selectinvforcredit](https://user-images.githubusercontent.com/77873407/162139610-8afec8da-96db-4845-8ca2-00197a8cb3f1.png)

2. Click On Return Button to take teller to checkout : 
![image](https://user-images.githubusercontent.com/77873407/162140268-0cb945f2-f89d-451f-8e6b-338080773943.png)

3.Click on Check Out Button to proceed , the system picks up what was paid by the customer  R2600 not the actual cost of item R2584 : 
![image](https://user-images.githubusercontent.com/77873407/162140610-2cf55c86-81ff-46ca-afad-1538a2d5a1a8.png)

4. Teller populates the actual amount owing to the customer -2584 as seen img and clicks on complete order : 
![image](https://user-images.githubusercontent.com/77873407/162141484-bbda1d79-320d-452a-bd27-e25cd0609b7e.png)

5. The system displays  a message that it wants to create a new-pos invoice instead of a credit return seen img : 
![image](https://user-images.githubusercontent.com/77873407/162142181-d381d6f6-1e09-4d53-85f6-4f976453abc8.png)

6. If teller clicks on "yes" the system generates a return for the amount of -2584.

Two things should happen : 
1. The system to look at the "grand total" for returns and not "amount paid" , this should then populate the cash amount due in credit to the customer correctly.
2. The message on point(5) should display submit return for tx .... and not submit new pos invoice.

### Module

selling, other

### Version

v13.24.0 (version-13)
v13.24.0 (version-13)

### Installation method

manual install

**Comment by thida-bcn** [comment]
this is not bug
even you paid customer 2600 and he will give you back some change
actual cash out is 2584
so just record as 2584
