### ISSUE TITLE
Issues list of "Maintenance Schedule" form

### ISSUE THREAD

**Issue by geetanjalishitole** [frappe/erpnext#3062]
Issue 1- "Maintenance Shedulle" get created  without serial no.

Issue 2-Maintenace Shedule form get submitted with shedule details even though related serial no has removed from 'Item' datagrid. 

Issue 3-Maintenance Shedule get generate for serial no which are not delivered.

Issue 4-Maintenance Shedule From Sales Order-
For Item , Maintenance Schedule get created  for date which are previous date than respective delivery date.

**Comment by cgpurbaugh** [comment]
Issue 1&2 - Not all maintenance issues are serial number based.
