### ISSUE TITLE
Employee allowed to work on holiday

### ISSUE THREAD

**Issue by ShraddhaRanjane** [frappe/erpnext#3063]
If Holiday list assign to any employee and attendance get mark in between that holiday then Attendance form get save.

**Comment by rmehta** [comment]
Maybe there should be a check if whether an employee is allowed to work on a holiday or not.

**Comment by rmehta** [comment]
Make a report "Employees worked on a holiday". I think there should not be a validation as Employees can work on holidays.

**Comment by vjFaLk** [comment]
[Fixed](https://github.com/frappe/erpnext/commit/1890c794d75ee394bc574a941630ea03baf95f4e)
