### ISSUE TITLE
{Urgent} POS mode of payment issue

### ISSUE THREAD

**Issue by dufani1** [frappe/erpnext#30639]
### Information about bug

Mode of payment not working please check attac![pos mode of payment issue](https://user-images.githubusercontent.com/23026263/162282474-1e1bde00-7541-435c-85db-e59275623cd4.gif)

### Module

selling

### Version

ERPNext: v13.25.1 (HEAD)
Frappe Framework: v13.25.0 (HEAD)

### Installation method

FC

**Comment by nextchamp-saqib** [comment]
Hey, @dufani1 
I couldn't replicate the issue. Could you please send a screenshot of the browser console (ctrl + alt + i)? 

Edit: I tested by adding a mode of payment with an Urdu title

<img width="1313" alt="CleanShot 2022-04-08 at 15 18 38@2x" src="https://user-images.githubusercontent.com/25369014/162411439-b2433f15-27f7-4456-8d1b-8b0b58f8bc99.png">

**Comment by dufani1** [comment]
@nextchamp-saqib thanks for your reply.
But try to change the cash payment (default mode of payment) not change... Please recheck we are sure the pos mode of payment not work.. We tested on more than 5 sites on FC and not work on last update
All amount of money back to default mode of payment after complete the order.Please check the following link:
https://youtu.be/g9M-aW2LXyQ

**Comment by nextchamp-saqib** [comment]
@dufani1 Have raised a fix, it will be released soon with the v13.25.2 update.

**Comment by dufani1** [comment]
@nextchamp-saqib thanks

**Comment by JLS8787** [comment]
![image](https://user-images.githubusercontent.com/128277614/226156481-edf58508-f369-4dd8-9abc-22eabf6465ce.png)

Still hasn't fixed 
erpnext 13.49.5
frappe 13.51.1
