### ISSUE TITLE
Link not appearing in sales invoice for delivery note

### ISSUE THREAD

**Issue by NightsOfCoding** [frappe/erpnext#30630]
### Information about bug

When Sales invoice is created from delivery note the link for sales invoice is visible in delivery note
![Screenshot from 2022-04-07 13-45-40](https://user-images.githubusercontent.com/55629212/162153654-6bc67cdc-c534-4a2b-ad10-ae8f48267acf.png)

But the link for delivery note is not shown in sales invoice. even though reference is present in the item level of sales invoice.
![Screenshot from 2022-04-07 13-45-30](https://user-images.githubusercontent.com/55629212/162153936-c4e1bad0-4f66-42ef-9a86-035e782c9e02.png)

### Module

stock

### Version

Frappe Framework: v12.25.0 (version-12)
ERPNext: v12.28.0 (version-12)

### Installation method

manual install

**Comment by shashankshirke** [comment]
This issue still persists in v14 and looks like it was reported 2 years back in v12 (https://github.com/frappe/erpnext/issues/21391)
