### ISSUE TITLE
Monthly Leave balance problem

### ISSUE THREAD

**Issue by chandrubiradar** [frappe/erpnext#30643]
### Information about bug

This issue is on my frappe cloud instance.
I have problem while allocating earned leaves to employees.
I have total 15 leaves per year for each employee.
I want employees to get 1.25 earned leaves by end of month.
I have configured same in applicable after working days.
But the employee able to get all the leaves at the starting and they can apply any number of leaves at the 1st month itself.

Note: It's working as expected in my local instance.
But it's not working on frappe cloud

Please help me solve this issue

### Module

HR

### Version

13.25
13.25

### Installation method

FrappeCloud

**Comment by ruchamahabal** [comment]
Hello, for earned leave you need to use [**Leave Policy Assignment**](https://docs.erpnext.com/docs/v13/user/manual/en/human-resources/leave-policy-assignment) and not create Leave Allocations directly. 

Also, a couple of fixes have gone through for earned leaves:

- https://github.com/frappe/erpnext/pull/29163
- https://github.com/frappe/erpnext/pull/29650
- https://github.com/frappe/erpnext/pull/29711
- https://github.com/frappe/erpnext/pull/30613

If you are making a Leave Policy Assignment already, can you share screenshots for the Leave Type configuration, employee's joining date, policy assignment, and leave allocation records?

**Comment by ruchamahabal** [comment]
Closing this issue for now. Please upgrade to the latest version and reopen if the issue persists.
