### ISSUE TITLE
Accounts Receivable Query Report Default Letterhead

### ISSUE THREAD

**Issue by lxnow** [frappe/erpnext#30641]
### Information about bug

ERPNext allows us to set a default letter head for print formats. User expectation is that this default letterhead will be used for all print formats. However, the print format for the Accounts Receivable query report does _not_  pick this up. The same is true for the print formats of other query reports.

# how to replicate
1. Ensure you have a default letterhead set
2. Run Accounts Receivable report
3. Select print from the `...` menu
4. Click on "With letterhead"
5. You will notice that the letterhead option is blank, forcing user to pick a letterhead each time

### Module

accounts, other

### Version

Frappe 13.25.0
ERPNext 13.25.1

### Installation method

FrappeCloud

**Comment by deepeshgarg007** [comment]
@lxnow In ERPNext's context you can set the default letterhead at the company level and by default will be fetched in the reports when "With Letter Head" is checked

 
<img width="1345" alt="Screenshot 2022-09-15 at 8 31 50 PM" src="https://user-images.githubusercontent.com/42651287/190438634-b713a31b-6581-4c35-948e-34a3fc103ae1.png">

**Comment by lxnow** [comment]
Thanks @deepeshgarg007 . Is there a way to make "With Letterhead" tickbox default to checked?
![image](https://user-images.githubusercontent.com/5035210/190527199-a44f50aa-a48c-4fd6-918f-26605d9d1db3.png)
