### ISSUE TITLE
Rates are not coming in Rejection Store and Purchase Return

### ISSUE THREAD

**Issue by ruchin78** [frappe/erpnext#3065]
I have received an item from the vendor and few quantity of the same I have rejected at the time of purchase receipt also I have selected the rejection store for the purpose rejection.
Now the problem is this, when I actually rejected the quantity system didn't transferred the rates in the rejection store therefore the rates are not coming in the purchase return.
I am using ERPNext: v4.24.2
I request you to please resolve this issue in this version as well as in Version 5

**Comment by umairsy** [comment]
Ruchin,

Thanks for reporting this issue. I can replicate it in my test account as well.

We shall update you when this issue is fixed.

**Comment by rmehta** [comment]
@ruchin78 you don't actually pay for the rejected rates, hence its value is set as 0 (else they will be part of your expense)

If we set the value, then you will have to remove it manually via a journal entry, else it will stay unbalanced.

@nabinhait what do you think? Lets discuss

**Comment by ruchin78** [comment]
1. At any point of time, if I need to know that how much value of inventory
is lying with us which belongs to vendor then how would we know?
2. If a store person wants to send the material back to vendor that at what
rate/value it will show in stock entry form as there is no rate transferred?
3. There is a process called re-work/re-consider, in this process material
comes back to the relevant store by doing some process on it manually. In
that case what rate the item should pick while transferring from rejection
store to main store?
4. What inventory value should the system show in the rejection store as
there is no rate associated with the item in rejection store?

*Regards*
*Ruchin Sharma*
*ERP Specilist*
*miSport Manufacturing Pvt. Ltd.*
*+91 9718555281*
*skype id:ruchinsharmagur*

**Comment by rmehta** [comment]
1. You can keep a separate "rejected" warehouse to keep track of rejected items.
2. No value for the rejected item
3. You can do a "manufacture" type entry for loading value
4. Qty is important not value of rejected items. You can always amend value via Stock Reco

**Comment by ruchin78** [comment]
Rishabh,

In case of quantity re-offer for quality the store person will not know the
rate of item.
And it is not recommended to tell the rate of an item to store person.


*Regards*
*Ruchin Sharma*
*ERP Specilist*
*miSport Manufacturing Pvt. Ltd.*
*+91 9718555281*
*skype id:ruchinsharmagur*

**Comment by ruchin78** [comment]
Also while raising debit note, how the rates and value be calculated?
I  mean I don't see any harm for transferring rates to rejection store.

*Regards*
*Ruchin Sharma*
*ERP Specilist*
*miSport Manufacturing Pvt. Ltd.*
*+91 9718555281*
*skype id:ruchinsharmagur*

**Comment by adityaduggal** [comment]
closing this issue since it seems to be resolved in the latest version
