### ISSUE TITLE
Error While Creating Cost Center

### ISSUE THREAD

**Issue by mmsh89** [frappe/erpnext#30670]
### Information about bug

Error While creating cost center and cost center already exist but tree view not appearing V 13.20 

### Module

accounts

### Version

Frappe: Version 13.20.1
Erpnext : 13.20.0
![ERPISSUE1](https://user-images.githubusercontent.com/56976991/162650544-88bc01d3-8874-47cb-9b19-b2953d8e808d.png)
![ERPISSUE2](https://user-images.githubusercontent.com/56976991/162650548-0d2cea53-53a0-42a5-9bbd-e0df80785ee3.png)

### Installation method

manual install

**Comment by deepeshgarg007** [comment]
@mmsh89 This happens when there are some errors during setup. Please reinstall your site in order to resolve this issue, if there are any visible errors other than this then please share the tracebacks and reopen
