### ISSUE TITLE
India E Invoice - GSP Client Credential when reset from GSP's website, ERPNext still send old Auth Token

### ISSUE THREAD

**Issue by nadarvinod** [frappe/erpnext#30673]
### Information about bug

As per the below code in `erpnext/regional/india/e_invoice/utils.py ` ERPNext will fetch a new auth_token only when the token expires. But if the client secret has been reset from GSP portal and updated in the site_config still it used the old token till it expires.

```
def get_auth_token(self):
		if time_diff_in_seconds(self.e_invoice_settings.token_expiry, now_datetime()) < 150.0:
			self.fetch_auth_token()

		return self.e_invoice_settings.auth_token
```

### Module

accounts, regional

### Version

Frappe Version - v13.25.0 (version-13)
ERPNext Version - v13.25.2 (version-13)

### Installation method

easy-install

**Comment by nextchamp-saqib** [comment]
@nadarvinod 

There's no way to trigger a change if `einvoice_client_secret` in the `site_config.json` has changed
I recommend using the **Client Secret** field in the E-Invoice Settings. On change of this field, the token can be refreshed
