### ISSUE TITLE
Time Period in Maintenance Schedule

### ISSUE THREAD

**Issue by wojosc** [frappe/erpnext#30682]
### Information about bug

In the Items table of Maintenance Schedule we find to dates and a field period. When using yearl period we get to dates in the fields start_date end_date.

When setting a start_date and setting period "Yearly" we get an end_date which is the same day and month as start_date but a year later
![image](https://user-images.githubusercontent.com/22279621/162754597-c597022c-1820-4bb8-b0cd-8d267072d37c.png)

We would expect the end_date to be one day prior (in the year later) to start_date:
<img width="995" alt="image" src="https://user-images.githubusercontent.com/22279621/162754873-270fb2d9-179b-4d3c-84f8-38bed4aa30a7.png">

Does this need fixing or is there a purpose for this?

A work around is to unset "Yearly" as standard periodicy via customize form and set the no_of_visits as standard 1

![image](https://user-images.githubusercontent.com/22279621/162756610-26a9acd7-b67f-452c-ba73-064055eac2ae.png)

### Module

other

### Version

ERPNext: v13.19.0 (version-13)

Frappe Framework: v13.19.0 (version-13)

### Installation method

manual install

**Comment by nabinhait** [comment]
already fixed in latest version
