### ISSUE TITLE
Discount on "Grand total" applies discount on "Net total"

### ISSUE THREAD

**Issue by johnlongland** [frappe/erpnext#30698]
### Information about bug

When selecting to apply discount on a purchase invoice, the operator is presented with the option of applying discount
on Net total or Grand total. My perception is, that when applying discount on Grand Total, that the Net-total will still remain
the sum of the original item-prices and that discount is only applied after the item pricing has been totalled with any taxes and Charges amounts. It seems that , currently, discount is applied the same way irrespective of the "Net-total" or "Grand-total" setting
in the "Discount" section.

### Module

buying

### Version

ERPNext: v13.26.0 (version-13)

Frappe Framework: v13.26.0 (version-13)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
No errors.
```

**Comment by deepeshgarg007** [comment]
@johnlongland if you'll check the discount amount it is based on the Grand Total, post calculation of the discount amount the base values are readjusted for all the item values, and hence it affects the net total as well, this is the intended behavior and not a bug
