### ISSUE TITLE
Issues with Discount accounting in Purchase invoice with update stock : Debit and Credit not equal

### ISSUE THREAD

**Issue by johnlongland** [frappe/erpnext#30697]
### Information about bug

1. Enable "Discount accounting" in Accounts settings
2. Generate Purchase invoice (1 Item-entry; 1 "Charges+-entry ) with discount : Grand total, R12.00 discount amount. 
3. Save
4. When submitting, an error message is generated : debits and credits are not equal. Difference is equal to discount amount.
5. Disable "Discount accounting " in Accounts settings
6. Go back to "draft" Purchase invoice. Clear all entries. Re-enter entries, Save. Submit
7. No error.
8. GL reflects discounted amounts.
9. I also noticed that even though discount on Grand Total  was selected, the discount was made on items and net-total, but I shall create another issue for that
10. 
![discount_2](https://user-images.githubusercontent.com/66208349/163116193-ac3bea96-ca44-44a5-b736-90b98804f86f.PNG)
.

### Module

buying

### Version

ERPNext: v13.26.0 (version-13)

Frappe Framework: v13.26.0 (version-13)

### Installation method

manual install

**Comment by johnlongland** [comment]
I neglected to mention ... this did not happen in V12

**Comment by johnlongland** [comment]
Good day DEVS
I have done another test : This only happens if you select "Update Stock" just above the "Items" table in the purchase invoice.
If you do not select "Update Stock" it does not give you this error and the PINV is submitted and on inspection the GL seems to
be correct.

**Comment by ankush** [comment]
@rahib-hassan can you look into this one?

**Comment by deepeshgarg007** [comment]
@johnlongland Discount accounting has been removed from the Purchase Cycle as it was not making much sense there, this issue is not applicable anymore. Closing this issue
