### ISSUE TITLE
When multiple shifts are assigned to an employee, shift is empty in Employee check-in

### ISSUE THREAD

**Issue by iamejaaz** [frappe/erpnext#30696]
### Employee Checkin
![image](https://user-images.githubusercontent.com/67804911/163106587-1da66c55-2112-4113-8b6e-b35990ce6d91.png)

### Assigned shift
![image](https://user-images.githubusercontent.com/67804911/163106715-195e3d98-039b-45bc-b004-8b681cd59a0c.png)

### Morning Shift
![image](https://user-images.githubusercontent.com/67804911/163107112-c9e005bb-6389-4fa8-a10f-dbff68594639.png)

### Evening Shift
![image](https://user-images.githubusercontent.com/67804911/163113191-bfaf6e3a-1f12-4839-892a-89b266892658.png)

### I've done some R&D (I'm not 100% sure it's right or not).
![image](https://user-images.githubusercontent.com/67804911/163109278-0cfd5240-923d-4dc0-a5c0-cb7ca85dc54f.png)
Below function fetches the last assigned shift to an Employee, i.e. In my case it is Evening Shift, But I am marking Attendance for the Morning Shift (Checkin DateTime: `22-03-2022 09:54:00`).

![image](https://user-images.githubusercontent.com/67804911/163110193-c0c569f9-d5e0-4938-a4a9-2dec801596ba.png)
Here, the this ⬆️  ⬇️  condition fails, since it fetches Evening shift, which is why shift is empty:
```python
if (
	get_datetime(shift_details.actual_start) #  Evening shift Start time
	<= get_datetime(for_timestamp) # My Checkin DateTime(for Morning shift)
	<= get_datetime(shift_details.actual_end) ## Evening Shift End Time
):
```

### Module

HR

### Version

erpnext 14.0.0-dev
frappe 14.0.0-beta.3

**Comment by naquiuddin** [comment]
@ejaazkhan, just a quick guess, it could be because start time of morning shift and evening shift is same 🤔  and because the check in timestamp lies between both morning and evening checkins it is picking the evening one? 

Could you try making shifts with different time intervals.

**Comment by iamejaaz** [comment]
> @ejaazkhan, just a quick guess, it could be because start time of morning shift and evening shift is same thinking and because the check in timestamp lies between both morning and evening checkins it is picking the evening one?
> 
> Could you try making shifts with different time intervals.

![image](https://user-images.githubusercontent.com/67804911/163112638-55bb23da-0894-45a5-bc86-9d9049b8254c.png)
Changed time 😅(also updated in issue description) , Still same issue
![image](https://user-images.githubusercontent.com/67804911/163112722-8d327de7-a481-4da2-91a7-d48d175eab83.png)

**Comment by iamejaaz** [comment]
IMO the issue is here
![image](https://user-images.githubusercontent.com/67804911/163124373-d861a528-d096-434a-b47a-584c404989cc.png)
- This query log
```
SELECT `name`,`shift_type` FROM `tabShift Assignment` WHERE `employee`='HR-EMP-00001' AND `docstatus`=1 AND `status`='Active' AND `start_date`<='2022-03-22' AND (`end_date` IS NULL OR (`end_date` IS NOT NULL AND `end_date`<='2022-03-22'))
```
- IMO, the issue in this condition ``` `end_date`<='2022-03-22')```, this should be like this ``` `end_date`>='2022-03-22') ```

This change fixed my issue
