### ISSUE TITLE
Quotation : Issue on page reload in mentioned scenario

### ISSUE THREAD

**Issue by nidhipurohit11** [frappe/erpnext#30706]
### Information about bug

**Issue 1** - On opening any company master, getting these errors - 

![Screenshot 2022-04-13 at 5 45 49 PM](https://user-images.githubusercontent.com/82337328/163178112-840fc934-da1f-410e-8b60-a27e803df68a.png)

![Screenshot 2022-04-13 at 5 46 58 PM](https://user-images.githubusercontent.com/82337328/163178126-95dd5f13-5710-4898-91d5-7dbcac9e3287.png)

**Issue 2** - Opened a new quotation page. Case1 - Getting the "Valid Till" date pre-filled, Case 2 - On changing the company, the "Valid Till" date remains blank.

![Screenshot 2022-04-13 at 5 48 47 PM](https://user-images.githubusercontent.com/82337328/163178670-bd5e0f43-1aaa-4f46-91d2-2de5d493db05.png)

![Screenshot 2022-04-13 at 5 49 00 PM](https://user-images.githubusercontent.com/82337328/163178689-0b77769e-a3db-48ea-80c0-4b4daa6a4298.png)

**Issue 3** - On trying to save a quotation, not getting any error pop-up, but getting error in console like - 

![Screenshot 2022-04-13 at 5 52 16 PM](https://user-images.githubusercontent.com/82337328/163178957-0eba5e4b-e314-4dbe-a168-8a761d2167b8.png)

### Module

selling

### Version

ERPNext: v14.0.0-dev (masters-transaction-tests)
Frappe Framework: v14.x.x-develop () (develop)

**Comment by ankush** [comment]
@nidhipurohit11 Company issue is not valid. You need to update ERPNext. https://github.com/frappe/erpnext/pull/30521
