### ISSUE TITLE
Can't pay POS in Version 5

### ISSUE THREAD

**Issue by LeaFin** [frappe/erpnext#3070]
A new sales invoice in POS can't be payed in Version 5. The error is
Missing Values Required: 
- Amount Paid

But there isn't a field Amount Paid.

**Comment by rmehta** [comment]
I can see it. Can you share a screenshot?

![screen shot 2015-04-14 at 2 28 25 pm](https://cloud.githubusercontent.com/assets/140076/7133587/8e524180-e2b2-11e4-9843-9b63adb1bafb.png)
