### ISSUE TITLE
After updating to Version V13.26 unable to update lead status field options

### ISSUE THREAD

**Issue by kidsyn** [frappe/erpnext#30727]
### Information about bug

Post update to V13.26 lead status options is not customizable as it throws up error "You can't set 'Options' for field Status".

prior versions we were able to update the status.

![image](https://user-images.githubusercontent.com/65041616/163723797-465b290a-fa79-4b42-b9e6-5a0becd4be58.png)

https://discuss.erpnext.com/t/you-cant-set-options-for-field-status-erpnext-v13-22-1-version-13/87376/8

https://discuss.erpnext.com/t/erpnext-new-version-issue-erpnext-v13-22-1-version-13/87377/2

### Module

CRM

### Version

ERPNext: v13.26.0 (version-13)
Frappe Framework: v13.26.0 (version-13)

### Installation method

easy-install

**Comment by ankush** [comment]
This is by design. Standard field options shouldn't be customizable, adding more options will break core business logic. 

Create a custom field instead.
