### ISSUE TITLE
Manual Depreciation Method  is not working in the ERPNext. 

### ISSUE THREAD

**Issue by JitendraSAW** [frappe/erpnext#30722]
### Information about bug

Step-1
Created the Assets Category

![image](https://user-images.githubusercontent.com/80260184/163663719-7c9f2d8f-90ef-4fa5-89ee-3c7f28f24b0b.png)

![image](https://user-images.githubusercontent.com/80260184/163663748-217030a2-d3ae-4358-b8fa-343741fee540.png)

Step-2
Created the Item Master as an Asset

![image](https://user-images.githubusercontent.com/80260184/163667399-9553bb68-06d8-498c-a2bc-8ca5bbbe40cc.png)

Step-3
Created the Asset Item
![image](https://user-images.githubusercontent.com/80260184/163667446-b26a3080-391f-44fc-a4b7-62f1c6cf6ee5.png)

![image](https://user-images.githubusercontent.com/80260184/163667504-f5ab8431-d29a-4f80-a85f-6d3957d30fda.png)

Hence if we see it is not allowing to change teh Depreciation amount manually though we have selected Manual Deprciation Method.

### Module

assets

### Version

![image](https://user-images.githubusercontent.com/80260184/163667567-ce6335f3-24bd-4cd1-9805-59959c012d51.png)

### Installation method

FrappeCloud

**Comment by dgerhardt** [comment]
I can confirm this issue. "Manual" seems to behave like "Straight Line" and does not allow any manual modifications and therefore does not behave as documented ("In this method, you can define the Schedule Date and Depreciation Amount for each period.").
