### ISSUE TITLE
Error getting items from delivery notes from sales invoice

### ISSUE THREAD

**Issue by monroy95** [frappe/erpnext#30766]
### Information about bug

When pressing the button, get delivery note items from sales invoice, when selecting a date range it throws the following error:

![error3](https://user-images.githubusercontent.com/26640728/164338660-5fe2e1a3-ab61-4005-9347-1d5aea891f86.png)

<hr>

1.
![error1](https://user-images.githubusercontent.com/26640728/164338933-d4741ffc-8ee2-46d6-8433-92fef057c028.png)

2.
![error2](https://user-images.githubusercontent.com/26640728/164338967-3d68f073-3226-4f7f-a701-6f9a41a199ac.png)

3.
![error3](https://user-images.githubusercontent.com/26640728/164338972-68efd63e-1ca9-48ac-b6f4-a18a1993dd01.png)

### Module

accounts

### Version

Frappe version - v13.26.1
ERPNext version - v13.27.0

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "13.27.0",
	"frappe": "13.26.1"
}
```
### Route
```
Form/Sales Invoice/new-sales-invoice-2
```
### Trackeback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 37, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 75, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1447, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/search.py", line 126, in search_widget
    raise e
  File "apps/frappe/frappe/desk/search.py", line 114, in search_widget
    frappe.response["values"] = frappe.call(
  File "apps/frappe/frappe/__init__.py", line 1447, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/search.py", line 294, in validate_and_sanitize_search_inputs
    return fn(**kwargs)
  File "apps/erpnext/erpnext/controllers/queries.py", line 389, in get_delivery_notes_to_be_billed
    "fcond": get_filters_cond(doctype, filters, []),
  File "apps/frappe/frappe/desk/reportview.py", line 710, in get_filters_cond
    query.build_filter_conditions(flt, conditions, ignore_permissions)
  File "apps/frappe/frappe/model/db_query.py", line 484, in build_filter_conditions
    conditions.append(self.prepare_filter_condition(f))
  File "apps/frappe/frappe/model/db_query.py", line 607, in prepare_filter_condition
    value = frappe.db.format_date(f.value)
  File "apps/frappe/frappe/database/database.py", line 1030, in format_date
    return getdate(date).strftime("%Y-%m-%d")
AttributeError: 'NoneType' object has no attribute 'strftime'

```
### Request Data
```
{
	"type": "GET",
	"args": {
		"doctype": "Delivery Note",
		"txt": "",
		"filters": "{\"docstatus\":1,\"company\":\"Gasolinas Economicas S.A.\",\"is_return\":0,\"customer\":\"Juan Perez\",\"posting_date\":[\"Between\",null]}",
		"filter_fields": "[\"customer\"]",
		"page_length": 25,
		"query": "erpnext.controllers.queries.get_delivery_notes_to_be_billed",
		"as_dict": 1
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.search.search_widget"
}
```
### Response Data
```
{
	"exception": "AttributeError: 'NoneType' object has no attribute 'strftime'"
}
```
```

**Comment by infinity-sys** [comment]
Confirmed

ERPNext: v13.29.2 (version-13)
Frappe Framework: v13.29.0 (version-13)

**Comment by carmagu** [comment]
Confirmed

ERPNext: v13.34.2 (version-13)
Frappe Framework: v13.34.0 (version-13)

The error appears to be caused by the "get_delivery_notes_to_be_billed" script, which does not properly create the fcond string variable...

**Comment by infinity-sys** [comment]
I confirm for the bug
anybody found a solution

**Comment by jayan13** [comment]
apps/frappe/frappe/desk/reportview.py
get_filters_cond()
line 687
elif isinstance(f[1], (list, tuple)) and f[1][0] in (
">",
"<",
">=",
"<=",
"!=",
"like",
"not like",
"in",
"not in",
"between",
):

update in values
-----------------
elif isinstance(f[1], (list, tuple)) and f[1][0] in (
"=",
">",
"<",
">=",
"<=",
"!=",
"like",
"not like",
"in",
"not in",
"Between",
"between",
):

**Comment by deepeshgarg007** [comment]
Can replicate this, please add proper replicable steps and reopen the issue
