### ISSUE TITLE
Ignore Price list Issue

### ISSUE THREAD

**Issue by smehata** [frappe/erpnext#30769]
### Information about bug

When Ignore Pricing Rule is True and I apply Custom Rate to the item and after that, I change the date and currency, it replaces the Custom Rate of the item with the Price List Rate in Sales invoice

### Module

other

### Version

erpnext version-14-beta

**Comment by deepeshgarg007** [comment]
Should be fixed via https://github.com/frappe/erpnext/pull/30990
