### ISSUE TITLE
Custom Purchasing Analytics vs. Sales Analytics Report Needed

### ISSUE THREAD

**Issue by katieo** [frappe/erpnext#3077]
I need to be able to pull data for a specific purchasing analytic (supplier group) and compare it to a specific sales analytic (item group or item) on a weekly, monthly, quarterly etc basis.  I would like to be able to set up reports for each of the combinations I need to look at so I can just run these specific reports and see how much was spend / received on a specific category vs how much was sold.  That data is available in the Purchasing Analytics reports and Sales Analytics reports but I have to manually combine and manipulate them / make a summary for the data to be easily read.

**Comment by rmehta** [comment]
There is a new gross profit report in version 5

Also would you be interested in sponsoring such a report?

**Comment by umairsy** [comment]
Closing because inactive since long time. Feel free to reopen if needed.
