### ISSUE TITLE
UOM specific barcodes

### ISSUE THREAD

**Issue by ankush** [frappe/erpnext#30777]
is it possible also support barcode for different UOM, e.g item has default UOM as PC, there is barcode for UOM Box, when scan the box barcode, in items table, both the quantity and UOM will be handled correctly.

_Originally posted by @szufisher in https://github.com/frappe/erpnext/issues/30445#issuecomment-1080076066_

**Comment by ankush** [comment]
@szufisher also shared a decent design for this on discuss forum, IMO we can implement it as is. 
https://discuss.erpnext.com/t/multiple-barcodes/31577/10?u=ankush


cc: @marination 


related: 
- https://discuss.erpnext.com/t/feature-request-multiple-barcode-per-item/12739/13 
- https://github.com/frappe/erpnext/issues/6910

**Comment by ankush** [comment]
@szufisher can you send the first cut PR? I can review and finish if there are any rough edges (probably need to check all transactions where scanning is used and if triggers are happening properly or not)

**Comment by szufisher** [comment]
@ankush Okay, I will do .

**Comment by ankush** [comment]
@szufisher thanks!

**Comment by ankush** [comment]
@szufisher any updates? if you're unable to do it lmk I can take this up 😅

**Comment by Andriesvn** [comment]
Could you please Backport this to v13 as well?

**Comment by ankush** [comment]
Doubt this can be backported, many internally incompatible changes are done to barcode scanning that this PR depends on. Also, we _usually_ don't port features to previous stable versions.
