### ISSUE TITLE
Is Return (Credit Note) column not show Tick in pdf view

### ISSUE THREAD

**Issue by tsothun** [frappe/erpnext#30775]
### Information about bug

![photo_2022-04-21_22-19-49](https://user-images.githubusercontent.com/56767875/164490694-3a8614b7-d99a-40bf-a853-bc4e4027328f.jpg)
![photo_2022-04-21_22-19-53](https://user-images.githubusercontent.com/56767875/164490705-5437ac24-a098-4ec1-a65c-2e914799a55d.jpg)

### Module

selling

### Version

ERPNext version 13

**Comment by ankush** [comment]
This was fixed in 13.26.1

https://github.com/frappe/frappe/pull/16648
