### ISSUE TITLE
Data import tool is not working Properly. 

### ISSUE THREAD

**Issue by mansuralitharadara** [frappe/erpnext#30782]
### Information about bug

I am trying to upload the sales invoice through data import. The sales invoice template is created in Google Sheet. No error is found before uploading. (sales invoice template contains more than 2000 invoices at a time). 
So my problem is when I press "Start Import" the Invoices are not Importing and there is no error notification also. Once I refresh the page "Start Import" button is shown. I am tried this multiple times but nothing is happening. 
I check the Internet connection but everything is proper.

### Module

other

### Version

Frappe Framework: v13.26.0 (HEAD)
ERPNext: v13.26.0 (HEAD)

### Installation method

FrappeCloud

**Comment by dj12djdjs** [comment]
@mansuralitharadara When you click "Start Import" check your background jobs. Most likely it is getting queued and has not started yet.
