### ISSUE TITLE
Plaid ERPNext to bank Mercury

### ISSUE THREAD

**Issue by chiefwinnoven** [frappe/erpnext#30789]
### Information about bug

We use a frappe account for our ERPNext. I click onto Plaid then click on link a new account or reset plaid link. If I use sandbox it works. But if I set it to developer (I change and use the correct security for each) it keeps coming back with the errors I have attached. 
<img width="965" alt="Screen 1" src="https://user-images.githubusercontent.com/104253711/164888607-568b0c65-ee75-43fa-ba99-3f487ebaa57b.png">
<img width="1305" alt="screen 2" src="https://user-images.githubusercontent.com/104253711/164888612-a914a58e-d89c-446c-80d2-efc516ce1d02.png">
<img width="410" alt="screen 3" src="https://user-images.githubusercontent.com/104253711/164888614-78abb4d2-f1f6-48d0-bc5f-eb3b6d1532fb.png">
<img width="375" alt="screen 4" src="https://user-images.githubusercontent.com/104253711/164888615-5789f803-6c4f-463f-92a2-687ff8c0ef2c.png">

### Module

integrations

### Version

I use the most recent version of all being Frappe keeps them updated.

### Relevant log output / Stack trace / Full Error Message.

```shell
see attachments
```

**Comment by batonac** [comment]
I have it working in ERPNext 13 & 14 syncing to Mercury using Plaid development. Is there any way you can provide more details? A log entry perhaps?

**Comment by chiefwinnoven** [comment]
I found the reason. After opening a ticket with them they responded with:Development usage


Test your Plaid integration with real credentials by adding up to a total of 100 
Each Item added counts towards this limit, even if it is later removed.
Item Adds
1
of 100 used

It connected now.

I wonder what the cost of using the production version?

**Comment by batonac** [comment]
They charge per new connection validation, not for the long term sync usage per my understanding. Better close this ticket...
