### ISSUE TITLE
all user same icon

### ISSUE THREAD

**Issue by kananeto** [frappe/erpnext#3078]
![image](https://cloud.githubusercontent.com/assets/3488769/7042016/141401d8-de11-11e4-9b53-7a50bc3fb871.png)

hi, i dont know why but all the user have the same icon.

**Comment by anandpdoshi** [comment]
Is someone else having the same problem? Maybe you can attach an export of
the User table's user_image field and see if they actually have the same
value? Maybe someone used data import tool and changed the value of this
field?

-Anand.
