### ISSUE TITLE
Error: Value missing for Item Price: UOM

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#30784]
### Information about bug

Steps

- Under customize form for Item Price, make UoM mandatory, (that way users can capture item prices for different UoMs correctly)
- Create a new item, with no item price
- Create a Purchase Order(it usually creates the new item price for this case.)
- Try saving the Purchase Order, it fails with: **Error: Value missing for Item Price: UOM**

I think it should use the default UoM/Stock UoM in this case.

### Module

stock, buying

### Version

ERPNext: v13.26.0 (version-13)
Frappe Framework: v13.26.0 (version-13)

### Installation method

FrappeCloud

**Comment by ankush** [comment]
Disable auto insertion of prices?

> I think it should use the default UoM/Stock UoM in this case.

It should be whatever is UOM on the transaction being submitted.

**Comment by muchai** [comment]
> Disable auto insertion of prices?
This would be a temporary fix, right? Because I think the auto-creation of the item price during purchase order creation should include the UoM (all the time, in some cases, via user settings?). Reporting it as a thing that needs some improvement, rather than a show stopper.

**Comment by lxnow** [comment]
> It should be whatever is UOM on the transaction being submitted.

It isn't. Tested on v13.40.3 . It doesn't follow the UOM specified in the purchase order. It follows default stock UOM.

I think line 856 here : https://github.com/frappe/erpnext/blob/8b69a3ec7a2427e90abae35ddda0bc9fba7dd282/erpnext/stock/get_item_details.py

needs to be changed from 
```
"uom": args.stock_uom,
```
to
```
"uom": uom,
```
