### ISSUE TITLE
Add Communication to Customer

### ISSUE THREAD

**Issue by schmidan** [frappe/erpnext#3080]
When i Post an Invoice and choose not to send an email erpnext will create a Communication.
This Communication is neither automatically Tagged to/with the Customer nor seems there to be a possibility to Tag this Communication to the Customer (or vice versa).
I think there should be such a possibility, as it is entirely possible to create a Communication via the Customer Form and have it show up in his "Communication History".

A Feature do add/tag Communications to a Customer would be greatly appreciated.

Thanks for the fantastic work!

**Comment by schmidan** [comment]
Linkback: https://discuss.frappe.io/t/communication-not-added-to-customer/5344

**Comment by rmehta** [comment]
Which version are you using. In version 5, communications are a part of any transaction.

**Comment by schmidan** [comment]
We were on 4.24. Will upgrade in the next couple of days and test it out.
Hope v5 will meet our needs and apologies for this "old version issue"

**Comment by rmehta** [comment]
No apologies :smile: please keep reporting issues and suggestions.
