### ISSUE TITLE
[V5] Item tables in many transactions are getting to a single column in V5 as per enclosed screen shots.

### ISSUE THREAD

**Issue by adityaduggal** [frappe/erpnext#3081]
This is also seen in SO and SI.

![image](https://cloud.githubusercontent.com/assets/1057509/7045140/bcf88182-de18-11e4-8b97-d6971cc5d16c.png)

**Comment by adityaduggal** [comment]
This kind of behavior is basically seen on those tables where the modification on the customize form view has been made.

**Comment by rmehta** [comment]
What is your suggestion? Should we reset customized layouts when version 5 is updated?

**Comment by adityaduggal** [comment]
Resetting is a big issue when a lot of users would have already made tons of customize form views changes and hence a risky thing. I would suggest that we raise forum topic and pin it as a known issue and a remedy to do the same.

If the resolution is to be done at the user's end then I think this issue should be closed.

**Comment by rmehta** [comment]
how bad was the layout? Was it only minor work? then we can leave it as it is.

**Comment by adityaduggal** [comment]
I am trying to get the layout to work but still getting many errors....some like duplicate property setter values for net_total.

Getting difficult for me to customize but I am still against resetting the layout as it would reset the perm level which is of major concern than the placement.

Though placement also can decide which fields are visible to which roles for ex if a field is intially placed under a section break with perm level  2 but now it get readjusted to be placed under a section break whose perm level 1 or 0.

**Comment by rmehta** [comment]
We can reset property setters for layout only. No changes on other customizations. Would that work?

**Comment by adityaduggal** [comment]
Yes, deleting the idx values in property setter did resolve the issue and I don't think a lot of people would create a big ruckus on this as setting the idx is not a big task now given the drag and drop is there.
