### ISSUE TITLE
Amendment of submitted sales order entries

### ISSUE THREAD

**Issue by ftorreti** [frappe/erpnext#3082]
We have created a sales order, started fulfilling that through a Make to Order process: Created material request, created PO, started receiving goods through multiple purchase receipts. All ok. 

Before the order was completed, invoiced and delivered, the customer has amended the order by adding a new SKU.  

We want to be able to use the same Sales Order but we cannot do so as the entry has already been submitted and we cannot amend this entry because we have multiple purchase receipts, a purchase order and a material request. 

How can we resolve this situation? We cannot create another sales order as according to our customer requirements we must invoice and ship under the same SO reference.

**Comment by rmehta** [comment]
This is a common request.

Can we:

1. On cancel, do nothing. Cancelled transactions stay as they are unless amended. All SL / GL / balances stay as they are.
2. On amend + submit, rework all the references and do cancel + submit

Seems like an easy fix. Cancelled orders remain submitted in a sense, until they are re-submitted. @robertbecht has been asking this for a long time/

@nabinhait @anandpdoshi  ?

**Comment by rmehta** [comment]
On further discussion:

1. Skip Cancel, allow user to directly amend
2. On submission of cancel and amend
  - do cancel entries
  - reset links
  - do submit entries
  - (or make an on_amend)

**Comment by rmehta** [comment]
I guess we should just have special workflows for 

1. Add / remove item
2. Change rate, qty, tax

after submit.

**Comment by anandpdoshi** [comment]
Or we could have a unlink/link feature in framework that unlinks a document, then user can cancel/amend. Then we have a link to document feature that's like a reconciliation in a way.

**Comment by David-at-GitHub** [comment]
Is there any way to amend already partial delivered Sales Orders? Let's say a Sales Order has 3 rows, 2 were delivered, customer wants to add a 4th row/product. I tried the suggested 'cancel' way, but it doesn't allow me to cancel an already partial delivered Sales Order.

**Comment by rmehta** [comment]
Easiest would be to create another Sales Order.

Can you post questions on the forum? GitHub issues is for bug reports and feature requests.
