### ISSUE TITLE
UAE TRN (tax_id) Not Showing on Quotation

### ISSUE THREAD

**Issue by knimer** [frappe/erpnext#30836]
### Information about bug

We have a customer that already have a TRN (tax_id) defined for it.

This is the Customer record screen shot:

![image](https://user-images.githubusercontent.com/32583831/165729287-8c4ede55-e137-4a84-91d8-f5a2e7b09b2f.png)

We are using a Print format that is as below screen shot:

![image](https://user-images.githubusercontent.com/32583831/165729770-f7a9b912-7d09-4ecb-a4d9-2eda2c8cc27f.png)

When editing the Print Format, this is the screen shot for the Print Format:

![image](https://user-images.githubusercontent.com/32583831/165730295-6d5e929a-dec7-4e64-81e7-5688acf541e2.png)

Now when we look at the Quotation Print view and assign the same print format, we see the below where the TRN (tax_id) is not present:

![image](https://user-images.githubusercontent.com/32583831/165730811-0e2d2824-1593-411a-9681-a3dfee119416.png)

But, for Sales Invoices, there is no issue! We can see the TRN (tax_id).

### Module

selling

### Version

ERPNext: v13.27.0 (HEAD)
Frappe Framework: v13.26.1 (HEAD)

### Installation method

FrappeCloud

**Comment by deepeshgarg007** [comment]
@knimer Was the transaction id fetched on the quotation first, if not then it won't be displayed, look like you added a custom field but did not add anything to fetch the value in that field
