### ISSUE TITLE
Auto population of Cost center

### ISSUE THREAD

**Issue by johnlongland** [frappe/erpnext#30839]
### Information about bug

good day to the DEVS

I placed this under the tag of BUG but a good argument could also be made to place it under "Feature request".
Perhaps the truth is somewhere in the middle.

Whenever I enter Purchase invoices and payments, there is the "Cost Center" field.  I only have one Cost- Center so I don't
really use it to the extent that some others may, but I do use one cost center. I do however, have to fill it in myself, which 
I have learned to do. In the company setup, there is a setting "Default Cost Center" ( which I have setup ) and yet I still
have to enter the Cost Center in docs requiring it. In the same way that the default account settings is setup in the company,
are being use to auto-populate account-fields in docs, in the same way I feel that the cost-center can be auto-populated.

I did some reading of other posts and found some where other users are in a situation because of this.

E.g this post..

https://discuss.erpnext.com/t/cost-center-not-updated-for-old-records/86177/2

In this post, the user does not complain or anything, but if there was an auto-populate setup in ERPNext, then they
will not find themselves in a situation when deciding to start using cost-centers.

So, this is just a request to the DEVS to consider an auto-population of Cost-center .... , if possible.... , Please.
And then , if a user has a more complex cost-center setup, then they can change it from the default to the setting of
their choice in the doc they are using.

Thanks for your time.

### Module

accounts, buying

### Version

ERPNext: v13.26.0 (version-13)

Frappe Framework: v13.26.0 (version-13)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
N/A
```

**Comment by deepeshgarg007** [comment]
@johnlongland If this is happening then this is surely a bug, I tried locally but couldn't replicate this. Can please mention which doctype and how you are facing this issue? It will be helpful for us to investigate further. Please update and reopen the issue
