### ISSUE TITLE
The "erpnext.org" is affiliate or under ERPNEXT this Official Community?

### ISSUE THREAD

**Issue by Special-Niewbie** [frappe/erpnext#30860]
Hello everyone,

As per title, it Is the `https://erpnext.org/` affiliate or under ERPNEXT Community control? 

I was looking for the Virtual Machine of Erpnext to test it , but here in Github, in README file it's not mentioned .....

**Comment by ankush** [comment]
VMs are discontinued in favour of docker based installs.
