### ISSUE TITLE
Field "Value Difference" in Stock Entry doctype calculation wrong way round.

### ISSUE THREAD

**Issue by riffraff2009** [frappe/erpnext#30867]
### Information about bug

I think the Value Difference field is supposed to calculate the value added to an item. The text says "Total Value Difference(Out - In) but the code calculates (In - Out)

From stock_entry.py
`def set_total_incoming_outgoing_value(self):`
		`self.total_incoming_value = self.total_outgoing_value = 0.0`
		`for d in self.get("items"):`
			`if d.t_warehouse:`
				`self.total_incoming_value += flt(d.amount)`
			`if d.s_warehouse:`
				`self.total_outgoing_value += flt(d.amount)`

		`self.value_difference = self.total_incoming_value - self.total_outgoing_value`

### Module

stock

### Version

v13.21.0
v13.21.0

### Installation method

manual install

**Comment by ankush** [comment]
It's correct. 

Example: 

Additional cost is added to inventory value using repack: 
<img width="1132" alt="Screenshot 2022-05-02 at 2 43 50 PM" src="https://user-images.githubusercontent.com/9079960/166211942-9ac6678e-ba23-4a2f-b5fc-d5f416915fea.png">



Outgoing = consumption
incoming = receipt


difference ~= difference added in inventory value. 

Anyway, this field isn't used anywhere in business logic. 




The field order and field labels are confusing maybe?
