### ISSUE TITLE
 “Rate” issue when importing ‘Sales order’ CSV template 

### ISSUE THREAD

**Issue by ShraddhaRanjane** [frappe/erpnext#3088]
I have created "Item Price List" for respective item with Define "Rate".
when we download "Sales order" template From 'Data import tool' and entering same item, quantity but not "Rate"(Because i have create "Item Price" for that item) after importing that "Sales Order" .csv, Define 'Rate' not reflected into system (For that sales order)

**Comment by rmehta** [comment]
answered via discuss
