### ISSUE TITLE
Newly created naming series not showing in New Item form's Series drop down and 'Update Series' section of Naming Series form

### ISSUE THREAD

**Issue by smtwkla** [frappe/erpnext#30905]
### Information about bug

When creating new item, the Series selection drop down lists only 4 items. But in Naming Series, for 'Item', the 'Series List for this Transaction' text box has 8 series defined. The other 4 are not displayed and we are not able to create items using this series.  Also, new series created is not showing in 'Update Series' section of the Naming Series form.

### Module

stock

### Version

Frappe Cloud.
ERPNext: v13.27.0 (HEAD)
Frappe Framework: v13.26.1 (HEAD)

### Installation method

FrappeCloud

**Comment by ankush** [comment]
Did you click on this update button? You probably saved it and hence it is appearing as if update went through. 

<img width="934" alt="Screenshot 2022-05-05 at 5 27 07 PM" src="https://user-images.githubusercontent.com/9079960/166918339-c00d2986-fd7f-4e5c-b59c-42ced4808bd1.png">


will remove the misleading save button.
