### ISSUE TITLE
Utilities /  Video  / Youtube Video Bug

### ISSUE THREAD

**Issue by Rgottsch1** [frappe/erpnext#30928]
### Information about bug

Utilities /  Video  / Youtube Video works first time, then subsequent Plays show black screen.  I've created URL link using https://youtu.be/VzknNCl7kMc, and Youtube as provider.  if I reboot the server, it will play 1 time.  After that it shows a black screen. 

### Module

other

### Version

Installed Apps
ERPNext: v13.27.1 (version-13)

Frappe Framework: v13.27.0 (version-13)

### Installation method

easy-install

**Comment by ankush** [comment]
@Rgottsch1 do you have youtube API configured in "video settings"?

**Comment by ankush** [comment]
This is because it's using help utility which marks it as "watched" :) 

https://github.com/frappe/frappe/blob/cdb92f2dfa590ffd0067a4783d3e64fcf3e17206/frappe/public/js/frappe/widgets/onboarding_widget.js#L416-L426 


Anyway, non-preview watches should work as expected!

**Comment by Rgottsch1** [comment]
I've updated Frappe and ERPNext to below: and still see the issue?

ERPNext: v13.31.0 (version-13)

Erpnext Mfg: v0.1.0 (main)

Frappe Framework: v13.30.0 (version-13)
