### ISSUE TITLE
Transfer Qty not displaying on Production Order form: 

### ISSUE THREAD

**Issue by geetanjalishitole** [frappe/erpnext#3092]
1.If I transfer material for Production Order then that Transfered Qty   not displaying  on respective PO.
2.After completion of first step
If i do Stock Entry(Manufacturer) for same PO then both Manufactured Qty and Transfer Qty displaying on respective PO form.

**Comment by neilLasrado** [comment]
already fixed via pull request at https://github.com/frappe/erpnext/pull/3037
