### ISSUE TITLE
Sign up password updation Bug

### ISSUE THREAD

**Issue by algoexpert12** [frappe/erpnext#30933]
### Information about bug

I have clicked on verification button to sign up via email and got an error

### Module

other

### Version

latest

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
Set Up Your Account
Invalid Password: This is a very common password.
Hint: Include symbols, numbers and capital letters in the password

This error came in verification signup page https://frappecloud.com/erpnext/setup-account
```

**Comment by algoexpert12** [comment]
i got no way to update password

**Comment by dj12djdjs** [comment]
I believe the message is telling you to use a stronger password.

**Comment by ankush** [comment]
@NagariaHussain can you validate and close this? I think it's just a misunderstanding like @dj12djdjs pointed out. The form will still let you type new password after strength validation fails.

**Comment by NagariaHussain** [comment]
Just checked, it is not a bug. You can type in a stronger password and try again @algoexpert12.
