### ISSUE TITLE
Stock Entry(Manufacturer) with 'Multilevel BOM'  get submitted even its related  item( raw material) deleted from that stock entry.

### ISSUE THREAD

**Issue by geetanjalishitole** [frappe/erpnext#3093]
Steps 
1.Go to Stock ->Stock Entry ->+
2.Select purpose as 'Manufacturer'
3.Select Production Order
4.Check 'Use Multi Level BOM' checkbox.
5.Delete raw material  entries.
6.Submit

**Comment by rmehta** [comment]
This is the expected behavior, the item could be created from existing, reused material.
