### ISSUE TITLE
Accounts structure in an unknown language

### ISSUE THREAD

**Issue by vanzylpj** [frappe/erpnext#3097]
Hi!

I'm a new user and busy setting up the basics to explore the use of ERPNext on the free Entrepreneur option.

However, somewhere, the accounts structure decided to be set up in an unknown to me language... I chose the standard option and I know I have chosen English wherever a langauge selection was optional. So I'm a bit dumbstruck by why this is the case thus.

Can anyone please assist/advise?

Thanks!

**Comment by asr17** [comment]
same problem here

**Comment by rmehta** [comment]
this is now fixed. You might have to create a new account though.

**Comment by vanzylpj** [comment]
Thx!

Pieter

Wheel Spot
021 872 3597

wheelspot.co.za
