### ISSUE TITLE
Unknown column ‘utgst_account’ in ‘field list’

### ISSUE THREAD

**Issue by megha0071994** [frappe/erpnext#30972]
### Information about bug

I've clone erpnext 13 using 
bench get-app branch version-13 erpnext https://github.com/frappe/erpnext
this command, 13.29 is my current version.
But I've restore DB backup of erpnext 13.26, till then it throwing following error : 
pymysql.err.OperationalError: (1054, "Unknown column 'utgst_account' in 'field list'")

why I'm getting this error.
Please guide me

### Module

buying, selling

### Version

13.29

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
pymysql.err.OperationalError: (1054, “Unknown column ‘utgst_account’ in ‘field list’”)
```

**Comment by ankush** [comment]
Share full traceback. 

After restore you should migrate to latest version with `bench migrate`

**Comment by megha0071994** [comment]
Thank you.. It worked.
