### ISSUE TITLE
subscription invoice not created

### ISSUE THREAD

**Issue by megha0071994** [frappe/erpnext#30981]
### Information about bug

I've created subscription follow all the steps but I don't see generated invoice, I've checked "generated invoice at the beginning" still not getting any invoice. 

### Module

selling

### Version

v13.28.0

### Installation method

manual install

**Comment by dj12djdjs** [comment]
Hello @megha0071994,

Please take a look at https://docs.erpnext.com/docs/v13/user/manual/en/accounts/subscription

I've tested on my end, invoices are getting generated.

If it's still not working, please provide all the steps you've followed.

**Comment by enoy19** [comment]
I have the same issue. I have to press "Fetch Subscription Updates" on all subscriptions for it to create Invoices.
I couldn't find anything odd in the Error Log.

**Comment by enoy19** [comment]
> I have the same issue. I have to press "Fetch Subscription Updates" on all subscriptions for it to create Invoices. I couldn't find anything odd in the Error Log.

I worked around my problem by creating a scheduled `Server Script` (hourly):

```
subs = frappe.db.get_list("Subscription",
    filters={
        "status": ["not in",["Cancelled","Completed"]]
    },
    fields=["name"]
);
for sub in subs:
    subDoc = frappe.get_doc("Subscription", sub.name)
    subDoc.process()
```

**Comment by megha0071994** [comment]
I have checked all the settings and follow the following link:
https://docs.erpnext.com/docs/v12/user/manual/en/accounts/subscription

**Comment by deepeshgarg007** [comment]
@megha0071994 You are looking at version 12 docs, please check the latest version documentation
