### ISSUE TITLE
ERPNext V5 TableRow Css Issue on Firefox

### ISSUE THREAD

**Issue by vitridex** [frappe/erpnext#3098]
Hi Guys,

Just letting you know, getting a Table row layout CSS Issue on Firefox

See attachment.
![erpnext-tablerowcsserror-screenshot-3](https://cloud.githubusercontent.com/assets/7604770/7106008/e37f73e0-e176-11e4-816f-e57c3dd98e1e.png)

Hope this helps
Vee

**Comment by rmehta** [comment]
We are unable to replicate this. What OS are you using?

Can you do an **Inspect Element** on the item and see what is causing the extra padding / line height?

**Comment by vitridex** [comment]
Hello Remehta, Im using:
Linux 3.13
KDE 4.13.2
Firefox for Ubuntu 37.0.1

Ive attched below what i'm seeing here. So just letting you know i guess, and to add i've seen the same result on window 7 firefox version as well.

![erpnext-tablerowcsserror-screenshot-5](https://cloud.githubusercontent.com/assets/7604770/7135415/c6b17d52-e2e9-11e4-987c-aed0c663c6dc.png)

Thanks Rmehta
Vee

**Comment by veggydawson** [comment]
Hi 

I'm having CSS issues as well with Firefox 37.0.1 and Chrome 41.0.2272.118 under Linux (Solydxk).

This issue appears in both FIrefox and Chrome:
![image](https://cloud.githubusercontent.com/assets/12224661/7446732/e926aca0-f1d9-11e4-96ac-f26414fbab02.png)


...and this one appears in Firefox only
![image](https://cloud.githubusercontent.com/assets/12224661/7446763/a531f846-f1da-11e4-8d79-c32a2aba8ae8.png)


Thanks.

**Comment by vitridex** [comment]
Hi Rmehta, 

I believe the this bug has now been fix, i'm not seeing any issues in firefox or chrome anymore.

@veggydawson  do you agree?

Thanks
Vee

**Comment by vjFaLk** [comment]
Fixed
