### ISSUE TITLE
Where is the Financial Ratios report?

### ISSUE THREAD

**Issue by vivekck** [frappe/erpnext#3099]
For e.g., Working capital ratio, current ratio, etc.

**Comment by vivekck** [comment]
If this is not coming as part of v5, we should definitely prioritize, as this is quite critical to get a quick overview of the financial health.  Until it is done, I request that you consider to provide a easy workaround to generate this report.

**Comment by rmehta** [comment]
We have a long list of priorities, with a limited team. Will surely consider.

**Comment by vivekck** [comment]
Thank you Rishab.  Appreciate your prompt response. 

Vivek C
Eos Software Systems <http://www.eossys.com/>  |  +91-99019-22660

**Comment by deepeshgarg007** [comment]
@vivekck No immediate plans to do this, closing this as this has been stale for a while now

**Comment by rmehta** [comment]
This is a good feature addition for dashboard.
