### ISSUE TITLE
Cannot cancel Work Order if some Stock Entry were submitted 

### ISSUE THREAD

**Issue by guilmori** [frappe/erpnext#30993]
### Information about bug

1. Submit a new Work Order with operations and Transfer Material Against = Job Card
2. Go into first Job Card, make a Material Transfer
3. Submit Material Transfer

Now something happens and we need to cancel the whole Work Order.

So I tried:

1. Cancel the Material Transfer => success
2. Cancel the Work Order => error: Cannot delete or cancel because Job Card PO-JOB00001 is linked with Stock Entry MAT-STE-2022-00002

So I'm stuck, I cannot cancel the Work Order.

Any suggestions ?

### Module

manufacturing

### Version

v13.27.0

### Installation method

manual install

**Comment by guilmori** [comment]
Hello? Is there anybody here ?

**Comment by guilmori** [comment]
Bump

**Comment by Nihantra-Patel** [comment]
If there is a link, then you have to cancel; without that, there is no option.

**We no longer provide support for version 13 or older.**

Kindly upgrade to version 14 or 15.

Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!
