### ISSUE TITLE
POS return invoice against unpaid invoice

### ISSUE THREAD

**Issue by MahmoudRizk** [frappe/erpnext#31037]
### Information about bug

1. Create POS opening entry.
2. Create Unpaid POS Invoice.
3. Create POS closing entry.

It will create unpaid pos sales invoice as expected. "No Problem"

![1](https://user-images.githubusercontent.com/10531092/168596859-ea4a26b2-12cc-4f49-b736-561dbdd34492.png)
![2](https://user-images.githubusercontent.com/10531092/168596892-7f930f36-1dbd-4579-9d66-fc1137fa0377.png)

Customer's Unpaid amount will be increased.

![test_cusotmer_1](https://user-images.githubusercontent.com/10531092/168597194-f7b0e4ba-c0d0-4532-93e3-1e3500e2280f.png)

5. Create POS opening entry.
6. Create Return POS invoice against the Unpaid consolidated POS invoice.
7. Create POS closing entry

Will create a return & paid pos sales invoice against the unpaid pos sales invoice, which is not a correct behavior. payments for the return pos sales invoice shall not exceed the payments for the returned against sales invoice.

![consolidated_unpaid_pos_invoice](https://user-images.githubusercontent.com/10531092/168597004-4c8c3bc2-080b-4cc0-920a-2ec473a104a8.png)

![consolidated_return_pos_invoice](https://user-images.githubusercontent.com/10531092/168597009-1d10aecc-c99d-4e42-ae05-c2d58499af56.png)

From the company's perspective, a paid return invoice has been made against unpaid invoice which means a paid transaction for the customer has been made against nothing.
Customer's Unpaid amount was not changed.
	

### Module

accounts

### Version

Frappe version: 13.26.0
ERPNext version: 13.26.0

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Not a blocker bug.
```

**Comment by ssiyad** [comment]
@MahmoudRizk 

> Create Unpaid POS Invoice.

Can you please provide exact steps? It is not possible to create unpaid POS invoices iirc
