### ISSUE TITLE
[V5] Stuck on loading in Project page

### ISSUE THREAD

**Issue by Nayar** [frappe/erpnext#3103]
Problem:

When I go on projects, the page remains on loading like the screenshot.

![snapshot7](https://cloud.githubusercontent.com/assets/454815/7135316/80c95ec8-e2b6-11e4-937e-72a3f31dbd7e.png)

It happened on my main browser and also provate browsing. I am using free hosting by ERPNext itself.
My version:
ERPNext: v5.0.0-beta
Frappe Framework: v5.0.0-beta

**Comment by rmehta** [comment]
1. Update the latest version 5/
2. Share error trace from your js console

**Comment by Nayar** [comment]
1. It's self hosted. Can't do that.
2. Here you go
```
Uncaught TypeError: Cannot read property 'read' of undefineddesk.min.js:599 $.extend.get_match_ruleslist.min.js:85 frappe.views.DocListView.frappe.ui.Listing.extend.show_match_helplist.min.js:81 frappe.views.DocListView.frappe.ui.Listing.extend.setuplist.min.js:81 frappe.views.DocListView.frappe.ui.Listing.extend.initdesk.min.js:77 Classlist.min.js:79 (anonymous function)desk.min.js:521 frappe.call.callbackdesk.min.js:165 statusCode.200desk.min.js:169 (anonymous function)jquery.min.js:2 n.Callbacks.jjquery.min.js:2 n.Callbacks.k.fireWithjquery.min.js:4 xjquery.min.js:4 n.ajaxTransport.k.cors.a.crossDomain.send.b
```
![snapshot7](https://cloud.githubusercontent.com/assets/454815/7135521/9d900ed8-e2b8-11e4-9d04-f84db1ddbf6d.png)

**Comment by rmehta** [comment]
Fixed. Thanks for reporting.
