### ISSUE TITLE
Linking Sales Order with Item

### ISSUE THREAD

**Issue by mbauskar** [frappe/erpnext#3104]
Hi Guys,
I've noticed that the ‘Linked with’ functionality for items shows transactions and records that an item is linked to.

I have created one item and created the sales order for the same. But when i click the Linked With for that item the Sales Order transaction does not display

e.g. The item 0000663107: Mama Heidi has been ordered, purchased and received, however when I click on ‘Linked with’ the sales order transaction does not display.

I am using Frappe Version 4

**Comment by rmehta** [comment]
This is fixed in v5
