### ISSUE TITLE
Item Tax Templates not getting recalculated after being set in Sales Order

### ISSUE THREAD

**Issue by Namekkural** [frappe/erpnext#31051]
### Information about bug

We use Item Tax Templates to calculate our taxes on Sales Orders. When a different Item Tax Template is chosen in the items section of the sales order, the taxes don't get updated in the taxes section.

Interestingly, after saving, the taxes are still wrong, but if I change anything to be able to hit save again, the taxes WILL be calculated correctly.

I think the order in which the taxes are calculated must be wrong in some way.
A quick workaround is to trigger the tax calculation before validate in a server script:

```
doc.calculate_taxes_and_totals()
```

### Module

accounts, selling

### Version

Frappe v13.29.0 / v14.0.0-beta.3
ERPNext v13.29.0 / v13.30.0 / v14.0.0-beta.4

Manual install + Docker install (tested both)

### Installation method

manual install

**Comment by deepeshgarg007** [comment]
@Namekkural Please add steps to replicate the issue and then reopen it, there is not much info to investigate right now.
