### ISSUE TITLE
Login for Local Area Networks

### ISSUE THREAD

**Issue by kariuki** [frappe/erpnext#3106]
Is would be great to be able to create user logins without necessarily having to connect to the Internet or an Outgoing Mail Server. This would work for small and medium sized businesses that do not have regular internet access.

**Comment by rmehta** [comment]
Plugging in https://erpnext.com/pricing/paid-feature-development

**Comment by vrms** [comment]
if you have a locally installed instance of ERPNext this is exactly what you have. 

Access to your ERPNext instance through local network (no internet involved). 
closing this issue therefore. If you mean anything else then this, please elaborate and we can reopen this issue
