### ISSUE TITLE
conversion factor issue

### ISSUE THREAD

**Issue by ankush** [frappe/erpnext#31063]
Hi. I've discovered a bug that is caused by the changes that were made in this commit. When creating a Sales Order from a Quotation (with a currency other than base), the variables cause the if statement to trigger the else block. Previously, this was not an issue however, with the new changes the exchange rate is set 1 instead of using the previously specified exchange rate or even at least the one specified in the Currency Exchange table.

_Originally posted by @Archais in https://github.com/frappe/erpnext/issues/30990#issuecomment-1129834011_

**Comment by Archais** [comment]
Hi @ankush. Thanks for looking into this, below is the change that I've made to both my testing and production instances and seems to be working (starting at [line 1044 in transaction.js](https://github.com/frappe/erpnext/blob/version-13/erpnext/public/js/controllers/transaction.js#L1044)):

		if(this.frm.doc.currency && this.frm.doc.currency !== company_currency) {
			if (!(this.frm.doc.__onload && this.frm.doc.__onload.ignore_price_list)) {
				this.get_exchange_rate(transaction_date, this.frm.doc.currency, company_currency,
					function(exchange_rate) {
						if(exchange_rate != me.frm.doc.conversion_rate) {
							me.set_margin_amount_based_on_currency(exchange_rate);
							me.set_actual_charges_based_on_currency(exchange_rate);
							me.frm.set_value("conversion_rate", exchange_rate);
						}
					});
			} else {
				this.conversion_rate();
			}
		} else {
			// company currency and doc currency is same
			// this will prevent unnecessary conversion rate triggers
			this.frm.set_value("conversion_rate", 1.0);
		}
