### ISSUE TITLE
Currency, Exchange rate & Bank A/C's

### ISSUE THREAD

**Issue by MrOmega** [frappe/erpnext#3109]
Please advice on the following issues,
USD is the default currency of the company.
AED is the default bank account currency for specific account.

How to record a transaction in AED and hence to verify account statement as it is.
In chart of accounts, that's fine to be converted to USD.

In case of changing the value of the exchange rate TODAY, Is it going to hit previously recorded transactions or only the future ones? Please clarify.

Please add "Account Currency" field in the account document.

**Comment by rmehta** [comment]
Dual currency accounts are coming in version 5.

https://github.com/frappe/erpnext/issues/1002
