### ISSUE TITLE
Daily Digest -  Daily Reminders with broken unsubscribe link

### ISSUE THREAD

**Issue by Namekkural** [frappe/erpnext#31095]
### Information about bug

Ever since setting up ERPNext for the first time I receive these daily emails with the subject "Daily Digest" and a big header "Daily Reminders" but no content.

The unsubscribe link is broken and I can not unsubscribe from it.
The Link "Unsubscribe from this Email Digest" links to http://%3C%21--unsubscribe%20url--%3E

I also don't know what kind of Digest this is, since it is not listed in "Email Digest List" in ERPNext.

### Module

other

### Version

Frappe v13.30.0
ERPNext v13.30.0

### Installation method

docker

**Comment by longGr** [comment]
I have the same error.

**Comment by j0rgan** [comment]
Same here...

**Comment by Namekkural** [comment]
I haven't gotten these emails lately, has this been fixed?

**Comment by Namekkural** [comment]
@longGr @j0rgan what versions are you on?

**Comment by j0rgan** [comment]
@Namekkural btw i am not using dockerized version like yourself. My versions: 
erpnext 13.30.0
frappe 13.29.1

**Comment by philippmeixner** [comment]
Just discovered that the "Daily Reminders" digest is called "Scheduler Errors". Disable that, and the empty mails are gone.

**Comment by Namekkural** [comment]
Thanks Philipp! For me the unsubscribe link worked again some day. I think probably a bug fix in some update.
