### ISSUE TITLE
View Settings

### ISSUE THREAD

**Issue by sunilsmspl** [frappe/erpnext#31106]
### Information about bug

In custom doctype in view setting for Print Format we are not getting drop down to select our custom print format as default.Every time we print manual selection is required.
pl look into

### Module

other

### Version

13.21

### Relevant log output / Stack trace / Full Error Message.

```shell
nil
```

**Comment by dj12djdjs** [comment]
The option to select default print format is not located in doctype view settings. It is located on all print formats for that doctype. If you wish to set a default, open the print format you want to be default and click "Set as Default"

![image](https://user-images.githubusercontent.com/29856401/170836067-bdbb704d-a0bf-49e0-bd86-81cdac677586.png)

**Comment by nihantra** [comment]
Hi @sunilsmspl,

Adding @dj12djdjs answer, Otherwise, you can default print format set in customize form in view setting section.

![image](https://user-images.githubusercontent.com/99652762/170931378-117b5343-5176-4e93-b1a0-7d4aed643508.png)

Thank You!
