### ISSUE TITLE
Payment Request E-Mail is only sent when payment gateway is set

### ISSUE THREAD

**Issue by enoy19** [frappe/erpnext#31109]
### Information about bug

In `erpnext/accounts/doctype/payment_request/payment_request.py:93` the following line resolves to `None`, if there is no `payment_gateway` defined in the document:
`		send_mail = self.payment_gateway_validation() if self.payment_gateway else None`

The `payment_gateway_validation` is not run and the `self.send_email()` function is never called.

I do not use payment gateways for requesting Payments. I always need to Press "Resend Payment Email".

### Module

accounts

### Version

ERPNext: v13.30.0
Frappe Framework: v13.29.2

### Installation method

docker

**Comment by enoy19** [comment]
Is there any progress here?
I may implement this fix myself, but I'd like to know if that behavior is wanted.

**Comment by deepeshgarg007** [comment]
@enoy19 What would the payment request email contain in the email content if not the payment link which can only be done if the payment gateway is set up, please add your comments and reopen if needed.

**Comment by enoy19** [comment]
Hi @deepeshgarg007, thank you very much for your time and answer.
You're correct, it doesn't make sense to request a payment without a payment gateway.

I guess I use the payment requests not as intended:

For me, payment requests are a convenient and dedicated way to track to whom I've sent a sales invoice email.
Thanks to the E-Mail templates, I just need to create the request and submit it.
I do not use payment gateways, I only send invoices. Thats the content of my payment request mail.

Is there a different way to realize this usecase? What do other users do?
Do they just send an email in the Sales Invoice Document?

Thank you @deepeshgarg007 and @frappe for this awesome ERP!
