### ISSUE TITLE
How to consider public port?

### ISSUE THREAD

**Issue by MrOmega** [frappe/erpnext#3111]
The system is enabled through the router as virtual server having public port (say 34180) and hence to be forwarded to private port number 80.

The provided links by email for users signup, backups download, etc. does not point to the public port and hence access will be blocked by the router.

Please add PORT field to be configured through the system and hence to be considered while emailing links.

**Comment by rmehta** [comment]
https://erpnext.com/pricing/paid-feature-development ?

**Comment by rmehta** [comment]
You can set `host_name` property in `site_config.json` with port number
