### ISSUE TITLE
Packing Slip from Delivery Note

### ISSUE THREAD

**Issue by Priyanka-IAS** [frappe/erpnext#3113]
Hi,

While we have been using ERPNext regularly for over a year now, we are unable to use the Packing Slips yet. The reason being that we require the following fields to also be available in the PS.
1. Item Name
2. Item Description
3. Batch No
4. Quantity
5. Quantity UOM

Also, we use weight as our quantity in almost all our items and the Net Weight calculated in this case seems incorrect. Is there a way to fix this?

Is there a way wherein we can have some of our Custom fields added in Delivery Note also show up in the Packing Slip with values.

Thanks for your help

**Comment by rmehta** [comment]
Added batch no and description in Packing Slip (that was easily do-able) in Version 5.
you might have to add a custom script to pull custom fields.
