### ISSUE TITLE
GSTR-1 shows duplicate company gstin in report filter

### ISSUE THREAD

**Issue by asoral** [frappe/erpnext#31147]
### Information about bug

def get_company_gstins(company):
	address = frappe.qb.DocType("Address")
	links = frappe.qb.DocType("Dynamic Link")

	addresses = (
		frappe.qb.from_(address)
		.inner_join(links)
		.on(address.name == links.parent)
		.select(address.gstin)
		.where(links.link_doctype == "Company")
		.where(links.link_name == company)
		.run(as_dict=1)
	)

	address_list = [""] + [d.gstin for d in addresses]

	return **address_list**
in the above code function should return in set i.e so only distinct value will be allowed

### Module

regional

### Version

frappe-13
erpnext-13

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
there is no error. Only code change is required
```

**Comment by nihantra** [comment]
Hi @asoral,

I have tested in erpnext hosting and also checked in the localhost system.
and does not duplicate appear in the company gstin filter.

so update/migrate your version. otherwise, check your code.
```
Version:
ERPNext: v13.28.0 (HEAD)
Frappe Framework: v13.28.0 (HEAD)
```

Thank You!

**Comment by sjain17** [comment]
When you have multiple addresses in the same state with the same GSTIN then it shows multiple GSTIN in the dropdown of the GSTR -1 report.

For example - I have a GST number of Maharashtra and billing is done from Mumbai and Pune then while seeing GSTR-1 it shows the dropdown of GST number twice.

**Comment by deepeshgarg007** [comment]
@asoral This issue should be resolved now, please check again
