### ISSUE TITLE
Permissions Manager Needs to be MORE logical

### ISSUE THREAD

**Issue by adityaduggal** [frappe/erpnext#3116]
I would like to give a scenario for permissions which is not happening currently.

Suppose we have certain Sales People who are assigned customers. So if I want that sales person is only to see customer ABC and XYZ then I can add a custom field in the customer which can be linked to the sales person's user id.

Now this works fine with the masters but when I want the same sales person to see the transaction of these customers then I would have to add these customers ABC and XYZ to sales person's user id but then this process is very cumbersome if the number of customers go to something like 50 or 100.

So my suggestion is that if we give a user the rights for transaction like Sales Order and then if the Sales person does not have the right to see customer "Webnotes" then why should that user have the right to see the Webnotes' Sales Orders.

I think this type of scenario is currently available in the reports module but it is not fully implemented in the Transactions front.

Ref: https://discuss.frappe.io/t/permission-in-erpnext-version-4-and-future/5267

**Comment by adityaduggal** [comment]
@rmehta Please make this as a PAID development and let me know the pricing.

**Comment by rmehta** [comment]
Aditya, sure, when I am back from vacation :) @anandpdoshi can you tag as paid development.

**Comment by rmehta** [comment]
@adityaduggal does share work for you?

**Comment by adityaduggal** [comment]
Please check the following code in my app:

1. https://github.com/adityaduggal/rigpl-erpnext/blob/master/rigpl_erpnext/rigpl_erpnext/validations/customer.py

1. https://github.com/adityaduggal/rigpl-erpnext/blob/master/rigpl_erpnext/rigpl_erpnext/validations/lead.py

Now in Item 1, when we change the Sales person in the sales_team table then the Customer is added to the permission of the user id of the sales person. It is also doing the same with Sales Partner. We have added a USER ID field in the SALES partner as well (Custom field)

Now how we have linked the Sales Person to the user id is a long thing.....Sales person is linked to the Employee and Employee is linked to the user id.

Also when we change the lead owner in LEAD then the system would DELETE the lead from the user permission of the old user and ADD it to the user permission of the existing USER.

This has made our JOB extremely easy just one small thing is LEFT which @anandpdoshi promised would be delivered, which according to me is a Security Flaw the issue #3194 

With #3194 fixed the requirement for this feature does not remain URGENT.

**Comment by vrms** [comment]
is this still an issue? Looks to me it could be closed

**Comment by adityaduggal** [comment]
Well can you do the following:
1. Create a Sales person and assign the Sales person a customer in the Sales team not the todo assign.
1. Now if the sales person has a userid or an employee id and if the userid of the sales person is limited to see transactions of that customer only, then in current system we need to manually add the user permission in the userid of the sales person which is not intuitive.
1. But in the above mentioned code which I have to give a pull request for we have added an employee field in the sales person and this field would link the sales person to that particular userid and the moment you add a sales person in the customer master which is linked to a userid the system would automatically add a user permission to the userid which seems more intuitive.
