### ISSUE TITLE
Stock balance - Queued

### ISSUE THREAD

**Issue by Audrey1010** [frappe/erpnext#31172]
### Information about bug

After the updatin the cpu in google cloud platform the stock balance response is too long too wait until the stock balance report was queued.

### Module

stock

### Version

ERPNext: v13.14.1 (HEAD)
Frappe Framework: v13.14.1 (HEAD)

**Comment by dj12djdjs** [comment]
Can you provide more information, System Spec, response time, how many items are generated in the report?

**Comment by Audrey1010** [comment]
ERPFrappe
ERPNext: v13.14.1 (HEAD)
Frappe Framework: v13.14.1 (HEAD)

Then only 1 item planning to generate sir. And this saturday on 2022-05-28 we upgrade cpu in then started to **QUEUED** because we use google cloud platform.



thanks

**Comment by ankush** [comment]
Most likely background workers aren't working, tried restarting `bench restart`?

**Comment by Audrey1010** [comment]
Hi. Sir Ankush, yes I already tried for this command **sudo /opt/bitnami/ctlscript.sh restart**

**Comment by Audrey1010** [comment]
Hello sir. please help me to resolve.

thanks

**Comment by dj12djdjs** [comment]
@Audrey1010 what is the output of `bench doctor` are there any background workers running ?

**Comment by Audrey1010** [comment]
Hi @dj12djdjs I was not yet do the bench doctor, how can I figure that? inside of ssh/cloud google?
Because I was newbie here.

Thanks

**Comment by dj12djdjs** [comment]
@Audrey1010 Yes you must be logged on to your server in your bench directory. Then run `bench doctor`

**Comment by dj12djdjs** [comment]
Closing, I cannot reproduce this and lack of response.
