### ISSUE TITLE
Page notification-settings not found

### ISSUE THREAD

**Issue by SalahAddinAbdo** [frappe/erpnext#31173]
### Information about bug

Page notification-settings not found
I can not access the notification settings page again? I was able to get it in the past but I do not know what is the problem now? I appreciate your help.

### Module

other

### Version

ERPNext: v13.30.0 (HEAD)
Frappe Framework: v13.29.2 (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
Page notification-settings not found
I can not access the notification settings page again? I was able to get it in the past but I do not know what is the problem now? I appreciate your help.
```

**Comment by dj12djdjs** [comment]
I'm able to access it via this route: /app/notification-settings

Also it is available by Desk
![image](https://user-images.githubusercontent.com/29856401/170906717-b514cf94-d3ca-413e-98b8-4de0272b38ba.png)


Although I was not able to access it from the Awesome bar

**Comment by ankush** [comment]
It also accessible from notification pane's "gear" icon.

**Comment by SalahAddinAbdo** [comment]
Dear, I did not find this page at all. When I click on notification pane's "gear" icon, the below is appear.

![Screenshot 2022-06-09 193741](https://user-images.githubusercontent.com/96741326/172899285-5aaaf62f-28b9-4725-84ef-0ab71bcf8c2a.png)
