### ISSUE TITLE
Pricing change after change the date of doctype

### ISSUE THREAD

**Issue by kanedai** [frappe/erpnext#31179]
### Information about bug

1, New Quotation.
2, Use foreign currency price list.
3, Insert some items, (some items will fetch from the price list)
4, Change price for some items.
5, Save.
(So far everything is fine)
6, Change date of the quotation,  the price is changed. It seems it will refetch the price from the price list and overwrite the unit price of the item.

### Module

accounts, buying, selling

### Version

Frappe version- 13.30.0
ERPNext Verion-  13.31.1

**Comment by dj12djdjs** [comment]
Possibly related to: https://github.com/frappe/erpnext/issues/29840

**Comment by deepeshgarg007** [comment]
@kanedai @dj12djdjs this issue was resolved via https://github.com/frappe/erpnext/pull/30990
