### ISSUE TITLE
letter head is not visible in pdf when I'm sending purchase order in email.

### ISSUE THREAD

**Issue by megha0071994** [frappe/erpnext#31207]
### Information about bug

letter head is not visible in pdf when I'm sending purchase order in email, while I've done all the settings, what show I do?
It working previously, but when I install new bench and site on server, it is not working. 

### Module

buying, selling

### Version

bench version : 5.8.1
ERPNext: v13.28.0
Frappe Framework: v13.28.0

### Installation method

manual install

**Comment by dj12djdjs** [comment]
I've had this happen when using multitenant dns. Here was my setup.

I had my primary site created with `bench new-site erp.SITE_NAME.com`

Then I had two addon domains pointing to the main site
`siteA.com` -> `erp.SITE_NAME.com`
`siteB.com` -> `erp.SITE_NAME.com`

We wanted to expire the `erp` subdomain extension but many people had this bookmarked.
So we setup a 301 redirect from `erp.SITE_NAME.com` -> `siteA.com`

When I did this PDF's (specifically the image letter head) would not be present at all. But only in Email. They where fine when generating PDF from the desk.

I had to remove the 301 redirect from `erp.SITE_NAME.COM` -> `siteA.com` removing this solved the issue.

**Comment by megha0071994** [comment]
I've not setup multitenant DNS.

**Comment by dj12djdjs** [comment]
Is your letter head based on an image or is it generated through HTML ?

**Comment by megha0071994** [comment]
generated through HTML
```
<div style="text-align: right; margin-bottom: 10px;">
    <img alt="Test" src="https://sub-domain.domain.in/files/logo.png" style="height: 50px;" title="Test">
</div>
```

**Comment by dj12djdjs** [comment]
I have a feeling it's a problem with the image resource you're requesting. Can you test if you remove the image from your letter head. Just put something like "Hello World" then test the email. If the text will show up in the email?

Another thing you can try is make sure your site_config.json has a key `host_name` with a value of your host example 
`sub-domain.domain.in`

**Comment by megha0071994** [comment]
Both solution are not working ..

**Comment by dj12djdjs** [comment]
If the letter head isn't appearing with just some text on it. Possibly the print setting is configured to not display letter head.
Could you check?
![image](https://user-images.githubusercontent.com/29856401/171797755-e858e6cc-b079-4c5d-8f74-8940808d89de.png)

**Comment by dj12djdjs** [comment]
I'm on
Frappe Framework: v13.29.1 (version-13)
ERPNext: v13.30.0 (version-13)

and email pdf with letter head is working perfectly for me.

**Comment by megha0071994** [comment]
Sorry still not working, all the settings are same as your screenshot.

**Comment by dj12djdjs** [comment]
@megha0071994 I'm not sure what it could be. Letter heads are working perfectly fine in emails for me on 13.30.0

Most likely there is a problem somewhere else. It will take some debugging and troubleshooting to figure it out.

**Comment by megha0071994** [comment]
I'm on the version 13.29. How can I properly update ERPNext without any trouble, Please guide me complete steps.

**Comment by dj12djdjs** [comment]
@megha0071994 You can update by running `bench update` in your bench directory.

However, if the PDF's were generating correctly on the previous server, it's most likely a server configuration issue. 
It's nearly impossible to figure out the exact problem without having access to debug it.

**Comment by hashmaldives** [comment]
I was having the same issue. The issue resolved when i unchecked the "Repeat Header and Footer in PDF" checkbox in the print settings -> pdf settings section.
![Screenshot 2023-07-02 at 09-53-37 Print Settings](https://github.com/frappe/erpnext/assets/63248880/ef745a98-5982-44ca-8296-18287a171506)

**Comment by rtdany10** [comment]
Faced the same issue, it's because of the version of wkhtmltopdf.
Make sure you have patched qt version.
`wkhtmltopdf 0.12.6.1 (with patched qt)`

For Ubuntu 22:
```
wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-2/wkhtmltox_0.12.6.1-2.jammy_amd64.deb
sudo apt install -f ./wkhtmltox_0.12.6.1-2.jammy_amd64.deb
```
