### ISSUE TITLE
Trial Balance not considering Finance Book

### ISSUE THREAD

**Issue by sunhoww** [frappe/erpnext#31214]
### Information about bug

_Opening(Dr)_ and _Opening(Cr)_ columns aggregates all entries with or without _Finance Book_ when this filter is left blank. Otherwise when, this filter is set, the resulting values are as expected.

The discrepancy can be observed when this report is compared against **Report: Balance Sheet**.

### Module

accounts

### Version

ERPNext: v13.32.0
Frappe Framework: v13.31.0

### Installation method

docker

**Comment by mn3m-cs** [comment]
There's **Include Default Book Entries** checkbox, that may solve your problem
![image](https://user-images.githubusercontent.com/34791641/172002278-f7bf940a-9a5d-4196-aa6d-f5d408878510.png)
