### ISSUE TITLE
Clearning taxes makes order doc unusable

### ISSUE THREAD

**Issue by ankush** [frappe/erpnext#31213]
### Information about bug

1. Open sales order
2. Sales tax template is loaded by default (if not add it)
3. Clear tax table rows. 

Makes form almost completely irrecoverable broken. 

https://user-images.githubusercontent.com/9079960/171429374-f28624a2-a238-4851-a2bb-e9283e684bbb.mov

### Module

accounts

### Version

develop

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
TypeError: Cannot read properties of undefined (reading 'US ST 6% - WP')
    at Object.clear_doc (model.js:549:28)
    at grid_row.js:91:20
```

**Comment by ankush** [comment]
<img width="466" alt="Screenshot 2022-06-01 at 7 58 47 PM" src="https://user-images.githubusercontent.com/9079960/171429507-c62c7ce1-bdc8-4adf-87a6-e70110541444.png">


Most likely symptom, the tax table row has incorrect parent set for whatever reason.

**Comment by dj12djdjs** [comment]
I've experienced this as well. I thought it was some bug in frappe. Whenever developing on `develop` I save the document before clearing any child tables.

As long as the document is saved. It will clear just fine.

**Comment by ankush** [comment]
I am guessing this is specific to taxes since they are set by server side: https://github.com/frappe/erpnext/blob/720e8517aab617061a8c4a8315b16e44535d65fc/erpnext/public/js/controllers/transaction.js#L1702-L1713 


I think we should fix both

- desk should be resilient to this
- parent should be correctly set.

**Comment by ankush** [comment]
Okay, I think I got it 😄 This is caused by https://github.com/frappe/frappe/pull/15411 

@phot0n no good deed goes unpunished 😆
