### ISSUE TITLE
On Production Order ,Wrong  Description of  'Actual Operating Cost'  field.

### ISSUE THREAD

**Issue by geetanjalishitole** [frappe/erpnext#3123]
Eg.
Item=xyz
1.Create BOM with operations.
2.Create Production order for above item.
3.Submit  respective 'Time Log'  of above production order.
4.In Production Order  form, 
  Open 'Operation' datagrid , and check the description of 'Actual Operating Cost'  field
  It displaying as  'Hour Rate * Actual Operating Cost'
  But I think description should be as 'Minute Rate* Actual Operation Time'

**Comment by rmehta** [comment]
@neilLasrado Please check this and fix.
