### ISSUE TITLE
Quantity difference showing in batch wise balance history and actual

### ISSUE THREAD

**Issue by shivansh12** [frappe/erpnext#31279]
### Information about bug

Hi Team,

I am facing an unwanted scenario in which ;
case 1: When i took batch wise balance history balance qty is 772 for an item for a particular batch but while stock reconciliation the quantity is showing as 177.

and if i try to reconcile it with some quantity lets say 100 then the batch wise balance history report shows it 695 quantity for that particular batch…

I tried many possible ways but couldn’t find any solution…
please guide me ,that will be more helpful.

Thanks,

### Module

stock

### Version

13.5
13.5

### Installation method

easy-install

### Relevant log output / Stack trace / Full Error Message.

```shell
Batch reconciliation not happen as per requirement. please help in that
```

**Comment by dj12djdjs** [comment]
Hello @shivansh12 

I just wanted to check, have you referred to? https://docs.erpnext.com/docs/v13/user/manual/en/stock/stock-reconciliation#43-for-batch-items

I've tested for myself, it seems to be working correctly. Let's say we want to reconcile 60pc to 100pc
The batch # is `EXAMPLE`

1. Proof 60pc exists
![image](https://user-images.githubusercontent.com/29856401/172689912-2995d53a-ce33-4ec8-87dc-bff4502c5018.png)

2. Create Stock Reconciliation - Make sure Warehouse, Qty, and Batch No. Is Set
![image](https://user-images.githubusercontent.com/29856401/172690969-b41b4351-8f3a-47ff-a5a9-c9083ab95133.png)

Now you will see the qty has been reconciled to 100pc
![image](https://user-images.githubusercontent.com/29856401/172691192-4e560d3e-9317-4475-bd40-46c0b1eaf38f.png)

**Comment by shivansh12** [comment]
@dj12djdjs thankyou for your response ... but the current system i am working on having this scenario...

I am attaching you for the reference.

1. batch wise balance history for a particular batch:

![batch wise balance](https://user-images.githubusercontent.com/36820016/172882398-7d9825be-ad4d-498d-ac85-6891f0eba02b.PNG)

2.batch quantity showing 177 (it should show as per report)before reconciliation. and i reconcile it with 0

![st reco ref](https://user-images.githubusercontent.com/36820016/172882864-11d2d1e6-92f2-441c-b55c-18d8dd9d5445.PNG)



3. reconciliation with qty 0.


![on reco](https://user-images.githubusercontent.com/36820016/172883011-7ffb18f0-85fa-4d05-a9aa-a4d7728425e7.PNG)

4.After reconciliation batch wise report.
 
![after reco report](https://user-images.githubusercontent.com/36820016/172883104-dc5ce8c1-18ac-4787-9102-652fcb7477c0.PNG)


please help me with your solution or any suggestion will be appreciated.

**Comment by shivansh12** [comment]
> @dj12djdjs thankyou for your response ... but the current system i am working on having this scenario...
> 
> I am attaching you for the reference.
> 
>     1. batch wise balance history for a particular batch:
> 
> 
> ![batch wise balance](https://user-images.githubusercontent.com/36820016/172882398-7d9825be-ad4d-498d-ac85-6891f0eba02b.PNG)
> 
> 2.batch quantity showing 177 (it should show as per report)before reconciliation. and i reconcile it with 0
> 
> ![st reco ref](https://user-images.githubusercontent.com/36820016/172882864-11d2d1e6-92f2-441c-b55c-18d8dd9d5445.PNG)
> 
>     3. reconciliation with qty 0.
> 
> 
> ![on reco](https://user-images.githubusercontent.com/36820016/172883011-7ffb18f0-85fa-4d05-a9aa-a4d7728425e7.PNG)
> 
> 4.After reconciliation batch wise report.
> 
> ![after reco report](https://user-images.githubusercontent.com/36820016/172883104-dc5ce8c1-18ac-4787-9102-652fcb7477c0.PNG)
> 
> please help me with your solution or any suggestion will be appreciated.

@dj12djdjs @yadavyk  as i describe the above scenario if you ever face this type of scenario please guide me how to solve this.
please help me with your solution or any suggestion will be appreciated.

**Comment by dj12djdjs** [comment]
@shivansh12 Thank you for sharing, as of now I haven't tested and looked into it. Maybe someone who has more experience with batch qty can check this out?

**Comment by maveezmh** [comment]
Still the issue persists in ERP for both V13 and V14 any update on same??? unable to match the ledger with stock balance

**Comment by Nihantra-Patel** [comment]
**We no longer provide support for version 13 or older.**

Kindly upgrade to version 14 or 15, then refresh and check again because lots of bugs fixed in the new version.

Everything is working fine. No problems were encountered in the latest versions 14 and 15.


https://github.com/frappe/erpnext/assets/141945075/ae62ccc7-18db-402f-9ec7-69a781929cb4





Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!
