### ISSUE TITLE
Accounts Receivable & Payable Report

### ISSUE THREAD

**Issue by TwinkleDamania** [frappe/erpnext#31281]
There are two checkboxes available in the Accounts Receivable Report - **'Show Future Payments'** and **'Group by Customers'** but the totals for them don't appear. (check screenshot 2)

![image](https://user-images.githubusercontent.com/96407484/172581701-90f1590c-2ecc-481e-bfcc-bd1098f52dc9.png)

![image](https://user-images.githubusercontent.com/96407484/172582360-f9c3c575-25cb-4bfd-b01f-38f03cb6308e.png)

For Accounts Payable Report, the option of **'Show Future Payments'** is not available and the same is required for checking the balances.

**Comment by Solufyin** [comment]
Hi @TwinkleDamania,

As per your requirement, we added subtotal and total for account receivable report and also added a feature of future payments in account payable report.
See the Reference : #31286 

@deepeshgarg007, I hope it will be helpful for all ERPNext community.

Thanks.

**Comment by Solufyin** [comment]
Hi @TwinkleDamania,

Please close the issue because PR is Merged.

Thank You!
