### ISSUE TITLE
Documentation Link broken

### ISSUE THREAD

**Issue by frewper** [frappe/erpnext#31290]
### Information about bug

Under this article [link](https://docs.erpnext.com/docs/v13/user/manual/en/selling/sales-taxes-and-charges-template#21-sales-taxes-and-charges-table), the first link which says, Check out this article, to know the difference; the link is broken

### Module

other

### Version

ERPNext Version - 13

### Relevant log output / Stack trace / Full Error Message.

```shell
Error 404
```

**Comment by dj12djdjs** [comment]
This is also referenced at https://docs.erpnext.com/docs/v13/user/manual/en/accounts/articles#23-advanced
>[What Is The Differences Of Total And Valuation In Tax And Charges](https://docs.erpnext.com/docs/v13/user/manual/en/accounts/articles/what-is-the-differences-of-total-and-valuation-in-tax-and-charges)

**Comment by dj12djdjs** [comment]
Fixed in:

https://docs.erpnext.com/docs/v13/user/manual/en/selling/sales-taxes-and-charges-template/edit?wiki_page_patch=957cd53223
https://docs.erpnext.com/docs/v13/user/manual/en/accounts/articles/edit?wiki_page_patch=1c9770ec56
