### ISSUE TITLE
Company specific price list

### ISSUE THREAD

**Issue by vikramnarayan** [frappe/erpnext#3129]
Hi,

Currently we find that the price list is not company specific. Could you look at enabling company field in price list. This will help especially SMEs as most operate as sister firms and it will help so that pricing in one company is clearly separated from another so that users dont make a mistake while entering.

Thanks,
Vikram

**Comment by umairsy** [comment]
Hello,

Please add a custom link field of Company in the Price List. Also, you can have this value fetched in Item Price if in the Item Price custom field is added on these lines.

https://frappe.github.io/frappe/user/en/guides/app-development/fetch-custom-field-value-from-master-to-all-related-transactions.html
