### ISSUE TITLE
An expiry date field in Notes menu

### ISSUE THREAD

**Issue by vikramnarayan** [frappe/erpnext#3130]
HI,

We find the Notes menu useful to upload and store all the registration and other manufacturing related documents. However since most of these are licenses etc, they come with expiry date. Can you look at adding an expiry date field so that on that particular date or say 2/3 days before the user get intimated that this is expiring shortly. This will help take the functionality of the notes menu greatly.

Thanks,
Vikram

**Comment by rmehta** [comment]
You can add a Custom Field

https://manual.erpnext.com/customize-erpnext/custom-field
