### ISSUE TITLE
Page notification-settings not found

### ISSUE THREAD

**Issue by SalahAddinAbdo** [frappe/erpnext#31309]
### Information about bug

This is related to  issues #31173,

I did not find this page at all. When I click on notification pane's "gear" icon, the below is appear.

![Screenshot 2022-06-09 193741](https://user-images.githubusercontent.com/96741326/172901538-eb6e87b3-e8c8-4298-9861-b540b7c6ce7d.png)

On the other hand, from doctype gate when I click on **"Go to notification list"** it is also not found. You can see that below
![Screenshot 2022-06-09 195234](https://user-images.githubusercontent.com/96741326/172902261-2e539438-e6c5-46e3-9852-0348313f9275.png)

### Module

other

### Version

ERPNext: v13.30.0 (HEAD)
Frappe Framework: v13.29.2 (HEAD)

### Installation method

FrappeCloud

**Comment by nihantra** [comment]
Hi @SalahAddinAbdo,

I have also found an issue in this version so please update your version.
It's will resolve your issue.

Thank You!

**Comment by SalahAddinAbdo** [comment]
Many thanks @nihantra,

I have update my version as your recommendation. I found the notification-settings page now.

Thank you again
