### ISSUE TITLE
Currency data align to right in the print format

### ISSUE THREAD

**Issue by MujtabaMohsin** [frappe/erpnext#31328]
### Information about bug

Hello, I face a common issue in the print format (Format Builder) when I try to print the document and it has currency or a number data. As you see in the photo the data align to the right. This might be due to the currency. 

![oz__659](https://user-images.githubusercontent.com/64940728/173183389-98cc4f0e-b7be-4ff2-aa28-6d5e8b2f35e5.png)

### Module

other

### Version

ERPNext: v13.29.0 (HEAD)
Frappe Framework: v13.29.0 (HEAD)

### Installation method

FrappeCloud

**Comment by dj12djdjs** [comment]
Hello @MujtabaMohsin 

You can create a custom print format, then left align the values you want. See attached GIF for example.
![change-currency-align](https://user-images.githubusercontent.com/29856401/173198752-63ffa583-9536-4074-bbb4-1ccc45743d51.gif)

**Comment by dj12djdjs** [comment]
The above GIF should solve this.
