### ISSUE TITLE
Guidance Next Button unresponsive

### ISSUE THREAD

**Issue by supersnapp** [frappe/erpnext#31329]
### Information about bug

Very simply in 14 the Next button is not working when the guidance is activated. 
![Locked_Walk_Through_Screen_Shot](https://user-images.githubusercontent.com/37027367/173202131-f6498b71-70c9-4fcd-abbd-541427550001.png)

### Module

other

### Version

This is for version 14.

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
None
```

**Comment by dj12djdjs** [comment]
Hi @supersnapp,

This seems to be working fine for me. Can you check the browser console for any errors when you click the "Next" button?

**Comment by supersnapp** [comment]
Thanks.
I just did that. Here is what I got.

Deprecation warning: value provided is not in a recognized RFC2822 or ISO
format. moment construction falls back to js Date(), which is not reliable
across all browsers and versions. Non RFC2822/ISO date formats are
discouraged and will be removed in an upcoming major release. Please refer
to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments:
[0] _isAMomentObject: true, _isUTC: true, _useUTC: true, _l: undefined, _i:
undefined, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (
https://brightworkresearch.frappe.cloud/assets/frappe/dist/js/libs.bundle.F66AV522.js:7:3
)
    at Nt (
https://brightworkresearch.frappe.cloud/assets/frappe/dist/js/libs.bundle.F66AV522.js:7:25540
)
    at vn (
https://brightworkresearch.frappe.cloud/assets/frappe/dist/js/libs.bundle.F66AV522.js:7:27820
)
    at gr (
https://brightworkresearch.frappe.cloud/assets/frappe/dist/js/libs.bundle.F66AV522.js:7:27687
)
    at Pn (
https://brightworkresearch.frappe.cloud/assets/frappe/dist/js/libs.bundle.F66AV522.js:7:27406
)
    at yr (
https://brightworkresearch.frappe.cloud/assets/frappe/dist/js/libs.bundle.F66AV522.js:7:28155
)
    at L (
https://brightworkresearch.frappe.cloud/assets/frappe/dist/js/libs.bundle.F66AV522.js:4:110935
)
    at Function.F [as tz] (
https://brightworkresearch.frappe.cloud/assets/frappe/dist/js/libs.bundle.F66AV522.js:7:57400
)
    at Object.convert_to_user_tz (
https://brightworkresearch.frappe.cloud/assets/frappe/dist/js/desk.bundle.KZFASDAC.js:789:442
)
    at Hl (
https://brightworkresearch.frappe.cloud/assets/frappe/dist/js/desk.bundle.KZFASDAC.js:783:4380
)

**Comment by dj12djdjs** [comment]
This is only reproducible on frappe cloud. Manual installation this doesn't occur. I've checked the diff between beta 3 and develop. Didn't see anything that might have fixed this.

**Comment by dj12djdjs** [comment]
Interestingly, it works via the console, but not by DOM click
![driver](https://user-images.githubusercontent.com/29856401/173206738-05c26999-1170-4d52-901d-0f763e3b488a.gif)
.

**Comment by supersnapp** [comment]
Ok. Is there a solution? Is there something I can do?

**Comment by dj12djdjs** [comment]
@supersnapp I've not been able to test this, but I think updating to Beta 4 might solve the issue.

You can ask Frappe Cloud team to update, or create a private bench and select the exact version you want to install.
https://frappecloud.com/docs/creating_a_new_bench

**Comment by supersnapp** [comment]
Ok  great. What is the email I should use to contact the Frappe Cloud team?

**Comment by dj12djdjs** [comment]
@supersnapp When you're logged into Frappe Cloud, at the top right there is "Support" from there just create a ticket.

Most likely they will just give a time frame when it will be updated. Once it's updated we can see if it's fixed. (For some reason I'm unable to install the betas on my local bench 🤷)

**Comment by supersnapp** [comment]
Ok, will do. Thanks.

**Comment by dj12djdjs** [comment]
This is working on frappe cloud nightly build. So once frappe updates the beta it will work.

**Comment by supersnapp** [comment]
Can I get a password reset for ***@***.***? The password reset
through the web is not working for me as no email arrives. I checked
the spam folder.

**Comment by dj12djdjs** [comment]
@supersnapp you can login as administrator from frappe cloud. Then change your password from User DocType.

![Screenshot_20220617-201432](https://user-images.githubusercontent.com/29856401/174414547-be88e87a-b3d0-443c-91c6-e5f2a38336a0.png)

**Comment by supersnapp** [comment]
Where am I logging in? What is @supersnapp? Thank link goes to GitHub.

**Comment by supersnapp** [comment]
I never received a response to my last question. The password reset does
not work. I do not know how to get in as my password is not working. And I
do not understand the instructions of where I can log in at @supersnapp
<https://github.com/supersnapp>.

**Comment by dj12djdjs** [comment]
@supersnapp is your GitHub username. I just add it when replying. I don't understand what you're trying to login to? If it's your ERPNext site and you haven't setup email yet. Just login to Frappe Cloud, from there you can open your site as Administrator user, then change the password to your user.

**Comment by supersnapp** [comment]
Ok, thanks.

**Comment by supersnapp** [comment]
Ok, it was the frappe URL versus brightwork URL confusion on my part.
