### ISSUE TITLE
Server Error:pymysql.err.ProgrammingError: ('DocType', 'Whatsapp Notification')

### ISSUE THREAD

**Issue by Atul1413** [frappe/erpnext#31340]
### Information about bug

Dear Team,
I installed WhatsApp Notification on our site a few days ago for free through the marketplace.
I recently received an email with the subject [FC Marketplace]. Because WhatsApp Integration is a paid app, I have removed it from our website. But now I’m getting an error message that says Server Error ** pymysql.err. (‘DocType’, ‘WhatsApp Notification’)** Programming Error I attempted to remove it from doctype but was unsuccessful.
please help us to resolve the issue.
![Screenshot 2022-06-13 at 11-22-13 Selling](https://user-images.githubusercontent.com/11453397/173340491-5cd5a172-9c09-4984-8ec6-19eb2c7330e2.png)

### Module

selling, integrations

### Version

frappe/frappe:version-13 v(13.32.0)
frappe/erpnext:version-13 v(13.30.)

	"erpnext": "13.33.0",
	"erpnext_support": "0.0.3",
	"frappe": "13.32.0",
	"posawesome": "3.3.0",
	"whatsapp_integration": "0.0.1"

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/desk/form/load.py", line 41, in getdoc
    run_onload(doc)
  File "apps/frappe/frappe/desk/form/load.py", line 330, in run_onload
    doc.run_method("onload")
  File "apps/frappe/frappe/model/document.py", line 941, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1260, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1244, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "apps/whatsapp_integration/whatsapp_integration/whatsapp_integration/doctype/whatsapp_notification/whatsapp_notification.py", line 117, in run_whatsapp_notifications
    alerts = frappe.get_all('Whatsapp Notification', fields=['name', 'event'],filters={'enabled': 1, 'doctype_c': doc.doctype})
  File "apps/frappe/frappe/__init__.py", line 1732, in get_all
```

**Comment by nihantra** [comment]
Hi @Atul1413,

Please migrate your site and then check it.

![image](https://user-images.githubusercontent.com/99652762/173346793-442fdf2b-e10a-4c00-9f47-4a0c45b0d523.png)

Thank You!

**Comment by Atul1413** [comment]
@nihantra ,
thank you so much and support. it's worked fro me.
Thanks Again..!
Regards,
Atul S
