### ISSUE TITLE
Random string for warehouse naming if user include company abbr when inserting new warehouse

### ISSUE THREAD

**Issue by koplingganda** [frappe/erpnext#31346]
### Information about bug

Hi guys, 

First, I want to thank all of you for this framework and ERP software we can use. 

In this opportunity, I want to report a bug when inserting a new warehouse in ERPNext. It occurs when I insert the company abbreviation in the New Warehouse Name field. 

For example, TCMB is the company abbreviation. When I insert 'TEST' in the New Warehouse Name field, it is fine and the warehouse naming is normal. But, if I insert 'TEST - TCMB' in the New Warehouse Name field, warehouse naming becomes a random string

- This is the case when I insert 'TEST - TCMB'

![image](https://user-images.githubusercontent.com/48271907/173486341-9ac9bef2-4839-4688-8941-6d02f8f7d10c.png)
![image](https://user-images.githubusercontent.com/48271907/173486442-ba416aff-dad9-45da-afea-687885ef6493.png)
![image](https://user-images.githubusercontent.com/48271907/173486483-54a5d6ce-0d84-4a74-a385-918f8ed75f6a.png)

- This is the case when I insert 'TEST'
![image](https://user-images.githubusercontent.com/48271907/173486665-d88cfa3c-7432-470d-b327-79d2c864ecf7.png)
![image](https://user-images.githubusercontent.com/48271907/173486690-6b58341d-7dbe-41ed-9bc9-df50384cb19f.png)
![image](https://user-images.githubusercontent.com/48271907/173486708-2bf1c35c-48fa-4a20-b076-5990c3483b39.png)

I suspect a bug in autoname controller in warehouse.py, if the user inputs the warehouse name with a company abbreviation it will escape the naming logic, and the warehouse name becomes a random string. 

I would like to create a pull request to fix this bug. Thank you for this opportunity.

### Module

stock

### Version

ERPNext: v12.30.1
Frappe: v12.27.0
![image](https://user-images.githubusercontent.com/48271907/173486850-c9a8c707-a989-480b-ae18-9945526cb2d7.png)

### Installation method

docker

**Comment by nihantra** [comment]
Hi @koplingganda,

Please check it.
https://github.com/frappe/erpnext/pull/31348#issuecomment-1154758168

Thank You!

**Comment by koplingganda** [comment]
Hi @nihantra 

Thank you!
