### ISSUE TITLE
Shortcut filter can't save more than 2 filters?

### ISSUE THREAD

**Issue by Hollowiman** [frappe/erpnext#31366]
### Information about bug

If I try to add more than 2 filters to it, won't those be saved?
![image](https://user-images.githubusercontent.com/21259292/173777225-ff3052be-96f5-4e73-9177-f5d453495759.png)

### Module

other

### Version

Frappe Framework: v13.30.0 (version-13)
ERPNext: v13.31.1 (version-13)

### Installation method

manual install

**Comment by nihantra** [comment]
Hi @Hollowiman,

Yes, you can use it to add a number of filters.
Check the below image.
![image](https://user-images.githubusercontent.com/99652762/173782769-111259e1-4205-4abc-93bb-dabfcf4e9ed2.png)

![image](https://user-images.githubusercontent.com/99652762/173782920-15c556ba-6057-457a-aa09-ddf5f86769af.png)

Thank You!

**Comment by Hollowiman** [comment]
Is it related to Link To "Task"? Or version? I can't save more than 2 filters...

**Comment by Hollowiman** [comment]
Ok i can save more, but it save's really only 2...

**Comment by nihantra** [comment]
Hmm :thinking: 

I tested in Version:
`ERPNext: v13.33.0 (HEAD)`
`Frappe Framework: v13.32.0 (version-13)`

Please check the below video.


https://user-images.githubusercontent.com/99652762/173793491-55b0630c-83ec-4895-a19f-153b3994d8d3.mp4


Also, check in another doctype.

Thank You!

**Comment by Hollowiman** [comment]
Ok, I was making that shortcut filter wrong. I used 2 times Status filter, and that's not the way... I managed it with "Not In" parameter, and now i got it right.

Sorry and thanks.
