### ISSUE TITLE
Stock Indicator Error

### ISSUE THREAD

**Issue by mbauskar** [frappe/erpnext#3136]
Hi, 
We have 1 unit of Item available in stock but when i tried to create the sales order for the same item keeping the qty as 1, Then the Stock indicator shows Not In Stock.

I have debugged the code and found the solution for the same. Please change the line number 55 of item_grid.html from 
if(actual_qty > doc.qty) {
to
if(actual_qty >= doc.qty) {

**Comment by rmehta** [comment]
@mbauskar thanks, will fix this.
