### ISSUE TITLE
method `has_sales_order()` has been removed, cannot use `declare_enquiry_lost()`

### ISSUE THREAD

**Issue by tukutela** [frappe/erpnext#31379]
### Information about bug

Removing the method `has_sales_order()` from `selling/doctype/quotation.py` has caused issues when using `declare_enquiry_lost()`, as it references it. Changes made in (#31347|https://github.com/frappe/erpnext/pull/31347/commits/37ba5503987b55e41a174437bca9c99232d256b1). 

### Module

selling

### Version

v13.34.0

### Relevant log output / Stack trace / Full Error Message.

```shell
File "apps/erpnext/erpnext/selling/doctype/quotation/quotation.py", line 119, in 
declare_enquiry_lost
    if not self.has_sales_order():
```

**Comment by deepeshgarg007** [comment]
Fixed via https://github.com/frappe/erpnext/pull/31396
