### ISSUE TITLE
TypeError: get_items() missing 1 required positional argument: 'item_group'

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#31376]
### Information about bug

![image](https://user-images.githubusercontent.com/1822868/173846907-aff36cfc-a3e6-4bb9-bccd-49eaa8f5c7e2.png)

### Module

accounts

### Version

ERPNext: v14.0.0-dev (HEAD)
Frappe Framework: v14.0.0-dev (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1551, in call
    return fn(*args, **newargs)
TypeError: get_items() missing 1 required positional argument: 'item_group'
```

**Comment by dj12djdjs** [comment]
@muchai I'm unable to reproduce this. What steps did you take setting up POS before you got this error?

**Comment by muchai** [comment]
@dj12djdjs just a pos profile.

This is on the nightly/dev version release on FC

**Comment by ahmedyousef96** [comment]
i faced the same issue , how can i solve it ? please help

**Comment by fkalpana** [comment]
If anyone face this problem again, this is the way i solved it. ( V14 ) .

Edit the file apps/erpnext/erpnext/selling/page/point_of_sale/point_of_sale.py
changed the following line 
def get_items(start, page_length, price_list, item_group, pos_profile, search_term=""):

to
def get_items(start, page_length, price_list, pos_profile, search_term="", item_group="All Item Groups"):


Basically made a default value to item group in case its not passed.
