### ISSUE TITLE
production orders skipping steps

### ISSUE THREAD

**Issue by tallen139** [frappe/erpnext#3137]
Hi we have an issue with the production order feature.  When the order is created and the transfer raw materials request is submitted the request messes up 2 parts:

1) it doesnt subtract the inventory from the source warehouse and move it to the work-in-progress warehouse but rather it just adds the quantity to the warehouse (e.g. source warehouse quantity= 10, then transfer materials -> new source quantity=10 and work-in-progress quantity=2)
2) Once the transfer raw materials stock entry has been made the production order gets listed as completed without allowing to "update finished goods" and all the raw material is still in work in progress and nothing is made in the finished goods warehouse but I am unable to edit anything on the production order.

**Comment by tallen139** [comment]
Update:
I have found out the issue I was having with the stock entries but I am still having issue 2 as listed above.

**Comment by rmehta** [comment]
@tallen139 can you reproduce this on https://demo.erpnext.com ?

**Comment by tallen139** [comment]
We are using version 4.1.1.1 and it looks like the demo is using a newer 
version.  Would this affect the test?

Regards,
Tyler

**Comment by rmehta** [comment]
If the issue is there in Version 5, we will surely fix it. You should upgrade to the latest 4.x.x at least, the issue may have gone.
