### ISSUE TITLE
My timesheet timer in the Draft which already saved is still running.

### ISSUE THREAD

**Issue by D-e-v-Sr** [frappe/erpnext#31384]
### Information about bug

Because of some date issues, I can't complete some of the timesheets. Now most of the timesheet in the draft is still running the timer. I can't fix it at any point. What could be the reason. Hope You'll deliver a possible solution
![Capture](https://user-images.githubusercontent.com/100205879/174040881-7c0ba798-a10f-4bd7-b038-a1b0ec3d9f8e.PNG)
.

### Module

projects

### Version

v13.32.0 (version-13)
v13.33.0 (version-13)

### Installation method

FrappeCloud

**Comment by Solufyin** [comment]
Hi @D-e-v-Sr,

Please update a new version on Frappe Cloud.
```
Version:
ERPNext: v13.34.0 (HEAD)
Frappe Framework: v13.33.0 (HEAD)
```
Then after check you site.

Thanks.

**Comment by dj12djdjs** [comment]
@D-e-v-Sr Also, could check if there are any error messages in the browser console when you try to complete the timer,
