### ISSUE TITLE
ERPNext User Interface ERROR

### ISSUE THREAD

**Issue by djapou** [frappe/erpnext#31385]
### Information about bug

Hi all

please need your help
For a few days I have been getting this error that persists when I try to access certain pages or when I try to create new records in ERPNext.

the error is an empty page that displays without content.
How to solve this problem?

the problem started after an update of ERPNext/Frappe to version v13.33.0/v13.32.0 on the online production environment
![ERREUR](https://user-images.githubusercontent.com/42442399/174052261-26e8740f-06dd-42e6-bc14-c73b5fea2b38.png)

thank you

### Module

other

### Version

Frappe Version 13.32.0
ERPNext version 13.33.0

### Installation method

FrappeCloud

**Comment by Solufyin** [comment]
Hi @djapou,

Please update a new version on Frappe Cloud.
```
Version:
ERPNext: v13.34.0 (HEAD)
Frappe Framework: v13.33.0 (HEAD)
```
Then after check you site.

Thanks.

**Comment by djapou** [comment]
thank sir

**Comment by dj12djdjs** [comment]
@djapou Did updating solve the issue?

**Comment by dj12djdjs** [comment]
This is most likely a cache problem from frappe cloud after the update. If updating/clearing the cache didn't fix the issue. Re-open the issue in https://github.com/frappe/frappe/issues
