### ISSUE TITLE
 Bank Clearance Summary Filter for Amount Column Not Working

### ISSUE THREAD

**Issue by jayfiro** [frappe/erpnext#31388]
### Information about bug

The Bank Clearance Summary has an Amount column by default. When entering values in the filter for this column, it does not filter out any of the rows.

![Screen Shot 2022-06-16 at 10 06 13 PM](https://user-images.githubusercontent.com/23268734/174208806-7bccea69-a130-4cf3-a2fe-64f5705f6ade.png)

However, this is the only column  for which filtering does not work. If you enter values in the filter for any other column, it does filter out the rows.

![Screen Shot 2022-06-16 at 10 06 49 PM](https://user-images.githubusercontent.com/23268734/174209139-f1af3d33-3b6d-43c6-b2a1-dd2a4aa5029e.png)

### Module

accounts

### Version

Frappe Framework: v13.33.0 (HEAD)
ERPNext: v13.34.0 (HEAD)

### Installation method

FrappeCloud

**Comment by nihantra** [comment]
Hi @jayfiro,

As per your requirement, we set the amount filter in Bank Clearance Summary.
See the Reference: #31395 

Thank You!

**Comment by nihantra** [comment]
Hi @jayfiro,

Please closed the issue because the pull request merge to develop branch and version-13-hotfix.
The upcoming update will set this issue in stable version 13.

Thank You!
