### ISSUE TITLE
I can no longer modify item names in sales orders item list

### ISSUE THREAD

**Issue by ioweb-gr** [frappe/erpnext#31399]
### Information about bug

When modifying an item name, the item name will reset itself to the one saved in the product. I can no longer modify it. 

Here's a video 

Whenever I try to type my custom name, it will reset it. 

https://user-images.githubusercontent.com/20220341/174433032-79b307f8-d041-48bb-87e3-23aefbec268d.mp4

### Module

selling

### Version

bench_manager 0.0.1
erpnext 14.x.x-develop
frappe 14.x.x-develop

### Installation method

easy-install

**Comment by dj12djdjs** [comment]
I tried in Sales Order and it seems to work fine. Which doctype are you displaying in the video ?

**Comment by ioweb-gr** [comment]
This is in sales order items list

**Comment by nihantra** [comment]
Hi @dj12djdjs,

@ioweb-gr is right.
when the item name clicked then it reset when opened the table.

Please check the below video.

https://user-images.githubusercontent.com/99652762/174796427-d82d82aa-c641-44f7-98db-9b8f332fd6ea.mp4


Thanks.

**Comment by ankush** [comment]
This is just because the item_code field is getting focused and on losing focus it's refetching item details.

**Comment by ioweb-gr** [comment]
which wasn't happening in previous versions and it's a bug.

**Comment by nabinhait** [comment]
Closing as this has been fixed
