### ISSUE TITLE
Date fields based on default fiscal year

### ISSUE THREAD

**Issue by kid1194** [frappe/erpnext#31403]
Hello everyone, 

If would like to suggest that the date fields be based on the default fiscal year to reduce the error of adding entries with a date that doesn't belong to the default active fiscal year. I managed to modify that using the **Client Script** but I had to create scripts for a lot of forms like sales, purchases, etc..

Best regards.

**Comment by SamiHajbi** [comment]
This is one of bigest problems in erpnext also you will have problem with serial if you do script like how you will fix serial if user delete some entry

**Comment by kid1194** [comment]
@SamiHajbi That's true. They need to make dates and naming series work based on the default fiscal year in every part of ERPNext.

**Comment by kid1194** [comment]
I have modified the **ControlDate** javascript file to solve the problem of the date fields, but it is still not tested.

[ERPNext Fiscal Year Based Date Related Fields](https://github.com/kid1194/ERPNext-Fiscal-Year-Based-Date-Related-Fields)

**Comment by kid1194** [comment]
This is a plugin that achieves that.

[ERPNext Fiscal Year Based Date Related Fields](https://github.com/kid1194/ERPNext-Fiscal-Year-Based-Date-Related-Fields)
