### ISSUE TITLE
Selling onboarding steps are disturbed in v14

### ISSUE THREAD

**Issue by sharmanakul** [frappe/erpnext#31409]
### Information about bug

selling onboarding steps in v14
![image](https://user-images.githubusercontent.com/88872881/149063221-ca325a06-54af-411e-bb5e-b7e62c6951c9.png)

selling onboarding steps in v13
![image](https://user-images.githubusercontent.com/88872881/149064543-3193e49f-6d8f-4a2b-86d6-fd8b4b736223.png)

### Module

selling

### Version

v14.0.0

**Comment by ankush** [comment]
looks like done intentionally for whatever reason: https://github.com/frappe/erpnext/pull/27112
