### ISSUE TITLE
Can't "Reject" a MR

### ISSUE THREAD

**Issue by mtntrekker01** [frappe/erpnext#31419]
### Information about bug

Rather than "Approve" an MR, I would like to use the "Reject" option from the dropdown and have the MR go back to working status. When I select "Reject" nothing happens and the MR stays on "Pending Approval"

![image](https://user-images.githubusercontent.com/97990211/174855964-e25e2c16-339a-45f2-b1da-1d1c2fc01235.png)

### Module

ecommerce

### Version

ERPNext: v12.28.0 (version-12)

Frappe Framework: v12.25.0 (version-12)

Riverstone ERPNext PROJ: v0.0.1 (master_new)

UProErpInteg: v0.0.1 (master)

**Comment by dj12djdjs** [comment]
@mtntrekker01 Please check your workflow, and update your system. I've tested on
```
ERPNext: v12.30.1 (HEAD)

Frappe Framework: v12.27.0 (HEAD)
```

It's working, please see attached.
![workflow](https://user-images.githubusercontent.com/29856401/174910717-a823f324-d8e8-4229-8d1c-009d41728987.gif)
