### ISSUE TITLE
Wrong entries when using the refactored Payment Reconciliation tool and Payment Entry using Payment Ledger entry 

### ISSUE THREAD

**Issue by centaur78** [frappe/erpnext#31428]
### Information about bug

While using the Payment reconciliation tool, when pulling the unreconciled entries..... the value shown in the outstanding column is the value in company currency which are in OMR ... whereas the purchase invoice are in Euro

for example the below image ,,if we take the PINV19-00001 ...Actual Invoiced amount is € 256.00  and the value in company currency is RO 107.52..... This is wrongly pulled here due to which we cannot reconcile !!!

This same issue is also seen when using Payment Entry as well  

could be due to this #31136 and related PR

![image](https://user-images.githubusercontent.com/1904802/175060553-69e3bd23-c03f-456f-86e8-b2867f05803b.png)

And Payment ledger entry for the same

![image](https://user-images.githubusercontent.com/1904802/175069755-fe9b945b-773a-4946-b9d1-6041c824f538.png)

### Module

accounts

### Version

ERPNext: v14.x.x-develop () (develop)
Frappe Framework: v14.x.x-develop () (develop)

### Installation method

manual install

**Comment by centaur78** [comment]
Hi @ruthra-kumar 

Could you have a look on this issue ?

**Comment by centaur78** [comment]
hi @ruthra-kumar 

Any update on the above issue ? 

Thanks in advance

**Comment by ruthra-kumar** [comment]
@centaur78 thanks for reporting this.
There are 2 issues here.
1. `account_currency` column is not populated on payment ledger entry creation due to incorrect column name.
2. Reconciliation tool using outstanding amount in company currency instead of account currency.

Should be fixed by #31499
