### ISSUE TITLE
Item detail on RFQ (from item-master) not auto-completing

### ISSUE THREAD

**Issue by johnlongland** [frappe/erpnext#31430]
### Information about bug

When generating an RFQ from within an Item, not all the Item details are auto-completing in the RFQ. I have attached some screen-shots. The first 3 pictures shows when I generate an RFQ from within an item-master.

The last 2 pictures shows when an RFQ is generated by selecting "Request for quotation" from the awesome-bar.

Problem : Item detail not auto-completing.

Desired result : Item-detail must auto-complete when generated from within Item-master, in a similar way when an RFQ is generated from outside the Item-master
![RFQ_1](https://user-images.githubusercontent.com/66208349/175105752-665f7d8e-79d4-45c7-91e3-dae36dea190c.PNG)
![RFQ_2](https://user-images.githubusercontent.com/66208349/175105785-ad9574b1-0f8b-4464-8088-7415848d07b8.PNG)
![RFQ_3](https://user-images.githubusercontent.com/66208349/175105815-f1df148f-20f2-4525-bf66-2e984fb60cd0.PNG)
![RFQ_4](https://user-images.githubusercontent.com/66208349/175105865-4dd892a1-5d8e-4f82-8d59-5165ec226fc7.PNG)
![RFQ_5](https://user-images.githubusercontent.com/66208349/175105903-cf4d712e-1a0a-43ef-8615-74763b3af225.PNG)
.

### Module

buying

### Version

ERPNext: v13.27.1 (version-13)

Frappe Framework: v13.27.0 (version-13)

### Installation method

manual install

**Comment by ankush** [comment]
merging with https://github.com/frappe/frappe/issues/16401 (same root cause)
