### ISSUE TITLE
PDF generation error in General Ledger

### ISSUE THREAD

**Issue by ajiragroup** [frappe/erpnext#31441]
### Information about bug

When creating a PDF from General Ledger, a file with name "pdf" gets downloaded. There is no extension of file. If renamed to "abc.pdf", the file opens all right.

Also, the title of the pdf has no margin on the top.

![image](https://user-images.githubusercontent.com/108009061/175493529-90395717-1535-41a3-9d8b-76f4f1ddcbf8.png)

### Module

accounts

### Version

Frappe version - 13.26.1
ErpNext version - 13.27.0

### Installation method

manual install

**Comment by deepeshgarg007** [comment]
@ajiragroup Works fine for me, maybe some browser setting might be causing this, not an ERPNext App issue
