### ISSUE TITLE
Party Account 2110 - Creditors currency and document currency should be same

### ISSUE THREAD

**Issue by Ponyooooo** [frappe/erpnext#31452]
### Information about bug

![image](https://user-images.githubusercontent.com/60758795/175839078-2a084ee1-d794-46bc-8013-c1b6fe98722c.png)

Not sure when was this bug occurred but we are experiencing it right now for the newly created suppliers but for the past years and for the old suppliers we can still create invoices for AP that has different document Currency. For example, the document currency is billed as INR based on the supplier invoice, but we use the multi-currency to convert the invoice into USD since we need to record the AP in USD since in our credit card it was paid as USD.

We also do this conversion since our profit and loss statement should be in USD. Or are we doing it wrong? Is our process incorrect?

### Module

accounts

### Version

ERPNext: v13.34.1 (HEAD)
Frappe Framework: v13.33.1 (HEAD)

### Installation method

FrappeCloud

**Comment by dj12djdjs** [comment]
@Ponyooooo This was done intentionally. Please refer here for the explanation https://github.com/frappe/erpnext/issues/31193
