### ISSUE TITLE
V13.34.1 sales order and sales invoice amount different

### ISSUE THREAD

**Issue by error-id** [frappe/erpnext#31459]
### Information about bug

1: create a sales with pricing rule for example 5 percent off ,
Submit the sales order
2: change the pricing rule to 10%
3: if the customer happy with the sales order  and the job has been finished we want to create a sales invoice
4: the new sales invoice amount does not equal to the sales order

### Module

accounts

### Version

V13.34.1

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
NA
```

**Comment by vamagithub** [comment]
Can I work on this Issue?

**Comment by maharshivpatel** [comment]
@vamagithub Sure.

**Comment by deepeshgarg007** [comment]
@error-id I am assuming this is happening (the rate is changing) only when you save the Sales Invoice. So before saving the invoice you can check "Ignore Pricing Rule" check and submit the invoice to avoid this
