### ISSUE TITLE
KSA VAT report, Total invoice amount not considering Currency.

### ISSUE THREAD

**Issue by fkalpana** [frappe/erpnext#31461]
### Information about bug

KSA Vat report calculation has a  bug. If the invoices are made in other currencies, VAT total does not consider the currency valuations.
We have found the issue in this file apps/erpnext/erpnext/regional/report/ksa_vat/ksa_vat.py

and corrected in our instance with the following changes  - Please include the same changes in the main code

```

def get_tax_data_for_each_vat_setting(vat_setting, filters, doctype):

    (KSA, {filters}, 'Sales Invoice') => 500, 153, 10 \n

    calculates and returns \n

    total_taxable_amount, total_taxable_adjustment_amount, total_tax"""



```

### Module

regional

### Version

ERPNext: v13.31.0 (version-13)
Frappe Framework: v13.30.0 (version-13)

**Comment by fkalpana** [comment]
Any update on this .

**Comment by deepeshgarg007** [comment]
@fkalpana This issue should be resolved now, please check
