### ISSUE TITLE
Selecting Batch in DN alters price

### ISSUE THREAD

**Issue by TurkerTunali** [frappe/erpnext#31468]
### Information about bug

Selecting a batch in DN, changes the item price although "Maintain same rate through sales cycle" enabled. Related: https://github.com/frappe/erpnext/issues/30540

To Reproduce:
Create an item with batch tracking.
Add a selling price as 1,3 USD.
Create a sales order with 1 USD.
Convert it to DN. Rate will be shown as 1 USD. Selecting a batch will make rate as 1,30 USD. It should be same as sales order's rate.

https://user-images.githubusercontent.com/710051/176140435-121d4c61-4858-43bc-9110-2913289010a1.mp4

### Module

selling

### Version

ERPNext: v13.33.0 (version-13)
Frappe Framework: v13.32.1 (version-13)

### Installation method

easy-install

**Comment by ankush** [comment]
@TurkerTunali can you see if https://github.com/frappe/erpnext/pull/31503 solves your problem?

I didn't see any other field triggering price list apart from batch no. (Others that do are valid triggers - like changing customer, price list itself)

**Comment by TurkerTunali** [comment]
Thank you @ankush . I will check it.
