### ISSUE TITLE
Buy 1 Get 1 Free Pricing Rule Not working

### ISSUE THREAD

**Issue by ravi854** [frappe/erpnext#31479]
### Information about bug

Creating a Procuct Discount Scheme, for buy 1 get 1 free is not working
![erp](https://user-images.githubusercontent.com/85276497/176469991-b3d37b15-60ee-4af9-bf7c-8ddc6e003805.gif)

![ERPNext](https://user-images.githubusercontent.com/85276497/176439248-f84b4309-9c83-478f-9e83-22a9ecd4d669.jpg)

### Module

accounts

### Version

Frappe Version - 13.34
Erpnext Version - 13.34.2

### Installation method

manual install

**Comment by ravi854** [comment]
Good Day,
Steps to reproduce
I creating 2 Items, Item1 and Item2 both stock Item.Bri
![ERPNext_040722](https://user-images.githubusercontent.com/85276497/177124005-cb6f90b9-b5c6-478b-8bb4-cfe4357cc8c9.gif)
ng Stock in for both Items.
Created Pricing Rule on Item Code for Item1 . Under product Discount Scheme, under free Item added Item2.
Qty =1, Rate=0, recursite enabled.
While Making Sales, Free stock dont fetch the Income Account and it gives error mandatory field Income Account needed for Item2.
![Erpnext_040722a](https://user-images.githubusercontent.com/85276497/177124184-8768b5f1-a032-4058-93db-39a0180fabb8.gif)

I will make another Gif and upload what I am refering to

**Comment by pram77** [comment]
Same trouble

**Comment by ravi854** [comment]
Its working in V14

**Comment by yusufrn1** [comment]
> Its working in V14

No, I think it still not working 
![Capture](https://user-images.githubusercontent.com/113101963/217719666-278d835e-b2cb-42f8-a12c-73a6992a4c22.JPG)
![Capture2](https://user-images.githubusercontent.com/113101963/217719801-59625336-1bde-4377-a11e-00030e9be187.JPG)

**Comment by ravi854** [comment]
Some how its working on my side, 
see the attached 
![2023-02-09_14 23 41](https://user-images.githubusercontent.com/85276497/217813218-8fee4d40-ee7d-424b-9fef-ecd3473cead0.gif)
