### ISSUE TITLE
map_current_doc options the "child_fieldname" misspelling

### ISSUE THREAD

**Issue by gn306029** [frappe/erpnext#31474]
### Information about bug

When I allow map_current_doc select child table
Like:
```javascript
erpnext.utils.map_current_doc({
		 method: "erpnext.buying.doctype.purchase_order.purchase_order.make_purchase_invoice",
		 source_doctype: "Purchase Order",
		 target: cur_frm,
		 setters: {
                        schedule_date: undefined,
                  },
                  get_query_filters: {
			docstatus: 1,
		  },
                   allow_child_item_selection: true,
                   child_fieldname: "items",
                   child_columns: ['item_code', 'qty']
})
```
I got error:  Cannot read properties of undefined (reading 'options')
<img width="784" alt="截圖 2022-06-29 上午10 04 02" src="https://user-images.githubusercontent.com/20434666/176335286-1e568c61-d037-4b54-8a2b-64c2b722d3f9.png">

So I check source code,
In https://github.com/frappe/erpnext/blob/develop/erpnext/public/js/utils.js#L716
opts.child_fieldname is misspell to opts.child_fielname, missing "d"
when I modify child_fieldname to child_fielname, is resolve

### Module

other

### Version

Frappe Version: 13.32.0
ERPNext Version:  13.33.0

**Comment by nihantra** [comment]
Hi @gn306029,

Please create the pull request for it.

Thanks.
