### ISSUE TITLE
Duplicate Item in Material Request

### ISSUE THREAD

**Issue by ruchin78** [frappe/erpnext#3147]
When I generate Material Request through Production Planning Tool, using the reference of Sales Order. Then when material request is generated for items where Minimum Order Quantity is defined for an item in item master, in that case system inserts item name twice in the material request to fulfil the minimum order quantity requirement.
For example as per Sales Order quantity required for raw material X is 4 whereas in item master its minimum order quantity is defined 100, in that case system will insert 2 rows in the material request as shown below

Item Name            Quantity
X                            96
X                            04

Now the problem comes when you try to create purchase order on the basis of material request of such kind, system will not allow you to create purchase order and will ask to complete the minimum order quantity requirement and so many things.

**Comment by rmehta** [comment]
It adds in separate rows because you can track it against Sales Order. But yes it could be better.

**Comment by ruchin78** [comment]
Actually you cannot create a purchase order with these kinds of material
request where item code is duplicate to fulfil the MOQ requirement.

I have tried to create Purchase Order so many times, also the same issue I
have reported to my support team but till now we didn't get any solution.
Please try to create Purchase Order with these kind of Material Request, I
challenge that you can't create.

*Regards*
*Ruchin Sharma*
*ERP Specilist*
*miSport Manufacturing Pvt. Ltd.*
*+91 9718555281*
*skype id:ruchinsharmagur*
