### ISSUE TITLE
Strange text outputs in generated PDFs of sales invoices

### ISSUE THREAD

**Issue by flortsch** [frappe/erpnext#31488]
### Information about bug

With the recent update to ERPNext 13.34.2, I get strange text outputs in generated PDFs of my sales invoices.
The generated PDFs contain the words "Drucken" (print in German), and "Get PDF" (as a link to my ERPNext instance).
Note that these strings don't show up when viewing the web/online version of the sales invoices.
I am using a custom sales invoice print format that does not contain any of these strings.
Generated PDFs worked just fine on my last ERPNext version (13.29.2).

Here are two screenshots where you can see this behavior.
The first one is the web version of a sales invoice that works fine.
The second one shows the generated PDF with the strange text output marked in a red box.

![Bildschirmfoto vom 2022-06-30 00-28-43](https://user-images.githubusercontent.com/15350076/176557817-21e08319-593a-4a54-97c0-82f6c53c2650.png)

![Bildschirmfoto vom 2022-06-30 00-29-03](https://user-images.githubusercontent.com/15350076/176557829-ed55b38a-877f-4152-ba96-f6b9b8269b51.png)

### Module

selling

### Version

Frappe version: 13.34.0
ERPNext version: 13.34.2

### Installation method

docker

**Comment by flortsch** [comment]
I managed to fix this issue. It's not an ERPNext bug, it's related to the Docker setup with the assets volume that has to be removed before upgrading ERPNext so it can be re-populated. Also see: https://github.com/frappe/frappe_docker/issues/790

**Comment by smmitc** [comment]
I have the same problem with new ERPNext deployments using the official helm charts (4.0.47). There are no problems with versions v13.29.2, v13.30.0 and v13.31.1. But starting from v13.32.0 I can confirm the above described strange output.

For testing, I used the following procedure for each version from v13.29.2 to v13.36.1 and v14.0.0-beta.6:
```
cat <<EOF>custom-values.yaml
nginx:
  image:
    tag: v13
worker:
  image:
    tag: <ERPNext Version>
socketio:
  image:
    tag: v13

persistence:
  worker:
    storageClass: "longhorn"

jobs:
  createSite:
    enabled: true
    siteName: "erpnext.example.org"
    adminPassword: "secret"
EOF

helm install frappe-bench --namespace beta frappe/erpnext -f custom-values.yaml
```

The quotation has been generated with
```
curl "https://erpnext.example.org/api/resource/Item" -H 'Accept: application/json' -d '{"item_code": "my Service","item_group": "Services","stock_uom": "hour","is_stock_item": "0","standard_rate": "1000"}'

curl "https://erpnext.example.org/api/resource/Customer" -H 'Accept: application/json' -d '{"customer_name": "Customer 1","customer_type": "Company","customer_group": "Commercial","territory": "All Territories"}'

curl "https://erpnext.example.org/api/resource/Address" -H 'Accept: application/json' -d '{"address_title": "Customer 1","address_type": "Billing","address_line1": "Mall Street 1","city": "NYC","country": "United States","links": [{"link_doctype": "Customer","link_name": "Customer 1","__unsaved":0}]}'

curl "https://erpnext.example.org/api/resource/Quotation" -H 'Accept: application/json' -d '{"naming_series": "SAL-QTN-.YYYY.-","quotation_to": "Customer","party_name":"Customer 1","company": "Example Org","order_type": "Sales","transaction_date": "2022-07-28","currency": "USD", "conversion rate": "1","plc_conversion_rate":"1","selling_price_list": "Standard Selling", "items": [{"item_code":"my Service","qty":"1"}]}'
```

The document generated by ERPNext v13.31.1 is fine:
![v13 31 1](https://user-images.githubusercontent.com/110170775/181502621-a25b9a93-2c5f-4380-9966-1abbe0f9eb73.png)

The document generated by ERPNext v13.32.0 is not:
![v13 32 0](https://user-images.githubusercontent.com/110170775/181502637-96a6f2d6-d485-491b-a035-7c07f0718ba6.png)

I think this simple setup should work for all ERPNext versions. Would be great if someone is able to help.

**Comment by flortsch** [comment]
I am not familiar with Helm, but does it use volumes / caches for the Assets directory? If so, clearing that before re-deploying ERPNext might help, similar to the Docker setup.

**Comment by smmitc** [comment]
Hi flortsch, thanks very much for answering that fast! The [Helm chart](https://artifacthub.io/packages/helm/erpnext/erpnext) uses the official erpnext docker images and deploys it in Kubernetes. In my described testing, I never did an upgrade but always a clean installation for each ERPNext version. As I understand, there is nothing to clear in that case or do I get something wrong?

**Comment by flortsch** [comment]
I am not familiar with Kubernetes either, have always tried to avoid it so far due to its complexity. But I see it has a concept of volumes similar to Docker. It could be that Helm/Kubernetes sees the volume declarations in the Docker images of ERPNext and creates persistent Kubernetes volumes. So even if you do a clean install, you might have some old Asset volumes on your machines (which Kubernetes does not delete) that you have to clear before running a new installation.

**Comment by smmitc** [comment]
Yes, `helm -n beta uninstall frappe-bench` does remove all pvcs/volumes but the pvc of mariadb. However, I did that manually before doing new fresh installation by issuing the command `kubectl -n beta delete pvc data-frappe-bench-mariadb-0`. So I think we can rule that out. In my opinion, that leads to the conclusion that the problem is not only related to upgrades. Could you please re-open this issue?

**Comment by smmitc** [comment]
Thx! How did you fix this issue with docker? You did a `docker volume rm <name of the volume>` and after that you used the new image version? Or did you a `rm -r  /home/frappe/frappe-bench/sites` inside the container before the upgrade?

Have you installed a new ERPNext instance >= v13.32.0 successfully?

**Comment by flortsch** [comment]
So I have a `frappe-assets` volume that is mounted into `/home/frappe/frappe-bench/sites/assets` and shared between the ERPNext containers. And yes, before I upgrade ERPNext, I just stop/remove all containers and remove the volume with `docker volume rm frappe-assets`. Then I redeploy the containers with the new image version and that's it. I don't remove any folder inside the containers.

Yes, we currently run v13.36.1 without any issue.

**Comment by flortsch** [comment]
It could also be that you only have a sites volume that sits on `/home/frappe/frappe-bench/sites`. If so, you would have to remove the content of the assets folder within that volume.

**Comment by smmitc** [comment]
> Yes, we currently run v13.36.1 without any issue.

Strange. Maybe the issue is related to my k3s environment using containerd instead of docker. Kubernetes dropped the docker support since version 1.20. Or there might be a problem with the chart or the way I'm using it.

```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.8+k3s2", GitCommit:"fe3cecc219175ea85d7a95ed9e44349d94734bc7", GitTreeState:"clean", BuildDate:"2022-07-06T20:35:20Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.8+k3s2", GitCommit:"fe3cecc219175ea85d7a95ed9e44349d94734bc7", GitTreeState:"clean", BuildDate:"2022-07-06T20:35:20Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
```

I'm going to do a clean installation with docker and post the results. Thanks again for the help!

**Comment by smmitc** [comment]
That's interesting, I've reproduced the same error in docker using the installation instructions documented [here](https://github.com/frappe/frappe_docker/blob/main/docs/setup-options.md):
```
git clone https://github.com/frappe/frappe_docker
cd frappe_docker
mkdir ~/gitops
docker compose -f compose.yaml \
  -f overrides/compose.noproxy.yaml \
  -f overrides/compose.erpnext.yaml \
  -f overrides/compose.mariadb.yaml \
  -f overrides/compose.redis.yaml \
  config > ~/gitops/docker-compose.yml

docker compose --project-name example -f ~/gitops/docker-compose.yml up -d
docker exec example-backend-1 bench new-site localhost --mariadb-root-password 123 --admin-password secret --install-app erpnext
```

After that I used the commands mentioned above to setup the example quotation:
```
curl "http://localhost:8080/api/resource/Item" -H 'Accept: application/json' -d '{"item_code": "my Service","item_group": "Services","stock_uom": "hour","is_stock_item": "0","standard_rate": "1000"}'

curl "http://localhost:8080/api/resource/Customer" -H 'Accept: application/json' -d '{"customer_name": "Customer 1","customer_type": "Company","customer_group": "Commercial","territory": "All Territories"}'

curl "http://localhost:8080/api/resource/Address" -H 'Accept: application/json' -d '{"address_title": "Customer 1","address_type": "Billing","address_line1": "Mall Street 1","city": "NYC","country": "United States","links": [{"link_doctype": "Customer","link_name": "Customer 1","__unsaved":0}]}'

curl "http://localhost:8080/api/resource/Quotation" -H 'Accept: application/json' -d '{"naming_series": "SAL-QTN-.YYYY.-","quotation_to": "Customer","party_name":"Customer 1","company": "Example Org","order_type": "Sales","transaction_date": "2022-07-28","currency": "USD", "conversion rate": "1","plc_conversion_rate":"1","selling_price_list": "Standard Selling", "items": [{"item_code":"my Service","qty":"1"}]}'
```

```
$ docker -v
Docker version 20.10.12, build 20.10.12-0ubuntu2~20.04.1
$ docker compose version
Docker Compose version v2.2.3
```

And just in case the first attempt didn't work and the asset volume is damaged, I did a `docker compose --project-name example -f ~/gitops/docker-compose.yml down`, deleted the volume with `docker volume rm frappe_docker_assets` and brought the containers up again, but then I still got the same error.

**Comment by flortsch** [comment]
So is this a complete clean install with a new site, or do you run the containers with the data of your existing site?

**Comment by smmitc** [comment]
It's a complete clean install with a new site.

**Comment by smmitc** [comment]
In the setup, I enter some data about language, company etc. After that I've injected the Customer, article and a quotation using the above shown four curl commands so that it can be easily reproduced by anybody. FYI these are the installed versions:
```
ERPNext: v13.36.2
Frappe Framework: v13.36.3
```

**Comment by smmitc** [comment]
This issue has been [solved](https://github.com/frappe/frappe_docker/issues/865#issuecomment-1203506025) by Byju Abraham.
