### ISSUE TITLE
TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'

### ISSUE THREAD

**Issue by Epdecking** [frappe/erpnext#31494]
### Information about bug

Error when saving purchase invoice. It just started to happen this week, never encountered this issue in the past. 

### Module

buying

### Version

ERPNext: v13.34.2 (HEAD)

Frappe Framework: v13.34.0 (HEAD)

**Comment by ankush** [comment]
when this happens "copy error to clipboard" and share the error. Else it's not really simple to identify what is the problem. 


Share that extra info and we can reopen the issue.
