### ISSUE TITLE
Items table appears blank in Pricing Rule 

### ISSUE THREAD

**Issue by yadavyk** [frappe/erpnext#31502]
### Information about bug

In the pricing rule form the items table against ( Apply Rule on Item Code ) appears blank without any rows 

![Untitled 8](https://user-images.githubusercontent.com/32797974/176889501-ac310697-226c-404a-8463-e297fbdae8ce.png)

Version : 

ERPNext: v13.34.2 (HEAD)
Frappe Framework: v13.34.0 (HEAD)

### Module

accounts

### Version

ERPNext: v13.34.2 (HEAD)
Frappe Framework: v13.34.0 (HEAD)

**Comment by rohitwaghchaure** [comment]
@yadavyk When you change the Apply On and save it and again select the same Apply On then it disappears otherwise it won't. Could you share steps to replicate the issue?

**Comment by rohitwaghchaure** [comment]
@yadavyk since we are not able to replicate the issue, closing this ticket. If you still facing the issue on latest v13 version then create a new ticket with proper steps
