### ISSUE TITLE
Negative Expense in Balance Sheet

### ISSUE THREAD

**Issue by EigenSolver** [frappe/erpnext#31511]
### Information about bug

I added a Freight and Forwarding Expense in a material transfer between two warehouse. 
Ideally, the expense should be counted positive in the balance sheet and decrease the profit. 
Yet, negative expense is counted in the balance sheet, which caused an increase of profit. 

The expense I added in the stock entry.
![image](https://user-images.githubusercontent.com/20223932/177032166-76e51007-ebc1-43ec-9b78-4e81b6bff1e5.png)

The corresponding ledger:
![image](https://user-images.githubusercontent.com/20223932/177032188-13f68ea6-fe38-4013-9f7e-118e19f79606.png)

The final balance sheet:
![image](https://user-images.githubusercontent.com/20223932/177032123-43316cab-ac46-4597-baee-5d57c1dd2b6b.png)

Similar problem is also reported on the ERPnext forum. 
https://discuss.erpnext.com/t/negative-expenses-in-profit-or-loss-account/76367

### Module

accounts

### Version

Frappe version - 13.32.1
ERPnext version - 13.33.0

### Installation method

manual install

**Comment by rmehta** [comment]
We are giving an option to choose the account.

Also expenses should be P&L accounts, not balance sheet accounts.

**Comment by nabinhait** [comment]
As you are using perpetual inventory, while transferring the stock the freight and forwarding expenses will be counted in the landed cost of the item, hence will increase Stock-in-hand value. And expenses will be booked when the item will be consumed or delivered later.

Closing the issue.
