### ISSUE TITLE
Fixing issue 31439 creates another issue

### ISSUE THREAD

**Issue by johnlongland** [frappe/erpnext#31512]
### Information about bug

Good day devs
I have just upgraded my servers ( multi-tenant, sub-domain) from 13.27.1 to 13.34.2 and directly after that I wanted to do the
month-end journals for the previous month and noticed that there is no longer a "Finance Book" field available in the Journal Entry.

I made a post in the forum..
https://discuss.erpnext.com/t/finance-book-in-journal-entry-v13-34-2/91671
and Brian drew my attention to this fix that was finalized 9 days prior. It seem to be issue #31439, where the Finance Book field was made RO.

This now creates a situation where, my previous Journal entries ( 109 of them) all have Finance Book entries and now the entry into `tabJournal Entry` is NULL.

And yes, I tried manually setting these entries with an UPDATE in MARIADB but surely I shouldn't have to do mysql entries manually?

Does a NULL entry in the Journal doc really solve the problem of issue 31439? If making it RO is the only solution,  and that the field should not be editable by myself, surely , it can at least be auto-loaded from the default settings on the Company master ?
Then the field still remains RO but then there will be continuity with my system as well , instead of suddenly loosing those entries in my `tabJournal Entry` and in `tabGL Entry` 

It is the same with issue 30839, where I suggested that "Cost Center" be auto-loaded from the Company master.
Not sure why "default" values are not auto-loaded from the Company master. Surely that is the purpose of a default
value... a value that is used be default and has to involve a specific action to be changed by the user ??

What is my expectation
My approach arround settings like "Finance Book" is that, although I don't have multiple finance books, I actually do complete the field so that incase I have a requirement later to have multiple financebooks, then at least all my entries already has an option set. So I would like the following outcome...
IF making the finance book field RO solves a problem, then at least auto-load default values for finance book from the Company master so that people like me can continue using our systems instead of finding ourselves with a system that now seems broken.

Thank you

### Module

accounts

### Version

ERPNext: v13.34.2 (version-13)

Frappe Framework: v13.34.0 (version-13)

### Installation method

manual install

**Comment by dj12djdjs** [comment]
I don't use Finance Books or Asset management in ERPNext. I'm not familiar on this topic.

> 3. Make the finance book field in Journal Entry read-only
The Finance book field in Journal Entry was only added for the purpose of single Asste depreciations via multiple methods as a compliance requirement for some companies. Many users end up using that without having proper knowledge or context about it and later end up having issues while reporting

@deepeshgarg007 Is there an alternative since manual entries have been disabled?

**Comment by valignit** [comment]
https://docs.erpnext.com/docs/v13/user/manual/en/accounts/finance-book 
clearly states that 'You can also use this to post alternate balance sheets for your internal reporting' which contradict the latest explanation  'only added for the purpose of single Asste depreciations via multiple methods as a compliance requirement'. So there is no question of 'proper knowledge' in this case. So please do the needful to provide a reasonable workaround.

**Comment by johnlongland** [comment]
Good day. I see the "valid" label has been removed and the "discussion" label added. Not sure why this was done, but if there is to be a discussion about this then perhaps I should open it ....
As you can see by my first post higher up, this change has left me stranded. I only have one finance book currently but in the event of a change in the way I operate later, I am now left without that option. And that, only because some other issue (31439) had to be fixed. I failed to see how this was really a fix for that issue.

Perhaps, to continue this discussion, the reason why this is a fix for issue 31439, can be explained so that we can understand.

**Comment by nabinhait** [comment]
As you have only a single finance book in your system, there is no need to create a finance book record. Keeping the finance book field blank means it's the default finance book.

Still, if you want to set the finance book in Journal Entry, you can set the default value in the finance book field from Customize Form. Closing the issue.
