### ISSUE TITLE
perf: Report Stock Balance

### ISSUE THREAD

**Issue by marination** [frappe/erpnext#31528]
With almost 1.1 million SLEs the background job `run_background` prematurely terminates
Seems like its a memory issue.

SLEs could be queried and looped over in batches. Build the resultant data incrementally
<img width="1397" alt="Screenshot 2022-07-05 at 7 10 58 PM" src="https://user-images.githubusercontent.com/25857446/177343954-2037300f-1b6e-4d52-a1c5-d299ef30f0e9.png">

Or bump up the memory

**Comment by ankush** [comment]
duplicate https://github.com/frappe/erpnext/issues/29183
