### ISSUE TITLE
ERPNext Version 5 Data Import Erro

### ISSUE THREAD

**Issue by ruchin78** [frappe/erpnext#3153]
Template downloaded from one instance of Version 5 should be able to upload as it is (without changing) to another instance of Version 5.

Like:
Item Group
BOM etc.

**Comment by rmehta** [comment]
Can you share the error?

**Comment by ruchin78** [comment]
The error is simple asking for the parent item.
My suggestion is, when csv get generated it should arrange the data in a manner so that the parent come first, then in that case there will be no error while uploading the data into another instance.
It will be more painful in case of BOM where your BOM has more sub-assemblies at different level.

**Comment by ruchin78** [comment]
![image](https://cloud.githubusercontent.com/assets/11055625/7297226/87577ed4-e9e4-11e4-81f2-0be3df0cd1db.png)

**Comment by nabinhait** [comment]
To import item groups (tree structured documents) successfully, parent item group must be imported before importing child item group.

While exporting the data from the report view, sort the data by "lft" and "rgt", it will give you the data in the correct order. Then you can import that data into the other system.

**Comment by ruchin78** [comment]
Can you explain it what is "lft" what is "rgt", I hope it is left and right
but can you explain with an example screenshot, that by which way we should
sort the data. Also, will that be applicable on BOM?


*Regards*
*Ruchin Sharma*
*ERP Specilist*
*miSport Manufacturing Pvt. Ltd.*
*+91 9718555281*
*skype id:ruchinsharmagur*

**Comment by ruchin78** [comment]
Also, can you explain me what do you mean by exporting the data from report
view?

*"While exporting the data from the report view, sort the data by "lft" and
"rgt", it will give you the data in the correct order. "*

*Regards*
*Ruchin Sharma*
*ERP Specilist*
*miSport Manufacturing Pvt. Ltd.*
*+91 9718555281*
*skype id:ruchinsharmagur*

**Comment by rmehta** [comment]
You can just delete the lft, rgt columns while importing.

**Comment by nabinhait** [comment]
![item_group_export](https://cloud.githubusercontent.com/assets/836784/7318756/e7ca4a1c-eaac-11e4-8213-91f00d6a182b.gif)

**Comment by nabinhait** [comment]
Lft and rgt are internal fields to maintain tree structure. And yes, it is applicable for BOM as well.
