### ISSUE TITLE
Received Validation on Purchase Order not working properly

### ISSUE THREAD

**Issue by mro-admin** [frappe/erpnext#31535]
### Information about bug

If an item in a purchase order is overreceived and the qty of the overreceived item is equal to the qty of the other items yet to be received ERPNext marks the purchase order as fully received. For example you have a purchase order with 3 line items for 1 each
and for the first line there is an over receipt of 3 qty. It will mark the purchase order as completed even if the other line items haven't been received yet

### Module

accounts, buying

### Version

Frappe Framework: v13.33.1 
ERPNext: v13.34.1

**Comment by dj12djdjs** [comment]
I have a purchase order with two items. One of the item is over received, the other is not received. The Purchase Order is still marked as To Receive.

![image](https://user-images.githubusercontent.com/29856401/178361164-feaff132-dd3b-4c0c-a3ee-6ecb3cf1f433.png)


![image](https://user-images.githubusercontent.com/29856401/178361327-b5ed1e05-f99a-4583-b6a3-640ab0f569a5.png)

**Comment by rohitwaghchaure** [comment]
@mro-admin 

I am not able to replicate the issue locally

I have created Purchase Order and added same item 3 times in the Purchase Order Item table. Then I have created purchase receipt and removed row 2 & 3 and increased the quantity of first row from 1 to 3.



After Submission of purchase receipt, I have checked the PO status and it was showing correctly as "To Receive and Bill"

**Purchase Receipt**

<img width="1191" alt="image" src="https://user-images.githubusercontent.com/8780500/192977949-08f9508b-13a6-4e28-82fc-b9c96691528c.png">

**Purchase Order**
<img width="1336" alt="Screenshot 2022-09-29 at 1 40 00 PM" src="https://user-images.githubusercontent.com/8780500/192977848-e9a4a342-03a3-4b19-a1bf-9a273633c034.png">

Status showing correct value as "To Receive and Bill"
