### ISSUE TITLE
Creating Sales/Purchase Return with Negative Rate

### ISSUE THREAD

**Issue by dj12djdjs** [frappe/erpnext#31533]
### Overview
When creating a return with a negative rate, the transaction is treated as an invoice instead of a credit.
This can happen if operator gets confused when adding negative quantity and also adds a negative rate.

### Observed Behavior
The transaction is submitted as an invoice.

### Expected Behavior
A validation error should be thrown similar to when positive qty is entered for a return.

### Module

accounts, buying, selling

### Version

frappe: develop
erpnext: develop

### Installation method

manual install

**Comment by yadavyk** [comment]
@dj12djdjs , a validation is thrown when positive qty is entered in return. 

![Untitled 11](https://user-images.githubusercontent.com/32797974/178666111-509ac1a9-558d-407b-9c7b-c218e744fade.png)

This is on : 

ERPNext: v14.x.x-develop () (develop)
Frappe Framework: v14.x.x-develop () (develop)

Could you confirm on which version are you facing this or the exact steps you're using to reproduce this ?

**Comment by dj12djdjs** [comment]
@yadavyk I should re-write the issue more clearly. I mean if you specify a negative rate and a negative qty it will be submitted as an invoice.

What I ment when refering to the negative qty is that a negative price (rate) should throw a validation error similarly how a positive qty would.

**Comment by deepeshgarg007** [comment]
@dj12djdjs This seems like a simple one, can you raise a PR for this?
