### ISSUE TITLE
translation mistake on new-employee-checkin

### ISSUE THREAD

**Issue by billy995** [frappe/erpnext#31536]
### Information about bug

Can't find file to change german translation  IM to EIN

![grafik](https://user-images.githubusercontent.com/48571007/177422779-a0a738a0-0386-4f49-9d68-07639acfd1e5.png)

### Module

HR

### Version

Frappe Framework: v13.29.1 (version-13)
ERPNext: v13.30.0 (version-13)

### Installation method

manual install

**Comment by dj12djdjs** [comment]
Hello @billy995,

Here is the file location for German translations.
https://github.com/frappe/erpnext/blob/0b822dade01c16a0f8319744113885f6b53bdcf4/erpnext/translations/de.csv#L6006

**Comment by billy995** [comment]
Thanks dj12djdjs, is it possible that you will fix this bug in the next version? Otherwise there could be translation mistakes for  German-speaking users
