### ISSUE TITLE
Incorrect data populated in HSN-wise-summary of outward supplies 

### ISSUE THREAD

**Issue by sjain17** [frappe/erpnext#31547]
### Information about bug

Double Total amount and Total Taxable Amount getting populated in the report if Sales Invoice has more than tax applicable. For example - If a sales invoice is having an item with an item tax template of GST 18% which is the combination of CGST 9% and SGST - 9% then the qty, total amount, and the total taxable amount is showing double value in HSN-wise-summary of outward supplies for that particular HSN. 

I think it is applying the loop for Taxes twice and adding the value two times from the sales invoice item (HSN-wise). 

### Module

regional

### Version

Frappe Version - 13
ERPNext Version - 13

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
There is no error in report publishing but the data is incorrect when invoice is having two tax lines.
```

**Comment by maharshivpatel** [comment]
Hello, can you please update to latest version and let us know if issue still persists.

**Comment by maharshivpatel** [comment]
I am closing the issue as it has been fixed. if you are still facing the issue please let me know.
