### ISSUE TITLE
Collaborative Project Mangement

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#3155]
Add collaborators on a project where they can follow progress, raise queries and comments

**Comment by skytizens** [comment]
@rmehta Please do not forget about Milestones to group Tasks. Very important is also ability to add attachments (more than one) to comments. So client can add print-screen/testing-report and write description. Attachment should be stored in (related to): 
* Documents (or Attachments) > Project > Project_Name (with status Comment Attachment - CA, because here I will have also many TOR). On that list we should have: File Name | Title | Project | Task | Category | CA {y/n} | Creator | .... (maybe something else)
* Documents (or Attachments) > Client > Client_Name - with: File Name | Title | Client | Category | CA {y/n} | Creator | .... (maybe something else)

Portal Pages are ok, but looks like you forgot about Milestones.

**Comment by skytizens** [comment]
@rmehta would be perfect if in that phrase we can:
1) add Milestones - details:
![screenshot202](https://cloud.githubusercontent.com/assets/12097152/7333418/8907ed34-eb99-11e4-871e-68553e51c6e9.png)

2) recommended files for Milestone: Title, Description, Due Date, Priority, Assign To (Employee) - feel free to add fields
* task related to Milestone cannot be after Milestone Due Date

3) when adding a new task ability to choose Milestone:
![screenshot203](https://cloud.githubusercontent.com/assets/12097152/7333457/819b0936-eb9a-11e4-997f-efa8eadca9f3.png)

4) ability to hide/disable Time Log Page (view) from Project on Customer Portal

Excluding the issue with Attachments (documents) thats all for phrase I.

**Comment by rmehta** [comment]
@skytizens do you want to start with this project?

**Comment by skytizens** [comment]
@rmehta thank you for your answer. Yes, we do.

**Comment by rmehta** [comment]
@skytizens Great. Would you be willing to sponsor? Do you have a budget in mind?

**Comment by skytizens** [comment]
@rmehta yes. We would like to use ERPNext in our company to collaborate with our clients instead of using existing application.

Last time you told me about 1000USD.

**Comment by rmehta** [comment]
@skytizens awesome, we can take this up now. 50% advance and 50% on completion? Can you email me your details at sales at erpnext dot com. 

Thanks again for your support!

**Comment by skytizens** [comment]
@rmehta no problem I will send you an email soon.

**Comment by rmehta** [comment]
The plan is to have a common interface for projects, issues etc so that we do not recreate the same UI for website user

- [ ] Merge **Website User** and **System User**
- [ ] Add new role **Portal User** with owner rights on Project, Task, Issue, Address
- [ ] Sales Order, Sales Invoice, Address will be visible via Share
- [ ] New home page for Portal User
- [ ] Company branding on new home page via website settings (?)
- [ ] New permission rule for owner match (based on user permissions?)

**Comment by skytizens** [comment]
@rmehta Please find my idea for "New home page for Portal User" :)
![erpnext-example](https://cloud.githubusercontent.com/assets/12097152/8702173/50a4bd0a-2b40-11e5-9294-5097fd7f8ceb.jpg)

Just group of the small tables with some useful information. 

Company branding on new home page via website settings (?) > Good idea
New permission rule for owner match (based on user permissions?) > Good idea

However most important are useful collaborative features - ready for production.

**Comment by rmehta** [comment]
@skytizens yeah we will need a home page, I am not too sure about the small tables as it will have design issues + we have to think about our. We will run it via our designer. 

Will keep you updated.

**Comment by skytizens** [comment]
@rmehta Yes of course. This is just my idea to have two groups:
a) indicators with useful information about important activities
b) two columns, tables with details about invoices, answered issues, projects, tasks, calendar, etc...

**Comment by mhbu50** [comment]
+1

**Comment by rmehta** [comment]
added in v7
