### ISSUE TITLE
Renaming cost center automatically adds old company abbreviation

### ISSUE THREAD

**Issue by blewsky** [frappe/erpnext#31562]
### Information about bug

ERPnext automatically adds the company abbreviation after each cost center. 
After a company abbreviation was changed, renaming a cost center does not work properly. ERPnext still adds the old company abbreviation. It is impossible to remove this part of the name, since ERPnext handles it internally (only the front part of the cost center is editable - not the abbreviation itself). 

A similar issue was previously raised here:
https://github.com/frappe/erpnext/issues/26746
This PR addresses a similar issue but doesn't solve the problem.
https://github.com/frappe/erpnext/pull/27766

**Suggested solution:** 
Allow the modification of the abbreviated part of the name which is currently impossible.

### Module

accounts

### Version

ERPNext: v13.35.0 (HEAD)
Frappe Framework: v13.35.0 (HEAD)

### Installation method

FrappeCloud

**Comment by vamagithub** [comment]
https://github.com/frappe/erpnext/pull/31619
