### ISSUE TITLE
Mandatory Error on Accounting Dimension Fields when clicking Submit Salary Slip Button in Payroll Entry

### ISSUE THREAD

**Issue by koplingganda** [frappe/erpnext#31564]
### Information about bug

Hello everyone, thank you for this opportunity and this fantastic framework. I want to raise a bug report in the HR module in this opportunity. 

This is actually not a bug in a normal case, but I have a mandatory accounting dimension field called Unit in Journal Entry and it makes us cannot submit salary slips in Payroll Entry even though the Unit field is filled. It will raise an exception that occurred due to the accounting dimension field Unit in Journal Entry is mandatory and it is not filled. 

I want to fix this in Payroll Entry that when I click Submit Salary Slips button in Payroll Entry, it will check all accounting dimensions field in Journal Entry. So, for example, if I set a value in the accounting dimension field Unit in Payroll Entry, it will pass the value of field Unit to the Accrual Journal Entry. I would be very happy to help develop this feature if I am allowed to do so😊

Thank you for your attention

Attachment: 

![image](https://user-images.githubusercontent.com/48271907/178183175-3a7729e6-cc3a-4041-aac5-1849ae4015d9.png)

### Module

HR

### Version

12.31.0
12.28.0

### Installation method

docker

**Comment by deepeshgarg007** [comment]
@koplingganda Please upgrade to version-13, this problem has been solved there

**Comment by hans-permana** [comment]
hi @deepeshgarg007 is there a chance this fix is also ported to version 12? Some of our apps are still depending on ERPNext version 12. Do you have any suggestions on what to do?
