### ISSUE TITLE
how to create attendance with working hours and calculate salary on the basis of working hours

### ISSUE THREAD

**Issue by megha0071994** [frappe/erpnext#31570]
### Information about bug

how can I mark employee attendance with employee checkins and outs and how can I calculate salary on the basis of that working hours in a month.

### Module

HR

### Version

Installed Apps
ERPNext: v13.28.0

Frappe Framework: v13.28.0

### Installation method

manual install

**Comment by dj12djdjs** [comment]
Hello @megha0071994,

Please refer to the docs: https://docs.erpnext.com/

For community support use: https://discuss.erpnext.com/

**Comment by mykeysr** [comment]
@megha0071994 Did you find the solution?

**Comment by megha0071994** [comment]
Not yet
