### ISSUE TITLE
A couple of bad links in online manual

### ISSUE THREAD

**Issue by fblauer** [frappe/erpnext#3158]
Results in error:
https://manual.erpnext.com/setting-up/setup-wizard/step-2-profile-details
https://manual.erpnext.com/setting-up/setup-wizard/step-3-company-details

**Comment by anandpdoshi** [comment]
Thanks! Fixed. Will be released tomorrow. :smile:

**Comment by anandpdoshi** [comment]
Ok. This is a different issue. These are old links. Can you go back to https://manual.erpnext.com/setting-up/setup-wizard and click on a link from the list of steps.

**Comment by fblauer** [comment]
I get an error:

https://manual.erpnext.com/setting-up/setup-wizard/step-2-profile-details

On Fri, Apr 24, 2015 at 2:02 PM, Anand Doshi <notifications@github.com>
wrote:

> Ok. This is a different issue. These are old links. Can you go back to
> https://manual.erpnext.com/setting-up/setup-wizard and click on a link
> from the list of steps.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/frappe/erpnext/issues/3158#issuecomment-96015231>.
>



-- 
Fred Blauer CA, CPA, CISA
http://openacct.ca
514-667-1555

**Comment by anandpdoshi** [comment]
Fixed the error. Can you refresh and check again?

**Comment by fblauer** [comment]
OK, no errors now

On Fri, Apr 24, 2015 at 3:11 PM, Anand Doshi <notifications@github.com>
wrote:

> Fixed the error. Can you refresh and check again?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/frappe/erpnext/issues/3158#issuecomment-96039025>.
>



-- 
Fred Blauer CA, CPA, CISA
http://openacct.ca
514-667-1555
