### ISSUE TITLE
Error mesage when trying to run profit and loss statement - permissions? 

### ISSUE THREAD

**Issue by fblauer** [frappe/erpnext#3159]
![en_error_pl](https://cloud.githubusercontent.com/assets/1015215/7333151/3e90aad8-eb31-11e4-92bd-b2c9a0389925.PNG)
I receive this error message when I try to run the PL statement. I am the system admin and should have have full access to everything. So, I don't know why it is telling me that there is a problem with permissions. If I look at the permitted documents by user, the PL statement is in there.

**Comment by rmehta** [comment]
@fblauer Cannot replicate it. You can also remove permissions for System Administrator. Please check Role Permission Manager.

Did you change any permission rules?

**Comment by fblauer** [comment]
I can give you access to my instance if you like. I am working on a test
phase as this point, and it is not live.

I didn't touch any of the permissions or rules. I am logging as the user
that the system created when I created the company. I checked access to all
the roles and modules.
The only thing I did was add a custom field for account number. Could it
have something to do with that? The permission level on the custom field is
0.
I am able to run the trial balance, which doesn't give me an error message,
which seems to display the same information.

I also tried creating another user. Same error. I havn't created any rules.
I checked access to all modules and roles.



On Mon, Apr 27, 2015 at 5:23 AM, Rushabh Mehta <notifications@github.com>
wrote:

> @fblauer <https://github.com/fblauer> Cannot replicate it. You can also
> remove permissions for System Administrator. Please check Role Permission
> Manager.
>
> Did you change any permission rules?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/frappe/erpnext/issues/3159#issuecomment-96581345>.
>



-- 
Fred Blauer CA, CPA, CISA
http://openacct.ca
514-667-1555

**Comment by nabinhait** [comment]
@fblauer Check if there is any circular loop in chart of accounts? And also try after saving all the root accounts.

**Comment by fblauer** [comment]
All I know is that its working now - no error message. I didn't do anything
here, so maybe you did something on your side?

On Tue, Apr 28, 2015 at 7:26 AM, Nabin Hait <notifications@github.com>
wrote:

> @fblauer <https://github.com/fblauer> Check if there is any circular loop
> in chart of accounts? And also try after saving all the root accounts.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/frappe/erpnext/issues/3159#issuecomment-97026062>.
>



-- 
Fred Blauer CA, CPA, CISA
http://openacct.ca
514-667-1555
