### ISSUE TITLE
BOM Tree Exploded

### ISSUE THREAD

**Issue by ruchin78** [frappe/erpnext#3162]
There should a report for BOM Tree Exploded, which should show all the components from 0 level BOM to last level and by looking at one report user can know which part of BOM is used in which sub-assembly and also which sub-assembly used in which Assembly of BOM etc.

**Comment by rmehta** [comment]
Dupicate of https://github.com/frappe/erpnext/issues/2807

@ruchin78 Please honour Issue Guidelines and don't raise duplicate issues.
