### ISSUE TITLE
Subcontracting receipt date is being set to "Today"

### ISSUE THREAD

**Issue by ishanloya** [frappe/erpnext#31653]
### Information about bug

Regardless of the selected posting date, the Subcontracting Receipt date is being reset to "Today"

### Module

other

### Version

ERPNext: v14.0.0-beta.6 (version-14-beta)
Frappe Framework: v14.0.0-beta.5 (version-14-beta)

### Installation method

manual install

**Comment by deepeshgarg007** [comment]
@ishanloya Please check on stable branches, beta branches are not supported
