### ISSUE TITLE
Material Request should be controlled for Minimum Order Quantity

### ISSUE THREAD

**Issue by ruchin78** [frappe/erpnext#3166]
While creating material request for purchase, whether the system should stop the user to create  material request as per minimum order quantity.

If system is not stopping the user for minimum order quantity at the time of material request then it should not stop the user while submitting the purchase order.

**Comment by rmehta** [comment]
The material requester does not need to worry about min order qty. Multiple requests can be clubbed for one PO

**Comment by ruchin78** [comment]
None of you understood the problem.

Umair from Web Technologies understand the problem well.

Problem is by generating Material Request using Production Planning Tool
with reference to Sales Order, you cannot create a purchase order by using
this these material request where minimum order quantity is mentioned in
the item master for the items mentioned in the material request. If you try
to create it the purchase order either you need to change the minimum order
quantity or either you need to increase the tolerance of the item otherwise
you cannot.

Therefore requesting you to please do not close any issue before
understanding it well.

What proof you want me to show you.

*Regards*
*Ruchin Sharma*
*ERP Specilist*
*miSport Manufacturing Pvt. Ltd.*
*+91 9718555281*
*skype id:ruchinsharmagur*

**Comment by nabinhait** [comment]
@ruchin78 

I have followed all the steps mention here and in #3147, system creates material requests adding extra row to honour MOQ. Then I have tried to create Purchase Order from that Material Request, it opens a new PO with all the rows. I can save and submit the PO without any problem.
Are you trying to club all the quantities in a single row in the PO or removing any rows before saving?
