### ISSUE TITLE
Payment terms not fetched in Sales Invoice, DN from order. Also not in PR from PO

### ISSUE THREAD

**Issue by nidhipurohit11** [frappe/erpnext#31668]
### Information about bug

As per this - https://github.com/frappe/erpnext/pull/26397 the payment terms should - 
- be fetched in PR from PI or PO
- be fetched in SI from SO or DN

Currently, if the payment term template is set in SO, then on creating SI/DN from this order the payment term template is not getting fetched. 

Same in the purchase cycle. 

### Module

accounts

### Version

ERPNext: v14.0.0-dev (HEAD)

Frappe Framework: v14.0.0-dev (HEAD)

### Installation method

FrappeCloud

**Comment by deepeshgarg007** [comment]
@nidhipurohit11 just checked and everything is working as expected.
PR and DN don't even have a Payment Terms Template field so fetching payment terms in them is not even possible. This is for cases where the Payment Terms are decided at order level based on order date and need to be fetched the same at invoice level which works as expected
