### ISSUE TITLE
PR >> PI, if currency exchange is changed in latter then also the item rate is not getting updated

### ISSUE THREAD

**Issue by nidhipurohit11** [frappe/erpnext#31663]
### Information about bug

While checking - https://github.com/frappe/erpnext/pull/25970

1. Created a PR with currency exchange at 80.01, the item rate is then $25. Submitted it.
2. Creating PI from this PR, and changing the currency exchange rate, the item rate in the child table is not getting updated according to changes in currency exchange. (If exchange rate is changed to 85, the item rate should also get updated)
3. Due to this, able to save the PI with the wrong rate. 

Expected - The item rate update should get triggered as soon as the currency exchange rate is updated. 

https://user-images.githubusercontent.com/82337328/180165484-6f91a038-0af7-4b6b-87ec-3c5c3f38e1e8.mov

### Module

accounts

### Version

ERPNext: v14.0.0-dev (HEAD)

Frappe Framework: v14.0.0-dev (HEAD)

### Installation method

FrappeCloud

**Comment by deepeshgarg007** [comment]
@nidhipurohit11 The rate of the item will still remain $25, changing the exchange rate will have no impact on it, it will just change the base amount in the company currency, again an invalid issue
