### ISSUE TITLE
How to write or update data in erpnext using curl?

### ISSUE THREAD

**Issue by prash4** [frappe/erpnext#3167]
Hello,

We are integrating it with magento we are almost done , only the the last step we are stuck 

Can you please tell us How to write or update data in erpnext using curl?

We have used the below 

curl -H "Content-Type: application/json" -X POST -d '{"subject":"xyz"}'https://demo.frappecloud.com/api/resource/Task/

Error while posting

Traceback (innermost last):
File "/home/frappe/press/benches/1504171238/apps/frappe/frappe/app.py", line 54, in application
response = frappe.api.handle()
File "/home/frappe/press/benches/1504171238/apps/frappe/frappe/api.py", line 98, in handle
data = json.loads(frappe.local.form_dict.data)
File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
return defaultdecoder.decode(s)
File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer

**Comment by pdvyas** [comment]
Please see the correct request structure from https://frappe.io/help/rest_api
Also, you'll have to login first.

I strongly suggest that you use something like [postman](https://chrome.google.com/webstore/detail/postman-rest-client/fdmmgilgnpjigdojojpjoooidkmcomcm?hl=en) to try out the API. 

For futher discussion, please post on https://discuss.frappe.io

**Comment by prash4** [comment]
We are using postman for api testing

Login is successful

Read API is working

On the write API I tried the example https://frappe.io/help/rest_api for CRUD create person and getting the below error.

Please can you telling me were we are going wrong ?

![804f971d02_650x500](https://cloud.githubusercontent.com/assets/6859203/7346006/dde06bf6-ecf7-11e4-86f5-82ea9e61f6f7.jpg)

**Comment by pdvyas** [comment]
I specifically asked you to post on https://discuss.frappe.io
