### ISSUE TITLE
Error on setting holiday reminder frequency 

### ISSUE THREAD

**Issue by yadavyk** [frappe/erpnext#31670]
### Information about bug

Reference : https://github.com/frappe/erpnext/pull/25735

Upon setting holiday reminder frequency under HR Settings --> Reminders section, an error is thrown 

![error on setting holiday reminder frequency](https://user-images.githubusercontent.com/32797974/180237250-9c260a1c-f643-450c-9ec1-d66f47a8794c.png)

### Module

HR

### Version

V14 beta2

**Comment by ruchamahabal** [comment]
Looks like the test site wasn't migrated properly so the scheduled job type didn't get created. Should be fine now. Reopen if issue persists
