### ISSUE TITLE
not able to create credit note /return with einvoice

### ISSUE THREAD

**Issue by rjbharath1003** [frappe/erpnext#31689]
### Information about bug

for sales return and credit note.
einvoice details getting carried to new form. 
needed below cs to make it work.
please do the needfull

frappe.ui.form.on('Sales Invoice', {
	onload: function(frm) {
 if(cur_frm.doc.name === cur_frm.doc.return_against + "-1")
	    {
	        
	    }
	    else{
          if(cur_frm.doc.is_return === 1)
         
        {
        cur_frm.set_value("irn","");
        cur_frm.set_value("ack_no","");
cur_frm.set_value("ack_date","");
}
    	       } 
    	       

### Module

accounts

### Version

ERPNext: v13.36.1 (version-13)

**Comment by maharshivpatel** [comment]
Please share the issue in detail and steps to reproduce it. preferably attach screenshots to convey your message and then if you know the solution raise Pull Requests against it.

How to : https://github.com/frappe/erpnext/wiki/Issue-Guidelines
