### ISSUE TITLE
Wrong Day Calculation of payment days for employee when I entered relieving date in employee master.

### ISSUE THREAD

**Issue by singh0834** [frappe/erpnext#31697]
### Information about bug

Wrong Day Calculation of payment days in the salary slip for the employee when I entered relieving date in employee master.

### Module

HR, other

### Version

Frappe Version 13

### Installation method

manual install

**Comment by ruchamahabal** [comment]
Closing as duplicate of https://github.com/frappe/hrms/issues/25
