### ISSUE TITLE
Accounts payable report showing sales and adjusting transactions having nothing to do with accounts payable

### ISSUE THREAD

**Issue by fblauer** [frappe/erpnext#3169]
![en_ap_rpt](https://cloud.githubusercontent.com/assets/1015215/7351686/c6451816-ecd4-11e4-8c61-72c9e8ee3f26.PNG)
Accounts payable report seems to have 2 problems:
It shows transactions other than AP as per attached
It is showing the detail of each transaction instead of the summary (like in the AR report, which is correct)
Shouldn't the AP report be similar to the AR one? 
![en_ar_rpt](https://cloud.githubusercontent.com/assets/1015215/7351745/1d89dca6-ecd5-11e4-9bef-20326921df3e.PNG)

**Comment by nabinhait** [comment]
fixed.
thanks for reporting.

**Comment by fblauer** [comment]
Thanks, but It hasn't changed on my instance. How long does it normally
take to see the change, or am I doing something wrong?

On Tue, Apr 28, 2015 at 7:16 AM, Nabin Hait <notifications@github.com>
wrote:

> Closed #3169 <https://github.com/frappe/erpnext/issues/3169>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/frappe/erpnext/issues/3169#event-291862358>.
>



-- 
Fred Blauer CA, CPA, CISA
http://openacct.ca
514-667-1555

**Comment by nabinhait** [comment]
Are you working on erpnext cloud instance? Then check it now.

**Comment by fblauer** [comment]
It works now. Thanks for the really fast response!

On Tue, Apr 28, 2015 at 7:53 AM, Nabin Hait <notifications@github.com>
wrote:

> Are you working on erpnext cloud instance? Then check it now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/frappe/erpnext/issues/3169#issuecomment-97033993>.
>



-- 
Fred Blauer CA, CPA, CISA
http://openacct.ca
514-667-1555
