### ISSUE TITLE
Journal entry against invoices not updating outstanding amount

### ISSUE THREAD

**Issue by ishanloya** [frappe/erpnext#31701]
### Information about bug

Sometimes when a sales invoice is paid using a journal entry, the outstanding amount doesn't get updated. Moreover, when the linked Journal Entry is cancelled, the invoice gets updated with the reverse entry.

So, for e.g. if an invoice amount is Rs. 3,000, on JV submission outstanding amount remains Rs. 3,000. When the JV is cancelled, the outstanding amount becomes Rs. 6,000 and the sales invoice needs to be cancelled and the whole process needs to be repeated.

### Module

accounts, selling

### Version

ERPNext: v14.0.0-beta.6 (version-14-beta)
Frappe Framework: v14.0.0-beta.5 (version-14-beta)
India Compliance: v0.0.1 (develop)

### Installation method

manual install

**Comment by ishanloya** [comment]
I can confirm that this issue arose twice. In both cases, I had renamed the journal entry after submission. I wonder if this had something to do with the linking of the GL entry with the journal entry since as per my understanding the GL entries are renamed later. 

If so, maybe we need to restrict journal entry renaming somehow until the linked GL Entry renaming is completed?

**Comment by ishanloya** [comment]
Same thing is happening with purchase invoices paid via journal entries as well. Even when the journal entry isn't renamed, the issue is still present. Seems to be happening randomly.

**Comment by Olawale1** [comment]
We had previously encountered the issue with Invoices not getting update via JV... thought it was fixed. Hope this can be resolved soon

**Comment by deepeshgarg007** [comment]
@ishanloya This should be resolved now, please check on stable branches again
