### ISSUE TITLE
Translations do not work in menus and on desk

### ISSUE THREAD

**Issue by kressi** [frappe/erpnext#3170]
Unfortunately, I do not know whether this is a frappe or erpnext issue. But in different places, the translation does not work since I updated to V5.0.

On desk only the translation 'Alle Anwendungen' is translated to german.
![desk](https://cloud.githubusercontent.com/assets/3862960/7354665/212afeb0-ed1d-11e4-951a-2f547a428e21.png)

Inside menu and open tasks, nothing is translated.
![menu](https://cloud.githubusercontent.com/assets/3862960/7354668/242d6828-ed1d-11e4-8dfe-3535d74bba6b.png)
![tasks](https://cloud.githubusercontent.com/assets/3862960/7354672/26abc996-ed1d-11e4-8f46-e6c0fa35eac2.png)

**Comment by rmehta** [comment]
fixed. Thanks for reporting
