### ISSUE TITLE
Not able to record the Purchases Invoice in Version 14 Beta 6 as getting the Error as GST Category is a Mandatory Fields

### ISSUE THREAD

**Issue by tailorraj** [frappe/erpnext#31719]
### Information about bug

While recording the Purchase Invoice we are getting the below error and also we have done all the checklist in the Customer Masters and also in the GST Settings we have defined the GST Category but still it is giving the error

![image](https://user-images.githubusercontent.com/30833692/181423473-a9ff25b4-04e1-404d-b7b2-f72f0dfb4acd.png)

### Module

buying

### Version

![image](https://user-images.githubusercontent.com/30833692/181423535-9587cfe1-3dea-4dc4-8bae-6c585c146c3e.png)

**Comment by deepeshgarg007** [comment]
@tailorraj This was caused via the India Compliance app, this should be resolved now, closing this issue
