### ISSUE TITLE
Gross Profit PDF and Print Issue 

### ISSUE THREAD

**Issue by meenara14** [frappe/erpnext#31718]
### Information about bug

I found a bug in the PDF and Print option in ERPNext Gross Profit Report. There is issue an issue with the js file.  I  made few changes in the js file then it's working now. These are the changes that I made in "/frappe-bench/apps/erpnext/erpnext/accounts/report/gross_profit/gross_profit.js" file:

Thanks
![grossprofiIssue](https://user-images.githubusercontent.com/102170258/181292707-ae7113f3-3883-4fb9-8b04-77b30f9e12df.jpg)

### Module

accounts

### Version

ERPNext: v13.34.1 (development)

Frappe Framework: v13.33.1 (development)

### Installation method

manual install

**Comment by meenara14** [comment]
Hi,
When I click on the print screen then new window opens but there is no option to print the report. Do you have any idea?

**Comment by Solufyin** [comment]
https://github.com/frappe/erpnext/pull/31721#issuecomment-1198872599

**Comment by meenara14** [comment]
Hi,
Thank you for the quick response. There is no need to press ctrl+p for print, now it will automatically print when you click print :)
Here is the code you can put it in this file : /frappe-bench/sites/assets/frappe/js/frappe/microtemplate.js

![image](https://user-images.githubusercontent.com/102170258/181788650-a8d4a7d9-5204-4532-93fa-e34037062af5.png)


Thanks,
Meena

**Comment by meenara14** [comment]
> [#31721 (comment)](https://github.com/frappe/erpnext/pull/31721#issuecomment-1198872599)

Hi,
Thank you for the quick response. There is no need to press ctrl+p for print, now it will automatically print when you click print :)
Here is the code you can put it in this file : /frappe-bench/sites/assets/frappe/js/frappe/microtemplate.js
![image](https://user-images.githubusercontent.com/102170258/181788835-38349356-2c7b-4198-bfcf-134a38ba068a.png)



Thanks,
Meena

**Comment by Solufyin** [comment]
Hi @meenara14,

The issue has been resolved by #31756
Please closed the issue.

Thank You!

**Comment by meenara14** [comment]
resolved
