### ISSUE TITLE
GPL copyright  Requirements

### ISSUE THREAD

**Issue by enyachoke** [frappe/erpnext#3173]
This is a quick one to really understand my obligations under the gnu licence. If a create a spin off of erpnext in another language lets say php. While keeping the the user interface and functionality exactly the same. I believe that is copying and am tied by the requirements of the GPL licence.

**Comment by rmehta** [comment]
I think keeping exactly the same UI / API. 

But does not sound like a very good plan to me to re-write it. What is the reason?

**Comment by enyachoke** [comment]
Just trying to recreate it for practice. Anyway on collapsing nested forms into a table like in journal voucher. I understand it is a javascript thing but I can't figure it out.
