### ISSUE TITLE
Global System Settings overwrite Currency format

### ISSUE THREAD

**Issue by blewsky** [frappe/erpnext#31754]
### Information about bug

In a multi-currency/multi-company setup, there might exist the need for differing currency format settings. Currently, the global number format overwrites the currency format rendering the currency format unusable. 
Example:
This is the setting in the currency doctype:
<img width="496" alt="image" src="https://user-images.githubusercontent.com/87971956/182183029-271dfde2-807a-4f35-8f39-06940e8607f6.png">
This is the setting in "System Settings":
<img width="506" alt="image" src="https://user-images.githubusercontent.com/87971956/182183339-770993e0-8725-411f-888c-22120b27eff8.png">
No currency precision is set in the global settings:
<img width="499" alt="image" src="https://user-images.githubusercontent.com/87971956/182186241-862178b4-0412-49ef-9177-338c18f26d1b.png">
The resulting formatting still features the decimals although a different setting (no decimals) has been set in the currency doctype:
<img width="63" alt="image" src="https://user-images.githubusercontent.com/87971956/182183593-a1f25db5-9702-41fc-978b-bfc32ddf5c43.png">

### Module

accounts

### Version

ERPNext: v13.36.2 (HEAD)
Frappe Framework: v13.36.3 (HEAD)

### Installation method

FrappeCloud

**Comment by Nihantra-Patel** [comment]
Hi @blewsky,

Please check it.

https://github.com/frappe/frappe/blob/91789ed9d1b687d5db363ac51ca39030caa9ee90/frappe/public/js/frappe/form/formatters.js#L131
```
docfield.precision || frappe.boot.sysdefaults.currency_precision || 2
```

If you haven't set "Currency Precision" then it's take a 2. and it's not a bug.

We no longer provide support for version 13 or older. 

Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!

**Comment by blewsky** [comment]
This bug is still valid in my opinion and the ticket should be, thus, reopened.
By now, I am on 
- ERPNext: v14.61.3 (HEAD)
- Frappe Framework: v14.64.0 (HEAD)

Still the same behavior as described. Maybe my old bug report was not clear enough. This is only relevant in a multi-currency setup with currencies that use different number formats. Currently, this is not configurable in ERPnext. E.g. there could be a setup for company that uses one of the following currencies that don't have subunits:

- Afghan afghani
- Albanian lek
- Algerian dinar
- Armenian dram
- Belarusian ruble
- Burundian franc
- Cambodian riel
- Cape Verdean escudo
- Central African CFA franc
- CFP franc
- Chilean peso
- Colombian peso
- Comorian franc
- Costa Rican colón
- Czech koruna
- Djibouti franc
- Dominican peso
- Guinean franc
- Guyanese dollar
- Hungarian forint
- Icelandic króna
- Indonesian rupiah
- Iranian rial
- Japanese yen
- Kazakhstani tenge
- Lao kip
- Macedonian denar
- Mauritian rupee
- Mongolian tögrög
- New Taiwan dollar (has a rarely used half dollar coin)
- Norwegian krone
- Pakistani rupee
- Paraguayan guaraní
- Rwandan franc
- São Tomé and Príncipe dobra
- Serbian dinar
- Sierra Leonean leone
- South Korean won
- Syrian pound
- Tanzanian shilling
- Ugandan shilling
- Uruguayan peso
- Uzbekistani som
- Vanuatuan vatu
- Vietnamese dong
- West African CFA franc
- Yemeni rial

Additionally, the company exports their products and bills in USD. The USD value need to be stated in the forma #,###.## but the other currency in #,###. Currently, this is not possible to configure in ERPnext.

**Comment by Nihantra-Patel** [comment]
Hi @blewsky,

Basically, if you choose to set the "Currency Precision" to 3 in ERPNext's System Settings, it will apply to all transactions. But if you don't set the precision, it will default to 2. I've already provided the code and explained how it operates.

More clarity for, you can share the video, and if a feasible feature or bug then we will report it.

Thank You!

**Comment by blewsky** [comment]
Hi @Nihantra-Patel,
Thank you for your response. Yes, I understand your point and also checked the code. There is nothing wrong with it. I do not want to change a global setting but I am talking about the number format for specific currencies. The issue that I reported is that currently ERPnext is not able to handle two different sets of precisions (for different currencies). One can set a number format in the currency doctype but it doesn't take effect. The global currency precision you referred to is interesting but not really relevant here, since it changes the precision of all currencies. This is a bug IMO which I assume will affect several users who operate in an international setting with any of the currencies above.
