### ISSUE TITLE
Automatically Posting Depreciation

### ISSUE THREAD

**Issue by Twiga79** [frappe/erpnext#31753]
### Information about bug

Despite ticking the box " Books asset depreciation automatically " on the settings page,
Depreciation is not automatically posting as I have to do manual journals. Please assist.

### Module

assets

### Version

ERPNext: v13.27.0 (version-13)

ERPNext Support: v0.2.1 (master)

Frappe Framework: v13.26.1 (version-13)

**Comment by anandbaburajan** [comment]
@Twiga79 are you still facing the issue? If yes, can you share the steps to reproduce this issue with some example data?
