### ISSUE TITLE
Could not find app "payments" when install erpnext-v14

### ISSUE THREAD

**Issue by j209** [frappe/erpnext#31769]
### Information about bug

Could not find app "payments" when install erpnext manually

![image](https://user-images.githubusercontent.com/18129232/182561819-4722bc80-ece8-466b-90de-6e416e44e25b.png)

### Module

accounts

### Version

frappe 14.0
erpnext 14.0

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Could not find app "payments"
```

**Comment by tuphuc** [comment]
same to me

**Comment by erpwala** [comment]
Alternative Solutions for this, Download app payments

And install it on site

**Comment by Jishnu-Epics** [comment]
same issue

**Comment by dineshliyanage0** [comment]
Same issue here.

**Comment by mohsinalimat** [comment]
Before install erpnext in your site, you have to install payments app in your site.

**Comment by linuxipho** [comment]
Hi, do `bench get-app payments` before `install-app erpnext` in your site.

**Comment by hamzamgit** [comment]
Receiving this after installing payments app to bench

`bench --site <site> install-app erpnext `

```
Traceback (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 413, in install_app
    _install_app(app, verbose=context.verbose, force=force)
  File "apps/frappe/frappe/installer.py", line 265, in install_app
    install_app(required_app, verbose=verbose, force=force)
  File "apps/frappe/frappe/installer.py", line 288, in install_app
    add_module_defs(name, ignore_if_duplicate=force)
  File "apps/frappe/frappe/installer.py", line 608, in add_module_defs
    d.insert(ignore_permissions=True, ignore_if_duplicate=ignore_if_duplicate)
  File "apps/frappe/frappe/model/document.py", line 268, in insert
    self.db_insert(ignore_if_duplicate=ignore_if_duplicate)
  File "apps/frappe/frappe/model/base_document.py", line 526, in db_insert
    raise frappe.DuplicateEntryError(self.doctype, self.name, e)
frappe.exceptions.DuplicateEntryError: ('Module Def', 'Payments', IntegrityError(1062, "Duplicate entry 'Payments' for key 'PRIMARY'"))

```

**Comment by hamzamgit** [comment]
can be solved using 
`bench --site <site> reinstall`

**Comment by jensonmala** [comment]
bench get-app payments

bench get-app hrms

bench update --reset

bench --site *sitename* install-app hrms

bench --site *sitename* install-app payments

bench --site *sitename* migrate

**Comment by jensonmala** [comment]
bench get-app payments

bench get-app hrms

bench update --reset

bench --site *sitename* install-app hrms

bench --site *sitename* install-app payments

bench --site *sitename* migrate

sudo service supervisor restart

sudo service nginx restart

**Comment by MicroEvan** [comment]
login to github on you command line. Use the following command:
gh auth login

......................................
If you don't have gh install gh first. Login and then do 

bench get-app payments

..................................
Should work

**Comment by ankush** [comment]
Payments app is not a hard dependency anymore. So this shouldn't be a problem.
