### ISSUE TITLE
I'm not sure why i cannot get the project id when i create a PO from connections of a project  

### ISSUE THREAD

**Issue by Xuquansheng** [frappe/erpnext#31760]
### Information about bug

get project id like SO

### Module

projects

### Version

ERPNext 13 & 14

### Installation method

docker

**Comment by dj12djdjs** [comment]
As you can see in the GIF, project is linking with PO just fine. The reference is stored in the items table.

![test-project](https://user-images.githubusercontent.com/29856401/182481305-773ebfcc-b33f-4e0e-a145-739670b9044c.gif)

**Comment by Xuquansheng** [comment]
Your pic is showing correct from PO point of view, having correct project id link and item based project id, as i can get these ids like you. but, when you come back to the project connections, POs connections is not correct as SOs connections.

![图片](https://user-images.githubusercontent.com/82086188/182494822-2ebea1b9-19e7-4265-92b3-b49a42349fec.png)

**Comment by Xuquansheng** [comment]
I checked Accounting Dimensions on PO, there are two accounting dimenstion, one is PO wise, another item wise. I need PO wise which is empty now,unlike SO.
![图片](https://user-images.githubusercontent.com/82086188/182496873-f5fcb17b-0872-488e-be59-7c945a1597f0.png)

**Comment by deepeshgarg007** [comment]
Fixed Via: https://github.com/frappe/erpnext/pull/32244

**Comment by Xuquansheng** [comment]
I've tested official latest docker images, v14 is OK, while v13 is not.
