### ISSUE TITLE
Stock in simplied chinese should be "库存“， not ”股票”

### ISSUE THREAD

**Issue by Xuquansheng** [frappe/erpnext#31775]
### Information about bug

All of words "Stock" should be translated into "库存“， not "股票“

### Module

stock

### Version

ERPNext 13 & 14
![图片](https://user-images.githubusercontent.com/82086188/182633525-07b96742-57f1-4cb3-a39b-811ef876071b.png)

### Installation method

docker

**Comment by gn306029** [comment]
Hi, @Xuquansheng , translation files are mostly created using machine translation like google translate.
Maybe you can update translate and create the pull request for Simplified Chinese.
This is simplified chinese translation file.
https://github.com/frappe/erpnext/blob/develop/erpnext/translations/zh.csv

If you want using custom translate file, you can create a new app and make translate file in app_folder/translations.
Then install it for your site. now translate will be overwrite.

**Comment by deepeshgarg007** [comment]
@gn306029 You can add a custom translation for yourself else you can also raise a PR if you want to improve this
