### ISSUE TITLE
[Gross Profit Report] Wrong calculation of buying amount

### ISSUE THREAD

**Issue by rtdany10** [frappe/erpnext#31786]
### Information about bug

Purchase Invoice:
![image](https://user-images.githubusercontent.com/52111700/183244857-85f8d606-e5d8-4853-b010-11558a792f2a.png)

Sales Invoice:
![image](https://user-images.githubusercontent.com/52111700/183244912-8921292b-79fc-4010-a94d-a3e1033fdf82.png)

Delivery Note:
![image](https://user-images.githubusercontent.com/52111700/183245022-e15fd21a-6bd2-4ee9-978d-4b87ad5f15dd.png)

So far,
We know that buying amount is 900, the selling amount is 100,000. So, the gross profit is 100,000 - 900 = 99,100.
But as per ERPNext's Gross Profit report, it is only 99,000(attached video for ref).

https://user-images.githubusercontent.com/52111700/183245282-30fd91c9-38aa-4c76-9e6d-630fa32550dd.mp4

### Module

accounts

### Version

ERPNext: v13.36.2 (HEAD)
Frappe Framework: v13.36.3 (HEAD)

### Installation method

FrappeCloud

**Comment by ruthra-kumar** [comment]
@rtdany10 
I wasn't able to replicate the issue. Creating the same kind of test data gives me the correct output of 99100 in gross profit.
<img width="1186" alt="Screenshot 2022-08-17 at 4 13 54 PM" src="https://user-images.githubusercontent.com/3272205/185100190-3f7f9144-79be-4bf8-9e58-d383c0d52b15.png">

What is the Stock Ledger posting for the Purchase Invoice? Can you post a screenshot?

**Comment by rtdany10** [comment]
In your case, the valuation rate is 9, which isn't my case. Did you exactly replicate the test data including two warehouses?

> What is the Stock Ledger posting for the Purchase Invoice? Can you post a screenshot?

https://user-images.githubusercontent.com/52111700/185105480-03de75fe-99d2-4daa-8f56-cbe01538b294.mp4

**Comment by rtdany10** [comment]
> In your case, the valuation rate is 9, which isn't my case. Did you exactly replicate the test data including two warehouses?

@ruthra-kumar The way ERPNext calculates buying amount is valuation rate times qty, which isn't really accurate at all. Please find the video regarding stock ledger entries of the purchase invoice.

**Comment by ruthra-kumar** [comment]
@rtdany10 
Multiple warehouses wasn't mentioned in the original post and isn't clear from the screenshots as well. But, I am able to replicate with that now.
<img width="1186" alt="Screenshot 2022-08-17 at 6 56 37 PM" src="https://user-images.githubusercontent.com/3272205/185349091-2a12f1f3-944f-47a6-b248-642d668539df.png">

Depending on how you order the items in the Purchase Invoice, you can get a valuation rate of '0' as well, which is incorrect.
<img width="1186" alt="Screenshot 2022-08-17 at 6 55 25 PM" src="https://user-images.githubusercontent.com/3272205/185349102-96c9d1e3-8b57-4ceb-ac5b-751470c1fa4f.png">

Report picks the last SLE to determine buying amount. In this case, since the items are stocked in different warehouses, multiple SLE's are posted and the Gross Profit report picks the last one, which varies depending on their order in Purchase Invoice.

Ideally, it should get the average buying amount from the whole transaction(Purchase Invoice).

**Comment by rtdany10** [comment]
> @rtdany10 Multiple warehouses wasn't mentioned in the original post and isn't clear from the screenshots as well. But, I am able to replicate with that now. 

My bad, should've given a better description. Thank you for validating tho :)

> Depending on how you order the items in the Purchase Invoice, you can get a valuation rate of '0' as well, which is incorrect.

Gross Profit is a highly required and sensitive report and values like these in the report just makes it completely useless.

> Ideally, it should get the average buying amount from the whole transaction(Purchase Invoice).

Average buying amount isn't the answer. Suppose I bought 2 qty of same item, one free of cost and other at 10INR. My average buying rate is 5INR. I sold my FOC item at 30INR, and my profit is 30INR, but the report will show 25INR. In the long run, when all items are sold out, the figures will add up, but until then report will show inaccurate values, and gross profit report isn't something that you want with inaccurate figures.

Also consider this scenario, after selling the FOC item, my actual profit is 30INR, the report shows 25INR. Now after a while, my other item gets expired, taking away my ability to sell it. In such cases, the gross profit won't add up in the long run as well.

I suggest to not show the gross profit of stock items that aren't yet delivered. You really haven't made a profit until the items are issued out of stock. And then use the actual incoming rate of the delivered items to calculate the buying amount.
@ruthra-kumar

**Comment by MinaSafwatWDX** [comment]
We are facing same issue, is there a resolution yet?

**Comment by ruthra-kumar** [comment]
> Average buying amount isn't the answer. Suppose I bought 2 qty of same item, one free of cost and other at 10INR. My average buying rate is 5INR. I sold my FOC item at 30INR, and my profit is 30INR, but the report will show 25INR. In the long run, when all items are sold out, the figures will add up, but until then report will show inaccurate values, and gross profit report isn't something that you want with inaccurate figures.

> Also consider this scenario, after selling the FOC item, my actual profit is 30INR, the report shows 25INR. Now after a while, my other item gets expired, taking away my ability to sell it. In such cases, the gross profit won't add up in the long run as well.

Not necessarily. Average buying amount is calculated on the valuation method maintained either at item master or at stock settings. If you have `Moving Average` valuation method, then 5 INR as buying amount and 25 INR as profit is correct. I presumed moving average as valuation method here since you mentioned 5 INR.

> I suggest to not show the gross profit of stock items that aren't yet delivered. You really haven't made a profit until the items are issued out of stock. And then use the actual incoming rate of the delivered items to calculate the buying amount.

This won't work for non-delivery based items.

**Comment by rtdany10** [comment]
> This won't work for non-delivery based items.

Service items? Buying rate for service items are 0 so it shouldn't be an issue?

**Comment by rtdany10** [comment]
@ruthra-kumar why remove the valid label? :thinking:

**Comment by ruthra-kumar** [comment]
> Service items? Buying rate for service items are 0 so it shouldn't be an issue?

Not because of the buying rate, rather it would make the report more rigid if delivery note is a must for each invoice.

> why remove the valid label?

Based on my testing, report does calculate buying rate correctly based on the valuation method. You can ignore my earlier comment about using the average rate from whole transaction. I overlooked the item valuation method on my testing.
Report did calculate the right buying amount based on the Valuation method(FIFO).

**Comment by ruthra-kumar** [comment]
Closing the ticket as the Buying amount is calculated based on Valuation method.

**Comment by rtdany10** [comment]
> Report picks the last SLE to determine buying amount. In this case, since the items are stocked in different warehouses, multiple SLE's are posted and the Gross Profit report picks the last one, which varies depending on their order in Purchase Invoice.

@ruthra-kumar isn't this still valid and a bug?

**Comment by ruthra-kumar** [comment]
Can you clarify which part you think is a bug?
Is it the multiple SLE's for the stock entry? or Is it about the buying amount calculation for that item? (For this the report is working as expected - based on valuation method as mentioned in earlier comment)

**Comment by rtdany10** [comment]
This is my delivery note:
![image](https://user-images.githubusercontent.com/52111700/195513265-519cbd21-b3c9-4309-a7ba-54862c89dd6f.png)

This is it's accounting ledger:
![image](https://user-images.githubusercontent.com/52111700/195513444-6cbca824-fcaf-49eb-abac-5c52d7d573e9.png)

This is the GP report:
![image](https://user-images.githubusercontent.com/52111700/195513688-4ceb8e20-0af8-4eac-838f-c6911b63638c.png)

Cost of Goods Sold was debited 200, Buying Amount here shows 152.6316.
Both these entries should have same value ideally.

@ruthra-kumar

**Comment by ruthra-kumar** [comment]
What is the Valuation method maintained in Stock settings?

**Comment by rtdany10** [comment]
> What is the Valuation method maintained in Stock settings?

FIFO in Stock Settings, None inside Item.

**Comment by ruthra-kumar** [comment]
What is the buying rate for that Item? Can you post the stock ledger entries for that Item?

**Comment by rtdany10** [comment]
SLE of that particular item:
![image](https://user-images.githubusercontent.com/52111700/195761190-9fca8ed8-8844-440e-b6b1-4a8bff9a1c8d.png)

@ruthra-kumar

**Comment by ruthra-kumar** [comment]
It would be helpful if you could post Stock Ledger posting up to Delivery Note MAT-DN-2022-00062 for the concerned item.

**Comment by rtdany10** [comment]
> It would be helpful if you could post Stock Ledger posting up to Delivery Note MAT-DN-2022-00062 for the concerned item.

![image](https://user-images.githubusercontent.com/52111700/195764280-49df79a9-815b-4053-86e6-fe14c6273314.png)

These are the total SLEs, nothing else.
@ruthra-kumar

**Comment by ruthra-kumar** [comment]
This is not replicable.

The same scenario works properly on my local setup.
Simulating same buying and selling:
<img width="1312" alt="Screenshot 2022-10-14 at 10 45 12 AM" src="https://user-images.githubusercontent.com/3272205/195768021-7ed72847-f2e5-42fd-a63f-78f131692150.png">


Delivery Note and GL entries: 
<img width="1286" alt="Screenshot 2022-10-14 at 10 46 20 AM" src="https://user-images.githubusercontent.com/3272205/195767899-57e4d6d1-e270-4b9f-8336-af2fa877839e.png">
<img width="1312" alt="Screenshot 2022-10-14 at 10 46 02 AM" src="https://user-images.githubusercontent.com/3272205/195767918-dde94da3-5c81-40ee-a81f-cd3673fcc568.png">

Gross Profit for the Invoice created from DN:
<img width="1286" alt="Screenshot 2022-10-14 at 10 46 52 AM" src="https://user-images.githubusercontent.com/3272205/195768182-5b9e2b6e-cd95-457b-9035-7efbc3b2bd72.png">

**Comment by rtdany10** [comment]
I was able to replicate this on a fresh server. The item has batch enabled, although I don't think it's a factor.
ERPNext: v13.39.4 (HEAD)
Frappe Framework: v13.41.4 (HEAD)

SLEs:
![image](https://user-images.githubusercontent.com/52111700/195812483-2443c8df-7f80-4155-a7d8-fd0f5b2b030b.png)

Accounting Ledgers:
![image](https://user-images.githubusercontent.com/52111700/195812615-a28f935a-8df3-4b19-a706-a12dad7de437.png)

GP Report:
![image](https://user-images.githubusercontent.com/52111700/195812742-d768657e-4a8d-4d5f-8e90-673757bbe4c1.png)
