### ISSUE TITLE
Print Format Builder - Error message when revisit Print Preview

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#3180]
Attached is the error message encountered when I opened Sales Order. I have set Print Format created via print Format builder set as Default Print Format.

![screen shot 2015-04-28 at 6 45 15 pm](https://cloud.githubusercontent.com/assets/910238/7371206/ec4b826c-eddc-11e4-97c9-0e51f010ca81.png)

**Comment by rmehta** [comment]
cannot replicate
