### ISSUE TITLE
general ledger give wrong results

### ISSUE THREAD

**Issue by citybirdman** [frappe/erpnext#31824]
### Information about bug

when i use the filter "group by voucher (consolidated)" with check on "consider Accounting Dimentions" then it gives me wrong results although the gl entries are all right 
and it gives me the right reults in the following acts:
1- use any group filter except "group by voucher (consolidated)"
2- filter results by the project if gl entries are linked to projects
the matter with this group option "group by voucher (consolidated)" is because it is useful than the other group options
but now it is giving a wrong results on a wrong date or wrong account
second thing which is not common is that the party is shown in the "against account" column that is wrong because whenever i filter by party in the search it won't give the right results to because all records that their party are shown in the "against account" will disappear when i make the filter

### Module

accounts

### Version

frappe version: v13.21.0 production
erpnext version: v13.21.0 production

### Installation method

manual install

**Comment by deepeshgarg007** [comment]
@citybirdman Can you please explain with some screenshots and reopen, right now its hard to understand the exact issue
