### ISSUE TITLE
Website portal issues

### ISSUE THREAD

**Issue by vbartosik** [frappe/erpnext#31833]
### Information about bug

Web portal not displaying sidebar.

After loggin in with website user (I tried Customer), the sidebar is not visible in Portal. I can access i.e. customers /quotations directly but the sidebar is not loading, so it is not possible to get there without manual typing of URL.

Also the profile of the user is not updateable for some reason.

### Module

other

### Version

Frappe version - 14.0.2
ERPnext version - 14.0.0

### Installation method

manual install

**Comment by GursheenK** [comment]
> Web portal not displaying sidebar.

Fixed in https://github.com/frappe/frappe/pull/21703

> Also the profile of the user is not updateable for some reason.

Tried replicating this issue. The form appears to be editable after clicking the **Edit Response**  button and saving the changes. Can you please provide more info for the case when it fails?

**Comment by Nihantra-Patel** [comment]
Kindly upgrade to version 14 or 15, then refresh and check again because lots of bugs fixed in the new version.

Everything is working fine. No problems were encountered in the latest versions 14 and 15.
