### ISSUE TITLE
Translate

### ISSUE THREAD

**Issue by listicos** [frappe/erpnext#3183]
![captura de pantalla 2015-04-28 a las 20 34 41](https://cloud.githubusercontent.com/assets/4566677/7383503/29abd824-ede6-11e4-8431-697a259642b5.png)
There are some words that are not found to translate like the image.

**Comment by rmehta** [comment]
We have a solution for this - hoping this will be fixed soon @pdvyas

**Comment by rmehta** [comment]
fixed

**Comment by listicos** [comment]
Hi, I just update and I see the same error with some numbers, like the attach.
Regards!

![captura de pantalla 2015-06-11 a las 0 06 13](https://cloud.githubusercontent.com/assets/4566677/8100163/8cf85c5a-0fcd-11e5-9c03-881bfaa3d825.png)
![captura de pantalla 2015-06-11 a las 0 09 40](https://cloud.githubusercontent.com/assets/4566677/8100188/e9bcdc86-0fcd-11e5-8e5f-67a5ea332503.png)
