### ISSUE TITLE
Asset Sale Process

### ISSUE THREAD

**Issue by dhawal-mahajan** [frappe/erpnext#31836]
### Information about bug

On submission of Sales Invoice for Sale of Asset, A JV for Depreciation is passed. The Depreciation amount should Ideally be the pro-rata depreciation amount for the last depreciation date and disposal date. But the automatic JV passed on sale of asset passes a Depreciation A/c to Accumulated Depreciation A/c entry for a higher amount. This results in Accumulated Depreciation for the asset to be higher than the Purchase Price of Asset. This also distorts the 'Gain(Loss) on Asset Disposal'. Also, the asset status is updated to 'Fully Depreciated' instead of 'Sold'. 

### Module

assets

### Version

ERPNext: v13.34.1
Frappe Framework: v13.33.1

### Installation method

manual install

**Comment by thida-bcn** [comment]
we are facing same issue

**Comment by anandbaburajan** [comment]
@dhawal-mahajan @thida-bcn can you provide some details ([example](https://github.com/frappe/erpnext/issues/31600#issue-1305302697)) to reproduce the issue? Maybe a GIF screencast too with sample data?

**Comment by anandbaburajan** [comment]
@deepeshgarg007 looks like this is same as the issue which https://github.com/frappe/erpnext/pull/32226 is solving?

**Comment by anandbaburajan** [comment]
> Also, the asset status is updated to 'Fully Depreciated' instead of 'Sold'.

@dhawal-mahajan does the asset have `maintenance_required` set?

**Comment by thida-bcn** [comment]
> depreciation

we will provide very soon with latest version
