### ISSUE TITLE
Wrong breadcrumb module for selling DocTypes

### ISSUE THREAD

**Issue by Jimmy-Newtron** [frappe/erpnext#31831]
### Information about bug

![image](https://user-images.githubusercontent.com/24460646/184165207-f8510f7c-f1d0-4eec-9f1e-4115dee0699f.png)

### Module

selling

### Version

Frappe 14.0.0
ERPNext 14.0.0

### Installation method

docker

### Relevant log output / Stack trace / Full Error Message.

```shell
As you can see in the image the breadcrumb shows the wrong module (Retail) for DocTypes that are part of the Selling module.

When clicking on the module name we go to the wrong URL of retail app
```

**Comment by trustedcomputer** [comment]
I am also seeing this behavior in a manual install upgraded from v13 to v14 on Ubuntu 22.04. Customer, Quotation, and Sales Order are all under the retail breadcrumb, which is not enabled (and never has been) in my install. They should all be under selling.
![Customer](https://user-images.githubusercontent.com/75872475/186033479-b2c05e8d-decc-46c9-9874-ab7036545c4a.png)
![Quotation](https://user-images.githubusercontent.com/75872475/186033483-bd452913-f560-42f6-8249-dfce6981ab59.png)
![Sales Order](https://user-images.githubusercontent.com/75872475/186033486-69d2763f-90b5-484d-bab8-f88ea4ba09ce.png)
![Selling](https://user-images.githubusercontent.com/75872475/186033611-def9fe9c-fcdf-46ca-b3d0-bd816b6fa5d0.png)

**Comment by icnbing** [comment]
This is my case. I have the same problem. Newly installed.
![image](https://user-images.githubusercontent.com/50577371/216669299-ae0034b0-1703-492e-8b73-b59bc7349a3b.png)

**Comment by rtdany10** [comment]
Getting the same

**Comment by trustedcomputer** [comment]
@deepeshgarg007 I believe this could be solved by backporting this [PR ](https://github.com/frappe/frappe/pull/20529) to version-13.

**Comment by ankush** [comment]
Fixed on v14 https://github.com/frappe/frappe/pull/20529
