### ISSUE TITLE
Stock entry not work for issuance the expired products

### ISSUE THREAD

**Issue by dufani1** [frappe/erpnext#31855]
Hello,
Stock entry not work for issuance the expired products.
How can dispos the expired products from system.
![11133](https://user-images.githubusercontent.com/23026263/184822770-f5706e2c-76d8-471e-a534-cfdc6fdab25f.jpg)

**Comment by rohitwaghchaure** [comment]
Fixed https://github.com/frappe/erpnext/pull/31863
