### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0) : Bug in POS 

### ISSUE THREAD

**Issue by Hafnianusha** [frappe/erpnext#31854]
![Screenshot from 2022-08-12 18-46-58](https://user-images.githubusercontent.com/100829201/184834367-7b6c390b-6337-47f5-bf64-5f915d586d76.png)
### Information about bug

After selecting item in Point of sale and Clicking button 'Check out' , Pop up message showing error
 "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0) "  and then  POS invoices are not submitting , it going to Draft mode

### Module

selling

### Version

ERPNext: v13.36.3 (HEAD)
Frappe Framework: v13.37.0 (HEAD)

**Comment by imadelakhaldev** [comment]
Hello,
I am facing the same problem, with the same output and error message, using POS AWSOME.

**Comment by fadilsiddique** [comment]
Gettin same error while checking out the items from pos

**Comment by AliShaatani** [comment]
Same Error

**Comment by deepeshgarg007** [comment]
Cannot replicate
