### ISSUE TITLE
Hello can i show here a calendar view fetched from patient appiontments ? 

### ISSUE THREAD

**Issue by Abdo2021-a** [frappe/erpnext#31859]
### Information about bug

![1](https://user-images.githubusercontent.com/82307815/184996543-a9a5d102-64e6-4086-b494-a1f2f5583485.png)

### Module

other

### Version

frappe 14 
erpnext 14

**Comment by deepeshgarg007** [comment]
@Abdo2021-a Please use discuss.erpnext.com for such queries
