### ISSUE TITLE
E-invoice import error

### ISSUE THREAD

**Issue by balabofficial** [frappe/erpnext#31876]
### Information about bug

When import xml e-invoice the quantity is not correct, there is an issue on for cicle but we try to solve without results

### Module

regional

### Version

14

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
No error on log
```

**Comment by balabofficial** [comment]
hi, I discovered the bug: the variables in file "import_supplier_invoice.py" are out of the loop and if the logic does not enter in this if:

`if rate and flt(line_total) / rate != 1.0 and line.find("Quantita"):
`
it returns the previous variables.
to solve it, just move the variables from here:

	def prepare_items_for_invoice(self, file_content, invoices_args):
		qty = 1
		rate, tax_rate = [0, 0]
		uom = self.default_uom

		for line in file_content.find_all("DettaglioLinee"):

inside the loop here:

	def prepare_items_for_invoice(self, file_content, invoices_args):

		for line in file_content.find_all("DettaglioLinee"):
			qty = 1
			rate, tax_rate = [0, 0]
			uom = self.default_uom

Greetins

**Comment by deepeshgarg007** [comment]
Duplicate issue, closing
