### ISSUE TITLE
Email alerts

### ISSUE THREAD

**Issue by Mahi-tsc** [frappe/erpnext#3188]
I had created an Email Alert for advance payment reminder. But it is just a one time process. Can we make it a repeated one, until the condition is met?? 
For example, I created an Email alert with Condition for my alert is that the email has to be sent on submission & if Advance paid is 0. Suppose, I receive payment after 3 days, in such case, can the email notification be sent everyday for the next 3 days, that is, when the condition is met??

**Comment by umairsy** [comment]
Perhaps you should apply condition on outstanding_amount > 0. For more support, please post this query on https://discuss.erpnext.com
