### ISSUE TITLE
Debit and Credit not equal for Payment Entry

### ISSUE THREAD

**Issue by techomniflo** [frappe/erpnext#31887]
### Information about bug

Submitting Payment Entry shows an error **Debit and Credit not equal for Payment Entry #ACC-PAY-2022-00000. Difference is 24856.0.**
Bill amount is 12428 and It is showing double the difference.

![Screenshot from 2022-08-18 18-17-38](https://user-images.githubusercontent.com/86599018/185398549-01ca447a-1fab-4009-b8e0-8f60709ab5a6.png)
![Screenshot from 2022-08-18 18-28-38](https://user-images.githubusercontent.com/86599018/185400683-2a3d9e5b-f4bf-42a0-af8e-8d47ceb8bb6a.png)

![Screenshot from 2022-08-18 18-26-27](https://user-images.githubusercontent.com/86599018/185400215-6ed7015f-a79d-4796-b870-956332c6cce4.png)
![Screenshot from 2022-08-18 18-26-36](https://user-images.githubusercontent.com/86599018/185400261-cd82398c-6db7-4021-bc74-d90e2288b047.png)

### Module

accounts

### Version

Frappe Version-v13.36.2 (version-13)
Erpnext Version-v13.36.2 (version-13)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Debit and Credit not equal for Payment Entry #ACC-PAY-2022-00000. Difference is 24856.0.
```

**Comment by gouravsaini021** [comment]
I also have the Same Problem,
Then Debugging I Found that in my site **Party Type** Doctype is empty 
So I insert the field "**Party Type**" to Customer and "**Account Type**" to Receivable and It Works
![image](https://user-images.githubusercontent.com/63018500/191935357-4a4eb886-766d-43d1-be2a-0ff12a6f1478.png)


Note:
By Uncheck field "User Cannot Create" in the Doctype setting of Party Type in Developer Mode.
![WhatsApp Image 2022-09-23 at 3 06 11 PM](https://user-images.githubusercontent.com/63018500/191933096-7a42992c-3f7e-4175-815e-12f627d7f10f.jpeg)

And If You are in Production Mode then update Json of Party Type Doctype by Following These Steps:
**Step 1**: Go to apps/erpnext/erpnext/setup/doctype/party_type/party_type.json and open party_type.json
**Step 2**:  Update JSON to Mentioned Below:
`{
 "actions": [],
 "autoname": "field:party_type",
 "creation": "2016-12-26 11:26:51.508286",
 "doctype": "DocType",
 "editable_grid": 1,
 "engine": "InnoDB",
 "field_order": [
  "party_type",
  "account_type"
 ],
 "fields": [
  {
   "fieldname": "party_type",
   "fieldtype": "Link",
   "in_list_view": 1,
   "label": "Party Type",
   "options": "DocType",
   "reqd": 1,
   "unique": 1
  },
  {
   "fieldname": "account_type",
   "fieldtype": "Select",
   "in_list_view": 1,
   "label": "Account Type",
   "options": "Payable\nReceivable",
   "reqd": 1
  }
 ],
 "links": [],
 "modified": "2022-08-27 18:26:13.911756",
 "modified_by": "Administrator",
 "module": "Setup",
 "name": "Party Type",
 "naming_rule": "By fieldname",
 "owner": "Administrator",
 "permissions": [
  {
   "create": 1,
   "email": 1,
   "export": 1,
   "print": 1,
   "read": 1,
   "report": 1,
   "role": "System Manager",
   "share": 1,
   "write": 1
  },
  {
   "create": 1,
   "email": 1,
   "export": 1,
   "print": 1,
   "read": 1,
   "report": 1,
   "role": "Accounts User",
   "share": 1,
   "write": 1
  },
  {
   "create": 1,
   "email": 1,
   "export": 1,
   "print": 1,
   "read": 1,
   "report": 1,
   "role": "Accounts Manager",
   "share": 1,
   "write": 1
  }
 ],
 "show_name_in_global_search": 1,
 "sort_field": "modified",
 "sort_order": "DESC",
 "states": [],
 "track_changes": 1
}`

**Step3**: Change  "modified": "2022-08-27 18:26:13.911756", in json file to Latest Datetime
**Step4**:Save party_type.json
**Step5**:Run Command:
                         **Sudo Bench Migrate
                         Sudo Bench Restart**

**Comment by deepeshgarg007** [comment]
@gouravengineer This happens when there are issues with the installation/setup. Will be helpful if you can share some tracebacks
