### ISSUE TITLE
Error in Create new BOM

### ISSUE THREAD

**Issue by neilLasrado** [frappe/erpnext#3189]
Steps:
1. Created a new BOM.
2 While adding Raw materials. In raw material row while selecting BOM selected create new BOM
3. The Page freezes

![error](https://cloud.githubusercontent.com/assets/8401344/7407623/03da46ec-ef32-11e4-8b0c-7f4c18cc389b.gif)

**Comment by rmehta** [comment]
fix it!

Also where is the trace??
