### ISSUE TITLE
Unit Rate changes to 0(zero) automatically in item table when clicked edit(Sales Order , Delivery Note , Sales Invoice ) 

### ISSUE THREAD

**Issue by ketandoshiaps** [frappe/erpnext#31904]
### Information about bug

Unit Rate changes to 0(zero) automatically in item table when clicked edit(Sales Order , Delivery Note , Sales Invoice ) 

### Module

accounts, selling

### Version

frappe:version-13.38.0
erpnext:version-13.36.4

### Installation method

FrappeCloud

**Comment by precihole** [comment]
Hey,
We are facing the same issue, Do let us know if you have any solution to it. thanks.
(issue link):  https://github.com/frappe/erpnext/issues/31908
