### ISSUE TITLE
Wrong currency symbol in "Exchange Rate Revaluation" form

### ISSUE THREAD

**Issue by blewsky** [frappe/erpnext#31901]
### Information about bug

The `exchange rate revaluation` doctype shows by default a "$" sign and not the symbol of the base currency in the `Balance In Base Currency`, `New Balance In Base Currency` and `Gain/Loss` fields. This is wrong and very confusing.

In this example, the base currency of the company was e.g.  INR and the foreign currency account "Test USD" was USD. The form shows wrongly a "$"(instead of "₹")  in the base currency fields:

![image](https://user-images.githubusercontent.com/87971956/185696487-d38edc1b-92db-4fa5-8ddc-c54214c8a938.png)

### Module

accounts

### Version

ERPNext: v13.36.4 (HEAD)
Frappe Framework: v13.38.0 (HEAD)

### Installation method

FrappeCloud

**Comment by blewsky** [comment]
Possibly duplicate of https://github.com/frappe/erpnext/issues/17525

**Comment by maharshivpatel** [comment]
@blewsky @dj12djdjs It is showing correct symbol on the latest version-13 please update to the latest version and let me know if it is still showing incorrect symbol. 
![SYMBOL](https://user-images.githubusercontent.com/39730881/189345014-900765f0-f384-4220-af1b-a1ee9b001d1e.png)

**Comment by dj12djdjs** [comment]
@maharshivpatel Please see attached video for procedure.

https://user-images.githubusercontent.com/29856401/190338910-affa4c96-bf39-480b-aa2e-0c1d677584f2.mp4


1. Initial Setup:
     Created "Demo Company" in currency CAD
2. Create another company "Company A" in "AED"
3. Set session defaults to "Company A"

Even after setting session defaults and resetting cache. All currency fields use the original created company currency.

**Comment by blewsky** [comment]
@maharshivpatel: Am on ERPNext: v13.39.0. Problem still persists and wrong currency symbols are shown.
