### ISSUE TITLE
Unit Rate changes to valuation rate automatically in item table when clicked edit in (Purchase Order,Supplier Quotation, Purchase Receipt) 

### ISSUE THREAD

**Issue by precihole** [frappe/erpnext#31908]
### Information about bug

After Clicking on edit, Unit Rate changes to valuation rate also changing the description to default item description and HSN code to blank in the item table automatically in (Purchase Order, Supplier Quotation, Purchase Receipt). 

### Module

buying

### Version

Frappe Version - v13.38.0 (HEAD)
Erpnext Version - v13.36.4 (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.
Video Link : https://drive.google.com/file/d/1m8swjP7RIHt_IVb2UYF-sbDJy1-ouYp7/view?usp=sharing

https://user-images.githubusercontent.com/111174201/185804546-7898ca25-28f2-4bf5-a66d-38e5cfc96efa.mp4

)
_No response_

**Comment by dj12djdjs** [comment]
@peciholesports I tried testing this on 
```
ERPNext: v13.36.5 (HEAD)
Frappe Framework: v13.39.0 (HEAD)
```
I wasn't able to replicate the issue. Can you try on latest version? let us know if this is still an issue for you.
