### ISSUE TITLE
Error in Company Creation

### ISSUE THREAD

**Issue by zaqoutabed** [frappe/erpnext#31911]
### Information about bug

When Create new company and the user language not English, will accord error when create departments tree and the tree will not be created.

![Screenshot from 2022-08-21 16-28-28](https://user-images.githubusercontent.com/26047413/185793347-a2cb5b2e-b8a0-444f-b396-b53820db6d5d.png)

### Module

other

### Version

ERPNext Version - 13

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
16:28:04 web.1            | Document Insert Error
16:28:04 web.1            | Traceback (most recent call last):
16:28:04 web.1            |   File "apps/frappe/frappe/desk/page/setup_wizard/setup_wizard.py", line 441, in make_records
16:28:04 web.1            |     doc.insert(ignore_permissions=True)
16:28:04 web.1            |   File "apps/frappe/frappe/model/document.py", line 255, in insert
16:28:04 web.1            |     self._validate_links()
16:28:04 web.1            |   File "apps/frappe/frappe/model/document.py", line 908, in _validate_links
16:28:04 web.1            |     frappe.throw(_("Could not find {0}").format(msg), frappe.LinkValidationError)
16:28:04 web.1            |   File "apps/frappe/frappe/__init__.py", line 504, in throw
16:28:04 web.1            |     msgprint(
16:28:04 web.1            |   File "apps/frappe/frappe/__init__.py", line 479, in msgprint
16:28:04 web.1            |     _raise_exception()
16:28:04 web.1            |   File "apps/frappe/frappe/__init__.py", line 434, in _raise_exception
16:28:04 web.1            |     raise raise_exception(msg)
16:28:04 web.1            | frappe.exceptions.LinkValidationError: Impossible de trouver Département parent: Tous les départements
16:28:04 web.1            |
```

**Comment by zaqoutabed** [comment]
fixed => 

https://github.com/frappe/erpnext/issues/31911

**Comment by zaqoutabed** [comment]
@nabinhait  @dj12djdjs 
Try to fix this in this PR
https://github.com/frappe/erpnext/pull/31912

**Comment by deepeshgarg007** [comment]
@zaqoutabed I tried the steps that you have mentioned and was able to create a company, the user language is "Español". Please mention detailed steps and reopen the issue if still replicable

<img width="1346" alt="image" src="https://user-images.githubusercontent.com/42651287/201072823-215cac15-8494-4570-959b-2126021e395a.png">
