### ISSUE TITLE
Multiple Cancellation/Assignment/Submit Required

### ISSUE THREAD

**Issue by ruchin78** [frappe/erpnext#3191]
I have one suggestion that there should be a way by which user can cancel/assign/submit multiple documents in one go.

Like for e.g., I have 200 Material Request and I want to cancel all therefore as per current feature I have to open each and everyone and press cancel button.

My opinion is system should raise error for the request which have some problem to cancel and leave them but user should be able to cancel the all in one go.

Same should be applied to
Assigned To
Submit

**Comment by Olawale1** [comment]
It's common practice in business environments to review documents (Expense Claims, Journal Vouchers, Orders etc) in batches for approval. It would greatly help to have a Bulk Submit feature for scenarios like this. There is already a feature to Delete documents in bulk from the List View. This should be extended to Submit and Cancel as well

Kind regards,

**Comment by betabank** [comment]
Hi, ist this feature planned to be added?
Thanks!

**Comment by joopdorresteijn** [comment]
+1

**Comment by Olawale1** [comment]
Hi,

Any updates on this?

Kind regards,

**Comment by taherkhalil** [comment]
+1 , bulk cancellation  plus bulk amend- **(best scenario to include in bulk update tool)** to make those documents in draft so that they can be updated from bulk update tool.

**Comment by adam-je** [comment]
Add **Close** to the

**Comment by dboobisMF** [comment]
+1 for this idea, being able to submit multiple documents at once is critical to our workflow.
