### ISSUE TITLE
Stock ledger report issue: It does not open from Item dashboard

### ISSUE THREAD

**Issue by mayanknahata007** [frappe/erpnext#31928]
### Information about bug

Steps:
Click on - This is based on stock movement. See [Stock Ledger] - https://sitename/app/item/Coffee%20Beans#query-report/Stock%20Ledger -  for details

URL which the report breaks on - https://sitename/app/%23query-report/Stock%20Ledger

<img width="1303" alt="Screenshot 2022-08-22 at 9 29 55 PM" src="https://user-images.githubusercontent.com/88381410/185966182-4850226d-9415-492a-9977-6a9dcb1e285e.png">

### Module

stock

### Version

ERPNext: v14.0.1 (HEAD)
Frappe Framework: v14.4.0 (HEAD)

**Comment by Solufyin** [comment]
Hi @mayanknahata007,

As per your requirement, we added a PR: #31935 
If will convenient for the changes then they will go ahead with the process.

Thank You!

**Comment by Solufyin** [comment]
Hi @mayanknahata007,

Please close the issue because PR is merged.

Thank You!
