### ISSUE TITLE
Issue with description of Tasks

### ISSUE THREAD

**Issue by pagliaso** [frappe/erpnext#3193]
Hi,

I think that there is an issue with the description of the Task, when edited from the list of tasks in a project.

The Description field on the window that emerges when you click a task on Task List inside a project is empty. And if you write anything in there and save, you loose the changes.

Many thanks and kind regards,

Alberto

**Comment by rmehta** [comment]
@neilLasrado did you fix this?

**Comment by pagliaso** [comment]
Hi,

I don't think this is yet solved.

Now you can see the description of the task if it had been created previously, but if you write a new description, and you click done, you can't see the description if you go to View Task.

Then, if you modify any other detail in task and click save you loose what you had introduced previously.

Thanks andkind regards,

**Comment by neilLasrado** [comment]
@pagliaso clicking on done wont save the work. you need to save the Project before continuing. Do let me know if this helps. It worked fine on my system.

**Comment by pagliaso** [comment]
Hi Neil,

Many thaks!

After your message, I realize it is obvious that the Project Status changes to not Saved, and if you save all is good.

So I am very sorry for my suggestion that the bug was not solved, and many thanks for your help!

Kind regards from Spain,

Alberto
