### ISSUE TITLE
Save button doesn't immediately save timesheet

### ISSUE THREAD

**Issue by Samweli** [frappe/erpnext#31933]
### Information about bug

When saving the information entered in the timesheet clicking the `Save` button doesn't always save the timesheet. In some cases  to save the timesheet you need to click the button more than twice.

### Module

projects

### Version

Frappe Version: v13.38.0 (HEAD)
ERPNext: v13.36.4 (HEAD)

**Comment by dj12djdjs** [comment]
The timesheet document saved on the first click of the save button for me.

How many rows of timesheets are you trying to save?

Also could you provide some screen capture of the provided behavior?
