### ISSUE TITLE
Issues caused by focusing on child table field on row form render

### ISSUE THREAD

**Issue by rtdany10** [frappe/erpnext#31941]
https://user-images.githubusercontent.com/52111700/186138975-644a07cd-9e56-4b6b-9190-8de65ad11b79.mp4

Fields often have triggers and focusing on a particular field while opening the edit page of rows can cause those triggers to activate and run client script. Focusing on the field shouldn't be a feature or at least avoid the trigger in such cases.

**Comment by ankush** [comment]
More importantly, these triggers should be idempotent. calling them multiple times shouldn't result in different values 😅 


The reason why it's focused is for UX: you can start editing the first field directly and move around by tabbing after that. 


FW part fixed here: https://github.com/frappe/frappe/releases/tag/v13.38.1 


ERPNext part doesn't seem easily fixable as item code trigger once fired will do it's thing (which ends up resetting values)
