### ISSUE TITLE
[URGENT]: Security Flaw in Permission Manager

### ISSUE THREAD

**Issue by adityaduggal** [frappe/erpnext#3194]
Reference: Ticket# WN-SUP10207

I have noticed that when you give rights to a user which are limited by `Apply User Permission` then if the user does not have any doctype mentioned in the user properties then they are able to SEE all the RECORDS.

For example: I give a role Sales Person access to read the `Sales Order` and the Role is limited by `Apply User Permission` say only on `Customer` then the user would only those Sales Orders where customer == the customer mentioned in the user permission.

Now suppose the person assigns this role to a user but forgets to mention the Customer in the user properties then this user would be able to see all the `Sales Order` for all the customers.

Now this thing has been changed in recent times only in v4 due to request by some users and the reference for them is on forums at the below link:

1. https://discuss.frappe.io/t/permission-in-version-4/2567
1. https://discuss.frappe.io/t/continued-permission-in-version-4/5006

Now if you people remove the bypassing then the person managing the permission manager would have to check the boxes of `Select Document Types` very judiciously as currently if we check all the boxes then even if there is no mention of the document in the user permission it passes the check but once this thing is implemented it would not let the users view the documents

I personally think that passing the users to view all documents is a SERIOUS FLAW and should be patched URGENTLY.

cc: @anandpdoshi

**Comment by anandpdoshi** [comment]
- [ ] In System Settings:
    - [ ] Add a section `Advance`
    - [ ] Add a checkbox `Prevent Access if User Permissions are Empty` (default for new sites. cannot force this on existing users.)
- [ ] Change code in
    - [ ] permissions.py
    - [ ] perm.js
    - [ ] query_report.py
    - [ ] db_query.py
- [ ] Test Cases with and without the condition as checked
    - [ ] get_list
    - [ ] get_doc

@adityaduggal I will try to get it done as soon as I can, but as you can see it involves many changes right in the middle of a complex code.

**Comment by adityaduggal** [comment]
@anandpdoshi How is it implemented on the system as I cannot see any new checkbox or anything on the role permission manager report.

**Comment by adityaduggal** [comment]
If Owner checkbox is the one which does the trick?

Apart from that is there any other user for this checkbox.

**Comment by anandpdoshi** [comment]
Go to System Settings and uncheck "Ignore User Permissions If Missing"

**Comment by adityaduggal** [comment]
So what does this `if_owner` do it seems to be doing the same thing but without the need for the system settings check box being unchecked.

I have tried this in my local system

**Comment by anandpdoshi** [comment]
if_owner allows access if the user is the owner.
