### ISSUE TITLE
Warehouses and Ledgers not set proper after migration

### ISSUE THREAD

**Issue by revant** [frappe/erpnext#3196]
My Stores Account under Charts of Accounts in v4
![mnt-stores-account-v4](https://cloud.githubusercontent.com/assets/1040161/7429741/bb9ff694-f024-11e4-86fc-4b2a718eeeda.png)
*it shows master name : Stores - MNT*

My GL reflecting Purchase Receipts in V4:
![stores-gl-v4](https://cloud.githubusercontent.com/assets/1040161/7429744/ec849198-f024-11e4-92a1-9b7fb0b03959.png)

Stores Account in Charts of Accounts after migration
![mnt-stores-account-v5](https://cloud.githubusercontent.com/assets/1040161/7429753/1dbb5ddc-f025-11e4-8978-5dc3c27c3cb3.png)
*notice "Warehouse" is not shown as "Stores - MNT"*

Old purchase receipts migrated successfully!
![stores-gl-v5](https://cloud.githubusercontent.com/assets/1040161/7429773/73ab6732-f025-11e4-977f-627bac115f8e.png)

related to discussion: https://discuss.frappe.io/t/message-on-submitting-repack-stock-entry/5619

**Comment by nabinhait** [comment]
Thanks Revant, nice job :)

Pushed a patch to fix the issue.
