### ISSUE TITLE
URGENT: Can't make new Production Order | error submitting new production order on new migration to v5

### ISSUE THREAD

**Issue by RealDesignGraphics** [frappe/erpnext#3197]
When I try to enter a new production order, and I fill out the target warehouse, it will let me save, but then when I submit, it deletes the target warehouse data and tells me it is mandatory and will not say.  This loop repeats infinitely, so it means I cannot create a new production order

**Comment by RealDesignGraphics** [comment]
I can use the production planning tool though

**Comment by rmehta** [comment]
I was able to create a Production Order and submit it. Can you retrace your steps?

**Comment by nabinhait** [comment]
Check if there is any error trace in the browser's console.
