### ISSUE TITLE
Material Transferred against Planned Quantity

### ISSUE THREAD

**Issue by dhawal-mahajan** [frappe/erpnext#31976]
### Information about bug

A workorder has 10 RM used to create FG.  For testing, we have kept weights per unit for all items as 1 UOM. When we create multiple 'Material Transferred for Manufacturing' stock entry transferrring one RM at a time, Material Transferred for Manufacturing cannt be greater than planned quantity error pops up. This MTM Quantity increases in multiples with each transfer stock entry. 10 MTM stock entries will require over-transfer allowance of 1000%, 12 stock entries will need 1200%.

### Module

manufacturing

### Version

ERPNext: v13.36.2 (version-13)

Frappe Framework: v13.36.0 (version-13)

**Comment by nabinhait** [comment]
Can't replicate in v15
