### ISSUE TITLE
Issue with renaming Item Code and Item Name 

### ISSUE THREAD

**Issue by shashankshirke** [frappe/erpnext#31987]
### Information about bug

Hi guys :raised_hand_with_fingers_splayed:

In Item master, when trying to rename the item name as well as the item code, there are 3 issues faced:

### Issue 1 : The field labels on item rename pop-up are confusing
  * When creating a new item, the field labels are "Item Code" and "Item Name"
  * When renaming the item (by clicking the item title), the labels are "New Item Name" and "New Name" which are really confusing.
  * The correct labels should be "New Item Name" (top field) and "New Item Code" (bottom field)
  * This may be occurring because the "item_code" field is the "name" or UID of the item DocType
  * Also, in the item list view, the column name for "Item Code" is labelled as "ID" which adds to the confusion
  * Better to retain same naming conventions across all views

### Issue 2 : Even when the "Merge with existing" checkbox is unticked, the renamed item is merged with the existing item
  * Intended functionality:
    * When renaming the item, the "merge with existing" checkbox is unticked by default, which means that a duplicate item should be created with the new item name and new item code.
    * If the "merge with existing" check box is ticked, only then the new item name and new item code should be merged with the existing item.
  * Bug:
    * Despite having the "merge with existing" unticked, the item is renamed and merged into the existing item

### Issue 3 : The UI gets buggy (unable to open the item list). It requires "Reload" to make it work again.
When clicking the rename button with "merge with existing" unticked, the item is saved and in the item list view, 2 separate items are seen for a brief while. After this point the UI gets buggy and we cannot again see the item list view. To again see the list view we have to click on the "Reload" button from the profile icon.

https://user-images.githubusercontent.com/7890147/186845085-9d42ccb2-2c94-4b37-baa7-3118aae83b9d.mov

 

### Module

stock

### Version

Frappe Framework: v14.4.0 (version-14)
ERPNext: v14.0.1 (version-14)

### Installation method

manual install

**Comment by rohitwaghchaure** [comment]
@shashankshirke 
Issues 2 and 3, I've tried multiple times to replicate the issue but issue is not replicating. Please check below GIF

 
![item_rename_issue_not_replicate](https://user-images.githubusercontent.com/8780500/190118289-2d52258e-9967-45ad-9283-f5c6d3c57f9a.gif)

**Comment by rohitwaghchaure** [comment]
@shashankshirke 
For issue 1

We need to make a changes in the design, currently it's not that easy to change the label from New Name to New Item Code.

**Comment by rohitwaghchaure** [comment]
@shashankshirke 

Issue 1 : Fixed (https://github.com/frappe/frappe/pull/18125)
Issue 2: Not able to replicate, please provide the steps
Issue 3: Not able to replicate, please provide the steps
