### ISSUE TITLE
[Proposed Improvements] in CRM Module & Lead Conversion Process 

### ISSUE THREAD

**Issue by shashankshirke** [frappe/erpnext#31986]
Hi guys :raised_hand_with_fingers_splayed:

I have having been testing out the CRM module in ERPNext as part of a client implementation project. It seems the process flow is very confusing (buggy at times) and it is not clearly documented. I have worked with various CRM products (Zoho, Salesforce, NetSuite, HubSpot, etc.) in the past 12+ years and from my experience I can say that ERPNext's CRM module definitely has a lot of scope of improvement.

In this post, I'll try to elaborate the issues faced and possible solutions.

# Current Scenario

ERPNext's CRM module has **6 primary objects** as given below;
1. Lead
2. Opportunity
3. Prospect
4. Customer
5. Contact
6. Quotation

<img width="768" alt="ERPN_CRM_Module_Objects_EC_SMS" src="https://user-images.githubusercontent.com/7890147/186837661-d4257960-8af0-4668-99d3-9027cc3c602f.png">

# Current Process Flow

* A new lead  is created

* When a new lead is created, the system will **automatically create a new contact** (this is the biggest issue)

* From this lead, the user can take 4 actions:
  1. Create Customer
  2. Create Opportunity
  3. Create Prospect
  4. Create Quotation 

<img width="413" alt="Screenshot 2022-08-25 at 10 58 56 PM" src="https://user-images.githubusercontent.com/7890147/186837702-c0962f79-c5c0-4cd6-83ad-94f08a9a1b0a.png">

* There's also an additional action called "Add to Prospect"

<img width="399" alt="Screenshot 2022-08-25 at 11 01 02 PM" src="https://user-images.githubusercontent.com/7890147/186837726-4464a0dc-8de1-48eb-816d-1814cd6e2a63.png">

The sales user who is in charge of processing the leads and "converting" them is now confused in terms of what action to take. I understand that a defined process can be enforced but if the company has a team of 20+ sales executives, it will be difficult to enforce and maintain such a process.

# Problem with Lead Conversion
* The biggest problem with the above process is that contacts are created at the time of lead creation.

* Contact creation is typically a part of the "lead conversion" process wherein you "convert" the lead into an "account (customer)" and the associated "contacts"

* Not all leads will be valid (almost 60-80% will be junk leads collected from various sources like data mining, website forms, conferences, etc.) and so it makes no sense to create contacts in the system which are invalid.

* A lead need not necessarily have fully verified data but when you "convert" the lead, the "account" and "contacts" ought to be verified as you only convert the lead post interaction with the lead.

* Also, there is no clear indication of whether the "opportunity" is to be linked to a lead or a prospect and what exactly is the intended use case of separating out the "Add to Prospect" functionality?

# Existing CRM Systems

In most popular CRM systems, the process of lead conversion is extremely simple and standardized 3 step process.

Create a Lead --> Convert the lead into Create an Account (company) & Contact (person) --> Create Opportunities / Quotations

## Lead Conversion Process in Salesforce

![image](https://user-images.githubusercontent.com/7890147/186837847-2ae31c66-8d02-4ac2-8976-235ed51e78d1.png)

![image](https://user-images.githubusercontent.com/7890147/186837891-844174c2-885d-4a5d-ab01-650b7319bd6a.png)

Ref: https://trailhead.salesforce.com/content/learn/modules/leads_opportunities_lightning_experience/create-and-convert-leads-lightning

## Lead Conversion Process in Zoho

![image](https://user-images.githubusercontent.com/7890147/186837933-24158d32-e9d8-4cfd-b3c6-2c6cf54e2c0c.png)

Ref: https://www.zoho.com/crm/help/img/lead-conversion.png

Most of the other popular CRM systems out there follow this exact, tried and tested process of lead conversion.

The advantage of this process is that it has a clear hierarchy, move ahead in a linear fashion and avoids any cyclical redundancy between the objects (leads, contacts, prospects, opportunities, customers, quotations, etc.)

# Proposed Solutions
* Disable the auto-creation of "contact" when a new "lead" is created.
* Role of "Prospect" object should be clearly defined. I think creation of prospect should be optional.
* Lead actions should be restricted. Eg: You cannot directly create an opportunity for a lead without first "converting" the lead into either a prospect or (account + contact)
* The lead form should have a clearly defined "Convert Lead" button which will open a pop-up box from where the lead can be converted into a customer/contact/opportunity (refer the Salesforce pop-up box image above)

Let me know what do you guys think.

@ankush @kennethsequeira  @rmehta

Thanks,
Shashank

**PS:** I looked in the forums and the "automatic contact creation" has already been reported here but it seems it has not been worked upon :point_down:

https://discuss.erpnext.com/t/proposal-issues-with-automatic-contact-creation-for-incoming-e-mails/59892

There's also a GitHub issue for the buggy Prospects functionality :point_down:

https://github.com/frappe/crm/issues/12

**Comment by rmehta** [comment]
++ @nabinhait

**Comment by rmehta** [comment]
Will be done via https://github.com/frappe/crm
