### ISSUE TITLE
total_net_weight in New Purchase Order not showing exact value

### ISSUE THREAD

**Issue by awrapk** [frappe/erpnext#31981]
### Information about bug

Hi,
   I have set precision 9 to weight_per_unit in Item. Whenever I select Item in Items Table in Purchase Order, it calculates using precision 3 of weight_per_unit. Result of 0.155098875 x 2579 should be 400. But, unfortunately it is showing 399.745000000

### Module

stock

### Version

Frappe Version 13.39.0
ERPNext Version 13.36.5

### Installation method

FrappeCloud

**Comment by nabinhait** [comment]
Can't replicate the issue. Make sure you have set precision as 9 for "weight_per_unit" for both Item and Purchase Order Item doctype.
