### ISSUE TITLE
URGENT: Can't make Stock Entry | Error on Stock entry for new migration to v5

### ISSUE THREAD

**Issue by RealDesignGraphics** [frappe/erpnext#3198]
When i try to do a stock entry with batch controlled items, there is no place to put the batch number and the stock entry will not save without batch number

**Comment by rmehta** [comment]
Let me check.

**Comment by rmehta** [comment]
I could add it in the Serial No and Batch Section. Are you checking for the right item?

![screen shot 2015-05-01 at 9 01 09 pm](https://cloud.githubusercontent.com/assets/140076/7432388/43342524-f045-11e4-8f46-501ffe014b45.png)

**Comment by nabinhait** [comment]
Go to Customize Form -> Stock Entry Detail and check if "Serial No / Batch" field is hidden.
