### ISSUE TITLE
Reports in V5?

### ISSUE THREAD

**Issue by vivekck** [frappe/erpnext#3199]
Firstly V5 looks great!  Awesome work!  Congrats on the new version and All the best!  Must say ERPNext is shaping up well.  

In V4 there was one cool feature which I used a lot, for e.g., when I am seeing a list of sales orders, I could click on a report icon (top right) and add columns, filters etc.  This option does not appear in V5?

There is a report builder option, though this seem to be a long process to generate a quick report..

**Comment by nabinhait** [comment]
You should find the "Report" link in left sidebar of the list view.

**Comment by vivekck** [comment]
Perfect.  Thank you.
