### ISSUE TITLE
Deferred Revenue Invoice Submit Error V14

### ISSUE THREAD

**Issue by AlaaBadry** [frappe/erpnext#31997]
### Information about bug

![msg-776876865-2143](https://user-images.githubusercontent.com/26534497/187056059-41679207-c72d-4504-a076-48299014563a.jpg)

a bug in the v14 when submitting invoices for deferred revenue item

### Module

accounts, selling

### Version

Frappe Version 14
Erpnext Version 14

### Installation method

FrappeCloud

**Comment by umairsy** [comment]
@maharshivpatel can you please review this once?

**Comment by umairsy** [comment]
@AlaaBadry In Debit To account the user has to use a normal Debtors account

Why are they using a deferred account there?

Ensure in the item master, Deferred in enabled... and Deferred about (non-receivable type) is selected there.
