### ISSUE TITLE
[Paid Development] Stock Cover Report

### ISSUE THREAD

**Issue by timothyjac** [frappe/erpnext#3201]
Need a report which tells me how many days my current stock for an item will last at the rate at which it’s currently selling. Simple :)

**Comment by rmehta** [comment]
$100? we can get this done today

**Comment by timothyjac** [comment]
Superb. That's fine. 

I don't know if I am supposed to type this message here. Can you just give me a quick wireframe of the report? And this will immediately go live in your hosted version of ERPNext? Thanks.

**Comment by nabinhait** [comment]
We can also extend the report Stock -> Standard Reports -> Itemwise Recommended Reorder Level. Additional columns: "Stock Balance", "Days to Zero Balance", Days to reach Reorder Level.
Additional Filters: "Item Code", "Warehouse"

@timothyjac What do you say?

**Comment by rmehta** [comment]
@timothyjac do you still want this?

**Comment by timothyjac** [comment]
Sorry Rushabh, I have settled in for another system. Kindly close the
ticket. Thanks for your help!
