### ISSUE TITLE
Migration from 13 to 14 Date Format is not preserved

### ISSUE THREAD

**Issue by michalls01** [frappe/erpnext#32012]
### Information about bug

After migration to v14 (to Branch Daily), the Date Format (in Settings / System settings), is not preserved and from dd.mm.yyyy is changed to the dd-mm-yyyy.

### Module

other

### Version

Frappe - 13.39.0
Erpnext - 13.36.5

**Comment by dj12djdjs** [comment]
@michalls01 I set the default date format to dd.mm.yyyy in version-13 then migrated to version-14. The date format stayed the same.

Could you show the version log of System Settings? It should provide more information how the value got changed.
Example:
![image](https://user-images.githubusercontent.com/29856401/187574534-3a30b8ea-8f79-4091-9355-669b5f3315d5.png)

**Comment by michalls01** [comment]
@dj12djdjs  Thank you for the follow up. The log in the System Setting is without any changes in the version 14. Below is the screenshot of the 13 and 14 for the reference. Thanks!

V13
![erpnext-13](https://user-images.githubusercontent.com/79514229/187684170-111aeda2-c368-4ff5-af6a-4247a9f66bfc.png)

V14
![erpnext-14](https://user-images.githubusercontent.com/79514229/187684221-fa7460df-f151-4c87-b1dd-27dfa76c7aba.png)

**Comment by dj12djdjs** [comment]
@michalls01 Thank you, I'll try a few things to try to replicate the bug.

Quick, do you have any other apps installed that ran patches during the migration to version-14 ?

**Comment by michalls01** [comment]
@dj12djdjs On V13 we have Wiki, on V14 HRMS, nothing more. Thanks!

**Comment by michalls01** [comment]
this has been somehow resolved in the latest 14V

**Comment by michalls01** [comment]
In the Frappe Framework v14.11.1 and ERPNext v14.2.3 the error still persists - the date is changed after migration from DD.MM.YYY to DD-MM-YYYY. Moreover, it cannot be altered to anything else.

**Comment by deepeshgarg007** [comment]
Closing this since its fixed in the latest v14
