### ISSUE TITLE
Data mismatch while upgrading V13 to V14 site

### ISSUE THREAD

**Issue by pra17shant** [frappe/erpnext#32041]
### Information about bug

I have two site in frappe cloud (V13) and (V14).
once we data restore v.13 to v.14 all entry gets restored successfully, but GL report shows Posting Date 1 day prior to actual date in financial year, which is not acceptable to financially point of view.
![Version13](https://user-images.githubusercontent.com/99401472/187835771-cf3808fa-b647-4db3-8a52-896e3b83f262.png)
![Version14](https://user-images.githubusercontent.com/99401472/187835787-cbc8976d-8745-492a-8dab-03afdfde4953.png)

### Module

accounts, stock, buying, selling

### Version

**1) Site Version**
ERPNext: v13.37.0 (HEAD)
Frappe Framework: v13.40.0 (HEAD)

**2) Site Version**
ERPNext: v14.0.2 (HEAD)
Frappe Framework: v14.4.3 (HEAD)

### Installation method

FrappeCloud

**Comment by deepeshgarg007** [comment]
@pra17shant You should freeze your books so that it cannot be modified once its finalized
