### ISSUE TITLE
 Bank Clearance Summary is Accessible only to System Manager 

### ISSUE THREAD

**Issue by maveezmh** [frappe/erpnext#32056]
### Information about bug

error is causing due to one of the column in report is link field to Document “Doctype”

gives Error “No permission to read Doctype”

https://discuss.erpnext.com/t/bank-clearance-summary-is-accessible-only-to-system-manager/91212

![image](https://user-images.githubusercontent.com/112148467/188121575-8199309a-4b22-4c26-a22a-3e552bfd5627.png)

Same issue with Lost Opportunity Report

![image](https://user-images.githubusercontent.com/112148467/188121649-9ca83438-367b-49c7-a383-8cf88f20a89f.png)

### Module

accounts, CRM

### Version

ERPNext: v13.37.0 (HEAD)

Frappe Framework: v13.40.0 (HEAD)

### Installation method

FrappeCloud

**Comment by maveezmh** [comment]
any update?

**Comment by deepeshgarg007** [comment]
Fixed Via: https://github.com/frappe/erpnext/pull/32219
