### ISSUE TITLE
Loan Repayment not deducting in salary slip

### ISSUE THREAD

**Issue by akhashogji** [frappe/erpnext#32064]
### Information about bug

I have an employee with a loan and the repayment is through his salary. This was working fine, till the last update.
Now, the loan is showing on the salary slip, but not actually deducting anything.
![ScreenShot_2022-09-02_22 20](https://user-images.githubusercontent.com/52230109/188222854-bc31964b-d96c-49f6-b02e-cdb7cf11f054.png)

### Module

HR

### Version

ERPNext: v13.37.0 (version-13)
Frappe Framework: v13.40.0 (version-13)

### Installation method

manual install

**Comment by deepeshgarg007** [comment]
@akhashogji There has been a slight change in the workflow. The total paid amount has to be repaid manually before submitting the salary slip. It is added to handle cases where the employer doesn't want to deduct loan repayment in a specific month or do partial deduction.

**Comment by akhashogji** [comment]
@deepeshgarg007 I tried doing that, it still not showing in the salary slip. Or do I have to manually deduct in the slip?

**Comment by jigneshpshah** [comment]
in v13.
Any solution on this @akhashogji  ? , could @deepeshgarg007 please share a screenshot on how to  put the paid amount in loan repayment via Salary Slip .
For me it reverts to 0.0 on save of salary slip.
<img width="1244" alt="Pasted Graphic 2" src="https://user-images.githubusercontent.com/4900815/189878616-eaa08fdb-2a25-47a2-b0e3-13c284aa2d50.png">

**Comment by RachealNeli** [comment]
mine doesnt even pick the table, then also  doesnt it bring alot of manual works like for organisations having over 20 employees or more with advance the u need to type in amounts manually
