### ISSUE TITLE
Unknown column 'master_name' in 'where clause' (link_warehouse_with_account patch)

### ISSUE THREAD

**Issue by kressi** [frappe/erpnext#3206]
following patch causes an error, when updating (bench update) on current version.
https://github.com/frappe/erpnext/blob/develop/erpnext/patches/v5_0/link_warehouse_with_account.py

master_name does not exist on tabAccount
https://github.com/frappe/erpnext/blob/develop/erpnext/accounts/doctype/account/account.json

**Comment by nabinhait** [comment]
Thanks for reporting, pushed the fix.
