### ISSUE TITLE
Cannot save material request

### ISSUE THREAD

**Issue by Jurmay** [frappe/erpnext#3208]
I created a demo today and was testing the ERP but am not able to save the "material request" after filling up the form.

Please help out freinds!

**Comment by nabinhait** [comment]
Any error message in browser's console?

**Comment by Jurmay** [comment]
No error message, just the save button gets disabled once it is clicked and it is not getting saved.
Actually the ERP is very user friendly (better than Odoo- i feel) but the only issue is no instant online support. The charge is also very reasonable. It would be great if i could get realtime customer support.

**Comment by nabinhait** [comment]
Fixed.

**Comment by rmehta** [comment]
@Jurmay are you a paid subscriber?

We will be happy to give priority support to paid customers

**Comment by Jurmay** [comment]
We would love to be a paid subscriber but we need to speak to your company once.

Do you have the apps (module) for fleet management?

WR

Jurmay

**Comment by rmehta** [comment]
@Jurmay Please feel free to drop in a mail at sales at erpnext dot com with your questions.

No fleet management as of now
