### ISSUE TITLE
Pricing rule is applied even if UOM doesn't match

### ISSUE THREAD

**Issue by carstenblt** [frappe/erpnext#32093]
### Information about bug

We have a pricing rule that applies to item groups. Some of the assigned item groups also have a UOM set. Documentation says:

> UoM: The Pricing Rule will apply only if the UoM set here matches with the transaction.

However, the pricing rule is applied to any item from these item groups, even though the UOM in the Sales Order does not match the UOM assigned to the item group. E.g. we created a pricing rule for "Bag (10 kg)" and create a Sales Order with an item from the item group with UOM "kg". The pricing rule is still applied.

### Module

selling

### Version

ERPNext: v13.37.0
Frappe Framework: v13.40.0

**Comment by maharshivpatel** [comment]
This issue has been fixed and will be released in next week's release. If you still face the issue please let me know.
