### ISSUE TITLE
Error: Value missing for Module Onboarding: Documentation URL

### ISSUE THREAD

**Issue by andy-irl** [frappe/erpnext#32094]
### Information about bug

Hi, I've started to get this error on my Frappe Cloud hosted site. Can you advise what the issue is?

### Module

stock, selling, HR

### Version

Frappe Framework
v13.40.0
frappe/frappe:version-13
ERPNext
v13.37.0
frappe/erpnext:version-13

### Installation method

FrappeCloud

**Comment by umarless** [comment]
@deepeshgarg007 Please provide solution  for this error
![Error](https://user-images.githubusercontent.com/97974556/234205107-9102b953-6768-4343-95d5-7f812c909040.jpg)

**Comment by ravishri1** [comment]
Have you found a solution to this problem? I am experiencing the same problem.

**Comment by andy-irl** [comment]
Hi – yes:

On V13 I got it working again by:
1.     Browse to https://yourwebsiteURL/app/onboarding-step/view/list
2.     Selecting the checkbox for all items
3.     Select the Actions button and then Edit
4.     Select the Is Complete field
5.     Ensure the checkbox is unselected then select the Update Records button
6.     Do this again for the Is Skipped field
7.     Refresh the page you’re having the issue with and it should work.
Hope this helps - this was a nightmare to figure out!
A


From: ravishri1 ***@***.***>
Date: Friday, 27 October 2023 at 10:42
To: frappe/erpnext ***@***.***>
Cc: andy-irl ***@***.***>, Author ***@***.***>
Subject: Re: [frappe/erpnext] Error: Value missing for Module Onboarding: Documentation URL (Issue #32094)

Have you found a solution to this problem? I am experiencing the same problem.

**Comment by ravishri1** [comment]
Hi,

I appreciate your help, but when I tried the same thing, I got a different error message.

![Screenshot 2023-10-30 104845](https://github.com/frappe/erpnext/assets/54638273/7217ed8d-67cb-425d-abbe-09acd0ca9fbf)
