### ISSUE TITLE
Tax included price in purchase cycle

### ISSUE THREAD

**Issue by nabinhait** [frappe/erpnext#321]
I want to use tax included price in Purchase Order as in Sales Order. But there is no option about tax included price in Purchase Order. I tried "Valuation and Total", "Valuation" and "Total" options with Add or Deduct but that does not belong my request.

For example: Basic rate (price) for item is 100. VAT %18 (price is tax included)
Total should be 100 and Vat Amount should be 15.254. 

But in Purchase order page I see with "Valuation and Total", "Total"  and "Add" option

Total is 118 and Vat Amount 18 .

And did not find any options for tax included price. Could you explain how can I manage this option?

from - aliosman20

**Comment by cgpurbaugh** [comment]
Is this really necessary?  Why not just make the rate 100?
