### ISSUE TITLE
Work flow and Authorization for Sales Invoice and Purchase Receipt

### ISSUE THREAD

**Issue by vivekck** [frappe/erpnext#3210]
At some point soon I would like to configure such that 

1)  Purchase receipt is allowed ONLY against a PO.  However only Mgmt shall have ability to enter purchase receipt without PO for any urgent situation.  

2)  Similarly, Invoice and Delivery Note to be created only against a Sales Order.  

How do I configure the above requirement?

Thank you.

**Comment by cgpurbaugh** [comment]
In Selling and Buying settings, check "Sales Order Required" & "Purchase Order Required" checkboxes.

**Comment by strixaluco** [comment]
Please post questions to [discuss.erpnext.com](https://discuss.erpnext.com)
