### ISSUE TITLE
Bench Update Stuck on migrate_remarks_from_gl_to_payment_ledger

### ISSUE THREAD

**Issue by sumeetagra** [frappe/erpnext#32121]
### Information about bug

Bench update stuck on executing the new patch erpnext.patches.v14_0.migrate_remarks_from_gl_to_payment_ledger

### Module

accounts

### Version

Frappe version - 14.1
ERPNext version - 14.1

### Installation method

manual install

**Comment by dj12djdjs** [comment]
Introduced in: https://github.com/frappe/erpnext/pull/32009

**Comment by dj12djdjs** [comment]
@ruthra-kumar what is the expected run time of this patch?

`GL Entry`: ~77k
`Payment Ledger Entry`: ~23k

I'm waiting  over 60min for this patch to complete. I will update with the exact runtime once it's completed.

Edit: Total Patch Execution Time (~4 hours)
```
Executing erpnext.patches.v14_0.migrate_remarks_from_gl_to_payment_ledger in localhost (erpnext)
Success: Done in 13616.342s
```

**Comment by dj12djdjs** [comment]
With only 23k payment ledger entries, the query results assigning to `pl_entries` 
https://github.com/frappe/erpnext/blob/dbe4fdc73d2bd2b05c08dd7b7d6e1d3fd1c7c3c2/erpnext/patches/v14_0/migrate_remarks_from_gl_to_payment_ledger.py#L13-L35

The length of `pl_entries` is 195,888. Seems like something isn't right with the query.

**Comment by ruthra-kumar** [comment]
> The length of `pl_entries` is 195,888.

Doesn't look right. Can we get more details?

Does the select query takes time or the batch-wise update? Any duplicate entries on the result set? 

@dj12djdjs

**Comment by dj12djdjs** [comment]
@ruthra-kumar There are many duplicate entries on the result set. I've made a dump file with query and record info for your review.
[debug.ods](https://github.com/frappe/erpnext/files/9698301/debug.ods)
