### ISSUE TITLE
DateTime Box not displayed In Webform On iOS

### ISSUE THREAD

**Issue by sagarrgarg** [frappe/erpnext#32136]
### Information about bug

I am Trying to setup the book appointment page on v13 ,

The page is set and everything works on - domain/book_appointment including formats , date picker etc , but only on non ios mobile phones and laptops/pcs
On Any latest iOS device the date selection shows invalid date to invalid date.

<img width="1416" alt="Screenshot 2022-09-08 at 10 04 49 PM" src="https://user-images.githubusercontent.com/619313/189177159-4914603a-d447-4c7b-bd45-862d9758327f.png">

### Module

CRM

### Version

Frappe: v13.40.0
ERPNext: v13.37.0

### Installation method

FrappeCloud

**Comment by Nihantra-Patel** [comment]
Hi @sagarrgarg,

![image](https://github.com/frappe/erpnext/assets/141945075/bcc51d88-7efe-4c65-ae0b-2e7bf5e0a436)

<img width="1440" alt="image" src="https://github.com/frappe/erpnext/assets/141945075/2ff70b1a-dd07-4b47-9560-a6884e669209">

<br>

We no longer provide support for version 13 or older. Kindly upgrade to version 14 or 15, then refresh and check again.
Everything is working fine. No problems were encountered in versions 14 and 15.

Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!
