### ISSUE TITLE
Payment entry

### ISSUE THREAD

**Issue by khb250** [frappe/erpnext#32151]
### Information about bug

I have created purchase invoices and made the payments but until now they are still marked as overdue and i can not figure out why. Please fix it as soon as possible

### Module

accounts, buying, other

### Version

ERPNext: v13.28.0 (version-13)
Frappe Framework: v13.28.0 (version-13)

**Comment by dj12djdjs** [comment]
@khb250 Can you provide more information? Please see attached as it's working as expected.

![pe](https://user-images.githubusercontent.com/29856401/189418534-dd78107f-94f8-4265-80c2-9af036ac9151.gif)

**Comment by khb250** [comment]
@dj12djdjs  Hello in the video below you can see that i made the payment but the invoice is still tagged as OVERDUE can you please help me with it 
https://user-images.githubusercontent.com/113194770/189636516-3e53f507-07f4-4475-b76c-57cb1c988d74.mp4

**Comment by dj12djdjs** [comment]
@khb250 It looks like the purchase invoice is showing as overdue because the invoice is not fully closed.
As shown in the screen shot from your video out of the 89,244,220,00 RWK only ~44,622,110,00 RWK is getting paid toward the invoice, therefor leaving it open.

![image](https://user-images.githubusercontent.com/29856401/190336365-e3211f18-047d-4e52-bc22-07aee0ed086f.png)

It looks like the column is cut off so I can't see the full amount allocated, It looks like 44,622,110,00.

**Comment by khb250** [comment]
@dj12djdjs Well the issue is that the full amount of this invoice was not paid all at once. Part of the amount was first paid on 21/07/2022 and the rest was paid in the following month on 26/08/2022. So, the problem is that it does not even show me the remaining amount to be paid it keeps displaying the full amount of the invoice

**Comment by khb250** [comment]
@dj12djdjs For example if those 44,622,110RWF was paid. The Outstanfing amount should have changed but it is not changing

**Comment by dj12djdjs** [comment]
@khb250 In your video at 1:14, the first payment entry on 21/07/2022 isn't submitted. It is still in Draft state. Please also submit the first payment entry.

**Comment by deepeshgarg007** [comment]
@khb250 as @dj12djdjs already investigated, your earlier payment entry is not submitted yet hence you see an overdue status. If something this common wouldn't have been working a lot of other users must have reported this by now. Closing this issue as it seems invalid at the moment
