### ISSUE TITLE
translation not work erpnext v14.1.0

### ISSUE THREAD

**Issue by ahmedbahgattt** [frappe/erpnext#32164]
### Information about bug

after make item translatable and publish it 

the arabic translation of items names  not appear when changing the language in website or inside item list or website item list

<img width="838" alt="Screen Shot 2022-09-11 at 8 52 14 PM" src="https://
<img width="684" alt="Screen Shot 2022-09-11 at 8 54 22 PM" src="https://user-images.githubusercontent.com/84731009/189542208-485f5d20-915b-4c9c-a2fa-d51884af733e.png">
user-images.githubusercontent.com/84731009/189542199-0076d14a-f454-4b5e-8f34-73176189eef0.png">

### Module

stock, ecommerce, other

### Version

 v14.1.0 (version-14)

### Installation method

manual install

**Comment by ahmedbahgattt** [comment]
<img width="892" alt="Screen Shot 2022-09-11 at 9 04 07 PM" src="https://user-images.githubusercontent.com/84731009/189542414-67020c15-1c7d-4ffb-a35d-3b377d182298.png">

**Comment by AliShaatani** [comment]
the Arabic language is not supported in version 14, use Ver13 is the latest stable release

**Comment by Nihantra-Patel** [comment]
fixed in v15, because The page was not translatable.

https://github.com/frappe/webshop/pull/121
