### ISSUE TITLE
Support Issue field shows up when entering issue and then disappears after saving

### ISSUE THREAD

**Issue by fblauer** [frappe/erpnext#3218]
I enter a support issue and there is a description field, in the first section. After I save and re-enter the issue, that description field is not there anymore on the issue data entry screen.

**Comment by rmehta** [comment]
The issue shows up as the first comment.

**Comment by fblauer** [comment]
I created a new issue, end entered the description. I save the issue. I
don't see any comments?? I am using V 5.0.3

On Tue, May 19, 2015 at 1:44 AM, Rushabh Mehta <notifications@github.com>
wrote:

> Closed #3218 <https://github.com/frappe/erpnext/issues/3218>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/frappe/erpnext/issues/3218#event-308097353>.
>



-- 
Fred Blauer CA, CPA, CISA
http://openacct.ca
514-667-1555

**Comment by rmehta** [comment]
Thanks, fixed. Might be released tomorrow though.
