### ISSUE TITLE
Deleting Todo items

### ISSUE THREAD

**Issue by fblauer** [frappe/erpnext#3219]
Is it possible to delete a todo item? I can't seem to find a way?

**Comment by anandpdoshi** [comment]
Give yourself Delete permission on ToDo and you can do that. People didn't
like that we allowed deletion of ToDos so we removed the permission from
the default configuration.

**Comment by fblauer** [comment]
I am just trying to figure out how to do that. Its not obvious to me. I gave myself access to all modules, and all roles, but that doesn't seem to do it. Do I have to change one of the roles?

**Comment by fblauer** [comment]
OK, I changed the rights to that module in the system manager role, and that seemed to work. Thanks
