### ISSUE TITLE
Export File  from Stock ledger and Stock Balance to excel problem  

### ISSUE THREAD

**Issue by tsothun** [frappe/erpnext#32203]
### Information about bug

1. When I try to remove Date or any column from stock ledger and export to excel those remove column still exist in excel. 
 2. The Title Stock Ledger Report or Stock Balance didnt show up in excel file but show up in Print or PDF file with header too if I choose header.
 3. There is not column when excel file into excel like pdf or print. Please help to have table too.

![photo_2022-09-13_21-00-37](https://user-images.githubusercontent.com/56767875/189921712-78dc500c-8e79-4075-9321-532bd35af2b3.jpg)

![photo_2022-09-13_21-01-42](https://user-images.githubusercontent.com/56767875/189922006-aa9f5149-3e05-42a5-9bfe-b4ddaa6c842c.jpg)

If there is not format like Print or PDF when export to excel, it will take too much time to design it again in excel.

### Module

stock

### Version

ERPNext: v13.37.0 (version-13)

Frappe Framework: v13.40.0 (version-13)

**Comment by deepeshgarg007** [comment]
@tsothun you will have to save the report first before exporting, this is not a bug. Please refer https://docs.erpnext.com/docs/v13/user/manual/en/customize-erpnext/articles/how-to-add-columns-in-the-standard-report-and-export
