### ISSUE TITLE
Payment Entry Party Filter Not Working

### ISSUE THREAD

**Issue by edwardleehl7097** [frappe/erpnext#32207]
### Information about bug

Party filter is not showing a list of party after select customer.

<img width="1445" alt="image" src="https://user-images.githubusercontent.com/25194385/190051295-4d00358a-64c7-4c51-87bb-9957ac990dbe.png">

### Module

accounts

### Version

ERPNext: v14.1.0 (version-14)

Frappe Framework: v14.6.0 (version-14)

Frappe HR: v0.0.1 (develop)

Payments: v0.0.1 (develop)

### Installation method

manual install

**Comment by Solufyin** [comment]
Hi @edwardleehl7097,

We have the same version but do not have any make problem found in the party.
![image](https://user-images.githubusercontent.com/34390782/190061110-3d35a555-912f-455d-a9d4-82ad0ce532b7.png)

If you have not apply command then apply it.

// if any changes in base doctype and base code then apply the below command. but make sure first take a backup.
`bench update --reset`
```
bench migrate
bench clear-cache
```

Thank You!

**Comment by edwardleehl7097** [comment]
yes, found it. Thank you.
