### ISSUE TITLE
Error in Subcontracting Flow

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#32223]
### Information about bug

Steps:

1. Tried making a subcontracting, but it asks for Purchase Order made for the same subcontracting doc. Is this the intended flow?
2. When I tried making a PO for subcontracting, it says the item to be selected must be a service item. The subcontracted item in all possibilities will be a stock item.

<img width="1079" alt="Screenshot 2022-09-15 at 12 46 39 PM" src="https://user-images.githubusercontent.com/910238/190339664-2a9471d3-9ce5-4a9b-8f3f-2000a32fb846.png">

4. Other masters like item, BOM, and supplier warehouse is in place.

Feel free to replicate in https://starelectronics.frappe.cloud/

@s-aga-r @rohitwaghchaure 

### Module

stock

### Version

Installed Apps

Education: v0.0.1 (HEAD)

ERPNext: v14.0.0-dev (HEAD)

Frappe Framework: v14.0.0-dev (HEAD)

Frappe HR: v0.0.1 (HEAD)

India Compliance: v0.0.1 (HEAD)

Payments: v0.0.1 (HEAD)

### Installation method

FrappeCloud

**Comment by nabinhait** [comment]
In subcontracting order, PO is mandatory and in PO, the item should be a service item - both are intentional. closing the issue

**Comment by shashankshirke** [comment]
@nabinhait I understand that from v14, it's necessary to have a service item PO for creating a sub-contracting order but how do we manage sub-assemblies with this approach?

Eg: We have a BOM as below;

<img width="383" alt="image" src="https://user-images.githubusercontent.com/7890147/202574136-bc674bbd-8531-4b38-924b-15e1d1871c6e.png">

As we can see in the above case, there are 2 services items (1 for the main finished good and 1 for the sub-assembly)

Now let's say we want to create a subcontracting order for manufacturing 10 units of the main finished good. In this case, how should we configure the PO? Should we include both the service items in the PO? If yes, we have to then manually calculate and enter the qty required for finished good of the sub-assembly.

Need further guidance on the correct approach to take in this case.

**Comment by nabinhait** [comment]
@shashankshirke Is it possible to add both service costs and enter the amount against a single service item?

**Comment by shashankshirke** [comment]
> @shashankshirke Is it possible to add both service costs and enter the amount against a single service item?

No it's not possible to do that because the example BOM that I have shared above has only one sub-assembly (and one service item attached to it). The actual business case has at least 12-15 sub-assemblies that go into the final finished good and each of those sub-assemblies has a service item attached to it.

In such a case, how do we add these multiple service items on the PO for creating the SCO? It completely breaks the subcontracting cycle if we try adding multiple service items into the PO.
