### ISSUE TITLE
Salary Structure Delete

### ISSUE THREAD

**Issue by hemanthbabu** [frappe/erpnext#3223]
How to delete salary structure

**Comment by neilLasrado** [comment]
You cannot delete salary structure at the moment... will fix this up.

**Comment by hemanthbabu** [comment]
Ok will wait....;-)

**Comment by neilLasrado** [comment]
You need to Role Permission Manager and give delete permission against your Role.
Please check https://manual.erpnext.com/contents/setting-up/users-and-permissions/role-based-permissions for details.
