### ISSUE TITLE
Fetching activities to Opportunity from a lead 

### ISSUE THREAD

**Issue by farazk3** [frappe/erpnext#32242]
### Information about bug

When an opportunity is created from a lead, Activities(emails with prospects) are not fetched to Opportunity. Activities stay within the lead and communication is not copied to opportunity, for reference of older communicated one has to again check lead doctype.

### Module

CRM

### Version

v14.0.0-dev (HEAD)

v14.0.0-dev (HEAD)

**Comment by muchai** [comment]
Tick that, it's a setting under CRM Settings
![image](https://user-images.githubusercontent.com/1822868/190668549-5507bd90-0d5f-43c4-915b-0e87a258e729.png)
