### ISSUE TITLE
Bank reconciliation error

### ISSUE THREAD

**Issue by fblauer** [frappe/erpnext#3224]
Per - umair
May 7
Hello Fred,
Sorry for the issue. Please create Github Issue for this. These options (System Balance, Amount not reflected in bank etc.) are not meant to be click-able.

Here is my initial question
When I go into the bank reconciliation report, After selecting a bank account, and click on either:
System balance,
Accounts not reflected in bank, or
Accounts not reflected in system
I get the following message:
"Sorry! I could not find what you were looking for"

It seems that these things are not meant to be hyperlinked, so I guess the links should be removed to reduce confusion.

**Comment by rmehta** [comment]
Example from QB

https://www.youtube.com/watch?v=71NvZfaCn6M https://www.youtube.com/watch?v=BoSZZCUP_iA

**Comment by rmehta** [comment]
Could not replicate. Seems fixed.

**Comment by fblauer** [comment]
If you were talking about the bogus hyperlinks on the bank reconciliation
report, I still see them.

On Tue, May 19, 2015 at 1:47 AM, Rushabh Mehta <notifications@github.com>
wrote:

> Closed #3224 <https://github.com/frappe/erpnext/issues/3224>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/frappe/erpnext/issues/3224#event-308098323>.
>



-- 
Fred Blauer CA, CPA, CISA
http://openacct.ca
514-667-1555

**Comment by rmehta** [comment]
Thanks. Did not notice "report"
