### ISSUE TITLE
margin issue in the erp next website

### ISSUE THREAD

**Issue by KMJ-007** [frappe/erpnext#32259]
### Information about bug

![image](https://user-images.githubusercontent.com/86996507/190886648-48682773-d005-434d-8518-5d234798541f.png)

I found this on the [website](https://erpnext.com/open-source-accounting), and I want to contribute to open source by fixing it,

but I didn't find any repo that contains the code of the website(I checked both erpnext and frappe's GitHub account), 

it would be a great help if someone can guide me in my first open source contribution.

Thankyou 

### Module

other

### Version

I actually don't know.

**Comment by deepeshgarg007** [comment]
@KMJ-007 This is on one of our internal repos, we will shortly be updating our website design post which it will get fixed.
Closing this from here
