### ISSUE TITLE
Drop-shipping : shipping_address not filled

### ISSUE THREAD

**Issue by NassimBentarka** [frappe/erpnext#32258]
### Information about bug

When using drop shipping option in sales order item, when generating a Purchase Order, the Shipping Address on the Purchase Order should reflect the Shipping Address on the Sales Order. However, that's not what happens on my ERP Next installation, it instead shows the Company Address as the Shipping Address on the PO regardless of the Drop Shipping procedure (AKA: item.delivered_by_supplier: True)

### Steps to reproduce the issue

1. Make a sale order, in a sale order item tick the box delivered_by_supplier and submit.
2. Make the corresponding purchase order using create purchase order.

### Observed result
The shipping_address field is filled by _Company Address_.

### Expected result
The shipping_address field should be the _Customer Shipping Address_ (shipping_address_name field of Sale Order)

### Module

buying, selling

### Version

ERPNext: v14.1.0 (HEAD)
Frappe Framework: v14.6.0 (HEAD)

### Installation method

FrappeCloud

**Comment by vamagithub** [comment]
Can i work on this issue?

**Comment by s-aga-r** [comment]
> Can i work on this issue?

@vamagithub Yes, if you are interested.

**Comment by s-aga-r** [comment]
@rohitwaghchaure @deepeshgarg007 

Don't know what will be a good fix for this issue. Imagine a case where we have `delivered_by_supplier` partially checked i.e., we have 2 items from which only one will be delivered by the supplier directly to the customer.

**Comment by deepeshgarg007** [comment]
@s-aga-r In case of partially delivered by the supplier separate PO should be made for this and the address to be updated by the user accordingly. If there is a possibility of adding any sane defaults then lets do that else we should close this if nothing can be done

**Comment by NassimBentarka** [comment]
@deepeshgarg007 We have tested the Dropshipping process step-by-step as per the official docs using just 1 item in the Sales Order, and the `shipping_address` does not populate when creating the Purchase Order.

I believe as long as the issue can still be reproduced on the Master version, we should work on finding a good fix. Client scripts are good workaround, however, ideally, fixing it permanently for all users is best.
