### ISSUE TITLE
How to move fields on data entry screen? 

### ISSUE THREAD

**Issue by fblauer** [frappe/erpnext#3226]
I can't seem to figure out how to move fields on the data entry screens. I tried deleting them and re-entering them in the customize forms, but they keep going back to the previous location. I couldn't find anything about this in the manual. I can't figure out what this means:
"Change layout (sequence of fields). To do this, select a field in the grid and click on“Up” or “Down” in the grid toolbar"
I can't seem to do that?

**Comment by anandpdoshi** [comment]
You can drag and drop them to rearrange them.

**Comment by fblauer** [comment]
That works great. I didn't know I could do that. I guess the manual needs
to be updated. Thanks for your help

On Thu, May 7, 2015 at 1:42 PM, Anand Doshi <notifications@github.com>
wrote:

> You can drag and drop them to rearrange them.
>
> Sent from my phone
>
> > On 07-May-2015, at 8:37, fblauer <notifications@github.com> wrote:
> >
> > I can't seem to figure out how to move fields on the data entry screens.
> I tried deleting them and re-entering them in the customize forms, but they
> keep going back to the previous location. I couldn't find anything about
> this in the manual.
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/frappe/erpnext/issues/3226#issuecomment-99955782>.
>



-- 
Fred Blauer CA, CPA, CISA
http://openacct.ca
514-667-1555

**Comment by anandpdoshi** [comment]
Fred, Manual needs a lot of work :(

Any chance of you to find some time to contribute?

Thanks,
Anand.

**Comment by fblauer** [comment]
I would be willing. But I am not an expert in the system functionality yet.
How about in exchange for some training?

How do you know which parts have to be updated? Do you have a list of
changes to the system since the last manual update?

On Thu, May 7, 2015 at 3:43 PM, Anand Doshi <notifications@github.com>
wrote:

> Fred, Manual needs a lot of work :(
>
> Any chance of you to find some time to contribute?
>
> Thanks,
> Anand.
>
>
> On Thu, May 7, 2015 at 10:47 AM, fblauer <notifications@github.com> wrote:
>
> > That works great. I didn't know I could do that. I guess the manual needs
> > to be updated. Thanks for your help
> >
> > On Thu, May 7, 2015 at 1:42 PM, Anand Doshi <notifications@github.com>
> > wrote:
> >
> > > You can drag and drop them to rearrange them.
> > >
> > > Sent from my phone
> > >
> > > > On 07-May-2015, at 8:37, fblauer <notifications@github.com> wrote:
> > > >
> > > > I can't seem to figure out how to move fields on the data entry
> > screens.
> > > I tried deleting them and re-entering them in the customize forms, but
> > they
> > > keep going back to the previous location. I couldn't find anything
> about
> > > this in the manual.
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/frappe/erpnext/issues/3226#issuecomment-99955782>.
> > >
> >
> >
> >
> > --
> > Fred Blauer CA, CPA, CISA
> > http://openacct.ca
> > 514-667-1555
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/frappe/erpnext/issues/3226#issuecomment-99956848>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/frappe/erpnext/issues/3226#issuecomment-99993411>.
>



-- 
Fred Blauer CA, CPA, CISA
http://openacct.ca
514-667-1555

**Comment by anandpdoshi** [comment]
Hi Fred,

For starters, if you think something is missing in the manual and you know
something and have figured it out, you can contribute an article in the
Knowledge Base: https://kb.erpnext.com

Thanks,
Anand.

**Comment by fblauer** [comment]
Ok

On Thu, May 7, 2015 at 4:21 PM, Anand Doshi <notifications@github.com>
wrote:

> Hi Fred,
>
> For starters, if you think something is missing in the manual and you know
> something and have figured it out, you can contribute an article in the
> Knowledge Base: https://kb.erpnext.com
>
> Thanks,
> Anand.
>
>
> On Thu, May 7, 2015 at 1:05 PM, fblauer <notifications@github.com> wrote:
>
> > I would be willing. But I am not an expert in the system functionality
> yet.
> > How about in exchange for some training?
> >
> > How do you know which parts have to be updated? Do you have a list of
> > changes to the system since the last manual update?
> >
> > On Thu, May 7, 2015 at 3:43 PM, Anand Doshi <notifications@github.com>
> > wrote:
> >
> > > Fred, Manual needs a lot of work :(
> > >
> > > Any chance of you to find some time to contribute?
> > >
> > > Thanks,
> > > Anand.
> > >
> > >
> > > On Thu, May 7, 2015 at 10:47 AM, fblauer <notifications@github.com>
> > wrote:
> > >
> > > > That works great. I didn't know I could do that. I guess the manual
> > needs
> > > > to be updated. Thanks for your help
> > > >
> > > > On Thu, May 7, 2015 at 1:42 PM, Anand Doshi <
> notifications@github.com>
> > > > wrote:
> > > >
> > > > > You can drag and drop them to rearrange them.
> > > > >
> > > > > Sent from my phone
> > > > >
> > > > > > On 07-May-2015, at 8:37, fblauer <notifications@github.com>
> wrote:
> > > > > >
> > > > > > I can't seem to figure out how to move fields on the data entry
> > > > screens.
> > > > > I tried deleting them and re-entering them in the customize forms,
> > but
> > > > they
> > > > > keep going back to the previous location. I couldn't find anything
> > > about
> > > > > this in the manual.
> > > > > >
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub.
> > > > > >
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> https://github.com/frappe/erpnext/issues/3226#issuecomment-99955782
> > >.
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > > Fred Blauer CA, CPA, CISA
> > > > http://openacct.ca
> > > > 514-667-1555
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/frappe/erpnext/issues/3226#issuecomment-99956848
> >.
> > >
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/frappe/erpnext/issues/3226#issuecomment-99993411>.
> > >
> >
> >
> >
> > --
> > Fred Blauer CA, CPA, CISA
> > http://openacct.ca
> > 514-667-1555
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/frappe/erpnext/issues/3226#issuecomment-100000150>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/frappe/erpnext/issues/3226#issuecomment-100005923>.
>



-- 
Fred Blauer CA, CPA, CISA
http://openacct.ca
514-667-1555

**Comment by fblauer** [comment]
How do I add knowledgebase articles? I have been collecting them in my
Support/Issues in my Erpnext instance. Here is an example:

*Sorting in logical order instead of alphabetical*
In order to sort things like lists or reports in logical order, I found
that preceding text fields with a number helps. For example:
Priority field (for todo's or issues)
1.High
2.Medium
3.Low
Then it will sort your list in a logical order rather than an alphabetical
one (High, Low, Medium), which is less logical
Another example in the chart of accounts:
1.Assets
2.Liabilities
3.Income
4.Expenses
You just have to find the selectable field in the forms customization for
that module. Then edit the options. Make sure to also edit the default
option. Then select the sort order for the form, ascending, and update the
form. (I logout and back in again, after updating forms, otherwise I seem
to get an error message when trying to use the updated form).
I found this practise to be helpful.

On Thu, May 7, 2015 at 4:21 PM, Anand Doshi <notifications@github.com>
wrote:

> Hi Fred,
>
> For starters, if you think something is missing in the manual and you know
> something and have figured it out, you can contribute an article in the
> Knowledge Base: https://kb.erpnext.com
>
> Thanks,
> Anand.
>
>
> On Thu, May 7, 2015 at 1:05 PM, fblauer <notifications@github.com> wrote:
>
> > I would be willing. But I am not an expert in the system functionality
> yet.
> > How about in exchange for some training?
> >
> > How do you know which parts have to be updated? Do you have a list of
> > changes to the system since the last manual update?
> >
> > On Thu, May 7, 2015 at 3:43 PM, Anand Doshi <notifications@github.com>
> > wrote:
> >
> > > Fred, Manual needs a lot of work :(
> > >
> > > Any chance of you to find some time to contribute?
> > >
> > > Thanks,
> > > Anand.
> > >
> > >
> > > On Thu, May 7, 2015 at 10:47 AM, fblauer <notifications@github.com>
> > wrote:
> > >
> > > > That works great. I didn't know I could do that. I guess the manual
> > needs
> > > > to be updated. Thanks for your help
> > > >
> > > > On Thu, May 7, 2015 at 1:42 PM, Anand Doshi <
> notifications@github.com>
> > > > wrote:
> > > >
> > > > > You can drag and drop them to rearrange them.
> > > > >
> > > > > Sent from my phone
> > > > >
> > > > > > On 07-May-2015, at 8:37, fblauer <notifications@github.com>
> wrote:
> > > > > >
> > > > > > I can't seem to figure out how to move fields on the data entry
> > > > screens.
> > > > > I tried deleting them and re-entering them in the customize forms,
> > but
> > > > they
> > > > > keep going back to the previous location. I couldn't find anything
> > > about
> > > > > this in the manual.
> > > > > >
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub.
> > > > > >
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> https://github.com/frappe/erpnext/issues/3226#issuecomment-99955782
> > >.
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > > Fred Blauer CA, CPA, CISA
> > > > http://openacct.ca
> > > > 514-667-1555
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/frappe/erpnext/issues/3226#issuecomment-99956848
> >.
> > >
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/frappe/erpnext/issues/3226#issuecomment-99993411>.
> > >
> >
> >
> >
> > --
> > Fred Blauer CA, CPA, CISA
> > http://openacct.ca
> > 514-667-1555
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/frappe/erpnext/issues/3226#issuecomment-100000150>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/frappe/erpnext/issues/3226#issuecomment-100005923>.
>



-- 
Fred Blauer CA, CPA, CISA
http://openacct.ca
514-667-1555
