### ISSUE TITLE
nginx: [warn] conflicting server name "site1.local" on 0.0.0.0:80, ignored nginx.

### ISSUE THREAD

**Issue by camilopianos** [frappe/erpnext#3229]
After bench upgrade and nginx restart I got this message:

"nginx: [warn] conflicting server name "site1.local" on 0.0.0.0:80, ignored nginx."

And I get still this message after login in:

"Redis cache server not running. Please contact Administrator / Tech support"

Are this two issues related. It is something I can do? I appreciate your help a lot!

**Comment by rmehta** [comment]
Please ask help on discuss.frappe.io

Seems like your other bench is not closed cleanly.
