### ISSUE TITLE
Getting error on "Production Plan" creation

### ISSUE THREAD

**Issue by nidhipurohit11** [frappe/erpnext#32308]
### Information about bug

Steps - 

- Creating a sales order with an item having BOM
- Creating a production plan where this sales order got fetched
- On saving the production plan getting server error "KeyError: 'item_code'"

Due to this, the cypress scripts are also breaking

![photo_2022-09-21 13 07 42](https://user-images.githubusercontent.com/82337328/191444031-a62fa41d-a8c6-492c-999d-98b921b54ffe.jpeg)

### Module

manufacturing

### Version

ERPNext: v14.x.x-develop () (develop)

Frappe Framework: v14.x.x-develop () (develop)

**Comment by FHenry** [comment]
@rohitwaghchaure  in version-13 too
