### ISSUE TITLE
Allowing non stock items in POS ERPNext: v14.2.0 

### ISSUE THREAD

**Issue by ahmedoryx** [frappe/erpnext#32318]
### Information about bug

When adding a non-stock item or service in POS, an Error message appear: "Item Code: code# is not available under warehouse warehouse-name", I found this issue is already closed #28998.
![pos error msg](https://user-images.githubusercontent.com/109868787/191594360-2264cebf-b644-4ae8-816a-ec97c43b9fc9.png)

### Module

other

### Version

ERPNext: v14.2.0 (version-14)
Frappe Framework: v14.8.0 (version-14)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Error
"Item Code: code# is not available under warehouse warehouse-name",
```

**Comment by maharshivpatel** [comment]
This issue has been fixed on the latest version of ERPNext. please update and let me know if you are still facing the issue.

**Comment by ahmedoryx** [comment]
Hello Sir,
I already updated to the latest version and the problem is still there.
Any advice?

Thank you for your interaction

Ahmed

‫في الخميس، 29 سبتمبر 2022 في 12:32 م تمت كتابة ما يلي بواسطة ‪Maharshi
Patel‬‏ ***@***.***‬‏>:‬

**Comment by maharshivpatel** [comment]
@ahmedoryx can you please share information like item settings as well as process you are following when you are getting this error

**Comment by ahmedoryx** [comment]
My mistake, It is working. Thank you Sir.

**Comment by ahmedoryx** [comment]
My mistake, It is already working. Thank you very much

‫في الأربعاء، 5 أكتوبر 2022 في 12:39 ص تمت كتابة ما يلي بواسطة ‪Max Oryx‬‏
***@***.***‬‏>:‬
