### ISSUE TITLE
A few Bugs on Opening Invoice Creation Tool Tool

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#32326]
### Information about bug

One, When upload button is used, the system does not capture party and amount, despite them being on the import template. The go around is to use the Data Import Tool, which imports the data correctly.

Two, and this is the major issue, after invoices are created from the tool, they are not deleted, and the Create Invoices button is still active, means a user can click on the button, and end up with duplicate opening invoices.

### Module

accounts

### Version

ERPNext: v14.1.0 (HEAD)
Frappe Framework: v14.6.0 (HEAD)

### Installation method

FrappeCloud

**Comment by muchai** [comment]
This tool may not be very useful anymore, one can use SI/PI/JE of type Opening entry to achieve this.

**Comment by deepeshgarg007** [comment]
@muchai Was not able to replicate the first one, worked fine for me

<img width="1333" alt="Screenshot 2022-10-24 at 11 21 39 AM" src="https://user-images.githubusercontent.com/42651287/197460705-6cd3a45f-f60e-423f-bdce-90f51bc7b041.png">

Have raised PR for the second issue

**Comment by muchai** [comment]
> @muchai Was not able to replicate the first one, worked fine for me

Seen the PR. Will retest above and let you know.

**Comment by nrodindo** [comment]
bug - opening invoice tool shows opening invoices created but they have failed to be created as shown in error log
![OICT bug](https://github.com/frappe/erpnext/assets/123488339/fefd1bef-d772-40d8-b22c-96f29dbd5d2f)
