### ISSUE TITLE
POS customer exceeded the credit limit 

### ISSUE THREAD

**Issue by ahmedoryx** [frappe/erpnext#32320]
### Information about bug

When the customer make purchase and partially pay the invoice, POS allow to proceed even if the customer exceed the credit limit.
When closing the POS, the list of customers exceeded the credit limit appear, and cant proceed the closing process until the admin extend the credit limit of those customers.
As a seller in POS with limited permissions, the system should warn me during the process of purchase to stop the process, not on closing where the process is already done.

### Module

accounts

### Version

ERPNext: v14.2.0 (version-14)
Frappe Framework: v14.8.0 (version-14)

### Installation method

manual install

**Comment by deepeshgarg007** [comment]
@ahmedoryx please help us with some values to replicate. Ideally POS means fully paid invoices so there are no chances of any credit being allocated so hence it will always pass credit limit check
