### ISSUE TITLE
Part of Settings is missing after migration from V13 to V14

### ISSUE THREAD

**Issue by michalls01** [frappe/erpnext#32335]
### Information about bug

Part of Settings is missing after migration from V13 to V14, please see screenshots. If the intention is to move the shortcuts to corresponding sections, then for example Project settings is completely gone from accessing through a shortcut link.

**V13**
![Screenshot 2022-09-22 at 22 56 54](https://user-images.githubusercontent.com/79514229/191849553-99e61265-8235-4d02-be90-722cf86d45a4.png)

**V14**
![Screenshot 2022-09-22 at 22 57 17](https://user-images.githubusercontent.com/79514229/191849624-ccc7d190-7639-4bc7-8685-80282d3b4d01.png)

### Module

other

### Version

V14

### Installation method

FrappeCloud

**Comment by dj12djdjs** [comment]
TODO:
-  Add Projects Settings link to Project workspace.

**Comment by anandbaburajan** [comment]
@michalls01 you can access the settings via `ERPNext Settings` on the sidebar.

**Comment by michalls01** [comment]
@AnandBaburajan Right now there is no Project settings in the Projects page, it shall be added to follow the other DocTypes concept.

**Comment by anandbaburajan** [comment]
> @AnandBaburajan Right now there is no Project settings in the Projects page, it shall be added to follow the other DocTypes concept.

Ah, I see. Sure.
