### ISSUE TITLE
[V5] Menu > Rename error in some languages

### ISSUE THREAD

**Issue by tmimori** [frappe/erpnext#3233]
Hi,

I got a error as bellow when I tried to rename with "Menu > Rename" in some pages.
e.g. "Price List", "Chart of Accounts", "Holiday List", "Customer" and "Employment Type".

1. When "My Settings > Language" is set to ...
	- English, successfully finished.
	- some languages, failed with error.
		- I tried it in Japanese, Chinese-Traditional, Korean and Spanish.

2. When "Rename" button is clicked, POST parameter "new" is not sent.

3. I found a localized value of attribute (data-fieldname="new_name") in "div.modal-dialog".
![modal](https://cloud.githubusercontent.com/assets/624831/7549475/176bdb9e-f671-11e4-8dcd-ba0c481c3292.jpg)

Could you please confirm it?

Thanks and regards,

---

App Versions

	"erpnext": "5.0.0-beta",
	"frappe": "5.0.0-beta"

Error Report

	Traceback (innermost last):
	  File "/home/erpnext/frappe-bench/apps/frappe/frappe/app.py", line 51, in application
	    response = frappe.handler.handle()
	  File "/home/erpnext/frappe-bench/apps/frappe/frappe/handler.py", line 66, in handle
	    execute_cmd(cmd)
	  File "/home/erpnext/frappe-bench/apps/frappe/frappe/handler.py", line 89, in execute_cmd
	    ret = frappe.call(method, **frappe.form_dict)
	  File "/home/erpnext/frappe-bench/apps/frappe/frappe/__init__.py", line 741, in call
	    return fn(*args, **newargs)
	 TypeError: rename_doc() takes at least 3 arguments (2 given)

Request Data
("標準購入" = "Standard Buying")

	{
		"type": "POST",
		"args": {
			"doctype": "Price List",
			"old": "標準購入",
			"cmd": "frappe.model.rename_doc.rename_doc",
			"_type": "POST"
		},
		"btn": {
			"0": {},
			"length": 1,
			"prevObject": {
				"0": {
					"sizzle1431146008701": {
						"parentNode": [
							2236,
							34,
							false
						]
					}
				},
				"length": 1,
				"prevObject": {
					"0": {
						"sizzle1431146008701": {
							"parentNode": [
								2236,
								34,
								false
							]
						}
					},
					"length": 1
				}
			},
			"selector": ".modal-header .btn-primary"
		},
		"url": "/"
	}

Response JSON

	{}

---

Environment : 
- Debian 7.8 amd64
- Python 2.7.9

**Comment by rmehta** [comment]
Thanks for the descriptive error report!
