### ISSUE TITLE
Desk does not open in android webview

### ISSUE THREAD

**Issue by betabank** [frappe/erpnext#3235]
Hi, we are testing v5 with webview in android environment. Navigation works, but not the desktop, just hangs on the icon ERPNext.

**Comment by rmehta** [comment]
Please add some additional help / trace.

**Comment by betabank** [comment]
Yes, we can send you an .apk file with a demo app. It consists just in a webview element for the demo site at https://demo.erpnext.com/

Shall we send it to support@erpnext.com
? It is around 1MB

**Comment by rmehta** [comment]
Not able to understand what is the objective? Is this a private app, then we cannot help. If this is public, you should open source it first.

**Comment by betabank** [comment]
Hi, the objective is testing the app capabilities of the ERPNext, this is just for testing purposes and the webview seems not to be compatible with v4 neither v5.
Do you have planned the release of an ERPNext app?

**Comment by rmehta** [comment]
We stared on a Cordova project. Not yet in release state though!

**Comment by betabank** [comment]
We can help testing/betatesting. The new v5 looks very good in android browser, this is why we started to make a simple test in order to embed it as webview obj.

**Comment by rmehta** [comment]
I just setup android and ios emulators in my machine to test. Its just that we are really bottlenecked with other issues :)

Would love some help in answering questions on the forum, at least the entry level questions. Will free up a lot of my time.

Thanks!

**Comment by betabank** [comment]
OK, we will try. We are also busy developing but ERPNext is also very important for us, as is our CRM reference software. I will speak with the team and try to dedicate some resources to the entry-level questions.

**Comment by AdamVB** [comment]
Hi, we had a similar Problem and solved it:

As well as enabling javascript you also need to enable Dom storage by adding in;

webView.getSettings().setDomStorageEnabled(true);


hope that answers your question

**Comment by vjFaLk** [comment]
Fixed?

**Comment by cgpurbaugh** [comment]
Considering there is an ERPNext app for [Android](https://play.google.com/store/apps/details?id=io.frappe.mobile) and [iOS](https://itunes.apple.com/us/app/erpnext/id1027318091?mt=8)  This should probably be closed.
