### ISSUE TITLE
Submit Button gone after V5 upgrade

### ISSUE THREAD

**Issue by monojoker** [frappe/erpnext#3236]
We are on Frappecloud and after upgrade to V5 on the weekend there is no way to Submit sales orders. We thus cannot invoice so need this fixed ASAP please. Or we are just not finding the Submit button in which case please advise where it is now located. I have checked Role permissions and all Roles have Submit for Sales Order so it should be there.

**Comment by anandpdoshi** [comment]
Hi. Can you check browser's console? Could be a conflict in custom script.

**Comment by monojoker** [comment]
No, it's caused by having Workflow enabled. When I set the workflow to not active I see submit button again. Can this please be fixed ASAP we need to track production status using workflow but also to be able to submit to invoice. Currently I have to flick between the two and it's causing confusion for the production team. Thanks.

**Comment by monojoker** [comment]
![image](https://cloud.githubusercontent.com/assets/10917366/7559418/42a68b30-f7fa-11e4-9d85-c8004215fb77.png)

![image](https://cloud.githubusercontent.com/assets/10917366/7559425/4ba32f86-f7fa-11e4-8634-8a53e5d85348.png)

**Comment by rmehta** [comment]
@monojoker in version 5, if you are using workflow, we assumed you will submit via workflow. 

For an immediate fix, you can set a workflow state with docstatus = 1 and system will automatically submit when you reach that state.

Let me see if I can fix this.

**Comment by monojoker** [comment]
Thanks Rushabh but unfortunately we cannot auto-submit even at despatch workflow status because price of shipping may change or be added - and we need to include the shipping price on the invoice correctly. Thus we usually move the job all the way through at docstatus = 0 for this reason then submit in front office for billing as the last step before invoicing.

**Comment by rmehta** [comment]
Can you create a state for submission?
