### ISSUE TITLE
Issue with Email Domain and Email Accounts creation on ERPNext 

### ISSUE THREAD

**Issue by abayomiawosusi** [frappe/erpnext#32388]
### Information about bug

We have a working email account that we want to connect to ERPNext and we have followed the documentation to add Email Domain and Email Account but it never worked. As a work-around we followed the steps below by creating a connector,
 then trying to add a New Email Domain) but it doesn’t seem to work. 
I need help - Is there any suggestions to try? 
What could be wrong?

1.	Follow the steps here: https://discuss.erpnext.com/t/office-365-settings/70551
2.	The setting that we’ve used in the New Email Domain:

<img width="523" alt="screenshot0" src="https://user-images.githubusercontent.com/113623622/192637092-ee25595e-1552-4c61-8eb9-acf0e53ce35c.png">
<img width="418" alt="screenshot" src="https://user-images.githubusercontent.com/113623622/192637116-0454758e-cf44-4a9a-958e-af3a70ac736a.png">

### Module

other

### Version

13.34.1

### Relevant log output / Stack trace / Full Error Message.

```shell
The page freezes when you click save. A times it brings a time out error after a long wait when we attempt to create a Email Domain . We use Office365 as email server.
```

**Comment by konradbr** [comment]
I have the same issue. Server is non-Microsoft.
