### ISSUE TITLE
Creating eBMR to link template or page with doctype

### ISSUE THREAD

**Issue by Akashv2510** [frappe/erpnext#32391]
### Information about bug

- Create New Template for one product (Ex: BMR-001) of any two stages (Line clearance, Granulation) and save the updated json in Template master(doctype).
- Create New Batch for created template master product (Ex: BMR-001).
- When BMR is created it should, get the updated template for product (Ex: BMR-001) from Template Master file and update the results/data and save the executed details in a separate page for this batch record.

1. A new doctype is created called Template Master with item code and operation stage fields. Both are link fields listing the active items and the operation stages that occurs during manufacturing(blending, line clearance, granulation, packing, compression, coating etc.)
![image](https://user-images.githubusercontent.com/114491833/192686532-07ab8278-5fa2-4d37-9c47-cce5a33a9158.png)
![image](https://user-images.githubusercontent.com/114491833/192686636-1bd22bae-42df-42b7-87e3-6f1ade701799.png)

2. On clicking Design Granulation button, Granulation page will be displayed which is already created as a page using html.
![image](https://user-images.githubusercontent.com/114491833/192687104-9fcca18a-1894-4fcd-8a0f-c902442bd2f6.png)
![image](https://user-images.githubusercontent.com/114491833/192687602-c6bb5cb5-1d85-49ee-baad-8eb57a4c6240.png)
![image](https://user-images.githubusercontent.com/114491833/192687791-fc6ba92e-857c-4a4c-af5c-d2a97e5c0a6e.png)

3. After entering details in granulation page, it is saved in template master as a json content.
![image](https://user-images.githubusercontent.com/114491833/192687882-a290a9c3-292d-4560-8f50-e990c3f359f7.png)

4. The next step is, while creating batch for this particular item, the above created template should be called automatically along with the saved table contents and should be saved in a separate page.

**NOTE:**
This is not a bug whereas it is a new requirement for our product.

Need help to how to handle this requirement.
Thanks in advance.

### Module

manufacturing

### Version

Frappe version - v12.10.2
ERPNext version - v12.10.1

**Comment by deepeshgarg007** [comment]
@Akashv2510 This looks like your own customization issue, the doctype that you have mentioned doesn't exist in the core. Closing this issue.
