### ISSUE TITLE
Gross Profit is not getting Calculated properly for Product Bundles.

### ISSUE THREAD

**Issue by maveezmh** [frappe/erpnext#32392]
### Information about bug

We we have a product bundle with list of items in it and when you sell that bundled item the report is not able to generate profit based on bundles.

below is the screenshot of two items in bundle
![image](https://user-images.githubusercontent.com/112148467/192701031-7905963a-3d17-4c56-b0b6-9f5e279bbb9d.png)

Below is the screenshot of Delivery note and it is followed by invoice

![image](https://user-images.githubusercontent.com/112148467/192701183-b164c8bc-e77e-4824-a320-f97baa889cf7.png)

Now if you see the Gross profit report for the same
its noticed that cost is booked against individual items
Selling price is booked on product bundle but its not calculating the difference. (Profit/Loss against the invoice)

![image](https://user-images.githubusercontent.com/112148467/192701736-59026978-7f18-4a96-bbe1-4709b9be60af.png)

### Module

accounts, stock, selling

### Version

ERPNext: v13.39.1 (HEAD)

Frappe Framework: v13.41.2 (HEAD)

### Installation method

FrappeCloud

**Comment by ruthra-kumar** [comment]
Can you post a Screenshot of the Gross Profit report?

**Comment by maveezmh** [comment]
![Screenshot 2023-01-05 at 09-20-26 Gross Profit](https://user-images.githubusercontent.com/112148467/210707698-74ac076a-2349-4491-a060-789154c21575.png)

@ruthra-kumar 
in Above 2 examples there are two bundles with 2 items in each bundle. the cost is not getting fetched for any of the bundles.

as we can see it shows 100% profit for both the items which is increasing the overall gross profit of invoice
