### ISSUE TITLE
Incorrect account currency shown in new journal entry

### ISSUE THREAD

**Issue by dgehriger** [frappe/erpnext#32409]
### Information about bug

I am using accounts in USD, EUR and CHF (the latter being the company currency). 

When creating a new journal entry involving accounts in a currency different from the company currency, the correct currency is shown in the _Account Currency_ column of the _Accounting Entries_ table.

However, when either _duplicating_, or creating from a _template_, those same accounts will show, and use, the company currency, not their own currency, in that column, as well as in the detailed entry form. 

The only way to correct this is to delete the account entry from the table and to re-enter it.

![image](https://user-images.githubusercontent.com/105200493/192798703-054283f1-b6c5-4fc1-b30b-bc960b017f19.png)

### Module

accounts

### Version

Frappe v14.5.0
ERPNext v14.1.2

### Installation method

manual install

**Comment by rtdany10** [comment]
Even though it shows wrong currency while duplicating, it will be updated to correct value when you save the journal entry.

**Comment by dgehriger** [comment]
@rtdany10 : thanks for your answer. The problem is that the difference calculations will be incorrect. In the screenshot above, line 1 and 3 are in USD, whereas 2 is in the company currency, which is CHF.

I fill in 1 & 3, and then click on the difference entry button to calculate the amount for 2 (Sales Expenses). That value will be wrong if the currency is wrong.

**Comment by dj12djdjs** [comment]
@dgehriger Please see my attached screen capture, are we looking a the same bug?

**Steps to Reproduce**
1. Duplicate an existing multi-currency journal entry.
2. Modify the target company currency account.
3. Clear previous company currency amount.
4. Click "Make Difference Entry" (Note at this time UI shows transaction as balanced)
5. Save -> throw validation error transaction is not balanced. 

![xxxx](https://user-images.githubusercontent.com/29856401/193379043-68c9c21d-882b-4aeb-b384-e6ca5d7ef1c2.gif)

**Comment by rtdany10** [comment]
Unchecking _No Copy_ for the currency field seems to have fixed the issue. But, was _No Copy_ enabled for some other reason?
@deepeshgarg007

**Comment by dgehriger** [comment]
> @dgehriger Please see my attached screen capture, are we looking a the same bug?

Yes, that's exactly what I am observing.

**Comment by dgehriger** [comment]
@rtdany10 
> Unchecking _No Copy_ for the currency field seems to have fixed the issue. But, was _No Copy_ enabled for some other reason?

Indeed, unchecking _No Copy_ in _Journal_ Entry Account_ fixes it when _duplicating existing journal entries_. It does, however, not fix it for _Journal Entry Templates_. The latter directly reference the _Account_ DocType, which doesn't have _No Copy_ checked anyway.

**Comment by rtdany10** [comment]
> @rtdany10
> 
> > Unchecking _No Copy_ for the currency field seems to have fixed the issue. But, was _No Copy_ enabled for some other reason?
> 
> Indeed, unchecking _No Copy_ in _Journal_ Entry Account_ fixes it when _duplicating existing journal entries_. It does, however, not fix it for _Journal Entry Templates_. The latter directly reference the _Account_ DocType, which doesn't have _No Copy_ checked anyway.

@dgehriger I've sent a PR to fix the issue.
