### ISSUE TITLE
Error in General ledger print of Customer/supplier with different Currency than base

### ISSUE THREAD

**Issue by maveezmh** [frappe/erpnext#32400]
### Information about bug

Whenever we have a customer or supplier with currency other than base currency and we goto accounting ledgers of that respective customer/supplier the ledger is loaded in customer/supplier's currency but when we generate pdf from that ledger the notation of currency(Currency Symbol) changes to company or Base currency. this is creating alot of issues with clients maintaining different curriencies.

![Screenshot 2022-09-28 at 12-02-14 General Ledger](https://user-images.githubusercontent.com/112148467/192725485-5acdf4c4-535c-43d3-8392-9bd1b169b537.png)

Below you can see when we generate Statement of account PDF for the Ledger the amount will be in USD but the notation of Currency will show in AED

![Screenshot 2022-09-28 at 12-57-12 c5763d1c-8b32-4c03-9d3d-3e2a9677e884](https://user-images.githubusercontent.com/112148467/192736538-77c55b9a-96fc-4700-8e34-a2abf7fc6313.png)

### Module

accounts

### Version

ERPNext: v14.2.0 (HEAD)
Frappe Framework: v14.8.0 (HEAD)
Frappe HR: v0.0.1 (HEAD)
Payments: v0.0.1 (HEAD)

ERPNext: v13.39.1 (HEAD)
Frappe Framework: v13.41.2 (HEAD)

### Installation method

FrappeCloud

**Comment by rtdany10** [comment]
Did you try setting the currency filter to USD and then generating the PDF?

**Comment by dj12djdjs** [comment]
@maveezmh Did you generate the PDF directly from the page you took your first screen shot? I just tried replicating and the PDF shows in the correct account currency.

**Comment by maveezmh** [comment]
@rtdany10  
We have multiple customers with different currencies and its not a feasible solution to select customer currency whenever we need to generate pdf of his SOA.

**Comment by maveezmh** [comment]
@dj12djdjs  the PDF works fine for customers/suppliers with base currencies. it has issue only when the customer's/supplier's billing currency and party accounts are in different currency than base currency. 

Ex:
When you select a customer with different currency the general ledger properly shows the statement as per customer currency and currency symbol but when you generate PDF the values will be same but currency symbol will be different

**Comment by maveezmh** [comment]
@dj12djdjs Can you please check it once?
