### ISSUE TITLE
Standard Wokring Hours as Float instead of Int

### ISSUE THREAD

**Issue by merlinwoff** [frappe/erpnext#32416]
Hi Guys

I am working for a small company in Switzerland and we are planning to start using ERPNext. During the testing phase, we noticed, that its only possible to define complete hours as the Standard Working Hours in the HR settings.

![Screenshot from 2022-09-28 22-34-45](https://user-images.githubusercontent.com/3635664/192883650-a768e139-6cca-4cb0-9644-38d0045f3235.png)

In Switzerland, it is quite common to have a total of 8.4 working hours / day.

Does somebody have an idea on how to change this input field from an Int to a Float or will this be causing any Frappe internal errors?

Thank you very much for your support.

BR
Merlin

**Comment by dj12djdjs** [comment]
All occurrences of `working_hours` is of type Float. So it makes sense `standard_working_hours` should also be of type float.
https://github.com/frappe/hrms/search?l=JSON&q=working_hours

@merlinwoff This can be easily changed, if you have the time to update the field type in DocType form and make a PR at https://github.com/frappe/hrms
