### ISSUE TITLE
How to get "all applications" back?

### ISSUE THREAD

**Issue by fblauer** [frappe/erpnext#3243]
I unchecked several applications including "all applications" Now I want to redisplay some of the applications, but I can't figure out how to get that application back?

**Comment by anandpdoshi** [comment]
Refreshing should bring back the icon.

**Comment by fblauer** [comment]
That does not work. I tried "reload" on the main desktop, and it does not bring back "all applications"

**Comment by anandpdoshi** [comment]
Are you on version 4?

**Comment by fblauer** [comment]
Version 5

**Comment by anandpdoshi** [comment]
I think you must've done this from Setup > Users, opened the user form and unchecked All Applications. You can go there again and check it.

**Comment by fblauer** [comment]
It IS checked, but I don't see it on my desktop. Here is a screenshot:



[image: Inline image 1]
Here is a screenshot of my desktop:

[image: Inline image 2]

There are several things missing, like all applications, manufacturing, nor
POS. I also have all the roles checked

On Mon, May 11, 2015 at 11:16 PM, Anand Doshi <notifications@github.com>
wrote:

> I think you must've done this from Setup > Users, opened the user form and
> unchecked All Applications. You can go there again and check it.
>
> Sent from my phone
>
>
> > On 11-May-2015, at 16:39, fblauer <notifications@github.com> wrote:
> >
> > Version 5
> > On 11 May 2015 6:49 pm, "Anand Doshi" <notifications@github.com> wrote:
> >
> > > Are you on version 4?
> > >
> > > On Mon, May 11, 2015 at 2:59 PM, fblauer <notifications@github.com>
> wrote:
> > >
> > > > That does not work. I tried "reload" on the main desktop, and it
> does not
> > > > bring back "all applications"
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> https://github.com/frappe/erpnext/issues/3243#issuecomment-101060693>.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/frappe/erpnext/issues/3243#issuecomment-101069028
> >.
>
> > >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/frappe/erpnext/issues/3243#issuecomment-101114606>.
>



-- 
Fred Blauer CA, CPA, CISA
http://openacct.ca
514-667-1555

**Comment by rmehta** [comment]
Seems like an issue. Will fix it.

**Comment by fblauer** [comment]
I have a client who just setup an instance to start using the system, and
they are having a similar problem. We created a user, added modules and the
modules are not showing up either. We tried reloading the screen several
times. When you fix it will that be for everyone, or just me?

On Mon, May 11, 2015 at 11:29 PM, Rushabh Mehta <notifications@github.com>
wrote:

> Seems like an issue. Will fix it.
>
> Sent from phone
>
>
> > On 12-May-2015, at 8:54 am, fblauer <notifications@github.com> wrote:
> >
> > It IS checked, but I don't see it on my desktop. Here is a screenshot:
> >
> >
> >
> > [image: Inline image 1]
> > Here is a screenshot of my desktop:
> >
> > [image: Inline image 2]
> >
> > There are several things missing, like all applications, manufacturing,
> nor
> > POS. I also have all the roles checked
> >
> > On Mon, May 11, 2015 at 11:16 PM, Anand Doshi <notifications@github.com>
> > wrote:
> >
> > > I think you must've done this from Setup > Users, opened the user form
> and
> > > unchecked All Applications. You can go there again and check it.
> > >
> > > Sent from my phone
> > >
> > >
> > > > On 11-May-2015, at 16:39, fblauer <notifications@github.com> wrote:
> > > >
> > > > Version 5
> > > > On 11 May 2015 6:49 pm, "Anand Doshi" <notifications@github.com>
> wrote:
> > > >
> > > > > Are you on version 4?
> > > > >
> > > > > On Mon, May 11, 2015 at 2:59 PM, fblauer <notifications@github.com
> >
> > > wrote:
> > > > >
> > > > > > That does not work. I tried "reload" on the main desktop, and it
> > > does not
> > > > > > bring back "all applications"
> > > > > >
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub
> > > > > > <
> > > https://github.com/frappe/erpnext/issues/3243#issuecomment-101060693>.
> > > > > >
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> https://github.com/frappe/erpnext/issues/3243#issuecomment-101069028
> > > >.
> > >
> > > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/frappe/erpnext/issues/3243#issuecomment-101114606
> >.
>
> > >
> >
> >
> >
> > --
> > Fred Blauer CA, CPA, CISA
> > http://openacct.ca
> > 514-667-1555
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/frappe/erpnext/issues/3243#issuecomment-101116160>.
>



-- 
Fred Blauer CA, CPA, CISA
http://openacct.ca
514-667-1555

**Comment by rmehta** [comment]
fixed.

**Comment by fblauer** [comment]
It doesn't seem to be fixed on my client's instance here:
https://atservice.erpnext.com/desk
They gave me access to all modules and all roles, and I only see some of
them on my desktop?
Here is a screenshot:

[image: Inline image 1]

On Tue, May 12, 2015 at 1:26 AM, Rushabh Mehta <notifications@github.com>
wrote:

> fixed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/frappe/erpnext/issues/3243#issuecomment-101137558>.
>



-- 
Fred Blauer CA, CPA, CISA
http://openacct.ca
514-667-1555

**Comment by fblauer** [comment]
When I click on all applications, only some of them show up. Also, is it
possible for him to give me access to setup?

On Tue, May 12, 2015 at 8:19 AM, fred blauer <fblauer@gmail.com> wrote:

> It doesn't seem to be fixed on my client's instance here:
> https://atservice.erpnext.com/desk
> They gave me access to all modules and all roles, and I only see some of
> them on my desktop?
> Here is a screenshot:
>
> [image: Inline image 1]
>
> On Tue, May 12, 2015 at 1:26 AM, Rushabh Mehta <notifications@github.com>
> wrote:
>
>> fixed.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/frappe/erpnext/issues/3243#issuecomment-101137558>.
>>
>
>
>
> --
> Fred Blauer CA, CPA, CISA
> http://openacct.ca
> 514-667-1555
>



-- 
Fred Blauer CA, CPA, CISA
http://openacct.ca
514-667-1555

**Comment by rmehta** [comment]
You only get access to the ones checked in your user profile.

**Comment by fblauer** [comment]
But they are all checked in my user profile. Here is a screenshot of my
user profile:

[image: Inline image 1]

On Tue, May 12, 2015 at 8:45 AM, Rushabh Mehta <notifications@github.com>
wrote:

> You only get access to the ones checked in your user profile.
>
>
>
> > On 12-May-2015, at 5:52 pm, fblauer <notifications@github.com> wrote:
> >
> > When I click on all applications, only some of them show up. Also, is it
> > possible for him to give me access to setup?
> >
> > On Tue, May 12, 2015 at 8:19 AM, fred blauer <fblauer@gmail.com> wrote:
> >
> > > It doesn't seem to be fixed on my client's instance here:
> > > https://atservice.erpnext.com/desk
> > > They gave me access to all modules and all roles, and I only see some
> of
> > > them on my desktop?
> > > Here is a screenshot:
> > >
> > > [image: Inline image 1]
> > >
> > > On Tue, May 12, 2015 at 1:26 AM, Rushabh Mehta <
> notifications@github.com>
> > > wrote:
> > >
> > >> fixed.
> > >>
> > >> —
> > >> Reply to this email directly or view it on GitHub
> > >> <https://github.com/frappe/erpnext/issues/3243#issuecomment-101137558
> >.
> > >>
> > >
> > >
> > >
> > > --
> > > Fred Blauer CA, CPA, CISA
> > > http://openacct.ca
> > > 514-667-1555
> > >
> >
> >
> >
> > --
> > Fred Blauer CA, CPA, CISA
> > http://openacct.ca
> > 514-667-1555
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/frappe/erpnext/issues/3243#issuecomment-101257008>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/frappe/erpnext/issues/3243#issuecomment-101262650>.
>



-- 
Fred Blauer CA, CPA, CISA
http://openacct.ca
514-667-1555

**Comment by fblauer** [comment]
Here is the rest of my user profile:

[image: Inline image 1]

On Tue, May 12, 2015 at 8:47 AM, fred blauer <fblauer@gmail.com> wrote:

> But they are all checked in my user profile. Here is a screenshot of my
> user profile:
>
> [image: Inline image 1]
>
> On Tue, May 12, 2015 at 8:45 AM, Rushabh Mehta <notifications@github.com>
> wrote:
>
>> You only get access to the ones checked in your user profile.
>>
>>
>>
>> > On 12-May-2015, at 5:52 pm, fblauer <notifications@github.com> wrote:
>> >
>> > When I click on all applications, only some of them show up. Also, is it
>> > possible for him to give me access to setup?
>> >
>> > On Tue, May 12, 2015 at 8:19 AM, fred blauer <fblauer@gmail.com> wrote:
>> >
>> > > It doesn't seem to be fixed on my client's instance here:
>> > > https://atservice.erpnext.com/desk
>> > > They gave me access to all modules and all roles, and I only see some
>> of
>> > > them on my desktop?
>> > > Here is a screenshot:
>> > >
>> > > [image: Inline image 1]
>> > >
>> > > On Tue, May 12, 2015 at 1:26 AM, Rushabh Mehta <
>> notifications@github.com>
>> > > wrote:
>> > >
>> > >> fixed.
>> > >>
>> > >> —
>> > >> Reply to this email directly or view it on GitHub
>> > >> <
>> https://github.com/frappe/erpnext/issues/3243#issuecomment-101137558>.
>> > >>
>> > >
>> > >
>> > >
>> > > --
>> > > Fred Blauer CA, CPA, CISA
>> > > http://openacct.ca
>> > > 514-667-1555
>> > >
>> >
>> >
>> >
>> > --
>> > Fred Blauer CA, CPA, CISA
>> > http://openacct.ca
>> > 514-667-1555
>> > —
>> > Reply to this email directly or view it on GitHub <
>> https://github.com/frappe/erpnext/issues/3243#issuecomment-101257008>.
>>
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/frappe/erpnext/issues/3243#issuecomment-101262650>.
>>
>
>
>
> --
> Fred Blauer CA, CPA, CISA
> http://openacct.ca
> 514-667-1555
>



-- 
Fred Blauer CA, CPA, CISA
http://openacct.ca
514-667-1555

**Comment by fblauer** [comment]
Now, I am talking about this instance that my client setup:
https://atservice.erpnext.com/desk#

When you fixed it for my instance, was it an application problem or a
database problem?

On Tue, May 12, 2015 at 8:48 AM, fred blauer <fblauer@gmail.com> wrote:

> Here is the rest of my user profile:
>
> [image: Inline image 1]
>
> On Tue, May 12, 2015 at 8:47 AM, fred blauer <fblauer@gmail.com> wrote:
>
>> But they are all checked in my user profile. Here is a screenshot of my
>> user profile:
>>
>> [image: Inline image 1]
>>
>> On Tue, May 12, 2015 at 8:45 AM, Rushabh Mehta <notifications@github.com>
>> wrote:
>>
>>> You only get access to the ones checked in your user profile.
>>>
>>>
>>>
>>> > On 12-May-2015, at 5:52 pm, fblauer <notifications@github.com> wrote:
>>> >
>>> > When I click on all applications, only some of them show up. Also, is
>>> it
>>> > possible for him to give me access to setup?
>>> >
>>> > On Tue, May 12, 2015 at 8:19 AM, fred blauer <fblauer@gmail.com>
>>> wrote:
>>> >
>>> > > It doesn't seem to be fixed on my client's instance here:
>>> > > https://atservice.erpnext.com/desk
>>> > > They gave me access to all modules and all roles, and I only see
>>> some of
>>> > > them on my desktop?
>>> > > Here is a screenshot:
>>> > >
>>> > > [image: Inline image 1]
>>> > >
>>> > > On Tue, May 12, 2015 at 1:26 AM, Rushabh Mehta <
>>> notifications@github.com>
>>> > > wrote:
>>> > >
>>> > >> fixed.
>>> > >>
>>> > >> —
>>> > >> Reply to this email directly or view it on GitHub
>>> > >> <
>>> https://github.com/frappe/erpnext/issues/3243#issuecomment-101137558>.
>>> > >>
>>> > >
>>> > >
>>> > >
>>> > > --
>>> > > Fred Blauer CA, CPA, CISA
>>> > > http://openacct.ca
>>> > > 514-667-1555
>>> > >
>>> >
>>> >
>>> >
>>> > --
>>> > Fred Blauer CA, CPA, CISA
>>> > http://openacct.ca
>>> > 514-667-1555
>>> > —
>>> > Reply to this email directly or view it on GitHub <
>>> https://github.com/frappe/erpnext/issues/3243#issuecomment-101257008>.
>>>
>>> >
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/frappe/erpnext/issues/3243#issuecomment-101262650>.
>>>
>>
>>
>>
>> --
>> Fred Blauer CA, CPA, CISA
>> http://openacct.ca
>> 514-667-1555
>>
>
>
>
> --
> Fred Blauer CA, CPA, CISA
> http://openacct.ca
> 514-667-1555
>



-- 
Fred Blauer CA, CPA, CISA
http://openacct.ca
514-667-1555

**Comment by rmehta** [comment]
Can you add via GitHub. I am unable to see your images

**Comment by fblauer** [comment]
![image](https://cloud.githubusercontent.com/assets/1015215/7587981/fee88cf2-f887-11e4-9e58-bac72d337579.png)
![image 1](https://cloud.githubusercontent.com/assets/1015215/7587982/fee9c0e0-f887-11e4-94e5-4f7e20d02cd1.png)
Here are the images attached. They just show that everything is selected in the user profile for both module access and roles

**Comment by rmehta** [comment]
can you send me your login and password (of both accounts) at my email id?

**Comment by fblauer** [comment]
https://atservice.erpnext.com/desk#

info@airtemp.ca
password - steven

fblauer@gmail.com
password - f123red

**Comment by rmehta** [comment]
Seems like a permission configuration issue.

System looks okay

**Comment by fblauer** [comment]
So, I don't understand why granting access to all modules, and all roles would result in only some applications showing up for the user? How would an admin grant access to a user for all modules, including setup. I can't figure that out.

**Comment by rmehta** [comment]
Have you made changes in role permissions? This feature works quite well.

Also check if you have not hidden anything via setup > show hide modules

**Comment by fblauer** [comment]
Do you have any idea why this keeps popping up again over and over?
http://haquefoundation.eleadatabase.com/get_involved/donate/index.html
Does it have anything to do with Erpnext?

**Comment by fblauer** [comment]
The client created the instance, so I can't answer all of your questions, but I checked the system settings and none of the modules are hidden. Also, I can't figure out how to grant access to the administrator role?
