### ISSUE TITLE
Workflow Submit behaviour issue

### ISSUE THREAD

**Issue by monojoker** [frappe/erpnext#3244]
Guys,

When you change the Sales Order Workflow_state to a state where the docstatus=1 (Submitted) and you click Close instead of Yes to Submit then you "lose" the Actions button (only Save remains) and therefore you cannot re-Submit the order! We have an order in our system (M00121) which has this issue now.

![image](https://cloud.githubusercontent.com/assets/10917366/7577668/64d3bd10-f88e-11e4-9336-e65bf78dd130.png)

There is no way to revert this Workflow_state to Despatch and then re-submit via Workflow either. So order cannot be submitted.

It's clear a SEPARATE button for Workflow_state Action and Save/Submit needs to exist as per issue https://github.com/frappe/erpnext/issues/3236 reported earlier for this reason.

**Comment by rmehta** [comment]
Ah, this seems to be an issue. We will fix it, but you will have to manually edit this record.

**Comment by rmehta** [comment]
fixed
