### ISSUE TITLE
Issues with creating Material Request from Sales Order

### ISSUE THREAD

**Issue by lonovo** [frappe/erpnext#3246]
If there is an item in the sales order that has BOM associated with it. Pushing create Create Material Request should explode the item to raw material in the MR. But that doesn't happen and just one item is added to the MR. 

Sequence:
Selling --> Sales Order --> Create one with a finished product that has BOM with few items --> Make Material Request

**Comment by lonovo** [comment]
In the item details i have set "Supply Raw Materials for Purchase" to "Yes"

![erpnext sales order production request bug- photo 1](https://cloud.githubusercontent.com/assets/12406801/7624104/c4e6c460-fa26-11e4-9d23-efe5b66a8911.png)

**Comment by nabinhait** [comment]
Please use Production Planning Tool to create Material Request. Check https://manual.erpnext.com/contents/guide-books/make-to-stock/production-planning-tool
