### ISSUE TITLE
Invoice outstanding amount is higher than invoice amount

### ISSUE THREAD

**Issue by sumeetagra** [frappe/erpnext#32471]
### Information about bug

As per attached Screenshot, Customer Outstanding Amount against an Invoice is showing higher than the actual Invoice Amount. There is an error with the Payment Ledger Entry which is automatically created by the system.

### Module

accounts
![Screenshot 2022-10-03 at 1 18 30 PM](https://user-images.githubusercontent.com/19186564/193526680-c67e38b4-47cf-4a36-aee3-7cfa48f8db02.png)

### Version

ERPNext: v14.2.1 (version-14)

Frappe Framework: v14.9.0 (version-14)

Frappeauth App: v0.0.1 (master)

Frappe HR: v1.0.0 (develop)

India Compliance: v0.0.1 (develop)

Payments: v0.0.1 (develop)

**Comment by ruthra-kumar** [comment]
Check the Payment Ledger entries for this invoice. Go to Payment Ledger Entry -> report view -> apply filter on `Against Voucher No` == Sales Invoice and `delinked`  == No. Ideally, the total amount on the filtered entries should add up to the outstanding amount.
Can you post those entries?

**Comment by sumeetagra** [comment]
Attached screenshot for your reference. In this case I've applied a filter
on 1 invoice, there are 3 ledger entries coming up for the same invoice.
The total Invoice value is Rs.372640.00, but the total Payment ledger value
is 3 times of the invoice value.


Best Regards
Sumeet Goyal | Director
Goyal Group

**Comment by ruthra-kumar** [comment]
screenshot is missing

**Comment by sumeetagra** [comment]
![Screenshot 2022-10-06 at 6 56 08 PM](https://user-images.githubusercontent.com/19186564/194510886-7ca38e23-30f1-4f4a-952f-71e5b9bbadb0.png)

**Comment by ruthra-kumar** [comment]
Is there any payment made for these Invoices? Is the `Update Stock` checkbox enabled for this invoice?
In the screenshot you've filtered on `Voucher No`. But to analyze further, do a filter on `Against Voucher No` with the same invoice no like shown below and post a screenshot.

<img width="1099" alt="Screenshot 2022-10-07 at 4 31 02 PM" src="https://user-images.githubusercontent.com/3272205/194538712-6976b1c7-2107-400a-814e-568acb0e0d14.png">

**Comment by sumeetagra** [comment]
![Screenshot 2022-10-07 at 4 46 38 PM](https://user-images.githubusercontent.com/19186564/194541018-3c0eace5-12d8-4604-b309-5fdc0a236b27.png)

Attached Screen shot as per mentioned filters. No payment is made for this invoice yet. Update Stock checkbox is enabled.

**Comment by NEW-MTC-ERP1** [comment]
same issue here, 
Outstanding amount is double the invoice amount, this goes for purchase and sales invoices, knowng that no payments have been made for these transactions:
<img width="431" alt="image" src="https://user-images.githubusercontent.com/114433956/194689450-c215c438-da0f-403a-9126-47d37f35c442.png">
<img width="365" alt="image" src="https://user-images.githubusercontent.com/114433956/194689477-1e9e1671-209c-438e-aedf-6bc38e36d3b9.png">

Please help

**Comment by ruthra-kumar** [comment]
This is wierd. There seems to be duplicate entries on Payment Ledger for that Invoice, yet the outstanding doesn't match the total of those entries.

**Comment by sumeetagra** [comment]
Duplicate Payment Ledger Entries of old Invoices are still not removed. They are still affecting the outstanding Amount of the Invoice. Because of this, Outstanding Amount is still higher than the Invoice Amount for ld records.

Attached Screen Shots.

![Screenshot 2022-12-14 at 4 39 16 PM](https://user-images.githubusercontent.com/19186564/207580000-902a0e80-c6ad-4e21-913d-82bbc7b6c431.png)

**Comment by ruthra-kumar** [comment]
You can use the `Repost Payment Ledger` doctype to fix this. Check PR description for details https://github.com/frappe/erpnext/pull/32742

**Comment by sumeetagra** [comment]
Getting the following Error on Repost Payment Ledger:

### App Versions
```
{
	"erpnext": "14.10.1",
	"frappe": "14.19.1",
	"frappeauth_app": "0.0.1",
	"hrms": "1.0.0",
	"india_compliance": "14.0.5",
	"payments": "0.0.1"
}
```
### Route
```
Form/Repost Payment Ledger/f51e63fe62
```
### Trackeback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1590, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 21, in savedocs
    doc.submit()
  File "apps/frappe/frappe/model/document.py", line 998, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 977, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 303, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 354, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1078, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 907, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1259, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1241, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 904, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/repost_payment_ledger/repost_payment_ledger.py", line 94, in on_submit
    execute_repost_payment_ledger(self.name)
  File "apps/erpnext/erpnext/accounts/doctype/repost_payment_ledger/repost_payment_ledger.py", line 104, in execute_repost_payment_ledger
    if not frappe.utils.background_jobs.is_job_queued(job_name):
AttributeError: module 'frappe.utils.background_jobs' has no attribute 'is_job_queued'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"name\":\"f51e63fe62\",\"owner\":\"sg@goyalironsteel.com\",\"creation\":\"2022-12-14 16:56:51.546040\",\"modified\":\"2022-12-14 16:59:47.538329\",\"modified_by\":\"sg@goyalironsteel.com\",\"docstatus\":0,\"idx\":0,\"company\":\"GOYAL IRON & STEEL (NAGPUR) PVT LTD\",\"posting_date\":\"2022-12-14\",\"add_manually\":1,\"repost_status\":\"Queued\",\"doctype\":\"Repost Payment Ledger\",\"repost_vouchers\":[{\"name\":\"4355f1b811\",\"creation\":\"2022-12-14 16:59:10.276632\",\"modified\":\"2022-12-14 16:59:47.538329\",\"modified_by\":\"sg@goyalironsteel.com\",\"docstatus\":0,\"idx\":1,\"voucher_type\":\"Sales Invoice\",\"voucher_no\":\"GI23/00050\",\"parent\":\"f51e63fe62\",\"parentfield\":\"repost_vouchers\",\"parenttype\":\"Repost Payment Ledger\",\"doctype\":\"Repost Payment Ledger Items\",\"owner\":\"sg@goyalironsteel.com\"}]}",
		"action": "Submit"
	},
	"btn": {
		"jQuery360049962716137177531": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 3523,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs"
}
```
### Response Data
```
{
	"exception": "AttributeError: module 'frappe.utils.background_jobs' has no attribute 'is_job_queued'"
}
```

**Comment by techfordai** [comment]
I am facing the same error. For many sales invoices, the outstanding amount is higher than grand total. 

Although the invoice is create by a different user. The payment ledger entry is being shown as added by administrator user ID. 

Why is this happening? Is it something to do with the settings?

**Comment by lafi87** [comment]
> You can use the `Repost Payment Ledger` doctype to fix this. Check PR description for details #32742

Thank you very much, this solved the duplication problem.
