### ISSUE TITLE
Additional discount bug 

### ISSUE THREAD

**Issue by error-id** [frappe/erpnext#32485]
### Information about bug

Conditions :  pricing rule set for particular customer.
new quotation based on the customer and pricing rule automatic applied.

when adding additional discount. (based on net total ) the discount is applied but not the final total amount is not changed. 
(grand total is not changed.)  the grand total shall be (Net total - addition discount(based on net toal ) Plus Tax

Once the additional discount is edited . but it wont be saved. The calculation of the payment will apply the discount . but the Grand total wont change.

### Module

selling

### Version

Frappe Version : V14.9.0
Erpnext Version: V14.2.1

### Installation method

manual install

**Comment by maharshivpatel** [comment]
I am unable to reproduce the issue. please update to the latest version and let me know if issue still persists. If you still face the issue please share your pricing rule settings along with step by step instructions to reproduce.
