### ISSUE TITLE
app store for third party apps

### ISSUE THREAD

**Issue by AlexanderF123** [frappe/erpnext#32483]
Like with other platforms there exist third party apps that extend and improve ERPnext. It would be great to find them in one place. Similar to odoo.

Also it would be great to install them using an app store.

**Comment by dj12djdjs** [comment]
You can find apps on the frappe cloud market place: https://frappecloud.com/marketplace

**Comment by ankush** [comment]
There's also: https://github.com/gavindsouza/awesome-frappe
