### ISSUE TITLE
Distributed cost centers for an employee

### ISSUE THREAD

**Issue by dakshithasp** [frappe/erpnext#32487]
### Information about bug

Hi All,

Is there a way to assign a single employee to multiple cost centers based on percentages?

There is an ERPNext documentation page under salary structure assignment which cannot be actually found under the salary structure assignment page on the system (https://docs.erpnext.com/docs/v13/user/manual/en/human-resources/payroll-entry)..

Should we adjust the salary structure assignment doctype and insert a table like in the above screenshot? Or is there already a method to assign a single employee to multiple cost centers based on different percentages?

### Module

HR

### Version

ERPNext Version - 13

**Comment by deepeshgarg007** [comment]
@dakshithasp Please refer to this https://docs.erpnext.com/docs/v13/user/manual/en/accounts/distributed-cost-center for enabling distributed cost center. 

In version 13 it only works on the report level and there is no effect on the GL entries, from v14 onwards this have been moved to Cost center allocation and also has an effect on GL Entries

https://docs.erpnext.com/docs/v14/user/manual/en/cost_center_allocation

**Comment by dakshithasp** [comment]
Hi Deepesh,

Does this mean that the distributed cost center will be an option for employees as well? during which we can allocate their cost under different cost centers at the time a salary structure is assgned to them?
