### ISSUE TITLE
Bug overbilling negative amounts v5

### ISSUE THREAD

**Issue by betabank** [frappe/erpnext#3249]
Hi,

when setting overbilling in stock settings, is working for items with positive prices, but not with items with negative prices. The problem is the logic, allows until the overbilling amount.
For example, 10% overbilling works for an item that costs $10. Price must bs lower than $11.
But with an item that costs -10$ (return) then the price must be lower than -11$. Should be greater than -11$.

**Comment by nabinhait** [comment]
Any use case when item rate is negative?

**Comment by betabank** [comment]
Yes, for material assets, returned empties. For example with drinks and food. Also for services, any form of deposit that is returned after the service.

**Comment by nabinhait** [comment]
currently, invoice is not designed for stock return. Though I will check into the overbilling issue.

May be you should proceed with stock entry for return.

**Comment by betabank** [comment]
We have experience already on this with v4. The problem is that the returned goods are delivered and billed and then in the next delivery they are deducted and billed. We found no other choice than creting items with negative prices, this solution works pretty good for us.

**Comment by rmehta** [comment]
+1 I think we should fix this.

**Comment by nabinhait** [comment]
will fix this

**Comment by nabinhait** [comment]
@betabank Could not replicate.. can you write down the steps?

**Comment by betabank** [comment]
You need to set the overbilling to 10% for example.

You need to create an item with negative price, then make a sales order with some items with positive prices and the item with negative price. The overall must be >0. The progress to DN, then to SINV.

Then in the SINV, you will not be able to save because the item with negative value must be under 110% of its value, which is impossible.
