### ISSUE TITLE
Usability suggestion for multiple select item in v5

### ISSUE THREAD

**Issue by betabank** [frappe/erpnext#3250]
Hi,

this feature is great, in v5 clicking in the item code, appears a new window to set quantity.

But, it would be better that before the item code, there would be the Qty. field by default set to 1 and then by clicking the item code, the Qty. desired is added.

Otherwise, there are too many clicks for single or low quantity items. We can send a prototype if needed.

**Comment by PawanMeh** [comment]
Have you tried the latest version, maybe it meets your requirements. If not, please attach mock up design & re-open issue.
