### ISSUE TITLE
Subscription Plan doctype is calculating incorrect number of months for Monthly price rate

### ISSUE THREAD

**Issue by codezart** [frappe/erpnext#32511]
### Information about bug

https://github.com/frappe/erpnext/blob/da43a5e371dede52acd26791ffa80ba4a13fc0ef/erpnext/accounts/doctype/subscription_plan/subscription_plan.py#L52

The `Subscription Plan` doctype, is counting an extra month for subscriptions when the plan's price determination is set to "Monthly" and the billing is yearly.

Instead of counting 12 months it is counting 13.

### Module

accounts

### Version

Frappe Version - version-14
ERPNext Version - version-14

**Comment by deepeshgarg007** [comment]
@codezart let's consider a standard year and start date as 2022-01-01 and end date as 2022-12-31, so as per this the no of months will be (2022-2022) * 12 + (12-1) + 1 = 12 which is correct, maybe the dates that you have set up seems incorrect. Please add the dates that you have used and reopen the issue if it still persists

**Comment by codezart** [comment]
@deepeshgarg007 
if the start_date is 2022-01-05 and
end_date is 2023-01-04

Then the number of months will be : (2023-2022) * 12 + (1-1) + 1 = 13

I think it would be better to use relativedelta.

https://github.com/frappe/erpnext/pull/32551
