### ISSUE TITLE
Employee Cost Center Distribution

### ISSUE THREAD

**Issue by dakshithasp** [frappe/erpnext#32517]
### Information about bug

Hi All,

Is there a way to assign a single employee to multiple cost centers based on percentages?

There is an ERPNext documentation page under salary structure assignment which cannot be actually found under the salary structure assignment page on the system (https://docs.erpnext.com/docs/v13/user/manual/en/human-resources/payroll-entry)..

Should we adjust the salary structure assignment doctype and insert a table like in the above screenshot? Or is there already a method to assign a single employee to multiple cost centers based on different percentages?

**@deepeshgarg007 - Do not close this without giving a proper solution.**

### Module

HR

### Version

ERPNext Version - 13

**Comment by ruchamahabal** [comment]
@dakshithasp this feature is available in v14 not v13. Upgrade to v14 and install the hrms app to get this feature https://github.com/frappe/hrms
<img width="1295" alt="image" src="https://user-images.githubusercontent.com/24353136/195836007-acc357fe-8669-44f6-b863-5d7a4908e53c.png">
