### ISSUE TITLE
Can't login to translate with GitHub API

### ISSUE THREAD

**Issue by Quentoo** [frappe/erpnext#3252]
Hello everybody, 

if i would create a account on https://translate.erpnext.com/login (Login with GitHub) i become this error message: 
![123123](https://cloud.githubusercontent.com/assets/1480580/7598703/9622b13c-f8fc-11e4-9d5a-1e6b1d68745c.JPG)

**Comment by anandpdoshi** [comment]
Fixed

**Comment by Quentoo** [comment]
Thanks, try again soon as possible.

**Comment by Quentoo** [comment]
Fix confirmed
