### ISSUE TITLE
All Applications is visible even if unchecked from User's Modules list

### ISSUE THREAD

**Issue by anandpdoshi** [frappe/erpnext#3253]
![project settings](https://cloud.githubusercontent.com/assets/836785/7599766/c4142fbe-f8b9-11e4-97f8-cbfaf798f1ad.jpg)
![projects user](https://cloud.githubusercontent.com/assets/836785/7599767/c59fc4c4-f8b9-11e4-8e67-b274ab273296.jpg)

by Ihab

**Comment by rmehta** [comment]
fixed via cache bug-fix
