### ISSUE TITLE
Opening a Sales Invoice without making changes gives "Not Saved" Alert incorrectly

### ISSUE THREAD

**Issue by monojoker** [frappe/erpnext#3254]
Guys,

In V5 when you open a Sales Invoice just to view - you make NO changes - it comes up immediately saying "Not Saved".

![image](https://cloud.githubusercontent.com/assets/10917366/7600254/e5d0807e-f94c-11e4-9082-a2b349bd0754.png)

 This confuses the user and when they click "Update" it gives an error saying you cannot change "In Words" after submission.

![image](https://cloud.githubusercontent.com/assets/10917366/7600279/0f5c9db0-f94d-11e4-9b47-d978e65f1bd4.png)

I'm guessing this is a bug to be fixed.

**Comment by rmehta** [comment]
Can you replicate this on demo.erpnext.com <http://demo.erpnext.com/>

Do you have a custom script that is setting values `onload`?

**Comment by monojoker** [comment]
Yes I have custom script onload:
```javascript
frappe.ui.form.on('Sales Invoice', 'onload', function(frm){
    if (frm.doc.customer){
        frappe.ui.form.trigger(frm.doc.doctype, 'customer');
    }
})
```

**Comment by rmehta** [comment]
You should add:

```
if (frm.doc.customer && frappe.doc.docstatus==0) {
```

Also please consider https://erpnext.com/pricing/assisted-development

Giving free customization support is hurting us very badly.
