### ISSUE TITLE
V14 Stuck at Migration

### ISSUE THREAD

**Issue by piratedkhan** [frappe/erpnext#32547]
### Information about bug

I was importing a v13 database to v14. everything was perfect but after importing when `execute bench --site [sitename] migrate`
the process is stuck the following step
`Executing erpnext.patches.v14_0.migrate_remarks_from_gl_to_payment_ledger in demo (_3cbf127f0870293e)`

even if i perform bench update --reset it get stuck at the same step

### Module

other

### Version

ERPNext: v14.2.3 (version-14)
Frappe Framework: v14.10.0 (version-14)

### Installation method

manual install

**Comment by ruthra-kumar** [comment]
Should be fixed by https://github.com/frappe/erpnext/pull/32501
Fix will be available on upcoming minor release v14.2.4

**Comment by ruthra-kumar** [comment]
Fix released on V14.3.0

**Comment by piratedkhan** [comment]
i have updated erpnext to V14.3.0
but still stuck at the same place i have check the patch file there are no changes has been made.

**Comment by ruthra-kumar** [comment]
[Patch File](https://github.com/frappe/erpnext/blob/develop/erpnext/patches/v14_0/migrate_remarks_from_gl_to_payment_ledger.py) has been updated on [V14.3.0](https://github.com/frappe/erpnext/pull/32501#issuecomment-1276075933). Make sure the `bench update` does update the patch file with latest changes.

**Comment by piratedkhan** [comment]
i have done bench update and also freshly installed it on another server and my erpnext is v14.3.0 but it get stuck at the same step when importing v13 database on migration.

this issue has been launched 10 days ago while the last commit to file was 16 days ago so i guess the file is not updated yet
