### ISSUE TITLE
Tax based on shipping address

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#3255]
- [ ] In address set default tax
- [ ] Add a rule based tax system (if zip / pin starts with xxx, then apply this tax)
- [ ] Pull default tax from shipping address select.

**Comment by rmehta** [comment]
Estimate
- [ ] 0.5 - Make Rule Engine - `For DocType X, if field Y (=, <, >, contains, startswith) Z, then A = B`
- [ ] 1.0 - Make a hook to apply generic rule engine
- [ ] 2.5 - Build
- [ ] 1.0 Test Cases

Total 5 hours

**Comment by anandpdoshi** [comment]
Isn't taxation based on billing address and only shipping charge based on shipping address?

**Comment by ItsRaichura** [comment]
Tax Should be based on Territory of Customer.
Say for example, I am a manufacturer from Gujarat state in India. Anything that I sell within my state is to be taxed under Gujarat VAT, anything that I sell out side gujarat is taxed under Central Government sales tax.

So I make territories as follows:
India >> Gujarat
India >> Outside Gujarat

Outside Gujarat >> North
Outside Gujarat >> South
Outside Gujarat >> West
Outside Gujarat >> East
and so on..

PS. It is possible that I sell goods to ABC India, situated in Mumbai, apply Central Govt Sales Tax and Ship goods to its warehouse located in Gujarat. It is always the billing address that should determine taxation
