### ISSUE TITLE
Error 1176 'item_warehouse' doesn't exist

### ISSUE THREAD

**Issue by kn0xit** [frappe/erpnext#32552]
### Information about bug

I have setup a fresh install of erpnext v14.2.3 on osx 12.6.1 through Docker 20.10.17.

When trying to create a new purchase invoice as the first task after the setup routine, I receive following error:
Server Error
pymysql.err.OperationalError: (1176, "Key 'item_warehouse' doesn't exist in table 'tabStock Ledger Entry'")

I checked the database, the table 'tabStock Ledger Entry' with many entries, but in fact 'item_warehouse' is not one of them.

Any help/resolution is much appreciated.

### Module

accounts

### Version

Installed Apps
ERPNext: v14.2.3
Frappe Framework: v14.10.0
Payments: v0.0.1

### Installation method

docker

**Comment by kn0xit** [comment]
I still have the same issue with a fresh installation of the following versions:
ERPNext: v14.3.0
Frappe Framework: v14.11.1

**Comment by s-aga-r** [comment]
@kn0xit Could you share the browser console log? It will help us to find the cause.

**Comment by kn0xit** [comment]
/api/method/frappe.desk.form.save.savedocs:1          Failed to load resource: the server responded with a status of 500 (Internal Server Error)
request.js:462 Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1585, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 23, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 303, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 325, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 257, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1058, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 930, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1270, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1252, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 927, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py", line 87, in validate
    super(PurchaseInvoice, self).validate()
  File "apps/erpnext/erpnext/controllers/buying_controller.py", line 33, in validate
    super(BuyingController, self).validate()
  File "apps/erpnext/erpnext/controllers/subcontracting_controller.py", line 52, in validate
    super(SubcontractingController, self).validate()
  File "apps/erpnext/erpnext/controllers/stock_controller.py", line 45, in validate
    super(StockController, self).validate()
  File "apps/erpnext/erpnext/controllers/accounts_controller.py", line 154, in validate
    self.set_incoming_rate()
  File "apps/erpnext/erpnext/controllers/buying_controller.py", line 297, in set_incoming_rate
    outgoing_rate = get_incoming_rate(
  File "apps/erpnext/erpnext/stock/utils.py", line 300, in get_incoming_rate
    in_rate = get_valuation_rate(
  File "apps/erpnext/erpnext/stock/stock_ledger.py", line 1252, in get_valuation_rate
    last_valuation_rate = frappe.db.sql(
  File "apps/frappe/frappe/database/database.py", line 207, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1176, "Key 'item_warehouse' doesn't exist in table 'tabStock Ledger Entry'")

(anonymous) @ request.js:462
DevTools failed to load source map: Could not load content for webpack://Quill/node_modules/quill-delta/dist/Delta.js.map: Fetch through target failed: Unsupported URL scheme; Fallback: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

**Comment by kn0xit** [comment]
Shared error message from the console above.

Also, in the meantime, I have found out that stopping the docker containers and starting them again resolves the issue. To test this, I reinstalled from scratch, and the error was back when I would try to enter a purchase invoice right after the setup wizard. Restart would again resolve this.

Is restarting the container after the setup wizard a normal requirement of some sorts in order for things to work?

**Comment by ankush** [comment]
`item_warehouse` is an index that someone might have dropped by mistake?

Running this should fix it technically:

https://github.com/frappe/erpnext/blob/dc3fe8592187bf543eae628c639868de84ad9006/erpnext/stock/doctype/stock_ledger_entry/stock_ledger_entry.py#L234

**Comment by kn0xit** [comment]
Not sure whether the field is required at all or if this error ist just an initial setup issue. As I mentioned, after restarting all containers once after install the error message disappears. Also, checking the database directly, the field item_warehouse still doesn't exist (see below).

MariaDB [xxx]> describe \`tabStock Ledger Entry\`;
+---------------------------------+---------------+------+-----+-------------+-------+
| Field                           | Type          | Null | Key | Default     | Extra |
+---------------------------------+---------------+------+-----+-------------+-------+
| name                            | varchar(140)  | NO   | PRI | NULL        |       |
| creation                        | datetime(6)   | YES  |     | NULL        |       |
| modified                        | datetime(6)   | YES  | MUL | NULL        |       |
| modified_by                     | varchar(140)  | YES  |     | NULL        |       |
| owner                           | varchar(140)  | YES  |     | NULL        |       |
| docstatus                       | int(1)        | NO   |     | 0           |       |
| idx                             | int(8)        | NO   |     | 0           |       |
| item_code                       | varchar(140)  | YES  | MUL | NULL        |       |
| warehouse                       | varchar(140)  | YES  | MUL | NULL        |       |
| posting_date                    | date          | YES  | MUL | NULL        |       |
| posting_time                    | time(6)       | YES  |     | NULL        |       |
| voucher_type                    | varchar(140)  | YES  |     | NULL        |       |
| voucher_no                      | varchar(140)  | YES  |     | NULL        |       |
| voucher_detail_no               | varchar(140)  | YES  | MUL | NULL        |       |
| dependant_sle_voucher_detail_no | varchar(140)  | YES  |     | NULL        |       |
| recalculate_rate                | int(1)        | NO   |     | 0           |       |
| actual_qty                      | decimal(21,9) | NO   |     | 0.000000000 |       |
| qty_after_transaction           | decimal(21,9) | NO   |     | 0.000000000 |       |
| incoming_rate                   | decimal(21,9) | NO   |     | 0.000000000 |       |
| outgoing_rate                   | decimal(21,9) | NO   |     | 0.000000000 |       |
| valuation_rate                  | decimal(21,9) | NO   |     | 0.000000000 |       |
| stock_value                     | decimal(21,9) | NO   |     | 0.000000000 |       |
| stock_value_difference          | decimal(21,9) | NO   |     | 0.000000000 |       |
| stock_queue                     | text          | YES  |     | NULL        |       |
| company                         | varchar(140)  | YES  | MUL | NULL        |       |
| stock_uom                       | varchar(140)  | YES  |     | NULL        |       |
| project                         | varchar(140)  | YES  |     | NULL        |       |
| batch_no                        | varchar(140)  | YES  | MUL | NULL        |       |
| fiscal_year                     | varchar(140)  | YES  |     | NULL        |       |
| serial_no                       | longtext      | YES  |     | NULL        |       |
| is_cancelled                    | int(1)        | NO   |     | 0           |       |
| to_rename                       | int(1)        | NO   | MUL | 1           |       |
| _user_tags                      | text          | YES  |     | NULL        |       |
| _comments                       | text          | YES  |     | NULL        |       |
| _assign                         | text          | YES  |     | NULL        |       |
| _liked_by                       | text          | YES  |     | NULL        |       |
+---------------------------------+---------------+------+-----+-------------+-------+
36 rows in set (0.002 sec)

**Comment by ankush** [comment]
It's not a field/column, it's an index.
