### ISSUE TITLE
Allow sending email from multiple outgoing emails

### ISSUE THREAD

**Issue by betabank** [frappe/erpnext#3256]
Hi, although v5 allows multiple outging emails, it is actually sending only from the default. Here is more info:
https://discuss.frappe.io/t/how-it-works-with-multiple-outgoing-emails/5824

**Comment by betabank** [comment]
Please, take this discussion in mind. It would be good that when this feature is implemented, the attached files in the email account setup are available for all emails sent from that email outgoing account.

https://discuss.frappe.io/t/issues-attach-file-global/5903

**Comment by umairsy** [comment]
Updated with Email inbox feature in ERPNext version 8.
