### ISSUE TITLE
Corrective Job Card Cost Calculation Incorrect

### ISSUE THREAD

**Issue by erpitadmin** [frappe/erpnext#32564]
### Information about bug

The current corrective job card calculation is using time in minutes multiply by the hourly rate which is incorrect. It should be `flt(row.total_time_in_mins) * flt(row.hour_rate / 60)`

Following is the section of code that have issue:
[Github Link](https://github.com/frappe/erpnext/blob/develop/erpnext/manufacturing/doctype/job_card/job_card.py#L455)
```
def update_corrective_in_work_order(self, wo):
		wo.corrective_operation_cost = 0.0
		for row in frappe.get_all(
			"Job Card",
			fields=["total_time_in_mins", "hour_rate"],
			filters={"is_corrective_job_card": 1, "docstatus": 1, "work_order": self.work_order},
		):
			wo.corrective_operation_cost += flt(row.total_time_in_mins) * flt(row.hour_rate)

		wo.calculate_operating_cost()
		wo.flags.ignore_validate_update_after_submit = True
		wo.save()
```

### Module

manufacturing

### Version

Frappe version - v14.10.0
ERPNext Version - v14.2.2

### Installation method

FrappeCloud

**Comment by s-aga-r** [comment]
@rohitwaghchaure
