### ISSUE TITLE
Invalid field name: enable_discount_accounting

### ISSUE THREAD

**Issue by hameedacpa** [frappe/erpnext#32569]
### Information about bug

Recently after the last update I got this message when trying to submit the purchase invoice

![2022-10-10_16-12-41](https://user-images.githubusercontent.com/84820402/195160638-cfae14a1-8d6e-4980-bdc8-fe36f6ce55e9.jpg)

### Module

accounts, buying

### Version

erpnext 14.2.3
frappe 14.10.0
hrms 1.0.0
payments 0.0.1

**Comment by s-aga-r** [comment]
enable_dicount_accounting field removed in https://github.com/frappe/erpnext/pull/32368

**Comment by ruthra-kumar** [comment]
@hameedacpa can you post the traceback from browser console.

**Comment by hameedacpa** [comment]
this error not showing anymore since I done update and restart the server
