### ISSUE TITLE
Different Email address defaults for different DocTypes

### ISSUE THREAD

**Issue by monojoker** [frappe/erpnext#3257]
On submit of Quotation, Sales Order and Sales Invoice we trigger emails to customers and attach the relevant Print Format. Is there a way to have a different email address default for each DocType? For example the customer contact who requests the Quotation is often different to the person who needs Sales Order confirmation and VERY OFTEN different to the customer contact who should receive the invoices.

It would be beneficial to have a selection tickbox against customer contacts/emails to determine which receives what doctypes.

Note: Requested as per @rmehta : https://discuss.frappe.io/t/different-email-address-defaults-for-different-doctypes/5835

**Comment by rmehta** [comment]
Implementing one default type would be easy, multiple default types could be hard as we would have to add a table of all document types for which this user is default.

**Comment by umairsy** [comment]
Closing issue inactive from very long. For now, please consider customizing this in your ERPNext account. Feel free to start a post on discuss.erpnext.com for discussion.
