### ISSUE TITLE
Convert Lead into Contact of a Customer

### ISSUE THREAD

**Issue by betabank** [frappe/erpnext#3258]
Hi, we would expect that the status of the lead is changed to converted only when is associated to a customer, a new one or an existing one.

We can help in the front-end and workflow definition of this feature.

**Comment by rmehta** [comment]
Can you explain the workflow?

**Comment by betabank** [comment]
The best would be to offer an action "Link with Customer" that can be available with converted status.

The user-side workflow would be as follows:

The user sets a lead Status to converted, like now. The linking depends if the email is already in the contact database or not:

If already exists a contact with the same email as the lead, the lead is automatically linked with this contact upwards. This means for example, that the communication of the lead is available also in the contact DocType. Now they are separate and the lead information is not available at a contact level. Probably, it is not expected that the contact information is updated in the lead, therefore "upwards".

If the email does not belong to any contact, a new action "Link with Customer" can be offered. By clicking "Link with Customer", the user selects an existing customer con confirms.

The system should create a new contact of the selected customer with the lead data. Again, the lead contact information is available at contact level. Duplication of the contacts is avoided because of the previous check.

**Comment by rmehta** [comment]
Ideally lead and contact should be same (lead / customer should just be a status)

https://github.com/frappe/erpnext/issues/342

**Comment by ttl76543** [comment]
:+1: Agreed — absolutely. Why enter contact info for the same person more than once?

> Ideally lead and contact should be same (lead / customer should just be a status)

**Comment by cgpurbaugh** [comment]
@rmehta Should Lead/Contact be the same or Lead/Customer?

**Comment by rmehta** [comment]
I think this is fixed now. If Lead is Company, it becomes the Customer and the person "Contact"
