### ISSUE TITLE
Conversion Factor

### ISSUE THREAD

**Issue by ruchin78** [frappe/erpnext#3259]
Where there are more than one conversion factor for an item for example Pack and Number.
A pack has 250 Number. Now my default UOM is Number as we do all the transactions in number whereas vendor supply the material in pack therefore we have added one more UOM and conversion factor for pack.

Now the problem is when user created material request for the purpose of "Purchase", item where purchase UOM is different for stock UOM.
Then in that case system should have an option to select the purchase UOM because when the material request will be converted to Supplier Quotation then we will not be able to enter the exact quotation received from supplier because supplier has send the quotation in Purchase UOM, then in that case we have to manually do the conversion and put the rates accordingly. It is very painful specially when you have more items in PO like in my case I have 42 items in PO and most of the items are like this only.

I appreciate if you can give some solution for the same.

**Comment by rmehta** [comment]
Same as #3260 

(closing this, as the other issue is clearer)
