### ISSUE TITLE
Sales Order Stock Reservation

### ISSUE THREAD

**Issue by rohitwaghchaure** [frappe/erpnext#32602]

**Comment by sjain17** [comment]
I am also looking for this feature. Is this already approved or will be developed in coming releases?

**Comment by jigneshpshah** [comment]
**Design idea :**

Design could be similar to Goods in Transit Warehouse  concept ( Reserved Warehouse) . with stock transfer entry  having SO & So Item reference.

Provide button on submitted SO ( Reserve/ Release button ).

On reserve get reservation request, ask: Release Type : Manual / Time based .  If time based, Reservation Upto date time.

Put in SO Item custom section : Reservation Information.
Reserved Qty in Stock UOM.
Release Type:  Manual  / Time Based
Release Date Time  

Show in SO connections Reservation section : Stock Entry which will have the SO reference.

On such Stock Entry give button to release which is nothing but cancel the Stock Entry.

In the above design reference storing can be of SO & SO Item in Stock Entry Details.

The reservation fields in SO Item will go blank  on Release of reservation.

Can have a background job if time based, to cancel the stock transfer entry.

On creating Delivery Note from SO having reservation on save of DN don't allow , stop by informing "Please cancel the reservation against the Sales Order".

**Comment by deepeshgarg007** [comment]
Done via https://github.com/frappe/erpnext/pull/34805, closing
