### ISSUE TITLE
Mistake in titling of ERPNext V14

### ISSUE THREAD

**Issue by Abdody84** [frappe/erpnext#32609]
### Information about bug

When we select customer tab, directory is showing retail by mistake and of course, when we press retail, system give an error

![IiOpMKW](https://user-images.githubusercontent.com/115890027/195997266-4166f69d-14e6-4a62-a2ea-6b9d74312d47.png)
![OKM96OO](https://user-images.githubusercontent.com/115890027/195997276-65a4a2a7-1446-459c-9bd0-ec0fd76a18b2.png)

### Module

selling

### Version

ERPNext Version 14

### Installation method

FrappeCloud

**Comment by Solufyin** [comment]
Hi @Abdody84,

Please remove Selling from workspace of Retail.

![image](https://user-images.githubusercontent.com/34390782/196167772-6f5a4d6b-b879-468f-ba8a-b6268a7444d9.png)

After then reload (Ctrl + Shift + R) and check it.

Thank You!

**Comment by deepeshgarg007** [comment]
@Abdody84 This looks because of some customization in the workspace that you have made. On other sites seems to be working fine
