### ISSUE TITLE
Dark Mode do not show help in pricing rule

### ISSUE THREAD

**Issue by sjain17** [frappe/erpnext#32611]
### Information about bug

Before selecting -
![Screenshot 2022-10-16 at 7 05 35 PM](https://user-images.githubusercontent.com/30950233/196043213-5a6eb036-25ed-4acd-9b34-50ba0afffe52.png)

After selecting -
![Screenshot 2022-10-16 at 7 05 54 PM](https://user-images.githubusercontent.com/30950233/196043187-6d9436a7-4fa6-46d5-b1d8-64825793b2b6.png)

### Module

selling

### Version

Frappe Version -13
ERPNext Version -13

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
In Dark mode help content is not visible due to white background and white font.
```

**Comment by s-aga-r** [comment]
@sjain17 

Fixed and released in [v13.15.0](https://github.com/frappe/erpnext/pull/28508). I think you are using an older version, please update to get this fixed.
ref: https://github.com/frappe/erpnext/pull/28408 

![image](https://user-images.githubusercontent.com/63660334/196119699-31e09cec-10a8-4a1b-90ee-d080f8145753.png)
