### ISSUE TITLE
Items Image Clipping

### ISSUE THREAD

**Issue by innovast-technology** [frappe/erpnext#32610]
### Information about bug

Using erpnext V14

When I upload an item images a clipping window appears before uplaod. The area is very small and not suitable for many items

### Module

stock

### Version

erpnext 14.3.0
frappe 14.11.1
hrms 1.0.0
payments 0.0.1

**Comment by s-aga-r** [comment]
@innovast-technology Could you please add screenshots for the same?

**Comment by innovast-technology** [comment]
![image](https://user-images.githubusercontent.com/40541181/196540614-0915aa5a-683b-4102-bf34-84beac6c6ba2.png)

**Comment by s-aga-r** [comment]
@innovast-technology 

1:1 is the ideal aspect ratio for the thumbnails and if you use 1:1 images it will work fine. See the below screenshot.

![image](https://user-images.githubusercontent.com/63660334/196752096-cff7cc9e-8bbd-48b6-ab50-e811af818e37.png)

**Comment by innovast-technology** [comment]
While this is a design decision left to your team (Which is doing a great job no doubt ) , I think this will create usability issues for stock with large number of items. V13 was more flexible.
