### ISSUE TITLE
[Paid Development] Improvements in Item Variants

### ISSUE THREAD

**Issue by adityaduggal** [frappe/erpnext#3261]
Currently Item variants cannot handle the following:
1. Variant fields which are not needed in Item Naming.
2. Variant fields which are Floats
3. Define filters according to which the customers can browse the website.

Suppose we want to make an Item Variant for LCD TV. The following fields would be used:
1. Type of TV (LCD, Plasma, CRT etc)
2. Size of TV (20", 22", 24" etc)

Now if we create the item variant then it would create 3x3 = 9 item codes for the variant but what if we had a range of size from 20" to 300" in steps of 1" each so in that case we would have like item codes for all the range but in most cases there would not be any stock of the items.

So to avoid such scenario, the new item variant improvement would only define an item variant and we could give an option to users/admins whether they want to create a definition or the actual item variants.

The definition of item variant has to handle the following things:
1. In case of float or numeric fields there should be an option to define the range and also the steps so in our case of TV the min would be 20 and max would be 300 along with step of 1 inch.
1. There should also be a way to link fields of different UoM. Like we can define the size of TV in Inch or in mm. Hence we would need to define a field size in mm == size in inch \* 25.4
2. Item variants should also have the option to define the Filters in the website like in the case of many online portals we can choose the filters and then zero in on the product needed.

A small but working model of this type of item variants is working in erpnext with the help of custom client and server scripts.

Server scripts are here: https://github.com/adityaduggal/rigpl-erpnext/blob/master/rigpl_erpnext/rigpl_erpnext/item.py

**Comment by rmehta** [comment]
@adityaduggal there are many suggestions here i my list

1. create variants by range (?) and step (?)
2. select allowed combinations (or make exceptions ?)

**Comment by adityaduggal** [comment]
@rmehta Please note that if I create a variant TV. The following are the options we have available:

1. TV type = LCD/CRT/LED
2. Size = (no option available, but the field is governed by the rules defined in the variant).

Now the variants would not be created by default but would be governed by rules. In case the field is a numeric field then we would have highest and lowest values and also the step increments that would define the item variants.

Like in our case of TV. If we have specified the TV size as numeric and range as 30~300 with steps of 5, then the only possible values in the size would be 30,35,40,45,50,55,60.....300.

I am still not able to get your 2nd point as to what do you mean by combinations or exceptions.

**Comment by adityaduggal** [comment]
@rmehta I am still waiting for a quote for this and hopefully this can be done in current scenario...I am in urgent need of this feature.

**Comment by rmehta** [comment]
@adityaduggal this is already built by @neilLasrado hopefully will be released later today

**Comment by adityaduggal** [comment]
@rmehta @neilLasrado I have checked the release on develop branch and I have found out that changes basically are similar to the old Item Variants the only difference being that now people have manage variants page which is essentially similar to the old Item being a template but it does not really address the issue of numeric fields.

Like my example of Television with different sizes,

lets say we make a Item Attribute as TV size. Now what if TVs start to come in sizes like 12",13".....200"

So we could set the item attribute as range 1~200 with step 1". Hence when a user created a new item and clicks on a check box "Is VARIANT of " then a select field comes up which shows only templates.

Now on selecting the template TV we would get the fields which we need to fill and the system checks if the fields are as per the template or not.

Maybe I think I am unable to explain the requirement clearly in writing, as I have seen many a times users asking for such  kind of utility on the forums as well.

**Comment by rmehta** [comment]
@adityaduggal the big difference is that in earlier version, the system would create all versions, now you select what variant combinations you want to apply. Hope that helps.

I am not sure how to wrap this around ranges.

**Comment by rmehta** [comment]
@adityaduggal did you play with the new system? does this work for you?

**Comment by adityaduggal** [comment]
Yes I am playing with the new changes but unfortunately this does not really solve anything for me. I would still strongly suggest that we create something for ranges. It would be great if you or any one from your team could spare time for TV session so that I could explain what is happening on my custom code and then you people I am sure would give a wonderful solution.

Once again request for the quote and if needed I can come over to mumbai to discuss and help with this feature.

**Comment by rmehta** [comment]
@adityaduggal Can you explain your requirement in very short. I am not sure how ranges work.

If you are coming to Mumbai, we can spend a day or so working for your features :smile: Just sync with @nabinhait so that he can spend the day with you. Or you are coming for the conference anyways right? :)

**Comment by adityaduggal** [comment]
@rmehta @nabinhait Kindly let me know the dates for your suiting so that I
could come over and explain the requirement in detail in person. I would
not like to club this with the conference like last time so that its ready
before the conference.

PS: I would only be coming to conference if this feature which we discussed
in last conference is done with...I still want this to be much more
versatile than the current system.

On Fri, 10 Jul 2015 at 12:46 Rushabh Mehta <notifications@github.com> wrote:

> @adityaduggal <https://github.com/adityaduggal> Can you explain your
> requirement in very short. I am not sure how ranges work.
>
> If you are coming to Mumbai, we can spend a day or so working for your
> features [image: :smile:] Just sync with @nabinhait
> <https://github.com/nabinhait> so that he can spend the day with you. Or
> you are coming for the conference anyways right? :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/frappe/erpnext/issues/3261#issuecomment-120261412>.
>
-- 
Best Regards,

Aditya Duggal
E: adityaduggal@gmail.com
Web: www.rigpl.com

**Comment by nabinhait** [comment]
@adityaduggal Please suggest any date after 15th July and except 2nd week of August

**Comment by adityaduggal** [comment]
@nabinhait how does 30 & 31st July sounds....let me know so I could book the tickets.

**Comment by nabinhait** [comment]
@adityaduggal Yes, am available on those dates.

**Comment by adityaduggal** [comment]
So its confirmed I am reaching on 30th. Tics booked.

On Mon, 13 Jul 2015 at 12:10 Nabin Hait <notifications@github.com> wrote:

> @adityaduggal <https://github.com/adityaduggal> Yes, am available on
> those dates.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/frappe/erpnext/issues/3261#issuecomment-120829628>.
>
-- 
Best Regards,

Aditya Duggal
E: adityaduggal@gmail.com
Web: www.rigpl.com

**Comment by nabinhait** [comment]
Noted.
