### ISSUE TITLE
erpnext_sync.py script for integrating biometric device  shows service running, but no data is fetched from the device.

### ISSUE THREAD

**Issue by ArunaDevraj** [frappe/erpnext#32614]
### Information about bug

erpnext_sync.py script shows;
service running
but no logs is fetched from the biometric device

### Module

HR

### Version

ERPNext: v13.35.3 (version-13)

Frappe Framework: v13.35.2 (version-13)

### Installation method

FrappeCloud

**Comment by dj12djdjs** [comment]
@ArunaDevraj I don't see a `erpnext_sync.py` script anywhere in version-13 code base.

**Comment by ArunaDevraj** [comment]
@dj12djdjs

This is an external script which we have to be integrated with erpnext.

In my logs directory punch data is available but the only pblm is it is in the attendance failed list.

**Comment by ArunaDevraj** [comment]
When I give the command python3 erpnext_sync.py in the terminal, the output shows that:

Service running

**Comment by ArunaDevraj** [comment]
It is the problem of fetching huge date, & cache has no that much memory size
