### ISSUE TITLE
Error when entering New Opportunity (from customer)

### ISSUE THREAD

**Issue by fblauer** [frappe/erpnext#3262]
Error message when trying to enter a new opportunity - New opportunity, chose Opportunity from customer, Chose customer, enter a title, try to save. 
Result is error message - "value missing for contact name"

**Comment by sbkolate** [comment]
For opportunity, Customer should have at least one contact.
I don't know why this validation is compulsory.

Also when we save opportunity, customer gets hide and converted into lead. 
The opportunity should be saved with customer name instead of contact name.

**Comment by rmehta** [comment]
Where is this validation, I am unable to find it.
