### ISSUE TITLE
feat: Allow setting valuation_rate as 1 instead of randomly picking from any warehouse

### ISSUE THREAD

**Issue by aakvatech** [frappe/erpnext#32628]
**Is your feature request related to a problem? Please describe.**
Performance problem when you have large number of transactions in SLE

**Describe the solution you'd like**
Setting value to 1 to avoid the unnecessary lookup from DB from other warehouses.

**Describe alternatives you've considered**
Setting value to 1 avoids the unnecessary lookup from DB from other warehouses.

**Additional context**
Below code is affecting performance when there is a high number of transactions in the system and the delivery note is being created for a warehouse that doesn't have the item yet (First time)
(https://github.com/frappe/erpnext/blob/ab137472b0b338a8676e85f2ca879b630b778f35/erpnext/stock/stock_ledger.py#L1265)

**Comment by rohitwaghchaure** [comment]
@aakvatech Maybe we can add settings like Do Not Fetch Valuation From Different Warehouse in stock settings to skip fetch from other warehouse and then you can set the valuation rate as 1 in the item master valuation rate field.

**Comment by aakvatech** [comment]
Alternatively use bin doctype to collect the valuation rate from different warehouses which is a much lighter query

**Comment by aakvatech** [comment]
Avoiding DB calls greatly helps though

**Comment by aakvatech** [comment]
@rohitwaghchaure what assistance can we offer to get this done for v13?
