### ISSUE TITLE
Multiple Issues with Assigned to Filter

### ISSUE THREAD

**Issue by bradley-preece-ict** [frappe/erpnext#3263]
Issue 1:
You have multiple Assigned To filter appearing in some documents. One Assigned to works correctly while the other Assigned to switches the operator to like and still failes when switched to different operator.  
![multiple assign to issue](https://cloud.githubusercontent.com/assets/11453272/7646322/3e8e0706-faf4-11e4-988f-45404e217f0e.jpg)

issue 2:
the Assigned To that is not working correctly has appeared in other documents filters and is not working.
![assign to failed](https://cloud.githubusercontent.com/assets/11453272/7646435/2cc05f18-faf6-11e4-8d26-db552f7d1f41.jpg)

the version i  am currently using is 24.0 of erpnext and frappe version 4.13.1. the issue has occured on older version of erpnext.

**Comment by rmehta** [comment]
You should always use the like operator and add `%` before and after the string.

**Comment by bradley-preece-ict** [comment]
cheers. have you come accross the second issue with multiple Assigned To filters in the ToDo list?

**Comment by rmehta** [comment]
You need to have required permissions on ToDo table as well.

**Comment by bradley-preece-ict** [comment]
i have been using the admin account on a virtual machine. does the admin account not come with permissions to the ToDo table?

**Comment by cgpurbaugh** [comment]
Is this resolved?  This is for a very old version of ERPNext.

**Comment by rmehta** [comment]
@cgpurbaugh thanks for flagging 👍
