### ISSUE TITLE
Error when creating Dunning from Sales Inoivce

### ISSUE THREAD

**Issue by wojosc** [frappe/erpnext#32643]
### Information about bug

When coming from Sales Invoice and trying to make -> Dunning we some times run into an error. The message is

> Server error TypeError: calculate_interest_and_amount() takes 4 positional arguments but 5 were given

A work around is to create a Dunning via the + icon in the connections table from Sales Invoice.

### Module

accounts

### Version

ERPNext: v13.39.4 (HEAD)

Frappe Framework: v13.41.4 (HEAD)

### Relevant log output / Stack trace / Full Error Message.

```shell
Server error TypeError: calculate_interest_and_amount() takes 4 positional arguments but 5 were given
```

**Comment by deepeshgarg007** [comment]
@wojosc Unable to replicate. Might be some network issue because of which this might be happening. Closing this for now
