### ISSUE TITLE
Opportunity form not saving

### ISSUE THREAD

**Issue by ShraddhaRanjane** [frappe/erpnext#3265]
I have taken bench update,but i got error while saving opportunity form
Steps:-
1. I have created new Lead.
2. creating new Opportunity ,in that selecting option as "Lead" from "Opportunity From" field.
3.select Respective Lead ,Opportunity type and Status.
4. save form 
5.Error displayed like:-  
Error: Value missing for: Contact Name
Did not save

same error displaying , when i select option as customer  .
on customer form  i have given respective contact still opportunity form not saving.

**Comment by rmehta** [comment]
just fixed. :( #3262

**Comment by ShraddhaRanjane** [comment]
Hello sir ,
i have check this errors,this errors not coming all the times. 
when i do some steps like:-
1. At the time of creating new lead if i do not give "Source" and creating Opportunity then error not showing
2. but at the time of creating new lead if i select source as "customer" or else and creating opportunity then this error shows
