### ISSUE TITLE
I cant logging from my ipad

### ISSUE THREAD

**Issue by resxa** [frappe/erpnext#3266]
I just created a text demo/free version of erp next for testing.I created the demo on my laptop with email and password to loggin.i discover that,other than,my laptop with chrome browser,from which i created the demo,i cant loggin from my ipad,with safari browser,even with the same loggin credientials,why?

**Comment by rmehta** [comment]
Which version of ipad and Safari are you using? ERPNext works fine in Safari

**Comment by rmehta** [comment]
Works on my iPhone with iOS8. Should work in an IPad too.
