### ISSUE TITLE
bench backup Error: no such option: --site

### ISSUE THREAD

**Issue by ufoping** [frappe/erpnext#32668]
### Information about bug

Hello,

I'm trying to backup erpnext to S3 but got error.
```
docker compose --project-name erpnext-one exec backend bash

cd /home/frappe/frappe-bench/sites

bench --site erp.ops2.dev backup --with-files push-backup --site erp.ops2.dev --bucket erp.ops2.dev --region-name us-east-2 --endpoint-url http://erp.ops2.dev --aws-access-key-id ****** --aws-secret-access-key ******
```

Error
Usage: bench  backup [OPTIONS]
Try 'bench  backup --help' for help.

Error: no such option: --site

What's going on?

### Module

other

### Version

erpnext 14.2.1
frappe 14.9.0
payments 0.0.1

### Installation method

docker

### Relevant log output / Stack trace / Full Error Message.

```
bench --site erp.ops2.dev backup --with-files push-backup --bucket erp.ops2.dev --region-name us-east-2 --endpoint-url http://erp.ops2.dev --aws-access-key-id ****** --aws-secret-access-key ******
the same errors
```

**Comment by louishot** [comment]
how to fix it ?

**Comment by louishot** [comment]
@deepeshgarg007 @ufoping 
do you have fix it ?
