### ISSUE TITLE
Sales Invoice - Logo not displaying on PDF

### ISSUE THREAD

**Issue by ShraddhaRanjane** [frappe/erpnext#32677]
### Information about bug

URL is = https://yagna.frappe.cloud/
Doc type= Sales Invoice

Added company logo and that is getting print , but same logo not getting display on PDF . when we convert into PDF or download PDF. Company logo not appearing on the pdf

### Module

selling

### Version

Education: v0.0.1 (HEAD)

ERPNext: v14.1.2 (HEAD)

Frappe Framework: v14.7.0 (HEAD)

Healthcare: v0.0.1 (HEAD)

Frappe HR: v0.0.1 (HEAD)

India Compliance: v0.0.1 (HEAD)

Payments: v0.0.1 (HEAD

**Comment by deepeshgarg007** [comment]
@ShraddhaRanjane I just checked on our site by generating a PDF and the logo seems to be appearing just fine. You will have to provide more info for us to investigate. Please reopen the issue once you do

<img width="1375" alt="image" src="https://user-images.githubusercontent.com/42651287/198628342-dc760ac4-cb16-440d-908b-0970da20d5a1.png">
