### ISSUE TITLE
Enhancement: markdown Doctypes like Github

### ISSUE THREAD

**Issue by betabank** [frappe/erpnext#3267]
Hi, it would be great to have accesible in the ERPNext text fields like comments a markup for the DocTypes, like Github.
So when you type SO-00011 or SINV-00320 is linking to the corresponding document. Github makes this markdown with a dropdown list as you type starting with # for example.
The same could be done in ERPNext when starting typing any Series, SO-, SINV-, PINV-, SUP- and so on.

**Comment by umairsy** [comment]
Closing as inactive and feature not request by other user. Feel free to re-open if feature is still needed.
