### ISSUE TITLE
Proposal: Optional Hungarian COA for microenterprises

### ISSUE THREAD

**Issue by backendoadmin** [frappe/erpnext#32688]
Based on Hungarian law most Hungarian small companies use a simplified version of the Chart of Accounts. If they want to use simplified yearly reports they have to use that special version of the Hungarian Chart of Accounts. 

It's called the Chart of Accounts for microenterprises. 

The government provides that simplified Chart of Accounts as a 3rd attachment of 398/2012. (XII. 20.) Act:
source: https://net.jogtar.hu/jogszabaly?docid=a1200398.kor

We can't change that COA by law, but it's allowed to add child accounts if it's needed. 

We are going to push a new commit with this Hungarian Chart of Accounts for microenterprises. And please merge it and make it available as an optional Hungarian Chart of Accounts in ERPNext.

Then we are going to add some child accounts because we also want to set some default accounts in ERPNext because that is needed for invoicing and for that we need a more detailed Chart of Accounts. But we focus only on the bare minimum to make invoicing available out of the box. And we split this task into two parts to make it transparent. 

In the third round, we are going to commit another new, optional, general Hungarian Chart of Account for all the other companies to make it easy to use ERPNext to them. 

Any feedback is welcome. 

Relevant Hungarian forum topic:
https://discuss.erpnext.com/t/magyar-mikrogazdalkodoi-szamlatukor/96364

**Comment by krnkris** [comment]
It is really a great step to Hungarian localization.

**Comment by backendoadmin** [comment]
We changed two account's name because of the 140-character limit (8691, 9691):

From:
Társaságba bevitt, értékpapírnak vagy részesedésnek nem minősülő vagyontárgyak könyv szerinti és létesítő okiratban meghatározott értékének veszteségjellegű különbözete

and

Gazdasági társaságba bevitt, értékpapírnak vagy részesedésnek nem minősülő vagyontárgyak nyilvántartás szerinti értékének és létesítő okiratban meghatározott értékének nyereségjellegű különbözete

To:
Társaságba bevitt, értékp. v. rész. nem minősülő vagyont. könyv sz. és létesítő o. meghat. értékének veszteségjellegű különbözete

and

Gazd. társ. bevitt, értékp. v. rész. nem minősülő vagyont. nyilv. sz. értékének és létesítő o. meghat. értékének nyereségjellegű kül.

**Comment by backendoadmin** [comment]
We had to rename some other account names because of the 140-character limit.
And there was a double \\ character and we fixed that.
