### ISSUE TITLE
Print-outs display contact and company address after totals

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#32694]
### Information about bug

![image](https://user-images.githubusercontent.com/1822868/197511927-f2ed8ea4-4653-420a-b905-8dc721c94c15.png)

### Module

accounts

### Version

ERPNext: v14.3.0 (HEAD)
Frappe Framework: v14.11.1 (HEAD)

### Installation method

FrappeCloud

**Comment by deepeshgarg007** [comment]
@muchai Can you please let us know what print format is this and what is the issue, nothing can be interpreted from the information given in the description

**Comment by muchai** [comment]
@deepeshgarg007  This affects all sales and purchase doctypes(Quotation, SO, DN,SI, PO,PR, and PI). Since introduction of tab breaks on those doctypes.

The date and delivery date, there's three columns for that section now. Twas two before.

See example below.

![image](https://user-images.githubusercontent.com/1822868/198637490-dcf10ca5-1e61-471a-beab-445aeaf2d366.png)

**Comment by nabinhait** [comment]
Seems like you are using the standard print format. In standard print format, it shows the values based on field's order. You need to create a custom print format using print format builder.

**Comment by muchai** [comment]
@nabinhait we have been creating custom print formats since.
Was hoping for standard/default nice templates, for those who may not have the bandwidth for custom print formats.
Let the issue remain closed though.
