### ISSUE TITLE
Bug in Pricing Rule

### ISSUE THREAD

**Issue by sjain17** [frappe/erpnext#32695]
### Information about bug

The pricing rule is having an issue with different UOMs.

Use Case - 

- Create an item ITM001 with 2 different UOM i.e., Nos and Box. Conversion of 1 Box = 10 Nos.
- Create an item price for ITM001 for UOM = Nos, Rate=Rs 10.
- Create an item price for ITM001 for UOM = BOX, Rate=Rs 90.
- Now create a pricing rule for ITM001 with apply on = Item, Apply Rule on Item Code = ITM001, UOM=Box. 
- Select Price based discount. Select Price Discount Scheme, Rate or Discount = Rate and Rate=85.
- Now the system should consider the rate of the item ITM001 for Box = Rs 85 but it is calculating the rate sales invoice by multiplying the rate with UOM conversion.

The system should consider the pricing rule UOM and the rate should be applied for selected UOM and not for stock UOM.

### Module

selling

### Version

Frappe - Version-13
ERPNext - Version-13

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
There is no error message but the output of the pricing rule is incorrect in the sales order/pos invoice and sales invoice.
```

**Comment by maharshivpatel** [comment]
This issue has been fixed in `v13.40.2` and `v14.3.1` by #32566
