### ISSUE TITLE
Pricing rule not working for Discount on other Item

### ISSUE THREAD

**Issue by sjain17** [frappe/erpnext#32697]
### Information about bug

If we try to apply pricing on the item group tree using the below structure -

1 FMCG
1.1 GROCERY
1.2 BEVERAGES
1.1.1 FLOUR
1.1.2 FAST FOOD
1.1.3 INSTANT FOOD
1.2.1 BOTTLED WATER
1.2.2 COLD DRINKS

I have selected the Apply rule on Item Code with the below data - 

Item Group                   UOM          
FLOUR                           Nos
FAST FOOD                   Nos
INSTANT FOOD            Nos
BOTTLED WATER         Nos

Now if I apply a pricing rule or promotional scheme using **Discount on Other Item** with a selection of **Apply Rule on Other Item** with either selection **Item or Brand** it is not working. It only works with Item Group. 

### Module

selling

### Version

Frappe Version-13
ERPNext Version-13

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
There is no error but the output of the condition is not working.
```

**Comment by deepeshgarg007** [comment]
Duplicate Issue https://github.com/frappe/erpnext/issues/32696
