### ISSUE TITLE
fix: Empty items[] allowed in Delivery Note using RestAPI and PUT

### ISSUE THREAD

**Issue by aakvatech** [frappe/erpnext#32709]
### Information about bug

When you send a PUT request for an existing DN and updates items = [] the system allows updating and clears the items table and reqd:1 of json is not being honored

Expected behaviour is to stop such PUT requests.

### Module

stock

### Version

Frappe Framework: v13.41.1 (version-13)
ERPNext: v13.39.0 (version-13)

### Installation method

FrappeCloud

**Comment by rohitwaghchaure** [comment]
@aakvatech 

Delivery Note Item is mandatory table, you shouldn't be able to save the delivery note without items table
