### ISSUE TITLE
GL entries for Journal Entry aggregated 

### ISSUE THREAD

**Issue by aadhilpm** [frappe/erpnext#32705]
When submitting a Journal Entry that has postings to the same account and cost center multiple times, the GL Entry for that account will be aggregated. This means that on the General Ledger view, we cannot see the individual movements, so have to drill down into the journal to make sure certain things have been submitted.

For example:

Journal:
Credit - Pension Control - Group - Employees Pension
Credit - Pension Control - Group - Employers Pension
Debit - Payroll Liabilities - Group - Employees Pension
Debit - Payroll Liabilities - Group - Employers Pension

GL Entry:
Credit - Pension Control - Group
Debit - Payroll Liabilities - Group

This means we can’t separate Employees Pension and Employers Pension in ledger reports.

[GL entries for Journal Entry aggregated](https://discuss.erpnext.com/t/bug-gl-entries-for-journal-entry-aggregated/37177)

**Solution:**
https://github.com/frappe/erpnext/blob/183662c0e20f65b80dbf459d0fb14fbb8debf997/erpnext/accounts/general_ledger.py#L28

In erpnext/accounts/general_ledger.py
Currently, merge_entries=True  based on toggle-able setting in Accounts Settings we can trigger the value of make_gl_entries function true or false [merge_entries=False]

**Comment by deepeshgarg007** [comment]
@aadhilpm In case you want to track them separately you might want to use a separate cost center or account. If the heads are same the system will merge the GL Entries

**Comment by aadhilpm** [comment]
This issue is already resolved by this PR (https://github.com/frappe/erpnext/pull/34838)

![Image](https://github.com/frappe/erpnext/assets/36843795/f938becf-a7b7-4d4c-806d-09b14c2415f2)

https://github.com/frappe/erpnext/blob/25e78fb311ec53ce3cc76ab7d6ce6dfc8f7d6475/erpnext/accounts/doctype/journal_entry/journal_entry.py#L935
