### ISSUE TITLE
Pricing Rule not working on release erpnext v14.1.2, Frappe framework v14.7.0

### ISSUE THREAD

**Issue by klw-sc** [frappe/erpnext#32729]
### Information about bug

Upgraded from ERPNext v14.1.0, Frappe Framework v14.6.0 to ERPNext v14.1.2, Frappe Framework v14.7.0. No changes made to the previous Pricing Rule, but now the Pricing rule is not making any change when it is applied. Not sure what logs I can provide, the settings are attached which do work on ERPNext v14.1.0 but do not work on release V14.1.2, the Pricing Rule settings were not changed, I only completed a bench update.
![price list](https://user-images.githubusercontent.com/26032757/198269579-16bcba8c-4523-4f19-9f24-8624e0d737eb.jpg)

### Module

selling

### Version

Frappe V14.7.0
ERPNext V14.1.2

**Comment by maharshivpatel** [comment]
I am unable to reproduce can you please share below information

Item details:
1. Default Stock UOM
2. Selling UOM
3. UOMs Conversation table

Transaction details:

1. Sales Item UOM
2. QTY

**Comment by deepeshgarg007** [comment]
@klw-sc I check and tried this and it worked just fine

<img width="1262" alt="image" src="https://user-images.githubusercontent.com/42651287/205060484-21d00370-d0d3-4a0d-9207-92e4ffc92701.png">

A margin of 20 is getting applied via the pricing rule 

<img width="1358" alt="image" src="https://user-images.githubusercontent.com/42651287/205061239-947a6484-6e59-47cf-aead-761e2f95a4eb.png">
