### ISSUE TITLE
Document Viewing Link is Not Working

### ISSUE THREAD

**Issue by sumeetagra** [frappe/erpnext#32728]
### Information about bug

Document is not opening on clicking the Document ID in List VIew.
EG: If we select a sale Invoice from the list, on clicking the ID to open that Invoice, the invoice is not redirected to Form View.

### Module

accounts, stock, buying, selling

### Version

ERPNext: v14.4.0 (version-14)

Frappe Framework: v14.0.0 (version-14)

Frappeauth App: v0.0.1 (master)

Frappe HR: v1.0.0 (develop)

India Compliance: v14.0.1 (version-14)

Payments: v0.0.1 (develop)

**Comment by sumeetagra** [comment]
This error occurs when the Naming Series has "/" in it. Eg: SO/2201

**Comment by deepeshgarg007** [comment]
<img width="1329" alt="image" src="https://user-images.githubusercontent.com/42651287/198636303-14ae8031-2151-4cac-a9ad-2eb3bf875360.png">

@sumeetagra I also have "/" in my naming series but it is working fine for me
