### ISSUE TITLE
Pricing Rule in V13

### ISSUE THREAD

**Issue by Wahyulutfi97** [frappe/erpnext#32727]
### Information about bug

In pricing rule not filter selling or buying type and where i use apply on transaction and finally discount percentage apply in selling and buying transaction. 

in this code. /home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/pricing_rule/utils.py
def get_other_conditions(conditions, values, args):
	for field in ["company", "customer", "supplier", "campaign", "sales_partner"]:
		if args.get(field):
			conditions += " and ifnull(`tabPricing Rule`.{0}, '') in (%({1})s, '')".format(field, field)
			values[field] = args.get(field)
		else:
			conditions += " and ifnull(`tabPricing Rule`.{0}, '') = ''".format(field)

	for parenttype in ["Customer Group", "Territory", "Supplier Group"]:
		group_condition = _get_tree_conditions(args, parenttype, "`tabPricing Rule`")
		if group_condition:
			conditions += " and " + group_condition

	if args.get("transaction_date"):
		conditions += """ and %(transaction_date)s between ifnull(`tabPricing Rule`.valid_from, '2000-01-01')
			and ifnull(`tabPricing Rule`.valid_upto, '2500-12-31')"""
		values["transaction_date"] = args.get("transaction_date")

	return conditions

### Module

accounts

### Version

13.39.0

### Installation method

manual install

**Comment by maharshivpatel** [comment]
@Wahyulutfi97 I am unable to understand the issue can you please describe it properly.

**Comment by Wahyulutfi97** [comment]
there is no filter to distinguish between selling and buying when applying on transactions in the nominal discount section. so when I made a discount, discount showing in buying transactiion

**Comment by Wahyulutfi97** [comment]
in the conditions of the code above
