### ISSUE TITLE
Site Navigation Issue

### ISSUE THREAD

**Issue by ramantalkin** [frappe/erpnext#3273]
![screenshot from 2015-05-17 00-49-35](https://cloud.githubusercontent.com/assets/10405307/7667672/9f7f5e94-fc2e-11e4-87a5-c72718297ca9.png)
When we browse an erpnext site and navigate to a blog, like {IP/blog/general/welcome}, then afterwards if we click on contact, about us or blog on the top bar it redirects to {IP/blog/general/contact}, which itself is wrong url and produces 'Page missing or moved'.

To note: Pointing it towards HOME Page works well.

**Comment by rmehta** [comment]
Make sure you set the contact link as "/contact" instead of just "contact"

Fixed default website.
