### ISSUE TITLE
Account Payable displays cancelled entries

### ISSUE THREAD

**Issue by zenicolas** [frappe/erpnext#32760]
### Information about bug

The supplier delivered products and the entry was booked as the standard process, purchase receipt -> purchase invoice.

While awaiting for the purchase invoice from the supplier, we had to send them payments recorded as individual payments made to the supplier's account (the payment was not linked to the purchase invoice yet).

Once the purchase invoice was received, the payments were reconciled through the payment reconciliation. 

After much fiddling, clearing cache, login out and cancelling and relinking the invoices, the (original now-cancelled) transactions are showing up on the account payable report despite being cancelled and unlinked. 

### Module

accounts, buying

### Version

Agriculture: v0.0.1 (HEAD)
Frappe Chat: v0.0.1 (HEAD)
Education: v0.0.1 (HEAD)
ERPNext: v14.4.0 (HEAD)
Frappe Framework: v14.13.0 (HEAD)
Frappe HR: v1.0.0 (HEAD)
Frappe LMS: v0.0.1 (HEAD)
Payments: v0.0.1 (HEAD)
Wiki: v0.0.1 (HEAD)
<img width="1728" alt="Screenshot 2022-10-29 at 18 05 36" src="https://user-images.githubusercontent.com/26570996/198838933-d8cda467-c7da-408d-8683-5a3e23cc54b5.png">
<img width="1728" alt="Screenshot 2022-10-29 at 18 05 29" src="https://user-images.githubusercontent.com/26570996/198838936-cd0d6757-52c9-4b90-9f8a-91c2db848a2b.png">

<img width="1728" alt="Screenshot 2022-10-29 at 18 05 11" src="https://user-images.githubusercontent.com/26570996/198838920-37b7cb9f-d20e-4f8c-b30f-896a12e74ee7.png">

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
No error message displayed.
```

**Comment by deepeshgarg007** [comment]
@zenicolas I tried this locally on my system and can't seem to replicate

Report before cancellation
<img width="1345" alt="Screenshot 2022-11-10 at 4 05 25 PM" src="https://user-images.githubusercontent.com/42651287/201071147-9f8ae187-4a80-44dc-af65-877bba81808b.png">

Entry Cancelled
<img width="1440" alt="Screenshot 2022-11-10 at 4 11 16 PM" src="https://user-images.githubusercontent.com/42651287/201071193-bb3db4ec-42bf-4b29-938d-4215bfd9006a.png">

Report after cancellation
<img width="1357" alt="Screenshot 2022-11-10 at 4 11 27 PM" src="https://user-images.githubusercontent.com/42651287/201071239-c0fba4d9-ae23-4253-9d03-8d3f16999ec2.png">
