### ISSUE TITLE
Pricing Rule Free Item not getting removed after added once

### ISSUE THREAD

**Issue by sjain17** [frappe/erpnext#32766]
### Information about bug

When we add pricing rules based on a product discount for min 2 qty and get 1 free; the system is not checking if the min qty condition if the pricing rule is applied once. 

For example - 
Create a pricing rule for Product Discount, Min=2 Qty, and Free =1 Qty. 

Once we save the sales invoice with 2 Qty of items then it applies the pricing rule for 1 free qty; however, when we remove 1 qty from the product (not the free one) still the pricing rule is applied and the free qty will be available in the sales invoice.

My Observation regarding the issue - 
In Sales Invoice Item the hidden field pricing rule string or list of pricing rules in small text field is not getting removed even after deleting one item from sales invoice (which makes the condition = False). 

### Module

selling

### Version

Frappe Version - 13.40
ERPNext Version - 13.40

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
No error but output is incorrect
```

**Comment by maharshivpatel** [comment]
@sjain17 I am unable to reproduce the issue. can you please update to the latest version and comment if you still face the issue.

**Comment by sjain17** [comment]
@maharshivpatel I don't how you are not getting this error but once the pricing rule is applied for product discount and even if you remove the main condition item, it will not remove the free item from the order.  I am using FrappeCloud and same error is there as well.

**Comment by maharshivpatel** [comment]
@sjain17 can you please share all pricing rule details and sales invoice details.

**Comment by sjain17** [comment]
@maharshivpatel I am using frappecloud with 
ERPNext: v14.5.1 (HEAD)
Frappe Framework: v14.14.2 (HEAD)

**Comment by maharshivpatel** [comment]
In the Issue you have mentioned v13.40

**Comment by sjain17** [comment]
I tried both Version 13 and Frappecloud version 14 as well.

**Comment by sjain17** [comment]
The else block is missing the pricing rule, so if we create any pricing rule which is having a product discount and if the condition gets satisfied once then the free item will be added up automatically; however, now when we try to remove the item which is part of the pricing rule then the system will not remove the free item automatically. It will be still there.

**Comment by maharshivpatel** [comment]
![Free Item](https://user-images.githubusercontent.com/39730881/201511095-e8bc98f7-ef56-4a1d-a7a1-fa51c097dfaa.gif)


> The else block is missing the pricing rule, so if we create any pricing rule which is having a product discount and if the condition gets satisfied once then the free item will be added up automatically; however, now when we try to remove the item which is part of the pricing rule then the system will not remove the free item automatically. It will be still there.

This is different issue the one you mentioned above is when you change the QTY. i am able to replicate the issue when you remove the main item from child table.

**Comment by sjain17** [comment]
https://user-images.githubusercontent.com/30950233/201511306-c45f981c-dcf5-4bf5-86ac-d1ab37710046.mp4

For reference I have attached the video.

**Comment by sjain17** [comment]
Thank you for reopening the issue and I am really sorry if I have created any confusion while explaining the problem.

**Comment by maharshivpatel** [comment]
@sjain17 I am still unable to replicate 😅. can you please check the console if anything is breaking and make sure you don't have any customisations client scripts enabled.

https://user-images.githubusercontent.com/39730881/201511766-17098615-01d8-4fe4-86aa-dfdfa3bd75bc.mov

**Comment by sjain17** [comment]
Can you try creating buy 3 get 1 free? and do the changes after clicking on the checkout once. In retail, it is a very frequent scenario where the customer keeps on adding or removing items from the cart. Try to do checkout and then remove it.

**Comment by maharshivpatel** [comment]
@sjain17 I am able to replicate now 👍.

**Comment by sjain17** [comment]
Thank you for the update! I will wait for the solution.

**Comment by sjain17** [comment]
Is this fixed now?
