### ISSUE TITLE
v14.4.0 - Links not opening if Naming Series have SLASH '/'

### ISSUE THREAD

**Issue by akashdubey22** [frappe/erpnext#32774]
### Information about bug

After updating to v 14.4.0, Links not opening if Naming Series have SLASH '/'
LIKE ...
....../app/sales-invoice/22-23/IND/331

before update it was working well & now to access these old records I have to manually type %2F in place of / in naming series.

### Module

accounts

### Version

Frappe - 14.13.0
ErpNext - 14.4.0

### Installation method

easy-install

**Comment by Ciangi** [comment]
not working for me too

**Comment by akashdubey22** [comment]
anyone else ?

**Comment by pagliaso** [comment]
Yes, same problem in here.

**Comment by rknroot** [comment]
Same Problem. 
Purchase Invoice, Sales Invoice & Project are not working

**Comment by pra17shant** [comment]
Reported similar issue here: https://github.com/frappe/erpnext/issues/32789

**Comment by ankush** [comment]
This should be fixed with https://github.com/frappe/frappe/pull/18748

**Comment by Ciangi** [comment]
After update everything works, thanks a lot.
