### ISSUE TITLE
Customer Quick Entry form not showing Primary Contact Details section.

### ISSUE THREAD

**Issue by KhaledBinAmir** [frappe/erpnext#32786]
### Information about bug

Customer Quick Entry form not showing Primary Contact Details section.
![image](https://user-images.githubusercontent.com/30042185/199160429-9df1e8a9-fd51-40c8-b892-2923f0ef427a.png)

It looks like somehow mobile number and email address fields are not rendered
![image](https://user-images.githubusercontent.com/30042185/199161239-40e0ed03-dbf0-4607-861d-0fa7fa149c90.png)

Also, how can I customize quick entry forms? if I do custom scripting for this form, will core dialog replaced? I need to add and remove some columns.

Best Regards!

### Module

selling

### Version

active_users 1.0.3
erpnext 14.4.0
frappe 14.13.0
frappedesk 0.4.7
hrms 1.0.0
payments 0.0.1

### Installation method

manual install

**Comment by KhaledBinAmir** [comment]
Mentioned in Discussion:
https://discuss.erpnext.com/t/where-is-the-mobile-number-and-email-id-field-in-quick-entry-new-customer-in-v14/96567/4?u=hiimkhaled

**Comment by GoldenScrew** [comment]
same.

**Comment by s-aga-r** [comment]
@hiimkhaled The **Primary Address Details** is visible to me in **v14.7.0**.

![image](https://user-images.githubusercontent.com/63660334/204197185-8d3e9234-5e3f-440c-b09f-7d08bf32bd43.png)

**Comment by GoldenScrew** [comment]
Any ideas?

**Comment by s-aga-r** [comment]
> Any ideas?

`mobile_no` and `email_id` are [Read Only](https://frappeframework.com/docs/v14/user/en/basics/doctypes/fieldtypes#read-only) fields.

![image](https://user-images.githubusercontent.com/63660334/204759757-0f32cbcf-060f-493f-b162-9a0b3a5c61a3.png)

**Comment by Maree27** [comment]
Seems like primary contact section is not working fine. As its mentioned in customer quick entry js file but not working,

**Comment by Govind-Jangid** [comment]
Install India Compliance App
[https://github.com/resilient-tech/india-compliance](https://github.com/resilient-tech/india-compliance)

**Comment by GoldenScrew** [comment]
> Install India Compliance App https://github.com/resilient-tech/india-compliance

Why? How to find solution for problem above?
