### ISSUE TITLE
After Site Upgrade by frappe Cloud, Issue Following raised.

### ISSUE THREAD

**Issue by pra17shant** [frappe/erpnext#32789]
### Information about bug

1) Previous created PO's not open normally.
2) once create New PO then suppler not able to select.
also while creating new entry for Purchase Receipt & Purchase Invoice DocType, not able to select supplier.
Please fix the issue as soon as possible. Thanks in advance.

https://user-images.githubusercontent.com/99401472/199169009-d8499655-60c5-4355-ba65-2c0945f4cdf2.mp4

### Module

buying

### Version

ERPNext: v14.4.0 (HEAD)
Frappe Framework: v14.13.0 (HEAD)
India Compliance: v14.0.1 (version-14)
Payments: v0.0.1 (HEAD)

### Installation method

FrappeCloud

**Comment by muchai** [comment]
- Our case is, in one site, customer cannot be selected on sales order or sales invoice.
- If so/si is started from Customer, it works fine.
- If it's started from SO/SI directly, user cannot select the customer on those doctypes.
- The site is in the same version 14 as other sites, and the other sites work as expected.
- Will try migrate it to another FC location, from paris, and see. I suspect could be that location/environment, not sure.

**Comment by muchai** [comment]
Your first problem, has to do with '/' character on your docnames.

Reported similar issue here: https://github.com/frappe/frappe/issues/18659

**Comment by pra17shant** [comment]
URL sems to be changed in core code, if i replaced manually / as a %2F then previous PO open normally.

**Comment by ankush** [comment]
https://github.com/frappe/frappe/pull/18748

Backslashes are a different problem. Forward slashes should work now. It was a regression :neutral_face:
