### ISSUE TITLE
how to chage my email as admin

### ISSUE THREAD

**Issue by kananeto** [frappe/erpnext#3279]
hi, i have signup for free erpnext account.

now i need to give admin to my friend. how to change the admin email address?

**Comment by kananeto** [comment]
Found it. Need to click on rename. this is not meaningfull
![github](https://cloud.githubusercontent.com/assets/3488769/7674570/7d9fb708-fd5d-11e4-8faf-ad0f3d0bcb0d.png)
. Change it to "Change Email Address"

**Comment by pdvyas** [comment]
You can also add another user.
