### ISSUE TITLE
Conversion Factor Issue

### ISSUE THREAD

**Issue by ruchin78** [frappe/erpnext#3280]
When generating material request for shortage item system generates material request of shortage quantity and then enter one more row for the same item to fulfill the MOQ requirement.

Now, the only issue is, let say an item X is required 4 quantity manufacture a product P and its MOQ is 100 and it comes in Pack of 100 quantity. By calculating all the factor system generated material request as under:

Item Code              Order Quantity    UOM
X                           04                      Nos
X                           96                      Nos

Now when you convert it into Purchase Order and change Purchase UOM of Line to Pack, system will treat it as 4 pack (400 quantity), system will not allow to save you as it increased the material request quantity of line 1 and similarly with line 2. Also if you change the quantity by calculating it on the basis of conversion factor then also it fails. You need to have both the line in the PO, you cannot club the both and also the PO will have to identical items twice in the PO.
Now if you convert the quantity as per conversion factor then it should be:
1 Pack
1 Pack

Which becomes 200 Nos whereas we needed only 4 quantity but as per MOQ we need to by 100 quantity means 1 pack. Please provide any solution for this.

**Comment by rmehta** [comment]
Can you be brief in describing the issue? this is very complicated to read.

**Comment by ruchin78** [comment]
I can understand but few things couldn't be understand well without an example.

**Comment by rmehta** [comment]
At least your title could be better. "Conversion Factor Issue" is too vague.
