### ISSUE TITLE
Item names not URL encoded

### ISSUE THREAD

**Issue by SvbZ3r0** [frappe/erpnext#32805]
### Information about bug

The link to an item's page includes the name of the item in the URL. An item named ABCD would reside at erpnext.site/app/item/ABCD. 
The problem is that the link to an Item in the Item List has the non-URL encoded item name in it. This causes issues when the item has an "/" in it's name.
For example, the link to an item called AB/CD becomes erpnext.site/app/item/AB/CD instead of erpnext.site/app/item/AB%2FCD.

This issue is also present in all other Lists where the name or id of the item is used to generate a link to the item.

To reproduce:
1. Create item named AB/CD
2.  Go to Item List
3.  Click on Item AB/CD
4.  Profit???

### Module

accounts, stock, buying, selling, ecommerce, manufacturing, CRM

### Version

frappe 14.13.0
erpnext 14.4.0

### Installation method

easy-install

**Comment by SvbZ3r0** [comment]
Issue already created here: https://github.com/frappe/frappe/issues/18659

**Comment by phot0n** [comment]
Should be fixed via https://github.com/frappe/frappe/pull/18749
