### ISSUE TITLE
fix: Multiple lines for same bank account in Journal Entry and Bank Reconciliation

### ISSUE THREAD

**Issue by aakvatech** [frappe/erpnext#32811]
### Information about bug

Replication path:
1. Create a journal with 5, 10, 15 and 20 INR Journal Entry for Bank Account. e.g. It could be bank charges for the month.
2. Submit the journal
3. Import Bank statement with 5, 10, 15, 20 INR bank charges
4. Attempt to do Bank Reconciliation and you will get an error: 
```The sum total of amounts of all selected vouchers should be less than the unallocated amount of the bank transaction```

### Module

accounts

### Version

ERPNext: v13.37.0 (HEAD)
ERPNext Support: v0.0.3 (HEAD)
Frappe Framework: v13.41.3 (HEAD)

### Installation method

FrappeCloud

**Comment by ruthra-kumar** [comment]
Closing the ticket. If issue persists in v14 or above, re-open.
