### ISSUE TITLE
get_plan_rate() returns 0 to validate_subscription_details(self) in Payment Requests.py always

### ISSUE THREAD

**Issue by Henry-Do-Su** [frappe/erpnext#32810]
### Information about bug

In payment_requests.py, the function validate_subscription_details(self) calls get_plan_rate() in Subscription_plan.py.

get_plan_rate calculates the correct value, but does not return the correct value for cost, Always returns 0, doesnt matter what plan is being used with its designated rate.

Due to that frappe returns the message error always:
_(
				#			"The amount of {0} set in this payment request is different from the calculated amount of all payment plans: {1}. Make sure this is correct before submitting the document."
				#		).format(self.grand_total, amount)

### Module

accounts

### Version

Frappe version -  v14.12.0 (version-14)
Erp Version - v14.3.1 (version-14)

### Installation method

manual install

**Comment by bhavesh95863** [comment]
You may have another payment request for the same invoice which is why it returns always 0. 

But this problem will occur when we will have a discount or tax on subscriptions so our grand total will not match our plan rate.

**Comment by Henry-Do-Su** [comment]
The reason to use payment requests was for the Stripe implementation. It was easy to write a new custom script for all Stripe API and webhook integration anyway, so that what I did. Will mark as solved.
