### ISSUE TITLE
Wrong Terms and Conditions selected after refreshing submited quotation

### ISSUE THREAD

**Issue by mastewalm** [frappe/erpnext#32817]
### Information about bug

I created two terms and conditions, selected one in the quotation, and saved and submitted the form. when I refreshed the page, the terms and conditions I selected were changed, also showing me that the form is not saved. And since the form was submitted, I was unable to save it again.

### Module

selling

### Version

Version 13

**Comment by deepeshgarg007** [comment]
@mastewalm I tried this on the latest version and it worked as expected. This might be due to some customization that you have done, please add more information for us to investigate and reopen
