### ISSUE TITLE
Cannot enter Customer on Sales Order or Supplier on Purchase Order since ERPNext update to v14.4.0

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#32826]
### Information about bug

If so/si is started from Customer, it works fine.

If it's started from SO/SI directly, user cannot select the customer on those doctypes.

Looks like this is only an issue if Supplier/Customer Naming By in Buying/Selling Settings is set to Naming Series.

### Module

selling

### Version

ERPNext: v14.4.0 (HEAD)
Frappe Framework: v14.13.0 (HEAD)

### Installation method

FrappeCloud

**Comment by Ciangi** [comment]
not working for me also.

**Comment by rohitwaghchaure** [comment]
@muchai Thanks for reporting the issue, we have identified and [fixed](https://github.com/frappe/erpnext/pull/32832) the issue. Soon we'll release the fix of this issue.

**Comment by rohitwaghchaure** [comment]
@muchai we have released the fix, could you please update your instance and check

**Comment by muchai** [comment]
@rohitwaghchaure Seen it. Thank you. Will update tonight. It's a prod site. Had switched to Customer Name on Selling Settings in the meantime.

**Comment by Ciangi** [comment]
@rohitwaghchaure  It is working thanks.  

btw. could you also check this bug - it is looks like heavy bug  https://github.com/frappe/erpnext/issues/32774

Thanks for your work !
