### ISSUE TITLE
Healthcare invoice and customer name

### ISSUE THREAD

**Issue by 3ml3ml** [frappe/erpnext#32839]
### Information about bug

As a veterinary clinic we activate the option to add multiple patients under 1 customer .. but in the customer list we don't see the customer name and instead the name of the latest patient added and the customer name is just ID. 

during the invoice, if I am doing an invoice for any patient, the customer name is the latest add patient name. 

### Module

CRM, other

### Version

14

**Comment by dj12djdjs** [comment]
Hello @3ml3ml

The healthcare module has been moved into a different repository. Please open your issue here: https://github.com/frappe/health
