### ISSUE TITLE
Fields checked as `Read Only` and `Hidden` in `DocTypes` can't be redefined

### ISSUE THREAD

**Issue by MaxMorais** [frappe/erpnext#3283]
After a long time trying to help the user @monojocker to personalize the recipiend that is auto-selected by method `cur_frm.email_doc` I found that we aren't able to replace the value of the field.

It works too for others fields, like display address, for example, if you create and Save a Sales Order, refresh the page and select another addres of the customer the field display address is not updated, and the `contact_email` and all others fields that match with this condition

![download](https://cloud.githubusercontent.com/assets/1288676/7695251/f6a4133c-fdc2-11e4-814f-d0c54d659038.png)

**Comment by rmehta** [comment]
If you edit, it will be updated with master? is that the issue?

**Comment by MaxMorais** [comment]
@rmehta when the doctype is new, I can add values for these fields, but after save, if I change the value e save again the doctype, the field return to the previous value.

**Comment by rmehta** [comment]
Is this fixed now?
