### ISSUE TITLE
Redesign - Item Variants

### ISSUE THREAD

**Issue by neilLasrado** [frappe/erpnext#3284]
In Item Table, 

- [ ] Make button 'Add Variants'
- [ ] On click of button open new Form
- [ ] Form will have Attribute and Attribute Value
- [ ] Create Item Variants as cross product of attribute and attribute value.
- [ ] Allow user to check uncheck variants to be created.
- [ ] Allow user to change item Code for variants

![mockup-item-varients](https://cloud.githubusercontent.com/assets/8401344/7696806/9cc6b764-fe1e-11e4-978b-ecbfed6ddf5f.png)

**Comment by sliska** [comment]
Hello, 
I updated my vm but when I clic on "Manage variants" I get an error message saying "Did not load. Not permitted." 

Why? How do I fix this?

Thanks,
Sofia

**Comment by nabinhait** [comment]
Can't replicate the issue. Check if you have permissions on Manage Variants.
