### ISSUE TITLE
Unable to open dashboards from any modules

### ISSUE THREAD

**Issue by maveezmh** [frappe/erpnext#32842]
### Information about bug

Unable to open dashboards from any workspaces. it throws blank screen. 
but when i open dashboard list open specific dashboard and then click show dashboard the dashboard will load. 

and on clearing cache same issue persists again.

![image](https://user-images.githubusercontent.com/112148467/199914408-1eab4502-e19c-4a96-829c-8ef387845a62.png)

### Module

other

### Version

ERPNext: v14.5.1 (HEAD)
Frappe Framework: v14.14.1 (HEAD)
Frappe HR: v1.0.0 (HEAD)
Payments: v0.0.1 (HEAD)

### Installation method

FrappeCloud

**Comment by ankush** [comment]
Not enough info to debug anything. 

- Is there any error? 
  - open browser console with F12 > Console and see if there are any errors 
- What's URL?

**Comment by ankush** [comment]
Duplicate https://github.com/frappe/frappe/issues/18662
