### ISSUE TITLE
Pricing rule applies on Buying, even though it's ticked for Selling, and also applies on selling even though ticked for Buying.

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#32853]
### Information about bug

Create a pricing, and set it for Selling under Party Information
![image](https://user-images.githubusercontent.com/1822868/200116267-0d41d7d2-4ce0-4a15-8398-6dadff2ca75e.png)

The Rule applies even on Buying Doctypes (PO/PR/PI)
![image](https://user-images.githubusercontent.com/1822868/200116354-cb4c28cc-e726-4e6f-a4c7-3317e725d397.png)

Same case, even if it's ticked just for Buying, it applies on Selling Doctypes (SO/DN/SI)

### Module

buying, selling

### Version

ERPNext: v14.5.1 (HEAD)
Frappe Framework: v14.14.2 (HEAD)

### Installation method

FrappeCloud

**Comment by maharshivpatel** [comment]
@muchai I am unable to reproduce on v14.6.0. can you please share exact Pricing Rule details.

> Note: Make sure you don't have any other pricing rule that is being applied check Pricing Rule Detail table to double check if it this the same pricing rule.

**Comment by muchai** [comment]
First, we created a promotion scheme.
![image](https://user-images.githubusercontent.com/1822868/201596742-9999e9d4-e4a8-41fe-8b1e-d24120c7c013.png)

Which created the pricing rule below
![image](https://user-images.githubusercontent.com/1822868/201596932-e69842e4-5069-46df-bff0-49a2112201bc.png)
