### ISSUE TITLE
Currency error in number card

### ISSUE THREAD

**Issue by centaur78** [frappe/erpnext#32869]
Hi @prssanna 

For number card when Grand totals for the any doctypes ( Quotes, invoices etc) are selected and saved it doesn't show the quoted currency but the company currency like below

As you can see RO here is the company currency and value is the sum of Grand totals in Euro which is quoted.

Showing the value in quoted currency rather than company currency is useful in Multi currency environment.

![currency error](https://user-images.githubusercontent.com/1904802/80622989-a188ac80-8a5a-11ea-9a3f-5e1efd3c8279.png)

**Comment by deepeshgarg007** [comment]
@centaur78 ERPNext has the ability to create muti-currency quotes. Some quotes can be in the customer's currency and some can be in the company's currency. Basically what I mean to say is there could be multiple currencies involved. Number cards are mostly used for showing summary-level information and when multiple currencies are involved they have to be normalized to a base currency and displaying in the company currency makes more sense here hence we do it that way.

In case you want in some other currency making a custom one should be easy enough I guess
