### ISSUE TITLE
Log not maintained for SMS

### ISSUE THREAD

**Issue by betabank** [frappe/erpnext#3288]
Comes from discuss:
https://discuss.frappe.io/t/where-are-the-sms-sent-via-sms-center/5928

**Comment by williamjmorenor** [comment]
+1

**Comment by rmehta** [comment]
@betabank @williamjmorenor 

Can you check if this works? We don't have an SMS Gateway

https://github.com/rmehta/erpnext/commit/9624bac3cfbf5e9cb3bd1fd283387e79364a2651

**Comment by betabank** [comment]
Yes, we already checked. It is not working the SMS log list. We can help with SMS test in ERPNext of this feature or any other.

**Comment by rmehta** [comment]
do you see an error? can you add `frappe.db.commit()` after insert and check if it works?

**Comment by betabank** [comment]
Hi, no, we do not see any error, the sms is sent OK from the SMS center, parameters are also sent OK. The only problem is that is not appearing in the log. We just know is working because we received the SMS but we cannot check anything in the log. We thought that we needed to make a special configuration but in the forum was said that the log is just not maintained for SMS.

In case you need further debugging, please send detailed instructions and we can do it.

**Comment by sbkolate** [comment]
+ 1,
I have successfully send sms from ERPNext, but in sms log I can not see message log

**Comment by rmehta** [comment]
Please fix this:

https://github.com/rmehta/erpnext/commit/9624bac3cfbf5e9cb3bd1fd283387e79364a2651

Test if this works.

**Comment by nirjhar** [comment]
It is not yet fixed. Mr @rmehta please give us an update.

**Comment by rmehta** [comment]
We will include the fix in the next release.

**Comment by cgpurbaugh** [comment]
Any update on this?

**Comment by rmehta** [comment]
This seems fixed.
