### ISSUE TITLE
Opportunity is not updated to converted after a sales order is created

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#32904]
### Information about bug

Opportunity is not updated to converted after a sales order is created, it still remains in quotation stage

### Module

CRM

### Version

ERPNext: v14.6.0 (HEAD)
Frappe Framework: v14.14.3 (version-14)

### Installation method

FrappeCloud

**Comment by deepeshgarg007** [comment]
<img width="1342" alt="image" src="https://user-images.githubusercontent.com/42651287/201106442-8fc59dfb-6965-406a-9d91-bf0b37a859b4.png">

@muchai I just checked and the status correctly got converted as "Ordered" for me. If there are more steps please update and reopen the issue

**Comment by muchai** [comment]
@deepeshgarg007 I meant Opportunity.

For Lead, and Quotation, as you show here, they are updated to Converted, Ordered respectively, Opportunity remains as Quotation even after a sales is created.
