### ISSUE TITLE
Item Reposting

### ISSUE THREAD

**Issue by amendsaccounting** [frappe/erpnext#32903]
### Information about bug

Item Reposting is pending around 14,000 transactions and it is affecting stock balance report as well.

### Module

stock

### Version

ERPNext: v13.34.0 (version-13)

Frappe Framework: v13.33.0 (version-13)

### Installation method

docker

**Comment by deepeshgarg007** [comment]
@amendsaccounting Please give more relevant information to investigate. Your background jobs might not be running hence the repost might be pending

**Comment by amendsaccounting** [comment]
> @amendsaccounting Please give more relevant information to investigate. Your background jobs might not be running hence the repost might be pending

Back ground jobs are running and we tried to start reposting through script as well.But still all the items are qued.
