### ISSUE TITLE
Could not Cancel Purchase Invoice

### ISSUE THREAD

**Issue by knaveenhyperbaric** [frappe/erpnext#32906]
### Information about bug

teknamfg.erpnext.com
Could not cancel  or delete purchase invoice
attached error report
![Uploading image.png…]()

### Module

accounts

### Version

ERPNext: v14.4.0 (HEAD)

ERPNext Support: v0.2.1 (HEAD)

Frappe Framework: v14.13.0 (HEAD)

Frappe HR: v1.0.0 (HEAD)

**Comment by knaveenhyperbaric** [comment]
https://user-images.githubusercontent.com/117721538/200828702-dea01aa3-50c5-4caa-94b4-0da1b5ce0b49.mp4

the issue still remains same

**Comment by knaveenhyperbaric** [comment]
https://user-images.githubusercontent.com/117721538/200830727-b307dfa0-d9da-466a-a11e-805e76a1c791.mp4

issue attached for your reference.

**Comment by deepeshgarg007** [comment]
@knaveenhyperbaric Please also add the traceback that you get when you try to cancel and then reopen the issue

**Comment by knaveenhyperbaric** [comment]
Hi

How to add traceback?

 

Thank You.

Best Regards,


Naveenkumar M

Purchase Team
Ph: 044-42116555/ 22501157

 


 <https://hyperbaric-chamber.com/> 

INDIA
Tekna Manufacturing Pvt. Ltd.,
C19, Industrial Estate,
Guindy, Chennai, India - 600032
Ph No. +91-44-42116555
