### ISSUE TITLE
Workflow - After Approve/Reject, If doc level remain same, workflow state is not updated

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#3290]
Steps:

Following is the Workflow rule for Purchase Order.

![screen shot 2015-05-19 at 5 13 12 pm](https://cloud.githubusercontent.com/assets/910238/7702017/5cf9ff84-fe4a-11e4-83fd-1b7194e5e066.png)

When Purchase Manager approve, doc level remains 1 only. Hence in the Purchase Order, status remain Draft. But workflow state is correctly updated to "Approved by Purchase Manager".

![screen shot 2015-05-19 at 5 16 03 pm](https://cloud.githubusercontent.com/assets/910238/7702064/daeeb2a4-fe4a-11e4-97bf-ff2a7190cd9e.png)

**Comment by rmehta** [comment]
Fixed. Release tomorrow?
