### ISSUE TITLE
Comments and activities on lead could be displaying for created by, not created by and for that specific lead

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#32916]
### Information about bug

![image](https://user-images.githubusercontent.com/1822868/200900042-b8c3b9ef-9f65-471e-b1f8-3f0db3e752b2.png)

All comments above are not for the lead 00237, the comments were created way before this lead.

This is the same case for activities

### Module

CRM

### Version

ERPNext: v14.6.0 (HEAD)
Frappe Framework: v14.14.3 (version-14)

### Installation method

FrappeCloud

**Comment by nabinhait** [comment]
Have you deleted lead records and reset the naming series after that? A hidden child table called "Notes" holds all the comments data. It seems like the child records have not been deleted while deleting the parent lead, which gets linked automatically with a separate lead record.
