### ISSUE TITLE
Foreign Currency Account Payable and General Ledger are not same

### ISSUE THREAD

**Issue by thida-bcn** [frappe/erpnext#32959]
### Information about bug

1)Create Supplier with Foreign Currency
![image](https://user-images.githubusercontent.com/62122640/201804615-0ef8c51c-f3a6-4ea8-9158-b097e5207067.png)
2) Setup Exchange Rate
![image](https://user-images.githubusercontent.com/62122640/201804680-59dd9058-5916-477f-b1c0-439b14441f63.png)
3) Open Purchase Invoice
Invoice Date is 31/10/2022
changed currency rate to 2900
![image](https://user-images.githubusercontent.com/62122640/201804778-5fbac1b6-2857-482f-9c30-6ef95e825314.png)
Total USD =10
Total MMK = 29000
![image](https://user-images.githubusercontent.com/62122640/201804822-be779b39-2d42-4e9b-99b1-6e6b09a5cc28.png)
4) View Account Ledger
![image](https://user-images.githubusercontent.com/62122640/201804889-d97e5699-55ae-412e-bf2e-5f70d9bb5705.png)
showing with based currency 29000
![image](https://user-images.githubusercontent.com/62122640/201804962-25cd3b83-cc40-41bc-bbd9-a07cb45cacff.png)

choose USD
To Date 14/11/2022
amount showing 9.51 (29000/3050)
![image](https://user-images.githubusercontent.com/62122640/201805090-6b95f130-c8db-4255-bafe-4c6b1b0318ea.png)
choose USD
change To Date 31/10/2022
amount showing 10.36 (29000/2800)

5) Account Payable
![image](https://user-images.githubusercontent.com/62122640/201805336-d5775b92-2dda-4f1b-988c-4ffdda115180.png)

in USD amount showing 10 USD same as transaction
![image](https://user-images.githubusercontent.com/62122640/201805428-80234a7e-07d2-47db-992f-690515a637c5.png)

in MMK amount showing 29000 MMK same as transaction

why didn't system show transaction rate?

### Module

accounts

### Version

ERPNext: v13.41.1 (version-13)

Frappe Framework: v13.43.2 (version-13)

**Comment by dj12djdjs** [comment]
https://github.com/frappe/erpnext/issues/34680
