### ISSUE TITLE
Quotation items are fetched multiple times

### ISSUE THREAD

**Issue by maveezmh** [frappe/erpnext#32985]
### Information about bug

While creating sales order when we do fetch items from quotation. am able to pull same items multiple times in the sales order. 

The below warning message is coming but the items are already getting added multiple times in sales order

![image](https://user-images.githubusercontent.com/112148467/202118085-ac0663a5-62da-448a-b23d-1fc5b8b6ecac.png)

### Module

selling

### Version

ERPNext: v13.41.1 (HEAD)
Frappe Framework: v13.43.2 (HEAD)

### Installation method

FrappeCloud

**Comment by Nihantra-Patel** [comment]
This issue occurs for all doctypes when retrieving items from sales orders or purchase orders.

It is defined in the core code and applies universally.

**Comment by maveezmh** [comment]
??? @Nihantra-Patel can we not fetch the quotation items and show error

**Comment by Nihantra-Patel** [comment]
Hey, you can fetch the items, but when you do, it will retrieve all of them. You will need to remove any items you don't want, as this occurs in both sales and purchase transactions.
