### ISSUE TITLE
Blank Password created every time User details are modified

### ISSUE THREAD

**Issue by ekpaxp** [frappe/erpnext#3299]
Hi, in ErpNExt v5.0.0-beta, every time a Users permissions or module access are changed, the password is reset and a pop-up box appears to say that a new Password has been emailed to the suer - even though the password was not changed.

**Comment by rmehta** [comment]
This has been fixed with the latest release. Can you check?

**Comment by ekpaxp** [comment]
Just pulled the latest updates and all is good now.  Many thanks
