### ISSUE TITLE
Missing Domains

### ISSUE THREAD

**Issue by j209** [frappe/erpnext#32998]
### Information about bug

Missing domains like education ...

![image](https://user-images.githubusercontent.com/18129232/202310752-240bd868-68dc-48c0-baeb-a132606b443f.png)

### Module

education

### Version

14

### Installation method

FrappeCloud

**Comment by deepeshgarg007** [comment]
@j209 Domains are separated into different apps, you will have to install them separately
Repo for education app https://github.com/frappe/education
