### ISSUE TITLE
Not Able to Cancel Purchase Invoice

### ISSUE THREAD

**Issue by knaveenhyperbaric** [frappe/erpnext#33000]
### Information about bug

Website: teknamfg.erpnext.com

Not Able to Cancel Submitted Purchase Invoice 
[Not Able to Cancel Purchase Invoice.webm](https://user-images.githubusercontent.com/117721538/202369018-a953a86f-19f5-440c-88f6-457c139b31d0.webm)

![image](https://user-images.githubusercontent.com/117721538/202369206-ac4a02ba-8432-4c44-9b09-d79c39984dec.png)

### Module

accounts

### Version

ERPNext: v14.4.0 (HEAD)

ERPNext Support: v0.2.1 (HEAD)

Frappe Framework: v14.13.0 (HEAD)

Frappe HR: v1.0.0 (HEAD)

Journeys: v0.0.1 (HEAD)

Payments: v0.0.1 (HEAD)

### Relevant log output / Stack trace / Full Error Message.

```shell
Only Error Message is showing. No Traceback
```

**Comment by deepeshgarg007** [comment]
@knaveenhyperbaric please add more information for investigation and then reopen. Not replicable right now.

**Comment by knaveenhyperbaric** [comment]
Hi

I am getting only the error message. Not any trace back detail. 

Please help with the information you need.

 

Thank You.

Best Regards,


Naveenkumar M

Purchase Team
Ph: 044-42116555/ 22501157

 


 <https://hyperbaric-chamber.com/> 

INDIA
Tekna Manufacturing Pvt. Ltd.,
C19, Industrial Estate,
Guindy, Chennai, India - 600032
Ph No. +91-44-42116555
