### ISSUE TITLE
Purchase invoice connection issue / Can't create payment from Purchase invoice / Purchase invoice options missing

### ISSUE THREAD

**Issue by zenicolas** [frappe/erpnext#33026]
### Information about bug

Creating payment entries from a purchase invoice isn't available. 

Options for purchase invoices are not available. 

Not really sure when this started to happen. I was updating the invoices for some suppliers and noticed this happening. 

Regarding user permission, I have super admin permissions. 

Apologies if this bug was already reported in another issue, didn't find it under the similar subject wordings.

<img width="1728" alt="Screenshot 2022-11-18 at 08 37 13" src="https://user-images.githubusercontent.com/26570996/202628810-8d3a84f9-9e35-450b-b765-78bdb6c408cd.png">

<img width="1728" alt="Screenshot 2022-11-18 at 08 36 41" src="https://user-images.githubusercontent.com/26570996/202628776-60779ecd-3c9b-45e5-bf1e-cf6021cd02b3.png">

### Module

accounts

### Version

Agriculture: v0.0.1 (HEAD)

Frappe Chat: v0.0.1 (HEAD)

Education: v0.0.1 (HEAD)

ERPNext: v14.7.0 (HEAD)

Frappe Framework: v14.15.0 (HEAD)

Frappe HR: v1.0.0 (HEAD)

Frappe LMS: v0.0.1 (HEAD)

Payments: v0.0.1 (HEAD)

Wiki: v0.0.1 (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
No error message, just missing action button
```

**Comment by deepeshgarg007** [comment]
<img width="1339" alt="image" src="https://user-images.githubusercontent.com/42651287/202676555-a199938a-ed96-4e96-967f-abd45c69f368.png">

I just checked and it works fine for me, I can see the Payment Button. This might also happen in case any client-side script fails. Please check the browser console for any errors. If this is a core issue you will be able to replicate on other sites as well. Please check that too and reopen if issue persists

**Comment by zenicolas** [comment]
Hi Deepesh, 

Thank you for your input. Attached the script errors that appear on my end. 

As for the client-side script, we only have one script working and it is not linked to the purchase invoice doctype. 

Let me know your thoughts. 

Thank you again. 

<img width="1728" alt="Screenshot 2022-11-21 at 16 11 57" src="https://user-images.githubusercontent.com/26570996/203063966-ea15a457-49d3-4ae9-a807-33155d0f6afa.png">

**Comment by zenicolas** [comment]
@deepeshgarg007 any idea regarding this issue ? 

It seems you were right regarding the Script error. How can I fix this ? 

Thanks
