### ISSUE TITLE
Purchase Invoice Issue with Tax Withheld Vouchers 

### ISSUE THREAD

**Issue by Donferarri92** [frappe/erpnext#33040]
### Information about bug

Unable to Amend and Save a Purchase Invoice.
![New-Purchase-Invoice-new-purchase-invoice-2](https://user-images.githubusercontent.com/90032072/202845843-93753e11-8a3f-4ba2-be0a-55c1f2a65af6.png)

Steps to reproduce:

Inside a Purchase invoice there is a section for Tax Withheld Vouchers. Whenever we create a Purchase invoice, the previous invoice of the respective supplier gets linked with this current purchase invoice. as shown below:

![New-Purchase-Invoice-new-purchase-invoice-2(1)](https://user-images.githubusercontent.com/90032072/202846079-4b1d63a7-1eb5-470a-9a58-d8fea47c6d8a.png)

Now if we need to do amendment because of any reason, we do it in any of the above linked invoice. 
Again we happened to do amendment on the original invoice and we cancel it, amend and now we click on save. We get the error.

**Expected process: When we amend the original invoice, and new invoice is created in draft. The Tax Withheld Vouchers should get refreshed with new invoice numbers in case any invoice in amended.**

### Module

accounts

### Version

Frappe Version: v13.41.6 (version-13)
ERPNext Version: v13.39.1 (version-13)

### Installation method

manual install

**Comment by deepeshgarg007** [comment]
@Donferarri92 All these issues were recently resolved. Please update your branches and check again
