### ISSUE TITLE
Discount on Other Item not working properly

### ISSUE THREAD

**Issue by sjain17** [frappe/erpnext#33047]
### Information about bug

Use Case 
If we create a pricing rule for Price based discount using the below conditions - 

1. Apply On = Item Group
2. Fill the table with 2 Item Groups Apply Rule On Item Group (Item Group = Grocery and Electronics)
3. Mixed Condition =1
4. Price or Product Discount = Price
5. Discount on Other Item >> Apply Rule On Other = Item (for example = Nike Sports Shoes) and Select any item which is not part of the above-selected group in Apply Rule On Item Group (Child Table).
6. Party Information>> Selling =1
7. Min Amt = INR 1000
8. Price Discount Scheme>> Rate or Discount=Discount Percentage, Discount Percentage= 50.

So the above condition is summarised as If you buy for Rs 1000 from Grocery and(or) Electronics you will get 50% off on Nike Shoes.

Actual Result -
The pricing rule is not applied because as per the code it searches the shoes into the above-selected item groups and then the discount is not applied because the shoes do not belong to the Grocery or Electronics group in the above example.

Expected Result -  
The system should show 50% discount on item code of Nike if the above said condition is fulfilled and should remove the discount if not met.

### Module

selling

### Version

Frappe Framework: v13.41.6
ERPNext: v13.39.1

### Installation method

manual install

**Comment by ruthra-kumar** [comment]
@Nihantra-Patel Is this still valid in v14 and above?

**Comment by Nihantra-Patel** [comment]
Yes @ruthra-kumar

**Comment by ruthra-kumar** [comment]
> Mixed Condition =1

This should be unchecked, without which 'Discount on Other Item' section will be unavailable.

It is due to apply_pricing_rule_on_item() applying rule on same item.
https://github.com/frappe/erpnext/blob/b3e163e9d835930aeff8fa47f5463c9c4ce46ebd/erpnext/public/js/controllers/taxes_and_totals.js#L9-L35
