### ISSUE TITLE
Point of Sales : Discount didn't reset

### ISSUE THREAD

**Issue by thida-bcn** [frappe/erpnext#33046]
### Information about bug

1) First time when we give a discount 
10%
2) next invoice needs to reset discount 

### Module

other

### Version

ERPNext: v13.41.1 (version-13)

Frappe Framework: v13.43.2 (version-13)

https://drive.google.com/file/d/1RJ8ESJONZ-cFtvVlqZHg0yvyLtOP5d6e/view?usp=share_link

**Comment by deepeshgarg007** [comment]
@thida-bcn Please add a GIF here itself for the issue and reopen the issue again

**Comment by thida-bcn** [comment]
> @thida-bcn Please add a GIF here itself for the issue and reopen the issue again
1st invoice with 10 % discount
![image](https://user-images.githubusercontent.com/62122640/207053712-0833d5cf-cfa0-40d6-b9e6-80cc086c54fb.png)
![image](https://user-images.githubusercontent.com/62122640/207053758-8861b98a-c48b-46b4-ab7e-20d30402627b.png)
![image](https://user-images.githubusercontent.com/62122640/207053798-ee673598-0645-437a-863c-43c9a124bc5e.png)
2nd invoice
![image](https://user-images.githubusercontent.com/62122640/207053903-2e4dc418-bda5-4915-a1d9-cfb7e68cbb0a.png)
![image](https://user-images.githubusercontent.com/62122640/207053952-bae21f4f-7960-4456-ac5c-dc4397b201d1.png)
![image](https://user-images.githubusercontent.com/62122640/207053992-7a44caeb-11c5-4d74-a8ab-e97ad63d6f0f.png)
