### ISSUE TITLE
Quotation - Discount on line items gets ignored

### ISSUE THREAD

**Issue by fblauer** [frappe/erpnext#3305]
I tried entering a line item with a discount on a quotation. It does not use the line item discount in the calculation, nor save it. It just seems to get dropped. Same thing happens on the sales order, and also the sales invoice?

**Comment by umairsy** [comment]
Hello,

Works fine in the Quotation made on my test account.

![screen shot 2015-05-21 at 12 00 28 pm](https://cloud.githubusercontent.com/assets/910238/7742792/0a1b085e-ffb1-11e4-92d4-bb8bad2ddf4b.png)

Also itemwise discount was carried forward correctly in the Sales Order and Sales Invoice. Please have %Discount showing in the print format, ensure it has Print Hide unchecked in the Customize Form.

**Comment by fblauer** [comment]
I can't figure out how to get this. If I go to "customize form" I don't see a field called %discount, or discount%. I only see a table field for item. How do I get to this field?
![screenshot from 2015-05-21 08 50 06](https://cloud.githubusercontent.com/assets/1015215/7748892/be445e0e-ff96-11e4-8b0e-5244d302caac.png)

**Comment by fblauer** [comment]
This is the items table field, it is not hidden:
![screenshot from 2015-05-21 08 57 09](https://cloud.githubusercontent.com/assets/1015215/7748982/9dce8a4a-ff97-11e4-8cd5-9c8a30e9c48c.png)

**Comment by fblauer** [comment]
This is my print format with discount% checked:
![screenshot from 2015-05-21 09 07 00](https://cloud.githubusercontent.com/assets/1015215/7749133/dd03b32e-ff98-11e4-9f31-03a70f8ea365.png)

**Comment by fblauer** [comment]
This is what I see on the screen. Can't figure out how to get to the discount% field on the form customization. What am I missing?
![screenshot from 2015-05-21 09 09 00](https://cloud.githubusercontent.com/assets/1015215/7749162/1220d5d2-ff99-11e4-8f6b-b58c1a9a126c.png)

**Comment by nabinhait** [comment]
In Customize Form, select "Quotation Item".

**Comment by fblauer** [comment]
OK, I just found that, but it still doesn't work for me. I still see the same screen with no discount? 
![screenshot from 2015-05-21 09 17 59](https://cloud.githubusercontent.com/assets/1015215/7749320/964d0db6-ff9a-11e4-9f2a-c6ca03180baa.png)

**Comment by fblauer** [comment]
I still can't get discount to show up?
![screenshot from 2015-05-21 09 23 23](https://cloud.githubusercontent.com/assets/1015215/7749424/683b234e-ff9b-11e4-8a2f-7f9fe12a45db.png)

**Comment by anandpdoshi** [comment]
Hi Fred,

So you want to see the discount value in the Item table while in the form.
Am I right?
(From the title it seemed that discount value isn't applied and the rate
isn't changing.)

Thanks,
Anand.

**Comment by fblauer** [comment]
The extended value doesn't change. If I enter a line item discount it is currently ignored, and keeps going back to 0. It does not show up in the line item calculation on any of the sales forms, nor on the screen, nor on the print out. According to Umair, it is in the calculation and shows up everywhere? So, apparently his system is different than mine. I can't figure out how to get it to behave that way, which is what most people would expect when entering a discount.

**Comment by anandpdoshi** [comment]
Have you defined any Pricing Rule?

**Comment by fblauer** [comment]
No

**Comment by fblauer** [comment]
Is that required in order to have a line item discount?

**Comment by anandpdoshi** [comment]
No. But it could explain that discount could be getting replaced by 0 based
on a Pricing Rule.

**Comment by fblauer** [comment]
I tried it on the demo database on the erpnext site, and the calculation seems to behave correctly. I am trying to figure out why mine is different.

**Comment by anandpdoshi** [comment]
Can you raise a ticket on support. Could be a data related issue. We will access your quotation and look at the possibilities.

**Comment by fblauer** [comment]
How is a ticket different than an issue that I raised here? Where would I do that? 
I just created a standard SAAS instance. I didn't do any customization, other than to add a few user defined fields in Issues, notes and todos. I didn't do anything in the sales module, other than enter a few test transactions.

**Comment by nabinhait** [comment]
@fblauer I want to verify the basic concept:
Do you have Price List Rate? Discount applied on Price List Rate and rate is calculated after discount is applied on Price List Rate.

**Comment by fblauer** [comment]
OK, it works for the product/items, but not the services. Do I have to create a price list for the services?

**Comment by nabinhait** [comment]
Yes, item-wise discount is only applied on the price list rate. You have to create price list for service item as well.

**Comment by fblauer** [comment]
OK, that works, thanks

**Comment by Tazintosh** [comment]
Hi @fblauer
Sorry to resurrect this topic, but I'm experiencing the exact same issue (cannot apply a discount per item).
Sadly I cannot get it to work even with the explanations here. Would you mind to give me a precise step by step to get this showing up and actually calculating?
I'm running ERPNext: v14.0.0-dev
Thanks a lot in advance
