### ISSUE TITLE
outstanding amount

### ISSUE THREAD

**Issue by robertbecht** [frappe/erpnext#3307]
![image](https://cloud.githubusercontent.com/assets/1532439/7737350/ab05beec-ff4a-11e4-8609-de6d2cf3cd99.png)

Outstanding amount of Euro 0.01>> saw a bottom (x) with write of outstanding amount>> does not work

**Comment by anandpdoshi** [comment]
X means that "Write Off Outstanding Amount" wasn't checked. It should be a
tick-mark.

**Comment by robertbecht** [comment]
hi anand,

 yes discovered this later. However, this payment list as "overdue" due to
a roundoff error. Would be "an improvement"if this could be "repaired"
without writing a JV even if the invoice is submitted.

rgds robert
