### ISSUE TITLE
Chart of Accounts : incorrect Currency Code

### ISSUE THREAD

**Issue by thida-bcn** [frappe/erpnext#33081]
### Information about bug

1) Create a Group Company with Based Currency is MMK
![image](https://user-images.githubusercontent.com/62122640/203378378-f8e610b1-f64d-40fc-942d-e98c7c6aaf1a.png)

2) Create Child Company1 with based currency is MMK
![image](https://user-images.githubusercontent.com/62122640/203378468-99edb39b-12c0-4a9a-892c-a27f152141fc.png)

3) Create Child Company2 with based currency is MMK
![image](https://user-images.githubusercontent.com/62122640/203378803-3f39016c-502e-4b25-8755-994c8871ff91.png)

4) Create a Chart of Accounts with other currency 
![image](https://user-images.githubusercontent.com/62122640/203379049-6b8de182-7986-4a28-bac3-e00dbebe4df0.png)

Expected Result:
The chart of Accounts in the Child Company should be the same as the Parent Company

but the system created COA with based currency in Child Company
![image](https://user-images.githubusercontent.com/62122640/203379215-fe37e02e-8296-4e81-bb95-60aa48cb8a34.png)

### Module

accounts

### Version

ERPNext: v13.41.1 (version-13)

Frappe Framework: v13.43.2 (version-13)

**Comment by deepeshgarg007** [comment]
@thida-bcn Do you mean the USD as currency was added by default? Can you please add a gif for this? Is there any default value configured using user permissions or any session defaults being set?

**Comment by deepeshgarg007** [comment]
Please reopen after adding more info
