### ISSUE TITLE
where is the (very useful) history ???? in v5.0

### ISSUE THREAD

**Issue by robertbecht** [frappe/erpnext#3308]

**Comment by anandpdoshi** [comment]
If you click on the Awesome Bar, the default list you get is the history.

**Comment by robertbecht** [comment]
thnx, robert
One issue that drives me nuts:: in sales the default quantity is zero. Can
this be changed to one (1) as it used to be.
Very irritating. Many items are sold as one and easy to forget, and a need
for extra action (change from zeo to one)
rgds robert

**Comment by anandpdoshi** [comment]
@nabinhait can you look into this?

**Comment by nabinhait** [comment]
@robertbecht I know it is very irritating, even for us (software service) qty is always 1. We have already discussed about this internally. Actually there was some specific reason why we set it as 0, but unfortunately we could not remember it. Anyway, we will give a deep though on it, will try to reset it as 1. Thanks for your valuable feedback as always :)

**Comment by nabinhait** [comment]
Closing this issue, another issue #3309 is open.
