### ISSUE TITLE
Rate of Finished Goods is not calculating correctly in case there is a process Loss Involved

### ISSUE THREAD

**Issue by JitendraSAW** [frappe/erpnext#33094]
### Information about bug

We are in a Paint Manufacturing Industry.

1. We have a use case where out of Total Qty- 97, out of Which 1 Qty is consider as a Process Loss (Scrap), 
2. When we record the Manufacture Entry of Qty-97, 1 Qty taken as a Scrap, Hence 96 is the actual Qty which is Actual Yield Qty
3. But the Valuation of the above Qty of FG Item is showing wrong- It shows wrong Valuation- It is showing wrong valuation =13521.26/97=139.3944, wheras it should show- 13521.26/96=140.8465, since the actual yield qty is 96 whereas it is considering even the Process Loss Qty also which should not be as this qty is totally loss for me.

![image](https://user-images.githubusercontent.com/80260184/203714434-4d1f35e7-3a36-43a8-816d-4d2b7e39d111.png)

![image](https://user-images.githubusercontent.com/80260184/203714516-b98280d9-0287-450c-b330-8932164e3641.png)

![image](https://user-images.githubusercontent.com/80260184/203714576-f8d6e535-a737-4e87-b07f-349555f310e4.png)

![image](https://user-images.githubusercontent.com/80260184/203714623-488c7a71-f6d6-4002-a890-25edd4b8f738.png)

![image](https://user-images.githubusercontent.com/80260184/203714720-c580e920-61fa-4dd4-9e5b-765a7d2c118d.png)

### Module

manufacturing

### Version

![image](https://user-images.githubusercontent.com/80260184/203715210-6cbe23b9-26e1-4a73-ad93-9e4389e60736.png)

### Installation method

FrappeCloud

**Comment by goapaints** [comment]
Please also note that Process Loss should not have a TARGET WAREHOUSE.

**Comment by rohitwaghchaure** [comment]
@JitendraSAW 

We are adding process loss in the inventory to match up the "For Quantity" and sum of FG item's quantity in the manufacture stock entry. If we keep the FG item quantity less than "For Quantity" then system throws the error that "The finished product quantity and For Quantity cannot be different".

I understand your point that the Process Loss should not be the part of Inventory. To fix this problem I am suggesting a solution that if the Item has Is Process Loss flag then that item won't be added in the Inventory. If the item has the flag Is Scrap Item then item will add the item in the Inventory. If the item as both Is Process Loss and Is Scrap Item then also system will add that item in the stock.

Process Loss condition                       
1) If the Item has checkbox "Is Process Loss" **->** **Don't add Item in the Inventory**
2) If the Item has checkbox "Is Scrap Item" **->** **Add Item in the Inventory** 
3) If the Item has checkbox "Is Scrap Item" & "Is Process Loss" **->** **Add Item in the Inventory**

**Comment by goapaints** [comment]
Hi Rohit,

Ideally, no inventory should be both process loss and a scrap item. ie A
scrap which cannot be recovered is a process loss.

Further,

Process loss should not insist on batch No and especially QI, even if
mandated in Item Master.

Value difference should be zero. ie
FG Valuation = {(Value of Input- Value of Scrap)/(Is finished qty)}

**Comment by goapaints** [comment]
Hi Rohit,

Please note that process loss percentage should be editable in
manufacturing stock entry, as exact process loss will vary from batch to
batch.

Thanks.
