### ISSUE TITLE
Stock Entry 

### ISSUE THREAD

**Issue by shivashakti** [frappe/erpnext#3311]
1. Created item
2. Entered the same in "Stock Entry" with quantity and price
3. Submitted
4. Created "Material Transfer" from Default warehouse to Target WareHouse
5. Stock Reconcilation processed
6. While Opening POS, it shows the time but quantity and value shows as "0".
7. What could be the issue

**Comment by nabinhait** [comment]
Can you see the qty in Stock Balance report?

**Comment by shivashakti** [comment]
Yes Nabin,

Can see the quantity in Stock Balance Report.

Regards,
Mukesh

**Comment by nabinhait** [comment]
Can you try to replicate the issue in demo.erpnext.com?

**Comment by shivashakti** [comment]
Sorry for delayed response Mr. Mehta. The issue has been solved. However, will surely replicate the issue in demo.erpnext.com
