### ISSUE TITLE
Accounting Dimension is not working properly

### ISSUE THREAD

**Issue by thida-bcn** [frappe/erpnext#33119]
### Information about bug

1)Setup Accounting Dimensions
![image](https://user-images.githubusercontent.com/62122640/204070187-dff5e4a7-c39e-473e-aa26-45804acde29e.png
2) Sales Invoice
I couldn't find Accounting Dimension
![image](https://user-images.githubusercontent.com/62122640/204070201-48390a16-5e43-4541-a84a-91c475a2847f.png)
3) Journal Entry
![image](https://user-images.githubusercontent.com/62122640/204070216-8e52adec-b57f-4118-995c-aa242a4d351a.png)

Expected:
there must be department drop down under Accounting Dimension at Entry Form such as Sales Invoice, Purchase Invoice, Journal Entry

Remark:
Previous version is working
v13.24 (before upgrade latest version we are using that version)

### Module

accounts

### Version

ERPNext: v13.42.1 (version-13)

Frappe Framework: v13.45.0 (version-13)

### Installation method

manual install

**Comment by deepeshgarg007** [comment]
@thida-bcn Accounting Dimensions are created via background job, please check if your background job is working or not or if there are any error logs and reopen the issue
