### ISSUE TITLE
Sales Return - Clear payment schedule message issue

### ISSUE THREAD

**Issue by nidhipurohit11** [frappe/erpnext#33134]
### Information about bug

When creating a credit note from a submitted sales invoice, then selecting any date in due_date shows a message to clear the payment schedule table, but there is no such table in the credit note.

https://user-images.githubusercontent.com/82337328/204233879-fc0e8dcf-1ea3-4bf5-9f2a-3cef9e7c9b6d.mov

### Module

accounts

### Version

ERPNext: v14.x.x-develop () (develop)
Frappe Framework: v14.x.x-develop () (develop)
Payments: v0.0.1 (develop)

**Comment by ruthra-kumar** [comment]
@nidhipurohit11 Payment Schedule table is hidden for Return Invoices and POS. The table doesn't have any business implication for such types of Invoices. The message can simply be ignored. https://github.com/frappe/erpnext/blob/b8b9d1b0a874fc0906b4c3bac648c3e779a7d0d0/erpnext/accounts/doctype/sales_invoice/sales_invoice.json#L1317-L1325
