### ISSUE TITLE
Simple hiding of Valuation rate

### ISSUE THREAD

**Issue by hadi82** [frappe/erpnext#33130]
Hello

As annoying as it gets to all users, hiding valuation rates of items is essential in almost all companies, and since it cannot be done in report level (anyuser has an access to any report involving item doctype, can add a column of "valuation rate" which is considered privacy breach in many companies.

So I suggest adding a simple check box in user page, that will restrict or all having the ability to see"valuation rate / incoming rate" across all reports/documents, also would be cool if we can also have a check box for the ability to editing reports (adding columns) for these users as well.

I think this is so urgent and hope easy to develop on erpnext v13 and v14.

BRs
Hadi

**Comment by rohitwaghchaure** [comment]
@hadi82 you can easily remove the any column from any report and create your own new report


![remove_column](https://user-images.githubusercontent.com/8780500/204259270-1438f832-c3c3-4465-bd1e-b227d6124fd3.gif)


Using "Role Permissions for Page and Report" you can restrict roles to access the report 

<img width="1140" alt="image" src="https://user-images.githubusercontent.com/8780500/204259424-6222f98f-af29-425d-8287-144308eccb21.png">

**Comment by hadi82** [comment]
Thanks
We did this in many ways, but we always get the same result; the user can always add the item valuation through any report customized or standard, through the "add column" button.

If there is a way to hide it

**Comment by hadi82** [comment]
@rohitwaghchaure would you please help...
