### ISSUE TITLE
If a sales order is duplicated, some fields e.g. valuation rate don't get updated

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#33169]
### Information about bug

If an old sales order didn't valuation rate for some items, when it's duplicated, valuation rate is not updated on new sales order.
This is despite the fact that valuation rate is now available for the item.
At the time of creating the sales order, there was no valuation rate.
There're fields that need to be re-updated in case of duplicating some doctypes like sales order, et al.

### Module

selling

### Version

ERPNext: v14.8.0 (HEAD)

Frappe Framework: v14.16.0 (HEAD)

### Installation method

FrappeCloud

**Comment by muchai** [comment]
Or even more, Gross Profit report seems not to pick valuation rate in some cases, even though the valuation rate is present in the sales order.

**Comment by deepeshgarg007** [comment]
@muchai fields like valuation rate are intentionally not copied and are supposed to be recomputed, doesn't look like a bug

**Comment by muchai** [comment]
@deepeshgarg007 they should be recomputed for sure.

Issue is, when you pick an item afresh on a sales order, it picks the valuation rate.

When you duplicate an existing sales order, the valuation rate is set to zero, even though there's one.

This affects the gross profit report eventually.
