### ISSUE TITLE
Actual Start Date on Work Order and From Time/To Time on Job Cards should validate against future dates

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#33166]
### Information about bug

Right? They should.

Not sure about this, just doesn't seem to add up, where Actual Start Date on Work Order and From Time/To Time can be input for a future date, and the job cards, and work orders can be completed.

### Module

manufacturing

### Version

ERPNext: v14.8.0 (HEAD)
Frappe Framework: v14.16.0 (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

![image](https://user-images.githubusercontent.com/1822868/204531117-564440c3-ad9a-42bb-b322-76f8499bf92d.png)

**Comment by Nihantra-Patel** [comment]
when you're dealing with Work Orders and Job Cards, it's important to keep track of when things start and end.

For Work Orders, there's a function that sets the actual start and end dates based on the times recorded for each operation. If these times aren't available, it looks at related stock entries (like materials transferred or manufactured) to set these dates. This helps in calculating how long the work took, known as lead time.

For Job Cards, the system tracks both expected and actual times for each task. It gathers all the start and end times from the logs and sets the overall start and end dates based on the earliest and latest times recorded. It also calculates the total time spent.

If there's a concern about dates being set in the future, you might need to add checks to make sure dates are always current. This ensures the system accurately reflects the work being done.
