### ISSUE TITLE
Total qty field not available in stock entry

### ISSUE THREAD

**Issue by ram-chandu** [frappe/erpnext#33177]
Hi Team,

In Stock entry doctype, currently the total quantity field is not being shown but its shown at the Purchase order and purchase receipt. But when we send the stock to subcontractor through stock entry type send to subcontract. Usually here its showing the pieces in the stock entry but when we send stock in bulk and has number of items, it will be difficult to calculate the total qty as we need to go through item wise and calculate. Here we are expecting to have a total quantity field in stock entry as shown in the PO and PR. Please check attaching the screenshots for reference.

At Purchase Order
![9P6kZZF](https://user-images.githubusercontent.com/119317369/204726915-7556009e-0653-430c-b6c1-b0dbf022d97a.png)

At Purchase Reciept
![wdAcEs6](https://user-images.githubusercontent.com/119317369/204726999-fb88e029-c7c9-43f2-ad3d-a3ef4151dbcb.png)

At Stock entry
![Yho40kx](https://user-images.githubusercontent.com/119317369/204727042-a3bd5489-9f22-4a2d-adb4-891c517253a4.png)

Thanks.

**Comment by rohitwaghchaure** [comment]
@ram-chandu 
Stock entry used for multiple purposes like stock transfer, material receipt, material issue, repack, manufacture etc
How this total quantity field will work for each purposes? Obviously it's not straightforward sum of all items quantity.

Better you write a client script in the stock entry to full-fill your requirement

**Comment by rohitwaghchaure** [comment]
Add Total Qty custom field in the Stock Entry the add below script in the Stock Entry client script and check 
```
frappe.ui.form.on("Stock Entry", {
    validate(frm) {
          let total = 0.0
          frm.doc.items.forEach(row => {
               total += row.qty
          })
          
           frm.set_value("total_qty", total)
    }
})
```

**Comment by ram-chandu** [comment]
Hi Rohit,

Thanks for the script it really worked. Can we do this on the addition of new item in the stock entry. As now the total qty is getting updated on the save, can it cal and shown when we are adding new items in stock entry.

Thanks.
