### ISSUE TITLE
Customer Save button broken  

### ISSUE THREAD

**Issue by maxfu9** [frappe/erpnext#33190]
### Information about bug

The customer save button is not working

### Module

selling

### Version

v14.9.0

**Comment by deepeshgarg007** [comment]
@maxfu9 I just checked and it worked fine for me. Please avoid raising such issues without providing any information for anyone to investigate or replicate the issue

**Comment by maxfu9** [comment]
@deepeshgarg007  It was due to a custom app. Accept apology
