### ISSUE TITLE
Delivery Note -> Make Sales Invoice & Sales Invoice -> Get Items From Delivery Note - different functionality

### ISSUE THREAD

**Issue by casesolved-co-uk** [frappe/erpnext#33209]
### Information about bug

There are two ways to create a Sales Invoice from a Delivery Note:

Operations:
1. Delivery Note -> Make Sales Invoice
2. Sales Invoice -> Get Items From Delivery Note

Different functionality:
1. Item prices are reset to the price list rate
2. Item prices are copied from the delivery note

Expected:
Functionality number 2 for both operations

To reproduce:
1. Create a Sales Order with items according to a price list & submit
2. Create a Delivery Note from the Sales Order & submit
3. Change the price list rates
4. Create a Sales Invoice using the two operations above
5. The item rates are different in the invoices

Details:
The code executed on the client side is significantly different for each case. The main thing that stands out is the Sales Invoice button runs a more specific erpnext JS function "erpnext.utils.map_current_doc" which has special functionality for the items table. The delivery note jumps straight to a generic frappe JS function "frappe.model.open_mapped_doc"
The eventual document creation is done by very similar PY functions: frappe.model.mapper.map_docs and frappe.model.mapper.make_mapped_doc

NOTE: this issue most likely applies to an awful lot of similar document mapping functionality

### Module

accounts, stock

### Version

version-11 to version-13 show the same behaviour

### Installation method

None

**Comment by deepeshgarg007** [comment]
@casesolved-co-uk I tried and this seems to be fixed in version 14. Please consider upgrading your sited to version-14 to resolve the issue

**Comment by casesolved-co-uk** [comment]
No significant changes on client or server side on develop branch in the last 3 years.
Tested v14, same problem.
