### ISSUE TITLE
Missing Add Comment feature in Opportunity Doctype

### ISSUE THREAD

**Issue by HnSSiva** [frappe/erpnext#33207]
### Information about bug

On updating the ERPNext to Version 14, the **Add Comment** feature in Opportunity Doctype is missing

### Module

CRM

### Version

Frappe Version -  v14.17.0 (version-14)
ERPNext Version - v14.9.0 (version-14)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
NA
```

**Comment by deepeshgarg007** [comment]
<img width="1348" alt="image" src="https://user-images.githubusercontent.com/42651287/205547691-995d7ce3-dc41-4a06-b78a-9457e16b2a12.png">

@HnSSiva There is a separate tab for comments in the opportunity section hence we have removed the generic comments section. Looks like an invalid issue. Closing this

**Comment by bhaveshmahavar** [comment]
I want that one comment section how can i get that one comment section when we create a manually comment it will show in records.

**Comment by shivangag** [comment]
@deepeshgarg007 Can anyone from frappe team let us know why the generic comments section, which is so fundamental to frappe framework, has been hidden in favor of CRM Notes(named unnecessarily IMHO as Comments instead of Notes)?
This kind of change breaks the uniformity of ERPNext and Frappe, on which other teams heavily depend for their customization and extensions.

**Comment by mustakimgodil** [comment]
Work Around Solution:
Extend  "erpnext.crm.Opportunity" and rewrite your own refresh function removing "this.show_activities()".

Add hook to extend doctype js of opportunity in your own custom app.

![image](https://user-images.githubusercontent.com/109956567/218095125-e5e653f5-1cea-4ed1-8c09-24b888795660.png)

![image](https://user-images.githubusercontent.com/109956567/218095181-4662b00d-cd99-47af-af39-a38aa531485e.png)
