### ISSUE TITLE
Bank Reconciliation Tool not finding payment entry

### ISSUE THREAD

**Issue by Suprazz** [frappe/erpnext#33229]
### Information about bug

When importing bank statement, reconciling debit transaction dont work. System can't find the transaction even if they are there...
![image](https://user-images.githubusercontent.com/3640711/205789799-272ce821-129d-47d5-bb53-95857610f2ab.png)

![image](https://user-images.githubusercontent.com/3640711/205789880-8f632bb7-0d58-4a6e-a560-476541ecf7f0.png)
If I go to Bank Transaction List and select this transaction and manually type the Payment Entry number, it allocate the amount and reconcile the transaction...
![image](https://user-images.githubusercontent.com/3640711/205790161-30ef87c1-e6c8-4e57-ac11-d657c751e9aa.png)

### Module

accounts

### Version

ERPNext: v14.9.0 (version-14)
Frappe Framework: v14.17.1 (version-14)

### Installation method

None

**Comment by deepeshgarg007** [comment]
@Suprazz Please mention some more details about the transactions with the use case and steps to replicate and then reopen the issue
