### ISSUE TITLE
charts.erpnext.com is 404

### ISSUE THREAD

**Issue by mehmetalianil** [frappe/erpnext#33241]
### Information about bug

Well, if you go into charts.erpnext.com, it is 404. 
Couldn't find the decision or issue to close it. 

### Module

accounts

### Version

ALL
ALL

### Installation method

None

**Comment by deepeshgarg007** [comment]
@mehmetalianil This is not being maintained anymore. In case you wish to contribute any country-specific COA you can raise a PR directly
