### ISSUE TITLE
Gross and Net Profit Report Calculations are wrong

### ISSUE THREAD

**Issue by maveezmh** [frappe/erpnext#33249]
### Information about bug

the gross and net profit is not calculating properly in the report

in the expense head it is taking overall expenses as total instead of selected ledgers

Gross Profit/Loss =(Revenue-COGS) 
Net Profit/Loss = (Revenue-Expenses)

![Screenshot 2022-12-07 at 13-33-58 Gross and Net Profit Report](https://user-images.githubusercontent.com/112148467/206144161-c2e3aed6-56e1-494e-aa46-45b26d92fc51.png)

### Module

accounts

### Version

ERPNext: v14.9.0 (HEAD)

Frappe Framework: v14.17.1 (HEAD)

Frappe HR: v1.0.0 (HEAD)

Payments: v0.0.1 (HEAD)

Also in V13

### Installation method

FrappeCloud

**Comment by thida-bcn** [comment]
check "include in gross" flag at COA


![image](https://user-images.githubusercontent.com/62122640/206168580-b0510aef-e1e8-492c-9d96-5417d77ed58c.png)

please make sure all child account must have same value "include in gross"

**Comment by maveezmh** [comment]
@thida-bcn i have only set of accounts tobe in Gross Profit. but the sysem is taking whole Expense Head and showing Wrong Gross profit and loss. 

Below are the accounts i assigned for gross profit

![image](https://user-images.githubusercontent.com/112148467/206835028-f8cb8da8-889c-4b95-9ba7-1ef560ea2461.png)

Below is the GP and NP report at parent level

![Screenshot 2022-12-10 at 10-07-12 Gross and Net Profit Report](https://user-images.githubusercontent.com/112148467/206835004-e4dc5f6e-6edf-47c3-88ef-6bbefbd23f4f.png)

**Comment by thida-bcn** [comment]
even you assign a child item, the system will show all items under same
group you can create a  new group and move that child to new group
Thanks and Regards,
Thida
Business Development Director

Business Centric Network Company Limited
+959 977 160 671
+959 254 677 192
***@***.***
https://businesscentricnetwork.com/

**Comment by maveezmh** [comment]
@thida-bcn 

Gross Profit shouldn't show all the other expenses. it should only show the ledgers for which gross profit check box is enabled.

**Comment by maveezmh** [comment]
Any Update on Gross Profit?

**Comment by maveezmh** [comment]
Any Update?

**Comment by maveezmh** [comment]
@deepeshgarg007 @dj12djdjs  the report is working fine in V14. can we please backport it to V13?

**Comment by maveezmh** [comment]
Looks good
