### ISSUE TITLE
customer list

### ISSUE THREAD

**Issue by stenbjorsell** [frappe/erpnext#3324]
Made this report: http://erp.shipcircuits.com/desk#Report/Customer/Cust%20List

If wish to add email as in recipient to the fields.
When anything (so far) with (communication) in name field  is selected nothing is listed.
How can I rectify this?
Regards Sten

**Comment by rmehta** [comment]
Sorry not able to get your question.

Seems like a standard report, you might have to make a query report to join tables:

https://kb.frappe.io/kb/reports/how-to-make-query-report
