### ISSUE TITLE
Point of Sales : Pricing Rule Discount other Item

### ISSUE THREAD

**Issue by thida-bcn** [frappe/erpnext#33277]
### Information about bug

1) Pricing Rule
when buy an item1, we will give a 
discount on item2
![image](https://user-images.githubusercontent.com/62122640/206600381-e5f99398-3ef4-44be-92f8-8a659c38a6d5.png)
2) Point of Sales
![image](https://user-images.githubusercontent.com/62122640/206600434-18ce1f99-981d-4eb0-ada7-f1344e855bf4.png)
system didn't allow us to save
![image](https://user-images.githubusercontent.com/62122640/206606810-78f34d41-78b0-4adc-810a-4e1fd1dddf9d.png)

### Module

selling

### Version

erpnext 13.41.1
frappe 13.43.2

### Installation method

manual install

**Comment by thida-bcn** [comment]
it was working with V14 now
V13 still having problem

**Comment by Nihantra-Patel** [comment]
**We no longer provide support for version 13 or older.**

Kindly upgrade to version 14 or 15.

Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!
