### ISSUE TITLE
Unable to setup company "Please specify currency in Company"

### ISSUE THREAD

**Issue by niekvb** [frappe/erpnext#33280]
### Information about bug

Tried to create a (first) new company after a fresh install and got the error message below:

![image](https://user-images.githubusercontent.com/37668320/206643347-f7fc8fa8-0f0d-4f2d-b3ed-004f8ea018a5.png)

### Module

other

### Version

ERPNext: v14.10.0
Frappe Framework: v14.18.1

### Installation method

docker

**Comment by dj12djdjs** [comment]
@niekvb I wasn't able to replicate this. Can you let me know if this is still an issue?

If so, could you please provide all the values used to attempt creating the company? 

Thanks!

**Comment by niekvb** [comment]
@dj12djdjs I just entered the bare minimum to create a company. You can see that a currency was selected (clicked from the dropdown menu) in the screenshot. But it would still not recognize the selected option.

I didn't go through with the deployment of ERPNext as I ran into more issues, some of the same kind. So I'll close this, thanks for responding though
