### ISSUE TITLE
amount adding issue

### ISSUE THREAD

**Issue by Daffygroup** [frappe/erpnext#33292]
### Information about bug

we are facing issue for amount adding 

![error ](https://user-images.githubusercontent.com/120366779/206994818-3b554587-0ad9-47a8-a724-d7a88c73ec30.png)

### Module

stock, manufacturing

### Version

ERPNext: v13.42.1 (HEAD)

ERPNext Support: v0.2.1 (HEAD)

Frappe Framework: v13.45.0 (HEAD)

### Installation method

None

**Comment by s-aga-r** [comment]
@Daffygroup please provide us with the steps to replicate the issue.
