### ISSUE TITLE
Dear Sir,  Many issues are facing in ERP as below,  1- In PPRF amount adding issue 2- In Quality inspection releasing issue 3- Material dispensing tag issue. 4- At the time of Purchase receipt GRN No. skipping issue 5- Amount mention in Quality Intimation Slip  6- Discount amount & % mention on Supplier Quotation 7- Required qty. is coming on Stock quantity. 8- Many time not data save 

### ISSUE THREAD

**Issue by Daffygroup** [frappe/erpnext#33293]
### Information about bug

![image](https://user-images.githubusercontent.com/120366779/206995573-bbea0109-0461-4f73-8376-e4a46f70ffd4.png)
![image](https://user-images.githubusercontent.com/120366779/206995603-5b0be81b-db63-4cad-b525-ea1a5e3a69d7.png)
![image](https://user-images.githubusercontent.com/120366779/206995618-783f251d-7563-46af-9dd7-f0210c7422fb.png)

### Module

stock, buying, selling, manufacturing

### Version

ERPNext: v13.42.1 (HEAD)

ERPNext Support: v0.2.1 (HEAD)

Frappe Framework: v13.45.0 (HEAD)

### Installation method

None

**Comment by nabinhait** [comment]
Can you please create a separate issue record for each issue? It will be helpful for tracking the status of each issue. Closing this issue.
