### ISSUE TITLE
Discount amount & % mention on Supplier Quotation

### ISSUE THREAD

**Issue by Daffygroup** [frappe/erpnext#33297]
### Information about bug

Discount amount & % mention on Supplier Quotation

### Module

stock, buying, manufacturing

### Version

ERPNext: v13.42.1 (HEAD)

ERPNext Support: v0.2.1 (HEAD)

Frappe Framework: v13.45.0 (HEAD)

### Installation method

None

**Comment by s-aga-r** [comment]
@Daffygroup could you please add screenshots of the issue so that we can understand it better?
