### ISSUE TITLE
Sales Person - Unable to save doctype

### ISSUE THREAD

**Issue by justinlusg** [frappe/erpnext#3329]
ERPNext > Selling > Sales Person

After I created a sales person, I click on the 'edit' to enter further details such as sales target. But whenever I tries to save I will receive the error for example,

Another sales person with the same employee id exists.
Sales Person Kelvin Lee already exists

**Comment by nabinhait** [comment]
Fixed via https://github.com/nabinhait/erpnext/commit/e2787cf2ec1855c84d0f571132a6092451a20278
