### ISSUE TITLE
Restaurant Order Entry Duplicatted Item Insert

### ISSUE THREAD

**Issue by BOB1212121** [frappe/erpnext#33302]
### Information about bug

In Resturant Order Entry There is A Bug Which appeared in items section
workflow:
1-choose table
2- choose Item
3- Press Enter
The item added two times in two rows

### Module

other

### Version

Frappe Version: 13
ERPNext Version: 13

### Installation method

None

**Comment by dj12djdjs** [comment]
Does it makes sense to transfer this issue to https://github.com/frappe/hospitality.
The fix there should get backported to version-13 here?

CC: @deepeshgarg007
