### ISSUE TITLE
Redirect Portal Page to "Accounts" after login

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#3330]
after logging in as a customer, the browser is not redirected to the ...erpnext.com/me page unless I reload the page, so it looks like it's stuck. It should be straightforward to fix it.

**Comment by KanchanChauhan** [comment]
Tested it on Chrome, Mozilla and Safari, it takes to "Accounts" webpage immediately after login. May be someone fixed it.

**Comment by Simranjeet7860** [comment]
I want that if a user has desk permission then after login he redirects to /me. Any suggestions for this.
