### ISSUE TITLE
Accounting Dimension Sales Invoice Error

### ISSUE THREAD

**Issue by hassan-youssef** [frappe/erpnext#33308]
### Information about bug

When creating an Accounting Dimension for Sales Invoice, when making any transaction and choosing the Dimension, the following message appears
Invalid date
%% is not a valid date string.
https://ckeditor.com/apps/ckfinder/userfiles/files/Screenshot%202022-12-12%20204645.jpg

### Module

accounts

### Version

ERPNext: v14.10.0 (version-14)

Frappe Framework: v14.18.0 (version-14)

Frappe HR: v1.0.0 (develop)

Payments: v0.0.1 (develop)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
Invalid date
%% is not a valid date string.
```

**Comment by dj12djdjs** [comment]
@hassan-youssef The screenshot you shared is getting Does not Exist error. 

What was the value of the accounting dimension you tried to create?

**Comment by hassan-youssef** [comment]
@dj12djdjs  Accounting Dimension Sales Invoice All invoices must be shown But when you click on it to show all bills, the following message appears
Invalid date
%% is not a valid date string.

**Comment by hassan-youssef** [comment]
@dj12djdjs  Accounting Dimension Sales Invoice All invoices must be shown But when you click on it to show all bills, the following message appears

@dj12djdjs  Accounting Dimension Sales Invoice All invoices must be shown But when you click on it to show all bills, the following message appears
Invalid date
%% is not a valid date string.

**Comment by dj12djdjs** [comment]
@hassan-youssef I'm not able to reproduce.
Please see attached screen capture.
![sales-invoice-accounting-dimen-test](https://user-images.githubusercontent.com/29856401/207737192-b88ebd6b-bdbb-40d0-bc0a-cbc0a755ab70.gif)

Please add additional information to reproduce the error message.
