### ISSUE TITLE
Inconsistent form display

### ISSUE THREAD

**Issue by shirleymayadewi** [frappe/erpnext#33324]
### Information about bug

Display inconsistency shows up for Purchase Invoices made from suppliers with US$. How to replicate: 
a. Go to Purchase Invoice 
b. Open a PI. 
c. Select and edit an item there. You will see one of the three versions of the displays. On the left side, the Rate will be displayed as: 1. Rate (CAD) -> but the number is actually in USD, 2. Rate (USD), or just Rate. See the screenshots below showing different display for the exact same Purchase Invoice, depending on when you open the item. 
![Incorrect_display](https://user-images.githubusercontent.com/99818612/207453662-484a8bc9-7441-400e-bffc-879e0fccfa65.png)
![Correct_display1](https://user-images.githubusercontent.com/99818612/207453667-dc81e005-493b-46dc-a311-936b9840df1e.jpg)

 

### Module

buying

### Version

ERPNext: v13.34.1 (development)

Frappe Framework: v13.33.1 (development)

### Installation method

None

**Comment by deepeshgarg007** [comment]
@shirleymayadewi This is working fine for me. Please add more details to replicate and reopen the ticket

<img width="1353" alt="image" src="https://user-images.githubusercontent.com/42651287/207631297-9a5ca011-12d6-4acc-80d4-8b3e4c25f08b.png">

**Comment by shirleymayadewi** [comment]
How many times did you open it? Every time I open it, I got a different display. Can you please open your Purchase Invoice 10 times and let me know if you always receive the same results? Because I do not.
