### ISSUE TITLE
Dates are entered by default in Hold Invoice and Subscription form

### ISSUE THREAD

**Issue by unidow** [frappe/erpnext#33326]
### Information about bug

Date in Hold Invoice field or Subscription field and even other relevant fields where user input is required are entered by system by default. User can't remove the dates in those fields and form application is throwing error message especially in Hold Invoice field which is not open by user and date is entered by system. User has to complete the checkbox to put a future date so that invoice can be submitted. 

### Module

accounts

### Version

ERPNext: v13.42.3 (HEAD)
Frappe Framework: v13.45.3 (HEAD)

### Installation method

None

**Comment by dj12djdjs** [comment]
@unidow Can you provide a set of detailed steps to reproduce? I don't know which form you're in. I checked the Subscription form. I didn't see any field called "Hold Invoice".

**Comment by unidow** [comment]
![Screenshot 2022-12-15 at 6 47 19 AM](https://user-images.githubusercontent.com/28171912/207749580-b1d1f484-9091-4274-8fdd-99361f1625e3.png)
![Screenshot 2022-12-15 at 6 47 55 AM](https://user-images.githubusercontent.com/28171912/207749665-80de43dd-8633-4aff-a424-d1a30b61f6d5.png)
![Screenshot 2022-12-15 at 6 48 35 AM](https://user-images.githubusercontent.com/28171912/207749720-f890f69b-136d-41c8-b226-581b426a39d8.png)
![Screenshot 2022-12-15 at 6 49 56 AM](https://user-images.githubusercontent.com/28171912/207749904-454f8522-57ca-4203-abea-700cf680f11e.png)

I have attached all screenshots related to "Hold Invoice" option/form. Dates are there by default and have to complete a checkbox to put a future date and then undo the checkbox to remove hold to ensure invoice is paid. Similarly, from and to dates in subscription are already there and it automatically comes in when we remove it. All this started happening since a month now.

Also, while we get invoice details from PO, the form is filtered by current date and we have to remove it to see all open POs available for billing. Kindly check all date fields. They are causing a lot of trouble while booking invoices.

**Comment by dj12djdjs** [comment]
@unidow I just tested from fresh installation, the dates in subscription and hold invoice are not automatically filled in by the system. They require user to fill in.

Please see attached screen capture.
![dates-not-autofill](https://user-images.githubusercontent.com/29856401/207754210-1fc1510d-ac24-4654-b274-e77a5f386f8b.gif)

Please let me know if there is any additional information to reproduce the bug you described.
