### ISSUE TITLE
Speeding-up filling of BOM/Estimates

### ISSUE THREAD

**Issue by Jaliya** [frappe/erpnext#3332]
I suggest implementing following things will speed -up making BOMs/Estimates:
1. A project may contain 1 job or several jobs. Therefor suggest to implement a BOM tree. Example:
   ......Project 1
   ..........Job 1
   ..................BOM 1.1
   ..................BOM 1.2
   ..........Job 2
    ..................BOM 2.1
     .................BOM 2.2
   This will contain all the BOMs of a project under th project heading in one place.

2.Items/Raw Materials should be able to tag to Items or parts of items being manufactured/assembled.
This will enable  the raw materials tagged to a particular manufactured item to be seen together in a screen, when that manufactured item is selected. A raw maerial should be abeled to tag to many items being manufactured.
As an example from Sign Industry:
An illuminated sign is an assembly of sub-assemblies and items.

...Signboard
........Internal Steel Frame
..............GI Box Bar 1"x1"x1,2mm
..............Hacksaw Blade
..............Welding Rods
........Sheet Metal Casing
........Wired Electrical Components
........Sign substrate & Graphics
........Signposts or Sign Brackets
..............GI Box Bar 1"x1"x1,2mm
..............Bolts & Nuts 1"x1/4"

So when I selected "Internal Steel Frame" the raw material list should shaw only the raw material tagged to ths sub-assembly. Then I can tik required items in sizes we require and send it to the BOM list. When you send raw materials to BOM, raw materials should fetch there prices also automatically. I have to repeat this for all the sub-assembles mentioned above. Only after compleating that I will start inserting the Quantities of those materials in the BOM sheet.

In this example GI Box Bar 1"x1"x1,2mm will be visible in the screen for "Internal Steel Frame" as well as for "Signposts or Sign Brackets" as this item is tagged against both those sub-assemblies.

This will definitely speed up inserting items to BOM.
1. In the BOM I suggest to have operations in the same raw as the material by which that material assembled to the final product. That will reduce the possibilities of forgetting to include an operation.
2. Now.BOM shows only the cost and we have to calculate price on our own to insert into the QUOTATION. I suggest to include a section below the BOM for working out the prices. It is better if we can use different mark-ups for MATRIALS, LABOUR, OUTSOURCED SERVICES. 
3. It is good, if we can use the same BOM tree format mentioned in Point 1 above, in the QUOTATION format too.

**Comment by Jaliya** [comment]
I had the followwing in the start of the above suggestion as a tree but formatting have changed it. Appreciate if you could correct.
...........................................................Project 1 
.....................................................................Job 1
........................................................... ..................BOM 1.1 
..............................................................................BOM 1.2 
.....................................................................Job 2 
.............................................................................BOM 2.1 
.............................................................................BOM 2.2

**Comment by rmehta** [comment]
@Jaliya thanks for your feedback. What I see is this:

1. Ability to define a BOM Tree in one screen
2. Link pricing to BOM
3. BOM to Quotation?

**Comment by Jaliya** [comment]
Yes you are correct.

 

When you reconsider Quotations, please provide an alternative way to make quotations without Total Price. This is due to the fact that in many occations we have to quote for 2 or more options  for one product requirement. Then there is no logic in giving the total price. Even the present reports of total  value of submitted quotations get distorted.

 

With version 5 and introduction of “add multiple rows” in BOM, the speed of selecting raw materials have speeded-up quite impressively. But  my suggestion for grouping of raw materials as per usage in work stations or according to another criteria still stands. It will make selection of required material at a glance within one screen. (You may have to provide a way to tik the material we select). It should facilitate selecting all the material first and then inserting quantities later. (This will facilitate selecting the items even while you are in a telephone conversation and filling the quantities in a more concentrated manner later referring to diagrams and using calculations etc.). Even under present system of adding multiple raws, it will be helpful if we can fill the quantities of all selected items later.
