### ISSUE TITLE
Trial Balance and other reports are not working

### ISSUE THREAD

**Issue by unidow** [frappe/erpnext#33325]
### Information about bug

While trying to open Trial Balance or Sales Register, the whole application is not responding and unable to access critical reports for the last three weeks.

### Module

accounts

### Version

Frappe Framework: v13.45.3 (HEAD)
ERPNext: v13.42.3 (HEAD)

### Installation method

None

**Comment by deepeshgarg007** [comment]
@unidow Please add screenshot of the issues and explain them and reopen

**Comment by unidow** [comment]
![Screenshot 2022-12-14 at 10 16 30 PM](https://user-images.githubusercontent.com/28171912/207656448-b77a0069-1dd6-421e-b98b-56a096cd4449.png)

**Comment by unidow** [comment]
This is the challenge we are facing for the last few days. Same goes with Sales register especially when it was required for GST return.
