### ISSUE TITLE
POS Closing is not working properly

### ISSUE THREAD

**Issue by thida-bcn** [frappe/erpnext#33337]
### Information about bug

1) Define Pricing Rule
Min Amount 100,000, will get 2% Discount
![image](https://user-images.githubusercontent.com/62122640/207586980-93a6ebb7-b5a9-4790-b5ba-1c7e3a6b3cf0.png)

2) Go to Retail and Create POS which amount is more than 100,000
![image](https://user-images.githubusercontent.com/62122640/207587309-d7225df9-8ccf-4508-9593-c188a801a560.png)
3) Close Shift
you will get below message and can't do Close Shift
![image](https://user-images.githubusercontent.com/62122640/207587711-a21e14a0-d712-4ee1-bd33-a79844052eeb.png)

PS/
I can do close shift without discount
![image](https://user-images.githubusercontent.com/62122640/207587615-f831ef06-3dcf-477c-8516-22f0e765fe85.png)

### Module

other

### Version

ERPNext: v14.10.0 (version-14)

Frappe Framework: v14.18.1 (version-14)

ERPNext: v13.41.1 (version-13)

Frappe Framework: v13.43.2 (version-13)

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
Hi @thida-bcn,

Everything is working fine. No problems were encountered in version 14. Kindly upgrade to version 14 or 15, then refresh and check again.


https://github.com/frappe/erpnext/assets/141945075/215bb9f5-b683-470e-91fc-9e14337e434f


If the issue occurs then please create/reopen an issue according to version (14 or 15) with video documentation.

Thank You!
