### ISSUE TITLE
Unable rearrange app inside Chrome

### ISSUE THREAD

**Issue by justinlusg** [frappe/erpnext#3333]
Hi there, I'm using Chrome Version 43.0.2357.65 m and i'm unable to re-arrange the app. I used to be able to do so in v4, but after moving to v5 I'm unable to do so anymore. However, I use am able to rearrange in IE and Firefox, it's just inside Chrome I lost the ability to do so.

**Comment by rmehta** [comment]
I am able to. Can you see any trace in your console?

**Comment by justinlusg** [comment]
There is no error in the console. It does not work for a few of our other colleagues as well. When we click and hold the mouse on any of the app, it highlights them instead. 

![image](https://cloud.githubusercontent.com/assets/12539216/7814982/396b08de-03f8-11e5-8165-4b8b68d28249.png)

**Comment by rmehta** [comment]
Do you see the "pointer" icon while dragging? Can't replicate.
