### ISSUE TITLE
Cost center: group cost center can't be used in transaction

### ISSUE THREAD

**Issue by ajiragroup** [frappe/erpnext#33336]
### Information about bug

While Creating Sales Invoice, i selected a cost center (which is not a group cost center), but it gives the error.

![image](https://user-images.githubusercontent.com/108009061/207581314-090ea1bd-55cf-427e-be0d-2307d78a64fd.png)

![image](https://user-images.githubusercontent.com/108009061/207581492-59456419-29ac-4356-bb85-95048e021b6b.png)

![image](https://user-images.githubusercontent.com/108009061/207581563-f4bb92ce-e0e6-4c97-a56a-9df2db0519ee.png)

### Module

selling

### Version

Frappe 14.15.0
Erpenxt 14.7.0

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Sales Invoice ACC-SINV-2022-00023: Cost Center Ajira Builders - AB is a group cost center and group cost centers cannot be used in transactions
```

**Comment by dj12djdjs** [comment]
@ajiragroup I wasn't able to replicate this. Can you double check what the field value of cost center is? It should say "Main - AB" if not. Please try typing "Main - AB".

Let me know if there is still any problems.
