### ISSUE TITLE
Trial Balance and other reports are not working

### ISSUE THREAD

**Issue by unidow** [frappe/erpnext#33345]
### Information about bug

While trying to open Trial Balance or Sales Register, the whole application is not responding and unable to access critical reports for finalising Financials or Statutory returns like GSTR 1 or GSTR 3B. 
![207656448-b77a0069-1dd6-421e-b98b-56a096cd4449](https://user-images.githubusercontent.com/28171912/207751013-8149ca48-075d-4bed-9a56-ea91fadefea0.png)

### Module

accounts

### Version

Frappe Framework: v13.45.3 (HEAD)
ERPNext: v13.42.3 (HEAD)

### Installation method

FrappeCloud

**Comment by dj12djdjs** [comment]
Interesting... Let's see if I can try to reproduce this...

What is the total number of accounts assigned to the company that the report is loading?

**Comment by unidow** [comment]
there are around 150 accounts. There was no problem in the last five years. but now suddenly it stopped working. I think frappe want us to migrate to ERP Next. Same goes for dates issue which is in different thread.

**Comment by deepeshgarg007** [comment]
@unidow This seems something specific to your account and not a core issue. All reports working fine for us. Closing this ticket
