### ISSUE TITLE
 In PPRF amount adding issue

### ISSUE THREAD

**Issue by Daffygroup** [frappe/erpnext#33352]
### Information about bug

![image](https://user-images.githubusercontent.com/120366779/207839523-19b1c0ec-40ed-4418-8667-74167e5c6609.png)

### Module

stock, selling, manufacturing

### Version

ERPNext: v13.42.3 (HEAD)

ERPNext Support: v0.2.1 (HEAD)

Frappe Framework: v13.45.3 (HEAD)

### Installation method

None

**Comment by rohitwaghchaure** [comment]
@Daffygroup Kindly save the stock entry and you can see the value in the fields amount and basic amount

**Comment by Daffygroup** [comment]
still issue same.
