### ISSUE TITLE
Location: Incorrect location mapped in Map View 

### ISSUE THREAD

**Issue by gavindsouza** [frappe/erpnext#33363]
Location Doctype has 3 Issues:
* Lattitude and Longitude don't correspond to the location in the map as seen below when auto set by browser location on 1st save.
* On changing the Lat/Lng in the form and saving again, the map still shows the location from the browser and not the coordinates on the saved document if the browser has location permission for the site.
* If the browser has location disabled, the map shows the vicinity but no map marker for the coordinates.

---

Map Location fetched automatically from browser:

![XKSDFye](https://user-images.githubusercontent.com/36654812/118116077-6f4cb180-b407-11eb-826e-48b9474e0e9b.png)

After Save Lattitude and Longitude shown:

![Fzq8adE](https://user-images.githubusercontent.com/36654812/118116047-678d0d00-b407-11eb-87e1-e81320f13a6b.png)

On Checking on OSM (which is used):

![nCZUg5x](https://user-images.githubusercontent.com/36654812/118116071-6d82ee00-b407-11eb-98c8-146ad3999890.png)

On changing the latitude value from 19.071 to 21.071 if the browser location is not blocked, notice the saved document:

![m2hXNMO](https://user-images.githubusercontent.com/36654812/118116068-6c51c100-b407-11eb-81f4-0acc885a731e.png)

But if the location is disabled, the map points to the vicinity but without a map location marker:

![onlCIe7](https://user-images.githubusercontent.com/36654812/118116075-6eb41b00-b407-11eb-95af-1940ad608832.png)

**Comment by ankush** [comment]
Apparantly it's not a bug. Leaflet uses lat-long.

https://gis.stackexchange.com/questions/244651/leafletgeojson-why-are-lat-lng-coordinates-in-the-wrong-order

Documented this behavior in docs.

**Comment by ankush** [comment]
Wait, maybe this one still is cause location doctype misinterprets it too? :woozy_face:

**Comment by ankush** [comment]
for some reason this seems correct now :woozy_face: 

![image](https://user-images.githubusercontent.com/9079960/207881901-50ae0cc4-50a6-49d7-97ca-7f050c2b2fe1.png)


how? idk at least the code "looks" correct.
