### ISSUE TITLE
Customer - Primary Contact Details Quick Entry Email Id & Mobile No disabled suddenly

### ISSUE THREAD

**Issue by maxchock** [frappe/erpnext#33361]
### Information about bug

![image](https://user-images.githubusercontent.com/59406510/207866398-15de5c68-b82b-4467-8abb-3f34e97fe6f6.png)

Been using ERPNEXT 13 for many months without issue. Suddenly the "Email Id & Mobile No" at Customer - Primary Contact Details Quick Entry page has disabled, previously that 2 field can just key in TEXT, but now it cannot enter anything, seems disabled.

### Module

selling, CRM

### Version

Frappe 13.45.3
ERPNEXT 13.42.3

### Installation method

FrappeCloud

**Comment by maxfu9** [comment]
It is also not working on version 14.10.1
