### ISSUE TITLE
Wrong Accounts Currency when adding new row

### ISSUE THREAD

**Issue by danjeremynavarro** [frappe/erpnext#33388]
### Information about bug

First create a new journal entry with Multi-Currency checked

Add a new row for an account with a currency that is different from the default
![image](https://user-images.githubusercontent.com/46537526/208539823-3baf357c-05a4-4a3e-8541-d0541c084a64.png)

Click on Add Row
![image](https://user-images.githubusercontent.com/46537526/208539548-6a77ec06-f988-4325-932d-f9712ef56019.png)

The currency on the added row is different from the actual currency the added row currency should be what the actual currency of the account s

### Module

accounts

### Version

ERPNext: v13.42.3
Frappe Framework: v13.45.3

### Installation method

None

**Comment by dj12djdjs** [comment]
Appears to be working correctly in latest version.

![grid currency](https://user-images.githubusercontent.com/29856401/229181520-dd4175ee-452a-432b-aef3-783817be4fbd.gif)
