### ISSUE TITLE
Stock in BOM is fetched when updating finished goods, not from stock entries

### ISSUE THREAD

**Issue by asr17** [frappe/erpnext#3340]
Actual Stock Issued is not Carried over during Update finished Goods
Stock in BOM is fetched when updating finished goods, not from stock entries

The scenario is stock is issued at different times for production order
not all stock is issued at once 
so I made 2 different stock entries on same production order and noticed when i click update finished goods, the items were fetched from BOM , not from stock entries to that production order

In BOM of Table
GLUE-ICI is 2 Kg

but during stock issuance, it was actually used 2.5 kg, **in 2 different stock enteries**
Both linked to same production order

**when i press update finished goods, it only shows 2kg as per BOM, not 2.5 Kg which is actually issued**
see pic

**BOM Table**
-------------

https://www.dropbox.com/s/9jitjpr6x3fw7v6/bom%20table.jpg?dl=0

**Stock Entry 1**
-----------------

https://www.dropbox.com/s/yit36tffsoqinjn/table%20Stock%20Entry%201.jpg?dl=0

**Stock Entry 2.**
------------------

https://www.dropbox.com/s/1ic33wdn3d3b2x5/table%20Stock%20Entry%202.jpg?dl=0

**Finished Item**
-----------------

https://www.dropbox.com/s/7n57aihq9dspnpn/Table%20Finished.jpg?dl=0

**Comment by neilLasrado** [comment]
Yes this is an intended feature. Stock Entries take values from the BOM specified in the production order.
You should ideally transfer raw materials of same qty as mentioned in the BOM. 
check out 'Transferring Materials for Manufacturing' section at https://manual.erpnext.com/contents/manufacturing/production-order for details.
If you have manually changed the quantity of Raw Materials you need to do so manually while making a Finished Goods Stock Entry.
You can also change the BOM to keep the stock accurate.
Do let me know your use case if this model is not suitable for you.

**Comment by rmehta** [comment]
@asr17 the reason is you may already have material while starting to manufacture, hence may release less / more material from store.

Backflush, should be consistent with BOM.

**Comment by asr17** [comment]
@rmehta Please See the screen shots .... I did not understand your point
I tried several examples and then i posted here ... with a fresh example and simplified to elaborate this issue

@neilLasrado Sir the issue is WE can not estimate accurately how much a raw material will be consumed in **engineer-to-order**
I had a chat with your representative in version 4 and he said BOM can not be Changed once its Submitted ...

We Make Customized Furniture ... So We can **Not** know how much a raw material will be consumed, we can only make estimates and actual quantity is known through stock entries to that production order  ...
So we need Raw material to be fetched from Productions orders not from BOM
How can you help me with tha? THX

**Comment by rmehta** [comment]
You can always manually edit items against Production Order.

Maybe we should have this as a setting in the Production Order, so that you can choose to validate the "Manufacture" entry against BOM or not.

**Comment by asr17** [comment]
Yes , But therer are so many raw materials , and reconciling is an issue,
ERP feature should be helping in minimizing work and maximizing efficiency,
So Kindly Add this feature as its an issue,that more other people will complaint about later

**Comment by inventobd** [comment]
I need to calculate my production cost by deducting damaged quantity. But production process calculates production cost for each item from boom not from production order or finished goods quantity. This feature is very important .

**Comment by soloincc** [comment]
I can see that @nabinhait closed this issue. Was @inventobd feature implemented?
