### ISSUE TITLE
Unable to get the Supplier Name and Purchase Order in Stock Entry of Type Send To Subcontractor

### ISSUE THREAD

**Issue by ram-chandu** [frappe/erpnext#33417]
Hi Team,

Facing the following issue in V14 instance:

While creating a stock entry of type send to subcontract from subcontracting order the supplier name and purchase order number details are not getting copied over from the subcontract order to stock entry. Please check.

Steps to replicate:
1. Go to the Purchase order created from Production plan(https://v14-test-rcil.frappe.cloud/app/purchase-order/PO%2FFY22%2Fbranch_abbr0043).
2. Then click on create and create a subcontracting order(https://v14-test-rcil.frappe.cloud/app/subcontracting-order/SC-ORD-2022-00012).
3. Once the subcontracting order is created, click on the transfer button and clink on material to supplier.
4. Then a stock entry of type send to subcontract is created(https://v14-test-rcil.frappe.cloud/app/stock-entry/MI%2FFY22%2FBK3205). 

Observation:
1. Here we are Unable to get the Supplier Name and Purchase Order details copied over in Stock Entry.

Expectation:
1. The Supplier Name and Purchase Order details need to be shown in Stock Entry

Attaching the screenshots for your reference. 
![Screenshot from 2022-12-22 10-34-19](https://user-images.githubusercontent.com/119317369/209061063-cb0d3062-5f2f-4afa-9f8b-a53dd671bbc2.png)

In stock entry:
![Screenshot from 2022-12-22 10-35-05](https://user-images.githubusercontent.com/119317369/209061117-62642173-6256-4fbb-a5c4-a17e0ae58e52.png)

Thanks.

**Comment by s-aga-r** [comment]
@ram-chandu 

Purchase Order will not be fetched from Subcontracting Order in the Stock Entry of type Send to Subcontractor. The Purchase Order field and Subcontracting Order field are used to specify for which order you are transferring the Raw Materials. You can only use one of them it can be a Purchase Order(v13) or Subcontracting Order(v14).

For the fields `supplier`, `supplier_name` and `supplier_address` I have added the fix. It will be fetched from Subcontracting Order in the Stock Entry.
