### ISSUE TITLE
Field plc_conversion_rate not found.

### ISSUE THREAD

**Issue by Daffygroup** [frappe/erpnext#33427]
### Information about bug

![image](https://user-images.githubusercontent.com/120366779/209327312-c644e372-4d6c-417e-921d-62cfe6bf2ee3.png)

### Module

stock, buying

### Version

ERPNext: v13.42.3 (HEAD)

ERPNext Support: v0.2.1 (HEAD)

Frappe Framework: v13.45.3 (HEAD)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
Field plc_conversion_rate not found.
```

**Comment by s-aga-r** [comment]
@Daffygroup please share the browser console log.

**Comment by Daffygroup** [comment]
Dear ERP Team,

We are facing the issue in ERP as per below details.



Kindly rectify soon.

[image: image.png]


*Thanks & Warm Regards,*

Satpal R.

Daffy* C*osmetics* P*vt.* L*td.

*Plot No. 11, Sector-3,*

*SIDCUL IIE, Pantnagar -263153*

*UttraKhand.*

Website      :  *www.daffygroup.com* <http://www.daffygroup.com/>
