### ISSUE TITLE
Letter Head Printing in PDF Issue

### ISSUE THREAD

**Issue by davygarg** [frappe/erpnext#33428]
### Information about bug

There is an issue in Quotation printing pdf with letter-head if you have multiple letterheads setup, during pdf preview it shows the correct letterhead but when you click on PDF button to generate PDF, letter-head changes to default letter-head instead of the selected.

### Module

buying

### Version

ERPNext: v14.11.0 (version-14)
Frappe Framework: v14.20.0 (version-14)

### Installation method

None

**Comment by ghost** [comment]
@davygarg What browser were you using when you encountered the issue? - [Clerkie](https://bit.ly/clerkie_ai)

**Comment by amrishshah** [comment]
Same issue.. i am using chrome

**Comment by davygarg** [comment]
I was using Firefox, however i was using multiple letterheads but now switched to single letter head and issue is gone.

**Comment by amrishshah** [comment]
I have updated ERPNext and restart the service. it is working now.

**Comment by iashaik** [comment]
I have the same issue, I also have multiple letterheads but I can't delete older latter heads since they are connected to old invoices etc. 

I tried disabling all of them except one. Still have issues.

**Comment by Nihantra-Patel** [comment]
Kindly upgrade to version 14 or 15, everything is working fine. No problems were encountered in the latest versions 14 and 15.
