### ISSUE TITLE
Can't access All Products page (/all-products)

### ISSUE THREAD

**Issue by QHD-sp** [frappe/erpnext#33421]
### Information about bug

1. Go to All Products page (/all-products)
2. Error

![image](https://user-images.githubusercontent.com/114915243/209271650-2b2a9df4-4307-4056-9ade-5de3b7022319.png)

### Module

ecommerce

### Version

![image](https://user-images.githubusercontent.com/114915243/209271857-60f7a6a1-0e7a-4153-b9bb-dc9c80d32697.png)

### Installation method

None

**Comment by s-aga-r** [comment]
@QHD-sp seems the issue is related to customization(?) somewhere you have set the document type as "abc" instead of "abc ".
