### ISSUE TITLE
Fold cannot be at the end of the form

### ISSUE THREAD

**Issue by adilgandhi** [frappe/erpnext#3343]
I keep getting this error whenever I try to customise a form type and finally nothing moves forward.

Also happened when I tried making the new year as default.

![fy error](https://cloud.githubusercontent.com/assets/12607689/7808727/ee2939f8-03b2-11e5-8741-66eac693bb90.jpg)

**Comment by neilLasrado** [comment]
I am unable to replicate this issue. did you customise the form and add a field of type 'fold' at the end. Please do check this also try replicating the issue at demo.erpnext.com and let us know.

**Comment by adilgandhi** [comment]
hey neilLasrado

No I do not have any field type named FOLD and it seems to appear when trying to customise any form and as you see in the image, when trying to change default FY.

**Comment by adilgandhi** [comment]
could it also be possible that my account has not been upgraded to V5 yet?

**Comment by nabinhait** [comment]
Can you check for position of "Fold" in following doctypes: "Quotation", "Sales Order", "Sales Invoice", "Delivery Note"? In any of these doctypes, "Fold" type field is at the end. Move "Fold" field before any labeled Section Break.

**Comment by adilgandhi** [comment]
Yes Nabin

I managed to change the 'fold' order and it the issue was sorted.
