### ISSUE TITLE
Github showing latest version as 13.42.5

### ISSUE THREAD

**Issue by varunpan** [frappe/erpnext#33438]
Not sure where to point this out but guthub is showing v13.42.5 as the latest versions even though there are releases for v14.11.0 (which seems to be real latest one).

**Comment by SimonFalcon** [comment]
This is due to the way GitHub shows latest releases.
There are several versions mainained of Erpnext.
But if the v13 was the one that got the update the latest GitHub will show it as the "latest release" even though we have v14.
