### ISSUE TITLE
Received quantity not updated in purchase receipt item (when creating purchase receipt from purchase order)

### ISSUE THREAD

**Issue by rayenlabdouni** [frappe/erpnext#33463]
### Information about bug

When i create a purchase receipt from purchase order, after saving the receipt, received quantity in item table don't get updated (picture 1), and we can not create purchase invoice after submitting (picture2)
![image](https://user-images.githubusercontent.com/62704271/209785030-dfd2f523-2eba-4d1f-bad7-75fddbfadafc.png)
![image](https://user-images.githubusercontent.com/62704271/209785075-31067a1d-70a1-4245-8730-e5d1ea0ff53e.png)
 

### Module

accounts, stock

### Version

Frappe Framework: v13.46.2
ERPNext: v13.42.5

### Installation method

FrappeCloud

**Comment by maveezmh** [comment]
Check if there is any customization that is creating this issue

**Comment by s-aga-r** [comment]
@rayenlabdouni The issue is not replicable. Please provide the steps to replicate it and reopen the issue.
