### ISSUE TITLE
Issue in Payment Reconciliation. Unable to Knock off return invoices with Outstanding invoices

### ISSUE THREAD

**Issue by maveezmh** [frappe/erpnext#33462]
### Information about bug

In payment reconciliation user is unble to knock off the return invoices against outstanding invoices. even when you reconcile the outstanding return invoice with normal invoice still the return invoice will be available to reconcile with another invoice.

PS> Working fine for Payment entries. 

basically am able to knock of all the outstanding invoices (for example 10000 AED) of a customer/supplier from single return invoice of 100 AED.

![image](https://user-images.githubusercontent.com/112148467/209768746-77dba01f-9872-4e17-b9d5-2ef54f29d140.png)

IN ABOVE EXAMPLE i can allocate that return invoice of 5000 AED on right side to all the invoices on the left side one by one and still it will be available to reconcile. 

@deepeshgarg007 requesting you to look into the issue as soon as possible. 

probably issue started happening once this hotfix is updated https://github.com/frappe/erpnext/pull/33367/files

### Module

accounts

### Version

ERPNext: v13.42.5 (HEAD)
Frappe Framework: v13.46.1 (HEAD)

### Installation method

FrappeCloud

**Comment by dineshpanchal93** [comment]
Facing the same issue 

https://github.com/frappe/erpnext/issues/33448

**Comment by ruthra-kumar** [comment]
Fixed in https://github.com/frappe/erpnext/pull/33471
