### ISSUE TITLE
Payment Reconciliation Debit Note - Return Invoice are not fetched

### ISSUE THREAD

**Issue by dineshpanchal93** [frappe/erpnext#33479]
### Information about bug

Need to adjust the Purchase Invoice with Return Purchase Invoice - Debit Note 

In Accounts Payable I can see the debit note, Not getting fetch in payment reco to adjust those Debit note with Payable Outstanding Invoices.

@ruthra-kumar @deepeshgarg007  kindly look it into.

![image](https://user-images.githubusercontent.com/21578167/209933145-0a74c06b-262b-436b-a7ff-035c8077c34c.png)

![Debite Note](https://user-images.githubusercontent.com/21578167/209933472-31c54e8a-a0aa-4051-a863-7463cf6465f8.gif)

### Module

accounts

### Version

ERPNext: v13.42.6 (version-13)
Frappe Framework: v13.46.2 (version-13)

### Installation method

manual install

**Comment by ruthra-kumar** [comment]
Should be fixed now
