### ISSUE TITLE
Account Head Message

### ISSUE THREAD

**Issue by thida-bcn** [frappe/erpnext#33485]
### Information about bug

I supposed it was really annoyed for users
Warehouse Setup
There was only Stock Account
![image](https://user-images.githubusercontent.com/62122640/210033975-68c3443c-ef63-4fc9-af49-09e5873681f0.png)
expenses account is not needed when we purchase stock
The message got at purchase invoice
![image](https://user-images.githubusercontent.com/62122640/210033942-7713442f-2935-44da-bf59-98c66dc2c3d1.png)

### Module

buying

### Version

ERPNext: v14.11.1 (version-14)

Frappe Framework: v14.21.0 (version-14)

### Installation method

None

**Comment by deepeshgarg007** [comment]
@thida-bcn This is just a notification for the user because the system auto-changes the account. How is this a bug, not able to understand? Please explain and reopen

**Comment by thida-bcn** [comment]
> @thida-bcn This is just a notification for the user because the system auto-changes the account. How is this a bug, not able to understand? Please explain and reopen

hello Sir,
I have one more question, Cost of Goods Sold is not related with Purchase, why system show above message?
Stock in Hand is not expense account, Stock in Hand is Assets Account
Your message is not relevant and It made annoy to users
thanks
![image](https://user-images.githubusercontent.com/62122640/211515937-0d95adae-6afa-410f-95e9-5316b648b6a6.png)
