### ISSUE TITLE
Wrong Group Filtering in General Ledger ( Version -14 )

### ISSUE THREAD

**Issue by sammish** [frappe/erpnext#33497]
### Information about bug

Hello Frappe Team 

Whenever I Filter Account there is wrong group ledger is showing 

![gl-1](https://user-images.githubusercontent.com/12432802/210168713-b3a01192-e33f-46e8-9702-1d47f37cca2b.png)

![gl-2](https://user-images.githubusercontent.com/12432802/210168725-576aa847-492e-4c9f-a1ad-6e5b7b89f1e7.png)

### Module

accounts

### Version

ERPNext: v14.11.1 (HEAD)

Frappe Framework: v14.21.0 (HEAD)

### Installation method

FrappeCloud

**Comment by ruthra-kumar** [comment]
Couldn't replicate it. 

If you are comfortable using bench console, verify the output of https://github.com/frappe/erpnext/blob/c78399c618ddc81cddba76caa7b8ab5563cc6a4b/erpnext/accounts/report/general_ledger/general_ledger.py#L283 function in general ledger. It should only include the child nodes of "1200 A - SMASH INTL - SHC".

Example:
<img width="836" alt="Screenshot 2023-01-04 at 2 07 20 PM" src="https://user-images.githubusercontent.com/3272205/210515610-52fdc157-a26e-4423-bc9a-d6ccf1bb5846.png">

**Comment by sammish** [comment]
@ruthra-kumar it's not happening all the group some groups only. i really wonder.please evaluate

**Comment by deepeshgarg007** [comment]
@sammish Your lft and rgt values for the Account Tree must have gone incorrect. Please use the following button to rebuild tree and correct

<img width="1359" alt="Screenshot 2023-01-07 at 4 59 16 PM" src="https://user-images.githubusercontent.com/42651287/211148584-b4fd4c3c-dfd0-47db-bf6c-d85670adab53.png">

**Comment by sammish** [comment]
@deepeshgarg007 Really ? Thanks let me try
