### ISSUE TITLE
ERPnext Version 14 > Shopping Cart > Shipping Address > Add a new address - Country field will not form fill

### ISSUE THREAD

**Issue by markareait** [frappe/erpnext#33506]
### Information about bug

ERPnext Version 14 > Shopping Cart > Shipping Address > Add a new address - In the web form the Country field will not form fill from any of the counties in the drop down and ends up with nothing in the field.

Note - Have upgrade the laterest ERPnext 14 with bench update still issue present.  Issue is seen with latest Chrome and Firefox.

### Module

ecommerce

### Version

Frappe Version:  14.21.0
ERPnext version: 14.11.1

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
No error code
```

**Comment by sudhandhiradevi** [comment]
Same issue

**Comment by markareait** [comment]
It is a worry that this major issue that stops the shopping cart from working has not been acknowledged by the dev team after 2 weeks.  Hard for me to feel confident in using ERPnext moving forward...

**Comment by Nihantra-Patel** [comment]
Kindly upgrade to version 14 or 15, then refresh and check again because lots of bugs fixed in the new version.

Everything is working fine. No problems were encountered in the latest versions 14 and 15.


https://github.com/frappe/erpnext/assets/141945075/daa0ee63-74ca-4735-8af1-5128a005a4aa
