### ISSUE TITLE
Multi UOM Barcode is not working for POS

### ISSUE THREAD

**Issue by thida-bcn** [frappe/erpnext#33522]
### Information about bug

Setup Multi UOM Barcode under Item
![image](https://user-images.githubusercontent.com/62122640/210365156-ada71dee-5925-4416-88e7-e4c83416000d.png)
when scan barcode, it's working for Nos(Based UOM)
![image](https://user-images.githubusercontent.com/62122640/210365274-50d81f7e-e784-4894-a463-b33bf66e8322.png)
when scan barcode for Box UOM>> system capture only based UOM
![image](https://user-images.githubusercontent.com/62122640/210365396-b1a091e4-c5f0-4d58-b7f5-9a1024c9898c.png)

### Module

selling, other

### Version

v13.42.7

Retail Module

### Installation method

manual install

**Comment by ankush** [comment]
Ah this was never implemented for POS. As of now it only works on regular transactions which support scanning. It should be easy to implement for POS too 👍

**Comment by ankush** [comment]
Reference

https://github.com/frappe/erpnext/pull/30988

**Comment by ankush** [comment]
Duplicate https://github.com/frappe/erpnext/issues/33649
