### ISSUE TITLE
Bug in Email Standard Reply - text pushes Salutation to bottom of message

### ISSUE THREAD

**Issue by monojoker** [frappe/erpnext#3352]
Guys,

Since v5 or earlier this function has a bug. When you trigger an email you get the following popup with the salutation "Dear [first name] [last name]":

![image](https://cloud.githubusercontent.com/assets/10917366/7827236/604adf2c-0468-11e5-987b-77f6d53b0426.png)

Then when you add a Standard Reply it inserts ABOVE the salutation thus pushing it to the bottom of the message:

![image](https://cloud.githubusercontent.com/assets/10917366/7827310/1b112870-0469-11e5-9f3d-50e97899d6c2.png)

Please fix so users don't have to manually move the salutation each time :) Thanks.

**Comment by monojoker** [comment]
Guys, any update, would have thought this is an easy fix???

**Comment by rmehta** [comment]
Thanks pushed a fix. Will be released with v6 (soon)
