### ISSUE TITLE
[Packaging for distributions] Manual installation without Bench

### ISSUE THREAD

**Issue by Spixmaster** [frappe/erpnext#33539]
I would like to package ERPNext for the [AUR](https://aur.archlinux.org/) so that more people can easily use this great software.

For this, an installation is needed without using Bench. Installing with `python -m build -nw` and `python -m installer /proper/path/dist/*.whl` does not install an executable. Therefore, I tried running every Python file but none of those starts a server.

Could you add an executable or could you tell me which Python file or perhaps method needs to be executed? In the latter case, I could create a pull request for the creation of an executable.

Thank you very much.

**Comment by ankush** [comment]
We have no plans to do this any time soon. In fact our intention is to just stick with Docker. Everything else is messy and difficult to manage for people.

**Comment by Thatoo** [comment]
Well, we just ask for a bit more transparency and flexibility about what bench commands are doing.
For instance how is it that 
`bench new-site $site_name --db-name $db_name --db-password $db_pwd --force --admin-password $admin_pwd`
require mysql root password whereas the database has been done before the bench command?
This sounds unsafe and is an unwanted behavior for such command.

**Comment by Thatoo** [comment]
Well I found at that in new version of ERPnext, v15, there is a --no-setup-db that allow that.
The only problem remaining is that `bench new-site` command check these mysql variables
```
	"character_set_server": "utf8mb4",
	"collation_server": "utf8mb4_unicode_ci",
```
whereas it could be unnecessary if the database is created in advance like that : 
`sudo mysql -u root -e "CREATE DATABASE IF NOT EXISTS $db_name CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"`

We don't need to set character and collation at server level if we do it at database level...
