### ISSUE TITLE
In Internal transfer Delivery note and Purchase Receipt force to use valuation rate as rate but it wont allow it to update rate in DN and PR

### ISSUE THREAD

**Issue by vishdha** [frappe/erpnext#33538]
### Information about bug

1.Create PO with Price List Rate 100.
2. Create SO against PO fetch Price List Rate 100
3. Create Delivery Note but it take valuation rate lets assume its 126 so price list rate is 100 but delivery note force to use valuation rate as rate 126. so tax also calculated based on valuation rate not price list rate.

Need to validate this

### Module

accounts

### Version

ERPNext: v14.7.0 (version-14)

Frappe Framework: v14.15.0 (version-14)

### Installation method

None

**Comment by deepeshgarg007** [comment]
@vishdha This is intentional and not a bug. Internal Transfers have to be done at valuation rates else there will be a Stock and Account Balance value mismatch. In DN since there is no tax impact it should not be an issue.

**Comment by vishdha** [comment]
@deepeshgarg007  Thanks for clarification.  but UX wise it looks wearied for End user. IN PO AND SO should get valuation rate based rate or zero value. otherwise assume Sales Dept set One value and  Dispatch Department get different value they get confuse. SO and DN value should be same
