### ISSUE TITLE
Unable to fetch Exchange rate for Price list with different currrency

### ISSUE THREAD

**Issue by maveezmh** [frappe/erpnext#33530]
### Information about bug

When the  created price list has currency other than base currency of the company. the system is unable to fetch exchange rate for pricelist currency from exchange rate server. 

![image](https://user-images.githubusercontent.com/112148467/210428226-02baedeb-f8f3-4d91-a264-1ef7539862a6.png)

it shows below error

<img width="1440" alt="Screenshot 2023-01-03 at 11 31 33 PM" src="https://user-images.githubusercontent.com/112148467/210428413-3a8badf3-3be2-4adf-9894-9d0606862f2e.png">

The issue is there in Every Transactional Document like 
Sales invoice
Sales Order
Quotation

And purchase Side.

### Module

selling

### Version

ERPNext: v14.11.1 (HEAD)

Frappe Framework: v14.21.0 (HEAD)

Frappe HR: v1.0.0 (HEAD)

Payments: v0.0.1 (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
Unable to find exchange rate for AED to USD for key date 2023-01-03. Please create a Currency Exchange record manually
```

**Comment by auntmaung** [comment]
pls show exchange rate setting? look like no exchange rate data in api with given date and currency.

**Comment by maveezmh** [comment]
@auntmaung 

if you see below image you can see that its fetching exchange rates properly for customer currency but throwing error in base currency and its getting reset to 1


![Screenshot 2023-01-19 at 08-40-16 New Quotation - new-quotation-1](https://user-images.githubusercontent.com/112148467/213357156-20b6c131-558a-4a60-8452-d88a56b41dd4.png)

**Comment by maveezmh** [comment]
Any Update?

**Comment by dj12djdjs** [comment]
https://github.com/frappe/erpnext/issues/34680

**Comment by ruthra-kumar** [comment]
The default exchange rate provider - frankfurter.app does not support `AED`. Would suggest you to explore other service providers, like exchangerate.host(has limited free service and a Paid option).

ERPNext v14 and above `Currency Exchange Settings` where frankfurter.app and exchangerate.host are pre-configured and a `Custom` option to configure any provider.

<img width="1440" alt="Screenshot 2024-01-09 at 3 50 07 PM" src="https://github.com/frappe/erpnext/assets/3272205/b3b8c99d-3715-48dc-b487-15474b95548c">
