### ISSUE TITLE
Disables Lead or Customer

### ISSUE THREAD

**Issue by chrisdent** [frappe/erpnext#33542]
### Information about bug

Creating an opportunity from Lead disables the lead.

Creating Sales Order from Lead creates customer but it creates it disabled.

Is it a bug or a parameter?

### Module

CRM

### Version

ERPNext: v14.11.0 (version-14)
Frappe Framework: v14.20.0 (version-14)

### Installation method

manual install

**Comment by deepeshgarg007** [comment]
@chrisdent Fixed via: https://github.com/frappe/erpnext/pull/33859
