### ISSUE TITLE
Items With Webhook Link 

### ISSUE THREAD

**Issue by tweetechnology** [frappe/erpnext#33571]
### Information about bug

I Imported my items and linked image from my S3 , It showing images all looks fines ,
but when same item i want to publish to web i get error about webhook image link its not readable , now what i did i removed webhook image link which i used while importing and again attached manually same webhook image but at this time i did by selecting public …while attaching webhook Image Link 
after attaching same webhook image public to this same item which was not able to publish as web item ,now published
Now Question is

Do i need to need to import my items all as public if i am not wrong this is not secure
If not when how i can set only webbook link as public so that all my items which imported as bulk i can also publics as webitems too ,
Looking forward from seniors Input
Thanks

### Module

ecommerce

### Version

ERPNext 14

### Installation method

None

**Comment by rohitwaghchaure** [comment]
@gotmoto 

Have you created Website Items to publish items on web? if not then you have to make Website Item using server script on creation of item through webhook .
