### ISSUE TITLE
POS Enhancements

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#3357]
- [ ] Reverse item order
- [ ] Ability to show, hide item image in pos
- [ ] Recalculate taxes on discount (?)
- [ ] Set final discount as rate or amount

via https://github.com/frappe/erpnext/issues/3132#issuecomment-105012184

**Comment by mbauskar** [comment]
@rohitwaghchaure,

Can you please check and close the issue if the enhancement is already implemented
