### ISSUE TITLE
Purchase order not created from Sales Order

### ISSUE THREAD

**Issue by zahidmansoor** [frappe/erpnext#33599]
### Information about bug

After submitting a sales order, When I try to create a purchase order from that sales order, it gives an error "Purchase Order already created for all Sales Order items".
But actually no purchase order has been created against this sales order.

![image](https://user-images.githubusercontent.com/16962072/211508814-9d51dc77-0ded-45ad-9565-ac617974f322.png)

### Module

selling

### Version

ERPNext: v14.12.0 (version-14)
Frappe Framework: v14.21.1 (version-14)

### Installation method

manual install

**Comment by zahidmansoor** [comment]
Any Update???

**Comment by s-aga-r** [comment]
> Any Update???

@zahidmansoor The issue is not replicable. Please provide the steps to replicate it and reopen the issue.

**Comment by marination** [comment]
@zahidmansoor The logic here is it checks if there is **atleast** one row in the child table where there is some pending qty to order. So it checks if (row's qty in stock uom - rows ordered qty is > 0). Maybe this hint will help
