### ISSUE TITLE
Auto generate Stock Repost entries (cron job)

### ISSUE THREAD

**Issue by vorasmit** [frappe/erpnext#33612]
## Issue faced

We have a report Stock and Account value comparision, that shows the difference between stock value and account value.
Differences pile up over time.

**Screenshot**: Stock and Account value comparision

![image](https://user-images.githubusercontent.com/10496564/211727395-6b6a154b-112a-40af-af06-26009b9c8f75.png)

## Proposed solution

- The best way could be to have a stock repost entry to reconcile this difference.
- This can be a cron job to identify the difference if any and make a stock repost entry to reconcile them.
- Difference entries can be restricted to the current financial year or where accounts are not frozen (from accounts settings).

**Comment by s-aga-r** [comment]
@vorasmit We have added a button to create Repost Item Valuations for the selected rows from the Stock and Account Value Comparison report.
