### ISSUE TITLE
New Stock Reconciliation Encoding 

### ISSUE THREAD

**Issue by rydersaint** [frappe/erpnext#3361]
Hello All

"New Stock Reconciliation" give me encoding error.
I am uploading a csv sheet with japanese text.
In the warehouse column shows encoding as "ä»®ååº« - F" instead of "仮倉庫 - F".

Any ideas what I can do next ?

Kind regards

**Comment by anandpdoshi** [comment]
Which spreadsheet app are you using?

**Comment by tmimori** [comment]
Hi, @anandpdoshi 
I could reproduce this issue.

Please confirm this Screenshot(bellow).
I downloaded by clicking "download", edited CSV, and uploaded bt clicking "upload", then corruption occured.
I used for uploading withFirefox 37.0.2 armv7h, and used for editing CSV with Pluma Text Editor.
I edited and saved the CSV with UTF-8.

Could you please confirm this?
Thank you and Regards,

![screenshot-sr-000001 - mozilla firefox](https://cloud.githubusercontent.com/assets/624831/7929483/8376c742-0939-11e5-9c7b-57e1bf16c430.png)

**Comment by anandpdoshi** [comment]
Can anyone send me the CSV which I can use to reproduce the problem?

**Comment by tmimori** [comment]
@anandpdoshi 
Thank you for the reply.

I sent a mail with attachment.
Could you please confirm it?

Thank you and Regards,

**Comment by anandpdoshi** [comment]
Got the CSV thanks!

Thanks,Anand Doshi.

**Comment by tmimori** [comment]
@anandpdoshi I made a pull-request.
Could you please onfirm it?
