### ISSUE TITLE
UOM Specific Barcode is not working on POS Screen

### ISSUE THREAD

**Issue by maveezmh** [frappe/erpnext#33649]
### Information about bug

We have option to create UOM specific barcodes but its not working on POS Screen

### Module

selling

### Version

V14

### Installation method

FrappeCloud

**Comment by developsessions** [comment]
@maveezmh Whats exacly is not working? Can you detail the issue please?

**Comment by maveezmh** [comment]
Basically we have UOM based barcodes in item master. Now when you are in sales Invoice based on scanned barcode the system takes UOM in sales invoice item table

ex if barcodes are like this

1122333 UOM=Nos
445566 UOM=Dz

now based on barcode scanned items will be added in the table with respective UOMs. 
the same functionality is not working in POS Screen.

for both the barcodes it will fetch default Item master UOM

**Comment by ankush** [comment]
https://github.com/frappe/erpnext/pull/30988

Should be simple to extend this to POS.

**Comment by RitvikSardana** [comment]
@maveezmh 
is it working now or are you still facing the issue?

**Comment by RitvikSardana** [comment]
<img width="787" alt="image" src="https://github.com/frappe/erpnext/assets/65544983/b42de23e-9a73-4efa-ad11-c309a3a0166f">
Each item here is a component.

When this Component is clicked, we trigger an event item_selected which in turn calls the `on_cart_update` function in POS Controller.js file. 
[https://github.com/frappe/erpnext/blob/develop/erpnext/selling/page/point_of_sale/pos_controller.js#L515](url)

`on_cart_update` calls `get_item_from_frm` which is responsible for handling "name, item_code, batch_no, uom, rate".

**Comment by maveezmh** [comment]
Hi, @RitvikSardana 

Basically we have two barcodes for an item one for unit and other for boxes. 

![Screenshot 2023-07-26 at 14-54-29 Apple - F001](https://github.com/frappe/erpnext/assets/112148467/a6dad7f9-7782-48d2-a003-3b5e02ae9bfa)

when you use Box based barcode in sales invoice following entries happen with UOM box as defined in the master

![Screenshot 2023-07-26 at 14-50-03 New Sales Invoice - new-sales-invoice-1](https://github.com/frappe/erpnext/assets/112148467/e059fad0-0181-43ad-b89a-b2fa574f9505)

but when you use same barcode in point of sale  the system adds default UOM irrespective of uom defined for that barcode.

![Screenshot 2023-07-26 at 14-48-22 New POS Invoice - new-pos-invoice-1](https://github.com/frappe/erpnext/assets/112148467/90ecc1c2-dec5-4d9b-81e5-43431638a568)

the point of sale in not selecting the proper UOM for given item
