### ISSUE TITLE
Sidebar is hidden in Firefox after update to ERPNext 14.12.1

### ISSUE THREAD

**Issue by flortsch** [frappe/erpnext#33647]
### Information about bug

I updated to ERPNext 14.12.1 and noticed that the sidebar is suddenly hidden in Firefox (108.0.2).
In my Chromium browser this is not the case and the sidebar is visible.

What is interesting: when you, e.g., click on edit workspace (top right button), the sidebar shortly pops up, but it hides again when you click on finish editing.
There seems to be some CSS rule active that hides the sidebar (screenshot attached).

### Module

all

### Version

Frappe version v14.22.0
ERPNext version v14.12.1

Screenshot attached.

![Bildschirmfoto vom 2023-01-13 16-40-51](https://user-images.githubusercontent.com/15350076/212359626-d62276ca-d9a9-4a6c-9212-757e52d0a057.png)

### Installation method

docker

**Comment by maveezmh** [comment]
Lots of calls from different customer

**Comment by komali2** [comment]
I'm having this issue on the "start on F Cloud" version of ERP next that I'm evaluating ERP next with. I'm glad it's a bug, I thought it was ERP next trying to force me to use a "search bar UX" which would be not fun lol

**Comment by flortsch** [comment]
Seems to be fixed in v14.13.0.
