### ISSUE TITLE
Serviceable items to be fetched automatically in PO

### ISSUE THREAD

**Issue by ram-chandu** [frappe/erpnext#33645]
Hi Team,

Facing the following issue in V14 instance:
When create "Subcontract PO " from Production plan. The draft PO should be make for service items automatically, but now the PO is creating with blank items. Right now we have to add service items manually in the PO. 

Steps to replicate:
1. Go to the Production plan.
2. From Production plan click on create button and click on Work order/ subcontract PO.
3. Then the subcontract PO (https://v14-test-rcil.frappe.cloud/app/purchase-order/PO%2FFY22%2Fbranch_abbr0044)will be created in draft status. 

Observation:
1. Here the created subcontract PO at the items table, the item code for service item is coming as blank and the user need to enter the service item manually.   

Approaches :
Currently in the production Plan you can include the non stock items(Maintain Stock is unchecked). Can we approach the selection of Serviceable Item at the Production Plan as below.

1. In Sub-Assembly Items Table if Manyfacturing Type is Subcontract provide by default a mandatory and checked checkbox as Include Serviceable Item: Link field to items for which the Maintain Stock checkbox is unchecked 
2. Users select the serviceable item and click on submit.

Expectation:
On submission the serviceable items should be carried forward to the Purchase Orders.

2nd Approach:
1. Create a Item for the subcontracted item foe which the checkbox If subcontracted to a vendor is checked.
2. On selection of the checkbox populate a mandatory field as Serviceable Item: Link field to Items for which the Maintain Stock is unchecked.
3. Save the item by entering the details.

Expectation:
If PO is created from the Production Plan the Subcontracted item master has details of Serviceable Item, automatically populate the details in the PO.

Attaching the Screenshots for your reference.
![DrIstQq](https://user-images.githubusercontent.com/119317369/212255095-1b99e5a8-5153-4250-b886-64be4aa10bf8.png)
![seEfImH](https://user-images.githubusercontent.com/119317369/212255118-cf972820-7519-4d6e-a898-5957468fbeac.png)

Thanks

**Comment by szufisher** [comment]
I developed customized solution per your 2nd approach.

this should for erpnext other than frappe

**Comment by ram-chandu** [comment]
Hi Szufisher,

Thank you for considering our request. Can you please help us with the release details.

Thanks.

**Comment by ram-chandu** [comment]
Hi Szufisher,

Can you please share the link to the code where you have developed the customisation.
 
Thanks.
