### ISSUE TITLE
UOM should be specific to Items selected in transaction

### ISSUE THREAD

**Issue by maveezmh** [frappe/erpnext#33640]
### Information about bug

When we add an item it has a default UOM or set of predefined UOMs whenever we are in a document like sales order sales invoice or any other transactional document we should only see uom's related to that item. not all the UOMs

<img width="1440" alt="Screenshot 2023-01-13 at 10 03 08 AM" src="https://user-images.githubusercontent.com/112148467/212249735-67fb249b-358f-4b81-a2e6-1153eed250bc.png">

### Module

stock

### Version

ERPNext: v14.12.1 (HEAD)

Frappe Framework: v14.22.0 (HEAD)

Frappe HR: v1.0.0 (HEAD)

Payments: v0.0.1 (HEAD)

### Installation method

FrappeCloud

**Comment by rohitwaghchaure** [comment]
@maveezmh Sometimes it's hard to define the conversion factor in the item master, specially when the conversion factor is not fixed. Take example of Tea Powder.

Support I have created purchase order for Tea Powder with 2 KG and supplier has send me in the packet with 100 Gram, 500 Gram size. In this case the conversion factor is not same for each packet.

If you want to restrict then write custom script to show the UOMs defined in the Item master using set_query

**Comment by maveezmh** [comment]
@rohitwaghchaure Thanks Rohit... Will look into the same.

 it would be really helpful if we could give a toggle in stock settings related to same. like user can define for his system if it will be filtered or global.
