### ISSUE TITLE
Shopping Cart rewrite and Automation of Taxes and Price List based on Address

### ISSUE THREAD

**Issue by anandpdoshi** [frappe/erpnext#3366]
Also takes care of #3255
- [ ] Item Variant view
- [ ] Automation via Selling Settings (enabled for Shopping Cart)
  - [ ] Select Price List based on Address
  - [ ] Select Tax Template and Shipping Rule based on Address
  - [ ] Selection based on ["Billing Address", "Shipping Address"]
  - [ ] Shipping Rule selection will always be based on Shipping Address  
    ![screen shot 2015-05-27 at 8 17 42 pm](https://cloud.githubusercontent.com/assets/836785/7850252/7d6fd568-04ad-11e5-8620-bb29ba601cac.png)
  - [ ] If user changes the Address in the form and if the tax template / price list turns out to be different than the one present in the form, a popup should ask if the user wants to re-apply the different tax template / price list based on the address
- [ ] Address Matching
  - [ ] If Address Matches = ["Any Country", "Home Country", "Rest of the World", "Country, State, Post Code Pattern"]  
    ![screen shot 2015-05-27 at 8 08 08 pm](https://cloud.githubusercontent.com/assets/836785/7850153/2d055658-04ac-11e5-9edc-62ff2182bf49.png) 
  - [ ] Search order
    - ("Country", "Post Code Pattern")
    - ("Country", "State")
    - Country
    - Home Country or Rest of the World
    - Any Country
  - [ ] Post Code Pattern can be values like "123XX"
- [ ] Customer's default Price List and Tax Template will be given priority over address matching

**Comment by anandpdoshi** [comment]
- [ ] Customer's default Price List and Tax Template will be given priority over address matching

**Comment by anandpdoshi** [comment]
Post Code seems to be a generic term instead of ZIP code that is valid only for US.

Possible generic solution to this localisation issue:
- Add a language en_US in languages.txt
- Add translations relevant to US like Post Code = ZIP Code in en_US.csv
- Similarly add a language en_IN in languages.txt and add "Post Code" = "PIN Code" in en_IN.csv

@rmehta and @pdvyas what do you think?

**Comment by anandpdoshi** [comment]
- [ ] Add a State DocType and populate it using geonames.org database or use the geonames database / api for validations and suggestions (no need for a State doctype in database)

**Comment by rmehta** [comment]
@anandpdoshi add it in country wise fixtures / setup
