### ISSUE TITLE
Future Payment Amount and Remaining Amount is wrong in Accounts Receivable Report with Multi currency 

### ISSUE THREAD

**Issue by AuntMaungGreenPhyto** [frappe/erpnext#33678]
### Information about bug

![image](https://user-images.githubusercontent.com/88998237/212641772-9e12eb17-b726-4698-b4ef-87a33075d1b4.png)
![image](https://user-images.githubusercontent.com/88998237/212641980-e5067a11-6aa6-4696-bba1-eefc8aba1161.png)
Future Payment should be $1.34 and Remaining Balance should be $ 0.82 intead $1 and $1.16

### Module

accounts

### Version

Frappe Version: v14.22.1
ERPNext Version: v14.12.0

### Installation method

None

**Comment by deepeshgarg007** [comment]
@AuntMaungGreenPhyto This issue doesn't have enough for further investigation. Please add more info and reopen for further investigation
