### ISSUE TITLE
Creating Purchase Order Of Bundled Items from sales Order Page

### ISSUE THREAD

**Issue by tweetechnology** [frappe/erpnext#33694]
### Information about bug

Hello Community and Honorable , 
As understood already Bundle Product can be sold but not maintain stock and suppose to be not purchased or maintain stocks 
as its made up of already individual items in stocks , 
now here is flow , 
If bundle item have created Sales Order > from sales order as we already can create purchase order when clicked on purchase order form selection form is loaded for defining suppliers with Parent Item , 
instead loading Parent Item that suppose to load all those individual Items which are in packed items (Table ) instead of Parent item , 
as parent item itself already we are not maintaining in stocked and suppose to be neither in purchase too . 

I hope with small tweak we can load table items from bundle packed item table in form which loading from sales order menu to "Create purchase order"  

![image](https://user-images.githubusercontent.com/22383443/212818558-1ce960a0-c6a4-49f2-88c2-6a2ef4dfba1e.png)
![image](https://user-images.githubusercontent.com/22383443/212818790-d7b9ea4c-88e4-4283-b880-934244477b77.png)
![image](https://user-images.githubusercontent.com/22383443/212819052-fe60d4a9-5dc6-47e2-8441-0d362a932472.png)

### Module

buying

### Version

erpnext 14.12.1

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
I understand your needs, @tweetechnology.

The feature isn't available yet, but you can tweak it using client/server script. If you have an idea, you can contribute it and even submit a Pull Request on GitHub. If the feature fits, the team will approve it.

Thank You!
