### ISSUE TITLE
Woocommerce connector dropping error if the customer already exist

### ISSUE THREAD

**Issue by Rokasandor** [frappe/erpnext#33708]
### Information about bug

1. You create a new weborder in woocommrce connected to erpnext. 
2. The new customer is created in order, and the sales order created in order.
3. The same customer is placing an order again in woocommerce. The sync is fail due to and error message
      frappe.throw(_("No changes made because old and new name are the same.").format(old, new))
      
    The reason is probably the frappe/erpnext/tree/develop/erpnext/erpnext_integrations/connectors)/woocommerce_connection.py line 84:
    frappe.rename_doc("Customer", old_name, customer_name)

before the rename call there should be a check if the new customer_name and the old_name are the same.
Ro reason to call the rename is these are the same, and it is causing an error.

### Module

integrations

### Version

Frappe version 14
ERPnext version 14

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/erpnext/erpnext/erpnext_integrations/connectors/woocommerce_connection.py", line 30, in order
    _order(*args, **kwargs)
  File "apps/erpnext/erpnext/erpnext_integrations/connectors/woocommerce_connection.py", line 62, in _order
    link_customer_and_address(raw_billing_data, raw_shipping_data, customer_name)
  File "apps/erpnext/erpnext/erpnext_integrations/connectors/woocommerce_connection.py", line 84, in link_customer_and_address
    frappe.rename_doc("Customer", old_name, customer_name)
  File "apps/frappe/frappe/__init__.py", line 1308, in rename_doc
    return rename_doc(
  File "apps/frappe/frappe/model/rename_doc.py", line 154, in rename_doc
    new = validate_rename(
  File "apps/frappe/frappe/model/rename_doc.py", line 357, in validate_rename
    frappe.throw(_("No changes made because old and new name are the same.").format(old, new))
  File "apps/frappe/frappe/__init__.py", line 525, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 493, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 442, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: No changes made because old and new name are the same.
```

**Comment by N-Codee** [comment]
I got the same. hope logical error.
`if old == new:
		frappe.throw(_("No changes made because old and new name are the same.").format(old, new))
`

**Comment by TubaApollo** [comment]
Why is this closed, has it been fixed? I have this problem too, new orders from the same customers are not transferred...

**Comment by Rokasandor** [comment]
I still have the problem even I have upgraded to the latest version. I do not undrestand why was it closed.

**Comment by aemirzephlex** [comment]
@deepeshgarg007 why did you close this? Please provide more details.

**Comment by ascorbic-acid** [comment]
this problem still exist, please re open, also i think it is better to split this into a separate app to allow contributes help easly

**Comment by ReginaldGouws** [comment]
Having the same issue
