### ISSUE TITLE
Service received but not billed accounting is wrong when item has expense account

### ISSUE THREAD

**Issue by chrisdent** [frappe/erpnext#33728]
### Information about bug

Service received but not billed accounting is wrong when item has expense account

When making a purchase order the against account is the expense account configured in the item default instead of the Accounts Payable. 

### Module

accounts

### Version

ERPNext: v14.11.0 (version-14)
Frappe Framework: v14.20.0 (version-14)

### Installation method

manual install

**Comment by deepeshgarg007** [comment]
<img width="1369" alt="Screenshot 2023-01-29 at 6 02 17 PM" src="https://user-images.githubusercontent.com/42651287/215326358-c7aa7a1f-2cc4-4b6b-bd14-d5c3036a1e7c.png">

@chrisdent You can uncheck this if you don't want this behaviour
