### ISSUE TITLE
Can't rename Lead

### ISSUE THREAD

**Issue by chrisdent** [frappe/erpnext#33806]
### Information about bug

Creating lead then save it. Then rename it, won't rename it.

### Module

CRM

### Version

ERPNext: v14.12.1 (version-14)
Frappe Framework: v14.22.0 (version-14)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
No error, but appears a success message and the rename is not done.
```

**Comment by dj12djdjs** [comment]
@chrisdent The lead doctype isn't allowed to be renamed by intention. Not sure why...

But the lead title can be changed by changing the field values:
### Without middle name set
![image](https://user-images.githubusercontent.com/29856401/214440402-52a4b8bb-86fb-4c16-a781-c9ab65fb168f.png)

### With middle name set
![image](https://user-images.githubusercontent.com/29856401/214440430-d02e15d7-0365-4599-984e-2e526b546df7.png)

**Comment by chrisdent** [comment]
Awesome, thanks for your clarification. Maybe not allowing to change the title with double click over the title would be helpful in usability.
