### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './assets/frappe/js/lib/snap.svg-min.js'

### ISSUE THREAD

**Issue by SaQDS** [frappe/erpnext#33805]
### Information about bug

when im trying to add "New Soil Texture" in Agriculture model, i got the error message. 

### Module

agriculture

### Version

	"erpnext": "13.42.6",
	"erpnext_telegram_integration": "1.1.0",
	"frappe": "13.46.2"

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "13.42.6",
	"erpnext_telegram_integration": "1.1.0",
	"frappe": "13.46.2"
}
```
### Route
```
Form/Soil Texture/new-soil-texture-1
```
### Trackeback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 38, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 76, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1457, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/client.py", line 349, in get_js
    with open(contentpath, "r") as srcfile:
FileNotFoundError: [Errno 2] No such file or directory: './assets/frappe/js/lib/snap.svg-min.js'

```
### Request Data
```
{
	"type": "GET",
	"args": {
		"items": "[\"assets/frappe/js/lib/snap.svg-min.js\"]"
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.client.get_js"
}
```
### Response Data
```
{
	"exception": "FileNotFoundError: [Errno 2] No such file or directory: './assets/frappe/js/lib/snap.svg-min.js'"
}
```
```

**Comment by dj12djdjs** [comment]
caused by: https://github.com/frappe/frappe/pull/12409

**Comment by SaQDS** [comment]
> caused by: [frappe/frappe#12409](https://github.com/frappe/frappe/pull/12409)

Thanks a lot, but in order to stop showing that error message, where and how can i edit or update the related codes? 
As each time i get the error message, it also produces below error, then my erpnext site stops responding, I have to wait for 10 or more mins before it's back.  

**During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/erpnext/apps/frappe/frappe/utils/error.py", line 50, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/erpnext/apps/frappe/frappe/utils/error.py", line 143, in get_snapshot
    value = pydoc.text.repr(getattr(evalue, name))
AttributeError: characters_written**
