### ISSUE TITLE
Posting date report column always too small

### ISSUE THREAD

**Issue by dgehriger** [frappe/erpnext#33827]
### Information about bug

As you can see on the screenshot, the date column (e.g. in the general ledger report) is too small. I can resize it, but this doesn't persist. The next time I modify anything, or open the ledger, the dates will again be cut off.

Is there any way to configure a slightly wider width? 

![image](https://user-images.githubusercontent.com/105200493/214855759-5991b238-c670-4a3f-b101-ba6466a1d07f.png)

### Module

accounts

### Version

Frappe: v14.23.0 (version-14)
ERPnext: v14.13.0 (version-14)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
N/A
```

**Comment by deepeshgarg007** [comment]
@dgehriger Fixed via https://github.com/frappe/erpnext/issues/33827

**Comment by iramluism** [comment]
@deepeshgarg007 the column name not appear properly yet, i add this PR to increment to 120.
