### ISSUE TITLE
[V5]: New Created Items have End Of Life field as NULL

### ISSUE THREAD

**Issue by adityaduggal** [frappe/erpnext#3383]
Hi,

The newly created items in V5 are having NULL values and hence they would create problems in showing in reports.

I have observed that all Items after converting to v5 are showing end of life as 31-12-2099 but not in case of new items

**Comment by anandpdoshi** [comment]
Hi Aditya,

If left blank, almost all fields have NULL value. What do you expect the
end of life to be if left blank?

Maybe the reports should show blank if date is null and that's where the
problem is and not that end of life is null. What do you think?

-Anand.

**Comment by adityaduggal** [comment]
I thought that the default value was being set to 31-12-2099 as all the items which were created in v4 have their eol populated as that date and hence I thought it might be a problem.

If I am not wrong this problem happened when the DB was changed from mysql to maria db and hence I thought that I should point this again and it might create issues later.

If you think that leaving the eol blank is not going to affect the normal functioning of the items then kindly close the issue.

**Comment by anandpdoshi** [comment]
Seems there is a patch that sets the end of life date to `2099-12-31` where date is `0000-00-00`. Maybe @rmehta can put some light on it. He wrote that patch.

**Comment by anandpdoshi** [comment]
Additional Note: When empty string `""` was passed to mysql it stored the value as `0000-00-00` but if `NULL` is passed, it stores it as `NULL` and not `0000-00-00`. So maybe the patch should've set it as `NULL` and not `0000-00-00`. I think this is fixed in mariadb / python-mysql i.e. if you pass '' or None, it results in None.

```
Original value:
(u'Polo Tshirt-XS-WHI', datetime.date(2099, 12, 31))

In [4]: frappe.db.sql("""update `tabItem` set end_of_life=%s where name='Polo Tshirt-XS-WHI'""", '')
Out[4]: ()

In [5]: frappe.db.sql("""select name, end_of_life from `tabItem` where name='Polo Tshirt-XS-WHI'""")
Out[5]: ((u'Polo Tshirt-XS-WHI', None),)

In [6]: frappe.db.sql("""update `tabItem` set end_of_life=%s where name='Polo Tshirt-XS-WHI'""", None)
Out[6]: ()

In [7]: frappe.db.sql("""select name, end_of_life from `tabItem` where name='Polo Tshirt-XS-WHI'""")
Out[7]: ((u'Polo Tshirt-XS-WHI', None),)
```

**Comment by adityaduggal** [comment]
I guess this behavior is expected as per the team and hence I am closing this ticket.
