### ISSUE TITLE
BOM Update Cost set 0$ when no actual qty

### ISSUE THREAD

**Issue by guilmori** [frappe/erpnext#33830]
### Information about bug

If a BOM's material item has 0 qty in stock, when we click 'Update Cost' it set cost to 0$, it won't get last transaction valuation.

### Module

manufacturing

### Version

v13.39.1

### Installation method

manual install

**Comment by guilmori** [comment]
Have a look at this line that does a division by 0, resulting in None value, which is then assumed no Bin exists...
https://github.com/frappe/erpnext/blob/b31b850db8775029714f41d0c40bc43f81f57bd5/erpnext/manufacturing/doctype/bom/bom.py#L956

**Comment by s-aga-r** [comment]
@guilmori not able to replicate.

Balance Qty is `0` for RM ITEM 01.

![image](https://user-images.githubusercontent.com/63660334/216645407-2aeab506-1ad4-4ae7-aec1-5af0b37e70a5.png)

After clicking `Update Cost` the price is still 100.

![image](https://user-images.githubusercontent.com/63660334/216645819-251035b4-f9e8-425d-840f-b6d8420b1605.png)

![image](https://user-images.githubusercontent.com/63660334/216645255-7df6cec9-4f8c-4ac6-983b-4590a52e503c.png)

**Comment by guilmori** [comment]
@s-aga-r  And you have no Valuation Rate set in the Item's page ?

Strange... If you debug python's code, this line returns 0 or None ?
https://github.com/frappe/erpnext/blob/2afed7de0393a09e00773aa300a35ab56f56e663/erpnext/manufacturing/doctype/bom/bom.py#L960

For me it returns None (and tabBin record exists)

**Comment by OneiricIT** [comment]
@guilmori we also have the same issue ourselves (v14.18.2) , and a client too ( earlier v13).

We would have expected the valuation to be the last valuation in stock ledger to be used if not stock, however the logic seems that if not stock then pull item master valuation amount correct?

**Comment by OneiricIT** [comment]
I have checked the logic.

Per below, and description therein, stock is checked in bin (first frappe.qb query) which if there is no stock found a NONE type would be returned and so it moves to line 984 which checks against item master valuation which would default to $0 if not altered by a user on creation.

So the question is: why is there no logic for items that **have** had stock in the system to pull the last valuation rate in SLE? I see no point in having to maintain an item valuation for stock already passing through the system. 
It also throws out the BOM's if item mast valuation is not set, or has not been updated. We have a customer with huge pains in this regard.

Linking in @marination given huge amount of input relating to BOM.py as of late for a possible answer / discussion? 

https://github.com/frappe/erpnext/blob/cfcbdfcaec8015296a06b6b7d692bd9ab51f6e4d/erpnext/manufacturing/doctype/bom/bom.py#L946-L987
