### ISSUE TITLE
Hi All, Any one had the same issue and got a solution for Error: Value missing for Module Onboarding: Documentation URL

### ISSUE THREAD

**Issue by ROKET3108** [frappe/erpnext#33854]
### Information about bug

ERPNext Error: Value missing for Module Onboarding: Documentation URL

### Module

accounts, stock, buying, selling, HR, projects, CRM, quality, education

### Version

ERPNext:

Version 13
Version 14
![image](https://user-images.githubusercontent.com/31337243/215288903-a6f92aa6-ffa5-4448-942e-136108bd2671.png)
<img width="951" alt="ERPNext Error" src="https://user-images.githubusercontent.com/31337243/215288934-b71fb5b3-175e-4fd4-8e76-a90842bbb079.PNG">

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
Error: Value missing for Module Onboarding: Documentation URL
```

**Comment by deepeshgarg007** [comment]
@ROKET3108 This seems to be happening because of some wrongly done customization in the Workspaces as its not replicable on other sites. Please add more info and then reopen

**Comment by ngenziremy** [comment]
Where does one needs to add more information and how can we prevent the above issue from recurrence?

**Comment by CreativeOthman** [comment]
Where does one needs to add more information and how can we prevent the above issue from recurrence?
