### ISSUE TITLE
Delivery note reference not showing in Sales Invoice connection

### ISSUE THREAD

**Issue by vishdha** [frappe/erpnext#33867]
### Information about bug

In Sales Invoice child table Delivery Note Name available still it not showing in Sales Invoice Connection. 

### Module

accounts

### Version

ERPNext: v14.14.0 (version-14)
Frappe Framework: v14.24.0 (version-14)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.
![image](https://user-images.githubusercontent.com/6947417/215391734-0d3026b9-b647-4c8e-8b90-4ef5e50258bb.png)

**Comment by s-aga-r** [comment]
There are two flows:

- Sales Invoice --> Delivery Note (Delivery Note Link will be available)

  ![image](https://user-images.githubusercontent.com/63660334/216612833-3d4cd8dc-a1bc-4b61-9854-bdb3a3cda339.png)

- Delivery Note --> Sales Invoice (Delivery Note Link will not be available)

  ![image](https://user-images.githubusercontent.com/63660334/216613359-ba88974b-2373-4a98-90c7-2ab5303fd0bc.png)

Why?

https://github.com/frappe/erpnext/blob/2afed7de0393a09e00773aa300a35ab56f56e663/erpnext/accounts/doctype/sales_invoice/sales_invoice_dashboard.py#L8

If you update this then the Delivery Note Link will not be shown for flow 1 (SI --> DN). As a DocType can't have more than one connection reference.



Closing this...
