### ISSUE TITLE
[V4] General Ledger is showing ledger of two accounts when we enter only one account?

### ISSUE THREAD

**Issue by rahulnejanawar** [frappe/erpnext#3387]
Hi All,

Query Report: General Ledger is showing ledger of two accounts when we enter only one account name in Account field. Here I attached the screen shots

When I want to see the ledger of account "Petty Cash ( Jagadish )", It is showing report of that account as well as this account also "Petty cash ( Santosh )"
http://i.imgur.com/IO8Aebu.png
For account "Petty cash ( Santosh )" is also showing same as above 
http://i.imgur.com/bzyVxvE.png

**Comment by nabinhait** [comment]
Seems like "Nested Set Model" is broken. Try to rebuild it using `rebuild_tree()` function: https://github.com/frappe/frappe/blob/develop/frappe/utils/nestedset.py#L138

**Comment by nabinhait** [comment]
Is this fixed?
