### ISSUE TITLE
Error Message when going into Asset Module

### ISSUE THREAD

**Issue by cambraventures** [frappe/erpnext#33887]
### Information about bug

When I click on the asset module on the left menu and go to the main asset screen I receive the following error message 

![7D877D84-DAA8-4D19-BAB8-EA628624C0BC](https://user-images.githubusercontent.com/117315619/215561075-8db84df9-6285-44f6-8d4d-4fa9217255c1.jpeg)

The trace back is as follows:
![Uploading AC50B30E-EEAC-44A0-909D-9829DA1A635C.jpeg…]()

### Module

assets

### Version

Frappe - 14.24.0
ERPNext - 14.14.0

### Installation method

manual install

**Comment by anandbaburajan** [comment]
@cambraventures sorry for the inconvenience. The issue should be fixed if you upgrade to the latest release.

**Comment by cambraventures** [comment]
This worked thank you
