### ISSUE TITLE
[v5] Migration Patch Error in 

### ISSUE THREAD

**Issue by adityaduggal** [frappe/erpnext#3388]
The error is in  frappe.patches.v5_0.bookmarks_to_stars
Here is the error: http://pastebin.com/7PT0qcxQ

**Comment by rmehta** [comment]
Sorry I did not test it. Pratik can you fix this?

**Comment by adityaduggal** [comment]
Don't worry I am doing it on my local server only but would be nice if I could migrate my server on a weekend.

**Comment by anandpdoshi** [comment]
Pushed the fix in develop.

**Comment by adityaduggal** [comment]
thanks I will switch to develop and check.

**Comment by adityaduggal** [comment]
the fix does not seems to be full I am getting this error http://pastebin.com/2vDhsWij

**Comment by rmehta** [comment]
Pushed another fix.

**Comment by adityaduggal** [comment]
I guess this does not fix again http://pastebin.com/kemKD495

**Comment by anandpdoshi** [comment]
@adityaduggal I think changes are not getting pulled in your system.

paste the output of:
`cat /home/aditya/frappe-bench-v4/apps/frappe/frappe/patches/v5_0/bookmarks_to_stars.py`

**Comment by adityaduggal** [comment]
http://pastebin.com/mVkAtgDP

**Comment by anandpdoshi** [comment]
Pushed a fix. This should work :tired_face:

**Comment by adityaduggal** [comment]
thanks worked
