### ISSUE TITLE
Sales Cycle is Broken

### ISSUE THREAD

**Issue by abhioncode** [frappe/erpnext#33893]
### Information about bug

According to the documentation and testing the system, the sales cycle can run the following way:

### Option 1
SALES ORDER → DELIVERY NOTE ⇒ SALES INVOICE

### Option 2
SALES ORDER → SALES INVOICE ⇒ DELIVERY NOTE

**In Option 1**, I am able to make a sales order, delivery note, and sales invoice in the correct sequence once the document is submitted. When I create a Delivery Note, it will link the sales order (Customer PO Number) correctly. And when I create the Sales Invoice, it will link the Delivery Note correctly.

_but ..._
**BUG**: When I create a Sales Order, Delivery Note, and finally Sales Invoice, by the time I reach Sales Invoice the system looses data on Customer PO. This is important because many customer's require the PO# to be able to reference the document in their system. **The only way currently to do this is through option 2, but that has it's own issue:**

**In Option 2**, I am able to make Sales Order and convert into Sales Invoice. Here I am able to show the Customer's PO# correctly. **BUG** But Once the invoice is done and submitted the create dropdown doesn't allow me to create a Delivery Note (even though the documentation says that you can).

I believe this two bugs are relatively easy to fix. The second bug I am able to solve with a custom script, but would rather see this fixed for all. The second bug is a bit more complicated for me to solve through custom scripts. 

### Module

selling

### Version

ERPNext: v14.14.0 (HEAD)
Frappe Framework: v14.24.0 (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
None
```

**Comment by Nihantra-Patel** [comment]
> In Option 1, I am able to make a sales order, delivery note, and sales invoice in the correct sequence once the document is submitted. When I create a Delivery Note, it will link the sales order (Customer PO Number) correctly. And when I create the Sales Invoice, it will link the Delivery Note correctly.
> 
> but ...
> BUG: When I create a Sales Order, Delivery Note, and finally Sales Invoice, by the time I reach Sales Invoice the system looses data on Customer PO. This is important because many customer's require the PO# to be able to reference the document in their system.

Everything is working fine. No problems were encountered in version 14. Please check it.


https://github.com/frappe/erpnext/assets/141945075/fa63158f-7de0-42d4-90aa-db91882e9fcf

> In Option 2, I am able to make Sales Order and convert into Sales Invoice. Here I am able to show the Customer's PO# correctly. BUG But Once the invoice is done and submitted the create dropdown doesn't allow me to create a Delivery Note (even though the documentation says that you can).

Also worked properly.


https://github.com/frappe/erpnext/assets/141945075/ad635a78-e325-4e41-a4eb-0d1a9693bbad

Thank You!
