### ISSUE TITLE
User with Manufacturing user and manager roles cannot see BOM

### ISSUE THREAD

**Issue by PhilVoltSport** [frappe/erpnext#33905]
### Information about bug

When the user follows a link into a BOM, they cannot see any BOM information. The window presents as the top line, which you can click into the boxes and see the available list, but when selected you cannot see the data table below at all.

Information was presenting OK, but stopped one lunchtime, so I think there must be some other setting / action that has overidden the permission?
![image](https://user-images.githubusercontent.com/95633077/215768365-488a868d-79a3-481a-bd51-2a3a6985cc3b.png)

Thanks for any insight!

### Module

manufacturing

### Version

Frappe 13.7.0
ERP 13.7.0

### Installation method

docker

**Comment by s-aga-r** [comment]
@PhilVoltSport The issue is not replicable. Please provide the steps to replicate it and reopen the issue.
