### ISSUE TITLE
Difference Amount on Payment Reconciliation for multi-currency transactions

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#33924]
### Information about bug

**Scenario.**

- Allow multi-currency invoices against single party account
- You have two debtors accounts, a base currency one(KES), and USD one.
- Create a customer who is not limited to any currency
- 
![image](https://user-images.githubusercontent.com/1822868/216054562-1a8def7e-4081-4f97-8254-6f5994f94291.png)

- Create a USD Sales Invoice, for a customer not limited to Debtors USD account, this sales invoice will Debit Debtors-KES(base currency)
- 
![image](https://user-images.githubusercontent.com/1822868/216054804-9de21766-b7e2-47fa-a880-ff7de2e26f9b.png)

![image](https://user-images.githubusercontent.com/1822868/216054967-e1b3a7dd-5742-4ecd-969a-dd0213af2cd1.png)

- Create a payment entry against a base currency bank account
- 
![image](https://user-images.githubusercontent.com/1822868/216055137-04e460f2-9af7-4879-a0a7-25e1d5c95a98.png)

- Create a payment reconciliation, the **Receivable / Payable Account**, will be the Debtors Base currency - KES
- 
![image](https://user-images.githubusercontent.com/1822868/216055326-75b807a6-ee9d-4f12-bc64-09032bdcc06a.png)

- Get unreconciled entries, and allocate
- You will end up with difference amounts posted on journal entry, not sure this should be the case.
- 
![image](https://user-images.githubusercontent.com/1822868/216055467-906f3759-31b7-481c-b0ce-c578aaa790c3.png)

### Module

accounts

### Version

ERPNext: v14.15.0 (HEAD)
Frappe Framework: v14.25.0 (HEAD)

### Installation method

FrappeCloud

**Comment by ruthra-kumar** [comment]
This was fixed by https://github.com/frappe/erpnext/pull/34466
Fix is available from [V14.19.0](https://github.com/frappe/erpnext/releases/tag/v14.19.0)
