### ISSUE TITLE
Hide report links if the REPORT is DISABLED

### ISSUE THREAD

**Issue by adityaduggal** [frappe/erpnext#3392]
Hi,

If a report is disabled then the report link should not show to the users since that creates a lot of clutter in the UI for reports if there are too many reports and DISABLING the reports would only reduce the clutter.

**Comment by adityaduggal** [comment]
Can we also disable the Awesome bar to show up disabled reports, this would be even great.

**Comment by nabinhait** [comment]
@KanchanChauhan Can you fix the awesome bar search as well?
