### ISSUE TITLE
How To Create Tree View

### ISSUE THREAD

**Issue by pankajpatel12** [frappe/erpnext#3393]
i have required land asset tree view in module AgriFarm, so please give me code for land asset tree view and help me how to create land asset tree view in module AgriFarm so, please reply me fast..

**Comment by rmehta** [comment]
Dear @pankajpatel12 

1. If you want "fast" replies, please get hold of someone you know and pay someone. 
2. Nobody will "give you code", you will have to find it yourself. If you are stuck somewhere we can help.

Also post questions on https://discuss.frappe.io

**Comment by pankajpatel12** [comment]
ok no problem.

**Comment by pankajpatel12** [comment]
this treeview quetion is not in https://discuss.frappe.io.
