### ISSUE TITLE
Action > Create delivery trip from delivery note list doing nothing after updating to v14

### ISSUE THREAD

**Issue by vcavel** [frappe/erpnext#33930]
### Information about bug

Nothing happens when clicking on the "create delivery trip" button from the delivery note list. Please find the JS stacktrace attached

### Module

stock

### Version

ERPNext: v14.15.0 (version-14)

Frappe Framework: v14.25.0 (version-14)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Uncaught ReferenceError: doclist is not defined
    action delivery_note__list_js:23
    l page.js:468
    jQuery 2
        dispatch
        handle
```

**Comment by dj12djdjs** [comment]
**Steps to Reproduce**
1. Create and submit a Delivery Note
2. Go to Delivery Note list view
3. Check n amount of Delivery Notes
4. Actions -> Create Delivery Trip
5. Error
