### ISSUE TITLE
Company wise default warehouse

### ISSUE THREAD

**Issue by bobzz-zone** [frappe/erpnext#3394]
i think there should be warehouse default value in company master when there is more than 1 company available than default warehouse in company that will be used....

**Comment by venetanji** [comment]
+1

Maybe this can be achieved by adding default warehouse to customer and a custom script to fetch it?

**Comment by LifeP** [comment]
Can you provide an example of custom script to fetch a default warehouse for sales order item, depending on customer/ company/ user?

**Comment by venetanji** [comment]
First you need to add custom field "default_warehouse" to customer,  then e.g. for Sales order you need to add something like:

```
cur_frm.add_fetch("customer", "default_warehouse", "default_warehouse");

frappe.ui.form.on("Sales Order Item", "item_code", function(frm, cdt, cdn) {
  if (!frm.cur_grid.doc.warehouse) {
    frm.cur_grid.doc.warehouse = frm.doc.default_warehouse;
    refresh_field("warehouse");
  }
});

```

**Comment by LifeP** [comment]
This works great! Thank You!

**Comment by vivek3377** [comment]
Hi ,

I want to preselect default warehouse in sales order/Purchase order item table as per company selection.
