### ISSUE TITLE
bypass credit limit for customer

### ISSUE THREAD

**Issue by bahaou** [frappe/erpnext#33967]
### Information about bug

you can bypass customer credit limit by closing existing sales order and then create new one and then open the old ones without checking customer credit limit  . system should check customer cerdit limit while re-opening sales orders . 

### Module

selling

### Version

14

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
Hi @bahaou,

It only checks in non-closed sales orders, so I think you have to check this condition and also read the command.
It was created based on the perspective of the user or client.

```py
	# if credit limit check is bypassed at sales order level,
	# we should not consider outstanding Sales Orders, when customer credit balance report is run
	if not ignore_outstanding_sales_order:
		outstanding_based_on_so = frappe.db.sql(
			"""
			select sum(base_grand_total*(100 - per_billed)/100)
			from `tabSales Order`
			where customer=%s and docstatus = 1 and company=%s
			and per_billed < 100 and status != 'Closed'""",
			(customer, company),
		)
```

https://github.com/frappe/erpnext/blob/develop/erpnext/selling/doctype/customer/customer.py#L614-L624

Thank You!
