### ISSUE TITLE
Getting 'The authorization server does not support obtaining an authorization code using this method' with Authentik OIDC

### ISSUE THREAD

**Issue by Dan6erbond** [frappe/erpnext#33961]
### Information about bug

I configured ERPNext with an Authentik social provider to configure OIDC for SSO. I was expecting it to work with the settings that I provided below, but unfortunately get this error in the frontend:

```py
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1607, in call
    return fn(*args, **newargs)
TypeError: custom() missing 1 required positional argument: 'code'
```

And in the backend:

```py
Form Dict: {'error': 'unsupported_response_type', 'error_description': 'The authorization server does not support obtaining an authorization code using this method', 'state': '<state>', 'cmd': 'frappe.integrations.oauth2_logins.custom'}
```

My client configuration looks like this:

![image](https://user-images.githubusercontent.com/32235074/216809075-4ad2a390-3a0a-4d7a-94d4-a75f03dace68.png)

And my Authentik provider is a simply OAuth2/OIDC provider with the confidential type, and a self-signed certificate.

### Module

integrations

### Version

Frappe version: v14.15.0
ERPNext version: latest

### Installation method

docker

**Comment by lexermal** [comment]
For everyone finding this issue via Google, I figured it out how to do it. You need to set : `{"response_type": "code", "scope": "openid profile email"}` in Auth URL Data.

Here is the full solution: https://github.com/lexermal/website-weixler-me/blob/master/blog/K3s%20Applications/Install%20ERPNext.md#configure-erpnext
