### ISSUE TITLE
Fix Asset Register

### ISSUE THREAD

**Issue by dineshpanchal93** [frappe/erpnext#33979]
### Information about bug

On click of the asset module give the below error
 [Error] Traceback (most recent call last):
File “apps/frappe/frappe/app.py”, line 69, in application
response = frappe.api.handle()
File “apps/frappe/frappe/api.py”, line 54, in handle
return frappe.handler.handle()
File “apps/frappe/frappe/handler.py”, line 45, in handle
data = execute_cmd(cmd)
File “apps/frappe/frappe/handler.py”, line 83, in execute_cmd
return frappe.call(method, **frappe.form_dict)
File “apps/frappe/frappe/init.py”, line 1607, in call
return fn(*args, **newargs)
File “apps/frappe/frappe/init.py”, line 789, in wrapper_fn
retval = fn(*args, **get_newargs(fn, kwargs))
File “apps/frappe/frappe/desk/query_report.py”, line 251, in run
result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
File “apps/frappe/frappe/init.py”, line 789, in wrapper_fn
retval = fn(*args, **get_newargs(fn, kwargs))
File “apps/frappe/frappe/desk/query_report.py”, line 87, in generate_report_result
res = get_report_result(report, filters) or []
File “apps/frappe/frappe/desk/query_report.py”, line 68, in get_report_result
res = report.execute_script_report(filters)
File “apps/frappe/frappe/core/doctype/report/report.py”, line 142, in execute_script_report
res = self.execute_module(filters)
File “apps/frappe/frappe/core/doctype/report/report.py”, line 159, in execute_module
return frappe.get_attr(method_name)(frappe._dict(filters))
File “apps/frappe/frappe/init.py”, line 1597, in get_attr
return getattr(get_module(modulename), methodname)
File “apps/frappe/frappe/init.py”, line 1327, in get_module
return importlib.import_module(modulename)
File “/usr/lib/python3.10/importlib/init.py”, line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File “”, line 1050, in _gcd_import
File “”, line 1027, in _find_and_load
File “”, line 1006, in _find_and_load_unlocked
File “”, line 688, in _load_unlocked
File “”, line 883, in exec_module
File “”, line 241, in _call_with_frames_removed
File “apps/erpnext/erpnext/assets/report/fixed_asset_register/fixed_asset_register.py”, line 15, in 
from erpnext.assets.doctype.asset.asset import get_asset_value_after_depreciation
File “apps/erpnext/erpnext/assets/doctype/asset/asset.py”, line 26, in 
from erpnext.assets.doctype.asset.depreciation import (
ImportError: cannot import name ‘is_last_day_of_the_month’ from ‘erpnext.assets.doctype.asset.depreciation’ (apps/erpnext/erpnext/assets/doctype/asset/depreciation.py)

### Module

assets

### Version

RPNext: v14.14.0 (version-14)
Frappe Framework: v14.25.1 (version-14)

### Installation method

manual install

**Comment by anandbaburajan** [comment]
@dineshpanchal93 can you please try the latest release and let me know if the bug is still there?

**Comment by dineshpanchal93** [comment]
Hi @AnandBaburajan updated the latest release, bug resolved !!
