### ISSUE TITLE
Sales Order 

### ISSUE THREAD

**Issue by shivashakti** [frappe/erpnext#3398]
Hello, we are apparel producer and have started using ERP Next Actively since past 3 months.
We are facing following issue after creating Sales BOM
1. We created the item for SALES BOM
2. As the apparels are produced in standard sizes of XS, S, M, L, XL & XXL., the customers provides us the ration in which we need to pack the garments. For Example XS-1, S-1, M-2, L-2, XL-1. 
3. While creating the item we ensure that it is "Is Stock Item" as "No" and "Is Sales Item" as "Yes"
4. In spite of all above while making sales BOM and when we create "make material request" from the Sales Order it fetches the data from "BOM".But the data is as per the BOM and not as per the ratio.
5. To clarify further, for example in Size M the customer needs 2 pieces (as per their ratio). Now the BOM should automatically calculate the items in it multiplied by 2. But instead it just pulls the data as it is without multiplying.

Any guidance will be highly appreciated.

**Comment by rmehta** [comment]
@shivashakti could be a bug. We will look into it.

**Comment by nabinhait** [comment]
Could not replicate it. Actually system does not make material request for raw materials at all. It make MR for sales BOM item.

**Comment by shivashakti** [comment]
Thanks Nabin for your revert. Just to re-clarify, the Sales BOM is of FINISHED GOODS and not of Raw Materials.  As mentioned in my original post the system is pulling data from BOM. But the end result is showing same quantity as in BOM. To elaborate this further, for example, the consumption to make 1 shirt is 1.50 cm per Shirt. The customer order stats the ratio as S-1, M-2, L-2, XL-1. This means if we need to produce 1 shirt we need 1.50 cm of fabric. If we want to produce 2 shirts we need 3 meters of fabrics and like wise. So if SALES BOM mentions above ratio, the system while pulling the data from BOM should compute the fabric requirements as per ratio and not constant output like 1.50 cm irrespective of ratio. Hope I have been able to explain you better for in depth understanding of the concern.

**Comment by rmehta** [comment]
Not clear whether you are talking about BOM or Sales BOM. Can you explain your problem in one sentence?

**Comment by PawanMeh** [comment]
If the issues still persists, kindly re-open issue with as per new [guidelines](https://github.com/frappe/erpnext/wiki/Issue-Guidelines)
