### ISSUE TITLE
v11 v12 v13 v14 v15: Delivery Note -> Make Sales Invoice & Sales Invoice -> Get Items From Delivery Note - different functionality

### ISSUE THREAD

**Issue by casesolved-co-uk** [frappe/erpnext#33987]
## Information about bug
There are two ways to create a Sales Invoice from a Delivery Note:

## Operations:
1. Delivery Note -> Make Sales Invoice
2. Sales Invoice -> Get Items From Delivery Note

## Different functionality:
1. Item prices are reset to the price list rate
2. Item prices are copied from the delivery note

## Expected:
Functionality number 2 for both operations

## To reproduce:

Create a Sales Order with items according to a price list & submit
Create a Delivery Note from the Sales Order & submit
Change the price list rates
Create a Sales Invoice using the two operations above
The item rates are different in the invoices

## Details:
The code executed on the client side is significantly different for each case. The main thing that stands out is the Sales Invoice button runs a more specific erpnext JS function "erpnext.utils.map_current_doc" which has special functionality for the items table. The delivery note jumps straight to a generic frappe JS function "frappe.model.open_mapped_doc"
The eventual document creation is done by very similar PY functions: frappe.model.mapper.map_docs and frappe.model.mapper.make_mapped_doc

Delivery note:
```javascript
frappe.model.open_mapped_doc({
	method: "erpnext.stock.doctype.delivery_note.delivery_note.make_sales_invoice",
```

Sales Invoice:
```javascript
erpnext.utils.map_current_doc({
	method: "erpnext.stock.doctype.delivery_note.delivery_note.make_sales_invoice",
```

NOTE: this issue most likely applies to an awful lot of similar document mapping functionality

## Module
accounts, stock, selling

## Version
version-11 to version-15 show the same behaviour

## Installation method
None

## Relevant log output / Stack trace / Full Error Message.
No response

**Comment by dj12djdjs** [comment]
I've noticed this on my production instance some times.

I've just tried on a fresh install and I couldn't replicate it. I'll try again this week.

**Comment by s-aga-r** [comment]
@casesolved-co-uk I am also not able to replicate:

[Screencast from 2023-02-20 11-56-45.webm](https://user-images.githubusercontent.com/63660334/220028959-9b76214f-f618-4c70-a0c3-3fb5edf12e8d.webm)

**Comment by casesolved-co-uk** [comment]
@s-aga-r Firstly, the bug description states:

> Create a Sales Order with items **_according to a price list_** & submit
> Create a Delivery Note from the Sales Order & submit

Your Item prices are 50 and 200, yet your delivery note is 100. So you haven't reproduced properly.

Secondly, this was reported by a customer who had old orders and delivery notes that were fulfilled and invoiced long after they had been created (stock issues), and in the interim, the price list had changed. So I suspect creating everything on the same day is the issue with reproducing it. I'll test more

**Comment by s-aga-r** [comment]
> Change the price list rates 

The initial price list rate was 100, updated after the Delivery Note submission.

> Secondly, this was reported by a customer...

Yes please, try to replicate it in your instance first.

**Comment by s-aga-r** [comment]
@casesolved-co-uk closing this, re-open if replicable.
