### ISSUE TITLE
How can we self-host the wiki or docs from erpnext on our own instances.

### ISSUE THREAD

**Issue by tjomtek** [frappe/erpnext#33993]
**Is your feature request related to a problem? Please describe.**
Want to fork the help docs of erpnext and use the wiki app from frappe in our own instance , similar to frappeframework.

**Describe the solution you'd like**
create a similar site wiki like frappeframework docs

**Comment by dj12djdjs** [comment]
@tjomtek The docs are stored in a database run by frappe.

You can try reaching out to frappe https://frappe.io/contact

**Comment by tjomtek** [comment]
thanks @dj12djdjs got a "dont share" response. thanks anyways.
