### ISSUE TITLE
V14: bom-import forcing an item id (that should be issued by ERPNext itself)

### ISSUE THREAD

**Issue by PatrickDEissler** [frappe/erpnext#33994]
### Information about bug

Hi,

the bom import (new records) forces me to give an Item ID it seems. 
I assume that I can't have it so far, because it is given by the system itself (within the child-table of the bom-items).

I tried following: 
1) Setting the mandatory fields "ID (Item)" and "Item Code (Item)" with the same values: for both I used Item code. 
2) As that did not work, I exported other boms (that I previously set up manually). I received a CSV that included the field of ID (Items) with hashed and automatically assigned values. From this I deleted the "ID (Items)" column, changed the BOM-ID slightly (for re-upload) and tried to import the "new" boms. 
As this (almost original data) did not work either, I assume that there is something wrong with the upload. 

Does anyone know what it can be? 

Thank you and best wishes from Leipzig, Germany
Patrick

### Module

manufacturing

### Version

ERPNext: v14.15.0 (version-14)
Frappe Framework: v14.25.0 (version-14)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Message
Item None not found
Traceback (most recent call last):
  File "apps/frappe/frappe/core/doctype/data_import/importer.py", line 148, in import_data
    doc = self.process_doc(doc)
  File "apps/frappe/frappe/core/doctype/data_import/importer.py", line 242, in process_doc
    return self.insert_record(doc)
  File "apps/frappe/frappe/core/doctype/data_import/importer.py", line 261, in insert_record
    new_doc.insert()
  File "apps/frappe/frappe/model/document.py", line 259, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1040, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 909, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1259, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1241, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 906, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/manufacturing/doctype/bom/bom.py", line 186, in validate
    self.set_bom_material_details()
  File "apps/erpnext/erpnext/manufacturing/doctype/bom/bom.py", line 264, in set_bom_material_details
    ret = self.get_bom_material_detail(
  File "apps/erpnext/erpnext/manufacturing/doctype/bom/bom.py", line 309, in get_bom_material_detail
    item = self.get_item_det(args["item_code"])
  File "apps/erpnext/erpnext/manufacturing/doctype/bom/bom.py", line 222, in get_item_det
    item = get_item_details(item_code)
  File "apps/erpnext/erpnext/stock/doctype/item/item.py", line 1217, in get_item_details
    doc = frappe.get_cached_doc("Item", item_code)
  File "apps/frappe/frappe/__init__.py", line 1091, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 1184, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 74, in get_doc
    return controller(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 106, in __init__
    self.load_from_db()
  File "apps/frappe/frappe/model/document.py", line 149, in load_from_db
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 525, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 493, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 442, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.DoesNotExistError: Item None not found
```

**Comment by FHenry** [comment]
Same problem here I was about create an issue but you made it before, BOM update is no more possible as well.

I think the problem is deeper, if you export a Draft BOM with mandatory import column, just change the BOM ID and remove ID (Item) cell data, you've got the same error. I dig into data_import/importer.py, to doctype/bom/bom.py", line 186, in validate the BOM item data are corrupted (it try to find a None item_code that do not exists into the file). I d'ont understand. I've try to find a PR merge recently that can cause that, but unlikely I miss it. Between Frappe and ERPNext, I tracked change in all file call by the import process, didn't find what wrong.

Hope someone can look a it

**Comment by FHenry** [comment]
I look deeper again and in importer.py, if I print doc before doc = self.process_doc(doc) , so the one that come from payloads :

it invert the scarp items and items .... I don't have and scrap item neither in my import file, neither in my orginal BOM. try to dig why

> {
>     "item": "_Test FG Item",
>     "company": "Wind Power LLC",
>     "item_name": None,
>     "uom": None,
>     "is_active": 1,
>     "is_default": 1,
>     "allow_alternative_item": 0,
>     "set_rate_of_sub_assembly_item_based_on_bom": 1,
>     "project": None,
>     "quantity": 1.0,
>     "image": None,
>     "rm_cost_as_per": "Valuation Rate",
>     "buying_price_list": "Standard Buying",
>     "price_list_currency": None,
>     "plc_conversion_rate": None,
>     "currency": "USD",
>     "conversion_rate": 1.0,
>     "with_operations": 0,
>     "transfer_material_against": "Work Order",
>     "routing": None,
>     "fg_based_operating_cost": 0,
>     "operating_cost_per_bom_quantity": None,
>     "process_loss_percentage": None,
>     "process_loss_qty": None,
>     "operating_cost": None,
>     "raw_material_cost": None,
>     "scrap_material_cost": None,
>     "base_operating_cost": None,
>     "base_raw_material_cost": None,
>     "base_scrap_material_cost": None,
>     "total_cost": None,
>     "base_total_cost": None,
>     "description": None,
>     "has_variants": 0,
>     "inspection_required": 0,
>     "quality_inspection_template": None,
>     "show_in_website": 0,
>     "route": None,
>     "website_image": None,
>     "thumbnail": None,
>     "show_items": 0,
>     "show_operations": 0,
>     "web_long_description": None,
>     "amended_from": None,
>     "__unsaved": 1,
>     "name": "BOM-_Test FG Item-002",
>     "scrap_items": [
>         {
>             "item_code": "_Test FG Item 2",
>             "item_name": None,
>             "stock_qty": 2.0,
>             "rate": 0.0,
>             "amount": None,
>             "stock_uom": "Nos",
>             "base_rate": None,
>             "base_amount": None,
>             "__unsaved": 1,
>         },
>         {
>             "item_code": "_Test Item",
>             "item_name": None,
>             "stock_qty": 1.0,
>             "rate": 100.0,
>             "amount": None,
>             "stock_uom": "Nos",
>             "base_rate": None,
>             "base_amount": None,
>             "__unsaved": 1,
>         },
>     ],
>     "items": [
>         {
>             "item_code": None,
>             "item_name": None,
>             "operation": None,
>             "do_not_explode": 0,
>             "bom_no": None,
>             "source_warehouse": None,
>             "allow_alternative_item": 0,
>             "description": None,
>             "image": None,
>             "qty": None,
>             "uom": "_Test UOM",
>             "stock_qty": None,
>             "stock_uom": "Nos",
>             "conversion_factor": None,
>             "rate": None,
>             "base_rate": None,
>             "amount": None,
>             "base_amount": None,
>             "qty_consumed_per_unit": None,
>             "has_variants": 0,
>             "include_item_in_manufacturing": 0,
>             "original_item": None,
>             "sourced_by_supplier": 0,
>             "__unsaved": 1,
>         },
>         {
>             "item_code": None,
>             "item_name": None,
>             "operation": None,
>             "do_not_explode": 0,
>             "bom_no": None,
>             "source_warehouse": None,
>             "allow_alternative_item": 0,
>             "description": None,
>             "image": None,
>             "qty": None,
>             "uom": "_Test UOM",
>             "stock_qty": None,
>             "stock_uom": "Nos",
>             "conversion_factor": None,
>             "rate": None,
>             "base_rate": None,
>             "amount": None,
>             "base_amount": None,
>             "qty_consumed_per_unit": None,
>             "has_variants": 0,
>             "include_item_in_manufacturing": 0,
>             "original_item": None,
>             "sourced_by_supplier": 0,
>             "__unsaved": 1,
>         },
>     ],
> }
>

**Comment by FHenry** [comment]
I think I've got it scarp item and items (row materials) are labeled in with the same field name
![image](https://user-images.githubusercontent.com/1050053/218588443-3579d19e-2f90-4881-9ee9-6c534b9fac6f.png)

**Comment by agbay72** [comment]
How to fix this one ??

**Comment by FHenry** [comment]
It's already fixed

**Comment by lstbrian** [comment]
how to fix it?

**Comment by PatrickDEissler** [comment]
@lstbrian It is already fixed in V14 somewhen in February.
