### ISSUE TITLE
Item Delayed Report

### ISSUE THREAD

**Issue by Prdpp** [frappe/erpnext#33997]
### Information about bug

In Delayed Item Report,when we give from date and to date and while selecting the sales order it does not shown the given date sales order,it shows some other sales order.

### Module

stock

### Version

ERPNext Version - 12

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
Selected date range sales order is not shown in sales order field of delayed item report.It shown as some other date's sales order.
```

**Comment by deepeshgarg007** [comment]
@Prdpp version-12 is not supported anymore
