### ISSUE TITLE
GST Setting not available in ERPNext v14 Frappe Cloud or Self Hosted

### ISSUE THREAD

**Issue by tejasmarvania** [frappe/erpnext#34006]
### Information about bug

I have created FrappeCloud ERPNext account for trial and trying to set up a company with GST Setting. Unfortunately, GST Setting is not available on the site. Also tried to install self-hosted copy and was also not able to get GST Setting in that.

I have tried solutions given in earlier issue threads like changing the country to other than India and back to India, but still not able to get the fields.

Is there any workaround to trigger GST Setup in Account Module?

### Module

accounts

### Version

Frappe Version - 14.25.1
ERPNext Version - 14.15.1

### Installation method

FrappeCloud

**Comment by mohsinalimat** [comment]
From version-14 you have to use https://github.com/resilient-tech/india-compliance app.
