### ISSUE TITLE
[V5] Failed with error on "Monthly Attendance Sheet"

### ISSUE THREAD

**Issue by tmimori** [frappe/erpnext#3402]
Hi,

I got error bellow on Monthly Attendance Sheet.

- Access to "#query-report/Monthly Attendance Sheet"
- Error dialog shown (as bellow)
- List not loaded ("Loading Report..." remaining)

Is this caused by setting "fiscal_year" and "company" with multibyte charactors?

Could you please confirm this? 

Thank you and Regards,

---
App Versions
```
{
	"erpnext": "5.0.13",
	"frappe": "5.0.15"
}
```
Route
```
query-report/Monthly Attendance Sheet
```
Error Report
```
Traceback (innermost last):
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/app.py", line 51, in application
    response = frappe.handler.handle()
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/handler.py", line 70, in handle
    execute_cmd(cmd)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/handler.py", line 93, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/__init__.py", line 751, in call
    return fn(*args, **newargs)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/desk/query_report.py", line 87, in run
    columns, result = frappe.get_attr(method_name)(frappe._dict(filters))
  File "/home/erpnext/frappe-bench/apps/erpnext/erpnext/hr/report/monthly_attendance_sheet/monthly_attendance_sheet.py", line 12, in execute
    conditions, filters = get_conditions(filters)
  File "/home/erpnext/frappe-bench/apps/erpnext/erpnext/hr/report/monthly_attendance_sheet/monthly_attendance_sheet.py", line 80, in get_conditions
    filters["month"])[1]
  File "/usr/lib/python2.7/calendar.py", line 121, in monthrange
    day1 = weekday(year, month, 1)
  File "/usr/lib/python2.7/calendar.py", line 113, in weekday
    return datetime.date(year, month, day).weekday()
 ValueError: year is out of range
```
Request Data
```
{
	"type": "GET",
	"args": {
		"report_name": "Monthly Attendance Sheet",
		"filters": "{\"month\":\"Jun\",\"fiscal_year\":\"第2期\",\"company\":\"株式会社\"}",
		"cmd": "frappe.desk.query_report.run",
		"_type": "GET"
	},
	"url": "/"
}
```
Response JSON
```
{}
```

**Comment by tmimori** [comment]
Hi,

I confirm this issue does not happen in demo.erpnext.com.
Difference between demo.erpnext.com and my environment looks that fiscal_year is a number or written with multibyte characters.

Should I set fiscal_year as number (e.g. 2015) ?

Thank you and regards,

**Comment by anandpdoshi** [comment]
Can you share the screenshot of the fiscal year record. It should show start date and end date. 

Thanks,Anand Doshi.

**Comment by tmimori** [comment]
Hi @anandpdoshi ,

Thank you for the reply.
Screenshot is as bellow.

![screenshot- mozilla firefox](https://cloud.githubusercontent.com/assets/624831/8006108/9ee242e2-0bcb-11e5-9de8-da4d3f79ef95.png)

Thank you and regards,

**Comment by tmimori** [comment]
Hi @anandpdoshi ,

I made a patch (as bellow) and it works on our environment.

*filters["fiscal_year"]* for *monthrange()* is used as string cast-able into INT, in "hr/report/monthly_attendance_sheet/monthly_attendance_sheet.py" L79.
But it should be string as a name (or key) for DocType "Fiscal Year".

Then I wrote 2 things into this patch:

1. To get Year from "Year Start Date" and "Year End Date" in DocType "Fiscal Year", instead of *filters["fiscal_year"]* .
1. To set Month in the range of "Fiscal Year" with *filters["month"]* .
  * e.g. If "Year Start Date" is set as "2015-04-01", "Year End Date" is set as "2016-03-31" and *filters["month"]* is set as "Jan" ... Year for *monthrange()* should be "2016" instead of "2015".

(On condition that a day number of "Year Start Date" only accepts "01")

Cloud you please confirm it?

```
--- monthly_attendance_sheet.py.org	2015-06-11 17:55:54.002984803 +0900
+++ monthly_attendance_sheet.py	2015-06-11 19:59:40.886015185 +0900
@@ -75,9 +75,21 @@
 	filters["month"] = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov",
 		"Dec"].index(filters["month"]) + 1
 
+        from frappe.model.document import Document
+        fiscal_years = frappe.get_doc("Fiscal Year",filters["fiscal_year"])
+        import datetime
+        year_start = fiscal_years.year_start_date.strftime("%Y")
+        year_end = fiscal_years.year_end_date.strftime("%Y")
+        dt_test = datetime.datetime.strptime(year_end + "-" + str(100+int(filters["month"]))[-2] + "-01", "%Y-%m-%d")
+        date_test = datetime.date(dt_test.year, dt_test.month, dt_test.day)
+        if date_test > fiscal_years.year_end_date:
+          year_target = year_start
+        else:
+          year_target = year_end
+
 	from calendar import monthrange
-	filters["total_days_in_month"] = monthrange(cint(filters["fiscal_year"].split("-")[-1]),
-		filters["month"])[1]
+        filters["total_days_in_month"] = monthrange(cint(year_target),
+                filters["month"])[1]
 
 	conditions = " and month(att_date) = %(month)s and fiscal_year = %(fiscal_year)s"
```
Thank you and regards,

**Comment by anandpdoshi** [comment]
@nabinhait can you look into this?

**Comment by rmehta** [comment]
@tmimori  can you send a pull-request?

**Comment by tmimori** [comment]
@rmehta I sent a pull-request. Could you please confirm it?
