### ISSUE TITLE
General Ledger PDF not showing "Against" Account

### ISSUE THREAD

**Issue by prateekkaramchandani** [frappe/erpnext#34035]
### Information about bug

General Ledger Report not showing "Against" Account when directly printing from browser or downloading as PDF.

![general_ledger](https://user-images.githubusercontent.com/40106895/218412279-32203eb2-fb45-450f-96ac-93fc2840fd57.png)

### Module

accounts

### Version

Frappe Version: v14.25.1
ERPNext Version: v14.15.1

### Installation method

manual install

**Comment by dj12djdjs** [comment]
@prateekkaramchandani The default general ledger report doesn't include this column. You can add it manually when preparing the report.  For further customizations you will have to create your own report that references the GL.
![gl report](https://user-images.githubusercontent.com/29856401/219221592-a45c63d2-16b5-44df-a3da-c7078c6a175e.gif)

**Comment by prateekkaramchandani** [comment]
@deepeshgarg007 Please look into this issue. The Against account in General Ledger Report PDF generated using the general_ledger.html does not show in ERPNext v14.15.1. I also tried in the latest v14 release v14.17.0, the against account is not showing there as well.

The against account does show in ERPNext v14.11.1

![general-ledger](https://user-images.githubusercontent.com/40106895/220956924-0d433323-49dd-46d4-bbe1-29406da89bc3.png)

**Comment by dj12djdjs** [comment]
Closing as per: https://github.com/frappe/erpnext/pull/33639

> Remove against account field from the statement of accounts, accounts are internal for the company and should not be added to it
