### ISSUE TITLE
How to set aply onchage event

### ISSUE THREAD

**Issue by pankajpatel12** [frappe/erpnext#3403]
below is my code i need to if division(here division is check box) is check than show division name textfield and hide field name textfield if uncheck division check box than show field name textfield and hide division name textfield.
how to apply javascirpt code and others

  {
   "fieldname": "division", 
   "fieldtype": "Check", 
   "label": "Division", 
   "permlevel": 0, 
   "precision": ""
  }, 
  {
   "depends_on": "division", 
   "fieldname": "division_name", 
   "fieldtype": "Link", 
   "label": "Division Name", 
   "options": "Division", 
   "permlevel": 0, 
   "precision": ""
  }, 
  {
   "fieldname": "field_name", 
   "fieldtype": "Link", 
   "in_filter": 1, 
   "label": "Field", 
   "options": "Field", 
   "permlevel": 0, 
   "precision": ""
  },

**Comment by rmehta** [comment]
questions on the forum
