### ISSUE TITLE
This is not an issue,it's kind of doubt

### ISSUE THREAD

**Issue by Prdpp** [frappe/erpnext#34033]
### Information about bug

I have attached the image,in that image there is delivery note field filter applied by docstatus as 1.Can i add another filter as date,is that possible?? how can i add on it ???
![Screenshot from 2023-02-13 13-33-49](https://user-images.githubusercontent.com/124979104/218404217-2682a1e5-03a4-486f-94e6-548a6748e303.png)

### Module

stock

### Version

ERPNext Version - 12

### Installation method

None

**Comment by s-aga-r** [comment]
Please refer to the custom report [docs](https://docs.erpnext.com/docs/v12/user/manual/en/customize-erpnext/articles/making-custom-reports).
