### ISSUE TITLE
Error while posting depreciation entries

### ISSUE THREAD

**Issue by barredterra** [frappe/erpnext#34045]
### Information about bug

Since the update to this version, we're getting daily emails with the subject "Error while posting depreciation entries".

The affected **Asset** has "Manual" deprecation enabled for one finance book. It is **already fully deprecated**.

### Module

accounts

### Version

ERPNext: v13.45.1 (version-13)
Frappe Framework: v13.49.2 (version-13)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Asset:


{
  "data": {
    "name": "STO-ASS-2022-00014",
    "owner": "owner@example.org",
    "creation": "2022-11-30 07:50:01.228224",
    "modified": "2023-02-13 00:00:25.093104",
    "modified_by": "Administrator",
    "idx": 0,
    "docstatus": 1,
    "company": "My Company Ltd",
    "item_code": "Ford",
    "item_name": "Ford",
    "asset_owner": "Company",
    "asset_owner_company": "My Company Ltd",
    "is_existing_asset": 0,
    "supplier": "Ford",
    "image": "/private/files/ford.jpeg",
    "naming_series": "STO-ASS-.YYYY.-",
    "asset_name": "Ford",
    "asset_category": "Auto",
    "location": "Schwabm\u00fcnchen",
    "cost_center": "Haupt - MCL",
    "purchase_receipt": "MAT-LS-2022-00168",
    "available_for_use_date": "2014-09-30",
    "gross_purchase_amount": 2000.0,
    "purchase_date": "2014-09-30",
    "calculate_depreciation": 1,
    "opening_accumulated_depreciation": 0.0,
    "number_of_depreciations_booked": 0,
    "depreciation_method": "",
    "value_after_depreciation": 0.0,
    "total_number_of_depreciations": 0,
    "frequency_of_depreciation": 0,
    "maintenance_required": 0,
    "status": "Submitted",
    "booked_fixed_asset": 0,
    "purchase_receipt_amount": 2000.0,
    "depr_entry_posting_status": "Failed",
    "doctype": "Asset",
    "finance_books": [
      {
        "name": "a04c1eadb1",
        "owner": "owner@example.org",
        "creation": "2022-11-30 07:50:01.228224",
        "modified": "2023-01-05 09:50:42.324617",
        "modified_by": "owner@example.org",
        "parent": "STO-ASS-2022-00014",
        "parentfield": "finance_books",
        "parenttype": "Asset",
        "idx": 1,
        "docstatus": 1,
        "finance_book": "MCL",
        "depreciation_method": "Manual",
        "total_number_of_depreciations": 1,
        "frequency_of_depreciation": 1,
        "depreciation_start_date": "2014-10-01",
        "expected_value_after_useful_life": 0.0,
        "value_after_depreciation": 2000.0,
        "rate_of_depreciation": 0.0,
        "doctype": "Asset Finance Book"
      }
    ],
    "schedules": [
      {
        "name": "e9cfee7fe2",
        "owner": "owner@example.org",
        "creation": "2022-11-30 07:56:46.008659",
        "modified": "2023-01-05 09:50:42.324617",
        "modified_by": "owner@example.org",
        "parent": "STO-ASS-2022-00014",
        "parentfield": "schedules",
        "parenttype": "Asset",
        "idx": 1,
        "docstatus": 1,
        "finance_book": "MCL",
        "schedule_date": "2014-10-01",
        "depreciation_amount": 133.33,
        "accumulated_depreciation_amount": 133.33,
        "finance_book_id": "1",
        "depreciation_method": "Manual",
        "doctype": "Depreciation Schedule"
      },
      {
        "name": "fd0c86fba4",
        "owner": "owner@example.org",
        "creation": "2022-11-30 07:56:46.013104",
        "modified": "2023-01-05 09:50:42.324617",
        "modified_by": "owner@example.org",
        "parent": "STO-ASS-2022-00014",
        "parentfield": "schedules",
        "parenttype": "Asset",
        "idx": 2,
        "docstatus": 1,
        "finance_book": "MCL",
        "schedule_date": "2014-10-30",
        "depreciation_amount": 1866.67,
        "accumulated_depreciation_amount": 2000.0,
        "finance_book_id": "1",
        "depreciation_method": "Manual",
        "doctype": "Depreciation Schedule"
      }
    ]
  }
}
```

**Comment by anandbaburajan** [comment]
@barredterra thanks for reporting. I don't see any journal entries linked to the two schedules (not sure how that happened since you said it's already fully depreciated). I also see that value_after_depreciation > expected_value_after_useful_life, so it's not fully depreciated. So I don't understand. Can you elaborate more?

**Comment by barredterra** [comment]
If it's set to "Manual", should the system try to create depreciation entries automatically?

**Comment by anandbaburajan** [comment]
@barredterra if `book_asset_depreciation_entry_automatically` is enabled in Accounts Settings, the system would try create depreciation entries automatically, regardless of the depreciation method. From the docs, the manual depreciation method means: "you can define the Schedule Date and Depreciation Amount for each period.".

I guess it's confusing. I'll think about how to improve the UX and/or the docs.

**Comment by barredterra** [comment]
In that case, I guess the reason for the failure might be that the scheduled date is way in the past and not in any active fiscal year.

**Comment by anandbaburajan** [comment]
@barredterra ah, I just realised that we don't send the traceback of the error in the email. We'll fix that. For now, to be sure, you could also click the `make_depreciation_entry` in the schedule to see what the error is.

To stop getting the emails, you would need to manually link the journal entry/entries to the schedules or you could change the asset's status to `Fully Depreciated`.

**Comment by barredterra** [comment]
> To stop getting the emails, you would need to manually link the journal entry/entries to the schedules or you could change the asset's status to Fully Depreciated.

That is not something a user can do. Manipulating the database is a bad workaround.

I also tried to create the **Asset** a different way to avoid any depreciation entries (existing, fully depreciated Asset). This still resulted in the "depreciation failed" status and notice.

![Bildschirmfoto 2023-02-24 um 13 17 52](https://user-images.githubusercontent.com/14891507/221177552-bde32b3a-6f9e-4719-bd40-03bdd6dd9905.png)

**Comment by anandbaburajan** [comment]
> > To stop getting the emails, you would need to manually link the journal entry/entries to the schedules or you could change the asset's status to Fully Depreciated.
> 
> That is not something a user can do. Manipulating the database is a bad workaround.

I suggested it not as a workaround, but as a solution to the incorrect data issue -- that there should have been JEs linked in the manual schedules but there aren't. However, now I realise that it's not an incorrect data issue, but you trying to create an existing asset in an unexpected way (not sure why).

> I also tried to create the **Asset** a different way to avoid any depreciation entries (existing, fully depreciated Asset). This still caused the "depreciation failed" status and notice.

This is the right way to create an existing asset. However not sure how you're still getting a depreciation failed error for the asset -- the system only tries to post depreciation entries for assets with [calculate_depreciation = 1](https://github.com/frappe/erpnext/blob/version-13-hotfix/erpnext/assets/doctype/asset/depreciation.py#L55).

Can you share more details?

**Comment by barredterra** [comment]
> but you trying to create an existing asset in an unexpected way (not sure why)

Yes, I realize it was the wrong way. Maybe we can add some more validation to prevent wrong entries in the first place?

> However not sure how you're still getting a depreciation failed error for the asset 

Maybe because I used cancel and amend on the "wrong" asset and it copied the failed status to the amended asset?

**Comment by anandbaburajan** [comment]
Ah, will fix that. Thanks.

**Comment by anandbaburajan** [comment]
@barredterra I thought about it and am not sure what to fix here. The only solution I can think of is giving the user option to manually change the `depr_entry_posting_status` in case something like this happens (rarely), but letting them manually change it doesn't seem right.

> Maybe we can add some more validation to prevent wrong entries in the first place?

Yep, definitely. Will think about how to improve the docs too, thanks.
