### ISSUE TITLE
Task bug

### ISSUE THREAD

**Issue by annt2911** [frappe/erpnext#34050]
### Information about bug

In Task module, completed_by is not display even field completed_by still existing in field list

### Module

HR

### Version

V14

### Installation method

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dj12djdjs** [comment]
@annt2911 Please make sure the status of the task is set to "Completed" the completed_by field is only displayed once the status is changed to "Completed".
