### ISSUE TITLE
Remove Credit To Validation in purchase invoice

### ISSUE THREAD

**Issue by pagliaso** [frappe/erpnext#3406]
Hi,

In Spain, customers and suppliers are under same root account, and that I know, I can only set root-type of an account in ERPNext as asset or liability, for the first nodes under the root in the tree of accounts.

The problem I have is that there is a validation for the Credit of a purchase invoice, and if you have chosen that common account for clients and customers not as a liability account, you can't proceed with the purchase. 

The exact message is I am getting is:

Credit To account must be a liability account

If you could remove the validation, or give the possibility to set the type of the account on a non per root basis.

Thanks and regards,

Many thanks and kind regards from Spain,

**Comment by rmehta** [comment]
@nabinhait can you check and remove this validation.

**Comment by rmehta** [comment]
Seems fixed.
