### ISSUE TITLE
I update timesheet progress but task progress not change.

### ISSUE THREAD

**Issue by annt2911** [frappe/erpnext#34064]
### Information about bug

After upgrade to V14, I update timesheet progress but task progress not change.

### Module

HR

### Version

V14

### Installation method

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dj12djdjs** [comment]
### Steps to Reproduce
1. Create Task
2. Create Timesheet
3. Set timesheet item task, and mark timesheet as completed.
4. Save then submit timesheet.

Expected Behavior:  Status of Task (Completed)
Observed Behavior: Status of Task (Working)
