### ISSUE TITLE
Remov Internal Notes Text in ticket

### ISSUE THREAD

**Issue by mabdelmelik** [frappe/erpnext#34078]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mabdelmelik** [comment]
we cant remove Internal Notes Text in ticket

**Comment by dj12djdjs** [comment]
I'm not sure what "Ticket" is... I don't see any doctype in version-13, or version-14.
