### ISSUE TITLE
Payroll Module not showing

### ISSUE THREAD

**Issue by miatano** [frappe/erpnext#34082]
### Information about bug

![image](https://user-images.githubusercontent.com/125456510/219010510-344773b3-982d-448f-8e24-ad4b65005ba9.png)

After upgrading to version 14, payroll module is not visible. Pls advise how to access it.

### Module

HR

### Version

14
14

### Installation method

None

**Comment by gsbaig** [comment]
I thnk you need to nstall hrms app separately and then you will see all the things

**Comment by gsbaig** [comment]
Installation
[Install bench](https://github.com/frappe/bench).

[Install ERPNext](https://github.com/frappe/bench#installation).

Once ERPNext is installed, add the hrms app to your bench by running

$ bench get-app hrms
After that, you can install the hrms app on the required site by running

$ bench --site sitename install-app hrms
