### ISSUE TITLE
Missing Option for Default Print Format

### ISSUE THREAD

**Issue by nakul80** [frappe/erpnext#34099]
### Information about bug

Version 14 doesnt have the option setting as default of a print format in edit properties page.

### Module

accounts, selling

### Version

ERPNext: v14.15.1 (HEAD)
Frappe Framework: v14.25.2 (HEAD)

### Installation method

None

**Comment by rohitwaghchaure** [comment]
@nakul80 Goto Print Format -> you can see the Provision to set print format as Default 

<img width="1315" alt="Screenshot 2023-02-17 at 5 05 37 PM" src="https://user-images.githubusercontent.com/8780500/219642558-190ec119-a131-4f32-97a3-136865836c63.png">

**Comment by nakul80** [comment]
Ok yes so if its already the default no button appears and if its not, only
then will a button appear.

Regards,
Nakul
