### ISSUE TITLE
Move Mpesa Integration to payments app or a separate app

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#34096]
Currently, M-Pesa Express is part of ERPNext, used in POS
Then, we have M-Pesa Express and Customer To Business (C2B), as part of POS Awesome.

Business To Customer (B2C), yet to be implemented.

Thinking, if the integration is moved to Payments app, or separate app?

Then all these can be worked on as a separate app.

**Comment by blaggacao** [comment]
Seems to be part of #37182
