### ISSUE TITLE
Stock>> Batch Details or Batch-Wise Balance History show Incoming Rate

### ISSUE THREAD

**Issue by thida-bcn** [frappe/erpnext#34105]
Is this possible to add "Incoming Rate" for each batch
under Stock >> batch details or
![image](https://user-images.githubusercontent.com/62122640/219551947-371556d0-2ab4-4a8c-9793-bfab43ac6836.png)

Batch-Wise Balance History
![image](https://user-images.githubusercontent.com/62122640/219551909-2634b32f-4cf6-4f20-abb9-52b26ff99391.png)

**Comment by s-aga-r** [comment]
@thida-bcn This won't be possible, as a `Batch` can have items with different `Incoming Rate`.

For Example: 

Batch `ABCD00002` has 200 Qty (100 Qty with `Incoming Rate` as ₹100 and 100 Qty with `Incoming Rate` as ₹50).

![image](https://user-images.githubusercontent.com/63660334/219577745-be5fda1e-8b40-41ef-8dd0-d8b55d6a6579.png)

![image](https://user-images.githubusercontent.com/63660334/219578453-8e0f2749-faca-45bc-b804-d4ac2094602b.png)

For a workaround, you can use Stock Ledger Report with the `Batch No` filter. 

![image](https://user-images.githubusercontent.com/63660334/219579989-2298a0a7-d163-4f49-8e13-ba577037ad51.png)
