### ISSUE TITLE
Total Amount in Sales Invoice Different from Total Amount in Customer Account (General Ledger)

### ISSUE THREAD

**Issue by THEOSKaris** [frappe/erpnext#34120]
### Information about bug

Upon submitting sales invoice, the total amount (revenue + tax) differs from the amount displayed in the customer's account in the General Ledger.

Here is an example of sales invoice number **251/21/USD/00500001**

**SALES INVOICE**
In the sales invoice, the total is **$160,380.12**
![image](https://user-images.githubusercontent.com/67414153/219869397-161b30e1-be17-4950-b6c3-e15979ad19e2.png)

**GENERAL LEDGER**
But the total for the same sales invoice number on the GL is **$159.960.00**
![image](https://user-images.githubusercontent.com/67414153/219869416-59d5d3b0-908e-46fa-8ba2-9d0864f4465e.png)

### Module

accounts

### Version

Frappe Version - v13.49.2 (HEAD)
ERPNext Version - v13.46.1 (HEAD)

### Installation method

None

**Comment by THEOSKaris** [comment]
Here is an observation (keep in mind this invoice is already submitted and paid even):

The total sales value (income + tax) is accurate initially, but strangely ERPNext starts fetching exchange rate:
![image](https://user-images.githubusercontent.com/67414153/219934017-b1502b52-a88e-446a-8645-07bcfd3e8d16.png)

After ERPNext fetches exchange rate, the invoice total changes:
![image](https://user-images.githubusercontent.com/67414153/219934059-4e680aba-9874-4de1-91ff-d52d366a411c.png)

This should not happen when the sales invoice document was already submitted.

**Comment by dj12djdjs** [comment]
related: https://github.com/frappe/erpnext/issues/29840

**Comment by dj12djdjs** [comment]
https://github.com/frappe/erpnext/issues/34680

**Comment by ruthra-kumar** [comment]
Multi Currency refactor https://github.com/frappe/erpnext/issues/34680 should've fixed this in v14 and above.
