### ISSUE TITLE
Image in print formate

### ISSUE THREAD

**Issue by sbkolate** [frappe/erpnext#3412]
If we add images in item, css breaks.
https://demo.erpnext.com/desk#Form/Quotation/QTN-00267
![print format](https://cloud.githubusercontent.com/assets/6648915/7967672/228649ba-0a49-11e5-98f7-ea69b8de12da.png)

https://github.com/frappe/erpnext/blob/develop/erpnext/templates/print_formats/includes/item_table_description.html#L3
```
<div class="pull-left" style="max-width: 38.2%; margin-right: 10px;">
    <img src="{{ doc.image }}" style="max-width: 100%">
</div>
```
This should be
```
<div class="pull-left" style="max-width: 38.2%; margin-right: 10px;">
    <img src="{{ doc.image }}" style="width: 100%">
</div>
```

**Comment by nabinhait** [comment]
@anandpdoshi please check. It does not work in Firefox, check #3412.
