### ISSUE TITLE
POS return is not possible, totals get wrong calculated, message: Paid amount + Write Off Amount can not be greater than Grand Total

### ISSUE THREAD

**Issue by developsessions** [frappe/erpnext#34134]
### Information about bug

In the Point of sale app "app/point-of-sale", click on Toggle Recent Orders, filter the paid orders and make a return.
The article qty is negative which is ok, but the prices and total is positive which should also be negative because its a return.
If we click on the blue Checkout button, we get the dialog window with the message "Paid amount + Write Off Amount can not be greater than Grand Total".

<img width="294" alt="image" src="https://user-images.githubusercontent.com/8073152/219980565-351a3bc3-8352-446c-99b8-a45bd967a67d.png">

The validation occurs in the file sales_invoice.py:
<img width="468" alt="image" src="https://user-images.githubusercontent.com/8073152/219980623-9c126270-7dab-4d83-94be-4c13ec1de633.png">

I do not know what is the cause of the problem, hopefully someone can help or give a hint.

![ErpNextReturnsNotPossible](https://user-images.githubusercontent.com/8073152/219980764-23f5388d-db69-4e62-aee4-265702324f76.gif)

### Module

selling

### Version

ERPNext: v14.x.x-develop () (develop)
Frappe Framework: v15.x.x-develop () (develop)
Payments: v0.0.1 (develop)

### Installation method

docker

**Comment by flamerz** [comment]
I believe this is wrong logic:

because invoice_total in Sales Invoice Return will be negative value so..e.g Paid Amount = Grand Total and we return it in full amount the formula will be:

1400 + 0 - (-1400) > precision or 0.001 (this will return true)

![image](https://user-images.githubusercontent.com/1543290/220989525-f338c443-b44c-4ff2-bcd3-1febe55449ad.png)

solution should be abs(flt(invoice_total))

**Comment by developsessions** [comment]
@flamerz I don't think so, the main problem is, that the Totals like the Grand Total isn't negative. And they should be negative, also on the screen. There must be anywhere a *-1 which invertes this logic, because if the POS Invoice is not marked as a return, it works like intended. The quantity is negative but the sum is positive. What is going on?

**Comment by flamerz** [comment]
@developsessions you mean the Paid Amount isn't negative ? the formula is

invoice_total = grand_total or rounded_total # this will return negative

paid_amount + write_off_amount - invoice_total  > precision or 0.001 

1400 + 0 - ( - 1400 ) > 0.0001

this is what happens in validate_pos function.

but if paid_amount made negative they will need to change the creation GL Ledger too

PS: I believe if validation successful the grand_total will be updated

**Comment by saeedkola** [comment]
Issue still remains when processing returns from sales invoice form with include payment ticked

**Comment by kyradais** [comment]
Is there any solution to ignore the rule? For example, our customer has already paid for both the Item Price and the Delivery Cost, but they can only receive the Item Price amount if they want to return the item.
