### ISSUE TITLE
Opportunity List Status to change upon creation of quotation

### ISSUE THREAD

**Issue by justinlusg** [frappe/erpnext#3415]
Hi there, this is a suggestion/enhancement feedback that the system should change the status of an opportunity from Open to Quotation when a quotation is created by clicking on the "Create Quotation" button from opportunity. 

Currently, our staff have to manually go and change the status in opportunity.

**Comment by neilLasrado** [comment]
Yes the system does exactly the same. can you please recheck. Also test at demo.erpnext.com and let me know if you can replicate.

**Comment by justinlusg** [comment]
It only works when "With Items" is checked and items added before clicking on Create Quotation. If you were to create a quotation with "With Items" checked, the status of the opportunity does not change.

**Comment by neilLasrado** [comment]
@justinlusg I tried the same keeping 'with Items' checked and 'with Items' Unchecked and then making quotations. System Worked fine under both the scenarios. Have you tried replicating the issue at demo.erpnext.com  ( also try reloading the opportunity page once you create a quote.)

**Comment by justinlusg** [comment]
It does not work for me, it only works when 'With Items' checked and the items are carried into the quotation. When it is not checked, after submitting the quotation, the opportunity stays as open.

**Comment by neilLasrado** [comment]
@justinlusg Hey i was able to recreate the issue. Its a design flaw At the moment quotation items are tracked against opportunity. We will give this a thought and update you.

**Comment by justinlusg** [comment]
Noted with thanks! It will be good if it doesn't track against items in opportunity.

**Comment by justinlusg** [comment]
@neilLasrado  Any good news on this feature?

**Comment by sbkolate** [comment]
Some Suggestion:

1) after creating sales order, Opportunity Status in "Converted"
When Opportunity Status is "Converted" User can not edit Opportunity.
Currently on updating converted opportunity it gives error message
"Status cannot be "Converted". It should be one of "Open", "Quotation", "Lost", "Replied", "Closed""
Need some meaningful message.

2) Forward Linking:
In Opportunity form, If we open Menu -> Links, this should show link to Quotation and Sales Order.
Currently this link is shown on Quotation. But links are not working in Opportunity form.

**Comment by justinlusg** [comment]
why not just make users create quotations instead of having "with items" in opportunity? There can be a few quotations for each opportunity (e.g. one customer is keen on buying a service now but after a few discussions there might be more quotations that are generated from the same opportunity)

**Comment by umairsy** [comment]
> Currently this link is shown on Quotation. But links are not working in Opportunity form.
Fixed in version 8.

> why not just make users create quotations instead of having "with items" in opportunity?

You can very much create Quotation directly, without opportunity reference. Creating opportunity is optional.

> Hi there, this is a suggestion/enhancement feedback that the system should change the status of an opportunity from Open to Quotation when a quotation is created by clicking on the "Create Quotation" button from opportunity.

Already implemented, hence closing issue.
