### ISSUE TITLE
RFQ - Incorrect Submit your Quotation URL in Email

### ISSUE THREAD

**Issue by Govind-Jangid** [frappe/erpnext#34166]
### Information about bug

![image](https://user-images.githubusercontent.com/63184660/220362611-e9a3e5c4-af17-496f-a596-e1f83f695cef.png)

After click on Submit your Quotation it redirects to the :
https://sitename.com/app/request-for-quotation/PUR-RFQ-2023-00001

Which should be:
https://sitename.com/rfq/PUR-RFQ-2023-00001

### Module

buying

### Version

ERPNext: v14.14.0 (version-14)
Frappe Framework: v14.24.0 (version-14)

### Installation method

manual install

**Comment by dj12djdjs** [comment]
easy fix, just needs to be modified here: https://github.com/frappe/erpnext/blob/a06d24037b79887662ed2ffaa3c5bde55c3590dd/erpnext/buying/doctype/request_for_quotation/request_for_quotation.py#L116

**Comment by s-aga-r** [comment]
> easy fix, just needs to be modified here:
> 
> https://github.com/frappe/erpnext/blob/a06d24037b79887662ed2ffaa3c5bde55c3590dd/erpnext/buying/doctype/request_for_quotation/request_for_quotation.py#L116

@dj12djdjs sending PR?

**Comment by dj12djdjs** [comment]
> @dj12djdjs sending PR?

@s-aga-r I wasn't planning on it.
