### ISSUE TITLE
Calendar displaying incorrectly when assigning to-do

### ISSUE THREAD

**Issue by justinlusg** [frappe/erpnext#3416]
![image](https://cloud.githubusercontent.com/assets/12539216/7977377/d5fa3c5e-0abc-11e5-871a-7a7960fedb30.png)

The calendar is appearing behind the to-do and not being able to use.

**Comment by anandpdoshi** [comment]
Fixed via https://github.com/frappe/frappe/commit/20642a0f379f0559d4515ab397b43705aed19d0e
