### ISSUE TITLE
Different Behavior when we use 'Duplicate' action and use 'Copy to Clipboard' for copying Item

### ISSUE THREAD

**Issue by jeshani** [frappe/erpnext#34188]
### Information about bug

- Create Item
![image](https://user-images.githubusercontent.com/56191568/220901287-b2f88a53-068a-417f-b973-98cace689779.png)

- Duplicate Item -> Change the code and name -> Save -> Works absolutely fine. 
![image](https://user-images.githubusercontent.com/56191568/220901600-119d701b-774d-45ba-9811-2bea98caf28a.png)

- Now Copy to clipboard the item and paste on screen -> Change the Item code and name -> it throws the error as below.
![test](https://user-images.githubusercontent.com/56191568/220905043-25f7b33b-a1ed-4c35-a814-3569af028373.gif)

### Module

stock

### Version

Frappe Version - v14.24.0 (version-14)
ERPNext Version - v14.14.0 (version-14)

### Installation method

FrappeCloud

**Comment by jeshani** [comment]
When we copy to clipboard and paste the Item,
the parameter **__newname** carrying the Item_code of item.
![image](https://user-images.githubusercontent.com/56191568/220908949-1618ac0b-5c01-442c-942c-435ca94451c8.png)

**Comment by phot0n** [comment]
they're both separate features, with separate intentions behind them. 
copy to clipboard was added as a developer centric feature for copying things from one site to another whereas duplicate is a user centric feature for duplicating a document on the same site.

closing this.
