### ISSUE TITLE
Merge Lead form into Contact form

### ISSUE THREAD

**Issue by anandpdoshi** [frappe/erpnext#342]
Lead and Contact forms have similar information. 

They can be merged and when a lead is converted to customer, the contact need just be linked to the customer eliminating duplication of records.

**Comment by betabank** [comment]
Yes, this would be the solution, but please keep in mind that may be a contact with the same email assigned already to a customer and the communications should be merged. We explained it in #3258

**Comment by cgpurbaugh** [comment]
@rmehta You closed the related issue, I think this can be closed as well.
