### ISSUE TITLE
Wrong Status in Material Request Workflow (Type: Material Issue)

### ISSUE THREAD

**Issue by kirthiss** [frappe/erpnext#3420]
In the material request workflow for type - Material Issue, the material request goes to status 'Ordered' when the material is issued. It should actually go to the status 'Issued'.

**Comment by neilLasrado** [comment]
We will fix this. Thanks for bringing it to our notice.

**Comment by kirthiss** [comment]
Thanks. Pardon my ignorance - I'm new to ERPNext and on trial mode. How often do you release the fixes? I just wanted to know when this fix might get released...Thanks.

**Comment by anandpdoshi** [comment]
After evaluating an issue, if we find that it requires only a limited change, we release it in a time frame of between a day or a week depending on our workload. Else it could take a lot more time if the changes are widespread. 

Thanks,Anand Doshi.

**Comment by neilLasrado** [comment]
This Issue has been Fixed.
