### ISSUE TITLE
Add filed of child table to listview

### ISSUE THREAD

**Issue by T941** [frappe/erpnext#34217]
### Information about bug

![image](https://user-images.githubusercontent.com/51939134/221463071-c0a159a4-60f7-4ae4-bc2c-081029795ec0.png)
in v13-beta I was able to do this to filter the user_email field in the child table but this no longer works in v14. Someone please help me with this on v14. Thanks.

### Module

other

### Version

14

### Installation method

None

**Comment by s-aga-r** [comment]
@T941 For help-related queries, please go to:

Frappe: https://t.me/frappeframework
ERPNext: https://t.me/erpnext_public
