### ISSUE TITLE
Connections (Links) and Costing and Billing Data in Project DocType not showing correct values when Project is on the Items Child Table of the Connected DocTypes

### ISSUE THREAD

**Issue by pibico** [frappe/erpnext#34211]
### Information about bug

1.- First issue is on the Project Connections
Purchase Order, Purchase Receipt, Purchase Invoice on Purchase Group, Sales Order, Delivery Note and Sales Invoice on Sales Group are not showing any amount if Project Links are Internal Links (on the Items Child Table) and not on the DocType Form.

2.- Second issue is on Costing and Billing fields
Total Purchase Cost (via Purchase Invoice) and Total Sales Amount (via Sales Order) or Total Billed Amount (via Sales Invoices) are not showing any amount if Project Links are Internal Links (on the Items Child Table) and not on the DocType Form.

How to replicate the issue on Purchase or Sales:
1.- Create two Projects
2.- Create a Purchase Order, Purchase Receipt, Sales Order or whatever DocType that can be linked to the Project and not fill the Account Dimensions Project on main form, leaving it blank.
3.- Create two rows on Items Child Table, and on each one fill the Account Dimension with one of the two created Projects (two lines and two different projects).
4.- Submit the Purchase Order, Receipt, …
5.- If you open either each of the Projects, no connections are shown on the Dashboard, even though there is a connection through Items child table.
6.- MoreOver, the Total Costing and Billing are not showing valid numbers if the project is an internal link.

### Module

projects

### Version

Frappe Framework: v13.41.1 (version-13)
ERPNext: v13.39.0 (version-13)

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
Please check it: https://frappeframework.com/docs/user/en/basics/doctypes/actions-and-links

How it worked so please check the dashboard structure of Item:
https://github.com/frappe/erpnext/blob/develop/erpnext/stock/doctype/item/item_dashboard.py

https://www.youtube.com/watch?v=CExg2ID-zmg

https://www.youtube.com/watch?v=L4Wq1HkVQL0


**We no longer provide support for version 13 or older.**

Kindly upgrade to version 14 or 15.

Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!
