### ISSUE TITLE
Trial Balance report is showing the amount in company currency, not account currency

### ISSUE THREAD

**Issue by shirleymayadewi** [frappe/erpnext#34216]
### Information about bug

This is very confusing because Trial Balance is showing USD account in company currency (CAD), instead of in USD. However, when you open General Ledger for that same USD account, it's correctly showing all the transactions in USD. Could a fix be developed so that Trial Balance is always showing the amount in the account currency? 

### Module

accounts

### Version

ERPNext version 13

### Installation method

None

**Comment by deepeshgarg007** [comment]
@shirleymayadewi You must have set some presentation currency in the filters, closing this, not a valid big

**Comment by dgehriger** [comment]
@deepeshgarg007 : why was this issue closed? In ERPNext v14 (14.13.0), too, reports all list amounts in the company currency, not the account currencies.

For tax reporting, the Trial Balance and Balance Sheet (including in the Consolidated Financial Statement) need to list account balances in both, the company currency, but also the account currency. 

If there is a magic "presentation currency in the filters", please indicate where to deactivate this filter. I have not found any reference to such a filter anywhere, and I am sure that I have not set any such filter actively.
