### ISSUE TITLE
Accounting Point of sale After completing an order

### ISSUE THREAD

**Issue by moneebshammout** [frappe/erpnext#34248]
1-After completing an order in accounting/point of sale then click on new order this error is logged to the console

![pos_after_create_order](https://user-images.githubusercontent.com/65316423/221862053-bdb9f7af-5037-462a-9e1f-904343fc2096.PNG)
 
2- then if you click on any item this error is logged to the console
![click_on_item_pos](https://user-images.githubusercontent.com/65316423/221862416-90274360-8569-48d6-ad2f-14c8904b8549.PNG)

**Comment by Nihantra-Patel** [comment]
Hi @moneebshammout,

Everything is working fine. No problems were encountered in versions 14 and 15.

Please check it.


https://github.com/frappe/erpnext/assets/141945075/dcab3a10-9b69-4b95-81aa-0fa207f67f20


Thank You!
