### ISSUE TITLE
Journal Voucher

### ISSUE THREAD

**Issue by robertbecht** [frappe/erpnext#3424]
When Bank voucher is selected automatically the bank account is selected. As communicated before would be nice if cash voucher is selected automatically cash account is selected.

Made a advance payment against a PO. Typed supplier name and YES, GREAT the PO's for this supplier came as a droplist!!! BUT: sorting started in 2012 and due to the length the required PO was not listed, so I had to go back to PO to see number. IF the list is sorted date wise, latest on top the functionality is perfect!!

Finally, a small usuability improvement. Non accounts probably always have to think about whether to debit or credit. To maintain the clean look of the screens a small pop up with the rules of the game:
 For example
If you buy merchandize and you pay supplier your Creditor account is debitted.

robert

**Comment by nabinhait** [comment]
Fixed
