### ISSUE TITLE
POS - Income Account

### ISSUE THREAD

**Issue by dhav-d** [frappe/erpnext#3425]
During a POS transactions, the default income account is take as per POS Profile, I believe the Item Income Account should be take as default. As we are selling a service item as well as sales item both should be registered respectively as the item default income account, which currently it does not allow

**Comment by rmehta** [comment]
@dhav-d we have had users asking otherwise. If you want to use Item account, just keep the pos account blank.

**Comment by dhav-d** [comment]
income account is mandatory to select! :(
also there is Cash/Bank Account mandatory- what do we select cash or bank? - payments could be made via cards(bank) or in cash
