### ISSUE TITLE
A minor correction required: Text color 

### ISSUE THREAD

**Issue by ajiragroup** [frappe/erpnext#34255]
### Information about bug

In this sales funnel, the texts to the right are dark in color which is not good for dark theme.

![image](https://user-images.githubusercontent.com/108009061/222054772-63b9f94f-6c8a-42dc-a454-d11ec96b8357.png)

### Module

CRM

### Version

erpnext 14.12.1
frappe 14.22.1
hrms 1.0.0
payments 0.0.1

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
Hi @ajiragroup,

Issue has been resolved.

Thank You!
