### ISSUE TITLE
HI I am not able to see the manufacturing module in my system. I am using v12.31.0 (HEAD)

### ISSUE THREAD

**Issue by gsahani44** [frappe/erpnext#34256]
### Information about bug

HI I am not able to see the manufacturing module in my system. I am using v12.31.0 (HEAD)

### Module

manufacturing

### Version

I am using v12.31.0 (HEAD)

### Installation method

None

**Comment by nihantra** [comment]
Hi @gsahani44,

If didn't check and if you did not enable the manufacturing module then apply it.
Please go to the Domain Setting and enable the manufacturing and save it.

![image](https://user-images.githubusercontent.com/99652762/222127246-689e950f-ad8f-4fda-9144-23e6d2bf143c.png)

Then reload (Ctrl + Shift + R) your system and check it.

Thank You!
