### ISSUE TITLE
POS - taxes

### ISSUE THREAD

**Issue by dhav-d** [frappe/erpnext#3426]
the POS should allow us to see tax break up of the Sales Invoice before proceeding for 'Pay' button.
Also it should allow us to have multiple taxes as per the items selected and not as per the profile understanding. 
We sell service as well as goods. Our invoice should have Items of service and then service tax, then items of goods and sales tax and then grand total. 

The item tax should also have priority over POS profile tax selection. Please help

**Comment by system19** [comment]
You can add different Sales or Service taxes on a per item basis. This over rides the POS profile tax selection.
