### ISSUE TITLE
Support Cases Created by Email Not Capturing body of Email for Description

### ISSUE THREAD

**Issue by ocodan** [frappe/erpnext#34271]
### Information about bug

When submitting a support ticket through email to ERPNext Support module the support ticket is not capturing the body of the email and putting it in the description of the incident, it is only capturing the subject line of the email and putting it in the subject line of the ticket.  Instead, it is putting the entire body of the email into the document history at the bottom of the incident.  How do we have ERPNext put the body of the email into the ticket description in ERPNext Support? 

### Module

support

### Version

Frappe Framework: v14.22.1 (HEAD)
ERPNext: v14.12.1 (HEAD)

### Installation method

manual install

**Comment by deepeshgarg007** [comment]
@ocodan If you have bought any support plan for your site please reach out to our executives and they will surely help you, closing this ticket
