### ISSUE TITLE
Can't Set the Unrealized Gain/Loss Exchange Account Because It Is Requiring a Profit and Loss Account

### ISSUE THREAD

**Issue by ocodan** [frappe/erpnext#34272]
### Information about bug

Unrealized Gains/Losses Due to Foreign Exchange are recorded in the Equity section of the Balance Sheet for US GAAP purposes.  However, I can't set the GL account as the default GL account for this type of revaluing transaction because it will only allow me to enter a Profit and Loss (Filtered for Expense, Income) Account.  How do I fix this?

![image](https://user-images.githubusercontent.com/65365208/222243515-95c9f34c-f153-470f-8682-20f6ef31e424.png)

### Module

accounts

### Version

Frappe Framework: v14.22.1 (HEAD)
ERPNext: v14.12.1 (HEAD)

### Installation method

manual install

**Comment by deepeshgarg007** [comment]
@ocodan Usually gain/loss account is a profit and loss account hence the filter, you can anyway copy and past other account name as well and the system will accept as there is no server-side validation for this
