### ISSUE TITLE
Rejected Serial number issue in Purchase Receipt

### ISSUE THREAD

**Issue by Gaurang1979** [frappe/erpnext#34290]
### Information about bug

At the time generating purchase receipt if serial numbers are entered in both accepted and rejected serial number. When creating return receipt rejected serial numbers are not accepting.

### Module

buying

### Version

Frappe - latest aa using frappe cloud 
Erp version 14

### Installation method

FrappeCloud

**Comment by deepeshgarg007** [comment]
@Gaurang1979 Please share more details about the issue with examples, what error did you get, what was the data entered.

**Comment by Gaurang1979** [comment]
1. Placed purchase order for products which has serial numbers. Total 1
item and 5 qty order placed.
2. Out of 5 qty, 3 qty is accepted and 2 are rejected. At the time of
creating purchase receipt I entered 3 serial numbers in accepted serial
number column [in item table edit] and 2 serial numbers in rejected column.
3. Now i have to generate return invoice from create return button. After
clicking purchase return page is opened with correct purchase receipt
number.
4. Now for returning 2 qty i have to write -2 in accepted qty as mentioned
in help document. At the time of submit system is showing error in both
cases a. writing rejected serial number in accepted warehouse column b.
writing rejected serial number in rejected warehouse column.

There is bug in system as with partial rejected qty return purchase receipt
not able to generate. System is not accepting serial numbers of rejected
items [serial number entered in rejected items at the time of purchase
receipt].
