### ISSUE TITLE
Attribute Error while opening Point Of Sale - v13

### ISSUE THREAD

**Issue by jabir-tridz** [frappe/erpnext#34303]
### Information about bug

![Screenshot from 2023-03-05 01-01-08](https://user-images.githubusercontent.com/88030376/222925348-c71b556d-97f4-465f-bb6c-f90952e8e0db.png)

Facing Attribute Error while opening Point of Sale. The items aren't loading and can't checkout and complete POS invoices after **ERPNext 13.49.0** update. I have also tried the latest ERPNext update as well and still facing this issue. ### " AttributeError: 'ProductBundleItem' object has no attribute 'stock_qty' "

### Module

selling

### Version

Frappe version - 13.50.3
ERPNext version -  13.49.0

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
File "apps/erpnext/erpnext/selling/page/point_of_sale/point_of_sale.py", line 137, in get_items
    item_stock_qty, is_stock_item = get_stock_availability(item_code, warehouse)
  File "apps/erpnext/erpnext/accounts/doctype/pos_invoice/pos_invoice.py", line 639, in get_stock_availability
    return get_bundle_availability(item_code, warehouse), is_stock_item
  File "apps/erpnext/erpnext/accounts/doctype/pos_invoice/pos_invoice.py", line 655, in get_bundle_availability
    max_available_bundles = available_qty / item.qty
AttributeError: 'ProductBundleItem' object has no attribute 'stock_qty'
```

**Comment by dj12djdjs** [comment]
https://github.com/frappe/erpnext/issues/34302
