### ISSUE TITLE
Inconsistent and incorrect Primary Contact List shown while opening opportunity directly or from a prospect

### ISSUE THREAD

**Issue by dlarocheRolle** [frappe/erpnext#34307]
### Information about bug

Hi,

I am discovering ERPNext and i have found an issue with Opportunities linked to a prospect. Screenshot below

I log in with a restricted user (same behaviour with an admin user)

I open an opportunity from the list of opportunity (this opportunity is linked to a prospect). For Primary Contact, i can select any contact (not linked with the organization of the opportunity). Screen shot below

![Opportunity_Direct](https://user-images.githubusercontent.com/46819406/223042689-9ac408d1-48c5-4d41-a326-a3565e5c3d84.png)

Now, i open the prospect and it shows the list of contacts

![ProspectAddressAndContact](https://user-images.githubusercontent.com/46819406/223042875-bf41690b-7e44-464a-835c-b4cf82d9c865.png)

I go to the Opportunities tab

![Prospect-Opportunities](https://user-images.githubusercontent.com/46819406/223043005-db9e54c7-33d6-42ec-8887-e097208d3108.png)

I open the Opportunity from the tab and it shows a filtered list of contact that does not contain the contact of the prospect

![ProspectOpportunityDisplay](https://user-images.githubusercontent.com/46819406/223043124-a9793b41-2eda-4d80-9df0-a2017b26483e.png)

I am unable to figure out whether this is a bug or something wrong that i am doing.

Thanks
Didier

### Module

CRM

### Version

ERPNext: v14.16.1 (version-14)

Frappe Framework: v14.25.4 (version-14)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
none
```

**Comment by deepeshgarg007** [comment]
Fixed, closing this issue
