### ISSUE TITLE
Page lower-deduction-certificate not found

### ISSUE THREAD

**Issue by kvt** [frappe/erpnext#34309]
### Information about bug

Page lower-deduction-certificate not found

### Module

accounts

### Version

```
bench version

erpnext 14.17.4
frappe 14.26.3
hrms 14.1.0
india_compliance 14.2.1
payments 0.0.1
```

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

Not found

Page lower-deduction-certificate not found

The resource you are looking for is not available

**Comment by deepeshgarg007** [comment]
@kvt Please add more details and reopen the issue, looks like a site-specific issue

**Comment by kvt** [comment]
@deepeshgarg007 tried creating new site and still facing same issue.

Steps to reproduce:

1. Go to doctype Lower Deduction Certificate
2. click on "Go to Lower Deduction Certificate List" Button
