### ISSUE TITLE
Company Access List Corrupted (see screenshot) 

### ISSUE THREAD

**Issue by ocodan** [frappe/erpnext#34318]
### Information about bug

Company List corrupted (see screenshot).  When I click on All Companies it just displays another All Companies and the sample company.   Created new user and that user can see Company List fine but original user can't - get's the same error.  So it is a user corruption?

Screenshot:
![image](https://user-images.githubusercontent.com/65365208/223219858-933b9444-f72f-4709-a0da-b2f0526e683b.png)

### Module

other

### Version

14.22.1
14.12.1

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
No error message.
```

**Comment by deepeshgarg007** [comment]
@ocodan This could be your site-specific issue, right there is not enough information for further investigation. Please add more details and reopen the issue
