### ISSUE TITLE
Subcontracting Order Qty Issue

### ISSUE THREAD

**Issue by sowndharya998** [frappe/erpnext#34317]
### Information about bug

Raise the Production Plan against the sales order 
![Screenshot 2023-03-06 at 9 28 42 PM](https://user-images.githubusercontent.com/75109236/223168682-425dfc34-07b0-46a1-b4e3-d9463218df92.png)
The production plan have an subassembly item it has 2 qty then it should be a Subcontract type

Then raise a purchase order against the production plan
![Screenshot 2023-03-06 at 9 29 13 PM](https://user-images.githubusercontent.com/75109236/223190222-2bcadb13-60e8-4afd-a531-1fa5b4c2f16d.png)

Then make an Subcontract order it have only one finished qty but we have to finish two qty 
![Screenshot 2023-03-06 at 9 29 43 PM](https://user-images.githubusercontent.com/75109236/223190579-c01c31c5-5b05-4268-8fd2-0cb845a7da11.png)
![Screenshot 2023-03-06 at 9 30 16 PM](https://user-images.githubusercontent.com/75109236/223190685-123a5d84-7c06-46af-bec9-e92c88896f59.png)
Then the finished  goods item qty must be 2 because the subassembly qty is 2 but it showing 1 qty

### Module

buying

### Version

ERPNext: v14.14.0 (version-14)

Frappe Framework: v14.24.0 (version-14)

### Installation method

None

**Comment by s-aga-r** [comment]
@sowndharya998 

Unable to replicate:

Purchase Order (Qty = 2, Finished Good Item Qty = 2):

![image](https://user-images.githubusercontent.com/63660334/224275313-9216e8ed-b91e-400f-a306-9fb1f2897d0d.png)

![image](https://user-images.githubusercontent.com/63660334/224275413-d0dd5589-662a-4cca-bb16-8244446a2464.png)

Subcontracting Order:

![image](https://user-images.githubusercontent.com/63660334/224275613-21ecb118-c3a6-4984-825e-eb2df784a6e0.png)

**Comment by s-aga-r** [comment]
@sowndharya998 

https://user-images.githubusercontent.com/75109236/223190579-c01c31c5-5b05-4268-8fd2-0cb845a7da11.png

You have to set the Finished Good Item Qty manually in Purchase Order as there is no mapping for Service Item and Finished Good Item Qty.
