### ISSUE TITLE
Publishing item fields on website

### ISSUE THREAD

**Issue by rsdstephen** [frappe/erpnext#3431]
It would be great if there was more flexibility around displaying Item information on the website. Either the ability to pull Item fields into the website layout or the ability to add more html elements. Currently all information appears under Description making editing on multiple items very difficult.

**Comment by anandpdoshi** [comment]
There is a table called website item specification that you can use for this.

**Comment by rsdstephen** [comment]
Hi

I have tried this but the fields I've added are not showing up in the
website display.

Regards
Roy

**Comment by rsdstephen** [comment]
Sorry, figured it out.
Thank you!

**Comment by rsdstephen** [comment]
Is this limited to Label and Description?
Editing the Item Website Specifications form does show additional fields in the table under Item but these do not pull through onto the website. Is there a way?
If not, then could Description at least be a Text Editor to allow for more customization? I know html works in the Description box but it is difficult to edit as text.

**Comment by rmehta** [comment]
Do you have a specific suggestion? Or can I close this?

**Comment by rsdstephen** [comment]
I have resolved my problem via Web specifications so you can close it.
