### ISSUE TITLE
Search filter In Pos

### ISSUE THREAD

**Issue by Nehamirpuri** [frappe/erpnext#3432]
In Pos one can search on basis of item code,item name but if search can be done on basis of item group it would make it more easier and convenient.

**Comment by anandpdoshi** [comment]
You can search by item group too. Did you try typing item group in it? It will show all items in that item group.

**Comment by Nehamirpuri** [comment]
No it does not work I have an item group Curtain Fabric but it only
filtered products which had the text "curtain fabric" in its Item name.
For your reference I have attached screenshot of the same.

On Mon, Jun 8, 2015 at 4:56 PM, Anand Doshi <notifications@github.com>
wrote:

> You can search by item group too. Did you try typing item group in it? It
> will show all items in that item group.
>
> Sent from my phone
>
> > On 08-Jun-2015, at 6:43, Nehamirpuri <notifications@github.com> wrote:
> >
> > In Pos one can search on basis of item code,item name but if search can
> be done on basis of item group it would make it more easier and convenient.
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/frappe/erpnext/issues/3432#issuecomment-109956781>.
>



-- 
Warm regards,
Neha,
support@boacasa.com
9665685781/8805336565

**Comment by Nehamirpuri** [comment]
Has the issue been solved or it cannot be viewed.
