### ISSUE TITLE
Auto-complete values are not rendering properly on modal

### ISSUE THREAD

**Issue by nabinhait** [frappe/erpnext#3433]
![screen shot 2015-06-08 at 4 15 42 pm](https://cloud.githubusercontent.com/assets/836784/8033207/10996700-0dfa-11e5-962b-a1d66f477ece.png)

@anandpdoshi The issue is related to your fix for date-picker https://github.com/frappe/frappe/pull/1148.

**Comment by anandpdoshi** [comment]
Argh. Should've tested this after the fix 😞.
