### ISSUE TITLE
Inventory Dimension fields are still retained in the stock documents even if the inventory dimension is deleted

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#34347]
### Information about bug

Create inventory dimension
Then delete the inventory dimension, the fields are still retained in the stock doctypes

### Module

stock

### Version

ERPNext: v14.18.1 (HEAD)
Frappe Framework: v14.26.4 (HEAD)

### Installation method

FrappeCloud

**Comment by rohitwaghchaure** [comment]
This is fixed
