### ISSUE TITLE
Multi Currency Payment Entry for Purchase Order/Sales Order

### ISSUE THREAD

**Issue by Shubee10** [frappe/erpnext#34345]
### Information about bug

In the current system when we create a Multi currency Payment Entry against a Sales order/Purchase Order it is considered as an advance payment like mentioned below in the screenshot

![image](https://user-images.githubusercontent.com/104073878/223635179-94d3a7ee-6370-4742-af04-5d4797364a0b.png)

While creating a Payment Entry the system creates and Advance payment against it 

![image](https://user-images.githubusercontent.com/104073878/223637254-51b3c2f5-07b0-43f4-a1dd-e4461025323d.png)

As it is a multi currency payment entry the system will create an Exchange Gain/Loss entry for the difference amount

![image](https://user-images.githubusercontent.com/104073878/223637424-5af36abc-54bb-49b1-80b3-4633c9d519b4.png)

As per the business logic any accounting entry should not be booked against any Purchase Order or Sales Order

### Module

accounts

### Version

ERPNext: v13.49.3 (HEAD)

ERPNext Support: v0.0.3 (HEAD)

Frappe Framework: v13.50.3 (HEAD)

### Installation method

None

**Comment by dj12djdjs** [comment]
I'm not sure about this.

@Shubee10 Could you provide any references why accounting entries should not be booked against PO/SO?

CC: @nextchamp-saqib @deepeshgarg007 @ruthra-kumar

**Comment by ruthra-kumar** [comment]
Exchange Gain/Loss for Advance payments against Multi-currency Sales/Purchase orders will not be booked.
https://github.com/frappe/erpnext/pull/35061
