### ISSUE TITLE
Sale team on sales order documents is cleared unless there's a sales team attached for the customer

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#34346]
### Information about bug

- Create a customer, don't attach any sales team to the customer
- Create a sales order for the customer above, attach a sales team for this sales order, sales team is not saved for this sales order
- Sales team saves on sales order if the customer has the sales team attached

### Module

selling

### Version

ERPNext: v14.18.1 (HEAD)
Frappe Framework: v14.26.4 (HEAD)

### Installation method

FrappeCloud

**Comment by rtdany10** [comment]
[Fixed by #34376 ](https://github.com/frappe/erpnext/pull/34376)
