### ISSUE TITLE
Include Inventory Dimension fields in Landed Cost Voucher/Item

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#34348]
Include Inventory Dimension fields in Landed Cost Voucher/Item

**Comment by agritheory** [comment]
~~Also should be included in Stock Reconciliation.~~ I am interested in working on this feature, if the team is willing to backport it to version 14. 

Edit: it _is_ implemented for Stock Reconciliation

**Comment by muchai** [comment]
It is.

And not applicable to Landed Cost Voucher, since it updates existing stock ledgers
