### ISSUE TITLE
Item rate has been updated to zero as Allow Zero Valuation Rate is checked for item xxxx

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#34354]
### Information about bug

Happens when doing a stock entry of type receipt, and you have set allow zero valuation.

Thing is, the message pops up for each line, and one has to wait a bit since the messages hide the action buttons.

Just 10 item lines, and the message is annoying mostly.

### Module

stock

### Version

ERPNext: v14.18.1 (HEAD)
Frappe Framework: v14.26.4 (HEAD)

### Installation method

FrappeCloud

**Comment by s-aga-r** [comment]
@muchai any expected solution for this?

**Comment by muchai** [comment]
Maybe, just one message, not sure. The message per line though, a bit not user friendly.
