### ISSUE TITLE
While doing the Import Purchase, the Figures is not capturing in the GSTR3B Report under the Sections -(A) ITC Available - Import of goods

### ISSUE THREAD

**Issue by JitendraSAW** [frappe/erpnext#34351]
### Information about bug

Frappe Team,
When we are recording the Purchase Invoice which is for Import Transactions, We are not getting an option as "Import of Goods"under the GST Details Sections
![image](https://user-images.githubusercontent.com/80260184/223647025-d2635db5-51e4-4432-878a-56b781d61a4c.png)
<img width="856" alt="image" src="https://user-images.githubusercontent.com/80260184/223647664-9297a340-24bb-457d-bfec-5f3099125e8e.png">

And because of that it is not showing the under the Import of Goods under the GSTR3B Report.

Kindy updates us or advice if any thing or points is missing from our end

### Module

accounts

### Version

![image](https://user-images.githubusercontent.com/80260184/223647762-1a167ff3-963a-41d1-93f5-dcbffb6d6e92.png)

### Installation method

FrappeCloud

**Comment by dj12djdjs** [comment]
Hi @JitendraSAW

This looks to be related to India compliance, which isn't handled natively by erpnext anymore. Please post your bug report at https://github.com/resilient-tech/india-compliance
