### ISSUE TITLE
Not Getting the Detailed Break Up of the Transactions that comes under the GSTR3B Report- Need the same -Feature Request

### ISSUE THREAD

**Issue by JitendraSAW** [frappe/erpnext#34364]
Presently, Many of the clients and organizations who are filing the GSTR3B want to match with the GSTR1 and their Purchase Registers, and in the same , there is no report or information pertaining to the Transaction which are capturing in the GSTR3B Report. We get only the Json File or the Hard Copy of the GSTR3B.

At the time of filing every assessee has to match the Figures of GSTR1 V/s GSTR3B and also its Inputs or Purchase or GSTR2 Registers, but presently without getting the detailed break and transaction summary it makes difficult to get reconcile between the GSTR1 and GSTR3B.

It would be a Features Request if we come with the above Features through Report Way or Any Summary Report with the Transaction captured in it.

Kindly let us know if any further clarification is needed

**Comment by dj12djdjs** [comment]
Hi @JitendraSAW 

This looks to be related to India compliance, which isn't handled natively by erpnext anymore. Please post your feature request at https://github.com/resilient-tech/india-compliance
