### ISSUE TITLE
[CI] Unit tests timeout because of infinite loop in test for BOM (Manufacturing)

### ISSUE THREAD

**Issue by cogk** [frappe/erpnext#34385]
### Information about bug

Hello,

The unit test in `test_update_bom_cost_in_all_boms` in `erpnext.manufacturing.doctype.bom.test_bom.TestBOM` enters an infinite loop which causes the GitHub Action Unit Tests Job to never finish and thus to timeout, as happened here: [github.com/frappe/erpnext/actions/runs/4340676101/jobs/7580788021](https://github.com/frappe/erpnext/actions/runs/4340676101/jobs/7580788021)

This is most likely caused by this recent PR: https://github.com/frappe/erpnext/pull/34305

More precisely by the following change: [erpnext/manufacturing/doctype/bom_update_log/bom_update_log.py:215](https://github.com/frappe/erpnext/commit/2f157fa5d3e08c642847042282512536e9a20ca5#diff-7e52149d88ae5d7d9100d4fda0287af7493325b63728125ddb00642f732d3c0fL215-R215)

```diff
-		if not bom_batches or incomplete_level:
+		if not bom_batches or not incomplete_level:
```

Which causes a while loop in `update_cost_in_all_boms_in_test` to never ends, as the BOM Update Log is never Completed.

### Module

manufacturing

### Version

Frappe version - develop
ERPNext version - develop

GitHub Actions

### Installation method

None

**Comment by dj12djdjs** [comment]
cc: @rohitwaghchaure
