### ISSUE TITLE
how to remove page

### ISSUE THREAD

**Issue by pankajpatel12** [frappe/erpnext#3438]
how to remove page/delete from page list in frappe/erpnext

**Comment by rmehta** [comment]
What page, what list?

**Comment by ryuliantoro** [comment]
And this still is the case. No delete action for page.
While there is for doctype now.

**Comment by ahmadpak** [comment]
@ryuliantoro  Update the delete permission for Page doctype and then you will be able to delete pages.

![image](https://user-images.githubusercontent.com/7881486/81151828-ccaf5680-8f9a-11ea-827a-462e826ac530.png)

**Comment by mingfang** [comment]
why is the delete page permission not enabled by default for administrators?
