### ISSUE TITLE
Recently installed ERPNEXT 14 but role permission is not working for users

### ISSUE THREAD

**Issue by Sealcoatings** [frappe/erpnext#34397]
### Information about bug

Recently installed ERPNEXT 14 but role permission is not working for users. even if i put sales user, the users could see all modules.

### Module

other

### Version

Frappe Chat: v0.0.1 (main)

ERPNext: v14.18.1 (version-14)

Frappe Framework: v14.27.0 (version-14)

Frappe HR: v14.1.0 (version-14)

Payments: v0.0.1 (develop)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
No errors
```

**Comment by dj12djdjs** [comment]
@Sealcoatings can you provide any extra information?

I just tried creating a user with only Sales User permission. Only the doctypes/modules associated with that role are applied.

**Comment by Sealcoatings** [comment]
Hi, i basically installed a new version of 14.18 and i imported an old DB of 14.01 , i have two issues the first when i create a user the role permission doesnt exist on the user and he can have access to all. Second issue i have the supervisor is not working i get this error 
f

**Comment by deepeshgarg007** [comment]
@Sealcoatings This looks like your site-specific config issue. Closing this
