### ISSUE TITLE
Drop Ship Feature Does not Work

### ISSUE THREAD

**Issue by shirleymayadewi** [frappe/erpnext#34398]
### Information about bug

I followed the instructions outlined here: https://docs.erpnext.com/docs/v13/user/manual/en/selling/articles/drop-shipping
but when I get to the step of Create PO from the newly submitted Sales Order, it gives me an error message "Purchase Order already created for all Sales Order Items". The PO clearly has not been created for that SO.  

### Module

selling

### Version

ERPNext Version 13

### Installation method

None

**Comment by deepeshgarg007** [comment]
@shirleymayadewi As per the logic the ordered qty values in the Sales Order Items must be equal to the item qty. Thats the reason you are getting this validation. How this was updated is site specific now. Doesn't look like a generic bug. Please add more info and then reopen the issue
