### ISSUE TITLE
Dependent Tasks not changed after tasks change

### ISSUE THREAD

**Issue by oliver19820323** [frappe/erpnext#34396]
### Information about bug

picture1
![image](https://user-images.githubusercontent.com/127501597/224317358-3933920c-cf38-482f-bd58-57f435081d08.png)

picture2
![image](https://user-images.githubusercontent.com/127501597/224317725-1a2afb7a-9da5-4672-bf72-f18e447c25e2.png)

From the pictures ,we can see the subject has been changed .but in Dependent Tasks  it is not changed automatically

### Module

projects

### Version

ERPNext: v14.1.2 (version-14)

Frappe Framework: v14.7.0 (version-14)

### Installation method

None

**Comment by dj12djdjs** [comment]
Caused by only modifies depends_on if the task doesn't already exist.

https://github.com/frappe/erpnext/blob/430378bb6e76fe3de7719334a1b237a2915574a6/erpnext/projects/doctype/task/task.py#L220-L224

**Comment by oliver19820323** [comment]
Thank you , but I don't know how to fix it . could you explain more ,how to do

**Comment by oliver19820323** [comment]
> Caused by only modifies depends_on if the task doesn't already exist.
> 
> https://github.com/frappe/erpnext/blob/430378bb6e76fe3de7719334a1b237a2915574a6/erpnext/projects/doctype/task/task.py#L220-L224

Thank you , but I don't know how to fix it . could you explain more ,how to do

**Comment by oliver19820323** [comment]
Anyone can help me ?

**Comment by vamagithub** [comment]
Is this still valid? In the current version of the hotifx, subject is not getting pulled when adding dependent task

**Comment by Nihantra-Patel** [comment]
It's not challenging, you can set using server script doctype.

Please apply it.

```py
depends_on_tasks = frappe.db.get_all('Task Depends On',
                                      filters={'task': doc.name},
                                      fields=['name', 'subject'],
                                      as_list=True)

for task_depends_on in depends_on_tasks:
    frappe.db.set_value('Task Depends On', task_depends_on[0], 'subject', doc.subject)
```

**Output:**


https://github.com/frappe/erpnext/assets/141945075/c4b17d89-9251-4c89-a385-fff06815e297
