### ISSUE TITLE
HR Module not present in 14.18

### ISSUE THREAD

**Issue by johnbangla** [frappe/erpnext#34394]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ruchamahabal** [comment]
Hello,

The HR & Payroll modules were separated from ERPNext in v14 into a separate app: https://github.com/frappe/hrms

https://github.com/frappe/erpnext/wiki/Migration-Guide-to-ERPNext-version-14#separating-modules-from-erpnext-to-new-apps

You will have to install the HR app to get HR and Payroll modules
