### ISSUE TITLE
Error in Exchange Rate Revaluation 

### ISSUE THREAD

**Issue by alkuhlani** [frappe/erpnext#34407]
### Information about bug

I get this error when I add an account that has a credit balance 
Server Error 
IndexError: list index out of range

and the accounts that have a credit balance  don't show

After I changed below code, it works smoothly 
 `change from **balance_in_account_currency** to **balance**`
`in calculate_new_account_balance method`
[current_exchange_rate * d.balance_in_account_currency](https://github.com/frappe/erpnext/blob/fcbcbc0aa7fffbfe732818768ecd5ed32fd4fda8/erpnext/accounts/doctype/exchange_rate_revaluation/exchange_rate_revaluation.py#L231)

### Module

accounts

### Version

ERPNext V14

### Installation method

easy-install

### Relevant log output / Stack trace / Full Error Message.

```shell
Server Error 
IndexError: list index out of range
```

**Comment by ruthra-kumar** [comment]
>> IndexError: list index out of range

Issue is not replicable. Can you share a simple scenario where in this exception occurs?
