### ISSUE TITLE
Cannot create journal entry from exchange rate revaluation

### ISSUE THREAD

**Issue by dgehriger** [frappe/erpnext#34406]
### Information about bug

I'm trying to create exchange rate revaluation entries for the closing of 2022.

The generation of the Exchange Rate Revaluation entry is successful. However, it's impossible to create a journal entry from it. It always produces the error message: "Total Debit must be equal to Total Credit. The difference is <some value>".

![Screenshot 2023-03-11 164130](https://user-images.githubusercontent.com/105200493/224493749-91d4a6a4-7938-4375-829a-c11549a34198.png)

### Module

accounts

### Version

ERPNext: v14.18.2 (version-14)
Frappe Framework: v14.27.0 (version-14)

### Installation method

manual install

**Comment by ernestoruiz89** [comment]
Same issue

**Comment by ruthra-kumar** [comment]
@dgehriger Can you post the traceback from the browser console when you get this error?

**Comment by dgehriger** [comment]
I have fixed the issue in my instance and submitted a PR. However the fix was rejected. I'll keep it on my side. In short, the way the amounts are calculated and rounded isn't consistent and results in the aforementioned error.

**Comment by ernestoruiz89** [comment]
> traceback from the browser console

![image](https://user-images.githubusercontent.com/1592496/231832743-eca052f3-1654-47ee-b12f-0a22a67832de.png)

**Comment by ruthra-kumar** [comment]
This is not replicable. Closing the issue. Re-open if needed
