### ISSUE TITLE
Credit Note against a paid Sales Invoice

### ISSUE THREAD

**Issue by ekpaxp** [frappe/erpnext#3440]
Hi, from what I can find, the only Credit Note functionality is for a Stock Return item by creating a JE.  However, what is needed is a way to issue a Credit Note against a paid Sales Invoice which is not for an Inventory item such as a Service Item or a General Credit Note to be applied to a particular party.
The Credit note needs to be linked to the Paid Sales Invoice and applied to the correct accounts.
Has anyone done any work on this before?

**Comment by rmehta** [comment]
Manual page seems missing. We will add this.
