### ISSUE TITLE
Not able to receive goods in other UOM

### ISSUE THREAD

**Issue by kirthiss** [frappe/erpnext#3441]
Purchase Receipt expects the item to be received only in the default UOM (Stock UOM). If I try to use any other UOM (that is defined in the Item Master with conversion factor), it throws an error. Is this how it is expected to behave?

In Pharma Industry, the packing in which the material is received is crucial. If I receive 5 bags of 10 Kg material, I need to record that in Purchase receipt. PO might still be in Stock UOM since we don't know how the supplier may pack the items. Is this a bug, or am I missing something?

**Comment by nabinhait** [comment]
UOM in PR must be same as PO. The system is designed as that way, it's not a bug. The design is to track received qty in against the PO. If we allow different uom in PR, it's very difficult to update that qty in PO.

**Comment by kirthiss** [comment]
but, isn't that why we define the conversion factors in the item master? If I define 3 UOMs for an item, I should be able receive the item in any of the 3 UOMs. System should be able to apply the conversion factor and update the received qty in PO. This happens all the time in our industry.../
