### ISSUE TITLE
Chart of Accounts does not render tree view for Arabic language

### ISSUE THREAD

**Issue by codezart** [frappe/erpnext#34420]
### Information about bug

When viewing the Chart of Accounts in the default English language it will render the tree. But if I change the user's default language to another language, say Arabic, it does not render the tree view.

Once it threw an error saying erpnext.accounts.utils.get_children requires company needs to be set.  
When console logging into the erpnext.utils.get_tree_default function it suddenly renders.

![Screenshot from 2023-03-13 09-05-40](https://user-images.githubusercontent.com/44206264/224710265-86b77980-35f4-40c9-9e03-0c78c248e170.png)

### Module

accounts

### Version

Frappe version 14
Erpnext version 14

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
No error shown. Just that it doesn't render. 
```

**Comment by codezart** [comment]
I investigated some more, apparently what happens is that the get_tree_options gets the unscrub_option in the language that is currently being used.
https://github.com/frappe/erpnext/blob/develop/erpnext/public/js/utils.js#L300

But in this line: https://github.com/frappe/erpnext/blob/develop/erpnext/public/js/utils.js#L309

the locals dictionary does not have the arabic version of the Company key.
That is why it is not working.

**Comment by Nihantra-Patel** [comment]
Kindly upgrade to version 14 or 15, then refresh and check again because lots of bugs fixed in the new version.

Everything is working fine. No problems were encountered in the latest versions 14 and 15.


https://github.com/frappe/erpnext/assets/141945075/1b9d9f2f-3d07-49e2-bbd6-b497a1ab6969
