### ISSUE TITLE
ERPnext Customer Section

### ISSUE THREAD

**Issue by Alistar989** [frappe/erpnext#34443]
### Information about bug

There is an issue with the customer section in ERPnext I think. I have one customer created. But when I create more, while they appear to be created (it shows that the customer with the same name and other details already exists), they don't appear on the list at all and no filters are being used whatsoever. 

Any possible reason why this is happening?

### Module

other

### Version

Frappe Framework: v13.49.2 (version-13)
ERPNext: v13.47.0 (version-13)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
No error message, they just don't appear..
```

**Comment by deepeshgarg007** [comment]
@Alistar989 this is not replicable on other sites. Please share some GIF and more info for further investigation and reopen the issue
