### ISSUE TITLE
Cannot Generate IRN through E-invoicing in ERPnext 

### ISSUE THREAD

**Issue by Rajinder122** [frappe/erpnext#34447]
### Information about bug

Hello Team,

Hope you are doing well !

We are unable to Generate IRN through E-invoicing in ERPnext in sales invoice module.

Error Message : "The field Location must be a string with a minimum length of 3 and a maximum length of 100".

Kindly please provide a solution to this issue as soon as possible.

### Module

selling

### Version

Frappe Framework: v13.25.0 (version-13)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
Message :
The field Location must be a string with a minimum length of 3 and a maximum length of 100.
```

**Comment by deepeshgarg007** [comment]
@Rajinder122 This error is related to the address, please update the address accordingly and then try
This is not a bug
