### ISSUE TITLE
Automatically print POS after submission

### ISSUE THREAD

**Issue by farhanayyaz1** [frappe/erpnext#3444]
dear in sales invoice when you select "is pos" after invoice submission it does not waits for print instruction.

**Comment by nabinhait** [comment]
Don't understand your issue. Why and how you are selecting "Is Pos" checkbox after submission of invoice?

**Comment by farhanayyaz1** [comment]
Dear when we make sales invoice if we check "is pos" then after submitting invoice, the invoice does not wait for print, a new invoice is loaded.

**Comment by nabinhait** [comment]
That is intended behaviour, user does not generally email to customer in retail businesses. We have skipped email to faster data entry.

**Comment by farhanayyaz1** [comment]
Yes but i need to print it 
--
Sent from myMail app for Android
Wednesday, 10 June 2015, 02:48PM +04:00 from Nabin Hait <notifications@github.com>:

**Comment by nabinhait** [comment]
Yes, I agree.. print is actually a required step.
@anandpdoshi what do you say?

**Comment by farhanayyaz1** [comment]
If you can also make when it submits in new tab full page view is open so it will save time for user.
--
Sent from myMail app for Android
Wednesday, 10 June 2015, 03:02PM +04:00 from Nabin Hait <notifications@github.com>:

**Comment by farhanayyaz1** [comment]
Any update
