### ISSUE TITLE
Consolidated Financial Statement ( error in report) some accounts show as Zero 

### ISSUE THREAD

**Issue by SamiHajbi** [frappe/erpnext#34463]
### Information about bug

i note there is error in bug  Consolidated Financial Statement  some account show with zero value if Group but in fact have values, it was working in v13 without problem .

check this short Video 

https://user-images.githubusercontent.com/93725977/225389098-1f107256-af5c-42aa-9f52-00cce6288fb9.mp4

### Module

accounts

### Version

ERPNext: v14.17.4 (version-14)
Frappe Framework: v14.26.3 (version-14)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
no output log error
```

**Comment by deepeshgarg007** [comment]
@SamiHajbi looks like a site specific issue rather than a bug, closing this
