### ISSUE TITLE
Profit value is fluctuating 

### ISSUE THREAD

**Issue by Marike2020** [frappe/erpnext#34471]
### Information about bug

On the 6th of March around 2PM and 4PM SAST, I ran the profit and loss report and my profit showed R1.8million (+/_) but when I ran my profit and loss report on the 13th of March it showed R300K profit. Subsequently, I reran the report on the 14th and 15th of March and now the profit shows R600K profit. 

Please help me understand why it is fluctuating. I've looked at the journals and there were none done with posting dates from 6-13 March that could cause this.

This is something urgent that I need to understand please - I have spoken to Dharmesh and he said a functional accountant should be looking at this.

### Module

accounts

### Version

![image](https://user-images.githubusercontent.com/69187616/225593323-aada00b2-d5b2-4fd7-badb-4445d1e6685f.png)
ERPNext: v13.43.1 (HEAD)
Frappe Framework: v13.47.0 (HEAD)

Journeys: v0.0.1 (HEAD)

Kartoza: v0.0.1 (HEAD)

### Installation method

FrappeCloud

**Comment by deepeshgarg007** [comment]
@Marike2020 This looks like a site-specific issue and not a product bug, closing this issue

**Comment by Marike2020** [comment]
@deepeshgarg007 it still doesnt resolve the issue. Please indicate why this is happening BEFORE CLOSING THIS ISSUE.
