### ISSUE TITLE
Can't add addresses/contacts when creating Prospect/Opportunity

### ISSUE THREAD

**Issue by damorjuancruz** [frappe/erpnext#34472]
### Information about bug

When trying to create a Prospect or Opportunity, the "Address & Contact" tab is empty but it works just fine when editing an existing Prospect or Opportunity.

I think it may be related with the following code, but I wasn't able to get it to work.
https://github.com/frappe/erpnext/blob/bd2dd7dfac38d91d47a417d2f9a18a0a6f9809b9/erpnext/crm/doctype/prospect/prospect.js#L25-L29
https://github.com/frappe/erpnext/blob/bd2dd7dfac38d91d47a417d2f9a18a0a6f9809b9/erpnext/crm/doctype/opportunity/opportunity.js#L123-L128

### Module

CRM

### Version

Frappe Version - 14.27.0
ERPNext Version - 14.18.2

### Installation method

None

**Comment by Nihantra-Patel** [comment]
Hi @damorjuancruz,

Adding an address and contact to a new opportunity or prospect without a generated ID for the opportunity or prospect, and linking them together, is currently not possible. 

After created an opportunity or prospect, you can add it.

The same applies to Bank, Bank Account, Shareholder, Supplier, Customer, etc.

Thank You!
