### ISSUE TITLE
Calendar days leave calculation

### ISSUE THREAD

**Issue by meatechsupport** [frappe/erpnext#3448]
Hi team,

How to calculate the number of lave days based on Calendar days.

For ex..
-	We Configured holiday list with Friday and Saturday as weekly off and pointed it to the employee
-	Assigned Annual leave of 30 days to employee
-	Now suppose if the employee is taking leave from this Wednesday to next Wednesday the number of leaves applied should be 8 days. But it is counting only 6 days (Friday and Saturday has been excluded).

**Comment by rmehta** [comment]
Are you open to paid development (https://erpnext.com/pricing/paid-feature-development). Will cost you 1 hour.

**Comment by rmehta** [comment]
Fixed via HR Settings
