### ISSUE TITLE
Upgrade Staging Site to the latest Version

### ISSUE THREAD

**Issue by Mayukh-Teabox** [frappe/erpnext#34492]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by marination** [comment]
Hi @Mayukh-Teabox, please limit issues to bugs/feature requests/vulnerabilities within the core product. Your concern seems to be support related. Get in touch with your paid support contact person.
