### ISSUE TITLE
Calendar in Leave Application showing holidays wrongly

### ISSUE THREAD

**Issue by justinlusg** [frappe/erpnext#3449]
![image](https://cloud.githubusercontent.com/assets/12539216/8083032/65352a68-0fb4-11e5-8f89-22accd2e0dfc.png)

![image](https://cloud.githubusercontent.com/assets/12539216/8083055/78172c76-0fb4-11e5-806b-77d1558b23f6.png)

Under holiday list, the weekdays off are set as every Saturday and Sunday of the week for the entire year. However, in the leave calendar, it is displaying correctly for FUTURE DATES, but once the weekend has passed the calendar will display as the wrong date. 

Please see the above 2 screenshot. The 1st one is once the date has passed, the calendar will block out the entire week as holiday. The 2nd consist of dates which has passed and future dates.

**Comment by neilLasrado** [comment]
@justinlusg Hello. How did you manage to get the holiday list on calendar ?

**Comment by justinlusg** [comment]
@neilLasrado  I've no idea, haha, I did not change any settings it just appeared there.

**Comment by justinlusg** [comment]
Please advise if you need any information from me..

**Comment by justinlusg** [comment]
@neilLasrado I managed to get it on when I assign the holiday list to the employee under Human Resource > Employee >> Holiday List

**Comment by neilLasrado** [comment]
@justinlusg Tried the same on my system, worked fine. Unable to replicate the issue.
can you please recheck.
![screen shot 2015-06-16 at 4 22 42 pm](https://cloud.githubusercontent.com/assets/8401344/8181491/f6da9910-1443-11e5-87ee-1177ee3fb727.png)

**Comment by justinlusg** [comment]
It is not under Calendar - Event, can you please check under Calendar - Leave Application? Go under Human Resource > Leave Application > Calendar Button on the Left Menu

**Comment by neilLasrado** [comment]
@justinlusg hey was able to trace the issue. Fixed it. Thanks.

**Comment by justinlusg** [comment]
Cool
