### ISSUE TITLE
If I generate the report based on (Invoice) in the gross profit report, the entire sum does not display correctly! but in exported Excel it is correct.

### ISSUE THREAD

**Issue by sumayyaalip** [frappe/erpnext#34507]
### Information about bug

If I select the report based on (Invoice) in the gross profit report, the entire sum does not display correctly! but in exported Excel it is correct.
But if I choose the report depend on (Item or anything other than the invoice), the sum of total will
show right
[Issue In Gross Profit Report (3).pdf](https://github.com/frappe/erpnext/files/11015225/Issue.In.Gross.Profit.Report.3.pdf)

### Module

accounts

### Version

ERPNext: v14.14.0 (version-14)
Frappe Framework: v14.24.0 (version-14)

### Installation method

None

**Comment by Nihantra-Patel** [comment]
Already issue added
