### ISSUE TITLE
i have need to how to set if-else condition to show different table record

### ISSUE THREAD

**Issue by pankajpatel12** [frappe/erpnext#3450]
below is my .py code and after "error"  i have need to how to set if-else condition to show different table record and how to remove this error and get preffect output..

# Copyright (c) 2015, Frappe Technologies Pvt. Ltd. and Contributors
# License: GNU General Public License v3. See license.txt

from __future__ import unicode_literals
import frappe
from frappe import _, msgprint

def execute(filters=None):
	if not filters: filters = {}
	
	columns = get_columns()
	data = get_entries(filters)
	
	return columns, data
	
def get_columns():
	return [_("Name") + ":Link/Vegetable Production", _("Division Name") + ":Link/Division", _("Field Name") + ":Link/Field", 
		_("Variety") + ":Link/Vegetable Production", _("Plant Row Width") + ":Link/Vegetable Production", _("Plant Spacing") + ":Link/Vegetable Production", _("Type") + ":Link/Vegetable Production", _("Type of Soil") + ":", _("Size") + ":", _("Color") + ":", _("Unit of Measure") + ":"]

def get_conditions(filters):
	conditions = ""
	if not filters.get("name1"):
		msgprint(_("Please select Vegetable Production Name"), raise_exception=1)
		
	else:
		conditions += " and name1 = %(name1)s"
	
		if  get_entries("division_name") !="":
	
		entries =  frappe.db.sql("""select name1, field_name, variety, 
			plant_row_width, plant_spacing, type, type_of_soil, size, color, unit_of_measure
			FROM `tabVegetable Production`, `tabField`
	 		WHERE `tabVegetable Production`.`field_name` = `tabField`.`field` %s"""% conditions, filters)
		else:
	
		entries =  frappe.db.sql("""select name1, division_name, variety,
			plant_row_width, plant_spacing, type, type_of_soil, size, color, unit_of_measure
			FROM `tabVegetable Production`, `tabDivision`
	 		WHERE `tabVegetable Production`.`division_name` = `tabDivision`.`division` %s"""% conditions, filters)
	return entries
		
	return conditions
	
#def get_entries(filters):
#	conditions = get_conditions(filters)
	...............................................................................................................................................................
	......"Error".......
Traceback (innermost last):
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/app.py", line 51, in application
    response = frappe.handler.handle()
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/handler.py", line 70, in handle
    execute_cmd(cmd)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/handler.py", line 93, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/__init__.py", line 751, in call
    return fn(*args, **newargs)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/desk/query_report.py", line 87, in run
    columns, result = frappe.get_attr(method_name)(frappe._dict(filters))
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/__init__.py", line 734, in get_attr
    return getattr(get_module(modulename), methodname)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/__init__.py", line 564, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/erpnext/frappe-bench/apps/agri_farm/agri_farm/agri_farm/report/vegetable_production_details/vegetable_production_details.py", line 30
    entries =  frappe.db.sql("""select name1, field_name, variety,
          ^
 IndentationError: expected an indented block

**Comment by rmehta** [comment]
The trace is clearly self explanatory.

https://www.google.com/search?q=IndentationError%3A+expected+an+indented+block&ie=utf-8&oe=utf-8

**Comment by pankajpatel12** [comment]
thank you
