### ISSUE TITLE
Unable to create a quotation from an Opportunity that is linked to a prospect

### ISSUE THREAD

**Issue by dlarocheRolle** [frappe/erpnext#34504]
### Information about bug

Hello,

I have done the following:
1. I created a lead
2. From the lead form, i create a Prospect (right top end corner create-> prospect)
3. From the prospect, i create an Opportunity and i open the opportunity
4. From the opportunity, i click to create a quotation: i receive an error message "Not Found - Lead 'Company1' not found - the resource you are looking for is not available'

If i display the list of opportunities and open the opportunity above and create a quotation -> same error message

If i show quotation list and i create a quotation from here directly without linking to opportunity -> it works.

Regards,
Didier

### Module

buying, CRM

### Version

ERPNext: v14.18.3 (version-14)

Frappe Framework: v14.28.2 (version-14)

### Installation method

manual install

**Comment by nitinfb** [comment]
is there any solution to this ? we are stuck on the same problem !

**Comment by umairsy** [comment]
@shariquerik
