### ISSUE TITLE
Enhancement - Billing Days drives Invoice Date

### ISSUE THREAD

**Issue by monojoker** [frappe/erpnext#3451]
Hi All,

In Customer there is a field called "Credit Days". Logically this should be the time period the customer has between invoice posting date and invoice due date. ERPNext does not do any calculation for this. So Sales Invoice Payment Due Date is always = Invoice Date.

Can you please enhance the Sales Invoice form to calculate the Payment Due Date as:

Sales Invoice Date (posting date) + Customer.Credit Days.

Additionally many customers can have terms like "last day of the next month after invoice", commonly referred to as "30 Days EOM" (End Of Month). So a field would need to be created to accommodate this. Typically in other systems it is TWO fields:

Credit Days - Integer Field
Credit Type - Dropdown field of: Days, EOM, etc.

In this scenario the calculation of Payment Due Date is:

Fetch Month of Sales Invoice Posting Date, add one month, take last day of month. Examples:

Posting Date: 01/01/15
Payment Due Date: 28/02/15

Posting Date: 16/06/15
Payment Due Date: 31/07/15

Posting Date: 31/10/15
Payment Due Date: 30/11/15

Please indicate if this makes sense or needs more explanation.

**Comment by rmehta** [comment]
@monojoker thanks for detailed explanation

https://erpnext.com/pricing/paid-feature-development ? We can do this in 1hr.

**Comment by monojoker** [comment]
Sounds good to me Rushabh, let me know how to pay and I can write a better spec if required but it sounds like you understand the requirement. Just to clarify you will develop the straightforward "days" requirement plus the "last day of next month" option too? I can show you the javascript I am using currently to calculate it - the normal "+ X days" is working but the last day of next month doesn't for some reason so I am having to manually edit credit days each day to fix. So worth getting the dev done. Here is gist of my script currently if it helps you understand. Thanks again, Liam.

https://gist.github.com/monojoker/96099c94c3d6baddf9fc

**Comment by rmehta** [comment]
Thanks @monojoker will send you an invoice and try and get on this today or tomorrow. We will also publicy acknowledge you for the contribution :)

**Comment by monojoker** [comment]
Hi Guys,

Paid via Paypal, ref no: Unique Transaction ID 3LJ537987W125044A

Please let me know when you commence and obviously finish dev for testing :)

Many thanks
Liam.

**Comment by rmehta** [comment]
Thanks Liam. Thats this first Paid Development going into production :) We will try and get this done by tomorrow latest.

**Comment by nabinhait** [comment]
Development completed #3616 

Will be released and deployed tomorrow.

**Comment by robertbecht** [comment]
Congrats for the first paid improvement robert

**Comment by nabinhait** [comment]
@monojoker We will release the feature on Monday. Sorry for the delay.

**Comment by nabinhait** [comment]
@monojoker Released the feature. Please check and let us know if there is any issue.
