### ISSUE TITLE
Job Card: start, complete, pause buttons missing

### ISSUE THREAD

**Issue by LukasBCG** [frappe/erpnext#34518]
### Information about bug

<img width="2423" alt="Bildschirmfoto 2023-03-20 um 16 25 48" src="https://user-images.githubusercontent.com/103038727/226389237-f37ebdc5-8ed9-4e39-955e-8cd882af4476.png">

After the material was transferred to the WIP warehouse, there were buttons (Start, Pause, Complete Job). With these buttons you could control the timing detail table.

Since the update from ERPnext v14.12.1 to v14.18.3 these buttons are no longer available and you have to enter start, end and produced quantity manually in the Timing Detail table.

Is this a bug, or does it need a different setting here since the update? Thanks! Cheers

### Module

manufacturing

### Version

ERPnext v14.18.3

### Installation method

manual install

**Comment by deepeshgarg007** [comment]
@LukasBCG Please check if there is any error in the browser console, if yes please share that

**Comment by rohitwaghchaure** [comment]
@LukasBCG I have tested on local instance and it's working fine, make sure you have transferred materials to the WIP warehouse 

<img width="1324" alt="image" src="https://user-images.githubusercontent.com/8780500/227239472-21186713-2472-472d-a81e-99f7e7e6a354.png">

**Comment by rohitwaghchaure** [comment]
@LukasBCG  Since the feature is working fine I am closing the ticket, kindly reopen the ticket if the issue still persists.

**Comment by LukasBCG** [comment]
Hi @deepeshgarg007 & @rohitwaghchaure thank you for your feedback.

We have checked the console and could not find any abnormalities. 

- The material was transferred to the WIP Warehouse in the screenshot above (recognizable in the badage "Material transferd").
- There were still some old job cards in the system, which were created before the update to 14.18.3, for these the buttons are present. Only with new create they are no longer available.

**Comment by LukasBCG** [comment]
@rohitwaghchaure no the problem is not fixed!

**Comment by LukasBCG** [comment]
> @LukasBCG Since the feature is working fine I am closing the ticket, kindly reopen the ticket if the issue still persists.

I can't reopen the ticket, the problem is not fixed, please reopen it!

**Comment by deepeshgarg007** [comment]
@LukasBCG Please give us more info to replicate, on our site its working fine, unless we are able to replicate there is nothing much we can do

**Comment by LukasBCG** [comment]
@deepeshgarg007 
I can gladly provide login data, then you can see the problem for yourself. I can't do more than send screenshots here.

Or tell me what other information you need.
I create a job card, do the material transfer and the buttons are missing. That's it...

**Comment by deepeshgarg007** [comment]
@LukasBCG Please send the full screenshot of the job car doc, you can also copy the document data from the menu to clipboard and share here

**Comment by LukasBCG** [comment]
@deepeshgarg007 I sent the data to your Gmail address because there is some personal information there that I don't want to share here. Thanks!

**Comment by rohitwaghchaure** [comment]
@LukasBCG I am able to replicate the issue, if you set the "Transfer Material Against" as "Job Card" then this issue persists. Issue doesn't replicate if the "Transfer Material Against" set as "Work Order".

**Comment by LukasBCG** [comment]
@rohitwaghchaure 
Yes you are right. If "Transfer Material Against" set as "Work Order" then the buttons are present in the Job Card.
<img width="709" alt="Bildschirmfoto 2023-03-23 um 17 56 16" src="https://user-images.githubusercontent.com/103038727/227278522-ba90c748-2607-46ac-ba39-0dd16546b39b.png">

Does this mean that this is a bug? Will this bug now be examined more closely by the team?

**Comment by rohitwaghchaure** [comment]
@LukasBCG Yes this is a bug and I have opened the PR to fix the issue

**Comment by LukasBCG** [comment]
Hi @rohitwaghchaure, @deepeshgarg007,

I have another question about the bug. I have installed the version that contains the bugfix, that works so far.

Only with job cards where no raw material is needed, the buttons are still not available. Can this be fixed?
<img width="2597" alt="Bildschirmfoto 2023-06-21 um 14 27 40" src="https://github.com/frappe/erpnext/assets/103038727/1b9a88d9-cba4-41ad-a022-d4365645ba45">
