### ISSUE TITLE
 How to specify Individual item price in sales bom? 

### ISSUE THREAD

**Issue by inventobd** [frappe/erpnext#3452]
I,m trying to sell an item package (Group of Items) . Like here are my individual items

    1. Air Ticket (Individual service Item with price)
    2. Visa Consultancy (Individual service Item with price)
    3. 1 night hotel accommodation  Price (Individual service Item with price)
    4. Sight seeing 1 person (Individual service Item with price)

"Sales person can increase or decrease quantity to increase night or person wise service like regular sales order"

Now I Also want to sell all this together as
#Thailand tour Package or any other package . I want to create as many packages with combining my items I want .

"Sales person can simply select a package in sales order . He can also add any extra individual item along with the package also. 

I have created Sales BOM with all this items . But there is no option to sell service item as package. Also package item doesn't have any option to fetch individual item price to decide package price. (Less important) . How can we sell service items as package ? Also as I mentioned earlier when selling package is there any way to specify individual item price of that package in sales order (less important also)

I think its very important for company who sell products/service individually and as a group of item too . They will also want to check reports for individual sale and package sell. How can we implement this feature ?

**Comment by rmehta** [comment]
Open for https://erpnext.com/pricing/paid-feature-development?

**Comment by inventobd** [comment]
If it doesn't cost too much then I don't have any problem sponsoring it . But I think its very necessary to have this functionality . I have service items which I want to sell individual or as package . Should I explain in more details there ?

**Comment by rmehta** [comment]
@inventobd from what I understand

1. Allow product bundle for services?
2. Auto calculate rate of product bundle based on sub-parts?

I think we can do this in 2 billable hours ($200). We have availability for next week.

**Comment by inventobd** [comment]
Hello @rmehta 

Great . Yes I want something like this . I might need few more customization also but requirement is not fully prepared yet. I can break this customization into part and do step by step . But that is exactly what I need first to start  "1. Allow product bundle for services" . I want to do this one first . And then the next ones when my requirement is fully ready. Can you guyz do number 1 in 1 hour ? . If yes just let me know when and how I need to send the money . I,m ready to sponsor it :)
Thanks a lot

**Comment by rmehta** [comment]
@inventobd yeah we can do Point 1 in 1 hr. Can you pay via PayPal? Please send us your details at info at erpnext dot com and we will send you an invoice. Thanks!

**Comment by inventobd** [comment]
Hello
Thank you very much for your replay. Unfortunately its our bad luck that paypal is still not available here in Bangladesh . Can I pay via different way ? I have a credit card with which I can pay . Or I can use western union . Please let me know . Also in this scenario I might need more customization which I will do step by step :)

**Comment by rmehta** [comment]
@inventobd Cost of wire-transfer is too much. All of us should just move to bitcoins! We will do this for now, maybe you can add the payment in your next feature request :)

**Comment by inventobd** [comment]
Hello @rmehta 
Thank you very much for your kindness . But I want to pay for it . Let me try if I can find someone Else's paypal to pay you. 
Thanks

**Comment by rmehta** [comment]
Sent for release.

**Comment by andiyan1** [comment]
@rushabh,

I can sponsor this, i have similar requirement regarding service product. as sometimes i have to add service product in my BOM and to calculate it altogether. can you re-activate this?

Thanks 
Anton

**Comment by rmehta** [comment]
@andiyan1 You can already add service items to Product Bundle. Do you want to add it to BOM too? Do you want to start a separate thread? Thanks for your interest in sponsoring :)

**Comment by inventobd** [comment]
@rmehta 

Can we repoen this ? I have 3 requirements : 

1. Allow product bundle for services
2. Auto calculate rate of service product bundle based on sub-parts
3. Ability for sales manager to change / alter sub parts item and item price in sales order 

You have done first one  :) . Can we do this next two ? I will adjust by sponsoring the next 2 . I can pay via paypal now . Please give me a small budget so I can afford :)

Thanks
