### ISSUE TITLE
Users passwords gets reset when changes are made to Roles or Access

### ISSUE THREAD

**Issue by ekpaxp** [frappe/erpnext#3453]
Hi, if an existing user has any changes made to say the allowed Roles or Module Access and the changes are applied by Save - the User's password is reset as well even though the Password field was not touched.  This is happening on ERPNext: v5.0.20/Frappe Framework: v5.0.24

**Comment by rmehta** [comment]
Cannot replicate. Does this still happen?

**Comment by ekpaxp** [comment]
It seems to not be occurring any more.  On a fresh install yesterday it is not happening.  In addition, on the system where it occurred before it also seems to have stopped.  I'll update if I see it happening again.  Thanks
