### ISSUE TITLE
Add Mode Of Payment into POS Profile

### ISSUE THREAD

**Issue by jof2jc** [frappe/erpnext#3454]
[Feature request]
Add mode of payment in POS Profle it's automatically selected when creating new invoice, to fasten the entry.

**Comment by fderyckel** [comment]
+1

**Comment by jof2jc** [comment]
No update on this? Tks

**Comment by neilLasrado** [comment]
@jof2jc We added this feature.

**Comment by jof2jc** [comment]
thanks @neilLasrado
