### ISSUE TITLE
Error (Invalid filter: undefined) when clicking Status column in Lead listview

### ISSUE THREAD

**Issue by Kolaani** [frappe/erpnext#34557]
### Information about bug

It should filter the listview based on status field value. But instead the following error

![image](https://user-images.githubusercontent.com/8342830/226944452-ac2f8d0d-485c-438c-92bb-01ea1d30b107.png)

![image](https://user-images.githubusercontent.com/8342830/226945292-0c04cc82-50f9-45e8-a308-148cadd0717e.png)

### Module

CRM

### Version

ERPVersion 14

### Installation method

manual install

**Comment by deepeshgarg007** [comment]
@Kolaani loos like the filters weren't applied correctly, doesn't look like a bug, please check again and mention the steps to reproduce if any

**Comment by Kolaani** [comment]
@deepeshgarg007 

How to reproduce? :
Add a few records to the Leads
Click on the **Status** field of the Lead's ListView

Normal behaviour should be to filter based on the value of the Status field. But instead it shows the above error message. If you inspect using Chrome Dev Tools it shows **data-filter** = undefined. The value of **data-filter** should be **status**

**Comment by Kolaani** [comment]
> @Kolaani loos like the filters weren't applied correctly, doesn't look like a bug, please check again and mention the steps to reproduce if any

How to reproduce? :
Add a few records to the Leads
Click on the Status field of the Lead's ListView

Normal behaviour should be to filter based on the value of the Status field. But instead it shows the above error message. If you inspect using Chrome Dev Tools it shows data-filter = undefined. The value of data-filter should be status
