### ISSUE TITLE
Specific Report Permission Setting on Role Permission Manager

### ISSUE THREAD

**Issue by jof2jc** [frappe/erpnext#3455]
Current problem is when we allow a role for a doctype then the users will have access to all reports associated with that doctype. The same if we disallow / uncheck Report then they'll not have access at all. So less control we have for reporting security.

What if we need to allow only some reports, not all? It's not possible! 

So it would be useful when Report is checked on Role Permission Manager then there's option list where we can select report by report of that doctype that are permitted for that role.

This way, company can ensure that the users only able to see information that they're authorized to see.

**Comment by anandpdoshi** [comment]
You can give  access to only selected reports for a USER via User Permissions. 


Go to Setup / User Permissions and add records for the combination of user and Report. 


Thanks,Anand Doshi.

**Comment by jof2jc** [comment]
Yeah I didn't know this if we can specify specific report under User Permission Manager.

Anyway, in my opinion I prefer to set Report permission under Role Permission Manager due to some reasons:
1. No need to specify this setting per user, so it will be faster under Role Permission Manager.
3. Via User Permission Manager, we have to specify permitted record line by line. If under Role,   when check Report then all reports of that doctype will automatically selected (allowed) by default. We just need to uncheck restricted reports for that role of that doctype.

This way gives user more convenient way
Thanks

**Comment by rmehta** [comment]
https://erpnext.com/pricing/paid-feature-development ?

**Comment by ai-erp** [comment]
Hi @jof2jc , I also have the same issue... any update if this has been pushed? thank you...

**Comment by adityaduggal** [comment]
This is now resolved with new permission for report and page.
