### ISSUE TITLE
Issue in Payment reconciliation for Multi Currency

### ISSUE THREAD

**Issue by maveezmh** [frappe/erpnext#34565]
### Information about bug

I Have a Customer with Currency in Company Default 
 Enabled Multi currency in Accounts settings

i Have a standalone payment entry of 36 AED
![image](https://user-images.githubusercontent.com/112148467/227171205-25601764-d46c-4264-b92f-d9a7d73a6a68.png)

and against same customer i created a sales Invoice in USD.

![image](https://user-images.githubusercontent.com/112148467/227171612-ec038bee-5d9f-4354-9c50-caf6e353a5cf.png)

now when i do payment reconciliation to allocate payment entry with Invoice following error happens

![image](https://user-images.githubusercontent.com/112148467/227172073-3f7ac54c-269b-4531-b1d6-39a97d07e9f8.png)

when i click allocate it shows difference in allocated values and books forex gain/loss

![image](https://user-images.githubusercontent.com/112148467/227172258-4e73c340-9721-409a-9d1d-90dcc77b5b86.png)

the invoice value is 36 the payment entry value is 36 but still there is exchange difference

![Screenshot 2023-03-23 at 14-14-54 Payment Reconciliation](https://user-images.githubusercontent.com/112148467/227172723-3da25e96-308e-42aa-b984-b436c2b2698c.png)

### Module

accounts

### Version

ERPNext: v14.18.3 (HEAD)
Frappe Framework: v14.28.2 (HEAD)
Frappe HR: v14.1.2 (HEAD)
Payments: v0.0.1 (HEAD)

### Installation method

FrappeCloud

**Comment by clayrisser** [comment]
I'm having issues as well with payment reconciliation for multi-currency. It marks the invoices as paid, but creates completely wrong journal entries, which I basically remove from the database directly. I'm not sure my bug is the same as this, but I don't think multi-currency reconciliation is reliable. Seems to have lots of weird side effects.

I'm kind of wondering if there would be a way to adjust the exchange rate during the reconciliation, or at least give the user more control during the process so they can correct any calculations that are incorrect.

**Comment by thida-bcn** [comment]
we had managed to reconcile from journal entry for multi-currency

**Comment by ruthra-kumar** [comment]
This was a bug, wherein difference amount was mistakenly calculated for base currency(company default currency) accounts. It was subsequently fixed by https://github.com/frappe/erpnext/pull/34466.
Fix is available in [V14.19.0](https://github.com/frappe/erpnext/releases/tag/v14.19.0)
