### ISSUE TITLE
Unique Fields should not check for Blank or None Fields

### ISSUE THREAD

**Issue by adityaduggal** [frappe/erpnext#3456]
There is an option to define a field as unique but this property does not let users save blank fields as they are considered as Similar and not unique.

Here is the Use Case:
I have added a USER ID field in the Sales Partner. Now not all Sales Partners would have a User ID for erpnext account and hence most of them would have this field as BLANK but I don't want to assign same email ID to different Sales partners and for this I wanted to make this field as UNIQUE.

**Comment by rmehta** [comment]
This is a DB feature. Hence hard to fix. Maybe a validation is a better way to handle this.

You want to fix this?

**Comment by adityaduggal** [comment]
Are you suggesting that I put a validation instead of using the unique field which I can do. Let me know if its going to be added or should I go for my own solution.

If its not going to be fixed then please close the ticket.

**Comment by adityaduggal** [comment]
@umairsy This is the issue which is not yet fixed which I was talking about during our skype session for unique fields.
