### ISSUE TITLE
Plaid integration not working with plaid developer credentials.

### ISSUE THREAD

**Issue by clayrisser** [frappe/erpnext#34575]
### Information about bug

It redirects correctly to plaid, but then I get an error that says "Something went wrong". The sandbox credential works fine, but when using the development credential it breaks. I tried with several banks and get the same error.

![2023-03-23-164859_screenshot](https://user-images.githubusercontent.com/6234038/227357055-634b98ca-4315-4945-9278-79164afc3077.png)

![2023-03-23-164925_screenshot](https://user-images.githubusercontent.com/6234038/227357111-7b8121cb-814e-43ae-8928-f788bc96803a.png)

### Module

accounts

### Version

Frappe version: v14.26.0
Erpnext version: v14.18.0

### Installation method

docker

**Comment by rspinuz** [comment]
@clayrisser

This is not a bug.

You need to request developer access via the Plaid dashboard.

Visit: https://dashboard.plaid.com/overview/development
to request your access.
