### ISSUE TITLE
Journal Entry 'Total Debit' & 'Total Credit', remains zero on Data Import

### ISSUE THREAD

**Issue by nrhdasa** [frappe/erpnext#34581]
### Information about bug

When we import Journal Entries from Data Import tool, it doesn't calculate the Total Debit & Total Credit and remains Zero. When we create manually from 'Add a new Entry' from List View, it works fine.

![image](https://user-images.githubusercontent.com/40687270/227451136-0d9ca34c-3968-4b0f-b6c5-f37e72d5a495.png)

### Module

accounts

### Version

ERPNext: v14.18.3 (version-14)
Frappe Framework: v14.28.2 (version-14)

### Installation method

manual install

**Comment by deepeshgarg007** [comment]
Fixed Via: https://github.com/frappe/erpnext/issues/34581
