### ISSUE TITLE
Pricing Rule is reset when entering quantity for a credit note (sales invoice)

### ISSUE THREAD

**Issue by jbellanca** [frappe/erpnext#34599]
### Information about bug

When entering a Credit Note (Sales Invoice - checking "Is Return (Credit Note)"), the Price Rule is correctly applied. However, when you change the quantity to a negative value (since it's a credit note) it resets the value as if the Pricing Rule doesn't apply. Also, changing settings values to apply the Pricing Rule for both Selling and Buying Parties doesn't change the outcome.

This has been reported previously as Bug 29798 on February 15, 2022, but was marked as inactive/stale - but it's still a bug. Screenshots and video can be found at: https://github.com/frappe/erpnext/issues/29798

Video: https://youtu.be/frEsUgQJvUQ

### Module

accounts, selling

### Version

ERPNext: v14.18.3 (HEAD)
Frappe Framework: v14.28.1 (HEAD)

### Installation method

None

**Comment by borgmatthew** [comment]
This is also happening for us

**Comment by nabinhait** [comment]
fixed in latest version
