### ISSUE TITLE
Payment Entry is already created on Sending Request for Mpesa Express - happens with POS Awesome

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#34598]
### Information about bug

If it's for POS Awesome, why report it here.

Because:

It's caused by: https://github.com/frappe/erpnext/blob/e271935673f1e27d7bd8ab7b7e1731a22b2e0bee/erpnext/accounts/doctype/payment_request/payment_request.py#L499

Suggestion is to change payment request to something like below.
![image](https://user-images.githubusercontent.com/1822868/227903548-aa18c7ef-4cbf-40f9-b8fa-525a5dd1c3e3.png)

I.e. To handle this situation where we need to create payment request against draft sales invoice in case outstanding amount is not coming.

### Module

accounts

### Version

ERPNext: v14.19.0 (HEAD)
Frappe Framework: v14.29.0 (HEAD)
POS Awesome: v4.2.0 (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
Stacktrace / full error message
request.js:457 Traceback (most recent call last):
File "apps/frappe/frappe/app.py", line 66, in application
response = frappe.api.handle()
File "apps/frappe/frappe/api.py", line 54, in handle
return frappe.handler.handle()
File "apps/frappe/frappe/handler.py", line 45, in handle
data = execute_cmd(cmd)
File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
return frappe.call(method, **frappe.form_dict)
File "apps/frappe/frappe/init.py", line 1607, in call
return fn(*args, **newargs)
File "apps/posawesome/posawesome/posawesome/api/posapp.py", line 1219, in create_payment_request
pay_req = get_new_payment_request(doc, pay)
File "apps/posawesome/posawesome/posawesome/api/posapp.py", line 1247, in get_new_payment_request
return make_payment_request(**args)
File "apps/posawesome/posawesome/posawesome/api/posapp.py", line 1373, in make_payment_request
pr.insert(ignore_permissions=True)
File "apps/frappe/frappe/model/document.py", line 259, in insert
self.run_before_save_methods()
File "apps/frappe/frappe/model/document.py", line 1045, in run_before_save_methods
self.run_method("validate")
File "apps/frappe/frappe/model/document.py", line 914, in run_method
out = Document.hook(fn)(self, *args, **kwargs)
File "apps/frappe/frappe/model/document.py", line 1264, in composer
return composed(self, method, *args, **kwargs)
File "apps/frappe/frappe/model/document.py", line 1246, in runner
add_to_return_value(self, fn(self, *args, **kwargs))
File "apps/frappe/frappe/model/document.py", line 911, in fn
return method_object(*args, **kwargs)
File "apps/erpnext/erpnext/accounts/doctype/payment_request/payment_request.py", line 39, in validate
self.validate_payment_request_amount()
File "apps/erpnext/erpnext/accounts/doctype/payment_request/payment_request.py", line 54, in validate_payment_request_amount
ref_amount = get_amount(ref_doc, self.payment_account)
File "apps/erpnext/erpnext/accounts/doctype/payment_request/payment_request.py", line 515, in get_amount
frappe.throw(_("Payment Entry is already created"))
File "apps/frappe/frappe/init.py", line 525, in throw
msgprint(
File "apps/frappe/frappe/init.py", line 493, in msgprint
_raise_exception()
File "apps/frappe/frappe/init.py", line 442, in _raise_exception
raise raise_exception(msg)
frappe.exceptions.ValidationError: Payment Entry is already created
```

**Comment by deepeshgarg007** [comment]
@muchai haven't seen how POS Awesome works but why would it go in the Sales and Purchase Invoice section
Your suggestion suggests changes in the Sales and Purchase invoice block, shouldn't it go in the "POS Invoice" else block?

I am a bit confused

**Comment by yrestom** [comment]
The issue is happened when we try to make a payment request against draft Sales Invoice in case outstanding amount is not coming so we need handle that situation and use different way to get grand_total just like what we are doing for POS Invoice

**Comment by deepeshgarg007** [comment]
@yrestom I am still confused, an invoice even in the draft state will have an outstanding amount field and the current logic should work, what am I still missing?

**Comment by muchai** [comment]
- @deepeshgarg007 POS Awesome, creates Sales Invoice of type is_pos, and there's no POS Invoice.

- Thing is, this Sales Invoice is of type cash, hence already paid, and outstanding amount will be 0. I.e. grand_total in the (https://github.com/frappe/erpnext/blob/e271935673f1e27d7bd8ab7b7e1731a22b2e0bee/erpnext/accounts/doctype/payment_request/payment_request.py#L499), will be zero.  Hence it ends up at the: else clause: frappe.throw(_("Payment Entry is already created")).

**- Maybe a change here.**

- elif dt in ["Sales Invoice", "Purchase Invoice"]:, excludes **is_pos** sales invoices
and
- elif dt == "POS Invoice":, includes **is_pos** sales invoices

**Comment by muchai** [comment]
@deepeshgarg007 We made the change as below, and extended the method. Trying to do a pr. Below solves the problem.
```
    elif dt in ["Sales Invoice", "Purchase Invoice"]:
        **if not ref_doc.is_pos:**
            if ref_doc.party_account_currency == ref_doc.currency:
                grand_total = flt(ref_doc.outstanding_amount)
            else:
                grand_total = flt(ref_doc.outstanding_amount) / \
                    ref_doc.conversion_rate
        **elif dt  == "Sales Invoice":
            for pay in ref_doc.payments:
                if pay.type == "Phone" and pay.account == payment_account:
                    grand_total = pay.amount
                    break**
    elif dt == "POS Invoice":
        for pay in ref_doc.payments:
            if pay.type == "Phone" and pay.account == payment_account:
                grand_total = pay.amount
                break
```

**Comment by muchai** [comment]
We re-open this please.

A different amount is sent to the customer MPESA popup, than the amount on the invoice. A bit erratic, so needs more testing.

We need your help on this.
