### ISSUE TITLE
Chart of accounts importer Template - columns assigned wrongly.

### ISSUE THREAD

**Issue by ocapito** [frappe/erpnext#34594]
### Information about bug

The blank template that you can download in csv or xlsx has an error according to my understanding. All 3 columns that have prefilled 'data' need to be shifted one column to the right.

That is: Under the column header "Parent Account" I get the 0s and 1s that I expect to be under the header "Is Group"

### Module

accounts

### Version

Not sure how to find out the exact version. I have some 14er Version and I believe it is
Frappe Version - 14.29.1
ERPNext Version - 14.19.0

### Installation method

FrappeCloud

**Comment by deepeshgarg007** [comment]
Fixed via: https://github.com/frappe/erpnext/issues/34594
