### ISSUE TITLE
Equity behaving like an asset

### ISSUE THREAD

**Issue by clayrisser** [frappe/erpnext#34591]
### Information about bug

I thought Equity is supposed to behave like a Liability, but Debits are increasing the Equity and Credit is decreasing the Equity, just like they would increase and decrease an Asset. Is this correct?

![2023-03-25-130501_screenshot](https://user-images.githubusercontent.com/6234038/227731534-44ae75af-d8be-433e-9bca-f4d2155ab090.png)

### Module

accounts

### Version

Frappe: 14
Erpnext: v14.19.0

### Installation method

None

**Comment by clayrisser** [comment]
Even the documentation seems to suggest the Equity account is supposed to behave like a Liability. The Debit is supposed to decrease the account.

![2023-03-25-130945_screenshot](https://user-images.githubusercontent.com/6234038/227731739-60f672d1-b851-4d28-b8f5-becc89b3d37e.png)

**Comment by deepeshgarg007** [comment]
@clayrisser In General Ledger report the balance is always shown as Debit - Credit, which has nothing to do with account type, you can check with other account types as well. Please correct me if I am wrong and reopen the issue
