### ISSUE TITLE
Please add an option to prevent cancelling paid invoices (Sales & Purchase) without cancelling the payment voucher(s) first

### ISSUE THREAD

**Issue by tardi** [frappe/erpnext#3460]
Please help to add and option/setting (in the setup maybe) to prevent cancelling paid invoices (partially paid or fully paid in Sales Invoices & Purchase Invoices) without cancelling the related payment voucher(s) first.
This is very important feature because it is very hard to force the users to do that.
Maybe it could be a similar feature like "Balance Must Be" option in Account Setup.
Thanks

**Comment by anandpdoshi** [comment]
For clarification: I think right now the system unlinks the payments from invoices but does not cancel them. The payment still remains for use in future. But the invoice is allowed to be cancelled. 

@nabinhait can you confirm this

**Comment by nabinhait** [comment]
@anandpdoshi is right. Cancelling invoices is just unlink all the payment
entry against them. You can link them again via Payment Reconciliation tool.

**Comment by tardi** [comment]
This gives troubles to the users, many times they forgot to cancel the related JV(s) / payment[s], so please help to prevent this case because the unlinked payment(s) will still be calculated in many reports.

**Comment by kittiu** [comment]
Agreed with tardi. The good ERP system should help prevent the wrong doing. If a document is cancelled, system must warn document after it.
Also, no deletion of the journal entry should be made, the system should auto reverse the entry. I.e., JV001, then, system create JV001_Cancelled. It is good for audit trail.
