### ISSUE TITLE
Multicurrency invoice with exchange gain and loss showing up in AR/AP report in Version 14

### ISSUE THREAD

**Issue by JitendraSAW** [frappe/erpnext#34605]
### Information about bug

There is a Forex Exchange Gain/Loss Entry which got recorded through Exchange Rate Revalution Doc Type
![image](https://user-images.githubusercontent.com/80260184/228161381-95f67263-b6ad-42bf-8707-bdba25273f01.png)

After recording this Entry it comes in the Accounts Payable Report - Version 14 

<img width="923" alt="image" src="https://user-images.githubusercontent.com/80260184/228161731-17958532-62f5-47fc-85ab-7389bf5e29b4.png">
<img width="943" alt="image" src="https://user-images.githubusercontent.com/80260184/228161973-c9fddf70-d5b2-469f-bcfa-d0b137575407.png">

Same is resolved in the Versions 13.42.2. Refer the Below Link:-

Multicurrency invoice with exchange gain and loss showing up in AR/AP report ([d38a289] (https://github.com/frappe/erpnext/commit/d38a2895b0cd285da44e071956a7446fd8d49adf))

### Module

HR

### Version

![image](https://user-images.githubusercontent.com/80260184/228162368-cfe506ac-b4bb-4162-a463-f77bf082bb64.png)

### Installation method

None

**Comment by ruthra-kumar** [comment]
ERR journals will be included in AR/AP report to match the Trial Balance. 
https://github.com/frappe/erpnext/pull/33380

**Comment by JitendraSAW** [comment]
@deepeshgarg007  Is this bugs has been resolved and if yes in which releases as still this is getting reflected in our Accounts Payable Reports
