### ISSUE TITLE
Bulk Delete the Deleted Documents

### ISSUE THREAD

**Issue by nitin-anantpranali** [frappe/erpnext#34631]
Please give a feature or Button or Menu to Bulk delete the Deleted Documents. It consumes a large part of the Database.

**Comment by Solufyin** [comment]
Hi @nitin-anantpranali,

Please check it in frappe forum:
https://discuss.frappe.io/t/how-to-bulk-delete-deleted-documents/102947/2?u=ncp

Thank You!

**Comment by nitin-anantpranali** [comment]
Thank you for your reply but if I have more than 60K entries, its a very time consuming task and it also consumes my daily time limit on Frappe Cloud.

So those entries consumes sizeable data space and deletion consumes the daily time limit.

**Comment by Nihantra-Patel** [comment]
For this, you can use the [System Console](https://frappeframework.com/docs/user/en/desk/scripting/system-console).

https://www.youtube.com/watch?v=CLV0dzXGBAM

Example:

If you want to delete specific tasks from a project, check this out.

![image](https://github.com/user-attachments/assets/11b7a4cc-11a4-472d-96f3-ea8318a2726b)

It deletes the record within a minute.
