### ISSUE TITLE
Item wise Discount in Purchase Invoice

### ISSUE THREAD

**Issue by nitin-anantpranali** [frappe/erpnext#34633]
There is no provision for Item wise Discount in Purchase Invoice.
Will need that option from Purchase Order to Purchase Invoice

**Comment by Solufyin** [comment]
Hi @nitin-anantpranali,

First, do set the price list rate for the Item, and after do check in the purchase item table so the discount section will show.

![image](https://user-images.githubusercontent.com/34390782/228726919-00e45c64-e3d4-42d6-8928-aa21778365e3.png)

Same process for the whole purchase cycle.
Please apply and check it.

Thank You!

**Comment by nitin-anantpranali** [comment]
These fields are not there in Purchase Order

![image](https://user-images.githubusercontent.com/116695322/228738036-bfb04581-28fa-4638-9c06-5bbdb220587b.png)

**Comment by Solufyin** [comment]
Hi @nitin-anantpranali,

First do apply the price list rate, then after it will show the discount section.

Please again check it.
![image](https://user-images.githubusercontent.com/34390782/228742775-8e681793-1e95-491c-8410-69eb7413b599.png)

Thank You!

**Comment by nitin-anantpranali** [comment]
Is there any parameter in the settings somewhere to enable this feature? By Default its not there in **Purchase Order**

**Comment by Solufyin** [comment]
Hi @nitin-anantpranali,

First, please set/add an Item Price according to the price list.

![image](https://user-images.githubusercontent.com/34390782/229430433-f258121f-b32f-4db6-ac8e-b677b24b799c.png)


After then, check in the Purchase Order.
When you enter an item in which you set the item price according to the price list, then the discount section will appear.

Please check it.
![image](https://user-images.githubusercontent.com/34390782/229431035-226ad785-4784-4aab-a583-ce49279a9fde.png)

I hope you understand.
Thank You!
