### ISSUE TITLE
Paid Status for Sales Invoice

### ISSUE THREAD

**Issue by jof2jc** [frappe/erpnext#3464]
Feature suggeation:

If a invoice is partially paid, the status is still "Unpaid", it's better to have "Partially Paid" or "Not Fully Paid". Also in the invoice detail, it's nice to see Outstanding Amount and Paid Amount.

**Comment by jof2jc** [comment]
Any update on this?

**Comment by jof2jc** [comment]
Still no update for this? Tks

**Comment by rmehta** [comment]
https://erpnext.com/pricing/paid-feature-development to bump up priority?

**Comment by kossanah** [comment]
Here is what worked for me
```
{% set total_paid_amount = [] %}

{% if doc.outstanding_amount>0 %}
   {% set total_paid_amount = doc.base_rounded_total - doc.outstanding_amount %}
   <strong>Total Paid Amount:</strong> {{total_paid_amount}}
{% endif %}
```
