### ISSUE TITLE
POS 

### ISSUE THREAD

**Issue by ravi854** [frappe/erpnext#34657]
### Information about bug

POS going into continous LOOP on clicking checkout, if  "Automatically Add Filtered Item To Cart" is selected under pos profile. In version 14.20 

### Module

accounts

### Version

Frappe Version: 14.30.0
Erpnext Version: 14.20.0
![pos](https://user-images.githubusercontent.com/85276497/228780505-6f3014c5-fd82-4914-8cf7-e3539ba950e3.gif)

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
Hi @ravi854,

Kindly upgrade to version 14 or 15, then refresh and check again because lots of bugs fixed in the new version.

Everything is working fine. No problems were encountered in the latest versions 14 and 15.

Thank You!
