### ISSUE TITLE
Daily Reminder and Progress Update

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#3466]
- [ ] In Project
  - Add user table
  - Checkbox to "collect daily progress"
  - if checked, show "hour of day to collect progress"
- [ ] Make DocType **Progress Update** in Project. 
  - It will have a Progress Update table with list of users.
  - Hour of day
- [ ] Add a scheduler event (hourly)
  - Create new **Progress Update** (Progress Update for project_name on xx/yy)
  - Send email to all users asking for progress against the project
  - Don't send on holidays
- [ ] Add a scheduler event (next day morning) to send compilation. 
  - Capture all replies from Communication against that Progress Update
  - Send summary to all users

**Comment by jwrober** [comment]
I assume the email I would get as an assignee of a collection of project task would make it easy for me to provide en-masse updates to my tasks? Where would the update go? Into the notes field of the task, the comments area, ?? 

This could create a lot of email traffic.
