### ISSUE TITLE
Unable to close multi-currency invoices.

### ISSUE THREAD

**Issue by dj12djdjs** [frappe/erpnext#34676]
### Information about bug

I have truly no idea how anyone is functioning with multi-currency accounting. I'm having consistent issues when it comes to Payment Entry and Payment Reconciliation.

Payment Ledger says a supplier has 59,364.92 EUR outstanding; General Ledger says supplier has 58,710.82 EUR outstanding. Therefor there is always outstanding invoices, even when the GL shows a balance of ZERO. This is the case with every one of our multi-currency supplier accounts. 

Can it be possible the amounts should be different? It doesn't make any sense to me.

I have no problem providing a dump of GL and Payment Ledger if required to help debugging.

### Module

accounts

### Version

frappe: develop
erpnext: develop

### Installation method

manual install

**Comment by thida-bcn** [comment]
did you try exchange rate revaluation before settle payment

**Comment by deepeshgarg007** [comment]
@dj12djdjs We are aware of the issues, will try and fix those in the coming weeks

**Comment by ruthra-kumar** [comment]
@dj12djdjs With [the refactor](https://github.com/frappe/erpnext/pull/35644) on Exc Gain/Loss booking logic for Multi-Currency Invoices, this issue should be addressed.
