### ISSUE TITLE
Multi Currency Issues

### ISSUE THREAD

**Issue by ruthra-kumar** [frappe/erpnext#34680]
## Issues pertaining to Multi-Currency Invoicing in ERPNext V14

1. Invoices that has Advance Payment with Exchange Gain/Loss has incorrect outstanding amount in V14
2. Cancelling Invoice/Payment from [1] leave behind Exchange Gain/Loss JE's with references removed. Which make it hard to track from where the JE was originally generated.
3. Accounts Receivable/Payable report should have provision to include Exc Gain/Loss incurred on each Invoice

Tasks:
- [x] Don't book Exchange Gain/Loss for Sales/Purchase Orders https://github.com/frappe/erpnext/pull/35061
- [x] Refactor `Advances` section in Sales and Purchase Invoices. It should submit Journal of type `Exchange Gain/Loss` https://github.com/frappe/erpnext/pull/35644
- [x] Refactor `Payment Entry`. It should create a Journal of type `Exchange Gain/Loss` for each reference with gain/loss https://github.com/frappe/erpnext/pull/35644

**Comment by deepeshgarg007** [comment]
Related Issues 
- https://github.com/frappe/erpnext/issues/34676
- https://github.com/frappe/erpnext/issues/34605
- https://github.com/frappe/erpnext/issues/34584
- https://github.com/frappe/erpnext/issues/34407
- https://github.com/frappe/erpnext/issues/34345
- https://github.com/frappe/erpnext/issues/34754

**Comment by ruthra-kumar** [comment]
1. Payment Reconciliation
2. Advances Section in Sales/Purchase Invoice
3. Deduction section in Payment Entry

All of these book Exchange Gain/Loss amount in different ways. [1] posts a JE of type `Exchange Gain/Loss`.
[2] & [3] post GL entries directly in the parent voucher name. For all these methods, when a parent is cancelled, the exchange gain/loss is left behind.

**Comment by dj12djdjs** [comment]
> 



> 1. Payment Reconciliation
> 2. Advances Section in Sales/Purchase Invoice
> 3. Deduction section in Payment Entry
> 
> All of these book Exchange Gain/Loss amount in different ways. [1] posts a JE of type `Exchange Gain/Loss`. [2] & [3] post GL entries directly in the parent voucher name. For all these methods, when a parent is cancelled, the exchange gain/loss is left behind.

@ruthra-kumar Also know that when an invoice is reconciled to a payment entry using the payment reconciliation tool, if the invoice is cancelled; exchange gain and loss is left behind, and you will not be able to assign the full paid amount to invoices because unallocated_amount = paid_amount - (total_deductions *(exchange gain/loss left behind)* * exchange_rate)

Therefor even if you've paid supplier, or customer has paid you. If a payment entry has this bug and if this payment entry is in a closed period. You will not be able to close invoices even though GL will be zero.

**Comment by ruthra-kumar** [comment]
> 1. Payment Reconciliation
> 2. Advances Section in Sales/Purchase Invoice
> 3. Deduction section in Payment Entry
> 
> All of these book Exchange Gain/Loss amount in different ways. [1] posts a JE of type `Exchange Gain/Loss`. [2] & [3] post GL entries directly in the parent voucher name. For all these methods, when a parent is cancelled, the exchange gain/loss is left behind.

One single approach - Post a JE of type `Exchange Gain/Loss`, will be used by all. So, if the parent voucher(Sales Invoice or Payment Entry) is cancelled, this JE will also be cancelled.

@dj12djdjs

**Comment by RJMHASKE** [comment]
When this issue is resolve?? or any alternate options??
