### ISSUE TITLE
[Gross Profit] Delivery Note Link issue

### ISSUE THREAD

**Issue by saurabh6790** [frappe/erpnext#3469]
Hello Team,

In gross profit report, link field not working for delivery note . 
When we click on DN, url shows "http://localhost:8000/desk#Form/Sales%20Invoice/DN-00001".

In previsous versions, there are two columns one shows DN and SI number where second one is for linking.

Can we provide two links to sigle column or we have to redesign it as per previsous versions, please suggest? I will fix it and send pull request.

**Comment by rmehta** [comment]
Suggest something and send a pull-request. Always easy to discuss against a pull-request.

**Comment by sbkolate** [comment]
@saurabh6790  can you replicate this in demo.v5? 
I didn't see Delivery note number in gross profit report.

for combining link, you can use dynamic link, see Stock Ledger report for dynamic link of Purchase Receipt, Stock Entry and Delivery Note.
https://demo.erpnext.com/desk#query-report/Stock%20Ledger
Code:
https://github.com/frappe/erpnext/blob/develop/erpnext/stock/report/stock_ledger/stock_ledger.py#L31

**Comment by nabinhait** [comment]
The issue has been fixed some days ago. Previously it was delivery note link, now the report always shows sales invoice id. Closing the issue.
