### ISSUE TITLE
Deleting the first company you make breaks Purchase Order Trends

### ISSUE THREAD

**Issue by livtanong** [frappe/erpnext#34691]
### Information about bug

# Summary
Deleting the first company you make (The one that you enter the details to during first Setup) causes a lot of issues
- "Company is Mandatory" error in Purchase Order Trends
- Issues submitting a purchase order (If you create a purchase order with the first company, delete that company, then try to assign that purchase order to another company, things break)
- Possibly more stuff that I haven't uncovered.

# Minimal Repro
1. From a clean installation...
2. Set up a company (Company A)
3. Create a new company (Company B)
4. Create a sample item (NOT a variant, track stock)
5. Create a sample purchase order
6. Add sample item onto purchase order, and create a dummy supplier
7. Save purchase order
8. Delete the company (refresh the browser just to be sure)
9. Open the purchase order that you just made
10. Resolve the various reference errors that pop up. For example, assign company to Company B. Fix the warehouses, etc...
11. Submit the order (it's possible to see more errors)
12. Refresh
13. Go to Dashboard Chart List
14. Search for and open Purchase Order Trends
15. You'll see "Company is Mandatory".

<img width="999" alt="image" src="https://user-images.githubusercontent.com/869638/229205489-9d744c60-5a31-454f-a0c1-991c14c929ba.png">

We cannot edit the filter because it's a standard chart, and duplicating the chart does not remove its standard-ness (which I think is itself a bug). You can attempt to recreate the chart from scratch, and the only way to make it work is if you set the Company.

This tells me that the First Company (the one created in the setup wizard) is somehow special, and there are things generated that have an implicit reference to this first Company. This is problematic because if the first Company is so special, deleting it should be disallowed. I would recommend having some way of specifying a primary company.

### Module

other

### Version

ERPNext Version - 14.19.0

### Installation method

None

**Comment by Nihantra-Patel** [comment]
Hi @livtanong,

Yes, that's correct. I elaborated further on that matter. If you assign a company to a user, but the company gets deleted or isn't set as the "global default," you'll encounter this error. When you delete a company, you must ensure it's set as the global default. Otherwise, you'll face this error on every dashboard and report. We followed your instructions, but when you delete the company, it also gets removed from the global default setting.

Thank You!
