### ISSUE TITLE
bug: Item description font colour reverts to black upon saving

### ISSUE THREAD

**Issue by ahmadpak** [frappe/erpnext#34705]
### Information about bug

Item description font colour reverts to black upon saving. 

![Kapture 2023-04-02 at 13 50 52](https://user-images.githubusercontent.com/7881486/229342747-c17df4ab-9070-40fc-804f-f0c0c3a4ba8a.gif)

### Module

stock

### Version

Frappe Framework: v14.29.2 (HEAD)
ERPNext: v14.19.0 (HEAD)

### Installation method

FrappeCloud

**Comment by Solufyin** [comment]
Hi @ahmadpak,

If you haven't tried then please check the full video and try it.
Maybe your issue will solve.


https://user-images.githubusercontent.com/34390782/229438817-4acfd983-cd5e-47e7-8270-8df501225694.mp4

</br>
Thank You!

**Comment by ahmadpak** [comment]
@Solufyin It solved the issue, thank you. I will test it in detail. Any idea when is this option beneficial?

**Comment by Solufyin** [comment]
Hi @ahmadpak,

More details for, please check it documentation.
https://docs.erpnext.com/docs/v14/user/manual/en/stock/stock-settings#6-convert-item-description-to-clean-html

Thank You!
