### ISSUE TITLE
Customer can't see Project in Portal

### ISSUE THREAD

**Issue by chrisdent** [frappe/erpnext#34706]
### Information about bug

Steps to reproduce:

Created a Customer.
Created two web site users
Created two contacts associated to Customer and associated a user to each.
Created a Project.
Project customer: The customer created.
Users both users.

As a matter of fact, followed this instructions: https://docs.erpnext.com/docs/v14/user/manual/en/projects/project-customer-portal

Logging as each user when trying to Projects it appears: Not Permitted

### Module

projects

### Version

ERPNext: v14.19.0 (version-14)
Frappe Framework: v14.29.0 (version-14)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
None.
```

**Comment by Solufyin** [comment]
Hi @chrisdent,

For that, please set the Guest rights for Project viewing.

![image](https://user-images.githubusercontent.com/34390782/229435592-7003a85e-8411-4d58-862b-c966676ceeb5.png)

Thank You!

**Comment by chrisdent** [comment]
Applying this will let the customer have access to all projects and not only the ones it should.

**Comment by mehrdd** [comment]
Same here.
