### ISSUE TITLE
Purchase Order - Required Date Problem

### ISSUE THREAD

**Issue by nitin-anantpranali** [frappe/erpnext#34714]
### Information about bug

On one of our FC Site
While entering a New Purchase Order, the Required Date is getting changed automatically. It shows garbage date instead of user selected date.

<img width="1175" alt="image" src="https://user-images.githubusercontent.com/116695322/229465207-979af423-39c5-4ff3-ab54-7d334ee66984.png">

### Module

buying

### Version

ERPNext: v14.20.0 (HEAD)
Frappe Framework: v14.30.0 (HEAD)
India Compliance: v14.4.0 (HEAD)
Payments: v0.0.1 (HEAD)

### Installation method

None

**Comment by rehanrehman389** [comment]
Hello,

I tried to reproduce the bug, but I couldn't.

Regards,
Rehan Ansari

**Comment by rohitwaghchaure** [comment]
@nitin-anantpranali Required By date field present in the Line Item (item child table) which you have to add manually or it get copied from Parent form Required By date field. In case if you change the Required By date field value in the line item(child table) then system reset the Required By date field value in the parent form. If this is the case happening with you then this is not a bug but a feature

<img width="1319" alt="Screenshot 2023-04-06 at 2 37 04 PM" src="https://user-images.githubusercontent.com/8780500/230330953-3a4dac9e-5ad3-41e7-9298-54a92ccad875.png">
