### ISSUE TITLE
How to Fetch data?

### ISSUE THREAD

**Issue by 0xjjad** [frappe/erpnext#34734]
I just created a custom fields in the timesheet to fetch the hours base on the Activity type (also using client script to work; fetch the hours).
as you can see on the screenshot below

![Screen Shot 2023-04-04 at 5 01 14 PM](https://user-images.githubusercontent.com/128226873/229765189-77ceb489-38b7-4aba-86fd-54f5cadd4ef1.jpg)

Also i created another custom fields in the Salary Slip Timesheet as you can see on the screenshot.

Now my problem is, how to fetch the data from Time Sheets “Regular Hours” and “Overtime Hours” to my Salary Slip Timesheet and also showing in the Earnings component.

Please help me. Thank you!

**Comment by s-aga-r** [comment]
Please ask your queries on our Telegram Group: https://t.me/frappeframework
