### ISSUE TITLE
solar hijri calendar

### ISSUE THREAD

**Issue by MiladHossein** [frappe/erpnext#3473]
hi
please let me know how i can add persian calendar to this application. This link is template of js persian calendar.
http://farhadi.ir/projects/jalalijscalendar/

**Comment by rmehta** [comment]
You will have to extend the standard JQuery datepicker:

https://github.com/frappe/frappe/blob/develop/frappe/public/js/frappe/form/control.js#L492

**Comment by mhbu50** [comment]
+1

**Comment by me2ne** [comment]
Hello @MiladHossein and @mhbu50 
I add this issue in bounty source , hope you can contribute to add this calendar to ERPNEXT . 

bounty source link is : https://www.bountysource.com/issues/22105311-solar-hijri-calendar
Regards
Meisam

**Comment by AWDGroup** [comment]
Any update on this? 
I think ERPNext should add the support to choose between different calendar types such as Solar Hijri (Jalali), Chinese, etc as the base calendar for the whole system. This includes a date picker for all the forms and the correct date format in all the reports, PDFs and etc.

**Comment by AWDGroup** [comment]
The simplest method that I can come up with, is to use Gregorian calendar in DB and have functions to convert TO and FROM other calendar types in both Python and Javascript to show it on the forms and reports. (we probably need to have a special date picker based on the calendar system)
This way the user can change the calendar type at any moment without affecting the data itself.

**Comment by AWDGroup** [comment]
I found a great library to use Jalali dates in Python:
https://github.com/slashmili/python-jalali

**Comment by me2ne** [comment]
It's one of important feature erpnext need it to use globally . hope some one can add this feature . 
any one can help please bounty in  bountysource to add jalai dates in erpnext . 
 https://www.bountysource.com/issues/22105311-solar-hijri-calendar

**Comment by PawanMeh** [comment]
There exists issue #8874 for tracking this, hence closing this one.

**Comment by abehnamfard** [comment]
+1

**Comment by alkuhlani** [comment]
+١
