### ISSUE TITLE
Invalid Date when I choose using picker

### ISSUE THREAD

**Issue by justinlusg** [frappe/erpnext#3474]
Under Human Resource > Leave Application > Calendar I will get an error when I change the dates manually using the date picker. It does not happen on other instance, only happens to this particular one on production.

![image](https://cloud.githubusercontent.com/assets/12539216/8166365/ee2d249c-13c9-11e5-80e4-9dcd47419c0c.png)

**Comment by justinlusg** [comment]
Ok after some testing.. i guess this happens when I use the picker to choose a date and it automatically fills up 26-06-2015 (dd-mm-yyyy) which is the date format in my country. However, I think the calendar only reads mm-dd-yyyy, hence the error.

**Comment by anandpdoshi** [comment]
Hi @justinlusg 
I found a similar problem though it was caused when I cleared the filter: https://github.com/frappe/frappe/issues/1161

Can you show me what you have as Date Format in Setup > System Settings?

**Comment by justinlusg** [comment]
![image](https://cloud.githubusercontent.com/assets/12539216/8224775/f4b72d48-15be-11e5-89c0-1e2dfb2d91d0.png)
