### ISSUE TITLE
Payment Entry Issue in Multi Currency Transactions- Advance payment done in one exchange rate and PI book in diff. exchange rate

### ISSUE THREAD

**Issue by RJMHASKE** [frappe/erpnext#34754]
### Information about bug

Information about bug

While doing purchase transaction in multi currency with advance payment made with one exchange rate and after material receipt exchange rate changed that time payment entry issue

My company base currency is INR and I have made Purchase order in USD with exchange rate- 80 USD.
![image](https://user-images.githubusercontent.com/119041865/230041768-15e482e1-57a9-4221-ac6c-eb29ba32c669.png)

I have made 50% advance payment against this PO to Supplier with exchange rate 80 USD
![image](https://user-images.githubusercontent.com/119041865/230041899-6efd2379-12e6-4930-bec8-39df4da1692f.png)

Material receipt at our company but exchange rate changed , I have made purchase receipt against this PO with exchange rate- 82 USD
![image](https://user-images.githubusercontent.com/119041865/230041998-76510232-26f5-4ae3-bf5c-2e67979c8672.png)

Chart of A/C Shows correct value for advance payment before material receipt and PI booking
![image](https://user-images.githubusercontent.com/119041865/230042133-7d3a1e0f-fbd0-4faf-9d69-85d4db6e8cb8.png)

Purchase Invoice booked against purchase receipt with exchange rate 82 USD and advance payment entry link to PI (exchange rate 80 USD for advance payment)
![image](https://user-images.githubusercontent.com/119041865/230042579-86277a06-0408-413c-81e4-96c7a3e7e217.png)

In Chart of A/C Creditor A/c show 487.80 USD/41000.00INR and In Exchange gain & loss - 1000 INR (system auto calculate advance payment exchange gain & Loss amount which is correct ) but USD amount wrong
![image](https://user-images.githubusercontent.com/119041865/230042710-5bb42ed0-a5ab-406e-a21f-b2bbf74ff613.png)

Supplier Ledger & Trial Balance report
![image](https://user-images.githubusercontent.com/119041865/230042821-6ffc38d6-e038-4974-b020-36f49ce7cb1a.png)

![image](https://user-images.githubusercontent.com/119041865/230042900-6d462fd5-a4cd-49b1-ab84-d5b5335ab66b.png)

In Purchase Invoice advance paid 500 USD & Pending amount 487.80 USD
![image](https://user-images.githubusercontent.com/119041865/230042995-c27e10f3-f6d6-49d8-bb93-832521c15292.png)

I have making pending amount payment entry against booked PI
![image](https://user-images.githubusercontent.com/119041865/230043152-2946856e-a281-4bbd-8688-2e7a09ca64d1.png)

I have manual change pending amount 41000 INR and set 1000 INR in Exchange gain & loss A/c
![image](https://user-images.githubusercontent.com/119041865/230043248-c47f04fa-90da-4539-8b07-e74533240f23.png)

Trial Balance & Supplier Ledger show 1000 INR balance
![image](https://user-images.githubusercontent.com/119041865/230043336-5c4fbd57-0a97-4412-9923-ab97dda833bc.png)

![image](https://user-images.githubusercontent.com/119041865/230043431-cbcc5294-a70f-42bc-b472-741cc3ae8431.png)

Chart of A/c GL Creditor USD- Zero and In INR 1000 Pending and Exchange gain & Loss GL - Zero
![image](https://user-images.githubusercontent.com/119041865/230043510-cf6552b9-47e5-48ab-90ae-54ee2267b183.png)

Please request to check this issue

### Module

accounts, buying

### Version

Version
Frappe Framework: v14.29.2 (HEAD)
ERPNext: v14.19.0 (HEAD)
India Compliance: v14.4.0 (HEAD)
Payments: v0.0.1 (HEAD)

### Installation method

FrappeCloud

**Comment by dj12djdjs** [comment]
https://github.com/frappe/erpnext/issues/34680

**Comment by RJMHASKE** [comment]
Hello Team,
when this issue will resolve???

**Comment by ruthra-kumar** [comment]
Multi-Currency refactor in https://github.com/frappe/erpnext/issues/34680 should have fixed this. Closing issue. If issue persists in the latest v14 or v15, re-open.
