### ISSUE TITLE
Production Planning Tool - Default BOM is not selected for Item

### ISSUE THREAD

**Issue by bfoxtrot** [frappe/erpnext#3475]
Using the Production Planning Tool and when I pull the SO's for the specific company everything works fine. As I move down the tool, under select items I pull in the different items from the Sales orders. It properly lists the needed items, but the default BOM is not automatically chosen for each item. 

This is reproducible after reload. 

V5.

**Comment by neilLasrado** [comment]
@bfoxtrot Is this still a Issue ? Did not replicate in my system.
