### ISSUE TITLE
Need General Ledger Format with invoice details

### ISSUE THREAD

**Issue by smbcatalyst** [frappe/erpnext#34764]
We require a general ledger format in details with invoice details. Currently the general ledger shows only Payable Amount in supplier case. When we do ledger checking with supplier details, our general ledger format is not showing invoice amount, GST amount, TDS, etc in supplier case.

e.g. If total is Rs. 100, GST is Rs. 18 and TDS deducted in that invoice is Rs. 10, then ERPNext shows Rs. 108 in general ledger. But the supplier details shows Rs. 118. For every transactions user needs to open each invoice and cross check the details. It will take hours to cross check the details of single supplier.

The purchase register report is the correct format for requirement but as it is purchase related so it is not considering payment entries.
We need a report where we can get the bifurcation as above with payment entries. 
[General_Ledger.xlsx](https://github.com/frappe/erpnext/files/11169974/General_Ledger.xlsx)

1: Current Format
![image](https://user-images.githubusercontent.com/113963271/230369359-bf584a0d-11a4-459d-82e4-ecb7fd49aaba.png)

2. Expected Format
![image](https://user-images.githubusercontent.com/113963271/230374943-fef5392b-591a-44bd-9416-394e498eb4d0.png)

3. If Possible Expected Format
![image](https://user-images.githubusercontent.com/113963271/230376209-f3c75534-7623-44cb-8305-8bcc551fed7e.png)

**Comment by deepeshgarg007** [comment]
Fixed via https://github.com/frappe/erpnext/pull/36069
