### ISSUE TITLE
Work Order Pick List - Error v14 

### ISSUE THREAD

**Issue by dineshpanchal93** [frappe/erpnext#34761]
### Information about bug

https://discuss.frappe.io/t/v14-work-order-pick-list-not-working/103271

### Module

manufacturing

### Version

"erpnext": "14.20.0",
"frappe": "14.30.0",
"hrms": "14.2.0",
"india_compliance": "14.5.1",

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	
	"erpnext": "14.20.2",
	"frappe": "14.31.0",
	"frappe_whatsapp": "0.0.2",
	"hrms": "14.2.1",
	"india_compliance": "14.5.1"
}
```
### Route
```
Form/Work Order/WO/2304/00041
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1607, in call
    return fn(*args, **newargs)
  File "apps/erpnext/erpnext/manufacturing/doctype/work_order/work_order.py", line 1474, in create_pick_list
    doc.set_item_locations()
  File "apps/erpnext/erpnext/stock/doctype/pick_list/pick_list.py", line 210, in set_item_locations
    locations = get_items_with_location_and_quantity(
  File "apps/erpnext/erpnext/stock/doctype/pick_list/pick_list.py", line 462, in get_items_with_location_and_quantity
    while remaining_stock_qty > 0 and available_locations:
TypeError: '>' not supported between instances of 'NoneType' and 'int'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"source_name": "WO/2304/00041",
		"for_qty": 0
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/erpnext.manufacturing.doctype.work_order.work_order.create_pick_list"
}
```
### Response Data
```
{
	"exception": "TypeError: '>' not supported between instances of 'NoneType' and 'int'"
}
```
```

**Comment by dineshpanchal93** [comment]
It works only when Fresh Work Order is created.

If we transfer first time the Partial qty against the work order using picklist and Stock entry is working

remaining item or shortage item needs to transfer against the work order.  ( Not Working )

**Comment by dineshpanchal93** [comment]
Can anyone look into priority!

**Comment by dineshpanchal93** [comment]
Any update on the same

**Comment by s-aga-r** [comment]
@dineshpanchal93 not able to replicate, could you please share the steps to replicate or a gif?

WO
![image](https://github.com/frappe/erpnext/assets/63660334/42923250-840e-4712-9ce2-a0d0139f9eff)

PL[1]
![image](https://github.com/frappe/erpnext/assets/63660334/71d999bc-5428-40f3-9fe1-92ac082350c5)

SE[1]
![image](https://github.com/frappe/erpnext/assets/63660334/c273f6db-7acc-433e-bce3-d4f1984989cf)

PL[2]
![image](https://github.com/frappe/erpnext/assets/63660334/085089cd-622f-4575-a92e-c9927f1fe85a)

SE[2]
![image](https://github.com/frappe/erpnext/assets/63660334/5ee6e843-820a-4a05-b9dc-9a3965aea783)

**Comment by dineshpanchal93** [comment]
Yes Sure

**Comment by dineshpanchal93** [comment]
@s-aga-r 

Please the attached video

https://github.com/frappe/erpnext/assets/21578167/4e917282-c863-44b1-a812-032c0c67fff1

**Comment by dineshpanchal93** [comment]
I can able to create the stock entry for the remaining item or shortage item. but not able to create the picklist for the same.

**Comment by s-aga-r** [comment]
@dineshpanchal93 This issue is related to https://github.com/frappe/erpnext/issues/28377, ignore Partial Transfer against Work Order. You can set **Overproduction Percentage For Work Order** in **Manufacturing Settings** as a workaround for existing Work Orders. I have raised a fix so you won't get `TypeError`.

![image](https://github.com/frappe/erpnext/assets/63660334/da7d26b7-1cd0-443a-a7b9-9eaf8b184b68)
