### ISSUE TITLE
Payroll Entry not filtering Time Sheets correctly based on Accounting Dimension

### ISSUE THREAD

**Issue by willspenc** [frappe/erpnext#34788]
### Information about bug

Explained in discussion forum ..
https://discuss.frappe.io/t/bug-in-payroll-entry/103339

But here is the detail..

Payroll Module

Employee : EMP-0001
Two projects PROJ-A ; PROJ-B
TIme sheets generated :
TS-001 for PROJ-A; 1-hour
TS-002 for PROJ-B; 1-hour
TS-003 for PROJ-B; 1-hour
( all time sheets in the same period )

When I do Payroll Entry for EMP-0001 and select PROJ-B in accounting dimension, 
then all time sheets are processed onto the payslip. ALso, the Journal entry is all 
on PROJ-B (3 hours), even though some of the cost should actually be journalled against PROJ-A
as per the setting in the Time Sheet

I am expecting that PROJ-A be excluded from the payslip, seeing that I entered the desired
project-accounting dimenstion as PROJ-B. The Payslip should only have 2 time sheets on and
only those time sheets should be journalised.

So my expectation is to find a payslip with only TS-002 , TS-003 on and a Journal for only 2 hours.

### Module

other

### Version

ERPNext: v13.49.11 (version-13)
Frappe Framework: v13.52.0 (version-13

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
No actual error message.

I found the mistake by correlating the time sheets, payslip and journal entry
```

**Comment by Nihantra-Patel** [comment]
Hi @willspenc,

Everything is working fine. No problems were encountered in the latest versions 14 and 15.

Kindly upgrade to version 14 or 15, then refresh and check again.
We no longer provide support for version 13 or older. 

If the issue occurs then please create a new issue according to version (14 or 15) with a video document if possible.

Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!
