### ISSUE TITLE
In the Stock Balance Report, Inventory Dimnesions is not getting displayed properly

### ISSUE THREAD

**Issue by JitendraSAW** [frappe/erpnext#34785]
### Information about bug

It has been noticed that in case we record 2 Stock Reconcilation Entries, it shows in the Stock Balances only 1 Dimensions Reporting and not the other Inventory Dimensions

Use Case:

1. Record 1 Stock reconcilation Entry with Inventory Dimensions created. In my Example- Third Party Customer Name: Krishna
<img width="926" alt="image" src="https://user-images.githubusercontent.com/80260184/230707588-f76b072b-a3c1-4283-b568-566b20ed156b.png">

2. Record the another Stock reconcilation Entry with the Other Dimensions Name.In my Example- Third Party Customer Name: Jitendra
<img width="927" alt="image" src="https://user-images.githubusercontent.com/80260184/230707611-73e53329-5dcd-445b-895d-c372d3c6ecd2.png">

Now if you check the Stock Balances Reports without any filter, it shows only for 1st Voucher Which we have done-i.e. Krishna
and not Jitendra

<img width="932" alt="image" src="https://user-images.githubusercontent.com/80260184/230707694-80553efe-d6da-4712-afc2-45c011b81c53.png">

Even if we filter through itemwise then also  it takes the first entry inventory dimensions only

<img width="939" alt="image" src="https://user-images.githubusercontent.com/80260184/230707761-2aa3543f-d322-4ff9-985b-f2575db83579.png">

Even if we filter through Warehousewise, then it is also it is capturing only 1 Inventory Dimensions and that too of the 1st Voucher Saved

<img width="928" alt="image" src="https://user-images.githubusercontent.com/80260184/230707806-409503c0-730e-4041-8ede-9642c14dba9d.png">

It is showing only when we filter with the inventory dimensionswise

<img width="920" alt="image" src="https://user-images.githubusercontent.com/80260184/230707849-ece16180-5283-47b4-9934-937df6a26aff.png">

Also in case of  Inventory Dashboards, in the Item Master, Even the  Qty of that Inventory dimensions say in my case Jitendra- is not getting reflected 

<img width="800" alt="image" src="https://user-images.githubusercontent.com/80260184/230707964-bf71f0fc-2be9-4e67-8f12-40e33f8f4bb9.png">
 

### Module

stock

### Version

<img width="416" alt="image" src="https://user-images.githubusercontent.com/80260184/230708001-529ffb5b-163a-4bbb-86f9-f9fbe5cd961e.png">

### Installation method

FrappeCloud

**Comment by s-aga-r** [comment]
@JitendraSAW 

`Also in case of Inventory Dashboards, in the Item Master, Even the Qty of that Inventory dimensions say in my case Jitendra- is not getting reflected`

The `Posting Time` of the Stock Reconciliation **MAT-RECO-2023-00003** is greater than the Stock Reconciliation **MAT-RECO-2023-00004** so the Item master Dashboard is showing the correct Qty which is 15 in your example.

**Comment by JitendraSAW** [comment]
There should be any issue for the Timing Difference as we are checking the Stock balance Report where we are not defining any Timing. It shows as the Totality. Can you just eloborate more on this?

Please try to resolve this issue as our Stock Reports based on the Inventory dimensions is not showing properly. In case you can check from your end by following the above use Case and then check the same and guide us what is the correct way.
Also we are ready to have a call on this.

**Comment by s-aga-r** [comment]
@JitendraSAW 

The Stock Balance represents the total quantity and balance of a item and warehouse combination. It is calculated by combining the values of the quantity and balance fields, using the item and warehouse as the key for consolidation. However, when multiple inventory dimensions are involved, the Stock Balance will only display the dimension that was utilized in the most recent transaction.

We will have an internal discussion to explore possible solutions. Once we have reached a decision, we will inform you of any actions we plan to take in order to address this issue effectively.

**Comment by rohitwaghchaure** [comment]
@JitendraSAW 

I have tested locally and it's working fine.

The First Stock Reco you have set the Posting Time as "12:06:17", where as in the second stock reco you have set the posting time as "12:05:42".  Which meant the second entry was the backdated entry.

Have you created backdated stock reco entry? if yes what's the status of the reposting?

**Comment by basdereus84** [comment]
I believe there is a potential area for improvement in how ERPNext handles inventory dimensions, particularly in the Stock Balance Report and possibly the Item Dashboard.

Consider a scenario where we have two inventory dimensions: Bin001 and Bin002. Suppose we allocate 5 pcs of Item A to Bin001 and 10 pcs to Bin002. In the current system, if the Stock Balance Report aggregates these quantities without differentiating between the bins, it will display a total of 15 pcs for Bin002. This aggregation obscures the specific quantities in each bin.

I think being able to differentiate between inventory dimensions in reports is crucial for accurate inventory management. It could be that I'm misunderstanding the functionality, but it seems logical that there should be a way to clearly distinguish between different dimensions.

Is there a workaround or a setting that I might be missing? Any insights or suggestions on how to achieve this differentiation would be greatly appreciated.

**Comment by Nihantra-Patel** [comment]
fixed: #37373


Kindly upgrade to version 14 or 15, then refresh and check again because lots of bugs fixed in the new version.
