### ISSUE TITLE
Point of sales Page Bug

### ISSUE THREAD

**Issue by yousra-mansour** [frappe/erpnext#34791]
### Information about bug

the is a bug on Point of Sales Page
when the user scans the item by search field and put the barcode for items this error appears
![LwfnrFY](https://user-images.githubusercontent.com/66638972/230770876-a0025242-a6f1-4e67-b564-6372e0ea70d8.png)
 you should be able to handle the case when there is no uom in the barcode
also, you fetch a stock_uom column that does not exist in the Item Price
this is the piece of code that has all the problem
![image](https://user-images.githubusercontent.com/66638972/230771075-cf434be5-2d30-4e46-bc31-31a323c9bfc4.png)

### Module

selling

### Version

frappe V14
ERPNext V14.20.3

### Installation method

docker

**Comment by Nihantra-Patel** [comment]
Hi @yousra-mansour,

It’s working properly in the latest version 14 so please upgrade your version and then check it.

https://github.com/Nihantra-Patel/view_video/assets/141945075/9cf5d16d-059d-4db5-8c8c-30b615387954

Reference: https://discuss.frappe.io/t/pos-barcode-error/117127/2?u=ncp

Thank You!
