### ISSUE TITLE
Issue with Gross profit for return invoices

### ISSUE THREAD

**Issue by maveezmh** [frappe/erpnext#34796]
### Information about bug

When Sales invoice is created the GP is booked as following below

![GP for Sales](https://user-images.githubusercontent.com/112148467/230848571-cbece941-9c9f-427e-bed9-f3b166a4b191.png)

and when we create a credit note against same invoice the credit note is not reducing/removing the GP from gross profit.

![GP when credit](https://user-images.githubusercontent.com/112148467/230848683-cc60fb29-c1d2-4975-88c7-4c07d956a7fe.png)

This is giving wrong GP for the given fate range.

### Module

selling

### Version

ERPNext: v14.20.0 (HEAD)
Frappe Framework: v14.30.0 (HEAD)
Frappe HR: v14.2.0 (HEAD)
Payments: v0.0.1 (HEAD)

### Installation method

FrappeCloud

**Comment by maveezmh** [comment]
any update??

**Comment by maveezmh** [comment]
@deepeshgarg007 Can you please check into this?

**Comment by maveezmh** [comment]
Hey There any update on above concern???

**Comment by ljain112** [comment]
Fixed in :https://github.com/frappe/erpnext/pull/44323
