### ISSUE TITLE
Purchase Invoice - Limit Crossed

### ISSUE THREAD

**Issue by Thrivenibrevera** [frappe/erpnext#34795]
### Information about bug

Dear Team,

We are facing issue while submitting Purchase invoice of [BILL-0636] as Limit crossed and we are unable submit the document.

Please help in this condition.

PO04991- Purchase Order No.
GRN09363 - Purchase Receipt No.

![WhatsApp Image 2023-04-08 at 4 33 46 PM](https://user-images.githubusercontent.com/130228891/230833375-0fa5e8b2-f31c-49dc-bbf0-d59380d5b217.jpeg)

### Module

accounts, stock, buying

### Version

ERPNext: v13.49.11 (HEAD)
ERPNext Support: v0.2.1 (HEAD)
Frappe Framework: v13.52.0 (HEAD)
Journeys: v0.0.1 (HEAD)

### Installation method

FrappeCloud

**Comment by PITPL-Akshay-Prajapati** [comment]
you have entered 1000 qty over then mentioned in purchase order. you need to allow over quantity from buying setting.

**Comment by Thrivenibrevera** [comment]
Dear Team,

We are getting over the limit for Rs. 1000 not for Qty.

Please clarify





--
*Regards,*
*Thriveni S*

*Purchase Executive*
Brevera Technologies Pvt. Ltd.,
Ph: 81974 22622
http://www.brevera.in/

https://www.youtube.com/watch?v=Y3Ds-o6lKLI

https://www.youtube.com/watch?v=RxufwyKEWcE

https://youtu.be/IGPPB1UhoVk

**Comment by Thrivenibrevera** [comment]
Dear Team,

ANy updates?






--
*Regards,*
*Thriveni S*

*Purchase Executive*
Brevera Technologies Pvt. Ltd.,
Ph: 81974 22622
http://www.brevera.in/

https://www.youtube.com/watch?v=Y3Ds-o6lKLI

https://www.youtube.com/watch?v=RxufwyKEWcE

https://youtu.be/IGPPB1UhoVk

**Comment by PITPL-Akshay-Prajapati** [comment]
Have you changed price for this product in Purchase invoice?
If yes, You need to allow over billing from this item master.

**Comment by Thrivenibrevera** [comment]
Dear Team,

We have making Purchase invoice against purchase receipt, while making
purchase receipt we have changed the price from Rs.0.30/- to Rs. 0.25/-

Please clarify ,Why Rs.1000 we are getting Limit crossed while submitting
purchase invoice?

*What will be the solution for this issue?*

Have you changed the price for this product in the Purchase invoice?  - In
Purchase invoice* NO*
If yes, You need to allow over billing from this item master. - It will
create problem in accounting or In Accounting ledger?





--
*Regards,*
*Thriveni S*

*Purchase Executive*
Brevera Technologies Pvt. Ltd.,
Ph: 81974 22622
http://www.brevera.in/

https://www.youtube.com/watch?v=Y3Ds-o6lKLI

https://www.youtube.com/watch?v=RxufwyKEWcE

https://youtu.be/IGPPB1UhoVk

**Comment by Thrivenibrevera** [comment]
Dear Team,

Gentle reminder.





--
*Regards,*
*Thriveni S*

*Purchase Executive*
Brevera Technologies Pvt. Ltd.,
Ph: 81974 22622
http://www.brevera.in/

https://www.youtube.com/watch?v=Y3Ds-o6lKLI

https://www.youtube.com/watch?v=RxufwyKEWcE

https://youtu.be/IGPPB1UhoVk

**Comment by Thrivenibrevera** [comment]
Dear team,

Awaiting for your updates on the issue below.







--
*Regards,*
*Thriveni S*

*Purchase Executive*
Brevera Technologies Pvt. Ltd.,
Ph: 81974 22622
http://www.brevera.in/

https://www.youtube.com/watch?v=Y3Ds-o6lKLI

https://www.youtube.com/watch?v=RxufwyKEWcE

https://youtu.be/IGPPB1UhoVk

**Comment by s-aga-r** [comment]
@Thrivenibrevera please raise a support ticket for the same on https://frappe.io/support
