### ISSUE TITLE
Batch No - Selection Dialog Box Not Reflect

### ISSUE THREAD

**Issue by dineshpanchal93** [frappe/erpnext#34828]
### Information about bug

https://user-images.githubusercontent.com/21578167/231363650-f283d5e9-7698-4eb5-97e0-4d7a739ef831.mov

### Module

stock, manufacturing

### Version

ERPNext: v14.21.0 (version-14)
Frappe Framework: v14.32.0 (version-14)
Frappe Whatsapp: v0.0.2 (master)
Frappe HR: v14.2.1 (version-14)
India Compliance: v14.5.3 (version-14)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
The batch No Selection Dialog box is not displayed and When clicking on ESC Button we can able to return to the main page.


Also, this was working fine before. latest release
```

**Comment by dineshpanchal93** [comment]
@rohitwaghchaure can you please look it into.

**Comment by dineshpanchal93** [comment]
Anyone can please check this issue.

**Comment by dineshpanchal93** [comment]
Because of these changes https://github.com/frappe/frappe/commit/8d4402e98bc8c7e123e42b2c14619ff85ad4b3f3

**Comment by dineshpanchal93** [comment]
@ankush this is not resolved

**Comment by ankush** [comment]
https://github.com/frappe/frappe/pull/20706

it is, release pending.

**Comment by dineshpanchal93** [comment]
Ok Thanks
