### ISSUE TITLE
Issue while creating Purchase Order and Purchase Receipt 

### ISSUE THREAD

**Issue by Thrivenibrevera** [frappe/erpnext#34827]
### Information about bug

Dear Team,

We are getting Bug while creating Purchase Order and Purchase Receipt, Its not taking SAVE, we will get popup as per image below.

Please guide us to solve this issue.

![WhatsApp Image 2023-04-12 at 10 06 47 AM](https://user-images.githubusercontent.com/130228891/231351602-d8155be9-61a4-4c11-8649-aa46d36e8e10.jpeg)

### Module

stock, buying

### Version

ERPNext: v14.20.3 (HEAD)
ERPNext Support: v0.2.1 (HEAD)
Frappe Framework: v14.31.0 (HEAD)
India Compliance: v14.5.1 (HEAD)
Journeys: v0.0.1 (HEAD)

### Installation method

FrappeCloud

**Comment by dineshpanchal93** [comment]
Please check your GST Settings and Install the India Compliance App

**Comment by s-aga-r** [comment]
Related to India Compliance App GST Settings, **Input** Account might be unset.
