### ISSUE TITLE
Wrong Stock Balance Showing 

### ISSUE THREAD

**Issue by dineshpanchal93** [frappe/erpnext#34833]
### Information about bug

<img width="1097" alt="Screenshot 2023-04-12 at 3 47 47 PM" src="https://user-images.githubusercontent.com/21578167/231428738-e84dd5b5-a8a0-417c-9bee-c92d8a43fb99.png">

<img width="1160" alt="Screenshot 2023-04-12 at 3 48 10 PM" src="https://user-images.githubusercontent.com/21578167/231428825-3551cc50-c487-4853-b0e8-344fa8620789.png">

<img width="959" alt="Screenshot 2023-04-12 at 3 49 00 PM" src="https://user-images.githubusercontent.com/21578167/231429038-52f63609-a52a-4da2-84a0-7bbac690929a.png">

### Module

stock

### Version

ERPNext: v14.21.0 (version-14)

Frappe Framework: v14.32.1 (version-14)

Frappe Whatsapp: v0.0.2 (master)

Gatepass: v0.0.1 (main)

Frappe HR: v14.2.1 (version-14)

India Compliance: v14.5.3 (version-14)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Wrong Stock Balance Reports
```

**Comment by s-aga-r** [comment]
@dineshpanchal93 might be related to https://github.com/frappe/erpnext/pull/34808 and can be easily fixed by reposting the stock reconciliation.

**Comment by dineshpanchal93** [comment]
Its has been resolved by the re-posting.

But it should be effect on immediate basis.

May be some improvement required
