### ISSUE TITLE
Can not create Sales Order from Quotation

### ISSUE THREAD

**Issue by Craftint** [frappe/erpnext#34831]
### Information about bug

When submitting the quotation, create button is missing (to create Sales Order), and all doctypes connections are missing

![image](https://user-images.githubusercontent.com/67686213/231409204-3dacf64f-d468-47ac-a928-e7352431552e.png)

### Module

selling

### Version

ERPNext v13.49.12
Frappe v13.53.0

### Installation method

FrappeCloud

**Comment by muchai** [comment]
Probably related.
https://github.com/frappe/erpnext/issues/34829

Fixed here:
https://github.com/frappe/frappe/pull/20658

**Comment by deepeshgarg007** [comment]
@Craftint Issue should be resolved, please update your site
