### ISSUE TITLE
The description in the quotation row doesn't appeared

### ISSUE THREAD

**Issue by ashcoft** [frappe/erpnext#34836]
### Information about bug

The description in quotation row 1 doesn't appear 
![image](https://user-images.githubusercontent.com/1115854/231552219-1fc92ff5-b8fb-4737-ad71-a7e90488ec9f.png)
it should be like this one
![image](https://user-images.githubusercontent.com/1115854/231552916-598e5c98-c90a-49ab-a514-b4fe535ae547.png)

 

### Module

selling

### Version

Installed Apps

Business Theme V14: v0.0.1 (main)

ERPNext: v14.21.0 (version-14)

Frappe Framework: v14.32.0 (version-14)

Frappe HR: v14.2.1 (version-14)

Payments: v0.0.1 (develop)

### Installation method

Manual installation

**Comment by nihantra** [comment]
Hi @ashcoft,

Please check in row 1.
If Item Code and Item Name are the same then will only display Item Code but if Item Code and Item Name are different then will show like => Item Code: Item Name

Please check your Item Code and Item Name.

And then reload and check it.

Thank You!

**Comment by deepeshgarg007** [comment]
@ashcoft You can add the description column in Grid View, doesn't look like a bug. Closing this issue
