### ISSUE TITLE
Project Name is not Appearing only Code is Visible in Purchase Invoice

### ISSUE THREAD

**Issue by SandeshMoolya** [frappe/erpnext#34839]
### Information about bug

Initially while doing Purchase Invoice we use select Project Name and same was appearing in  the Purchase Invoices as well once after successfull submission.But once after updation instead of Project name,project code was appearing in the Purchase.This is really worried if we dump export to excel.
![image](https://user-images.githubusercontent.com/130632680/231662333-98858ac6-5b6a-49f4-b20b-09c5da2d103a.png)
![Capture](https://user-images.githubusercontent.com/130632680/231662421-bbacb6ae-975a-49b9-a647-5919f1263d2c.JPG)
 

### Module

accounts, projects

### Version

Website: https://frappeframework.com/
ERPNext: v13.49.11 (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
Quick help on this would be highly appreciated
```

**Comment by SandeshMoolya** [comment]
Any updates on the issue?

**Comment by SandeshMoolya** [comment]
Any updates on the issue

**Comment by precihole** [comment]
Hello,

You can add one field **Project Name** and fetch name of the project using fetch from option.

**Comment by SandeshMoolya** [comment]
Hi , How do we add field Project name in the Purchase Invoice , Not getting any options
![image](https://user-images.githubusercontent.com/130632680/233300799-d36c0aac-a932-4560-aac6-c5c44fd829de.png)

**Comment by precihole** [comment]
Hello,

Using Customize Form option.

Try to give System Manager role in you user account.

**Comment by SandeshMoolya** [comment]
Hi , Guide me the path where do I get that options

**Comment by s-aga-r** [comment]
> Hi , Guide me the path where do I get that options

@SandeshMoolya 

related docs:

- https://docs.erpnext.com/docs/v13/user/manual/en/customize-erpnext/customize-form

- https://frappeframework.com/docs/v14/user/en/guides/app-development/fetch-custom-field-value-from-master-to-all-related-transactions

can also ask for help in our telegram group: https://t.me/frappeframework
