### ISSUE TITLE
Issues observed in updating to Version 13.49.12

### ISSUE THREAD

**Issue by JitendraSAW** [frappe/erpnext#34840]
### Information about bug

Team,

It has been observed that many of issues we are getting encountering in the version 13.49.12

1. No Create Button is coming from Quotation to Sales Order and also need to check in other documents also Create Button is not coming, even checked the Roles and permission , it has been provided

<img width="942" alt="image" src="https://user-images.githubusercontent.com/80260184/231672972-5b4c0058-6b62-4b42-afc6-41cb88914dc3.png">

2. Unable to change the Price List earlier it was allowing in the Version 13.49.11

In version 13.49.12
<img width="935" alt="image" src="https://user-images.githubusercontent.com/80260184/231673515-469b7c89-b082-4d65-94da-96644534b706.png">

In Version 13.49.11, it is allowing to change

<img width="943" alt="image" src="https://user-images.githubusercontent.com/80260184/231673901-af777be7-a82c-47f6-a4a6-a1ac7887e874.png">

### Module

selling

### Version

<img width="427" alt="image" src="https://user-images.githubusercontent.com/80260184/231676365-c1dae155-f993-4c2d-bf99-921715c7832a.png">

### Installation method

FrappeCloud

**Comment by deepeshgarg007** [comment]
@JitendraSAW This should be resolved, please update your site and check
