### ISSUE TITLE
STOCK RAW MATERIAL  ITEM ISSUE-CR 2032-PCB MOUNT

### ISSUE THREAD

**Issue by kavithabrevera** [frappe/erpnext#34855]
### Information about bug

CR 2032-PCB MOUNT raw material item is while opening through stock-item-its stock level showing  r&d -905# in stock ledger-400# , stock level showing mysore-stores-370# in stock ledger-875 # & below their its details link PLease refer that one. & correct it as soon as possible.many times getting this issue why this issue will create again & again ?

[CR 2032-PCB MOUNT - STOCK LEDGER.pdf](https://github.com/frappe/erpnext/files/11230346/CR.2032-PCB.MOUNT.-.STOCK.LEDGER.pdf)
[CR 2032-PCB MOUNT - stock levels details.pdf](https://github.com/frappe/erpnext/files/11230348/CR.2032-PCB.MOUNT.-.stock.levels.details.pdf)
[CR 2032-PCB MOUNT-STOCK LEDGER-R&D.pdf](https://github.com/frappe/erpnext/files/11230349/CR.2032-PCB.MOUNT-STOCK.LEDGER-R.D.pdf)

### Module

stock

### Version

https://brevera.erpnext.com

### Installation method

None

**Comment by s-aga-r** [comment]
@kavithabrevera please raise a support ticket for the same on https://frappe.io/support

**Comment by kavithabrevera** [comment]
Dear Frappe/Erpnext

Above complaint is not cleared

Thanks and Regards,

Kavitha

-----------------------------
Mob No:7259281002
www.brevera.in
