### ISSUE TITLE
In-browser barcode scanning via camera does not work

### ISSUE THREAD

**Issue by FearsomePhobia** [frappe/erpnext#34862]
### Information about bug

The in-browser barcode scanning via camera does not work; leads to an error.

**Steps to Reproduce:**
- Open a DocType that supports barcode scanning.
- Press the Scan button:
![image](https://user-images.githubusercontent.com/55375132/232055330-398b211c-ec2d-4606-ab94-36dc3c3912c5.png)
- The following popup appears, then automatically dismisses:
![image](https://user-images.githubusercontent.com/55375132/232055671-c4d7cebe-a2ae-4bae-a35d-8230de4d50eb.png)
- An error will appear in the console:
`Camera streaming not supported by the browser.`

**Note:** Tested with the latest version of both Firefox and Chromium, error occurs with both.

_Also, the popup title being named "Scan QRCode" seems a little strange considering the button for it is located next to the "Scan Barcode" field._ 

### Module

other

### Version

Frappe Version: v14.31.0
ERPNext Version: v14.20.3

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Camera streaming not supported by the browser.
```

**Comment by ankush** [comment]
This might be problem with your hardware. Works fine for me on mac, linux and Android phone. 


Make sure you have HTTPS connection.

**Comment by d-franklin** [comment]
A note for anyone who might have this issue in the future, it will also be caused if you have denied access to the camera in the browser (either for the website address or for every site).

Unblocking the site or enabling camera in the browser will fix this issue.

**Comment by richardadinugraha** [comment]
same issues happened, any updates on this?

**Comment by d-franklin** [comment]
> same issues happened, any updates on this?

The issue you're having is more than likely a permission issue with your browser and not an issue with ERPNext.

If you've reset the camera permissions, tried multiple browsers and it's still happening, then I would suggest submitting a bug report with more details about your specific problem.

I'm not a developer for ERPNExt btw, just offering some help.
