### ISSUE TITLE
Change address button not working on cart page.

### ISSUE THREAD

**Issue by PITPL-Akshay-Prajapati** [frappe/erpnext#34878]
### Information about bug

When user wants to change address on cart page, instead of list of other addresses dialog box will open with jinja template in billing and shipping address.

![image](https://user-images.githubusercontent.com/95674015/232298076-b640e541-2dbf-440f-a81b-fbd9b2014bcf.png)
and also routing on incorrect page when user click on edit button given below address
![image](https://user-images.githubusercontent.com/95674015/232299472-cc080186-b36e-4b3a-91c5-7d2962b08845.png)

Both operation working fine on version 13 but given issues in version 14

### Module

ecommerce

### Version

Frappe version 14
Erpnext Version 14.21.0

### Installation method

manual install

**Comment by vcavel** [comment]
Same issue here +1

**Comment by Nihantra-Patel** [comment]
Kindly upgrade to version 14 or 15, then refresh and check again because lots of bugs fixed in the new version.

Everything is working fine. No problems were encountered in the latest versions 14 and 15.


https://github.com/frappe/erpnext/assets/141945075/3826b802-9f52-4da5-8856-e0bb50a52850
