### ISSUE TITLE
Autosuggest Item Variant's Attribute Value

### ISSUE THREAD

**Issue by anandpdoshi** [frappe/erpnext#3488]
As of now, Item Attribute has autosuggest, but Item Attribute Value doesn't have an autosuggest. Once Item Attribute is selected, it should suggest Item Attribute Value.

**Comment by jof2jc** [comment]
@anandpdoshi  I've just updated to latest 5.1.2 but no autocomplete/autosuggest while inputing item attribute value on Manage Variants form...
