### ISSUE TITLE
Cannot Start Work order due to Message "All items have already been transferred for this work order "

### ISSUE THREAD

**Issue by farukahmmed** [frappe/erpnext#34880]
### Information about bug

Getting Message "All items have already been transferred for this work order ". 
But nothing has been transferred actually .
Please Screen shoot.

![SharedScreenshot-1](https://user-images.githubusercontent.com/64157742/232375915-8b
![SharedScreenshot-2](https://user-images.githubusercontent.com/64157742/232375931-0b0337d8-0e60-43a2-ab7c-b5df06546748.jpg)
2a1a84-906b-4165-8929-5b0305a05696.jpg)

### Module

manufacturing

### Version

erpnext version 14.21.0
frappe version 14.32.1
hrms version 14.2.1

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
no error log for this message
```

**Comment by farukahmmed** [comment]
![SharedScreenshot-1](https://user-images.githubusercontent.com/64157742/232376596-a73a9094-a2cd-4994-b025-3cc5fbf20ef3.jpg)

**Comment by rohitwaghchaure** [comment]
@farukahmmed It seems you have not enabled the checkbox "Include Item In Manufacturing" in the respective raw materials. Could you check and confirm?

**Comment by farukahmmed** [comment]
yes, "Include Item In Manufacturing", was not enabled.
I have enabled it but still getting the same error message.
It is not the appropriate message, the software should show a relevant error message.

**Comment by rohitwaghchaure** [comment]
@farukahmmed Yes the message is not proper and even the checkbox not make sense. We have planned to remove the checkbox "Include Item In Manufacturing" in the upcoming releases.

You also needs to enabled "Include Item In Manufacturing" in the BOM and Work Order to fix this issue

**Comment by lmmena2** [comment]
Hi, did you find out the problem? how can I correct it?
