### ISSUE TITLE
Subcontracting Purchase Order - Error Saying Non-Stock Item

### ISSUE THREAD

**Issue by jukkis69** [frappe/erpnext#34894]
### Information about bug

This worked on V13 without issues.

Trying to place PO for a stock item that is provided by the sub-contractor. When I select 'is Subcontracted', ERPNext gives error message that the item must be a Non-Stock Item. However the item being produced by a subcontractor is a stock item, and to produce the item we supply to the subcontractor the components to produce the item --> Therefore need the 'is Subcontracted' enabled to allow to create Material Transfer / Comsumption of the parts once the subcontracted item has been produced. How to do this?

![image](https://user-images.githubusercontent.com/105164376/232483693-2a027f44-2690-429e-bcdc-6128609a43d0.png)

This problem has been raised previously in early versions of 14, but seems there is no resolution, or guidance how to resolve the issue. The documentation for v14 seems not to mention this as well.
https://docs.erpnext.com/docs/v13/user/manual/en/manufacturing/subcontracting

### Module

buying

### Version

Frappe Version - v14.32.1
ERPNext Version - v14.21.0

### Installation method

manual install

**Comment by sugurujay** [comment]
@jukkis69  Yes i have also tested this use case, because when you are transferring the sub contracting items , you are transferring from your warehouse to supplier warehouse, in subcontracting, po py files etc development team need to make maintain_stock as 1

**Comment by jukkis69** [comment]
Thank you for verifying the bug @sugurujay .. hope the development team fixes this soon.

**Comment by s-aga-r** [comment]
@jukkis69 There is a change in Subcontracting Flow in v14. In Subcontracted PO you will select the Service Item (Non-Stock Item) and the respective Finished Good Item (Subcontractor provided Stock Item).

You can refer to the [docs](https://docs.erpnext.com/docs/v14/user/manual/en/manufacturing/subcontracting) for more information.

**Comment by SvbZ3r0** [comment]
@s-aga-r 
The v14 docs have contradicting information on the Subcontracting flow.
[Subcontracting](https://docs.erpnext.com/docs/v14/user/manual/en/manufacturing/subcontracting) vs. [Subcontracting in ERPNext](https://docs.erpnext.com/docs/v14/user/manual/en/manufacturing/articles/subcontracting-in-erpnext)
