### ISSUE TITLE
When using cash sales invoices, of type POS, amount paid shows on credit note column on the accounts receivable reports

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#34902]
### Information about bug

![image](https://user-images.githubusercontent.com/1822868/232698373-a7cb1cea-9498-4222-9702-89d043036289.png)

### Module

accounts

### Version

ERPNext: v14.21.0 (HEAD)
Frappe Framework: v14.32.1 (HEAD)

### Installation method

FrappeCloud

**Comment by Nihantra-Patel** [comment]
Hi @muchai,

Kindly upgrade to version 14 or 15, then refresh and check again.
Everything is working fine. No problems were encountered in versions 14 and 15.


Please check it.

https://github.com/frappe/erpnext/assets/141945075/20e08413-c354-4b3b-b64a-591596ad215b

If the issue again appears then reopen the issue and provide with error.

Thank You!
