### ISSUE TITLE
Create Payment asks Cheque/Reference Date  in ERPNext: v13.49.12 (HEAD)

### ISSUE THREAD

**Issue by zzecool** [frappe/erpnext#34904]
### Information about bug

After the update to ERPNext: v13.49.12 (HEAD), whenever you try to create a payment for an invoice we are getting :

![pronlem](https://user-images.githubusercontent.com/2816897/232724009-c300cb52-c549-4b8e-84ec-9d1236704283.png)

Any hints will be helpfull.

Thanks in advance.

### Module

selling

### Version

Frappe Framework: v13.53.2 (HEAD)
ERPNext: v13.49.12 (HEAD)

### Installation method

FrappeCloud

**Comment by deepeshgarg007** [comment]
Should be fixed via https://github.com/frappe/erpnext/pull/34915
