### ISSUE TITLE
Issues are getting cropped in the Batch Selection and also for the Serial No Selections.

### ISSUE THREAD

**Issue by JitendraSAW** [frappe/erpnext#34900]
### Information about bug

Issues are getting cropped in the Batch Selection and also for the Serial No Selections.. We need to click 3-4 times click  to select the Batch No through pressing the Buttong "Pick Batch No" and similary it happens for the Serial No too where many times we have to press "Add Serial No" button, but it opens the  batch and serial no window on the background. and then it opens the Serial No/Batch No. It does open only after doing the clicking 4-5 times

<img width="935" alt="image" src="https://user-images.githubusercontent.com/80260184/232682046-8086ee5e-5a5a-42cd-8d09-3c065594bdc6.png">
<img width="815" alt="image" src="https://user-images.githubusercontent.com/80260184/232682164-cdbb094d-e5f7-4c2d-a590-613b707d87ef.png">

This is happening in latest Version of 13- 13.49.12 & also in the Versions 14.21.0

### Module

stock

### Version

<img width="433" alt="image" src="https://user-images.githubusercontent.com/80260184/232682440-3f19b362-efaf-47d5-9ba0-11215b58a1a6.png">

<img width="551" alt="image" src="https://user-images.githubusercontent.com/80260184/232682685-f3925f2c-ec50-4535-97ca-e0af7562fb6f.png">

### Installation method

FrappeCloud

**Comment by Solufyin** [comment]
Hi @JitendraSAW,

Upcoming updates will resolve your problem.

Please check it.
https://github.com/frappe/frappe/pull/20706

Bug issue:
https://github.com/frappe/erpnext/issues/34828

Thank You!

**Comment by s-aga-r** [comment]
fixed in https://github.com/frappe/frappe/pull/20706
