### ISSUE TITLE
I'm experiencing an issue where, upon attempting to attach an image to the current form, it opens in the background.

### ISSUE THREAD

**Issue by Gurukrupa-Export** [frappe/erpnext#34919]
### Information about bug

![Screenshot 2023-04-19 122039](https://user-images.githubusercontent.com/129185339/232991277-5eb59c6a-5f74-474e-a181-47856f325344.png)

### Module

other

### Version

ERP Next Version - 14 

### Installation method

None

**Comment by precihole** [comment]
Hello,

This issue is solved in Frappe Framework: v14.33.0 (HEAD).
