### ISSUE TITLE
Asset Depreciation Schedule is Wrong!

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#34920]
### Information about bug

Hi ,

There seems to be a serious problem with the Asset Depreciation Schedule in the recent versions of ERPNext (V13 and V14). It becomes very obvious in existing assets that are long lasting... the schedule extends beyond the Gross Purchase Amount and an extra line is added with a negative value (apparently in some form of attempt to bring the value back to the Gross Purchase Amount) !

![Asset Depreciation Issue 01](https://user-images.githubusercontent.com/9269337/233007740-f18edec8-4efb-4494-aa22-cae0085af058.png)
![Asset Depreciation Issue 02](https://user-images.githubusercontent.com/9269337/233007811-05597ae3-2b21-45f6-a9f2-da8753d6fe99.png)

This needs urgent fixing

Kind regards,

### Module

assets

### Version

ERPNext: v13.49.13 (version-13)
Frappe Framework: v13.54.0 (version-13)

Same in V14

### Installation method

None

**Comment by Olawale1** [comment]
This issue is affecting both Straight Line and Manual Depreciation methods which I believe are the most widely used… It needs to be fixed urgently

Thanks

**Comment by anandbaburajan** [comment]
@Olawale1, 6 number of depreciations booked means that the asset has been depreciating for 6 months (since the frequency of depreciation is set to 1). But the asset was available for use in March and the current month is May, so it hasn't been 6 months. Can you please explain? I guess our docs for existing assets need some more improvement?

**Comment by Olawale1** [comment]
Hi @AnandBaburajan 

Even with that adjustment, schedule is still wrong! Pls see screenshot below:

![Screenshot_20230507-180954](https://user-images.githubusercontent.com/9269337/236696966-cfe3e1fe-1807-4eab-ae59-b3aca2a2cc92.jpg)

The schedule should have 336 Depreciations, instead it has 306 !

**Comment by Olawale1** [comment]
Previously, the simple logic for existing assets was that the system subtracts the Number of Depreciations already booked for Total Number of Depreciations to know how many Depreciations should be included in the schedule

Also, Sum of Gross Accumulated Depreciation and Expected Value after Useful Life was subtracted from Gross Purchase Amount to know what value should be evenly spread across the schedule with the last row absorbing whatever slight difference there may be due to rounding

I really don't  think the issue of whether or not the Number of Depreciations booked from the Available for use

**Comment by Olawale1** [comment]
Previously, the simple logic for existing assets was that the system subtracts the Number of Depreciations Booked from Total Number of Depreciations to know how many Depreciations should be included in the schedule

Also, Sum of Gross Accumulated Depreciation and Expected Value after Useful Life was subtracted from Gross Purchase Amount to know what value should be evenly spread across the schedule with the last row absorbing whatever slight difference there may be due to rounding. This is a simple and effective system 

I really don't think the issue of the Number of Depreciations booked tallying with the Available for Use Date should determine accuracy of the schedule. In any case, you can see from the screenshot that even when it tallies, the generated schedule is still wrong 

Pls try checking on your end as well

Thanks

**Comment by Olawale1** [comment]
Sorry, I just noticed I closed this accidentally

**Comment by Olawale1** [comment]
Hi @AnandBaburajan 

have you been able to replicate the issue ?

**Comment by anandbaburajan** [comment]
@Olawale1 I've been trying for a while, but no. I don't understand how you're getting the 99,999,990 value at the end. With the values in the latest screenshot you shared, I'm getting 336 rows with the last one negative, but not 99,999,990. Have you set an 'expected value after useful life' by any chance? Can you share the whole asset as in JSON (you can use the 'copy to clipboard' option from the menu). I'm still not sure if there's actually an issue. If you can share an actual real-life scenario with system-produced incorrect values and your correct expected values, maybe that will help.

**Comment by anandbaburajan** [comment]
@Olawale1 this is a small example which is working as expected:

![image](https://user-images.githubusercontent.com/2698932/236821133-22536944-9da5-466a-9906-19a7bb9b2164.png)
![image](https://user-images.githubusercontent.com/2698932/236821234-495019c0-0381-4a9a-a8e7-6f772a3a541d.png)

**Comment by Olawale1** [comment]
@AnandBaburajan , I'm getting same expected results for Assets with short lifespan. Please see below:

![Asset Depreciation Issue 03](https://user-images.githubusercontent.com/9269337/236828678-e04e4f26-3d08-44f0-9b49-453c734874b9.png)

As I mentioned in my original post, the issue becomes more obvious when you have Assets with longer lifespan. Pls try replicating with figures similar to what I have in my post (for example, 340 depreciations)

Also toggle between adding Expected Value after Useful Life and leaving the field blank. Following are my observations:

- When the field is blank, the system automatically adds some negative value there and then you have an extra row added to depreciation schedule with negative amount

- When the field is set, the depreciation schedule is shorter than expected !

**Comment by Olawale1** [comment]
> @Olawale1 I've been trying for a while, but no. I don't understand how you're getting the 99,999,990 value at the end. With the values in the latest screenshot you shared, I'm getting 336 rows with the last one negative, but not 99,999,990. Have you set an 'expected value after useful life' by any chance? Can you share the whole asset as in JSON (you can use the 'copy to clipboard' option from the menu). I'm still not sure if there's actually an issue. If you can share an actual real-life scenario with system-produced incorrect values and your correct expected values, maybe that will help.

@AnandBaburajan , yes I have set Expected Value after Useful Life to 10 

The example I have shared with you is a real life scenario ! Right now, we have totally suspended use of the Asset Module because of this issue

From your response, you have encountered the 1st issue of an additional negative row when Expected Value after Useful Life is not set. This is very much an issue because it simply means the monthly depreciation values are wrong. Then imagine what happens at the last month when the system posts a significant negative value ! 

To see the 2nd issue, simply set a value for Expected Value after Useful Life... The system then generates a schedule with only 306 rows !

**Comment by anandbaburajan** [comment]
@Olawale1 thanks for the detailed explanations.

> the issue becomes more obvious when you have Assets with longer lifespan

Ah, I see.

> you have encountered the 1st issue of an additional negative row when Expected Value after Useful Life is not set

I thought the negative row was due to incorrect dummy values, but now I get it that it was indeed a real-life scenario.

I'll take up this issue on priority. Thanks for reporting!

**Comment by anandbaburajan** [comment]
Fixing this via https://github.com/frappe/erpnext/pull/35255.

**Comment by anandbaburajan** [comment]
@Olawale1 I just realised that the issue you reported is due to an incorrect Opening Depreciation Amount. You've set it as 10000000 but if you actually follow the schedule, it's supposed to be 1176470.59. If you set that as the Opening Depreciation Amount, the schedule should generate properly as shown in the screenshots below.

![image](https://github.com/frappe/erpnext/assets/2698932/8548f674-c786-47d6-98dc-d843fc327a9c)
...
![image](https://github.com/frappe/erpnext/assets/2698932/67d24f09-1551-458a-880e-b2855eff7e49)

Now the thing I'm not sure about is: is there a use case where users would need to set an incorrect Opening Depreciation Amount? Otherwise, I'll just add a validation to let users know if the Opening Depreciation Amount is incorrect. Please share your thoughts, thanks.

**Comment by Olawale1** [comment]
> I'll just add a validation to let users know if the Opening Depreciation Amount is incorrect

Hi @AnandBaburajan 

No ! This is not the right approach. When dealing with existing assets, it's much better to stay away from the asset history. You don't know if it's been damaged, revalued, been under repair, upgraded etc so there's no such thing as an 'incorrect Opening Accumulated Depreciation'

Also, there are many people moving their assets from unstructured systems into the ERP. Writing such a validation means you are forcing them to try and calculate what the correct Opening Accumulated Depreciation value from the perspective of ERPNext should be for each asset. This is a time-consuming, frustrating, and pointless exercise if they have lots of assets

All we need to know are the following:

1. The original Purchase Amount
2. The number of Depreciations already booked (which is just another way of asking how many Depreciations the system should book for the asset)
3. The Opening Accumulated Depreciation (which is just another way of asking what value should be depreciated via the ERP)
4. The Expected Value after Useful Life (which is used in conjunction with no. 3 above)

Trying to force an exact figure for Opening Accumulated Depreciation is not the way to go... especially when we don't know the asset history

Do let me know if any further clarification is required

Many thanks

**Comment by anandbaburajan** [comment]
Thanks @Olawale1 for the explanation! We've fixed the issue.

**Comment by Olawale1** [comment]
Wow! Thanks @AnandBaburajan 

This is great news! Hope the fix is deployed for both V13 and V14

Kind regards,

**Comment by anandbaburajan** [comment]
@Olawale1 it will be released on Tuesday.

**Comment by Olawale1** [comment]
Thanks @AnandBaburajan , just want to be sure it will be backported for V13 as well

**Comment by victorlatest** [comment]
Thanks for bringing this up @Olawale1
