### ISSUE TITLE
Stock Ledger Batch Wise Showing Incorrect Balance

### ISSUE THREAD

**Issue by dineshpanchal93** [frappe/erpnext#34924]
### Information about bug

https://discuss.frappe.io/t/stock-ledger-showing-ledger-for-the-batch-wise/103821

### Module

stock

### Version

Frappe Chat: v0.0.1 (main)

ERPNext: v14.21.0 (version-14)

Frappe Framework: v14.33.0 (version-14)

Gatepass: v0.0.1 (main)

Frappe HR: v14.2.2 (version-14)

India Compliance: v14.5.3 (version-14)

### Installation method

manual install

**Comment by rohitwaghchaure** [comment]
@dineshpanchal93 have you created backdated stock reconciliation?

**Comment by dineshpanchal93** [comment]
Yes

And I did the reposting it has been resolved.
