### ISSUE TITLE
Using shopify SKU as Item Id and Item Code [Proposal]

### ISSUE THREAD

**Issue by SherefAbolmagd** [frappe/erpnext#34921]
When syncing the shopify items users need to have the shopify SKU as ID for the item in the erpnext for searching for item when adding an item price and better management of items when the list getting better for my case we have 18k+ items and we have SKU for each one for that reason I have modified the code for the ecommerce_integrations module in the product itegration to use the shopify SKU as the item code and if SKU not exist then use the shopify code as a fallback here a screenshot of the current modification.

![image](https://user-images.githubusercontent.com/40181573/233020553-9f30d9f6-9021-43ce-b14e-2b9b1cae52cd.png)

If it's possible to get access and create a PR for this issue it would be great!

**Comment by ankush** [comment]
duplicate https://github.com/frappe/ecommerce_integrations/issues/238
