### ISSUE TITLE
Job card Creation from Workorder goes wrong

### ISSUE THREAD

**Issue by nitin-anantpranali** [frappe/erpnext#34936]
### Information about bug

While creating Jobcard from Work order screen, it shows following dialog. If we select only one Jobcard then also System creates all Job Cards

<img width="863" alt="image" src="https://user-images.githubusercontent.com/116695322/233235262-6c3432a9-4103-4210-bf16-b94a0c2f7a0c.png">

### Module

manufacturing

### Version

Frappe Chat: v0.0.1 (HEAD)
ERPNext: v14.22.0 (HEAD)
Frappe Framework: v14.33.0 (HEAD)
Frappe HR: v14.2.2 (HEAD)
India Compliance: v14.5.3 (HEAD)
Payments: v0.0.1 (HEAD)

### Installation method

FrappeCloud

**Comment by nitin-anantpranali** [comment]
It creates the Job cards like this...

<img width="863" alt="image" src="https://user-images.githubusercontent.com/116695322/233235615-0a0099d2-9ee9-40e7-b6c9-453e943fe370.png">

<img width="863" alt="image" src="https://user-images.githubusercontent.com/116695322/233235682-b5c322ec-705f-4afe-8892-88e8751afd31.png">

**Comment by nitin-anantpranali** [comment]
One more supporting Issue. If I click multiple times on the Create Job Card button on same Work order, it duplicates the Job Cards every time.

<img width="1045" alt="image" src="https://user-images.githubusercontent.com/116695322/233235864-809b94fb-47e0-4a4b-a7a6-2603888e5418.png">

**Comment by rohitwaghchaure** [comment]
@nitin-anantpranali Delete rows against which you don't want to make job cards

**Comment by nitin-anantpranali** [comment]
And what about the Same Job Cards getting created multiple times?

**Comment by rohitwaghchaure** [comment]
@nitin-anantpranali I have tested locally and it's creating one record only and not multiple

![issue_of_job_card](https://user-images.githubusercontent.com/8780500/233323184-67403336-fac2-44db-b4bf-abc3b31fe91f.gif)

**Comment by nitin-anantpranali** [comment]
Can be stop user from creating repetitive and same Job Cards by adding over check whether a job card is already exists for the given work order and item?
