### ISSUE TITLE
Unable to Save Purchase Order created from Material Request

### ISSUE THREAD

**Issue by maveezmh** [frappe/erpnext#34932]
### Information about bug

Unable to Save purchase order from material request 

>1
Create Material Request for purchase:

![image](https://user-images.githubusercontent.com/112148467/233145209-fabec637-721d-47fa-bf08-7be86fbe5169.png)

>2 Create Purchase order from material request
>3 select supplier
>4 Remove items that are not required
>5 Add required by date 
>Click Save

The system wont save the document.

![image](https://user-images.githubusercontent.com/112148467/233146188-8ea50abd-83ec-4eab-8953-284ed929db50.png)

### Module

buying

### Version

ERPNext: v14.21.0 (HEAD)

Frappe Framework: v14.32.1 (HEAD)

Frappe HR: v14.2.1 (HEAD)

Payments: v0.0.1 (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
TypeError: locals[m.doctype][m.name] is undefined
    o save.js:67
    o save.js:74
    o save.js:58
    n save.js:19
    save save.js:269
    validate_and_save form.js:807
    promise callback*frappe.run_serially/< desk.bundle.JV5IB42T.js:297
    run_serially desk.bundle.JV5IB42T.js:297
    validate_and_save form.js:798
    save form.js:737
    save form.js:734
    Save toolbar.js:652
    set_action desk.bundle.JV5IB42T.js:588
    jQuery 2
form.js:785:12
```

**Comment by Solufyin** [comment]
Hi @maveezmh,

Because the issue is on Purchase Order, not in MR to PO creation.
Check it: #34843

Thank You!
