### ISSUE TITLE
Field Not found Error while creating a new BOM

### ISSUE THREAD

**Issue by nitin-anantpranali** [frappe/erpnext#34941]
### Information about bug

While creating a new BOM, gearing this error on % Process Loss field

![image](https://user-images.githubusercontent.com/116695322/233265573-6bc02301-d67c-4280-aa4c-7c6fe1a077ce.png)

### Module

manufacturing

### Version

Frappe Chat: v0.0.1 (HEAD)
ERPNext: v14.22.0 (HEAD)
Frappe Framework: v14.33.0 (HEAD)
Frappe HR: v14.2.2 (HEAD)
India Compliance: v14.5.3 (HEAD)
Payments: v0.0.1 (HEAD)

### Installation method

None

**Comment by Solufyin** [comment]
Hi @nitin-anantpranali,

Your issue has been resolved.
Please close the Issue.

Thank You!

**Comment by nitin-anantpranali** [comment]
Found in Item > Accounts > Table
