### ISSUE TITLE
Bug - Choosing customer with blank contact doesn't reset contact information

### ISSUE THREAD

**Issue by monojoker** [frappe/erpnext#3494]
Guys, if you select a customer onto a sales document (order, invoice, etc) that has contact details they populate - correctly. If you then choose a different customer (say you picked the wrong one by mistake) that doesn't have any contact details set, they "old" details do not get over-written and are thus retained incorrectly against the sales document. If you select a customer onto an existing sales document that doesn't have contact information the transactional document (order, invoice, etc) should have the contact information reset to BLANK. Thanks.

**Comment by rmehta** [comment]
@monojoker should not be so annoying. In most cases, you always select another customer.

**Comment by monojoker** [comment]
While this is true I often believe you should protect the users from themselves. You are correct though a customer should ALWAYS have at least one address and contact record set. We just discovered this as a result of poor "housekeeping" as you note. Thanks.
