### ISSUE TITLE
Feature Request: Notification when user is mentioned in comment

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#3495]
ERPNext offers the awesome feature of basically commenting on everything. However it would be great if I could mention somebody in the comment like "@Mark please check out this sales order, it's stalling, we have to react before the customer writes us". Then this should be listed in the users notifications or some sort of inbox/messages so the user can check out whats happening needing his attention. This is how Asana does it and after an "@" mention happened the user is automatically a follower of that process and will be informed in the inbox of any further comments.

**Comment by justinlusg** [comment]
This is one of the feature we really need as well!

**Comment by rmehta** [comment]
Any sponsorship https://erpnext.com/pricing/paid-feature-development ?

**Comment by justinlusg** [comment]
@rmehta how much would it cost for such an enhancement and how long would it take? I'm keen to sponsor some to get this feature running! It would aid us greatly when we try to promote erpnext to our clients as well.

**Comment by rmehta** [comment]
- [ ] Explore autocomplete options in text box
- [ ] Server side query
- [ ] In Communication / Comment validation strip all "@" comments and try and match with user / employee first names
- [ ] Add to recipients if missing.
- [ ] Testing

4 billable hours ?

@justinlusg Thanks for considering. We will also publicly attribute you in the popup as well as maintain a special page in the repo for sponsred features. I guess open source works if there are contributions either as code or money and more money will mean we can hire more devs to get things done faster.

**Comment by justinlusg** [comment]
@dottenbr would you want to share the sponsorship? I do not mind paying half of the fees.

**Comment by rmehta** [comment]
@justinlusg do you still want to sponsor this? Maybe we can reduce it to 3 hours

**Comment by justinlusg** [comment]
@rmehta ok, we can sponsor for 3 hours! it is paid via paypal?

**Comment by rmehta** [comment]
Thanks @justinlusg will send you a PayPal invoice :+1: 

Sorry for being pushy, but we need to be revenue focused for sometime now, till the hosting revenue catches back up.

**Comment by rmehta** [comment]
@justinlusg can you send us your paypal id at **hello at erpnext dot com**

**Comment by mark** [comment]
Incidentally, this is also how github does it.

**Comment by justinlusg** [comment]
@rmehta no worries! This is a great feature I'm sure everyone will enjoy using it. Have sent you the email.

**Comment by rmehta** [comment]
@justinlusg since we don't have user ids in erpnext, there are 3 options:

1. @First+name 
2. @First+name+Last+name like Facebook? 
3. Just the userid part of the user's email id? 

I am thinking the 3rd. What do you think?

**Comment by anandpdoshi** [comment]
Let's create a new field username and set it as the first part of email address. People can later change it as needed. If there's a duplicate, we add a number to it.

**Comment by justinlusg** [comment]
@rmehta I would prefer the 2nd one, first name + last name because like for us the email address might be a short form (e.g. Justin Lu might be jlu@xxx.com).. doing it like Facebook would be easy for users to pick up how to use it

**Comment by justinlusg** [comment]
@rmehta I've received the invoice, I will ask my finance to make payment within this few days.

**Comment by rmehta** [comment]
@justinlusg thanks! We will take this up within a couple of days of your payment.

**Comment by dottenbr** [comment]
Thank you @justinlusg for sponsoring this feature development. We are very excited about this and cant wait to see it live. This will give the collaborative work a boost.

**Comment by justinlusg** [comment]
@rmehta Sorry for the delay as well! I just got my finance to approve the payment last Friday.. they should be making payment for the PayPal invoice within this week.

**Comment by dottenbr** [comment]
@rmehta any news on this feature? I was hoping to see it when migrating to the brand new ERPNext 6

**Comment by rmehta** [comment]
I was hoping too @justinlusg did you get the approval for the sponsorship. Thanks!

**Comment by Devens** [comment]
Hello... Any news on this? We would also look forward for this feature.

**Comment by dottenbr** [comment]
It seems like there is nothing moving regarding the sponsorship on @justinlusg end?

**Comment by justinlusg** [comment]
Unfortunately, I only managed to get a $200 budget for this feature. :( I'm very keen to get this in, it's on my watchlist. Give me a couple more weeks, i'm determined to push this through.

**Comment by Devens** [comment]
We can manage for budget of $50 provided this feature includes sending email to all followers (shared list).

**Comment by justinlusg** [comment]
If i can sponsor $150, @Devens sponsor $50, can @dottenbr sponsor the remaining $100? this would be such a cool feature.

**Comment by dottenbr** [comment]
If @rmehta can enable the things happening with an @-mention to appear in a sort of activity stream so we see the doctype that its relating to, the comment, who wrote it and when and we can click to get in the doctype to write a reply I am all for it and I am willing to cover 100$ if we do this together.

<img width="860" alt="bildschirmfoto 2015-11-30 um 16 02 36" src="https://cloud.githubusercontent.com/assets/9136094/11475092/d235deba-977b-11e5-8e4b-fff32897f11d.png">

**Comment by dottenbr** [comment]
I just saw the Activity Log and I think that would be a wonderful way to do it to filter the things where you have been mentioned.

**Comment by justinlusg** [comment]
@rmehta

**Comment by rmehta** [comment]
On @anandpdoshi 's list. ETA 1-2 weeks

**Comment by justinlusg** [comment]
great!!

**Comment by justinlusg** [comment]
@anandpdoshi i wonder is there any update on this? We are all so excited about this feature :D

**Comment by anandpdoshi** [comment]
Will work on this feature this week. Thanks for the push!

Best,
Anand Doshi

ERPNext

**Comment by justinlusg** [comment]
@anandpdoshi just wondering if this would be ready before xmas? haha

**Comment by anandpdoshi** [comment]
Yeah it should be :)

Best,
Anand Doshi

ERPNext

**Comment by anandpdoshi** [comment]
@justinlusg :santa: has sent you a :gift: https://github.com/frappe/frappe/pull/1473

**Comment by anandpdoshi** [comment]
The patch will set the username value to `firstname` or `firstname_lastname` or blank depending on conflicts. Username is non-mandatory.

**Comment by rmehta** [comment]
36 comments and finally done. Great job @anandpdoshi

**Comment by nabinhait** [comment]
:+1:

**Comment by justinlusg** [comment]
@anandpdoshi Happy Xmas to you too!

**Comment by Devens** [comment]
@anandpdoshi - This functionality already updated? How does it work?

**Comment by anandpdoshi** [comment]
@Devens will be release to cloud customers this week

Here's a demo:

![@mention](https://cloud.githubusercontent.com/assets/836785/11978485/f0af9d0c-a9b1-11e5-8f3c-ae3c538c4a62.gif)
