### ISSUE TITLE
 Save button remains disable in "Material Transfer for Manufacture"

### ISSUE THREAD

**Issue by kengjungwa** [frappe/erpnext#3496]
Save button remains disable after acknowledging the error message in  "Material Transfer for Manufacture"

To reproduce:
- Open an submitted and not-yet-completed Production Order
- Click on "Transfer Materials for Manufacture" then enter any amount
- Remove items in the table if any
- Click "Save" and notice that there is an error message
- Click "Close" on the error message "Item table can not be blank"
- Notice that the "Save" button remains disable; hence users cannot continue as shown below

![image](https://cloud.githubusercontent.com/assets/1743535/8270181/3f6372b8-17fc-11e5-8b12-a0a1ebcaec6a.png)

**Comment by inventobd** [comment]
This happened with me previously when I didn't set default warehouse for my purchase items . Check your stock to see if it has all the items available in your raw materials warehouse . Also check your boom to see the raw materials quantity and manufacturing quantity are correct

**Comment by kengjungwa** [comment]
Thanks inventodb for sharing. The case also happens when no BOM is set for the particular item, leading to no item in the table by default. Basically, this issue could occur in many situations, but I guess the cause of issues might be the same, which is enabling the button after throwing error.

**Comment by rmehta** [comment]
Thanks fixed.
