### ISSUE TITLE
After update No creation of new documents possible and the old ones are no longer displayed

### ISSUE THREAD

**Issue by Koljan76** [frappe/erpnext#34966]
### Information about bug

After update No creation of new documents possible and the old ones are no longer displayed.
![image](https://user-images.githubusercontent.com/131370769/233380799-42597fb6-fe2e-4542-a6d0-b77fb0dde713.png)

### Module

buying, selling

### Version

Installed Apps
Ecommerce Integrations: v1.15.3 (main)

ERPNext: v14.22.2 (version-14)

Frappe Framework: v14.32.1 (version-14)

Frappe HR: v14.0.3 (version-14)

Payments: v0.0.1 (develop)

### Installation method

None

**Comment by rohitwaghchaure** [comment]
@Koljan76 any error on browser's console log?

**Comment by Koljan76** [comment]
> @Koljan76 any error on browser's console log?

tested in different browsers, the same behaviour..

browser's console log:

vTools failed to load source map: Could not load content for webpack://Quill/node_modules/quill-delta/dist/Delta.js.map: Fetch through target failed: Unsupported URL scheme; Fallback: HTTP-Fehler: Statuscode 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for webpack://Quill/node_modules/quill-delta/dist/AttributeMap.js.map: Fetch through target failed: Unsupported URL scheme; Fallback: HTTP-Fehler: Statuscode 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for webpack://Quill/node_modules/quill-delta/dist/Op.js.map: Fetch through target failed: Unsupported URL scheme; Fallback: HTTP-Fehler: Statuscode 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for webpack://Quill/node_modules/quill-delta/dist/Iterator.js.map: Fetch through target failed: Unsupported URL scheme; Fallback: HTTP-Fehler: Statuscode 404, net::ERR_UNKNOWN_URL_SCHEME


eadcrumbs.js:129 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'Selling')
    at Object.set_workspace (breadcrumbs.js:129:47)
    at Object.set_workspace_breadcrumb (breadcrumbs.js:90:9)
    at Object.update (breadcrumbs.js:62:9)
    at Object.add (breadcrumbs.js:45:8)
    at frappe.views.ListView.set_breadcrumbs (base_list.js:260:22)
    at frappe.views.ListView.setup_page_head (base_list.js:179:8)
    at frappe.views.ListView.setup_page_head (list_view.js:128:9)
    at frappe.views.ListView.setup_page (base_list.js:173:8)
    at frappe.views.ListView.setup_page (list_view.js:124:9)
set_workspace @ breadcrumbs.js:129
set_workspace_breadcrumb @ breadcrumbs.js:90
update @ breadcrumbs.js:62
add @ breadcrumbs.js:45
set_breadcrumbs @ base_list.js:260
setup_page_head @ base_list.js:179
setup_page_head @ list_view.js:128
setup_page @ base_list.js:173
setup_page @ list_view.js:124
Promise.then (async)
(anonym) @ dom.js:269
frappe.run_serially @ dom.js:267
show @ base_list.js:9
show @ list_view.js:36
frappe.views.ListView @ list_view.js:26
make @ list_factory.js:30
show @ factory.js:25
render_page @ router.js:303
render @ router.js:282
route @ router.js:147
await in route (async)
push_state @ router.js:459
Promise.finally.frappe.route_flags @ router.js:356
set_route @ router.js:345
frappe.set_route @ router.js:535
(anonym) @ quick_list_widget.js:256
dispatch @ jquery.js:5430
c1.handle @ jquery.js:5234

**Comment by Koljan76** [comment]
anyone have an idea for a solution?

**Comment by Koljan76** [comment]
[solved] it was necessary to deinstall and delete HRMS Module..
