### ISSUE TITLE
V14 Process Loss should be considered as part of qty to manufacture in Work Order

### ISSUE THREAD

**Issue by goapaints** [frappe/erpnext#34978]
### Information about bug

New Process Loss feature has been added in Version 14 for Process Manufacturing Industry.
In this flow, if this feature is used, work order shows as below, after completing stock entry:
<img width="615" alt="image" src="https://user-images.githubusercontent.com/120462375/233609162-29cee264-4980-4f6c-9ed3-71e7f7e43d3a.png">

Here the quantity to manufacture as per WO was 120, but actual manufactured qty was 118 and 2 was process loss.

Now the Work Order status is still set as "Not Started" and it asks to create Stock entry for process loss qty of 2. This should not be the case as 118 is the yield of the process and 2 is the loss and as such the process is completed.

BUG LOGIC:
WO is complete if:
Qty to manufacture = Manufactured Qty
CORRECT LOGIC:
WO is complete if:
Qty to manufacture = (Manufactured Qty + Process Loss)

### Module

manufacturing

### Version

ERPNext: v14.22.0 

Frappe Framework: v14.33.0 

### Installation method

FrappeCloud

**Comment by goapaints** [comment]
@rohitwaghchaure

**Comment by ghiont** [comment]
I have the same issue

**Comment by rohitwaghchaure** [comment]
@ghiont @goapaints This issue has fixed and by tomorrow we'll release the [fix](https://github.com/frappe/erpnext/pull/35629).
