### ISSUE TITLE
V14 Batch Renaming not allowed for auto created batch

### ISSUE THREAD

**Issue by goapaints** [frappe/erpnext#34979]
### Information about bug

the setting of auto creation of new batch is as follows
<img width="556" alt="image" src="https://user-images.githubusercontent.com/120462375/233611979-ad958964-648f-472c-aa36-812b929cb508.png">
In V13 , renaming of batch was allowed.
However, in V14, while the rename dialog box opens

<img width="524" alt="image" src="https://user-images.githubusercontent.com/120462375/233613721-1c75f657-0e15-4b16-bd6b-46aa5c79fffb.png">
<img width="542" alt="image" src="https://user-images.githubusercontent.com/120462375/233614321-fa9191f9-922f-4b61-9803-32e513f1408b.png">

And saved message appears
<img width="858" alt="Untitled" src="https://user-images.githubusercontent.com/120462375/233614041-2d7f1f1b-b819-4698-8033-b248fd0bd955.png">

Actual batch no remains as per original itself

### Module

stock, manufacturing

### Version

ERPNext: v14.22.0 (HEAD)
Frappe Framework: v14.33.0 (HEAD)

### Installation method

FrappeCloud

**Comment by rohitwaghchaure** [comment]
@goapaints batch rename not works in v13 as well. We can't enable rename feature for the batch because the batch is Data field and not Link field in the stock ledger entry. If we allowed rename feature for the batch then the valuation rate might get calculated wrong for the batch.
