### ISSUE TITLE
How to handle multiple email IDs of Leads or Contacts

### ISSUE THREAD

**Issue by adityaduggal** [frappe/erpnext#3498]
There is a validation in the email field which would not let us enter multiple email IDs, the validation of emails needs to be re-looked at.

Refer: https://discuss.frappe.io/t/how-to-handle-multiple-email-ids-of-a-contact-or-lead/6282

**Comment by tsuga** [comment]
I think this feature is very useful!

**Comment by anupamvs** [comment]
can be done through prospect https://github.com/frappe/erpnext/pull/27102
