### ISSUE TITLE
Class not assigned to Item in itemised_tax_breakup.html

### ISSUE THREAD

**Issue by nitin-anantpranali** [frappe/erpnext#34993]
### Information about bug

In the file "templates/includes/itemised_tax_breakup.html"
Please assign some class to the line shown in the screenshot. We are facing some UI issues while customising the Invoice format for Tax Breakup.

Line No : 17
<td>{{ item }}</td>

![image](https://user-images.githubusercontent.com/116695322/233762604-6d674993-6f3d-426f-ac8d-b87c73e8532b.png)

### Module

selling, manufacturing

### Version

ERPNext: v14.22.2 (HEAD)
Frappe Framework: v14.33.1 (HEAD)
India Compliance: v14.5.4 (HEAD)
Payments: v0.0.1 (HEAD)

### Installation method

None

**Comment by Nihantra-Patel** [comment]
Hi @nitin-anantpranali,

Issue has been resolved.
Reference: #36235

Kindly upgrade to version 14 or 15, then refresh and check again because lots of bugs fixed in the new version.
Everything is working fine. No problems were encountered in the latest versions 14 and 15.

Thank You!
