### ISSUE TITLE
The tasks in projects is not updated when project tasks are closed

### ISSUE THREAD

**Issue by justinlusg** [frappe/erpnext#3500]
![image](https://cloud.githubusercontent.com/assets/12539216/8275507/9c98f5e2-18d9-11e5-8e86-c16feb001cf3.png)

The tasks under projects are not updated when the project tasks itself is closed. See % completed = 25% but all 4 tasks are displayed as Open in the table. However, the task is already closed under project tasks.

**Comment by neilLasrado** [comment]
Do you have some custom script on your system ? I was not able to replicate the issue. also the code appears to be fine. Also try replicating the issue on demo.erpnext.com

**Comment by justinlusg** [comment]
I tried when I create the project and the task, after which I close it myself -> It works perfectly. 

However, the issue comes when I assign one of the task to people. For example, I created 4 tasks and I go into one of the task and assign it to someone. 
![image](https://cloud.githubusercontent.com/assets/12539216/8277231/0ca0fb46-18f3-11e5-842a-a72f96f91756.png)

When the assigned staff closes the project tasks, the task is not updated in projects.

**Comment by neilLasrado** [comment]
I tried assigning, it works. Can you please check if the task was saved with status 'closed'. Try reloading the document. Project document on load fetches the data from task.

It is possible that this may be a permission related issue. Was there any error while saving the task ?

**Comment by justinlusg** [comment]
Please try this,

Steps to replicate:
1) Create Project and add 2 - 3 tasks
2) Click on the tasks and select "View Task"
3) Assign the task to another user
4) Login via that other user account
5) Set project task to Closed
6) Login back to main user
7) View Projects (task table not updated)

![image](https://cloud.githubusercontent.com/assets/12539216/8428741/8efb41a8-1f53-11e5-8058-4c7ce5aae172.png)

**Comment by neilLasrado** [comment]
@justinlusg Hey thanks for the detailed explanation. Was able to replicate.

**Comment by justinlusg** [comment]
:+1:  :+1:
