### ISSUE TITLE
When a quotation is converted to a sales order, the associated lead status is updated to Converted, while the opportunity status still remains as Quotation

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#35001]
### Information about bug

When a quotation is converted to a sales order, the associated lead status is updated to Converted, while the opportunity status still remains as Quotation

### Module

CRM

### Version

ERPNext: v14.22.2 (HEAD)
Frappe Framework: v14.33.1 (HEAD)

### Installation method

FrappeCloud

**Comment by Nihantra-Patel** [comment]
Hi @muchai,

Issue has been resolved. please check the PR: #35145

Now it working fine and also I checked from my end in the latest version 14.

Thank You!
