### ISSUE TITLE
Pick list -- Stock Entry Cancelled  - Pick - list as completed

### ISSUE THREAD

**Issue by dineshpanchal93** [frappe/erpnext#35014]
### Information about bug

<img width="1188" alt="Screenshot 2023-04-24 at 5 22 00 PM" src="https://user-images.githubusercontent.com/21578167/233988285-f23d3b16-8fb8-4e07-af08-7389e9023f21.png">

<img width="1138" alt="Screenshot 2023-04-24 at 5 22 14 PM" src="https://user-images.githubusercontent.com/21578167/233988334-62988152-ad07-4d61-8f01-836e5f7eed0e.png">

Even If Amend the Stock entry is then batch no is getting pick the wrong and, Pick list is showing as completed.

https://user-images.githubusercontent.com/21578167/233990533-61201c51-f194-4538-8466-b359e45357b3.mov

### Module

stock

### Version

ERPNext: v14.22.0 (version-14)

Frappe Framework: v14.33.0 (version-14)

Gatepass: v0.0.1 (main)

Frappe HR: v14.2.2 (version-14)

India Compliance: v14.5.3 (version-14)

### Installation method

manual install

**Comment by dineshpanchal93** [comment]
One more thing that. I canceled the pick list and amend it, which still shows as completed and allows me to create the stock entry for the same, and this time in stock entry correct batch no. was picked

**Comment by s-aga-r** [comment]
@dineshpanchal93 Why do you want the status of the Pick List to be updated on the cancellation of Stock Entry? When a Stock Entry or Delivery Note gets created against a Pick List then the Pick List status gets updated to `Completed` it won't get updated on the cancellation of Stock Entry or Delivery Note. 

For `One more thing that. I canceled the pick list and amend it, which still shows as completed and allows me to create the stock entry for the same, and this time in stock entry correct batch no. was picked` I have raised a fix.
