### ISSUE TITLE
Price Hide to warehouse user

### ISSUE THREAD

**Issue by bobzz-zone** [frappe/erpnext#3501]
Hi,

im really need that price is hidden (at purchase recipt / stock entry / delivery note) from warehouse user , can we create that option?
because i thin we had to modify core code to do it right now

Thanks

**Comment by rmehta** [comment]
You can set permlevel on the field.

**Comment by sliska** [comment]
@rmehta , which fields do we set permlevels on? Every field that is type "currency"? or just some of those fields?
