### ISSUE TITLE
Logo shows correctly on screen but broken in PDF sent via e-mail

### ISSUE THREAD

**Issue by tonancheta** [frappe/erpnext#35025]
### Information about bug

When printing any print format on screen, logo appears correctly but when resulting PDF is generated and sent via e-mail, logo shows up as a broken link.

![image](https://user-images.githubusercontent.com/128594821/234190517-97307b7f-e0c5-48e1-b094-2d26b493a70e.png)

![image](https://user-images.githubusercontent.com/128594821/234190780-54aceac6-f819-4c59-be87-c26f619396e9.png)

![image](https://user-images.githubusercontent.com/128594821/234190846-29e245ad-5d2a-4c03-902b-d340322691b1.png)

### Module

other

### Version

ERPNext: v13.49.10 (HEAD)
Frappe Framework: v13.51.3 (HEAD)

### Installation method

FrappeCloud

**Comment by vitamincy** [comment]
might because of the file is priviate

**Comment by dj12djdjs** [comment]
@tonancheta as @vitamincy mentioned the image is private and not accessible to any Guest visitors.

Make the file public, then change the URL to the public URL and you'll be good to go
