### ISSUE TITLE
I can't customize dashboard

### ISSUE THREAD

**Issue by ahmed-advicts** [frappe/erpnext#35058]
### Information about bug

I edited the Home workspace by adding new shortcut but I can't find the shortcut after saving the changes. I tried refresh, clear server and browser cache, nothing happend.

### Module

other

### Version

14

### Installation method

FrappeCloud

**Comment by dj12djdjs** [comment]
It appears to be working on latest version as per attached gif:

![dashboard-edit](https://user-images.githubusercontent.com/29856401/234997040-0ea8bf3b-6bd9-4e31-ba51-b67f3ae5dd67.gif)
