### ISSUE TITLE
lead add email address can't save timeout 

### ISSUE THREAD

**Issue by aunret** [frappe/erpnext#35065]
### Information about bug

CRM
when i create new lead whitout email address it can save , but when i add the email address it can't save , after long time it says timeout.
but if i use bench start everything works fine. it can can not work well with nginx.

### Module

CRM

### Version

Frappe Framework: v13.56.0 
ERPNext: v13.49.14

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
   914	2023/04/27 10:28:39 [error] 1562480#1562480: *1 upstream prematurely closed connection while reading response header from upstream, client: 101.86.48.237, server: erp.qingbs.com, request: "POST /api/method/frappe.desk.form.save.savedocs HTTP/2.0", upstream: "http://127.0.0.1:8000/api/method/frappe.desk.form.save.savedocs", host: "erp.qingbs.com", referrer: "https://erp.qingbs.com/app/lead/CRM-LEAD-2023-00002"

**Comment by whohasmyname** [comment]
ERPNext: v14.36.0
Frappe Framework: v14.46.0
Linux...
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy

I am also facing this issue. Is there a workaround? It's a pretty bad bug. I can create or edit existing leads if an email address is entered. After a 2 minute timeout, I can do to the list view and see the entry was created (or updated). Click to view details and the details are updated. On creation, the contact is also created.  The UI just makes you think it failed and makes you wait 2 minutes before timing out.

I'm new - where do I find the relevant logs? Just curious. I would have provided if I knew where to look.

![image](https://github.com/frappe/erpnext/assets/80305653/1eb92b4b-7676-4aca-9ea4-085ac2d38b1d)

**Comment by aunret** [comment]
update to v14.53.2 , same issue

**Comment by github383560341** [comment]
我也是同样的问题，有解决方案吗？

**Comment by Nihantra-Patel** [comment]
Kindly upgrade to version 14 or 15, then refresh and check again because lots of bugs fixed in the new version.

Everything is working fine. No problems were encountered in the latest versions 14 and 15.


https://github.com/frappe/erpnext/assets/141945075/c996de6f-5535-4d68-aa12-e8ef73e0f392
