### ISSUE TITLE
Sales Order > Create material request > (requesting different material which is not listed "Sales order items" )  the material request won't have connection with the Sales order

### ISSUE THREAD

**Issue by vitamincy** [frappe/erpnext#35068]
### Information about bug

1: Create a quotation with item 1,2,3,4          ----OK
2: Submit the quotation                                ----OK
3: Create a sales order from the quotation    ----OK
4: the quotation items will automatically fetched to Sales order items : 1,2,3,4  ----OK
5: Create a material request from sales order  (By default the sales order item will automatically listed)  ----OK
6: if we want to purchase a item which is not linked to the sales order (not shown on the list 1,2,3,4 ) for example we want to request the item 5  when creating the material request. it works fine  -----OK
7: once the material request "submitted" on the "connection tab" the sales order is not linked   -----ISSUE /BUG  

### Module

selling

### Version

Frappe Version - 14.34.0
Erpnext Version - 14.23.0

### Installation method

manual install

**Comment by s-aga-r** [comment]
@vitamincy unable to replicate with the mentioned steps:

Quotation for Items 1, 2, 3.
![image](https://github.com/frappe/erpnext/assets/63660334/e71d3a4a-8ef2-4bdb-9933-2c2bf5887500)

Sales Order for Items 1, 2, 3.
![image](https://github.com/frappe/erpnext/assets/63660334/85ba3cb9-d496-4dd1-9fbc-010e300655be)

Material Request for Items 1, 2, 3, 4.
![image](https://github.com/frappe/erpnext/assets/63660334/00d7dfc6-2456-4ce2-ac18-76e76e90ac09)

Linked Sales Order in Material Request.
![image](https://github.com/frappe/erpnext/assets/63660334/19436199-b95d-4771-92e2-3eac8c146f57)

**Comment by s-aga-r** [comment]
@vitamincy The `Material Request Items` table holds the reference of the `Sales Order` and `Sales Order Item` by which it shows the linked `Sales Order` in the connections. As you are trying to add an item which is not present in the Sales Order the references will also be missing in that case.

![image](https://github.com/frappe/erpnext/assets/63660334/0933a41d-22bd-44b9-93e7-63581e0a87c0)
