### ISSUE TITLE
Enhancement: email does not search for employee's emails

### ISSUE THREAD

**Issue by justinlusg** [frappe/erpnext#3507]
![image](https://cloud.githubusercontent.com/assets/12539216/8298159/9e161a44-1997-11e5-9b72-827f2bd48dbc.png)

Currently, when sending emails, the system only search for customer contacts emails. Can we suggest for the system to also display shortcuts to employee's emails? Because alot of time we might be sending the email to our internal employees instead for the particular opportunity or sales order. 

This feature might be useful.

**Comment by rmehta** [comment]
Need to add a hook to this:

https://github.com/rmehta/frappe/blob/empty-form-fix/frappe/email/__init__.py#L29

and then build a union query to make it generic for any doctype.

**Comment by justinlusg** [comment]
Could it be implemented in the next update? :dancer:

**Comment by rmehta** [comment]
Not sure this gets priority :) Just have a look at our list! My first priority now is to make sure all the erpnext tests pass.

**Comment by justinlusg** [comment]
Understandable! :D Thanks for all the fast and great work on ERPNext!

**Comment by jwrober** [comment]
I don't think this exists any longer as an issue. i get listing of all users and customers now when trying to send emails by default at the top of the list.
