### ISSUE TITLE
Sales invoice  Total Quantity after submission when updating some field (which is allowed edit after submit) error as per picture

### ISSUE THREAD

**Issue by vitamincy** [frappe/erpnext#35076]
### Information about bug

![image](https://user-images.githubusercontent.com/116448314/234783933-70960da1-0e86-423f-8fcd-812b01556717.png)

### Module

selling

### Version

Frappe Version 14.34.0
ErpNext Version 14.23.0

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
Hi @vitamincy,

Everything is running smoothly without any problems in the latest versions 14 and 15. You might encounter an issue if you change the precision of a field, but otherwise, you shouldn't face any problems.

Thank You!
