### ISSUE TITLE
translation errors

### ISSUE THREAD

**Issue by ghost** [frappe/erpnext#35078]
### Information about bug

translation file line 24 -> qustion -> question
translation file line 43 -> Accessable -> Accessibly
translation file line 296, 297, 298, 1229, 1680, 1998, 2024, 3622, 4334, 9182, 9385, 9515, 9568 -> Atleast -> At least
translation file line 473-> Vaulation-> Valuation
translation file line 489, 910, 1776 -> Equipments -> Equipment
translation file line 518 -> Chargeble -> Chargeable
translation file line 574 -> manadatory -> mandatory
translation file line 745, 7761 -> Customerwise -> Customer wise
translation file line 887 -> cutomer -> customer
translation file line 936 -> submited -> submitted
translation file line 936 -> apllication -> application
translation file line 962, 963, 964 -> submittting -> submitting
translation file line 965 -> betweeen -> between
translation file line 1122 -> Furnitures -> Furniture
translation file line 1139 -> Invocies -> Invoices
translation file line 1449 -> madatory -> mandatory
translation file line 1461 -> sucessfully -> successfully
translation file line 1591, 1592 -> Memebership -> Membership
translation file line 1603 -> Milestonde -> Milestone
translation file line 1751 -> authroized -> authorized
translation file line 1917 -> Tems -> Terms
translation file line 1987-> Maintaince -> Maintenance
translation file line 2520 -> Ememption -> Exemption
translation file line 2573, 2654, 2655, 3219, 3221, 3222, 4145, 4166, 4168, 4350, 4352, 4707, 8360, 9761 -> Upto -> Up to
translation file line 2754 -> skiping -> skipping
translation file line 2574 -> overlaped -> overlapped
translation file line 2755 -> Softwares -> Software
translation file line 2878 -> Suplier -> Supplier
translation file line 2896 -> Suppliies -> Supplies
translation file line 3025 -> skiped -> skipped
translation file line 3025 -> exisiting -> existing
translation file line 3034 -> activites -> activities
translation file line 3149 -> Transfered -> Transferred
translation file line 3165 -> Treshold -> Threshold
translation file line 3167 -> Trialling -> Trialing
translation file line 3172 -> coversion -> conversion
translation file line 3335 -> agianst -> against
translation file line 3348 -> enought -> enough
translation file line 3387 -> submittted -> submitted
translation file line 3488 -> Fieldtype -> Field type
translation file line 3658 -> dependant -> dependent
translation file line 3658 -> ccompleted -> completed
translation file line 3770 -> greter -> greeter
translation file line 3935 -> Compnay -> Company
translation file line 3970 -> mandatroy -> mandatory
translation file line 4100 -> greated -> greeter
translation file line 4122 -> retreived -> retrieved
translation file line 4373 -> asign -> assign
translation file line 4405 -> sucessfully -> successfully
translation file line 4850 -> Writeoff -> Write-off
translation file line 5233, 5234 -> DIscount -> Discount
translation file line 5314 -> LInked -> Linked
translation file line 5790 -> TIme -> Time
translation file line 6070 -> to to -> to
translation file line 6426, 6605, 6910, 6914, 6928, 6929 -> Checkin -> Check-in
translation file line 6542, 6548 -> Prefered -> Preferred
translation file line 7041 -> Refuelling -> Refueling
translation file line 7621 -> Deductee -> Deducted
translation file line 8055 -> overrridden -> overridden
translation file line 8496 -> Comptables -> Compatibles
translation file line 8903 -> Practitoner -> Practitioner
translation file line 8918 -> Similary -> Similarly
translation file line 8929 -> Detials -> Details
translation file line 9203 -> Depreciatied -> Depreciated
translation file line 9285 -> Barnch -> Branch
translation file line 9362 -> occured -> occurred
translation file line 9383 -> postive -> positive
translation file line 9477 -> submittted -> submitted
translation file line 9700 -> Occured -> Occurred
translation file line 9703 -> reserverd -> reserved
translation file line 9703, 9831 -> fullfill -> fulfil
translation file line 9714 -> serilialized -> serialized
translation file line 9765 -> succesfully -> successfully
translation file line 9865, 9866 -> succesfully -> Put away

### Module

regional

### Version

ERPNext 14 version from de.csv file

### Installation method

None

**Comment by dj12djdjs** [comment]
@gbatkhuyag You can edit the de.csv file and create a pull request.

**Comment by ghost** [comment]
the problem is spelling errors in a core code of ERPNext
