### ISSUE TITLE
Sales Invoice (Return) on table item if "qty" value change to 0 the amount is not fetch 

### ISSUE THREAD

**Issue by farrasiqtsm1** [frappe/erpnext#35086]
### Information about bug

![image](https://user-images.githubusercontent.com/132031952/235044642-13ed78f2-b0d7-42f2-98ec-cb194b4fdd18.png)

when make sales invoice return on table item if field "qty" value change to 0 the amount is not fetch and still showing the amount when "qty" is -1

### Module

other

### Version

Frappe Version: v13.46.3 (version-13)
ERPNext: v13.43.0 (version-13)

### Installation method

None

**Comment by danjeremynavarro** [comment]
had the same issue the amount field is not updating properly on returns

**Comment by Nihantra-Patel** [comment]
Because Once you save the document, you can change the quantity and then change the amount.

main reason is: https://github.com/frappe/erpnext/pull/40700
