### ISSUE TITLE
No option to set additional discount to Net/Grand total in settings

### ISSUE THREAD

**Issue by maveezmh** [frappe/erpnext#35087]
### Information about bug

Applying Additional discount on a Sales or purchase document right now its doneat document level. user needs to select if its on net or grand total. 

for companies with Tax the discount is usually applied on Net total. but this is either set on document level or need to set default in each form manually. 

there is no option to define it at company level. where user can define by default discount for sales and purchase process will be applied on net or grand total.

### Module

accounts, buying, selling

### Version

ERPNext: v14.23.0 (HEAD)
Frappe Framework: v14.34.0 (HEAD)
Frappe HR: v14.2.3 (HEAD)
Payments: v0.0.1 (HEAD)

### Installation method

FrappeCloud

**Comment by Nihantra-Patel** [comment]
Hi @maveezmh,

This isn't a bug 😅.
Based on my understanding of your situation, you might want to look into pricing rules. They can help you set default discounts, although there might be some limitations. Some functionality (Tax discount) is not yet.

You can find more information about pricing rules here: https://docs.erpnext.com/docs/user/manual/en/pricing-rule#3-6-price-discount-scheme

Exploring the pricing rule [documentation](https://docs.erpnext.com/docs/user/manual/en/pricing-rule) might solve the issue.

Thank You!

Thank You!
