### ISSUE TITLE
Confusion between Contact Name and Organization name of Lead

### ISSUE THREAD

**Issue by geetanjalishitole** [frappe/erpnext#3509]
If  Lead created with below data 
 Contact Name=Geetanjali
Organization Name=Indictrans Technologies 

From above Lead  form
1.If we open the 'Customer' form then  lead details get fetched as 
    Full Name=Indictrans Technologies 

2.If we open the 'Opportunity' form then lead details get fetched as 
   Customer / Lead Name=Indictrans Technologies 

3.If we open 'Quotation' form then lead details get fetched as 
   Customer / Lead Name=Geetanjali

4.If we open 'Address' form then lead details get fetched as
   Lead Name=Geetanjali

**Comment by rmehta** [comment]
What is the solution?

**Comment by cgpurbaugh** [comment]
@rmehta Why not add another field in lead that concatenates contact name and organization name, and makes that the title?  Then change the fetches to pull that field, so it would always read
Geetanjali - Indictrans Technologies

**Comment by rmehta** [comment]
I think this is clear - the company name becomes "Customer" and lead name becomes "Contact" Maybe we should rename lead name as contact name

**Comment by rmehta** [comment]
Its already "Person Name" so closing
