### ISSUE TITLE
Wrong Calculation of Amount on Return Invoices

### ISSUE THREAD

**Issue by danjeremynavarro** [frappe/erpnext#35095]
### Information about bug

ERPNext is currently calculating the wrong amount when creating a sales invoice return

it doesn’t multiply the rate against the qty

![image](https://user-images.githubusercontent.com/46537526/235210957-cb634001-47ec-4b8e-9440-cc6331ec29f5.png)

### Module

accounts

### Version

ERPNext: v13.49.10
Frappe Framework: v13.51.3

### Installation method

None

**Comment by Nihantra-Patel** [comment]
Hi @danjeremynavarro,

Kindly upgrade to version 14 or 15, then refresh and check again.
**We no longer provide support for version 13 or older.** 

Everything is working fine. No problems were encountered in versions 14 and 15.


https://github.com/frappe/erpnext/assets/141945075/30aed45f-bb6f-45b0-a0a9-42e3ca19081d


Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!
