### ISSUE TITLE
Precision still doesn't work

### ISSUE THREAD

**Issue by mm86133** [frappe/erpnext#35099]
### Information about bug

Set precision to 8 decimal points in settings for both currency & float.

I.e. go to new purchase invoice, enter 0.07 for the amount and 0.004 for rate (i.e. cost per x units)

Or 1200 / 0.00084 

This is well known issue that is not resolved for number of versions..

Before closing please post result of a test showing that it is working.

### Module

buying

### Version

v14.18.2

### Installation method

docker

**Comment by mm86133** [comment]
https://github.com/frappe/erpnext/issues/17276

**Comment by mm86133** [comment]
![image](https://user-images.githubusercontent.com/52691210/235297732-21f4ecd2-d8ea-4f5c-9ec8-ccedf69a74a0.png)


result

![image](https://user-images.githubusercontent.com/52691210/235297740-02e44a2c-fa6a-4558-8e83-59772973d04a.png)

settings:

![image](https://user-images.githubusercontent.com/52691210/235297753-21823edf-ab32-492b-a5a5-541bd7aa8afe.png)

**Comment by Nihantra-Patel** [comment]
check it.


https://github.com/frappe/erpnext/assets/141945075/fb231ca1-e9ec-45a5-86b0-cf0087b9c344
