### ISSUE TITLE
Not found DocType Item Product Category not found The resource you are looking for is not available

### ISSUE THREAD

**Issue by shazej** [frappe/erpnext#35106]
### Information about bug

Not found DocType Item Product Category not found The resource you are looking for is not available

when clicking on projected stock quantity. the following error appears

### Module

stock

### Version

13
7

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
Not found DocType Item Product Category not found The resource you are looking for is not available
```

**Comment by nvisionitmu** [comment]
Same issue on v14 when trying to access or trying to create a new item

**Comment by s-aga-r** [comment]
The link field for `Item Product Category` might be available in Item DocType, try deleting the same.
