### ISSUE TITLE
Can't be able to delete Submitted Lead

### ISSUE THREAD

**Issue by HUMENTH** [frappe/erpnext#35111]
### Information about bug

I have created a Lead and Submitted; Now I want to delete that Lead. When I tried to delete it, system ask to cancel it first, but there is no cancel button found on Lead.

![image](https://user-images.githubusercontent.com/4609678/235416561-323597e0-cad8-46b2-a797-d5bf1a8d924a.png)

![image](https://user-images.githubusercontent.com/4609678/235416607-3f65a816-6622-4211-9b44-8dbe070d7ea2.png)

### Module

CRM

### Version

Frappe Version: 14.34.0
ERPNext Version: v14.23.0

### Installation method

manual install

**Comment by prononext** [comment]
Have the same problem, but without the Error message.  Please solve it.

**Comment by nabinhait** [comment]
There was a patch named `enable_all_leads` to unsubmit all the submitted leads, maybe the patch didn't executed in your site for some reason. Please run the patch, closing the issue.
