### ISSUE TITLE
Unable to Create Sale Invoice from Delivery Note

### ISSUE THREAD

**Issue by sumeetagra** [frappe/erpnext#35141]
### Information about bug

Sales Invoice cannot be created from Delivery Note as the Delivery Note Status is showing Completed on submit.

### Module

stock

### Version

ERPNext: v14.23.1 (version-14)

Frappe Framework: v14.35.0 (version-14)

### Installation method

manual install

**Comment by s-aga-r** [comment]
@sumeetagra The issue is not replicable. Please provide the steps to replicate it and reopen the issue.
