### ISSUE TITLE
Picker for Item Attributes Layering Error

### ISSUE THREAD

**Issue by justinlusg** [frappe/erpnext#3515]
![image](https://cloud.githubusercontent.com/assets/12539216/8348073/3855bbc8-1b41-11e5-88ae-e1c96e9c4701.png)

Steps to replicate
1) Create new item
2) Enable variants and create variants
3) Add new item attribute 
4) Mouse click on item attribute value
5) picker appears behind popup

**Comment by rmehta** [comment]
fixed finally
