### ISSUE TITLE
Counter Party GL created from Party Link doesn't get cancelled when you cancel the document

### ISSUE THREAD

**Issue by asoral** [frappe/erpnext#35150]
### Information about bug

I created a Link Party to link A supplier with a customer of his own. I then created a sales invoice for the customer (linked one), only later to realize that I missed mentioning the cost center, I then had to cancel the Sales Invoice and re-create it. I missed something once again on this one, I had to cancel and amend once again.

But the last Sales Invoice I created was good and I can see the ledger entry as I wanted. I then navigated to the Supplier (linked to the customer I just created the sales invoice for), and I can see 3 journal entires showing up as -ve balance for this supplier now. Whereas, the other 2 should have been canceled, only the last was it correct.

### Module

accounts

### Version

Latest Version-14

### Installation method

FrappeCloud

**Comment by Nihantra-Patel** [comment]
Hi @asoral,

Everything is working fine. No problems were encountered in the latest versions 14 and 15.


https://github.com/frappe/erpnext/assets/141945075/b9e9ee1a-9c9d-403f-8f5b-ce570581ea4d

If the issue occurs then please create a new issue according to version (14 or 15) with a video document if possible.

Thank You!
