### ISSUE TITLE
Unable to update Subcontracted PO as in V13

### ISSUE THREAD

**Issue by ram-chandu** [frappe/erpnext#35157]
Hi Team,

Facing the following issue in V14 instance:

Here in the V14 Purchase Order created for subcontracting , we are not getting an option "Update items" which was available in V13 for update PO item/rate/qty before creating any purchase receipts.

Steps to Replicate:
1. Navigate to the Purchase Order created from the Production Plan at the following link: https://rangsutra-test-v14.frappe.cloud/app/purchase-order/PO%2FFY23%2Fbranch_abbr0013
2. Click on "Create" and create a subcontracting order at the following link: https://rangsutra-test-v14.frappe.cloud/app/subcontracting-order/SC-ORD-2023-00011
3 .Once the subcontracting order is created, click on the "Transfer" button and then click on "Material to Supplier": https://rangsutra-test-v14.frappe.cloud/app/stock-entry/MI%2FFY23%2FBK0005
4 .Create a subcontracting receipt at the following link: https://rangsutra-test-v14.frappe.cloud/app/subcontracting-receipt/MAT-SCR-2023-00006
Use case:
   In v13 the "Update Item" button was available in Subcontracting PO and this button was visible until you created a Purchase Receipt. And before receipt we were able to update item rate/quantity etc but now we are unable to edit rate/quantity in v14 subcontract purchase order. We need this option in v14 because we create subcontract purchase orders before finalizing service rates. After finalizing the service rate, we update the PO before creating the first receipt. So please provide "Update Item" button to update PO.
Please Note: After updating the service rate in the PO, the subcontracted item rate in the subcontracting order must also be updated as the service rate has changed.

Observation:
1. In the Purchase order created for subcontracting, we are not getting an option "Update items" which was available in v13 for update PO item/rate/qty before creating any purchase receipts. But in v14 the option is missing.

Expectation:
1. Here we are expecting the option "Update items" to be available in v14 for update PO item/rate/qty before creating any purchase receipts.

Attaching the screenshots for reference:
Old subcontracting PO:
![2tMRQBG](https://user-images.githubusercontent.com/119317369/236153776-33fa2421-08f4-48f5-9392-aa41fcb1fef9.png)

New subcontracting PO:
![9YM4CFI](https://user-images.githubusercontent.com/119317369/236153791-d8fdf00c-777a-4282-bd2c-ca77bbf1369a.png)

Thanks,
Ram.

**Comment by Rajatha26** [comment]
Hi Team,

This issue is of high priority. Kindly check and update.

Thanks and Regards
Rajatha B
Functional Consultant
Promantia Business Solutions Pvt. Ltd.
Bangalore

**Comment by s-aga-r** [comment]
Hi @ram-chandu,

The `Update Items` button is hidden for Subcontracted Purchase Order in V14 as in V13 the Purchase Receipts are created against the Purchase Order but in V14 the Subcontracting Receipt is created against Subcontracting Order. So if you want to update the Items or Qty in Purchase Order the same should be validated and updated in respective Subcontarcting Order and Subcontracting Receipts. Currently Update Items provision is not available for V14 Subcontracted Purchase Order, we will add the same to our roadmap.
