### ISSUE TITLE
wkhtmltopdf : currently problems and future problems awaiting to happen

### ISSUE THREAD

**Issue by lstbrian** [frappe/erpnext#35155]
### Information about bug

I found out a lot fo problems are linked to gkhtmltopdf which erpnext embed into their framework but that repo is getting obsolete and isn't compatible with many css, or even some js script files. That is a problem especially with jinja which erpnext users might use css a lot for print format section.

### Module

other

### Version

All versions 13 and 14.

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
For example, grid css doesn't work when html is converted to pdf.
```

**Comment by lstbrian** [comment]
Was thinking of should replacing this repo by another

**Comment by rafalkrupinski** [comment]
wkhtmltopdf has been abandoned the last year and the repository is now archived.
Its author recommends WeasyPrint.

**Comment by ankush** [comment]
duplicate
