### ISSUE TITLE
Asset Wrong Deprecation Amount Calculation on Selling of Asset  

### ISSUE THREAD

**Issue by choureySumit** [frappe/erpnext#35159]
### Information about bug

Asset Wrong Deprecation Amount Calculation on Selling of Asset  

Details is Attached 
[Asset.docx](https://github.com/frappe/erpnext/files/11396446/Asset.docx)

### Module

accounts, assets

### Version

Frappe Framework: v14.34.0 (version-14)
ERPNext: v14.23.0 (version-14)

### Installation method

None

**Comment by anandbaburajan** [comment]
Thanks @choureySumit for reporting and for the detailed doc. Will take a look.

**Comment by anandbaburajan** [comment]
@choureySumit, fixing this issue through https://github.com/frappe/erpnext/pull/35396.
