### ISSUE TITLE
Stock Reconciliation form get save and submit  without entering quantity and valuation rate.

### ISSUE THREAD

**Issue by ShraddhaRanjane** [frappe/erpnext#3516]
Steps To Reproduce:-
I have created new Warehouse  i.e Central Store
created three new item by keeping Default warehouse as "Central Store". 
1. Create new stock reconciliation
2. Click on "Get Items" button.
3. Select Respective 'Warehouse' from list
4. click on "update" button
5. All item code(three newly created + existing in application) get fetched with quantity and valuation rate  as zero
6. when i click on "Save" button  then error message get displayed as
"Removed items with no change in quantity or value." 
an all items get removed from table grid.
7. Now close Message pop up 
8. click on "Submit" button
9. Record get submitted.

**Comment by rmehta** [comment]
make the item table mandatory
