### ISSUE TITLE
Workflow State issue when cancelling a doctype

### ISSUE THREAD

**Issue by lakhanidaniyal** [frappe/erpnext#35160]
### Information about bug

I am trying to cancel sales invoice but it keeps on showing a pop-up message "Workflow State transition not allowed from Draft to Approved".
There is no workflow defined for sales invoice but still the error persists
![image](https://user-images.githubusercontent.com/132129802/236184729-5cfb462b-c72a-42cc-aea1-9316018b0301.png)

### Module

selling

### Version

version 14

### Installation method

None

**Comment by Nihantra-Patel** [comment]
Hi @lakhanidaniyal,

I think, you have not configured the workflow for the doctype, that the issue. Please check the [documentation](https://docs.erpnext.com/docs/user/manual/en/workflows) of the workflow and also check the [video](https://www.youtube.com/watch?v=OZjreBjFHtY) of the workflow.

We haven't faced the issue on the latest version 14.

Thank You!
