### ISSUE TITLE
Data Import: New DocType Doesn't Show Up

### ISSUE THREAD

**Issue by natalia-3nitilab** [frappe/erpnext#35183]
### Information about bug

Added a new custom DocType. Trying to do the Import Records, the new doctype doesn't show up.

### Module

integrations

### Version

cloud trial just started

### Installation method

FrappeCloud

**Comment by natalia-3nitilab** [comment]
Had to Reload to clear the cache. Sorry, not a bug

**Comment by SherinKR** [comment]
In Doctype, Under 'Form Settings' Section there is one checkbox named 'Allow Import (via Data Import Tool)'. Enable the Same and try again.
