### ISSUE TITLE
Make the LMS "null_card" transparent

### ISSUE THREAD

**Issue by willspenc** [frappe/erpnext#35193]
### Information about bug

Currently, if a single Program is published to the LMS portal, the other slots for programs as blank but
visible. If the background is set to white, then they are also invisible. But when a background colour is set,
then one can see these two white blocks.

Un-dersired outcome: white blocks when background colour is set.

Desired outcome : white blocks of unsused program-slots invisible.

Looking at the code , these are the "null_cards".. (.../lms/macros/card.html )

`div class="h-100 d-none d-sm-block" style="border: 1px solid rgba(209,216,221,0.5);border-radius: 0.25rem;background-color: rgb(250, 251, 252);"`

To make it invisible so that any background colour shows, add the "opacity: 0" directive to the "null_card" macro.

` div class="h-100 d-none d-sm-block" style="border: 1px solid rgba(209,216,221,0.5);border-radius: 0.25rem;background-color: rgb(250, 251, 252);opacity: 0;"`

### Module

portal

### Version

V13.48.1

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
Hi @willspenc,

We no longer provide support for version 13 or older. 

If the issue occurs then please create a new issue according to the version (14 or 15) on [LMS GitHub](https://github.com/frappe/lms).

Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!
