### ISSUE TITLE
The production plan pushes down the material request, the system is very slow

### ISSUE THREAD

**Issue by JasonFu06** [frappe/erpnext#35194]
### Information about bug

when run follow command, the system is very slow.

SELECT DISTINCT `tabStock Entry`.name
FROM `tabStock Entry`
LEFT JOIN `tabStock Entry Detail` ON (`tabStock Entry Detail`.parenttype = 'Stock Entry'
                                      AND `tabStock Entry Detail`.parent = `tabStock Entry`.name)
WHERE `tabStock Entry Detail`.`material_request` = 'X202300695'
LIMIT 100
OFFSET 0
![933](https://user-images.githubusercontent.com/93484850/236622958-f57096c1-fecd-4596-9eea-e25e977f3f4e.png)
![952](https://user-images.githubusercontent.com/93484850/236622970-1ee133ae-3ce4-4584-b4a1-17f4210171d3.png)
![032](https://user-images.githubusercontent.com/93484850/236622975-1d63fb7d-6f2a-4d9e-b8d4-84db6d328753.png)

### Module

buying, manufacturing

### Version

Frappe : V14.35
Erpnext V14.23.3

### Installation method

manual install

**Comment by rohitwaghchaure** [comment]
@JasonFu06  Can you add index on the column material_request in the stock entry detail table and check
