### ISSUE TITLE
Common Ledger Party 

### ISSUE THREAD

**Issue by riddhisolanki001** [frappe/erpnext#35199]
Hello Community,

there is a problem with the general ledger report, how can we set the filter of party and party type if there is common party accounting?

if we search in a bar under the party column then the total column will disappear so how can we see the proper ledger of the common party? how can I solve this

**Comment by Nihantra-Patel** [comment]
Reference:

https://discuss.frappe.io/t/common-party-accounting-ledger/104261/4?u=ncp

Thank You!
