### ISSUE TITLE
Can't hide 'Add Row' Button in child table

### ISSUE THREAD

**Issue by zacharysalvatore** [frappe/erpnext#35205]
### Information about bug

```
frappe.ui.form.on('Warehouse', {
 	onload_post_render: function(frm) {
 		frm.fields_dict.rats_details.grid.wrapper.find('.grid-add-row:not(.hidden)').addClass('hidden');
		frm.fields_dict.rats_details.grid.wrapper.find('.grid-remove-rows').hide();
 		frm.fields_dict.rats_details.grid.wrapper.find('.grid-remove-all-rows').hide();
	}
})
```
add row, remove row, remove all could hidden use above code. but when i use in 'refresh' section, remove row, remove all could hidden, but add row can't hidden

### Module

stock

### Version

ERPNext: v14.23.3
Frappe : v14.35.0

### Installation method

docker

**Comment by Solufyin** [comment]
Hi @zacharysalvatore,

Please apply and check it.

```js
frappe.ui.form.on('Warehouse', {
    refresh: function(frm) {
       frm.set_df_property('rats_details', 'cannot_add_rows', true);
       frm.set_df_property('rats_details', 'cannot_delete_rows', true);
       frm.set_df_property('rats_details', 'cannot_delete_all_rows', true);
    }
});
```

Please check/set your child's table field name accordingly.

Thank You!

**Comment by zacharysalvatore** [comment]
> Hi @zacharysalvatore,
> 
> Please apply and check it.
> 
> ```js
> frappe.ui.form.on('Warehouse', {
>     refresh: function(frm) {
>        frm.set_df_property('rats_details', 'cannot_add_rows', true);
>        frm.set_df_property('rats_details', 'cannot_delete_rows', true);
>        frm.set_df_property('rats_details', 'cannot_delete_all_rows', true);
>     }
> });
> ```
> 
> Please check/set your child's table field name accordingly.
> 
> Thank You!

Problem Solved! Thank you very much! how do you find these properties by the way. I searched all interent can't find the right solution before.

**Comment by Solufyin** [comment]
Hi @zacharysalvatore,

Please check it reference.
https://github.com/search?q=repo%3Afrappe%2Ferpnext%20cannot_add_rows&type=code
https://github.com/search?q=repo%3Afrappe%2Ferpnext+cannot_delete_rows&type=code

I hope this helps.
Thank You!
