### ISSUE TITLE
Journal Entry transaction did not appear in General Ledger

### ISSUE THREAD

**Issue by Bionmedical** [frappe/erpnext#35201]
### Information about bug

Hi,
One transaction on our Journal entry did not appear in the general ledger.
This transaction previously appeared on our GL, but suddenly it did not appear and did affect our balance sheet.
As attached below our transaction in journal entry which did not appeared in GL

![image](https://user-images.githubusercontent.com/113512658/236728388-fae1afe8-d13e-4ae1-8b37-8b10cf2df5d3.png)

Is this issue due to an update by Frappe? Since this issue happened just last week.
Thank you.

### Module

accounts

### Version

Frappe version - v13.56.1 (HEAD)
ERPNext version- v13.50.0 (HEAD)

![image](https://user-images.githubusercontent.com/113512658/236727878-f7a2782b-d6ac-4426-8996-ab0abab9bc65.png)

### Installation method

None

**Comment by shinzuco** [comment]
I have the same exact issue in version  erpnext 14.20 . Is this a user error?

**Comment by Bionmedical** [comment]
> 

Not a user error, I think is due to update by the system only. It do takes around 5 days for our transaction to appear back.

**Comment by shinzuco** [comment]
@Bionmedical But where you identify why?  Was there any background process stuck in queue?

**Comment by Bionmedical** [comment]
@shinzuco Sorry I'm not sure about this either.
This issue occurred when our system was updated at the beginning of May and at this time this transaction is lost and not on our record suddenly.

And after a few days this transaction is back to normal. I just think that this happen due to system update since this transaction is appearing back.

**Comment by shinzuco** [comment]
@Bionmedical Thanks for the input.

For anyone reading this in the future, we were facing this because we were entering a few 1000 JV's via the api/code and Submitted the document(of type Bank Entry)  without a madatory field (Cheque number).

The JV did get submitted but the gl entries did not get posted. Fixed it by manually running the on_submit function for journal entry.
