### ISSUE TITLE
CLOSING BALANCE IN THE CASHBOOKS ARE NOT CORRECT, ALSO  UNABLE TO DELETE THE PURCHASE INVOICE EVEN I HAVE THE ADMIN ACESS.

### ISSUE THREAD

**Issue by rs115199789** [frappe/erpnext#35213]
### Information about bug

CLOSING BALANCE IN THE CASHBOOKS ARE NOT CORRECT.
SOME OF THE CASHBOOK ENTRIES CLOSING BALANCE ARE NOT CORRECT.
ALSO THE CASHBOOK CLOSING BALANCE GLITCH IS A MAJOR ISSUE.
PLEASE PROVIDE A VALID SOLUTION FOR THIS BUG OR ISSUE.
![3](https://user-images.githubusercontent.com/132902023/236810759-8a179a3b-a516-4e51-a777-a6b2b0de2db2.PNG)

### Module

accounts, buying, selling, other

### Version

ERPNext: v13.50.0 (HEAD)

Frappe Framework: v13.56.1 (HEAD)

### Installation method

None

**Comment by Nihantra-Patel** [comment]
Hi @rs115199789,

We no longer provide support for version 13 or older. 

Everything is working fine. No problems were encountered in versions 14 and 15.

Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!

**Comment by rs1151997** [comment]
Thanks can you also please reply to my forum post i tagged you as well, Thank you
