### ISSUE TITLE
Setting Item Price from Template

### ISSUE THREAD

**Issue by nathanso** [frappe/erpnext#35210]
Hi there, new to ERPNext. Is there a way to set the price for templates? Our company price item variants the same and we have a lot of them.
I noticed in previous versions, this feature was available but now when I try to set the price, I get an error. Is there a workaround it?
![image_5](https://user-images.githubusercontent.com/4767622/236788309-46f17b6a-bfeb-471a-85a9-b9be5401a728.png)

**Comment by s-aga-r** [comment]
@nathanso 

**As Templates are NOT transaction items, they should not be selectable in the Item Price doctype.**

ref: https://github.com/frappe/erpnext/pull/34189

**Comment by TurkerTunali** [comment]
> **As Templates are NOT transaction items, they should not be selectable in the Item Price doctype.**

We can add a validation in the Stock Controller like if "Maintain Stock" is not selected in the Item master we can't create a stock transaction against it.

Templates are used to get prices for all variants. Customers can't assign the same price to the 100s of variants each month.

This is a must for variant management like garment and textile industries and it was working with v13. Either we need a tool to easily create prices for all variants (which will be painful to edit) or we need this feature back.
