### ISSUE TITLE
HSN-wise-summary of Outward Supplies GST-report showing incorrect data for UQC

### ISSUE THREAD

**Issue by innomalous** [frappe/erpnext#35217]
### Information about bug

Hello team,

The HSN-wise Summary of Outward Supplies report under Other GST Reports is reporting incorrect UQC data.

We are using **Kg** for HSN 2309, **Units** for HSN 23091000, and **Nos** for HSN 996812 as the UOMs in our invoices. However, the UQC is reported as OTH and NA in the report. (See screenshot below)

![erpnext hsn screenshot](https://user-images.githubusercontent.com/42608563/236846797-7a0ff3e3-a947-4ad7-9882-b3322b87e464.jpg)

All other data seems correct, just the UQC is reported incorrectly.

### Module

accounts

### Version

Frappe v14.35.0
ERPNext v14.23.2
India Compliance v14.6.1

### Installation method

FrappeCloud

**Comment by bhavyajicomputers** [comment]
As Per GST Portal requirement the UQC of service items should be NA and quantity Should not be mentioned. its not bug.

**Comment by innomalous** [comment]
Yes. But the other two items are not service items. They are products, and their UQC should not be OTH.

That is a bug.

**Comment by deepeshgarg007** [comment]
@innomalous Please raise this on https://github.com/resilient-tech/india-compliance, closing this from here
