### ISSUE TITLE
erpnext white screen error after submission of production order.

### ISSUE THREAD

**Issue by sebbaghnassim21** [frappe/erpnext#35229]
### Information about bug

I need help .
erpnext white screen error after submission of production order.

### Module

manufacturing

### Version

V 13

### Installation method

manual install

**Comment by rohitwaghchaure** [comment]
@sebbaghnassim21 this is not replicating, could you please provide more information to replicate this issue

**Comment by Surianarayanan** [comment]
@sebbaghnassim21 Please share, if the solution already got.

Because I also run into the same. Thanks in advance.

**Comment by sebbaghnassim21** [comment]
I deleted the time of each operation. It works very well.

**Comment by Surianarayanan** [comment]
@sebbaghnassim21 Can you elaborate the procedure ? Because 'time' variable is mandatory / >0, by default, for the operational / stage records. Bit confused, between, table structure and query changes or data edit.

Thanks for replying and looking forward again.

**Comment by mightyteja** [comment]
I was able to fix this issue by updating the Production Capacity in "Workstation". 

<img width="883" alt="image" src="https://github.com/frappe/erpnext/assets/2662727/5910df42-d0e9-4c5f-bebe-2e9868a895f5">
