### ISSUE TITLE
Clock Changes in Cairo, Egypt  (Daylight Saving Time)

### ISSUE THREAD

**Issue by melrefaie** [frappe/erpnext#35226]
### Information about bug

Egypt changed its clock but its not updated in erpnext (Daylight Saving Time)
[https://www.timeanddate.com/time/change/egypt/cairo](url)

timezone still did not change. and all times are fault now. 

28 Apr 2023 - Daylight Saving Time Started
When local standard time was about to reach
Friday, 28 April 2023, 00:00:00 clocks were turned forward 1 hour to
Friday, 28 April 2023, 01:00:00 local daylight time instead.

### Module

other

### Version

ERPNext: v14.23.4 (HEAD)

Frappe Framework: v14.35.0 (HEAD)

### Installation method

None

**Comment by Nihantra-Patel** [comment]
Hi @melrefaie,

Please check it in the new update of version 14. Maybe it is fixed.
If the issue occurs then please create a new issue according to version (14 or 15) with a video document if possible.

Thank You!
