### ISSUE TITLE
Can't access Shopify Integration Settings

### ISSUE THREAD

**Issue by zzecool** [frappe/erpnext#35232]
### Information about bug

Hello there recently i tried to setup Shopify Integration.

After a refresh i lost access to the settings when i press "Shopify Settings" it goes nowhere.

![image](https://github.com/frappe/erpnext/assets/2816897/9b8c1084-6741-4235-acb6-c4596c4ff652)

As im running on Frappe Cloud i tried to deactivate and reactive site to no avail.
Next thing that i tried is to Uninstall the Ecommerce Integrations app and reinstall it with the hope that this will fix the access.

And now at least im getting an error when i try to access the "Shopify Settings"

![shopify error](https://github.com/frappe/erpnext/assets/2816897/4b366674-ef2b-498f-ad41-948af2f9a889)

Any help will be appreciated.

Thanks in advance.

### Module

ecommerce

### Version

ERPNext: v13.50.0 (HEAD)
Frappe Framework: v13.56.1 (HEAD)

### Installation method

FrappeCloud

**Comment by zzecool** [comment]
Now i see that during reinstall of "ecommerce_integrations" app im getting a failure with the following log:

> Installing ecommerce_integrations...
> Updating DocTypes for ecommerce_integrations: [========================================] 100%
> An error occurred while installing ecommerce_integrations: Module import failed for Membership Settings (erpnext.non_profit.doctype.membership_settings.membership_settings Error: No module named 'erpnext.non_profit.doctype.membership_settings')
> Traceback (most recent call last):
>   File "apps/frappe/frappe/modules/utils.py", line 243, in load_doctype_module
>     doctype_python_modules[key] = frappe.get_module(module_name)
>   File "apps/frappe/frappe/__init__.py", line 1205, in get_module
>     return importlib.import_module(modulename)
>   File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
> ModuleNotFoundError: No module named 'erpnext.non_profit.doctype.membership_settings'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "apps/frappe/frappe/commands/site.py", line 293, in install_app
>     _install_app(app, verbose=context.verbose)
>   File "apps/frappe/frappe/installer.py", line 188, in install_app
>     add_to_installed_apps(name)
>   File "apps/frappe/frappe/installer.py", line 215, in add_to_installed_apps
>     post_install(rebuild_website)
>   File "apps/frappe/frappe/installer.py", line 369, in post_install
>     init_singles()
>   File "apps/frappe/frappe/installer.py", line 386, in init_singles
>     doc = frappe.new_doc(single)
>   File "apps/frappe/frappe/__init__.py", line 999, in new_doc
>     return get_new_doc(doctype, parent_doc, parentfield, as_dict=as_dict)
>   File "apps/frappe/frappe/model/create_new.py", line 24, in get_new_doc
>     frappe.local.new_doc_templates[doctype] = make_new_doc(doctype)
>   File "apps/frappe/frappe/model/create_new.py", line 40, in make_new_doc
>     {"doctype": doctype, "__islocal": 1, "owner": frappe.session.user, "docstatus": 0}
>   File "apps/frappe/frappe/__init__.py", line 1079, in get_doc
>     doc = frappe.model.document.get_doc(*args, **kwargs)
>   File "apps/frappe/frappe/model/document.py", line 77, in get_doc
>     controller = get_controller(doctype)
>   File "apps/frappe/frappe/model/base_document.py", line 82, in get_controller
>     site_controllers[doctype] = _get_controller()
>   File "apps/frappe/frappe/model/base_document.py", line 64, in _get_controller
>     module = load_doctype_module(doctype, module_name)
>   File "apps/frappe/frappe/modules/utils.py", line 246, in load_doctype_module
>     "Module import failed for {0} ({1})".format(doctype, module_name + " Error: " + str(e))
> ImportError: Module import failed for Membership Settings (erpnext.non_profit.doctype.membership_settings.membership_settings Error: No module named 'erpnext.non_profit.doctype.membership_settings')

**Comment by Nihantra-Patel** [comment]
**We no longer provide support for version 13 or older.**

Kindly upgrade to version 14 or 15.

If have any issue then raised issue on [Ecommerce Integrations](https://github.com/frappe/ecommerce_integrations/issues)

Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!
