### ISSUE TITLE
Posting date and time on stock reconciliation gets updated to current date and time, on approval

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#35243]
### Information about bug

**Steps to reproduce**

- Create a workflow for Stock Reconciliation, just one approval is enough.
- Create a stock reconciliation, say on **9 May 2023**, **do not tick Edit Posting Date and Time, the bug happens when this is not ticked****
- Send the Stock Reconciliation for approval
- Approve the stock reconciliation, on **10 May 2023**, on approval, the Posting Date and Time are updated to the current date and time. Shouldn't be the case, since the stock reconciliation was as of stock take on 9th May 2023.

**_Note:_** if Edit Posting Date and Time, is ticked at time of creation, on approval, posting date and time, are not updated to current date and time.

### Module

stock

### Version

ERPNext: v14.23.4 (HEAD)
Frappe Framework: v14.35.0 (HEAD)

### Installation method

FrappeCloud

**Comment by Nihantra-Patel** [comment]
Hi @muchai,

You are right but it's not a bug because the condition is set in the validate_posting_time method. So, please review the link for more information.
https://github.com/frappe/erpnext/blob/develop/erpnext/utilities/transaction_base.py#L18-L31


`stock_reconciliation.py`
```py
def validate(self):
	self.validate_posting_time()
```

`transaction_base.py`
```py
def validate_posting_time(self):
	# set Edit Posting Date and Time to 1 while data import
	if frappe.flags.in_import and self.posting_date:
		self.set_posting_time = 1

	if not getattr(self, "set_posting_time", None):
		now = now_datetime()
		self.posting_date = now.strftime("%Y-%m-%d")
		self.posting_time = now.strftime("%H:%M:%S.%f")
	elif self.posting_time:
		try:
			get_time(self.posting_time)
		except ValueError:
			frappe.throw(_("Invalid Posting Time"))
```

I hope this helps.

Thank You!

**Comment by muchai** [comment]
@Nihantra-Patel Thanks for the feedback.

- Albeit, I think the behavior should be consistent, whether user ticks, **Edit Posting Date and Time** or not
- Also, when is the actual posting date and time, when transaction was created. Right?

**Comment by Nihantra-Patel** [comment]
When "Edit Posting Date and Time" is set to 1, the date and time won't change. However, if "Edit Posting Date and Time" is set to 0 and you save or submit the transaction after a few days, it will use the current time. Please review the condition for better understanding.
