### ISSUE TITLE
Issue with income account for invoices Created with include Payment Option

### ISSUE THREAD

**Issue by maveezmh** [frappe/erpnext#35241]
### Information about bug

>>1 Created a POS Profile: with default income account as "Research Activities-el"

![image](https://github.com/frappe/erpnext/assets/112148467/1a173696-a1b8-41be-82bf-a7ab74b03385)

>>2 Created a  item "Indian Apple" with no default income account

![image](https://github.com/frappe/erpnext/assets/112148467/c8917a23-f20d-4b10-a5cc-33eb677c4bb8)

>>3 Default Income account in company is set to "Sales Account-el"
![image](https://github.com/frappe/erpnext/assets/112148467/e7e29821-1cb4-457d-9005-7740172118c0)

>>4 Created a sales invoice with **include payment** Checked
![image](https://github.com/frappe/erpnext/assets/112148467/4851a295-635e-487e-96a6-a2c724f81c23)

>>5 when we save and submit the invoice the default income account in Item master is set to POS profile income account.

**P.S. Clear Cache to see changes in item master**

![Screenshot 2023-05-10 at 10-57-58 Indian Apple - F002](https://github.com/frappe/erpnext/assets/112148467/a2df9717-a3d3-4c5c-83f2-a1115cbf3886)

### Module

accounts, stock, buying, selling

### Version

issue is on both V13 and V14 

ERPNext: v13.49.4 (HEAD)
Frappe Framework: v13.51.0 (HEAD)

ERPNext: v14.23.4 (HEAD)
Frappe Framework: v14.35.0 (HEAD)
Frappe HR: v14.3.0 (HEAD)
Payments: v0.0.1 (HEAD)

### Installation method

FrappeCloud

**Comment by Nihantra-Patel** [comment]
Hi @maveezmh,

You are right but It's not a bug, it's designed this way to prevent the accidental selection of the wrong account automatically.

Let me explain. This feature applies not only to the Point of Sale (POS) but also sets the Default Sales or Purchase Account at the time of the transaction (such as creating a Sales Invoice or Purchase Invoice).

If you've already set the Income Account, it won't change. But if you haven't set the income account and you create a Sales Invoice or POS Invoice, it will automatically use the default income account for your company. Additionally, it will set the income account in the Item Master to prevent users from selecting the wrong account and causing issues in the General Ledger. I hope this clarifies the situation.

Thank You!

**Comment by maveezmh** [comment]
@Nihantra-Patel 
POS profile has default pos income account and company master has a default income account. now when a pos entry is done thec item master gets updated with POS income account

and because of this all the normal sales invoices will have POS income account instead of default company income account.

i believe this is not right approach
