### ISSUE TITLE
CoA importer: Forced Equity Account as a root account

### ISSUE THREAD

**Issue by nissekalle0** [frappe/erpnext#35252]
### Information about bug

I can not import a CoA because the importer forces me to have an Equity root account.
IN BAS chart of accounts, which is widely used in the Nordic, the Equity account is not a root account it is a group account with the account number 20.
It means I am blocked to import the CoA

### Module

accounts

### Version

latest version 14.xx

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
Please try to import on the stable version 14 or 15.

Thank You!
