### ISSUE TITLE
CoA importer: Several root account as Root Type: Expense

### ISSUE THREAD

**Issue by nissekalle0** [frappe/erpnext#35254]
### Information about bug

In the BAS CoA which is used in the Nordic there are several so called class accounts as root accounts:

4 Cost of goods, materials and certain subcontract work
5 Other external operating expenses/costs
6 Other external operating expenses/costs
7 Personnel costs, depreciation etc.
8 Financial and other income and expenses

They are all of Root Type: Expense

The design of CoA is not flexible enough to make it possible...!!!

### Module

accounts

### Version

Latest 14.xxx

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
none
```

**Comment by deepeshgarg007** [comment]
@nissekalle0 Users have the provision to completely replace the existing COA and also modify and add their own account. Please mention specifics as to where are you unable to modify things and then please reopen the issue
