### ISSUE TITLE
UI bug:- "Item Attribute value" not get search or displayed

### ISSUE THREAD

**Issue by ShraddhaRanjane** [frappe/erpnext#3525]
Steps To Reproduce:-
1.I have created New Item Attribute and its Attribute values.
2. when i select Respective "item Attribute" from drop down list. on 'Item master' form
3. then its 'Item Attribute Value'  not get displayed or search.
4. when i enter manually Value and remove it again ,then it displayed in light font.

**Comment by jof2jc** [comment]
I'm facing the same issue
https://discuss.frappe.io/t/found-some-layout-issues/6422

**Comment by neilLasrado** [comment]
@jof2jc  this has been fixed. Please update and recheck.

**Comment by jof2jc** [comment]
@neilLasrado I've just updated to latest 5.1.2 but no autocomplete/autosuggest while inputing item attribute value on Manage Variants form...

**Comment by neilLasrado** [comment]
@jof2jc yes was able to replicate.
