### ISSUE TITLE
Youtube video statistics not updating

### ISSUE THREAD

**Issue by willspenc** [frappe/erpnext#35250]
### Information about bug

When creating a Video and linking this to a Youtube video, the stats updates when you "save" the information 
entered.

From there on , the stats does not update automatically as per the interval set.

Desired outcome: Stats updating automatically per set interval.

Additional info:

1.When accessing the Google Developers Console, it is clear that there is an attempt to get info because one can
see on the graph an access every 30 min. No error reported by Google Console

2. When I go to Video again, change a small thing like a character in "notes", and re-save, then the stats updates
    again.

3. Looking at the code, there are two pathways.... one where info is entered and save ( manually). This seems
    to work. Then there is code that gets executed by a hook (30 min). seems the problem is there.

### Module

other

### Version

ERPNext: v13.49.6 (version-13)

Frappe Framework: v13.51.2 (version-13)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
No error generated
```

**Comment by Nihantra-Patel** [comment]
We no longer provide support for version 13 or older. 

Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!
