### ISSUE TITLE
CoA Importer: Could not find Currency: Balance Sheet

### ISSUE THREAD

**Issue by nissekalle0** [frappe/erpnext#35253]
### Information about bug

The Currency column is empty = no text at all but in the Report Type field there is occasions of Balance Sheet
This error does not come up in the Data Importer.

Seem to be a mix of fields?!?!

### Module

accounts

### Version

Latest 14.xx

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
none
```

**Comment by Nihantra-Patel** [comment]
Please try to import on the stable version 14 or 15.

Thank You!
