### ISSUE TITLE
Hero Slider content align option is not present at slide 3 and so forth

### ISSUE THREAD

**Issue by firmans22** [frappe/erpnext#35272]
### Information about bug

I can't select content align option at Hero Slider template, because the option is not present from slide 3 etc
![image](https://github.com/frappe/erpnext/assets/120091488/1d073012-8124-40a5-a6a8-d2707abe7805)
![image](https://github.com/frappe/erpnext/assets/120091488/c04938d0-f406-4f78-a0fa-812b9e634116)

### Module

other

### Version

ERPNext: v14.23.1 (version-14)
Frappe Framework: v14.35.0 (version-14)
Frappe HR: v14.3.0 (version-14)
Payments: v0.0.1 (develop)

### Installation method

manual install

**Comment by s-aga-r** [comment]
@firmans22 Which DocType is this?
