### ISSUE TITLE
Permission Error in Customer Role

### ISSUE THREAD

**Issue by keymealll** [frappe/erpnext#35277]
### Information about bug

I found a bug which is weird.

When I set the "Default Role at Time of Signup" as a "Customer", and user from the sign up created as a "Customer" role, it cannot save the address while checkout and cannot access the sales order due to a permission error here:

![image](https://github.com/frappe/erpnext/assets/75361771/4a173996-e451-4683-a188-7e33dc0bda9d)
![image](https://github.com/frappe/erpnext/assets/75361771/78ee9f36-94b3-4a9a-8498-7883ce9da06c)

After that, I tried to change the "Default Role at Time of Signup" to a "Non-Profit Portal User" role and tried to create a user from Sign Up for the first time. Then I change this user role manually  into the "Customer" Role from the Administrator, and it works:

![image](https://github.com/frappe/erpnext/assets/75361771/d99cc89f-dad1-4bc0-bce2-2b1ba1cbff1f)

I hope that the "Customer" Role after the set-up in the "Default Role at Time of Signup" bug can be fixed as soon as possible, thank you

### Module

selling, other

### Version

ERPNext: v13.50.1 (version-13)
Frappe Framework: v13.56.1 (version-13)
Python: 3.8

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
Hi @keymealll,

**We no longer provide support for version 13 or older.** 

Everything is working fine. No problems were encountered in the latest versions 14 and 15.


https://github.com/frappe/erpnext/assets/141945075/2ca4c307-7442-490f-a12f-64a8728ce927


Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!
