### ISSUE TITLE
Price Rule changing rate and not price list rate when mixed conditions is checked

### ISSUE THREAD

**Issue by SergioA76** [frappe/erpnext#35280]
### Information about bug

Use Case
If we create a pricing rule for Price based price using the below conditions -

Apply On = Item
Mixed Condition =1
Price  = Price
Party Information>> Selling =1
Min Amt =15
Price Discount Scheme>> Rate 

Actual result:

When price ruled is applied, it will change rate and not price list rate which calculates a discount. When you save document, Price Rule will update Price List Rate but leave discount in line which results in lower price than expected.

Expected result:
If mixed conditions = 0 Erpnext works as expected, When price rule is applied it updates Price List Rate and therefore no discount is calculated. So same should happen when Mixed Condition=1

When Item is selected
![image](https://github.com/frappe/erpnext/assets/129229420/553fa812-82b3-4c80-90b2-08efb3458e8d)
Once Price Rule is applied
![image](https://github.com/frappe/erpnext/assets/129229420/f9d2bea3-af6a-4df6-85ba-6a83e0964182)
Once document is saved
![image](https://github.com/frappe/erpnext/assets/129229420/43166c41-64c6-4cc0-8041-051a47854dab)

### Module

selling

### Version

ERPNext: v14.20.1 (version-14)
Frappe Framework: v14.30.0 (version-14)

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
Hi @SergioA76,

Kindly upgrade to version 14 or 15, then refresh and check again.

Everything is working fine. No problems were encountered in the latest versions 14 and 15.


https://github.com/frappe/erpnext/assets/141945075/ac82b5c0-5e8e-412a-84fe-74771cca8a04

Thank You!
