### ISSUE TITLE
Item Merge Queue Issue

### ISSUE THREAD

**Issue by sowndharya998** [frappe/erpnext#35287]
### Information about bug

When we tried to merged with the old items to new items and the pop-up has to be appear as "the document renaming from ### to ### has been queued". but didn't merged with old items. 
![2](https://github.com/frappe/erpnext/assets/75109236/afa0a70e-1b36-4261-bbe2-07353fd7f391)
![1](https://github.com/frappe/erpnext/assets/75109236/aeb3741f-d73d-43b9-8758-352e49fde422)

### Module

stock

### Version

ERPNext: v14.24.1 (version-14)

Frappe Framework: v14.36.0 (version-14)

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
Kindly upgrade to version 14 or 15, then refresh and check again because lots of bugs fixed in the new version.

Everything is working fine. No problems were encountered in the latest versions 14 and 15.
