### ISSUE TITLE
website image

### ISSUE THREAD

**Issue by Suprazz** [frappe/erpnext#3528]
if there is a space in the image in the website section of an item, the image preview in the public is blank

**Comment by rmehta** [comment]
what do you mean by "space". can you give an example?

**Comment by Suprazz** [comment]
"image 1.jpeg" will show a blank preview on the website product page. But when you click on the product to see the description, the image load correctly.

If you put "image1.jpeg", the preview will be ok on the website.

**Comment by PawanMeh** [comment]
Kindly post screen shots of the issue you are facing with clear steps for replication. Please try on latest version. Closing this for now.
