### ISSUE TITLE
BOM creator automatically comes with a filter for the Item we are trying to manufacture in raw material

### ISSUE THREAD

**Issue by dakpek** [frappe/erpnext#35292]
### Information about bug

<img width="1327" alt="Error" src="https://github.com/frappe/erpnext/assets/23242515/f0809596-1a25-408c-9b70-cad65fd2f08b">

### Module

manufacturing

### Version

Frappe Version - 14
ERP Version - latest

### Installation method

None

**Comment by s-aga-r** [comment]
fixed in https://github.com/frappe/erpnext/pull/35269
