### ISSUE TITLE
Can’t make a transaction above 1 trillion (13 digit)

### ISSUE THREAD

**Issue by farrasiqtsm1** [frappe/erpnext#35302]
### Information about bug

There’s error cant save JE when input a transaction above or total Rp.1.000.000.000.000 (13 Digit)

pymysql.err.DataError: (1264, “Out of range value for column ‘total_debit’ at row 1”)

![image](https://github.com/frappe/erpnext/assets/132031952/4912cf20-c05f-4922-b5df-fe37197f228f)

### Module

accounts

### Version

Frappe Version : v12.28.2 (version-12)
ERP next Version : v12.31.0 (version-12) 

actually already test this in V14 is error to 
ERPnext version : v14.23.1 (version-14) 

![image](https://github.com/frappe/erpnext/assets/132031952/47279463-2092-40ad-88d9-b02149d46065)

### Installation method

None

**Comment by Nihantra-Patel** [comment]
Hi @farrasiqtsm1,

**We no longer provide support for version 13 or older** but for version 14, To resolve this issue, you'll need to break down the transaction into smaller amounts and input them as separate rows. Each entry should contain an amount ranging from 9 to 10 digits to ensure compatibility and prevent the "Out of range value" error from occurring.

Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!
