### ISSUE TITLE
Validation if selling price is below its purchase/valuation rate

### ISSUE THREAD

**Issue by jof2jc** [frappe/erpnext#3532]
[Suggestion] Put an option in selling settings whether must validate if selling price of an item on DO/Invoice is below its valuation rate.

https://discuss.frappe.io/t/validation-if-selling-price-is-under-purchase-valuation-rate/6446

**Comment by jof2jc** [comment]
Any update for this issue?

**Comment by rmehta** [comment]
https://erpnext.com/pricing/paid-feature-development ? Estimate 1hr
