### ISSUE TITLE
Auto insert new pricelist on DO/Sales Invoice

### ISSUE THREAD

**Issue by jof2jc** [frappe/erpnext#3533]
[Feature request]
If an item doesn't has a pricelist rate on selected price list on DO/Sales Invoice then it will automatically insert new price list rate for that item if user fill up Price List Rate field.

https://discuss.frappe.io/t/price-list-creation-on-transaction/6445

**Comment by jof2jc** [comment]
This will save a lot of time to enter price list for all items before making any transactions

**Comment by sbkolate** [comment]
(+1)

**Comment by rmehta** [comment]
@jof2jc its a good suggestion. @sbkolate fix it!

Adding to watchlist

**Comment by sbkolate** [comment]
@jof2jc @rmehta Price List Rate field is read only in DO/Sales Invoice.. We can update `price list rate` if Price List Rate is zero.
Also, we can add check box for update price in Item table, and give permission only to manager to update price list rate.

**Comment by rmehta** [comment]
I think if Price List is set and Price List Rate is set, just add it. Add a message saying that this was added, if the user does not want, they can remove.

**Comment by rmehta** [comment]
Lets not add a new checkbox for this.

**Comment by jof2jc** [comment]
While user is on DO/Sales Invoice and the item doesn't has price list rate yet, then system will automatically insert new price list rate for that item (if price-list rate is not zero)

**Comment by AliKhafaji** [comment]
Hello Everyone!

I am moving from Odoo to ERPNext, and i have a question about customizing ERPNext.

Can we customize the pricelist?

in a way that pricelist will automatically be created for that customer when changing the product price on the quotation or invoice, For it to be done only 1 time then the product fix price will be set for that customer for feature sales?
