### ISSUE TITLE
Posting error

### ISSUE THREAD

**Issue by AalokRathore** [frappe/erpnext#35342]
### Information about bug

hi , Please let me know how to resolve this ? 

![image](https://github.com/frappe/erpnext/assets/133873457/9cbe19d8-af9c-4609-b33c-3f743cb66770)

### Module

stock

### Version

NA

### Installation method

easy-install

### Relevant log output / Stack trace / Full Error Message.

```shell
NA
```

**Comment by deepeshgarg007** [comment]
@AalokRathore Please add more info for us to replicate and then reopen the issue
