### ISSUE TITLE
Credit/Debit Note should be available for Reconciilation by default

### ISSUE THREAD

**Issue by ruthra-kumar** [frappe/erpnext#35343]
When a Credit/Debit note is created from a parent invoice, it is directly linked to it and cannot be unlinked. This means if there are Payment Entries or Journals agianst that same invoice, Cr/Dr note cannot be used for clearing future invoice from same customer.

Expectation: 
Cr/Dr notes should be available for reconciliation even if it has a parent. To achieve this Cr/Dr Notes will post Ledger entries against itself.

**Comment by barredterra** [comment]
@ruthra-kumar is there anything we can do to resolve this issue in v14 as well?

**Comment by barredterra** [comment]
Related: https://github.com/frappe/erpnext/issues/36170
