### ISSUE TITLE
Purchase Order Notification does not update automatically

### ISSUE THREAD

**Issue by justinlusg** [frappe/erpnext#3534]
![image](https://cloud.githubusercontent.com/assets/12539216/8426690/62208efe-1f44-11e5-9cb5-8e14b8dff031.png)

![image](https://cloud.githubusercontent.com/assets/12539216/8426695/66b016ce-1f44-11e5-8f99-429f01e92ac4.png)

The notifications of the Purchase Order does not update automatically after new PO has been created/completed. As seen in the screenshot above, the Purchase Orders are closed/completed but the notification number does not update on its own.

**Comment by rmehta** [comment]
updates with the next notification refresh.
