### ISSUE TITLE
Recurring ToDo

### ISSUE THREAD

**Issue by adityaduggal** [frappe/erpnext#3535]
It would be great if we could get a recurring ToDo option.

**Comment by rmehta** [comment]
there is a recurring event, use that?

**Comment by adityaduggal** [comment]
events and todo are different and hence needed the todo...tried to do it at my end but I am not skilled enough to change things in frappe/frappe.

**Comment by mbauskar** [comment]
@adityaduggal,

Just add the Custom Field in ToDo and keep the Custom Field name as subscription then user will be able to create the Subscription against the ToDo
