### ISSUE TITLE
Payment Entry Unallocated Amount not calculated until after Save

### ISSUE THREAD

**Issue by Jammyinc** [frappe/erpnext#35350]
### Information about bug

On Payment Entry prior ERPNext versions (v12 for example) calculated the Unallocated Amount before Saving a transaction. Version 14 Payment Entry the Unallocated Amount does not calculate until after Save. This forces manual calculation of unallocated amount in order to apply that remaining portion of funds to the transaction OR performing another transaction to allocate additional funds, after the transaction is saved.

The Unallocated Amount should continuously update before Saving the transaction so we don't have to use a calculator. The Allocated Amount updates on the fly - so should the Unallocated Amount. My team hopes this bug can be attended to soon. I think it should be an easy fix.

![Screenshot_Payment-Entry-Bug](https://github.com/frappe/erpnext/assets/15970725/0c72cd81-ea1b-4013-a763-04aab564aadb)

### Module

accounts

### Version

Frappe Framework: v14.34.0 (version-14)
ERPNext: v14.23.0 (version-14)

### Installation method

manual install

**Comment by ashish-greycube** [comment]
@Jammyinc  It is fixed by us. https://github.com/frappe/erpnext/pull/35239

**Comment by Jammyinc** [comment]
Wow! Thanks! Glad it was easy.

Ralph 


-------- Original Message --------
