### ISSUE TITLE
Rename Template does not rename - update the variants

### ISSUE THREAD

**Issue by zzecool** [frappe/erpnext#35358]
### Information about bug

Renaming a Template product does not rename - update the variants

![image](https://github.com/frappe/erpnext/assets/2816897/9f2c515d-4fab-4eae-b91c-30c3f6cd29ac)

### Module

stock

### Version

Ecommerce Integrations: v1.15.4 (HEAD)

ERPNext: v14.24.2 (HEAD)

Frappe Framework: v14.36.1 (HEAD)

### Installation method

FrappeCloud

**Comment by s-aga-r** [comment]
@zzecool This works fine for me could you provide more details about the issue like traceback?

![Peek 2023-05-22 17-47](https://github.com/frappe/erpnext/assets/63660334/07dd4298-c3a2-4528-b6c0-06831b1217d3)

**Comment by zzecool** [comment]
@s-aga-r  i didnt say i cant rename the Template.

I said that it doesnt rename the variants of the Template based on the new Template name.

Thanks in advance.

**Comment by s-aga-r** [comment]
@zzecool There can be n number of variants of a template, and renaming all of them can cause a timeout. Better to use a custom server script here for the `after_rename` event.

**Comment by zzecool** [comment]
> @zzecool There can be n number of variants of a template, and renaming all of them can cause a timeout. Better to use a custom server script here for the `after_rename` event.

And how is this possible in the Cloud Instance?

No matter the number of variants this should be scheduled accordingly

**Comment by s-aga-r** [comment]
@zzecool 

> And how is this possible in the Cloud Instance?

Custom Apps and Scripts can be added in any Frappe Instance. 

> No matter the number of variants this should be scheduled accordingly

Renaming Documents is an expensive operation. Check [this](https://github.com/frappe/frappe/blob/develop/frappe/model/rename_doc.py#L121-L234) function: 
- Renaming has several get_doc calls [example1](https://github.com/frappe/frappe/blob/a7171918ee5f764df0a1ebb28340771857ead563/frappe/model/rename_doc.py#L163), [example2](https://github.com/frappe/frappe/blob/a7171918ee5f764df0a1ebb28340771857ead563/frappe/model/rename_doc.py#L202). 
- All the child docs need to update i.e., the parent field in all the linked Child Tables.
![image](https://github.com/frappe/erpnext/assets/63660334/af72c3aa-a53e-4b9a-bc60-09901a74e533)
- Link Fields, Attachments, Versions, and Energy Points also need to be updated.
- Dynamic Links need to be renamed.

We have customers with over 5L Variants for an Item. So, scheduling also not going to work here.
