### ISSUE TITLE
Raw Materials missing on Job Card generated from Work Order

### ISSUE THREAD

**Issue by ghost** [frappe/erpnext#35366]
### Information about bug

![image](https://github.com/frappe/erpnext/assets/132303314/45d9b1c5-f951-48a2-9dd5-dc2b6818180f)

I generate work order from BOM, then I generate job cards from work order. For some reason, when I make new job card manually, raw materials show. When job card is created from script, raw materials is not there. Can someone help me understand this issue a little better? 

Why is this happening? User is admin. 

### Module

manufacturing

### Version

Frappe: 14.0.1
ERPNext: 14.24.3

### Installation method

manual install

**Comment by s-aga-r** [comment]
@ClassicCookie The Raw Materials (Job Card Items) are used when the Work Order **Transfer Material Against** is set to **Job Card** to maintain the items **Transferred Qty**. This [method](https://github.com/frappe/erpnext/blob/9308cd9b5738da9c108026bec02c39468539ca2a/erpnext/manufacturing/doctype/job_card/job_card.py#L422-L452) is used to get the Required Items from Work Order.

![image](https://github.com/frappe/erpnext/assets/63660334/af9f6f00-e0ff-41e4-bdc6-7d2ac9261cb3)

![image](https://github.com/frappe/erpnext/assets/63660334/6378b10c-a181-455c-98fb-a4d9e57c5334)
