### ISSUE TITLE
Delivery Note Status Change Problem

### ISSUE THREAD

**Issue by JasonFu06** [frappe/erpnext#35370]
### Information about bug

For an sales order with a unit price of zero, if it is shipped in batches, the first delivery note is submitted and an invoice is generated, and the status is completed. When the same sales order is outbound and submitted again, the status of the delivery note related to this sales  order is completed, and the system Automatically changed to bill, per_billed = 0.

### Module

stock, selling

### Version

Frappe : V13, V14 all branch
Erpnext : V13, V14 all branch

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
Hi @JasonFu06,

Could you share a video demonstrating the problem you're experiencing? The status feature seems to be functioning correctly in the latest versions 14 and 15.

We no longer provide support for version 13 or older. 

Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!
