### ISSUE TITLE
Purchase Receipt Status Change Problem

### ISSUE THREAD

**Issue by JasonFu06** [frappe/erpnext#35371]
### Information about bug

For a purchase order with a unit price of zero, if the goods are received in batches, the first purchase receipt is submitted to the warehouse and a purchase invoice is generated, and the purchase receipt  status is still To Bill. When the same purchase order is receipted again and submitted to the warehouse, it is related to this purchase order After completing the purchase receipt status, the system automatically changes it to To Bill, per_billed = 0.

### Module

stock, buying

### Version

Frappe : V13, V14 all branch
Erpnext V13, V14 all branch

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
Hi @JasonFu06,

Could you share a video demonstrating the problem you're experiencing? The status feature seems to be functioning correctly in the latest versions 14 and 15.

We no longer provide support for version 13 or older. 

Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!
