### ISSUE TITLE
Request: Website User seeing default print format

### ISSUE THREAD

**Issue by justinlusg** [frappe/erpnext#3539]
Website users are seeing the default print format and not the customised one. 

It would be good if there is a feature that allows us to decide which default print format Website Users would see when they click.

![image](https://cloud.githubusercontent.com/assets/12539216/8437878/ab781d6a-1f94-11e5-9dcb-b687872f8ddc.png)

**Comment by rmehta** [comment]
Do you want a print format per document or a global print format default for the web.

If its the latter, then why is this different from the default print format?

**Comment by justinlusg** [comment]
hi @rmehta, the issue is the web users will only see the "Standard" print format that default comes in ERPNext. I am unable to select the Web Users to see our customized print format.

**Comment by justinlusg** [comment]
Not sure if we are still discussing on this? Currently we are unable to display our own print format (e.g. one with out letterhead and customised formatting) when users login as a web user. 

For example, web users are linked to http://erpdemo.agtech.com.sg/orders/SO-00001 while System Users are linked to http://erpdemo.agtech.com.sg/desk#Form/Sales%20Order/SO-00001. 

Both display different format.
