### ISSUE TITLE
Purchase Receipt & Date column showing Blank in GST Itemised Purchase Register

### ISSUE THREAD

**Issue by asoral** [frappe/erpnext#35395]
### Information about bug

Purchase Receipt & Date column showing Blank in GST Itemised Purchase Register
![pr rcpt   date](https://github.com/frappe/erpnext/assets/11851156/196a0cde-aba5-445b-ba6b-9a84eff667c8)

### Module

regional

### Version
In version-13
v13.36.2 (version-13)
v13.36.0
in version-14
v14.36.0 (version-14)
v14.24.1 (version-14)

### Installation method

None

**Comment by deepeshgarg007** [comment]
@asoral This issue should be resolved now, please update and check. Closing this issue
