### ISSUE TITLE
Filtering using parent group (Item/Customer)

### ISSUE THREAD

**Issue by NEW-MTC-ERP1** [frappe/erpnext#35412]
When opening list/report view of item list, and trying to filter it by a parent item group, list will show only items that are assigned to that particular parent item group, and will ignore items that are linked to any child group to the same item group.

Solving this issue is being reported by most of users of ERPNext.

Same issue applies to customer filtering through customer group tree.
Thanks

**Comment by ankush** [comment]
https://github.com/frappe/frappe/pull/21156
