### ISSUE TITLE
Suggestion: Standardize naming for system and website users

### ISSUE THREAD

**Issue by justinlusg** [frappe/erpnext#3541]
![image](https://cloud.githubusercontent.com/assets/12539216/8438551/2d607436-1f99-11e5-9515-6600909a7525.png)

System = Postal Code
Website = Pincode

System = Email
Website = Email Id

**Comment by rmehta** [comment]
@justinlusg these are pretty simple. Can you send a pull request for these

**Comment by neilLasrado** [comment]
@justinlusg what do you mean by System ? The Naming is consistent with the Address form in ERPNext System.
![screen shot 2015-07-09 at 5 03 44 pm 1](https://cloud.githubusercontent.com/assets/8401344/8594239/bede7e34-265c-11e5-9403-507d89dae22c.png)

**Comment by justinlusg** [comment]
![image](https://cloud.githubusercontent.com/assets/12539216/8597599/10d20a2c-2689-11e5-949e-5deb07d19441.png)

Mine is different @neilLasrado

**Comment by rmehta** [comment]
@justinlusg maybe you customized it.

**Comment by justinlusg** [comment]
Is there a way to change the one that is at the web user to postal code instead of pincode?

**Comment by neilLasrado** [comment]
@justinlusg you can ... just go to website module and under web form select the address form & change the label.

**Comment by justinlusg** [comment]
oh got it! Thanks!
