### ISSUE TITLE
Hi, 

### ISSUE THREAD

**Issue by tsaqiif** [frappe/erpnext#35428]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tsaqiif** [comment]
in restaurant, currently we only able to put 1 order at a time...we need more than that and please provide Outstanding Order List.
Many Thanks in advance

**Comment by ankush** [comment]
You can use POS or restaurant POS app from marketplace. Sales Orders are not designed for restaurant-type workflow.
