### ISSUE TITLE
Ship Dates on Company Calendar

### ISSUE THREAD

**Issue by sellisjr** [frappe/erpnext#3542]
It would be a great asset to be able to see ship dates of sales orders on the company-wide calendar for all users to see.  For example, users could view the calendar for the current week to assess all orders planned to ship.  Would this be something that could be implemented soon?

Thanks,

Steve

**Comment by rmehta** [comment]
Yeah should be easy.

- [ ] Add calendar to Sales Order

@sellisjr Will you be willing to sponsor 1hr? We will do it anyways.

**Comment by sellisjr** [comment]
Hello Rushabh,

 

I thank you for your response and appreciate you accommodating my request to add ship dates to the company calendar.  At the current time, I have not been granted a budget on our ERP project.  

 

Our company manufactures and distributes fire suppression and detection equipment in the marine industry (www.sea-fire.com).   We are located in Baltimore, MD USA.  Typically our annual sales average about $7 million USD.  We have found your ERPNext system to be of great interest and have been exploring the system features and capabilities.  So far, we really like what we see.
  Because our factory operates at such a fast pace and the equipment we manufacture has the ability to save lives, inventory control and QA procedures are two areas of great concern for us.  Your system seems to incorporate both
 aspects quite nicely.

 

In the coming months we will be deciding whether to host through your company, or host ERPNext on our own server. I noticed that hosting through your company, the largest storage available is 50GB.  Our company’s current data file is at 70MB so I am not sure if you offer anything larger to accommodate such size.  We would of course purchase a support contract, regardless of whether we decide to host ourselves, or with you.

 

Any advice you could offer would be greatly appreciated.

 

Best Regards,

 

Steve Ellis, Jr.

Sea-Fire / Metalcraft

410-687-5500 Ext. 101

 

Description: PageHead

Tell us how we are doing!  Please take a few moments to fill out our Customer Survey <http://www.sea-fire.com/survey/> .

**Comment by rmehta** [comment]
@sellisjr thanks!  Did you say **70MB**? Our highest plan has **50GB** (thats a lot of space!)

If you want to take this discussion offline, please email us at sales@erpnext.com. We can also help you with a 30 min online consultation to get you started.

**Comment by sellisjr** [comment]
@rmehta Hello.  Is there any update on this feature?  Thank you very much.

**Comment by rmehta** [comment]
We will try for this week. Any chance of sponsorship will make it faster :)
