### ISSUE TITLE
Inventory Valuation Issue in warehouse to warehouse material transfer

### ISSUE THREAD

**Issue by RJMHASKE** [frappe/erpnext#35423]
### Information about bug

Inventory Valuation Issue in warehouse to warehouse material transfer

We have created material transfer stock entry from one warehouse to other transit warehouse.
Item valuation and basic rate fetch 15/-, Amt-150/-

<img width="864" alt="image" src="https://github.com/frappe/erpnext/assets/119041865/26b824f6-ad13-47c5-8e46-b005c8810931">

We Create Material In from Transit warehouse, Item Valuation and basic rate changed 15/- to 24.98/-, Amt-249.82/-
Inventory valuation difference amt- 99.82/-

<img width="865" alt="image" src="https://github.com/frappe/erpnext/assets/119041865/91eb8d2b-24ba-4980-b4db-5e1851e265d3">
<img width="879" alt="image" src="https://github.com/frappe/erpnext/assets/119041865/e641948e-9f1d-4564-b437-2ab51a10c600">

How system change valuation rate of Item in only changing location one warehouse to other warehouse without adding any cost???

This is major issue in Inventory valuation

### Module

accounts, stock

### Version

ERPNext: v13.46.1 (HEAD)
Frappe Framework: v13.49.2 (HEAD)

### Installation method

FrappeCloud

**Comment by rohitwaghchaure** [comment]
@RJMHASKE What's the valuation method you have set the in the stock settings ? if the valuation method is FIFO then system will pickup the valuation rate of older inventory irrespective of the previous Material Transfer Entry (From Warehouse to In Transit Warehouse)

For example:

You have purchase item ABC with quantity 1 for rate 10 in **warehouse A** and then you created material transfer entry from **warehouse A** to **GIT Warehouse**

At the same time you have purchase item ABC with quantity 1 for rate 20 in **warehouse A** and then you created material transfer entry from **warehouse A** to **GIT Warehouse**.

Now In GIT warehouse there are 2 quantity of same items are exists with different rates.

If you create the Material In entry against the second stock entry(having valuation 20) then system will pick the rate as 10 based on FIFO method.

**Comment by RJMHASKE** [comment]
Hello Rohit,

This issue is not completed, please see below clarifications

1. we set FIFO method and using Batch management for all Inventory Item
2. we are upload opening stock with valuation rate- 15/- Batch code- 1BE74EE in warehouse- Gevari Bazar RM
<img width="814" alt="image" src="https://github.com/frappe/erpnext/assets/119041865/56853c3d-bfb9-4356-ad6f-675e36a6a991">

3. Same Item with Batch code transfer to Transit warehouse
<img width="848" alt="image" src="https://github.com/frappe/erpnext/assets/119041865/fc536a40-6e32-4c7d-9502-61193569070c">

4. when do Material In from Transit to Inward warehouse with same Batch code , how system change valuation rate??
<img width="790" alt="image" src="https://github.com/frappe/erpnext/assets/119041865/00e32d35-3ad7-44b0-bcf5-8875f1002732">
<img width="671" alt="image" src="https://github.com/frappe/erpnext/assets/119041865/b90ce012-1e46-46d5-9cb8-dcfedc9bde29">

**In FIFO method when one Item code transfer with same batchcode one warehouse to other warehouse valuation rate change??**

Stock ledger for reference
<img width="883" alt="image" src="https://github.com/frappe/erpnext/assets/119041865/0205dc44-fa9b-4083-b513-562fb2543703">
