### ISSUE TITLE
I cannot see "Finish" button on work order when i completed a stock entry newly controlled by a workflow against stock entry

### ISSUE THREAD

**Issue by Xuquansheng** [frappe/erpnext#35434]
### Information about bug

![图片](https://github.com/frappe/erpnext/assets/82086188/39c15157-030e-4ad8-992d-a391be814d15)

i have to click "Reload" to get "Finish" button which is correct. 

![图片](https://github.com/frappe/erpnext/assets/82086188/43152ecb-69d2-40f6-8506-332daeec0186)

### Module

manufacturing

### Version

ERPNext 13, 14

### Installation method

docker

**Comment by rohitwaghchaure** [comment]
@Xuquansheng I have tested on a site which is hosted on [frappecloud](https://frappecloud.com/) and it's working properly.

![work-order-issue](https://github.com/frappe/erpnext/assets/8780500/fc8619de-4fab-4e6b-bd4c-c0d933cba688)

**Comment by Xuquansheng** [comment]
You haven't run a workflow against stock entry, so you can get "Finish" button which is correct. below is my workfow
![图片](https://github.com/frappe/erpnext/assets/82086188/ec6dcb75-1d58-46dc-80df-2e0c43a526f2)
![图片](https://github.com/frappe/erpnext/assets/82086188/c41c7642-e583-4596-83e8-7ff07addab4b)
after workflow, i cannot see the "Finish" button
![图片](https://github.com/frappe/erpnext/assets/82086188/925c8491-aff6-4e2c-a5be-5ed763eba930)

**Comment by Xuquansheng** [comment]
I can’t reopen this issue，so I added some comments on the ticket. please see the comments.





来自钉钉专属商务邮箱------------------------------------------------------------------
***@***.***>
日　期：2023年05月30日 19:44:42
***@***.***>
***@***.***>; ***@***.***>
主　题：Re: [frappe/erpnext] I cannot see "Finish" button on work order when i completed a stock entry newly controlled by a workflow against stock entry (Issue #35434)

@Xuquansheng I have tested on a site which is hosted on frappecloud and it's working properly.
