### ISSUE TITLE
Linkedin Setting Error

### ISSUE THREAD

**Issue by KBP-Civil** [frappe/erpnext#35449]
### Information about bug

Hi,

Am using the below documentation and trying to make configuration and did how the documentation is guide as per.

[https://docs.erpnext.com/docs/v14/user/manual/en/CRM/linkedin-settings 3](https://docs.erpnext.com/docs/v14/user/manual/en/CRM/linkedin-settings)

But Am getting the error like is:
![image](https://github.com/frappe/erpnext/assets/119104949/b03f9c61-f97d-4fe7-9da8-41996b04ffa8)

 I have given the right company Id, Consumer Key, Consumer Secret which is there in the linked in app as it is. but after entering all and trying to save it’s get redirected and showing this error.

This is the link I have given in the LinkedIn in Authorized redirect URLs for your app https://{yoursite}/api/method/erpnext.crm.doctype.linkedin_settings.linkedin_settings.callback. I have followed the instruction as it’s in the documentation but unable to achieve this .

### Module

CRM

### Version

ERPNext: v13.50.5 (HEAD)
Frappe Framework: v13.56.3 (HEAD)

### Installation method

FrappeCloud

**Comment by Nihantra-Patel** [comment]
Hi @KBP-Civil,

We can't help with version 13 or older anymore. Managing the Linkedin integration is difficult, so this integration is deprecated and will be removed in v15.

Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!
