### ISSUE TITLE
v14 Bank Reconciliation - does not clear all when reconciling multiple vouchers with a single Bank Transaction in a single step

### ISSUE THREAD

**Issue by casesolved-co-uk** [frappe/erpnext#35440]
### Information about bug

When there are multiple vouchers offered to match a single Bank Transaction, and the sum of the vouchers will clear the Bank Transaction, not all (and it appears only one) voucher is marked cleared, yet both are added to and reconciled against the Bank Transaction.

![Screen Shot 2023-05-27 at 15 47 52](https://github.com/frappe/erpnext/assets/110036763/c9f2cbb8-c809-4505-8910-4eb1f4ad8b09)

All vouchers need to be cleared.

Workaround: Reconcile each voucher against the Bank Transaction separately.

### Module

accounts

### Version

ERPNext >= v14.19

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

Introduced: #34476

**Comment by Nihantra-Patel** [comment]
Right now, we've closed it because it doesn't make sense. If there's a solution that applies (like the one Raffael Meyer mentioned in the PR and others), then we'll reopen the pull request with the new issue with newer versions develop or 15.

**Comment by casesolved-co-uk** [comment]
I gave you a bug fix, you've refused it, nothing more I can do.
