### ISSUE TITLE
lead time in the work order can't be change

### ISSUE THREAD

**Issue by hyx0908** [frappe/erpnext#35442]
### Information about bug

Hello,
   i wonder that is there  a way change the lead time, why it is always zero? is it design that way or i did not know where to change it?

### Module

manufacturing

### Version

ERPNext: v14.22.2 (version-14)

Frappe Framework: v14.33.1 (version-14)

### Installation method

manual install

**Comment by hyx0908** [comment]
i take the lead time is the time between orders

**Comment by hyx0908** [comment]
Hello,
    on a second thought, the lead time should based on job cards right?  for instance, after finished 10 pieces of iphones, than change to make 10 pieces of iwatchs, should reserve for every workstation to prepare, am i understanding it right, or the system already has the better way to do it.

**Comment by rohitwaghchaure** [comment]
@hyx0908 lead time calculations works based on the time required to complete the Job Cards of the respective work order.
For example 

To make 10 pieces of iphones required below operations.

1. Assembly
2. Polishing
3. Packing

If two machines used parallel to complete 10 pieces and it required one day to complete all 3 operations of all 10 pieces then complete lead time will be 1 day for 10 pieces.
