### ISSUE TITLE
Kanban by "status" includes internal status "Template"

### ISSUE THREAD

**Issue by moltar** [frappe/erpnext#35446]
### Information about bug

When creating a Kanban for "status", the resulting board contains a column for "Template".

![screenshot-20230528T175750-TDWG0zi8@2x](https://github.com/frappe/erpnext/assets/491247/113fbad9-01a4-489a-9f0f-a6b117d7fb13)

### Module

projects

### Version

ERPNext: v14.25.1
Frappe Framework: v14.36.3

### Installation method

docker

**Comment by Nihantra-Patel** [comment]
Hi @moltar,

It's a default system-provided status in Task, it's not an internal status or custom status. Please check the status list in the task.

<img width="1440" alt="image" src="https://github.com/frappe/erpnext/assets/141945075/a6a505ed-e622-42e2-92b9-34a870cad57d">

Thank You!
