### ISSUE TITLE
Payslip

### ISSUE THREAD

**Issue by mehulmehta** [frappe/erpnext#3545]
Can the payslip generation be modified from the current method of once a month to and open dated one wherein one can generate for any time frame based on the date. Also this should be allowed for any or all of the employees. For eg. in our organisation we have workers who are paid daily, weekly and monthly. We should be able to create the payslip as per the class of workers. Can this be done?

**Comment by rmehta** [comment]
- [ ] add dates in payslip / salary manager
- [ ] validate using dates
- [ ] re-do calculation
- [ ] testing

We are estimating 3 hrs, can you sponsor?

https://erpnext.com/pricing/paid-feature-development
