### ISSUE TITLE
[Urgent]Editing Option for Consumed Quantity in Subcontracting Receipt

### ISSUE THREAD

**Issue by Rajatha26** [frappe/erpnext#35452]
Hi Team,

There has been no provision to edit the consumed quantity of the items, during updating Subcontracting Receipt, before submitting in the V14 live instance.
The same steps are replicated in the V14 test instance for reference. 

Steps to replicate:
1. From the Sub contracting order, create the Sub contracting receipt.
2. In the subcontracting receipt screen, find the table by name Raw Materials Consumed.
3. In the table, find the column by name Consumed Qty.

Expectation:
1. The user has to edit the data in the column Consumed Qty (In the form view).

Observation:
1. The user cannot edit the data in the column Consumed Qty (In the form view).

I am attaching the links below for reference. 
https://v14-test-rcil.frappe.cloud/app/subcontracting-receipt/SCR%2FFY23%2FBK0001

Note: The feature of editing the Consumed Qty, in the Sub Contracting Receipt, was available in V13. I am attaching the V13 test instance link, for reference.
https://testrangsutra-rcil.frappe.cloud/app/purchase-receipt/PR%2FFY23%2FBK0001

We need this feature because of two reasons:
1. We make products from in-house center as well as job worker. But for this a common BOM is used. We issue all RM to in-house center as defined in BOM but some RM do not issue to job worker like sewing thread/overlock thread. So in this case while receiving material from job worker we have to remove(or set zero) sewing thread/overlock thread from consume qty as we have not issued it. And the cost of these RM is included in the job work rate.
2. We have to make BOM before start of production. But consumption may change during production, it is a normal process that in mass manufacturing, consumption may vary (+/-) around 2% (including waste/rejection). Hence the quantity consumed should be editable while subcontracting receive.  

Kindly check and revert.

Thanks and Regards,
Rajatha B
Functional Consultant
Promantia Business Solutions Pvt. Ltd.
Bangalore

**Comment by s-aga-r** [comment]
The **Consumed Qty** will be editable when the **Backflush Raw Materials of Subcontract Based On** is set to **Material Transferred for Subcontract** in **Buying Settings**.

![image](https://github.com/frappe/erpnext/assets/63660334/91289c1d-01fe-4be4-8666-e8a7471e8072)

ref: https://github.com/frappe/erpnext/pull/35337

**Comment by Rajatha26** [comment]
Hi Team,

Kindly find the points mentioned below:

If we use Backflush Raw Materials of Subcontract Based On >> ‘Material Transferred for Subcontract’ instead of ‘BOM’ than :

1. User shall have no control over issue of material to the supplier against the subcontracting order.
2. User will not know how much raw material we have to issue to complete this order and if we have already issued some material then how much more is yet to be issued.
3. If user will enter any quantity while issuing material then system will accept it and will not give any warning that you are issuing material more than required quantity etc.
4. Similarly, while receiving the goods the system will accept any quantity given by the user.
5. Hence, we will not get the correct cost of finished goods.

Hence the solution provided, cannot be applied.

So, kindly find all the above mentioned points and revert us with the solution.

Thanks and Regards,
Rajatha B
Functional Consultant
Promantia Business Solutions Private Limited
Bangalore
