### ISSUE TITLE
Sync Communication Status from Mandrill App

### ISSUE THREAD

**Issue by adityaduggal** [frappe/erpnext#3546]
Hi,

Currently we are using the Mandrill App to send all our emails from the erpnext system. The email just works fine its being sent from the erpnext system to Mandrill and then to the recipient but the only problem is that there is NO WAY to tell the following, whether the email was:

DELIVERED or BOUNCED or SOFT BOUNCED
Opened by the Recipient
Clicked by the Recipient
Now all these things are already there in Mandrill but every time we need to check if it was opened or not then we need to login to the mandrill app and check for the same.

I know its possible to fetch the same data from mandrill to the erpnext system via apis but I am not an expert on developing such apps and hence I would request some one to develop an app to fetch the data from mandrill

Please consider this as a PAID DEVELOPMENT.

I am not posting this as a PAID DEVELOPMENT since I think that the team is already pre-occupied with alot of things and I would need this thing quite soon.

If anyone is interested kindly post the price, obviously the ERPNext team is the first preference if they are willing to develop something like this.

**Comment by rmehta** [comment]
- [ ] write a scheduled event to get list of blacklisted addresses from mandrill via https://mandrillapp.com/api/docs/rejects.JSON.html
- [ ] add blacklist property in newsletter, contact, lead
- [ ] set as blacklisted / unsubscribed and then delete them from Mandrill list

- Estimate 2 hours. @adityaduggal what do you think?

**Comment by rmehta** [comment]
Or you are looking to sync message status (https://mandrill.zendesk.com/hc/en-us/articles/205583307-Message-Event-Webhook-format)

This might be a lot more expensive though. In the first cut, I would just track bounces / rejects.

**Comment by adityaduggal** [comment]
Honestly I am a very lazy and a greedy person and hence would love to see the full thing but still the rejects should be fine considering they can be delivered soon.

Btw do give me a quote for the full version as well so that we can contemplate on the full thing and in the mean time we could go for the rejects only.

Please go ahead and email me the quote so I could process the payment.

**Comment by robertbecht** [comment]
the rejects ldb be great

**Comment by rmehta** [comment]
@adityaduggal can we take this next week - want to complete collaborative PM this week.

**Comment by adityaduggal** [comment]
Sure do let me know the pricing, I am still waiting for that.

**Comment by rmehta** [comment]
2 hours = INR 10k?

**Comment by adityaduggal** [comment]
Wow...I should plan on changing my business.

Anyways please send me the invoice and I would do the NEFT/RTGS today only.

I hope this feature would tell us the following:

1. Communication was bounced or rejected.
2. Communication was Opened or Clicked (This is important as well)
3. Would it by default not send the communication next time to the same
email ID or not.

Please clarify the above things so that I can initiate the transfer.



On Thu, 16 Jul 2015 at 11:28 Rushabh Mehta <notifications@github.com> wrote:

> 2 hours = INR 10k?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/frappe/erpnext/issues/3546#issuecomment-121842217>.
>
-- 
Best Regards,

Aditya Duggal
E: adityaduggal@gmail.com
Web: www.rigpl.com

**Comment by rmehta** [comment]
We think it will take longer, but billing only a part of it :)

Will send you and invoice next week. Thanks!

**Comment by adityaduggal** [comment]
Transfer done.

**Comment by rmehta** [comment]
You know how to put pressure :). Will get it done this week.

**Comment by anandpdoshi** [comment]
Started work on it: https://github.com/frappe/mandrill_integration

**Comment by anandpdoshi** [comment]
Almost done. Just need to merge this pull request: https://github.com/frappe/frappe/pull/1219

**Comment by anandpdoshi** [comment]
This requirement is done. Thanks @adityaduggal for sponsoring the app!
