### ISSUE TITLE
Foreign Exchange transaction -unallocated amount - shows even when payment amount= invoice amount

### ISSUE THREAD

**Issue by bhavyajicomputers** [frappe/erpnext#35470]
### Information about bug

Invoice - Grand total and advance payment received  and allocated are 16870000 yen but invoice still shows a outstanding amount AMOUNT of 5,52,295.91 yen
![image](https://github.com/frappe/erpnext/assets/113116758/b9d0b27b-438f-4b50-9643-f9f55d69a955)
![image](https://github.com/frappe/erpnext/assets/113116758/00e36926-272f-4b40-80ba-9dcde8975fa8)

general ledger shows the invoice values as 17422295.91 yen

![image](https://github.com/frappe/erpnext/assets/113116758/c5f6066d-d0c3-4fa1-b46d-3062e2dbe193)
Payment entry
![image](https://github.com/frappe/erpnext/assets/113116758/d9481c71-35af-47bd-afb7-e77eadaa0ef5)

### Module

accounts, selling

### Version

Frappe Version 14.36.3
ERP Next Version 14.25.1

### Installation method

FrappeCloud

**Comment by Nihantra-Patel** [comment]
We checked in the latest version 14 so we haven't faced the issue.
If the issue occurs in the latest version then reopen it with the video documentation, if possible.
