### ISSUE TITLE
v14/v15 Invoice reset on date change removes discount

### ISSUE THREAD

**Issue by casesolved-co-uk** [frappe/erpnext#35485]
### Information about bug

There is a bug in transaction.js which overwrites the line rate with the price list rate when performing a refresh. The refresh can be triggered by changing the invoice date.

https://github.com/frappe/erpnext/blob/eb723637d3b9d6dbf9280d4269beb68ef9f4f95f/erpnext/public/js/controllers/transaction.js#L1511

Have tested a fix which changes `"rate"` to `key` which works but I'm not familiar with the code enough to say it is correct.

To reproduce:

- Create a draft invoice with a discount applied to a line item via a pricing rule
- Save
- Change the date of the invoice

Observed:
Line rate is reset to price list rate, discount is removed

Expected:
Line rate still should have pricing rule applied

version-14-hotfix

### Module

accounts

### Version

ERPNext - v14.23.0 & develop

### Installation method

None

**Comment by Nihantra-Patel** [comment]
Hi @casesolved-co-uk,

Everything is working fine. No problems were encountered in versions 14 and 15. Please check it.


https://github.com/frappe/erpnext/assets/141945075/36da457c-6b91-438a-8fd5-f550b6a582d7

Kindly upgrade to version 14 or 15, then refresh and check again.

Thank You!

**Comment by casesolved-co-uk** [comment]
The bug was reported on v15, as it states in the description

**Comment by Nihantra-Patel** [comment]
Please check it in the version 15


https://github.com/frappe/erpnext/assets/141945075/ed0db121-6fcf-48e2-b632-4a354f252b9f

Thank You!
