### ISSUE TITLE
Round Off Value Calculating Twice in Additional Discount

### ISSUE THREAD

**Issue by sjain17** [frappe/erpnext#35484]
### Information about bug

After additional discount the round-off is calculated twice in Sales Invoice. If a sales invoice has an additional discount and the amount of Taxes or Net Amount of the Item requires rounding then the rounding adjustment value is calculated twice.

### Module

accounts

### Version

ERPNext: v14.24.1 (version-14)
Frappe Framework: v14.36.0 (version-14)
Frappe HR: v1.0.0 (develop)
India Compliance: v14.6.2 (version-14)
Payments: v0.0.1 (develop)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
No error only calculation mistake.
```

**Comment by Nihantra-Patel** [comment]
Hi @sjain17,

Issue has been resolved #38171
