### ISSUE TITLE
Hello Rohit,

### ISSUE THREAD

**Issue by RJMHASKE** [frappe/erpnext#35496]
Hello Rohit,

Inventory valuation Issue Warehouse to Warehouse is not completed, please see below clarifications

1. we set FIFO method and using Batch management for all Inventory Item
2. we are upload opening stock with valuation rate- 15/- Batch code- 1BE74EE in warehouse- Gevari Bazar RM
<img width="814" alt="image" src="https://github.com/frappe/erpnext/assets/119041865/56853c3d-bfb9-4356-ad6f-675e36a6a991">

3. Same Item with Batch code transfer to Transit warehouse
<img width="848" alt="image" src="https://github.com/frappe/erpnext/assets/119041865/fc536a40-6e32-4c7d-9502-61193569070c">

4. when do Material In from Transit to Inward warehouse with same Batch code , how system change valuation rate??
<img width="790" alt="image" src="https://github.com/frappe/erpnext/assets/119041865/00e32d35-3ad7-44b0-bcf5-8875f1002732">
<img width="671" alt="image" src="https://github.com/frappe/erpnext/assets/119041865/b90ce012-1e46-46d5-9cb8-dcfedc9bde29">

**In FIFO method when one Item code transfer with same batchcode one warehouse to other warehouse valuation rate change??**

Stock ledger for reference
<img width="883" alt="image" src="https://github.com/frappe/erpnext/assets/119041865/0205dc44-fa9b-4083-b513-562fb2543703">

_Originally posted by @RJMHASKE in https://github.com/frappe/erpnext/issues/35423#issuecomment-1569509880_

**Comment by rohitwaghchaure** [comment]
@RJMHASKE Till version 13 valuation rate for the batch item calculate based on item and warehouse and not based on batch. We have added batchwise valuation in the version 14, you need to migrate your account to version 14 to fix this issue. After migrate to version 14 the batchwise valuation will work for the new batches and for the old batches the valuation will work as per old method only.
