### ISSUE TITLE
Item Not Showing in Quick Entry of Batch Creation from Batch No. Field in Purchase Receipt Item and Stock Entry Detail

### ISSUE THREAD

**Issue by sonali8848** [frappe/erpnext#35493]
### Information about bug

There is a bug in creating the batch through batch no. field in the purchase receipt item or stock entry detail. Sometimes, the filtered item does not populate in the new batch quick entry. However, when we reload the form and create the batch through batch no. field, the filtered item is auto-populated.
The screenshot before reload
![image](https://github.com/frappe/erpnext/assets/115159164/9c251045-019e-4b77-bf0f-bd8efbf6c421)
The screenshot after reload
![image](https://github.com/frappe/erpnext/assets/115159164/29d2ca2a-eb2e-4eb1-a384-1231f47f42f8)

### Module

stock

### Version

ERPNext version - v14.25.1

### Installation method

None

**Comment by FHenry** [comment]
Gi, 

this bug occurs since version 13, before it was only after a "go back" in browser, but now it's all the time

https://github.com/frappe/erpnext/assets/1050053/63de8af2-973b-4089-9cd0-a2419427b08a
