### ISSUE TITLE
Advance Payment Reconciliation Issue against Payment entry & Standalone JV

### ISSUE THREAD

**Issue by RJMHASKE** [frappe/erpnext#35516]
### Information about bug

Advance Payment Reconciliation Issue against Payment entry & Standalone JV

1.we have created sales order for customer 
<img width="882" alt="image" src="https://github.com/frappe/erpnext/assets/119041865/85c958ed-05dc-4a35-a223-cc6f2356a853">
2. create advance payment entry against SO and select Advance GL in entry for book advance payment in separate A/c 
<img width="776" alt="image" src="https://github.com/frappe/erpnext/assets/119041865/54387852-c431-451a-92dd-373fd77040ee">
3. create sales invoice against SO with party GL Debtors
<img width="795" alt="image" src="https://github.com/frappe/erpnext/assets/119041865/2d68f16c-0265-45a3-84f6-5d18de4ce798">

**while creating sales invoice system not shows advance amount entry or any msg**

4. we are create balance amount receive payment entry
<img width="794" alt="image" src="https://github.com/frappe/erpnext/assets/119041865/f00dce9d-6837-4edb-833f-5c64632a103a">

5. when we are doing payment reconciliation and selecting receivable a/c- Debtors which is selected in sales Invoice , so system not show advance payment entry for reconcile
<img width="800" alt="image" src="https://github.com/frappe/erpnext/assets/119041865/61ac6194-7f14-42fa-963f-5ed6a135cb20">

6. we are selecting Advance payment from party that time sales invoice not found
<img width="833" alt="image" src="https://github.com/frappe/erpnext/assets/119041865/bcaf49c5-2c8c-43ec-bb76-d6168cc207bb">
<img width="675" alt="image" src="https://github.com/frappe/erpnext/assets/119041865/4b18bf6a-9b4b-415e-8d4a-9e21273a230a">

7. then we are creating payment entry for same customer that time this invoice comes in outstanding invoice list with outstanding amount, we are add paid amount and system posted this payment entry.
<img width="714" alt="image" src="https://github.com/frappe/erpnext/assets/119041865/4313c734-1761-4d1c-aaeb-789872cf904f">
<img width="721" alt="image" src="https://github.com/frappe/erpnext/assets/119041865/ba482d6e-c1df-41af-8f0b-d77bf6e37e33">

So we can reconcile advance payment entry?? 

same issue with booking advance payment through JV

### Module

accounts

### Version

ERPNext: v14.25.1 (HEAD)
Frappe Framework: v14.36.3 (HEAD)
India Compliance: v14.7.0 (HEAD)
Payments: v0.0.1 (HEAD)

### Installation method

FrappeCloud

**Comment by deepeshgarg007** [comment]
@RJMHASKE Currently the flows are designed to work this way, doesn't look like a bug but a feature request.
Should be solved once https://github.com/frappe/erpnext/pull/35609 is merged. Closing this issue
