### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by VardaPanchal005** [frappe/erpnext#35524]
A dark mode and light mode button needs to be added
I want to work on this issue
@ankush

**Comment by ankush** [comment]
ctrl+shift+g or this menu


![image](https://github.com/frappe/erpnext/assets/9079960/6557b7ef-5f2d-4c8d-91cf-c301e358f037)

**Comment by VardaPanchal005** [comment]
I’m sorry for my ignorance
