### ISSUE TITLE
Suggestions on Subscription Doctype and Module

### ISSUE THREAD

**Issue by mayanknahata007** [frappe/erpnext#35533]
What is a subscription? 
When a company sells service to their clients, they would often go for a model where they invoice the client on a set frequency (days, months, quarters, years) and the payment happens accordingly.

The current subscription doctype can easily manage generation of invoices by setting up a frequency,
But, this at time is not very much practical.

1. For example, I want to invoice the customer on 18th May, so would I create the invoice on 18th May? 
Maybe or Maybe not.
The invoice could be created before so that it can be shared with the customers prior.

2. How to we set a stop to the subscription or increase the period of it?

3. No data can be shared from the Subscription doctype to the Sales Invoice (as there is no link).

4. Moreover, the current setup is chaotic/confusing when it comes to creating subscription from a Sales Order.
Instead of taking you to Subscription, it takes you to auto-repeat functionality. Weird?

**Comment by rmehta** [comment]
* Create subscription schedule (like asset depreciation) in Subscription - link invoice
* Invoice on Day X of the period

**Comment by ankush** [comment]
https://github.com/frappe/erpnext/pull/37126
