### ISSUE TITLE
SO - Pick List - Delivery all way wrong calculation 

### ISSUE THREAD

**Issue by dineshpanchal93** [frappe/erpnext#35547]
### Information about bug

1. SO - 10 Qty

<img width="1329" alt="Screenshot 2023-06-03 at 8 38 59 PM" src="https://github.com/frappe/erpnext/assets/21578167/92e4ac69-386a-4b26-a1ea-2031173b80f7">

2. Pick List - 5 Qty
<img width="1286" alt="Screenshot 2023-06-03 at 8 40 05 PM" src="https://github.com/frappe/erpnext/assets/21578167/414a290b-d379-4720-92c8-bf18795f5df2">

3. Delivery Note 3 Qty.

<img width="1335" alt="Screenshot 2023-06-03 at 8 41 00 PM" src="https://github.com/frappe/erpnext/assets/21578167/ab07602b-2d85-4024-8f82-e653e4f90051">

4. Picklist show as completed.

<img width="1284" alt="Screenshot 2023-06-03 at 8 41 53 PM" src="https://github.com/frappe/erpnext/assets/21578167/68f15dbf-64c8-4fc1-a438-4bb6557516f1">

Also, I can able to create the delivery note more than picked Qy.

Also, If I canceled the Delivery note  - Picklist is not opened again.

### Module

stock

### Version

Frappe Chat: v0.0.1 (main)

Employee GatePass: v0.0.1 (master)

ERPNext: v14.26.0 (version-14)

Frappe Framework: v14.37.0 (version-14)

### Installation method

manual install

**Comment by s-aga-r** [comment]
@dineshpanchal93 

>> Also, I can able to create the delivery note more than picked Qy.

The delivery qty depends on Over Delivery/Receipt Allowance (%) in Stock Settings.

>> Also, If I cancelled the Delivery note - Picklist is not opened again.

Only one Delivery Note can be created against a Pick List, once a Pick List gets completed it won't be re-open again on Delivery Note cancellation.
