### ISSUE TITLE
Quotation Print Overlap

### ISSUE THREAD

**Issue by ashcoft** [frappe/erpnext#35557]
### Information about bug

description overlap while using A4 paper and no problem with A3 paper
![image](https://github.com/frappe/erpnext/assets/1115854/94427cc3-dfaa-4d7d-be21-768c27f04974)

### Module

selling

### Version

Frappe version v14.37.0 (version-14)
ERPNext version v14.26.0 (version-14)

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
Hi @ashcoft,

Everything is working fine. No problems were encountered in the latest versions 14 and 15.

please check it.


https://github.com/frappe/erpnext/assets/141945075/cd6f1d3a-22ea-4ed0-aee7-872e8bf867ab

Thank You!
