### ISSUE TITLE
Please make some correction in pos.py file.i am getting error ,conversion factor is not none. and stock_um is not part of Item price.erpnext 14.24.2

### ISSUE THREAD

**Issue by erppardeep** [frappe/erpnext#35561]
### Information about bug

item_stock_qty, is_stock_item = get_stock_availability(item_code, warehouse)
item_stock_qty = item_stock_qty // item.get("conversion_factor")
item_stock_qty = item_stock_qty // item.get("conversion_factor", 1)
item.update({"actual_qty": item_stock_qty})

price = frappe.get_list(
	doctype="Item Price",
	filters={
		"price_list": price_list,
		"item_code": item_code,
	},
	fields=["uom", "stock_uom", "currency", "price_list_rate"],
)

### Module

selling

### Version
erpnext 14.24

**Comment by Nihantra-Patel** [comment]
Hi @erppardeep,

Everything is working fine and tested. No problems were encountered in versions 14 and 15.
If the issue occurs then reopen the issue then can you elaborate on the process and what you are facing with the issue? can you provide the video for a better understanding?

Thank You!
