### ISSUE TITLE
Expense Claim Account

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#3556]
Expense Claim Type should have field link to Account where user can select default Expense account for that Expense Claim Type.

On selection of Expense Claim Type in the Expense Claim, Account should be fetched (could be hidden).

When creating Bank Entry against Expense Claim, Expense Accounts as fetched from Expense Claim Type should be updated in the Journal Entry Accounts table.

**Comment by ekpaxp** [comment]
Hi, in our custom App we are working on, we have created custom fields to link an expense account to each Expense Claim type.  That way, we will be able to create the JE traumatically with the correct accounts etc.  We have also done this with Earnings Type and Deductions Type.
What will happen if these fields are introduced in ErpNext App?  I presume if our custom field names are different there would be no issues?

**Comment by rmehta** [comment]
@ekpaxp you should send a pull-request!

But if the fields clash, you will have to probably rename the fields or use the standard feature.
