### ISSUE TITLE
from_time & to_time not displayed in Invoice Timesheet

### ISSUE THREAD

**Issue by joni1993** [frappe/erpnext#35573]
### Information about bug

When adding "Timesheets (Table)" to an invoice print format - activating from_time or to_time does not show it in the final print.

![grafik](https://github.com/frappe/erpnext/assets/29347/9fc5ff69-7367-4a60-b91c-6f0c6fdbd4d1)

![grafik](https://github.com/frappe/erpnext/assets/29347/1a3457fe-4047-4da4-b5f3-2c9f1cc2d8e0)

### Module

accounts, projects

### Version

ERPNext: v14.26.0 (version-14)
Frappe Framework: v14.37.1 (version-14)

### Installation method

easy-install

**Comment by Nihantra-Patel** [comment]
Hi @joni1993,

Kindly upgrade to version 14 or 15, then refresh and check again. We tested in the latest version 14 with a custom print format. In standard format does not show the timesheet table in the invoice.

![image](https://github.com/frappe/erpnext/assets/141945075/0fc84a66-fea2-41e8-bf75-23627d993d1f)

Thank You!
