### ISSUE TITLE
Web Form - Link fields do not shows drop down values...

### ISSUE THREAD

**Issue by nitin-anantpranali** [frappe/erpnext#35583]
### Information about bug

Hi, I have created a new Web form based on the Purchase Request.

And kept the settings as follows
![image](https://github.com/frappe/erpnext/assets/116695322/7a66072d-de66-4736-b2a3-0661ffc8543f)

While making the entry, the Linked fields doesn't pop up values. Is this a noted BUG or configurational mistake?

https://github.com/frappe/erpnext/assets/116695322/ca30e7fe-8f54-4be3-9584-8c992ecc8162

### Module

portal

### Version

ERPNext: v14.26.0 (HEAD)
Frappe Framework: v14.37.1 (HEAD)
Frappe HR: v14.4.0 (HEAD)
India Compliance: v14.9.0 (HEAD)
Payments: v0.0.1 (HEAD)

### Installation method

FrappeCloud

**Comment by s-aga-r** [comment]
@nitin-anantpranali  Please share a screenshot of the `Web Form Fields`
