### ISSUE TITLE
Work Order - Not being generated from the Sales Order

### ISSUE THREAD

**Issue by dineshpanchal93** [frappe/erpnext#35589]
### Information about bug

https://github.com/frappe/erpnext/assets/21578167/9b94982f-f715-40ce-84e5-b7487f574e7b

### Module

selling, manufacturing

### Version

ERPNext: v14.26.0 (version-14)

Frappe Framework: v14.38.0 (version-14)

Frappe HR: v14.4.1 (version-14)

India Compliance: v14.10.0 (version-14)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
No Error logs in Console
```

**Comment by FHenry** [comment]
Hi @dineshpanchal93 

You have to check (the first checkbox column) the line with the checkbox (as the box title explain) to tell witch line you want to produce

I've cross the same misunderstand as well, some "Confirm Box" need to check the first checkbox, other need to remove the unwanted lines (like create quality inspection from Stock Entry)....

**Comment by dineshpanchal93** [comment]
Yes, it got resolved !! A check box is required to generate the Work Order for Against which line item need to generate the Work Order.

@FHenry  Thank you so much
