### ISSUE TITLE
Issues after Upgrading to V14 from V13 - Frappe Cloud

### ISSUE THREAD

**Issue by moizsami** [frappe/erpnext#35595]
### Information about bug

My ERP is hosted on frappe cloud. I requested the upgrade from 13 to 14.

After the upgrade I am noticing couple of things:
- HR module is not available. (although on frappe dashboard ->apps, you can see it available)

![image](https://github.com/frappe/erpnext/assets/24491918/2f25b195-a867-4957-a03b-47bdd7d44689)

but in the about page you do not see it installed:
![image](https://github.com/frappe/erpnext/assets/24491918/311bb4da-6b19-42b3-99c5-beb867176570)

- The second issue is the modified workspaces have become corrupted for some reason hence the navigation bar and center page are not loading.
 
![image](https://github.com/frappe/erpnext/assets/24491918/ecd24302-8938-4caf-b8b2-10344121a998)

If I go into the workspaces form and try to edit anything for the custom user workspace it gives error saying missing title
![image](https://github.com/frappe/erpnext/assets/24491918/1e66a1e5-4282-438e-b07b-91530f35b22a)

### Module

other

### Version

ERPNext: v14.27.0 (HEAD)
Frappe Framework: v14.38.0 (HEAD)

### Installation method

FrappeCloud

**Comment by moizsami** [comment]
Ok the first issue seems to be resolved by uninstalling and reinstalling the HR module, good thing is we dont loose the data.

**Comment by phot0n** [comment]
for 2nd issue: https://github.com/frappe/frappe/pull/21258
