### ISSUE TITLE
problem in Serial numbers automatically entered in delivery note

### ISSUE THREAD

**Issue by negini** [frappe/erpnext#3560]
I have encountered some problems regarding our delivery notes.

We have noticed that when making delivery note, the serial numbers was
automatically there in the serial number box.

We again need to delete the serial numbers automatically entered in the delivery
note and input again the actual serial numbers that has been delivered to
customers.It is too risky for new users not to notice the serial numbers and directly submitted
the document. Serial numbers are essential for us since we are using it for warranty purposes.

Would it be possible to make that serial numbers’ box blank so that we can just enter
the serial numbers manually to avoid this kind of error??
It's make too much problem when some one make delivery note for serials items .

**Comment by rmehta** [comment]
@negini this is for your help to make sure you dispose off the earlier serial nos first (first-in-first-out)

Maybe we can add this as an option (would you be willing to sponsor 1hr of dev work)

https://erpnext.com/pricing/paid-feature-development

**Comment by negini** [comment]
Hi rmehta 
Thanks for your reply , i can be sponsor and pay $50 for this option , can you do it ?

**Comment by negini** [comment]
Hi Rmehta
I requested as [Paid Development]  , i'll be sponsor for this work . please try to do it and update for us .

**Comment by nabinhait** [comment]
fixed
