### ISSUE TITLE
Issue in calculation of no. of days for Depreciation Amount in Assets

### ISSUE THREAD

**Issue by sonali8848** [frappe/erpnext#35627]
### Information about bug

Incorrect calculation of no. of days to calculate depreciation amount.

### Module

assets

### Version

Frappe Version -  v14.25.0 
Erpnext Version -  v14.15.0 

### Installation method

None

**Comment by anandbaburajan** [comment]
Hi @sonali8848, please share the details of the asset in JSON or share the steps to reproduce the error.
