### ISSUE TITLE
Blanket Order cannot handle multi-currency operation

### ISSUE THREAD

**Issue by reinald-at** [frappe/erpnext#35623]
## Unable to handle multi-currency operations in Blanket Order in the Manufacturing module.

For example,
The default currency used in the document is always set to the global default currency.
If the supplier or customer selected in a Blanket Order document is chosen, the currency on the document wouldn't be changed into the currency of the supplier or customer.

Image of Blanket Order document with IDR currency (same as global default) doesn't follow the supplier/customer selected.
![image](https://github.com/frappe/erpnext/assets/134350557/5f25e04c-ca1a-4aa5-b1dc-42018b66b699)

Image of the set billing currency in the Supplier document.
![image](https://github.com/frappe/erpnext/assets/134350557/2749dcf3-2ead-4eb1-9417-a39fc82fe3cd)

Image of global default settings
![image](https://github.com/frappe/erpnext/assets/134350557/3eeab0fc-8b9f-44f5-b698-72802745a85c)

Although the currency in Blanket Order seems to be having problems with the multi-currency operations,
following operations, such as in Purchase Order, seem to have no problem in handling the multi-currency document.
![image](https://github.com/frappe/erpnext/assets/134350557/bc582831-0b73-4c79-94fc-5d44682668de)

### Module

manufacturing

### Version

Frappe version v14.33.0
ERPNext version v14.22.0

### Installation method

docker

**Comment by reinald-at** [comment]
This bug was resolved by creating a **Link**-type field that is named "currency" and links to the **Currency** doctype, which was then used to contain the type of currency, such as "IDR", "SGD", and "CNY".
![image](https://github.com/frappe/erpnext/assets/134350557/43514b8b-b730-411f-a112-61b13db882aa)

On the items table-level fields, the **Options** property of the **Rate** field would then need to be filled with the name of the field which links to the **Currency** doctype. For setting the **Options** property of the **Rate** field on the **Items** table, the **Property Setter** doctype was used to modify the properties of the **Rate** field, 
![image](https://github.com/frappe/erpnext/assets/134350557/712de534-9c62-428f-a55c-4f935d4618d7)

since when modifying the **Options** property on the **Customize Form** interface, an error was thrown stating that 
![image](https://github.com/frappe/erpnext/assets/134350557/23434088-00cb-4168-a809-eaa4d7718540)

**Comment by Nihantra-Patel** [comment]
A Blanket Order is an agreement from a customer to purchase materials for specific items over a period at pre-negotiated rates.

From a blanket order, sales orders can be generated according to the delivery schedule provided by the customer. Blanket orders help customers avoid storing materials in large quantities while allowing them to benefit from fixed rates by committing to volumes within a specific timeframe.

A blanket order facilitates faster creation of sales and purchase transactions but does not support multiple currencies by default. To manage multiple currencies, you need to create two custom fields: "buying price list" and "selling price list." When creating a purchase order or sales order, set the appropriate price list.

Therefore, some customization is required if you want to implement this scenario.
