### ISSUE TITLE
ERPNext shows incorrect ledgers when an account is selectd

### ISSUE THREAD

**Issue by Botanium** [frappe/erpnext#35631]
### Information about bug

currently I am using ERPNext V13 and sometimes I go to General Ledger inside the accounting module, but when I select an account like "Cleaning Expenses" to filter the general ledger and shows only the ledgers that has been done on that account, it also bring different account which shows a wrong balance at the end.

There are no child accounts under cleaning expense, but it shows fuel expenses as well. 
![image](https://github.com/frappe/erpnext/assets/3994826/6385883d-65b3-4c58-8b8a-47d13aa4644d)

### Module

accounts

### Version

Frappe Chat: v0.0.1 (HEAD)
**ERPNext: v13.51.1 (HEAD)**
Erpnext Telegram Integration: v1.2.0 (HEAD)
**Frappe Framework: v13.56.7 (HEAD)**
Laboratory: v0.0.1 (HEAD)
Twilio Integration: v0.0.1 (HEAD)

### Installation method

FrappeCloud

**Comment by deepeshgarg007** [comment]
@Botanium This is because there might be issues with your nested set model (Tree Structure). Use the rebuilt tree button to fix this issue (Note, only the admin user will see this button)

![Uploading Screenshot 2023-07-04 at 1.53.35 PM.png…]()
