### ISSUE TITLE
Please make sure that Redis Queue runs @ redis://localhost:11000"

### ISSUE THREAD

**Issue by mrPauwHaan** [frappe/erpnext#35632]
### Information about bug

Hello, when downloading ERPNext I am getting this error when creating a new site. I have never received this error before and I saw that someone else also posted today a forum post about this exact same issue.

Please make sure that Redis Queue runs @ redis://localhost:11000"

### Module

other

### Version

Frappe Version: 5.16.3

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
bench new-site test1.loc
MySQL root password:

Installing frappe…
Updating DocTypes for frappe : [========================================] 100%
Updating country info : [========================================] 100%
Set Administrator password:
Re-enter Administrator password:
Please make sure that Redis Queue runs @ redis://localhost:11000
Please make sure that Redis Queue runs @ redis://localhost:11000
Please make sure that Redis Queue runs @ redis://localhost:11000
Please make sure that Redis Queue runs @ redis://localhost:11000
Please make sure that Redis Queue runs @ redis://localhost:11000
Please make sure that Redis Queue runs @ redis://localhost:11000
Please make sure that Redis Queue runs @ redis://localhost:11000
Please make sure that Redis Queue runs @ redis://localhost:11000
Please make sure that Redis Queue runs @ redis://localhost:11000
Please make sure that Redis Queue runs @ redis://localhost:11000
Traceback (most recent call last):
File “/home/frappe/f14/apps/frappe/frappe/model/base_document.py”, line 502, in db_insert
frappe.db.sql(
File “/home/frappe/f14/apps/frappe/frappe/database/database.py”, line 221, in sql
self._cursor.execute(query, values)
File “/home/frappe/f14/env/lib/python3.10/site-packages/pymysql/cursors.py”, line 158, in execute
result = self._query(query)
File “/home/frappe/f14/env/lib/python3.10/site-packages/pymysql/cursors.py”, line 325, in _query
conn.query(q)
File “/home/frappe/f14/env/lib/python3.10/site-packages/pymysql/connections.py”, line 549, in query
self._affected_rows = self._read_query_result(unbuffered=unbuffered)
File “/home/frappe/f14/env/lib/python3.10/site-packages/pymysql/connections.py”, line 779, in _read_query_result
result.read()
File “/home/frappe/f14/env/lib/python3.10/site-packages/pymysql/connections.py”, line 1157, in read
first_packet = self.connection._read_packet()
File “/home/frappe/f14/env/lib/python3.10/site-packages/pymysql/connections.py”, line 729, in _read_packet
packet.raise_for_error()
File “/home/frappe/f14/env/lib/python3.10/site-packages/pymysql/protocol.py”, line 221, in raise_for_error
err.raise_mysql_exception(self._data)
File “/home/frappe/f14/env/lib/python3.10/site-packages/pymysql/err.py”, line 143, in raise_mysql_exception
raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, “Duplicate entry ‘email_account.pull’ for key ‘PRIMARY’”)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File “/home/frappe/f14/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py”, line 209, in insert_single_event
doc.insert()
File “/home/frappe/f14/apps/frappe/frappe/model/document.py”, line 270, in insert
self.db_insert(ignore_if_duplicate=ignore_if_duplicate)
File “/home/frappe/f14/apps/frappe/frappe/model/base_document.py”, line 529, in db_insert
raise frappe.DuplicateEntryError(self.doctype, self.name, e)
frappe.exceptions.DuplicateEntryError: (‘Scheduled Job Type’, ‘email_account.pull’, IntegrityError(1062, “Duplicate entry ‘email_account.pull’ for key ‘PRIMARY’”))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File “/home/frappe/f14/env/lib/python3.10/site-packages/redis/connection.py”, line 559, in connect
sock = self._connect()
File “/home/frappe/f14/env/lib/python3.10/site-packages/redis/connection.py”, line 615, in _connect
raise err
File “/home/frappe/f14/env/lib/python3.10/site-packages/redis/connection.py”, line 603, in _connect
sock.connect(socket_address)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File “/home/frappe/f14/env/lib/python3.10/site-packages/tenacity/init.py”, line 407, in call
result = fn(*args, **kwargs)
File “/home/frappe/f14/apps/frappe/frappe/utils/background_jobs.py”, line 380, in get_redis_conn
redis_connection = RedisQueue.get_connection(**cred)
File “/home/frappe/f14/apps/frappe/frappe/utils/redis_queue.py”, line 24, in get_connection
conn.ping()
File “/home/frappe/f14/env/lib/python3.10/site-packages/redis/client.py”, line 1378, in ping
return self.execute_command(‘PING’)
File “/home/frappe/f14/env/lib/python3.10/site-packages/redis/client.py”, line 898, in execute_command
conn = self.connection or pool.get_connection(command_name, **options)
File “/home/frappe/f14/env/lib/python3.10/site-packages/redis/connection.py”, line 1192, in get_connection
connection.connect()
File “/home/frappe/f14/env/lib/python3.10/site-packages/redis/connection.py”, line 563, in connect
raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 99 connecting to localhost:11000. Cannot assign requested address.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File “/usr/lib/python3.10/runpy.py”, line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File “/usr/lib/python3.10/runpy.py”, line 86, in _run_code
exec(code, run_globals)
File “/home/frappe/f14/apps/frappe/frappe/utils/bench_helper.py”, line 109, in
main()
File “/home/frappe/f14/apps/frappe/frappe/utils/bench_helper.py”, line 18, in main
click.Group(commands=commands)(prog_name=“bench”)
File “/home/frappe/f14/env/lib/python3.10/site-packages/click/core.py”, line 829, in call
return self.main(*args, **kwargs)
File “/home/frappe/f14/env/lib/python3.10/site-packages/click/core.py”, line 782, in main
rv = self.invoke(ctx)
File “/home/frappe/f14/env/lib/python3.10/site-packages/click/core.py”, line 1259, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File “/home/frappe/f14/env/lib/python3.10/site-packages/click/core.py”, line 1259, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File “/home/frappe/f14/env/lib/python3.10/site-packages/click/core.py”, line 1066, in invoke
return ctx.invoke(self.callback, **ctx.params)
File “/home/frappe/f14/env/lib/python3.10/site-packages/click/core.py”, line 610, in invoke
return callback(*args, **kwargs)
File “/home/frappe/f14/apps/frappe/frappe/commands/site.py”, line 77, in new_site
_new_site(
File “/home/frappe/f14/apps/frappe/frappe/installer.py”, line 106, in _new_site
install_app(app, verbose=verbose, set_as_patched=not source_sql, force=False)
File “/home/frappe/f14/apps/frappe/frappe/installer.py”, line 306, in install_app
sync_jobs()
File “/home/frappe/f14/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py”, line 152, in sync_jobs
all_events = insert_events(scheduler_events)
File “/home/frappe/f14/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py”, line 164, in insert_events
event_jobs += insert_event_jobs(events, event_type)
File “/home/frappe/f14/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py”, line 182, in insert_event_jobs
insert_single_event(frequency, event)
File “/home/frappe/f14/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py”, line 212, in insert_single_event
doc.delete()
File “/home/frappe/f14/apps/frappe/frappe/model/document.py”, line 1021, in delete
return frappe.delete_doc(
File “/home/frappe/f14/apps/frappe/frappe/init.py”, line 1244, in delete_doc
return frappe.model.delete_doc.delete_doc(
File “/home/frappe/f14/apps/frappe/frappe/model/delete_doc.py”, line 129, in delete_doc
frappe.enqueue(
File “/home/frappe/f14/apps/frappe/frappe/init.py”, line 2167, in enqueue
return frappe.utils.background_jobs.enqueue(*args, **kwargs)
File “/home/frappe/f14/apps/frappe/frappe/utils/background_jobs.py”, line 101, in enqueue
q = get_queue(queue, is_async=is_async)
File “/home/frappe/f14/apps/frappe/frappe/utils/background_jobs.py”, line 342, in get_queue
return Queue(generate_qname(qtype), connection=get_redis_conn(), is_async=is_async)
File “/home/frappe/f14/env/lib/python3.10/site-packages/tenacity/init.py”, line 324, in wrapped_f
return self(f, *args, **kw)
File “/home/frappe/f14/env/lib/python3.10/site-packages/tenacity/init.py”, line 404, in call
do = self.iter(retry_state=retry_state)
File “/home/frappe/f14/env/lib/python3.10/site-packages/tenacity/init.py”, line 361, in iter
raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x7f425a5a01f0 state=finished raised ConnectionError>]
```

**Comment by Abhishek-Chougule** [comment]
sudo nano /etc/redis/redis.conf
update port number to 11000. comment original port 6379
i hope this will fix your problem.

**Comment by kumuduraj** [comment]
We got same error. any solution?

**Comment by mikibudhiraja** [comment]
> sudo nano /etc/redis/redis.conf
> update port number to 11000. comment original port 6379
> i hope this will fix your problem.

This fixes the problem but gives an error while installing HRMS app.

**Comment by AishaMabdqr** [comment]
Same issue I fixed the port number to "11001" and I am unable to start the bench.

The new error is "Could not create server TCP listening socket 127.0.0.1:11001: bind: Address already in use"
 

Any solutions?

**Comment by amitascra** [comment]
yeah when we do this : 
"sudo nano /etc/redis/redis.conf
update port number to 11000. comment original port 6379"

then , i am not able to start Bench because it give error : 

"Could not create server TCP listening socket 127.0.0.1:11001: bind: Address already in use"

So after creating a Site or App or after installing app i am reverting the changes in redis.conf final in order to start bench again..... Cant find the solution to this but as of now this the solution to change the port in redis.conf file everytime after creating site or installing app.

**Comment by Abhishek-Chougule** [comment]
Solution : 
Just setup production auto / manual by running below commands:
For automatic : sudo bench setup production username

Note : i recommend manual setup.

For manual : 

Supervisor: 
sudo apt -y install supervisor
bench setup supervisor
sudo ln -s `pwd`/config/supervisor.conf /etc/supervisor/conf.d/frappe-bench.conf

Nginx : 
sudo apt -y install nginx
bench setup nginx
sudo ln -s `pwd`/config/nginx.conf /etc/nginx/conf.d/frappe-bench.conf

Please confirm and replace your username and bench name as per yours.
Then start the bench.
And then run bench new-site site_name command.
It will definitely work. 

Happy Learning 
Thanks :)

**Comment by lstbrian** [comment]
> Solution : Just setup production auto / manual by running below commands: For automatic : sudo bench setup production username
> 
> Note : i recommend manual setup.
> 
> For manual :
> 
> Supervisor: sudo apt -y install supervisor bench setup supervisor sudo ln -s `pwd`/config/supervisor.conf /etc/supervisor/conf.d/frappe-bench.conf
> 
> Nginx : sudo apt -y install nginx bench setup nginx sudo ln -s `pwd`/config/nginx.conf /etc/nginx/conf.d/frappe-bench.conf
> 
> Please confirm and replace your username and bench name as per yours. Then start the bench. And then run bench new-site site_name command. It will definitely work.
> 
> Happy Learning Thanks :)

it doesn't work. can you give us an example on with linux syntax "Please confirm and replace your username and bench name as per yours" is ubuntu username is frappe, then ..?

**Comment by CoffeeGeek101** [comment]
what is this?? is this a bug or we need to configure our sites differently?? because I don't have any file @/etc/redis/redis.con
I have supervisor, nginx, mariaDB and other requirements are already installed. 
What's the solution for this issue?

I'm using Mac, apple silicon chip

**Comment by CoffeeGeek101** [comment]
> sudo nano /etc/redis/redis.conf
> update port number to 11000. comment original port 6379
> i hope this will fix your problem.

still the same issue remains : 
 
<img width="349" alt="Screenshot 2023-06-22 at 2 27 35 PM" src="https://github.com/frappe/erpnext/assets/110016849/2be20545-a4e2-4604-a631-903d4745bd9f">

**Comment by 0xhaval** [comment]
I faced the same error with the 11001 port, 
I solved it with the following steps

`sudo nano /etc/redis/redis.conf`

Look for the following lines in the configuration file:
`port 6379`

Add a new line below the port line to specify the extra port you want to use. For example, if you want to add port 11000, the configuration will look like this:
`port 6379`
`port 11001`


after saving the file, Restart the Redis server to apply the new configuration. Use the following command:
`sudo service redis-server restart`

To test the connection to the extra port, you can run the following command:
`redis-cli -h localhost -p 11001 ping`


If the connection is successful, you will see PONG as the response.
create the new site by this command :
`bench new-site [site-name]`

**Comment by kumuduraj** [comment]
I tried but still getting same error. i am trying this past 2 week .
stills unable to install .  I would be very grateful if you could help me
with this matter

[image: image.png]

**Comment by kumuduraj** [comment]
I installed it successfully 3 week ago. same environment. same installation
guide. but now it is not working.  I don't
 know why.

**Comment by Abhishek-Chougule** [comment]
Solution :
Just setup production auto and manual by running below commands:

For automatic : 
sudo bench setup production username

then :

Supervisor:
sudo apt -y install supervisor
bench setup supervisor
sudo ln -s pwd/config/supervisor.conf /etc/supervisor/conf.d/frappe-bench.conf

Nginx :
sudo apt -y install nginx
bench setup nginx
sudo ln -s pwd/config/nginx.conf /etc/nginx/conf.d/frappe-bench.conf

Note: Here 'frappe-bench' is name of your bench.

sudo systemctl restart nginx
sudo systemctl restart mariadb
sudo systemctl restart supervisor
sudo bench restart


Please confirm and replace bench name as per yours.

And then run : 
sudo bench new-site site_name --force

It will definitely work.

Happy Learning
Thanks :)

**Comment by CoffeeGeek101** [comment]
the manual setup works.

**Comment by ankush** [comment]
https://github.com/frappe/frappe/pull/21539

**Comment by rioshaz** [comment]
@ankush 

new Site will add but during set-wizard it fail  with :
"newly created user xyz@123.com  has no roles enabled. "
as redis issue is not solved by just delete the  line :   "frappe.email.doctype.email_account.email_account.pull",

Also  the bench migrate fails with : 
Please make sure that Redis Queue runs @ redis://localhost:11000

""
Queued rebuilding of search index for team.example.com
Please make sure that Redis Queue runs @ redis://localhost:11000

so just changed in : common_site_config.json file

redis_queue": "redis://localhost:11000",  to redis_queue": "redis://localhost::6379",

all works perfect
