### ISSUE TITLE
Editing Price while on POS View

### ISSUE THREAD

**Issue by jof2jc** [frappe/erpnext#3565]
Currently user cannot edit the price while creating POS Invoice (via POS View). So, we have to maintain and keep updating price list which is not efficient.

For most small businesses here at my local use-cases, price-list is just for 'reference'. At the end buyer and seller come to agreed-price rate, so it must be flexible at transaction point-of-time.

I believe this 'small' feature would be helpful for for most small businesses.
https://discuss.frappe.io/t/edit-the-price-on-pos-view/6472/2

**Comment by rmehta** [comment]
https://erpnext.com/pricing/paid-feature-development

**Comment by nabinhait** [comment]
fixed in v7
