### ISSUE TITLE
Missing Cents

### ISSUE THREAD

**Issue by jeanneanne713** [frappe/erpnext#35656]
### Information about bug

Somehow we think there was an update done to the round up round down function because in any order confirmations we have that have not been processed to an invoice yet are not showing the cents and if the cost is less than a 1 dollar it looks like it is a zero but when you click on it then you can see the actual cost, we need to be able to see the cost without having to click on it.  There must of been an update to this over the weekend because last week it was right.  You can see in the screenshots below the first shows that it looks like the packing is $0.00 in the field but if you click on the line item under packing you can see in the second screen shot you can see how i clicked on the second line item under packing and it shows it is not 0.00 it is 0.50 we need it to look like that all the item.  

### Module

selling

### Version

![Screenshot 2023-06-12 112223](https://github.com/frappe/erpnext/assets/136361395/8bad7020-1a18-4b64-a7b7-64cf74f679a2)
![Screenshot 2023-06-12 112257](https://github.com/frappe/erpnext/assets/136361395/d9292672-19e1-49ba-a283-fdc121e200da)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
Somehow we think there was an update done to the round up round down function because in any order confirmations we have that have not been processed to an invoice yet are not showing the cents and if the cost is less than a 1 dollar it looks like it is a zero but when you click on it then you can see the actual cost, we need to be able to see the cost without having to click on it.  There must of been an update to this over the weekend because last week it was right.  You can see in the screenshots below the first shows that it looks like the packing is $0.00 in the field but if you click on the line item under packing you can see in the second screen shot you can see how i clicked on the second line item under packing and it shows it is not 0.00 it is 0.50 we need it to look like that all the item.
```

**Comment by Nihantra-Patel** [comment]
Hi @jeanneanne713,

Everything is working fine. No problems were encountered in the latest versions 14 and 15.

Kindly upgrade to version 14 or 15, then refresh and check again.
If your version is 13, We no longer provide support for version 13 or older.

Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!
