### ISSUE TITLE
Pick Columns on List-view Reports

### ISSUE THREAD

**Issue by jof2jc** [frappe/erpnext#3566]
PickColumns for list-view report in almost forms I think...it doesn't scroll down if we add many columns list.

![window-report pick column](https://cloud.githubusercontent.com/assets/12841357/8491659/993cb9ce-2167-11e5-964b-1bbacdd98867.png)

**Comment by jof2jc** [comment]
I also found the same issue on Select Table Columns For Items on Print Format Builder

**Comment by rmehta** [comment]
can't replicate in Firefox / Chrome. What browser are you using?

**Comment by jof2jc** [comment]
I'm using erpnext 5.1.2 and Chrome v43..the popup window won't scroll down..

**Comment by strixaluco** [comment]
Can't replicate. I've added over 40 columns in Firefox ESR 45.5.1 and Chrome 55.0.2883.87.
