### ISSUE TITLE
Multiple Invoices for the same Sales Order possible with Shopping Cart and Payment Request

### ISSUE THREAD

**Issue by casesolved-co-uk** [frappe/erpnext#35685]
### Information about bug

`on_payment_authorised` does not protect against multiple calls, which could happen with asynchronous processing like webhooks on a payment gateway.

This will result in multiple Invoices and Payment Entries being created against the same Shopping Cart Sales Order.

https://github.com/frappe/erpnext/blob/984f89d274289535e05c53ae8dc47ef4454a65e3/erpnext/accounts/doctype/payment_request/payment_request.py#L367

### Module

accounts

### Version

ERPNext all

### Installation method

None

**Comment by Nihantra-Patel** [comment]
The feature is not available now and it's not easy to maintain. However, it might be possible in the future with updates in the upcoming version or through some app enhancements (like payments and webshop). Currently, it's not in the plans.

**Comment by casesolved-co-uk** [comment]
This is a bug not a feature request.
