### ISSUE TITLE
 Product wise raw material tracking ERPNext Stock

### ISSUE THREAD

**Issue by inventobd** [frappe/erpnext#3568]
I,m manufacturing 2 items example: Item x and item Y which are books at the same time .

I have purchased same raw materials with different price and from same supplier for both this books which is ex: book binding (1 for item x with bdt 2000 and another for item y with bdt 3000) . Now when both of them are in stock how can I track which material I have purchased for item x and which one for item y ?

**Comment by rmehta** [comment]
When you create Production Order, the item will be "Planned" in Stock Level report.

Questions on https://discuss.frappe.io please
