### ISSUE TITLE
Skip available sub assembly items in production plan not working : incorrect projected qty fetch

### ISSUE THREAD

**Issue by willspenc** [frappe/erpnext#35690]
### Information about bug

Good day 
I created a BOM as follows
Prod 5 consistes of 2 sub assemblies, Sub 1 & Sub 2  ( Finished Good WareH)
Sub 1 = Item 2 & Item 3 ( Sub Assemblies WareH )
Sub 2 = Item 4 & Item 5 ( Sub Assemblies WareH)

I produce some units of  "Sub 1" ( Sub Assemblies WareH )
"Sub 2" has no stock (Sub assemblies WareH)

I check the projected qty in 2 places for "Sub 1"
Stock Project QTY report ( Module Stock)
I also check on the backend in `tabBin`. Report and database report same values.

I modify the "Sub assemblies table" in "Production Plan" to indicated "Projected qty" .

Create Production plan
Select "Prod 5"
Select "Skip available sub assembly items"
Click "Get sub assembly items"

BOTH "Sub 1" and "Sub 2" is fetched. And even thought the projected qty is reported by the report ( see earlier) as 3 units,
the "projected qty" column in my "Sub assembly Items" table repors zero (0) for both "Sub 1" and "Sub 2".

Clearly the projected qty is fetched incorrectly when the Sub Assembly item table is populated and this explains why 
"Sub 1" is placed in the table even thought it should not be there. This is the closest I can get to making
a suggestion, because I did look at the code but cannot make any further suggestions.
Thank you

### Module

manufacturing

### Version

ERPNExt V14.27.0
Frappe 14.38.0

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
No errors generated
```

**Comment by Nihantra-Patel** [comment]
Hi @willspenc,

Everything is working fine. No problems were encountered in the latest versions 14 and 15.
If the issue occurs then please create a new issue according to version (14 or 15) with a video document if possible.

If you haven't checked the scenario and [documentation](https://docs.erpnext.com/docs/user/manual/en/managing-multi-level-bom) then please check it.

Also check the Video.

https://www.youtube.com/watch?v=TjhNa1Ifeso

Thank You!
