### ISSUE TITLE
Exchange Rate Revaluation :unable to save

### ISSUE THREAD

**Issue by thida-bcn** [frappe/erpnext#35691]
### Information about bug

<img width="866" alt="image" src="https://github.com/frappe/erpnext/assets/62122640/ff976837-a57d-4851-bda6-3127d4f2e104">
No error log
No message
unable to save

### Module

accounts

### Version

Email Delivery Service: v0.0.1 (HEAD)

ERPNext: v14.27.2 (HEAD)

Frappe Framework: v14.39.0 (HEAD)

Payments: v0.0.1 (HEAD)

### Installation method

easy-install

### Relevant log output / Stack trace / Full Error Message.

```shell
demo at erpnext.com
```

**Comment by deepeshgarg007** [comment]
@thida-bcn The issue is not replicable at our end. Please add more info and reopen the issue if possible
