### ISSUE TITLE
No result when deleting more than 10 items in bulk.

### ISSUE THREAD

**Issue by cyberxnomad** [frappe/erpnext#35705]
### Information about bug

When more than 10 items are selected and the delete button is clicked, the page will immediately refresh with no prompt, and the selected items will not be deleted.

### Module

other

### Version

Frappe version: 14.39.0
ERPNext version: 14.27.2

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Sorry, I'm not sure where to obtain the relevant logs.
```

**Comment by deepeshgarg007** [comment]
@xray-bit There must be some error in the browser console or something in the network request data. Without those there isn't much to investigate. Closing this issue
