### ISSUE TITLE
Party Account Trade Receivable - - currency xxx and document currency xxx should be same

### ISSUE THREAD

**Issue by khaledrifa3i** [frappe/erpnext#35727]
### Information about bug

when submitting an invoice for a customer with a currency different than the trade receivable account currency, received this mesaage "Party Account Trade Receivable - - currency (AED) and document currency (OMR) should be same", 
This only apply for newly added customers with configured price list with different currency than the trade receivable account.

customers already added in version 13, with different price list currency than the trade receivable account  are still working normally while submitting the invoices. 

please note that currency exchange rate is configured already in the currency exchange list 

### Module

selling

### Version

Frappe Version 14.38.0 and 14.39
ERPNext Version 14.27.1 and 14.27.5

### Installation method

docker

### Relevant log output / Stack trace / Full Error Message.

```shell
Party Account Trade Receivable - - currency (AED) and document currency (OMR) should be same
```

**Comment by Sendipad** [comment]
Check whether you have posted any journal entry to that party with other currency , mostly this happened by Journal entries

**Comment by deepeshgarg007** [comment]
@khaledrifa3i You can enable the below setting to resolve this issue, doesn't look like a bug

<img width="1346" alt="Screenshot 2023-06-29 at 4 17 15 PM" src="https://github.com/frappe/erpnext/assets/42651287/c17e2c36-7421-44e9-8429-b0c7e8114ce5">
