### ISSUE TITLE
Get Outstanding Invoice in Payment Entry showing Overdue Sales Orders

### ISSUE THREAD

**Issue by Craftint** [frappe/erpnext#35760]
### Information about bug

in Payment Entry, when we get outstanding invoices, its getting **overdue sales orders** in that table, it should bring just outstanding sales invoices,
![image](https://github.com/frappe/erpnext/assets/67686213/55b0070c-2968-4b3e-a4a7-35c9cb469d31)

### Module

accounts

### Version

Frappe Framework: v14.38.3 
ERPNext: v14.27.1 

### Installation method

None

**Comment by anandbaburajan** [comment]
Fixed in https://github.com/frappe/erpnext/pull/35776
