### ISSUE TITLE
 How to calculate production cost by deducting damaged item quantity?

### ISSUE THREAD

**Issue by inventobd** [frappe/erpnext#3577]
I,m doing production of an item X with a quantity of 500 piece. I have a BOM with raw materials of
BDT 98288 . It provides me a production cost of 192 for each item. I have a transfer cost of BDT 500 from work in progress warehouse to finished goods warehouse, which makes production cost 197 for each item. This is what I have done so far . But I have 50 piece of damaged product at the time of production which I can't transfer to my finished good warehouse. So it will make total quantity to 450 and will increase production cost for each item to BDT 219 . I didn't find any option to log that damaged quantity and increase price .

How can I deduct the damaged quantity before transferring to finished good warehouse and increase final production cost according to that ? And also where I can log warehouse transfer cost ?

---------------------------------------------------------------------------------------------------

neilLasrado

@inventobd We don't have a system to handle rejected goods in ERPNext against a production order. please check this kb to learn how to manage rejected goods. https://kb.erpnext.com/kb/stock/manage-rejected-finished-goods-items4

There is a issue at https://github.com/frappe/erpnext/issues/33402 i feel is similar to your case. Please do give your inputs.

---------------------------------------------------------------------------------------------------

Hello neilLasrado

Thank you very much for your replay. Right now I,m doing this way. But this cannot be a solution. Because I need to calculate my production cost by deducting damaged quantity. But production order calculates production cost for each item from boom not from production order or finished goods quantity. This feature is very important .

Is it possible to add this is feature request ?

**Comment by rmehta** [comment]
Can you sponsor?

**Comment by inventobd** [comment]
Yes . Can you provide me an estimation ? 
Thanks :)

**Comment by rmehta** [comment]
@inventobd let us get back to you next week with an estimate. Thanks!

**Comment by nabinhait** [comment]
@inventobd 

Estimate is 4 billable hours
For terms, please check https://erpnext.com/pricing/paid-feature-development

**Comment by rmehta** [comment]
@inventobd are you still interested in sponsoring?

**Comment by inventobd** [comment]
Hello Rushabh
Sorry for being late . Actually it was a long Eid holiday here in Bangladesh. Yes I,m still interested on this but can you provide me a little more time on this ? I had another issue before this one which is very important for us right now also . If and if you guyz are kind enough :) can you also provide me an estimation for this too ? :) 
https://github.com/frappe/erpnext/issues/3452
Thanks in advance

**Comment by bohlian** [comment]
I want to revive this enhancement request particularly with respect to capturing wastage. I imagine we have a place to specify the wastage warehouse and once the **Production Order** is **In Progress**, we can click a button called **Wastage** and specify Raw Materials that was wasted.

Am interested to know what the team thinks would be the best way to do this?
