### ISSUE TITLE
Serial and Batch Bundle: New Batch No. Not Displayed

### ISSUE THREAD

**Issue by pmjd-code** [frappe/erpnext#35804]
### Information about bug

When creating a new Purchase Receipt, a new Serial and Batch Bundle ID is created for each item and a new Batch ID is created for each item. 

However, the Batch ID is no longer displayed (see screenshot below).
![image](https://github.com/frappe/erpnext/assets/81377942/963d680a-2d4f-4bfe-b75d-dbf82036e87a)

The option exists to _Add_ a Batch/Serial No., rather than displaying the newly created Batch No.
![image](https://github.com/frappe/erpnext/assets/81377942/2d22344f-93ee-435a-98f1-61885792a327)

### Module

stock

### Version

Frappe version - 15.x.x-develop (updated 20-Jun-2023 10:08 GMT)
ERPNext version - 14.x.x-develop (updated 20-Jun-2023 10:08 GMT)

### Installation method

manual install

**Comment by s-aga-r** [comment]
@pmjd-code You can ignore the Batch ID and Serial No fields, we have made it read-only (They are visible to you as you have added them on List View). The Serial and Batch details will be kept in the Serial and Batch Bundle only.

**Comment by pmjd-code** [comment]
@s-aga-r I don't think you have understood the issue.

When I created a Purchase Receipt previously, a Batch No was created (as defined in the Item) for the received item and displayed, so the end user knew what Batch No to physically label it with. This is no longer the case, the link between them is broken and the only link is the Serial and Batch Bundle ID (SBB). As you can see there are no links on the Purchase Receipt
![image](https://github.com/frappe/erpnext/assets/81377942/b9050f40-e4ea-4598-b0a7-5f12e680c156)

But if I select the item and click on the SBB I can find the Batch No, as in previous screenshots.

This is a **significant** loss of functionality.

How can an end user know which Batch No to label a physical item with if they can no longer see it, and having to click through several options to find it is near useless.

The introduction of the Serial and Batch Bundle ID seems to have caused this.

Is there a way to restore the linkage between the items in the Purchase Receipt and the Batch No created?

**Comment by s-aga-r** [comment]
@rohitwaghchaure I think we should also show Serial Nos and Batch Nos (fetched from SBB) in the document(?)

**Comment by rohitwaghchaure** [comment]
@pmjd-code since we can't add the child table inside the another child table, we can show the Serial Nos / Batches in the HTML table format below the items table like as below

<img width="1000" alt="image" src="https://github.com/frappe/erpnext/assets/8780500/28c39baa-57ad-43a4-8eb8-833f68f360f6">

Will this solution work for you?

**Comment by pmjd-code** [comment]
Thank you @rohitwaghchaure it looks like it could work.

Can the Serial/Batch Nos info include warehouse (on presumption that it is the info in the Serial and Batch Bundle doctype), and are the values in this table accessible via a client script? 

I ask because I currently use a client script to create a button to pull the information from the Purchase Receipt Items table (item code, item name, status of accepted/rejected (warehouse could work) and quantity) and print directly to a Zebra label printer with this information and the correct quantity of labels for each item.

One other thing I notice is that the **Connection** section of the Batch, the links to both Purchase Receipt or any Quality Inspection are absent but the Serial and Batch Bundle ID is present. The LOT000004 below had both a Purchase Receipt and a Quality Inspection but the link to neither is present in the **Connections** lists, only the Serial and Batch Bundle ID. Should this be raised as a separate bug?
![image](https://github.com/frappe/erpnext/assets/81377942/76a772d0-6498-4735-807a-0ab7da175648)

**Comment by rohitwaghchaure** [comment]
> Can the Serial/Batch Nos info include warehouse (on presumption that it is the info in the Serial and Batch Bundle doctype), and are the values in this table accessible via a client script?

We can add the 'warehouse' column to the table. Since this is HTML code, you cannot retrieve the values using 'doc.fieldname'. Instead, you can obtain the information from the 'Serial and Batch Entry' table using the method 'frappe.get_all'.


> One other thing I notice is that the **Connection** section of the Batch, the links to both Purchase Receipt or any Quality Inspection are absent but the Serial and Batch Bundle ID is present. The LOT000004 below had both a Purchase Receipt and a Quality Inspection but the link to neither is present in the **Connections** lists, only the Serial and Batch Bundle ID. Should this be raised as a separate bug?

This is not a bug; we will remove the unlinked connections and add a Report link to view transactions made against the Batch.

**Comment by pmjd-code** [comment]
Ah an HTML table, did wonder why it looked different. This would be a useful feature to display the information.

I do still think there is a bug/breakage between Purchase Receipts and Quality Inspections. 
When you create and submit a Quality Inspection as part of a Purchase Receipt it does not have the Batch number associated, because the Batch number has not yet been created. However, once the Purchase Receipt is submitted and the Batch number created, the Quality Inspection is not updated to reference the Batch number. 

So the Quality Inspection for the item is only accessible via the Purchase Receipt, there is no direct link to the Batch or Serial and Batch Bundle for that matter.

Will the Report link help with issues like this?

**Comment by rohitwaghchaure** [comment]
> Ah an HTML table, did wonder why it looked different. This would be a useful feature to display the information.

This is just a mockup and not actual table.



> I do still think there is a bug/breakage between Purchase Receipts and Quality Inspections. When you create and submit a Quality Inspection as part of a Purchase Receipt it does not have the Batch number associated, because the Batch number has not yet been created. However, once the Purchase Receipt is submitted and the Batch number created, the Quality Inspection is not updated to reference the Batch number.

In this case better you create the Batch first


> So the Quality Inspection for the item is only accessible via the Purchase Receipt, there is no direct link to the Batch or Serial and Batch Bundle for that matter.

Batch No Link field is available in the Quality Inspection, So in batch connection the Quality Inspection will remain as it's. We'll remove the Purchase Receipt, Purchase Invoice, Sales Invoice and Delivery Note documents from the batch connection

**Comment by pmjd-code** [comment]
> 
> In this case better you create the Batch first
> 
How can I do that? The way ERPNext is setup is that if I cannot create the Batch number until the Purchase Receipt is submitted. Once submitted there is no trigger to force the user to perform a Quality Inspection on a received item, in out case a delivery from a supplier can be a mix of items that do and do not require a Quality Inspection.

**Comment by rohitwaghchaure** [comment]
> How can I do that? The way ERPNext is setup is that if I cannot create the Batch number until the Purchase Receipt is submitted. Once submitted there is no trigger to force the user to perform a Quality Inspection on a received item, in out case a delivery from a supplier can be a mix of items that do and do not require a Quality Inspection.

I think we are deviating from the main topic. This issue is also present in version 14. You can't link the auto-created batch from the Purchase Receipt in the quality inspection. First, you need to create a batch and then link it with the Quality Inspection.

**Comment by pmjd-code** [comment]
> I think we are deviating from the main topic. 

Perhaps but your reply was quite dismissive, telling me to do something that I couldn't see how ERPNext could be setup to allow, so I just wanted to asked you how this was possible.

> This issue is also present in version 14. You can't link the auto-created batch from the Purchase Receipt in the quality inspection.

Yes it is, quite happy to raise it there too if you wish, or will the batch transaction report you have previously mentioned solve this by including links to Quality Inspections performed on Purchase Receipt for a Batch?

**Comment by rohitwaghchaure** [comment]
> Perhaps but your reply was quite dismissive, telling me to do something that I couldn't see how ERPNext could be setup to allow, so I just wanted to asked you how this was possible.

Currently, achieving this is not possible. We need to generate the Batch / Serial Nos upon the creation of the Purchase Receipt instead of waiting for its submission. This could be a significant change, which is why I am considering tracking this issue separately rather than within this thread.

**Comment by pmjd-code** [comment]
@rohitwaghchaure if you implement your original fix to display an additional table with the Batch info, is this likely to be weeks or months away? Just asking so I can plan accordingly.

Thanks

**Comment by rohitwaghchaure** [comment]
@pmjd-code The earlier solution was causing issues, so we decided to discard it. Instead, we have implemented a new solution to solve this problem. In the new solution, we have added a button called 'View Serial/Batch Numbers' in the Form View, which enables users to easily access and view the Serial/Batch Numbers. For more details, please refer to the [PR link](https://github.com/frappe/erpnext/pull/36151).

**Comment by pmjd-code** [comment]
@rohitwaghchaure thanks but I can’t see this option available. 

The PR referenced is listed as merged, have just updated and can’t see this as an option in the Purchase Receipt screen.

**Comment by pmjd-code** [comment]
Can see the options available now, must have been an odd caching issue.
