### ISSUE TITLE
Blanket Order Connections + sign lost. 

### ISSUE THREAD

**Issue by ShwetaERPData** [frappe/erpnext#35814]
![image](https://github.com/frappe/frappe/assets/113356463/93a12f88-83ca-46df-96eb-9163e96fd0f7)
Plus sign is missing
Please help

**Comment by Nihantra-Patel** [comment]
Hi @ShwetaERPData,

Everything is working fine. No problems were encountered in versions 14 and 15.
Kindly upgrade to version 14 or 15, then refresh and check again.

![image](https://github.com/frappe/erpnext/assets/141945075/df831243-119f-4c4c-8a16-0ed9a4b4178f)

Thank You!
