### ISSUE TITLE
Due date on sales invoice will not change from delivery date of associated sales order

### ISSUE THREAD

**Issue by hroperators** [frappe/erpnext#35817]
### Information about bug

Due date on sales invoice will not change from delivery date of associated sales order

Tried every combination of removing terms, changing terms, and the value in the payment schedule always reverts to delivery date of associated sales order on save/submit.

Previously the terms would be fetched from Sales Order but would be editable on associated sales invoice.

As items may be delivered prior to invoice being submitted, this is a large problem with AR. As due date of invoice should be from actual invoice date 

### Module

selling

### Version

ERPNext: v14.27.8 (HEAD)

Frappe Framework: v14.39.0 (HEAD)

Frappe HR: v14.4.3 (HEAD)

Journeys: v0.0.1 (HEAD)

### Installation method

None

**Comment by Nihantra-Patel** [comment]
Hi @hroperators,

The Due Date or Payment Due Date in ERPNext is determined by the posting date of a sales invoice. If you manually change the Payment Due Date and save it, the system will reset it or automatically set it based on the payment term template. This design caters to the preferences of users and clients. If you wish to modify this functionality, you can develop a custom app. Alternatively, if you encounter a functionality issue and have a solution, you can submit a Pull Request on GitHub to contribute. If you encounter an actual bug, please share a video demonstrating the entire process.

Thank You!
