### ISSUE TITLE
Unable to create multiple Item Variants

### ISSUE THREAD

**Issue by Donferarri92** [frappe/erpnext#35822]
### Information about bug

When I click Create >>> Multiple Variants on a template item, I select the Variants parameters. 

Expected: Variants should be created.
Actual: Variant creation has been queued.

![image](https://github.com/frappe/erpnext/assets/90032072/0384642e-164c-4613-9fc1-93acb6cc8953)

Not able to find this queue and Variants are not created.

### Module

stock

### Version

Frappe Version: v14.39.0 (HEAD)
ERPNext Version: v14.27.8 (HEAD)

### Installation method

FrappeCloud

**Comment by Donferarri92** [comment]
Anyone, kindly attend this bug.

**Comment by s-aga-r** [comment]
@Donferarri92 The Item Variants creation will be enqueued if there are 10 or more variants, they will be created via Background Jobs / RQ Job. The job will also be visible in RQ Job DocType with status, let us know if it's getting failed.

ref: https://github.com/s-aga-r/erpnext/blob/9d27a25e5f2335386402f96f83a10729695b20c8/erpnext/controllers/item_variant.py#L214-L234

![image](https://github.com/frappe/erpnext/assets/63660334/6c477a90-a0be-4255-9481-eacc379006a8)

**Comment by Donferarri92** [comment]
@s-aga-r   Today a strange thing started happening. As soon as I click on Multiple Variants, the browser is crashing. tried in every browser possible. Something is not right. 

It shows erro code: SIGILL

![image](https://github.com/frappe/erpnext/assets/90032072/6bb77dbb-d9eb-4512-9311-8155ab28e680)

**Comment by s-aga-r** [comment]
@Donferarri92 That looks like a separate thing: https://www.reddit.com/r/chromeos/comments/rg1kqq/error_codesigill/

**Comment by Donferarri92** [comment]
@s-aga-r I found the reason also for this. My Scenario.

1. I have 1 template item with 2 Variant attributes assigned to it. 1 Variant attribute is Quality which has 16 Attributes. and other Variant Attribute as Pack sizes having 10 Attributes.
So for this item when I click on Create >> Multiple variants, the browser crashes.

For other Item I checked, with just 1 Variant Atrribute, I am able to go beyond Create >>>> Multiple Variants and can see the variant selection wizard.

Attaching a video for your ref.

I need to refresh as browser freezes/crashes. This is in a case where I have more attributes.


[Screencast from 29-06-23 06:41:50 PM IST.webm](https://github.com/frappe/erpnext/assets/90032072/ad44f1c9-076e-4c6c-812c-621da01f8542)

In below video you can see I opened another item and Multiple variants wizard appears.

**Comment by Donferarri92** [comment]
@s-aga-r  kindly look into this and reopen. If there are multiple variant attributes...... the code is crashing.

**Comment by s-aga-r** [comment]
@Donferarri92 Make sure you don't have any customizations for the item master since the issue is not replicable.

**Comment by Donferarri92** [comment]
Yes there isnt any customization in Item master. Problem appears when we have more than 15 Attribute Values. Example,
Item Attributes: Quality and Size.
Quality having 15+ Attribute Values and Size having 5+ values.

Now when we try creating multiple variants, the code crashes.

**Comment by s-aga-r** [comment]
@Donferarri92 No. of variants can't be the reason here, we have other users who have 100+ attribute values.
