### ISSUE TITLE
POS Invoice Total Amount in the POS Closing Entry

### ISSUE THREAD

**Issue by EkasaTech** [frappe/erpnext#35823]
### Information about bug

Trying to create POS Invoice for total amount $500, and payment is $300. The status is "Unpaid" but when this invoice is trying to be consolidated in POS Closing Entry, the total amount showing $500. 

### Module

accounts, selling

### Version

Frappe Framework: v14.32.0 (version-14)
ERPNext: v14.21.0 (version-14)

### Installation method

manual install

**Comment by RitvikSardana** [comment]
Fixed in develop branch
