### ISSUE TITLE
Sales / Purchase Return enhancements

### ISSUE THREAD

**Issue by bohlian** [frappe/erpnext#3582]
To have Credit and Debit Notes as a separate DocType that includes Item Information and can be subjected to Tax. The Credit and Debit Notes can also have a reference back to a related Purchase or Sales Invoice. 

Once submitted, Journal Vouchers may be posted against these Credit and Debit Notes.

**Comment by rmehta** [comment]
@bohlian We had a discussion and we think that a negative value invoice will be the best solution.

Maintaining duplicate structures is expensive and will create problems in the long run. We need to remove some validations and do a lot of testing to make sure this works. Estimate is 4 billable hours. Does that work for you? We can finish this week.

**Comment by bohlian** [comment]
@rmehta We have a few queries regarding the negative value Invoice function for Credit Note (CN) and Debit Note (DN) processing.

1. Which screen will be used to access the negative Invoice function? Will it be the Sales Invoice/Purchase Invoice screen or a new screen? We would prefer a new screen specifically to process CN and DN transactions.

2. Will the negative Invoice act as a CN? If yes, will we be processing a DN as a type of Sales Invoice or Purchase Invoice? Do note that a CN and DN can be applied to both Sales Invoices and Purchase Invoices.

3. The negative Invoice function should be able to manage the following business scenarios:
(a) Price Adjustments
In this scenario, we have billed the Customer with the wrong price (over/under-billed). Hence, a CN or DN is required for a price adjustment. The CN or DN should be created with reference to a preceding Sales Invoice document and Item data (e.g. quantity, selling price, tax charges, discounts, etc.) should be copied over. The same concept applies for CN or DN created with reference to Purchase Invoice documents.
(b) Stock Returns
In this scenario, the Customer returns the stock to us due to product defects or over-delivery for instance. 
i. The existing Sales Return function allows us to create some form of a Return Delivery Note with reference to a preceding Delivery Note or Sales Invoice. However, Customer and Item information is not copied over to the Sales Return document from the reference document (there is an error currently, we will report this as a separate issue). Can this function be enhanced?
ii. There is a subsequent Make Credit Note function available upon submission of the Sales Return document. Can this subsequent Make Credit Note function be linked to the negative Invoice screen instead of the Journal Voucher CN screen?
iii. If the negative Invoice can be created and linked to a Sales Return document, can the Customer and Item information (e.g. return quantity, selling price, tax charges, discounts, etc.) be retrieved from the original Sales Invoice (entered as reference in the Sales Return screen) and also the Sales Return document itself? 
The same concept should apply in the purchasing process for Purchase Returns.

4. We assume that in the CN/DN screen, tax charges templates should be available as well. Please confirm this. We have to be able to change the tax charges template in the CN/DN to be different from the reference Sales Invoice/Purchase Invoice where necessary - depending on the situation, the tax amount may take a negative value.

5. Can the print format be specific to a CN/DN rather than a Sales Invoice/Purchase Invoice? The CN/DN printout should contain the item details as well, similar to a Sales Invoice/Purchase Invoice (e.g. quantity, list price, discounts, item description, etc.).

**Comment by nabinhait** [comment]
@bohlian please check my comments below:

1. Sales /Purchase Invoice screen will be used for both Invoice and CN/DN. There will be a select field "Document Type" with option for normal Invoice and Credit /Debit Note. And the item quantity will be defined as negative.

2. Credit Note (negative Sales Invoice) can be made against a Delivery Note or Sales Invoice. There will be a link field to select original invoice or delivery note.

3.
a) Price Adjustments: In Credit Note, all items will be fetched from linked DN / original SI. But you will be able to delete a item / modify item details like qty / rate in the CN.

b) Stock Returns: There will be no separate form/entry for stock returns, like existing Stock Entry form. There will be some options in Credit Note itself, to define the purpose of Credit Note, whether the entry is only for returning stock or price adjustment or both. In case of returning stock, on submission of credit note, item will be returned to associated warehouse automatically.

4. Taxes and charges table in CN/DN will be fetched automatically from linked DN / SI, but will be available for change. Negative taxes can also be entered.

5. There will be separate print format for CN / DN and it will contain item / tax details wherever applicable.

**Comment by bohlian** [comment]
@nabinhait just a few more questions. Thank you. 

1) We just want to double confirm that a CN or a DN can be created against a Sales Invoice. Similarly, a CN or a DN can be created against a Purchase Invoice.

2) Can we have different Naming Series for CN / DN that is different from the Invoices?

3) Can this be merged into master?

4) Will the CN / DN processing be integrated to Accounting Ledger and Stock Ledger posting?

5) For payment purposes, will the CN / DN be then linked to a Journal Voucher of CN and DN type? - Similar to how payment for a Sales Invoice or Purchase Invoice is settled?

**Comment by nabinhait** [comment]
@bohlian Yes, all the 5 points will be covered

**Comment by robertbecht** [comment]
Further to this: My accounts are a bit less formal. Rarely use CN/DN 's.
If a customer brings back an item I used to write in invoice with negative quantity and account=cash
Simple.
This functionality to enter a negative quantity in a sales invoice has been removed from v5.
Will it come back. Would be great.
robert

**Comment by rmehta** [comment]
@robertbecht yes that is exactly what are are proposing

**Comment by nabinhait** [comment]
@bohlian Stuck in fixing some old buggy logic related to purchase return. Currently system does not return the items with original purchase receipt rate it came with, it considers rate based on FIFO. It needs to be fixed to implement Purchase Receipt with negative quantity (Purchase Return). Thats why we are getting late to complete this feature.

**Comment by bohlian** [comment]
@nabinhait no worries, it is understandable. Am sure all of us would rather have something complete as opposed to a half baked solution. Many thanks for the effort.

**Comment by nabinhait** [comment]
@bohlian Yesterday we have released the sales/purchase return enhancement. Please pull the updates and check.

**Comment by bohlian** [comment]
@nabinhait Apologies for the late response on this, we have just tested the enhancement and have identified several issues:-

1. A select field "Document Type" with options for normal Invoice, Credit Note and Debit Note is not available. 

2. There are no options in the Credit Note or Debit Note itself, to define the purpose of the transaction, whether the entry is for stock return, price adjustments etc. A select field "Order Reason" should be made available to manage this as most businesses would need this information for reporting purposes.

3. There is no function to allow Sales Debit Note to be created from a Sales Invoice. Likewise, there is also no function to allow Purchase Credit Note to be created from a Purchase Invoice.

4. Sales Credit Note and Purchase Debit Note (complete with item details) cannot be created independently without reference to any preceding Invoice documents. This could be necessary for certain business scenarios.

5. Journal Entry to record payment for Sales Credit Note (Return Sales Invoice) to Customer cannot be created from the Sales Credit Note itself. It has to be done via the original Sales Invoice ("payment" function). As a result, the reference document number in the Journal Entry is set as the original Sales Invoice number instead of the Sales Credit Note number. Can the "payment" function be made available in the Return Sales Invoice screen?

6. Somewhat similar to Issue (5), the Journal Entry to record payment for Purchase Debit Note (Return Purchase Invoice) to Supplier cannot be created from any preceding documents. It has to be done directly in the Journal Entry screen. This makes the process very manual as the user has to enter the Purchase Debit Note and amount to be posted in the Journal Entry. Can the "payment" function be made available in the Return Purchase Invoice screen?

7. The system auto proposes the voucher type as a Bank Entry instead of a Credit Note or Debit Note during the Journal Entry processing for returns.

8. A separate print format for Credit Note or Debit Note containing item and tax details wherever applicable is not available.

Appreciate your help on this. Thanks.

**Comment by nabinhait** [comment]
@bohlian Please check replies inline:

> A select field "Document Type" with options for normal Invoice, Credit Note and Debit Note is not available.

"Is Return" field does the job, still if you need it for printing or other purpose, create a custom field.

>There are no options in the Credit Note or Debit Note itself, to define the purpose of the transaction, whether the entry is for stock return, price adjustments etc. A select field "Order Reason" should be made available to manage this as most businesses would need this information for reporting purposes.

You can track the purpose using "Remarks" field.

> There is no function to allow Sales Debit Note to be created from a Sales Invoice. Likewise, there is also no function to allow Purchase Credit Note to be created from a Purchase Invoice.

What is the purpose of Sales Debit Note, for pricing adjustment? Is it not similar to a fresh invoice?

> Sales Credit Note and Purchase Debit Note (complete with item details) cannot be created independently without reference to any preceding Invoice documents. This could be necessary for certain business scenarios.

What is the use case? Though difficult to implement.

> Journal Entry to record payment for Sales Credit Note (Return Sales Invoice) to Customer cannot be created from the Sales Credit Note itself. It has to be done via the original Sales Invoice ("payment" function). As a result, the reference document number in the Journal Entry is set as the original Sales Invoice number instead of the Sales Credit Note number. Can the "payment" function be made available in the Return Sales Invoice screen?

Create a github issue for the improvement #3951 

> Somewhat similar to Issue (5), the Journal Entry to record payment for Purchase Debit Note (Return Purchase Invoice) to Supplier cannot be created from any preceding documents. It has to be done directly in the Journal Entry screen. This makes the process very manual as the user has to enter the Purchase Debit Note and amount to be posted in the Journal Entry. Can the "payment" function be made available in the Return Purchase Invoice screen?

Create a github issue for the improvement #3951 

> The system auto proposes the voucher type as a Bank Entry instead of a Credit Note or Debit Note during the Journal Entry processing for returns.

I think it should be Bank Entry only. Credit Note is there, if you want to create Credit Note directly from Journal Entry.

> A separate print format for Credit Note or Debit Note containing item and tax details wherever applicable is not available.

In today's release, we have removed "Credit Note - Negative Invoice" print format. Instead, created two "Print Heading" records for Credit Note and Debit Note. On creation of return invoice, print heading will be set to Credit Note automatically. And then you can simply use standard print format for printing Credit Note.

**Comment by bohlian** [comment]
@nabinhait Kindly refer to my response (tagged <BL>) below:

1. A select field "Document Type" with options for normal Invoice, Credit Note and Debit Note is not available.

"Is Return" field does the job, still if you need it for printing or other purpose, create a custom field.
<BL> The objective of having this field is to allow the system to auto-propose the naming series selection based on the document type. Right now, the default naming series is "SINV-" regardless of the document type. This causes room for data discrepancies as the users might select the wrong series during creation of a billing document. Can you provide a better solution for this?


2. There are no options in the Credit Note or Debit Note itself, to define the purpose of the transaction, whether the entry is for stock return, price adjustments etc. A select field "Order Reason" should be made available to manage this as most businesses would need this information for reporting purposes.

You can track the purpose using "Remarks" field.
<BL> OK


3. There is no function to allow Sales Debit Note to be created from a Sales Invoice. Likewise, there is also no function to allow Purchase Credit Note to be created from a Purchase Invoice.

What is the purpose of Sales Debit Note, for pricing adjustment? Is it not similar to a fresh invoice?
<BL> Yes, it is mostly for pricing adjustments. The purpose of creating a Sales Debit Note and Purchase Credit Note with reference to a preceding Invoice document is to provide a link in the entire document flow processing for tracking purposes. This cannot be considered as a fresh Invoice.


4. Sales Credit Note and Purchase Debit Note (complete with item details) cannot be created independently without reference to any preceding Invoice documents. This could be necessary for certain business scenarios.

What is the use case? Though difficult to implement.
<BL> These documents will usually be used for rebates whereby a bulk rebate is given if the sales volume exceeds a certain quantity or amount. This business case is applicable in both Selling and Buying modules.


5. Journal Entry to record payment for Sales Credit Note (Return Sales Invoice) to Customer cannot be created from the Sales Credit Note itself. It has to be done via the original Sales Invoice ("payment" function). As a result, the reference document number in the Journal Entry is set as the original Sales Invoice number instead of the Sales Credit Note number. Can the "payment" function be made available in the Return Sales Invoice screen?

Create a github issue for the improvement #3951 
<BL> OK


6. Somewhat similar to Issue (5), the Journal Entry to record payment for Purchase Debit Note (Return Purchase Invoice) to Supplier cannot be created from any preceding documents. It has to be done directly in the Journal Entry screen. This makes the process very manual as the user has to enter the Purchase Debit Note and amount to be posted in the Journal Entry. Can the "payment" function be made available in the Return Purchase Invoice screen?

Create a github issue for the improvement #3951 
<BL> OK


7. The system auto proposes the voucher type as a Bank Entry instead of a Credit Note or Debit Note during the Journal Entry processing for returns.

I think it should be Bank Entry only. Credit Note is there, if you want to create Credit Note directly from Journal Entry.
<BL> OK


8. A separate print format for Credit Note or Debit Note containing item and tax details wherever applicable is not available.

In today's release, we have removed "Credit Note - Negative Invoice" print format. Instead, created two "Print Heading" records for Credit Note and Debit Note. On creation of return invoice, print heading will be set to Credit Note automatically. And then you can simply use standard print format for printing Credit Note.
<BL> OK
