### ISSUE TITLE
After a "Go Back" in browser : Item Not Showing in Quick Entry of Batch Creation from Batch No. Field in Stock Entry Detail

### ISSUE THREAD

**Issue by FHenry** [frappe/erpnext#35841]
### Information about bug

Create an Item with "Has Batch No"
Create a stock entry
click to create a Batch number, the first time the item is correctly fill.
Go back with your browser arrow to go on item page
retry , this time the Item field in quick Entry create batch  is empty

https://github.com/frappe/erpnext/assets/1050053/71a05b99-f0b1-47d0-b613-a7aa3b3df685

### Module

stock

### Version

Frappe and ERPNext version 13 and version 14

### Installation method

None

**Comment by s-aga-r** [comment]
@FHenry This should be resolved in https://github.com/frappe/erpnext/pull/35743 (v14.27.9). Please update your instance and retry.

Closing this, re-open if not fixed after the update.

**Comment by FHenry** [comment]
@s-aga-r When I open this issue you'r PR that's I've check was already merge, I git it a try with frappe v14.27.12 and the bug is still here.
The problem is more deeper than just a route, it happens only when you use "Previous page" from your browser, it's like in the deep JS (vue js, or other) the state is remove.

I already try to find where it come from, as this bug occurs at least since version-13. but when I find it can be related to awesomplete, I can't find more relevant information

I can't re-open the issue could you do it ?

**Comment by s-aga-r** [comment]
@FHenry If that's the case then this should also be happening with other doctypes. Could you try with other doctypes?

**Comment by FHenry** [comment]
@s-aga-r you in mind other just frappe doctype (or in ERPNext,I don't knowotherDoctype exemple that work like that,that's can explain this bug is unknown) another that have this feature? A quick entry with a link on an element of the source doctype?

**Comment by FHenry** [comment]
@s-aga-r I've made a sample app with simple feature like so Item Batch stuff
https://github.com/FHenry/erpnext_my_sample_project.git

And here it work even with the "Previous page" browser.

So I have to come from other part specifics of Batch Doctype of Stock entry Doctype I continue to dig

**Comment by FHenry** [comment]
@s-aga-r 

The fact is the "setup"(https://github.com/frappe/erpnext/blob/29ea5cfc213a15fa98fa9ba0b9e08fb474a68969/erpnext/stock/doctype/stock_entry/stock_entry.js#L9) JS method of Stock Entry is **not triggers** after the previous page button so 

https://github.com/frappe/erpnext/blob/29ea5cfc213a15fa98fa9ba0b9e08fb474a68969/erpnext/stock/doctype/stock_entry/stock_entry.js#L104 
is executed and so 

https://github.com/frappe/frappe/blob/74633305c154f0b3df3f50d5cb0f1b64415f1bf2/frappe/public/js/frappe/form/controls/link.js#L162

is not run 


https://github.com/frappe/erpnext/assets/1050053/b28ce540-7fd6-4421-9621-41ed343c6339

**Comment by s-aga-r** [comment]
@FHenry sending PR?

**Comment by FHenry** [comment]
@s-aga-r I would like but I don't understand why setup JS is not launched the second time... If you find I'm curious

**Comment by s-aga-r** [comment]
> @s-aga-r I would like but I don't understand why setup JS is not launched the second time... If you find I'm curious

@FHenry `setup` didn't get run every time ig since the page got cached. Try moving the Items Batch `set_query` to `refresh`. If it works then raise a PR for version-14-hotfix as v15 has Serial and Batch Bundle. 

Edit:
Fix this in FW otherwise, you will end up moving `set_query` to `refresh`.

**Comment by FHenry** [comment]
@s-aga-r Thank's for the hints. I've been able to apply your suggestion and it works.

Edit :
PS : What does it mean "FW" ?

**Comment by s-aga-r** [comment]
> @s-aga-r Thank's for the hints. I've been able to apply your suggestion and it works.
> 
> Edit : PS : What does it mean "FW" ?

FW => FrameWork => Frappe Framework

All the set queries are written in setup, what about others? 
>> https://github.com/frappe/erpnext/issues/35841#issuecomment-1718714557, Fix this in FW otherwise, you will end up moving set_query to refresh.

**Comment by FHenry** [comment]
Because others set_query do not make a get_route_options_for_new_doc

**Comment by FHenry** [comment]
Other place in ERPNext where get_route_options_for_new_doc is called is in onload() event, so I think it was the only here where this bug can occurs (as I see read in the documentation onload() is executed each time not like setup())

**Comment by s-aga-r** [comment]
> Other place in ERPNext where get_route_options_for_new_doc is called is in onload() event, so I think it was the only here where this bug can occurs (as I see read in the documentation onload() is executed each time not like setup())

@FHenry then let's move all the `get_route_options_for_new_doc` to onload, and add commits in existing PRs.

ex. Asset Repair, Job Card, Transaction js etc.

**Comment by FHenry** [comment]
For #37092 (version-14-hotfix)
project.js : already in `onload()` => OK
job_card.js : already in` setup_quality_inspection: function(frm)` call by `refresh()` => OK
transaction.js (1): KO, I've misscheck first time, it was in `setup()`, I've move them to `onload()` (and remove duplicate code)  => OK with the PR
transaction.js (2): already in `setup_quality_inspection: function(frm)` call by `refresh()` => OK
subcontracting_receipt.js: already in `refresh()` => OK

Asset Repair ? Are you on branch version-14 ? No `get_route_options_for_new_doc` in erpnext/assets/doctype/asset_repair/asset_repair.js
Edit : Ok It is in develop


For #37096 (develop)
stock_entry.js : in `setup_quality_inspection: function(frm)` call by `refresh()` => OK
transaction.js (1): KO it was in setup, I've move them to `onload()` (and remove duplicate code) => OK with the PR
transcation.js (2): in `setup_quality_inspection()` call in `refresh()` => OK
asset_repair.js : KO it was in setup, I've move them to `refresh()` => OK with this PR
job_card.js (1)  : KO it was in setup, I've move them to `refresh()` => OK with this PR
job_card.js (2) : already in` setup_quality_inspection: function(frm)` call by `refresh()`=> OK
quotation.js : KO it was in setup, I've move them to `refresh()` => OK with this PR
stock_reconciliation.js : already in `onload()` => OK
asset_capitalization.js : already in `setup_queries()` call by `onload()`
project.js : already in `onload()` => OK
installation_note.js : KO it was in setup, I've move them to `onload()` => OK with this PR
pick_list.js :  KO it was in setup, I've move them to `refresh()` => OK with this PR
subcontracting_receipt.js: KO in in `set_queries:` in `setup()`, I've move `frm.trigger('set_queries');`  to `refresh()` => OK with this PR

**Comment by s-aga-r** [comment]
@FHenry did some changes in https://github.com/frappe/erpnext/pull/37096 and https://github.com/frappe/erpnext/pull/37092, could you check once in your local?

**Comment by FHenry** [comment]
I've check and it's ok
