### ISSUE TITLE
Purchase Order to Material Request Link

### ISSUE THREAD

**Issue by ruchin78** [frappe/erpnext#3586]
In central Purchasing where every dept. raises Material Request for Purchase.

Now say for item X:

Material Request for Item    Dept.                 Qty.
X                                       Production1       10
X                                       Spares              10
X                                       Production2       12

And the MOQ for item X is 100.

Now, when the Purchaser will raise the Purchase Order for item X.
He will need to enter one more row to fulfill the MOQ Requirement,
Now, finally in the Purchase Order, Item X will be having 4 Rows.
IS IT THE RIGHT WAY TO RAISE PURCHASE ORDER?

**Comment by rmehta** [comment]
Might have to rework the Purchase Order / Material Request link for this. Not an easy fix. Can you sponsor?

**Comment by ruchin78** [comment]
Sorry, no from my side. It is just a suggestion for enhancement because as a standard functionality it is shown in one line and the the details are in the detail section where we can find the Material Request Number/Supplier Quotation Number (if any) and then the required qty and the required date and in the po line the total qty. will be shown in one line.

**Comment by kennethsequeira** [comment]
Closing this as it can be managed with MOQ and default purchase UOM set in the item. 

Whenever MOQ is available, the system raises Material Request for MOQ.
