### ISSUE TITLE
Feature Request:  Customizable list view 

### ISSUE THREAD

**Issue by cgpurbaugh** [frappe/erpnext#3587]
In the Sales Order, Purchase Order, etc. views, it would be nice to be able to modify the columns, such as adding the % delivered column.

**Comment by jof2jc** [comment]
It will be nice +1

**Comment by acumensec** [comment]
+1

**Comment by rmehta** [comment]
Some columns are configurable via the In List View setting in Customize DocType. But the biggest problem is space availability.

**Comment by cgpurbaugh** [comment]
rmehta, where is the code for this list?  I'd like to take a look at it.  

How about the option for each order taking up 2 lines, so that additional information can be displayed?  

Another Idea:  When you resize the browser, certain information goes away.  If we could do the opposite of this (I have about 4 inches on either side of my  screen that could be utilized) then we could get alot more information on there.

**Comment by rmehta** [comment]
This is not as easy as it looks.

2 lines is a bad idea. What is your use case, is there any important information that is being missed?

**Comment by cgpurbaugh** [comment]
2 lines is already the case when viewed in tablet mode.  I talked to Umair on skype this morning, he saw what was going on.

**Comment by hellojalex** [comment]
perhaps we can configure to remove the other fields?
example for opportunity list, we can replace the ID and timestamp with other fields

**Comment by strixaluco** [comment]
As was discussed in the forum https://discuss.erpnext.com/t/how-to-create-filter-link-in-side-bar/13870, this is a very useful feature for us. Is it possible to implement it?

**Comment by fasilkaks** [comment]
+1 here. Its a really important feature. For eg. In the sales invoice list, it would be great to show the total invoice amount and the outstanding amount in the list. Editable/Customizable list view is really needed.

**Comment by Devens** [comment]
I agree that ERPNext needs to work in List View. A better list view utility can not only eliminate requirement of many reports, but, it can be very useful even as a  user specific Dashboard. I am sharing very useful List View from one of very renowned SAAS ERP/CRM company Zoho. 

https://docs.google.com/document/d/1qgv3P33EAktYbBVYNGkKN4K0hMHPGQcDxG3gsB4v7Xc/edit#
