### ISSUE TITLE
Feature request: Assign to more than 1 user simultaneously 

### ISSUE THREAD

**Issue by cgpurbaugh** [frappe/erpnext#3588]
It would be nice to be able to assign orders to several people, for example we have orders that require several departments to work together, and it would be good to have each department manager assigned to the order.

**Comment by cgpurbaugh** [comment]
@rmehta any progress on this?  I know this was on V4, and somehow got lost in V5.  Could this be an easy fix?

**Comment by anandpdoshi** [comment]
We are planning to merge assign and share. But there's no timeline.
