### ISSUE TITLE
Cut-off Screen for Messages

### ISSUE THREAD

**Issue by justinlusg** [frappe/erpnext#3589]
The screen is cut-off in the middle on phones and when the browser is resized.

![image](https://cloud.githubusercontent.com/assets/12539216/8537984/b20510f8-2498-11e5-9251-905bbf83d16a.png)

![img-20150701-wa0002](https://cloud.githubusercontent.com/assets/12539216/8537985/b521399c-2498-11e5-9ecc-9b2ba32f5df8.jpg)

![img-20150701-wa0005](https://cloud.githubusercontent.com/assets/12539216/8537986/b54b8a1c-2498-11e5-9df4-951ee9f773a8.jpg)

**Comment by neilLasrado** [comment]
Looks like fixed. Could not replicate.

**Comment by cgpurbaugh** [comment]
Same here, at least on android.  This should probably be closed.
