### ISSUE TITLE
Can't create new versions of BOMs

### ISSUE THREAD

**Issue by MartinFulgueiras** [frappe/erpnext#35892]
### Information about bug

Installed Apps
ERPNext: v14.0.0-beta.5
Frappe Framework: v14.0.0-beta.6
frappecloud
no bench

Hi, i can't create new versions of BOMs in the manufacturing module. Everytime i click on New Version and then want to save, the message appears and can't proceed:
![image](https://github.com/frappe/erpnext/assets/32270312/f86b4c6a-a5e8-4b8f-a9fe-5da9c7f7a49e)

At the beginning it was the same message but for Item_name, but changed the Naming configuration in customization of Doctype and it solved that, but then this new problem appeared.

I have already unchecked the Unique option in Doctype configuration:
![image](https://github.com/frappe/erpnext/assets/32270312/dead8b07-9f1e-4a2f-907e-d053f0f15d42)

![image](https://github.com/frappe/erpnext/assets/32270312/59162597-164b-4ec0-acce-cb6bfdcafb88)

![image](https://github.com/frappe/erpnext/assets/32270312/3036ae13-b297-41e7-aa25-4c15ad127cbb)
(I've been trying changing the Naming in the customize section as this solved the previous issue, but to no avail. This image is just an example)

I'm starting to believe this is a bug of some sorts. 

Regards and thanks for any help

Martín

### Module

manufacturing

### Version

Frappe Version - v14.0.0-beta.5
ERPNext Version - v14.0.0-beta.6
Installed on frappecloud

### Installation method

FrappeCloud

**Comment by rohitwaghchaure** [comment]
@MartinFulgueiras You have disabled the Unique property for the item but it seems that the property has still there in the database for the column item. You need to drop the Unique constraint from the item column for the tabBOM table.

**Comment by MartinFulgueiras** [comment]
Thanks. Also noticed my version is very old. Regards.

**Comment by MartinFulgueiras** [comment]
Issue got solved with version update. Regards
