### ISSUE TITLE
Subcontracting Issue

### ISSUE THREAD

**Issue by precihole** [frappe/erpnext#35898]
### Information about bug

1) Create Subcontracting Order of qty 50.
2) Create two Subcontracting Receipts of 10 and 20 qty from subcontracting order.
3) Create Return of Components for remaining qty of 10 of 20. (**Then Subcontracting Order status is Closed**)
4) Create Subcontracting Receipt of remaining 10 qty from Subcontracting Order but it is not allowing to Create. 
**(Button not showing in Subcontracting Order to create Subcontracting Receipt)**
@rohitwaghchaure

### Module

buying

### Version

ERPNext: v14.27.8 (HEAD)
Frappe Framework: v14.39.0 (HEAD)

### Installation method

FrappeCloud

**Comment by s-aga-r** [comment]
Closing this one, https://github.com/frappe/erpnext/issues/35864
