### ISSUE TITLE
AR Report Server Error 'Meta' object has no attribute 'permissions'

### ISSUE THREAD

**Issue by barathprathosh** [frappe/erpnext#35906]
### Information about bug

While Open Account Receivable Report after selecting Customer using filters Server Error **'Meta' object has no attribute 'permissions'** pop-up

![accounts_receivable](https://github.com/frappe/erpnext/assets/48587404/d8f28cd4-e529-4502-9501-640d7a6f858b)

i checked the Account Receivable Report JS file get_value **Customer Credit Limit** child table raise the Issue. if i remove the Line No : 55 to 60 code then it working fine, i don't know why it raise the issue. may be because of read Replica Database or not..?

![Screenshot from 2023-06-27 17-55-02](https://github.com/frappe/erpnext/assets/48587404/7e2f8b09-e3a2-4e6b-9df1-7fdb6fc28a84)

**Console Log:**
**Errprint statement data:**

request.js:428 {'doctype': 'Customer', 'fields': ['tax_id', 'customer_name', 'payment_terms'], 'filters': {'name': '#0003 WAL-MART'}, 'or_filters': None, 'order_by': None, 'limit_start': None, 'limit_page_length': 1, 'debug': False, 'as_list': False, 'save_user_settings': True}

request.js:428 {'doctype': 'Customer Credit Limit', 'fields': ['credit_limit'], 'filters': {'parent': '#0003 WAL-MART'}, 'or_filters': None, 'order_by': None, 'limit_start': None, 'limit_page_length': 1, 'debug': False, 'as_list': False, 'save_user_settings': True}

request.js:428 data.doctype
request.js:428 Customer Credit Limit
request.js:428 Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 38, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 76, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1473, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/client.py", line 127, in get_value
    value = get_list(
  File "apps/frappe/frappe/client.py", line 62, in get_list
    validate_args(args)
  File "apps/frappe/frappe/desk/reportview.py", line 83, in validate_args
    validate_fields(data)
  File "apps/frappe/frappe/desk/reportview.py", line 120, in validate_fields
    if df.get("permlevel") not in meta.get_permlevel_access(parenttype=data.doctype):
  File "apps/frappe/frappe/model/meta.py", line 522, in get_permlevel_access
    for perm in self.get_permissions(parenttype):
  File "apps/frappe/frappe/model/meta.py", line 532, in get_permissions
    permissions = frappe.get_meta(parenttype).permissions
AttributeError: 'Meta' object has no attribute 'permissions'

### Module

selling

### Version

ERPNext: v13.49.10 (version-13)
Frappe Framework: v13.51.3 (version-13)

### Installation method

manual install

**Comment by deepeshgarg007** [comment]
@barathprathosh The error seems to be irreproducible. Please add more steps and then reopen the issue
