### ISSUE TITLE
Stock ledger Previous transaction Qty Balance not getting fetched as opening balance for new transaction 

### ISSUE THREAD

**Issue by Amapolley** [frappe/erpnext#35903]
### Information about bug

#34670 
I took backup of current site and restored it in a test environment then i updated the new site to latest version just to check 
if issue will be fixed but issue still exist

If you check given screenshot the stock ledger previous balance is not getting carry forward to the next transaction as opening when you check the last but 2 rows in below screenshot. 

Is the solution you gave in PR 34670 meant to to prevent the issue from occurring or it will solved existing issue for report to correct so do i need to correct existing issue manually via stock reconciliation and believe that it won't re-occur

![stock ledger previous qty balance not carry forward to new trans  as opening](https://github.com/frappe/erpnext/assets/106424868/863521bd-f1a0-48f4-8620-7b61c0a2c930)

### Module

stock

### Version

ERPNext: v14.27.12
Frappe Framework: v14.40.0

![stock ledger previous qty balance not carry forward to new trans  as opening](https://github.com/frappe/erpnext/assets/106424868/f6c4ee4d-cc76-4a85-a43d-9878c44995e9)

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
Hi @Amapolley,

Opening quantity will be displayed in the Stock Balance report, not in the stock ledger report. Any changes made to the stock ledger report are due to the absence of issues in the latest version 14. Please verify with the latest version.

Thank You!
