### ISSUE TITLE
"Exchange Rate is mandatory" error

### ISSUE THREAD

**Issue by ekpaxp** [frappe/erpnext#3590]
Hi, after an update this morning on our development system, the following error now appears when trying to add an Item to a new Sales Order:-
"Exchange Rate is mandatory. Maybe Currency Exchange record is not created for SGD to SGD"
Once the error pop-up is closed, the "Item Name" & "Item Description" have to be manually entered before the row can be saved.

**Comment by ekpaxp** [comment]
Is this possibly due to the 5.1.3 update that included the automatic rates from fixer.io?   If so, where to setup the mechanism for the rate updates?  Thanks

**Comment by nabinhait** [comment]
Can't replicate the issue. It can be due to some other syntax error  in sales order. are you getting any error in the console?

**Comment by ekpaxp** [comment]
Strange, because it is happening in the development server as well as the test server - both of which were updated this morning.  Is there a way to check the SGD-SGD exchange record as it cannot be created manually?

**Comment by ekpaxp** [comment]
With the implementation of fixer.io, is there a need to setup the exchange rates manually?

**Comment by ekpaxp** [comment]
Hi Nabin,  it looks like the issue was to do with the Fiscal Year.  Even though I was creating a SO dated in the last fiscal year as setup during the install (ending 30 June 2015), the SO had the error.  Once I created a new Fiscal Year which covers the current date then the error does not appear when creating an Item in the SO.

**Comment by nabinhait** [comment]
Is it fixed now? Otherwise, you can try to debug using print in following function. And there are no configuration needed to fetch exchange rate, by default it fetches from fixer.io.

https://github.com/frappe/erpnext/blob/develop/erpnext/setup/utils.py#L62

**Comment by ekpaxp** [comment]
Looks like it's OK now - just have to remember to make sure the system has a current Fiscal Year setup.  Many thanks
