### ISSUE TITLE
POS Closing Entry:Change amount is showing under card transaction

### ISSUE THREAD

**Issue by ravi854** [frappe/erpnext#35932]
### Information about bug

When closing the POS the Change amount is showing under card transaction.

https://github.com/frappe/erpnext/assets/85276497/d21797fa-e81d-49d1-b0e8-7a4fbc3da649

[POS-CLO-2023-00250.pdf](https://github.com/frappe/erpnext/files/11903576/POS-CLO-2023-00250.pdf)

### Module

accounts

### Version

Frappe Version : 14.40.1
Erpnext Version: 14:28

### Installation method

manual install

**Comment by RitvikSardana** [comment]
It is fixed in develop branch
