### ISSUE TITLE
Mode Of Payment on Sales report

### ISSUE THREAD

**Issue by jof2jc** [frappe/erpnext#3593]
Hi,

It's useful to add filter for Mode Of Payment on Sales Reports. It;s very basic but very useful for many businesses.

Tks

**Comment by rmehta** [comment]
Which reports?

**Comment by jof2jc** [comment]
sales register report
On Jul 13, 2015 12:57 PM, "Rushabh Mehta" <notifications@github.com> wrote:

Which reports?

—
Reply to this email directly or view it on GitHub
<https://github.com/frappe/erpnext/issues/3593#issuecomment-120823250>.

**Comment by RogueF** [comment]
Hi,

I am very interested in this feature as well. Has there been any progress made on it? 

Thanks

**Comment by nabinhait** [comment]
Added via https://github.com/frappe/erpnext/pull/5328
