### ISSUE TITLE
Can not Cancel/Delete Asset Depreciation Voucher

### ISSUE THREAD

**Issue by nitin-anantpranali** [frappe/erpnext#35934]
### Information about bug

Circular Referencing Issue

System is passing the Depreciation Automatically in Journal Entry. 
But we can not cancel/delete the Journal Entries. It gives Message stating that Asset Exists.

And if we can not cancel/delete the Assets. It gives Message stating that Journal Entries Exists.

### Module

accounts

### Version

ERPNext: v14.27.9 (HEAD)
Frappe Framework: v14.40.0 (HEAD)
India Compliance: v14.10.2 (HEAD)
Payments: v0.0.1 (HEAD)

### Installation method

FrappeCloud

**Comment by anandbaburajan** [comment]
@nitin-anantpranali hi, I'm able to cancel JEs on the latest version of v14. So not able to reproduce the issue. Can you please try updating to the latest version and let me know if the issue persists?
