### ISSUE TITLE
Add Project as filter in the Balance Sheet Report

### ISSUE THREAD

**Issue by Shubee10** [frappe/erpnext#35967]
Many companies require Project filter in Balance Sheet details. Please add this filter in the core. 

![image](https://github.com/frappe/erpnext/assets/104073878/75ef1aa6-54e2-419e-ab4c-a75073ba3f3d)

**Comment by nihantra** [comment]
Hi @Shubee10,

I think, that for, you want to develop the [custom server script report](https://www.youtube.com/watch?v=PCVFNvK0UFs).

Otherwise, You add the project in [Accounting Dimensions](https://docs.erpnext.com/docs/v13/user/manual/en/accounts/accounting-dimensions).

Thank You!

**Comment by deepeshgarg007** [comment]
Fixed Via https://github.com/frappe/erpnext/pull/36097
