### ISSUE TITLE
Sales Invoice Status Issue / Outstanding Amount Issue

### ISSUE THREAD

**Issue by MrGiveItAway-TPK** [frappe/erpnext#35964]
### Information about bug

As an example: I made a sales invoice with for example 2 items each has a quantity of 5 then i make from the invoice a return invoice and return only 2 quantities of each item in this invoice the outstanding amount is 0 so the invoice correctly takes the status of Return. now after the first return go back again to the credit note issue invoice and make another return this time the return invoice takes the status of unpaid because the outstanding amount is greater than 0.

After further debugging regarding the status it is because of the outstanding indeed like so:
![image](https://github.com/frappe/erpnext/assets/100308806/343126ed-0685-40ed-a017-443a887a128c)
and the issue is due to the is_pos check because the condition below does not return the function and continues to calculate:
![image](https://github.com/frappe/erpnext/assets/100308806/c742a174-1773-4db9-a366-fa25cd8f7151)

### Module

accounts

### Version

Frappe Version - 14.40.1
ERPNEXT Version - 14.28.1

### Installation method

docker

**Comment by deepeshgarg007** [comment]
@MrGiveItAway-TPK This has been like this for a long and have not heard any complaints on this before. Is there any suggestion/proposal that you have?

If yes please add and reopen this issue, closing this for now
