### ISSUE TITLE
ERPNext Issue: Data No Longer Fetching From Linked Master

### ISSUE THREAD

**Issue by super-her-oh** [frappe/erpnext#35969]
### Information about bug

In **Stock Reconciliation Item** child table, our team added Item description as an additional data column, referencing: https://docs.erpnext.com/docs/v13/user/manual/en/customize-erpnext/articles/how-to-add-master-link-and-fetch-data-from-the-same
Everything was working 6/1/2023:
![image](https://github.com/frappe/erpnext/assets/120831367/44990c08-74b3-4de0-a1b2-4e3fe362df77)

We are now attempting to use Stock Reconciliation again on 7/2/2023, and it is no longer populating the descriptions: 
![image](https://github.com/frappe/erpnext/assets/120831367/e33c3932-61b8-4d11-a3e9-072afbbc4376)

Here is what we have which was working before: 
![image](https://github.com/frappe/erpnext/assets/120831367/c754c94a-c1c3-4dd1-8243-4a0168a98cd6)
![image](https://github.com/frappe/erpnext/assets/120831367/bc91bf67-cbb4-455e-9af4-85b084b95b8f)

Is there a glitch right now, or was there a glitch before that made this work on ERPNext v13?

Any guidance is appreciated-- thank you!

### Module

stock

### Version

ERPNext: v13.51.7 (HEAD)
Frappe Framework: v13.57.3 (HEAD)

### Installation method

FrappeCloud

**Comment by nihantra** [comment]
Hi @simplifybs,

Please check it.

https://discuss.frappe.io/t/erpnext-issue-stock-reconciliation-child-table-not-populating-data/106741/2?u=ncp

Thank You!

**Comment by super-her-oh** [comment]
Thank you! This issue was partially resolved with the help of @nihantra !
For a callout to persisting "Fetch from Warehouse" issue, please review the Frappe Forum link he provided. Thanks!
