### ISSUE TITLE
When you Select Project in Sale Inovice, API doesnt respond and Page Unresponsive

### ISSUE THREAD

**Issue by dexterhussain** [frappe/erpnext#35979]
### Information about bug

Create a Project, Add Time Sheets, Now go to Selling and Select Project in Sales Inovice, A message will come setting cost center and API which has to get response gets struck and page becomes unresponsive.
We have debugged, the error and it is coming because when I am selecting a project it is trying to fetch timesheets automatically, which should not be the case, it should not fetch timesheets until I click that button.

### Module

selling, projects

### Version

bench --version
5.16.2
Erpnext verison 14

### Installation method

None

**Comment by Nihantra-Patel** [comment]
Hi @dexterhussain,

Everything is working fine. No problems were encountered in versions 14 and 15.
Kindly upgrade to version 14 or 15, then refresh and check again.

https://github.com/frappe/erpnext/assets/141945075/ba49e4de-a457-4215-a5ca-ee89442ef6db

Thank You!
