### ISSUE TITLE
Newsletter List - Import Subscribers will Repeat Emails

### ISSUE THREAD

**Issue by justinlusg** [frappe/erpnext#3597]
![image](https://cloud.githubusercontent.com/assets/12539216/8564968/ba37813e-2583-11e5-9e42-2ff8ffc5b63e.png)

Importing Subscribers from the same group will result in the same email addresses being imported twice.

Steps to replicate
1) Create new Newsletter List
2) Import Subscribers from Contacts
3) Import Subscribers from Contacts again
Contacts get added twice

This could an issue in the design as it won't allow us to extend the list after it is imported and it's not feasible to create new lists every time when we want to send out a new newsletter.

**Comment by rmehta** [comment]
Can't replicate
