### ISSUE TITLE
Bank Reconciliation Tool - Delete Uploaded Transactions

### ISSUE THREAD

**Issue by mplubratt** [frappe/erpnext#35983]
I have uploaded a bank statement to the Bank Reconciliation Tool for the first time.  In the past, I just manually reconciled my bank account and it's becoming more and more complicated.  So, I thought I'd try the upload feature.  I uploaded a statement and it is showing a number of already entered bank transactions.  Now, I don't know how to delete the the lines in the Reconciliation Tool.  It would be great if one of the items in the "Actions" button was to delete the line.  Right now, that list is becoming polluted with imported lines that I don't know how to get rid of.  Please see the example below.

![ERPNext Feature](https://github.com/frappe/erpnext/assets/15216167/1ee7b0ab-ba5b-4eed-97e1-d14e0ecede8c)

**Comment by marination** [comment]
@mplubratt Go to "Bank Transaction" List and delete unwanted transactions that were created on uploading your statement

**Comment by mplubratt** [comment]
I was looking all over for that!  Thank you.
