### ISSUE TITLE
Total Subscribers for Newsletter List not Updating

### ISSUE THREAD

**Issue by justinlusg** [frappe/erpnext#3598]
![image](https://cloud.githubusercontent.com/assets/12539216/8565088/bf86854e-2584-11e5-8e0f-9bc83ea9c39a.png)

Steps to Replicate
1) Create new Newsletter List
2) Add subscribers 
3) Check the total number of subscribers 
4) Delete subscribers
5) Check the total number of subscribers again

Note: Total no. of subscribers will be updated only after another new subscriber is added but not after deletion.

**Comment by rmehta** [comment]
Can't replicate. Maybe you are using an older version

**Comment by justinlusg** [comment]
I've updated to the latest version, 

1) 
![image](https://cloud.githubusercontent.com/assets/12539216/8589976/92b0742e-264e-11e5-8be1-2aaa1941f54f.png)

2) 
![image](https://cloud.githubusercontent.com/assets/12539216/8589985/9b976494-264e-11e5-9eec-54cfb2c6a391.png)

3) ![image](https://cloud.githubusercontent.com/assets/12539216/8589990/a51e9dfc-264e-11e5-8cfd-dc5c70bc0be4.png)

4) 
![image](https://cloud.githubusercontent.com/assets/12539216/8589998/b4cff16a-264e-11e5-8c81-018dd70fb86c.png)

5) 
![image](https://cloud.githubusercontent.com/assets/12539216/8590002/bad366c8-264e-11e5-8c76-9b563f6cd64c.png)

6) 
![image](https://cloud.githubusercontent.com/assets/12539216/8590009/c2764f9e-264e-11e5-8025-a58c24a5ccfd.png)

The same contacts get imported twice

**Comment by justinlusg** [comment]
@rmehta  please see above screenshot

**Comment by rmehta** [comment]
@justinlusg cannot replicate in my local! it said 0 subscribers added the second time.

**Comment by justinlusg** [comment]
@rmehta is there a way to reinstall just that doctype?

**Comment by justinlusg** [comment]
it seems to only affect me, haha i tried on other instances and it works well.. I've no customisation on it and no idea why is it working in this manner.

**Comment by satishguptajaipur** [comment]
strangely it is affecting even me. I imported contacts to subscribers list and now when i delete some of them the list still shows 19 subscribers even when there are only 11 in the list.
