### ISSUE TITLE
get_valuation_rate returns wrong value

### ISSUE THREAD

**Issue by Namekkural** [frappe/erpnext#36010]
### Information about bug

When creating a new Stock Entry of type Material Receipt, when there have been Stock Entries for the current item with valuation 0.00, the function get_valuation_rate in stock_ledger.py will return 0.00 even if allow_zero_valuation_rate is set to false.

The issue is occuring here:

    # Get valuation rate from last sle for the same item and warehouse
	if not last_valuation_rate or last_valuation_rate[0][0] is None:
		last_valuation_rate = frappe.db.sql(
			"""select valuation_rate
			from `tabStock Ledger Entry` force index (item_warehouse)
			where
				item_code = %s
				AND warehouse = %s
				AND valuation_rate >= 0
				AND is_cancelled = 0
				AND NOT (voucher_no = %s AND voucher_type = %s)
			order by posting_date desc, posting_time desc, name desc limit 1""",
			(item_code, warehouse, voucher_no, voucher_type),
		)

	if not last_valuation_rate:
		# Get valuation rate from last sle for the item against any warehouse
		last_valuation_rate = frappe.db.sql(
			"""select valuation_rate
			from `tabStock Ledger Entry` force index (item_code)
			where
				item_code = %s
				AND valuation_rate > 0
				AND is_cancelled = 0
				AND NOT(voucher_no = %s AND voucher_type = %s)
			order by posting_date desc, posting_time desc, name desc limit 1""",
			(item_code, voucher_no, voucher_type),
		)

	if last_valuation_rate:
		return flt(last_valuation_rate[0][0])

When `if not last_valuation_rate`is run, it will return false every time, since it is receiving the sql result. I think this should be `if not last_valuation_rate[0][0]`, so the value gets checked and returns false when the value is 0.00

Please check wether this is expected behaviour!
You can see proof of the logic error in my screenshot taken from replicating this in the python console.

<img width="353" alt="CleanShot 2023-07-05 at 14 01 11@2x" src="https://github.com/frappe/erpnext/assets/11909277/3323f941-26c4-4757-9e14-b13110e6df8c">

### Module

stock

### Version

Frappe & ERPNext Version: 14.26.0

### Installation method

FrappeCloud

**Comment by Nihantra-Patel** [comment]
Kindly upgrade to version 14 or 15, then refresh and check again because lots of bugs fixed in the new version.

Everything is working fine. No problems were encountered in the latest versions 14 and 15.

Thank You!

**Comment by Namekkural** [comment]
Hi, 

this happened in 14.26, so we are already on 14. do you know if this has indeed been fixed in a later update?

we have upgraded a few times since then. It would be nice if this has been fixed.
