### ISSUE TITLE
E-commerce (The e-commerce site does not redirect to the all-products page when you login, and the page becomes stuck when we place an order )

### ISSUE THREAD

**Issue by sammish** [frappe/erpnext#36026]
### Information about bug

Hello Team 
The e-commerce site does not redirect to the all-products page when you login, and the page becomes stuck when we place an order 

Video Here : https://youtu.be/CosEHVVakt4

### Module

ecommerce

### Version

![image](https://github.com/frappe/erpnext/assets/12432802/a8ac5aad-fcaa-481e-a7e5-387e1c9cd577)

### Installation method

FrappeCloud

**Comment by rohitwaghchaure** [comment]
@sammish 

Tested and working fine on the latest version of v14, kindly update your site and check.
