### ISSUE TITLE
Unable to generate GST itemised sales register report

### ISSUE THREAD

**Issue by pkppandian** [frappe/erpnext#36029]
### Information about bug

When we generate GST itemised sales report we are getting the error message. TypeError: _execute() takes from 0 to 3 positional arguments but 4 were given

### Module

accounts

### Version

Frappee

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
Server Error
TypeError: _execute() takes from 0 to 3 positional arguments but 4 were given
```

**Comment by Nihantra-Patel** [comment]
Hi @pkppandian,

Kindly upgrade to version 14 or 15, then refresh and check again.


https://github.com/frappe/erpnext/assets/141945075/1ee97033-d0ad-4a98-9b87-fb8f53776029


Everything is working fine. No problems were encountered in versions 14 and 15.

Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!
