### ISSUE TITLE
Bug:  Custom fields writing before save

### ISSUE THREAD

**Issue by cgpurbaugh** [frappe/erpnext#3603]
There is a bug when customizing a form, if you click update, it starts writing your lines to the custom field list, before checking all of the lines.  If you get an error on one of the lines, and correct it, when you hit save it will try to write all of the lines again, resulting in a duplicate entry error.

**Comment by rmehta** [comment]
It works on refresh though, right?

**Comment by cgpurbaugh** [comment]
No, I have to go to the custom fields, and delete the ones that have already submitted.
