### ISSUE TITLE
Workflow State Issue

### ISSUE THREAD

**Issue by precihole** [frappe/erpnext#36050]
### Information about bug
there is an issue with workflow after i update the site.
Actual workflow is not showing in list view.
@rohitwaghchaure 
![image](https://github.com/frappe/erpnext/assets/111174201/82797566-3d58-445a-8817-a9e491cd2216)
![image](https://github.com/frappe/erpnext/assets/111174201/a992733b-0184-493d-a91e-cd69a2f58d81)
![image](https://github.com/frappe/erpnext/assets/111174201/c9dfeff8-4fe1-42f7-b513-7c532e3eb7c9)

### Module

other

### Version

ERPNext: v14.29.1 (HEAD)

Erpnext Telegram Integration: v1.2.0 (HEAD)

Frappe Framework: v14.40.2 (HEAD)

### Installation method

None

**Comment by penieldev** [comment]
I have the same issue on Frappe v14.40.3

**Comment by LijoJosephP** [comment]
Same issue

**Comment by michellealva** [comment]
fixed in https://github.com/frappe/frappe/pull/21657
