### ISSUE TITLE
Mode of payment Account linking destroyed when deleting Company transactions

### ISSUE THREAD

**Issue by meaziz** [frappe/erpnext#36081]
### Information about bug

When deleting company transaction child table linking made to Company Account is removed.

### Module

accounts

### Version

Version-14

### Installation method

None

**Comment by Nihantra-Patel** [comment]
Hi @meaziz,

Can you explain a bit more, and are you still having the same problem in the latest version 14?
otherwise, please share videos and images to help understand the documentation process better.
