### ISSUE TITLE
A bug while useing Journal Entry

### ISSUE THREAD

**Issue by AFelmorsi88** [frappe/erpnext#36109]
### Information about bug

while using Journal Entry we can't do any transaction only show 
This page is not responding ( exit page or wait ) without any response

### Module

accounts

### Version

I don't know it 

### Installation method

FrappeCloud

**Comment by Nihantra-Patel** [comment]
Hi @AFelmorsi88,

Please close all tabs, again open it, and check it. We haven't faced any type of issue on the latest versions 14 and 15.

Thank You!
