### ISSUE TITLE
Perm Level for "section" not visible in V14

### ISSUE THREAD

**Issue by willspenc** [frappe/erpnext#36103]
### Information about bug

It seems "Perm Level" for sections have been removed in V14. I can set Perm Level for a section in V13 but not in my V14 server.

( Logged in as Administrator )
Goto Customise from
Select form ( e.g. Job Card "
Goto a section : Operation Section
"Perm Level" field not visible
Perm Level field on actual fields within Operation is actually visible

Desired outcome : Pem Level for "Section" must also be visible

When repeating this on a V13 server, Perm Level for both the "section" and "Fields" are visible

I tested a few more doctypes and compared results between V14 and V13 , and I find the same.

### Module

manufacturing

### Version

ERPNext: v14.27.12 (version-14)

Frappe Framework: v14.40.0 (version-14)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
NA
```

**Comment by willspenc** [comment]
Update

I have updated my ERPNExt to

Ecommerce Integrations: v1.17.4 (main)
Education: v0.0.1 (develop)
ERPNext: v14.30.1 (version-14)
Frappe Framework: v14.40.3 (version-14)
Frappe HR: v14.5.1 (version-14)
Frappe LMS: v1.0.0 (main)

Still having this issue. I also checked other V14 systems and they have the same issue as my own system.

**Comment by michellealva** [comment]
yes, in v14, it is removed for section break, column break and tab breaks. ref: https://github.com/frappe/frappe/blob/develop/frappe/core/doctype/docfield/docfield.json#L309
