### ISSUE TITLE
[BUG] Can't set value 0 to Billing Hours in Timesheet

### ISSUE THREAD

**Issue by hamzahabeeeeb** [frappe/erpnext#36102]
### Information about bug

i want to be able to set the hours to 0

### Module

projects

### Version

13

### Installation method

None

**Comment by michellealva** [comment]
This isn't a bug. Setting hours = 0 would essentially mean your `from_time` and `to_time` is the same, which is not possible. There has to be some difference in both, even milliseconds would do.
