### ISSUE TITLE
how to set previos button is show after next button is click..

### ISSUE THREAD

**Issue by pankajpatel12** [frappe/erpnext#3612]
******This is my html page******

<div class="padding" style="max-width: 300px;">
    <div class="question"></div>
	
    
</div>
<div class="padding" style="max-width: 300px;">
    <div class="answare"></div>
   
    <p>
	
	<button class="btn btn-sm btn-default btn-previos-question">
            {%= __("<< Previous") %}</button>
        <button class="btn btn-sm btn-default btn-next-question">
            {%= __("Next >>") %}</button>
    </p>
</div>

*******this is my js page******

frappe.pages['subject'].on_page_load = function(wrapper) {
	frappe.subject = new frappe.Subject(wrapper);
	frappe.breadcrumbs.add("subject", "Student Test");
}

frappe.Subject = Class.extend({
	init: function(parent) {
		this.parent = parent;
		this.make();
		this.refresh();
	},
	refresh: function() {
		//if(!this.student_test) 
		{
			this.show_start();
		}
	},
	make: function() {
		this.page = frappe.ui.make_app_page({
			parent: this.parent,
			title: __("Test"),
			single_column: true
		});

	},
	show_start: function() {
		this.page.main.html(frappe.render_template("student_test_builder_start", {}));
		this.page.clear_actions();
		this.page.set_title(__("Test"));
		this.start_question();
		this.start_answare();
	},
	start_question: function() {
		// Test control
		var me = this;
		this.question_input = frappe.ui.form.make_control({
			parent: this.page.main.find(".question"),
			df: {
				fieldtype: "Read Only",
			
				label: __("Que"),
			},
			render_input: true
		});

	},
	start_answare: function() {
		var me = this;
		this.answare_input = frappe.ui.form.make_control({
			parent: this.page.main.find(".answare"),
			df: {
				fieldtype: "Small Text",

				label: __("Ans")
			},
			render_input: true
		});
		
	},		
	
 });

**Comment by rmehta** [comment]
@pankajpatel12 please follow the guidelines and don't post questions here, else will have to ban you.
