### ISSUE TITLE
Customer Name in Opportunity & Quotation are different

### ISSUE THREAD

**Issue by justinlusg** [frappe/erpnext#3615]
When creating quotation from opportunity, the name that is brought over is the lead name and not the customer name. 

**Opportunity Screen**
![image](https://cloud.githubusercontent.com/assets/12539216/8593031/bb73bd36-2666-11e5-85ad-54388393f63c.png)

*Click on Create Quotation*
**Quotation Screen**
![image](https://cloud.githubusercontent.com/assets/12539216/8593037/c6642046-2666-11e5-814e-b3a3fcb60e64.png)

I understand it should display the customer name instead of the lead name

**Comment by sbkolate** [comment]
Organization Name in Lead is customer full name in customer
And 
Person Name in Lead is  Contact Name in Customer

Also,  Customer Name(i.e Lead Name) in Opportunity & Quotation are same, Tested on demo.erpnext.com

**Comment by justinlusg** [comment]
Please try these steps, 
1) Create Lead
2) Convert Lead to Opportunity (Customer/Lead name is Organization Name from Lead)
3) Create Quotation from Opportunity (Customer/Lead name is Person Name from Lead)

It should be consistent where both Opportunity and Quotation are both Organization Name from Lead
