### ISSUE TITLE
Adding Email Account loads without saving the account

### ISSUE THREAD

**Issue by tedyswaga** [frappe/erpnext#36155]
### Information about bug

I have tried adding multiple email accounts including Gmail and am not able to save the email account with no error

### Module

other

### Version

frapper version :  14
erpnext version: 14

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
Hi @tedyswaga,

For some services like Gmail, you may need to enable 2FA and use [App Passwords](https://myaccount.google.com/u/0/apppasswords).

Using Gmail, Everything is working fine. No problems were encountered in the latest versions 14 and 15.

If you haven't checked the updated [documentation](https://docs.erpnext.com/docs/user/manual/en/email-account) then check it.

Thank You!
