### ISSUE TITLE
Non-stop Auto Creation of Material Request

### ISSUE THREAD

**Issue by aliparlar** [frappe/erpnext#36154]
### Information about bug

Not sure if bug or intention

I have an item below auto order level. Each day a new Material Request is generated. 

Since the material request is not fulfilled yet, I will keep getting new Material Requests until I take action. I would expect only one Material Request to be generated. It warns me allright, but I see no point of having a bunch of the same Material Requests, cancel, delete etc. 

### Module

stock

### Version

ERPNext: v14.x.x-develop () (develop)
Frappe Framework: v15.x.x-develop () (develop)

### Installation method

manual install

**Comment by s-aga-r** [comment]
@aliparlar The Auto-Reorder works based on Projected Qty. 

Projected Qty = Actual Qty + Planned Qty + Requested Qty + Ordered Qty - Reserved Qty - Reserved Qty for Production - Reserved Qty for Subcontracting - Reserved Qty for Production Plan

When a Material Request is created the Requested Qty gets increased means the Projected Qty will also get increased.

Consider an example:
- I have an Item with 0 stock for which the Re-order Level is 100 and Re-order Qty is 110. 
  
![image](https://github.com/frappe/erpnext/assets/63660334/72032ac9-5a46-4980-80c9-9b853ac1f052)

- Now, the system will create a Material Request for 110 Qty and the Requested Qty gets increased by 110 i.e., Projected Qty will be 110. If the Projected Qty is greater than the Re-order Level system won't create new Material Requests daily. 

  ![image](https://github.com/frappe/erpnext/assets/63660334/aab28a74-6980-4fa2-a4fb-e17f98b22879)

  ![image](https://github.com/frappe/erpnext/assets/63660334/d7bb20b4-b8a1-4bce-8e0f-5d03be52ed9b)
