### ISSUE TITLE
E-Mails very inconsistent

### ISSUE THREAD

**Issue by venkatsethu** [frappe/erpnext#3617]
Hi,
We have been using ERPNEXT last 1.5 months. About 30% of the times the e-mails go out from the various modules and 70% of the time the e-mails don't go and our customers or partners do not receive the email. Even if the e-mails are marked as cc to the sender, it doesnt come.

Our e-mail outside ERPNEXT Is working perfectly fine with no problem at all. 

Due to this it is becoming a big hassle for us to download the pdf and resend the E_mails offline leading to delays and unwanted confusion.

We have followed all the procedures as per your setup instructions, but the e-mail behaviour is completely unpredictable and much less than satisfactory.

Can you get this fixed conclusively or let us know how to make any changes to get it sorted out at our end (if at all we have to anything different in terms of set up?)

**Comment by rmehta** [comment]
EMail works fine with us. You might want to check if you have setup your email & DNS correctly. You can also use 3rd party like Mandrill or Sendgrid to ensure deliverabililty.
