### ISSUE TITLE
Agriculture is not  working in ERPNext Version 14

### ISSUE THREAD

**Issue by ArunaDevraj** [frappe/erpnext#36194]
### Information about bug

/home/aruna/Pictures/Screenshots/Screenshot from 2023-07-19 12-59-52.png

### Module

agriculture

### Version

Frappe Version - v14.40.3 (version-14)
ERPNext Version - v14.31.1 (version-14)

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
Hi @ArunaDevraj,

The Agriculture module in ERPNext isn't well developed. It has many bugs and currently isn't being maintained. However, we are considering improvements for it in the future.

Thank You!
