### ISSUE TITLE
Amount is not calculated for quotation item, if,  Is Alternative, is ticked

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#36199]
### Information about bug

- Create a Quotation
- Add an item
- Tick IS Alternative
- Change qty or rate, amount remains unchanged

### Module

selling

### Version

ERPNext: v14.31.2 (HEAD)

Frappe Framework: v14.41.0 (HEAD)

### Installation method

FrappeCloud

**Comment by Nihantra-Patel** [comment]
Hi @muchai,

You are right but check the logic and concept.

#33609

#33874

Thank You!
