### ISSUE TITLE
Error: Bank statement import

### ISSUE THREAD

**Issue by nissekalle0** [frappe/erpnext#36197]
### Information about bug

The "Bank Account" field must be put as last column in the .csv file. If not the error of number of columns at each row is to many than the header names.

### Module

accounts

### Version

Frappe and ERPNext 14.x

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Error: "row has more values than columns"
```

**Comment by Nihantra-Patel** [comment]
Kindly upgrade to version 14 or 15, then refresh and check again because lots of bugs fixed in the new version.

And again download the template and set it and import it.

Thank You!
