### ISSUE TITLE
New BOM Does not have any entry fields

### ISSUE THREAD

**Issue by daxwilder** [frappe/erpnext#36204]
### Information about bug

When I select New BOM for the first time, the screen is blank with no entry fields.

See Attached Image
![BOM_Screen_Blank](https://github.com/frappe/erpnext/assets/129622586/16dda627-184f-4df2-83d6-b06647472b5e)

### Module

manufacturing

### Version

v14.21.0

### Installation method

manual install

**Comment by rohitwaghchaure** [comment]
@daxwilder Have you done any customization in the BOM? Any error on a console log?

Also make sure you're using the latest version of V14

**Comment by daxwilder** [comment]
I have not done any customization. That was the first time opening the BOM screen.

**Comment by rohitwaghchaure** [comment]
@daxwilder This is working fine, please update your site to latest version of v14 and check

**Comment by daxwilder** [comment]
Yes, upgraded and the BOM is working now.  Thank you for your help.
