### ISSUE TITLE
List view has a weak UX when window is higher than the 20 default items

### ISSUE THREAD

**Issue by zifeo** [frappe/erpnext#36212]
**Is your feature request related to a problem? Please describe.**

By default, only 20 items are displayed. When the window height is larger than the 20 items, there is an empty space between the last item and the pagination. This hints the user that there is no more element to browse.

**Describe the solution you'd like**

No space between the last item and the pagination.

**Describe alternatives you've considered**

Load more items by default but that is not a good solution.

**Additional context**

<img width="92" alt="image" src="https://github.com/frappe/erpnext/assets/9053709/bccd102b-a6fe-43d3-996e-138546d1a928">

**Comment by ankush** [comment]
@shariquerik / @maharshivpatel any of you wanna take this forward? 


This is quite noticeable on hi-res displays. Possible fixes:

- Load 100 by default (feels weird and inconsistent, also extra perf cost)
- Move the "load more" section close to where rows end when limit is set (?)
- Somehow indicate that there are more entries and what's shown is not the end.

**Comment by bosue** [comment]
> Move the "load more" section close to where rows end when limit is set (?)

This would be intuitive and lean. Maybe display the row count as well, like „356 more items…“

**Comment by zifeo** [comment]
@shariquerik @maharshivpatel Any news on the above? This is critical for customers. cc @mayanknahata007

**Comment by zifeo** [comment]
Hello, can we get back on this critical point @shariquerik @maharshivpatel? cc @mayanknahata007

**Comment by zifeo** [comment]
@shariquerik @maharshivpatel Any progress on that important one? cc @ankush @mayanknahata007
