### ISSUE TITLE
Expense Account Field not showing other Account Title on Purchase Order Item

### ISSUE THREAD

**Issue by davidwebbespiritu** [frappe/erpnext#36225]
### Information about bug

https://github.com/frappe/erpnext/commit/d54f52474af27d129fc1bcbb166933bf0fc94fbc

Kindly refer to that commit; I have also commented on that.
We were not able to select other account title as field has a filter for only "Profit and Loss" as report type. Commit was only meant for Sales Invoice but it has affected also Purchase Order.

### Module

buying

### Version

Frappe Framework: v14.40.3
ERPNext: v14.30.6

### Installation method

manual install

**Comment by deepeshgarg007** [comment]
@davidwebbespiritu Ideally this account should also be an Profit and Loss account only. Any particular use case why you need a different account type?

**Comment by davidwebbespiritu** [comment]
Our accounting department already used account titles under "Balance Sheet" as report type specifically, chart of accounts "2000 - Source of Funds" which is quite what should be selected on expense account field don't you think? Also previous version of ERPNext before that commit includes only Company as filter.  Why change? This could mean our previous encoding are wrong? Thanks for getting back by the way.
