### ISSUE TITLE
Create contact to customer - name will be overwritten

### ISSUE THREAD

**Issue by applejuiceDE** [frappe/erpnext#36223]
### Information about bug

Hello all,

I have noticed a phenomenon in my installation (v14), so I would like to ask you for help.

When creating a new contact, if a company reference is included, I can enter whatever I want as the name, it is always overwritten with the customer name and number. If I create a new contact without a reference, everything works smoothly. The reference can then also be added afterwards without any problems.

What can I do to correct this?

### Module

CRM

### Version

erpnext 14.30.3 version-14 (2f2b45b)
erpnext_datev 14.1.0 version-14 (eeac4c9)
erpnext_germany 0.0.5 version-14 (f2a67ad)
erpnext_nextcloud 2.0.0 master (831ec50)
frappe 14.40.3 version-14 (d5a296a)
hr_addon 0.0.1 version-14 (a52de76)
hrms 15.0.0-dev develop (9cff930)
payments 0.0.1 develop (be9a2e3)
whitelabel 0.0.1 master (7d93307)
wiki 2.0.0 version-14 (488bfe7)

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
Kindly upgrade to version 14 or 15, then refresh and check again because lots of bugs fixed in the new version.
