### ISSUE TITLE
Required Stock UOM error, when Purchase Order is created from a Blanket Order

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#36236]
### Information about bug

- Default Stock UOM is not set when a PO is created from a Blanket Order.
- On the other hand, appropriate price list is not set when Sales Order is created from Blanket Order

### Module

buying

### Version

ERPNext: v14.31.3 (HEAD)
Frappe Framework: v14.41.0 (HEAD)

### Installation method

FrappeCloud

**Comment by Nihantra-Patel** [comment]
Everything is working fine. No problems were encountered in the latest versions 14 and 15.

> Default Stock UOM is not set when a PO is created from a Blanket Order.


https://github.com/frappe/erpnext/assets/141945075/cdf4d7c5-9e78-4352-a514-4a46c1efa5b8


> On the other hand, appropriate price list is not set when Sales Order is created from Blanket Order

For this you add the field of price list in the blanket order and also add the field of currency. It will be set automatically when you create a sales order or purchase order.
