### ISSUE TITLE
Fiscal Year Setup

### ISSUE THREAD

**Issue by trackomatic** [frappe/erpnext#36234]
### Information about bug

I have installed ERPNEXT14 on a fresh ubuntu server following this guide [https://discuss.frappe.io/t/guide-how-to-install-erpnext-v14-on-linux-ubuntu-step-by-step-instructions/92960/121](url)

I landed on ERPNEXT 14.31.3. I need to add some accounting information for previous fiscal year for which I created the fiscal year 2022-23. But there is no option to set this fiscal year as default. This option was available in v14.30.0 but it is no more there.

![image](https://github.com/frappe/erpnext/assets/140053831/cf20909e-e751-4801-a5d4-40ef100499b8)

![image](https://github.com/frappe/erpnext/assets/140053831/7b091523-4040-4eff-b7e1-d4b357b45c65)

![image](https://github.com/frappe/erpnext/assets/140053831/c710d7fd-b7a7-4157-99d1-0fd2904ccf04)

can anyone please help???

### Module

accounts, buying, selling, ecommerce, CRM, assets, quality, regional

### Version

**Installed Apps**
**Frappe Chat:** v0.0.1 (main)

**ERPNext:** v14.31.3 (version-14)

**Frappe Framework:** v14.41.0 (version-14)

**Frappe HR: v14.7.0** (version-14)

**India Compliance: v14.12.0** (version-14)

**Payments: v0.0.1** (version-14)

### Installation method

manual install

**Comment by deepeshgarg007** [comment]
@trackomatic This has been removed. The fiscal year is fetched based on the date now. Any particular reason for requiring to set any year as default?

**Comment by trackomatic** [comment]
@deepeshgarg007 
Thanks for your reply. 

The Fiscal Year needs to be set for clear the entries of previous year so that to properly close the account books. the users (like us) who wish to switch to ERPNEXT would need to migrate their data from software to ERPNEXT and would need to retain the document numbers i.e. the Invoice Numbers, Quotation Numbers etc. having the option of setting the default fiscal year helps in maintaining the document naming series.

apart from that, at the time of end of a fiscal year, companies will need to keep using the previous fiscal year (at least for a couple of weeks) to prepare their balance sheets and then after the fiscal year will be set to New Fiscal Year. **This feature was there for a reason during all previous year.** So I believe that the feature is not taken away, but it is bug which needs to fixed.

Moreover, we are trying to adapt the ERPNEXT. We need to make entries for our previous year accounting books on which the Invoice numbers are set. This option was there until v14.28.00. I just updated the bench and their feature was gone. Now I am trying to re-install the complete setup (done it many times in 02 days) but that feature doesn't appear.

**Comment by trackomatic** [comment]
> @trackomatic This has been removed. The fiscal year is fetched based on the date now. Any particular reason for requiring to set any year as default?

@deepeshgarg007 Moreover, the fiscal year is also needed for Naming Series which is not working as of now.

**Comment by trackomatic** [comment]
Hello,

We are using ERPNEXT14 for our very small business and it was working fine.

We have set naming series for all the documents i.e. Purchase Orders, Sales Orders, Sales Invoices etc. Our Common pattern:
Doc Name: PO 
fiscal Year: 2023-24
3 digit serial number: 001. 

hence we have set the naming series **“PO.FY.###”**

After updating to v14.31.3, fiscal year is not working in naming series. We already have issued many tax invoices with our series i.e. SINV2023-24001 which are also registered with GST portal. as per GST guidelines, the invoice series shouldn’t be changes in mid of fiscal year but the naming series in ERPNEXT is no more considering “.FY.” as a valid argument.

although there is a work around to situaiton by manually naming the series i.e. by putting PO.2023-24.### but then we need to do the same for all the doc types. moreover, at the end of fiscal year, we’ll need to do the same practice again to update the naming series of all the documents. whereas having Fiscal Year .FY. as a valid argument for Naming Series, it could have been done by changing the Fiscal Year in Accounting Module itself.

can anyone suggest where can be re-activate this feature in ERPNEXT14.

**Comment by bosue** [comment]
This was only recently removed in #35960 and backported to v14 in #36153.

In various issues there have been at least three complaints of users missing the fiscal year in naming series.
I think we should at least rollback the backport for now and discuss the consequences of fiscal year being removed in v15.

**Comment by SvbZ3r0** [comment]
Hi @deepeshgarg007 , in #35960 , the following function was added:
```py
def parse_naming_series_variable(doc, variable):
	if variable == "FY":
		return get_fiscal_year(date=doc.get("posting_date"), company=doc.get("company"))[0]
```
When using the `Try a naming series` feature in the `Document Naming Settings`, `doc.get("posting_date")` and `doc.get("company")` will both result in an error.

So you get 
![image](https://github.com/frappe/erpnext/assets/57280279/0bc48a18-dc2d-4667-9288-0809900a0cd5)

I haven't debugged why this is causing an issue when creating a document using the FY variable yet (because `india_compliance` reads the error as the document name and fails when the name is longer than 16 characters), but there is no question of there being an issue when using FY.

I think this should be reverted until a fix can be found. I will try to dig deeper and see why there is an error.

**Comment by SvbZ3r0** [comment]
Ok.. I did dig deeper and the 16 characters failure wasn't due to an error. It was INV/2023-2024/00001 which is longer than 16 characters. Otherwise using FY in, say, Purchase Receipts or what not doesn't cause an issue. 
The insta lookup in `Document Naming Settings` is definitely broken though. Maybe a default date can be provided for that page?

**Comment by SvbZ3r0** [comment]
Sorry for using this issue like a log.
Upon further testing, there's a very particular scenario when this issue occurs. 
Essentially, it only occurs in the case where the DocType chosen in `Select Transaction` does not have any previous documents created. In this case, there will not be a document it can pass to `pass_naming_series_variable` resulting in a call to what is essentially `None.get("posting_date")` and `None.get("company")`, and hence `'NoneType' object has no attribute 'get'`.

**Comment by aphchoo** [comment]
![image](https://github.com/frappe/erpnext/assets/149393532/ccd8b387-3537-4d9d-8d2e-be5074c5e140)


Without the fiscal year has affected many dashboard charts that uses as a filters. (see above)


![image](https://github.com/frappe/erpnext/assets/149393532/388a02a0-214d-40fe-83f3-e712faab1e18)

It also caused many reports not functioning like Profit and Lost statement, Balance Sheets return errors.

**Comment by aphchoo** [comment]
![image](https://github.com/frappe/erpnext/assets/149393532/8edee7f4-31fa-43e8-ab50-959525358e97)

Another Dashboard error.

**Comment by aphchoo** [comment]
![image](https://github.com/frappe/erpnext/assets/149393532/822b7e73-7616-4419-ad1c-c3200b4d4765)
Fiscal Year are setup but all not being usable now.

**Comment by dedunumax** [comment]
I had the same error everywhere. I think ERPNext is looking for current year in fiscal years. If you don't have the current year, try creating it.
