### ISSUE TITLE
„Edit“ button slipping to next line in translated environments

### ISSUE THREAD

**Issue by bosue** [frappe/erpnext#36266]
### Information about bug

In non-English environments, where the translation of „Edit“ may be longer, such as „Bearbeiten“ in German, the Edit button slips to the table‘s next line, also slightly messing up the horizontal alignment of all columns.

Example 1:
![IMG_1177](https://github.com/frappe/erpnext/assets/46800703/066649aa-c991-486b-a33f-8f26713c1c98)

Example 2:
![IMG_1179](https://github.com/frappe/erpnext/assets/46800703/4331526d-be26-44b2-94a3-8001f9740080)

Unsure if this is an implementation bug with ERPNext or a more general bug with the underlying Frappe framework. Please move accordingly, in case it‘s the latter.

### Module

other

### Version

ERPNext v15 nightly

### Installation method

FrappeCloud

**Comment by Nihantra-Patel** [comment]
Kindly upgrade to version 14 or 15 or dev, then refresh and check again because lots of bugs fixed in the new version.

Everything is working fine. No problems were encountered in the latest versions 14, 15 and dev.
