### ISSUE TITLE
„Allow Sales Invoice Creation Without Sales Order / Delivery Note“ setting seemingly without any effect

### ISSUE THREAD

**Issue by bosue** [frappe/erpnext#36285]
### Information about bug

1.) The actual bug report:

Seems like the settings “Allow Sales Invoice Creation Without Sales Order” and “Allow Sales Invoice Creation Without Delivery Note“ don’t have any effect whatsoever.

Both being switched off, it still seems possible to create a sales invoice without any prerequisite:

https://github.com/frappe/erpnext/assets/46800703/21befa5c-b945-4ba8-a1be-731b8714484b

2.)
Wouldn’t these settings be better placed in the Customer Group DocType? They would nicely fit in there, and in most cases, if Sales Orders and/or Delivery Notes may be waived, this won’t be on a per-customer base but for a certain group of customers. So moving it to Customer groups, which may be set up as fine-grained as needed, would simplify setting up these workflow stages.

3.)
In case the bug gets confirmed not just for v15, and given that nobody seems to have been crying for this functionality to be fixed, wouldn’t it be a good idea to give up these isolated tweaks in favor of a proper, full-fledged sales workflow / pipeline? In this case, it might be best to remove the two checkboxes from those versions where they never worked anyway and wait for a better solution to be proposed…

### Module

selling

### Version

ERPNext v15 nightly

### Installation method

FrappeCloud

**Comment by basawaraj-fosserp** [comment]
@bosue the 'Allow Sales Invoice Creation Without Sales Order' and 'Allow Sales Invoice Creation Without Delivery Note' checkboxes allow you to override the 'Is Sales Order Required for Sales Invoice & Delivery Note Creation?' and 'Is Delivery Note Required for Sales Invoice Creation?' settings in 'Selling Settings'.

If 'Is Sales Order Required for Sales Invoice & Delivery Note Creation?' is set to 'No' in 'Selling Settings' then the checkbox 'Allow Sales Invoice Creation Without Sales Order' has no impact.

If 'Allow Sales Invoice Creation Without Delivery Note' is set to 'No' in 'Selling Settings' then the checkbox 'Allow Sales Invoice Creation Without Delivery Note' has no impact.

This also explained in the documentation.
https://docs.erpnext.com/docs/user/manual/en/selling-settings

**Comment by basawaraj-fosserp** [comment]
@anandbaburajan I think this can be closed.
