### ISSUE TITLE
SHipping Cost or Landed Cost Voucher

### ISSUE THREAD

**Issue by farhanayyaz1** [frappe/erpnext#3629]
Please get me some information on the following:

1 - I have import purcahse how to put shpping cost to purcahse invoice.

2 - Customs & Duty to purchase invocie

3 - In landed cost voucher the expense just go to valutaion .

4 - The expense liek shipping xpense we want on purchase invoice also has to be paid to company, so please get me some information on that.

**Comment by adityaduggal** [comment]
@farhanayyaz1 This post should more appropriately be put into the FORUMS link is: https://discuss.frappe.io/

I don't see the issue being a issue of the core application
