### ISSUE TITLE
Erratic and random search result in the search box of the external website

### ISSUE THREAD

**Issue by robertbecht** [frappe/erpnext#3630]
Reported (several times before) the unpredictable “search” 

https://dogsloveit.erpnext.com/product-groep/diepvries

Please type “darf” in search>> no returns
Please type “eend” in search>> no returns

Please type “tinlo” in search>> works
Please type “hert” in search>> works

The functionality of the search used to be perfect until some six montb ago.
I fail to understand the logic what is found and what not.

Rgds robert

**Comment by rmehta** [comment]
@robertbecht do these strings exist in the name or description?

**Comment by robertbecht** [comment]
High Rushabh, yes of course. This behavior exist already 6-9 month. Before
that it worked fine.

rgds robert

**Comment by rmehta** [comment]
Fixed.
