### ISSUE TITLE
Change default in POS to exact amount.

### ISSUE THREAD

**Issue by robertbecht** [frappe/erpnext#3631]
99 % of our customers pay electronically with a bank card. The amount paid should be by default the amount (to be paid) that can be overwritten if needed (cash payment)

Since the POS is used now as a general input tool for PO/SO/etc a date picker would be an enhancement. ( also for the sales POS, I still copy when time available our handwritten invoices so have to adjust the date)

rgds robert

**Comment by rmehta** [comment]
Fixed
