### ISSUE TITLE
Item Variant Show Error on recent 5.14 update

### ISSUE THREAD

**Issue by andiyan1** [frappe/erpnext#3632]
Hi team, 

I am sorry for this reply, however i found out that after i update erpnext to the latest update. i found out that i cant create item that has variant with it. everytime i would try to make new item with variant i would end up with error shown.

Please check and please confirm if other are having similar problem or if its just me?

Thanks 
Anton

**Comment by rmehta** [comment]
@andiyan1 what error? In the latest update, variant creation has been moved to another form.

**Comment by andiyan1** [comment]
Hi rushabh,

I confirm that the variant are working as it should. Sorry that we are
confused with the new changes.

The problem that is you have to tick the "has variant" box then save it
first. Thus upating the item.

I did not.

I tick the item "has variant" box then directly go to the manage variant
page. Thus resulting error and state that the item i selected does not have
any variant. Umair sort this out for me.

Thanks and best regards.

Anton
