### ISSUE TITLE
Purchase Receipt, same item different warehouse

### ISSUE THREAD

**Issue by fderyckel** [frappe/erpnext#3633]
Hi, 
It seems like it is not possible at this stage with ERPNext to make a purchase of 50 item A in Warehouse a and 50 item A in Warehouse B.  
Similarly, it doesn't seem possible to make a purchase a receipt of 50 item A at price x$ and 60 item A at price y$.

Any special reason for that?  It does happen quite a lot for us that we receive 24T of a given product at once (from same suppliers) but that we have to store it in more than one warehouse.

Best,

François

**Comment by rmehta** [comment]
@fderyckel you should make separate receipts or stock entry.

**Comment by strixaluco** [comment]
Please post questions to [discuss.erpnext.com](https://discuss.erpnext.com)
