### ISSUE TITLE
Cant Add supplier Unable to Create New Supplier and Missing Fields After Hiding Majority of Fields Using Fixtures in Custom App (ERPNext v14)

### ISSUE THREAD

**Issue by Hafnianusha** [frappe/erpnext#36348]
### Information about bug

![image](https://github.com/frappe/erpnext/assets/100829201/1458a924-dd53-44f8-8491-87fe986df299)
 
I encountered an issue in ERPNext version 14 after following a client's request to hide the majority of fields in the Supplier doctype . I hide it and exporting the changes to my custom app using 'Export Customisation' Button in Customize Form. After implementing these changes, I am unable to create a new Supplier.

Symptoms:

 1. New Supplier Creation Issue:When clicking 'Add new Supplier' From Supplier List it is showing read only fields which cant be changed

  2. Missing Fields: Alll mandatory  fields including supplier name , group , type that were not hidden in the Supplier doctype are now missing. Only  fields (which was shared in a previous screenshot) is visible, but it appears to be read-only. 

  3. Absence of Save Button: The Save button is missing, which prevents me from saving any changes or creating new Supplier records.
  
  Expected Result:

    I should be able to create a new Supplier without any issues, and all relevant fields (those not hidden) should be visible and editable.
    The Save button should be available to save changes and new Supplier records.

Actual Result:

    I am unable to create a new Supplier.
    Fields that were not hidden are now missing, except for some field which is now readonly.
    The Save button is not visible, preventing any changes from being saved.

### Module

buying

### Version

ERPNext: v14.8.0 (version-14)

Frappe Framework: v14.36.0 (version-14)

Hospitality: v0.0.1 (develop)

Frappe HR: v14.0.1 (version-14)

India Compliance: v14.0.2 (v14)

Non Profit: v0.0.1 (develop)

Payments: v0.0.1 (develop)

### Installation method

None

**Comment by s-aga-r** [comment]
Ask customizations-related queries in our community group https://t.me/frappeframework/3457
