### ISSUE TITLE
Unable to save the Sales Cycle

### ISSUE THREAD

**Issue by anisharaulo** [frappe/erpnext#36341]
### Information about bug

1. Unable to save the Sales cycle records.Getting a pop-up error as "KeyError: 'tax_amount'".
2. Getting the error from the core file. file name : [taxes_and_totals.py]
![Screenshot from 2023-07-27 11-21-59](https://github.com/frappe/erpnext/assets/114654335/bc8a60fc-7fd6-4e97-ad3c-5d1661b8724c)
![Screenshot from 2023-07-27 11-21-20](https://github.com/frappe/erpnext/assets/114654335/80a898d3-aa4a-4f40-a4b5-bcde230991e5)
Record - (https://alltronix-test.frappe.cloud/app/sales-order/SAL-ORD-2023-00077)

### Module

selling

### Version

Frappe - 14.42.0
Erpnext - 14.32.1

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
Getting a pop-up error as "KeyError: 'tax_amount'".
```

**Comment by tailorraj** [comment]
Any Update on this as it is impacting our daily transaction which is not getting happening

**Comment by s-aga-r** [comment]
https://github.com/frappe/erpnext/pull/36235#issuecomment-1651406822
