### ISSUE TITLE
Reconciled items are not put back in the list of Reconcilation tool if a transaction is cancelled and then deleted

### ISSUE THREAD

**Issue by nissekalle0** [frappe/erpnext#36354]
### Information about bug

1. Let us say you create a purchase invoice and then submit.
2. You reconcile it against the imported bank transactions.
3. You delete the purchase invoice
4. the item has not been put back in the list of Reconcilation Tool

### Module

accounts

### Version

Latest

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
No error
```

**Comment by Nihantra-Patel** [comment]
Hi @nissekalle0,

If you are use version 13 then We no longer provide support for version 13 or older.

Kindly upgrade to version 14 or 15, then refresh and check again.

Everything is working fine. No problems were encountered in the latest versions 14 and 15.
If the issue occurs then please create a new issue according to version (14 or 15) with a video document if possible.

Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!
