### ISSUE TITLE
Link in Bank Transaction to Payment Entry does not work 

### ISSUE THREAD

**Issue by nissekalle0** [frappe/erpnext#36350]
### Information about bug

In the payment entries list the payment entry link does not work inside a Bank Transaction.

### Module

accounts

### Version

Latest

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
no link is activated
```

**Comment by Nihantra-Patel** [comment]
Hi @nissekalle0,

Everything is working fine. No problems were encountered in the latest versions 14 and 15.

If a problem happens, make a new issue for the latest version 14 or 15 (please mention the version). Include a video if you can. Describe what happened (error log if possible), the type of problem, and which doctype it's related to.

Thank You!
