### ISSUE TITLE
Bank Transaction naming series is picked a random serial number

### ISSUE THREAD

**Issue by nissekalle0** [frappe/erpnext#36351]
### Information about bug

Of some reason the ACC-BTN series is given a random last five figures

### Module

accounts

### Version

latest

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
no error
```

**Comment by Nihantra-Patel** [comment]
Hi @nissekalle0,

We haven't faced any type of issue regarding naming series in the latest versions 14 and 15. Also fixed naming series variable parsing for FY.

Kindly upgrade to version 14 or 15, then refresh and check again.

Thank You!
