### ISSUE TITLE
Service Level Agreement: "SLA Fulfilled On" and "SLA Paused On" cannot be chosen

### ISSUE THREAD

**Issue by Spixmaster** [frappe/erpnext#36368]
### Information about bug

Visit this route `/app/service-level-agreement/` of your ERPNext instance and create a Service Level agreement. The fields "SLA Fulfilled On" and "SLA Paused On" have a dropdown menu with no items.

![screenshot-20230728-063436](https://github.com/frappe/erpnext/assets/46067952/4588f47a-c570-4bdc-b79c-e17a5f05949e)

### Module

support

### Version

Installed Apps
ERPNext: v14.31.3 (HEAD)

Frappe Framework: v14.41.0 (HEAD)

Hospitality: v0.0.1 (develop)

Frappe HR: v14.7.0 (HEAD)

### Installation method

manual install

**Comment by nihantra** [comment]
Hi @Spixmaster,

Because it will show depending on Apply On Field.
If doctype has a status then it will show.

Please check it.

https://github.com/frappe/erpnext/assets/99652762/3d90047d-9eff-4daa-b79a-4ab576563c10

Thank You!

**Comment by Spixmaster** [comment]
@nihantra Thank you very much! I had chosen "Article" for "Apply on". Then no statuses are shown. Since the status is necessary this means that this document cannot be created with application on an article.

**Comment by madhusona** [comment]
@nihantra create a status field with type Select in Article. Give your options like status 1, status 2, status 3. After creating this you able to access the status in service level agreement
