### ISSUE TITLE
Add new item field is missing in edit full form

### ISSUE THREAD

**Issue by Bolderus** [frappe/erpnext#36370]
### Information about bug

I added manufacturer field in item and set it mandatory when I click to create add item I can see manufacturer field.But when I create new item it is missing I cant see. also in full form it is missing. 

The filed I added and here
![manufacture-1](https://github.com/frappe/erpnext/assets/28384123/b0ee1e0c-e786-46c2-a7ad-cc9cde3a6cf2)

Bu missing here
![manufacture-missing](https://github.com/frappe/erpnext/assets/28384123/dbb35915-82c6-488c-a460-451a45113619)

Best Regards!

### Module

stock

### Version

v14.42.0
v14.32.1

### Installation method

manual install

**Comment by ankush** [comment]
it's in manufacturing section
