### ISSUE TITLE
no pol filtration in api

### ISSUE THREAD

**Issue by siasty** [frappe/erpnext#36371]
### Information about bug

no pol filtration in api for a bank account when we take specyfic items

http://127.0.0.1:8000/api/resource/Bank Account/PKO - PKO?fields=["bank_account_no"]

![image](https://github.com/frappe/erpnext/assets/39690589/8d2de03e-0c75-4502-a9f0-7d5bc8362c0a)

### Module

accounts

### Version

frappe/erpnext/bench - latest

### Installation method

manual install

**Comment by ankush** [comment]
field filters don't apply when you are fetching single document. 

`/api/resource/doctype?field=["x"]&filters=[["name", "=", "doc name"]]`
