### ISSUE TITLE
Billing & roundoff account

### ISSUE THREAD

**Issue by robertbecht** [frappe/erpnext#3638]
Entered Purchase Invoice of standard supplier. Entered the discount he is giving us. Could not save.>> Message "specify roundoff account under company" I did this, reloaded, restarted Erpnext.
Message remained. Than removed the Discount (it was a very small amount :) ) and now could submitt the invoice without problems.

**Comment by rmehta** [comment]
@robertbecht did you add the Round Off account in your Company record? We have added a new account to round off decimal errors.

**Comment by robertbecht** [comment]
hi rushabh, no i used the standard roundoff account. Will look at the new
roundoff account, rgds robert

**Comment by strixaluco** [comment]
Please post questions to [discuss.erpnext.com](https://discuss.erpnext.com)
