### ISSUE TITLE
Item Code: CP_0001 is not available under warehouse .

### ISSUE THREAD

**Issue by muneerobeidat** [frappe/erpnext#36398]
### Information about bug

Item Code: CP_0001 is not available under warehouse .
<img width="1043" alt="Screenshot 2023-07-29 at 7 25 48 AM" src="https://github.com/frappe/erpnext/assets/140870356/bb092217-3021-4f97-9479-9089d740033d">

### Module

stock

### Version

latest

### Installation method

None

**Comment by s-aga-r** [comment]
@muneerobeidat Based on the message Item **CP_0001** don't have stock in the selected warehouse.
