### ISSUE TITLE
Default admin password does not work

### ISSUE THREAD

**Issue by martinzerty** [frappe/erpnext#36392]
### Information about bug

I have installed erpnext succefully on permise.
But once at the login page, the credentials pair:
user: Administrator
password: admin

fails to give me access to ERPNext..
can anyone have tips to give me please ? thx

### Module

accounts

### Version

Bench 5.16.4
Frappe 14.42.0
erpnext 14.32.1

### Installation method

manual install

**Comment by shoaib0300** [comment]
@martinzerty 100% SOLVED

Enter Bench Console:

Enter the Bench console by running the following command:

bench --site sitename console

Replace sitename with the name of the site for which you want to reset the password.

Reset the Password:

Once you are in the Bench console for the specific site, you can reset the password using Python code. Here's an example of how to reset the password for the Administrator user:

from frappe.utils import set_user_password
set_user_password("Administrator", "new_password")

Replace "new_password" with the desired new password for the Administrator user. Make sure to enclose the username and password in double quotes.

Save and Exit the Console:

After setting the new password, you can save the changes and exit the Bench console by pressing Ctrl + D or entering exit().

**Comment by msbcs** [comment]
ImportError : cannot import name 'set_user_password' from frappe.utils

**Comment by PatrickSchutte** [comment]
> ImportError : cannot import name 'set_user_password' from frappe.utils

```
from frappe.commands.site import set_user_password
set_user_password(user="Administrator", password="password", site="mysite.com")
```
This works for me.

**Comment by martinzerty** [comment]
Thank you all for your help. I don't use it anymore. It never worked for me. The erpnext application never worked on any server I tried, even in a docker container.
