### ISSUE TITLE
Bug when customer views tickets raised by employee

### ISSUE THREAD

**Issue by justinlusg** [frappe/erpnext#3643]
![image](https://cloud.githubusercontent.com/assets/12539216/8651524/fbd63294-29ab-11e5-8528-d96c029c55af.png)

Steps to replicate
1) Employee raised support ticket via issues
2) Enter in customer email address in Raised By (Email) field
3) Customer logs in to Web Portal and click on issue

**Comment by justinlusg** [comment]
The same error appears when customer emails in. 

Steps to replicate
1) Customer (Web User) email to support@agtech.com.sg
2) Email get retrieved and a ticket is created 
3) Customer logs in as web user
4) Click on Issues

**Comment by rmehta** [comment]
@justinlusg we are re-designing the portal UI and merging it with the bench #3677

**Comment by justinlusg** [comment]
Cool!
