### ISSUE TITLE
In the Sales Invoice list the Grand Total is not the same as inside the item view

### ISSUE THREAD

**Issue by nissekalle0** [frappe/erpnext#36444]
### Information about bug

![Screenshot from 2023-08-01 11-45-19](https://github.com/frappe/erpnext/assets/88166895/1c68dc6a-f32d-40c3-a0c7-6269ae521936)

The Grand total is with decimals even if it has been rounded inside the item view f.i.115.163,75 should have been 115.164,00

### Module

accounts

### Version

Latests

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
No errors
```

**Comment by Nihantra-Patel** [comment]
Hi @nissekalle0,

Everything is working fine. No problems were encountered in the latest versions 14 and 15.
Kindly upgrade to version 14 or 15, then refresh and check again.

If the issue occurs then please create a new issue according to version (14 or 15) with a video document if possible.

Thank You!
