### ISSUE TITLE
Mastodon integration

### ISSUE THREAD

**Issue by weddige** [frappe/erpnext#36463]
**Is your feature request related to a problem? Please describe.**
We are using LinkedIn and Mastodon (Our Twitter community left the platform and thus Twitter doesn't work for us anymore) for social media and I would love to manage social media posts in ERPNext.

**Describe the solution you'd like**
I would like to have a mastodon integration analogue to the Twitter integration.

**Describe alternatives you've considered**
The alternative is to continue to manage the accounts manually and not use ERPNext for it.

**Comment by ankush** [comment]
New integrations won't be added in core apps. These can be built as separate apps.
