### ISSUE TITLE
Time Overlap & Round-Down Error 

### ISSUE THREAD

**Issue by latelladuboyce** [frappe/erpnext#3647]
We needed to write a code to automate a refresh when our employees received the time overlap error. When they input 10AM-2PM, then received the error and input 10:00:01AM-2PM, the hours would automatically update to 3.999 hours which was frustrating for them. Now when they input a new 10:00:01AM-2PM, it updates to 10:00:01AM-2:00:01PM. I understand why the system doesn't allow for time overlaps, but as a company we don't care about having our employees tasks logged to the second. We are currently trying to develop a way to override this error. Furthermore, when inputting 4.5 hours as an hourly float and pressing "Save", the system rounds the float down to 4 hours.

**Comment by rmehta** [comment]
Fixed.

**Comment by latelladuboyce** [comment]
Hi Rushabh, 
Will the fix come in the next update? I've been receiving more complaints about our time logs. The system takes the information, saves it to the nearest hundredth of an hour (as specified), but then once submitted, it rounds the hours down to the nearest integer and changes the end time as well. The odd thing is that the proper information is still correctly stored in the calendar view. See the attached screen shots for confirmation. The first photo is of the calendar, the following three are the log sheets submitted for that day. 
![erpnext calendar week view](https://cloud.githubusercontent.com/assets/13245890/8728295/36d25578-2b99-11e5-9fd6-aef051ba4bda.png) 
![erpnext tl-00228](https://cloud.githubusercontent.com/assets/13245890/8728482/3489d222-2b9a-11e5-837c-59a026787a96.png)
![erpnext tl-00214](https://cloud.githubusercontent.com/assets/13245890/8728357/8094af30-2b99-11e5-9b5d-63bb94f61050.png)
![erpnext tl-00215](https://cloud.githubusercontent.com/assets/13245890/8728420/dc87306a-2b99-11e5-8969-e246cefb06c5.png)

**Comment by rmehta** [comment]
This is already fixed. Should come in the next update.
