### ISSUE TITLE
No update of the Bank reconciliation popup in the Bank Reconciliation tool

### ISSUE THREAD

**Issue by nissekalle0** [frappe/erpnext#36482]
### Information about bug

In the Bank Reconciliation Tool you click on the Actions button of an item. A popup of current alternatives come up but not all untill you click on any of the Filters checkboxes then the list refreshes

### Module

accounts

### Version

Latest

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
No errors
```

**Comment by Nihantra-Patel** [comment]
Some issues might be fixed in the newer version so Kindly upgrade to version 14 or 15, then refresh and check again because lots of bugs are fixed in the new version.

Thank You!
