### ISSUE TITLE
Merge Asset

### ISSUE THREAD

**Issue by precihole** [frappe/erpnext#36499]
Is there any option where we can merge 2 or 3 different asset and then create one asset like Computer,Mouse,CPU & Keyboard will be merge and create one asset.

**Is your feature request related to a problem? Please describe.**
If we establish numerous assets such as a computer, mouse, CPU, and keyboard, we will be unable to detect when the computer, CPU, mouse, and keyboard are in pair, and we will also need to check the total cost of the workstation. Also consider the necessity to consolidate all of these costs into a single capital item.

**Describe the solution you'd like**
There should be one document that merges all assets and creates a new asset with the value of all merged assets.

**Comment by anandbaburajan** [comment]
@precihole you can use the [Asset Capitalization](https://docs.erpnext.com/docs/user/manual/en/asset-capitalization#3-convert-one-or-more-assets-into-a-new-asset) feature.

**Comment by precihole** [comment]
Thanks @anandbaburajan
