### ISSUE TITLE
Sales invoice can not connect to delivery note at connections

### ISSUE THREAD

**Issue by JasonFu06** [frappe/erpnext#36513]
### Information about bug

When click delivery note button at sales invoice's connections area, there is no associated delivery note information. because a parameter is missing in the sales_invoice_dashboard.py file

  "Delivery Note": ["items", "delivery_note"], 

correct code :

"internal_links": {			
     "Delivery Note": ["items", "delivery_note"], 
     "Sales Order": ["items", "sales_order"],
     "Timesheet": ["timesheets", "time_sheet"],
},

### Module

accounts

### Version

Frappe Version - 14.43.1    13.58.4
Erpnext Version - 14.33.2   13.52.8

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
from frappe import _


def get_data():
	return {
		"fieldname": "sales_invoice",
		"non_standard_fieldnames": {
			"Delivery Note": "against_sales_invoice",
			"Journal Entry": "reference_name",
			"Payment Entry": "reference_name",
			"Payment Request": "reference_name",
			"Sales Invoice": "return_against",
			"Auto Repeat": "reference_document",
			"Purchase Invoice": "inter_company_invoice_reference",
		},
		"internal_links": {			
                        "Sales Order": ["items", "sales_order"],
			"Timesheet": ["timesheets", "time_sheet"],
		},
		"transactions": [
			{
				"label": _("Payment"),
				"items": [
					"Payment Entry",
					"Payment Request",
					"Journal Entry",
					"Invoice Discounting",
					"Dunning",
				],
			},
			{"label": _("Reference"), "items": ["Timesheet", "Delivery Note", "Sales Order"]},
			{"label": _("Returns"), "items": ["Sales Invoice"]},
			{"label": _("Subscription"), "items": ["Auto Repeat"]},
			{"label": _("Internal Transfers"), "items": ["Purchase Invoice"]},
		],
	}
```

**Comment by anandbaburajan** [comment]
Already fixed in #36183
