### ISSUE TITLE
Dsicount Account Option in selling

### ISSUE THREAD

**Issue by TahaEzoubi** [frappe/erpnext#36529]
### Information about bug

when we select the discount account option in the selling setting.

in a multi-currency site, this option works smoothly when we use a sales invoice in the base currency 

but when we use the discount in the other currency, it a message appears that the difference between the base_discount_amount and the discount_amount is more than zero

although it's the same amount in different currencies

https://github.com/frappe/erpnext/assets/106906789/954eebb4-c677-4739-9c5d-f2f8f3f87d26

### Module

selling

### Version

Frappe Framework: v14.42.0 (HEAD)

ERPNext: v14.32.1 (HEAD)

### Installation method

None

**Comment by AlghryaneeAnees** [comment]
I'm facing the same issue
