### ISSUE TITLE
Allow to make return against sales invoice which has closed sales order.

### ISSUE THREAD

**Issue by techomniflo** [frappe/erpnext#36537]
Hello everyone,

I would like to make a feature request regarding the ability to process returns against a sales invoice that is associated with a closed sales order. Currently, it is quite frustrating to have to first reopen a closed sales order in order to mark a return on a sales invoice, and then close the sales order again.

Customers often return items due to various reasons such as store damage, expiry, or other issues. Dealing with these returns efficiently is essential, but the current process is time-consuming and not user-friendly.

I suggest implementing a more straightforward and user-friendly approach that allows us to process returns directly on the sales invoice, even if the related sales order is closed. This would greatly improve the efficiency of handling return transactions and provide a better experience for both our staff and customers.

Thank you for considering this feature request.

**Comment by bosue** [comment]
Fixed in #36676, may be closed.
