### ISSUE TITLE
Shipping Order based on Delivery Note

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#3655]
For Drop Shipment in marketplaces, fulfillment is done by the supplier and the marketplace earns a commission

- [ ] Delivery Note & Sales Order of Type **Shipping Order**
- [ ] Supplier Field in DN & SO in document and item
- [ ] Set default Supplier in Item
- [ ] Buying Rate in item table (as in purchase via default buying price list / pricing rule)
- [ ] Calculate difference in **Grand Total based on Buying Rate** and **Grand Total** as **Gross Margin / Commission** (Listing Fees)

---

- [ ] Payment received against Sales Order in Escrow Account or **Marketplace Payments**, not Receivables
- [ ] From Sales Order in **Make Delivery Note** you should be able to select by supplier.
- [ ] Payment made against Shipping Order from Escrow
- [ ] Commission Invoice against Shipping Order (button next to **Gross Margin**) against Marketplace Payments

**Comment by prash4** [comment]
Used for Ecommerce companies

**Comment by rmehta** [comment]
@prash4 did you get my mail? We can barter this against your magento app,

**Comment by prash4** [comment]
Hello,
We an Ecommerce company , and we operate as a market place model as well as warehouse model
So below features are required for the same

Sales order - when we submit the sales order , we should get the option to select marketplace model or ware house model . When we select market place model , we need below steps

Shipping Order - Where no physical delivery is made , just an order to ship - We should select supplier and customer in the shipping order

Buying price - So when we place a order to supplier, we will send him details of buying and selling price

Listing fees/Commission - , it will be the difference between the buying price and selling price

Payment receipt from customers - As we are collecting payment on behalf of supplier , we need to keep in a different account , and we will the supplier from that account , so we will maintain it supplier wise

Commission invoice - we will raise the invoice of commission / listing fees to the supplier ( this will difference of buying and selling price )

**Comment by umairsy** [comment]
As per the latest discussion:

- [ ] One receipt of order from Customer, Sales Order will be created, of type Drop Shipment.
- [ ] Purchase Order will be created as Shipping Order.
- [ ] In Purchase Order, details will be fetched from Sales Order. Sales Order details like Customer details, Item and its selling price will be fetched into Purchase Order.
- [ ] Purchase Order of type Shipping Order will carry Customer and Supplier details.
- [ ] Sales Order wise Gross Profit report, only for drop shipment orders.

**Comment by prash4** [comment]
Great ,

**Comment by rmehta** [comment]
Merged into #4089
