### ISSUE TITLE
Purchase Invoice: Tax break down not calculated until the record has been saved

### ISSUE THREAD

**Issue by nissekalle0** [frappe/erpnext#36553]
### Information about bug

You have to save the record in Purchase Invoice until you can get the Tax breakdown.

Solution: Automatically update without saving when necessary values have been entered

### Module

accounts

### Version

Latest

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
None
```

**Comment by Nihantra-Patel** [comment]
Sometimes, certain functions rely on a specific concept, so JavaScript doesn't always work. In these cases, we might need to use Python instead. This is especially true when there are many calculations involved in validation, making it challenging to update values promptly when they change. I hope you understand.

Thank You!
