### ISSUE TITLE
The Unallocated field does not change after removing a payment row in Payment Entry

### ISSUE THREAD

**Issue by nissekalle0** [frappe/erpnext#36565]
### Information about bug

In Payment Entry all payments of a supplier comes up.
If you delete a row you don't want to pay  then the Unallocated field below does not change and the sum is wrong and the invoice becomes not fully paid.

It seems to happen if an invoice with lower order value is removed then just part of the other invoice is allocated and part becomes unallocated.

Solution: recalculate, update, refresh after deletion

### Module

accounts

### Version

Latest

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
none
```

**Comment by Nihantra-Patel** [comment]
Hi @nissekalle0,

Everything is working fine. No problems were encountered in versions 14 and 15.
Kindly upgrade to version 14 or 15, then refresh and check again.

https://github.com/frappe/erpnext/assets/141945075/60166989-8bed-47d4-91fb-b53babcc0410

Thank You!
