### ISSUE TITLE
Doctype: Appointment Letter - In this doctype the field "Appointment Letter Template" should not be as mandatory

### ISSUE THREAD

**Issue by Antony-M1** [frappe/erpnext#36583]
### Information about bug

I'm trying to create an appointment I can see the doctype name called **Appointment Letter Template** there is one field called **Introduction** It should be in a **Text Editor**. The reason is when I'm create a formate and use that format in doctype **Appointment Letter** I'ts showing without space. as well as there is no formed structure this one issue.

In the doctype **Appointment Letter** there is field called **Appointment Letter Template** that field should be non mandatory. because sometimes I want to create **Appointment Letter** without a template.

I can see this issue in erpnext 13, 14, 15-beta

### Module

HR

### Version

Frappe Version: 13, 14, 15-beta
ERPNext Version: 13, 14, 15-beta

### Installation method

None

**Comment by Nihantra-Patel** [comment]
Hi @Antony-M1,

> I'm trying to create an appointment I can see the doctype name called Appointment Letter Template there is one field called Introduction It should be in a Text Editor. The reason is when I'm create a formate and use that format in doctype Appointment Letter I'ts showing without space. as well as there is no formed structure this one issue.

It's made to fit what the user or client needs. If you want to suggest changes to the [HRMS](https://github.com/frappe/hrms/pulls) app, you can submit a Pull Request.

> In the doctype Appointment Letter there is field called Appointment Letter Template that field should be non mandatory. because sometimes I want to create Appointment Letter without a template.

Also, in the Appointment Letter, you can make a non-mandatory by using the Property Setter for Appointment Letter Template. This is a significant change, you can easily so solved it.

**We no longer provide support for version 13 or older.**

Thank You!
