### ISSUE TITLE
Auto Create Assets on Purchase - are created only with Purchase Receipt, but not with Purchase Invoice

### ISSUE THREAD

**Issue by tinodj** [frappe/erpnext#36603]
### Information about bug

As title says - when Auto Create Assets on Purchase for a fixed asset item is enabled, Assets are auto-created only when submitting Purchase Receipt, but not when submitting Purchase Invoice. I understand that PR has to do with material accounting, and PI has to do with Financial accounting. However, I am not sure whether this is by design or not. 

In the documentation: 

https://docs.erpnext.com/docs/user/manual/en/asset-asset

it is well explained and everywhere it talks only for PR, but at one place also for PI: 
`On submission of a Purchase Receipt/Purchase Invoice with that Item a message is shown indicating that you need to create assets manually. `

This is not true, on submission of PI no message is shown, nor attempt is made to create an asset. 

Also, from some companies perspective, would be much easier creating one document, e.g. PI and to serve as PR as well, to reflect Material and Financial accounting. 

### Module

buying, assets

### Version

ERPNext: v14.29.1
Frappe Framework: v14.40.1

### Installation method

docker

**Comment by nabinhait** [comment]
The system automatically creates an asset even from the Purchase Invoice if "Update Stock" is checked in PI.
