### ISSUE TITLE
Bug in Promotional Scheme/Pricing Rule when Rate is applied

### ISSUE THREAD

**Issue by ajit-jain1** [frappe/erpnext#36616]
### Information about bug

So, the when the pricing rule gets applied on mixed Conditions - there is a bug where by the values are not cleared off and double discount happens on one or two of the items.

For example -
The promotion scheme is set up as under

![image](https://github.com/frappe/erpnext/assets/19492543/308b75ca-1986-4d0e-83e4-754f525da5e2)image
![image](https://github.com/frappe/erpnext/assets/19492543/0e61287d-b572-4e4c-b5ae-4250e9339992)
![image](https://github.com/frappe/erpnext/assets/19492543/0143f8c8-c223-4afc-af38-c97155f2f537)

and accordingly 3 pricing rules are created.

So now when creating a sales order or a delivery note -

while adding the items

![image](https://github.com/frappe/erpnext/assets/19492543/59572ba3-74e3-4947-bff2-9a65ed22004a)
![image](https://github.com/frappe/erpnext/assets/19492543/be44ac9b-b865-46e0-819f-b27ae216e9b6)

After saving we are getting these values which are no where part of the pricing rule
![image](https://github.com/frappe/erpnext/assets/19492543/75d00ee2-82e1-4ddf-a955-bbf851bedbb6)

Also after deleting/reducing the quantity the pricing rule is not reversed
![image](https://github.com/frappe/erpnext/assets/19492543/45e4f9bd-afda-4c06-bf71-29c3b3141738)

I think this has to do with a temporary variable storing the total qty for the mixed condition to be true which is not getting emptied correctly before every step.

I hope I am able to explain the issue at hand.

### Module

selling, other

### Version

Frappe Verison - 14.42.0
ERP Version - 14.32.1

### Installation method

None

**Comment by Nihantra-Patel** [comment]
Hi @ajit-jain1,

Kindly upgrade to version 14 or 15, then refresh and check again because lots of bugs fixed in the new version.

Everything is working fine. No problems were encountered in the latest versions 14 and 15.
If the issue occurs then please create a new issue according to version (14 or 15) with a video document if possible.

Thank You!
