### ISSUE TITLE
Unable to select income account while creating pose profile. It only allows creating a new account rather than selecting existing one

### ISSUE THREAD

**Issue by kumuduraj** [frappe/erpnext#36622]
### Information about bug

Unable to select income account while creating pose profile. It only allows creating a new account rather than selecting existing one

### Module

selling

### Version

14

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Unable to select income account while creating pose profile. It only allows creating a new account rather than selecting existing one
```

**Comment by nabinhait** [comment]
Can't replicate
