### ISSUE TITLE
Appointment requests from web create event's with Guest as the owner

### ISSUE THREAD

**Issue by conncampbell** [frappe/erpnext#36648]
### Information about bug

When creating a appointment request from the website, the generated event document has the owner set as Guest instead of the sales representative.  This causes the sales rep to not have access to the calendar information.

Perhaps it would be better to add the sales rep employee as a participant, and update the event permissions check to allow participant employees access...

### Module

CRM

### Version

ERPNext: v13.52.9 (version-13)
Frappe Framework: v13.58.5 (version-13)

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
We no longer provide support for version 13 or older.

Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!
