### ISSUE TITLE
Selling rate not pulled correctly

### ISSUE THREAD

**Issue by ajiragroup** [frappe/erpnext#36641]
### Information about bug

Lets create an item, while doing so, lets keep the standard selling rate = 10.

Lets go to Item Price Doctype, find the newly created item and update the standard selling rate to 150. And hit save, of course.

Go back to the newly created item, and check reponses, the rate is still the same (10).

While creating sales order/quotation, it pulls 150 but somehow this value is not updated.

![image](https://github.com/frappe/erpnext/assets/108009061/52eee64b-3bbc-42f1-9110-de3c7dc13f1b)

### Module

other

### Version

erpnext 14.12.1
frappe 14.22.1
hrms 1.0.0
payments 0.0.1

### Installation method

None

**Comment by s-aga-r** [comment]
@ajiragroup The Item Master `Standard Selling Rate` is just used to create a default Item Price with Price List as `Standard Buying`. The documents (Sales Order/Purchase Order etc) get buying/selling rate from the Price List.
