### ISSUE TITLE
Cancel Payment Entry Bug

### ISSUE THREAD

**Issue by BelalShatara** [frappe/erpnext#36655]
### Information about bug

If we have a Payment Entry, we need to use it in the sales invoice (Advance Payment)
If we cancel the payment entry the status for the sales invoice will be Overdue, but now it's been Submitted.

![5f9e43b4-881d-4436-aff2-789a0addf442](https://github.com/frappe/erpnext/assets/55027843/2778cc46-bbcc-4ec0-adee-20f5c4c629b6)
![7db05129-220b-4792-b265-86692da80ebd](https://github.com/frappe/erpnext/assets/55027843/8499fe64-ee7a-4bb8-bbc6-1cc61af1abef)

### Module

accounts

### Version

Frappe v14.44.0
ERPNext v14.24.1

### Installation method

docker

**Comment by nabinhait** [comment]
Seems like it has been fixed in latest version, can't replicate.
