### ISSUE TITLE
Stock GL Accounts Allow Journal Entry Even When Account Type is Set to Stock

### ISSUE THREAD

**Issue by allenemotive** [frappe/erpnext#36665]
### Information about bug

When a user creates a Journal Entry, the ERPNext is allowing an update to a Stock Account even when the Account Type is set to Stock.  In previous versions of ERPNext, the software would not allow a transaction to update the balance on an account with the type Stock.  For example, the error message was Account: 1310 - Stock In Hand - "SA" Can only be updated via Stock Transactions.  Of course, if you changed the Account Type to anything other than "Stock", the software would allow a JE.  That is fine.  We need to correct the software so users are not allowed to perform a JE when the account type is set to "Stock".  Users are allowed to get their inventory balance out of balance as a result of this issue.  This is urgent.  It happens in Version "ERPNext: v14.31.3 (version-14)" and Other Versions of ERPNext.  I don't know specifically what version the bug was introduced.  I do know that the alert worked and restricted the user from posting the transaction is prior releases.

### Module

accounts, stock

### Version

Frappe Framework: v14.41.0 (version-14)
ERPNext: v14.31.3 (version-14)

Older Version Alert:
![Screenshot 2023-08-15 at 11 37 42 AM](https://github.com/frappe/erpnext/assets/112016365/7a7192ee-d839-4aae-9f88-afbe922aca1a)

### Installation method

None

**Comment by nabinhait** [comment]
This is not an error, we allowed journal entries against stock account if stock balance (stock module) and account balance for stock accounts are mismatched. This is required to match the balance by posting a Journal Entry.
