### ISSUE TITLE
Workflow - Sales Order - Billing and Delivery Status is not updated/replaced with final workflow status

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#3667]
In the attached screenshot, Status column refer to the value of final approval status of Sales Order, as defined via Workflow.

In the Standard Sales Order, Based on the Delivery Note and Sales Invoice created against Sales Order, status like Not Billed, Not Delivered, Overdue is updated in the Sales Order. If this case, where Workflow is applied, status of delivery and billing is not updated, but final approval status remains in its place.

![screen shot 2015-07-15 at 6 21 56 pm](https://cloud.githubusercontent.com/assets/910238/8717147/1fe3db9e-2bb6-11e5-8ff0-e6e272ae3a88.png)

**Comment by rmehta** [comment]
There is only one column for indicator, if workflow is used it will override standard workflow.

**Comment by cgpurbaugh** [comment]
If that's the case, then shouldn't it be possible to re-create the standard workflow, within the custom workflow, so that no functionality is lost?

**Comment by anandpdoshi** [comment]
Yes, you can manually add the standard statuses as one of the Workflow States or make it part of the Workflow State label.

**Comment by cgpurbaugh** [comment]
But, there is no way to update the status from another document with the replacement workflow, which is very necessary.  You can make the names the same, but it won't update itself.

**Comment by cgpurbaugh** [comment]
This can be closed.  I resolved the problem with custom scripts.

**Comment by PITPL-Kaushal-Khute** [comment]
same problem i am facing @cgpurbaugh  can you shared custom scripts.  i am also duplicate sales order and delivery note but in my doctype Billing and Delivery status not updated plz help me
