### ISSUE TITLE
Warehouse-wise Sales Report

### ISSUE THREAD

**Issue by jof2jc** [frappe/erpnext#3668]
Currently I cannot see sales details on all available sales reports by warehouse (e.g. sales register, item-wise sales register, sales analytic, sales invoice trends etc). So as work-around, I use Territory (one territory for each warehouse with same name, because most sales reports using territory).

But it would be better to have warehouse filter on all sales reports, so Territory is used more for regional tracking...because one territory usually can have one or more warehouses.

**Comment by rmehta** [comment]
Can you be specific?

**Comment by jof2jc** [comment]
I mean  warehouse field and filter on sales reports like sales register, sales trends, sales analytic.. so users can analyze sales performance per warehouse...

**Comment by PawanMeh** [comment]
Added additional filters to Sales Register and sent PR

**Comment by PawanMeh** [comment]
Closing this, as sales register has the relevant filters now and is merged into develop. If there is anything another issue can be opened.
