### ISSUE TITLE
On Sales Invoice : Quantity dispalying in fraction.

### ISSUE THREAD

**Issue by geetanjalishitole** [frappe/erpnext#3669]
Steps -1
Sales Order SO-0001  contains the following details 
Item-------Qty --------Rate ------- Amount 
XYZ-------  1  ---------500  --------- 500

Steps - 2
For above sales order , I have created Sales Invoice SI-0001
Item-------Qty --------Rate ------- Amount 
XYZ-------  1  ---------200  --------- 200    (Rate given as less than rate defined in sales order)

Step - 3
Again If we open Sales Invoice form from above sales order then following details displaying 
 Item-----------Qty --------Rate ------ Amount 
XYZ-------- 0.6000 ------500  ------  300

**Comment by rmehta** [comment]
@nabinhait can you replicate?

**Comment by nabinhait** [comment]
@rmehta Yes, currently it worked that way only. It determined by billed amount, and pending qty is calculated based on pending amt.
