### ISSUE TITLE
Streamline subcontracting workflow

### ISSUE THREAD

**Issue by SvbZ3r0** [frappe/erpnext#36704]
Currently, the Subcontracting workflow includes 2 seperate Receipt entries. One in the Subcontracting Receipt linked to the Subcontracting Order, and another in the Purchase Receipt linked to the Purchase Order.

In a Subcontracting PO, the billed material is a non-stock Item (service). Therefore, a Purchase Receipt for the service Item doesn't make any sense. If the FG is delivered, then the service has been performed. If the RM is returned, then the service has not been performed. So, the Subcontracting Receipt and Purchase Receipt both contain the same information.

To make things easier, the Purchase Receipt should be automatically created based on Subcontracting Receipt entry.

**Comment by frewper** [comment]
@SvbZ3r0 

I have seen the use for Purchase Receipt, in Subcontracting Order, when the purchase team and operations team work independently. 

Because Purchase Order needs to be raised and approved everytime, and the Operations folks cannot send out material before the PO is approved, hence it is necessary. 

Also there are cases when the subcontracting is over, and the items come back, there is just a challan, which indicates the items are returned. And the final Invoice comes much later. So it makes sense that the operations folks only close the SCO and not create the purchase receipt. And to give purchase control to the purchase folks, its better the PR is not made when the SCO receipt is made. 

If you could highlight specific use cases rather than generic ones, it would be more essential.

**Comment by SvbZ3r0** [comment]
I don't understand the problem in the scenario you mention.
The operation team still has full control after the PO is raised  by using the Subcontracting Order -> Subcontracting Receipt workflow. The purchase team still has control over invoicing. There is just one less entry to be made manually.

Can you give an example of when Subcontracting Receipt is not the same as the Purchase Receipt?

**Comment by frewper** [comment]
I have explained clearly on the last paragraph (or second last). My answer still remains the same.  Please let me know what you have not understood

**Comment by bosue** [comment]
I’m not into Subcontracting, so my expertise may be limited, but the two obvious solutions if both usecases are valid would be:

- add an option to Subcontracting Settings, like „Auto-create Purchase Receipt based on Subcontracting Receipt“ and/or
- add a „Create Purchase Receipt“ action on the Subcontracting Receipt.

Both should simplify this task, and the two of you resp. we all may debate whether one or the other or both may be the best solution? 😉 @SvbZ3r0 @frewper

**Comment by SvbZ3r0** [comment]
Yes, that would make a lot of sense. I don't know why I didn't think of that despite being the type to complain that a niche feature should have just been made optional instead of being removed.

**Comment by bosue** [comment]
Now which of the two would you guys prefer?

Or would a combination of both be useful and not just “niche”?

- add an option to Subcontracting Settings, like „Auto-create Purchase Receipt based on Subcontracting Receipt“ _**and**_
- add a „Create Purchase Receipt“ action on the Subcontracting Receipt if Auto-creation is off.

Subcontracting doesn’t have too many settings, so adding one more shouldn’t be a UX degradation, if this is a commonly needed feature for subcontracting.

Yet another option:

- Always auto-create Purchase Receipt based on the Subcontracting Receipt if the user has permission to do so _**and**_
- Add a „Create Purchase Receipt“ action on the Subcontracting Receipt for users with permission to do so (e.g. the other department), unless the Purchase Receipt has already been auto-created.

You guys who are using Subcontracting need to figure out which solution you prefer. Sorry, but I won’t start writing a PR until you guys have agreed upon one or the other. 💁🏻‍♂️

**Comment by TurkerTunali** [comment]
I think that Purchase Receipt can be skipped. We can directly issue an Purchase Invoice from the Purchase Order.

"Subcontracting Receipt" and "Send to Subcontractor" are only required stock transactions.

**Comment by bosue** [comment]
@TurkerTunali: in principle, Purchase Receipts may not be necessary. But I can see @frewper‘s point that one and the other may be handled in separate departments and/or with delay. And I can see that for controlling reports having a Purchase Receipt may be deemed necessary to have all transactions covered.

In the end I‘m not involved enough as we don‘t use subcontracting. Ready to help, but the main effort will have to come from ppl using this feature day by day… 🤷🏻‍♂️

But the one step forward we should be able to go without sacrificing any flexibility is:

> - add an option to Subcontracting Settings, like „Auto-create Purchase Receipt based on Subcontracting Receipt“ and
> - add a „Create Purchase Receipt“ action on the Subcontracting Receipt if Auto-creation is off.

**Comment by SvbZ3r0** [comment]
@bosue i would prefer an auto create option but would settle for a "create purchase receipt" button.

Again, i don't see a business use case at all for a separate purchase receipt and scr since they are literally the same thing, so i might be biased in my preferences.

**Comment by bosue** [comment]
I guess I should step aside. I’m not the one using Subcontracting, so can’t really help with finding a good or even the best solution… 🤷🏻‍♂️

**Comment by s-aga-r** [comment]
Planning for:
- Auto create Subcontracting Order (Draft/Submit) on Purchase Order submission.
- Auto create Purchase Receipt on Subcontracting Receipt submission.
- Subcontracting Receipt LCV.

@SvbZ3r0 @frewper @bosue @TurkerTunali

**Comment by SvbZ3r0** [comment]
Thanks @s-aga-r . Sounds great!

What is LCV btw?

**Comment by s-aga-r** [comment]
> What is LCV btw?

[Landed Cost Voucher](https://docs.erpnext.com/docs/user/manual/en/stock-transactions-landed-cost-voucher)
