### ISSUE TITLE
Invalid "depends_on" expression on many module after restore the site

### ISSUE THREAD

**Issue by QuakeString** [frappe/erpnext#36702]
### Information about bug

I've taken backup(db/privte-files/public-files/site-config) of my site from prvious installatin which was as normal installation. 
Then erpnext was Production Branch Version - 14.26 or so ( not remember exactly.
Now I've install erpnext on docker (Production branch version-14) as per official guide. and restore my previous site.
Most of the things works but few things does not.
1. `Sales Invoice` form does not appear, its just blank
![2023-08-17_23-43_1](https://github.com/frappe/erpnext/assets/5375918/afc3b3ab-1ac6-4df9-8a5b-087448021b78)
2. There is error on  address module, Item module, `Invalid "depends_on" expression`
![2023-08-17_23-44](https://github.com/frappe/erpnext/assets/5375918/acc8c598-3544-405e-a863-3fffb356f4e1)
![2023-08-17_23-43](https://github.com/frappe/erpnext/assets/5375918/43c09e59-418c-4fac-b739-97261fee3905)
3. I've tried to update using `bench update --reset` it does output a error. 
![Screenshot_20230817_161725](https://github.com/frappe/erpnext/assets/5375918/f3c34e75-b9a3-4f5e-a460-adbb7f7dc346)
4. I've tried to installed the same system in another server, and got exactly same result. 

### Module

accounts, selling, HR

### Version

```
erpnext 14.34.3
frappe 14.44.0
hrms 14.10.0
india_compliance 14.15.1
payments 0.0.1
whitelabel 0.0.1
```

### Installation method

docker

**Comment by deepeshgarg007** [comment]
@QuakeString This looks like some customization issue, closing this

**Comment by shamsi2u** [comment]
have same error

**Comment by QuakeString** [comment]
> have same error

as @deepeshgarg007  replied, it is customization error cause by India_Compliance. 
and I see there is is depends  on field of "Item-get_hsn_code"
when I removed that code, I can add item, but still the issue of invoice form not showing up is persist, and India_compliance dev told me it may be issue of js & CSS so `bench build` may fix it, but once I did that, my complete site got broken and now its looks like as 2nd pic

![2023-10-08_06-54](https://github.com/frappe/erpnext/assets/5375918/c1dd823a-1822-4a35-9e30-c522e01482f3)

![2023-10-08_08-23](https://github.com/frappe/erpnext/assets/5375918/803b9e60-00fa-497c-a9b0-688a8295ed80)
