### ISSUE TITLE
A journal entry is booked against Exchange Gain/Loss on submit payment entry

### ISSUE THREAD

**Issue by maxfu9** [frappe/erpnext#36703]
### Information about bug

When I submit a payment entry against an expense claim, in the background, a journal entry is booked against Exchange Gain/Loss.

### Module

accounts

### Version

ERPNext: v14.35.1 (version-14)
Frappe Framework: v14.45.0 (version-14)

### Installation method

None

**Comment by frewper** [comment]
@maxfu9  Please can you add the expected behaviour as well. Would help define the behaviour
