### ISSUE TITLE
In Journal Entry change the Title does not update

### ISSUE THREAD

**Issue by nissekalle0** [frappe/erpnext#36718]
### Information about bug

If the title of a Journal Entry item has been changed, the header field with the new Title  is not updated until later with several reloads.

### Module

accounts

### Version

Latest

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
None
```

**Comment by Nihantra-Patel** [comment]
It's worked depending on the condition, so please check it.

https://github.com/frappe/erpnext/blob/5f376009d04d641b0076e392144902a5bd78581c/erpnext/accounts/doctype/journal_entry/journal_entry.py#L229-L230
