### ISSUE TITLE
System notification for new releases (erpnext, frappe & future plug-ins)

### ISSUE THREAD

**Issue by raveslave** [frappe/erpnext#3671]
As a start, it would be nice to see the latest official release under "System -> Application Installer".

i.e. 
Installed Version: v5.0.13
There is a new version v5.2.0 available _[link to release-notes]_

As an addition, the system itself could email out a notification to registered admins to notify when a new software release or security patch has been released.

**Comment by kennethsequeira** [comment]
This enables the update for installed apps in the system:

https://github.com/frappe/frappe/pull/5960
