### ISSUE TITLE
Sales Order Stopped status no longer working

### ISSUE THREAD

**Issue by monojoker** [frappe/erpnext#3672]
Guys,

Previously there used to be a Stop "button" for placing Sales Orders on Stop. There is no longer this button and using the report list, ticking the box beside and pressing Menu -> Stop doesn't work. Has a recent update caused this? I know we were previously able to stop Sales Orders as we have a few on that status. See screenshots for full story:

1. SOs currently Stopped:

![image](https://cloud.githubusercontent.com/assets/10917366/8740542/908306d0-2c8e-11e5-9085-137d3933b823.png)

2. Attempt to place SO on Stop now:

![image](https://cloud.githubusercontent.com/assets/10917366/8740547/b24ff53e-2c8e-11e5-921e-722f99e469dc.png)

3. Job is not placed on Stop:

![image](https://cloud.githubusercontent.com/assets/10917366/8740597/6acf86b0-2c8f-11e5-8359-a40c6f730e22.png)

Please advise if the process has changed or how to do this - we place SOs on stop if significant delays are encountered or they need to be halted but continued at a later stage.

Thanks
Liam.

**Comment by rmehta** [comment]
@monojoker the SO is on stopped, but the indicator (there can be only one value!) is taken over by Workflow. If you are using Worfkow and Stopped, I recommend you add a stopped state too.

**Comment by monojoker** [comment]
But previous jobs on Stop have this notification on form:

![image](https://cloud.githubusercontent.com/assets/10917366/8740814/788d245c-2c93-11e5-80de-e3bd70b578a5.png)

Other workflow states also:

![image](https://cloud.githubusercontent.com/assets/10917366/8740818/8fcda498-2c93-11e5-9bb8-6b608ac7e062.png)

What's changed or different with this newest SO?

**Comment by rmehta** [comment]
Seems like an issue. Let me check.

**Comment by anandpdoshi** [comment]
@monojoker is your workflow changing the value of "Status" field in Sales Order, maybe in the "Pre-Press" state?

**Comment by monojoker** [comment]
@anandpdoshi I don't think so, can you tell from the below? The only field I update on workflow_state change is workflow_state itself...

![image](https://cloud.githubusercontent.com/assets/10917366/8769262/81b4a8c0-2edc-11e5-9a66-8ddd51a0e669.png)

**Comment by monojoker** [comment]
And on Final workflow_state that triggers a Submit. Otherwise nothing in workflow is setup to affect status.

**Comment by anandpdoshi** [comment]
Does this happen only for this particular document or for many others? Can
you identify a pattern?

**Comment by monojoker** [comment]
All documents are affected, it seems the STOP ability just disappeared recently. As we do not STOP SOs daily I cannot tell you EXACTLY the date it has gone. If I look at the Demo system it still allows STOP but when a SO is set to that status it shows on the report list as such. On my report list it shows a different value - eg final or complete. It appears once again a conflict between Workflow and Status. Why can't they be treated independently?

**Comment by anandpdoshi** [comment]
They are independent. It is just how they are displayed in the indicator
that is different. I think this wasn't considered while designing. As a
workaround, you can add a Stop status in your workflow, or if you see the
"Unstop" button in the form, the Sales Order is stopped.

**Comment by monojoker** [comment]
Can't see the Unstop button in the form - that's basically how I know the SO hasn't moved to Stopped. I can setup a Workflow workaround but is that the best result? A "permanent" workaround for something that's been changed (inadvertantly) and thus impacts our process...

**Comment by anandpdoshi** [comment]
Can you send me the details of how to recreate the workflow that you are
using? I will need it to reproduce this issue.

**Comment by monojoker** [comment]
Sure @anandpdoshi should I email the setup directly with screenshots? Otherwise you can logon to our system with the user logon i created for you guys. I will email details. Please do not make any changes but you can see the setup there. Let me know. Thanks.

**Comment by anandpdoshi** [comment]
Liam, I will try to reproduce this issue in my dev environment and get back
to you.

**Comment by monojoker** [comment]
Please close as @anandpdoshi has educated me that only Submitted document can be placed on Stop. Thankyou.

**Comment by cgpurbaugh** [comment]
@anandpdoshi This can be closed.
