### ISSUE TITLE
We are facing the issue in UOM at the time every documents saving

### ISSUE THREAD

**Issue by Daffygroup** [frappe/erpnext#36732]
### Information about bug

![image](https://github.com/frappe/erpnext/assets/120366779/97f8cf76-cd49-4f95-975c-35bdb7119dd7)

### Module

buying

### Version

v0.2.1 (HEAD)

### Installation method

None

**Comment by Daffygroup** [comment]
Please clear the same on urgent basis  we are facing the more problems in Buying,stock,requesting invoicing etc.

**Comment by Daffygroup** [comment]
Dear Team, We are facing the issue for Save the any documents. 

Error massage is showing in UOM.


![image](https://github.com/frappe/erpnext/assets/120366779/15447fce-dc91-4e4e-a12a-35f9867b03e4)

**Comment by Daffygroup** [comment]
Dear Team,

No one resolve the issue .

kindly resolve the issue top most priority.

**Comment by thida-bcn** [comment]
> Dear Team,
> 
> No one resolve the issue .
> 
> kindly resolve the issue top most priority.

go to UOM and edit " must be whole number" to uncheck
![image](https://github.com/frappe/erpnext/assets/62122640/85bedcfb-328a-4202-9826-289df6b65a62)
