### ISSUE TITLE
ERPNext on iPhone: Last line of Calendar cut off, and 3 more Responsive layout errors 

### ISSUE THREAD

**Issue by superlack** [frappe/erpnext#3674]
1)  When using ERPNext's Calendar on an iPhone (5s, personally) in Chrome or Safari, there are only 4 calendar lines, which don't always coincide with the month if it happens to roll over that for the remaining day or few.

1b)  I'm not sure if this is a result of the drag functions of the calendar that negate the ability to scroll down the page.   (Also an issue, when trying to move up or down the calendar page, the only "handle" to scroll is a small section at the header, and it can't be retrieved when its scrolled past)

2) I noticed that when customizing columns for any reports, it allows the user to create, drag, and re-arrange, but can't change the field name.

3) When returning to the ERPNext login page from after logging out, and the autofill information on my phone is suggesting the username/password, i'll press it, but the fields remain empty

**Comment by rmehta** [comment]
Thanks for reporting, but please read:

https://github.com/frappe/erpnext/blob/develop/CONTRIBUTING.md

1. Each issue separately
2. Screenshots if possible.
