### ISSUE TITLE
iPhone: Last line of Calendar cut off

### ISSUE THREAD

**Issue by superlack** [frappe/erpnext#3675]
When using ERPNext's Calendar on an iPhone (5s, personally) in Chrome or Safari, there are only 4 calendar lines, which don't always coincide with the month if it happens to roll over that for the remaining day or few. 
![image1](https://cloud.githubusercontent.com/assets/12856084/8741187/d20c07da-2c09-11e5-8f57-7852802a4c10.PNG)

**Comment by netchampfaris** [comment]
@superlack So, 5 rows instead of 4 should do?

**Comment by superlack** [comment]
Great, thanks for looking into it!
