### ISSUE TITLE
"Inter Company Purchase Order" Is Not Created In The "Sales Order" form

### ISSUE THREAD

**Issue by Triplem8360** [frappe/erpnext#36765]
### Information about bug

The same bug is true in the "Purchase Order" form ...
These operation work correctly in the "Sales Invoice" and "Purchase Invoice" forms ...

Probably, the get_received_items() method in the sales_invoice.py (also its equivalent in the purchase_invoice.py form) should be revised and if the document is created and the field values are transferred, it should be checked whether the created document can be saved or not.

### Module

buying, selling

### Version

Frappe Version 13.41.1
ERPNext Version 13.39.0

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
pymysql.err.OperationalError: (1054, "Unknown column 'tabPurchase Order.inter_company_invoice_reference' in 'where clause'")
```

**Comment by tundebabzy** [comment]
This is actually fixed by #38826
