### ISSUE TITLE
None of the Help topic links are working

### ISSUE THREAD

**Issue by maveezmh** [frappe/erpnext#36784]
### Information about bug

when you goto help dropdown on a certain documents there is option to see document specific help as in the screenshot

![image](https://github.com/frappe/erpnext/assets/112148467/6114ca96-82cf-4565-b995-99338d258bbc)

in above screenshot none of the help topic links are working except documentation

![image](https://github.com/frappe/erpnext/assets/112148467/f755f5f0-9615-4c37-854b-01a2d2ba37ad)

### Module

accounts, stock, buying, selling, HR, projects, support, CRM, assets

### Version

V14

### Installation method

FrappeCloud

**Comment by deepeshgarg007** [comment]
@maveezmh I just checked and all links seem to be working fine, please recheck and reopen the issue if it still persists with more details

**Comment by maveezmh** [comment]
![image](https://github.com/frappe/erpnext/assets/112148467/69d73506-c729-4599-b97a-ca86f1c5cda8)

@deepeshgarg007  some of the links are working some are not working i guess those are not mapped properly

for instance for recurring sales invoices its taking me to below link

https://docs.erpnext.com/docs/user/manual/en/recurring-orders-and-invoices

![image](https://github.com/frappe/erpnext/assets/112148467/4dcb825f-3295-4953-bca0-0874d02a7643)
