### ISSUE TITLE
Disable Add Batch Nos on entering item on stock entry - v15

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#36787]
### Information about bug

In V15, after capturing qty, and saving a stock entry(transaction), system auto picks batch nos, which is great.

Issue is, minute an item is selected, the below auto dialog pops up, I don't it's necessary.

![image](https://github.com/frappe/erpnext/assets/1822868/9a1387a6-4f6b-4b61-8797-d532767ec22b)

### Module

stock

### Version

ERPNext: v15.0.0-dev (HEAD)
Frappe Framework: v15.0.0-dev (HEAD

### Installation method

FrappeCloud

**Comment by rohitwaghchaure** [comment]
You can disable the dialog box 
<img width="1321" alt="Screenshot 2023-08-25 at 2 05 41 PM" src="https://github.com/frappe/erpnext/assets/8780500/d7435f15-ee97-44e6-afe1-1fa2cdd4113a">
