### ISSUE TITLE
Work order picks a different item from the raw material defined in the BOM - v15

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#36788]
### Information about bug

Work order picks a different item from the raw material defined in the BOM - v15

### Module

manufacturing

### Version

ERPNext: v15.0.0-dev (HEAD)
Frappe Framework: v15.0.0-dev (HEAD)

### Installation method

FrappeCloud

**Comment by rohitwaghchaure** [comment]
@muchai I have tested and it's working fine.

It would be helpful if you could provide the steps to replicate the issue.

**Comment by muchai** [comment]
@rohitwaghchaure let me share steps in a few.
