### ISSUE TITLE
after restore database  I have error  with bench update  command

### ISSUE THREAD

**Issue by ahmedbahgattt** [frappe/erpnext#36790]
### Information about bug

after restore database  I have error  with bench update  command

I receive error message 
Cannot proceed with update: You have local changes in app "hrms" that are not committed.

### Module

HR

### Version

erpnext 14.36.0
frappe 14.46.0
hrms 14.10.1

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Cannot proceed with update: You have local changes in app "hrms" that are not committed.

Here are your choices:

1. Merge the hrms app manually with "git pull" / "git pull --rebase" and fix conflicts.
1. Temporarily remove your changes with "git stash" or discard them completely
        with "bench update --reset" or for individual repositries "git reset --hard"
2. If your changes are helpful for others, send in a pull request via GitHub and
        wait for them to be merged in the core.
```

**Comment by viralkansodiya** [comment]
user this command if you change in direct repository
cd ../hrms
git status
take a backup of this code in notpade
git stash

bench update

**Comment by deepeshgarg007** [comment]
@ahmedbahgattt This is not a core product issue but due to some local changes you are unable to update, not the right place for such issues.

Closing this
