### ISSUE TITLE
Statement of account/general ledger report doesn't display transaction currency code, but the default base currency code

### ISSUE THREAD

**Issue by muchai** [frappe/erpnext#36801]
### Information about bug

The transactions below are all in USD, not KES.

![image](https://github.com/frappe/erpnext/assets/1822868/13d960f6-1743-4b73-bf23-b838844da21e)

The opening, and closing balances display correct currency code.

Explicitly picking currency code on the general ledger, before printing, displays the correct currency code
![image](https://github.com/frappe/erpnext/assets/1822868/14b8bc3b-2ffa-46c5-9a72-d539110d2b29)

### Module

accounts

### Version

ERPNext: v14.36.0 (HEAD)
Frappe Framework: v14.46.0 (HEAD)

### Installation method

FrappeCloud

**Comment by GursheenK** [comment]
We couldn't replicate this issue due to a validation set for disallowing transactions for the same Customer in different currencies. Please provide the exact steps to replicate this issue.

**Comment by GursheenK** [comment]
Please re-open the issue if it is replicable in the latest release for v14.
