### ISSUE TITLE
Stock Balance Report Decimal issue

### ISSUE THREAD

**Issue by thida-bcn** [frappe/erpnext#36812]
### Information about bug

![image](https://github.com/frappe/erpnext/assets/62122640/08903f0e-2de6-44f4-bfb4-3ed269e02299)
system settings >> currency precision set to 2
stock balance
in value, out value and valuation rate shown 5 decimal places
![image](https://github.com/frappe/erpnext/assets/62122640/12465dfc-51b2-430e-8795-07bb9213bf2e)
expected result  must be 2 decimal places

### Module

stock

### Version

frappe 14.46.0
erpnext 14.36.0

### Installation method

manual install

**Comment by rohitwaghchaure** [comment]
@thida-bcn 
Some customers prefer to view the valuation rate value with a decimal point, based on the Float Precision, while others prefer it based on Currency Precision. Could we incorporate a filter for precision in the stock balance report?

**Comment by thida-bcn** [comment]
> @thida-bcn Some customers prefer to view the valuation rate value with a decimal point, based on the Float Precision, while others prefer it based on Currency Precision. Could we incorporate a filter for precision in the stock balance report?

it's a good ideas
If you can add, filter for precision, it would be great
thank you

**Comment by rohitwaghchaure** [comment]
@thida-bcn Fixed https://github.com/frappe/erpnext/pull/36866

Default set as Currency in the filter

**Comment by thida-bcn** [comment]
> @thida-bcn Fixed #36866
> 
> Default set as Currency in the filter

thank you, we will check

**Comment by thida-bcn** [comment]
> @thida-bcn Fixed #36866
> 
> Default set as Currency in the filter

thanks

**Comment by thida-bcn** [comment]
> @thida-bcn Fixed #36866
> 
> Default set as Currency in the filter

hello,
I supposed something wrong
when i choose currenty, it was shown 2 decimal place
when i choose float, it was shown 5 decimal place
Actually,
you should comply with system settings decimal place
![image](https://github.com/frappe/erpnext/assets/62122640/5ea5f33e-cf6a-4161-a76c-8f1247d64149)
some of our customer using 
float 5
Currency 2
But other are using
float 5
currency 5 / 9

**Comment by rohitwaghchaure** [comment]
@thida-bcn This is difficult to handle in the core, maybe you create the custom report and handle the case as per the customer's requirement.
