### ISSUE TITLE
Fiscal Year Value Not Fetched in Opportunity Doctype

### ISSUE THREAD

**Issue by dipalivaddoriya** [frappe/erpnext#36826]
### Information about bug

While using the Opportunity Doctype, Current fiscal year value is not getting fetched automatically by default.
If I am not wrong, This was encountered during creation of opportunity due to Fiscal Year data used for Naming Series. 
Using Erpnext Version - ERPNext: v14.36.0 (version-14)

<img width="1644" alt="Screenshot 2023-08-26 at 11 52 12 AM" src="https://github.com/frappe/erpnext/assets/13333125/b5b0d165-849b-48c2-8596-88ce49802e01">

### Module

CRM

### Version

ERPNext: v14.36.0 (version-14)

Frappe Framework: v14.46.0 (version-14)

Frappe HR: v15.0.0-dev (develop)

Payments: v0.0.1 (develop)

### Installation method

manual install

**Comment by deepeshgarg007** [comment]
@dipalivaddoriya We have deprecated the default fiscal year from Global Defaults, this looks like a custom field. You can set the default value using customize form here
