### ISSUE TITLE
Deadlock and Lock timeout issue with Stock Entry on v14

### ISSUE THREAD

**Issue by sinhpn92** [frappe/erpnext#36825]
### Information about bug

Hello,

We have multiple systems operating in the production environment, such as POS, Sales, and more. We are building an intermediate system to synchronize data to ERPNext, with the goal of eventually transitioning the entire system to utilize ERPNext. However, our system is complex and consists of multiple components, making it necessary to transition one part at a time. Thus, we have a service in place to synchronize data from our existing system to ERPNext, which runs at 3 am every day.

We are currently facing problems related to Deadlocks and Lock Timeout errors. Our synchronization service retrieves data from the running system and creates documents in ERPNext. Specifically, we are synchronizing data related to Stock Entry. Sales data from our POS, Sales, and other systems are synchronized to ERPNext. Everything works fine until this synchronization service is executed in the production environment. Each day, we have around 2-3 thousand orders being processed. When the synchronization service processes around 200-300 documents, Deadlock or Lock Timeout errors start occurring. We have tried restarting the bench, but the same errors persist upon reattempting the process.

Currently, we are using the Rest API to create documents. We have attempted to use the `api/resource` with the `frappe.client.insert_many` command to create multiple documents, and we’ve also tried the `api/resource/Stock%20Entry` to create individual documents, but the same errors occur.

What can be done to improve and resolve this situation? Thank you for taking the time to assist me. It would be greatly appreciated if we could address and rectify this issue.
<img width="671" alt="Screenshot 2023-08-26 at 11 14 45" src="https://github.com/frappe/erpnext/assets/9253441/581a245e-cc4e-4ae0-93c5-984c0954b29c">
<img width="702" alt="Screenshot 2023-08-26 at 11 14 15" src="https://github.com/frappe/erpnext/assets/9253441/0e1af202-f41c-4070-b474-5a4ab050eb9d">

<img width="579" alt="Screenshot 2023-08-26 at 11 15 15" src="https://github.com/frappe/erpnext/assets/9253441/37c6d14f-ed7c-4549-a82c-14eb69200756">
<img width="703" alt="Screenshot 2023-08-26 at 11 15 00" src="https://github.com/frappe/erpnext/assets/9253441/83907e36-9e45-4e6c-adf1-445a0412db6f">

### Module

stock

### Version

**ERPNext:** v14.36.0 (version-14)
**Frappe Framework:** v14.46.0 (version-14)
**Frappe Helper:** v0.3.3 (master)
**Frappe HR:** v14.10.2 (version-14)
**Restaurant:** v1.3.7 (master)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Timeout error:

{
      exception: "frappe.exceptions.QueryTimeoutError: (1205, 'Lock wait timeout exceeded; try restarting transaction')",
      exc: `["Traceback (most recent call last):\\n  File \\"apps/frappe/frappe/database/database.py\\", line 220, in sql\\n    self._cursor.execute(query, values)\\n  File \\"env/lib/python3.10/site-packages/pymysql/cursors.py\\", line 158, in execute\\n    result = self._query(query)\\n  File \\"env/lib/python3.10/site-packages/pymysql/cursors.py\\", line 325, in _query\\n    conn.query(q)\\n  File \\"env/lib/python3.10/site-packages/pymysql/connections.py\\", line 549, in query\\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\\n  File \\"env/lib/python3.10/site-packages/pymysql/connections.py\\", line 779, in _read_query_result\\n    result.read()\\n  File \\"env/lib/python3.10/site-packages/pymysql/connections.py\\", line 1157, in read\\n    first_packet = self.connection._read_packet()\\n  File \\"env/lib/python3.10/site-packages/pymysql/connections.py\\", line 729, in _read_packet\\n    packet.raise_for_error()\\n  File \\"env/lib/python3.10/site-packages/pymysql/protocol.py\\", line 221, in raise_for_error\\n    err.raise_mysql_exception(self._data)\\n  File \\"env/lib/python3.10/site-packages/pymysql/err.py\\", line 143, in raise_mysql_exception\\n    raise errorclass(errno, errval)\\npymysql.err.OperationalError: (1205, 'Lock wait timeout exceeded; try restarting transaction')\\n\\nThe above exception was the direct cause of the following exception:\\n\\nTraceback (most recent call last):\\n  File \\"apps/frappe/frappe/app.py\\", line 91, in application\\n    response = frappe.handler.handle()\\n  File \\"apps/frappe/frappe/handler.py\\", line 47, in handle\\n    data = execute_cmd(cmd)\\n  File \\"apps/frappe/frappe/handler.py\\", line 85, in execute_cmd\\n    return frappe.call(method, **frappe.form_dict)\\n  File \\"apps/frappe/frappe/__init__.py\\", line 1622, in call\\n    return fn(*args, **newargs)\\n  File \\"apps/frappe/frappe/client.py\\", line 215, in insert_many\\n    out.append(insert_doc(doc).name)\\n  File \\"apps/frappe/frappe/client.py\\", line 474, in insert_doc\\n    return frappe.get_doc(doc).insert()\\n  File \\"apps/frappe/frappe/model/document.py\\", line 274, in insert\\n    d.db_insert()\\n  File \\"apps/frappe/frappe/model/base_document.py\\", line 504, in db_insert\\n    frappe.db.sql(\\n  File \\"apps/frappe/frappe/database/database.py\\", line 229, in sql\\n    raise frappe.QueryTimeoutError(e) from e\\nfrappe.exceptions.QueryTimeoutError: (1205, 'Lock wait timeout exceeded; try restarting transaction')\\n"]`
    }
```

**Comment by osangs60** [comment]
increase HTTP timeout

**Comment by rohitwaghchaure** [comment]
@sinhpn92 

Based on the traceback it seems that you're updating the same stock entry from the different requests parallelly. To fix the issue you need to create a custom queuing system, through which you can insert one record at a time. Also instead of syncing the data run time, you can also sync closing stock of the day with the main system at the end of the day.
