### ISSUE TITLE
can’t do more than one payment entry for the sales order

### ISSUE THREAD

**Issue by badrbin** [frappe/erpnext#36834]
### Information about bug

We can’t do more than one payment entry for the sales order even has outstanding amount and get this alert
Sales Order SO230167 has already been partly paid. Please use the 'Get Outstanding Invoice' or the 'Get Outstanding Orders' button to get the latest outstanding amounts.

![IMG_0014](https://github.com/frappe/erpnext/assets/124630341/a6187336-4f5b-429b-8e87-446a9f255663)

### Module

accounts

### Version

ERPNext: v14.36.0 (HEAD)
Frappe Framework: v14.46.0 (HEAD)

### Installation method

FrappeCloud

**Comment by Nihantra-Patel** [comment]
Hi @badrbin,

I think you should check the [Forum Post and video](https://discuss.frappe.io/t/make-multiple-linked-payment-entries-against-a-single-sales-order/108907/2?u=ncp).

I hope this helps.

Thank You!

**Comment by ruthra-kumar** [comment]
@badrbin 
Fixed by https://github.com/frappe/erpnext/pull/36844
Should be available in the upcoming weekly release.
