### ISSUE TITLE
Fiscal Year  'Set as Default' button missing for version 14

### ISSUE THREAD

**Issue by thida-bcn** [frappe/erpnext#36831]
### Information about bug

![image](https://github.com/frappe/erpnext/assets/62122640/4d0c2a57-ebd1-4769-ae09-d5e9501a09c4)
version 13

![image](https://github.com/frappe/erpnext/assets/62122640/49bceb0d-ffb6-4457-a88e-912b5d4b01a8)
version 14 
is this feature remove?

### Module

accounts

### Version

frappe 14.46.0
erpnext 14.36.0

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
Hi @thida-bcn,

A global default for fiscal is not actually needed. Users don't set the fiscal year directly in any document anyways. The fiscal year should be auto-set based on the posting date of the transaction......

More details for check the PR: #35960

I hope this helps.

Thank You!

**Comment by aphchoo** [comment]
I have recently  restored database from v14.22.3 to a v14.45.4 test instance with live data. The missing Fiscal Year has affected a lot of accounting function, for many dashboard charts are using Fiscal Year as a filter it also affected PnL, Balance Sheet reporting.
