### ISSUE TITLE
Error in UOM

### ISSUE THREAD

**Issue by Daffygroup** [frappe/erpnext#36838]
### Information about bug

Dear Frappe Team,

We are facing the issue for saving the every documents below error is coming ,

kindly solve the issue on urgent basis.

![image](https://github.com/frappe/erpnext/assets/120366779/8cba03f3-19aa-452d-acc1-ce3f4fc49600)

Any clarification call us-9627552918

### Module

accounts, stock, buying, selling

### Version

v0.2.1 (HEAD)

### Installation method

None

**Comment by s-aga-r** [comment]
@Daffygroup seems related to customization, please check your custom scripts once.

**Comment by deepeshgarg007** [comment]
@Daffygroup This is not replicable, closing this issue
