### ISSUE TITLE
Asking Round off account and cost center 

### ISSUE THREAD

**Issue by thida-bcn** [frappe/erpnext#36833]
### Information about bug

Global Default
![image](https://github.com/frappe/erpnext/assets/62122640/0c6bae2a-ad37-4678-a0d3-e386c447ea04)
Company
![image](https://github.com/frappe/erpnext/assets/62122640/6293dfa7-5e46-4e32-b47b-272067beac3c)
sales invoice
Disable round total
amount was full number, no need to round off
![image](https://github.com/frappe/erpnext/assets/62122640/51b1c62a-d84e-4d01-90e8-4e22e054810e)
system asked for round off account / cost center
![image](https://github.com/frappe/erpnext/assets/62122640/c308808f-c149-4513-b99f-92c100fed81e)

### Module

accounts

### Version
frappe 14.46.0
erpnext 14.36.0

### Installation method

manual install

**Comment by nihantra** [comment]
Hi @thida-bcn,

I know you Disable Rounded Total but
If you haven't checked, please check the [documentation](https://docs.erpnext.com/docs/user/manual/en/round-off-account-validation).

I hope this helps.

Thank You!

**Comment by Nihantra-Patel** [comment]
Hi @thida-bcn,

I know you Disable Rounded Total but
If you haven't checked, please check the [documentation](https://docs.erpnext.com/docs/user/manual/en/round-off-account-validation).

I hope this helps.

Thank You!
