### ISSUE TITLE
Deferred Revenue and Expense Fields should be company wise

### ISSUE THREAD

**Issue by maveezmh** [frappe/erpnext#36841]
### Information about bug

in item master we can set only one account for deferred revenue and expenses. As erpnext has multiple companies there should be option to select the ledger company wise for deferred revenue and expenses

![image](https://github.com/frappe/erpnext/assets/112148467/8cfca734-b53c-46fd-9f2f-843e19fcefd4)

### Module

accounts

### Version

V13 V14

### Installation method

FrappeCloud

**Comment by deepeshgarg007** [comment]
@maveezmh Resolved via https://github.com/frappe/erpnext/pull/37023
