### ISSUE TITLE
after using remove_custom_button in client script , button will not remove in Mobile view

### ISSUE THREAD

**Issue by viralkansodiya** [frappe/erpnext#36845]
I have used this client script for Lead Doctype and it is working correct in desktop view but in mobile view that button still not removed

Client script:-

frappe.ui.form.on('Lead', {
        refresh: function(frm){                      
        frm.page.remove_inner_button('Prospect', 'Create')
        frm.page.remove_inner_button('Customer', 'Create')
        frm.page.remove_inner_button('Quotation', 'Create')
        frm.page.remove_inner_button('Add to Prospect', 'Action')
        }    
})
after applied this script desktop view is correct but for mobile view is not working
this image is for mobile view

![mobile view](https://github.com/frappe/erpnext/assets/141210323/ff4cf988-95ac-4d4d-bcaa-3e0489e49295)

### Module

CRM

### Version

Frappe version - v14.46.0
Erpnext version - v14.36.0

### Installation method

FrappeCloud

**Comment by Nihantra-Patel** [comment]
Hi @viralkansodiya,

Please apply it.

```js
frappe.ui.form.on('Lead', {
    refresh: function(frm) {
        setTimeout( () => {
            frm.page.remove_inner_button('Prospect', 'Create');
            frm.page.remove_inner_button('Customer', 'Create');
            frm.page.remove_inner_button('Quotation', 'Create');
            frm.page.remove_inner_button('Add to Prospect', 'Action');
            frm.page.menu.find('[data-label="Create%20%3E%20Customer"],\
            [data-label="Create%20%3E%20Quotation"],\
            [data-label="Create%20%3E%20Prospect"],\
            [data-label="Action%20%3E%20Add%20to%20Prospect"]').parent().parent().remove();
        }, 10);
    }
});
```

Then reload (Ctrl + Shift + R) and check it.

**Output:**

![image](https://github.com/frappe/erpnext/assets/141945075/f59e0dd0-46c8-4d19-acee-e11008bdaba0)

Thank You!

**Comment by viralkansodiya** [comment]
@Nihantra-Patel 
thanks Brother it is working Perfect
