### ISSUE TITLE
Filter group items for selection in Quick Entry form

### ISSUE THREAD

**Issue by bosue** [frappe/erpnext#36849]
While in the full-size DocType form, DocType links are correctly filtered to exclude group items:

![IMG_1368](https://github.com/frappe/frappe/assets/46800703/c276b28a-fb5a-44bb-9cbf-11de5505e2c7)

… in the quick entry form they’re not, so group items may be selected:

![IMG_1367](https://github.com/frappe/frappe/assets/46800703/f4b7976a-7002-4fd4-af2a-b553f2af80c6)

The latter should not be allowed. Atm unsure if this on Frappe’s or ERPNext’s side, but guessing it’s a general issue as the quick entry form is automatically rendered, not individually specified in a DocType.

**Comment by bosue** [comment]
Please move to the ERPNext queue.

While one may argue there should be some centralized code for all Frappe DocTypes that may be parametrized by a DocType‘s json, there currently isn‘t, so this applies to ERPNext.

**Comment by Nihantra-Patel** [comment]
Hi @bosue,

There is no built-in event or method to directly handle custom validation in the Quick Entry form. The Quick Entry form is designed for fast data entry and doesn’t provide the same level of customization as the full edit form.

But you can also use Python events to perform custom validation on the server side. By benefitting the before_save event in a custom Python script, you can validate the data before it is saved to the database.

Reference: https://discuss.frappe.io/t/quick-entry-doctype-events-are-not-working/106067/7?u=ncp

That for, Please go to the Server Script DocType and add the script.

```py
cg = frappe.get_doc("Customer Group", doc.customer_group)
if cg.is_group == 1:
    frappe.throw("You can't select the Parent Customer Group.")
```
![image](https://github.com/frappe/frappe/assets/99652762/200a6dd7-0e65-4da1-ab82-40fc15340dd1)

___

**Output:**

![image](https://github.com/frappe/frappe/assets/99652762/665b85ee-1253-40c7-bae6-95e0e38e0c5f)

Thank You!

**Comment by bosue** [comment]
Thank you! But surely, a filter may be applied to the select field's options?
Data integrity issues may be caught be validation, true.
But for UX simplicity and consistency, it seems desirable to filter select options in the Quick Entry form just the ways they're filtered in the full form.
And for DX and KISS, it would be wonderful if such a filter could be provided in the DocType's Json, to do away with custom JS.
How can I help?

**Comment by ankush** [comment]
We've allowed this for long time, so breaking it by default might not be ideal. 
You can add this as a setting in ERPNext if required.

**Comment by szufisher** [comment]
And for DX and KISS, it would be wonderful if such a filter could be provided in the DocType's Json, to do away with custom JS.
How can I help?

In odoo, it is called domain. if the filtering condition can be defined in doctype and customize form, then it can replace a lot of simple set_query js code.
