### ISSUE TITLE
Can we add Item Tax Template column in GST Itemised Purchase Register 

### ISSUE THREAD

**Issue by DipenFrappe** [frappe/erpnext#36864]
Can we add the Item Tax Template column in the GST Itemised Purchase Register? Customers are asking for this because it will help them to cross-check the tax % applied while booking the purchase invoice for each item and this help them to compile data for other GST reports like GSTR3B

**Comment by vorasmit** [comment]
Rate columns are already available. Wouldn't that serve the intended purpose? Please see the attached image for reference: 
![image](https://github.com/frappe/erpnext/assets/10496564/37f17260-8356-4ca6-a5d5-c079b8e58479)
