### ISSUE TITLE
shopping cart issue

### ISSUE THREAD

**Issue by hyx0908** [frappe/erpnext#36877]
### Information about bug

i am configuring e commerce on erpnext, i found a problem on shopping cart, when i entered shopping cart, if i changed the quantity by clicking the plus button or keying in. then the “request for quota” button no response no matter how many times you click it.

### Module

ecommerce

### Version

ERPNext: v14.22.2 (version-14)

Frappe Framework: v14.33.1 (version-14)

Frappe HR: v15.0.0-dev (develop)

Payments: v0.0.1 (develop)

### Installation method

manual install

**Comment by Noreen222** [comment]
Hello. I am facing a similar problem. 
Did you get the solution?

Regards,

**Comment by Nihantra-Patel** [comment]
Kindly upgrade to version 14 or 15, then refresh and check again because lots of bugs fixed in the new version.

Everything is working fine. No problems were encountered in the latest versions 14 and 15.
