### ISSUE TITLE
Payment Entry : Exchange Gain/ loss 

### ISSUE THREAD

**Issue by thida-bcn** [frappe/erpnext#36873]
at payment entry when we made payment for other currency customer
exchange  gain / loss entry posted by invoice
up to previous version only one JE per payment
current version posted JE per invoice
![image](https://github.com/frappe/erpnext/assets/62122640/342e0611-cf6a-4451-a972-a61de3fadc82)
JE
![image](https://github.com/frappe/erpnext/assets/62122640/424c30f0-a8c1-4635-9c32-48e8d94ba8c9)

Base USD
Customer Receivable Currency : CNY
Payment received in Currency : MMK
frappe 14.46.0
erpnext 14.36.0

**Comment by thida-bcn** [comment]
previous version
![image](https://github.com/frappe/erpnext/assets/62122640/f0bd0b5c-e2ab-41f8-adca-c324b27f0a47)
![image](https://github.com/frappe/erpnext/assets/62122640/dfda4e6f-6c32-4341-9460-b789a21c1f76)
 there was not extra gain/loss entry

**Comment by thida-bcn** [comment]
https://github.com/frappe/erpnext/assets/62122640/c324374f-f523-491a-b382-883bf9f92682

**Comment by ruthra-kumar** [comment]
@thida-bcn 

We did an internal refactor of how Exchange Gain/Loss amount is handled and going forward Exchange Gain/Loss amount incurred on transactions during reconciliation/linking will be posted through a Journal. This is part of a [larger effort](https://github.com/frappe/erpnext/issues/34680) to fix inconsistencies in multi currency invoicing. Journals will be created for each voucher in the references section of Payment Entry. These Journals are valid and are not be cancelled/deleted.

If deleted, ledger inconsistencies will arise.

**Comment by ruthra-kumar** [comment]
As for the difference amount being calcuated in Payment Entry upon adding outstanding invoices, that is a UI bug. We will be creating a fix for it.

**Comment by thida-bcn** [comment]
[payment reconcilation JE issue.webm](https://github.com/frappe/erpnext/assets/62122640/dba1f478-c059-4842-947d-38b5280be51c)
Payment reconcilation >> JE more than invoices

**Comment by thida-bcn** [comment]
we foud

> @thida-bcn
> 
> We did an internal refactor of how Exchange Gain/Loss amount is handled and going forward Exchange Gain/Loss amount incurred on transactions during reconciliation/linking will be posted through a Journal. This is part of a [larger effort](https://github.com/frappe/erpnext/issues/34680) to fix inconsistencies in multi currency invoicing. Journals will be created for each voucher in the references section of Payment Entry. These Journals are valid and are not be cancelled/deleted.
> 
> If deleted, ledger inconsistencies will arise.

we are facing another issue
Based in USD
Customer in CNY
Payment in MMK
![image](https://github.com/frappe/erpnext/assets/62122640/c0b7ef7c-9a51-45d2-94d7-96fe49cb7800)
customer settled 15000 CNY for 3 invoices
last invoice outstanding amount was wrong
![image](https://github.com/frappe/erpnext/assets/62122640/a2346577-6387-4e1d-8d06-d9f6dcdee141)
![image](https://github.com/frappe/erpnext/assets/62122640/506a7fe8-1dbb-40a9-9b26-7d511cffb7a2)

**Comment by thida-bcn** [comment]
Invoice Status was correct
but outstanding amout at payment is not correct
![image](https://github.com/frappe/erpnext/assets/62122640/0c16ea6b-9326-4256-838c-4dcc43b604ed)

**Comment by ruthra-kumar** [comment]
> [payment reconcilation JE issue.webm](https://github.com/frappe/erpnext/assets/62122640/dba1f478-c059-4842-947d-38b5280be51c)
> Payment reconcilation >> JE more than invoices

@thida-bcn 
https://github.com/frappe/erpnext/pull/36911 should fix the duplication issue
