### ISSUE TITLE
BUG - Item attributes

### ISSUE THREAD

**Issue by sliska** [frappe/erpnext#3687]
I deleted ALL of my items and transactions but it still won't let me delete the item attributes. It says the attributes are linked to items but there are no items!

**Comment by nabinhait** [comment]
How you deleted the items, from browser or directly from mysql terminal?

**Comment by sliska** [comment]
Hi Nabin,

I deleted them from the browser.

thanks,
Sofia

**Comment by rmehta** [comment]
@sliska yeah this could be an issue related to an upgrade.

@neilLasrado will deleting item also delete its attribute table (since its not offically a table now)

**Comment by neilLasrado** [comment]
@rmehta Yes deleting the template shall remove the variants and its attributes.
