### ISSUE TITLE
Notifications won't go away

### ISSUE THREAD

**Issue by sliska** [frappe/erpnext#3688]
Hello, I deleted all of my company's transactions but the notifications are still there. Why? How do I make them go away?

Thanks
Sofia

**Comment by nabinhait** [comment]
It should go away after reloading the system from Profile menu.

**Comment by sliska** [comment]
Hi Nabin,

I reloaded the system from my profile menu but the notifications remain. I
realize you all are busy but it would be good for the notifications to go
away after the user has completed the cycle of that notification and a new
notification should automatically appear to remind the user of the next
step.

For example, if it notifies me that there is a new purchase order and I
submit the purchase order, the notification should go away and a new one
should appear that says..."pending receipt of purchase invoice." When I
receive the purchase invoice form the supplier and submit it, the purchase
invoice notification should go away and a new notification that says
"pending payment" should appear. When I make the payment, a new
notification that says "pending receipt of goods" should appear, etc.

thanks,
Sofia Liska

**Comment by rmehta** [comment]
@sliska that is the way notifications are designed at the moment, they will remind you until you close them.

**Comment by cgpurbaugh** [comment]
We have the same issue here. Notifications will not go away until the next day.  For example, if there is an open sales order, there will be a notification.  If we make a sales invoice, there will be a new notification for sales invoice, but the sales order notification will not go away.  Refreshing/Reloading does nothing to fix this.

**Comment by yashodhank** [comment]
@sliska @cgpurbaugh considering new version 7 have advanced in various areas, please let us know if you still face this issue. I will reopen this issue if it persists provided you share screenshot, logs and version details of your setup and os etc.

**Comment by cgpurbaugh** [comment]
@yashodhank I will be deleting all company transactions next week, I can verify and document this then.  What sort of logs are you looking for?

**Comment by KanchanChauhan** [comment]
@cgpurbaugh Are you still facing same issue in v7? Are your notifications still there for deleted company transactions?
