### ISSUE TITLE
BUG exchange rates

### ISSUE THREAD

**Issue by sliska** [frappe/erpnext#3689]
![screen shot 2015-07-17 at 5 19 12 pm](https://cloud.githubusercontent.com/assets/13278512/8758952/55537d3c-2ca8-11e5-8ae4-6cffd7ce7c68.png)

There cannot be an exchange rate from one currency to the same currency. I cannot generate a supplier quotation from the material request because of this error message.

**Comment by nabinhait** [comment]
Could not replicate the issue. Might be due to custom script, do you have any customs script? Have you checked browser's console, is there any error message?

**Comment by kalintush** [comment]
I'm having the Same problem when creating an Invoice using invoice list. The older version doesn't have that error

**Comment by rmehta** [comment]
@kalintush  your custom script may be broken. Share your JS console.

**Comment by kalintush** [comment]
![captureerpnext](https://cloud.githubusercontent.com/assets/6616120/8849312/4d450864-315c-11e5-9b98-762fd341bb00.PNG)

**Comment by kalintush** [comment]
![image](https://cloud.githubusercontent.com/assets/6616120/8849371/9c34881e-315c-11e5-9f6a-e6e2ec4dc463.png)

**Comment by kalintush** [comment]
@rmehta I never used a custom script. I think it's a bug because this error message on invoice List is raising only one time.

**Comment by sliska** [comment]
@rmehta <https://github.com/rmehta> I didn't use a custom script either.

**Comment by cgpurbaugh** [comment]
Is this issue still valid?
