### ISSUE TITLE
Submit Sales Invoice very slow after large data stored

### ISSUE THREAD

**Issue by budi7** [frappe/erpnext#36891]
### Information about bug

First, thank you for this amazing framework..

i'm currently migrating my sales invoice data to erpnext.
first couple month my migration was smooth, but after my data quite large, it's getting slow to submit a sales invoice. it takes approx 4s to submit a data after my sales invoice data reached 89.109 data.

i'm trying to do slow log query and found that the problem was the slow query in function `update_company_current_month_sales` ([link](https://github.com/frappe/erpnext/blob/develop/erpnext/setup/doctype/company/company.py))

i think the problem was caused by the query used `DATE_FORMAT(`posting_date`, '%m-%Y') = ..` in `where` clause.
i tried to update the query,  so the output query will using `between` instead, and the result was satisfying.

#### TEST RESULTS

-----

SELECT
    SUM(base_grand_total) AS total,
    DATE_FORMAT(`posting_date`, '%m-%Y') AS month_year
FROM
    `tabSales Invoice`
WHERE
    DATE_FORMAT(`posting_date`, '%m-%Y') = '08-2023'
    AND docstatus = 1
    AND company = 'ACME'
GROUP BY
    month_year;

will result 3.290 sec, with total data  89.109 record 

---
SELECT
    SUM(base_grand_total) AS total,
    DATE_FORMAT(`posting_date`, '%m-%Y') AS month_year
FROM
    `tabSales Invoice`
WHERE
    `posting_date` BETWEEN '2023-08-01' AND '2023-08-31'
    AND docstatus = 1
    AND company = 'Nakoa'
GROUP BY
    month_year;

will result 0.001 sec, with total data  89.109 record 

---

pls correct me if i'm wrong, 
But if you think this can cause a problem, i can help with pr.
thanks..  

### Module

other

### Version

frappe 14.14.3
erpnext 14.6.0

### Installation method

manual install

**Comment by deepeshgarg007** [comment]
@budi7 You can change the default update frequency to "Monthly" instead of every transaction in Selling Settings.
We have already made this default to "Monthly" in the lastest v14 release.
