### ISSUE TITLE
bench init frappe-bench:got bad md5 warning

### ISSUE THREAD

**Issue by Jack--Wang** [frappe/erpnext#3690]
Dear All,
When I run following command to init frappe-bench.

eg:bench init frappe-bench

I will got this following warning info.
=========================
Already using interpreter /usr/local/opt/python/bin/python2.7
You are using pip version 6.1.1, however version 7.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 6.1.1, however version 7.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Cloning into 'frappe'...
remote: Counting objects: 2175, done.
remote: Compressing objects: 100% (1835/1835), done.
remote: Total 2175 (delta 854), reused 1322 (delta 299)
Receiving objects: 100% (2175/2175), 5.50 MiB | 270.00 KiB/s, done.
Resolving deltas: 100% (854/854), done.
Checking connectivity... done.
installing frappe
You are using pip version 6.1.1, however version 7.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
  Hash of the package https://pypi.python.org/packages/source/d/dropbox/dropbox-2.2.0.zip#md5=8f9bc437c19b34670aff2526e30c855a (from https://pypi.python.org/simple/dropbox/) (ca8cb4c896343e952e5b594e01c447c3) doesn't match the expected hash 8f9bc437c19b34670aff2526e30c855a!
  Bad md5 hash for package https://pypi.python.org/packages/source/d/dropbox/dropbox-2.2.0.zip#md5=8f9bc437c19b34670aff2526e30c855a (from https://pypi.python.org/simple/dropbox/)
Error: None
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 9, in <module>
    load_entry_point('bench==0.1', 'console_scripts', 'bench')()
  File "/Users/Jack/ERPBoostDev/bench-repo/bench/cli.py", line 38, in cli
    return bench()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/Users/Jack/ERPBoostDev/bench-repo/bench/cli.py", line 106, in init
    no_auto_update=no_auto_update, frappe_path=frappe_path, frappe_branch=frappe_branch)
  File "/Users/Jack/ERPBoostDev/bench-repo/bench/utils.py", line 49, in init
    get_app('frappe', frappe_path, branch=frappe_branch, bench=path)
  File "/Users/Jack/ERPBoostDev/bench-repo/bench/app.py", line 44, in get_app
    install_app(app, bench=bench)
  File "/Users/Jack/ERPBoostDev/bench-repo/bench/app.py", line 63, in install_app
    find_links=find_links))
  File "/Users/Jack/ERPBoostDev/bench-repo/bench/utils.py", line 61, in exec_cmd
    subprocess.check_call(cmd, cwd=cwd, shell=True)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'frappe-bench/env/bin/pip install -q  -e frappe-bench/apps/frappe' returned non-zero exit status 1
========================

and then I try to run it
eg:rappe-bench/env/bin/pip install -q  -e frappe-bench/apps/frappe
I will got following warnning info agin.
========================
You are using pip version 6.1.1, however version 7.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
  Hash of the package https://pypi.python.org/packages/source/d/dropbox/dropbox-2.2.0.zip#md5=8f9bc437c19b34670aff2526e30c855a (from https://pypi.python.org/simple/dropbox/) (ca8cb4c896343e952e5b594e01c447c3) doesn't match the expected hash 8f9bc437c19b34670aff2526e30c855a!
  Bad md5 hash for package https://pypi.python.org/packages/source/d/dropbox/dropbox-2.2.0.zip#md5=8f9bc437c19b34670aff2526e30c855a (from https://pypi.python.org/simple/dropbox/)
JackWang-PC:ERPBoostDev Jack$ 
========================

Could I how to solve this issue,everyone help me?
how to solve Bad md5?
Thanks a lot 
Jack.Wang

**Comment by yashodhank** [comment]
Upgrade your pip version
follow instructions: http://askubuntu.com/questions/599317/bad-md5-hash-for-package-https-pypi-python-org-packages-source-s-scikit-image
