### ISSUE TITLE
Feature Idea: More integrated barcoding

### ISSUE THREAD

**Issue by cgpurbaugh** [frappe/erpnext#3691]
If it was possible, It would be a good idea to introduce barcoding to ERPnext.  Here are some ideas:

1. Add an automatically generated barcode to the print format of all documents.  A user at a station should be able to scan this barcode while at the Desk, and the document open for them.

2. Add an automatically generated barcode for Item/Batch combination, and have the ability to print batch labels with all of the relevant information.  If you could match GS1-128 formatting, that would be something to boast about on your site.  This is a widely used international standard for shipping.

3. When entering information in stock transfer, one barcode should fill both the item and batch, then move to the next line.  This way the operator can scan multiple parts very quickly.

I don't know if this is possible, but I think it should be.  Barcode integration would be a huge thing for ERPnext.  Thanks for hearing my idea :)

**Comment by rmehta** [comment]
https://erpnext.com/pricing/paid-feature-development ?

**Comment by cgpurbaugh** [comment]
I can bring this up with upper management here for potential funding, but I need a quote.

**Comment by rmehta** [comment]
We can do this. https://github.com/frappe/frappe/issues/983

This will create a field type of Barcode that you can create for printing in any format and can be linked to any field (like Batch No / Item No)

- Excluding printing of batch labels (you can create an HTML format for that, or you will have to give us the format, but this should not be too hard) I anticipate 4 billable hours ($400).

Let us know!

**Comment by cgpurbaugh** [comment]
I will be bringing this up at the next meeting.  Will this allow us to fill both the item and batch with one barcode?

**Comment by rmehta** [comment]
If you select batch code, item is automatically selected.

**Comment by mhbu50** [comment]
Is this completed or what?
