### ISSUE TITLE
Custom Accounting Dimensions Not Updated in Budget Variance Report Filters

### ISSUE THREAD

**Issue by dmbabu** [frappe/erpnext#36957]
### Information about bug

**Information about bug**
When a custom Accounting Dimension is created, a filter corresponding to the Accounting Dimension is not created for Budget Variance Report (and perhaps others) and other HR doctypes. Only the default dimensions (Project and Cost Center) exist.

<img width="997" alt="image" src="https://github.com/frappe/erpnext/assets/45001106/d4d11b37-f5eb-42d6-a49b-ca53cc09ffa8">

### Module

accounts

### Version

ERPNext: v14.34.3 (version-14)
Frappe Framework: v14.45.0 (version-14)
Frappe HR: v14.10.0 (version-14)

### Installation method

manual install

**Comment by deepeshgarg007** [comment]
@dmbabu This is not replicable, closing this issue.
