### ISSUE TITLE
Need to configure Web API for sending mails.

### ISSUE THREAD

**Issue by maheshaddagatla** [frappe/erpnext#36951]
### Information about bug

Hi Team,

 We wanted to implement Web API for sending mail from ERP Next. As we have found vendor who is having WEB API and SMTP features both. We wanted to implement same for tracking the mails, details like, 2.Delivery confirmation (Delivered, Bounce, Mail Opened,Mail Deleted (if possible) Forwarded and Reply)
3.If the user hasn't opened an email for a week. Reminder email should be sent to both the recipient and the sender (option to enter message for reminder and also schedule time and period of reminder mail. 
4. If user not replied to mail also it should a reminder mail.(option to enter message for reminder and also schedule time and period of reminder mail.

One of vendor is having all these features with them. Need your help the same.

### Module

integrations

### Version

ERPNext: v13.51.4 (HEAD)

Frappe Framework: v13.57.0 (HEAD)

### Installation method

FrappeCloud

**Comment by maheshaddagatla** [comment]
Any updates on please ??

**Comment by s-aga-r** [comment]
@maheshaddagatla This is not the right place to ask for help. Use our [Community Forum](https://discuss.frappe.io/) or [Telegram Group](https://t.me/frappeframework).
