### ISSUE TITLE
Logic for not allowing change of Customer on Sales Invoice

### ISSUE THREAD

**Issue by monojoker** [frappe/erpnext#3695]
Hi Guys,

Probably just a question but I am having trouble seeing the logic behind not allowing the Customer to be changed on a Sales Invoice (one that's based on a Sales Order). So we've done work for a customer with a very similar name to another (same holding company, etc but different trading name). So we complete the Sales Order, invoice it and then the customer says "This invoice needs to go to Company X, not Company Y". So we cancel the Invoice and then choose Amend and try to change the customer. ERPNext says:

![image](https://cloud.githubusercontent.com/assets/10917366/8770976/17c04b0a-2efe-11e5-9c18-841afe273fa3.png)

I assume the "correct" way to remedy this is to raise a new Sales Order then take it through to invoicing but by that time we've quoted that Sales Order number in various documentation either to customer and/or to our own production staff so generating a new SO number is problematic. Are we unique in this respect? I'd have thought an option to allow change of customer between SO and SI would be acceptable and warranted.

Thanks.

**Comment by rmehta** [comment]
Configurable in selling settings?

**Comment by monojoker** [comment]
It would make sense to be there I agree!

**Comment by monojoker** [comment]
@rmehta do you think this is a useful enhancment and if so might it be included soon? We have a number of customers who run multiple business entities with similar names and that leads to orders sometimes making it all the way to submitting and billing without this being picked up. To change a customer for an invoice now we have to:

1. Cancel old sales order.
2. Duplicate old sales order and change customer.
3. Renumber all the production documentation and electronic files stored to the new SO number.
4. Raise a new invoice.

A simple ability to invoice with a different customer would be great.

Thanks
Liam.

**Comment by rmehta** [comment]
Adding to watchlist. Will try and get this done in a week or so.

**Comment by monojoker** [comment]
Hi @rmehta any luck with this one? Re-raising the sales order on one today and I thought I'd see how it's going :) Thanks.

**Comment by rmehta** [comment]
@monojoker sorry had been pretty busy with the conference. Will try for next week.

**Comment by monojoker** [comment]
Hey @rmehta is this one gonna make it in soon? :) Cheers.

**Comment by rmehta** [comment]
@monojoker Lots of issues to solve! Let me see. Thanks for reminding.

**Comment by monojoker** [comment]
Hi @rmehta, Happy New Year to you and the team, any progress or an ETA on this one? :)

**Comment by rmehta** [comment]
@nabinhait might get it done this week :)

**Comment by deepeshgarg007** [comment]
@monojoker a lot of things can be customer specific like item prices and taxes, terms and conditions. Changing the customer mid-sales cycle might leave an inconsistent state. Why not just create a stand-alone Sales Invoice just for such specific cases? Might allow changing customers in SO itself, but no plans yet, closing this
