### ISSUE TITLE
Purchase Receipt Provision Booking for Service item for Foreign Currency 

### ISSUE THREAD

**Issue by VARDHANA87** [frappe/erpnext#36959]
### Information about bug

On 01.09.2023

Company Posted 1/09/2023

Purchase Receipt 

Item X              100 qty @ rate 100 USD and exchange rate 75.797500000  = 7,57,975.00
Freight              1 QTY   500 USD  @ Exchange rate of 75.797500000           = 37,898.75

![image](https://github.com/frappe/erpnext/assets/79317458/4128784e-e2e8-43c8-b8b7-4ed03b48576a)

Purchase Invoice  dated 05/09/2023

Item X              100 qty @ rate 100 USD and exchange rate 75.797500000  = 7,57,975.00
Freight              1 QTY   500 USD  @ Exchange rate of 75.797500000           = 37,898.75

![image](https://github.com/frappe/erpnext/assets/79317458/18fb027d-77e1-4cce-9086-f801f03c511c)

landed cost Voucher Posted on 01/09/2023

The below is the attached Accounting Effect of Purchase Receipt Post landed Cost Voucher. / Purchase Invoice 

![image](https://github.com/frappe/erpnext/assets/79317458/09c37fa2-4777-4191-b071-5049da4edc60)

1. The Service Item rate is 500 USD, but the value getting debited is 500 rs whereas it should get debited 37898.750
2. Provision Accounting is not reversed post-booking of Purchase Invoice.

### Module

accounts, buying

### Version

4.47.2 (HEAD)
14.36.0 (HEAD)

### Installation method

FrappeCloud

**Comment by deepeshgarg007** [comment]
@VARDHANA87 This issue should be resolved now, please check.
