### ISSUE TITLE
Provision Booking for NON- SYSTEM CURRENCY 

### ISSUE THREAD

**Issue by VARDHANA87** [frappe/erpnext#36965]
### Information about bug

The user has booked the Purchase Receipt for the Service Received. 

5000 USD FOR Freight expenses ,accounting effect of Purchase Receipt Post Booking of the Purchase Invoice 

<img width="448" alt="image" src="https://github.com/frappe/erpnext/assets/79317458/d22d701d-55c7-4a0f-9499-95dc9c42ad83">

Whereas the accounting effect as per accounting or company currency is 3,78,987.50.

As per the Purchase Invoice 

<img width="758" alt="image" src="https://github.com/frappe/erpnext/assets/79317458/7540f1cb-2db9-4222-ab84-ebe2a1159d2e">

### Module

accounts

### Version

 v14.47.2 (HEAD)

v14.36.0 (HEAD)

### Installation method

FrappeCloud

**Comment by deepeshgarg007** [comment]
@VARDHANA87 This should be resolved now, please update your site and check
