### ISSUE TITLE
LDAP Configuration 

### ISSUE THREAD

**Issue by shubham-prabhat** [frappe/erpnext#36966]
### Information about bug

I want  to do , when user do log in by LDAP, then user should be automatic System user with speciefic role

### Module

assets

### Version

Frappe Framework: v14.36.0 (version-14)
ERPNext: v14.24.0 (version-14)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
When I log in as an ERP employee, the user's role is automatically changing to the default user role that I have set as an Account Manager. Can you ple
![Uploading Screenshot 2023-09-05 155013.png…]()
```

**Comment by s-aga-r** [comment]
@shubham-prabhat This is not the right place to ask queries, use our [Community Forum](https://discuss.frappe.io/) or [Telegram Group](https://t.me/frappeframework) for help.
