### ISSUE TITLE
Foreign Currency Customer Payment: Exchange Gain/ Loss

### ISSUE THREAD

**Issue by thida-bcn** [frappe/erpnext#36967]
### Information about bug

When we made payment for foreign currency
Example,
Posting Date : 30/08/2023
Creation Date : Today
Exchange / Gain Loss  Entry posted with Creation Date which caused uncorrect ledger when customer check up to posting date

Expected Result : Exchange / Gain Loss Entry posting date must be same as payment posting date

### Module

accounts

### Version

erpnext : 14.36.0
frappe:14.46.0

### Installation method

manual install

**Comment by thida-bcn** [comment]
[exchange gain loss posting date.webm](https://github.com/frappe/erpnext/assets/62122640/706dca27-ee65-49c4-91df-c594c6be61d1)

**Comment by ruthra-kumar** [comment]
@thida-bcn This had been addressed in https://github.com/frappe/erpnext/pull/36950.

**Comment by thida-bcn** [comment]
> @thida-bcn This had been addressed in #36950.

thank you
