### ISSUE TITLE
Disable system warning popups - config setting?

### ISSUE THREAD

**Issue by monojoker** [frappe/erpnext#3699]
Hi Guys,

For various reasons the system popups warning of duplicated item code and purchase order number within Sales documents is making processes difficult for us. Please provide quote to have a tickbox to turn these on or off if that is possible please.

Many thanks
Liam.

**Comment by rmehta** [comment]
Just those two? 

- [ ] Setting for duplicate item code in Sales
- [ ] Setting for duplicate purchase order

That will be 1 hour ($100)

**Comment by monojoker** [comment]
I'm a bit worried as I don't know what OTHER warnings exist in Sales. Do you have a list??? I'd be a bit disappointed getting paid development then realising we have to add to it - best to get it all done upfront :)

**Comment by monojoker** [comment]
@rmehta let's go with these 2, please send invoice and paypal details. Thanks, Liam.

**Comment by rmehta** [comment]
@monojoker Thanks! Will do asap :+1:

**Comment by monojoker** [comment]
Hi Guys, I'm going on leave for a week so might wait until back for this. Sorry I don't mean to mess you around just like to be here when it's migrated into our system in case of any issues - not that I expect any but you know just in case :) Thanks again!

**Comment by rmehta** [comment]
@monojoker no problem. We will try and get this done though. Have a good break!

**Comment by monojoker** [comment]
Just thought I'd check if I make payment today we're still good to go? Thanks, and I did have a good break, thanks @rmehta :)

**Comment by rmehta** [comment]
@monojoker Sure thanks. Will try and build this later today.
