### ISSUE TITLE
Request: We want to have an additional option (Half Yearly) in the Asset Maintenance Task child table  Sample PR:

### ISSUE THREAD

**Issue by Akkumaresh** [frappe/erpnext#36997]
Request: We want to have an additional option (half  Yearly) in the Asset Maintenance Task child table 

<img width="960" alt="Screenshot 2023-09-07 164413" src="https://github.com/frappe/erpnext/assets/138001414/d855fdbf-cd5e-47e8-8e34-4ac91c96ac22">

So kindly update this option

Sample PR:

**Comment by bosue** [comment]
Periodicity is used in [several places](https://github.com/search?q=repo%3Afrappe%2Ferpnext+Quarterly&type=code).

I think we should factor it out into its own DocType, so it may be reused everywhere in Core as well as in custom / contributed code. We would need periodicity for several custom modules as well, so I‘d happily take a stab at it.

**Comment by bosue** [comment]
Periodicity is also [used throughout Frappe](https://github.com/search?q=repo%3Afrappe%2Ffrappe+Quarterly&type=code), so I think a Perodicity DocType belongs there.

Should we offer a quick fix first and a more comprehensive solution thereafter, @Akkumaresh? Or can you use your own custom patch for now and just move over once the Periodicity DocType lands in Frappe?

**Comment by anandbaburajan** [comment]
Here's a similar PR raised recently: https://github.com/frappe/erpnext/pull/34641.

**Comment by bosue** [comment]
Another [related request](https://github.com/frappe/lending/issues/2) in frappe/lending, supporting the notion that this functionality should be generically available as a Frappe DocType.

I‘ll post a quick fix first though.

**Comment by anandbaburajan** [comment]
> this functionality should be generically available as a Frappe DocType.

@bosue seems like a good idea, please raise an issue on frappe.

**Comment by anandbaburajan** [comment]
@Akkumaresh, issue fixed by @bosue in https://github.com/frappe/erpnext/pull/37006.
