### ISSUE TITLE
Restore from backup make site_config.json currpted

### ISSUE THREAD

**Issue by SoCodeNow** [frappe/erpnext#36994]
### Information about bug

Fresh install in docker -> do not change anything and directly backup -> restore -> backup again : site_config.json  corrupted

### Module

other

### Version

Erpnext: 14.38.0 & 14.34.3
Frappe: 14.48.0 & 14.34.3

Both verion, on both on server an locally have the same issue.

### Installation method

docker

### Relevant log output / Stack trace / Full Error Message.

```shell
1. Make a fresh install to docker: docker-compose -f pwd.yml up
2. Get into docker container: docker exec -it erpnext-frontend-1 /bin/sh
3. Backup: bench backup --with-files --compress --backup-path /home/frappe/frappe-bench/sites/frontend/private/backups/0827
4. Restore: bench --force restore sites/frontend/private/backups/0827/20230827_093803-frontend-database.sql
5. Backup again: bench backup --with-files --compress --backup-path /home/frappe/frappe-bench/sites/frontend/private/backups/0906

Shows error: Backup failed for Site frontend. Database or site_config.json may be corrupted
```

**Comment by SoCodeNow** [comment]
BTW, the pwd.yml file in step 1 is downloaded from: 
https://github.com/frappe/frappe_docker/blob/main/pwd.yml

**Comment by SoCodeNow** [comment]
For anyone fall into the same issue, use "bench backup-all-sites" instead of "bench backup".

**Comment by SoCodeNow** [comment]
"bench backup-all-sites" worked for the firs serveral times. Now shows the same error again. I don't know why, any help is welcome.

**Comment by viralpatel15** [comment]
use encryption  key in your new site_config.json from your old site_config.json

may be that will help you

**Comment by SoCodeNow** [comment]
> use encryption key in your new site_config.json from your old site_config.json
> 
> may be that will help you

Thank you for your suggestion. But there is no luck. I replaced the encryption key in the site_config.json of the target server with the encryption key from source server. Then run "bench backup-all-sites", the error is the same:
`Backup failed for Site frontend. Database or site_config.json may be corrupted`

**Comment by SoCodeNow** [comment]
The error is still there, why is this issue closed?
