### ISSUE TITLE
Need an option for Accounting Dimension in Sales Order Item Table

### ISSUE THREAD

**Issue by sanjay141986** [frappe/erpnext#37005]
Hello,

Currently, We do not have an option to define the Accounting Dimension in the Sales Order Item table. Even after creating through Customization we are unable to add the same. 

![image](https://github.com/frappe/erpnext/assets/108865344/b058e42d-a2bf-4da6-b149-0deb22fbe16b)

**Comment by bosue** [comment]
May #36921 be possibly related? Like, is yours just a display issue?

**Comment by deepeshgarg007** [comment]
@sanjay141986 This should be available now, closing this issue.
