### ISSUE TITLE
Stock Reconciliation Error

### ISSUE THREAD

**Issue by Stores3** [frappe/erpnext#37012]
Serial number of item number 2 is 12 active and stock is 10 in erp and we need stock quantity 12 pcs.

If reconciliation is done inside a message is received from the system that we are sharing a screenshot for your reference.

Please guide.
![Reconciliation Error screen shot](https://github.com/frappe/erpnext/assets/144588917/807a3520-f38d-4a0a-adb5-cd8ae7c735d3)

Item Code-ST-BR-0017
MAT-RECO-2023-00081

**Comment by s-aga-r** [comment]
@Stores3 Please provide a screenshot of the Stock Reconciliation Item row.

**Comment by Stores3** [comment]
Dear Sir,

 Please see the below screen shot for your reference.

![Stock Reconciliation Error Date-14 09 2023](https://github.com/frappe/erpnext/assets/144588917/8fc1e461-fb18-4761-9706-8b6da2d2e2f1)

**Comment by Stores3** [comment]
one more screen shot

![Stock Reconciliation Error-2 Date-14 09 2023](https://github.com/frappe/erpnext/assets/144588917/e91d03d6-73e5-4af3-89df-c2bf8dbb738d)

**Comment by s-aga-r** [comment]
> @Stores3 Please provide a screenshot of the Stock Reconciliation Item row.

@Stores3 Please provide a screenshot of the Stock Reconciliation Items Row#2 Serial Nos field.

**Comment by Stores3** [comment]
Dear Sir,
Screen shot already send to you, send again for your reference.
![Stock Reconciliation Error-2 Date-14 09 2023](https://github.com/frappe/erpnext/assets/144588917/6bb02554-aa40-4320-9a21-a9a12ac73c85)

**Comment by Stores3** [comment]
Dear Sir,
Till Error Showing please help.

**Comment by s-aga-r** [comment]
@Stores3 I want to see the Serial Nos, which are not visible in your screenshots.

**Comment by Stores3** [comment]
Dear Sir,
We are mentioning below serial no. in row number-2.
ST-BR-0017-0025(02-23)
ST-BR-0017-0027(02-23)
ST-BR-0017-0036(03-23)
ST-BR-0017-0029(03-23)
ST-BR-0017-0031(03-23)
ST-BR-0017-0032(03-23)
ST-BR-0017-0028(02-23)
ST-BR-0017-0033(03-23)
ST-BR-0017-0034(03-23)
ST-BR-0017-0030(03-23)
ST-BR-0017-0035(03-23)
ST-BR-0017-0026(02-23)

**Comment by s-aga-r** [comment]
> Dear Sir, We are mentioning below serial no. in row number-2. ST-BR-0017-0025(02-23) ST-BR-0017-0027(02-23) ST-BR-0017-0036(03-23) ST-BR-0017-0029(03-23) ST-BR-0017-0031(03-23) ST-BR-0017-0032(03-23) ST-BR-0017-0028(02-23) ST-BR-0017-0033(03-23) ST-BR-0017-0034(03-23) ST-BR-0017-0030(03-23) ST-BR-0017-0035(03-23) ST-BR-0017-0026(02-23)

@Stores3 Can't help here, need to check the entry. Please raise a support ticket for the same [here](https://support.frappe.io/).
