### ISSUE TITLE
Display HSN code in separate lines if the Interstate and Intra state tax is applied

### ISSUE THREAD

**Issue by ram-chandu** [frappe/erpnext#37034]
Hi Team,

Facing the following issue in live instance:

Here HSN-wise-summary of outward supplies report, if the HSN code is same and IGST, SGST, CGST all are applied then it shows in the same line. The user is expecting to display HSN code in separate lines if the Interstate and Intra state tax is applied. Please check. 

Steps to replicate:
1. Go to the HSN-wise-summary of outward supplies report (https://v14-test-rcil.frappe.cloud/app/query-report/HSN-wise-summary%20of%20outward%20supplies?company=Rangsutra%20Crafts%20India%20Ltd&gst_hsn_code=63049289).
2. Filter the report by adding any HSN code(63049289).

Observation:
1.Here you can see that if the HSN code is same and IGST, SGST, CGST all are applied then it shows in the same line. 

Expectation:
1. Display HSN code in separate lines if the Interstate and Intra state tax is applied in the HSN-wise-summary of outward supplies report  

Attaching the Screenshots for reference.
![Screenshot from 2023-09-12 07-31-33](https://github.com/frappe/erpnext/assets/119317369/31d88f4d-a9ea-435a-8592-e8be80f6af9e)

Thanks,
Ram.

**Comment by deepeshgarg007** [comment]
Please raise this on the IC repo
