### ISSUE TITLE
How to display the bank charges recorded through Journal Entry in GSTR-3B

### ISSUE THREAD

**Issue by ram-chandu** [frappe/erpnext#37035]
Hi Team,

We have got a case in which the Bank regularly charges some amount from RS as bank charge, and on this RS pay GST and take input credit of the same. The transaction is recorded using Journal Entry to capture these types of expenses. We cannot use PI as the bank is not a supplier. Please refer transaction:https://v14-test-rcil.frappe.cloud/app/journal-entry/JV%2FFY23%2F0007

Observation: We are unable to see the transaction details at the GSTR-3B.
![Screenshot from 2023-09-12 08-10-24](https://github.com/frappe/erpnext/assets/119317369/36db22a6-27fd-4c2d-be3d-86cb06f00a2c)

Expectation: We would like to see the transaction in the GSTR-3B report

Please let us know in case if we are missing something. 

Thanks

**Comment by deepeshgarg007** [comment]
@ram-chandu this should be raised on the India compliance app repo, closing this from here.
