### ISSUE TITLE
Open Translation Tool Issue

### ISSUE THREAD

**Issue by m-aglan** [frappe/erpnext#37056]
### Information about bug

<img width="664" alt="Screenshot 2023-09-12 at 9 01 32 PM" src="https://github.com/frappe/erpnext/assets/76439836/077edde5-fefc-483c-ba46-cf599ee492bd">

### Module

accounts, stock, buying, selling, ecommerce, manufacturing, HR, projects, support, CRM, assets, integrations, quality, regional, portal, agriculture, education, non-profit

### Version

Frappe Framework [v14.48.1]
ERPNext [v14.38.0]

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
Open Translation tool results an error
```

**Comment by deepeshgarg007** [comment]
@m-aglan This is not being maintained anymore, you can directly raise a Pull Request to update translations, closing this issue.
