### ISSUE TITLE
Standard Report : Default Date is not working

### ISSUE THREAD

**Issue by thida-bcn** [frappe/erpnext#37054]
### Information about bug

Let's say
Account Receivable Report 
I had added column and save as AR San on 28/08/2023
Today 12/09/2023 when I open "AR San" default date was showning the date when I had save that report

### Module

accounts

### Version

![image](https://github.com/frappe/erpnext/assets/62122640/24f24627-a94b-4b14-86ae-a53fc74a3a4b)

### Installation method

manual install

**Comment by thida-bcn** [comment]
[report date issue.webm](https://github.com/frappe/erpnext/assets/62122640/0e08ca57-d1c0-433a-bad4-f1202a3dd327)

**Comment by deepeshgarg007** [comment]
@thida-bcn You must have also saved the date filter hence it is also showing you the old. Not sure if dynamic filters are supported yet, please remove the date filter and then save the report again and then it should work I guess

**Comment by thida-bcn** [comment]
> @thida-bcn You must have also saved the date filter hence it is also showing you the old. Not sure if dynamic filters are supported yet, please remove the date filter and then save the report again and then it should work I guess

that was working fine up to version v14.27.2 
issues with recent update only
