### ISSUE TITLE
Bug in Notes Module (Unable to share notes)

### ISSUE THREAD

**Issue by justinlusg** [frappe/erpnext#3705]
Users are unable to share notes, the moment notes are shared the system will not work well.

Steps to Replicate:
1) Sharing of notes between User A and User B
2) User A creates a note, set it to private
3) User A shares the note with User B
![image](https://cloud.githubusercontent.com/assets/12539216/8819065/318162d0-307b-11e5-8be5-c1f2b7114528.png)
4) User B access Notes module
5) User B is unable to see any notes, including previous private notes and public notes 
![image](https://cloud.githubusercontent.com/assets/12539216/8819082/5870e708-307b-11e5-90d3-b002d4350660.png)

**Comment by cgpurbaugh** [comment]
I am unable to replicate with my account.  Sharing notes is working fine for me.

**Comment by anandpdoshi** [comment]
This was fixed recently. Can you update and check?

**Comment by justinlusg** [comment]
Noted, will update and check
