### ISSUE TITLE
Charts of Accounts in Account Module

### ISSUE THREAD

**Issue by S-mkc** [frappe/erpnext#37062]
![Charts of account Issue](https://github.com/frappe/erpnext/assets/97079101/d8fba507-f7a9-4bd8-b337-57151ed137df)
### Information about bug

I can't see any entry/data while I am nevagiting to charts of account inside accounting modle but it is getting displayed when I am searching in seacrh bar. I have attached the screenshot for reference.

### Module

accounts

### Version

Frappe version - 5.16.2

### Installation method

FrappeCloud

**Comment by bosue** [comment]
Thanks for your report!

However, the screenshot is unfortunately missing. Would be nice if you could add it in a comment or by editing your original post!

**Comment by S-mkc** [comment]
> Thanks for your report!
> 
> However, the screenshot is unfortunately missing. Would be nice if you could add it in a comment or by editing your original post!

I have attached screenshot. plz look into it and help me with solution.Thank you

**Comment by ruthra-kumar** [comment]
Do you see any errors in browser console? Browser Console can be accessed by pressing F12.
