### ISSUE TITLE
Suggestion: To differentiate system messages from user messages  

### ISSUE THREAD

**Issue by justinlusg** [frappe/erpnext#3707]
![image](https://cloud.githubusercontent.com/assets/12539216/8820336/18fe27aa-3087-11e5-82ab-337800ed56f0.png)

A suggestion to have a clearer way to differentiate the system messages vs. the user messages. We have many real life scenarios where *user messages* got lost in the many *system messages* and end up the piece of information did not get to the designated user.

**Comment by rmehta** [comment]
Thanks pushed in v6
