### ISSUE TITLE
POS Invoice not fetching values from different doctype

### ISSUE THREAD

**Issue by arif-shamsudin** [frappe/erpnext#37083]
### Information about bug

Fetch in POS Invoice keep returning undefined on initial load in this case the company abbreviation. After reselecting the company, it fetch the right values

Bug proof:
![image](https://github.com/frappe/erpnext/assets/140783448/ab376f6b-b181-4f49-92d7-5426875b27d2)

My config in the custom field
![image](https://github.com/frappe/erpnext/assets/140783448/67f561a8-c709-410c-be34-8d8648941ef1)

### Module

accounts

### Version

Frappe Framework: v13.58.4 (version-13)
ERPNext: v13.52.9 (version-13)

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
**We no longer provide support for version 13 or older.**

Kindly upgrade to version 14 or 15. Everything is working fine. No problems were encountered in the latest versions 14 and 15.


https://github.com/frappe/erpnext/assets/141945075/a2fcdf94-6085-49d3-a78b-924a064be853



Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!
