### ISSUE TITLE
VAT 201 Report - VAT Emirate in sales invoice fetched from Company Address instead of Customer Address

### ISSUE THREAD

**Issue by Craftint** [frappe/erpnext#37093]
### Information about bug

VAT Emirate in sales invoice fetched from Company Address instead of Customer Address. Hence giving wrong data in VAT 201 report

![image](https://github.com/frappe/erpnext/assets/67686213/778f39e3-ec9f-4e3c-87d4-8660f263c427)

### Module

regional

### Version

Frappe version - version 14
Erpnext version - version 14

### Installation method

None

**Comment by deepeshgarg007** [comment]
@maveezmh KSA VAT from V15 onwards will be maintained at https://github.com/8848digital/KSA
Please raise your issues here, no updates planned to be done on v13 and v14

**Comment by maveezmh** [comment]
Hi @deepeshgarg007 this UAE VAT 201 report not KSA
