### ISSUE TITLE
Item Tax Template Duplication of the same name is allowed, merging option does not exist

### ISSUE THREAD

**Issue by SamiHajbi** [frappe/erpnext#37094]
### Information about bug

Item Tax Template Duplication of the same name is allowed, this will allow errors to exist, and thus will affect the tax report

and there is no way to fix it using system merging option does not exist , like merging  Duplication  customer Item Tax Template Duplication of the same name is allowed, this will allow errors to exist, and thus will affect the tax report

and there is no way to fix it using system merging option does not exist , like merging  Duplication  customer 
<img width="1212" alt="Erpnext error" src="https://github.com/frappe/erpnext/assets/93725977/8ffe02bf-c006-4d13-8444-637705618319">

That is why I suggest adding this feature and preventing the repetition of names in the system defaults

### Module

accounts

### Version

Frappe Framework: v14.26.3 (version-14)
ERPNext: v14.17.4 (version-14)

### Installation method

None

**Comment by GursheenK** [comment]
@SamiHajbi Creation of an Item Tax Template with a duplicate ID throws an error, that the Item Tax Template already exists. Please provide more details like the Naming Rule used for the Item Tax Template and steps to replicate this issue.
