### ISSUE TITLE
Item name shouldn‘t be generated from Item code

### ISSUE THREAD

**Issue by bosue** [frappe/erpnext#37091]
On Items (DocType Item), Item Code is required, so Item Name is automatically generated from Item Code.

But only if you enter the code fast enough, because it will only work once. Here I swiftly entered “TQ TX“ and added “A1“ only after a few seconds which was too late:

![IMG_1486](https://github.com/frappe/erpnext/assets/46800703/e74c6079-908a-4afe-95a7-15f9de7657af)

Nice idea, but it doesn‘t really work, neither does it make all too much sense. If anything, then the code should be generated from the name, but without proper templates, this wouldn‘t help either.

As much as autogeneration is a nice thing, if it works well, here I would simply remove the JS code and leave the Item name for manual entry. The Item name isn’t not required anyway.

**Comment by Nihantra-Patel** [comment]
Hi @bosue,

Please check my [Forum](https://discuss.frappe.io/t/item-name-same-as-item-code/95394/2?u=ncp
) post.

Please apply the client script for Item Doctype.
```js
frappe.ui.form.on('Item', {
	item_code: function(frm) {
	    frm.set_value("item_name", frm.doc.item_code);
	}
});
```

Then reload (Ctrl + Shift + R) and check it.

I hope this helps.
Thank You!

**Comment by bosue** [comment]
Thanks, but I hit this UI bug accidentally, don’t need a workaround, but think it should either be fixed or removed and left to a custom script.

**Comment by niraj2477** [comment]
IMO, It is better to add script suggested by @Nihantra-Patel into the core itself.
@bosue
