### ISSUE TITLE
VAT 201 Should be based on Customer Emirates not Company.

### ISSUE THREAD

**Issue by maveezmh** [frappe/erpnext#37101]
### Information about bug

VAT 201 report is calculating VAT by taking emirates field from company master. it should be based on customer Emirate. when you create a sales invoice the system should fetch vat emirate from customer billing Address. in some scenarios vat is also booked based on delivery Emirate. in this scenario the VAT 201 should calculate it from delivery address of customer. 

### Module

accounts, buying, selling

### Version

V13 V14

### Installation method

FrappeCloud

**Comment by deepeshgarg007** [comment]
@maveezmh KSA VAT from V15 onwards will be maintained at https://github.com/8848digital/KSA
Please raise your issues here, no updates planned to be done on v13 and v14
