### ISSUE TITLE
Wrong Balance Sheet assets calculation (v15)

### ISSUE THREAD

**Issue by SirPente** [frappe/erpnext#37107]
### Information about bug

I am testing ERP next as potential ERP for my company. I tried one transaction (just one invoice get 1000 Customer is still owed 1000). Total assets in the balance sheet gives -1000 while I would expect  0. Trial balance looks ok. Or did I get something wrong?

Thank you

<img width="951" alt="image" src="https://github.com/frappe/erpnext/assets/141501283/df7464a3-a584-4e3a-aa09-98d652de6aa3">
<img width="461" alt="image" src="https://github.com/frappe/erpnext/assets/141501283/0f9f9d70-301d-4e4a-b00b-cbe6149b9f61">
<img width="832" alt="image" src="https://github.com/frappe/erpnext/assets/141501283/a2e53469-f476-4f68-8ec5-4c13a0f46843">

### Module

accounts

### Version

ERPNext: v15.0.0-dev (HEAD)
Frappe Framework: v15.0.0-dev (HEAD)

### Installation method

FrappeCloud

**Comment by deepeshgarg007** [comment]
@SirPente Looks like you made an advance payment against some customer. The reports and entries are correct and used by many users, doesn't look like a bug, closing this issue.
