### ISSUE TITLE
Payment Receive from Shareholder 

### ISSUE THREAD

**Issue by mohamxx** [frappe/erpnext#37124]
### Information about bug

Trying to submit a payment of type receive from a shareholder with cash payment mode to cash account from creditors account causes an error.. Debit and Credit entries created are not equal. ERPNext puts both entries on one side instead of one entry in Debit and the other in Credit. 

### Module

accounts

### Version

14.49
14.39

### Installation method

manual install

**Comment by RitvikSardana** [comment]
Share Traceback?
