### ISSUE TITLE
No automatic update of Trial Balance with figures in fields

### ISSUE THREAD

**Issue by nissekalle0** [frappe/erpnext#37130]
### Information about bug

The UI does not update even though figures are in the fields. It is needed to retype then again to get the info listed in Trial Balance.

### Module

accounts

### Version

Latest versions

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
No error messages
```

**Comment by deepeshgarg007** [comment]
@nissekalle0 There is not enough information or context in the issue for anyone to look into this, closing this issue.
