### ISSUE TITLE
Maintenance Visit creation

### ISSUE THREAD

**Issue by bhavyajicomputers** [frappe/erpnext#37145]
### Information about bug

When create new maintenance visit having  more than one sales person in child table getting following error

![image](https://github.com/frappe/erpnext/assets/113116758/752f4bae-853f-43fb-9b65-d7f4e89f7a83)
 

### Module

support

### Version

Frappe Framework
  [v14.49.0]
ERPNext [v14.39.0]

### Installation method

FrappeCloud

**Comment by s-aga-r** [comment]
@bhavyajicomputers unable to replicate, make sure the selected/pasted Sales Person exists.
