### ISSUE TITLE
Margin in Sales Invoice Item cannot be set

### ISSUE THREAD

**Issue by hans-permana** [frappe/erpnext#37151]
### Information about bug

When creating a new Sales Invoice, upon setting up Margin Type inside Sales Invoice Item, the section is automatically collapsed and the value that has been set is gone. 

Steps to reproduce the issue:
- Create a new Sales Invoice
- Select a Customer
- Select an Item
- Click Edit to open the SI Item detail
- Click **Discount and Margin** section to open the collapsible
- On the field **Margin Type**, select **Percentage**
- When the Margin Type is selected, the collapsible unexpectedly shuts. When it is reopened, the values are gone

Also, this behavior is similar to the one in Purchase Invoice, albeit with slightly different behavior details.

I am trying to search where this bug is introduced in the code but found it difficult to pinpoint the location. Need a help from someone in this group.

Cheers,
Hans

### Module

accounts, selling

### Version

Frappe Version: v13.58.11
ERPNext Version: v13.52.15

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
N/A
```

**Comment by deepeshgarg007** [comment]
@hans-permana v13 is not supported anymore. Please check on the latest release and raise the issue again if applicable.
