### ISSUE TITLE
Supplier delivery note & delivery date should be there in the subcontracting receipt

### ISSUE THREAD

**Issue by ram-chandu** [frappe/erpnext#37162]
Hi Team,

Facing the following issue in V14 instance:

While creating a subcontracting receipt from the subcontracting order, In the subcontracting receipt, supplier delivery note and the delivery date fields are not present as they are present in the purchase receipt. Please check.

Steps to replicate:
1. Go to the Purchase order created from Production plan(https://v14-test-rcil.frappe.cloud/app/purchase-order/PO%2FFY23%2FBM0073).
2. Then click on create and create a subcontracting order(https://v14-test-rcil.frappe.cloud/app/subcontracting-order/SC-ORD-2023-00314).
3. Once the subcontracting order is created, create a subcontracting receipt(https://v14-test-rcil.frappe.cloud/app/subcontracting-receipt/SCR%2FFY23%2FBM0185).
4. Then create a Purchase Receipt(https://v14-test-rcil.frappe.cloud/app/purchase-receipt/PR%2FFY23%2FBM0417). 

Observation:
1. Here the created subcontract receipt doesn't have the Supplier delivery note and delivery date fields which are present in the Purchase receipt.

Expectation:
1. Supplier delivery note & delivery date should also be there in the subcontracting receipt.

Attaching the screenshots for your reference.

Purchase Receipt:
![Screenshot from 2023-09-20 07-19-14](https://github.com/frappe/erpnext/assets/119317369/ee4d353d-0511-4116-a372-04fc534eaa01)

Subcontracting receipt:
![Screenshot from 2023-09-20 07-18-44](https://github.com/frappe/erpnext/assets/119317369/0885a368-b03c-4c8c-815f-01af24fa825c)

Thanks.

**Comment by s-aga-r** [comment]
@ram-chandu The `Supplier Delivery Date` is a custom field added from your end in the Purchase Receipt DocType. We have added the `Supplier Delivery Note` field in the Subcontracting Receipt.
