### ISSUE TITLE
Serial no bugs

### ISSUE THREAD

**Issue by Wahyulutfi97** [frappe/erpnext#37168]
### Information about bug

when serial no delivered and make purchase recipt with serial no same seriol no will overwrite and status active again. in v13.

### Module

stock

### Version

13

### Installation method

None

**Comment by s-aga-r** [comment]
@Wahyulutfi97 This is expected behaviour, consider the case for Internal Transfer. Although we have added configuration for the same in v14.

ref: https://github.com/frappe/erpnext/pull/35534
