### ISSUE TITLE
Auto Material Request Generation UOM issue

### ISSUE THREAD

**Issue by dineshpanchal93** [frappe/erpnext#37164]
### Information about bug

Item - 24x24 Printing Polybag
Default Unit of Measure - Gram
Default Purchase Unit of Measure - Kgs

Below we have created Auto Re-Order Level.

<img width="504" alt="Screenshot 2023-09-20 at 10 48 25 AM" src="https://github.com/frappe/erpnext/assets/21578167/00961819-950b-4a4c-8ae3-e17b59522dd4">

A new Material Request is created with  Proper UOM but the wrong Quantity

<img width="1084" alt="Screenshot 2023-09-20 at 10 49 53 AM" src="https://github.com/frappe/erpnext/assets/21578167/e9e64049-f9a9-4243-9ad6-c86adbe29f8b">

**Now it's 0.150 it should be 150 Kg**

### Module

stock, buying

### Version

ERPNext: v14.38.0 (version-14)

Frappe Framework: v14.48.1 (version-14)

Frappe HR: v14.10.5 (version-14)

India Compliance: v14.16.2 (version-14)

### Installation method

manual install

**Comment by viralkansodiya** [comment]
Hey @dineshpanchal93  i am on Erpnext V14.39.0
please check my transaction

![Screenshot 2023-09-21 174021](https://github.com/frappe/erpnext/assets/141210323/c68d9a3b-65f6-4759-9542-63b20b48f4bb)

![Screenshot 2023-09-21 174321](https://github.com/frappe/erpnext/assets/141210323/bc10d34f-0c4c-406b-b432-704f728f75e8)


![Screenshot 2023-09-21 174334](https://github.com/frappe/erpnext/assets/141210323/0517840c-5b86-4ee3-9341-ac43c74364f8)

purchase 5 qty in kg = 5000 in gram
![Screenshot 2023-09-21 174403](https://github.com/frappe/erpnext/assets/141210323/d4fab77b-6aed-4d02-8b9f-f895de0cecac)

after purchase
![Screenshot 2023-09-21 174422](https://github.com/frappe/erpnext/assets/141210323/c3ed1c29-9d86-4ee6-aeb7-628afd218002)

after delivery remaining qty = 5 gram
![Screenshot 2023-09-21 174526](https://github.com/frappe/erpnext/assets/141210323/7b68e0c7-abf2-4cff-b983-9d8f77daf9c8)

![Screenshot 2023-09-21 175005](https://github.com/frappe/erpnext/assets/141210323/7bade975-bf3c-4f94-8cd9-fb601468c984)

Now execute a Auto reorder function

![Screenshot 2023-09-21 175108](https://github.com/frappe/erpnext/assets/141210323/a1133a6b-c5eb-4c52-8f3c-ef9cc8ad843b)


Item Purchase UOM Kg

in Latest version it is working correct
