### ISSUE TITLE
Enable entering amount in LCV

### ISSUE THREAD

**Issue by rasika2502** [frappe/erpnext#3717]
Presently in the Landed Cost Voucher (LCV), the amount of Customs Duty, freight etc is calculated by the system based on amount and distributed accordingly. However, this leads to incorrect distribution of customs duty amount as the customs duty % applicable for each item may be different. This will lead to incorrect valuation of the item.

So it will be really helpful, if entering amounts for individual items in the LCV is enabled. The system can distribute automatically, however it will be helpful if we can modify the amounts as per actual data.

**Comment by rmehta** [comment]
https://erpnext.com/pricing/paid-feature-development ? Estimate is 2 hours.
