### ISSUE TITLE
Account currency is not coming in excel format

### ISSUE THREAD

**Issue by viralkansodiya** [frappe/erpnext#37170]
### Information about bug

when we export char of account in excel by using Chart of Accounts Importer , Account currency is not print excel file 
is it logically right or wrong ?
Account currency in excel should be Selected Company Currency
if it is bug so tell me I will raise a PR

step 1
![Screenshot 2023-09-20 151741](https://github.com/frappe/erpnext/assets/141210323/41be5329-5a2b-4bd5-8733-fff0112dcbc3)

step 2
![Screenshot 2023-09-20 151757](https://github.com/frappe/erpnext/assets/141210323/a57972b3-c4e7-49a2-abcd-8b3c52c09570)

step 3
![Screenshot 2023-09-20 152116](https://github.com/frappe/erpnext/assets/141210323/3daac8fb-c629-487d-bc8c-2ddd51a35518)
   

### Module

accounts

### Version

Frappe version:- v14.49.0
Erpnext version:- v14.39.0

### Installation method

manual install

**Comment by shoaib0300** [comment]
@viralkansodiya 
when you export the Chart of Accounts to Excel using the "Chart of Accounts Importer," it should ideally include the account currency as the selected company currency for each account. If you find that the account currency is not included in the exported Excel file, it may indeed be a bug or an oversight in the export functionality.

That will help i know 
Review the default behavior and export settings of the "Chart of Accounts Importer" to see if the account currency should be included in the export by default.
