### ISSUE TITLE
translate.erpnext.com Certificate Date is invalid

### ISSUE THREAD

**Issue by cwerner1** [frappe/erpnext#37199]
### Information about bug

The Translation tool is not working.

The Certificate Date for https://translate.erpnext.com/ has expired.
open the URL with you web-browser, and see also the Error message from your browser.

### Module

accounts, stock, buying, selling, ecommerce, manufacturing, HR, projects, support, CRM, assets, integrations, quality, regional, portal, agriculture, education, non-profit, other

### Version

Frappe: yes
Erpnext: yes

Local installation is not relevant, because translate.erpnext.com is running on your side.

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
"requests.exceptions.SSLError: HTTPSConnectionPool(host='translate.erpnext.com', port=443): Max retries exceeded with url: /api/method/translator.api.get_strings_for_translation?language=de&start=0&page_length=100&search_text=&FrappeClient=%3Cclass+%27frappe.frappeclient.FrappeClient%27%3E&translator=%3Cfrappe.frappeclient.FrappeClient+object+at+0x7f1574c14d50%3E (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1002)')))"
```

**Comment by cwerner1** [comment]
This Issue is keeps reappearing. 
2022-10-02 and 2023-01-06 https://github.com/frappe/erpnext/issues/32665
2023-02-06 https://discuss.frappe.io/t/the-certificate-of-translate-erpnext-com-has-expired/100760
2018-02-24 https://github.com/frappe/erpnext/issues/13083

**Comment by marthoff** [comment]
+1

**Comment by aheart** [comment]
+1
I've also reported the problem here https://github.com/frappe/translator/issues/216
