### ISSUE TITLE
Stock miss match for items with batch after creating stock reconciliation before the date of last transaction.

### ISSUE THREAD

**Issue by Ponnusamy1-V** [frappe/erpnext#37192]
### Information about bug

I have created a new item with batch enabled.
Added 15000 qty via stock entry at datetime 2023-09-19 16:15:13
Created delivery note for 2000 stock at datetime 2023-09-21 16:19:29
Created stock reconciliation for (15000 to 13000) stock at datetime 2023-09-21 03:11:17

I expected the final balance qty should be 11000 but it is 9000
![image](https://github.com/frappe/erpnext/assets/95607086/89d9711b-89e3-4e38-a6db-1c8b8025b06b)

when i have multiple batches with high qty, the balance qty goes to negative values. And i cannot able to cancel the stock reconciliation.

### Module

stock

### Version

I have faced this issue in version13. So i tried in erpnext demo site.

Erpnext demo site version:
Frappe - v15.0.0-dev (HEAD)
Erpnext - v15.0.0-dev (HEAD)

### Installation method

None

**Comment by viralkansodiya** [comment]
@Ponnusamy1-V 
as per your Report Screen shot 9000 is correct , there is nothing wrong
in coming 15000 + 13000
outgoing -15000 - 2000

total = 9000

can you share your reconciliation document screen shot

**Comment by Ponnusamy1-V** [comment]
> @Ponnusamy1-V as per your Report Screen shot 9000 is correct , there is nothing wrong in coming 15000 + 13000 outgoing -15000 - 2000
> 
> total = 9000
> 
> can you share your reconciliation document screen shot

![image](https://github.com/frappe/erpnext/assets/95607086/aaf2da91-ced1-4d20-ab37-1a17a584e45a)

**Comment by Ponnusamy1-V** [comment]
@viralkansodiya 
how it will be 9000

in coming 15000 + 13000 = 28000
outgoing -15000 - 2000 = -17000

28000-17000 = 11000

**Comment by s-aga-r** [comment]
@Ponnusamy1-V Make sure the Batch is the same in all the transactions.

**Comment by Ponnusamy1-V** [comment]
> @Ponnusamy1-V Make sure the Batch is the same in all the transactions.

Yes i used same batch

**Comment by s-aga-r** [comment]
@Ponnusamy1-V check the Repost Item Valuation for the back-dated Stock Reconciliation.
