### ISSUE TITLE
Bug: [Report: Item Price] does not show the correct currency sign

### ISSUE THREAD

**Issue by chaoyee** [frappe/erpnext#3719]
If I have two price lists with currency A and B and the default currency is A.   [Report: Item Price] shows all prices (rates) with default currency sign (which is A), regardless of the prices with price list of currency B.
![2015-07-25 12 46 51](https://cloud.githubusercontent.com/assets/2167909/8879859/fa4e9d30-3266-11e5-94e4-3bacbc400a0a.png)

**Comment by rmehta** [comment]
You will have to select the current column too in the report to enable this. Can you check if this works with the currency column? Maybe there should be a way to auto-select.

**Comment by chaoyee** [comment]
No way, I tried to select different currency but it did not change.

**Comment by rmehta** [comment]
Unable to replicate in my system. Added a fix to include currency column by default.
