### ISSUE TITLE
BOM: Material list shows wrong currency sign in rate and amount field.

### ISSUE THREAD

**Issue by chaoyee** [frappe/erpnext#3720]
In item price, the price for this item has been set as "49.6" in currency USD.  
![2015-07-25 12 55 19](https://cloud.githubusercontent.com/assets/2167909/8880171/4135f516-3269-11e5-8b85-0e2fbdd659a8.png)

In BOM operation, however, "Material" list shows wrong currency sign (NT$)  but the same price (49.6) in rate and amount field.
![2015-07-25 12 54 20](https://cloud.githubusercontent.com/assets/2167909/8880105/c63e64a6-3268-11e5-8db5-aea0dedb03e4.png)

The currency exchange rate for TWD to USD has been set.  If "Material" list shows "NT$", the rate and amount should be converted through the exchange rate.  But it does not happen.

**Comment by rmehta** [comment]
Thanks @chaoyee this needs to be fixed.
