### ISSUE TITLE
Deferred Revenue and Expense Checkboxes are not visible

### ISSUE THREAD

**Issue by maveezmh** [frappe/erpnext#37203]
### Information about bug

WRT Update : https://github.com/frappe/erpnext/pull/37023

After updating ERP the deferred revenue and expense  checkboxes are not visible. the system is showing section as shown below

![image](https://github.com/frappe/erpnext/assets/112148467/1f591329-3bc8-42ce-a537-d8c82b9bd124)

Upon opening the section i dont see option to check the given fields

![Screenshot 2023-09-22 at 11-05-09 Office Rent - Office Rent](https://github.com/frappe/erpnext/assets/112148467/ac340f00-d25b-4ef5-9171-7a8710da2c05)

but in customize the fields are available

![image](https://github.com/frappe/erpnext/assets/112148467/e69c15e5-bbf7-4638-b722-822dfb132ecc)

Fields are scattered in Purchase and sales Tab

Sales Tab
![image](https://github.com/frappe/erpnext/assets/112148467/896f5229-bddf-4a48-a09d-176242a9ed35)

Purchase Tab
![image](https://github.com/frappe/erpnext/assets/112148467/776c1842-88bb-40f6-b6de-0f7cf41e218d)

### Module

accounts, stock

### Version

V14 Latest Update

### Installation method

FrappeCloud

**Comment by GursheenK** [comment]
We were unable to replicate this issue since both the checkboxes appear in the Deferred Accounting section. Please try updating your site using `bench --site <site-name> migrate` and let us know if the issue still persists.
