### ISSUE TITLE
 BOM Variance Report is not showing any data

### ISSUE THREAD

**Issue by maveezmh** [frappe/erpnext#37205]
### Information about bug

In BOM Variance Report am not able to select workorders related to selected BOM and unable to generate the report

<img width="998" alt="image" src="https://github.com/frappe/erpnext/assets/112148467/aa8eb52b-be8d-4ef4-a1a2-f61e19e6d37b">

### Module

stock, manufacturing

### Version

V13 and V14

### Installation method

FrappeCloud

**Comment by s-aga-r** [comment]
@maveezmh Make sure you have Work Orders for the selected BOM. The records will only come when WO Produced Qty is greater than WO Qty and WO Docstatus is 1 i.e., Submitted.

**Comment by maveezmh** [comment]
@s-aga-r there are multiple work orders against that BOM its not showing up any

**Comment by s-aga-r** [comment]
@maveezmh 

>> The records will only come when WO Produced Qty is greater than WO Qty and WO Docstatus is 1 i.e., Submitted.

Work Order [Qty To Manufacture = 1, Manufactured Qty = 1]
- ![image](https://github.com/frappe/erpnext/assets/63660334/cecee499-10c7-4590-bcf4-46df5ab2c672)
- ![image](https://github.com/frappe/erpnext/assets/63660334/3a579acf-ee43-4677-9e95-59daceca3d4c)

Work Order [Qty To Manufacture = 1, Manufactured Qty = 2]
- ![image](https://github.com/frappe/erpnext/assets/63660334/29cfd63c-f1ae-4346-b437-acc8973eee83)
- ![image](https://github.com/frappe/erpnext/assets/63660334/d325f613-7768-4a14-b0d7-a3204b856646)

**Comment by maveezmh** [comment]
@s-aga-r  am still not able to see the report

**Comment by s-aga-r** [comment]
@maveezmh Please share any one of your Work Orders that you are expecting to be shown in the report.
