### ISSUE TITLE
Error when creating delivery note when stock is reserved

### ISSUE THREAD

**Issue by AnnaPrilk** [frappe/erpnext#37208]
### Information about bug

After creating a sales order, reserving the stock. When i click on the action button and make a delivery note this error pops up in the picture

### Module

selling

### Version

![image](https://github.com/frappe/erpnext/assets/145773013/5903bd0c-4510-40b2-90cf-101f5246308d)

### Installation method

None

**Comment by s-aga-r** [comment]
@AnnaPrilk seems like a permission issue. Please share the browser console log.

**Comment by pritambiswal** [comment]
<img width="1381" alt="image" src="https://github.com/frappe/erpnext/assets/19719012/2b81cf44-08a3-4640-ac26-01b624544e25">
when stock is unreserved and action button is clicked to create delivery note, it works..

**Comment by s-aga-r** [comment]
Fixed: https://github.com/frappe/erpnext/pull/37758
