### ISSUE TITLE
Strange behavior for Sales Team commissions 

### ISSUE THREAD

**Issue by MaxMorais** [frappe/erpnext#3721]
I'm trying to define commissions in the Sales Order, and I have the below rules

 - 1.5% for the Sales Manager
 - 3% for the Sales User

![fireshot capture 12 - reliance trends-p_ - https___demo erpnext com_desk form_sales 20order_so-00249](https://cloud.githubusercontent.com/assets/1288676/8892734/0182f8fa-3341-11e5-8e98-881caada026f.png)

But while I'm saving the Sales Order, I receive the message
![fireshot capture 13 - reliance trends-p_ - https___demo erpnext com_desk form_sales 20order_so-00249](https://cloud.githubusercontent.com/assets/1288676/8892760/596929da-3342-11e5-92a8-17c285143d04.png)

Tracing it in the code I found this line [SellingController.py#L146](https://github.com/frappe/erpnext/blob/2b7eda813594a93a57078058a123addf6aed17f3/erpnext/controllers/selling_controller.py#L146)

![fireshot capture 14 - erpnext_sellin__ - https___github com_frappe_erpnext_](https://cloud.githubusercontent.com/assets/1288676/8892747/95f4f9d4-3341-11e5-9d4b-72e753264abc.png)

In my understanding of this rule, the `allocated_percentage` should be 100%, but the calculation of the `commission` is `net_amount x allocated_percentage` and, if the total allocated in commissions should be 100%, then the total value of the `Sales Order` will be paid as commission. Is right it? and if it is Okay, why?

**Comment by nabinhait** [comment]
System do not calculate commission/incentives automatically, it is just "contribution to net total". You have to enter Incentive manually. We do not calculate commission because most of the cases it is defined by some complicated rules, not simply based on percentage.

**Comment by MaxMorais** [comment]
@nabinhait But is the calculation that the system is doing, do you can check i in the L146

**Comment by nabinhait** [comment]
The system is designed to keep track of contribution of the sales persons involved in an Order. Suppose there are 2 sales person involved to close a deal/order, so you will enter there what is percentage of the contribution to close that deal/order. The total percentage must be same as 100. And based on that we also calculate contributed amount to the net total. In this way, you will know how much value of Order, one sales person has been contributed in a month/period. And based on that amount, may be company will give commission to the sales persons.
