### ISSUE TITLE
Error: Value missing for Module Onboarding: Documentation URL

### ISSUE THREAD

**Issue by sivabhogela88** [frappe/erpnext#37225]
### Information about bug

Error: Value missing for Module Onboarding: Documentation URL

### Module

accounts

### Version

Frappe-14
ERPNEXT-14

### Installation method

docker

### Relevant log output / Stack trace / Full Error Message.

```shell
Error: Value missing for Module Onboarding: Documentation URL
```

**Comment by Nihantra-Patel** [comment]
There is no further information in this issue so we close it.
