### ISSUE TITLE
Rename of fields in doctypes

### ISSUE THREAD

**Issue by KrithiRamani** [frappe/erpnext#3723]
Whenever a field is renamed in a doctype, it creates a new column in the table with the new field name instead of renaming the column in the table. Because of this, the existing records in the old column are lost and new column has only null values.

**Comment by cgpurbaugh** [comment]
I believe the recommended way to change the name would be to customize the form, and leave the doctype alone.

**Comment by anandpdoshi** [comment]
How did you rename the field?

**Comment by KrithiRamani** [comment]
renamed from the doctype!

**Comment by anandpdoshi** [comment]
You will have to write a patch to do the data migration when doing it like
that. Automating it can lead to all sorts of trouble if it goes wrong.

**Comment by rmehta** [comment]
It should not be automated because there may be code dependent on it.
