### ISSUE TITLE
doc is not defined

### ISSUE THREAD

**Issue by ankush** [frappe/erpnext#37231]
https://github.com/frappe/erpnext/blob/ee178ff2ce4fa2021dc846dfaa363aff42fa17bf/erpnext/public/js/controllers/accounts.js#L119

sentry FRAPPEIO-17F

**Comment by ghost** [comment]
you can try" if(doc.docstatus == 2) "{

**Comment by niraj2477** [comment]
It should be `d.docstatus` instead of `doc.status`

**Comment by iamrishiksahu** [comment]
I want to work on this issue, kindly assign this to me. I have understood the problem, the issue can be resolved by simply replacing the line #119 with `if (doc.docstatus == 1){`.

Kindly assign to me.
