### ISSUE TITLE
Feature Request: Expand all levels option in Tree Views

### ISSUE THREAD

**Issue by citizen-khan** [frappe/erpnext#3724]
It would be very handy to be able to click a button to:

a) expand all levels throughout the whole tree view
b) expand all levels with an particular parent of a tree view

When you are working on a tree view building your structure I can be reloading the view many times and each time it collapses everything. I want to be quickly able to expand all levels or just the section I was working on.

**Comment by cgpurbaugh** [comment]
:+1:  would be very useful

**Comment by rmehta** [comment]
Not as simple as it looks as we will have to query the full table first.

**Comment by gemlog** [comment]
Surely we've already queried the full table to populate the view?* I downloaded the vm image at the weekend and that was actually the first question I had -- "How to expand all in the accounts tree?" Very tedious without such a button.
* tbh, I haven't browsed the db yet or read much of the dev docs yet. just been experimenting, but I know this would frustrate users.

**Comment by mhbu50** [comment]
+1
