### ISSUE TITLE
Pick List items not filled with qty

### ISSUE THREAD

**Issue by infinityprogrammer** [frappe/erpnext#37244]
### Information about bug

I have a sales order with a quantity of 1 carton. The stock unit of measure is 24, and I have 2 batches: batch 1 has 7 items, and batch 2 has 1000 items. When I create a pick list from the sales order, the pick list items are empty. When I checked the code, I found that a break statement in a while loop was the reason. I changed the break statement to a continue statement, and the pick list items are now generated properly.

path : https://github.com/frappe/erpnext/tree/develop/erpnext/stock/doctype/pick_list/pick_list.py
function : get_items_with_location_and_quantity

uom_must_be_whole_number = frappe.db.get_value("UOM", item_doc.uom, "must_be_whole_number")
if uom_must_be_whole_number:
	qty = floor(qty)
	stock_qty = qty * item_doc.conversion_factor
	if not stock_qty:
		break

### Module

stock, selling

### Version

frappe 13
ERPNext 13, 14

### Installation method

manual install

**Comment by niraj2477** [comment]
You can raise the PR for it.

**Comment by s-aga-r** [comment]
@infinityprogrammer seems like the Conversion Factor is 0 in the Sales Order.

**Comment by infinityprogrammer** [comment]
@s-aga-r if the there is no issue with  Conversion Factor , if the qty not enough, system should select next batch, but here, the loop is being break and return empty dict

**Comment by s-aga-r** [comment]
@infinityprogrammer I tried to replicate the issue, here are the results:

- Stock Entry (Material Receipt) to inward the stock for Item NEW ITEM in two batches (7, 1000).

  ![image](https://github.com/frappe/erpnext/assets/63660334/af5d313a-0f2e-4c84-880d-72ce32157406)

- Sales Order for 1 Carton (Stock Qty = 24):

  ![image](https://github.com/frappe/erpnext/assets/63660334/fd489c1c-aed2-45ee-adc7-ae660414a612)

  ![image](https://github.com/frappe/erpnext/assets/63660334/58dcbffc-b0dc-4b90-ac59-5e8216ff860d)

- Sales Order > Pick List:

  https://github.com/frappe/erpnext/assets/63660334/b524d170-7d28-4c9e-974e-e7a9a70bafa7

The Batch gets picked based on FIFO. Let me know in case I missed something.
