### ISSUE TITLE
2nd Picklist for work Order

### ISSUE THREAD

**Issue by dineshpanchal93** [frappe/erpnext#37256]
### Information about bug

Item  001-SMT --> BOM
          001-RM-SMT
          002-RM-SMT

Item 001-MI ---->BOM
          001-RM-SMT
          001-RM-MI
          002-RM-MI

Two Work Order created from Store -  Pick list  for 001-MI ---->BOM  
Store transfer the Material against - Work Order-   
001-RM-MI
002-RM-MI

Issue in Picklist WOrk Order not visible when we transfer the Material against  001-MI ---->BOM   after store 
001-RM-SMT. - 

### Module

stock, manufacturing

### Version

ERPNext: v14.38.0 (version-14)

Frappe Framework: v14.48.1 (version-14)

Frappe HR: v14.10.5 (version-14)

India Compliance: v14.16.2 (version-14)

### Installation method

manual install

**Comment by dineshpanchal93** [comment]
Any update ?

**Comment by rohitwaghchaure** [comment]
Created a pick list against the work order which has work order information 
<img width="1179" alt="Screenshot 2024-06-04 at 11 51 21 AM" src="https://github.com/frappe/erpnext/assets/8780500/5c9d581a-8b74-4b1c-8c78-aa4b8567bc43">

Created a material transfer against the pick list which has work order information 
<img width="1318" alt="Screenshot 2024-06-04 at 11 51 35 AM" src="https://github.com/frappe/erpnext/assets/8780500/deeb39f9-2663-4464-b929-b5bc931cd7b5">


So everything is working fine in version 15, if you're facing the issue in v14 please either update the latest v14 version and check or migrate your site to version 15
