### ISSUE TITLE
Incorrect Total Stock Value for a user in  multi company setup

### ISSUE THREAD

**Issue by idmlabhishek** [frappe/erpnext#37257]
### Information about bug

Hi, 
In a multi company setup, I need an employee to have a look at only company specific stock informaiton. 
On the Stock Dashboard, Total Warehouses card shows the right value since there isa company filter available. At the same time Total Stock Value shows the value of stock across all the companies, since it is a number card on the bin. The bin has no Company field and hence the number doesn't come correctly. 
Is there a way to get this fixed ? 

### Module

stock

### Version

ERPNext: v14.40.0 (HEAD)
Frappe Framework: v14.50.0 (HEAD)

### Installation method

FrappeCloud

**Comment by Nihantra-Patel** [comment]
Modify the query report and set it accordingly.

https://github.com/frappe/erpnext/assets/141945075/9857f115-e7c1-421f-95f8-f8415a381dc9


Query:

```sql
SELECT 
    a.item_code AS "Item:Link/Item:120",
    a.item_name AS "Item Name::150",
    a.item_group AS "Item Group:Link/Item Group:120",
    a.description AS "Description::150",
    b.warehouse AS "Warehouse:Link/Warehouse:120",
    b.actual_qty AS "Balance Qty:Float:140",
    b.stock_value AS "Stock Value:Currency:140",
    w.company AS "Company:Link/Company:120"

FROM 
    `tabItem` a
LEFT JOIN `tabBin` b ON a.item_code = b.item_code
LEFT JOIN `tabWarehouse` w ON b.warehouse = w.name

WHERE
    w.company = %(company)s
```
