### ISSUE TITLE
serial_no.py needs to be refactored for Serial and Batch Bundles

### ISSUE THREAD

**Issue by batonac** [frappe/erpnext#37259]
### Information about bug

The `fetch_serial_numbers` and `get_delivery_note_serial_no` functions in `erpnext/stock/doctype/serial_no/serial_no.py` reference fields which have been removed in #34564. Specifically `sales_invoice` and `delivery_document_no`.

The functions in question will need to be transitioned to the new "Serial and Batch Bundle" equivalents.

### Module

stock

### Version

Frappe version - develop/version-15-beta
ERPNext version - develop/version-15-beta

### Installation method

manual install

**Comment by batonac** [comment]
@rohitwaghchaure you probably want to take a look at this, as relates to your PR.

**Comment by rohitwaghchaure** [comment]
Added the View Ledgers button in serial no for to see the transaction history of the respective serial no.

1) View Ledgers button in Serial No

<img width="1323" alt="Screenshot 2024-01-09 at 3 34 20 PM" src="https://github.com/frappe/erpnext/assets/8780500/e27408fb-1bd0-4652-832b-e1e5883e8330">

2) Serial No Ledgers report

<img width="1309" alt="Screenshot 2024-01-09 at 3 34 29 PM" src="https://github.com/frappe/erpnext/assets/8780500/d7eef3ad-3fb1-4070-ae9e-e1b9d0e3366e">

**Comment by batonac** [comment]
@rohitwaghchaure I'm obviously misunderstanding something. Why does the `fetch_serial_numbers` function in `serial_no.py` still reference the `serial_no.sales_invoice` and `serial_no.delivery_document_no` fields, which no longer exist on the "Serial No" doctype?
