### ISSUE TITLE
Process Statement Account Error Date are mandatory

### ISSUE THREAD

**Issue by edwardleehl7097** [frappe/erpnext#37260]
### Information about bug

Create new Process Statement of Account, filled up all details and click send email or download, it pop up error "From Date and To Date are mandatory" but the date field already filled.

<img width="2244" alt="image" src="https://github.com/frappe/erpnext/assets/25194385/b72d9ad4-f146-41b5-ba24-a1492eb296ff">

### Module

accounts

### Version

ERPNext: v14.40.0 (version-14)

Frappe Framework: v14.50.0 (version-14)

Frappe HR: v14.11.0 (version-14)

Payments: v0.0.1 (develop)

### Installation method

easy-install

### Relevant log output / Stack trace / Full Error Message.

```shell
From Date and To Date are mandatory
```

**Comment by GursheenK** [comment]
Fixed via https://github.com/frappe/erpnext/pull/37213
