### ISSUE TITLE
Unable to check the box "Is Return" on a Purchase Receipt

### ISSUE THREAD

**Issue by NobleDruid** [frappe/erpnext#37279]
### Information about bug
Recreate:
1. Create a purchase receipt
2. Try to select the checkbox "Is Return"

The checkbox is greyed out.

NOTE: Willing to help how I can, but not clear how to start help with logs, stack trace, etc. Also willing to help with code, but again unclear where to start. Would greatly appreciate anyone able to provide prompt assistance either to resolving the issue, or helping me know where to start to help resolve the issue myself.

### Module

buying

### Version

ERPNext: v14.41.1 (version-14)
Frappe Framework: v14.51.0 (version-14)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
None yet.
```

**Comment by bosue** [comment]
@OpenSourceJedi: It _is_ possible to create a return from the original Purchase Receipt:

https://github.com/frappe/erpnext/assets/46800703/db3fbaa2-ba60-4dcd-99c5-f78aef1f307a

Question is whether it should be possible to start with „New Purchase Receipt“, check „Is Return“ and select an original receipt to be returned.

There may be a case to add this as a second option, but in any case it would be a feature request or UX enhancement, not a bug.
