### ISSUE TITLE
Feature Request: Improved UOM functionality

### ISSUE THREAD

**Issue by cgpurbaugh** [frappe/erpnext#3729]
currently, UOMs cannot be modified in sales and purchase orders.  instead of being fixed, it should be a drop down list of all UOMs set in the item master.   I think this should be an option.  If you require paid development, please give us a quote.  Thanks!

**Comment by nabinhait** [comment]
I did not understood your query properly.

Currently Sales Order can only be made in default stock UOM, there is no options to select different UOM.

And in Purchase Order, you can select different UOM in Purchase Order, and on selection it fetches conversion rate from item master, if defined there. But it shows all available UOMs in the system, instead of showing only those UOMs which are defined in item master.

Can you please elaborate your query?

**Comment by cgpurbaugh** [comment]
Sorry, looks like they can be modified in Purchase orders, as you said.  Basically I think it would be good to have the option to change UOM in all forms like you can in Purchase Order.

**Comment by cgpurbaugh** [comment]
These Issues are saying similar things, I think this should be investigated: 

#1047
#2544
#1776
#1882
#3441

**Comment by rmehta** [comment]
@cgpurbaugh yeah! Making UOM conversion consistent in all transactions is on the priority list!

**Comment by cgpurbaugh** [comment]
Awesome, thank you!

**Comment by cgpurbaugh** [comment]
@rmehta @nabinhait  I looked into UOMs a bit more today, and when picking a non-default UOM in the Purchase order, it does indeed pull the conversion rate, but does not update the price.

Example:
If we were to order loctite, which is sold by the case, we would select the UOM for case.  but the default UOM is by bottle. 

So, the price of Loctite by bottle is $50. If we select 1 case in the purchase order, then the price should be $200.  But the price never updates, and shows $50.

**Comment by Cattmy** [comment]
Has there been any progress on this?  I had sales UOM developed for my deployment of ERPNext but am very frustrated with it and unable to update to V7. An official ERPNext solution would be sweet!

**Comment by rmehta** [comment]
>  I had sales UOM developed for my deployment of ERPNext but am very frustrated with it and unable to update to V7

That is why you should always get your development contributed - so it becomes a part of the product!

**Comment by Cattmy** [comment]
Is it helpful if I send you the modified core files I have? I'd love to get this in the product!

**Comment by rmehta** [comment]
@Cattmy send a pull request

https://help.github.com/articles/using-pull-requests/

**Comment by wsxedcr** [comment]
Is there any update to this problem?

**Comment by justmilk** [comment]
Hi,

Any update of this? it will be good that have mutli UOM in single SKU under Sales modules section

**Comment by hwinkel** [comment]
Why this is closed if the feature not exists?

**Comment by rmehta** [comment]
@hwinkel  Can you start a new thread with the specific issue you are facing. This thread has too many discussions
