### ISSUE TITLE
error in get_list

### ISSUE THREAD

**Issue by bakhtari** [frappe/erpnext#37303]
### Information about bug

Code:
today = str(date.today())
md_today=today[5:]
filters={‘date_of_birth’:[“like”, “%”+md_today]}
employees=frappe.get_list(‘Employee’,filters=filters)

### Module

other

### Version

erpnext 14.33.2
frappe 14.43.1

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
File “/home/erp/b1/apps/frappe/frappe/utils/data.py”, line 98, in getdate
return parser.parse(string_date, dayfirst=parse_day_first).date()
File “/home/erp/b1/env/lib/python3.10/site-packages/dateutil/parser/_parser.py”, line 1368, in parse
return DEFAULTPARSER.parse(timestr, **kwargs)
File “/home/erp/b1/env/lib/python3.10/site-packages/dateutil/parser/_parser.py”, line 643, in parse
raise ParserError(“Unknown string format: %s”, timestr)
dateutil.parser._parser.ParserError: Unknown string format: %09-29
```

**Comment by bakhtari** [comment]
this filed type is date and like not supported!

**Comment by cogk** [comment]
### Cleaner way

```py
Emp = frappe.qb.DocType("Employee")
query = frappe.qb.select(Emp.name).from_(Emp).where(Emp.date_of_birth.like("%" + md_today))
employees = query.run(as_dict=True)
```

---

### Original answer
Hello, maybe this query could be done differently using more advanced features like frappe.qb or something else, but still I found a way to bypass this issue:

```py
frappe.get_list("Employee", filters=[["ifnull(date_of_birth)", "like", "%" + md_today]])
#                                      ^~~~~~~             ~ wrapped in a ifnull(…)
```

The ifnull is there to bypass the check done in sanitize_column.
