### ISSUE TITLE
Offer Letter cannot be rejected

### ISSUE THREAD

**Issue by justinlusg** [frappe/erpnext#3732]
![image](https://cloud.githubusercontent.com/assets/12539216/8925506/dc77fe60-353a-11e5-8ab3-dd41723dd2fe.png)

There will be an error whenever you try to update the error letter to Rejected

**Comment by anandpdoshi** [comment]
Pushed a fix. If you are on erpnext's develop branch, you will get the
update immediately, else you will get it with the next release i.e. in
about 2-3 hours.
