### ISSUE TITLE
For v12, Offline POS, i want to add functionality to add multiple serial number for one item user can read and update after added in the cart section.

### ISSUE THREAD

**Issue by bhaveshmtpl** [frappe/erpnext#37331]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bhaveshmtpl** [comment]
![image](https://github.com/frappe/erpnext/assets/144006777/c5e3c88b-9cb7-466f-a9a3-4c10a000b1e3)

**Comment by deepeshgarg007** [comment]
@bhaveshmtpl v12 is not supported anymore. Closing this issue
