### ISSUE TITLE
Unable to find exchange rate

### ISSUE THREAD

**Issue by AnaG9696** [frappe/erpnext#37333]
### Information about bug

Hello, we are using the ERPNext  about 10 months already and it's first time this happens, we activated new currency, deactivated it again but didn't solve the problem, when we try to create new invoice in different currencies, it's unavailable, because when we try to save it comes the notification "Unable to find exchange rate for XXX to EUR for key date "2023-00-00". Please create a Currency Exchange record manually", it doesn't matter the currency or date, this notification is written in any case, we need help with that

### Module

buying, selling

### Version

Frappe Version - v13.58.12 (HEAD)
ERPNext Version - v13.53.0 (HEAD)

### Installation method

FrappeCloud

**Comment by kalungia** [comment]
Hello, 
Make sure that the exchange rate gateway under Exchange Settings has proper credentials. If not go to currency  exchange rate doctype then create a record for the date of the invoice you are creating if the invoice date is 3/04/2023 then create a record under currency  exchange rate doctype with the same date for that Currency

**Comment by Craftint** [comment]
In version 13, there is no settings for exchange rate. Kindly update the url to api_url = "https://api.exchangerate.host/convert" as before instead of frankfurt

**Comment by ruthra-kumar** [comment]
@AnaG9696 api.exchangerate.host will require API access key going forward. So, we changed it to api.frankfurter.app. You can update to [v13.54.1](https://github.com/frappe/erpnext/releases/tag/v13.54.1) to get the fix.

On upcoming minor version, user's will have the ability to choose the provider. Ref: https://github.com/frappe/erpnext/pull/37385

**Comment by ruthra-kumar** [comment]
[v13.54.2](https://github.com/frappe/erpnext/releases/tag/v13.54.2) now has selectable Exchange Rate providers
<img width="1440" alt="Screenshot 2023-10-07 at 7 54 15 PM" src="https://github.com/frappe/erpnext/assets/3272205/cc2db994-e3c8-4348-9a56-89abf9669ca8">

**Comment by AnaG9696** [comment]
Thank you for your help, as I see we have this version v13.53.0, so without update I can't fix this problem? It's not available on this version?
