### ISSUE TITLE
 Sales Pipeline Analytics is not showing any Data

### ISSUE THREAD

**Issue by maveezmh** [frappe/erpnext#37336]
### Information about bug

There are 100s of opportunities created in ERP but the sales pipeline analytics report is not showing any of the give data.

its totally blank

![image](https://github.com/frappe/erpnext/assets/112148467/7cc7225a-94dd-4510-bc3d-fba2ee40661d)

### Module

CRM

### Version

V14

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.
Error in parsing value for ‘stroke’.  Declaration dropped. 71 [Sales Pipeline Analytics](https://craft-trading.frappe.cloud/app/query-report/Sales%20Pipeline%20Analytics?pipeline_by=Owner&from_date=2023-01-01&to_date=2023-10-03&range=Monthly&status=Open&based_on=Number&company=Craft%20Interactive)
Error in parsing value for ‘stroke’.  Declaration dropped. 8 [Sales Pipeline Analytics](https://craft-trading.frappe.cloud/app/query-report/Sales%20Pipeline%20Analytics?pipeline_by=Owner&from_date=2023-01-01&to_date=2023-10-03&range=Monthly&status=Open&based_on=Number&company=Craft%20Interactive)
Error in parsing value for ‘stroke’.  Declaration dropped. 54 [Sales Pipeline Analytics](https://craft-trading.frappe.cloud/app/query-report/Sales%20Pipeline%20Analytics?pipeline_by=Sales%20Stage&from_date=2023-01-01&to_date=2023-10-03&range=Monthly&status=Open&based_on=Number&company=Craft%20Interactive)
Error in parsing value for ‘top’.  Declaration dropped. 2 [Sales Pipeline Analytics](https://craft-trading.frappe.cloud/app/query-report/Sales%20Pipeline%20Analytics?pipeline_by=Sales%20Stage&from_date=2023-01-01&to_date=2023-10-03&range=Monthly&status=Open&based_on=Number&company=Craft%20Interactive)
Error in parsing value for ‘stroke’.  Declaration dropped. 18 [Sales Pipeline Analytics](https://craft-trading.frappe.cloud/app/query-report/Sales%20Pipeline%20Analytics?pipeline_by=Sales%20Stage&from_date=2023-01-01&to_date=2023-10-03&range=Monthly&status=Open&based_on=Number&company=Craft%20Interactive)

​
_No response_

**Comment by Nihantra-Patel** [comment]
Kindly upgrade to version 14 or 15, then refresh and check again because lots of bugs fixed in the new version.

Everything is working fine. No problems were encountered in the latest versions 14 and 15.

![image](https://github.com/frappe/erpnext/assets/141945075/b749e956-ebcf-4a48-9fbd-b1dfe2628c44)


![image](https://github.com/frappe/erpnext/assets/141945075/ecc143b0-d7ac-4042-89c0-f73e0a6d92d0)
