### ISSUE TITLE
Bug: Stock Item UOM revert after pressing save.

### ISSUE THREAD

**Issue by adithep** [frappe/erpnext#3734]
I just updated from Erpnext 4 to 5 and found this strange behavior.

Lets say there is Item001 with UOM: Unit:1, Box:12

I enter in stock (Material receipt): Qty: 5, UOM: Box.... "Qty as per Stock UOM" at the bottom will show "60" 

Then I press save and  "Qty as per Stock UOM" at the bottom will show "5", Conversion Factor shows as "1"

Before saving conversion factor will show as "12" correctly, but after pressing save it always reverts to "1"

All the rate and everything is incorrect after pressing save...even after submit.

**Comment by rmehta** [comment]
Can you show screenshots? With the UOM Conversion table in your Item?

**Comment by adithep** [comment]
Item UOM:
![item_uom](https://cloud.githubusercontent.com/assets/6279977/9000462/aeda1a86-3771-11e5-881b-6eae4e7e4ca9.png)

Before Pressing Save: 
![before_pressing_save](https://cloud.githubusercontent.com/assets/6279977/9000461/aed8f8f4-3771-11e5-9454-65aeda44f8df.png)

After Pressing Save:
![after_pressing_save](https://cloud.githubusercontent.com/assets/6279977/9000459/aea9d182-3771-11e5-914f-f78537ee5c68.png)

**Comment by umairsy** [comment]
Replicating in Purchase Receipt.

**Comment by rmehta** [comment]
@adithep thanks for the screenshots and reporting. Fixed.

**Comment by adithep** [comment]
Wow. Really fast. Thankyou.
