### ISSUE TITLE
Invoice cannot be submitted

### ISSUE THREAD

**Issue by Joey-Aillio** [frappe/erpnext#37356]
### Information about bug

I ran into this issue trying to submit and invoice that i previously did not see 

![invoice error](https://github.com/frappe/erpnext/assets/146909915/1d1dc619-727a-48a8-897b-eed3503d70c8)

### Module

buying

### Version

Aillio: v1.1.5 (HEAD)

ERPNext: v13.52.12 (HEAD)

Frappe Framework: v13.58.7 (HEAD)

### Installation method

None

**Comment by deepeshgarg007** [comment]
@Joey-Aillio This is a validation and not a bug. P&L accounts cannot be used for opening entries.
