### ISSUE TITLE
Timer still breaks when adding record to empty timesheet time sheets table

### ISSUE THREAD

**Issue by muslimfaisal** [frappe/erpnext#37368]
### Information about bug

Like the issues reported and fixed by @tundebabzy (https://github.com/frappe/erpnext/issues/35011#issue-1680787428) I still have the same issue now on the latest version. Not sure why.

![image](https://github.com/frappe/erpnext/assets/50970263/fb0b7467-443c-4d48-999b-dceda6dd85c1)

### Module

projects

### Version

Frappe Framework: v14.51.0
ERPNext: v14.43.0

### Installation method

None

**Comment by Nihantra-Patel** [comment]
Kindly upgrade to version 14 or 15, then refresh and check again because lots of bugs fixed in the new version.

Everything is working fine. No problems were encountered in the latest versions 14 and 15.


https://github.com/frappe/erpnext/assets/141945075/d7b8351a-7990-4b3c-bf4d-2885ffed7df8
