### ISSUE TITLE
Sales Order and Purchase Order Status

### ISSUE THREAD

**Issue by Puntoitalia** [frappe/erpnext#3736]
Since our system has been upgrading, we are facing difficulties in keeping track with our documents status. Not that it takes time to adapt with the new design because we are familiar with the old one but it’s actually difficult to keep track. For example:

- Purchase order: Now the status of receiving products and billing is merged into one. But there will be a case that we receive the sales invoice before receiving 100% product quantity or there will be a case that the product might be missing and we don’t receive it enough. How can we keep track and take an easy look to control things and get information easily on the status of documents?

- Sales Order: Our working flow is: Sales Order  Sales Invoice  Delivery note. However, what we are facing is after finishing the Sales Order, the status of that Sales Order is Not Delivered. You said it’s because of the default set up on general work flow, but this is actually make us difficult in control our things. How do we know if that Sales Order is billed or not to take further action since it’s showing Not Delivered. After seeing that status, our staff will immediate create Delivery Note, which is wrong! Can you please help to find a way for us?

**Comment by rmehta** [comment]
Fixed. Will be updated with the next release.

**Comment by justmejust** [comment]
Hi @Puntoitalia Does your problem solved ?
i nearly facing the same but i need to daily tracking of Purchase Orders 
could you please confirm
