### ISSUE TITLE
File sharing with customer

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#3737]
Requirement:

An accounting firm needs a solution to share files with Customers. There will be separate login for each client, and they should have access to files of there company only.

Solution Suggested:

Client should create Project/Task for each client and for each assessment period (yearly, had yearly, quarterly). Files will be attached against Project/Task. Those Project/Task will be shared explicitly with Customer.

When customer login, they will have access to their Project/Task and files within.

**Comment by anandpdoshi** [comment]
Maybe later we can have a new app called Frappe Files ;)

**Comment by revant** [comment]
File Manager and private files are now available
