### ISSUE TITLE
Stock Transfer Enteries

### ISSUE THREAD

**Issue by toykraft** [frappe/erpnext#37382]
### Information about bug

The stock transfer entry STKTFR-2223-076 has a total value of Rs. 99,174.4968... however part of this entry is also hitting the Stock Adjustment ! 

### Module

stock

### Version

ERPNext: v14.41.1 (HEAD)

ERPNext Support: v0.2.1 (HEAD)

Frappe Framework: v14.50.0 (HEAD)

India Compliance: v14.16.2 (HEAD)

Frappe Insights: v1.2.0 (HEAD)

Journeys: v0.0.1 (HEAD)

### Installation method

None

**Comment by rohitwaghchaure** [comment]
@toykraft 
It seems to be related to incorrect valuation rate issue.
To fix the issue, you need to check the "Stock Ledger Invariant Check" report and do reposting for incorrect entries.
