### ISSUE TITLE
Chart Of Account Value / Balance Not Showing Up In V14.43.0

### ISSUE THREAD

**Issue by rawsel** [frappe/erpnext#37384]
### Information about bug

I just performed an update from ERPNext v14.33.0 to the latest version ERPNext V14.43.0. 

I updated the npm, node, yarn, and frappe-bench to the latest version before performing the update. 
After that I'm using this command to perform an update:

```
bench update --no-backup --reset
```
The update finished without showing any warning or error in the frappe-bench CLI. 
But after I login and inspect the chart of account the nominal or balance for each account is not showing up.

<img width="902" alt="Screenshot 2023-10-06 200243" src="https://github.com/frappe/erpnext/assets/131623802/7772ab5b-0279-41a5-94a4-9baeee3aff98">
<img width="452" alt="Screenshot 2023-10-06 200446" src="https://github.com/frappe/erpnext/assets/131623802/31cf2d9d-e08c-450e-b865-969e49a4df75">
<img width="294" alt="Screenshot 2023-10-06 200658" src="https://github.com/frappe/erpnext/assets/131623802/77f02883-d6dc-4cd9-ad0c-caf0314f1a5a">
<img width="925" alt="Screenshot 2023-10-06 201243" src="https://github.com/frappe/erpnext/assets/131623802/e43ee201-b032-4b7a-8de6-a7e17a0e950f">

### Module

accounts

### Version

ERPNext V14.43.0

### Installation method

manual install

**Comment by thida-bcn** [comment]
![image](https://github.com/frappe/erpnext/assets/62122640/9b6cd4f6-1a3e-497f-8ddb-0cc791407752)
you can set setting there

**Comment by rawsel** [comment]
Oh my god. I'm embarrassed lol. Thank you so much for the response!
