### ISSUE TITLE
Shipping Rule by Volume/weight of shipment

### ISSUE THREAD

**Issue by fderyckel** [frappe/erpnext#3740]
label: "Paid Development" as a follow up of the following issue.
https://github.com/frappe/erpnext/issues/3321

At the moment, we are not able to distributed the transport charge or other fix charged based on net weight (We can only do it base on either qty or amount).  We would like to add net weight on this list of choice.  

Validation rule: all items in the Purchase Receipt or LCV should have 
1. a net weight
2. the same unit of measure for net weight.  

Thanks

François

**Comment by rmehta** [comment]
Sames as #3717 ?

**Comment by fderyckel** [comment]
Almost.  
This net weight should be added both in LCV and in the additional tax & charges of the purchase receipt. 
Also it is more than just adding the transport charges manually.  It should be calculated automatically.
Best,
François

**Comment by graphskill** [comment]
This is an essential and should be top priority.  Many companies have shipping rates based on weight.

**Comment by federojoavellaneda** [comment]
Hi! how to generate a bountysource for this paid feature? It is a very important features for many companys.

**Comment by vishdha** [comment]
https://github.com/frappe/erpnext/pull/11672
