### ISSUE TITLE
Unable to find exchange rate. 

### ISSUE THREAD

**Issue by chanyork** [frappe/erpnext#37408]
### Information about bug

System did not find any exchange rate.

![Screenshot 2023-10-09 at 9 23 57 pm](https://github.com/frappe/erpnext/assets/28833849/44e4592d-6ed5-44a0-8287-c5fa0b7736ac)

### Module

selling

### Version

Frappe Version 13.58
ERPNEXT V13.53

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
Unable to find exchange rate for AUD to HKD for key date 2023-10-09. Please create a Currency Exchange record manually
```

**Comment by bosue** [comment]
See #37355, backported to v13 in #37365.
You‘ll need the latest update, then exchange rates should be fetched again.

**Comment by chanyork** [comment]
I had requested the update but has not been done yet.  Please help to do an update ASAP as I am not able to issue invoice now.

**Comment by maveezmh** [comment]
@bosue after update Exchage Rate is not working on both V13 and V14 
unable to fetch

![image](https://github.com/frappe/erpnext/assets/112148467/4cc37c40-4a01-4045-a33f-3e1b6c57be1b)


Same while invoicing

![image](https://github.com/frappe/erpnext/assets/112148467/50520b28-f9b6-4128-b495-8f42a30feb2c)

Exchange settings V13 not working 

![image](https://github.com/frappe/erpnext/assets/112148467/1b4d0a43-8505-4d82-96dd-977ee5b3c738)


cc @ruthra-kumar

**Comment by bosue** [comment]
@maveezmh:
![IMG_1800](https://github.com/frappe/erpnext/assets/46800703/b1f531d7-a33a-457a-bca5-5b67f1064e15)
On the Currency Exchange Settings page, you need to select “frankfurter.app“ and then Save.

@ruthra-kumar:
Should we add a patch to update the setting on running systems?

@chanyork:
I‘m sorry, this is no support board, so I can‘t really help you with updating your site on Frappe Cloud. Try this: https://frappecloud.com/docs/benches/updating_a_bench and feel free to ask fellow users on https://discuss.frappe.io

**Comment by ruthra-kumar** [comment]
@maveezmh 
V13 and V14 has 2 preconfigured service providers.
1. frankfuter.app - Free but has limited support for currencies. Supported ones: https://api.frankfurter.app/currencies
2. exchangerate.host - Has Limited free(1000 req/month) and paid services. Both the free and paid tier require API access key.

> Should we add a patch to update the setting on running systems?

@bosue 
Makes sense. Will add it.

**Comment by chanyork** [comment]
Yes please, Update.  Thank you
