### ISSUE TITLE
Discount override User

### ISSUE THREAD

**Issue by maveezmh** [frappe/erpnext#37405]
### Information about bug

User is able to give discount % on sales no option to set role who can override the condition 

![Screenshot 2023-10-09 at 12-17-34 Wheat Flour - Wheat Flour](https://github.com/frappe/erpnext/assets/112148467/f0d6b662-80bc-4ba1-bac4-095d7b83ea28)

### Module

stock, selling

### Version

V13 V14

### Installation method

FrappeCloud

**Comment by Nihantra-Patel** [comment]
You can manage via field level role permission manager.

![image](https://github.com/frappe/erpnext/assets/141945075/79323f15-11b4-4fb2-b741-1c59bf626ea5)

**Comment by maveezmh** [comment]
@Nihantra-Patel if we make any changes in standard fields bench migrate will reset those changes. its better to add a field in settings to define a role responsible to make changes. just like we have credit controller role

**Comment by Nihantra-Patel** [comment]
Many users with field permissions do not encounter any issues during migration. Field permission is a standard feature, and when you grant field permissions, they are applied consistently. These permissions are not removed during version updates, as many clients rely on this functionality.
