### ISSUE TITLE
Update Request

### ISSUE THREAD

**Issue by chanyork** [frappe/erpnext#37409]
### Information about bug

Please help to update my ERPNEXT due to some bug fixes that is require for exchange rate fetching.

Please perform the update as soon as you can.

petpalace.erpnext.com

### Module

selling

### Version

ERPNext: v13.53.0 (HEAD)
ERPNext Support: v0.2.1 (HEAD)
Frappe Framework: v13.58.12 (HEAD)
Journeys: v0.0.1 (HEAD)

### Installation method

None

**Comment by chanyork** [comment]
Urgently need help on this.

**Comment by chanyork** [comment]
Can someone help on this?

**Comment by s-aga-r** [comment]
@chanyork Please raise a Support Ticket [here](https://support.frappe.io/) if your site is hosted in [Frappe Cloud](https://frappecloud.com/). OR use the `bench update` command to update the self-hosted site.
