### ISSUE TITLE
Incoming email account not correct

### ISSUE THREAD

**Issue by MatthK** [frappe/erpnext#37422]
### Information about bug

On a new install of ERPNext Version 14.43.0 (Frappe Framework 14.51.0) I tried to create a new Email Domain. I entered the Incoming Server details as well as the Outgoing Settings. Chose IMAP and SSL and the corresponding ports.

When saving the page, I receive the following error message:

```
Incoming email account not correct
Error connecting via IMAP/POP3: [SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1007)
```

The email server serves multiple domains. I get the same error, using the actual domain name, or the default domain of the email server. The ERPNext domain is included as an Alternative Name in the SSL certificate. The SSL certificate is from Letsencrypt.

The same settings (with a different domain name) work in a different ERPNext Version 13 installation.

### Module

other

### Version

Frappe Version 14.51.0
ERPNext Version 14.43.0

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
Kindly upgrade to version 14 or 15, then refresh and check again because lots of bugs fixed in the new version.

Everything is working fine. No problems were encountered in the latest versions 14 and 15.
