### ISSUE TITLE
cannot open payment Gateway in erpnext14

### ISSUE THREAD

**Issue by R-Gourav** [frappe/erpnext#37425]
### Information about bug

Missing DocType
Field payment_gateway is referring to non-existing doctype Payment Gateway.
This particular message comes as a alert when i click into accounting --> payment gateway.
Also, paytm,razorpay and other integration is not available.I also integrated shiprocket that too is vanished. I also searched in searbar but no result. I am in the middle of project so,please help me ASAP .

### Module

accounts, ecommerce, integrations

### Version

Frappe Version- 5.17.2
erpnext version- 14

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
Missing DocType
Field payment_gateway is referring to non-existing doctype Payment Gateway. when i click on payment gateway
```

**Comment by mohsinalimat** [comment]
You have to install below branch of version-14 app.

https://github.com/frappe/payments

**Comment by R-Gourav** [comment]
$ bench --site install-app payments. Is this code is enough to install all gateway(razorpay, paytm,etc...)

**Comment by mohsinalimat** [comment]
Please check this.

https://github.com/frappe/payments/tree/develop/payments/payment_gateways/doctype

**Comment by R-Gourav** [comment]
Thank you so much @mohsinalimat . Similarly like paytm and razorpay , do you know how to install Phonepay  gateway in erpnext

**Comment by DonnC** [comment]
> Thank you so much @mohsinalimat . Similarly like paytm and razorpay , do you know how to install Phonepay gateway in erpnext

If there is an open source gateway created for ERPNext framework for that payment gateway (Phonepe) then you will be able to install it like any other erpnext application, but if its not available then unfortunately you will have to find a developer to develop the integration for you
When i checked up for Phonepe gateway for ERPNext, i couldnt find any at the moment
