### ISSUE TITLE
How to integrate phonepay in erpnext for payment gateway????

### ISSUE THREAD

**Issue by R-Gourav** [frappe/erpnext#37426]
### Information about bug

Please provide the necessary steps. 

### Module

integrations

### Version

Frappe - 5.17.2
erpnext- 14

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
no option
```

**Comment by R-Gourav** [comment]
$ bench --site <sitename> install-app payments.   Is this code is enough to install all gateway(razorpay, paytm,etc...)

**Comment by DonnC** [comment]
You can look at https://github.com/frappe/payments to see how other third-party gateways have been implemented, unfortunately there is no write up on how to go about integrating your own payment gateway unless you find a developer to do that for you.
