### ISSUE TITLE
feat: Request to Add Supplier Name Column Dynamically in Address and Contact Report within Buying Module

### ISSUE THREAD

**Issue by soundarya00** [frappe/erpnext#37433]
### Information about bug

Issue : Under the Buying Module, in the Address and Contact Report,  it currently lacks a dedicated column for Supplier Name, Instead of manually adding a Supplier Name column each time a new supplier is added using a series pattern, I believe it would be more efficient to have the system dynamically fetch the supplier name.

Steps :
1. Access the Buying module.
2. Navigate to the Address and Contact report.
3. Observe that there is no Supplier Name column.
4. Create a new supplier using a series pattern (e.g., Supplier-001, Supplier-002, etc.).
5. The report should dynamically display the Supplier Name associated with each supplier in the report without requiring manual column additions.
  
Expected : Ideally, there should be a column for the supplier name in the Address and Contact Report, allowing users to easily identify suppliers even when series patterns are used, This would save time and effort for users and ensure that the report always reflects accurate supplier information.

Please let us know if any further information or clarification is needed to implement this feature request effectively.

### Module

buying

### Version

Frappe Framework : v14.51.0 
ERPNext : v14.43.0 (version-14)

### Installation method

manual install

**Comment by niraj2477** [comment]
Can you share relevant screenshots?
@soundarya00
