### ISSUE TITLE
Stock Balance and Stock Ledger report remaining quantity difference

### ISSUE THREAD

**Issue by rehmankashif79** [frappe/erpnext#37441]
### Information about bug

Stock Balance and Stock Ledger report remaining quantity difference in some items any possible reasons

### Module

stock

### Version

14

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
no message two reports comparision
```

**Comment by rohitwaghchaure** [comment]
@rehmankashif79 Can you share the exact version of ERPNext app, also make sure that the Repost Item Valuation records are in the completed state.
