### ISSUE TITLE
sales return

### ISSUE THREAD

**Issue by annperera21** [frappe/erpnext#3745]
hi,in our newest update system we can make sales return by sales invoice. that method is better than previous method . but if you can make new Series , instead of " SINV " i think i'll more user friendly. from that  we can easily track it is a invoice or sales return. 
Please also create a report sales return (Account - Main Report- Sales return ) So then we can easily calculate how many sales return we do in the month.

**Comment by farhanayyaz1** [comment]
dear could you explain how to make sales return using sales invocie

**Comment by rmehta** [comment]
@annperera21 you can always create a new series via Naming Series and its a good idea to keep the series separate.

For Sales Return, you can filter by the Is Sales Return Filter

@farhanayyaz1 It is available in the latest release.
