### ISSUE TITLE
You cannot unset 'Read Only' for field Finance Book

### ISSUE THREAD

**Issue by trysyss** [frappe/erpnext#37469]
### Information about bug

Able to create multiple Finance Book but it will not show in Journal Entry. Trying to customize the form, it will show this error: You cannot unset 'Read Only' for field Finance Book.

### Module

accounts

### Version

Frappe Version: v14.51.0 (version-14)
ERPNext Version: v14.43.0 (version-14)

### Installation method

manual install

**Comment by trysyss** [comment]
With latest ERPNext release V14.44, Finance Book display bug is still around. But found some trick that works. Intention is to put a wrong value.
:: Read Only Dependency
myfield eval:doc.title=='My Value'

**Comment by deepeshgarg007** [comment]
@trysyss We have intentionally set it as read-only as users are not supposed to use finance book directly in Journal Entry. Its not a bug but intentional behaviour.
