### ISSUE TITLE
Problems filters in script report

### ISSUE THREAD

**Issue by letirc** [frappe/erpnext#3747]
In script reports when I try filter in the search fields located under each column header, and then to print only this records, all records are being printing. In the version 4 it works fine, also I
checked in other reports of version 5 and it happened the same problem.
In addition to , when I filter for this fields the total row is not showing.

PrintScreen:https://discuss.erpnext.com/t/problems-filters-in-script-report/6807

**Comment by rmehta** [comment]
I don't think this worked in v4 either.

**Comment by geekroot** [comment]
@rmehta i have the same issue and it's working in v4.

**Comment by rmehta** [comment]
tried to replicate, seems fixed
