### ISSUE TITLE
Traceback Log is been shown in production Mode

### ISSUE THREAD

**Issue by Shivam327** [frappe/erpnext#37474]
### Information about bug

1) Check Box for Log trace has been Disabled
![image](https://github.com/frappe/erpnext/assets/23412311/604f932e-2102-4fe2-8433-c3e8f1a567a6)
2) Site is Running in Production Mode
![image](https://github.com/frappe/erpnext/assets/23412311/69e08e28-93b5-423a-ad26-d72f7d0fa0a7)
Then Also If error is thrown Site shows Traceback Log
![image](https://github.com/frappe/erpnext/assets/23412311/a5d148ae-b20e-47f6-874c-b3b4ab003211)

### Module

other

### Version

ERPNext: v14.44.0 (version-14)
Frappe Framework: v14.52.0 (version-14)

### Installation method

manual install

**Comment by niraj2477** [comment]
The traceback that you are getting is because of an error thrown intentionally, nothing to do with system setting. If you look at REST API (i.e. `resourse`, `method`), you won't get any error if any occurred, you will just get `Not Found`. 

NOTE : This issue should be part of frappe.
@Shivam327

**Comment by Shivam327** [comment]
@niraj2477 
I have just posted the log for reference but orignal problem lies in traceback display. Thou i have turned off it in system settings but then also it's showing, and when gome through source code, it also has a check for Production but it seems that code is not working properly

**Comment by niraj2477** [comment]
The URL which you shared `http://127.0.0.1/api/method`, accepts method path that you can execute, but since you are not passing it, the system is throwing error from `execute_cmd()` method. For this one have to check if executable path is provided or not, if not provided just throw `Not found`.

ref:
> https://github.com/frappe/frappe/blob/develop/frappe/handler.py#L48

Here, no check had been made if `cmd` is None.

**Comment by Shivam327** [comment]
Please read Subject.
I don't have problem with error it is thrown because I have not passed any parameters.
The issue is Traceback is shown in production mode... which shouldn't be the case when I turn off the checkbox in system setting.
And also source code says that this should not be the case as it has a check for Production 
https://github.com/frappe/frappe/blob/c9bba3c1b29665ae22cdc4896372a5df0797437d/frappe/app.py#L369
Look at the above line

**Comment by ankush** [comment]
https://github.com/frappe/frappe/commit/3f142c1dcebc6ee928b821918f06dc68f7ddb2b1

**Comment by Shivam327** [comment]
@ankush I know I have gone through this code, But if you check after disabling the button then also it is showing traceback on the screen

**Comment by ankush** [comment]
You probably have developer mode enabled?

**Comment by Shivam327** [comment]
No Developer mode is turned off, You can also replicate it, I have tried all the things.
