### ISSUE TITLE
Impossibe to save Subcontracting Receipt if Batch tracking is active

### ISSUE THREAD

**Issue by TurkerTunali** [frappe/erpnext#37486]
### Information about bug

If backflush raw materials is based on BoM in the subcontracting settings and raw item's batch tracking is active, it is impossible to save the subcontracting receipt.

![undefined-high](https://github.com/frappe/erpnext/assets/710051/ba87b5f0-ed9c-48f8-b514-21fc4303774e)
[Longer version](https://vimeo.com/873746137)

ERPNext erases the selected batch on save and we can't save or submit the receipt.

[The faulty commit is this one.](https://github.com/frappe/erpnext/pull/33651)

---

Error is 
![image](https://github.com/frappe/erpnext/assets/710051/7739dc2d-179a-4be6-aa63-3cd06f49f8dc)

Settings are 
![image](https://github.com/frappe/erpnext/assets/710051/08d22e16-1395-4301-b5d1-01a7fff04bea)

### Module

stock, buying, other

### Version

ERPNext: v14.44.0 (version-14)
Frappe Framework: v14.52.0 (version-14)

### Installation method

manual install

**Comment by s-aga-r** [comment]
Fixed: https://github.com/frappe/erpnext/pull/40371

**Comment by TurkerTunali** [comment]
@s-aga-r thank you.
