### ISSUE TITLE
Bulk Warehouse Upload Issue

### ISSUE THREAD

**Issue by RJMHASKE** [frappe/erpnext#37493]
### Information about bug

we are uploading 6000 Nos warehouse through data upload tool, Preparing template as per require but system showing below error Parent Warehouse does not exit. 

**when we prepare template as Group parent manner then why system not auto crate parent warehouse first then add linked child warehouse.** 

<img width="543" alt="image" src="https://github.com/frappe/erpnext/assets/119041865/441ea60f-ab11-4c3d-b2f7-533b8c15f501">

### Module

stock

### Version

ERPNext: v13.53.0 (HEAD)
Frappe Framework: v13.58.12 (HEAD)

### Installation method

FrappeCloud

**Comment by Nihantra-Patel** [comment]
Hi @RJMHASKE,

When you're importing a tree structure, make sure to set the parent data first, and then set the child data. This helps the import process go smoothly. When adding child data, always ensure that the parent data is already added. Check your Excel data to ensure it's in the correct sequence before importing.

We no longer provide support for version 13 or older. Kindly upgrade to version 14 or 15, then check again.

Everything is working fine. No problems were encountered in versions 14 and 15.
If the issue occurs then please create a new issue according to the version (14 or 15).

Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!
