### ISSUE TITLE
Item may not be marked a Fixed Asset after saving

### ISSUE THREAD

**Issue by bosue** [frappe/erpnext#37505]
You create an item via Quick Entry form without being asked if it is supposed to be a Fixed Asset. When you go on to the full edit form, it’s too late and you can‘t check the box anymore as it‘s disabled as soon as it’s saved:

![IMG_1832](https://github.com/frappe/erpnext/assets/46800703/1dfd407d-6366-4355-8562-a2e48f00876f)

This is a bit of an anti-pattern: a non-submittable Doctype that behaves like one and doesn‘t even allow editing in the form of amending.

Workarounds are of course: go straight to the full edit form, or duplicate your item and later delete the original one.

But in the end, the proper solution is that editing it should be possible. Of course this isn‘t easy to do…

For now we should at least add „Is Fixed Asset“ to the Quick Edit form.

**Comment by niraj2477** [comment]
> For now we should at least add „Is Fixed Asset“ to the Quick Edit form.

Yes, doing so will resolve this issue. IMO, `set_only_once` property is there for a reason.
