### ISSUE TITLE
Seemingly random company’s default currency being displayed

### ISSUE THREAD

**Issue by bosue** [frappe/erpnext#37526]
### Information about bug

In a multi-company setting, with different company default currencies, the currency displayed in the Workspace dashboard seem to randomly oscillate between all the different companies set up, while the values do refer to the default company being set up:

![IMG_1858](https://github.com/frappe/erpnext/assets/46800703/d60641c6-3e11-414f-a8f3-af5b486625a5)
![IMG_1859](https://github.com/frappe/erpnext/assets/46800703/a703cace-7dc4-44be-83d1-415e2d2fbc74)
![IMG_1856](https://github.com/frappe/erpnext/assets/46800703/717123db-8d6e-499d-972d-4ee5c2db2966)

Company data in this case is from testing, however the initial and default company has been properly set up with currency “EUR”:
![IMG_1860](https://github.com/frappe/erpnext/assets/46800703/b6cac2df-4526-4143-b453-592945857df3)

This one may probably be related: #37507.

### Module

other

### Version

Frappe / ERPNext: dev

### Installation method

None

**Comment by Nihantra-Patel** [comment]
Hi @bosue,

Everything is working fine. No problems were encountered in version 15.
If the issue occurs then please create a new issue or reopen it according to the version (14 or 15) and also share the screenshot and video.

Thank You!
