### ISSUE TITLE
How to translate the language in JSON JavaScript Python files, adding it to the translations file does not work

### ISSUE THREAD

**Issue by mrchenxxx** [frappe/erpnext#37536]
### Information about bug

Implement translation

### Module

other

### Version

docker  erpnext v14.44.0

### Installation method

None

**Comment by s-aga-r** [comment]
@mrchenxxx Please ask your queries on our [Forum](https://discuss.frappe.io/) or [Telegram Group](https://t.me/frappeframework).

Docs for translations:
- https://frappeframework.com/docs/user/en/translations
- https://frappeframework.com/docs/user/en/translations
