### ISSUE TITLE
Incomplete processing of supplier quotations upon submit by the supplier from the supplier portal

### ISSUE THREAD

**Issue by GichanaMayaka** [frappe/erpnext#37531]
### Information about bug

I'm having trouble when suppliers submit their quotations from the portal. Upon receiving an email asking them to quote their prices, they populate the rates field then when they submit, they receive a modal with the title "Message" and nothing else, as below:.
![SQ Submit](https://github.com/frappe/erpnext/assets/12395135/95fb05c9-bc2d-43fa-ae73-24a50d705a9d)
The dev tools do not display any error message indicating that no exception/error is being thrown/raised. The submitted supplier quotation does not register as a record in the database either. 

It should be noted that there is a customised application (https://github.com/navariltd/navari_rfq_opening) that does some validation and processing before sending the email to suppliers to quote their prices. The error on submission happens whether the application's override whitelisted method is called, or the system's default implementation is called. Having said that, the issue still persists even without any custom application installed. It should also be noted that the issue resolves when giving the supplier additional permissions - Purchase User in this case - but this has the caveat that the supplier can access information they should not be privy to via the "Switch to Desk" option in the supplier portal.

### Module

buying

### Version

Frappe Version: 15.0.0-dev
ERPNext Version: 15.0.0-dev

### Installation method

FrappeCloud

**Comment by muchai** [comment]
@rohitwaghchaure Despite the updates, the error occurs if the supplier has an address attached to them.
![image](https://github.com/frappe/erpnext/assets/1822868/bd097807-ebf9-4929-9dd2-cefe0ee91c96)
Solution is to grant All to Address doctype.
