### ISSUE TITLE
Supplier Quotation not reflecting the prices the client submitted or just reflecting 0 Zero rate

### ISSUE THREAD

**Issue by erassystems** [frappe/erpnext#37537]
### Information about bug

Upon trying the RFQ feature which provides a link where suppliers can directly input their price offers, after clicking the submit button, there are 2 issues that are encountered:

A. Despite typing prices for all items in the RFQ Link, only one item price remained and the other rates for other items became 0 zero.

![image](https://github.com/frappe/erpnext/assets/148128926/71a6c857-e74f-4a83-b202-7e2a4ce8215e)

Item prices becomes zero.

![image](https://github.com/frappe/erpnext/assets/148128926/c44b150b-7a6a-4f70-a649-7306632eea07)

B. The submit button becomes "PAY" after submitting. From the perspective of the supplier, why should they be the ones to pay? Also this link leads to error. 

![image](https://github.com/frappe/erpnext/assets/148128926/6815506b-d256-4fe9-9da5-74dba38c8ea1)

![image](https://github.com/frappe/erpnext/assets/148128926/b97b68cf-6138-4930-83d3-f010effcc8bd)

Hope these issues for RFQ will be resolved so that we can fully utilize these features.

### Module

buying

### Version

Frappe Version 14
Erpnext 14.43.0

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 95, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1622, in call
    return fn(*args, **newargs)
  File "apps/erpnext/erpnext/accounts/doctype/payment_request/payment_request.py", line 408, in make_payment_request
    grand_total = get_amount(ref_doc, gateway_account.get("payment_account"))
  File "apps/erpnext/erpnext/accounts/doctype/payment_request/payment_request.py", line 518, in get_amount
    if grand_total > 0:
UnboundLocalError: local variable 'grand_total' referenced before assignment
```

**Comment by rohitwaghchaure** [comment]
@erassystems 
The first issue is not able to replicate and working fine

<img width="1073" alt="Screenshot 2024-01-09 at 3 26 55 PM" src="https://github.com/frappe/erpnext/assets/8780500/1e7cf1d1-987c-4f4a-a67c-c3a9362639d0">

For the second issue, in the core there is no provision to make the Payment against the supplier quotation. So this is not a bug but a feature request. Kindly create a new Github issue for this feature request.
