### ISSUE TITLE
Delivery Note - Bill to Customer 1 and Ship to Customer 2

### ISSUE THREAD

**Issue by rasika2502** [frappe/erpnext#3754]
The issue is explained below

We have EPC (L&T) and PSUs (SAIL,GAIL) as our customers. 
So I receive SO from Customer 1 (L&T) for supply to Customer 2(SAIL/GAIL etc). 

In Delivery Note, I added a custom field for Customer 2 with link to the Customer doctype. 
However it still shows the address of the Customer1 in the shipping address.

So what i am looking for is, is there any way wherein once i put the name of Customer 2, the shipping address should link to the addresses associated with that particular customer.

Attaching an image for better understanding
![delivery note - shipping issue](https://cloud.githubusercontent.com/assets/8692486/8977098/74bf415a-36b3-11e5-9960-9f5c6ba1bacd.JPG)

**Comment by rmehta** [comment]
best to use custom fields & custom print format in such a scenario
