### ISSUE TITLE
Reimplement TestCompany on top of TestNestedSet

### ISSUE THREAD

**Issue by bosue** [frappe/erpnext#37547]
### Information about bug

`test_company.py` should use `frappe/tests/test_nestedset.py` as a base class and inherit its extensive tests, instead of doing the same all over again.

For one or two tree doctypes, this may not matter all too much, but will later vastly improve maintenance and testing of further tree doctypes. Also, this way we‘re backtesting the base test class.

See also: #37546.

### Module

other

### Version

Frappe / ERPNext: dev

### Installation method

None

**Comment by Nihantra-Patel** [comment]
A lot of functionalities may have changed so try to test the new functionality accordingly
