### ISSUE TITLE
Item Variants Update

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#3756]
- [ ] Item Attributes table in Item Template will be "Valid Attributes"
- [ ] **Make Variant** button in Item Template
- [ ] When **Make Variant** is clicked, show popup of all Items Attributes, ask user to fill values
- [ ] User fills values and clicks on "Search"
- [ ] If no options, show button "New"
- [ ] When "New" is clicked, a new Item form opens up with the Attributes table filled up. User sets item code and saves.

**Comment by adityaduggal** [comment]
@neilLasrado any update on the way item variant handles floats (decimal) ranges. Kindly let me know once a fix is pushed for the same.

**Comment by neilLasrado** [comment]
@adityaduggal yes sure... its WIP

**Comment by adityaduggal** [comment]
@neilLasrado is the variants part complete. Please let me know as the pull request is pending since 4 days in develop.

**Comment by neilLasrado** [comment]
@adityaduggal some issues in the PR, Fixing it.

**Comment by adityaduggal** [comment]
any news on this issue...can it be done before the holidays or would it be going to next week.

**Comment by anandpdoshi** [comment]
I just need to review the changes. We can merge it once that is done and
there's no problem that can be found.
