### ISSUE TITLE
Warehouse Rename Issue

### ISSUE THREAD

**Issue by RJMHASKE** [frappe/erpnext#37570]
### Information about bug

We having 6000 Nos of warehouses in system, In some warehouses need correction in code or name but system can't rename it.

why this rename option remove, we are trying to rename custom development but core can't do this, please confirm.

we can't use delete transactions and disable options.

<img width="780" alt="image" src="https://github.com/frappe/erpnext/assets/119041865/e8eb4f40-d648-4ff3-83ae-b61f5d47dc04">

### Module

stock

### Version

ERPNext: v14.38.0 (HEAD)
Frappe Framework: v14.48.1 (HEAD)

### Installation method

FrappeCloud

**Comment by RJMHASKE** [comment]
Hello Team,

Any update on this Issue??

**Comment by s-aga-r** [comment]
@RJMHASKE 

I am able to rename the warehouse:

https://github.com/frappe/erpnext/assets/63660334/92f66e9a-135d-4373-ae34-e8754d181cb8

**Comment by RJMHASKE** [comment]
Hi,
Please cross check u r warehouse name is not changing, only lable change
but unique name not change.

I have checked multiple times but issue not resolve

Ramesh

**Comment by s-aga-r** [comment]
@RJMHASKE 

Warehouse renaming (`name` field) is disabled as it may cause data inconsistency.

ref: https://github.com/frappe/erpnext/pull/28712
