### ISSUE TITLE
Credit Note Create Issue against Sales Invoice (Timesheet Link)

### ISSUE THREAD

**Issue by RJMHASKE** [frappe/erpnext#37583]
### Information about bug

we are not able to create credit note to customer against sales invoice , which sales invoice created against timesheet.
below popup show

<img width="735" alt="image" src="https://github.com/frappe/erpnext/assets/119041865/7b057bdd-df87-469f-9a03-12a8aaf0ea04">

when we go on timesheet to cancelled so system don't allow, system say 1st cancelled Sales Invoice but how we can create credit note to customer??
<img width="727" alt="image" src="https://github.com/frappe/erpnext/assets/119041865/1feeb556-9c14-43cc-a768-a1a4c342eace">

### Module

accounts

### Version

ERPNext: v14.38.0 (HEAD)
Frappe Framework: v14.48.1 (HEAD)
India Compliance: v14.16.2 (HEAD)

### Installation method

FrappeCloud

**Comment by Nihantra-Patel** [comment]
Hi @RJMHASKE,

Issue has been resolved and Everything is working fine. No problems were encountered in versions 14 and 15.

Please check it.


https://github.com/frappe/erpnext/assets/141945075/b3b8955a-6fab-464c-baeb-eac30ed1efb6


Thank You!

**Comment by RJMHASKE** [comment]
@Nihantra-you are doing wrong testing. This bug is related to credit note. Pls checking adding Timesheet against customer and project > fetch timesheet in sales invoice > create credit note against same invoice. same issue in V15 also
<img width="789" alt="image" src="https://github.com/frappe/erpnext/assets/119041865/1582d6d8-844c-4ca7-baa9-436f5c478a28">
