### ISSUE TITLE
Customer Item Code problem in Sales Order

### ISSUE THREAD

**Issue by TurkerTunali** [frappe/erpnext#37593]
### Information about bug

We can have different item codes for different customers in the Item master. "customer_item_code" is correctly fetched in the item details of the Sales Order transaction. But if we change the Customer in the Sales Order, "customer_item_code" doesn't change.

Item Master:
![image](https://github.com/frappe/erpnext/assets/710051/bc49b140-967d-4ab8-821b-10a808befe4e)

Sales Order behaviour:

https://github.com/frappe/erpnext/assets/710051/e05294c9-8c82-475d-8aab-6f225341a0d5

It fetches the customer item code correctly. But if I change the Customer it doesn't refreshed. We can force it if we change the Item Code.

ERPNext should trigger a refresh to fetch the correct customer item codes. If customer item code is exist for the selected customer it should fetch it and update it or it should delete it.

### Module

selling

### Version

ERPNext: v14.28.1 (version-14)
Frappe Framework: v14.40.1 (version-14)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
None
```

**Comment by Nihantra-Patel** [comment]
Hi @TurkerTunali,

You're correct, but it's becoming difficult to implement this commonly because the customer reference code will be set by the [get_item_details](https://github.com/frappe/erpnext/blob/version-14/erpnext/stock/get_item_details.py#L38) method. So, if you change the customer, the code won't be set because it depends on the selected item. Here, I'm sharing the code.

```js
frappe.ui.form.on('Sales Order', {
    customer: function(frm) {
        frm.doc.items.forEach(function(item) {
            get_ref_code(frm, item);
        });
    }
});

function get_ref_code(frm, item) {
    var customer = frm.doc.customer;
    var customer_group = frm.doc.customer_group;
    var item_code = item.item_code;
    var foundCustomerItemCode = false;

    frappe.call({
        method: 'frappe.client.get',
        args: {
            doctype: 'Item',
            filters: {
                item_code: item_code
            },
        },
        callback: function(r) {
            if (r.message) {
                for (var row in r.message.customer_items) {
                    var cust_code = r.message.customer_items[row];
                    if (cust_code.parent == item_code) {
                        if (cust_code.customer_name == customer) {
                            // If customer-specific item code found
                            frappe.model.set_value(item.doctype, item.name, 'customer_item_code', cust_code.ref_code);
                            var foundCustomerItemCode = true;
                            break;
                        } else if (cust_code.customer_group == customer_group) {
                            // If customer group item code found and no customer-specific item code found yet
                            frappe.model.set_value(item.doctype, item.name, 'customer_item_code', cust_code.ref_code);
                            foundCustomerItemCode = true;
                        }
                    }
                }
            }
        }
    });
}
```

we're planning to submit a pull request (PR) to address this issue and set it commonly. The problem is that the entire code is written in js, so merging it might be challenging, but we'll attempt it.

Thank You!
