### ISSUE TITLE
Rename Issue

### ISSUE THREAD

**Issue by thida-bcn** [frappe/erpnext#37598]
### Information about bug

Previously Version 13 allow renaming 
1) Fixed Assets
2) Serial

At Version 14, unable to rename
1) Fixed Assets
2) Serial

### Module

accounts, stock

### Version

![image](https://github.com/frappe/erpnext/assets/62122640/37db6f15-e75b-4a88-874c-989c0b62a36f)
![image](https://github.com/frappe/erpnext/assets/62122640/b7150e59-1dea-4875-b5f5-b7f2c7c1a0d9)

### Installation method

manual install

**Comment by s-aga-r** [comment]
@thida-bcn We have disabled the renaming of Serial No in v14 as the Serial No is used as a `Small Text` field in DocTypes like Purchase Receipt, Delivery Note, Stock Ledger Entry, etc. So, If you rename the Serial No the same will not be updated in the documents/transactions.

In v15 we have introduced [Serial and Batch Bundle](https://docs.erpnext.com/docs/user/manual/en/serial-and-batch-bundle) which solves the problem we have with `Small Text`.
