### ISSUE TITLE
ERPNEXT UPDATE ASKING FOR PASSWORD AND USERNAME OF GITHUB

### ISSUE THREAD

**Issue by Sealcoatings** [frappe/erpnext#37592]
### Information about bug

Hi when i run bench update --reset 
i get this prompt 

HEAD is now at 6931db98f1 chore(release): Bumped to Version 14.44.1
$ find . -name "*.pyc" -delete
Skipping pull for app sealapp
$ git fetch --all
$ git reset --hard upstream/develop
HEAD is now at 30e5deb chore: loosen pycryptodome and install mariadb
$ find . -name "*.pyc" -delete
Skipping pull for app library_management
$ git fetch --all
Username for 'https://github.com': 
Password for 'https://github.com':
this is the first time its happening

### Module

other

### Version

erpnext 14

### Installation method

None

**Comment by agritheory** [comment]
This is not a bug. You need to add a deploy key to the repo and your local instance.
https://gist.github.com/agritheory/4422bd0abc61f873360eb3e164046a93

**Comment by Sealcoatings** [comment]
> This is not a bug. You need to add a deploy key to the repo and your local instance. https://gist.github.com/agritheory/4422bd0abc61f873360eb3e164046a93

Thanks for that, is there a erpnext guide to do it. before i use to update as normal. why now it is asking for it

**Comment by Sealcoatings** [comment]
Im geting this error after the password
remote: Repository not found.
fatal: repository 'https://github.com/f-9t9it/project-control.git/' not found
ERROR: git fetch --all
subprocess.CalledProcessError: Command 'git fetch --all' returned non-zero exit status 128.

The above exception was the direct cause of the following exception:

**Comment by agritheory** [comment]
The root cause is that you cannot use https:// remotes for private projects. Your options are:
- Add a deploy key for the private projects
- Uninstall the app(s) with `bench remove-from-installed-apps {app_name}`
- Exclude the apps from `bench update` with  `bench exclude-app {app_name}`

**Comment by ankush** [comment]
Simpler alternative: setup git over ssh for private projects.

Not really a bug.

**Comment by agritheory** [comment]
Yes, that is implicit with a deploy key. It's not simpler, it's part of the requirement. You should not share an SSH key between production and development environments.
