### ISSUE TITLE
Email address bar

### ISSUE THREAD

**Issue by supportTware** [frappe/erpnext#3759]
I have discovered that when you want to send a mail, it doesn't retain the email address you have used before, you need to type the email address again and again.It should have a temp buffer where email addresses are stored when it has been used to send a mail.

An instance is, if you want to send a mail to an applicant after creating the applicant and the position applicant applied for, when you use the Email under menu, it shows you the necessary fields but the needed address would not be there,Moreso, email addresses that have been used before was still typed in as normal email id,meanwhile it is expected have cc/Bcc field just in case you need to copy some people in the mail.
Would be glad if this issue is looked into.

**Comment by rmehta** [comment]
In Job Applicant, it will automatically select the Email ID (if set). Cannot replicate.
