### ISSUE TITLE
Item Quantity changes when Invoicing

### ISSUE THREAD

**Issue by monojoker** [frappe/erpnext#3760]
Guys, not sure if this is something I've created - have been setting up stock for inventory, etc but these items were not affected/changed in any way. But we have a couple of Sales Orders where, when invoiced the item quantities change from 1.00000 to something very much lower - see the below screenshots. Can you investigate and tell me what's going on please? I can amend quantities when we invoice but this shouldn't be happening...

SO1 - M26774

![image](https://cloud.githubusercontent.com/assets/10917366/9001288/d25a094a-3798-11e5-9bed-3694f03519e8.png)

Generates Sales Invoice

![image](https://cloud.githubusercontent.com/assets/10917366/9001297/e983ea78-3798-11e5-88b2-b9d91e2281d8.png)

Second item (postage) is also REMOVED from invoice items.

SO2 - M26733

![image](https://cloud.githubusercontent.com/assets/10917366/9001317/1d2b63ce-3799-11e5-9c8a-07dd4edf707f.png)

Generates Sales Invoice

![image](https://cloud.githubusercontent.com/assets/10917366/9001324/2c9b7c2c-3799-11e5-9e1d-a16c63f47256.png)

Thanks.

**Comment by rmehta** [comment]
@monojoker Seems like you have already made an invoice against the given SO, with some pending qty. The invoice is pulling the pending qty (by value).

Ideally there should be a setting which allows you to choose pending qty by value or by qty. Currently it does by value.

**Comment by monojoker** [comment]
Where is that actual field I can't see a Pending Quantity on either SO or SI? Could this be caused by a rounding amount discrepancy given we go to 6 decimal places for our per unit pricing on some orders?

Thanks for the response I will mark these as invoiced and we can move on.
