### ISSUE TITLE
Version 15 Installation issue

### ISSUE THREAD

**Issue by precihole** [frappe/erpnext#37626]
frappe.exceptions.LinkExistsError: Cannot delete or cancel because Report Tax Detail is linked with Workspace Accounting at Row: 46
![image](https://github.com/frappe/frappe/assets/111174201/18bf28ae-e14c-4bbc-a90c-eb6e16d99b6b)

**Comment by mrPauwHaan** [comment]
I am also facing this error and I am not able to pursue with the update because of this. I also cannot change anything in frappe since I am in the middle of migrating to v15

**Comment by mrPauwHaan** [comment]
I am facing the same issue

**Comment by thirurepo** [comment]
same issue for me, any fix, pls help
