### ISSUE TITLE
Unable to delete auto created demo company

### ISSUE THREAD

**Issue by maveezmh** [frappe/erpnext#37634]
### Information about bug

On installation i setup the company using demo data, as standard behaviour
the demo company was created with transaction 

but when i try to delete the demo company its not allowing me to delete the same

>> there are two companies

![image](https://github.com/frappe/erpnext/assets/112148467/1bf3ab8d-3ee7-4f08-8edc-ef35b9896e70)

>> trying to delete demo company which throws following error

![image](https://github.com/frappe/erpnext/assets/112148467/8f2eb1b4-9ed5-4c09-a8e7-34f2a211b895)

>> when checked global defaults it shows other company as default. 

![image](https://github.com/frappe/erpnext/assets/112148467/a13d73e2-3ef2-4b55-9556-2898c217d906)

>> Kindly advise

### Module

accounts, stock, buying, selling

### Version

Installed Apps

ERPNext: v15.0.0 (HEAD)

Frappe Framework: v15.0.0 (HEAD)

Frappe HR: v15.0.0-dev (HEAD)

### Installation method

FrappeCloud

**Comment by deepeshgarg007** [comment]
@maveezmh You should get a floating button below to delete this demo company, is that button not visible for you?

**Comment by maveezmh** [comment]
![image](https://github.com/frappe/erpnext/assets/112148467/d4f6355f-cbb7-457d-aea3-4c82d39bc493)

its throwing this error  @deepeshgarg007
