### ISSUE TITLE
Event Producer/ Event Streaming  

### ISSUE THREAD

**Issue by Rohitkumarthongar** [frappe/erpnext#37633]
Hi Team, i want fetch data from site to another site so check and found a event Streaming feature in Doc where @ruchamahabal explain it but when u try to find i don't get, so can u tell me u have another alternative to share data from site to site ?

**Comment by ruchamahabal** [comment]
It has been moved to a separate app: https://github.com/frappe/event_streaming
You can install this app and check

**Comment by Rohitkumarthongar** [comment]
@ ruchamahabal Thank you
