### ISSUE TITLE
Customize Form view takes too long to arrange the fields.

### ISSUE THREAD

**Issue by adityaduggal** [frappe/erpnext#3763]
When we arrange the fields in Customize form view then after updating the form view the code just hangs the server as its too resource heavy.

Ex: If a form has 100 fields and if I move field # 100 to field no.1 and then update the form then the system is going to take a lot of server resources where as if we do the same change in the Property setter via idx its done within seconds.

**Comment by rmehta** [comment]
Now then cannot be arranged :stuck_out_tongue_winking_eye:

**Comment by adityaduggal** [comment]
Super Like.....once again another of those regressive steps....
