### ISSUE TITLE
Specific Price List

### ISSUE THREAD

**Issue by Puntoitalia** [frappe/erpnext#3765]
We are not able to see the appointed price list which was applied in a submitted Sales Order. Which makes us very difficult in understanding and controlling the pricing. We can only see it when preparing the Sales Order, but unfortunately, not after the sales order has been submitted. It is affecting our work routine and management. Please kindly find a way to put it back.

Thank you very much.

**Comment by rmehta** [comment]
@Puntoitalia it is not hidden via code, did you hide it via Customize Form?

**Comment by Puntoitalia** [comment]
Dear Rushabh,

No, I checked it already. It was not checked hidden in customize form.
Please help to make it showed in our form.

Thank you,
Trang


_______________________________________________________________________________________

[cid:image001.jpg@01CE9909.68DD1DC0]

Trang Thi Ha (Ms)

Tel: +84-(0)4-6258 3510
Fax: +84-(0)4-6258 1801
Mobile : +84-(0)977-716592

Email: assistant@puntoitalia.asia<mailto:assistant@puntoitalia.asia>
www.puntoitalia.asia<http://www.puntoitalia.asia/>

[Heading]<http://www.puntoitalia.asia/>


P Please consider your environmental responsibility before printing this e-mail

[in_dark]<http://www.linkedin.com/company/punto-italia-vietnam> [twitter02_dark] <https://twitter.com/Punto_Italia>  [facebook_dark] <http://www.facebook.com/puntoitalia.asia>       [skype_active] <skype:dothuy113?chat>

**Comment by rmehta** [comment]
We will reply you via support.

**Comment by delpuso** [comment]
can i hide the specific Pricelist? ill try to hide the Standard buying because this is confidential. how to hide it?

![image](https://cloud.githubusercontent.com/assets/27795514/25215091/c2cf53c0-25cd-11e7-89e4-48894451ef91.png)
