### ISSUE TITLE
Over Order Allowance in Selling Settings

### ISSUE THREAD

**Issue by bosue** [frappe/erpnext#37664]
Sry if I‘m missing something out or am otherwise wrong.

But I‘m really wondering whether the description of “Over Order Allowance“ added in f5937f46cb60f3521463f7a4c80c765f8a65e52b to Selling Settings hits the mark.

`"description": "Percentage you are allowed to order more against the Blanket Order Quantity. For example: If you have a Blanket Order of Quantity 100 units. and your Allowance is 10% then you are allowed to order 110 units."`

This is confusing. It is also exactly the same description as was added in d7da8928ac44df3a84f6099fc7bfbc9a9161be20 to Buying Settings.

You place an order to purchase, but you receive an order to sell. Sure we have representations for both sides in ERPNext, but they’re still not the same.

If I get it right, the description should rather be something like:

`"description": "Percentage you are allowed to **sell** beyond the Blanket Order Quantity. For example: If you have a Blanket Order for a quantity of 100 units, and your allowance is 10%, then you are allowed to **sell** up to 110 units."`

### Module

selling

### Version

Frappe / ERPNext: dev

### Installation method

manual install

**Comment by bosue** [comment]
Should it better be called “Maximum Blanket Order Overage”?

“Over Order Allowance” is quite hard to associate with Blanket Orders. It might as well be associated to a Credit Limit or an individual order overrun as is common in the printing industry.

That’s probably why the description has to be so long. A long description often points to a suboptimal name that needs a lot of explanation.

For now, we would probably be renaming it on the surface only, but please share your thoughts, @s-aga-r! 🤗

**Comment by s-aga-r** [comment]
@bosue makes sense, will rename the field from Over Order Allowance to Blanket Order Allowance (as we have used the same convention for other % fields) and update the description in both Buying and Selling Settings.

**Comment by bosue** [comment]
Thx. In this case, with a sufficiently specific field title and precise wording, I guess we also may substantially shorten the description:

- “Percentage you are allowed to **order** beyond the Blanket Order quantity.“
- “Percentage you are allowed to **sell** beyond the Blanket Order quantity.“

(Pls note the lowercase “q” in quantity, too.)

This should do. Adding an example is redundant and a bit excessively verbose.
