### ISSUE TITLE
Display Error in Edge on Windows 10

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#3769]
![2015-08-02 16_20_06-new customer 1 - new customer 1 - microsoft edge](https://cloud.githubusercontent.com/assets/9136094/9026537/94701796-3932-11e5-97ac-7e85bb82a899.png)
Overlay of "X" and "link" button in form fields

**Comment by rmehta** [comment]
seems like a boostrap issue. Let Edge get stable first.
