### ISSUE TITLE
PIN code should be ZIP code or Postal Code

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#3770]
We believe "Postal Code" would be the best name for it. You called it PIN Code which neither of us has ever heard before.
![2015-08-02 16_24_38-start](https://cloud.githubusercontent.com/assets/9136094/9026556/3cc69050-3933-11e5-8db3-6df7ee2ee641.png)

**Comment by anandpdoshi** [comment]
Agreed. Will change it. Thanks !!
