### ISSUE TITLE
Error: could not convert string to float: 'outstanding_amount'

### ISSUE THREAD

**Issue by SanderVanDenBerk** [frappe/erpnext#37706]
### Information about bug

When upgrading ERPNext from V13 to V14 according to this [manual](https://cloud.erpgulf.com/blog/support-forum/erpnext-upgrade-from-version-13-to-version-14-ubnutu) I encounter an error.

There is an issue when migrating the Doctype: Purchase Invoice. This is when executing the ERPNext patch: 'Executing erpnext.patches.v14_0.change_is_subcontracted_fieldtype in test-erp (_538750cc54da9304)' . See error log below.

Any idea/tips on how to fix this issue?

### Module

buying

### Version

ERPNext: v13.54.5 -> V14
Frappe Framework: v13.58.14  -> V14

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
      self = <frappe.database.mariadb.schema.MariaDBTable object at 0x7f9ab432ddb0>
  File "/home/bench/frappe-bench/apps/frappe/frappe/database/mariadb/schema.py", line 72, in alter
    col.build_for_alter_table(self.current_columns.get(col.fieldname.lower()))
      self = <frappe.database.mariadb.schema.MariaDBTable object at 0x7f9ab432ddb0>
      col = <frappe.database.schema.DbColumn object at 0x7f9ab41e5420>
  File "/home/bench/frappe-bench/apps/frappe/frappe/database/schema.py", line 247, in build_for_alter_table
    self.default_changed(current_def)
      self = <frappe.database.schema.DbColumn object at 0x7f9ab41e5420>
      current_def = {'name': 'paid_amount', 'type': 'decimal(21,9)', 'default': '0.000000000', 'index': 0, 'unique': 0}
      column_type = 'decimal(21,9)'
  File "/home/bench/frappe-bench/apps/frappe/frappe/database/schema.py", line 262, in default_changed
    return self.default_changed_for_decimal(current_def)
      self = <frappe.database.schema.DbColumn object at 0x7f9ab41e5420>
      current_def = {'name': 'paid_amount', 'type': 'decimal(21,9)', 'default': '0.000000000', 'index': 0, 'unique': 0}
  File "/home/bench/frappe-bench/apps/frappe/frappe/database/schema.py", line 302, in default_changed_for_decimal
    return float(current_def["default"]) != float(self.default)
      self = <frappe.database.schema.DbColumn object at 0x7f9ab41e5420>
      current_def = {'name': 'paid_amount', 'type': 'decimal(21,9)', 'default': '0.000000000', 'index': 0, 'unique': 0}
builtins.ValueError: could not convert string to float: 'outstanding_amount'
```

**Comment by SanderVanDenBerk** [comment]
I have been debugging a bit further and I discovered that the table is not loaded in correctly in frappe (see screenshots). The default on the paid_amount is set to nothing (Null) be is filled with 'outstanding_amount'. 

![image](https://github.com/frappe/erpnext/assets/24277377/7b93e281-193d-4288-b6a9-86625d98b95e)

![image](https://github.com/frappe/erpnext/assets/24277377/a9638809-9c03-4616-92d5-6f44992a21f8)

Anyone an idea where I can go looking further, this is blocking my upgrade to version 14.

**Comment by deepeshgarg007** [comment]
@SanderVanDenBerk This is a data-related issue that you'll have to resolve at your end. Closing this issue
