### ISSUE TITLE
 Product wise raw material tracking 

### ISSUE THREAD

**Issue by inventobd** [frappe/erpnext#3771]
Hello

I,m manufacturing 2 items example: Item x and item Y which are books at the same time .

I have purchased same raw materials with different price and from same supplier for both this books which is ex: book binding (1 for item x with bdt 2000 and another for item y with bdt 3000) . Now when both of them are in stock how can I track which material I have purchased for item x and which one for item y ?

Thanks

**Comment by rmehta** [comment]
If you have such a variance, use serialized inventory.

**Comment by inventobd** [comment]
Hello @rmehta 
Thank you very much for your kind answer . Unfortunately I have a problem using serialized inventory . I,m doing production of books so my raw materials are book binding , printing , cover design , laminating . For production of 100 copy of a book  I have to purchase all those service / raw materials once for a specific book .  So in my case quantity of my raw materials is 1 of each item for 100 copy . So when I create production order it automatically made  fraction of each item. So when I try to transfer material to WIP warehouse I got this error message 
Serial No Pro - One Off quantity -0.005 cannot be a fraction
