### ISSUE TITLE
Autosuggest suggesting my login email ID in every input field

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#3772]
In Windows 10, Edge browser after saving my email id and password for login the edge autosuggest is proposing my email ID for every input field.

![2015-08-02 16_33_54-start](https://cloud.githubusercontent.com/assets/9136094/9026578/493d921a-3934-11e5-9f0f-76cd34f39d17.png)

**Comment by anandpdoshi** [comment]
Clearly a browser bug. Don't think we can do anything about it. 😞

**Comment by dottenbr** [comment]
We thought so too, but its basically unusable. Maybe there is some attribute you have to set. With a date drop down it gets unusable, check it out.

![2015-08-02 18_06_25-jump list for google chrome](https://cloud.githubusercontent.com/assets/9136094/9026920/546eb97c-3941-11e5-83ee-a96551a88083.png)

**Comment by anandpdoshi** [comment]
It is just an input field and we've attached the widgets with JavaScript.

**Comment by dottenbr** [comment]
I see that there seems like nothing can be done about it other than not using a untested buggy browser. I will close this for now, maybe revisit this later?
