### ISSUE TITLE
Quantity ignoring "Must be Whole Number", 3 decimals confusing for continental Europe

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#3773]
The quantity when editing an item row in a quotation ignores the Setting from unit of measure. For example for my UOM "Stk" which is "Pieces" we have set that it should not allow decimals. However the line allows decimals and will save a decimal.

![2015-08-02 17_18_42-stk - microsoft edge](https://cloud.githubusercontent.com/assets/9136094/9026742/53c8d5da-393b-11e5-86ca-ac7a49069fc2.png)
![2015-08-02 17_18_49-start](https://cloud.githubusercontent.com/assets/9136094/9026743/53e13a08-393b-11e5-973b-e04fb1b6281c.png)

Also for non-English it would be smart to by default use 2 digits not 3. For example 1,000 meaning "1 Piece" is actually "1000 pieces in Europe". The decimal separator in Europe is the comma and the thousand separator is a dot. So your default of 3 digits with a dot separator suggests that it is actually 1000 pieces. Continental European ontethousand fivehundread and fifty = 1.500,50. Imperial = 1,500.50

**Comment by yashodhank** [comment]
Not sure, have you looked at System Settings, as follows? which allows to setup precision and format. etc.

![image](https://cloud.githubusercontent.com/assets/1083792/9027519/f48c2cda-3975-11e5-8b36-ea43e463954f.png)

**Comment by dottenbr** [comment]
Amazing, thank you!
