### ISSUE TITLE
Different fonts in emailed PDF and web generated PDF

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#3774]
The font in the emailed PDF attachment looks very different (not as nice and clean cut) as the font when you click on the link in the email.

Emailed PDF attachment

![2015-08-02 18_18_45-jump list for google chrome](https://cloud.githubusercontent.com/assets/9136094/9026969/41427b70-3943-11e5-8b30-a967acf9aa4a.png)

PDF link
![2015-08-02 18_19_10-jump list for google chrome](https://cloud.githubusercontent.com/assets/9136094/9026970/469e3cd0-3943-11e5-9f8d-30196ead24af.png)

**Comment by cgpurbaugh** [comment]
Mine are identical, I would suggest checking your settings in settings>print.
This is how mine look:
![print settings](https://cloud.githubusercontent.com/assets/13136405/9037275/a6bc4f84-39b7-11e5-97dd-865929b3e56c.png)

**Comment by dottenbr** [comment]
It seems like the PDF attachment is Print Style "Classic" even though here it is set to "Modern" while the link generates a "Modern" style. Probably during the PDF generation you are missing to check for the Print Style and setting it correctly.

**Comment by dottenbr** [comment]
This was resolved by installing fonts on the webserver @anandpdoshi could you post the link to the font install here so people who encounter this in the future know how to fix it. Closed.
