### ISSUE TITLE
Over-supply of sub-contracted items

### ISSUE THREAD

**Issue by ArcticSilk** [frappe/erpnext#37770]
We sub-contract out a lot of our electronic manufacturing, often providing suppliers raw goods from our inventory to process, but electronic items in particular require more than the stated BoM quantity to facilitate setup and test runs etc.

Can the feature be updated so that I am able to supply greater quantities than just the stated BoM quantity to enable accurate stock levels. Currently i can only provide sub-contractors up to a maximum BoM quantity rather than excess.

**Comment by s-aga-r** [comment]
@ArcticSilk You can set the **Over Transfer Allowance (%)** in Buying Settings.

![image](https://github.com/frappe/erpnext/assets/63660334/0164de2f-8933-4c4e-b05e-ff4de0a8ef09)
