### ISSUE TITLE
Unknown column 'parent_employee' in 'where clause'

### ISSUE THREAD

**Issue by Antony-M1** [frappe/erpnext#37774]
### Information about bug

In the **Employee** Doctype I'm when to tree structure I tried to **Rebuild the Tree** Im getting this error

**Unknown column 'parent_employee' in 'where clause'**

here the all details about my setup

softsuave is a custom app its not only in 15 i seen in 13 & 14 please check

```
### App Versions
```
{
	"erpnext": "15.0.0",
	"frappe": "15.0.1",
	"hrms": "15.0.0",
	"payments": "0.0.1",
	"softsuave": "0.0.1"
}
```
### Route
```
Tree/Employee
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1682, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/utils/nestedset.py", line 196, in rebuild_tree
    ).run()
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/database.py", line 217, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'parent_employee' in 'where clause'")

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doctype": "Employee",
		"parent_field": "parent_employee"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.utils.nestedset.rebuild_tree",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "pymysql.err.OperationalError: (1054, \"Unknown column 'parent_employee' in 'where clause'\")",
	"exc_type": "OperationalError"
}
```
```

### Module

HR

### Version

"erpnext": "15.0.0",
"frappe": "15.0.1",
"hrms": "15.0.0",
"payments": "0.0.1",

### Installation method

docker

### Relevant log output / Stack trace / Full Error Message.

```shell
2023-10-30 11:52:37,618 ERROR frappe New Exception collected in error log
Site: ss15-2.localhost
Form Dict: {'doctype': 'Employee', 'parent_field': 'parent_employee', 'cmd': 'frappe.utils.nestedset.rebuild_tree'}
2023-10-31 05:17:38,840 ERROR frappe New Exception collected in error log
Site: ss15-2.localhost
Form Dict: {'doctype': 'Employee', 'parent_field': 'parent_employee', 'cmd': 'frappe.utils.nestedset.rebuild_tree'}
```

**Comment by Antony-M1** [comment]
Its a white list function overrided. but you have to use the **reports_to** instead of **parent_employee**

here the code
```
import frappe
from frappe import _
from frappe.query_builder.utils import DocType
from frappe.query_builder import Order
from frappe.utils.nestedset import rebuild_node


@frappe.whitelist()
def rebuild_tree(doctype, parent_field):
    """
    call rebuild_node for all root nodes
    """
    if parent_field == 'parent_employee':
        parent_field = 'reports_to'
    
    # if frappe.local.form_dict.parent_field == 'parent_employee':
    #     frappe.local.form_dict.parent_field = 'reports_to'

    # Check for perm if called from client-side
    if frappe.request and frappe.local.form_dict.cmd == "rebuild_tree":
        frappe.only_for("System Manager")

    meta = frappe.get_meta(doctype)
    if not meta.has_field("lft") or not meta.has_field("rgt"):
        frappe.throw(
            _("Rebuilding of tree is not supported for {}").format(frappe.bold(doctype)),
            title=_("Invalid Action"),
        )

    # get all roots
    right = 1
    table = DocType(doctype)
    column = getattr(table, parent_field)
    result = (
        frappe.qb.from_(table)
        .where((column == "") | (column.isnull()))
        .orderby(table.name, order=Order.asc)
        .select(table.name)
    ).run()

    frappe.db.auto_commit_on_many_writes = 1

    for r in result:
        right = rebuild_node(doctype, r[0], right, parent_field)

    frappe.db.auto_commit_on_many_writes = 0
```

I simply added this line in the top of the white list funtion
```
if parent_field == 'parent_employee':
        parent_field = 'reports_to'
```

**Comment by Antony-M1** [comment]
This the core path of that funtion
```
/workspace/development/frappe-bench/apps/frappe/frappe/utils/nestedset.py
```
this is the core function
```

@frappe.whitelist()
def rebuild_tree(doctype, parent_field):
	"""
	call rebuild_node for all root nodes
	"""

	# Check for perm if called from client-side
	if frappe.request and frappe.local.form_dict.cmd == "rebuild_tree":
		frappe.only_for("System Manager")

	meta = frappe.get_meta(doctype)
	if not meta.has_field("lft") or not meta.has_field("rgt"):
		frappe.throw(
			_("Rebuilding of tree is not supported for {}").format(frappe.bold(doctype)),
			title=_("Invalid Action"),
		)

	# get all roots
	right = 1
	table = DocType(doctype)
	column = getattr(table, parent_field)
	result = (
		frappe.qb.from_(table)
		.where((column == "") | (column.isnull()))
		.orderby(table.name, order=Order.asc)
		.select(table.name)
	).run()

	frappe.db.auto_commit_on_many_writes = 1

	for r in result:
		right = rebuild_node(doctype, r[0], right, parent_field)

	frappe.db.auto_commit_on_many_writes = 0

```

**Comment by nabinhait** [comment]
fixed via https://github.com/frappe/frappe/pull/24107
