### ISSUE TITLE
Return of Components option In Subcontracting Order on status of Material Transfer

### ISSUE THREAD

**Issue by precihole** [frappe/erpnext#37784]
There are instances where our supplier returns everything we sent them for a subcontract.

I want to create a return of component entry in the ss below, but it appears that we can only do it in the case of a partially received order.
<img width="960" alt="image" src="https://github.com/frappe/erpnext/assets/111174201/28110854-0e42-499a-87d9-258dffc93629">

<img width="960" alt="image" src="https://github.com/frappe/erpnext/assets/111174201/12e61865-d914-4ad1-9d67-8f1cd26388b3">

**Is your feature request related to a problem? Please describe.**
Supplier return all the material

**Describe the solution you'd like**
want return of component even if there is not material received

**Comment by s-aga-r** [comment]
Fixed: https://github.com/frappe/erpnext/pull/37686
