### ISSUE TITLE
Quality Check in Production Order / Stock Entry

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#378]
Add QC check in closing Stock Entry against production order.

via Mehul Mehta

**Comment by cgpurbaugh** [comment]
@rmehta What would be required?  I can try to make a PR for this.

**Comment by rmehta** [comment]
@cgpurbaugh great!

- [ ] Make a new column in **Stock Entry Detail** for `quality_inspection` (Link)
- [ ] In Item, add check `quality_inspection_required_for_manufacture`
- [ ] In Stock Entry of type "Manufacture", validate **Quality Inspection** is selected

**Comment by kickapoo** [comment]
@rmehta This a very old but interesting. I can make if a feature in ERPnext 7 that I miss.

**Comment by rmehta** [comment]
👍

**Comment by KanchanChauhan** [comment]
@kickapoo We already have Inspection Criteria section in Item. You can add "Inspection Required for Manufacture" here. 
<img width="441" alt="screen shot 2016-11-10 at 11 28 38 am" src="https://cloud.githubusercontent.com/assets/16913064/20166150/e865fb8e-a738-11e6-842b-25676c342241.png">

Look up Delivery Note how inspection is setup on it to have a  idea how to do it.

**Comment by umairsy** [comment]
Followup via https://github.com/frappe/erpnext/issues/2273
