### ISSUE TITLE
Purchase Invoice - Please set default Asset Received but not Billed in company 

### ISSUE THREAD

**Issue by zzecool** [frappe/erpnext#37831]
### Information about bug

When we try to submit a purchase invoice we are started to getting the following error :

![error_message](https://github.com/frappe/erpnext/assets/2816897/86edd94b-8824-4d49-8bc0-8bd3c2491b6d)

Strange thing is that the account is setup properly 

![stock settings](https://github.com/frappe/erpnext/assets/2816897/95f64b92-ee87-4f61-80df-c68059b563f6)

This must happned oin the last update.

Any help is appreciaed as we cant use the erp like that.

### Module

buying

### Version

Ecommerce Integrations: v1.19.0 (HEAD)

ERPNext: v14.45.1 (HEAD)

Frappe Framework: v14.53.1 (HEAD)

### Installation method

FrappeCloud

**Comment by OmelMedina** [comment]
@zzecool if you go under accounts when selecting your company. Is there a box at the end like this? 

![Screenshot from 2023-11-01 12-43-49](https://github.com/frappe/erpnext/assets/149500817/92b35ccc-8ac4-4584-9e8b-164258ab8d34)

**Comment by zzecool** [comment]
@Glitch-Trap-1 

![image](https://github.com/frappe/erpnext/assets/2816897/0b594dd2-c18a-46e7-89a4-8ac2c7ce601d)


Yes it was collapsed and i mised it before. What should i put there ? I never had to use this before.

**Comment by zzecool** [comment]
Funny fact if i press create a new account:

![image](https://github.com/frappe/erpnext/assets/2816897/7a233bb2-b898-4fbe-bcb4-d6c088165ad7)


Im getting this :

![image](https://github.com/frappe/erpnext/assets/2816897/ca7b5ddb-0f8c-4f2f-9b35-f270268f8902)

**Comment by OmelMedina** [comment]
@zzecool I would put an account that matches the account type. I'm assuming you have administrator privileges right? You need to be able to create a new account. Anyone with the Account Manager role should be able to do that much

**Comment by OmelMedina** [comment]
![Screenshot from 2023-11-01 12-59-05](https://github.com/frappe/erpnext/assets/149500817/426cbc2f-7d3d-4aec-926e-beb90b53ef77)

It would be as simple as going to chart of accounts. Click on add accounts and then account type. Choose Asset received but not billed as the type of account

**Comment by zzecool** [comment]
There was an update available i did it and now it let me create the account. No idea why it  bugged like that.

What should be the Parent account of this type of account ? 

And why is this acount is needed now out of nowhere ? We havent have to use it before. Also the Purchase invoice is products that are not fixed assests and just products from a manufacturer --> resale

**Comment by OmelMedina** [comment]
@zzecool The parent account type would be asset. It might not be directly linked to to purchase invoice. Not sure why it would be needed out of nowhere. It's safe to assume it won't affect anything else though. Just a weird requirement

**Comment by zzecool** [comment]
> @zzecool The parent account type would be asset. It might not be directly linked to to purchase invoice. Not sure why it would be needed out of nowhere. It's safe to assume it won't affect anything else though. Just a weird requirement

Maybe this is another bug and this account is only used when you buy "fixed assets"  ??

![image](https://github.com/frappe/erpnext/assets/2816897/072cc53b-7682-4064-a1c2-cfdccfc4822f)


??

**Comment by deepeshgarg007** [comment]
@zzecool This issue should be resolved now, closing this issue.

**Comment by zzecool** [comment]
> @zzecool This issue should be resolved now, closing this issue.

The real issue is why we get out of nowhere this kind of things after an update that makes the ERP unusable ?
