### ISSUE TITLE
Highlight/Bold Group in Account Report ( Trial Balance.BS..etc ) both in Display and Download    

### ISSUE THREAD

**Issue by Chourey30** [frappe/erpnext#37848]
### Information about bug

Highlight/Bold Group in Account Report ( Trial Balance.BS..etc ) both in Display and Download    

### Module

accounts

### Version

v14.20.0 (version-14)
v14.30.0 (version-14)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
Highlight/Bold Group in Account Report ( Trial Balance.BS..etc ) both in Display and Download    , So it will be easily identified and helpful.

Thank you in advance



Regards
Sumit Chourey
```

**Comment by Chourey30** [comment]
Currently we are facing issue that after download Trial Balance and General Entry report, we have to manually make Bold figures to identify groupings. 
Thank you in advance

**Comment by deepeshgarg007** [comment]
@Chourey30 There is already an option in these reports to export with indentation which helps you identify the parent groups. This sounds more like a feature request than a bug.
