### ISSUE TITLE
Discount GL Entry not happening in Sales / Purchase Invoice

### ISSUE THREAD

**Issue by rayenlabdouni** [frappe/erpnext#37878]
### Information about bug

in Purchase Invoice, when we add discount account on item row, and submitting the invoice, GL Entry its not happening,

when we checked the code, **make_discount_gl_entries()** function is there in Accounting Controller but the entry its not happening,
we were able to modify the code and fix it On Accounts side, but in Stock Side also the valuation should be proper,

![image](https://github.com/frappe/erpnext/assets/62704271/d7364692-6d90-406e-865c-56840eca1b2c)

### Module

buying

### Version

ERPNext Version 13.52.1

### Installation method

None

**Comment by deepeshgarg007** [comment]
@rayenlabdouni You have to first enable discount accounting from Selling settings and then only you can do discount accounting. It is not available at the buying cycle as it is not needed there with perpetual inventory and has been removed.

Hope this resolves your doubt
