### ISSUE TITLE
Query report creation for Cloud customers

### ISSUE THREAD

**Issue by monojoker** [frappe/erpnext#3788]
Hi All,

I tried to create a Query Report but received the following message on save:

![image](https://cloud.githubusercontent.com/assets/10917366/9051223/f5ff2948-3a9a-11e5-836c-876f2ede3720.png)

Could you create an administrator account in our instance for creating query reports or is it possible to have a role for "report manager" or similar to do this?

It would be very handy to create SQL reports so I can get more control over the data output to our other systems.

Cheers
Liam.

**Comment by umairsy** [comment]
Hello Liam,

Hosted users doesn't have privilege to create Script and Query reports. Please check following link to learn more on this.

https://kb.erpnext.com/kb/report/making-custom-reports-in-erpnext

For the hosted accounts, only we (at ERPNext) have access to administrator login.

**Comment by rmehta** [comment]
@monojoker just send it across to us and we will add it to the product.

**Comment by monojoker** [comment]
Thanks @rmehta I think with other customers who interface (export) invoices from ERPNext to Xero it would be of benefit as the Xero import format is a set format - not just specific to us. It's also just Sales Invoice and Sales Invoice Item fields, nothing to be derived or calculated. Will email a spec to you guys. Cheers.
