### ISSUE TITLE
Timelog UI improvement

### ISSUE THREAD

**Issue by acumensec** [frappe/erpnext#3789]
Hello, the current timelog form is not very intuitive and UI does not map to timesheet apps currently available. Would it be possible to create a different UI/form that looks something like this?

![timesheet_mockup](https://cloud.githubusercontent.com/assets/7266036/9052119/c1dab52e-3a31-11e5-9ac7-760ea791e4a6.png)

This is a "timesheet" that each user will see and where they can record their time on a per project basis.

**Comment by revant** [comment]
`Time Log`s are not used anymore, ERPNext now uses `Timesheet`
