### ISSUE TITLE
Unable to cancel documents tied to new Unreconcile * doctypes

### ISSUE THREAD

**Issue by dj12djdjs** [frappe/erpnext#37900]
### Information about bug

Introduced via: https://github.com/frappe/erpnext/pull/36879

![image](https://github.com/frappe/erpnext/assets/29856401/4d5f6555-e5b3-416e-b62e-fe525cfd5286)

### Module

accounts

### Version

ERPNext: v15.0.0 (version-15)

Frappe Framework: v15.0.2 (version-15)

Payments: v0.0.1 (version-15)

### Installation method

manual install

**Comment by rtdany10** [comment]
@ruthra-kumar

**Comment by rtdany10** [comment]
@ruthra-kumar is it safe to give the required perm to cancel and delete from Role Permission Manager?

**Comment by ruthra-kumar** [comment]
> @ruthra-kumar is it safe to give the required perm to cancel and delete from Role Permission Manager?

No need to add permissions, https://github.com/frappe/erpnext/pull/38570 should fix it.

**Comment by rtdany10** [comment]
This happens on Journal Entry also @ruthra-kumar 
Probably sales too

Ref: https://github.com/frappe/erpnext/issues/38492

**Comment by ruthra-kumar** [comment]
Journal Entry has been addressed. Sales Invoice already has the Unreoncile payment doctype in the ingore doctypes flag.
