### ISSUE TITLE
Option to hide disabled account in COA

### ISSUE THREAD

**Issue by DipenFrappe** [frappe/erpnext#37931]
Like while seeing the item master list view we have the option to filter active items the same way while seeing the COA tree view user do not want to see a disabled account but that is not possible currently so need the option to hide the disabled account.

For example, in the below screenshot Petty Cash account is disabled but the user has no option to hide it while seeing COA.

![image](https://github.com/frappe/erpnext/assets/123350348/d2a21406-b1a8-49fa-a922-da1186bdf994)

**Comment by deepeshgarg007** [comment]
The item view you are talking about is a list view, none of the tree views has an option to filter disabled records if we are building this should ideally be done at the framework level and not just for Accounts doctype (COA)

**Comment by DipenFrappe** [comment]
I just gave the example of Item master for a better understanding and if it is a framework feature request then the respective team can give a thought and if it is not possible framework level then can it be implemented for COA that you can think of as the use case is more common for COA.

**Comment by bosue** [comment]
> The item view you are talking about is a list view, none of the tree views has an option to filter disabled records if we are building this should ideally be done at the framework level and not just for Accounts doctype (COA)

True, the feature should be present framework-wide for all tree views.
However, CoA accounts should only be hidden if disabled _and_ empty.

**Comment by GursheenK** [comment]
Completed via https://github.com/frappe/erpnext/pull/38551
