### ISSUE TITLE
"DocType GSTR-1 not found" - Error while downloading JSON from GSTR-1 Report

### ISSUE THREAD

**Issue by innomalous** [frappe/erpnext#37955]
### Information about bug

Getting an error "DocType GSTR-1 not found" when trying to download JSON file from GSTR-1 Report

![image](https://github.com/frappe/erpnext/assets/42608563/3da4a4d5-6531-4290-b0aa-823bc5b36c3b)

### Module

accounts

### Version

Frappe v14.54.0
ERPNext v14.46.2
India Compliance v14.19.1

### Installation method

FrappeCloud

**Comment by ghost** [comment]
I am facing the same issue!

**Comment by deepeshgarg007** [comment]
@innomalous Please raise this issue at https://github.com/resilient-tech/india-compliance/issues
