### ISSUE TITLE
Multiple email ID in LEAD or Contact.

### ISSUE THREAD

**Issue by adityaduggal** [frappe/erpnext#3796]
Hi,

With recent update there is a validation which does not allow for multiple email ID in LEAD or Contact form.

My recommendation is that multiple email ID should be allowed with the following format: `email id 1` , `email id 2` etc..

This would help us enter multiple email IDs in contacts and LEADS and the system can also check the validity of the email id.

**Comment by rmehta** [comment]
Custom Field?

(Ideally there should be one email id!)
