### ISSUE TITLE
Project module not showing

### ISSUE THREAD

**Issue by cordovacloud** [frappe/erpnext#37974]
### Information about bug

Projects module is not showing in the sidebar
while using it displayed some error and refreshed and now the module is not available

### Module

projects

### Version

Frappe Framework: v14.53.2 (version-14)
Frappe HR: v16.0.0-dev (develop)
ERPNext: v14.45.4 (version-14)

### Installation method

FrappeCloud

**Comment by s-aga-r** [comment]
@cordovacloud The `Projects` module is available in the sidebar, seems like you have removed it manually.

https://github.com/frappe/erpnext/assets/63660334/34ad7bef-170a-4334-b956-4fab7ed59704

>> while using it displayed some error
Please share the screenshots and browser console logs.
