### ISSUE TITLE
Enhancement: Make Full Use of Supplier Part Numbers

### ISSUE THREAD

**Issue by citizen-khan** [frappe/erpnext#3798]
At present the Supplier Part Number plays a bit of a supporting role only ever referred to however it's real power can found when it is actually used directly.

For myself there are two scenarios where the Supplier Part Number would extremely useful are:

1) Supplier Price Lists - because these are supplied from information from the Supplier then the stock code you get is their stock code / part number therefore when entering these it would much easier to manage the Supplier Price list by searching for the Supplier Part Number rather than by our own stock number.

2) Purchase Invoices - when creating Purchase Invoices you have a Supplier's Invoice which has all the products supplied but with their Supplier Part Numbers therefore it would be much quicker to search for the Supplier Stock Number than having to try and translate it to our stock code. The infos there already.

The info is already there so let's make better use of it

**Comment by Arundhatii** [comment]
Closing the issue for now as no further discussion or similar requirement is raised. Please feel free to reopen if it is still relevant.
