### ISSUE TITLE
Negative Stock Balance

### ISSUE THREAD

**Issue by thida-bcn** [frappe/erpnext#38014]
### Information about bug

Stock Setting  (Allow Negative Stock was checked)
![image](https://github.com/frappe/erpnext/assets/62122640/7ad5581a-5985-4d27-a9d6-41ffd0df3ef3)
Item (Allow Negative Stock was unchecked)
![image](https://github.com/frappe/erpnext/assets/62122640/e003adcd-fe46-42b6-b4cf-470fb09b5b59)

Expected Result:
system should not allow user to use negative stock for that item

Now ERPNext Accepted Negative Qty for "Allow Negative Stock uncheck Items)
![image](https://github.com/frappe/erpnext/assets/62122640/cfd57a70-a064-4db2-9568-7d5a2aece74d)

### Module

stock

### Version

![image](https://github.com/frappe/erpnext/assets/62122640/8b91ba57-e34f-47e7-af1d-8beaffb217a7)

### Installation method

None

**Comment by dj12djdjs** [comment]
Hello @thida-bcn

The "Allow Negative Stock" in Stock Settings allows for negative stock globally, regardless of an items allow negative stock state.

If you want "Allow Negative Stock" to be item specific, you should uncheck "Allow Negative Stock" in Stock Settings, and selectively check "Allow Negative Stock" for the item's that are allowed to reach negative.

Incase majority of your items are allowed to be negative, you can set this to be checked by default via customize form, then uncheck the box for those item's that aren't allowed to be negative.

https://docs.erpnext.com/docs/user/manual/en/stock-settings#8-allow-negative-stock
