### ISSUE TITLE
Problem with erpnext.accounts.doctype.process_subscription.process_subscription.create_subscription_process

### ISSUE THREAD

**Issue by yakotdev** [frappe/erpnext#38039]
### Information about bug

After the latest update, the background workers are not working well in processing subscriptions
This is the line it gives:
Traceback (most recent call last):
   File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 124, in execute
     frappe.get_attr(self.method)()
TypeError: create_subscription_process() missing 2 required positional arguments: 'subscription' and 'posting_date'

### Module

accounts

### Version

Frappe last update
Erpnext last update

### Installation method

None

**Comment by mimiza** [comment]
My system has the same error after the latest update
