### ISSUE TITLE
POS Time error

### ISSUE THREAD

**Issue by ernestoruiz89** [frappe/erpnext#38032]
### Information about bug

create POS Invoice
Checkout

![image](https://github.com/frappe/erpnext/assets/1592496/d7f75abb-b9f4-4626-8a04-5f9d0987b77e)

### Module

accounts, selling

### Version

Frappe: 15
ERPNext: 15

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
Kindly upgrade your version 15 because everything is working fine. No problems were encountered in the latest version 15.

Please check it.


https://github.com/frappe/erpnext/assets/141945075/390c3e2f-68e6-4f56-8d8e-ea079c653615
