### ISSUE TITLE
COGs is booked for Purchase invoices created using moving average method. 

### ISSUE THREAD

**Issue by maveezmh** [frappe/erpnext#38042]
### Information about bug

As in system settings the stock movement is set as moving average. whenever we are creating invoice the systm is booking some random value to COGs. we are unable to identify how the calculations are happening and how its impacting the expense ledger.

![image](https://github.com/frappe/erpnext/assets/112148467/a4f55bb7-81b4-406e-9c6a-6958c98f5ce5)

in above image the purchase value of each item is mentioned and total becomes **79.79** plus **3.99** as tax so total of **83.78 ~ rounded to 84 AED**

the accounting entries should be as follows

(84.00)  in Accounts Payable - DPRCL                   
79.70 in Materials and ingredients - DPRCL	
03.99 in VAT 5% - DPRCL	                                
 00.22 in Write Off - DPRCL	                               

but following entries are happening and is messing up the accounts. 

![image](https://github.com/frappe/erpnext/assets/112148467/03f80803-98da-4a8c-b9cd-157d850cefb1)

### Module

accounts, stock, buying, selling

### Version

ERPNext: v14.46.4 (HEAD)
Frappe Framework: v14.54.0 (HEAD)
Frappe HR: v14.16.0 (HEAD)

### Installation method

FrappeCloud

**Comment by maveezmh** [comment]
we have set item group revenue and expense ledger to specific accounts and default cost of goods sold account is COGs

Also all the items are stock items

**Comment by maveezmh** [comment]
@deepeshgarg007

**Comment by dj12djdjs** [comment]
Hi @maveezmh,

This could be the reason COGS is getting used in your accounting ledger: https://github.com/frappe/erpnext/blob/7b14e9d5f673ff5ab28d29c1c64d0087a2db46cd/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py#L979-L1019

If have have Update Stock checked, the system is booking the stock value difference in the COGs account.

**Comment by maveezmh** [comment]
> Hi @maveezmh,
> 
> This could be the reason COGS is getting used in your accounting ledger:
> 
> https://github.com/frappe/erpnext/blob/7b14e9d5f673ff5ab28d29c1c64d0087a2db46cd/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py#L979-L1019
> 
> If have have Update Stock checked, the system is booking the stock value difference in the COGs account.

i went through the process.. like you said... it is happening due to negative stock value in inventory.. and the differences are getting booked against cogs
