### ISSUE TITLE
Incorrect Valuation Rate in Stock Ledger and Repost Item Valuation not working for back dated cancelation Subcontracting Receipt" Batch Item"

### ISSUE THREAD

**Issue by hassan-youssef** [frappe/erpnext#38051]
### Information about bug

Subcontracting Receipt
The rating rate is wrong and I don't know why, and gl has a large number
![Screenshot from 2023-11-12 08-56-30](https://github.com/frappe/erpnext/assets/60713522/04ee6ddc-56e3-444d-993e-0821c6fb4aa6)

![Screenshot from 2023-11-12 09-04-48](https://github.com/frappe/erpnext/assets/60713522/3e33f997-1ac3-4ee8-93ad-7b4f54eb5509)

### Module

manufacturing, other

### Version

ERPNext: v15.0.0 (version-15)

Frappe Framework: v15.1.0 (version-15)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Incorrect Valuation Rate
```

**Comment by s-aga-r** [comment]
Duplicate: https://github.com/frappe/erpnext/issues/38062
