### ISSUE TITLE
Debit Credit not equal for Purchase Receipt

### ISSUE THREAD

**Issue by keelouwah** [frappe/erpnext#38056]
### Information about bug

Hi, 

I tried to generate a purchase receipt from a purchase order that was already been received. Upon submission of the purchase receipt, it gave me an error notification that the debit and credit is not equal for purchase receipt  #MAT-PRE-2023-00025 Difference is -28219.13. 

The difference was between the total SAR value of 38,480.63 SAR and total USD value of 10,261.50 USD.

It seems like ERPNext couldn't recognize that both value are just the same. Please see screenshot below
<img width="1244" alt="Screenshot 2023-11-09 at 11 30 20 AM" src="https://github.com/frappe/erpnext/assets/150589883/91941356-531c-45f0-b38d-5106d4802a3f">

### Module

stock

### Version

ERPNext: v14.45.0

Frappe Framework: v14.53.1

### Installation method

None

**Comment by ur-uw** [comment]
I have the same issue, hope this will be fixed as soon as possible as our work is temporary depending on it.

It is subtracting the amount in foreign currency from the default currency amount 10261.50 USD -38480.63 SAR  = -28219.13

**Comment by nabinhait** [comment]
Can't replicate the issue.

Closing the issue for now, if the issue still exists, please reopen with more information like versions, steps and data etc.
