### ISSUE TITLE
Subcontract Receipt  with batch Valuation Rate Error

### ISSUE THREAD

**Issue by Kamereldawla** [frappe/erpnext#38062]
### Information about bug

![Subcontract Receipt](https://github.com/frappe/erpnext/assets/50329342/6827932a-f542-400a-a516-ffc703cd6a69)
![Stock Ledger Recipt](https://github.com/frappe/erpnext/assets/50329342/43e461b3-f2d3-4c0d-a061-d7cddc821252)

### Module

stock, buying, manufacturing

### Version

ERPNext: v15.0.0 (version-15)

Frappe Framework: v15.0.1 (version-15)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Not calculating Valuation Rate correctly in Batch with Item (Subcontracting Cycle)
```

**Comment by hassan-youssef** [comment]
Please solve

**Comment by kelechi2020** [comment]
HI, I would take a shot at this.

**Comment by hassan-youssef** [comment]
@kelechi2020 Simply try cycle Subcontracting but item "Has Batch No" Raw material and Finished products ,
When you reach the final stage "Subcontracting Receipt" Check Valuation Rate Finished products . 
Please solve it

**Comment by rohitwaghchaure** [comment]
<img width="983" alt="image" src="https://github.com/frappe/erpnext/assets/8780500/ec45856b-fe27-4f4e-bfcc-1b44cddfb078">

@kelechi2020 can you share the screenshot of the "Raw Materials Cost Per Qty"? this field is available in the line items table.

**Comment by s-aga-r** [comment]
@Kamereldawa we are unable to replicate the issue, please provide us with the exact steps.

**Comment by hassan-youssef** [comment]
@rohitwaghchaure  In this example, I mentioned in the table that the cost of the raw material is 100 and the cost of the service is 100. The finished product is supposed to be 200 excellent, but a result other than this is given with the items.
"Has Batch No"

**Comment by hassan-youssef** [comment]
![Screenshot from 2023-11-17 06-30-51](https://github.com/frappe/erpnext/assets/60713522/bbc8b103-ac2d-4e02-a05f-69673fcf6b06)
![Screenshot from 2023-11-17 06-28-20](https://github.com/frappe/erpnext/assets/60713522/8f566db4-1562-4d80-b772-70e808d92000)
Look at the cost of the raw material and the cost of the service. The Valuation Rate of the finished product is supposed to be 3.52
I updated to ERPNext: v15.1.0, but the problem persists. Please solve it

**Comment by s-aga-r** [comment]
@hassan-youssef Please create a Repost Item Valuation entry for this Subcontracting Receipt. 

Also, the Service Cost Per Qty should be correct. The actual issue was with the Valuation Rate not with the Service Cost. Please share screenshots of the Subcontracting Receipt Item and Supplied Item Tables.

**Comment by s-aga-r** [comment]
@hassan-youssef 

> Please share screenshots of the Subcontracting Receipt Item and Supplied Item Tables.

Got [this](https://user-images.githubusercontent.com/60713522/282283330-04ee6ddc-56e3-444d-993e-0821c6fb4aa6.png)

The Service Cost is not correctly set. Please share screenshots of the linked Purchase Order.

**Comment by hassan-youssef** [comment]
@s-aga-r  
http://75.119.156.55:8090/app/purchase-order/PUR-ORD-2023-00014
user :administrator
pass:admin@231

**Comment by hassan-youssef** [comment]
![Screenshot from 2023-11-18 21-17-31](https://github.com/frappe/erpnext/assets/60713522/5894a057-912d-4e7c-b044-d588dfd575cd)
