### ISSUE TITLE
[V15] Sales / Purchase Invoice Reposting didn't work

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#38075]
### Information about bug

![inv-repost](https://github.com/frappe/erpnext/assets/910238/a35cb178-b03a-4e75-9609-f881b955339d)

### Module

accounts

### Version

FF - V15
ERnext - v15

### Installation method

FrappeCloud

**Comment by umairsy** [comment]
Similar thing didn't work in Purchase invoice also. Infact, dimensions were not editable at all. Only expense account was changed.

<img width="1227" alt="Screenshot 2023-11-13 at 4 42 15 PM" src="https://github.com/frappe/erpnext/assets/910238/c0327b71-1e1e-4b9b-acdf-226752fd7f03">

**Comment by GursheenK** [comment]
Mostly need to accommodate changes from https://github.com/frappe/erpnext/commit/5a068410c6ff4bc4ac100098c712d09bb70854df 
These types were hard-coded before.
