### ISSUE TITLE
Selling Module Workflow changes required

### ISSUE THREAD

**Issue by bharatepillars** [frappe/erpnext#3810]
ERPNext Default Workflow is : Lead -> Quotation -> Sales Order
I would like to have different workflow for the same and requirement follows as:
Lead -> Supplier Quotation -> Customer Quotation -> Sale Order

Here, supplier quotation should get created first, then only one should proceed with Sales Order. Kindly provide your feedback on this and let us know how much time required to provide this functionality and your cost too.

We are ready for Paid Development also.

**Comment by rmehta** [comment]
Can you explain clearly.

We can have a button in **Lead** (should be **Opportunity**) to make **Supplier Quotation** and copy the Items and then a button in **Suppiler Quotation** to make **Quotation**?

It should be around 2 hours ($200)

**Comment by bharatepillars** [comment]
Can we have a skype call, as i few other requirements to discuss ?

**Comment by dottenbr** [comment]
This is very specific and should be configurable so it does not become part of the standard workflow.

**Comment by cgpurbaugh** [comment]
Can this be closed?
