### ISSUE TITLE
Stock Summary: 'float' object has no attribute 'get',  Possible source of error: erpnext (app)

### ISSUE THREAD

**Issue by ReachyBayern** [frappe/erpnext#38115]
### Information about bug

after executing the stock summary report...
![grafik](https://github.com/frappe/erpnext/assets/59421037/8f25f38f-a227-46eb-a066-3ff50b09d048)
an error message occurs:
![grafik](https://github.com/frappe/erpnext/assets/59421037/c6360655-c1d2-455b-bbd5-df2e4cbb10f9)

But the same output of the stock levels of an item is shown correctly in the item dashboard:
![grafik](https://github.com/frappe/erpnext/assets/59421037/d1acf689-e22b-4a76-a310-169f3f0e6a9a)

So it is no general bug!

The problem is here: /opt/bench/erpnext/apps/erpnext/erpnext/stock/dashboard/item_dashboard.py
![grafik](https://github.com/frappe/erpnext/assets/59421037/3e70ed90-5e8b-4959-a62f-6dd9ec8d5b63)

by replacing the code to the following, it would work fine:
![grafik](https://github.com/frappe/erpnext/assets/59421037/fcc65ea0-f243-40a0-8555-8f60b08dff89)

May be there is another solution. For me it is okay for the moment with this modification. But please correct this in the next version of erpnext V14. Thanks in advance

### Module

stock

### Version

Frappe Version: 15.x.x-develop
ErpNext Version: 14.x.x-develop
installed on 13th September 2023

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
15:43:42 web.1         | 172.16.xx.x - - [09/Nov/2023 15:43:42] "GET /api/method/frappe.client.get_js?items=["/assets/erpnext/dist/js/item-dashboard.bundle.BSQIEHGC.js"]&_=1699543963011 HTTP/1.0" 200 -
15:43:43 web.1         | Traceback (most recent call last):
15:43:43 web.1         |   File "apps/frappe/frappe/app.py", line 84, in application
15:43:43 web.1         |     response = frappe.api.handle()
15:43:43 web.1         |   File "apps/frappe/frappe/api.py", line 53, in handle
15:43:43 web.1         |     return _RESTAPIHandler(call, doctype, name).get_response()
15:43:43 web.1         |   File "apps/frappe/frappe/api.py", line 69, in get_response
15:43:43 web.1         |     return self.handle_method()
15:43:43 web.1         |   File "apps/frappe/frappe/api.py", line 79, in handle_method
15:43:43 web.1         |     return frappe.handler.handle()
15:43:43 web.1         |   File "apps/frappe/frappe/handler.py", line 48, in handle
15:43:43 web.1         |     data = execute_cmd(cmd)
15:43:43 web.1         |   File "apps/frappe/frappe/handler.py", line 86, in execute_cmd
15:43:43 web.1         |     return frappe.call(method, **frappe.form_dict)
15:43:43 web.1         |   File "apps/frappe/frappe/__init__.py", line 1670, in call
15:43:43 web.1         |     return fn(*args, **newargs)
15:43:43 web.1         |   File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
15:43:43 web.1         |     return func(*args, **kwargs)
15:43:43 web.1         |   File "apps/erpnext/erpnext/stock/dashboard/item_dashboard.py", line 78, in get_data
15:43:43 web.1         |     "reserved_stock": sre_reserved_stock_details.get((item.item_code, item.warehouse), 0),
15:43:43 web.1         | AttributeError: 'float' object has no attribute 'get'
15:43:43 web.1         | 
15:43:43 web.1         | 172.16.xx.x - - [09/Nov/2023 15:43:43] "POST /api/method/erpnext.stock.dashboard.item_dashboard.get_data HTTP/1.0" 500 -
```

**Comment by s-aga-r** [comment]
@ReachyBayern This issue is already fixed in https://github.com/frappe/erpnext/commit/b6437e387ff5d50779c1804e4048c5c37e89fd04. Make sure you are in the latest version of ERPNext v15 or develop.

![image](https://github.com/frappe/erpnext/assets/63660334/37b24499-436f-452f-8140-d7cbd1aced27)
