### ISSUE TITLE
[bug] stock_ledger_entry.py throw msg not tranlatable

### ISSUE THREAD

**Issue by szufisher** [frappe/erpnext#38116]
### Information about bug

these below throw messages not translatable, the message not wrapped in translate function _()

		if not item_detail:
			self.throw_error_message(f"Item {self.item_code} not found")

		if item_detail.has_variants:
			self.throw_error_message(
				f"Stock cannot exist for Item {self.item_code} since has variants",
				ItemTemplateCannotHaveStock,
			)

		if item_detail.is_stock_item != 1:
			self.throw_error_message("Item {0} must be a stock Item").format(self.item_code)

		if item_detail.has_serial_no or item_detail.has_batch_no:
			if not self.serial_and_batch_bundle:
				self.throw_error_message(f"Serial No / Batch No are mandatory for Item {self.item_code}")

		if self.serial_and_batch_bundle and not (item_detail.has_serial_no or item_detail.has_batch_no):
			self.throw_error_message(f"Serial No and Batch No are not allowed for Item {self.item_code}")

### Module

stock

### Version

ERPNext 15+

### Installation method

None

**Comment by nabinhait** [comment]
Those messages are getting translated inside the function `throw_error_message`.
