### ISSUE TITLE
Add example Naming Series based on Year, Month

### ISSUE THREAD

**Issue by anandpdoshi** [frappe/erpnext#3813]
- [ ] Move Naming Series manager to Frappe
- [ ] Add example for Year Month based naming

**Comment by sbkolate** [comment]
@anandpdoshi  
Today I have same suggestion when I am working on YYMM naming series, so I have searched for pull request.

1) We can set YYMM format, but lots of people don't know about this feature.
Today I have set this naming series.
 SBK-SINV.-.YY..MM.-.#####

If we add example on naming series form and kb, then it will helpful for developer and user.
cc @nabinhait @rmehta

**Comment by mhbu50** [comment]
+1
