### ISSUE TITLE
Need PO number column in Reports

### ISSUE THREAD

**Issue by Spanraj** [frappe/erpnext#3814]
During  Reconciliation its will be more useful to cross check with other accounting report.
So we request you to add the column of PO number.

Please do the need full

**Comment by Spanraj** [comment]
Dear Sir,

we Requested for a PO number in Reports, please let me know the status.

**Comment by Spanraj** [comment]
Dear Sir,

we Requested for a PO number in Reports, please advise for the further progress.
ASAP.

**Comment by kennethsequeira** [comment]
Closing the issue. Since v11, one can add additional columns/fields within the standard reports available in the system.

https://github.com/frappe/frappe/pull/7225

Also, the issue does not specify the accounting reports where the column is needed.
