### ISSUE TITLE
Workflow state sent too many emails

### ISSUE THREAD

**Issue by ajiragroup** [frappe/erpnext#38187]
### Information about bug

I had a few payment entries filled out a few months ago. Last month I set a new workflow method for payment entry. Until then, I was using the default method (no workflow was set).

Today, I reconciled the old payment entries with Sales Invoices. A few minutes later I received tons of email from workflow for those old payment entries that were reconciled.

Here's the look into email:

![image](https://github.com/frappe/erpnext/assets/108009061/2f5e9dc4-4dea-4aa4-900e-aa7b8189ecd3)

I believe this should not have happened.

### Module

accounts

### Version

Frappe 15.1.0
Erpnext 15.0.0

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
Disable the "Send Email Alert" in the workflow.

Kindly upgrade to version 14 or 15, then refresh and check again because lots of bugs fixed in the new version.

Everything is working fine. No problems were encountered in the latest versions 14 and 15.

**Comment by ajiragroup** [comment]
Which app are you suggesting to upgrade because we are using erpnext v 15
This error occured with:
Version

Frappe 15.1.0
Erpnext 15.0.0

Disabling send email alert would not be a great ideas as we need email alerts for transactions. 
The problem we faced was: when reconciling old payment entries with sales invoice, this reconcialiaton act triggered email alerts which should not have happened ?

**Comment by Nihantra-Patel** [comment]
If you disable the workflow once and disable Send Email Alert then the emails stop coming. I tried it, I don't get any issue. If you have mentioned any workflow related in the notification then disable it also. And if you have to keep the workflow enabled then you have to set Disable Send Email Alert only then the email will stop. Alternatively check if you have done custom development. Else we tried everything from our end everything works properly.

**Comment by ajiragroup** [comment]
ok thank you !  We will check in depth again.
