### ISSUE TITLE
SO Delivery Date automatically select current date

### ISSUE THREAD

**Issue by habali08** [frappe/erpnext#38195]
### Information about bug

Hi, 
I have noticed the following 
if you create a sales order from a quote you can't change the delivery date, even if you do when you save the SO it changes the date to current date; this is not the case if you create a standalone SO.

regards,  

### Module

selling

### Version

ERPNext: v14.48.1 (version-14)

Frappe Framework: v14.55.0 (version-14)

Frappe HR: v14.17.0 (version-14)

### Installation method

manual install

**Comment by s-aga-r** [comment]
@habali08 The SO Delivery Date gets set based on the Items Delivery Date. Which is common among all the other DocTypes example Purchase Order (Required By).

- Sales Order
   
  https://github.com/frappe/erpnext/assets/63660334/062ef260-c5a9-4717-963c-657f40a87ace

- Purchase Order

  https://github.com/frappe/erpnext/assets/63660334/26a3ad5e-a4eb-42cf-be7c-b24d5d67fd1e
