### ISSUE TITLE
Custom Naming Series for LCV

### ISSUE THREAD

**Issue by rasika2502** [frappe/erpnext#3820]
As of now, it is not possible to customize the naming series for Landed Cost Voucher.
I created some LCVs and deleted, so I want to reset the series at 1, but there is no option to do so.

**Comment by bhupennewalkar1337** [comment]
You can reset the naming series current number from Setup -> Naming Series.

**Comment by bhupennewalkar1337** [comment]
You can also add multiple series from there.
