### ISSUE TITLE
Need branch filter or accounting dimension filters in Payment entry or Payment reconciliation

### ISSUE THREAD

**Issue by smbcatalyst** [frappe/erpnext#38227]
When we want to do reconciliation of invoices against payment with restricted access i.e. user permissions, we face issues in payment reconciliation or payment entry. At this moment, the system shows all invoices and payment entries irrespective of user permissions. Even without user permissions, it gets difficult to reconcile entries when no of transactions are higher side.
e.g. one of our client deals with retail customer in multiple states and users have restricted access to respective states. Currently, there is filter option for "Cost Center". Along with this, other accounting dimensions or branch filter will help to ease the process.

issue 1: When a user has Maharashtra branch access, the system shows all branch invoices in reconciliation and payment entry.

Issue 2: For admin user, it is difficult to identify specific branch invoices, entries and select those for reconciliation and payment entry. It is a time consuming and error prone process. 

Issue 3: Need Supplier invoice Number field in Invoices table and outstanding table in payment entry. Most of the time user does payment against supplier invoice number for accurate outstanding report.
Payment Reconciliation

<img width="1207" alt="image" src="https://github.com/frappe/erpnext/assets/113963271/ea59d43f-1e3f-45c4-b0e5-adfdce287783">

Payment Entry
<img width="1192" alt="image" src="https://github.com/frappe/erpnext/assets/113963271/e2ab8997-3227-4f98-beec-8ab354f2e63b">

**Comment by smbcatalyst** [comment]
We received a reply as Completed. Can you please share when will be available for user and in which release?

**Comment by ruthra-kumar** [comment]
This is merged in develop branch. It will most likely be released in the next 2 weeks on both v14 and v15.
