### ISSUE TITLE
Ability to change Sales Order Items after submission

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#3824]
- [ ] Change un-billed & un-delivered qty
- [ ] Remove Item (if un-billed & un-delivered)
- [ ] Add Item

Also in Purchase Order

**Comment by SonaliBudhrani** [comment]
+1

**Comment by aakvatech** [comment]
SO and PO are documents that are shared outside the organizations and with agreement between the two parties. Changing the qty/item list could create confusion. It would be better to close the SO/PO and recreate them afresh with new items.
