### ISSUE TITLE
'Project' Fields added on list is always NULL

### ISSUE THREAD

**Issue by fungmankit** [frappe/erpnext#38243]
### Information about bug

Hi all,

Projects are assigned to a PO and the filter could successfully identify those PO in Purchase Order screen. However when I tried to add 'Project' on a list under Buying - Purchase Order screen, it shows no value -

**Filter Applied**
<img width="769" alt="image" src="https://github.com/frappe/erpnext/assets/39433251/a17cec7e-01fd-4fa4-be4b-a35759545d03">

**Project field contains no value**
<img width="772" alt="image" src="https://github.com/frappe/erpnext/assets/39433251/56ec7cb9-8c5e-47f7-91dc-10e2bd6c984f">

Thanks.

### Module

buying

### Version

Frappe: v15.0.2 (HEAD)
ERPnext: v15.0.0 (HEAD)

### Installation method

FrappeCloud

**Comment by s-aga-r** [comment]
@fungmankit Project displayed correctly in my instance. Make sure you don't have any customization related to this.

![image](https://github.com/frappe/erpnext/assets/63660334/8296fb32-0fcb-4b56-850d-5c6e65f5c117)

**Comment by nabinhait** [comment]
Initially, it was not showing in my local instance as well after adding project column for the first time. But after clearing the browser's cache, it is showing. Closing the issue.
