### ISSUE TITLE
Feature Request: manufacturing auto Re-Order points

### ISSUE THREAD

**Issue by cgpurbaugh** [frappe/erpnext#3826]
Add the ability to make make automatic re-order points for manufactured items that would auto-generate a production order, in the same way that Purchase Orders can be auto-generated now.

**Comment by cgpurbaugh** [comment]
If possible, could I get a paid development quote?

**Comment by rmehta** [comment]
How about

- [ ] Add type of Material Request as "Manufacture"
- [ ] Add feature in Production Planning Tool to select planning from "Sales Order" or "Manufacture"

**Comment by cgpurbaugh** [comment]
This should work, I think.

**Comment by rmehta** [comment]
I am thinking $300 would be a fair amount. Drop in a mail at hello@erpnext.com and we will send you a PayPal invoice.

**Comment by arwema** [comment]
In a material request of type Manufacture you can add a product that cannot be manufactured, and making a production order will fail. Can a material request be set automatically depending on wether an item can or cannot be purchased/manufactured?
