### ISSUE TITLE
Picking/packing tool

### ISSUE THREAD

**Issue by cgpurbaugh** [frappe/erpnext#3828]
I've come to the realization that our packing department is going to struggle when we go live.  There's no easy way to see which orders can be packed.

Some programs solve this with a dedicated ‘picking ticket’ that is updated with the available stock in real time.  For example, in fishbowl inventory orders that can be picked/packed completely have a green dot, orders that can be partially picked/pack have an yellow dot, and orders that can’t be picked/packed at all have a red dot.  Here’s a link to their wiki which explains it better than I can: http://www.fishbowlinventory.com/wiki/Picking .  QuickBooks has an almost identical feature called the ‘Sales Order Fulfilment Worksheet’.  This is definitely worth investigating.  This would be a form similar to the ‘Links’ pop-up in a sales order, showing the status of production orders and inventory parts. It could be integrated with the ‘packing slip’ and could be made automatically every time a sales order is submitted.  All that would be required is a dot, similar to the DRAFT ones in the Pack slip list view,  that would give statuses similar to what I stated above, and when the packing slip is opened the ability to view the status of any production orders linked to the sales order(s) in question.

Please advise of Paid Dev. costs.

**Comment by yashodhank** [comment]
(just a thought) Complete Shipping Module with integration possibilities to connect it to popular logistic service providers such as Fedex, UPS, etc. will definitely bring wider attention and possibly success to ERPNext as it will solve the major problem for almost everyone.

I am learning frappe/ERPNext and I'm hoping to do it for community in upcoming months, if such thing is on least priority of great ERPNext team.

**Comment by robert1112** [comment]
Hi @cgpurbaugh 
Did you find a way to do this? Picking process to be achieved with ERPNext? I am struggled now. Thanks.
