### ISSUE TITLE
Product Bundle - with valuation rate cannot change the price is not correct anymore?

### ISSUE THREAD

**Issue by schmutzfuss42** [frappe/erpnext#38291]
### Information about bug

Using and creating Product Bundles works well, as long as don't use Product valuation rates ... by creating the system is fetching the correct value, after saving/submitting the rate will be changed.

At least for me it looks like there are some dependencies to Product Valuation Rates ... I tried a few different bundles and figured out that there are changes in the item prices in my sales order if the valuation rates are changed. So I deleted all valuation rates for the products in the bundle and after that I could choose the price by myself.

Could someone confirm, that this is a bug, or is there a reason for?

### Module

stock, selling

### Version

erpnext 15.2.0
frappe 15.1.0
hrms 15.3.0

### Installation method

manual install

**Comment by bander140414** [comment]
Go To : Selling Settings

 ---> Calculate Product Bundle Price based on Child Items' Rates

![image](https://github.com/frappe/erpnext/assets/133365426/c9c6bc9c-a36d-4bd7-8570-734a0f2fa1a3)

**Comment by s-aga-r** [comment]
@schmutzfuss42 

The rate of the Product Bundle will be the sum of all the child items if the `Calculate Product Bundle Price based on Child Items' Rates` is checked in Selling Settings else the Valuation Rate of the Product Bundle Item itself.

**Comment by schmutzfuss42** [comment]
Hi,
thx for updating me ... I didn't realized, as I choosed to use that option, that I'm not able anymore, to change the price manually ... even if it's helpful, to let the employees see what's ongoing with the base price ... without overrule option I cannot use it :-(

Anyway ..again thanks for your feedback :-)
