### ISSUE TITLE
Feature request: Any date field will recognize "t" as today

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#3830]
You could speed things up for the user if you enabled the keyword "t" for "today" in any field where there is a date so rather than selecting with the mouse or typing the user gets faster.

**Comment by dottenbr** [comment]
@rmehta are you considering this?

**Comment by dottenbr** [comment]
Watchlist sounds good, lets see what happens :-)

**Comment by rmehta** [comment]
fixed.

**Comment by dottenbr** [comment]
Thank you!

Sent from my mobile
