### ISSUE TITLE
Stock Entry _ If the item is not specified, “Automatically Create New Batch,” the system chooses the batch for me

### ISSUE THREAD

**Issue by hassan-youssef** [frappe/erpnext#38303]
### Information about bug

Automatic selection of batch number

### Module

stock

### Version

Erpnext v15. 3

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
batch Automatic
If it is selected, it will not be saved and will be selected automatically
```

**Comment by s-aga-r** [comment]
@hassan-youssef Please provide a screenshot, gif or browser console log.

**Comment by s-aga-r** [comment]
If you want not to pick the batches automatically, please disable `Auto Create Serial and Batch Bundle For Outward` in `Stock Settings`. The Item Master `Automatically Create New Batch` is used for inward transactions.

![image](https://github.com/frappe/erpnext/assets/63660334/335a107e-908f-4dd1-9157-90a74ff6c476)
