### ISSUE TITLE
Non Maintain Stock to Maintain Stock

### ISSUE THREAD

**Issue by Ponyooooo** [frappe/erpnext#38310]
### Information about bug

from this discussion: https://discuss.frappe.io/t/non-maintain-stock-to-maintain-stock/113642

What is the proper way to change an item from non maintaining stock to maintain stock and vice versa?

Is it really okay that tickmark on the maintain stock can edited?

### Module

stock

### Version

ERPNext: v13.54.6 (HEAD)
Frappe Framework: v13.58.15 (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
no error message
```

**Comment by bosue** [comment]
Good question whether any inconsistencies arise this way or the other way around, from stock to non-stock. Feel free to report whatever you may encounter.

**Comment by s-aga-r** [comment]
@Ponyooooo There is no way to change the `Maintain Stock` value if the item has transactions. The main difference between a stock and a non-stock item is that for stock items the system maintains the inward and outward qty warehouse-wise using Stock Ledger Entries. The only way you have is to disable the non-stock item and create a new one with `Maintain Stock` checked.

**Comment by bosue** [comment]
From stock to non-stock, both the checkbox is set read-only and there is a server-side error message.
From non-stock to stock, there is only the latter.

![IMG_2180](https://github.com/frappe/erpnext/assets/46800703/92120cb0-8810-4cc0-a90a-65f327d5b7f6)


For now, we should in both cases set the checkbox read-only.
In the longer term, we should probably allow changing status at least between fiscal years in the course of a listing or delisting inventory.
