### ISSUE TITLE
The serial number function is abnormal。

### ISSUE THREAD

**Issue by xingdianao** [frappe/erpnext#38328]
### Information about bug

When an item with a serial number is sold, the status of the serial number is displayed as invalid rather than sold, and the purchase and sales record information cannot be viewed by clicking on the serial number.

### Module

stock

### Version

ERPNext: v15.3
Frappe：v15.2

### Installation method

manual install

**Comment by s-aga-r** [comment]
@xingdianao Please share the screenshots for our reference.

**Comment by xingdianao** [comment]
When the purchase is placed in the inventory, the serial number status is activated：
![微信截图_20231128131645](https://github.com/frappe/erpnext/assets/137211649/61432950-0ce5-4b36-866c-d6b56ed27977)
After the sale, the serial number status is invalid：
![微信截图_20231128131742](https://github.com/frappe/erpnext/assets/137211649/44e8c204-8bfa-4676-bff8-5bdc74ff2325)
When the sale is out of the warehouse, there is no purchase and sale information when the serial number is clicked：
![微信截图_20231128131801](https://github.com/frappe/erpnext/assets/137211649/4e6c3124-10ad-4f2d-ae4e-dd8b4da14038)

**Comment by s-aga-r** [comment]
@xingdianao Could you share a screenshot of the Stock Ledger Entry (inward and outward) for the Serial No with `Inactive` status?

**Comment by xingdianao** [comment]
When I selected a serial number when opening the sales invoice, the serial number was not displayed in the form, and the Stock Ledger query serial number was blank.
![微信截图_20231128144056](https://github.com/frappe/erpnext/assets/137211649/56721d77-13e9-4e61-83d5-8233f2726c75)
![微信截图_20231128144152](https://github.com/frappe/erpnext/assets/137211649/fabdb3e7-efae-453c-bece-fb7684b13360)
![微信截图_20231128144641](https://github.com/frappe/erpnext/assets/137211649/e0062328-96cc-42bd-858c-ee5a2370704c)

**Comment by s-aga-r** [comment]
@xingdianao From v15, the Serial and Batch Nos are maintained in the Serial and Batch Bundle. Please use the `Serial / Batch Nos` button to see the Serial and Batch Nos. 

![image](https://github.com/frappe/erpnext/assets/63660334/7bb598de-ff81-43da-a8b5-56738ac30068)

**Comment by xingdianao** [comment]
@s-aga-r
Thank you for your answer, I would like to know how to find the sales information of the product through the serial number when a product with a serial number is sold.

**Comment by rohitwaghchaure** [comment]
@xingdianao We have fixed the status of the serial no as well added option to view ledgers (Sales / Purchase) from the serial no. For more details please check the below PR link
https://github.com/frappe/erpnext/pull/38391
