### ISSUE TITLE
Need Project name with project id in all reports

### ISSUE THREAD

**Issue by Sunilmehra21** [frappe/erpnext#38326]
Hello team

In various types of reports, the project ID is provided, but users are unable to identify the project name from the project number alone. Therefore, I request that the project name be included along with the project number in all reports.

Regards
Sunil

**Comment by s-aga-r** [comment]
@Sunilmehra21 You can use the `Add Column` feature to add the fields from linked DocTypes.

![image](https://github.com/frappe/erpnext/assets/63660334/3601ec56-7cfc-434b-8009-329440ceba91)
