### ISSUE TITLE
Feature request: Helpdesk Happieness Rating

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#3833]
When customers receive replies from a helpdesk system they typically have an emotional reaction to it, be it positive or negative. Why dont we use the moment and ask the customer how happy he was with the service he has provided? The feedback can be shown in the message within the ticket and the helpdesk worker can improve the quality next time or call the customer to get things right.

The user can click the smiley faces in the email:

<img width="286" alt="bildschirmfoto 2015-08-08 um 00 27 05" src="https://cloud.githubusercontent.com/assets/9136094/9143448/3b609258-3d64-11e5-83ca-8320a59d71bc.png">

this opens a link to the website with a token key:
<img width="529" alt="bildschirmfoto 2015-08-08 um 00 27 57" src="https://cloud.githubusercontent.com/assets/9136094/9143466/5960c2c8-3d64-11e5-9eb1-48ac309283b8.png">

Helpdesk users can see the rating within the ticket:
<img width="342" alt="bildschirmfoto 2015-08-08 um 00 29 40" src="https://cloud.githubusercontent.com/assets/9136094/9143559/d361cb94-3d64-11e5-87df-303824860306.png">

Also it would be great to have the customer happieness index a number that you can see when you go to the helpdesk:

<img width="997" alt="bildschirmfoto 2015-08-08 um 00 28 51" src="https://cloud.githubusercontent.com/assets/9136094/9143487/7e0ba278-3d64-11e5-90a0-ceec3cc7e13d.png">

I have attached images of the implementation within the help desk system Help Scout.

**Comment by dottenbr** [comment]
@rmehta  can you merge this issue with #3877? I don't want to close it myself because it has some screenshots that will be helpful.

**Comment by umairsy** [comment]
Customer Feedback feature has been added in ERPNext version 8 to fulfill this requirement.

https://youtu.be/XwcDQiCjcbw?t=8m4s

Please confirm if we can close this issue.
