### ISSUE TITLE
Ehancement: Purchase Receipt - Add Row Product Accepted Qty Should Change to Match Rec Qty

### ISSUE THREAD

**Issue by citizen-khan** [frappe/erpnext#3835]
If I'm creating a Purchase Receipt from scratch ie not from a Purchase Order when I add a row there is a default Rec Qty of 1 and if I change this to the correct number which I received then the Accepted Qty doesn't change so it stays at 1 and therefore this then means rejected adjusts to number received - 1. In most circumstances the received quantity is going to be accepted in full therefore the Accepted Qty should be changed to match this. If an adjustment is then required because some goods are not accepted then this can be manually overridden.

**Comment by kennethsequeira** [comment]
Working as expected. 

The received qty updates as per accepted qty and vice versa. 

Refer attached gif

![accepted_qty](https://user-images.githubusercontent.com/33246109/129772612-3917e818-cdde-47dc-9408-82b8117d2b61.gif)
