### ISSUE TITLE
Bug: Project Completion Status not Updating Correctly

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#3836]
Sample case: a project has one task, you set that to complete = the project is 100% complete. So far so good. But now you open that task again and say "pending review" or "working", unfortunately it doesn't update the project completion status to 0% but it keeps it at 100%.

<img width="1164" alt="bildschirmfoto 2015-08-08 um 23 44 34" src="https://cloud.githubusercontent.com/assets/9136094/9151654/b92ab6be-3e27-11e5-9ab1-66a381fc1463.png">

**Comment by KanchanChauhan** [comment]
It is fixed in v7. Could not replicate it now.
