### ISSUE TITLE
Sales Order Trends does not include Sales Orders with status 'Closed'

### ISSUE THREAD

**Issue by SvbZ3r0** [frappe/erpnext#38363]
### Information about bug

Suppose we have an order for 1000 units, and have delivered 998 units. We want to stop processing the order because the client says they don't want the other 2 units. The only way to do this is to mark the Sales Order as 'Closed'. If we don't close the order, it will kepp showing up as an option for planning, etc.
The problem is if we mark the order as closed, the Sales Order Trends graph on the Selling page does not take it into account despite the fact that it was a successfully executed order that counts towards the company's sales target.

### Module

selling

### Version

erpnext 15.3.0
frappe 15.2.0

### Installation method

manual install

**Comment by support-gennextsystems** [comment]
trends do not follow closed ones.?
