### ISSUE TITLE
Feature request: Enable commenting in Project Tasks

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#3838]
Users should be able to comment in Project Tasks, if you implement the @mention feature this would alert users to discussions going on in tasks even though they might not be assigned the task.

<img width="881" alt="bildschirmfoto 2015-08-08 um 23 50 46" src="https://cloud.githubusercontent.com/assets/9136094/9151673/a53df5c0-3e28-11e5-93de-d3707ebd5dac.png">

**Comment by strixaluco** [comment]
Implemented as of v 7.1
