### ISSUE TITLE
The total gross profit is wrong.

### ISSUE THREAD

**Issue by xingdianao** [frappe/erpnext#38409]
### Information about bug

The total gross profit is wrong：
![微信截图_20231129120607](https://github.com/frappe/erpnext/assets/137211649/4ecf88cc-2115-4e6a-bf9b-a2349a78d5ed)
![微信截图_20231129120724](https://github.com/frappe/erpnext/assets/137211649/dc4611f2-76cd-46ce-8ad9-e778578ccfde)

### Module

other

### Version

ERPNext: v15.4.0 (version-15)

Frappe Framework: v15.3.0 (version-15)

### Installation method

manual install

**Comment by dj12djdjs** [comment]
Duplicate of: https://github.com/frappe/erpnext/issues/33911
