### ISSUE TITLE
Colombia Chart of Account not showing.

### ISSUE THREAD

**Issue by computerman2k5** [frappe/erpnext#3842]
Hi, 
I have a Problem with Country Wise Charts of Account, I choosed Colombia ( An unverified chart of account, with his own JSON file ), I need to use this .JSON file. Please help me to use this file in ErpNext official hosting if possible.

**Comment by nabinhait** [comment]
Please check following thread in erpnext forum:
https://discuss.erpnext.com/t/help-needed-country-wise-chart-of-accounts/4154

And please share back the file if you are able to verify the chart of accounts.
