### ISSUE TITLE
It is not possible to amend a Subcontracting Order

### ISSUE THREAD

**Issue by ophl55** [frappe/erpnext#38433]
### Information about bug

Problem:

Cancelled Subcontracting Order can not be amended. The validation fails on submitting the new version of the document.

The validation checks that no other Subcontracting Order is submitted against the Purchase Order. Unfortunately the valiadtion "thinks" the new and correct doc is already submitted and not legal. 

Therefore the validation fails. 

### Module

other

### Version

ERPNext: v14.52.0 (version-14)
Frappe Framework: v14.57.0 (version-14)

### Installation method

docker

### Relevant log output / Stack trace / Full Error Message.

```shell
request.js:457 Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 95, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1628, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 31, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 309, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 343, in _save
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1058, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 919, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1281, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1263, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 916, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/subcontracting/doctype/subcontracting_order/subcontracting_order.py", line 21, in validate
    self.validate_purchase_order_for_subcontracting()
  File "apps/erpnext/erpnext/subcontracting/doctype/subcontracting_order/subcontracting_order.py", line 41, in validate_purchase_order_for_subcontracting
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 540, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 508, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 454, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Only one Subcontracting Order can be created against a Purchase Order, cancel the existing Subcontracting Order to create a new one.
```

**Comment by s-aga-r** [comment]
@ophl55 Works for me, could you provide a gif following the steps?

Also, the validation ignores the Cancelled and Draft Subcontracting Order i.e., only considers the Submitted one. Although will raise a PR to check the `docstatus` instead of `status`.

https://github.com/frappe/erpnext/assets/63660334/0b0fe412-592c-44fe-8f1d-09bc5671eff4

**Comment by ophl55** [comment]
Hi @s-aga-r  and thanks for your fast reply. Here the requested gif:

![sc_ord_bug](https://github.com/frappe/erpnext/assets/5788712/43d027ba-ae2a-44e9-90d2-6bca19f546c9)

**Comment by ophl55** [comment]
As you can see only the cancelled and them amended SC-ORD (Draft) exist:

![image](https://github.com/frappe/erpnext/assets/5788712/4d62b253-bcad-4db7-b77b-fb82f64f4c08)

**Comment by s-aga-r** [comment]
@ophl55 Try creating directly from PO instead of amending the cancelled one. Also, you have `Restrictions` there might be an SCO to which you don't have access (?)

**Comment by ophl55** [comment]
@s-aga-r 

1.) "Try creating directly from PO instead of amending the cancelled on" -> Doesn't work. The same error appears.

2,) "Also, you have Restrictions there might be an SCO to which you don't have access (?)" -> I have no restrictions. 

While debugging the code I saw, that the SCO I want to submit is the one that causes the validation to fail. So the SCO blocks itself during validation. It seems like the SCO has already the state "Submitted" since the query to validate filters out the "Drafts" and "Cancelled" docs.

To reproduce and analyze the behviour you can add these lines to `purchase_order.py` method `def is_subcontracting_order_created()`:

```
@frappe.whitelist()
def is_subcontracting_order_created(po_name) -> bool:
	count = frappe.db.count(
		"Subcontracting Order", {"purchase_order": po_name, "status": ["not in", ["Draft", "Cancelled"]]}
	)

        # ***FOR DEBUGGING***
	docs = frappe.db.get_all(
		"Subcontracting Order", {"purchase_order": po_name, "status": ["not in", ["Draft", "Cancelled"]]}
	)

	return True if count else False
```

Have a look at `docs`. You will see the name of current SCO that should be amended.

**Comment by s-aga-r** [comment]
@ophl55 might be a status issue. The status gets copied to the amended doc or the cancelled doc might have incorrect status I.e., submitted? 

Check `cur_frm.doc.status` for both the docs.

**Comment by ophl55** [comment]
@s-aga-r 

`cur_frm.doc.status='Open'` for the amended Draft. 

Yes, that's the issue. So I can confirm that you PR should solve the issue. 
Thanks for the effort!
