### ISSUE TITLE
Consumed material in sub-contracted purchases does not pull specified alternative items as 'consumed stock'

### ISSUE THREAD

**Issue by ArcticSilk** [frappe/erpnext#38462]
### Information about bug

Hello,
I had transferred stock across to a suppliers warehouse as they were using stock from my inventory to build a product. I had specified a few items to use alternative items.
I have just received the goods back and gone to consume material from the suppliers warehouse, but the alternative items are not being consumed and is still pulling in the original items. It looks like the consumed materials are still trying to be pulled across from the original BoM and not what i have actually sent the supplier. 
I have also double checked that i did actually send the supplier the alternative items - which i have.
Can you advise please.
Thanks

### Module

buying

### Version

FRAPPE - 13.58.12
ERPNext - 13.54.6

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
No error message - it isn't doing something as it should
```

**Comment by ArcticSilk** [comment]
Update:

Digging a bit deeper, the stock entry for this product shows me having transferred the alternative items, but the table of 'raw material supplied' in the purchase order is still showing the original items - it looks like the 'consumed material' when receiving the products is pulling in the items from this table and seems that the supplied material does not copy the stock entry of supplied material

**Comment by s-aga-r** [comment]
@ArcticSilk Please update your instance to v14/15 and try to replicate the issue, reopen this issue if you see similar results.

**Comment by ArcticSilk** [comment]
You have historically upgraded our system - can you please advise how you can do this?

**Comment by s-aga-r** [comment]
> how / where do i find the link to update or upgrade to v14/15?

If you are on Frappe Cloud just raise a ticket for a site upgrade. If self-hosted follow the [migration](https://github.com/frappe/erpnext/wiki/Migration-Guide-to-ERPNext-version-14) guide.

**Comment by ArcticSilk** [comment]
Sorry, i cannot see how to raise a ticket on frappe cloud and i dont see any link in the migration guide. Can you point me in the right direction?
