### ISSUE TITLE
Broadcast message

### ISSUE THREAD

**Issue by ajiragroup** [frappe/erpnext#38465]
Wouldn't it be great if there were some means to send out a broadcast message to every user about some important urgent updates ?

Every other user would see a popup or a highlighted message box (which will be read only) which show the broadcast message from management. 

What employee wouldn't be happy to see this message from Admin ?

`Tomorrow is a Holiday !`

**Comment by cogk** [comment]
You might want to look at the `Note` document type: tick the checkbox `Public` then `Notify on login`.
