### ISSUE TITLE
Sort order of Customer should be `modified DESC`, not `ASC`

### ISSUE THREAD

**Issue by cogk** [frappe/erpnext#38473]
# Sort order of Customer should be `modified DESC`

[It's been like that for 8 years](https://github.com/frappe/erpnext/commit/29b565fdf54cb7d59e52a9ae1ab70c143ceae827#diff-e851c9f6c12204fced775db0f626fa7ccb65899189362a9312d8b94bc59d160dR1012), but [a recent change to the way Link results are sorted](https://github.com/frappe/frappe/pull/22745) means that **the Customer that I just created won't appear at the top of the list** when making a Quotation/Order/Invoice.

https://github.com/frappe/erpnext/blob/832734ff4c3b36e0345c846f11e3822a2d83cbde/erpnext/selling/doctype/customer/customer.json#L667-L668

### Module

buying, selling, CRM

### Version

develop

**Comment by s-aga-r** [comment]
@cogk raising PR? This needs to be correct for all ERPNext DocTypes.
