### ISSUE TITLE
user permission error

### ISSUE THREAD

**Issue by adhennon** [frappe/erpnext#38470]
### Information about bug

i created a user permission where a user was restricted to view employee records in employee doctype apart from his but could access employee records in other doctypes. but the rule was applying to all doctypes yet it was not supposed to do so. i expected that when creating a user permission and i select a user, for example user john, allow for employee , for value i selected that employee only then apply to all documents is unticked and applicable for i select only employee doctype. i only expect this rule to restrict this user access to other employee records in the employee doctype alone not all doctypes.
thanks

### Module

other

### Version

ERPNext: v14.46.1
Frappe Framework: v14.54.0

### Installation method

docker

**Comment by cogk** [comment]
When you create a `User Permission` (restriction), it restricts all DocTypes that have a **Link** to the specified DocType. I will give you an example just to make sure I understand your problem:

- If I create a User Permission for DocType **Company** with value _MyFirstCompany_, then the affected User won't be able to see Invoices of _MySecondCompany_, even though I never even mentioned Invoices in my User Permission document.
- Indeed, restrictions are applied based on the value of **any Link field in any document** (Sales Invoice has a link to a Company)
- If I want to ignore restrictions for some field, I can customize the affected Link field and check `Ignore user permissions`
- If I want even stricter restrictions, check System Settings for `Apply strict user permissions`

**Comment by adhennon** [comment]
Thanks for the explanation i now understand it very well

**Comment by adhennon** [comment]
the concern was resolved
