### ISSUE TITLE
Serial No document showing inactive after delivery note is created

### ISSUE THREAD

**Issue by sapl-santhosh** [frappe/erpnext#38495]
### Information about bug

Serial number is created in stock entry using manufacture method.  (Active)
the same serial number is picked up to create a delivery note. After doing so it goes to Inactive state. 

But in version 14 it shows as Delivered and the warranty expiry date shows  DN date + 365 days
but in version 15 can't able to see that warranty expiry itself 

### Module

stock

### Version

Frappe: 15.2.1
Erpnext: 15.3

### Installation method

FrappeCloud

**Comment by sapl-santhosh** [comment]
![Screenshot 2023-12-01 173905](https://github.com/frappe/erpnext/assets/109452795/2e29e793-c774-46b4-956e-40382c2a9e36)
![Screenshot 2023-12-01 173929](https://github.com/frappe/erpnext/assets/109452795/33af7c0a-dcad-48a4-94e0-a2abbca71dfc)

**Comment by rohitwaghchaure** [comment]
@sapl-santhosh Fixed in v15.4.0 https://github.com/frappe/erpnext/pull/38397

Please update your site and check for new entry

**Comment by sapl-santhosh** [comment]
@rohitwaghchaure thanks it works fine now.

**Comment by sapl-santhosh** [comment]
hi still the warranty expiry field is not visible.
just tried with creating another stock entry and Delivery note and serial number
