### ISSUE TITLE
Item Color Code in Stock Entry Material Transfer

### ISSUE THREAD

**Issue by rawsel** [frappe/erpnext#38509]
### Information about bug

Hello i just want to ask what is this colored circle icon beside item code in stock entry material request document? I tried all the things and still can't get it to turn green. Can someone please explain what each color means? Sometimes the color is green, blue, or brown

<img width="453" alt="Screenshot 2023-12-02 162632" src="https://github.com/frappe/erpnext/assets/131623802/ece2d8ce-0565-472c-ba58-656107418909">

Thank you

### Module

stock

### Version

ERPNext: v14.43.0 (version-14)
Frappe Framework: v14.51.0 (version-14)
Frappe HR: v14.13.0 (version-14)
POS Awesome: v6.1.3 (version-14)

### Installation method

manual install

**Comment by rohitwaghchaure** [comment]
If the available quantity in the source warehouse is greater than the quantity in the stock entry, the color will be green, otherwise it will be orange. 
If the entry is material receipt or manufacture / repack then the color will be Blue 

I don't think this is a bug
