### ISSUE TITLE
Cannot delete the Stock Entry in the Draft state 

### ISSUE THREAD

**Issue by MohamedShajith** [frappe/erpnext#38507]
### Information about bug

"Cannot delete or cancel because Stock Entry ABC-00091 is linked with Serial and Batch Bundle SABB-00001328."

### Module

stock

### Version

v15.1.0 - Frappe
v15.2.0 - ERPNext

### Installation method

manual install

**Comment by rohitwaghchaure** [comment]
@MohamedShajith Delete the Serial and Batch Bundle SABB-00001328 and then try to delete the stock entry ABC-00091

**Comment by MohamedShajith** [comment]
I haven't submitted the Stock entry right. Then why I need to delete the Serial and batch bundle everytime
