### ISSUE TITLE
Serial Number Ledger showing all the serial number data inspite of the filters

### ISSUE THREAD

**Issue by sapl-santhosh** [frappe/erpnext#38510]
### Information about bug

In serial nunber doc > when clicking view ledger opens the ledger with the particular item and serial no. in the filter. but it shows all the serial numbers in the particular item code. 

There is some issue in the serial number ledger report

### Module

stock

### Version

ERPNext: v15.4.0 (HEAD)
Frappe Framework: v15.3.0 (HEAD)

![Screenshot 2023-12-02 170627](https://github.com/frappe/erpnext/assets/109452795/a7ecc5ed-7fa7-423f-af9c-753731ccd506)

### Installation method

FrappeCloud

**Comment by rohitwaghchaure** [comment]
@sapl-santhosh 

I have tested in my local instance and it's working fine

<img width="1327" alt="image" src="https://github.com/frappe/erpnext/assets/8780500/ff021499-a787-44f4-b804-69a7fd5f4b19">


Looks like some data issue in your account, can you share your site name

**Comment by sapl-santhosh** [comment]
sensoware.frappe.cloud
