### ISSUE TITLE
Schedule date in Purchase Order Item should be modifiable after Submit

### ISSUE THREAD

**Issue by Priyanka-IAS** [frappe/erpnext#3852]
Hi,

It is very common for us to face delays/changes in delivery schedule dates from our suppliers much after the Purchase Order was placed. 

We would like to change the date in the PO (after submit) so that we are able to keep track of the delivery dates. Currently we cannot update "Schedule Date" in Purchase Order Item as it is a Standard field that cannot be marked "Allow on Submit".

Regards,

Priyanka Kaushal

**Comment by robertbecht** [comment]
Yepp,dates of docs should be modiable. Used to like that in an earlier version
