### ISSUE TITLE
POS workflow enhancement (Pay & Print button) + no confirmation

### ISSUE THREAD

**Issue by fderyckel** [frappe/erpnext#3853]
PAID development.
As a follow up of https://github.com/frappe/erpnext/issues/3444

Hi Rushabh and Frappe Team, 
Could you quote us on the following development:
**Add a "Pay & Print" button on the POS view for sale invoice.  Immediately this will print the invoice.  Right now the process is very long.  
** skip the confirm submission button
1. Click Pay
2. Click on confirm submission
3. Use the back button as once it is paid it bring us to a new invoice.
4. Click the Print button
5. Print the pdf.

All of this should normally be just one click.

Thanks

François

**Comment by rmehta** [comment]
@fderyckel added to watchlist, we will do this on priority.

**Comment by fderyckel** [comment]
Hi Rushabh,
Any news on this?  Could you make it as Paid development (and an estimate of the cost)?
Thanks
François

**Comment by rmehta** [comment]
@fderyckel sorry had got caught up in other issues. Yeah paid development is a better model sometimes. $100?

**Comment by rmehta** [comment]
Fixed. Will be updated in the next release.
