### ISSUE TITLE
Strange Behavior of "Allow Zero Valuation Rate" in Stock Reconciliation

### ISSUE THREAD

**Issue by hans-permana** [frappe/erpnext#38587]
### Information about bug

In Stock Reconciliation Item doctype, there is a field called **allow_zero_valuation_rate**, which is very helpful in enabling the rate of an item to be 0. However, upon checking, the field is read-only and depends on **allow_zero_valuation_rate**. Is this an intended behavior? If so, could someone explain what this is for?

### Module

stock

### Version

ERPNext: v14.46.1 (version-14)
Frappe Framework: v14.54.0 (version-14)

![allow-zero-valuation-rate-issue](https://github.com/frappe/erpnext/assets/7643370/c805e772-054f-4670-9905-bc0a1b0fee36)

### Installation method

manual install

**Comment by s-aga-r** [comment]
@hans-permana https://github.com/frappe/erpnext/pull/24888#discussion_r599264847

**Comment by s-aga-r** [comment]
@hans-permana https://github.com/frappe/erpnext/pull/24888

**Comment by hans-permana** [comment]
I see, so this checkbox is made only for customer-provided item. Thanks for the pointer.
