### ISSUE TITLE
Total Column goes off in Reporting if you use any filter in reports

### ISSUE THREAD

**Issue by bharatepillars** [frappe/erpnext#3858]
Total Column goes off in Reporting if you use any filter in reports. 
![item-wise sales history 2015-08-12 15-36-12](https://cloud.githubusercontent.com/assets/13675195/9223141/81cbefb0-4108-11e5-8a70-d7fa2f026a7f.png)
![item-wise sales history 2015-08-12 15-34-20](https://cloud.githubusercontent.com/assets/13675195/9223142/81d109c8-4108-11e5-8e21-ca3ab343bab3.png)

**Comment by robertbecht** [comment]
totals on filtered data would really be an improvement

**Comment by revant** [comment]
Duplicate: https://github.com/frappe/erpnext/issues/7592
