### ISSUE TITLE
receive and pay postpaid cheque 

### ISSUE THREAD

**Issue by negini** [frappe/erpnext#3860]
Hi
there is problem in erpnext , we can't manage postpaid cheque we receiving from customer , so we control when the date of cheque will come and we can deposit to account or each customer how much postpaid cheque have with us to control credit of customer before issue new invoice . 

also problem when we paid postpaid cheque to our supplier , for example we pay cheque dated for 60 days , to some supplier 30 days to some and ... 
we can't get any report how much outstanding cheque we have for example for next 10 days to arrange money for that and we have to calculate separately in excel , 
any solution in erpnext to handle sent  and received postpaid cheque ?

**Comment by PawanMeh** [comment]
Please check the following [link1](https://frappe.github.io/erpnext/user/manual/en/accounts/advance-payment-entry) & [link2](https://discuss.erpnext.com/t/advance-payment-to-supplier/6412/2)
