### ISSUE TITLE
GROSS PROFIT, GIVING WRONG FIGURES

### ISSUE THREAD

**Issue by tedyswaga** [frappe/erpnext#38611]
### Information about bug

In the gross profit, am getting wrong total figures,  this is due to how the total calculations are performed.
Erpnext adds the total invoice amount and individual invoice items. Giving a very large figure.
![IMG-20231207-WA0002](https://github.com/frappe/erpnext/assets/28439380/80e8af14-108c-4a62-a484-204e5c862440)
![IMG-20231207-WA0001](https://github.com/frappe/erpnext/assets/28439380/bf6ca14d-10b4-48a8-bd33-803b7cd0de3c)

### Module

accounts

### Version

Erpnext v13

### Installation method

None

**Comment by dj12djdjs** [comment]
Closing as this issue is already documented: https://github.com/frappe/erpnext/issues/33911
