### ISSUE TITLE
Email for Opportunity is not working

### ISSUE THREAD

**Issue by justinlusg** [frappe/erpnext#3861]
1) Email account (sales@agtech.com.sg) has been setup correctly and appended to Opportunity
2) Emails are sent to sales@agtech.com.sg and mails are checked and removed from the server
3) Emails does not appear under communications and neither are opportunities created
4) The emails just vanished
5) Weirdly ONLY email sent from info@agtech.com.sg are appended correctly. All other emails does not work. Tried from many different domains, sent from different servers and only emails from info@agtech.com.sg email gets appended.
6) All other email accounts (e.g. support@agtech.com.sg for Issues, hr@agtech.com.sg for Job Applicants) works perfectly

Not sure if the issue is with appending emails to opportunity.

**Comment by justinlusg** [comment]
Ok, I realised it's because there is a mandatory field which I've made mandatory and the system is unable to create a new lead, hence unable to create an opportunity.

**Comment by anandpdoshi** [comment]
But afaik we ignore mandatory fields and just insert it. Let me look into it.

**Comment by justinlusg** [comment]
@anandpdoshi just for information, the mandatory field is a custom field that was created, linked to Sales Person and made mandatory.
