### ISSUE TITLE
v5. Debit and Credit not equal, Difference in whole number

### ISSUE THREAD

**Issue by computerman2k5** [frappe/erpnext#3862]
Hi, I have a problem with Submitting an Invoice, I will show the image
![captura_de_pantalla_081215_113444_am](https://cloud.githubusercontent.com/assets/1940336/9230107/229f9824-40e6-11e5-881a-2171d98101db.jpg)

As you can see, Difference is not in decimals, I've read other forum threads related to this problem, but all of them are with decimal numbers. 

I tried: 
- Changing float numbers to 6
-Put the difference as a Real tax in round account.
-Change the tax type from "Total" to "Value" (It worked, but the tax is not getting into Grand Total)

**Comment by anandpdoshi** [comment]
Can you share the purchase invoice values, after obfuscating confidential info?

**Comment by nabinhait** [comment]
Have you entered Creditors (supplier) account in item or tax table?

**Comment by nabinhait** [comment]
Assuming this has been fixed. If not, create an invoice with same data in demo.erpnext.com and share the invoice id.
