### ISSUE TITLE
 Some fields are not listed in the doc object in the server side script

### ISSUE THREAD

**Issue by bakhtari** [frappe/erpnext#38622]
### Information about bug

Some fields are not listed in the doc object in the server side script
for example:
diff=frappe.db.get_value(“Stock Ledger Entry”,{“name”: doc.name},“stock_value_difference”)
diff is None
or
doc.stock_value is None
or
stock=frappe.get_doc(“Stock Ledger Entry”, doc.name)
stock_value is None

### Module

stock

### Version

erpnext 14.13.0
frappe 14.23.0
OR
erpnext 15.0.0
frappe 15.0.1

### Installation method

manual install

**Comment by s-aga-r** [comment]
@bakhtari Please provide us with the complete Server Script you have written and the selected DocType Event.

**Comment by bakhtari** [comment]
Server Side Code:
weight_per_unit=frappe.db.get_value('Item', {'item_code': doc.item_code}, ['weight_per_unit'])
weight_unit=frappe.db.get_value('Item', {'item_code': doc.item_code}, ['weight_uom'])
frappe.db.set_value("Stock Ledger Entry",doc.name,'custom_weight_unit',weight_unit)
frappe.db.set_value("Stock Ledger Entry",doc.name,'custom_weight_per_unit',weight_per_unit)
frappe.db.set_value("Stock Ledger Entry",doc.name,'custom_total_weight',abs(weight_per_unit*doc.actual_qty))
diff=frappe.db.get_value(“Stock Ledger Entry”,{“name”: doc.name},“stock_value_difference”)
frappe.db.set_value("Stock Ledger Entry",doc.name,'custom_stock_value_difference',abs(weight_per_unit*doc.stock_value_difference))
Event is: After Save

**Comment by s-aga-r** [comment]
@bakhtari 

SLE is not a normal DocType, it is a ledger. The entry is created first with Actual Qty and other details, the Stock Value Difference gets updated later by the system.

Closing this issue, please ask for help in our [Forum](https://discuss.frappe.io/) or [Telegram Group](https://t.me/erpnext_public/40513).
