### ISSUE TITLE
Cannot access site from other computer in LAN  after install

### ISSUE THREAD

**Issue by biz1990** [frappe/erpnext#38631]
### Information about bug

I had installed Erpnext 15 and Frappe 15 on Ubuntu Server 22.04 LTS. After create site i can access with ip and port from other computer although in LAN can ping IP with port 8000. Address at http://192.168.190.237:8000/ and name of site is ermp.dev. If i use IP access site the webpage response 404 not found and 192.168.190.237 does not exist

### Module

other

### Version

Frappe version 15.4.1
ERPNext version 15.5.0

### Installation method

manual install

**Comment by s-aga-r** [comment]
@biz1990 Ask development-related queries in our [Forum](https://discuss.frappe.io/) OR [Telegram Group](https://t.me/frappeframework/3457).
