### ISSUE TITLE
Quality Inspection defaults to request Serial No input

### ISSUE THREAD

**Issue by ArcticSilk** [frappe/erpnext#38648]
### Information about bug

Completing a QA report on some incoming items (which are not SN enabled), but when completing a QA report, the SN field has a red asterix asking me to input a value for this item, but this item is not serialised, and so i cannot proceed.

### Module

quality

### Version

ERPNext - v15.52.1
Frappe - v14.57.0

### Installation method

FrappeCloud

**Comment by s-aga-r** [comment]
@ArcticSilk Please provide us with screenshots and steps to replicate the issue.
