### ISSUE TITLE
V15 Purchase Order Creation

### ISSUE THREAD

**Issue by krishnanhemanth** [frappe/erpnext#38656]
### Information about bug

Cannot create Purchase Order Due to the following conditions
Condition 1
In Purchase Order
**If "IS SUBCONTRATED" is not selected**
Then only Purchase items can be selected from Items Drop Menu
While saving --- This error shows up
"Company GSTIN is a mandatory field for GST Transactions"
This error is coming in spite of GST details entered for the supplier

Condition 2
**If "IS SUBCONTRATED" is selected**
Then Only non stock items can be selected from items Drop Menu

Thanks and Regards

### Module

buying

### Version

ERPNext: v15.5.0 (version-15)
Frappe Framework: v15.4.1 (version-15)

### Installation method

None

**Comment by s-aga-r** [comment]
@krishnanhemanth 

Both are working as expected.

> If "IS SUBCONTRATED" is not selected

Only Purchase Items can be purchased via Purchase Order/Receipt/Invoice.

> If "IS SUBCONTRATED" is selected

That's a different flow. For subcontracting, you need to select two Items (Service Item and Finished Good Item)

Docs:
- https://docs.erpnext.com/docs/user/manual/en/purchase-order
- https://docs.erpnext.com/docs/user/manual/en/subcontracting

**Comment by krishnanhemanth** [comment]
Hi
When  "IS SUBCONTRATED" is selected
Then I am able to select only NON STOCK ITEM in the item drop down menu
Whereas Subcontracted items are stock items
For example
I manufacture Bolts
Here Bolt being the parent (processed item), i have these below as unprocessed and stock items
1>10mm steel rod
2> cnc machining
3> heat treatment
4> Blackening
here, all the above 4 are items and are stock items
A bom has been created like below
1>Parent : cnc machining
    Child : 10mm steel rod
2>Parent : heat treatment
    child : cnc Machining
3> Parent : Blackening
     Child : heat treatment
Now when i got create Purchase order
select the supplier
Tick Yes for  "IS SUBCONTRATED"
go to the items table 
Select the item >>>>
here I don't get to select any item that are marked as "stock item"
so any of the items listed above (1-4) are not available for selection in the Items Drop down list
Thanks and Regards
Hemanth

**Comment by s-aga-r** [comment]
@krishnanhemanth Please go through the docs once. We have introduced a new flow of Subcontracting where you will select a Service Item against the finished good as subcontracting is a service, not a direct purchase. There are two fields in the Purchase Ordre Item table first is the Item Code where you need to select the Service Item (represents the service you are taking from the subcontractor) and the second is the Finished Good where you need to select the actual stock item which you will receive at the end of the cycle (receipt).

**Comment by krishnanhemanth** [comment]
Hi
Thanks for the reply
The above seems to be working
But
While saving the Po i get the error "Company GSTIN is a mandatory field for GST Transactions"
Have already mentioned about this error in my first post
This error in throwing up in spite of Supplier and Company GST being entered
Hence not able to save and move forward to check the entire Sub Contract Cycle
Thanks and Regards
Hemanth

**Comment by s-aga-r** [comment]
@krishnanhemanth 

> Company GSTIN is a mandatory field for GST Transactions

For this, you need to set the GSTIN in the Company as you have I[ndia Compliance](https://github.com/resilient-tech/india-compliance) app installed.

**Comment by krishnanhemanth** [comment]
Hi
First... Thanks a lot s-aga-r for your response
For company settings, the below image shows the setting. I have entered the gstin for the company
![company gst](https://github.com/frappe/erpnext/assets/13927972/d5418650-dcc5-4b2c-940c-4a2d5d9f1304)

Am i missing something
Thanks and Regards
Hemanth

**Comment by s-aga-r** [comment]
@krishnanhemanth raised a separate ticket in [India Compliance](https://github.com/resilient-tech/india-compliance).

**Comment by krishnanhemanth** [comment]
Hi
Should i Raise a ticket at India Compliance
Thanks and Regards
Hemanth

**Comment by krishnanhemanth** [comment]
Hi s-aga-r
The issue is sorted
There are two things that need to be done to successfully create a Po
1> In address list > add your company address with GST details and at the bottom of the page under Link, Link your company name
This solves the issue of "Company GSTIN is a mandatory field for GST Transactions"
This needs to be updated in the documents (the help documents of erpnext)
This solves the issue but again there is duplicating of details.
Company details are already filled in the company settings along with GST No

2> Not able to create a PO (primary Issue)
Here Please follow the steps
1> Create a non-stock Item
create an item for example Anodizing is an item i have created and **have not ticked the Maintain Stock**
2> create a Purchase Order
fill all the details
select / tick  - is subcontracted
3> go to items table
here is all the confusion is about
4>select item code - it shows only those items that **have not ticked the Maintain Stock**
5>select the item
and when you save - it throws an error - Row #1: Finished Good Item is not specified for service item ABC
6>go to the right end of the table 
you can see the edit button
7>Press edit
here once the form opens, you can see the columns to enter the finished goods that is required
8>submit and proceed
So this is it
Some clarity in documentation
the finished goods column showing up in the main page rather than accessing it after pressing the edit button
can make things easy
Thanks and Regards
Hemanth
