### ISSUE TITLE
Company filters in link fields on Lending module not working

### ISSUE THREAD

**Issue by chrisdent** [frappe/erpnext#38650]
### Information about bug

There is no company filter on link fields in the following doctypes fields in the lending module:

Loan Product:  almost all accounts.
Loan Disbursement: Cost Center, Bank Account, Disbursement Account, 
Loan Repayment: Cost Center

### Module

other

### Version

ERPNext: v15.5.0
Frappe Framework: v15.4.1
Frappe HR: v15.5.0
Frappe Lending: v0.0.1

### Installation method

manual install

**Comment by deepeshgarg007** [comment]
@chrisdent Please raise this issue on the lending app repo. Closing this issue
