### ISSUE TITLE
Full PostgreSQL Support - Removal of MariaDB Dependency

### ISSUE THREAD

**Issue by edardev** [frappe/erpnext#38664]
**Is your feature request related to a problem? Please describe.**
  Yes, the current use of the MariaDB database in ERPNext poses challenges for users who prefer or are mandated to use PostgreSQL. This creates compatibility issues and makes it challenging for organizations to align their database systems.

**Describe the solution you'd like**
 propose a feature request to remove the dependency on MariaDB and provide full support for PostgreSQL as the primary database for ERPNext. This involves ensuring that all ERPNext functionalities are fully compatible with PostgreSQL and that the installation process seamlessly integrates with PostgreSQL.

**Describe alternatives you've considered**
  The current workaround for users preferring PostgreSQL is to manually migrate the database from MariaDB to PostgreSQL. However, this process can be complex and error-prone, leading to potential data inconsistencies and disruptions. A built-in feature for direct PostgreSQL support would eliminate the need for such manual interventions.

**Additional context**
  Given the increasing popularity of PostgreSQL and its adoption as the preferred database system by many enterprises, having ERPNext fully support PostgreSQL would enhance its flexibility and appeal to a broader user base. This change aligns with industry trends and provides users with the option to choose the database solution that best fits their organizational requirements.

**Comment by ankush** [comment]
https://github.com/frappe/erpnext/issues/24389
