### ISSUE TITLE
Showing empty batch in the consumed table

### ISSUE THREAD

**Issue by Anoop2312** [frappe/erpnext#38666]
Here is an issue we are facing while doing material receipt in the stock entry doctype,

Let’s Suppose, One month ago we transferred a raw material (ITEM - 123), which has a total qty in 2 batches (BATCH0001 & BATCH0002) to the supplier's warehouse and we did the subcontracting receipt and stock entry of that item and consumed the whole qty of that item from BATCH0001 & BATCH0002.

After 1 month, again we created a subcontracting order and did stock entry of some qty for the same item (ITEM - 123) and sent material to the supplier warehouse in which batch is BATCH0003.

Then, while creating material receipts, sometimes it shows the old empty batches in the consumed table. Attached is the screenshot for reference:
![image](https://github.com/frappe/frappe/assets/148338951/59e2de34-b648-4a89-83a7-d3f656af7f0a)

https://rangsutra-erpnextv14.frappe.cloud/app/subcontracting-receipt/SCR%2FFY23%2FBK1336

It's not fixed how many batches it's going to pick, sometimes it picks two batches (ex. BATCH0001, BATCH0003) of that same item (ITEM - 123) and sometimes it picks all batches that have been sent to that supplier (ex. BATCH0001, BATCH0002, BATCH0003), and in some cases it picks the correct batch (BATCH0003) which has been sent to the supplier for that particular order.  

Expectation -  
1. The system does not automatically display and add zero consumed batches in the table.
2. During the material receipt process, batches should be chosen based on the FIFO  basis.
3. Provide the capability to include or exclude row items from the consumed table.

Kindly do needful for this issue.

Thanks & Regards,
Anoop

**Comment by s-aga-r** [comment]
@Anoop2312 

> Provide the capability to include or exclude row items from the consumed table.

This won't be allowed if the Backflush is based on BOM as the Valuation of the Finished Item depends on the consumed materials.

**Comment by s-aga-r** [comment]
https://github.com/frappe/erpnext/pull/38892
