### ISSUE TITLE
Amount from Exchange Rate Revaluation appears on AP report

### ISSUE THREAD

**Issue by hans-permana** [frappe/erpnext#38695]
### Information about bug

Upon submitting Exchange Rate Revaluation document (and subsequently the ERR Journal Entry), the amount is appearing in AP report under Paid Amount (and subsequently Outstanding Amount). I think it should not appear there.

![image](https://github.com/frappe/erpnext/assets/126162889/8a8b1934-9a8a-46ee-acad-ce5398dcc07b)

![image](https://github.com/frappe/erpnext/assets/126162889/418f53a4-c18f-406b-aea9-b522b16ac343)

### Module

accounts

### Version

ERPNext: v14.46.1 (version-14)
Frappe Framework: v14.54.0 (version-14)

### Installation method

None

**Comment by GursheenK** [comment]
In the latest version, there is a filter available in the Payable and Receivable Reports called "Revaluation Journals". You can disable it to not include any revaluation journals within the report.
