### ISSUE TITLE
There is no way to set read_only prop in server script.

### ISSUE THREAD

**Issue by itse4elhaam** [frappe/erpnext#38706]
### Information about bug

There is no equivalent for ` frm.set_df_property("myfield", "read_only", frm.is_new() ? 0 : 1);` in **server scripts.**

### Module

CRM

### Version

ERPNext & Frappe Version: 14

### Installation method

easy-install

### Relevant log output / Stack trace / Full Error Message.

```shell
It doesn't log out any error but doesn't do anything else either.
```

**Comment by s-aga-r** [comment]
@itse4elhaam The Client Script is used to alter the client site functionality whereas the Server Script is used to update the data.

**Comment by itse4elhaam** [comment]
@s-aga-r 

Where can I alter the read_only property?

**Comment by s-aga-r** [comment]
Use [Client Script](https://frappeframework.com/docs/user/en/desk/scripting/client-script), [reference](https://discuss.frappe.io/t/how-to-make-readonly/37018)
