### ISSUE TITLE
Getting Error: No module named 'frappe.core.doctype.repost_accounting_ledger_settings' while bench migrate

### ISSUE THREAD

**Issue by sagardspeed2** [frappe/erpnext#38704]
## Description of the issue
Getting error while bench migrate
Error: No module named 'frappe.core.doctype.repost_accounting_ledger_settings'

## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 14.x.x-develop
frappe 15.x.x-develop
hrms 16.0.0-dev
india_compliance 16.0.0-dev
payments 0.0.1
```

## Steps to reproduce the issue

1.```bench --site all migrate```

### Stacktrace / full error message

```
builtins.ImportError: Module import failed for Repost Accounting Ledger Settings, the DocType you're trying to open might be deleted.<br> Error: No module named 'frappe.core.doctype.repost_accounting_ledger_settings'
```

## Additional information

OS version / distribution, `Frappe` install method, etc.

**Comment by sagardspeed2** [comment]
<img width="807" alt="image" src="https://github.com/frappe/frappe/assets/31651612/3971b829-2f91-455b-8415-877f65e484a6">

**Comment by viralkansodiya** [comment]
when I was in the old version of frappe and erpnext and I was installed the latest version of HRMS that time I got this error

To resolve this error update frappe and erpnext also this error will automatically resolve
