### ISSUE TITLE
Issue while loading the data from another doctype

### ISSUE THREAD

**Issue by TusharTs9401** [frappe/erpnext#38719]
### Information about bug

I have auto load the product from product doctype instead of their ID’s I get the product model number. But currently I encounter another issue in it.
When clicked on the product loaded to enter their values like achievement type or achievement value it removes the product number and we have to reselect it.
when we auto load the product instead of their ID’s we get the product model number. But currently we encounter another issue in it.
When clicked on the product loaded to enter their values like achievement type or achievement value it removes the product number and we have to reselect it.

It would be great if someone can help us with these issue.
![Auto Load of Products](https://github.com/frappe/erpnext/assets/147740690/00084616-28bc-4357-806a-2edeca3eb8c5)

### Module

other

### Version

Frappe Version-v15.0.0
ERPNext Version-v15.0.0

### Installation method

FrappeCloud

**Comment by s-aga-r** [comment]
@TusharTs9401 Please ask development/customization-related queries on our [Forum](https://discuss.frappe.io/) or [Telegram Group](https://t.me/erpnext_public/40513).
