### ISSUE TITLE
Unable to rename Item Code 

### ISSUE THREAD

**Issue by davygarg** [frappe/erpnext#38715]
### Information about bug

Getting Error while updating Item Code . Error Screenshot below: 

![image](https://github.com/frappe/erpnext/assets/34978049/dd784153-ba83-43f5-a1c2-c50cb8063b94)

### Module

stock

### Version

ERPNext: v15.6.0 (version-15)

Frappe Framework: v15.5.0 (version-15)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"business_theme_v14": "0.0.1",
	"erpnext": "15.4.0",
	"frappe": "15.3.0",
	"frappe_system_monitor": "0.0.1",
	"india_compliance": "15.0.4",
	"payments": "0.0.1",
	"print_designer": "1.0.0",
	"webshop": "0.0.1"
}
```
### Route
```
Form/Item/AD200 ON/OFF
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1715, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/model/rename_doc.py", line 75, in update_document_title
    transformed_name = doc.run_method("before_rename", current_name, updated_name, merge)
  File "apps/frappe/frappe/model/document.py", line 950, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1316, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1300, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
TypeError: execute() takes from 3 to 4 positional arguments but 5 were given

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doctype": "Item",
		"docname": "AD200 ON/OFF",
		"name": "G-AD200-0002",
		"title": "ON/OFF SWITCH AD200 PRO",
		"enqueue": true,
		"merge": 0,
		"freeze": true,
		"freeze_message": "Updating related fields..."
	},
	"freeze": true,
	"freeze_message": "Updating related fields...",
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.model.rename_doc.update_document_title",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "TypeError: execute() takes from 3 to 4 positional arguments but 5 were given",
	"exc_type": "TypeError"
}
```
```

**Comment by rohitwaghchaure** [comment]
@davygarg 

I have checked in my local instance and it's working fine
![rename_item](https://github.com/frappe/erpnext/assets/8780500/95d35791-eb7d-490f-97ea-606f2819eb32)


Maybe you can pull the latest code and check
ERPNext current version: [v15.6.0](https://github.com/frappe/erpnext/releases/tag/v15.6.0)
Frappe current version: [v15.5.0](https://github.com/frappe/frappe/releases/tag/v15.5.0)

**Comment by davygarg** [comment]
Updated to Latest version v15.6.0 , still same issue

**Comment by davygarg** [comment]
> @davygarg
> 
> I have checked in my local instance and it's working fine ![rename_item](https://private-user-images.githubusercontent.com/8780500/290136937-95d35791-eb7d-490f-97ea-606f2819eb32.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NTk3MTAsIm5iZiI6MTcwMjQ1OTQxMCwicGF0aCI6Ii84NzgwNTAwLzI5MDEzNjkzNy05NWQzNTc5MS1lYjdkLTQ5MGYtOTdlYS02MDZmMjgxOWViMzIuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTNUMDkyMzMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Yzg4N2NlZTkyMWE0ZDdlYzA0MDU2YzFlMzUzOGEwMzFiNjEyMzBiODViZmYzYzk4NmMyOGY4MzljZTVlY2E2NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dcDkCycDzQK74aVGftsQgKTeyYjXSK9LMvccTAJ1ZEE) [ ](https://private-user-images.githubusercontent.com/8780500/290136937-95d35791-eb7d-490f-97ea-606f2819eb32.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NTk3MTAsIm5iZiI6MTcwMjQ1OTQxMCwicGF0aCI6Ii84NzgwNTAwLzI5MDEzNjkzNy05NWQzNTc5MS1lYjdkLTQ5MGYtOTdlYS02MDZmMjgxOWViMzIuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTNUMDkyMzMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Yzg4N2NlZTkyMWE0ZDdlYzA0MDU2YzFlMzUzOGEwMzFiNjEyMzBiODViZmYzYzk4NmMyOGY4MzljZTVlY2E2NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dcDkCycDzQK74aVGftsQgKTeyYjXSK9LMvccTAJ1ZEE) ![rename_item](https://private-user-images.githubusercontent.com/8780500/290136937-95d35791-eb7d-490f-97ea-606f2819eb32.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NTk3MTAsIm5iZiI6MTcwMjQ1OTQxMCwicGF0aCI6Ii84NzgwNTAwLzI5MDEzNjkzNy05NWQzNTc5MS1lYjdkLTQ5MGYtOTdlYS02MDZmMjgxOWViMzIuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTNUMDkyMzMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Yzg4N2NlZTkyMWE0ZDdlYzA0MDU2YzFlMzUzOGEwMzFiNjEyMzBiODViZmYzYzk4NmMyOGY4MzljZTVlY2E2NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dcDkCycDzQK74aVGftsQgKTeyYjXSK9LMvccTAJ1ZEE) [ ](https://private-user-images.githubusercontent.com/8780500/290136937-95d35791-eb7d-490f-97ea-606f2819eb32.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NTk3MTAsIm5iZiI6MTcwMjQ1OTQxMCwicGF0aCI6Ii84NzgwNTAwLzI5MDEzNjkzNy05NWQzNTc5MS1lYjdkLTQ5MGYtOTdlYS02MDZmMjgxOWViMzIuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTNUMDkyMzMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Yzg4N2NlZTkyMWE0ZDdlYzA0MDU2YzFlMzUzOGEwMzFiNjEyMzBiODViZmYzYzk4NmMyOGY4MzljZTVlY2E2NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dcDkCycDzQK74aVGftsQgKTeyYjXSK9LMvccTAJ1ZEE)
> 
> Maybe you can pull the latest code and check ERPNext current version: [v15.6.0](https://github.com/frappe/erpnext/releases/tag/v15.6.0) Frappe current version: [v15.5.0](https://github.com/frappe/frappe/releases/tag/v15.5.0)



Updated to Latest version v15.6.0 , still same issue.

I think in your case Item Name and Item Code are Same. 
When I change Item Name, there is no issue, but during Item Code change , this issue is coming
