### ISSUE TITLE
Issue while creating item variant based on manufacture

### ISSUE THREAD

**Issue by TusharTs9401** [frappe/erpnext#38711]
### Information about bug

I am creating a item variant based on manufacture. So while creating it is showing me an error
“Mandatory fields required in Item * Variant Attributes”.But if I select variant based on manufacture there is no place to add variant attribute. (as shown in attached below).
But in these first if I select variant based on item attribute and add a colour as attribute in it and then change the option to variant based on manufacture then it does not shows any error and works perfectly fine. So can anyone help me with these.
![Attribute Variant](https://github.com/frappe/erpnext/assets/147740690/3d719d76-9192-4995-9b32-e9a34be5a4e5)

### Module

stock

### Version

Frappe Version-v15.0
ERPNext Version-v15.0

### Installation method

FrappeCloud

**Comment by rohitwaghchaure** [comment]
@TusharTs9401 I have tried, this is working fine
