### ISSUE TITLE
PR #38608 breaks Pricing Rules ("don't update qty blindly")

### ISSUE THREAD

**Issue by cogk** [frappe/erpnext#38724]
@rtdany10 is working on a fix right now if I'm not mistaken? (just a revert)

/cc @s-aga-r 

---

### Information about bug

In a Quotation, when adding an Item row, the `get_item_details` method is called.
When Pricing Rules exist for the given item_code, a list of their names is loaded into a property called `pricing_rules`.

```py
r.message = {
  ...,
  "pricing_rules": "['my rule name']",
}
```

**However, there is also a `pricing_rules` field (table) in the parent document (Quotation).**

Because the `child: item,` parameter was removed in #38608 from the `frm.call` params, this means that the `else` branch of the callback is executed, which calls `frm.set_value({ ..., "pricing_rules": "..." })`. This breaks the `pricing_rules` table in the parent document, silently with an error visible in the console.

https://github.com/frappe/frappe/blob/174e24f1597e6c3834a6888c2e7d2a7cabe69065/frappe/public/js/frappe/form/form.js#L1755-L1758
```js
if ($.isPlainObject(r.message)) {
	if (opts.child) {
		// Copy all fields, even the qty field that PR #38608 wants to preserve.
	} else {
		// update parent doc
		me.set_value(r.message); // This sets the value of the `pricing_rules` TABLE with a string value (bad)
	}
```

---

https://github.com/frappe/erpnext/pull/38608/commits/0156339f3433f1a3ddb08885d2b85902c1114345

### Module

buying, selling

### Version

develop

**Comment by s-aga-r** [comment]
@rtdany10 try replacing the [this.frm.call](https://github.com/s-aga-r/erpnext/blob/c5e4e0174782222dc4bc26e3f03f5724d16c99ce/erpnext/public/js/controllers/transaction.js#L472) with `frappe.call`?

**Comment by s-aga-r** [comment]
https://github.com/frappe/erpnext/pull/38728

**Comment by rtdany10** [comment]
> @rtdany10 try replacing the [this.frm.call](https://github.com/s-aga-r/erpnext/blob/c5e4e0174782222dc4bc26e3f03f5724d16c99ce/erpnext/public/js/controllers/transaction.js#L472) with `frappe.call`?

That should probably take care of it, let me check in the evening.
