### ISSUE TITLE
Homepage issue in v15

### ISSUE THREAD

**Issue by precihole** [frappe/erpnext#38723]
### Information about bug

there is an issue with homepage as content not showing as below,
![image](https://github.com/frappe/erpnext/assets/111174201/47e2b843-762f-419c-b970-1e38ccfcfe63)

### Module

portal

### Version

ERPNext: v15.4.0 (HEAD)

Erpnext Telegram Integration: v1.2.0 (master)

Frappe Framework: v15.4.1 (version-15)

### Installation method

None

**Comment by s-aga-r** [comment]
@precihole If it is related to e-commerce (as mentioned) then install the [Webshop](https://github.com/frappe/webshop) app, Ecommerce is moved to a separate app now.

**Comment by precihole** [comment]
Hello, @s-aga-r 

Homepage doctype is not showing and it is in **Portal Module.**
sorry for wrong tagging.

![image](https://github.com/frappe/erpnext/assets/111174201/4838792b-afce-4a71-b9c3-29bc42da1384)

getting some error in background.
![image](https://github.com/frappe/erpnext/assets/111174201/55afb78c-19f3-4cc1-ace4-683656641026)

**Comment by s-aga-r** [comment]
> Hello, @s-aga-r 
> 
> Homepage doctype is not showing and it is in **Portal Module.**
> sorry for wrong tagging.
> 
> ![image](https://github.com/frappe/erpnext/assets/111174201/4838792b-afce-4a71-b9c3-29bc42da1384)
> 

@precihole please share the browser console log.

**Comment by precihole** [comment]
Hello, @s-aga-r 

![image](https://github.com/frappe/erpnext/assets/111174201/dcd3be08-53e4-4930-acb2-6201d124a314)

**Comment by rohitwaghchaure** [comment]
@precihole Could you please share the site name

**Comment by precihole** [comment]
> @precihole Could you please share the site name

It is locally hosted site.
