### ISSUE TITLE
API permission

### ISSUE THREAD

**Issue by prash4** [frappe/erpnext#3873]
Hello,
We have created an API to integrate with magento , 
It used to work fine , but since last 2 weeks , we are not able to access it.
When we run , it says not allowed to access , permission required .
We have not done any changes in the ERPnext setup.

So why is this happening ?

**Comment by rmehta** [comment]
Can you post the exact message? Also check your user permissions

**Comment by prash4** [comment]
Hello,

 

We are getting the attached error message .

 

And we check the permission, it is allowed .

**Comment by prash4** [comment]
![erp error](https://cloud.githubusercontent.com/assets/6859203/9299148/6e5c9caa-44d6-11e5-8e15-34ff2467a96d.png)
![erp error](https://cloud.githubusercontent.com/assets/6859203/9299163/b0d1a9b8-44d6-11e5-804d-8dfbda16cdd6.png)

**Comment by rmehta** [comment]
@prash4, the user that you use to run the API does not have permission to create Customer.

**Comment by prash4** [comment]
Hello,

 

The user which we are using , is the admin so we have all the permission .

**Comment by rmehta** [comment]
The error message is clearly about the permission. Can you check again? Something may have changed.

**Comment by prash4** [comment]
![erp user pemissiom](https://cloud.githubusercontent.com/assets/6859203/9299677/f3a1f31a-44db-11e5-88f5-bedc41fb036d.png)

Please see the attached photo , the user has all the permissions
