### ISSUE TITLE
Naming Series not showing up

### ISSUE THREAD

**Issue by zapirolabs** [frappe/erpnext#38759]
### Information about bug

Hi, I just started learning to use ERPNext, and one of the things I want to explore is Naming Series, however when I search it in the AwesomeBar, its not showing up, what could be the problem? I attached screenshot below.

![image](https://github.com/frappe/erpnext/assets/116142085/bb6f2459-777c-4c6d-9880-dd0ccb518d1b)

### Module

HR

### Version

Frappe - 15.5.0
ERPNext - 15.6.1

### Installation method

manual install

**Comment by s-aga-r** [comment]
@hellofathul [here](https://docs.erpnext.com/docs/user/manual/en/document-naming-settings) is the documentation for `Document Naming Settings`.
