### ISSUE TITLE
Enhancement: 3-State Business

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#3881]
I believe that the Tax Number / ID actually has to be moved from Customer to the Address. This is because a company could have different addresses. Example: We get an order from an Austrian company, they want us to deliver the goods to their Romanian factory but have Austria as the Billing Address. However the invoice is sent to Serbia for processing. Similarly we have customers in Germany who have logistics centers in Italy so Billing is Germany and Delivery is Italy while they again also have a different financial services company. This also means that weather Taxes are applied or not depends on the shipping address and not on the Company address. Interesting discussion to be had here!

**Comment by citizen-khan** [comment]
I think is a very good idea. If we look at how we have to determine what VAT is applicable, if any we have to consider all these points or ideally erpnext needs to consider them all:

1) What is being sold?
2) Is it a product or a service?
3) What are the rules on where the VAT is applied ie is it based on the place of supply (your businesses  fulfilment centre) or on the destination address (the customer's destination address)?
4) When you've got to 3 then you can decide what the VAT rate is.
5) and whether the VAT Reverse charge rules are applied or not.

So along with the address the item being sold (product or service) needs to be properly configurable to allow erpnext to determine whether the VAT is charged on the place of supply or destination and whether it is subject to a reverse charge.

EU VAT is such a big area it really needs a dedicated setup ie when you are setting up the company if you choose an EU country you should be asked are you VAT Registered and if you are then you should get a customised Customer, Contacts & Stock Item screen which allow us to configure our stock correctly and set the appropriate Tax ID which can then be picked up based on our Stock Item configuration.

There may be other considerations of VAT that I haven't considered or rules that differ in other countries within the EU which may involve more decision levels.

**Comment by rmehta** [comment]
Already coming as part of #3536
