### ISSUE TITLE
When canceling and modifying any DocType !

### ISSUE THREAD

**Issue by hassan-youssef** [frappe/erpnext#38816]
### Information about bug

When canceling and modifying any DocType, for example, a sales invoice or purchase order
Then 2 DocType will remain
1 original 0032
2 Amended 0032-1
* When Deleted DocType original 0032
And create a new sales invoice whose number will be 0032. Why!
I now have a new sales invoice number 0032 and an amended invoice that has nothing to do with the old one, number 0032-1.

### Module

accounts, stock, buying, selling, manufacturing

### Version

ERPNext: v15.2.0 (version-15)

Frappe Framework: v15.1.0 (version-15)

### Installation method

manual install

**Comment by ankush** [comment]
@hassan-youssef 

Few things:
1. Invoices should never be deleted as most half-decent accounting standards don't allow doing so.
2. You can control how naming is done for amended documents from `document naming settings` -> `amend naming`. It has two options adding amend counter like `-1` or just using next number in naming series like `xx-001`, `xx-002` etc

**Comment by hassan-youssef** [comment]
@ankush But this Amended From is not correct in this case
When the new one is Cancelled, it is not allowed to be modified. Is this true?
Please implement it to shake this big problem

**Comment by ankush** [comment]
@hassan-youssef I am unable to understand problem correctly. Can you maybe share one example with screenshots?

**Comment by hassan-youssef** [comment]
@ankush 
https://github.com/frappe/erpnext/assets/60713522/8ab7d80d-68d7-4f70-9727-96714793da9d
