### ISSUE TITLE
Sent to Subcontractor - Not possible to Send BOM item Qty Higher than Suncontracting Order Qty

### ISSUE THREAD

**Issue by jukkis69** [frappe/erpnext#38812]
### Information about bug

When trying to do a material transfer  to subcontractor - created from the subcontracting order - it is not possible to send higher qty than the qty specified by the subcontracting item BOM qty (* item qty).

It is very common that more BOM items are transferred to the subcontractor than required by the order )to their stock), and then the BOM qty is consumed by the subcontracting receipt. This is e.g. when electronic components come in fixed qty reels e.g. 3,000 pcs.

![image](https://github.com/frappe/erpnext/assets/105164376/7263bebe-9cc2-4cee-86ea-ce40d0e14d64)

By changing the Buying settings to 'Materials Transferred for Subcontract' it is possible to Submit the items.
![image](https://github.com/frappe/erpnext/assets/105164376/512dddc7-2adc-45ca-961b-796a99b83496)

BUT 'Materials Transferred for Subcontract' setting creates other problem when creating the Subcontracting Order Purchase Receipt - this will now not bring the 'Raw Materials Consumed based on the BOM for the subcontracted items.

### Module

buying

### Version

ERPNext: v14.29.1 (version-14)

Frappe Framework: v14.40.1 (version-14)

### Installation method

manual install

**Comment by s-aga-r** [comment]
@jukkis69 You need to set the `Over Transfer Allowance (%)` in Buying Settings.

![image](https://github.com/frappe/erpnext/assets/63660334/a5eebdc1-0ae0-4a25-b88a-ff9877bc405a)
