### ISSUE TITLE
Credit Note Booked Agst Paid Invoice receipt Not showing in Payment Reconciliation

### ISSUE THREAD

**Issue by Chourey30** [frappe/erpnext#38834]
### Information about bug

Credit Note Booked Agst Paid Invoice not receipted Not showing in Payment Reconciliation

Details attached for ready reference

[Credit Note Booked Agst Paid Invoice not receipted Not showing in Payment Reconciliation.docx](https://github.com/frappe/erpnext/files/13703979/Credit.Note.Booked.Agst.Paid.Invoice.not.receipted.Not.showing.in.Payment.Reconciliation.docx)

Thank You in Advance 

### Module

accounts

### Version

Frappe Framework: [v15.5.0]
ERPNext: [v15.6.1]
[Credit Note Booked Agst Paid Invoice not receipted Not showing in Payment Reconciliation.docx](https://github.com/frappe/erpnext/files/13703922/Credit.Note.Booked.Agst.Paid.Invoice.not.receipted.Not.showing.in.Payment.Reconciliation.docx)

[Credit Note Booked Agst Paid Invoice not receipted Not showing in Payment Reconciliation.docx](https://github.com/frappe/erpnext/files/13703926/Credit.Note.Booked.Agst.Paid.Invoice.not.receipted.Not.showing.in.Payment.Reconciliation.docx)
India Compliance: [v15.1.0]
Frappe HR: [v15.6.0]

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
Credit Note Booked Agst Paid Invoice not receipted Not showing in Payment Reconciliation

Attached details document for reference

Thank you in advance
```

**Comment by deepeshgarg007** [comment]
@Chourey30 Did you mean debit note. A debit note is booked against the Purchase Invoice. It should show up in the payment reconciliation tool. Closing this issue

Please reopen with more details.

**Comment by Chourey30** [comment]
Hi @deepeshgarg007 
[Uploading Credit.Note.Booked.Agst.Paid.Invoice.not.receipted.Not.showing.in.Payment.Reconciliation (1).docx…]()
 
It's Credit Note agst sales Invoice Only...

Pls Check the attached Document , I have attached all screen shot with details..

Issue is I f Payment Booked & also CN booked either of one ( Payment entry or CN )  should be shown open in Payment reconciliation 

Thanks
