### ISSUE TITLE
Material Transfer to Subcontract -V15

### ISSUE THREAD

**Issue by krishnanhemanth** [frappe/erpnext#38841]
### Information about bug

Hi
After clicking Material transfer form Subcontracting Order
In stock entry page
The Purchase Order Number is not being fetched as shown in the below Image
![no po number in stock entry](https://github.com/frappe/erpnext/assets/13927972/6afa4e7e-335d-4b75-b267-d6301d3eb779)
Neither is the Purchase order numbers showing up while clicking the column
Thanks and regards
Hemanth

### Module

stock

### Version

ERPNext: v15.6.1 (version-15)
Frappe Framework: v15.5.0 (version-15

### Installation method

manual install

**Comment by s-aga-r** [comment]
@krishnanhemanth This is not a bug.

Subcontracting Order gets mapped if you create a Stock Entry (Send to Subcontractor) against the Subcontracting Order (New flow of subcontracting). Purchase Order gets mapped when you create Stock Entry against Purchase Order (Old subcontracting flow).
