### ISSUE TITLE
Work order creation

### ISSUE THREAD

**Issue by nayan-flooid** [frappe/erpnext#38860]
### Information about bug

![image](https://github.com/frappe/erpnext/assets/154306926/1d4e8a97-72e4-4fd8-9c31-c6b52bce2818)
Getting this error while creating work order.

### Module

manufacturing

### Version

ERPNext: v14.54.2 (HEAD)
Frappe Framework: v14.59.0 (HEAD)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
When i try to submit its throwing me error.
Why this message is showing?
I am creating work order which has start date on august but not able to create with old date.
```

**Comment by rohitwaghchaure** [comment]
It seems that you have enabled the capacity planning in the Manufacturing Settings for 30 days which exceeding, either disable the capacity planning in the Manufacturing Settings or increase the Capacity Planning For (Days). For more details see the below image 

<img width="1337" alt="Screenshot 2023-12-21 at 2 42 32 PM" src="https://github.com/frappe/erpnext/assets/8780500/5f2f93bc-7066-40e4-98dd-d9454604dd4b">
