### ISSUE TITLE
Total allocated percentage for sales team should be 100 on Sales Order

### ISSUE THREAD

**Issue by JasonFu06** [frappe/erpnext#38868]
### Information about bug

![Q8(LOB~H00MN$3UV7WM{J 1](https://github.com/frappe/erpnext/assets/93484850/cbd75c26-4d25-4d3f-9a64-1da938a11206)
This error occurs when the sales order pulls multiple documents from the quotation.-(Get Items From).

### Module

selling

### Version

Frappe : 15.5.0
Erpnext : 15.5.1

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
The error code occurs in the def set_missing_values(source, target) part of def _make_sales_order(source_name, target_doc=None, customer_group=None, ignore_permissions=False) in the quotation. For version 15, the following code is added and an error occurs.

		for d in customer.get("sales_team") or []:
			target.append(
				"sales_team",
				{
					"sales_person": d.sales_person,
					"allocated_percentage": d.allocated_percentage or None,
					"commission_rate": d.commission_rate,
				},
			)
```

**Comment by philippmeixner** [comment]
I have the same issue. When creating a Sales Order from a Quotation, the Sales Person is listed twice in the same table (duplicate entry). It throws the error "Total allocated percentage for sales team should be 100". 

ERPNext: v14.32.1 (version-14)
Frappe Framework: v14.42.0 (version-14)
