### ISSUE TITLE
Server Error when adding Serial no and Batch no. from Stock Entry - Manufacture

### ISSUE THREAD

**Issue by sapl-santhosh** [frappe/erpnext#38874]
### Information about bug

The Serial no and batch bundle could not be added.
[serinoandbatchbundleerror.txt](https://github.com/frappe/erpnext/files/13724448/serinoandbatchbundleerror.txt)

### Module

stock

### App Versions
```
{
	"erpnext": "15.6.1",
	"frappe": "15.5.0",
	"hrms": "15.6.0",
	"india_compliance": "15.1.0",
	"payments": "0.0.1"
}

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

_No response_

**Comment by sapl-santhosh** [comment]
workflow as follows
1) create stock enry as manufacture with item and warehouse
2) choose add serial and batch bundle
3) import Serial and batch as csv file  (Also note previously in v14 if the batch is auto create selected in item doc, dont need to create manually batch. But here it asks for batch number to be included in the data import CSv)
4) With that too batch no. done
5) it is showing the above error

**Comment by rohitwaghchaure** [comment]
@sapl-santhosh Have you enabled the Skip Material Transfer in the Work Order? you don't need to add serial / batches in the manufacture entry if you have transferred it in the Work In Progress warehouse.

I have tried without Skip Material Transfer and it's working fine (see below GIF)
![manufacturing_entry](https://github.com/frappe/erpnext/assets/8780500/a4f561e9-9aec-4b8e-92a2-7598decc791c)

**Comment by rohitwaghchaure** [comment]
@sapl-santhosh We have identified and fixed the issue related to Serial Batch bundle adding using CSV. For more details please check below link
https://github.com/frappe/erpnext/pull/38950

**Comment by rohitwaghchaure** [comment]
@sapl-santhosh We have fixed the issue, kindly update your site and check
