### ISSUE TITLE
css stopped working

### ISSUE THREAD

**Issue by migs35323** [frappe/erpnext#38888]
### Information about bug

This is a kubernetes deployment.
Had this deployment in production for several months, i did upgraded it before and it was fine until randomly yesterday.

erpnext sudendly stopped being able to serve the css....
i am running erpnext in kubernetes using erpnext helm chart

i did run several times commands like bench build, migrate, ran jobs like fix permissions, 
nothing helped...
i also did end up update the chart to the latest version (and ran migrate) which didn't seem to do any effect..

please note that i never changed the default login page since we don't use that.
![erp1](https://github.com/frappe/erpnext/assets/92784574/867ea4fe-406d-4e75-b384-c39d42bfb6ae)

after running bench build/migrate:
![erp2](https://github.com/frappe/erpnext/assets/92784574/ea9e4cad-fe65-4af8-bd85-20ea1491b4d6)

### Module

other

### Version

$ bench version
erpnext 15.7.0
frappe 15.6.1

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
running some commands in bench sometimes outputs 2 errors
 
$bench build:
 Assets for Release /bin/sh: 1: Syntax error: "(" unexpected don't exist

bench update --apps erpnext
ERROR: Command 'basename $(git symbolic-ref -q HEAD)' returned non-zero exit status 1.

nginx container:
2023-12-20T16:07:02.832902367Z 10.42.3.10 - - [20/Dec/2023:16:07:02 +0000] "GET /assets/frappe/dist/css/website.bundle.HCJJCX4E.css HTTP/1.1" 404 184 "https://erp.<redacted>.com/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
```

**Comment by hhharsha36** [comment]
I am facing the same problem where none of the `.css` files in the home page load up and return a 404 error upon inspection.

I am using the same erpnext and frappe version as yours using a custom docker build image. I think there is a problem with the recent release of frappe bench.

**Comment by 0xD0M1M0** [comment]
Can you try to delete the docker containers, then the docker volumes with the long random strings (eg. 3d17aed2dab19fe1ea4cd13e6f3c22c286913fb191d4edee6f7). Then create the containers again. Fixed it on my system.

**Comment by migs35323** [comment]
i think i found something, maybe something to do with hardlinks/symlinks inside a pvc across pods, i tried to create and delete files from the assets folder trying to force the problem
the sites folder is a PVC with RWX, there is discrepancies in the directory across pods, heres a picture:


![pvc_rwx](https://github.com/frappe/erpnext/assets/92784574/421082d8-8c78-40bf-b8c2-a9704ffe7a4f)

**Comment by migs35323** [comment]
Finally fixed it, but i am guessing this will happen sometime later or there will be inconsistencies across pods in the future.

i think the problem started to happen when in a previous upgrade i did ran bench commands in one of the running pods, so, when running bench commands in a running pod (for example bench build in gunicorn pod) it link to folders outside of the volume (picture above shows in the left side frappe and erpnext are symlinks to home folder that exists only in that container/pod)
this created inconsistencies across the different deployments of the application
in this helm chart, there are several deployments. Each deployment is a part of the app, but every pod is (1 container) using the same docker image but running a a different entrypoint/command. 

All the deployments share the "sites" volume but each one has an internal copy of the frappe and erpnext "release"
by running bench update in gunicorn, it created symlinking/hardlinking to the /home/frappe..., the nginx pod still had the old app files.

so, here's how i did fix it:

1. stopped every container that mounts the sites pvc (scaled down deployments, its ok if you keep the statefulsets running)
2. grabbed the template for the migrate job, adapt it to rebuild the app
spec.template.spec.containers.[0].args
```
  bench --site all set-maintenance-mode on;
  bench --site all build;
  bench --site all clear-website-cache ;
  bench --site all set-maintenance-mode off;
```
(
NOTE, THE JOB SHOWS A WARNING WHICH SHOULD BE IT'S OWN ISSUE:
`Assets for Release /bin/sh: 1: Syntax error: "(" unexpected don't exist`
)
3. ran the job with no pods/containers attached, scale up deployments again and let them create it's linking


extra note, you can change the job arguments to run migrate, that might help

**Comment by migs35323** [comment]
Yep as a suspected, the issue is present again, after i scaled up the development and it created pods, it started to 404 on css resources at random again.

i scalled it down back and it seems to be able to serve the css again
i believe this is due to some volume inconsistency between gunicorn and nginx, i am going to troubleshoot a little more and provide some info later today

**Comment by hhharsha36** [comment]
@migs35323 I facing the same problem where the `.css` files are not loading.

I am using a custom docker production build script with additional apps. tried reinstalling the app, frappe build, even complete fresh install and nothing seemed to work :(

Any help would be appreciated if you can share your findings.

Below is the error message I am getting on the browser:
<img width="765" alt="image" src="https://github.com/frappe/erpnext/assets/28597188/47cc4a3b-7a1e-460f-a5c7-6dba3ef634ea">


Below is the custom Docker build file I use, can you please let me know if I did something wrong with the file?
```dockerfile
ARG PYTHON_VERSION=3.11.6
ARG DEBIAN_BASE=bookworm
FROM python:${PYTHON_VERSION}-slim-${DEBIAN_BASE} AS base

COPY resources/nginx-template.conf /templates/nginx/frappe.conf.template
COPY resources/nginx-entrypoint.sh /usr/local/bin/nginx-entrypoint.sh
COPY resources/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY resources/supervisord.conf /etc/supervisord.conf
COPY nvm.sh /nvm.sh

ARG WKHTMLTOPDF_VERSION=0.12.6.1-3
ARG WKHTMLTOPDF_DISTRO=bookworm
ARG WKHTMLTOPDF_PGSQL_VERSION=16
# ARG NODE_VERSION=18.18.2
ARG NODE_VERSION=21.4.0
ENV NVM_DIR=/home/frappe/.nvm
ENV PATH ${NVM_DIR}/versions/node/v${NODE_VERSION}/bin/:${PATH}

RUN useradd -ms /bin/bash frappe \
    && apt-get update \
    && apt-get install --no-install-recommends -y \
    curl \
    git \
    vim \
    nginx \
    gettext-base \
    # weasyprint dependencies
    libpango-1.0-0 \
    libharfbuzz0b \
    libpangoft2-1.0-0 \
    libpangocairo-1.0-0 \
    # For backups
    restic \
    # MariaDB
    mariadb-client \
    ## Postgres
    libpq-dev \
    #postgresql-client \
    # GPG & other custom packages
    #gnupg \
    ffmpeg libsm6 libxext6 libmagic-dev libgl1 gnupg2 wget vim nano \
    # For healthcheck
    wait-for-it \
    jq \
    # NodeJS
    && mkdir -p ${NVM_DIR} \
    && cat /nvm.sh | bash \
    && . ${NVM_DIR}/nvm.sh \
    && nvm install ${NODE_VERSION} \
    && nvm use v${NODE_VERSION} \
    && npm install -g yarn \
    && nvm alias default v${NODE_VERSION} \
    && rm -rf ${NVM_DIR}/.cache \
    && echo 'export NVM_DIR="/home/frappe/.nvm"' >>/home/frappe/.bashrc \
    && echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm' >>/home/frappe/.bashrc \
    && echo '[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion' >>/home/frappe/.bashrc \
    # Install wkhtmltopdf with patched qt
    && if [ "$(uname -m)" = "aarch64" ]; then export ARCH=arm64; fi \
    && if [ "$(uname -m)" = "x86_64" ]; then export ARCH=amd64; fi \
    && downloaded_file=wkhtmltox_${WKHTMLTOPDF_VERSION}.${WKHTMLTOPDF_DISTRO}_${ARCH}.deb \
    && curl -sLO https://github.com/wkhtmltopdf/packaging/releases/download/$WKHTMLTOPDF_VERSION/$downloaded_file \
    && apt-get install -y ./$downloaded_file \
    && rm $downloaded_file \
    # Clean up
    && rm -rf /var/lib/apt/lists/* \
    && rm -fr /etc/nginx/sites-enabled/default \
    && pip3 install frappe-bench \
    # Custom install Python Pillow Package
    && pip3 install --upgrade pip \
    # Fixes for non-root nginx and logs to stdout
    && sed -i '/user www-data/d' /etc/nginx/nginx.conf \
    && ln -sf /dev/stdout /var/log/nginx/access.log && ln -sf /dev/stderr /var/log/nginx/error.log \
    && touch /run/nginx.pid \
    && chown -R frappe:frappe /etc/nginx/conf.d \
    && chown -R frappe:frappe /etc/nginx/nginx.conf \
    && chown -R frappe:frappe /var/log/nginx \
    && chown -R frappe:frappe /var/lib/nginx \
    && chown -R frappe:frappe /run/nginx.pid \
    && chmod 755 /usr/local/bin/nginx-entrypoint.sh \
    && chmod 644 /templates/nginx/frappe.conf.template
    #&& npx update-browserslist-db@latest \
    #&& npx browserslist@latest --update-db

RUN curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg \
    && sh -c 'echo "deb https://apt.postgresql.org/pub/repos/apt ${WKHTMLTOPDF_DISTRO}-pgdg main" > /etc/apt/sources.list.d/pgdg.list' \
    && apt-get update \
    && apt-get install postgresql-contrib-${WKHTMLTOPDF_PGSQL_VERSION} postgresql-client-${WKHTMLTOPDF_PGSQL_VERSION} postgresql-client-common -y
    #&& apt-get -y install supervisor \
    #&& apt-get install ffmpeg libsm6 libxext6 libmagic-dev libgl1 gnupg2 wget vim nano -y

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]


FROM base AS builder

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
    # For frappe framework
    wget \
    # For psycopg2
    libpq-dev \
    # Other
    libffi-dev \
    liblcms2-dev \
    libldap2-dev \
    libmariadb-dev \
    libsasl2-dev \
    libtiff5-dev \
    libwebp-dev \
    redis-tools \
    rlwrap \
    tk8.6-dev \
    cron \
    # For pandas
    gcc \
    build-essential \
    libbz2-dev \
    && rm -rf /var/lib/apt/lists/*

# apps.json includes
ARG APPS_JSON_BASE64
RUN if [ -n "${APPS_JSON_BASE64}" ]; then \
    mkdir /opt/frappe && echo "${APPS_JSON_BASE64}" | base64 -d > /opt/frappe/apps.json; \
  fi

USER frappe

ARG FRAPPE_BRANCH=version-15
ARG FRAPPE_PATH=https://github.com/frappe/frappe
#ARG FRAPPE_BRANCH=develop
#ARG FRAPPE_PATH=https://github.com/hhharsha36/frappe.git
RUN export APP_INSTALL_ARGS="" && \
  if [ -n "${APPS_JSON_BASE64}" ]; then \
    export APP_INSTALL_ARGS="--apps_path=/opt/frappe/apps.json"; \
  fi && \
  bench init ${APP_INSTALL_ARGS}\
    --frappe-branch=${FRAPPE_BRANCH} \
    --frappe-path=${FRAPPE_PATH} \
    --no-procfile \
    --no-backups \
    --skip-redis-config-generation \
    #--no-auto-update \
    --verbose \
    /home/frappe/frappe-bench && \
  cd /home/frappe/frappe-bench && \
  echo "{}" > sites/common_site_config.json && \
  find apps -mindepth 1 -path "*/.git" | xargs rm -fr && \
  pip3 install 'python-barcode~=0.15.1' --force-reinstall && \
  pip3 install 'Pillow~=10.0.1' --force-reinstall && \
  pip3 install 'opencv-python-headless~=4.8.1.78' --force-reinstall && \
  mkdir -p /home/frappe/frappe-bench/backup
  #bench build --force

FROM base as backend

USER frappe

COPY --from=builder --chown=frappe:frappe /home/frappe/frappe-bench /home/frappe/frappe-bench

WORKDIR /home/frappe/frappe-bench

VOLUME [ \
  "/home/frappe/frappe-bench/sites", \
  "/home/frappe/frappe-bench/sites/assets", \
  "/home/frappe/frappe-bench/logs" \
  "/home/frappe/frappe-bench/backup" \
]

CMD [ \
  "/home/frappe/frappe-bench/env/bin/gunicorn", \
  "--chdir=/home/frappe/frappe-bench/sites", \
  "--bind=0.0.0.0:8000", \
  "--threads=4", \
  "--workers=2", \
  "--worker-class=gthread", \
  "--worker-tmp-dir=/dev/shm", \
  "--timeout=120", \
  "--preload", \
  "frappe.app:application" \
]
```

**Comment by deepeshgarg007** [comment]
@migs35323 This looks more like a deployment issue and not a system bug. Closing this ticket

**Comment by hyperdatavn** [comment]
> I am facing the same problem where none of the `.css` files in the home page load up and return a 404 error upon inspection.
> 
> I am using the same erpnext and frappe version as yours using a custom docker build image. I think there is a problem with the recent release of frappe bench.

I facing the same issues with u @hhharsha36 , appreciate if u can share a solution here when u can resolve it

**Comment by CarlosChiari** [comment]
This is clearly NOT a deployment issue. If Frappe/erpnext is to be taken seriously, this issue has to be addressed, fully explained, and have a clear solution.

**Comment by migs35323** [comment]
> @migs35323 This looks more like a deployment issue and not a system bug. Closing this ticket

Please re-open, i am using the official helm chart, and i believe the same exact issue happens with the docker deployment, i didnt tested that, but since i did seen this threads in some other places and other people having the same issue, i believe this should be noticed and done something about it..
the docker and helm deployments are both basically the same thing (they use the same images and i believe the chart is heavily based of the docker compose)
every-time my pods/containers are going down or something changes this issue happens again due to some decisions by frappe/erpnext...
as i went trough a troubleshooting process i explained in this issue my findings..
and i did find that the problem at least in my deployment, lies in how frappe/erpnext designed the system on how they are mapping static\not static data...

**Comment by CarlosChiari** [comment]
@migs35323 What I found is that when I add an app, using bench --site somesite install-app someapp, it deletes the frappe and erpnext directories at assets/, so the problem arises; and that the solution that works for me is building again those apps resources using bench build. Also, I need to use --hard-link for it to work for me.  So, to fix it meanwhile, I use these commands after the problem arises:
bench build --app frappe --hard-link --production
bench build --app erpnext --hard-link --production.

Regards.

**Comment by hyperdatavn** [comment]
I found a workaround solution is stop backend container, remove it and docker compose up again. But it will have a down time once deploy.
