### ISSUE TITLE
Project field filters broken in all DocTypes

### ISSUE THREAD

**Issue by SvbZ3r0** [frappe/erpnext#38889]
### Information about bug

The `project` field used to filter away "cancelled" and "closed" projects. However, now the fields show all Projects, cancelled or not. I have tested in Sales Order, Delivery Note, Purchase Order, and Purchase Receipt.
In Sales Order, there is an additional query to filter by Customer. This is also not applied. Setting this filter manually in the browser console shows the `Filters Applied for Customer = your_customer` at the bottom of the dropdown, but the actual results show all Projects regardless of Customer (or status).
The `cost_centre` field is set to automatically fetch the default Cost Centre of the Project, but this doesn't work either. 
Moreover, in Sales Order, I get notifications that the Cost Centre for each row in the `items` table has been set to the default Cost Centre of the Project, but Sales Order Item doesn't actually have a `cost_centre` field.

I have uninstalled all custom apps in case the error was introduced from elsewhere, but the error persists on a vanilla install.

All of this used to work until a while ago. I'm not sure what broke this. (Edit: I checked in an old v14 environment and it doesn't work on that too. Maybe I imagined the whole thing?)

~~Sorry for no pics. Current test environment has production data. Will upload pics asap.~~ Pics in PR

### Module

projects

### Version

erpnext 15.5.0
frappe 15.4.1
india_compliance 15.0.4 (uninstalled)
payments 0.0.1
print_designer 1.0.0
textiles 0.0.1 (uninstalled)
erpnext_plus 0.0.1 (uninstalled)

### Installation method

manual install

**Comment by ruthra-kumar** [comment]
Partially fixed by https://github.com/frappe/erpnext/pull/39212

**Comment by SvbZ3r0** [comment]
@ruthra-kumar this is not completed. Your PR doesn't affect this issue. Closed and Completed Projects still show up when they absolutely should not. Customer filters should be applied, but they are not.
I understand you could go into every single Doctype and set these filters individually, but that defeats the point of Contollers. At the very least, filters for "Completed" and "Cancelled" Projects should be set at the Controller level.

**Comment by ruthra-kumar** [comment]
@SvbZ3r0 
https://github.com/frappe/erpnext/pull/39402 should address the broken query controller.
