### ISSUE TITLE
[ BUG ] Problem in Outgoing Email Settings User and Password (character limited ) 

### ISSUE THREAD

**Issue by negini** [frappe/erpnext#3889]
There is bug in SMTP setting of erpnext , when we use some SMTP service like http://elasticemail.com/ , user and password in about 40 character , but in erpnext not accept 40 character for user or password and we can't use most third party SMTP service in erpnext .

**Comment by anandpdoshi** [comment]
That's strange. ERPNext allows for up to 255 characters.

**Comment by negini** [comment]
may be new version support 255 characters , i use version 4.5.2 , any one can update my erpnext to last version ?
