### ISSUE TITLE
critical : not access restriction in attached file to customer/lead/quotation /.... 

### ISSUE THREAD

**Issue by negini** [frappe/erpnext#3890]
There is critical problem in erpnext , when we attach file to any customer / lead or .... , any other staff login to erpnext can delete that file and manager can't restrict  access of staff to only attach file , and can't delete old file , so any one can delete file attached to customer :( .

**Comment by revant** [comment]
Now the files can be attached as private

**Comment by vijaysingh0507** [comment]
Even though the Files are private the Files can be viewed by any logged in user even though they don't have access on the module.
