### ISSUE TITLE
search by ID

### ISSUE THREAD

**Issue by thomasburq** [frappe/erpnext#3891]
searching PO/SO/Invoices by ID is not possible in the search field. The default filter when hitting Enter is 'Supplier name'/'Customer name' and I cannot add ID in the search fields when trying to customize the form, I get the following error:

![po search2](https://cloud.githubusercontent.com/assets/13672618/9296920/6fe63f2a-44c9-11e5-9cda-d986f268f7f8.PNG)

**Comment by MaxMorais** [comment]
Doctypes search by the ID ever, the ID field for Doctypes is "name"

2015-08-16 23:19 GMT-03:00 thomasburq <notifications@github.com>:

> searching PO/SO/Invoices by ID is not possible in the search field. The
> default filter when hitting Enter is 'Supplier name'/'Customer name' and I
> cannot add ID in the search fields when trying to customize the form, I get
> the following error:
>
> [image: po search2]
> <https://cloud.githubusercontent.com/assets/13672618/9296920/6fe63f2a-44c9-11e5-9cda-d986f268f7f8.PNG>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/frappe/erpnext/issues/3891>.
>



-- 

Best Regards.

Maxwell Morais
Python Developer powered by Webnotes framework <3
+55 11 954329659

**Comment by thomasburq** [comment]
Ok but I still cannot add 'name' to the search fields (same error).

**Comment by MaxMorais** [comment]
You dont need do it, it is a standard behavior

2015-08-17 0:06 GMT-03:00 thomasburq <notifications@github.com>:

> Ok but I still cannot add 'name' to the search fields (same error).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/frappe/erpnext/issues/3891#issuecomment-131664961>.
>



-- 

Best Regards.

Maxwell Morais
Python Developer powered by Webnotes framework <3
+55 11 954329659

**Comment by thomasburq** [comment]
But it is not working on my fresh install and it looks like the issue can be replicated: https://discuss.erpnext.com/t/search-purchase-sales-orders-by-id/7016/3

**Comment by strixaluco** [comment]
Can't replicate on latest v8

**Comment by strixaluco** [comment]
Closing as of now. Please reopen if can reproduce.
