### ISSUE TITLE
Parent Menu not visible in website -V15

### ISSUE THREAD

**Issue by krishnanhemanth** [frappe/erpnext#38929]
### Information about bug

Hi
The Parent menu is not getting displayed in the website
The below image shows the Navbar with the parent menu Products
![v1](https://github.com/frappe/erpnext/assets/13927972/9361c18e-3d96-43ef-be4e-34899fe2978a)
the next image shows the homepage without the parent menu
![v2](https://github.com/frappe/erpnext/assets/13927972/9c60a200-54dd-4ecb-a45e-eed2b6b9583d)
Thanks and Regrads

### Module

other

### Version

ERPNext: v15.7.0 (version-15)
Frappe Framework: v15.6.1 (version-15)

### Installation method

None

**Comment by s-aga-r** [comment]
@krishnanhemanth Make sure to install the [webshop](https://github.com/frappe/webshop) app if your issue is related to the E-commerce module. The e-commerce module has separated from ERPNext as a new app webshop.

**Comment by krishnanhemanth** [comment]
Hi
The Webshop app is already installed.
The Navbar option for menu is in the website settings and not in webshop

**Comment by s-aga-r** [comment]
@krishnanhemanth Try to set a URL for Products Website Settings.

![image](https://github.com/frappe/erpnext/assets/63660334/6cadb29d-f74f-4d3e-8a7c-0e18210ea3e3)

**Comment by krishnanhemanth** [comment]
Hi
The link on here is throwing an error
![here error](https://github.com/frappe/erpnext/assets/13927972/73edf935-33ff-44dc-affd-0144147fc128)
Regards
Hemanth

**Comment by krishnanhemanth** [comment]
Hi
"Try to set a URL for Products Website Settings."
The above is not possible because the system allows entry in either url or Parent label
If i try to enter anything in the url column, then the Parent label goes empty
Thanks and Regards

**Comment by s-aga-r** [comment]
@krishnanhemanth Just remove the `Parent Label` from your Products row. 

![image](https://github.com/frappe/erpnext/assets/63660334/07f70398-2562-485a-a80b-2019395dd4f3)

![image](https://github.com/frappe/erpnext/assets/63660334/9c570a65-f91c-4184-8f4e-e29689c1fc66)

**Comment by krishnanhemanth** [comment]
Dear s-aga-r
Thanks for the reply
Its working now
Thanks again
