### ISSUE TITLE
Journal Entry yyyyyyy: Either debit or credit amount is required for xxxxx

### ISSUE THREAD

**Issue by convergenix** [frappe/erpnext#38933]
### Information about bug

Just upgraded from version 13 to version 14. I get this error "Journal Entry yyyyyyy: Either debit or credit amount is required for xxxxxsometimes when I am trying submit a journal, sales invoice or purchase invoice

### Module

stock, buying, selling

### Version

ERPNext: v14.56.0 (version-14)
Frappe Framework: v14.60.0 (version-14)

### Installation method

manual install

**Comment by ruthra-kumar** [comment]
@convergenix Could you post the traceback.

**Comment by ruthra-kumar** [comment]
Closing this issue. Re-open if issue persists in latest v14 or v15.
