### ISSUE TITLE
Cannot cancel Sales Invoice with Serial and Batch Bundle (circular dependence)

### ISSUE THREAD

**Issue by carstenblt** [frappe/erpnext#38975]
### Information about bug

When trying to cancel an invoice, the dialog suggest to delete the linked Serial and Batch Bundles of the invoice items. However, their deletion fails because they are linked to the invoice that should be deleted. Circular dependency.

### Module

selling

### Version

ERPNext: v15.8.0
Frappe Framework: v15.7.0

### Installation method

None

**Comment by rohitwaghchaure** [comment]
@carstenblt we have fixed the issue, Kindly update your site and check
