### ISSUE TITLE
Batch selector: local decimal separator bug

### ISSUE THREAD

**Issue by carstenblt** [frappe/erpnext#39001]
### Information about bug

https://github.com/frappe/erpnext/assets/11031419/e75551a6-c6c3-4f02-bebd-f8544ac49eec

When opening the batch selector dialog from a Stock Entry using the "Add Serial / Batch No" button, the required qty is first shown correctly with an English decimal point. Any interaction that triggers a rerendering will result in a wrong qty with the decimal point removed and a German decimal comma added, however at the wrong position. Additionally as you can see in this case, another batch line is added.

### Module

stock

### Version

ERPNext: v15.8.1
Frappe Framework: v15.7.0

### Installation method

None

**Comment by rohitwaghchaure** [comment]
@carstenblt 

This is not an issue, the 1.4 means 14 in the "#.###,##" format. So when you change the qty system fetch the batches as per the mentioned qty.

If you type 1.4 in the qty field of the stock entry, it will change it to 14,###
![qty_converter](https://github.com/frappe/erpnext/assets/8780500/a2259407-061b-456f-8933-0cf3af5d596a)

**Comment by carstenblt** [comment]
@rohitwaghchaure the correct qty from the item line in the Stock Entry the dialog is opened from however should be 1.4 and not 14.
