### ISSUE TITLE
Web Form "Issue" - Priority Picker not working

### ISSUE THREAD

**Issue by 0xD0M1M0** [frappe/erpnext#39010]
### Information about bug

The priority link in the file "erpnext/tree/version-15/erpnext/support/web_form/issues/issues.json" is not working. That means on the website the priority cannot be selected and due to translations into other languages, the form cannot be send, if the "Issue Priority" is not exactly "Medium". Creating an "Issue Priority" with "Medium" returns then the error "Message / Not permitted". 

### Module

portal

### Version

erpnext 15.8.0
frappe 15.7.0
hrms 15.7.0

### Installation method

docker

**Comment by s-aga-r** [comment]
@0xD0M1M0 Please share the browser console log.

**Comment by 0xD0M1M0** [comment]
![grafik](https://github.com/frappe/erpnext/assets/76812428/57db7e58-155f-4d65-bd95-58b4010f3104)

The selector is partically working in Firefox with newly created "Prio Typs". Old ones are not shown. Chrome is not working at all.

**Comment by s-aga-r** [comment]
@0xD0M1M0 All `Issue Priority` is visible to me (chrome).

![image](https://github.com/frappe/erpnext/assets/63660334/f2fec426-2e5b-451f-be0f-2da333c183d6)

**Comment by 0xD0M1M0** [comment]
I created a new webform and the field is working in the new web form.

I close the issue, due to the fact, that it is not reproducible.
