### ISSUE TITLE
batches not showing up in search_link/erpnext.controllers.queries.get_batch_no

### ISSUE THREAD

**Issue by carstenblt** [frappe/erpnext#39011]
### Information about bug

In a batch selection dropdown the query to `/api/method/frappe.desk.search.search_link` with parameters

```
txt: 
doctype: Batch
reference_doctype: 
query: erpnext.controllers.queries.get_batch_no
filters: {"item_code":"xyz","warehouse":"xyz"}
```

does not return any batches. The item queried is a manufacturing item with several active batches. E.g. the following batch should show up but does not:

```
{
  "name": "xyz-00280",
  "owner": "xyz",
  "creation": "2023-12-29 00:36:41.962099",
  "modified": "2023-12-29 00:36:42.374250",
  "modified_by": "xyz",
  "docstatus": 0,
  "idx": 2,
  "disabled": 0,
  "use_batchwise_valuation": 1,
  "batch_id": "xyz-00280",
  "item": "xyz",
  "item_name": "xyz",
  "manufacturing_date": "2023-12-29",
  "batch_qty": 1,
  "stock_uom": "kg",
  "expiry_date": "2024-09-24",
  "reference_doctype": "Stock Entry",
  "reference_name": "MAT-STE-2023-04249",
  "qty_to_produce": 0,
  "produced_qty": 0,
  "doctype": "Batch",
}
```

### Module

stock

### Version

ERPNext: v15.8.1
Frappe Framework: v15.7.0

### Installation method

None

**Comment by rohitwaghchaure** [comment]
@carstenblt Batch No field in the stock entry child table is not editable so this method shouldn't be trigger. Can you share the steps to replicate the issue

**Comment by carstenblt** [comment]
@rohitwaghchaure I am adding an item to a Sales Invoice and use the batch selector dialog. This method triggers when you click/type in the batch field to select a batch to be added to the SABB.

After trying a few things I believe that **batches that were manufactured by a Stock Entry do not show up in the list**. Batches that were created manually with stock added by a Purchase Invoice show up.

**Comment by carstenblt** [comment]
When adding a SABB manually using the doctype's form, there is indeed another query used:
```
txt:
doctype: Batch
ignore_user_permissions: 0
reference_doctype: Serial and Batch Entry
filters: {"item":"xyz","disabled":0}
```

This returns the batches correctly.

**Comment by rohitwaghchaure** [comment]
@carstenblt I have tested on latest version of v15 and it's working fine.

Also in the below batch which you've shared earlier, why the produced_qty is showing as zero? if the quantity is zero then system won't show the respective batch in the dropdown
```
{
  "name": "xyz-00280",
  "owner": "xyz",
  "creation": "2023-12-29 00:36:41.962099",
  "modified": "2023-12-29 00:36:42.374250",
  "modified_by": "xyz",
  "docstatus": 0,
  "idx": 2,
  "disabled": 0,
  "use_batchwise_valuation": 1,
  "batch_id": "xyz-00280",
  "item": "xyz",
  "item_name": "xyz",
  "manufacturing_date": "2023-12-29",
  "batch_qty": 1,
  "stock_uom": "kg",
  "expiry_date": "2024-09-24",
  "reference_doctype": "Stock Entry",
  "reference_name": "MAT-STE-2023-04249",
  "qty_to_produce": 0,
  "produced_qty": 0,
  "doctype": "Batch",
}

```
