### ISSUE TITLE
Bank Reconciliation doesn't change status

### ISSUE THREAD

**Issue by hkmj-erp** [frappe/erpnext#39041]
### Information about bug

When we reconcile a Journal Entry using Bank Reconciliation Tool.
1. It sets clearance date in Journal Entry.
![image](https://github.com/frappe/erpnext/assets/142988840/dbc88587-7469-453c-a7c1-8246723fa2e6)

2. In Bank Transaction document also, it allocates the amount.
![image](https://github.com/frappe/erpnext/assets/142988840/f3701cc0-9134-452b-965f-2f57bb5ebbcd)

3. Also it shows the status as Reconciled, but the field "Status" remains "Unreconciled".
![image](https://github.com/frappe/erpnext/assets/142988840/415715e2-295b-47c8-8733-f96b79521f08)

Please help.

### Module

accounts

### Version

Frappe Framework: v15.6.1
ERPNext: v15.7.0

### Installation method

None

**Comment by schmutzfuss42** [comment]
same here ...

**Comment by ruthra-kumar** [comment]
Should be fixed by https://github.com/frappe/erpnext/pull/39196
