### ISSUE TITLE
attemp to install erpnext

### ISSUE THREAD

**Issue by sagardspeed2** [frappe/erpnext#39051]
### Information about bug

I created new site and want to install erpnext on it, but getting error like, 

You're attempting to install ERPNext version 15 with Frappe version 16. This is not supported and will result in broken install. Switch to correct branch before installing

### Module

other

### Version

doppio 0.0.1
erpnext 14.x.x-develop
frappe 15.x.x-develop
india_compliance 16.0.0-dev
payments 0.0.1

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
You're attempting to install ERPNext version 15 with Frappe version 16. This is not supported and will result in broken install. Switch to correct branch before installing.
```

**Comment by emushene** [comment]
how did you resolve this sir

**Comment by agritheory** [comment]
@emushene Try the `--branch` argument like this `bench get-app erpnext --branch version-15`
