### ISSUE TITLE
Issue with Payment Entry json.

### ISSUE THREAD

**Issue by ajiragroup** [frappe/erpnext#39070]
### Information about bug

We wanted to modify the default naming series for Payment entry for the year 2024. Since today is Jan1, we thought today is the best day to start it. We tried by editing the naming series field in customize form. But the numbering started at 00771. It should have started at 00001. Default naming series is ACC-PAY-.YYYY.-. We needed to shorten it to PAY-.YY.-. Now the first payment entry of 2024 is PAY-24-00771.

So we turned on developer mode and went to edit the doctype and edited the series field's option to PAY-.YY.-

Now, when making payment entry, we still see the old default series ACC-PAY-.YYYY.-

Upon inspecting the json file, option is update to PAY-.YY.- But the payment entry form does not reflect the new option. 

Also, upon rechecking the Payment Entry form via customize form, we still see ACC-PAY-.YYYY.- But via edit doctype, we see PAY-.YY.-

Strange!

Doctype:
![image](https://github.com/frappe/erpnext/assets/108009061/7d878c8b-a904-464b-9e44-161b9aa3aa07)

Customize Form:
![image](https://github.com/frappe/erpnext/assets/108009061/5aa51a09-3754-4dde-a6a2-ede39444a513)

Payment Entry form after editing doctype:
![image](https://github.com/frappe/erpnext/assets/108009061/999b9aad-d9d7-41a5-ba2d-5a0d90d1a497)

Payment Entry id (number) we get after multiple(4/5) tests is :
![image](https://github.com/frappe/erpnext/assets/108009061/c66e17fd-f73a-476f-9f30-1cfd13426c4a)

### Module

accounts

### Version

erpnext 15.8.3
frappe 15.7.0
payments 0.0.1

### Installation method

manual install

**Comment by ankush** [comment]
You shouldn't be editing doctype or customizing for naming series. It's done from https://docs.erpnext.com/docs/user/manual/en/document-naming-settings 

It also has option to reset counter if it's been consumed. I can't really tell how it was consumed without looking at data.

**Comment by ajiragroup** [comment]
I understand, we should not be editing doctype. But if we did, the form should show the same value irrespective of where we open it from, be it Customize form or Doctype. The issue here is different data loaded via different editor.

We later found the Document Naming settings and updated it. We are still checking for any issues there.
