### ISSUE TITLE
[Feature request] Minimum password requirements

### ISSUE THREAD

**Issue by thomasburq** [frappe/erpnext#3907]
Hello,

An instance of erpnext will most certainly contain sensitive information regarding finance, orders etc. of the company, I think Admins should be able to set minimum requirement for user passwords (like minimum 1 letter, 1 number, 1 special character) when they set up the 1st time or when they change it.

**Comment by anandpdoshi** [comment]
Fixed via https://github.com/frappe/frappe/pull/1802

The feature suggests password strength in update password page, but allows you to set weak passwords if you still want to
