### ISSUE TITLE
General Ledger One Account Merging with another Account without you merging them

### ISSUE THREAD

**Issue by hassan-youssef** [frappe/erpnext#39078]
### Information about bug

![Screenshot from 2024-01-02 00-49-22](https://github.com/frappe/erpnext/assets/60713522/d7ea7e72-b479-4ed5-8ec4-2ea8a662a20c)

### Module

accounts

### Version

ERPNext: v14.57.0 (version-14)

Frappe Framework: v14.61.0 (version-14)

Frappe HR: v14.21.0 (version-14)

### Installation method

manual install

**Comment by rtdany10** [comment]
Open your chart of accounts, click on the 3 dots (menu) and rebuild the tree.

**Comment by hassan-youssef** [comment]
@rtdany10 Thank you

**Comment by rtdany10** [comment]
You're welcome, please close the issue if resolved
