### ISSUE TITLE
Batch and serial feature ISSUE

### ISSUE THREAD

**Issue by baladante94** [frappe/erpnext#39077]
### Information about bug

Having Problem with the new batch feature. why is it asking when i disabled batch for outward is not needed. When the selector is disabled i get batch is needed error. Also it is not fetching the rate of my item for that particular batch. Need this to be fixed immediately. imagine a Supermarket scenario when they scan using barcode in POS they cannot choose batch for all the items.
![Stock Settings - Google Chrome 1_1_2024 8_00_12 PM](https://github.com/frappe/erpnext/assets/109241162/2d9b38c1-8ea2-4ed5-a747-07db8e2d42d3)
![Stock Settings - Google Chrome 1_1_2024 8_01_37 PM](https://github.com/frappe/erpnext/assets/109241162/99e5ee21-1f82-4e2b-9c7c-1cdd1188bf4a)
![Stock Settings - Google Chrome 1_1_2024 8_02_42 PM](https://github.com/frappe/erpnext/assets/109241162/f9f00806-12ff-45a9-9e5c-b171517d8d64)
![Stock Settings - Google Chrome 1_1_2024 8_03_55 PM](https://github.com/frappe/erpnext/assets/109241162/55762673-e2a7-48c9-a7ad-d581b1169747)

### Module

accounts, stock, buying, selling

### Version

Frappe - v15.5.0 
ERPNext - v15.8.3 

### Installation method

manual install

**Comment by rohitwaghchaure** [comment]
@balayuvabe We have [fixed](https://github.com/frappe/erpnext/pull/39114) the issue and we'll release it in the next release cycle (https://github.com/frappe/erpnext/pull/39114)
