### ISSUE TITLE
Stock Reservation against Work Order

### ISSUE THREAD

**Issue by satisharalkar** [frappe/erpnext#39080]
### Information about bug

Hi Team,

We are working on ERPNext: v15.7.0 (version-15)

We wanted to reserve raw material against Sales order as per finished product BOM. Following process we have followed as per documents.

We have created BOM for FG item and for FG, we need to buy RM from Supplier.

In Stock Setting We have followed below setting.

<img width="1338" alt="image" src="https://github.com/frappe/erpnext/assets/17386166/7864da13-7862-442e-ae46-c35e9c29e8f8">

- We have created first Sales order
- Created Production plan against Sales Order.
- From Production Plan, created work order and Material Request.
- From Material Request, created Purchase order->Purchase receipt.
- In this case, Stock reservation entry should create automatically but did not created.

<img width="1300" alt="image" src="https://github.com/frappe/erpnext/assets/17386166/3d5e3165-32ed-48ae-b7b2-5d26953456cd">

Kindly suggest if any setting is missing from our end or this is a bug. Thanks in advance.

Regards,
Satish Aralkar

### Module

stock

### Version

ERPNext: v15.7.0 (version-15)

### Installation method

manual install

**Comment by s-aga-r** [comment]
@satisharalkar It looks like the Sales Order Item references didn't get copied when we created the Material Request from the Production Plan.

Two Verify in Material Request:
- Look for Sales Orders in Material Request connections.
  
  ![image](https://github.com/frappe/erpnext/assets/63660334/9a361340-fe65-4428-8db0-0a60ff90a20a)

- Run `cur_frm.doc.items.forEach(e => console.log(e.idx, e.item_code, e.sales_order, e.sales_order_item))` in Browser Console Log.

  ![image](https://github.com/frappe/erpnext/assets/63660334/21d37ea3-0959-40f9-9f68-366aafacd950)

**Comment by svdhole** [comment]
Based on your suggestion, I ran the command you provided and observed that the output was "undefined." Additionally, on the Material Request page under the Connection section, I don't see any connection with a sales order. I have attached a screenshot for your reference.

Could you please suggest what our next action should be? Is this a bug? Thanks in advance

![image](https://github.com/frappe/erpnext/assets/155748578/49cbd7e8-574b-4dc9-b7b8-79a83254c23b)

![image](https://github.com/frappe/erpnext/assets/155748578/08613d8d-03e3-4b91-b778-73b00d64e097)

**Comment by s-aga-r** [comment]
The flow SO -> PP -> WO -> MR -> PO -> PR breaks as in WO we don't store the reference of SO coming from PP.

**Comment by s-aga-r** [comment]
@satisharalkar This is a feature request, not a bug. Currently, we have Stock Reservation for a Sales Order means you can reserve the stock against the items of the Sales Order. The flow you are expecting will be a part of Stock Reservation against Work Order where you will be able to reserve the raw materials directly or on purchase.

**Comment by satisharalkar** [comment]
@s-aga-r When we can expect this feature, this is very useful and required feature for all the manufacturing clients. If possible, we need this on priority. Thanks in advance.

**Comment by s-aga-r** [comment]
FR: https://github.com/frappe/erpnext/issues/41455
