### ISSUE TITLE
[priority Issue] Document naming rule is not reseting the counter to zero for new fiscal year

### ISSUE THREAD

**Issue by maveezmh** [frappe/erpnext#39086]
### Information about bug

the document naming rule is not reseting the counter to new series when the year is changedit still contineus same numbering. 

for example  for series INV.YY.-.####

for 2023 the last invoice is for 3046

INV23-3045
INV23-3046

now the year changed to 2024 so the new series should be INV24-0001 but the system is showing INV24-3047

Kindly Advise

### Module

accounts, stock, buying, selling, manufacturing, HR, projects, support, CRM, assets

### Version

happening in both V14 and 15

### Installation method

FrappeCloud

**Comment by maveezmh** [comment]
any update?

**Comment by deepeshgarg007** [comment]
@maveezmh I tried this and for me, the naming series did reset automatically.

<img width="1120" alt="image" src="https://github.com/frappe/erpnext/assets/42651287/11501f32-b733-455a-9346-a950356180dc">

Must be something site specific, closing this issue
