### ISSUE TITLE
Default WIP warehouse and FG warehouse for production order

### ISSUE THREAD

**Issue by neilLasrado** [frappe/erpnext#3910]
Add Default Work in Progress Warehouse and Finished Goods Warehouse in Manufacturing Settings
Make WIP and FG Warehouse mandatory (client side) in Production Order
Fetch default warehouse on making new Production Order or while creating Production Orders from Production Planning Tool.

**Comment by dawoodjee** [comment]
This is great. But different products may need different Source, WIP and Finished Goods warehouses. Or is there an existing workaround?
