### ISSUE TITLE
Wrong Asset Purchase Amount set when creating assets from purchase invoice

### ISSUE THREAD

**Issue by KorucuTech** [frappe/erpnext#39128]
### Information about bug

1- We created a "Purchase Invoice" for an Asset Type. Where purchase invoice has 2 item lines where **_both lines has the same asset item_** being purchased but for different amount. i.e
Purchase Invoice Item Line 1.  Item = computer, Quantity=1, price/each = $5000
Purchase Invoice Item Line 2. Item = computer, Quantity=2 price/each = $7000
Total value of the purchase invoice is $19000
Update Stock is checked.
Purchase invoice is saved and submitted and later items received.
3 Assets are created 

EXPECTED RESULT:
There should be 1 Asset with the Gross Purchase Amount of $5000
There should be 2 Assets with the Gross Purchase Amount of $7000 each
Total Value of Assets Creted = $19000

WHAT HAPPENS:
There are 3 Assets with Gross Purchase Amount of $7000 each
Total Value of Assets Created = $21000

When Creating each Asset it uses the purchase price of the last item in the list of items

### Module

stock, buying, assets

### Version

ERPNext: v14.22.2 (HEAD)

Frappe Framework: v14.33.1 (HEAD)

### Installation method

None

**Comment by rehanansari26** [comment]
@nabinhait @nabinhait
Can this scenario work for creating an asset upon submitting a purchase receipt?
