### ISSUE TITLE
HR expenses claim showing new Account code, but General Ledger still showing old Account code.

### ISSUE THREAD

**Issue by maxchock** [frappe/erpnext#39133]
### Information about bug

I have a lot of Expenses Claim which I previously setup Account Code wrongly. So I update all the Account Code accordingly. The changes showed correctly in Expenses Claim but General Ledger wasn't reflected, it still showing the OLD account code.

Can see from here, Expenses Claim showing 
UPKEEP OF MOTOR (Account Code:920-U02 - Upkeep Of Motor Vehicle - OKSB) Amount $660.00, 
PETROL (Account code:920-P02 - Petrol, Parking & Tol - OKSB) Amount $701.50.

![image](https://github.com/frappe/erpnext/assets/59406510/de62792e-35d6-42b3-b81b-1d598944c3e4)

but when i click VIEW "Account Ledger", it showing the 2 expenses claim in the Account 920-T02 Travel Expenses which was previously set wrong Account code.
![image](https://github.com/frappe/erpnext/assets/59406510/f407f7b9-f2e4-4184-bdef-59a2d7845143)

### Module

accounts, HR

### Version

ERPNext: v15.9.1 (HEAD)

Frappe Framework: v15.8.1 (HEAD)

Frappe HR: v15.8.0 (HEAD)

### Installation method

FrappeCloud

**Comment by deepeshgarg007** [comment]
@maxchock Looks like you have renamed the expense claim type and not the expense claim account. That won't have any effect of the ledge postings. Closing this issue. Doesn't look like a bug

**Comment by maxchock** [comment]
Hi.

No, it is not just the expense claim type. It is the expense account. I just didn't include the screenshots. I will update the screenshot if that's necessary.

**Comment by maxchock** [comment]
![image](https://github.com/frappe/erpnext/assets/59406510/c7511b10-88af-4dbe-8616-e186714649d7)

As you can see, the expense claim type "Upkeep of Motor Vehicle" in Expense Claim is link to Account "920-U02 - Upkeep Of Motor Vehicle - OKSB", but in General Ledger, it still showing "920-T02 - Travel Expenses"

> @maxchock Looks like you have renamed the expense claim type and not the expense claim account. That won't have any effect of the ledge postings. Closing this issue. Doesn't look like a bug
