### ISSUE TITLE
Forgot Password shows current password field

### ISSUE THREAD

**Issue by Shivam327** [frappe/erpnext#39141]
### Information about bug

After clicking on forgot password link, it contains 3 fields rather than two, Please check the Below Image
![image](https://github.com/frappe/erpnext/assets/23412311/20973787-f221-413b-ac42-05cb84c893a0)

### Module

other

### Version

ERPNext: v14.48.1 (version-14)

Frappe Framework: v14.55.0 (version-14)

### Installation method

manual install

**Comment by deepeshgarg007** [comment]
<img width="657" alt="image" src="https://github.com/frappe/erpnext/assets/42651287/1ddaaf20-6ccd-4b75-8e1d-140524c0cbb6">

Seems to be fixed now, closing this issue
