### ISSUE TITLE
Price Difference Credit Note + Sale Return with difference price

### ISSUE THREAD

**Issue by fderyckel** [frappe/erpnext#3915]
PAID DEVELOPMENT

Good afternoon (evening?) Frappe Team,

As we are continuing to implement ERPNext into our company, we were wondering how we can issue a credit note to a customer for the following reason:
We invoiced 100 items at 20$
Now that was a mistake as the price was actually 18$.  So we have to issue a CN for 100 x 2$  for that specific item.
Correct accounts have to be debited / credited.

Right now, we have to do it as a JV.  This become quite complicated for our invoicing clerk ladies when we have to choose which sale account was that item, and which amount is for credit or debit, etc.  
Also we can not give JV to our customer.  They need a proper CN (or sale return).

What would like is to do the CN from the sale invoice itself.  (using the sale return button).   Now they are restriction on how to do that sale return.  We should be able to do a sale return with no stock update and different price to fit the above situation.    This is what we call a Price Difference Credit Note.
Similarly we should be able to do sale return with different price that those initially invoiced.  
(for instance, customer has damaged the product.  We are happy to take it back but let's say at only 80% of its value.)

We could finance that development if you give us a quote.  

Thanks

Francois

**Comment by nabinhait** [comment]
Fixed via https://github.com/frappe/erpnext/pull/3940
