### ISSUE TITLE
In v15 BOM Creator tool Operations & Routing, Costing addition options not visible.

### ISSUE THREAD

**Issue by RJMHASKE** [frappe/erpnext#39160]
### Information about bug

while using BOM Creator tool in v15- adding Operations, routing, costing options not visible so BOM has submitted and created multilevel structure but without theses details. then we go into BOM list all BOM was submitted so how we can add operations/Routing??

![image](https://github.com/frappe/erpnext/assets/119041865/2455dec3-0d04-449a-8036-44de5020e699)
![image](https://github.com/frappe/erpnext/assets/119041865/f8d29721-a514-49b9-9a8b-fc9e544676a6)

![image](https://github.com/frappe/erpnext/assets/119041865/9c4f7542-9207-4ab1-a5be-754749788cd6)

### Module

accounts, stock, manufacturing

### Version

![image](https://github.com/frappe/erpnext/assets/119041865/2b5b8d2c-89c5-4216-9c26-69309c3e5363)

### Installation method

manual install

**Comment by rohitwaghchaure** [comment]
@RJMHASKE this is a feature request and not a bug. We are already working on it and will add it in the upcoming version of v15.
