### ISSUE TITLE
Create Invoice from Multiple DNs

### ISSUE THREAD

**Issue by jof2jc** [frappe/erpnext#3916]
Currently when we want to create one invoice against multiple delivery notes, we have to select each DN one by one then press Get button to fetch the items (see below image)

![get from delivery note](https://cloud.githubusercontent.com/assets/12841357/9384489/043636f4-477b-11e5-8adf-bb989636fb94.png)

This is not efficient when user has many e.g. 30 or more DNs in a month for 1 customer. Imagine if they have hundreds of customers? This will consume a lot of time... This should be a standard feature like in the many accounting software.
1. Can we add option to select period -> From Date: defaulted to 1 month back and To Date:current date on the 'Get From Delivery Note' window?
2. Press Get button, then automatically fetch all DNs in the period range from selected customer.
3. Show DN number on each invoice item-row.
4. The same scenario is applied for purchase invoice against multiple receipts.

**Comment by jof2jc** [comment]
Can we add this Period From-To filter to do 'batch fetching' instead of getting each delivery notes/purchase receipts one by one when creating new invoice? It will save a LOT of time...

**Comment by rmehta** [comment]
Can you sponsor? 1 hr of development?
