### ISSUE TITLE
CRM - Email campaign doesnt work with HTML emails

### ISSUE THREAD

**Issue by sjoulaei** [frappe/erpnext#39176]
### Information about bug

The email templates can be created with an HTML tick ON. These emails are sent correctly when used for a normal email.
But when the email is sent by the CRM email campaign, it goes as plain text and is not rendered as HTML.

### Module

CRM

### Version

ERPNext Version 14
ERPNext Version 15

### Installation method

FrappeCloud

**Comment by Nihantra-Patel** [comment]
Solved: https://github.com/frappe/erpnext/issues/41168
