### ISSUE TITLE
Asking for Default Cost of Goods Sold Account in Purchase return

### ISSUE THREAD

**Issue by WavesSkipper** [frappe/erpnext#39174]
### Information about bug

Hello,

When I create a Purchase return (Debit Note) and I check the "**Update Stock**" it inform me that It'll credit the stock account, but when I want to submit or preview the posting transaction I get and error msg "**Please set default Default Cost of Goods Sold Account in Company**", I don't know why it's needed this account! when I provide an account for "**Default Cost of Goods Sold Account**" in a company level, the posting transaction I got is wrong, It makes the qty in the warehouse as amount in credit and make the stock account in credit but deducted by the value in "**Default Cost of Goods Sold Account**"  which is the qty in stock. Please if you can solve that, thanks

### Module

accounts, buying

### Version

ERPNext: v15.3.0 (version-15)
Frappe Framework: v15.2.1 (version-15)

### Installation method

None

**Comment by deepeshgarg007** [comment]
@WavesSkipper This issue seems site-specific. I am unable to replicate on my site. Please provide more details and reopen the issue
