### ISSUE TITLE
CRM-Email Campaign - Status stucks at In Progress

### ISSUE THREAD

**Issue by sjoulaei** [frappe/erpnext#39179]
### Information about bug

When an email campaign is set, the emails go out as scheduled. But the status stays as in progress forever.

### Module

CRM

### Version

ERPNext: v15.9.1
Frappe Framework: v15.8.1

### Installation method

None

**Comment by khushali-beehyv** [comment]
@rohitwaghchaure @deepeshgarg007 Please help the PR mentioned above to go forward for the tests and the review process.
