### ISSUE TITLE
Timesheet against Production Order should be made for BOM qty (not Production Order qty)

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#3917]
- [ ] Timesheet should be generated based on BOM Qty not total qty. For example if BOM qty is 1 and Production Order qty is 3, there should be 3 timesheets (for 1 each)

On submitting Production Order, following is the error message:

![screen shot 2015-08-20 at 6 43 39 pm](https://cloud.githubusercontent.com/assets/910238/9384867/befc3f70-4770-11e5-839f-306473a78ca4.png)

This issue arises if Working Hours table in the Workstation master is blank. After updating value in the said table, Production Order gets submitted.

We should either improve validation message, so that user knows what needs to be fixed. Or we can make Working Hours table mandatory in the Workstation master.

**Comment by mhbu50** [comment]
+1
