### ISSUE TITLE
Production Order - Operation Time didn't fetch from BOM

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#3918]
In the Production Order, operation time was not fetched from BOM. Error message on submitting Purchase Order was:

![screen shot 2015-08-20 at 5 25 03 pm](https://cloud.githubusercontent.com/assets/910238/9385026/a2a0a4be-4771-11e5-9716-161c1d3b425f.png)

I entered operations time manually, and Production Order was submitted correctly.

Firstly Operations Time should auto-fetch (working correctly now). If value is missing in said field, then validation message should state it clearly.

**Comment by neilLasrado** [comment]
Operation Time didnt work because qty to manufacture might not have been entered. Will fix up the validation.
