### ISSUE TITLE
Disappearing link in non En language

### ISSUE THREAD

**Issue by bakhtari** [frappe/erpnext#39197]
### Information about bug

In General Ledger Report, column Voucher Number does not have a link to Voucher (such as sales invoice) in some non-English languages.

### Module

accounts

### Version

Frappe Version: 15.x
Erpnext Version: 15.x

### Installation method

manual install

**Comment by deepeshgarg007** [comment]
@bakhtari Can you please elaborate on the issue and add some screenshots for which language? Not able to understand the issue

**Comment by bakhtari** [comment]
Tthis issue related to dynamic links. in dynamic link in non EN language related doctype field translated in report and system not found in doctypes list.i remove translation for voucher type in report
