### ISSUE TITLE
Task sort option missing "Expected Start Date"

### ISSUE THREAD

**Issue by aarauf** [frappe/erpnext#39203]
## Description of the issue
If the user selects a different option for sorting the gantt chart, the default (Expected Start Date) goes missing. Without this (default) view, the gantt chart is virtually unusable.

Update: "Expected start date" is missing from all task list sorting views (Kanban, List, Report, ...all of them)

## Context information (for bug reports)
Appears in both V12 and V13.

**Output of `bench version`**
```
(paste here)
```

## Steps to reproduce the issue

1. View a project in Gantt View
2. Change the sorting order from "Expected Start Date"
3. Try to switch the sorting back to "Expected Start Date"

### Observed result
The option is not available

### Expected result
"Expected Start Date" is an option in the list of sorting options

### Stacktrace / full error message

```
(paste here)
```

## Additional information
First observed on V12, also with the V13 trial hosted by erpnext servers.

OS version / distribution, `ERPNext` install method, etc.

**Comment by aarauf** [comment]
I'm going to venture to say this is a frappe issue. Seems like it's related to the desk html. Looking for "sort-selector" and how it retrieves the list options...

**Comment by aarauf** [comment]
Making the "Expected Start Date" Bold in the task doctype causes the option to appear properly in all but Gantt view.

**Comment by deepeshgarg007** [comment]
<img width="1359" alt="image" src="https://user-images.githubusercontent.com/42651287/198298714-ede8b6ed-5018-4747-82fb-d89be07293b5.png">

Sort options not rendered properly in gantt view
