### ISSUE TITLE
Timesheet / Sales Invoice: Status of some Timeesheets randomly don't get updated

### ISSUE THREAD

**Issue by DrZoidberg09** [frappe/erpnext#39227]
### Information about bug

When I create sales invoices based on Timesheets, Timesheets get set to status "billed". This works for about 95% of the Timesheets. However, sometimes they don't get updated and keep status "submitted".

### Module

accounts, projects

### Version

v15.9.1 ERPNext and newest Frappe

### Installation method

docker

### Relevant log output / Stack trace / Full Error Message.

```shell
So far I did not find anything relevant in terms of logs. Please let me know if there are logs that help to identify the issue.
```

**Comment by ruthra-kumar** [comment]
https://github.com/frappe/erpnext/issues/40006

**Comment by ankush** [comment]
duplicate
