### ISSUE TITLE
Closing stock balance validation doesn't allow creation of second entry

### ISSUE THREAD

**Issue by Namekkural** [frappe/erpnext#39243]
### Information about bug

After creating my first Closing Stock Balance for 2018, I wanted to create one for 2019. Unfortunately I get an error: "Closing Stock Balance [CBAL-00001] already exists for the selected date range". This is a false alarm, since the mentioned CBAL-00001 has a different date range.

I would really appreciate you looking into this, since we are experiencing slowdowns in our Stock Balance reports. As I understand it, this feature is supposed to improve performance in this area by locking the stock values from previous periods.

I have attached some images that show the error.

![CleanShot 2024-01-09 at 09 57 13@2x](https://github.com/frappe/erpnext/assets/11909277/96930861-db49-4d62-a1ee-9a00221186a6)
![CleanShot 2024-01-09 at 09 57 17@2x](https://github.com/frappe/erpnext/assets/11909277/88e1c31c-327e-49ea-ac75-7beeaf56bc30)
![CleanShot 2024-01-09 at 09 57 39@2x](https://github.com/frappe/erpnext/assets/11909277/1e3d0e35-fd01-4ce3-a21b-6e0903341160)

### Module

stock

### Version

Frappe version 14.62.1
ERPNext version 14.58.1

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
Duplicate Closing Stock Balance
Closing Stock Balance CBAL-00001 already exists for the selected date range
```

**Comment by s-aga-r** [comment]
fixed:https://github.com/frappe/erpnext/pull/39262
