### ISSUE TITLE
Work order not save without sales order id

### ISSUE THREAD

**Issue by AlaaBadry** [frappe/erpnext#39291]
### Information about bug

work order not save without sales order is which is not mandatory 

### Module

manufacturing

### Version

ERPNext: v15.9.1 (version-15)
Frappe Framework: v15.8.1 (version-15)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
"_server_messages": "[\"{\\\"message\\\": \\\"Sales Order  not found\\\", \\\"title\\\": \\\"Message\\\", \\\"indicator\\\": \\\"red\\\", \\\"raise_exception\\\": 1, \\\"__frappe_exc_id\\\": \\\"0706f0825f5d13e93648da3cec62bb2a9e5c56aee109528221330c85\\\"}\"]"
}
```

**Comment by nabinhait** [comment]
Can't replicate the issue, can you give the steps you are following?

**Comment by AlaaBadry** [comment]
Thanks for your reply 
When create Work Order directly not form sales order the document didn't save and i got this message 
![Screenshot Capture - 2024-01-10 - 15-41-24](https://github.com/frappe/erpnext/assets/26534497/40382505-fb98-4ed9-87e7-980ce71e8a51)

and here is the server response message 
"_server_messages": "[\"{\\\"message\\\": \\\"Sales Order  not found\\\", \\\"title\\\": \\\"Message\\\", \\\"indicator\\\": \\\"red\\\", \\\"raise_exception\\\": 1, \\\"__frappe_exc_id\\\": \\\"0706f0825f5d13e93648da3cec62bb2a9e5c56aee109528221330c85\\\"}\"]"
}

**Comment by AlaaBadry** [comment]
Solved It was custom app issue
