### ISSUE TITLE
v14.58.1 No option to reserve website stock when order is placed

### ISSUE THREAD

**Issue by N1RMS** [frappe/erpnext#39298]
### Information about bug

PR 38382 has a code change that affects stock validation in the website cart. It no longer looks at reserved quantity but at actual stock only. This causes overbooking of goods. There is no option to reserve stock automatically in v14 like in v15. 
<img width="1440" alt="Screenshot 2024-01-10 at 8 12 38 AM" src="https://github.com/frappe/erpnext/assets/90060058/ef6ab677-3109-4038-8654-5c639d4c728f">

### Module

ecommerce

### Version

framework: 6687b8f
erpnext: 14.58.1

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
File "apps/erpnext/erpnext/e_commerce/shopping_cart/cart.py", line 115, in place_order
    throw(_("Only {0} in Stock for item {1}").format(item_stock.stock_qty, item.item_code))
This is the error in cart when i try to order more than how much is present, however this is only looking at actual stock and not at actual stock-reserved stock as it always used to before PR#38382
```

**Comment by s-aga-r** [comment]
fixed: https://github.com/frappe/erpnext/pull/39292
