### ISSUE TITLE
[Feature request] Journal Boucher list show user note as title

### ISSUE THREAD

**Issue by williamjmorenor** [frappe/erpnext#3930]
Hi.

Currently the list o Journal Bourcher show the firt Account afected in the entry as the title, it is hard to find a registry by looking for the account, it will be better to show the User comment as the Title of the JV in the list.

**Comment by PawanMeh** [comment]
Can you explain with a screen shot? Have you tried in the latest version.

Closing this for now, re-open if it is still an issue.
