### ISSUE TITLE
Owner Based Permission can be by-passed via report

### ISSUE THREAD

**Issue by sbkolate** [frappe/erpnext#3931]
I want to setup "Owner Based restriction" for Sales User.
I have checked If Owner in Role Permission manager(for Lead and Customer).
It woks fine, Now user can see only his Customer and Lead.

Issue is, User can see all customer from "Customer Addresses And Contacts" report, and when he click on customer in report, he is able to see customer.
Same is for "Lead Details" report, when user click on any Lead, he is able to see Lead.

I want to restrict user from this report, He can only see customer related to him.

Also, "Customer Addresses And Contacts" report heading should be in Title Case.
Please see image.
![customer detail](https://cloud.githubusercontent.com/assets/6648915/9423051/4a566a36-48d0-11e5-9437-00c71c01f15b.PNG)

**Comment by jof2jc** [comment]
Is this resolved already?

**Comment by strixaluco** [comment]
Fixed via frappe/frappe/pull/2847
