### ISSUE TITLE
Production Order

### ISSUE THREAD

**Issue by krishnanhemanth** [frappe/erpnext#3933]
Hi
all my production orders are getting saved as draft
iam not able to edit or delete the production orders
the error is " Server Error: Please check your server logs or contact tech support "\
Please help in resolving this issue

**Comment by neilLasrado** [comment]
can you please paste the error message at dpaste.com and share the link ?

**Comment by krishnanhemanth** [comment]
Hi
when I try to open a production order (saved as draft) this is the error I get
http://dpaste.com/3H21563
when I select a production order (checkbox) and try to delete it, this is the error i get
http://dpaste.com/0W4CBSR
Please help me in resolving the issue

**Comment by anandpdoshi** [comment]
Which date format is defined in Setup > System Settings. Also, which
browser did you use?

Can you try to reproduce this error on demo.erpnext.com?

-Anand.

**Comment by krishnanhemanth** [comment]
Hi
the date setup is dd-mm-yyyy
iam using ie 10 and chrome .. both are showing the same error
Can you please let me know how I can reproduce this error on demo.erpnext
Thank you

**Comment by anandpdoshi** [comment]
Just see if you can create a Production Order like you do in your system and if the error occurs for you. I tried it and it is working fine for me.

By any chance, do you have any custom fields in your system for Production Order?

**Comment by krishnanhemanth** [comment]
no
I don't have any custom fields
Iam really stuck.
neither am I able to delete or edit the production order

**Comment by anandpdoshi** [comment]
Are you using some other language?

**Comment by krishnanhemanth** [comment]
No...Iam Using English Language only
