### ISSUE TITLE
Advanced Rest Client Internal Server Error 500

### ISSUE THREAD

**Issue by monojoker** [frappe/erpnext#3934]
Hi Guys,

I'm having problems connecting to ERPNext using the Rest API client within Google Chrome. See below no matter what URL I point to or how I parse my credentials to the site I get an Internal Server Error. Can someone tell me what I'm doing wrong please? Thanks.

![image](https://cloud.githubusercontent.com/assets/10917366/9430714/326543ec-4a43-11e5-8fc9-01f836fdddf3.png)

**Comment by monojoker** [comment]
Anyone? I'd really like to get this working. I guess it's not really ERPNext support so I'll try asking on a generic forum. Cheers guy.

**Comment by pdvyas** [comment]
Yeah, post it on discuss.erpnext.com
