### ISSUE TITLE
Salary slips visible to other users

### ISSUE THREAD

**Issue by hpema** [frappe/erpnext#3935]
Hi Team,

Not sure if this is already reported but the salary slips are visible to all user of the company.

I have set the user permissions to company and employee but only company is applied to the salary slip screen. Should employee not be there too for HR users?

regards
Hemant

**Comment by anandpdoshi** [comment]
Hemant,

HR User typically has access to all Salary Slips unless you specify
Employee based User Permissions.

**Comment by hpema** [comment]
Oh ok, then its not an issue, i will just remove user from that role.

Thanks
