### ISSUE TITLE
Incorrect Voucher Subtype

### ISSUE THREAD

**Issue by ishanloya** [frappe/erpnext#39382]
### Information about bug

As a result of commit [e5d73c7](https://github.com/frappe/erpnext/commit/e5d73c780bc5e272dd7c3db7db65665010ef6623), voucher subtype is being incorrectly returned. For e.g. When voucher is "Sales invoice" voucher subtype is being returned as "Debit Note" even when it isn't

### Module

accounts

### Version

ERPNext: v15.10.0 (version-15)
Frappe Framework: v15.9.0 (version-15)
Frappe HR: v15.9.0 (version-15)
India Compliance: v15.4.1 (version-15)

### Installation method

None

**Comment by ishanloya** [comment]
Same issue with "Purchase Invoice" being incorrectly marked as "Credit Note" when it isn't

**Comment by sammish** [comment]
Yes, 

![image](https://github.com/frappe/erpnext/assets/12432802/228b2368-663b-4a7a-b85b-a31ea8add264)

**Comment by Akshaths12** [comment]
This issue was also raised by one of our clients. Do we have any fix for this?

**Comment by dvdl16** [comment]
Experiencing the same issue

![image](https://github.com/frappe/erpnext/assets/4974009/be0dab68-fe9b-4634-81a0-8f2767027ab7)

```
ERPNext: v15.14.7
Frappe Framework: v15.15.0
```

**Comment by Craftint** [comment]
Facing the same issue. It needs to be corrected asap

**Comment by MohitJ640** [comment]
@deepeshgarg007 Till when can we expect this error to be resolved?
