### ISSUE TITLE
GUI BUG

### ISSUE THREAD

**Issue by parthdalvi** [frappe/erpnext#3938]
![capture 3](https://cloud.githubusercontent.com/assets/13132998/9436434/f4fb2056-4a6c-11e5-8376-4a0042f94b8b.JPG)
![capture](https://cloud.githubusercontent.com/assets/13132998/9436435/f552ac22-4a6c-11e5-9309-5105e834db78.JPG)
![capture2](https://cloud.githubusercontent.com/assets/13132998/9436436/f59b527e-4a6c-11e5-8145-e0759acf9e60.JPG)

1) 1st image(capture 3) : when we check all & refresh the page, select all check box remains checked.

2) 3rd image(capture 2) : when we click on check all, it functions as expected but when we uncheck any of the check box, check all button remains checked which actually should get unchecked.

**Comment by PawanMeh** [comment]
Only point .1, seems to be a UI issue. Apart from that everything works in the latest version

**Comment by PawanMeh** [comment]
This is fixed in the latest version. Closing this.
