### ISSUE TITLE
Gross Profit Report by Project is not working!

### ISSUE THREAD

**Issue by jof2jc** [frappe/erpnext#3944]
Using v5.6.3. Project info doesn't appear in Gross Profit Report

**Comment by jof2jc** [comment]
It does appear on Sales Register report..

**Comment by jof2jc** [comment]
still not resolved?

**Comment by gohyc** [comment]
I am facing the same issue.  I'd like to report profit by project but even with the project_name in all the documents, the Gross Profit report group by Project is showing nothing.

**Comment by rohitwaghchaure** [comment]
Hi @gohyc 

It's working, can you please check
