### ISSUE TITLE
Can't change default dates in chart of accounts

### ISSUE THREAD

**Issue by com-guy** [frappe/erpnext#39442]
### Information about bug

ERPNext: v14.61.0 (version-14)

Frappe Framework: v14.62.3 (version-14)

Frappe HR: v14.21.2 (version-14)

Can't find a way to change the default date range (start/end dates) that are in chart of accounts.

When opening an account, the dates for the previous fiscal year are displayed...

### Module

accounts

### Version

ERPNext: v14.61.0 (version-14)

Frappe Framework: v14.62.3 (version-14)

Frappe HR: v14.21.2 (version-14)

### Installation method

manual install

**Comment by Poorvi-R-Bhat** [comment]
There is no Date,Fiscal Year field in the Account Doctype. Need the steps to replicate the issue.

**Comment by com-guy** [comment]
When I open Chart of Accounts (in Tree view) and I drill down to the account I want to view, I click View Ledger.  When the Ledger is loaded, the default dates that are displayed is for the previous fiscal year.  In the previous version, this would change when the previous fiscal year was closed and the new fiscal year activated.  
![dates](https://github.com/frappe/erpnext/assets/95228822/bfb45498-e2b2-4a87-9476-e777fa59351c)

**Comment by nabinhait** [comment]
Can't replicate in v15, now it always sets current fiscal year dates.
