### ISSUE TITLE
Additional Features required for market place

### ISSUE THREAD

**Issue by prash4** [frappe/erpnext#3948]
Hello,
We an Ecommerce company , and we operate as a market place model  as well as warehouse model
So below features are required for the same

Sales order - when we submit the sales order , we should get the option to select marketplace model or ware house model . When we select market place model , we need below steps

Shipping Order - Where no physical delivery is made , just an order to ship - We should select supplier and customer in the shipping order 

Buying price - So when we place a order to supplier, we will send him details of buying and selling price

Listing fees/Commission - , it will be the difference between the buying price and selling price 

Payment receipt from customers - As we are collecting payment on behalf of supplier , we need to keep in a different account , and we will the supplier from that account , so we will maintain it supplier wise

Commission invoice - we will raise the invoice of commission / listing fees to the supplier ( this will difference of buying and selling price )

**Comment by rmehta** [comment]
Please add it to the original issue #3655
