### ISSUE TITLE
ERPNEXT and mobile computer with barcode scanner

### ISSUE THREAD

**Issue by negini** [frappe/erpnext#3949]
Hi
is it any special facility in ERPNEXT to work with mobile computer with barcode scanner to do fast stock inventory by serial number or track items history by serial number ?

**Comment by yashodhank** [comment]
Yes, already available. please make use https://discuss.erpnext.com before posting here. Thanks.

**Comment by negini** [comment]
i send it on    https://discuss.erpnext.com   and got reply , not available in erpnext at a moment :) 


Hi
is it any special facility in ERPNEXT to work with mobile computer with barcode scanner to do fast stock inventory by serial number or track items history by serial number ?
for example right now if we want to track serial we have to go stock\serial add filter then scan serial and for next items again cancel or edit old filter and again scan , its very hard when you want to track and check for example 100 items .

or when you want to check stock we have for example 10,000 serialize items , how we can do stock inventory ?

**Comment by PawanMeh** [comment]
Check the following [link](https://discuss.erpnext.com/t/erpnext-for-retail-outlets-some-lessons-learnt/33787/2) on discuss, if anything more specific is needed after that, you can re-open the issue or create a new one.
