### ISSUE TITLE
ERPNext v15: Amount does not change in Material Request even when the quantity and rate is changed

### ISSUE THREAD

**Issue by mbile** [frappe/erpnext#39517]
### Information about bug

While creating a Material Request on a newly installed ERPNext v15, I noticed that the amount does not change based on the quantity and the rate of the items selected (see the screenshot). 

<img width="1330" alt="Screenshot 2024-01-23 at 9 22 01 PM" src="https://github.com/frappe/erpnext/assets/22956463/f5084ad6-2aef-43ea-b224-5658b9681d4b">

I have also tested it a new docker installation on another machine(ERPNext v15 of course) which is still not working. This is just working fine on an old ERPNext v14 installation.

### Module

stock

### Version

Installed Apps

ERPNext: v15.10.4 (version-15)

Frappe Framework: v15.10.0 (version-15)

Frappe HR: v15.9.1 (version-15)

Payments: v0.0.1 (version-15)

<img width="550" alt="Screenshot 2024-01-23 at 9 27 04 PM" src="https://github.com/frappe/erpnext/assets/22956463/e642d010-2635-4375-bbf8-c5fa31a92141">

### Installation method

manual install

**Comment by liviaarumsari** [comment]
I also found this bug. When I read the codes further, I found this issue appeared because of this change from PR #38720 (https://github.com/frappe/erpnext/pull/38720/files)
