### ISSUE TITLE
In BOM item image is not showing after submiting BOM

### ISSUE THREAD

**Issue by sbkolate** [frappe/erpnext#3954]
check this link
https://demo.erpnext.com/desk#Form/BOM/BOM%2FT-shirt%2F003

In BOM form:
Item image is showing correctly
![bom01](https://cloud.githubusercontent.com/assets/6648915/9493869/50e1f476-4c20-11e5-9a5c-167d753ff0c5.PNG)

But when we submit BOM, only image path is showing
![bom02](https://cloud.githubusercontent.com/assets/6648915/9493886/66673b94-4c20-11e5-84c5-fc67f0890d33.PNG)

**Comment by rohitwaghchaure** [comment]
Working
![screen shot 2016-10-10 at 6 27 57 pm](https://cloud.githubusercontent.com/assets/8780500/19236903/7efdae3c-8f17-11e6-94fd-14418c539a33.png)
