### ISSUE TITLE
Repost Item Valuation Error

### ISSUE THREAD

**Issue by thida-bcn** [frappe/erpnext#39545]
### Information about bug

"Unknown column 'validate_negative_stock' in 'field list'" errorclass = pymysql.err.OperationalError: (1054, "Unknown column 'validate_negative_stock' in 'field list'")

### Module

stock

### Version

![image](https://github.com/frappe/erpnext/assets/62122640/410cffef-c40a-4f7d-8ff5-ef45f398ba2f)

### Installation method

manual install

**Comment by rohitwaghchaure** [comment]
@thida-bcn do bench --site your_site_name console from the frappe-bench folder and then run below command and check

```
frappe.reload_doc("stock", "doctype", "inventory_dimension", force=True)
frappe.db.commit() 

```
