### ISSUE TITLE
ERPNext Documentation is not working

### ISSUE THREAD

**Issue by Islamation** [frappe/erpnext#39546]
### Information about bug

Hi there,
I tried a lot to open ERPNext Documentation, but it is not working, has anyone any information about the reason?

### Module

other

### Version

Frappe version 14

### Installation method

None

**Comment by GeoCommander** [comment]
there is an issue with the functionality of the site when browsing using phone

**Comment by Nihantra-Patel** [comment]
Hi @Islamation,

Can you share the link to documentation and which documentation does not open?
