### ISSUE TITLE
Server Scripts Disabled

### ISSUE THREAD

**Issue by GerardoIPM** [frappe/erpnext#39563]
### Information about bug

We are receiving in multiple cases the following message:
Server Scripts are disabled. Please enable server scripts from bench configuration.
[Read the documentation to know more](https://frappeframework.com/docs/user/en/desk/scripting/server-script)

Following the recommended documentation, it says that "1) If your site is being hosted on [erpnext.com](https://erpnext.com/), contact support to activate Server Script."
![Schermata 2024-01-25 alle 11 43 55](https://github.com/frappe/erpnext/assets/143416246/ad9dc053-6209-45b4-8925-579e7529eecd)

So here we are: we urgently need to have the scripts enabled!

### Module

accounts, buying, selling, CRM, other

### Version

ERPNext: v15.10.5 (HEAD)
Frappe Framework: v15.11.0 (HEAD)

### Installation method

None

**Comment by GerardoIPM** [comment]
Please it is really urgent. We were upgraded to Version15 this night and we can't make anything

**Comment by GerardoIPM** [comment]
Please it is a really urgent matter for us. I noticed that many request of support are left without any reply from you.

We can't face such situation.

We urgently require you to take action and support us.

**Comment by GerardoIPM** [comment]
URGENT SUPPORT NEEDED

**Comment by ankush** [comment]
Please raise a support ticket on https://support.frappe.io/ with site details. If you're hosted with us you can get a private bench with server scripts enabled.

**Comment by ankush** [comment]
@GerardoIPM I've updated your site to allow server scripts. In future please raise ticket on support.frappe.io for faster response. Github issues are for free and open source aka community users.

**Comment by GerardoIPM** [comment]
Dear Ankush, thank you so much for your prompt support.
I also create an account on support.frappe.io for my account and shared the information with my colleagues.
thank you so much again: we will use the right platform to ask for assistance next time!
