### ISSUE TITLE
Server Script 

### ISSUE THREAD

**Issue by leonardo231086** [frappe/erpnext#39561]
### Information about bug

I cannot create a sales order from quotation. thia is the message: Server Scripts are disabled by default to improve security on shared benches.

### Module

other

### Version

v15.10.5

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
Server Scripts are disabled. Please enable server scripts from bench configuration.
```

**Comment by leonardo231086** [comment]
Urgent Help Needed

**Comment by ankush** [comment]
Please raise a support ticket on https://support.frappe.io with site details. If you're hosted with us you can get a private bench with server scripts enabled.
