### ISSUE TITLE
Not able to open the purchase invoice

### ISSUE THREAD

**Issue by FederIPM** [frappe/erpnext#39579]
### Information about bug

Hello, whenever i try to access to my purchase invoice list, there is a bug and appear this (chek the enclosed file). 
![Schermata 2024-01-26 alle 09 14 17](https://github.com/frappe/erpnext/assets/135955357/fce74014-c95a-4cf2-8c74-518222994ae8)
Please, solve this issue as soon as possible because otherwise we are not able to work. 

Thank you

### Module

accounts, buying

### Version

Frappe Framework: v15.10.5 - ERPNext: v.15.11.0 

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
Field expense_claim is referring to non-existing doctype Expense Claim. Please delete the field from Purchase Invoice-expense_claim or add the required doctype.
```

**Comment by viralpatel15** [comment]
May be hrms app in uninstalled but fields are still there
install HRMS app and then try

**Comment by Nihantra-Patel** [comment]
Hi @FederIPM,

ERPNext and HRMS can't provide the expense_claim type of field so please check if the custom field expense_claim field is added in the Purchase Invoice or not. If there and if you don't use the HRMS app then remove then expense_claim field.

Thank You!
