### ISSUE TITLE
v15: Purchase order advance paid is not updated on payment entry & the payment request status is also not updated.

### ISSUE THREAD

**Issue by mujeerhashmi** [frappe/erpnext#39574]
### Information about bug

The payment ledger entry created for payment against purchase order is not created properly. The fields "Against Voucher Type" and "Against Voucher No" are same as "Voucher Type" & "Voucher No". 

<img width="523" alt="Screenshot 2024-01-26 at 9 07 04 AM" src="https://github.com/frappe/erpnext/assets/12420747/b0d8c8f4-7716-4f3a-99f0-1b00879f6f54">

### Module

accounts, buying

### Version

ERPNext: v15.10.6 (version-15)
Frappe Framework: v15.11.0 (version-15)

### Installation method

manual install

**Comment by mujeerhashmi** [comment]
@deepeshgarg007 @ruthra-kumar  Kindly have a look. Tagging for criticality.

**Comment by ruthra-kumar** [comment]
Does the Payment Entry has any reference? and Is the `Book Advance Payments in Separate Party Account` option enabled in Company master?

**Comment by mujeerhashmi** [comment]
>Does the Payment Entry has any reference?

The payment entry has reference to purchase order.

>and Is the Book Advance Payments in Separate Party Account option enabled in Company master?

Yes the option is selected.

To give you the timelines, the issue seems to have happened with changes introduced after Jan 1.

**Comment by mujeerhashmi** [comment]
@ruthra-kumar The issue is not seen when we disable `Book Advance Payments in Separate Party Account`.

**Comment by mujeerhashmi** [comment]
I think the GL build logic introduced in #38393 is the issue . The references for PO are not kept in the GL entry and hence the logic to update the advance paid status fails.

**Comment by mujeerhashmi** [comment]
@ruthra-kumar either the gl build logic or the status of the advance paid logic has to change. I am not fully aware of the design of the gl build logic so cannot send the PR. But it is very critical for this to be fixed as some of us have production sites on v15. Hope this issue will get the attention it needs 😊.

**Comment by mujeerhashmi** [comment]
@ruthra-kumar Request your kind attention for the fix. May be you can guide me so that i can raise the PR for this.

**Comment by ruthra-kumar** [comment]
@mujeerhashmi We are making a fix for this. Should be ready by this week

**Comment by ruthra-kumar** [comment]
Fix will take more time to develop.

**Comment by mujeerhashmi** [comment]
Thanks for the heads up. Any quick fix for production ? By the way more as in how much more ?

**Comment by ruthra-kumar** [comment]
Can't provide any date at the moment.

This issue only affects the `Advance Paid` field in Sales/Purchase Order, which is not a critical field.
Can you explain how this field affects or important for your scenario?

**Comment by mujeerhashmi** [comment]
As stated in the title, The  status of payment request through which the payment entry is created is also not getting updated. The team processing payment request will not know whether it was processed. The workflows are getting affected.

**Comment by mujeerhashmi** [comment]
Hello @ruthra-kumar. Any updates ???

**Comment by ruthra-kumar** [comment]
You can pull the changes from https://github.com/frappe/erpnext/pull/39681, test on your case and use it. But, it is highly inefficient - if payment entry has many references, reconciliation will be slow.

We are working on a fix that will be performant than this, which will take a while.

**Comment by ruthra-kumar** [comment]
Fixed by https://github.com/frappe/erpnext/pull/39681
