### ISSUE TITLE
Multiple Tax in sales order and sales invoice 

### ISSUE THREAD

**Issue by prash4** [frappe/erpnext#3959]
Hi,

In the sales order and in sales invoice , we have multiple items with different tax rates

Eg Item 1 may be with 12.5 vat,Item 2 with 5% vat, Item 3 with 1% vat

So in same sales invoice  , how can we show different vat rates ?

Item code   Description Quantity    Price   Tax rate    Tax amount  Total  
Mu32    Gloves  2   310 1%  6.6 626 
Mo12    Plastic 4   225 5%  45  945 
SP98    Tape    5   170 12.5%   106 956 
                                                                                                Total -                            Rs 2527

Summary – Total tax amount – Rs.157

So is there any way we can show this different tax rates in same documents

**Comment by strixaluco** [comment]
Please post questions to [discuss.erpnext.com](https://discuss.erpnext.com)
