### ISSUE TITLE
I can't save any row in child table when I am linking 2 docfield to the same child table

### ISSUE THREAD

**Issue by stockarea** [frappe/erpnext#39597]
### Information about bug

I have a single child table - Documents.

I have the main table - A

Now I have 2 fields, lets say field1 and field2 , both of type Table and linked to child table Documents.

But I am not able to save any row in this field1 and field2.

When I am linking only single field1 or field2 its working, but not on both.

### Module

other

### Version

Frappe Version : 15
ERPnext Version : 15

### Installation method

easy-install

**Comment by Nihantra-Patel** [comment]
Hi @stockarea,

Already issue is registered in frappe (https://github.com/frappe/frappe/issues/24556). It's a framework issue.
so we closed this issue.

Thank You!
