### ISSUE TITLE
Incorrect Warehouse Selection and Duplicate Serial/Batch Bundle Creation in Pick List from Sales Order

### ISSUE THREAD

**Issue by rknroot** [frappe/erpnext#39602]
### Information about bug

Incorrect Warehouse Selection and Duplicate Serial/Batch Bundle Creation in Pick List from Sales Order 

**Steps to Reproduce**

1. Ensure three warehouses are created: Mumbai, Delhi, and Chennai.
2. Stock the iPhone 15 in each of these warehouses with a sufficient quantity.
3. Navigate to the Sales Order doctype and create a new Sales Order.
4. Add an item (e.g., iPhone 15) with the quantity (e.g., 500 Nos) and specify the "Delhi Warehouse" as the source warehouse.
5. Submit the Sales Order.
6. Go to the Pick List doctype and create a new Pick List based on the submitted Sales Order.
7. Observe the warehouse selection for the item and the creation of Serial/Batch Bundles.

**Expected Behaviour**

- The Pick List should select the "Delhi Warehouse" as specified in the Sales Order, and a single Serial/Batch Bundle should be created with the Pick List voucher number as a reference.
- In cases where the "Delhi Warehouse" does not have sufficient stock to fulfil the Sales Order, the system should alert the user about the insufficient stock instead of automatically selecting an alternative warehouse.

**Actual Behaviour**
The Pick List incorrectly selected "Chennai & Mumbai Warehouses", and duplicate Serial/Batch Bundles were created, one with and one without the Pick List voucher number reference.

**Impact**
This issue leads to incorrect stock deductions and inventory discrepancies, impacting order fulfilment process.

**Screen Recording**
![Jan-28-2024 12-26-50](https://github.com/frappe/erpnext/assets/9102676/cf5f62a2-d0a5-4d38-8c0e-1213ae7b89a8)

### Module

stock

### Version

```
ERPNext: v15.10.6 (version-15)
Frappe Framework: v15.11.0 (version-15)
```

### Installation method

None

**Comment by rohitwaghchaure** [comment]
@rknroot I have tried to replicate the issue but not able to replicate it.

1. Created Iphone 15 item and enabled Has Serial No and Has Batch No
<img width="1313" alt="image" src="https://github.com/frappe/erpnext/assets/8780500/4b9f6ebf-5b5c-44c6-ba6d-40f78dac342d">


2. Created 3 Warehoues (WHT-1, WHT-2, WHT-3)

<img width="1319" alt="Screenshot 2024-02-01 at 1 01 42 PM" src="https://github.com/frappe/erpnext/assets/8780500/85d209c7-1e9f-4f87-bab9-ff2033cb58ab">


3. Created purchase receipt for item Iphone 15 with 500 qty in each warehouse
<img width="1339" alt="Screenshot 2024-02-01 at 1 03 54 PM" src="https://github.com/frappe/erpnext/assets/8780500/4706ad9d-b72d-4c52-9221-bae900fb5e1c">


4. Created Sales Order for item Iphone 15 with 500 qty and WHT-1 warehouse

<img width="1343" alt="Screenshot 2024-02-01 at 1 56 17 PM" src="https://github.com/frappe/erpnext/assets/8780500/2256d8ce-cc72-4f76-96f7-30a134f7b428">

5. Then created Pick List successfully against the above Sales Order 

![pick_list_bundle](https://github.com/frappe/erpnext/assets/8780500/b57383a3-e257-4e7e-afd5-5f4109be34e9)

**Comment by rknroot** [comment]
@rohitwaghchaure Try without Serial No. 
This problem is for the items with only batch numbers.

**Comment by rohitwaghchaure** [comment]
Fixed https://github.com/frappe/erpnext/pull/39826
