### ISSUE TITLE
Gantt Chart Print Format

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#3960]
Requested by: Michael, ThermaDynamics

Gantt Chart report doesn't have any print format, or option to convert it into PDF file. Please add print option for Gantt Chart report.

**Comment by mithinr** [comment]
+1 for this feature, Also export to xls or cvs

**Comment by Kozlov-V** [comment]
+1 pdf

**Comment by Shak88** [comment]
+1 pdf

**Comment by Mexarm** [comment]
can we have it added to the project printed version in pdf

**Comment by Devens** [comment]
Very Important. +1

**Comment by Tropicalrambler** [comment]
+1

**Comment by elvislam** [comment]
+1 Extremely important, please add it.

**Comment by umairsy** [comment]
@netchampfaris will this feature be available in upcoming upgrade?

**Comment by netchampfaris** [comment]
@umairsy Will try

**Comment by Devens** [comment]
+ 1

Regards,
Deven Shah
098250 60116

**Comment by addymuliady** [comment]
+1

**Comment by netchampfaris** [comment]
So, this is not very easy to implement. Please make do with screenshots. Closing for now.

**Comment by dawoodjee** [comment]
+1
