### ISSUE TITLE
search in all of erpnext 

### ISSUE THREAD

**Issue by negini** [frappe/erpnext#3961]
Hi 
I believe if add search in erpnext to searching in all system  it's help to improve software , for example some one  want to search for one word to find it's lead name / name / customer name / tel / item name or ... 
same search there is in Vtiger CRM or Odoo .

**Comment by yashodhank** [comment]
Yeah, this feature is being loved by many people and might be one of the reason, Vtiger and Odoo is gaining more interest and attention too..
:+1:

**Comment by rmehta** [comment]
You can use the awesome bar to search.

Use the keyword "in". For e.g. "test in Customer" then it will search in that form.

**Comment by yashodhank** [comment]
@rmehta searching by phone number or mobile number using awesome bar search will be really helpful addon.

**Comment by strixaluco** [comment]
Implemented via https://github.com/frappe/frappe/pull/2710
