### ISSUE TITLE
Rename issue

### ISSUE THREAD

**Issue by keerthanamuruge** [frappe/erpnext#39645]
### Information about bug

CRM Module:

Where not able rename the lead on production mode.

Select allow rename on doctype:

![image](https://github.com/frappe/erpnext/assets/86115511/0d77055c-3980-47e8-8bc3-728f5b44d6a4)

![image](https://github.com/frappe/erpnext/assets/86115511/72949c26-2a6f-418e-a158-0147eca9206a)

same window popup. It get saved but the lead is not renamed. Not throw any error also.

**Developer mode**
![image](https://github.com/frappe/erpnext/assets/86115511/d270fc96-b79a-4486-a284-fdcff6ae19d6)
Screen itself change and it is working

### Module

CRM

### Version

Version
Frappe:  14 latest
Erpnext: 14 latest
Hr: 14 latest.

### Installation method

docker

**Comment by keerthanamuruge** [comment]
Rename issue on lead

**Comment by Nihantra-Patel** [comment]
Hi @keerthanamuruge,

It's not a bug, if you want to rename the document ID then you must enable the option "Allow Rename" in Lead doctype or other doctype which you want to change.

but in your case, you want to change the title so the title is basically from the company name or full name (lead_name). so please check it. so if you change the first, middle, and last name then automatically title will change.

https://github.com/frappe/erpnext/blob/5e71d6ac4ea187e386e5b8cde83b64d71d42488c/erpnext/crm/doctype/lead/lead.py#L148-L149

I hope this helps.

Thank You!
