### ISSUE TITLE
Bug in customizing doctype Lead / Opportunties DocType Open Activities HTML and Comments

### ISSUE THREAD

**Issue by mikibudhiraja** [frappe/erpnext#39644]
### Information about bug

I was trying to customize layout of Lead doctype, and I dragged the open_activities_html field to the details section and saved it. It didn't solve my purpose as I wanted a clear view of activities when a lead is open, on the right side of the screen.
And when I put the open_activities_html field back in the activities tab, the document stopped showing lead activity (both Open as well as All activities) along with the comments section.
![Screenshot from 2024-01-30 19-34-32](https://github.com/frappe/erpnext/assets/306154/10d7baf4-7b22-44d9-8f59-393f4b1bd927)
![Screenshot from 2024-01-30 19-34-52](https://github.com/frappe/erpnext/assets/306154/8aa08b67-31b4-479a-a80e-60b33570f262)
![Screenshot from 2024-01-30 19-35-14](https://github.com/frappe/erpnext/assets/306154/ca5452e4-93bd-45db-a610-67c4d0ea5f6e)

### Module

CRM

### Version

Frappe Framework: v15.11.0 (version-15)
ERPNext: v15.10.8 (version-15)

### Installation method

None

**Comment by Nihantra-Patel** [comment]
Hi @mikibudhiraja,

I have tested in the latest ERPNext version 15 but we haven't any type of issue.

Please check the video.

https://github.com/frappe/erpnext/assets/141945075/9a6fa914-1f84-4019-b0cf-cf60cf6ff498

Thank You!

**Comment by mikibudhiraja** [comment]
Hi,
I rechecked everything, but still it hasn't been sorted. Can you suggest me to share any logs that would help trace the problem? Everything related to HTML fields haven't been working in the DocType Lead.
