### ISSUE TITLE
[Paid Development]  problems regarding delivery notes for serialized items

### ISSUE THREAD

**Issue by negini** [frappe/erpnext#3967]
I have encountered some problems regarding delivery notes for serialized items.

We have noticed that when making delivery note, the serial numbers was
automatically there in the serial number box.

We again need to delete the serial numbers automatically entered in the delivery
note and input again the actual serial numbers that has been delivered to
customers.It is too risky for new users not to notice the serial numbers and directly submitted
the document. Serial numbers are essential for us since we are using it for warranty purposes.

Would it be possible to make that serial numbers’ box blank so that we can just enter
the serial numbers manually to avoid this kind of error??
It's make too much problem when some one make delivery note for serials items .

**Comment by negini** [comment]
hi , any reply for that ?

**Comment by rmehta** [comment]
@negini sorry for the late reply. Serial Nos are automatically selected on basis of FIFO. Do you want us to make that a setting? This should be < 1hr. Can you sponsor $100?

Thanks!

**Comment by negini** [comment]
Hi rmehta
Ok  , i'll be sponsor for this option , i request after add this option update my erpnext to that version too . 
Please send invoice to meisam@shoukinet.com . 
Regards

**Comment by rmehta** [comment]
@negini pushed a fix. Will send you an invoice. Thanks!

**Comment by negini** [comment]
Thanks , please share your email or Skype id too .

**Comment by negini** [comment]
Hi
Still i don't receive invoice , please check .

**Comment by rmehta** [comment]
@negini we will send you monday :)

Our skype id is "erpnext"
