### ISSUE TITLE
Setup wizard fails: V15.11.1

### ISSUE THREAD

**Issue by maovidal** [frappe/erpnext#39704]
### Information about bug

Selecting:
- Colombia
- Default accounts
- English / Spanish
- And my email, password, company name, etc.

I get an Stuck Wizard like this:

![ERPNext_Error_Setup](https://github.com/frappe/erpnext/assets/13444566/800120e1-c0fc-473a-ba3c-b4554d1daade)

I've also experienced this with another browser and V15.11.0 and reported it here (It has an screen shoot of the message): https://discuss.frappe.io/t/setup-wizard-fails-erpnext-v15-11-0-frappe-framework-v15-12-0/116665

I have tried Safari, Chrome, Firefox.

### Module

accounts, stock, buying, selling, HR, projects, support, CRM, assets, integrations, quality, regional, portal, other

### Version

ERPNext: v15.11.1
Frappe Framework: v15.12.0
Frappe HR: v15.10.0
Payments: v0.0.1

### Installation method

docker

### Relevant log output / Stack trace / Full Error Message.

- Firefox does not report any error on its Console.

- Safari Console shows:

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1684, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
TypeError: setup_complete() missing 1 required positional argument: 'args'
```

- Chrome console shows:

```shell
Failed to load resource: the server responded with a status of 524 ()
request.js:362 Unable to handle failed response
request.js:363 TypeError: Cannot read properties of null (reading 'setup_wizard_failure_message')
    at SetupWizard.abort_setup (setup_wizard.js:218:27)
    at Object.error [as error_callback] (setup_wizard.js:199:22)
    at Object.<anonymous> (request.js:360:33)
    at I (jquery.js:3213:31)
    at Object.fireWith [as rejectWith] (jquery.js:3343:7)
    at en (jquery.js:9619:14)
    at XMLHttpRequest.<anonymous> (jquery.js:9878:9)
(anonymous) @ request.js:363
I @ jquery.js:3213
fireWith @ jquery.js:3343
en @ jquery.js:9619
(anonymous) @ jquery.js:9878
```

**Comment by maovidal** [comment]
BTW, found these issues which mention similar problems: #16898 #17883, even they may not have the same cause.

**Comment by OneGreenDiary** [comment]
This has worked for v15

bench config http_timeout 6000
bench setup supervisor
bench setup nginx

sudo supervisorctl reload
sudo service nginx reload

**Comment by maovidal** [comment]
Thank you @OneGreenDiary !
I'm closing this for now, as I'm not able to replicate this issue at the moment.
