### ISSUE TITLE
(Paid Development) Add "Target Warehouse" to Delivery Note Packed Items

### ISSUE THREAD

**Issue by sliska** [frappe/erpnext#3970]
Hi, 

We sell some product bundles with components that need to be transferred from our central warehouse to a "rented" warehouse so that we can depreciate them. 

1. We'd like the Delivery Note Packed items section to have a "Target Warehouse" feature. 

If Next had a "Target Warehouse" feature in the packed items section of the Delivery Note then we would not have to remember to create a material transfer every time a certain product bundle is sold. 

How much would it cost and how long would it take to develop this feature?

thank you very much!
Sofia

**Comment by rmehta** [comment]
@sliska 

- [ ] We will have to add Target Warehouse field in the Delivery Note and update the mapping with Stock Entry
- [ ] For Serialized Items, we will have to remove the "Status" as Delivered so that the Item can be brought back from the delivered warehouse.

Can you sponsor $200? Thanks

**Comment by sliska** [comment]
Hi @rmehta ,

Yes, sounds good. How do I proceed? 

Will the target warehouse field appear per serialized item? We need to be able to apply the target warehouse to packed items primarily but also to the main items. 

thanks

**Comment by rmehta** [comment]
@sliska Thanks! please drop in a mail at hello@erpnext.com with your email id. We will send you a Paypal Invoice.

**Comment by sliska** [comment]
Hi @rmehta, was this development successful?

**Comment by rmehta** [comment]
Merged to develop. There was a test-case that took half a day to fix. Hoping to release tomorrow or early next week.

**Comment by sliska** [comment]
thank you!

**Comment by sliska** [comment]
Hi Rushabh, when can we have a look at this?

thanks!
Sofia

**Comment by rmehta** [comment]
This is done and released!
