### ISSUE TITLE
Tree structure support for department

### ISSUE THREAD

**Issue by eezhangjianwei** [frappe/erpnext#3977]
Many companies including mine have tree structure departments, so can erpnext support this ?

like xtools crm:

![image](https://cloud.githubusercontent.com/assets/7467437/9655672/75374b6e-5265-11e5-8e04-9f1786506322.png)

Thanks a lot .

**Comment by yashodhank** [comment]
Somebody have already attempted to developed a module and available on github, maybe considered in future. Closing for now.
