### ISSUE TITLE
Modify Cheque Printing format to show Payee Address & Invoice details

### ISSUE THREAD

**Issue by ekpaxp** [frappe/erpnext#3978]
Hi, it would be good if the Cheque printing format was able to show the payee address as well as a list of Invoices Numbers, Invoice Date & Invoice Amounts if the Payment Tool is used to make a single payment for multiple invoices.

**Comment by nabinhait** [comment]
Now you can create your own custom cheque printing format using "Account -> Cheque Print Template".
