### ISSUE TITLE
Remove Default Filter on List View in V15

### ISSUE THREAD

**Issue by BHAGYASHRIMHASKE** [frappe/erpnext#39796]
### Information about bug

In most of list views in V15 there're default filters. Like on Sales Order there is two default filters so users causing confusion, is there draft entry will save or not that's why duplicate draft entries are created.

And that comes with extra support calls about records not being seen, because of the filters.

<img width="635" alt="image" src="https://github.com/frappe/erpnext/assets/138584686/23a4160e-7f39-4d35-87b3-53206833cb8c">
<img width="626" alt="image" src="https://github.com/frappe/erpnext/assets/138584686/965aa271-61f7-4707-bfdb-652a689f2378">

### Module

accounts, stock, selling

### Version

<img width="193" alt="image" src="https://github.com/frappe/erpnext/assets/138584686/027bc990-223e-44f2-a22f-c5eece00f4a6">

### Installation method

manual install

**Comment by ankush** [comment]
These are not default filters, these are filters you last used.

**Comment by BHAGYASHRIMHASKE** [comment]
Thanks ankush, but these filters are not used by us, If you check on any V15 site on sales order there is default filter.

**Comment by BHAGYASHRIMHASKE** [comment]
Or if you saying these last used filters then how we can remove this to not set next time by default?
