### ISSUE TITLE
Letter head not printing in PDF

### ISSUE THREAD

**Issue by perotom** [frappe/erpnext#39806]
### Information about bug

This issue was never resolved and is still present in the current version: https://github.com/frappe/erpnext/issues/31207
It affects all pdf documents.

### Module

All

### Version

ERPNext: v15.12.2 (version-15)
Frappe Framework: v15.13.0 (version-15)

### Installation method

None

**Comment by klw-sc** [comment]
Hi peretom, you may have the wrong version of wkhtmltopdf, depending on what OS you have installed, check the current version using:

wkhtmltopdf --version

if it does not return the following:

wkhtmltopdf 0.12.6.1 (with patched qt)

then you need to upgrade to the latest version, for Ubuntu you can use:

wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-2/wkhtmltox_0.12.6.1-2.jammy_amd64.deb
sudo apt install -f ./wkhtmltox_0.12.6.1-2.jammy_amd64.deb

hope it helps.

**Comment by perotom** [comment]
It was not related to wkhtmltopdf but the print setting `Repeat Header and Footer`. If this option is enabled, not letter head will be print. Very strange.

**Comment by perotom** [comment]
https://github.com/frappe/erpnext/issues/31207#issuecomment-1616369709
