### ISSUE TITLE
Chinese characters shown incorrect in exported .cvs file

### ISSUE THREAD

**Issue by chaoyee** [frappe/erpnext#3982]
As title, when data exported from export utulity, Chinese characters shown incorrect in exported
May be it happens in double-byte character sets. Please help!

![2015-09-04 3 56 22_1](https://cloud.githubusercontent.com/assets/2167909/9679256/98dc7d0e-531f-11e5-8477-25a5a039ff3a.png)

**Comment by Gleisson03** [comment]
Search on Google how to import CSV files. Typically, this problem happens when we choose the wrong character encoding.

**Comment by vrms** [comment]
this seems to be obsolete and also more a question then an issue.
Closing this therefore
