### ISSUE TITLE
Feature Request: Turning Notes into a basic Wiki

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#3985]
I believe that notes would be a great place to put company information just like in a wiki. For this it would be great if one had the opportunity to categorize things into a hierarchies and subfolders as well as a easier way for linking to other pages.

**Comment by cgpurbaugh** [comment]
This is a good idea, I wish I had thought of this.  Wikis are open source as well, it might be an easy integration.

**Comment by dottenbr** [comment]
I think this is related to my question here https://github.com/frappe/knowledge_base/issues/3 if the Knowledge Base App is Depreciated of Active. I think the basics would be simple linking between articles and some sort of hierarchy. That would be pretty much all one needs.
