### ISSUE TITLE
multi-company auto fetch from global defaults issue

### ISSUE THREAD

**Issue by bhattdevarsh** [frappe/erpnext#39867]
### Information about bug

Steps to replicate:
1. Create multiple Companies under Company doctype.
2. Set a Global Defaults for the company.
3. Come back to _Non-default Company_ form.
4. Click on any Link field which has Company field under {option} doctype and click on Create a New {doctype}.
5. One will find the Company is already set with reference of Global Default.

The issue is if I am creating new document for `Company 1` let say, and the default company is `Company 2`, in that case "Create a New {doctype}" auto populate the `Company 2` (default company) and will now allow to edit back to `Company 1`(read only).

Desire output:
The company field should be editable OR the company name should be auto populate the company name from Create New doctype is being triggered and not the Global Default company.

![multi-company-issue-2](https://github.com/frappe/erpnext/assets/58166671/5ba948b9-9900-449f-9a79-e04ca530b021)

### Module

accounts, other

### Version

Behavior can be observed on 
ERPNext: Version-14 and Version-15

### Installation method

manual install

**Comment by donnieferdian** [comment]
@bhattdevarsh have you try this ??
<img width="251" alt="Session Default" src="https://github.com/frappe/erpnext/assets/109821040/a9a8a0ec-d414-49f9-8d4c-da851dcf5bb6">
