### ISSUE TITLE
All Trend Report Filters not loading on refresh event V15

### ISSUE THREAD

**Issue by niyazrazak** [frappe/erpnext#39865]
### Information about bug

To replicate the issue:

1. Refresh the page.
2. Search for any Trend Report directly from the search bar or refresh the page from any trend report.

![image](https://github.com/frappe/erpnext/assets/76736615/3a999326-245c-4d77-9110-14f53ea58e6b)
![image](https://github.com/frappe/erpnext/assets/76736615/f4ce2824-0816-4e26-8568-c6c585c03d6b)

I think Asset taking time to load on refresh

### Module

accounts, buying, selling

### Version

Frappe version -15
ERPNext Version - 15

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Asset Not loading
```

**Comment by donnieferdian** [comment]
same problem,...
