### ISSUE TITLE
Bug: Outstanding amount and status do not get updated when a credit note is issued against the invoice

### ISSUE THREAD

**Issue by Jeevansyriac** [frappe/erpnext#39889]
### Expected
**Paid invoice**
- outstanding amount goes negative
- status changes to 'credit note issued'

**Unpaid invoice**
- outstanding amount becoms zero
- status changes to 'credit note issued'

### Module

accounts, selling

### Version

Frappe v14.64.0
ERPNext v14.61.3

### Installation method

None

**Comment by Jeevansyriac** [comment]
https://github.com/frappe/erpnext/assets/95610320/fec0e4a8-d043-4636-8054-6e315e5c4271

**Comment by Jeevansyriac** [comment]
@ankush

**Comment by lympik** [comment]
I can confirm, the issue also exists on v15.14.0. Sales invoice status isn't changed when credit note is issued.

**Comment by perotom** [comment]
I have the same issue. Probably related to https://github.com/frappe/erpnext/issues/38305 ?

**Comment by rtdany10** [comment]
@ruthra-kumar @deepeshgarg007 
Credit Note against Is POS invoice doesn't work as expected. It shows wrong values.
Scenarios tested:
1. Main Invoice with Is POS checked and Credit Note with Is POS checked - main invoice shows wrong outstanding figure
2. Main Invoice with Is POS checked and Credit Note with Is POS unchecked - outstanding is not updated in main invoice and hence payment entry can't be created

**Comment by ruthra-kumar** [comment]
Post [this change](https://github.com/frappe/erpnext/pull/39497), from v14.61.3 and above, one additional step is required. Credit/Debit note has to be reconcilied against the Parent Invoice through the Payment Reconciliation tool. A popup has been added to inform about this additional step(https://github.com/frappe/erpnext/pull/39943).


for more context: https://github.com/frappe/erpnext/pull/35330

**Comment by perotom** [comment]
Seems to work but creates a lot of room for error. To mitigate this errors it would be a very good idea to get back the default behaviour of version 13 which automatically did this extra step.
Optionally one could add an extra checkbox `reconcile with original invoice` which would do exactly that.

**Comment by ruthra-kumar** [comment]
> Seems to work but creates a lot of room for error. To mitigate this errors it would be a very good idea to get back the default behaviour of version 13 which automatically did this extra step. Optionally one could add an extra checkbox `reconcile with original invoice` which would do exactly that.

What would you think is a better option?
System level checkbox that applies for all Credit/Debit notes? or a checkbox on Credit/Debit notes which allow for control at the Individual Credit/Debit notes

**Comment by perotom** [comment]
I think a checkbox for individual credit/debit notes would be best. This way, it is possible to set default values and visibility for this checkbox easily in doc form editor.

**Comment by ALI159-CLOUD** [comment]
![Screenshot 2024-03-06 144224](https://github.com/frappe/erpnext/assets/75094361/7f917b41-712e-40dc-b9b4-8c2cd6bac551)
 
i can confirm this issue too, i attach test case with same issue

**Comment by ALI159-CLOUD** [comment]
[invoice return.MP4.zip](https://github.com/frappe/erpnext/files/14510592/invoice.return.MP4.zip)

this video illustrate the issue.

**Comment by ALI159-CLOUD** [comment]
https://github.com/frappe/erpnext/assets/75094361/2907acdc-3c6e-445e-801e-dd6600513dd5


this video illustrate the issue.

**Comment by ismael-alkrad** [comment]
I have the same issue, 
I wish to solve it faster

**Comment by ruthra-kumar** [comment]
> I think a checkbox for individual credit/debit notes would be best. This way, it is possible to set default values and visibility for this checkbox easily in doc form editor.

An Invoice level checkbox is added to allow better control.
<img width="1552" alt="Screenshot 2024-03-19 at 9 51 30 AM" src="https://github.com/frappe/erpnext/assets/3272205/064b146a-7bd1-40aa-a6dd-c09005de9b2c">
