### ISSUE TITLE
Cannot add an item to a sales invoice

### ISSUE THREAD

**Issue by stevenyaga** [frappe/erpnext#3993]
When selecting an item to add to a sales invoice, i get a message "Please specify: Customer. It is needed to fetch Item Details." This is after i have already selected the customer before i even click the "Add new row" button.

**Comment by anandpdoshi** [comment]
Which ERPNext version are you using

**Comment by stevenyaga** [comment]
I am using Version v6.0.1

**Comment by anandpdoshi** [comment]
I am unable to reproduce this error, you can try on demo.erpnext.com

Do you have any customizations like custom fields / scripts in the sales
invoice form? Also look for any errors in the browser's console.

**Comment by stevenyaga** [comment]
I restarted my computer and now it is working. I did not manually clear the browser cache.
