### ISSUE TITLE
Enhancement: Print Footer for PDF Files

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#3994]
Please add the functionality to define a print footer in Letter Head Doctype.

http://stackoverflow.com/questions/1360869/how-to-use-html-to-print-header-and-footer-on-every-printed-page

![image](https://cloud.githubusercontent.com/assets/9136094/9729492/12b9f96a-5610-11e5-887f-dae39921914b.png)

**Comment by MaxMorais** [comment]
There I have a way of control it in weasy-print https://gist.github.com/MaxMorais/5783051

**Comment by dottenbr** [comment]
Currently being discussed as paid feature implementation https://discuss.erpnext.com/t/header-footer-development/7442/19

**Comment by anandpdoshi** [comment]
Fixed in PDF!
