### ISSUE TITLE
Accounting Reposting on sales invoice is throwing Error. 

### ISSUE THREAD

**Issue by ahsansowaan** [frappe/erpnext#39959]
### Information about bug

Updating GL accounts and cost center on sales invoice after submission, The reposting is throwing following error message.

![image](https://github.com/frappe/erpnext/assets/151606274/a96e3577-5937-40aa-adf1-3ccb586d41c2)

![image](https://github.com/frappe/erpnext/assets/151606274/894a1400-8767-4af0-a44e-d2bde505db49)

please help

### Module

accounts

### Version

15.2

### Installation method

None

**Comment by GursheenK** [comment]
This occurs due to a missing configuration.

You can open **Repost Accounting Ledger Settings** and allow reposting ledger entries for the **Sales Invoice** DocType.

<br>

><img width="1314" alt="Screenshot 2024-02-19 at 2 03 58 PM" src="https://github.com/frappe/erpnext/assets/40693548/87307d0b-0c81-420f-ae84-12e61ad75154">

<br>

Bad error message already fixed via https://github.com/frappe/erpnext/pull/38081

**Comment by ahsansowaan** [comment]
Only administrator role can reach to this docytpe.

Thanks
