### ISSUE TITLE
Discrepancy in purchase invoice naming

### ISSUE THREAD

**Issue by fadilsiddique** [frappe/erpnext#39965]
### Information about bug

Found out that purchase invoice naming is not proper. Lets say I have total invoice of 273 and the purchase invoice naming series is PI - {#####}, it is supposed to be PI - 00273, but it is showing the number of sales invoice i.e if my last sales invoice naming is SI - 03234, then next purchase invoice id will be PI - 03235. There is no document naming rule or no custom script is running for naming.

### Module

accounts, buying, selling

### Version

Frappe Version - 15.13.0
ERPNext Version - 15.13.0
![WhatsApp Image 2024-02-17 at 6 02 36 PM](https://github.com/frappe/erpnext/assets/48912196/c530efb3-f880-4a06-8d39-115b48a1610d)

### Installation method

FrappeCloud

**Comment by ankush** [comment]
can you go to customize form and share what's value of "autoname"?

**Comment by fadilsiddique** [comment]
> can you go to customize form and share what's value of "autoname"?

@ankush 

Sales Invoice

![Sales-Invoice (1)](https://github.com/frappe/erpnext/assets/48912196/39d3efff-0005-4519-9ded-5c9208ead0cc)

Purchase Invoice

![Purchase-Invoice](https://github.com/frappe/erpnext/assets/48912196/b9ec1514-f3ae-4795-968a-d692696e84a2)

**Comment by ankush** [comment]
`format:` naming uses shared counter, this is counter intuitive and we need to remove it.

Use naming series field or plain series to avoid this.
