### ISSUE TITLE
Search_Fields for Delivery Note is NOT WORKING

### ISSUE THREAD

**Issue by jof2jc** [frappe/erpnext#3997]
Using latest v6.0.1, Search_Fields which are defined under Customize Form > Delivery Note are not searchable..whatever fields we put in search_fields. Search Dialog always shows DN no and Customer Name only.

I notice this only happens with Delivery Note..others like Sales Order, Purchase receipt etc are working well. SO I think this is a 'Bug'

Below picture is the example when we want to create Sales Invoice from Delivery Note via Get From Delivery Note popup window

![get from delivery note](https://cloud.githubusercontent.com/assets/12841357/9737539/51afbf36-5671-11e5-8df0-0fb673efab5e.png)

**Comment by jof2jc** [comment]
Not resolved yet?

**Comment by rmehta** [comment]
Can you fix this or sponsor this?. We are already working on a lot of issues.

**Comment by jof2jc** [comment]
@rmehta If I'm a programmer, surely I will fix this.. This is minor issue, can you help? Or you can help with some hints...maybe other community developer can fix this.. Thanks

**Comment by rmehta** [comment]
@jof2jc you need to incentivize the "community" in some way. Maybe help us in answering questions on the forum. Maybe write a few blog posts. Communities need care and effort to be build.

**Comment by jwrober** [comment]
I think this issue is outdated. v8.x has tons of search features now in the code and the user interface is totally different than v6.
