### ISSUE TITLE
Coupon code based pricing rules are auto applied without checking the coupon code entered in sales order

### ISSUE THREAD

**Issue by Rajesh2445** [frappe/erpnext#40013]
### Information about bug

Add two pricing rules & create coupons for the same
Item 1 - Discount 10%
Item 2 - Discount 25%

In sales order add both Item 1 & Item 2. Apply coupon for Item 1, instead of applying only 10%, it applies both pricing rules in the sales order

### Module

selling

### Version

Frappe 14

ERP latest

### Installation method

None

**Comment by nikolas-beckel** [comment]
Push. ⬆️
Is there any news in this regard?

**Comment by nikolas-beckel** [comment]
I debugged the code a little bit and I think I found the bug. Line 389 in `pricing_rule.py` checks whether a price rule is coupon_code_based (pricing_rule.coupon_code_based == 1). If this is the case, it is only checked whether any coupon code is set in the args parameter (args.coupon_code). However, there is no specific check as to whether the coupon code used is actually linked to the price rule.
As a result, all price rules with coupon_code_based == 1 that fulfil the other conditions are applied as soon as a coupon code is entered - regardless of whether this code applies to the respective price rule.

![image](https://github.com/user-attachments/assets/2a24b9ce-b45e-4f75-a183-00c9e94efb2e)

At the beginning of the loop pass via the pricing_rules, it should be checked whether the pricing_rule is coupon_code_based. If this is the case, a database query should be used to verify whether this pricing rule is actually linked to the transferred coupon code. If there is no match, the pricing rule can be skipped as it is not relevant.

![image](https://github.com/user-attachments/assets/027066a8-d891-476a-85a3-41b70d2553cb)

I don't know whether this has side effects that I'm just overlooking. Or is the approach generally wrong?
Btw: I am also on version 14.

Maybe you can help us with this problem: @deepeshgarg007 @ruthra-kumar @sagarvora @Nihantra-Patel 🫶
