### ISSUE TITLE
Supplier Section Missing for Purchase Invoice

### ISSUE THREAD

**Issue by bohlian** [frappe/erpnext#4005]
For default setup, in the Purchase Order Form there is a Section Break called supplier_section which is placed as the first field:

![image](https://cloud.githubusercontent.com/assets/8383249/9783663/b77c3296-57d8-11e5-9475-9904a3981296.png)

However, in the Purchase Invoice Form the supplier_section Section Break is missing. This should be added:

![image](https://cloud.githubusercontent.com/assets/8383249/9783682/e1cf9c90-57d8-11e5-8b7e-95c851ab9528.png)

**Comment by rmehta** [comment]
@bohlian The first section break is optional. Is there any specific reason you want it?

**Comment by bohlian** [comment]
@rmehta Initially I thought I would require it to detect the first section for a custom print format, but after some testing I realised you are right, the first section can still be detected when using the "page" variable.

I suppose, the only reason why I think it would be required is just for consistency of the form between Purchase Order --> Purchase Invoice like how Sales Order --> Sales Invoice has the same first section.
