### ISSUE TITLE
Feature Reaquest / Paid Development: Log transection into a libility account insted of income account until delivery is compleated for service based organization

### ISSUE THREAD

**Issue by inventobd** [frappe/erpnext#4006]
If I create a sales invoice for an sales order, system log the invoice amount immediately to income account . But as a service based organization it take me time to provide/deliver that service/group of service to customer . Maybe I can fail too . So Until I deliver it I don't want to log the sales amount to my income head because sales is not realized until I deliver it , instead of that I want it to log under a liability account until I deliver it , and after successful delivery I can adjust liability and income account. 

Here is the current process 

If I sale a service package of 50,000 to a customer which will took me 1 month to deliver and rise invoice of 50,000 to the customer:

    Account Receivable - (Dr) 40,000
    Cash - (Dr) 10,000 (Advance)
    Income - (Cr) 50,000

but according to this business until we deliver it to client sale is not realized and transaction will not log under Income head , rather than that it will be logged under a liability account called unrealized sales.

I want my transactions to be like this

Accounting treatment – e.g. package @ Tk 50000 with booking money paid of Tk 5000

    Cash/Bank Debit 5000

    Account receivables (Debtors) Debit 45000

    Unrealised Sales Credit 50000 (Liability account)

Step 2: Partial payment received from client

    Cash/Bank Debit 20000

    Accounts receivable Credit 20000

Step 3: Final Accounting treatment for the package sale

    Cash/Bank Debit 25000

    Accounts receivable Credit 25000

    Unrealised sale Debit 50000

    Income Credit 50000

I have already posted this to forum , and If its not possible with current process you can take it as a feature request . And if it not takes too much I can sponsor this also for a paid development . 

Forum post : https://discuss.erpnext.com/t/revenue-recognition-principle-terms-for-erpnext/7325
Realization: http://accounting-simplified.com/financial/concepts-and-principles/realization.html

**Comment by nabinhait** [comment]
Fixed. 

https://discuss.erpnext.com/t/manual-accounting-entry-after-sales-invoice-submission-insted-of-auto-entry/7772/15
