### ISSUE TITLE
ERPNext developers guide

### ISSUE THREAD

**Issue by stevenyaga** [frappe/erpnext#4008]
Hi,

I want to use ERPNext for developing an application. Any link on a developer's guide. This link https://frappe.io/developers seems to be broken. I have read that it is possible to use hooks.py but i cant seem to get my way round it. Any help will be appreciated

Regards

**Comment by yashodhank** [comment]
@stevenyaga Best Place to ask any questions is dedicated ERPNext community forum @ https://discuss.erpnext.com or Dedicated Chat Room: https://gitter.im/frappe/erpnext

Github -> Issues are only used to report technical issues related ERPNext.
Please close this issue.

**Comment by rmehta** [comment]
Try https://frappe.io/tutorial
