### ISSUE TITLE
Associating a single contact with multiple customer

### ISSUE THREAD

**Issue by manivk** [frappe/erpnext#4010]
Hi

We have a situation where very often, we have consultants and freelancers who work with different organizations (schools in this case) and give us orders. In this case, these freelancers are contacts associated to multiple organizations. Currently Erpnext does not allow a contact to be associated to multiple customers. We also do not want to create duplicate contacts as it creates further issues as we would not know in the future that it is the same contact. 

We require the ability of associating a single contact with multiple customers.

Mani.

**Comment by MaxMorais** [comment]
Use the Sales Partner for this, not the Contact

**Comment by manivk** [comment]
Thanks for the input - sales partner is an option - will explore this and see if it works for us - will work mostly for the freelancers and dealers. Issue is that we still have instances where the same contact works in 2-3 schools at the same time - it does create issues as they are not exactly sales partners....they are contacts in all these organizations working in them.
