### ISSUE TITLE
Subcontracting order reference not coming in stock ledger report/Unable to add Subcontracting order column

### ISSUE THREAD

**Issue by Sunilmehra21** [frappe/erpnext#40112]
### Information about bug

Now in V14 subcontracting flow has been changed, and all the issue-receipt make against subcontracting order not purchase order. but in stock ledger report subcontracting order reference is not coming or we cant add it by a column option. so please add subcontracting order reference in this report. so we could add this column. 
![image](https://github.com/frappe/erpnext/assets/119653765/510b8b8d-f52b-40dd-8aaa-93bed6799394)
Regards
Sunil

### Module

stock

### Version

ERPNext: v14.62.3 (HEAD)
Frappe Framework: v14.65.0 (HEAD)
Frappe HR: v14.21.6 (HEAD)
India Compliance: v14.24.1 (HEAD)

### Installation method

None

**Comment by Sunilmehra21** [comment]
@rohitwaghchaure please check it

**Comment by s-aga-r** [comment]
@Sunilmehra21 Is this a custom report?

**Comment by Sunilmehra21** [comment]
@s-aga-r No, It is not customized report, it's stock ledger report with add some extra columns based on this standard stock ledger report.

**Comment by s-aga-r** [comment]
> @s-aga-r No, It is not customized report, it's stock ledger report with add some extra columns based on this standard stock ledger report.

@Sunilmehra21 You have added the Purchase Order custom field in the Stock Ledger Entry DocType. Similarly, you need to add the Subcontracting Order field to see the option to add it to the report.

**Comment by Sunilmehra21** [comment]
@s-aga-r we have not added any custom field in stock ledger entry doctype, you can see in Screen Shot
![image](https://github.com/frappe/erpnext/assets/119653765/c9312dcd-aab3-470e-986f-1d7659c8c37f)

Regards
Sunil
