### ISSUE TITLE
iOS app crashes on clicking generated HTML hyperlinks

### ISSUE THREAD

**Issue by superlack** [frappe/erpnext#4014]
Part of my "Projects" script includes a link generator for google maps based on a custom "project_address" field. 

It goes like this:

```
doc.map_link = "";
        doc.map_link =('<a href="http://maps.google.ca/?q=') + doc.project_address +('">') + doc.project_address + ('</a>');
}
```

"map_link" is a read only data field so it generates a clickable link when the project is saved.  It works well on a desktop browser, but when clicked inside the new iOS app, it crashes the entire phone.  Are there any other types of script that would be preferred?  

Thanks

**Comment by anandpdoshi** [comment]
I think you have to whitelist domains in the iPhone and android apps.
@rmehta can you confirm?

**Comment by superlack** [comment]
Interesting. How might a user or developer go about doing that?

**Comment by strixaluco** [comment]
Can this issue be closed?

**Comment by superlack** [comment]
Seems to work now.  Thanks
