### ISSUE TITLE
Purchase Invoice Submit issue

### ISSUE THREAD

**Issue by bhavyajicomputers** [frappe/erpnext#40146]
### Information about bug

Not able to submit purchase invoice and  Purchase receipt.  
![image](https://github.com/frappe/erpnext/assets/113116758/fed4eb8d-52da-42d2-9f41-610078f5b7a4)
![image](https://github.com/frappe/erpnext/assets/113116758/91b1f2b9-85ce-49ea-b4e1-3234c62b9d3b)

### Module

buying

### Version

frappe/frappe:version-15  v15.15.0
frappe/erpnext:version-15 v15.14.6
frappe/payments:version-15 Version : a3a84cd
frappe/hrms:version-15  v15.12.0
resilient-tech/india-compliance:version-15 v15.5.3
frappe/insights:main v2.1.2

### Installation method

Frappe Cloud

**Comment by rohitwaghchaure** [comment]
Fixed https://github.com/resilient-tech/india-compliance/pull/1756

**Comment by bhavyajicomputers** [comment]
Thanks

**Comment by Nihantra-Patel** [comment]
Please check on the latest version.
