### ISSUE TITLE
Repost Accounting Ledger Settings Blank

### ISSUE THREAD

**Issue by dineshpanchal93** [frappe/erpnext#40175]
### Information about bug

<img width="1358" alt="Screenshot 2024-02-28 at 1 34 27 PM" src="https://github.com/frappe/erpnext/assets/21578167/a9d072c0-2bbd-40fd-802f-0377a4dd5dfc">

### Module

accounts

### Version

ERPNext: v15.15.0 (version-15)

Frappe Framework: v15.15.0 (version-15)

Frappe HR: v15.12.0 (version-15)

India Compliance: v15.5.4 (version-15)

### Installation method

manual install

**Comment by Kevinizevbigie** [comment]
Also have the same issue.

**Comment by khushi8112** [comment]
@dineshpanchal93 @vinn2010

Looks fine to me.
<img width="1306" alt="Screenshot 2024-04-04 at 3 54 52 PM" src="https://github.com/frappe/erpnext/assets/142375893/e1736e4e-0d75-4eee-992d-9920a4ca5182">
