### ISSUE TITLE
Multi Currency bugs

### ISSUE THREAD

**Issue by bobzz-zone** [frappe/erpnext#4017]
i got bugs... on account payable .... there is currency errors ,
because in the amount column there should be CNY 73.400 but shown CNY
164.658.000 (kurs 1 CNY = IDR 2.243.3) on my data. my company currency
is IDR

i think the error is made when ledger for PI is created the GL entry is not right.....

also in supplier detail for example :
at the top
Total Billing This Year: Rp 172.891.131,00 / Total Unpaid: Rp 77.070,00

it should be CNY 77,070

**Comment by rmehta** [comment]
@bobzz-zone  Can you explain with screenshots?

**Comment by bobzz-zone** [comment]
![pinv](https://cloud.githubusercontent.com/assets/1543515/9903086/72ce8b48-5c9d-11e5-85b9-1ef9e5afb550.jpg)
![gl](https://cloud.githubusercontent.com/assets/1543515/9903098/877005fe-5c9d-11e5-9df8-54f33c06c3cb.jpg)
see in the inv... grand total is in CNY.... but in the ledger ....

**Comment by nabinhait** [comment]
General Ledger report shows balances in Party / Account Currency if filter is applied based on Party / Account. Otherwise, it shows values in company currency.

Sent pull request #4030 to fix dashboard in Customer / Supplier.
