### ISSUE TITLE
This bug is related to credit note. Pls checking adding Timesheet against customer and project > fetch timesheet in sales invoice > create credit note against same invoice. same issue in V15 also

### ISSUE THREAD

**Issue by RJMHASKE** [frappe/erpnext#40192]
@Nihantra-you are doing wrong testing. This bug is related to credit note. Pls checking adding Timesheet against customer and project > fetch timesheet in sales invoice > create credit note against same invoice. same issue in V15 also
<img width="789" alt="image" src="https://github.com/frappe/erpnext/assets/119041865/1582d6d8-844c-4ca7-baa9-436f5c478a28">

_Originally posted by @RJMHASKE in https://github.com/frappe/erpnext/issues/37583#issuecomment-1970666227_

**Comment by Nihantra-Patel** [comment]
Will check again, @RJMHASKE
