### ISSUE TITLE
Work order Status is not Changing 

### ISSUE THREAD

**Issue by maveezmh** [frappe/erpnext#40234]
### Information about bug

While creating work order i can see only 3 status Draft, Not startd and Completed. 

but when the work order process starts the in progress status is not getting updated.

![Screenshot 2024-03-02 at 12-50-44 Work Order](https://github.com/frappe/erpnext/assets/112148467/00b23780-afbf-4b79-9d42-18a67846610e)

Below is the setting defined in manufacturing settings for your reference

![image](https://github.com/frappe/erpnext/assets/112148467/7932f1e8-13c5-40b4-8e3a-a0650dbbfc76)

work order screen

![Screenshot 2024-03-02 at 12-53-21 3 PLY BRN-AR 210 X 210 X 120 MM - MFG-WO-2024-00005](https://github.com/frappe/erpnext/assets/112148467/299d2bf5-b707-4607-ab6c-1380dc7cae5a)

### Module

manufacturing

### Version

ERPNext: v15.15.0 (HEAD)
Frappe Framework: v15.16.1 (HEAD)
Frappe HR: v15.12.0 (HEAD)

### Installation method

FrappeCloud

**Comment by s-aga-r** [comment]
fixed: https://github.com/frappe/erpnext/pull/40407
