### ISSUE TITLE
Incompleted PO and SO documents, the HOLD and CLOSED buttons are not displayed.

### ISSUE THREAD

**Issue by JasonFu06** [frappe/erpnext#40261]
### Information about bug

The reason is that there are too few digits of decimal precision.
 
V15.15.0 takes two digits. And V13.52 takes 6 digits.

### Module

buying, selling

### Version

Frappe Version - 15.16.1
Erpnext Versiob - 15.15.0

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Erpnext Versiob - 15.15.0

			if(!in_list(["Closed", "Delivered"], doc.status)) {
				if(this.frm.doc.status !== 'Closed' && flt(this.frm.doc.per_received, 2) < 100 && flt(this.frm.doc.per_billed, 2) < 100) {
					if (!this.frm.doc.__onload || this.frm.doc.__onload.can_update_items) {
						this.frm.add_custom_button(__('Update Items'), () => {
							erpnext.utils.update_child_items({
								frm: this.frm,
								child_docname: "items",
								child_doctype: "Purchase Order Detail",
								cannot_add_row: false,
							})
						});
					}
				}
				if (this.frm.has_perm("submit")) {
					if(flt(doc.per_billed, 2) < 100 || flt(doc.per_received, 2) < 100) {
						if (doc.status != "On Hold") {
							this.frm.add_custom_button(__('Hold'), () => this.hold_purchase_order(), __("Status"));
						} else{
							this.frm.add_custom_button(__('Resume'), () => this.unhold_purchase_order(), __("Status"));
						}
						this.frm.add_custom_button(__('Close'), () => this.close_purchase_order(), __("Status"));
					}
				}


V13.52 - OK

			if(!in_list(["Closed", "Delivered"], doc.status)) {
				if(this.frm.doc.status !== 'Closed' && flt(this.frm.doc.per_received) < 100 && flt(this.frm.doc.per_billed) < 100) {
					this.frm.add_custom_button(__('Update Items'), () => {
						erpnext.utils.update_child_items({
							frm: this.frm,
							child_docname: "items",
							child_doctype: "Purchase Order Detail",
							cannot_add_row: false,
						})
					});
				}
				if (this.frm.has_perm("submit")) {
					if(flt(doc.per_billed, 6) < 100 || flt(doc.per_received, 6) < 100) {
						if (doc.status != "On Hold") {
							this.frm.add_custom_button(__('Hold'), () => this.hold_purchase_order(), __("Status"));
						} else{
							this.frm.add_custom_button(__('Resume'), () => this.unhold_purchase_order(), __("Status"));
						}
						this.frm.add_custom_button(__('Close'), () => this.close_purchase_order(), __("Status"));
					}
				}
```

**Comment by Nihantra-Patel** [comment]
Hi @JasonFu06,

Please check the PR: #36167

Ensure that all percentages are rounded to two decimal places.

The fields per_delivered, per_picked, per_billed, and per_received represent percentages that typically range from 0 to 100. If something has been delivered, picked, billed, or received at a rate greater than 99.99%, it's likely completed.

Previously, we used a precision of 6 in some cases. However, this meant that orders had to be extremely large for a value like 0.004% to have any significant impact on whether the order remained open.

For instance, if three payments, deliveries, or receipts were each at 33.333%, the transaction would still be considered unresolved because multiplying 33.333 by 3 doesn't equal 100 precisely. But when rounded to two decimal places, as in flt(33.333 * 3, 2), it equals 100.

But if you want, then you can override this thing using the client script.

Thank You!

**Comment by JasonFu06** [comment]
Dear all,
    Is it better to judge by the unfinished quantity or amount?
Thanks and Regards

Jason Fu - 符 漢

Mobile : 852 - 9755 8043 

    Nihantra C. Patel ***@***.***>) 在 2024年3月5日 星期二 GMT+8 下午02:36:07 寫道：  
 
 


Hi @JasonFu06,

Please check the PR: #36167

Ensure that all percentages are rounded to two decimal places.

The fields per_delivered, per_picked, per_billed, and per_received represent percentages that typically range from 0 to 100. If something has been delivered, picked, billed, or received at a rate greater than 99.99%, it's likely completed.

Previously, we used a precision of 6 in some cases. However, this meant that orders had to be extremely large for a value like 0.004% to have any significant impact on whether the order remained open.

For instance, if three payments, deliveries, or receipts were each at 33.333%, the transaction would still be considered unresolved because multiplying 33.333 by 3 doesn't equal 100 precisely. But when rounded to two decimal places, as in flt(33.333 * 3, 2), it equals 100.

But if you want, then you can override this thing using the client script.

Thank You!
