### ISSUE TITLE
Timestamps of all comments suddenly disappeared

### ISSUE THREAD

**Issue by KarymTaha** [frappe/erpnext#40267]
### Information about bug

The timestamps of the comments you can add at the bottom of every page suddenly disappeared. This affects all modules.

![Screenshot 2024-03-04 161639](https://github.com/frappe/erpnext/assets/150258535/4208bdeb-85cb-4bc7-8971-58c1c3250819)

### Module

other

### Version

ERPNext: v14.63.3 
ERPNext DATEV Integration: v14.1.1 
ERPNext Germany: v14.4.2 
ERPNext Shipping: v14.2.2 
Frappe Framework: v14.66.2 
Helpdesk: v0.10.0 
Frappe HR: v14.22.0 
PDF on Submit: v14.0.5 

### Installation method

None

**Comment by YamanQD** [comment]
We have the same bug
I hope this can be fixed quickly, since timestamps are necessary for comments

**Comment by YamanQD** [comment]
Any update on this?

**Comment by YamanQD** [comment]
Just updated to
`ERPNext: v14.65.3`
`Frappe Framework: v14.67.1`
and the bug is fixed

**Comment by s-aga-r** [comment]
fixed: https://github.com/frappe/frappe/pull/25315
