### ISSUE TITLE
Links in Sales order is not showing the right status

### ISSUE THREAD

**Issue by gohyc** [frappe/erpnext#4026]
I am using version 5.6.4. We realized that when we click the links menu in the sales order (may be some other documents), the sales invoice link is not showing the right status of the invoice. The invoice has not been paid (which is shown correctly when we use the sales invoice list. But in the link, it is showing paid. And sometimes, it just show submitted only.

**Comment by rmehta** [comment]
What do you mean by “links” can you show a screenshot?

**Comment by gohyc** [comment]
I have it mentioned in the forum and umair said he is able to reproduce and asked me to report it here as well.

And I also attached the screenshots here.

![capture5](https://cloud.githubusercontent.com/assets/7393911/9928713/929d2bd8-5d5a-11e5-8bf8-1f53554f6980.PNG)
![capture6](https://cloud.githubusercontent.com/assets/7393911/9928714/92a066b8-5d5a-11e5-9c88-7a49a86c3479.PNG)
![capture7](https://cloud.githubusercontent.com/assets/7393911/9928715/92a53724-5d5a-11e5-8d86-08a47d9fa344.PNG)

**Comment by rmehta** [comment]
Fixed now.
