### ISSUE TITLE
Purchase Receipt item rate changing on save

### ISSUE THREAD

**Issue by ishanloya** [frappe/erpnext#40277]
### Information about bug

When a purchase receipt is created from a Purchase Order, if I change the item quantity for an item, for some reason the item rate is also changing even though under Buying Settings "Maintain Same Rate" is selected. The item rate is changing based on the quantity entered.

### Module

accounts, stock, buying

### Version

ERPNext: v15.15.0 (version-15)
Frappe Framework: v15.16.1 (version-15)
Frappe HR: v15.12.0 (version-15)
India Compliance: v15.5.6 (version-15)

### Installation method

manual install

**Comment by ishanloya** [comment]
Closing this. Refer to #40159

**Comment by dineshpanchal93** [comment]
Its not closed yet
