### ISSUE TITLE
Function in payment tools 

### ISSUE THREAD

**Issue by AndrewCBPM** [frappe/erpnext#4027]
Hi,

I understand that in ERPNExt, we could make a batch payment by making use of payment tools. However I do have a query on payment tools function. After I click on get outstanding invoices, payment tools would pull out all the outstanding invoices for 1 particular supplier and I have to key in "payment amount" manually for each invoice. This would be very tedious exercise if I had over 100 invoices to be paid.

It would be better if there is a function which could automatically key in the outstanding amount in "payment amount" as it would save a lot of time if there were many invoices amount to be keyed in.

Cheers,

Andrew

**Comment by anandpdoshi** [comment]
Hi Andrew

Thanks for raising this issue. We have pushed a fix to this. If you are on our cloud, it will be released today.
