### ISSUE TITLE
Sales Order -> Update Items won't update "Amount Eligible for Commission"...

### ISSUE THREAD

**Issue by maxchock** [frappe/erpnext#40308]
### Information about bug

Updating items in a confirmed Sales Order won't update the "Amount Eligible for Commission" and also "Sales Team" table. Causing incentives calculation inaccurate.

### Module

selling

### Version

ERPNext

v15.15.0

### Installation method

FrappeCloud

**Comment by Nihantra-Patel** [comment]
fixed in https://github.com/frappe/erpnext/pull/40770
