### ISSUE TITLE
Address Quick Query Not Working on Version 15

### ISSUE THREAD

**Issue by SmoothPlay** [frappe/erpnext#40310]
### Information about bug

Basicly when you're filling an Address anywhere, sales invoice, client, user, the field won't quick query addresses on version 15. 

On Version 14 it works.

Confirmed to not work both on Selfhosted and on SaaS.

### Module

other

### Version

Frappe 15. Erpnext 15.

### Installation method

None

**Comment by Nihantra-Patel** [comment]
Hi @SmoothPlay,

We checked in the latest version 15 so it worked properly. so please check it.

https://github.com/frappe/erpnext/assets/141945075/c7d41800-eda1-4fbb-9730-f4be864a92fa

If the issue occurs then please reopen the issue according to the latest version 15 with a video document if possible.

Thank You!
