### ISSUE TITLE
Unable to update customize form of sales invoice

### ISSUE THREAD

**Issue by shree0110** [frappe/erpnext#40322]
### Information about bug

Unable to update customize form of sales invoice getting "Fetch From for field transporter_name is invalid: Supplier does not have a field name"

### Module

selling

### Version

ERPNext Version - 15

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
Fetch From for field transporter_name is invalid: Supplier does not have a field name
```

**Comment by cgallay** [comment]
I am facing the same issue

**Comment by yoyowu1000** [comment]
Having the same issue - however it's with delivery notes rather than sales invoice

**Comment by deepeshgarg007** [comment]
@shree0110 This should be resolved now, closing this issue.
