### ISSUE TITLE
Quality Inspection for Finished Goods in Subcontracting Receipt

### ISSUE THREAD

**Issue by ophl55** [frappe/erpnext#40342]
**Is your feature request related to a problem? Please describe.**
I have finished goods with a serial number that get assembled via a subcontractor. I need a quality inspection on receiption of the finished goods.

In the old subcontracting flow it was kind of easy to configure. You just had to check "Inspection Required before Delivery" in the item master. 

In the new subcontracting flow you order the service item. And the service item is the item that gets submitted in the pruchase receipt. So you can only do the quality inspection against the service item. There will be no quality inspection for the finished good.

**Describe the solution you'd like**
There should be the possibility to configure and apply the same data and logic on the subcontracting receipt as we do it in the purchase receipt. 

If "Inspection Required before Delivery" is enabled in the item master for the finished good, then the subcontracting receipt shall only be submitted if an quality inspection exists that fullfills the rules.

**Additional context**
ERPNext: v14.65.0

**Comment by ophl55** [comment]
@s-aga-r @rohitwaghchaure @deepeshgarg007 Can you please have a look? Thanks in advance!

**Comment by s-aga-r** [comment]
@ophl55 This is added in v15.

ref: https://github.com/frappe/erpnext/pull/36786

**Comment by ophl55** [comment]
@s-aga-r  Ah okay. Thank you for the fast reply and good to know that it is already implemented. Looks like I have to migrate soon.. :)
