### ISSUE TITLE
Set PO to Completed without Purchase Receipt or Invoice

### ISSUE THREAD

**Issue by curlyroger** [frappe/erpnext#4037]
We are using ERPNext to generate POs for equipment we dropship directly to customer.  I want to create a PO and then just set it to Completed. I don't need a Purcahse Receipt (since it isn't coming to me) and I don't need an Invoice (since we handle financials separately). For cleanliness, I just want to make the PO, send it, and then close it out to Completed. 

Basically, just need a way to alter PO status which does not currently seem possible.

**Comment by KanchanChauhan** [comment]
@curlyroger Once the PO is created, you can set the status to Deliver without creating a Purchase Receipt. 
<img width="331" alt="screen shot 2016-10-18 at 3 13 19 pm" src="https://cloud.githubusercontent.com/assets/16913064/19472612/8a2bad20-9545-11e6-946b-2ad9c6c2b74a.png">
