### ISSUE TITLE
Wrong Batch Quantity in Batch Bundle

### ISSUE THREAD

**Issue by dmbabu** [frappe/erpnext#40392]
### Information about bug

The wrong batch quantity is calculated for Items in same batch in different warehouses. To replicate, receive a batch in one warehouse and another batch in another warehouse.

<img width="789" alt="image" src="https://github.com/frappe/erpnext/assets/45001106/22031237-22bc-4ef9-8a6d-9be607080234">

### Module

stock

### Version

ERPNext: v15.14.7 (version-15)
Frappe Framework: v15.15.0 (version-15)

### Installation method

easy-install

**Comment by rohitwaghchaure** [comment]
Already fixed https://github.com/frappe/erpnext/pull/40274

Kindly update your site and create a new entry against this batch and check
