### ISSUE TITLE
List Count 

### ISSUE THREAD

**Issue by swathishir123** [frappe/erpnext#40425]
### Information about bug

Hello, I have a list view where i want the list count to show me the number of records present for example if the list view is showing me 4 records the list count should show 4 of 4 but as of now the list count couldnt be altered as it is showing 4 of 7 where 7 is the records present in database. how can i modify it to get the result

### Module

HR

### Version

5.22.3

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
in console and all im getting the count properly
```

**Comment by s-aga-r** [comment]
@swathishir123 Why do you want 4 of 4 instead of 4 of 7 (total count)?

Although there is no option to alter the default list count. [Here](https://github.com/frappe/frappe/blob/fe3244c886f3f8d164f807995e1bf1196efe9163/frappe/public/js/frappe/list/list_view.js#L986) the count gets set.

**Comment by swathishir123** [comment]
i actually for the output but it is not effecting the filter,
Basically my requirement is in listview it is fetching the records
according to my requirements and showing
[image: image.png]

now list-count is also showing but when render the list is now allowing to
filter the records here is my code , this is server script
import frappe

@frappe.whitelist()
def get_evaluation_forms_for_user():
    session_user = frappe.session.user
    if session_user == ***@***.***' or session_user ==
'Administrator':
        # If the user is ***@***.***, fetch all records
        forms = frappe.db.sql("""
            SELECT * FROM `tabFimer Post Training Evaluation Form`
        """, as_dict=True)
    else:
        # For other users, fetch records based on ownership or reporting
        forms = frappe.db.sql("""
            SELECT * FROM `tabFimer Post Training Evaluation Form`
            WHERE owner = %s OR reports_to = %s
        """, (session_user, session_user), as_dict=True)

     # Get the count of forms
    count = len(forms)

    return {
        "forms": forms,
        "count": count
    }


 and this is my client script

frappe.listview_settings['Fimer Post Training Evaluation Form'] = {
    refresh: function(listview) {
        // Call to fetch evaluation forms for the current user
        frappe.call({
            method:
'hrms.hr.doctype.fimer_post_training_evaluation_form.custom.get_evaluation_forms_for_user',
            callback: function(response) {
                if (response.message && response.message.forms) {
                    var forms = response.message.forms;
                    var count = response.message.count;

                    // Update the list count with the fetched count
                    //listview.page.wrapper.find('.list-count').hide();

listview.page.wrapper.find('.list-count').text(`${count} of ${count}`);
                   // console.log("List count updated to:", `${count} of
${count}`);
                    // Render the fetched forms
                    listview.data = forms;
                    listview.render();
                    // Assuming response is the variable containing the
response object
                    //console.log('Total Count:', response.message.count);
                    // Hide page count

listview.page.wrapper.find('.list-pagination').css('display', 'none');
                } else {
                    listview.page.wrapper.find('.result').html("<div>No
forms available.</div>");
                }
            },
            error: function(xhr, textStatus, error) {
                console.error("Error fetching forms:", error);
                listview.page.wrapper.find('.result').html("<div>Error
fetching evaluation forms.</div>");
            }
        });
    }
};
[image: image.png]
this filter is not working can you tell me why

**Comment by s-aga-r** [comment]
@swathishir123 So it's a development-related query. I would suggest asking it in the [Community Forum](https://discuss.frappe.io/) or [Telegram Group](https://t.me/frappeframework). You can check the existing ERPNext code if a similar implementation is done somewhere.
