### ISSUE TITLE
DocType Batch No not found

### ISSUE THREAD

**Issue by xhijack** [frappe/erpnext#40448]
### Information about bug

When I scan the item batch on the Delivery Note, a dialog box appears saying "Scan barcode for item ..."
![Screenshot 2024-03-14 at 10 19 30](https://github.com/frappe/erpnext/assets/1784964/e9d681b8-8aad-4254-9274-e5cd8cfbfbf1)
Then, when I scan again, an error pops up saying "The Doc Type Batch No not Found". However, when I scan again, there is no error anymore. The scanning process itself works fine, but the dialog box is bothersome for the first time; it seams to indicate a bug.
![Screenshot 2024-03-14 at 10 19 24](https://github.com/frappe/erpnext/assets/1784964/767e1197-e9a3-4a61-bdea-a6911e53ba99)

### Module

stock

### Version

ERPNext: v15.17.0 (version-15)
Frappe Framework: v15.17.3 (version-15)

### Installation method

manual install

**Comment by rohitwaghchaure** [comment]
@xhijack I have tried locally and it's working

![batch_scan_working](https://github.com/frappe/erpnext/assets/8780500/e9f92b10-1207-49b9-8f4b-5ddc06b110e8)


Copy the traceback of an error from the browser's console and share here
