### ISSUE TITLE
Payment Entry : Exchange Gain or Loss

### ISSUE THREAD

**Issue by Bknjogu** [frappe/erpnext#40472]
### Information about bug

I'm encountering an issue during payment reconciliation in the system, specifically related to the generation of journals for exchange gain or loss with abnormal figures.
When conducting payment reconciliation involving multiple currency transactions, the system generates journals to account for exchange gain or loss. However, I have observed that the figures in these journals are abnormal, deviating significantly from the expected values.

There's a Customer with Currency in Company Default
Have allowed multi-currency invoices against single party account.

 Have a stand lone Payment Entry. When receiving Payment the Exchange Rate from USD to KES was 140.5.

<img width="749" alt="frappe1" src="https://github.com/frappe/erpnext/assets/95646022/b4fe8562-6aeb-4278-8d07-105b33f3bcdb">

Against the same customer I created an Invoice in USD, at the point of invoicing the Exchange Rate USD to KES was 160.00

<img width="815" alt="frappe3" src="https://github.com/frappe/erpnext/assets/95646022/aa4272ee-b684-468f-b358-51aab1263129">

When I do Payment Reconciliation to allocate the Payment, reconciliation is successful and a journal is booked to register the Exchange Gain or loss, and rightly so. However, the figures in these journals are abnormal, deviating significantly from the expected values. 

<img width="926" alt="frappe2" src="https://github.com/frappe/erpnext/assets/95646022/72a43856-f8b0-4a83-b6d4-85ff78c0c81f">

<img width="912" alt="image" src="https://github.com/frappe/erpnext/assets/95646022/f23203a6-3c9c-4efc-bf49-57152ad15028">

<img width="816" alt="image" src="https://github.com/frappe/erpnext/assets/95646022/d72200ea-b63a-493c-8e96-0b30045e76ad">

 

### Module

accounts

### Version

ERPNext: v14.65.3 (HEAD)
Frappe Framework: v14.67.1 (HEAD)
Frappe HR: v14.23.0 (HEAD)
Payments: v0.0.1 (HEAD)

### Installation method

FrappeCloud

**Comment by albertfns** [comment]
Same problem in version 15.17.1

**Comment by albertfns** [comment]
Same problem in version 15.17.1

**Comment by ruthra-kumar** [comment]
caused by a regression in https://github.com/frappe/erpnext/pull/40149

https://github.com/frappe/erpnext/pull/40511 will fix it.
