### ISSUE TITLE
Can't submit Sales Invoice

### ISSUE THREAD

**Issue by ajiragroup** [frappe/erpnext#40484]
### Information about bug

Current sales invoice no. is 004 (lets assume).

I deleted this sales invoice and created a new one. It takes the number 004. But when I try to submit this invoice, it is not submitted. I don’t get any error message, just a error sound.

When I create another invoice (number 005), leaving that one as draft, then 005 gets submitted. Now when I delete 005 and create another invoice (number is 005 for new invoice) this invoice now does not get submitted.

Is this problem to everyone or is it just me ?

Any solution to this ?

I get 500 internal server error in console.
image
[image1595×529 88.7 KB](https://discuss.frappe.io/uploads/default/original/3X/8/1/8182f6b4c4e9ad765830374344b8d8d999c9f3a9.png)

image
[image2336×812 76.2 KB](https://discuss.frappe.io/uploads/default/original/3X/0/c/0c2d45cc5a5aba7481df20e7b3b1174074fda2a9.png)

### Module

selling

### Version

Frappe 15.17.1
Erpnext  15.16.2

### Installation method

manual install

**Comment by thida-bcn** [comment]
> ### Information about bug
> Current sales invoice no. is 004 (lets assume).
> 
> I deleted this sales invoice and created a new one. It takes the number 004. But when I try to submit this invoice, it is not submitted. I don’t get any error message, just a error sound.
> 
> When I create another invoice (number 005), leaving that one as draft, then 005 gets submitted. Now when I delete 005 and create another invoice (number is 005 for new invoice) this invoice now does not get submitted.
> 
> Is this problem to everyone or is it just me ?
> 
> Any solution to this ?
> 
> I get 500 internal server error in console. image [image1595×529 88.7 KB](https://discuss.frappe.io/uploads/default/original/3X/8/1/8182f6b4c4e9ad765830374344b8d8d999c9f3a9.png)
> 
> image [image2336×812 76.2 KB](https://discuss.frappe.io/uploads/default/original/3X/0/c/0c2d45cc5a5aba7481df20e7b3b1174074fda2a9.png)
> 
> ### Module
> selling
> 
> ### Version
> Frappe 15.17.1 Erpnext 15.16.2
> 
> ### Installation method
> manual install
> 
> ### Relevant log output / Stack trace / Full Error Message.
> _No response_
did you check allocate payment under payment tab?
are you using HRMS ?
i'm facing the same issues when we used HRMS with allocate payment, without HRMS it's working well

**Comment by ajiragroup** [comment]
@deepeshgarg007 Is the issue solved ?
