### ISSUE TITLE
Account Balance didn't show at warehouse

### ISSUE THREAD

**Issue by thida-bcn** [frappe/erpnext#40488]
### Information about bug

Version 13 Warehouse tree
![image](https://github.com/frappe/erpnext/assets/62122640/ab164b81-9f29-498e-bcfc-228bcfa50db8)
after upgrading to version 14 
Account Balance are missing

### Module

accounts, stock

### Version

![image](https://github.com/frappe/erpnext/assets/62122640/2d83f525-244a-4363-96ee-de915a311c5e)

### Installation method

manual install

**Comment by dj12djdjs** [comment]
@thida-bcn The stock balances have been [removed](https://github.com/frappe/erpnext/pull/33199) from the Warehouse tree in version >= 14 in favor of the Warehouse Wise Stock Balance [report](https://github.com/frappe/erpnext/pull/33236)

**Comment by thida-bcn** [comment]
> @thida-bcn The stock balances have been [removed](https://github.com/frappe/erpnext/pull/33199) from the Warehouse tree in version >= 14 in favor of the Warehouse Wise Stock Balance [report](https://github.com/frappe/erpnext/pull/33236)

thanks
