### ISSUE TITLE
Email send failures to one customer

### ISSUE THREAD

**Issue by monojoker** [frappe/erpnext#4048]
Hi Guys, Bit of a minor one but hopefully a simple fix and I'm just missing something. But when we try to email an invoice to our biggest customer (ironically LOL) it fails - every time. Below is the message trail and a Gist of the bulk email log message so hopefully you can tell me what I'm doing wrong. Interestingly the email is supposed to send to admin@[customer].com.au but reports it fails to send to an internal address as shown in the second screenshot below.

![image](https://cloud.githubusercontent.com/assets/10917366/10037099/bb43d0e8-61f4-11e5-8e05-cea2c9df01c8.png)

![image](https://cloud.githubusercontent.com/assets/10917366/10037104/ccd8a158-61f4-11e5-9c25-2dcc993fe4d1.png)

https://gist.github.com/monojoker/804146c299fd34a41557

**Comment by yashodhank** [comment]
Please post console log using Google Chrome.
How to do it?
Open Google Chrome, then go to Menu -> More Tools -> Developer Tools (once opened) go to Console tab.
Try performing same steps, which restarted into an error.
Copy and paste console output here as a comment.
(You may enclose error log from chrome console  here in ``` ``` error ``` ```) for more info on comment formatting:(https://guides.github.com/features/mastering-markdown/)

**Comment by anandpdoshi** [comment]
This person must be unsubscribed. 

If it is a user in the system they must've stopped following notifications. Else check the Email Unsubscribe list.

**Comment by monojoker** [comment]
That person is unsubscribed (sonia@mcleans.net.au) but the customer email isn't so I don't know why it's not sending to them. The unsubscribe list is:

![image](https://cloud.githubusercontent.com/assets/10917366/10088980/418cf8b4-6362-11e5-98a9-cdeb05953a15.png)

@yashodhank there's no reported issue in the console as you can see here:

![image](https://cloud.githubusercontent.com/assets/10917366/10088987/6ee83878-6362-11e5-84f5-f22e69f11658.png)

**Comment by monojoker** [comment]
That user email (admint@teatowel...) doesn't appear in the user list so I'm certain that email isn't set to unsubscribed. Very strange :(

**Comment by rmehta** [comment]
Check **Email Unsubscribed** table. Check via Awesome Bar

**Comment by monojoker** [comment]
hi @rmehta that's what I pasted earlier, or is it the wrong table?

![image](https://cloud.githubusercontent.com/assets/10917366/10093767/bfa265f8-639a-11e5-98c8-84371124c8cf.png)

**Comment by rmehta** [comment]
Seems strange. Can you ask your customer to check their SPAM account?

Also try sending from the same ISP using a normal mail client.

**Comment by anandpdoshi** [comment]
Hi @monojoker 

Looks like mandrill is rejecting the email address. It says that the domain is invalid. I will send the screenshot on your email id. Can you check if you are able to send emails to this customer via gmail or some other email service?

**Comment by monojoker** [comment]
Hey @anandpdoshi thanks for that, I'm pretty sure the domain is OK and I've sent successfully from hotmail to that address before. It's also their domain name here: http://www.teatowelkeepsakes.com.au/#!contact-us/c11m6

Very strange, I mean like you say, the evidence seems to suggest an incorrect email address we are sending to but we know it's valid to send to manually...

They have previously advised it's not going to SPAM at their end.

**Comment by anandpdoshi** [comment]
@monojoker I've raised a ticket to mandrill. Till then, you can switch to another service via setting up Email Account.

**Comment by cgpurbaugh** [comment]
Has this issue been resolved?

**Comment by anandpdoshi** [comment]
@cgpurbaugh this was an issue from Mandrill and not one of ERPNext. Closing this issue.
