### ISSUE TITLE
Custom field missing when submit/cancel the document

### ISSUE THREAD

**Issue by nguyenth1810** [frappe/erpnext#40486]
### Information about bug

I created a custome field on Material Request named "custom_cancellation_reasons" with depends on condition as eval:doc.status=='Cancelled'. I setup a workflow and once I choose workflow action to cancel the document. My custom field is missing.

### Module

stock

### Version

ERPNext: v15.14.6 (version-15)

Frappe Framework: v15.15.0 (version-15)

Payments: v0.0.1 (develop)

Webshop: v0.0.1 (version-15)

### Installation method

manual install

**Comment by s-aga-r** [comment]
@nguyenth1810 Please add screenshots of the custom field properties and workflow.

**Comment by nguyenth1810** [comment]
@s-aga-r Hi, my clarifications are below:
*** I created a workflow in Material Request:
![image](https://github.com/frappe/erpnext/assets/110219301/1e169e15-5882-441d-80e3-604759a4aa75)

*** And added 3 custom fields in Material Request:
1 - Cancellation Reasons - show depend on document status (Cancelled)
![image](https://github.com/frappe/erpnext/assets/110219301/db61ea18-2bdb-462d-af59-2b53b699b5e5)

2 - Cancelled Reason - show depend on Amended From field and fetch from Cancellation Reasons field of Amended From linked document
![image](https://github.com/frappe/erpnext/assets/110219301/5c6f3e41-108c-4b9d-a9c4-dbbf03cfd871)

3 - Amendments - show depend on Amended From
![image](https://github.com/frappe/erpnext/assets/110219301/7f94bac8-7d9a-4d38-a787-3faf78d1d912)

*** Next I created a client script, so whenever an user choose workflow action "Reject", a dialog will show up for user to fill out detail. The detail will fetch into Cancellation Reasons (custom_cancellation_reasons) once user choose "Save" on the dialog and the document status changes to "Cancelled" as setup workflow.
*** Client Script:
frappe.ui.form.on('Material Request', {
    before_workflow_action: (frm) => {
        return new Promise(resolve => {
            frappe.dom.unfreeze();
            if (frm.selected_workflow_action === 'Reject') {
                var d = new frappe.ui.Dialog({
                    title: __("Cancellation Information"),
                    fields: [
                        {
                            "fieldname": "custom_text",
                            "fieldtype": "Text",
                            "label": __("Please fill out the information for cancellation"),
                            "reqd": 1
                        }
                    ],
                    primary_action_label: __("Save"),
                    primary_action: function() {
                        var customText = d.get_value('custom_text');
                        frm.set_value('custom_cancellation_reasons', customText);
                        frm.save().then(() => {
                            d.hide();
                            resolve();
                        });
                    }
                });
                d.show();
            } else {
                resolve();
            }
        });
    }
});

However, once user choose workflow action "Reject", filled in the cancellation information then click on "Save", Cancellation Reasons field is missing

**Comment by s-aga-r** [comment]
@nguyenth1810 Is the value updated in the field `custom_cancellation_reasons`? IIRC the field value of a submitted document can't be updated if the `Allow on Submit` is unchecked.

**Comment by nguyenth1810** [comment]
Thank you @s-aga-r for looking into this,
Respond to your Question: Is the value updated in the field custom_cancellation_reasons? Yes, the value updated into custom_cancellation_field
I checked on Allow on Submit for the field.
![image](https://github.com/frappe/erpnext/assets/110219301/aa0df831-005d-4d56-9ac3-ba9eb8c4a16b)

Adding a New Material Request > Actions > Reject
![image](https://github.com/frappe/erpnext/assets/110219301/a22b4c4e-40d5-4ed2-bc6f-d131f3b05b52)

Input some text > Confirm
![image](https://github.com/frappe/erpnext/assets/110219301/67a5d6e6-1728-4a62-ae83-1f082b392a17)

The field is missing even the status is Cancelled
![image](https://github.com/frappe/erpnext/assets/110219301/e7dd1e49-45a9-4942-9f06-b6d53a27597b)

**Comment by s-aga-r** [comment]
@nguyenth1810 run this in the browser console and share the output here.

``` js 
cur_frm.doc.status + " " + cur_frm.doc.custom_cancellation_reasons
```

**Comment by nguyenth1810** [comment]
@s-aga-r Here it is:
![image](https://github.com/frappe/erpnext/assets/110219301/9facd1aa-8a44-4f8b-9590-0e2a52a8d647)

**Comment by s-aga-r** [comment]
> custom_cancellation_reasons

@nguyenth1810 The value didn't get set for `custom_cancellation_reasons`.

**Comment by nguyenth1810** [comment]
@s-aga-r , I see, I remove the depend on condition on the custom_cancellation_reasons. However, whenever I the status change to Pending, the field is disappear. Maybe my script was not setup correctly?

**Comment by s-aga-r** [comment]
@nguyenth1810 Fields with no value get hidden on a submitted document. There is some issue with the script you are using to set the value of `custom_cancellation_reasons`. As it's a development/customization-related query you may ask the same in the [Community Forum](https://discuss.frappe.io/) or [Telegram Group](https://t.me/frappeframework).

**Comment by nguyenth1810** [comment]
@s-aga-r Thanks for your help and suggestion, I figured it out and able to make it works
