### ISSUE TITLE
Calendar View of Leave Requests not working

### ISSUE THREAD

**Issue by Barbariandude** [frappe/erpnext#4050]
Hi,

The leave requests are not showing up in the calendar view. We've tried with a workflow and with a leave approver changing the status by hand, neither seems to cause the annual leave request to show up in the calendar.

![list](https://cloud.githubusercontent.com/assets/915121/10040639/0b593672-61e6-11e5-8e3f-d5cc9beb1476.png)
![calendar](https://cloud.githubusercontent.com/assets/915121/10040641/102eea2a-61e6-11e5-945d-bb0e157e9dfb.png)

Is there some setup requirement for the Leave Request calendar to function?

**Comment by Barbariandude** [comment]
Found workaround:

A user must have an entry in the employee list linked to their user account in order to see the leave applications.

Relevant lines are these:

`def get_events(start, end):
        events = []

        employee = frappe.db.get_value("Employee", {"user_id": frappe.session.user}, ["name", "company"],
                as_dict=True)
        if not employee:
                return events`

This is an unintuitive feature. If the user is not an employee, they should probably get at least a warning as to why they cannot see any of the leave requests.

**Comment by rmehta** [comment]
@Barbariandude I guess it should show based on permission then. Do you want to fix it?

**Comment by Barbariandude** [comment]
@rmehta I think maybe a role that can see all the leave requests regardless of who the employee or approver is would be a pretty good solution.

**Comment by PawanMeh** [comment]
Can you check if the setting of "Show Leaves of All Department Members in Calendar" would fix what you are looking for. If not you can re-open the issue.

![setting](https://user-images.githubusercontent.com/20460498/47839960-a6738e00-ddda-11e8-971e-4cdb15159fee.png)
