### ISSUE TITLE
Permission restriction on print formats

### ISSUE THREAD

**Issue by manivk** [frappe/erpnext#4051]
Hi

Currently, there is no way to restrict permissions in print formats (both for standard print formats in the system as well as custom print formats). Would be good if we could have a feature where we can restrict print formats. Since, for a document we could have instances where we want to give print rights to a department but not reveal data that is there in the standard format. 
For e.g., in our case, we would like to restrict our factory from seeing customer information in the print format for sales orders. Even though I have customized the form so that factory does not see in the information in the document form, when I give print access, they see the standard report that has all the data related to the customers.Hence, ability to set up restrictions by giving permissions on various print formats in the system (both standard and custom print formats) would be good. 

Also, let me know what would be the cost of developing this if I would like to pay for the same.

Thanks
Manikandan.

**Comment by hamzahali** [comment]
Very Important requirment esp when we have multiple companies or multiple user roles.

**Comment by hamzahali** [comment]
Is there a solution for this right now

**Comment by hamzahabdo** [comment]
+1
