### ISSUE TITLE
Webforms Not Capturing/Saving Comments to ERPNext V15

### ISSUE THREAD

**Issue by thatphythonguy** [frappe/erpnext#40517]
### Information about bug

The webforms integrated with ERPNext are failing to capture and save user comments/input. Despite users filling out the form and submitting their comments, the data is not being recorded in ERPNext as expected.

**Steps to Reproduce:**
Navigate to the webform integrated with ERPNext.
Fill out the required fields including comment/input section.
Submit the form.
Verify the submission in ERPNext to ensure that the comments/input are saved.

![Screenshot 2024-03-18 204414](https://github.com/frappe/erpnext/assets/161945345/94b1f527-4898-4af1-8a37-1a0bb5669094)
![Screenshot 2024-03-18 204500](https://github.com/frappe/erpnext/assets/161945345/b570add4-52dc-46d0-9869-4d7228299271)

### Module

CRM

### Version

ERPNext v15

### Installation method

None

**Comment by Nihantra-Patel** [comment]
Please check it. and worked properly

![image](https://github.com/frappe/erpnext/assets/141945075/3749c545-e7c1-4f03-89cb-b37c2df4fba9)

**Comment by thatphythonguy** [comment]
@Nihantra-Patel According to the attached picture, users must be logged in and the 'allow comments' option must be checked. If this is a lead form, requiring users to sign up may create sales friction, as they might be reluctant to create an account for a simple inquiry. Allowing visitors to send messages without creating an account can potentially capture more leads without having them to go through the account creating process. 
If we uncheck the 'Login Required" option ,it does not allow to capture comments or messages typed by Lead.

Would appreciate , if you could provide a solution or a work around to capture comments. 

![image](https://github.com/frappe/erpnext/assets/161945345/11621c77-1f06-4042-903b-7a36ff879743)
