### ISSUE TITLE
Creating opportunity from prospect failed with link check

### ISSUE THREAD

**Issue by sunxiaoguang** [frappe/erpnext#40566]
### Information about bug

When creating opportunity from existing prospect. Save failed when checking linked documents on prospect. We need to ignore links check before update prospect. 

<img width="578" alt="image" src="https://github.com/frappe/erpnext/assets/3982329/cfe4c92a-9f2a-46fc-9827-bfc025a8163d">

### Module

CRM

### Version

erpnext 16.0.0-dev
frappe 15.x.x-develop

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
Could not find Row #1: Opportunity: CRM-OPP-2024-00004

127.0.0.1 - - [20/Mar/2024 12:49:53] "POST /api/method/frappe.desk.form.save.savedocs HTTP/1.1" 417 -
```

**Comment by juzerali** [comment]
I am wondering why is this simple issue not being solved and PR not being accepted by ERPNext team. This issue blocks the CRM pipeline which is the most basic functionality of ERP. But I notice that issue is not present in ERPNext Cloud. Is it that ERPNext team is not committed to Open Source?

**Comment by juzerali** [comment]
Is this bug present on 15.21.2 as well?
