### ISSUE TITLE
 POS Reports And POS Operator Opening and closing their account 

### ISSUE THREAD

**Issue by chandutalluri** [frappe/erpnext#4058]
HI Request for Reports in pos
sales by user and shifts
( POS Operator Opening and closing)

Sales Anneliese
Ex.
Best Hour  and  Worst Hour

Sale Amount Summary Chart

Reconciliation And Audit
Ex.
| Employee | Returned Items | Returned Amount | Returned Sales

| Payment from POS Operator | Counted | Recorded | Variance

**Comment by chandutalluri** [comment]
HI Request in POS
By user and shifts Ex:(morning shift and evening shift)
POS user opening and closing Amount

**Comment by chdecultot** [comment]
Hi, we are working on this issue with #7582.

Therefore I'm closing this one to gather all requirements in one place. Don't hesitate to add your inputs in #7582 

Thanks!
