### ISSUE TITLE
SO/PO Not Fetch Item Price

### ISSUE THREAD

**Issue by donnieferdian** [frappe/erpnext#40592]
### Information about bug

Hi Dev @rohit
After Latest Update Sales Order/Purcase Order cant fetch item price,..

https://github.com/frappe/erpnext/assets/109821040/f936752a-9f09-49a5-b374-ee2d1d5a3832

### Module

buying, selling

### Version

erpnext 15.17.3
frappe 15.18.0

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
No Error Log
```

**Comment by KO-IT** [comment]
@donnieferdian Make sure the Item price is valid. Today's date fall between Valid From and Valid Upto Dates

**Comment by szufisher** [comment]
already fixed via https://github.com/frappe/erpnext/pull/40601

**Comment by donnieferdian** [comment]
thanks @rohitwaghchaure for fix #40602
