### ISSUE TITLE
Primary Address in customer showing as HTML

### ISSUE THREAD

**Issue by dmateos** [frappe/erpnext#40603]
### Information about bug

Customer primary address is showing HTML code 

Similar to bug #25574 and #40563

<img width="369" alt="Screenshot 2024-03-22 at 11 23 55 AM" src="https://github.com/frappe/erpnext/assets/13409/7616cb9c-3801-42bf-8301-d595c87ba577">

### Module

other

### Version

ERPNext: v15.17.3
Frappe Framework: v15.18.0

### Installation method

Running docker container version of frappe/erpnext

**Comment by Craftint** [comment]
This issue is there for all html fields. They are not rendering. Also there is another issue with latest update:

![image](https://github.com/frappe/erpnext/assets/67686213/4335817d-c14e-4b73-bb8c-092c590d5bd1)

This error shows on deleting, downloading as well.

Please fix this asap

**Comment by Craftint** [comment]
Facing same issue. All HTML fields are not rendering
