### ISSUE TITLE
Tax Rule - Validity

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#4062]
Senario:

In tax rule:
1. Sales Tax and Charges master is selected. This tax master is not a default tax master.
2. Customer Group selected as "Commercial".
3. Tax rule validity for September, 2015.

While creating Sales Order:
1. Default Tax master is auto-fetched.
1. On selecting Customer, as per Tax Rule, tax master is overwritten, as expected.
1. Posting Date for the Sales Order is changed to 30th August (date out of Tax Rule validity).
1. Sales Order is saved.

On Saving Sales Order, should it check for validity of Tax Rule again?

**Comment by rmehta** [comment]
if there is no other tax rule then it should be fine.
