### ISSUE TITLE
Use JIRA for ERPnext issue tracking

### ISSUE THREAD

**Issue by ttl76543** [frappe/erpnext#4063]
I'd like to suggest using JIRA for issue tracking instead of GitHub, because users can vote for issues in addition to just commenting on them like in GitHub, and you can watch/subscribe to individual issues.

It's proprietary software, but "Atlassian provides JIRA for free to open source projects meeting certain criteria."

**Comment by rmehta** [comment]
Yeah we would love to have a voting feature :+1: Maybe we are growing out of GH Issues!

**Comment by ttl76543** [comment]
Glad you agree, Rushabh! :+1:

**Comment by yashodhank** [comment]
Cool.. :+1: https://www.atlassian.com/software/views/open-source-license-request

**Comment by rmehta** [comment]
We kind-of :heart: GitHub. Maybe at a later point

**Comment by vrms** [comment]
maybe [this ](https://github.com/github/developer.github.com/issues/994)might help
