### ISSUE TITLE
General Ledger Voucher Subtype Issue

### ISSUE THREAD

**Issue by Gubbu77** [frappe/erpnext#40646]
### Information about bug

In General Ledger report, voucher subtype is interchanged Sales Invoice Subtype is Debit Note and Purchase Invoice Subtype is Credit Note.

Voucher  Type = Sales Invoice
![image](https://github.com/frappe/erpnext/assets/91895505/e50c308f-88e1-4ac0-95a9-4c5d9079fc11)

Voucher Type = Purchase Invoice
![image](https://github.com/frappe/erpnext/assets/91895505/dbaf9c93-5e90-4c8a-b7d5-0666ab329529)

### Module

accounts

### Version

Frappe Framework: v15.18.2 (HEAD)
ERPNext: v15.17.5 (HEAD)

### Installation method

FrappeCloud

**Comment by deepeshgarg007** [comment]
@Gubbu77 a Sales Invoice is a Debit note and Purchase Invoice is a credit note. A sales invoice return is a Credit Note and a purchase invoice return is Debit note.

**Comment by rtdany10** [comment]
@deepeshgarg007 the accounting impact might be same, but a Sales Invoice is not really Debit Note as it has a different meaning. So is the case of Purchase Invoice and Credit Note. Maybe we should keep the subtype column empty for normal invoices?
