### ISSUE TITLE
Addresses detached from customers

### ISSUE THREAD

**Issue by monojoker** [frappe/erpnext#4066]
Hi Guys,

After the most recent cloud upgrade we have an issue with a number of customers no longer having address records associated with them. The address record is still there along with the customer one but the address.customer field is blank so they don't associate. This has also happened with contacts as well. This means when we add a customer to a sales order we no longer have their details being brought onto the Sales Order.

Is there a way you can fix this? I've been fixing them individually but there are hundreds. I can supply a list and also a login to the system if that is what you need.

Please assist. Thanks.

**Comment by rmehta** [comment]
@monojoker This was not due to an update. Did you bulk upload Addresses anytime? You can also bulk upload with the correct "customer" property and fix it.

**Comment by monojoker** [comment]
My apologies it was only noticed just after the latest upgrade. I imported addresses for suppliers, why would that affect customer addresses? Please let me know if it's something I did wrong so I can avoid in future. Thanks @rmehta

**Comment by anandpdoshi** [comment]
Fastest way to fix this would be to restore your backup on another site,
export the addresses and contacts and import them in your live site.

**Comment by monojoker** [comment]
restoring a backup is beyond me i have no local server suitable. I'll export the address and contacts, fill in the customer field (it should be a derivative of the address/contact name i hope) and import that.

Thanks.
