### ISSUE TITLE
Pick List Batch selection issue

### ISSUE THREAD

**Issue by rknroot** [frappe/erpnext#40686]
### Information about bug

**Information about bug**
After creating pick list form sales order while selecting batch child table is adding the different batch in one row.

**Steps to Reproduce**
1. Create Item with at least three batches
2. add stock in all the batch
3. create sales order for the item (I have created for 1200 qty)
<img width="1618" alt="image" src="https://github.com/frappe/erpnext/assets/9102676/b4d493c0-45c9-40c9-8527-37a93601315b">
4. Create Pick list and change qty and batch by adding additional row.

![Mar-26-2024 18-29-10](https://github.com/frappe/erpnext/assets/9102676/e5e4220a-6862-4460-9cca-b804f790d926)

### Module

stock, selling

### Version

ERPNext: v15.17.6 (version-15)
Frappe Framework: v15.18.2 (version-15)

### Installation method

None

**Comment by rohitwaghchaure** [comment]
This is not a bug, it's a feature request. We even not allowing to change the batch in v14
