### ISSUE TITLE
Supplier Quotation Tax Breakup not displaying properly

### ISSUE THREAD

**Issue by quebn** [frappe/erpnext#40694]
### Information about bug

Supplier Quotation Tax Breakup not displaying properly and instead displays the HTML code as show below.
![image](https://github.com/frappe/erpnext/assets/93438531/d9f083b1-0c49-4570-9ab5-49816ec697ca)

Other Doctype's Tax Breakup is working as intended as shown below.
![image](https://github.com/frappe/erpnext/assets/93438531/b45add29-f6a6-4c3a-b90a-719c968d229d)

### Module

buying

### Version

Frappe Framework: v15.18.2 - ERPNext: v15.17.6

### Installation method

FrappeCloud

**Comment by Nihantra-Patel** [comment]
Already raised the PR: #40563

**Comment by quebn** [comment]
> Already raised the PR: #40563

Bug is still present in latest version of version-15, the field is still a MarkdownEditor rather TextEditor.

**Comment by Nihantra-Patel** [comment]
We again raised the PR for that.
