### ISSUE TITLE
Bank transaction delete bug

### ISSUE THREAD

**Issue by nehasan16** [frappe/erpnext#40701]
### Information about bug

When deleting bank transactions in bulk, the system shows that the selected entries are deleted but actually they aren't. 

After repeated tries, I came to know that first I have to cancel the transaction and only then delete it. This was a UX bug and should be fixed. 

### Module

accounts

### Version

ERPNext Version 15

### Installation method

FrappeCloud

**Comment by nehasan16** [comment]
@deepeshgarg007 kind of noticed this issue recently. 

1. Firstly due to some UX issue, bank data got uploaded thrice
2. Secondly, bulk delete didn't work. Later came to know that first I have to cancel and only then the entries can be deleted. This error message was not very clear.
3.

**Comment by khushi8112** [comment]
<img width="1224" alt="Screenshot 2024-03-28 at 4 14 32 PM" src="https://github.com/frappe/erpnext/assets/142375893/1e4d69b6-438b-4c8a-a6e3-3a4c48a411fa">

We encounter this message when attempting to delete. I believe this message is clear enough for the situation.

**Comment by nehasan16** [comment]
@khushi8112 Can you try if the message appears when you try bulk delete?

The issue was happening in bulk delete and not single transaction delete.

**Comment by khushi8112** [comment]
Okay, so I have tried to delete 4 transactions at once and for me it encountered the same message I have shared above.
Also in the screenshot you can check that I tried to delete 2 transactions and the shown message is also for 2 different transaction not for single transaction.
@NehaSan16  Could you please attach the screenshot of message which you are getting.
