### ISSUE TITLE
Problem to change warehouse in stock entry

### ISSUE THREAD

**Issue by gmarke** [frappe/erpnext#4072]
THere is problem to change warehouse(source and target) in stock entry form.
Looks that this request is done with very long GET URI and can not be processed by server.

Is it possible to chnge it to be send via POST??

**Comment by gmarke** [comment]
To even increase limit_request_line in gunicorn is not possible - the max is 8190...
The only solution is to pass it via POST but how to make the change???
Please help with that!!

**Comment by rmehta** [comment]
Can you post post the query / line-number.

You can add `"type": "POST"` in the `frappe.call` arguments.

**Comment by gmarke** [comment]
https://xxxx.xxx/?method=get_warehouse_details&docs=%7B%22use_multi_level_bom%22%3A1%2C%22value_difference%22%3A0%2C%22naming_series%22%3A%22test-%22%2C%22company%22%3A%22Azimut+sprl%22%2C%22creation%22%3A%222015-09-28+12%3A23%3A11.761348%22%2C%22fiscal_year%22%3A%222015%22%2C%22modified%22%3A%222015-09-28+12%3A24%3A34.694701%22%2C%22letter_head%22%3A%22title%22%2C%22additional_costs%22%3A%5B%5D%2C%22total_outgoing_value%22%3A0%2C%22posting_date%22%3A%222015-09-28%22%2C%22owner%22%3A%22Administrator%22%2C%22posting_time%22%3A%2212%3A21%3A37%22%2C%22total_additional_costs%22%3A0%2C%22modified_by%22%3A%22Administrator%22%2C%22total_amount%22%3A0%2C%22title%22%3A%22Material+Issue%22%2C%22items%22%3A%5B%7B%22basic_rate%22%3A40%2C%22transfer_qty%22%3A0%2C%22description%22%3A%22%3Cp%3E1m+%2F%2F+optical+jumpers%3C%2Fp%3E%3Cp%3EFO+jumper+cables+ODVA%2FLC+%26nbsp%3Bde+1+m%3C%2Fp%3E%22%2C%22parent%22%3A%22test-00001%22%2C%22basic_amount%22%3A0%2C%22creation%22%3A%222015-09-28+12%3A23%3A11.761348%22%2C%22conversion_factor%22%3A1%2C%22item_code%22%3A%221m+%2F%2F+optical+jumpers%22%2C%22qty%22%3A0%2C%22parenttype%22%3A%22Stock+Entry%22%2C%22doctype%22%3A%22Stock+Entry+Detail%22%2C%22owner%22%3A%22Administrator%22%2C%22cost_center%22%3A%22Main+-+AZT%22%2C%22expense_account%22%3A%22Stock+Adjustment+-+AZT%22%2C%22actual_qty%22%3A16%2C%22modified_by%22%3A%22Administrator%22%2C%22name%22%3A%22e6cbbc9ec9%22%2C%22idx%22%3A1%2C%22item_name%22%3A%221m+%2F%2F+optical+jumpers%22%2C%22additional_cost%22%3A0%2C%22modified%22%3A%222015-09-28+12%3A24%3A34.694701%22%2C%22s_warehouse%22%3A%22FZ9048E+-+AZT%22%2C%22amount%22%3A0%2C%22stock_uom%22%3A%22Unit%22%2C%22batch_no%22%3A%22%22%2C%22valuation_rate%22%3A0%2C%22docstatus%22%3A0%2C%22uom%22%3A%22Unit%22%2C%22parentfield%22%3A%22items%22%7D%2C%7B%22basic_rate%22%3A0%2C%22transfer_qty%22%3A1%2C%22description%22%3A%22Cable+end+4mm-10mm+AWG+12%26nbsp%3B%26nbsp%3B%26nbsp%3B+BIZ+225+006+%26nbsp%3B%26nbsp%3B%26nbsp%3B%26nbsp%3B%26nbsp%3B+100pcs+in+pack%22%2C%22parent%22%3A%22test-00001%22%2C%22basic_amount%22%3A0%2C%22image%22%3A%22%2Ffiles%2Fgreen.png%22%2C%22creation%22%3A%222015-09-28+12%3A23%3A11.761348%22%2C%22conversion_factor%22%3A1%2C%22item_code%22%3A%22Cable+end+4mm-10mm+AWG+12%22%2C%22qty%22%3A1%2C%22parenttype%22%3A%22Stock+Entry%22%2C%22doctype%22%3A%22Stock+Entry+Detail%22%2C%22owner%22%3A%22Administrator%22%2C%22cost_center%22%3A%22Main+-+AZT%22%2C%22expense_account%22%3A%22Stock+Adjustment+-+AZT%22%2C%22actual_qty%22%3A900%2C%22modified_by%22%3A%22Administrator%22%2C%22name%22%3A%22cb8e1a1006%22%2C%22idx%22%3A2%2C%22item_name%22%3A%22Cable+end+4mm-10mm+AWG+12%22%2C%22additional_cost%22%3A0%2C%22modified%22%3A%222015-09-28+12%3A24%3A34.694701%22%2C%22s_warehouse%22%3A%22Stores+-+AZT%22%2C%22amount%22%3A0%2C%22stock_uom%22%3A%22Unit%22%2C%22batch_no%22%3A%22%22%2C%22valuation_rate%22%3A0%2C%22docstatus%22%3A0%2C%22uom%22%3A%22Unit%22%2C%22parentfield%22%3A%22items%22%7D%2C%7B%22basic_rate%22%3A0%2C%22transfer_qty%22%3A1%2C%22description%22%3A%22Cable+end+6mm-11%2C5mm+AWG+10%26nbsp%3B%26nbsp%3B%26nbsp%3B+DZ5CE062+Schneider%26nbsp%3B%26nbsp%3B%26nbsp%3B%26nbsp%3B%26nbsp%3B%26nbsp%3B+100pcs+in+pack%22%2C%22parent%22%3A%22test-00001%22%2C%22basic_amount%22%3A0%2C%22image%22%3A%22%2Ffiles%2Fgreen.png%22%2C%22creation%22%3A%222015-09-28+12%3A23%3A11.761348%22%2C%22conversion_factor%22%3A1%2C%22item_code%22%3A%22Cable+end+6mm-11%2C5mm+AWG+10%22%2C%22qty%22%3A1%2C%22parenttype%22%3A%22Stock+Entry%22%2C%22doctype%22%3A%22Stock+Entry+Detail%22%2C%22owner%22%3A%22Administrator%22%2C%22cost_center%22%3A%22Main+-+AZT%22%2C%22expense_account%22%3A%22Stock+Adjustment+-+AZT%22%2C%22actual_qty%22%3A1000%2C%22modified_by%22%3A%22Administrator%22%2C%22name%22%3A%2245658bb0e8%22%2C%22idx%22%3A3%2C%22item_name%22%3A%22Cable+end+6mm-11%2C5mm+AWG+10%22%2C%22additional_cost%22%3A0%2C%22modified%22%3A%222015-09-28+12%3A24%3A34.694701%22%2C%22s_warehouse%22%3A%22Stores+-+AZT%22%2C%22amount%22%3A0%2C%22stock_uom%22%3A%22Unit%22%2C%22batch_no%22%3A%22%22%2C%22valuation_rate%22%3A0%2C%22docstatus%22%3A0%2C%22uom%22%3A%22Unit%22%2C%22parentfield%22%3A%22items%22%7D%2C%7B%22basic_rate%22%3A0%2C%22transfer_qty%22%3A0%2C%22description%22%3A%22ECLAIRAGES+ET+SIGNALISATIONS+TL+herm%C3%A9tique+1+x+36+watts%22%2C%22parent%22%3A%22test-00001%22%2C%22basic_amount%22%3A0%2C%22creation%22%3A%222015-09-28+12%3A23%3A11.761348%22%2C%22conversion_factor%22%3A1%2C%22item_code%22%3A%22Light+and+Signalisation+TL+hermetic+1+x+36+watts%22%2C%22qty%22%3A0%2C%22parenttype%22%3A%22Stock+Entry%22%2C%22doctype%22%3A%22Stock+Entry+Detail%22%2C%22owner%22%3A%22Administrator%22%2C%22cost_center%22%3A%22Main+-+AZT%22%2C%22expense_account%22%3A%22Stock+Adjustment+-+AZT%22%2C%22actual_qty%22%3A1%2C%22modified_by%22%3A%22Administrator%22%2C%22name%22%3A%226f824fe99e%22%2C%22idx%22%3A4%2C%22item_name%22%3A%22Light+and+Signalisation+TL+hermetic+1+x+36+watts%22%2C%22additional_cost%22%3A0%2C%22modified%22%3A%222015-09-28+12%3A24%3A34.694701%22%2C%22s_warehouse%22%3A%22Stores+-+AZT%22%2C%22amount%22%3A0%2C%22stock_uom%22%3A%22Unit%22%2C%22batch_no%22%3A%22%22%2C%22valuation_rate%22%3A0%2C%22docstatus%22%3A0%2C%22uom%22%3A%22Unit%22%2C%22parentfield%22%3A%22items%22%2C%22image%22%3Anull%7D%2C%7B%22basic_rate%22%3A0%2C%22transfer_qty%22%3A1%2C%22description%22%3A%22Chemins+de+c%C3%A2bles+type+KBS+60+cable+way+KBS60+-+largeur+400+mm+(longueur+de+3m)%22%2C%22parent%22%3A%22test-00001%22%2C%22basic_amount%22%3A0%2C%22creation%22%3A%222015-09-28+12%3A23%3A11.761348%22%2C%22conversion_factor%22%3A1%2C%22item_code%22%3A%22Cable+tray+KBS60+400+mm+width+(length+3m)%22%2C%22qty%22%3A1%2C%22parenttype%22%3A%22Stock+Entry%22%2C%22doctype%22%3A%22Stock+Entry+Detail%22%2C%22owner%22%3A%22Administrator%22%2C%22cost_center%22%3A%22Main+-+AZT%22%2C%22expense_account%22%3A%22Stock+Adjustment+-+AZT%22%2C%22actual_qty%22%3A2%2C%22modified_by%22%3A%22Administrator%22%2C%22name%22%3A%229582955652%22%2C%22idx%22%3A5%2C%22item_name%22%3A%22Cable+tray+KBS60+400+mm+width+(length+3m)%22%2C%22additional_cost%22%3A0%2C%22modified%22%3A%222015-09-28+12%3A24%3A34.694701%22%2C%22s_warehouse%22%3A%22Stores+-+AZT%22%2C%22amount%22%3A0%2C%22stock_uom%22%3A%22Unit%22%2C%22batch_no%22%3A%22%22%2C%22valuation_rate%22%3A0%2C%22docstatus%22%3A0%2C%22uom%22%3A%22Unit%22%2C%22parentfield%22%3A%22items%22%7D%2C%7B%22basic_rate%22%3A0%2C%22transfer_qty%22%3A1%2C%22description%22%3A%22Chemins+de+c%C3%A2bles+type+KBS+60+cable+way+KBS60+-+largeur+100+mm%22%2C%22parent%22%3A%22test-00001%22%2C%22basic_amount%22%3A0%2C%22creation%22%3A%222015-09-28+12%3A23%3A11.761348%22%2C%22conversion_factor%22%3A1%2C%22item_code%22%3A%22Cable+tray+KBS60+Width+100+mm%22%2C%22qty%22%3A1%2C%22parenttype%22%3A%22Stock+Entry%22%2C%22doctype%22%3A%22Stock+Entry+Detail%22%2C%22owner%22%3A%22Administrator%22%2C%22cost_center%22%3A%22Main+-+AZT%22%2C%22expense_account%22%3A%22Stock+Adjustment+-+AZT%22%2C%22actual_qty%22%3A30%2C%22modified_by%22%3A%22Administrator%22%2C%22name%22%3A%227be563155b%22%2C%22idx%22%3A6%2C%22item_name%22%3A%22Cable+tray+KBS60+Width+100+mm%22%2C%22additional_cost%22%3A0%2C%22modified%22%3A%222015-09-28+12%3A24%3A34.694701%22%2C%22s_warehouse%22%3A%22Stores+-+AZT%22%2C%22amount%22%3A0%2C%22stock_uom%22%3A%22Meter%22%2C%22batch_no%22%3A%22%22%2C%22valuation_rate%22%3A0%2C%22docstatus%22%3A0%2C%22uom%22%3A%22Meter%22%2C%22parentfield%22%3A%22items%22%7D%2C%7B%22basic_rate%22%3A0%2C%22transfer_qty%22%3A1%2C%22description%22%3A%22Echelle+a+cable+type+KSDavid+largeur+200+mm%22%2C%22parent%22%3A%22test-00001%22%2C%22basic_amount%22%3A0%2C%22creation%22%3A%222015-09-28+12%3A23%3A11.761348%22%2C%22conversion_factor%22%3A1%2C%22item_code%22%3A%22Cables+Ladder+KSDavid+width+200+mm%22%2C%22qty%22%3A1%2C%22parenttype%22%3A%22Stock+Entry%22%2C%22doctype%22%3A%22Stock+Entry+Detail%22%2C%22owner%22%3A%22Administrator%22%2C%22cost_center%22%3A%22Main+-+AZT%22%2C%22expense_account%22%3A%22Stock+Adjustment+-+AZT%22%2C%22actual_qty%22%3A16.5%2C%22modified_by%22%3A%22Administrator%22%2C%22name%22%3A%22f2c3dd9ca0%22%2C%22idx%22%3A7%2C%22item_name%22%3A%22Cables+Ladder+KSDavid+width+200+mm%22%2C%22additional_cost%22%3A0%2C%22modified%22%3A%222015-09-28+12%3A24%3A34.694701%22%2C%22s_warehouse%22%3A%22Stores+-+AZT%22%2C%22amount%22%3A0%2C%22stock_uom%22%3A%22Meter%22%2C%22batch_no%22%3A%22%22%2C%22valuation_rate%22%3A0%2C%22docstatus%22%3A0%2C%22uom%22%3A%22Meter%22%2C%22parentfield%22%3A%22items%22%7D%2C%7B%22basic_rate%22%3A0%2C%22transfer_qty%22%3A1%2C%22description%22%3A%22Echelle+a+cable+type+KSDavid+largeur+400+mm%22%2C%22parent%22%3A%22test-00001%22%2C%22basic_amount%22%3A0%2C%22creation%22%3A%222015-09-28+12%3A23%3A11.761348%22%2C%22conversion_factor%22%3A1%2C%22item_code%22%3A%22Cables+Ladder+KSDavid+width+400+mm%22%2C%22qty%22%3A1%2C%22parenttype%22%3A%22Stock+Entry%22%2C%22doctype%22%3A%22Stock+Entry+Detail%22%2C%22owner%22%3A%22Administrator%22%2C%22cost_center%22%3A%22Main+-+AZT%22%2C%22expense_account%22%3A%22Stock+Adjustment+-+AZT%22%2C%22actual_qty%22%3A0%2C%22modified_by%22%3A%22Administrator%22%2C%22name%22%3A%2270d491af03%22%2C%22idx%22%3A8%2C%22item_name%22%3A%22Cables+Ladder+KSDavid+width+400+mm%22%2C%22additional_cost%22%3A0%2C%22modified%22%3A%222015-09-28+12%3A24%3A34.694701%22%2C%22s_warehouse%22%3A%22Stores+-+AZT%22%2C%22amount%22%3A0%2C%22stock_uom%22%3A%22Meter%22%2C%22batch_no%22%3A%22%22%2C%22valuation_rate%22%3A0%2C%22docstatus%22%3A0%2C%22uom%22%3A%22Meter%22%2C%22parentfield%22%3A%22items%22%7D%2C%7B%22basic_rate%22%3A0%2C%22transfer_qty%22%3A1%2C%22description%22%3A%22-+Echelle+%C5%95+c%C3%A2bles+type+KLIE+-+largeur+200+mm%22%2C%22parent%22%3A%22test-00001%22%2C%22basic_amount%22%3A0%2C%22creation%22%3A%222015-09-28+12%3A23%3A11.761348%22%2C%22conversion_factor%22%3A1%2C%22item_code%22%3A%22Cables+Ladder+type+KLIE+Width+200+mm%22%2C%22qty%22%3A1%2C%22parenttype%22%3A%22Stock+Entry%22%2C%22doctype%22%3A%22Stock+Entry+Detail%22%2C%22owner%22%3A%22Administrator%22%2C%22cost_center%22%3A%22Main+-+AZT%22%2C%22expense_account%22%3A%22Stock+Adjustment+-+AZT%22%2C%22actual_qty%22%3A0%2C%22modified_by%22%3A%22Administrator%22%2C%22name%22%3A%227a576bde47%22%2C%22idx%22%3A9%2C%22item_name%22%3A%22Cables+Ladder+type+KLIE+Width+200+mm%22%2C%22additional_cost%22%3A0%2C%22modified%22%3A%222015-09-28+12%3A24%3A34.694701%22%2C%22s_warehouse%22%3A%22Stores+-+AZT%22%2C%22amount%22%3A0%2C%22stock_uom%22%3A%22Meter%22%2C%22batch_no%22%3A%22%22%2C%22valuation_rate%22%3A0%2C%22docstatus%22%3A0%2C%22uom%22%3A%22Meter%22%2C%22parentfield%22%3A%22items%22%7D%2C%7B%22basic_rate%22%3A0%2C%22transfer_qty%22%3A1%2C%22description%22%3A%22-+Echelle+%C5%95+c%C3%A2bles+type+KLIE+-+largeur+300+mm%22%2C%22parent%22%3A%22test-00001%22%2C%22basic_amount%22%3A0%2C%22creation%22%3A%222015-09-28+12%3A23%3A11.761348%22%2C%22conversion_factor%22%3A1%2C%22item_code%22%3A%22Cables+Ladder+type+KLIE+Width+300+mm%22%2C%22qty%22%3A1%2C%22parenttype%22%3A%22Stock+Entry%22%2C%22doctype%22%3A%22Stock+Entry+Detail%22%2C%22owner%22%3A%22Administrator%22%2C%22cost_center%22%3A%22Main+-+AZT%22%2C%22expense_account%22%3A%22Stock+Adjustment+-+AZT%22%2C%22actual_qty%22%3A1%2C%22modified_by%22%3A%22Administrator%22%2C%22name%22%3A%22fee83ca905%22%2C%22idx%22%3A10%2C%22item_name%22%3A%22Cables+Ladder+type+KLIE+Width+300+mm%22%2C%22additional_cost%22%3A0%2C%22modified%22%3A%222015-09-28+12%3A24%3A34.694701%22%2C%22s_warehouse%22%3A%22Stores+-+AZT%22%2C%22amount%22%3A0%2C%22stock_uom%22%3A%22Meter%22%2C%22batch_no%22%3A%22%22%2C%22valuation_rate%22%3A0%2C%22docstatus%22%3A0%2C%22uom%22%3A%22Meter%22%2C%22parentfield%22%3A%22items%22%7D%2C%7B%22basic_rate%22%3A0%2C%22transfer_qty%22%3A1%2C%22description%22%3A%22-+Echelle+%C5%95+c%C3%A2bles+type+KLIE+-+largeur+600+mm%22%2C%22parent%22%3A%22test-00001%22%2C%22basic_amount%22%3A0%2C%22creation%22%3A%222015-09-28+12%3A23%3A11.761348%22%2C%22conversion_factor%22%3A1%2C%22item_code%22%3A%22Cables+Ladder+type+KLIE+Width+600+mm%22%2C%22qty%22%3A1%2C%22parenttype%22%3A%22Stock+Entry%22%2C%22doctype%22%3A%22Stock+Entry+Detail%22%2C%22owner%22%3A%22Administrator%22%2C%22cost_center%22%3A%22Main+-+AZT%22%2C%22expense_account%22%3A%22Stock+Adjustment+-+AZT%22%2C%22actual_qty%22%3A0%2C%22modified_by%22%3A%22Administrator%22%2C%22name%22%3A%222c90539768%22%2C%22idx%22%3A11%2C%22item_name%22%3A%22Cables+Ladder+type+KLIE+Width+600+mm%22%2C%22additional_cost%22%3A0%2C%22modified%22%3A%222015-09-28+12%3A24%3A34.694701%22%2C%22s_warehouse%22%3A%22Stores+-+AZT%22%2C%22amount%22%3A0%2C%22stock_uom%22%3A%22Meter%22%2C%22batch_no%22%3A%22%22%2C%22valuation_rate%22%3A0%2C%22docstatus%22%3A0%2C%22uom%22%3A%22Meter%22%2C%22parentfield%22%3A%22items%22%7D%2C%7B%22basic_rate%22%3A0%2C%22transfer_qty%22%3A1%2C%22description%22%3A%22Cablofill+pour+locaux+indoor+-+gaine+thermoretractable+55%2F12+mm+1m%22%2C%22parent%22%3A%22test-00001%22%2C%22basic_amount%22%3A0%2C%22creation%22%3A%222015-09-28+12%3A23%3A11.761348%22%2C%22conversion_factor%22%3A1%2C%22item_code%22%3A%22Cablofill+for+indoor+premises+Shrink+sleeve+55%2F12+mm+1m%22%2C%22qty%22%3A1%2C%22parenttype%22%3A%22Stock+Entry%22%2C%22doctype%22%3A%22Stock+Entry+Detail%22%2C%22owner%22%3A%22Administrator%22%2C%22cost_center%22%3A%22Main+-+AZT%22%2C%22expense_account%22%3A%22Stock+Adjustment+-+AZT%22%2C%22actual_qty%22%3A0%2C%22modified_by%22%3A%22Administrator%22%2C%22name%22%3A%227d033c8dee%22%2C%22idx%22%3A12%2C%22item_name%22%3A%22Cablofill+for+indoor+premises+Shrink+sleeve+55%2F12+mm+1m%22%2C%22additional_cost%22%3A0%2C%22modified%22%3A%222015-09-28+12%3A24%3A34.694701%22%2C%22s_warehouse%22%3A%22Stores+-+AZT%22%2C%22amount%22%3A0%2C%22stock_uom%22%3A%22Meter%22%2C%22batch_no%22%3A%22%22%2C%22valuation_rate%22%3A0%2C%22docstatus%22%3A0%2C%22uom%22%3A%22Meter%22%2C%22parentfield%22%3A%22items%22%7D%2C%7B%22basic_rate%22%3A0%2C%22transfer_qty%22%3A1%2C%22description%22%3A%22Cablofill+pour+locaux+indoor+-+gaine+thermoretractable+%C5%95+tirette+34%2F12+mm+1m%22%2C%22parent%22%3A%22test-00001%22%2C%22basic_amount%22%3A0%2C%22creation%22%3A%222015-09-28+12%3A23%3A11.761348%22%2C%22conversion_factor%22%3A1%2C%22item_code%22%3A%22Cablofill+for+indoor+premises+Shrink+sleeve+to+pull+34%2F12+mm+1m%22%2C%22qty%22%3A1%2C%22parenttype%22%3A%22Stock+Entry%22%2C%22doctype%22%3A%22Stock+Entry+Detail%22%2C%22owner%22%3A%22Administrator%22%2C%22cost_center%22%3A%22Main+-+AZT%22%2C%22expense_account%22%3A%22Stock+Adjustment+-+AZT%22%2C%22actual_qty%22%3A0%2C%22modified_by%22%3A%22Administrator%22%2C%22name%22%3A%22f0a8573068%22%2C%22idx%22%3A13%2C%22item_name%22%3A%22Cablofill+for+indoor+premises+Shrink+sleeve+to+pull+34%2F12+mm+1m%22%2C%22additional_cost%22%3A0%2C%22modified%22%3A%222015-09-28+12%3A24%3A34.694701%22%2C%22s_warehouse%22%3A%22Stores+-+AZT%22%2C%22amount%22%3A0%2C%22stock_uom%22%3A%22Meter%22%2C%22batch_no%22%3A%22%22%2C%22valuation_rate%22%3A0%2C%22docstatus%22%3A0%2C%22uom%22%3A%22Meter%22%2C%22parentfield%22%3A%22items%22%7D%2C%7B%22basic_rate%22%3A0%2C%22transfer_qty%22%3A1%2C%22description%22%3A%22Cablofill+pour+locaux+indoor+-+gaine+thermoretractable+%C5%95+tirette+43%2F13+mm+1.5m%22%2C%22parent%22%3A%22test-00001%22%2C%22basic_amount%22%3A0%2C%22creation%22%3A%222015-09-28+12%3A23%3A11.761348%22%2C%22conversion_factor%22%3A1%2C%22item_code%22%3A%22Cablofill+for+indoor+premises+Shrink+sleeve+to+pull+43%2F13+mm+1.5m%22%2C%22qty%22%3A1%2C%22parenttype%22%3A%22Stock+Entry%22%2C%22doctype%22%3A%22Stock+Entry+Detail%22%2C%22owner%22%3A%22Administrator%22%2C%22cost_center%22%3A%22Main+-+AZT%22%2C%22expense_account%22%3A%22Stock+Adjustment+-+AZT%22%2C%22actual_qty%22%3A0%2C%22modified_by%22%3A%22Administrator%22%2C%22name%22%3A%22944be8791c%22%2C%22idx%22%3A14%2C%22item_name%22%3A%22Cablofill+for+indoor+premises+Shrink+sleeve+to+pull+43%2F13+mm+1.5m%22%2C%22additional_cost%22%3A0%2C%22modified%22%3A%222015-09-28+12%3A24%3A34.694701%22%2C%22s_warehouse%22%3A%22Stores+-+AZT%22%2C%22amount%22%3A0%2C%22stock_uom%22%3A%22Meter%22%2C%22batch_no%22%3A%22%22%2C%22valuation_rate%22%3A0%2C%22docstatus%22%3A0%2C%22uom%22%3A%22Meter%22%2C%22parentfield%22%3A%22items%22%7D%5D%2C%22from_warehouse%22%3A%22FZ9048E+-+AZT%22%2C%22total_incoming_value%22%3A0%2C%22doctype%22%3A%22Stock+Entry%22%2C%22name%22%3A%22test-00001%22%2C%22from_bom%22%3A0%2C%22docstatus%22%3A0%2C%22purpose%22%3A%22Material+Issue%22%2C%22__last_sync_on%22%3A%222015-09-28T10%3A28%3A18.559Z%22%2C%22__unsaved%22%3A1%7D&arg=%7B%22item_code%22%3A%221m+%2F%2F+optical+jumpers%22%2C%22warehouse%22%3A%22FZ9048E+-+AZT%22%2C%22transfer_qty%22%3A0%2C%22qty%22%3A0%7D&cmd=runserverobj

**Comment by gmarke** [comment]
sorry for the mess ;o)
this is the reqest sent by js to server, looks that is comming out form function get_server_fields from frappe.
I'm not sure if i can remove the parameter doc from this function??
there is already a comment that this function is alrady depricated.. how it can be replaced in  stock_entry.js ??

**Comment by rmehta** [comment]
Pushed in develop

commit 87f3f36823b0a66a0af6a3b9085e99111ceab1a9

**Comment by gmarke** [comment]
Working!!!


Thanks a lot.
