### ISSUE TITLE
Sales Analytics Report: Chart datasets is empty

### ISSUE THREAD

**Issue by casesolved-co-uk** [frappe/erpnext#40729]
### Information about bug

The Sales Analytics report generates table data, but the chart dataset has not been finished:

![Screen Shot 2024-03-28 at 03 34 36](https://github.com/frappe/erpnext/assets/110036763/454fe4f3-88b7-4715-abcf-134b57a5ee77)

![Screen Shot 2024-03-28 at 03 34 51](https://github.com/frappe/erpnext/assets/110036763/c4393a32-a2f6-4830-a4bc-d0b4570fa1c9)

https://github.com/frappe/erpnext/blob/9709a18ef5cd25ca01e97983a873c8b1f4675a8a/erpnext/selling/report/sales_analytics/sales_analytics.py#L404

### Module

selling

### Version

ERPNext: v16 develop

### Installation method

None

**Comment by Nihantra-Patel** [comment]
Hi @casesolved-co-uk,

To view the chart, you need to select the checkbox first.

![image](https://github.com/frappe/erpnext/assets/141945075/b7d5f18f-3459-4ef3-b36e-a8e44ccb740a)

Thank You!
