### ISSUE TITLE
Cannot update Project Form: "Company (company) cannot be hidden and mandatory without any default value"

### ISSUE THREAD

**Issue by RANSoftRA** [frappe/erpnext#40798]
### Information about bug

We upgraded from ERPNext 13 to 15, now adding a new field to the project form does not work anymore.

When trying to change the form (Projects > Project > Edit) via. `/app/customize-form ` clicking on update results in an error:

![image](https://github.com/frappe/erpnext/assets/8775880/dee9c0ef-ddea-4781-a42c-fa27e5f93373)

I tried to update the company field (setting hidden to false, setting a default value), but the changes are not being updated. The presented error always occurrs.

### Module

projects

### Version

ERPNext: v15.18.3 (version-15)

Frappe Framework: v15.19.1 (version-15)

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
Hi @RANSoftRA,

It's not an issue 😄, it's validation. If a field is mandatory, you can't hide it without setting a default value first. To hide it, set a default value, update the form, then hide it again and save. Hope that clarifies things.

**Comment by RANSoftRA** [comment]
Hi @Nihantra-Patel 

thank you for your response.

The thing is I cannot update the hidden property or add a default value for the field. The error still occurrs.

https://github.com/frappe/erpnext/assets/8775880/93a2ee6c-48ab-4bc2-9ca3-08b0f5d25caf

Fields are in german
- "Versteckt" = hidden
- "Standard" = Default value

**Comment by Nihantra-Patel** [comment]
You are going to be wrong.

Please check the steps.


https://github.com/frappe/erpnext/assets/141945075/1087dd19-90f3-468b-995f-e69b94f64c36

**Comment by RANSoftRA** [comment]
Thank you for the video, but as already mentioned - I receive an error when doing this. Maybe it has to do with the migration from 13 to 14 than 15. I dont know.

I have resolved the issue by resetting all customizations:

`Actions > Reset all Customizations` in the Customize-Form page.
