### ISSUE TITLE
Event Doctype Naming Error

### ISSUE THREAD

**Issue by nilpatel42** [frappe/erpnext#40795]
### Information about bug

My employee created event in calendar, which is only available to him

now when i am creating new event as administrator
its showing error this error

![image](https://github.com/frappe/erpnext/assets/135511086/59a1ab37-17af-4d7b-9267-bfd00f2c27ae)

### Module

other

### Version

ERPNext: v14.66.2 (version-14)
Frappe Framework: v14.69.0 (version-14)

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
Reference: https://discuss.frappe.io/t/event-doctype-naming-error/120144
