### ISSUE TITLE
Import Error: Coercing to Unicode: need string or buffer, nonetype found

### ISSUE THREAD

**Issue by cgpurbaugh** [frappe/erpnext#4079]
When attempting to import accounts, we keep getting this error for every line item.

**Comment by rmehta** [comment]
Can you check the detailed trace in the console?

**Comment by cgpurbaugh** [comment]
Are there instructions on how to do this?

**Comment by nabinhait** [comment]
Please send us the screenshot of the javascript console and also explain the exact steps you did?

Here's the help to open javascript console: http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers
