### ISSUE TITLE
[bug] when item code not same as name/id of item, item code filter not work in projected qty report

### ISSUE THREAD

**Issue by szufisher** [frappe/erpnext#40807]
### Information about bug

![image](https://github.com/frappe/erpnext/assets/12823863/9a549b81-26a6-435a-97e4-b97feaa09c9e)

above line 296 
item.item_code == item_code

should be 

item.name == item_code

### Module

stock

### Version

v13,v14, v15

### Installation method

None

**Comment by Nihantra-Patel** [comment]
Hi @szufisher,

It's worked properly, please check it.


https://github.com/frappe/erpnext/assets/141945075/287ddc2a-00cd-4367-b402-0a2c79bdb7e2
