### ISSUE TITLE
Issue with Gantt Chart

### ISSUE THREAD

**Issue by ajiragroup** [frappe/erpnext#40818]
### Information about bug

Gantt is an important tool for project management. In ERPNext, I have seen some slight malfunction in the way it behaves. When editing the chart by using the handles at the edge, it works fine until we refresh the view and the time automatically snaps to 12. See the video. (edit: please use chrome to view the video, apparently Firefox is not playing the video.) 

Edit: The problem occurs in Quarter day view. 

https://github.com/frappe/erpnext/assets/108009061/c6960e44-ec52-4cf4-8c67-d5f871835172

### Module

projects

### Version

erpnext 15.16.2
frappe 15.17.1

### Installation method

manual install

**Comment by safwansamsudeen** [comment]
@ankush could you transfer over to the gantt repo?

**Comment by Nihantra-Patel** [comment]
Kindly upgrade to version 15, everything is working fine. No problems were encountered in the latest version 15.


https://github.com/frappe/erpnext/assets/141945075/cf5cac6b-d83b-4423-918a-121999482337

**Comment by ajiragroup** [comment]
We are running v15. I request you to view the video we attached again. The problem comes not in day view but in quarter day view.
