### ISSUE TITLE
Cost Centre Budget second fiscal year not visible on cost centre

### ISSUE THREAD

**Issue by wjherckenrath** [frappe/erpnext#4081]
We have a project with a cost centre. I made some fiscal year 2015 budget lines and I created a fiscal year 2016 budget line on one of the accounts that has a budget in 2015 also. I can see in the budget variance report that the created budget line is there, but it is not visible on the project cost centre screen.

I tried to upload some screenshots but that failed.

**Comment by rmehta** [comment]
What do you mean by "project cost center" screen.

Use a service like imgur and post a link.

**Comment by wjherckenrath** [comment]
Hi

I attached the screenshots.

Met vriendelijke groet / Kind regards,

Willem-Jan Herckenrath
Manager ICT/SSC

Alewijnse Holding B.V.
Phone

: +31 24-3716140

Mobile

: +31 6-22478561

E-mail

: wj.herckenrath@alewijnse.com<mailto:wj.herckenrath@alewijnse.com>

Web

: www.alewijnse.com<http://www.alewijnse.com>



Alewijnse Holding B.V., Nijmegen, kvknr 10037019
[Alewijnse]

**Comment by rmehta** [comment]
Screenshots still not visible

**Comment by wjherckenrath** [comment]
It looks like the problem is solved. I say both fiscal years.

Met vriendelijke groet / Kind regards,

Willem-Jan Herckenrath
Manager ICT/SSC

Alewijnse Holding B.V.
Phone

: +31 24-3716140

Mobile

: +31 6-22478561

E-mail

: wj.herckenrath@alewijnse.com<mailto:wj.herckenrath@alewijnse.com>

Web

: www.alewijnse.com<http://www.alewijnse.com>



Alewijnse Holding B.V., Nijmegen, kvknr 10037019
[Alewijnse]
