### ISSUE TITLE
Taxes Not added Automatically after selecting a supplier, Added Tax Rule to the Supplier (for In State, Out State Rule)

### ISSUE THREAD

**Issue by zafar26** [frappe/erpnext#40819]
### Information about bug

Taxes are Not Added Automatically After Selecting a Supplier, and one more thing the supplier had a Tax Rule for Different Locations

### Module

buying

### Version

ERPNext Version - v15.18.1
Frappe Version - v15.19.0

Screenshot after Selecting Supplier
<img width="1148" alt="Screenshot 2024-04-02 at 12 51 54 PM" src="https://github.com/frappe/erpnext/assets/47274625/50039b10-8efc-409f-8a08-59c9c3f38fe4">

### Installation method

easy-install

**Comment by khushi8112** [comment]
Hey @zafar26 

I tried to replicate your issue but for me it is working fine.

<img width="1115" alt="Screenshot 2024-04-04 at 12 24 01 AM" src="https://github.com/frappe/erpnext/assets/142375893/799c3d23-a9c0-43cc-a01a-25a142b8b5ab">

Can you elaborate how you are creating tax rule for the supplier.
[You can refer this doc if it's needed.](https://docs.erpnext.com/docs/user/manual/en/tax-rule)
