### ISSUE TITLE
Issue while selecting supplier in Purchase Order 

### ISSUE THREAD

**Issue by ajiragroup** [frappe/erpnext#40829]
### Information about bug

While creating a new PO from Material request, I selected a supplier name. Then I get this warning message:

![image](https://github.com/frappe/erpnext/assets/108009061/165d0e0b-580a-4b5d-a01b-03e230016d3f)

### Module

buying

### Version

erpnext 15.16.2
frappe 15.17.1

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
Hi @ajiragroup,

We checked in the latest version 15, so we haven't found any type of issue. so please check it.


https://github.com/frappe/erpnext/assets/141945075/026c5b3d-bfad-4c64-94e8-f4a9b0a1751f


Thank You!

**Comment by ajiragroup** [comment]
@Nihantra-Patel Thanks! Will check again after updating the apps.
