### ISSUE TITLE
Multiple Tax in  Quatation , sales order and sales invoice

### ISSUE THREAD

**Issue by prash4** [frappe/erpnext#4082]
If we have multiple items with multiple tax rates , we are not able to show them in the sales documents like quotation , order and invoice  .

So is there any way we can do it .

And even we could have tax summary at the end , where we can show the break up

**Comment by PawanMeh** [comment]
Re-check the latest version 8. If the issue is still relevant post on [discuss](discuss.erpnext.com) or re-open issue by adding screen shots to explain the issue.
