### ISSUE TITLE
Database maxing out

### ISSUE THREAD

**Issue by DrTrills** [frappe/erpnext#4084]
Hi all,

I posted this on the forum but figured this being a technical issue GH might be a better option to keep it tracked/fixed.

This is the message that comes up when trying to save more fields:

OperationalError: (1118, 'Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs')

Here is the discussion: https://discuss.erpnext.com/t/maxing-out-the-db/7524/2

Thanks!

**Comment by rmehta** [comment]
Fixed.
