### ISSUE TITLE
POS Closing Entry not able to create sales invoice in a multi company instance

### ISSUE THREAD

**Issue by avaiskhatri** [frappe/erpnext#40866]
### Information about bug

POS Invoice & POS Closing Entry belongs to Company B,

When we submit POS Closing Entry, it try to creates Sales invoices for same comany (B), but the change amount accout is getting picked of company A (thats the error), it should pick account of company B.

I think is just automatically picking company A defaults cash change account on every transaction, instead it should use same company default account.

### Module

accounts, selling

### Version

V14

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Sales Invoice ACC-SINV-2024-00001: Account 1110 - Cash - PSAR does not belong to Company A
```

**Comment by Nihantra-Patel** [comment]
Your reference: https://discuss.frappe.io/t/pos-closing-entry-multi-company/120498/6?u=ncp
