### ISSUE TITLE
Account is not set for the dashboard chart Bank Balance

### ISSUE THREAD

**Issue by nilpatel42** [frappe/erpnext#40870]
### Information about bug

Account is not set for the dashboard chart Bank Balance

![image](https://github.com/frappe/erpnext/assets/135511086/bc03ed6d-3d19-4161-8985-fccd18922601)

### Module

accounts

### Version

ERPNext: v15.19.0 (version-15)
Frappe Framework: v15.20.0 (version-15)

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
If not added then add it.

```
locals[":Company"][frappe.defaults.get_user_default("Company")]["default_bank_account"]
```


https://github.com/frappe/erpnext/assets/141945075/f0eb668f-2310-4c1d-b044-6e191ea3b871
