### ISSUE TITLE
(Suggestion) Organization Chart

### ISSUE THREAD

**Issue by Ferohers** [frappe/erpnext#4087]
My suggestion is putting an organization chart under HR module. HR manually draws organization chart and updates it all the time. Time to time managers (plus consultants such as, KPMG) require it to look at bigger picture. I actually made a research and checked other open hr systems if I could bring something, after my research found out that it is above my skills.

Thank You!

Ref another open source project which has a basic org. chart system: http://sourceforge.net/projects/sentrifugo/

**Comment by jwrober** [comment]
This would be a great enhancement to HR module.
