### ISSUE TITLE
Default Value for Field not Updating 

### ISSUE THREAD

**Issue by nilpatel42** [frappe/erpnext#40884]
### Information about bug

Default Value for Field not Updating, I created custom small text field in Item doctype with Default text, after save it's showing in current items

when i change default text it's not updating in current item, in new creation item it's updated text

### Module

stock

### Version

ERPNext: v15.19.1 (version-15)
Frappe Framework: v15.20.0 (version-15)

### Installation method

None

**Comment by Nihantra-Patel** [comment]
Hi @nilpatel42,

When you change the defaul value, it will apply to the upcoming new creation document; it will not affect the older or current transaction. If changed, then you don't know, it will break the lots of older transaction and default value feature only worked on the new creation document or new transaction.
