### ISSUE TITLE
Drop Shipping Order based on Purchase Order

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#4089]
As per the latest discussion:

- [ ] One receipt of order from Customer, Sales Order will be created, of type Drop Shipment.
- [ ] Purchase Order will be created as Shipping Order.
- [ ] In Purchase Order, details will be fetched from Sales Order. Sales Order details like Customer details, Item and its selling price will be fetched into Purchase Order.
- [ ] Purchase Order of type Shipping Order will carry Customer and Supplier details.
- [ ] Sales Order wise Gross Profit report, only for drop shipment orders.

**Comment by umairsy** [comment]
In Sales Order Item table, if default Supplier is defined for an item, then Sales Order should show option create Purchase Order.

**Comment by Devens** [comment]
+1 (When this is expected to release?)

**Comment by connort77** [comment]
Really great feature to have, looking forward to it!

**Comment by nabinhait** [comment]
The feature has been released yesterday, documentation yet to come.

**Comment by Devens** [comment]
Great!! Could you please suggest the functionality and how can we check? If
some screen shots are available, it would be great.


Thanking you,

With Regards,
Deven Shah
Safeworld Systems Pvt Ltd
M - 09825060116

**Comment by nabinhait** [comment]
https://frappe.github.io/erpnext/user/guides/selling/drop-shipping.html
