### ISSUE TITLE
Opening Entry is wrongly fetched in Payment Entry

### ISSUE THREAD

**Issue by rknroot** [frappe/erpnext#40890]
### Information about bug

Opening Entry is wrongly fetched in Payment Entry
If we create opening entry for all customer and try to make a payment entry, the total opening balance is considered as outstanding amount for the customer and the first line of Journal Entry is considered as the customer's opening balance.

**Step to replicate :** 
Create 4-5 customers and make opening entry in Journal entry.
Create a Sales invoice for one customer except first customer in journal.
make a payment entry for any of the customer except first customer in journal.

![Greenshot 2024-04-07 11 52 57](https://github.com/frappe/erpnext/assets/9102676/b3d809b3-e2ea-427f-badf-a63e7e360bdb)
![Greenshot 2024-04-07 11 54 13](https://github.com/frappe/erpnext/assets/9102676/30a345c0-4aac-4bdd-91bf-93496e782e93)

### Module

accounts

### Version

ERPNext: v15.19.1 (version-15)

Frappe Framework: v15.20.0 (version-15)

### Installation method

None

**Comment by nabinhait** [comment]
@rknroot Couldn't replicate the issue in my local test instance.
