### ISSUE TITLE
Contact details not Fetch in Lead, only mail id and customer name fetched

### ISSUE THREAD

**Issue by aditya3366** [frappe/erpnext#40912]
### Information about bug

When an email is sent to the ERP mail, contact details should also be fetched. Currently, only the name and email are fetched. We require the capability to fetch contact details as well as some additional content when an email is sent to the ERP mail account

### Module

CRM

### Version

Frappe Version -  v15.17.3 (version-15)
ERPNext Version - v15.17.1 (version-15)

![Screenshot_185](https://github.com/frappe/erpnext/assets/107920741/325fdf1d-9af6-48d5-a31d-e420041c8444)

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
Hi @aditya3366,

You can only configure the Sender Email Field, Sender Name Field, and Subject Field. Thus, when an email arrives in the system, only these three fields can be configured. Currently, there is no option available to set other content. The main limitation lies in determining where and how to set the content.


https://github.com/frappe/erpnext/assets/141945075/d263bd01-aa7b-4e64-9a82-52d8a522b6dc
