### ISSUE TITLE
Suggestion:- on Contact form :- 'Phone' field  accepting strings also

### ISSUE THREAD

**Issue by ShraddhaRanjane** [frappe/erpnext#4092]
1. Go to "Contact" form
   2.Inside "Phone" - enter any string =fghfasd
   3.save contact form
   4.form get save.

I think "Phone"field should accept integer value and some  character (i.e + , -). but should not accept string

**Comment by cgpurbaugh** [comment]
I disagree, in some instances it may be beneficial to be able to enter a string.

**Comment by kennethsequeira** [comment]
Should be solved with: https://github.com/frappe/frappe/pull/9784
