### ISSUE TITLE
valuation is not correct (Serial Item), Stock Transfer , add to transit with additional cost 

### ISSUE THREAD

**Issue by thida-bcn** [frappe/erpnext#40933]
### Information about bug

Stock Transfer with additional cost (for serial items)
![image](https://github.com/frappe/erpnext/assets/62122640/8c6cd394-1864-4e10-acf1-761ad1f42d6c)
![image](https://github.com/frappe/erpnext/assets/62122640/5be95213-5a42-4611-b855-26b298594e29)
![image](https://github.com/frappe/erpnext/assets/62122640/06a900d8-98b2-4fc8-8dce-0191e64aaa21)
costing is correct at transit warehouse
end transit, valuation is not correct
![image](https://github.com/frappe/erpnext/assets/62122640/a785fb2a-5d13-49e5-8f30-16c2d135d70c)
![image](https://github.com/frappe/erpnext/assets/62122640/3ca29b4d-f789-42d5-83ee-0a0487bfcefd)![image](https://github.com/frappe/erpnext/assets/62122640/3988c7c8-fb88-471d-835f-9d8b89f54948)

### Module

stock

### Version

![image](https://github.com/frappe/erpnext/assets/62122640/aecfbd74-7d5c-44a8-bc3f-af2e670e2f4f)

### Installation method

manual install

**Comment by Poorvi-R-Bhat** [comment]
Not able to replicate. Screenshots are attached.
Stock Entry
![image](https://github.com/frappe/erpnext/assets/27720465/11e2c98d-ecf7-4e39-915c-71b39a65dafe)
Additional Cost:
![image](https://github.com/frappe/erpnext/assets/27720465/d140aa0b-c84c-42c9-a311-a46065f191a6)
Valuation Rate
![image](https://github.com/frappe/erpnext/assets/27720465/b0020fbe-3e60-41ef-bb72-4e7c7bff87f7)

**Comment by thida-bcn** [comment]
> Not able to replicate. Screenshots are attached. Stock Entry ![image](https://private-user-images.githubusercontent.com/27720465/325965791-11e2c98d-ecf7-4e39-915c-71b39a65dafe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMzM3MzMsIm5iZiI6MTcxNDEzMzQzMywicGF0aCI6Ii8yNzcyMDQ2NS8zMjU5NjU3OTEtMTFlMmM5OGQtZWNmNy00ZTM5LTkxNWMtNzFiMzlhNjVkYWZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDEyMTAzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlMDc3MDFiYTQ4MjkzNGFjNzNhMDRjNzA1ZWEwYjc3YjI5ZjNiYzY1NWQ0MGFkNWM3NWU5YzQwNGM1Mjc3ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hckH8QOcbpwv8pWIuEb4L5MTxNip416WmSsYWEvZnAc) Additional Cost: ![image](https://private-user-images.githubusercontent.com/27720465/325965998-d140aa0b-c84c-42c9-a311-a46065f191a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMzM3MzMsIm5iZiI6MTcxNDEzMzQzMywicGF0aCI6Ii8yNzcyMDQ2NS8zMjU5NjU5OTgtZDE0MGFhMGItYzg0Yy00MmM5LWEzMTEtYTQ2MDY1ZjE5MWE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDEyMTAzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzZmMwNjE2OWE2M2FhNjYyZjVmMTUwMDE0MTQ4YjQ4ZWMxNzNhZGFmNTEzYTkyOTg1MWZhZWRmMGIyNDA3ZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VLimUBi8cWzUa8D1KG3wYEhVPRy_SXj4UPePdwBIBko) Valuation Rate ![image](https://private-user-images.githubusercontent.com/27720465/325966147-b0020fbe-3e60-41ef-bb72-4e7c7bff87f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMzM3MzMsIm5iZiI6MTcxNDEzMzQzMywicGF0aCI6Ii8yNzcyMDQ2NS8zMjU5NjYxNDctYjAwMjBmYmUtM2U2MC00MWVmLWJiNzItNGU3YzdiZmY4N2Y3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDEyMTAzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3Yzc1YzBhYmEyOWU2YjkwMTdkNGFlYzQyOTg3MzM4M2JiN2Y3OTkxYjc4NTZkOTAxMDgxMmNjNDdjMzZiOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c5Jdyi5LnWkWQEZnJF-NUYwOG6m7F_W7OI7uaMNRpBs)

please let me know the version you are using?

**Comment by Poorvi-R-Bhat** [comment]
Tried replicating the issue  in both v15.18.3  and v14.61.1. Its working fine. Please check.

**Comment by thida-bcn** [comment]
Step to reproduce

1. Stock Entry
  2. Material Transfer with "Add to Transit" with additional cost(Stock Ledger is correct)
  3. Make "End Transit", check at stock ledger , additional cost didn't include in stock value

**Comment by thida-bcn** [comment]
> Tried replicating the issue in both v15.18.3 and v14.61.1. Its working fine. Please check.
for me 14.65.8 is working but version 14.66.3 is not working

**Comment by thida-bcn** [comment]
> Tried replicating the issue in both v15.18.3 and v14.61.1. Its working fine. Please check.

i forgot to mention that it was problems for serial items

**Comment by nabinhait** [comment]
It's working properly for serialised items as well in v15.

**Comment by thida-bcn** [comment]
> It's working properly for serialised items as well in v15.

version 15 is working well, we had upgraded urgently to v15
i will recheck with v14 latest at that time latest version had problems and decided to upgrade v15

**Comment by thida-bcn** [comment]
hello sir I had retest with v14 latest version
please check following link, i hope it will help
https://1drv.ms/v/s!ApZZW_p_lZ549ElyOuhi_Yoil25B?e=Poicuc
