### ISSUE TITLE
When creating a quality inspection from a purchase receipt while the quality inspection is in draft, the status of the purchase receipt changes to "Quality Inspection Pending

### ISSUE THREAD

**Issue by aditya3366** [frappe/erpnext#40942]
### Information about bug

When creating a quality inspection from a purchase receipt while the quality inspection is in draft, the status of the purchase receipt changes to "Quality Inspection Pending and while the quality inspection is submitted then the status of receipt changes to "Quality Inspection Completed
![Screenshot_186](https://github.com/frappe/erpnext/assets/107920741/ceed6a3b-008d-4f7c-80e8-cc00dc246a12)
"

### Module

stock

### Version

Frappe Version - v15.17.3 (version-15)
ERPNext Version - v15.17.1 (version-15)

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
Hi @aditya3366,

This is a feature request rather than a bug. However, you can address it by modifying a client script. It's not particularly challenging. Alternatively, you could also adjust the status server script or client script. Below, I've included the client script for your reference.

client script:

```js
frappe.ui.form.on('Purchase Receipt', {
    refresh: function(frm) {
        if (frm.doc.docstatus === 0) {
            $.each(frm.doc.items,  function(i,  d) {
                frappe.db.get_value("Item",
                {"name": d.item_code},
                "inspection_required_before_purchase",
                function(i_val) {
                    if (i_val.inspection_required_before_purchase === 1) {
                        frappe.db.get_value("Quality Inspection", 
                        {"reference_type": "Purchase Receipt", "reference_name": frm.doc.name}, 
                        "docstatus", function(qc_val) {
                            if (qc_val.docstatus === 0) {
                                frm.page.clear_indicator();
                                frm.page.set_indicator(__("Quality Inspection Pending"), 'orange');
                            } else if (qc_val.docstatus === 1) {
                                frm.page.clear_indicator();
                                frm.page.set_indicator(__("Quality Inspection Completed"), 'green');
                            } else {
                                frm.page.clear_indicator();
                                frm.page.set_indicator(__("Quality Inspection Not Created"), 'red');
                            }
                        });
                    }
                });
            });
        }
    }
});
```

**Output:**


https://github.com/frappe/erpnext/assets/141945075/de6f6740-8a11-40e8-a64a-8bf00cc23684

You can modify the code according to the requirement, you can also apply the same thing for delivery note time (Quality Inspection).

Hope this helps!
