### ISSUE TITLE
Suggestion:- if enter any invalid email id then error message not displaying

### ISSUE THREAD

**Issue by ShraddhaRanjane** [frappe/erpnext#4095]
i.Go to Contact Form. select "Email" checkbox.
ii.click on compose"button
iii.now enter any random character inside "To", CC field i.e do not enter @, .com  (i.e To= afshdasdd)
iv. click on "Send" button
v. Error Message not displaying.

I think error Message should displayed

**Comment by strixaluco** [comment]
`afshdasdd is not a valid Email Address` error message is displayed as of ERPNext: v8.x.x-beta (51cd2df) / Frappe Framework: v8.x.x-beta (da1ade6)
