### ISSUE TITLE
Production plan summary is not updating with completed purchase order quantity

### ISSUE THREAD

**Issue by alwinmartis** [frappe/erpnext#40977]
### Information about bug

after making purchase order complete production plan summary is not updating completed purchase order quantity

### Module

manufacturing

### Version

ERP next version 15

### Installation method

FrappeCloud

**Comment by Nihantra-Patel** [comment]
When the final stock entry for manufacturing is made from the work order, the Produced/Received Quantity and Pending Quantity will be updated. However, these updates are not based on the Purchase Order quantity.

![image](https://github.com/frappe/erpnext/assets/141945075/f959d4d2-199b-4d4b-a0f2-a664752db048)
