### ISSUE TITLE
Date Range wrong at Balance Sheet

### ISSUE THREAD

**Issue by thida-bcn** [frappe/erpnext#40984]
### Information about bug

![image](https://github.com/frappe/erpnext/assets/62122640/e79584cb-252a-4362-a78e-771b6e52f371)
Start / End Date is showing current fiscal year

### Module

accounts

### Version

![image](https://github.com/frappe/erpnext/assets/62122640/4222c232-8711-44b2-b270-2305a22b7f3f)

### Installation method

manual install

**Comment by Poorvi-R-Bhat** [comment]
Balance Sheet Report is showing the proper Fiscal Year based on the Fiscal Year set. 
![image](https://github.com/frappe/erpnext/assets/27720465/38730597-41f9-40da-b412-6194872ad80c)

Filter Based on Date Range ( Start Date and End Date) is also showing properly
![image](https://github.com/frappe/erpnext/assets/27720465/39ae63fb-318a-4c2a-890f-5636d75f55e9)

**Fiscal Year DocType**
![image](https://github.com/frappe/erpnext/assets/27720465/43345693-b4e1-463e-b291-1409279e728f)

Need the steps to replicate the issue.

**Comment by thida-bcn** [comment]
Fiscal Year
![image](https://github.com/frappe/erpnext/assets/62122640/b874c3bd-72e1-48a9-a4fe-0524b5187767)
Balance Sheet
![image](https://github.com/frappe/erpnext/assets/62122640/836fe32d-7cc8-4673-badf-3c6513680d17)
Report
![image](https://github.com/frappe/erpnext/assets/62122640/d9de74a9-230b-455e-bda2-8744d62b1f18)
For Date what we had been chosen were under FS 2023-2024
Report should show
Start Year - 2023-2024
End Year - 2023-2024

**Comment by Poorvi-R-Bhat** [comment]
Though the Date Range is proper in the Balance Sheet Report, In the Prepared report, it shows the wrong Fiscal Year.
**Balance Sheet Report Date Range:**
![image](https://github.com/frappe/erpnext/assets/27720465/7486da22-586e-4f6a-858d-1874ea4ecdbc)

**Prepared Report:**
![image](https://github.com/frappe/erpnext/assets/27720465/839b3835-6d5b-4c3e-9e8f-e3c8cc580719)

**Comment by nabinhait** [comment]
Even though From Fiscal Year is showing wrong year, it does not use while running the report. It uses actual from and to dates if "Filter Based On" is "Date Range".

**Comment by thida-bcn** [comment]
there was still issue with pick column
for end user "presentation" is very important, they just know what they see
![image](https://github.com/frappe/erpnext/assets/62122640/e0e07ba7-20cb-4332-9771-6f61c5702902)

https://github.com/frappe/erpnext/assets/62122640/2da08266-ffd7-47c4-a40a-71d1df7d221f

**Comment by thida-bcn** [comment]
@rmehta 
hello sir, help me check
thanks

**Comment by ljain112** [comment]
Fixed: https://github.com/frappe/frappe/pull/28331
