### ISSUE TITLE
Payment tool not working

### ISSUE THREAD

**Issue by eyaptangco** [frappe/erpnext#4099]
I am using the hosted cloud version of ERPNext.

When I use the payment tool, the amounts are not properly distributed across the multiple payment invoices when I review the JV document. What happens is that the 1st related purchase invoice is put into the full amount and the rest of the purchase vouchers are added to the JV document but with 0 debit and credit amounts. As a result, when I run the accounts payable query, the purchase vouchers are not properly cleared out.

This was working as of 9/29 and it seems to have broken today. Please fix ASAP.

**Comment by nabinhait** [comment]
@eyaptangco Could not replicate the issue in our test account. Can you please explain with some screenshots? Or can you replicate the issue in demo.erpnext.com?

**Comment by eyaptangco** [comment]
I am able to replicate it in the demo.erpnext.com environment. Here are the details of my transactions:

1. Entered 3 Purchase Invoices (PINV-00072, 73, and 74) dated 10/2 for abc company with the amounts of 2460, 4680, and 6900 respectively. Screen shot of PINV-00074 attached (1).

![1 - purchase invoice](https://cloud.githubusercontent.com/assets/14910291/10223568/a0a7c67a-6827-11e5-8a96-4b2a76fce6ff.png)

2. Put in a supplier payment to ABC company (JV-00092) for 14,040 dated 10/2.

![2 - supplier payment](https://cloud.githubusercontent.com/assets/14910291/10223587/cafab590-6827-11e5-9969-4466193e5344.png)

3. Went into the Payment Reconciliation tool and performed the reconciliation with the 3 Purchase Invoices.

![3 - payment reconciliation screen](https://cloud.githubusercontent.com/assets/14910291/10223613/eb6baee2-6827-11e5-9456-2b97112eb23a.png)

4. Went to the Payment and the entries are not correct as the amounts are not distributed to the individual purchase invoices. If you cancel the document and try to amend then save, validation errors occur since the allocations are not correct.

![4 - resulting jv with error entries](https://cloud.githubusercontent.com/assets/14910291/10223634/1939bba2-6828-11e5-93bd-da4961bd5bb0.png)

Please indicate if you need more information. All the test transactions should still be in the demo.erpnext.com environment.

Thanks.

**Comment by nabinhait** [comment]
Fixed via #4108
