### ISSUE TITLE
Unable to fetch Serial/Batch number from Delivery Note to Sales Invoice

### ISSUE THREAD

**Issue by HUMENTH** [frappe/erpnext#41003]
### Information about bug

Unable to fetch Serial/Batch Number from Delivery Note to Sales Invoice. So not able to print serial/batch number in sales invoice.
There should be an option to link same Serial And Batch Bundle to Delivery Note and Sales Invoice both document.

### Module

stock, selling

### Version

Frappe version - 15.21.0
ERPNext Version - 15.20.3

### Installation method

manual install

**Comment by rohitwaghchaure** [comment]
@HUMENTH You can't link the same serial and batch bundle in multiple documents.
