### ISSUE TITLE
Sales Invoice Item - rate not change when UOM is changed

### ISSUE THREAD

**Issue by volkswagner** [frappe/erpnext#41004]
### Information about bug

Running:
ERPNext: v14.67.1 (version-14)
Frappe Framework: v14.71.0 (version-14)
Bench Version 5.22.3
Python 3.11.2
Node v18.19.0

It's a fresh install on Debian 12. I created an item, (4) unique UOM, for prices in Default Selling.
When adding the item to a sales invoice, changing the UOM does not change the rate based
on Item Price for the UOM.

This symptom does not exist in:
ERPNext: v14.56.0
Frappe Framework: v14.60.0

### Module

stock, selling

### Version

Frappe Framework: v14.71.0 (version-14)
ERPNext: v14.67.1 (version-14)

### Installation method

manual install

**Comment by volkswagner** [comment]
There are dependencies and various results for UOM/Price. 
Results depend on if Item has "Maintain Stock" (need UOM conversions).
If disable Maintain stock, changing UOM in invoice, will fetch associated price!
Closing due to working as expected.

**Comment by Nihantra-Patel** [comment]
fixed in the upper version: https://github.com/frappe/erpnext/pull/40216

If you want, then we will raise the PR for version 14.
