### ISSUE TITLE
Purchase Order

### ISSUE THREAD

**Issue by sakshitjain02ji** [frappe/erpnext#41011]
### Information about bug

In purchase If item was created at the time of new purchase order they do not fetch the item tax and INR number formatting not working 

### Module

stock, buying, selling

### Version

don't know-15
 

### Installation method

None

**Comment by Poorvi-R-Bhat** [comment]
While creating the new Item in the Purchase Order, if the HSN/SAC is filled properly in the Item then the Item Tax gets fetched automatically in the Purchase Order
![image](https://github.com/frappe/erpnext/assets/27720465/b01dbec2-782c-40e0-893c-94afd1868148)

**HSN/SAC in the item**
![image](https://github.com/frappe/erpnext/assets/27720465/a9fc804e-ab8b-491e-8a20-22a9b9b82ca6)
