### ISSUE TITLE
Dashboard Duplicate

### ISSUE THREAD

**Issue by moaazmf** [frappe/erpnext#41014]
### Information about bug

1. go to dashboard list
2. choose one dashboard
3. from the menu click duplicate 
4. new screen will be opened but not able to change the name or even save the new dashboard

![image](https://github.com/frappe/erpnext/assets/29341232/6fc649b5-d3d2-4d6d-b910-fafe74cf4d7d)

### Module

other

### Version

Email Delivery Service: v0.0.1 (HEAD)
ERPNext: v15.18.3 (HEAD)
Frappe Framework: v15.20.0 (HEAD)

### Installation method

None

**Comment by Nihantra-Patel** [comment]
If developer mode is on, then it's working.

Developer Mode: 1


https://github.com/frappe/erpnext/assets/141945075/0941a86c-789b-4195-a082-6daccce3faf7



Developer Mode: 0


https://github.com/frappe/erpnext/assets/141945075/04a5da8c-7546-4ea7-b5e8-6d7be3f18c7f


___

Please check the documentation for [How to Enable Developer Mode in Frappe](https://frappeframework.com/docs/user/en/guides/app-development/how-enable-developer-mode-in-frappe)
