### ISSUE TITLE
Error in Monthly Attendance Sheet Report

### ISSUE THREAD

**Issue by kirthiss** [frappe/erpnext#4101]
Please see the attachment - The monthly Attendance Sheet report throws this error only for the months Oct, Nov & Dec. (Jan - Sep is fine).

![image](https://cloud.githubusercontent.com/assets/12151358/10214102/989b5afe-6832-11e5-81c1-a53c4cb5cb9d.png)

**Comment by nabinhait** [comment]
Fixed via #4103
