### ISSUE TITLE
No accounting entries for the following warehouses

### ISSUE THREAD

**Issue by geraldleungontario** [frappe/erpnext#41016]
### Information about bug

I'm getting this error "No accounting entries for the following warehouses: Stores - I" when I submit a Purchase Receipt. What's causing this error? I copied the warehouse and account information related to "Stores - I" warehouse.

"Stores - I" warehouse:
Parent Warehouse: All Warehouses - I
Account: Stock of finished products - I

"All Warehouses" warehouse:
Account: Stock of finished products - I

"Stock of finished products - I" account:
Parent Account: Stocks - I
Account Type: Stock

"Stocks - I" account:
Parent Account: Current assets - I
Account Type: Stock

"Current assets - I" account:
Parent Account: Active - I
Account Type: <blank>

"Active - I" account:
Parent Account: <blank>
Account Type: <blank>

### Module

accounts, buying

### Version

Docker frappe/erpnext:v15.20.2
Still happening with frappe/erpnext:v15.20.3

### Installation method

None

**Comment by geraldleungontario** [comment]
I did a similar test in the erpnext.com cloud which has using the warehouse "Stores - GTD", but it didn't cause this error. This environment doesn't have any accounts set up in the warehouses. Why would there be an error in my environment where I have accounts set up for the receiving warehouse and the parent warehouse?

This is the settings from erpnext.com below which doesn't cause the error.

"Stores - GTD" warehouse:
Parent Warehouse: All Warehouses - GTD
Account:

"All Warehouses - GTD" warehouse:
Account:

**Comment by deepeshgarg007** [comment]
@geraldleungontario Your local instance might not have a default inventory account setup in the company master while the erpnext.com might have a default inventory/stock account setup in the company master

Hence you get a validation while on the other site the one erpnext.com you did not.
