### ISSUE TITLE
Stock Entry Submitted Document is still in Draft stage

### ISSUE THREAD

**Issue by SaqlainsPSPL** [frappe/erpnext#41033]
### Information about bug

Hello,

![dH0vcSA](https://github.com/frappe/erpnext/assets/167191848/87b6086c-2d40-4867-9941-4f9bbde81f65)

As you can see in the image above, this warning comes when we submit the stock entry The status is changed to submitted, and workflow that were in pending approval will go to an approved state. But as the warning mentions, the task is running in the background, and if the stock entry runs at some error, it will revert the stock entry status back to draft, which it does, but the workflow state will remain in the approved state. So i think it should also go back to approval pending state as well.

Thanks & Regards
Saqlain Shaikh

### Module

stock

### Version

ERPNext: v14.65.7 (HEAD)

Frappe Framework: v14.68.2 (HEAD)

### Installation method

None

**Comment by Nihantra-Patel** [comment]
Any workflow applied or not, if applied, then check the workflow is proper or not.

We checked in the latest version 14 but we haven't found the issue. and also check if the RQ job status is active or not; if not, then enable the scheduler.


https://github.com/frappe/erpnext/assets/141945075/7cf51e62-ac0d-4afb-a84e-d38e498a0a51
