### ISSUE TITLE
Sales Invoice creation is skipped by POS when performing POS Close Entry

### ISSUE THREAD

**Issue by yogeshvachhani** [frappe/erpnext#41036]
### Information about bug

We are using the **POS** and everything seems to be working fine but we have observed that when we create **POS Close Entry**  at the end of the day sometimes the POS does not generate necessary `Sales Invoice` for each `POS Invoice`.  Some get skipped.

Because of this the **Quantity** of an Item reported by POS and that we get in various stock related reports do not match.

How to solve this problem?

### Module

selling

### Version

Frappe Version: 14.64.0
ERPNext Version: 14.61.4

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
No errors are generated.
```

**Comment by karanwilson** [comment]
Hi @yogeshvachhani,
As per the documentation of ERPNext (URL mentioned below):-
"The stock and accounting entries are now created at the end of day while closing a POS session by a **single sales invoice which merges all the intermediate invoices created throughout the day**";
each of these 'intermediate invoices' (logged in the POS Invoice "sub-ledger"), updates the "Reserved for POS Transactions" column in the "Stock Projected Quantity Report" - which are then consolidated as a single 'Sales Invoice', after you create the 'POS closing entry'.

Hence the ERPNext POS will not generate a separate 'Sales Incoice' for each 'POS Invoice'; instead it will consolidate the 'POS Invoices' logged between a "POS Opening Entry" and a "POS Closing Entry"

Reference:
https://docs.erpnext.com/docs/user/manual/en/pos_invoice_consolidation


@nabinhait

**Comment by yogeshvachhani** [comment]
Thanks for the clarification.

But the Qty reported by POS is different then that of `Stock Balance` and `Stock Ledger`. It is generally less the what is reported by Stock reports.

To test further...

We manually created Sales Invoices for all those POS Invoices which were not related to Sales Invoice to check and found that after we created necessary Sales Invoices the Qty reported by POS was the same as that reported by `Stock Balance` and `Stock Ledger`.

Why is this happening?

**Comment by karanwilson** [comment]
Yes, as per the documentation: when you create a "POS Opening Entry", the POS will reserve some QTY out of the "Actual QTY", in a column called "Reserved for POS Transactions", within the "Stock Projected Quantity Report".

Hence the POS QTY ("Reserved for POS Transactions") will be less than the "Actualy QTY" - either until you create a "POS Closing Entry" (which creates a consolidated Sales Invoice), or if you manually create a separate 'Sales Invoice' before closing the POS (note that after closing the POS, the consolidated Sales Invoice will again reduce the QTY as per the logged POS Invoice).

You can read this document in detail, to understand this process well:-
https://docs.erpnext.com/docs/user/manual/en/pos_invoice_consolidation

However, as long as your accounts and stock ledgers are in order, after the POS is closed, you do not need to worry about the internals of this process - it was designed to make the POS transactions faster.

@nabinhait

**Comment by yogeshvachhani** [comment]
Thanks for the clarification.

This means one will have to set the POS Profile to not Validate Stock.

![image](https://github.com/frappe/erpnext/assets/109499572/b19991c3-107a-47b8-8bd9-204abee97c91)
Because if this is setting is active POS does not allow to add an item which is zero (0).

**Comment by karanwilson** [comment]
Hi Yogesh, I just verified from the code that if you check "Validade Stock on Save" in the POS profile, ERPNext will check stock against the QTY that is reserved for POS; So this setting works as per the POS consolidation design discussed above.

Further, in case you wish to add an item in the POS cart, which has zero QTY - you will need to enable the option "Allow Negative Stock" in the "Stock Validations" tab of the "Stock Settings" page - attaching a screenshot for this.
![allow_negative_stock](https://github.com/frappe/erpnext/assets/48678570/f0e59699-5c57-4b18-b2a0-44d55b984f6a)

@nabinhait

**Comment by yogeshvachhani** [comment]
Ok understood.

Will try to setup the whole thing as per the documentation suggested.

Thanks a lot.
