### ISSUE TITLE
Quotation dropdown not opening

### ISSUE THREAD

**Issue by perotom** [frappe/erpnext#41054]
### Information about bug

In quotations the button "set as lost" and "create" are exchanged and the dropdown is not opening. It looks like the option is simply missing. With one user it is working, with another not.

User A:
![macos](https://github.com/frappe/erpnext/assets/3322872/93103353-be65-4891-93a3-51023885e8b3)

User B:
![windows](https://github.com/frappe/erpnext/assets/3322872/41c955ce-254d-43ec-aab5-96a97dc73d42)

Both users have the same permission. Is this a bug?

### Module

selling

### Version

ERPNext: v15.20.3 (version-15)
Frappe Framework: v15.22.0 (version-15)

### Installation method

easy-install

**Comment by Nihantra-Patel** [comment]
We tested it with multiple uses, and everything is working fine. No problems were encountered in the latest version 15.

Please migrate the site and check it.

<img width="1440" alt="image" src="https://github.com/frappe/erpnext/assets/141945075/274e44ee-a149-4332-ac89-b9e4d4a9f5e1">
