### ISSUE TITLE
Exchange Rate Not created for UAE (United Arab Emirates dirham) currency

### ISSUE THREAD

**Issue by Marimuthumariappan** [frappe/erpnext#41052]
### Information about bug

While create sales invoice Exchange rate not create automatically, customer currency is UAD, My company currency is USD  
Every time i create exchange is manually , other currency exchange rate is working fine, UAD currency exchange rate only not working
![Screenshot_25](https://github.com/frappe/erpnext/assets/166038816/ac4362bf-4eee-40c2-b787-781cdbea66db)

### Module

selling

### Version

ERP Next: v14.61.1

Frappe Framework: v14.63.0

Frappe HR: v14.21.3

### Installation method

docker

**Comment by Poorvi-R-Bhat** [comment]
Please refer the documentation for Exchange Rate: 
https://docs.erpnext.com/docs/user/manual/en/exchange-rate-revaluation
If the issue still persists then please let us know the steps to replicate

**Comment by nabinhait** [comment]
Please check which service provider you are using from the Currency Exchange Settings doctype. Maybe the selected service provider does not support UAD currency, in that case try changing the service provider.
