### ISSUE TITLE
Balance Qty Stock balance different from Balance Qty Stock ledger

### ISSUE THREAD

**Issue by KamHerve** [frappe/erpnext#41063]
### Information about bug

Hello, The issue that i am having is about the balance qty in my stock balance differing from the qty displayed in the stock ledger for some items. This is affecting me to the point that it is allowing negative stock in the system wvwn though I have disabled that feature. So, If there is any assistance you can provide on this issue i would be grateful.
Thank you.

### Module

stock

### Version

ERPNext: v13.42.4 (version-13)

Frappe Framework: v13.46.0 (version-13)

### Installation method

None

**Comment by rohitwaghchaure** [comment]
Since this issue is related to data, it's difficult to identify the issue without looking into data. If your site has hosted on frappe cloud and you have support plan then please create a support ticket.
