### ISSUE TITLE
Warranty claim document not fetching serial number by customer name

### ISSUE THREAD

**Issue by sapl-santhosh** [frappe/erpnext#41062]
### Information about bug

In the warranty claim document, If the customer name is selected. 
It is not filtering out the serial number that belongs to that customer. 
Rather it is showing all the list of serial numbers available. 

### Module

support

### Version

ERPNext: v15.20.3 (HEAD)

Frappe Framework: v15.22.0 (HEAD)

Frappe HR: v15.17.0 (HEAD)

India Compliance: v15.7.2 (HEAD)

Payments: v0.0.1 (HEAD)

### Installation method

FrappeCloud

**Comment by sapl-santhosh** [comment]
![image](https://github.com/frappe/erpnext/assets/109452795/1ad56bf8-c238-40f3-8645-62ab0d51e41f)

**Comment by Nihantra-Patel** [comment]
Hi @sapl-santhosh,

First thing, serial no doctype has no customer field, so how do we set filters without customers? It's a logical thing.

**Comment by sapl-santhosh** [comment]
![Screenshot 2024-04-19 144107](https://github.com/frappe/erpnext/assets/109452795/0afce678-6c3e-4211-a8e7-83fcd0637a8a)

this is screenshot from v14 serial no doctype. 
After that particular serial number has been used in a delivery note. 

it auto populates the customer name, also fills the warranty details.  
So I hope in the warranty claim document, after a customer name is selected the serial numbers can be filtered to match what all serial numbers that customer has purchased.

**Comment by Nihantra-Patel** [comment]
V14 and v15 have different functionality now, please check the serial doctype in v15. Lots of features have been changed.

**Comment by sapl-santhosh** [comment]
if you come across similiar type of requirement from someone. kindly try to add this feature. 

workflow will be 
1) first we open a issue of a customer from their email manually. (Issue doc type)
2) then if there is a product issue. we raise a warranty claim
3) so from issues doc, we create a warranty claim. In that when we select customer name, based on that if the serial nos are populated it will be easy for a support agent to choose it. 

as I now create a V14 site and checked. The serial doctype is fetching the customer name after a delivery note. But in the warranty claim doctype the serial number is not filtering out based on customer name. 

either its v14 or v15. if this feature was there. it will be useful.

**Comment by Nihantra-Patel** [comment]
> as I now create a V14 site and checked. The serial doctype is fetching the customer name after a delivery note. But in the warranty claim doctype the serial number is not filtering out based on customer name.


Certain functionalities can be carried forward to the upper version because maintaining the document store or other details might be cumbersome, so they cannot be backported to v14. I understand the challenges you're facing, but it was removed in v15 due to the new feature of [Serial and Batch Bundle] (https://docs.erpnext.com/docs/user/manual/en/serial-and-batch-bundle).

hope you understand.

**Comment by sapl-santhosh** [comment]
Even when serial number of the product sold to that customer is selected in the serial number field it is not populating the Item code and other details. Also put up a error related to delivery date field.
![Screenshot 2024-04-23 122626](https://github.com/frappe/erpnext/assets/109452795/b7d608f1-6390-4389-9107-206d9c2304ee)

![Screenshot 2024-04-23 122729](https://github.com/frappe/erpnext/assets/109452795/1611fd25-dc7f-4e32-afbf-3747acbca45e)
