### ISSUE TITLE
[Feature Request]: From Date and To Date filters for Payment Tool

### ISSUE THREAD

**Issue by eyaptangco** [frappe/erpnext#4107]
There is no date filter for the Payment Tool so when I click Get Outstanding Requests, all the unpaid Invoices appear.

Please add From Date and To Date parameters that filter on the Invoice Posting Date like what you have in the other Account Tools (e.g. Bank Reconciliation, Payment Reconciliation).

Thanks.

**Comment by nabinhait** [comment]
Payment tool will be deprecated in v7. Instead there is a new Payment Entry form.
