### ISSUE TITLE
Autoselection of Batch Bundle on Point of Sale

### ISSUE THREAD

**Issue by Skoros16** [frappe/erpnext#41088]
The POS of Sale process could be much faster provided that users don't have to select the batch number each time they have a batched item on the item cart.

![Screenshot 2024-04-17 095829](https://github.com/frappe/erpnext/assets/164153267/a5a0b661-3386-45ed-adcb-7607789313af)

From the screenshot above, the item is set up as having their batch automatically created.

![Screenshot 2024-04-17 095946](https://github.com/frappe/erpnext/assets/164153267/61c9a1dd-0ca5-4c96-9632-fdf6f4ed50c6)

Stock Settings have also been set up to auto create the serial and batch bundle for all outward stock movement.

![Screenshot 2024-04-17 100107](https://github.com/frappe/erpnext/assets/164153267/bb1235dc-a8a8-4935-9abb-d834f4827151)

However at the point of checkout on the Point Of Sale, the batched item is removed from the cart due to the batch number not being selected.

Just as Batch bundles are being automatically picked when it comes to the other normal sales process, having the same applicable for the Point of Sale will be really useful.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Nihantra-Patel** [comment]
Duplicate Issue: #41070
