### ISSUE TITLE
Automatic Comment showing in today's date

### ISSUE THREAD

**Issue by Sunil-Codes** [frappe/erpnext#41082]
### Information about bug

In the lead doc when I am opening any lead it is showing a comment on my name and on today's date but that was not submitted by me.

we checked it with different user in their account that same lead is showing on their name and same on today's date how it is happening 

![image](https://github.com/frappe/erpnext/assets/70105075/11e6f9e7-79c2-4d98-a314-73173d7f627b)
Screenshot of user1

![image](https://github.com/frappe/erpnext/assets/70105075/c9d2b882-50bf-4db4-b82c-929b28fd56f6)
Screenshot of user2

What is this issue?

### Module

CRM

### Version

ERPNext: v14.43.0 (HEAD)
Frappe Framework: v14.51.0 (HEAD)

### Installation method

None

**Comment by Nihantra-Patel** [comment]
If you don't know, open then unhide table and check it.


https://github.com/frappe/erpnext/assets/141945075/474c8627-6350-4bc4-8056-d83a9592fedc
