### ISSUE TITLE
Can't Purchase Return when One of Batch is Not Available or Not Completed

### ISSUE THREAD

**Issue by xhijack** [frappe/erpnext#41080]
### Information about bug

I have a Purchase Receipt with batch items. For example, I have one item with 10 batches. When one of the batches is empty or sold out, I couldn't create a purchase return. I believe a purchase return should be possible as long as the purchase return has not been submitted.

<img width="699" alt="Screenshot 2024-04-18 at 11 32 42" src="https://github.com/frappe/erpnext/assets/1784964/68ef6659-33d0-4651-971d-560d6e4c9774">
create purchase return in purchase receipt
FYI:  I have enable "Allow Negative"

### Module

stock

### Version

ERPNext: v15.20.3 (version-15)

Frappe Framework: v15.22.0 (version-15)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Batch No BMJ2404170344 of an Item JM00000002 has negative stock of quantity -20.0 in the warehouse Stores - JMT
```

**Comment by rohitwaghchaure** [comment]
Allow negative stock doesn't make Sense for Batch or serial no, if the batch has already consumed then how could you return it?

**Comment by xhijack** [comment]
I understand that if all batches have been sold, then it's not possible to return them. However, the main issue lies elsewhere. For example, I create a purchase receipt for 10 different batches. Then, I make a sale for 1 batch, leaving me with 9 batches. However, when I try to make a return, the system rejects it because 1 batch is no longer available. Returns should still be possible as long as I have the remaining 9 batches.

**Comment by xhijack** [comment]
Reopening.
