### ISSUE TITLE
[BUG] [DOCUMENTATION] Unable to disable/hide unused apps

### ISSUE THREAD

**Issue by SalahAdDin** [frappe/erpnext#41119]
### Information about bug

We are trying to hide/disable all the applications we don't need for our small company.

We followed the current [documentation](https://docs.erpnext.com/docs/user/manual/en/show-hide-modules) but the current home does not have such a feature.

[This documentation](https://github.com/frappe/manual_erpnext_com/blob/master/manual_erpnext_com/www/contents/customize-erpnext/hiding-modules-and-features.md) is also outdated.

Also, we don't find any valid documentation about disabling unused applications since `bench` does not work for production.

What should we do?

### Module
ERPNext

### Version

Frappe: 15.20.6
ERPNext: 15.20.6

### Installation method

docker

**Comment by Nihantra-Patel** [comment]
Please check it.


https://github.com/frappe/erpnext/assets/141945075/d51ea620-c9dc-44dd-9d2f-8b0db9d55e82

For the user, then you can disable it from the user doctype. 

And if you want to set the role wise workspace, then check the below image.

![image](https://github.com/frappe/erpnext/assets/141945075/52bc90cc-8a90-4216-9592-30aa3d2b70c9)

**Comment by SalahAdDin** [comment]
> Please check it.
> scrnli_22_04_2024_16-55-06.mp4
> 
> For the user, then you can disable it from the user doctype.
> 
> And if you want to set the role wise workspace, then check the below image.
> 
> ![image](https://private-user-images.githubusercontent.com/141945075/324442365-52bc90cc-8a90-4216-9592-30aa3d2b70c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4MjE2MzAsIm5iZiI6MTcxMzgyMTMzMCwicGF0aCI6Ii8xNDE5NDUwNzUvMzI0NDQyMzY1LTUyYmM5MGNjLThhOTAtNDIxNi05NTkyLTMwYWEzZDJiNzBjOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMlQyMTI4NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYzkzNTY0NTA2YTQyY2NjMWJkOGYyNWRkN2RhYTRlZWViYzM3ZjI5NmNjY2FiZGU2MWVkMzQ4ZDYwZjgzNTQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.U6ij-cs_r50sO0O9F0iBxJ3VPMjPM4ZLmr6E0STXl8M)

Hiding them one by one is annoying! 

Despite of... why is the documentation outdated? I could not find anything about this clear in the documentation.

Also, the Odoo-like iconed dashboard... what happened with it? It is still visible on the documentation.

Does Frappe have plans to update the documentation soon?

Finally, wouldn't it be better to make the module installation available on the ERP setup? Like in Odoo?

**Comment by Nihantra-Patel** [comment]
Hi,

Different ERP systems have varying functionalities, so setting them identically and comparing them isn't feasible. In versions 14 and 15, many functionalities have been updated. We acknowledge that some of the documentation may be outdated. However, you can check the current documentation for [workspace](https://frappeframework.com/docs/user/en/desk/workspace). We will remove the outdated links as soon as possible.

You can configure module visibility rights for users directly. However, if you need to set workspace visibility, please refer to the steps provided in the previous post. Currently, there are no other options available.

![image](https://github.com/frappe/erpnext/assets/141945075/6fa27c91-b58b-4d33-a2bb-d149e96e411d)

**Comment by SalahAdDin** [comment]
> Hi,
> 
> Different ERP systems have varying functionalities, so setting them identically and comparing them isn't feasible. In versions 14 and 15, many functionalities have been updated. We acknowledge that some of the documentation may be outdated. However, you can check the current documentation for [workspace](https://frappeframework.com/docs/user/en/desk/workspace). We will remove the outdated links as soon as possible.
> 
> You can configure module visibility rights for users directly. However, if you need to set workspace visibility, please refer to the steps provided in the previous post. Currently, there are no other options available.
> 
> ![image](https://private-user-images.githubusercontent.com/141945075/324687239-6fa27c91-b58b-4d33-a2bb-d149e96e411d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MTE5NzYsIm5iZiI6MTcxMzkxMTY3NiwicGF0aCI6Ii8xNDE5NDUwNzUvMzI0Njg3MjM5LTZmYTI3YzkxLWI1OGItNGQzMy1hMmJiLWQxNDllOTZlNDExZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyM1QyMjM0MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMmFkY2Y2MTUyNzkyYzllN2NhYmI3MzAwNjA1NWI5YTQwMDA5NDRiNzZiZjBjOWQ4NDE1YjdlNGUxMTk2NWI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fdRkWSC_NPmIeCXqwX0LFiDvaX04wWS9ucfTMe323OI)

Even Odoo have documentation for each ERP version, is it hard for Frappe to update the documentation?

**Comment by Nihantra-Patel** [comment]
Already updated workspace documentation link provided.

Thank You!
