### ISSUE TITLE
[BUG] Serial and Batch Bundle deadlock during deleting Stock Reconciliation

### ISSUE THREAD

**Issue by toofun666** [frappe/erpnext#41129]
### Information about bug

Serial and Batch Bundle causes deadlock during deleting Stock Reconciliation when a reconciliation ivolves batch numbers and have been accidentally Submiited with the bundle. Both of the Doctypes can be Cancelled but after that, they cannot be deleted because two Doctypes in Cancelled state are still bound blocking the Deletion of both Doctypes.

### Module

accounts, stock

### Version

ERPNext: v15.20.6 (version-15)
Frappe Framework: v15.23.0 (version-15)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Received while trying to delete Cancelled Stock Reconciliation:
Cannot delete or cancel because Serial and Batch Bundle SABB-00000141 is linked with Stock Reconciliation MAT-RECO-2024-00031
Received while trying to delete Cancelled Serial and Batch Bundle:
Cannot delete or cancel because Serial and Batch Bundle SABB-00000141 is linked with Stock Reconciliation MAT-RECO-2024-00031
```

**Comment by rohitwaghchaure** [comment]
@toofun666 We have fixed the issue, kindly pull the latest update and check
