### ISSUE TITLE
Error Matching Accounts Cache Data with Account DB

### ISSUE THREAD

**Issue by osamaerksosi** [frappe/erpnext#41125]
### Information about bug

When make change in grand father parent Account (location in tree) the lft and rgt of children accounts not matching between database and cache.
this mismatch make a problem in general ledger when you set account filter for one of mismatched accounts
 this example will explain the case:
<img width="808" alt="before" src="https://github.com/frappe/erpnext/assets/48605449/b2782fdf-44f8-4d2b-9e83-adb300e30f9d">

<img width="808" alt="after" src="https://github.com/frappe/erpnext/assets/48605449/5c582010-905f-4855-b3e3-8fc0c8936c4c">

### Module

accounts

### Version

Frappe Version v15.23.0
Erpnext Version v15.20.6

### Installation method

manual install

**Comment by rmehta** [comment]
`get_cached_doc` is supposed to be used within a transaction. Where are you facing this problem?

**Comment by osamaerksosi** [comment]
it used in general ledger report which causes interference and problems in fetching data when we filter by account
https://github.com/frappe/erpnext/blob/cacb5bfe03da45b6f7c360a35a48c95c48d8f4e3/erpnext/accounts/report/general_ledger/general_ledger.py#L323
