### ISSUE TITLE
Item Table getting disturbed after changing the Editable Grid unchecked

### ISSUE THREAD

**Issue by dineshpanchal93** [frappe/erpnext#41132]
### Information about bug

<img width="1096" alt="Screenshot 2024-04-22 at 11 36 37 AM" src="https://github.com/frappe/erpnext/assets/21578167/415e876e-a855-4eef-b030-10b7a6673274">

### Module

other

### Version

ERPNext: v15.20.5 (version-15)

Frappe Framework: v15.23.0 (version-15)

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
Did you apply any scripts?

**Comment by dineshpanchal93** [comment]
@Nihantra-Patel No

There is no changes in the frappe and ERPNext not even the client script too

**Comment by Nihantra-Patel** [comment]
I don't know, what's going on, but every problem is facing you only! 😅


https://github.com/frappe/erpnext/assets/141945075/8cca8be7-4937-460d-af1b-3668dc800eba

**Comment by Nihantra-Patel** [comment]
Please check with latest version, we haven't found any type of issue.
