### ISSUE TITLE
Scan Item in delivery not are very slow fetch in delevery item table

### ISSUE THREAD

**Issue by mmplerp** [frappe/erpnext#41148]
### Information about bug

When we make delevery note and scan item with barcode than all item price and discount are auto refresh and scan item fetch in around  20 to 40 second

### Module

stock

### Version

Frappe 15.23
ErpNext 15.20.5

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
Not error
```

**Comment by nabinhait** [comment]
Can't replicate
