### ISSUE TITLE
dynamic variable unusable

### ISSUE THREAD

**Issue by nakul80** [frappe/erpnext#41152]
### Information about bug

Inbuilt variable for fiscal year is illogical compared to the warning given by the system regarding limitation of numbers for GST. I feel .FY. should be in 2 digit year form.

The system itself previews generating invoice numbers as 19 digits if one simply puts SINV-.FY. as the format whereas the warning on the top says maximum 16 allowed in GST. If we try to combine with fields or more customised naming, the variable .FY. leaves no room for any other variables or fields.

![image](https://github.com/frappe/erpnext/assets/64956588/2c2557e4-ad5a-4fd9-8dae-636183a7cc50)

### Module

accounts

### Version

ERPNext: v15.20.5 (HEAD)
Frappe Framework: v15.23.0 (HEAD)

### Installation method

FrappeCloud

**Comment by Nihantra-Patel** [comment]
Hi @nakul80,

The validation is set within the India Compliance, not within the ERPNext. We are unable to condense the invoice series as users from various regions are working on this series, and only the India region has a validation requirement stating, "Naming Series should not exceed 16 characters for GST."

https://github.com/resilient-tech/india-compliance/blob/3bba90d64d35e1b1e42dd9a04d518c1c588aa2d4/india_compliance/public/js/utils.js#L247-L261

https://github.com/resilient-tech/india-compliance/blob/3bba90d64d35e1b1e42dd9a04d518c1c588aa2d4/india_compliance/public/js/transaction.js#L285


When you create a fiscal year, then define in a small word like (2425).

**Comment by nakul80** [comment]
Is it not possible to just give one more variable with condensed fiscal
years?

Regards

Nakul

**Comment by Nihantra-Patel** [comment]
might be possible, but customization is needed.
