### ISSUE TITLE
Unable to delete custom field

### ISSUE THREAD

**Issue by asbasawaraj** [frappe/erpnext#4116]
Hi,

I added a custom field(check box) in Lead form .

I named it "Unelectrified?"......  Names with special characters are not allowed but somehow it is saved. I cannot update the name of the field also I cannot delete the custom field. 

Even if I hit "Reset to default" and confirm, this is field is not getting deleted!!!

Can anyone help me,

![error](https://cloud.githubusercontent.com/assets/11595602/10261691/c7375350-69c1-11e5-9dbd-4e47bf8b9b8a.png)

Thanks

**Comment by rmehta** [comment]
Did you try deleting it from the Custom Field page?

As an immediate fix you can also delete it from the database.

We will fix this validation.

**Comment by asbasawaraj** [comment]
Yes I was able to delete from custom field Page.

Should I close this issue now or you will close it once validation is added?

Thanks.
