### ISSUE TITLE
Issue on fetching exchange rate when making sales order from purchase order

### ISSUE THREAD

**Issue by AureliusIvan** [frappe/erpnext#41163]
## Step to reproduce the issue:
1. Create a Purchase Order from an existing Sales Order. The Sales Order currency is in IDR, but the Purchase Order currency is in USD.

## Observed result:
1. The exchange rate in PO is not fetched automatically. It shows 1 instead of the correct rate (around 16000)
2. The currency for PO items remains unchanged, not switching to USD.
3. The last PO Item has 0 item price even though there is an item price for that Item

## Expected result:
1. The exchange rate should be fetched automatically when creating a purchase order from a sales order.
2. The currency for items should switch to USD in line with the currency conversion.
3. All items should display their correct prices as per the defined item prices.

## Apps:
ERPNext: v14.56.0 (HEAD)
Frappe Framework: v14.66.0 (HEAD)

**Sales Invoice Doctype**
![image (21)](https://github.com/frappe/frappe/assets/102419837/ca2f0fde-686a-4987-ab3b-5171bb78190b)

**Purchase Order Doctype** 
![image (22)](https://github.com/frappe/frappe/assets/102419837/f8cdff91-b294-429a-b7a8-e7abe954fc93)

**Item Price List Doctype**
![image (23)](https://github.com/frappe/frappe/assets/102419837/e3782d99-4831-4015-ad30-408591850565)

**Comment by Poorvi-R-Bhat** [comment]
1. Exchange rate is being fetched automatically on creating the Purchase Order from Sales Order DocType. 
2. Currency is also being set in the Purchase Order DocType from the Sales Order  Doctype.
3. The items are displaying the Item Price based on the Rates and Price List defined on the Item Price DocType.

Sales Order 
![image](https://github.com/frappe/erpnext/assets/27720465/d53b4d21-c137-4da0-b097-8089a569f65d)

Purchase Order
![image](https://github.com/frappe/erpnext/assets/27720465/2c8fe173-8a98-41c5-8600-80e9a7ea6846)

**Comment by Poorvi-R-Bhat** [comment]
1. Exchange rate is being fetched automatically on creating the Purchase Order from Sales Order DocType. 
2. Currency is also being set in the Purchase Order DocType from the Sales Order  Doctype.
3. The items are displaying the Item Price based on the Rates and Price List defined on the Item Price DocType.

Sales Order 
![image](https://github.com/frappe/erpnext/assets/27720465/d53b4d21-c137-4da0-b097-8089a569f65d)

Purchase Order
![image](https://github.com/frappe/erpnext/assets/27720465/2c8fe173-8a98-41c5-8600-80e9a7ea6846)
