### ISSUE TITLE
Plaid integration failing

### ISSUE THREAD

**Issue by Pvir24** [frappe/erpnext#41190]
### Information about bug

![PHOTO-2024-04-23-10-28-30](https://github.com/frappe/erpnext/assets/168130806/0d01015c-f9e3-4416-9ec1-ffa01ff9a894)

### Module

accounts

### Version

ERPNext: v15.21.0 (HEAD)

Frappe Framework: v15.24.1 (HEAD)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
NA
```

**Comment by nabinhait** [comment]
As the message shows, currently system does not support multi-factor authentication. Please disable it to use the plaid integration.
