### ISSUE TITLE
How to assign projects to supplier invoice or purchase orders

### ISSUE THREAD

**Issue by istvano** [frappe/erpnext#4120]
Dear Team,

I love erp next. Great work! 

I am evaluating it and I have one question I hope you can answer.

I sell services and services are broken down by projects.

I can see that I can assign a project to SALES ORDERs which is great although most of my services are provided by subcontractors. Hence I would need to assign projects to PURCHASE ORDERs as well.

is there I was I can do this ?

I would think that being able to assign projects could be a cross cutting feature so that projects can be assign to many items. 

For example I actually invoice my customers sometimes where

each invoice line ( row ) actually belongs to a different project.

e.g.

50h consulting project A
20h consulting project B
10h consulting project C

should I implement this using products / project then ?

Thanks very much for pointing me to the right direction.

Kind Regards,

**Comment by nabinhait** [comment]
You should find project field in Item table in entire purchase cycle.

**Comment by istvano** [comment]
Hi,

Thanks very much! I can see it on Supplier quotation. Great !
