### ISSUE TITLE
The text field "Married" showing in the Different language

### ISSUE THREAD

**Issue by sanjay141986** [frappe/erpnext#41223]
### Information about bug

The Created a Web form based on Employee Document but in the Web form for the Matial Status field the Married option is showing in the a Different Language.
![image](https://github.com/frappe/erpnext/assets/108865344/0c8db27f-410c-42b9-ba7e-ebb9087528a7)

We checked the Bench site country and Company country both are set to India but don't know from where it is fetching in different language.

**Workaround:** We added a Translation for Martial Staus for Married and then it work properly in the Webform.
![Screenshot 2024-04-29 at 9 11 25 AM](https://github.com/frappe/erpnext/assets/108865344/78f9c3b3-e67d-47ff-b4de-b14ca4e1b7fa)

 

### Module

other

### Version

Frappe Chat: v0.0.1 (HEAD)

ERPNext: v15.21.2 (HEAD)

Frappe Framework: v15.24.1 (HEAD)

Frappe HR: v15.20.1 (HEAD)

### Installation method

None

**Comment by raaannzzz** [comment]
same problem with employee

**Comment by deepeshgarg007** [comment]
@sanjay141986 This should be fixed now.
