### ISSUE TITLE
Expense claim not linking to the bank entry

### ISSUE THREAD

**Issue by phpmathan** [frappe/erpnext#4122]
Steps to replicate:
1. create a new expense claim and approve
2. click "Make Bank Entry" button from approved claim, and make bank entry and submit (here, row item correctly referenced to expense claim number).
3. After making bank entry, back to the claim page and click "Reload" - nothing happens, and "Make Bank Entry" button still showing, and also when click "Links" menu it showing "Not Linked to any record."

**Comment by nabinhait** [comment]
Fixed
