### ISSUE TITLE
Multiple Purchase receipt are getting created in Draft

### ISSUE THREAD

**Issue by satisharalkar** [frappe/erpnext#41225]
### Information about bug

Hi Team,

Currently, we observed that multiple purchase receipts are getting created in Draft status against the same PO.

currently system stops while submit the "Purchase Receipt"  but draft receipts should not be created.

### Module

buying

### Version

ERPNext: v15.17.1 (version-15)

Frappe Framework: v15.17.3 (version-15)

Frappe HR: v15.14.1 (version-15)

India Compliance: v15.5.7 (version-15)

### Installation method

manual install

**Comment by nabinhait** [comment]
This is not a bug, it is by design. If you don't want the behaviour, you can add a validation via server script.
