### ISSUE TITLE
Trial Balance not equal to Balance Sheet

### ISSUE THREAD

**Issue by AndreiaFerreira** [frappe/erpnext#4124]
Trying to get a trial balance for the year and it doesnt reflect some movements. But they are reflected in the Balance Sheet report and P&L.
Even when i get a Journal documents report, some of them don't appear, and there are no filters...

**Comment by nabinhait** [comment]
Can you provide some screenshots and more details?

**Comment by AndreiaFerreira** [comment]
Hi,

Thank you for your quick answer!

Find in attach a print screen of the “normal” journal documents without filter and the Journal Report, where you can see that in the first you only have till JV-00046 and in the second you have till JV-00049.

Thank you.

**Comment by nabinhait** [comment]
No screenshots attached. If you are still getting the issue, post the screenshots again.
