### ISSUE TITLE
Session default Not Working (List View)

### ISSUE THREAD

**Issue by Kamereldawla** [frappe/erpnext#41265]
### Information about bug

the company displayed in the "Company" search field does not change based on their selections in the current session.
![Screenshot_3](https://github.com/frappe/erpnext/assets/50329342/9b981a98-3b89-4202-800f-61562d12c007)
![Screenshot_4](https://github.com/frappe/erpnext/assets/50329342/68850770-172a-49f8-9930-833d59a7e404)

### Module

other

### Version

ERPNext: v15.20.6

Frappe Framework: v15.23.0

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
the company displayed in the "Company" search field does not change based on their selections in the current session.
```

**Comment by Kamereldawa** [comment]
the company displayed in the "Company" search field does not change based on their selections in the current session.

**Comment by gsbaig** [comment]
I have suggestion for this session defaultcompany. can we move this  to the top bar near user icon . it will be very helpful

**Comment by Nihantra-Patel** [comment]
Hi @Kamereldawa,

Session defaults cannot be set at the list view level; they are set at the form level. Please refer to the video for more details.


https://github.com/frappe/erpnext/assets/141945075/b67e397a-ac83-4cc6-9f20-d27357189b8e
