### ISSUE TITLE
POS SALE CANNT ADD ALLOW NEGATIVE ITEM

### ISSUE THREAD

**Issue by mmplerp** [frappe/erpnext#41274]
### Information about bug

IN POS SALES WE CANNOT ADD ALLOW NEGATIVE ITEM 
BUT IN FORM VIEW WE CAN ADD ITEM

### Module

selling

### Version

FRAPPE - v15.25
ERPNEXT - v15.21

### Installation method

FrappeCloud

**Comment by frewper** [comment]
Please can you also add a realistic use case as to when you would need to add a negative item ?

**Comment by Shirkit** [comment]
> Please can you also add a realistic use case as to when you would need to add a negative item ?

Smaller companies JIT fast producing items.
