### ISSUE TITLE
Difference account in stock entry (repack) NOT overriding Difference account in stock entry items

### ISSUE THREAD

**Issue by fderyckel** [frappe/erpnext#4127]
Hi There ,

It seems like the Difference account in stock entry (repack) is NOT overriding Difference account in stock entry items.  
The reason I am saying this is because if there are 2 different "difference accounts", the one from the stock entry doctype is not overriding the one in stock entry item.
Thanks
François

**Comment by jof2jc** [comment]
https://discuss.erpnext.com/t/difference-account-overriding-not-working-on-material-receipt/7222/3

**Comment by nabinhait** [comment]
By design it works in that way. System gives higher priority to the expense account mentioned in Item table. If it is not specified in any row in Item table, then system takes it from the Difference Account in parent form.
I can see that description of the "Difference Account" field is misleading, will update that.

**Comment by jof2jc** [comment]
I think there're always situations that user would still need flexibility
while doing transaction to post to different account.

If not, changing item expense account one by one is really wasting time.

Item expense account should only for default value and normal use..

**Comment by fderyckel** [comment]
@nabinhait  Well here is the issue then...  It is not possible to leave the difference account in the item table of a repack as blank.  By default, the "difference account" in item table is in our instance "Other Direct Production Costs - CFL" .  

Any chance at least we can define somewhere a default "difference account"?

I still think that the difference account field on the stock entry page should override the stock item table difference table. Right now, every stock entry of type repack is taken us lots of time just because on every row we have to redefine the stock difference account because we don't want to use the "Other Direct Production Costs - CFL" account.  

Sorry for reopening this....

**Comment by nabinhait** [comment]
@fderyckel If you remove "Default Expense Account" in Item master and system will pick the value from the "Stock Adjustment Account" field in Company.

**Comment by lxnow** [comment]
Pardon for bringing up an old thread, but think a bug: even if item master does not include a "Default Expense" account, the system does *not * pick up the stock adjustment account. In one case, the system is pulling the COGS account during stock entry, which is wrong. Still looking for a fix or workaround -- any advice?
