### ISSUE TITLE
item price based on FG item on subcontracting purchase order

### ISSUE THREAD

**Issue by sowndharya998** [frappe/erpnext#41273]
We send two types of finished goods for subcontracting, Even though these items are different, the services involved are identical. Currently, our ERP system assigns them the same price. 

For example, if we send both Mobile and Laptop items to the subcontractor for fitting panels and receive them back as finished goods, they are priced equally. However, we need different prices for each type of finished good. 

So, we require a feature in our system that allows us to specify different rates for each FG item.

**Comment by TurkerTunali** [comment]
We've created different service items for that. For instance: "Laptop Service", "Mobile Service" items.
