### ISSUE TITLE
 Error in Purchase Receipt

### ISSUE THREAD

**Issue by letirc** [frappe/erpnext#4129]
When I try to type the quantity of an item in a purchase receipt ERPNext throws me the following error.

Error:Accepted Quantity > Recd Quantity.

The users are using the POS view to made the purchase receipt.

How could I fix this error?

Note: I'm doing my purchase receipt directly without having made before the purchase order in my case I do not need it .

**Comment by rmehta** [comment]
POS view is removed in v7 for all transactions (the grid is now keyboard friendly!)
