### ISSUE TITLE
Error on creating new employee for a user, no permissions changed recently

### ISSUE THREAD

**Issue by innomalous** [frappe/erpnext#41290]
### Information about bug

Hello, one of the users on our account is getting the following error while creating a new Employee.

Not allowed for Employee: None
User nitin@innomalous.com does not have access to this document
Insufficient Permission for Employee (create)

![WhatsApp Image 2024-05-02 at 12 17 34 PM](https://github.com/frappe/erpnext/assets/42608563/cf0fc512-234c-421c-a93b-8653446ee81e)

No recent changes have been made to the user settings. The user was able to create new Employees before today.

The user has all permissions enabled. See screenshot below:
![image](https://github.com/frappe/erpnext/assets/42608563/ff3814ca-5acb-42a5-9009-b2fdd19d610f)

### Module

HR

### Version

"erpnext": "14.67.2",
"frappe": "14.72.0",
"hrms": "14.26.0",
"india_compliance": "14.26.3",
"payments": "0.0.1"

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
NA
```

**Comment by toofun666** [comment]
This issue is quite hot and urgent!

**Comment by rgug24** [comment]
I have also encountered this error.  However, I have different specs.  Any updates on this?

ERPNext: v15.23.0 (version-15)

Frappe Framework: v15.26.0 (version-15)

Frappe Health: v16.0.0-dev (develop)

Frappe HR: v16.0.0-dev (develop)

**Comment by Nihantra-Patel** [comment]
https://github.com/frappe/erpnext/issues/42210#issuecomment-2213021604
