### ISSUE TITLE
Template item should not be allowed in product bundle child table

### ISSUE THREAD

**Issue by NagariaHussain** [frappe/erpnext#41301]
### Information about bug

![CleanShot 2024-05-02 at 20 08 46@2x](https://github.com/frappe/erpnext/assets/34810212/31e0da95-c562-47e6-a00a-486153f711bb)

### Module

stock

### Version

15

### Installation method

FrappeCloud

**Comment by Nihantra-Patel** [comment]
In develop version it will be solved easily by using filter but in version 15 we have to add code like frm.set_query for it. Let's do PR for it if you say yes.
