### ISSUE TITLE
Purchase Order Item filter on Supplier not working

### ISSUE THREAD

**Issue by geraldleungontario** [frappe/erpnext#41306]
### Information about bug

In Purchase Order, after selecting a Supplier, when clicking in the Purchase Order Item table's Item Code cell, the list of items appear in a drop down, but the items listed are the same as if no supplier was selected earlier.

Another user has reported this in https://discuss.frappe.io/t/purchase-order-supplier-not-filtering-on-item-code/102758 and I have reproduced the issue.

### Module

stock, buying

### Version

ERPNext: v15.22.0
Frappe Framework: v15.25.0

### Installation method

docker

### Relevant log output / Stack trace / Full Error Message.

```shell
When clicking in the Item Code cell (no errors):
frappe_docker-frontend-1      | 172.19.0.1 - - [02/May/2024:18:56:08 +0000] "POST /api/method/frappe.desk.search.search_link HTTP/1.1" 200 468 "http://localhost:8080/app/purchase-order/new-purchase-order-pfulrarcnz" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
```

**Comment by kunhimohamed** [comment]
Did you try this https://docs.erpnext.com/docs/v13/user/manual/en/party_specific_item

**Comment by geraldleungontario** [comment]
> Did you try this https://docs.erpnext.com/docs/v13/user/manual/en/party_specific_item

This works in certain scenarios, but fails in others..

The closest matching behaviour appears to be this:
Party Type: Supplier
Party Name: <supplier name>
Restrict Items Based On: Item Group
Based On Value: <item group of the item under that supplier>

The scenario that causes this to fail is this:
Supplier, Item Group, Item
Sanitizing Company, Sanitizing Stuff, Hand Sanitizer
Cleaning Company, Sanitizing Stuff, 99% Alcohol

In this scenario, I would set up 2 Party Specific Item. When creating the Purchase Order, I would put Sanitizing Company as the Supplier, then the Purchase Order Item's Item Code cell would list both of these items from the 2 suppliers as possible choices because the filter is based on Item Group.

**Comment by kunhimohamed** [comment]
you can manage using an item group.

**Comment by Nihantra-Patel** [comment]
You can apply only one threshold at a time if you set up an item for one supplier, then you cannot set up an item group with the same supplier, and If you add, then the item will appear, which is common from both conditions.

https://github.com/frappe/erpnext/assets/141945075/a2681518-25f8-4677-818b-1bb53cfe0771
