### ISSUE TITLE
fix: SO ordered qty on PO item removal

### ISSUE THREAD

**Issue by tonspar** [frappe/erpnext#41319]
### Information about bug

Hello,
this is the same like this: https://github.com/frappe/erpnext/pull/38378.
It is working in v14 but it is not implemented in v15.

Order Qty in Sales Order Item is not updated if item is deleted in linked PO.

Is here any reason for no implementation, please?

Thank you.
Jiri Sir

### Module

buying

### Version

ERPNext: v15.20.3 (HEAD)

Frappe Framework: v15.23.0 (HEAD)

Frappe HR: v15.17.0 (HEAD)

Payments: v0.0.1 (HEAD)

### Installation method

FrappeCloud

**Comment by yrestom** [comment]
Can you explain more please 
And give an example

**Comment by tonspar** [comment]
Hello,
example:

1. Make the Sales Order (SO) with two items, each of 1qty and submitted it.
2. Create Purchase Order (PO) with these items via button "Create" -> "Purchase Order" in SO button section.
3. Submit this new PO.
4. Now we can check items in SO, the field "ordered_qty" = 1 for both items => OK.
5. Let's update the PO: remove first item and update it.
6. Now we should find in SO in first item "ordered_qty" = 0, but here is still 1 and it is an issue. It blocked you for new PO with first item via "Create" -> "Purchase Order". Here is this warning: _Purchase Order already created for all Sales Order items_ but it is not true.

Some pictures:
1. SO items:
![image](https://github.com/frappe/erpnext/assets/121026420/40c125a3-37bf-4720-8b8d-d4389bfb35e7)
2. PO items after update:
![image](https://github.com/frappe/erpnext/assets/121026420/1f4c6e54-a6ff-46c8-bdb1-2e96a2563faf)

In mentioned PR (https://github.com/frappe/erpnext/pull/38378) it is resolved for v14, but it is not backported to v15.

Thank you.

Jiri Sir

**Comment by Nihantra-Patel** [comment]
Hi @tonspar,

Issue has been fixed, the next updates will solve your issue.

**Comment by tonspar** [comment]
Hi @Nihantra-Patel,
perfect, thank you very much.
Jiri Sir
