### ISSUE TITLE
Lead Qualification Status does not display as in Form

### ISSUE THREAD

**Issue by nguyenth18** [frappe/erpnext#41322]
### Information about bug

Upon selecting any Lead Qualification Status in the Form, the information display in Lead List unchanged
![image](https://github.com/frappe/erpnext/assets/168114061/f1172a60-bc97-4794-8be4-c4c8881ea246)

### Module

CRM

### Version

ERPNext: v15.21.1 (version-15)

Frappe Framework: v15.24.1 (version-15)

### Installation method

None

**Comment by Nihantra-Patel** [comment]
Everything is working fine. No problems were encountered in the latest versions 14 and 15.



https://github.com/frappe/erpnext/assets/141945075/eff1f179-456a-44af-87ea-3ba5f0448a23
