### ISSUE TITLE
Missing the file of employee_dashboard.py

### ISSUE THREAD

**Issue by manalErpnext** [frappe/erpnext#41328]
### Information about bug

erpnext/setup/doctype/employee
this path is missing the employee_dashbaord.py file to custom the links (connections)

### Module

other

### Version

frappe   15.25.0 version-15
erpnext  15.22.1 version-15
hrms     15.20.2 version-15
my_app   0.0.1   develop
payments 0.0.1   develop

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
https://discuss.frappe.io/t/i-could-not-find-employee-dashboard-py-file/122460?u=manal_erpnext
```

**Comment by Nihantra-Patel** [comment]
Please check the post.

https://discuss.frappe.io/t/i-could-not-find-employee-dashboard-py-file/122460/2?u=ncp
