### ISSUE TITLE
Creating purchase order from Material Request adds an additional row in the items table

### ISSUE THREAD

**Issue by kiranshegde** [frappe/erpnext#41333]
**Steps to produce**

1. Create Material Request with one item.
2. Submit Material Request
3. Create a Purchase Order using Create button at the top
4. Now in the purchase order items table, it adds item two times, one with the original quantity as in the Material Request and another with quantity 1.
5. Even if you delete the second one, it still adds it as soon as you save or select a supplier

[screen-capture-purchase-order.webm](https://github.com/frappe/frappe/assets/64835183/1d1e9f74-0314-4d07-8f0a-1d148e9291c7)

**ERPNext version**
erpnext 15.15.0
frappe 15.16.1
grsforging 0.0.1
hrms 15.12.0
india_compliance 15.5.5
payments 0.0.1

**Comment by Nihantra-Patel** [comment]
Hi @kiranshegde,

Everything is working fine. No problems were encountered in the latest version 15.


https://github.com/frappe/erpnext/assets/141945075/5adc6ba5-40c6-41b6-8012-b2673f2e7f80

If any custom code applied then comment out it and reload and check it.
