### ISSUE TITLE
Return invoice wrong total

### ISSUE THREAD

**Issue by perotom** [frappe/erpnext#41343]
### Information about bug

I created a normal invoice:
![Bild (6)](https://github.com/frappe/erpnext/assets/3322872/8adb4b33-b61e-4eaa-a14b-c308975b4cb9)

And then tried to create a return invoice but the total amount is different:
![Bild (7)](https://github.com/frappe/erpnext/assets/3322872/986b0663-fccc-4067-8b85-c7ce572ff407)

Looks like the difference comes from this one green marked item. Maybe rounding error?

### Module

selling

### Version

ERPNext: v15.20.3
Frappe Framework: v15.22.0

### Installation method

easy-install

**Comment by Nihantra-Patel** [comment]
Everything is working fine. No problems were encountered in the latest version 15.


https://github.com/frappe/erpnext/assets/141945075/d7208f41-27a9-4639-a3d9-7a91215b1ad6

**Comment by perotom** [comment]
If you use quantity 1, it works but if you use for example quantity 10 with price 82.50€ and 15% discount, you will get a wrong total. This issue is still there.

**Comment by Nihantra-Patel** [comment]
Tested, worked properly.


https://github.com/frappe/erpnext/assets/141945075/3ad2a136-b19e-461d-9cee-0f377c293298

**Comment by perotom** [comment]
Please use the price values I used. It is a rounding issue. The following is happening:
Item A: `82,50€ - 15% = 70,125€`
On the sales invoice, it is rounded up:
`70,125 = 70,13€ * 10 = 701,30€`
and on the return invoice it is rounded down:
`70,125 = 70,12€ * 10 = 701,20€`
resulting in a wrong total value. Seems like the rounding mode is not consistent across sales and return invoices.

**Comment by Nihantra-Patel** [comment]
Please check with latest version and provide the video.

**Comment by perotom** [comment]
I changed the rounding mode from bankers to commercial and now it works. Thank you.
