### ISSUE TITLE
Adding User permission do ingore Role permission

### ISSUE THREAD

**Issue by yahyaoudra** [frappe/erpnext#41363]
### Information about bug

I added new user with a role of project manager But I assigned only a specific projects to manage, but I wanted that user to stay have th eability to create new projects.
now it's says you don't have permission as long as I only give him/her permission to a specific projects so he/she can't create new project 

### Module

projects

### Version

ERPNext: v15.22.2 (version-15)

Frappe Framework: v15.25.0 (version-15)

Helpdesk: v0.10.0 (main)

Frappe HR: v16.0.0-dev (develop)

Frappe LMS: v1.0.0 (main)

Raven: v1.5.5 (develop)

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
I think, this isn't a bug.

If you have applied user permissions to the project to the user. So it means that the user will be able to view or edit only that project. But now you say that the user has to create a project. How can it be done, if you think about it practically, it is not possible. If you have given the user permission, he cannot create the project.
