### ISSUE TITLE
General Ledger wrong date filter

### ISSUE THREAD

**Issue by NourSeleem** [frappe/erpnext#41366]
### Information about bug

1. Open general ledger report, within account filter choose an account its currency differs from the company currency
2. Within date filter add long range of date filtration ( a year for example from 1-1-2023 till 31-12-2023) 
3. Within currency filter choose different currency other than account currency 
4. view the report 
The issue within displayed results within amount (debit or credit) as it consider the exchange rate as per the "**date to**" filtration (in this case 31-12-2023) regardless the transaction date (it could be within January which has a very different exchange rate than in December) 
A fix should be applied to calculate the exchange rate based on either the transaction exchange rate or the first nearest date within currency exchange list , not based on the "**date to**" filter

### Module

accounts

### Version

V15.23.0 - V15.20.5

### Installation method

None

**Comment by Nihantra-Patel** [comment]
Everything is working fine. No problems were encountered in the latest version 15.


https://github.com/frappe/erpnext/assets/141945075/484bbc51-b182-48f4-81f0-d4c1ade9840b
