### ISSUE TITLE
Overlapping elements when column content spans to another page during Quotation PDF Generation 

### ISSUE THREAD

**Issue by gabtzi** [frappe/erpnext#4139]
Here's an example of the result caused by this bug at list item 9 attached in the image

![quotation bug](https://cloud.githubusercontent.com/assets/11225818/10382186/08528668-6e2a-11e5-9c7c-4e0b6885799d.JPG)

I've also opened a discussion thread regarding this issue 

<a>https://discuss.erpnext.com/t/blank-page-and-item-list-problem-in-pdf-after-customizing-quotation-item-frields/7782</a>

and the current fix I implemented is adding

`table tr {
        page-break-inside: avoid !important;
}`

near line 93 at

`"apps/frappe/frappe/templates/styles/standard.css"`

**Comment by gabtzi** [comment]
I'm updating my question and closing the issue. After a lot of digging up the problem comes up when it's a local server and you haven't used your hosts file in the server to set up the pseudo-domain to be accessible from the server.

So for future reference to others who might encounter this issue I solved it by
1. adding to the hosts file the pseudo-domain so that it is accessible in the server
2. and also use the command 
    `bench set-url-root {sitename} http://{hostname_that_resolves_the_site}`

**Comment by anandpdoshi** [comment]
Strage.

Can you confirm if the Item description’s html does not have some problem that is ruining the css of further elements?

**Comment by gabtzi** [comment]
Hi, yes the html was very clean and properly formatted and the problem occured even with a long plain text without any html like 

Text text text  text text
 text text text text text text ....

 repeated 15 times or so to span over the next page. 

After setting properly the pseudo domain with the commands above though it started working correctly for no apparent reason. I do think that it should work without setting up a properly accessible domain though so I would be glad to assist in any way

**Comment by anandpdoshi** [comment]
If you don’t setup the domain, the server does not load the required CSS files. So you have to setup the domain.

**Comment by gabtzi** [comment]
I see. 

Out of curiosity, the CSS File 
`apps/frappe/frappe/templates/styles/standard.css` 
changed the pdf result when I added an extra line so it's safe to assume that this specific file was loaded without setting up the domain. 

If certain files can be loaded without correctly setting up the domain shouldn't the other ones be able to load as well?
