### ISSUE TITLE
Purchase Order Item doesn't trigger currency exchange

### ISSUE THREAD

**Issue by geraldleungontario** [frappe/erpnext#41399]
### Information about bug

In Purchase Order, when entering an item with a foreign currency into the Purchase Order Item table, the Rate is showing 0.

I have the following configured:
Price List: Currency = USD, Buying enabled, named as "Standard Buying US"
Item Price (for the item tested): Price List = Standard Buying US, Buying enabled, Currency = USD, Rate = 120, Valid From = 05-02-2024
Global Defaults: Default Currency = CAD, Country = Canada

I tried manually setting a Currency Exchange for today (05-09-2024) with these:
From Currency = USD, To Currency = CAD Exchange Rate = 1.37
The Rate is still shows 0 in my test.

I tried configuring Currency Exchange Settings with these settings:
Service Provider = exchangerate.host, Use HTTP Protocol
I was able to save this and it counted as 1 API call in exchangerate.host. I retested my scenario and Rate still shows 0. I tried a few times and exchangerate.host didn't show any API calls.

### Module

buying

### Version

ERPNext: v15.22.0
Frappe Framework: v15.25.0

### Installation method

docker

**Comment by ruthra-kumar** [comment]
This is not replicable. Does this happen on all cases or only a specific scenarios?

**Comment by ruthra-kumar** [comment]
System does pull the item price, following the same setup you've mentioned.
<img width="1440" alt="Screenshot 2024-06-04 at 2 13 23 PM" src="https://github.com/frappe/erpnext/assets/3272205/018da556-390b-4c09-a11c-22612d9ae30c">
<img width="1440" alt="Screenshot 2024-06-04 at 2 10 50 PM" src="https://github.com/frappe/erpnext/assets/3272205/b973836d-1972-4f28-bc30-96f425c2e95a">

**Comment by ruthra-kumar** [comment]
Closing this for now. You can re-open if it is replicable on a clean ERPNext instance.
