### ISSUE TITLE
Wrong Delete Batch In Sales Return

### ISSUE THREAD

**Issue by xhijack** [frappe/erpnext#41407]
### Information about bug

 have a Delivery Note with batch items. Then, I create a Sales Return against the delivery note. After creating the Sales Return, I click "pick serial and batch" and try to select some batches to delete. However, when I delete them, the results are incorrect

Uploading Screen Recording 2024-05-10 at 21.05.46.mov…

### Module

stock

### Version

ERPNext: v15.23.0 (version-15)
Frappe Framework: v15.26.0 (version-15)

### Installation method

manual install

**Comment by xhijack** [comment]
![sales_return](https://github.com/frappe/erpnext/assets/1784964/cbaaeb0a-230e-4b5d-9f74-322c22ccb238)

**Comment by rohitwaghchaure** [comment]
@xhijack We have fixed the issue and tomorrow we'll release the fix
