### ISSUE TITLE
Purchase Invoice Return for Serial No : V15

### ISSUE THREAD

**Issue by thida-bcn** [frappe/erpnext#41403]
### Information about bug

Let's say when we buy items we got 
24-100039 to 24-100050
when we made purchase return
we want to return only 1 item of serial 24-100043 which is not fifo/lifo/expiry
it was very complicated to make return for desired serial no
is this possible to add one more option fifo/lifo/expiry/ manual
when user choose manual, allow user to choose desired serial no which they want to return
please check details at video
thanks

### Module

stock

### Version

Frappe:15.26.0
ERPNext: 15.23.0

### Installation method

manual install

**Comment by thida-bcn** [comment]
https://github.com/frappe/erpnext/assets/62122640/9b604e8b-66c7-4ff9-8fa9-606756d98d5f

**Comment by rohitwaghchaure** [comment]
@thida-bcn Enable "Use Serial / Batch Fields" in the stock settings and check.
<img width="1280" alt="Screenshot 2024-05-10 at 1 32 54 PM" src="https://github.com/frappe/erpnext/assets/8780500/6e78ce57-2c67-43c4-a040-b419e45a9a3d">

**Comment by thida-bcn** [comment]
> @thida-bcn Enable "Use Serial / Batch Fields" in the stock settings and check. <img alt="Screenshot 2024-05-10 at 1 32 54 PM" width="1280" src="https://private-user-images.githubusercontent.com/8780500/329506883-6e78ce57-2c67-43c4-a040-b419e45a9a3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMzA4MTMsIm5iZiI6MTcxNTMzMDUxMywicGF0aCI6Ii84NzgwNTAwLzMyOTUwNjg4My02ZTc4Y2U1Ny0yYzY3LTQzYzQtYTA0MC1iNDE5ZTQ1YTlhM2QucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTBUMDg0MTUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTAyOTk1M2NjMGFmYTg2MDJhMzhkNzBkM2Q1ZWUwZjExZmM5NDhiNmFiMTgxY2U4Yjg0MzMxZDgzZWQyZmRlYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.j1LvqgOf5EN9CXNDeVwBzfjWY3bva81ouFP3L9cc3aw">

thank you
got it now
