### ISSUE TITLE
Exchange Rate Issue when creating PO

### ISSUE THREAD

**Issue by chanyork** [frappe/erpnext#41423]
### Information about bug

When creating a PO from SO.  The PO did not seems to get a correct exchange rate.  Base currency is HKD and Purchasing currency is CNY and Purchasing Price List is in CNY.  When loaded PO form it always load exchange rates of 1 CNY = HKD.

![image](https://github.com/frappe/erpnext/assets/28833849/f2204a5f-68e7-415b-b05a-b8d57eaef816)

### Module

buying

### Version

ERPNext: v15.23.0 (HEAD)
Frappe Framework: v15.26.0 (HEAD)

### Installation method

FrappeCloud

**Comment by ruthra-kumar** [comment]
Could you share steps to replicate this?

**Comment by chanyork** [comment]
Seems to be fix in the latest update already.
