### ISSUE TITLE
Notifications are not being sent upon Lead Task assignment

### ISSUE THREAD

**Issue by joshuarestivo** [frappe/erpnext#41439]
### Information about bug

When a new Activity Task is created within a Lead, it is failing to trigger an assignment email notification to the assigned user. This causes a swivel-chair process to be required to notify users of new task assignments and also doesn't align with Task handling elsewhere in the system.

To Reproduce:
1. In CRM -> Lead -> [Lead] -> Activities, select New Task
2. Select a date, Assign a User, and add a note
3. Select Create
4. Using the email account of the assigned user, wait for an email notification indicating that the task has been assigned. You will be waiting for a very long time.

Expected behavior:
Assigned user receives 'new task' notification.

### Module

CRM

### Version

Frappe: v14.66.2
ERPNext: v14.63.3

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
> Expected behavior:
> Assigned user receives 'new task' notification.

You can set up notifications for this. When a task, is assigned, the system creates a todo, and when the todo is created, it triggers an email to be sent to the assigned user.
