### ISSUE TITLE
System should not allow to modify (Add or Remove) files from doctypes after they were submitted 

### ISSUE THREAD

**Issue by asmithkumarreddy** [frappe/erpnext#41454]
Hi Team,

Currently ERP system is allowing to modify (Add or Remove) files (attachments) from Expense claim doctype after they were submitted. This is causing issue for finance team to track.  System should restrict the modification of files for audit purpose as well. 
 
The same logic should also be applicable to all other Doctypes. Once the document is in SUBMITTED status, users should not be allowed to modify the attachments.
 
Please prioritize this functionality urgently and implement the same in your upcoming releases.

Thanks
Asmith
![Expense](https://github.com/frappe/erpnext/assets/46068189/32e6ac80-3baa-4638-8916-2877c7a54136)

**Comment by Nihantra-Patel** [comment]
It's designed according to the user and client perspective. Actually, it's not possible because many users/clients need to make attachments after submission, so this feature request is not valid.

But I will share a suggestion: you can easily manage it using the client script. So please check it.

```js
frappe.ui.form.on('Expense Claim', {
	refresh: function(frm) {
	    if (frm.doc.docstatus == 1) {
	        $('.form-attachments').css({'pointer-events': 'none'});
	    }
	}
});
```

If you want to do it for all doctype then you can set it in custom app. please check the reference:

https://discuss.frappe.io/t/add-custom-script-to-all-doctypes/41773/2?u=ncp

**Comment by purnabunty** [comment]
Hi @Nihantra-Patelm,

Now we are able to restrict the user.
Thanks for helping.

**Comment by Nihantra-Patel** [comment]
> ```
> frappe.ui.form.on('Expense Claim', {
> 	refresh: function(frm) {
> 	    if (frm.doc.docstatus == 1) {
> 	        $('.form-attachments').css({'pointer-events': 'none'});
> 	    }
> 	}
> });
> ```

Now I have updated the script as you can't access the attachment in the above script.
If you want to access the attachment and don't want to delete the user after submit then please apply it.

**For Version 15:**

```js
frappe.ui.form.on('Expense Claim', {
	refresh: function(frm) {
	    if (frm.doc.docstatus == 1) {
	        $('button.add-attachment-btn.btn.btn-link.icon-btn').hide();
	        $('span.remove-btn.cursor-pointer').hide();
	    }
	}
});
```

**For Version 14:**

```js
frappe.ui.form.on('Expense Claim', {
	refresh: function(frm) {
	    if (frm.doc.docstatus == 1) {
	        $('li.attachments-actions').hide();
	        $('span.remove-btn.cursor-pointer').hide();
	    }
	}
});
```

Then reload <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>R</kbd> and check it.
