### ISSUE TITLE
Cutting of a title even though screen wide enough?

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#4145]
@anandpdoshi is there a better way than cutting this of arbitrarily after some length when screens are wide enough to show the full width?

<img width="1226" alt="bildschirmfoto 2015-10-09 um 23 28 41" src="https://cloud.githubusercontent.com/assets/9136094/10401608/9d81b188-6edd-11e5-9538-05026e330b9b.png">

**Comment by anandpdoshi** [comment]
It is possible. We just didn't have the mindspace at the time to delve further into it.

**Comment by dottenbr** [comment]
Also here in the overview its cut off unnecessarily 
<img width="1230" alt="bildschirmfoto 2015-10-10 um 00 13 53" src="https://cloud.githubusercontent.com/assets/9136094/10402584/dea34b12-6ee3-11e5-8eb0-35722e5b43d4.png">

**Comment by anandpdoshi** [comment]
Dominik. I will take this up when I work on the mobile views in the coming days. I don’t like the truncation either :), but I suspect this will take a lot of trial and error to get this right for different number of possible columns.

**Comment by m-delvalle** [comment]
+1
