### ISSUE TITLE
Unintended GST Expense Entry Appearing in Financial Reports.

### ISSUE THREAD

**Issue by shubhampreciholesports** [frappe/erpnext#41460]
### Information about bug

I have encountered an issue where an extra GST expense entry is displayed in our financial reports without any corresponding transaction. This entry appears under the 'GST Expense - PSPL' account, but it was not expected nor used in any documented transactions.

Expected Behavior:
The 'GST Expense - PSPL' should only display entries that are explicitly recorded in transactions. There should be no extra entries unless they are associated with an actual transaction processed through the system.

Actual Behavior:
An extra entry for GST expenses is appearing in the report even though there has been no transaction to justify this entry.

![Screenshot from 2024-05-14 17-16-50](https://github.com/frappe/erpnext/assets/154511820/4df9651c-d11e-41f2-960d-f9312970bba0)

### Module

accounts

### Version

ERPnext Version- 15

### Installation method

FrappeCloud

**Comment by Nihantra-Patel** [comment]
Open the purchase invoice transaction and review it. If you encounter any issues, please share the image of the complete purchase invoice or a video. This will help identify any errors in your transaction.

**Comment by vorasmit** [comment]
@shubhampreciholesports,

Following docs could be useful in how this came up.
https://docs.indiacompliance.app/docs/configuration/purchase_transaction#itc-ineligibility
