### ISSUE TITLE
"Get stops from" in delivery trip does not work as expected

### ISSUE THREAD

**Issue by vcavel** [frappe/erpnext#41468]
### Information about bug

When getting delivery notes from the "Get stops from" button in a delivery trip, all the existing stops are deleted and only the new stops are remaining.

The expected behavior should be that the new stops are added to the other ones.

That's how it worked in v14

Cheers

### Module

stock

### Version

ERPNext: v15.22.0 (version-15)
Frappe Framework: v15.25.0 (version-15)

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
Hi @vcavel,

Issue has been fixed, please check it: https://github.com/frappe/erpnext/pull/41431

Upcoming update will resolved your issue.
