### ISSUE TITLE
Item wise sales register wont show delivery note linked with sales order

### ISSUE THREAD

**Issue by maveezmh** [frappe/erpnext#41477]
### Information about bug

Created a sales order with delivery note and invoice 
in sales register and 
itemwise sales register the system is not able to show delivery note number

![image](https://github.com/frappe/erpnext/assets/112148467/32aef0f8-a403-42d4-b7b3-fb9d27c6fec4)

### Module

accounts, selling

### Version

ERPNext V14 and V15

### Installation method

FrappeCloud

**Comment by Nihantra-Patel** [comment]
Kindly upgrade to version 15, then refresh and check again because lots of bugs fixed in the new version.

Everything is working fine. No problems were encountered in the latest version 15.


https://github.com/frappe/erpnext/assets/141945075/55ce0a9c-be03-4b82-a669-bbfbba6ba64c
