### ISSUE TITLE
The description of my countrie's currency is wrong

### ISSUE THREAD

**Issue by emiliolazo** [frappe/erpnext#4147]
Hello, 

The amounts in words form PEN currency is wrong. It sais "Ciento cincuentas solamente" instead of "Ciento cincuenta soles"
Regards,

Emilio

**Comment by anandpdoshi** [comment]
@emiliolazo What is the language that you are using?

**Comment by anandpdoshi** [comment]
And, can you also give the exact number so that I can reproduce the error?

**Comment by fderyckel** [comment]
Also on a similar note, the currency for Zambia is wrong.  It used to be ZMK, now it is ZMW.  Thanks ;-)
https://en.wikipedia.org/wiki/Zambian_kwacha
http://www.boz.zm

**Comment by emiliolazo** [comment]
I am using spanish. The error occurs with all numbers. For example if you
introduce 1150 PEN the number in text it says "Mil ciento cincuenta
solamente" instead of "Mil ciento cincuenta soles".

**Comment by KanchanChauhan** [comment]
@emiliolazo Can you please edit and verify your translation via [https://translate.erpnext.com/](https://translate.erpnext.com/). 

@fderyckel Thanks for reporting this. It will be fixed via https://github.com/frappe/frappe/pull/2190
