### ISSUE TITLE
Stuck in Item valuation reposting in progress

### ISSUE THREAD

**Issue by norel-misr** [frappe/erpnext#41493]
### Information about bug

I have created a landed cost voucher for an item based on its purchase reciept.  Now whenever I goto stock ledger report a message saying "Item valuation reposting in progress. Report might show incorrect item valuation." is displayed.  This message has been showing for sometime so I think the system is stuck in this re-evaluation.
Any solution ?

### Module

stock

### Version

v15.23.2 (HEAD)

### Installation method

FrappeCloud

**Comment by rohitwaghchaure** [comment]
"Item valuation reposting in progress, Report might show incorrect item valuation"
This message shows when Repost Item Valuation records are is Queued state. Please check how many Repost Item Valuation records are is Queued state.

**Comment by norel-misr** [comment]
how do I check this ?

**Comment by rohitwaghchaure** [comment]
Search Repost Item Valuation list in the global search, after that you will see the list of Repost Item Valuation records. In the list view of Repost Item Valuation, set the status filter as Queued and check
<img width="708" alt="image" src="https://github.com/frappe/erpnext/assets/8780500/0e5209d3-8e6c-44b8-b615-b52b2ad1a084">
