### ISSUE TITLE
POS Closing Entry Issue

### ISSUE THREAD

**Issue by nrhdasa** [frappe/erpnext#41514]
### Information about bug

POS Closing procedure collects all the POS made in between the POS Opening and Closing Time and consolidates them in a Sales Invoice.

But the consolidation misses the POS Invoice which was created just at the time of Closing.

Example: 

Closing Entry
<img width="331" alt="image" src="https://github.com/frappe/erpnext/assets/40687270/47f7c3b9-7dad-4880-b92a-1e1f92546c51">

Last POS Invoice.
<img width="1258" alt="image" src="https://github.com/frappe/erpnext/assets/40687270/5999ee62-63f4-47f8-acc1-c7cc60cf5624">

POS Closed at : 11-05-2024 22:48
Last POS Created at: 11-05-2024 22:48

And this POS invoice remains unconsolidated forever.

### Module

selling

### Version

ERPNext: v15.20.5 (version-15)

Frappe Framework: v15.23.0 (version-15)

### Installation method

None

**Comment by ruthra-kumar** [comment]
If you looks at the query that pulls POS Invoices, posting time is not used for filtering. POS Invoices that don't have `consolidated_invoice` set is pulled.
https://github.com/frappe/erpnext/blob/a8fc32dc3256963ef72fbf1681e53b9a357dce23/erpnext/accounts/doctype/pos_closing_entry/pos_closing_entry.py#L155-L166

**Comment by ruthra-kumar** [comment]
This is not replicable. Closing this.
You can reopen if issue recurs.
