### ISSUE TITLE
`search_fields` and `title_field` in Address customize form has no effect

### ISSUE THREAD

**Issue by kehwar** [frappe/erpnext#41532]
### Information about bug

Setting `search_fields` and `title_field` in `Address` customize form has no effect on linked fields

Docs: https://frappeframework.com/docs/user/en/basics/doctypes/form_&_view_settings#title-field

## Steps to reproduce the issue

1. Set `search_fields` and `title_field` in `Address` customize form
2. Create a new `Quotation`, choose a party
3. Search addresses for customer or company, etc.
4. The title field will always be `city`, only when saved and refreshed will the `title_field` be shown
5. On the popup list, the title and description will also not show the `title_field` or `search_fields` as set on customize form

### Module

selling

### Version

ERPNext: v15.24.0 (HEAD)
Frappe Framework: v15.27.0 (HEAD)

### Installation method

FrappeCloud

**Comment by nabinhait** [comment]
I have tested in version 15, it's working as expected. The title and search_field value is showing while searching.

**Comment by kehwar** [comment]
This issue was specific to linked address fields, because a custom query is used

This issue is still present, but should be fixed for the next release

See: https://github.com/frappe/frappe/pull/26611 https://github.com/frappe/frappe/pull/26570
