### ISSUE TITLE
Error Using opening invoice creation tool

### ISSUE THREAD

**Issue by norel-misr** [frappe/erpnext#41541]
### Information about bug

When I try to create a new invoice in the opening invoice creation tool I get the an error saying: "Could not find Row #1: UOM: Nos".
<img width="1437" alt="Screenshot 2024-05-19 at 12 32 09 PM" src="https://github.com/frappe/erpnext/assets/80753288/3b5edb52-da95-4e62-9967-487750920d08">

### Module

accounts

### Version

ERPNext: v15.24.0 (HEAD)
Frappe Framework: v15.27.0 (HEAD)

### Installation method

FrappeCloud

**Comment by Nihantra-Patel** [comment]
I tested with the same (latest) version, so everything is working fine. No problems were encountered.

Please check it.


https://github.com/frappe/erpnext/assets/141945075/0af93533-cd97-427f-8eb9-dc42ce875cf6

If you rename, change, or delete "Nos," you will face issues. Otherwise, you won't.
