### ISSUE TITLE
Unloading Page

### ISSUE THREAD

**Issue by ardhirahmatfauzi** [frappe/erpnext#41560]
### Information about bug

Cant load page 
![image](https://github.com/frappe/erpnext/assets/170392391/4783cd83-313a-40bc-af05-cd77d1ee9e54)

### Module

selling

### Version

Hase Utama Indonesia

### Installation method

None

**Comment by Nihantra-Patel** [comment]
**We no longer provide support for version 13 or older.**

Kindly upgrade to version 14 or 15.

Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!
