### ISSUE TITLE
Error: Value missing for None: parenttypeError: Value missing for None: parent

### ISSUE THREAD

**Issue by amansonimtr** [frappe/erpnext#41565]
### Information about bug

when i create new custom report its give such types of error

### Module

accounts

### Version

ERPNext: v15.22.0 (version-15)

Frappe Framework: v15.25.0 (version-15)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Error: Value missing for None: parenttype
Error: Value missing for None: parent
```

**Comment by Nihantra-Patel** [comment]
We tested both Report Builder and Custom Report. so everything is working fine. No problems were encountered in the latest version 15.


https://github.com/frappe/erpnext/assets/141945075/756e4385-5099-4649-a670-6393f97fd45d

**Comment by amansonimtr** [comment]
Tq Bhaiya all done
