### ISSUE TITLE
Report Deferred Revenue and Expense does not filter by Company

### ISSUE THREAD

**Issue by konradbr** [frappe/erpnext#41566]
### Information about bug

When trying to display Deferred Revenue and Expense reports for two different companies (both belonging to same parent company), applying the Company filter seems to have no effect — the data remains the same independent of which company (either child or parent company) is selected in the filter:

<img width="898" alt="Screenshot 2024-05-21 at 09 04 32" src="https://github.com/frappe/erpnext/assets/28401247/25ef8f31-1b85-4a46-b574-3f69f4dc0ab5">

result for company 1:

<img width="375" alt="Screenshot 2024-05-21 at 09 02 24" src="https://github.com/frappe/erpnext/assets/28401247/7c362e58-741b-43df-bd00-75d68979e726">

result for company 2:

<img width="386" alt="Screenshot 2024-05-21 at 09 03 23" src="https://github.com/frappe/erpnext/assets/28401247/2cf4e6bc-4a5a-4f5e-aea1-28a7f64b8274">

### Module

accounts

### Version

bench: 5.16.2
erpnext 15.24.1
frappe 15.27.0
nextcloud_integration 0.0.1
payments 0.0.1

### Installation method

manual install

**Comment by deepeshgarg007** [comment]
@konradbr This is how all the reports work in ERPNext, company filters don't honor parent/child company relationships. This is intentional.

**Comment by konradbr** [comment]
@deepeshgarg007 I am almost certain this is a bug:

You're talking about honoring parent/child company relationships, whereas I mean that the filter does not work *at all*, *for this specific report*. Meaning that in other reports work fine, whereas in this report, the filter has no effect whatsoever.

Could you please kindly re-open this thread? I can provide you with more information, or even dig into the code to try and help in finding a solution.

Many thanks for your response,
All the best,

K.
