### ISSUE TITLE
Submitting a sales invoice (with stock update checked) for a reserved order is not marking the reserved entry delivered

### ISSUE THREAD

**Issue by ayush22051989** [frappe/erpnext#41577]
### Information about bug
Submitting a sales invoice (with stock update checked) for a reserved order is not marking the reserved entry delivered

### Module

stock

### Version

V15

### Installation method

None

**Comment by ruthra-kumar** [comment]
Does it happen for every Sales Order or a select few? Would it be possible to share some steps to replicate?

**Comment by ruthra-kumar** [comment]
This is not replicable. With the same scenarios, Sales Order's status is being updated to completed.

<img width="1440" alt="Screenshot 2024-06-04 at 2 44 25 PM" src="https://github.com/frappe/erpnext/assets/3272205/ed3bc552-0e4c-4a55-bb8a-9a17c65638f3">

<img width="1440" alt="Screenshot 2024-06-04 at 2 44 43 PM" src="https://github.com/frappe/erpnext/assets/3272205/18ffe91d-776b-45da-b8cc-5d97138312a7">
