### ISSUE TITLE
Cancelled Purchase Invoices show up in Payment Reconciliation Tool / Payment Ledger Entries not DeLinked

### ISSUE THREAD

**Issue by konradbr** [frappe/erpnext#41581]
### Information about bug

After cancelling several invoices and amending each, then trying to reconcile previously recorded payments, both the amended _and the cancelled_ invoices show up in the Payment Reconciliation tool.

Further investigation led to discovery that Payment Ledger Entries associated with the cancelled entries were not _DeLinked_. _DeLinking_ manually failed due to permission restrictions (e.g. `User ####@#### does not have access to this document: Payment Ledger Entry - f1e001f1fd`).

### Module

accounts

### Version

```
erpnext 15.24.1
frappe 15.27.0
nextcloud_integration 0.0.1
payments 0.0.1
```

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
(none)
```

**Comment by hpotabatti** [comment]
Hey @konradbr 

I would like to replicate and investigate this issue.
Could you please share the steps to replicate this locally along with your current system's Stock and Accounts Settings configurations?

**Comment by konradbr** [comment]
Hi Harshwardhan,Thanks for your message! I will get back to you at the earliest opportunity with the information you requested.All the ***@***.***: + 41 79 800 85 26On 23 May 2024, at 11:17, Harshwardhan Potabatti ***@***.***> wrote:﻿
Hey @konradbr
I would like to replicate and investigate this issue.
Could you please share the steps to replicate this locally along with your current system's Stock and Accounts Settings configurations?

**Comment by konradbr** [comment]
Hi @hpotabatti

Thank you for your reply, I will provide you with more details at the earliest opportunity!

**Comment by ruthra-kumar** [comment]
This is not replicable. If the issue persits on a clean ERPNext instance, do share screenshots/videos of issue.

**Comment by konradbr** [comment]
@ruthra-kumar I wasn't able to controllably reproduce this, but it did indeed happen again "on its own" for the one or other invoice. The workaround I found was to enable deletion of GL entries upon deletion of invoices, and deleting and re-posting from scratch the problematic invoices.

**Comment by konradbr** [comment]
@ruthra-kumar I am facing this issue again. This happens specifically when I amend several (different) invoices in a row. It might have something to do with amending, then cancelling, then amending again the same invoice.

Update: I have now noticed this happens also on original, unmodified invoices.

<img width="906" alt="Screenshot 2024-06-30 at 22 37 05" src="https://github.com/frappe/erpnext/assets/28401247/d901754e-4519-48fe-b897-b2c5e60273b3">

**Comment by ruthra-kumar** [comment]
can you post screenshot of payment ledger entries of those purchase invoices?

**Comment by konradbr** [comment]
@ruthra-kumar I had to delete these to be able to progress with work, but will post more detail next time this happens. Note that there is something similar happening with some cancelled *Process Deferred Expense* items, whereby these still show up in spite of being cancelled.
