### ISSUE TITLE
Supplier Invoice Date in Payment Entry-> Payment Reference 

### ISSUE THREAD

**Issue by reeta-greycube** [frappe/erpnext#41582]
Hi,

We would like to suggest an enhancement to the payment entry process. When adjusting purchase invoices, it would be highly beneficial to include a field for the Supplier Invoice Date from the Purchase Invoice.

Having this field visible will allow us to see the corresponding Supplier Invoice Date, making it easier to accurately adjust our entries according to the Purchase Invoice->Supplier Invoice Date

![image](https://github.com/frappe/erpnext/assets/110815754/cd262c74-2dd2-4768-9526-7580114678fa)
![image](https://github.com/frappe/erpnext/assets/110815754/9ef85aae-afd8-4496-b0f8-924f7826ad87)

**Comment by Nihantra-Patel** [comment]
Please read the comment: https://github.com/frappe/erpnext/pull/41587#issuecomment-2136518577
