### ISSUE TITLE
Stock Balance is incorrect for Batch

### ISSUE THREAD

**Issue by abhioncode** [frappe/erpnext#41580]
### Information about bug

I have mentioned this before, but got my message closed and surprised more people are not facing similar issue. Thanks to a post by  @Nihantra-Patel i dug deeper and still found the issue to be a bug in the system and not an erorr of data entry.

I have a product that was purchased last year
Then selling that product this year. But when generating the Batch-Wise Balance History its very clear that there is a bug in the way the Stock Ledger is calculating the stock value. 

If I take a long to and from date, which encompases the original purchase, the system calculates the balance correctly as you can see here:
![image](https://github.com/frappe/erpnext/assets/85059961/9c99df84-ee4b-4292-946c-8f99a852fc9b)
shows a balance of 28,250 units.

If I run same report in Stock Ledger, 
![image](https://github.com/frappe/erpnext/assets/85059961/bcdbb019-582e-4a62-b284-ff2a20f8f25a)
witha  long date range of more than a year, I get the same stock balance of 28,250 units. great...

But if I run the same report in Stock Ledger, chaning the date range to this year ...
![image](https://github.com/frappe/erpnext/assets/85059961/1799f8ac-3f1b-4890-9f41-be2247d07bce)
You can clearly see that the Opening Balance is 172,800 units, and all subsquent movements done has caused the stock level balance to go into negative.

This is a bug.

### Module

stock

### Version

Frappe: 15.21
ERPNext: 15.24

Using FrappeCloud

### Installation method

FrappeCloud

**Comment by Admin661** [comment]
Hello @ablashek is the issue resolved yet? You'll have to rectify with the ledger loptimal weblink and try it again.

**Comment by rohitwaghchaure** [comment]
@ablashek what is the stock transaction document types for negative entries? have you hosted your site on FC? if yes please share the site name

**Comment by rohitwaghchaure** [comment]
@ablashek we have fixed the issue related to opening stock for the stock ledger report and tomorrow we'll release the fix 
Fixed https://github.com/frappe/erpnext/pull/41758

**Comment by abhioncode** [comment]
hi @rohitwaghchaure , yes issue has been resolved. Thanks!
