### ISSUE TITLE
Provide docker or vagrant for ease of setup

### ISSUE THREAD

**Issue by cdvv7788** [frappe/erpnext#4159]
I wanted to do a manual installation of the project, but that proved to be painful and somehow obscured. The virtual machine option is good, but it may take a while to download. Vagrant can recreate the instance on the fly without requiring an external download, just a couple more files on the root.
Another option would be docker, which would require something similar. Note that both options allow easy deployment of instances both for users and developers.

**Comment by yashodhank** [comment]
Unofficial Docker implemented by some other community member: https://github.com/pfy/erpnext

**Comment by rmehta** [comment]
https://github.com/frappe/erpnext_vagrant
