### ISSUE TITLE
Payment Entry Server Error

### ISSUE THREAD

**Issue by convergenix** [frappe/erpnext#41608]
### Information about bug

![image](https://github.com/frappe/erpnext/assets/74385558/3f10ddb1-c8e4-412c-98c0-e52023634968)

### Module

accounts

### Version

Frappe Version - 14.75.0
Erpnext 14.70.1

### Installation method

None

**Comment by kunhimohamed** [comment]
Please give more details.

**Comment by m-aglan** [comment]
This issue happens when you open any invoice and make payment entry

**Comment by kunhimohamed** [comment]
Tested with given versions not able rise any error at payment entry.

**Comment by Ponyooooo** [comment]
also experiencing this one, 
on version ERPNext: v14.70.1 (HEAD)
Frappe Framework: v14.75.0 (HEAD)
Frappe HR: v14.28.1 (HEAD)
for frappecloud installed

**Comment by Ponyooooo** [comment]
here are the other discussion; https://discuss.frappe.io/t/typeerror-get-reference-details-takes-3-positional-arguments-but-5-were-given/123764/12

**Comment by dj12djdjs** [comment]
This is fixed in v14.70.2 release
