### ISSUE TITLE
ledger not showing

### ISSUE THREAD

**Issue by ashwinpmani** [frappe/erpnext#41628]
### Information about bug

cant search and find some ledgers in payment vouchers, 
employee name not showing  for some users 

### Module

accounts, HR

### Version

ERP NEXT

### Installation method

None

**Comment by Nihantra-Patel** [comment]
Which version?

Please provide a detailed explanation because the information you've given isn't sufficient. Include screenshots showing where the error occurs in the report.

**Comment by Mikeledger** [comment]
Hello @ashwinpmani is the issue resolved yet? You'll have to rectify with the ledger loptimal weblink.

**Comment by Nihantra-Patel** [comment]
Kindly upgrade to version 14 or 15, then refresh and check again because lots of bugs fixed in the new version.

Everything is working fine. No problems were encountered in the latest versions 14 and 15.
