### ISSUE TITLE
Bug on Link Field

### ISSUE THREAD

**Issue by bobzz-zone** [frappe/erpnext#4162]
Hi,

i found a bug...
in a link field if i fill wrong spelling and accidentially click out side the field or press tab and move to another field its make the field error

example:
creating PO
1. fill the supplier with wrong spelling
2. press tab to change to company
3. back to customer field to change to the right customer (since its mandatory , its still red if im not going back)
4. fill another filed with right data
5. press save

Expected:
Data is saved successfully

Actual
Its error, supplier is mandatory

please if this

**Comment by rmehta** [comment]
seems fixed
