### ISSUE TITLE
Inventory balances missing

### ISSUE THREAD

**Issue by miatano** [frappe/erpnext#41634]
### Information about bug

We are not able to see our inventory balances on our site armanarya.erpnext.com

### Module

stock

### Version

ERPNext: v13.55.2 (HEAD)

Frappe Framework: v13.58.21 (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
https://armanarya.erpnext.com/app/query-report/Stock%20Balance
```

**Comment by miatano** [comment]
any update?

**Comment by Nihantra-Patel** [comment]
Please check the role permissions for the report. Everything is working fine. No problems were encountered in the latest versions 14 and 15.

If site is on the frappe cloud then please raise the issue on the https://support.frappe.io


**We no longer provide support for version 13 or older.**

Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!

**Comment by miatano** [comment]
we need to upgrade the version 14. We put request on support tab of ERPNext but no response received so far
