### ISSUE TITLE
Exchange Rate Revaluation Settings

### ISSUE THREAD

**Issue by thida-bcn** [frappe/erpnext#41631]
![image](https://github.com/frappe/erpnext/assets/62122640/c7b1b273-d5d9-41e3-9ff8-62f3664a2c7d)

is this possible to add "Frequency" of Monthly?

**Comment by thida-bcn** [comment]
@ruthra-kumar hello sir, when will you release this?

**Comment by ruthra-kumar** [comment]
@thida-bcn 

Can't confirm on a date, due to other high priority tasks.


This is simple addition though. Contributions are welcome. If you can add this, I can help with review and merging.

**Comment by thida-bcn** [comment]
thanks
currently, we don't have enough Technical Person
Thanks and Regards,
Thida
Business Development Director

Business Centric Network Company Limited
+959 977 160 671
+959 254 677 192
***@***.***
https://businesscentricnetwork.com/
