### ISSUE TITLE
Serial No. Delivered - Warranty date not getting updated

### ISSUE THREAD

**Issue by dineshpanchal93** [frappe/erpnext#41646]
### Information about bug

In the Support module Warranty date has not much validation, 

I think we need to improve on that module 

### Module

support

### Version

ERPNext: v15.25.0 (version-15)

Frappe Framework: v15.28.0 (version-15)

Frappe Whatsapp: v0.0.2 (master)

Frappe HR: v15.21.2 (version-15)

India Compliance: v15.7.4 (version-15)

Print Designer: v1.2.0 (main)

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
Please elaborate on the scenario in full step (Steps to reproduce the issue).

**Comment by dineshpanchal93** [comment]
OK Sure

**Comment by Nihantra-Patel** [comment]
We have not encountered any such case so far. If it is an actual bug, please provide full details with a video and reopen the issue.

**Comment by dineshpanchal93** [comment]
https://www.youtube.com/watch?v=eoBU-5tyl2Q

As per the video its not working.

**Comment by dineshpanchal93** [comment]
@Nihantra-Patel I have made a video for your understanding


https://github.com/frappe/erpnext/assets/21578167/eba82de9-d31c-4596-8403-9122055f1494
