### ISSUE TITLE
[BUG] Purchase Order - Email being sent to wrong users

### ISSUE THREAD

**Issue by mayur-patel** [frappe/erpnext#4164]
Hi There,

We can confirm that even after un-ticking the recipients in CC section of email functionality on Purchase Order page the system still send out emails to those recipients that were not ticked before sending the email. Can this be fixed ASAP please?

Kind regards,
Mayur Patel

**Comment by anandpdoshi** [comment]
@mayur-patel I found this bug but that raises another question: if a person replies to this email, all followers (owner, assigned, starrers) are notified. Will this raise a concern for you?

**Comment by mayur-patel** [comment]
No. That should be fine in our case as we are only sending out the email internationally and then we send out the po attachment separately to external party. Please make sure that if the checkbox is ticked then email should be sent to those ppl on CC but if the checkbox is not ticked then the email shouldn't be sent to the ppl on CC.

Thanks
Mayur

On 14 Oct 2015 7:48 am, Anand Doshi <notifications@github.com> wrote:
@mayur-patel I found this bug but that raises another question: if a person replies to this email, all followers (owner, assigned, starrers) are notified. Will this raise a concern for you?

---
