### ISSUE TITLE
Transfer (warehouse should not allow user to choose same)

### ISSUE THREAD

**Issue by thida-bcn** [frappe/erpnext#41643]
### Information about bug

![image](https://github.com/frappe/erpnext/assets/62122640/640acb71-434b-4905-8097-7a932460025a)

### Module

stock

### Version

Frappe : 15.28.0
ERPNext : 15.25.0

Frappe : 14.75.0
ERPNext : 14.70.2

### Installation method

None

**Comment by dj12djdjs** [comment]
The reason this is allowed is for inventory dimensions: https://github.com/frappe/erpnext/pull/41651#issuecomment-2143521704

Maybe there is another way to validate by checking if mandatory inventory dimensions (if any) are set?
