### ISSUE TITLE
Wrong GSTIN picked up in Purchase Order doctype. other doctypes are picking correct GSTIN

### ISSUE THREAD

**Issue by Pankajo76** [frappe/erpnext#41641]
### Information about bug

i created several PURCHASE ORDER. it created PO using correct GSTIN. recently i observed PO are getting created using an incorrect GSTIN. in company setup GSTIN is showing up correctly. this does not happen with other doctypes/txn

### Module

accounts, buying

### Version

latest 15

### Installation method

None

**Comment by hpotabatti** [comment]
@Pankajo76 could you share a few more details, maybe a few screenshots so we can check and try to replicate this?
Also, which app do you use for GST compliance?

**Comment by Nihantra-Patel** [comment]
Everything is working fine. No problems were encountered in the latest version 15.


https://github.com/frappe/erpnext/assets/141945075/7205cd18-e1c1-4485-92c6-6d27f1584953


Again, check the supplier's GST number to see if the user has changed it or not.

**Comment by Pankajo76** [comment]
what we observed: once you setup ERPNEXT with a particular GSTIN and later if you change the GSTIN of the company for some reason, OLD gstin repopulates itself again. so we had to write a custom FETCH which always looks into current value of GSTIN in company address.
