### ISSUE TITLE
Asset Depreciation : Written Down Calculation is not correct

### ISSUE THREAD

**Issue by thida-bcn** [frappe/erpnext#41663]
### Information about bug

![image](https://github.com/frappe/erpnext/assets/62122640/067393b1-7fc3-414e-8419-836d95b41370)
![image](https://github.com/frappe/erpnext/assets/62122640/1010d87e-c945-4c9b-81ce-12b29fef26a2)

### Module

assets

### Version

Frappe : 15.28.0
ERPNext: 15.25.0

### Installation method

manual install

**Comment by nabinhait** [comment]
I think the current calculation in the system is correct. Please provide some website links to support your expected calculation. For now, I am closing the issue.

**Comment by thida-bcn** [comment]
https://www.wallstreetmojo.com/written-down-value-method/
