### ISSUE TITLE
Unable to login using social login keys

### ISSUE THREAD

**Issue by justinlusg** [frappe/erpnext#4166]
I've successfully saved the social login keys for Facebook. However, everytime when I try to login this page will always appear after facebook Authentication. Everytime I login with the same facebook account, system will always prompt me for my email, and first name and last name.

![image](https://cloud.githubusercontent.com/assets/12539216/10454551/e7202e52-71e7-11e5-84cb-f6c8c328ee24.png)

Possible security flaw:
I can fill in any email addresses in the system after i login with my Facebook account by entering the email address of the user in the email field.

**Comment by anandpdoshi** [comment]
@justinlusg thanks for reporting this

**Comment by anandpdoshi** [comment]
@justinlusg are you using the latest version? I am unable to reproduce this error in my local. Could also be due to some missing info from your profile or you might have denied permissions.

**Comment by justinlusg** [comment]
@anandpdoshi yes, it is the latest version.. you can try it over here..

http://erpdemo.agtech.com.sg
Username: administrator
Password: demo

I've setup a demo site and tested it and it has the same problem.

The "One Last Step" will always appear no matter how many times I've login using Facebook.

**Comment by fderyckel** [comment]
Same thing for me.  
It is just with Facebook login.   It works fine with Google.
But more annoyingly is that I always asked for customer address although the address is already entered.

**Comment by fderyckel** [comment]
For some reason, I can see that user/customer created by a Google Login works fine

![screen shot 2015-10-21 at 07 23 42](https://cloud.githubusercontent.com/assets/7240992/10628356/c4d5d936-77c4-11e5-88c3-c29d79f8e574.png)

But it stays blank with Facebook.

![screen shot 2015-10-21 at 07 23 32](https://cloud.githubusercontent.com/assets/7240992/10628365/d24fd288-77c4-11e5-8acb-81870d5dc639.png)

**Comment by justinlusg** [comment]
@fderyckel I've not tried personally with Google, will try it. 

@anandpdoshi might be a possible security flaw, which is critical to be resolve soon.

**Comment by justinlusg** [comment]
After the latest update, it third party authentication disappeared under the user account. The Facebook authentication still does not work as well. The security flaw however is still there, I can use Facebook to authenticate and get into anybody's account without their permission/password.

**Comment by anandpdoshi** [comment]
@justinlusg fixed. Facebook had changed its api
