### ISSUE TITLE
Non-transparent header on cloud and transparent header area on hosted installs

### ISSUE THREAD

**Issue by Ferohers** [frappe/erpnext#4167]
There is a differnece between on cloud erpnext and .sh installed. Desk.min.css is responsible for that. It is transparent on hosted versions.

![image](https://cloud.githubusercontent.com/assets/14891349/10459268/7ebff8de-71d7-11e5-92a4-b9aa0db6babc.png)

**Comment by Ferohers** [comment]
Automatic update hit :)
![image](https://cloud.githubusercontent.com/assets/14891349/10477534/a4a5832e-725f-11e5-8657-7bb02d50d552.png)

**Comment by rmehta** [comment]
There is no difference between hosted and open source version!
