### ISSUE TITLE
error: delivery link return response code: 500

### ISSUE THREAD

**Issue by momakarem** [frappe/erpnext#41675]
### Information about bug

solve the problem of error: delivery link return response code: 500 when linking woocommerce to erpnext in 2024

### Module

ecommerce

### Version

15

### Installation method

None

**Comment by Nihantra-Patel** [comment]
Deprecating the woo-commerce integration in v15 due to its broken and unmaintained state.

![image](https://github.com/frappe/erpnext/assets/141945075/97b68d8f-111a-4383-b22a-6a950e185b51)

Please check it: https://github.com/frappe/erpnext/pull/37015
