### ISSUE TITLE
Cash Flow Customization

### ISSUE THREAD

**Issue by thida-bcn** [frappe/erpnext#41670]
### Information about bug

is this possible to get back features of cash flow customization at version 15
we are using cash flow customization at version 13,14 after upgrade to version 15 cash flow customization feature is missing

### Module

accounts

### Version

version: 15

### Installation method

FrappeCloud

**Comment by Nihantra-Patel** [comment]
The Cashflow Mapper has been removed in version 15. It was buggy and not maintained, so we decided to deprecate it.

https://github.com/frappe/erpnext/wiki/Migration-Guide-to-ERPNext-version-15#cashflow-mapper
