### ISSUE TITLE
Saving Purchase Invoice Gives "Please set default Asset Received But Not Billed in Company XXXX" after latest update

### ISSUE THREAD

**Issue by fadilsiddique** [frappe/erpnext#41684]
### Information about bug

When trying to save Purchase Invoice, itGives "Please set default Asset Received But Not Billed in Company xxxx" after latest update. It wasnt there before and i'm not purchasing a fixed asset as this account head is for fixed assets.

![Screenshot from 2024-05-30 10-05-58](https://github.com/frappe/erpnext/assets/48912196/699e88e6-174d-4679-8cf7-63f3a0af00f2)

### Module

stock, buying

### Version

ERPNext: v15.26.0 (HEAD)

Frappe Framework: v15.29.0 (HEAD)

### Installation method

FrappeCloud

**Comment by Nihantra-Patel** [comment]
Please check this PR: https://github.com/frappe/erpnext/pull/41368

Now you have to set the default accounts in the company.

![image](https://github.com/frappe/erpnext/assets/141945075/51936262-dc14-4187-8ebe-ec868bac971d)
