### ISSUE TITLE
Paypal Integration [Paid Development] 

### ISSUE THREAD

**Issue by marri2k** [frappe/erpnext#4169]
Paypal integration

**Comment by rmehta** [comment]
@marri2k thanks. Here is what we have planned

1. Checkout using PayPal
2. Create a new "Payment Request" document where the end customer will pay via PayPal and the payment will be automatically recorded.

Can you sponsor this for $500?

**Comment by aacosae** [comment]
We are open to sponsor for $200

**Comment by marri2k** [comment]
Our Budget is 200$ as mentioned by our company AACOS

**Comment by yashodhank** [comment]
Feature is implemented with Integration Services now. So Closing.
@marri2k maybe you donate pledged amount to ERPNext/Frappe Technologies.
