### ISSUE TITLE
Unresolved #29048 – Cannot select company when adding a new account in Chart Of Accounts

### ISSUE THREAD

**Issue by konradbr** [frappe/erpnext#41695]
### Information about bug

See: https://github.com/frappe/erpnext/issues/29048

In a multi-company setup, when adding a new account from the list view, the **Company** field is grayed out (pre-filled with the default company). Adding via Tree view is still possible:

![image](https://github.com/frappe/erpnext/assets/28401247/0ea602be-750f-4feb-aac6-c5608807b0a0)

### Module

accounts

### Version

```
erpnext 15.19.0
erpnextswiss 1.23.2
frappe 15.20.0
hrms 15.16.0
payments 0.0.1
```

### Installation method

manual install

**Comment by hpotabatti** [comment]
Hey @konradbr ,

What is your expectation of the system?
should the system not auto-populate the default company or the system should allow the user to manually select a company?

**Comment by konradbr** [comment]
@hpotabatti The field can auto-populate (based on session defaults?) or stay blank, but the system should always allow the user to change it. Having the account number field available and editable here would be great, too!

**Comment by dj12djdjs** [comment]
This has been the case for a while, The problem is in account.json `account_number` is `read_only`. The system assumes everyone will create an account via the Chart of Accounts tree.

Account record creation should be the same using "New Account" and "Add Child".

**Comment by Nihantra-Patel** [comment]
I raised the PR: https://github.com/frappe/erpnext/pull/41731.

Let me know if I am forgetting anything. If PR is proper then upvote.

**Comment by konradbr** [comment]
@Nihantra-Patel perfect, thank you!

**Comment by konradbr** [comment]
@Nihantra-Patel couldn't find option to upvote PR/message — not sure I'm not seeing the proper option / missing permissions, let me know, please, and I will be happy to do it :)

**Comment by Nihantra-Patel** [comment]
> not sure I'm not seeing the proper option / missing permissions

😄 -> 👍 

![image](https://github.com/frappe/erpnext/assets/141945075/d7ab9029-9044-40b8-aaae-b43e038260bc)
