### ISSUE TITLE
Stock Recon with a Batched Item not allowing change of quantity from original stock value.

### ISSUE THREAD

**Issue by abhioncode** [frappe/erpnext#41698]
### Information about bug

In erpnext version 15.26.1, When trying to stock reconcile an item, I would select all the basic fields such as item, warehouse, and batch value. ErpNext then goes ahead and calculates the stock balance and value. Great. 

But when I try to change the value, upon save ... it reverts back to the original stock balance. basically not allowing me to update the stock balance in teh stock reconciliation. Which is a problem.

### Module

stock

### Version

ERPNext Version - 15.26.1

### Installation method

None

**Comment by Nihantra-Patel** [comment]
Tested, worked properly.


https://github.com/frappe/erpnext/assets/141945075/30c9af69-f21f-4ec1-ba82-637faacafc66

**Comment by abhioncode** [comment]
Hi @Nihantra-Patel 

Yes, I can see in your video it works as it's supposed to. But Take a look at the video i am uploading. you can see how no matter if i increase or decrease the quanttiy the system reverts back to the original value.


Uploading Grabación 2024-06-02 160000 (1).mp4…

**Comment by abhioncode** [comment]
https://github.com/frappe/erpnext/assets/85059961/4ad74f65-5098-41c0-96c1-c5fb0eb2100a

**Comment by abhioncode** [comment]
Ok, found what seems to be the issue. Version 15 has a new feature called Batch Bundle. I had to configure settings as per this documentation and it started working: 

https://docs.erpnext.com/docs/user/manual/en/serial-and-batch-bundle
