### ISSUE TITLE
Unable to open Supplier from supplier list

### ISSUE THREAD

**Issue by Amanthakur11111** [frappe/erpnext#41705]
### Information about bug

Unable to open Supplier from supplier list. 

### Module

buying

### Version

Frappe version - 15

### Installation method

FrappeCloud

**Comment by Nihantra-Patel** [comment]
Everything is working fine. No problems were encountered in the latest 15.

Please check it.


https://github.com/frappe/erpnext/assets/141945075/aa264a11-38bf-4db4-bee7-c0f0d80ab742

I think there will be problem in permission issue, check.
