### ISSUE TITLE
[Paid Development] 

### ISSUE THREAD

**Issue by inventobd** [frappe/erpnext#4170]
Hello All

I have 3 requirements :

    1. Allow product bundle for services
    2.  Auto calculate rate of service product bundle based on sub-parts
    3. Ability for sales manager to change / alter sub parts/item and item price in sales order

@rmehta  have done first one :) . Can we do this next two ? I will adjust by sponsoring the next 2 . I can pay via paypal now . Please give me a small budget so I can afford :) . Previous thread is closed , so I have opened a new one . Here is the previous one 

https://github.com/frappe/erpnext/issues/3452

Thanks

**Comment by rmehta** [comment]
@inventobd can you please open a new request for each issue. Will be happy to respond on that.
