### ISSUE TITLE
[Enhencement]  Auto calculate rate of service product bundle based on sub-parts

### ISSUE THREAD

**Issue by inventobd** [frappe/erpnext#4171]
Hello 

I,m selling service items individually and as package . Like 
1. Air Ticket (Individual service Item with price)
2. Visa Consultancy (Individual service Item with price)
3. 1 night hotel accommodation  Price (Individual service Item with price)
4. Sight seeing 1 person (Individual service Item with price)

And as a product bundle I,m selling it as  "Thailand tour package"

Right now I can only create an item as Thailand tour package and specify a fixed price for it . And then can add other items from Selling -> Setup -> Product bundle with the parent item . Which is actually system giving to customer as packing list item . 

But I want system to fetch item prices from individual package items and determine full package price automatically based on quantity of individual items .  Is it possible in any way ? If needed I can sponsor it .
Thanks

**Comment by rmehta** [comment]
@inventobd do you want to do this in the order or at time of making bundle?

**Comment by inventobd** [comment]
@rmehta I think at time of making bundle is good but if its possible to keep option for both fixed price and auto calculate price then it will be very helpful :)

**Comment by rmehta** [comment]
@inventobd The hard thing here is that price info for packed items is not updated. And this will have to be multi-currency et. all. This is a much bigger problem than it looks.

How important is this?

**Comment by inventobd** [comment]
I see . Yes I saw that pricing is not associated with packed items at all, also this packing items doesn't make any impact on sales report too only main item price does .  Then I can take a look how much I can utilize fixed pricing and we can proceed with it in future ?  Can you guyz plz take a look at this issue https://github.com/frappe/erpnext/issues/4172 then ? 

Thanks
