### ISSUE TITLE
When we try to submit Purchase invoice we get this error "Please set default Asset Received But Not Billed in Company"

### ISSUE THREAD

**Issue by vittitrade** [frappe/erpnext#41715]
### Information about bug

When we try to submit the purchase invoice after creating the purchase receipt. We get this error " Please set default Asset Received But Not Billed in Company" . Where we have the default asset is set for the same account. 

This has started happening after the 29/05/2024 update. 

### Module

buying

### Version

ERPNext: v15.26.0 (HEAD)

Frappe Framework: v15.29.0 (HEAD)

### Installation method

FrappeCloud

**Comment by ahmad-91** [comment]
yes you should select one

**Comment by fadilsiddique** [comment]
> ### Information about bug
> When we try to submit the purchase invoice after creating the purchase receipt. We get this error " Please set default Asset Received But Not Billed in Company" . Where we have the default asset is set for the same account.
> 
> This has started happening after the 29/05/2024 update.
> 
> ### Module
> buying
> 
> ### Version
> ERPNext: v15.26.0 (HEAD)
> 
> Frappe Framework: v15.29.0 (HEAD)
> 
> ### Installation method
> FrappeCloud
> 
> ### Relevant log output / Stack trace / Full Error Message.
> _No response_


check this 
https://github.com/frappe/erpnext/issues/41684#issuecomment-2138869707

**Comment by Nihantra-Patel** [comment]
Please check this PR: https://github.com/frappe/erpnext/pull/41368

Now you have to set the default accounts in the company.

![image](https://github.com/frappe/erpnext/assets/141945075/51936262-dc14-4187-8ebe-ec868bac971d)

**Comment by Nihantra-Patel** [comment]
fix the issue: https://github.com/frappe/erpnext/pull/41734
