### ISSUE TITLE
Issue with Configured DAS Formula in Supplier Scorecard

### ISSUE THREAD

**Issue by sowndharya998** [frappe/erpnext#41728]
### Information about bug

We have configured the DAS(Delivery, Accuracy, and Service) formula in our supplier scorecard, but it appears that the formula is not working as expected. Despite following the configuration steps, the results are not being calculated correctly.

![Screenshot 2024-06-03 102009](https://github.com/frappe/erpnext/assets/75109236/ac16199e-8362-460b-8412-32170f4c532f)

And we got the result like very poor for all suppliers.
![q](https://github.com/frappe/erpnext/assets/75109236/dc3d890a-dcea-4793-aaaa-5de9bfff6e94)

For Your reference,
We would like to rate our vendors based on :
Delivery Adherence Score (DAS): DAS = (Promised delivery time (days) / Actual delivery time (days)) * 100

Instead of these, what variables can I use? These variables are not successful for us.

kindly provide us, the correct formula for this.

### Module

buying

### Version

Frappe version- v15.8.0
ERPnext version-  v15.8.3

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
If you haven't checked, then please check the [documentation](https://docs.erpnext.com/docs/user/manual/en/supplier-scorecard). 

Also, check out the video.

https://www.youtube.com/watch?v=2w_psd-IqlM

**Comment by nabinhait** [comment]
This is not a bug, it's a configuration issue. Please post your query on https://discuss.frappe.io/
