### ISSUE TITLE
[Paid Development] Ability for sales user  to change / alter service product bundle items in sales order

### ISSUE THREAD

**Issue by inventobd** [frappe/erpnext#4172]
I,m selling service items individually and as package . Like

```
Air Ticket (Individual service Item with price)
Visa Consultancy (Individual service Item with price)
1 night hotel accommodation Price (Individual service Item with price)
Sight seeing 1 person (Individual service Item with price)
```

And as a product bundle I,m selling it as "Thailand tour package"

Sometimes beacuse of unavailability of Air tickets , sales person need to provide a different air ticket , or sometimes customer can request for a different hotel at the time of sale . Is it possible to change or alter product bundle items in time of sales for a sales user ? Package price can be the same and will not vary just service will be changed and will impact on package costing 

Thanks

**Comment by system19** [comment]
Sorry if this is the wrong place to add a comment @inventobd . But would you want to give a "sales user" the privileges to change the price/product/service? Sounds potentially dangerous.

**Comment by inventobd** [comment]
Hello @system19 Whether its sales user or manager , I think permission or user restriction can take care of that . But my requirement is ability to change, whatever  its admin or regular user .
Thanks

**Comment by system19** [comment]
Sounds all good. There are so many different business structures that use ERPNext that I learn something new every day in these forums. Only hope that you get the chance to sell yourself a good holiday bundle from time to time :-)

**Comment by rmehta** [comment]
@inventobd this is a hard one again, can you just leave a note / comment saying that this is changed?
Or maybe create generic items, that can have specific notes later on?

Or maybe have separate notes for each type of item using custom fields that are editable after submit?

**Comment by inventobd** [comment]
@rmehta 
Can you explain a bit ? Sorry for late replay :(

**Comment by rmehta** [comment]
@inventobd You can create a standard item for Air Ticket. And then add the details in description which you can change later.
