### ISSUE TITLE
TItle: ERPNext is Picking the System Settings Number Format over the Format Specified in the Currency DocType

### ISSUE THREAD

**Issue by emmanuel-mwendwa** [frappe/erpnext#41730]
## Steps to Reproduce
 - Set a number format in the System Settings of the application instance
 ![Screenshot from 2024-05-29 08-23-40](https://github.com/frappe/frappe/assets/82759762/8f27ec0e-d482-4eee-9bb9-f28b145b04c9)
 - Go to a Sales Invoice or Purchase Invoice DocType
 - In the Currency and Price List Section. Select a Currency you want.
 ![Screenshot from 2024-05-29 08-23-48](https://github.com/frappe/frappe/assets/82759762/f2a3ccd0-a7e9-476f-a3e6-2e61fa6c71d3)

## Actual behavior

 - The amount or grand total field picks and displays in the number format provided in the System Settings rather than Currency type selected.
 
 ## Expected behavior

I expect the application to pick the format specified by the Currency and display them in this format.

Like for the screenshots below I expect the grand total to be displayed in INR number format (#,##,###.##) but the system is choosing the System Settings format (#,###.##)

## Screenshots:

![Screenshot from 2024-05-29 08-23-32](https://github.com/frappe/frappe/assets/82759762/261c7283-fdc9-4831-a9b8-f31a5d360bdb)

### Module

accounts, buying, selling

### Version

ERPNext: v15.26.1 (HEAD)

Frappe Framework: v15.29.0 (HEAD)

### Installation method

None

**Comment by Nihantra-Patel** [comment]
Duplicate issue: https://github.com/frappe/frappe/issues/26584
