### ISSUE TITLE
Difference between print preview on the website and an emailed pdf file.

### ISSUE THREAD

**Issue by Ferohers** [frappe/erpnext#4173]
This is the normal preview works perfectly.
![1](https://cloud.githubusercontent.com/assets/14891349/10477975/0a4334d0-7263-11e5-8dd1-b748e993c167.png)
This is full page preview works perfectly.
![2](https://cloud.githubusercontent.com/assets/14891349/10477987/1aadd3a2-7263-11e5-807d-6701ba4df6a5.png)
This is the pdf file which is sent thru an e-mail
![image](https://cloud.githubusercontent.com/assets/14891349/10478020/514b5d94-7263-11e5-9abf-6c07871a9edd.png)

**Comment by anandpdoshi** [comment]
This is because for self hosted version, you need to set the host_name property in site_config.json

**Comment by Ferohers** [comment]
Thank you very much

**Comment by jwrober** [comment]
Closed via comments.
