### ISSUE TITLE
Enable "Allow on Submit" on "Supplier Delivers to Customer" (Quick Fix Issue)

### ISSUE THREAD

**Issue by NassimBentarka** [frappe/erpnext#41754]
**Is your feature request related to a problem? Please describe.**
Supplier Delivers to Customer field is one of the fields that are frequently updated. To avoid cancelling and amending a Sales Order, this field has to be editable after Submitting the Sales Order.

**Describe the solution you'd like**
Make the Field "Supplier Delivers to Customer" that's located on the Sales Order Item child table as "Allow on Submit" = 1
 
**Describe alternatives you've considered**
Alternative is to cancel the Sales Order, make the changes then resubmit as a new amended Sales Order. However this takes a lot of time and creates too many cancelled Sales Order for no good reason

**Additional context**
A reliable solution is to Enable "Allow on Submit" on "Supplier Delivers to Customer"

**Comment by Nihantra-Patel** [comment]
You can easily set using the property setter, so please check it and apply it.

![image](https://github.com/frappe/erpnext/assets/141945075/cef9272d-4cef-461e-9f9a-9bf1dbf344b0)
