### ISSUE TITLE
 add title field in customize form 

### ISSUE THREAD

**Issue by mayur-patel** [frappe/erpnext#4177]
@anandpdoshi 
As requested I am creating this issue so that we can have title field functionality for doc type like Leave Application which doesn't have default title field.

**Comment by mayur-patel** [comment]
Thanks Anand. I can see "Title Field" section customize form page. But it only allows me to use one field. As per @rmehta  suggestion I can't use {employee_name} {leave_type}. The whole purpose we want title field so that we can display multiple field as one field on leave application list page to over come limit of 5 fields restriction. I thought you were making the function as per this  link https://manual.erpnext.com/contents/customize-erpnext/document-title

**Comment by anandpdoshi** [comment]
Hi Mayur,

Add “{employee_name} {leave_type}” in the options of the custom field ’title’. See this help: https://manual.erpnext.com/contents/customize-erpnext/document-title

Best,
Anand Doshi

ERPNext

**Comment by mayur-patel** [comment]
Thanks Anand.
Kind regards,
Mayur Patel
