### ISSUE TITLE
Profit and Loss >> Pick Column Orders

### ISSUE THREAD

**Issue by thida-bcn** [frappe/erpnext#41815]
### Information about bug

is this possible to show original order by month 
![image](https://github.com/frappe/erpnext/assets/62122640/57cf04ae-fffc-459f-8eee-b072de3219b3)
Expected 
Jan
Feb
March
ERPNext Result
Apr
Aug
Dec

### Module

accounts

### Version

Frappe : 15.29.1
ERPNext : 15.27.0

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
i know this isn't a bug.
It defines the whole printing report, not just one report, and it works based on alphabetical order.
