### ISSUE TITLE
Error while updating Employee Record

### ISSUE THREAD

**Issue by tejasmarvania** [frappe/erpnext#41820]
### Information about bug

I have an employee left and I am trying to update the record with relieving date and status and I am getting the following error. 
"Could not find Row #50: Role: Moderator". It dosen't have any other information. 

### Module

HR

### Version

Frappe Version - 15.29.1
ERPNext Version - 15.27.1

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
Could not find Row #50: Role: Moderator
```

**Comment by Nihantra-Patel** [comment]
Everything is working fine. No problems were encountered in the latest version 15.


https://github.com/frappe/erpnext/assets/141945075/9172631b-f799-4198-afd9-d1fbae3eb393

If any customizations or scripts have been added, check them. Also, open the console log to identify and locate any errors.
