### ISSUE TITLE
In LIST VIEw, Actions Tab after Selection of Items, is not available in new Update 

### ISSUE THREAD

**Issue by CandidSolution** [frappe/erpnext#41830]
### Information about bug

In earlier erpnext 15 Versions, in LIST VIEW, when you select a list of entries, Actions tab used to become active to perform actions such as Export, Cancel, Delete, etc.

But after the last update, now when you select a list of entries, there is no actions tab so we cannot export or delete multiple entries. Now we have to individually open the entry and then delete it.

![image](https://github.com/frappe/erpnext/assets/172197899/c92b45e3-1b76-4ad4-9e8a-320628f10bc2)

### Module

accounts, stock, buying, selling, ecommerce, manufacturing, HR, projects, support, CRM, assets, integrations, quality, regional, portal, agriculture, education, non-profit, other

### Version

15.29.1-15.27.1

### Installation method

FrappeCloud

**Comment by Nihantra-Patel** [comment]
We tested it with multiple users. Everything is working fine. No problems were encountered in the latest version 15.


https://github.com/frappe/erpnext/assets/141945075/53bef350-df73-45bb-9ee3-f9c40ab1774c

Maybe, there is a permissions or rights issue, please check with another user.
