### ISSUE TITLE
Permission issue regarding to leave management

### ISSUE THREAD

**Issue by Ferohers** [frappe/erpnext#4184]
We will have 5 leave approver who are also managers. I want leave approvers only see their own related leave applications. When I choose only the owner can see the leaves
![1](https://cloud.githubusercontent.com/assets/14891349/10538186/834e4e80-73ff-11e5-88cf-5bab491f43d8.png)

No leave approver able to see or able to access (from messaging links too) and approve the leaves.

![2](https://cloud.githubusercontent.com/assets/14891349/10538264/1290a5ac-7400-11e5-8298-acf6ba3112e4.png)

If no owner is chosen, 
![3](https://cloud.githubusercontent.com/assets/14891349/10538306/54e81368-7400-11e5-9760-81a7781ee286.png)

![33](https://cloud.githubusercontent.com/assets/14891349/10538323/745d79ae-7400-11e5-9105-866d738d701a.png)

Leave approvers can see all applications.

**Comment by PawanMeh** [comment]
Closing this as it appears to be merged
