### ISSUE TITLE
Column Break showing in Purchase Order under the 'Recurring' section

### ISSUE THREAD

**Issue by bohlian** [frappe/erpnext#4185]
Within Purchase Order, under the 'Recurring' section, there is a column break that is showing with a visible label.

![image](https://cloud.githubusercontent.com/assets/8383249/10538856/ae221f1c-7425-11e5-8b1f-723bf4ec6422.png)

Most likely its because of a column break element that is set in the Purchase Order doctype.

![image](https://cloud.githubusercontent.com/assets/8383249/10538872/bf9df946-7425-11e5-9f9b-220dcc3ff590.png)

The Sales Order doctype does not have such an element.

**Comment by anandpdoshi** [comment]
Thanks! we will fix this.

**Comment by anandpdoshi** [comment]
Pushed a fix on develop branch

**Comment by bohlian** [comment]
Confirmed that its ok now, thanks @anandpdoshi
