### ISSUE TITLE
Permission Error while creating new company

### ISSUE THREAD

**Issue by tejasmarvania** [frappe/erpnext#41857]
### Information about bug

I have a user with Accounts Manager role. When I am creating new Company from that User Account I am getting Permission error
[Permission Error.pdf](https://github.com/user-attachments/files/15785906/Permission.Error.pdf)

### Module

accounts

### Version

Frappe Version - v15.29.1
ERPNext Version - v15.27.2

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
Not allowed for Company: None
User info@milliyant.com does not have access to this document: Company - None

Insufficient Permission for Company (create)
```

**Comment by Nihantra-Patel** [comment]
Please check the role permissions for the Company doctype. If any user permissions have been applied to the Company, please remove them.

![image](https://github.com/frappe/erpnext/assets/141945075/7628aef7-b31d-44aa-b641-5934032f1c13)


Everything is working fine. No problems were encountered in the latest version 15.
