### ISSUE TITLE
Accounting Dimension on Journal Entry is not Fetched from Invoices/Payments when Invoice Reconciled against Credit Note using Payment Reconciliation

### ISSUE THREAD

**Issue by landersaga** [frappe/erpnext#41866]
### Information about bug

Payment Reconciliation with Credit Note create Journal Entry that it seems has bug, Accounting Dimension other than Cost Center on newly created Journal Entry is blank although the Invoices/Payments have Accounting Dimension other than Cost Center. So allocated credit/debit has no tag on GL Report

Invoices reconciled against Credit Note using Payment Reconciliation
![image](https://github.com/frappe/erpnext/assets/80461903/49abf23e-1530-4d0d-a247-e18565a9818b)

Journal Entry created has no Accounting Dimension other than Cost Center
![image](https://github.com/frappe/erpnext/assets/80461903/93f6726a-ff98-4f90-be34-cbb533f52f97)

### Module

accounts

### Version

Frappe v14.62.4
ERPNext v14.46.7

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
Worked properly in the latest version 14. please check it.


https://github.com/frappe/erpnext/assets/141945075/ae686ea2-ddc6-43d4-9e5b-4ffe09dd6a06
