### ISSUE TITLE
Select cost center in sales order in time of submitting sales order to manage different branch wise sales

### ISSUE THREAD

**Issue by inventobd** [frappe/erpnext#4187]
According to previous forum post and conversation . I saw that if we want to manage branch wise sales management then we need to log our sale under different cost center . 

But cost center is only selectable in sales invoice items . And sales invoice is raised by accounting department only. For a service item how can a sales user select cost center when he/she create a sales order ? Or is there any way we can differentiate branch or cost center at the time of sales for service items not at the time of rising invoice ?

**Comment by anandpdoshi** [comment]
Cost Centre is used to track income or expense. Maybe you should use Project instead of Cost Centre in your case. Each branch could be a project and you get project wise report for that.
