### ISSUE TITLE
Remove Validation to Prevent Foreign Currency Advance Accounts

### ISSUE THREAD

**Issue by parasonit** [frappe/erpnext#41878]
### Feature Request: Remove Validation to Prevent Foreign Currency Advance Accounts

**Context:**
We need to remove the validation that prevents using foreign currency advance accounts in ERPNext because we have EEFC accounts and frequently receive amounts in foreign currency as advances.

**Problem:**
The current validation in ERPNext does not allow using foreign currency advance accounts. This limitation causes issues for companies like ours that operate with EEFC accounts and need to process foreign currency advances efficiently.

![image](https://github.com/frappe/erpnext/assets/118710551/0ef8bf15-63c1-4b93-bc59-bbb9c0a7d8e7)
![image](https://github.com/frappe/erpnext/assets/118710551/c7445efc-bd03-4dfb-a258-fe877dfe5c83)
![image](https://github.com/frappe/erpnext/assets/118710551/94bebfd4-db1f-4460-bd69-277db248d7c8)

**Proposed Solution:**
Introduce a configuration option to allow specific foreign currency advance accounts. This could be done by:
1. Allowing users to specify which accounts can be used for foreign currency advances.
2. Implementing a customizable validation logic to bypass the default restriction for specified accounts.

![image](https://github.com/frappe/erpnext/assets/118710551/8700f482-9d82-481a-b52b-07f7ce3b0117)

**Benefits:**
- This feature will help businesses operating with EEFC accounts and handling foreign currency advances.
- It will improve the flexibility and usability of the Payment Entry process in ERPNext.

**Additional Information:**
We currently have EEFC accounts and need to receive and manage advances in foreign currency without facing validation issues. Implementing this feature will greatly enhance our workflow and ensure compliance with our financial operations.

This feature request. We believe it will be beneficial for many ERPNext users handling foreign currencies.

**Comment by Nihantra-Patel** [comment]
refactor: allow foreign currency advance accounts : https://github.com/frappe/erpnext/pull/41844

**Comment by ruthra-kumar** [comment]
Support added in https://github.com/frappe/erpnext/pull/41844
