### ISSUE TITLE
Purchase Order Update Items button does not add Supplier Codes

### ISSUE THREAD

**Issue by Codeaview** [frappe/erpnext#41887]
### Information about bug

1. Submit Purchase Order
2. Use Update Items button
3. Added Items are not added with their Supplier Codes - the Supplier Codes are missing in printed documents even though they exist for given Items. Originally added items do have the Supplier Codes.

### Module

buying

### Version

Frappe Framework: v14.43.1 (version-14)
ERPNext: v14.33.2 (version-14)

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
The purpose of the update item feature after submission is to enable faster future entries. However, it does not update everything, and maintaining this feature has become very difficult. Therefore, the team is considering whether to remove this feature altogether. Many requests have been received to update various aspects such as XYZ, but not all items get updated. Additionally, people need to update pricing rules and discounts. Managing all these updates has become very challenging and is no longer feasible.
