### ISSUE TITLE
Cannot send email AGAIN - system is trying to send to user and causes fail

### ISSUE THREAD

**Issue by monojoker** [frappe/erpnext#4188]
Hi Guys,

Can someone please help me get to the bottom of this it's really causing issues with customers not receiving invoices... Here's the story in a nutshell:

1. Go to send email of invoice:

![image](https://cloud.githubusercontent.com/assets/10917366/10567296/177d179a-7643-11e5-83c1-96aea3e964a2.png)

Note I am removing the tick to CC sonia@... 

2. Click send and receive error:

![image](https://cloud.githubusercontent.com/assets/10917366/10567303/35fd1a6c-7643-11e5-9525-44e3ce06d4ac.png)

3. Check Bulk Email list and see Not Sent message:

![image](https://cloud.githubusercontent.com/assets/10917366/10568034/ef878a14-7655-11e5-84fb-bf7af5b5a582.png)

In fact nothing is sending now...

Why is the system reporting a failure to send to sonia@mcleans where there is NOTHING telling it to even send to that user. They are not subscribed to notifications:

![image](https://cloud.githubusercontent.com/assets/10917366/10568043/1bff5e14-7656-11e5-8833-73a50db1db48.png)

If the internal email "system" is this problematic what else can I setup? We need this to work reliably or it affects cashflow negatively!

**Comment by pdvyas** [comment]
Seems to be related to subscription code with erpnext.com

**Comment by anandpdoshi** [comment]
Hi Liam

Check the checkbox in user form "send notifications from transactions I
follow" and you should start getting the emails. It is because someone
unchecked it that the user isn't getting the emails.

- Anand.

**Comment by monojoker** [comment]
Hi @anandpdoshi - that's turned off so the user doesn't get the emails. Are you saying it's failing because they HAVE to follow? It should send to the customer regardless I thought?

@pdvyas closed as fixed? I have received the one i sent to my hotmail so I'll assume it was just an issue at your end and say a big THANKS? :)

**Comment by anandpdoshi** [comment]
Hi Liam

Sorry just saw pratik's reply. Ignore my reply.

Also the problem about CC notified as not sent will be fixed with the next
release with a related bug fix.

**Comment by monojoker** [comment]
@anandpdoshi no problems thanks for the reply. Glad to hear we have a fix coming up. I'll stop asking the same question then, sorry.
