### ISSUE TITLE
Employee list not updated

### ISSUE THREAD

**Issue by Smokinjoint** [frappe/erpnext#41891]
![Screenshot_20240613-102943_Chrome](https://github.com/frappe/erpnext/assets/172584998/d3b14480-8c87-46a7-a9e6-e91dd90b070a)
![Screenshot_20240613-103029_Chrome](https://github.com/frappe/erpnext/assets/172584998/884c78e8-9eba-4e55-8d6c-48e2f16c1b11)
### Information about bug

I have two employees but they don't reflect on the HR dashboard under total employees. The dashboard says zero employees. Yet when I click on the total employees' button, the employees are there.

### Module

HR

### Version

version 15

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
Kindly upgrade your version 15 because everything is working fine. No problems were encountered in the latest version 15.


https://github.com/frappe/erpnext/assets/141945075/df2a2aff-2713-4c11-a501-c7802270ed26

**Comment by Smokinjoint** [comment]
noted tha

> Kindly upgrade your version 15 because everything is working fine. No problems were encountered in the latest version 15.
> 
>  scrnli_13_06_2024_14-04-45.mp4

noted thank you
