### ISSUE TITLE
Batch No of an Item has negative stock of quantity -30.0 in the warehouse

### ISSUE THREAD

**Issue by PraveenkumarSubramani** [frappe/erpnext#41909]
### Information about bug

While Submitting the Delivery Note, the following warning occurs. "Batch No EET-2405459 of an Item  has negative stock of quantity -30.0 in the warehouse Mother Warehouse - ELPL"

<img width="807" alt="Screenshot 2024-06-15 at 12 59 51 PM" src="https://github.com/frappe/erpnext/assets/93510095/a1ed56a0-5e12-43ae-bd19-b64dcaf200ee">
<img width="1331" alt="Screenshot 2024-06-15 at 1 41 44 PM" src="https://github.com/frappe/erpnext/assets/93510095/39dec927-b14f-4937-93ad-e92796cdcf31">

### Module

stock, selling

### Version

Frappe Version - v15.29.2
ERPNext Version - v15.27.6

### Installation method

None

**Comment by Nihantra-Patel** [comment]
Please check the time of your last stock purchase and the time on your delivery note. If the time of your last stock purchase is before you create the delivery note, then this will happen.

**Comment by PraveenkumarSubramani** [comment]
@Nihantra-Patel We ensured it. But the purchase is not done after delivery note and we are creating the delivery note for current date.

**Comment by thida-bcn** [comment]
> @Nihantra-Patel We ensured it. But the purchase is not done after delivery note and we are creating the delivery note for current date.

can you share me stock ledger

**Comment by rohitwaghchaure** [comment]
@PraveenkumarSubramani do you have submitted serial and batch bundles with no Voucher No?

**Comment by thida-bcn** [comment]
> ### Information about bug
> While Submitting the Delivery Note, the following warning occurs. "Batch No EET-2405459 of an Item has negative stock of quantity -30.0 in the warehouse Mother Warehouse - ELPL"
> 
> <img alt="Screenshot 2024-06-15 at 12 59 51 PM" width="807" src="https://private-user-images.githubusercontent.com/93510095/339966619-a1ed56a0-5e12-43ae-bd19-b64dcaf200ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4MDI1NDksIm5iZiI6MTcxODgwMjI0OSwicGF0aCI6Ii85MzUxMDA5NS8zMzk5NjY2MTktYTFlZDU2YTAtNWUxMi00M2FlLWJkMTktYjY0ZGNhZjIwMGVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDEzMDQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmZTMyMjE5MjJkYjJjOWU4OWZhNzU1ZTI0ODNmZTkyZDlkMTBlZTdhYjM5ZmU3YTA1OWRlNTAwYWM1MjQwMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NqoLQ0EM4MWcvtjuJt8xCLtchqwLAutyuV8sS3y2Z-k"> <img alt="Screenshot 2024-06-15 at 1 41 44 PM" width="1331" src="https://private-user-images.githubusercontent.com/93510095/339966764-39dec927-b14f-4937-93ad-e92796cdcf31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4MDI1NDksIm5iZiI6MTcxODgwMjI0OSwicGF0aCI6Ii85MzUxMDA5NS8zMzk5NjY3NjQtMzlkZWM5MjctYjE0Zi00OTM3LTkzYWQtZTkyNzk2Y2RjZjMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDEzMDQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxZTNmMzg1Yjk3ODAwNWUxNmU1ZDQ0MzgxM2M3MDk5YmQ3NmE1ZWM0ZjNmMTViOWZhY2MxMmY1NTk0YjEyY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-pBDfeZKykXbdfDptArkhexmy7u5Xo4-VEW3-lclzVQ">
> ### Module
> stock, selling
> 
> ### Version
> Frappe Version - v15.29.2 ERPNext Version - v15.27.6
> 
> ### Installation method
> None
> 
> ### Relevant log output / Stack trace / Full Error Message.
> _No response_

you need to check time of purchase receipt / purchase invoice
sales invoice or delivery date time should be after the time of purchase receipt / purchase invoice

**Comment by PraveenkumarSubramani** [comment]
@rohitwaghchaure Yeah we have submitted serial and batch bundles without voucher no. After Cancel those serial and batch bundles, this issue solved.

**Comment by PraveenkumarSubramani** [comment]
@rohitwaghchaure Thanks!!!
