### ISSUE TITLE
Incorrect Status of Payment Request

### ISSUE THREAD

**Issue by nabinhait** [frappe/erpnext#41901]
### Issue

If we create a payment request and make the payment of the amount mentioned in Payment request then too it shows Partially Paid.

Steps to reproduce -

Create a Purchase Order of any Supplier for INR 10,000.

Submit the Purchase Order

Create Payment Request of INR 2,000 and submit it.

Create Payment Entry for the above mentioned Payment Request.

Now check the status of Payment Request, it shows as Partially Paid which should be Paid, as the complete payment against the request is done.

### Investigation

Currently, the status is shown based on payment status of reference document. Payment Entry is not linked directly to Payment Request, hence it's difficult to update status of Payment Request.

### Expected Solution

Maintain a link of Payment Request inside Payment Entry and update status based on it.

**Comment by sagarvora** [comment]
Working on this in https://github.com/frappe/erpnext/issues/42280
