### ISSUE TITLE
Bug ( ValueError: --enable-jpeg requested but jpeg not found, aborting.)

### ISSUE THREAD

**Issue by Ferohers** [frappe/erpnext#4192]
altan@ERP:~/frappe-bench$ bench update
Already up-to-date.
Collecting Pillow
  Using cached Pillow-3.0.0.tar.gz
Building wheels for collected packages: Pillow
  Running setup.py bdist_wheel for Pillow
  Complete output from command /home/altan/frappe-bench/env/bin/python -c "import setuptools;__file__='/tmp/pip-build-Zk0zs3/Pillow/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpvni2Ojpip-wheel-:
  Single threaded build, not installing mp_compile:1 processes
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/PIL
  copying PIL/TgaImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/ImageMorph.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/Hdf5StubImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/ExifTags.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/JpegPresets.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/__init__.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/_util.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/OleFileIO.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/Image.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/PyAccess.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/TarIO.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/ImageFont.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/GimpGradientFile.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/ImageSequence.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/ImagePath.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/WmfImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/PcdImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/IptcImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/ImImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/PcfFontFile.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/ImageColor.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/JpegImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/Jpeg2KImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/ImtImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/ContainerIO.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/FliImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/PsdImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/McIdasImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/BufrStubImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/GbrImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/PaletteFile.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/GimpPaletteFile.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/ImageTransform.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/ImageOps.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/ImageChops.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/ImageCms.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/PixarImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/PdfImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/WebPImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/TiffTags.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/PcxImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/ImageDraw2.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/GifImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/IcnsImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/PalmImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/MicImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/ImageMode.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/XpmImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/ImagePalette.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/ImageStat.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/PngImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/MpoImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/ImageTk.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/XbmImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/BmpImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/SgiImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/ImageFile.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/GdImageFile.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/FontFile.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/WalImageFile.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/features.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/SunImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/ImageQt.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/CurImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/ImageGrab.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/ImageDraw.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/IcoImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/ImageShow.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/ImageEnhance.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/DcxImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/ImageFilter.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/PSDraw.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/MspImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/TiffImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/MpegImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/PpmImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/BdfFontFile.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/FitsStubImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/ImageWin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/_binary.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/XVThumbImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/GribStubImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/SpiderImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/ImageMath.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/FpxImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  copying PIL/EpsImagePlugin.py -> build/lib.linux-x86_64-2.7/PIL
  running egg_info
  writing Pillow.egg-info/PKG-INFO
  writing top-level names to Pillow.egg-info/top_level.txt
  writing dependency_links to Pillow.egg-info/dependency_links.txt
  warning: manifest_maker: standard file '-c' not found

  reading manifest file 'Pillow.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'Pillow.egg-info/SOURCES.txt'
  copying PIL/OleFileIO-README.md -> build/lib.linux-x86_64-2.7/PIL
  running build_ext
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-Zk0zs3/Pillow/setup.py", line 767, in <module>
      zip_safe=not debug_build(),
    File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/home/altan/frappe-bench/env/local/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 175, in run
      self.run_command('build')
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
      self.run_command(cmd_name)
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/lib/python2.7/distutils/command/build_ext.py", line 337, in run
      self.build_extensions()
    File "/tmp/pip-build-Zk0zs3/Pillow/setup.py", line 515, in build_extensions
      % (f, f))
  ValueError: --enable-jpeg requested but jpeg not found, aborting.

  ----------------------------------------
  Failed building wheel for Pillow
Failed to build Pillow
Installing collected packages: Pillow
  Running setup.py install for Pillow
    Complete output from command /home/altan/frappe-bench/env/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-Zk0zs3/Pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-B1CE2V-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/altan/frappe-bench/env/include/site/python2.7/Pillow:
    Single threaded build, not installing mp_compile:1 processes
    running install
    running build
    running build_py
    running egg_info
    writing Pillow.egg-info/PKG-INFO
    writing top-level names to Pillow.egg-info/top_level.txt
    writing dependency_links to Pillow.egg-info/dependency_links.txt
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'Pillow.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'Pillow.egg-info/SOURCES.txt'
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-Zk0zs3/Pillow/setup.py", line 767, in <module>
        zip_safe=not debug_build(),
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/altan/frappe-bench/env/local/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run
        self.run_command('build')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
        self.run_command(cmd_name)
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/distutils/command/build_ext.py", line 337, in run
        self.build_extensions()
      File "/tmp/pip-build-Zk0zs3/Pillow/setup.py", line 515, in build_extensions
        % (f, f))
    ValueError: --enable-jpeg requested but jpeg not found, aborting.

    ----------------------------------------
Command "/home/altan/frappe-bench/env/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-Zk0zs3/Pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-B1CE2V-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/altan/frappe-bench/env/include/site/python2.7/Pillow" failed with error code 1 in /tmp/pip-build-Zk0zs3/Pillow
Please install these dependencies using the command:
sudo apt-get install -y libtiff5-dev libjpeg8-dev zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev python-tk
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 9, in <module>
    load_entry_point('bench==0.92', 'console_scripts', 'bench')()
  File "/home/altan/bench-repo/bench/cli.py", line 60, in cli
    bench()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/home/altan/bench-repo/bench/cli.py", line 240, in _update
    update(pull, patch, build, bench, auto, restart_supervisor, requirements, no_backup, upgrade, force=force)
  File "/home/altan/bench-repo/bench/cli.py", line 256, in update
    before_update(bench=bench_path, requirements=requirements)
  File "/home/altan/bench-repo/bench/utils.py", line 625, in before_update
    validate_pillow_dependencies(bench, requirements)
  File "/home/altan/bench-repo/bench/utils.py", line 633, in validate_pillow_dependencies
    exec_cmd("{pip} install Pillow".format(pip=pip))
  File "/home/altan/bench-repo/bench/utils.py", line 103, in exec_cmd
    raise CommandFailedError(cmd)
bench.utils.CommandFailedError: ./env/bin/pip install Pillow
altan@ERP:~/frappe-bench$ ^C
altan@ERP:~/frappe-bench$

**Comment by anandpdoshi** [comment]
Have a look at: https://discuss.erpnext.com/t/new-python-dependency-pillow-if-you-get-error-during-update-see-this-post/7900/5

Best,
Anand Doshi

ERPNext

**Comment by Ferohers** [comment]
Thank you for your patience :+1:
