### ISSUE TITLE
Charge Type "Actual" is not supported in Bill of Entry

### ISSUE THREAD

**Issue by parasonit** [frappe/erpnext#41980]
### Information about bug

**Describe the bug**
The Bill of Entry in ERPNext does not support the charge type "Actual". This limitation affects the accurate recording of actual GST charges in the Bill of Entry.

**To Reproduce**
1. Go to the 'Bill of Entry' form in ERPNext.
2. Try to add a charge with the type set to "Actual".
3. Observe that the system does not allow or recognize this charge type.

**Expected behavior**
The Bill of Entry should support the charge type "Actual" to allow for the proper entry and accounting of actual GST charges.

**Screenshots**
![image](https://github.com/frappe/erpnext/assets/118710551/60dadcf0-87d4-4230-9413-85c69781a5fe)
![image](https://github.com/frappe/erpnext/assets/118710551/e0669702-3d8f-4f1c-ac84-a0beaccce10f)

**Additional context**
Supporting the charge type "Actual" in the Bill of Entry is crucial for businesses that need to record actual incurred GST charges accurately. This feature would enhance the accuracy and functionality of the Bill of Entry module.

@vo

### Module

accounts

### Version

ERPNext: v15.27.2 (version-15)

Frappe Framework: v15.29.0 (version-15)

India Compliance: v15.7.5 (version-15)

### Installation method

None

**Comment by Nihantra-Patel** [comment]
It's an india-compliance issue, not ERPNext!

Same issue: https://github.com/resilient-tech/india-compliance/issues/2275
