### ISSUE TITLE
TCS calculation is not working

### ISSUE THREAD

**Issue by Quantbittech** [frappe/erpnext#42001]
### Information about bug

TCS is calclualted against the accumalated sales invoice value exceddeing 50,00,000.

Example - First I have received advance of 30,00,000 from customer. Now I am making the invoice of 30,00,000 for the same customer. I am getting the advance amonunt in the sales invoice so that the outstanding should be zero.

I want to calculate the TCS. When I made such etry ideally there should not be the TCS as TCS is only applicable when we cross the sales invoice value to 50 Lakh. In this case, system is calculating the TCS on 10 lakh as it is considering the sales invoice 30Lakh + advance amount 30Lakh and calculating as total of 60 Lakh and calculating TCS on 10 Lakh amount. Which is incorrect.

TCS set up is done as threshold value is 50,00,000 and cumulative value is 50,00,000. Rate applicable is 0.1%

This is tested on version 14 and version 15 and having the same issue. Also raised in office hour query and this is found as bug.

### Module

accounts

### Version

Frappe Version - 14
ERPNExt Version - 14.70

Also having the same issue with version 15 as well

### Installation method

FrappeCloud

**Comment by parasonit** [comment]
> ### Information about bug
> TCS is calclualted against the accumalated sales invoice value exceddeing 50,00,000.
> 
> Example - First I have received advance of 30,00,000 from customer. Now I am making the invoice of 30,00,000 for the same customer. I am getting the advance amonunt in the sales invoice so that the outstanding should be zero.
> 
> I want to calculate the TCS. When I made such etry ideally there should not be the TCS as TCS is only applicable when we cross the sales invoice value to 50 Lakh. In this case, system is calculating the TCS on 10 lakh as it is considering the sales invoice 30Lakh + advance amount 30Lakh and calculating as total of 60 Lakh and calculating TCS on 10 Lakh amount. Which is incorrect.
> 
> TCS set up is done as threshold value is 50,00,000 and cumulative value is 50,00,000. Rate applicable is 0.1%
> 
> This is tested on version 14 and version 15 and having the same issue. Also raised in office hour query and this is found as bug.
> 
> ### Module
> accounts
> 
> ### Version
> Frappe Version - 14 ERPNExt Version - 14.70
> 
> Also having the same issue with version 15 as well
> 
> ### Installation method
> FrappeCloud
> 
> ### Relevant log output / Stack trace / Full Error Message.
> _No response_

We are also facing same issue
