### ISSUE TITLE
Custom default letterhead not being used when 'attach document print' from email dialog

### ISSUE THREAD

**Issue by lansgt** [frappe/erpnext#42003]
### Information about bug

Even after setting the custom default letterhead via client script

frappe.ui.form.on('Doctype', {
    refresh(frm) {
        frm.doc.letter_head = "CustomDefault";
    }
});

Attached document print PDF is not being generated with the correct letterhead.

### Module

accounts

### Version

erpnext v15.27.7
frappe v15.30.0

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
First, you need to save the letterhead in the Doctype. To do this, you have to apply the client script and save the letterhead in the the field.

Please use it.


```
frappe.ui.form.on('Doctype', {
    before_save: function(frm) {
        frm.set_value("letter_head", "CustomDefault");
    }
});
```
