### ISSUE TITLE
Add Workspace button is missing

### ISSUE THREAD

**Issue by Rebaz-balisani** [frappe/erpnext#42010]
### Information about bug

When going to Build from the side bar and opening WORK SPACE list, its expected to show "add workspace" button, but its missing
![image](https://github.com/frappe/erpnext/assets/84542451/6adbc772-3dbe-4a9e-b0c5-5f0a04e4ea8f)

### Module

stock, buying, selling

### Version

ERPNext v15

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
I know this isn't a bug.

Check the documentation for Workspace 2.0.
https://frappeframework.com/docs/v14/user/en/desk/workspace#customization
Do not use the workspace doctype to add or update the blocks on the workspace; check the above link.

You have to create a workspace from the desk view.

![image](https://github.com/frappe/erpnext/assets/141945075/682140bd-0d8d-4946-b3db-59b18ffe1680)

If have a doubt, then please raise the issue on the [Frappe Forum](https://discuss.frappe.io/new). There are lots of thread in the forum

**Comment by Rebaz-balisani** [comment]
@Nihantra-Patel , the tutorials i was following is all v13 or v14 and yet and on the other side yet ERPNexts documentation not updated to mach the expresso version, thats why i thought it could be a bug. anyways thank you
