### ISSUE TITLE
Missing Letter Head >> Sales Invoice Batch Print

### ISSUE THREAD

**Issue by thida-bcn** [frappe/erpnext#42019]
### Information about bug

Sales Invoice Print format
![image](https://github.com/frappe/erpnext/assets/62122640/4e4b4b34-7522-4cd6-8369-ac5368a3651c)
Select multi invoices >> click action >> click print >> download pdf
missing letter head
![image](https://github.com/frappe/erpnext/assets/62122640/f0045b7b-4eb5-4b0f-b4b5-1b8b433bc29e)
![image](https://github.com/frappe/erpnext/assets/62122640/6235d771-d235-4472-a526-249ede05a77c)
![image](https://github.com/frappe/erpnext/assets/62122640/ea9fe573-f83c-4260-9822-94f128df1178)

### Module

selling

### Version

ERPNext: v15.27.1 (version-15)

Frappe Framework: v15.29.1 (version-15)

Frappe HR: v15.22.1 (version-15)

Payments: v0.0.1 (version-15)

Webshop: v0.0.1 (version-15)

### Installation method

None

**Comment by Nihantra-Patel** [comment]
Everything is working fine. No problems were encountered in the latest version 15.


https://github.com/frappe/erpnext/assets/141945075/4c288137-e0cb-484e-994a-0721f1922fd5

Maybe issue is in the wkhtmltopdf.

please install the correct / latest version of **wkhtmltopdf with qt patched**

https://wkhtmltopdf.org/downloads.html
