### ISSUE TITLE
Serial No Ledger

### ISSUE THREAD

**Issue by nakul80** [frappe/erpnext#42022]
### Information about bug

<img width="1071" alt="image" src="https://github.com/frappe/erpnext/assets/64956588/2589e349-f331-446c-82f4-300b6c78933e">

Why does a regular user need 'DocType' permission for viewing serial no ledger? This user has rights as Stock Manager

### Module

accounts, stock

### Version

ERPNext: v15.27.7 (HEAD)
Frappe Framework: v15.30.0 (HEAD)
India Compliance: v15.8.1 (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1768, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 921, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/query_report.py", line 223, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 921, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/query_report.py", line 109, in generate_report_result
    result = get_filtered_data(report.ref_doctype, columns, result, user)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/query_report.py", line 590, in get_filtered_data
    match_filters_per_doctype = get_user_match_filters(linked_doctypes, user=user)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/query_report.py", line 777, in get_user_match_filters
    filter_list = frappe.desk.reportview.build_match_conditions(dt, user, False)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/reportview.py", line 684, in build_match_conditions
    match_conditions = DatabaseQuery(doctype, user=user).build_match_conditions(as_condition=as_condition)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/db_query.py", line 937, in build_match_conditions
    frappe.throw(_("No permission to read {0}").format(_(self.doctype)), frappe.PermissionError)
  File "apps/frappe/frappe/__init__.py", line 645, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 610, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 561, in _raise_exception
    raise exc
frappe.exceptions.PermissionError: No permission to read DocType

(anonymous) @ request.js:473Understand this error

**Comment by Nihantra-Patel** [comment]
We tested. Everything is working fine. No problems were encountered in the latest version 15.


https://github.com/frappe/erpnext/assets/141945075/3c0f7373-25e4-453a-86f2-8fd90fe560ef

Again, check your user rights or any changes added, then revert it, because we checked in the new installed version.

**Comment by nakul80** [comment]
Tried everything you said. Please note one difference. The code for error shows that the error msg will show name of the DocType giving the error. It seems its asking for DocType (core) to be accessible. This error goes away for admin ac which has access to Doctype(core) 

_frappe.throw(("No permission to read **{0}**").format((self.doctype)), frappe.PermissionError)_

**Comment by nakul80** [comment]
Also, this user is able to view Serial No and Serial and Batch Bundle. Also can view Stock Ledger. Only Serial No Ledger is an error.

**Comment by Nihantra-Patel** [comment]
We tested, please check the video that i provided again. We just added the sales user role and checked the report to see if it was working properly.

**Comment by nakul80** [comment]
Reset all permissions for doctype serial no and serial and batch bundle and set user exactly like you. Logged in with that user and all light theme screenshots from that user

<img width="1000" alt="SCR-20240625-opox" src="https://github.com/frappe/erpnext/assets/64956588/ce0eb51f-a2d1-40ce-86b0-9fc45d0c48d3">

<img width="1000" alt="SCR-20240625-oprc" src="https://github.com/frappe/erpnext/assets/64956588/b49627b5-06b8-49ed-9735-3fc9fd89995c">

<img width="1000" alt="SCR-20240625-opzp" src="https://github.com/frappe/erpnext/assets/64956588/5cdba2b9-bd2f-4018-9129-4a6dfad9c973">

<img width="1000" alt="SCR-20240625-oqbf" src="https://github.com/frappe/erpnext/assets/64956588/dbf1dcda-fdab-4bd4-9b39-5d1c485d1ebc">

<img width="1000" alt="SCR-20240625-oqdu" src="https://github.com/frappe/erpnext/assets/64956588/16be1a11-2bc5-4f46-9249-fd61371a684e">

<img width="1000" alt="SCR-20240625-oqhk" src="https://github.com/frappe/erpnext/assets/64956588/97a9a00d-5c7b-436c-b62b-74304dc8cf45">

<img width="1000" alt="SCR-20240625-oqjs" src="https://github.com/frappe/erpnext/assets/64956588/470046c1-7bf6-4068-a57a-8b09fee88379">
