### ISSUE TITLE
"Customer Address" while website user are placing order with Cart.

### ISSUE THREAD

**Issue by fderyckel** [frappe/erpnext#4204]
Good day,
I login to the erpnext portal through social logins (fine with Google, but not with Facebook - https://github.com/frappe/erpnext/issues/4166)

Once I'm logged in and add items to the cart, I tried to place order.  It then says I have to enter Customer Address:

![screen shot 2015-10-21 at 07 11 53](https://cloud.githubusercontent.com/assets/7240992/10628421/7c429d20-77c5-11e5-9966-4c73d1072353.png)

I then click on "Manage Addresses" below the shipping address.  Create New address, indicate preferred bBlling and Shipping address.  Save.  Then go back to cart to try now to place order.  ... But same thing happen again: "Customer address is required."

![screen shot 2015-10-21 at 07 36 19](https://cloud.githubusercontent.com/assets/7240992/10628522/a4e79f54-77c6-11e5-8d09-5ba7e0615992.png)

I imagine it is also related to this issue?  https://github.com/frappe/erpnext/issues/4066

So how do we enter customer address?

**Comment by fderyckel** [comment]
OK thanks to community on forum, I got helped.  https://discuss.erpnext.com/t/customer-addresses-in-shopping-cart/6429/6

So could we improve this by having an automatic selected address once the first address is entered?  

Thanks

**Comment by jwrober** [comment]
Bump. This is over a year old, but still present in latest 7.1.x. This would be a very nice user experience enhancement for the shopping cart.

**Comment by umairsy** [comment]
Just checked and found that billing/shipping address is not auto-checked. 

![screen shot 2017-05-03 at 5 44 41 pm](https://cloud.githubusercontent.com/assets/910238/25660072/4a5071da-3028-11e7-8c6c-d304c98a1ae4.png)

Please check and confirm. If needed, feel free to reopen this issue.

**Comment by jwrober** [comment]
@umairsy - were you able to place the order? The issue/error crops up when you attempt to place the order without both addresses present.

**Comment by umairsy** [comment]
Yes. Just tried with one Address for which both Preferred for Billing and Preferred for Shipping was checked. I was able to complete the order with that one address.

**Comment by umairsy** [comment]
I think this is the root cause.
https://github.com/frappe/erpnext/issues/8694
