### ISSUE TITLE
Batch Items Valuation Rate calculation difference in v14 vs V15

### ISSUE THREAD

**Issue by moizsami** [frappe/erpnext#42072]
### Information about bug

First of all I am not sure this is a bug or not. My issue is we were using 'Moving Average' on v14 and we had batch items.

During Manufacturing entries, the system use to pick the average valuation rate for the raw materials (not aware of the backend procedure).

Once I upgraded to V15, the similar exact entry once done on it, the raw material valuation rate is completely different. Again I do not know how these calculations are done.

Also during the creation of this record the value appears correct, it is only after saving/submitting that the valuation or this raw material gets changed to another number.

How to tackle this, as prod system is up and the process is getting affected.

@rohitwaghchaure  Sorry I am tagging you but I saw your videos for the batch and some posts, still it is very unclear to me.

### Module

stock, manufacturing

### Version

ERPNext: v15.28.1 (version-15)

Frappe Framework: v15.32.0 (version-15)

### Installation method

FrappeCloud

**Comment by rohitwaghchaure** [comment]
@moizsami we have forced Use Batch-wise Valuation for the batches from the version 15. Is this causing the issue? In my opinion for the batched item the valuation rate should be based on the Batch-wise

**Comment by moizsami** [comment]
@rohitwaghchaure  Yes, the issue is from client side, that suddenly the manufactured items are having different valuation rates. It is affecting their profit calculations.

Can you explain how the batch wise calculation is done so I could propose them the idea? I had chosen FIFO in stock batch setting, so is it taking the FIFO calculation?

Also, I would suggest if there is an option where user can select what how the calculation of batch Items should be calculated. As new users might not have an issue, but those coming from older versions are use to something else.

For now I had no choice but to rollback client's environment to v14 as they were not accepting the change in valuation rate during manufacturing entry.

**Comment by rohitwaghchaure** [comment]
@moizsami I am still not able to understand the problem, maybe can you explain with the example what customer is expected. Also if you have purchased support plan, please create a support ticket so that I can able to see the customer's data as well.

**Comment by moizsami** [comment]
@rohitwaghchaure  we are on the 25 USD plan so unfortunately I cannot open a ticket.

On v14. although we had multiple batches, but during the manufacturing entry when raw material were consumed, they used to have the average rate of the Item which can be seen on stock balance report as well.

On v15: During creation of the manufacturing entry it fetches the average rate of the Item, but then according to the batches selected. while saving it changes the valuation rate (I am assuming its taking the FIFO calculation into consideration)

So suppose the Item A has valuation rate: 80 EGP on stock balance report under Raw Material warehouse
In the manufacturing entry, that item's rate will be changed while saving to 127 EGP as maybe a certain batch's valuation rate was higher than others.

Providing figures for all batches will be a bit difficult as there are multiple batches with different qty and price variations. but let me know what exactly is needed and i will surely provide.

**Comment by rohitwaghchaure** [comment]
Can you share the site name and stock entry id

**Comment by moizsami** [comment]
@rohitwaghchaure 

I still have the v15 environment and v14 also sharing both details:

V15:
URL: https://glabels.frappe.cloud/
stock entry: MAT-STE-2024-00210

Now I created v14 url for them to work on:
URL: https://glabels14.frappe.cloud/
stock entry: MAT-STE-2024-00211

check the Item SG103 as an example..how the valuation rate is different in both.

**Comment by rohitwaghchaure** [comment]
@moizsami We have [fixed](https://github.com/frappe/erpnext/pull/42186/files) the issue and we'll release the fix in the next week (Wednesday). After the release, kindly update your site and do reposting of items using Repost Item Valuation having incorrect valuation rate.
