### ISSUE TITLE
Unable to set time/duration for tasks

### ISSUE THREAD

**Issue by justinlusg** [frappe/erpnext#4209]
![image](https://cloud.githubusercontent.com/assets/12539216/10632003/1fa8bcf8-7814-11e5-8340-e547c0901c09.png)

A suggestion, for project tasks it would be good if users are able to allocate the time/duration for each task as well. Currently, all tasks are default to 12mn and when it display on the calendar, it looks confusing to users.

**Comment by chdecultot** [comment]
Hi @justinlusg,

This issue seems to be solved. You can select the expected duration, a start and end date in each task.

I am therefore closing this issue.
