### ISSUE TITLE
Issue while creating a pick list with promotional scheme

### ISSUE THREAD

**Issue by rknroot** [frappe/erpnext#42117]
### Information about bug

**Information about bug**
While creating Picklist from Sales order with promotional scheme with Product Discount Slabs if the stock is not available the free qty combination is not selected. Just available qty is selected and after creating delivery note the sales order qty is fetched and throwing warning Serial No / Batch No are mandatory for Item.

**Steps to Reproduce:**
1. Create Item with Batch number & Expiry Date enabled (Only Batch Enabled)
2. Make a Stock receipt or Purchase Receipt for 100 Qty
3. Create Sales Order with promotional scheme with Product Discount Slab (10 + 1 Scheme - 100 qty SO 10 Qty free)
4. Create Picklist Insufficient Stock warning will show - Only available stock is fetched in Picklist
5. Create Delivery Note, Full SO qty is taken in Delivery note and throwing warning Serial No / Batch No are mandatory for Item.
![Scheme picklist bug](https://github.com/frappe/erpnext/assets/9102676/60a37e90-96ed-49d5-90f3-c8dd14406510)

### Module

selling

### Version

ERPNext: v15.28.2 (HEAD)

Frappe Framework: v15.32.0 (HEAD)

### Installation method

None

**Comment by rohitwaghchaure** [comment]
Ideally free item should be available otherwise there is no point to run promotional schemes. If you don't want to give free item in the delivery note then remove free item and enable ignore pricing rule
