### ISSUE TITLE
Creation of Sales Order from Quotation Error when quotation_to is not Lead

### ISSUE THREAD

**Issue by casesolved-co-uk** [frappe/erpnext#42136]
### Information about bug

The following lines need to be updated to match the new options for `quotation_to`, i.e. Prospect:

https://github.com/frappe/erpnext/blob/99f2735ad3440aa3690bb514b32d7d9610753041/erpnext/selling/doctype/quotation/quotation.py#L516-L523

@ruthra-kumar 
Related: #41040

### Module

selling, CRM

### Version

ERPNext: v15.22.2

![Screen Shot 2024-07-01 at 19 09 40](https://github.com/frappe/erpnext/assets/110036763/906c94be-9efa-4457-a2d3-9efe822c5f4c)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
{"exc_type":"DoesNotExistError","_server_messages":"[\"{\\\"message\\\": \\\"Lead REDACTED not found\\\", \\\"title\\\": \\\"Message\\\", \\\"indicator\\\": \\\"red\\\", \\\"raise_exception\\\": 1, \\\"__frappe_exc_id\\\": \\\"94a9bc1b8e4484bf38f08b1b6b958fba5b07ddd98795be65bd52871c\\\"}\"]"}
```

**Comment by Nihantra-Patel** [comment]
Kindly upgrade your version 15 because everything is working fine. No problems were encountered in the latest version 15.


https://github.com/frappe/erpnext/assets/141945075/06bf00bb-15eb-41e5-8d8e-0356ebb8b5b6

**Comment by casesolved-co-uk** [comment]
You tested from a LEAD not a PROSPECT

@Nihantra-Patel

**Comment by Nihantra-Patel** [comment]
share the video, or process flow and first update your version and then test it.

**Comment by casesolved-co-uk** [comment]
1. Create Prospect
2. Create Quotation
3. Create Sales Order

**Comment by casesolved-co-uk** [comment]
I don't need to test it, the above referenced code is from v16 develop and does not cater for Prospects.

@Nihantra-Patel

**Comment by Nihantra-Patel** [comment]
issue is in v15 or v16?

**Comment by casesolved-co-uk** [comment]
All versions

**Comment by Nihantra-Patel** [comment]
All version 😅

Let me check!
