### ISSUE TITLE
FIFO Does Not Consider Per Batch ID Value

### ISSUE THREAD

**Issue by jof2jc** [frappe/erpnext#4217]
FIFO should look-up per batch-id value for all batch items transactions. If not, we will get wrong costing calculation. 

So I can say all ERPNext customers is having wrong costing values for batch items.

I didn't test for serialized items.

**Comment by jof2jc** [comment]
@nabinhait I think this is crucial costing issue..would you consider this on next updates?

**Comment by 18alantom** [comment]
On it, [#26914](https://github.com/frappe/erpnext/pull/26914)
