### ISSUE TITLE
Purchase invoice page not loading.

### ISSUE THREAD

**Issue by rs115199789** [frappe/erpnext#42187]
### Information about bug

Hello, Today i tried to open a purchase invoice however the purchase invoice list is showing but when i try to open an invoice it's only showing the search bar/ rest everything is white blank.
The server is hosted on Frappe Cloud and i dont have the code access.
Also if i try to open the same with an account which have admin access everything is showing.

Note:- The other roles also have access of Purchase invoice, it's just this issue came suddenly, i haven't made any changes in the system too.

![asddas](https://github.com/frappe/erpnext/assets/132902023/70abc369-ec17-4e03-aa3e-fb52bfac197c)

Thank You 

### Module

accounts

### Version

Frappe Framework: v14.77.2 (HEAD)

ERPNext: v14.70.8 (HEAD)

### Installation method

FrappeCloud

**Comment by Nihantra-Patel** [comment]
Solved: https://discuss.frappe.io/t/purchase-invoice-page-not-loading/128114/9?u=ncp
