### ISSUE TITLE
Android App: Application Error

### ISSUE THREAD

**Issue by yashodhank** [frappe/erpnext#4218]
Self-hosted ERPNext version on experimental development server:
Installed Apps
ERPNext: v6.6.4
Frappe Framework: v6.6.1

Application Error
net::ERR_FILE_NOT_FOUND (file:///index.html)

Screenshot:
![erpnext_android_app_1_screenshot_2015-10-23-10-37-00](https://cloud.githubusercontent.com/assets/1083792/10685673/4e94a038-797a-11e5-91b1-826438894b76.png)

**Comment by ahmad18189** [comment]
is there any update ?

**Comment by guojian83** [comment]
I have the same problem

**Comment by rmehta** [comment]
Seems like a fixed issue. Please raise another issue if you still have this problem.

**Comment by guojian83** [comment]
The latest version works.

**Comment by akashdubey22** [comment]
Same error again in v11 when I open print invoice or any voucher.

Akash
