### ISSUE TITLE
[Bug] Could not find DocType: Sales Order - Domestic

### ISSUE THREAD

**Issue by JEEVAN28** [frappe/erpnext#42196]
### Information about bug

Hello,
I am trying to duplicate Sales Order Doctype and given name as Sales Order - Domestic, but when I try to save it throws error as below

![image](https://github.com/frappe/erpnext/assets/12723595/8c04ef29-4edf-4d47-a63c-78d73a309a5c)

![image](https://github.com/frappe/erpnext/assets/12723595/84ca2e01-eae8-4357-bc41-2345b22081cf)

### Module

selling

### Version

Frappe Version - 15
ERPNext Version - 15

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.
![image](https://github.com/frappe/erpnext/assets/12723595/4dc67062-4522-4324-9160-8308e3198c75)

_No response_

**Comment by Nihantra-Patel** [comment]
Already, the issue has been raised in the frappe. if you have to make a new doctype and manually add the field. As per now, you can't duplicate the doctype.
