### ISSUE TITLE
ERP , App and website

### ISSUE THREAD

**Issue by prash4** [frappe/erpnext#4219]
We are in process of making an App for our products  , and also updating the website .
So is there a way or which technologies we should use to make the App and the website , so that we can integrate it with ERP next .
So when we update or add any product it should get update in ERP next masters , APP and the website 

Is there a way to do it  ?

**Comment by yashodhank** [comment]
@prash4 ERPnext and Frappe does have its own REST API here: https://frappe.io/help/rest_api
Docs: https://docs.erpnext.com/current

Please follow the posting guideline: https://github.com/frappe/erpnext/blob/develop/CONTRIBUTING.md

Note: If you have questions on how to use ERPNext or want help in customization or debugging of your scripts, please post on https://discuss.erpnext.com. This is only for bug reports and feature requests.

Please close this issue for now and open a thread on https://discuss.erpnext.com
Thank you
