### ISSUE TITLE
Bank Reconciliation Module

### ISSUE THREAD

**Issue by nitesh-nsuregrowth** [frappe/erpnext#42203]
### Information about bug

Hello , could anyone let me know if they are also facing the same issue.
I somehow guess is this a bug or there is something wrong I am doing

I am trying to match a sales invoice booked from the ‘Bank reconciliation Tool”
However, when I am trying to do so the sales invoices booked are not reflecting.
What is the way to match these transactions ??

Picture 1![image](https://github.com/frappe/erpnext/assets/170872428/9f88b91f-674f-4e79-b572-d6c837c9d854)

### Module

accounts, other

### Version

Version 15

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
Hello , could anyone let me know if they are also facing the same issue.
I somehow guess is this a bug or there is something wrong I am doing

I am trying to match a sales invoice booked from the ‘Bank reconciliation Tool”
However, when I am trying to do so the sales invoices booked are not reflecting.
What is the way to match these transactions ??

Picture 1
```

**Comment by git529** [comment]
> ### Information about bug
> 
> Hello , could anyone let me know if they are also facing the same issue. I somehow guess is this a bug or there is something wrong I am doing
> 
> I am trying to match a sales invoice booked from the ‘Bank reconciliation Tool” However, when I am trying to do so the sales invoices booked are not reflecting. What is the way to match these transactions ??
> 
> Picture 1![image](https://private-user-images.githubusercontent.com/170872428/346267939-9f88b91f-674f-4e79-b572-d6c837c9d854.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3MzMxNTIsIm5iZiI6MTcyMjczMjg1MiwicGF0aCI6Ii8xNzA4NzI0MjgvMzQ2MjY3OTM5LTlmODhiOTFmLTY3NGYtNGU3OS1iNTcyLWQ2YzgzN2M5ZDg1NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNFQwMDU0MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOTZlNzg2MDkwZDNkZmRlMzYxYTE2ODNhNDMxMDUxMzBiZGQ3YTIxZmI3YjYxNTJjMzlhY2Q2ZmJmZWQ2ZWQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.F7gctePyULVIFADUe86MusMmQPJkA5PZ3DKAVpTMRUc)
> ### Module
> 
> accounts, other
> ### Version
> 
> Version 15
> ### Installation method
> 
> FrappeCloud
> ### Relevant log output / Stack trace / Full Error Message.
> 
> ```shell
> Hello , could anyone let me know if they are also facing the same issue.
> I somehow guess is this a bug or there is something wrong I am doing
> 
> I am trying to match a sales invoice booked from the ‘Bank reconciliation Tool”
> However, when I am trying to do so the sales invoices booked are not reflecting.
> What is the way to match these transactions ??
> 
> Picture 1
> ```

Generally, you generate a payment entry against the sales invoice, and then reconcile the bank transaction against the payment entry.

**Comment by barredterra** [comment]
Matching unpaid Sales Invoices is not supported in ERPNext. If that's what you're looking for, check out the Bank Reconciliation Tool in https://github.com/alyf-de/banking .

 (The checkbox is meant for Sales Invoices that at the same time constitute a payment.)
