### ISSUE TITLE
SALES INVOICE TEMPLATESSSSS

### ISSUE THREAD

**Issue by psquare6271** [frappe/erpnext#42209]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Nihantra-Patel** [comment]
This issue lacks sufficient information about the feature request. Whenever you create a new issue for a feature request or bug, please provide complete details of the feature you want and your requirements. If you are reporting a bug, share a screenshot or a video of the error.
