### ISSUE TITLE
Error while creating new employee 

### ISSUE THREAD

**Issue by tejasmarvania** [frappe/erpnext#42210]
### Information about bug

Error while creating new employee.
![image](https://github.com/frappe/erpnext/assets/55729741/4e802fbd-cfb0-4dcc-8f24-261d48a0b554)

The user from which I am creating the employee has all the permission
![image](https://github.com/frappe/erpnext/assets/55729741/fb7fecf4-777f-48b6-8ccb-73d64a0c3629)
![image](https://github.com/frappe/erpnext/assets/55729741/0ad83829-6545-4844-bd80-4676dd331b58)

### Module

HR

### Version

Frappe Builder: v1.10.1 
ERPNext: v15.29.2 
Frappe Framework: v15.33.3 
Frappe Whatsapp: vv1.0.7 
Frappe HR: v15.23.1 
India Compliance: v15.10.0
Frappe Insights: v2.2.2 
Print Designer: v1.4.0 

### Installation method

FrappeCloud

**Comment by Nihantra-Patel** [comment]
I know this isn't a bug because it's a user permission issue.

Please go to the User Permission doctype and check the employee-related permission for the logged user. if any permission is applied then remove it. then reload and check it.
