### ISSUE TITLE
Reports not working at all in 15.29.2

### ISSUE THREAD

**Issue by prononext** [frappe/erpnext#42239]
### Information about bug

When trying on any doctype I cannot see any report view. Not the system ones, not the custom ones and also not when just switching to the report view. 

Browser Console Error Provided:

### Module

accounts, projects, support

### Version

- ERPNext: v15.29.2
- Frappe Framework: v15.33.3
- Frappe HR: v15.23.1
- Payments: v0.0.1
- Print Designer: v1.4.0

### Installation method

docker

### Relevant log output / Stack trace / Full Error Message.

```shell
Crome:

report_view.js:225 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'find')
    at frappe.views.ReportView.get_count_element (report_view.js:225:34)
    at frappe.views.ReportView.freeze (list_view.js:505:9)
    at frappe.views.ReportView.refresh (base_list.js:491:8)
    at frappe.views.ReportView.refresh (list_view.js:312:16)
    at frappe.views.ReportView.refresh (utils.js:890:19)
    at onload (task__custom_list_js:21:18)
    at frappe.listview_settings.Task.onload (task__custom_list_js:195:9)
    at frappe.views.ReportView.setup_result_area (report_view.js:79:41)
```

Firefox:
```
Uncaught (in promise) TypeError: this.$paging_area is undefined
    get_count_element report_view.js:225
    freeze list_view.js:505
    refresh base_list.js:491
    refresh list_view.js:312
    throttle utils.js:890
    onload task__custom_list_js:21
    onload task__custom_list_js:195
    setup_result_area report_view.js:79
report_view.js:225:15
Uncaught TypeError: this.$paging_area is undefined
    get_count_element report_view.js:225
    freeze list_view.js:505
    refresh base_list.js:491
    refresh list_view.js:312
    throttle utils.js:890
    refresh_list_view base_list.js:659
    s utils.js:905
```
```

**Comment by Nihantra-Patel** [comment]
> at onload (task__custom_list_js:21:18)

If any applied the listview client script then remove or comment out it. because everything is working fine. No problems were encountered in the latest version 15.


https://github.com/frappe/erpnext/assets/141945075/73f6cb62-aea1-4bdb-83d7-e56ee9c7a750

**Comment by prononext** [comment]
If you still are looking for a working Reports view Feature and also are using Clients scripts on the List view. You might have to do a exeption and check to not apply the Client view when reports are active like this:

`  if (!frappe.route_options || frappe.route_options.view != 'Report') `
