### ISSUE TITLE
Multiple Expenses Included in Valuation Accounts

### ISSUE THREAD

**Issue by sliska** [frappe/erpnext#4223]
Hi, 

It'd be good to be able to have more than 1 account of type "expenses included in valuation" in order to be able to direct expenses in landed cost vouchers to a specific account rather than sending them automatically to the default account.

thanks,
Sofia

**Comment by umairsy** [comment]
Expense Included in Valuation is just for the adjustment purpose. On receipt of bill from the vendor, you can create separate Purchase Invoice to book additional expenses. Also, you can define more specific Expense Accounts in the Purchase Invoice.
