### ISSUE TITLE
The Show Opening Entries in General Ledger does not work

### ISSUE THREAD

**Issue by manalErpnext** [frappe/erpnext#42230]
### Information about bug

when I use the filters of date with the Show Opening Entries filter
example:
when you enter the from date 25-03-2024, to date 25-03-2024 and checked the third filter
They display all the operations with opening entries
and
when you did not check the third filter
They display all the operations without opening entries
![image](https://github.com/frappe/erpnext/assets/164166793/a322238c-9a94-464e-94a1-52d2a14aa780)

### Module

accounts

### Version

ERPNext: v15.29.2 (version-15)
Frappe Framework: v15.33.3 (version-15)
Frappe HR: v15.23.1 (version-15)
Custom app: v0.0.1 (develop)
Payments: v0.0.1 (develop)

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
"Show Opening Entries" filter works like this:

- When checked, it shows all entries, including opening entries, for the selected date range.
- When unchecked, it shows only regular entries, excluding opening entries, for the selected date range.

This behavior is normal and not a bug.

Any GL Entry that has its 'Is Opening' field set is considered an opening entry, regardless of the date it falls on. This means that the 'Is Opening' status determines whether an entry is an opening entry, not the date.
