### ISSUE TITLE
Quality Inspection Reference type for Subcontracting Reciept

### ISSUE THREAD

**Issue by rohitgonsalves** [frappe/erpnext#42267]
**I do file Quality inspections for reference types**

1. Purchase Invoice
2. Purchase Receipt
3. Sales Invoice 
4. Delivery Note
5. Stock Entry
6. Job Card

The problem is when we have a Subcontracting receipt against subcontracting Orders, It is difficult to link the Quality inspection connected to this receipt.

**Describe the solution you'd like**
Reference Type option to be added as Subcontracting Receipt.

**Describe alternatives you've considered**
I am filing this incoming quality inspection against send to subcontractor stock entry.

**Additional context**
I tried to customize this doc type Quality Inspection but the Reference type options are not allowed to change,

**Comment by Nihantra-Patel** [comment]
Feature already developed

Please check the PR: https://github.com/frappe/erpnext/pull/36786

Subcontracting Receipt is available in the Quality Inspection.

Please check it.


https://github.com/user-attachments/assets/df2b394a-9ce6-4867-97cd-fc31eda3fe6d
