### ISSUE TITLE
Documentation Page

### ISSUE THREAD

**Issue by m23am** [frappe/erpnext#42293]
### Information about bug

Doc page simply broken: https://docs.erpnext.com

Can someone have a look asap? I'm trying to sell the idea to my client's, this broken page is a deal killer )

### Module

other

### Version

latest

### Installation method

None

**Comment by Nihantra-Patel** [comment]
Thank you for letting us know about this problem. We resolved the issue.

So please reload <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>R</kbd> and check it.

![image](https://github.com/user-attachments/assets/249b147c-c6fa-4d94-9cdc-cbdec6695c35)
