### ISSUE TITLE
Total Wth not calculating

### ISSUE THREAD

**Issue by Noreen222** [frappe/erpnext#42328]
![Screenshot_15-7-2024_92255_dev14-csf-tz aakvaerp com](https://github.com/user-attachments/assets/49cb1219-0436-4384-bc31-b57580ccc6b4)
### Information about bug

Hello everyone,

I have an issue here.

Below is my code for calculating Total WTH:

{% set total_wth_amount = 0 %}

{% for item in doc.items %}
{% if item.item_name == “Rent” or item.item_name == “Science TextBook” or item.item_name == “WTH item” %}
{% set wth_rate = 5 %}
{% else %}
{% set wth_rate = 0 %}
{% endif %}

{% if wth_rate > 0 %}
{{ item.item_name }} item amount is
 {{ item.get_formatted(“base_net_amount”, doc) }}  

Tax withheld at  {{ wth_rate }}  %
{% set wth_amount = item.base_net_amount * (wth_rate / 100) %}
  {{ frappe.format_value(wth_amount, {‘fieldtype’: ‘Currency’, ‘options’: ‘TZS’}) }}  

{% set total_wth_amount = total_wth_amount + wth_amount %}
{% endif %}
{% endfor %}

Total withheld tax amount is:
  {{ frappe.format_value(total_wth_amount, {‘fieldtype’: ‘Currency’, ‘options’: ‘TZS’}) }}  

It does calculate Total Wth
Anyone to help debug?

Regards.

### Module

accounts

### Version

Frappe Version: 14.7.0

### Installation method

None

**Comment by Nihantra-Patel** [comment]
Resolved: https://discuss.frappe.io/t/total-wth-not-reflecting/128737/4?u=ncp


If have a bug then report it otherwise If have a doubt then please raise it in the [frappe forum](https://discuss.frappe.io)
