### ISSUE TITLE
export-fixture issue for Role Permission for Page and Report

### ISSUE THREAD

**Issue by Rebaz-balisani** [frappe/erpnext#42320]
### Information about bug

I have created some roles such as **OWNER** and i wanted to give some permissions for reports such as **Gross Profit** in the **Role Permission for Page and Report** it was working perfectly but this time i wanted to move these changes to my custom app so i can move it to the production server. inside the app folder as usual i did "**bench export-fixtures**" everything went smoothly even after i pushed it to  github it was ok in the production server i did "git pull" and it was perfectly working but once i did "**bench --site mysite.com migrate**" it gave me  a long error. later on i went to the exported fixtures and i checked the set_role_for is empty please check the attachments

[err.txt](https://github.com/user-attachments/files/16216455/err.txt)
![image](https://github.com/user-attachments/assets/70d3c58c-7256-4216-9773-4ffd18e6f2c5)
![image](https://github.com/user-attachments/assets/cf2f71ae-39be-49af-99cc-ddb69d39da9b)

### Module

other

### Version

erpnext 15.29.3
frappe 15.34.1

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
First thing, you can't export the role permission for page and report. because it's a page, not a doctype. if you want to export the custom permission that you applied for page and report then you have to export the Custom DocPerm.

![image](https://github.com/user-attachments/assets/e4357698-db8f-4af5-880e-da42d58b4119)

**Comment by Rebaz-balisani** [comment]
I have given access of many reports(not doctypes) to the custom role that I created, so i exported from the Custom Docperms and imported to my production server, I checked it has not moved any of my permissions to the reports(Role Permission for Page and Report). there is no documentation so I could follow up of how to export. thank you
