### ISSUE TITLE
v15.29.4 - shows version as v15.29.3

### ISSUE THREAD

**Issue by smtwkla** [frappe/erpnext#42324]
### Information about bug

I ran frappe/erpnext:v15.29.4 container and find that the version shown in the About page is v15.29.3 instead of .4

### Module

other

### Version

v15.34.1 - v15.29.4

### Installation method

docker

**Comment by bobotdls** [comment]
same with me still on ERPNext: v15.29.3
but my frappe update into new version

**Comment by bobotdls** [comment]
Hi Nihantra-Patel,

Sorry I a beginner on this frappe, how and where do I fix that Update __init__.py to 15.29.4

**Comment by Nihantra-Patel** [comment]
A new version has been released so update it.

![image](https://github.com/user-attachments/assets/e91a82a9-bb88-4909-8569-b51e854721fc)
