### ISSUE TITLE
Paid Amount field in "New Payment Entry" not working properly

### ISSUE THREAD

**Issue by primalstudio** [frappe/erpnext#42347]
### Information about bug

The Paid amount field does is not working properly, when writing a number like: 20800 the field only register the first two numbers.
the maximum digits recorded is three digits.
![Captura de pantalla 2024-07-15 090545](https://github.com/user-attachments/assets/43289008-13b1-4103-8119-7b84d645c2f8)

![image](https://github.com/user-attachments/assets/3309a90d-d880-4c01-8e30-ddfb07e3750c)

### Module

accounts

### Version

Frappe V14.
Erpnext V14
![image](https://github.com/user-attachments/assets/f97291d6-6484-4661-bfae-f0d36311014e)

### Installation method

FrappeCloud

**Comment by Nihantra-Patel** [comment]
We tested in the lastest version:

```
ERPNext: v14.70.8 (version-14)
Frappe Framework: v14.77.7 (version-14)
```

Everything is working fine. No problems were encountered in the latest version 14.

Please check it.


https://github.com/user-attachments/assets/7fc0838e-d8de-49ba-b45e-50159423906e

Kindly upgrade to version 14 and test it.

if the issue occurs then raise the support ticket on [Frappe Cloud](https://support.frappe.io/).

**Comment by primalstudio** [comment]
Hi,

thanks for your reply,
ill record a video so you can see where the problem is,
maybe the problem has to do with the MXN currency only.

https://github.com/user-attachments/assets/b1cc57f2-261b-49a1-b6a8-24f04cf8eb29

thanks in advance., looking forward
