### ISSUE TITLE
Item Price Import  Scheduler is inactive. Cannot import data.

### ISSUE THREAD

**Issue by dtxman** [frappe/erpnext#42346]
### Information about bug

![image](https://github.com/user-attachments/assets/3dce7038-7603-4ab6-891a-7f2a9f7a14dc)

### Module

other

### Version

ERPNext: v15.29.3

### Installation method

None

**Comment by Nihantra-Patel** [comment]
I know this isn't a bug, because your scheduler is inactive. so please enable the scheduler using the below command:

```
bench --site your-sitename.com enable-scheduler
bench --site your-sitename.com migrate
```

**Comment by dtxman** [comment]
![image](https://github.com/user-attachments/assets/b03eb009-140d-43a6-a7e6-0c788c3e3e1a)
![image](https://github.com/user-attachments/assets/c1275037-2cb7-4dab-a986-bce5af9c69fd)

**Comment by Nihantra-Patel** [comment]
stop the bench and again start it. (restart bench)

**Comment by dtxman** [comment]
Please see the update screenshot, I did this command before reporting, I still get the same result.

**Comment by Nihantra-Patel** [comment]
Please check the thread: https://discuss.frappe.io/t/data-import-the-scheduler-is-inactive/104708/2

**Comment by dtxman** [comment]
thanks for support, was able to import, I used the command below

bench --site site_name set-config pause_scheduler 0
