### ISSUE TITLE
Cloud version of website is different from Selfhosted one

### ISSUE THREAD

**Issue by sane5ek** [frappe/erpnext#42359]
### Information about bug

Hello!

I tried cloud version of your application, and it differs from one I hosted with your docker repository https://github.com/frappe/frappe_docker

Cloud version:
![image](https://github.com/user-attachments/assets/4bb7a940-09d1-408e-b120-2ec7250142f4)

Selfhosted version:
![image](https://github.com/user-attachments/assets/878242e7-1761-4cbb-b369-8afc0cb80181)

About tab Cloud version:
![image](https://github.com/user-attachments/assets/99c6435d-5dec-42da-a7fa-272600b5ab4e)

About tab Selfhosted version:
![image](https://github.com/user-attachments/assets/0a474ea6-8fef-42c6-95ae-6252e1a21848)

The question is, why are there more options in the left menu on the cloud version than in the selfhosted version?

### Module

other

### Version

Frappe Framework: v15.34.1

### Installation method

None

**Comment by Nihantra-Patel** [comment]
I know this isn't a bug.

Because the cloud version provides default apps like ERP, print designer, and possibly email delivery service, on a self-hosted server, you have to install these apps manually. It only provides the base app(frappe) by default.
