### ISSUE TITLE
Earlier HSN was coming automatically by FIFO in Delivery Note.

### ISSUE THREAD

**Issue by Sunil-Codes** [frappe/erpnext#42350]
### Information about bug

In version 14 when I was creating the delivery note from a sales order or directly the batch nos were coming automatically now I have to do this manually for my 100 items in the delivery note what is the solution for the same?

![image](https://github.com/user-attachments/assets/11d06369-f877-4d8a-b435-1d61866003d3)

### Module

selling

### Version

ERPNext: v15.27.1 (HEAD)

Frappe Framework: v15.29.1 (HEAD)

### Installation method

None

**Comment by Nihantra-Patel** [comment]
The functionality has been completely upgraded from version 14 to 15, so many features have been changed.

If you want to automatically pick serial/batch bundles, please enable 'Auto Create Serial and Batch Bundle' in Stock Settings.

![image](https://github.com/user-attachments/assets/83045541-6bc8-462c-a721-d8a9f6f7b0f5)


When you submit the Delivery Note then it will take automatically.

![image](https://github.com/user-attachments/assets/b7f7434a-0813-410c-9a4a-3460dfb43466)


![image](https://github.com/user-attachments/assets/540ec387-3f7c-4881-9299-6ff044dc2184)


Please check the [documentation](https://docs.erpnext.com/docs/user/manual/en/serial-and-batch-bundle)

Please check the [video](https://www.youtube.com/watch?v=-VjZvRtdjDQ).
