### ISSUE TITLE
Filter user by role

### ISSUE THREAD

**Issue by deep1991** [frappe/erpnext#4235]
Right now, In HR module in Employee doctype, for leave approver child table we get all user in drop down and not just user who has role "Leave Approver". But it should be just those user who has this role of "Leave Approver" and not all the user of the system.

**Comment by vjFaLk** [comment]
I cannot replicate this on my build.

**Comment by vjFaLk** [comment]
My bad, I was checking in the Leave Application form. I can replicate the issue.

**Comment by vjFaLk** [comment]
Fixed

**Comment by deep1991** [comment]
Thanks for fixing the issue. :+1:
