### ISSUE TITLE
Project Status Automatic Update Issue

### ISSUE THREAD

**Issue by sjoulaei** [frappe/erpnext#42363]
### Information about bug

This update (https://github.com/frappe/erpnext/pull/42204) has caused the following issues: 

1- All of the old completed projects that had incomplete tasks in them have been re-opened. (mess for us but possibly desired outcome of this recent change) 

2- Any project that has all tasks in it completed is closed off automatically (this is problematic as projects may need other non-task items to finalise before they can be closed) 

3- Any project that doesn't have any tasks in it can not be closed off (definitely a problem, as not every project in our use case has tasks in it)

Issues started as a result of: https://github.com/frappe/erpnext/pull/42204

### Module

projects

### Version

ERPNext: v15.29.3
Frappe Framework: v15.34.1

### Installation method

FrappeCloud

**Comment by vorasmit** [comment]
> All of the old completed projects that had incomplete tasks in them have been re-opened.

This PR just updates the project status when a task is created or updated. Should not have automatically opened closed projects.

> project that has all tasks in it completed is closed off automatically
> Any project that doesn't have any tasks in it can not be closed off

This has been original design. Current implementation is just completing it. Did you know you could choose % completion method as manual and update the completion status manually like you want?

Default method is where % complete changes based on Task Completion. Hence the project status should ideally be automatic. If at any moment you want to mark it as complete irrespective of tasks in it, you can choose to update the method and mark it as complete.

![image](https://github.com/user-attachments/assets/cdea8ebb-e02b-4de7-87de-29b8afa5d8d7)

If you still think this is an issue, please let me know and we can discuss this.

**Comment by sjoulaei** [comment]
thanks for your reply. I hadn't noticed the % completion method field. Many of the unused fields are hidden on our forms. Changing all project % completion to manual will fix our issues. Thanks again.
