### ISSUE TITLE
Material Request by Supplier - feature request

### ISSUE THREAD

**Issue by AdamBrewology** [frappe/erpnext#4238]
Hi,
At the moment it is not possible to pull parts into a Purchase Order from a single Material Request for a single Supplier.
I can pull a whole Material Request into a Purchase Order, or pull a list of parts from one Supplier from all open Material Requests into a Purchase order but it is not possible to narrow this down to one Material Request and one Supplier without manually deleting all the unwanted parts from the Purchase Order.
This feature would be very helpful and would save time and potential problems caused by deleting the incorrect items from the Purchase Order.
Thanks,
Adam

**Comment by DavidBrewology** [comment]
We are happy to consider paying for this if you can provide a quote for the work

**Comment by rmehta** [comment]
@DavidBrewology thanks for the paid-dev offer. The workflow ill be

1. Open PO
2. Select Supplier
3. Select Material Request

Only items that have that particular supplier as the default supplier will be pulled. Does that work?

**Comment by DavidBrewology** [comment]
Hi Rushabh

Basically correct but I think it would be good to have an option to
consolidate common items from the Material Request.  i.e. if there are 2 of
the same items in the material request this can either add them up so it
produces 1 item in the Purchase Order or the other option is to show the
item multiple times in the Purchase Order.


   1. Open PO
   2. Select Supplier
   3. Select Material Request
   4. Option to Consolidate Common Items

Kind Regards,

*David*

-- 
 <http://www.brewology.co.uk>

**Comment by rmehta** [comment]
I think think might have to be tracked separately as they need to be tagged against the Material Request. But will look into it. The dev schedule is pretty packed right now. But adding this to watchlist.

**Comment by chaoyee** [comment]
I believe this is a very important feature.  We need it as well.

**Comment by Arundhatii** [comment]
UI Mock up :
![new mock up for default supplier material request po](https://cloud.githubusercontent.com/assets/20164097/22146896/57542ebe-df2c-11e6-9579-b0a700943c54.png)

**Comment by bcornwellmott** [comment]
I would suggest adding a box to the dialog box instead of using the supplier from the form...

**Comment by dvdl16** [comment]
We can also help with payment for this feature. This is really needed
