### ISSUE TITLE
Serial No Unable to be set to Available or Delivered

### ISSUE THREAD

**Issue by bohlian** [frappe/erpnext#4244]
A manual stock entry "receipt" with Serial Nos indicated within the document doesn't change the Serial No status to Available.

Likewise a manual stock entry "issue" doesn't change the Serial No status to Delivered. A Delivery Note done with the specified Serial No also yields the same result.

In "Warranty Claims" the Serial No. filters items which are in the "Delivered" status, without a way to set the Serial Nos to be "Delivered" the filter will never show any result.

**Comment by nabinhait** [comment]
In a recent release, we have removed "Status" field from Serial No. Now the status is purely based on Warehouse value.

In Warranty Claim, we have fixed the query of Serial No, it will be updated in the next release.

**Comment by bohlian** [comment]
Yes I can confirm it works now. Thanks.
