### ISSUE TITLE
wrong rate calc in BOM

### ISSUE THREAD

**Issue by canta76** [frappe/erpnext#4247]
in my test case:
- DMA120 has a price of 11 euro
- Supply Raw Materials for Purchase is selected for DMA120
- DMA120 has a BOM with just an item (in this case CM0010, price 23.90 euro)

the price shown in the item row DMA120 of the TE0001 BOM must be:
23.90 + 11.00 = 34.90

instead it's only showed 23.90 euro

see the picture below:

![1](https://cloud.githubusercontent.com/assets/2210346/10806535/6dc83d2e-7dd6-11e5-9a6b-c86e73c7e875.png)

![2](https://cloud.githubusercontent.com/assets/2210346/10806538/720bfb64-7dd6-11e5-9894-92143bd1e597.png)

**Comment by canta76** [comment]
I've checked bom.py
maybe you have to use this code?
```
def get_rm_rate(self, arg):
		"""	Get raw material rate as per selected method, if bom exists takes bom cost """
                rate = 0
                if arg['bom_no']:
			rate = self.get_bom_unitcost(arg['bom_no'])
		if arg and (arg['is_purchase_item'] == 1 or arg['is_sub_contracted_item'] == 1):
			if self.rm_cost_as_per == 'Valuation Rate':
				rate += self.get_valuation_rate(arg)
			elif self.rm_cost_as_per == 'Last Purchase Rate':
				rate += arg['last_purchase_rate']
			elif self.rm_cost_as_per == "Price List":
				if not self.buying_price_list:
					frappe.throw(_("Please select Price List"))
				rate += frappe.db.get_value("Item Price", {"price_list": self.buying_price_list,
					"item_code": arg["item_code"]}, "price_list_rate") or 0

		return rate
```

**Comment by neilLasrado** [comment]
@canta76 we will fix it up. For the moment you can proceed by creating a separate price list.

**Comment by canta76** [comment]
how i can do this?

**Comment by neilLasrado** [comment]
Create a separate price list for the subcontracted item and include the cost of subcontracting in it.
