### ISSUE TITLE
Payment Order Creates Journal Instead of Payment Entry

### ISSUE THREAD

**Issue by Bknjogu** [frappe/erpnext#42486]
### Information about bug

We are encountering an issue with the Payment Order functionality in ERPNext. When multiple payment requests for a supplier are created and then consolidated into a Payment Order to facilitate bulk payment, the system creates a journal entry instead of a payment entry upon clicking the "Create Payment Entries" button. If we were to use Payment Entry shortcut provided in the Connection section, the Reference Documents are not fetched whilst the Payment Type remains as “Receive”.

Step1: Create multiple payment requests for a supplier. The Mode of Payment and Bank Accounts details remain the same across all Payment Requests.

Step 2: Consolidate All Payment Requests to one Payment Order.
![Payment Request1](https://github.com/user-attachments/assets/255f30dc-77b8-4386-839e-afd8e79e3192)
![Payment Request2](https://github.com/user-attachments/assets/d514b613-a6ce-492a-a347-277071cd5c9b)
![Payment Request3](https://github.com/user-attachments/assets/959a2ea1-dfbc-4fbf-a181-b82c01bd21fd)

Step 3: Click the "Create Payment Entries" button in the Payment Order
![Payment Order1](https://github.com/user-attachments/assets/68b6730d-af80-41cd-8a51-f9b4eff5c390)

Expected Behavior: The system should create a Payment Entry upon clicking the "Create Payment Entries" button in the Payment Order.

Actual Behavior: The system creates a Journal Entry instead of a Payment Entry.
![Journal Entry](https://github.com/user-attachments/assets/bcd0a0ad-ff50-43f6-be03-c620fc2b34c7)

We rely on the Payment Entry functionality due to its integrated approval processes. This issue disrupts our workflow and poses challenges in maintaining the approval integrity for payments.

### Module

accounts

### Version

ERPNext: v15.31.1 (HEAD)

Frappe Framework: v15.36.0 (HEAD)

### Installation method

None

**Comment by ruthra-kumar** [comment]
Payment Order has always created Journal entries. Button naming has caused a misunderstanding here. I've renamed the button to avoid further confusion.
https://github.com/frappe/erpnext/pull/42528
