### ISSUE TITLE
Error while creating Payment entry

### ISSUE THREAD

**Issue by poojavadher** [frappe/erpnext#42521]
### Information about bug

Error While creating Payment entry
![image](https://github.com/user-attachments/assets/13d0e6ca-7a7a-45f3-81fa-c36d0f171b6b)

### Module

accounts

### Version

ERPNext: v15.31.2 (HEAD)

Frappe Framework: v15.36.0 (HEAD)

Frappe HR: v15.25.0 (HEAD)

India Compliance: v15.12.0 (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1768, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/form/save.py", line 39, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 359, in _save
    return self.insert()
           ^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 291, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1091, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 78, in validate
    self.set_liability_account()
  File "apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 149, in set_liability_account
    liability_account = get_party_account(
                        ^^^^^^^^^^^^^^^^^^
IndexError: list index out of range


### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"docstatus\":0,\"doctype\":\"Payment Entry\",\"name\":\"new-payment-entry-fffwgfufds\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"naming_series\":\"ACC-PAY-.YYYY.-\",\"payment_type\":\"Pay\",\"payment_order_status\":\"Initiated\",\"custom_entry_type\":\"\",\"posting_date\":\"2024-06-07\",\"company\":\"eFRA Industries LLP\",\"book_advance_payments_in_separate_party_account\":0,\"reconcile_on_advance_payment_date\":0,\"paid_from_account_currency\":\"INR\",\"paid_to_account_currency\":\"INR\",\"references\":[],\"apply_tax_withholding_amount\":0,\"taxes\":[],\"deductions\":[],\"status\":\"Draft\",\"custom_remarks\":0,\"is_opening\":\"No\",\"letter_head\":\"Efra Industries-Purchase\",\"__run_link_triggers\":false,\"mode_of_payment\":\"Wire Transfer\",\"party_type\":\"Supplier\",\"party\":\"S0043\",\"party_name\":\"Axis Bank Limited\",\"party_balance\":-840,\"paid_from\":\"Axis Bank Ltd CC A/c-923030069679572 - EIL\",\"paid_from_account_type\":\"Bank\",\"paid_from_account_balance\":-921264.5,\"paid_to\":\"Axis Bank Ltd - EIL\",\"paid_to_account_type\":\"Payable\",\"paid_to_account_balance\":-840,\"paid_amount\":11.8,\"paid_amount_after_tax\":11.8,\"source_exchange_rate\":1,\"base_paid_amount\":11.8,\"base_paid_amount_after_tax\":11.8,\"received_amount\":11.8,\"received_amount_after_tax\":11.8,\"target_exchange_rate\":1,\"base_received_amount\":11.8,\"base_received_amount_after_tax\":11.8,\"total_allocated_amount\":0,\"base_total_allocated_amount\":0,\"unallocated_amount\":11.8,\"difference_amount\":0,\"base_total_taxes_and_charges\":0,\"total_taxes_and_charges\":0,\"company_address\":\"eFRA Industries LLP-Billing-1\",\"company_gstin\":\"24AAIFL0473C1ZQ\",\"reference_no\":\"penal charges\",\"reference_date\":\"2024-06-07\",\"base_in_words\":\"INR Eleven and Eighty Paisa only.\",\"in_words\":\"INR Eleven and Eighty Paisa only.\",\"title\":\"S0043\",\"creation\":\"\",\"modified_by\":\"Administrator\",\"modified\":\"\",\"lft\":null,\"rgt\":null,\"idx\":null}",
		"action": "Save"
	},
	"btn": {
		"jQuery3700023377281782816841": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 1613,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": "758e15d1-9aa6-468d-8425-ab95bf937ae0"
}
```
### Response Data
```
{
	"exception": "IndexError: list index out of range",
	"exc_type": "IndexError",
	"_exc_source": "erpnext (app)"
}
```
```

**Comment by Nihantra-Patel** [comment]
Everything is working fine. No problems were encountered in the version 15.


https://github.com/user-attachments/assets/d0d82390-60c0-4fa8-b045-032b447f2f79

**Comment by poojavadher** [comment]
@Nihantra-Patel 
It is showing error while recording the payment in advance

**Comment by Nihantra-Patel** [comment]
Whenever you raise an issue, please make sure to include all the necessary steps and provide detailed information.

We tested it, and It's working properly. if possible then please provide the video and step.

**Comment by poojavadher** [comment]
I have already added full error message

**Comment by Nihantra-Patel** [comment]
We don't necessarily know from the error log. Sometimes we need steps too. Because how do we know from which step that error came? It didn't show the error log, even though we looked through the advanced entry, we didn't see anything. So again you too, can you give us the steps how you do advance entry?

**Comment by poojavadher** [comment]
https://github.com/user-attachments/assets/edc93a00-6175-4b25-9e01-20fc00505df9

**Comment by Nihantra-Patel** [comment]
Again, please check it.


https://github.com/user-attachments/assets/f0cb6415-f11a-4c9d-b667-44cf5f2b9adb

**Comment by poojavadher** [comment]
It was showing error because of the advance payment settings  " Book Advance Payments in Separate Party Account" but account does not set for this. in such case it should not show error and should give the message to set the default accounts to company/party/party group.

![image](https://github.com/user-attachments/assets/40180d50-2f00-43c7-a42f-1e2fb54b36f8)
