### ISSUE TITLE
Combined tender types at pos screen

### ISSUE THREAD

**Issue by noetico** [frappe/erpnext#4256]
Hello Sir, I would like to get a costing for the following:
1. Cashier is able to receive payment for a sale from more than 1 tender type, say 100usd total paid as 50usd cash 50usd card.
2. Ability to setup instant print on pos screen so after full payment; print is sent to the default printer.

Let me know the costing for each feature.

Thank you.

**Comment by noetico** [comment]
Please forward a quotation for this, item 1 is most critical as we can do with the current sales finalization workflow.

**Comment by rmehta** [comment]
$200 ?

**Comment by noetico** [comment]
Sounds good; what's your best? how about $100; I'm just a young business
man. Let me know what's good for you though. How will the update be
integrated and do I get access to reuse it when I need to?

**Comment by system19** [comment]
@noetico This type of enhancement is added to the next ERPNext/Frappe release. So yourself and all the other ERPNext users receive the benefit.
I can chip in $50 to add to notice's offer of $100 so we are up to $150.
I can transfer the money next Tuesday 3rd Oct.

**Comment by noetico** [comment]
@System19 thanks a loy for the support on this, indeed it's better for the
whole community to benefit. I will make a transfer by thursday 5th Oct. How
do we send the money?

Thanks.

**Comment by system19** [comment]
You have to wait to see if the Frappe team accepts the offer :-) And when they can find time to code this.  It maybe that this request requires a lot of work behind the scenes and can't be done for that price.  So they will look at it and get back in touch with you probably on Monday. Frappe team pricing is excellent compared to paying an individual developer to do this work. Also Thursday 5th for money suits me better as well.  Best Regards

**Comment by noetico** [comment]
Alright Sir; Thanks again, we'll see how it goes. Keeping fingers crossed.

**Comment by munimaubdullah** [comment]
The two features are already done with the newest version. One can easily pay by multiple payment method and also have the ability to print directly from pos screen.
