### ISSUE TITLE
Future Development - Newsletter Subscribers

### ISSUE THREAD

**Issue by sliska** [frappe/erpnext#4257]
It'd be pretty great if, rather than importing subscribers, it were possible to view all contacts and make newsletter subscriber lists based on the filters chosen (lead, opportunity, opportunity lost, customer, customer group, and industry). This is not urgent for us so I'm just throwing it out there as an item to add to the to-do list.

**Comment by Devens** [comment]
+ 1

**Comment by manivk** [comment]
Same here - would like to have a feature where I can create filters on fields within each doc type (even custom created fields), so that we do not add subscribers to the list manually every time

**Comment by deepeshgarg007** [comment]
@sliska I think you can make email groups now. That should satisfy your requirement
