### ISSUE TITLE
Purchase Transactions do not allow purchase to an Asset Account

### ISSUE THREAD

**Issue by casesolved-co-uk** [frappe/erpnext#42583]
### Information about bug

The query for the `expense_account` field mandates the account must be from Profit and Loss, however it is acceptable to purchase something as an asset (or even liability) on the balance sheet and miss P&L entirely.

https://github.com/frappe/erpnext/blob/281198456dde21d521b653d660e10ec045279070/erpnext/public/js/controllers/transaction.js#L197-L207

![Screen Shot 2024-08-01 at 16 13 54](https://github.com/user-attachments/assets/cbfff5a8-c3b8-44d3-89ac-08ac4e144641)

### Module

accounts

### Version

v16 develop

### Installation method

None

**Comment by Nihantra-Patel** [comment]
If you want, then you can easily set it from the client script!
