### ISSUE TITLE
IRN not generating for the sales invoice 

### ISSUE THREAD

**Issue by prash4** [frappe/erpnext#42580]
### Information about bug

![WhatsApp Image 2024-08-01 at 10 30 43 AM](https://github.com/user-attachments/assets/4aec9f30-c9e1-4615-9a1f-83594808ab2f)

Hello, We are not able to make any sales invoice as its showing below error 

### Module

accounts

### Version

ERPNext: v14.62.3 (HEAD)

Frappe Framework: v14.65.0 (HEAD)

India Compliance: v14.24.1 (HEAD)

### Installation method

FrappeCloud

**Comment by ljain112** [comment]
This field is not mandatory.
There can be customisations in this field.

For generating e-invoice you can refer to documentation.
https://docs.indiacompliance.app/docs/ewaybill-and-einvoice/generating_e_invoice
