### ISSUE TITLE
Filters in the reports

### ISSUE THREAD

**Issue by manivk** [frappe/erpnext#4259]
Would be great to have the ability to save standard filters in the report formats of the various doc types - for e.g., when we go to orders, I always want to see only the open orders (that is orders whose status is not equal to fully delivered), but right now every time I go to the report, I need to enter the standard filters that I use all the time again and again

**Comment by Devens** [comment]
I agree. This is slightly annoying also. Everytime we need to filter.

+ 2

**Comment by Devens** [comment]
@rmehta How can we know whether any action is planned on this Or What is general flow of such issues raised?

**Comment by nabinhait** [comment]
fixed in v7
