### ISSUE TITLE
I want to add an option of item name or item desciption in update items

### ISSUE THREAD

**Issue by rajubaghel** [frappe/erpnext#42609]
![jkhjkjhk](https://github.com/user-attachments/assets/e1eae2fe-b0d8-4f23-870b-65f63f445f92)
![hfghfghfh](https://github.com/user-attachments/assets/045ffb30-bd35-4dc3-8f6f-c1288e631335)

**Comment by Nihantra-Patel** [comment]
Don't create the same issue because you already created the same issue 1 week ago.
