### ISSUE TITLE
Bug OR Feature Request - Has Serial No ( No Auto ) Has Batch No - ( Is Auto )

### ISSUE THREAD

**Issue by dineshpanchal93** [frappe/erpnext#42600]
### Information about bug

![Screenshot 2024-08-02 at 4 43 22 PM](https://github.com/user-attachments/assets/8f292346-cf5d-4e2e-b043-3f6618a4b26f)

When we make stock Reco 

I can make the serial no manually while saving it asking for the batch no. it should create the auto based on the Series selected on Item Master.

![Screenshot 2024-08-02 at 4 47 03 PM](https://github.com/user-attachments/assets/338df42b-6095-4e2f-bfbb-75d31646f9fd)

### Module

stock

### Version

ERPNext: v15.31.3 (version-15)

Frappe Framework: v15.36.1 (version-15)

### Installation method

manual install

**Comment by toofun666** [comment]
SABB introduced lots of bugs for professional users.
