### ISSUE TITLE
Cannot set different naming series for Quotation

### ISSUE THREAD

**Issue by derTuca** [frappe/erpnext#42619]
### Information about bug

I am trying to follow [this guide](https://docs.erpnext.com/docs/user/manual/en/company-wise-naming-series) to create different naming series for different companies' quotations. However, when I try to add another series to the Options field of the Naming Series, I get the error `You can't set 'Options' for field Series` when trying to save the Form.

The series that I am trying to use is: `SINV-.abbr.-.####`

### Module

selling

### Version

ERPNext: v15.31.5
Frappe Framework: v15.36.1

### Installation method

docker

**Comment by Nihantra-Patel** [comment]
> You can't set 'Options' for field Series when trying to save the Form.
> 
> The series that I am trying to use is: SINV-.abbr.-.####

Please don't update the series from the customize form, if you want to add the series then please go to the Document Naming Settings.

![image](https://github.com/user-attachments/assets/94e461a4-04a0-4f6e-8f00-2df9906ffbcc)

Update the series, reload and check it.
