### ISSUE TITLE
Features for adding the vendor invoices

### ISSUE THREAD

**Issue by RBvijay281** [frappe/erpnext#42624]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Nihantra-Patel** [comment]
A vendor invoice refers to a supplier invoice, which is also known as a [Purchase Invoice](https://docs.erpnext.com/docs/user/manual/en/purchase-invoice).
