### ISSUE TITLE
Unable to generate Supplier Ledger

### ISSUE THREAD

**Issue by RBKasim** [frappe/erpnext#42620]
### Information about bug

We are unable to generate general ledger of supplier. We have booked purchase invoice and the same we are not able to find in the supplier ledger

### Module

accounts

### Version

ERP

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
We are unable to generate general ledger of supplier. We have booked purchase invoice and the same we are not able to find in the supplier ledger
```

**Comment by Nihantra-Patel** [comment]
Everything is working fine. No problems were encountered in the latest versions 14 and 15.


https://github.com/user-attachments/assets/97194b16-cbc7-4074-a5ec-db39e8b056d7


If "Enable Prepared Report" is enabled then disable it. then reload and check it.

![image](https://github.com/user-attachments/assets/7f0b695b-fe22-4788-b341-28e59f4effb8)
