### ISSUE TITLE
Item-Wise Sales Register

### ISSUE THREAD

**Issue by thida-bcn** [frappe/erpnext#42635]
at Item-Wise Sales Register, 
is this possible to add 'Item Code' Filter

**Comment by Nihantra-Patel** [comment]
It's already added: https://github.com/frappe/erpnext/pull/41921

![image](https://github.com/user-attachments/assets/d5ccee3a-990e-48be-afc6-ca52b1d959a1)

**Comment by thida-bcn** [comment]
> It's already added: #41921
> 
> ![image](https://private-user-images.githubusercontent.com/141945075/355328610-d5ccee3a-990e-48be-afc6-ca52b1d959a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MzUwNDIsIm5iZiI6MTcyMjkzNDc0MiwicGF0aCI6Ii8xNDE5NDUwNzUvMzU1MzI4NjEwLWQ1Y2NlZTNhLTk5MGUtNDhiZS1hZmM2LWNhNTJiMWQ5NTlhMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQwODU5MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MDM2YjU5ZjljNWZlZTQ4YjI5MGU5ZWU3MmY2ODg2NGI5N2FkZDVlYjhlMWViOWE5OTcxMDMxNWJjNTEzOTlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.koyAe6o2_AXWD5ojitjHkkwFd1jxv2nT57hCU2jYbF4)

hello,
is this possible to add version 14

**Comment by Nihantra-Patel** [comment]
> is this possible to add version 14

Added.

**Comment by thida-bcn** [comment]
> > is this possible to add version 14
> 
> Added.

thanks
