### ISSUE TITLE
Property setter for Unique property does not function as expected.

### ISSUE THREAD

**Issue by remigius974** [frappe/erpnext#42662]
### Information about bug

i changed the unique property(field_type=check) value in payment entry from 0 to 1 but still can generate non unique payment entry transactions(with non-unique reference numbers).

### Module

accounts

### Version

Frapper version - v15.15.0
ERPNext version - v15.14.4

### Installation method

docker

**Comment by Nihantra-Patel** [comment]
Sometimes the property setter does not work unique scenario because a unique related function runs in the validate event.
