### ISSUE TITLE
Status Filter does not work properly

### ISSUE THREAD

**Issue by stepsibg** [frappe/erpnext#42675]
### Information about bug

Status filter set as "to bill"
Filter set as status-not equals-completed but system still shows documents with status as completed. see the picture. 
Check this in Purchase Receipt  and Delivery Notes. Probably this error in all the doc where this "status filter" is used.

![2024-08-08_09-51-00](https://github.com/user-attachments/assets/f7cbcd85-abe2-4a88-ad77-c1cd5143fb90)

### Module

buying, selling

### Version

ERPNext: v15.31.5 (version-15)
Frappe Framework: v15.36.1 (version-15)
but this bug is since version 14

### Installation method

None

**Comment by Nihantra-Patel** [comment]
Kindly upgrade your version 15 because everything is working fine. No problems were encountered in the latest version 15.

https://github.com/user-attachments/assets/b4889549-35ed-4813-8afc-9ada0b7c0f7b

**Comment by stepsibg** [comment]
we are on v15.31.5 already

**Comment by stepsibg** [comment]
that is our video of the case


https://github.com/user-attachments/assets/f7ac7876-a74c-4ce5-a9a8-270eef3da4cf

**Comment by Nihantra-Patel** [comment]
Maybe it's a caching issue. You can also check the commit log on GitHub. If the update status and update list have not changed in the last six months. we also checked on the frappe cloud side but everything worked properly.

If anything is override in your custom app then check it from your end!
