### ISSUE TITLE
Time Zone Issues at POS Close Shift

### ISSUE THREAD

**Issue by thida-bcn** [frappe/erpnext#42701]
### Information about bug

System Settings >> Myanmar
![image](https://github.com/user-attachments/assets/19599873-e60c-47eb-86b0-d8ed52d2177f)
POS Closing Shift
![image](https://github.com/user-attachments/assets/2e5fd54d-8795-448b-bb19-cd8e59d81538)
Start Time > End Time 

POS Invoice >> Posting Time shown 2
![image](https://github.com/user-attachments/assets/a0a2ad6d-27aa-4ce9-901e-46d43537d44c)

when made close shift POS invoice didn't attached at close shift

### Module

selling

### Version

Installed Apps
Email Delivery Service: v0.0.1 (HEAD)

ERPNext: v15.32.0 (HEAD)

Frappe Framework: v15.37.0 (HEAD)

Print Designer: v1.4.0 (HEAD)

### Installation method

FrappeCloud

**Comment by thida-bcn** [comment]
[Video](https://1drv.ms/u/s!ApZZW_p_lZ54gZMSEKNUf9icMr2BdA?e=x3MQ6N)

**Comment by Nihantra-Patel** [comment]
Issue is related to the user's time zone, so update it accordingly. We tested it on both the local and Frappe Cloud side.

**Local Test:**

https://github.com/user-attachments/assets/c3fdf467-2057-487c-9bb4-829b36672f0e

**Frappe Cloud Test:**

https://github.com/user-attachments/assets/a2fe8d26-8e66-4bbb-a4e5-a973d5853bcb

**Comment by thida-bcn** [comment]
Thanks
We need to update timezone for user manually 
Actually system time zone must be set as default
