### ISSUE TITLE
ERPnext Manufacturing module Work order Picklist source warehouse 

### ISSUE THREAD

**Issue by aalkhaldi47** [frappe/erpnext#42722]
### Information about bug

Hello ,
our company is using batch pre preparation module for production. 
so we are preparing material on site based on FIFO for multiple batches.
 so we prepare 5 to 7 batches , each batch takes 11-18 hours depend on the grade we are producing.
so we have plan consumption based on Bill of material and we have physical consumption based on operation consumption.

in system we are doing it the same way as below.
we create Work order then we create pick list after we create the pick list and confirms material availability on site based on pick list we transfer material on system to Work in progress.

so when we complete this cycle we need to wait for around 13 hours to have visibility of how much we actually consumed so we can close the work order. in the same time we need to start 2nd batch on exactly 7 hours from first batch running, so in system when we try to create pick list , the system will take 2nd batch pick list from work in progress warehouse instead of raw material warehouse which is the default source warehouse in the work order item list. as screen shot

so we are facing this issue note that we are using ERPnext: v12.18.0 (version-12)

what kind of suggestion you guys suggest to solve this issue.

![212](https://github.com/user-attachments/assets/d7c460ad-9acf-4f55-bcde-de8e11a399d7)

### Module

stock, manufacturing

### Version

ERPnext: v12.18.0 (version-12)

### Installation method

None

**Comment by Nihantra-Patel** [comment]
If it's a bug, it hasn't been fixed in version 13 or older. because they stopped fixing bugs for that version. It might still have problems. It's best to upgrade to version 14 or 15 because lots of bugs fixed in the new version.

Version | EOL | Branch
-- | -- | --
Version 12 | End of 2022 | version-12
Version 13 | End of 2023 | version-13
Version 14 | End of 2024 (planned) | version-14
Version 15 | End of 2026 (planned) | version-15
Bleeding edge | N/A | develop


For more information, please refer to the [guidelines](https://github.com/frappe/erpnext/wiki/Supported-Versions).

Thank You!

**Comment by aalkhaldi47** [comment]
Hello Patel , 

unfortunately i try v 15 but the issue remines the same. pick list ignores the source warehouse and always take materials remaining in the work in progress warehouse.

**Comment by Nihantra-Patel** [comment]
Please share the video of process in version 15, also share the version of v15.

**Comment by Nihantra-Patel** [comment]
And source warehouse comes from the item master. If you define the Default Warehouse in Item Defaults and then create a work order, it will come automatically. 

![image](https://github.com/user-attachments/assets/2267ba9b-daa4-4b34-baff-505e8dc581f9)


Otherwise, it comes from the work order source warehouse.

![image](https://github.com/user-attachments/assets/eefb8c89-754e-4d0a-a4f5-a20a26ba3e0b)

**Comment by aalkhaldi47** [comment]
Hello Patel, 
these are the steps that I already done before. 
![erp1](https://github.com/user-attachments/assets/919de78e-3017-4fdb-88b7-0821f8e9da5f)
![erp2](https://github.com/user-attachments/assets/4d4a5334-4364-420f-9b54-22e4ed03e726)

WO1 setting 
![erp WO1-1](https://github.com/user-attachments/assets/cd37f78f-18f5-4c4c-8996-cbe312c305cf)
Picklist created against the WO. 
![erp WO1-2](https://github.com/user-attachments/assets/dcfe7b04-25ac-471e-bb9f-8b0de65d3e7e)
then I done stock entry to transfer the pick list to work in progress warehouse.

WO2 setting 
![erp WO2-1](https://github.com/user-attachments/assets/a4ca9ff7-2bac-448b-8a92-c9f6fc906c5e)
Pick list created against The WO , it shows source is work in progress which i didnt select as source warehouse when i created the work order even the material meta data showing different warehouse.
![erp WO2-2](https://github.com/user-attachments/assets/b95a6591-f6f4-4e39-b567-d176739ba07d)

**Comment by aalkhaldi47** [comment]
note that i used import method to all items so setting all the same for all items in ERP

**Comment by aalkhaldi47** [comment]
and this is system v 
![frapp](https://github.com/user-attachments/assets/92584d02-9e2a-4449-9200-1e94f1f50f86)

**Comment by Nihantra-Patel** [comment]
The warehouse listed in the work order will appear in the warehouse pick list. If you haven't selected a source warehouse in the work order, it will use the item's default warehouse. When you create a pick list, it will automatically choose the same warehouse as specified in the work order item. We have tested this process two or three times and did not find any issues.

**Comment by aalkhaldi47** [comment]
you are correct if there is no item related to the work order in the work-in-progress warehouse. 
but if there is a material already transferred to work on progress related to another work order it will be chosen from there instead of taking it from the Raw material warehouse.
so what i understand is that the pick list will prioritize items in work in progress regardless of the source warehouse set in the work order or item master data.

try to make 2 work orders and make pick list for 1st one and make a stock entry against it to work in progress. 
then go to the 2nd work order and create a pick list you will find what I mean.

**Comment by aalkhaldi47** [comment]
i fixed it , i changed Raw material warehouse to be under unique group , then i forced pick list to take source from the group i created. this is the only way to force pick list to take from a source warehouse
