### ISSUE TITLE
Module Access Permission Not working Userwise 

### ISSUE THREAD

**Issue by mehtaharsh15** [frappe/erpnext#4276]
Hello All,

Also I have posted this 

I have found major bug in erpnext module access and it should be sortout on immediate basis.

Steps that i have follow for module access

Step 1 : I created new user and set module access permission for that user and save it.

Step 2 : Now if i again check module access permission for that user then i can't see my module access permission that i have saved.

Please find attached GIF image so you will get better idea.

![erp-bug](https://cloud.githubusercontent.com/assets/5945814/10961058/6e163eea-83b0-11e5-9866-448356e9c44a.gif)

**Comment by Devens** [comment]
I also faced this issue for other forms also...


Thanking you,

With Regards,
Deven Shah
Safeworld Systems Pvt Ltd
M - 09825060116

**Comment by rmehta** [comment]
not able to replicate. can you check again?

**Comment by mehtaharsh15** [comment]
Hello rmehta,

Please follow steps according to GIF Image.

Or Follow below steps

Step 1 :  Check on module access which you want to assign for user

Step 2 :  Save the form

Step 3 : Now see Module Access Permission, they are not in conformity with the ones that were assigned and saved in above steps
