### ISSUE TITLE
Patch Error on Update to ERPNext version 14.72.0

### ISSUE THREAD

**Issue by danjeremynavarro** [frappe/erpnext#42776]
### Information about bug

Update fails when the system runs the patch
erpnext.patches.v14_0.update_pos_return_ledger_entries
with error frappe.exceptions.ValidationError: Cannot Resubmit Ledger entries for vouchers in Closed fiscal year.

### Module

accounts

### Version

erpnext version 14.72.0
frappe version 14.78.2

### Installation method

self-hosted

### Relevant log output / Stack trace / Full Error Message.

 frappe.exceptions.ValidationError: Cannot Resubmit Ledger entries for vouchers in Closed fiscal year

**Comment by danjeremynavarro** [comment]
https://github.com/frappe/erpnext/pull/42720

**Comment by danjeremynavarro** [comment]
https://github.com/frappe/erpnext/pull/42720 Commit

**Comment by ruthra-kumar** [comment]
Thanks for reporting.

Will have to modify the patch to handle vouchers within and outside closed fiscal years differently.

**Comment by ruthra-kumar** [comment]
Fixed in https://github.com/frappe/erpnext/pull/42791
