### ISSUE TITLE
Field automatically_set_serial_nos_based_on_fifo does not exist on Stock Settings

### ISSUE THREAD

**Issue by redolencetech** [frappe/erpnext#42781]
### Information about bug

Adding new items into sales orders lets me add the items themselves, but displays an error message every time: `Field automatically_set_serial_nos_based_on_fifo does not exist on Stock Settings`

### Module

stock, selling

### Version

Frappe CRM: v2.0.0-dev (develop)
Desk Navbar Extended: v0.0.1 (main)
ERPNext: v15.33.0 (version-15)
Frappe Framework: v15.38.0 (version-15)
Frappe Better List View: v1.4.0 (main)
Frappe M365: v0.0.1 (main)
Frappe Pdf: v0.0.1 (main)
Frappe Whatsapp: vv1.0.7 (master)
Frepple: v0.0.1 (main)
general customiztion : v0.0.1 (main)
Go1 CMS: v0.0.1 (master)
Frappe HR: v16.0.0-dev (develop)
Item Price: v0.0.1 (master)
Itemfeatures: v0.0.1 (master)
Microsoft Integration: v0.0.1 (main)
Payments: v0.0.1 (develop)
PDF on Submit: v15.1.0 (version-15)
Print Designer: v1.2.0 (develop)
QR Demo: v0.0.1 (version-14)
Reacteur: v0.0.1 (main)
Resource Manager: v0.0.1 (master)
Split Sales Order: v0.0.1 (main)
Wiki: v2.0.0 (master)

### Installation method

easy-install

**Comment by rohitwaghchaure** [comment]
New settings added for that

<img width="1135" alt="Screenshot 2024-09-25 at 2 51 57 PM" src="https://github.com/user-attachments/assets/826a173c-0fe6-4c66-8d06-9f878342a24d">
