### ISSUE TITLE
[Bug] Add Brand Button not work

### ISSUE THREAD

**Issue by donnieferdian** [frappe/erpnext#42780]
### Information about bug

Add Brand Button work
![Screen Recording 2024-08-15 at 6 18 37 PM](https://github.com/user-attachments/assets/00ee52a7-c7bd-4dbd-a62d-bedcdf01ae63)

### Module

stock

### Version

ERPNext: v15.33.0 (version-15)
Frappe Framework: v15.38.0 (version-15)

### Installation method

manual install

**Comment by bobotdls** [comment]
Yup I agree, all of out instance since I upgrade the Brand is not working properly,  there's a bugs on the latest version

**Comment by bobotdls** [comment]
Hi any target date when this bugs will fix. It's really affect our operation

**Comment by donnieferdian** [comment]
hi @bobotdls you can use alternative way by using the import function
