### ISSUE TITLE
[Patch require] : Leave Allocation data to populate To Date and From Date for existing data

### ISSUE THREAD

**Issue by mayur-patel** [frappe/erpnext#4279]
Hi There,

It seems that the new feature “Allocate leaves in Leave Allocation by specific dates and not Fiscal Year” has broken the existing Leave Application form. On the form, it no longer display Leave Balance section due to it always returning 0. The new enhancement has below sql query which compare to_date and from_date but the existing data has these fields as NULL. We need a patch to populate existing date to have From date and To date to be populated  based on the fiscal year stored in the data. Other wise below will not return any value.

 leave_all = frappe.db.sql("""select total_leaves_allocated
                from `tabLeave Allocation` where employee = %s and leave_type = %s
                and from_date<=%s and to_date>=%s and docstatus = 1""", (employee,
                        leave_type, from_date, to_date))

**Comment by mayur-patel** [comment]
@anandpdoshi 
Thanks. I can see that the patch has worked. But there is a bug in the system. The leave_application.js file is passing doc.from_date and doc._todate to get_leave_balance function. It should be passing the fiscal_year.from_date and fiscal_year.to_date to the get_leave_balace. I am not sure how to get this from the client side java script and hence not able to fix it at my end and hence I can’t send pull request for it. Please help to fix it. Thanks.

**Comment by anandpdoshi** [comment]
@mayur-patel is this still a problem?

**Comment by mayur-patel** [comment]
@anandpdoshi 
Yes. On Leave Application Add page, there is a field to display "Leave Balance Before Application" which is not display correct balance. The reason it doesn't display correct balance becauseit is not subtracting the leaves already taken. I understand that you guys have changed the module to allow the leave allocation based on a period (start and end date rather than fiscal year), so the question is what should be displayed on the leave application page for "Leave Balance Before Application"? Should it be the leave balance for the current year or for a period (which period)? Currently leave_balance.js passed the start and end date of the leave period the user is applying for hence no leaves are being subtracted. Please check it in your local environment too. I am 100% sure the login is wrong. As per the original logic, it should pass the start date and end date for the fiscal year or for a particular period and not the start and end date for the leave itself. I hope I am clear. I have also added a bug for this. See Issue #4300

**Comment by mayur-patel** [comment]
@anandpdoshi
Yes. On Leave Application Add page, there is a field to display "Leave Balance Before Application" which is not displaying the correct balance. The reason it doesn't display correct balance because it is not subtracting the leaves already taken. I understand that you guys have changed the module to allow the leave allocation based on a period (start and end date rather than fiscal year), so the question is what should be displayed on the leave application page for "Leave Balance Before Application"? Should it be the leave balance for the current year or for a period (which period)? Currently leave_balance.js passed the start and end date of the leave period the user is applying for hence no leaves are being subtracted. Please check it in your local environment too. I am 100% sure the logic is wrong. As per the original logic, it should pass the start date and end date for the fiscal year or for a particular period and not the start and end date for the leave itself. I hope I am clear. I have also added a bug for this. See Issue #4300
