### ISSUE TITLE
Stock entry accept the Finished Goods even though the Production not Properly Completed

### ISSUE THREAD

**Issue by prasathchandrasekar** [frappe/erpnext#42806]
### Information about bug

I create one BOM with required raw materials
<img width="1326" alt="image" src="https://github.com/user-attachments/assets/fd9d20bc-04c7-4d0c-b5c2-1a6174ad1709">
And i Create work order against that bom
<img width="1345" alt="image" src="https://github.com/user-attachments/assets/0d9a2957-8645-4c9f-ba81-f2952e6d63c0">
Now I transfer the Goods for manufacturing:
<img width="1301" alt="image" src="https://github.com/user-attachments/assets/05e5868e-0801-45f8-a895-791e21fe8c7f">
now its shows insufficient stock so i was allocate the available stock only:
<img width="1337" alt="image" src="https://github.com/user-attachments/assets/906425a0-a9cd-4e86-b8f4-055646b62210">
Now I finished the manufacturing process:
<img width="1343" alt="image" src="https://github.com/user-attachments/assets/95dfae2e-2f0a-429c-bea7-08ab295db9cf">
it will accept the completed the manufacturing process eventhough raw material is insufficient:
<img width="1364" alt="image" src="https://github.com/user-attachments/assets/bccadb56-4646-497a-a8d2-d7410f2f51ab">

### Module

stock, manufacturing

### Version

ERPNext: v15.32.1 (version-15)

Frappe Framework: v15.37.0 (version-15)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
The stock entry didn't accept raw material insufficient or otherwise change the Output Quantity
```

**Comment by szufisher** [comment]
in my opinion, this is not a bug

**Comment by prasathchandrasekar** [comment]
> in my opinion, this is not a bug

sir which is not allowed the manufacturing completion process in work order because of insufficient raw material.

**Comment by rohitwaghchaure** [comment]
@prasathchandrasekar 
Set Backflush Raw Materials Based On as BOM and check
<img width="1347" alt="Screenshot 2024-08-19 at 1 01 01 PM" src="https://github.com/user-attachments/assets/e2d9abe0-0a7b-4669-b669-f1077cc235d8">


If you're changing the qty manually in the Manufacture Stock Entry then it's not a bug

**Comment by prasathchandrasekar** [comment]
@rohitwaghchaure 
If the manufacturing user purposefully entered wrong quantity, the erp next system why not validate the actual quantity based on raw material, its bug or not?

**Comment by rohitwaghchaure** [comment]
@prasathchandrasekar fixed https://github.com/frappe/erpnext/pull/43011
