### ISSUE TITLE
Bug: Dragging a button takes user to desk

### ISSUE THREAD

**Issue by cgpurbaugh** [frappe/erpnext#4280]
Dragging a button results in being taken back to the desk
![button glitch](https://cloud.githubusercontent.com/assets/13136405/10979085/6e870806-83c8-11e5-9acb-e5fff38cc2a0.gif)

**Comment by Devens** [comment]
Hello. Can I ask here that which software do you use for screen recording
like this?

**Comment by rmehta** [comment]
licecap

**Comment by cgpurbaugh** [comment]
I use this program: http://gifrecorder.com/

**Comment by Devens** [comment]
Thank you very much to both.


Thanking you,

With Regards,
Deven Shah
Safeworld Systems Pvt Ltd
M - 09825060116
