### ISSUE TITLE
pick list scan barcode issue

### ISSUE THREAD

**Issue by mohsinalimat** [frappe/erpnext#42812]
### Information about bug

Maximum quantity scanned for item item_name.

Create new pick list and In scan barcode field paste barcode then you can see the msg.

![image](https://github.com/user-attachments/assets/c4ae4e81-cdc7-44fb-a8ed-feb45eb8671f)

https://support.frappe.io/helpdesk/my-tickets/20366

### Module

stock

### Version

Latest version 15

### Installation method

FrappeCloud

**Comment by rohitwaghchaure** [comment]
@mohsinalimat Working fine 
![make-pick-lis-against-so](https://github.com/user-attachments/assets/787a3481-4046-4c82-a873-f641efb90577)
