### ISSUE TITLE
Payment Request

### ISSUE THREAD

**Issue by nakul80** [frappe/erpnext#42836]
### Information about bug

Payment Request for outward payment to supplier has a payment link in the message. This is not possible.

<img width="1330" alt="image" src="https://github.com/user-attachments/assets/ce7518ba-9e2a-4375-ad43-4c4c0219b23e">

### Module

accounts

### Version

ERPNext: v15.33.0 (HEAD)
Frappe Framework: v15.38.0 (HEAD)

### Installation method

None

**Comment by Nihantra-Patel** [comment]
You mean the line with "make payment" should not appear at outward time, and I think the line above it should not appear either (Maybe).

**Comment by nakul80** [comment]
The line above should not be there if this payment request goes to the supplier. If it goes to accounting user its fine. I guess thats something to consider. Is doctype 'payment request' a request to the 3rd party or an internal process request? I think if its only meant for 3rd party then I cant understand why payment request would give an option for "outward" payment 

The field message_examples seems to have something to do with this but I did not want to fiddle with that.

**Comment by Nihantra-Patel** [comment]
Okay, now I'll explain it to you in detail:

'Payment Request' doctype serves as a way to request payments, typically related to sales invoices or purchase invoices. It can be used both as an internal process to formalize payment requests and as a means to communicate with third parties (such as customers or suppliers) regarding payment.

For a **Purchase Invoice**:
- **Payment Request** is generally used to request payment from your company to a supplier.
- The "outward" payment option refers to the payment leaving your company's account to pay the supplier.

Though it might seem like this should be strictly an internal process, the Payment Request doctype can be configured and utilized to facilitate communication with external parties (like sending a payment request to a supplier to formalize or confirm payment details). This flexibility is why both inward (receiving payment) and outward (making payment) options are available.

So, even though the Payment Request can be seen as an internal request, it is designed to handle outward payments to suppliers in the context of Purchase Invoices.

If you want, then you can easily customize it in your custom app. so we can't remove it.

**Comment by nakul80** [comment]
No I prefer that its for both options.

But Outward should not have the payment link. The Depends on only has
'eval: doc.payment_channel != "Phone"' as the condition.

Regards,
Nakul

**Comment by Nihantra-Patel** [comment]
But you can customize the message according to the requirement.

![image](https://github.com/user-attachments/assets/21f17e7b-b179-4450-b34d-1c8716f9e982)
