### ISSUE TITLE
Option to Set Default Stock Entry Type in Manufacturing

### ISSUE THREAD

**Issue by akhtarmohsin** [frappe/erpnext#42834]
When we create a stock entry from workorder, the default stock entry type is **Material Transfer for Manufacture** for transfer to manufacturing and **Manufacture** for finished goods. Now, when we create a new stock entry type 'Recycle' with Purpose **Manufacture** the system automatically fetches Recycle as the default stock entry type for finished goods.
Expectation: Either system should fetch **Manufacture** as default always or a provision is required to set the default stock entry type in the manufacturing setting.
![Screenshot 2024-08-20 at 2 47 26 PM](https://github.com/user-attachments/assets/806dcb6a-2b14-4787-91af-e24b57cc0392)
![Screenshot 2024-08-20 at 2 50 14 PM](https://github.com/user-attachments/assets/3979d9c4-dc44-4d8c-acdc-432e9f73d52e)

**Comment by rohitwaghchaure** [comment]
Fixed https://github.com/frappe/erpnext/pull/42835
