### ISSUE TITLE
General Ledger: 'Show Cancelled Entries' is displaying incorrect information.

### ISSUE THREAD

**Issue by sammish** [frappe/erpnext#42838]
### Information about bug

General Ledger: 'Show Cancelled Entries' is displaying incorrect information.

https://github.com/user-attachments/assets/0913e229-71d2-4507-9d57-3b8def42ac81

### Module

accounts

### Version

ERPNext: v15.33.2 (version-15)
Frappe Framework: v15.39.0 (version-15)

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
I want to clarify that "Show cancel entry" means that when you select it, both the normal and canceled entries will be displayed. This means that all entries, including submitted and canceled entries, will be visible.
