### ISSUE TITLE
Created Address/Contact in Opportunity is not visible - Opportunity only see Lead references

### ISSUE THREAD

**Issue by bastelfeak** [frappe/erpnext#42864]
### Information about bug

Within the doctype Opportunity you see only contacts and addresses which are referenced to the lead where the opportunity is based on. 
If you create a new address in the oppornutiy it gets as reference the opportunity but to have it as choice in the address field in the opportunity you have to manually link the address to the lead.

### Module

CRM

### Version

ERPNext: v15.30.0
Frappe Framework: v15.35.0

### Installation method

docker

**Comment by Nihantra-Patel** [comment]
Solved: https://github.com/frappe/erpnext/pull/42596
