### ISSUE TITLE
PO received_qty incorrect when multiple batches of the same item are received in a purchase receipt. 

### ISSUE THREAD

**Issue by lopper** [frappe/erpnext#42881]
### Information about bug

When I create a purchase receipt with multiple lines for the same item but using different batches for each line, the purchase order's received quantity for that item appears incorrect. It seems that only the quantity from the first line in the purchase receipt is being updated in the purchase order.

To reproduce the issue:

Create a Purchase Order for 100 units of Item A.
Create a Purchase Receipt and receive 70 units of Item A in Batch 1 and 30 units of Item A in Batch 2.
The received quantity for Item A in the Purchase Order shows only 70 units, instead of the expected 100 units.

### Module

buying

### Version

ERPNext: v14.52.1
Frappe Framework: v14.76.1

### Installation method

docker

**Comment by rohitwaghchaure** [comment]
It seems that you have not set the purchase_order_item reference in the purchase receipt line item. 
Make sure the column purchase_order_item has the value (use the duplicate button to split quantity in the PR)

Also to solve this issue, we have added Serial and Batch Bundle feature in v15. For more details please check below link
https://docs.erpnext.com/docs/user/manual/en/serial-and-batch-bundle
