### ISSUE TITLE
Timesheet is not working - Release 15.27.0

### ISSUE THREAD

**Issue by njbhatt18** [frappe/erpnext#42889]
### Information about bug

Before version 15.27.0, the Timesheet worked normally, but it stopped working after this update. Can you please check?

### Module

HR

### Version

ERPNext: v15.33.4 (version-15)

Frappe Framework: v15.39.0 (version-15)

Frappe HR: v15.27.0 (version-15)

India Compliance: v15.12.1 (version-15)

### Installation method

manual install

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ruchamahabal** [comment]
Please add more info to your issue. What is not working exactly? 
Any error traceback, steps to replicate would be helpful

**Comment by njbhatt18** [comment]
Please check this video: https://drive.google.com/file/d/1mFvzH95S1mv_2qBRuaHZ4iiW_3et7rT6/view?usp=sharing

Below are the points which I have found while filing up the timesheet:

1.	Enter the start time and the total hours; it does not calculate the end time automatically.
2.	After filling up all the details and pressing the Insert Below button, the whole section gets appended instead of adding 1 row.
3.	The timesheet is not saved When clicking on the Save button.

**Comment by Nihantra-Patel** [comment]
Issue was: https://github.com/frappe/erpnext/issues/42884#issuecomment-2306594837

Fixed: https://github.com/frappe/frappe/pull/27690

**Comment by prononext** [comment]
Got the same problem on the latest version  frappe/erpnext · v15.35.1

Neither removing the read only condition or the project from the list view helped. 
I tried also to downgrade to ERPNext: v15.29.2 but no success.
