### ISSUE TITLE
POS Payment not possible

### ISSUE THREAD

**Issue by robertbecht** [frappe/erpnext#4289]
The amount is prefilled in the amount te be paid (old request :) but than blocks, and gives errors msg that amount needs to be entered

![image](https://cloud.githubusercontent.com/assets/1532439/11170350/e5e76d8a-8bd1-11e5-8f09-355e0f2cb596.png)

**Comment by chabito79** [comment]
I'm having the same problem! :(

**Comment by retroneo** [comment]
Many with same problem ( See #4686 / #4828 ) - still present in  v6.24.5
