### ISSUE TITLE
Custom fields in BOM Operation not mapped to Work Order Operation when creating Work Order from BOM

### ISSUE THREAD

**Issue by northern-concrete** [frappe/erpnext#42927]
### Information about bug

Custom field, "custom_weight", added to both BOM Operation and Work Order Operation doctypes. 

![image](https://github.com/user-attachments/assets/e737f6d7-2b59-4a45-9607-f05f32443089)

![image](https://github.com/user-attachments/assets/68894d20-36c3-48a7-809f-a34cf5e05f39)

 

### Module

manufacturing

### Version

ERPNext: v15.33.2
Frappe Framework: v15.38.0

### Installation method

docker

**Comment by Nihantra-Patel** [comment]
Because the table is different, if the table name is the same in both doctypes then it will auto-fetch.

You have to map the custom field using the server/client side with custom logic. It's not a BUG!

**Comment by northern-concrete** [comment]
The table names in both DocTypes (BOM and Work Order) for the operations are the same (operations), so my confusion.  Documentation states exactly what you said, however, does not work that way.

I will follow your advise.

Thanks for your help!

![image](https://github.com/user-attachments/assets/d0ff1f03-4c19-419d-b043-0275303c81a3)

![image](https://github.com/user-attachments/assets/0bce56ad-e997-461f-9c79-35102ef98740)
