### ISSUE TITLE
Website User Edit Profile Link Break

### ISSUE THREAD

**Issue by justinlusg** [frappe/erpnext#4293]
![step1](https://cloud.githubusercontent.com/assets/12539216/11021586/096df36a-8681-11e5-84ec-133f393a3e81.png)

![step 2](https://cloud.githubusercontent.com/assets/12539216/11021587/0d1e14e0-8681-11e5-9d14-085e6b0fdae1.png)

When Website user click on "Edit Profile", will receive this page error.

**Comment by justinlusg** [comment]
Is this a bug?

**Comment by anandpdoshi** [comment]
Cannot reproduce in the latest code
