### ISSUE TITLE
is_pro_applicable default should be 0

### ISSUE THREAD

**Issue by justinlusg** [frappe/erpnext#4298]
![image](https://cloud.githubusercontent.com/assets/12539216/11030716/d39ea420-870a-11e5-8f11-90a19af959d0.png)

There will be an error if "Maintain Stock" is unchecked and if Manufacturing option is disabled.

![image](https://cloud.githubusercontent.com/assets/12539216/11030757/2176c498-870b-11e5-87f3-0f3303ffe207.png)

The "Manufacturing" collapsible would not appear and there would be no way to workaround and save the non-stock item.

Should default is_pro_applicable to 0 to avoid this issue.

**Comment by nabinhait** [comment]
Fixed this, now `is_production_order` will be unchecked automatically if you uncheck "Maintain Stock" option. The fix will be released soon.
