### ISSUE TITLE
Raven chat banner is hidden under new app sidebar.

### ISSUE THREAD

**Issue by Altrix-One** [frappe/erpnext#42990]
### Information about bug

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/946fde30-73fa-4bfe-978a-26ad330dfa97">

ERPNext v16 - App Sidebar is currently over the Raven chat bar. Raven should dynamically shift with sidebar

### Module

other

### Version

Frappe Framework: v16.0.0-dev (HEAD)
ERPNext: v16.0.0-dev (HEAD)

### Installation method

FrappeCloud

**Comment by Nihantra-Patel** [comment]
It's a Raven chat app issue, not a frappe/ERPNext issue. Currently, in the develop branch, we are changing the UI, so there are lots of bugs. It's under development mode. I suggest using the stable version.
