### ISSUE TITLE
[Bug] : Leave Application - Leave Balance Before Application displays wrong value

### ISSUE THREAD

**Issue by mayur-patel** [frappe/erpnext#4300]
@anandpdoshi 
There is a bug in the system. The leave_application.js file is passing doc.from_date and doc._todate to get_leave_balance function which are from and to date of the leave being applied. It should be passing the fiscal_year.from_date and fiscal_year.to_date to the get_leave_balace to get total leaves taken in that time period.

**Comment by nabinhait** [comment]
Released a major update related to leave management, please check now.

**Comment by mayur-patel** [comment]
The calculation for leave balance before application doesn't take into consideration of the upcoming future leaves that are approved. So User think that they have more leave remaining.

**Comment by mayur-patel** [comment]
Another bug is when you open an existing leave application that is been saved before but not approved yet, if you change the from date of the existing leave application then total is always displayed as 0.50 days. Which is not correct. System seems to update it to the correct total when user clicks on Save but before that user get confused by seeing 0.50 and hence they call IT support team about it. We have had 11 complaint since the new leave changes has been rolled out. They have started to doubt the the system since the calculation are incorrect. Please help to fix this issue. 

![leave error](https://cloud.githubusercontent.com/assets/2786730/11365381/ede60370-929d-11e5-8ec3-08fbd513ee7c.PNG)
