### ISSUE TITLE
Accounts Payable doesn't match General Ledger

### ISSUE THREAD

**Issue by SvbZ3r0** [frappe/erpnext#43012]
### Information about bug

Accounts Payable is considering some payments twice and therefore giving the wrong status.
![image](https://github.com/user-attachments/assets/7017a4b0-d338-4fc7-98a6-b4cd08f17a3a)
All entries where paid amount is twice of invoiced amount should actually have paid amount equal to invoiced amount.
For example, here's the ledger related to entry 13 in the above image:
![image](https://github.com/user-attachments/assets/fec69ad6-3a09-49b7-9fbc-3541923e9cbb)
And here, the ledger related to entry 25:
![image](https://github.com/user-attachments/assets/362d5fb4-2042-451e-adbc-12b3543ba862)

As you can see, some entries are accounted for twice in the Payables Report and hence gives us wrong information. I believe this might be related to Payment Reconciliation entries, but I'm not really sure. Payables Report is unusable until this is fixed.

Possibly related to #42991 

### Module

accounts

### Version

crm 1.20.0
erpnext 15.34.0
frappe 15.39.1
hrms 15.28.0
india_compliance 15.13.2

### Installation method

manual install

**Comment by ruthra-kumar** [comment]
Recheck after enabling 'Ignore Account Closing Balance' in Accounts settings

**Comment by SvbZ3r0** [comment]
I've tried with that setting on and off, but it didn't help. At all.

I did notice that sometimes, on setting or changing the Project (or possibly other Accounting Dimensions) in the child table in a submitted Journal Entry, the Payables report got updated and the value from those JEs weren't showing up twice, BUT that method didn't work for all JEs. I believe this has nothing to do with accounting dimensions themselves but rather with the fact that Payment Ledger Entries are recreated.

Another thing I've noticed is that only some JEs are accounted for twice in the Payables report. I haven't come across a situation where a Payment Entry has this problem.

**Comment by SvbZ3r0** [comment]
This has to do with allocating correct amounts to the correct projects. ie. if Purchase JE is Project 1, Payment JE is Project 2, but said Payment is allocated to said Purchase, it leads to this issue. It should not occur during proper Accounting Entries.
I had this issue because I was importing from Tally and mass reconciling all Payments and Purchases. That caused random (maybe on a FIFO basis) payment allocations to purchases. So even when the ledger tallied up, individual project ledgers were open.
I had to go back and manually fix Project allocations on each JE. Which in turn leads to this bug: #43575
