### ISSUE TITLE
Supposed bug in the handling of multi-currency transactions when creating GL entries from a journal entry.

### ISSUE THREAD

**Issue by jnoufaily** [frappe/erpnext#43021]
### Information about bug

Supposed bug in the handling of multi-currency transactions when creating GL entries from a journal entry. The system is incorrectly applying the exchange rate from the first row to all subsequent rows, leading to inaccurate currency conversions.

*GHS is the company currency*

### 01. Journal Entry
Create a multi-currency journal entry with the following data as it's rows.
| Row | Account | AccountCurrency | Party Type | Party No     | Exchange  Rate | Debit in  Account  currency | Credit in  Account  currency | Debit in  Company  currency | Credit in  Company  currency |
|-----|---------|-----------------|------------|--------------|----------------|-----------------------------|------------------------------|-----------------------------|------------------------------|
| 1   | 01      | EUR             | Supplier   | EUR Supplier | 2,000          | 100                         |                              | 200,000                     |                              |
| 2   | 02      | USD             | Supplier   | USD Supplier | 1,250          | 50                          |                              | 62,500                      |                              |
| 3   | 03      | GHS             |            |              | 1              |                             | 262,500                      |                             | 262,500                      |
|     |         |                 |            |              |                |                             |                              |                             |                              |

After the unfolding of the above transaction in the system, adjacent GL entry records are create wherein lies our problem.

### 2. GL Entry

**Current Output:**
| GL Entry No | Account | Account  Currency | Transaction  Currency | Exchange  Rate | Debit in Accounting Currency | Credit in  Accounting Currency | Debit in Company  Currency | Credit in  Company  Currency | Debit  Amount in  Transaction  Currency | Credit  Amount in  Transaction  Currency |
|-------------|---------|-------------------|-----------------------|----------------|------------------------------|--------------------------------|----------------------------|------------------------------|-----------------------------------------|------------------------------------------|
| 1           | 01      | EUR               | EUR                   | 2,000          | 100                          |                                | 200,000                    |                              | 100                                     |                                          |
| 2           | 02      | USD               | EUR                   | 2,000          | 50                           |                                | 62,500                     |                              | 31.25                                   |                                          |
| 3           | 03      | GHS               | EUR                   | 2,000          |                              | 262,500                       |                            | 262,500                     |                                         | 131.25                                   |

For the above respective GL entries of the Journal Entry, entries 2 and 3 continue to use the currency and exchange rate of the first row which is EUR and 2000

**Expected Output:**
| GL Entry No | Account | Account  Currency | Transaction  Currency | Exchange  Rate | Debit in Accounting Currency | Credit in  Accounting Currency | Debit in Company  Currency | Credit in  Company  Currency | Debit  Amount in  Transaction  Currency | Credit  Amount in  Transaction  Currency |
|-------------|---------|-------------------|-----------------------|----------------|------------------------------|--------------------------------|----------------------------|------------------------------|-----------------------------------------|------------------------------------------|
| 1           | 01      | EUR               | EUR                   | 2,000          | 100                          |                                | 200,000                    |                              | 100                                     |                                          |
| 2           | 02      | USD               | USD                   | 1,250          | 50                           |                                | 62,500                     |                              | 50                                      |                                          |
| 3           | 03      | GHS               | GHS                   | 1              |                              | 262,500                       |                            | 262,500                     |                                         | 262,500                                  |

Each GL Entry should use its own correct exchange rate (2,000 for EUR, 1,250 for USD, 1 for GHS).

### Module

accounts

### Version

Frappe Framework: v15.39.2
ERPNext: v15.34.0

### Installation method

FrappeCloud

**Comment by ruthra-kumar** [comment]
Couldn't replicate this.

Ex:
Journal against 2 suppliers - USD and EUR, with 80 and 95 as exchange rate respectively.
![Screenshot from 2024-09-06 14-22-37](https://github.com/user-attachments/assets/5b30d2ae-46b8-4348-94c0-7258833fedcb)

GL's use the same exchange rate for each account / row
![Screenshot from 2024-09-06 14-22-02](https://github.com/user-attachments/assets/e8f4aea0-9f94-4702-86b5-16404e836762)

**Comment by jnoufaily** [comment]
Hi Ruthra,

Thank you for the reply.

Would it be possible to do a call and I can run you through the case live?

Regards,
Joseph

**Comment by ruthra-kumar** [comment]
Unfortunately, won't be available for a call.

It would be better if you can provide below details.
1. Is this Journal manually created or generated by system?
2. Is there any customization done on Journal Entry - through app or Server script

**Comment by jnoufaily** [comment]
No problem I will elaborate more through a detailed explanation on Monday.

Concerning the following
Is this Journal manually created or generated by system? Manually created
Is there any customization done on Journal Entry - through app or Server script? a minor customization is only done for creating a custom naming series

**Comment by ruthra-kumar** [comment]
What is the exchange rate maintained in account rows for the Journal Entry? If possible can you post a screenshot?

Also, a screenshot of the GL Entry doctype filtered on that Journal Entry, with Debit, Credit, Debit in Account Currency and Credit in Account Currency fields visible

**Comment by jnoufaily** [comment]
As requested
![image](https://github.com/user-attachments/assets/a90d049e-28e6-4ddd-a711-cdee2ab3807c)
[GL Entry.xlsx](https://github.com/user-attachments/files/16907213/GL.Entry.xlsx)
![image](https://github.com/user-attachments/assets/b5330c8f-a301-4847-aea8-c79427937610)

**Comment by ruthra-kumar** [comment]
Debit  and Credit values are fine, only the `transaction_exchange_rate` had incorrect value. It has been fixed by https://github.com/frappe/erpnext/pull/43331
