### ISSUE TITLE
Gross Profitability report for Drop Ship items

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#4302]
Since stock is not maintained for the drop ship items, there is no valuation rate available as well. Perhaps we should look at Purchase Invoice for the item's rate, and accordingly provide Gross Profit report for the drop ship item.

**Comment by PawanMeh** [comment]
Last purchase rate was added for non-stock items, issue 6089 can be looked at for reference. If this meets the requirement, this issue can be closed.
