### ISSUE TITLE
[Paid Development] - Configurable behavior for Exchange rate in Multi-Currency Account

### ISSUE THREAD

**Issue by MaxMorais** [frappe/erpnext#4303]
Continuation from https://github.com/frappe/erpnext/issues/4273
@nabinhait After our talk, I started a discussion with the accountant, and him say to me, that your suggestion can work, for certain cases, but not for money purchase or billing.

In our case these operations are ruled by laws, so while I'm doing a transfer between accounts in the banks, I have a daily standard exchange rate that should be followed in the day, and the same exchange rate, should be reported in the books.

We are able to sponsor the development of a new behavior for this situation, where instead of the actual behavior the system dont use a exchange rate based in the average movement, we want be able to inform the value in local currency and the exchange rate, or the value in the foreign currency.

Can you give-me a quote for this feature?

**Comment by MaxMorais** [comment]
I discovered another detail to include in the quote of this issue:

![balance general](https://cloud.githubusercontent.com/assets/1288676/11109547/bd8b90f6-88d8-11e5-97d5-45a61a559e97.png)

In the balance we have in the accounts, the amount in USD and MXN, but I would love configure the amount to be used in the Plan of Accounts, if you take a look in the bellow image you will see that the amount of "Clientes Extrangeros" is reported in MXN, but the amount is from USD

![plan de cuentas](https://cloud.githubusercontent.com/assets/1288676/11109546/bd8a7702-88d8-11e5-986c-a8b19a6c6500.png)

**Comment by nabinhait** [comment]
@MaxMorais We have decided to remove the validation to force-apply the average exchange rate in case of bank transfer. 

And for the second query, in Chart of Accounts, I will try to show balance in both currency wherever applicable.

Both the changes will go to the standard product, so no quotation for customization.

**Comment by MaxMorais** [comment]
:+1: @nabinhait
