### ISSUE TITLE
Timesheet feature in projects becoming unresponsive

### ISSUE THREAD

**Issue by MartinFulgueiras** [frappe/erpnext#43035]
### Information about bug

When using timesheet in projects, once you complete the header info and start inputing time sheets, the system becomes unresponsive and doesn't save a draft of the timesheet. The feature worked ok until some versions ago. No idea what might be happening. No error message appears or gets registered in the error log. I attach a video. 

[Kooha-2024-09-03-11-48-25.webm](https://github.com/user-attachments/assets/ddc8ceab-c351-4475-845e-989d96a305e4)

Quite strangely, when the error occurs the screen recording app also shows an error (twice). I believe the video already shows the problem, but latter the full timesheet feature becomes unresponsive, it doesn't save the draft and everything needs to be restarted. Sometimes it records the timsheet, sometimes it doesn't 

# System Details Report
---

## Report details
- **Date generated:**                              2024-09-03 11:55:54

## Hardware Information:
- **Hardware Model:**                              Dell Inc. Inspiron 5584
- **Memory:**                                      16.0 GiB
- **Processor:**                                   Intel® Core™ i7-8565U × 8
- **Graphics:**                                    Intel® UHD Graphics 620 (WHL GT2)
- **Graphics 1:**                                  NVIDIA GeForce MX130
- **Disk Capacity:**                               2.0 TB

## Software Information:
- **Firmware Version:**                            1.22.1
- **OS Name:**                                     Ubuntu 24.04.1 LTS
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               46
- **Windowing System:**                            X11
- **Kernel Version:**                              Linux 6.8.0-41-generic

### Module

projects

### Version

ERPNext: v15.33.4

Frappe Framework: v15.39.0

### Installation method

docker

**Comment by MartinFulgueiras** [comment]
When I manage to save the timesheet (by not trying to edit a time sheets and just inputting the data in the table), then I can't add more lines / time sheets. Sometimes if I refresh, the lines appear empty, but the behaviour is not regular. I attach video...
[Kooha-2024-09-03-12-06-30.webm](https://github.com/user-attachments/assets/a5cdba99-5109-4a93-bfe8-f3303a57abb9)

**Comment by Nihantra-Patel** [comment]
Duplicate Issue: https://github.com/frappe/erpnext/issues/42889

You can track it there.
