### ISSUE TITLE
On Work Order Screen, In Items Child Table UOM is not showing.

### ISSUE THREAD

**Issue by nitin-anantpranali** [frappe/erpnext#43050]
### Information about bug

On Work Order Screen, In Items Child Table UOM is not showing.

### Module

manufacturing

### Version

Installed Apps
ERPNext: v15.30.0 (HEAD)
Frappe Framework: v15.36.0 (HEAD)
Frappe HR: v15.24.0 (HEAD)
India Compliance: v15.11.0 (HEAD)
Payments: v0.0.1 (HEAD)

### Installation method

FrappeCloud

**Comment by Nihantra-Patel** [comment]
Share the screenshot or video and provide the steps to reproduce the issue. We tested the latest version and couldn't find the issue.

**Comment by nitin-anantpranali** [comment]
<img width="997" alt="image" src="https://github.com/user-attachments/assets/2ec59b27-aa1b-4b99-beb3-fe6460285d7a">

There is no UOM field in child table and at header level...

**Comment by Nihantra-Patel** [comment]
The reason the Unit of Measure (UOM) is not available in the Work Order Item table because the system does not support multiple UOMs for items in Work Orders by default. However, if you require UOM functionality in this table, you can customize it by adding a custom field for UOM. This customization would allow you to track and manage UOM for specific Work Order items based on your requirements.

**Comment by nitin-anantpranali** [comment]
This is a big flaw on the UI side. 
Imagine a scenario where there are multiple items in BOM and the user should get a clear idea about the quantity of the Raw Material which is getting consumed. So on the screen (may be in disabled mode) the UOM should be visible. 

Otherwise until the user do not make Stock Entry he wont get a clear idea about the UOM, whether its in KG or GMs.

Please do not overlook it. We are facing issues while implementation at various clients.

**Comment by nitin-anantpranali** [comment]
This is a typical screen. What user is going to understand by looking at the figures... Whether the quantity is in Kg, Gm, ml, cm, meter????

There should be a clear information on the screen. The units (based on the BOM) should be visible there.


<img width="997" alt="image" src="https://github.com/user-attachments/assets/260b948f-1c13-4b36-b9b3-34adc49202af">

**Comment by umairsy** [comment]
We can simply fetch UoM from BOM Item table? @rohitwaghchaure 

If there is qty, UoM should be there.
