### ISSUE TITLE
[Paid Development Request] Simple Restaurant Module

### ISSUE THREAD

**Issue by jof2jc** [frappe/erpnext#4310]
Hi ERPNext Team,

We have requirement to build restaurant view module.

I have looked through the existing POS View but it's too general and may not fully suit restaurant requirement.

Therefore we'd like to request development for this restaurant module to be integrated with core modules.

The flow for order:
1. First page, customer list in grid-box style (similar with current item grid in Pos View). Each box show customer number (e.g. table 01-30) in the center (large size to suit the box-size). Just display search box on top but user can directly point&tap each customer box without searching.
1. After clicked, it goes to page-2: item grid-box (like in Pos View) but with collapsible section based on item-group (i.e. appetizers, drinks, foods, etc).

Again, search box is provided but user can scroll down to each section and tap the product. By default, it fetches 20 items per item group section so we need More button if an item-group section has over 20 items.
1. Save the order - status is ordered
2. Pay and submit invoice - status is done/paid/invoiced.
   It would be nice if we can use existing workflow engine for 3rd and 4th step so we can put own status and action before it's submitted.

Another thing is can we have main dashboard? I think the module first start should be from this dashboard:
1. On top, show restaurant list then dashboard display customer table number. User can make a reservation for each customer table. Click the number box - show action (reserve) then Status for this table no. is Reserved. User can put customer info (name,phone,..) who's making reservation.
2. Continued to 1st flow.
3. The customer (table no) box must show different status with different color. If clicked, it goes to active order if any. If not, it goes to sales invoice history list for that customer tableno.
4. Restaurant master record and with child-table to put table no. info. User can define max seats for each table no. We can create multiple restaurant records. I think each restaurant master must be linked with company, territory and warehouse record.
5. For reporting,just define sales report per restaurant with item details with period. I'm little bit confuse whether each restaurant is a customer? So we can use existing reports e.g. sales register, item-wise sales register etc. Please suggestion for this.

The status list are reserved; ordered (customer has ordered menu/has active order...user can add additional menu item in this state); open (it's paid and open for next order/reserve).

Please note so that It can be utilized 100% on touch screen without keyboard.

Hope my explanation describes you well. Let me know your thoughts and best design suggestion. Our main purpose is we can fully utilize ERPNext as core ERP and restaurant-friendly module interface at the front...

I think it's just to modify current Pos view, add restaurant module with dashboard as main page, restaurant master, and sales report. The rest will follows ERPNext cores.

Can you estimate fair development hours? 

Thanks

**Comment by rmehta** [comment]
@jof2jc can you make a few mockups of the screens?

**Comment by jof2jc** [comment]
@rmehta can you give estimation hours for our internal review? Also, do you know easy online tools for  mockup builder? Tks

**Comment by rmehta** [comment]
Try balasmic or pencil.evolus.vn/

**Comment by mhbu50** [comment]
+1

**Comment by woakes070048** [comment]
this could potentially work https://discuss.erpnext.com/t/ideas-for-new-pos-interface/14638

**Comment by PawanMeh** [comment]
Kindly review the new POS interface in v8, if it does not meet requirements, please re-open issue with mock up files attached.
