### ISSUE TITLE
Missing HR Module 

### ISSUE THREAD

**Issue by rithika271999** [frappe/erpnext#43145]
### Information about bug

Not able to find HR modules like Payroll, attendance etc, Tried searching in Search engine with various HR modules but could find only Employee List but rest all fields of HR is not there .
In the Modules section the whole HR module is not visible .

### Module

HR

### Version

14

### Installation method

None

**Comment by mohsinalimat** [comment]
For version 14, if you need hrms then you must have to use below command.

`bench get-app https://github.com/frappe/hrms --branch version-14`

`bench --site sitename install-app hrms`

**Comment by Nihantra-Patel** [comment]
HR module has been separated in version 14 and 15 so you have to install it separately on the site. so follow the Mohsin Ali step.

**Comment by rithika271999** [comment]
Can you guide me through mohin Ali steps
Where can I find it ?

**Comment by Nihantra-Patel** [comment]
https://github.com/frappe/hrms?tab=readme-ov-file#installation

Explore the Bench Commands Cheatsheet: https://frappeframework.com/docs/user/en/bench/resources/bench-commands-cheatsheet
