### ISSUE TITLE
Issue in stock ledger Invariant ledger affecting Gross profit and incoming rate

### ISSUE THREAD

**Issue by maveezmh** [frappe/erpnext#43168]
### Information about bug

![image](https://github.com/user-attachments/assets/630c7b54-5f0f-4129-b194-19d0f8e72efb)

As described in above image if there is an item which comes in and goes out from the stock the incoming rate will be proper while item is coming in but when same item goes out. the system is taking initial incoming rate and the gross profit is calculated based on wrong incoming rate of the item. 

in above example the item was first bought at 72 and sold 
again it was bought 2nd time at 44 and sold in this scenario the system is taking 72 as incoming rate where it should have taken 44 as incoming rate. 
same is happening in next set of transaction.

as a result the incoming value in gross profit report and delivery note is fetched wrong. showing wrong profit margin

![image](https://github.com/user-attachments/assets/712ca738-e64d-4604-b41e-4be250cd341b)

### Module

stock, buying, selling

### Version

ERPNext: v14.60.1 (version-14)

Frappe Framework: v14.62.2 (version-14)

Frappe HR: v14.5.1 (version-14)

Payments: v0.0.1 (version-14)

Vector Customization: v0.0.1 (master)

### Installation method

FrappeCloud

**Comment by maveezmh** [comment]
@dj12djdjs any possible solution for this?

**Comment by maveezmh** [comment]
Hey there, any solution for this?

**Comment by maveezmh** [comment]
@ruthra-kumar

**Comment by dj12djdjs** [comment]
@maveezmh I've tested your above scenario using the Stock Ledger Invariance Check report on version:
frappe: 14.81.6
erpnext: 14.74.3

And it appears to be working correctly on that version. See screenshot.
![image](https://github.com/user-attachments/assets/7fc40c97-e152-4152-ba73-217a165959cf)


Can you confirm?

**Comment by maveezmh** [comment]
@dj12djdjs thanks for confirmation. i guess its issue in previous version. let me update the client site and check.

**Comment by maveezmh** [comment]
closing this issue as completed @dj12djdjs
