### ISSUE TITLE
Email Digest - allow for daily sales (in Sales module)

### ISSUE THREAD

**Issue by lxnow** [frappe/erpnext#4319]
Would request to have the previous feature return: creating daily email digests that provide summary of sales metrics, particularly around:
- daily sales booked (sales orders submitted, aggregated on a per day or some specified time frame basis)
- daily sales invoiced (sales invoices submitted, aggregated on a per day or some specified time frame basis)

Thanks.

**Comment by jwrober** [comment]
Instead of it being blindly daily, would prefer this be a setting somewhere that can be configurable.

**Comment by rmehta** [comment]
https://github.com/frappe/erpnext/issues/10497
