### ISSUE TITLE
[BUG]: Leave Balance Report

### ISSUE THREAD

**Issue by justinlusg** [frappe/erpnext#4322]
![image](https://cloud.githubusercontent.com/assets/12539216/11174194/ad6e6028-8c5b-11e5-9470-aa46b9580179.png)

The leave balance report is not working correctly after the recent update to change leave application from fiscal year to calendar based

**Comment by justinlusg** [comment]
There are 5 employees with 16 days of annual leave each, however after the recent update, the annual leave count all are added to 1 employee instead. (e.g. 16 days x 5 employees = 80 days)

**Comment by nabinhait** [comment]
We have fixed this report, it will be released today
