### ISSUE TITLE
Set "Available Batch Report" Default Date to Today

### ISSUE THREAD

**Issue by jayfiro** [frappe/erpnext#43220]
### Information about bug

Currently, the default date for the "Available Batch Report" is set to a month before Today.

The expected behavior is that the date should default to Today.
 
![Screenshot 2024-09-13 at 15 48 28](https://github.com/user-attachments/assets/1b54811c-a144-4361-b666-316d46f29733)

Suggested fix for for available_batch_report.js

![Screenshot 2024-09-13 at 16 05 11](https://github.com/user-attachments/assets/91e3152e-48f1-4245-b0ec-3ae0665626d5)

### Module

stock

### Version

Frappe and ERPNext v14 and v15.

### Installation method

FrappeCloud

**Comment by maveezmh** [comment]
looks like its been already fixed
![image](https://github.com/user-attachments/assets/6784fc94-6f43-4b0b-b209-89b1d9891318)

**Comment by jayfiro** [comment]
That's right! Thank you for pointing that out. It was fixed by #43121
