### ISSUE TITLE
[Feature-request] Auto-repeat Letterhead on every page

### ISSUE THREAD

**Issue by TanujW** [frappe/erpnext#4324]
Hi,

Is it possible to implement the letterhead into every page?
Currently the header is mapped to the top of the first page, and the footer to the bottom of the last page.

Thank You all!

**Comment by cgpurbaugh** [comment]
There is a possible paid development here: https://discuss.erpnext.com/t/header-footer-development/7442/9 

If you could contribute, it would help alot.

**Comment by TanujW** [comment]
Can we get an estimate for this?

**Comment by rmehta** [comment]
@TanujW @cgpurbaugh I spent some time looking into this. This is not possible in the current HTML/CSS specs, so please don't make the payment. The work around of manually checking "page" break should work.

**Comment by MaxMorais** [comment]
Hi folks!

A old time ago, while we are using wnframework yet, I created a workaround for JavaScript, to calculate the page break in the browser, this is here https://jsfiddle.net/MaxMorais/q3q38/embedded/result/

After the inclusion of weasy-print to generate PDF's, I found this discussion https://github.com/Kozea/WeasyPrint/issues/92, and this gist https://gist.github.com/pikhovkin/5642563, for solve this issue!

**Comment by rmehta** [comment]
weasyprint had issues when we last looked at it. @MaxMorais Have you tested recently?

**Comment by MaxMorais** [comment]
@rmehta I dont know if your issue are the same issue that I found, where the sizes of the page dont match or header and footer or are overlapping the page body, if the issue is the same, do you need get the size of the header and the footer and adds it with padding-top and padding-bottom in the page-body container.

**Comment by anandpdoshi** [comment]
Fixed!
