### ISSUE TITLE
[Usability] User - confusion between Role and Module

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#4325]
I have observed that after creating User, some only assign Module to new User, and doesn't assign Roles.

Suggestion: We should merge Module and Roles. Firstly Module should be assigned to User. On checking Module, relative Roles should be visible. 
Example: For the new user, first Account module should be checked. Then Account User or Account Manager Role or both should be assigned to User.

**Comment by kennethsequeira** [comment]
@umairsy closing this, since V11, user permissions were refactored, module permission was removed.
