### ISSUE TITLE
Payment Reconciliation Issue for Advance Payment Against Sales Order

### ISSUE THREAD

**Issue by parasonit** [frappe/erpnext#43272]
### Information about bug

**Title:** Payment Reconciliation Issue for Advance Payment Against Sales Order

**Description:**

There is a bug in the payment reconciliation process when handling advance payments received against a sales order.

**Steps to Reproduce:**

1. Create a sales order and receive an advance payment for it.
2. Post the payment entry against the sales order.
3. Generate a sales invoice for the sales order.
4. Proceed to reconcile the payment against the sales invoice.

Notice that the payment entry reconciles successfully, but it still appears on the invoice side of the payment reconciliation screen.

**Expected Behavior:**

The payment entry should be removed from the invoice side of the reconciliation screen once it has been successfully reconciled.

**Actual Behavior:**

The payment entry remains visible on the invoice side, despite being reconciled.

Below is the example for reference.
![AdvanceagainstSalesOrderPmtReconciliationissue-ezgif com-resize (1)](https://github.com/user-attachments/assets/2a507aec-d0fd-44d8-8cee-fd297f5dc636)

### Module

accounts

### Version

ERPNext: v15.35.1 (version-15)

Frappe Framework: v15.40.6 (version-15)

India Compliance: v15.13.2 (version-15)

### Installation method

None

**Comment by ruthra-kumar** [comment]
Fixed in https://github.com/frappe/erpnext/pull/43627
