### ISSUE TITLE
Negative Sales Order Item (Discount or Refund) does not transfer to invoice

### ISSUE THREAD

**Issue by monojoker** [frappe/erpnext#4330]
Hi Guys,

We regularly apply discounts to some customers for various reasons and to do this we add a line item to the Sales Order to adjust the final price but show all the detailed charges. When you generate a Sales Invoice for such Orders the negative (discount) item line is ignored and not added to the Invoice.

Can this be changed to allow such "inline discounts" and refunds to occur please? It would allow much greater flexibility in our invoicing and I suspect other companies would do similar.

Example Sales Order contains 4 lines including last line of discount:

![image](https://cloud.githubusercontent.com/assets/10917366/11199717/e927bd24-8d1b-11e5-8062-724869f4f0aa.png)

Sales Invoice only generates positive amount lines:

![image](https://cloud.githubusercontent.com/assets/10917366/11199723/0093cfa2-8d1c-11e5-84e7-5cc589b2964d.png)

Please let me know.

Thanks
Liam.

**Comment by monojoker** [comment]
Hi Guys, an feedback on this? Should it work, not work? Thanks.

**Comment by nabinhait** [comment]
@monojoker Pushed a fix https://github.com/frappe/erpnext/pull/4407

**Comment by monojoker** [comment]
Many thanks @nabinhait and @rmehta really helpful for us!
