### ISSUE TITLE
"Save" Button (DRAFT) Not Working for Sales Orders, Invoices, and Other Documents in ERPNext

### ISSUE THREAD

**Issue by edardev** [frappe/erpnext#43323]
### Information about bug

The "Save" button (in Draft mode) for several key documents, including Sales Orders and Invoices, is not functioning as expected. When attempting to save a document as a draft, the system fails to save the document. Currently, the document is only saved when the user proceeds to submit it, preventing users from saving drafts for later review or updates.

Tested in FrappeCloud and Docker Compose installation.

### Module

accounts, buying, selling

### Version

ERPNext: v15.36.1 (HEAD)

Frappe Framework: v15.41.0 (HEAD)

Frappe HR: v15.29.0 (HEAD)

Payments: v0.0.1 (HEAD)

Print Designer: v1.4.2 (HEAD)

### Installation method

FrappeCloud

**Comment by Nihantra-Patel** [comment]
We tested locally and also in the frappe cloud side, but we haven't found the issue.


https://github.com/user-attachments/assets/605ace18-8fc3-4e79-bb1b-c0ca9821ee28




If your site is hosted on frappe cloud and if support is available in your plan, raise a [support ticket](https://support.frappe.io).
