### ISSUE TITLE
My Account secureedgsal.erpnext.com is too slow we cannot work. can you check please the service or the server. we have tried to open the account on 2 diffrent connections and mane PC's and problem is the same.

### ISSUE THREAD

**Issue by marioseif-ceo** [frappe/erpnext#43354]
### Information about bug

My Account secureedgsal.erpnext.com is too slow we cannot work. can you check please the service or the server. we have tried to open the account on 2 different connections and mane PC's and problem is the same.

### Module

accounts

### Version

Frappe Framework: v13.58.21 (HEAD)
ERPNext: v13.55.2 (HEAD)

### Installation method

FrappeCloud

**Comment by Nihantra-Patel** [comment]
If site hosting on frappe cloud then raise the support ticket on the [frappe cloud](https://support.frappe.io).
