### ISSUE TITLE
Cannot Delete a Project Update

### ISSUE THREAD

**Issue by kptdaaron** [frappe/erpnext#43371]
### Information about bug

There is no "Cancel" action in the project update therefore can't delete it. 
![Screenshot 2024-09-24 at 9 03 50 PM](https://github.com/user-attachments/assets/de7ed990-261e-4067-8200-35a92c7d4512)

### Module

projects

### Version

ERPNext Version: V15

### Installation method

docker

**Comment by Nihantra-Patel** [comment]
You have to give the cancel rights to the user role. so please check the video.


https://github.com/user-attachments/assets/d55f6f29-ba62-4333-9269-ba90c8c894a8
