### ISSUE TITLE
Purchase Order from Supplier Quotation does not auto-populate "Supplier's quotation reference" field

### ISSUE THREAD

**Issue by fishter** [frappe/erpnext#43383]
### Information about bug

Creating a Purchase Order from a Supplier Quotation does not auto-populate the "Supplier's quotation reference" in the New Purchase Order.

This should be a straightforward pull from the source document to the new one.

### Module

buying

### Version

Frappe 14.81.4
ERPNext 14.74.1

### Installation method

FrappeCloud

**Comment by Nihantra-Patel** [comment]
Everything is working fine. No problems were encountered in the latest version 14 and version 15.


https://github.com/user-attachments/assets/59445a8a-7b40-4350-a09b-88207f701a3a

**Comment by fishter** [comment]
I did not mean the ERPNext reference of the supplier quotation. I meant the supplier's reference - the one the supplier gives on their quotation. In the following screenshot it is "350003185", visible at the bottom right
![image](https://github.com/user-attachments/assets/72629938-0391-4679-8bec-575f0ddf8284)

This reference does not get pulled into the Purchase Order when it is created from the Supplier Quotation. You can see here the Supplier quote reference is blank.
![image](https://github.com/user-attachments/assets/84f804d6-09a6-4f91-a5a6-05d3228cfe48)

**Comment by Nihantra-Patel** [comment]
It's your custom field and custom requirement, you can customize in your custom app according to the scenario.

**Comment by fishter** [comment]
Ah. That's a bit embarassing! Sorry for wasting your time.
