### ISSUE TITLE
Feature Request: Enable Child Table Fields in Quick Entry for Parent Doctype (Contact)

### ISSUE THREAD

**Issue by falahteam** [frappe/erpnext#43404]
Description: I would like to request an enhancement to the Quick Entry functionality in ERPNext, specifically for the Contact doctype, which currently does not display fields from its child tables (Contact Email and Contact Phone) in the Quick Entry form.

Current Behavior: After enabling the Quick Entry checkbox for the child tables and checking the "Allow in Quick Entry" option for their fields in the Customize Form, the child table fields still do not appear in the Quick Entry form. Only the parent doctype fields are displayed.

Desired Behavior: It would be beneficial if the fields from the child tables could be included in the Quick Entry form for the Contact doctype. This would streamline data entry and enhance user experience by allowing users to input contact information more efficiently.

Use Case: Many users manage contacts with multiple email addresses and phone numbers. Having the ability to enter this information directly in the Quick Entry form would save time and reduce the need for additional clicks to open the full form.

Proposed Solution: Consider implementing the option to include child table fields in the Quick Entry form alongside the parent fields, allowing users to add or edit contact details seamlessly.

**Comment by Nihantra-Patel** [comment]
Duplicate Issue: https://github.com/frappe/frappe/issues/27918
