### ISSUE TITLE
Bulk transaction feature merge to version-15?

### ISSUE THREAD

**Issue by kittiu** [frappe/erpnext#43419]
@ruthra-kumar 

For this bulk transaction feature,

https://github.com/frappe/erpnext/pull/43058

Is this plan to merge in version-15?

Thank you

**Comment by ruthra-kumar** [comment]
There wasn't any plan. But I don't see any reason not to, as the change is simple and non-breaking.

**Comment by ruthra-kumar** [comment]
Backported https://github.com/frappe/erpnext/pull/43434
