### ISSUE TITLE
Getting error while uploading leads

### ISSUE THREAD

**Issue by ajinkyagadewar** [frappe/erpnext#4348]
Hello,

Everything is running fine but getting error while uploading leads. 
![notpermitted](https://cloud.githubusercontent.com/assets/3275617/11300315/0400f418-8fb4-11e5-99e3-4972ff6df52d.png)

**Comment by anandpdoshi** [comment]
Fixed. Please update your system.

If you are on cloud, just try again.

Best,
Anand Doshi

ERPNext

**Comment by ajinkyagadewar** [comment]
Fixed. Thanks.
