### ISSUE TITLE
Issue in Serial and  Batch Bundle creation for Rejected Quantity in Purchase Reciept Doctype

### ISSUE THREAD

**Issue by Akshaths12** [frappe/erpnext#43492]
### Information about bug

Below is the Scenario of the issue

I have an Item RM001 which is serial number enabled , I have created below serial numbrers manually which are not yet active
SN0001
SN0002
SN0003
SN0004
SN0005

In Purchase reciept document , I am adding the below serial numbers to accepted Warehouse “ Stores”  through scanning using Add Serial/Batch No button  at Item level as shown below SS
SN0001
SN0002
SN0003

![image](https://github.com/user-attachments/assets/82eae298-eb95-47be-afa7-2341fe77083f)

After that Updating the rejected serial numbers through the option “ Add Serial/ Batch No ( Rejected Qty)  

![rejected](https://github.com/user-attachments/assets/32479bb6-c7ed-4047-b816-95ba48cd4440)

First issue here is Rejected Warehouse is not fetching automatically

Second for rejected serial numbers a Seperate batch bundle is not creating , It is overriding the previously created accepted serial number Serial and Batch Bundle document

Also System is throwing below error once we click on update serial number button. System Automatically changing the rejected warehouse

![image](https://github.com/user-attachments/assets/ec714724-804d-45df-8b27-885fc01b00dc)

### Module

stock

### Version

ERPNext: v15.36.2 (HEAD)

Frappe Framework: v15.42.0 (HEAD)

### Installation method

None

**Comment by rohitwaghchaure** [comment]
@Akshaths12 We have fixed this issue, please update the site and check
