### ISSUE TITLE
Approved is not translated on the pdf files - Full Name and Status also could not be translated

### ISSUE THREAD

**Issue by Ferohers** [frappe/erpnext#4350]
![image](https://cloud.githubusercontent.com/assets/14891349/11304334/37a31278-8fb0-11e5-8661-1f6f78f83b4a.png)

I guess this Full name and status is in "apps\erpnext\erpnext\hr\doctype\employee\employee.json". 
However I could not find any way to translate Full Name and Status
"apps/erpnext/erpnext/hr/doctype/employee/employee.json +134,Full Name,Ad Soyad" this did not work

![image](https://cloud.githubusercontent.com/assets/14891349/11304359/5fcb9f4a-8fb0-11e5-923a-fc79abb7b579.png)

**Comment by Ferohers** [comment]
The issue persist on different languages as well

**Comment by rmehta** [comment]
Fixed
