### ISSUE TITLE
Item Name field in "Stock Reconciliation Item"

### ISSUE THREAD

**Issue by Devens** [frappe/erpnext#4351]
It is becoming difficult to know the item from item code. So, we request to have Item Name Field in "Stock Reconciliation Item" table.

**Comment by heepdog** [comment]
I would second this request. I can get the Item name in using the customize forms, however it only works for manual entry not using get items from warehouse. Would be happy with a refresh button that would fill in the missing fields.

**Comment by nabinhait** [comment]
Added in v7
