### ISSUE TITLE
Item Manufacturers as List rather then text

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#4352]
Can we make the manufacturers that are selectable in the item a list instead of free text? I believe most companies would want a list of all the manufacturers to ensure data consistency.

**Comment by dottenbr** [comment]
see also https://github.com/frappe/erpnext/pull/3888

**Comment by rmehta** [comment]
@dottenbr yeah should be easy.

**Comment by dottenbr** [comment]
issue is fixed with https://github.com/frappe/erpnext/pull/8134
