### ISSUE TITLE
Valuation Rate | Avg Rate | FIFO Rate

### ISSUE THREAD

**Issue by dineshpanchal93** [frappe/erpnext#43560]
### Information about bug

As per the income tax, All the CA's are asking for the FIFO-based valuation is setup to give us the summery of how the consumption is being done FIFO or Moving Average

There is report called Stock ledger Invariant  we can see Consumption rate is based on FIFO

How we can get those in Stock balance?

### Module

accounts, stock

### Version

V15

### Installation method

manual install

**Comment by frewper** [comment]
Can you please be more elaborate on the question. More brief would help. Unable to understand the question

**Comment by rohitwaghchaure** [comment]
Stock Balance is summary of the Stock Ledger report. You better check the stock ledger report or customized it according to your requirement.
