### ISSUE TITLE
[Paid Development] - Bank Reconciliation 

### ISSUE THREAD

**Issue by justinlusg** [frappe/erpnext#4356]
Currently Bank Reconciliation can only be done line by line within the ERP System. Please let us know how much would it cost to develop the feature for it to be able to be exported and imported again (similar to how stock reconciliation is done right now).

**Comment by rmehta** [comment]
yeah should be done.

**Comment by justinlusg** [comment]
Can you give me a quote for this?

**Comment by rmehta** [comment]
$300

**Comment by justinlusg** [comment]
I've a budget of only $200, can it be done within $200?

**Comment by rmehta** [comment]
@justinlusg Ok, but it will take a week. Also please be sure, because last time there was no response from your end after we sent an invoice.

**Comment by justinlusg** [comment]
Yup, this is confirmed, already got the budget. 

The other one, I'm still trying to get the budget of $300, because similarly I only got $200 budget for the other function too.

**Comment by PrakashH** [comment]
@justinlusg  PayPal invoice 0084 sent you.

**Comment by justinlusg** [comment]
Received with thanks, will make payment soon.

**Comment by justinlusg** [comment]
Payment made.

**Comment by rmehta** [comment]
Thanks. Will update you as soon as its done.

**Comment by justinlusg** [comment]
@rmehta if i've a customer that wants to develop certain features that is not made public (e.g. for example some special tax reports, or certain function customisation) do you all provide the development service?

**Comment by rmehta** [comment]
No. Please add comments only relevant to this issue here.

**Comment by rmehta** [comment]
@justinlusg Fixed via https://github.com/frappe/erpnext/pull/4386

Turned out to be a lot easier that I thought, I can include the "@" notification project in your sponsorship

**Comment by justinlusg** [comment]
@rmehta wonderful! do we need to add on any more sponsorship for the "@" notification project?

**Comment by justinlusg** [comment]
@rmehta do we need to add on any more sponsorship for the "@" notification project?
