### ISSUE TITLE
Issues with shopping cart

### ISSUE THREAD

**Issue by elektrinis** [frappe/erpnext#4357]
When User is not logged in, I mean when public user is trying to add item to cart, he gets two identical messages on top of each other, saying "Not permitted".
When Administrator tries to do the same, he gets a message "Not defined: Territory".
When other user tries the same, item is added to cart just fine.

Also I would like to point out that, on a good eshop, shopping cart should not work like it is currently designed.
What it is now: public user clicks on Add to cart and he is forwarder to login page. Where he also must somehow input his address. And what about VAT ID?

What it should be like: Public user adds several items to his cart without registering, then he clicks to see the cart, then he clicks on "confirm", then he inputs his email, shipping address and VAT number (!!!), and only then he is registered automatically.
Also registration should not be something "important". No one wants to register on every eshop they buy at. You need to allow purchasing without complex registrations, especially without confirming your email and other nonsense.

**Comment by gmplab** [comment]
Temporary closed.
More information need.
Thanks.
