### ISSUE TITLE
Wrong Stock Valuation 

### ISSUE THREAD

**Issue by bhavyajicomputers** [frappe/erpnext#43580]
### Information about bug

Item Stock Valuation method - Moving Average

Purchased item -A on 1st jan 24 qty one @ 200 warehouse - rack1

Purchased item -A on 2nd jan 24 qty one @ 200 warehouse - rack1

Purchased item -A on 3rd jan 24 qty one @ 0  warehouse - rack2

Item  Stock Valuation method - Moving Average

now  item-A Valuation becomes 133.33

Stock Value Should Be 400

if i sell item from warehouse rack 2 , the stock value remains @ 400 for remaining 2 items-A

it should work out to 133.33 × 2 = 266.66

Kindly do needful

Thanks

### Module

stock

### Version

ERPNext: v14.74.3 (HEAD)
Frappe Framework: v14.81.6 (HEAD)
Frappe HR: v14.33.0 (HEAD)
India Compliance: v14.30.5 (HEAD)
Payments: v0.0.1 (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
Item Stock Valuation method - Moving Average

Purchased item -A on 1st jan 24 qty one @ 200 warehouse - rack1

Purchased item -A on 2nd jan 24 qty one @ 200 warehouse - rack1

Purchased item -A on 3rd jan 24 qty one @ 0  warehouse - rack2

Item  Stock Valuation method - Moving Average

now  item-A Valuation becomes 133.33

Stock Value Should Be 400

if i sell item from warehouse rack 2 , the stock value remains @ 400 for remaining 2 items-A

Stock Value in Balance Sheet is Shown As 400 instead of 266.66





Kindly do needful

Thanks
```

**Comment by rohitwaghchaure** [comment]
Valuation we calculate based on item and warehouse. So the system has calculated correct valuation rate.
Better you use inventory dimension for rack with single warehouse to achieve your use case.
