### ISSUE TITLE
Header Links for Item view like Customer & Supplier View

### ISSUE THREAD

**Issue by Devens** [frappe/erpnext#4359]
Links like Purchase Receipt, Purchase Invoice, Delivery Note, Sales Invoice, (also Quotation, Sales Order, Purchase Order, Opportunity would be helpful). 

![image](https://cloud.githubusercontent.com/assets/10671911/11332948/f91ddd0c-91ef-11e5-95bd-0e83fd1eb202.png)

**Comment by Devens** [comment]
Hi... Any consideration/plan for this request?

**Comment by rmehta** [comment]
@Devens not as of now. But its a good feature to have.

**Comment by Devens** [comment]
If whole thing (all various displays) may take time, only stock (actual qty & project qty) can be displayed it would be very helpful, as checking stock is pretty frequent requirement and checking it through "Show Balance" is little time consuming as actual balance being displayed after scrolling horizontally. (Moreover "Stock Balance" main report is not editable.)

**Comment by Devens** [comment]
Hello. Any plan for this. If everything may take time, can we show Sales Order & Purchase Order for selected item? (As other info can be traced from Balance/ledger reports from View Menu)

**Comment by cgpurbaugh** [comment]
It looks like this has been developed for V7

@Devens is what V7 has what you wanted?
