### ISSUE TITLE
about design of printing format

### ISSUE THREAD

**Issue by omnison** [frappe/erpnext#4361]
[INV369-23-11-2015.pdf](https://github.com/frappe/erpnext/files/41450/INV369-23-11-2015.pdf)

Can I make such print template through ERPNEXT?  And how to make?

**Comment by anandpdoshi** [comment]
Use the print format builder: https://manual.erpnext.com/contents/setting-up/print/print-format-builder

You can edit the CSS of the Print Format from the Print Format record if you want to customise the look further.

Best,
Anand Doshi

ERPNext

**Comment by rmehta** [comment]
https://manual.erpnext.com/contents/customize-erpnext/print-format

**Comment by rmehta** [comment]
@omnison for questions, use https://discuss.erpnext.com. For bug reports, feature requests, use github issues.

**Comment by omnison** [comment]
Dear Rmehta:

Can i pay some to request your company to customize print template according to our requirement(check attachment)?  And share the html code of template with me also. 
[QUO404-24-11-2015.pdf](https://github.com/frappe/erpnext/files/51721/QUO404-24-11-2015.pdf)

And how much.

**Comment by rmehta** [comment]
@omnison you can pay a freelancer. Try posting on http://upwork.com or https://community.erpnext.com
