### ISSUE TITLE
Report: Item Price currency dislay error

### ISSUE THREAD

**Issue by ekpaxp** [frappe/erpnext#4364]
If an item has different currencies used for Buying and Selling, when looking at the Item Price report, both prices are shown in only one currency - typically in the currency of the price that was last edited.
The actual values are correct, and the price list reflects the correct currency so it is only a display issue.

**Comment by rmehta** [comment]
Seems fixed:

<img width="769" alt="screen shot 2016-12-20 at 12 11 40 pm" src="https://cloud.githubusercontent.com/assets/140076/21340566/7e8a41e0-c6ad-11e6-9f12-b9811023838c.png">
