### ISSUE TITLE
Page Workflow Action Not Found

### ISSUE THREAD

**Issue by fawwazid** [frappe/erpnext#43664]
### Information about bug

Hello,

I am encountering an issue when attempting to access the /app/workflow-action page in ERPNext after upgrading from version 13 to 15. The following error message appears:

Error Message:
> Page workflow-action not found
> The resource you are looking for is not available

![Screenshot 2024-10-15 142418](https://github.com/user-attachments/assets/b0466fef-401e-42ab-9855-5dc63be02dd9)

Steps to Reproduce:
- Navigate to /app/workflow-action.
- Observe the error message displayed on the page.

Expected Behavior:
I expect the workflow actions page to load successfully and display the available workflow actions for management.

### Module

other

### Version

- ERPNext: v15.38.2 (version-15)
- Frappe Framework: v15.44.1 (version-15)
- Frappe HR: v15.31.0 (version-15)
- Frappe Lending: v0.0.1 (version-15)
- Payments: v0.0.1 (version-15)

### Installation method

easy-install

**Comment by Nihantra-Patel** [comment]
It's a Role Permission issue on doctype, you have to give or add the role to view and write permission for Workflow Action. Currently default, only Desk User can only access that, so you have to add the role according to the scenario. 

![image](https://github.com/user-attachments/assets/027ae7b5-71e4-484c-90dd-496fc73c6f09)
