### ISSUE TITLE
502 Bad Gateway  nginx

### ISSUE THREAD

**Issue by Ruttie** [frappe/erpnext#4367]
Hello,

I just starting working on my Erp next system online and building all the elements for our company. But just faced this 502 warning online. Is there someone who can help me out?

Thanks.

**Comment by Ruttie** [comment]
it just popped up again. Guess its a server issue.

**Comment by Ruttie** [comment]
it just popped up again. Guess its a server issue.

**Comment by rmehta** [comment]
I hope its working now. Sorry for the inconvenience

**Comment by Ruttie** [comment]
Thank you for the response. Was it a server problem or something I did? Just to know for the future.
