### ISSUE TITLE
Default Print Format matching/linking not logical

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#4371]
When I create a custom print format I have to select which doc type it is for and I can flag it as default. This is good.

![2015-11-25 10_12_48-pcb specification heinrich](https://cloud.githubusercontent.com/assets/9136094/11392938/20403fba-935d-11e5-9b70-06315fc237f1.png)

However now this is not automatically set in the doctype itself where I have a free text field to define it. Should this be automatically set and be a link to the Print Format as autosuggest?

![2015-11-25 10_13_45-pcb heinrich](https://cloud.githubusercontent.com/assets/9136094/11392990/70f60b60-935d-11e5-8fbf-a956bb1087c9.png)

**Comment by rmehta** [comment]
The "Make Default" button makes a property setter (custom setting) and is used more for customization. For developer mode, it should set in the default doctype though.

fixed via https://github.com/frappe/frappe/commit/caac8209c8326e47e12c7211c796b1ed5722ec88
