### ISSUE TITLE
Upgrade Font Awesome

### ISSUE THREAD

**Issue by zsajjad** [frappe/erpnext#4372]
Font Awesome v3.2.1 is quite old now is it possible to upgrade it to v4.5.0.

**Comment by anandpdoshi** [comment]
We will have to change all instances of "icon-" to "fa-". Too much work for now. Would you be willing to make the change and send a pull request?

**Comment by yashodhank** [comment]
@anandpdoshi I'm working on it, expect pull request in a day or two.
Thanks

**Comment by zsajjad** [comment]
icon-fixed-width should be changed to fa-fw, some icons are changed as well for example: folder-closed is no more there and its just folder.

**Comment by rmehta** [comment]
@yashodhank :+1:

**Comment by yashodhank** [comment]
@zsajjad Thank, I am referring to https://github.com/FortAwesome/Font-Awesome/wiki/Upgrading-from-3.2.1-to-4

**Comment by ccfiel** [comment]
@yashodhank any updates? :)

**Comment by revant** [comment]
currently using fontawesome v4.7.0
