### ISSUE TITLE
Text editor Features are not working

### ISSUE THREAD

**Issue by maveezmh** [frappe/erpnext#43724]
### Information about bug

Text editor features are not working i created a descriptions with  bold colors in description on save the colors are getting reset to default.

Tested in Item master description table

![image](https://github.com/user-attachments/assets/3ed6b023-0e27-4960-8fd1-fa9b49dae653)
Description created before save

![image](https://github.com/user-attachments/assets/d5ceea17-bee9-4e36-b8e4-8cc3a9824f87)
Description after Save.

Similar issues with bullet and numbering

![image](https://github.com/user-attachments/assets/c4f51b7e-de1f-431d-8f98-8ae8a9403d06)
before save it was bullets

![image](https://github.com/user-attachments/assets/b09d98fc-b8f9-457b-824f-511aa68c693e)
After save it becomes numbering

### Module

stock

### Version

ERPNext: v15.38.1 (HEAD)

Frappe Framework: v15.44.1 (HEAD)

Frappe HR: v15.31.0 (HEAD)

### Installation method

FrappeCloud

**Comment by Nandhinidevi123** [comment]
![image](https://github.com/user-attachments/assets/c994c3d9-a255-479e-86c0-e2915240da52)

@maveezmh It's not a bug; it's a feature in stock settings. Disable the 'Convert Item Description to Clean HTML in Transactions' checkbox, and it will work as expected.

**Comment by maveezmh** [comment]
> ![image](https://private-user-images.githubusercontent.com/95607404/385739875-c994c3d9-a255-479e-86c0-e2915240da52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NjAyNDIsIm5iZiI6MTczMTY1OTk0MiwicGF0aCI6Ii85NTYwNzQwNC8zODU3Mzk4NzUtYzk5NGMzZDktYTI1NS00NzllLTg2YzAtZTI5MTUyNDBkYTUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDA4MzkwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiZDBiN2RlODI3NmI5NTVkY2Y5MGNkZDUwY2I5YTM5YTkwNzljMTYwN2JkODhkYzIyNTM1ZjY3NWI2OWUyYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.udftZ_fFLB0kqyVafaUBAfl3CR_b3jXpJtvOdYcpDms)
> 
> @maveezmh It's not a bug; it's a feature in stock settings. Disable the 'Convert Item Description to Clean HTML in Transactions' checkbox, and it will work as expected.

its working as expected. thanks @Nandhinidevi123
