### ISSUE TITLE
This could be more awesome if you could add kerberos and LDAP integration.

### ISSUE THREAD

**Issue by jadedevin13** [frappe/erpnext#4375]
Kerberos/LDAP is used by established businesses for authentication. It would be better if you could integrate that so that there is no need to add users in the application.

**Comment by mruepp** [comment]
I second that. Want to define group with erp access in ldap. Add only erp users to that group, and they are granted access. Even better would be to define ERP roles as LDAP-Groups.

**Comment by joelchen** [comment]
+1

**Comment by rmehta** [comment]
LDAP is now added.
