### ISSUE TITLE
Seeking to improve report format in ERPNEXT system

### ISSUE THREAD

**Issue by Masige** [frappe/erpnext#4378]
Dear ERPNEXT team,
I realize the good work that ERPNEXT has been doing particularly over recent to improve the platform and make more interactive and user friendly. A lot has been going on and indeed, we are happy to be part of ERPNEXT
However, from our side, we are more on projects than sales which means we are more of project reports and tracking progress and performances. 
However, we are not very happy on the report format for project modules in the system and I thought if I can share with you a slight sample of one among the many formats we normally use if can help to customize the report module in the erpnext system.
I have attached the report sample just to give overview of what we could expect from erpnext in the coming near future on project management
[Proposed report format.docx](https://github.com/frappe/erpnext/files/43868/Proposed.report.format.docx)

**Comment by rmehta** [comment]
@Masige can you post images instead of docx files

**Comment by Masige** [comment]
Dear Rushab,
Here are the images for report format

Regards
==============================
PEng. Deus D.H. Masige
Executive Director,
Tanzania Association of Environmental Engineers (TAEEs)
Box 35454,
Dar es Salaam, Tanzania

Mob: 0713/0767-483590
Email: *director*@taees.org <taeestz@gmail.com>; bwanamacd@gmail.com
Website: www.taees.org; and Website: www.taees.wordpress.com
<http://www.taees.com/>

*It's not necessarily you print every email you receive, please consider
the Environment before printing this e-mail. Be part of the environmental
Activist to receive the amount of solid wastes scattered around our
streets *

**Comment by Masige** [comment]
![report format 2](https://cloud.githubusercontent.com/assets/16017232/11425798/931f2b34-9468-11e5-8d76-87540ca2fd7e.jpg)
![report format 1](https://cloud.githubusercontent.com/assets/16017232/11425799/93253cc2-9468-11e5-8c56-7e9bf41d7735.jpg)

**Comment by Masige** [comment]
Dear Rushab,
See the images for report format I formally posted in word document

**Comment by Masige** [comment]
guys, is there anyone to assist on this?

**Comment by rmehta** [comment]
https://manual.erpnext.com/contents/customize-erpnext/print-format
