### ISSUE TITLE
Today's date should be highlighted in Field Calendar

### ISSUE THREAD

**Issue by Devens** [frappe/erpnext#4380]
Please see following screen shot. (if we see carefully, sometimes today's date is visible with very light gray colour. But, we suggest that it should be properly highlighted with different colour (like blue or any other semi-dark Colour). 

If buttons for Today, Tomorrow, etc can be added, it can be further helpful. 

![image](https://cloud.githubusercontent.com/assets/10671911/11415954/23638c7e-942f-11e5-9fd3-cb2e85fc387c.png)

**Comment by rmehta** [comment]
Fixed
