### ISSUE TITLE
modifying "Auto Material Request Generation Notification"

### ISSUE THREAD

**Issue by Devens** [frappe/erpnext#4381]
Currently following message comes for above mentioned notification. The message should be editable. If not feasible to provide modification facility, add Item Name in the list. 

Following Material Requests has been raised automatically based on item reorder level:

MREQ-00013

Item Code	Warehouse	Qty	UOM
ITEM01584	Stores - DE	500.0	Kg

**Comment by anandpdoshi** [comment]
Pushed a fix to show Item Name

**Comment by Devens** [comment]
Great! So Fast!! Thank you!


Thanking you,

With Regards,
Deven Shah
Safeworld Systems Pvt Ltd
M - 09825060116
