### ISSUE TITLE
Issue when creating one Sales Invoice from multiple Delivery Notes

### ISSUE THREAD

**Issue by itsdaveit** [frappe/erpnext#4384]
While creating a Sales-Invoice one can use the "from Delivery-Note" function to add the items from a Delivery-Note to the Sales invoice. In the "Get From Delivery Note"-popup Only Delivery-Notes which contain unbilled items are displayed. That is quite great so far. But: Why am i able to add the same Delivery-Note in the Sales-Invoice multiple times? I think this is a kind of consufsing and that it will lead to problems due to Items beeing billed mutiple times on the same Invoice.

The expected behaviour is that once i add a Delivery-Note, i should not be able to add it a second time. I think that it should be set to something like "not clickable/inactive" in the  "Get From Delivery Note"-popup, or even disappear from it after beeing added the first time.

**Comment by cgpurbaugh** [comment]
I think that this is a valid idea as well.

**Comment by bhupennewalkar1337** [comment]
Already [Fixed] :Disallow same items to be fetched multiple times in sales invoice #7103
