### ISSUE TITLE
Item batch no when sales return is error

### ISSUE THREAD

**Issue by sxyouling** [frappe/erpnext#43850]
### Information about bug

The batch number. When a sales return occurs, it will be changed to a new batch number (no longer the original batch number). At the same time, if the Item cost price changes, the return will reference the new cost price instead of the original cost price

### Module

selling

### Version

ERPNext: v15.38.0 (version-15)
Frappe Framework: v15.43.0 (version-15)
Frappe HR: v15.30.0 (version-15)
Payments: v0.0.1 (version-15)

### Installation method

None

**Comment by rohitwaghchaure** [comment]
@sxyouling I have tested on local instance and it's working fine. Issue might be related to customizations

**Comment by rohitwaghchaure** [comment]
@sxyouling The new batch is creating for the Rejected Quantity, could you please confirm the issue you're facing is for Rejected Quantity
