### ISSUE TITLE
Function for adding all delivered and not billed items to a Sales-Invoice at one click

### ISSUE THREAD

**Issue by itsdaveit** [frappe/erpnext#4385]
While creating a Sales-Invoice it is possible to add unbilled items from Delivery Notes by selecting each Delivery-Note one by one with the "from Delivery-Note"-button.

But if you have dozens of Delivery-Notes to add, that means you have to do a lot of mouse-clicks and you have to manuly look out for not to insert the same Delievery-Note twice. (see https://github.com/frappe/erpnext/issues/4384 )

It would be great if there could be a function like "add all unbilled from Delivery-Notes" which immediately would add all unbilled items from all Deleiver-Notes. So basicly it would add all items which apear on the "Delivered items to be billed"-report to the current Sales-Invoice.

**Comment by aambernath** [comment]
+1

**Comment by deepeshgarg007** [comment]
<img width="1336" alt="image" src="https://user-images.githubusercontent.com/42651287/198890735-292a6857-9ab1-462f-8def-e130987a9d49.png">

Its available now and you can select all delivery notes and get pending items for a specific customer
