### ISSUE TITLE
POS: After selling item stock is not deducted from selected warehouse/WH.

### ISSUE THREAD

**Issue by uc77** [frappe/erpnext#43867]
### Information about bug

Maybe we have not set something up right. So we setup a store profile using WH: Good in transit. We then sold an item from the POS. The issue is that the stock levels stayed the same say (121 units) as per item master; 117 items in the POS. 

Part1:
![POS inaccurate stock issue](https://github.com/user-attachments/assets/69c37616-346b-4165-924b-d3d4335e9132)

Part2:
![POS inaccurate stock issue - part2](https://github.com/user-attachments/assets/1f2932da-b0a2-48aa-9460-8d475434e4a7)

When we jump back in the POS we will see that the stock is minus one piece (i.e 116).

![POS showing stock minus 1 item](https://github.com/user-attachments/assets/e1985893-182e-4d63-9722-10cc4ef33050)

This is urgent as **stock levels** are at risk. Thanks guys!

### Module

stock, selling

### Version

Frappe version: v15.45.0
ERPNext version: v15.39.0

### Installation method

FrappeCloud

**Comment by muchai** [comment]
The design is that POS updates stock qtys, after closing the till: https://docs.erpnext.com/docs/user/manual/en/point-of-sales#35-pos-closing-voucher

**Comment by uc77** [comment]
🙈 We thought there was some missing step here, thanks for shedding light!
However, doesn't it make more sense & a better logic to validate the stock at the minute? Why I am saying this is that what happens if the stock showing available in the item master is allocated to someone else, resulting in a stock minus?
Have you tried this?

**Comment by uc77** [comment]
Also, did you take note of https://github.com/frappe/erpnext/issues/43815 in the process? The order can be finalized wthout paying a penny or dime.

**Comment by uc77** [comment]
Closing this.

**Comment by muchai** [comment]
> Also, did you take note of #43815 in the process? The order can be finalized without paying a penny or dime.

I think setting mode of payment as cash/phone instead of Bank prevents this.

**Comment by muchai** [comment]
> 🙈 We thought there was some missing step here, thanks for shedding light! However, doesn't it make more sense & a better logic to validate the stock at the minute? Why I am saying this is that what happens if the stock showing available in the item master is allocated to someone else, resulting in a stock minus? Have you tried this?

You're late to the party. This is an ongoing debate, caused a major debate on the forum way back. Either way, that's why POS Awesome came to be, since it updates stock in real time. But POS Awesome from v15 is no longer open source.

**Comment by uc77** [comment]
> e

Tried this. No luck. Can you show it from your end?

**Comment by uc77** [comment]
> > Also, did you take note of #43815 in the process? The order can be finalized without paying a penny or dime.
> 
> I think setting mode of payment as cash/phone instead of Bank prevents this.

Tried this. No luck. Can you show it from your end?

**Comment by uc77** [comment]
> > 🙈 We thought there was some missing step here, thanks for shedding light! However, doesn't it make more sense & a better logic to validate the stock at the minute? Why I am saying this is that what happens if the stock showing available in the item master is allocated to someone else, resulting in a stock minus? Have you tried this?
> 
> You're late to the party. This is an ongoing debate, caused a major debate on the forum way back. Either way, that's why POS Awesome came to be, since it updates stock in real time. But POS Awesome from v15 is no longer open source.

Hmm. That's interesting. We have only been using this product for < 9 months 😉 
Thanks for highlighting this. Do you have a link to the debate on the forum?

**Comment by uc77** [comment]
Closing this topic.
