### ISSUE TITLE
can i move "series" to head editing section

### ISSUE THREAD

**Issue by omnison** [frappe/erpnext#4389]
![2015-11-27 12 59 25-1](https://cloud.githubusercontent.com/assets/7886153/11437856/55ccfc64-950a-11e5-8824-8f8070dae7c7.jpg)
1. can i move "series" to head editing section
2. can we check the html code of printing format, so i can edit html in "HTML editor" in ERPNEXT

**Comment by cgpurbaugh** [comment]
as far as #1 goes, add the following to the heading:

{{ doc.status }}
