### ISSUE TITLE
[BUG] Unable submit installation note after fieldtype limit to 255 characters

### ISSUE THREAD

**Issue by justinlusg** [frappe/erpnext#4393]
![image](https://cloud.githubusercontent.com/assets/12539216/11462165/6f0b10ce-974b-11e5-9ab8-257c140d40d9.png)

![image](https://cloud.githubusercontent.com/assets/12539216/11462193/e3b81750-974b-11e5-8661-d45aa67bbc3f.png)

After update unable to submit installation note because Stock Item description is above 255 characters. Unable to change the field type as well as will cause problem reference to https://github.com/frappe/erpnext/issues/4362 issue.

**Comment by rmehta** [comment]
Can you change the field to Text / Small Text

**Comment by justinlusg** [comment]
![image](https://cloud.githubusercontent.com/assets/12539216/11463182/4aa674fe-9759-11e5-8b50-92df0b673049.png)

@rmehta  I've tried changing before, unable to change field type

**Comment by rmehta** [comment]
Try Small Text
