### ISSUE TITLE
Customer portal doesnot show all tasks

### ISSUE THREAD

**Issue by ajiragroup** [frappe/erpnext#43949]
### Information about bug

I set up a customer user, assigned user in Projects and in Customer doctypes. I logged in with customer account..

The portal shows the project correctly. Upon entering the project, it loads only 10 tasks with no "More" Button.

### Module

portal

### Version

erpnext 15.36.2
frappe 15.42.0

### Installation method

manual install

**Comment by ajiragroup** [comment]
Hello, this is great. But does this solve the pagination issue?



> Upon entering the project, it loads only 10 tasks with no "More" Button.

With current fix, it will load 100 tasks. But 100 tasks might not be enough. 

This is the screenshot of current (before this fix) system. There are 100's of tasks in this project. It currently shows 10 and no option to "View More".
![image](https://github.com/user-attachments/assets/1c29fb70-4f93-4358-851a-b9dd8eedf336)

**Comment by Nihantra-Patel** [comment]
Pagination will not be set because it is a custom-designed page if looks like order or invoice portal page then pagination comes automatically.

**Comment by ajiragroup** [comment]
> Pagination will not be set because it is a custom-designed page if looks like order or invoice portal page then pagination comes automatically.

OK. But what will be the default sorting of this Tasks list be based on ? Will it display according to ID ? Or Task name(alphabetic) ? or last edited on ?
