### ISSUE TITLE
[Urgent Bug] Unable submit ticket via Web Form after update

### ISSUE THREAD

**Issue by justinlusg** [frappe/erpnext#4394]
![image](https://cloud.githubusercontent.com/assets/12539216/11464207/2361c976-9767-11e5-8a10-cf51af60b601.png)

After the recent update, the web form page is broken. Unable to submit any tickets by customers anymore. No changes was made to the web form and was working before

**Comment by anandpdoshi** [comment]
This was fixed with the last week's release. You should update your installation.

**Comment by justinlusg** [comment]
Noted with thanks, will update
