### ISSUE TITLE
JSONDecodeError in Sales Pipeline Analytics Doctype

### ISSUE THREAD

**Issue by Triplem8360** [frappe/erpnext#43952]
### Information about bug

In the ` check_for_assigned_to` method located in the **sales_pipeline_analytics** doctype, when `info.get("opportunity_owner")` returns a string that cannot be parsed as JSON, the `json.loads()` function raises a _JSONDecodeError_. This occurs when the value of `opportunity_owner` is not a valid JSON string.

**Code Snippet:**
```python
def check_for_assigned_to(self, period, value, count_or_amount, assigned_to, info):
    if self.filters.get("assigned_to"):
        # Change here to check for assigned_to instead of opportunity_owner
        for data in json.loads(info.get("assigned_to") or "[]"):
            if data == self.filters.get("assigned_to"):
                self.set_formatted_data(period, data, count_or_amount, assigned_to)
    else:
        self.set_formatted_data(period, value, count_or_amount, assigned_to)
```

**Suggested Fix:**
Replace `json.loads(info.get("opportunity_owner") or "[]")` with the `assigned_to` input argument to avoid the error when opportunity_owner is a non-JSON string.

### Module

CRM

### Version

frappe 14.45.0
erpnext 14.35.2

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
**Error Message:**
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by Triplem8360** [comment]
This error occurs when the following filters are set in the report:

Pipeline by = Owner
Based on = Amount

**Comment by Nihantra-Patel** [comment]
Your version is old, we tested in below version but we haven't found the issue. code is updated so please check it on the latest version.

```
ERPNext: v14.74.8 (version-14)
Frappe Framework: v14.85.0 (version-14)
```

https://github.com/frappe/erpnext/blob/710771edf41b897d77f4235b0ec09f4dbfcd3b10/erpnext/crm/report/sales_pipeline_analytics/sales_pipeline_analytics.py#L230-L236
