### ISSUE TITLE
Consolidate Items - Material Request/Purchase Order

### ISSUE THREAD

**Issue by tajff** [frappe/erpnext#43957]
### Information about bug

There is no option to merge similar items.

![image](https://github.com/user-attachments/assets/858b6e20-a151-43a0-9f4c-45880276d48b)

### Module

stock

### Version

ERPNext: v15.x.x-develop () (develop)

Frappe Framework: v15.45.1 (version-15)

### Installation method

None

**Comment by Nihantra-Patel** [comment]
The feature is not available yet, as users sometimes purchase the same material in different units of measurement (UOM), which makes it challenging to set or merge the item. However, you can implement logic on the client or server side to achieve this.


For Material Request:
```py
item_qty = {}
items_to_delete = []

for item in doc.items:
    item_code = item.item_code
    
    if item_code in item_qty:
        item_qty[item_code] = item_qty[item_code] + item.qty
        items_to_delete.append(item)
    else:
        item_qty[item_code] = item.qty

for item in items_to_delete:
    doc.items.remove(item)

for item_code, qty in item_qty.items():
    for item in doc.items:
        if item.item_code == item_code:
            item.qty = qty
            break
```

**Comment by tajff** [comment]
Thanks, it works
I hope it is in the update , making sure of the different units
