### ISSUE TITLE
Opportunity don't appear in Customer Connections Tab

### ISSUE THREAD

**Issue by tranminhnhanchinh** [frappe/erpnext#43951]
### Information about bug

I create customer from opportunity but in Customer Connection Tab, opportunities don't appear

### Module

CRM

### Version

ERPNext 15.39.0

### Installation method

None

**Comment by Nihantra-Patel** [comment]
If the Opportunity from "Customer" then will show in the customer connection dashboard. We tested in the latest version so it's worked properly.

Please check it.

![image](https://github.com/user-attachments/assets/5af9620c-3cef-47d0-8345-b27fca79d330)

![image](https://github.com/user-attachments/assets/021a046f-2aeb-418e-9421-f04cf0f14e9b)
