### ISSUE TITLE
CSS not Working after bench buld

### ISSUE THREAD

**Issue by tranminhnhanchinh** [frappe/erpnext#43954]
### Information about bug

After 'bench build'

i got this

Please help me 
![Screenshot at Nov 03 22-40-19](https://github.com/user-attachments/assets/fe3232c4-5423-4991-9f0f-29848839f919)

### Module

other

### Version

15.39.3

### Installation method

None

**Comment by Nihantra-Patel** [comment]
Please apply it

```
bench setup requirements
bench build
bench clear-cache
bench clear-website-cache
```

```
chmod -R o+rx /home/[frappe-user]

// OR

sudo chmod -R o+rx /home/frappe
```

It’s not a bug. I think this is your first time manually installing it. If you have any doubts, feel free to raise an issue on https://discuss.frappe.io/.
