### ISSUE TITLE
POS Opening entry creation popup

### ISSUE THREAD

**Issue by Ahmed8647** [frappe/erpnext#43976]
### Information about bug

1- While creating a new POS opening entry the list of saved POS profiles doesn't show i have to type the name of the profile each time i want to create a new pos opening entry.
2- There is no way to close the popup window if you wanted to cancel the creation.
![Capture](https://github.com/user-attachments/assets/04129189-dd18-42df-8f4b-c6e9c8be6bb6)

### Module

selling

### Version

v: 15.38.0

### Installation method

docker

**Comment by Nihantra-Patel** [comment]
If the POS Opening Entry is open, the popup will not appear. However, if the POS Opening Entry is closed, you must first enter the POS Opening Entry before creating a POS Invoice.

**Comment by Ahmed8647** [comment]
> If the POS Opening Entry is open, the popup will not appear. However, if the POS Opening Entry is closed, you must first enter the POS Opening Entry before creating a POS Invoice.

Hi Patel, thank you for the reply but I think you misunderstood the issue,
![001](https://github.com/user-attachments/assets/9081f742-1d8e-417f-9c98-e4949ec93c34)
![002](https://github.com/user-attachments/assets/7c3ceca6-bd93-4449-bd91-cc68001c5fc3)

**Comment by Nihantra-Patel** [comment]
There is no close option because if there is close then how the entry of opening is done then run some logic, and second thing POS profile is created company wise, you may have created in some other company then create company wise POS profile and check.

**Comment by Ahmed8647** [comment]
i have one company but i created a second profile the second showed but not the first, as for the close button i am aware that i can't use pos without the opening entry but if there was a close button that when you click on it redirects to the home screen if i wanted to cancel the operation, rather than go back then refresh the browser.

**Comment by Nihantra-Patel** [comment]
First, you need to understand the basic POS flow to know how it works. Once you create a POS Opening Entry, it won't show up every time you open POS, but If you want to switch to a different company, you also need to close the current POS session with a POS Closing Entry and then create a new POS Opening Entry for the new company. You can't manage POS for multiple companies at the same time.

**Comment by Ahmed8647** [comment]
Ok thank you, I will learn more about that.
