### ISSUE TITLE
Cannot map because following condition fails: docstatus=1

### ISSUE THREAD

**Issue by Craftint** [frappe/erpnext#43992]
### Information about bug

While getting items from material request in purchase order, the list is showing the cancelled and draft material requests as well. 

![image](https://github.com/user-attachments/assets/a5dc86d2-669e-4325-8d57-6e32b6326bca)

![image](https://github.com/user-attachments/assets/89b19735-5cad-4979-8d31-22c6922acd5e)

Hence while getting items, it is showing below error:

![image](https://github.com/user-attachments/assets/c473e2a7-ca0f-4da4-ba14-289aa8e58c73)

### Module

buying

### Version

ERPNext: v15.35.1 (HEAD)
Frappe Framework: v15.40.6 (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/mapper.py", line 53, in map_docs
    target_doc = method(*_args)
                 ^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/stock/doctype/material_request/material_request.py", line 435, in make_purchase_order
    doclist = get_mapped_doc(
              ^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/mapper.py", line 93, in get_mapped_doc
    map_doc(source_doc, target_doc, table_maps[source_doc.doctype])
  File "apps/frappe/frappe/model/mapper.py", line 170, in map_doc
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 652, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 617, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 568, in _raise_exception
    raise exc
frappe.exceptions.ValidationError: Cannot map because following condition fails: docstatus=1
```

**Comment by Nihantra-Patel** [comment]
We tested in the latest version and also defined docstatus 1 in the below code. please check line no. 550

https://github.com/frappe/erpnext/blob/9ccdb987d9deb844a1126fba1e33c55367484631/erpnext/buying/doctype/purchase_order/purchase_order.js#L536-L561

![image](https://github.com/user-attachments/assets/e39d3960-c33f-4c19-95e5-8f430233c878)


![image](https://github.com/user-attachments/assets/66cb588e-3b6f-47e7-93b9-fbb96a9b36fb)

**Comment by Craftint** [comment]
As you can see in the screenshot, it is showing with the latest version itself. Its not showing for all. Whichever is coming by default in the list, it is not filtered.

![image](https://github.com/user-attachments/assets/b981a436-1cf8-4688-8804-f9af77f6f5c6)

![image](https://github.com/user-attachments/assets/831b9ef0-4462-481c-a861-41c452e70068)
![image](https://github.com/user-attachments/assets/b4a87d11-92e2-4462-abab-7607be2b7192)

It is not showing if you are searching for old which is not part of the initial list

![image](https://github.com/user-attachments/assets/92f9c266-1cfb-40a0-8f93-3e4cf09c065f)

![image](https://github.com/user-attachments/assets/c1a1bde1-8e42-4c1e-8b3c-609e8c7f1327)

**Comment by Nihantra-Patel** [comment]
I tested it with and without filters on the Frappe Cloud and also checked it locally, but I couldn't find this type of issue. I have already shared the code, and it appears to have the docstatus set to 1 correctly. If there is any custom code applied in the client script doctype or a custom app, please check that as well.

**Comment by Craftint** [comment]
There is no customization. The site is on frappe cloud. 
As mentioned, the initial list showing on the dialogue is not filtered somehow. 

![image](https://github.com/user-attachments/assets/3a3c9601-ee29-4b0b-b164-baaded9e108f)

MAT-MR-2024-00003 which is in draft is also showing.

![image](https://github.com/user-attachments/assets/956ed7dc-a9af-4520-a6fa-f1a9f87f37a5)

Is there any way for you to access frappe cloud sites and check

**Comment by Nihantra-Patel** [comment]
If your site have a support plan then raise the [support ticket](https://support.frappe.io/).

**Comment by Craftint** [comment]
Site is under 25$ plan. Hence i don't think it will be covered :(

**Comment by Nihantra-Patel** [comment]
Also, your version is old so please update it and again check it.

**Comment by Craftint** [comment]
ERPNext: v15.40.0 (version-15)

Frappe Framework: v15.46.0 (version-15)

Updated to latest
