### ISSUE TITLE
Department Doctype is not not found after the update

### ISSUE THREAD

**Issue by khourytony** [frappe/erpnext#44009]
### Information about bug

Department Doctype is not not found after the update.

### Module

HR

### Version

ERPNext: v15.41.0 (version-15)
Frappe Framework: v15.47.1 (version-15)
Frappe HR: v16.0.0-dev (develop)

### Installation method

None

**Comment by Nihantra-Patel** [comment]
I’ve shared a suggestion:
If you’ve installed ERPNext in version 15, make sure the hrms is also in version 15 to prevent errors.

Also check the latest version 15 and develop branch, Department doctype show properly.

![image](https://github.com/user-attachments/assets/67ade10c-a493-45f6-8fcd-b3885c7dfa5b)


Also check, if user has not right of Department doctype then give them from the [Role Permission Manager](https://docs.erpnext.com/docs/user/manual/en/role-based-permissions)
