### ISSUE TITLE
Incorrect calculation for Provisional Profit/Loss (Credit)

### ISSUE THREAD

**Issue by deryak127** [frappe/erpnext#44017]
### Information about bug

The Provisional Profit / Loss (Credit) should be calculated as:
Total Asset−(Total Liability+Total Equity) 
When I look at my balance sheet report, I see inconsistencies.

Expected:
179.372,31 - (11.255,87 + 168.116,44 ) =   0  
Actual Result 
179.372,31 - (11.255,87 + 168.116,44 ) =    -17.000,00

![image](https://github.com/user-attachments/assets/c6a241f9-7e0e-4e46-92ea-ba91326206be)
![image](https://github.com/user-attachments/assets/b09f26d5-18fb-4a20-a2b5-50a1cebf6bfb)

### Module

accounts

### Version

ERPNext: v15.32.1

Frappe Framework: v15.37.0

### Installation method

None

**Comment by Nihantra-Patel** [comment]
Please update your version because your version is old and lots of changes made in last 2 months: https://github.com/frappe/erpnext/pull/43426

Current Version is:

```
ERPNext: v15.41.1 (version-15)
Frappe Framework: v15.47.1 (version-15)
```
