### ISSUE TITLE
Issue: Splitting a batch with STE-Repack purpose does not split

### ISSUE THREAD

**Issue by YamadaKaito** [frappe/erpnext#44015]
### Information about bug

I just upgraded version from v13 to v15 with docker frappe+erpnext installation method & everythings looks good.
But when I tried to split a batch using StockEntry - Repack Purpose with BOM the result does not split the batch after submitted. Is this consider a bug or there's feature / updates on business process in certain version?

<details><summary>Details on the use case</summary>
<p>
- on the left side (source), nos enabled (serialized, lets say item-A with SN-A), 1 item, qty = 1<br>
- on the right side (target), 3 items (1 item is nos enabled serialized, item-B), qty each = 1<br>
when using v13 this case resulting:<br>
- Item-A is replaced with 3 items, one of them is Item-B with SN-A<br>
- the serial no is changed from item-A to item-B<br>
- which is correct<br>
but when using v15 this case resulting:<br>
- Item-A still intact to the serial no (does not replaced with the item-B)<br>
- but the ledger says the qty of Item-A is reduced & item-B is increased<br>
- which is dont know, is it intended to be that or..?<br>
- is this related to the new SABB also?<br>
</p>
</details>

Thank you

### Module

stock

### Version

ERPNext: v15.41.0
Frappe Framework: v15.47.0

### Installation method

docker

**Comment by rohitwaghchaure** [comment]
@YamadaKaito In v13 we were allowing but that was not a proper way. It was causing a lot of problem with the valuation. Better you create the one serial no for one item. Also you can add custom field in which you can keep the non-unique value in that field for two different serial nos.

For example

Item A has unique serial No SN-00001 with non-unique value SND-0001 (Custom field)
Item B has unique serial No SN-00002 with non-unique value SND-0001 (Custom field)

**Comment by YamadaKaito** [comment]
Hi @rohitwaghchaure thank you for the reply..
I see, so if according to my case, how to do a simple assembly & disassembly process without going through the work-order manufacture process? & this is what i find this far:
1. STE-Manufacture to replicate the repack purpose (from materials to finished good) but yes using additional custom field as non-unique value (additional SN on my case)
2. STE-Disassemble to replicate the repack purpose but with opposite (from finished good back to materials), but how to skip the mandatory which needed to create work order for this purpose?

Is this the correct way?
Thank you
