### ISSUE TITLE
Drop Shipped Items are not being recorded in Cost of Goods Sold

### ISSUE THREAD

**Issue by brandonjcreek** [frappe/erpnext#4403]
Items that are drop shipped do not make it into the Cost of Goods sold ledger, which in turn, completely messes up the Profit and Loss report.

**Here is the way the workflow should work:**

1: A member of the sales team creates a Sales Order for the customer.

2: All items that are being drop shipped are marked as so, and are assigned to a Supplier.

3: Sales Order is submitted and then "Purchase Order" button is clicked to create the PO.

4: Purchase Order is created, undergoes any needed modifications, and is then submitted and sent to the supplier.

5: Once delivery confirmation is received from the supplier, the "Mark as Delivered" button is clicked within the Purchase Order.

6: From here, a user goes into the Sales Order and clicks the "Invoice" button.

7: The cost of the items invoiced should then appear within the Cost of Goods Sold Ledger, as it does for any other Sales Invoices or Delivery Notes.

The problem is, when using the above workflow, the purchased items do no show up under Cost of Goods Sold, and in return, when a P&L report is generated, it shows that the Gross Profit Margin is well above what it actually is.  This poses a huge problem for companies that rely heavily on drop shipping.

**Here is an example of how this would mess up a companies financials:**
A customer orders $100 worth of merchandise. 
Seller's cost is $50. 
If Seller drop ships their items to the Customer using the above method, and then ran a P&L report, it would show that they had a Net Profit of $100 as opposed to $50, since the $50 cost of the items were never logged under the Cost of Goods Sold ledger. 

**Current Workarounds:**

Users can forgo using the drop ship feature, and simply receive the items into inventory, and then create a Sales Invoice with the update stock option checked. This will then enter the transaction into the Chart of Accounts: Cost of Goods Sold ledger.  However, the drawback is that it completely defeats the convenience of the Drop Shipping feature.

Another viable workaround would be to switch from a Perpetual Inventory system to a Periodic Inventory system, and then have the Purchase Orders (and then items contained on them) logged under the Cost of Goods Sold ledger. However, the Perpetual System is arguably better, since it gives you a truer report on "Cost of Goods Sold" since the costs are linked to Sales Invoices and or delivery notes, rather than Purchase Invoices.

**Comment by rmehta** [comment]
This is fixed via https://github.com/frappe/erpnext/pull/4395

Will be in today's release
