### ISSUE TITLE
Payment terms not visible in payment schedule table after selecting the payment term template

### ISSUE THREAD

**Issue by nikitadattapawar06** [frappe/erpnext#44039]
### Information about bug

After selecting the payment term template the payment terms are auto populated in the payment schedule table but currently the payment schedule table is not getting auto filled this error occured after current release of the erpnext 
![purchase issue](https://github.com/user-attachments/assets/2631ef4d-b656-4d79-9b92-cc8648039748)
if i save the purchase order after selecting the payment terms template with 2 terms that are not getting reflected in the table but when im trying to save the purchase order then im getting error for due date same for 2 terms

### Module

buying

### Version

ERPNext: v14.75.0 (HEAD)
Frappe Framework: v14.85.0 (HEAD)
Helpdesk: v0.10.0 (HEAD)
Frappe HR: v14.35.0 (HEAD)

### Installation method

FrappeCloud

**Comment by shaikhmk73** [comment]
It seems there’s no explicit trigger or function call here that auto-populates or updates the Payment Schedule table when a Payment Terms Template is selected. To resolve this, a method could be added to force a reload or calculation of payment terms when a template is selected.

Below is the suggestion:

Add the following function to handle updates to the payment schedule when terms are added or changed.

payment_terms_template.js

    terms_add: function(frm) {
        // Trigger update_payment_schedule when a term is added
        frm.trigger("update_payment_schedule");
    },

    update_payment_schedule: function(frm) {
        frappe.call({
            method: "erpnext.accounts.doctype.payment_terms_template.payment_terms_template.update_payment_schedule",
            args: {
                template_name: frm.doc.name,
                schedule: frm.doc.terms
            },
            callback: function(r) {
                if (r.message) {
                    frm.set_value("payment_schedule", r.message);
                    frm.refresh_field("payment_schedule");
                }
            }
        });
    }



In payment_terms_template.py, add a new method to calculate the payment schedule:


@frappe.whitelist()
def update_payment_schedule(template_name, schedule):
    template = frappe.get_doc("Payment Terms Template", template_name)
    payment_schedule = []
    
    for term in template.terms:
        schedule_entry = {
            "payment_term": term.payment_term,
            "due_date": calculate_due_date(term),
            "invoice_portion": term.invoice_portion,
            "payment_amount": calculate_payment_amount(term)
        }
        payment_schedule.append(schedule_entry)
    
    return payment_schedule

def calculate_due_date(term):
    # Placeholder for your due date calculation logic
    return term.due_date  # Adjust this as needed

def calculate_payment_amount(term):
    # Placeholder for payment amount calculation logic
    return term.amount  # Adjust this as needed
    
    
 I believe above changes will enable the Payment Schedule to auto-populate based on the selected Payment Terms Template.

**Comment by nikitadattapawar06** [comment]
Thank you for your reply but I'm currently using the on cloud instance of erpnext is there anything that i can do to solve this issue
