### ISSUE TITLE
Ordering of Filter Search "Preview" List

### ISSUE THREAD

**Issue by monojoker** [frappe/erpnext#4404]
Hi Guys,

When you begin typing into a filter on a document list screen it previews the matching results in a dropdown. Currently this dropdown lists (for example) Sales Orders in ascending order. It makes more sense to search in descending as you're typically searching for a recent document rather than wanting to see the first.

![image](https://cloud.githubusercontent.com/assets/10917366/11487159/1629d710-9809-11e5-93b1-24bbd57182b9.png)

This would be very helpful for users who rely on this search option to quickly locate a customer order for giving status updates to customers on the phone or finding the current order(s) for a particular customer. 

I also suspect it's a pretty simple change - just to set the query/result ordering from ASC to DESC? Please consider and let me know :+1: 

Thanks
Liam.

**Comment by Devens** [comment]
+1

**Comment by rmehta** [comment]
@monojoker this goes via the standard sorting in the form. Check Customize Form view if you have set it to ascending.

**Comment by MaxMorais** [comment]
@rmehta I have followed the support on this question in gitter, and It dont work using the standard behavior.

**Comment by rmehta** [comment]
Everything goes via the standard control.js methods. Did not see any customization.

**Comment by monojoker** [comment]
Thanks everyone but @MaxMorais is correct, we have ALWAYS had the sort set to Modified DESC which should show the last jobs first (by means of them having their workflow_state changed most recently). I have also tried setting it to name DESC but still it doesn't affect that specific "preview search" feature. Could you look into it please @rmehta it would certainly make ad-hoc searching while on phone to customers MUCH quicker :) Thanks.

![image](https://cloud.githubusercontent.com/assets/10917366/11516410/be33e71e-98ce-11e5-98c2-d680004c200d.png)
