### ISSUE TITLE
Successfully update to the latest version ERPNext: v15.41.2, but show the ERPNext: v15.41.1 in About menu

### ISSUE THREAD

**Issue by bobotdls** [frappe/erpnext#44061]
### Information about bug

I successfully update my ERPNext v15.41.2,
But when I check it on my About menu still on  ERPNext: v15.41.1 

### Module

other

### Version

ERPNext: v15.41.1 (version-15)

Frappe Framework: v15.47.1 (version-15)

Payments: v0.0.1 (version-15)

Print Designer: v1.4.3 (main)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
No error while updating
```

**Comment by Nihantra-Patel** [comment]
You’re right, but the last version was released recently. Normally, a new version is released each week, but due to a critical bug, it wasn’t updated by the frappe-bot. You can ignore this for now, as it will be automatically updated in the next version.
