### ISSUE TITLE
Submitting Work Order with connected Serial Number generates a second Serial Number.

### ISSUE THREAD

**Issue by northern-concrete** [frappe/erpnext#44110]
### Information about bug

1. Create Work Order for quantity (1) for an Item that Has Serial No and Save.
2. On Connections sheet, select Serial No and Add Serial No.
3. Enter information for new Serial No and Save.
4. Return to previous Work Order and inspect Connection sheet to see new Serial Number is connected to Work Order.
5. Submit Work Order.
6. Another Serial Number is created and connected to the Work Order.

This bug affects importing Work Orders and Serial Numbers from another ERP system.  After Work Orders are imported without being submitted, Serial Numbers are imported with the connected Work Order mentioned in the work_order field.  However, when the Work Orders are then submitted, a second Serial Number is created and connected to the Work Order.

System should check for existing number of connected Serial Numbers and only generate Serial Numbers if needed.

### Module

manufacturing

### Version

Frappe: v15.47.1
ERPNext: v15.41.1

### Installation method

docker

**Comment by rohitwaghchaure** [comment]
@northern-concrete If you don't want the system to create the serial nos automatically on submission of the work order, then disable the checkbox "Make Serial No / Batch from Work Order" in the manufacturing settings.
