### ISSUE TITLE
Itemwise delivery Date for Sales Order Item (similar to PO Item)

### ISSUE THREAD

**Issue by Devens** [frappe/erpnext#4411]
Very useful to decide multiple delivery dates for same item as well as different delivery date for different items. (When It's provided in PO why not in SO?)

**Comment by PawanMeh** [comment]
This is available in the latest version, hope it meets your requirements

![multiple_dates_in_so](https://user-images.githubusercontent.com/20460498/36097105-72612e3a-101f-11e8-8136-d7d314b21b9f.png)
