### ISSUE TITLE
Payment Entry In Words is wrong if not company currency

### ISSUE THREAD

**Issue by JesTom94** [frappe/erpnext#44141]
### Information about bug

When the payment made is not in company currency, the base_in_words and the in_words field have the same value. When I checked the code, it seems to be incorrect.

If you look at the code below, you can see that if the payment type is Receive, then the amount used to print is received_amount and vice versa for paid. Please check the below screenshots

![image](https://github.com/user-attachments/assets/d8fb7370-b291-46ab-8b5d-bfbe71c2d4f1)

As you can see if it is Receive, then the amount actually comes in paid_amount and base_paid_amount but the function takes received_amount and base_received_amount and vice versa for Pay.
Hence the In words comes like this

![image](https://github.com/user-attachments/assets/032b1a58-9c57-4fb5-9ba1-e4b8f762fea0)

Both company currency and the other in words are the same data.

### Module

accounts

### Version

Frappe Version: v15.47.2 (version-15)
ERPNext Version: v15.41.1 (version-15)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
def set_total_in_words(self):
		from frappe.utils import money_in_words

		if self.payment_type in ("Pay", "Internal Transfer"):
			base_amount = abs(self.base_paid_amount)
			amount = abs(self.paid_amount)
			currency = self.paid_from_account_currency
		elif self.payment_type == "Receive":
			base_amount = abs(self.base_received_amount)
			amount = abs(self.received_amount)
			currency = self.paid_to_account_currency

		self.base_in_words = money_in_words(base_amount, self.company_currency)
		self.in_words = money_in_words(amount, currency)
```

**Comment by Nihantra-Patel** [comment]
The code you’re using for showing the amount in words is set up correctly. It works like this: when you make a payment, the code checks if the payment type is "Pay" or "Receive." If it’s "Pay," it uses the amount from the "paid" fields and the currency of the account where the money is coming from. If it’s "Receive," it uses the amount from the "received" fields and the currency of the account where the money is going.

The code then creates two versions of the amount in words:
- One in the company’s currency.
- One in the currency of the account used in the transaction.

The text in words might look the same even though they’re actually in different currencies. This is normal and doesn’t mean there’s an error in the code.
