### ISSUE TITLE
Some fields do not pick up translations

### ISSUE THREAD

**Issue by Ferohers** [frappe/erpnext#4416]
Dear Super Developers,

Field for gender refuse to get any translation (all other languages seems having the issue). In addition, status of the employee seems ok on the list view (translated) but on the pdf forms shows default English strings.

![1](https://cloud.githubusercontent.com/assets/14891349/11527728/52604808-98eb-11e5-90ff-f0ada85197b5.png)

**Comment by Ferohers** [comment]
Marital Status's field value also refuse to be translated. 

![2](https://cloud.githubusercontent.com/assets/14891349/11528142/928504a8-98ed-11e5-89d5-0365a30198d9.png)

**Comment by strixaluco** [comment]
Fixed as of Frappe Framework: v8.9.4
