### ISSUE TITLE
The "leave this conversation" link in emails should be an option

### ISSUE THREAD

**Issue by gabtzi** [frappe/erpnext#4417]
Hi, 

I really think there should be an option to enable/disable this link because if you set up erpnext locally and not under a working FQDN it will make this link be invalid to the email recipients. This in turn will increase the likelihood spamassassin and Hotmail will mark the email as spam/junk. 

Messages containing malformatted urls or urls not resolving correctly or obfuscated urls are having points deducted from their spamassassin score as a rule and the points are not negligible either. 

Even if we exclude that, it will also confuse the recipient if the link didn't work

**Comment by pifiu** [comment]
I just came across this thread and this is true, is it possible to customize the footer?

**Comment by me2ne** [comment]
yes , you are right , in version 7 they is one option to remove "View this in your browser " , but still show "Leave this conversation"  and it's linked to erpnext server ip , when some one use local server this link not work and email go to junk mail

**Comment by hiousi** [comment]
I would like an option too.
