### ISSUE TITLE
Country Doctype should not allow to be renamed

### ISSUE THREAD

**Issue by meaziz** [frappe/erpnext#44199]
### Information about bug

Since the Country doctype is used to set the regional settings.
and this is hardcoded into apps and dependencies.

The Country doctype should not be allowed to be renamed.

### Module

accounts, regional

### Version

ERPNext: v15.42.0 (HEAD)
Frappe Framework: v15.47.2 (HEAD)

### Installation method

None

**Comment by meaziz** [comment]
https://github.com/lavaloon-eg/ksa_compliance/issues/175#issuecomment-2483459251

**Comment by akhilnarang** [comment]
Resolved with https://github.com/frappe/frappe/pull/28596
