### ISSUE TITLE
Company Name is required

### ISSUE THREAD

**Issue by princessfrombabylon99** [frappe/erpnext#44200]
### Information about bug

If a prospect is saved, it mandates a user to punch-in organization name , even if the customer group is selected as an  'Individual' and not Entity.
![image](https://github.com/user-attachments/assets/620dbc54-f329-4f56-8aa4-ab85ec82b5e2)

### Module

CRM

### Version

ERP and Frappe bench v15

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Company Name is required*
```

**Comment by Nihantra-Patel** [comment]
Because naming set from the company_name

![image](https://github.com/user-attachments/assets/316e8d0e-8300-4c69-8c07-0bcdd14aead6)

**Comment by princessfrombabylon99** [comment]
@Nihantra-Patel You want me to change 'company_name' to 'customer_name'? Could you please explain it a little bit . Is there any documentation link available to read upon?

**Comment by Nihantra-Patel** [comment]
It's not a bug, Prospect id will be created from the company_name so if company_name is not existed then will throw the error so you have to enter the company name.

**Comment by princessfrombabylon99** [comment]
@Nihantra-Patel If a prospect is saved, it mandates a user to punch-in organization name , even if the customer **group** is selected as an '**Individual**' and not Entity. @NagariaHussain Could you please clarify this?

**Comment by princessfrombabylon99** [comment]
For example, if a person expresses interest in purchasing a product or service, attends a sales presentation, or fits a specific target demographic, they can be considered a prospect, it can apply to individual people as well (as in B2C).
