### ISSUE TITLE
Add Weekly Payroll Processing

### ISSUE THREAD

**Issue by system19** [frappe/erpnext#4422]
### Some assumptions
- Weekly/fortnightly intervals determined by the employee start date and day of the week payroll is run. For example, payroll is run every Friday:
- Employee A starts Wednesday October 19th 2016 – first weekly salary slip will be for 2 days (Wednesday & Thursday).
- Subsequent weekly payroll run with be from Friday to Thursday.
- Multiple payroll run dates are required.
### Payroll Run Dates
- New DocType to capture payroll run dates by Company. Future dates are pre-determined by the holiday calendar.
- Weekly – fixed working day each week.
- Fortnightly – fixed working day every fortnight.
- Monthly – fixed working day each month.
### Employee DocType changes
- New field called Payroll Run with drop down options:
  - Weekly
  - Fortnightly
  - Monthly
### Salary Structure DocType changes
  - No change to salary structure.
  - Salary structures created for following groups
  - Weekly salary structure (separate group for each role or rate)
  - Fortnightly salary structure (separate group for each role or rate)
  - Monthly salary structure (separate group for each role)
### Process Payroll DocType changes
- Change to Create Salary Slip button to check the current date against:
- Weekly Payroll Run Date: If current date is >= the next Weekly Payroll Run Date then create weekly salary slips for all active employees where Payroll Run = Weekly.
- Fortnightly Payroll Run Date: If current date is >= the next Fortnightly Payroll Run Date then create fortnightly salary slips for all active employees where Payroll Run = Fortnightly.
- Monthly Payroll Run Date:  If current date is >= the next Monthly Payroll Run Date then create monthly salary slips for all active employees where Payroll Run = Monthly.
  If any of the above conditions are not met, then skip.
### Salary Slip DocType changes:
- Salary Slip primary key changes to allow 
  - multiple salary slips per month
  - across multiple months i.e. when a week or fortnight spans 2 months.
  - across multiple years i.e. when a week or fortnight spans two fiscal years.
- Interval dates for weekly and fortnightly salary slips.
  - Leave days, sick days, payment days to be calculated based on date intervals for weekly and  fortnightly salary slips.

**Comment by mhbu50** [comment]
+1

**Comment by OneiricIT** [comment]
+1

Also ability for fortnightly too.

**Comment by joezsweet** [comment]
+1 

Also montly would be nice to have ..at the end lets say configurable period by settings

**Comment by OneiricIT** [comment]
Opened discussion to find more interest in community 
https://discuss.erpnext.com/t/weekly-and-fortnightly-payroll-salary-slips/16305

**Comment by rmehta** [comment]
@system19 can you finalize the specs for this?

**Comment by IAGAdmin** [comment]
https://discuss.erpnext.com/users/tonyta has already started the design

**Comment by tta-cloude8** [comment]
[ERPNext Design Proposal for Weekly Payroll and Salary Slip.docx](https://github.com/frappe/erpnext/files/547385/ERPNext.Design.Proposal.for.Weekly.Payroll.and.Salary.Slip.docx)

Detailed design uploaded.

**Comment by rmehta** [comment]
@tta-cloude8 I have copied your code to the top post. Best not to do attachments! I have given you edit rights, you can now edit the top post

**Comment by tta-cloude8** [comment]
Hi all

My team are currently estimating the effort required for this development based on the current design.

**Comment by IAGAdmin** [comment]
@tta-cloude8 just a couple of observations:
- Why Payroll run option in Employee and not in Salary Structure?
- better to change Current Date in Process Payroll to the current Posting Date (Payroll Run Date) to allow flexibility and fixes

**Comment by rmehta** [comment]
I agree. It should just be in the Salary Structure.

Let's finalize the design, @KanchanChauhan can build it since she already has been working on Payroll.

**Comment by system19** [comment]
To allow more types of loans/advances and repayment options:
"Employee Loan" should just be called "Business Loan" or something like that. 
Put the Loan process back into the Accounts area with the option of print to the Pay Slip. If thats possible? That way the Company can loan to other people than just employees.

**Comment by rmehta** [comment]
Please refer to #6808
