### ISSUE TITLE
Add a "Super Contribution" field to Salary Structure and Salary Slip

### ISSUE THREAD

**Issue by system19** [frappe/erpnext#4423]
As per discussion at https://discuss.erpnext.com/t/payroll-processing-integration-with-accounts/8276/4

To have an additional table (similar to Earnings and Deductions) in the Salary Structure and Salary Slip forms for Contributions i.e. staff retirement benefits contributed by employer. Contributions from employers are typically not included in the monthly Net Pay calculation.

**Comment by rmehta** [comment]
Contributions from employer are usually part of the full package, so they can be in deductions?

**Comment by KanchanChauhan** [comment]
@system19 new Salary Structure in v7
