### ISSUE TITLE
Bug: Sales Invoice

### ISSUE THREAD

**Issue by Naspleda** [frappe/erpnext#44328]
### Information about bug

fix: net_amount calculation #44231

As of this PR, Sales invoice not work

![image](https://github.com/user-attachments/assets/1c07daaf-1499-4055-91b9-239e2ec05000)

![image](https://github.com/user-attachments/assets/0ec336cb-9d90-48ba-b4c2-1cffba8506a9)

### Module

stock

### Version

Frappe Version 16.0.0-dev nvg-develop
Erpnext .29.0 nvg-develop

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
16:34:34 web.1         |   File "apps/frappe/frappe/app.py", line 118, in application
16:34:34 web.1         |     response = frappe.api.handle(request)
16:34:34 web.1         |   File "apps/frappe/frappe/api/__init__.py", line 49, in handle
16:34:34 web.1         |     data = endpoint(**arguments)
16:34:34 web.1         |   File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
16:34:34 web.1         |     return frappe.handler.handle()
16:34:34 web.1         |   File "apps/frappe/frappe/handler.py", line 49, in handle
16:34:34 web.1         |     data = execute_cmd(cmd)
16:34:34 web.1         |   File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
16:34:34 web.1         |     return frappe.call(method, **frappe.form_dict)
16:34:34 web.1         |   File "apps/frappe/frappe/__init__.py", line 1807, in call
16:34:34 web.1         |     return fn(*args, **newargs)
16:34:34 web.1         |   File "apps/frappe/frappe/utils/typing_validations.py", line 32, in wrapper
16:34:34 web.1         |     return func(*args, **kwargs)
16:34:34 web.1         |   File "apps/erpnext/erpnext/__init__.py", line 189, in wrapper
16:34:34 web.1         |     return func(ctx, *args, **kwargs)
16:34:34 web.1         |   File "apps/erpnext/erpnext/stock/get_item_details.py", line 100, in get_item_details
16:34:34 web.1         |     out.item_tax_rate = get_item_tax_map(
16:34:34 web.1         |   File "apps/frappe/frappe/utils/typing_validations.py", line 32, in wrapper
16:34:34 web.1         |     return func(*args, **kwargs)
16:34:34 web.1         |   File "apps/erpnext/erpnext/stock/get_item_details.py", line 693, in get_item_tax_map
16:34:34 web.1         |     for t in (t for t in (doc.get("taxes") or []) if not t.set_by_item_tax_template):
16:34:34 web.1         |   File "apps/erpnext/erpnext/stock/get_item_details.py", line 693, in <genexpr>
16:34:34 web.1         |     for t in (t for t in (doc.get("taxes") or []) if not t.set_by_item_tax_template):
16:34:34 web.1         | AttributeError: 'dict' object has no attribute 'set_by_item_tax_template'
```

**Comment by Naspleda** [comment]
![image](https://github.com/user-attachments/assets/adfa9b95-2bc4-49c4-8be0-b013fca62ceb)

With the new changes, still don't calculate tax and totals @barredterra

**Comment by Naspleda** [comment]
[‎erpnext/public/js/controllers/taxes_and_totals.js](https://github.com/NovigoTechnology/erpnext/commit/3732dd1b1f57b099635cc849dfe388e5b63461ba#diff-9faea27a2ac47e603914ab1813d4b3d9c26e60135d60753701603ddfad5b2e5f)

In this file, I found in line 250 "var current_net_amount = 0.0" was deleted but is referenced after

![image](https://github.com/user-attachments/assets/572ffbaa-891e-442a-8cf0-03321575ed6f)

**Comment by barredterra** [comment]
I'd like to leave fixes of the logic errors to @blaggacao. I can only fix some syntax issues here.

**Comment by blaggacao** [comment]
Hi sorry, didn't see this before. I can have a look / provide any missing fix tomorrow.

Thanks for tagging me.

**Comment by blaggacao** [comment]
I think getting some client testing (cypress) also into erpnext would help, on the longer run.

I've seen some organically grown discrepancies between some of the client side and server side calculations that already seemed accidental in nature while doing the refactor.

This is definitely a regression / oversight though.
