### ISSUE TITLE
Parent Label is not visible on the website

### ISSUE THREAD

**Issue by Nandani-20** [frappe/erpnext#44333]
### Information about bug

I have set the parent label for the navbar but it is not showing me in the navbar

![image](https://github.com/user-attachments/assets/efd12d5b-1bff-4a3b-8bc1-f9fdb4e71d68)

![image](https://github.com/user-attachments/assets/845d8d4c-0e27-4ed0-a828-7bdaa0094c40)

### Module

ecommerce, other

### Version

ERPNext: v14.76.0 (version-14)

Frappe Framework: v14.85.1 (version-14)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Parent Label is not visible on the navbar
```

**Comment by Nandani-20** [comment]
@ruthra-kumar

**Comment by Nihantra-Patel** [comment]
We tested, it's worked properly, and remove Company from Parent Label from Company row.

[scrnli_eb31BUd3FZLFW3.webm](https://github.com/user-attachments/assets/af940861-72b1-4f5e-9700-74db7ddc15cf)
