### ISSUE TITLE
Accounts Receivable Summary Report (Customer Aging Report) having values in seperated days section is not correct for eg. 1 - 30 column values is not correct and many more

### ISSUE THREAD

**Issue by alaaelshamy** [frappe/erpnext#44352]
### Information about bug

The Accounts Receivable Summary Report is not working correctly,
In this report only outstanding column data is  correct
And all the days seperated column is not correct
for eg. 0-30 days, 31-60 days, ............. etc.
**I want all values in these column calculated correctly**

### Module

accounts

### Version

I dont know the version but iam using this link for my application
http://35.170.104.156/#login

### Installation method

None

**Comment by ruthra-kumar** [comment]
@alaaelshamy 

it looks like you are using ERPNext v12, which reached it's [EOL on Dec 2022](https://github.com/frappe/erpnext/wiki/Supported-Versions). 

You can check https://discuss.frappe.io/ for community support.
