### ISSUE TITLE
Server Script it't not working

### ISSUE THREAD

**Issue by yahyaoudra** [frappe/erpnext#44374]
### Information about bug

I'm experiencing an issue where server scripts are not executing as expected in ERPNext v15. Specifically, I've created a simple server script that is intended to run on the Customer doctype with the After Insert event, but the script doesn't appear to trigger at all. I've verified the script setup and also attempted different document types and events, but none seem to work.

Environment:

ERPNext Version: 15.43.3
Frappe Version: v15.48.1

Steps to Reproduce:

Go to Settings > Server Script and create a new server script.
Script Type: Document Event
Reference Document Type: Customer
Event: After Insert

Script:
python
Copy code
```
def create_project_and_tasks(doc, method):
    frappe.log_error(title="Server Script Trigger Test", message=f"Server script has been triggered for the document: {doc.name}")
    frappe.throw("Server script triggered successfully.")
```
Save the script and ensure it is Active.
Create a new Customer from the Customer doctype.
Expected Behavior:

When a new customer is created, the server script should:
Log an entry in the Error Log with the title "Server Script Trigger Test".
Raise an error saying "Server script triggered successfully."

Actual Behavior:

No log entries are created in the Error Log.
No pop-up error is displayed after saving the customer.
It appears that the server script is not being triggered at all.
Additional Details:

I have verified that the server script feature is enabled in the site_config.json with "server_script_enabled": true.
I have also tried other document types (e.g., Sales Order) and different events (Before Insert, Before Save).
Client scripts are working fine, and I can confirm that client-side execution triggers as expected.
I tried restarting the bench and verified that the script is active and permissions are appropriate, but still no luck.
No relevant logs or errors appear in the Error Log or in the bench console when running the server script.

Steps Taken for Troubleshooting:

Restarted ERPNext services using bench restart.
Ensured that the server script feature is enabled.
Tested on different doctypes and events.
Verified user permissions and logged in as an administrator.
Monitored the bench console but didn't observe any related errors or logs.

### Module

selling, other

### Version

ERPNext Version: 15.43.3
Frappe Version: v15.48.1

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
We tested it locally and also in the frappe cloud side in that version so it's worked properly. if you use server script doctype then no need to add method and import package or library.

[scrnli_fXen4q499Z11Yb.webm](https://github.com/user-attachments/assets/94bf3b2a-2249-4c90-9962-c14422ea6ce5)

**Comment by yahyaoudra** [comment]
Hi there,
thanks For reply.I see
but on my side your script worked 
what's wrong with mine here please

`def create_default_project(doc, method):
    if not doc or not doc.name:
        frappe.log_error("Invalid customer document")
        return
    
    try:
        frappe.log_error(f"Attempting to create project for customer: {doc.name}")
        
        project = frappe.new_doc('Project')
        
        frappe.log_error(f"New project document created: {project}")
        
        project.project_name = f"Project for {doc.customer_name}"
        
        project.customer = doc.name
        
        project.status = 'Open'
        
        try:
            project.save(ignore_permissions=True)
            frappe.log_error(f"Project saved successfully for {doc.customer_name}")
        except Exception as save_error:
            frappe.log_error(f"Error saving project: {str(save_error)}")
            frappe.log_error(f"Project document details: {project.as_dict()}")
            raise
        
        frappe.msgprint(f"Created default project for {doc.customer_name}")
    
    except Exception as e:
        frappe.log_error(f"Complete error creating project for {doc.customer_name}")
        frappe.log_error(f"Error details: {str(e)}")
        frappe.log_error(f"Customer document: {doc.as_dict()}")
        frappe.throw(f"Could not create project: {str(e)}")

def execute(doc, method):
    create_default_project(doc, method)

def on_update(doc, method):
    create_default_project(doc, method)`
