### ISSUE TITLE
POS Module slow 

### ISSUE THREAD

**Issue by noetico** [frappe/erpnext#4438]
The POS module is slow on ERPNext; during v4 it was very snappy and fast; I think it has something to do with the way the module pulls items; loading everything at once. Is there a way to limit the number of items being loaded from pos.py? Below is the pos.py file as shipped with ERPNext; how and where do we limit the items to a small set of items like the first 100 only and then let search and barcode scanning work as usual.

from __future__ import unicode_literals
import frappe

@frappe.whitelist()
def get_items(price_list, sales_or_purchase, item=None):
	condition = ""
	order_by = ""
	args = {"price_list": price_list}

	if sales_or_purchase == "Sales":
		condition = "i.is_sales_item=1"
	else:
		condition = "i.is_purchase_item=1"

	if item:
		# search serial no
		item_code = frappe.db.sql("""select name as serial_no, item_code
			from `tabSerial No` where name=%s""", (item), as_dict=1)
		if item_code:
			item_code[0]["name"] = item_code[0]["item_code"]
			return item_code

		# search barcode
		item_code = frappe.db.sql("""select name, item_code from `tabItem`
			where barcode=%s""",
			(item), as_dict=1)
		if item_code:
			item_code[0]["barcode"] = item
			return item_code

		condition += " and ((CONCAT(i.name, i.item_name) like %(name)s) or (i.variant_of like %(name)s) or (i.item_group like %(name)s))"
		order_by = """if(locate(%(_name)s, i.name), locate(%(_name)s, i.name), 99999),
			if(locate(%(_name)s, i.item_name), locate(%(_name)s, i.item_name), 99999),
			if(locate(%(_name)s, i.variant_of), locate(%(_name)s, i.variant_of), 99999),
			if(locate(%(_name)s, i.item_group), locate(%(_name)s, i.item_group), 99999),"""
		args["name"] = "%%%s%%" % frappe.db.escape(item)
		args["_name"] = item.replace("%", "")

	# locate function is used to sort by closest match from the beginning of the value
	return frappe.db.sql("""select i.name, i.item_name, i.image,
		item_det.price_list_rate, item_det.currency
		from `tabItem` i LEFT JOIN
			(select item_code, price_list_rate, currency from
				`tabItem Price`	where price_list=%(price_list)s) item_det
		ON
			(item_det.item_code=i.name or item_det.item_code=i.variant_of)
		where
			ifnull(i.has_variants, 0) = 0 and
			{condition}
		order by
			{order_by}
			i.name""".format(condition=condition, order_by=order_by), args, as_dict=1)

**Comment by rmehta** [comment]
Thanks fixed via https://github.com/frappe/erpnext/commit/441b2c765743987037b9a2b99e6e0520d451861b

**Comment by noetico** [comment]
Thanks Rushabh; will add these lines.

Best regards;

Kent
Noetico.IT Corporate Mail

-----Original Message-----

**Comment by noetico** [comment]
Hello Rushabh; I just tried the limit and it didn't work; it doesn't reduce our items pulled into the grid. What does the 99999 around lines 35 to 38 do? 

Thanks.
Noetico.IT Corporate Mail

-----Original Message-----

**Comment by anandpdoshi** [comment]
Did you do bench update?

You need to restart the frappe server processes for changes to take effect.

Best,
Anand Doshi

ERPNext

**Comment by noetico** [comment]
Thanks! That did it. I also suggest this little update should be added in the updates; the pos is super-blazing fast now.

Thanks to the best ERP team in the world.

Noetico.IT Corporate Mail

-----Original Message-----
