### ISSUE TITLE
User Manual

### ISSUE THREAD

**Issue by ShashaQin** [frappe/erpnext#4440]
https://frappe.github.io/erpnext/user/manual/en/human-resources/tools/leave-allocation-tool.html
The leave allocation tool page of user manual is using incorrect page sample which is leave application page snapshot.

**Comment by anandpdoshi** [comment]
@ShashaQin thanks for reporting!

**Comment by rmehta** [comment]
Update: https://frappe.github.io/erpnext/user/manual/en/human-resources/leave.html
