### ISSUE TITLE
404 after installation

### ISSUE THREAD

**Issue by charleslcso** [frappe/erpnext#44421]
### Information about bug

Been manual installing v13 for a long time a few years ago.
Now I'm back to installing v15. 

Used this guide https://github.com/frappe/bench, and installed a frappe site.

`root@backoffice:/opt/frappe_docker# systemctl stop nginx
root@backoffice:/opt/frappe_docker# python3 easy-install.py --prod --email frappeadmin@email.com
 
Setting Up Production Instance
 
Please refer to .example.env file in the frappe_docker folder to know which keys to set

[+] Running 7/7
 ✔ queue-short Pulled                                                                                                            2.2s 
 ✔ scheduler Pulled                                                                                                              2.3s 
 ✔ configurator Pulled                                                                                                           2.3s 
 ✔ queue-long Pulled                                                                                                             2.3s 
 ✔ frontend Pulled                                                                                                               2.1s 
 ✔ websocket Pulled                                                                                                              2.3s 
 ✔ backend Pulled                                                                                                                2.3s 
[+] Running 11/11
 ✔ Container frappe-db-1            Healthy                                                                                      0.5s 
 ✔ Container frappe-redis-queue-1   Running                                                                                      0.0s 
 ✔ Container frappe-redis-cache-1   Running                                                                                      0.0s 
 ✔ Container frappe-proxy-1         Started                                                                                      0.5s 
 ✔ Container frappe-configurator-1  Exited                                                                                       5.9s 
 ✔ Container frappe-queue-long-1    Started                                                                                      0.9s 
 ✔ Container frappe-backend-1       Started                                                                                      0.8s 
 ✔ Container frappe-websocket-1     Started                                                                                      0.7s 
 ✔ Container frappe-scheduler-1     Started                                                                                      1.1s 
 ✔ Container frappe-queue-short-1   Started                                                                                      0.8s 
 ✔ Container frappe-frontend-1      Started                                                                                      0.6s 
 
Creating site: site1.localhost 
 
--no-mariadb-socket is DEPRECATED; use --mariadb-user-host-login-scope='%' (wildcard) or --mariadb-user-host-login-scope=<myhostscope>, instead. The name of this option was misleading: it had nothing to do with sockets.

Installing frappe...
Updating DocTypes for frappe        : [========================================] 100%
Updating Dashboard for frappe

Installing erpnext...
Updating DocTypes for erpnext       : [========================================] 100%
Updating customizations for Address
Updating customizations for Contact
Updating Dashboard for erpnext
site1.localhost: SystemSettings.enable_scheduler is UNSET
*** Scheduler is disabled ***
Current Site set to site1.localhost
`

First of all, why is it site1.localhost? Not just site1.local?

Next, it seems to be running:
`docker-pr 6699     root    4u  IPv4 368608575    0t0  TCP *:http (LISTEN)
docker-pr 6707     root    4u  IPv6 368603079    0t0  TCP *:http (LISTEN)
docker-pr 6713     root    4u  IPv4 368606685    0t0  TCP *:https (LISTEN)
docker-pr 6720     root    4u  IPv6 368603084    0t0  TCP *:https (LISTEN)`

Next, the log file is not under $HOME as stated in the doc. It is in the frappe install directory.

This is the content of the log:
`
root@backoffice:/opt/frappe_docker# cat easy-install.log
2024-11-29 13:55:36,819 - INFO - Running Production Setup
2024-11-29 13:55:47,350 - INFO - Docker Compose file generated at ~/frappe-compose.yml
2024-11-29 13:59:34,629 - INFO - New site creation completed
`

I hard linked site1.local and site1.localhost to IP.

Browser accepted the cert by "TRAEFIK DEFAULT CERT", but I get "404 page not found".

What now?

### Module

other

### Version

Frappe version and bench version - no idea

### Installation method

docker

### Relevant log output / Stack trace / Full Error Message.

```shell
root@backoffice:/opt/frappe_docker# cat easy-install.log
2024-11-29 13:55:36,819 - INFO - Running Production Setup
2024-11-29 13:55:47,350 - INFO - Docker Compose file generated at ~/frappe-compose.yml
2024-11-29 13:59:34,629 - INFO - New site creation completed
```

**Comment by charleslcso** [comment]
Duh!

I need to install docker-compose, run it inside the installation directory, then run:

* docker-compose -f ./pwd.yml up

The URL is :8080, not 80!

Now the login page loads!

Please revise the documentation!

What is the administrator login email? The email I used during the above install process returns "User does not exist"!

How do I log in?

**Comment by maniamartial** [comment]
@charleslcso What 

> Duh!
> 
> I need to install docker-compose, run it inside the installation directory, then run:
> 
> * docker-compose -f ./pwd.yml up
> 
> The URL is :8080, not 80!
> 
> Now the login page loads!
> 
> Please revise the documentation!
> 
> What is the administrator login email? The email I used during the above install process returns "User does not exist"!
> 
> How do I log in?

What about using Administrator as username, should be able to login.

**Comment by charleslcso** [comment]
Need to run a command to set administrator's password, then I can log in using "administrator"
