### ISSUE TITLE
Employee Advance Status is not updating after payment Entry

### ISSUE THREAD

**Issue by DileepMedayil** [frappe/erpnext#44452]
### Information about bug

After making the payment entry the status of employee advance still shows unpaid.

### Module

HR

### Version

ERPNext: v15.43.0 (version-15)

Frappe Framework: v15.48.0 (version-15)

Frappe HR: v16.0.0-dev (develop)

### Installation method

manual install

**Comment by Nihantra-Patel** [comment]
We tested in the latest version, but we haven’t found the issue. The status will update when you submit the Payment Entry.

Also, I shared a suggestion:
If you’ve installed ERPNext in version 15, make sure the hrms is also in version 15 to prevent errors.

[scrnli_JSwRnaQI5MTJxR.webm](https://github.com/user-attachments/assets/14c9e715-cf28-4fa6-b810-b69c3c3dfead)
