### ISSUE TITLE
Fields not loading in the POS Profile doctype

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#44487]
### Information about bug

Only for frappe team. Check following link to replicate the issue.

Check: https://spindl16.frappe.cloud/app/pos-profile/Cashier%201

### Module

POS / selling

### Bug

<img width="1154" alt="Screenshot 2024-12-03 at 5 47 31 PM" src="https://github.com/user-attachments/assets/7d4184c9-e756-4cad-9f8e-20fb202ee1c0">

### Version

Installed Apps
ERPNext: v16.0.0-dev (HEAD)

Framework: v16.0.0-dev (HEAD)

Frappe HR: v16.0.0-dev (HEAD)

India Compliance: v16.0.0-dev (HEAD)

Payments: v0.0.1 (HEAD)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
Using this console may allow attackers to impersonate you and steal your information. Do not enter or paste code that you do not understand.
script_manager.js:32 ƒ (frm) {
		frm.set_query("selling_price_list", function () {
			return { filters: { selling: 1 } };
		});

		frm.set_query("tc_name", function () {
			return { filters: { selling: 1 } };
		});

		erpn…
d @ script_manager.js:32Understand this errorAI
request.js:309 Unable to handle success response Object
request.js:310 ReferenceError: erpnext is not defined
    at setup (pos_profile__js:19:3)
    at d (script_manager.js:30:12)
    at n (script_manager.js:109:16)
    at script_manager.js:125:5
    at Array.forEach (<anonymous>)
    at frappe.ui.form.ScriptManager.trigger (script_manager.js:122:22)
    at frappe.ui.form.ScriptManager.setup (script_manager.js:247:8)
    at frappe.ui.form.Form.setup (form.js:116:23)
    at frappe.ui.form.Form.refresh (form.js:445:10)
    at frappe.views.FormFactory.render (formview.js:107:45)
```

**Comment by umairsy** [comment]
Same for POS as well.

point-of-sale:1 Uncaught SyntaxError: Failed to execute 'appendChild' on 'Node': Unexpected token '<'
    at Object.eval (dom.js:33:44)
    at Object.js (assets.js:27:16)
    at go.eval_assets (assets.js:82:33)
    at assets.js:111:8
    at Array.forEach (<anonymous>)
    at assets.js:109:10Understand this errorAI
point_of_sale.js:11 Uncaught (in promise) TypeError: erpnext.PointOfSale.Controller is not a constructor
    at point_of_sale.js:11:17
    at assets.js:17:16
    at assets.js:114:4

<img width="1157" alt="Screenshot 2024-12-03 at 5 50 01 PM" src="https://github.com/user-attachments/assets/77810de9-64ea-4b2d-a467-9ba8c8959e0a">

**Comment by diptanilsaha** [comment]
Could not replicate the bug.
