### ISSUE TITLE
Name, Lastname and Company name Fields

### ISSUE THREAD

**Issue by Ooops-404** [frappe/erpnext#4448]
Why not use different fields?
I know that currently we can select the contact type to be "individual or Company", that helps.

But having a different field for the name and another for the last name will help not only in importing records from other CRM's/ERP's* but also with the newsletters.
I am sure some of us greet their contacts with Hi/hello/dear [name] and prefer to stear away from using the full name (more professional but less friendly). Whoever, having two fields will give everyone the flexibility to do as they wish.

(all other CRMs/ERPs I have seen use two fields, and some also have the optional "title" (dr. mr, etc).

As anyone customize NEXTErp in this way? if so, ho did you do it?

**Comment by system19** [comment]
Regarding customer names in ERPNext, Why do we use a Full Name when creating a new customer and Address but use First Name & Last Name when creating a Contact? What is the advantage of this? @Ooops-404 I can post a simple Concat custom script on frappe forums that may assist you in allowing you to enter First Name Last Name during new customer creation. I found it pretty easy to concat other ERP name data in a spreadsheet prior to importing into ERPNext.

**Comment by Ooops-404** [comment]
The advantage of using First Name & Last Name is the possibilities that it gives you to handle that data. A good example is when you're preparing a newsletter. The latest trend(?) is to communicate with the clients in a first name basis in order to come across as friendly and personal.

Scenarion above:
If you want to use the full name: [firstname] [lastname]
If you only want to use the first name: [firstname]


@system19 I did that  (I am currently on it...) but its easier to do that than the other way around (as in spliting the first and last name on a later date in an automated fashion).

**Comment by system19** [comment]
@Ooops-404 The First Name Last Name structure does make sense when explained. To have First Name, Initial, Last Name would be great in English speaking countries. This would help avoid issues when trying to add a new customer with the same name as an already entered customer.

**Comment by Ooops-404** [comment]
@system19 That would be perfect, adding the "title" would also be useful for allot of people too (not me personally, but I know some companies do care).

**Comment by system19** [comment]
Forgot to add that the "Initial" field should be optional and can be left blank. This is important.

**Comment by yashodhank** [comment]
Things you are talking about can be customized easily and if you want them to be part of core product then please care to open topic for larger discussion and more inputs at https://discuss.erpnext.com

@Ooops-404 Discussions regarding any feature or unless you are not sure if its an issue, should be strictly done at https://discuss.erpnext.com
Please adhere to community standards and please follow guideline, it will help reduce the workload of core team.

**Comment by Ooops-404** [comment]
@yashodhank Thanks, I will do so.

**Comment by Ooops-404** [comment]
New home for the discussion,

https://discuss.erpnext.com/t/name-lastname-and-company-name-fields/8951/2
