### ISSUE TITLE
Adding columns of Item Code, Item Name and brand without description

### ISSUE THREAD

**Issue by stepsibg** [frappe/erpnext#4451]
As per current format, values of item code, item name, image etc. are contained in description column of the reports. I need a format where brand, item code and item name are separate columns and description column should be hidden. One of our customer would like to receive quotation from us in this format and I am unable to design my Print Format accordingly by enabling desired fields in "Print Format Builder" > Items Table > Select Table Columns for Items"

**Comment by rmehta** [comment]
@stepsibg you can make a new print format in HTML from scratch

https://frappe.github.io/erpnext/user/manual/en/customize-erpnext/print-format
