### ISSUE TITLE
ِPurchase order analysis report bug

### ISSUE THREAD

**Issue by NEW-MTC-ERP1** [frappe/erpnext#44536]
### Information about bug

Hello,
In subject report - Purchase Order Analysis, when you receive the same item in more than one line, the report will only read the first line of the Purchase receipt and ignores other lines' quantities (usually this is applies when receiving batched items).  (same case in Sales Order analysis)

### Module

buying

### Version

Frappe Framework: v15.48.1 (HEAD)
ERPNext: v15.44.0 (HEAD)
<img width="763" alt="image" src="https://github.com/user-attachments/assets/40d563b8-9182-4d16-a040-69210acc9727">
<img width="784" alt="image" src="https://github.com/user-attachments/assets/08ba745a-11fe-4924-bf07-9b1f85a8da9f">
<img width="722" alt="image" src="https://github.com/user-attachments/assets/dfbf1b23-6578-4a32-ae91-eff401c9bbd7">

### Installation method

FrappeCloud

**Comment by rohitwaghchaure** [comment]
@NEW-MTC-ERP1 Checked on local system and it's working. It seems that the second row has no reference of PO Line item.
To fix the issue, use the duplicate button while splitting the row in the purchase receipt instead of manually adding new rows

**Comment by NEW-MTC-ERP1** [comment]
Great Job, many thanks, I missed this one.
