### ISSUE TITLE
asset_maintenance_log file missing?

### ISSUE THREAD

**Issue by sambhxv** [frappe/erpnext#44588]
### Information about bug

While running `bench migrate`, I saw this warning statement:
![image](https://github.com/user-attachments/assets/84085a9b-2bd0-41c6-a17a-442f4e5a8e16)

Clearly, it shows that the given function `update_asset_maintenance_log_status` is referenced somewhere in erpnext but is not implemented in the app, and the file containing it seems to be missing.

### Module

other

### Version

ERPNext version: v15.29.0
Frappe Framework: v15.32.0

### Installation method

docker

**Comment by malikrohail** [comment]
can i fix

**Comment by khushi8112** [comment]
Hey, @sambhxv @malikrohail already fixed via - https://github.com/frappe/erpnext/pull/42157
