### ISSUE TITLE
Email Alert Recipiants 

### ISSUE THREAD

**Issue by Devens** [frappe/erpnext#4461]
Only Email fields should be displayed here (Pl see the screenshot below). 

![image](https://cloud.githubusercontent.com/assets/10671911/11707135/063b1bce-9f26-11e5-8725-5a2f1aaf4be2.png)

**Comment by Ferohers** [comment]
Time to  to we create custom forms and need to choose different rules for email settings. This is one of the best feature of ERPNext. I understand it might cause a bit confusion but it is very useful.

For example I create an announcement archive under HR. one of the field called 
"To whom" and once it is saved it send the contents to related email group such as, managers, supervisors or everyone.

**Comment by rmehta** [comment]
fixed
