### ISSUE TITLE
[V16] Company master not loading

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#44634]
### Information about bug

When navigate to Company master from a Company link field, then end-up on this screen... Do note the URL as well

<img width="998" alt="Screenshot 2024-12-10 at 2 19 07 PM" src="https://github.com/user-attachments/assets/246c48b7-3ebb-4bf8-af31-8b7c576363a9">

Note that this site was created by restore the V15 site, where "skip patches error" etc. was enabled.

### Module

accounts, buying

### Version

Installed Apps
ERPNext: v16.0.0-dev (HEAD)

Framework: v16.0.0-dev (HEAD)

Frappe HR: v16.0.0-dev (HEAD)

India Compliance: v16.0.0-dev (HEAD)

Payments: v0.0.1 (HEAD)

[Dependencies & Licenses](https://spindl16.frappe.cloud/attribution)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
script_manager.js:32 setup(frm) {
        erpnext.company.set_custom_query(frm, [
            "default_customs_expense_account",
            { root_type: "Expense" },
        ]);
        erpnext.company.set_custom_query(…
d @ script_manager.js:32Understand this errorAI
form.js:1683 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'grid')
    at frappe.ui.form.Form.set_query (form.js:1683:27)
    at setup (company__js:538:13)
    at d (script_manager.js:30:12)
    at n (script_manager.js:109:16)
    at script_manager.js:125:5
    at Array.forEach (<anonymous>)
    at frappe.ui.form.ScriptManager.trigger (script_manager.js:122:22)
    at frappe.ui.form.ScriptManager.setup (script_manager.js:247:8)
    at frappe.ui.form.Form.setup (form.js:116:23)
    at frappe.ui.form.Form.refresh (form.js:445:10)
```

**Comment by nabinhait** [comment]
It's loading after upgrading the site
