### ISSUE TITLE
to change Column width of ID field in Report

### ISSUE THREAD

**Issue by Devens** [frappe/erpnext#4464]
to change the minimum width of ID Column (all other columns' width can be changed by drag-drop & save, but not for ID Column).

https://discuss.erpnext.com/t/how-to-change-column-width-of-id-field-in-report/8958

**Comment by m-delvalle** [comment]
+1

**Comment by kennethsequeira** [comment]
Closing the issue since currently under v12, one can reduce column size by dragging the column width. Columns can be hidden as well.
