### ISSUE TITLE
Email to issue not working

### ISSUE THREAD

**Issue by omnison** [frappe/erpnext#4470]
I set up email account "support@mankem.com" for support and append to "Issue", but when i send any email to "Support@mankem.com" through other email account, i can get responce like:
Thank you for your email
Your query has been received. We will reply back shortly. If you have any additional information, please reply to this mail.
Reference: Issue ISS-00003
This is an automatically generated reply
This email was sent to gavin.ji@msn.com
Leave this conversation

But i cannot find this issue that should be generated in issue section in ERPnext. 

So what is problem and how to fix it.

**Comment by rmehta** [comment]
@omnison can you post this on the forum https://discuss.erpnext.com
