### ISSUE TITLE
Unselect All button ticks checkbox

### ISSUE THREAD

**Issue by sh3hz** [frappe/erpnext#44709]
### Information about bug

User > Roles & Permissions > Roles > Role Profile
Select All and Unselect All button acts opposite function

https://github.com/user-attachments/assets/0c6f622e-2010-4243-b920-f790c995b923

### Module

other

### Version

ERPNext: v15.45.4 (HEAD)
Frappe Framework: v15.50.0 (HEAD)

### Installation method

FrappeCloud

**Comment by rs-rethik** [comment]
Hi @sh3hz 
Kindly refresh the page and check else migrate the site once
It may work
