### ISSUE TITLE
Price List inconsistency in POS page after backtracking from checkout

### ISSUE THREAD

**Issue by Shirkit** [frappe/erpnext#44700]
### Information about bug

Let's say you have two price lists, PL1 and PL2, and you have an item, I1. Suppose you have a POS of setup so that it loads the price list PL1, but the I1 has two prices, one for PL1 and one for PL2.

Now, once on the POS page, the first time you load in and select the customer, it loads PL1 for the price of I1.

If you have a Customer that has the Price List of PL2, if you select it on the POS page, it still displays the prices for PL1 as it's documented.

However, if you then add an item to the cart, go to checkout, and then click back on "Edit Cart", the price for all the items will be PL2, overriding the setting on the POS profile.

This is both good and bad behavior in my opinion, as it can actually load the prices for PL2 (despite the documentation), but in an inconsistent way (which is obviously bad).

There's two possible solutions:
1. Use the price list for the client, which solves many POS issues and allows users a finer grain of control
2. Only use the price list described for the POS Profile

IMO it should be the `1` as the behavior, and maybe include a fallback if the item has no price for the loaded Price List.

[Screencast from 2024-12-13 18-25-37.webm](https://github.com/user-attachments/assets/d3492ffa-7eff-45ee-9e09-24ba0280cb22)

### Module

selling

### Version

Frappe version - v15.39.3 (version-15)
ERPNext version - v15.45.1 (version-15)

### Installation method

manual install

**Comment by diptanilsaha** [comment]
@Shirkit can you give an example, where you need a separate price list for customers in pos?

**Comment by Shirkit** [comment]
Certainly @diptanilsaha 

I work in a small/medium sized producing company, where we deal with two types of customers: resellers and direct buyers.

Both of them can purchase remote and in-store, and most of the sales happens in-store. For direct buyers, they pay full price for each product, while resellers are pre-authorized to have access to a fixed discounted price, and that price varies from product by product, and not all products have a discounted price. Some products have a 5/10/15/20/30% off, some have an absolute 5/9/14/25 currency units off, and some no discount at all.

There's no single pricing policy that we could come up with to simplify and keep both customers and company happy, and that can be applied that satisfies all these requirements except for a different pricing list. We could open two registers, one for direct buyers and one for resellers, but now the reports gets mixed up.

We use the POS to more easily sell in-store to allow faster sales. Currently, we deal with this by automating pricing rule for all products that have a different price for one type of customer vs the other, apply a fixed discount on them on the direct buyer price, and only use that pricing list on the POS.

**Comment by Shirkit** [comment]
That was awesome! I tried fixing it myself but couldn't find a way, glad you know the ways into ERPNext to be able to tackle these things.

One question though, what happens if a product has no price in that price list? Is there any fallback for that product?

**Comment by diptanilsaha** [comment]
price will be " 0 / {uom} " if the product does not exist in a price list.

**Comment by Shirkit** [comment]
Thank you! I guess that makes perfect sense, there shouldn't be any additional action being done.

I'll just copy the prices from the price list when no discount should be applied. Now I can remove the mess of the pricing rules automation I've made.
