### ISSUE TITLE
Private Attachments Files Unable to Read

### ISSUE THREAD

**Issue by justinlusg** [frappe/erpnext#4474]
![image](https://cloud.githubusercontent.com/assets/12539216/11718892/29f58b18-9f93-11e5-99ae-2b516aa63e87.png)

After the update, I am unable to open private attachment files even when I am logged on.

**Comment by justinlusg** [comment]
Also another thing is, the files are not deleted off the server when I delete the attachments within ERP. e.g. the file is deleted in ERP but it still physically exists in the private/files folder

**Comment by justinlusg** [comment]
Solution, 
bench update
bench setup nginx
sudo service nginx reload

**Comment by nasir97177** [comment]
I have issues when I want to Attachment file, It is not showing 
Kindly help me
