### ISSUE TITLE
 Calendar 24-hour time format 

### ISSUE THREAD

**Issue by barkode** [frappe/erpnext#4480]
Settings to select the presentation time on the calendar in 24-hour format or 12 hour format.

**Comment by umairsy** [comment]
Closing this issue as no user has request for it. Feel free to reopen if needed.

**Comment by anajo333** [comment]
hello @umairsy  i have two qustions :
1- There is no option to change the time format from 24h to 12h with am&pm ??
my erpnext now only show me a 24h time format

2- Tools>Calendar
if user language is english events in Calender is showing without any problem
if user language is arabic   events in Calender be hidden .. how can i solve that ? 
** iam using lastest version for OCT-2020 from erpnext

**Comment by hoddertug** [comment]
Hello, could you please reopen this request and implement for v15? 
Better to have 12/24 hour time format in System settings for all environment.
