### ISSUE TITLE
Material Request based on forecast

### ISSUE THREAD

**Issue by brentglover** [frappe/erpnext#4482]
Hi

Looking to generate a material request from a forecast sales considering items in stock and then propose a material request for the missing quantity.  We have been informed that this feature doesn't exist and to raise it on github.

Thanks

Brent

**Comment by rmehta** [comment]
@brentglover  can you explain how do you want to generate a forecast? From Sales Order data?

**Comment by brentglover** [comment]
Yes

We generate a sales order based on our forecast.  The problem is that when we know we have for example 5 items in stock at that warehouse and create an order that includes 5 of these SAME items....the problem is that when we generate a purchase order it is still attempting to order these 5 items we already have in stock and obviously do not need to actually order.

Hope this makes sense to you - if you need access to our system please ask.

Brent

**Comment by rmehta** [comment]
@brentglover yeah i agree a basic regression based forecast is an ideal next step (there is no end!) I am just thinking how to prioritize this over all the requests we have. Do you have a budget to sponsor this?

**Comment by realstew** [comment]
We are just beginning to dive in to an erpnext installation to organize the sourcing, manufacturing, and distribution needs for our company. I am very impressed with the product simplicity and ease of implementation so far. It will be great for a number of our operational needs. 

The one thing that I am still trying to figure a best solution for, is forecasting. 

Has there been any further development or thought put into a forecasting module? 

Thanks
Nick

**Comment by rmehta** [comment]
> Has there been any further development or thought put into a forecasting module? 

No yet. Sharing detailed specs is a good place to start!

**Comment by deepeshgarg007** [comment]
Closing this as there are more similar open issues
