### ISSUE TITLE
German translation - "Lead"

### ISSUE THREAD

**Issue by KOAR** [frappe/erpnext#4485]
Hi there

I recommend "Lead" to translate by "Interessent" into German. "Lead" is not a common term in German.

Thanks

KOAR

**Comment by anandpdoshi** [comment]
Hi Koar,

You can contribute transactions at: https://translate.erpnext.com/view?lang=de

Best,
Anand Doshi

ERPNext

**Comment by KOAR** [comment]
Hi Anand

Yes I did it. But the following I could'nt correct (see attached). I have no authorization. Can you pleas do it for me?

Thanks

KOAR

[Uploading TranslateGermanLead.pdf…]()
