### ISSUE TITLE
Print contains Head and Foot of Browser

### ISSUE THREAD

**Issue by KOAR** [frappe/erpnext#4488]
Hi there

If I print out a form, for example an order, on the print out appears the header and footer of the browser (Firefox).

Pleas correct this issue.

Thanks

KOAR

**Comment by anandpdoshi** [comment]
Hi Koar,

This is a configuration in the browser and not part of ERPNext. Please go to Page Setup of the browser and remove the headers and footers.

Best,
Anand Doshi

ERPNext

**Comment by KOAR** [comment]
Hi Anand

I understand. But normally I'd like to show in my browser header an footer. But for ERPNext this is not desired. Nobody is interestet, to toggel on an off the browser headers and footers wether they are working in ERPNext or browsing in the www. This is not userfriendly and has to be solved in my way of thinking, especially if I think of user, which are not so familyar with IT.

Do you think, there would be a way to make it more convenience?

Regards

Art
