### ISSUE TITLE
Solution needed - amount in words: show or hide / unclear ending

### ISSUE THREAD

**Issue by KOAR** [frappe/erpnext#4489]
Hi there

On the forms the final amount is in words displayed. In the German language this text always ends with "nur." (example: "Dreitausendsechshundert nur.") That makes no sense. In Switzerland, a tendered amount is also mentioned with decimal fraction (example: "Dreitausendsechshundert 20/100").

I rather would prefere not to show this amount in words. Maybe you can add a function by default, if it should be shown generally or not.

Please provide a solution.

Thanks

KOAR

**Comment by anandpdoshi** [comment]
Hi Koar,

You can hide the Amount of Words in each form using Setup > Customize > Customize Form.

Here’s some help: https://frappe.github.io/erpnext/user/manual/en/customize-erpnext/customize-form

Best,
Anand Doshi

ERPNext

PS. Please close this issue if you think it is resolved.

**Comment by KOAR** [comment]
Thanks for the hint. It works ;-)
