### ISSUE TITLE
Missing Networker

### ISSUE THREAD

**Issue by KOAR** [frappe/erpnext#4490]
Hi there

"Networker (lobbyists)" are also an important group of people who are besides the "Leads" mostly without any buying intentions. But especially this group of people can contribute significantly to customer acquisition. For example: politicians, business leaders, consultants, recruiters, working groups, research group, association, government, etc. This group of people should be preceded with the prospects (leads) the CRM. Contrary to the leads must these individuals be managed proactively, not reactively. Somehow this Networkers would be Suppliers of Leads!

Please integrate these Networkers (German translation: "Netzwerker") as an independent group in ERPNext.

thank you

KOAR

**Comment by anandpdoshi** [comment]
Hi Koar

I think this is a rare use case and should be handled by creating a separate frappe app that extends ERPNext. You can get this done from a freelance developer. Check: community.erpnext.com

**Comment by rmehta** [comment]
These can be tracked via  custom field

**Comment by KOAR** [comment]
Yes, that's an idea. But in fact, the networkers are rather suppliers than customers. Because they may deliver new customers. In this sense, those in fact are supplier of services, but without financial claim.

Thanks for your hint.

KOAR
