### ISSUE TITLE
Unbounded postions for offer an billing

### ISSUE THREAD

**Issue by KOAR** [frappe/erpnext#4491]
Hi there

In a offer, order and when billing it should be possible to insert unbound positions, which are not included in the items database. Especially with services and works that would be very helpful.

We ask for a solution.

Thank you

KOAR

**Comment by anandpdoshi** [comment]
Hi Koar

Most of our reports use Item as a link that connects the transactions. What's preventing you from creating Items for services? It's item group can be Service and its inventory is not tracked.

**Comment by justinlusg** [comment]
Try creating an item called "non-inventory" item

**Comment by KOAR** [comment]
I will do it with a Item called "Services". Thanks for your help.
