### ISSUE TITLE
Browser tab - "E" should be blue

### ISSUE THREAD

**Issue by KOAR** [frappe/erpnext#4492]
Hi there

The icon "E" appears in the browser tab black, please change it to blue.

thank you

KOAR

**Comment by DrTrills** [comment]
@KOAR I think they just updated the favicon on purpose. If it's a big deal on your side, you could modify your version by changing the URL here to the favicon you prefer

https://github.com/frappe/erpnext/blob/cf3da35d675d17094ced40e2bde5d479c4c6f291/erpnext/hooks.py#L45

**Comment by KOAR** [comment]
No, it's not a problem, but I tought, the templet for new erpnext downloader could be corrected generally, so the color in the application would be the same as in the tab. Thank you anyway
