### ISSUE TITLE
Need Total on filtered query / report

### ISSUE THREAD

**Issue by Ardi2016** [frappe/erpnext#4499]
Total row can display normally on unfiltered report like shown below :
![image](https://cloud.githubusercontent.com/assets/16289397/11781527/08b7d12e-a29d-11e5-8f23-138aca05c949.png)

But once it is filtered (in this example using "Expense" under Account column header)
then the Total row disappeared as shown below
![image](https://cloud.githubusercontent.com/assets/16289397/11781631/b8195dfe-a29d-11e5-8a1c-ff0ff6c77294.png)

Such case happens in all other reports too.
Hopefully the reports can be enhanced so the Total for filtered column[s] will still be shown and calculated based on the filtered record(s)
Best Wishes
Ardi

**Comment by PratibhaPatil** [comment]
Please solve this issue as early as possible, because report are most important everywhere.

**Comment by revant** [comment]
https://github.com/frappe/erpnext/issues/7592

**Comment by magic-overflow** [comment]
@revant  have you tested it yet?
I don't think it works. This works only query report with add_total_row = true and total row contains string "Total". General Ledger add_total_row = false and total row contains "Totals" not "Total".

**Comment by magic-overflow** [comment]
Sorry, I thought u referred to solution to close this issue.
