### ISSUE TITLE
user does not got the module

### ISSUE THREAD

**Issue by shazasheik** [frappe/erpnext#4511]
actually in administrator i create the user in that user i click the access module in the name of "CRM, DESK , MARKETING , PROJECTS BUT I DONT GET THESE MODULES ON THE SPECIFIC USER 
![error user](https://cloud.githubusercontent.com/assets/16335702/11868733/1b385270-a4e0-11e5-99d7-90941df7e306.png)
"
ONLY I GOT 
![error user 2](https://cloud.githubusercontent.com/assets/16335702/11868769/5af4eef0-a4e0-11e5-9774-a65b195e3176.png)

**Comment by PawanMeh** [comment]
Please check the roles of the user, also try this on the latest version.
