### ISSUE TITLE
Problems with multicurrency entry 

### ISSUE THREAD

**Issue by ViktoriaFabbers** [frappe/erpnext#4512]
![image](https://cloud.githubusercontent.com/assets/12729830/11870271/cd2c123a-a4ce-11e5-8ead-4b0898d53c43.png)

**Comment by rmehta** [comment]
@ViktoriaFabbers you will have to add a row for "Currency Conversion Expense" or adjust your currency coversion rate to match the values in your company currency.

**Comment by ViktoriaFabbers** [comment]
Total debit and total credit are match, as you see - 6393.726 usd

**Comment by ViktoriaFabbers** [comment]
There was issue before this problem - currency exchange that system showed me was wrong, it didn't mach with anyone that have been all to the system. (1.13019usd=1 eur, and should be 1.1419 usd =1 eur) after a while system accept right  exchange rate, but gave me message on the screen.

**Comment by rmehta** [comment]
@nabinhait can you replicate?

**Comment by nabinhait** [comment]
@ViktoriaFabbers Can you try deleting the second row and adding a fresh row? Or may be after refreshing the system?

**Comment by ViktoriaFabbers** [comment]
![image](https://cloud.githubusercontent.com/assets/12729830/11891401/e89de08c-a566-11e5-80b2-bdbb47159be0.png)

Here is again. It first thing in the system today.

**Comment by nabinhait** [comment]
As per screenshot, "Credit in Account Currency" is wrongly entered. It should be less, so that Credit in Company Currency is equal to 6393.726

**Comment by ViktoriaFabbers** [comment]
![image](https://cloud.githubusercontent.com/assets/12729830/11891468/87332e5a-a567-11e5-8e4a-ae6c0989d999.png)

and exchange rate have been add 2 month ago

![image](https://cloud.githubusercontent.com/assets/12729830/11891475/a8962b42-a567-11e5-8700-1af793369cb3.png)

**Comment by ViktoriaFabbers** [comment]
amount in usd is wright, currency exchange is wrong. And it takes exch. automatically from somewhere.

**Comment by nabinhait** [comment]
Is it a bank account (Asset)? In that case, system takes average exchange rate as per available balance.

**Comment by nabinhait** [comment]
But you should be able to modify it manually.

**Comment by ViktoriaFabbers** [comment]
yes, it's Asset.  I modified, and it gave me an error in pic 1

**Comment by nabinhait** [comment]
Can you come on our chat support? We can continue a screen sharing session via Team Viewer.

**Comment by ViktoriaFabbers** [comment]
ok, min...
