### ISSUE TITLE
Pick columns in the price list

### ISSUE THREAD

**Issue by robertbecht** [frappe/erpnext#4515]
The Report: Item Price - Item-wise Price List Rate, under pick columns is missing some useful fields that allows filtering and sorting.
Status (active, depreciated)
Show in Webside
Brand
Item group
Supplier

A more fundemental approach would be a screen like used for eg the ledger, allowing the user to compose all sales, purchase, valuation , net & gross etc price/cost info, wit a set as fields (status,pricelist, show-in-website,brand, itemgroup, supplier, etc ) to generate the price list, that can than be printed.

**Comment by umairsy** [comment]
This report is based on Item Price doctype which doesn't have all the the particulars of items saved.

**Comment by kennethsequeira** [comment]
This can be achieved by:

1. Adding the custom fields which will fetch details from item master based on item code
2. Creating a new report based on standard item price list report by picking new columns.
