### ISSUE TITLE
Select Mode of Payment for POS

### ISSUE THREAD

**Issue by robertbecht** [frappe/erpnext#4516]
Currently the POS can only handle CASH, not more modern ways of payment (cardreader etc)
To allow other payment modes to be handled by the POS, an extra field in the Doc Payment_Mode will define this: POS-Payment (y/n)

rgds robert

**Comment by robertbecht** [comment]
Hi Nabin, Thanks for improved functionality, but the default value should
be POS settings defined, same for traditional screen.
Further, the discount functionality of the Pos, that was there the first
week i used it, has disappeared!!
rgds Robert

**Comment by nabinhait** [comment]
@robertbecht Sorry for the issue, we will add the discount functionality again in the new POS.

**Comment by nabinhait** [comment]
@robertbecht 
Actually the additional discount feature is available, user has to checked "Apply discount" in the POS profile.

![screen shot 2016-10-22 at 7 00 44 pm](https://cloud.githubusercontent.com/assets/8780500/19619646/1213dca2-988a-11e6-9545-2207925d0d89.png)

**Comment by robertbecht** [comment]
Hi Nabin,,

However what I really would appreciate is that the default account would
come back with automatic filling of the amount...

In the POS changing from CASH to another account goes quite
quick....nevertheless...it takes time..

In the standard Invoice screen it is really a lot of extra work:
Scroll down to Mode of Payment
Add a new line
Add account
and manually type amount or use copy/paste....

Ideally the default account should be users selectable...I tried to set the
default in the Mode-of-Payment table...but failed...and autofilled with
full amount...
Then, under POS profile, the option to define an other default account.....
(so even different profiles can have different default accounts...)

rgds Robert

**Comment by robertbecht** [comment]
No need to....one only has to enable it under the POS profile settings  :)

rgds from Kenya
