### ISSUE TITLE
Item Price not Permitted for Certain Roles

### ISSUE THREAD

**Issue by bohlian** [frappe/erpnext#4528]
Item Price, read permissions should be permitted for Sales Users, Purchase Users and Accounts Users. Without this permission they are unable to create Sales Orders, Purchase Orders, Invoices etc.

**Comment by rmehta** [comment]
I don't think this is needed. Where do you face this problem?

**Comment by bohlian** [comment]
Create a user with only Sales User role. Then try creating a Sales Order that has multiple price lists. the user will see a blank list when trying to select a price list.

**Comment by bohlian** [comment]
Actually after reading your comment I realised that I hit this problem when doing a frappe.call with get_list in a custom script. So its not a problem with the standard program (because I think you retrieve Item Price through a python program which maybe doesn't check for permissions?).

Question: shouldn't Sales Users, Purchase Users and Account Users be able to read Item Price information?
