### ISSUE TITLE
Unread Message Counter

### ISSUE THREAD

**Issue by notagmo** [frappe/erpnext#4529]
The unread message counter in the upper right continues to show notifications even after the actions have been cleared. Is there a way to disable this, or manually clear it?

Thanks!

**Comment by rmehta** [comment]
As of now, notifications get updated every minute or so, not instantly

**Comment by notagmo** [comment]
Rushabh,

Thank you for the reply. However, the notifications are staying for days. 

1) Is there a way to turn the notifications off completely? For my purposes, I don't need them.
2) Is there a way to clear them manually?
3) Is the information that places the notification counter on the task controlled somewhere in SQL? I can access the SQL and am more familiar with SQL than with Frappe and Linux.

Sincerely,
Jason Dreier

www.notagmo.com
301 9th Street, Suite 100
Redlands, CA 92374
Phone: +1 (909) 663-8216

---- On Tue, 22 Dec 2015 23:17:12 -0800 Rushabh Mehta &lt;notifications@github.com&gt; wrote ---- 

As of now, notifications get updated every minute or so, not instantly
