### ISSUE TITLE
Product Bundle Item's SO should make PO for Packed Item and not for Product Bundle Itself

### ISSUE THREAD

**Issue by Devens** [frappe/erpnext#4539]
On suggestion of @rmehta this issue is created here. 

Here are few more suggestions on the same topic. 

While creating PO, it should take care of current stock (Projected Qty) and Reorder Level.

Similar is the case for Manufacturing Item. It can create PO as per Exploded Items in BoM.

At this outset, just wondering, whether separate entity called "Product Bundle" is required? Product Bundle has a similar functionality as (Single level) BoM. I have seen it in some ERP as "Sales BoM" (Or Packing BoM). Moreover, costing related features (Like BoM) are desirable for Product Bundle also. Similarly Product Bundle also may need multiple bom type requirement for larger organization. So, is it not better to keep only one concept type of BOM (and eliminating Product Bundle)?

**Comment by ankush** [comment]
Fixed recently. Product bundle gets unbundled in PO.
