### ISSUE TITLE
Creating variants with Naming Series: Item Code is mandatory because Item is not automatically numbered

### ISSUE THREAD

**Issue by gabtzi** [frappe/erpnext#4543]
Hello,

I'm trying to setup some items in ERPNext but I'd like the item code to be created based on Naming Series for better management. 

In doing so I created the naming series called `SUP-` and the item code `SUP-00003` was automatically created just fine when I created the base/parent item. The bug came when I tried to create a variant for that item for one attribute. When I try to save the item it won't let me save it complaining that 
`Item Code is mandatory because Item is not automatically numbered`

![variants problem](https://cloud.githubusercontent.com/assets/11225818/12003145/a002b972-ab1c-11e5-915f-e3ad317561f1.JPG)

I think that in such cases one of the rest should happen:
1. Use parent Item Code and append the attribute identifier code with value (check below)
2. User parent item code and append a numeric counter
3. Simply increment the parent's Naming Series 
4. At last let the user select an Item Code by himself. 

Regarding 1. 
While creating the item attribute I noticed that there is no field like an Item Attribute Code but only the name exists. In my opinion Item Attributes should also have a unique Item Attribute Code value or Abbreviation to separate them because we might want them to be looking the same but refer to different things. 

For example the sizes in shoes and shirts and jackets and trousers are completely different but we might want their name to appear as just Size and not `Shoe Size`  or `Shirt Size` for example. Imagine the complications if an employee were to mess things up when adding the variant's attribute values because he had to browse through 200 different values. 

I appreciate any input regarding this

EDIT:
This happens when in attribute the "Numeric Values" checkbox is selected.

**Comment by gabtzi** [comment]
For anyone who might face the same issue as me 

In my case and for my needs and inspired by Magento I worked around my issue by altering the code in file: 
`erpnext/stock/doctype/item/item.py`

so that the code I added will handle the creation of the new code by appending to the parent product item code the concatenated attribute values with dashes.
```python
elif frappe.db.get_default("item_naming_by")=="Naming Series" and self.variant_of:
            itemCodeSuffix = ""
            for attribute in self.attributes:
                itemCodeSuffix += "-" + str(attribute.attribute_value)
            self.item_code = str(self.variant_of) + itemCodeSuffix
```

So for product `SERIES-00003`  and for `NumericAttribute1=5`,  `Color=RED` the new item code would be `SERIES-00003-5-RED`

So the file now in line 32 looks like:
```python
	def autoname(self):
		if frappe.db.get_default("item_naming_by")=="Naming Series" and not self.variant_of:
			from frappe.model.naming import make_autoname
			self.item_code = make_autoname(self.naming_series+'.#####')
		elif frappe.db.get_default("item_naming_by")=="Naming Series" and self.variant_of:
			itemCodeSuffix = ""
			for attribute in self.attributes:
				itemCodeSuffix += "-" + str(attribute.attribute_value)
			self.item_code = str(self.variant_of) + itemCodeSuffix
		elif not self.item_code:
			msgprint(_("Item Code is mandatory because Item is not automatically numbered"), raise_exception=1)

		self.name = self.item_code
```

**Comment by rmehta** [comment]
@gabtzi nice. I think the naming by naming series is ignored till now. Can you send a pull request for this? Please use `snake_case` instead of `camelCase` :smile:
