### ISSUE TITLE
Reordering requirement for Production Order (Manufacturing Item)

### ISSUE THREAD

**Issue by Devens** [frappe/erpnext#4545]
We have facility to create Auto Material Request on the basis of Reorder level for Purchase order. Similar facility should be available for Manufacturing Item also.

**Comment by rmehta** [comment]
- [ ] In Production Order, convert Sales Order field to Dynamic Link
- [ ] Add material request type "Manufacture"
- [ ] In Production Planning tool, manufacture from Material Request or Sales Order
- [ ] Update status in Material Request
- [ ] Allow reorder for manufacturing item in `reorder.py`
