### ISSUE TITLE
POS enhancement

### ISSUE THREAD

**Issue by fderyckel** [frappe/erpnext#4551]
Hi all, 
Following this conversation: 
https://discuss.erpnext.com/t/pos-summary-my-user-experience-github-issues/9222

Hi,
I actively use the POS with a wireless barcode scanner.
All works fine :smile: although users wishes many improvements.

They can roughly be defined in 3 sections;
1) Improvement on the current POS screen.
2) More functionality
3) integrations.

An improvement has been made in release 23dec: a percentage can be entered to calculate discount!!

1) Improvement on the current POS screen.
a.Speed. Fast scanning is not possible. See also:

github.com

Issue: POS Module slow

opened by noetico on 2015-12-07
closed by rmehta on 2015-12-08
github.com/frappe/erpnext
The POS module is slow on ERPNext; during v4 it was very snappy and fast; I think it has something to...

b. Space for test under images to small to hold longer text
c.With long sales item list the last entries are off-screen and thus difficult to see whether entered correctly
A scroll bar for the left and the right side of the screen would be nice. Also the last item entered should be always visible, Currently the whole screen jups to the top if one edits an item in the low end of the list
d. The option to also allow non-cash payments (see https://github.com/frappe/erpnext/issues/4516)
2) More functionality
More option to customize POS, like custom fields, info at the right hand side (image, code, Name, description, in stock, .... 
Split tenders: https://github.com/frappe/erpnext/issues/4256//1 there was a discussion here for a paid development.
Other functionality that is usually found in POS ... layaways...

3) integrations.
Integration with payment system, printers, and cash drawers. I understand that important for ,many shops, I am fine with the current system.

I seems that some users are willing to support financially. May be the ERPNext Team can give a rough quote for the various enhancements, and can we raise these funds...

Robert

Hi Robert, 
As mentioned here, POS is definitely lacking behind with hardware integration.

Although there are ways to use POS printer, cash drawer is still an issue. I think the team can test the integration on some standard materials that we can buy (a bit like Shopify)

Thermal printers are still an issues with no easy (out of the box) format for the usual roll size which are standard. The whole pdf - html thing is nor practical or intuitive.

Another issue for us is the barcode scanning of printing label with weight... barcode include items + weight / price

Then there is still this issue I believe... I am not sure it has been addressed.

A very important one for us would also be this one.... Very important considering internet might not always be reliable and we have several shops in various part of the country. Shops need to be able to run despite internet connectivity.

I would be willing to put a $1,000 for the above to be addressed.

**Comment by rmehta** [comment]
@fderyckel thanks! Can you post your bounty to bountysource? https://www.bountysource.com/ Just paste the url of the issue.

Also can you edit your issue into clear actionable points so that it will be easy for anyone to claim the bounty.

**Comment by PawanMeh** [comment]
Please check the following [link](https://discuss.erpnext.com/t/enhancement-pos-redesign/19984), POS has been substantially improved
