### ISSUE TITLE
Latest update error setting po_no as unique in tabSales order

### ISSUE THREAD

**Issue by ekpaxp** [frappe/erpnext#4555]
When updating a deployment, the update throws the following error:-
frappe.exceptions.ValidationError: po_no field cannot be set as unique in tabSales Order, as there are non-unique existing values
The duplicate vaues arose primarily from Sales Orders that were cancelled after first creation so that they could be amended and re-submitted.  Therefore, the same po_no appears in both records.  After manually editing the offending duplicate entries, the update went through.
 
However, apart from dealing with cancelled/amended docs, I am not sure making the po_no unique is a good idea as it assumes that every customer will use a unique numbering system.  For discussion?

**Comment by rmehta** [comment]
@ekpaxp You always allow multiple POs via Selling Settings
