### ISSUE TITLE
Wrong Bank Balance in email Digest

### ISSUE THREAD

**Issue by bennaiqbal** [frappe/erpnext#4559]
ERPNext doesn't show the correct bank balance, when there are two bank accounts, different currencies and when there is negative balance on one of them and positive on the other. It's fully wrong information.

Additionally, there is a delay of more than 20 minutes in emails that are being sent by the system.

**Comment by sagarvora** [comment]
Hi @bennaiqbal,

- The bank balance shown in Email Digest is as on period ending date. (For ex: week end, month end, etc.)
- The negative amounts get reduced from total bank balance.

**Comment by sagarvora** [comment]
This issue regarding incorrect balance in case of multiple currencies is fixed in #9369
