### ISSUE TITLE
Import not working with Microsoft Edge

### ISSUE THREAD

**Issue by cgpurbaugh** [frappe/erpnext#4561]
Attempting to import records does not work in Microsoft Edge.  You can select the file, but you can't upload.

**Comment by yashodhank** [comment]
It is limitation of MS Edge browser itself, not that of ERPNext / Frappe.
Being very new Browser platform by MS, it is not officially supported by ERPNext / Frappe at present.

**Comment by rmehta** [comment]
@yashodhank if its from M$ we will need to support it whether we like it or not

**Comment by cgpurbaugh** [comment]
It's working now.
