### ISSUE TITLE
Multi currency needed for Expenses Claim & Salary

### ISSUE THREAD

**Issue by hhashiesh** [frappe/erpnext#4562]
Dear Sir,

We need Multi currency for Expenses Claim & Salary urgently.

Thanks for your support.

**Comment by rmehta** [comment]
@hhashiesh if you need "urgent" support, you should hire a freelancer.

**Comment by hhashiesh** [comment]
Thanks Mehata and happy new year.

Would you please let me know the idea of this forum, and what is the relation between it and ERPnext ?
What is the differance between the support here and the support from ERPnext team, as I already paid for support with them..
Finally I am not a programer, so will your support need technical people to apply it, or will it be applied automatically as a new update ?

Thanks

**Comment by rmehta** [comment]
@hhashiesh happy new year to you too!

If you have a paid account at erpnext.com, you can email at support@erpnext.com for paid support queries.

FYI, feature requests are not support queries though.

**Comment by hhashiesh** [comment]
I already did few days ago and they replied on some points, and asked me to post here the other points.
That is why I am asking, as I can't understand the procedures, and the differance between the 2 types of support.

**Comment by rmehta** [comment]
@hhashiesh support, by most definitions, is help on existing features.

**Comment by hhashiesh** [comment]
So here I can ask for new features, am I right ?
How much will this cost us ? And the new features will be a new update or will you need a technical people to apply it ?
Sorry for bothering you by many questions, but this is the first time for us to use an open source.

**Comment by rmehta** [comment]
@hhashiesh Yes this is the place for asking new feature requests. For new feature requests the general process is this:

1. How many times this has been asked
2. How critical is it
3. How easy is it to implement it

If you are willing to sponsor and need this urgently, you can easily connect with someone in the community (https://community.erpnext.com/jobs) or (upwork.com) and they can build the feature for you at a cost.

The core team is usually happy to accept well made contributions and they will also be live on the cloud as soon as someone contributes this.

**Comment by jaimeclima** [comment]
Hello!

I have been settling and setting up my account at ERPnext, and just for this problem today. For me it is also very important to have the possibility to choose currency expense by expense.

I don't understand nothing about programming, but once this is a feature is already working on other types of documents (and very well), I think it won't require a major intervention for this. 
@rmehta

Thanks for your support

**Comment by KanchanChauhan** [comment]
@jaimeclima Can you please raise the separate issue for this. I am closing this thread.
