### ISSUE TITLE
Batch ID Naming series

### ISSUE THREAD

**Issue by kunalgoel1** [frappe/erpnext#4567]
Just like how we can select if we want to to have the Item Name by Item code or Naming series in Stock Settings, similarly should also have the same option for Batch ID. Batch ID should also have a automated naming series. It is a generic requirement for many as it will reduce the effort for manual creation of batches.

**Comment by kennethsequeira** [comment]
Available in item master:
![image](https://user-images.githubusercontent.com/33246109/55374285-83820d00-5525-11e9-98c2-34c60559313d.png)
