### ISSUE TITLE
Chart of Accounts - tree listing not working

### ISSUE THREAD

**Issue by phpmathan** [frappe/erpnext#4568]
ERPNext: v6.15.1
Frappe Framework: v6.16.4

In Chart of Accounts page, whatever folder clicked, related top level folder name only requested to the server.

ctype=Account&comp=Quality+Testing+Services&parent=Application+of+Funds+(Assets)+-+QTS&cmd=erpnext.accounts.page.accounts_browser.accounts_browser.get_children

![chart-of-accounts-bug](https://cloud.githubusercontent.com/assets/527140/12080726/3d8e0a10-b28a-11e5-8a4c-b09f7840e2f2.png)

**Comment by nabinhait** [comment]
Can't replicate it. Must be related to your customization.
