### ISSUE TITLE
Filters for Newsletter List

### ISSUE THREAD

**Issue by Devens** [frappe/erpnext#4577]
Newsletter is an excellent tool for Mass Mailing. We suggest that filters should be provided to select right segment for Newsletter List.

**Comment by Devens** [comment]
@rmehta - Any plan for this?

In fact, the database if of no use, if we can't filter them for a particular segment. We can just send Greetings (and at the most very general announcments) to "each and every" customers/suppliers/leads.

**Comment by jwrober** [comment]
This has been handles with groups now.
