### ISSUE TITLE
Material request - Status does not display "Pending" in report filter.

### ISSUE THREAD

**Issue by Devens** [frappe/erpnext#4587]
It is being displayed in List View. But the same is not being displayed in Report Filter for Status.

**Comment by felixvarghese** [comment]
Yes - in the List View, "Status" displays as Pending, Transferred, etc

However, in the Material Request report, Status displays as "Submitted"

The code to do this is seen at https://github.com/frappe/erpnext/blob/develop/erpnext/stock/doctype/material_request/material_request_list.js

As a temporary workaround, use the "% Ordered" column to get a better understanding of this.
