### ISSUE TITLE
"Save As" sub-menu Item in Reports

### ISSUE THREAD

**Issue by Devens** [frappe/erpnext#4593]
"Save As" menu item can be very handy to create another similar report

![image](https://cloud.githubusercontent.com/assets/10671911/12193422/3460a0ec-b60e-11e5-908f-81c836743ebb.png)

**Comment by rmehta** [comment]
Edit report and duplicate?

**Comment by Devens** [comment]
Yes... It was suggested to Edit Report and duplicate the same.
