### ISSUE TITLE
Bug: In sales invoice item, the "tab" character doesn't switch through all fields

### ISSUE THREAD

**Issue by gabtzi** [frappe/erpnext#4594]
Here's a picture of the issue of between which fields I noticed it.

![capture](https://cloud.githubusercontent.com/assets/11225818/12195268/897e4da0-b5fe-11e5-8cab-20433f4b5f5b.JPG)

In my opinion not having to use the mouse to do data entry in an ERP is a must in most business environments and also for sales orders / invoices and most ERPs in the market also strive to do this via "TAB" or "ENTER"  or Arrow keys. Some older ERPs used to use predifined hotkeys for actions. 

Cliking to expand tabs and stuff may be nice visually because it organizes things but forcing the user to use the mouse is something of negative impact.

**Comment by anandpdoshi** [comment]
@gabtzi I think we fixed this on Friday. It will be released tomorrow. Can you check again later?

**Comment by gabtzi** [comment]
Sure, I'll have a look next week.

**Comment by gabtzi** [comment]
Sorry for the delay. I updated today and it's now working.
