### ISSUE TITLE
Some issues in SMS Manager

### ISSUE THREAD

**Issue by MaxMorais** [frappe/erpnext#4610]
Hi guys, I'm seeing some issues, in SMSManager, 
- [ ] Add i18n support in messages
- [ ] Add i18n support in fields-labels and dialog title
- [ ] Move `default_messages` to outside of the function to enable customization

**Comment by rmehta** [comment]
@MaxMorais should be simple fixes for you :)

Or send the traces

**Comment by MaxMorais** [comment]
@rmehta, I'll fix, I open it here for we discuss the points :smile_cat:

**Comment by system19** [comment]
Hi All. I noticed that the ERPNext SMS API only works with http url's but not with https. Does the python httplib, url lib allow for https? If so where would I read up about how to fix/add this feature?

**Comment by rmehta** [comment]
fixed
