### ISSUE TITLE
Addresses not being saved under Sales Partners

### ISSUE THREAD

**Issue by sunrisecomadmin** [frappe/erpnext#4611]
When entering all of our Sales Partners, we have the ability to add an address. We have done this for all of them. When adding the address the default “address type” is billing, which we keep as is. Once we have entered the address and saved, upon going back to that Sales Partner, it shows no addresses associated with them under Sales Partners. The only way to see the address is to go to “addresses” and then you can see who the address is associated with.

**Comment by rmehta** [comment]
Thanks for reporting. This is fixed, for your old sales partners, you will have to update the `sales_partner` property via data import.
