### ISSUE TITLE
Feature Request - BPMN 2.0 Charts

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#4622]
In business we use BPMN (Business Process Model and Notation) to describe processes such as "receiving goods" or "printing an invoice". You can practically describe anything as a BPMN process.

![screencast](https://cloud.githubusercontent.com/assets/9136094/12355793/689fa29a-bb9f-11e5-9ea6-10596dc793e0.gif)

Now there is a project on GitHub https://github.com/bpmn-io/bpmn-js that you can try out live at http://demo.bpmn.io/ that does exactly that and renders the editor in HTML.

@anandpdoshi and @rmehta how could we implement this into ERPNext so we can either add a BPMN model directly within any text box? It would be amazing if we could write text and then insert these BPMN models directly into the text. Another solution would be adding a BPMN field, however this would mean one note or whatever doctype uses it has only one BPMN model rather than having it in text.

This is a super hot thing for any enterprise business, we all use and live BPMN.

**Comment by MaxMorais** [comment]
@dottenbr, BPMN is not only about draw a workflow in the System, it's about a workflow integration

**Comment by dottenbr** [comment]
@MaxMorais it depends what you use it for. Of course you can model workshop processes in it without executing the workflows. That would be a major thing. My idea here is to implement a basic tool that can be used to model workflows or even better to also add flowcharts and organizational charts rather than drawing them and uploading them as an image file.

**Comment by woakes070048** [comment]
@MaxMorais want you working on something like this?

**Comment by MaxMorais** [comment]
@woakes070048 yes.

**Comment by woakes070048** [comment]
@MaxMorais is this the coreflow app or something else. It would be awesome to have something that was similar to cumonuda or activiti. We should talk.

**Comment by MaxMorais** [comment]
@woakes070048 `CoreFlow` is a draft of a Business Rule Engine, for Frappe. It's related with workflows, but it dont use the BPMN patterns, how I told, It's part of a private app, I'll work to share the integration for draw diagrams!

**Comment by woakes070048** [comment]
@MaxMorais awesome I am hoping to do some great things with erpnext and the ecosystem really needs to be enriched. these are some indea's for now

**Comment by MaxMorais** [comment]
@woakes070048 if you are able to conversation ping me on gitter https://gitter.im/frappe/erpnext

**Comment by dottenbr** [comment]
@MaxMorais this is a super feature for us!

**Comment by MaxMorais** [comment]
@dottenbr, give me some days to create it, I'm on Nicaragua now! I'll return to Brazil on the next week, so I can work on this!

**Comment by dottenbr** [comment]
@MaxMorais awesome. Enjoy Nicaragua!

**Comment by CWTGMBH** [comment]
@dottenbr 

Maybe we can help, what was the benefit for you drawing within ERPNext? We use activity for workflows which already come with alfresco, for the connector it works out of the box. Diagrams are normally drawn with a full spec solution like signavio. This diagrams can be overtaken within eclipse to be succeeded within a process engine. When they are just "painted" and don't come with correct -xml schemata I don't see a benefit? 

But if you will sponsor some parts we can go for a full integration together. Signavio come with a powerful REST-Api, for that not so hard to integrate, but take some resources. 

Best

Michael

**Comment by MaxMorais** [comment]
@dottenbr, I'm coding this on the next week! Let's discuss?

**Comment by rmehta** [comment]
@MaxMorais :+1: let me know how its going!

**Comment by MaxMorais** [comment]
@rmehta, I'll discuss with @dottenbr to cover my requirements and him requirements!

**Comment by woakes070048** [comment]
@MaxMorais Hey how is this project coming?

**Comment by MaxMorais** [comment]
@woakes070048, I dont give a answer from @dottenbr, I can share the app, how it is working to me, only with the designer!

**Comment by woakes070048** [comment]
@MaxMorais how does the app work? I would like to see it. thanks

**Comment by MaxMorais** [comment]
@woakes070048 It's just a designer, you write your own BPMN diagrams, and it store in a doctype, that you can link with others!

I'll update the BPMN.io to include new features and I'll share the app here!

**Comment by dottenbr** [comment]
@MaxMorais I am interested in this and also in proper workflows from @CWTGMBH. I think both have their justification for use in ERPNext. @MaxMorais how can I test drive your system?

**Comment by woakes070048** [comment]
@dottenbr i thought @CWTGMBH just allowed for archiving files from erpnext not workflows. I like both solutions but having used activiti in the past and it awesome

**Comment by MaxMorais** [comment]
@dottenbr, @woakes070048 , @CWTGMBH here is the APP https://github.com/mxmo-co/bpmn_editor.git

It is composed of 2 pages, one viewer and one editor, since is impossible to use the viewer and the editor at same page, due namespace conflicts.

The editor stores the diagram in SVG and XML into `BPMN Diagram` doctype.

**Comment by MaxMorais** [comment]
@rmehta, I think it can be closed! the app is already published in github, but has no more updates from @dottenbr  and @woakes070048!

**Comment by Grolaf** [comment]
Hello ! Little UP here, just to know if the bpmn_editor app still works with version 14. 

Because I cannot access the BPMN editor page due to permissions issues ...
