### ISSUE TITLE
Round prices to nearest 0.05

### ISSUE THREAD

**Issue by frehu01** [frappe/erpnext#4623]
In Swiss Francs the lowest coin is a 5 cent piece. So a price like CHF 20.85 is common. A price like 20.86 should be rounded to the nearest 0.05,  i.e. 20.85 and not to the 21.00.

**Comment by anandpdoshi** [comment]
:+1:

**Comment by nabinhait** [comment]
Fixed, sent a PR #4632

**Comment by frehu01** [comment]
Just to be clear: This is not only an issue of the POS module (because you pay by cash). It is also an issue of every summary. (Just mentioning this because @nabinhait s PR-description sais POS.)

**Comment by anandpdoshi** [comment]
Can you specify all the places you know where this change would be helpful?

**Comment by nabinhait** [comment]
@frehu01 I can't imagine any other scenario where this should be applicable.

**Comment by frehu01** [comment]
Well every Order and Quotation would be the scenarios. Independently of the payment mode.
I know it's theoretically possible to pay something like CHF 9.97 via bank transfer in Swiss Francs but you would never see that in Switzerland! You would always round to the next CHF 0.05. The only time you get that is when you're buying from a foreign company.

**Comment by frehu01** [comment]
And of course: Invoices.

**Example**
![img_20160118_211753](https://cloud.githubusercontent.com/assets/15348100/12401887/b9c62040-be29-11e5-8316-074d60a75c37.jpg)
This is a picture of a purchase invoice I got from a delivery company to pay by bank transfer. As you can see the total (Rechnungstotal) is 523.88, the amount to pay (Zahlbetrag) is 523.90.

**Comment by nabinhait** [comment]
Makes sense, will apply same rounding methodology to calculate "Rounded Total" on all related documents.

**Comment by frehu01** [comment]
That would be great! Thanks

**Comment by nabinhait** [comment]
The feature has been released, you have to set "Smallest Currency Fraction Value" in Currency master.

**Comment by frehu01** [comment]
Thanks! It works like a charm, great!
