### ISSUE TITLE
BoM  Button in Item Header

### ISSUE THREAD

**Issue by Devens** [frappe/erpnext#4625]
BoM header in item header to display following. 
1. BoMs for selected item
2. BoMs in which selected item is used as Sub-item.

**Comment by rmehta** [comment]
- [ ] If manufacturing item, add "BOM" in "View"

**Comment by Devens** [comment]
With V7, "Related Documents" Section, this is being taken care of PARTIALLY (i.e. 1st point is taken care of). 

We suggest that from BoM list, it should also display the BoMs in which particular item is sub-item (meaning the item is part of BoM).

In otherwords, when BoM list is opened from an Item, it should have two filter (with OR expression) as under

- Item Name = "Item Code"
- Item Name (BoM Item) = "Item Code"

If required, we can give separate link in "Related Documents Section" for above filter. But, it would be very useful.

**Comment by sharmanakul** [comment]
reference for BOMs created against an items are already provided.

and to see reference of an item being used as raw material in BOM is already mentioned in 
( #6733 ) which will be worked upon in the next month.

So i'm closing this issue.
