### ISSUE TITLE
CC in Emails

### ISSUE THREAD

**Issue by Devens** [frappe/erpnext#4626]
CC should be shown as per regular mail, so that when someone wants to send "reply to all" he can do it. By doing this, other persons in loop also can know about that reply. (If you have some other solution to this issue then also please suggest).

**Comment by dottenbr** [comment]
Absolutely on the same page here. Furthermore there should be an autosuggest for all CC that have been used in the company if you want to add an CC or a TO address. It should lookup in the customer database and in all emails sent and received.

**Comment by Devens** [comment]
I agree @dottenbr for auto-suggest also. It can save plenty of time.

**Comment by dottenbr** [comment]
autosuggest email addresses is really is an issue whenever one writes an email in erpnext

**Comment by DrTrills** [comment]
I'd like to chime in and say it would be great to have ERPNext auto remove the default footer it adds to emails. Makes email communication not so clean in the system.

**Comment by rmehta** [comment]
This is now fixed
