### ISSUE TITLE
Updating translations to German

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#4628]
Since CWT contributed their cleaned up translation from English to German I was wondering how we could update to those translations in DocTypes. For example there is the Chart of Accounts which lists all accounts. Now in the old translation there were some really awkwardly translated accounts like "Gerechtigkeit" which means justice. There are a couple of other locations where there is bad translations that I am now stuck with or that I have to manually alter. How can I update all of this or does that mean I need to start with a clean install?

**Comment by anandpdoshi** [comment]
We are going to release a Country-wise Chart of Account editor just like the translator portal, sometime this month

Best,
Anand Doshi

ERPNext

**Comment by dottenbr** [comment]
That's a great idea. I think it's not just in the financial accounting though but in all demo data. So I am wondering is one could overwrite that. But most of all proper accounting names would be important and having a way to easily update them when you have an instance running already. Will you consider that?

> Am 17.01.2016 um 17:01 schrieb Anand Doshi <notifications@github.com>:
> 
> We are going to release a Country-wise Chart of Account editor just like the translator portal, sometime this month
> 
> Best,
> Anand Doshi
> 
> ERPNext
>

**Comment by anandpdoshi** [comment]
Hi Dominik,

Which demo data are you referring to? Is it the one on demo.erpnext.com?

Best,
Anand Doshi

ERPNext

**Comment by dottenbr** [comment]
Hi @anandpdoshi no I am talking about the data that is in the system if one has installed ERPNext before the translations have been fixed. We have updated to the lastest ERPNext but we still have messy account naming even though it has been translated, there hasnt been a patch.
