### ISSUE TITLE
Display of Suggested Qty in PO Item

### ISSUE THREAD

**Issue by Devens** [frappe/erpnext#4633]
While creating PO, PO item can display a read only field called "Suggested Qty" (= Projected Qty + (Reorder Qty - if  Projected Qty < Reorder Level)

**Comment by rmehta** [comment]
@Devens  can you explain a bit more clearly

**Comment by Devens** [comment]
@rmehta Please see following scenarios in shared file. (Formula is rephrased for more clarity). 

https://docs.google.com/spreadsheets/d/1L3JSFvmdmTOHNgZBvWxsq8ifBia45iB1staf9EQNTmM/edit?usp=sharing

**Comment by Devens** [comment]
@rmehta - alternatively, we can just display actual stock in PO Item. (As With Version 7, "stock level" section in Item Master, it has become very easy to track the stock now). Please suggest whether it's feasible.
