### ISSUE TITLE
Hyperlink from "Assigned To" field

### ISSUE THREAD

**Issue by Devens** [frappe/erpnext#4636]
By clicking on "Assigned To" field, it should open the relevant ToDo.

![screenshot_011916_100804_am](https://cloud.githubusercontent.com/assets/10671911/12409870/8bd1cd5e-be94-11e5-969b-4f019fd31a09.jpg)

**Comment by anandpdoshi** [comment]
@Devens as an immediate workaround, click on the "Assigned To" comment in the timeline to go to the ToDo

**Comment by Devens** [comment]
Ok... Thank you.


Thanking you,

With Regards,
Deven Shah
Safeworld Systems Pvt Ltd
M - 09825060116

**Comment by Devens** [comment]
@anandpdoshi - With new release hyperlink is not available from timeline also.

**Comment by anandpdoshi** [comment]
Will release a fix this week
