### ISSUE TITLE
Reports for Stock

### ISSUE THREAD

**Issue by Devens** [frappe/erpnext#4647]
Stock Balance: Missing Features 

1   Customizable through report Builder
2   Filter for BoM (Main Item & Sub-items)
3   Filter by "Is Asset Item" (Providing "Is Asset Item" in Pick Columns list can serve the purpose)
4   Print with Filter selection (Filter selection does not stay when we give print command)
5   Filter by multiple value for a field
6.     Rearranging/removing/adding columns. 
7.     Totaling in filtered result

(Actually, Point No 1 will resolve most of the remaining points).

**Comment by rmehta** [comment]
This is now fixed via https://github.com/frappe/frappe/pull/7251
