### ISSUE TITLE
Uploading private attachment doesnt work

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#4657]
When I upload a private attachment it shows but is not accessible. What does private mean anyway? Shouldnt it be that any upload is private for thee whole company and a user should make a conscous decision to upload something public? Or does private mean that only that specific user can access?

![upload](https://cloud.githubusercontent.com/assets/9136094/12447473/ad0c8144-bf70-11e5-9362-9df4a11bc0c1.png)

![404](https://cloud.githubusercontent.com/assets/9136094/12447475/b12314be-bf70-11e5-8178-4226d1b0cd52.png)

**Comment by anandpdoshi** [comment]
Private means you need to be logged in and must've read permission on the document to which the file is attached

**Comment by dottenbr** [comment]
OK thanks for clarifying @anandpdoshi. Then I believe private should be enforced, otherwise its a possible security breach. However it doesnt work on my setup, I dont know why.

**Comment by anandpdoshi** [comment]
Run
bench setup nginx
sudo service nginx reload

**Comment by dottenbr** [comment]
su frappe rather than root?

**Comment by anandpdoshi** [comment]
All bench commands to be run using frappe user

Sudo commands can be root user if you don't have frappe user password

**Comment by dottenbr** [comment]
Thank you @anandpdoshi

**Comment by adgency** [comment]
I have the same problem,
I am loged in
I created the document (for example Sales Invoice)
I add the attachment and keep the Private check box on
and then I can't access the file (I get the 404 error)
the file path is "https://my_erp_url/private/files/myfile.png
But strangely I can delete the file. 
ERPNext: v6.21.5
Frappe Framework: v6.22.6

what needs to be modified in the nginx conf for the attachments to work properly?

Thank you

**Comment by anandpdoshi** [comment]
Run bench setup nginx, service nginx reload and it should start working.
