### ISSUE TITLE
Cannot Undo Journal Entry in Bank Recon

### ISSUE THREAD

**Issue by ccfiel** [frappe/erpnext#4661]
Hello @anandpdoshi @nabinhait 

I want to submit a PR for this if the logic is acceptable in ERPNext.

The problem now in ERPNext is you cannot Undo a record in bank recon. Even you edit the clearance date.

My propose solution allow to set clearance date to blank again (None) the record will be back to unreconcilled state.

or is there a better way to undo reconciled journal entry

What do you think?

**Comment by ccfiel** [comment]
made a PR https://github.com/frappe/erpnext/pull/4662

any comments? :)

**Comment by ccfiel** [comment]
thanks! its now merge in dev.

**Comment by nabinhait** [comment]
Thanks for the PR
