### ISSUE TITLE
Designation is not updated on Salary Slip

### ISSUE THREAD

**Issue by towkir** [frappe/erpnext#4666]
I created an employee, with a designation of Executive.
Then I created a Salary Slip for him. the slip shows his designation as Executive which is correct.

Now I updated his designation from employee form. and made it "Manager"
Then I again created a Salary Slip for him which still shows his designation "Executive" on Salary Slip which is not correct.

I am not an advanced programmer or python coder.
How can I fix this ? Is this a real bug ? or am I misunderstanding something ?

Thanks in Advance

**Comment by rmehta** [comment]
@towkir it should not change in existing salary slips.
