### ISSUE TITLE
Filters for Sales Order Calendar

### ISSUE THREAD

**Issue by Devens** [frappe/erpnext#4668]
Please see following screen. Need to provide Filter for Status (or if "Add Filter" button can be provided, it can be the best)

![unnamed](https://cloud.githubusercontent.com/assets/10671911/12481691/cc5e607a-c070-11e5-9e7f-e8c53d0d5365.png)

**Comment by rmehta** [comment]
Not possible, what are you missing?

**Comment by Devens** [comment]
@rmehta - We had found round about solution for our previous requirement. 

But, here, if you can provide selection (filter) for Company, it can be further helpful.

**Comment by rmehta** [comment]
This is now coming in 7.3 with Kanban
