### ISSUE TITLE
Sending reports by email at a frequent (predefined) interval

### ISSUE THREAD

**Issue by Devens** [frappe/erpnext#4671]
In absence of Dash-Board, this can be very handy. 

- It will be very useful tool for receiving automated MIS at various levels. 
- Certain reports can be sent to selected customers (already requested to filter for Newsletter List) like list of non moving stock to potential customers. 
- Circulating revised price-lists
- So on...

### This can be achieved by following two options

**Email Alert**
- Giving selection of "Report" in "Email Alert" to send along with alert as an attachment
- Frequency Selection (When to send - Weekly/monthly/quarterly)

**Report (Doctype)**
- Providing Fields for "Whom to send"
- Frequency Selection
- Message Text Field

**Comment by VivekC-ICP** [comment]
Yes I agree totally!  This will be a very useful feature.

**Comment by Devens** [comment]
Hello... Any feedback on this?

**Comment by shafbachu** [comment]
Hi Guys, do we have any updates on this? I think this is such an essential facility especially for accounting purposes to send to debtors on a periodic time.

**Comment by rmehta** [comment]
- [ ] Email Report
  - Select Report
  - Select Frequency (daily, weekly - day of week, monthly)
  - Email list
  - Format (HTML, CSV, XLS)
  - Max rows
- [ ] Add scheduler event
  - Run report
  - Send email
- [ ] Restrict # of reports to # of users?
