### ISSUE TITLE
new sales invoice

### ISSUE THREAD

**Issue by farhanayyaz1** [frappe/erpnext#4672]
some issue in item not working.

**Comment by anandpdoshi** [comment]
We are very sorry for the problem. We just pushed a fix. Can you refresh and try again?

**Comment by farhanayyaz1** [comment]
Thank You Anand.


First Moon Electronics Trading.

SHIPPING
MARK:  MFB

TEL:00971-4-2284525

FAX: 00971-4-2242179

Mobile
Dubai: 00971-52-9291514

P.O.BOX: 86527,DUBAI-UAE

Address: SH#47,Baglaf
Bldg,Nakheel Road,Dubai-UAE

Date: Thu, 21 Jan 2016 08:04:01 -0800
