### ISSUE TITLE
Email configuration and alerts.

### ISSUE THREAD

**Issue by rainersg** [frappe/erpnext#4675]
Hi all,

The email account configuration is for only one account? What about other users? Right now, I set up email account for system administrator only, and I wanted to set the accounts for users too. When I allowed the user's access to the Gmail and saved it, it seems that the address was changed from the administrator to the intended address. How will I set so that all the users can allow access to their individual Gmail?

What is the ideal setting for the Email By Document field in the Email Alert? I have followed the guide found but I am not sure about the field? I want to create some email notifications for Task created, Task due date update, Task description update and Comments. How will I go about this? And does the syntax for the Message fields start with {{ doc.XXXX }} where the XXXX represents the name for the fields?

Here I have attached the screenshots. Really appreciate help on this

![screen shot 2016-01-22 at 11 17 24 am](https://cloud.githubusercontent.com/assets/16292330/12501577/c6f80cc4-c0f9-11e5-98ee-92cb6f243db1.png)

**Comment by rmehta** [comment]
@rainersg  please post help queries on https://discuss.erpnext.com.
