### ISSUE TITLE
Reports - Group by and Sub-Totals/Totals

### ISSUE THREAD

**Issue by vivekck** [frappe/erpnext#4678]
A very useful option in Reports will be to have an option to choose a field(s) for "Group by", so the numerical value columns get totaled based on the Group, i.e., sub-totals.  

For e.g., Invoice Total with Group by a certain column, let’s say “Item group” or “Customer name", etc., this is just an e.g., we have many more such cases!  

I am sure this would be an useful feature to many, we can go to Excel/Spreadsheets for any additional dimensions of the report, however group-by I feel will make it easy to have it in the report builder itself. 

Let me know whether we can sponsor this feature?

Cheers!

**Comment by Devens** [comment]
I agree. This is something very important and basic, which is unfortunately missing in ERPNext.

**Comment by aakvatech** [comment]
Isn't this already done? Can somebody mark it closed?
