### ISSUE TITLE
Review of the installation instruction

### ISSUE THREAD

**Issue by jordsti** [frappe/erpnext#4679]
The installation instruction seems deprecated, there's even some command for bench that doesn't exsists anymore in bench like install-app. You should redo the instruction, beacause it just doesn't works when you follow it. It works until the get-app and install-app.

**Comment by rmehta** [comment]
@jordsti which page?

**Comment by jordsti** [comment]
frappe/bench README.md,

Setting Up ERPNext Section,

Install-app command doesn't even exists anymore.

**Comment by rmehta** [comment]
What are you trying? It does exist. Try `bench --help`. Can you post details on discuss.erpnext.com

**Comment by jordsti** [comment]
I tried to see the help entry in bench --help, install-app is not in the list.

I just followed the entire setup walkthough and at the step, I just saw a full stack of python exception.

**Comment by pdvyas** [comment]
@jordsti Were you able to `bench init`? `install-app` is a framework command which appears when you're in a bench dir. Try,
```
cd ~
bench init frappe-bench
cd frappe-bench
bench --help | grep install-app
```
