### ISSUE TITLE
Website Redesign

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#4690]
The website needs to be "designed". Right now, its just a bunch of simple pages without much thought of standardization or consistency or aesthetics. There needs to be
1. Better Typography
2. Consistent layouts

I think we should go for one classical layout and let users play within that layout, like Medium. We are past the age of fancy layouts and letting users too much freedom is also not good.

Here are the different Elements
# Navbar

Navbar must have 4-5 menus and a place for logos. Logos can be very different
#### Example 1:

![screen shot 2016-01-26 at 1 41 31 pm](https://cloud.githubusercontent.com/assets/140076/12575888/26c0eb82-c436-11e5-9bb4-b2b36ae6af46.png)
#### Example 2:

![screen shot 2016-01-26 at 11 33 44 am](https://cloud.githubusercontent.com/assets/140076/12575890/2a0c4570-c436-11e5-9598-d4822b93582d.png)
#### Example 3:

![screen shot 2016-01-26 at 11 33 17 am](https://cloud.githubusercontent.com/assets/140076/12575899/347c4a5a-c436-11e5-8d17-a9f6ea56955b.png)
#### Example 4: With Dropdown

![screen shot 2016-01-26 at 1 45 15 pm](https://cloud.githubusercontent.com/assets/140076/12575938/6db10dec-c436-11e5-82f3-69a5c298965a.png)
#### Example 5: "My Profile / Account" Link

![screen shot 2016-01-26 at 1 44 31 pm](https://cloud.githubusercontent.com/assets/140076/12575944/7a6abe52-c436-11e5-8f1f-17fa33c3bd5e.png)
# Home Page

Home page must be completely re-designed.
### Current Design

![screen shot 2016-01-26 at 1 44 14 pm](https://cloud.githubusercontent.com/assets/140076/12575931/633696ca-c436-11e5-9e49-f8247443d978.png)

Ideally, There should be one headline, one sub-headline and one image

And a bunch of featured products
### Inspiration

Publication page on Medium

![screen shot 2016-01-26 at 2 04 45 pm](https://cloud.githubusercontent.com/assets/140076/12575995/c5d4bbf4-c436-11e5-9e95-b39925db1c02.png)

![screen shot 2016-01-26 at 2 03 00 pm](https://cloud.githubusercontent.com/assets/140076/12576006/d5c56716-c436-11e5-91cc-020fc05d0d71.png)
# Login

![screen shot 2016-01-26 at 1 44 47 pm](https://cloud.githubusercontent.com/assets/140076/12576026/ec4f1342-c436-11e5-9186-d25500ad3678.png)
# Footer

Standardized footer to contain footer nav, copyright notice and sign-up for newsletter features

![screen shot 2016-01-26 at 1 45 00 pm](https://cloud.githubusercontent.com/assets/140076/12576037/faa8c884-c436-11e5-8cc9-6c45157938db.png)
# Blog Home

![screen shot 2016-01-26 at 1 45 48 pm](https://cloud.githubusercontent.com/assets/140076/12576045/0916e39c-c437-11e5-9f0c-97f604dbb613.png)
# Blog Post

![screen shot 2016-01-26 at 1 45 56 pm](https://cloud.githubusercontent.com/assets/140076/12576052/0dd12c30-c437-11e5-8b1b-7b6b08bc8bed.png)
# Product List

Maybe a title?

![screen shot 2016-01-26 at 1 46 08 pm](https://cloud.githubusercontent.com/assets/140076/12576059/20a7d62e-c437-11e5-85bb-428dc3ddd914.png)
# Product Page

![screen shot 2016-01-26 at 1 46 14 pm](https://cloud.githubusercontent.com/assets/140076/12576065/2b47c904-c437-11e5-80a3-0e94c389cdf1.png)
# My Account / Home

![screen shot 2016-01-26 at 1 46 24 pm](https://cloud.githubusercontent.com/assets/140076/12576072/32182b34-c437-11e5-9cd2-861248c4c586.png)
# Listing Pages
#### Order List

![screen shot 2016-01-26 at 1 46 36 pm](https://cloud.githubusercontent.com/assets/140076/12576080/3caceeae-c437-11e5-9957-6e0b9c580af2.png)
#### Issue List

![screen shot 2016-01-26 at 1 47 00 pm](https://cloud.githubusercontent.com/assets/140076/12576083/4548b840-c437-11e5-8902-4db5a451332f.png)
# Order Page / Shopping Cart

![screen shot 2016-01-26 at 1 46 44 pm](https://cloud.githubusercontent.com/assets/140076/12576108/646752c2-c437-11e5-8805-be1e295e3463.png)
# Web Form

![screen shot 2016-01-26 at 1 47 07 pm](https://cloud.githubusercontent.com/assets/140076/12576096/56b5620e-c437-11e5-949a-61c94d3c01cc.png)

**Comment by Devens** [comment]
I agree.

**Comment by mhbu50** [comment]
+1
