### ISSUE TITLE
Holiday Request

### ISSUE THREAD

**Issue by CWTGMBH** [frappe/erpnext#4702]
A Holiday Request don´t consider existing Holiday Lists.

EG
Public Holiday on 15th August in Germany. Recorded in an Holiday List. When employee open new task for holiday from 14th August till 16th August, it should only subtract 2 Days from individual Holiday. For now it removes three days.

**Comment by anandpdoshi** [comment]
I think there is a checkbox in HR Settings to disable this behaviour. Can you check?
