### ISSUE TITLE
[Feature Request] Allow editing of visible columns on child tables

### ISSUE THREAD

**Issue by Barbariandude** [frappe/erpnext#4708]
On child tables of forms such as Material Request and Purchase Order, the child tables (items) have hardcoded columns. I would greatly appreciate being able to add arbitrary columns to it.

For example, I have a field added to the Material Request Item doctype called "Local or Overseas", which is of type Select and has "Overseas" and "Local" as options. I would like to add it to the child table in the Material Request form.

Thank you.

**Comment by jwrober** [comment]
This is available with customize form in setup.
