### ISSUE TITLE
Incorrect quanitity discounts

### ISSUE THREAD

**Issue by graphskill** [frappe/erpnext#4709]
When creating the quote / order we add a quantity and the discount is applied. If you then manually change the quantity the discount is not recalculated.

So, 1 item added to the cart - no discount

![quantity 1 no discount](https://cloud.githubusercontent.com/assets/925619/12685895/ad106336-c6be-11e5-92c5-d453164da2a3.jpg)

Quantity changed to 100 and the 20% discount is applied

![quantity 100 discount applied](https://cloud.githubusercontent.com/assets/925619/12685905/b442b6f4-c6be-11e5-8fd2-564889f7f948.jpg)

quantity 100 discount applied.jpg965x467 35.6 KB
Quantity changed to 10 and the discount is not removed

![quanity 10 discount not removed](https://cloud.githubusercontent.com/assets/925619/12685912/b9e55a3a-c6be-11e5-88c1-ae9158151993.jpg)

**Comment by manassolanki** [comment]
@graphskill This is working properly in my system. You can view it in the attached link
http://imgur.com/a/3E98t

If the problem still persist, you can provide me the additional details to replicate this in my system.

**Comment by graphskill** [comment]
@manassolanki I raised this issue a long time ago. But it does work now so all is well and this can be closed
