### ISSUE TITLE
Issues at login

### ISSUE THREAD

**Issue by fderyckel** [frappe/erpnext#4717]
After a bench update last night, I am not able to login to the desk anymore.  I am automatically redirected to the website with this error:

> Traceback (innermost last):
>   File "/home/franky1/frappe-bench/apps/frappe/frappe/app.py", line 81, in application
>     response = frappe.website.render.render(request.path)
>   File "/home/franky1/frappe-bench/apps/frappe/frappe/website/render.py", line 55, in render
>     data = render_page(path)
>   File "/home/franky1/frappe-bench/apps/frappe/frappe/website/render.py", line 107, in render_page
>     return build(path)
>   File "/home/franky1/frappe-bench/apps/frappe/frappe/website/render.py", line 114, in build
>     return build_page(path)
>   File "/home/franky1/frappe-bench/apps/frappe/frappe/website/render.py", line 127, in build_page
>     context = get_context(path)
>   File "/home/franky1/frappe-bench/apps/frappe/frappe/website/context.py", line 16, in get_context
>     context = build_context(context)
>   File "/home/franky1/frappe-bench/apps/frappe/frappe/website/context.py", line 54, in build_context
>     ret = module.get_context(context)
>   File "/home/franky1/frappe-bench/apps/frappe/frappe/templates/pages/error.py", line 11, in get_context
>     print frappe.get_traceback()
>  IOError: [Errno 32] Broken pipe
> 

All I can do is to logout.

**Comment by anandpdoshi** [comment]
Can you do bench update again and check if you get any error?

**Comment by fderyckel** [comment]
No change.  
The website works when I try "contact us", "blog", "Product".  I get the error when I click "switch to desk".

> franky1@erpnextTesting:~$ bench update
> INFO:bench.utils:setting up sudoers
> Already up-to-date.
> Requirement already satisfied (use --upgrade to upgrade): Pillow in ./env/lib/python2.7/site-packages
> INFO:bench.app:pulling frappe
> From https://github.com/frappe/frappe
>  * branch            develop    -> FETCH_HEAD
> Already up-to-date.
> INFO:bench.app:pulling erpnext
> From https://github.com/frappe/erpnext
>  * branch            develop    -> FETCH_HEAD
> Already up-to-date.
> INFO:bench.app:pulling jasper_erpnext_report
> From https://github.com/saguas/jasper_erpnext_report
>  * branch            master     -> FETCH_HEAD
> Already up-to-date.
> /home/franky1/frappe-bench/env/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
>   SNIMissingWarning
> /home/franky1/frappe-bench/env/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
>   InsecurePlatformWarning
> Requirement already up-to-date: pip in ./env/lib/python2.7/site-packages
> Migrating site1.local
> Updating frappe                     : [========================================]
> Updating erpnext                    : [========================================]
> Updating jasper_erpnext_report      : [========================================]
> Wrote ./assets/js/jasper_erpnext_report.js - 166k
> Wrote ./assets/js/print_format_v3.min.js - 18k
> Wrote ./assets/js/frappe-web.min.js - 100k
> Wrote ./assets/css/jasper_erpnext_report.css - 27k
> Wrote ./assets/js/form.min.js - 107k
> Wrote ./assets/js/report.min.js - 155k
> Wrote ./assets/js/erpnext.min.js - 35k
> Wrote ./assets/css/list.min.css - 6k
> Wrote ./assets/js/erpnext-web.min.js - 1k
> Wrote ./assets/css/report.min.css - 7k
> Wrote ./assets/css/frappe-web.css - 51k
> Wrote ./assets/js/list.min.js - 65k
> Wrote ./assets/js/dialog.min.js - 58k
> Wrote ./assets/js/desk.min.js - 869k
> Wrote ./assets/css/form.min.css - 2k
> Wrote ./assets/js/editor.min.js - 26k
> Wrote ./assets/css/erpnext.css - 1k
> Wrote ./assets/css/desk.min.css - 256k
> Wrote ./assets/js/module.min.js - 5k
> Wrote ./assets/css/module.min.css - 1k
> ________________________________________________________________________________
> Bench: Open source installer + admin for Frappe and ERPNext (https://erpnext.com)
> 
> franky1@erpnextTesting:~$

**Comment by fderyckel** [comment]
Also very strange, is that I update both my testing site and my production site and both are in develop branch.  But in this testing site, it got the new functionality with attendance, but not into production site.  very strange.

**Comment by fderyckel** [comment]
BTW Thanks so much for responding so quickly.

**Comment by anandpdoshi** [comment]
Try running

bench --site all clear-cache

**Comment by fderyckel** [comment]
No change...

**Comment by rmehta** [comment]
@fderyckel hope this is fixed now.
