### ISSUE TITLE
Assigning Numbers to Employees

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#4727]
We have employee numbers such as "043" which is my number or "104" which is somebody in our romanian facility. I strongly believe we whould be able to give each employee a number manually when adding them. If no number is given we can autoassign. I am OK with the EMP/... notation we will just ignore the EMP for ourselves.

Please assign to @emakis

**Comment by vrms** [comment]
not sure why this is an issue (in the logic of ERPNext). 
As I understand that matter so far (following since about a month) you'd just add a field from inside the GUI (add a custom field and Customize Form). So if anyone could explain what is the difference I'll help my understanding.

**Comment by dottenbr** [comment]
@vrms most companies use employee numbers for various things like vending machines, time logging with punch cards or electronic systems etc. So these employees have a number. Of course we could do this it ha custom field but why do so if when creating the employee it would be possible to assign a number right away? I am not a big fan of duplicate and conflicting information if it can be applied in a way that would be useful for most ERPNext users.

**Comment by dottenbr** [comment]
@rmehta do you want to chip in and choose if this is something for everybody and if so assign it to @emakis?

**Comment by rmehta** [comment]
@dottenbr do you want to go with custom field for now? This does not seem such a common request.

**Comment by vrms** [comment]
I agree with @dottenbr actually we have the same situation in our company. Still trying to understand the mechanics of how everything works in the ERPNext universe. Wouldn't it be an approach to make a custom field (which once you do it right results into a custom app if I am not mistaken) and then make this app (called "Employee Number" or so) publicly available in some way?
In case I am besides the point and standard procedures please don't hesitate to let me know. I'd be really keen on finding out how these are.

**Comment by anandpdoshi** [comment]
Hi Dominik,

You can go to HR Settings and change Employee Naming by from Naming Series to Employee Number. Then specify whatever Employee Number that you want.


Best,
Anand Doshi

ERPNext

**Comment by dottenbr** [comment]
Awesome! Thank you!

**Comment by vrms** [comment]
@anandpdoshi would that really allow employee numbers as you want? I'd expect it to work as Invoice number (able to define a starting point from where the system starts counting but without the option to freely define any value.

**Comment by anandpdoshi** [comment]
that's how the default Naming Series option works

**Comment by vrms** [comment]
so, then @dottenbr can not use whatever Employee numbers he already has, right?

**Comment by anandpdoshi** [comment]
Yes

**Comment by dottenbr** [comment]
I switched to numbers which allows me assigning any number I have. I have to manually do the work but that's exactly what I wanted. 

The auto naming series is good for most people but number did the trick for us. 

Sent from my mobile

> Am 05.02.2016 um 03:42 schrieb Anand Doshi <notifications@github.com>:
> 
> Yes 
> 
> Sent from my phone
>

**Comment by vrms** [comment]
@dottenbr 
> I switched to numbers which allows me assigning any number I have
can you elaborate how you achieved that. If you added a custom field as per my understanding that ideally (if you do not want that to be overwritten by any update) that is being added as a new app. If that's what you did, can you point me to it? There seems noting to exist in our github.
