### ISSUE TITLE
Quality Inspection

### ISSUE THREAD

**Issue by ftorreti** [frappe/erpnext#4734]
In quality inspection it is possible to select a batch number associated to an item and select a different item in the inspection and still submit the report correctly.

For example:

QI document created for item 123 and in the batch number field you can select any batch numbers.

Recommend to implement a filter only for batch number that match the item selected in the QI document during creation.

**Comment by sbkolate** [comment]
did you submit PR before quality inspection?

**Comment by nabinhait** [comment]
Fixed it, will be released next week.
