### ISSUE TITLE
Shipping Rule by Volume/weight of shipment. 

### ISSUE THREAD

**Issue by Devens** [frappe/erpnext#4736]
Generally shipping rates are based on Volume or weight (and not on the basis of rates). There should be provision to define shipping rules based on Volume/weight also.

**Comment by fderyckel** [comment]
Quite a few threads were already done on this (here and on the forum)
https://github.com/frappe/erpnext/issues/3740

**Comment by gmplab** [comment]
related to #3740
so close this issue.
