### ISSUE TITLE
Column for Total (amount) in Stock Reconciliation Item table

### ISSUE THREAD

**Issue by Devens** [frappe/erpnext#4738]
When we update stock for multiple (many) items, it is very important to know that which item is contributing more to "Difference Amount". We suggest to have Total amount column similar to almost all child tables (like SO, PO, et al). 

Alternatively, Formula field type also can be added (so that it can be customized without use of any code). You may also suggest if any simple alternative method.

**Comment by rmehta** [comment]
:+1:

**Comment by nabinhait** [comment]
Add columns in both Item and parent table:

- Difference Qty
- New Amount
- Existing Amount
- Difference Amount

**Comment by KanchanChauhan** [comment]
Fixed via https://github.com/frappe/erpnext/pull/6462
