### ISSUE TITLE
Critical - Sales invoice notification and not permitted popup error after setting "Read Permission" for Account User

### ISSUE THREAD

**Issue by noetico** [frappe/erpnext#4745]
Hello Sirs; we have a small issue; we want to prevent cashiers from viewing sales invoices when they click the Sales Invoice link above; this is for security. Under Permissions; we have unchecked "Read" for the Account user role and yes it works; they can no longer view sales invoice list but there is a problem now; the POS module keeps randomly popping up "Not Permitted" and "Notifications for sales Invoice not permitted"; its random and erratic; closing the pop up doesnt stop the sale; but scanning or searching or starting a new sale could keep these pop ups coming on and on. I think once this permission is unchecked; the Account user role should only get this "not permitted" notification when trying to access the sales invoice list not during the sale. We would appreciate getting some information on how to remove this from the POS module code.
![screen shot 2016-02-04 at 11 41 20 pm](https://cloud.githubusercontent.com/assets/15412145/12832217/f1f4f532-cb98-11e5-9fb7-3860a9239b24.png)
![screen shot 2016-02-04 at 11 41 24 pm](https://cloud.githubusercontent.com/assets/15412145/12832218/f1fb9b4e-cb98-11e5-924a-ebc381abfe34.png)
![screen shot 2016-02-04 at 11 41 30 pm](https://cloud.githubusercontent.com/assets/15412145/12832219/f2082c6a-cb98-11e5-8907-e059a15c572f.png)
![screen shot 2016-02-04 at 11 41 47 pm](https://cloud.githubusercontent.com/assets/15412145/12832220/f210a8f4-cb98-11e5-8e17-939bec3924ea.png)

**Comment by yashodhank** [comment]
@noetico have you tried by creating new role and assigning permission to the sales users?
Read permission is required for various reason in general.

**Comment by rmehta** [comment]
The POS design has been changed also the message is more specific now. Please re-open this issue if it happens again.
