### ISSUE TITLE
Print margins of HTML preview and PDF significantly different

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#4753]
The print margins on the HTML preview look very nice, however when saving it as a PDF it messes it up. could you resolve this to ensure it is consistent?

Preview HTML
<img width="861" alt="bildschirmfoto 2016-02-07 um 18 46 36" src="https://cloud.githubusercontent.com/assets/9136094/12873990/5bbb63c8-cdcb-11e5-8332-7fafd7f6b39d.png">

PDF
<img width="920" alt="bildschirmfoto 2016-02-07 um 18 46 45" src="https://cloud.githubusercontent.com/assets/9136094/12873995/732da58e-cdcb-11e5-83a9-de61b7579631.png">

**Comment by dottenbr** [comment]
Instead of doing the spacing with <br/> which I did first I now assigned padding-top and padding-bottom which seems to show consistent behavior. Somehow the <br> showed in HTML but got ignored int the PDF?

**Comment by dottenbr** [comment]
Unfortunately I have to report that the paddings are still significantly larger in HTML than in PDF :-(

**Comment by qrevel** [comment]
I have the same issue on Quotation PDF.

**Comment by dottenbr** [comment]
This is still not resolved and is now discussed here https://github.com/frappe/erpnext/issues/8108 so I will close this issue
