### ISSUE TITLE
Disable "In Words" for Grand Total

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#4754]
The "In Words" like "EUR Three Thousand, Six Hundred only." for "€ 3.599,75" is a cool feature but I have never seen this used in Germany. We would need to be able to turn this off like "Disable Rounded Total" function in Setup -> Global Defaults.

**Comment by anandpdoshi** [comment]
You can hide In Words field for now.

Best,
Anand Doshi

ERPNext

**Comment by dottenbr** [comment]
Can you assign this to Makis and have him fix it? It's quite similar to the
rounded values configuration he should fix it for everyone.

Am Montag, 8. Februar 2016 schrieb Anand Doshi :

> You can hide In Words field for now.
>
> Best,
> Anand Doshi
>
> ERPNext
>
> > On 07-Feb-2016, at 11:22 PM, Dominik <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > The "In Words" like "EUR Three Thousand, Six Hundred only." for "€
> 3.599,75" is a cool feature but I have never seen this used in Germany. We
> would need to be able to turn this off like "Disable Rounded Total"
> function in Setup -> Global Defaults.
> >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/frappe/erpnext/issues/4754>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/frappe/erpnext/issues/4754#issuecomment-181205037>.
>


-- 

Mit freundlichen Grüßen / All Best,

*Dominik Ottenbreit*
Geschäftsführer ESO Germany
Director of Business Development

Tel.: ​+49 6752 9112-55
Mobil: ​+49 160 90813466
Fax: ​+49 6752 1524998

www.eso-electronic.com

ESO Electronic Service Ottenbreit GmbH
Hahnenbachstr. 21
55606 Hahnenbach, Germany

Geschaeftsfuehrer (CEO and President): Dominik Ottenbreit
Prokurist (Authorized Signatory):Bjoern Ottenbreit
Gerichtsstand (Jurisdiction): Bad Kreuznach, Germany (HRB 3460)
USt-IdNr. (Tax ID): DE 812 004 832
NCAGE: CH591, DUNS: 314797515, WEEE-Reg-Nr.: DE 84 800 814

**Comment by anandpdoshi** [comment]
@dottenbr makis can send a pull request

**Comment by dottenbr** [comment]
@emakis please work on this

**Comment by emakis** [comment]
Whick DocType has "In Words" field?

**Comment by nabinhait** [comment]
Quotation, Sales Order, Delivery Note, Sales Invoice, Supplier Quotation, Purchase Order, Purchase Receipt, Purchase Invoice.

**Comment by emakis** [comment]
@anandpdoshi 
While committing it throws bellow error
`remote: Permission to frappe/erpnext.git denied to emakis.
fatal: unable to access 'https://github.com/frappe/erpnext/': The requested URL returned error: 403`

I just hidden the in_words field of the doctypes @nabinhait mentioned

**Comment by anandpdoshi** [comment]
use `frappe` user on your server and not `root` user

**Comment by emakis** [comment]
Waiting @anandpdoshi  to merge my first pull request
