### ISSUE TITLE
Letter Heads for Companies

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#4755]
We have multiple companies that are separate legal entities. We would love it if we could create letter heads that are automatically chosen when creating for example a quote from our company A located in Romania than if we create a quite from our company B located in Germany. They have different addresses and contact information.

**Comment by sbkolate** [comment]
@dottenbr  `Default Letter Head` is present in Company form.
You can create different letter head for different company and then select default letter head in company setting.

let me know, if it works for you.
