### ISSUE TITLE
Adding Text Alignment and Border thickness to Print Settings for Print Heading

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#4756]
I would like to propose Setup -> Print Settings to get an addition to configure the border thickness and the alignment of the title such as "QUOTATION" to be left, center or right.

I find print-heading aligned left and a border of 1px much better for my company's design.

Default:
<img width="840" alt="bildschirmfoto 2016-02-07 um 19 30 16" src="https://cloud.githubusercontent.com/assets/9136094/12874295/7f20404e-cdd1-11e5-8143-0dbe15a4854b.png">

My preference:
<img width="838" alt="bildschirmfoto 2016-02-07 um 19 31 04" src="https://cloud.githubusercontent.com/assets/9136094/12874297/8605d108-cdd1-11e5-9e85-95be7390c753.png">

**Comment by rmehta** [comment]
@dottenbr you can customize the print format using print format builder

**Comment by bghayad** [comment]
@rmehta do u mean to use the custom format and write html and custom css?

**Comment by rmehta** [comment]
@bghayad no you can just edit the "heading" section in customize print format

**Comment by bghayad** [comment]
@rmehta 
Thanks a lot. 
In case I need to have table that contains the titles and the values of the fields, what is the solution to do this?
Regards
Bilal
