### ISSUE TITLE
Spacing issue in Quotation

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#4757]
Check this out, this is default ERPNext. The red space is awkwardly big while the green space is awkwardly small. I suggest both being the same somewhat in the middle.

Maybe this is also an issue in other documents and could be resolved for all.

<img width="1119" alt="spacing issue" src="https://cloud.githubusercontent.com/assets/9136094/12874329/4aeb3350-cdd2-11e5-8f97-fe07bea7bb35.png">

**Comment by dottenbr** [comment]
FYI this is in the PDF. For some reason its is not quite as dramatic in the HTML preview. Also the PDF has the text QUOTATION and the QTN-0008 black while the HTML has both in different shades of grey. There is something buggy there.

**Comment by rmehta** [comment]
Spacing in PDF is fixed.
