### ISSUE TITLE
Keyboard shortcuts in Delete/Confirm Dialog: Y or N

### ISSUE THREAD

**Issue by Tropicalrambler** [frappe/erpnext#4771]
When the dialog confirming deletion of an account or item comes up, it would be fantastic to use the "Y" or "N" key on the keyboard to confirm the action, instead of using the mouse.  A setting to enable this would be much better.  Thanks!

**Comment by LifeP** [comment]
Just a suggestion. A "Ctrl+right arrow" for confirming Y, would be good. As we are already using "ctrl+down". " Ctl+left" could be used for N

**Comment by system19** [comment]
Just my 5c:
Wouldn't **Enter** for Yes and **ESC** for no work best?
Safari uses CTR and CMD Right and Left for Back/Forward Page. I know Safari is an edge case browser but still worth thinking about.

**Comment by anandpdoshi** [comment]
I like enter and escape 👍🏼

**Comment by Tropicalrambler** [comment]
Enter and escape work.  I am thinking about end users that do not program, or for example in different languages:  Spanish  would be  S for Si  and N for NO.   Maybe "customizable"  keys for dialog confirmation would be better, so people can set what they want,  with defaults being ESC and ENTER?

**Comment by cgpurbaugh** [comment]
@Tropicalrambler customizable keys would probably add too much complexity for a simple thing. 

Enter and Escape do the specified action.  This should be able to be closed.
