### ISSUE TITLE
Hide special item on print layout

### ISSUE THREAD

**Issue by ShashaQin** [frappe/erpnext#4772]
Hi,
We created a special item called 'TITLE' which are used only to describe the doctype content. So this item just has description, don't have qty, amount and rate. We'd like to hide its qty, amount and rate on the print layout. Our solution is changing html code in item_table_qty.html and creating item_table_amount.html like item_table_qty.html etc.
The changed item_table_qty.html:
{% if (doc.item_code !="TITLE") -%}
	{% if (doc.stock_uom and not doc.is_print_hide("stock_uom")) or (doc.uom and not doc.is_print_hide("uom")) -%}
	<small class="pull-left">{{ doc.uom or doc.stock_uom }}</small>
	{%- endif %}
	{{ doc.get_formatted("qty", doc) }}
{%- else -%}

{%- endif %}
The item list print layout will be:
![item-print](https://cloud.githubusercontent.com/assets/12147007/12905321/4158ceb6-cf11-11e5-9112-77a86a37062e.png)
The qty, amount and rate of line 2 and 4 are hidden by our customized code.
We're wondering if there are other solutions to deal with this issue.

**Comment by anandpdoshi** [comment]
@ShashaQin I think such questions are supposed to be discussed on forum: discuss.erpnext.com

Github issues are mainly for bugs and feature requests.

A simpler solution for this is to add the special item content in the description of the previous item or add a custom field below item table or just add it in terms and conditions.
