### ISSUE TITLE
[Feature Request] Improve Project based budget tracking

### ISSUE THREAD

**Issue by jmatsushita** [frappe/erpnext#4774]
Hi there,

I'm using ERPNext for the first time and trying to setup project based budget tracking. It would be good to be able to be able to see several years on the budget variance report. For instance adding 3-Years and 5 Years options on the Period filter. 

Also it would great to be able to have totals per cost center (enabling "Add total row" works, but filtering by cost-center is hiding the total - I guess because the filtering happens client side). I guess this could be done either by calculating totals client side, or allowing to filter by cost center.

Finally it would be great if it was possible to display cost-centers across all organisations (actually it would also help if this you could also display all cost centers in the chart of cost center tree. Bonus: Allowing to expand all in the char of cost centers).

Cheers!

Jun

**Comment by jmatsushita** [comment]
Hi there, @rmehta friendly bump to ask if this might make its way to the roadmap at some point?

**Comment by rmehta** [comment]
@jmatsushita  can you share a mockup of the report structure.
