### ISSUE TITLE
Print and PDF format not same

### ISSUE THREAD

**Issue by TanujW** [frappe/erpnext#4778]
After the new enhancement, which allows footers, the print format does not show the print format, but the PDF does.

**Comment by anandpdoshi** [comment]
@TanujW can you share a screenshot? I didn't understand the issue.

**Comment by TanujW** [comment]
[Silicon Business Solutions Pvt Ltd.pdf](https://github.com/frappe/erpnext/files/122967/Silicon.Business.Solutions.Pvt.Ltd.pdf)
[Untitled.pdf](https://github.com/frappe/erpnext/files/122968/Untitled.pdf)

The first one is via print (Silicon....pdf)
Second via PDF (with footer) (Untitled.pdf)

The one via print has perfect margins, but the PDF margins are off. 

The PDF one gets the footer, while the print one doesn't

**Comment by TanujW** [comment]
Print Button, and PDF button from Document

**Comment by anandpdoshi** [comment]
duplicate: https://github.com/frappe/erpnext/issues/4753

Also, footer appears only in PDF due to limitations of HTML print
