### ISSUE TITLE
Displaying stock balance while creating quotation (In Quotation Item Line)

### ISSUE THREAD

**Issue by Devens** [frappe/erpnext#4780]
It is very important that while creating quotation, sales user would know - what is the availability of stock (Displaying stock balance will further empower him by understanding total balance of stock in various warehouses). 

We suggest that in Quotation Item (similar to Actual Qty, etc being shown in Sales order Item), stock balance should be displayed as read only field. By clicking on that stock balance, if user can be directed to stock balance report for respective item, it can be further helpful.

**Comment by kamtex** [comment]
Agreed. That will be a good enhancement.
