### ISSUE TITLE
Quotation not linking to Opportunity without items

### ISSUE THREAD

**Issue by TanujW** [frappe/erpnext#4784]
When creating a Quotation from an Opportunity, the new document, Quotation does not add to "Linked With" in the source Opportunity, UNLESS the opportunity has items. 

In case this is a functionality, and not a bug, is there any way I can Link the Opportunity to the Quotation without items?

Thanks!

**Comment by rmehta** [comment]
The liking of opportunity to quotation is done on basis of Items, so this would not be possible with the current design.

**Comment by marination** [comment]
[tested on develop branch: v14]
Created Opportunity without Items > Created Quotation against it > Added items in Quotation > Save > Submit.
Quotation has Opportunity Link in bottom.
Opportunity has quotation link in dashboard and "Linked With" (Links)
