### ISSUE TITLE
[Paid Development] Advanced standard replies/templates for CRM functions

### ISSUE THREAD

**Issue by bradbendy** [frappe/erpnext#4787]
Hi,

We would like to see about adding some features to the "Standard replys" for the CRM functionality.

Once a lead/opportunity has been added we would like to be able to send a e-mail to them with a template/standard reply. In the template we would like to be able to pull doctype variables such as company name, first name, etc. The goal behind this is to create templates with some basic information but also customized with the leads company name, phone numnber, any other fields that are part of the lead.

We would also like to have the functionality to have attachments in the template that will then be sent when that e-mail goes out.

This functionality would be great if it would work in the lead, opportunity and other sections of ERPNext where you can initiate a e-mail to a client, our primary need is for the lead and opportunity though.

Please let me know estimated hours for this project.

Thanks!!

**Comment by Devens** [comment]
+1 for fetching doctype fields as well as for attachment in template (Standard reply)

**Comment by sbkolate** [comment]
@bradbendy  Its great feature,
For now, you can write custom script to fetch doctype variable and make standard reply.
you can post job here https://community.erpnext.com/jobs

**Comment by rmehta** [comment]
- [ ] Call `frappe.render_template(standard_reply_html, doc.as_dict())`

**Comment by vjFaLk** [comment]
@bradbendy This feature has been implemented :)

**Comment by bradbendy** [comment]
Great, I will check this out, thanks so much!!!

**Comment by Devens** [comment]
Hello. If this is implemented, could you please let us know how variables (field values) can be pulled in. Any documentation on this?

**Comment by vjFaLk** [comment]
We've updated the Standard Reply section with a short tutorial

**Comment by Devens** [comment]
Thank you for reply. Could not find neither in Learn Or Standard Reply
section. Could you please advise what are we missing? (Pl see following
screen shots).

[image: Inline image 1]


[image: Inline image 2]




Thanking you,

With Regards,
Deven Shah
Safeworld Systems Pvt Ltd
M - 09825060116

**Comment by vjFaLk** [comment]
@Devens Sorry for the confusion, we've developed the feature but it hasn't been released yet. However, you can have a look at it on [our beta.](http://beta.erpnext.com/desk#Form/Standard%20Reply/New%20Standard%20Reply%201)

**Comment by Devens** [comment]
@valmik - Thank you for reply. Can I have access details for Beta?


Thanking you,

With Regards,
Deven Shah
Safeworld Systems Pvt Ltd
M - 09825060116

**Comment by vjFaLk** [comment]
@Devens Just go to http://beta.erpnext.com/ and hit "Launch Demo"

**Comment by Devens** [comment]
@valmik - Thank you. Could access.

As I understand "Standard reply" would be available at setup/email/standard
reply path.

In Demo (Beta), setup section is not visible.

If it's becoming difficult, we can wait till it's being updated in next
release.


Thanking you,

With Regards,
Deven Shah
Safeworld Systems Pvt Ltd
M - 09825060116

**Comment by vjFaLk** [comment]
@Devens You can access it by searching it in the searchbar.

**Comment by Devens** [comment]
@valmik - Thank you very much. Could see that.


Thanking you,

With Regards,
Deven Shah
Safeworld Systems Pvt Ltd
M - 09825060116

**Comment by valmik** [comment]
Yo, you've been tagging the wrong Valmik. @Devens @vjFaLk

**Comment by vjFaLk** [comment]
@valmik Hahah, this is hilarious. Apologies.
