### ISSUE TITLE
Cannot set custom email address using script for Sales Invoice correspondence

### ISSUE THREAD

**Issue by monojoker** [frappe/erpnext#4793]
Hi Guys, as mentioned in the chat to @rmehta recently I am trying to have the Sales Invoice email routine send to the Billing Contact Email address - rather than the Sales Order which is default. Script we (Maxwell M and I) tried to use is pasted below. However it appears even though the script works, email_doc is encapsulated in a context which means it's an unreplaceable reference - in other words it simply overrides the email my script returns and uses the one from Sales Order doc anyway!

Can you look at this and see what my options are please - our Billing contact is ALWAYS the email address for the invoice, not the person who placed the order (which is the email it defaults to from Sales Order).

    `function get_emails( customer ){
  var ret = [];
  frappe.call({
    'method': 'frappe.client.get_list',
    'async': false,
    'args': {
         'doctype': 'Address',
         'filters': [["Address", "customer", "=", "customer"],
                             ["Address", "email_id", "!=", null],
                             ["Address", "address_type", "=", "Billing"]],
         'fields': 'email'
     },
    'callback': function(res){
        if (res && res.message){
            res.message.forEach(function(row){  ret.push(row.email);  });
        }
    }
  });
 return ret.join('; ')
}
    cur_frm.email_doc = function(message) {
        var composer = new frappe.views.CommunicationComposer({
        doc: cur_frm.doc,
        frm: cur_frm,
        recipients: get_emails(cur_frm.doc.customer),
        attach_document_print: true,
        message: message,
        real_name: this.doc.real_name || this.doc.contact_display || this.doc.contact_name
        });
        composer.dialog.get_input('standard_reply').val('Invoice').trigger('change');
         composer.dialog.set_value('send_me_a_copy', false);
        }`

**Comment by anandpdoshi** [comment]
This script won’t work because of its async nature. 

I think once we were even discussing about removing the email field from “Address” doctype. 

Why don’t you just change the value of “Contact” in the Sales Invoice? Maybe have a “Billing” checkmark in Contact or use the existing ’Is Primary Contact'. Fetch the right Contact and it will change the contact_email, and consequently the default To email address when you compose an email.

Or, you can change the ‘contact_email’ value of Sales Invoice by fetching the email from Address doctype.

Best,
Anand Doshi

ERPNext

**Comment by monojoker** [comment]
That is a good idea - a custom script to change Contact on Sales Invoice form to use the contact we prefer. I hadn't thought of that instead. Will give it a go, thanks @anandpdoshi

**Comment by monojoker** [comment]
@anandpdoshi I think your last sentence is what I already tried and didn't work. Or is there something I'm not thinking of? I am reluctant to create an entire new set of contacts when we have a Billing Address for every customer already. But if in the future the email_id from Address record may be removed then I guess I have no choice :)

**Comment by anandpdoshi** [comment]
Use ajax to set the value of address email into `contact_email` on form load and on contact change
