### ISSUE TITLE
Remove Abbreviation from Accounts

### ISSUE THREAD

**Issue by lakshhya** [frappe/erpnext#4794]
There is abbreviation option in Company Details which is good but this abbreviation is appearing behind every account numbers.  We have only one company and we have unique number to differentiate every account number, so there is no need for abbreviation. Isn't there any option to remove abbreviation.

![image](https://cloud.githubusercontent.com/assets/17191150/12999697/f634d43e-d177-11e5-91b8-fc52fc49ee31.png)

**Comment by anandpdoshi** [comment]
Solution: We should show Account Name instead of Name field

**Comment by mkumar9699** [comment]
we have same problem because my client does not want company abbreviation is chart of account. Please remove this.

**Comment by vrms** [comment]
I'd advise anybody not to put efforts into fighting this dragon but just to adopt to how this works currently

**Comment by ahmed-madi** [comment]
+1 Any updates on this issue?

**Comment by iMoshi** [comment]
I'd really like to be able to remove the company abbreviation as well, at least from the Department in HR. There's only 1 company in the whole system :)
