### ISSUE TITLE
Date and time translations are broken

### ISSUE THREAD

**Issue by Ferohers** [frappe/erpnext#4796]
Hi,

Couldnt really come up with an idea to fix. Had to turn to you guys.

![1](https://cloud.githubusercontent.com/assets/14891349/13002091/69cd0ac8-d174-11e5-8fbd-df2be5283cbc.png)
![2](https://cloud.githubusercontent.com/assets/14891349/13002092/6a5da24a-d174-11e5-8821-bfe07394914a.png)
![3](https://cloud.githubusercontent.com/assets/14891349/13002093/6b4764c0-d174-11e5-9db6-8f4ad0bbac14.png)

**Comment by rmehta** [comment]
Fixed
