### ISSUE TITLE
Manufacturing process with operations

### ISSUE THREAD

**Issue by PratibhaPatil** [frappe/erpnext#4797]
Suppose we are manufacturing one item .i.e lid. So we need to buy raw material as plastic, after that we are going to do some processes on it like melting, moulding.  and also the processes are done on outside vendors,we need to give purchase order So how we will know status of item in manufacturing process. For melting process, plastic will be raw material.

**Comment by rmehta** [comment]
@PratibhaPatil you can either make multi-level bill of materials and make production orders for each stage, or simpler, you can make custom fields for status and change the status after each process update.

Best to ask such questions at https://discuss.erpnext.com
