### ISSUE TITLE
Recurring Invoice custom field value

### ISSUE THREAD

**Issue by adgency** [frappe/erpnext#4798]
I have set up a monthly recurring invoice with a custom date field (tax_date).
Unfortunately every new recurring invoice just copies this date from the first one.
But I need this date to increment monthly OR just add TODAY.
In the Custom Field setup, I've selected NOCOPY and default value TODAY, but this doesn't seem to work for recurring invoice, only for a new invoice or a copy of a invoice.

Thank you for an advice

Milan

**Comment by kennethsequeira** [comment]
The **[Subscription](https://erpnext.com/docs/user/manual/en/accounts/subscription)** or **[Auto Repeat](https://erpnext.com/docs/user/manual/en/accounts/auto_repeat)** should take care of this from now
