### ISSUE TITLE
This webpage is not available

### ISSUE THREAD

**Issue by mkumar9699** [frappe/erpnext#4801]
https://sgsninfo.erpnext.com/login?redirect-to=/desk#login

Till 9:25 AM I was using now it says this web page is not available

Thanks
Mithilesh Kumar

**Comment by anandpdoshi** [comment]
Looks to be working fine. Go to https://sgsninfo.erpnext.com/login <https://sgsninfo.erpnext.com/login> and login.

Best,
Anand Doshi

ERPNext

**Comment by mkumar9699** [comment]
Thanks. Now it's working.



________________________________
