### ISSUE TITLE
Navigation Improvement

### ISSUE THREAD

**Issue by wuditex** [frappe/erpnext#4802]
@rmehta, @anandpdoshi I feel that the ERPNext navigation panel on the left can be further improved by renaming the categories and sorting the documents based on categories shown in navigation panel on left. For Eg. Accounts Module has categories as "Documents, Tools, Setup, Main Reports, Standard Reports, Help" whereas it should have been "Transactions, Masters, Tools, Reports, Setup, Help, etc." Transactions should only have documents like Journal Entry, Purchase Invoice, Sale Invoice, etc.
Similarly for inventory it can be redefined as Stock Movement, Manufacturing, Masters, Tools, Setup, Reports, Help, etc.
HR can be "Employee, HR Entry, Masters, Tools, Setup, etc.
**All that is to be done is that the language should me made simpler for users of those module to understand better.**
I hope you will work on the suggestion. I am sure it would make it a much better product.

**Comment by busyfritz** [comment]
Totally Agreed. This is one of the biggest issues in getting some people in my company to try ERPNext

**Comment by busyfritz** [comment]
For example: http://www.cliptheme.com/demo/packet/LAYOUT-1/#/app/dashboard
This theme feels modern, cohesive and is easy on the eyes

**Comment by wuditex** [comment]
@busyfritz I also like your idea for changing the navigation and further improve ease of use. But I am currently suggesting just redoing the category names and its items. UI Theme can be changed later too.

**Comment by busyfritz** [comment]
Agreed,  the category thing is the biggest issue. As far as look and feel,  the complaint I've gotten is "where is everything"? Users feel lost in the whitespace.  But that could definitely be a step 2

**Comment by rmehta** [comment]
@wuditex @busyfritz A major revamp of the navigation is already under way, and should cover most of your points.

ps. No, the theme won't change as of now.
