### ISSUE TITLE
Tracing invoices by mode of payment (exp. cheque / CC)

### ISSUE THREAD

**Issue by ramielian** [frappe/erpnext#4808]
it is a must in any accounting system to have a trace for the mode of payment and some information when paying in it, like (cheque number, bank, from, date....etc and same of the Credit cards as well).

these information being missing is making the work much harder for the accounting team....

thanks :+1:  :100:  :)

**Comment by rmehta** [comment]
Fields already exist in Journal Entry, are you looking for something else?

Else you can add a custom field!
