### ISSUE TITLE
Not able to add shortcuts to Dashboard

### ISSUE THREAD

**Issue by kamtex** [frappe/erpnext#4809]
In addition to the existing apps on the Dashboard, I would like to add shortcuts to my commonly used pages. too E.g. Invoices, Quotations, Delivery Note. 

There is plenty of wasted screen real estate that can be properly used if I can add my own shortcuts. This will reduce clicks. I know the smart search is good but not fast enough compared to a direct click.

Maybe add a** "Pin to Dashboard"  **under the Menu of the page. Then let us rename it. Add a small shortcut overlay icon to indicate that it is a shortcut and not a full app.

![dashboard idea](https://cloud.githubusercontent.com/assets/17243028/13039805/e63e5870-d3de-11e5-849f-17138908d679.jpg)

Regards,
William

**Comment by Devens** [comment]
It would be really useful for each user.

**Comment by kamtex** [comment]
@Devens Glad that you agree. 
Yup. That is why I think the ERPnext team should look into this for the next update. :)

**Comment by anandpdoshi** [comment]
We have had this in mind for a long time, but it will take some time and effort because:

1. Permissions decide which icons should be shown
1. Show Hide modules per User
1. Show Hide modules for the whole system
1. Good Desktop Icons for each DocType

**Comment by kamtex** [comment]
@anandpdoshi Glad to know that it is planned. I think you should keep it simple first. Implement a basic version and let users decide if they need other features you mentioned. It might be simpler than you think.

Stage 1
**1. **Only for Users. ****
No need for System wide options. The screen should be tailored for each user's own taste and preference. I don't want to see those that others pinned. Not what I want.
You login, you see the ones you 'pinned'. That's it. 

**2. No need for fancy icons.  Just a rounded square with initials in it.** Heck, even reuse some of your icons if you want. Or let users select up to 2 initials/letters for the icon overlay. 

Suggested Flow: Click 'Pin to Dashboard' > Select 2 letters for icon > Choose icon colour (optional) > Icon displays on dashboard.

**3. Open count max at 10. Any more show 10+.  (for a start)**
The open count lets take swift action. Personally if something is more 10 and I have not touch it yet means it's not really important. (Eisenhower's Decision matrix)

Hope my suggestion helps! :)

**Comment by kamtex** [comment]
@anandpdoshi Actually you can scrap no. 3 and not reveal counts at all.  I think we users will be contented with just the basics.

**Comment by sbkolate** [comment]
+1 very good feature.

So if one user is only sales user then he will add Lead / Opportunity / Quotation / Sales Oder as Icon for his desktop

**Comment by anandpdoshi** [comment]
https://github.com/frappe/frappe/pull/1594

**Comment by kamtex** [comment]
@anandpdoshi Wow, thanks for listening! I am sure everyone will be loving this!

**Comment by kamtex** [comment]
Oops, I pressed wrongly!
