### ISSUE TITLE
HR - report once a employee leave

### ISSUE THREAD

**Issue by fderyckel** [frappe/erpnext#4810]
Let's say Employee A has left the company on January 15th.  
We have tagged him as left and indicated the date of his last day in the exit section. 

Now I would like to review the attendance of December & January for Employee A (and today we are February 15th).  

It is not possible to review the attendance of an employee that has left the company for a time when he was in the company.  Any chance, we cool change that?

**Comment by vjFaLk** [comment]
Fixed via #4824

**Comment by fderyckel** [comment]
Thank you @vjFaLk Awesome work!

**Comment by vjFaLk** [comment]
You should be able to see _any_ employee with a minimum of a single marked **attendance** in the selected month. In case an employee doesn't have a single attendance, they will not show up.

**Comment by fderyckel** [comment]
OK now it works.  I had to wait 6.22.1
Thanks again for doing this.
You can close.
