### ISSUE TITLE
Modification in Stock analytics report

### ISSUE THREAD

**Issue by Devens** [frappe/erpnext#4812]
1. Item Name should be displayed (either in place of Item Code OR in separate column)
2. search/filter by Item Name
3. Option to hide zero value rows
4. From report heading, it's not clear that the analysis is of what (Inword, Outword, balance or anything else?)
5. Option to filter by Company

![image](https://cloud.githubusercontent.com/assets/10671911/13042887/10d85256-d3ea-11e5-893e-cf44d2b4d00f.png)

**Comment by SonaliBudhrani** [comment]
+1

**Comment by SaiFi0102** [comment]
+1

**Comment by ankush** [comment]
1. Item name is displayed now.
2. search anyways considers item name, item group fields in addition to item code. 
3. Set the filter as `>0` in any of the columns where you want to remove zero-valued rows. So no need for extra option for this.
4. It's stock balance, will try to clarify it somehow in UI. 
5. Good point!
