### ISSUE TITLE
Can I set one field value to Other field with some logic

### ISSUE THREAD

**Issue by mkumar9699** [frappe/erpnext#4816]
I want to add two columns in Invoice 1. Actual Weight 2. Charged Weight
If I enter 30 as actual weight then minimum charged weight should be 50 or 100 as defined in Sales Order and if it is greater than minimum  then charged weight should be Actual weight.

Please suggest

Mithilesh

**Comment by rmehta** [comment]
please add a custom script.

http://frappe.github.io/erpnext/user/manual/en/customize-erpnext/custom-scripts/

Further questions on https://discuss.erpnext.com
