### ISSUE TITLE
Sum of Additional column Value other than Amount  can be set in sales tax template

### ISSUE THREAD

**Issue by mkumar9699** [frappe/erpnext#4817]
I want to add sum charges column in sales invoice Item and post the sum of columns to their respective Account head or Sum of column Value other than Amount  can be set in sales tax template to post the account entries.

Please tell me how can be done.

Thanks
Mithilesh

**Comment by mkumar9699** [comment]
I am still waiting. Please help.

**Comment by nabinhait** [comment]
Could not understand your requirement properly. Please give some example to describe the requirement. Also, please post such issues in the forum (discuss.erpnext.com), this is not the right place for posting requirements for customization. Closing this issue.
