### ISSUE TITLE
Sales Tax Charges for Other charges can be calculate on charge_type Net Weight

### ISSUE THREAD

**Issue by mkumar9699** [frappe/erpnext#4819]
I want to calculate charges on Net Weight or Total no. of packs in Sales Invoice. Please help.

Thanks
Mithilesh

**Comment by mkumar9699** [comment]
I am still waiting.

**Comment by rmehta** [comment]
@mkumar9699 can you ask questions on the forum? https://discuss.erpnext.com

If this is a feature request, please elaborate how you want the feature to be built.
