### ISSUE TITLE
Combine order for common item

### ISSUE THREAD

**Issue by PratibhaPatil** [frappe/erpnext#4821]
While placing the PO for the same item having more than 2 material request,must add additional quantity instead of adding same item in the Purchase Order.

**Comment by LifeP** [comment]
This is something that can be extended to production orders too.

**Comment by kennethsequeira** [comment]
this can be achieved within print: 
![image](https://user-images.githubusercontent.com/33246109/128975153-ea9af002-27b1-4e49-8346-1f9d083c26ab.png)


The reason for keeping the line items separate is that each of them originate from a different MREQ. Thus for the sake of tracking, each one is kept separate in the item. 

But at print level one has the option of grouping them.
