### ISSUE TITLE
Unable to pay in ERPNext POS

### ISSUE THREAD

**Issue by olbanana** [frappe/erpnext#4828]
Everything is working fine and as required. But when I go to pay using the POS screen I don't get the option to pay off a transaction.

When I click on pay after doing my selections, it says missing values required and the popup after that shows up without any button to pay off the transaction.

Is this an issue with ERPNext or is it something with my configuration. Will highly appreciate any input on this as currently my implementation is live on premises and this is causing huge issues.

![screen shot 2016-02-17 at 8 18 51 pm](https://cloud.githubusercontent.com/assets/605724/13114107/e169edd8-d5b3-11e5-876a-a1ea5bd2ec81.png)
![screen shot 2016-02-17 at 8 19 00 pm](https://cloud.githubusercontent.com/assets/605724/13114108/e1c72282-d5b3-11e5-8833-9bee5c91ce86.png)

**Comment by rmehta** [comment]
Do you see anything in your JS console?

Did you add "Amount Paid"?

**Comment by olbanana** [comment]
Actually, based on my understanding of the issue... this function is not working altogether... as in nothing happens here.

As you can see the total amount is empty when this should have the actual value of the transaction it normally have.

Then even if I enter the amount paid it doesn't calculate the change as it normally does.

My JSConsole does throughs an error but I don't think thats the cause of it. The error attached generates when I click on pay.


![screen shot 2016-02-18 at 2 11 39 pm](https://cloud.githubusercontent.com/assets/605724/13138622/0f049b30-d64a-11e5-8198-dacbbd85d88e.png)
![screen shot 2016-02-18 at 2 13 23 pm](https://cloud.githubusercontent.com/assets/605724/13138623/0f53a144-d64a-11e5-8b67-c58fb02ba833.png)

**Comment by nabinhait** [comment]
Can't replicate the issue. Are you using the latest version?

**Comment by retroneo** [comment]
Can replicate here if select non-cash as default mode of payment in POS profile.

For me, error disappears if switch to cash and then back to other payment method.
