### ISSUE TITLE
Typos in accouting app 

### ISSUE THREAD

**Issue by limehalves** [frappe/erpnext#4830]
Hello,
it seems that there are two typos in the accounting App in the demo system.
Would you like us to correct them?
Installed Apps:
ERPNext: v6.22.0, ERPNext Demo: v0.0.1, Frappe Framework: v6.23.0

![typo in accounts module 20160218](https://cloud.githubusercontent.com/assets/17129732/13136248/29fd3154-d618-11e5-8b0c-1669d4b512b0.JPG)

**Comment by neilLasrado** [comment]
@limehalves fixed it. Thanks for reporting.

**Comment by limehalves** [comment]
@neilLasrado  that was fast. good job!
