### ISSUE TITLE
Typo in Accounts module II

### ISSUE THREAD

**Issue by limehalves** [frappe/erpnext#4835]
here's another one...sorry I didn't notice it earlier

![tyop in accounts module 20160218-2](https://cloud.githubusercontent.com/assets/17129732/13143824/d57041ec-d646-11e5-8a10-996599514e60.JPG)

**Comment by neilLasrado** [comment]
Fixed it as well :-)

**Comment by limehalves** [comment]
Awesome, @neilLasrado !
