### ISSUE TITLE
issue with "In Stock" and "Projected" inventory in POS

### ISSUE THREAD

**Issue by limehalves** [frappe/erpnext#4837]
It seems that there is an issue with the "In Stock" and "Projected" inventory levels in the POS app.
Installed Apps: ERPNext: v6.22.0, ERPNext Demo: v0.0.1, Frappe Framework: v6.23.0
Please check out the step-by-step screenshots of three consecutive orders of the same product
 on the ERPNext demo site and pay attention to the evolution of the "In Stock" and "Projected" inventory levels. 
In case you can confirm the issue, would you like us to fix it?

![pos inventory 1](https://cloud.githubusercontent.com/assets/17129732/13144957/ec786f48-d64d-11e5-930e-654b6ead5176.JPG)
![pos inventory 2](https://cloud.githubusercontent.com/assets/17129732/13144971/042a08fe-d64e-11e5-9e02-970672d03002.JPG)
![pos inventory 3](https://cloud.githubusercontent.com/assets/17129732/13144977/08699574-d64e-11e5-8214-33467f0bc3dc.JPG)
![pos inventory 4](https://cloud.githubusercontent.com/assets/17129732/13144981/0e403188-d64e-11e5-98c2-28800fa52213.JPG)
![pos inventory 5](https://cloud.githubusercontent.com/assets/17129732/13144985/13c31418-d64e-11e5-9779-283e5466563d.JPG)
![pos inventory 6](https://cloud.githubusercontent.com/assets/17129732/13144990/1774a400-d64e-11e5-9f6c-7b927d858e50.JPG)
![pos inventory 7](https://cloud.githubusercontent.com/assets/17129732/13144991/1a74c3ba-d64e-11e5-83f5-eaca3ccdf4fb.JPG)
![pos inventory 8](https://cloud.githubusercontent.com/assets/17129732/13144994/1d31c346-d64e-11e5-8f3b-02777b7d0062.JPG)
![pos inventory 9](https://cloud.githubusercontent.com/assets/17129732/13144997/20a794ba-d64e-11e5-8837-3057644babe8.JPG)
![pos inventory 10](https://cloud.githubusercontent.com/assets/17129732/13145001/246541c4-d64e-11e5-8ae4-d00284978e89.JPG)
![pos inventory 11](https://cloud.githubusercontent.com/assets/17129732/13145005/272acd34-d64e-11e5-83d7-8f1451476d35.JPG)
![pos inventory 12](https://cloud.githubusercontent.com/assets/17129732/13145006/2a19114a-d64e-11e5-822d-f3378c0d3759.JPG)

**Comment by rmehta** [comment]
@limehalves check if "Update Stock" is checked for each of the invoices. If yes, then it does seem like an issue.

We are happy to take fixes anytime :)

**Comment by limehalves** [comment]
@rmetha good point! "Update Stock" is indeed unchecked when switching from "Point-of-Sale View" to "Form View" (Sales Invoice view). However, I'm not sure if I understand your comment correctly. Do you suggest that, for example, employees using the POS interface in a retail store should switch from the "Point-of-Sale View" to "Form View" during each transaction they perform?

**Comment by anandpdoshi** [comment]
Check “Update Stock” in POS Profile form and it will always check “Update Stock” for each transaction.

Best,
Anand Doshi

ERPNext

**Comment by limehalves** [comment]
@rmehta and @anandpdoshi  thanks for the hint! I've tried it with an updated POS Profile on [https://demo.erpnext.com/](url) and the inventory levels work fine.
