### ISSUE TITLE
Suppliers' quotations filed in foreign currency should update base_total when currency exchange rate changes

### ISSUE THREAD

**Issue by m-delvalle** [frappe/erpnext#4840]
**Use case:**

Buyer receives quotations of imported goods on "B" currency, which is not the company's base currency (that would be "A"). In spite of this, payments are only made in "A" (a legal constraint).

In-between the time the buyer receives a quotation (or even a bill) and until the accountant actually files the corresponding payment, currency conversion rate (B/A) might change.

When buyer submits a supplier quotation with "B" as currency, ERPNext uses stored conversion rate B/A to display a local currency cost as well. That's nice, but if accountants change the currency rate (in 'Accounts > Setup > Currency Exchange') this local currency value is not updated. Buyer can validate the quote, create an invoice, and accountants can even validate such invoice and make payments with the old currency rate.

**Expected behaviour:**

ERPNext should only fix local currency cost (in "A") at the moment of actually _filing_ the payment. Till then, local currency cost should always be updated with current exchange rate.

If quotation is defined to have "B" as currency, then displaying cost in "A" is only a (useful) matter of convenience for, e.g., comparison sake. But the supplier's commitment is on the "B" price.

Maybe there's a use case for current behaviour (other countries, other legal regulations, other market conditions than exposed here), so perhaps this request should be enabled through a "switch" in setup.

**Comment by strixaluco** [comment]
Has this issue been eventually closed?

**Comment by harshit-30** [comment]
Please create another issue if it is replicable after v13.10.
