### ISSUE TITLE
Feature request - Billable hours tracking

### ISSUE THREAD

**Issue by gabtzi** [frappe/erpnext#4850]
Hello, I would like to suggest a feature that could be useful to a lot of professionals that charge by the hour. I've tried to think of how it should work through a real case example so I might have missed a few points or difficulties but here's a rough analysis of how I imagine it would work. 

Here's the original discussion https://discuss.erpnext.com/t/how-to-track-prepurchased-hours-of-technical-support/10551
### Entities:

CUSTOMER: The actual customer that purchases the service
USER: The erp user
SERVICE: Any service or item that is billed by Time units
SYSTEM: ERPNext
### Use case scenario:

The CUSTOMER purchases and prepays for a fixed amount of hours for a SERVICE so he can buy them at a lower rate.
The SERVICE could be something like phone support, technical support, legal advice, psychiatrist appointments, machine usage, rentals and generally services that are billed by time periods.  
After the CUSTOMER purchases the package he has to use it within a timeframe after which the available hours in the package expire (for example 3 months). Ideally both the expiration and starting date should be set by the USER. 
For easier understanding we will be talking about hours but this could be expanded to other periods as well for example for leasing periods. 
#### USER
1. The USER should be able to view the remaining hours for each CUSTOMER. 
2. The USER should be able to see when the remaining hours expire
3. The USER should have an interface to actually mark the used hours.
4. The USER should be able to mark when, why and who authorized the usage of those hours. 
5. It would be nice if there was a link where the USER  could see a list of all used up hours with the dates and justification.
#### CUSTOMER
1. It would be nice if there was a link where the CUSTOMER could see a list of all used up hours with the dates and justification.
2. It would also be nice to have a report of when the hours expire and how many hours are left linked through the invoice IDs in case they purchased two or more SERVICES that haven't expired for example tech support and development
#### SYSTEM:
1. The SYSTEM should automatically add billable hours to the customer's account for each SERVICE when an invoice is issued. 
2. The SYSTEM should track the dates of expiration and mark the remaining hours of each invoice as expired after expiration date has passed. 
3. The SYSTEM should notify the CUSTOMER's dafault contact person for the remaining hours from each invoice item a few days before they expire.

**Comment by jwrober** [comment]
Might be related to this issue too
https://github.com/frappe/hrms/issues/208

**Comment by gabtzi** [comment]
Hi, I don't see the resemblance of what I describe with frappe/hrms#208 . This is something entirely different and what I described doesn't need any type of linking with work personnel and those employees billable hours.

**Comment by jwrober** [comment]
You could a project and timesheet with billable hours loaded to track used vs purchased.

**Comment by lostless13** [comment]
We have a similar workflow at our company and I have seen it at others.

CUSTOMER provides a purchase order authorizing X number of time (hours or days) under different activity types with corresponding rates.
USER creates Sales Order in a project to reflect customer sales orders
USERS submit timesheets assigning time to the project and activity types
USER creates Invoice from sales order and applies billable hours from timesheet to that sales order based on activity type.
CUSTOMER receives Invoice showing total time, activity and totals price along with an itemized report of time, date and justification.
SYSTEM tracks total hours used and hours burndown.
