### ISSUE TITLE
Feature request - Loyalty / Reward points

### ISSUE THREAD

**Issue by gabtzi** [frappe/erpnext#4851]
One feature that would be very interesting to see implemented but I think would be hard to do so is a loyalty / reward system. This exists in most ecommerce platforms in various forms but the basic one could be handled for physical sales in a shop as well. I've seen it in two high selling ERPs for B2B purposes. The basic one is that the CUSTOMER is automatically rewarded X points for each Y money spent based on rules defined by the USER and can then exchange them for discounts or change CUSTOMER group and get better discounts. The reason why points are used instead of actual money, is to make the CUSTOMER feel better at spending them. It's easier for a person to spend points than actually spend money so they would probably end up using their points really fast. It's also a bit addictive to gather them up so that you can gain a gift. 
### Entities:

CUSTOMER: The actual customer that purchases the service
USER: The erp user
ITEM: Any product or service
SYSTEM: ERPNext
COMPANY: The company selling the ITEM
### Use case scenario:

The COMPANY wants to reward CUSTOMER loyalty. Loyalty can be defined as any way that will promote the COMPANY. For example, a like on facebook, sharing, emailing to a friend, purchases, birthdays. 
In particular the one I find more interesting is significant purchases or repeat purchases. 

For example the CUSTOMER is automatically rewarded X points for each Y money spent based on rules defined by the USER. Consequently a fixed amount of points can be exchanged for actual amount of discount or a coupon code or an ITEM again based on rules defined by the USER.  Optionally the reward points could expire after a period. 

In a B2B case scenario, the points could be gathered up within a timeframe to actually change the level of a CUSTOMER and give him a better discount. The level could be just a CUSTOMER GROUP. 

The USER would also add points manually for actions that need to be checked like a facebook like or share of facebook contests. These could also be done automatically it's a whole different story. 
#### USER
1. The USER should be able to view the points awarded to each CUSTOMER. 
2. The USER should be able to add/subtract manually points. 
3. The USER should be able to set fixed rules to automatically award points. 
4. The USER should be able to set fixed rules for using the points.
#### CUSTOMER
1. It would be nice if there was a link where the CUSTOMER could see a list of all used up points with the dates and justification.
2. The CUSTOMER would need to see how many points he has gathered and when they expire.
#### SYSTEM:
1. The SYSTEM should automatically award points based on a set of rules.
2. The SYSTEM should automatically subtract points based on a set of rules and implement the actions of those rules (e.g. discount). 
3. The SYSTEM should track the dates of expiration and mark the remaining points of each CUSTOMER as expired after expiration date has passed. 
4. The SYSTEM should notify the CUSTOMER's dafault contact person for the remaining points a few days before they expire.

**Comment by rmehta** [comment]
@gabtzi thanks for the detailed explanation! Screen mock-ups would be great.

**Comment by gabtzi** [comment]
Not good at designing but I'll try to see what I can do this weekend

**Comment by PawanMeh** [comment]
PR is in progress for this feature. You can follow it [here](https://github.com/frappe/erpnext/pull/12631).
