### ISSUE TITLE
Feature Request - System Generated Events for Reminders and Notifications

### ISSUE THREAD

**Issue by bibinqcs** [frappe/erpnext#4853]
Hi,
It would be very helpful if the ERPNext system has an option to automatically create events in the calendar that can give reminders and notification for any document based on a particular date field, Similar to the follow up feature in leads and Birthday Notifications. 

It would be helpful for the following Scenarios when
- There is a post dated cheque and needs to be cashed on a particular day
- Credit period is nearing the end on a particular transaction (sales or purchase)
- Customer has been issued a quotation with a particular rate which is valid for a specific number of days
- When a personnel in HR has to renew a contract

Thank you

With Regards
Bibin

**Comment by rmehta** [comment]
Notification already does this for most cases
