### ISSUE TITLE
Feature Request - Add Project inside the Production Planning Tool

### ISSUE THREAD

**Issue by andiyan1** [frappe/erpnext#4861]
Dear SIr,

In the Production Planning Tool of the manufacturing module in ERPNEXT, I can pull sales order based on items and customer then get all the item required then make production order or material request.

my question is, do you think its good to add "pull from project" option so that the production planning tool can pull all the sales order related to project and create production orders and material request based on that project.

i also notice that material request still do not have project related to it. eventhough purchase order can be related to a specific project.

my question is:

do you think its posible to link project to production planning tool and material request
then it would be easier to track production and material request based on the ongoing project that we are doing right now

i am willing to sponsor for development if its necessary

Thanks and best regards

Anton

**Comment by neilLasrado** [comment]
@andiyan1 I can add project as a filter in Production Planning Tool. so you can pull all sales orders / material requests based on a project. Will also add project in Material Requests. Hope that would work for you.

**Comment by andiyan1** [comment]
Hi Neil,

Yes thats would be sufficient. So I can filter Production Planing tool
based on Project

then i can create the material request or production order based on that
project

dont forget to add link to push project_name from material request to
supplier quotation and purchase order.

so that i can link all the existing document with the project i am doing

Anton



On Tue, Mar 1, 2016 at 6:14 PM, Neil Trini Lasrado <notifications@github.com

**Comment by andiyan1** [comment]
Hi Neil,  sorry

Dont forget to push it to production order too

Thanks
Anton
