### ISSUE TITLE
Shipping rule charge_type Net Weight does not work

### ISSUE THREAD

**Issue by mkumar9699** [frappe/erpnext#4870]
Shipping rule charge_type has two options On Net Total and Net Weight but when I select On Net Weight it does not calculate on Net Weight

Net Weight is a calculated field. Please help.

Thanks
Mithilesh Kumar

**Comment by nabinhait** [comment]
Seems like you have added customized option "On Net Weight" in charge_type. It will not work automatically, you have to change the code for calculation as well. Also, please raise such customization related issues on discuss.erpnext.com, it is related to issues with standard functionalities.

**Comment by mkumar9699** [comment]
"On Net Weight" in charge_type is already there in Shipping Rule template. Please check.


Thanks

Mithilesh


________________________________

**Comment by nabinhait** [comment]
Can you please provide a screenshot?

**Comment by mkumar9699** [comment]
![image](https://cloud.githubusercontent.com/assets/16901262/13317137/c01d8f82-dbd9-11e5-851d-69d3a0ef4867.png)

**Comment by nabinhait** [comment]
But that is a hidden field. The feature is not implemented, only field remained as a hidden field.
