### ISSUE TITLE
Format Setup - Cannot align right

### ISSUE THREAD

**Issue by kamtex** [frappe/erpnext#4872]
Hi. I was editing my Quotation format under Heading, the rich format editor button only show Align Left, Align Centre but no Align Right.

**Comment by nabinhait** [comment]
Can you give a screenshot?

**Comment by kamtex** [comment]
Hi Nabin,

Here it is. .[image: Inline images 1]

*Kamtex Industries Pte Ltd *(since 1982) | www.kamtexsolar.com | T:
+65-67445307, 67414939 | F: +65-67445306 | *Your one-stop solar provider! *
Products: COMPLETE SYSTEMS | SOLAR PANELS | BATTERIES | CONTROLLERS | SOLAR
LIGHTS | KITS | CUSTOMISATION
Brands: KAMTEXSOLAR | SHARP | PHOCOS | MORNINGSTAR | TROJAN

**Comment by Devens** [comment]
+1. In fact, pointed out long back.

**Comment by kamtex** [comment]
@nabinhait I updated the screenshot.

![erpnextalighright](https://cloud.githubusercontent.com/assets/17243028/13316511/5d757dc4-dbeb-11e5-8854-79d5466cd7b4.jpg)

**Comment by kamtex** [comment]
Sorry. Here is a better image. 

![erpenextrightalign2](https://cloud.githubusercontent.com/assets/17243028/13316890/18ac37bc-dbed-11e5-8162-702a9411c48d.jpg)
