### ISSUE TITLE
In Delivery Note hide both Is Return and  Ignore Pricing Rule if check-box is not checked 

### ISSUE THREAD

**Issue by sbkolate** [frappe/erpnext#4878]
Confusion due to read only check-box Is Return and Ignore Pricing Rule In Delivery Note.

When we create Delivery Note, It looks like this.

![dn11](https://cloud.githubusercontent.com/assets/6648915/13345182/d9cb3b38-dc82-11e5-828f-ada2adc387b4.png)

One of our user reported bug that he can not click on Ignore pricing rule and Is Return.

We know that is return is checked when we create Sales Return from submitted delivery note.
But showing unchecked check-box is quite confusing to basic user

![dn22](https://cloud.githubusercontent.com/assets/6648915/13345237/54747138-dc83-11e5-8032-70bc22f6613b.png)

Similarly for ignore pricing rule.
We can define pricing rule based on customer, item and territory. 
We can ignore same rule in Sales Order and Sales Invoice, but we can not ignore pricing rule directly in Delivery Note.
If we create Delivery Note from Sales Order then ignore pricing rule is carry forward in delivery note.

Our suggestion is to hide both **Is Return** and  **Ignore Pricing Rule** if check-box is not checked 

Thanks,

**Comment by anandpdoshi** [comment]
Fixed. Now it shows this symbol in read only mode if unchecked: http://fontawesome.io/3.2.1/icon/ban-circle/

**Comment by sbkolate** [comment]
Thanks @anandpdoshi for fixing this issue. 
It will helpful for end user.

**Comment by anandpdoshi** [comment]
@sbkolate thanks for raising it :+1:
