### ISSUE TITLE
Issue while creating sales order

### ISSUE THREAD

**Issue by cvishyl** [frappe/erpnext#4890]
While creating a new sales order, delivery date tab shows the list of users of the system in the drop down list and at the back the calendar is displayed .. it seems this is a bug.

Same is the issue with Customer Purchase Order also.

I am using IE on windows 10

**Comment by anandpdoshi** [comment]
Can you share a screenshot?

**Comment by cvishyl** [comment]
I have tried on windows platform with IE browser ... it has this
problem... attached




On Sat, Feb 27, 2016 at 9:49 AM, Anand Doshi <notifications@github.com>
wrote:

> Can you share a screenshot?
>
> Sent from my phone
>
> > On 27-Feb-2016, at 7:44 AM, Viswanath <notifications@github.com> wrote:
> >
> > While creating a new sales order, delivery date tab shows the list of
> users of the system in the drop down list and at the back the calendar is
> displayed .. it seems this is a bug.
> >
> > Same is the issue with Customer Purchase Order also.
> >
> > I am using IE on windows 10
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/frappe/erpnext/issues/4890#issuecomment-189574394>.
>



-- 
Viswanath Ch V K

**Comment by anandpdoshi** [comment]
@cvishyl didn't receive the screenshot. Can you go to the github issue page and drop the files?

**Comment by cvishyl** [comment]
screenshot attached
![error](https://cloud.githubusercontent.com/assets/17192258/13415760/7a6c3c06-df83-11e5-9baa-8a9f7aab6202.jpg)

**Comment by cvishyl** [comment]
What happend....any update?

On Saturday, February 27, 2016, Anand Doshi <notifications@github.com>
wrote:
> Can you share a screenshot?
>
> Sent from my phone
>
>> On 27-Feb-2016, at 7:44 AM, Viswanath <notifications@github.com> wrote:
>>
>> While creating a new sales order, delivery date tab shows the list of
users of the system in the drop down list and at the back the calendar is
displayed .. it seems this is a bug.
>>
>> Same is the issue with Customer Purchase Order also.
>>
>> I am using IE on windows 10
>>
>> —
>> Reply to this email directly or view it on GitHub.
>>
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci6.googleusercontent.com/proxy/EBUAxk1cfsxwFeznDl1Myb4JVYad2e1q4ofN6jUsemI-z31uA1g-DR_YP7LX8uyUkgXapeEN8QiQmIcIdOxjPgxMk7vwk7sCIrCO4IlHxtcqh7r6MrqRimSQnywwA7r9uufbiVCXx5s-pIoKTW1KqXmlfXgUSg=s0-d-e1-ft#https://github.com/notifications/beacon/AQZVQvEGhd19xyy9Q0xjlmmTRUyZxtOdks5poRs9gaJpZM4HkV4K.gif
>

-- 
Viswanath Ch V K

**Comment by rmehta** [comment]
This was an IE bug, please update your IE

**Comment by cvishyl** [comment]
Yes... i noticed this...thanks


On Thu, Mar 17, 2016 at 5:46 PM, Rushabh Mehta <notifications@github.com>
wrote:

> This was an IE bug, please update your IE
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/frappe/erpnext/issues/4890#issuecomment-197852276>
>



-- 
Viswanath Ch V K

**Comment by cvishyl** [comment]
We have uploaded stock opening thru stock reconciliation option .. And also
updated the VAT and item price...

But when we do a POS invoice... The VAT appears some time for the same item
and some times it does not...

What could be the reason ?

Viswanath

On Fri, Mar 18, 2016 at 10:13 AM, Cvishyl Viswanath <cvishyl@gmail.com>
wrote:

> Yes... i noticed this...thanks
>
>
> On Thu, Mar 17, 2016 at 5:46 PM, Rushabh Mehta <notifications@github.com>
> wrote:
>
>> This was an IE bug, please update your IE
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/frappe/erpnext/issues/4890#issuecomment-197852276>
>>
>
>
>
> --
> Viswanath Ch V K
>



-- 
Viswanath Ch V K

**Comment by anandpdoshi** [comment]
@cvishyl do you mind posting this as a separate issue?
