### ISSUE TITLE
Serial Print on screen incorrectly on Purchase Reciept

### ISSUE THREAD

**Issue by hpema** [frappe/erpnext#4893]
Hi Team,

Dont know yet how to fix this bug myself ;), but I think the html format is not correct with auto generated serial numbers

![image](https://cloud.githubusercontent.com/assets/5782668/13377877/d3eed77c-ddf6-11e5-8461-d59403f18f74.png)

regards
Hemant

**Comment by anandpdoshi** [comment]
Hi Hemant,

Thanks for reporting this. We will fix this tomorrow.
