### ISSUE TITLE
Block the printing of draft copies

### ISSUE THREAD

**Issue by pickmix** [frappe/erpnext#4894]
Hello i would like to block the printing of draft copies so that my cashier will have to submit all her journals so we can cash up at the end of the day

**Comment by rmehta** [comment]
- [ ] In Print Settings
  - [ ] "Allow printing of cancelled documents"
  - [ ] "Allow printing of draft documents"

**Comment by pickmix** [comment]
Thanks. 

This is brilliant

Regards

Robert
Pickmix Team

**Comment by pickmix** [comment]
Hello Rushabh ,

Thanks ,Please do you mean the print settings .
I think the update has not kicked in yet.

Regards

Robert
Pickmix Team

**Comment by anandpdoshi** [comment]
@pickmix it is in todo. You will know when the above boxes get ticked :smile:

**Comment by felixvarghese** [comment]
I believe this issue can be closed as these options are available in Print Settings.

**Comment by rmehta** [comment]
@felixvarghese should i add you to the issue closing group :) ?

**Comment by felixvarghese** [comment]
Sure. I'm happy to help wherever I can.

I had a need for this option today and ran across this issue while searching. Its amazing how many features ERPNext has.
