### ISSUE TITLE
Stock valuation issue

### ISSUE THREAD

**Issue by hpema** [frappe/erpnext#4895]
Hi think this is a bug.

I created serialised items for this example as it best describes out business process from a cost point of view.

We do receive items from suppliers that are for demo purposes to our customers and therefore do not have any cost in the journals but we want to manage the movements. ERPNext allows me to receipt these at zero cost which works well. But as soon as I do the next receipt at value it does not calculate the new stock value correctly. According to my example the value should be R500 as the first 10 receipted have no value.

Then I ship them out and those calculation reduce the value correctly as I shipped 3xR100 on line 3 and the last line showing correctly as the shipment is 2x(1@R100 and 1@R0)=R100, this would make the stock value = R100 but showing R1100 cause of the error in calcs

Hope I explained that correctly.

![image](https://cloud.githubusercontent.com/assets/5782668/13379854/a8405044-de3a-11e5-9cb1-e279f19a2463.png)

**Comment by hpema** [comment]
Hi,

Im still trying to understand the underlying code but I think I found the issue and not sure if it does not affect other parts of the system so not going to recommend a pull request - maybe you can tell me if Im on the right track.

What I have done is change in stock_ledger.py, def process_sle(self, sle): line 158 from : 
self.stock_value = flt(self.qty_after_transaction) * flt(self.valuation_rate)
to:
self.stock_value = flt(sle.actual_qty) * flt(sle.incoming_rate)

I will keep testing further.

regards
Hemant

**Comment by nabinhait** [comment]
Thanks for reporting. Will push a fix today.

**Comment by hpema** [comment]
Please dont fix anything yet...im still analysing the effects as I noticed that shipment valuation and stock balance not working. I will come back with a fully resolution as I investigate more - trying to learn how its all fitting together taking some time.

thanks

**Comment by nabinhait** [comment]
Already pushed a fix https://github.com/frappe/erpnext/pull/4899.
