### ISSUE TITLE
Need In Sales Invoice, Get Item from Delivery Note depends on “Proof Of Delivery Date(PoD) ” field of Delivery Note

### ISSUE THREAD

**Issue by mkumar9699** [frappe/erpnext#4896]
I have "Proof Of Delivery Date(PoD) " field in Delivery Note and PoD update after making delivery note. When I select get item from delivery note and if Proof of delivery date(PoD) is less than Invoice Date and not billed then it Should appear in sales invoice.

If PoD has not been received then it should not insert row in to Sales Invoice Item.
Delivery Note #: DN-00001
Delivery Note Date: 01-FEB-2016
PoD Date: 10-FEB-2016 (It should be updated after making Delivery Note)

Invoice Date : 23-FEB-2015

Thanks
Mithilesh

**Comment by anandpdoshi** [comment]
Hi Mithilesh,

I think this should be handled as a customization. You should start by
adding a Custom Field and writing custom script for this.
