### ISSUE TITLE
Outgoing Email not sent in Bulk Email List

### ISSUE THREAD

**Issue by airzoink** [frappe/erpnext#4902]
Tried to setup outgoing email based on instructions (using free Gmail Account). I could not make it to send out quotations, sales order, sales invoice, etc.. I tried restarting and updating bench. Changed email account and saving it without errors. Still Bulk Email List gives out 'not sent' status. Help please!

Thanks!

- Aaron

**Comment by anandpdoshi** [comment]
Looks like a problem with supervisor config. Check `sudo supervisorctl status` and see if all processes are running. 

This issues list is used for reporting bugs or adding feature requests. Please post on https://discuss.erpnext.com if you need help.
