### ISSUE TITLE
Series for serial number cannot be reset

### ISSUE THREAD

**Issue by hpema** [frappe/erpnext#4903]
Hi Team

When deleting all data for a company I see that the serial number series sequence number is not reset.

I tried the naming series form but the series does not list on the select box.

Any idea how to reset to zero the serial number series?

regards
Hemant

**Comment by addymuliady** [comment]
Hi!

encountered this too on 7.1

Has this been fixed?

**Comment by uzbek14** [comment]
Is there any solution for this
