### ISSUE TITLE
Multicurrency (Foreign currency & local currency) in the same Accounts Receivable & Payable Report

### ISSUE THREAD

**Issue by Dineshbabunest** [frappe/erpnext#4907]
We require the Accounts Receivable & Accounts Payable Report (customer wise/supplier wise) with an additional columns for Foreign currency.  The report should show the Foreign currency in one column and the value in local currency (UAE Dhs.) in the ext column. Sample report attached.
[1.Aging Receivable-(sample).docx](https://github.com/frappe/erpnext/files/152454/1.Aging.Receivable-.sample.docx)

**Comment by Dineshbabunest** [comment]
Is there any progress in solving the above issue?

**Comment by nabinhait** [comment]
How do you want it? Should outstanding amount in company currency be shown by simply multiplying by some fixed exchange rate? Or you want to display actual outstanding in the company currency based on invoice exchange rate?

I think second one (based on invoice exchange rate) does not makes sense. As customers are actually going to make payment in their currency, hence only outstanding amount in party currency is important.

**Comment by Dineshbabunest** [comment]
We are looking for a report as per attached format.    

Date: Tue, 29 Mar 2016 22:33:58 -0700

**Comment by harshit-30** [comment]
Please create a new issue if the problem persists.

**Comment by dj12djdjs** [comment]
I think this is still a problem. 
This image is of Accounts Payable report. It is showing outstanding balance of $626.33 (CAD)
However, this supplier bills us in EUR.
![image](https://user-images.githubusercontent.com/29856401/140394754-0b73f42d-0cb7-4ceb-8a77-74f7891d1eca.png)

You can see the ledger these two invoices are fully paid off.
![image](https://user-images.githubusercontent.com/29856401/140395171-3ba21506-80bf-4781-90a7-9e2387113588.png)

I think it should show the balance owing in the billing currency of that supplier?
