### ISSUE TITLE
small bugs in multi currency purchase receipt.  

### ISSUE THREAD

**Issue by fderyckel** [frappe/erpnext#4911]
I have a supplier that is in Zar (Currency from South-Africa).  My company is in Zk (Currency from Zambia).  I did a purchase receipt from that supplier in South-Africa.  
In my purchase receipt report, it shows the wrong the currency on the column "Grand Total".  It shows our company currency, instead of our supplier currency.  
![screen shot 2016-03-01 at 07 54 19](https://cloud.githubusercontent.com/assets/7240992/13440417/94a74f8a-dffa-11e5-9e79-9f7de0553d55.png)

**Comment by PratibhaPatil** [comment]
As per my Knowledge, In currrency list, ZAR currency is disable, firstly you must enable that.

**Comment by fderyckel** [comment]
Hi @PratibhaPatil ,
No,  Zar is enabled as I need it as well for the other documents.  
The amount in Gran Total are the one in Zar, but the symbol is wrong.  It is ZK when it should have been Zar.

**Comment by nabinhait** [comment]
Select Currency column, it should show correct symbol.
