### ISSUE TITLE
Last Purchase Price to be displayed in Purchase Order Item

### ISSUE THREAD

**Issue by Devens** [frappe/erpnext#4913]
Last Purchase price (Based on Purchase Order/Invoice) should be displayed in Purchase Order Item. 

It's a vital information while finalizing (Submitting/Approving) PO.

**Comment by graphskill** [comment]
We would agree, but perhaps more than just the last purchase price. We would like to see the purchase history prices - perhaps the last 10 prices

**Comment by rmehta** [comment]
- [ ] Add a column "last purchase rate" in pricing section
- [ ] Fetch last purchase rate `get_item_details`

**Comment by graphskill** [comment]
@rmehta 
Thanks for the reply. Unfortunately I have no idea what that means. Can you give me some more detailed instructions

**Comment by vjFaLk** [comment]
@graphskill Ha, sorry for the confusion. That's a checklist for our reference.

**Comment by graphskill** [comment]
OK, so nothing for us to do at this stage

**Comment by Devens** [comment]
Whether this is implemented? If not, when expected? If yes, Please suggest how does it work (as we could not find it out).

**Comment by Devens** [comment]
@rmehta - Hello. Any update on this...

It's very important information to take decision on every PO. 

![untitled_clipping_092816_115303_am](https://cloud.githubusercontent.com/assets/10671911/18902684/1fc8dc4c-8572-11e6-8edc-2b4720b8d2ce.jpg)

**Comment by rmehta** [comment]
@Devens get a freelancer to do this?

**Comment by Devens** [comment]
@rmehta - Ok. Thank you. 

It is really so time consuming? In fact, I tried checking as the tasks are already generated. Sorry, for the followup.

**Comment by rmehta** [comment]
too many things in the pipeline as of now.

**Comment by Devens** [comment]
Could you please suggest a freelancer, if this is not in priority list?

**Comment by rmehta** [comment]
Add it to https://community.erpnext.com/jobs (?)

@vjFaLk do you want to take a look?

**Comment by vjFaLk** [comment]
I did have a look and messed around with the code previously, I was able to make it work on the button press, but getting it to work on Item select turned out to be a more difficult task than I imagined, my JS is pretty rusty. I see @Devens has made a job posting, I'll give it a go tomorrow and just contribute back if I find success.

**Comment by shreyashah115** [comment]
#10897
