### ISSUE TITLE
take file and database backup 

### ISSUE THREAD

**Issue by me2ne** [frappe/erpnext#4917]
Hello
I have ERPNEXT in my local server , how i can't take daily backup from database and files , dropbox not work for me ,because i think my server is behind NAT .
there is any option in UI to take daily backup of database and files or send backup to NAS ( FTP ) ?
even there is no option to download backup manually in UI ?
Regards

**Comment by rmehta** [comment]
There is no option in the UI. To take a backup you can do

`bench --site sitename backup`
