### ISSUE TITLE
Feature Request - OFX import into bank/checking accounts

### ISSUE THREAD

**Issue by HeneryH** [frappe/erpnext#4918]
I really need to be able to pull credit card downloads from my bank.  Entering them all in manually is unworkable for me.

Here is sample code from Gnu Cash
https://github.com/Gnucash/gnucash/tree/c3e054a96c68e8398dc0efcb6718fd719621939a/src/import-export/ofx

**Comment by rmehta** [comment]
Thanks, there seem to be a couple of python parsers too:

https://pypi.python.org/pypi/ofxclient/

https://pypi.python.org/pypi/ofxparse

Can you try these? Unfortunately none of the banks I have support this format.

**Comment by HeneryH** [comment]
I'll try it out.  FYI - OFX is an open standard format.  Quicken has added
a few fields and charged a license fee to banks and the result is QFX.  I
suppose that the OFX tool should work fine for QFX too just ignore the
extra Quicken fields.

**Comment by strixaluco** [comment]
I guess it's better to close this as duplicate and continue at #5903

**Comment by jboilesen** [comment]
@strixaluco This issue was closed as duplicate but the issue wasn't solved. OFX file import was not considered in the bank reconciliation enhancement #5903

**Comment by strixaluco** [comment]
@jboilesen Thanks for pointing this out, issue is reopened.

**Comment by jboilesen** [comment]
@strixaluco do you know when will this feature be assigned / developed?

**Comment by strixaluco** [comment]
I'm sorry, but don't have any info on this.

**Comment by jboilesen** [comment]
@rmehta is there anything I can do to help this development?

**Comment by rmehta** [comment]
@jboilesen pay someone? (plug: https://erpnext.com/support)

**Comment by jboilesen** [comment]
@rmehta I already tried that approach, contacted sales, they contacted development but they didn't even know what OFX files are (and asked for some OFX example files in order to "estimate effort, hours and costs").

Still, this feature is missing since 2016 (I wasn't the first to ask for it) and this is essential for ANY ERP.

If you are trying to make ERPNext a serious competitor for SAP or Odoo you really should care about this without the need for your "paying" community to make it happen.

**Comment by jboilesen** [comment]
@rmehta  Odoo import ofx files: https://www.odoo.com/documentation/user/13.0/accounting/bank/feeds/ofx.html

**Comment by harshit-30** [comment]
@jboilesen let me know if you want to sponsor this feature.

**Comment by harshit-30** [comment]
Kindly create a new issue you'd like to have this feature in the upcoming version.
