### ISSUE TITLE
Batch with same id cannot be created for different items.

### ISSUE THREAD

**Issue by nbalauro** [frappe/erpnext#4924]
Unable to save duplicate batch ID with different item. We produce different items on separate machines concurrently with same batch id. Batch or lot is used to identify a specific production run/datetime,

**Comment by nbalauro** [comment]
Solved this by modifying the autoname function. The issue was due to the primarykey being generated to index the batch was the autoname. This creates unique key errors even though the batch_id and item_id are different, because the autoname is generated from the batch_id.

At the database level the uniqueness should atleast be enforced across both keys (item and batch). By changing the autoname to generated based on both the item and batch_id satisfies the unique index.

IMO the proper way to model this relationship however is to have a one-to-many relationship from batch to item allowing a batch to be related to multiple items, instead of replicated batch_ids and enforcing uniqueness across what is essentially a compound primary key(batch and item).

**Comment by intelliant01** [comment]
@nbalauro Could you please share the exact code change you have done to batch.py? I seem to have run into a similar situation and would appreciate if your exact changes can help solve my situation.
