### ISSUE TITLE
Mobile App Doesn't recognize public port

### ISSUE THREAD

**Issue by MrOmega** [frappe/erpnext#4928]
Accessing ERPNext throughout port-forwarded URL has been achieved successfully while can not access the same server by using the mobile app; Please correct.
Note: Server Address as HTTP://ServerIP:Port

**Comment by Zlash65** [comment]
It should work. I use my local instance for testing all the time `http://my_ip_address:8000`

Closing this issue for now, let me know if i got this all wrong and the issue still persists.
