### ISSUE TITLE
Quotation Status - Cancel

### ISSUE THREAD

**Issue by Devens** [frappe/erpnext#4929]
Many times, we prepare quotation, but we cannot send due to one or other issue. We still need to keep it in our record but can't submit (or keep in draft mode, as It will be displayed on top every time). 

Hence, we suggest to have a status "Cancelled" for Quotation also.

**Comment by rmehta** [comment]
- [ ] Add 'Closed' button along with lost
- [ ] fix 'Lost' dialog to show "Primary" button on the top bar

**Comment by cgpurbaugh** [comment]
Submit, then cancel.
