### ISSUE TITLE
Feature Request - Addition of option in Account type "Is a non cash account"

### ISSUE THREAD

**Issue by wajiman** [frappe/erpnext#4940]
i was wondering whether if we could include the option is a non cash account under the new account adding option in chart of accounts. if this is checked, it will automatically be added back in the cash flow as non cash items are needed to be added back into the cash flow

As per IAS (International Accounting Standards) - 7 Cash flow format is as follows:

**Net profit for the year**

**Adjustments:**
Depreciation 
Amortization of intangibles and other non current asset  (non cash expense account, here the expense is incurred but the cash is not paid for it. if non cash option checked then current year expense will be automatically taken in the cash flow)
Provision for doubtful debts (is non cash account)
(Profit) / Loss on sale of fixed assets 
Provision on employee'e end of service benefits (is non cash account)
Add tax expense
Add interest expense
Operating profit before changes in working capital changes

**Working capital changes:**
Changes in Inventories
Changes in Trade receivables and other assets
Changes in related party balances
Changes in trade payables and accruals
Cash flow from/( used ) operating activities
less tax paid
less interest paid 
Employees end of service benefits paid
**Net cash flow from (used) operating activities**

**Cash flow from investing activities**
Purchase of Property and equipments
Purchase of intangible assets
Payment for Leasehold right over land
Proceeds on sale of fixed assets
Investment in subsidiaries
**Net cash used in Investing activities**

**Cash flows from financing activities**
Net addition to loans/ Repayment of loans
Dividend paid during the year
**Net cash from financing activities**

**Net Increase /(decrease )in cash and cash equivalents**
Cash and cash equivalents- beginning of year
**Cash and cash equivalents- end of year**

There are many more variables which i cant seem to remember now but this is the most standard format

Description:
1. Under the "Adjustments" all non cash transactions, such as depreciation and provisions expenses for the year are added back and any profit on sale of fixed assets is subtracted and loss added back. Operating profit before working capital changes in the total of net profit plus the adjustments.
2. Under "Working Capital changes", increase in inventory i.e difference between the closing inventory balance of prior year and this year, if its an increase it is subtracted as this shows cash has gone out to purchase the inventory. In receivables and other assets if its a decrease it is added as you received money due to which they decreased. We again take the closing balance of the last year and subtract it from this year's balance. Changes in related party is the same thing, it is just transactions between related group companies. In trade payables, an increase is added and vice versa, as this shows cash has been retained rather than giving it out.
3. Under "Cash flow from/( used ) operating activities" we add "Operating profit before changes in working capital changes" + "Working capital changes"
4. Then we just deduct the tax paid, and gratuity paid then calculate the remainder and show it in "Net cash flow from (used) operating activities"
5. Under "Cash flow from investing activities", any activity that requires investment i.e cash outflow, is deducted for fixed assets and under "Proceeds on sale of fixed assets" total amount an asset is sold for is displayed. Under "Net cash used in Investing activities", it is the total for this section only.
6. Under "Cash flows from financing activities", any addition to loan is treated as addition as cash increases and repayment as reduction. Dividend is also treated as a reduction. If shares are issued then cash is received which is treated as an addition. Under "Net cash from financing activities" we just calculate the total of this individual section.
7. Under "Net Increase /(decrease )in cash and cash equivalents" we add "Net cash flow from (used) operating activities" with all the section totals. Then We take the total of closing cash+bank balance of last year and add the "Net Increase /(decrease )in cash and cash equivalents" which should give us the closing cash+bank balance which should be equal to the balance displayed in the balance sheet for cash and bank.

**Comment by mhbu50** [comment]
+1

**Comment by harshit-30** [comment]
Please create another issue if it is not included in v13.10.
