### ISSUE TITLE
Issues when emailing quotation or sales order

### ISSUE THREAD

**Issue by sudharsan77** [frappe/erpnext#4953]
Hi,
   When I generate a quotation and print it within ERPnext, the quotation is displayed correctly with Logo on the Letterhead, but when it is emailed the logo goes missing from the letter head. Also the Total and other fields below the table are misaligned. I am using the same standard template for the quotation. I am attaching below the two quotations, first the emailed version and the second the printed version in pdf format.
[QTN-00001.pdf](https://github.com/frappe/erpnext/files/165349/QTN-00001.pdf)
[QTN-00001_printed.pdf](https://github.com/frappe/erpnext/files/165350/QTN-00001_printed.pdf)

Sudharsan

**Comment by c0mputerking** [comment]
I am having a similar issue

**Comment by rmehta** [comment]
Please share your letterhead URL on https://discuss.erpnext.com. Your letterhead image most probably has relative links that are not accessible outside erpnext
