### ISSUE TITLE
Stock Balance Report Broken

### ISSUE THREAD

**Issue by cgpurbaugh** [frappe/erpnext#4954]
With latest update, cannot see stock balance report except for specific items, or specific warehouse.  Can no longer see all items in all warehouses.

**Comment by anandpdoshi** [comment]
This is not broken but design change. You have to filter by item or warehouse. Otherwise the report takes a lot of processing which can be easily saved with filters. Filtering by item or warehouse solves almost all use cases.

**Comment by cgpurbaugh** [comment]
In our system, because locations within warehouses are not a feature, all of our locations are stored as warehouses. for example, Asile D10, Pallet Rack K, Shelf 2 is D10K2, which is stored as a warehouse, D10K2 - MC.  This change prevents the generation of a Stock Balance Report.

**Comment by anandpdoshi** [comment]
Okay we missed that :(

Sure we will make filters non mandatory. But you will have to go through the trouble of clicking Refresh to load the report. This report is pretty resource hungry and it best load when the intention is firm ;)

Okay to wait till tomorrow?

**Comment by cgpurbaugh** [comment]
Ya, that's fine.  Thanks :)
