### ISSUE TITLE
Lead Status Update on Quotation

### ISSUE THREAD

**Issue by turner-james** [frappe/erpnext#4956]
Selling Lead Status is updated only when Lead is converted into Customer or Opportunity. We also need a the Lead status to change from "open" to "converted" when a Quotation is created from the Lead.

**Comment by rmehta** [comment]
@shachiTakalkar can you replicate?

**Comment by shachiTakalkar** [comment]
@rmehta I can replicate this.
The status of the lead changes from lead to open when opportunity is created against that particular lead but the status do not change when Quotation is created.

**Comment by rmehta** [comment]
Lead status changes to "Quotation" after quotation is submitted
