### ISSUE TITLE
Email Retrieval Error

### ISSUE THREAD

**Issue by airzoink** [frappe/erpnext#4960]
> Error in retrieving email.
> Traceback (innermost last):
> File "/home/administrator/frappe-bench/apps/frappe/frappe/email/receive.py", line 174, in retrieve_message
> msg = self.pop.retr(msg_num)
> File "/usr/lib/python2.7/poplib.py", line 232, in retr
> return self._longcmd('RETR %s' % which)
> File "/usr/lib/python2.7/poplib.py", line 167, in _longcmd
> return self._getlongresp()
> File "/usr/lib/python2.7/poplib.py", line 152, in _getlongresp
> line, o = self._getline()
> File "/home/administrator/frappe-bench/apps/frappe/frappe/email/receive.py", line 403, in _getline
> ret = self.super.getline(self, _args, *_kwargs)
> File "/usr/lib/python2.7/poplib.py", line 375, in _getline
> self._fillBuffer()
> File "/usr/lib/python2.7/poplib.py", line 365, in _fillBuffer
> localbuf = self.sslobj.read()
> File "/usr/lib/python2.7/ssl.py", line 260, in read
> return self._sslobj.read(len)
> File "/home/administrator/frappe-bench/env/local/lib/python2.7/site-packages/billiard/pool.py", line 235, in soft_timeout_sighandler
> raise SoftTimeLimitExceeded()
> SoftTimeLimitExceeded: SoftTimeLimitExceeded()

**Comment by rmehta** [comment]
Seems to be fixed by TimerMixin. Please re-raise if it happens again.
