### ISSUE TITLE
Accounts receivable report - Line for total changes postion with sort order

### ISSUE THREAD

**Issue by vrms** [frappe/erpnext#4965]
I am referring to this report:   > Accounts > Main Reports > **Accounts Receivable**
Apparently there is a little bug with the sorting

let's say you have 4 Sales invoices there from totally 2 customers and you want to see all Sales invoices, sorted by customer

**current behavior**
you see a line per Sales Invoice and the total on the bottom but as soon you change the sort order (i.e. by customer name instead of sorted by date posted/due [which is the default]) the total line also changes position from the bottom (where it should be) to the top (because the customer name column is empty)

**expected behavior**
The total line never changes it's position (at the bottom) no mater how you sort the sales invoices in this Accounts Receivable Report

**Comment by PawanMeh** [comment]
Unable to replicate this in v11, kindly re-open with screenshots if the issue still persists.

![ar_report](https://user-images.githubusercontent.com/20460498/47411269-c923f800-d785-11e8-9ec2-2fa968894cd3.gif)

**Comment by nakul80** [comment]
Almost all reports have this issue. I can see its persisting since 2018 atleast. Even gross profit report goes completely haywire when sorting by gross profit amount. all the headers get clubbed and total line comes to the top.. extremely disruptive bug.
