### ISSUE TITLE
email account automatically disable incoming option and assigned to all users

### ISSUE THREAD

**Issue by omnison** [frappe/erpnext#4968]
email account automatically disable incoming option and assigned to all users

If i setup again email account to enable incoming and delete all users assigned, and few days after, same issue happen again. 

when this issue happen, every user will receive the email below:
New Message

_

You have a new message from: Administrator

A new task, Email Account: Support, has been assigned to you by Administrator.

Invalid Mail Server. Please rectify and try again.

Login and view in Browser

_

**Comment by omnison** [comment]
how to make email account not disable incoming function and do not assigned to users automatically?

**Comment by anandpdoshi** [comment]
Hi. You need to debug your incoming mail server. There seems to be some connectivity issues with your email server.
