### ISSUE TITLE
'In List View' not allowed for type Image in row 12 when adding Image View to Item List View

### ISSUE THREAD

**Issue by kevzzz** [frappe/erpnext#4987]
When I try to add ImageView in Item List view I add this message:
_'In List View' not allowed for type Image in row 12_

**Process:**
1. Select Customize Form
2. Look for editing Item form
3. Select line 12 Image view > check "In List View"
4. Click Done then Update

**Config:**
Installed Apps
ERPNext: v6.25.5
Frappe Framework: v6.26.4

I tried to do an update just before to post this issue.

Regards

**Comment by strixaluco** [comment]
If I understood you correctly, then you can use the "In image view" flag in ERPNext v7: https://github.com/frappe/frappe/pull/1767 and https://github.com/frappe/frappe/pull/1883
The feature probably won't get backported to v6.

**Comment by jwrober** [comment]
Old...
