### ISSUE TITLE
bench update ,and pending in updating mandrill_integration

### ISSUE THREAD

**Issue by omnison** [frappe/erpnext#4989]
Last login: Wed Mar 16 09:07:12 on ttys000
Gavin-MacBook-Pro:~ gavin$ ssh root@128.199.200.6
root@128.199.200.6's password: 
Last failed login: Wed Mar 16 01:02:53 EDT 2016 from 185.110.132.54 on ssh:notty
There was 1 failed login attempt since the last successful login.
Last login: Wed Mar 16 01:02:46 2016 from bba424245.alshamil.net.ae
-bash: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory
[root@123 ~]# bench update
INFO:bench.utils:setting up sudoers
Already up-to-date.
Requirement already satisfied (use --upgrade to upgrade): Pillow in ./env/lib/python2.7/site-packages
INFO:bench.app:pulling frappe
From https://github.com/frappe/frappe
 * branch            master     -> FETCH_HEAD
Already up-to-date.
INFO:bench.app:pulling erpnext
From https://github.com/frappe/erpnext
 * branch            master     -> FETCH_HEAD
Already up-to-date.
INFO:bench.app:pulling mandrill_integration
From https://github.com/frappe/mandrill_integration
 * branch            master     -> FETCH_HEAD
Already up-to-date.
INFO:bench.app:pulling mankem
From https://github.com/sbktechnology/mankem
 * branch            master     -> FETCH_HEAD
Already up-to-date.
/home/frappe/frappe-bench/env/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/home/frappe/frappe-bench/env/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Requirement already up-to-date: pip in ./env/lib/python2.7/site-packages
Migrating site1.local
Updating frappe                     : [========================================]
Updating erpnext                    : [========================================]
Updating mandrill_integration       : [========================================]

**Comment by anandpdoshi** [comment]
The progress bar shows mandrill integration syncing is done. It is your custom app that's stuck.
