### ISSUE TITLE
Report for Activity log of a certain user

### ISSUE THREAD

**Issue by Mahi-tsc** [frappe/erpnext#4990]
Would like to have a report format for the activity log of certain users.

**Comment by asbasawaraj** [comment]
+1

**Comment by Devens** [comment]
+1

**Comment by applepipe** [comment]
+1

**Comment by Devens** [comment]
Very much required. In fact, I have suggested filter by user for Activity Report. This can be very useful.

**Comment by ankush** [comment]
Use the report builder. Don't see a need to have a script report for this.
