### ISSUE TITLE
Price List Rate and Discount on Price List Rate not appearing in Sales Order

### ISSUE THREAD

**Issue by justinlusg** [frappe/erpnext#5001]
![image](https://cloud.githubusercontent.com/assets/12539216/13854050/8dd7b8c8-eca4-11e5-826b-26addd988af7.png)

![image](https://cloud.githubusercontent.com/assets/12539216/13854053/933d9a80-eca4-11e5-8615-93db13c2f96e.png)

![image](https://cloud.githubusercontent.com/assets/12539216/13854059/9c1f8fd2-eca4-11e5-8878-1a2ab0c47f69.png)

I have set the setting to show in print format, and also ensured that the values are valid. However, in the print format it does not appear.

**Comment by nabinhait** [comment]
Are you using the latest version?

**Comment by justinlusg** [comment]
@nabinhait updated and it's resolved. thanks!
