### ISSUE TITLE
iOS app #desk won't display any modules since redesign

### ISSUE THREAD

**Issue by superlack** [frappe/erpnext#5007]
Using the ERPNext app on the iPhone, typically home would display the applications that should be visible to the user (eg. Accounts, Projects, etc..).  Since the redesign of erpnext, the app only displays a blank page when "Home" is clicked.  The server is operating fine, and other info is displayed when it's navigated to (confirmed by navigating to the user settings with the sidebar)

**Comment by rmehta** [comment]
@superlack fixed. Thanks for reporting

**Comment by superlack** [comment]
Just like that! Thanks!
