### ISSUE TITLE
Installation Note Time Format Wrong/Error

### ISSUE THREAD

**Issue by justinlusg** [frappe/erpnext#5014]
![image](https://cloud.githubusercontent.com/assets/12539216/13897771/1bd92e8c-edf8-11e5-8195-3b18073c4168.png)

The Time Format can it be changed to just display seconds/minutes?

**Comment by pratu16x7** [comment]
Fixed as of now. Closing.

![screen shot 2017-05-15 at 10 48 26 pm](https://cloud.githubusercontent.com/assets/5196925/26070039/b6a38204-39c0-11e7-9db1-b81cfca91989.png)
