### ISSUE TITLE
When click Add New Row in Delivery Note it goes back to desk top and create one row

### ISSUE THREAD

**Issue by mkumar9699** [frappe/erpnext#5015]
When click Add New Row in Delivery Note it goes back to desk top and create one row in item table and row cannot be clicked  to edit or romove.

It is serious issue.

Thanks
Mithilesh Kumar

**Comment by vjFaLk** [comment]
Hi, I cannot recreate this. Is it still an issue?

**Comment by anandpdoshi** [comment]
@mkumar9699 any error in the browser's console?

**Comment by mkumar9699** [comment]
length property of against sales order says invalid, removed to fix this issue.

thanks
Mithilesh
