### ISSUE TITLE
Feature Request - Purchase Receipt>Row Editor>Accepted Quantity field

### ISSUE THREAD

**Issue by Tropicalrambler** [frappe/erpnext#5017]
When one is entering Items in the Row Editor for a new Purchase Receipt, after you have entered the item code, as you TAB from the **Received Quantity** field to the **Accepted Quantity** field, the cursor for a moment "selects all" in the field so that just typing the number changes the amount in that field, but it quickly switches to a cursor for data entry at the end of the field.  This means one must press  CTRL+A  or CMD+A  to select the entire data again, and type in the new amount.

In the spirit of simplicity and speed, this little move adds another keystroke which means one more second, to the data entry which is already blazing fast.   I am using Google Chrome when this happens.  I do not know if this is a bug or a feature request, but it would be great to have it be consistent.   This does NOT happen when an item code has NOT been previously entered, which means that the feature exists, it just seems that the code is missing something.

**Comment by PawanMeh** [comment]
Could you re-check this on the latest release. Kindly re-open with relevant screen shots attached if this is still an issue.
