### ISSUE TITLE
Feature Request - Stock>Purchase Receipt>Grand Total Section> In Words Read only field

### ISSUE THREAD

**Issue by Tropicalrambler** [frappe/erpnext#5018]
I use ERPNext in english, because of personal preference.  However, the country where I work uses spanish as the official language. I could most certainly go ahead and select Spanish as my language for using ERPNext, and so when I create a **Purchase Receipt**, in the Grand Total section, the field **"In Words"** will be displayed in spanish.  The thing is, what happens if I want to use ERPNext in english, but have the information **print** in spanish or be stored in spanish, or any other language for that matter?

An option for "Currency words language" would be a great addition as a feature to ERPNext.

I visualize someone who speaks and types mandarin, but wishes to save or print a purchase receipt whose currency amount **In Words** is in english.
Is this automatically selected according to the country of the supplier for the purchase invoice?

**Comment by rohitwaghchaure** [comment]
Hi Tropicalrambler

You can print document in any language, select language from drop down next to standard on print preview.

![screen shot 2016-03-21 at 12 57 23 pm](https://cloud.githubusercontent.com/assets/8780500/13912605/00edec5c-ef65-11e5-9929-5a5bb4c101d6.png)

You can create your own translation, goto Setup -> Custom Translations -> New Translation

**Comment by anandpdoshi** [comment]
@rohitwaghchaure I think what he is referring to is that when language is changed, in words is not changed.

I am in favor of deprecating `in_words` altogether. In words just acts as a verification, which is obsolete in the digital era, since no one enters the amounts manually.

**Comment by Tropicalrambler** [comment]
@anandpdoshi @rohitwaghchaure   I agree that the "in_words" might be obsolete in the digital era, but legally speaking, here where we operate, the invoice MUST have the currently total amount printed in words, so deprecating it could take some functionality out of ERPNext. I suggest you leave the feature, but allow a checkbox in the setup area such as enable "print break"  or "display POS", etc.   so you can customize whether you show this or not.

My case is this
Legal language for printing currency total in words:  X
Language with which I operate ERPNext:  Y
Country's official language: X

So, the idea is to enable selecting language with which currency total in words is printed.

Any suggestions as to how to work this on my own?

**Comment by anandpdoshi** [comment]
@Tropicalrambler ideally the amount in words should be set in before_print method. For example: https://github.com/frappe/erpnext/blob/develop/erpnext/stock/doctype/delivery_note/delivery_note.py#L64
