### ISSUE TITLE
Feature Request - Conversion Factor Table - predefined table

### ISSUE THREAD

**Issue by Tropicalrambler** [frappe/erpnext#5032]
I think that the UOM table is fantastic.  I like the fact that ERPNext supports PER ITEM conversion factors. But I consider that a great addition would be a generic, default table. This way, ERPNext could use the generic conversion factor as priority #1, and where a PER ITEM conversion exists, as is currently the case, use the PER ITEM conversion factor as priority #1. This would allow any conversion factor for a BOM, stock entry, or when entering a purchase receipt.
For example, two units of measure are defined in ERPNext. 
1. "Foot" referring to the English Foot measurement
2. "Metre" referring to the SI unit.

The conversion table would thus house that a "Foot", defined in terms of "Metre" is equivalent to 0.3048 Metre
Source: https://en.wikipedia.org/wiki/Foot_(unit)

Electrical wire is purchased from supplier, usually, by "Metre".   But the warehouse or field operator requires amount in "Foot" in Material Request (due to cultural and idiosincratyc behavioral habits that die hard, or is impractical to request change). When the purchase order is printed, the measurement is shown in "Metre", and stated that amount originally was expressed in "Foot".

The problem is that having a PER ITEM definition forces you to find the conversion factor each time, where some factors would be ideally pre-loaded into the system, with the SI and worldwide standards pre-loaded by ERPNext and the capability to define or customize the units.

**Comment by Tropicalrambler** [comment]
@anandpdoshi I am willing to sponsor this, as I do not have the luxury of time, since i am also involved in trying to setup another module for ag. Who wants to program it?

Let me know.

**Comment by agritheory** [comment]
I was just looking for something similar and discovered [pint](https://github.com/hgrecco/pint). Perhaps this will help?

**Comment by Tropicalrambler** [comment]
So here is a major proposal on how to structure UOM and conversions.

# UOM family relationships
- [ ] UOM Doctype should have Parent/Child relationship, just as an account has a parent. Changing the family of the UOM will break the conversion to be specified later. An example of what I propose:

## Basic conversions (parent)
### Length (parent UOM category)
- millimeter (child UOM)
- centimeter (child UOM)
- inch (child UOM)
- meter (child UOM)
- kilometer (child UOM)
### Area (parent UOM)
- acre (child UOM category)
- hectare (child UOM)
- square inch (child UOM)
- square meter (child UOM)

## Conversion Table (DocType)
- [ ] DocType creation
The conversion table shows all the available parent UOM and their child UOM.  Each parent UOM will highlight the pre-selected (or user specified) **Master Unit**.  Each parent UOM filter can contain one and only one valid Master UOM at a time.  All other units must be specified in terms of the Master unit. An example of all the units within the parent "Length" unit, clarifies:

### Length (parent)
**Unit ID | Abbreviation | Conversion Factor | Is Master Unit | Must Be Whole Number | Description**
**meter   |       m      | 1 | YES | NO | It is the basic unit in SI system...**
**millimeter | mm | .001 | NO | NO | 1/1000 of a meter**
**centimeter | cm | .01 | NO | NO | 1/100 of a meter**
**inch | in | .0254 | NO | NO | international inch is exactly 25.4mm**
**foot | ft | .3048 | NO | NO | International foot, about ¼ to ⅓ meters**

## Add fields to UOM DocType

To add this functionality, each UOM DocType needs to have these fields added:
- [ ] Parent category  (Length, Area, Volume, etc.) Link to Parent Field.
- [ ] Abbreviation (Data.  Could be auto-generated from name, or manually entered)
- [ ] Conversion factor (Float number, expressed in terms of the master unit for that parent category)
- [ ] Is master unit (Check field, if selected, all other fields will have to be expressed in terms of this field
- [ ] Description (Rich Text field describing this particular unit)
- [ ] External Source (Hyperlink field, for more information about the UOM, such as Wikipedia, etc.)

## Add behavior elsewhere based on these fields
- [ ] **Master field behavior**:  If you wish to change the master field, you must first deselect the master field in the master UOM and save it. Then you open the desired Master UOM and check the field "is master unit".  A message should show preventing you from changing the master field if one is already defined. A confirmation dialogue should appear before user changes the master unit. Upon confirmation, all UOMs in the parent category should have, programmatically, their conversion factors changed and saved in terms of the new Master Unit.

- [ ] External Source Behavior:  A user enters a link to a wikipedia article or similar containing other sources confirming the unit conversion factor. A read-only, clickable link should appear in the UOM DocType which opens in a new tab, allowing the user to study more information about that UOM, if desired.

- [ ] **Purchase Item, Sales Invoice Item, Quotation Item, etc. DocType Behavior**
When user is adding items to a purchase or sales invoice, in the expanded view (when you click the arrow in the child table to add items), in the Quantity and Rate section, user can specify Quantity, and then UOM. If the UOM specified is different than Stock UOM, but already has a conversion specified in UOM parent, the conversion factor should automatically show up.

Now, I do have a question:  Would it be better to stick to the current form, where conversions are ultimately defined within Item DocTypes?

If we continue with the Item DocType, when you select conversion units in the **Units of Measure** section and table in the **Item DocType**, if the UOM being added is from the same parent as the Stock UOM, the number from the conversion table should immediately show up.  Item then is saved with pre-set unit conversions.

## Modify Module Views and miscellaneous
- [ ] Change **Setup** > **Stock** > **Unit of Measure (UOM)**  so that it goes to a "configuration-like" DocType.  This DocType should thus contain the defined UOMs as a child table.  Child table can be filtered according to parent unit, and user can also defined units there in terms of the master unit (which appears boldfaced)

- [ ] Add conversion table and common units as a predefined item when installing ERPNext

- [ ] Allow users to submit common conversions sets, similar to the way Chart of Accounts or translations can be submitted.

- [ ] Direct conversion tool: Assume the user simply wants to use the conversion table for a one-time conversion. He can simply enter the UOM number, select the origin UOM, the target UOM, and ERPNext would show the output UOM conversion, for easy reference, copy / paste, etc. It could also help quickly verify and validate that conversions are operating properly.

## Proposed list of parent categories
- [ ] The full list of proposed parent categories are as follows:

1. Length
1. Area
1. Angle
1. Speed
1. Mass
1. Volume
1. Time
1. SI Prefixes
1. Temperature
1. Luminance
1. Frequency and Wavelength
1. Electrical Charge
1. Electric Current
1. Electrical Conductivity
1. Magnetic Induction
1. Agriculture (custom)  (percentage and parts per million conversions)
1. Pressure
1. Force
1. Energy
1. Power
1. Density
1. Dynamic Viscosity

Screenshot of the program that inspired these feature requests:
![kamlexunitcnvtr](https://user-images.githubusercontent.com/16600935/32398997-5cf29964-c0b8-11e7-9392-29ccceb56343.gif)

## KML conversion File from freeware Windows converter - Kamlex (for reference)
I am attaching a file from a freeware converter called kamlex, which I used frequently, in its native kml format. It was only available for Windows, and even though you can still download it, it seems the developer no longer maintains it. The beauty of that converter was that you could define your own unit conversions in terms of existing conversions. This was useful for customized in-house solutions. It was also useful because it contained a comprehensive list of existing conversions, with links to the sources confirming the conversion factors. 

I believe no schema is necessary, it is a simple tree/node structure
[2017-ConvertData.txt](https://github.com/frappe/erpnext/files/1442681/2017-ConvertData.txt)
