### ISSUE TITLE
Data import Tool

### ISSUE THREAD

**Issue by Atheryl** [frappe/erpnext#5038]
Firstly I would like to thank you guys for the great work you have done on this tool.

 I have an issue with the data import tool. Basically my sales want to access the leads/quotations import tool so I have add import entity into the sales user and manager role.

 I successfully see the "import" button in the menu under CRM->Leads but when click on it I get a "Not permitted" error. If i set theses users with the role "System Manager" they can access.
 I have read all the permissions of the "System Manager" role but I haven't find anything that block/allow the data import tool ...

 Am I missing something ?

**Comment by nabinhait** [comment]
Seems like you have not given permissions to sales user/manager for "Data Import Tool" page.
