### ISSUE TITLE
 reorder level of stock

### ISSUE THREAD

**Issue by SonaliBudhrani** [frappe/erpnext#5045]
We want the reorder level of stock to be a function of previous 4 months sale minus already placed purchase order Quantity (not yet received).

**Comment by bcornwellmott** [comment]
This sounds like a customization, as opposed to a github issue with the development. Every user will have a different preference for what the reorder level of stock is, and that is settable by item. All you need to do is write a script that updates the reorder level based on the last 4 months of sales.

**Comment by nabinhait** [comment]
@SonaliBudhrani Please raise customization related query in community.erpnext.com (for paid development) or in discuss.erpnext.com.
