### ISSUE TITLE
Add support for printing and reading external devices directly such as printers and scales

### ISSUE THREAD

**Issue by pifiu** [frappe/erpnext#5051]
I have mentioned that some additional POS and tighter integration would be good for ERPNext.

Right now when using the POS to print receipts the process is a bit cumbersome instead of quick and efficient. A POS transaction should be able to be done in a couple of clicks, with the majority of those being in terms of making the sale not printing a receipt.

Currently in ERPNext it goes a little something like this:
1. Hit Print
2. Print preview shows up
3. Click Print
3. Browser print preview with printer selection shows up
4. Hit print again
5. Receipt prints.

It should be possible to hit "print" and have it come directly into the printer once the hardware is configured. This is useful for POS thermal printers which print instantly by simply hitting print.

I have explored multiple options:

**Option 1**
QZ used to be jzebra, Due to the deprecation of NPAPI in Chrome a QZ Tray was developed:

https://qz.io/
https://github.com/qzind/tray
https://github.com/qzind/qz-print

QZ offers a free and a premium version, perhaps offer the free one and if the user is interested provide an easy way to change over to the premium version.

**Option 2**
Another option is printnode: https://github.com/PrintNode

This is similar in that you can print directly to the printer or read devices connected to the computer.

**Option 3**
Lastly, another alternative which I think might be the best for erpnext because it would be free of dependencies. This is a solution that currently works with Odoo.

This project https://github.com/csrocha/fpoc-chrome

This is a plugin for chrome to communicate with local printers. It has 2 issue's which I think could be easy to address to work fine in ERPNext. 
1. Replace the connection from Long Pooling connections to websockets
2. Port this https://github.com/csrocha/odoo_fpoc to frappe

Whatever implementation is done, I think this feature would be helpful for a number of reasons and features such as: 
1. POS Receipt Printing
2. Warehouse/Inventory Label Printing
3. Reading external devices such as a scale for weight or other serial devices

Is there any interest in getting this done?

**Comment by mhbu50** [comment]
+1

**Comment by karthikeyan5** [comment]
@pifiu @mhbu50 Support for 'QZ Tray' has been added to the Frappe Framework in PR https://github.com/frappe/frappe/pull/7088. Please that a look at the [ERPNext Raw Printing Documentation](https://erpnext.com/docs/user/manual/en/setting-up/print/raw-printing) to learn more.
