### ISSUE TITLE
Selectively Get Items from Upstream Documents in Transactions

### ISSUE THREAD

**Issue by epochc** [frappe/erpnext#5055]
You are doing a purchase receipt, you use the get items from PO option and pick the PO. Let's say the PO has 25 items (real scenario) and let's say that you are receiving only 1 item (real scenario). Now as you hit Get, all 25 items are pulled into the Purchase Receipt. Now the operator has to painstakingly remove 24 items to receive one item. Is there anyway you can selectively pull items, or make it easier to delete unwanted items?

This could occur in any related transaction - Quotation > Sales Order > Delivery Note > Invoice; Supplier Quotation > PO > GRN > Supplier Invoice.

**Comment by rmehta** [comment]
Fixed in 7.3
