### ISSUE TITLE
Products RSS Feed

### ISSUE THREAD

**Issue by mehighsi** [frappe/erpnext#5056]
We need a RSS Feed with the products listed and managed onto by our  ERPNext system to be published for 3rd party. We have this request from an important prospect (La Redoute) in order to be able to list our products on their market place and get access to a huge potential customers.

When can you help us?

Regards,
Mihai
https://mix.erpnext.com/

**Comment by PawanMeh** [comment]
Kindly check if REST API could work for you. If not, you can re-open issue as per new [guidelines](https://github.com/frappe/erpnext/wiki/Issue-Guidelines)
