### ISSUE TITLE
Get Item from Sales Order in Delivery Note 

### ISSUE THREAD

**Issue by mkumar9699** [frappe/erpnext#5063]
Get Item from Sales Order in Delivery Note.
All items are inserted. Unwanted items have to be deleted.
Suggested Solution

1. After select sales order
2. Display Dropdown of items in sales order
3. Select 1 item and insert
4. Go To Serial 2 again
5. Validate duplicate item selection

I have average more than 10 items in sales order.

Please fix this issue. 

This solution is useful for ALL customers.

**Comment by mkumar9699** [comment]
waiting

**Comment by nabinhait** [comment]
I think this will not help that much. Because you have to click on "get items" for each individual items. This will be cumbersome for those who generally deliver all items at once.
