### ISSUE TITLE
Report: Item view does not reflect field state upon field update.

### ISSUE THREAD

**Issue by Tropicalrambler** [frappe/erpnext#5064]
- [ ] 1. In the Report view, particularly for Item, when you select an existing item field, if you change one of the fields with checkboxes such as "Is Sales Item", clickin update and then close, the field in the report does not show its changed state until a page refresh or reload is done.  May I suggest that the report autoupdate each time, so one can keep track of the items being edited.

**Comment by Tropicalrambler** [comment]
Additional bonus points:  When you enter the Report: Item view, only a certain amount of items are viewable. You click on the 100 or 500 button at the bottom right to increase items displayed. Then, when you refresh, the view returns to the original state with 20 items displayed, and the 100 or 500 buttons must be clicked again. I believe the view state as indicated by the 100 or 500 button should remain as an environment variable even upon a refresh of the page.

**Comment by strixaluco** [comment]
> Then, when you refresh, the view returns to the original state with 20 items displayed, and the 100 or 500 buttons must be clicked again.
This doesn't seem to be an issue anymore, at least on ERPNext: v8.x.x-beta (95233a6) (develop) / Frappe Framework: v8.x.x-beta (eb079e1) (develop).

Can someone replicate the first issue?
