### ISSUE TITLE
submit Job Application, error :Could not find Job Opening

### ISSUE THREAD

**Issue by omnison** [frappe/erpnext#5066]
i create job:http://128.199.200.6/jobs/sales-executive
and when i open this link, and "apply now", and "submit".
popup: Could not find Job Opening: Sales Executive

How to solve this issue?

**Comment by vjFaLk** [comment]
Hi, I'm unable to reproduce this on my setup. Can you tell me what your Job Opening looks like?

**Comment by omnison** [comment]
<img width="1348" alt="2016-03-27 7 53 07" src="https://cloud.githubusercontent.com/assets/7886153/14063764/fd41ccdc-f3f0-11e5-8e60-d4d999d07d2a.png">

**Comment by omnison** [comment]
Please check the job screenshot, once click "see on website", generate link: http://128.199.200.6/jobs/sales-executive
and "apply now", and fill details and then "submit".
Popup: Could not find Job Opening: Sales Executive
<img width="1306" alt="2016-03-27 8 17 49" src="https://cloud.githubusercontent.com/assets/7886153/14063827/73b19b74-f3f4-11e5-9cbd-09669b38e0d9.png">

**Comment by vjFaLk** [comment]
Can you remove the dash from the Job Opening title and try?

**Comment by omnison** [comment]
yes, if remove dash, it is working, but do you have better solution, i think it is one small bug.

**Comment by vjFaLk** [comment]
@omnison Yes, it's a bug, we'll get on fixing it ASAP :)
