### ISSUE TITLE
Opportunity - Status not being changed to Closed (Bug)

### ISSUE THREAD

**Issue by Devens** [frappe/erpnext#5067]
Please look at following screenshot. Opportunity is manually set to "closed". But, status is not being changed to closed. Because of this all such closed opportunities continue to display in report filtered for open opportunities.  

![screenshot_032716_125546_pm](https://cloud.githubusercontent.com/assets/10671911/14064277/38aee1b8-f41b-11e5-993f-97bf973ab08a.jpg)

**Comment by vjFaLk** [comment]
Fixed
