### ISSUE TITLE
how to setup Sales Team and hide others sales leads

### ISSUE THREAD

**Issue by suvapapa** [frappe/erpnext#5068]
I am setting up Sales Team

Team 1
- Sales Mgr 1
-- Sales Guy 1
-- Sales Guy 2

Team 2
-Sales Mgr 2
-- Sales Guy 1
-- Sales Guy 3
-- Sales Guy 4

Team 3
- Sales Mgr 3
-- Sales Guy 2

In Team 3, with the proper setup, is it possible to hide Sales leads of Sales Guy 2 from Sales guy 1 as both are in different teams ? and also hide Sales Leads of Different Managers from each other ?

what will be the right setup ?

**Comment by suryanamha** [comment]
This can be controlled by the authorizations at the role level or may be at user level. for more you may refer to the user manual. 
https://frappe.github.io/erpnext/user/manual/en/setting-up/users-and-permissions/role-based-permissions.html
