### ISSUE TITLE
Issue: Sales funnel not appearing correctly in Firefox

### ISSUE THREAD

**Issue by wajahatid** [frappe/erpnext#5073]
The sales funnel diagram is not appearing correctly on firefox browser. i have not tested it on other browsers.
![salesfunnel](https://cloud.githubusercontent.com/assets/18127463/14091435/f122bb60-f548-11e5-9bf3-9b208d52a3d3.png)

**Comment by nabinhait** [comment]
- [ ] Create the funnel using c3.js

**Comment by vqw** [comment]
+1 for this, Chrome has the same issue

**Comment by vqw** [comment]
Actually we may use this:
https://github.com/jakezatecky/d3-funnel
