### ISSUE TITLE
"Date Change" field is not visible in ToDo (for email alerts)

### ISSUE THREAD

**Issue by Devens** [frappe/erpnext#5079]
We need to check event every day (for eg. if ToDo is overdue by 7 days, it should send alert everyday till it's getting completed). Kindly advise. 

![untitled_clipping_032916_070905_am](https://cloud.githubusercontent.com/assets/10671911/14100955/b6fa1a8a-f5ae-11e5-9b73-a28b13f433e3.jpg)

**Comment by Devens** [comment]
Hello... Any update on this?

**Comment by Devens** [comment]
Hello... Any update on this?

**Comment by rmehta** [comment]
Hey why don't you get it done from someone in the community? Happy to merge.

**Comment by Devens** [comment]
There are certain development on anvil and will come for pull request very soon. 

But, I think this might be already developed (as it's being seen even as hint point). So, I suggested to rectify and put in case there is some issue.

**Comment by rmehta** [comment]
:+1: Its just mind-space. There are so many things on our list and the community is constantly demanding more, that its hard to prioritize which issue to fix. This may turn out to be a simple fix, but digging into it may take a longer time.

**Comment by rmehta** [comment]
This is fixed.
