### ISSUE TITLE
Update Chart of Accounts for all Countries

### ISSUE THREAD

**Issue by dploeger** [frappe/erpnext#508]
For the german market, support of the german chart of accounts called "SKR03" and "SKR04" is crucial.

There are various source where to get these, but the most complete and tested one seems to be the SQL-files from the lx-office-project:

https://github.com/kivitendo/kivitendo-erp/blob/master/sql/Germany-DATEV-SKR03EU-chart.sql
https://github.com/kivitendo/kivitendo-erp/blob/master/sql/Germany-DATEV-SKR04EU-chart.sql

**Comment by aShure** [comment]
Hey there, gentle reminder, as of the latest version the SKR04 still does not seem to be in working condition. Was this closed to signal that there won't be any more work done on this? It's the missing piece why we can't move to ERPnext.

**Comment by nabinhait** [comment]
We have created a portal to build and contribute chart of accounts for different countries by the community members. You can build SKR04 from charts.erpnext.com and contribute to the community.
