### ISSUE TITLE
Feature proposal: "Image view" in the Item list

### ISSUE THREAD

**Issue by strixaluco** [frappe/erpnext#5089]
Greetings.
At my company we are designing and manufacturing handbags. Therefore, for our designers' team it's very important to keep track on the items and review design iterations in a visual manner as a primary kind.

Here is a preliminary draft of the proposed "Image view" feature:
![image view mockup](https://cloud.githubusercontent.com/assets/10875796/14106206/448c5bf0-f5e2-11e5-9b01-13b9e30e3328.png)

I guess all elements here are pretty common for ERPNext users, but there is an addition in a top right corner of the cells: it's a date when the item with current design was submitted for the first time.
One more important feature would be zoomed view, invoked by single click on the image, which will let user ability to have a closer look and see all the details of appearance.

Please express your opinions and ideas on improving the mock-up. Thanks.

**Comment by Devens** [comment]
+1 for image view. It's very similar to POS view. There can be a toggle option for List View & Image View. (we had already suggested this in past).

**Comment by strixaluco** [comment]
@Devens 
> There can be a toggle option for List View & Image View.

Exactly.
And how was your suggestion accepted? Was there any progress?

**Comment by Devens** [comment]
@strixaluco - Perhaps the team was busy in other priority work, so further action could not be taken. But, with suggestion of yours & probably others (as I believe that this feature can be useful for many), this can be shifted to priority list.

**Comment by strixaluco** [comment]
@Devens
For us it's really crucial and we will sponsor implementation.

**Comment by rmehta** [comment]
@strixaluco you can also ask someone in the community to build this, we will be happy to review / merge. Just post at https://community.erpnext.com/jobs

**Comment by strixaluco** [comment]
@rmehta 
Will post job in the list, thanks.

**Comment by strixaluco** [comment]
With https://github.com/frappe/frappe/pull/1767 and https://github.com/frappe/frappe/pull/1883 it can be closed now, I suppose.
