### ISSUE TITLE
HR Module - Salary Structure not updated  (bug?)

### ISSUE THREAD

**Issue by fderyckel** [frappe/erpnext#5099]
Hi Frappe team, 
Employee A is in Dpt. D with Designation "Des".  I am creating salary structure for that employee.  
Now employee A change dpt.  He goes into Dpt. E.  He keep the same salary. So no need to create new salary structure.  
We have changed on employee doc the dpt.  
Unfortunately salary structure is not updated from employee information.  

Any way the two docs can be linked?

Thanks

ALSO still no update on how to link deduction to an account?

**Comment by rmehta** [comment]
[ ] Remove designation field from Salary Structure
[ ] In Salary Slip, set latest designation from Employee
