### ISSUE TITLE
Backup Upload Failed

### ISSUE THREAD

**Issue by emakis** [frappe/erpnext#5100]
Backup Upload Failed

Oops, your automated backup to Dropbox failed.

Error message: 
ESO Electronic Corpoprate Design Erklärungfedba9.png - Traceback (innermost last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_backup/dropbox_backup.py", line 206, in upload_from_folder
    dropbox_client = upload_file_to_dropbox(filepath, dropbox_folder, dropbox_client)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_backup/dropbox_backup.py", line 227, in upload_file_to_dropbox
    size = os.stat(filename).st_size
 UnicodeEncodeError: 'ascii' codec can't encode character u'\u0308' in position 70: ordinal not in range(128)

Traceback (innermost last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_backup/dropbox_backup.py", line 45, in take_backups_dropbox
    if did_not_upload: raise Exception
 Exception
Please contact your system manager for more information.

**Comment by emakis** [comment]
If the problem is in filename characters, please either don't allow special filename characters while upload a file or rename it during the uploading

**Comment by anandpdoshi** [comment]
@emakis not able to reproduce this on my mac. Does this error occur on your server?

**Comment by emakis** [comment]
yes @anandpdoshi, this happens on the server

**Comment by nabinhait** [comment]
@emakis Are you still getting this error?

**Comment by emakis** [comment]
If I remember well that problem caused because some documents named in local language and contained special characters (german umlaut: ü). As soon as I replaced them the error disappeared, but the issue with the special local characters must be resolved

**Comment by rmehta** [comment]
Seems fixed.
