### ISSUE TITLE
Feature Request UOM for Sales

### ISSUE THREAD

**Issue by yashodhanp** [frappe/erpnext#5111]
It would be great to have UOM available for sales invoices, with different Barcodes/SKU and prices for each variant:

For Eg:

PRODUCT : Barcode/SKU
Cup (1pc) :  00021
Cup (Pack 10) : 00022
Cup (Pack 50) : 00023

and so on.  

Regards

**Comment by mbauskar** [comment]
Multi UOM in sales transaction is available from v8.
Closing the issue please reopen if you find any issue in Sales UOM
