### ISSUE TITLE
Add status change in support to communication

### ISSUE THREAD

**Issue by neilLasrado** [frappe/erpnext#5118]
In Support when a user changes status of a document, add a message in communication.

This can be important to track who closed a ticket and when.

**Comment by mbauskar** [comment]
changes can be track using versions for the documents

<img width="717" alt="screen shot 2017-10-16 at 3 32 38 pm" src="https://user-images.githubusercontent.com/11224291/31606620-44779bc6-b287-11e7-89bd-95a0bedcf73d.
