### ISSUE TITLE
Offline mode for PoS

### ISSUE THREAD

**Issue by javieralmancevo** [frappe/erpnext#5123]
All modern PoS systems are capable of working offline in the event that the internet connection drops, so the shop can keep operating and serving the customers, even if in reduced capability. I think there is a general agreement that the ERPNext PoS needs to be updated, not only with offline capabilities, but I believe this is the best starting point as it is the most limiting condition.

So here is a list of the characteristics the new offline capable PoS should have:

- It should be a webapp, which could be both launched in the browser from within ERPNext and also function as a standalone webapp (for Android, iOS, linux, windows, ...).

- Any local data should be stored using html5 local storage facilities. There should be no need to install locally any external database or other program.

- It should follow the minimalist ERPNext style. Any decorations can be added later as customization by users or developers.

- It should tend to use well known and tested javascript libraries and frameworks (f.e. React, Angular, ...) unless fully justified. Also, the ERPNext devs have expressed their prefference for http://electron.atom.io/ .

- The PoS developer should be ready to communicate and collaborate with the ERPNext developers. They have expressed their support for a revamped PoS and are usually very helpful towards developers.

- The application should be able to load in local memory a list of the products, clients, etc... at start-up so in the event of internet failure it can continue to operate. Ideally, it will be able to update only the changes in the database since last synchronization instead of loading all the fields at every start up.

- In online mode, the new sales should be transmitted immediately to the ERPNext server. In offline mode the new sales should be stored locally, marked as unsent, to be sent to the server once the connectivity is restored.

- There should also be the option to export to a file the data of the unsent transactions, so stores with really bad connectivity can synchronize with the server using a usb drive or some other physical medium.

- In online mode, it should keep in sync with the server the amount of each product available. In offline mode, it should allow to sell any product, as it is assumed that if it is being sold in the PoS the client has the product so it is available. Once online mode is restored, it can reconcile the amounts with the server.

(to be updated)

Any suggestions and comments welcomed.

**Comment by fderyckel** [comment]
+1000
Just on your last point ... From a cashier (who is using the POS) perspective, there is no need to know the quantity of product available.  Obviously if somebody comes at the tilt with a beer bottle, that bottle was part of stock.  It doesn't matter at the time of sales if the product was available or not inside the ERP. 
The point of offline capabilities is to have sale uninterrupted by connectivity.  

I would also add another one, (sorry if it sounds as a naive question).  Is there any difference between POOR connectivity and NO connectivity.  What I mean is I don't wan't a line of customers in front of the cashier because it takes time to load the Item name or customer ID, etc.  All of this should happen fast regardless if connection is fast or slow ... It is really frustrating at times when I have to enter stock entries or GRN (Purchase Receipt) and it just take time to load because connection is slow. 
Maybe all the sync should be done in the background instead of instantaneously.

**Comment by javieralmancevo** [comment]
@fderyckel Thanks for the comment. Answering your two points:

>From a cashier (who is using the POS) perspective, there is no need to know the quantity of product available. Obviously if somebody comes at the tilt with a beer bottle, that bottle was part of stock. It doesn't matter at the time of sales if the product was available or not inside the ERP.
The point of offline capabilities is to have sale uninterrupted by connectivity.

Sure, but for example if you use the PoS in a clothing store for a company that has more than one store, it is nice to know the amount you have of a certain model, and in the future it could be added the option to check the stock in other shops, so employees can reserve them. I understand that for certain industries it might not be useful, but for others it is vital. In any case the PoS should always be able to sell an item, both online and offline.

>I would also add another one, (sorry if it sounds as a naive question). Is there any difference between POOR connectivity and NO connectivity. What I mean is I don't wan't a line of customers in front of the cashier because it takes time to load the Item name or customer ID, etc. All of this should happen fast regardless if connection is fast or slow ... It is really frustrating at times when I have to enter stock entries or GRN (Purchase Receipt) and it just take time to load because connection is slow.
>Maybe all the sync should be done in the background instead of instantaneously.

As stated above the products, costumer list and other data will be synched and stored locally. The connectivity is needed to update (obviously) and to send the confirmed sales. But once the data is synched there is no need to reload it for every sale.

Hope that answers your concerns. Add more suggestions if you have any.

**Comment by yashodhank** [comment]
- **Product Search** - Products stored locally for super fast search by title and also by attributes.
  * Filters products by SKU : sku:barcode
  * Filters products by id, eg: selects product id 1002
  * Filters products by category, eg: tools
  * Filters products by category, eg: tools AND searches title for ‘wrench’
  * Filters products by a two word category, eg: Tools Office / Tools Home
  * Filters products by type, eg: Simple or Variable
  * Filters virtual products, eg: True or False
  * Filters taxable products, eg: True or False
  * Filters in-stock products, eg: True or False
  * Filters backordered products, eg: True or False
  * Filters featured products, eg: True or False
  * Filters on-sale products, eg: True or False
- **Barcode Scanning** - Use the barcode hotkey to switch between barcode and normal search.
  * If a search matches the barcode field exactly the product is added to the cart instantly and the search field is reset.
  * Barcode scanning using mobile device camera.
- **POS Only Products** - Designate products as POS Only or Online Only.	
  * Products that are visible both online in web store and in physical store. A POS Only product will be hidden from the online web store and conversely an Online Only product will be hidden from the POS.
  * Ability to enable product for both POS and Web
- **Edit Cart Items** - Change product title, price and tax rate on the fly.
- **Add Shipping** - Add shipping, choose method and set tax rate (override default global).
- **Add Fees** - Add fees and choose a tax rate.
- **Add Customers** - Add new customers during checkout.
- **Park Carts** - Serve multiple customers at the same time.
- **Payment Gateways** - Use any installed ERPNext payment gateway or available methods of payment.
  * Ability to enable disable Payment methods and Gateways for POS, Globally, Store wise etc.
- **Customer Relationship Management** - Quickly update customer details and view previous order information.
- **Reports** - POS vs Online, Sales by cashier, Sales by store, Sales by payment method.

**Comment by sicsrmanic** [comment]
![pos-1](https://cloud.githubusercontent.com/assets/4644125/14231290/139fd424-f99b-11e5-83b2-0d4cf31983a0.gif)
![pos-cart-shipping](https://cloud.githubusercontent.com/assets/4644125/14231293/2e8baa2e-f99b-11e5-8a7b-8c9caf04babb.gif)

**Comment by javieralmancevo** [comment]
@yashodhank All great suggestions that add clarification to what we expect from a PoS. Only two things:

> Barcode Scanning - Use the barcode hotkey to switch between barcode and normal search.
>        If a search matches the barcode field exactly the product is added to the cart instantly and the search field is reset.
>        Barcode scanning using mobile device camera.

This is a needed feature for any decent PoS but I did not want to include it because it adds a lot of work for the developer, meaning increased funding would be necessary for a developer to go for it. My aim now is not to create the perfect PoS, but to fund the development of a basic PoS that can be easily expanded. A good 0.1 version onto which to build more features. It is going to be difficult enough for people to fund this type of development as it is. But if a good PoS system with potential is already there I am sure people will be happy to develop or fund small improvements. Starting and creating a good base is probably the hardest part. So it will help to keep it simple first.

I am open to realistic counter-opinions, but I believe this is the best way to succeed. That said, if enough people are willing to add funds towards having this feature included in version 0.1 then we can consider it. Everybody's suggestions are welcome but obviously the opinions and needs of people willing to contribute will have more weight.

>Reports - POS vs Online, Sales by cashier, Sales by store, Sales by payment method.

For similar reasons, this should be part of ERPNext, not really the PoS specifically.

**Comment by ramielian** [comment]
We have more than 3000 sku/ product, will it all be available using the HTML 5 storage!!? Will it be fast enough as @fderyckel  mentioned !?

**Comment by javieralmancevo** [comment]
@ramielian There is no reason why using HTML 5 storage would make the system slower, once the data is loaded in memory they would behave the same. In fact, using HTML 5 storage the initial launch will be quicker as the information is local and not gathered over the network from a server.

**Comment by ramielian** [comment]
What I mean by customer screen is like in modern retail pos have a screen for customers to see what products added to the pos and the prices and information of it
I think it will be an added feature to Erpnext pos

**Comment by woakes070048** [comment]
i was thinking of integrating wallace pos it has most of what you guy are looking for

**Comment by ramielian** [comment]
I have checked wallace pos and its great, missing some features (Multilanguage, customer screen ..) but have many good features as well...
And it also have offline capability which is what was needed in first place...
@woakes070048 if you need any help let me know I have some free time to kill...

**Comment by woakes070048** [comment]
@ramielian I don't think we will be starting working on it until sometime next month but we are planning on integrating verifone and also we were planning on a customer screen as well. We are currently working on a wso2 integration for a EDI implementation.

**Comment by fderyckel** [comment]
Lucky you 😉

**Comment by ramielian** [comment]
@fderyckel unfortunately not lucky, after reviewing the pos, it have limited features not as I saw it on first time, and after reviewing the demo and source code, it has manyyyyyy bugs that we cannot afford to fix (timely speaking)...

**Comment by javieralmancevo** [comment]
There is a new PoS scheduled for the next release of ERPNext. I would advise to wait, see the new version and then decide the best course of action.

**Comment by woakes070048** [comment]
@javieralmancevo when is the next release?

**Comment by chungyan5** [comment]
hi all, 

For the title as Offline mode for PoS, actually this offline solution can extent to erpnext other module, such as: i would like to have Project, Task, Event, Note offline(at mobile/desktop) / online mode too, for Collaborative project management. I would like to join to implement this offline / online mode for this module.

**Comment by nabinhait** [comment]
Added in version 7
