### ISSUE TITLE
How to make courses from school addon availbe on ERPNEXT website?

### ISSUE THREAD

**Issue by aacosae** [frappe/erpnext#5124]
How to make courses from school addon availbe on ERPNEXT website?

**Comment by sicsrmanic** [comment]
@aacosae Do you mean, show courses from school module on Website? I think that feature is surely not available out of the box.
Workaround: use shopping cart to display courses you want students to register and then build hooks to add registered and paid students to the course.

**Comment by anandpdoshi** [comment]
@aacosae do you mean to use schools on your subscription at erpnext.com? We are expecting to launch a beta by next week.

**Comment by aacosae** [comment]
No we will use them on our private hosting

**Comment by vjFaLk** [comment]
@aacosae If what you're considering is only having the Courses module in ERPNext it won't work very well. I'd recommend you to use the entire ERPNext Schools app. The ERPNext Schools app works with ERPNext so you can still access ERP functions. 

Refer : https://github.com/frappe/schools
