### ISSUE TITLE
Drop "Role" table from Event, now that we can "Share"

### ISSUE THREAD

**Issue by omnison** [frappe/erpnext#5125]
Dear 

during creating new event in calendar, there is participant, role is not suitable for our company, i need to change to user or employee. 
How to operate this change? 

<img width="1282" alt="2016-04-03 8 04 15" src="https://cloud.githubusercontent.com/assets/7886153/14230699/068e7952-f973-11e5-852e-8e2753c7618e.png">

**Comment by anandpdoshi** [comment]
I think this can be done by ‘Sharing’ the event to users.

**Comment by omnison** [comment]
ok. thank you.

**Comment by rmehta** [comment]
Maybe we should just drop the "Role" table from Event, now that we have share
