### ISSUE TITLE
Production Planning Tool - Add multiple rows

### ISSUE THREAD

**Issue by Gleisson03** [frappe/erpnext#5126]
The button "Add multiple rows" would be very useful in Production Planning Tool. Can be added this button?
Certainly I would greatly speed up my work.

Thanks in advance.

**Comment by PawanMeh** [comment]
![screen shot 2016-09-05 at 9 16 38 am](https://cloud.githubusercontent.com/assets/20460498/18236996/d254d798-7349-11e6-9cea-4bf2c5c5c5dd.png)

The button is available now,closing this issue.

**Comment by Gleisson03** [comment]
Wow, thank you so much for your attention for sure will help me a lot!
