### ISSUE TITLE
Lead import tool failure after positive confirmation 

### ISSUE THREAD

**Issue by nanoDavide** [frappe/erpnext#5128]
On two occasions (  31st March 2016 and today Monday 4th April) I have tried to import a list of leads without success. 
- the list is short about 60 entries 
- I have tested format (.csv) and encoding (UTF-8) before (e.g. acouple of months ago) and it was working fine.
- now I have Import success response but the data is not actually in the system 
- actually the confirmation appears suspiciously quickly and without any error messages, suggesting it is not comparing the new list with the database

I am putting in attachment the print screen of the import page and the list itself
[BPS leads  copy.csv.zip](https://github.com/frappe/erpnext/files/201980/BPS.leads.copy.csv.zip)
![screen shot 2016-03-31 at 17 24 14](https://cloud.githubusercontent.com/assets/18257613/14241851/3d6c93a6-fa4e-11e5-9bc2-6d2542bcf437.png)

How do I fix this issue?

Kind regards, 

Davide

**Comment by anandpdoshi** [comment]
Check if you are using the latest CSV template

Best,
Anand Doshi

ERPNext
