### ISSUE TITLE
Hide batch & serial fields in all forms except when item requires it.

### ISSUE THREAD

**Issue by cgpurbaugh** [frappe/erpnext#5135]
see title.

**Comment by jwrober** [comment]
How would the "form" know it is required? What is the use case or scenario you are looking fro from a UX perspective?

**Comment by cgpurbaugh** [comment]
The form could know it's required by looking up the value from the item file.  The use case is that if an item is not serialized, users should not be given the option of entering serial numbers.  the same goes for batches.

**Comment by jwrober** [comment]
Thanks
