### ISSUE TITLE
over transfer production order qty and stock in 

### ISSUE THREAD

**Issue by Manson10x** [frappe/erpnext#5136]
Good day

i have 2 question

my sales order Product-A order qty=10000pcs
and then my bom Material item_code B 1.3 pcs,can do 1pcs Product-A(BOM setup)
and then  my Production order qty=10000pcs
my material  Picking list 13000pcs
and then
1.time log ---i can't transfer over completed production qty next operation 
2.stock in---i can't stock in over completed production qty

beacuase,
my bom have 6 operations
1.cliping----- completed OK qty =13000 ,Bad qty=0
2.Aging-----completed OK qty =13000
3.Grinding------completed OK qty =12500,Bad qty=500
4.Expoy------completed OK qty =12000,Bad qty=500
5.E-test------completed OK qty =11000,Bad qty=1000
6.Package-----completed OK qty =11000,Bad qty=0

our product  Yield maybe some time is good ,some time is bad...

-------
so,i want to a option
口allow over transfer qty

thanks

**Comment by rmehta** [comment]
Please post help queries at https://discuss.erpnext.com
