### ISSUE TITLE
Customer print format

### ISSUE THREAD

**Issue by Manson10x** [frappe/erpnext#5137]
good day
doc.Customer
i want to print  customer all sales order..
like customer name=ABCZoo

{% set u = frappe.get_doc("Sales Order",doc.name) %}
{%- for row in u.items -%}
<tr>
<td style="border-style: solid; border-width: thin;" class="style18">{{ row.item_code }}</td>			
<div class="row">	</div>
</tr>
{%- endfor -%}

the error msg
Sales Order ABCZoo not found

thanks

**Comment by rmehta** [comment]
Please post help queries at https://discuss.erpnext.com
