### ISSUE TITLE
Unable to create journal entries.

### ISSUE THREAD

**Issue by bennaiqbal** [frappe/erpnext#5139]
Hello,

I'm unable to create any journal entries. We've been using the system actively for over 6 months now. Suddenly, we are no longer able to create new journal entries, with the following error.

Duplicate name Journal Entry JV-00001
Journal Entry JV-00001 already exists
Did not save

Please help.

Thanks

**Comment by rmehta** [comment]
Please post help questions at https://discuss.erpnext.com

https://frappe.github.io/erpnext/user/manual/en/setting-up/articles/naming-series-current-value.html

**Comment by anandpdoshi** [comment]
Looks like someone reset the Naming Series counter: https://frappe.github.io/erpnext/user/manual/en/setting-up/articles/naming-series-current-value.html 


Best,
Anand Doshi

ERPNext
