### ISSUE TITLE
Close Sales Order that is a Draft

### ISSUE THREAD

**Issue by bfoxtrot** [frappe/erpnext#5140]
Unable to change the status of a sales order from draft to closed.

**Comment by Devens** [comment]
+1

**Comment by nabinhait** [comment]
Same issue #4037

**Comment by KanchanChauhan** [comment]
@bfoxtrot Since it is not submitted, you cannot change the status to Close. You sure can delete the Draft or may be just leave it as Draft if you wish to retain it. Can you explain the use case?
