### ISSUE TITLE
Price List should have an option to mention price in Purchase UOM

### ISSUE THREAD

**Issue by ruchin78** [frappe/erpnext#5142]
There are chances where item "X" comes in pack of 100 each and used in each.
Now the default UOM will be each and conversion details are as under:

UOM                     Conversion factor
each                      1
pack                       100

Now, there is a case that I need to define the price list of the item "X", first of all there is no option of UOM on price list there the issue comes.

Let say item "X" price is INR 5 each, now if I enter the price list for each and the price is INR 5.

Now, I create a BOM and select the rate of material based on price list.
and the BOM pics its price as INR 5 that is fine.

Now, I create Material Request of 100 qty. and then I create a Purchase Order, now I select the purchase UOM as pack and the qty. is 2, as 2 pack=100 qty., but again it picked up the rate as 5 which should be 5*50=250.

**Comment by Devens** [comment]
+1

**Comment by mobentec** [comment]
Are there plans to add UOM to the Standard Buying Price List?  That would be very helpful!

**Comment by tundebabzy** [comment]
Yes

**Comment by umairsy** [comment]
added in version 11.
