### ISSUE TITLE
Feature Request -  Hide menu in sidebar menu

### ISSUE THREAD

**Issue by andiyan1** [frappe/erpnext#5146]
Hi Team

Recent UI update in erpnext is a good progress and now we can customize our desktop like we want it to be. 

However on the sidebar menu,  there are no option to hide uneccesary menu from the side menu. 

Let say a salesman would only need sales module we can hide other module in desktop icon. However on left navigation bar,  there are no option to hide the menu. 

Can you help me for this 
Thank you
Anton

**Comment by rmehta** [comment]
@andiyan1 yeah this should be fixed. Can you raise it on support?

**Comment by andiyan1** [comment]
Okay will do

**Comment by anandpdoshi** [comment]
@andiyan1 fixed. Will be released sometime today.

**Comment by andiyan1** [comment]
Thanks @anand, rushabh and nabin

Best regards
Anton
