### ISSUE TITLE
Budget Variance Report - Monthly Budget Allocation

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#5148]
As per the monthly budget allocation feature, unused allocation of one month is carried forward to the succeeding month. In the budget variance report, value in the Target column for each month should be cumulative of unused balance of the preceding months.

For example: Monthly budget allocated in the Cost Center is 20,000. From Jan to March, no expense is booked against a Cost Center. Hence for the Month of April, Target should be updated as 80,000. Currently Target value for each month is fixed (i.e. 20,000), and not updated based on the unused balance of the preceding months.

![screen shot 2016-04-07 at 3 30 45 pm](https://cloud.githubusercontent.com/assets/910238/14347728/38fd35b6-fcd6-11e5-9784-f7922a27f11a.png)

**Comment by Tropicalrambler** [comment]
+1
