### ISSUE TITLE
remove link from emails sent by erpnext

### ISSUE THREAD

**Issue by me2ne** [frappe/erpnext#5155]
Hello
There is problem when some one use ERPNEXT in local server , when they send email ( quote / PI / ... ) there is two link in email **"View this in your browser" and "Leave this conversation"** , but due erpnext installed in local network this link will not work for customer and email sent with wrong link . 
my suggestion make it optional . 
Regards

**Comment by rmehta** [comment]
If you set disable signup in website settings, "view this in your browser" will not show.

@KanchanChauhan can you move this to somewhere in **Email Account**

**Comment by me2ne** [comment]
Hello
Thanks for your reply , I disable Signup , but still when i send any invoice of quote by email show linked  ""view this in your browser"  in email . 
Can you please check what is issue . 
Regards
![screen shot 2016-06-12 at 11 33 42 am](https://cloud.githubusercontent.com/assets/6168204/15989759/cea8c4d8-3091-11e6-8a79-8bf06cb8024f.png)
![screen shot 2016-06-12 at 11 33 18 am](https://cloud.githubusercontent.com/assets/6168204/15989760/cf7cb928-3091-11e6-8396-8b1b48ba0795.png)

**Comment by KanchanChauhan** [comment]
Uncheck the option highlighted in red below when you compose the email.

<img width="739" alt="screen shot 2016-06-21 at 5 11 29 pm" src="https://cloud.githubusercontent.com/assets/16913064/16228231/676a6184-37d3-11e6-8e0f-e044ca5c580d.png">

**Comment by rmehta** [comment]
@KanchanChauhan the user wants to send the email with attachment, but does not want the link.

**Comment by KanchanChauhan** [comment]
https://github.com/frappe/frappe/pull/1807

**Comment by KanchanChauhan** [comment]
@me2ne Check button "Send document web view link in email" have been provided in Print Settings now. It will be realized with v7.

**Comment by me2ne** [comment]
Hi
In version 7 i uncheck  "Send document web view link in email"  , but still when i send quote by email show "Leave this conversation" , in email and due we have erpnext in local server this link not work for our customer .
Please check and solve this issue too .
Regards

**Comment by hiousi** [comment]
same problem here, want to remove "Leave this conversation"

**Comment by KanchanChauhan** [comment]
@me2ne It did work for "View this in your browser". Right? 
@me2ne and @hiousi For "Leave this conversation" may be we can have another checkbox. Can you please raise separate issue for that.

**Comment by krnkris** [comment]
Hello,

I have the same problem, please check it.
In version 7 i uncheck "Send document web view link in email" , but still when i send quote by email show "Leave this conversation"
Sincerely

**Comment by KanchanChauhan** [comment]
Fixed via https://github.com/frappe/frappe/pull/2298

**Comment by karlosTM** [comment]
In erpNext v14 this setting has been moved to System Settings, but we have unticked the option but it still adds the web link to my emails. Any idea how to fix?
_System Setting - email - Send document Web View link in email_
