### ISSUE TITLE
Add multiple item

### ISSUE THREAD

**Issue by farhanayyaz1** [frappe/erpnext#5163]
in add multiple item if we can add price also would be helpfull.

**Comment by anandpdoshi** [comment]
@farhanayyaz1 Why not use Price List?

**Comment by farhanayyaz1** [comment]
Dear,
We are into wholesale , retail and installations so we have diffrent prices each time for diffrent cuatomer and than bargain doacount is there.
--
Sent from myMail app for Android Saturday, 09 April 2016, 08:07am +04:00 from Anand Doshi < notifications@github.com> :

**Comment by anandpdoshi** [comment]
That's why you select items quickly and enter amount and discount in each row from the standard UI.

**Comment by farhanayyaz1** [comment]
Yes dear doing same but this is faster way thats why i said.
--
Sent from myMail app for Android Saturday, 09 April 2016, 10:05am +04:00 from Anand Doshi < notifications@github.com> :

>That's why you select items quickly and enter amount and discount in each row from the standard UI.
>
>Sent from my phone
>

**Comment by rmehta** [comment]
This is removed in v7
