### ISSUE TITLE
Underline BUG in PDF print

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#5168]
When you underline a text and export the PDF it increses the underline to the beginning of the next character, it seems the nbsp; is underlined too. This should be fixed.

Preview (good):
![preview](https://cloud.githubusercontent.com/assets/9136094/14403186/14cb4c04-fe4e-11e5-8d0d-e88a8e5edbf9.png)

PDF print (bad):
![pdf](https://cloud.githubusercontent.com/assets/9136094/14403187/18368b4c-fe4e-11e5-8b43-fa98f9e7fc4b.png)

**Comment by cgpurbaugh** [comment]
@dottenbr how are you underlining these?

**Comment by dottenbr** [comment]
You can underline any text editor field type by hitting ctrl+u on your keyboard. That's how I did it. 

Sent from my mobile

**Comment by anandpdoshi** [comment]
@dottenbr can you check if chrome browser shows underline or not for empty space?

**Comment by dottenbr** [comment]
Hi Anand,

The screenshot that has the space not underlined is print preview in chrome. Also the text editor doesn't show underline. However the PDF export does show underlined. 

@emakis can you check if the code includes the empty space in the underline tag?

Sent from my mobile

**Comment by emakis** [comment]
Which is this docType @dottenbr ?

**Comment by dottenbr** [comment]
In this case it is instruction but you can use any doctype with text editor field. 

Sent from my mobile

**Comment by emakis** [comment]
the html tag is correct, no empty space: <u>Montag:</u>
The problem is in the PDF creation

**Comment by dottenbr** [comment]
Is this still an issue with summernote ow was it it strictly pdf rendering?
