### ISSUE TITLE
Report Builder -  Field is not selectable and i can't delete

### ISSUE THREAD

**Issue by Gleisson03** [frappe/erpnext#5171]
When I create a report with the Report Builder and add a field that has a link, this link is invalid, and the following error appears: "Field is not selectable."

Example: I've created a report of "Sale Invoice" and add a field that indicates the "Sales Order", when I click on its "Sales Order" appears this error, but when I click on the ID of the "Sale Invoice" works fine.
![000000001](https://cloud.githubusercontent.com/assets/13992475/14407615/eb585aca-fea6-11e5-98e2-299549fd47e1.jpg)

**Comment by jinayG** [comment]
Could you please tell me where is the report builder?

**Comment by Gleisson03** [comment]
Of course.

https://frappe.github.io/erpnext/user/manual/en/customize-erpnext/articles/making-custom-reports-in-erpnext.html

**Comment by PratibhaPatil** [comment]
When we create custom report from standard. There we need to select the report type.

**Comment by Gleisson03** [comment]
@PratibhaPatil 
I apologize, I did not understand.
There is the option of selecting the type of report and make links to other documents to be open?

**Comment by Gleisson03** [comment]
I have a new problem
I created some reports and saved, but now I can not delete them, even with the Administrator account.

**Comment by anandpdoshi** [comment]
Use Role Permission Manager to give yourself delete rights on Report doctype

**Comment by Gleisson03** [comment]
Thank you for your attention @anandpdoshi !!
I had the privilege to exclude, but just in case I checked again and confirmed that I have permission to delete.
When I click to delete the report, simply nothing happens.

**Comment by anandpdoshi** [comment]
@Gleisson03 are you on our cloud or have you self installed?

**Comment by Gleisson03** [comment]
Please I apologize for the delay to answer.
I was doing it the wrong way, so it could not delete.

They can close the topic. Again, I'm sorry for the problem.
