### ISSUE TITLE
Draft Stock entry is not updating values on Reload

### ISSUE THREAD

**Issue by jinayG** [frappe/erpnext#5172]

**Comment by nabinhait** [comment]
Please elaborate your queries in detail.

**Comment by jinayG** [comment]
1)I have added new item abc
2)I created a BOM and created it's production order which uses raw material
as item ABC and submit the order.
3)To start the production I need to transfer materials to WIP warehouse
from stores warehouse, however on the Production order screen it is showing
that item is not in Stock so I save the production order as Draft.
4)I do receipt of material and add stock for item ABC in stores warehouse.
5)I go to my draft production order and reload values but it's still not
updated stock showing item not in Stock.

Alternate Solution-
1) I create a duplicate production order and submit it.
2)Now when start the production by transfer of material it is showing item
in Stock.

Ps- In the title of the issue it should have been "DRAFT PRODUCTION ORDER"
instead of "Draft stock entry".
On Apr 11, 2016 10:39 AM, "Nabin Hait" <notifications@github.com> wrote:

Please elaborate your queries in detail.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/frappe/erpnext/issues/5172#issuecomment-208164840>

**Comment by jinayG** [comment]
Please note that Item abc is the raw material and Production order is to
manufacture item XYZ

**Comment by nabinhait** [comment]
fixed via https://github.com/frappe/erpnext/pull/5180
