### ISSUE TITLE
Processable custom forms

### ISSUE THREAD

**Issue by herbkansiime** [frappe/erpnext#5174]
1.I would like to make forms that will appear in the CRM module and have the red counters like they appear in the Opportunity, communication etc so that my staff can see what's come in and process it. I have tried creating the form via the doctype, as a child and as single but both don't give me what I want.

**Comment by yashodhank** [comment]
@herbkansiime This is not the correct place to discuss such issues, please use https://discuss.erpnext.com for development help from the community.

**Note: ** Github > Issues are strictly used for reporting/tracking bugs, issues and feature request (after discussion at discuss.erpnext.com) Thanks
