### ISSUE TITLE
Unable to delete test doctypes

### ISSUE THREAD

**Issue by herbkansiime** [frappe/erpnext#5175]
I am trying to delete some of the test doctypes I created but I don't get the delete option. I have tried with various permissions for the doctypes but still cant delete them. There must be a way of protecting the standard doctypes and letting hosted users delete what they create.

**Comment by rmehta** [comment]
Did you add delete permission on doctypes?

**Comment by herbkansiime** [comment]
I am on the managed hosting package and therefore cannot change permissions on doctypes.

**Comment by herbkansiime** [comment]
Here is a reply I got from Umair Sayyed "Since there are Standard doctypes as well, hosted user's doesn't have permission to delete doctypes"

**Comment by rmehta** [comment]
@nabinhait can you fix this?

You can restrict standard deletes for non-Admins via controller

**Comment by nabinhait** [comment]
Fixed via frappe/frappe#1862
