### ISSUE TITLE
No option or link to remove icons on Dashboard created by "Add to Desktop'

### ISSUE THREAD

**Issue by kamtex** [frappe/erpnext#5181]
As above. On the Dashboard,** there is not Trash / Bin icon ** where I can drag icons I accidentally created by** 'Add to Desktop'.** This means that it is possible for one to overload the Dashboard with icons created by 'Add to Desktop' and overwhelm the interface, making the UI unusable. 
Please fix ASAP.

**Comment by neilLasrado** [comment]
It creates a record used Desktop Icons. delete the record from there.

**Comment by rmehta** [comment]
User Icon (top right) > My Settings ... > Set Desktop Icons
