### ISSUE TITLE
problem erpnext smtp with ZOHO mail 

### ISSUE THREAD

**Issue by me2ne** [frappe/erpnext#5183]
Hi 
This is problem in ERPNEXT smtp and ZOHO mail , ERPNEXT only can send email with default outgoing if we use ZOHO mail server and can't send email with other email we add . 
if we add other SMTP email in erpnext and it's not default smtp , email will not send form new user and status show "not sent"  . 
Regards
Meisam

**Comment by anandpdoshi** [comment]
Can you elaborate with screenshots?

Best,
Anand Doshi

ERPNext

**Comment by neilLasrado** [comment]
@me2ne ERPNext works fine with Zoho mail. make sure you have used zoho mail settings as mentioned here https://www.zoho.com/mail/help/zoho-smtp.html

**Comment by me2ne** [comment]
hi 
when you have only one sender and click on "Always use Account's Email ID as Sender" and " Default Outgoing" it's working fine , but if you have two different sender with ZOHO mail , not working fine :)

**Comment by me2ne** [comment]
@anandpdoshi 
Thanks for your reply , from witch part you need screen shot ?

**Comment by pugalde** [comment]
I have the exact same problem. 3 days ago everything worked fine but as of today it's not working anymore. I didnt change any setup from the account and somehow it is not working anymore.
I created an email account in ZOHO specifically for the emails going out of ERPNEXT but the system is not sending them.
I have tried with the checking and unchecking the default  outgoing and the always use... but it hasnt worked so far.
Does anyone know a goog fix for this issue?

**Comment by pugalde** [comment]
Just to help with this. I receive every digest that comes from ERPNext. So automatically generated emails are being sent. Everytime I want to send an email manually is when nothing happens.
Hopefully someone can look into this issue. As far as I have been looking around the forums, there is many people having problems with Zoho and there's no apparent solution.

**Comment by anandpdoshi** [comment]
I had fixed a few issues related to ZOHO sometime back. Are you using the latest version?

Best,
Anand Doshi

ERPNext

**Comment by pugalde** [comment]
I am using the SaaS version. 

---- On Wed, 20 Apr 2016 11:55:20 -0300 notifications@github.com wrote ----

I had fixed a few issues related to ZOHO sometime back. Are you using the latest version?

Best,
Anand Doshi

ERPNext

**Comment by anandpdoshi** [comment]
@pugalde we recently pushed some fixes that will show you the status of your email, whether it was sent or did it lead to an error. May be that will confirm if emails were sent, but not received at the user's end.

**Comment by me2ne** [comment]
Thanks anand , ERPNEXT team always UP TO Date and find solution for problems . I'm happy to use erpnext in my shop .
