### ISSUE TITLE
[Enhancement] Add section tab to Employee

### ISSUE THREAD

**Issue by DrTrills** [frappe/erpnext#5185]
The Employee page has many many sections creating a long page. Adding some tabs similar to how Facebook does it would be a great remedy. More here: https://discuss.erpnext.com/t/add-section-tabs-to-employee/11713

Thank you!

**Comment by mhbu50** [comment]
+1

**Comment by revant** [comment]
> rmehta:
> Employee Sections are yet to be collapsed. Will do that in the next release.
> We have gone away from tabs because you don't know what to do when you have too many of them!

https://discuss.erpnext.com/t/add-section-tabs-to-employee/11713/4

**Comment by PawanMeh** [comment]
List sections are collapsed by default in the latest release.
