### ISSUE TITLE
[bug] field login_id_is_different not showing up

### ISSUE THREAD

**Issue by imapirate** [frappe/erpnext#5186]
According to [discussion on forums](https://discuss.erpnext.com/t/mail-setup-with-google-groups-aliases/11743?u=imapirate), email account form should expose a login_id_is_different check field to setup accounts where username and actual address are different. I did setup a fresh installation pulling `davidgu/erpnext` docker image but that field is not present.

**Comment by yashodhank** [comment]
The latest version which my test server running in production mode installed using latest bench yesterday. Does have the option to enable Login Id is Different.

> Kindly note that the Docker image consists an older version.
> It is nonofficial and released by one of the community member.
> For updates, you should contact docker image publisher.

**Comment by imapirate** [comment]
I see, thank you! I was fooled by looking at the dockerfile which seemingly pulled from the official repo master branch. I'll try the official _easy production setup_ script and update the issue asap.

**Comment by imapirate** [comment]
Indeed @yashodhank is right, my bad The latest version works pretty fine already in this respect!
