### ISSUE TITLE
Custom module [logistics] help

### ISSUE THREAD

**Issue by ramielian** [frappe/erpnext#5188]
Need help to know how to send this custom module to github for anyone to use and share, am a newbie to github and never actually used it before...

**Comment by anandpdoshi** [comment]
Try this: https://youtu.be/6JpB5QeOkQw?list=PL3lFfCEoMxvzHtsZHFJ4T3n5yMM3nGJ1W

Please post your doubts and questions on https://discuss.erpnext.com instead. This issues list is for bug reports and feature requests.
