### ISSUE TITLE
Make it easier to add Serial Numbers to a Stock Entry for Production (paid development)

### ISSUE THREAD

**Issue by sjoulaei** [frappe/erpnext#5190]
I have a number of products which are built based on a BOM. Most of the items in the BOM are serialised items.
Starting a manufacturing process (Transfer Material for Manufacture) is a big pain at the moment as I need to select each BOM item one by one and select the serial number that i want to use in this manufacturing process.
It would be much easier to add a "Bulk serial number transfer" button to the Production Order page. Then give the ability to add all the serial numbers needed for this item and click submit. System then finds the right item to assign each serial number based on the type of the item and also the warehouse they are.
Few result scenarios:
1. If entered serial number list is complete and fits into the BOM list --> then serial numbers assigned and go to next step.
2. one or some of the serial numbers are not existed or not matching with any of the items in the BOM. Then an error message to be produced.
3. Serial numbers are OK but not covering all of the items then this stage submit should be okay and when transfer material button pressed a message appears to say some items missing serial number (exactly as it is happening now)

This would be very beneficial for the usability of the manufacturing module with big serialised BOM items. We want to implement ERPNext into our manufacturing and person doing the job will have the needed BOM items physically in hands. A hand-held bar code reader will read all the serial numbers one by one into the list.
![bulk serial number assignment](https://cloud.githubusercontent.com/assets/12406801/14448389/ec13f762-009a-11e6-8449-5d5edfe62bc5.PNG)

**Comment by lonovo** [comment]
I might be able to pay for this development. Can someone give me an estimate for it? 
Thanks,

@umairsy

**Comment by rmehta** [comment]
@lonovo this is still a bit vague.

The goal, I understand is to quickly add Serial Numbers to the item table?

**Comment by lonovo** [comment]
Correct. At the moment when we build an item which includes 14 serialised items inside. We need to open 14 pages and enter the serial numbers for each of them.
What i would like to see is to be able to enter all at once.

**Comment by kennethsequeira** [comment]
This issue can be solved using pick list:

https://docs.erpnext.com/docs/v13/user/manual/en/stock/pick-list
