### ISSUE TITLE
Re-arranging as per fields within a doc type

### ISSUE THREAD

**Issue by maheshengg** [frappe/erpnext#5192]
Dear Team,
User Friendly Forms is an essential criteria. 
All Businesses have different set of priorities and focus on what amount of and which type of data should be inputed precisely and in what order.

Usually, Every Form can be safely divided into three parts.. TOP, BODY and FOOTER.
Body usually is a child table, say, an item table 

Many a times, certain important fields like addresses, contacts which other wise appear in the footer ( after the item table) during form filling is skipped or less focused by users , can gain more attention if they are "moved" to TOP part of the form.

Thus doctype fields re-arrangement flexibility to sys admins gives them the flexibility to gain more control over forms.

In my case, I take the example of Sales invoice, in which Customer Address is at the bottom, in "more information tab" , which I desire to be at the top. Like wise, many-a-times, (also POS) with update stock, in order to provide faster invoice creation, we directly create a sales invoice, (without sales order and delivery note) and there is a need to select customer address and contact ( which are multiple and user is supposed to select ) 

There are many such forms, say, Quotations, Sales Orders, Purchase Orders, etc.

Agreed, doctype with standard fields shouldn't be allowed for account admins to be modified, as it may alter the stability, but re-arranging (if not all, certain fields) shouldn't be as damaging I guess.

Kindly look into this and provide a way for this issue.

**Comment by adityaduggal** [comment]
@maheshengg Long time, I fully agree that the address in the Invoice should be moved to the TOP instead at bottom, I guess now since field movement is restricted we need to post issues for such things as well but look at the brighter side that each field would have to be thought out in the standard product as well.

**Comment by rmehta** [comment]
@umairsy can you fix this?
