### ISSUE TITLE
Customization of in series of task

### ISSUE THREAD

**Issue by PratibhaPatil** [frappe/erpnext#5201]
We have 3-4 types of work order for bolting tools, some times it is in hour basis, shift basis, target wise or fixed amount. When we place the work order in system. It is fine. But while creating project of that work order, in task, we want that separation in series wise so that billing will be not easy as per counting of bolts. Any idea about this???

**Comment by adityaduggal** [comment]
@PratibhaPatil Please note that this is not supposed to be on github issue as it does not seem like an issue, please post this query on http://discuss.frappe.io/ since queries are supposed to be posted there.
