### ISSUE TITLE
ERPNext Quickbooks Connector

### ISSUE THREAD

**Issue by nabinhait** [frappe/erpnext#5202]
- [ ] Migrate opening data from Quickbooks to ERPNext.
- [ ] Customers, Suppliers, Item, Tax, Employee and User will be managed through ERPNext and whenever added new or updated existing one, it will update in QuickBooks.
- [ ] Sales / Purchase Invoice will be created in ERPNext and synced with Quickbooks.
- [ ] Journal Entry against SI/PI will be primarily created in QuickBooks and same will sync to ERPNext or vice versa.
- [ ] Listing on Quickbooks app store and ERPNext app store
- [ ] Test Cases
    - Webhooks + Syncing 
        - Store a sample response to a request and check if sync works
        - Examples
            - [Shopify Test Cases](https://github.com/frappe/erpnext_shopify/blob/develop/erpnext_shopify/erpnext_shopify/doctype/shopify_settings/test_shopify_settings.py)
            - [Shopify Test Case Data](https://github.com/frappe/erpnext_shopify/tree/develop/erpnext_shopify/erpnext_shopify/doctype/shopify_settings/test_data)
- [ ] Documentation

---

**Syncing**
- If webhooks are available, use them
- As a fallback, use scheduler to sync data. Ideally, sync should happen at a minimum of every hour.
- Also provide a button to call the sync method manually, but it should be a background job, as sync could take more than 2 mins, which is the timeout of the web process. 
    - See [Sync Shopify](https://github.com/frappe/erpnext_shopify/blob/develop/erpnext_shopify/api.py#L15)
    - Note that you will have to change this call once celery is deprecated in favor of python rq. We will post instructions. 
- All sync / webhook calls should be logged, with exceptions if any. Logs should be cleared every 30 days. (See [Shopify Log](https://github.com/frappe/erpnext_shopify/tree/develop/erpnext_shopify/erpnext_shopify/doctype/shopify_log))
- Exception Handling
    - If due to some exception, a record does not get synced, the code should be able to sync that record once the error is taken care of, similar to how IMAP works in email.
    - If there are repeated exceptions, disable auto-syncing and notify System Managers. (See: [Disable Shopify Syncing on Exception](https://github.com/frappe/erpnext_shopify/blob/develop/erpnext_shopify/api.py#L42))

**Comment by gupteshwar** [comment]
Please follow development and updates, https://github.com/indictranstech/erpnext_quickbooks
