### ISSUE TITLE
Dashboards

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#5204]
Useful info for entities
### Customer
- [ ] Ranking (all time sales)
- [ ] Total volume
- [ ] Last order
### Supplier
- [ ] Ranking (all time purchase)
- [ ] Total volume
- [ ] Last order
### Item
- [ ] Sales Ranking (by volume)
- [ ] Purchase Ranking
- [ ] Average Price (?)
- [ ] Current stock positions (in each warehouse)
- [ ] Warning if projected qty is below 0

**Comment by Devens** [comment]
Great!!

For customer dashboard, I suggest ranking by A/R also. Actually very-very important for any business. 

Note: When team has initiated Quickbooks integration, I would suggest to have a look at A/R graphical representation (along with drilling down upto record level is) provided in Quickbooks. It's THE BEST in segment and Most Useful feature (especially for an SME owners/decision makers).

**Comment by me2ne** [comment]
@rmehta 
Dear Mehta
It's very good idea , this is biggest problem we have with erpnext , we move from WEBERP to ERPNEXT but due we don't have any dashboard for items with all details need in one page , still we use old ERP . 
i make one mockup may be help you to get idea for item dashboard what's important for trading company , so easily can make best decision and share price with customer . 
Please check attachment .
Regards
[Copy of MOCK-UP.pdf](https://github.com/frappe/erpnext/files/217440/Copy.of.MOCK-UP.pdf)
[Copy of MOCK-UP.pdf](https://github.com/frappe/erpnext/files/217442/Copy.of.MOCK-UP.pdf)

**Comment by rmehta** [comment]
@me2ne you get that data via reports anyways.

If you want such dashboards, you can make them yourself in your app

**Comment by me2ne** [comment]
Thanks for your reply , I'm not technical , i need to ask some one do it for me :)

**Comment by yashodhank** [comment]
@me2ne Post your custom requirements to hire Frappe/ERPNext Developers & Service Providers > https://community.erpnext.com/jobs

**Comment by yashodhank** [comment]
For more ideas, I am proposing following layout for Client Portal - Dashboard.
![image](https://cloud.githubusercontent.com/assets/1083792/14525509/6e7a933e-025b-11e6-9520-68d974324d92.png)

**Comment by woakes070048** [comment]
@yashodhank I am working on dashboards for erpnext and other applications but i have chosen to make it an external application. It does have single sign on for erpnext. I happen to agree with @rmehta that dashboard usually give a mind set for setting short term goals and can hurt you long term. To get a true overview you need to dig in and see whats going on with all of your customers. Anyway it should be done by the end of next week if you would like it

**Comment by sbkolate** [comment]
@yashodhank from where you have capture this image. Can you share html/css code.
We can build such webpage in existing shopping cart.
Really good design (y)
We also like same designed page for supplier portal

**Comment by woakes070048** [comment]
@yashodhank that page is from whmcs

**Comment by yashodhank** [comment]
@sbkolate sure, take a look at
https://getgrav.org/ & https://github.com/smartgravity/whmcs-smartgravity-template
Then for screenshot theme > https://github.com/WHMCS/templates-six

**Comment by felixvarghese** [comment]
This may already be the plan, but it may be good to think of these in terms of widgets. Users can pick and choose what they want to see. Devs can extend/add widgets through apps.

**Comment by Devens** [comment]
+1

**Comment by mhbu50** [comment]
+1

**Comment by rmehta** [comment]
#8777

**Comment by LifeP** [comment]
These are some of the best dashboard I've seen on a system. Simple and practical.

This one shows orders along with states of payment remittance in a bar per day.
<img width="949" alt="screen shot 2017-06-19 at 2 24 28 am" src="https://user-images.githubusercontent.com/16747599/27354472-521fec24-5625-11e7-898f-12a0abaf1830.png">

Sales Dashboards -> 
<img width="1202" alt="screen shot 2017-06-21 at 2 01 38 am" src="https://user-images.githubusercontent.com/16747599/27354589-b54dc8a2-5625-11e7-95e7-522eccb6cf36.png">

Sales Analysis by location, days, time of day and top selling items.
<img width="1207" alt="screen shot 2017-06-21 at 2 03 25 am" src="https://user-images.githubusercontent.com/16747599/27354648-e28b5faa-5625-11e7-8cff-cc10773975cf.png">

**Comment by bghayad** [comment]
Hello @LifeP 
Is it real time? In other words, if the page is opened, then data are changed automatically or the user need to click on refresh?
Regards
Bilal

**Comment by LifeP** [comment]
These were not realtime.
