### ISSUE TITLE
page for serial number history 

### ISSUE THREAD

**Issue by me2ne** [frappe/erpnext#5206]
Hi
In ERP next if we sell items to some one then he return back and we sell some one else or return back to supplier , it's very hard to track history of that products , 
It's good if there is one page like attachment for serial number history . 
Regards
[Copy of MOCK-UP-serial.pdf](https://github.com/frappe/erpnext/files/217458/Copy.of.MOCK-UP-serial.pdf)

**Comment by ankush** [comment]
Checkout "Serial No Ledger" report.

Alternatively Stock Ledger with item + sr no filter (in datatable) also works.
