### ISSUE TITLE
Quotation: Missing Description column when no description not filled

### ISSUE THREAD

**Issue by kamtex** [frappe/erpnext#5213]
Hi. I have a stockable item with item code and item name filled. Description is empty. 
When I enter this item into my quotes and look at the PDF, the description column is empty.
If I type some text in the description of my items in my quote, the column will reappear.

I believe previously, it will still show the Item Code and Item Name. Now it does not. The description column just disappears.

Photo attached. Top image: No description. Bottom image: When I entered 'NA' in the item's description.

![erpnext-missing1](https://cloud.githubusercontent.com/assets/17243028/14533707/c1a97b32-0298-11e6-92b0-51a4bb66c9c1.jpg)

**Comment by kamtex** [comment]
Anyone?

**Comment by rmehta** [comment]
Have you set "Print Hide" on item code / item name?
