### ISSUE TITLE
[V7] Error when adding Address from Quick View

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#5214]
![address-error](https://cloud.githubusercontent.com/assets/910238/14552485/8dab3348-02fc-11e6-8997-f9e94771de6d.gif)

Suggestion:

When adding new Address, in the Quick View, Customer and Supplier field should not be visible. Currency it is visible, but blank and frozen.

![screen shot 2016-04-15 at 11 25 06 am](https://cloud.githubusercontent.com/assets/910238/14552499/ba7dd7e0-02fc-11e6-93f2-de3d94948103.png)

**Comment by rmehta** [comment]
fixed.
