### ISSUE TITLE
[V7] Suggestion: In the master, when Edit, transactions count should get hidden

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#5215]
As per the recent update, in the masters like Item, Customer and Supplier, transaction count is shown.

![screen shot 2016-04-15 at 11 29 23 am](https://cloud.githubusercontent.com/assets/910238/14552573/566c0d84-02fd-11e6-96bd-4c5f1d848f6b.png)

On clicking edit, form opens below the section this section. My suggestion is, if user clicks on "Edit", then this section should get hidden, and it should only show form with doc fields (like earlier).

**Comment by rmehta** [comment]
it should scroll to the open form.
