### ISSUE TITLE
ERPNext Payroll Issues

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#5217]
The ERPNext Payroll functionality is still very manual and cumbersome. The following points are urgently required to make it more helpful and functional:

1. Better handling of Deductions so that relevant accounts can be specified for each Deduction and Journals raised accordingly to book these entries
2. Earnings in Salary Structure should have the option of being calculated as a percentage of specified Gross Salary (ie Transport allowance could be 5% of Gross Salary)
3. Deductions in Salary Structure should have the option of being calculated as a percentage of specified Earning Types (i.e. Salary Tax could be a percentage of all Earnings except Reimbursables and Housing allowance)
4. Option to settle Expense Claims via an Earning Type. Many organizations settle Expense Claims along with Salaries at the end of the month
5. Linking Attendance to Payroll. Option to automatically calculate Absent Days and Half Days in Attendance as Full Pay, Half Pay, or No Pay

Reference:  https://discuss.erpnext.com/t/salary-and-deduction/10721/5

**Comment by pugalde** [comment]
Any news about this?

**Comment by rmehta** [comment]
@rohitwaghchaure are we covering all of this in the new design?

**Comment by fikrut** [comment]
any update on this issue?

**Comment by rohitwaghchaure** [comment]
@fikrut Currently we are working on version 7 release, after that we will start working on auto deductions based on formula feature.

**Comment by Olawale1** [comment]
@rohitwaghchaure thanks for the good work being done on the auto deductions. Please don't forget the earnings side of things which is even more straightforward. Many organizations just split this into percentages based on a Gross Salary

Most times the organization already has the gross salary fixed and a template based on which the earnings are calculated e.g. Basic Salary (50%), Housing Allowance (30%), Wardrobe (10%), Transport (10%). There are sometimes different templates used for different categories of employees especially in larger organizations

Please let me know if you require any further clarification/input on any of the points listed

Thanks plenty

**Comment by fikrut** [comment]
@Olawale1 did the deduction part of erpnext V7 is working based on formula?as I can read from your comment its done where can I check please?thanks

**Comment by Olawale1** [comment]
@fikrut Not yet but discussions are already going on in that regard. I just pointed out the earnings part because Rohit only mentioned deductions in his post. I believe we should start seeing some updates in Payroll after V7 is launched this weekend

Cheers!

**Comment by rmehta** [comment]
@Olawale1 can you please raise separate issues for separate feature requests. Closing this for now!

**Comment by Olawale1** [comment]
Done! #5887 #5889 #5891 #5892 #5893
