### ISSUE TITLE
Item always dissapear after creating Selling Order

### ISSUE THREAD

**Issue by pugalde** [frappe/erpnext#5220]
I have created all the items I sell and everything seems to be ok. I can create SO without any problems but when I create the Delivery Note one item (if present in the SO) always dissapear.
I have the stock, The item is created as any other item but I cant seem to find with this particular item always dissapear.
Can someone help me with this?

**Comment by rmehta** [comment]
Can you check if you see anything in your JS console. Also can you replicate this on demo.erpnext.com?

**Comment by anandpdoshi** [comment]
Does this Item have Maintain Stock checked?

**Comment by pugalde** [comment]
I think I found out what the problema was. Somehow the item had checked the box "delivered by supplier". Turned that off at it worked. Thanks for caring
