### ISSUE TITLE
Script Report with Link type in filter shows canceled doc as submitted.

### ISSUE THREAD

**Issue by kardmode** [frappe/erpnext#5221]
A custom script report with a link type in the filter, which (in my case) shows all quotations, shows documents that have been canceled as submitted in the dropdown menu.
![untitled](https://cloud.githubusercontent.com/assets/8419064/14573918/68494bae-0369-11e6-97e9-eb4e883bfedd.png)

**Comment by anandpdoshi** [comment]
Did you also customise the get query if the filter?

**Comment by kardmode** [comment]
I first tested it without a get_query. Just to make sure I also tested with a get_query that doesn't include canceled documents and the document which I had canceled wasn't shown.
