### ISSUE TITLE
Adding "Supplier Manufacturer Linecard"

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#5225]
Certain suppliers sell certain manufacturers and either have franchise contracts or not. I would like to introduce a new DocType called "Supplier Manufacturer Linecard" which is a child table of Supplier where we can add a new entry for a supplier. The fields should be Manufacturer (LINK), Franchise (Boolean) and Specialty (Boolean). I would like to assign this to @emakis and have it moved to stack if possible and logical for others.

**Comment by dottenbr** [comment]
assgined to @kickapoo to fix and create pull request since this is interesting for EPRNext stack.

**Comment by anandpdoshi** [comment]
@dottenbr 

1. Why not just call it `Supplier Manufacturer`
1. What is the end use of storing this information?

**Comment by dottenbr** [comment]
I agree with your naming recommendation. The purpose is creating a database to see which manufacturers are sold by which supplier. Assume you are trading something, but where do you actually buy what you are trading. For us we assemble boards and we need that info. 

Sent from my mobile
