### ISSUE TITLE
Bug in Permitted Documents for User Report

### ISSUE THREAD

**Issue by justinlusg** [frappe/erpnext#5226]
![image](https://cloud.githubusercontent.com/assets/12539216/14588164/37133242-04f5-11e6-9101-a3041a2debb5.png)

To replicate error:
1) Set Permission to "If Owner" and remove "Apply User Permission"
![image](https://cloud.githubusercontent.com/assets/12539216/14588176/6134e796-04f5-11e6-9362-e87870083815.png)

2) Generate report for Permitted Document for User Report

The report will show the documents permitted for the CURRENT LOGGED IN USER instead of the selected user. This bug only affect when "If Owner" permission is generated. 

3) For the above user "info@agtech.com.sg", when we log in to their account this is what we see.
![image](https://cloud.githubusercontent.com/assets/12539216/14588187/92155db4-04f5-11e6-9389-c9a8d16b74f1.png)

**Comment by rmehta** [comment]
@KanchanChauhan try and replicate this

**Comment by KanchanChauhan** [comment]
@justinlusg Thank you for reporting this issue. It has been fixed now. Will be realized shortly with v7.
