### ISSUE TITLE
How do I obtain the new Item screen?

### ISSUE THREAD

**Issue by slushpuppy** [frappe/erpnext#5233]
I just updated to 

ERPNext: v6.27.9

Frappe Framework: v6.27.10

However my Item Master view still looks like the old 1:
http://i.imgur.com/dG3Rsjf.png

How do I update/recache to obtain the new view as shown in your demo site:

https://demo.erpnext.com/desk#Form/Item/MK1234

Thank you

**Comment by anandpdoshi** [comment]
But the pic you have attached is the NEW item screen!

**Comment by slushpuppy** [comment]
Hi Anandpdoshi,

  Thanks for the prompt reply. What I am seeing is quite different from the onsite demo & in the doucmentation. Basically I am trying to find the "Purchase Detail" section, it doesn't appear for in my screen  http://frappe.github.io/erpnext/user/manual/en/stock/item/

Thank you

**Comment by slushpuppy** [comment]
Oh Wow, turns out there is an "Edit" button at the top right hand corner. Perhaps the documentation highlight that the user should press that button before rest of the fields would appear

http://i.imgur.com/i6KM3nL.png

Thanks for your help anyway Anandpdoshi. I will close this issue

*Throwing in some keywords so the next unfortunate soul wouldn't have to search as hard as I did*
"How to show Sales Details Purchase Details Stock code Edit Item"
