### ISSUE TITLE
Creating Salary Slips for "inactive" Salary Structures - Process Gap

### ISSUE THREAD

**Issue by felixvarghese** [frappe/erpnext#5235]
I ran into a rather interesting edge case for creating salary slips earlier this month. The situation was the following
1.	Person had active salary structure from XXX till 31 March 2016. 
2.	On Apr 1, a new salary structure for this person went in place
3.	So, the Salary structure till 31 march changed to inactive (active = no).
4.	When we tried to process payroll for this person on April 4th for the month of March, it said that there is no active salary structure for this person for that time period.

While that is factually correct as the salary structure for march is now inactive, it leaves a logical gap of what should be allowed and what should not be allowed. In this (in my opinion, quite valid) case, we have no good way of processing this persons payroll – we could do some gymnastics and reactivate the structure, but that doesn’t scale beyond a few people.

My thought is that active/inactive Salary Structures shouldn’t have bearing when allowing creation of salary slips – only From date/to date (see the line below).

https://github.com/frappe/erpnext/blob/develop/erpnext/hr/doctype/salary_slip/salary_slip.py#L55 

It was mentioned that maybe in this case, it would be possible to completely remove "active" from salary structure. However, i would argue that keeping "Active" helps a user easily find the current salary structure of a person. I would personally not like to see "active" removed.

Any thoughts?

**Comment by rmehta** [comment]
@rohitwaghchaure can you fix this in the new design?

**Comment by nabinhait** [comment]
fixed in v7
