### ISSUE TITLE
Can not change the reference (code) of a product

### ISSUE THREAD

**Issue by pugalde** [frappe/erpnext#5236]
I just set up the company and its products in the system. At the beggining, when I entered the information about the products my company has I could write the internal reference or code when each one was being created. After saving it, it mainteined the reference I typed in.
A few days after I changed the naming sequence to "Prod-" (from "Item-") and everytime I create a new product I type in the internal reference number but the system changes it automatically to Prod-*****.
So my question is: Can I change the reference number after the creation of the product (Item)? If so, how?
If the above answer is "no", how can I enter my own reference number when I create a product, or what setting do I have to select so the system allows that?
Hope you can help me.

**Comment by asbasawaraj** [comment]
When you say 'Internal refrence number' do you mean 'Item Code'???

**Comment by asbasawaraj** [comment]
go to Stock -->Stock Settings and look at 'Item Naming By' field....

**Comment by pugalde** [comment]
That did the trick.Now I can add my own code. And yes, I was refering to Item Code. Thanks for the tip.
One last thing. I had to create a Product and it automatically took the item code Prod-00002. Because I was in a Hurry I had to buy it (PO created) and I had to sell it (SO created, delivered and invoiced) The thing is that I can't change the item code to my own code and I can't delete to create the same one with a different code because there are many documents created with that Item Code. Is it posible to change it?Maybe through "Import Data"?

**Comment by anandpdoshi** [comment]
Item > Menu > Rename 😄

**Comment by pugalde** [comment]
You made me feel dumb hahaha.

It worked, thanks a lot.

 

De: Anand Doshi [mailto:notifications@github.com] 
Enviado el: martes, 19 de abril de 2016 13:11
Para: frappe/erpnext <erpnext@noreply.github.com>
CC: pugalde <pugalde@toyvi.cl>
Asunto: Re: [frappe/erpnext] Can not change the reference (code) of a product (#5236)

 

Item > Menu > Rename 😄

**Comment by anandpdoshi** [comment]
@pugalde 👍
