### ISSUE TITLE
Translation of in Words

### ISSUE THREAD

**Issue by ramielian** [frappe/erpnext#5237]
Dear All...

this is a very big issue for the Asia region as the words are some kinda flipped not like in English,,,

We need to find a way to make this translatable and also modifiable in some way because it is very important for all transnational documents...

**Comment by anandpdoshi** [comment]
You can fix it and send a pull request at https://github.com/frappe/num2words

**Comment by ramielian** [comment]
@anandpdoshi do you mean i can translate it to Thai (the language we use) then send PR ?

am not sure how to integrate it with Frappe...

**Comment by anandpdoshi** [comment]
@ramielian yeah you need to edit the num2words repository and not frappe

**Comment by ramielian** [comment]
yup dont it already and sent a PR already:
https://github.com/frappe/num2words/pull/1
