### ISSUE TITLE
Attach file from existing file list

### ISSUE THREAD

**Issue by sbkolate** [frappe/erpnext#5238]
1) Add New Field "File" link to existing file doctype.
![upload_file](https://cloud.githubusercontent.com/assets/6648915/14641977/3b90f788-0666-11e6-972e-12b97d5877d7.png)

2) On selection on File, fetch file url from selected file into web link.
![kpifile2](https://cloud.githubusercontent.com/assets/6648915/14641980/3efffda6-0666-11e6-8a1c-59d8a1a6259d.png)

Click on Attach, Now existing file is gets attached current doc.

This is useful to attach broacher, checklist document and email from erpnext

**Comment by rmehta** [comment]
Just make a public file and add the `/public/` url?

**Comment by sbkolate** [comment]
I have extended​ file upload popup. 
User can search File Name from existing uploaded files and attach it to current doc,It will save time to copy past public url.
![attach](https://cloud.githubusercontent.com/assets/6648915/15926252/9b4870c4-2e58-11e6-95d3-22e1b02398cf.png)

It will also help if we have provision for bulk upload and attach multiple files like blueimp plugin
https://blueimp.github.io/jQuery-File-Upload/

**Comment by rmehta** [comment]
Where is the pull request?

**Comment by system19** [comment]
This is a very cool feature @sbkolate.

**Comment by sbkolate** [comment]
@rmehta 
Initially, I am planning to show file browser popup, but after some failed attempt, I have created this with small custom script.

If you think its helpful, I will send pull request.
```
frappe.ui.form.on("Quotation", "refresh", function(frm, doctype, name) {
	if(!cur_frm.doc.__islocal){
		cur_frm.add_custom_button(__('Attach File'),
			function() { cur_frm.cscript.attach_file_custom(); }, 'icon-retweet', 'btn-default')
	}
	
});	


cur_frm.cscript.attach_file_custom = function(frm, cdt, cdn) {
	standard_dialog = function(opts){
	  dialog = new frappe.ui.Dialog({
	    title: __('Upload File'),
	      fields: [
	          {fieldtype: "Section Break"},
	          {"fieldtype": "Link" , "fieldname": "file" , "label": "File Items", "options": "File"},

	        ],

	  });
	  var btn = dialog.set_primary_action(__("Attach"));
	  btn.removeClass("btn-primary").addClass("btn-default");
	  dialog.show();
	  // $(dialog.body).empty();
	  frappe.upload.make({
	    parent: dialog.body,
	    args: opts.args,
	    callback: function(attachment, r) {
	      dialog.hide();
	      if(opts.callback){
	        opts.callback(attachment, r);
	      }
	    },
	    on_select: function() {
	      btn.removeClass("btn-default").addClass("btn-primary");
	    },
	    onerror: function() {
	      dialog.hide();
	    },
	    btn: btn,
	    max_width: opts.max_width,
	    max_height: opts.max_height,
	  });

	  return dialog;
	}
	dialog = standard_dialog({
	  	"args": {
			  from_form: 1,
			  doctype: cur_frm.doctype,
			  docname: cur_frm.docname,
			},
	  	"callback": function(attachment, r) { 
	    msgprint("File uploaded successfully");
	    cur_frm.reload_doc(); },
	});
	var fd = dialog.fields_dict;
	$(fd.file.input).change(function() {
	    frappe.call({
	          'method': 'frappe.client.get_value',
	          'args': {
	              'doctype': 'File',
	              'fieldname': 'file_url',
	                'filters': {
	                  'name': dialog.get_value("file")
	                }
	              }
	              ,
	             callback: function(r){
	                  dialog.$wrapper.find('[name="file_url"]').val(r.message.file_url);

	             }
	       
	      });

	});
}

```

**Comment by rmehta** [comment]
@sbkolate add it to upload.js in frappe

**Comment by vaibhav007-droid** [comment]
VM5085:11 Uncaught ReferenceError: standard_dialog is not defined
    at init.cur_frm.cscript.attach_file_custom (eval at setup (script_manager.js:155), <anonymous>:11:18)

Got This Error..!!
