### ISSUE TITLE
add line to .csv files

### ISSUE THREAD

**Issue by cgpurbaugh** [frappe/erpnext#5239]
If a user opens a .csv file and their regional delimiter is ";" it will not open correctly. adding

`sep=,`

to the first line of the .csv file overrides the system settings, and solves this issue.

**Comment by MaxMorais** [comment]
@cgpurbaugh, I think that this is a more complex issue than the separator!

If the user open the CSV with the regional delimiter it can affect too,

Date Format
Number Format
Can have Unicode Issues too!

**Comment by anandpdoshi** [comment]
It would be best to support xlsx format for import

**Comment by cgpurbaugh** [comment]
xlsx support would be nice. . .
ods would be nice as well.
How about being able to import from google sheets format?  Is that doable?  If so, that'd be cool.

If support for xlsx, ods, or any other file format that can have multiple sheets, how would that be handled?

**Comment by rmehta** [comment]
@cgpurbaugh I could not find any such standard adding `sep=,` did not help. Can you refer and get back?

**Comment by cgpurbaugh** [comment]
It's just what I found while looking for solutions.  Not sure where to get an official answer from, but here is a post that goes into details about various solutions:

http://superuser.com/questions/407082/easiest-way-to-open-csv-with-commas-in-excel

**Comment by rmehta** [comment]
See the comments, it only works in Excel and only if you do some advanced settings

**Comment by cgpurbaugh** [comment]
When I tested it before, it worked in Open Office 5 as well.
