### ISSUE TITLE
Landed Cost Voucher to have editable Applicable Charges field

### ISSUE THREAD

**Issue by accountantpuntoitalia** [frappe/erpnext#5243]
### Applicable Charges field to be editable

Dear all,

After our phone conversation, we would like to ask to make the Applicable Charges field in the Landed Cost voucher to be editable.
The reason is that when we allocate the duties for the imported items in a Purchase Receipt, at the moment the system allocates the values automatically.  This does not correspond to the actual amounts of duties per each time as some items may have 0 duties and others different % of duties.
Therefore it is necessary that we can input manually the amount and the system can check that the total will correspond to the amount indicated in the field for the amount that needs to be distributed.

Please let us know soon as we need to update our COGS with several landed cost vouchers.

Thank you and best regards,

Quang

---

![applicable charges field](https://cloud.githubusercontent.com/assets/18569958/14667698/b8a84ad8-070a-11e6-94a5-9532941989bf.jpg)

**Comment by me2ne** [comment]
my opinion  landed cost , should be optional  how to divide custom fee per items , how divide shipping fee , and ....  and in item setting should be  enter item dimension (gross weigh for shipping calculation ) . 
so in landed cost can calculate shipping per items . .
