### ISSUE TITLE
[WIP] Wiki Cleanup

### ISSUE THREAD

**Issue by vjFaLk** [frappe/erpnext#5247]
To Remove : 
- [ ] https://github.com/frappe/erpnext/wiki/Version-4-Permission-Use-Cases
- [ ] https://github.com/frappe/erpnext/wiki/Updating-ERPNext-Instance
- [ ] https://github.com/frappe/erpnext/wiki/Ubuntu-HA-Cluster-with-lsyncd,-remote-MariaDB,-Apache-Reverse-Proxy-Setup-Guide
- [ ] https://github.com/frappe/erpnext/wiki/Version-5-Release-Notes
- [ ] https://github.com/frappe/erpnext/wiki/How-to-Install-ERPNext-Version-3
- [ ] https://github.com/frappe/erpnext/wiki/Test-Checklists (Append to PR Template?)
- [ ] https://github.com/frappe/erpnext/wiki/Adding-Custom-Form-to-Website
- [ ] https://github.com/frappe/erpnext/wiki/Developer-Docs
- [ ] https://github.com/frappe/erpnext/wiki/ERPNext-Upgrade-to-Version-5
- [ ] https://github.com/frappe/erpnext/wiki/Apache-HTTP-Settings-for-Mac-OS
- [ ] https://github.com/frappe/erpnext/wiki/Improve-Precision-of-Stock-Valuation
- [ ] https://github.com/frappe/erpnext/wiki/Install-ERPNext-on-Debian-based-systems
- [ ] https://github.com/frappe/erpnext/wiki/Install-ERPNext-on-RedHat-based-systems
- [ ] https://github.com/frappe/erpnext/wiki/Integrating-Emails-in-ERPNext
- [ ] https://github.com/frappe/erpnext/wiki/Manufacturing-Module
- [ ] https://github.com/frappe/erpnext/wiki/Migrating-your-erpnext-instance-to-wsgi
- [ ] https://github.com/frappe/erpnext/wiki/MySQL-configuration-file
- [ ] https://github.com/frappe/erpnext/wiki/Future-Development:-Tracking-Productivity
- [ ] https://github.com/frappe/erpnext/wiki/Setting-up-Backup-Manager
- [ ] https://github.com/frappe/erpnext/wiki/WSGI-Production-Deployment

To Move: 
- [ ] Print Formats
- [ ] https://github.com/frappe/erpnext/wiki/Restoring-From-ERPNext-Backup

**Comment by anandpdoshi** [comment]
Move https://github.com/frappe/erpnext/wiki/Manufacturing-Module to an issue
