### ISSUE TITLE
Daily Digest - Daily Reminders

### ISSUE THREAD

**Issue by Tropicalrambler** [frappe/erpnext#5250]
### Issue Description

On a self-install: When I receive the Daily Digest for ERPNext by email, more specifically the To Do List, I click open and the link defaults to: site1.local  instead of the ip address where we are hosting the database an ERPNext.

Steps to reproduce:   setup a daily digest email.  create a to do item for a specific date. Receive daily digest email with item in open status. Click on link to open the item in ERPNext. Web browser opens successfully, but referred  URL is site.1local/desk#Form/ToDo/  instead of 111.111.111.111/desk#Form/ToDo/

Another e-mail generated by ERPNext after an assignment for a ToDo, comes with the link properly formatted and functions perfectly. This means that a variable somewhere for the Daily Digest email is not obtaining the correct IP address for the Daily Digest. 

---

### Checklist

- [] This is a bug report / feature request and not just a problem I am facing. 
      (Go to https://discuss.erpnext.com for help)
- [x] I have searched https://github.com/frappe/erpnext/issues and didn't find a similar issue
- [x] I have mentioned steps to reproduce the issue
- [ ] I have added screenshots / video / mockups
- [x] I have not edited the code of Frappe and ERPNext
- [x] I have mentioned a python error traceback or javascript error [optional]

---

### Specs

- ERPNext version:  
- Frappe version: 
- Operating System: IOs 
- Browser: Chrome
- Language: English

---

> **Note:** If you are reporting a security issue, please send a private email to <info@frappe.io>

**Comment by rmehta** [comment]
Did you set `host_name` in site_config.json?

https://discuss.erpnext.com/t/renaming-site1-local-to-domain-com-issue/3497
