### ISSUE TITLE
[Item] appears multiple times in Price List issue while creating any SO/SI etc

### ISSUE THREAD

**Issue by sbkolate** [frappe/erpnext#5251]
Hello,

We are always getting this error.
`Item Upper Bearing Plate appears multiple times in Price List Standard Selling`
![sales_inv](https://cloud.githubusercontent.com/assets/6648915/14699551/575e7d22-07b6-11e6-9474-e5d850bc7230.png)

I have reproduced this error on your demo server.
Steps to reproduce.
1) Go to Item Price List Standard Selling
2) Select Item 'Upper Bearing Plate' and add rate 0
3) Now, create Sales Invoice with Item 'Upper Bearing Plate' and rate '100'
4) ERPNext finds price is zero and tries to add it into Price List Standard Selling.
5) Click on Save, it will throws above error. `Item Upper Bearing Plate appears multiple times in Price List Standard Selling`

Thanks,
Sambhaji

**Comment by rmehta** [comment]
@sbkolate you should be fixing such bugs yourself!
