### ISSUE TITLE
POS module, stock reports slowed down after 15 months

### ISSUE THREAD

**Issue by noetico** [frappe/erpnext#5257]
### submitting sales invoices and viewing certain reports have become slow after about 15 months of usage

We have been noticing a gradual decline in ability to submit sales invoices, the system becomes very slow, viewing stock balance reports was also impossible, any saved invoices older than about a day take a while to submit, older ones may never. We noticed its due to the database size as its a retail business. 

Now, we got ssd harddives for all critical systems, pos and server systems, that helped greatly as the stock balance report started displaying again after months of inability, also the sales module became faster. The core of the problem is the 'update stock' feature; which is a very very good feature we cannot disable permanently, we had to turn it off temporarily to get older draft invoices to submit. 

I am proposing the addition of a feature in stock or accounts settings that allows for deferred stock updates, as such an administrator can set a time say 00:00 hours to run stock updates, so sales proceed without hiccups for users whose data has grown very large, oura is nearly 28gb. I think this will help, because more users arw going to face this issue sometime as the data grows, unfortunately for those who stuck to v4, there may not be an easy way out. 

---

### Checklist

- [ ] This is a bug report / feature request and not just a problem I am facing. 
      (Go to https://discuss.erpnext.com for help)
- [ ] I have searched https://github.com/frappe/erpnext/issues and didn't find a similar issue
- [ ] I have mentioned steps to reproduce the issue
- [ ] I have added screenshots / video / mockups
- [ ] I have not edited the code of Frappe and ERPNext
- [ ] I have mentioned a python error traceback or javascript error [optional]

---

### Specs

- ERPNext version:  
- Frappe version: 
- Operating System: 
- Browser: 
- Language: 

---

> **Note:** If you are reporting a security issue, please send a private email to <info@frappe.io>

**Comment by rmehta** [comment]
@noetico why are you still on v4? there have been tons of improvements in v6

**Comment by noetico** [comment]
Hello Sir; good to hear from you; but I had also mad e complaint that it's
been impossible to update any v4 versions from my part of the world; trust
me I have tried well over 200 times; even v5, I have tried the update; many
times I end up with "we are updating..." or database connection errors; so
for a while now I never update for fear of loosing access. I also see this
on the forums; This is the only thing I find super scary with erpnext; the
updates are extremely delicate. This image has been in use for a while and
we have made copies and tried bench update with all options plus tips from
the forums; nothing worked. I really wish there could be a rollback feature
or maybe updates done through the interface with setup options like
rollback if update fails etc so people can safely try to update.
Pleeeeease; we really appreciate erpnext and keep sending the word out and
we are always proud when you make things better.... a lot of users will be
delighted if this can happen.

Thanks @rmehta

**Comment by noetico** [comment]
In addition; imagine if you can have a "check for updates button, a
snapshot feature for roll-back and an update button; now the user is free
to switch to a snapshot while retaining transactional data; I know this is
a big task; but it's worth every bit of code; I am not good at python or
the bench else I would devote myself to getting this updating feature done
so you dont have to bother and the community enjoys it, by the wy; thanks
for making the pos limit I suggested a global update; it shows how good
your team is.

**Comment by rmehta** [comment]
@noetico  you should get someone to upgrade it for you who understands the patch system. Its not so hard.

Post a job at https://community.erpnext.com/jobs
