### ISSUE TITLE
Repost valuation rate for all future vouchers with target warehouse

### ISSUE THREAD

**Issue by nabinhait** [frappe/erpnext#5259]
### Checklist
- [ ] This is a bug report / feature request and not just a problem I am facing. 
    (Go to https://discuss.erpnext.com for help)
- [ ] I have searched https://github.com/frappe/erpnext/issues and didn't find a similar issue
- [ ] I have mentioned steps to reproduce the issue
- [ ] I have added screenshots / video / mockups
- [ ] I have not edited the code of Frappe and ERPNext
- [ ] I have mentioned a python error traceback or javascript error [optional]

---
### Specs
- ERPNext version:  
- Frappe version: 
- Operating System: 
- Browser: 
- Language: 

---

> **Note:** If you are reporting a security issue, please send a private email to info@frappe.io

**Comment by ManarSlik** [comment]
@nabinhait ,
Any progress in this regard ?

**Comment by nabinhait** [comment]
@ManarSlik Nope, still could not manage time to fix this.

**Comment by ShashaQin** [comment]
@nabinhait  did the commit of 'Item Valuation Rate in case of negative inventory' solve this issue?

**Comment by nabinhait** [comment]
@ShashaQin No, it does not fix this issue.
