### ISSUE TITLE
Can't disable dropbox backup

### ISSUE THREAD

**Issue by graphskill** [frappe/erpnext#5260]
### Issue Description

Description...

Using cloud hosting. I cannot disable dropbox backup. When i remove the tick from the box there is no "save" button. So when I log out and in again the tick is still there

Frappe Framework
Close
Open Source Applications for the Web

 Website: https://frappe.io

 Source: https://github.com/frappe

Installed Apps

ERPNext: v6.27.11

Frappe Framework: v6.27.14

Frappe Subscription: v0.0.1

Knowledge Base: v0.0.1

Mandrill Integration: v0.0.1

Paypal Integration: v0.0.1

---

### Checklist

- [ ] This is a bug report / feature request and not just a problem I am facing. 
      (Go to https://discuss.erpnext.com for help)
- [ ] I have searched https://github.com/frappe/erpnext/issues and didn't find a similar issue
- [ ] I have mentioned steps to reproduce the issue
- [ ] I have added screenshots / video / mockups
- [ ] I have not edited the code of Frappe and ERPNext
- [ ] I have mentioned a python error traceback or javascript error [optional]

---

### Specs

- ERPNext version:  
- Frappe version: 
- Operating System: 
- Browser: 
- Language: 

---

> **Note:** If you are reporting a security issue, please send a private email to <info@frappe.io>

**Comment by neilLasrado** [comment]
@graphskill was able to replicate this. WIll fix it and update you once it is done.

**Comment by vjFaLk** [comment]
@graphskill This is not intuitive, but you can disable it by going in "Menu" and selecting "Delete"
