### ISSUE TITLE
Dropbox stopped backups

### ISSUE THREAD

**Issue by DrTrills** [frappe/erpnext#5271]
### Issue Description

Dropbox backups stopped on 4/13/2016. I have had successful backups since 2014 starting with V4. I am unsure what to do, I have made a new app in the dropbox developer console, authorized the new app with ERPNext and still nothing. I posted in the forum without much luck. I am getting concerned now as my site is going almost half a month without backups to an external provider.

I updated the site_config file with the new api keys, made sure my server had the pip dropbox etc. packages installed and updated yet still no luck.
---

### Checklist

- [x] This is a bug report / feature request and not just a problem I am facing. 
      (Go to https://discuss.erpnext.com for help)
- [x] I have searched https://github.com/frappe/erpnext/issues and didn't find a similar issue
- [x] I have mentioned steps to reproduce the issue
- [ ] I have added screenshots / video / mockups
- [  ] I have not edited the code of Frappe and ERPNext
- [ ] I have mentioned a python error traceback or javascript error [optional]

---

### Specs

- ERPNext version:  6.27.11
- Frappe version: 6.27.14
- Operating System: Ubuntu
- Browser: Chrome
- Language: English

---

> **Note:** If you are reporting a security issue, please send a private email to <info@frappe.io>

**Comment by anandpdoshi** [comment]
Check the 'Scheduler Log' list for any errors. You can access it via Awesome Bar or Setup module

**Comment by DrTrills** [comment]
@anandpdoshi Thanks for the reply!

Here is the error:
Method: 
`frappe.utils.error.collect_error_snapshots`
Error:
`Method: all, Handler: frappe.utils.error.collect_error_snapshots
Traceback (innermost last):
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/tasks.py", line 114, in scheduler_task
    frappe.get_attr(handler)()
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/utils/error.py", line 178, in collect_error_snapshots
    clear_old_snapshots()
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/utils/error.py", line 195, in clear_old_snapshots
    ctime = datetime.datetime.fromtimestamp(os.path.getctime(file))
  File "/home/erpnext/frappe-bench/env/lib/python2.7/genericpath.py", line 64, in getctime
    return os.stat(filename).st_ctime
 OSError: [Errno 2] No such file or directory: '2016-05-04 15:52:11.934444-104.197.100.16-d58.json'
`

Thank you!

**Comment by anandpdoshi** [comment]
This is an unrelated error. You will need to browse through the logs to
find one for dropbox backup.

**Comment by DrTrills** [comment]
@anandpdoshi My mistake!

I have 5 errors, but they're all the same as above. None directly connected to dropbox. Perhaps when V7 is out I will do a fresh install and import the data from our v6 install in the hopes it works correctly then.

If you have any other ideas i'd be happy to help with reporting this issue. Thanks!

**Comment by anandpdoshi** [comment]
Try doing setup dropbox backup again via the UI and check if you receive any error
