### ISSUE TITLE
bench update error

### ISSUE THREAD

**Issue by omnison** [frappe/erpnext#5272]
### Issue Description

Today I use “bench update”, and find error: 
```
[root@123 ~]# bench update
remote: Counting objects: 1113, done.
remote: Compressing objects: 100% (166/166), done.
remote: Total 1113 (delta 756), reused 701 (delta 698), pack-reused 249
Receiving objects: 100% (1113/1113), 390.26 KiB | 166.00 KiB/s, done.
Resolving deltas: 100% (847/847), completed with 240 local objects.
From https://github.com/frappe/frappe
   9c7d1f2..7801d94  develop    -> upstream/develop
   cc11832..984ec6c  gh-pages   -> upstream/gh-pages
   f85f2f5..8373c87  hotfix     -> upstream/hotfix
   70a4e33..eecd537  master     -> upstream/master
 * [new tag]         v6.27.14   -> v6.27.14
From https://github.com/frappe/frappe
 * [new tag]         v6.27.11   -> v6.27.11
 * [new tag]         v6.27.12   -> v6.27.12
 * [new tag]         v6.27.13   -> v6.27.13
INFO:bench.utils:updating bench
remote: Counting objects: 39, done.
remote: Total 39 (delta 20), reused 20 (delta 20), pack-reused 19
Unpacking objects: 100% (39/39), done.
From https://github.com/frappe/bench
   6862eb7..6060915  master     -> origin/master
   4d90001..ca97764  develop    -> origin/develop
Updating 6862eb7..6060915
Fast-forward
 bench/config/production_setup.py | 7 +++++--
 1 file changed, 5 insertions(+), 2 deletions(-)
Requirement already satisfied (use --upgrade to upgrade): Pillow in ./env/lib/python2.7/site-packages
INFO:bench.app:pulling frappe
From https://github.com/frappe/frappe
 * branch            develop    -> FETCH_HEAD
Updating 9c7d1f2..7801d94
error: Your local changes to the following files would be overwritten by merge:
	frappe/website/website_theme/standard/standard.json
Please, commit your changes or stash them before you can merge.
Aborting
Traceback (most recent call last):
  File "/usr/bin/bench", line 9, in <module>
    load_entry_point('bench==0.1', 'console_scripts', 'bench')()
  File "/home/frappe/bench-repo/bench/cli.py", line 40, in cli
    bench_command()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/bench-repo/bench/commands/update.py", line 60, in update
    _update(pull, patch, build, bench, auto, restart_supervisor, requirements, no_backup, upgrade, force=force)
  File "/home/frappe/bench-repo/bench/commands/update.py", line 76, in _update
    pull_all_apps(bench=bench_path)
  File "/home/frappe/bench-repo/bench/app.py", line 92, in pull_all_apps
    exec_cmd("git pull {rebase} upstream {branch}".format(rebase=rebase, branch=get_current_branch(app, bench=bench)), cwd=app_dir)
  File "/home/frappe/bench-repo/bench/utils.py", line 99, in exec_cmd
    raise CommandFailedError(cmd)
bench.utils.CommandFailedError: git pull  upstream develop
```

It says I changed frappe/website/website_theme/standard/standard.json,but I did’t change any code. 
---

### Checklist

- [ ] This is a bug report / feature request and not just a problem I am facing. 
      (Go to https://discuss.erpnext.com for help)
- [ ] I have searched https://github.com/frappe/erpnext/issues and didn't find a similar issue
- [ ] I have mentioned steps to reproduce the issue
- [ ] I have added screenshots / video / mockups
- [ #] I have not edited the code of Frappe and ERPNext
- [ ] I have mentioned a python error traceback or javascript error [optional]

---

### Specs

- ERPNext version:  v6.27.9
- Frappe version: v6.27.10
- Operating System: Mac
- Browser: Chrome
- Language: CN

---

> **Note:** If you are reporting a security issue, please send a private email to <info@frappe.io>

**Comment by anandpdoshi** [comment]
@omnison you must've saved the standard website theme using administrator login and when in developer mode

**Comment by omnison** [comment]
then please tell me, how to solve this problem, i heard version 7 is ready to release, if this issue cannot be solved, i cannot update to version 7.

**Comment by anandpdoshi** [comment]
Go to apps/frappe folder, run `git stash`

**Comment by omnison** [comment]
`[frappe@123 ~]$ cd frappe-bench
[frappe@123 frappe-bench]$ cd apps/frappe
[frappe@123 frappe]$ git stash

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident name (for <frappe@123.(none)>) not allowed
Cannot save the current index state
`
how to proceed next?

**Comment by omnison** [comment]
git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

what should be global user email?
what should be global user name?

**Comment by omnison** [comment]
I just using my ID details in erpnext:
`[frappe@123 frappe]$ git config --global user.email "gavin@mankem.com"
[frappe@123 frappe]$ git config --global user.name "gavin"
[frappe@123 frappe]$ git stash
Saved working directory and index state WIP on develop: 2eb9e91 [fix] quick_entry
HEAD is now at 2eb9e91 [fix] quick_entry`

**Comment by omnison** [comment]
Thanks you.

**Comment by vjFaLk** [comment]
@omnison The ideal email and username should be the same as your Github account so Github can automatically link it up with your profile

However, it's not necessary

**Comment by omnison** [comment]
@vjFaLk  now i already setup :
git config --global user.email "gavin@mankem.com"
git config --global user.name "gavin"

how can i change them to Github account?

**Comment by vjFaLk** [comment]
@omnison Just run the same commands again, but with your GitHub email. You can set the name as anything though.

**Comment by omnison** [comment]
Done. thank you very much.

**Comment by vjFaLk** [comment]
Fixed?
