### ISSUE TITLE
Error Material request quantity generated by Production Planning tool

### ISSUE THREAD

**Issue by chaoyee** [frappe/erpnext#5274]
### Error Material request quantity generated by Production Planning tool

Description...

1, If we use the Production Planning tool for a Sales order say SO 001 which needs manufacturing : it generates the material Request for raw material for that sales order considering the Stock , material Request Purchase & the Purchase order raised

2, we order the material needed for manufacturing against the SO 001

3, Now Before we transfer the material for manufacturing If we use the Production Planning tool for a new sales order say SO 002 for the same item or different item but needs some of the common raw material - then the items already ordered or the items in stock are considered( Which are supposed to reserved for SOI 001 ) & the new material Request is only generated for Shortages & does not consider the requirement of SO 001

### Checklist

- [x] This is a bug report / feature request and not just a problem I am facing. 
      (Go to https://discuss.erpnext.com for help)
- [x] I have searched https://github.com/frappe/erpnext/issues and didn't find a similar issue
- [x] I have mentioned steps to reproduce the issue
- [x] I have not edited the code of Frappe and ERPNext

### Specs

- ERPNext version: v6.27.12 
- Frappe version: v6.27.15
- Operating System: Mac OS X 10.11.4 
- Browser: Chrome
- Language: English

**Comment by rmehta** [comment]
Option added to generate material for full requirements (and not only shortage)
