### ISSUE TITLE
Quotation Improvements

### ISSUE THREAD

**Issue by agerken** [frappe/erpnext#5279]
Comes from post: https://discuss.erpnext.com/t/improvement-wishlist-minor-things/11826?u=agerken

This ties in closely with my Project module enhancement ideas.

At the time of Quote it would be advantageous to be able to select if the Quote is Fixed or Variable. A fixed quote would be used as "normal" to create a fixed Sales Order, Invoice, etc. If this is selected and a Project was created, the cost keeping would just be for business purposes, and the Invoice would always be driven by the Sales Order amount.

A Variable type quote would be used for a Time and Material type job, which would likely be driven by a project. In this model the Quote is treated as simply an estimate, and the invoice amount is driven by actual Project costs. It would also be useful to include an NTE (not to exceed) value to a Variable quote, as many customers request this. If a NTE amount was entered, it would block the system from Invoicing more than that amount.

Fixed vs Variable could also drive different default Terms and Conditions to make sure the customer is aware of the stipulations of each type.

Here's a simple Custom Field showing how it would look:
![quote](https://cloud.githubusercontent.com/assets/18719200/14888910/65ce7cf8-0d2a-11e6-9cae-ef929e9cb53d.jpg)

**Comment by rmehta** [comment]
Can be easily fixed by custom fields

**Comment by agerken** [comment]
@rmehta Not really. I have a custom field for Quotation Type as above, but this improvement would tie back into Sales Orders, Projects, etc. If you take a look at my other issues/improvements I think you'll see it's not as simple as adding a custom field.
