### ISSUE TITLE
Sales Order Improvements

### ISSUE THREAD

**Issue by agerken** [frappe/erpnext#5280]
This comes from the discussion at: https://discuss.erpnext.com/t/improvement-wishlist-minor-things/11826?u=agerken

After submitting a Sales Order it would be really nice to be able to create a Project or Production Order right from there. Production Order seems pretty self explanatory, and would just pull in the manufactured products from Sales Order.

Creating a Project would pull the "Service" line items from the Sales Order and create Tasks based on them. Estimated Cost for the project would be pulled from the Sales Order amount. Fixed vs Variable attribute (see my Quote Improvement post) would come from the Quote, and would dictate how the Project was Invoiced... a fixed cost or based on the actual Project costs, with an optional max NTE amount.
![sales order](https://cloud.githubusercontent.com/assets/18719200/14889243/07d84014-0d2c-11e6-919f-075bfc146871.jpg)

**Comment by Devens** [comment]
+1
