### ISSUE TITLE
Project Improvements

### ISSUE THREAD

**Issue by agerken** [frappe/erpnext#5281]
This comes from the discussion at: https://discuss.erpnext.com/t/improvement-wishlist-minor-things/11826?u=agerken

This is definitely the area that ERPNext could use the most amount of work. This would be an incredibly powerful tool if done right, and would be the thing that would blow other systems like Odoo out of the water.

The first thing is that I would love to pull Project details from a Sales Order, see my Sales Order Improvements post.

I'd also like to be able to "Make" a Time Log or Invoice right from a project, this would eliminate a lot of clicking around. It would also be HUGE to have a clock in/clock out function to automatically create time logs based on the user, clocking and out time. The Activity Type may have to be a selection at the time of clock in, but that's easy enough. The "Billable" could be preset based on if the Quote/Sales Order drove the Project to being Fixed cost or Variable (Fixed would not be billable, Variable would be billable)
![project top](https://cloud.githubusercontent.com/assets/18719200/14889573/59dc6326-0d2d-11e6-9f23-9110cb04dd12.jpg)

The second big thing is the Project accounting needs a lot of attention to be useful. The Estimated Cost should come from the Sales Order. The total billing amount should come from the billing amount from Time logs, Material Costs, Expense Costs, and Manufacturing Costs.
![project accounting](https://cloud.githubusercontent.com/assets/18719200/14889829/668f6e6e-0d2e-11e6-97af-7eebf6547275.jpg)

Manufacturing Costs should come from Production Orders that are associated with a Project. Material Cost should come from any Sales Invoice, Purchase Order, or JV that is associated with the Project.

The "Margin" area also needs work. The Gross Margin should come from the Billing Amount (above) minus the Costing amount of Time Logs, material purchases, etc. I'd also like to have
-"Amount Invoiced" is just that - how much of the Project has been Invoiced.
- "Amount to be Invoiced" to be pulled from Total Billing minus "Amount Invoiced"
  -"Amount Paid" to come from Payments made against Invoices associated with the Project.
  ![projectmargin](https://cloud.githubusercontent.com/assets/18719200/14890091/4c1fcc62-0d2f-11e6-859d-c9969d79b950.jpg)

**Comment by dumiller** [comment]
+1 Great suggestions. It would be good to have two kinds of projects: Cost Plus and Quoted or Projects. A dashboard to see the current man hours , materials costs, labor costs and profit margin associated with each project.

**Comment by addymuliady** [comment]
+1
