### ISSUE TITLE
Task Improvements

### ISSUE THREAD

**Issue by agerken** [frappe/erpnext#5282]
This comes from the discussion at: https://discuss.erpnext.com/t/improvement-wishlist-minor-things/11826?u=agerken

The improvements for Task I would like are very similar to Project. I'd like to have a "Make" option for Invoice and Time Log, as well as a Clock in/out feature. It would also be great to have a Task auto create an Invoice upon its completion.
![task](https://cloud.githubusercontent.com/assets/18719200/14890303/0e01ecd4-0d30-11e6-93c8-835532c111c1.jpg)
This Invoicing and Time Log would tie back to the Project accounting stuff I suggested in my Project Improvements post.

**Comment by joolsr** [comment]
Clock In/Out feature has now been added to Develop
