### ISSUE TITLE
Create Standard Operation Cost 

### ISSUE THREAD

**Issue by agerken** [frappe/erpnext#5283]
It would be great to have a "Standard Operation Cost" to track the labor rates of Production Orders instead of relying only on Workstations. I currently have a 1:1 relationship between Workstations and Operations but it gets me in trouble when I have to submit a Time Log for the same Operation at the same time, the system complains about having a conflict at the Workstation.

![operation](https://cloud.githubusercontent.com/assets/18719200/14890500/ef1b5d36-0d30-11e6-90b4-9db9b73e83ab.jpg)

It also should not be mandatory to have a Workstation selected. I would propose that if a Workstation was selected, and there were costs associated to that Workstation, that would override the Default Operation Cost.

**Comment by rmehta** [comment]
This will be redesigned in the new timesheets
