### ISSUE TITLE
Creating Pay Slips for Hourly Employees

### ISSUE THREAD

**Issue by agerken** [frappe/erpnext#5286]
I'd like a tool to create a pay slip for hourly employees. I think this would be fairly straight forward: it could be a simple form where you enter the Employee and date range and hit generate. It would pull all time entered in Time Logs, add them up. A "Make" button could be created to create a JV, and a check.

This could also be run for any Employee marked as "hourly" and email them their pay slips.

It could also generate a Supervisor Approval time document that would compile all a manager's employees onto one report, and when approved it would generate the individual slips and JV's.

This one is just an idea, I don't really have any specifics exactly what I'd like to see yet.

**Comment by rmehta** [comment]
Coming in v7

**Comment by agerken** [comment]
Looking forward to it @rmehta! Sounds like v7 is going to be a really good ERP! I wish I had time to learn the development and help more, maybe in the next couple months.
