### ISSUE TITLE
[Paid Development] Let's Encrypt Integration

### ISSUE THREAD

**Issue by user002** [frappe/erpnext#5288]
A.  I am potentially willing to pay for this feature.

B.  Feature request: integrate Let's Encrypt ( https://letsencrypt.org/ ) SSL certificate creation / management / maintenance / renewal / etc. into ERPNext or similar functionality.  Feature is important as security and privacy are inherently important in business and life.

C.  https://community.letsencrypt.org/t/integration-guide/13123 has details on how to maybe do it for ERPNext hosted (and maybe the source code too -- not sure).

D.  https://github.com/letsencrypt/letsencrypt/wiki/Links has tools / implementations that might be useful in development.

E.  https://letsencrypt.readthedocs.io/en/latest/ is the Let's Encrypt client documentation.  https://www.eff.org/deeplinks/2016/05/announcing-certbot-new-tls-robot has details on "certbot" which could be useful in implementing this feature.

F.  Anonymous sponsoring is requested.

G.  Reference: https://frappe.github.io/frappe/user/en/bench/guides/configuring-https.html

**Comment by user002** [comment]
Reference: https://frappe.github.io/frappe/user/en/bench/guides/configuring-https.html

**Comment by anandpdoshi** [comment]
See: https://github.com/frappe/bench/wiki/Setting-up-SSL-certificates-from-Let's-Encrypt-for-sites <https://github.com/frappe/bench/wiki/Setting-up-SSL-certificates-from-Let's-Encrypt-for-sites>

Best,
Anand Doshi

ERPNext

**Comment by user002** [comment]
Thanks for the detail -- I missed that in my search -- as might many many other users.  Yet, I think such functionality should be more "in your face" as many people do not know what SSL / HTTPS are nor the the importance of them.  And, they may not have the technical acumen to take on the solution proposed in the above URL.

I propose, at a first step, taking https://github.com/frappe/bench/wiki/Setting-up-SSL-certificates-from-Let's-Encrypt-for-sites and adding it to https://frappe.github.io/frappe/user/en/bench/guides/configuring-https.html

Even better, add Let's Encrypt capability to the SSL / HTTPS setup process.  Let the user choose among, paid CA, Let's Encrypt CA, or self signed.  I am not promoting Let's Encrypt but rather security and privacy.  SSL / HTTPS is still underused.  Should be mandatory for almost all use cases in today's world.  ERPNext can do a blog post about the enhanced security it now offers after implementing "SSL/HTTPS for Dummies" functionality into ERPNext.

I am not looking to spend money haphazardly but I think this functionality needs to be more user friendly and a default setting.

**Comment by anandpdoshi** [comment]
Agreed

**Comment by rmehta** [comment]
Fixed via https://github.com/frappe/bench/commit/312e59f44bf8cea4069c316b7d536c6d21ae1983

**Comment by iramireze** [comment]
Hi rmehta -

sudo bench setup lets-encrypt site1.local is not working. Any ideas?

This is the system answer:

----
Usage: bench setup [OPTIONS] COMMAND [ARGS]...
Error: No such command "lets-encrypt".
----

Regards,

**Comment by yashodhank** [comment]
It only works with public domain names.

**Comment by yashodhank** [comment]
Probably your are on bench version 1, let's encrypt only available with new
bench version 2.
