### ISSUE TITLE
Currency not showing the currency symbol

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#5293]
I have added custom fields to quote item and marked them as "currency", however it is not rendered with the currency symbol.

<img width="711" alt="bildschirmfoto 2016-04-30 um 13 43 25" src="https://cloud.githubusercontent.com/assets/9136094/14935654/8a731e8c-0ed9-11e6-9bbf-f994edebd488.png">

**Comment by rmehta** [comment]
You need to set it to the correct currency field (containing the currency link) with options (hint: see other currency fields)
