### ISSUE TITLE
Production Planing tool

### ISSUE THREAD

**Issue by MANOJMAINKAR** [frappe/erpnext#5302]
Filter option required to select specific warehouse to download Material Required csv file

**Comment by rmehta** [comment]
Exists

**Comment by MANOJMAINKAR** [comment]
But not working while exporting csv file
Also required one column in exported csv file 'Qty to Procure' =((Order Qty-Actual Qty)-Required Qty)

**Comment by MANOJMAINKAR** [comment]
But not working 

On 09-06-2016 02:40 PM, Rushabh Mehta wrote: 

>
Exists 
> 
> --
> You are receiving this because you authored the
thread.
> Reply to this email directly, view it on GitHub [1], or mute
the thread [2].

-- 

Print this message only if necessary ...SAVE TREES


 

Links:
------
[1]
https://github.com/frappe/erpnext/issues/5302#issuecomment-224840759
[2]
https://github.com/notifications/unsubscribe/AKRa5tkw44P1ghxs2XlyK1Dl5K8ZtB_tks5qJ9ifgaJpZM4IV7ad
