### ISSUE TITLE
Naming Series

### ISSUE THREAD

**Issue by MANOJMAINKAR** [frappe/erpnext#5303]
Customize naming series option required for Bill of Material

**Comment by rmehta** [comment]
How do you want to customize?

**Comment by MANOJMAINKAR** [comment]
BOM name can be user define same as project name , not necessary to have
any BOM naming series. 

Manoj 

On 02-06-2016 05:57 PM, Rushabh Mehta wrote: 

> How do you want to customize? 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1] https://github.com/frappe/erpnext/issues/5303#issuecomment-223276453
[2]
https://github.com/notifications/unsubscribe/AKRa5lU_wVJXcE_pMcT0IW3xTDaF4dnJks5qHswwgaJpZM4IV7em
