### ISSUE TITLE
STUCK ON LOADING IN LIST VIEW

### ISSUE THREAD

**Issue by sumeetagra** [frappe/erpnext#5309]
![screen shot 2016-05-04 at 4 52 35 pm](https://cloud.githubusercontent.com/assets/19186564/15012736/b4c00780-1218-11e6-848f-db8f5c99cbee.png)

**Comment by sumeetagra** [comment]
JAVA Error Console Snap:
![screen shot 2016-05-04 at 9 43 30 pm](https://cloud.githubusercontent.com/assets/19186564/15020826/642c90f8-1241-11e6-860b-eb710f145f99.png)

**Comment by anandpdoshi** [comment]
Solution: https://discuss.erpnext.com/t/sales-purchase-order-list-wont-load/12271/33?u=anand
