### ISSUE TITLE
[Feature] Routings + Wiki + Quality System Documentation Capability

### ISSUE THREAD

**Issue by user002** [frappe/erpnext#5310]
I wish for routings + wiki functionality to be added to ERPNext.  Adding appropriate wiki functionality will give ERPNext a full quality system documentation capability.  These features are related and that is why they are being requested in a single request.

These features are important because:

A.  Routings are fundamental to any ERP system that supports manufacturing (reference: https://discuss.erpnext.com/t/production-routing-for-items/4673 ).  In addition, routings are very useful for guiding the work of non-manufactruing operations and can be a substitute or improvement over projects in some environments.  See the links below for evidence of the ubiquity of routings in ERP systems for manufacturing as well as details on what type of functionality is standard for most routing features.
- https://docs.oracle.com/cd/E16582_01/doc.91/e15128/enter_wc_and_rtg_instructs.htm#EOAPD00318
- https://www.configureone.com/product-configurators/boms-routings-part-numbering/manufacturing-routings/
- http://www.managementstudyguide.com/production-module-bom-and-routing.htm
- http://help.sap.com/saphelp_me52/helpdata/en/9c/f01debaa804b4c9f59c6d5f9c8a5d0/content.htm
- http://www.opentaps.org/docs/index.php/Production_Routings
- https://docs.oracle.com/cd/E26228_01/doc.93/e21775/ch_rev_bills_mat_rout_fm.htm#WEAMA152
- https://www.dbamanufacturing.com/features/routing/
- http://www.netsuite.com/portal/common/pdf/ds-manufacturing-wip.pdf
- http://www.fitrix.com/erp-software/standard-routing/
- https://www.odoo.com/forum/help-1/question/how-to-use-bom-working-center-operation-routing-etc-for-modeling-stool-manufacturing-2914

B.  A wiki allows documentation of organizations policies and processes to include how to use ERPNext beyond what is provided in the ERPNext manual.  More importantly, a wiki combined with existing ERPNext functionality will provide full quality system documentation capability in ERPNext -- something very few ERP packages offer today.  Quality system documentation generally consists of 4 layers (reference: http://www.quality.co.uk/isoadvic/dqs.htm and https://encrypted.google.com/search?q=Quality+System+Documentation&hl=en&tbm=isch&tbo=u&source=univ&sa=X&ved=0ahUKEwi60v6Wx7PMAhWMjo4KHYKZBdEQsAQIOA&biw=1541&bih=803 ) per the below.
- Quality Manual - This document normally describes the policy, organization and responsibilities of the organization. It would also commonly contain a brief policy statement on each of the individual clause requirements of the quality standard such as ISO9100.
- Procedures - These documents describe the processes of the organization, and the best practice to achieve success in those processes. It is a good idea to ensure the procedures answer the following questions about each process: Why?  Who?  When?  Where?  What?  How?
- Work Instructions - These documents normally describe a sub-process in some detail, answering one of the above questions (e.g. what or how).
- Documents - These are the items completed while undertaking the process, forming a means of communication and a record of events.

Today, many of the "Documents" aspect of a quality system can be provided with the current features of ERPNext.  Examples: invoices, packing lists, work orders, and quotes.  Routings can be work instructions but likely do not offer the multi-media and version control features of a wiki.  Procedures and the Quality Manual itself are best provided by way of a wiki although many companies continue to use word processors or dedicated document management systems.

For the wiki functionality, FOSWIKI ( https://foswiki.org/ and https://foswiki.org/About/WebHome ) is a comprehensive, open-source wiki to serve as a guide to feature.  A bare bones feature list would be security / access per ERPNext existing functionality + revision control for each wiki page + ability to attach / display files (PDF, images, etc.).

A dynamic wiki that can be updated with ERPNext data could be a real game changer and this funcatioality would likely dovetail well with the ERPNext website module.  In fact, the wiki module and website module could potentially be combined or share significant portions of code.

See https://wiki.python.org/moin/PythonWikiEngines for a list of Python-powered wiki engines that might be of use in this feature.

C.  Adding wiki + routings allow ERPNext to be used as a tool to document open source hardware ("Github for Open Hardware" (reference: http://www.wired.com/2012/05/we-need-version-control-for-real-stuff/ and https://www.wevolver.com/ and http://www.makeystreet.com/ ).  Solutions for documenting open source hardware do exist but they are not fully-featured and end up duplicating a lot of information found in ERP systems.

D.  I can potentially pay for this feature.

E.  Please make any sponsoring by me anonymous.

**Comment by addymuliady** [comment]
Just to add @user002 if you don't mind. Yours is a very great idea to improve the manufacturing module. Probably a deal breaker for some. The current one is excellent for a simple manufacturing scenario.

The feedback generally is for Raw Materials to separate from Operations and Workstations as there is a chance for Operations and Workstations from other production orders to work simultaneously.

To go deeper in manufacturing, allows a planner to schedule Workstations based on operating hours and number of availability. This will help getting the flexibility to either make a production all under one roof or in another warehouse.

Landed Cost Voucher or any Purchase Invoices should be able to be applied to Production Orders too and affect the valuation rate of manufactured goods.

**Comment by m-delvalle** [comment]
This is probably a major milestone (although I am not a developer, so I cannot know for sure) as regards workman hours needed. ISO 9001 certified (or wannabe) companies would find this _really_ useful.

Being able to consolidate all QA registers in the same environment where the rest of the company's "papership" happens would be very nice. And even further: interleave QA registers with the very manufacturing workflow would be super useful.

Not so much as a "deal-breaker" if it's not there, but perhaps more of a "deal-maker" for certified/certifying companies :wink:

**Comment by kennethsequeira** [comment]
Can be handled with the following:

1. Quality module: https://docs.erpnext.com/docs/v13/user/manual/en/quality-management/
2. Routing in mfg: https://docs.erpnext.com/docs/v13/user/manual/en/manufacturing/routing
3. Wiki app: https://github.com/frappe/wiki
