### ISSUE TITLE
[V7] Unable to select Bank account in Bank Reconciliation Statement

### ISSUE THREAD

**Issue by PrakashH** [frappe/erpnext#5318]
Steps:

1. Accounts > Bank Reconciliation Statement
1. Tried selecting Bank Account, but no select.
1. Once Bank Account was shown in the auto-suggest, but on refresh, field got reset.

![screen shot 2016-05-06 at 3 09 37 pm](https://cloud.githubusercontent.com/assets/4570016/15069860/2255bc64-139e-11e6-86b3-57bbdc294549.png)

**Comment by rmehta** [comment]
Cannot replicate
