### ISSUE TITLE
Custom Field Order changed after Update

### ISSUE THREAD

**Issue by David-at-GitHub** [frappe/erpnext#5322]
Dear all, 

after updating ERPNext from 5 to 6.2 Version, the field order in various Forms changed. This is an example for the Item Master Form, the 2 red marked fields went below my custom fields (which are the SAP fields) after the Upgrade. I can go now to customize the form and correct again the order, but I was wondering if there would be any fix for the next upgrade: 

![image](https://cloud.githubusercontent.com/assets/15001320/15086668/3157e900-1397-11e6-9991-8aced54996d0.png)

Thanks, David

**Comment by anandpdoshi** [comment]
@David-at-GitHub this is strange indeed. But we have stopped customization of position of Standard fields by users. So this problem should be reduced in future.
