### ISSUE TITLE
Links view not showing workflow state

### ISSUE THREAD

**Issue by cgpurbaugh** [frappe/erpnext#5326]
Viewing linked documents does not show the workflow state for an item, instead it shows the default status.

![workflow1](https://cloud.githubusercontent.com/assets/13136405/15113526/d3c05a2e-15c2-11e6-9fe3-1aecaa208c3d.png)
![workflow2](https://cloud.githubusercontent.com/assets/13136405/15113527/d3c6be5a-15c2-11e6-95a8-da31fb52ee10.png)

**Comment by rmehta** [comment]
@cgpurbaugh  are you on latest? I think the rendering function is same as the list.

**Comment by cgpurbaugh** [comment]
@rmehta I'm now on V7 develop, current as of this morning, still showing default status instead of workflow state.

**Comment by cgpurbaugh** [comment]
This is happening with stock workflow too, if you view links on beta.erpnext.com it shows wrong workflow state sometimes.

**Comment by pratu16x7** [comment]
`Linked With` has been recently refactored, resolving most of its issues, including this one. Closing.
![screen shot 2017-05-15 at 11 00 58 pm](https://cloud.githubusercontent.com/assets/5196925/26070510/94cf23ca-39c2-11e7-99d9-49dfcef2a847.png)
![screen shot 2017-05-15 at 11 01 32 pm](https://cloud.githubusercontent.com/assets/5196925/26070514/95f7cb3a-39c2-11e7-85c4-f6b59bdaaa94.png)
