### ISSUE TITLE
Suggestion for future - external ecommerce hook

### ISSUE THREAD

**Issue by giorgiotomasi** [frappe/erpnext#5333]
I know all businesses have a website and ecommerce, and many have more than one. It would be great and I am sure this would absolutely blow odoo out of the water, have a link programm - or shops. The link programm or shops can then be linked to the existing ecommerce platform. Import and export data.
Shop A - product, price, stock, client, date of order, no.pcs orderd, stock move etc.
Every shop would be a seperate ecommerce website - easy hook to Amazon, Ebay, personal ecommerce, Magento,Joomla, you name it. All a programmer needs to do is hook the incomming data to the specific point, and do the same on outgoing data..
Within ERPNEXT - a person would see a number of shops that push in orders, and process them all in the same place.

**Comment by rmehta** [comment]
Each of these is a separate project.

Do a web search and you might find connectors to different platforms.
