### ISSUE TITLE
Purchase Receipt for Subcontract and Rejected Qty

### ISSUE THREAD

**Issue by zachlankton** [frappe/erpnext#5336]
The Purchase Receipt Rejected Qty does not pull value or stock qty from the raw material warehouse (in this case supplier warehouse) per the BOM when submitted.  It creates scrap qty of the subcontracted item in the rejected warehouse without pulling the raw material from the supplier stock inventory (or value).

Steps to Recreate:

1. Create two items, one to be used as a raw material for the other, and set the other up to be a subcontracted item.
2. Create BOM for the subcontracted item using the other item as a raw material.
3. Create Purchase Order for the subcontracted item.
4. Receive Items in accepted qty and rejected qty
5. Check Stock Ledger for the purchase receipt and note the discrepancy between the BOM Supplier Warehouse (negative entry) and the scrap and accepted warehouse (positive entries).  These should balance and they do not.
6. Also Check the Accounting Ledger and note that the value pulled from the supplier warehouse account is only the value of the "Accepted" Parts.  The Value of the rejected parts remains in the supplier warehouse account.

**Comment by zachlankton** [comment]
Forgot a couple steps... sorry trying to recreate from memory...

Step
2.5: Stock Entry to Receive a Qty of the Raw Material
3.5: Transfer Raw Material to Supplier

**Comment by rmehta** [comment]
Unable to replicate. Can you share screenshots?
