### ISSUE TITLE
Quotation probability and expected close date?

### ISSUE THREAD

**Issue by ttiurani** [frappe/erpnext#5344]
I'm currently evaluating using ERPNext and it looks like the best fit for my needs.
 
The only crucial problem I have, is that need to be able to set a probability to a submitted quotation, a value from 0% to 100%, and also an expected close date for the quotation. I'd like to use these two values to calculate an estimate monthly "pipeline" value. The pipeline would optimally be a report, if possible. "Probability" and "estimated close date" are used in CapsuleCRM from where I would like to migrate my B2B sales data to ERPNext.

Have you considered adding those fields to a quotation?

I'd be happy to make a pull request myself to at least be able to input those values to into the quotation, if that's something you'd be interested in. (I could probably hack my way into a report using Metabase on top of MariaDB, so the report part isn't something I have a personal investment in.)

**Comment by cgpurbaugh** [comment]
You could just add 2 custom fields to the Quotation document, if you only need fields.

**Comment by ttiurani** [comment]
Well don't I feel silly: two custom fields work perfectly for my needs, thanks!

Although this might be a nice full feature for ERPNext (i.e. sorting quotations by these values, implementing the pipeline report), I'm closing this issue.
