### ISSUE TITLE
Ability to setup tax rules based upon both county & city. 

### ISSUE THREAD

**Issue by jasonbrowne** [frappe/erpnext#5348]
We recently finished our taxes and all of our taxes had to be organised by county.
Currently ErpNext only allows for creation of tax rules by city.

Feature request:
Ability to setup tax rules based upon both county & city.

**Comment by jasonbrowne** [comment]
As all of our taxes had to be done by county I am sure there are several other US based companies that would benefit from, and need this feature as well.

**Comment by rmehta** [comment]
@jasonbrowne are you a developer? We can help you build this.

**Comment by rmehta** [comment]
Fixed
