### ISSUE TITLE
Adding field to doc-type Account

### ISSUE THREAD

**Issue by rwmd** [frappe/erpnext#5351]
In an older installation I added a custom field "TaxCode" to Account since we in Austria need Tax Reports based on tax-codes that group certain accounts.

In the new version the doc-type Account is not changeable - is there a workaroud?

Note:
I understand your reasons that no user should be able to mess up central documents, but in almost every ERP-system users are not allowed to change the delivered fields but allowed to add own fields.

**Comment by rmehta** [comment]
Custom Fields are editable

https://frappe.github.io/erpnext/user/manual/en/customize-erpnext/customize-form.html
