### ISSUE TITLE
Setup error «root type is mandatory».

### ISSUE THREAD

**Issue by Mycelin** [frappe/erpnext#5356]
Setup wizard throws «root type is mandatory» error on any data.
It also shows service manager user error and 3rd error: «Setting this Address Template as default as there is no other default».

Steps to Recreate:
1. Install and run erpnext.
2. Login and fill all the data, click «complete».

Additional steps:
3. Reinstall bench, repeat steps 1—2.
4. Update bench, repeat steps 1—2.
The same.

**Comment by samjaninf** [comment]
I'm coming across the exact same issue:
![erp_errors](https://cloud.githubusercontent.com/assets/6589200/15305118/35ea7244-1b8f-11e6-9302-78b172510e0d.png)

I cannot seem to find any errors in relation to this.
