### ISSUE TITLE
`bench  install-app erpnext` error 'ImportError: No module named background_jobs'

### ISSUE THREAD

**Issue by Arnoldnuo** [frappe/erpnext#5357]
when I run `bench install-app erpnext`, I get error `ImportError: No module named background_jobs`

full message:

> Traceback (most recent call last):
>   File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
>     "__main__", fname, loader, pkg_name)
>   File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
>     exec code in run_globals
>   File "/home/erp/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 79, in <module>
>     main()
>   File "/home/erp/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 16, in main
>     click.Group(commands=commands)(prog_name='bench')
>   File "/home/erp/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/erp/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 696, in main
>     rv = self.invoke(ctx)
>   File "/home/erp/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/home/erp/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/home/erp/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/erp/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
>     return callback(*args, **kwargs)
>   File "/home/erp/frappe-bench/env/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
>     return f(get_current_context(), *args, **kwargs)
>   File "/home/erp/frappe-bench/apps/frappe/frappe/commands.py", line 29, in _func
>     ret = f(frappe._dict(ctx.obj), *args, **kwargs)
>   File "/home/erp/frappe-bench/apps/frappe/frappe/commands.py", line 176, in install_app
>     _install_app(app, verbose=context.verbose)
>   File "/home/erp/frappe-bench/apps/frappe/frappe/installer.py", line 125, in install_app
>     sync_for(name, force=True, sync_everything=True, verbose=verbose)
>   File "/home/erp/frappe-bench/apps/frappe/frappe/model/sync.py", line 43, in sync_for
>     import_file_by_path(doc_path, force=force)
>   File "/home/erp/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 54, in import_file_by_path
>     import_doc(doc, force=force, data_import=data_import, pre_process=pre_process)
>   File "/home/erp/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 122, in import_doc
>     doc.insert()
>   File "/home/erp/frappe-bench/apps/frappe/frappe/model/document.py", line 213, in insert
>     self.run_post_save_methods()
>   File "/home/erp/frappe-bench/apps/frappe/frappe/model/document.py", line 645, in run_post_save_methods
>     self.run_method("on_update")
>   File "/home/erp/frappe-bench/apps/frappe/frappe/model/document.py", line 588, in run_method
>     return Document.hook(fn)(self, *args, **kwargs)
>   File "/home/erp/frappe-bench/apps/frappe/frappe/model/document.py", line 750, in composer
>     return composed(self, method, *args, **kwargs)
>   File "/home/erp/frappe-bench/apps/frappe/frappe/model/document.py", line 733, in runner
>     add_to_return_value(self, fn(self, *args, **kwargs))
>   File "/home/erp/frappe-bench/apps/frappe/frappe/model/document.py", line 582, in <lambda>
>     fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
>   File "/home/erp/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 135, in on_update
>     self.run_module_method("on_doctype_update")
>   File "/home/erp/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 144, in run_module_method
>     module = load_doctype_module(self.name, self.module)
>   File "/home/erp/frappe-bench/apps/frappe/frappe/modules/__init__.py", line 64, in load_doctype_module
>     doctype_python_modules[key] = frappe.get_module(get_module_name(doctype, module, prefix))
>   File "/home/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 598, in get_module
>     return importlib.import_module(modulename)
>   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
>     __import__(name)
>   File "/home/erp/frappe-bench/apps/erpnext/erpnext/crm/doctype/newsletter/newsletter.py", line 12, in <module>
>     from frappe.utils.background_jobs import enqueue
> ImportError: No module named background_jobs

**Comment by samjaninf** [comment]
Have you tried bench update as your frappe user?

**Comment by rmehta** [comment]
Cannot replicate
