### ISSUE TITLE
Move enable/disable scheduler from System Settings to site_config.json

### ISSUE THREAD

**Issue by anandpdoshi** [frappe/erpnext#5369]
- [ ] https://github.com/frappe/frappe/blob/develop/frappe/core/doctype/system_settings/system_settings.json#L250
- [ ] https://github.com/frappe/frappe/blob/develop/frappe/utils/scheduler.py#L175
- [ ] Commands
- [ ] Patch: Set `"disable_scheduler": 1` if enable_scheduler is unchecked in System Settings
- [ ] On installing erpnext/schools, disable scheduler and enable it on completing setup wizard

**Comment by rmehta** [comment]
Why?

**Comment by anandpdoshi** [comment]
Isn't required anymore
