### ISSUE TITLE
Naming Series - "User must always select" option does not unset

### ISSUE THREAD

**Issue by TomFreudenberg** [frappe/erpnext#5370]
Hi,

when using naming series and activate "User must always select" option on e.g. "Sales invoice", the option is not unmarked when changing the "Transaction". So it seems that ALL Transactions needs that.

This is not true, functionality is fine as expected. ONLY "Sales Invoice" requires selecting a series.

You need to "uncheck" the option, when new selection was done.

![bildschirmfoto 2016-05-18 um 16 35 40](https://cloud.githubusercontent.com/assets/410087/15363126/f397a5d0-1d17-11e6-8e74-b221daa4d39e.png)

**Comment by Tropicalrambler** [comment]
+1

**Comment by nabinhait** [comment]
Fixed via https://github.com/frappe/erpnext/commit/dc16b7e34a60ca64884efc635bf2bc83d902a8eb

**Comment by TomFreudenberg** [comment]
Great, thanks for support!
Tom
