### ISSUE TITLE
[6.27.19] Error on creating warehouse object

### ISSUE THREAD

**Issue by gadiel** [frappe/erpnext#5382]
Currently have ERPNext 6.27.19 on my server.

I have two companies configured, when creating new warehouse I get the following console error:

<img width="635" alt="console_error" src="https://cloud.githubusercontent.com/assets/1625685/15437503/b138b80a-1e84-11e6-9dea-4fed89e07441.png">

the stack goes like this:

<img width="525" alt="frappe_erp_error" src="https://cloud.githubusercontent.com/assets/1625685/15437526/c759e96a-1e84-11e6-978c-c49eb2fc6936.png">

**Comment by rmehta** [comment]
This was fixed. Have you updated your instance?

**Comment by gadiel** [comment]
It was indeed fixed!, I just had to flush my browser cache.

Thanks for the great work!
