### ISSUE TITLE
[Paid Development] Drawn signature HTML Field

### ISSUE THREAD

**Issue by betabank** [frappe/erpnext#5383]
The functionality is explained in this post from the discuss:
https://discuss.erpnext.com/t/drawn-signature-html-field/6824

Basically, we want the possibility of adding a custom HTML field to get a drawn signature in any DocType (probably most used in delivery notes, purchase order, sales order...)

As other fields, once the document is submitted, the field should not be editable anymore.

Thank you.

**Comment by mhbu50** [comment]
+1

**Comment by mhbu50** [comment]
I think this is done.
you have to close it
