### ISSUE TITLE
Cannot create "System User" in V7

### ISSUE THREAD

**Issue by fderyckel** [frappe/erpnext#5385]
Hi, 
I have tried to create several new users in the development branch V7.  
I am adding a role (let's say: sale user" ) then I click save.  It does save without error (going from orange dot to green dot) but in reality nothing has been saved.  If I reopen the "role" section, nothing has been selected, it is still all unselected.  I have tried it several time on different browser and I always get the same results.  not managing to get a system user ... all the user I create are "website user".

I hope I made sense.

**Comment by fderyckel** [comment]
Also I am not managing to set new icons on the desktop for system user.  I click on the new icon list, I click update.  Message on the screen come with update, but nothing is actually updated and I refresh the page, none of the icons I have selected come as ticked again.

Thanks

**Comment by rmehta** [comment]
Should be fixed now.
