### ISSUE TITLE
Viewing records

### ISSUE THREAD

**Issue by acumensec** [frappe/erpnext#5388]
Currently the default view of records to view in one page is limited to a low number (less than 50 it seems). Would it be possible to keep this configurable such that 100 (or even 500) records can be viewed?

**Comment by rmehta** [comment]
@acumensec you can view more records when you switch to reports

<img width="1008" alt="screen shot 2016-05-24 at 12 07 37 pm" src="https://cloud.githubusercontent.com/assets/140076/15494405/d89eae4c-21a7-11e6-841a-d12d5f6c8a7f.png">

**Comment by acumensec** [comment]
Yes that is possible However my normal view is the list that shows up (lets say when I click on Project List). It would be nice to be able to configure how many records show up (perhaps a global configure for all lists). That way if I have more than 70-80-100 records, I do not have to click to expand everytime.

**Comment by rmehta** [comment]
Done :)

**Comment by acumensec** [comment]
Awesome, thank you! How do I configure the list view?:-)

**Comment by rmehta** [comment]
It will remember your last selection (coming in v7)

**Comment by acumensec** [comment]
Very cool!

Ashit Vora
Co-Founder and Laboratory Director
Cell: +1 (213) 268-2593
Web: www.acumensecurity.net <http://www.acumensecurity.net>

From:  Rushabh Mehta <notifications@github.com>
Reply-To:  frappe/erpnext
<reply+006edef421d25616709a2db1cdfb5369025f3c7b385aa7b692cf0000000113674e2c9
2a169ce094ee8d4@reply.github.com>
Date:  Wednesday, June 1, 2016 at 9:30 PM
To:  frappe/erpnext <erpnext@noreply.github.com>
Cc:  acumensec <info@acumensecurity.net>, Mention
<mention@noreply.github.com>
Subject:  Re: [frappe/erpnext] Viewing records (#5388)


It will remember your last selection (coming in v7)


You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/frappe/erpnext/issues/5388#issuecomment-223172520> , or
mute the thread 
<https://github.com/notifications/unsubscribe/AG7e9KUMSfBoypvScHzZWw6_wEfJHS
44ks5qHjIsgaJpZM4IkDD7> .
