### ISSUE TITLE
Templates in Product Bundles.... lead to a dead end

### ISSUE THREAD

**Issue by nununo** [frappe/erpnext#5389]
Hello,

I just tried to add a template to a product bundle. It worked. 
And then I tried to create a SO with that product bundle and it also worked.
And then I created the Delivery. But when I tried to submit it it says:

"Stock cannot exist for Item ZZZ since has variants"

If I am allowed to templates to product bundles, I was hoping that, at some point I'd have to choose a variant for each of those templates. But no. I got stuck here.

So what's the point of let me add template items to product bundles?
This sounds like a bug. Or am I missing something?

Thanks in advance,
Nuno

**Comment by rmehta** [comment]
You should not be allowed to add variants after you have made a Sales Order.

You can either cancel the Sales Order or make a new item. Nothing wrong with Product Bundles

**Comment by nununo** [comment]
But... why can I add template products to a sales order, then? 
Can you give me an example of a situation in which that will make sense?

**Comment by rmehta** [comment]
it should not allow templates in sales order, unless you made it a template after you made the sales order.

**Comment by nununo** [comment]
Hum... I could swear that I managed to do this but I am no longer able to reproduce it... so either it was corrected or it was all in my imagination. Thanks anyway!

**Comment by rmehta** [comment]
I have fixed this. You converted it to a numeric format (which was not validated)
