### ISSUE TITLE
[V7] When add new User, User Type is auto-set as Website User

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#5392]
Stes:

1. Users > new User
2. Added email id and user's name.
3. Saved User.

On save, User Type was set as "Website User". Since this is a read only field, I cannot set this user as a System User.

![screen shot 2016-05-23 at 3 10 53 pm](https://cloud.githubusercontent.com/assets/910238/15469140/e7f2a0b2-2105-11e6-8264-dd0106719d34.png)

**Comment by rmehta** [comment]
it is set based on roles.
