### ISSUE TITLE
ERPNext for Service Providers

### ISSUE THREAD

**Issue by MaxMorais** [frappe/erpnext#5397]
Hey Guys, currently I'm doing a customization of ERPNext for my uncles company, they are loving ERPNext!

They are in the Service's market segment, the company started on the bankruption of Group Realize, my first work with ERPNext!

I'm currently working with they on weekends, to implement his requirements, that are small, but I'm feel that have some things that I can patch in ERPNext, to improve it to Service Providers

The patches that I'm able to do, in this journey are:

## Sales Order

- [ ] Deprecate `Maintenance` in favor of `Service` in `Sales Type` field
- [ ] Deprecate `Sales Team` in favor of `Comissioned Team`

## `Sales Person` deprecation in favor or `Team Person`

Due `Team` is a generic term, it can cover better the possible scenarios

- Team Types
 - [ ] Internal
 - [ ] External

- [ ] Internal Teams can have:
  - [ ] Members that can be related with a `Employee` or a `User`
 - [ ] Managers that can be a `Employee` or a `User`
 - [ ] Calendar

- [ ] External Teams can have:
  - [ ] Members that are related with a `Contact` from `Customer` or `Supplier`
- [ ] Managers, where at least one should be a `Internal Manager`
- [ ] Calendar accessible via Portal

- Can have targets
 - A target can:
  - [ ] Count the number of records in a `DocType`, with a rule or not
  - [ ] Or can sum a number field or sub-field in a `DocType`, with a rule or not
  - [ ] A target can have a time window, eg: in last 90 days, in last 3 months, in next 5 weeks
  - [ ] A target should have a start trigger

## Rename `Maintenance Schedule` in favor of `Service Schedule`
The term `Maintenance` don't cover all the options of the `Service Market Segment`

**Comment by rmehta** [comment]
:+1:

Pick your priority though!

**Comment by rmehta** [comment]
Open each separately?
