### ISSUE TITLE
BUG - Supplier Quotation Report Currency

### ISSUE THREAD

**Issue by ai-erp** [frappe/erpnext#5401]
We have encountered a BUG in the system when viewing reports on supplier quotations.
We have suppliers wherein we made quotation in system with different currencies (let us say USD and AED, etc)
As we go through the report and look for 1 item quoted by different suppliers, it is showing in the report that all supplier's quotations were in AED(company currency) which is misleading because not all quotations were made in AED currency. Some of that was quoted in USD and etc...
I have already checked that the rate showing as we pick the column was "Rate (Supplier Quotation Item)" and not based on company currency. Below is the screenshot of the said issue:

![untitled](https://cloud.githubusercontent.com/assets/16744099/15575148/789333bc-2362-11e6-9e06-85c8077d5987.jpg)

Below is the screenshot of SQTN-00534 which amount in quotation is in $ but showing in report as AED

![untitled-sqtn-00534](https://cloud.githubusercontent.com/assets/16744099/15575162/86ee7610-2362-11e6-80e4-87164a3db1ac.jpg)

Same is showing as we check on the erpnext demo as below:

![untitled-demo](https://cloud.githubusercontent.com/assets/16744099/15575173/9151dfca-2362-11e6-8035-ebaa155c073d.jpg)

**Comment by nabinhait** [comment]
Please select Currency column in the report, then it will show proper currency.
