### ISSUE TITLE
Account not found

### ISSUE THREAD

**Issue by jmatsushita** [frappe/erpnext#5402]
Hi,

When using the skr04 german chart of accounts (both on master and develop) I get messages about a particular account being not found when creating a new company.

with `master` the error is
```
Account Wertberichtigungen zu Forderungen mit einer Restlaufzeit von mehr als 1 Jahr gegen Unternhemen- mit denen ein Beteiligungsverhaltnis besteht - test not found
```
with `develop`
```
Account Abschreibungen a. Vermögensgeg. d. Umlaufvermögens- soweit diese die in der Kapitalgesellschaft üblichen Abschreibungen überschreiten - test not found
```

We're happy to at least remove these errors before tagging the accounts appropriately, but I don't understand what is causing them in the first place. Missing is_group properties? Problem with the character encoding?

Thanks for your support,

Jun

**Comment by nabinhait** [comment]
@jmatsushita Can you please try to build and contribute SKR04 using charts.erpnext.com?
