### ISSUE TITLE
Shopify Connector: Add support for multiple warehouses

### ISSUE THREAD

**Issue by raveslave** [frappe/erpnext#5409]
To enable support for multiple pick&pack warehouses, we'd love to see support for this. 

From an e-comm perspective, this is usually done by having different markets and/or products pointing to different warehouse & stock locations.

reference: https://discuss.erpnext.com/t/shopify-connector/8416/5

**Comment by rmehta** [comment]
Move to https://github.com/frappe/erpnext_shopify/issues
