### ISSUE TITLE
Shopify Connector: Add support for serialized stock

### ISSUE THREAD

**Issue by raveslave** [frappe/erpnext#5410]
Products managed by serialized stock entries should be supported and synced back to erpnext.

So when an order is expedited in shopify, each item and it's corresponding serial numbers is saved with the order. To allow validation (in the pick&pack view), this would require realtime sync and allocation of that serial in erpnext.

**Comment by rmehta** [comment]
Please open the issue at https://github.com/frappe/erpnext_shopify/issues
