### ISSUE TITLE
Error - General Ledger

### ISSUE THREAD

**Issue by fderyckel** [frappe/erpnext#5411]
I got this error while refreshing the general ledger page.

> Traceback (most recent call last):
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
>     response = frappe.handler.handle()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
>     execute_cmd(cmd)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 36, in execute_cmd
>     ret = frappe.call(method, **frappe.form_dict)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 854, in call
>     return fn(*args, **newargs)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/query_report.py", line 88, in run
>     res = frappe.get_attr(method_name)(frappe._dict(filters))
>   File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/report/general_ledger/general_ledger.py", line 23, in execute
>     res = get_result(filters, account_details)
>   File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/report/general_ledger/general_ledger.py", line 97, in get_result
>     gl_entries = get_gl_entries(filters)
>   File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/report/general_ledger/general_ledger.py", line 124, in get_gl_entries
>     group_by_condition=group_by_condition), filters, as_dict=1)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 136, in sql
>     self._cursor.execute(query, values)
>   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 185, in execute
>     for key, item in args.iteritems())
> KeyError: 'company'

**Comment by nabinhait** [comment]
Pushed a potential fix, can you please update and check?
