### ISSUE TITLE
Error - Stock Balance

### ISSUE THREAD

**Issue by fderyckel** [frappe/erpnext#5412]
I tried to open the Stock balance report.  

> Traceback (most recent call last):
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
>     response = frappe.handler.handle()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
>     execute_cmd(cmd)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 36, in execute_cmd
>     ret = frappe.call(method, **frappe.form_dict)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 854, in call
>     return fn(*args, **newargs)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/query_report.py", line 88, in run
>     res = frappe.get_attr(method_name)(frappe._dict(filters))
>   File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/report/stock_balance/stock_balance.py", line 16, in execute
>     iwb_map = get_item_warehouse_map(filters)
>   File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/report/stock_balance/stock_balance.py", line 88, in get_item_warehouse_map
>     from_date = getdate(filters["from_date"])
> KeyError: u'from_date'

**Comment by nabinhait** [comment]
Pushed a potential fix, can you please update and check?
