### ISSUE TITLE
Stock Ledger shows quantity for a particular serial # but that item does not show up for material issue

### ISSUE THREAD

**Issue by mehtapawan007** [frappe/erpnext#5421]
[Bug#1-Created a material in with serial no 29052016 and it shows up in the stock ledger.docx](https://github.com/frappe/erpnext/files/290225/Bug.1-Created.a.material.in.with.serial.no.29052016.and.it.shows.up.in.the.stock.ledger.docx)

**Comment by rmehta** [comment]
Check the date of the stock entry, it has to be after the date you make a DN

Also please paste images directly and not in a docx!

**Comment by mehtapawan007** [comment]
As discussed, it was due to incorrect bar code entered on the stock entry,the stock ledger shows correct details now but I did not see the accounting entry,maybe the item master needs to be checked for this
