### ISSUE TITLE
Time Log > Time Log Batch creates blank line 1

### ISSUE THREAD

**Issue by superlack** [frappe/erpnext#5422]
In recent updates, creating a Time Log Batch form selected Time Logs will transfer them to the appropriate screen, but when saving, it asks for the Time Log on Line 1.  The child table shows a blank line.

-- Another odd part is that when deleting the empty line, the data moved up from line 2 is present, but only the billable amount shows.

**Comment by rmehta** [comment]
Thanks for reporting. Fixed
