### ISSUE TITLE
Error after last update 6.27.21

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#5425]
I get the following error when I try to access any doctype:

> Traceback (most recent call last):
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
>     response = frappe.handler.handle()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
>     execute_cmd(cmd)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 36, in execute_cmd
>     ret = frappe.call(method, **frappe.form_dict)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 854, in call
>     return fn(*args, **newargs)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 71, in getdoctype
>     frappe.response['list_settings'] = get_list_settings(parent_dt or doctype)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/utils/list_settings.py", line 13, in get_list_settings
>     update_list_settings(doctype, list_settings)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/utils/list_settings.py", line 20, in update_list_settings
>     current.update(list_settings)
> ValueError: dictionary update sequence element #0 has length 1; 2 is required

**Comment by bcornwellmott** [comment]
I get the same issue. Running the develop branch.

**Comment by rmehta** [comment]
sorry, fixed now.
