### ISSUE TITLE
Error after last Bench update

### ISSUE THREAD

**Issue by navdeepghai** [frappe/erpnext#5426]
Unable to install jasper_erpnext_report , because of frappe.logger.
There are multiple lines in  jasper_erpnext_reoport under  *.py files that are using frappe.logger and whenever i try to install jasper_erpnext_report it throw an error where ever  installation find frappe.logger.

I've also tried after commenting those frappe.logger lines , but there are many files that are containing frappe.logger line.

Result i m unable to install jasper_erpnext_report after updation. 
Its only happened in new frappe system.
Its working fine in all  system , before updation.

Thanks
Navdeep

**Comment by vjFaLk** [comment]
Hi, I'm assuming you're on the develop branch of frappe? We actually changed our logger system, that's why the report isn't working. The developer of the project will have to make it compatible with our new logger.

You should be using the master branch of frappe that is meant for production systems, whereas develop branch is for development purposes.

**Comment by navdeepghai** [comment]
Yes ! We are  already using master branch of frappe rather than develop branch,  what we doing , We are simply trying to install jasper_erpnext_report after new installation of system but its creating error due to system logger changes that you'r team have made in last update of frappe system . Please Can you provide me link of frappe older update or  any other link available for fresh installation for old version frappe system. so that we can install older frappe system and try to install jasper_report as time being .
Please response as soon as possible. Because we are  using jasper_erpnext_report in our production system.
Thanks
Navdeep

**Comment by vjFaLk** [comment]
The master branch of Frappe does not have the new logger. You shouldn't be facing problems. Make sure you're installing the right branch of jasper_erpnext_report

**Comment by navdeepghai** [comment]
I have cloned this app using 
frappe-bench/ bench get-app  bench get-app jasper_erpnext_report https://github.com/saguas/jasper_erpnext_report.git
as i have already set a branch as master branch.
 And installed this app using : bench install-app jasper_erpnext_report.

Same process i've done for installation of frappe system.

What i'm missing now , Please guide me to right track .

**Comment by vjFaLk** [comment]
Those are the correct steps. You'll need to get in touch with the developer of the app.

**Comment by navdeepghai** [comment]
Hi frappe Team !
 
Actually i m getting anything related to this error . JasperErpnextReport developer's are saying , you will  need to talk to Frappe Team and Frappe Team is Saying You need to talk with jasper Erpnext Report Developer.

Please sir guide me correct direction, what a need to do , to sort out this error.
Please ....

Regards
Navdeep

**Comment by yashodhank** [comment]
Take help from community @navdeepghai , or be ready to spend some money to get it fixed from someone!
