### ISSUE TITLE
Cash Flow Statement

### ISSUE THREAD

**Issue by santhosh1967** [frappe/erpnext#5431]
I have gone through the cash flow available in ERP Next. 
However it is not the report I was looking for.

I would need a cash flow report as below:-

For a selected date range – from--- to---

Cash Inflows(Source of Cash)
Here one by one the receipts into bank showing from where or from whom the money came is to be listed.
Basically it is a listing of all debits into the Bank.
But the difficulty is in the case of compound entries that, eg., For a sales, party is debited and sales is credited. Later when payment is received from customer, bank is debited and party is credited. Hence, if we go by the debits into the bank alone we will not know that the source of funds is sales.

But in the case of simple entries like owner giving money to the company, the bank is debited and owner is credited, it can straight away list the account name of the owner as the source of cash.

Cash out flows (application of cash)
(here one by one the expenses for which the cash was utilized, withdrawal by owner etc., is to be listed)
Here too if the entry is a compound entry (the party to which the payment is made, has a linked purchase invoice, the account name(s) listed in the purchase invoice should be listed instead of the party name alone.

The above report straight away will help the management in understanding from which sources the cash came into the company and for what the cash was utilized over a period of time.

One more problem I came across is that in the current cash flow in the system, even opening entries are shown. If I want to know the cash flows for this year, and if all the opening entries are figuring in the month of Jan, then it doesn’t make sense to me as I am interested in knowing from the opening balance in bank what happened. Hence there must be a way of filtering out opening entries.

Please advice how to resolve.

Thanks
Santhosh

**Comment by yashodhank** [comment]
Open topic at https://discuss.erpnext.com for more discussion and feedback.
