### ISSUE TITLE
Fixed Asset depreciation missing/inputs for future release

### ISSUE THREAD

**Issue by mehtapawan007** [frappe/erpnext#5434]
Some inputs for depreciation feature 

Some nice to have features related to FA depreciation that can be considered for future releases or whenever depreciation feature is released:

1) Asset creation options should be given to users i.e. auto asset creation can happen at time of purchase receipt or at time of payment for asset and depreciation should start once the asset is put into service(based on in service date)
2) Accounting scenarios to be considered would be asset addition,adjustment,asset transfer, retirement, sale of asset
3) It would be nice to have Sale of asset linked to Billing 
4) Item master should be linked to asset profile
5)Asset profile( will contain information like depreciation convention(straight line, reducing balance etc), Asset Category/class(like Machiery, F&F etc) to control depreciation % as per regulations ,life in months 
6) Net book value of asset (cost-accumulated depreciation till date) should be visible on the asset page at all times.
7)Reports: Fixed asset register

Thanks

**Comment by nabinhait** [comment]
The feature has already been developed in develop branch (version 7). And all the inputs mostly taken care off. You can test the feature by setting up the environment with develop branch.

**Comment by mehtapawan007** [comment]
Below are inputs for tax addition to asset cost:

1) If tax is recoverable it should not be added to asset cost. For example , service tax credit , or recoverable VAT etc. In general, non-recoverable taxes + transportation cost + installation charges can me added to asset cost while asset is created from a purchase receipt.

**Comment by nabinhait** [comment]
Thanks for the inputs :)
