### ISSUE TITLE
Updated Item price in quotation shows in print preview but goes back to price list price in PDF

### ISSUE THREAD

**Issue by mineolatx** [frappe/erpnext#5435]
Updated Item price in quotation shows in print preview but goes back to price list price in PDF.

Changed price of item in quotation and it shows correctly including updated totals in the quote and print preview. When I go to PDF output the price has changed back along with the totals. 
Why would the PDF show different information from the quote page and the print preview?

**Comment by PawanMeh** [comment]
Unable to replicate this issue, try to save the document before you look for the PDF view
