### ISSUE TITLE
Discount percentage in Pricing policy

### ISSUE THREAD

**Issue by Nehamirpuri** [frappe/erpnext#5440]
We should have discount percentage in pricing rule can be set to the maximum discount set and any percentage below it can be offered similar to item master,whereas now only the percentage set can be offered,which causes the issue if any percentage less than that has to be offered in the same quotation

**Comment by adityaduggal** [comment]
@Nehamirpuri If I get your question correctly then you are asking for below mentioned functionality:

Suppose Customer = "Apple Computers" and the Pricing Rule is setup to give discount of 45% on all computers to the customers, then you are saying that the user should be allowed to give a discount of 40% as well but nothing above 45% correct?

If that is the case then you should use IGNORE PRICING RULE checkbox in the transactions  and change the discount. Please close the issue if this resolves your query.

**Comment by deepeshgarg007** [comment]
The pricing Rule is already complicated enough, adding more rules to it will make things more complex. Working on making the existing functionality as it is supposed to be, closing this request for now
