### ISSUE TITLE
Autocomplete in shipping address stops working

### ISSUE THREAD

**Issue by Jdash99** [frappe/erpnext#5441]
I cannot select the address in the `shipping address` field after if I try to change it. 

I tested this in a `Purchase Order` and a `Purchase Receipt`

This is what happens:

![purchase](https://cloud.githubusercontent.com/assets/1348365/15969194/8e814cc0-2ef4-11e6-951a-16a2c0851864.gif)

In this example I have two addresses to choose. The first time I have no problem to choose one, but if I made a mistake and try to change it I can't do it. The autocomplete does not show anything and I have to reload the page to select the right one.

**Installed Apps**

    ERPNext: v6.27.22
    Frappe Framework: v6.27.21
    Frappe Subscription: v0.0.1
    Mandrill Integration: v0.0.1

**Browsers tested**

    Google Chrome Versión 51.0.2704.84 m
    Firefox 47.0

**OS**

    Windows 10

**Address 1 information**
![acerias](https://cloud.githubusercontent.com/assets/1348365/15969580/4fa390ce-2ef6-11e6-9d3f-a367258fbf64.png)

**Address 2 information**
![consorcio](https://cloud.githubusercontent.com/assets/1348365/15969586/51d03064-2ef6-11e6-8767-ebf3b1a6d5e9.png)

**Shipping Address Field information**
![ship](https://cloud.githubusercontent.com/assets/1348365/15969982/0bd424c4-2ef8-11e6-90e1-2165558776e1.png)

**Comment by rohitwaghchaure** [comment]
@Jdash99 I am unable to reproduce this issue, can you please provide the version of apps and the user language detail.

**Comment by Jdash99** [comment]
**Installed Apps**

- ERPNext: v6.27.22
- Frappe Framework: v6.27.21
- Frappe Subscription: v0.0.1
- Mandrill Integration: v0.0.1

**Language**

- Spanish

**Comment by Jdash99** [comment]
Could you reproduce this issue? Or you need more information?

**Comment by rohitwaghchaure** [comment]
@Jdash99 Nope, Can you please provide more information.

**Comment by Jdash99** [comment]
I updated the issue with more information and set the language to english. If you need more specific information just tell me.

**Comment by rohitwaghchaure** [comment]
Thanks @Jdash99 ,
I am able to replicate the issue, I have fixed it and sent pull request.
One more, shipping address only shows the addresses of your company(See attachment). 
![screen shot 2016-06-11 at 12 30 13 am](https://cloud.githubusercontent.com/assets/8780500/15977306/8dfa0d92-2f75-11e6-9785-0169ae2f761f.png)
