### ISSUE TITLE
[BUG] in SMS center

### ISSUE THREAD

**Issue by me2ne** [frappe/erpnext#5444]
Hi 
There is bug in SMS Centre  of ERPNEXT . When you chose more to 200 contact to  send sms , erpnext only send sms for first 200 and don't show any thing in SMS Log about that . 
Regards

**Comment by rmehta** [comment]
There is no such restriction in ERPNext - must be a restriction with your provider

**Comment by me2ne** [comment]
if there is no problem in erpnext why don't show any thing in log about that ??? 
Don't show sms sent or not sent or only sent to 200 ??
