### ISSUE TITLE
ERPNext does not maintain audit trail in draft mode

### ISSUE THREAD

**Issue by mkumar9699** [frappe/erpnext#5448]
Dear All,

Software does not maintain audit trail in draft mode. if one user created a document and save. The audit trail says that <username> created this document but if someone modifies with wrong value it does not reflect their name. This   provision should be there in software to capture who changed this document.

Thanks
Mithilesh Kumar

**Comment by adityaduggal** [comment]
@mkumar9699 I don't think there is any audit trail in ERPNext out of the box, even submitted docs would never tell you what exactly changed and hence there is no audit trail

**Comment by sbkolate** [comment]
@mkumar9699 
Agree with you,

ERPNext stores last modified, but not complete list users who modify doc.

In Comment may be we can store modified by log, so at least we know list of people who accessed and changed doc.

**Comment by strixaluco** [comment]
Implemented via frappe/frappe/pull/2523
