### ISSUE TITLE
Screen Greys out Permanently on Certain Screens

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#5452]
We are having this issue after the last update:

The screen goes grey in almost every document, like POS, Project and every configuration.

https://discuss.erpnext.com/t/screen-greys-out-permanently-on-certain-screens/13180/1

**Comment by rmehta** [comment]
I assume this is v7/develop

**Comment by applepipe** [comment]
Yes, erpnext v6.27.22 and frappe v6.27.21

Sorry, I forgot to put the full details.

**Comment by rmehta** [comment]
Fixed.
