### ISSUE TITLE
Wrong header for Material Request

### ISSUE THREAD

**Issue by Devens** [frappe/erpnext#5454]
Please check following screen shots. MR created for Agni Enterprise Company. But, header being shown in preview is of different company. 

![untitled_clipping_060816_093153_am](https://cloud.githubusercontent.com/assets/10671911/15882391/b3e5df3e-2d5b-11e6-8641-db6ecd2218f8.jpg)

![screenshot_060816_093231_am](https://cloud.githubusercontent.com/assets/10671911/15882400/cbd0c4ec-2d5b-11e6-9c62-a41d6f7bbac4.jpg)

**Comment by rmehta** [comment]
Letter head is editable from "Print Settings"

If you set a default for company, it will automatically fetch.
