### ISSUE TITLE
[BUG] in SMS center  ( Reopen )

### ISSUE THREAD

**Issue by me2ne** [frappe/erpnext#5457]
Hi
I open issue recently here about Bug in sms centre , but ERPNEXT team just reply "There is no such restriction in ERPNext - must be a restriction with your provider " . 
*_If restriction from my provider why in SMS LOG of ERPNEXT didn't show any thing about sms sent or not or only send to 200 number .( nothing show about that sms ) *_
They like to just close issue about ERPNEXT BUG immediately . 

This is issue closed  ( #5444) . 

Hi 
There is bug in SMS Centre of ERPNEXT . When you chose more to 200 contact to send sms , erpnext only send sms for first 200 and don't show any thing in SMS Log about that . 
Regards

**Comment by tundebabzy** [comment]
Hello @me2ne have you been able to solve the issue? As said in the referenced issue, ERPNext does not put any restrictions on the number of receipients.

Please reopen if needed.
