### ISSUE TITLE
Description column disappears if no description entered for items. 

### ISSUE THREAD

**Issue by kamtex** [frappe/erpnext#5460]
Hi. I am doing quotations.
I do not enter description for my line items.
When I preview the document, the description column is missing.
When I put just any random text in any one of the line item descriptions, the whole column reappears with the item name and item code.
It should be possible to NOT enter description and yet allow Item Name and Item Code to appear. 
All fields are NOT Print Hide.

![erpnext-missing111](https://cloud.githubusercontent.com/assets/17243028/15953944/7f2020da-2f03-11e6-9e7c-2f425b9a7b52.jpg)

![erpnext-missing222](https://cloud.githubusercontent.com/assets/17243028/15953943/7f174cee-2f03-11e6-9e24-9022bf8bcc7c.jpg)

**Comment by netchampfaris** [comment]
Seems fixed.

![image](https://cloud.githubusercontent.com/assets/9355208/26055063/dbd4cdfa-398c-11e7-8152-a96f5802befa.png)
