### ISSUE TITLE
BOM does not allow Item Qty. Zero for listed items.

### ISSUE THREAD

**Issue by Snowflake6** [frappe/erpnext#5464]
When entering a BOM, items can be added to the BOM with zero quantity.  Once the BOM is built, trying to save the BOM results in a popup with "Item Quantity Required for..." and the part number/line in the BOM list.

This behaviour does not change if you toggle the "mandatory" field in the form setup (Setup -> Customize -> Customize Form -> BOM Item -> Qty field).

**Comment by PawanMeh** [comment]
This validation is enforced by code(line 223, bom.py), in case your business does not require this validation you could look to comment it out in case you are self hosting.
