### ISSUE TITLE
ERPNext setup issue

### ISSUE THREAD

**Issue by MaxMorais** [frappe/erpnext#5465]
![download 23](https://cloud.githubusercontent.com/assets/1288676/15976856/ac8f796c-2f2b-11e6-9aa6-c9a7f1fcf944.png)

Because a picture is worth more than a thousand words and a traceback too:

Has no traceback!
Has no access to the desktop!
Just this message!

**Comment by rmehta** [comment]
I have fixed this issue. Can you check?
