### ISSUE TITLE
Adding new currency - Birr - Ethiopian Birr

### ISSUE THREAD

**Issue by ajinkyagadewar** [frappe/erpnext#5467]
Would like to know the process to add the currency in the currency master and make it default for all transactions?

**Comment by yashodhank** [comment]
@ajinkyagadewar Please note this is not a support channel / help desk. Try to get help from [community](https://discuss.erpnext.com) for your issues or hire a developer/consultant.

**Comment by ajinkyagadewar** [comment]
Noted.
