### ISSUE TITLE
Stock Updates of 'Product Bundle' via Rest API

### ISSUE THREAD

**Issue by dhav-d** [frappe/erpnext#5469]
Following are the observations with the stock calculations when 'submitting' invoices directly through Rest API.

The value of particular stock item (which is set as 'product bundle' to anther item) remains 0 hence the balance qty in stock ledger remains as it is, thus misrepresenting stock balances.

It seems the 'product bundle' assigned to each item are not getting triggered when submitting an invoice directly via Rest API. 

We observed while creating draft invoices via Rest API is perfect and the stock trigger for 'product bundle' is applied perfectly when submitting that invoice from erpnext.com

Thus making the process for creating invoices via Rest API mute. Please help.

Here's the link to the discussion topic for the same
https://discuss.erpnext.com/t/inventory-balance-quantity-problem/12995/4

Thanks! :)

**Comment by nabinhait** [comment]
@dhav-d I have checked the code related to product bundle, but could not found any issue which can lead to the problem. Can you please share the input data (json) of the Sales Invoice?

**Comment by dhav-d** [comment]
Can you guide me how to do that?
I am 100% noob

**Comment by nabinhait** [comment]
You can use `print` statement in your code before pushing data using Rest API. From which application you are pushing the data to erpnext? If there is a field-to-field mapper to make the input data, you can also share that piece of code.

Also share the screenshot of the sales invoice created in erpnext, particularly details of packed item and item table.

**Comment by dhav-d** [comment]
Why closed? I was getting help from my devs to  give yiu screenshots. And I could allow you to enter our account to check items and bundled items

**Comment by rmehta** [comment]
Not an issue with ERPNext :) You can continue chatting though.
