### ISSUE TITLE
Deleton of Task from Project

### ISSUE THREAD

**Issue by amithasarath** [frappe/erpnext#5470]
All the 'Tasks' from the project / the last task can't delete permanently at a stretch from the project, though they can delete through 'Tasks' List. Tasks can be deleted one by one except the last one. If tried it again gets saved!!!

**Comment by sbkolate** [comment]
Issue is present in both v6 & v7
When we delete all task/last task then its not deleted.

Reference: https://github.com/frappe/erpnext/issues
