### ISSUE TITLE
[Feature request] Apply Pricing Rule per Warehouse

### ISSUE THREAD

**Issue by GSLabIt** [frappe/erpnext#5471]
Hi all,

is possibile to develop a feature in order to have Pricing Rule per Warehouse? and/or apply price for a selected price list (like discount percentage)?

Regards,
Giovanni

**Comment by mhbu50** [comment]
+1

**Comment by kennethsequeira** [comment]
https://docs.erpnext.com/docs/v13/user/manual/en/accounts/pricing-rule
