### ISSUE TITLE
[V7] Pricing Rule for Margin

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#5483]
Steps:

1. I created following Pricing Rule for calculating Margin and applying Discount.

![screen shot 2016-06-16 at 9 18 10 am](https://cloud.githubusercontent.com/assets/910238/16104952/6be97ada-33a3-11e6-8913-51d6924ec666.png)

1. When I created Sales Order, Pricing Rule was not applied.

1. In the Pricing Rule, I selected "Standard Buying" Price List. But it was not selectable in the Quotation.

1. Then in the Pricing Rule, I selected "Standard Selling" Price List. With this Margin was correctly applied, and discount was calculated as well.

Suggestion: If Pricing Rule has Margin defined in it, then selecting Price List should be mandatory. Also we should filter Price Lists for which is Selling. Price Lists only created for Buying should not be selectable for calculating Margin. Or we can give a help notification suggesting to also check Selling for the Price List.

**Comment by rmehta** [comment]
@umairsy this explanation is not helpful at all - (read 3 times!)
