### ISSUE TITLE
[V7] Stock Reconciliation - Difference Account Issue

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#5484]
Steps:

1. New Stock Reconciliation
1. Selected "Item", entered Qty and Valuation for it.
1. In the Difference Account, replaced Stock Adjustment (default) Account with "Temporary Opening" Account.
1. Attached is the error message received on save.

![screen shot 2016-06-16 at 9 28 29 am](https://cloud.githubusercontent.com/assets/910238/16105317/f20d5ca0-33a6-11e6-881d-e9a2999663dc.png)

**Comment by nabinhait** [comment]
could not replicate
