### ISSUE TITLE
[V7] RFQ - Fetching Supplier details

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#5485]
Steps:

1. Created Material Request from Sales Order.
1. Created Request for Quotation against Material Request.
1. In the Request for Quotation, on selection of Supplier, Contact Name and Email is not auto-fetched.

On selection of Supplier, it's primary Contact and email id should be auto-fetched.

![rfq-supplier](https://cloud.githubusercontent.com/assets/910238/16105912/080aba74-33ad-11e6-8bab-89fe314324df.gif)

**Comment by bcornwellmott** [comment]
The email is fetched upon saving. Still agree that primary contact and email should auto-fetch though.
