### ISSUE TITLE
[V7] Supplier Quotation - RFQ can be submitted multiple times

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#5486]
Steps:

1. Created RFQ.
1. Logged in as a Supplier to submit Supplier Quotation against RFQ.
1. Open RFQ, entered Price, and then Submitted RFQ.
1. On submitting RFQ, message print confirms creation of Supplier Quotation. (Message needs cleaning)
1. Since Submit button is still visible in RFQ, on clicking it, another Supplier Quotation is created.

![supplier-quotation-portal](https://cloud.githubusercontent.com/assets/910238/16106147/90f89ee4-33af-11e6-9c23-3eeea52345cb.gif)

Suggestions:

1. Once RFQ is submitted, and Supplier Quotation is created, then Submit button should not be visible there. If needed, we could provide cancel, amend like workflow.

2. Supplier should be able to see Supplier Quotations submitted by oneself.

**Comment by rohitwaghchaure** [comment]
@umairsy Supplier Quotation is not implemented yet for supplier portal, this feature is in queue.
