### ISSUE TITLE
[V7] Suggestion: Flow bar

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#5487]
Steps:

1. I completed purchase cycle by creating Material Request, RFQ, Supplier Quotation, Purchase Order, Receipt and Invoice.
1. In the Flow Bar, for the preceding transactions, dotted sign should be shown as well.

![screen shot 2016-06-16 at 10 48 03 am](https://cloud.githubusercontent.com/assets/910238/16106329/232b2128-33b1-11e6-92f9-f5a854dddb5f.png)

**Comment by saurabh6790** [comment]
Fixed.
