### ISSUE TITLE
[V7] POS Invoice Issues

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#5491]
Steps:

1. Select Customer and Items in the Sales Invoice.
1. Clicked on Pay.
1. Clicked on Submit.

Issues:

1. Once Sales Invoice is submitted, there is no notification as Sales Invoice created successfully. Or Sales Invoice id is SINV-#####

2. Even if POS invoice is created when Online, that Sales Invoice is listed under "View Offline Records".

3. POS Invoice are actually not submitted. They are in draft mode.

For all the issues, check below GIF animation. I have online when recorded this invoicing.

![pos-inv](https://cloud.githubusercontent.com/assets/910238/16112749/7111db8c-33d6-11e6-89a0-5bd3574f4068.gif)

**Comment by rmehta** [comment]
@rohitwaghchaure  maybe we should not name it as "Submit"
