### ISSUE TITLE
Sales Invoice negative amount allow

### ISSUE THREAD

**Issue by betabank** [frappe/erpnext#5494]
Hi, as requested by @nabinhait we are raising this issue in order to allow sending the customer an invoice with negative amount, this is useful for any producer that works with returnable crates, bottles, packagings and any container that has a value and may be returned to the producer.
More info and use cases here:
https://discuss.erpnext.com/t/generating-credit-notes/5045
And here:
https://discuss.erpnext.com/t/how-to-ignore-grand-total-rules/9593

**Comment by rmehta** [comment]
This is already implemented now!
