### ISSUE TITLE
Subscription system based on Quotation

### ISSUE THREAD

**Issue by anandpdoshi** [frappe/erpnext#550]
- [ ] Sales Order type Subscription / Contract
- [ ] Expiry Date (final expiry)
- [ ] Billing Cycle (Monthly, Yearly)
- [ ] Next Bill Date (one month before expiry date - default)
- [ ] Send Reminder Emails (Create Email Alert)
- [ ] On next bill date, create new Sales Order
- [ ] Based On Sales Order
- [ ] Patch (create Subscription Sales Orders for exiting Recurring Invoices)

---

In Email Alert
- [ ] Send Print Attachment

**Comment by MaxMorais** [comment]
@anandpdoshi I'm working on this!

**Comment by umairsy** [comment]
Continued at https://github.com/frappe/erpnext/issues/6313
