### ISSUE TITLE
Journal Entry - Remove Account if it has no Debit or Credit value

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#5504]
Journal Entry - Remove Account if it has no Debit or Credit value.

![screen shot 2016-06-17 at 12 20 14 pm](https://cloud.githubusercontent.com/assets/910238/16142777/ee6b417c-3485-11e6-880d-755272671dc6.png)

**Comment by nabinhait** [comment]
For reference

https://github.com/frappe/erpnext/blob/develop/erpnext/accounts/doctype/payment_entry/payment_entry.py#L280
