### ISSUE TITLE
Flex Time Hours

### ISSUE THREAD

**Issue by derekmontgomery** [frappe/erpnext#5512]
We are interested in a new feature for the Attendance Form to track Flex Time Hours.  Employees are allowed to work extra time, and take the accumulated time off at a later date.  Employees would enter the amount of hours worked as flex time on the Attendance Form, which would also display the accumulated total (similar to Leave Allocation Time).

Add 2 new fields:
1.  Flex Time Hours Worked:  (can be a negative number in case employees take time off to reduce their accumulated total).
2.  Accumulated Flex Time Hours:  running total of Flex Time Hours Worked.

**Comment by almeidapaulopt** [comment]
This could be generated from timesheet. for that is needed the working hours in employee.

**Comment by PawanMeh** [comment]
You can check if the "Compensatory Off" feature in [version 11 ](https://erpnext.org/releases/version-11/features/human-resources) meets your requirements. If it does not kindly re-open issue or create new issue mentioning the gaps in the feature.
