### ISSUE TITLE
Sales Invoice email address - V6 & V7

### ISSUE THREAD

**Issue by ghost** [frappe/erpnext#5516]
We have many companies with different billing (invoice) address to the delivery address. ErpNExt is brilliant for this, but one small issue

Invoice address is in Town 1 and has an email address town1@invoice.com
Delivery address is in Town 2 and has an email address of town2@delivery.com
Contact is John Smith who has an email address of johnsmith@contact.com

Now when we raise a quotation and select the invoice address, delivery address and contact address then when we email ERPNEXt correctly picks up the contact email address. Perfect

When we convert this to a sales order and raise an invoice the invoice email SHOULD pick up the billing email address (that is why it is there) but it does not, it still picks up the contact email address, Although we can change this by over typing we cannot select the invoice email address from a drop down

The default action should be to pick up the invoice address details when creating the invoice

From what I can see this is also the case on V7

**Comment by PawanMeh** [comment]
Did some initial analysis, since the code to get the contact is commodified, a possible solution could be to add additional check boxes in the contact master for "Default Billing Address","Default Shipping Address", setting this as an enhancement for now.
