### ISSUE TITLE
Payroll Management system

### ISSUE THREAD

**Issue by fikrut** [frappe/erpnext#5517]
how can we manage the payroll in ERP next?
there must be some tool to calculate income tax automatically in percentage based on their salary range,
there must be a tool that will calcualte overtime based on the countries rule like for holidays,night,weekend,and normal days over time,
all deduction and additional payments on payroll must be linked with their respective account in chart f account,also if possible there must be a tool that will manage employees loan deduction from payroll automatically.....and other issues must be also solved...please help us on this and if its on your road map...please inform us when it will be avialble...all other features of erpnext are best but on payroll we are still not good.thanks

**Comment by fderyckel** [comment]
Check here

https://discuss.erpnext.com/t/salary-and-deduction/10721/3

**Comment by rmehta** [comment]
Please raise issues separately for each feature
