### ISSUE TITLE
Delivery Note List - Percent billed shows dollar sign instead of percent sign

### ISSUE THREAD

**Issue by cgpurbaugh** [frappe/erpnext#5520]
see title

![screenshot dollarsign](https://cloud.githubusercontent.com/assets/13136405/16243288/84bcc0c4-37c4-11e6-8510-ad97ada3721b.jpg)

**Comment by bcornwellmott** [comment]
Addressed in https://github.com/frappe/erpnext/pull/5527

**Comment by PawanMeh** [comment]
@cgpurbaugh kindly close the issue, if it is fixed for you
