### ISSUE TITLE
Journal Entry shows 'undefined' in links

### ISSUE THREAD

**Issue by cgpurbaugh** [frappe/erpnext#5521]
See title, status shows undefined.

**Comment by nabinhait** [comment]
Could not replicate.

<img width="998" alt="screen shot 2016-07-08 at 9 29 36 am" src="https://cloud.githubusercontent.com/assets/836784/16677018/8a4a0a42-44ee-11e6-8c1d-3f40c60a392b.png">

**Comment by cgpurbaugh** [comment]
@nabinhait It's not viewing links from journal entry, it's viewing a journal voucher link from a sales invoice:
![2016-07-08](https://cloud.githubusercontent.com/assets/13136405/16686806/9909724a-44e2-11e6-80e5-e093618823b1.png)
