### ISSUE TITLE
[Time Log list] Pressing "Billable" in list, sets filter as Billable="no"

### ISSUE THREAD

**Issue by superlack** [frappe/erpnext#5532]
I found when sorting through time logs, and trying to filter down in the list view, clicking "Billed" on a time log marked as billed will set the filter to "billed=yes", however clicking billable (on a billable time log), will set the filter to "billable=no"

**Comment by PawanMeh** [comment]
Please share screen shots of the steps performed so that it is easier for us to replicate

**Comment by superlack** [comment]
This was an issue with the existing timekeeping format.  Just tested and it doesn't perform with the problem on timesheets.  Thanks
