### ISSUE TITLE
More information/dashboard on Lead

### ISSUE THREAD

**Issue by sbkolate** [frappe/erpnext#5533]
We can see customer dashboard on Customer as follows 
![customerlead](https://cloud.githubusercontent.com/assets/6648915/16335637/51c06ed8-3a25-11e6-938e-714e16bf1e4e.png)

It will help if we add more information on Lead
(e.g Opportunity Number, Number of Quotation Created, Number of ToDo)
![customerlead2](https://cloud.githubusercontent.com/assets/6648915/16335645/6036c9ee-3a25-11e6-9895-be7bfa74d4ca.png)

**Comment by PawanMeh** [comment]
Since leads are not tied to customer ID,it may not be possible to show them on customer dashboard

**Comment by PawanMeh** [comment]
Opportunity, quotations now exist in the latest release
