### ISSUE TITLE
Print preview and link through email don't show 'letter head' footer, PDF is fine

### ISSUE THREAD

**Issue by aShure** [frappe/erpnext#5536]
example from clicking the link in the email, footer isn't shown: 
![image](https://cloud.githubusercontent.com/assets/4117408/16342819/4d9d498e-3a34-11e6-977b-569b62e3b017.png)

Here is a similar invoice as a PDF, including the correct footer
[IIUG-20160624-10.pdf](https://github.com/frappe/erpnext/files/332041/IIUG-20160624-10.pdf)

**Comment by pratu16x7** [comment]
The specs (refer the end note): https://frappe.github.io/erpnext/user/manual/en/setting-up/print/letter-head

> Please note that Footer will be visible only when document's print is seen in the PDF. Footer will not be visible in the HTML based print preview.
