### ISSUE TITLE
[V7] RFQ - Error when sending Email to Supplier

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#5546]
Steps:

1. Created Material Request.
1. Created RFQ. Select supplier, contact and entered email id.
1. Save and Submitted RFQ.
1. When click on Send Email to Supplier button, getting following error message.

![screen shot 2016-06-27 at 10 58 46 am](https://cloud.githubusercontent.com/assets/910238/16369761/acbdb44c-3c57-11e6-9275-fad0f072b81d.png)

First name is correctly set for both the contacts.

**Comment by nabinhait** [comment]
@umairsy Can't replicate. Can you please test again?

**Comment by umairsy** [comment]
Work
