### ISSUE TITLE
Currency error when creating Quotation from Opportunity

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#5550]
Steps:
1. Created Lead.
1. Converted Lead into Opportunity.
1. Creating Quotation from Opportunity.

Attached is the error message as soon as data is fetched into Quotation from Opportunity. Till now, there is no question of selecting Currency for the Country. Base Currency for this Company is AED only.

![screen shot 2016-06-27 at 4 30 16 pm](https://cloud.githubusercontent.com/assets/910238/16377656/fd0a6134-3c84-11e6-8854-29fb7fcf262b.png)

**Comment by nabinhait** [comment]
Fixed via https://github.com/frappe/erpnext/pull/5678
