### ISSUE TITLE
[V7] Payment Request - No option to create

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#5554]
As per the standard permissions, Accounts User, Accounts Manager and Administrator has permission to create Payment Request. But there is no New button in the list.

![screen shot 2016-06-27 at 4 53 46 pm](https://cloud.githubusercontent.com/assets/910238/16378182/00525d58-3c88-11e6-943c-3f2f28c1f4e9.png)

Can Payment Request creation dependent on the installation of payment gateway integration application? If yes, then Payment Request should only be visible if application for payment gateway integration is installed.

**Comment by nabinhait** [comment]
Payment Request can only be created from SO / SI. @saurabh6790 Am I correct?
