### ISSUE TITLE
/desk#modules/Setup throws: get() takes exactly 1 argument (0 given)

### ISSUE THREAD

**Issue by pate** [frappe/erpnext#5561]
First-time user of ERPNext. Starting from a fresh install, I created a new custom role and I think I checked a permission for it. After that, every view breaks with a modal showing "Server Error: Please check your server logs or contact tech support."

Here is the output from `/home/frappe/frappe-bench/logs/web.error.log`:

```
2016-06-27 12:12:43,092 New Exception collected with id: 2016-06-27 12:12:43.086462-41.164.24.2-94f
 site: site1.local
 form: {'cmd': u'frappe.desk.moduleview.get'}

Traceback (innermost last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 57, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 36, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 806, in call
    return fn(*args, **newargs)
 TypeError: get() takes exactly 1 argument (0 given)
```

I'm not sure how to diagnose this further. I started poking around in the MariaDB, but I can't find any foreign key relationships (???) for tabRole table and I see that names are used as natural primary keys (no surrogate keys?). My next step would be to delete this row, but then I'm worried other things will break.

**Comment by rmehta** [comment]
@pate welcome to ERPNext! Are you using "develop"? Its unstable right now. If you testing the system out please use the "master" branch

**Comment by anandpdoshi** [comment]
Are you using production setup or develop one?

Also go to frappe-bench folder and check the output of 
bench version

**Comment by pate** [comment]
I'm using production setup.

ERPNext: v6.27.25
Frappe Framework: v6.27.22

**Comment by pate** [comment]
Looks like this might be related to https://github.com/frappe/frappe/issues/1793 ?

Can anyone kindly point me to a doc to get a better stack trace?

**Comment by anandpdoshi** [comment]
@pate what was the Role that you created?
