### ISSUE TITLE
Add ability to set host_name & developer mode from within ERP ui

### ISSUE THREAD

**Issue by cgpurbaugh** [frappe/erpnext#5563]
It would be useful to be able to set this in settings, vs changing the file on the server.  A bench restart button should be available as well.

**Comment by mhbu50** [comment]
+1

**Comment by shreyasp** [comment]
@cgpurbaugh More appropriate way to do this would be adding a command to enable-disable developer mode through `bench`. As you are aware `bench` serves as a virtual environment for ERPNext. And adding such an functionality doesn't actually seem to be good way of achieving it.

**Comment by mbauskar** [comment]
Developer Mode and Host Name can be set through `bench` using `bench set-config [KEY] [VALUE]`

Alternatives would be to use the `https://github.com/frappe/bench_manager` using `bench manager` you can set the `Developer Mode` from GUI

<img width="404" alt="screen shot 2017-10-16 at 3 46 08 pm" src="https://user-images.githubusercontent.com/11224291/31607216-27e179d0-b289-11e7-9a6c-fb6eb556c71c.png">
