### ISSUE TITLE
System showing item's available quantity in warehouse as per current date not as per posting date

### ISSUE THREAD

**Issue by rohitwaghchaure** [frappe/erpnext#5568]
- Created delivery note(draft mode) on 27th June with Item as "Macbook" and qty as "1", system shows Available Qty at From Warehouse as 0.
- Make purchase stock entry on 28th June with qty 10 in Stock Warehouse. 
- On delivery note, if user select warehouse as Stock Warehouse it shows Available Qty at From Warehouse as 10.

When user trying to submit the delivery note(on 28th June) it shows negative error because posting date is 27th June while it shows available qty as 10.

![image005b996e6](https://cloud.githubusercontent.com/assets/8780500/16406932/8eed65fc-3d2e-11e6-92aa-ff3bdcb6598b.jpg)

**Comment by ankush** [comment]
This field isn't used for validations anymore and fetching/re-fetching qty for specified posting date seems bit excessive 😅
