### ISSUE TITLE
[V7] Warehouse Tree master not listing existing warehouse

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#5569]
I have made stock entries in the default warehouses (Stores, Finish Goods etc.)

![screen shot 2016-06-28 at 1 16 29 pm](https://cloud.githubusercontent.com/assets/910238/16407711/ccb335d4-3d32-11e6-9d8a-1bdbebdc6139.png)

But in the Warehouse Tree master, it is not listing already existing Warehouses.

![screen shot 2016-06-28 at 1 16 21 pm](https://cloud.githubusercontent.com/assets/910238/16407762/09047124-3d33-11e6-9593-4377af191bf4.png)

**Comment by cgpurbaugh** [comment]
It seems that All Warehouses - FM needs to be changed to being a group warehouse.
