### ISSUE TITLE
Traceability in ERPNext

### ISSUE THREAD

**Issue by MelanieLa** [frappe/erpnext#5571]
Hi ! Here is my issue, I hope someone will be able to help me.

Our company manufactures a system which has its own serial number. However, it contains other components that have serial numbers too. When we store or sell the system, we would like to be able to trace it (it is possible thanks to the search bar in « Serial No ») but we would also like to be able to trace the components inside of it. Indeed, if we look for a specific serial number of a component, we would like to know in what system this component is but we couldn’t find a way to do that with Erpnext other than entering the serial numbers of the components in the « more details » box and open every serial number of a system to see if the component we are looking for is in it, which can make us loose a lot of time.. Is there a solution to this problem ?

**Comment by Arundhatii** [comment]
Hello,
You can trace components inside a manufactured finished product using the report "Issued Items Against Production Order".
This report can be referred to find the serial number component used to manufacture a system.
![screenshot from 2016-08-12 12 44 41](https://cloud.githubusercontent.com/assets/20164097/17617812/cba70c62-6099-11e6-82a3-2185200e4021.png)

Hope this solve the problem.
