### ISSUE TITLE
[V7] Error when opening new transactions

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#5573]
![new-sinv](https://cloud.githubusercontent.com/assets/910238/16410607/f15039ba-3d40-11e6-8bd5-1f454532f418.gif)

This error is replicating in sales transactions, from Quotation to Sales Invoice. Issue also occuring if open new document from list view.

**Comment by saurabh6790** [comment]
Fixed with https://github.com/frappe/frappe/pull/1819
