### ISSUE TITLE
[V7] Issues in Quick View

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#5574]
In the Quick View, add fetch script is not executed. For example, I tried creating Production Order from quick view. After selecting Production Item, BOM was not auto-fetched. It works just fine in the full page view.

![quick-view-issue](https://cloud.githubusercontent.com/assets/910238/16411650/aca76e0a-3d45-11e6-8e82-bd367523908a.gif)

Same way, while creating an Item Code, value of Item Code is copied to Item Name and Description field as well. This doesn't work in the quick view.

**Comment by nabinhait** [comment]
JS code does not work in quick entry.

Removed BOM and Pro Order from Quick Entry.
