### ISSUE TITLE
[V7] New Item - Valuation Rate is not set based on Opening Qty and Price

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#5578]
Steps:

1. When adding new Item, entered Opening Stock and Valuation Rate.

![screen shot 2016-06-28 at 4 53 51 pm](https://cloud.githubusercontent.com/assets/910238/16413718/4cf0e70a-3d51-11e6-9ec7-c4b47e7e8981.png)

2. Stock Entry is created for updating opening stock balance of an Item. But in the Stock Entry, Standard Rate is not set as Valuation Rate. Hence item's stock valuation is set as 0.

![screen shot 2016-06-28 at 4 54 29 pm](https://cloud.githubusercontent.com/assets/910238/16413764/9c81ef6c-3d51-11e6-8df7-a9655d991b18.png)

**Comment by nabinhait** [comment]
Changed "Standard Rate" to "Standard Selling Rate", it adds rate in default selling price list.

Added another field "Valuation Rate", depends on "Opening Stock".

**Comment by ShashaQin** [comment]
@nabinhait  did the commit of 'Item Valuation Rate in case of negative inventory' solve this issue?
