### ISSUE TITLE
Electronic Signature

### ISSUE THREAD

**Issue by conelco** [frappe/erpnext#5585]
Dear Developer,
request to have module for electronic signature ( sign)  to save from printing paper and getting signature on hard copy.

customers, receivers can sign electronically on Gadgets ( Ipad, Tablet, Smart Fones.) instead of accessing and printing paper.

**Comment by rmehta** [comment]
Duplicate of #4410

**Comment by conelco** [comment]
Dear Mr Mehta i do not understand this , as i m new to this Github.

**Comment by cgpurbaugh** [comment]
@conelco Issue #4410 has the same request as the one you made.
