### ISSUE TITLE
Delivery note not reflecting current stock levels

### ISSUE THREAD

**Issue by cgpurbaugh** [frappe/erpnext#5590]
If a delivery note is created before a stock entry, it will not see that stock entry's items.  

I believe that this is caused by the Posting Date.  Is there a way to make the posted date the present time until the note is submitted?

**Comment by rmehta** [comment]
I think it would be dangerous to automatically change posting date and time without the user's permission. I think the new message is much cleaner. Let's see if this request comes up more often.

**Comment by cgpurbaugh** [comment]
@rmehta What new message?
