### ISSUE TITLE
[V7] Sales Invoice - Customer is getting reset

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#5596]
Steps:

1. Created Time Sheet.
2. Creating Sales Invoice against Time Sheet.
3. Selected Customer in the Sales Invoice.
4. Selected Item.

On selecting Item, Customer value gets reset.

![inv-ts-error](https://cloud.githubusercontent.com/assets/910238/16441440/2cfd7750-3de8-11e6-8a1c-cb8ec42f6de2.gif)

**Comment by saurabh6790** [comment]
Not able to reproduce !!!
