### ISSUE TITLE
[V7] Customer Portal - Cannot view Task with Status = Working, Pending for Review, Cancelled

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#5600]
View as a System User:

![screen shot 2016-06-29 at 2 26 46 pm](https://cloud.githubusercontent.com/assets/910238/16446510/946544c8-3e05-11e6-8c2f-82b5bdefdade.png)

View as a Website User:

![screen shot 2016-06-29 at 2 27 03 pm](https://cloud.githubusercontent.com/assets/910238/16446514/9da58462-3e05-11e6-94d1-bf926ac11226.png)

**Comment by KanchanChauhan** [comment]
It is by design, we are just showing open and close tasks to Website User.
