### ISSUE TITLE
[V7] Project - Tasks visibility

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#5601]
Steps:

1. Open existing Project.
2. Edit Status for Task.
3. Save Project.

After saving Project, none of the Task is visible in the Project. After a refresh, Tasks are visible again.

![project-task-visibility](https://cloud.githubusercontent.com/assets/910238/16446748/be2237ca-3e06-11e6-8fbc-74e7edb24264.gif)

**Comment by KanchanChauhan** [comment]
And if you refresh the page, tasks come back. :P
