### ISSUE TITLE
[V6] User portal Orders list requires Invoice record to flag SO as payed although a payment was made.

### ISSUE THREAD

**Issue by forellana-digithinkit** [frappe/erpnext#5606]
Hi

I noticed what may be an issue while testing the user portal view of orders. I know it may not be a regular thing that people do, but the system does allow it to happen. 

If you do the following:
- Create Sales Order
- Submit Sales Order
- Create Payment Request
- Submit Payment Request
- Later user goes to the user portal and pays the Payment Request

Now on the user portal under the list of Orders this last order displays as "Not Paid and Not Delivered" although it just took a payment. And will allow you to open it and attempt to "pay" this Payment Request. At this point if you click "Pay" you will see a(non user friendly) python error about this payment request was already completed previously.

Now, if I create the Invoice on the backend for this Sales Order, the list is updated correctly and the Pay button disappears. 

I thought I would bring it to your attention.

**Comment by jwrober** [comment]
Is this still an issue?

**Comment by jwrober** [comment]
@forellana-digithinkit - is this still an issue in latest 8.x?
