### ISSUE TITLE
[V7] Customer Portal - When check RFQ, left bar gets hidden

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#5610]
In the Customer Portal, when checking Project, Invoices, Shipment, left bar keep showing. But when check Request for Quotation, left bar gets hidden.

![cp-rfq-left bar](https://cloud.githubusercontent.com/assets/910238/16479854/94ca5186-3ec0-11e6-906d-1af29681478b.gif)

**Comment by shubham7saxena** [comment]
I'll take care of it
