### ISSUE TITLE
[v7] Initial Item in table causes issues

### ISSUE THREAD

**Issue by bcornwellmott** [frappe/erpnext#5624]
In v7, tables start out with an empty child in order to make entering data easier (can add data from the parent form). This causes problems in some forms where no data is expected in the child tables at the start. For example, in Purchase Order, the Get Material Requests from Supplier button requires that no children be in the items table, but since there is a blank entry, the button won't show up.

Not sure if the fix is to change the conditions for tables that are empty, or if somehow a blank child entry should be treated as non-existent.

**Comment by nabinhait** [comment]
For now I have changed the condition for visibility of the button. 
https://github.com/frappe/erpnext/pull/5679

**Comment by srinivasragav** [comment]
@nabinhait . Hi , Is this issue fixed ?
