### ISSUE TITLE
[v7] cancel submitted Salary Slip

### ISSUE THREAD

**Issue by cecetw** [frappe/erpnext#5637]
A submitted Salary Slip can not be deleted nor cancel. The is no way to correct, if there were any mistake made.

**Comment by bcornwellmott** [comment]
Are you sure you have permissions to cancel and delete it? I have been successful in doing it.

**Comment by KanchanChauhan** [comment]
@cecetw Salary Slip can be canceled and even deleted. Can you please check your permissions.
