### ISSUE TITLE
missing translations

### ISSUE THREAD

**Issue by adamtong1110** [frappe/erpnext#5658]
installed version:
ERPNext: v6.27.25
Frappe Framework: v6.27.23

<img width="1029" alt="2016-07-06 2 18 35" src="https://cloud.githubusercontent.com/assets/1941183/16609209/b8a746fe-4384-11e6-8d40-f7d7413469ba.png">

I found the zh-cn.csv has the translation for the strings and the desktop.py has the _("Human Resources"). But the translation seems not working. How can it be fixed?

Thank you in advance!

**Comment by adamtong1110** [comment]
any solution?

**Comment by Braintelligence** [comment]
I also have problems with the translation.

ERPNext 6.27.25
Frappe 6.27.24

I use the German localisation but there are strings that are already translated here:
https://translate.erpnext.com/

But aren't translated in the app.

I don't understand why this is not synchronized. What do I have to do to get the latest translation?

**Comment by anandpdoshi** [comment]
These will be released with v7. We haven't back ported the translations to v6 yet.
