### ISSUE TITLE
Child Table V7 format needs to be changed

### ISSUE THREAD

**Issue by srinivasragav** [frappe/erpnext#5660]
The child table's first row appears before clicking the add row button , due to which the custom script is not working for the first row , every time the first row should be deleted and scripts work in the second row .
Absolutely no problem with the 6.27 version , please remove this option

**Comment by rmehta** [comment]
@srinivasragav must be an issue with your custom script. no reason this should not work.

The new row comes only if mandatory and its great for user experience.

**Comment by srinivasragav** [comment]
Thank you for responding sir , but my script was working like a charm in v6.27 , now the same script does not work with v7 , I need to delete the first row and the script will work . Why is it so ?

**Comment by rmehta** [comment]
Can't respond without seeing your script. Please share only the relevant part.

**Comment by srinivasragav** [comment]
I even shared the script in the forum , but I did not get any reply , Could you please tell me where I am going wrong ? 

frappe.ui.form.on("BOM", {
item: function(frm) {
frappe.call({
"method": "frappe.client.get_value",
"args": {
"doctype": "Item",
"filters": {"item_code": cur_frm.doc.item},
"fieldname": ["percnt_carbon_min"]
}, 
callback: function(r) { 
cur_frm.set_query("item_code", "items", function(doc, cdt, cdn){
return {
"filters": {
"percnt_carbon_min": [">=",r.message.percnt_carbon_min],
"item_group": "Raw Material"
}
}
});
}
});

}
});

**Comment by cgpurbaugh** [comment]
I've had the same problem.

**Comment by srinivasragav** [comment]
@rmehta  , Sir kindly refer this link [https://github.com/frappe/erpnext/issues/5624](url) , the problem is not with my script , it is initial fields in the child table , I did not have issues with v6.27 . Why this issue is closed ?

**Comment by srinivasragav** [comment]
@cgpurbaugh . Did you solve it sir ?

**Comment by srinivasragav** [comment]
Why this is closed ?

**Comment by cgpurbaugh** [comment]
The Issue that @srinivasragav was trying to issue is #5624

**Comment by srinivasragav** [comment]
@rmehta . Sir you told me you could not respond without seeing my script but , it's been 4 days since I shared my script and I am yet to receive a reply , I understand you have to address lot of issues but I feel sad to see a wontfix label , when the problem is on your side . Please respond , help me if I am wrong as I have already shared my script .

**Comment by rmehta** [comment]
It is humanly not possible to help each and everyone out, specially with customisations. The software is free but my time is not. You should follow this up on the forum.

If you urgently need help, pay someone in the community, or share enough "specific" info so it's easy to help you.

Since your subject is that "grid needs to change", hence wontfix
