### ISSUE TITLE
[V7] Razorpay Integration - Secret Key Validation issue in Payment Request

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#5672]
Steps:

1. Created account on Razorpay.
2. Enter Razor Pay API details in the hosted version 7 account.
![screen shot 2016-07-06 at 4 23 34 pm](https://cloud.githubusercontent.com/assets/910238/16615801/bdacb14a-4396-11e6-8b46-696ba1265000.png)
3. Created Sales Order.
4. Tried creating Payment Entry against Sales Order.

When saving Payment Entry, error message says the API Secret provided for the Razorpay in not valid. I checked couple of times, and found it to be valid.

![screen shot 2016-07-06 at 4 35 14 pm](https://cloud.githubusercontent.com/assets/910238/16615955/aefc30ca-4397-11e6-9320-cf9c7d3ac505.png)

**Comment by saurabh6790** [comment]
fixed via  https://github.com/frappe/razorpay_integration/pull/3
