### ISSUE TITLE
Bug in Letter head - v7

### ISSUE THREAD

**Issue by srinivasragav** [frappe/erpnext#5677]
There is a bug with the letter head in v7 beta . The image attached to the letterhead disappears while saving . But it could be achieved thru HTML coding .

Even others who are using the v7 are facing this issue . For the ease of reference I have attached the below link [https://discuss.erpnext.com/t/bug-in-letter-head-v7/13928](url)

**Comment by KanchanChauhan** [comment]
@srinivasragav This was recently fixed. Just do bench update.
