### ISSUE TITLE
Saving a report with report builder causes "Not Found Page" when trying to load

### ISSUE THREAD

**Issue by ioweb-gr** [frappe/erpnext#5682]
When trying to access a saved report from the report builder the URL is different than when going to "Report List" then accessing the saved report and clicking on "Show report"

From Sales Invoice
![capture](https://cloud.githubusercontent.com/assets/20220341/16649009/5dd6bc3a-443f-11e6-9a5a-c581c20abf7d.JPG)

From Report List the url looks like and produces the proper report
http://domain.com/desk#Report/Sales%20Invoice/Sales%20Invoice%20with%20Status

This happens to every report I checked

**Comment by nabinhait** [comment]
fixed via https://github.com/frappe/frappe/pull/1860
