### ISSUE TITLE
[V7] Upgrade from V6 to V7

### ISSUE THREAD

**Issue by Gleisson03** [frappe/erpnext#5685]
ERPNext: v6.27.25
Frappe Framework: v6.27.22

When I try to upgrade, the following error appears

![tela 1](https://cloud.githubusercontent.com/assets/13992475/16654378/e35b9ab0-442b-11e6-96a6-358eb3cd4645.png)
![tela 2](https://cloud.githubusercontent.com/assets/13992475/16654379/e36225e2-442b-11e6-989d-30c722598e30.png)

**Comment by nabinhait** [comment]
Which steps are you following to upgrade?

**Comment by Gleisson03** [comment]
I'm following the steps suggested by @anand.

> Go to bench-repo folder and run: git pull && git checkout develop
> Go to frappe-bench folder and run: bench --site all backup
> Then run: bench switch-to-develop --upgrade
> Then try running: bench update

Link: https://discuss.erpnext.com/t/version-upgrade-from-6-to-7/13305/14?u=gleisson03

**Comment by nabinhait** [comment]
Pushed a potential fix https://github.com/frappe/erpnext/pull/5699.

Can you please try to update again?

**Comment by Gleisson03** [comment]
It worked, thank you very much for your attention and for your work.
