### ISSUE TITLE
ERPNext - trying to write an invoice for a service, system insists on a batch No.

### ISSUE THREAD

**Issue by otbopko** [frappe/erpnext#5689]
Hi all,
I am trying to write a generic invoice to one of my customers for what they sold on consignment. The customer is OK with a simple invoice saying "Sales for June-16" for example. They keep track of all the sales per unit and send me monthly reports.I created an item "Sales" and put it in the "Services" category so ERP does not ask me for batch no. I set as UOM "hours" but still every time I try to write an invoice, ERP requires a batch no..... really frustrating. Any suggestions? Thanks.

**Comment by nabinhait** [comment]
Could not replicate the issue. Can you please check if you have made the "Batch No" field mandatory in Sales Invoice Item form via Setup -> Customize Form.

**Comment by otbopko** [comment]
![image](https://cloud.githubusercontent.com/assets/20341535/16676641/7b6df866-449a-11e6-92ea-432eeb50acdb.png)

**Comment by nabinhait** [comment]
@otbopko I am not talking about Item form. Check Sales Invoice Item table from Customize Form.

**Comment by otbopko** [comment]
But I need the batch no. for my batch-wise products... I need to have batch for some products and no batch for services....

**Comment by nabinhait** [comment]
yeah, for that you do not need to make "Batch No" field mandatory in Sales Invoice Item table. If you check "Has Batch No" field in Item for stock items, system will force you to enter Batch No in all stock related transactions.

**Comment by otbopko** [comment]
Oh Glory day, finally it worked....you are so helpful... can you help me create non-taxable items? Pleaseeee

**Comment by nabinhait** [comment]
Please post your query in discuss.erpnext.com. This is a place only for reporting error / feature request.

**Comment by otbopko** [comment]
I tried posting - nobody answers. Or the answers are too complicated. I am sure it is something simple - I just need to set it up so it does not levy tax on some products.... I would really appreciate it.

**Comment by nabinhait** [comment]
Please post your query in the forum, I will reply there.
