### ISSUE TITLE
Default Tax Template

### ISSUE THREAD

**Issue by epochc** [frappe/erpnext#5695]
As you save a tax template, it automatically gets set as default. Operator has to unclick the Default button and save that again. Which operators forget and then it gets automatically gets pulled into transactions. This is very, very annoying. Great if you can fix this.

**Comment by rmehta** [comment]
@epochc  cannot replicate. It does not make default unless you specifically check

**Comment by epochc** [comment]
Okay try replicating this issue thusly:

First ensure that no Tax Template is the default template. (this doesn't happen if there is a default tax template already). So, no default tax template and proceed on.

Create or modify a new Tax Template. Make sure that you have not clicked the Default Check Box. Save the template. Surprise, you will see this template saved as the default tax template.

Now the operator has to notice this and uncheck the Default Check Box and save again. Else, it gets pulled into every transaction.

It's so annoying. I'm surprised you cannot replicate it.

Thanks

Jay

**Comment by epochc** [comment]
Same thing happens when you modify a template. Again there should be no default tax template for this annoyance to occur.

**Comment by rmehta** [comment]
Fixed.

> Again there should be no default tax template for this annoyance to occur.

Always helps to explain the full steps to recreate the issue.

**Comment by epochc** [comment]
Yep. My bad. But thanks for fixing it.

Jay
