### ISSUE TITLE
Problem with Child Table V7 

### ISSUE THREAD

**Issue by Ninjarazor** [frappe/erpnext#5696]
Hi All ,
I just updated from v6.23 to v7 beta and facing an issue , I had a custom script to filter a link in the child table, I could see the first row in the child table appears before clicking the add button which causes this issue . My script works like a charm upon deleting the first row which is hard coded. Checked again my script is perfect. Could you guys please fix this . Please do not ignore this issue thinking that there could be a problem with my script , it works perfectly in version v6.23. I even tried checking if others are facing this issue and my search yielded two links [https://github.com/frappe/erpnext/issues/5624](url)
[https://github.com/frappe/erpnext/issues/5660
](url)
but sad to see the above things were closed without a proper fix.

Thanks in advance

**Comment by rmehta** [comment]
This is a free software, feel free to share your patch. If it makes sense, we will accept it.

**Comment by nabinhait** [comment]
There are 2 simple solutions for the problem you are facing:

1. Remove BOM Item table from mandatory and in validate function write a code to make sure items table is not blank.

2. In onload function, set the item table as blank.

I think this will solve the issue.

**Comment by Ninjarazor** [comment]
Hi @rmehta  and @nabinhait .

Many thanks for responding to the issue in-spite of your hectic schedule . I am sharing my code here , it is very simple only if the glass field's value matches it would get displayed in the bom item table. 

```
frappe.ui.form.on("BOM", {
item: function(frm) {
frappe.call({
"method": "frappe.client.get_value",
"args": {
"doctype": "Item",
"filters": {"item_code": cur_frm.doc.item},
"fieldname": ["glass"}, 
callback: function(r) { 
cur_frm.set_query("item_code", "items", function(doc, cdt, cdn){
return {
"filters": {
"glass": ["=",r.message.glass],
"item_group": "Raw Material"
}}});}});}});
```
I could not add the refresh function here , as you could see the only workaround is to remove the hard coded first row of the child table , am I right ?

Please guide.

Thanks in advance

**Comment by nabinhait** [comment]
Have you tried my suggestions?

**Comment by rmehta** [comment]
@Ninjarazor If you have a specific issue in the grid please report. We don't have the time/energy/motivation to debug your custom script. If you need urgent help, pay someone from the community

**Comment by Ninjarazor** [comment]
@nabinhait . Thanks a ton for your swift response sir . I am a novice , just I know the basics , got the above code from the internet and customized it for my requirement . I removed the BOM Item table from mandatory and don know how to validate function to make sure items table is not blank.
Please could you guide me , how to do that ?

Thanks in advance

**Comment by Ninjarazor** [comment]
@rmehta . Thanks a lot for responding sir and sorry for wasting your time, I did not have any issue with v6.23 , that is why I am reporting .

**Comment by rmehta** [comment]
@Ninjarazor v7 is a different than v6. You will have to update your custom scripts. If you discover a specific issue in the core app, then report.
