### ISSUE TITLE
ERPNext manual webpage is not (getting) rebuilt from the repo

### ISSUE THREAD

**Issue by strixaluco** [frappe/erpnext#5697]
Reading the first sentence in the [Customize form](https://frappe.github.io/erpnext/user/manual/en/customize-erpnext/customize-form.html) article:

> Before we venture to learn form customization tool, click [here](https://frappe.github.io/frappe/user/tutorial/doctypes.html) to understand the architecture of forms in ERPNext. It shall help you in using Customize Form tool more efficiently.

One can notice that the link to the [DocType](https://frappe.github.io/frappe/user/en/tutorial/doctypes.html) article is broken, but at the same time it is perfectly correct [in the repository](https://github.com/frappe/erpnext/blob/develop/erpnext/docs/user/manual/en/customize-erpnext/customize-form.md).
Apparently the "Customize form" page hasn't been rebuilt or the rebuild process fails.

**Comment by rmehta** [comment]
Thanks - we will rebuild docs soon around v7
