### ISSUE TITLE
System so slow

### ISSUE THREAD

**Issue by HelenShires** [frappe/erpnext#5700]
It is taking abouut 10 or 15 seconds between each key command. I am struggling to work on the system. It's getting slower each day. Is this due to updates been done?

**Comment by rmehta** [comment]
@HelenShires where are you hosting your system? which version are you using?

**Comment by HelenShires** [comment]
Not sure what you mean...its on my laptop which hard wired in to our 20 meg lease line. How do I find out what version I am using? Thanks

**Comment by rmehta** [comment]
@HelenShires  we are looking into it. There is an issue with one of our servers. Sorry for the inconvenience

**Comment by HelenShires** [comment]
Lovely, thank you for been so prompt in your response.

**Comment by rmehta** [comment]
@HelenShires I hope this is fixed now. Sorry for the inconvenience
