### ISSUE TITLE
[V7] Loading issue when proceed to new transaction

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#5706]
Steps:

1. Created Lead
2. Converted Lead into Opportunity
3. Converted Opportunity into Quotation.
4. When trying to create Sales Order from the Quotation, link is updated (as in the screenshot), but Sales Order form is not loaded.

![screen shot 2016-07-11 at 3 10 49 pm](https://cloud.githubusercontent.com/assets/910238/16726659/fe27dc80-477a-11e6-9025-585d4b87d941.png)

**Error message found in the browser's console:**

Failed to load resource: net::ERR_CONNECTION_REFUSED
4http://localhost:8000/ 

Failed to load resource: net::ERR_CONNECTION_REFUSED
http://localhost:8000/?doctype=Sales+Order&with_parent=1&cached_timestamp=&cmd=frappe.desk.form.load.getdoctype&_=1468229782127 Failed to load resource: net::ERR_EMPTY_RESPONSE

**Comment by KanchanChauhan** [comment]
@umairsy I am not able to replicate it. It may be because of your Ad blocker or something. Does not look like Eprnext Issue.

**Comment by KanchanChauhan** [comment]
@umairsy still can't replicate, tried couple of times :( Can you test on some other browser or Incognito window.

**Comment by rmehta** [comment]
seems fixed
