### ISSUE TITLE
Supplier Quotation doesn't have % Ordered

### ISSUE THREAD

**Issue by cgpurbaugh** [frappe/erpnext#5714]
could this be added like the Material Request has?

**Comment by bcornwellmott** [comment]
Would you want to have a % ordered here? I feel like the material request is an indication of what materials you need, whereas the Supplier Quotation is just as likely to be for planning (not directly tied to material needs). 

I can't think of a usage case where this is helpful - could you explain?

**Comment by cgpurbaugh** [comment]
Well, I guess it comes down to a difference in workflows.  I’m not sure what would be considered a standard procedure for purchasing, but in our case, department managers generate material requests.   The purchasing department generates supplier quotations, and sends them to the company president for approval.  After the president approves the quotation, purchasing is free to create a purchase order.  If purchasing looks at the Supplier Quotations to see what needs to be made into a PO, they would rather be able to see if the items on the SQ have already been ordered, rather than backtracking to the Material Request.
