### ISSUE TITLE
Profitability of a Specific Sale

### ISSUE THREAD

**Issue by mjomane** [frappe/erpnext#5725]
Hi

We need to know how much are we making on a specific sale. Basically selling price rate minus buying price rate
It needs to be there on both invoice types, normal sales invoice and point of sale invoice.
Obviously this will be for viewing purposes only and not be printed on the invoice but trust me, in my previous pos system, this was my most valued feature. Determining the size or eligibility of a discount depended heavily on the system's ability to show me how much I was making on a specific sale during the transaction while the customer waited for my decision.

**Comment by rmehta** [comment]
@mjomane Have you see the Gross Profit report? You can filter it by invoice, item

**Comment by mjomane** [comment]
You don't understand what I mean. 

I am talking about live update the gross profit during the transaction. 

For example, the total and the tax are calculated live as you type items in, in the same way, the gross profit per transaction should also be given to you as you complete an invoice.

The gross profit report you speak of is excellent for post transaction analysis. I am talking about a live occurrence of it.

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.
