### ISSUE TITLE
Desktop icon labels

### ISSUE THREAD

**Issue by turner-james** [frappe/erpnext#5746]
We would like to be able to change the label wording for desktop icons. More specifically, if we create a Custom Report and wish to add it to the Desktop, we want to be able to name it with a custom label (rather than the generic, non-descriptive label that ERPNext gives it by default).

**Comment by mhbu50** [comment]
+1

**Comment by rmehta** [comment]
@turner-james you can change it by editing the **Desktop Icon** record. (you need to be system manager to edit)
