### ISSUE TITLE
Email contact lookup

### ISSUE THREAD

**Issue by turner-james** [frappe/erpnext#5747]
When sending emails from documents, we need the ability to look up contacts' email addresses. We do not always want to use the default email address - so we need to be able to search from within the email composition box for an alternative contact.

**Comment by me2ne** [comment]
very good option , it's good if they add for sms too  so we can chose right contact number to send sms or email or send to all contact of lead or customer .

**Comment by mhbu50** [comment]
+1

**Comment by Devens** [comment]
+1

**Comment by mbauskar** [comment]
This was added in version 8
