### ISSUE TITLE
Problem with pending quantity field in production planning tool

### ISSUE THREAD

**Issue by srinivasragav** [frappe/erpnext#5750]
Hi Experts,

I am on v7 beta , the pending quantity field in the production planning tool always displays 0.00 irrespective of the sales order and the item selected . 

Thank you,

**Comment by Ninjarazor** [comment]
Yes even the same case here , @nabinhait  Sir could please help us with this ?

**Comment by nabinhait** [comment]
Can't replicate the issue.

<img width="1014" alt="screen shot 2016-07-18 at 10 16 53 am" src="https://cloud.githubusercontent.com/assets/836784/16906196/d54695a8-4cd0-11e6-843f-9bc064adf2e9.png">


Check whether items has already been delivered, pending qty is undelivered qty in SO. Another thing to confirm, Pending qty is set only if you pull items using "Get Items" button. It does not set if rows added manually.

**Comment by Ninjarazor** [comment]
Yes it works for me  when I create a delivery note for the items , but that should not be the use case . The pending qty should be displayed against the production order and not on the delivery note . Anyway thanks for the help.

**Comment by nabinhait** [comment]
But there is no point to producing against Sales Order if the item is already delivered.

**Comment by Ninjarazor** [comment]
Thanks a lot for the quick response and for your continued support but we would have received a sales order for 500 numbers to deliver in the december month but we would have produced 250 in this month and if we plan to produce another 250 after two months how to check how many we have manufactured to complete the project ?
