### ISSUE TITLE
[V7]Opening Stock for Serialized Inventory 

### ISSUE THREAD

**Issue by Arundhatii** [frappe/erpnext#5753]
When creating a new item if Opening stock is entered and 'Has Serial number" is checked error message is there.
For the serialized item, Opening Stock should not be updated from the Item master.

![serial no](https://cloud.githubusercontent.com/assets/20164097/16831155/fb34f402-49c0-11e6-8099-80bcfc7199d9.png)

**Comment by rohitwaghchaure** [comment]
@Arundhatii 
Set serial number series in item master.
