### ISSUE TITLE
[v7] Deadlock in Item Variant Table

### ISSUE THREAD

**Issue by adityaduggal** [frappe/erpnext#5756]
Hi,

Just was trying to add a new value in an existing attribute in v7 develop branch and found out the system just hangs and sometimes I get the error Another Transaction is blocking this and try after sometime

I have tried to do this after stopping and starting the bench but to no avail. I think the way the code is running to check the existing item codes for the attributes is creating a deadlock into the system, I think the problem is with:

https://github.com/frappe/erpnext/blob/develop/erpnext/stock/doctype/item_attribute/item_attribute.py#L25-L29

Which used to be like this below:

https://github.com/frappe/erpnext/blob/master/erpnext/stock/doctype/item_attribute/item_attribute.py#L43-L57

@rmehta: Could you please shed some light on this as this commit was made by you: https://github.com/frappe/erpnext/commit/aed79e993f51a7b2d4379359e516705115a55fd0

**Comment by rmehta** [comment]
@adityaduggal  I have pushed a fix that will make the validation faster. Can you check?

**Comment by adityaduggal** [comment]
@rmehta I am getting this error below, surely it is validating an item but since there is no mention of the item code, I am unable to find which item code its talking about maybe the message can be a bit more informative.

Now I have just tried to change the ordering of the child table inside one of the attribute and then save then I am getting this error. I think it is validating all items and I can't really know which item is giving this error and also this kind of validation is not there in v6, though I think it's a good thing to have this validation.

Let me know if you need more information. Btw this validation took around 28secs on my test environment to throw the below error

![image](https://cloud.githubusercontent.com/assets/1057509/16879975/9460fad0-4ad0-11e6-9dff-7789d5e5fbe7.png)


```
Traceback (most recent call last):
  File "/home/aditya/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 20, in savedocs
    doc.save()
  File "/home/aditya/frappe-bench/apps/frappe/frappe/model/document.py", line 264, in save
    self.run_post_save_methods()
  File "/home/aditya/frappe-bench/apps/frappe/frappe/model/document.py", line 663, in run_post_save_methods
    self.run_method("on_update")
  File "/home/aditya/frappe-bench/apps/frappe/frappe/model/document.py", line 606, in run_method
    return Document.hook(fn)(self, *args, **kwargs)
  File "/home/aditya/frappe-bench/apps/frappe/frappe/model/document.py", line 771, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/aditya/frappe-bench/apps/frappe/frappe/model/document.py", line 754, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/aditya/frappe-bench/apps/frappe/frappe/model/document.py", line 600, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/aditya/frappe-bench/apps/erpnext/erpnext/stock/doctype/item_attribute/item_attribute.py", line 24, in on_update
    self.validate_exising_items()
  File "/home/aditya/frappe-bench/apps/erpnext/erpnext/stock/doctype/item_attribute/item_attribute.py", line 30, in validate_exising_items
    validate_item_variant_attributes(item[0])
  File "/home/aditya/frappe-bench/apps/erpnext/erpnext/controllers/item_variant.py", line 62, in validate_item_variant_attributes
    .format(attribute, from_range, to_range, increment, item.name), InvalidItemAttributeValueError)
  File "/home/aditya/frappe-bench/apps/frappe/frappe/__init__.py", line 299, in throw
    msgprint(msg, raise_exception=exc, title=title)
  File "/home/aditya/frappe-bench/apps/frappe/frappe/__init__.py", line 292, in msgprint
    _raise_exception()
  File "/home/aditya/frappe-bench/apps/frappe/frappe/__init__.py", line 265, in _raise_exception
    raise raise_exception, encode(msg)
InvalidItemAttributeValueError: Value for Attribute d1_mm must be within the range of 1.0 to 100.0 in the increments of 0.001 for Item 100.0
```

**Comment by rmehta** [comment]
pushed another fix for the error. Can you check? Most likely you have an item with an invalid attribute value.

**Comment by adityaduggal** [comment]
@rmehta Works fine and the message is at least giving me the name of the item for validation error.

Just one thing, I wanted to say before I close this issue. You have added a new validation that when we change one attribute then the system would check for integrity of all data for all attributes. In my case the error was due to d1 (numeric value) had a range set as 1 to 100 in step of 0.001 where inside the template I had by mistake changed the range from 0.5 to 10 in step of 0.01, 

Now earlier there was no validation whether numeric range is OUT of range of the actual attribute but since now there is a validation (which is good) how can old customers who might have data outside of their range would change the things since there could be more than 1 attribute setup wrongly and then the problem would happen as the user would have change the values in the mysql db at backend to get it in sync with Frappe validation. 

Just a thought only for old customers using attributes and they would definitely have some issues, just wanted to make you aware that this would come up as an issue in v6 to v7 upgrade for old users.

**Comment by rmehta** [comment]
@adityaduggal this validation should have been there. Maybe we can un-assign, skip in the patch.

**Comment by adityaduggal** [comment]
I fully agree that this validation should have been there and I guess that if there is some kind of issue in a user's DB then they would have to do it at backend if its in more than one attribute.
But again :+1:  for this validation. I must say the team does skip a lot of validations initially :stuck_out_tongue_winking_eye:
