### ISSUE TITLE
Bug with production planning tool v7

### ISSUE THREAD

**Issue by srinivasragav** [frappe/erpnext#5768]
Hi All ,

There is a bug with production planning tool and production order in v7 beta , it allows the user to create a production order with more quantity than the quantity mentioned in the sales order . 
If I had created a sales order for 500 numbers , the production order allows us to create 300 numbers in one production order and 300 in another production order , there is no validation here.

**Comment by Ninjarazor** [comment]
Set Over Production Allowance Percentage is set as 0 . This should be closed
