### ISSUE TITLE
Latest update removed production order validation

### ISSUE THREAD

**Issue by Ninjarazor** [frappe/erpnext#5778]
Hi ,

The latest update removed the validations in the production order , the user could create more quantity than mentioned in the selected sales order . Please fix this at the earliest .

**Comment by srinivasragav** [comment]
Yes , even I am experiencing this . Seems to be a major bug. Experts please help

**Comment by vjFaLk** [comment]
Are you both on the develop branch?

**Comment by Ninjarazor** [comment]
Yes , Sir I am on develop branch .

**Comment by srinivasragav** [comment]
@vjFaLk  Yes sir I am on develop branch v7 beta

**Comment by Niville** [comment]
@vjFaLk  Same issue here . Even I am on develop branch v7 beta . Facing lot of issues without validation.

**Comment by nabinhait** [comment]
I cannot replicate the issue in my local. It is giving correct validation to me.

<img width="1039" alt="screen shot 2016-07-18 at 9 36 51 am" src="https://cloud.githubusercontent.com/assets/836784/16905919/6cff776c-4ccb-11e6-967c-8037e2df29b0.png">

Can you please check if you have set "Over Production Allowance Percentage" in Manufacturing Settings?

**Comment by Ninjarazor** [comment]
Over Production Allowance Percentage is set as 100

**Comment by nabinhait** [comment]
Allowance Percentage 100 means system allows production of double qty of SO.

**Comment by nabinhait** [comment]
If you don't want to allow more that SO qty, it should be set as zero.

**Comment by Ninjarazor** [comment]
Yes I set that as zero , but I did not change the value in manufacturing setting it is a fresh install , I came to know about this only when you told me to check . I ran bench update and I was facing the issue .Even the other fellows are facing the issue because of this it seems

Thanks a lot ,

**Comment by Ninjarazor** [comment]
This issue can be closed , but the new update sets the Over Production Allowance Percentage in manufacturing setting as 100 . Thanks for the help

**Comment by nabinhait** [comment]
I have tested in a newly installed site, system does not set default value as 100. Also checked code/patch, there no such thing which sets it as 100. Anyway, closing this issue.
