### ISSUE TITLE
Version 7 POS Serial entry

### ISSUE THREAD

**Issue by StalinNR** [frappe/erpnext#5779]
We are unable to select items using serial numbers, this was possible in v6, we can i/p serial in the product search bar and the POS would bring up and add the item with serial in the packed item list. i tested in beta.erpnext.com and am unable to replicate that functionality in v7. Since most of our products are serialised, we would be glad to have serial input in POS.
![posfeature](https://cloud.githubusercontent.com/assets/20497554/16898735/d264fa5a-4c03-11e6-99ca-50c2de601536.jpg)

**Comment by rohitwaghchaure** [comment]
@StalinNR 
This issue has fixed now, please check
Note: If user has set the warehouse in POS profile then he can only search the serial no which is available in the respective warehouse

**Comment by StalinNR** [comment]
@rohitwaghchaure thanks for the quick fix. I will  also watch out for the POS profile.
