### ISSUE TITLE
 [V7] Issue on child tables not fetching field values correctly on link change and on “Depends On” ERPNext

### ISSUE THREAD

**Issue by it2sme** [frappe/erpnext#5781]
Raising an issue from the following link at discuss. when retrieving item in child table the details aren't fetched.

https://discuss.erpnext.com/t/v7-issue-on-child-tables-not-fetching-field-values-correctly-on-link-change-and-on-depends-on/14188

Thank you.

**Comment by rmehta** [comment]
Thanks fixed.
