### ISSUE TITLE
[v7]- ERPNext Release 7 Sale of Asset functionality account set up

### ISSUE THREAD

**Issue by PawanMeh** [frappe/erpnext#5784]
When clicking on "Sale Asset" I get the below message

"Please set 'Gain/Loss Account on Asset Disposal' in Company Wind Power LLC"

However while visiting the company information, I do not see a place holder to set this account. Also, it appears as display only. Maybe a default account should be included in demo data or if it is to be set up some place other to test further , let me know
![sale_of_asset_account](https://cloud.githubusercontent.com/assets/20460498/16910346/cf338a84-4cf5-11e6-9df8-c57d4c4382ef.jpg)

**Comment by nabinhait** [comment]
fixed
