### ISSUE TITLE
[V7] Timesheet - Not able to create Time Sheet without Employee

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#5786]
I was creating Time Sheet after demo session. In the Timesheet details, not able to select Activity Type without Employee. We should be able to select Activity Type without Employee as well.

![timesheet1](https://cloud.githubusercontent.com/assets/910238/16914541/21021578-4d10-11e6-80dd-b111edaa1911.gif)

**Comment by rohitwaghchaure** [comment]
@umairsy 
Have fixed it please check.

**Comment by umairsy** [comment]
Fixed.
