### ISSUE TITLE
[V7] Timesheet - Calculating To Time based on From Time and Hours

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#5787]
In the Time Log, after entering From Time, and Hours, To Time was auto-calculated. This feature is missing in the Timesheet.

Also Title field is missing in the Timesheet.

**Comment by partzsch** [comment]
also if to time is not editable in quick entry as soon as from time and hours are set - 
if you move the to time hour bar, the from time moves as well

**Comment by rohitwaghchaure** [comment]
@umairsy @partzsch 
This is fixed please check
