### ISSUE TITLE
ERPNext Dashboard

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#5792]

**Comment by umairsy** [comment]
Do not replace but create a new Page/Doctype where graphical presentation will be show.

- [ ] Sales pipeline
- [ ] Actual monthwise sales
- [ ] Actual monthwise purchases
- [ ] Account Receivable
- [ ] Accounts Payable
- [ ] Balance Sheet
- [ ] P&L
- [ ] Manufacturing jobs in calendar / scattered view
- [ ] Leave dashboard

**Comment by umairsy** [comment]
Option to generate graph based on different value in the same field. It will help in generating a pipeline and other sort of analysis. In the example below, Hot, Warm and Cold are the option in the same select field called "Probability". We could also show presentation in the pie view.

<img width="1171" alt="screen shot 2018-08-24 at 2 38 08 pm" src="https://user-images.githubusercontent.com/910238/44576415-20204780-a7ac-11e8-8357-4c421fb5921a.png">
