### ISSUE TITLE
PayPal Integration Issue, when "Pay" Button is clicked, JSON output appears [ERPNext 7]

### ISSUE THREAD

**Issue by Nathaniel401** [frappe/erpnext#5797]
I did some research on the forums and this was an issue in the past, but it was resolved by using the Payment Gateway name was Pay**P**al vs. Paypal . This is now fixed, however I am experiencing the same issues:

Essentially, once the Pay button is clicked to process a payment, the following JSON output appears (note, I blocked out the URL's with XXXX's)

`{"message":{"payment_url":"https://my.xxxxxxxxx.com/api/method/erpnext.accounts.doctype.payment_request.payment_request.generate_payment_request?name=PR000001","creation":"2016-07-18 17:39:16.260568","doctype":"Payment Request","currency":"CAD","owner":"email@xxxxxxx.com","message":"Please click on the link below to make your payment","subject":"Payment Request for SINV-08800001","reference_doctype":"Sales Invoice","modified_by":"email@xxxxxxxx.com","docstatus":1,"status":"Draft","reference_name":"SINV-08800001","mute_email":0,"email_to":"","payment_gateway_account":"PayPal - CAD","payment_account":"PayPal - LG","grand_total":45.2,"name":"PR000001","idx":0,"modified":"2016-07-18 17:39:16.281243","make_sales_invoice":0,"payment_gateway":"PayPal"}}`

**Comment by saurabh6790** [comment]
@Nathaniel401 Sorry but can't reproduce the issue. Can you try it by pulling latest update for PayPal application ? If error still persists, please share steps to reproduce.
