### ISSUE TITLE
Payroll Management system

### ISSUE THREAD

**Issue by fikrut** [frappe/erpnext#5802]
i need the following funcionalities on payroll management system
1, income tax calculation based on formula not percentage or manaually like
if the government rule is for gross salary 0-750 tax is zero
for gross salary from 751-1500 tax will be Gross salary*5%-250
for gross salary from 1501-3000 tax will be Gross salary*10%-450
for gross salary from 3001-4500 tax will be Gross salary*15%-500
for gross salary from 4501-6000 tax will be Gross salary*20%-750
for gross salary from >6000 tax will be Gross salary*25%-900...it means your gross salry will be claculated by selection at which range are you,like that the system must allow to insert the formula manually
2, overtime calculation based on time range like for oT for normal hours your hourly salary *1
for overnight your hourly salary *1.5
for weekend ot your hourly salary *2
for holiday your hourly salary *2.5 so the OT must work like that
3, every type of earnings and deductions musthave their respective account and must be seen on payroll reports on total like total deduction or total earning or total ttransport earning(if transport is earning type)
4, in our country employees might take loan that will be cutted from their salary so there must be a sytem that will be linked to the deduction automaticall then as soon as they finish paying back their loan the system must automatically stop cutting from their salary.
thanks i need this as a paid development so please inform me how much it will cost me and how many days it will take.
thanks

**Comment by rmehta** [comment]
@fikrut please post this on https://community.erpnext.com/jobs
