### ISSUE TITLE
Feature request ability to make entering a serial number for an item optional.

### ISSUE THREAD

**Issue by jasonbrowne** [frappe/erpnext#5809]
**Problem:** In the item master the serial number values field is frozen for each of our servers, as we initially chose not to serialize them. In order to un freeze this item have to delete all the stock transactions for an item.

**Solution: Key** searches off of something other then serial number so that if an item started out with out serial numbers we can have a serial number assigned to it at a later date.

**Example:** We have build a single server modle xx7y we give it a serial number. If we build 100 servers for a client we wait until we have all 100 servers to issue the serial numbers so that they are sequential.
We would like to be able to add the serial numbers at a later date or not at all.

https://frappe.github.io/erpnext/user/manual/en/stock/articles/maintain-stock-field-frozen-in-item-master.html

For an item, once stock ledger entry is created, values in these fields will be froze. This is to prevent user from changing value which can lead to mis-match of actual stock, and stock level in the system of an item.

For the serialized item, since its stock level is calculated based on count of available Serial Nos., setting Item as non-serialized mid-way will break the sync, and item's stock level shown in the report will not be accurate, hence Has Serial No. field is froze.

To make these fields editable once again, you should delete all the stock transactions made for this item. For the Serialized and Batch Item, you should also delete Serial No. and Batch No. record for this item.

**Comment by ankush** [comment]
Duplicate: https://github.com/frappe/erpnext/issues/28086
