### ISSUE TITLE
[V7] Customer Addresses and Contacts report at beta.erpnext.com doesn't load

### ISSUE THREAD

**Issue by strixaluco** [frappe/erpnext#5814]
After opening [Customer Addresses and Contacts report](https://beta.erpnext.com/desk#query-report/Customer%20Addresses%20and%20Contacts) at beta.erpnext.com the screen gets bleached and nothing loads.

Firefox ESR 45.2.0

Console output:
```
GET XHR https://beta.erpnext.com/ [HTTP/1.1 200 OK 746ms]
TypeError: me.report_doc is undefined
frappe.views.QueryReport<.load/<() report.min.js:66
.with_doc/<.callback() desk.min.js:525
frappe.call/callback() desk.min.js:121
frappe.request.call/statusCode[200]() desk.min.js:123
frappe.request.call/<() desk.min.js:128
n.Callbacks/i() jquery.min.js:2
n.Callbacks/j.fireWith() jquery.min.js:2
z() jquery.min.js:4
.send/c/<() jquery.min.js:4
 report.min.js:66:478
GET XHR https://beta.erpnext.com/socket.io/ [HTTP/1.1 502 Bad Gateway 261ms]
GET XHR https://beta.erpnext.com/socket.io/ [HTTP/1.1 502 Bad Gateway 262ms]
GET XHR https://beta.erpnext.com/socket.io/ [HTTP/1.1 502 Bad Gateway 735ms]
```

**Comment by nabinhait** [comment]
Can't replicate. It is loading properly, but taking some time as beta.erpnext.com is little slow.

**Comment by strixaluco** [comment]
Curious. At first I thought it might be some Great Firewall of China-related issue, but the problem persists if I access the beta site via VPN too. And with Chrome 52.0.2743.82 the experience is the same.
