### ISSUE TITLE
Delete Company Transactions Button

### ISSUE THREAD

**Issue by justinlusg** [frappe/erpnext#5825]
![image](https://cloud.githubusercontent.com/assets/12539216/17033276/f9faa75e-4faf-11e6-9ddc-bf43361f1b89.png)

I just used this button, and it seems that the button not only deletes the records but it also cleared all the addrseses. Can please check that the button is not removing other import data other than transaction records?

**Comment by PawanMeh** [comment]
Please check the [link](https://frappe.github.io/erpnext/user/manual/en/setting-up/articles/delete-a-company-and-all-related-transactions) for further information.
