### ISSUE TITLE
Salary Slip Based on Timesheet Issues

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#5837]
1. There should be a way to indicate in the Time Sheet Details if an employee should be paid for a task just like we can indicate if it is billable
2. In the salary slip, the Salary Component (Earning) does not get updated when a Time Sheet row is removed or when the Total Working Hours/Hour Rate is changed (even after Saving changes!)
3. There's currently no way to differentiate between Earning and Deduction components. This means the same component can be selected both as an Earning and a Deduction!

Please help look into these

Thanks!

**Comment by rmehta** [comment]
@Olawale1 #2, #3 are not an issue

Yes we can add a check on Timesheet if this is linked to salary

**Comment by Olawale1** [comment]
@rmehta why do you say so? Should the Salary Slip form get updated when you change the values? For example, I'm creating the Salary Slip for an employee and notice there's a row in the timesheet section that shouldn't be there. I removed the row but the Total Working Hours section of the form remains the same and so does the related Salary Component! Even when I manually change the Total Working Hours field, the Salary Component still doesn't change. This is surely not how it is intended to function? This will lead to inconsistent information in the Salary Slip form

Also, shouldn't there be a distinction between Earnings and Deductions as it has been in previous versions? I think it is even more needed in V7 with the functionality of auto calculating Salary Components from Timesheets; things can get confusing very fast. By the way, is there any use case for having the exact same component as an Earning and a Deduction simultaneously?

Thanks

**Comment by KanchanChauhan** [comment]
Billable option added to the Timesheet Detail.
Earning and Deduction type added to the Salary Component.
