### ISSUE TITLE
[SOLVED] Difference account not being updated

### ISSUE THREAD

**Issue by nununo** [frappe/erpnext#5843]
Hello,

1. I have a BOM which has an operation costing 6.50€/h.
2. I manufacture an item.
3. I choose the option "manufacture" to move the manufactured item to the "Finished Goods" material
4. The "manufacture" Stock Entry clearly shows those 6.50€ as a difference and displays the difference account "Mão de Obra -TS".
5. But when I look at the Chart Of Accounts the amount isn't reflected there. Should it show there?

This is what I see in the Stock Entry:
<img width="345" alt="06d3be2665408f2383471f3bac746e93ea4a43e0_1_690x455" src="https://cloud.githubusercontent.com/assets/532049/17069961/6791d4ee-5051-11e6-9648-2efb20bc8829.png">

And this is what I see in the Chart Of Accounts after submitting the Stock Entry:
<img width="345" alt="3eff2af64d69eb3c0c6870ebb0c22daea1e995af_1_690x207" src="https://cloud.githubusercontent.com/assets/532049/17069970/7201f1ca-5051-11e6-90be-9de63037329d.png">

Besides, looking at the General Ledger I don't see any entry related to this. And it should be there, right?

Something seems to not be working correctly.

Regards,
Nuno

**Comment by nununo** [comment]
Besides, looking at the General Ledger I don't see any entry related to this. And it should be there, right?

Something seems to be wrong, no?

Thanks,
Nuno

**Comment by nabinhait** [comment]
The difference account in parent form is used just to set the difference account in the child item table. Please check if it is different from parent difference account.

**Comment by nununo** [comment]
This seems to be solved somehow in my new instance. So I think I can make it as solved. Thanks!

**Comment by nununo** [comment]
Ah... this is github so I can actually close it :) Closing...
