### ISSUE TITLE
Default warehouse

### ISSUE THREAD

**Issue by raghav4593** [frappe/erpnext#5848]
Dear all,
 
We are into a typical manufacturing company. Having a suppliers more than 300, and very few of them regular.
Now I want to make the default warehouse for some particular supplier.
To make that I have created an customized field for supplier i.e., default warehouse for supplier.
But whenever I make a purchase receipt for that particular supplier the item was going into the item warehouse but not into the supplier warehouse.
Can anybody please suggest me to how to overcome with this situation

**Comment by yashodhank** [comment]
You should ask such questions on discuss.erpnext.com

This place is strictly for submitting issues / bugs with ERPNext.
