### ISSUE TITLE
[v7] Desktop Icon not showing for users 

### ISSUE THREAD

**Issue by jetplane99** [frappe/erpnext#5850]
Hi there, just would like to say that Erpnext is by far one of the best erp out there!

I seem to notice this strange bug in a fresh install of production version of v7 on ubuntu 1404.

The domain is Manufacturing.

The desktop icons is not showing for all other users except for system admin account. I have already enabled all desktop icons for all users (Setup>Show/Hide Desktop Icons), however, only these following icons seem to appear and checkable:

Item
BOM
Customer
Supplier
Sales Order
Production Order
Stock Entry
Purchase Order
Task
Buying
Selling
Accounts
Human Resources
ToDo

**Comment by Braintelligence** [comment]
I have the same problem.

**Comment by rmehta** [comment]
Click on your user id, select "set desktop icons", then "select for everyone" and then check the icons you want everyone to see.

**Comment by Braintelligence** [comment]
![image](https://cloud.githubusercontent.com/assets/6761196/17085051/bf850c42-51ce-11e6-8576-eb884be90c39.png)

![image](https://cloud.githubusercontent.com/assets/6761196/17085053/ca1b8e9c-51ce-11e6-9d17-2266739881a2.png)

![image](https://cloud.githubusercontent.com/assets/6761196/17085054/d486982c-51ce-11e6-8431-90a7d5ebcbdc.png)

If this would work, we wouldn't write about it here. Or did you mean another setting?

**Comment by Braintelligence** [comment]
Now, if you go to the setting for every user a lot of checkboxes are not checked.

After checking them I can see a lot more modules.

I guess this is fixed then.

**Comment by jetplane99** [comment]
Its definitely a BUG. 

Only the following will appear even though all the boxes are checked for all users.

Item
BOM
Customer
Supplier
Sales Order
Production Order
Stock Entry
Purchase Order
Task
Buying
Selling
Accounts
Human Resources
ToDo

However, when i unchecked all the boxes for the above selection and save, ERPNEXT will suddenly show all other options that were previously hidden.
