### ISSUE TITLE
[V7] Fresh install "subscription expired" on login

### ISSUE THREAD

**Issue by Braintelligence** [frappe/erpnext#5851]
After a fresh install of V7 on a fresh Ubuntu 16.04 I installed Bench and ERPnext on a site of mine.

I activated DNS multitenant and had problems getting the site to run; then I found out that supervisor didn't run on startup, so `systemctl enable supervisor` helped.

Now, after initializing ERPnext with the first user I alway get this when logging in:

![image](https://cloud.githubusercontent.com/assets/6761196/17084357/b1fbce52-51bb-11e6-8235-2e4a2dbc7814.png)

I don't know anything about a subscription.
If I reload the page I am logged in and can switch to desk but this is really irritating.

**Comment by vjFaLk** [comment]
That's odd. Can you check the contents of site_config.json inside the site's folder and paste them here?

**Comment by Braintelligence** [comment]
![image](https://cloud.githubusercontent.com/assets/6761196/17084514/df691cce-51bf-11e6-8756-66ee3707ded0.png)

Below are two more lines containing the SSL cert paths from the letsencrypt installation.

I guess the "expiry" part is the one making problems.

But how did it get there?

I really only did the most necessary steps to install a single ERPnext site with letsencrypt enabled on Ubuntu 16.

**Comment by vjFaLk** [comment]
That's quite odd, Yea, just remove the entire line from there, and that should fix it. 
Reinstall won't change the DB password. You'll have to drop-site and then create another.

**Comment by Braintelligence** [comment]
Ok, thanks.

**Comment by rmehta** [comment]
@vjFaLk can you get to the root of this? This must be set somewhere and other users will face this too.
