### ISSUE TITLE
How to customize or update translation

### ISSUE THREAD

**Issue by Braintelligence** [frappe/erpnext#5856]
I was promised that with version 7 the current translation strings from the translate-portal would be merged to ERPnext.

The translation improved, thank you a lot for this :+1: .

But there are still a lot of untranslated strings, to a point where I can't use this software in a serious production environment.

I want to translate every relevant string but I don't know the most efficient way to do this.

If I just use https://translate.erpnext.com/ the translation won't be immediately useable (from what I understand). Even though the help-text says it would be updated in 2-3 weeks this didn't happen with ERPnext 6 at all (more like months). So what could I do to translate on-demand?

EDIT: Oh, and also the translation portal doesn't seem to work. (I get a 404 when choosing a language.)

**Comment by rmehta** [comment]
translations fixed. will now be updated for each minor release (maybe once in 2 weeks) can't think of a better realtime system

**Comment by Braintelligence** [comment]
I will work on the current translations then.
Can you please elaborate on the fastest way to reach 100 Karma so I can edit verified translations?

For example "POS" was translated to "Verkaufsstelle" but there are a lot of verified strings where "POS" is being used as-is. I can't edit those strings yet.

Also I found a lot of strings that have no translatable string in translate.erpnext.com. I will collect them and write a new issue.

**Comment by rmehta** [comment]
send me your email id and I can get your karma up (PM me on discuss)
