### ISSUE TITLE
Non-translateable strings

### ISSUE THREAD

**Issue by Braintelligence** [frappe/erpnext#5860]
Hi,

I will gather strings that I couldn't translate in translate.erpnext.com in here.

After a fix I will try to remove them from this post and only keep the not fixed strings here.

Strings I have found:

- ![pos1](https://cloud.githubusercontent.com/assets/6761196/17098171/4f5c1530-5261-11e6-97fd-914c49ed13a4.PNG)
(Can't find a string for this in translate.erpnext.com)

- ![desktop1](https://cloud.githubusercontent.com/assets/6761196/17098177/58ff5002-5261-11e6-8f7c-aa0282657e64.PNG)
(There is a string for this in translate.erpnext.com and it is correctly translated. If you click on this icon the title of the DocType is correct but the icon has an untranslated string.)

- ![image](https://cloud.githubusercontent.com/assets/6761196/17570777/1ad0d720-5f4e-11e6-8298-8ac3ec47d9ce.png)
(The "like" in the filter tag.)

- ![image](https://cloud.githubusercontent.com/assets/6761196/17571051/0627ca30-5f4f-11e6-9c7e-bec48f6ed556.png)
If you add a customer it says "Phone:" in his address overview, also in invoices, even though "Phone" is translated in translate.erpnext.com

- ![image](https://cloud.githubusercontent.com/assets/6761196/17571239/b430fcaa-5f4f-11e6-9675-d99bd2b2c331.png) (In Timesheets this string is existing but has no translateable equivalent.)

- ![image](https://cloud.githubusercontent.com/assets/6761196/17653023/2fe95640-628d-11e6-995b-31675b6cf9c3.png)
In outgoing invoices you see the sum to be paid "in words". First of all I don't understand why the English word "only" is necessary in there, at all. In German translating "only" to "nur" makes no sense at all at that point. It should only say "NUMBER_IN_WORDS EUR" and nothing else. I know you can remove this whole point but maybe someone wants to use this function. Right now it is unusable.

- ![image](https://cloud.githubusercontent.com/assets/6761196/17653253/ab751aec-6292-11e6-8ce1-9c7b0b1c4588.png)
Using "@" here makes no sense. It should be "TAX_NAME X%"

**Comment by mhbu50** [comment]
+1

**Comment by Braintelligence** [comment]
From what I gather none of these were added to translate.erpnext.com yet. Is that correct?

**Comment by rmehta** [comment]
Its in the 7.1 milestone so please be patient.

These should be relatively easy fixes, maybe you can consider sending a patch?

**Comment by Braintelligence** [comment]
Sorry but I don't have enough understanding of your system to be patching this myself.
