### ISSUE TITLE
PREC Problem - Subcontracting after bench upgrade.

### ISSUE THREAD

**Issue by epochc** [frappe/erpnext#5863]
Moved to version 7 for a client. Getting this problem when submitting Purchase Receipt for a Sub Contract Purchase Receipt:

Debit and Credit not equal for Purchase Receipt #PREC-02285. Difference is 8591.96.

Any ideas how to overcome this problem? 

The amount coming up in the error message is the exact amount related to the valuation of stocks.

This environment has Pass Accounting Entry for every Stock Movement checked, Moving Average for Stock Valuation and already has in the Vendors warehouse Raw Materials at a particular valuation.

This case has a difference between the outgoing (Stock Entry Subcontract) value, the stock balance valuation and the Incoming value (PREC).

Anything else you need?

Not sure if this is relevant but One PREC where the outgoing value, the stock balance valuation and the incoming value were all the same and went through without any problems.

This PREC seems to be stuck.

**Comment by rohitwaghchaure** [comment]
Hi @epochc ,
Can you share your screen

**Comment by epochc** [comment]
Do you just need a System Admin access or do you need access to the server?

Thanks

Jay

**Comment by rohitwaghchaure** [comment]
I want access of your system, can you share me your screen using skype or teamviewer

Thanks

**Comment by rohitwaghchaure** [comment]
Have fixed this issue, we'll release it soon
