### ISSUE TITLE
[v7] Unable to generate web page

### ISSUE THREAD

**Issue by jaslyn94** [frappe/erpnext#5867]
Previously I was able to build a custom webpage on erp6. However when I attempt to create the page, i encounter this error which seems to be derived by issues in routing the web page properly.

I have posted this is the forum here: https://discuss.erpnext.com/t/web-generator-for-erpnext7/14345/3

Thanks.

**Comment by rmehta** [comment]
replied via forum

**Comment by jaslyn94** [comment]
Hi, I have follow up on the forum on this issue that I met in ver 7 but able to do so in ver 6.

https://discuss.erpnext.com/t/web-generator-for-erpnext7/14345/4

Thanks!
