### ISSUE TITLE
Reference Number on Export Document

### ISSUE THREAD

**Issue by neuralaccounts** [frappe/erpnext#5869]
Hello,
1. We require one column reflecting reference number (i.e bill number) as quoted when we export any      particular general ledger this feature is available in case of purchase & sale transactions.
2. In Customer & Vendor Registration procedure we require one additional column to quote the CIN number of company.

**Comment by kennethsequeira** [comment]
@neuralaccounts this can now be easily accommodated by:

1. Adding custom field

2. Adding the column in any report via **Add Column** option
