### ISSUE TITLE
BOM Cancel button remains hidden

### ISSUE THREAD

**Issue by arpanzen** [frappe/erpnext#5871]
When we press the Cancel button to cancel a BOM record the cancel button hides and the record gets cancelled. But when we have to cancel another BOM the cancel button remains hidden until we clear cache. After clearing cache the button is again displayed.

**Comment by PawanMeh** [comment]
Unable to replicate this,please provide step by step screen shots if you are still having the issue

**Comment by hiousi** [comment]
Same here. Same steps as described above  to reproduce:
- open a BOM click cancel. Menu delete or duplicate or... do what you want
- open another BOM. Cancel is invisible

Hit F5 to make it reappear. or reload. 

-

**Comment by strixaluco** [comment]
Can't replicate on ERPNext: v8.x.x-beta (226ea7d) (develop) / Frappe Framework: v8.x.x-beta (eb079e1) (develop)
