### ISSUE TITLE
Base Document Line

### ISSUE THREAD

**Issue by David-at-GitHub** [frappe/erpnext#5873]
Dear all,

in the JSON formatted RESTful call, the base-document number (from which the document was converted/copied from) is mentioned. For example in the Delivery Note this would be the 'against_sales_order' field. This is good, but in case the same Item exists in more than one line, or in case there are multiple Sales Orders converted to the same Delivery, it would be important also to have the 
Base Document Line ID (e.g. against_sales_order_idx), as the Item Code is not unique. It would be great if this could be added to the next level Document Form and RESTful JSON file:

![image](https://cloud.githubusercontent.com/assets/15001320/17136246/40229fac-5302-11e6-8aa0-c21f1ee32655.png)

Thanks, David

**Comment by David-at-GitHub** [comment]
Any updates if/when this could be implemented?

Thanks, David

**Comment by PawanMeh** [comment]
@nabinhait any inputs on this?

**Comment by nabinhait** [comment]
The field for Base Document Line Id is already there in Delivery Note Item table, it is called "so_detail". Are you looking for this?

**Comment by David-at-GitHub** [comment]
Hi Nabin,

just checked, this looks great. Thanks a lot for the update. Could you tell
me in which Version/Patch this has been implemented?

Thanks, David

**Comment by nabinhait** [comment]
I think the field is there right from the beginning.

**Comment by David-at-GitHub** [comment]
Thank you. Strange I never noticed that before, but this should help me now
to identify and convert the exact document lines.

David
