### ISSUE TITLE
ERPNext Payroll Issues (Deductions Accounting)

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#5887]
Better handling of Deductions so that relevant account heads can be specified for each Deduction and Journals raised accordingly to book these entries

**Comment by mhbu50** [comment]
+1

**Comment by nabinsachine** [comment]
+1

**Comment by KanchanChauhan** [comment]
Work in progress. Duplicate of https://github.com/frappe/erpnext/issues/5921
