### ISSUE TITLE
ERPNext Payroll Issues (Earnings Calculation)

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#5889]
Earnings in Salary Structure should have the option of being calculated as a percentage of specified Gross Salary. Most times organizations already have the gross salary fixed and a template based on which the earnings are calculated e.g. Basic Salary (50%), Housing Allowance (30%), Wardrobe (10%), Transport (10%). There are sometimes different templates used for different categories of employees especially in larger organizations

Other variable earnings like Overtime and Reimbursements can then be auto calculated from external inputs like Timesheets and Expense Claims

Thanks

**Comment by fikrut** [comment]
if this helps you in your development of this module let me post what our country experience looks like especially for over time calculation
there are 4 type of OT calculate
1, **Normal time OT** will be calculated **(Basic Salary*1.25*no of OT hour**) divided by **208(no of days you work*hours you work per day or 26 days * 8 Hours per day**)
2, **overnight time OT** will be calculated **(Basic Salary*1.5*no of OT hour**) divided by **208(no of days you work*hours you work per day or 26 days * 8 Hours per day**)
3, **weekend time OT** will be calculated **(Basic Salary*2*no of OT hour**) divided by **208(no of days you work*hours you work per day or 26 days * 8 Hours per day**)
4, **Holiday time OT** will be calculated **(Basic Salary*2.5*no of OT hour**) divided by **208(no of days you work*hours you work per day or 26 days * 8 Hours per day**)
also all earning types must be connected with there accounts on chart of accounts.thanks

**Comment by nabinsachine** [comment]
this is the feature which i was expecting for a long time and that will take erpnext to the next level...as **fikrut** express different countries tax rule is different so try to make the formula flexible and don't forget to add the deduction part after the percentages(it will balance the deduction)..and finally even if its to early to ask when shall we expect this to happen?thanks.

**Comment by nabinsachine** [comment]
This is also a feature which makes erpnext earning system powerful and keep working hard to make it happen...  also take into consideration some static no earnings can be available...so when shall we expect this feature?thanks in advance

**Comment by mhbu50** [comment]
+1
