### ISSUE TITLE
ERPNext Payroll Issues (Deductions Calculation)

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#5891]
Deductions in Salary Structure should have the option of being calculated as a percentage of specified Earning Types. This should be one-to-many i.e. Salary Tax Deduction could be say 15% of Basic + Housing + Transport Earnings

**Comment by fikrut** [comment]
Salary Range (ETB)              Tax Rate           Deduction (ETB) 
1.  0 - 600 Birr                  Non-Taxable        - 
2.  601-1,650 Birr            10%                       60 Birr 
3.  1,651 - 3,200 Birr        15%                     142.50 Birr 
4.  3,201 - 5,250 Birr        20%                       302.50 Birr 
5.  5,251 - 7,800 Birr        25%                        565 Birr 
6.  7,801 - 10,900 Birr      30%                        955 Birr 
7.  Over 10,900 Birr         35%                        1,500 Birr 
so in our country income tax calculation is **(Salary Range*Tax rate)-deduction** like this assume your salary is 5000 then the calculation will be the range will fall in no 4 so (5000*20%)-302.5=697.5 so the income tax is calculated so when you develop this module take this in to consideration.thanks

**Comment by fikrut** [comment]
also take in to consideration other type of deductions are also available they will be calculated based on percentage like
Pension scheme is there in our country has a percentage like from employee basic salary*7%, and from company (employer) basic salary*11%
provident fund is from employee basic salary*11% so another type of deduction might be available in different countries so make it to add different types by selecting the formula.
thanks

**Comment by fikrut** [comment]
this is a good idea which i was expecting for a long time,take in to consideration that the tax rule differs from country to country so make it flexible and it must work on formula not on percentage becayse in many countries after the percentage there is a static number which will be deducted to make it balanced as Fikrut expresses...so when can we expect this to happen?

**Comment by nabinsachine** [comment]
this is the feature which i was expecting for a long time and that will take erpnext to the next level...as **fikrut** express different countries tax rule is different so try to make the formula flexible and don't forget to add the deduction part after the percentages(it will balance the deduction)..and finally even if its to early to ask when shall we expect this to happen?thanks

**Comment by mhbu50** [comment]
+1

**Comment by fikrut** [comment]
@KanchanChauhan have you started it?
thanks

**Comment by rmehta** [comment]
@fikrut please don't add reminders. Your feature will come when it comes. Please have patience!

**Comment by aakvatech** [comment]
Not sure if this was addressed, but we are working out a way to including the employer based deduction without including it in the total and creating accounting entries related to it automatically.
