### ISSUE TITLE
ERPNext Payroll Issues (Attendance Linking)

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#5893]
Linking Attendance to Payroll. Option to automatically calculate Absent Days and Half Days in Attendance as Full Pay, Half Pay, or No Pay. The whole point of taking attendance in many organizations is so that it can be linked to payroll!

**Comment by mhbu50** [comment]
+1

**Comment by KanchanChauhan** [comment]
@Olawale1 we do link "Leave Without Pay" type of leaves to Payment Days in Salary Slip.

**Comment by aambernath** [comment]
+1 , I think this should be added without the need for Leave Application

**Comment by dawoodjee** [comment]
@mhbu50 @aambernath please use the **thumbs up** emoji on the issue to increase its importance.

Thanks

**Comment by jrubinos** [comment]
i also do think that attendance could be linked to the salary slip. The real purpose of marking the employee present, absent, half day etc is so that you can pay them properly. The attendance module will be useless if the employee is marked absent or half-day. And yet they still received a full pay for the period. 
Not sure on how It can be done. but probably we can have the attendance reflect at the payment_days field?

**Comment by dawoodjee** [comment]
Precisely so I think Joeven

**Comment by amitsaxena01** [comment]
If a person is absent, then it should automatically become leave without pay until and unless they have applied for a leave which gets paid. Adding a leave without pay is an unnecessary step which increased the burden of the payroll team to ensure that a leave without pay has been set up and approved. Further what is the incentive for the employee to put the leave without pay in the system when they know if they wont put it in, they get paid for that day?

**Comment by Olawale1** [comment]
Hi @KanchanChauhan 

Trust you're doing well. Could this be re-opened seeing as it is not resolved? The above suggestion by @amitsaxena01 might be a good way to resolve this for now. There also needs to be a setting where we can switch this on or off

Thanks

**Comment by clarkejj** [comment]
@amitsaxena01 comments can be found here https://discuss.erpnext.com/t/absence-and-salary/38208

**Comment by ashish-greycube** [comment]
We are working on it

**Comment by JoyceBabu** [comment]
What is the current status of this request? I can see that @ashish-greycube's PR was closed without merging.

**Comment by kennethsequeira** [comment]
@JoyceBabu the PR was closed as there were no test cases written for it:  https://github.com/frappe/erpnext/pull/15823#pullrequestreview-171450908
