### ISSUE TITLE
Using ERPNext at a Repair Centre

### ISSUE THREAD

**Issue by pate** [frappe/erpnext#5897]
Is there any plan for supporting a repair business? Or is this something that is handled by a Workflow?

**Comment by PawanMeh** [comment]
Currently there is no separate domain for repair business, however the current manufacturing domain in ERPNext has adequate functionality to support a repair business by way of creation of multiple items and tracking them serially.

If there are any specific scenarios you want to try out, you could sign on to our free version and try it and let us know your feedback
