### ISSUE TITLE
7.4-Addition of context specific help for transactions

### ISSUE THREAD

**Issue by PawanMeh** [frappe/erpnext#5899]
Add "Help" or ? icon for context specific help, for eg: If a user is creating an item, he needs to see a ? or help icon somewhere on the screen and when he clicks that he should be shown help videos, information related to that particular transaction

**Comment by PawanMeh** [comment]
![screen shot 2016-07-28 at 12 26 25 pm](https://cloud.githubusercontent.com/assets/20460498/17203736/b9a4a632-54be-11e6-9ad0-0026c6292054.png)

For eg: when customer master(customer entry) screen opens we can show customer related help documents

**Comment by netchampfaris** [comment]
@PawanMeh this can be closed now
