### ISSUE TITLE
Deferred Transactions in Accounting

### ISSUE THREAD

**Issue by PawanMeh** [frappe/erpnext#5904]
Enhance revenue recognition functionality to add deferred revenue recognition.

FASB Standard for deferred revenue: http://www.fasb.org/jsp/FASB/Document_C/DocumentPage?cid=1176164076069&acceptedDisclaimer=true

**Comment by PawanMeh** [comment]
In order to improve compliance of accounting revenue recognition with FASB, the below solution can be explored:

1) Add a "check box" at "item" we sell to give the user an option to enable deferred revenue for the product & enter the no.of months over which revenue would be deferred. This would default to the invoice & can be changed if needed.
2) When the invoice entry is created,invoice date:01-aug-2016 , Service Start Date:01-Aug-2016,Service End Date:01-Feb-2017, product: YEARLY-CLOUD-SERVICE, Amount: 2500, revenue entries would be like below:
		      
![screen shot 2016-08-01 at 3 06 43 pm](https://cloud.githubusercontent.com/assets/20460498/17289967/a9a508b0-57f9-11e6-9750-7a16f99c44be.png)

**Comment by PawanMeh** [comment]
To move towards FASB standards for revenue recognition,below solution can be thought of:
![1-item](https://cloud.githubusercontent.com/assets/20460498/17293012/4c18c562-580b-11e6-969b-ebe163688607.png)
![2-accouting details](https://cloud.githubusercontent.com/assets/20460498/17293014/4c59cf12-580b-11e6-9aa0-d67ca11d7b77.png)
![3-revenue calculations example](https://cloud.githubusercontent.com/assets/20460498/17293013/4c551c42-580b-11e6-94a1-73848990f370.png)

**Comment by magic-overflow** [comment]
How's it going?

**Comment by SoriyaKH** [comment]
Hi how is deferred revenue functionality going? I don't see it in 7.2. 
It is important that we defer revenue for unbilled income (we already complete performing services, but not yet bill our fee) and unearned revenue (we already billed our fee, but we have not complete our service yet) according to revenue recognition of IFRS.

**Comment by Olawale1** [comment]
+1

This would be a very helpful functionality

**Comment by manassolanki** [comment]
- [ ] Enable deferred revenue in the item master
- [ ] Details in the Sales Invoice for booking the income
- [ ] Scheduler for booking the income from the deferred account to the income account
- [ ] Deferred Account in the Chart of Accounts
