### ISSUE TITLE
Training Module

### ISSUE THREAD

**Issue by neilLasrado** [frappe/erpnext#5916]
- [x] Training Event
- [x] Training Feedback

**Comment by PawanMeh** [comment]
Some thoughts for the design:

1) *Participant Name: These can be employees of the school or students(Can be prompted from Employee master or student master)
2) *Department:Departments of the school(Admin,maths,science etc)/college/organization(Can be prompted from Dept ID)
3) *Course: Programming in python
4) Location: Room in campus / school/organization or external location of training
4) *Start Date:29/7/2016
5) *End Date:30/7/2016
6) *Hours:16
7) Vendor: Fossify(List of Vendors in ERPNext)--
8) *Trainer name: Sayali(Trainer master can be maintained seperately along with email ID of trainer)
9) *trainer email id:
10) *Type:Seminar/Theory/Workshop/Exam/Conference/Internet(Can be a list of values)
11) Results:Passed/Failed/Not Assessed/Competent/Not Competent(Can be a list of values)-Can be secured fields , controlled by field level permissions to be edited by training administrator 
12) Training Status:Completed/Cancelled/Ongoing/Withdrawn/Deferred(Can be a list of values)-Can be secured fields , controlled by field level permissions to be edited by training administrator
13) Feedback:This field can be used to provide Participant feedback

* implies required fields

Other nice to have features, once the training event is created and participants are assigned system should notify them via email 

Reports:

1) Hours spent by participant on training

Stretch goal for development:
1) Training cost (This can be got based on the Invoices paid for the Vendor)

**Comment by PawanMeh** [comment]
![1-training event](https://cloud.githubusercontent.com/assets/20460498/17245183/f35b986a-55a2-11e6-95b6-45aff17b316e.png)
![2-training enrollment](https://cloud.githubusercontent.com/assets/20460498/17245184/f3b52bc8-55a2-11e6-8da7-ad00813f4c05.png)
![3-training feedback](https://cloud.githubusercontent.com/assets/20460498/17245186/f3b723e2-55a2-11e6-96cc-b7ff3cb69b2e.png)
![4-participant feedback](https://cloud.githubusercontent.com/assets/20460498/17245185/f3b57574-55a2-11e6-9c1b-0f3225451bd7.png)

**Comment by mhbu50** [comment]
+1

**Comment by PawanMeh** [comment]
- [ ] Combine training event and training enrollment screens into one during development

- [ ] List of values for 'Training Status'
        -Scheduled
        -Invited
        -Attended
        -Completed
        -Withdrawn
- [ ] Rename 'Vendor' to 'Supplier' on Training event
- [ ] Rename 'Vendor' to 'Supplier' on Training event
- [ ] Include Training module under HR
