### ISSUE TITLE
RFQ - Standard Reply not copying into the Message for Supplier field

### ISSUE THREAD

**Issue by Dbonejones** [frappe/erpnext#5917]
In the Request for quote form, if you choose a Standard Reply the text from the selected Standard Reply is not copied into the text field. The text field remains blank or with whatever text is there currently.

Also, the Standard Reply text box is not on Print Hide by default, but the Message for Supplier text field is. I can change these myself easily, but maybe the defaults should be changed.

**Comment by rmehta** [comment]
@rohitwaghchaure can you check?
