### ISSUE TITLE
[BUG] Timesheet table has trouble with Date

### ISSUE THREAD

**Issue by bcornwellmott** [frappe/erpnext#5934]
When trying to fill out a Timesheet using the editable table for Timesheet Details (time_logs), the first entry seems to have issues getting set properly. The date picker dialog comes up and is changeable, but the value doesn't always save in the field correctly. This only affects the first item in the table - all the other rows seem to work fine. 

![image](https://cloud.githubusercontent.com/assets/16806041/17252627/44f1106a-5562-11e6-80e8-0f3fd0b6be90.png)

**Comment by PawanMeh** [comment]
![screen shot 2016-08-08 at 6 53 24 pm](https://cloud.githubusercontent.com/assets/20460498/17481298/0ab541b0-5d9a-11e6-8fdc-1b1503fda1c1.png)

'Extra' from time box appears after selection of time. 
@rohitwaghchaure can you check?

**Comment by rohitwaghchaure** [comment]
This issue is fixed
