### ISSUE TITLE
POS take payment screen adjustments

### ISSUE THREAD

**Issue by pifiu** [frappe/erpnext#5937]
I wanted to provide some small feedback to the take payment window.

1. When the window is originally opened the amount paid is already set to the total. This should be $0.00 until the amount is entered.

![cash1](https://cloud.githubusercontent.com/assets/2664750/17267349/91bcedde-55d4-11e6-91ea-202c4e4eb5a3.JPG)

2.

 Occasionally hitting "C" to clear the amount entered and clicking it again does not seem to update the "Paid". See below.
![cash2](https://cloud.githubusercontent.com/assets/2664750/17267351/9ec63210-55d4-11e6-8ce2-a2e154e4c07a.JPG)

3.
 When keying in the numbers using the on-screen keypad, the numbers entered should go from left to right. For example If I have $10 to pay, if you use the keypad to enter 1 and then 0, it should show up as $0.10, until you type in 0 and then 0 again to make it 10.00. If you were to type another 0 then it should keep moving left to make it $100.00.

4.
 Once the amount due has been marked as fully paid by one form of payment, any form of secondary payment should be null and not be allow the user to enter more.
![cash3](https://cloud.githubusercontent.com/assets/2664750/17267354/a5834674-55d4-11e6-9b0a-cdab85b838db.JPG)

**Comment by rohitwaghchaure** [comment]
Hi @pifiu 
2 & 4 is fixed.
Regarding 1 & 3 is specific case.
