### ISSUE TITLE
Production Order throws Mandatory Error

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#5940]
Production Order throws error, that Operation Description is necessary, however when you create the BOM and have operations, the Operation Description is not mandatory. This should be fixed.

**Comment by dottenbr** [comment]
@kickapoo can you fix this and make a pull request?

**Comment by Dbonejones** [comment]
This is the same issue now:

https://github.com/frappe/erpnext/issues/5980

**Comment by neilLasrado** [comment]
Has been fixed https://github.com/frappe/erpnext/pull/6146
