### ISSUE TITLE
Customer Status Stays "Open" After Deleting All Company Transactions

### ISSUE THREAD

**Issue by jetplane99** [frappe/erpnext#5942]
Dear Developers,

I'm noticing a bug whereby customer status stays "Open" after i've just deleted all company transactions to get rid of trial data. The customer's status is still open despite having no transactions. 

The calendar in Customer's still show the transactions. Please see the screenshot for better reference. 

Thanks!

![bug_status_open2](https://cloud.githubusercontent.com/assets/20623820/17278288/d8442cc6-5783-11e6-801c-666cab9e3f26.png)
![bug_status_open](https://cloud.githubusercontent.com/assets/20623820/17278289/d84598a4-5783-11e6-965f-9392114fce7f.png)

**Comment by sp9leo** [comment]
Having the same issue. Looks like data in heatmap calendar depends on Communication table. Also noticed that heatmap calendar gets populated even if you just open and save customer.
