### ISSUE TITLE
[v7]cannot create new leave application

### ISSUE THREAD

**Issue by omnison** [frappe/erpnext#5943]
Click buttom "New", no response. cannot create new leave application

**Comment by rmehta** [comment]
Cannot replicate.

Please share your error trace

**Comment by omnison** [comment]
i using google chrome, developer tool, and find error:
erpnext.min.js:17 Uncaught TypeError: Cannot read property 'employee_name' of undefined

**Comment by nabinhait** [comment]
Fixed via #5941
