### ISSUE TITLE
GL missing

### ISSUE THREAD

**Issue by ShashaQin** [frappe/erpnext#5945]
Hi,
We found GL Entry will be lost in some case.
This is one sales invoice, including one finished goods item, and update stock ticked.
![sales_invoice](https://cloud.githubusercontent.com/assets/12147007/17284327/5a049cb0-57ec-11e6-9b3b-23f84e70dd92.png)
This is the Accounting Ledger of above sales invoice, looks some account records not generated. It should have one 'finished goods' account and one 'cost of goods sold' account like the third picture.
![incorrect_gl](https://cloud.githubusercontent.com/assets/12147007/17284328/5bf3352c-57ec-11e6-9d84-c58d8b347068.png)
![correct_gl](https://cloud.githubusercontent.com/assets/12147007/17284331/5dc5e87c-57ec-11e6-8e99-331972c1b98f.png)

I'm not sure if this GL missing is caused by sales invoice created before stock entry, but the third picture is tested on version 7, that sales invoice is created before stock entry as well(Picture 1 and 2 are history data generated in the earlier version than version 7). I'm wondering if the version 7 fixed this issue, but not create a patch to fix the missing data.

**Comment by rohitwaghchaure** [comment]
Hi @ShashaQin 
Can you check, what is the valuation rate of the item **item1** before the date 09/09/2015.

**Comment by ShashaQin** [comment]
@rohitwaghchaure thank you for your reply. The valuation rate of the item1 is 0. 
And I tested again on version 7, I found this problem still exists. The following two scenario will cause GL missing problem:
1. Stock entry created/submitted before sales invoice, but posting date is after the posting date of sales invoice. 
2. Stock entry created/submitted after sales invoice.

**Comment by ShashaQin** [comment]
This is stock ledger for item1:
![stock ledger](https://cloud.githubusercontent.com/assets/12147007/17394589/926d03ae-5a5c-11e6-8ded-5f2c1ffdd988.png)

**Comment by ShashaQin** [comment]
This is GL report, the circled one couldn't find matched gl record that should be generated when submit SINV-12122 (as you can see the second picture)
![gl](https://cloud.githubusercontent.com/assets/12147007/17395067/07e28a94-5a5f-11e6-8a5e-56d22f4d29ac.png)

**Comment by ShashaQin** [comment]
This will leave finish good account with amounts that won't be credited even if the correspondent Sales invoice or a Delivery Note is submitted.

**Comment by nabinhait** [comment]
@ShashaQin 

You should always deliver / invoice after receiving the goods. If you deliver before receiving, system does not know the valuation rate and hence does not post the GLE for COGS.

To get better results, you should disable negative inventory, in case of  perpetual inventory.

**Comment by ShashaQin** [comment]
@nabinhait Thank you for your reply. I know what you mean, but now our GL missed some data because of that. Do you have some suggestion or solution to fix those data?

**Comment by nabinhait** [comment]
May be a back-dated Stock Reconciliation for all the relevant items will fix the GL Entry for DN/SI.
