### ISSUE TITLE
Autofill item code in batch when creating from a purchase receipt

### ISSUE THREAD

**Issue by cgpurbaugh** [frappe/erpnext#5960]
I have attempted to get this to work using custom scripts, but so far no luck.  could someone help me figure out a way to do this?

**Comment by jwrober** [comment]
Please open a discussion on this subject in the forum - https://discuss.erpnext.com/ - to get help with this.

**Comment by satishmalkar94** [comment]
I am facing same issue can any any one help me for the same , how to do this using custom script or any another approach..
