### ISSUE TITLE
Problem with Insert Below and Insert Above

### ISSUE THREAD

**Issue by komsel2228** [frappe/erpnext#5973]
Dear ERPNext Team, i found some error in all form example : journal voucher,purchase receipt, delivery note, landed cost voucher, payment entry, etc if we use "insert below" or "insert above"

for example, i attach 2 picture.
![screenshot from 2016-08-02 16 03 54](https://cloud.githubusercontent.com/assets/8717967/17325632/cff225a6-58d6-11e6-836e-634297169a09.png)
![screenshot from 2016-08-02 17 20 42](https://cloud.githubusercontent.com/assets/8717967/17325640/d56b125e-58d6-11e6-96f5-1f0ec48cb508.png)

in versi 6, if we use insert above and insert below did not close "picture 1", and still "picture 1"
in versi 7, if we use insert below have bugs and insert above like that..run to "picture2"
please fix that..

thanks,
best regards,
ignatius cuknoris  & antonius andiyanto tara

**Comment by PawanMeh** [comment]
@komsel2228 , I think this is fixed with the latest update, Kindly close the issue if it is fixed.

**Comment by komsel2228** [comment]
@PawanMeh ooh oke.. 
on erpnext 7.0.42 frappe 7.0.30 it's work.. thanks ERPNext Team for fix that...
