### ISSUE TITLE
The videos from the "Learn" section are opened several times in the popup window

### ISSUE THREAD

**Issue by vnkb** [frappe/erpnext#5979]
a. Open the "Learn" Section.
b. Click to open a video. For example: the "Navigating"
c. As result the video is loaded in the popup window many times.
As result the UX is not cool. I am trying to figure out how to lead my team to be trained in the EPRNext is and found that there will be questions in non-tech persons.

**Comment by yashodhank** [comment]
@vnkb Already fixed few build before. It's time for you to perform.
```
$ bench update --upgrade
```
Close this issue if resolved.

**Comment by vnkb** [comment]
Confirmed as fixed. 
Great job, guys!
