### ISSUE TITLE
Production Planning Tool - no Production order created and no error message if the item's BOM has Operations without descriptions

### ISSUE THREAD

**Issue by Dbonejones** [frappe/erpnext#5980]
PPT will create a Production Order from a Sales Order item or a Material Request Item without Operations, but if the Item has Operations it will not create. No error message.

ERPNext v 7.0.16
Frappe v 7.0.14

**Comment by rmehta** [comment]
Did you check if the item is already in stock?

**Comment by Dbonejones** [comment]
> Did you check if the item is already in stock?

Yes. Makes no difference if it's in stock.

I found the source of the error though. If an Operation has no description the PPT will not create a production order. I found this out by trying to manually create a Production order from the same Item, same BOM. I got an error message there saying that the Operation needed a description.
You have to remake the BOM after the description is added too since the BOM will not update by design.

So it looks like that error message should be added to the PPT, with probably an addition letting the user know which Item contains the bad Operation.
Or alternatively, all Operation fields should be updated to have the description be mandatory, probably a better fix so people don't end up with many BOM's that must be cancelled and updated.

**Comment by Dbonejones** [comment]
These issues are related now:

https://github.com/frappe/erpnext/issues/5940

**Comment by mulyadi-agtechsg** [comment]
Hi,

Any progress on this? It is essential part of manufacturing process/workflow.

Thanks.

**Comment by neilLasrado** [comment]
Has been fixed https://github.com/frappe/erpnext/pull/6146
