### ISSUE TITLE
Payment Entry currency bug

### ISSUE THREAD

**Issue by kodybaker** [frappe/erpnext#5982]
Installed Apps
ERPNext: v7.0.18
Frappe Framework: v7.0.15

There's currently an issue with which currencies are being used when recording a payment entry against a purchase order.

As shown in the screen caps below:
1. Account currency is USD. Account Paid to is CAD.
2. Paid Amount is shown in USD, but actually represents the PO amount in CAD.
3. Received Amount is showing CAD correctly.
4. The Paid Amount (CAD) at the bottom is multiplying the USD field by the exchange rate, but it is already showing the CAD quantity in the USD field, making it multiply by the exchange rate twice.

![chrome_2016-08-02_15-44-56](https://cloud.githubusercontent.com/assets/12718284/17347971/29902f36-58c8-11e6-8331-ec16497d035c.png)
![chrome_2016-08-02_15-45-18](https://cloud.githubusercontent.com/assets/12718284/17347973/2bf87800-58c8-11e6-9dc1-01d975db155d.png)

**Comment by kodybaker** [comment]
It produces some bizarre effects when making all of the concerned accounts in USD as well. 
Purchase Order in USD.
Account Paid from in USD
Account Paid to in USD
Paid Amount (USD) = 5,465.21 (The CAD quantity)
Exchange rate to CAD presented. Anything typed here impacts the writeoff section under the references box. 
![image](https://cloud.githubusercontent.com/assets/12718284/17348323/5ca0fc0a-58ca-11e6-9e5f-7ab78da4ef67.png)

**Comment by nabinhait** [comment]
Pushed a potential fix for 2nd case #5986 .

And for the first case, as you are paying the supplier from a USD bank account, the paid amount should be USD 4204.008 (5465.21  / 1.3) and received amount should be CAD 5465.21.
