### ISSUE TITLE
Unable to customize list views

### ISSUE THREAD

**Issue by cgpurbaugh** [frappe/erpnext#5990]
Checking/Unchecking 'list view' has no effect.
One can check 'hidden' and it will disappear from list view, but there is no method for adding a field.

**Comment by umairsy** [comment]
In the Customize Form, "In List View" function is primarily intended for adding a field as a Column in the grid view of data entry form. To learn more, check:

https://frappe.erpnext.com/kb/setup/customizing-visibility-of-data-in-the-child-table
