### ISSUE TITLE
[V7] Shipping Rule - Unable to Save

### ISSUE THREAD

**Issue by yashodhank** [frappe/erpnext#5993]
**Installed Apps**
ERPNext: v7.0.18
Frappe Framework: v7.0.15
Razorpay Integration: v1.0.0

Selecting Worldwide Shipping option does saves the rule.
But if Country is selected, record is not being saved with error message as follows:

![image](https://cloud.githubusercontent.com/assets/1083792/17394139/270f7d06-5a45-11e6-959c-f848d6342d72.png)

**Comment by PawanMeh** [comment]
Unable to replicate in beta
