### ISSUE TITLE
Finalise chart of accounts based on country

### ISSUE THREAD

**Issue by nabinhait** [frappe/erpnext#5994]

**Comment by nabinhait** [comment]
charts.erpnext.com

**Comment by PawanMeh** [comment]
![screen shot 2016-08-08 at 12 05 22 pm](https://cloud.githubusercontent.com/assets/20460498/17471247/7cc764d4-5d60-11e6-9ec3-be8a5671b5dc.png)
Error at charts.erpnext.com

**Comment by nabinhait** [comment]
@PawanMeh Fixed the error

**Comment by PawanMeh** [comment]
![screen shot 2016-08-09 at 2 33 05 pm](https://cloud.githubusercontent.com/assets/20460498/17510883/633ed072-5e3e-11e6-9910-d61e4daa91c0.png)
Unable to add new child, the "New Account Name" field does not allow typing
