### ISSUE TITLE
[v7] Salary Slip has Default Amount = 0

### ISSUE THREAD

**Issue by ASneha1** [frappe/erpnext#5997]
Hi,

Noticed that in Salary Structure, we do not have to set Default Amount and it remains at 0. Thus, we only set the Amount. 
![image](https://cloud.githubusercontent.com/assets/16811259/17397407/85493c2a-5a6a-11e6-98d3-1798522ce05d.png)

When Salary Slip is made from Salary Structure, the Default Amount is carried over to be 0 and when 'Depends on Leave Without Pay', the calculation is from Default Amount and it does calculation on 0. 
The result is : 
![image](https://cloud.githubusercontent.com/assets/16811259/17397482/d9342624-5a6a-11e6-90ee-98fe2654c93f.png)

Kindly help to address this issue.

Thank you.

**Comment by KanchanChauhan** [comment]
@ASneha1 it has been fixed in v7
