### ISSUE TITLE
[V7] Editing row window pop-up not working right

### ISSUE THREAD

**Issue by sp9leo** [frappe/erpnext#6009]
Controls on Edit row window don't seem to work right. "insert above" adds a new line but closes the window, "insert below" does nothing. Same behavior on forms and in customize form table.

![image](https://cloud.githubusercontent.com/assets/15377465/17456135/071265fc-5bcd-11e6-845a-f973c98d1316.png)

Error in Chrome:  

> form.min.js:308 Uncaught TypeError: Cannot read property 'idx' of undefined

**Comment by PawanMeh** [comment]
The issue with "insert above" and "insert below" is fixed in the latest releases. Please close the issue if your problem is resolved.
