### ISSUE TITLE
V7 - Material Request Item table not going to to old style when unchecking is "editable grid"

### ISSUE THREAD

**Issue by it2sme** [frappe/erpnext#6013]
V7 - Material Request Item table not going to to old style when un-checking is "editable grid".
All other doctype respond well, except for Material Request and also item name is checked for "in list view"

Thank you.

**Comment by jetplane99** [comment]
i can't seem to go back to old style for all doctypes when unchecking "Editable Grid".

@it2sme, how did you do it?

**Comment by it2sme** [comment]
@jetplane99 For other doctypes, I just uncheck the "editable grid" checkbox in "Customize". But for material request item it does not have any effect. 
Now after checking the files I saw the piece of code that allows to go back to the old style is this:

**Material Request:**
# form_grid_templates = {
# 	"items": "templates/form_grid/material_request_grid.html"
# }

**Stock Entry:**
form_grid_templates = {
	"items": "templates/form_grid/stock_entry_grid.html"
}

The difference is that it is commented in the Material Request and in 
**/home/frappe/frappe-bench/apps/erpnext/erpnext/templates/form_grid**
there is also no **material_request_grid.html** file.

As a temporary solution until a fix, I have copied the **material_request_grid.html** file from a V6 server and copied it the templates folder and uncommented the text in the python file. Now it showing.

Any help needed let me know.
