### ISSUE TITLE
Installation error 

### ISSUE THREAD

**Issue by zaasmi** [frappe/erpnext#6016]
TASK [Get nodejs 6.x bash script] **********************************************
fatal: [localhost]: FAILED! => {"changed": false, "dest": "/tmp/setup_6.x", "failed": true, "msg": "Request failed", "response": "Request failed: <urlopen error timed out>", "state": "absent", "status_code": -1, "url": "https://deb.nodesource.com/setup_6.x"}

NO MORE HOSTS LEFT *************************************************************
	to retry, use: --limit @production/install.retry

PLAY RECAP *********************************************************************
localhost                  : ok=8    changed=0    unreachable=0    failed=1   

Traceback (most recent call last):
  File "install.py", line 342, in <module>
    install_bench(args)
  File "install.py", line 111, in install_bench
    run_playbook('production/install.yml', sudo=True, extra_vars=extra_vars)
  File "install.py", line 292, in run_playbook
    success = subprocess.check_call(args, cwd=os.path.join(cwd, 'playbooks'))
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ansible-playbook', '-c', 'local', 'production/install.yml', '-e', '@/tmp/extra_vars.json', '--become', '--become-user=frappe']' returned non-zero exit status 2

**Comment by yashodhank** [comment]
@zaasmi known issue, closing.
Follow up:
https://discuss.erpnext.com/t/i-always-get-error-from-ansible-no-more-hosts-left/13179
https://discuss.erpnext.com/t/closed-fresh-install-error-access-denied-for-user-root-localhost/14481
**Hint:** Google > frappe returned non-zero exit status 2
