### ISSUE TITLE
pricing rule bug in POS

### ISSUE THREAD

**Issue by aboganas** [frappe/erpnext#6028]
POS doesn't take into consideration minimum qty to apply pricing rule

Tp reproduce the bug:
- define a pricing rule for an Item, and set a minimum quantity for this rule to be applied
- if a create a sale order and add the item then the rule apply perfectly based on min qty; however, if i try it in POS when I add the item it apply the discount even when the minimum qty is not meet

Erpnext version 7.0.21
frappe version 7.0.18
bench version 4.1.0

**Comment by rohitwaghchaure** [comment]
This issue has fixed, we'll release it soon.
