### ISSUE TITLE
Outbound email service does not work

### ISSUE THREAD

**Issue by vCentre** [frappe/erpnext#6029]
Adding email account whatever incoming or outgoing by using the predefined services i.e Gmail or custom such as Elastic mail always results in freeze faded screen.

Please fix email service, and add test connection button to get informed.

**Comment by rmehta** [comment]
@vCentre works for me (locally)

Which version are you on? Can you check your error console?

**Comment by yashodhank** [comment]
@vCentre I observed similar issue few months ago, but unfortunately that causes due to server load or specially on low memory machines.
it is no more the case. So please reply if you do not face this issue at present, as I will go ahead and close this issue.
