### ISSUE TITLE
Feature Development: Merge repeat items in Purchase Orders generated by Material Request

### ISSUE THREAD

**Issue by sliska** [frappe/erpnext#6041]
Hi ERPNext team,

At the moment when a material request is generated by the production planning tool there can be multiple lines for the same item if it appears in multiple sales orders or has an order minimum. When the material request is converted into a purchase order the purchase order also has multiple lines for the same item. If the lines are added up into one in the purchase order then the system does not register the complete purchase of the material request.

When a purchase order is generated by a material request, we'd like the repeated items in the material request to be added together into one line at the purchase order level. A supplier does not need to receive a purchase order with two or more lines for the same item. 

Can you help us with this please?

thanks,
Sofia

**Comment by PawanMeh** [comment]
@nabinhait can a grouping/group by be done on the PO Print layout for this?

**Comment by rmehta** [comment]
I agree with @PawanMeh this can be done in Print Format. Maybe in the item table we can make it standard for all documents. Create check box for (group same items in one line) and then based on that, merge in the print table.

**Comment by sliska** [comment]
Sounds good. How long will developing this take?

**Comment by rmehta** [comment]
We usually won't commit on timelines. If you want it earlier, you can always sponsor it :)

**Comment by sliska** [comment]
Hi @rmehta, sounds good. How much to sponsor it? When could it be done by if we sponsor it?

**Comment by rmehta** [comment]
Do you want to post this on https://community.erpnext.com ?

Make sure you mention that it must be contributed back to the product!

**Comment by rmehta** [comment]
Will do this with the 7.1 release.

**Comment by sliska** [comment]
Okay, thanks @rmehta .
