### ISSUE TITLE
Stock Settings - Allowance % Is not affecting PO Receiot

### ISSUE THREAD

**Issue by sumeetagra** [frappe/erpnext#6042]
Allowance percent 0 is allowing additional receipt quantity more than the PO Quantity.

**Comment by rohitwaghchaure** [comment]
Hi @sumeetagra 
Not able to reproduce this issue.

It's working properly 
![screen shot 2016-09-14 at 4 54 28 pm](https://cloud.githubusercontent.com/assets/8780500/18510500/033758aa-7a9c-11e6-8d42-7317a041e6b0.png)
