### ISSUE TITLE
Simple rule to auto escalate a ticket of SLA breach

### ISSUE THREAD

**Issue by nishikantpanda** [frappe/erpnext#6049]
As a system admin I want to escalate a support ticket to the reporting manager of the assignee if the ticket is not responded within a set time. 

This should keep on escalating the tickets till it reaches the highest level. 

I should be able to define individual SLAs for each level.

**Comment by kennethsequeira** [comment]
Should be now configurable with [SLA](https://docs.erpnext.com/docs/v13/user/manual/en/support/service-level-agreement) and [auto-assign](https://docs.erpnext.com/docs/v13/user/manual/en/automation/assignment-rule) features.
