### ISSUE TITLE
 Created Quotation for Leads should also be seen when lead was converted to Customer

### ISSUE THREAD

**Issue by ai-erp** [frappe/erpnext#6051]
We have updated our ERP to V7...
I have noticed that upon creation of Quotation for leads, that same quotation is not showing upon viewing the customer (after conversion from Lead to Customer)...

Like for example, i have Lead no.1111...
i have created a quotation for that lead QTN-00001 dated 15/07/2016
on 18/07/2016, this Lead ordered the items included in this QTN.
In that case, we converted the Lead to customer (example: Customer AAA)

When we open Customer AAA, there is no quotation showing.

The quotation should also be showing since the lead and customer is linked together.
Thank you...

**Comment by PawanMeh** [comment]
The suggested sequence is : Lead -> Customer -> Quotation. If you follow this, you will see the quotations under customer.

When you create a Quotation from a Lead the 'person name' in the lead defaults to the 'customer name' in the quotation,which would probably be different from your final customer name. Hence the discrepancy.

**Comment by ai-erp** [comment]
hi, usually, the lead are only prospective customers... we are not converting leads to customer unless they have confirm order. and also, this is to note which are actual customers who are buying our products and which one are getting only quotes but are not yet buying...

**Comment by opsninja1** [comment]
We are having the exact same issue, under the exact same circumstances.  There really is no benefit to creating a customer before an order is confirmed.  We have thousands of quotes that do not end up as Sales Orders.  Our customer db would be enormous if we converted each lead to a customer before generating a quote.

**Comment by ai-erp** [comment]
you are definitely right @opsninja1 ...
