### ISSUE TITLE
[V7] ERPNext crashes when trying to upload image

### ISSUE THREAD

**Issue by Gleisson03** [frappe/erpnext#6052]
ERPNext crashes when trying to upload image and takes a few minutes until the system back.
Note 1: I uploaded the image through the File Manager before.
Note 2: If you try to open the ERPNext on another page, the system will be out of breath.

![error](https://cloud.githubusercontent.com/assets/13992475/17557131/71bf528a-5eec-11e6-9101-02129681f310.gif)

**Comment by rmehta** [comment]
You have to save it before you the image gets saved. Its a UX issue. Fixed in local. Will push in a bit.

Thanks for reporting.
