### ISSUE TITLE
[V7] Dropbox Error

### ISSUE THREAD

**Issue by iramireze** [frappe/erpnext#6057]
After a minor update, Dropbox Backup stopped.

Setup > Dropbox Backup's system message as follows:

> Please install dropbox python module

Any ideas?

**Comment by PawanMeh** [comment]
please try from frappe-bench

env/bin/pip install dropbox

**Comment by iramireze** [comment]
Thank you Pawan..

I had to reinstall and restore from back-up. Everything is fine now.

Regards,
