### ISSUE TITLE
[FAILED TEST] - Tests are failed after repeated test execution 

### ISSUE THREAD

**Issue by safo-bora** [frappe/erpnext#6066]
**Environment:**
- bench 4.1.0
- erpnext 7.0.26
- frappe 7.0.19

**Step to reproduce:**
1. Download from https://erpnext.com/download ERPNext-Production.ova 
2. Setup and run tests two times:
```
cd frappe-bench
bench update
bench run-tests
bench run-tests
```

**Result (failed tests):**

# Test # 1
**frappe.tests.test_api.TestAPI**

> Traceback (most recent call last):
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/tests/test_api.py", line 23, in test_insert_many
>     server = FrappeClient(host, "Administrator", "admin", verify=False)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/frappeclient.py", line 16, in __init__
>     self.login(username, password)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/frappeclient.py", line 34, in login
>     raise AuthError
> AuthError

# Test # 2
**erpnext.accounts.doctype.sales_invoice.test_sales_invoice.TestSalesInvoice**
> Traceback (most recent call last):
>   File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/sales_invoice/test_sales_invoice.py", line 980, in test_party_status
>     self.assertEquals(frappe.db.get_value('Customer', customer.name, 'status'), 'Open')
> AssertionError: u'Active' != u'Open'
> - Active
> + Open

# Test # 3
**erpnext.accounts.doctype.sales_invoice.test_sales_invoice.TestSalesInvoice**
> Traceback (most recent call last):
>   File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/sales_invoice/test_sales_invoice.py", line 474, in test_make_pos_invoice
>     self.assertEquals(si[0], '09052016142')
> IndexError: list index out of range

# Test # 4
**frappe.tests.test_permissions.TestPermissions**

> ERROR: test_insert_if_owner_with_user_permissions (frappe.tests.test_permissions.TestPermissions)
> If If Owner is checked for a Role, check if that document is allowed to be read, updated, submitted, etc. except be created, even if the document is restricted based on User Permissions. 
> Traceback (most recent call last):
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/tests/test_permissions.py", line 247, in test_insert_if_owner_with_user_permissions
>     doc.insert()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 223, in insert
>     self.db_insert()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 284, in db_insert
>     ), d.values())
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 137, in sql
>     self._cursor.execute(query, values)
>   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
>     self.errorhandler(self, exc, value)
>   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
>     raise errorclass, error value
> DuplicateEntryError: (u'Blog Post', u'-test-blog-post-title', IntegrityError(1062, "Duplicate entry '-test-blog-post-title' for key 'PRIMARY'"))

# Test # 5
**frappe.website.doctype.blog_post.test_blog_post.TestBlogPost**

> ERROR: test_generator_not_found (frappe.website.doctype.blog_post.test_blog_post.TestBlogPost)
> Traceback (most recent call last):
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/doctype/blog_post/test_blog_post.py", line 27, in test_generator_not_found
>     frappe.db.set_value('Blog Post', pages[0].name, 'route', 'test-route-000')
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 608, in set_value
>     {2}""".format(dt, field, conditions), values, debug=debug)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 137, in sql
>     self._cursor.execute(query, values)
>   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
>     self.errorhandler(self, exc, value)
>   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
>     raise errorclass, error value
> IntegrityError: (1062, "Duplicate entry 'test-route-000' for key 'route'")
>

**Comment by rmehta** [comment]
@safo-bora No need to raise issues. If tests fail, they will be updated in Travis

https://travis-ci.org/frappe/erpnext
https://travis-ci.org/frappe/frappe

Closing these issues here
