### ISSUE TITLE
BoM Item code changed

### ISSUE THREAD

**Issue by cgpurbaugh** [frappe/erpnext#6072]
Item code and item name are combined when saving.  Item link field acts like Item Code: Item name is the item code, so clicking the link doesn't work.

**Comment by PawanMeh** [comment]
I noticed that right click and open link in new window actually opens up the Item, is that what you were trying?

![screen shot 2016-08-31 at 8 18 31 am](https://cloud.githubusercontent.com/assets/20460498/18114281/a617b744-6f53-11e6-90ea-e96ce99d087d.png)

**Comment by cgpurbaugh** [comment]
Actually it's the item code/name of the assembly, not the raw matls table:
![capture](https://cloud.githubusercontent.com/assets/13136405/18128722/3228797a-6f55-11e6-8c72-c0c6cce094d9.PNG)

**Comment by cgpurbaugh** [comment]
This has been fixed!
