### ISSUE TITLE
Cancelled Timesheet hours show under Project Activity Summary

### ISSUE THREAD

**Issue by superlack** [frappe/erpnext#6074]
When a timesheet is cancelled, the hour value shows under the activity summary in the project doctype.  Dangerous for double entering hours if a timesheet is submitted/cancelled/amended, because the hours add on, and the cancelled timesheet cannot even be deleted because it's related to the new amended timesheet.

**Comment by superlack** [comment]
Thanks!

**Comment by rmehta** [comment]
Thanks for reporting :)
