### ISSUE TITLE
Custom Report Development

### ISSUE THREAD

**Issue by sliska** [frappe/erpnext#6075]
Hi ERPNext team, 

We need a custom report to be developed and I'm told it requires changes from the backend. Can you help is with this? If so, how much would it cost and how long would it take? 

We need the purchase and sales register reports to pull additional data from the purchase and sales invoices and from the item profile. We also need the purchase and sales invoices to pull data from fields in the item, supplier, and customer profiles. Below is a link to a googlesheet that shows the fields we need in the report. Please let me know if you can help us so that I can send you more detail if necessary.

Thanks,
Sofia

**Comment by rmehta** [comment]
THere is no link. Please attach a screenshot of the report you want and not google links!

**Comment by sliska** [comment]
@rmehta , sorry! Here is a screenshot of the columns we need and which documents the data is fetched from. 

Sales Register Report:
![image](https://cloud.githubusercontent.com/assets/13278512/17629569/40057660-6078-11e6-996e-574e8ac3b3bf.png)

Purchase Register Report:
![image](https://cloud.githubusercontent.com/assets/13278512/17629588/518c0f84-6078-11e6-9b59-514befd5482a.png)

Thanks!
Sofia

**Comment by sliska** [comment]
@rmehta , can we sponsor the development of this report?

**Comment by rmehta** [comment]
@sliska  you want to post a job at https://community.erpnext.com/jobs ?

**Comment by sliska** [comment]
The problem is our instance is on the frappe servers. I already hired a programmer to made the fields and connect all of them to the correct data but he cannot access developer mode to add the columns to the reports.

**Comment by rmehta** [comment]
Your programmer needs to send a pull-request with the required changes and we will update it in the app.
