### ISSUE TITLE
Currency symbol wrong in Report:Accounts Receiveable (total line)

### ISSUE THREAD

**Issue by jaywks** [frappe/erpnext#6077]
Currency symbol should be of Party Account Currency's when generating report for single customer ,but shown Company Base Currency's in total line of A/R report instead.ERPNext: v7.0.24
<img width="1149" alt="accounts receivable currency symbol wrong in total line" src="https://cloud.githubusercontent.com/assets/16625441/17615931/8939c390-6082-11e6-94f9-24e44c97d2b8.png">

**Comment by nabinhait** [comment]
fixed via https://github.com/frappe/frappe/pull/1989

**Comment by jaywks** [comment]
Thank you , but the printed report still having same issue.
<img width="705" alt="ar print total row curency symbol" src="https://cloud.githubusercontent.com/assets/16625441/17830094/96058f04-66d2-11e6-9477-6890a2e4126a.png">

**Comment by nabinhait** [comment]
Fixed total row currency via https://github.com/frappe/frappe/commit/c1bab9d5d0e7ad38f0447ae212a7fe77bf71f506
