### ISSUE TITLE
Purchase Invoice column title shows EUR even though it's GBP

### ISSUE THREAD

**Issue by nununo** [frappe/erpnext#6081]
I think the image is self-explanatory:
<img width="919" alt="screen shot 2016-08-13 at 03 48 52" src="https://cloud.githubusercontent.com/assets/532049/17641060/e93d04a6-6108-11e6-81bf-be0739c32026.png">

**Comment by rohitwaghchaure** [comment]
Hi @nununo 

We have fixed this issue, kindly pull latest update and check

**Comment by nununo** [comment]
I guess I'll have to way for it to be published in the cloud version, right?
