### ISSUE TITLE
Communication Count Badges show wrong number

### ISSUE THREAD

**Issue by Braintelligence** [frappe/erpnext#6082]
As you can see here:

![image](https://cloud.githubusercontent.com/assets/6761196/17652779/5cc1ed8c-6286-11e6-886b-3c4d05fd1ff5.png)

The badges for Closed, Linked and Sent are clearly wrong. Even with the administrator account I can't see anything there.

How can I find and erase them for good?

**Comment by rmehta** [comment]
Fixed in next release.
