### ISSUE TITLE
Issue on Delivered items to be billed

### ISSUE THREAD

**Issue by ai-erp** [frappe/erpnext#6087]
Hi there,

We were checking the Delivered items to be billed in our V7 erpnext.
We have noticed that in this report, it includes the items which was returned by customers..

like for example, i have made a delivery note for item 1 with DR-00001..
I also made INV-00001 linked to that delivery note...
this means that ITEM 1 in DR-00001 is billed.

On the next day, customer came and said that he want to return the item.
In this case, Delivery Note Return has made with DR-RET-00001 and INV-CN-00001...

In the report of DELIVERED ITEMS TO BE BILLED, this DR-00001 is included.

I think this should not be included since this DR has been returned.

**Comment by PawanMeh** [comment]
Can be handled as part of customization by customer on case by case basis
