### ISSUE TITLE
Error when trying add to desktop

### ISSUE THREAD

**Issue by justinlusg** [frappe/erpnext#6088]
![image](https://cloud.githubusercontent.com/assets/12539216/17664545/6b9839fa-6327-11e6-9cbc-e6568200826f.png)

I get this error when trying to add a custom Sales Order report to the desktop. The desktop has a Sales Order shortcut.

**Comment by phamviet** [comment]
As i know Desktop shortcut does not support custom filters and what are you doing is trying to re-add Sales Order shortcut that is already existed. Hope we will support it in future, as well as on module shortcuts.

**Comment by justinlusg** [comment]
It used to work, I used to be able to add custom reports to the desktop.

**Comment by PawanMeh** [comment]
This seems to be working fine,have you tested after application of the latest updates?

**Comment by nabinhait** [comment]
fixed in develop
