### ISSUE TITLE
Issue on Gross Profit

### ISSUE THREAD

**Issue by SujanPillai** [frappe/erpnext#6089]
Hi,

We have an issue with Gross Profit Report.

For eg. we purchased an material for selling GTSC3M05703CBMP-ST and it is non-stocking material.
1st we purchased it with AED.7.50 and we sold it to a customer.
After some days we again purchased it for AED.6.50 for another customer and we sold it.

Issue is when we took the updated Gross Profit Report ;
According to Image Part.1 the Average Buying Rate of last buying Showing as 6.80 .We need there Latest Buying Rate instead of Average Buying rate.

According to Image Part.2 Buying rate is calculated by system as ;
40 pcs x AED.7.50 = AED.300.00
100 pcs x AED.7.00 = AED.700.00
160 pcs x AED.6.50 = AED.300.00
ie Total Amount =AED.2040.00 for 300 pieces.
ie AED.6.80/pcs as average.

But as the item is an Non-stocking item we cant take the average value , we need the latest purchase rate(we are selling according to latest purchase rate only).

So Please help in the issue.

![erp-1](https://cloud.githubusercontent.com/assets/21039453/17666921/a0957910-6313-11e6-9f6e-d08167d04469.jpg)

**Comment by PawanMeh** [comment]
Closing this as it appears to have been merged.
