### ISSUE TITLE
Daily cash/cash in bank collection/expense report

### ISSUE THREAD

**Issue by ai-erp** [frappe/erpnext#6100]
Dear ALL,

Good day...
Is there any way we can generate daily cash collection report same as below format:

![c](https://cloud.githubusercontent.com/assets/16744099/17706422/06f8a072-63ed-11e6-9cb2-2dbe3535e677.png)

Right now, we can only get daily report in the GL by selecting each cash/CIB/PDC account to get the total amount for each on a daily basis. It would be very helpful if we get the same report as shown in the screenshot.
Is this possible to create?
Thank you...

**Comment by me2ne** [comment]
It's good , if there is report for each seller of cashier , how much they have collection per day . 
For example in one company there is 4 cashier and end of day or end of his duty they want to give his cash and cheque collection to his manager or account . . it's good if there is separate report for each cashier . 
Regards

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.
