### ISSUE TITLE
On change of custom workflow, all transactions disappear

### ISSUE THREAD

**Issue by cgpurbaugh** [frappe/erpnext#6104]
https://discuss.erpnext.com/t/solved-purchase-orders-not-being-displayed-after-change-in-workflow/14879

I believe this is caused when one of the documents has a workflow state that is removed.

**Comment by mhbu50** [comment]
+1

**Comment by tundebabzy** [comment]
See https://discuss.erpnext.com/t/solved-purchase-orders-not-being-displayed-after-change-in-workflow/14879/11?u=tundebabzy for resolution

**Comment by cgpurbaugh** [comment]
@tundebabzy The post you are referencing is the reason that I made this issue.  The system should not make all transactions disappear because there is a workflow state missing.  At the very least an error message should be thrown.

**Comment by tundebabzy** [comment]
Oh ok. I get it now.
