### ISSUE TITLE
Cost Center - Improve validation message for Budget

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#6109]
![screen shot 2016-08-17 at 5 57 27 pm](https://cloud.githubusercontent.com/assets/910238/17736215/23fa78aa-64a4-11e6-8640-a2f2e2df9080.png)

**Comment by nabinhait** [comment]
Any suggestion?

**Comment by PawanMeh** [comment]
round off the decimals to 2 
and color next to message should be 'red' based on setting of 'Stop','Warning' etc
