### ISSUE TITLE
Global Search Like Vtiger CRM

### ISSUE THREAD

**Issue by ai-erp** [frappe/erpnext#6112]
Just a suggestion...

I think it is better to make search bar in erpnext same as that of the Vtiger CRM.
When we want to search for example telephone number or name of any person, and we type the keyword in the search bar, all links will be shown without going through to the document type where that keyword might be found.

Same thing when we type keyword in searching to discuss, we only type and all links will show...

Thank you...

**Comment by me2ne** [comment]
i think he is right , it's very important feature and missed in erpnext .

**Comment by PawanMeh** [comment]
Kindly post further discussion comments on [discuss](https://discuss.erpnext.com)

**Comment by justinlusg** [comment]
I agree, this is one of the most important features for an ERP platform

**Comment by mhbu50** [comment]
+1

**Comment by Devens** [comment]
+1

**Comment by rmehta** [comment]
#6674
