### ISSUE TITLE
Error with User Permissions Manager

### ISSUE THREAD

**Issue by komsel2228** [frappe/erpnext#6116]
Dear ERPNext Team,
we have some problems with "User Permissions Manager"
![screenshot from 2016-08-18 15-42-49](https://cloud.githubusercontent.com/assets/8717967/17767922/2a54ea92-655c-11e6-94f5-7f1d92849966.png)
![screenshot from 2016-08-18 15-43-14](https://cloud.githubusercontent.com/assets/8717967/17767962/40b9db44-655c-11e6-9782-62295438f63a.png)
![screenshot from 2016-08-18 15-43-34](https://cloud.githubusercontent.com/assets/8717967/17767980/520e8bb0-655c-11e6-82ec-83a275302c72.png)
![screenshot from 2016-08-18 15-44-14](https://cloud.githubusercontent.com/assets/8717967/17767991/5d45bfa8-655c-11e6-9625-ec19dcb488b3.png)
![screenshot from 2016-08-18 15-44-54](https://cloud.githubusercontent.com/assets/8717967/17768008/688c8928-655c-11e6-85b5-999dd0730d5b.png)
![screenshot from 2016-08-18 15-45-18](https://cloud.githubusercontent.com/assets/8717967/17768017/6f34090e-655c-11e6-9a78-69784d770c5f.png)
![screenshot from 2016-08-18 15-46-02](https://cloud.githubusercontent.com/assets/8717967/17768025/74fe8710-655c-11e6-8185-8e1c2b04140f.png)
can fix that. 
by the way, we use ERPNext: v7.0.29 and Frappe Framework: v7.0.23

thanks,
best regards,
ignatius cuknoris & antonius andiyanto tara

**Comment by PawanMeh** [comment]
Hi,

I am trying to replicate this issue and I have followed the below steps:

- Set permissions for the user
![1-permissions](https://cloud.githubusercontent.com/assets/20460498/18129164/1a476670-6fa7-11e6-9f61-bdfdbf11c351.png)

- Create delivery note
![2-delivery note](https://cloud.githubusercontent.com/assets/20460498/18129169/22f00868-6fa7-11e6-9abd-8a6db685768c.png)

![3-delivery note](https://cloud.githubusercontent.com/assets/20460498/18129177/30b92fb0-6fa7-11e6-9b84-62e52320ae6b.png)

- Stock Ledger
![4-stock ledger](https://cloud.githubusercontent.com/assets/20460498/18129188/3b3f0d4c-6fa7-11e6-8b08-97b0cbd50c20.png)

So it seems to be working fine, could you recheck on the latest version?

**Comment by komsel2228** [comment]
@PawanMeh em.. i am so confuse. 
i try in version erpnext 7.0.36 frappe 7.0.30 it's work. em...oke... 
thx for you feedback and i close this issue
