### ISSUE TITLE
[v7] Timesheets adjustments for billing

### ISSUE THREAD

**Issue by PawanMeh** [frappe/erpnext#6118]
- [ ] Add column for 'Adjustment Hrs' in timesheet detail.This can be shown only to 'Manager' or editable only by 'Manager'.

- [ ] While pulling in number of Hours for Invoice , logic should be to pull in sum of (Reported Hours+Adjustment Hours) for the timesheet.

**Comment by nabinhait** [comment]
Alternative:
Add a column called "Billling Hours" in timesheet detail, by default it should be same as adjustment hrs. And this column should be used for billing/invoice.

**Comment by PawanMeh** [comment]
@rohitwaghchaure ,while testing in beta i noticed the below issues:

- [ ] When I put "From Time" in the timesheet and save,the from time disappears

![screen shot 2016-08-29 at 8 04 28 am](https://cloud.githubusercontent.com/assets/20460498/18039319/59d718ec-6dbf-11e6-8edf-e42fe90a8369.png)

- [ ] "Billable Hrs" shows blank on Sales Invoice screen even after pulling the data from the timesheet
![screen shot 2016-08-29 at 7 59 33 am](https://cloud.githubusercontent.com/assets/20460498/18039346/b29100b0-6dbf-11e6-8d61-a5fc08baed45.png)
