### ISSUE TITLE
Job Application Link Broken

### ISSUE THREAD

**Issue by justinlusg** [frappe/erpnext#6121]
![image](https://cloud.githubusercontent.com/assets/12539216/17787153/84317720-65ba-11e6-88bc-775b5021f508.png)

The job application form used to be working until v7 update. Now when we click "Apply Now" the system will route to http://erp.agtech.com.sg/job_application?job_title=Admin%20Assistant (Admin Assistant is the Job Opening doc name). There will be error when there is a space in the URL (e.g. %20).

**Comment by KanchanChauhan** [comment]
@justinlusg The link you have provided seems to be working fine. Can you share the error screenshot or something.
<img width="1079" alt="screen shot 2016-08-19 at 11 52 19 am" src="https://cloud.githubusercontent.com/assets/16913064/17800763/7792f806-6603-11e6-8ea3-ea5eec63e03e.png">
