### ISSUE TITLE
ErpNext accounts root type defaults to Asset as from second child level?

### ISSUE THREAD

**Issue by gwtechbv** [frappe/erpnext#6122]
I'm setting up ERPNext: v7.0.27, Frappe Framework: v7.0.22 and come accross a problem in accounts, root type. 
At the first level child, the root type can be set to any of the 5 alternative choices.  However as from the  second level onwards, the root type defaults to Asset, although a different input (liability, equity, Income or Expense) at the New Account popup was set.

Please help, as this issue puts a hold on further setup!

Thanks for any help.
Gerard

**Comment by umairsy** [comment]
Gerard,

Please post this issue on forum.

https://discuss.erpnext.com

In the Github Issues, we mainly track feature suggestions.

**Comment by gwtechbv** [comment]
Dear Umair,
 
Please find below the link to 
 
https://discuss.erpnext.com/t/accouts-root-type-defaults-to-asset-as-from-second-child-level/15186
 
Thanks.
 
Met vriendelijke groet
Mit freundlichem Gruß
With best regards



Gerard Werdmūller
GWTECH bv
Postbus 566
3900 AN Veenendaal

tel +31 318 541369
Mob +31 653 195560
info@gwtech.nl
www.gwtech.nl
