### ISSUE TITLE
Ambiguous column issue in calendar (when using custom field) 

### ISSUE THREAD

**Issue by superlack** [frappe/erpnext#6123]
I have a link field named "project" in the Timesheet master for organization and billing reasons.  Since there is an identical field in the Timesheet Detail form, pulling up the Timesheet calendar throws an error.

`Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 36, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 879, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/projects/doctype/timesheet/timesheet.py", line 312, in get_events
    }, as_dict=True, update={"allDay": 0})
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 137, in sql
    self._cursor.execute(query, values)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1052, "Column 'project' in field list is ambiguous")`

The commit shows as referencing timesheet detail for project, but I don't know if it that means it has to be declared in the timesheet_calendar.js too. 

Commit: [Added a Calendar view for timesheet logs](https://github.com/frappe/erpnext/commit/ed1b8cfe3ff319558ca3aabdb6cc37747023da20)

Any way of specifying the doctype specifically to prevent the issue with overlap?

**Comment by nabinhait** [comment]
That is always a scope for such issues with same custom fieldname. How about renaming your custom field?

To rename your custom field create a new custom field with other name, copy the values from old field to new field and then delete the old field.

**Comment by superlack** [comment]
Hey, thanks for replying.  I tried deleting the "project" field in my timesheet master, but that didn't resolve the error.  I created a test project with new timesheet data that didnt utilize the custom field, and tried to filter down in calendar view to just that one entry, but it still resulted in the same message.  Am I required to drop the column in timesheet view?

**Comment by nabinhait** [comment]
@superlack Yes, you need to drop the column in the database. Because we don't drop column on deletion of any field from the web view.

**Comment by superlack** [comment]
Okay good stuff, is it possible to rename the column through the MySQL shell and then create the field with the new name in the web view?  

Otherwise, I'm assuming I would try something like:

ALTER TABLE tabTimesheet DROP COLUMN project; 

And a side question: Would you recommend a remote sql browser to connect to the database?

Thanks for the assistance!
