### ISSUE TITLE
[Develop]- Unable to "Preview Salary Slip' when using formula based salary 

### ISSUE THREAD

**Issue by PawanMeh** [frappe/erpnext#6130]
1. Created salary structure and components as shown below:

![screen shot 2016-08-21 at 6 44 28 pm](https://cloud.githubusercontent.com/assets/20460498/17837565/027af9ec-67d4-11e6-9709-86a86e8fa9f6.png)
![screen shot 2016-08-21 at 6 44 47 pm](https://cloud.githubusercontent.com/assets/20460498/17837568/1209917a-67d4-11e6-92ba-b3b8f09917b1.png)

2. Added formulae as show below:

![screen shot 2016-08-21 at 7 40 46 pm](https://cloud.githubusercontent.com/assets/20460498/17837691/352e523c-67d7-11e6-853b-24c5e8cd2efd.png)

3. Click on 'Preview Salary Slip' & enter the employee ID, click on 'Show Salary Slip' , nothing is generated
![screen shot 2016-08-21 at 6 44 28 pm](https://cloud.githubusercontent.com/assets/20460498/17837699/85de7324-67d7-11e6-95a3-d28f71e998d3.png)

![screen shot 2016-08-21 at 7 50 56 pm](https://cloud.githubusercontent.com/assets/20460498/17837730/ba8d75e2-67d8-11e6-86ca-d403b9236013.png)

**Comment by PawanMeh** [comment]
Was an issue with the update not being pulled properly on my machine..closing it for now

**Comment by KanchanChauhan** [comment]
@PawanMeh maybe pop ups were blocked.
