### ISSUE TITLE
[Develop] Preview Salary slip alignment issues

### ISSUE THREAD

**Issue by PawanMeh** [frappe/erpnext#6131]
- [ ] Working days,leave without pay,payment days should have the same alignment as Start date,end date
- [x] Currency symbol is misaligned
- [x] 'Salary Component' can be renamed to 'Component' 
- [x] If 'Default Amount' and 'Amount' are functionally the same, then we need not display 'Default Amount', just the calculated amount should be fine
![screen shot 2016-08-21 at 8 44 28 pm](https://cloud.githubusercontent.com/assets/20460498/17838061/549f7362-67e1-11e6-8d18-224294efa300.png)

**Comment by KanchanChauhan** [comment]
1st issue will be addressed here https://github.com/frappe/erpnext/issues/6227
