### ISSUE TITLE
[develop] Salary components using abbreviation in formulae are not shown on preview

### ISSUE THREAD

**Issue by PawanMeh** [frappe/erpnext#6133]
1. Set up salary structure as shown
![screen shot 2016-08-21 at 10 24 17 pm](https://cloud.githubusercontent.com/assets/20460498/17838572/14a7e732-67ee-11e6-8046-1afc8f8b24fc.png)

2. Set up formulae as shown below
![screen shot 2016-08-21 at 10 25 46 pm](https://cloud.githubusercontent.com/assets/20460498/17838576/3fa30c0a-67ee-11e6-8e96-3bbbebe3669e.png)

3. Preview salary slip, you will notice that components using the 'BS' abbreviation in calculation are not seen
![screen shot 2016-08-21 at 10 29 08 pm](https://cloud.githubusercontent.com/assets/20460498/17838595/b64b7784-67ee-11e6-93e7-656f13c63ab0.png)

**Comment by KanchanChauhan** [comment]
Did you manually set the abbreviation? Because Basic will probably have "B" as abbreviation.

**Comment by PawanMeh** [comment]
The help text says you can set up the abbreviation ,so was following that.If user cannot change or set the abbreviation then that field should not be editable and the help text needs to be modified appropriately.

**Comment by KanchanChauhan** [comment]
Sure you can. I am just asking to know if problem is when you set it yourself or with system generated abbreviation. But I was not able to replicate it in both the cases.

**Comment by PawanMeh** [comment]
I think it has something to with usage of the abbreviation in the formulae, could you check by setting up the formulae as suggested above in the replication steps?

**Comment by KanchanChauhan** [comment]
I tried above given formulae as well, worked for me.

**Comment by PawanMeh** [comment]
- I tried to replicate this in the beta instance, go to Salary structure TEST-AUG-SAL,run the preview for employee ID:EMP/0021
![screen shot 2016-08-23 at 9 55 30 am](https://cloud.githubusercontent.com/assets/20460498/17880381/cab8fd98-6917-11e6-91f3-ecdb501c03b3.png)

- The salary slip generated does not show amounts.

**Comment by rmehta** [comment]
@PawanMeh @KanchanChauhan  can you discuss this over chat 😄
