### ISSUE TITLE
[develop] Formula based salary help results in long vertical scroll

### ISSUE THREAD

**Issue by PawanMeh** [frappe/erpnext#6134]
- Currently the formula based salary help shows below salary component which leads to a long vertical scroll for the user and also a loss of context.
![screen shot 2016-08-21 at 10 32 32 pm](https://cloud.githubusercontent.com/assets/20460498/17838635/ad84e0b2-67ef-11e6-955c-d70fa7c35a0a.png)
![screen shot 2016-08-21 at 10 33 07 pm](https://cloud.githubusercontent.com/assets/20460498/17838751/81339f56-67f1-11e6-8bd7-95ae10726824.png)

- It would be nice if user can see help for 'Condition and formula' besides the 'Condition' & 'Formula',something like below:
![screen shot 2016-08-21 at 11 07 33 pm](https://cloud.githubusercontent.com/assets/20460498/17838836/25e1c594-67f4-11e6-93bd-d950f808bf6e.png)

**Comment by KanchanChauhan** [comment]
I tried it, it did not look very nice. It kind of broke the design consistency since it will span over other table.

**Comment by PawanMeh** [comment]
Since we are planning to introduce context specific help, maybe a NOTE to check the help link would suffice instead of this long scrollable text. Just a suggestion you can think upon.
