### ISSUE TITLE
Jinja Template not working for Standard Reply

### ISSUE THREAD

**Issue by justinlusg** [frappe/erpnext#6136]
![image](https://cloud.githubusercontent.com/assets/12539216/17844760/6fc8c060-686f-11e6-9900-04ce5112352a.png)

I get an error message when I try to add a standard reply. Please see above screenshot there is a {{doc.expiry_date}} field and an error will appear when I try to add the standard reply at the DocType.

> Traceback (most recent call last):
>   File "/home/ubuntu/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
>     response = frappe.handler.handle()
>   File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
>     execute_cmd(cmd)
>   File "/home/ubuntu/frappe-bench/apps/frappe/frappe/handler.py", line 36, in execute_cmd
>     ret = frappe.call(method, **frappe.form_dict)
>   File "/home/ubuntu/frappe-bench/apps/frappe/frappe/__init__.py", line 879, in call
>     return fn(*args, **newargs)
>   File "/home/ubuntu/frappe-bench/apps/frappe/frappe/email/doctype/standard_reply/standard_reply.py", line 18, in get_standard_reply
>     return frappe.render_template(standard_reply.response, doc)
>   File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/jinja.py", line 50, in render_template
>     return get_jenv().from_string(template).render(context)
>   File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
>     return self.environment.handle_exception(exc_info, True)
>   File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "
>

**Comment by justinlusg** [comment]
Any update for this bug?

**Comment by rmehta** [comment]
There might be an issue with your template. This is not a place to discuss customizations, try the forum https://discuss.erpnext.com

**Comment by justinlusg** [comment]
@rmehta but this is not a template issue. You can try to replicate the issue by adding `{{doc.name}}` in the standard reply. After you save the document and refresh the page, ERPNext will automatically insert in `{{ <a href="http://doc.name" rel="nofollow">doc.name</a> }}`
