### ISSUE TITLE
Reports to be downloaded on weekly and fortnightly basis also

### ISSUE THREAD

**Issue by yashgaglani** [frappe/erpnext#6137]
With respects to reports related to Cashflow, Profit & Loss, etc., it is generated as monthly, quarterly, half yearly and yearly. Would like you to add an option for weekly and fortnightly as well as we require for reporting purpose.

![image](https://cloud.githubusercontent.com/assets/21167836/17845696/71c0db4a-6861-11e6-9a32-f96c99634251.png)

**Comment by yashgaglani** [comment]
Instead add an option to select period from date to date.

**Comment by deepeshgarg007** [comment]
@yashgaglani This option is now available in latest version
