### ISSUE TITLE
Sales Invoice can save with out customer name

### ISSUE THREAD

**Issue by komsel2228** [frappe/erpnext#6138]
Dear Team ERPNext,
may be i found wrong or bugs, can help me to see that or explain to me.

A. i make 1 New Sales Invoice -- for example : SINV-00001
![screenshot from 2016-08-22 13-42-06](https://cloud.githubusercontent.com/assets/8717967/17846207/70090d1c-6871-11e6-8eae-37c42d02dc5f.png)
![screenshot from 2016-08-22 13-55-22](https://cloud.githubusercontent.com/assets/8717967/17846209/70103164-6871-11e6-8313-3bbdd72d2ad6.png)
![screenshot from 2016-08-22 13-44-11](https://cloud.githubusercontent.com/assets/8717967/17846204/70026174-6871-11e6-88c4-9d888963ed5e.png)

B. i make 1 New Sales Invoice -- for example : SINV-00002
![screenshot from 2016-08-22 13-45-35](https://cloud.githubusercontent.com/assets/8717967/17846206/70060324-6871-11e6-8a9e-a0e61cddd877.png)
![screenshot from 2016-08-22 13-55-37](https://cloud.githubusercontent.com/assets/8717967/17846205/7002bdfe-6871-11e6-8f92-9d6c20d9b262.png)

Why we can make, save and submit Sales Invoice with out Customer Name? can explain to me.
![screenshot from 2016-08-22 13-46-17](https://cloud.githubusercontent.com/assets/8717967/17846208/700b1436-6871-11e6-850d-5fcbf8e4bb54.png)

Thanks

**Comment by PawanMeh** [comment]
Based on accrual accounting system, you should not select Cash account while creating sales invoice, it should be debtors account. If you select debtors account , customer will be required

**Comment by komsel2228** [comment]
@PawanMeh oke...thanks for the explanation.
