### ISSUE TITLE
BUG: po_no field duplicate when there is a comma

### ISSUE THREAD

**Issue by justinlusg** [frappe/erpnext#6148]
Please look at "Customer's Purchase Order" field for both Sales Order and Delivery Note

SALES ORDER
![image](https://cloud.githubusercontent.com/assets/12539216/17850595/812b77e6-6890-11e6-9718-af3a166ec8cb.png)

DELIVERY NOTE
![image](https://cloud.githubusercontent.com/assets/12539216/17850599/85b4661a-6890-11e6-8858-220999507966.png)

The system will automatically duplicate the "Purchase Order's No" under Delivery Note when there is a comma added in the Sales Order page for the same field.

**Comment by PawanMeh** [comment]
![screen shot 2016-08-29 at 5 14 14 pm](https://cloud.githubusercontent.com/assets/20460498/18050416/185e22aa-6e0c-11e6-86dd-9cb9b1414683.png)

![screen shot 2016-08-29 at 5 14 35 pm](https://cloud.githubusercontent.com/assets/20460498/18050431/2b9e0e52-6e0c-11e6-82d4-08d7ba5c4968.png)
