### ISSUE TITLE
"Quotation to Customers" from "Quotations from Supplier"

### ISSUE THREAD

**Issue by mosabamf** [frappe/erpnext#6154]
In our Business process we always issue "Quotation to Customers" after we receive Quotations from Supplier, unfortunately we couldn't make Quotation or get items from "Quotations from Supplier"

**Comment by PawanMeh** [comment]
Please refer to [Request For Quotation](https://frappe.github.io/erpnext/user/manual/en/buying/request-for-quotation) help

**Comment by mosabamf** [comment]
Thanks dear, my point is After added Supplier  Quotation, How can I use it to generate "Quotation to Customer" after adding my margin

**Comment by strixaluco** [comment]
Please post questions to [discuss.erpnext.com](https://discuss.erpnext.com)

**Comment by uzairahsan** [comment]
Hi, I have a same situation. Was this resolved somehow ? Any help on this will be appreciated.
Customer Quotation -------> Supplier Quotation + Margin
