### ISSUE TITLE
CRM Communication Form - Important links and fields needed

### ISSUE THREAD

**Issue by mosabamf** [frappe/erpnext#6155]
CRM: in Communication Form I guess you to need to work on it a little bit, I've some suggestions:   

- [ ] A. In TO/WITH field; communication should be linked to Contact's Masters include his all details "email, phone, organization, ..etc" this will ease followup Activities made per Contact Person and Organization

- [ ] B. Activity Duration to be added to track and analyse time spent with customers vs different activities and then against income achieved from him

- [ ] C. I highly recommend Subsequent Todo or Communication with time alarm and or Todo notification if the current commutation result inquired a subsequent activity
    (e.g. after visiting a customer he inquired to send him some docs when been received for third party within 3 days from the meeting)

- [ ] D. Add strong Communication Analysis Reports to Track all communications details like "Communication per Organization, Communication per Contact​, 
Communication​ ​​type analysis​,  Communication​-Sales person Analysis,​Customer's ​Purchases​ Vs Communication​​ ....etc,  you can adopt too many​ ​report​​.​

**Comment by AleCVERP** [comment]
I agree with all the suggestions ok mosabamf
