### ISSUE TITLE
Payment still can be made even after 100% of Advanced Payment in v7

### ISSUE THREAD

**Issue by addymuliady** [frappe/erpnext#6159]
Hi there!

With reference to the following manual,
https://frappe.github.io/erpnext/user/manual/en/accounts/advance-payment-entry.html

I think the Advance Payment can be done directly from Purchase Order.
Is the journal entry for Advance Payment still relevant? If not, can have it removed as it is confusing.

Also, after I have completed the payment, the system will still allow user to make payment.
For example, 1st payment made 50%, 2nd payment made 50%. By right, user should not be able to make another payment as payment is completed. However, I can still make payment.

Thanks!

**Comment by PawanMeh** [comment]
Payment entry is not blocked,but the amount you pay does not get allocated to PO and remains unallocated.

![screen shot 2016-09-03 at 7 41 50 pm](https://cloud.githubusercontent.com/assets/20460498/18225421/8ce69e62-720e-11e6-953b-6e9ed63615cc.png)

**Comment by addymuliady** [comment]
Hi Pawan!

Thanks! Is there any reason or scenarios for this?

As a user, I think it is better for payment entry to be blocked to prevent future journaling and human error.

Warm Regards

Get Outlook for Android<https://aka.ms/ghei36>

**Comment by PawanMeh** [comment]
I have a few questions for the scenario you are trying:

1) I think you are not receiving anything against the PO before paying, would you pay 100% amount without receiving?
2) Would you pay without a purchase invoice?

You can let us know step by step screen shots and then maybe we can say weather the scenario you are trying is valid from a business perspective.

Thanks
Pawan

**Comment by addymuliady** [comment]
Hi

Just had another thought on this.

There might be a scenario where a customer "overpaid" via transfer or cheque.

Can the overpaid amount be:

1) Adjustment on credit limit if customer is on credit limit
2) if customer is not on credit limit, be on offset on customer later purchases?

Thanks!

**Comment by PawanMeh** [comment]
I think in v11 when you can make a payment entry without an invoice and it treats it as an advance. Kindly check and if the issue persists, you can re-open.
