### ISSUE TITLE
BOM Rate of Materials didn't auto update

### ISSUE THREAD

**Issue by addymuliady** [frappe/erpnext#6160]
When creating BOM, the rate of materials only shows after you have saved the document.

**Comment by PawanMeh** [comment]
Unable to replicate this, can you provide step by step screen shots?

**Comment by addymuliady** [comment]
Hi @PawanMeh I think my app wasn't updated. After I updated it seems fine. Set a price list for my raw material and on BOM, Rate Of Materials Based On is set to Price List.

Just to understand, valuation rate is based on stock valuation?

What do you think is the best practice?

**Comment by PawanMeh** [comment]
Please refer to the valuation help [here](https://frappe.github.io/erpnext/user/manual/en/manufacturing/articles/valuation-based-on-field-in-bom)

About best practice it depends on the nature of business like trading or manufacturing etc. I would suggest you can post such queries on [discuss](https://discuss.erpnext.com)
