### ISSUE TITLE
Material Transfer - Stock Balance not updated

### ISSUE THREAD

**Issue by addymuliady** [frappe/erpnext#6161]
Hi there,

I did a Material Transfer under Stock Entry from Main Warehouse to Repack Warehouse but the Stock Balance still indicates the same in the Main Warehouse.

![image](https://cloud.githubusercontent.com/assets/21187126/17912850/f3d886d8-69c8-11e6-8464-1d536a6248f8.png)

**Comment by PawanMeh** [comment]
Check source warehouse you entered while making the repack entry. You need to choose correct source warehouse,if issue still persists share step by step screen shots

**Comment by addymuliady** [comment]
Thank you @PawanMeh! Got it!
