### ISSUE TITLE
company in quotation cannot be changed or selected

### ISSUE THREAD

**Issue by omnison** [frappe/erpnext#6163]
ERPNext: v7.0.32
Frappe Framework: v7.0.27

Two issues:
1. company in quotation cannot be changed or selected
2. Error happen when save quotation: Billing currency must be equal to either default comapany's currency or party account currency

These two issue happened after my upgrade. 

<img width="1216" alt="2016-08-24 10 01 58" src="https://cloud.githubusercontent.com/assets/7886153/17919904/ff13e470-69e1-11e6-8fdd-cfd2229e417f.png">

**Comment by nabinhait** [comment]
Fixed in the latest release, thanks for reporting :)
