### ISSUE TITLE
Cost Center can not be selected

### ISSUE THREAD

**Issue by komsel2228** [frappe/erpnext#6164]
Dear ERPNext Team,
in this version:
ERPNext: v7.0.32
Frappe Framework: v7.0.27

Cost Center can not be selected  in Delivery Note, Purchase Receipt, Purchase Invoice, Sales Invoice, etc.
![screenshot from 2016-08-24 13-39-14](https://cloud.githubusercontent.com/assets/8717967/17920951/9f2fb686-6a01-11e6-9454-e0613a88f83b.png)
![screenshot from 2016-08-24 13-37-16](https://cloud.githubusercontent.com/assets/8717967/17920952/9f33f390-6a01-11e6-9435-3e2e3500b17d.png)

thanks for fix that.

**Comment by rmehta** [comment]
Thanks for reporting :)

**Comment by komsel2228** [comment]
yeah!! thanks rmetha and nabin ^^
