### ISSUE TITLE
Cannot Create Quotation from Lead

### ISSUE THREAD

**Issue by ai-erp** [frappe/erpnext#6167]
We tried directly creating quotation from Lead by clicking from MAKE button.
but below error is coming:

![error message - making quotation from lead](https://cloud.githubusercontent.com/assets/16744099/17938211/08183356-6a36-11e6-9f33-7949795f0756.png)

we have customize our source selection and shop is included in that list.
But this error is coming...
Can anyone check what is the problem?

On the other hand, we can make quotation directly from document type quotation and selecting the same lead.

thank you....

**Comment by komsel2228** [comment]
i use ERPNext: v7.0.32 Frappe Framework: v7.0.28 (standard with out modification) i can create quotation from lead. its run and good..

are you customize, add and link a Doctype if anyone select "Shop" in source? Can you share/screen shoot your "Lead"

**Comment by ai-erp** [comment]
hi @komsel2228 , currently we are on ERPNext: v7.0.31 and Frappe Framework: v7.0.25...
below is the screenshot of our lead:

![lead](https://cloud.githubusercontent.com/assets/16744099/17959157/96a52498-6aaf-11e6-8233-3bb03fce8717.png)

**Comment by komsel2228** [comment]
![screenshot from 2016-08-25 17-15-06](https://cloud.githubusercontent.com/assets/8717967/17965636/d1b2e6dc-6ae7-11e6-9ca6-37f20c17ba1d.png)
![screenshot from 2016-08-25 17-15-50](https://cloud.githubusercontent.com/assets/8717967/17965635/d1aa5152-6ae7-11e6-9974-a26fa0f2fe64.png)
![screenshot from 2016-08-25 17-16-00](https://cloud.githubusercontent.com/assets/8717967/17965634/d1a6c12c-6ae7-11e6-9dfc-e2b2fa2cd8e9.png)

**Comment by ai-erp** [comment]
@komsel2228 , have you tried creating quotation from "make " button in lead?

**Comment by me2ne** [comment]
i see this bug in system too . 
on this way @komsel2228 you make quot is working , bug when you open lead or add new lead  and click make and then click quotation , then , it's not work , i think it's should report as bug

**Comment by komsel2228** [comment]
@ai-erp  yes.. i try that. its work.
if you add "shop" in lead, you should add "shop" too in quotations, sales order, delivery note, sales invoice.
i think its simple way with out coding.

**Comment by me2ne** [comment]
what do you mean : "you should add "shop" too in quotations, sales order, delivery note, sales invoice" ??

**Comment by cgpurbaugh** [comment]
This is because 'Source' gets pulled to 'Source' in Quotation, and the options don't line up.  I'll send a PR shortly.

**Comment by ai-erp** [comment]
hi, this means that Source selection in lead and other Doctypes related to these transactions should be same, right?

**Comment by komsel2228** [comment]
@ai-erp  yes. its right.
