### ISSUE TITLE
Unable to click on selection in Link Field

### ISSUE THREAD

**Issue by cgpurbaugh** [frappe/erpnext#6175]
![lead field problem](https://cloud.githubusercontent.com/assets/13136405/17978721/5c3bf398-6ac5-11e6-99d5-831fea657697.gif)

I know you can't tell when I clicked, but I did 4 times.
This particular field was the Company Field in Opportunity.  This is the second time we've come across this, but I can't remember what field it was the first time.  

This also appeared in the Project field filter.

**Comment by superlack** [comment]
Also having an issue with link fields.  In child tables (ex Timesheet "Activity Type", Sales Invoice "Item").

The dropdown list doesn't appear at the front, instead the faint shadow of the list is visible at the bottom of the field being entered.  Predictive typing doesn't function either.

**Comment by komsel2228** [comment]
same like this:
company in quotation cannot be changed or selected #6163 
Cost Center can not be selected #6164

should be fixed in the next version

**Comment by rmehta** [comment]
These are already fixed. Can you update once more and confirm?

**Comment by komsel2228** [comment]
@rmehta  yup..after bench update, its already fixed and run.. thanks
