### ISSUE TITLE
Manufacturing module needs a change

### ISSUE THREAD

**Issue by Niville** [frappe/erpnext#6182]
Hi guys ,

The manufacturing module doesnot allow the materials to get transferred until all the process mentioned in the BOM gets completed . Ideally this is not correct . The actual thing is , one operation will take place in one warehouse and the other operation in the next warehouse , so practically this is wrong .

Kindly change this validation .

**Comment by PawanMeh** [comment]
- Create a production Order

![1-production order](https://cloud.githubusercontent.com/assets/20460498/18092378/adf70a42-6ee9-11e6-9447-56757d163331.png)

- Change quantity to accordingly after clicking finish. You need not complete the entire quantity in one go if you have items being manufactured in different warehouses as part of a BOM, the production order would remain in progress.

![2-rename](https://cloud.githubusercontent.com/assets/20460498/18092381/b138b05c-6ee9-11e6-8a9e-9af9bba2cffc.png)

- Appropriate stock entry is generated.

![3-stock entry](https://cloud.githubusercontent.com/assets/20460498/18092385/b3e83390-6ee9-11e6-86b4-5317895f6cbd.png)

Hope this would resolve your scenario

**Comment by creamdory** [comment]
Already implemented. Can transfer stocks multiple times for a Production Order.

<img width="571" alt="screen shot 2018-03-15 at 11 03 10" src="https://user-images.githubusercontent.com/21003054/37457012-10f6cecc-2841-11e8-9ed7-1d8cd555e6e2.png">
