### ISSUE TITLE
barring a warehouse for a particular item

### ISSUE THREAD

**Issue by maheshengg** [frappe/erpnext#6184]
How to "bar" "ban" a particular item from being inwarded or outwarded from a specific warehouse ?

**Comment by joezsweet** [comment]
👍

**Comment by maheshengg** [comment]
any ideas on this ?

**Comment by yadavyk** [comment]
Please refer : [Putaway Rule](https://docs.erpnext.com/docs/v13/user/manual/en/stock/putaway-rule)
