### ISSUE TITLE
No permission to read DocType for account user

### ISSUE THREAD

**Issue by kxt5258** [frappe/erpnext#6189]
The error is thrown for account user role when viewing "Bank Clearance Summary" and "Payment Period Based On Invoice Date" reports

**Comment by PawanMeh** [comment]
Please share screen shot of the error you are facing

**Comment by nabinhait** [comment]
It is a permission related issue. Check Browser's Console, you will get an idea for which doctype user is not permitted.

**Comment by Craftint** [comment]
@PawanMeh 
![image](https://user-images.githubusercontent.com/67686213/174027609-513074fb-be1c-4b7a-95ea-1d629a47d7fe.png)


@nabinhait 
It is not related to particular doctype. It is the permission to read 'Doctype' doctype itself.
One of the columns in this report is a link field to doctype.
columns = [
    {
      "label": _("Payment Document Type"),
      "fieldname": "payment_document_type",
      "fieldtype": "Link",
      "options": "Doctype",
      "width": 130,
    },

Apart from system manager, who can access it then?
It should be available for non admin users.
