### ISSUE TITLE
"Make Sales Invoice" from Timesheet list view.

### ISSUE THREAD

**Issue by superlack** [frappe/erpnext#6194]
Using the filters in list view is the only practical way of viewing multiple timesheets, but since the removal of Time Logs and Batches, there's a missing workflow to direct timesheets to an invoice.

**Comment by Arundhatii** [comment]
Closing the issue as no other request received for this or similar feature. Feel free to re-open if you think its important.

**Comment by superlack** [comment]
i did try to work on it, but during the same time the importing of unbilled time sheets was introduced upon selecting a project in invoice, so that was big help.  I may add it later on, but in the meantime, an issue is not necessary.

Thanks
