### ISSUE TITLE
Improve accounting related messages to users

### ISSUE THREAD

**Issue by PawanMeh** [frappe/erpnext#6195]

**Comment by rmehta** [comment]
@PawanMeh specify the messages!

**Comment by PawanMeh** [comment]
- [ ] "Cost Center is required for 'Profit and Loss' account Telephone Expenses - WP" on journal entry.This message gives the user what is missing but not what he should do to rectify this. For eg, it could be "Cost Center is required for 'Profit and Loss' account Telephone Expenses - WP.Please set up default Cost Center by navigating to:Set Up > Company "

- [ ] "Party Type is required" on Sales invoice and Purchase Invoice. This has been changed to used the words "Customer" and "Supplier" as there is no such thing as party type on Sales invoice and Purchase Invoice screens. @nabinhait assuming this is already pushed to develop branch

@rmehta above are some examples, I plan to keep adding to this list and pushing improvements like this whenever I find them.
