### ISSUE TITLE
Additional Discount Amount can't be refresh automatically

### ISSUE THREAD

**Issue by komsel2228** [frappe/erpnext#6199]
Dear ERPNext Team,
i found "Additional Discount Amount" in "Purchase Receipt",and "Delivery Note" can not be refresh automatically with new calculation.
for the example:
![capture1](https://cloud.githubusercontent.com/assets/8717967/18042679/e892b8b6-6dec-11e6-8e35-576cd94ebce2.PNG)
![capture2](https://cloud.githubusercontent.com/assets/8717967/18042682/e8aeb6a6-6dec-11e6-9093-6e043b92bf9b.PNG)
![capture3](https://cloud.githubusercontent.com/assets/8717967/18042678/e888180c-6dec-11e6-968a-b071c50af58f.PNG)
![capture4](https://cloud.githubusercontent.com/assets/8717967/18042684/e8d385da-6dec-11e6-8be0-b27a3229a7c3.PNG)
![capture5](https://cloud.githubusercontent.com/assets/8717967/18042681/e8a4a30a-6dec-11e6-92b7-c17a19317aa7.PNG)
![capture6](https://cloud.githubusercontent.com/assets/8717967/18042680/e898bb3a-6dec-11e6-82cd-1ffba33e93c6.PNG)
![capture7](https://cloud.githubusercontent.com/assets/8717967/18042683/e8b496ac-6dec-11e6-93fc-e4a6b003ed11.PNG)

**Comment by PawanMeh** [comment]
Please try to save the document in 'Draft' status and see if calculation works correctly.You can change the document many times in Draft status and save before submitting.

**Comment by komsel2228** [comment]
![screenshot from 2016-08-29 20-47-57](https://cloud.githubusercontent.com/assets/8717967/18054162/eb6e3eee-6e2c-11e6-8c93-692621d58415.png)
![screenshot from 2016-08-29 20-52-53](https://cloud.githubusercontent.com/assets/8717967/18054161/eb664784-6e2c-11e6-847c-5d3d9320d43f.png)
![screenshot from 2016-08-29 20-57-25](https://cloud.githubusercontent.com/assets/8717967/18054163/eb72bc30-6e2c-11e6-9d2e-543ee31a2666.png)

can "Additional Discount Amount" recalculated automatically with out select / choice again "Apply Additional Discount On" ?
