### ISSUE TITLE
Payment advances not pulling through to Sales Invoices

### ISSUE THREAD

**Issue by TogoBuSo** [frappe/erpnext#6200]
When converting a sales order to an invoice with advance payments using the new payments received entry the entries are pulled through. However for legacy entries using Journal Entries for advance payments, they are not pulled through.

ERPNext: v7.0.32
Frappe Framework: v7.0.27

**Comment by PawanMeh** [comment]
Hi,

I followed the below steps to replicate

1. Created journal entry with advance and created invoice , when I used the payment reconciliation tool I see both the entries. 

![screen shot 2016-08-30 at 6 06 45 pm](https://cloud.githubusercontent.com/assets/20460498/18089261/a7515d94-6edc-11e6-9d1a-53b0b458b984.png)

We are unable to replicate,Could you specify more details with screen shots about your issue

**Comment by TogoBuSo** [comment]
Hi

My business operates on a "lay-away" basis. Customers place orders and make
payments against those orders. Once the order is fully paid, an invoice is
generated and the goods dispatched.

The process flow is as follows:

New Sales Order > Advance Payment 1 > Advance Payment x > Make Sales
Invoice.

In version 5 of the application, the journal entries with the advance
payments were pulled through to the invoices when the Sales Orders were
converted. However after the upgrade to 7 only the entries made via
payments are pulled through to the invoices. The result is that there is a
manual process now to cancel the old payments and change the references to
the invoices generated.

Satish

**Comment by PawanMeh** [comment]
We have tried replicating your scenario , created sales order > Advance payments > Sales invoices and entries were pulled in as shown below:

![screen shot 2016-08-31 at 1 03 45 pm](https://cloud.githubusercontent.com/assets/20460498/18120101/94e757c2-6f7b-11e6-88e1-0bc4aa874fcc.png)
