### ISSUE TITLE
Error: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://erpnext.com' is therefore not allowed access.

### ISSUE THREAD

**Issue by nick9822** [frappe/erpnext#6201]
Hi Developers,

I am getting an error while calling an API of different url than erpnext.com
`Error: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://erpnext.com' is therefore not allowed access.`

I think there is issue of Cross-Origin Resource Sharing (CORS). Can it solved or any workaround to the same? Please advice.

I made it work by using chrome extension to allow CORS, but user can be on any browser other than chrome.

Thanks,
Nick

**Comment by rmehta** [comment]
How do you replicate this?

**Comment by nick9822** [comment]
@rmehta I just made a call to 
` $.ajax({
          url: "https://httpbin.org/get",
          success: function(response) {             
              console.log(response);
            }               
        })`

and it went fine. So Is there a problem with API host?

Thanks.

**Comment by rmehta** [comment]
Most likely, the host (marinetraffic.com) is not allowing cross reference calls.
