### ISSUE TITLE
POS Payment For IDR Currency

### ISSUE THREAD

**Issue by haiyang89** [frappe/erpnext#6203]
My company currency is IDR. and i create POS Profile for retail. when i do payment, the amount is still follow USD Format.

**Comment by rohitwaghchaure** [comment]
Hi @haiyang89 
Can you share screenshots

**Comment by haiyang89** [comment]
1. Go to **Global Setting** Setup the Currency to IDR
![image](https://cloud.githubusercontent.com/assets/21308275/18075406/ba087b5e-6e9e-11e6-8d12-44ae2b1a892b.png).

2. Go to **System Setting**, setup the format number to #.###,## (Indonesia format number)
![image](https://cloud.githubusercontent.com/assets/21308275/18075449/10db24f4-6e9f-11e6-8596-28614a83831f.png)

3. Create a POS profile.
I will skip the screen shot of this one,  because not related.
4. Open POS, make some transaction then **pay**. Then i input the case amount. However the system not get the value correctly to field "Paid". you can see the screen. the value of cash not equal to paid. it is because the format numbering.
![image](https://cloud.githubusercontent.com/assets/21308275/18075513/983ee886-6e9f-11e6-9da0-39d2903fa400.png)

**Comment by rohitwaghchaure** [comment]
Hi @haiyang89 ,
We have fixed this issue, we'll release it soon.
