### ISSUE TITLE
Supplier Quotation (created online) should be visible to Supplier from Portal

### ISSUE THREAD

**Issue by Devens** [frappe/erpnext#6205]
We were trying RFQ utility from V7. It's wonderful and very useful utility. 

We suggest that Supplier Quotation (created by adding value in RFQ online) should be visible to Supplier after he has submitted the same. (Presently we could not find any link form where supplier can see the quotation which created by him). 

![image](https://cloud.githubusercontent.com/assets/10671911/18051337/6ab36646-6e11-11e6-8604-d0f0731d27bf.png)

**Comment by rmehta** [comment]
@rohitwaghchaure can you check the broken rupee symbols too!
