### ISSUE TITLE
Feature Request: Fees Module - Include Concession Amount

### ISSUE THREAD

**Issue by umaepoch** [frappe/erpnext#6208]
Hi,

Just wanted to check about something. There are cases in the school
where the school authorities have to give concession on the fees. It
could be because of RTE or Economically weak section or because of
students being the children of the staff, or some such thing. I tried
creating custom fields inside the Program Fees doctype and was able to
give concession, and the Program fees also reflected the discount given.
But, when I submitted the form, the Fees created was again showing the
original fees. On checking the py files, found out that the api.py is
picking up the records from the original fee structure.

Is there any way that I can create concession fields and give concession
on the actual fees amount? If I have to customize, where should I do it?
At the Program fees level or at the Fees level? In the Fees level, I
notice that the form is already submitted and I cannot make any changes,
other than Collect the Fees.

Please advise.

Thanks
Uma
________________________________________________________________________________
@UmaG You will have to customize at the Program Enrollment level. Maybe also add a field in the Program Master Fees table to store the Category for which the fees applies.

Also raise a feature request on Github. Maybe we can add this as a feature.

**Comment by umaepoch** [comment]
Hi,

I got a message saying that this feature request is merged with 6245. But,
I don't see the details of my request on that. Can you please advise?

Thanks
Uma

**Comment by neilLasrado** [comment]
@umaepoch we have introduced a new field student category. You can set fee structures against student categories and in program enrollment in selection of student category the respective fees as per the program master will be fetched.

**Comment by umaepoch** [comment]
Thanks Neil. Will check that out and get back to you.. :-)

**Comment by umaepoch** [comment]
Hi Neil,

I created a fees structure for a particular program with Student Category as RTE. While creating a new Program enrollment for a student, when I am selecting RTE under Student Category and the program code, it is not displaying the fee components automatically. Am I missing out on anything?

The code in the api.py file shows:

def get_fee_structure(program, academic_term=None):
        """Returns Fee Structure.

        :param program: Program.
        :param academic_term: Academic Term.
        """
        fee_structure = frappe.db.get_values("Fee Structure", {"program": program,
                "academic_term": academic_term}, 'name', as_dict=True)
        return fee_structure[0].name if fee_structure else None

@frappe.whitelist()
def get_fee_components(fee_structure):
        """Returns Fee Components.

        :param fee_structure: Fee Structure.
        """
        if fee_structure:
                fs = frappe.get_list("Fee Component", fields=["fees_category", "amount"] , filters={"parent": fee_structure}, order_by= "idx")
                return fs

**Comment by HoFaks** [comment]
This feature is very important and no school can operate without it, as it is constantly changing throughout the year
We look forward to including this feature more flexibly in the future
Thanks
