### ISSUE TITLE
[v7] Error at Text Editor (Description) in Expense Claim

### ISSUE THREAD

**Issue by ASneha1** [frappe/erpnext#6219]
At times, the Text Editor (Description) in Expense Claim appears as such, without text edit options, just as a text box : 
![image](https://cloud.githubusercontent.com/assets/16811259/18072589/18d785ba-6e92-11e6-8477-77529b0f1d35.png)

**Comment by PawanMeh** [comment]
![screen shot 2016-08-30 at 9 08 04 am](https://cloud.githubusercontent.com/assets/20460498/18075320/5c757bde-6e91-11e6-8032-b6d070b1d5e1.png)

Unable to replicate this, have you tried to clear your browser cache ? And reload?

**Comment by ASneha1** [comment]
Hi Pawan, 

It is usually after we attach an Image to the Expense Claim row. Save it. 
And we reload and edit at Editable Data : 
![image](https://cloud.githubusercontent.com/assets/16811259/18339511/82be9206-75d2-11e6-985c-d92ed0454740.png)

And when we open up, 
![image](https://cloud.githubusercontent.com/assets/16811259/18339485/56e53e82-75d2-11e6-8ecf-3e6de4dd9c4e.png)

Thank you.

**Comment by PawanMeh** [comment]
We generally recommend to use the attach file button

![screen shot 2016-09-08 at 3 47 23 pm](https://cloud.githubusercontent.com/assets/20460498/18346187/ae2c8290-75dc-11e6-96ec-2f5d602e7535.png)

**Comment by ASneha1** [comment]
Hi @PawanMeh, 

Thank you. That is how we usually use it for other doctypes but for expense claim, it is preferred that the users attach the bill for each expense claim row at the row itself. This will make it straightforward to identify which expense the bill (attachment) is for.

Hope that provides a better understanding of the use case.

**Comment by PawanMeh** [comment]
I do understand the use case but from the description of the issue you have projected it as a bug in the system.I think this is not a bug and as a work around you could try to attach multiple files using the button instead of writing something in the description.

If it is very critical, then you can raise a paid development request for it.
