### ISSUE TITLE
One POS Profile can't have multiple item price list for different customer

### ISSUE THREAD

**Issue by haiyang89** [frappe/erpnext#6220]
Hi Master, I have a question. Lastly i tried one POS profile and default POS price list is using standard selling pricelist. Then i create two customer, One of the customer using standard selling price list and the other one is reseller pricelist. After that, i tried to create transaction in POS. when i change the customer to reseller. the price of the item didn't change to reseller. Kindly advise.

![image](https://cloud.githubusercontent.com/assets/21308275/18075652/e1e578a0-6ea0-11e6-923e-c2ad5fca244a.png)

Thanks you.

**Comment by rohitwaghchaure** [comment]
Hi @haiyang89 
For this case you need to use sales invoice instead of POS.

**Comment by haiyang89** [comment]
How to treat member concept in POS, customer A for item XXX the price is 500. and because customer B is member than the price for item XXX the price is 480. i think i can't ask cashier input sales invoice in retail shop.
