### ISSUE TITLE
[Frappe 7.1] Could not find print language english

### ISSUE THREAD

**Issue by manqala** [frappe/erpnext#6225]
Hello,

It seems the updates related to languagues in 7.1 have caused some regressions. Please see errors that I experience in my 7.1 system when trying to create an invoice and sign-up on the website respectively.

![image](https://cloud.githubusercontent.com/assets/21128143/18099758/fa266ae8-6edf-11e6-87e0-2b71ae7d719e.png)

![image](https://cloud.githubusercontent.com/assets/21128143/18099822/40fd93a6-6ee0-11e6-8f95-d474166635fd.png)

Regards,
cksgb

**Comment by ravi-modi** [comment]
I am getting same error when trying to make Lead into Customer & save the record.  I have done run bench update  &  done latest updates.
