### ISSUE TITLE
Printing Balance Sheet and Profit and Loss, too many columns error

### ISSUE THREAD

**Issue by addymuliady** [frappe/erpnext#6230]
Hi

When I am printing Balance Sheet and PNL ... if I decided to print in months, it prompts me that I have too many columns

![image](https://cloud.githubusercontent.com/assets/21187126/18123663/77f3799a-6fa1-11e6-86d0-b055378a494c.png)

**Comment by PawanMeh** [comment]
This restriction is in place because of UI reasons, You can use Menu to export the report in such cases.
