### ISSUE TITLE
delete default company details from erpnext

### ISSUE THREAD

**Issue by ashinkk675** [frappe/erpnext#6234]
i had configured erp next on server. logged in  with UN & PW. there is already a company available (Bitnami)with some transactions. i wanted to delete the company as well as transactions. pl help me out.

when i am trying to delete the company transaction, it shows like below. 

Transactions can only be deleted by the creator of the Company
You do not have enough permissions to access this resource. Please contact your manager to get access.

**Comment by rmehta** [comment]
@ashinkk675  please post help queries on https://discuss.erpnext.com
