### ISSUE TITLE
Can't print project 

### ISSUE THREAD

**Issue by superlack** [frappe/erpnext#6239]
User is unable to select "Print" from the menu in a project document, and user is unable to print from list view (no checkboxes in list, only the "favourited" heart symbol)

**Comment by rohitwaghchaure** [comment]
@superlack 
Seems they don't have permission for print, check role permission manager.
I have checked on local setup and it's working properly, check below image
![project](https://cloud.githubusercontent.com/assets/8780500/18182749/e28dc766-70ae-11e6-95ff-63005e5bfa20.png)

![1](https://cloud.githubusercontent.com/assets/8780500/18182952/b79f6194-70af-11e6-827b-16c10fd9720b.png)
![2](https://cloud.githubusercontent.com/assets/8780500/18182953/b7a42c24-70af-11e6-9e9e-9019a051f26a.png)
![3](https://cloud.githubusercontent.com/assets/8780500/18182954/b7a75afc-70af-11e6-82bb-2cee180853dd.png)

**Comment by superlack** [comment]
Oh, now I feel like an idiot. Sorry, and thanks!
