### ISSUE TITLE
Report General Ledger not found

### ISSUE THREAD

**Issue by kagabuisa** [frappe/erpnext#6244]
Hullo am using erpnext 6.27, however I can not access the general ledger, when I click on its link this the message the system gives "Report General Ledger not found" & "Not found"

Please assist resolve this issue, thanks

![general ledger](https://cloud.githubusercontent.com/assets/20890769/18160959/79c6a53e-7038-11e6-984c-53854c466d64.jpg)

**Comment by PawanMeh** [comment]
Could you check your permissions and roles?

**Comment by kagabuisa** [comment]
thanks for response, which permissions or roles in particular do I check sir,

**Comment by PawanMeh** [comment]
Could you send a screen shot of the user in question and the roles they have from Set Up > User ?

**Comment by kagabuisa** [comment]
![roles](https://cloud.githubusercontent.com/assets/20890769/18161642/7295e240-703b-11e6-83e7-4b5142b84196.jpg)

**Comment by PawanMeh** [comment]
Are you able to run the report with Admin User?

**Comment by kagabuisa** [comment]
No i cant, because I having been using the admin user all the time

**Comment by PawanMeh** [comment]
Since this is an older version, I would suggest you post this query on [discuss](discuss.erpnext.com).
