### ISSUE TITLE
"General Ledger" Print, PDF issue

### ISSUE THREAD

**Issue by Devens** [frappe/erpnext#6247]
When we print "General Ledger", it shows correctly in Portrait. But, when we try to generate PDF, it gets distorted (see Letterhead portion & it gets converted into landscap). Please see following screen shots. 

![image](https://cloud.githubusercontent.com/assets/10671911/18164160/0b777c1a-705c-11e6-96c2-38602975d4a5.png)

![image](https://cloud.githubusercontent.com/assets/10671911/18164164/0ff28ac8-705c-11e6-9eca-de9609b5286c.png)

![image](https://cloud.githubusercontent.com/assets/10671911/18164171/1618a090-705c-11e6-8977-71c42f42cc42.png)

**Comment by ai-erp** [comment]
hi, same with our ErpNext V7... Menu>Print is showing Portrait but Menu>PDF is showing landscape...
Currently, what I am doing is printing SOA on PDF to save it in PDF format....

**Comment by netchampfaris** [comment]
Added configurable orientation for pdf frappe/frappe#2358
