### ISSUE TITLE
Inter-company sales and stock transfers

### ISSUE THREAD

**Issue by dzenou** [frappe/erpnext#6251]
Hello,

The reason I’m raising this issue is that I have replicated our group of Companies (there are 4) structure in ERPNext and have applied the different Sales cycles that we have in place from Customer Sales order until delivery using the different Companies. Everything works fine as long as the cycle is direct, i.e. Customer orders to Company A, Company A orders to Supplier, Supplier delivers quantity, Company delivers Customer. 
Where I seem to be stuck, is when we have intercompany sales transactions, i.e. Customer orders to Company A, Company A orders to Company B, Company B orders to Supplier, Supplier delivers quantity to Company B, Company B delivers to Company A but then Company A cannot deliver to Customer because the stock does not seem to be there.

I believe this is somewhat similar to the topic discussed under https://discuss.erpnext.com/t/transfer-material-from-one-company-to-another/8350/18 although I think the main reason is that the setup does not allow a Company to also be a Customer and/or Supplier and therefore as a Customer has no access to the Company warehouse stock as there is no link.

As a workaround I am setting up the 4 Companies as Customers and as Suppliers but this means that I cannot track inter-company stock movements. Thanks for looking into adding this feature.

**Comment by rmehta** [comment]
> Thanks for looking into adding this feature. 

You can sponsor this if you looking to build this quickly!

**Comment by rohitwaghchaure** [comment]
Hi @dzenou 

Mockup design:
![screen shot 2016-11-04 at 3 23 37 pm](https://cloud.githubusercontent.com/assets/8780500/20001548/b599282e-a2a2-11e6-9de1-f39812702ede.png)

If company A raise PO against company B, company B make SO > DN against the company's A PO. On submission of delivery note system auto makes the purchase receipt against the PO which is raised by company A. Through this cycle stock and account will maintain.
Kindly share your thoughts and if you have any mockup design please share with us.

Thanks

**Comment by dzenou** [comment]
Hi,

Thanks for your proposal.
Your focus is on stock transfer only when in fact there are full inter-company transactions (within the Group) including ordering and invoicing which need to be kept. 
Below is my mock-up proposal, it basically comes down to allowing a Company (in my example Company A) to be a Supplier (of Company B) for the flow to work fully:

 
![mockup](https://cloud.githubusercontent.com/assets/21678714/20141751/0fed10d6-a692-11e6-9eff-baed11d54bec.jpg)


Best regards,
Daniel Zenou

**Comment by umairsy** [comment]
migrating issue to ERPNext Hub.

https://github.com/erpnext/hub/issues/23

**Comment by joshiparthin** [comment]
Any idea whether inter-company transactions would be possible on the same site?

**Comment by Fredoluka** [comment]
As the account module is given opportunity to present 4 issues to be addressed i think this should be one of the foremost so that the journey of inter company transaction can be commenced.Maybe later payment and journal transactions between two companies can be added

**Comment by karantkiruba** [comment]
Hi friends, Is this feature available in ERPNext?
We need to setup a dealer OEM network in ERPNext. Kindly advice to proceed.

**Comment by deepeshgarg007** [comment]
@dzenou We have both inter and intra-company transactions possible now in ERPNext. Closing this issue

**Comment by faris-mohamed10** [comment]
Hi @deepeshgarg007 any documentation available for the same? couldn't find any. It'll be helpful if you could share it.
