### ISSUE TITLE
iPhone 4S, 5S visualization issue

### ISSUE THREAD

**Issue by joezsweet** [frappe/erpnext#6252]
WIP, 

can u have a look at mobile visualization for iPhone 4S, 5S ..basically for width of 320px ..header is overlapping title name. See pics. 

Regards

<img width="292" alt="schermata 2016-09-01 alle 16 54 38" src="https://cloud.githubusercontent.com/assets/11652845/18172360/5bf2a90e-7065-11e6-9d39-286527ec02d6.png">
<img width="330" alt="schermata 2016-09-01 alle 16 54 26" src="https://cloud.githubusercontent.com/assets/11652845/18172361/5c0c7456-7065-11e6-9950-bf419a6ec0a9.png">

**Comment by PawanMeh** [comment]
@netchampfaris can you check?

**Comment by netchampfaris** [comment]
Will be fixed with frappe/frappe#2023

**Comment by joezsweet** [comment]
Hi there, seems problem is still there: 

<img width="274" alt="schermata 2016-09-16 alle 15 28 59" src="https://cloud.githubusercontent.com/assets/11652845/18587522/cbde5588-7c22-11e6-815a-a2d3a3b712a4.png">

is possible to have the following: 

<img width="279" alt="schermata 2016-09-16 alle 15 29 48" src="https://cloud.githubusercontent.com/assets/11652845/18587545/e7cb6826-7c22-11e6-9aff-fc515d612827.png">

Looks ike the image in the erpnext home page: 

<img width="290" alt="schermata 2016-09-16 alle 15 30 19" src="https://cloud.githubusercontent.com/assets/11652845/18587557/f6365cea-7c22-11e6-9122-fe05a7285ff5.png">
