### ISSUE TITLE
Custom fields defiened as mandatory does not appear in dialog window.

### ISSUE THREAD

**Issue by hfaridgit** [frappe/erpnext#6253]
When I defined custom fields in Cost Center doctype as mandatory they should appear in the first dialog that pops up when creating new cost center.... actually this does not happen and making error as the mandatory fields are not defined.

**Comment by PawanMeh** [comment]
Please post such queries on [discuss](discuss.erpnext.com)

**Comment by rmehta** [comment]
The Cost Center Dialog is custom coded, maybe it should include mandatory custom fields

Re-opening this.

**Comment by PawanMeh** [comment]
Sorry about the confusion, was not aware of the custom coding.

**Comment by rmehta** [comment]
@saurabh6790 maybe we should use Quick Entry for the Cost Center dialog
