### ISSUE TITLE
Leave allocation series not appearing in Naming series

### ISSUE THREAD

**Issue by PawanMeh** [frappe/erpnext#6254]
![screen shot 2016-09-01 at 9 08 03 pm](https://cloud.githubusercontent.com/assets/20460498/18173703/3f5910bc-7088-11e6-9511-b6cd2be22b60.png)
Leave allocation doc type does not currently appear in Update number series, this needs to be corrected and also other doc types with similar problems need to be identified and corrected.

**Comment by nabinhait** [comment]
fixed in develop
