### ISSUE TITLE
Change format in words of total amount 

### ISSUE THREAD

**Issue by aarondiazr** [frappe/erpnext#6256]
Hi!

I have a problem with the total mount in words value, I need to change it for a custom string o description, but I dont know how to make it. I'm a python developer, but your documentation not it clear....
How can i change the value for this field?
For example in report selling we have this:

(Default sentence):

> In Words (USD):
> USD Three Hundred And Forty only.

(Custom sentence):

> In Words (USD):
> Three Hundred And Forty Dollars 00/100 USD.

I need to change "_USD Three Hundred And Forty only_" to "_Three Hundred And Forty Dollars 00/100 USD_"
Anyone can help me or give me a clue?

**Comment by PawanMeh** [comment]
Please raise such queries on [discuss](discuss.erpnext.com)
