### ISSUE TITLE
sending mail from support module

### ISSUE THREAD

**Issue by arillus-at** [frappe/erpnext#6265]
Hi,

we are able to send out emails from other modules, but email will not go out of "support module". 
(it worked briefly in the beginning, but then email send broke down on "support module".

I delete mail account, added a new one, added another. Authentication work well on other application (roundmail) btw it doesn't matter, if it's gmail or not.

Error at Scheduler log:

Method
frappe.email.queue.flush

error:
`
(535, 'Refused. Authentication failed.')
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/queue.py", line 306, in send_one
    smtpserver.sess.sendmail(email.sender, email.recipient, encode(email.message))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/smtp.py", line 174, in sess
    (self.password or "").encode('utf-8'))
  File "/usr/lib/python2.7/smtplib.py", line 622, in login
    raise SMTPAuthenticationError(code, resp)
ValidationError: (535, 'Refused. Authentication failed.')
`
Installed Apps
ERPNext: v7.0.38
Frappe Framework: v7.0.30

**Comment by PawanMeh** [comment]
Could you reset your password and try once

**Comment by arillus-at** [comment]
Hi,

reseted password and tried again, same message:

`(535, 'Refused. Authentication failed.')
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/queue.py", line 306, in send_one
    smtpserver.sess.sendmail(email.sender, email.recipient, encode(email.message))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/smtp.py", line 174, in sess
    (self.password or "").encode('utf-8'))
  File "/usr/lib/python2.7/smtplib.py", line 622, in login
    raise SMTPAuthenticationError(code, resp)
ValidationError: (535, 'Refused. Authentication failed.')`

**Comment by PawanMeh** [comment]
@KanchanChauhan any idea?

**Comment by PawanMeh** [comment]
Could you send a screen shot of your email settings?
![screen shot 2016-09-07 at 12 42 00 pm](https://cloud.githubusercontent.com/assets/20460498/18303028/9dca93a4-74f8-11e6-938d-381891d421fe.png)

**Comment by arillus-at** [comment]
![image](https://cloud.githubusercontent.com/assets/4117478/18509730/6bdf6374-7a7a-11e6-9d24-c6df1b833911.png)

I do not check Default Outgoing, because my default Outgoing is another one.

**Comment by yashodhank** [comment]
@arillus-at As error message clearly states, **Refused. Authentication failed.**
You have issue with not module but with your email account being validated by your mail provider.
Please check with your provider, reset password, check ports and SSL/LTS Options with provider.

Closing this issue for now as there is no issue with ERPNext Email sending and receiving.

@arillus-at if you still need help, please open topic @ https://discuss.erpnext.com for more inputs from community.
