### ISSUE TITLE
Cannot View Images on in-app Help Documentation

### ISSUE THREAD

**Issue by manqala** [frappe/erpnext#6268]
Hello,

It seems that the links to the images on the in-app help documentation are broken. 
I'm on 7.1.0-beta.

I have done bench migrate after pulling the latest develop from upstream

![image](https://cloud.githubusercontent.com/assets/21128143/18211891/14065838-7138-11e6-937b-3a63ecf6b04c.png)

![image](https://cloud.githubusercontent.com/assets/21128143/18211906/26464364-7138-11e6-9dc1-9e8c561eb52f.png)

Regards,
cksgb

**Comment by PawanMeh** [comment]
@netchampfaris , please reply accordingly.

**Comment by netchampfaris** [comment]
@manqala Cannot replicate. Working fine for me.

Can you check the `src` attribute of those `img` tags?

**Comment by manqala** [comment]
Hi Please see below:

![image](https://cloud.githubusercontent.com/assets/21128143/18250131/0028884c-737a-11e6-9cdd-86c3b69013ca.png)

**Comment by netchampfaris** [comment]
@manqala 
Try to run this command `bench --site yoursitename setup-help`

**Comment by netchampfaris** [comment]
@manqala any update?

**Comment by manqala** [comment]
Hi @netchampfaris I did a bench update and it's working okay now. Thanks.
