### ISSUE TITLE
Add support for Item based Taxes and Charges

### ISSUE THREAD

**Issue by kworm83** [frappe/erpnext#6270]
I am wanting to do the development work to add support for Item based Taxes and Charges so that a single sales order/invoice can contain items which have different Taxes and Charges Templates.  I'm new to ERPNext development and wanted to discuss the best way to handle this for inclusion into the main codebase at some point...ie not breaking existing functionality.

**Comment by PawanMeh** [comment]
![screen shot 2016-09-03 at 10 33 02 am](https://cloud.githubusercontent.com/assets/20460498/18222847/d5a88fae-71c1-11e6-8d88-979257245e43.png)

You can configure this at Item level. Hope this meets your requirements

**Comment by kworm83** [comment]
@PawanMeh 

Yes I realize you can add all the taxes to each item but what I'm wanting is to configure the tax template only once (including taxes, rates, etc.) and then be able to apply the "Taxes and Charges Template" to the Items.  If you have hundreds of Items it does not make sense to have to input the different taxes and rates for each one of them...Imagine tax rate changes and you have to edit large numbers of Items to fix it.

**Comment by PawanMeh** [comment]
Data import tool is available for that, you can always use that, Invoice also has the option to choose tax templates,so they can be set up once and be applied accordingly,I think there are various work around to this,since this is more a discussion you could consider using the [forum](discuss.erpnext.com), in case you want to customize the form, you can use Customize Forms

**Comment by kworm83** [comment]
Well we really don't want to have to import data just to change tax rates.  The invoice option can only set one tax template for all items on the invoice...I'm wanting to support a tax template per-item on the invoice.  I'm going to develop it...I was just wanting to get some input from the main devs to see if there was any interest and/or discussion of the best way to implement it where it would be useful for others.  I can move it to the forum if you think that is the best place to discuss it.

**Comment by kworm83** [comment]
I haven't had much response from others...I may be the only one with this use case so I guess the question becomes would the core devs want to accept something like this into the core product if I develop it that way?  I'm thinking I would just add a "Tax and Charges Template" selection to the Item master and then extend the logic of the sales order/invoice to support using it per-Item if it is set...if it's not set then the existing behavior would remain the same.

**Comment by gregoribic** [comment]
It is a must have option for ERPNext to be usable in European countries. Tax should be selectable on per item basis. There are too many options for taxes to be entered in item's tax table. Taxes are also not only dependant on item, but also on client origin, type of item, type of services added, type of company legal type, amount of turnover, and so on.
It is almost impossible to write tax rules, so it is easier to select a tax type on item entry.

Another sub-question. Consequence of selection of Tax types on items is that different tax statements have to be written on invoice. Is there any functionality for this in ERPNext?

**Comment by addymuliady** [comment]
An item may be taxed or not in different countries so I think this feature is valid. @kworm83 you may want to create a bounty to this? I will be a backer definitely. We cannot expect the core developers to push for any features because it will mean hundreds of features for them to develop.

> I'm thinking I would just add a "Tax and Charges Template" selection to the Item master and then extend the logic of the sales order/invoice to support using it per-Item if it is set...if it's not set then the existing behavior would remain the same.

This is a great idea but then the tax and charges table way of calculating taxes have to change in the code. At the moment the Item Tax is against an account. It would be great if it is against the Taxes and Charges Template.

**Comment by OneiricIT** [comment]
+1 - just updated existing discussion post. Would it make sense to 

Would it not make sense to incorporate the below hierarchy? 
 > Global Sales / Purchase Tax template
 > > Item Master Tax > overrides Global Sales / Purchase Tax Template
 > > > Sales / Purchase Line Item Tax > overrides Item Master Tax

https://discuss.erpnext.com/t/item-wise-taxes-and-templates/20726/4

**Comment by raheebashraf** [comment]
@kworm83 Any update on this? Cause I'm having the same issue. Let me know if you have developed any module for it.

**Comment by kennethsequeira** [comment]
Closing the issue as the requirements are met with item tax template added in version 12:

https://docs.erpnext.com/docs/user/manual/en/accounts/item-tax-template

#16377
