### ISSUE TITLE
Multiple items

### ISSUE THREAD

**Issue by PratibhaPatil** [frappe/erpnext#6272]
It was better in previous version where we can add multiple items. But in version 7, we need to do more things for changing and for adding items. do something that will minimise the work.

**Comment by PawanMeh** [comment]
Could you let us know the screen or navigation you are referring to?

**Comment by rmehta** [comment]
@PratibhaPatil the new editable grids are much more keyboard friendly and hence we dropped the feature... were you using it frequently?
