### ISSUE TITLE
Error: Serial no is mandatory for item on POS VIew

### ISSUE THREAD

**Issue by sumitmatta998** [frappe/erpnext#6273]
I am just install ERP next on my system and need to use POS View for Serialized item.

I have created a new item and marked is serial number as true.

but when selecting a item from POS View I am not able to select that Item.
![screen shot 2016-09-03 at 13 23 42](https://cloud.githubusercontent.com/assets/12976181/18223602/c0129bfe-71d9-11e6-8d38-10923ab4afef.png)

Error: Serial no is mandatory for item.

**Comment by PawanMeh** [comment]
@rohitwaghchaure ,kindly check and respond appropriately

**Comment by rohitwaghchaure** [comment]
Hi @sumitmatta998 
This is a validation error, you need to inward the serial number first and enter into the Item search box.
