### ISSUE TITLE
Bulk Upload of BOM's

### ISSUE THREAD

**Issue by shivashakti** [frappe/erpnext#6274]
Hello,
Downloaded BOM Template with DATA and replaced with new data.
While processing for Bulk upload, following POP up appears
**### Only allowed 5000 rows in one import**
Thanks to advice workable solution.
Regards,
Mukesh

**Comment by PawanMeh** [comment]
You would need to split the data into multiple files having rows less than 5000 and try to upload.

**Comment by shivashakti** [comment]
Thanks will work on your suggested input and will update if this helps.
