### ISSUE TITLE
Android App images bug

### ISSUE THREAD

**Issue by Dbonejones** [frappe/erpnext#6275]
Android app does not show custom images (at least on my phone, Samsung S7 edge). It works fine with the default background and avatar, but custom background and avatar images do not show, the avatar image disappears and the background is white.
Tested multiple instances and users, multiple types of images.

![screenshot](https://cloud.githubusercontent.com/assets/20559059/18224980/5e0879bc-71be-11e6-980b-cab3864c438e.jpg)

**Comment by netchampfaris** [comment]
@Dbonejones Will be fixed with frappe/frappe#2023
