### ISSUE TITLE
Order of countries is out of alphabetical order

### ISSUE THREAD

**Issue by pifiu** [frappe/erpnext#6277]
I have an issue where the list of countries in a drop down menu is out of order. For example the very first country listed when it should be alphabetical order is Zimbabwe but followed by Aruba, and further down the country list, between the letters "A" and "B" I get a country with a "B" and then it continues into countries starting with the letter "A".
I verified that in "Customize Form" -> Country the setting is set to ASC.

See screenshots attached screenshots.

![zfirst](https://cloud.githubusercontent.com/assets/2664750/18228574/b42fbe18-7222-11e6-93bf-8e5c38c3520e.PNG)

![b-before-a](https://cloud.githubusercontent.com/assets/2664750/18228573/b42ecd78-7222-11e6-83a4-a7c5954ff448.png)

![country1](https://cloud.githubusercontent.com/assets/2664750/18228572/b42e7616-7222-11e6-864c-4d1ef6c0dec0.PNG)

**Comment by PawanMeh** [comment]
Could you provide the navigation for your first screen shot?

**Comment by pifiu** [comment]
What do you mean the navigation? This is in a custom doctype and using the country drop down.

**Comment by pifiu** [comment]
is my screenshot helpful?

**Comment by PawanMeh** [comment]
This is being investigated

**Comment by pifiu** [comment]
hey @PawanMeh any update on this?

**Comment by pifiu** [comment]
@PawanMeh anything?

**Comment by nabinhait** [comment]
Sent a PR to develop branch
