### ISSUE TITLE
POS - Reduce Clicks to Pay and Print

### ISSUE THREAD

**Issue by felixvarghese** [frappe/erpnext#6293]
In POS currently, after sales are all entered, the process to pay and print is the following
1. Click Pay
2. Enter the Amount
3. Click Submit
4. An "Are You Sure" message appears - click Yes
5. A "Success" message appears - click OK
6. Click "Print"
7. In the Windows/Chrome/Mac/Whatever OS Print Dialog, click "Print"
8. After successful printing, click "New" to process the next customer 

Steps 1-3 are good. Step 7 can be improved, but that requires a lot of work and would be out of scope for this issue - I also see there are other issues that discuss direct printing so no need to duplicate or discuss that in this issue.

My targeted/limited proposal to streamline this is the following
- [x] 1. Remove the "Are You Sure" message in Step 4 - that just adds friction which is unnecessary.
- [x] 2. Remove the "Success" message (step 5) - only show a message if there is an error.
- [ ] 3. If successful, automatically send a print signal to print the receipt - this means that step 6 is unnecessary. If there is contention on this point (i realize some people may not want to print a receipt), make it a setting in POS profile.

This would save 3 clicks and at least 5 seconds.

**Comment by ialhashim** [comment]
I agree, in my case I commented out the "are you sure message". It would be nice to have it as an option in the POS profile.

**Comment by pifiu** [comment]
I think the following can be eliminated or maybe have configuration setting for POS view that one can enable the extra confirmations if you want:

4. An "Are You Sure" message appears - click Yes - **Not required.**
5. A "Success" message appears - click OK - **Not required.**
6. Click "Print" - **Required.**
7. In the Windows/Chrome/Mac/Whatever OS Print Dialog, click "Print" - **Not required** if integration with direct priting is implemented.
8. After successful printing, click "New" to process the next customer. - **Not required,** it should go to the next transaction automatically.

I had mentioned this before, the POS should be a tool to help make a transaction fast and efficient, currently there are too many confirmation and clicks required to complete one which should be optional.

You guys should also look at this thread: https://discuss.erpnext.com/t/ideas-for-new-pos-interface/14638/10

I had also suggested this in another issue: https://github.com/frappe/erpnext/issues/4596 you can look in the middle: 

Better native POS thermal printer functionality without so many prompts - direct print to thermal. This is a big feature. Right now the printing configuration is clunky. To print you need to go through about 3 or 4 options before printing something. It should be possible to allow for the "print" button to instantly print to the thermal printer, not have to go through 1 or 2 extra options to be presented with which option to print. This goes back to the ability to set a tighter hardware integration and perhaps enabling a default printer if that would resolve the issue. Additionally an easier to customize receipt template engine.

**Comment by nosite** [comment]
Would be great if there are less clicks!

**Comment by rohitwaghchaure** [comment]
Hi @felixvarghese @pifiu @ialhashim @pifiu 

We have did some changes in the POS, which we have release in the V7.1. For more details about POS changes please check below link
https://www.dropbox.com/s/954kqm926wp1qy2/pos.gif?dl=0

**Comment by pifiu** [comment]
my only feedback is why is the print/new prompt showing after it prints? Wouldn't it be better to just go to the new transaction by default? If you need to reprint again, it should be on a separate menu option, not in that one. It's one less click in the sequence I mentioned above.

Overall however its greatly reduced.
