### ISSUE TITLE
File - Cannot set Private file to public

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#6297]
Scenario:

1. I attached an image to an item. While attaching an image, "Is Private" was checked by default.
2. Since Image file was private, it's not being displayed on website and on the web page of that item.
3. In the File record, Is Private is read only field, hence not able to set it as public.

![screen shot 2016-09-06 at 5 36 54 pm](https://cloud.githubusercontent.com/assets/910238/18272962/86848510-7458-11e6-8629-07a7e4c0bd7d.png)

**Comment by sonnguyengc** [comment]
You need chmod folder files to 775 or 777
Ex: sudo chmod 777 /opt/bitnami/apps/erpnext/htdocs/frappe-bench/sites/erpnext/public/files
