### ISSUE TITLE
Adding an offline POS number for unsynced documents at POS page

### ISSUE THREAD

**Issue by ialhashim** [frappe/erpnext#6298]
As discussed here: https://discuss.erpnext.com/t/no-invoice-number-available-when-printing-from-pos-page/15693

User felix suggested a possible solution of having an offline POS number that is attached to the invoice for later identification and verification. An invoice number is necessary for legal reasons in some countries.

**Comment by rohitwaghchaure** [comment]
@ialhashim 
POS print format
![screen shot 2016-09-06 at 11 58 27 pm](https://cloud.githubusercontent.com/assets/8780500/18285918/2489bf3e-748e-11e6-8f86-9b10d5504177.png)

Sales Invoice List

![screen shot 2016-09-06 at 11 59 47 pm](https://cloud.githubusercontent.com/assets/8780500/18285944/3cbc6f84-748e-11e6-8759-005574cd52c7.png)

![screen shot 2016-09-06 at 11 59 56 pm](https://cloud.githubusercontent.com/assets/8780500/18285969/4f417b9a-748e-11e6-88e9-20f2447ec25c.png)


Sales invoice print format

![screen shot 2016-09-07 at 12 00 06 am](https://cloud.githubusercontent.com/assets/8780500/18285994/66d15d5c-748e-11e6-93eb-9b3b5085edcc.png)

**Comment by ialhashim** [comment]
Thanks @rohitwaghchaure!

That is a reasonable compromise.
