### ISSUE TITLE
*SOLVED*** Error in manufacturing module or frappe

### ISSUE THREAD

**Issue by noetico** [frappe/erpnext#6304]
*SOLVED*** Manufacturing module has no BOM, BOM is unavailable from search, from stock entry etc. Also; there's the timesheet in the Manufacturing module. Then again production orders cannot be created. please test this; I have updated, also this is a clean demo install, pictures attached.
![erpnext-man-error](https://cloud.githubusercontent.com/assets/15412145/18295092/82c60a32-7496-11e6-8df1-12a5f92d7bb5.PNG)
![erpnext-prod-erro](https://cloud.githubusercontent.com/assets/15412145/18295093/82c712f6-7496-11e6-8665-fdab5eaeb39d.PNG)

**Comment by PawanMeh** [comment]
Assuming this is resolved from your title change. You can reopen if needed.
