### ISSUE TITLE
[v7.1] Rate values ignoring decimal precision

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#6305]
On sales order the Rate field has 6 decimal places, like I set on System Setting > Date and Number Format

But on buying module there's only 2 places, this causes a difference in the grand total, and I cant apply a discount because It would lead to a wrong cost

Any ideas?

**Comment by PawanMeh** [comment]
Please refer to the following [link](https://discuss.erpnext.com/t/erpnext-removes-fraction-amount-from-rate-field/14544/4) on our forum.

**Comment by applepipe** [comment]
thank you!
