### ISSUE TITLE
POS - Allow Multiple POS Profiles for a User

### ISSUE THREAD

**Issue by felixvarghese** [frappe/erpnext#6308]
Potential Use Cases:
- Currently, if a company has multiple sales outlets with users working at both, there is no good way to have a POS Profile for each
- Tracking for Individual POS Checkouts within a single location
- Working at different registers (returns/service vs sales)

Proposal: Allow multiple POS Profiles per user. Right now, if you try to create a second profile for a user/company combination, it throws an error.

Implementation
1. Allow multiple profiles to be created for a user/company combination - this may require the addition of a "Profile Name" to help people identify profiles
2. When opening the POS, If a user only has one profile created or valid, load the profile automatically. If a user has multiple profiles, allow a user to select which profile they want to use.

**Comment by graphskill** [comment]
This would be a really useful addition

**Comment by olamide2** [comment]
This is a good and much desired feature, I have just one issue to add..how can we ensure that when a staff is in a particular physical store all transactions he does will devolve into that particular store without HQ needing to do anything extra.

**Comment by xctheo** [comment]
+1

**Comment by mhbu50** [comment]
+1

**Comment by felixvarghese** [comment]
I'm adding the comment I made on #7582 here.

With regards to POS Profile, one idea may be the following. Fundamentally, a user will create a POS Profile mostly based on a location. So, if you have 5 locations and 10 users, that can be 50 profiles. However, what if you simply assigned users to a POS Profile? So, if you have 5 locations, create 5 profiles. Then assign users to those profiles.

This would be similar to assigning employees to salary structures.

So, have a POS Profile, then have a child table of users. In the child table of users, you can assign users.

As for a unique identifier, each record in the user child table has a hash which can be used in Sales Invoice.

With this comment, implementation steps look like the following

- [ ] Create a POS Profile Users Child table - it has one field, a linked field to User
- [ ] Add the POS Profile Users child table to POS Profile
- [ ] Add a "POS Profile Name" field to POS Profile - this becomes the new unique identifier for POS Profile
- [ ] When user opens POS, allow them to select the correct POS Profile (I realize this point will need to be broken down into more parts for implementation)
- [ ] Write a patch to deal with existing implementation. The patch would do two things - (1)Populate the POS Profile Name field. Use the "Applicable for User" field as the value for this. (2)Populate the new Users child table in POS Profile. In this implementation, the "Applicable for User" User would be added as a line to the child table for each POS Profile.
- [ ] Deprecate the "Applicable for User" field in POS Profile

**Comment by rebin2002** [comment]
Hello, 

I have the same problem that I can not make multiple POS Profiles for 1 user, my case is as the following.

I'm distributing smart phones in shops, around 500 shops, and I have 10 representatives which means each Rep has 50 shops to control and visit them daily, we want to add these 500 shops as warehouses because we put our phones there and when its sold then they make payment otherwise we should return the goods which are not sold, that means when its sold to end user then will be an invoice.

So I need to make 50 POS profiles for each user so they can make quick invoice and receiving payment in each shop they visit for the phones which are sold.

In my case there is 2 solutions which need to be added in the system i think.

1. Allow Multiple POS Profiles per user.
2. In POS window there should be an option to select the Warehouse. 

Please if anyone has any other idea let me know. Thank you very much.

**Comment by netchampfaris** [comment]
@felixvarghese Thank you for your clear explanations. It became a lot easier to implement after reading this.

**Comment by sylvestus** [comment]
to fix this issue go to  [Desk Form](http://127.0.0.1:8000/app/desk-form)
look for 
[restaurant-order-customer](http://127.0.0.1:8000/app/desk-form/restaurant-order-customer)
and add a field to allow you to sellect station when selecting a customer

2 pos_profile  Link  Station  POS Profile
  works like a charm

**Comment by sylvestus** [comment]
> Hello,
> 
> I have the same problem that I can not make multiple POS Profiles for 1 user, my case is as the following.
> 
> I'm distributing smart phones in shops, around 500 shops, and I have 10 representatives which means each Rep has 50 shops to control and visit them daily, we want to add these 500 shops as warehouses because we put our phones there and when its sold then they make payment otherwise we should return the goods which are not sold, that means when its sold to end user then will be an invoice.
> 
> So I need to make 50 POS profiles for each user so they can make quick invoice and receiving payment in each shop they visit for the phones which are sold.
> 
> In my case there is 2 solutions which need to be added in the system i think.
> 
> 1. Allow Multiple POS Profiles per user.
> 2. In POS window there should be an option to select the Warehouse.
> 
> Please if anyone has any other idea let me know. Thank you very much.

to fix this issue go to /app/desk-form
look for
 restaurant-order-customer app/desk-form/restaurant-order-customer
and add a field to allow you to sellect station when selecting a customer

2 pos_profile Link Station POS Profile
works like a charm
