### ISSUE TITLE
[Feature Request] Manufacturing - Automatically create sub-assemblies orders

### ISSUE THREAD

**Issue by ghost** [frappe/erpnext#6312]
Usually, in an ERP, an order (either MR for replenishing for example, or from a customer order) for a finished product automatically creates orders (purchase or manufacturing or transfer and automatic re-order) for its sub-assemblies so that there is no need to do it manually. For complex products and productions lines, it is essential for it to be fully automatic since products can be made of a few sub-assemblies but a few tens of different finished products can be ordered at the same time, multiplying the number of subcomponents to get.

When this happens, it is too complicated to create orders manually.

Then, production orders are grouped together by items, sub-assemblies.… down to the smallest component so that employees know exactly how many of each they have to produce over the next days. These lists are then printed and distributed. So production orders have to be extracted together, as a list.

Warehouses and other details could be set to default values.

**Comment by Devens** [comment]
Very useful and important suggestion. I agree.

**Comment by bcornwellmott** [comment]
This currently exists. It's called the production planning tool:

https://frappe.github.io/erpnext/user/manual/en/manufacturing/tools/production-planning-tool

**Comment by ChesAlex** [comment]
@bcornwellmott That's the point, when using the production planning tool, even when enabling multi-level BOM with nested BOMs… it does create production orders for finished products but not for its subassemblies. You have to create them recursively.

**Comment by bcornwellmott** [comment]
In v7.1, material requests for manufacture, which can be used to create production orders, can be created all in one go.

**Comment by ChesAlex** [comment]
@bcornwellmott Interesting, we have been using :
ERPNext: v7.0.40
Frappe Framework: v7.0.30

so far…

**Comment by bcornwellmott** [comment]
If you switch to the develop branch you'll see the new changes. It is much more thorough than the previous version (which until recently couldn't even do the recursive creation).

**Comment by ChesAlex** [comment]
@bcornwellmott 

So in the next versions, when we get an order from a customer, it will be able to order the components for the finished products automatically ? Will it group them together ?

**Comment by bcornwellmott** [comment]
So when you get an order from a customer, you would create a Sales Order for it and then go to the Production Planning Tool (same as older versions). The tools options have been expanded to give more options on the types of material requests to be generated based on a Sales Order, which includes creating Material Requests (for Purchase) for all the raw purchased materials (like before), PLUS Material Requests (for Manufacture) for all the sub-assemblies. From there, you can create Purchase Orders and Production Orders from these material requests.

The "ordering" still needs to be processed manually (as in, going from the material requests to the orders).

I'm not 100% sure that the Material Requests for manufacture are linked to the Sales Order (or a Project), but I *think* they are. If so, you can view them this way. It would not be hard to add this if it isn't already done.

**Comment by ChesAlex** [comment]
@bcornwellmott 

Okay, great.
Thanks for the explanation !

**Comment by corbincavolt** [comment]
@bcornwellmott When creating material requests, does the production planning tool take into account if you already have some of the raw materials in inventory?  If so, does it also take into account things like reorder points on certain raw materials?
