### ISSUE TITLE
Subscription functionality redesign

### ISSUE THREAD

**Issue by PawanMeh** [frappe/erpnext#6313]
- [ ] Create new "Subscription" doc type as below

![screen shot 2016-09-08 at 12 30 54 am](https://cloud.githubusercontent.com/assets/20460498/18324729/8d555294-755b-11e6-8252-3af90ba3130f.png)
- [ ] Remove the current fields of the "recurring" section from the doc types: Sales Order, Sales Invoice,Purchase Order, Purchase Invoice
- [ ] Refactor code that uses current fields to use the new "Subscription" doc type fields to create recurring documents and update the "Subscription ID" back to the base document(eg:Sales Order, Sales Invoice,Purchase Order,Purchase Invoice)

This new design will reduce redundant data which gets copied over to multiple invoices and also give a single page from where the user can set "Subscription IDs" for various doc types.

**Comment by kworm83** [comment]
I would have the following suggestions as well for now:

add an action to occur at the end date such as: expire, renew for x months, etc
add an action to notify via email x days before end of recurrence term
add a display field for the last time a recurrence was generated

**Comment by rmehta** [comment]
Why not "Subscription"? Recurrance seems like a non standard term

**Comment by kworm83** [comment]
Yes, I agree "Subscription" would be better especially for those who would be using it to bill subscribers like us.  Do you feel this should be implemented as a new module or use one of the existing ones...I suppose Account would be the only existing one to fit since this would create documents from both Selling and Purchasing.

**Comment by PawanMeh** [comment]
The reason I used recurrence is because the functionality today exists in
purchase order and purchase invoice as well, the base doc type would
dictate which recurrence to use.

We can use subscription if that's what the majority thinks but I think it
is not generic enough.

**Comment by kworm83** [comment]
I think recurrence is a little confusing.  For users like us we would be using this to represent subscriptions for services that we have sold to a customer on a contract…I suppose for purchasing it would be the same concept of buying under contract or having a standing order.

**Comment by PawanMeh** [comment]
Changed references to use "Subscription", will update the screen shot shortly, do reference the issue number in your Git Branch, in case anyone is taking up this for development

**Comment by kworm83** [comment]
I have started working on this.  What is the thought on using a series vs just a prefix for the subscription id naming?  I have it using a prefix of SUBS-.###### for now but it could be a series.

**Comment by kworm83** [comment]
<img width="1189" alt="screen shot 2016-09-08 at 12 10 05 pm" src="https://cloud.githubusercontent.com/assets/21957311/18358959/49bf76d8-75bd-11e6-9353-c840b15bd165.png">

I have a draft doctype done.

**Comment by kworm83** [comment]
<img width="1184" alt="screen shot 2016-09-08 at 12 12 12 pm" src="https://cloud.githubusercontent.com/assets/21957311/18359014/89c06c4c-75bd-11e6-981a-e63401b1497c.png">

**Comment by kworm83** [comment]
In validation I'm going to require the base document be in the "draft" status so that the subscription will process all the occurrences.  I will start on the backend work next...

**Comment by kworm83** [comment]
<img width="1190" alt="screen shot 2016-09-08 at 12 39 35 pm" src="https://cloud.githubusercontent.com/assets/21957311/18359855/6056fb38-75c1-11e6-8bd9-7fe6ae231cdb.png">

Revised to remove 2nd notify email textbox...probably no need for the redundant info.

**Comment by PawanMeh** [comment]
I would vote for naming series as different recurring base doc types could have different series. Maybe we can create one default naming series with the prefix of SUBS and leave it to the user in case they want to add different naming series they can.

**Comment by kworm83** [comment]
Ok, I have modified it to use a naming series with just SUBS- by default.

**Comment by PawanMeh** [comment]
Any updates on further progress on the development of this feature?

**Comment by Etine** [comment]
My use case is that of a reseller of monthly use licenses for online services. Customers can add or drop licenses. They only pay for the days that a license is used. So I need a way to prorate the customer for their use of their current subscription plan. The difference in days has to be calculated and discounted from the full subscription price. So it would be nice if there was a box that you can tick to mark that the subscription has to be prorated.

I would also be nice if there also is a way to manage subscription plans.

**Comment by joezsweet** [comment]
@PawanMeh @kworm83  any news on this?

**Comment by kworm83** [comment]
I’m still working on the functionality…it’s maybe 50% complete at this point.

**Comment by rmehta** [comment]
@kworm83 hey let us know if you need any help. Even if its partially done, we can review it

**Comment by joezsweet** [comment]
@kworm83 would be possible to enable/disable pro-rata invoice for subscription?

**Comment by hwinkel** [comment]
Seems great progress after all. @Etine especially your use case is intended here as well. I could offer to test the functionality with our use cases. @kworm83 is there anything in PRs.

**Comment by hwinkel** [comment]
@kworm83 regarding your suggestions of monthly extension, I would prefer to not only do that on month might also be in years, weeks or even days?

**Comment by hwinkel** [comment]
@Etine and all, seems we have a similar use case for online services. From a perspective of the subscription contracts developed here I would suggest another feature which should appear as part of this functionality. Usually such kind of subscription contracts have the following pricing structure which I think could internally modelled with a BOM:

* a price for non recurring costs (NRC)
* a price for monthly (or any other schedule) recurring costs (MRC)
* a price for (additional) usage based costs items (SMS, Gigabytes, Time, etc...)

Especially the latter must be imported or edited with every recurrence cycle.

**Comment by hwinkel** [comment]
We also can imagine that subscription contract might change over time, i.e. mid month. Do you have any envisioned ideas how to deal with that? It seems a bit like the use case @Etine has described where items getting in and out the contract framework. Or you terminate the current subscription contract and start a new one. Both might be partly charged.

I know this could become complex, but at least I would drop the comments and ideas here.

**Comment by mhbu50** [comment]
+1

**Comment by joezsweet** [comment]
hi there, any news on this?

**Comment by hwinkel** [comment]
Would be interested as well about the status

**Comment by joezsweet** [comment]
@manassolanki @nabinhait  Any news on this?

**Comment by hwinkel** [comment]
Is there any plan to go forward with this? for us service management based on booked subscriptions is a crucial point to get running with ERPnext. As ERPnext self is a subscription based service I'm wondering why its not in the software self.

**Comment by Etine** [comment]
@hwinkel Perhaps we can pool some resources to develop this feature. For some reason this project has halted. I also think it's a useful addition to Erpnext.

**Comment by ronniegarcia** [comment]
I would love to switch to ERPNext, and we also require a subscription mechanism as we sell Cloud Computing hosting services. We sell "one shot" services like setup fees, also known as NRC (Non Recurring Charge), and MRC or YRC like hosting services or internet domain names or SSL certificates (Monthly/Yearly Recurring Charge). Both of this service may appear in the same Sale Order.
And like many of you, services may vary during time for a same customer.
We would love to participate to this development : developer resource or money

**Comment by rmehta** [comment]
@hwinkel @Etine yeah we have this on our list too, just that there are so many competing things for priority. Maybe starting a bounty will help move things faster!

Just added $100 for this https://www.bountysource.com/issues/37656603-subscription-functionality-redesign

**Comment by hwinkel** [comment]
@rmehta Thanks for the feedback, I can imagine. However if we put the money on the table, is there a estimate whats happens then an when? ;-)

![money](https://cloud.githubusercontent.com/assets/152759/25004801/641dcedc-2056-11e7-9ed3-95a7d2ea4ac9.gif)

**Comment by hwinkel** [comment]
@Etine Yes, I would like to avoid to look for another tool or external service like www.freshservice.com and missuse the  ITSM for ordering things like Cloud Subscriptions etc...

**Comment by rmehta** [comment]
@hwinkel @Etine hope you guys add to the bounty too. Please show some "skin in the game" that you really need this feature!

**Comment by hwinkel** [comment]
@rmehta I have no problem adding to the bounty, but I'm not used to the bounty process. What happens after adding funds? Is there a minimum limit? is there any rough timeframe? Many thanks for advise.

**Comment by Etine** [comment]
@rmehta Same here. I would like to define the requirements more precisely and have some kind commitment over the lead time. Thanks.

**Comment by rmehta** [comment]
@hwinkel You add your commitment and hope someone picks it up, I think at $500 you might find some developers willing to go for tit

@Etine feel free to share the requirements more clearly.

**Comment by hwinkel** [comment]
I have already contacted somebody who will come along with suggestions. @rmehta how ever it goes, the result will be contributed. @Etine shall we have a session at gitter to discuss the requirements?

**Comment by hwinkel** [comment]
@ronniegarcia You are also interested in joining efforts?

**Comment by ronniegarcia** [comment]
@hwinkel sure i will, but i will first write some bits about my specs/requirements.
I will do this within the next 5-6 days.

**Comment by Etine** [comment]
I am, need some time to think out  / write up the requirements. But I am certainly interested. It makes more sense to commit to bountysource when there is a clear vision a what is going to be build.

**Comment by hwinkel** [comment]
Sure, but let the ball rolling. I have pointed another developer team too to the bounty. Let's see how they respond. I was thinking the upstream team would participate on developing the stuff even with bounty. I'm fine with sponsorship for the feature.

**Comment by ronniegarcia** [comment]
My thoughts :

Add a property to the Services Items, which allows them to be "one time only" (as for commissioning fees, Non Recurring Charges), or "subscription" (Monthly/Yearly Recurring Charges). For "subscriptions", it would be necessary to be able to specify their frequency of recurrence (per month, per year, etc)

Add a property to Customers, to specify if they want to be charged:
* "by Customer's Purchase Order reference", in which case the system will generate periodically as many Invoices as Sales Order
* "Globally", in which case the system will generate periodically a single Invoice with all active subscriptions

In my opinion, the normal workflow is:
Quotation → Sales order → Contract (or "Subscription") → Invoices periodically generated
                                          → Invoice for initial charges

The Contract (or "Subscription") is created from the contents of the Sales Order.

The same Sales Order can contain both "one time" and "subscription" services.
"One-time" items only need to be charged once.
"Subscription" items need to be charged periodically

Each line of a Contract (or "Subscription") should be independent of the others. That is, each line may have a different start date, a different end date, and a different commitment time. Each line can be terminated while the others continue to be active and therefore charged.

The status of a line of a Contract (or "Subscription") can be for example: active, expired, terminated.
We would need a list view to get an overview of all the items that are active or not.

When the start or end dates do not coincide with the first day of the month, invoicing must be prorated.

Each line of a Contract (or "Subscription") should have a readable reference, enabling it to be identified quickly. For example, the reference for subscribing to an e-mail account might be "a.smith@example.com". The one for renting a vehicle could be the license plate. The reference would be entered manually when the services were delivered.

Ideally, elements such as the quantity or price of a subscription can change over time. For example, a customer may consume more or less of a service from one month to the next. Changes in quantity or price can be made manually or by scripts.

What do you think ?

**Comment by hwinkel** [comment]
I think a subscription or contract is just the commercial agreement between the parties allows the supplier to charge regularly the items consumed by the customer based on a contracted price basis I.e. Price list. Therefore I would like to see a deliver note or similar doctype which collects the items consumed. A regular invoice will bundle all the items on a regular schedule to charge for everything consumed. This way you have the flexibility what to add when to a invoice rather then just make a copy if existing invoice items. If you ever have received a amazon or gce invoice you know what I mean. Further based on the delivery slip infos you might have the option to show a estimate of the monthly cost to the customer in a Portal.

**Comment by hwinkel** [comment]
@ronniegarcia I'm just reread your specs. As a user of a couple of Cloud, IaaS and SaaS Services I would like propose to decouple the Items booked either Non Recouring or Reccouring totally from the Contract. In Example, theses days you signup for IaaS Provider i.e. AWS, Azure etc. The Items of these Providers changing regulary and may even change prices. USer start to book and terminate service more or less on demand. With the design of the intendted Functionality we should be prepared for such functionality. I Envision rougly the follwing concept:

A user signs up to a given service and starts therefore a contract. This Contract holds a ID and the Charging relationship, duration etc. with the customer.  Once the customers starts to book items theses are selected from the Items (may organised in Groups, Categories, BOM etc). As the price for a Item might not allowed to change while contracted via a contract the item price would need to be part of a Customer/Contract based PriceList. Another option would be to use versioned item objects. A booking transaction will then create a given Sales Order or similar confirmation transaction which get mailed to the Customer as booking confirmation. If it required to charge immediately or either up Front BTO style Items could be used to trigger a immediate payment cycle.

Thats all for now. Contract and eventually NRC Items are charge and the contract is in place.

Next two things going to happen:

The User starts to book or consumes further items which receive order confirmations, delivery notes  etc. All of them are collected in a standing order and available as "usage" in the system.

A periodic, regular Job (workflow, automatic  workflow) will iterate over the contract status and collected Items. The Parameter for cron must me smaller as the smallest billing period which is stored in the contract. The Contract also holds the regular Items always used per billing cycle.
I.e. MRC.

The Billing Cycle Job will collect all Open Items (NRC, MRC, Recurring Usage, etc) and Creates a automatic Invoice and the payment process.

Hope the proposal makes some sense for this intended functionality.

**Comment by federojoavellaneda** [comment]
+1 for the bountysource mont! 

This topic was somewhat deserted, perhaps if we revive it in discuss more they join either for the economic or functional contribution.

**Comment by federojoavellaneda** [comment]
Hi @rmehta , The link to bountysource that is still to make contributions is still valid for this functionality?. So we collaborate and spread this a little.

**Comment by fproldan** [comment]
Hi, any idea to continue with this? I can contribute with a bounty.

**Comment by Etine** [comment]
Perhaps it's useful to put our heads together to define a set of requirements  / backlog of stories.
I really would like to see this feature sooner than later..

**Comment by hwinkel** [comment]
as mentioned, we are still happy to add to the bounty, once we can see an estimated release date on the horizon. I'm still happy to add Ideas how to model the functionality.

**Comment by hwinkel** [comment]
Hhm, added and removed from the next milestone? Any ideas about the future of the feature? It is really blocking the adoption for two organisations here.

**Comment by manassolanki** [comment]
Hi @hwinkel,
If you look closely, the milestone is changed from **Version 9** to **July-2017** which means it is targeted to be completed **this month** instead of **next few months**.

**Comment by hwinkel** [comment]
OK, missed the previous message about milestone 8. Thank you for clarification

**Comment by rohitwaghchaure** [comment]
**1st Cut**
Frequency = Daily, Weekly, Monthly, Quarterly, Half-yearly, Yearly

![screen shot 2017-07-20 at 5 22 20 pm](https://user-images.githubusercontent.com/8780500/28416116-4729b45a-6d70-11e7-8edd-7e5b9188f47e.png)

This feature is still under development, kindly share your thoughts.

**Comment by rmehta** [comment]
@rohitwaghchaure why child table? It can be just a link in the Dashboard?

**Comment by rohitwaghchaure** [comment]
@rmehta 

It's for linking purpose, I will display child table data in the base docname's dashboard

**Comment by hwinkel** [comment]
HI, we are just tackling a use case to quote for reccuring cost:

- Write a quotation wich includes non recurring items (NRC)  and scheduled i.e. monthly reccurring items (MRC).
- customer accept the quotation
- Customer will get a Salesorder may includes a aggregat of the MRC over the conntracted commitet duration
- System Creates a Contract/Subscription which holds the details of the contracted Items and recurring sequence
- System collects the consumed item over the time i.e. Deliver Slips etc. if you also have usage based items
- Recurring sequence emmits scheduled aggregated documents

I think process wise this was already written above in the past. What's just springs to my mind is how to model the Scheduled Reccuring Items. What about:

- Extend UOMs to hold such recurrance infomations
- Introduce named UOMs which can have a configurable Schedule

and in general, introduce UoM conversation including formulas, where UoM of the same Category can be converted tu be used in different documents. (i.e. Buy tons sell kilograms)

**Comment by hwinkel** [comment]
Seems Odoo is using the UoM "month" too. See screenshot here:

https://www.odoo.com/page/subscriptions

**Comment by hwinkel** [comment]
@ronniegarcia You are right, after sketching and hacking a couple of more documents I would argue the recurrence should be part of the product/service definition. I.e. as a UoM?! or extended UoM.

fully agree to decouple billing frequency from Product recurrence cycle. if you change the billing cycle i.e. 12 Month in advance for no usage based service could drive a pricing and rounding rule for discounts of the product.

Another option would be to make i.e. Monthly Products part of a anula Bundle (BoM) to handle such use case.

**Comment by Etine** [comment]
Would be nice if you could define business rules for a subscription. This rule can than be applied to a service or if you ship products to those items. 
E.g. A service can be a use(r)  license for a cloud service. The license cost is calculated  proratedly, so if the service is used for x minutes / hours /days only the use cost will be billed. 
It would be very useful if you could define scenario's that apply to a specific service or product and have some default set's like monthly use / yearly use.

**Comment by hwinkel** [comment]
@Etine what you describe is for me somehow the same as a (may extendd) UoM cobversion rule. You buy a License p.a. (yearly) and sell them Monthly, hourly - you name it. As long UoMs are in the same category (rime here) the can be converted. A pricing rule can then use the converted input and add formulas and  rounding. The result will be a (named) price list which holds this price model. This priocelist then can be used for you customers.

it gets interesting for usage based services, but I think it can be modeled with existing functionality. If you use existing functionality like BoMs, Stock Aggregation, Manufacturing  etc etc.  you get quite far. The only thing misssing is the job scheduling and workflow engine calling the transactions on a regular bases. See my comment above.

https://github.com/frappe/erpnext/issues/6313#issuecomment-293883631

**Comment by hwinkel** [comment]
just send a $100 for the issue via bounty source to get some traction by team.. ;-)

**Comment by federojoavellaneda** [comment]
Donate :)

**Comment by ronniegarcia** [comment]
Donated $100 more to draw attention, I'm sure we will donate more when someone takes it up

**Comment by hwinkel** [comment]
@ronniegarcia @federojoavellaneda thanks for following. we are also are open to donate more.

**Comment by epochc** [comment]
While you are designing, developing and implementing this, can you please, if you've not already done it, pay a bit of attention to revenue recognition principles.

Like if you were to buy the ERPNext Frappe 5 user license. You pay some $500 (say) per year. Now, accounting and regulatory principles say that this amount should sit as an Advance amount from customer, and depending on the country, the regulatory and accounting principles, you can recognize revenue on a periodic (say daily, could be even hourly or every second, or whatever is the appropriate period as decided by the combination of Country, Regulatory requirements, generally accepted accounting practices, and what the Company Management thinks is the right governance model for the company) basis this amount moves from the liability (Current Liabilities) to the Income Account.

This process also supports the company policies in terms of cancellation. So, if a consumer that signed up for a Yearly package at $500.00 decides to cancel subscription after 24 days, the company policy may say that hosting fees are chargeable monthly or part thereof, then on the day of signing, $500/12 hits the income account, and $500*11/12 hits the Customer Advances amount.

So, now all the organization has to do is to look at the advance amount balance for the customer and refund that amount, in case of cancellations.

This also means that there is a background job upon appropriate triggers, that moves these amounts for these parties from the Liability account to the Income account.

Different plans may have different revenue recognition criteria. You could have a very aggressively priced plan that does not refund any amount at all. And a conservative priced plan that does. So the revenue recognition parameters is ideally configurable at the Plan level.

Please collaborate with the Schools Account Module https://discuss.erpnext.com/t/education-domain-fee-module-redesign/25973. They will have similar challenges and these two projects, if planned well can share much of this code. While I am not sure if the Schools guys can contribute to the bounty, they may be interested in contributing code and energies to the develop this functionality.

@manassolanki : This may be of interest to you.

Please let us know if you need any help from the Foundation.

Great initiative and I am very grateful for your passion, energies, contributions and involvement.

Thanks

Jay

**Comment by epochc** [comment]
Will somebody please post the link to the bounty here and on the Discuss forum?

Thanks

Jay

**Comment by hwinkel** [comment]
@epochc for the link just look above: 
https://github.com/frappe/erpnext/issues/6313#issuecomment-293831215

**Comment by hwinkel** [comment]
@epochc you are right with the cancelation policy. but this is also true if you not even received the payments. we have  a use case where we have a lets say 24 months contract with monthly fixed costs (MRC) and a usage based Price (lets say Gigabytes). Now we are forced to have a cancelation clause which says: If you cancel the contract you have to pay 60% of MRC of the remaining committed contract duration.

**Comment by bobbyst** [comment]
Is this available in the Virtual Image version of ERPNext? I don't see the subscriptions screen.

**Comment by hwinkel** [comment]
seems the milestone has slipped again, no attention either. bounty also does not help

**Comment by joezsweet** [comment]
@hwinkel ..keep calm 😁 ..the important thing is to be done ..no matter a couple of months ahead 🖒

**Comment by rohitwaghchaure** [comment]
Have sent PR, currently it's under review. 
Closing this issue, kindly start with new issue in the githun, if there is any issue in the subscription module after merge the PR.
