### ISSUE TITLE
Only open nodes are filtered during Trial Balance

### ISSUE THREAD

**Issue by bekchandra** [frappe/erpnext#6330]
Hi,

In Trial Balance, how can I get all the balances by searching a specific word in all nodes ( whether it is open or closed ) ?

![trial](https://cloud.githubusercontent.com/assets/22111642/18408045/a710f382-7740-11e6-8292-615c3ebb1e22.JPG)

In the above case, I want to view the balances of All Nodes ( Open & Closed ) Starting With the word **AMD**

**Comment by PawanMeh** [comment]
You can export the file to CSV and do filtering

**Comment by bekchandra** [comment]
CSV conversion is the other way of doing this filter. But why the balances of all nodes, whether it is open or closed, with a specific word can not the searched.
