### ISSUE TITLE
Cannot Add Email Addresses to Setup Default Email Accounts with GMail service

### ISSUE THREAD

**Issue by garrierao** [frappe/erpnext#6341]
Hi. We have ERPNext running on the Google Online Servers (Bitnami) and have been getting this error mesaage when adding Email Accounts:

Message
Close
Did not save
Server Error: Please check your server logs or contact tech support.
Traceback (most recent call last):
  File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 20, in savedocs
    doc.save()
  File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/model/document.py", line 250, in save
    self._validate()
  File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/model/document.py", line 369, in _validate
    self._save_passwords()
  File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/model/base_document.py", line 582, in _save_passwords
    set_encrypted_password(self.doctype, self.name, new_password, df.fieldname)
  File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/utils/password.py", line 25, in set_encrypted_password
    { 'doctype': doctype, 'name': name, 'fieldname': fieldname, 'pwd': encrypt(pwd) })
  File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/utils/password.py", line 95, in encrypt
    cipher_suite = Fernet(encode(get_encryption_key()))
  File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/utils/password.py", line 109, in get_encryption_key
    update_site_config('encryption_key', encryption_key)
  File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/installer.py", line 276, in update_site_config
    with open(get_site_config_path(), "w") as f:
IOError: [Errno 13] Permission denied: u'./erpnext/site_config.json'

Traceback (most recent call last):
  File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/app.py", line 58, in application
    response = frappe.handler.handle()
  File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/handler.py", line 36, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/__init__.py", line 875, in call
    return fn(*args, **newargs)
  File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 20, in savedocs
    doc.save()
  File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/model/document.py", line 250, in save
    self._validate()
  File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/model/document.py", line 369, in _validate
    self._save_passwords()
  File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/model/base_document.py", line 582, in _save_passwords
    set_encrypted_password(self.doctype, self.name, new_password, df.fieldname)
  File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/utils/password.py", line 25, in set_encrypted_password
    { 'doctype': doctype, 'name': name, 'fieldname': fieldname, 'pwd': encrypt(pwd) })
  File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/utils/password.py", line 95, in encrypt
    cipher_suite = Fernet(encode(get_encryption_key()))
  File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/utils/password.py", line 109, in get_encryption_key
    update_site_config('encryption_key', encryption_key)
  File "/opt/bitnami/apps/erpnext/htdocs/frappe-bench/apps/frappe/frappe/installer.py", line 276, in update_site_config
    with open(get_site_config_path(), "w") as f:
IOError: [Errno 13] Permission denied: u'./erpnext/site_config.json'

**Comment by garrierao** [comment]
https://104.199.173.106/desk

username:  garrie@grhealthservices.com
password:  erpnext123

**Comment by garrierao** [comment]
Its something to so with the Bitnami instance of ERPNext as the site hosted on ERPNEXT.COM doesnt have any issue in adding the same gmail account!  Why is this the case ? 
I want to host ERPNExt only on google servers - I should not have so many 'hidden' restrictions?!

**Comment by shreyasp** [comment]
@garrierao Bitnami configures it's application stack in a weird way and ERPNext team is not responsible for maintaining the Bitnami ERPNext Images. It would be better If you can raise the issue directly on Bitnami forum.

Also, you can check the official instructions to install to BITNAMI ERPNext on the following link,
https://bitnami.com/stack/erpnext/README.txt

In case you want to setup, you can also try using,
```
- wget https://raw.githubusercontent.com/frappe/bench/master/playbooks/install.py
- sudo python install.py --develop --user frappe --site <your_site_name>
```

This will eliminate any issues, regarding to BITNAMI or email account 😃

**Comment by garrierao** [comment]
Is there any way to link ERPNEXT to any receipt / OCR capture technology to incorporate electronic paperless accounts payable ? Eg. Email or upload or email directly as PDF an original supplier invoice into ERP Next ‎which does OCR Scan of supplier details / PO Number, dates, numerical references, total value etc etc  and creates a draft of Accounts Payable Invoice  ? Dr Garrie RaoGRHS                                                                                                                                                                                                                From: Shreyas PatilSent: Monday, 12 September 2016 6:23 PMTo: frappe/erpnextReply To: frappe/erpnextCc: garrierao; MentionSubject: Re: [frappe/erpnext] Cannot Add Email Addresses to Setup Default Email Accounts with GMail service (#6341)@garrierao Bitnami configures it's application stack in a weird way and ERPNext team is not responsible for maintaining the Bitnami ERPNext Images. It would be better If you can raise the issue directly on Bitnami forum.

Also, you can check the official instructions to install to BITNAMI ERPNext on the following link,
https://bitnami.com/stack/erpnext/README.txt

In case you want to setup, you can also try using,

- wget https://raw.githubusercontent.com/frappe/bench/master/playbooks/install.py
- sudo python install.py --develop --user frappe --site <your_site_name>


This will eliminate any issues, regarding to BITNAMI or email account 😃 

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/frappe/erpnext","title":"frappe/erpnext","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/frappe/erpnext"}},"updates":{"snippets":[{"icon":"PERSON","message":"@shreyasp in #6341: @garrierao Bitnami configures it's application stack in a weird way and ERPNext team is not responsible for maintaining the Bitnami ERPNext Images. It would be better If you can raise the issue directly on Bitnami forum.\r\n\r\nAlso, you can check the official instructions to install to BITNAMI ERPNext on the following link,\r\nhttps://bitnami.com/stack/erpnext/README.txt\r\n\r\nIn case you want to setup, you can also try using,\r\n```\r\n- wget https://raw.githubusercontent.com/frappe/bench/master/playbooks/install.py\r\n- sudo python install.py --develop --user frappe --site \u003cyour_site_name\u003e\r\n```\r\n\r\nThis will eliminate any issues, regarding to BITNAMI or email account 😃 "}],"action":{"name":"View Issue","url":"https://github.com/frappe/erpnext/issues/6341#issuecomment-246307557"}}}

**Comment by garrierao** [comment]
I have abandoned Bitnami and setup grhealthservices.erpnext.com‎    but I am still having the same error message as below with the Gmail account    please help or shall I use another SMTP referral/patch like mandrill?                                                                                                                                                                                                                                                                                                                                         Dr Garrie RaoGRHS                                                                                                                                                                                                                From: Shreyas PatilSent: Monday, 12 September 2016 6:23 PMTo: frappe/erpnextReply To: frappe/erpnextCc: garrierao; MentionSubject: Re: [frappe/erpnext] Cannot Add Email Addresses to Setup Default Email Accounts with GMail service (#6341)@garrierao Bitnami configures it's application stack in a weird way and ERPNext team is not responsible for maintaining the Bitnami ERPNext Images. It would be better If you can raise the issue directly on Bitnami forum.

Also, you can check the official instructions to install to BITNAMI ERPNext on the following link,
https://bitnami.com/stack/erpnext/README.txt

In case you want to setup, you can also try using,

- wget https://raw.githubusercontent.com/frappe/bench/master/playbooks/install.py
- sudo python install.py --develop --user frappe --site <your_site_name>


This will eliminate any issues, regarding to BITNAMI or email account 😃 

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/frappe/erpnext","title":"frappe/erpnext","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/frappe/erpnext"}},"updates":{"snippets":[{"icon":"PERSON","message":"@shreyasp in #6341: @garrierao Bitnami configures it's application stack in a weird way and ERPNext team is not responsible for maintaining the Bitnami ERPNext Images. It would be better If you can raise the issue directly on Bitnami forum.\r\n\r\nAlso, you can check the official instructions to install to BITNAMI ERPNext on the following link,\r\nhttps://bitnami.com/stack/erpnext/README.txt\r\n\r\nIn case you want to setup, you can also try using,\r\n```\r\n- wget https://raw.githubusercontent.com/frappe/bench/master/playbooks/install.py\r\n- sudo python install.py --develop --user frappe --site \u003cyour_site_name\u003e\r\n```\r\n\r\nThis will eliminate any issues, regarding to BITNAMI or email account 😃 "}],"action":{"name":"View Issue","url":"https://github.com/frappe/erpnext/issues/6341#issuecomment-246307557"}}}

**Comment by shreyasp** [comment]
@garrierao Can you send screenshot of the error and the page?

**Comment by nabinhait** [comment]
Please post this on bitnami forum
