### ISSUE TITLE
Suggestion for Email Digest

### ISSUE THREAD

**Issue by Devens** [frappe/erpnext#6342]
Currently in Email Digest/Pending Activity/ToDo List, all ToDos allocated to "me" and assigned by "me" are shown together. If we can prepare two separate list for the same, it would be more helpful.

**Comment by Devens** [comment]
![untitled_clipping_091216_121755_pm](https://cloud.githubusercontent.com/assets/10671911/18430152/ec9c2aec-78f4-11e6-9ca0-c0a1a5c06392.jpg)

**Comment by rmehta** [comment]
https://github.com/frappe/erpnext/issues/10497
