### ISSUE TITLE
bug in creating quotation from lead: missing "Source cannot be Customer"

### ISSUE THREAD

**Issue by ioweb-gr** [frappe/erpnext#6348]
I upgraded today to the latest version and I'm facing an error trying to create a quotation from a lead. 

```Source cannot be "Customer". It should be one of "", "Contact", "Existing Customer", "Reference", "Advertisement", "Cold Calling", "Exhibition", "Supplier Reference", "Mass Mailing", "Customer's Vendor", "Campaign"```

![capture](https://cloud.githubusercontent.com/assets/20220341/18435321/1655b834-78fb-11e6-8874-4e6804e8e5ee.JPG)

I was able to save the Lead using Customer for Source fine though

**Comment by rmehta** [comment]
Fixed with #6231
