### ISSUE TITLE
Remark field in Sales Invoice and Journal entry

### ISSUE THREAD

**Issue by Nehamirpuri** [frappe/erpnext#6354]
In sales invoice the "Remark field" under reference can it be made allow on submit? &
in Journal Entry can the "Remark field" under reference be made on allow on submit & can the auto fill be optional along with removing read only option from the field?

As we want to use these fields for oustanding follow up remark update based on accounts receivable report.

**Comment by Nehamirpuri** [comment]
Hi any update by when this shall be done as its been 24 days since issue is created!!

**Comment by Veluswami** [comment]
Hi, is this been implemented, will be good to have this feature

**Comment by ankush** [comment]
If you MUST have this then just hide the original field, create a new custom field and make it "allow on submit".

**Comment by Veluswami** [comment]
Thanks @ankush
