### ISSUE TITLE
Error while updating

### ISSUE THREAD

**Issue by slushpuppy** [frappe/erpnext#6360]
Updating 3683001..a8b8d81
Fast-forward
 erpnext/__init__.py                                                           |  2 +-
 erpnext/accounts/doctype/payment_entry/payment_entry.js                       |  6 ++++++
 erpnext/accounts/doctype/payment_entry/payment_entry.json                     |  4 ++--
 erpnext/accounts/doctype/payment_entry/payment_entry_list.js                  |  6 ------
 erpnext/accounts/doctype/payment_entry_reference/payment_entry_reference.json |  2 +-
 erpnext/accounts/page/pos/pos.js                                              |  2 ++
 erpnext/accounts/print_format/point_of_sale/point_of_sale.json                |  4 ++--
 erpnext/controllers/accounts_controller.py                                    |  5 ++---
 erpnext/controllers/queries.py                                                |  3 ++-
 erpnext/maintenance/doctype/maintenance_schedule/maintenance_schedule.py      | 15 +++++++++------
 erpnext/patches/v7_0/convert_timelog_to_timesheet.py                          |  4 +++-
 erpnext/patches/v7_0/migrate_mode_of_payments_v6_to_v7.py                     | 32 +++++++++++++++++++++++++-------
 erpnext/patches/v7_0/setup_account_table_for_expense_claim_type_if_exists.py  |  3 ++-
 erpnext/projects/report/daily_timesheet_summary/daily_timesheet_summary.py    |  8 +++++---
 erpnext/startup/notifications.py                                              | 20 ++++++++++++++++----
 15 files changed, 78 insertions(+), 38 deletions(-)
 delete mode 100644 erpnext/accounts/doctype/payment_entry/payment_entry_list.js
Requirement already up-to-date: pip in ./env/lib/python2.7/site-packages
Command "/home/frappe/frappe-bench/env/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-s8ZCnv/python-ldap/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-TsDk8u-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/frappe/frappe-bench/env/include/site/python2.7/python-ldap" failed with error code 1 in /tmp/pip-build-s8ZCnv/python-ldap/
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 9, in <module>
    load_entry_point('bench==3.0.0', 'console_scripts', 'bench')()
  File "/home/frappe/bench-repo/bench/cli.py", line 40, in cli
    bench_command()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/bench-repo/bench/commands/update.py", line 60, in update
    _update(pull, patch, build, bench, auto, restart_supervisor, requirements, no_backup, upgrade, force=force)
  File "/home/frappe/bench-repo/bench/commands/update.py", line 79, in _update
    update_requirements(bench_path=bench_path)
  File "/home/frappe/bench-repo/bench/utils.py", line 375, in update_requirements
    install_requirements(pip, req_file)
  File "/home/frappe/bench-repo/bench/utils.py", line 379, in install_requirements
    exec_cmd("{pip} install -q -r {req_file}".format(pip=pip, req_file=req_file))
  File "/home/frappe/bench-repo/bench/utils.py", line 127, in exec_cmd
    raise CommandFailedError(cmd)
bench.utils.CommandFailedError: ./env/bin/pip install -q -r ./apps/frappe/requirements.txt

**Comment by shreyasp** [comment]
@slushpuppy 

Please run following commands depending upon your OS,
```
- sudo yum install -y python-devel, openldap-devel
- sudo apt-get install -y libsasl2-dev python-dev libldap2-dev libssl-dev
```

And then update your bench.

**Comment by slushpuppy** [comment]
@shreyasp Perfect, it works! Closing this issue now
