### ISSUE TITLE
Project module enhancements

### ISSUE THREAD

**Issue by PawanMeh** [frappe/erpnext#6363]
- [x] Allow to add weights for tasks.
- [x] Add percent completion method at project level, to allow for calculation of % complete of project based on weighted average of tasks.

**Comment by OneiricIT** [comment]
Can I also add(?):

- [ ] Sales Quotation reference for Projects

- [ ] Add Sales Quotation in Project Related Documents

**Comment by PawanMeh** [comment]
I think project is created after a sales order, the customer may not accept your sales quotation , why would you create a project in the system to execute it?

**Comment by OneiricIT** [comment]
We have many situations where we need to quote on additional work and/or products within an existing project, so in order to properly manage and track the sales flow we also needed references to quotations created from the project.

**Comment by PawanMeh** [comment]
You can add a custom field to Sales Quotation for tracking project in that case and get it via a report OR you could develop the feature and contribute OR you could request it as part of GitHub issue 6326, which is raised for related documents.

**Comment by OneiricIT** [comment]
Thanks. Already doing 1st point at present, will also jump onto 6326.

**Comment by PawanMeh** [comment]
If you have developed some custom solution for it as part of #1, I think you should try to contribute it back to the community.

**Comment by OneiricIT** [comment]
Haven't done custom report or anything worth noting, just added the custom field so not much to contribute sorry.

**Comment by mhbu50** [comment]
+1
