### ISSUE TITLE
renaming and item does not change the item_name but the item_code

### ISSUE THREAD

**Issue by vrms** [frappe/erpnext#6365]
click on the name (top left) of an item in the Form View
![item-2](https://cloud.githubusercontent.com/assets/7608112/18507189/df6f04d0-7aa1-11e6-90eb-0ef4e9839ead.JPG)
opens a Dialog Box prompting you to **Rename**. First unexpected thing is that you do not see the name (which you have clicked on but a number (the item_code)

once you changed the entry and click on **Rename** (second reference to **name** not **code**)
![item-3](https://cloud.githubusercontent.com/assets/7608112/18507283/4eb45840-7aa2-11e6-9feb-27df678f2799.JPG)

when you come back to the Form view the **Name** (upper left) is unchanged while the **Code** (which is not identified here as such) on the upper right has changed
![item-4](https://cloud.githubusercontent.com/assets/7608112/18507346/8f3690ae-7aa2-11e6-9068-51c38dac5020.JPG)

Furthermore in the item list Filters you can search for the Item Code and a an ID (which seems to be the same thing)

If you actually wanted to change the item name you'd have to scroll much further down the form and change the item name there

Isn't that unnecessary confusing? Or is there any deeper sense behind this I just don't see?

**Comment by vrms** [comment]
I just noted that the same principle (which seems to be not logical to me) applies for Customers as well. One difference though ... Customers do not have a Customer Code (apart from the for the user invisible naming series) 

I wonder whether I just do not get something real genius here or **is** this actually a bit confusing (to everybody)?

**Comment by rmehta** [comment]
@shachiTakalkar can you rename and item and check?

**Comment by shachiTakalkar** [comment]
@rmehta @vrms I tried to replicate it in my test account and I was able to change my Item Code as well as Item Name. You can change the Item Name by changing the full name under the Name and Type section.
