### ISSUE TITLE
Unable to submit timesheet against an "Unstopped" Production Order

### ISSUE THREAD

**Issue by PawanMeh** [frappe/erpnext#6370]
1) Create a Production Order, start processing it, Stop it and then Unstop it.
![screen shot 2016-09-15 at 10 10 08 am](https://cloud.githubusercontent.com/assets/20460498/18538538/9cb9e4e4-7b2c-11e6-8d82-b001b19e7229.png)

2) Once the production Order is unstopped, user assumes it is "resumed", however a timesheet cannot be submitted against this

![screen shot 2016-09-15 at 10 09 05 am](https://cloud.githubusercontent.com/assets/20460498/18538533/844ac32e-7b2c-11e6-99e4-8bc8274b762a.png)

3) If possible, rename "Unstopped" to "Resumed".

**Comment by mainul94** [comment]
Fixed in Pull Request [6398](https://github.com/frappe/erpnext/pull/6398)
