### ISSUE TITLE
[Feature Request] Automatic addition of Privilege Leaves for each employee

### ISSUE THREAD

**Issue by saurabhvashist** [frappe/erpnext#6376]
Earned Leaves (EL) or Privileges Leaves (PL) or Annual Leaves (AL), differently named leaves by different organizations but treated similarly. They are added to every employees' account at the end of the month on pro-rata basis, automatically.

Need this feature in ERPNext to be able to add X leaves automatically at the end of the month depending on the leaves taken by the employee in that month. These leaves have capability of being carry forward to next year with limitation (added recently by many organizations) to compulsorily deduct 15 leaves out of 30 PL. These compulsory leaves are to be taken by the employee in the defined fiscal and only 15 can be carry forwarded. 

Additionally, there is now a limit (setup differently by different organizations) on number of leaves that can be accumulated. Govt. employees can accumulate 300 EL however, private company allows 60 leaves to 90 leaves only. Anything exceeding this limit will get lapsed automatically at the end of the year if not taken/used.

Hope other users too face this problem and this new feature can be added soon to ERPNext!

**Comment by mhbu50** [comment]
+1

**Comment by PawanMeh** [comment]
You can check the latest features in [version 11](https://erpnext.org/releases/version-11/features/human-resources) related to earned leave. If they do not meet the requirements, kindly re-open the issue or create a new issue with gaps in the feature.
