### ISSUE TITLE
mobile visualization issue (width 320px, i.e. iPhone 4s, 5s)

### ISSUE THREAD

**Issue by joezsweet** [frappe/erpnext#6386]
Hi there, seems problem is still there:

<img width="274" alt="schermata 2016-09-16 alle 15 28 59" src="https://cloud.githubusercontent.com/assets/11652845/18587681/84fe32c2-7c23-11e6-80b5-f294c77e6355.png">

basically seem that it comes out when module name is larger than the max allowed space. 

What about to put an icon like: 

<img width="132" alt="schermata 2016-09-16 alle 15 47 05" src="https://cloud.githubusercontent.com/assets/11652845/18587996/dae6bffa-7c24-11e6-9617-305e52a786db.png">

instead of full module name? Let's say "B" for buying, "A" for accounting, "St" for stock? 

WIP, have the following:

<img width="279" alt="schermata 2016-09-16 alle 15 29 48" src="https://cloud.githubusercontent.com/assets/11652845/18587822/1685020c-7c24-11e6-97bc-fdd287096e25.png">

Looks ike the image in the erpnext home page:

<img width="290" alt="schermata 2016-09-16 alle 15 30 19" src="https://cloud.githubusercontent.com/assets/11652845/18587778/e6c3eb6e-7c23-11e6-8b89-db20dd6dbd95.png">

**Comment by netchampfaris** [comment]
Sent the PR frappe/frappe#2053
Took good care of it this time. Hopefully, it doesn't come up again :)

**Comment by joezsweet** [comment]
👍
