### ISSUE TITLE
Cannot access Leads

### ISSUE THREAD

**Issue by ioweb-gr** [frappe/erpnext#6387]
After upgrading today I'm getting this error when trying to access leads (CRM -> Lead)
`DocType Advertisement Blog Post Campaign Call Customer Exhibition Supplier Email not found`

![image](https://cloud.githubusercontent.com/assets/20220341/18589086/c7dc5d72-7c31-11e6-9557-6b4f913dec15.png)

**Comment by rmehta** [comment]
Reset customization on Lead and try again. Will fix the patch

**Comment by rmehta** [comment]
https://github.com/frappe/erpnext/commit/cf7a36ac2666a57436aac6ba6fa97b7d29c21a3d

**Comment by ioweb-gr** [comment]
I reset customization on Lead and managed to open it, however the problem was shifted to creating a quotation from lead. 

When I click on Make->Quotation from a lead I get a very similar error
DocType Contact Existing Customer Reference Advertisement Cold Calling Exhibition Supplier Reference Mass Mailing Customer's Vendor Campaign not found

![image](https://cloud.githubusercontent.com/assets/20220341/18606558/f57d23c6-7cbb-11e6-969f-389070a274c2.png)
