### ISSUE TITLE
Warehouse Tree Structre - Not working properly

### ISSUE THREAD

**Issue by Devens** [frappe/erpnext#6388]
Please see following screen-shots. 

1. "Adani Corporate House" - Warehouse has parent warehouse is "FPS Projects". Still it is being shown out of that tree. 

2. "Hose Santej" - warehouse has paranet warehouse is "Hose Unit". Still it is being shown out of that tree. 

![untitled_clipping_091716_095725_am](https://cloud.githubusercontent.com/assets/10671911/18605961/a9daa242-7cbe-11e6-9394-3f8b4ea4dbb0.jpg)

![untitled_clipping_091716_105255_am](https://cloud.githubusercontent.com/assets/10671911/18606159/c86b339c-7cc4-11e6-8be2-b1caa87e80e9.jpg)

![untitled_clipping_091716_101300_am](https://cloud.githubusercontent.com/assets/10671911/18605987/17d68d42-7cbf-11e6-832b-bdb69620876b.jpg)

**Comment by PawanMeh** [comment]
I tried the above scenario, it seems to be working fine. Maybe there is some confusion on intended usage of the system. Please find the below screen shots

- Set Up Tree as per the company warehouse structure(Parent Warehouse can be linked from the tree itself by using "Add child" and selecting "Is Group")

![screen shot 2016-09-19 at 9 52 44 am](https://cloud.githubusercontent.com/assets/20460498/18622579/df656230-7e4e-11e6-8a2f-0c3f0a3e93b8.png)

![screen shot 2016-09-19 at 9 51 39 am](https://cloud.githubusercontent.com/assets/20460498/18622564/b818ba92-7e4e-11e6-96cd-16c8b8ce95d4.png)


![1-warehousetree](https://cloud.githubusercontent.com/assets/20460498/18622541/60b2ac36-7e4e-11e6-8509-23e164e7f2f2.png)

- As you can see the field which links warehouse hierarchy is "Parent Warehouse"

![2-parentwarehouse](https://cloud.githubusercontent.com/assets/20460498/18622543/6778bd08-7e4e-11e6-8998-3d8f56bd80e3.png)

**Comment by Devens** [comment]
Dear Nabin,

Thank you for update and sorry to raise issue here.
