### ISSUE TITLE
[enhancement] quicker date picking procedure

### ISSUE THREAD

**Issue by vrms** [frappe/erpnext#6389]
issuing almost any Doctype requires the user to pick a date (some even have multiple dates to pick).
Once you click on the date field the current month pops up to click on the date of choice
![date-chooser](https://cloud.githubusercontent.com/assets/7608112/18612451/e2871732-7d8c-11e6-9173-d44274996d91.JPG)

the last days of the previous as well as the starting days of the following month can not be picked from the current months display and you have to go back one months to pick those. This happens quite often and it would be more slick whether you could pick the last days from previous / first days from following month from withing the current month's display as shown below
![date-chooser_should](https://cloud.githubusercontent.com/assets/7608112/18612473/43b968e8-7d8d-11e6-8573-29ca0a6a38d8.JPG)
It's a small enhancement which brings a better user experience. If it's not too difficult to code I'd suggest to implement it

Futhermore I'd suggest that once you click on the date (which opens the date picker as shown above) the current date (which is the default chosen date) should be highlighted automatically (which is not the current behavior) so you can manually type in the date without clicking and without have to mark it first (as in the example below)
![date-picker2](https://cloud.githubusercontent.com/assets/7608112/18612520/73c1a306-7d8e-11e6-8eb2-1e830848bca4.JPG)

**Comment by Devens** [comment]
+1

Regards,
Deven Shah
098250 60116
