### ISSUE TITLE
Email alert not working

### ISSUE THREAD

**Issue by miewling** [frappe/erpnext#6400]
Been trying to set an email alert reminder when a due date is up.

In this case, I should be notified 60 days before "expiry_date".

The following is my screenshot. Please advise if there is any wrong input. Thank you.

![capture](https://cloud.githubusercontent.com/assets/22291016/18626909/6eaa4614-7e8a-11e6-8462-6cea92aa8bcc.PNG)

**Comment by nabinhait** [comment]
I think it is correct. Please post such discussions on discuss.erpnext.com. Github Issue is for feature requests  and bug reporting.
