### ISSUE TITLE
add multiple users

### ISSUE THREAD

**Issue by neha-boddul** [frappe/erpnext#6408]
Sorry. You have reached the maximum user limit for your subscription. You can either disable an existing user or buy a higher subscription plan.
i m getting this error but i m not able to use trial version of higher subscription.

**Comment by shreyasp** [comment]
@neha-boddul 
What is your domain and what plan did you use for the initiating your trial ?

**Comment by neha-boddul** [comment]
plan i tried was 5 people login and car manufacturing is the domain. i can't afford buying the subscription 
i m doing this just because i m suppose to submit a project .please help.

**Comment by yashodhank** [comment]
@neha-boddul irrelevant demand, if you are really interested then you should download ERPNext (VM Image) from https://erpnext.com/download
Kindly refrain from opening issue, unless it is actually a bug or malfunction within ERPNext software.
For general help from community, use: https://discuss.erpnext.com/

**Comment by neha-boddul** [comment]
Sorry to disturb you sir. But can you do me a favor?
can you send me a mail specifying that free trial is not available for
multiple system users. Please help me regarding this.
 Thanking You


   Yours Faithfully


 Neha Boddul

**Comment by yashodhank** [comment]
@neha-boddul Why do you expect anyone to send you such email? checkout: https://erpnext.com/pricing it is clearly mentioned.
If can download ERPNext software as mentioned earlier and it is without any restrictions.
**Please do not post any such requests here.** This is not helpdesk channel.
