### ISSUE TITLE
Email by document field should allow more than just Owner

### ISSUE THREAD

**Issue by ASneha1** [frappe/erpnext#6409]
For doctypes such as Leave Application and Expense Claim, the Email by Document field at Email Alert, should allow more than just email to Owner. Should be able to send email alert to Leave Approver / Expense Approver upon Save : 
![image](https://cloud.githubusercontent.com/assets/16811259/18655276/08c170f8-7f1a-11e6-8abb-1906d9ba6f72.png)

**Comment by ASneha1** [comment]
Thank you, @rmehta. Wondering if there is a way to update just frappe app, as our client has gone live with a previous version of ERPNext and we would like to keep them on that version until they are ready and we have tested our customization against the latest ERPNext version.

**Comment by rmehta** [comment]
you can cherry pick the commit. Google it
