### ISSUE TITLE
Ability to Copy Roles & Permissions from one User to Another

### ISSUE THREAD

**Issue by PawanMeh** [frappe/erpnext#6410]
- User A is created & permissions/roles are created and tested for this user. These roles and permissions need to be copied to all users with similar work functions.
- Create a simple new page with single doc type & fields 'Copy From User' & 'Copy To User'. Once the fields are entered and document is saved, copy roles from one user to another.

This is generally an implementation task & an on going process for new user creation, so this will help speed up things.

---

Design

### Role Profile

- [x] Create a new DocType "Role Profile"
  - [x] child table `roles` similar to User (Has Role)
  - [x] use checkbox UI from User form in Role Profile
- [x] When Role Profile is saved, it should update `roles` in all Users linked with that Role Profile
- [x] Test case for role profile updation

### In User:

- [x] Link field `role_profile` for role profile in User (in roles section)
  - [x] When a Role Profile is selected, the roles checked in role profile should be selected in user
    - [x] use `frappe.with_doc` to load the Role Profile
    - [x] reset the child table `roles` in User

**Comment by mhbu50** [comment]
+1

**Comment by shreyashah115** [comment]
[https://github.com/frappe/frappe/pull/4222](url)

**Comment by shreyashah115** [comment]
https://github.com/frappe/frappe/pull/4222
