### ISSUE TITLE
Make comments field as rich text field

### ISSUE THREAD

**Issue by PawanMeh** [frappe/erpnext#6414]
![screen shot 2016-09-20 at 4 22 10 pm](https://cloud.githubusercontent.com/assets/20460498/18667488/68f50168-7f4e-11e6-99b5-1e9965574db0.png)

**Comment by Devens** [comment]
+1

Regards,
Deven Shah
098250 60116

**Comment by netchampfaris** [comment]
I don't think we need rich text in comments.

**Comment by rmehta** [comment]
Maybe a baby editor like the one on github :) Not priority

**Comment by PawanMeh** [comment]
Closing this, notes field has rich text functionality which can be used.
