### ISSUE TITLE
No notifications green is too distracting

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#6423]
<img width="164" alt="screen shot 2016-09-21 at 12 50 19 pm" src="https://cloud.githubusercontent.com/assets/140076/18701413/0efc985e-7ffa-11e6-8cee-2f243e416346.png">

**Comment by joezsweet** [comment]
what about to have something similar to user/help icon? 

<img width="95" alt="schermata 2016-09-21 alle 18 37 06" src="https://cloud.githubusercontent.com/assets/11652845/18720098/8c8a1424-802a-11e6-8168-46f3f6f70a46.png">

**Comment by strixaluco** [comment]
Maybe something lighter?

<img width="164" alt="navbar_notif" src="https://cloud.githubusercontent.com/assets/10875796/18735054/4bc17f62-80ad-11e6-8b9d-4e74d0ec5aa5.png">

**Comment by joezsweet** [comment]
Hi, once clicked an orizontal line will be shown: 

<img width="143" alt="schermata 2016-09-22 alle 10 17 25" src="https://cloud.githubusercontent.com/assets/11652845/18741244/5364edac-80ae-11e6-9a91-4a7309017a13.png">

Probably should be inactive link if no notifications.
