### ISSUE TITLE
Chart of Accounts tree view- View Ledger option is missing

### ISSUE THREAD

**Issue by rajanikanth18** [frappe/erpnext#6425]
Hi Team,

I am not seeing the  "view Ledger" option in chart of Accounts tree. I am using v7.0.33, in the earlier versions it used to be there. Please advise if i am missing any thing ?

We have hosted or local version of ERPNext using production VM download.
Following are the version details
ERPNext: v7.0.33

Frappe Framework: v7.0.29

Regards,
Rajanikanth

**Comment by PawanMeh** [comment]
- Please try the "Edit" option in the screen shot below,you should find what you are looking for

![screen shot 2016-09-22 at 12 37 46 pm](https://cloud.githubusercontent.com/assets/20460498/18739532/e8999ba8-80c1-11e6-9e94-ddfe04b44aa9.png)

**Comment by rajanikanth18** [comment]
Thank you Pawan,i found it.
