### ISSUE TITLE
Installation Documents

### ISSUE THREAD

**Issue by stroudmw** [frappe/erpnext#6428]
I have tried several times to get ERPNext up and running totally from scratch, but have never had any success. When I post an issue I get referred to another script that I should run. In the end, I have jumped around so much that I'm still not confident in my ability to install the product. My question is:

Where can I find a definitive set of instructions on how to install ERPNext? 
- I will be using either Ubuntu 16.04 (desktop) or 14.04 (server). 
- It doesn't need to be "all-in-one".
- it must clearly define any/all prerequisites, how to install them, and in which order.
- and, please: it must work.

Thanks!

**Comment by yashodhank** [comment]
@stroudmw This place is only for posting issues with software, bugs, usage etc.
You should seek help from community on this using https://discuss.erpnext.com

- I will be using either Ubuntu 16.04 (desktop) or 14.04 (server).
Answer: Linux Server OS will be more suitable (Debian 7/8 & CentOS 6/7)
- It doesn't need to be "all-in-one".
Answer: Minimal (without Web server, mysql, etc. pre-installed)
- it must clearly define any/all prerequisites, how to install them, and in which order.
Answer: Installer build for people who do not have full knowledge about how to deploy, ERPNext's installer **bench** tool does every software installation and basic config require you to run ERPNext/Frappe on your server.
- and, please: it must work.
Answer: It always works if you understand installation instructions and carefully follow it.
Along with that it is expected you know basic shell and server command line experience, if you dont have it then you can always hire an expert to get it sorted out.
