### ISSUE TITLE
Custom header for reports

### ISSUE THREAD

**Issue by addymuliady** [frappe/erpnext#6437]
Hi,

I would like to put an issue on custom header for all reports. At the moment, only a few reports is able to have custom .
https://discuss.erpnext.com/t/custom-report-with-header/11723/6

Thanks.

Regards

Mulyadi

**Comment by mhbu50** [comment]
+1

**Comment by Devens** [comment]
+1

**Comment by rmehta** [comment]
Add option to show letter head for report
