### ISSUE TITLE
Server-side API documentation links broken

### ISSUE THREAD

**Issue by chdecultot** [frappe/erpnext#6445]
All links to the models and server side API contents seem to be broken at the following address: http://frappe.github.io/erpnext/current/api/

![image](https://cloud.githubusercontent.com/assets/4903591/18751739/5fd46e46-80e0-11e6-8dbd-66d27fcde35a.png)

**Comment by shreyasp** [comment]
@chdecultot Looks fine at my end. Please check back again, If the problem persists try clearing your browser cache or accessing the site from another browser.

Closing the issue.

<img width="1293" alt="screen shot 2016-10-03 at 11 50 17 am" src="https://cloud.githubusercontent.com/assets/3377167/19028980/a02fd962-895f-11e6-9531-be46d51ed610.png">

**Comment by chdecultot** [comment]
Hi @shreyasp, Sorry if I wasn't clear in my bug description, but the problem is not with the above page, but with the links to the contents (i.e. 1.frappe._init_ ; 2.frappe.api ; 3.frappe.app ; ...)

I have cleared my cache but still can't access the pages:

http://frappe.github.io/erpnext/current/api/ is fine:
![image](https://cloud.githubusercontent.com/assets/4903591/19073289/779f7d82-8a3a-11e6-8722-9ab980a1b21e.png)

But if I try to access the link to "1.frappe._init_" I have a 404 error:
![image](https://cloud.githubusercontent.com/assets/4903591/19073317/a0f8ed1c-8a3a-11e6-89f8-5f9f0ca7311e.png)
