### ISSUE TITLE
Suppliers not receiving Purchase Orders. 

### ISSUE THREAD

**Issue by HelenShires** [frappe/erpnext#6450]
Morning

I have had two suppliers on recently and again today saying they are not receiving our purchase orders. I have called them to chase and they are denying receiving the PO's
Can you please look into this.
DMR Seals. Order sent this morning at 9am and still not received to either email address it was sent to.
sales or Martin Peat.
![image](https://cloud.githubusercontent.com/assets/20105451/18781504/e98d16bc-8179-11e6-8680-7bfbc47cce47.png)

**Comment by nabinhait** [comment]
Is this a problem for all the suppliers?

It is not a generic problem to everyone. Please send an email to support@erpnext.com.
