### ISSUE TITLE
Stock Summary: Suggestions

### ISSUE THREAD

**Issue by Devens** [frappe/erpnext#6459]
1. Stock Summary Report should have option to display Item Name also. (Or can be replaced for Item Code). 
2. Stock Summary Report should have Filter for Item Group
3. There should be an option to print/PDF this report. 

![image](https://cloud.githubusercontent.com/assets/10671911/18806195/6e32680a-8241-11e6-83cb-c1dba655d0b6.png)

**Comment by rmehta** [comment]
Fixed. Other than PDF
