### ISSUE TITLE
Standard Selling Rate in the V7 update

### ISSUE THREAD

**Issue by GiorgioKN** [frappe/erpnext#6464]
Hi Guys, when the new version v7 has been installed replacing the v6 (great job by the way), the standard selling rate of old items, that had prices, is now zero...is there a way to synchronize them with the old price list? or I have to add manually again?

![picture1](https://cloud.githubusercontent.com/assets/18040129/18829003/1a155bd0-83e3-11e6-945b-f0423c4528bf.png)

**Comment by nabinhait** [comment]
Please update the standard selling rate manually using Data Import Tool
