### ISSUE TITLE
Feature request - Assign Series No to invoice only on submit

### ISSUE THREAD

**Issue by ioweb-gr** [frappe/erpnext#6467]
Hello I would like to present a use case in which I'm afraid a serious error will happen and please correct wherever I'm wrong. For my example I have 

```
User1, User2
Invoice1 - A00005 
Invoice2 - A00006 
1 Naming series for invoices "A-"
```

While saving a draft invoice I noticed that the series number is assigned to it on first save. Of course I can modify the series but the number is still there if I don't modify it and any new invoice made will get assigned the next increment. 

For example 

I have User 1 with Invoice 1 saved as draft and Series No A-00005 is assigned to it. 
User 2 at the same time saves invoice 2 as draft which gets assigned a number as A-00006, however User 1 can't submit his invoice A-00005 because he's delayed due to some reasons but A-00006 is submitted on time. 

At this point, the posting date for A-00006 is set to 'Now" but for A-00005 it might be later than A-00006 and the user has no way to fix it. If he cancels it and makes a new one, the next one will become A-00007  so A-00005 will be missing. 

I can't say about other countries but in my country this is an error. If I cancel A-00005 then I have to issue a let's call it "credit invoice" to the customer, and then remake a new one. Both of us then must submit to the tax department both documents. This is a huge hussle for an invoice that's not even submitted but still in draft mode. 

What I would propose as a solution is that when invoices are saved as drafts, they get assigned a draft- series number. Afterwards when they're submitted, they should get assigned the real series number. Also the following check should occur:
1. The posting date must be later than the posting date of the invoice which was issued latest in the series.   

So the flow would be something like this

```
1. User1 saves Invoice1 as draft with Series No. DRAFT-00001 and it is to be issued under series A- 
2. User2 saves Invoice2 as draft with Series No. DRAFT-00005 and it is to be issued under series A-
3. User 2 submits Invoice2.
    3a. System checks for the proper Series No to assign to Invoice2
    3b. System checks for the invoice issued latest under series A- (for example A-00004)
    3c. System checks Invoice2 posting date is later than A-00004
    3d.
         3d-a. System finds the posting date is correct and submits and invoice
         3d-b. System finds the posting date is before A-00004 posting date and cancels submission with an error message
4. User1 submits invoice1
    4a to 4d  same as 3a to 3d
```

Sorry if this has already been addressed but I don't have an environment set up to test this use case thoroughly.

**Comment by joezsweet** [comment]
👍

**Comment by rmehta** [comment]
Maybe have a separate custom field for Invoice number that gets generated on submit (?)

**Comment by ioweb-gr** [comment]
I'm assuming this would require javascript to actually trigger populating the custom field at the `onSubmit()` event. 
Seems more complicated and dangerous imho. We would have to manage 2 invoice numbers, more naming series, more code logic, an extra field, the generation would probably be based on an extra JS piece of code which might crash because of improper implementation or because of a browser plugin conflict. 

So far from what I see in ERPNext it is becoming very client dependent with everything being decided by javascript code. A basic rule in web is "Never trust the client" for serious things. 
I can think of at least 2-3 ways a malicious person could use it to his advantage to issue fake invoices dated in the past like this utilizing previous series numbers which would also be hard to detect

I strongly think this should be validated on server side so if the logic will be implemented in the server side anyway to validate, why not also generate the number on the server side?
