### ISSUE TITLE
Activity heat map pop up not showing properly

### ISSUE THREAD

**Issue by joezsweet** [frappe/erpnext#6476]
Hi there, wip have a look at the heat map pop up on activity, it's shown in wrong position ..see pic

<img width="1280" alt="schermata 2016-09-27 alle 23 40 07" src="https://cloud.githubusercontent.com/assets/11652845/18893066/8e0c8444-850c-11e6-875c-72719f5e2691.png">

**Comment by netchampfaris** [comment]
Fixed with frappe/frappe#2140
