### ISSUE TITLE
Payment Entry Tool

### ISSUE THREAD

**Issue by mkumar9699** [frappe/erpnext#6479]
Dear Rushabh,
We want to inform you that in your new version there are too much changes in Payment tool/ Payment Entry mode while feeding data. Details are as below
1.       We can’t check the Invoice Date. We have to open the invoice to check the date.
   1.       By default it always feed outstanding amount in allocated column due to which we have to remove all the other information one by one which is wasting our too much time.
   2.       TAB key is not working which is also waste of time.
   3.       On our requirement, It was said that in the new version there will be one option to select the period of outstanding invoices but this is not in this version again.

Thanks
Mithilesh

**Comment by nabinhait** [comment]
Point 1 has been implemented
