### ISSUE TITLE
Sanctioned Amount not auto-populated from Claim Amount

### ISSUE THREAD

**Issue by ASneha1** [frappe/erpnext#6484]
Hi Team, 

When we create a new Expense Claim and enter the Claim Amount in the line item, Sanctioned Amount is not auto-populated to be the same as the Claim Amount (particularly for the first row, second row onwards it triggers). Used to be available in the previous version. Kindly help to look into this : 
![image](https://cloud.githubusercontent.com/assets/16811259/18909903/1b991390-85a8-11e6-9e14-9d1c995d369e.png)

**Comment by adfluidics** [comment]
Hi, 

This problem seems to have risen again. Please correct this, thank you!
