### ISSUE TITLE
Parent Item Group should be selectable for Sales Partner Target Table

### ISSUE THREAD

**Issue by Devens** [frappe/erpnext#6496]
Generally a sales partner is appointed as a major group of products. Hence, Parent item Group should be selectable for Sales Partner Target Table. 

![untitled_clipping_092916_040054_pm](https://cloud.githubusercontent.com/assets/10671911/18951287/05b695f6-8662-11e6-8399-fa4b28709326.jpg)

**Comment by umairsy** [comment]
https://github.com/frappe/erpnext/pull/6495
