### ISSUE TITLE
In the currency master, Ukrainian Hryvnya (Гривня) is missing. 

### ISSUE THREAD

**Issue by Sergeyzhol** [frappe/erpnext#6502]
In the currency master, Ukrainian Hryvnya (Гривня) is missing. 

NAME: UAH
Native name: Гривня
Symbol: ₴
Fraction (the best version): kop.
Fraction (Native): коп.
Fraction Units: 100
Smallest Currency Fraction Value: 0.01

Reference: https://en.wikipedia.org/wiki/Ukrainian_hryvnia

**Comment by strixaluco** [comment]
This is fixed in develop branch: https://github.com/frappe/frappe/pull/2051
