### ISSUE TITLE
msgprint dialog max height need to fix

### ISSUE THREAD

**Issue by khatrijitendra** [frappe/erpnext#6503]
1.msgprint dialog according to mobile screen expected
![mobile_expected](https://cloud.githubusercontent.com/assets/14298126/18981662/17a55e4a-86fe-11e6-884f-a2454d44cc75.png)

2. currently dialog is look like
![mobile_original](https://cloud.githubusercontent.com/assets/14298126/18981675/37d6c168-86fe-11e6-939a-a2aa678e3688.png)

3. Desktop screen 
![desktop_view](https://cloud.githubusercontent.com/assets/14298126/18981717/7566bf9c-86fe-11e6-8bdf-9e7cff4f872d.png)

**Comment by netchampfaris** [comment]
I think this is the expected view on mobile.

**Comment by khatrijitendra** [comment]
thanks @netchampfaris 

but you can check msgprint dialog on mobile screen occupied full screen.

**Comment by netchampfaris** [comment]
What I meant was, the current fullscreen message was designed for mobile view.

**Comment by khatrijitendra** [comment]
1. mobile_view

![mobile_view](https://cloud.githubusercontent.com/assets/14298126/19034003/df137598-897e-11e6-8024-89831b9e40a6.png)

2. desktop_view
 
![desktop_view](https://cloud.githubusercontent.com/assets/14298126/19034006/e4c6521c-897e-11e6-9d99-0da46498ef5d.png)

so is it possible to see back ground form in mobile view.

**Comment by netchampfaris** [comment]
@khatrijitendra Yes, it is possible.

**Comment by sbkolate** [comment]
@netchampfaris Default Full Screen for mobile view is not handy, if you can configure default size of dialog to its content size, then it will be very useful.

As @khatrijitendra  done this configuration in following image:
One can see full form in Background using scroll down.
<a href="https://cloud.githubusercontent.com/assets/14298126/18981662/17a55e4a-86fe-11e6-884f-a2454d44cc75.png" target="_blank"><img src="https://cloud.githubusercontent.com/assets/14298126/18981662/17a55e4a-86fe-11e6-884f-a2454d44cc75.png" alt="mobile_expected" style="max-width:100%;"></a>

Thanks,
Sambhaji

**Comment by netchampfaris** [comment]
@rmehta Thoughts on this?

**Comment by rmehta** [comment]
This is bootstrap default. Makes sense for small messages to have a smaller dialog / modal. Maybe we can do it if its not too hard.

**Comment by netchampfaris** [comment]
Fixed with frappe/frappe#2153
