### ISSUE TITLE
Job openings appearing under /jobs page even without selecting ‘publish on website’

### ISSUE THREAD

**Issue by neeraj022** [frappe/erpnext#6514]
While creating a job opening, I didn't select 'publish on website'. Still that job is appearing on the website.

**Comment by neeraj022** [comment]
Even after closing a job opening, its visible on the jobs page.

**Comment by rmehta** [comment]
@neeraj022 you want to send a pull-request for this one?

**Comment by rmehta** [comment]
Fixed
