### ISSUE TITLE
To update Delivered Qty Field in Sales Order

### ISSUE THREAD

**Issue by Devens** [frappe/erpnext#6517]
We understand (as informed by Umair)  that "Delivered Qty" field is updated in Sales Order Item table only if Delivery Note is created from Sales Invoice. It should be updated when Sales Order is created from Delivery Note also. 

![image](https://cloud.githubusercontent.com/assets/10671911/19011233/8a105c5a-87ad-11e6-9211-c80f19ce39f9.png)

**Comment by nabinhait** [comment]
> We understand (as informed by Umair) that "Delivered Qty" field is updated in Sales Order Item table only if Delivery Note is created from Sales Invoice. It should be updated when Sales Order is created from Delivery Note also.

@Devens Is this correct explanation of the issue? Or all "Sales Order" term should be replace by "Sales Invoice".

**Comment by Devens** [comment]
@nabinhait - Extremely Sorry. Please replace "Sales Invoice" In place of "Sales Order". :)

**Comment by rmehta** [comment]
This is fixed
