### ISSUE TITLE
Numbering of accounts in chart of accounts

### ISSUE THREAD

**Issue by mhbu50** [frappe/erpnext#6520]
I wish that it would be possible to number each account in the chart of accounts, and use these numbers for whenever selecting an account, instead of the name.

**Comment by PawanMeh** [comment]
You can create Account as 1000-Fixed Assets and so on

![screen shot 2016-10-03 at 8 48 24 am](https://cloud.githubusercontent.com/assets/20460498/19026667/304ea024-8946-11e6-8e48-20b5d05883e6.png)

**Comment by mhbu50** [comment]
Numbering should be in different field and fill in backend.
It is better to be able to enable and disable this feature from account setting

**Comment by gregoribic** [comment]
I think this option is a must have one.

**Comment by vrms** [comment]
+1 to separated field for account Codes. Especially as it has been stated several time how much Accountants have to say when a company decides on which ERP system to use. And adding Account Codes (which is a standard in the accounting realm) would be a first step into giving the Accountants what they want

**Comment by jwrober** [comment]
https://github.com/frappe/erpnext/issues/8194

**Comment by nabinhait** [comment]
Sent a PR, closing this.
