### ISSUE TITLE
Completed sales order still shown as outstanding

### ISSUE THREAD

**Issue by nununo** [frappe/erpnext#6521]
Somehow a completed sales order SO-00012 is still shown as outstanding:

<img width="751" alt="screen shot 2016-10-02 at 22 31 23" src="https://cloud.githubusercontent.com/assets/532049/19023860/492c25ea-88f0-11e6-8329-a549b176a6a3.png">

My cloud domain: tsuristudio.erpnext.com

Please advise.

Thanks,
Nuno

**Comment by rohitwaghchaure** [comment]
Hi @nununo ,

I am not able to reproduce this issue on local system, can you provide the steps to reproduce the issue

Thanks, Rohit

**Comment by nununo** [comment]
Hello @rohitwaghchaure,

1. I go to Selling
2. I click the red circle with a number 4 (meaning 4 sales orders in need of attention)
3. I get the list I showed you above. While 3 are indeed outstanding, the 4th is clearly closed, green, and clearly shouldn't be listed there. This only happened with this exact sales order but I didn't do anything different to it, as far as I know.

Can't you look into my cloud server and check it out?

Thanks,
Nuno

**Comment by nabinhait** [comment]
@nununo Please send an email to support@erpnext.com with login credentials, so that we can check into the issue in your account from backend.

**Comment by nununo** [comment]
Hello, you closed the issue  but it is still happening. Does that mean you'll be tracking the issue in some other way?

**Comment by rohitwaghchaure** [comment]
Nope actually I have send PR and it's under review

**Comment by nununo** [comment]
Thanks!
