### ISSUE TITLE
ERPNext App : Buttons not shown properly

### ISSUE THREAD

**Issue by ASneha1** [frappe/erpnext#6522]
Hi, 

The following buttons (boxed in Red) are not shown properly on both Android and iPhone app of ERPNext. Believe this is because of the introduction of the ? icon (boxed in Blue) in the first header bar. Kindly help to look into this:
![image](https://cloud.githubusercontent.com/assets/16811259/19025886/8ed024d2-8951-11e6-98d5-afa236fc5a3c.png)

**Comment by netchampfaris** [comment]
What version are you on?

**Comment by ASneha1** [comment]
This was noticed in version V7.0.27.

**Comment by netchampfaris** [comment]
This was fixed with frappe/frappe#2053

**Comment by ASneha1** [comment]
Hi @netchampfaris, 

We had taken in the commit. However, the fix has not been evident. Are we required to run any command in the backend to refresh the site/app? 

Thank you.
