### ISSUE TITLE
Making Sales quotation from  Supplier quotation

### ISSUE THREAD

**Issue by Priyanka-IAS** [frappe/erpnext#6523]
Hi,

Since we are trading company, our Sales quotations are based on our supplier quotations. We would like to be able to make the Sales quotation from supplier quotation based on a fixed markup in price.

Let me know if you need any further details.

Regards,

Priyanka

**Comment by gladwynlewis83** [comment]
I second this entirely, this feature would be absolutely amazing +1

**Comment by bhupennewalkar1337** [comment]
Fixed

**Comment by Priyanka-IAS** [comment]
Awesome!! :)

When can we expect to see this online?

**Comment by nabinhait** [comment]
The feature will go live with v7.3 release (in a month or so)

**Comment by Priyanka-IAS** [comment]
Hi,

Any update on this feature? When can we expect this?

Regards,

Priyanka Kaushal

Director Operations

Indo Aerospace Solutions  (P) Ltd

Visit us on-line at www.indo-aerospace.com <http://www.indo-aerospace.com/>

**Comment by Priyanka-IAS** [comment]
Hi guys,

any update on this?

- Priyanka

**Comment by Devens** [comment]
This would be useful. +1

Regards,
Deven Shah
098250 60116

**Comment by Priyanka-IAS** [comment]
I see that we can now make a Quotation from a Supplier quotation, however I would like to know if there is any way to put in a standard percentage profit to be applied to the price while making the Quotation. 

- Priyanka
