### ISSUE TITLE
Project Closure

### ISSUE THREAD

**Issue by PawanMeh** [frappe/erpnext#6541]
Currently there is no Project Closure mechanism in ERPNext.Below are some small changes that would help

- [ ] Add new Project Status value 'Closed'

- [ ] 'Closed' and 'Cancelled' projects should not be available for entering time-sheets

**Comment by nabinhait** [comment]
- As Project is not a submittable form, "Cancelled" status is for cancelling / closing the project. 

- Added filters in project query in timesheet
