### ISSUE TITLE
Timesheet Error

### ISSUE THREAD

**Issue by PawanMeh** [frappe/erpnext#6542]
- Enter the below fields in a timesheet (Enter Hours but leave From Time blank)

![screen shot 2016-10-05 at 9 42 55 am](https://cloud.githubusercontent.com/assets/20460498/19100852/1a26540e-8ae0-11e6-90ba-aa5f909491cb.png)

- On Save, User gets a system error 

![screen shot 2016-10-05 at 9 45 03 am](https://cloud.githubusercontent.com/assets/20460498/19100877/6d2725ac-8ae0-11e6-95f6-d8faf7fda481.png)

- The user should get a error message saying "From Time" is required if Hours are entered.

**Comment by AdamN1** [comment]
Hi,
the timesheet supports counting positive and negative hours but validation stop us from saving data.

I proposes to change the validation to:
```
if not data.from_time or not data.to_time:
    frappe.throw(_("To date cannot be empty"))
```

Usecase
![image](https://user-images.githubusercontent.com/3781249/205492547-08f0cd0a-2ad4-45fb-8b1c-c7792e653f96.png)

If employee need to stay longer (overtime) he can pick up these hours in the next days.

**Comment by AdamN1** [comment]
@nabinhait can you verify my proposition?
