### ISSUE TITLE
Chart of account, currency visualization issue

### ISSUE THREAD

**Issue by joezsweet** [frappe/erpnext#6546]
Hi there, 

got an issue on chart of accounts, it shows Dr other than company currency, see pic:

<img width="1124" alt="schermata 2016-10-05 alle 09 53 37" src="https://cloud.githubusercontent.com/assets/11652845/19105371/e381ac4e-8ae1-11e6-986a-bbc5e5c01cc7.png">

**Comment by nabinhait** [comment]
Here, Dr stands for Debit and Cr for Credit

Company currency is Euro, which is shown as prefix.

**Comment by joezsweet** [comment]
Ah ..i didn't get it ..probably would be nice to have whole word like Credit (green) or Debit (red) ..
