### ISSUE TITLE
Conditional workflows

### ISSUE THREAD

**Issue by rohanjdr** [frappe/erpnext#6548]
Ability to create create conditional workflows in ERPNext. 

For example, say, the workflow I'm dealing with is:

Task A -> Task B -> Task C -> Task D ->Submit

But before the workflow can move to Task C from Task B, Task B1 needs to be completed but is not associated with the this particular workflow. 

To add to the above, say there's the additional constraint that Task B1 can't be done until finishing Task B.

**Comment by mhbu50** [comment]
+1

**Comment by majdalhalabi1994** [comment]
+1

**Comment by mhbu50** [comment]
I think this is done since V11.
You can close it now.
