### ISSUE TITLE
POS on a terminal and timeouts

### ISSUE THREAD

**Issue by ialhashim** [frappe/erpnext#6549]
We have a machine that is always running with the POS page. However, it seems after a certain time (session timeout? usually following day) the page blocks the user out and we have to login again, several times, to avoid all the access error messages on screen.

It would be helpful for the system to consider any timeout restrictions and then gracefully redirect the user to the login page to avoid the annoying issue we are seeing.

**Comment by nabinhait** [comment]
Please check "Session Expiry" value in the System Settings page.

<img width="459" alt="screen shot 2016-10-06 at 12 45 01 pm" src="https://cloud.githubusercontent.com/assets/836784/19143610/c53f065a-8bc2-11e6-896a-f9578ea35b40.png">

**Comment by nabinhait** [comment]
@rohitwaghchaure Is this the same issue you fixed via https://github.com/frappe/erpnext/pull/6969

**Comment by rohitwaghchaure** [comment]
@nabinhait  Yes

**Comment by jay-parikh** [comment]
@nabinhait, @rohitwaghchaure  If this is fixed, can you please close this issue?
