### ISSUE TITLE
critial : cannot save at email Notification Control Not Saved

### ISSUE THREAD

**Issue by hoeichia** [frappe/erpnext#6558]
the update button is not working
will not save the setting

**Comment by shreyasp** [comment]
@hoeichia Can you please elaborate the problem and steps to reproduce the problem that you are having, so that we can pinpoint the issue and get it fixed.

**Comment by PawanMeh** [comment]
@shreyasp , I think the notification Control Update button is what is being referred to here.

![screen shot 2016-10-07 at 11 47 33 am](https://cloud.githubusercontent.com/assets/20460498/19180500/dbeb00c2-8c83-11e6-9f1c-8153ca832389.png)

If you check a check box and click on "Update" it does not appear to do anything.

**Comment by shreyasp** [comment]
@PawanMeh Thanks. I will check this issue.

**Comment by hoeichia** [comment]
yes, that what i mean. nothing saved when click update,
click on refresh will back to same setting
