### ISSUE TITLE
Upgrade Reset the Timesheets Status

### ISSUE THREAD

**Issue by Ooops-404** [frappe/erpnext#6571]
Hi,

I just noticed that the upgrade reset most of my timsheets to Submitted, but I know for a fact that the majority had been billed already...

What can be done now?

**Comment by rohitwaghchaure** [comment]
Hi @Ooops-404 

Can you share erpnext version?

**Comment by Ooops-404** [comment]
Hi @rohitwaghchaure 

ERPNext: v7.0.58
Frappe Framework: v7.0.43

**Comment by rohitwaghchaure** [comment]
Hi @Ooops-404 ,

Can you pull the latest update and check
