### ISSUE TITLE
Material Request - Required Date Auto Set

### ISSUE THREAD

**Issue by Priyanka-IAS** [frappe/erpnext#6573]
Hi, 

Before the current upgrade, the Required Date in Material Request field used to be blank. When we would set the the date in the first item, all items would be updated with this date. Now, this date defaults to Todays date and we need to manually change the date in each item.

There needs to be an option for Auto set date in all items, or just leave the field blank as before.

Regards,

Priyanka
Indo Aerospace Solutions Pvt Ltd

**Comment by Priyanka-IAS** [comment]
Please re-open. Auto set date not working again. All dates are blank, need to manually populate each one of them.

**Comment by umairsy** [comment]
Fixed.

![mr-date](https://user-images.githubusercontent.com/910238/30022122-8dd4edb2-9187-11e7-93d0-f53ac4c74416.gif)
