### ISSUE TITLE
Feature Request: Stock Levels for Alternate Items and BoM items. 

### ISSUE THREAD

**Issue by Devens** [frappe/erpnext#6580]
![untitled_clipping_100816_105137_am](https://cloud.githubusercontent.com/assets/10671911/19210604/044169f0-8d45-11e6-8b6b-83d49d731754.jpg)

**Comment by joezsweet** [comment]
What u mean for alternative item and where is possible to set it?

**Comment by Devens** [comment]
One of the "Work Around" can be from Related Items, as shown in following screenshot. (But, I am not sure whether this is available for all). 

If not, there should be some feature as it's very much generic requirement. Especially, when we define differnt items for differnt brands, usually "Alternate Item" is required. 

![untitled_clipping_100916_095646_am](https://cloud.githubusercontent.com/assets/10671911/19217912/9a575ff0-8e06-11e6-9e28-f6de2ab07fd2.jpg)

**Comment by joezsweet** [comment]
Cant find that feature out of the box, did u customize it?

**Comment by Devens** [comment]
@joezsweet - Yes. It's customized one. But, Alternate item is more of a generic requirement and it should be available in core module, i suggest.

**Comment by joezsweet** [comment]
@Devens you mean Alternative Item? So that it can be ordered if not available at supplier side?

**Comment by Devens** [comment]
@joezsweet - Yes. Moreover, it can be used in manufacturing as well as it can be suggested to customer.

**Comment by deepeshgarg007** [comment]
@Devens Alternate Item can be configured now in BOMs
