### ISSUE TITLE
[V7] ERPNext crashes when trying to upload image

### ISSUE THREAD

**Issue by Gleisson03** [frappe/erpnext#6582]
Some time ago I reported a problem and a team member resolved (Thank you so much.). Now I'm having the same problem. 
Follow the link from the description of the problem: https://github.com/frappe/erpnext/issues/6052

Follow this tip of mehta, but had the same problem:

> rmehta commented on 11 Aug
> 
> You have to save it before you the image gets saved. Its a UX issue. Fixed in local. Will push in a bit.
> 
> Thanks for reporting.

**Comment by rmehta** [comment]
@Gleisson03 can you explain clearly the steps you followed (with screenshots if possible)

@netchampfaris attachments should be disallowed unless a document is saved.

**Comment by Gleisson03** [comment]
# This way does not work.

Of course I can. If you need any more information, just let me know.

![1000 mili](https://cloud.githubusercontent.com/assets/13992475/19256178/cc63965a-8f3a-11e6-8a96-8270a7d8893e.gif)

**Note: Before these screen shots, I had already uploaded the file to a folder using the "File Manager". Maybe that's the problem?**

.
.
# This way it works.
If I attach the photo directly on the item, as in the following example, everything works normally.

![1000 mili](https://cloud.githubusercontent.com/assets/13992475/19256392/ea84a6fe-8f3c-11e6-9a06-6bcaa43cfd39.gif)

**Comment by netchampfaris** [comment]
@Gleisson03 Are you still facing this problem?
I can't seem to replicate this issue on my local machine.
