### ISSUE TITLE
After Merging Items, it shows all warehouses in Stock Level Section

### ISSUE THREAD

**Issue by Devens** [frappe/erpnext#6585]
After Merging Items, it shows all warehouses in Stock Level Section. It should display only relevant warehouses where transactions have taken place. Please see following screenshot. 

![image](https://cloud.githubusercontent.com/assets/10671911/19217904/162ba8ee-8e06-11e6-9d99-03f3b1c475ca.png)

**Comment by nabinhait** [comment]
fixed
