### ISSUE TITLE
Show Credit in Account Currency within Credit Note print format

### ISSUE THREAD

**Issue by ManarSlik** [frappe/erpnext#6593]
The Amount at Credit note always shown in company currency, it's better to have choice of showing it in Account currency.

**Comment by nabinhait** [comment]
Which document are you using to book credit note? If you are making negative sales invoice for credit note, then you can select yourself which fields will be shown in credit note print format.

**Comment by ManarSlik** [comment]
Sometimes i use journal entry to create credit note specially when the items are services not products.

**Comment by saurabh6790** [comment]
@ManarSlik As credit note is generally used to repay money to a customer. Generally, these payments take place between debtors account and company's bank or cash account. Thus, currently, the system shows the amount in companies account currency. 

Please share your scenario.
