### ISSUE TITLE
[CRITICAL] can't made purchase return 

### ISSUE THREAD

**Issue by hoeichia** [frappe/erpnext#6595]
when made purchase receipt again return
Incorrect value: Grand Total (Company Currency) must be >= 0.0 show..

setting the partial return item value also show Error: Accepted Quantity > Recd Quantity

and even you can submit full quantity return againt the purchase receipt, the stock summary will show actualy 100 and waiting (30) -----100 (30)
but is should not be waiting item

also there is no easy way to create return...

**Comment by hoeichia** [comment]
Row #1: Rejected Qty can not be entered in Purchase Return
the accepted and rejected logic seems not right
![image](https://cloud.githubusercontent.com/assets/22652544/19245532/394e58a4-8f54-11e6-92f0-777a7111c3f6.png)

**Comment by hoeichia** [comment]
figured it out... but still seems need to further polish the terms

**Comment by yashodhank** [comment]
@hoeichia Most welcome! here you go: https://translate.erpnext.com
