### ISSUE TITLE
report that have landscape layout cant show properly

### ISSUE THREAD

**Issue by hoeichia** [frappe/erpnext#6596]
alot of report cant show properly with correct layout
![image](https://cloud.githubusercontent.com/assets/22652544/19246274/0dc3f2b2-8f58-11e6-8232-b4e083c0c821.png)

Item-wise Sales Register cant export pdf also for example

**Comment by Devens** [comment]
+1

**Comment by rmehta** [comment]
This needs to be fixed in preview

**Comment by strixaluco** [comment]
Still reproducible as of ERPNext: v8.x.x-beta (95233a6) / Frappe Framework: v8.x.x-beta (eb079e1)
