### ISSUE TITLE
Timesheet calendar view: All timesheets shown on current day

### ISSUE THREAD

**Issue by superlack** [frappe/erpnext#6597]
All timesheets shown in calendar are showing up on current day.

![untitled](https://cloud.githubusercontent.com/assets/12856084/19247873/f41f54d0-8ee1-11e6-9aaf-783ac95272b0.png)

**Comment by bcornwellmott** [comment]
Can you give more details? What version of ERP/Frappe are you on?

Also, can you give screenshots of a couple of the timesheet tasks so we can see what days they are supposed to be on?

**Comment by superlack** [comment]
ERPNext: v7.1.0-beta

Frappe Framework: v7.1.0-beta

The timesheets are not using tasks, but rather just Activity Type, From Time, Hrs, and Project.

As you can see from these screenshots the first of the calendar list (TS-00371) is submitted on September 25th, and the Calendar view continues to all timesheets on the current day.  
![tsts](https://cloud.githubusercontent.com/assets/12856084/19501062/5488d5fa-9557-11e6-857f-d94c74bdd5cf.png)
![tsts2](https://cloud.githubusercontent.com/assets/12856084/19501063/548f6640-9557-11e6-9ed4-9ea00b507521.png)
