### ISSUE TITLE
A lot of forms are cached, not able to return selection unless F5 refresh 

### ISSUE THREAD

**Issue by hoeichia** [frappe/erpnext#6599]
eg 
i click setup print format builder, and selected a doc to edit
after edit , i click save > setup > print format builder again, last document show up instead of choose document screen, i have to press F5 to get there
this also apply to alot of pages which i forgot

![image](https://cloud.githubusercontent.com/assets/22652544/19255305/1a9a9446-8f8f-11e6-95c6-b5d620aa53fe.png)

**Comment by paulator** [comment]
Same issue here with Release v7.1.20.

**Comment by rmehta** [comment]
This is fixed
