### ISSUE TITLE
When click pdf of the sales invoice, quotation or sales order, image letterhead is not attached, format is all messup

### ISSUE THREAD

**Issue by hoeichia** [frappe/erpnext#6600]
in print view

![image](https://cloud.githubusercontent.com/assets/22652544/19255675/fd915b56-8f92-11e6-9144-acfeacef076d.png)

in exported pdf
![image](https://cloud.githubusercontent.com/assets/22652544/19255689/21c103b4-8f93-11e6-8f8a-0c2986f70787.png)

**Comment by rmehta** [comment]
You need your PDF image to be accessible publicly (on your machine) with urls like `http://` instead of relative urls.

Please report if this is still an issue

**Comment by PawanMeh** [comment]
Closing this for now, if this is still an issue kindly reopen. You can also add images directly to letter head if this is still a problem and check.
