### ISSUE TITLE
No submenu Company under Accounts Setup

### ISSUE THREAD

**Issue by jodumont** [frappe/erpnext#6601]
Hi;

Saddly, I can't find the submenu Company under Accounts > Setup
I'm using ERPNext: v5.0.7 and Frappe Framework: v5.0.6
a screenshot just in case you don't believe me : https://imgur.com/a/Gcx9i
;)

**Comment by nabinhait** [comment]
We don't support version 5 anymore. You have to debug yourself, it might be due to permissions. Can you access the company via "awesome search bar"?
