### ISSUE TITLE
Item-wise Sales Register, mode of payment column don't have data inside 

### ISSUE THREAD

**Issue by hoeichia** [frappe/erpnext#6603]
no data inside the mode of payment column
all the details gone when select the drop down box sorting for mode of payment too

![image](https://cloud.githubusercontent.com/assets/22652544/19282503/3b6579a6-9021-11e6-8a69-7b1983fb51f6.png)

**Comment by nabinhait** [comment]
Which version are you using? This is fixed in the latest version.
