### ISSUE TITLE
Filters in Left Side Column in List View

### ISSUE THREAD

**Issue by Devens** [frappe/erpnext#6612]
Pl refer following screenshot. 

There should be two different properties for Display in left column bar of list view AND display of field as a column in list view. (There are chances that if it's shown in Left Column bar, we can have some other field being displayed in list table. )

![untitled_clipping_101216_084652_pm](https://cloud.githubusercontent.com/assets/10671911/19359154/78f497cc-9196-11e6-94dd-e7458dde6317.jpg)

**Comment by rmehta** [comment]
I think this will be fixed by the new configurable filter dashboard
