### ISSUE TITLE
As there are existing transactions for this item, you can not change the value of Has Serial No

### ISSUE THREAD

**Issue by opsninja1** [frappe/erpnext#6614]
I really need to be able to change the "Has Serial No" box whether the item has transactions or not.  When ordering new product, it is often unknown whether the manufacturer uses serial numbers or not.  How do I do this?

**Comment by KanchanChauhan** [comment]
@opsninja1 You might have to create a new item, since this item previously had serial no and have transactions associated with it, you cannot change it.

**Comment by manasan3010** [comment]
@KanchanChauhan, The problem with your suggested method is, it is not possible to create another item with the same attributes as of the disabled item. And the backend validation does not allow that on save. So, the system has to either check whether the duplicate item has been disabled OR allow the user to add Serial No for the future transactions of this item after the current stock has been cleared.
