### ISSUE TITLE
Monthly Salary Report

### ISSUE THREAD

**Issue by joshiparthin** [frappe/erpnext#6623]
@KanchanChauhan 
I am raising this issue for Salary Report.
The issue is that, i have created a dummy salary slip for september and when i see it under report the fields for earning as well for deduction are displayed twice. I ll post an image for the same to make you understand the issue in much clearer way..

![screenshot from 2016-10-17 11 45 53](https://cloud.githubusercontent.com/assets/6594877/19427258/66b2b252-9460-11e6-9a04-86af413b0053.png)
![screenshot from 2016-10-17 11 46 03](https://cloud.githubusercontent.com/assets/6594877/19427264/784fdf8a-9460-11e6-8293-78e43512e063.png)

**Comment by KanchanChauhan** [comment]
@joshiparthin I was able to replicate the issue at my end as well, we will look into it as soon as possible. Thanks for reporting it.

**Comment by joshiparthin** [comment]
@saurabh6790 thanks for the fix. Appreciate it. Is your pull request merged ? if not how do you suggest I should take it up in my project? Besides copy and paste of file, but I dont think its a good pratice...

**Comment by nabinhait** [comment]
It will be released today
