### ISSUE TITLE
Need to display additional column in ListView place of down arrow/drop down key of a table 

### ISSUE THREAD

**Issue by mkumar9699** [frappe/erpnext#6631]
1. I need one more column "Cost_Center" should be visible in the ListView of  Journal Entry Account. In " Journal Entry Account" the down arrow navigation can be removed because it's not necessary.
2.  I want to add one more column  "delivery_note" in the ListView  of "Sales Invoice Item" in "Sales Invoice". In "Sales Invoice Item" the down arrow navigation can be removed because it's not necessary.  
   While In Previous version I did that (i.e. Delivery note display in sales Invoice Item and Cost center in Journal Entry).
   Please provide that. It will be beneficial for ERPNext users.
   Please find the snapshot of Sales Invoice Item as a table in Sales Invoice
   ![image](https://cloud.githubusercontent.com/assets/16901262/19440062/149eeb64-949e-11e6-9569-4480cb34be52.png)

**Comment by jwrober** [comment]
This is not a defect or enhancement request. You can do this on your own. Please open a discussion on this subject in the forum - https://discuss.erpnext.com/ - to get help with this.
