### ISSUE TITLE
Feature Request: Tracking Assets issued to employees

### ISSUE THREAD

**Issue by Devens** [frappe/erpnext#6632]
Many times organization issues movable assets to employee like laptop, bike, tooling sets et al.

We request a feature wherein there can be provision for...
- Issuing asset to employee
- Keeping track of the same (Also display in Employee "Related Doc" header bar)
- Receiving back the issued assets/settlement against the same.

@umairsy - On your request please.

**Comment by PawanMeh** [comment]
Kindly close issue #6613. It seems like a duplicate of this issue.

**Comment by PawanMeh** [comment]
In the latest v11 release, fields for 'Owner' and 'Custodian' have been added on the Asset doctype. Hope this would help.
