### ISSUE TITLE
System settings: Time zone list empty

### ISSUE THREAD

**Issue by joezsweet** [frappe/erpnext#6635]
Hi there, got a time zone list empty on System Settings, see pic of the field definition:

<img width="1164" alt="schermata 2016-10-18 alle 09 10 09" src="https://cloud.githubusercontent.com/assets/11652845/19467697/d6631f8a-9512-11e6-9263-eae469f6198b.png">

**Comment by nabinhait** [comment]
Time Zone options are loaded via js
