### ISSUE TITLE
Work in progress wharehouse not populated on production order

### ISSUE THREAD

**Issue by hiousi** [frappe/erpnext#6636]
Hi,
from material request, the new production orders are not getting the value of the default Work-Porgress Warehouse and default Source Warehouse

**Comment by nabinhait** [comment]
Currently there is no settings for default source/WIP warehouse.

**Comment by hiousi** [comment]
I see a setting named "Default Work In Progress Warehouse" in Manufacturing settings

**Comment by nabinhait** [comment]
Thanks for correcting me, reopening the issue

**Comment by dawoodjee** [comment]
This is great. But different products may need different Source, WIP and Finished Goods warehouses. Or is there an existing workaround?
