### ISSUE TITLE
Sending email problem

### ISSUE THREAD

**Issue by makelport** [frappe/erpnext#6638]
Dear Sir/Madam,

We are using Erpnext for our company for now single user. We have been sending our purchasing orders from cloud more than a month. But for last two days, our emails do not reach to their recipients. We have contacted our email provider, there seems to be nothing wrong there. 

We are new to Erpnext, maybe our problem is a simple one sorry for that in advance.

Would you please give us any information why would such a problem may occur.

Regards
Emre

**Comment by nabinhait** [comment]
Can you please send an email to support@erpnext.com with account name and login credentials.
