### ISSUE TITLE
[BUG] Percent Billed does not include Payment Entries

### ISSUE THREAD

**Issue by bcornwellmott** [frappe/erpnext#6643]
Issue created on discuss.erpnext.com: https://discuss.erpnext.com/t/payment-entry-doesnt-count-against-billed/16927

The percent billed field does not include payments made through the payment entries list. In those cases, the per_billed field mistakenly shows 0% when a payment has been made against it.

**Comment by PawanMeh** [comment]
Do you have an Invoice against which you are paying the advance? Possibly %billed could be related to the Supplier Invoice

**Comment by bcornwellmott** [comment]
My understanding is that an invoice can only be created if the full payment has been made, and also needs a purchase receipt (if the system settings require that).  If I understand it correctly, a Payment Entry is made before the items are received, and a Purchase Receipt and Purchase Invoice are made once the items are received.

The issue is that until items are received, there is no way to increase the percent billed data field for the Purchase Order Items.

**Comment by bcornwellmott** [comment]
Closing this issue. I misunderstood the difference between "% Billed" and "% Paid". The PO document shows Advance Paid, which is sufficient to understand.
