### ISSUE TITLE
Delete, Insert Above & Insert Below buttons not working

### ISSUE THREAD

**Issue by PawanMeh** [frappe/erpnext#6646]
- After the latest bench update, the grid seems to be messed up. The delete, insert above, insert below buttons are not working. When you click on them, nothing seems to happen.

![screen shot 2016-10-19 at 11 51 51 am](https://cloud.githubusercontent.com/assets/20460498/19507716/72917bc4-95f2-11e6-8cc5-5140b41cd72a.png)

**Comment by slushpuppy** [comment]
I can confirm the same issue. Dialogue box doesn't go away

**Comment by nabinhait** [comment]
@rmehta Can you please check this? It's urgent.

**Comment by mohsin4228** [comment]
Just Applied the above provided fixes in my app, but problem still there after build.

**Comment by PawanMeh** [comment]
It is working fine after the update, closing this issue for now.
