### ISSUE TITLE
Student window error

### ISSUE THREAD

**Issue by samehmreda** [frappe/erpnext#6649]
[Error.pdf](https://github.com/frappe/erpnext/files/538356/Error.pdf)

Hello , the attached error appeared when i tried to open student icon & when i press " report this issue " at the end of the error , nothing happened.

please advise.

Thanks,

Sameh,

**Comment by nabinhait** [comment]
We have pushed a fix, are you still getting the issue?

**Comment by samehmreda** [comment]
thanks , it works now


appreciate your efforts


________________________________
