### ISSUE TITLE
Overflow when image is attached at Child Table

### ISSUE THREAD

**Issue by ASneha1** [frappe/erpnext#6650]
Hi, 

When we attach an image at the Expense Claim field Description, the image overflows like so : 
![image](https://cloud.githubusercontent.com/assets/16811259/19511937/3105f4d0-961c-11e6-9f6a-b1c613baa80b.png)

We have disabled grid edittable to check but unable to avoid this overflow. Kindly advice how we can tackle this. 

Thank you.

**Comment by netchampfaris** [comment]
This has been fixed with 7.1

**Comment by abue90** [comment]
@netchampfaris We currently on v7.0.x branch. Can we have specific commit of the fix for us to cherry-pick?
