### ISSUE TITLE
Issue with Grid Details

### ISSUE THREAD

**Issue by PawanMeh** [frappe/erpnext#6660]
1. Open doc type page and click to view the details
![screen shot 2016-10-20 at 9 11 16 am](https://cloud.githubusercontent.com/assets/20460498/19545608/469d9e2c-96a5-11e6-9297-bb41d1eaff0f.png)

1. The details open up
![screen shot 2016-10-20 at 9 09 41 am](https://cloud.githubusercontent.com/assets/20460498/19545618/5ef4a2b8-96a5-11e6-9324-88d9f183c4a4.png)

1. Close the details after making changes or without making any changes and again click to view details
![screen shot 2016-10-20 at 9 11 16 am](https://cloud.githubusercontent.com/assets/20460498/19545637/7d204dfa-96a5-11e6-875c-776e3f49225b.png)

1. You will notice that the details don't open up, go to administrator and reload, the details would then open up.

**Comment by nabinhait** [comment]
Can't replicate, are you using latest version?

**Comment by mohsin4228** [comment]
facing this issue on Purchase Invoice/Receipt page on "Item" rows, but its working fine on Stock Entry page. 
I am using v7 (latest).

**Comment by PawanMeh** [comment]
This is working now, maybe it had something to do with the Grid issues with the earlier update.
