### ISSUE TITLE
Including Employees as Party Type in JV sub-table

### ISSUE THREAD

**Issue by Devens** [frappe/erpnext#6668]
In JV many times expense is not related to only customer & supplier Party Type. We suggest to add Employees here. This can be very useful for recording general expenses wherein party is an employee. 

![untitled_clipping_102116_071900_am](https://cloud.githubusercontent.com/assets/10671911/19584032/f7f5c3d4-975e-11e6-8e40-f00bc8a92224.jpg)

**Comment by PawanMeh** [comment]
Employee related expenses can be also managed with Expense Claims and Loans etc. can be managed by creating Employee Loan Account which can be used in JV. Please refer to the [link](https://frappe.github.io/erpnext/user/manual/en/human-resources/articles/employees-loan-management) for managing employee loans.

Are there any other scenarios for which you are looking for this particular change?

**Comment by Devens** [comment]
Please refer to following type of entries. Wherein person himself is not claiming for expenses, but accountant has to pay in cash and book the expenses.In such case, name of employee in party can be very useful. You would say that it can be mentioned in User Remarks. Agreed but name menitoned in party field would be very useful for generating reports with various filters. 

For eg. Telephone expense done/paid/reimbused to Employee-X over the period of time can be easily found out with the help of above sugested provision. 


This was wide used practice in famous software like Quickbooks etc. (In fact, in QB, they display all the contacts also for "Party Field" they have given name to that fields as "payee". 

![untitled_clipping_102716_082040_pm](https://cloud.githubusercontent.com/assets/10671911/19772088/b0c8300e-9c82-11e6-9d8a-ccfa0b41e43f.jpg)

**Comment by Devens** [comment]
Please refer to following type of entries. Wherein person himself is not
claiming for expenses, but accountant has to pay in cash and book the
expenses.In such case, name of employee in party can be very useful. You
would say that it can be mentioned in User Remarks. Agreed but name
menitoned in party field would be very useful for generating reports with
various filters.

For eg. Telephone expense done/paid/reimbused to Employee-X over the period
of time can be easily found out with the help of above sugested provision.


This was wide used practice in famous software like Quickbooks etc. (In
fact, in QB, they display all the contacts also for "Party Field" they have
given name to that fields as "payee".

[image: Inline image 1]


Thanking you,

With Regards,
Deven Shah
Safeworld Systems Pvt Ltd
M - 09825060116

**Comment by PawanMeh** [comment]
This is available in latest versions.

![3-party type employee](https://user-images.githubusercontent.com/20460498/47206181-98b71500-d3a5-11e8-8b84-3a6aee557af0.png)
