### ISSUE TITLE
Unable To Cancel Stock Recon - Stuck at 'Queued For Cancellation'

### ISSUE THREAD

**Issue by addymuliady** [frappe/erpnext#6672]
Hi

I did a Stock Recon and have decided to cancel it.

However, the status is now Queued For Cancellation. First time this happens to me.

![image](https://cloud.githubusercontent.com/assets/21187126/19589636/09912318-97a0-11e6-81ca-b1067a3cf2e6.png)

And when I try to cancel, this error comes out.

![image](https://cloud.githubusercontent.com/assets/21187126/19589690/49d1ce32-97a0-11e6-9bad-3ce2fe5ce173.png)

Thanks!

**Comment by nabinhait** [comment]
Check if scheduler is disabled for the site. If stock reconciliation has more than 100 items, then submission and cancellation event goes into background jobs (scheduler).

**Comment by addymuliady** [comment]
I have checked the log and received this error.

{'retry': 0, 'log': <function log at 0x7fb7ea85bed8>, 'site': u'cx3.erpnext.sg', 'event': None, 'method_name': u'frappe.model.document.execute_action', 'method': <function execute_action at 0x7fb7eb49a320>, 'user': u'Administrator', 'kwargs': {'action': u'_cancel', 'name': u'SR/000009', 'doctype': u'Stock Reconciliation'}, 'async': True, 'job_name': u'frappe.model.document.execute_action'}
Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 61, in execute_job
    method(**kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 1003, in execute_action
    _('Action Failed') + '<br><br>' + json.loads(frappe.local.message_log[-1]).get('message'))
IndexError: list index out of range

**Comment by addymuliady** [comment]
I have checked the error and received this msg.

{'retry': 0, 'log': <function log at 0x7fb7ea85bed8>, 'site': u'erp.dwenterprise.org', 'event': None, 'method_name': u'frappe.model.document.execute_action', 'method': <function execute_action at 0x7fb7eb49a320>, 'user': u'Administrator', 'kwargs': {'action': u'_cancel', 'name': u'SR/000009', 'doctype': u'Stock Reconciliation'}, 'async': True, 'job_name': u'frappe.model.document.execute_action'}
Traceback (most recent call last):
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 61, in execute_job
    method(**kwargs)
  File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 1003, in execute_action
    _('Action Failed') + '<br><br>' + json.loads(frappe.local.message_log[-1]).get('message'))
IndexError: list index out of range

**Comment by addymuliady** [comment]
Unchecking the scheduler didn't do anything

**Comment by addymuliady** [comment]
Hi @nabinhait

Is this a bug or settings issue? Please advice.

**Comment by nabinhait** [comment]
Seems like, this is outdated code.

1. Update to the latest version.
2. From mysql console, update docstatus of the Stock Reconciliation from 2 to 1
3. Then try to cancel the Stock Reconciliation again.
4. If it fails again, please check scheduler log and share the traceback.

**Comment by addymuliady** [comment]
Hi @nabinhait ,

Will do so over the weekend as we do updates on the weekends. Thank you very much for the advice! Will close this if it works.

**Comment by addymuliady** [comment]
Hi @nabinhait issue resolved. Very much thanks!
