### ISSUE TITLE
Process Salary : Salary Slips Are No Created

### ISSUE THREAD

**Issue by rohitk75** [frappe/erpnext#6681]
Salary Slips are are not created if Payment Account is Blank. The error message is "No employee for the above selected criteria OR salary slip already created"

If you fill up the Payment Account Number then it works. Either we should make the field mandatory or give a different
![salary slip creation](https://cloud.githubusercontent.com/assets/7210284/19618792/4fb3867c-9865-11e6-925f-606a7f6e264e.png)
 error message.

**Comment by KanchanChauhan** [comment]
Thanks for reporting the issue. It has been fixed via https://github.com/frappe/erpnext/pull/6682

Now Make Bank Entry button will not appear till you select Payment Account.
