### ISSUE TITLE
Bench installing erpnext on virtualenvwrapper fails

### ISSUE THREAD

**Issue by kkoci** [frappe/erpnext#6685]
Hi, I'm trying to install erpnext via frappe, on Linux Mint Rafaela (Ubuntu 14.04)

On a virtualenv created with virtualenvwrapper, it throws me this error:

> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-rCdCR8/frappe/
> Traceback (most recent call last):
>   File "/home/kristian/.virtualenvs/erpnext/bin/bench", line 9, in <module>
>     load_entry_point('bench', 'console_scripts', 'bench')()
>   File "/home/kristian/erpnext/bench-repo/bench/cli.py", line 40, in cli
>     bench_command()
>   File "/home/kristian/.virtualenvs/erpnext/local/lib/python2.7/site-packages/click/core.py", line 716, in **call**
>     return self.main(_args, *_kwargs)
>   File "/home/kristian/.virtualenvs/erpnext/local/lib/python2.7/site-packages/click/core.py", line 696, in main
>     rv = self.invoke(ctx)
>   File "/home/kristian/.virtualenvs/erpnext/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/home/kristian/.virtualenvs/erpnext/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
>     return ctx.invoke(self.callback, *_ctx.params)
>   File "/home/kristian/.virtualenvs/erpnext/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
>     return callback(_args, **kwargs)
>   File "/home/kristian/erpnext/bench-repo/bench/commands/make.py", line 30, in get_app
>     get_app(git_url, branch=branch)
>   File "/home/kristian/erpnext/bench-repo/bench/app.py", line 73, in get_app
>     install_app(app=app_name, bench_path=bench_path, verbose=verbose)
>   File "/home/kristian/erpnext/bench-repo/bench/app.py", line 103, in install_app
>     find_links=find_links))
>   File "/home/kristian/erpnext/bench-repo/bench/utils.py", line 127, in exec_cmd
>     raise CommandFailedError(cmd)
> bench.utils.CommandFailedError: ./env/bin/pip install -q  -e ./apps/erpnext

After this command:

> bench get-app erpnext https://github.com/frappe/erpnext

Any ideas on this?

Thanks in advance!

**Comment by shreyasp** [comment]
@kkoci Can you try executing this command for more detailed error while installing ERPNext `./env/bin/pip install -q -e ./apps/erpnext`.

PS: Run this command from `frappe-bench` directory

**Comment by kkoci** [comment]
Hi, I activate the virtualenv, then go to frappe-bench directory

Ran the command You told me, but:

`Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-j4k0nE/frappe/`

That is it :/

**Comment by kkoci** [comment]
Maybe I should install this system wide?

**Comment by jwrober** [comment]
Please open a discussion on this subject in the forum - https://discuss.erpnext.com/ - to get help with this
