### ISSUE TITLE
In POS, make the item grid scrollable

### ISSUE THREAD

**Issue by dufani1** [frappe/erpnext#6691]
hiiii
I suggest that the left side of POS should be frozen and dose not scroll down with items list as when I scroll down to select an item I could not see the if I selected the item or not.
Regards,
![image](https://cloud.githubusercontent.com/assets/23026263/19639376/8f6461e6-99d8-11e6-9f41-fa56ef4381cf.png)

**Comment by rmehta** [comment]
the problem is when the sidebar becomes scrollable too, double scrolling looks like a mess!

**Comment by dufani1** [comment]
But I think we should find a solution as the current design is not friendly to use.
And I am suffering when use POS, I have to select the item then scroll up to check if I selected or not in the invoice form (left side of POS).

**Comment by rmehta** [comment]
Maybe make the item section scrollable

**Comment by dufani1** [comment]
Yes it is very good idea Rushabh.

**Comment by netchampfaris** [comment]
#7290
