### ISSUE TITLE
Sales/Purchase Return

### ISSUE THREAD

**Issue by epochc** [frappe/erpnext#6693]
The Sales/Purchase return screen is very confusing right now. A simpler way is to pop the screen that asks the quantity that is being returned. User enters a number without the - sign and the system should calculate the various numbers: Amount, Tax amounts, etc.

A debit/credit note option from the submitted Return (Purchase Receipt or Delivery Note) will make it easy to raise an appropriate note.

**Comment by Suprazz** [comment]
One other thing I would like to say is that we need to be able to create partial purchase return more easily. I remember that I wanted to create a partial refund for shipping only and it was not very intuitive.

**Comment by rmehta** [comment]
There are many decisions to be made regarding the qty, rate, taxes etc, so best to make a reverse document.
