### ISSUE TITLE
BUG (v7.0): Currency mismatch caused by advance payments on purchase orders when invoice created.

### ISSUE THREAD

**Issue by kodybaker** [frappe/erpnext#6697]
ERPNext: v7.0.62
Frappe Framework: v7.0.46

Steps to reproduce:
1. Create purchase order (in foreign currency). 
![image](https://cloud.githubusercontent.com/assets/12718284/19657620/d3126aae-99d9-11e6-9050-615bf9e82f8b.png)
1. Make advance payment towards PO (in foreign currency).
   ![image](https://cloud.githubusercontent.com/assets/12718284/19657576/a701c194-99d9-11e6-9c9e-d03874ac2ec6.png)
2. Make invoice towards PO. Issue shown below.
   ![image](https://cloud.githubusercontent.com/assets/12718284/19657488/48c41e92-99d9-11e6-929a-569ef93b3254.png)

For some reason, it's not picking up the foreign currency for the payment (showing "undefined"). 

One cannot submit the invoice, due to the following error.
![image](https://cloud.githubusercontent.com/assets/12718284/19657695/1da87932-99da-11e6-9567-2b8582da7fef.png)

The reconciliation should be done against the foreign currency since the PO, payment, and invoice are all in the same foreign currency. Daily changes in exchange rates make this impractical to reconcile in company currency.

**Comment by rohitwaghchaure** [comment]
Fixed issue of currency label, system shows the supplier account currency in the advance amount. If account has not defined against the supplier then system use the Creditors ledger's currency
