### ISSUE TITLE
Enhancement Request: Print GL Accounts Tree

### ISSUE THREAD

**Issue by jwrober** [frappe/erpnext#6698]
From https://discuss.erpnext.com/t/enhancement-request-print-gl-accounts-tree/17021

I would like to suggest an enhancement to the main accounts tree-view (not list-view) to have a print icon added that then allows you to print the tree structure fully exploded (expanded) in regular letter head.

Thank You

**Comment by jwrober** [comment]
@nabinhait - may I ask why this was closed?

**Comment by nabinhait** [comment]
This has been implemented and merged into develop branch.
