### ISSUE TITLE
website footer uses bootstrap col-sm-3 inside a col-sm-6 div tag, which breaks footer

### ISSUE THREAD

**Issue by jwrober** [frappe/erpnext#6718]
From https://discuss.erpnext.com/t/website-footer-settings/17098

Per @rmehta, this needs to be fixed in the code somewhere.

**Comment by rmehta** [comment]
@jwrober, the best to way to fix it now is to add some custom CSS via **Website Theme**

**Comment by rmehta** [comment]
@jwrober, the best to way to fix it now is to add some custom CSS via **Website Theme**

**Comment by jwrober** [comment]
I am not that good with css, been poking at it a bit and can't see to figure it out.  If you have some code to share great, otherwise I'll hang and wait till patch is avail.

**Comment by pratu16x7** [comment]
Fixed via #2265
![screen shot 2016-11-05 at 4 27 07 pm](https://cloud.githubusercontent.com/assets/5196925/20030275/f782aa7c-a387-11e6-87f3-246451a1efb5.png)

**Comment by pratu16x7** [comment]
Fixed via frappe/frappe#2265

![screen shot 2016-11-05 at 4 27 07 pm](https://cloud.githubusercontent.com/assets/5196925/20030385/ccf696e0-a389-11e6-92ad-7fda18831192.png)
