### ISSUE TITLE
Currencies issue: Outstanding amount on an invoice shown in incorrect currency

### ISSUE THREAD

**Issue by kodybaker** [frappe/erpnext#6720]
ERPNext: v7.1.0
Frappe Framework: v7.1.0

Currently, if an invoice has been partially paid, it shows the Outstanding Amount in the company currency instead of the invoice currency. This makes it more difficult to process a final payment to close the invoice.

At the very least, the invoice should show both the invoice currency as well as the company currency.

Steps to recreate:
1. Create invoice in foreign currency.
2. Mark invoice as paid. Enter some non-fully-paid amount (in foreign currency, since that's what the invoice is demanding). 
3. When looking at submitted invoice, it will show the outstanding amount in company currency instead of the simple math of invoice total (foreign currency) - paid amount (foreign currency). 

Thanks!

**Comment by bcornwellmott** [comment]
Make sure the Credit To field is set to an account in the correct currency. You can set this by default for a supplier in Supplier >> Default Payable Account.
