### ISSUE TITLE
v7.1.0 New Chart of Account Currency Error

### ISSUE THREAD

**Issue by OneiricIT** [frappe/erpnext#6726]
When adding new Chart of Account (Accounts > Chart of Accounts) as soon as the 'currency' field is selected it produces below error relating to non-existent column. 

> Traceback (most recent call last):
> File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
> response = frappe.handler.handle()
> File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
> execute_cmd(cmd)
> File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 36, in execute_cmd
> ret = frappe.call(method, **frappe.form_dict)
> File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 890, in call
> return fn(*args, **newargs)
> File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/search.py", line 12, in search_link
> search_widget(doctype, txt, query, searchfield=searchfield, page_len=page_len, filters=filters)
> File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/search.py", line 91, in search_widget
> as_list=not as_dict)
> File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1069, in get_list
> return frappe.model.db_query.DatabaseQuery(doctype).execute(None, *args, **kwargs)
> File "/home/frappe/frappe-bench/apps/frappe/frappe/model/db_query.py", line 80, in execute
> result = self.build_and_run()
> File "/home/frappe/frappe-bench/apps/frappe/frappe/model/db_query.py", line 104, in build_and_run
> return frappe.db.sql(query, as_dict=not self.as_list, debug=self.debug, update=self.update)
> File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 148, in sql
> self._cursor.execute(query)
> File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
> self.errorhandler(self, exc, value)
> File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
> raise errorclass, errorvalue
> OperationalError: (1054, "Unknown column 'tabCurrency.company' in 'where clause'")

**Comment by KanchanChauhan** [comment]
Fixed via https://github.com/frappe/frappe/pull/2223
