### ISSUE TITLE
IMPROVEMENT OF PAYROLL IN 7.1

### ISSUE THREAD

**Issue by Fredoluka** [frappe/erpnext#6729]
I have reviewed the great work that is being done in ERP Version 7.1 particularly the improvement in payroll.
I want to request that in the payslip of each staff an option should be made for each salary component to have account to link it  to enable the management of Staff Loan and other deduction that may not be peculiar to all the staff.(the present method of loan management will not make the chart of account to be tidy if you have say 50 staff that have loan)
If the default account is generalised in Salary component and the option is not made available in each staff payslip,management of deductions in accounts would be made impossible.
Kindly consider it in 7.1 so that the payroll in ERP will meet minimum payroll requirement
EXAMPLE.
A company has  5 staff.Income tax is deducted for each of the 5 staff.So having default account in the salary component call Income tax will not be a problem(if the management does not care to know what is deducted from each staff in the account) because all the income tax deductions will be credited to the account specified in the Income tax salary component.
But if 3 out of the 5 took loan and you have only one default account in the Loan Deduction salary component,it means all the loan deducted from the 3 staff will be credited to this account.With this each staff loan balance cannot be determine {Note i have read how you want loan repayment should be treated.The method will make your chart of account look untidy where you have many staff who took loan}
But if there is option to define account (account receivable with option of selecting the party i.e staff) for each salary component in each staff payslip,you can specify the loan account of the staff and by the time salary is paid,the loan deduction from the staff will be credited to the loan account of the staff thereby reducing the loan balance
Here is the example in table form.
<img src="/uploads/default/original/2X/a/a93ebfaea32d234b831ac19fbee18b61326753fe.png" width="652" height="461">
For any payroll software to meet a basic payroll feature,the two stages of payroll must be captured.

FURTHER CLARIFICATION
See how loan will be managed or any other deduction that is to be tracked if at the level of each staff pay slip option of selecting account {account receivable ) is made possible:
1. I create another account receivable group in my chart of account and renamed it Staff Loan and Advances.So i can create each staff  as a party that has loan even if they are 500 staff (which will make my chart of account neater).
2.When loan is given,the staff is debited as a party through journal 
3.At point of deduction in his salary slip,the deduction is linked to this account receivable as a party.
4. When salary is paid,automatically the balance of loan is reduced by the deduction.
Each staff will be created as a party and in his pay slip you can select the created account receivable and select the staff as a party.
In the same vein if a staff has a contribution,his contribution can also be tracked by creating another Account Payable Group in the chart of account,re name it to Staff Contribution Scheme then only one account (just like Creditor) is created in the chart of account (let called it Staff Contribution Account)and then all the staff in the company regardless of their number (even if they are 1000) are created as Parties-This makes the ERPNEXT chart of accounts look professional rather than creating individual staff account in the chart of accounts which can be very clumsy when tracking loan or contribution of many staff
In the payroll ,a deduction salary component of the contribution of each staff is linked to the account (a created account payable different from the default Creditor account)  and the party i.e the staff is selected.
When salary is processed,the staff (as a party) is automatically credited.With this at any time you know what the staff has contributed rather than lumping all the staff contribution together in one account if the default account is domiciled in the Salary Component as it currently proposed in 7.1 beta
So let our amiable team add this feature.
Once again i appreciate effort made so far
Fred

**Comment by rmehta** [comment]
See linked issue
