### ISSUE TITLE
Right alignment tool in Heading (HTML) Editor

### ISSUE THREAD

**Issue by Devens** [frappe/erpnext#6730]
Currently there is no right alignment tool in Editor. 

We tried formating outside for right aligmentmet and pasted it back, which generated Error. We suggest that there should be right alignment button, especially when basic heading design has right aligmement of texts. 

![untitled_clipping_102716_082656_pm](https://cloud.githubusercontent.com/assets/10671911/19772358/8b06fa70-9c83-11e6-8f22-86c22a24d31e.jpg)

@nabinhait - For reference on request.

**Comment by pratu16x7** [comment]
Fixed via frappe/frappe#2279
