### ISSUE TITLE
[Feature Request] Purchase Orders and Delivery Notes included in Portal

### ISSUE THREAD

**Issue by bcornwellmott** [frappe/erpnext#6732]
Currently, the supplier portal is capable of showing suppliers the Request for Quotations and Supplier Quotation documents they are tied to. It would be great to include POs and Delivery Notes as well, so the supplier can see what they were awarded and what has been received.

**Comment by jaichavan** [comment]
Hello, as a workaround for now you can refer to status of Sales Order to know about delivery/billing status. We shall review and improvise if needed. Thanks for reaching out. @bcornwellmott
