### ISSUE TITLE
[enhancement] Field to show what BOMs an item is in for Related Documents

### ISSUE THREAD

**Issue by bcornwellmott** [frappe/erpnext#6733]
Currently there is a field in the related documents for BOM, which corresponds to a list of BOMs for which this item is the master item (parent). It would be great to have another field for BOMs for which this is a child (BOM Item).

![image](https://cloud.githubusercontent.com/assets/16806041/19778454/abfc0880-9c31-11e6-8835-db639a1264ab.png)

**Comment by Devens** [comment]
Very Useful. +1

**Comment by kodybaker** [comment]
+1
