### ISSUE TITLE
[v7.1] There are two profit and loss statements modules

### ISSUE THREAD

**Issue by jwrober** [frappe/erpnext#6736]
From - https://discuss.erpnext.com/t/two-profit-and-loss-statement-modules/17188

One of them is misspelled, not sure of implications.

**Comment by KanchanChauhan** [comment]
@jwrober Can you point us where, I could not find it. Also reload the page and see if it is still there.

**Comment by hiousi** [comment]
same here. I can also see them in the "Show or Hide Desktop Icons" their name:

- Profit and Loss Statement
- Profit and Loss Statment

**Comment by jwrober** [comment]
Look at the forum link. @KanchanChauhan gave me the solution yesterday.
