### ISSUE TITLE
Export file to TXT

### ISSUE THREAD

**Issue by ASneha1** [frappe/erpnext#6737]
Hi ERPNext Team, 

We were looking into exporting data as TXT file (as an application's input would allow for TXT uploads). 

For us to make the call to export TXT file, we would like to contribute the following to the standard response.py in frappe : 

``` python
def build_response(response_type=None):
    if "docs" in frappe.local.response and not frappe.local.response.docs:
        del frappe.local.response["docs"]

    response_type_map = {
        'csv': as_csv,
        'download': as_raw,
        'json': as_json,
        'page': as_page,
        'redirect': redirect,
        'txt' : as_txt
    }

    return response_type_map[frappe.response.get('type') or response_type]()
```

``` python
def as_txt():
    response = Response()
    response.mimetype = 'text/csv'
    response.charset = 'utf-8'
    response.headers[b"Content-Disposition"] = ("attachment; filename=\"%s.txt\"" % frappe.response['doctype'].replace(' ', '_')).encode("utf-8")
    response.data = frappe.response['result']
    return response
```

Thank you.

**Comment by strixaluco** [comment]
@ASneha1, is this kind of export different from current one to CSV?

**Comment by ASneha1** [comment]
@strixaluco, sorry, am not sure I understand your question. 
The code aims to achieve an export as TXT, similar to how currently we are able to export CSV.

**Comment by strixaluco** [comment]
I apologize for being not clear. Was just curious about use case. Why export to CSV doesn't work for you?

On Mon, 31 Oct 2016 01:18:07 -0700
ASneha1 <notifications@github.com> wrote:

> @strixaluco, sorry, am not sure I understand your question. 
> The code aims to achieve an export as TXT, similar to how currently we are able to export CSV.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/frappe/erpnext/issues/6737#issuecomment-257236212


-- 
strixaluco <strixaluco@rocketmail.com>

**Comment by ASneha1** [comment]
This is because the govt website that they upload the Export to only allows for txt upload.

**Comment by strixaluco** [comment]
Oh, I see then. Thanks for explanation.

On Thu, 03 Nov 2016 02:54:34 -0700
ASneha1 <notifications@github.com> wrote:

> This is because the govt website that they upload the Export to only allows for txt upload.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/frappe/erpnext/issues/6737#issuecomment-258100800


-- 
strixaluco <strixaluco@rocketmail.com>

**Comment by rmehta** [comment]
@ASneha1 sure, please send a pull request!
