### ISSUE TITLE
Not possible to find required Time Zone

### ISSUE THREAD

**Issue by President** [frappe/erpnext#6743]
I am setting up new site and selecting time zone. All time zones are unsorted neither by name nor by time zone. So it is almost impossible to find the right zone - e.g. look at screenshot and try to find Moscow time zone
![image](https://cloud.githubusercontent.com/assets/275339/19802172/13879a80-9d0b-11e6-9a65-b58a2cb5b28b.png)

**Comment by KanchanChauhan** [comment]
Timezone is sorted on zone name not on time name. You can see first all the zones under Asia are sorted and so on. You can find Moscow as Europe/Moscow.
