### ISSUE TITLE
can't compare datetime.date to str

### ISSUE THREAD

**Issue by khenchring** [frappe/erpnext#6746]
Do anyone get error when exporting Purchase Receipt file into ERP?

Mine got this error message

Import Log
Import Failed
Error for row (#21) "PREC-01884" : can't compare datetime.date to str
Please correct the format of the file and import again.

Current ERP Version 7.1.0

**Comment by joezsweet** [comment]
Did u double check the date format?

**Comment by khenchring** [comment]
yes.. do the date format but still giving the problem

**Comment by rmehta** [comment]
Can you share the file?

**Comment by KanchanChauhan** [comment]
Was able to replicate it earlier but now it looks like it is fixed. @khenchring Can you update and try again.
