### ISSUE TITLE
Fiscal year end date cannot be set for USA

### ISSUE THREAD

**Issue by President** [frappe/erpnext#6747]
Trying to workaround the defect:
https://github.com/frappe/erpnext/issues/6744

I get back to initial page and selected another country - USA. But not I cannot select the end date for fiscal year - I am selecting 31 december 2016 and then I get error - attached screenshot.
![image](https://cloud.githubusercontent.com/assets/275339/19802891/968afd3e-9d0e-11e6-8696-4e595f8b7f78.png)

**Comment by President** [comment]
PS. when I entered it manually 12-31-2016 it worked ok. So - not working only when I use calendar popup. And moreover after I close this error message the page changed to the latest page of the wizard.

**Comment by netchampfaris** [comment]
Are you on master or develop?
Also mention the frappe and erpnext versions.

**Comment by netchampfaris** [comment]
@President Can you provide the steps to replicate. I can't seem to encounter this issue.

**Comment by netchampfaris** [comment]
Closing for now
