### ISSUE TITLE
Conditional Workflow Transition Rules

### ISSUE THREAD

**Issue by PawanMeh** [frappe/erpnext#6749]
- [ ] Add eval based condition (similar to salary structure), eg: doctype.amount > 100 
- [ ] Only if conditions evaluate to true the workflow should transition to next state, if false it should skip the current state and move to the next state to evaluate conditions

**Comment by hwinkel** [comment]
What about making such workflows spanning multiple doctypes as described partly in

https://discuss.erpnext.com/t/automated-workflow-execution/17527

**Comment by Devens** [comment]
Similarly, for same doc type (Let's say PO), one can have different workflow for different company (or Cost Centers). 

If this task is undertaken, we suggest to check above mentioned point also.

**Comment by jk2081** [comment]
+1

**Comment by PawanMeh** [comment]
Closing this at it is being tracked as part of another issue
