### ISSUE TITLE
[enhancement] View attachments for Portal documents

### ISSUE THREAD

**Issue by bcornwellmott** [frappe/erpnext#6755]
It would be great if suppliers and customers logged into the portal could access the files that are attached to their documents, and attach documents of their own. For example, when I send a Request for Quotation to my supplier, I attach a bunch of documents the the Request for Quotation doctype which get sent with the RFQ email. When the supplier signs onto the portal to enter their quote, those documents aren't available for them.

I'd imagine a setting in Portal Settings that turns this ON/OFF for each portal type:
![image](https://cloud.githubusercontent.com/assets/16806041/19824351/75651436-9d23-11e6-9221-d3f4ad441a55.png)

If checked, it would add a section to the website where the attachments would show up as a list:
![image](https://cloud.githubusercontent.com/assets/16806041/19824420/125353b6-9d24-11e6-9da4-517407d29187.png)

**Comment by rmehta** [comment]
Add a property in "Web Form" to view attachments. If checked, add links for downloading attachments.

**Comment by chdecultot** [comment]
Hi guys,

I have just submitted two PRs in Frappe and ERPNext that can answer partially to this request (ERPNext #8830/ Frappe 3289).

@bcornwellmott, I used your idea of a checkbox in portal menu items that allows displaying public attachments on the portal orders/invoices display.

I think a great next step could be to be automatically generate a PDF version of a document that customers can download directly (For example the invoice PDF). It could be great for subscriptions in addition to automatic emails.

If you have any suggestion please let me know.

**Comment by jodeq** [comment]
I have done it in this frappe PR : https://github.com/frappe/frappe/pull/6089
Could it be reviewed ?

**Comment by jaichavan** [comment]
This PR ": frappe/frappe#6089" which caters the request, has been merged, hence closing the issue. @bcornwellmott
