### ISSUE TITLE
new feature Pagination, where to apply it?

### ISSUE THREAD

**Issue by hoeichia** [frappe/erpnext#6756]
I am very happy with the new features, but where can i apply it?
i cant see any in the Customize Form part, thanks
1. Pagination
   ![image](https://cloud.githubusercontent.com/assets/22652544/19828612/c15c7b9c-9dfd-11e6-9d63-05dcd7cb61ff.png)

To help your users fill out long new forms, you can insert page breaks that will appear on new sections. This way the user can focus on only filling one section at a time.

**Comment by revant** [comment]
Please ask questions on the forum https://discuss.erpnext.com/
