### ISSUE TITLE
[schools] UI Schools > Program > Edit Program Department dropdown menu overlaps grid element.

### ISSUE THREAD

**Issue by yashodhank** [frappe/erpnext#6757]
![image](https://cloud.githubusercontent.com/assets/1083792/19829527/be61fddc-9e01-11e6-9b6e-091946adcc92.png)

Installed Apps
ERPNext: v7.1.1
Frappe Framework: v7.1.2
Chrome: Version 54.0.2840.71 (64-bit)
Mac: macOS Sierra V:10.12.1 (16B2555)

**Comment by netchampfaris** [comment]
Sent a pr frappe/frappe#2231
