### ISSUE TITLE
[Paid Feature] - Enlarge/Open item image on website

### ISSUE THREAD

**Issue by Scheercuzy** [frappe/erpnext#6758]
Our organization has high definition images for our items which are not fully utilize when displayed on the website.

We kindly request that the image on the website becomes clickable and is linked to the image file to be able to see the image in full resolution.

**Comment by Scheercuzy** [comment]
This feature is very important to us as we wish to show very detailed photos to our customers using our ERPNEXT website. 

We are willing to pay for this development as it is essential for us. 

Thank you

**Comment by strixaluco** [comment]
This issue is related rather to [Frappe framework](https://github.com/frappe/frappe), than ERPNext.
Have you posted request to [Jobs](https://community.erpnext.com/jobs) section? If you are happy with functionality available within `Image view` in `Item` list, then I expect it should be pretty easy to implement the same on the website part.

**Comment by Scheercuzy** [comment]
Thank you very much for your help, I wasn't aware of the Jobs section before, I came here after reading the article of paid feature on the Erpnext website.

I will post my request on the jobs section 

Thank you

**Comment by strixaluco** [comment]
Not at all. See the corresponding PR for the reference: [#1767](https://github.com/frappe/frappe/pull/1767)
Consider contributing back to core.

**Comment by rmehta** [comment]
@Scheercuzy do you still need this feature?

**Comment by Scheercuzy** [comment]
@rmehta Yes, we still do. I have been busy working on the computer that will be taking high definition images so I wasn't able to continue with this feature for the website.
