### ISSUE TITLE
Stock Ageing Report - Suggestion to improve

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#6764]
Hi Team,

Recently I was doing Stock ageing analysis for my Warehouse. My ERPNEXT v 7.0.58
When I open Stock Ageing Report, I got some report that my Inventory age is 450 days in the report.

When i checked on the stock balance in erpnext. it shows that the item has been sold out long time ago,
and now are showing 0 balance.

I think for stock ageing should be calculated by:

present day (today) - date of stock receival (date of PREC) = stock days in warehouse

or if the stock has 0 balance means:

last day of stock sold - date of stock receival

or if stock balance 0 another option is:

should it be an option to hide all the stock with 0 balance so that it wont appear in the stock ageing report.

Thanks and best regards
Anton

https://discuss.erpnext.com/t/stock-ageing-report-shows-item-with-zero-quantity/17175

**Comment by KanchanChauhan** [comment]
I could not replicate it. The default behavior is that if stock balance is 0, it does not shows up in Stock Aging Report.

**Comment by ai-erp** [comment]
I have the same issue with our stock ageing..
Zero quantity showing ageing even if it was sold long time ago... 
Currently, we are on ERPNext: v7.2.6
Thanks..

**Comment by ai-erp** [comment]
Hi There,

Any update if this issue has been fixed?
The same issue is still there with our current version below:
ERPNext: v7.2.19
Frappe Framework: v7.2.15

Thanks..
