### ISSUE TITLE
Displaying number of selected entries

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#6773]
We use filtering for quick statistics such as "how many employees do we have in our company at the moment" this is why I am proposing to have a text field in the top right corner  that displays the number that is currently selected. So this is some Javascript.

Please see the screenshot and pay attention to "45 entries selected" right next to Menu / Refresh / Delete.

![no of entries selected](https://cloud.githubusercontent.com/assets/9136094/19856608/7d7b5064-9f7a-11e6-93ad-bf53b6539d65.png)

**Comment by pratu16x7** [comment]
Fixed via frappe/frappe#2286
