### ISSUE TITLE
Guidelines for ERPnext "new" Modules / update current Module and more 

### ISSUE THREAD

**Issue by kickapoo** [frappe/erpnext#6792]
Hello ppl, 

I am starting with issue in order to share it with the community and all Erpnext discussion options. 

Basically, there is a urgent need of proper guidelines contributing. 

- How a new feature should be proposed? 
- How a new addition to current functionality be proposed ?
- What are the Unit Test that every pull request must have ?
- How the pull request is documented ?
- and more ..  

So, setup up your keyboard cause writing mode should be on!!! 

Let start by updating: https://github.com/frappe/erpnext/blob/develop/.github/CONTRIBUTING.md

any document Team ? volunteers ?

**Comment by rmehta** [comment]
I think this is updated now!
