### ISSUE TITLE
[schools] > Fees > New Fees 1 (field dropdown overlap)

### ISSUE THREAD

**Issue by yashodhank** [frappe/erpnext#6797]
Installed Apps
ERPNext: v7.1.5
Frappe Framework: v7.1.4

Browser: Chrome Version 54.0.2840.71 (64-bit)

![image](https://cloud.githubusercontent.com/assets/1083792/19901106/e9d1f648-a08b-11e6-9765-aa37805d41a7.png)

Following fields are overlapping with its following fields.
- Student
- Academic Year
- Academic Term
- Program
- Program Enrollment

**Comment by jwrober** [comment]
I can confirm I have same behavior on Chrome 54.0.2840.87 m 32-bit, MS Internet Explorer 11.321.14393.0 32-bit and MS Edge 38.14393.0.0 on my install (not hosted)

**Comment by netchampfaris** [comment]
Fixed with frappe/frappe#2248
