### ISSUE TITLE
ERPNext > Selling > Customer (New Customer) form fields overlap

### ISSUE THREAD

**Issue by yashodhank** [frappe/erpnext#6798]
Installed Apps
ERPNext: v7.1.5
Frappe Framework: v7.1.4

Browser: Chrome Version 54.0.2840.71 (64-bit)

![image](https://cloud.githubusercontent.com/assets/1083792/19913334/abbebf8a-a0c7-11e6-9d26-569e4178ca4b.png)

![image](https://cloud.githubusercontent.com/assets/1083792/19913361/d333207e-a0c7-11e6-8ca1-af756d8eda2b.png)

**Comment by netchampfaris** [comment]
I am on the same Chrome version. And not able to replicate.

![image](https://cloud.githubusercontent.com/assets/9355208/19918150/174e06da-a0ef-11e6-857e-83eeb238bafd.png)

**Comment by jwrober** [comment]
I can confirm I have same behavior on Chrome 54.0.2840.87 m 32-bit, MS Internet Explorer 11.321.14393.0 32-bit and MS Edge 38.14393.0.0 32-bit on my install (not hosted) from a Windows 10.0.14393 PC

**Comment by netchampfaris** [comment]
Fixed with frappe/frappe#2248
