### ISSUE TITLE
SERIOUS ISSUES ON IMPROVED SALARY PROCESS IN 7.1.5

### ISSUE THREAD

**Issue by Fredoluka** [frappe/erpnext#6802]
Want to thanks erpnext team for their tireless effort in improving the software.
The payroll processes In version 7.1.5 beta failed to address real life situations.Once decision to link the payroll to the account has been taken by the erpnext team,it is good that a minimum payroll accounting system should be put in place in 7.1
AREAS OF IMPROVEMENT BEFORE FINAL RELEASE
1.Mode of payment:The default account should not be limited to Cash and Bank account.In practise payroll preparation is not the same as salary payment.Sometime payroll is prepared while payment follows later.So an option for the CREDIT payment should be included meaning an ACCOUNT PAYABLE(Accrual) will be the default account in the payment account for such option instead of cash or bank account,But presently it is only cash or bank account type that is selectable in the PAYMENT ACCOUNT,
2.Salary slip based on time sheet in the salary structure environment is made applicable to all the employee attached to the salary structure.In real life,this will not work because the rate for each of the employee linked to the salary structure cannot be the same.Effort should be made to make the rate dependable to employee rather than generalising to all the employee in the salary structure.Simply each employee should have his own rate and should be made possible even for that employee rate to be variable for that particular staff because in real life ,a staff might work in two sites in a month and the rate paid to him differed in the two sites.
3.Tracking Loan and advances to staff including other deductions is not resolved.Organisation that has 50 staff that take loan cannot use your prescribed method of opening loan account for each of the staff.This will make our chart of accounts look very untidy
Thanks

**Comment by epochc** [comment]
For #3, please add Employee as a party and like in the AR & AP reports all transactions related to employees can be booked into a separate account (Salary, Loans Advances, Travel Expenses, Other Expenses, etc.)

Thanks

Jay

**Comment by rmehta** [comment]
#6808
