### ISSUE TITLE
Plan upgrade

### ISSUE THREAD

**Issue by samehmreda** [frappe/erpnext#6803]
Hi,

Can you please upgrade my current plan to be 5 users " i mean in the trail period " ?

Thanks,

Sameh,

**Comment by umairsy** [comment]
Hello,

Please post this request, with the URL of your ERPNext account on support@erpnext.com

**Comment by samehmreda** [comment]
Hi,

Can you please upgrade my current plan to be 5 users " i mean in the trail period " ?

Thanks,

Sameh,



________________________________
