### ISSUE TITLE
Calender widget does not appear in pop-up 

### ISSUE THREAD

**Issue by djpalshikar** [frappe/erpnext#6804]
While editing row in a pop-up, if there is date field, the calender widget appears in the background while trying to enter data.
Erpnext version v7.1.5, Frappe Framework v71.1.4
Browser: Firefox 44.02 for Ubuntu
![screenshot from 2016-11-02 18 46 29](https://cloud.githubusercontent.com/assets/23133635/19930397/44ebfb94-a12e-11e6-9e93-6631da7bbd19.png)

**Comment by kodybaker** [comment]
I can confirm this is happening on my system too:
ERPNext: v7.1.5
Frappe Framework: v7.1.4
Chrome 54.0.2840.71 (64bit) on Windows 10

**Comment by kodybaker** [comment]
Also happening on android mobile app.

**Comment by rmehta** [comment]
This is fixed
