### ISSUE TITLE
Custom report not loading

### ISSUE THREAD

**Issue by Sivabalan-S** [frappe/erpnext#6806]
I tried building a custom report for the company salary register and when i tried opening it, it gets into the loading mode and never operates. Need resolve !!

Thanks in advance :+1:

**Comment by rmehta** [comment]
Please share some trace or steps to reproduce this.

**Comment by Sivabalan-S** [comment]
![image](https://cloud.githubusercontent.com/assets/23147153/19957829/189c5e52-a1c0-11e6-84b0-65fc5b62b98c.png)

![image](https://cloud.githubusercontent.com/assets/23147153/19957839/26ae086a-a1c0-11e6-9bbc-4587692f27fd.png)


I am facing the same issue as this one does !! Thanks :)

**Comment by rmehta** [comment]
Share the error log in your javascript trace. I cannot replicate this locally

**Comment by Sivabalan-S** [comment]
![error](https://cloud.githubusercontent.com/assets/23147153/19958104/5cb7412c-a1c2-11e6-96bb-729244566861.png)

**Comment by rmehta** [comment]
Did you change any custom fields after you made the report? Can you make a new report and check?
