### ISSUE TITLE
Language Translation for Printing Invoice or any other documents not working

### ISSUE THREAD

**Issue by PawanMeh** [frappe/erpnext#6814]
1. When you want to print a document in any language, you would selected the language code from the drop down and expect the data along with the elements to be translated. As you can see the data, like RAM etc is not translated.

![screen_shot1](https://cloud.githubusercontent.com/assets/20460498/19968510/de579b40-a1fa-11e6-98c7-0f42ff7aea0d.png)

2. When you try to add a new language code to add the translation for RAM manually, it does not allow you to do so. (Language Code Field is read only) 

![screen_shot2](https://cloud.githubusercontent.com/assets/20460498/19968550/0abb3f0c-a1fb-11e6-81dd-2628e4e0a365.png)

**Comment by rmehta** [comment]
Could not replicate. Seems fixed
