### ISSUE TITLE
Strange error bench update --upgrade 

### ISSUE THREAD

**Issue by nick9822** [frappe/erpnext#6816]
Hi Team,
While updating erpnext to version 7 we got an error 
`File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 306, in check_link_table_options
frappe.throw(_("Options must be a valid DocType for field {0} in row {1}").format(d.label, d.idx))
File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 300, in throw
msgprint(msg, raise_exception=exc, title=title, indicator='red')
File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 293, in msgprint
raiseexception()
File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 266, in raiseexception
raise raise_exception, encode(msg)
frappe.exceptions.ValidationError: Options must be a valid DocType for field Source in row 82`

Its on centos-release-7-2.1511.el7.centos.2.10.x86_64
You can see full trace at http://pastebin.com/vUdy68aX

Thanks,
Nick

**Comment by nabinhait** [comment]
- fixed via https://github.com/frappe/erpnext/pull/6817
- pending to release

**Comment by nick9822** [comment]
Thanks. :+1:

**Comment by nick9822** [comment]
Hi Team,
@nabinhait
After #6817 hotfix when we try bench update --upgrade we got following error
_mysql_exceptions.OperationalError: (1054, "Unknown column 'doctype' in 'where clause'")
See full trace at http://pastebin.com/U8fUm1Mi

And we again execute bench update --upgrade and above error went away but new following appeared which is persistent.
ImportError: No module named desktop_icon.desktop_icon
See full trace at http://pastebin.com/1X9A8RRg

Thanks,
Nick
