### ISSUE TITLE
Sales Order rate float precision differs from Sales Invoice’s 

### ISSUE THREAD

**Issue by nununo** [frappe/erpnext#6820]
I have already reported this here:
https://discuss.erpnext.com/t/sales-order-rate-float-precision-differs-from-sales-invoices/17346

My Sales Order rate float precision is 4 decimal places. I submitted the SO and generated the Sales Invoice. But when I tried to submit the Sales Invoice I got an error saying I was overrating (or something similar).

I finally understood that the Sales Invoice rate float precision is only 2 decimal places (thus different from the SO's equivalent field) and that's what's causing the error.

I finally solved it by removing 0.01 from the rate but this is not correct and should not be needed.

I searched the forum and found this old post in which @rmehta says one can set the float precision in the System Settings:
https://discuss.erpnext.com/t/make-valuation-rate-beyond-2-decimal-points/6002

I found that it was already at 3 and changed it to 4. 
I also tried changing the precision on the Sales Invoice Item rate field to 4.
Both to no avail as all the currency fields (EUR) are still only showing 2 decimal points except for the Sales Order rate.

Please advise.

Regards,
Nuno

**Comment by rmehta** [comment]
Precision has to be set for each field (I think). There must be a global way to set it too.

**Comment by nununo** [comment]
I changed it both in the global setting and at that specific field. Nothing happened.

In the discussion user pawdan suggested this:

> Please check if developer_mode = 1 in site_config.json file before changing precision.

But I don't know if this is possible in the cloud version nor if this is relevant for my scenario.

Please advise.

Thanks,
Nuno

**Comment by nabinhait** [comment]
Fixed in latest version.
@rohitwaghchaure is working for a global settings.
