### ISSUE TITLE
Mandetory Field not shown after Custumize the Form

### ISSUE THREAD

**Issue by abdulrahim313** [frappe/erpnext#6827]
I Have customized the customer form with mandatory field. (added above lead) its not shown while edit the form @ existing customer form.

**Comment by rmehta** [comment]
Did you refresh the other screen?

@shachiTakalkar can you replicate this?

**Comment by shachiTakalkar** [comment]
@abdulrahim313  I tried to replicate it in my test account but could not reproduce it. It created a mandatory field for me in my existing customer's form as well. 
Can you please provide me with the steps you have followed and got the error?
