### ISSUE TITLE
Customer Creation in PoS Module

### ISSUE THREAD

**Issue by olamide2** [frappe/erpnext#6836]
Hello all, I see that in the PoS module, you create a new customer by simply typing in the customer name.

For most retail business, customer creation is done 100% at this point and requires at the barest minimum the following data about the customer

Name
Email address
Phone number 1
Phone number 2

Can we make this possible ? It is quite essential

Thank you

**Comment by Fredoluka** [comment]
At least Contact Address should be added to the above mention essentials of customer details.

**Comment by dzulhelmi** [comment]
Hmmm...this is highly requested feature - https://github.com/frappe/erpnext/issues/7278
