### ISSUE TITLE
Billing amount does not refresh when entering Time before Activity Type on timesheets

### ISSUE THREAD

**Issue by superlack** [frappe/erpnext#6838]
When entering timesheets, billing amount does not calculate if the From time is entered before the Activity.  When hours get calculated, this triggers the billing amount it seems, but without the activity and activity cost being entered, it doesn't.  

Shown here, is a timesheet that was done when entering time before activity in the editable grid, and submitted.

Could be a dangerous issue for project billing

![tserror](https://cloud.githubusercontent.com/assets/12856084/20042849/2e42be04-a436-11e6-9afd-9c280c948f61.png)

**Comment by rohitwaghchaure** [comment]
Hi @superlack 

It's working properly, have checked on v7.1.7.
For more details please check [Gif](https://www.dropbox.com/s/fmn7uurkhlm5d5b/timesheet.gif?dl=0)

Thanks, Rohit

**Comment by superlack** [comment]
Oh ok, I may have to retrace my steps and find out exactly how to reproduce it..  An employee had this issue also, but it has been intermittent for the both of us, and I don't think there any any scripts that should cause it to fail.  Will report back
