### ISSUE TITLE
Formatting of the dropdown at Expense Claim child table and other child table. 

### ISSUE THREAD

**Issue by ASneha1** [frappe/erpnext#6844]
On version ERPNext: v7.0.29, Frappe Framework: v7.0.23, the following misalignment is noticed in dropdown fields : 
![image](https://cloud.githubusercontent.com/assets/16811259/20048251/1cc6fb02-a4f6-11e6-8486-4cd34675e47b.png)

Kindly advice if this has already been fixed in the latest version or with a fix we could pull. 
Thank you.

**Comment by nabinhait** [comment]
This is related to latest updates of Chrome. We have released a fix in the latest version.

If you don't want to update to the latest v7.1.5, you can update to latest version of v7.0 (v.7.0.63), by switching to v7.0.x branch
