### ISSUE TITLE
Combining Quotation Requests & Purchase Order Requests for Multiple Items

### ISSUE THREAD

**Issue by sukritbharati** [frappe/erpnext#6848]
Currently when you run the production plan, material request is generated per item. Which is acceptable considering the system would not know which items to club together. But there should be an option to sort the items by item groups. 
Then to select a few components & send out combines quotation requests. Which can be compared after quotations are received. 
Delivery time commitments should be included in the quotation requests and quotation comparisons. 
Then combines POs for multiple components to the same supplier should be viable. 

Currently if I want to use the system & i am buying 50 components from a supplier I will have to send them 50 quotation request and 50 purchase orders which is absurd. 

I hope we can build this feature in quickly.

**Comment by bcornwellmott** [comment]
Supplier Quotations and Purchase Orders can group from multiple Material Requests, so you don't need to send separate ones to the same supplier. As well, the Purchase Orders can pull all material requests from a default supplier, so in one click you can have populate the Purchase order with many MRs.

Improving the "Get Items From" tool for RFQs and Purchase Orders to allow filters (based on Item Group or other fields) would be a great addition.

There are tools to compare the Supplier Quotations, so if you have any specific suggestions for how to improve them, please suggest.

**Comment by sukritbharati** [comment]
Could you please elaborate as to how the first part can be done. 

Also for the second part, the comparison of quotations needs to be done on: 
1. The rate
2. The quantity available 
3. The delivery time line
4. Other costs, overheads or taxes
So if there can be a clear comparison of these 3-4 points in a table for specific components or even specific BOMs it would make the job much more efficient.

**Comment by bcornwellmott** [comment]
To pull multiple material requests into the same Request for Quotation or Purchase Order, use the "Get Items From" (or "Add Items From") button at the top right of the doc. This will let you enter the Material Request number that you want to include.

If you want to pull all the items from a specific supplier into a PO, create a new PO and fill in the Supplier field. A button will appear ("Get Items from Open Material Requests"). If you click that button, any items in a material request whose default supplier matches the supplier for this PO will be added.

For the comparison of quotations, there is a report (in Supplier Quotations) called "Quoted Item Comparison" which compares the piece cost of an item at each quantity level quoted from every supplier quotation. It does not include delivery time or other costs.

The challenge with what you are proposing is a simple and clear way of including all that information to make a comparison. If a quotation includes multiple parts, how can you separate out the other costs, overheads and taxes for each specific item? Sometimes it might be based on relative costs (some taxes are like this), but often there are other factors at play (e.g. for shipping, weight or size could be the factor, import duties are at different rates for product classes). Can you propose a specific layout for a report that would allow you to examine all your criteria between two (or more) quotations?

**Comment by Tropicalrambler** [comment]
It would be fantastic to have the ability to fill a "request for quotation"  from a "purchase order", using the "get items from" menu.  Usually it happens with a material request, but if you already have a purchase order made and you want to convert to a Request for quotation, it would be a little extra!
