### ISSUE TITLE
Daily timesheet summary report - time not showing up?

### ISSUE THREAD

**Issue by fblauer** [frappe/erpnext#6856]
Version 7.0 - SAAS
I enter time, some of which is billed and some of which is draft
I can't get it to show up on the daily time sheet summary report 
Not sure which date the date range is referring to, but I make it an extretemly wide range and it is not showing up?

**Comment by yashodhank** [comment]
@fblauer Known issue, your ERPNext instance will be updated sooner with planned update to Version 7.1 in which this and all other issues are fixed.
Note: To know more about update and for SAAS support you may directly contact to ERPNext Support from your ERPNext.
