### ISSUE TITLE
Feature Suggestion : Customer/Supplier view should show Unallocated amounts received/paid

### ISSUE THREAD

**Issue by ai-erp** [frappe/erpnext#6859]
I have noticed that when viewing
customer/supplier module, we can only see the unpaid balance (not effecting the
unallocated amounts paid by the customer or unallocated payments made to
supplier). In actual scenario, there were cases wherein the user of ERPNext
were not able to get advance payments received/paid upon invoicing to
customers/billing to suppliers. In that case, Matching payments with Invoices
have to be done to allocate the amounts received/paid in advance. I suggest to
include this in this area since there are cases that customers are making
advance payments and we are also making advance payments to suppliers. For most
companies, not all users have the access to view GL to check how much has been received/paid
in advance since it is not showing in customer/supplier module.… In the same manner, PDC received/paid should be also seen customer/supplier module. In this case
we suggest to have this feature in viewing customer/supplier in ERPNext. Below
is a sample for your reference:

![untitled](https://cloud.githubusercontent.com/assets/16744099/20088732/8c1e4712-a59b-11e6-906c-9e3816b1cf96.png)

![cus-](https://cloud.githubusercontent.com/assets/16744099/20088737/934ce3ea-a59b-11e6-8f0b-3f1b1540d122.png)

**Comment by Devens** [comment]
+1

**Comment by harshit-30** [comment]
Can you showcase any other tools doing the same?
