### ISSUE TITLE
Feature: What did you work on today

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#6862]
The system will send an email to all or specified employees at 5pm on what did they work on today. At midnight it will take all responses and make a common email to everyone with the collection of replies.

### Design

- [x] DocType "Daily Work Summary Settings"
   - [x] Time to send email (?)
   - [x] List of employees to send to
   - [x] Incoming Email Account
   - [x] Message
- [x] DocType "Daily Work Summary" will be generated everyday an midnight
   - [x] Date
   - [x] Status
- [x] DocType "Daily Work Summary Response" (child table)
   - [x] Email ID, Employee, Response (text)

### Scheduler

- [x] Trigger events at a specific hour
  - [x] Don't send emails on holiday
- [x] Trigger summary email at midnight

### Inbound Email

- [x] Hook to handle responses against a particular transaction email

### Patch

- [x] Set default time to 17:00 in Daily Work Summary Settings

**Comment by Devens** [comment]
Wonderful Feature...

**Comment by vladucoju** [comment]
This is great!

**Comment by rmehta** [comment]
Pushed to develop!
