### ISSUE TITLE
GENERIC FEATURE: Make Sales Invoice from Delivery Note - multiple selection 

### ISSUE THREAD

**Issue by vladucoju** [frappe/erpnext#6866]
Hello everyone, 
i am new to ERPNEXT. I saw that there is no option to select and add all DN/SO from particular customer when creating a single Sales Invoice.. I think this option should be included in erp because it is quite dificult to add it one by one. There is a big chance to make a mistake. 
I would suggest something like this.

![make si](https://cloud.githubusercontent.com/assets/9590909/20093710/299ce370-a59e-11e6-99f1-5434f125bf7a.png)

Option for selecting all at ones will be great feature. Ideal view will be like in next picture

![untitled](https://cloud.githubusercontent.com/assets/9590909/20093719/2fbac81c-a59e-11e6-84ca-806a5c821ee0.png)

This is list view from Sales Invoice.

**Comment by Devens** [comment]
+1 (alternatively Checkbox for each DN would be better).

**Comment by vladucoju** [comment]
That would be perfect.

**Comment by rmehta** [comment]
Make this a generic feature

**Comment by vladucoju** [comment]
Ok @rmehta .Could you explain me how could i do that?

**Comment by vladucoju** [comment]
Hello @pratu16x7 . How is going with this? When we should expect this feature in Erpnext?

**Comment by vladucoju** [comment]
Hi @pratu16x7 . Can we expect this feature in v8?

**Comment by Devens** [comment]
+1

**Comment by vladucoju** [comment]
Any update?

**Comment by vladucoju** [comment]
Thank you @pratu16x7. You almost finish this. This is very usefull feature. Maybe one of the best thing  in V8.

**Comment by vladucoju** [comment]
Is this merged? i saw that the issue was closed.

**Comment by pratu16x7** [comment]
@vladucoju Sorry about the delay, this turned out to have more to it than just multiple selection ;)

**Comment by vladucoju** [comment]
Thank you @pratu16x7 . I was following your activity on this feature all the time. I will update vm this weekend and let you know.

**Comment by pratu16x7** [comment]
The multiselect dialog as of now satisfies the previously stated requirements of this issue. Please let us know of any issues that you find. Closing.
