### ISSUE TITLE
Salary not being created from Process Payroll for new employee

### ISSUE THREAD

**Issue by saurabhvashist** [frappe/erpnext#6870]
This is in addition to issue #6834 

The last employee joined on 05-Oct. Now when we create his salary slip from Process Payroll for October, the system shows there is no such employee. But it successfully creates salary for November, for the same employee.

It seems the system is unable to create Salary Slip for the employee who joins after start of month like in my case the employee joined on 5th. Probably the code needs attention for this peculiar situation.

Thanks!

**Comment by KanchanChauhan** [comment]
Fixed via https://github.com/frappe/erpnext/pull/6962
