### ISSUE TITLE
Drop down in Chart of Account not working properly

### ISSUE THREAD

**Issue by saurabhvashist** [frappe/erpnext#6871]
While creating new account head in chart of account, the account type drop down shows limited heads. When we create it, then we have to go to edit and from there we have to choose the right account head.

![1](https://cloud.githubusercontent.com/assets/22211942/20101811/8ccf2232-a5e9-11e6-8606-98a54b9f5443.png)

Need to look into the code for drop down while creation of new account head.

Thanks!

**Comment by saurabhvashist** [comment]
Close this issue as well @rmehta 

It is the easiest ways to get rid of the issues from your dream project 👎

**Comment by rmehta** [comment]
@saurabhvashist usually I don't like to engage in such conversations, but erpnext is free and open source. I have no obligation to do your work and you have no right to expect anything from developers. If you want to engage in the community, do so in a constructive way. 

It is easy to berate someone and spit on their dreams, but much harder to actually *do* something about it.

**Comment by saurabhvashist** [comment]
In place of motivating users who struggling with the bugs in your software, you close their issues without solving them. You tell them to go get PAID help and shut-up. And then you preach humility and how to be constructive?

Close this thread and let the users continue to struggle. This will be the right thing to do..
