### ISSUE TITLE
Sales Invoice not populating Tax data

### ISSUE THREAD

**Issue by saurabhvashist** [frappe/erpnext#6872]
While creating Sales Invoice, I am facing issue in populating Tax information. Although my Sales Invoice format contains all the Tags taken form the defaults but it is not getting populated in the Print Format. The specific tags which are getting skipped by system are:
- Sales Taxes & Charges (Table)
- Taxes & Charges Calculation

See screen-shots below:

![2](https://cloud.githubusercontent.com/assets/22211942/20102333/cc1f00cc-a5eb-11e6-998c-b2b4adc56cda.png)

![3](https://cloud.githubusercontent.com/assets/22211942/20102385/f3aa35c6-a5eb-11e6-93dc-3a304fb3ec50.png)

**Comment by saurabhvashist** [comment]
Additionally, the value "Item Tax Rate" in the "Items (Table)" is getting populated in brackets i.e. {....}. See screen-shot:

![1](https://cloud.githubusercontent.com/assets/22211942/20146590/896346dc-a6ca-11e6-807f-18b89fb7c3d2.png)

This value should only show Item Tax Rate in % and not as seen above! Need correction in code..

PS: If this table itself can show tax amount alongside tax rate, it would solve lot of trouble for many companies.

**Comment by saurabhvashist** [comment]
This is the most crucial part in any business - Create Sales Invoice.

While I'm not able to do it on my server, are there any other users who are facing the same issue?

There has been no response from ERPNext Team and this issue is pending first response.

Don't know if I should switch to other ERP solution or keep waiting till a response is received for such crucial fix.

**Comment by rmehta** [comment]
@saurabhvashist best you should engage a freelancer and make a custom HTML format to fix this issue.
