### ISSUE TITLE
Help subcategory showing videos repeatedly

### ISSUE THREAD

**Issue by hisyam** [frappe/erpnext#6874]
In every category where there is a Help subcategory, clicking on any the Help link item will show a popover with embedded youtube video inside. However the videos seem to be repeated over & over again.

![erpnext learn bug](https://cloud.githubusercontent.com/assets/1519780/20106374/e2e971e2-a60f-11e6-812a-76c859677a3b.png)

**Comment by rmehta** [comment]
This was fixed in latest.
