### ISSUE TITLE
Dropbox backup authentication broken - erpnext 7.1.8 frappe 7.1.7

### ISSUE THREAD

**Issue by DrTrills** [frappe/erpnext#6875]
Hi all,

I have with SSL the latest version of ERPNext running on a debian 8 server on Google Cloud. I am trying to authenticate Dropbox like I have in the past and am getting some errors. Upon further investigation in the console it seems this is happening when I click **Allow Dropbox to Access.** Not really sure where to go from here but figured this was worth reporting.

Thanks!

`
jquery.min.js:4 POST https://erpv7.website.com/ 502 (Bad Gateway)send @ jquery.min.js:4ajax @ jquery.min.js:4frappe.request.call @ desk.min.js:138frappe.call @ desk.min.js:134allow_dropbox_access @ VM1032:18(anonymous function) @ form.min.js:254(anonymous function) @ form.min.js:254map @ jquery.min.js:2trigger @ form.min.js:254onclick @ desk.min.js:444(anonymous function) @ desk.min.js:444dispatch @ jquery.min.js:3$event.dispatch @ report.min.js:203r.handle @ jquery.min.js:3
VM1056:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0(…)(anonymous function) @ desk.min.js:141i @ jquery.min.js:2fireWith @ jquery.min.js:2z @ jquery.min.js:4(anonymous function) @ jquery.min.js:4
`

**Comment by rmehta** [comment]
I setup dropbox recently for an account and worked alright.

**Comment by DrTrills** [comment]
Hi @rmehta 

Just wanted to update with more info on the errors i'm having regarding Dropbox backups.

I was able to connect Google for sign in so it's seems specific to dropbox and not an API error with other services. Please let me know if there is anything else I can do to provide help and get this taken care of.

These are my steps:

1. Add dropbox keys in site_config.json 
2. Settings > Integration Services > Dropbox
3. Here It no longer shows the fields for the API. In source, it has the hidden attribute. 
<img width="992" alt="screen shot 2017-01-05 at 4 50 39 pm" src="https://cloud.githubusercontent.com/assets/1430005/21698965/88f74cd8-d367-11e6-8691-acf4b9bf8520.png">
4. Click Allow Dropbox access > Allow access on dropbox page to folder, then get this error page after trying to authenticate
<img width="1324" alt="screen shot 2017-01-05 at 4 55 49 pm" src="https://cloud.githubusercontent.com/assets/1430005/21699048/ec18da2a-d367-11e6-95dd-1f808a7a87f7.png">

This is the error code on the page

```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 40, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 896, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/integrations/doctype/dropbox_settings/dropbox_settings.py", line 158, in dropbox_callback
    _("Dropbox access is approved!") + close,
UnboundLocalError: local variable 'close' referenced before assignment
```

This is the console log:

`https://erpv7.website.com/?cmd=frappe.integrations.doctype.dropbox…ropbox_settings.dropbox_callback&oauth_token=NvIMqyoLfWbcWBb0&uid=55033491 Failed to load resource: the server responded with a status of 500 (INTERNAL SERVER ERROR)`


Thank you!!!
