### ISSUE TITLE
[new feature] If this then that

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#6877]
Please add a feature to set the value of a field based on another field's value

Example Use Cases:

-Setting the naming series of a doc based on the value in the company field
-Automatically setting the appropriate series (i.e. SINV-RET-) based on the value of the 'Is return' field
-etc

Reference:
https://discuss.erpnext.com/t/set-value-of-a-field-based-on-other-fields-value/7762/1

Mockup:

![ifttt](https://user-images.githubusercontent.com/140076/32765542-f05900c8-c930-11e7-8037-1d378c2d42c4.png)

**Comment by mhbu50** [comment]
+1

**Comment by somicoito** [comment]
+1

**Comment by rmehta** [comment]
Is this only for naming series or any other usecase?

**Comment by somicoito** [comment]
In our case for normal fields, in example when we sell to customers outside the EU we need to add specific texts in invoices for customs. In the EU other texts and so on.
I think to be able to set a field value based on another would give us incredible opportunities to simplify user's daily work and reduce the possibility to make mistakes.

**Comment by Olawale1** [comment]
Hi @rmehta 

Great to hear from you. This is not only for naming series; I only used that as an example. It is required for other fields too as rightly pointed out by @somicoito
Having this would make a significant impact in terms of simplifying data entry and improving accuracy

Thanks

**Comment by MaxMorais** [comment]
I have this solution already coded, over Custom Scripts, like you can see there

https://www.youtube.com/watch?v=z1OP5uyRJVM

If do you need a patch for this, I can contribute!

**Comment by jk2081** [comment]
Can you add this to core and send a PR?

**Comment by cosimot** [comment]
This would be amazing!

**Comment by mhbu50** [comment]
@MaxMorais It will be great contribution

**Comment by Olawale1** [comment]
Hi @MaxMorais 

Trust you're doing great. Have you been able to make the contribution yet?

Kind regards,

**Comment by Olawale1** [comment]
Any update on this feature pls?

Kind regards,

**Comment by MaxMorais** [comment]
@Olawale1 it's kinda complex to be developed!

I had success to develop the UI, but when I try to make it work, I discovered that now I need to develop around other problems, to have a list of actions, and have an way to trigger that actions.

Because that, I'm working in a parellel project, called Studio, that allow me to develop my functions into the backend of Frappe, using JavaScript, trought the UI, and these functions can be called by this UI.

I'm showing a bit about that functionality here https://www.useloom.com/share/da23a0d1eaab4c27914ca77b405f2407

Due it's an party time project, it's moving really slow.

**Comment by Olawale1** [comment]
@MaxMorais 

Thanks a lot for the update. Studio looks like a really great project! Hope you get to finish it soon... 

Cheers!

**Comment by Olawale1** [comment]
Hi @nabinhait 

Any progress here?

Thanks

**Comment by MaxMorais** [comment]
@Olawale1, my plan is to finish it in September/2019 to get it ready for a presentation in the ERPNext Conference.

I'm already using this on production, and It's stable, but lacks, documentation and the most important thing is the Business Process Layer., that will come with the If then that widget.

**Comment by rmehta** [comment]
https://github.com/frappe/frappe/pull/8550
