### ISSUE TITLE
Shopping Cart

### ISSUE THREAD

**Issue by rohitwaghchaure** [frappe/erpnext#6890]
- [ ] Cleanup the old images on the [shopping cart](https://frappe.github.io/erpnext/user/manual/en/website/shopping-cart)

**Comment by kickapoo** [comment]
Please provide more explanation. 

Shopping cart, with Cleanup the old image TODO, doesn't mean anything. 
Any link? Any screenshoot?

**Comment by rohitwaghchaure** [comment]
@kickapoo 
Thanks for your comment, I have added the link.
You can also add the points which you think missing in the shopping cart documentation.

Thanks
