### ISSUE TITLE
Website Module

### ISSUE THREAD

**Issue by rohitwaghchaure** [frappe/erpnext#6891]
- [ ] Cleanup the old images in the topic [Add Products To Website](https://frappe.github.io/erpnext/user/manual/en/website/add-products-to-website)

- [ ] [Managing User Sign Up via Website](https://frappe.github.io/erpnext/user/manual/en/website/articles/managing-user-sign-up-via-website)(Broken Link)

- [ ] [Website Security](https://frappe.github.io/erpnext/user/manual/en/website/articles/website-security)(Broken Link)

- [x] Cleanup the old images in the topic [Website Home Page](https://frappe.github.io/erpnext/user/manual/en/website/articles/wesite-home-page)

**Comment by kickapoo** [comment]
Please provide related Broken links

**Comment by jwrober** [comment]
https://github.com/frappe/erpnext/pull/7128

**Comment by gmplab** [comment]
#7128 fixed it. 
so i close it.
