### ISSUE TITLE
GANTT Chart Freezes in IE 11

### ISSUE THREAD

**Issue by iadr3805** [frappe/erpnext#6894]
Project Gantt chart freezes in Internet Explorer 11 windows 10. Browse error log is below

SCRIPT5007: Unable to set property 'scrollLeft' of undefined or null reference
list.min.js (275,73)

https://discuss.erpnext.com/t/gantt-chart-freezes/17555/7

**Comment by netchampfaris** [comment]
Fixed with frappe/frappe#2328
