### ISSUE TITLE
Filter by blank fields

### ISSUE THREAD

**Issue by ishanloya** [frappe/erpnext#6902]
Employee register > filters don't seem to work on all fields if I want to see only fields where values are not entered (null). 

For e.g., if I filter Bank A/C No. = "", it shows me employees with no bank account numbers but the same does not work for Bank Name, Designation, etc.

**Comment by KanchanChauhan** [comment]
Try using `Like` instead of `Equals` in filter.

**Comment by ishanloya** [comment]
Thanks @KanchanChauhan
