### ISSUE TITLE
Not able to create salary slip

### ISSUE THREAD

**Issue by ayaas** [frappe/erpnext#6905]
Not able to create salary slip because not field available under "Month Field".

Similarly "Process Payroll" is also not working.
for https://ayaas.erpnext.com

**Comment by KanchanChauhan** [comment]
What version are you on and can you please share some screenshot.

**Comment by ayaas** [comment]
Version:
[image: Inline image 1]

If I go with "New Salary Slip" - I do not get the option to select the
month. Issue started this month I have generated the salary slip for last
month.

[image: Inline image 2]

If I go with "Process Payroll" below error occurs

Traceback (most recent call last):
  File "/home/frappe/benches/bench-2016-11-09-a/apps/frappe/frappe/app.py",
line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/benches/bench-2016-11-09-a/apps/frappe/frappe/handler.py",
line 19, in handle
    execute_cmd(cmd)
  File "/home/frappe/benches/bench-2016-11-09-a/apps/frappe/frappe/handler.py",
line 36, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/benches/bench-2016-11-09-a/apps/frappe/frappe/__init__.py",
line 890, in call
    return fn(*args, **newargs)
  File "/home/frappe/benches/bench-2016-11-09-a/apps/frappe/frappe/handler.py",
line 67, in runserverobj
    frappe.desk.form.run_method.runserverobj(method, docs=docs, dt=dt,
dn=dn, arg=arg, args=args)
  File "/home/frappe/benches/bench-2016-11-09-a/apps/frappe/frappe/desk/form/run_method.py",
line 35, in runserverobj
    r = doc.run_method(method)
  File "/home/frappe/benches/bench-2016-11-09-a/apps/frappe/frappe/model/document.py",
line 654, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/benches/bench-2016-11-09-a/apps/frappe/frappe/model/document.py",
line 882, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/benches/bench-2016-11-09-a/apps/frappe/frappe/model/document.py",
line 865, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/benches/bench-2016-11-09-a/apps/frappe/frappe/model/document.py",
line 648, in
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/benches/bench-2016-11-09-a/apps/erpnext/erpnext/hr/doctype/process_payroll/process_payroll.py",
line 100, in create_sal_slip
    ss.insert()
  File "/home/frappe/benches/bench-2016-11-09-a/apps/frappe/frappe/model/document.py",
line 203, in insert
    self.run_before_save_methods()
  File "/home/frappe/benches/bench-2016-11-09-a/apps/frappe/frappe/model/document.py",
line 753, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/benches/bench-2016-11-09-a/apps/frappe/frappe/model/document.py",
line 654, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/benches/bench-2016-11-09-a/apps/frappe/frappe/model/document.py",
line 882, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/benches/bench-2016-11-09-a/apps/frappe/frappe/model/document.py",
line 865, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/benches/bench-2016-11-09-a/apps/frappe/frappe/model/document.py",
line 648, in
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/benches/bench-2016-11-09-a/apps/erpnext/erpnext/hr/doctype/salary_slip/salary_slip.py",
line 24, in validate
    self.validate_dates()
  File "/home/frappe/benches/bench-2016-11-09-a/apps/erpnext/erpnext/hr/doctype/salary_slip/salary_slip.py",
line 47, in validate_dates
    if date_diff(self.end_date, self.start_date) < 0:
  File "/home/frappe/benches/bench-2016-11-09-a/apps/frappe/frappe/utils/data.py",
line 104, in date_diff
    return (getdate(string_ed_date) - getdate(string_st_date)).days
  File "/home/frappe/benches/bench-2016-11-09-a/apps/frappe/frappe/utils/data.py",
line 39, in getdate
    return parser.parse(string_date).date()
  File "/home/frappe/benches/bench-2016-11-09-a/env/lib/python2.7/site-packages/dateutil/parser.py",
line 1168, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/frappe/benches/bench-2016-11-09-a/env/lib/python2.7/site-packages/dateutil/parser.py",
line 581, in parse
    ret = default.replace(**repl)
ValueError: day is out of range for month

Report this issue

**Comment by KanchanChauhan** [comment]
There are no images attached.

**Comment by ayaas** [comment]
Version
![version](https://cloud.githubusercontent.com/assets/23402103/20236888/f35a31b0-a8e9-11e6-9ba4-f8213fab69c7.png)

If I go with "New Salary Slip" - I do not get the option to select the month. Issue started this month I have generated the salary slip for last month.
![salaryslip](https://cloud.githubusercontent.com/assets/23402103/20236909/64fe428e-a8ea-11e6-951e-73b4b6fd9563.png)


If I go with "Process Payroll" below error occurs Traceback (most recent call last): File "/home/frappe/benches/bench-2016-11-09-a/apps/frappe/frappe/app.py", line 55, in application response = frappe.handler.handle() File "/home/frappe/benches/bench-2016-11-09-a/apps/frappe/frappe/handler.py", line 19, in handle execute_cmd(cmd) File "/home/frappe/benches/bench-2016-11-09-a/apps/frappe/frappe/handler.py", line 36, in execute_cmd ret = frappe.call(method, **frappe.form_dict) File "/home/frappe/benches/bench-2016-11-09-a/apps/frappe/frappe/__init__.py", line 890, in call return fn(*args, **newargs) File "/home/frappe/benches/bench-2016-11-09-a/apps/frappe/frappe/handler.py", line 67, in runserverobj frappe.desk.form.run_method.runserverobj(method, docs=docs, dt=dt, dn=dn, arg=arg, args=args) File "/home/frappe/benches/bench-2016-11-09-a/apps/frappe/frappe/desk/form/run_method.py", line 35, in runserverobj r = doc.run_method(method) File "/home/frappe/benches/bench-2016-11-09-a/apps/frappe/frappe/model/document.py", line 654, in run_method out = Document.hook(fn)(self, *args, **kwargs) File "/home/frappe/benches/bench-2016-11-09-a/apps/frappe/frappe/model/document.py", line 882, in composer return composed(self, method, *args, **kwargs) File "/home/frappe/benches/bench-2016-11-09-a/apps/frappe/frappe/model/document.py", line 865, in runner add_to_return_value(self, fn(self, *args, **kwargs)) File "/home/frappe/benches/bench-2016-11-09-a/apps/frappe/frappe/model/document.py", line 648, in fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs) File "/home/frappe/benches/bench-2016-11-09-a/apps/erpnext/erpnext/hr/doctype/process_payroll/process_payroll.py", line 100, in create_sal_slip ss.insert() File "/home/frappe/benches/bench-2016-11-09-a/apps/frappe/frappe/model/document.py", line 203, in insert self.run_before_save_methods() File "/home/frappe/benches/bench-2016-11-09-a/apps/frappe/frappe/model/document.py", line 753, in run_before_save_methods self.run_method("validate") File "/home/frappe/benches/bench-2016-11-09-a/apps/frappe/frappe/model/document.py", line 654, in run_method out = Document.hook(fn)(self, *args, **kwargs) File "/home/frappe/benches/bench-2016-11-09-a/apps/frappe/frappe/model/document.py", line 882, in composer return composed(self, method, *args, **kwargs) File "/home/frappe/benches/bench-2016-11-09-a/apps/frappe/frappe/model/document.py", line 865, in runner add_to_return_value(self, fn(self, *args, **kwargs)) File "/home/frappe/benches/bench-2016-11-09-a/apps/frappe/frappe/model/document.py", line 648, in fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs) File "/home/frappe/benches/bench-2016-11-09-a/apps/erpnext/erpnext/hr/doctype/salary_slip/salary_slip.py", line 24, in validate self.validate_dates() File "/home/frappe/benches/bench-2016-11-09-a/apps/erpnext/erpnext/hr/doctype/salary_slip/salary_slip.py", line 47, in validate_dates if date_diff(self.end_date, self.start_date) < 0: File "/home/frappe/benches/bench-2016-11-09-a/apps/frappe/frappe/utils/data.py", line 104, in date_diff return (getdate(string_ed_date) - getdate(string_st_date)).days File "/home/frappe/benches/bench-2016-11-09-a/apps/frappe/frappe/utils/data.py", line 39, in getdate return parser.parse(string_date).date() File "/home/frappe/benches/bench-2016-11-09-a/env/lib/python2.7/site-packages/dateutil/parser.py", line 1168, in parse return DEFAULTPARSER.parse(timestr, **kwargs) File "/home/frappe/benches/bench-2016-11-09-a/env/lib/python2.7/site-packages/dateutil/parser.py", line 581, in parse ret = default.replace(**repl) ValueError: day is out of range for month

**Comment by KanchanChauhan** [comment]
Cannot replicate it. Try replicating it on [https://beta.erpnext.com/](https://beta.erpnext.com/) and also check if you have any customizations to Salary Slip doctype.

**Comment by ayaas** [comment]
Disabled all salary slip customization along with Letterhead customization, still same issue. 
Not able to replicate into beta version also.

**Comment by ayaas** [comment]
is there any possibility to downgrade to old version or recovering the old data from backup and start new system ?

**Comment by rmehta** [comment]
Is this issue still valid? Can you share the exact data to help us replicate?

**Comment by ayaas** [comment]
Hi,

Not able to access my space. Shows below error.

ayaastech.erpnext.com does not exist



On 30-Dec-2016 3:15 pm, "Rushabh Mehta" <notifications@github.com> wrote:

Closed #6905 <https://github.com/frappe/erpnext/issues/6905>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/frappe/erpnext/issues/6905#event-907966040>, or mute
the thread
