### ISSUE TITLE
Credit Limit Exception

### ISSUE THREAD

**Issue by alimalkhalifa** [frappe/erpnext#6906]
# Credit Limit Exception

### Sale Order

When a sales order is to be submitted for a customer whose credit exceeds limits, the system should allow escalation to a user who has permission to approve transactions over limit.

**Comment by nabinhait** [comment]
The feature is already there, you can set "Credit Controller" role in Accounts Settings page. User with that role has access to submit orders even though credit limit has been crossed.
https://frappe.github.io/erpnext/user/manual/en/accounts/credit-limit
