### ISSUE TITLE
Kitchen and Restaurant Module

### ISSUE THREAD

**Issue by alimalkhalifa** [frappe/erpnext#6907]
# Kitchen and Restaurant Module

### Recipes

Allows creation of recipes.

### Item

Can be defined as kitchen item.
Kitchen items may have a recipe

### Stock Behavior

Kitchen items need not be stocked (although can be).  They are considered items that are made Just-In-Time.

### POS

Selling a kitchen item does not require you to have stock.  If no stock is available, it gets pushed as a kitchen order.

Should allow having open tickets.  These will be defined by table (i.e Table 1, 2, 3).  Bonus points for having this as a configurable GUI of tables.

### Kitchen Order

Queue of orders based on kitchen items/recipes.  Those orders must be reconciled using a tool end of period (daily/weekly/monthly/on-demand based on business requirement).

Can be inserted via POS or manually entered.

### Recipe

Definition of a recipe

### Kitchen Reconciliation Tool

End of period (as per business requirement), usage of raw materials is entered for all kitchen orders made during this time.  System should convert those raw materials to the sold kitchen item after the fact, and thereby assign a valuation to the kitchen item (and COGS).

### Kitchen dashboard

Displays open tickets (kitchen orders) and time.

### Kitchen Report

Shows all recipes, and their cost based on historic wastage.

### Wastage Report

Display all wastage for period

### additional feature

Define par wastage values and have a report that shows if business is above or below par as %, graphed over time.

**Comment by mhbu50** [comment]
+1

**Comment by biruk360** [comment]
+1

**Comment by Tropicalrambler** [comment]
I believe the ERPNext provides most of this functionality, in particular "recipe",  use BOM and manufacturing module for each. Except:

- [ ] Should allow having open tickets. These will be defined by table (i.e Table 1, 2, 3). Bonus points for having this as a configurable GUI of tables.

- [ ] Displays open tickets (kitchen orders) and time.

- [ ] For "fast food" like kitchens,  it should display orders similar to 
https://i.ytimg.com/vi/GrqS9gPqaH8/maxresdefault.jpg

**Comment by fabyc** [comment]
+1

**Comment by umairsy** [comment]
@alimalkhalifa can you create a Bounty for this feature? Also, you can consider sponsoring it to fast-track.

https://erpnext.org/bounties
