### ISSUE TITLE
Meaningful Notifications, Notification Screen, Notification Settings, Escalation, and create issue from any Document

### ISSUE THREAD

**Issue by alimalkhalifa** [frappe/erpnext#6908]
# Meaningful Notifications

Currently, as a management user, or a user whose field of view is large, we get too many notifications for them to be meaningful.  Rather, I would like to lead an effort to make it so that a user will only get ***Actionable Notifications***.

# Notification Screen

Those notifications should be viewable in list view
Maybe notification should be a DocType?

# Notification Settings

Users should be able to define if they don't want to receive notifications from a certain module by default

Users should also be able to "subscribe" to a transaction at any point, and thereby be notified of any linked document changes

Users should be able to dismiss a notification, which will remove it from their notifications forever.  They can readd it by going back to the document and undismissing

Users should be able to define custom logic to receiving notification on per user and per role basis.
I.E a non-accounting but management role might define to not be notified of an overdue payment until it is 30 days or more overdue

# Escalation

Escalation should be defined on a per DocType basis.

Flow as such.

DocType Sales Invoice Level 0 notify all Accounts User role and Debt Collector role.  As such, current notification (overdue on the day it becomes overdue) will go to users with one (or both) of those roles.

Sales Invoice Level 1 notify all Accounts Managers.  Should any user with permission to Read or Write to this Document click the escalate button, it will be escalated to Level 1, thereby notifying all Accounts Managers.

Automated custom logic for escalation should also be definable as above User custom logic.

Unlimited number of levels, and may keep escalating indefinitely.

# Create issue from any Document

Any document should have a create issue button.  This will link the document to a new issue, where it can be submitted as normal.

This will make it easy for users to get help from accounts/IT when they face an issue.  It can create a separate path of help rather than making a comment and assigning the document, when you are instead flagging a technical or accounting issue.

**Comment by mhbu50** [comment]
+1

**Comment by alimalkhalifa** [comment]
We are working on an initial system for this. Will update!

**Comment by rmehta** [comment]
@alimalkhalifa did you make any progress?

**Comment by fginfodev** [comment]
+1

**Comment by fginfodev** [comment]
A notification configuration panel would be nice

**Comment by rmehta** [comment]
- Creation of issue is same as assignment
- Notifications are already role based
- Escalation can be done with Email Alerts

If there is any specific feature we are missing, lets create a new issue
