### ISSUE TITLE
Barcode Generator

### ISSUE THREAD

**Issue by alimalkhalifa** [frappe/erpnext#6909]
It would be nice if we had a bar code generator (for printing using a label printer or other method).

This can apply to Batch No, Barcode No, Serial No, Assets, etc

As well as encoding for example item barcode, delimiter, weight for weighed items.

We can have multiple barcode formats available.

**Comment by giovanni-codrotech** [comment]
Have a look at

https://github.com/frappe/erpnext/issues/6800

**Comment by alimalkhalifa** [comment]
Thanks for that link. I missed the generation part.

Will close this issue now
