### ISSUE TITLE
POS for weighed items

### ISSUE THREAD

**Issue by alimalkhalifa** [frappe/erpnext#6910]
# POS for weighed items

### Item

Weighed item? check box

Weighed item barcode format.  This is usually one of:
- BarcodeNo {Delimiter} Weight
- BarcodeNo {Delimiter} Weight {Delimiter} UOM as Number

Should have support for data that should be discarded.  This is because some government regulated weighed barcodes such as those that come on livestock carcasses might have encoded things like slaughterhouse establishment numbers, export certificate numbers, etc which might not be relevant for us.

### Item UOM

Field for UOM as Number for barcode (optional)

### POS

When a weighed item is scanned, POS should expect the defined format and parse the weight automatically.

**Comment by giovanni-codrotech** [comment]
There are cases in which price for weighed item is printed in the barcode. 

They are normally used named at variable price; i.e. vegetables, fruit etc. 

Customers weights items by themselve and a label is printed based on the price per UOM (Kg).

This is usually:

BarcodeNo {Delimiter} Price

**Comment by Helkyd** [comment]
I did something for me maybe can be modified and implemented by asking what barcode type or initial code is to have this code implemented ...

https://discuss.erpnext.com/t/how-can-mange-barcode-for-weighted-items-in-pos/20066/4

**Comment by Botanium** [comment]
Wow, so this feature has been left for all of these years?

**Comment by HaniTetouha** [comment]
this should be implemented

**Comment by ankush** [comment]
This hardcoding of information might work for you but it's not the general case. 

What if we allocate separate barcode for each UOM? 

Suggested by @szufisher here: https://github.com/frappe/erpnext/pull/30445#issuecomment-1080076066

**Comment by Botanium** [comment]
Every POS comes with this feature. Adding the parameters for weight or price-based items to the POS settings page will help.
