### ISSUE TITLE
Gantt Chart: Task should display more information while hovering

### ISSUE THREAD

**Issue by Devens** [frappe/erpnext#6916]
Please see following screen shot. Task should display "Project" & "Assigned to" Fields also. 

![untitled_clipping_111316_101315_am](https://cloud.githubusercontent.com/assets/10671911/20243733/14703dd6-a98a-11e6-8f27-716e403def39.jpg)

**Comment by Dbonejones** [comment]
https://github.com/frappe/gantt/issues/9
