### ISSUE TITLE
Balance Sheet report error

### ISSUE THREAD

**Issue by samehmreda** [frappe/erpnext#6918]
Hello,

i got the attached error while trying to get balance sheet report.

please advise.
[Balance Sheet.pdf](https://github.com/frappe/erpnext/files/587724/Balance.Sheet.pdf)

Thanks,

Sameh,

**Comment by rmehta** [comment]
<img width="826" alt="screen shot 2016-11-15 at 4 21 20 pm" src="https://cloud.githubusercontent.com/assets/140076/20303029/914c55da-ab4f-11e6-89cd-897a450b4b1d.png">

@samehmreda please don't attach PDFs in bug reports!

**Comment by samehmreda** [comment]
Ok ,


i just got the attached error while trying to open balance sheet report.


please advise urgent ASAP.


Regards,


Sameh,



________________________________

**Comment by samehmreda** [comment]
any updates Sir?


________________________________
