### ISSUE TITLE
Error page after submitting Job Application

### ISSUE THREAD

**Issue by justinlusg** [frappe/erpnext#6919]
Submit Job Application via Web Form
![image](https://cloud.githubusercontent.com/assets/12539216/20246866/0b791a7e-a9fb-11e6-80da-ecc17105bcf0.png)

Upon submitting, the record is saved in the system, but the applicant end up viewing this page instead of the "thank you" page. 
![image](https://cloud.githubusercontent.com/assets/12539216/20246868/0f01f080-a9fb-11e6-84c5-2d01c3039e8a.png)

I have already checked the Web Form setting and confirmed everything is correct.
![image](https://cloud.githubusercontent.com/assets/12539216/20246877/2da26d08-a9fb-11e6-9cfd-326e504d94a1.png)

**Comment by KanchanChauhan** [comment]
Change success URL to `/jobs`

**Comment by justinlusg** [comment]
@KanchanChauhan  it is the same, it still redirect me to something like this.. 

> http://erp.agtech.com.sg/job_application?name=test%20-%20test@test.com

**Comment by justinlusg** [comment]
You can try to submit the form at http://erp.agtech.com.sg/job_application?job_title=account-executive also to see the error

**Comment by KanchanChauhan** [comment]
@justinlusg Did you change the success URL from `/` to `/jobs`?

**Comment by jwrober** [comment]
This behavior is same as https://github.com/frappe/frappe/issues/2266

**Comment by rmehta** [comment]
pushed a fix
