### ISSUE TITLE
Missing ref and date column in other languages except En

### ISSUE THREAD

**Issue by vladucoju** [frappe/erpnext#6927]
Hi,

i am working in croatian language. I tried to print account receivable report but on this language row ref and date is missing. Also there are no values in other columns. I check other languages, and there is a same problem except English and EN-Us.

Same problem with delivered items to be billed.

Delivery trends also.

I am on the latest version.

Could you please fix this.

Thanks in advance

**Comment by rmehta** [comment]
fixed via https://github.com/frappe/erpnext/pull/6943

**Comment by KanchanChauhan** [comment]
Fixed for Accounts Receivable report. 
Delivery Note Trends report not fixed yet. Values are fetched based on field and field not being translated. Will need more work.

**Comment by vladucoju** [comment]
Ok @KanchanChauhan .Account receivable with ref field is one of the most important reports. I updated this morning and now is perfect. Great work!

Beside Delivery Note Trends try to fix Delivered items to be billed. Item column is blank. Other columns are ok.
Thanks once again.

**Comment by vladucoju** [comment]
Hi Kanhan,
Did you had time to work on this?

**Comment by vladucoju** [comment]
Closed
