### ISSUE TITLE
Custom Report - Top line with text boxes for filter

### ISSUE THREAD

**Issue by Priyanka-IAS** [frappe/erpnext#6929]
Hi,

Like we have the first line in most reports with text boxes on top of each column where the results get filtered based on the text we type, is it possible to have that first line for filtering in Custom Reports as well?

I know I could do a “Add filter” to do the same, but the text boxes are way easier to use - in case they are available.

Regards,

Priyanka

PS - I made a custom report for Quotations. Very often we need to refer to old quotations to see if we have quoted this item to any customer in the recent past. We usually check the rate and as well as quantity quoted. Quotation trends Report doesn't really help to do this.

**Comment by rmehta** [comment]
@Priyanka-IAS New clickable filters coming in 7.2. Courtesy of @IAGAdmin and @RobertSchouten
