### ISSUE TITLE
Issue in Print Format after upgrade to 7.1

### ISSUE THREAD

**Issue by Devens** [frappe/erpnext#6931]
Please see following screenshot. 

It shows multiple horizontal lines (instead of only one line)

![untitled_clipping_111416_030310_pm](https://cloud.githubusercontent.com/assets/10671911/20259478/37e89bb8-aa7b-11e6-80d9-6994d864df11.jpg)

**Comment by rmehta** [comment]
This was fixed

**Comment by Devens** [comment]
In which release fix would come? Since we need to send it regularly, it affects the working. Kindly advise. 

![image](https://cloud.githubusercontent.com/assets/10671911/20343198/7159d184-ac13-11e6-8c63-beba5d26726e.png)

**Comment by rmehta** [comment]
@Devens you can go to "Edit Properties" in your print format builder and uncheck "show lines after section break"

**Comment by Devens** [comment]
Got it. Thank you very much.
