### ISSUE TITLE
Commission for Sales Person and more

### ISSUE THREAD

**Issue by piratedkhan** [frappe/erpnext#6935]
**Background** 
We have Sales Partners/Persons in selling Module in order to track commission on sales used in most of the business model. The commission is rate can be set for the sales partner/person in percentage. there were no improvements made to this since long time.

**Need Improvement**

- Different sets of commission rates for single sale partner/person.
- i would like give customer detail example. the customer dashboard contains heatmape, related sales order, invoices, receivable, payments received etc. if features like this implemented for sale partner/person that contains relative information like total annual commission, unpaid commission, sales details etc. it will be great job.
-  payment tool can also be modified for it paying commission. selecting payment and in the party there must be an option to select supplier or salesperson/partner.
- For sales person if there is a structure to make the incentive more dynamic it will be cool. 
- Calculation of commission and incentive for salesperson must have option to add to salary slip. we can use salary structure for this also.

**Comment by maxfu9** [comment]
Any updates about sales partner?

**Comment by maxfu9** [comment]
update?
