### ISSUE TITLE
When Duplicating a Sales Order the Save button disappears on the form

### ISSUE THREAD

**Issue by monojoker** [frappe/erpnext#6938]
Hi Guys,

When we duplicate a Sales Order the Save button on the form will usually disappear. Given the recent change to CTRL + S behaviour we can't then save easily. Triggering a Back browser navigation then Forward restores the Save button. Can you have a look into this please as it's not ideal.

Thanks
Liam.

**Comment by netchampfaris** [comment]
@monojoker Please provide the frappe and erpnext version on which you encountered the issue. Since, I cannot reproduce on v7.1.15

**Comment by rmehta** [comment]
Cannot replicate
