### ISSUE TITLE
Calendar field is non-editable in Quick Edit screen

### ISSUE THREAD

**Issue by truptikmali** [frappe/erpnext#6940]
When we try to populate any document through quick entry screen - the date(calendar field) field is non editable. We can not select any date - unless we jump to full screen edit view.

**Comment by netchampfaris** [comment]
@truptikmali 
Cannot reproduce. For which doctype is this not working?

**Comment by truptikmali** [comment]
It was happening when I had last did bench update a week back to get latest version. Today, I did bench update again and verified and this is not happening. So lets close it. Thanks
