### ISSUE TITLE
Table Naming Logic? tabAccount --> Account

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#6941]
I was wondering if it is 'just' legacy naming scheme or if it has a purpose that all tables in MariaDB are called tab... like `tabSupplier Quotation` shouldn't that be just `Supplier Quotation`.

**Comment by rmehta** [comment]
This is a massive massive rewrite - basically involves running `ALTER TABLE` on all tables and rewriting *all* SQL queries. I guess we can live with this. ?

**Comment by dottenbr** [comment]
I can absolutely live with it, but found it curious.

**Comment by dottenbr** [comment]
we also have to consider that some people may have written custom mysql queries referencing these tables and a lot will break until they refactor it. Maybe this is an architectural choice that we will have to live forever or will there be an announced cut lets say in version 9? Just some thoughts.

**Comment by emakis** [comment]
I don't think the table naming is an issue. The prefix 'tab' is very common and distinguishes the objects of db such like qry for queries etc. Personally I like the 'tab' prefix
