### ISSUE TITLE
Sales invoice template with sum ident

### ISSUE THREAD

**Issue by vladucoju** [frappe/erpnext#6942]
i'm trying to custumize sales invoice print format. I didn't saw any similar example on community. I wan't to sum item fields on invoice. For example i have multiple same items on invoice. When i create Sales Invoice from multiple delivery notes there are multiple same items. I think default print format should do this.

**Comment by rmehta** [comment]
Please post help questions on https://discuss.erpnext.com

**Comment by vladucoju** [comment]
Hello, I already post it
https://discuss.erpnext.com/t/custom-sales-invoice-print-template-with-sum-item/17708

They told me to create new issue. I think that it will be usable to have item sum option in template builder,
