### ISSUE TITLE
PDC Management Suggestion - Full Feature [Bounty]

### ISSUE THREAD

**Issue by ai-erp** [frappe/erpnext#6946]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=39242671)](https://www.bountysource.com/issues/39242671-pdc-management-suggestion-full-feature?utm_source=39242671&utm_medium=shield&utm_campaign=ISSUE_BADGE)

Dear ALL, 

with reference to https://github.com/frappe/erpnext/issues/6859 , I think full feature required for managing PDCs are as follows:

	FIELD TO BE ADDED IN JOURNAL/PAYMENT ENTRY
•	RECEIPT/VOUCHER DATE 
•	DATE DEPOSITED (FOR PDCs RECEIVED)

	In BANK RECONCILIATION, when bank account is not selected and the user clicked on “Get Payment Entries”, the Outstanding Cheques and Deposit in Transits for ALL Bank Accounts should be displayed based on the period covered selected.

From there, user can update to which bank the cheque has been deposited (column for Deposited to - Bank Account Option). It should also automatically update entry to reclass the previously selected bank account during the initial entry when the cheque has been received. This is important to note since the company with different bank accounts have the discretion to which bank they want to deposit the cheque when it is due for deposit. This is also useful for companies receiving too many cheques in a day or a week in monitoring which cheques are still on hand awaiting for deposit. Update button should be added.

In cases of Returned/Redeposited Cheques, there should also be a column in the Bank Reconciliation with label “Returned/Redeposited”. In the same way in entering when cheque was deposited, it should also automatically update reversal of initial entry on the journal (debiting back the receivable and crediting cash in bank for returned cheques / debiting back the cash in bank and crediting receivable for cheques redeposited)

	FROM JOURNAL/PAYMENT ENTRY, A REPORT SAME AS THE BANK RECONCILIATION 
STATEMENT SHOULD BE GENERATED WITH THE FOLLOWING COLUMNS:
•	RECEIPT/VOUCHER DATE
•	POSTING DATE (SAME AS THE CHEQUE DATE)
•	PAYMENT ENTRY (Receipt/Voucher created ex. PDCR-00001, PDCI-00001, etc.)
•	AGAINST ACCOUNT (CUSTOMER/SUPPLIER, ETC.)
•	DEBIT AMOUNT
•	CREDIT AMOUNT
•	TOTAL FOR BOTH DEBIT AND CREDIT SIDE
•	CHEQUE/REFERENCE NO.
•	CHEQUE/REFERENCE DATE
•	DATE DEPOSITED / RETURNED 
•	DEPOSITED TO (BANK ACCOUNT OPTION)

 	NOTE: IN THIS REPORT, THERE SHOULD BE AN OPTION TO SELECT PERIOD COVERED FOR THE PERIOD WE WANT TO GENERATE

	In connection to the above details, In CUSTOMER/SUPPLIER dashboard, below should be added aside from annual billing and total UNPAID (refers to invoices/returns only) Portion.

 	PDCs RECEIVED BUT NOT YET CLEARED – this is to show how much PDCs were exactly received from the customer including uncleared cheques and paid to supplier including cheques date which have passed but not yet cleared in the bank.

 	TOTAL OUTSTANDING - this portion does not only reflect invoices/returns made by customer/supplier but should also include journal entries made to book receivables/payables. This amount should not deduct uncleared cheques received/issued.

NOTE: For most companies, not all users have the access to view GL to check how much PDC has been received/paid by customer or paid to supplier dashboard, in this case, 
we suggest to have this feature in viewing customer/supplier in ERPNext. Below
is a sample for your reference:

![cus-](https://cloud.githubusercontent.com/assets/16744099/20304154/408e39e4-ab48-11e6-84a9-394f72d6fbe3.png)

![sup](https://cloud.githubusercontent.com/assets/16744099/20304162/48559550-ab48-11e6-90d6-a6592f300ca1.png)

**Comment by me2ne** [comment]
important feature  , because of this weakness we are still using  tally erp to manage our cheque and other thing we manage with erpnext .

**Comment by Devens** [comment]
+1

**Comment by ai-erp** [comment]
I have paid $100 for this post in Bounty Source. @me2ne  @Devens  hope you are going to contribute as well to add this feature in erpnext... Thanks...

**Comment by ahmedfme** [comment]
Yes , this feature is very important in Middle East.
I hope it will be available soon

**Comment by ahmedfme** [comment]
+1

**Comment by me2ne** [comment]
+1

**Comment by zbisho** [comment]
Any update on this feature please, much appreciated

**Comment by riyasrawther** [comment]
Yes very important for us too..

**Comment by bghayad** [comment]
@ai-erp 
Have you tried this: https://github.com/hfaridgit/Cheque-Management?
Regards
Bilal

**Comment by riyasrawther** [comment]
@ai-erp I tried that, but no use

**Comment by riyasrawther** [comment]
Approximately how much money need to done this work.

**Comment by me2ne** [comment]
i think money not important , it's important that  ERPNEXT team understand how much this option to control and manage PDC is important in some countries .

**Comment by me2ne** [comment]
Hi @bghayad 
is it stable and good future for PDC management ?
why they didn't add it in erpnext ?
Regards

**Comment by hda** [comment]
Dear community,
Hope this pull request will work for the features required : https://github.com/frappe/erpnext/pull/12961
Its exactly the same with bank statement management as suggested in requirement specification above. Any feedback will be appreciated.

**Comment by bghayad** [comment]
Hello @hda 
Thanks a lot for you.
How can we know that this cheque has been returned? There should be a status in the payment that declare this is returned cheque. 
The returned cheques are required to be known to be able to follow up it again.
One more point which is also important: at the customer dashboard, it is required to know the PDC amount and the Returned PDC amount, because by knowing the Unpaid, the PDC amount and the Returned PDC amount, then it is possible to follow up the payments with the customer and it will be very good to control its payments and its credit.
Regards
Bilal

**Comment by zbisho** [comment]
Hi,

We tried to use this module, however we faced the issue that the code uses the default accounts payable defined in the company, and ignores the one we entered in the Payment Entry, It also ignores the bank account we entered in the payment entry, where it would be logical to use it to add to the cheque it creates instead of us going to manually update that in the check module itself.

These two issues are preventing us from rolling this module to production, I wish they could be handled

Cheers

**Comment by bghayad** [comment]
Hello @zbisho 
I might need to install it and try it and come back for you.
But I have a question: it was contains the ability to determine if this cheque is cleared or returned (status of cheque)?
Regards
Bilal

**Comment by bghayad** [comment]
It is module that needs to be installed.

**Comment by zbisho** [comment]
yes, it does

**Comment by mghoneem10** [comment]
any updates ??

**Comment by harshit-30** [comment]
This is now possible using Post Dated Cheque Entry.
Refer [here](https://docs.erpnext.com/docs/v13/user/manual/en/accounts/articles/post-dated-cheque-entry).
