### ISSUE TITLE
In Sales Invoice - "Project" Field should be allowed to edit after submit. 

### ISSUE THREAD

**Issue by Devens** [frappe/erpnext#6951]
Sales Invoice cannot be cancelled after Payment is done against the same. Hence, changing Project after submission should be allowed to modify the same afterwords.

**Comment by nabinhait** [comment]
Project is linked to GL Entry of Sales Invoice, thats why we can't allow to change it after submission. Why can't you cancel/amend the sales invoice after payment is done against it?

**Comment by Devens** [comment]
@nabinhait - I think this is resolved in latest release, right?

**Comment by chdecultot** [comment]
Hi @Devens ,

You can cancel and amend your invoice after submission, even if a payment entry as been made against it. As Nabin said, it is the best way to ensure GL entry integrity.
I am therefore closing this issue.
