### ISSUE TITLE
Suggestions on General Ledger Report (Filtered report also should show total row)

### ISSUE THREAD

**Issue by Devens** [frappe/erpnext#6952]
Please see following screenshots. 

Filtered report also should show total row. 

![untitled_clipping_111516_081345_pm](https://cloud.githubusercontent.com/assets/10671911/20309915/de9556dc-ab6f-11e6-8dc5-4431dafbaef2.jpg)

![untitled_clipping_111516_081515_pm](https://cloud.githubusercontent.com/assets/10671911/20309954/1379f286-ab70-11e6-8a05-763980ef356a.jpg)

**Comment by rmehta** [comment]
Figure out a generic way to do this in SlickGrid

**Comment by djpalshikar** [comment]
Total should be a separate field, it should also update after filters are added.

**Comment by harshit-30** [comment]
Not applicable in the current versions.
