### ISSUE TITLE
(Repeatable Calculation Bug) Tax calculated incorrectly on PO with many line items

### ISSUE THREAD

**Issue by kodybaker** [frappe/erpnext#6954]
I've found a repeatable bug in ERPNext: v7.1.7, Frappe Framework: v7.1.6 (ERP demo site) and ERPNext: v7.1.11, Frappe Framework: v7.1.13 (our production site).

See the two sample POs I've created here: https://demo.erpnext.com/desk#Form/Purchase%20Order/PO-00016
and here: https://demo.erpnext.com/desk#Form/Purchase%20Order/PO-00017

Both subtotals are correctly calculated as $ 7,716.67. 
The PO with one line item calculates a 5% tax correctly as $ 385.83
The PO with 22 line items calculates a 5% tax **incorrectly** as $ 385.87.

It's only a $0.04 difference, but there is some sort of rounding bug happening here when there are many items in the PO. It's confusing though, because both POs are reporting the same subtotal.

Definitely doesn't give me confidence in the trueness of my numbers though! 

Can anyone weigh in on what could be happening?

**Comment by partzsch** [comment]
I think it is the way rounding is handeled...

It should be if per item line - usefull for different tax rates via different item lines
(("net Item price in company currency" * "PO conversion rate foreighn currency")rounded to 2 digits decimals) * Tax rate = item Tax
then add up item taxes per different tax rates

if consolidated tax - useful if only one tax rate troughout all items
(("net Item price in company currency" * "PO conversion rate foreign currency")rounded to 2 digits decimals)
then Sum up " rounded net item prices"
then "sum of net item prices" * Tax rate = item Tax

well at least for Germany and the VAT both ways are allowed and should not give a difference greater then 0,01
no matter how many items are in the pipe.
that difference however is not crutial as VAT taken and VAT payed are consolidated and only the difference payed is forwarded to Tax officers
