### ISSUE TITLE
Suggestion for Purchase Order Item (Required by Date should be below Item Description)

### ISSUE THREAD

**Issue by Devens** [frappe/erpnext#6967]
PL see following screenshot. 

![untitled_clipping_111616_080750_pm](https://cloud.githubusercontent.com/assets/10671911/20351313/523dc6d2-ac38-11e6-8b97-7a87102490d3.jpg)

**Comment by KanchanChauhan** [comment]
If we do this, it will affect Purchase Order Item child table as well. I tried, it was not looking very good. 
<img width="888" alt="screen shot 2016-11-30 at 4 50 50 pm" src="https://cloud.githubusercontent.com/assets/16913064/20750491/34cd6540-b71d-11e6-96de-ef9d52021a3b.png">
