### ISSUE TITLE
Bug: Form pre-filled by filter

### ISSUE THREAD

**Issue by cgpurbaugh** [frappe/erpnext#6968]
Having a filter applied in list can fill fields that shouldnt be.  Example:  % Ordered, below.
![image](https://cloud.githubusercontent.com/assets/13136405/20357628/aa7f90a6-abf6-11e6-92c9-6d0dd5d3a5cc.png)

![image](https://cloud.githubusercontent.com/assets/13136405/20357598/99270302-abf6-11e6-8a16-cf3f23e3e5f2.png)

**Comment by rmehta** [comment]
This should only be for Link Fields!
