### ISSUE TITLE
Trial balance for Party with total sum at all columns

### ISSUE THREAD

**Issue by vladucoju** [frappe/erpnext#6975]
Hi,

i wan't to add total sum at all columns in Trial balance for Party report.

![image](https://cloud.githubusercontent.com/assets/9590909/20379510/e4981a32-ac9c-11e6-86b3-2e277939055c.png)

Also there is another issue

when i filter (closing) total sum is not updated on report. 
Also filter in pdf is not working. Filter is ok in print view but sum is not updated.
Couple days ago i open issue on git hub for missing total sum in closing columns.

**Comment by vladucoju** [comment]
When we could expect this fields? Everyone need closing sum. We wan't this in beautifull pdf report, not to export and sum in excel.

**Comment by nabinhait** [comment]
fixed

**Comment by vladucoju** [comment]
I updated and it works. Thanks. You didn't work yet about problem with filter in pdf. I try to filter but and print but that doesn't work. Ok, now this is almost perfect module. Thanks again @nabinhait for your great work. Keep going ;-)

**Comment by vladucoju** [comment]
Hi Nabin,
did you had time to see issue about pdf print?When using filters <, >... he works fine but when i try to print in pdf, there filters are not applied. In print filters are ok, but sum values are not filtered.

**Comment by nabinhait** [comment]
The filters below the header is only for filtering in client side. As PDF printing and export functionality is executed in server side, those filters is not applied. To make it work, we have rewrite a lot of things.

**Comment by vladucoju** [comment]
Ok, we wan't do that :-). Can i ask you about reports wishlist? I've been watching your presentation from ERPNEXT conference and you told that you wan't from us more report request. I agree that ERPNEXT biggest disadvantage are reports. I will prepare some basic examples to suggest. Right now i am focused on CRM and Projects and i will do it for that modules.
