### ISSUE TITLE
Production Planning Tool "BOM BOM not found"

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#6979]
When you plan a Production Order in the Production Planning Tool you get the error "BOM BOM not found".

![bildschirmfoto 2016-11-17 um 11 19 58](https://cloud.githubusercontent.com/assets/9136094/20385514/0413b5d6-acb8-11e6-8697-fe17ce868a87.png)

By playing around I found that this is caused if a BOM is not set as the default for an item. So I propose when you create a new BOM for an item it is automatically set to default. If you create a new version (reject -> amend) that new BOM should be default. This error message "BOM BOM not found" is very unclear. So the default behavior should be changed and the error massage should be changed to "No default BOM selected for item XYZ. Please set a a default bom in the BOM DocType".

**Comment by KanchanChauhan** [comment]
@dottenbr I think default behavior is what you explained,` Is Default` is checked by default and if new BOM is created `Is Default` is unchecked on the previous one. Can you please check again.
Fixed the error message via https://github.com/frappe/erpnext/pull/7000
