### ISSUE TITLE
POS View and many others have auto realignment error

### ISSUE THREAD

**Issue by elvinng37** [frappe/erpnext#6988]
Whenever you click certain buttons, the screen shifts to the original position and this is rather frustrating.

Eg, In POS View, once u click and item, it automatically goes into the Search item field again. Same when you increase the quantity of the item you selected. This is especially irritating when you are using mobile devices or other devices where the screen is small.

It also happens when you use the cell boxes within a form, Eg add items, customise form, etc. Once you try to click the done button, it realigns downwards again and u have to click done again. 

Please help. Thanks

**Comment by rohitwaghchaure** [comment]
Hi @elvinng37 

We keep the focus in the search bar after adding an item into the cart for the user who use the serial no to place an order. I have never found the issue when clicked on the item to place an order.

**Comment by PawanMeh** [comment]
Kindly share screen shot or gif file of the issue & re-open issue. Please share the version of frappe & ERPNext on which you are facing this issue. Also, ensure your browser is on the latest version.

Closing this for now.
