### ISSUE TITLE
Precision Enhancement for Currency Field

### ISSUE THREAD

**Issue by rohitwaghchaure** [frappe/erpnext#6993]
**Make settings to set precision for the fields(rate, amount)**
- [x] Add provision to set precision for field rate, amount on the accounts settings 

- [x] Identify the rate, amount fields on the sales and purchase cycle and set the precision as per defined in the accounts settings 

**Round off amount on the sales and purchase**

- [x] Add field round off account, round off amount on the sales and purchase cycle

- [x] Add provision to set allowance to calculate the round off amount

- [x] Calculate the round off amount and book against the round off account.

**Comment by harshit-30** [comment]
Fixed.
