### ISSUE TITLE
Overlay sub-page too big for screen but no scroll bar

### ISSUE THREAD

**Issue by addymuliady** [frappe/erpnext#6996]
Hi,

I have this view problem where the sub page overlay is too large for the screen. However. there is no scroll for that sub page. See pic and I think you know what I mean. It needs to either be condensed to fit standard screens or have a scroll at the sides. Currently, I have to reduce view size via browser.

![image](https://cloud.githubusercontent.com/assets/21187126/20460955/bab380d8-af2d-11e6-9d95-84694ca664ba.png)

Hope this issue is valid.

Thanks!

**Comment by addymuliady** [comment]
To add for Payment Entry, the sub page will stay in position during scrolling down.

**Comment by rmehta** [comment]
If your mouse is on the background, the background will scroll, if you scroll when your mouse is hovering on the dialog, it will scroll the dialog.

Does that fix this issue?
