### ISSUE TITLE
Feature Request: Email Templates

### ISSUE THREAD

**Issue by mukeshmv1** [frappe/erpnext#6997]
Most business communications have some similar emails to be sent to clients at various stages of communication. It will be useful if these can be saved as Email templates and can be pulled while sending emails from ERP.

Currently New Email form from in any doctype eg Lead, customer etc is rendered from[ communication.js](https://github.com/frappe/frappe/blob/develop/frappe/public/js/frappe/views/communication.js) as understood on below forum thread.

https://discuss.erpnext.com/t/new-email-doctype-name/17374

If New Email form was a doctype, it would have been a simple customisation which can be done by anyone as below.

Create 1 Custom Doctype: “Email Templates” having 3 fields
Field 1: Title
Field 2: Subject
Field 3: Message

Create a link field in New Email doctype and link it to above created "Email Templates"
This will be used to pull subject and email message from “Email Templates” to "New Email".

But unfortunately "New Email" form is not a doctype but rendered from below script. So need your help, please consider adding this functionality. 
It's a simple feature, but can be very useful to many ERPNext users, who would have similar business emails to be sent to Lead/Opportunity/Customer.

**Comment by yashodhank** [comment]
**My two cents**
The default email templates that will be supplied with the system are sent when certain events occur.
Users may also able create custom email templates which users can send to clients manually at any time or assign to products/services as their welcome email.
Or email template may also be able to assign to any other doctypes/workflow etc.

**Comment by rmehta** [comment]
Already exists "Standard Reply"
