### ISSUE TITLE
Error with "purchase Invoice" object has no attribute 'status'

### ISSUE THREAD

**Issue by fderyckel** [frappe/erpnext#7008]
I'm on virtual machine, with almost latest update. 
I did the usual bench update from the frappe-bench folder and I got this error

'Purchase Invoice' object has no attribute 'status'

I'm attaching the screen shot of the error.  (Sorry I do not know how to copy-paste from the vm console)

![screen shot 2016-11-21 at 10 08 20](https://cloud.githubusercontent.com/assets/7240992/20475144/d1e252b6-afd2-11e6-9570-5552e3a46b50.png)

**Comment by fderyckel** [comment]
Due to this, i'm not able to log in on localhost.  All I got is "Updating. We will be back in a few moments..."  Any way I could get back on track?

**Comment by rmehta** [comment]
@rohitwaghchaure can you check?

**Comment by rohitwaghchaure** [comment]
Hi @fderyckel 

Can you please share complete error traceback

**Comment by fderyckel** [comment]
hi @rohitwaghchaure , 
Sorry I'm unable to give you more than the picture that I have attached on my first post.  
I'm on VM and I don't know how to scroll up-down the console and/or copy paste.  
I've just updated and the problem persisted. 

Thanks

**Comment by fderyckel** [comment]
hi @rohitwaghchaure , 
Where do I find the purchase_invoice.json file?

**Comment by yashodhank** [comment]
@fderyckel File will be located in your frappe-bench directory:

```path
/home/frappe/frappe-bench/app/erpnext/blob/master/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.json
```
Open json file in nano (text editor)
```
Press CTRL & w key
Copy paste following to search box in nano editor prompt
"fieldname": "status"
Then press enter, if that files has it/not report back in here.
```

**Comment by fderyckel** [comment]
Ok.  Yes the file has it.  See attached.  
The pathname is slightly different though: 
apps/erpnext/erpnext/account/doctype/purchase_invoice/purchase_invoice.json

![screen shot 2016-11-22 at 15 51 32](https://cloud.githubusercontent.com/assets/7240992/20540198/e905bb2a-b100-11e6-9c7d-7ac2bbb5fb87.png)

**Comment by fderyckel** [comment]
@rohitwaghchaure 
Hi Rohit, 
It seems like the fixed works when I did the bench update.  It used a patch and I can work on it again. 
Thank you so much...
Best regards, 
François
