### ISSUE TITLE
Multiple Delete and Multiple Select of Child Items

### ISSUE THREAD

**Issue by addymuliady** [frappe/erpnext#7009]
Hi

I would like to request for a feature which I think would make it easier to use ERPNext

Use case
Sales Order >> Get Items from Quotation

I need only 2 out of 10 quoted items. At the moment, I think we have to delete line by line item but for user convenience, are we able to do a selection and delete items we don't need at once?

 16 clicks at the moment can be reduced to at least 10.

Thanks.

**Comment by kodybaker** [comment]
+1

**Comment by Tropicalrambler** [comment]
+1

**Comment by Devens** [comment]
+1

**Comment by mhbu50** [comment]
please close this, it is done
