### ISSUE TITLE
Notification e-mail settings not saving giving error

### ISSUE THREAD

**Issue by hfaridgit** [frappe/erpnext#7017]
![notification mail](https://cloud.githubusercontent.com/assets/19759675/20483403/82c8540a-affa-11e6-8617-8693c1ca1a84.jpg)

**Comment by Albatros79** [comment]
I also have a problem with email 

I set an outgoing email account 
But my mails which is sent through menus has never arrived to the recipients

But I just got a daily reminder from erpnext (set email address) 

What can be wrong

**Comment by yashodhank** [comment]
@hfaridgit please do care to share version details, setup as development / production environment? and copy paste full console log from browser for us to troubleshoot.

**Comment by hfaridgit** [comment]
It was server problem (server was blocking smtp). sorry.
