### ISSUE TITLE
Got error when clicking on Help

### ISSUE THREAD

**Issue by hfaridgit** [frappe/erpnext#7022]
![help error](https://cloud.githubusercontent.com/assets/19759675/20484834/bb183b84-b001-11e6-87c1-ddae394dc7e2.jpg)

**Comment by KanchanChauhan** [comment]
Please update and try again.

**Comment by yashodhank** [comment]
@hfaridgit Please confirm if it is fixed so that we will able to close this issue for good.

**Comment by hfaridgit** [comment]
Yes after update is was fixed.
