### ISSUE TITLE
Feature Request: Sales Analytics Graphing, Budget variance graphing.

### ISSUE THREAD

**Issue by Tropicalrambler** [frappe/erpnext#7027]
Sales analytics report for ERPNext v7 looks fantastic!

I would like to request the addition of the following characteristics

- [ ] 1. Sales report allows comparison of periods. 
One can compare Jan 2014, Jan 2015, and Jan 2016. or
One can compare Jan 2016, Feb 2016
The comparison can be by day, week, etc.

- [ ] Sales report allows basic statistics.
e.g.  For three years of sales data, 2014, 2015, 2016, each month can be Averaged (mean) µ
Then, Limit graphs can be constructed based on
a. Budgeted amounts (Budget sets the "mean")
b. The average of the selected periods and six standard deviations + an d- from the mean: -3σ, -2σ, -1σ  1σ, 2σ, 3σ.  This is a very basic six-sigma graph, which is very useful for finding pattern changes in sales
Colors for the limits should be customizable.  However I provide an example of a typical graph I use to analyze behavior through time.
![screen shot 2016-11-21 at 5 25 13 pm](https://cloud.githubusercontent.com/assets/16600935/20504910/92f902ec-b00f-11e6-946a-b31b5a044c14.png)

c. Max, Min reference data for each period considered.  For example, Jan can have both a Max or Min preset to clearly display goals. Here is an example of the same data:

![screen shot 2016-11-21 at 5 26 46 pm](https://cloud.githubusercontent.com/assets/16600935/20504946/c322d34e-b00f-11e6-90d5-915ed0229df6.png)

- [ ] This report should also be available for expense accounts as well (COGS, General expenses), so that any outliers can be seen.

**Comment by SonaliBudhrani** [comment]
+1
