### ISSUE TITLE
Drag & Drop file directly from email attachment...

### ISSUE THREAD

**Issue by NickMalef** [frappe/erpnext#7028]
ERPNext drag and drop works great when the file is in a folder, but fails if the file is an email attachment.

In order to simulate, please try to drag an email attachment into a project.

**Comment by rmehta** [comment]
You mean email attachment of your desktop's mail app?

**Comment by NickMalef** [comment]
Yes, exactly!

**Comment by NickMalef** [comment]
To simulate, please drag an email attachment eg. from outlook into eg. a project...

**Comment by rmehta** [comment]
@NickMalef seems like the email client (Outlook) and web browser don't talk to each other. Not sure if we can fix it from our end, as the browser as no control beyond its limits.

Closing this issue.
