### ISSUE TITLE
POS - Default Warehouse not fetching from POS Profile

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#7037]
In the POS Profile, I defined default Warehouse for the User.

But when I was creating POS Invoice, it was not fetching that Warehouse. It only checks for the default Warehouse in the Item master. If in the Item master, default Warehouse is not set, then Item is not added in the POS Invoice.

**Comment by addymuliady** [comment]
Hi

I have updated to 7.1.20 and it is still showing quantity from default warehouse.

![image](https://cloud.githubusercontent.com/assets/21187126/20821864/2d81b25e-b881-11e6-8df3-c7f07aa73d2d.png)

![image](https://cloud.githubusercontent.com/assets/21187126/20821878/45a6ac22-b881-11e6-8233-5f51dd204f76.png)
