### ISSUE TITLE
Exchange rate issue on payment entry for Purchase Order / Invoice

### ISSUE THREAD

**Issue by OneiricIT** [frappe/erpnext#7040]
ERPNext version: 7.1.16
Frappe version: 7.1.17

Believe https://github.com/frappe/erpnext/issues/4840 may also relate to similar issue

When completing purchase orders dealing with multi-currency, there is an issue with the present setup where the exchange rate is set only on the Purchase Order or Purchase Invoice and not the payment entries. Although the present would be workable if one payment was made at the time of the PO or PINV creation as the exchange rate can be set, it does not cater for multiple payments over a period of time. Exchange rate should be set on the payment entry. There would still need to be an 'estimated' conversion currency on the PO / PINV. Adding the exchange rate to the payment entry will also allow for historical rate reporting.

Some examples

**Scenario A: Full payment made on receipt of Supplier Invoice** 

-PO is raised to supplier with exchange rate auto populated
-Invoice is received from supplier
-Create Purchase Invoice and either set / use auto added exchange rate
-Make immediate payment which reflects the present exchange rate

This has no issue

**Scenario B: Initial deposit made on purchase order, followed by payment / final payment at later date**

-PO is raised to supplier with exchange rate auto populated
-Deposit is made based on pro-forma invoice reflecting the exchange rate in PO
-Invoice is received from supplier week later
-Create Purchase Invoice and either set / use auto added exchange rate at that time - updating the exchange rate alters the currency converted total for the entire Purchase Invoice

Issue is seen when exchange rate changes and causes the currency converted total to be calculated on the new exchange rate for entire order and not just the final payment. Further payments may also be made reflecting different exchange rates.

**Scenario C: Full payment made based on Terms of Supplier invoice**

PO is raised to supplier with exchange rate auto populated
Invoice is received from supplier
Create Purchase Invoice and either set / use auto added exchange rate at that time
Make payment per terms i.e. 7 days later - exchange rate is different and would need to amend the Purchase Invoice to adjust

Issue is only way to alter exchange rate is to amend the Purchase Invoice - although works there maybe records affiliated which restrict the ability to amend. 

**Screenshots show the effect of Scenario B**

Initial payment made against PO

![1 - initial payment made to purchase order](https://cloud.githubusercontent.com/assets/22227933/20549018/9b3e63ca-b17c-11e6-9a52-a850a51fca00.png)

Final payment made against PINV

![2 - final payment made to purchase invoice](https://cloud.githubusercontent.com/assets/22227933/20549019/a0a919cc-b17c-11e6-83b5-381a88f01029.png)

Feedback if this is incorrect or should be altered?

**Comment by umairsy** [comment]
Answered from https://discuss.erpnext.com/t/exchange-rate-issue-on-payment/17990/3?u=umair
