### ISSUE TITLE
Print Format Bug: Unable to use more than 1 Custom HTML

### ISSUE THREAD

**Issue by addymuliady** [frappe/erpnext#7041]
Hi,

The Custom HTML in Print Format is broken.

This is what it looks like on the surface:
![scs sales order](https://cloud.githubusercontent.com/assets/21187126/20550483/035dd9b0-b171-11e6-8ebd-ac349c91d4f2.JPG)

But when you click on Edit HTML:
![scs_2](https://cloud.githubusercontent.com/assets/21187126/20550527/7ba2dc04-b171-11e6-98df-9dfce959a92f.JPG)
(which is a repeat of another Custom HTML and this is showing to all Custom HTML)

Kindly look into this urgently.

Thanks!

**Comment by DevenK** [comment]
I can confirm that I'm seeing the same issue.

**Comment by rmehta** [comment]
This is already fixed. Please update your bench.

**Comment by addymuliady** [comment]
Hi thank you!
