### ISSUE TITLE
Localize don't work 

### ISSUE THREAD

**Issue by kickapoo** [frappe/erpnext#7046]
On a production machine with Multitenant setup: 

Server date: 
![screenshot 2016-11-23 10 23 49](https://cloud.githubusercontent.com/assets/5064612/20554845/2e254dfe-b167-11e6-9ec9-0c0c7e4a1374.png)

Adding a comment `now()` on a site: 
![screenshot 2016-11-23 10 23 25](https://cloud.githubusercontent.com/assets/5064612/20554851/3738a3f0-b167-11e6-8ba1-c7c6e240931d.png)

**in 4 hours** <-------- WRONG

On console: 
```
  frappe.utils.now()
```
'2016-11-23 14:06:25.829962'

site settings on database: 
![screenshot 2016-11-23 10 35 23](https://cloud.githubusercontent.com/assets/5064612/20555105/c88bc94e-b168-11e6-9b35-d583b50a3d2e.png)

Please give a feedback on debugging it or how to reload the localize for a current site.

**Comment by rmehta** [comment]
You will have to set the timezone in your user account.

The system is designed to show times based on the System / User timezone and not browser. This is the design.

Do you have another suggestion?
