### ISSUE TITLE
"Close" button for Mutliple PO Selection

### ISSUE THREAD

**Issue by Devens** [frappe/erpnext#7053]
Please see following screenshot. Close button for multiple PO is available in List View. But, it is not available from PO report view. 

Since, in List View, only few columns are available, it's very difficult to select POs to close it. Whereas in Report view (as shown below), it is easy to select the PO to be closed. But, "Close" button is not available. 

![untitled_clipping_112316_085118_pm](https://cloud.githubusercontent.com/assets/10671911/20567400/89711d08-b1be-11e6-818c-aa865ea3e939.jpg)

![untitled_clipping_112316_085304_pm](https://cloud.githubusercontent.com/assets/10671911/20567462/cc7af7c2-b1be-11e6-8c1f-26bcb166ae01.jpg)

**Comment by rmehta** [comment]
- [ ] Execute 'onload' list view in report view too
- [ ] make sure wiring works (fix any broken wiring if required)

**Comment by rohitwaghchaure** [comment]
https://github.com/frappe/frappe/pull/2452
