### ISSUE TITLE
Currency Exchange Rate entry when entering PI with home currency

### ISSUE THREAD

**Issue by Albatros79** [frappe/erpnext#7055]
Hello,
we are a distributor company,
our products price list is in EUR
but manufacturer is sending us invoices in our home currency TRY calculated basis official rates issued by the goverment. 
so I made a Standart Buying List with EUR and using it for Purchase invoices,

when i want to enter an PI in my home country , in "Currency and Price List" field ; if i choose home currency , exchange rate field not shown and when i enter the products unit cost is being calculated according to its own exchange rate. but in Turkey we have to use goverments exchange rates on invoice date.  
i tried all options to see exchange rate in fom customization  but i could not achieve to do it.
can you help me on that. 
also although i set Float Precision to 6 i can only see 2 decimals in PI. as far as i saw in the forum ,this should have been fixed already. am i doing something wrong?
thanks beforehand
best Regards,

**Comment by kennethsequeira** [comment]
Exchange rate can be edited at the Purchase Invoice level
