### ISSUE TITLE
Cannot send email , but ERPNext can send daily reminders

### ISSUE THREAD

**Issue by Albatros79** [frappe/erpnext#7056]
Hello ,

I Cannot send email , but ERPNext can send daily reminders
i have received ERPNext's automatically generated emails.
but when i entered an email adress for example for sending a quotation. it is not being received.
also i cannot use images in signatures? 
could you help?
thanks and best Regards,

**Comment by Albatros79** [comment]
i saw this message in error log

frappe.email.queue.flush

Error	

(551, 'Sender address is not valid for your login. Check your email program settings.', u'Administrator <admin@example.com>')
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/queue.py", line 306, in send_one
    smtpserver.sess.sendmail(email.sender, email.recipient, encode(email.message))
  File "/usr/lib/python2.7/smtplib.py", line 736, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
SMTPSenderRefused: (551, 'Sender address is not valid for your login. Check your email program settings.', u'Administrator <admin@example.com>')

**Comment by yashodhank** [comment]
@Albatros79 As error suggest, you cant use same email account with other non-existing or existing email account with same provider as provider does not allow you to spoof email account.

For example, if you have info@yourdomain.ext and helpdesk@yourdomain.ext as two different mail accounts then while adding one of them to ERPNext, even if you enable to **Login Id is Different**, service providers mail server does not respect that as It must be restricted by default. Hence it has nothing to do with ERPNext not being able to send or receive your messages.
