### ISSUE TITLE
freeze while saving new doctype

### ISSUE THREAD

**Issue by cgpurbaugh** [frappe/erpnext#7057]
This has happened a few times to me, on a couple doctypes. 

ERPNext V 7.1.14

![image](https://cloud.githubusercontent.com/assets/13136405/20583765/c6d0c418-b1ba-11e6-825c-31502f831fa1.png)

**Comment by rmehta** [comment]
Try increasing your Redis size to 10% of your RAM.

Also pull the latest, this has been resolved.
