### ISSUE TITLE
Sales Order - Time Field - Calendar

### ISSUE THREAD

**Issue by Bow-N** [frappe/erpnext#7058]
How can I edit a Sales Order Form to include a Date so that they appear on the calendar. I tried changing the transaction date and delivery date field to be datetime but I get an error saying you cannot do this

**Comment by rmehta** [comment]
Already appears on basis of delivery date

<img width="1008" alt="screen shot 2016-12-15 at 3 59 26 pm" src="https://cloud.githubusercontent.com/assets/140076/21220573/85416706-c2df-11e6-9e26-ef5f952d0d23.png">
