### ISSUE TITLE
General Ledger report - enhancement 

### ISSUE THREAD

**Issue by Priyanka-IAS** [frappe/erpnext#7059]
Hi,

Our Customers ask for a ledger very often for a certain time period. We usually use the “General Ledger” for the customer but I feel it could do with the following enhancements:

1. Give separate column with actual Transaction date (not posting date)
2. Separate column for Bank Reference
3. Separate column for Total amount received. We usually get combined payments for a few invoices at a time. Total amount received is not clearly visible in this report. - IMPORTANT

Essentially, whenever a customer doesn’t agree with the numbers on “Accounts receivable “ report, they want to see a ledger to reconcile entries with their accounts. Without the data mentioned above, the report cannot be of any use to them.

Regards,

Priyanka

**Comment by SonaliBudhrani** [comment]
+1

**Comment by ai-erp** [comment]
@Priyanka-IAS is right, I think there should be a portion to add Receipt/Voucher date in making payment or Journal Entry for this transaction date to be added in the GL report. Below should be the format in the Payment/Journal entry. This transaction date will show when exactly the transaction happened and posting date will be the date when the transaction should be reflected in the Financial Statement. 

![transaction date](https://cloud.githubusercontent.com/assets/16744099/26204040/94bf3b4e-3bee-11e7-8d30-ae1eb475955a.jpg)

**Comment by kennethsequeira** [comment]
The GL report can be customized to add new columns from any reference document such as Invoice, payment entry, etc.

As long as a field exists in these documents, they can be added to the GL using **Add Column** button (generic feature for all the reports). This report can be saved as a new one.

**Comment by gpRabie** [comment]
Hi! Is there a way to make the added columns in GL permanent?

**Comment by gpRabie** [comment]
> The GL report can be customized to add new columns from any reference document such as Invoice, payment entry, etc.
> 
> As long as a field exists in these documents, they can be added to the GL using **Add Column** button (generic feature for all the reports). This report can be saved as a new one.



> The GL report can be customized to add new columns from any reference document such as Invoice, payment entry, etc.
> 
> As long as a field exists in these documents, they can be added to the GL using **Add Column** button (generic feature for all the reports). This report can be saved as a new one.

Hi! Is there a way to make the added columns in GL permanent?

**Comment by kennethsequeira** [comment]
@gpRabie Adding the column via the UI and saving the report as a new one should work. This will be adding on top of your GL report. You can always keep on making changes to this report rather going back to standard GL report.
