### ISSUE TITLE
Not able to setup ERP Next with Gmail Account

### ISSUE THREAD

**Issue by mayank13** [frappe/erpnext#7065]
Getting the following error when trying to configure Mail with Gmail:
Cannot connect: [ALERT] Please log in via your web browser: https://support.google.com/mail/accounts/answer/78754 (Failure)

Have enabled allow access to low secure apps also.

**Comment by yashodhank** [comment]
@mayank13 Please google before asking questions, this is not a support channel.
Use user forum for questions and queries. Be patient for answers. If you can not afford to wait hire a freelancer to get job done.


You have to unblock your server IP address, open following URL on server from where ERPNext is trying to connect to gmail to fetching/sending mails.

Solution: https://support.google.com/accounts/answer/2461835?hl=en

Use Application Password or Simply Enable access to less secured apps from Google Apps management consol.

**Comment by mayank13** [comment]
The solution you have mentioned is no longer valid and it is an issue which anyone who is trying to configure Gmail with ERP next would be facing.

**Comment by yashodhank** [comment]
@mayank13 Unfortunately your assumption is not correct. I have tested it on my own production setup without any issue or errors.
If you still believe it is an issue open new topic and follow up at forum for more inputs from community.

![image](https://cloud.githubusercontent.com/assets/1083792/20619970/34041798-b31d-11e6-8f3f-00658c39fc70.png)


**Installed Apps**
ERPNext: v7.1.19
Frappe Framework: v7.1.19
