### ISSUE TITLE
Item Report - filtering by Default Warehouse not possible

### ISSUE THREAD

**Issue by Tropicalrambler** [frappe/erpnext#7067]
I assembled an item report, filtering first by ID LIKE %[id string]%.  It worked fine.
Next I added a filter "By **Default Warehouse** like "  the filter command entry bar changes , and the field for entering the arguments disappear.

Filter working OK
![screen shot 2016-11-24 at 10 49 02 am](https://cloud.githubusercontent.com/assets/16600935/20606007/e8902a7a-b233-11e6-87ef-217bcd077aa2.png)

As soon as the selection is made for "Default Warehouse", the box where the argument for the filter is to be entered, dissappears.  The **Purple check button** and **remove** commands shift to the left, and no field is available to enter the arguments for the filter.

Filter **not **working****
![screen shot 2016-11-24 at 10 49 36 am](https://cloud.githubusercontent.com/assets/16600935/20606023/fd6f8b34-b233-11e6-9688-4096cee9c417.png)

**Comment by Tropicalrambler** [comment]
Thanks!

**Comment by rmehta** [comment]
Works fine for me!
