### ISSUE TITLE
Incorrect POS Quantity 

### ISSUE THREAD

**Issue by vjFaLk** [frappe/erpnext#7075]
ERPNext: v7.1.19
Frappe Framework: v7.1.15
No errors in console

Quantity shows up normally when first item is selected
![image](https://cloud.githubusercontent.com/assets/6697133/20640880/810e3e48-b411-11e6-8e05-22cb34376be9.png)

On selecting an item with a different quantity, all the items get the quantity of the new item
![image](https://cloud.githubusercontent.com/assets/6697133/20640883/893248da-b411-11e6-9eba-3797683efba2.png)

This happens for following items added to the list
![image](https://cloud.githubusercontent.com/assets/6697133/20640896/c8dba4b8-b411-11e6-978b-3b06d45da211.png)

**Comment by rohitwaghchaure** [comment]
Hi @vjFaLk 
Thanks for reporting an issue, have fixed the issue and soon we'll release the fix
