### ISSUE TITLE
Attendance Tool not working right with bulck no. of employees

### ISSUE THREAD

**Issue by hfaridgit** [frappe/erpnext#7078]
I have more than 1500 employees and tried to do attendance from Attendance tool for all selected but doesn't work, while when choosing 10 0r 20 employees it works.

**Comment by yashodhank** [comment]
@hfaridgit you should alway google before asking questions as it might have been addressed already somewhere. This is not right place to ask questions for that we have https://discuss.erpnext.com

Data Import tool have known limitation of 1000 records, if you are processing large data sets split in to two or three batches while importing or as you might know ERPNext support RESTful API, using that with another script (built in your prefered language) will allow you to process & handle even larger amount of data and that is prefered method when dataset is large.

**Read more about limit in User Manual:**
https://frappe.github.io/erpnext/user/manual/en/setting-up/data/data-import-tool

If and only if, you find bug/glitch while using software, then only report it here, (maybe after confirming on https://discuss.erpnext.com if not sure about it) with steps to reproduce it & some details about your setup and software versions.
