### ISSUE TITLE
Creating new Leave from within a custom python function doesn't work

### ISSUE THREAD

**Issue by hfaridgit** [frappe/erpnext#7079]
I tried the following code in my custom python in Frappe:
But it doen't create the leave application record **Why ???**

@frappe.whitelist()
def set_shift_time(shift_date=None, shift_start=None, shift_end=None, company=None):
		la = frappe.new_doc('Leave Application')
		la.company = company
		la.employee = '21111'
		la.employee_name = '21111 name'
		la.naming_series = 'LAP/'
		la.leave_type = 'Casual Leave'
		la.posting_date = shift_date
		la.from_date = shift_date
		la.to_date = shift_date
		la.status = 'Approved'
		la.insert()
		la.submit()

**Comment by nabinhait** [comment]
You need to commit at the end, use `frappe.db.commit()`
