### ISSUE TITLE
Map client roles with ERPNext roles

### ISSUE THREAD

**Issue by pgarodia** [frappe/erpnext#7089]
Hi,

I have a client from the fashion industry. They have roles like Merchandiser, Quality Assurance, Team Lead, etc. I am currently storing these in designation field. I have two requirements from the system. 

1. Some people play multiple roles. How do I store them in ERPNext?
2. Is there a way to map ERPNext roles with client roles? This way when I add a new person and assign him a client role, the ERPNext roles are automatically assigned to that person. This will also be valid in scenarios where roles are changing due to lateral or vertical promotions. 

Thanks,
Prateek

**Comment by strixaluco** [comment]
Please post questions to the forum: [discuss.erpnext.com](https://discuss.erpnext.com)
