### ISSUE TITLE
Recording capacity of suppliers' workstations

### ISSUE THREAD

**Issue by pgarodia** [frappe/erpnext#7090]
Hi,

From what I understand the current implementation of ERPNext allows us to track capacity in our own manufacturing facilities. Can we do the same in case of a supplier? This is assuming the supplier agrees to share their data honestly.

**Comment by rmehta** [comment]
You can do it as a custom field. It would not make sense to do it unless you are tracking inventory at the supplier's end and consistently updating the value.
