### ISSUE TITLE
Enhancement: Budget distribution periods, add Weekly Distribution!

### ISSUE THREAD

**Issue by Tropicalrambler** [frappe/erpnext#7095]
The monthly distribution function in budgeting is fantastic!

Our business operates on a Weekly period, since we have a weekly meeting to track progress.  For a startup or aggressively growing company, this rhythm helps the startup pivot accordingly, and it helps to adjust efforts every week.

It would be fantastic to enable a **Weekly distribution**, pre-defining the dates, and setting up the ISO week numbers as per ISO 8601.
[https://en.wikipedia.org/wiki/ISO_week_date](https://en.wikipedia.org/wiki/ISO_week_date)

**Comment by Tropicalrambler** [comment]
Bumped back into this issue while working on Budgets.  The distribution currently supports monthly only, however for Agriculture and other domains Weekly is more precise, and can be more powerful and useful. Will code this myself as soon as we are done with AgriNext

**Comment by parsimonyERP** [comment]
👍 Not just Agriculture, Retail too! (... and if it comes up, we like Monday to Sunday weeks!)

**Comment by harshit-30** [comment]
Hi @Tropicalrambler, let me know if you'd still like to contribute to this feature.

**Comment by remigius974** [comment]
would be much appreciated if this feature is implemented

**Comment by remigius974** [comment]
weekly distribution for sales targets
