### ISSUE TITLE
Enhancement: Budget Variance Report budget Actual vs. Budgeted graphs

### ISSUE THREAD

**Issue by Tropicalrambler** [frappe/erpnext#7096]
**Budget Variance Report** should have the following:
For each Line item in the report, one additional column per period displaying a "completion graph"
The idea is to have a simple "progress bar"  where a bounding empty rectangle is filled proportionatelly from left to right as the budget is executed. The rectangle color is one color.  The fill color is another color, so that if the actual amount "exceeds" the budgeted amount, the bar can clearly continue filling the rectangular space allocated to the "progress bar", but where the encasing rectangle representing the budgeted amount, makes itself smaller to represent budget being exceeded.

Similar to a combination of Number 1 graph (horizontal) and number 3 "Thermo" on this website:
[http://www.criticaltosuccess.com/5-top-budget-vs-actual-excel-charts-you-need/](http://www.criticaltosuccess.com/5-top-budget-vs-actual-excel-charts-you-need/)
Ideally the "Icons" column should be included in the same BOX to show a GREEN-YELLOW-RED icon beside the recantgular progress bar. From green to red for expense root accounts, and from red to green for income root accounts.  It could also be just the color of the progress bar fill, changing color to reflect progress accordingly.
Also a percentage amount inside the "progress bar" would be helpful.

**Comment by harshit-30** [comment]
Is this not possible using Report Builder?

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.
