### ISSUE TITLE
[bug] Supplier billing and unpaid not updating

### ISSUE THREAD

**Issue by sp9leo** [frappe/erpnext#7116]
I noticed that total billing and amound unpaid fields are not updating on a certain supplier. I suspect the problem is that suppliers name contains letter "ž". I tried changing both `name `

and `supplier_name`, and made another purchase invoice. That worked. If `name `doesn't contain that letter and `supplier_name `does error is still present.

Another thing probably related to this is open notification about supplier. Even if all transactions are completed and no supplier shows "open" status in list.

![image](https://cloud.githubusercontent.com/assets/15377465/20791924/9c046d10-b7bf-11e6-99eb-09936d1b32c5.png)

**Comment by rmehta** [comment]
The notifications work with a lag. Are you sure you can replicate this issue?

**Comment by sp9leo** [comment]
Found a problem. Purchase invoice was marked as "is paid". 
With that option unchecked everything working correctly. 
I will close issue now. Feel free to reopen it if this actually IS an issue.
Thank you
