### ISSUE TITLE
Update error: No module named psutil

### ISSUE THREAD

**Issue by noetico** [frappe/erpnext#7117]
Need some insight on this update error; after running git fetch and pull on bench-repo and frappe, erpnext folders; on updating it fails immediately with the following import error: no module named psutil> What needs to be done? Anyone facing this issue?

**Comment by shreyasp** [comment]
@noetico You need to run `sudo pip install psutil` and then run `bench update`. A new module named `psutil` has been added to bench because of which the update fails.

**Comment by noetico** [comment]
Thanks! I'll be sure to use this the next time; for now; I commented out the parts of the file that referenced psutil. Not a very good route; but I needed to upgrade urgently; all went well though.

Thanks again.

Kent@Live Mail
From: Shreyas Patil
Sent: Thursday, December 1, 2016 18:23
To: frappe/erpnext
Reply To: frappe/erpnext
Cc: Kent; Mention
Subject: Re: [frappe/erpnext] Update error: No module named psutil (#7117)



@noetico<https://github.com/noetico> You need to run sudo pip install psutil and then run bench update. A new module named psutil has been added to bench because of which the update fails.

-
