### ISSUE TITLE
Salary Component

### ISSUE THREAD

**Issue by vishdha** [frappe/erpnext#7121]
Depends on Leave Without Pay  set = 1 .
When I add earnings in earnings table salary component value get set to 0.00.
Earlier whenever I click on Depends on Leave Without Pay, the default amount field has occurred. but, now it does not change.

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/6947417/20825114/f9fdba2a-b887-11e6-902e-57542dd1cc4f.gif)

**Comment by KanchanChauhan** [comment]
Fixed via https://github.com/frappe/erpnext/pull/7127
