### ISSUE TITLE
New custom Sales Order report doesn't show in report list

### ISSUE THREAD

**Issue by monojoker** [frappe/erpnext#7122]
Hey Guys,

Small issue I have found - when you make a new report using Report Builder it doesn't seem to show in the Reports list for that doctype. See here for the report:

![image](https://cloud.githubusercontent.com/assets/10917366/20825419/a7ace1a6-b8af-11e6-9599-eabb7c7bb32c.png)

And then when I look in reports in the Sales Order screen it doesn't show:

![image](https://cloud.githubusercontent.com/assets/10917366/20825426/c4861978-b8af-11e6-9c24-b607279bc0f7.png)

I tried a Reload but still doesn't show. All my other reports for Selling show in that dropdown list.

Thanks

**Comment by KanchanChauhan** [comment]
Tried to replicate but it worked fine for me. See screenshots.
My reports appear under Custom reports.
<img width="992" alt="screen shot 2016-12-05 at 5 28 43 pm" src="https://cloud.githubusercontent.com/assets/16913064/20884316/9197a2ee-bb10-11e6-9a11-d364a0f76fe1.png">

And also in dropdown.
<img width="328" alt="screen shot 2016-12-05 at 5 29 40 pm" src="https://cloud.githubusercontent.com/assets/16913064/20884315/8fbdf7a2-bb10-11e6-9d2a-5fa0b4e4e0de.png">
