### ISSUE TITLE
LDAP login for Customers and company Users

### ISSUE THREAD

**Issue by blackyzero** [frappe/erpnext#7124]
By now, i'd like to know how to login as ldap users, cause i don't see the field for login as ldap at login page? other saying, how could i import existing LDAP users into ERPNext?

In addition, i have another question, is that possible to add a specific LDAP setting for website users as customer users?
ex: i have two LDAP OU
ou=users,dc=company,dc=com
ou=customers,dc=company,dc=com

For employee login, LDAP will only allow from "ou=users", and for customer login or website login, only "ou=customers" is allowed.

Thanks in advanced.

**Comment by blackyzero** [comment]
would be great if this feature is considered to add into next release.
thanks a lot.

**Comment by revant** [comment]
To enable LDAP login enter the "LDAP Settings" as already logged in system user. Search for LDAP Settings in awesome bar 

Once logged in first time, as any web sign-up user the access will be restricted as a "website user"/customer. I.e anyone who logs in first time using LDAP will be website user

System manager has to assign roles to the new user to allow desk access.

**Comment by strixaluco** [comment]
Please post questions to [discuss.erpnext.com](https://discuss.erpnext.com)
