### ISSUE TITLE
Unexpected menu appears for user

### ISSUE THREAD

**Issue by blackyzero** [frappe/erpnext#7125]
Dear team,

i have a user, with very limited permission, only checked on "CRM" module.
however, when that user loggin, he can see other menus which are not expected to see, such as "Tools", "Human Resources", "Manufacturing"
Please refer attached screenshots for more detail.

I am running below version,
frappe@pink:~/frappe-bench$ bench version
erpnext 7.1.20
frappe 7.1.21
frappe@pink:~/frappe-bench$ 

Could you please advise how to fix it? is it a bug of existing version?
Thank you.

![screen shot 2016-12-02 at 3 28 43 pm](https://cloud.githubusercontent.com/assets/4286063/20827409/57c72d64-b8a4-11e6-8360-87948375eb87.png)
![screen shot 2016-12-02 at 3 28 36 pm](https://cloud.githubusercontent.com/assets/4286063/20827408/57c66b18-b8a4-11e6-8b65-cf16f869b532.png)
<img width="831" alt="screen shot 2016-12-02 at 3 28 32 pm" src="https://cloud.githubusercontent.com/assets/4286063/20827410/57c79e48-b8a4-11e6-8df8-1499b1df86bb.png">

**Comment by rmehta** [comment]
Those checks are only for desktop modules, the list in "Explore" is based on user permissions. That is the design.

Closing this issue for now.
