### ISSUE TITLE
Print Format / Custom Format not working when print format is edited with the print format builder

### ISSUE THREAD

**Issue by paulator** [frappe/erpnext#7133]
When I create a custom format with the format module with a new print format entry, I'm able to see my custom designed print layout.

When I change something in the print format builder (graphical tool), then my custom design is not shown anymore and I can only see the format from the print format builder.

**Comment by KanchanChauhan** [comment]
I am not able replicate the issue. Please make sure you select the correct print format from dropdown and save your changes when you customize it. If problem still persists please share steps to reproduce it and screenshots as well so that we can replicate it.

**Comment by strixaluco** [comment]
This is a kind of floating issue, can't actually replicate it now, though faced it few days ago. Didn't have a chance to find any regularity, but seems that sometimes it takes longer for the print format to appear in a dropdown list.

**Comment by KanchanChauhan** [comment]
@strixaluco That can be the case, it might take little bit time to appear in dropdown list but it does eventually.

**Comment by strixaluco** [comment]
@KanchanChauhan it can be indeed.
@paulator please check if print format appears a bit later.

**Comment by paulator** [comment]
Here are the steps to reproduce the error:

1. create a new print format
2. make the following settings (html is copied from the bottom of the page)
![image](https://cloud.githubusercontent.com/assets/7262648/20926014/898da22e-bbba-11e6-882b-b2611523cdb7.png)
3. click on save and check the print: 
![image](https://cloud.githubusercontent.com/assets/7262648/20926110/0ef69d44-bbbb-11e6-894b-89886750b001.png)
4. go back to print format settings and click on "edit format" 
5. Change anything in the format editor and save it. (e.g. change position of Customer Name and Offline POS Name) 
6. The printformat shows now the format from the format editor.
![image](https://cloud.githubusercontent.com/assets/7262648/20926294/d5e87c92-bbbb-11e6-976f-7e48e27db4ab.png)

So far so good. 

But now I don't find any way to switch back to the custom HTML format (like shown in point 3). The settings of the custom HTML format are still present. It seems that the format editor overwrites the custom HTML format.

The only workaround for me was to delete the print format and create a new one without touching the format editor.

**Comment by paulator** [comment]
Thanks. Now it's working like expected.
