### ISSUE TITLE
Security Flaw : Apply User Permissions is being ignored for blank field values

### ISSUE THREAD

**Issue by rohitk75** [frappe/erpnext#7137]
Hi

User permission does not work if the Field value is blank. The list shows where user field matches (territory =ERP) and also where Territory is blank. They system should only show where Territory = ERP and not blank ones.

![user permission](https://cloud.githubusercontent.com/assets/7210284/20878476/977d5ef6-bae8-11e6-9b55-c17fd446c580.png)

![user permission is being applied](https://cloud.githubusercontent.com/assets/7210284/20878474/9779a37e-bae8-11e6-80ac-6d07d3ba8a9e.png)

![user permission is being ignored for blank values](https://cloud.githubusercontent.com/assets/7210284/20878475/977add2a-bae8-11e6-864e-dd9323b4a0e0.png)

Regards

Rohit

**Comment by KanchanChauhan** [comment]
This is the default behavior. You will have to uncheck "Ignore User Permissions If Missing" from System Settings so that blank values are not shown.
<img width="1165" alt="screen shot 2016-12-06 at 4 44 00 pm" src="https://cloud.githubusercontent.com/assets/16913064/20923645/719d5542-bbd3-11e6-972b-2c373bcb114c.png">

**Comment by rohitk75** [comment]
Hi

That does not help.  The issue is because territory has null values so they
still turn-up  and the list.

Regards
Rohit

**Comment by KanchanChauhan** [comment]
Does it still shows up after unchecking "Ignore User Permissions If Missing"?

**Comment by rohitk75** [comment]
Yes

**Comment by KanchanChauhan** [comment]
Apologies, I could replicate it now. Will take a look.

**Comment by Olawale1** [comment]
Hi,

Any progress on this yet?

Kind regards,

**Comment by manassolanki** [comment]
Fixed via https://github.com/frappe/frappe/pull/3496

**Comment by manassolanki** [comment]
This feature can be turned on by checking the "Apply Strict User Permission" in the system settings.
