### ISSUE TITLE
“Auto Email Report” - dates needs to be dynamic! 

### ISSUE THREAD

**Issue by VivekC-ICP** [frappe/erpnext#7147]
I am trying to setup an “Auto Email Report” or “Email Digest” with a list of invoices submitted, on a daily basis.

- [ ] Add "Send only records created today"
- [ ] Add "Send only records modified today"
- [ ] Add additional filters based on these check values

**Comment by yashodhank** [comment]
@VivekC-ICP Kindly use https://discuss.erpnext.com for such queries. Only open issue for requesting new feature/enhancements & reporting bugs/issues with ERPNext software. (with appropriate details)

**Comment by VivekC-ICP** [comment]
@yashodhank, Certainly this is a bug/defect or an incomplete feature.  Please see my comment, if the dates are not dynamic then there is no point in having a daily auto email being sent!

**Comment by VivekC-ICP** [comment]
I request you to kindly open this issue and suggest when this will be fixed?

**Comment by rmehta** [comment]
@VivekC-ICP Yes, I agree

- [ ] Add "Send only records created today"
- [ ] Add "Send only records modified today"
- [ ] Add additional filters based on these check values

**Comment by VivekC-ICP** [comment]
Great! Thank you Rushabh!

**Comment by superlack** [comment]
Has there been any update on this?  I was trying to use Auto email report for "General Ledger" and "Daily Timesheet Summary" but it seems like without dynamic dates, nothing will work as intended

**Comment by VivekC-ICP** [comment]
Yes still waiting for this feature

**Comment by Devens** [comment]
+1

**Comment by Olawale1** [comment]
Interesting! I just came across this issue and it's very similar to the one I posted here:

https://github.com/frappe/erpnext/issues/7460

The difference however is that I propose the feature should be added to the Date Filters specifically. This way, it will work in Reports, List Views, and of course in the Auto Email Report feature

Regards

**Comment by mukeshmv1** [comment]
+1

**Comment by strixaluco** [comment]
This issue looks more specific, than #7460. Should we close current one in favor of #7460?

**Comment by tundebabzy** [comment]
I think #7460 addresses this use case and more. @VivekC-ICP please follow progress on this on #7460
