### ISSUE TITLE
Cannot set child table's value after v7.1 update

### ISSUE THREAD

**Issue by jof2jc** [frappe/erpnext#7148]
Before v7.1 the script did work, but affter v7.1 update..it's not working
```
frappe.ui.form.on("Stock Entry Detail", "item_code", function(frm, cdt, cdn) {
    var d = locals[cdt][cdn];
    
    if (frm.doc.purpose == "Material Receipt"){
	if (frm.doc.company == "Toko GBU"){
		//d.expense_account = "Capital Stock - tk";
   		frappe.model.set_value(d.doctype, d.name, "expense_account", "Capital Stock - tk");
		
	}
	else{
		d.expense_account = "Capital Stock - pt";
	}

    }
  //msgprint(d.expense_account);
});
```

**Comment by KanchanChauhan** [comment]
Script looks fine, what is it complaining about?

**Comment by jof2jc** [comment]
if you test above script in Stock Entry, then expense account is always overridden by Stock Adjustment account.. I want to set another default account if users do MaterialReceipt transaction

**Comment by strixaluco** [comment]
Is this still valid?

**Comment by mbauskar** [comment]
@jof2jc,

It is not a bug, Your script works perfectly fine, the custom script is setting a value to expense account as `Capital Stock - pt` then system fetches the item details from the item master and sets the expense account defined in selected item.

please check https://github.com/frappe/erpnext/blob/develop/erpnext/stock/doctype/stock_entry/stock_entry.js#L157.

**Comment by jof2jc** [comment]
@mbauskar so custom script is not priority here...how to override it?

**Comment by mbauskar** [comment]
@jof2jc you can set the value on validate trigger instead of item_code trigger
