### ISSUE TITLE
Next / Previous option to navigate from one Document to another

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#7151]
- [ ] UI for previous next
- [ ] Pick previous / next item from list view
  - [ ] If listview not created, create it
  - [ ] If paging is required, set it up

---

As requested by Muqthar:

We should have a way to navigate the documents one by one to next from its page itself. For example QTN#1 to QTN#2,QTN#3 and so on. Right now, overtime we have to go back to quotation list again and select the next one.

**Comment by Devens** [comment]
It will be very useful and much time-saving. +1

**Comment by vladucoju** [comment]
Maybe something like this

![untitled](https://cloud.githubusercontent.com/assets/9590909/20927732/30220fd2-bbc3-11e6-8112-f5d6714e646d.png)

Next - Previous
First - last
Cancel
Search

**Comment by strixaluco** [comment]
That would be really great.

**Comment by mhbu50** [comment]
This is nice feature

**Comment by rmehta** [comment]
If you are on a filtered list, the user will expect to go to the next filtered item as per the list view

**Comment by vladucoju** [comment]
Yes, that option too. I must suggest better filter options. i think it is more intuitive to be  in POP UP window. I will suggest to change sort type field in search by to be select field (ID, Customer,...), and on the right side search field like it is now. When user choose sort type to get the same by default when next time start to search. I will make some mock up later

**Comment by asbasawaraj** [comment]
+1

**Comment by joolsr** [comment]
This is especially true for the Email Inbox feature. It feels awkward to go, email to Communications list and back to next email.

**Comment by somicoito** [comment]
Really really useful

**Comment by bghayad** [comment]
Useful and important, it gives more power for ERPNext in manipulating the data.

**Comment by kennethsequeira** [comment]
Added: https://github.com/frappe/frappe/pull/7777
