### ISSUE TITLE
Suggestion: Account Payable Report - Toggle Button for Summary

### ISSUE THREAD

**Issue by Devens** [frappe/erpnext#7159]
If we need to check the summary of Account Payable from "Account payable" report, we need to come out of that report and then open the summary report. We suggest to have one toggle button for "Summary" and "Details" as shown below. In that case there will not be need of two separate reports. 

![untitled_clipping_120716_073108_pm](https://cloud.githubusercontent.com/assets/10671911/20970516/f3ae2be8-bcb3-11e6-98b6-ff1365de9191.jpg)

**Comment by rmehta** [comment]
It would be easy to add a link!

**Comment by Devens** [comment]
Ok... That's fine if links added in both reports vice-versa.
