### ISSUE TITLE
Get Sales Orders Button in Production Planning Tool doesnt appear to be working

### ISSUE THREAD

**Issue by rest1** [frappe/erpnext#7168]
Hi All, 

The Get Sales Orders Button (Pull sales orders (pending to deliver) based on the above criteria) in Production Planning Tool doesnt appear to be working.

No error message.

**Comment by rohitwaghchaure** [comment]
Hi @rest1 
Get sales orders button is working properly please check below GIF
![production_planning_tool](https://cloud.githubusercontent.com/assets/8780500/21039911/655b1e00-be07-11e6-9133-916f0d99edf7.gif)

**Comment by rest1** [comment]
Hi, 
I'm still having the same issue, I'm doing the same as in the GiF screen capture, but doesn't display any results.

Also what fields are mandatory to bring results, can you just no have the dates as mandatory fields.


Thanks
