### ISSUE TITLE
Automate Employee creation with User creation or vice versa

### ISSUE THREAD

**Issue by pgarodia** [frappe/erpnext#7173]
Currently users and employees need to be created separately in the system even when they are the same person. Please allow employee creation with user creation or vice versa so that the work is not duplicated. This will also negate the requirement to have duplicate fields like birth dates, phone, etc. from both screens.

**Comment by KanchanChauhan** [comment]
All users are not necessarily Employees, Employees are always users though. User can be Project User or Blogger or Lead.

**Comment by pgarodia** [comment]
Understood. Maybe this can be automated for at least all users with role of
employees?

**Comment by rmehta** [comment]
Make a "Create User" button in Employee if `user_id` is not set

**Comment by pgarodia** [comment]
Hi Nabin,

Thanks a lot. When will the fix appear in my instance?

Regards,
Prateek
