### ISSUE TITLE
Easier Opening Stock Entry for Serialized Items

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#7176]
It is currently very difficult creating opening stock entries for serialized items in ERPNext especially when you have a large number of different items. Currently, the only way is to enter each item in a new line and enter the corresponding serials... this is too cumbersome even for a business that only has a few items talk less of those with hundreds or more! The Stock Entry import template is a no-go area as it is even more cumbersome and time-consuming than using the front end

I believe the most ideal and user-friendly way would be to have a tool that can just import all the unique serial numbers at once. The Warehouse and Incoming Rate fields can be used to update the Stock and Accounting Ledgers

The template for importing Serial Numbers (via the Data Import Tool) already contains all the relevant fields like Item Code, Company, Warehouse, Incoming Rate etc. There's however a restriction that warehouse for new serial numbers can only be set from Stock Entry or Purchase Receipt. I'm also not sure that relevant ledgers will be updated via the current Data Import Tool 

Please help look into this as soon as possible. It'll go a long way in improving the on-boarding process

Thanks

**Comment by rmehta** [comment]
- [ ] In Stock Entry, add a button for "Add Serial No", in dialog ask user to paste a list of Serial Nos
- [ ] Create an item entry for each Serial No

User can make this entry against Temp Opening account.

**Comment by Olawale1** [comment]
Hi Rushabh,

Item Code, Quantity, and UoM are mandatory in Stock Entry! How do you manage that?

**Comment by rmehta** [comment]
You select the number of serial nos in to import as qty, then paste the serial nos in the text column. Seems simple?

**Comment by Olawale1** [comment]
Hi Rushabh, 

I've tried this already. It doesn't work without Item Code and UoM (and Conversion Factor) as I mentioned earlier. The workflow is fine but it doesn't work in the current implementation of ERPNext due to the restrictions I've mentioned

**Comment by rmehta** [comment]
Yes you will have to add the Serial Nos item-wise.

**Comment by Olawale1** [comment]
...But that is the exact problem we are trying to resolve! Imagine having to do that for 2000 items!!

**Comment by Olawale1** [comment]
Hi @rmehta 

Trust you're doing great. I would suggest the following:

1. Create a new Stock Entry of type 'Opening Stock'
2. When this type of Stock Entry is selected, 'Item Code', 'UoM' etc are pulled from the serial number masters

This way, it becomes possible to upload Serial Numbers and then use a Stock Entry to set warehouse (by pasting all serial nos in one row) as you earlier suggested

This will be an extremely significant improvement in the on-boarding process. Any retail business that deals in serialized items will benefit from this immensely especially if they're migrating to ERPNext from another system. Updating opening stock by entering serials for each item on a new row is practically impossible if you have hundreds (or even thousands) of different items. With this approach however, it can be done in a day!

Thanks

**Comment by Olawale1** [comment]
Hi @rmehta 

I just revisited the Data Import Tool recently and discovered it actually takes care of this decently enough. It would however be generally helpful to increase the capacity of the upload function so that more rows can be handled efficiently in one go. Large numbers of records need to be broken down into several parts for uploading

I'm closing this now. Thanks for the great work you're doing

Kind regards,
