### ISSUE TITLE
Suggestion: Be able to enter customer Purchase Order number into POS screen

### ISSUE THREAD

**Issue by graphskill** [frappe/erpnext#7177]
Suggestion: Be able to enter customer Purchase Order number into POS screen. This will make it easier to track down invoices later

**Comment by rmehta** [comment]
Is that a need in retail? Most customers don't walk in with a purchase order.

**Comment by graphskill** [comment]
In the DIY kind of trade yes. Perhaps the kind of place where a plumber will pop in to get his supplies and give a purchase order number to be billed later, or a normal customer will come in and pay by cash. The person at the till needs to be able to record both "sales". That way they don't need to worry about working the main system, just the POS
