### ISSUE TITLE
Forward with masking

### ISSUE THREAD

**Issue by DaveRye** [frappe/erpnext#7179]
Right now if you type our published URL: www.exxonlighting.com into a browser it forwards to https://exxonlighting.erpnext.com WITHOUT masking, so that URL shows in the browser. We want forwarding WITH masking so that www.exxonlighting.com shows in the browser and the user never sees https://exxonlighting.erpnext.com

Please can you fix this? Thanks.

Dave Rye
Sr. VP, Exxon Lighting Corp.

**Comment by yashodhank** [comment]
@DaveRye usually this is provided by your domain registrar when you do domain forwarding, you enable URL masking option to make it completely transparent.

Your current registrar also supports it follow: https://godaddy.com/help/manually-forwarding-or-masking-your-domain-name-422
