### ISSUE TITLE
Sales Invoice - is Pos - commission gone

### ISSUE THREAD

**Issue by chanlung** [frappe/erpnext#7182]
I'm trying to create a sales invoice that is from a POS. I would like to pay commission to the person who made the sale. Unfortunately, the commission sections is removed when I click on "is Pos".

Many shops sell by commission with their store employee(along with a salary) as an incentive to sell their products. Otherwise you have many shop employee who will just sit there and do nothing. This is a very common practice in North America. The cashier usually asks the questions, "was there someone who helped you today?". And that person is entered into the system.

Please leave the commission section when "is Pos" is selected.

**Comment by rmehta** [comment]
@shachiTakalkar can you confirm if this is the case, AFAIK there is no relation between is pos and commission

**Comment by bhupennewalkar1337** [comment]
@chanlung  I think if you want to give incentive to your employee; there is field "sales team" where you can select your sales person and can give incentive in percentage. 
Commission field includes sales partner not sales team.

**Comment by Arundhatii** [comment]
@chanlung is this still relevant? Feel free to re-open if you think its important.
