### ISSUE TITLE
Improvement to Sales Analysis

### ISSUE THREAD

**Issue by graphskill** [frappe/erpnext#7186]
Improve the sales analysis report so we can also look at volume or quantity of sales. Effectively the footfall

![image](https://cloud.githubusercontent.com/assets/925619/21093794/9c9a3108-c04b-11e6-936a-394853f0dd30.png)

So, the number of sales invoices. Per customer / customer group. Ideally by day / week / month etc

This will enable us to see how many sales in a period. How many customer came in to the shop for example

**Comment by sharmanakul** [comment]
hey @graphskill, the highlighted field exists in the report. 
closing this.
