### ISSUE TITLE
Add subcontracting module to ERPNext - PAID Services

### ISSUE THREAD

**Issue by gauravmjoshi** [frappe/erpnext#7198]
Hi fellow coders,

I need the services of a experienced coder to add a subcontracting module to ERPNext. The usage of the module would be as below :

1. In sales order, another order type 'sub-con' to be created. Order types are currently hard coded in ERPNext and hence need to be added from program side. 

2. Sub-con sales order shall raise a production work order for processing after subtracting the current stock & also raise a material requisition for raw material requirement. This can be a single level process or multi-level process. The levels ( processing as well as input materials ) shall be fetched from multi-level BOM. For each level current stocks shall be subtracted and then requisitions & processing orders shall be raised. 

3. After material is ready for dispatch, against the original Sub-con sales order number, delivery challan ( not invoice ) shall be raised & material shall be transferred back to customer. 

4. Scrap generated shall be monitored in default scrap warehouse. 

5. Reports to be made of recieved material from customer vs processed material + scrap sent to customer. 

6. Since scrap generated shall be accumulated in plant together, scrap report required detailing total scrap accumulated vs sub con number against which it is generated. 

7. Delivery note should include the batch number, operator names who operated on machines, ideal work times, actual work time, OK work pieces created, Not OK work pieces & scrap generated. All these data shall be fetched from respective modules present in ERPNext.

**Comment by rmehta** [comment]
@gauravmjoshi you can also post this on https://community.erpnext.com/jobs

Our estimate for this would be 25 hours ($1750)

**Comment by yadavyk** [comment]
Please refer : [Subcontracting](https://docs.erpnext.com/docs/v13/user/manual/en/manufacturing/subcontracting)
