### ISSUE TITLE
Allow Item to be added multiple times in a transaction

### ISSUE THREAD

**Issue by nabinhait** [frappe/erpnext#7210]
There are settings for this in Selling Settings and Buying Settings. But the settings should be applied  on all the transactions in sales/purchase cycle. Currently it only applied on Sales Order and Delivery Note in the sales cycle.

**Comment by strixaluco** [comment]
I apologize, some bug happened when I was assigning labels and bhupennewalkar1337 was accidentally unassigned by me, but now I can't assign him back.

**Comment by ishanloya** [comment]
Can we have this for stock entries as well?
