### ISSUE TITLE
Usage Info section is unvisible for free account 

### ISSUE THREAD

**Issue by PrakashH** [frappe/erpnext#7213]
Usage Info section is not visible for free ERPNext accounts. Please fix as soon as possible.

![screen shot 2016-12-14 at 2 04 28 pm](https://cloud.githubusercontent.com/assets/4570016/21175128/f5180028-c206-11e6-81e0-3fd5526c1940.png)

**Comment by rmehta** [comment]
@umairsy can you replicate?

CC @saurabh6790
