### ISSUE TITLE
GL Entry is not updated with cost center in payment entry (deductions or loss)

### ISSUE THREAD

**Issue by hfaridgit** [frappe/erpnext#7219]
I found when making entries in deductions or loss in the Payment Entry that it is not updating the GL Entry with the cost centers in Payment Entry
GL Entry cost center field is null. While I define it in my entries.

**Comment by rkurungadam** [comment]
Cost center is reflected in GL Entry when account of type Income or Expense is selected in deductions line. Please confirm. Thanks

**Comment by hfaridgit** [comment]
Yes, it reflects when account type is expense or income.

**Comment by nabinhait** [comment]
Cost Center and Project are used to analyse incomes/expenses for a period and to define / validate expenses against  budget. Currently, it is not tagged against any Asset/Liability accounts.

Can you please elaborate why you want to tag Cost Center and Project against them?

**Comment by hfaridgit** [comment]
No it was not defined in my accounts (the account type was not defined).
when I defined the account type as expense or income it works, that's right, but what if the user forgot to define the account type then he use it in this part and need to define the cost center and suddenly found that it didn't affect the GL, so I think it is better to leave it to user (either put the cost center or not for any account type) or change the get_query function for the accounts here to be choosen only from expense type or income type, that way there would not be chance for mistakes.

**Comment by rkurungadam** [comment]
We are trying to manage internal transfers and advance payments related to project using payment entry, but project reference is not tagged in GL Entry. So its not possible for us to create project wise GL reports. Any pointers on how to do this is appreciated.
Thank you

**Comment by nabinhait** [comment]
@hfaridgit Accounts are not identified based on "account type", it is identified based on "root type".  And root type is set based on parent account, it does not depend on user input. It means, if you are creating a account under "Direct Expenses", its root type automatically set to "Expense".

@rkurungadam To track internal transfers and advance payments, please create a custom report on Payment Entry / Journal Entry form. Cost Center and project in accounting only designed for Profit & Loss accounts.

**Comment by hfaridgit** [comment]
But when I changed the account_type to expense it works (same account under same root, and same root type) while without account_type defined it doesn't work (and the root type was income or expense).

**Comment by nabinhait** [comment]
@hfaridgit I have checked it again, found that actually it is based on "report_type", and it should be "Profit and Loss". There is no logic based on account_type.
