### ISSUE TITLE
Multi currency Purchase Invoice payment Bug

### ISSUE THREAD

**Issue by mukeshmv1** [frappe/erpnext#7220]
In purchase invoice in currency other than account currency, if we click make payment its updating received amount in foreign currency. Below is screen shot of make payment entry from a purchase invoice in USD, (Company Accounting currency is INR). Instead of getting field of Received Amount (USD) auto-updated with purchase invoice amount, it should be Paid Amount (USD).

![payment entry](https://cloud.githubusercontent.com/assets/12980488/21181230/e6b1ea00-c222-11e6-8ac8-fb9b231fad90.JPG)

**Comment by rohitwaghchaure** [comment]
Hi @mukeshmv1 

I have checked and it's working properly.
Maybe the account of mode of payment is in INR therefore system showing INR in the paid amount.
