### ISSUE TITLE
purchase receipt and bill with negative quantity

### ISSUE THREAD

**Issue by robertbecht** [frappe/erpnext#7228]
Returned one item to supplier combined with order. Got an invoice with one negative quantity and further the normal purchases.. Normally follow the PO>GRN>Invoice>bill...'
Cld not enter the negative quantity in the PO...Logical...Removed it...And added it to the purchase receipt...No problem...Generated the invoice....On Save (Not Possible!!) received Message:  "**Cannot overbill for Item daruvol3 in row 1 more than -33.06. To allow overbilling, please set in Stock Settings**"
Went to stock settings.....No such setting there.....
Robert

**Comment by PawanMeh** [comment]
Can you check the limit percent field ? Assuming this would resolve the issue.

![tolerance](https://user-images.githubusercontent.com/20460498/28522891-8380f93e-7097-11e7-8407-dbf0617e3fa4.png)

If this issue still persists, kindly re-open with Frappe framework version & ERPNext version
