### ISSUE TITLE
Bug / Feature Request - Data Import /Export tool

### ISSUE THREAD

**Issue by Tropicalrambler** [frappe/erpnext#7230]
I tried downloading a data export of Sales Invoices.  When ALL fields are selected, the server gives me an error:

Bad Request
Request Line is too large (4176 > 4094)

This clearly can be fixed with selecting only mandatory fields. However, some data is clealry lost with this. I also tried selecting mandatory and adding some fields.   Yet the case is clear...  at some point the lines, even with only mandatory entering, will exceed 4094 records.

It would be great to have an option to export only those according to date.

**Comment by rmehta** [comment]
Also reported elsewhere. This needs to be a POST query
