### ISSUE TITLE
[Bug] Chart of Accounts - Values caching

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#7237]
Steps:

1. I created new Expense Account called Cleaning Expense.
2. Then I tried adding one more account. 

In that dialog box for entering new account's details, values of the earlier Account created were copied. It needs to be removed manually and set new value.

![values-copied-in-new-account](https://cloud.githubusercontent.com/assets/910238/21225517/4609df60-c2f7-11e6-8c51-c13c0d210f98.gif)

**Comment by mhbu50** [comment]
+1
