### ISSUE TITLE
Enable Collapse All in Tree Reports [v7.2.0-beta]

### ISSUE THREAD

**Issue by IAGAdmin** [frappe/erpnext#7242]
A tree (e.g. Profitability Analysis) is usually by default neither All Expanded nor All Collapsed, as some parts are expanded (see image below).

However to get the Collapsed All button enabled I need to Expand All first and then the Collapse All button gets enabled. 

Is there any reason why it's not enabled right away?

![image](https://cloud.githubusercontent.com/assets/9671446/21249635/6c432a50-c37a-11e6-830a-1d8100ae5772.png)

**Comment by nabinhait** [comment]
fixed
