### ISSUE TITLE
Timesheet Detail "Billing Hours" only calculated on first entry of time

### ISSUE THREAD

**Issue by superlack** [frappe/erpnext#7243]
The field "Billing Hours" is only calculated on the first entry of time, however if the working hours are modified, it could lead to overbilling or underbilling on a project if the user is not aware of the field.

Perhaps a checkbox in the pop-out would allow conditional entry of the field manually?

**Comment by rohitwaghchaure** [comment]
Hi @superlack 

Feature has been added to overbilling or underbilling on a project. It's good feature request, we will add the checkbox in the pop out for manual or auto entry of billing hours based on working hours.

Thanks

**Comment by superlack** [comment]
Fantastic, thank you! Keeps the approval process easy.  I've made the mistake and changed hours many times myself without noticing the billing hours field.
