### ISSUE TITLE
[v. 7.2.0-beta] Wrong Amount calculation when UOM Convertion factor > 1

### ISSUE THREAD

**Issue by joezsweet** [frappe/erpnext#7247]
Hi there, 

i'm not sure if it's by design btw, on `Purchase Order`, editing `Item` row and changing `UOM / UOM Conversion factor` doesn't change the `Amount` value. 

I would expect `Amount =  Price List Rate * Quantity * UOM Conversion factor`, see pic:

<img width="640" alt="schermata 2016-12-15 alle 18 53 43" src="https://cloud.githubusercontent.com/assets/11652845/21256385/3f31aa30-c372-11e6-8a15-b91572dfa085.png">

Please have a look also at Sell Order, Sell Invoice, Quotation etc. 

- In `Purchase Orders`, any chance to allow to select only the Items that can be bought from selected `Supplier`?

**Comment by rmehta** [comment]
@Arundhatii @shachiTakalkar can you replicate this?

**Comment by shachiTakalkar** [comment]
@rmehta it worked fine in my test account. I changed the UOM from Unit to Box and set the conversion factor as 10 and then 12, worked fine both times.

**Comment by rmehta** [comment]
Thanks @shachiTakalkar 

@joezsweet can you confirm this works? And you don't have any custom script

**Comment by joezsweet** [comment]
@rmehta  @shachiTakalkar I can confirm it still not working on Safari 10.0.1, while it's working properly on Chrome. I'm testing on beta.erpnext.com.

**Comment by shachiTakalkar** [comment]
@joezsweet @rmehta I tried to update the UOM in Safari browser as well and it again worked fine for me. It updated the value according to the conversion factor.

**Comment by joezsweet** [comment]
@shachiTakalkar are u testing on beta.erpnext.com?

**Comment by joezsweet** [comment]
See pic ..taken few mins ago 

<img width="640" alt="schermata 2016-12-22 alle 09 34 06" src="https://cloud.githubusercontent.com/assets/11652845/21419768/f74a2230-c829-11e6-90a1-1b0682f5c4a1.png">

**Comment by shachiTakalkar** [comment]
@joezsweet when you change the UOM, I don't think it affects the amount value!!

**Comment by joezsweet** [comment]
@shachiTakalkar i've changed both UOM Conversion factor as well ..and it doesn't work while on Chrome it's working ..could be a browser related issue ..

**Comment by rmehta** [comment]
@joezsweet the qty does not change in either chrome or safari

**Comment by joezsweet** [comment]
@rmehta so, it's working properly?
