### ISSUE TITLE
[v. 7.2.0-beta] What is "Close" on module menu?

### ISSUE THREAD

**Issue by joezsweet** [frappe/erpnext#7248]
As per @IAGAdmin post: 

https://discuss.erpnext.com/t/announcement-erpnext-version-7-2-0-beta-release/18492/4

See pic:

![da1aaa4e6d72a9dbd06ff2c1b10840502b3f3d7f](https://cloud.githubusercontent.com/assets/11652845/21256585/763414b8-c373-11e6-9826-e9a3930b2d15.png)

**Comment by rmehta** [comment]
Fixed
