### ISSUE TITLE
Email alert - suggestion

### ISSUE THREAD

**Issue by graphskill** [frappe/erpnext#7249]
Email alerts are great, but we need to have the option to NOT email the owner

![image](https://cloud.githubusercontent.com/assets/925619/21261769/5921f464-c385-11e6-94f8-c391605256ae.png)

If we think this through, the original creater / owner of the item / document may have left the organisation.  Or as in our case, the Managing Director puts on new products, he does not want to know when the other staff members change the product, perhaps categories etc.

**Comment by cgpurbaugh** [comment]
Agreed.  This didn't used to be the case, it must be a recent change.

**Comment by graphskill** [comment]
@cgpurbaugh 

is that something that we can do (i.e. in the email alert screen) or does it require programming?

**Comment by cgpurbaugh** [comment]
@graphskill I probably should have been more clear, I mean this could be fixed in a future update by simply adding a blank line to the select field.  You may be able to add a blank line in customize form, I'm not sure.

**Comment by graphskill** [comment]
Thanks for the clarification, but probably beyond my understanding

This is the custom form for the recipient table

![image](https://cloud.githubusercontent.com/assets/925619/22071885/7ed6a664-dd98-11e6-8eae-415b18f4b26a.png)

And the recipient

![image](https://cloud.githubusercontent.com/assets/925619/22071909/9144f60c-dd98-11e6-8500-41e2d3f16d33.png)


Anything i can do? or do I just need to wait for some kind soul to update the code

**Comment by graphskill** [comment]
Can anyone help here? This issue ruins the feature and makes it unusable

**Comment by Devens** [comment]
+1

**Comment by graphskill** [comment]
This seems to be fixed in version 8
