### ISSUE TITLE
[v. 7.2.0-beta] Socket API 502 Bad Gateway error

### ISSUE THREAD

**Issue by akhileshdarjee** [frappe/erpnext#7252]
Hi Team,

Getting console error as follows as soon as you login:

libs.min.js:3684 GET https://beta.erpnext.com/socket.io/?EIO=3&transport=polling&t=1481899142556-0 502 (Bad Gateway)
Request.create @ libs.min.js:3684
Request @ libs.min.js:3607
XHR.request @ libs.min.js:3538
XHR.doPoll @ libs.min.js:3568
Polling.poll @ libs.min.js:3957
Polling.doOpen @ libs.min.js:3901
Transport.open @ libs.min.js:3078
Socket.open @ libs.min.js:2508
Socket @ libs.min.js:2390
Socket @ libs.min.js:2325
Manager.open.Manager.connect @ libs.min.js:1064
Manager @ libs.min.js:922
Manager @ libs.min.js:892
lookup @ libs.min.js:825
init @ desk.min.js:164
startup @ desk.min.js:1049
load_startup @ desk.min.js:1049
init @ desk.min.js:1049
Class @ desk.min.js:7
frappe.start_app @ desk.min.js:1048
(anonymous) @ desk.min.js:1049
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
ready @ jquery.min.js:2
J @ jquery.min.js:2

libs.min.js:3684 GET https://beta.erpnext.com/socket.io/?EIO=3&transport=polling&t=1481899143664-1 502 (Bad Gateway)
Request.create @ libs.min.js:3684
Request @ libs.min.js:3607
XHR.request @ libs.min.js:3538
XHR.doPoll @ libs.min.js:3568
Polling.poll @ libs.min.js:3957
Polling.doOpen @ libs.min.js:3901
Transport.open @ libs.min.js:3078
Socket.open @ libs.min.js:2508
Socket @ libs.min.js:2390
Socket @ libs.min.js:2325
Manager.open.Manager.connect @ libs.min.js:1064
(anonymous) @ libs.min.js:1329

I suppose the API is on set to an interval which is responding with 502 Bad Gateway Error

Steps to get the error:

1. Visit https://beta.erpnext.com/
2. Click on "Launch Demo"
3. Open the browser console to see the error

**Comment by nasir97177** [comment]
I have Same Issues V13, Kindly help me For Solving this issues
