### ISSUE TITLE
[BUG] Sales Order shows incorrect net total after saving draft

### ISSUE THREAD

**Issue by saurabhvashist** [frappe/erpnext#7253]
**Issue Encountered:**
While using "Apply Discount On - Net Total" in "Sales Order" phase.

No issue while using "Apply Discount On - Gross Total".

**Versions:**
ERPNext v7.1.26
Frappe v7.1.26

**Issue In Detail**
While entering data in the Sales Order, it shows totals as below:

![1](https://cloud.githubusercontent.com/assets/22211942/21285059/6253ecac-c454-11e6-8a12-d1d5d28dfde6.png)

After saving the sales order, it shows net totals as below (which is incorrect):

![2](https://cloud.githubusercontent.com/assets/22211942/21285060/6d31694c-c454-11e6-8803-c7ba139d9738.png)

In this scenario:
Gross Total = Rs.18352
VAT Rate = 20% (included in above price). Hence,
Net Total = Rs.15293.33

Apply Additional Discount on
Net Total = Rs.706

New Net Total = Rs.14587.33
VAT @20% = Rs.2917.47
New Gross Total = Rs.17505 (rounded)

During data entry, the ALL values are correctly shown. However, after saving the draft, the system incorrectly considers:
- Gross Total as Net Total (it means Rs.18352 which was Gross Total, becomes Net Total)
- Applies the additional discount of Rs.706 on Rs.18352 making Net Total as Rs.17646
- Then applies VAT (20%) on the incorrect value of Rs.17646 making the Gross Total as Rs.21175.19

--
Regards
Saurabh

**Comment by saurabhvashist** [comment]
Same issues encountered while testing on: https://beta.erpnext.com

**Comment by rmehta** [comment]
@Arundhatii can you replicate this?

**Comment by Arundhatii** [comment]
@rmehta  Working on it 
 https://discuss.erpnext.com/t/bug-sales-order-shows-incorrect-net-total-after-saving-draft/18521

**Comment by saurabhvashist** [comment]
I just updated my server to following versions:
ERPNext - v7.2.6
Frappe - v7.2.5

Unfortunately, the problem persists for me. I observed that as per the fix, test_sales_order.py file has been updated but not sales_order.py. Do I need to manually make changes on my server to make it work?

--
Regards
Saraubh
