### ISSUE TITLE
Renaming a `Warehouse` changes the linked `Account` name but not the warehouse name itself

### ISSUE THREAD

**Issue by hendysg** [frappe/erpnext#7254]
For example, starting with the "Finished Goods" warehouse

![image](https://cloud.githubusercontent.com/assets/660814/21285135/55a831a4-c46b-11e6-9395-5b06cf1fe012.png)

Try to change the name

![image](https://cloud.githubusercontent.com/assets/660814/21285153/fe713448-c46b-11e6-83c4-216670a4ec0f.png)

![image](https://cloud.githubusercontent.com/assets/660814/21285143/b513287e-c46b-11e6-9898-f69039dd8c9b.png)

ends up with 

![image](https://cloud.githubusercontent.com/assets/660814/21285168/4a8284e0-c46c-11e6-99bc-8521feb06271.png)

When I go to Chart of Accounts page. I see that the linked account is changed too.

![image](https://cloud.githubusercontent.com/assets/660814/21285184/af857546-c46c-11e6-88b9-59dc4325baff.png)

When I download the Warehouse csv from the data-import-tool page, see that the `name` column has changed but `warehouse_name` did not.

![image](https://cloud.githubusercontent.com/assets/660814/21285208/4edbee40-c46d-11e6-8906-e428b915b23d.png)

**Comment by hendysg** [comment]
I'm not a hundred percent sure if the behavior above is a bug or a feature. If it is a feature, can someone show me how I can change the warehouse name (`warehouse_name` column) properly please? Hopefully without having to do update query to mysql directly.

**Comment by nabinhait** [comment]
fixed this in v8. now it will rename the warehouse_name column as well.
