### ISSUE TITLE
Feature Request: Allocation of Expense between Cost Centers

### ISSUE THREAD

**Issue by xainch** [frappe/erpnext#7256]
Can this be considered for a feature please? 
Division/Allocation of **Expense** among **Cost Centers** on Percentage basis for one time occurring expenses and Automatic Allocation in case of Recurring Expenses.

**Comment by Devens** [comment]
Very Useful... +1

**Comment by mhbu50** [comment]
+1 I need this to

**Comment by mhbu50** [comment]
@harshit-30 is this feature get implemented?

**Comment by harshit-30** [comment]
Kindly create a new issue with the detailed real-life use case and requirements based on what problem are you solving.
