### ISSUE TITLE
Manage over payment directly in Payment Entry

### ISSUE THREAD

**Issue by jof2jc** [frappe/erpnext#7257]
Payment entry allows us to e.g. receive advance payment or over payment againts invoices.

But later we have to match invoices with payments using separate payment reconciliation..this is not efficient!!

Using payment entry, when customer is selected then users must be able to match any advance deposits or over payment with invoices directly without moving to separate payment reconciliation.

Users mostly don't aware if customer has advance or deposit balance.

So I think payment reconciliation functionalities are better merged into payment entry. So all payment, receipts, reconciliation are done within single form.

**Comment by Devens** [comment]
I agree with @jof2jc +1

Further, similar reconciliation section can be made available in Invoice also. So, that from invoice also it can be set against payment without going to separate reconciliation form.

**Comment by hani888** [comment]
I agree with you

**Comment by Scheercuzy** [comment]
+1

**Comment by jorgeastiazaran** [comment]
Hi, any update on this?

**Comment by harshit-30** [comment]
While creating a new invoice, use Get Advances Received button to allocate the advances.
