### ISSUE TITLE
variable value today() in filter

### ISSUE THREAD

**Issue by Devens** [frappe/erpnext#7259]
We should have "today" variable in filter for Date type Field

![untitled_clipping_121416_031238_pm](https://cloud.githubusercontent.com/assets/10671911/21299572/02aac148-c5c3-11e6-8135-6da9eaf6c7b2.jpg)

**Comment by PawanMeh** [comment]
This exists now

![today in date](https://user-images.githubusercontent.com/20460498/36097991-3d6fcf3e-1023-11e8-9ffa-9ca6bd6c5aea.png)

![report builder](https://user-images.githubusercontent.com/20460498/36098038-6d0a7618-1023-11e8-8fec-6dbd324400d5.png)
