### ISSUE TITLE
Differentiation of Salary Process from Salary Payment 

### ISSUE THREAD

**Issue by Fredoluka** [frappe/erpnext#7262]
In the Process Payroll page in the HR of Erpnext,the MAKE BANK PAYMENT should be changed to make JOURNAL ENTRY so that payment account can allow a current liability account selection(bank journal will only allow bank or cash account).It must be understood that salary process differs from salary payment and it will be wrong to think that each time salary is processed ,it is paid..
Fred

**Comment by KanchanChauhan** [comment]
Fixed via https://github.com/frappe/erpnext/pull/7704
