### ISSUE TITLE
Official HScode - Item code suggestion...

### ISSUE THREAD

**Issue by NickMalef** [frappe/erpnext#7263]
Dear team,

Given my profession (Customs Agent) I understand that item code mechanism in ERPNext is identical with the globaly accepted HScode mechanism that all countries use to categorise all commodities.

https://en.wikipedia.org/wiki/Harmonized_System

With that said ERPNext could create a mechanism to fetch HScodes (from douzens of websites around the world) and set value in the Item Code field automatically as a proposal to the user.

just my 0.02

a link from the ERPNext forum:

https://discuss.erpnext.com/t/item-code-from-customs-authorities-hs-codes/18546/2

Nick

**Comment by bcornwellmott** [comment]
It4em Code and HS code are not the same. An item code is a unique product identified, whereas an HS code is a general identified to describe the type of item. HS code is more akin to an Item Group than Item Code.

**Comment by NickMalef** [comment]
Dear bcornwellmott,

I am afraid this is not correct.

HS code is EXACTLY the same as item code.

What you must mean, is that HS code has a route from 2nd to 10th digit which has a logic passing from Customs category to Customs category, but always, always, a 10th digit HS code is unique and represents a specific commodity, so an item code the way we know it in ERPNext.

Please click the link above to read the conversation in ERPNext forum.

Thanks 

Nick

**Comment by bcornwellmott** [comment]
I don't think you understand what an Item Code is.  For example,  brake pads for cars has an HS code 8708.30.9990 (for Canada for example). If I'm a distributor of brake pads in Canada however, I might sell OEM pads from 6 different companies plus aftermarket products. Each of those suppliers might have 10 different products. Each of those products, having the same HS code, would have a unique Item Code. 

My company creates hundreds of new items a year. None of those get assigned an HS code, but I need to be able to track them in my system to produce and sell them. Once again, I think HS code and Item Group are more closely related.

**Comment by NickMalef** [comment]
Yeap I see your point.... You are right, but in this case are you sure you use item code the correct way?

I mean what is the meaning of a field with the name "code" in it? Isn't it uniqueness?

Item code should be a unique code which represents the uniqueness of an item. HS code does this globaly and it is invented for this reason.

IMHO your item code then should be:
8708.30.9990.OEM
8708.30.9990.AftX
8708.30.9990.AftY
8708.30.9990.AftZ

Of course I am not claiming that the HS code mechanism should be mandatory, but it would be a great feature for those who need it.

**Comment by bcornwellmott** [comment]
I think for most people, the HS code is a side feature. Even in companies that use the HS code regularly, they typically have internal and external part numbers that are completely separate from the HS code. If all you do is supply one specific HS type, why waste typing all those digits in your item codes for no benefit.

I think having a field in the Item for an HS code would be useful, especially if there was a tool to automatically look it up.

**Comment by dalers** [comment]
@bcornwellmott - so what do you use for Item Code? Your internal part number? Your external part number? Do you have ERPNext assign its own unique Item Code?
