### ISSUE TITLE
[v7.2] valuation rate not found for warehouse {1} Error on every stock transaction

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#7265]
Hello,

I'm testing and reporting the issues in the beta version and I'm facing this error that I'm not sure if it is a bug or something I did wrong. Here is the issue, every transaction that updates stock can't be submitted, it shows this error: "For the Item {0}, valuation rate not found for warehouse {1}. To be able to do accounting entries (for booking expenses), we need valuation rate for item {2}. Please create an incoming stock transaction, on or before {3} {4}, and then try submiting {5}"

I use negative stock, which seems to be related to the the problem, did I do anything wrong?

![sem titulo](https://cloud.githubusercontent.com/assets/18335894/21311139/ceb974f6-c5cc-11e6-8188-3fb57093bb26.png)

**Comment by nabinhait** [comment]
The validation has been added in this version. Basically, as per perpetual inventory, system books expenses on delivery of the item. To book expenses, we need the incoming rate of an item. But here, system did not found any incoming entry for the item 1761 in the suggested warehouse. 
Here, incoming entry can be any of the Purchase Receipt, Stock Entry (Material Receipt) or Stock Reconciliation. But the posting date of incoming entry must be before delivery datetime.

**Comment by applepipe** [comment]
@nabinhait Thank your for your explanation! I've deactivated the option to Make Accounting Entry For Every Stock Movement and now its working.
