### ISSUE TITLE
Company Filtering - Material Request and BOM

### ISSUE THREAD

**Issue by OneiricIT** [frappe/erpnext#7268]
Hi,
Finding filtering is not working as expected when creating BOM, specifically I am able to create a BOM allocated to **Company A** however I can select and tie the BOM to a project which is in **Company B**? This is also the same in Material Request.

Further to Material Request, and specifically the 'Get Items from BOM' - after I specify the Company and then select 'Get Items from BOM' I can select any BOM from any company, and also any warehouse from any company - example shown below. If I do not use the 'Get Items from BOM', but instead populate the warehouse in the materials table it is filtering correctly.

erpnext 7.1.26
frappe 7.1.26

![image](https://cloud.githubusercontent.com/assets/22227933/21334548/89093b54-c6ac-11e6-8b07-5ae616495ff5.png)

![image](https://cloud.githubusercontent.com/assets/22227933/21334399/61a2fa4c-c6ab-11e6-8097-7152d11f2f89.png)

**Comment by strixaluco** [comment]
@OneiricIT, does the issue still persist? Can't replicate it.

**Comment by OneiricIT** [comment]
@strixaluco sorry, would need to setup new tenant as that was a test instance which has been removed. I will close for time being and create new if occurs again.
