### ISSUE TITLE
Design a better login page

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#7269]
<img width="972" alt="screen shot 2016-12-20 at 11 02 55 am" src="https://cloud.githubusercontent.com/assets/140076/21339282/f4c4bd9a-c6a3-11e6-9d91-4602041b9542.png">

#### with social keys

<img width="676" alt="screen shot 2016-12-20 at 11 03 15 am" src="https://cloud.githubusercontent.com/assets/140076/21339284/f854c720-c6a3-11e6-9e05-2b0325117dc6.png">

**Comment by dalers** [comment]
At some time, and possibly still, Chrome didn't recognize the username field and remember the username/ password pair correctly.

**Comment by dalers** [comment]
Sorry, I should have said Chrome on an iPad. It doesn't seem to recognize the username field as a username field because the fields don't get populated with my remembered username/password. 


----- Original Message -----

**Comment by Naqeebullah0098** [comment]
is it possible to change login page without change in its core ....?
or apply our own layouts and templates
