### ISSUE TITLE
Shipping Address searching

### ISSUE THREAD

**Issue by lxnow** [frappe/erpnext#727]
When searching for a Customer's Shipping Address in Sales Order, with field *ID* selected, the search function seems to be only searching through field *address_type*.  

Is this correct? Isn't *ID* a combination of *address_type* + *address_title*?   This has come to be an issue as *address_type* is now limited to a few values since the July 2013 UI changeover.

**Comment by cgpurbaugh** [comment]
This seems to be fixed.
