### ISSUE TITLE
Troubleshooting Permissions for a New Role

### ISSUE THREAD

**Issue by rohitk75** [frappe/erpnext#7273]
Hi 

I am trying to create a new role with very restrictive bare minimum permissions. When I try to do a transaction like POS,  I get a message "You do not have enough permissions to access this resource. Please contact your manager to get access." 

This is very generic message which does not tell me which Doc Type do I need to give permission to.

Is there a way I can look at some Log files and see which Doc Type I do not have permission to. Since it is a one time task I am willing to iterate by looking at log files and give more permissions to a Role Type till I get it right.

I do not want give any extra permission since I am creating a a very restrictive profile. 

Any suggestions ? Role duplication feature can also help since It is easier to just delete permissions on different Doc Types rather than add them.
 
Thanks & regards

Rohit

**Comment by revant** [comment]
Please ask questions on the forum https://discuss.erpnext.com/
