### ISSUE TITLE
Show customer fields in POS

### ISSUE THREAD

**Issue by dzulhelmi** [frappe/erpnext#7278]
This is from [this thread](https://discuss.erpnext.com/t/show-customer-fields-in-pos/18564) and Umair suggested to post it here

Our current business is using other POS solution where we can create new customer data straight from the POS interface. (attachment)

![screen shot 2016-12-19 at 3 08 34 pm](https://cloud.githubusercontent.com/assets/1688224/21341978/60eaf270-c6ca-11e6-9f50-2ef5f1453194.png)

However, the ERPN POS **only** allow to select from **existing** customer or add new customer by entering their Fullname.

Is there anyway that in the POS screen itself, we can create new customer just like in the Customer module? The info I want to appear in the POS screen are:

- Name

- Address

- Telephone

- Custom fields (Car Make, Car Model, Car Registration Number)

The selection from existing customer feature is fine, leave it there. By default, the POS load the existing customer fullname, but imagine if we have so many customers with same fullname? We are in automotive industry, loading just by name is not helping, maybe we can load the selection with combination of Fullname+Car Registration Number? Is this series number?

**Comment by sharmanakul** [comment]
in the newer versions, new customers can be added through the POS using the quick entry form.
