### ISSUE TITLE
Serialized Items in ERPNext Online Demo

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#7281]
Hi Team,

Please add some serialized items (Has Serial No = Yes) in the ERPNext online demo. Since demo users are restricted from adding items, it's important to have the major scenarios covered. The online demo account not only helps new users get acquainted with the application, it also serves as a platform to test if issues being experienced are general and/or if they've been resolved in the latest release

Many thanks

**Comment by strixaluco** [comment]
https://beta.erpnext.com has serialized item now
