### ISSUE TITLE
Stock Entry Crash with Non-Stock UOM

### ISSUE THREAD

**Issue by bcornwellmott** [frappe/erpnext#7283]
I get a console error (and ERPNext freezes) when I try to create a stock entry and set the UOM to a non default UOM for an Item.

Here is an example, where the default UOM is Unit:
![image](https://cloud.githubusercontent.com/assets/16806041/21363331/f1932592-c6a0-11e6-99e8-82ff0a4d54f5.png)

The error Uncaugt TypeError: Converting circular structure to JSON comes up as soon as I enter the other UOM.

**Comment by rmehta** [comment]
Not able to replicate. Can you share the response to the query?
