### ISSUE TITLE
Trial balance should be displayed/printed/exported without groups

### ISSUE THREAD

**Issue by fblauer** [frappe/erpnext#7288]
Trial balance should be displayed without groups, or at least have that option. The financial statements and also the chart of accounts already have groups. There is no reason for the groups to show on the trial balance, which should have actual/detail accounts only, with a total at the end. The groups get in the way of being able to print a list of actual accounts with balances, since the export and also the print report shows only the groups instead of the detail accounts which is what we need. This is a very basic report that everyone will need. 

I tried a custom report in the chart of accounts list, but this will not display balances, since that is not one of the column options. Nabin agreed and suggested that I create an issue here.

**Comment by ai-erp** [comment]
I Agree with @fblauer ...
Or there should be at least option for detailed trial balance or for group...
Total should be also shown below the beginning and ending debits and credits...
Thanks...

**Comment by fblauer** [comment]
I checked version 8, and it doesn't seem to be there? Any idea of ETA? I think that this is something that everyone would need. The trial balance should not have account groupings, only accounts. Maybe you can just suppress the amounts on the account groupings, if that would be easier.

**Comment by kennethsequeira** [comment]
Refer Simple Trial Balance report.

**Comment by Olawale1** [comment]
Hi @kennethsequeira 

Trust you're doing well. This same issue with export applies to 'Balance Sheet' and 'Profit and Loss' report

How can we get around this ?

Kind regards,
