### ISSUE TITLE
wrong fiscal year

### ISSUE THREAD

**Issue by almagalvez** [frappe/erpnext#7293]
I cannot work on the demo because I set up the fiscal year from Jan 1st, 2017 to Dec 31st, 2017.  Can you help me change it to 2016 so I can run my tests?

**Comment by almagalvez** [comment]
Nevermind

**Comment by yashodhank** [comment]
@almagalvez demo is used by everyone and may not be amendable to your needs. Simply signup from erpnext.com for an account as it is free for 1 user.
