### ISSUE TITLE
GL Entry project field not update from Payment entry 

### ISSUE THREAD

**Issue by rkurungadam** [frappe/erpnext#7298]
Related Issue #7219

Project field in GL Entry is not set based on the project reference in Payment Entry. Need advice, can this  be set for party, bank as well as deduction entries.

Project and Cost Center fields are set too None in GL Entries Validation if Accounts report type is Balance Sheet. This makes sense for cost center, if project too is considered the same then these issues can be closed. I have commented in #7219

Thank You

**Comment by nabinhait** [comment]
Closing this issue, please elaborate the reason of having Project for Assets/Liabilities in the issue #7219
