### ISSUE TITLE
[Enh] Shopping Cart Addresses

### ISSUE THREAD

**Issue by jwrober** [frappe/erpnext#7303]
From discussion https://discuss.erpnext.com/t/shopping-cart-addresses/18630

Would like to see two things with the shopping cart feature.
1. Add a setting so we can configure if we want to require shipping address or not. Clearly always need a billing address, but if you are selling a service there is nothing to ship and so would be nice to be able to turn that requirement off for the shopping cart.

2. Develop a means to create your own shopping cart "path" or "wizard". Kind of like the slideshow feature of the website. For example, in the discussion I would like to be able to add capturing an address inline with the check out process if one does not exist, but that is not there right now. I could see other areas where an admin would want to add more pages, setup cross and up sell items, etc all during check out.

Thanks

**Comment by jwrober** [comment]
To add this my own comment the other day, especially around point 2 -- In the shopping cart wizard (if that is what we can call it), give option to incorporate features of web form in there so we can get information from a customer as they are checking out.

**Comment by federicocalvo** [comment]
Hi, @jwrober , I think this issue could be related to ours. 

https://github.com/frappe/erpnext/issues/15198

For anyone to consider using ecommerce they must have the option of not logging in or at least logging in at the end of the day.

Regards!

**Comment by sharmanakul** [comment]
shopping cart has gone through some refactoring recently. https://www.youtube.com/watch?v=aQOAIsG29AM
i think the issue posted here might have been addressed.
