### ISSUE TITLE
Item naming by series or item code (optional) [Paid Development] 

### ISSUE THREAD

**Issue by jeff-fournier** [frappe/erpnext#7304]
We would like to sponsor a change in the ITEM creation feature for ERPNext.
We would like the ability to choose between creating a standard item OR a serialized item code while on the same window.  Currently, you must create series and change stock settings to create a serialized item code.  If you wish to create a non-serialized item code you have to change all the settings in order to do so.  We believe it would be beneficial to have the option to toggle this on or off while on the ITEM creation window.  This way either type of code can be created on demand and with ease.

Ideally, when the ITEM CODE field is being input on the NEW ITEM window, a pull down list could list available SERIES.  If that series is selected, the next available number will be input with it.  If no series is selected, whatever is entered in ITEM CODE will be taken as it is typed.

For example, if we create an ITEM series "TEST" and set the numbering to start at 123, if we start typing in the ITEM CODE field, a pull down list will display TEST124.  If I select it, it will be shown in the ITEM CODE field as "TEST124".  If instead you type "SOMEITEM", it will just display "SOMEITEM".  When clicking SAVE, the ITEM CODE will be used (if available) when creating the item.  If it was a series selection, the number should auto-increment to 124.  When selecting a NEW ITEM and typing an ITEM CODE and selecting the series again, it will now be "TEST125".

We would like to see an estimate on such a feature.

**Comment by rmehta** [comment]
@jeff-fournier would a check do to select whether you want to name it by Series or custom? Also it will make it explicit so there is no confusion to the person making the entry whether the new item will be named by series or by code.

**Comment by jeff-fournier** [comment]
That could work. As long as the effect of being able to choose is there.
One other item I noted that will be related, I noticed the series increment is based on individual series names. So if I create a series named HELLO, and a series named WORLD, the increments as each are added are independent. That is, HELLO-1 will be created first and then HELLO-2, but WORLD will be WORLD-1 when it is created.  Is it possible to add an option to bind a series together so the increments are treated the same to the group of series? E.g.: HELLO-1, HELLO-2, WORLD-3?
This is important to us because barcodes are created based on the number in the item created and must be unique.
Thanks for your quick response.

**Comment by rmehta** [comment]
@jeff-fournier grouping is a separate feature request.

Let me find a dev who can do it for you.

**Comment by jeff-fournier** [comment]
Hello.  Sorry for the late reply.  I've been busy catching up with work and just got this message now.  I have my management staff reviewing it and will get back to you shortly to let you know if we will go ahead.

**Comment by jeff-fournier** [comment]
UPDATE:  (That was quick)
We will proceed with this.  Please send an invoice.  Please make it out to MICROFORUM SERVICES GROUP. My e-mail is jeff.fournier@microforum.ca if you need to get further information.
Regards,
Jeff

**Comment by Arundhatii** [comment]
Stock settings will be showing an additional option for Item Naming by "User will select"

![new mockup 2](https://cloud.githubusercontent.com/assets/20164097/21977820/e35d9fda-dbfd-11e6-8fec-5caaeb77c39f.png)

Once it is selected in the stock settings Item Creation screen will show an additional check box option for selection the naming series.
![item naming](https://cloud.githubusercontent.com/assets/20164097/21977829/eab7a01e-dbfd-11e6-989d-44f6460682ad.png)

**Comment by jeff-fournier** [comment]
Will I be receiving an invoice for this development soon?  I wanted to be sure it will be in a future release. Please advise.

**Comment by rmehta** [comment]
@jeff-fournier does the mockup seem okay to you?

**Comment by jeff-fournier** [comment]
The mock up is perfect, but to be more specific, for the wording on the last, "The item code generated from the Naming Series will be the next number from the previous item code", I would like to specify "regardless of the selected series item". It may even be worth having an option box in the item creation screen to allow users to specify that the series numbering can be specific to the item or a global increment. That way the platform can be more useful to the rest of the community.
So we could add a check box called "use global series" under "naming by series". If the naming by series is unchecked, use global series is not enabled. When it is checked, the use global series is enabled. When item is created, the number generated would be based on the options selected.

That would make it more useful I believe.

**Comment by nabinhait** [comment]
@jeff-fournier adding another checkbox for global series will make it more complicated. The series whether it is global or depends on some condition will come in the dropdown, hence user will be able to select required series.

To make the design more consistent, instead of adding a checkbox "Naming by Series", I think we should add a select field "Item Naming By", same as Stock Settings. By default it will be set based on Stock Settings while opening a new Item form, user can later change it. The Series field will be visible and become mandatory based on the input on "Item Naming By" field.

**Comment by jeff-fournier** [comment]
The biggest reason for this particular feature is that we sometimes have to generate UPCA bar codes based on the item.  In our business, a customer can place an order for say a CD, or a DVD, or a Vinyl Record.  The base codes for the items we would create are either MF, MD, or V12.  The number that gets added to each code needs to be unique.  So you could never have an MF-53333 and V12-53333.  Even though they are unique items in ERPNext, the numeric code that will be used to generate a UPCA code (which will have a base code that is reserved for our company.  If this is out of scope and requires additional quoting, we are willing to go down that road.  This particular feature is very important for us.  

If you feel that this could be handled in the current scope, let me know.
