### ISSUE TITLE
Allow Sales Orders and Invoice creation only if quantity is available in stock

### ISSUE THREAD

**Issue by Shervin24** [frappe/erpnext#7307]
Hi,

Control need to be developed in order to Restrict  SO being created without stock. In general If Allow negative Stock is allowed it will not allow user to release Sales order or Invoices without Quantity of the particular item in hand.

I think this is a very critical function which is required to be developed ASAP

**Comment by rmehta** [comment]
In Make to order, engineer to order, Sales Orders are always made before the stock is in hand.

Maybe you need an additional feature to allow Sales Orders to be created only with stock. Btw, this is the first time we are hearing of such a request. Leaving the issue open, but does not seem priority.

**Comment by Shervin24** [comment]
Hi Rushabh,

Hope you enjoyed the Christmas Holidays. Wish you a merry Christmas !

In general tier 1 ERP like Oracle Does not allow Negative stock from SO. However this is a Option to allow where it depends on the Organization and Nature of the business. However Appreciate if you can bring this to Invoicing at least to avoid user to invoice  without  the stock. Need to be Option to allow or Not. Hope to hear from you soon.

Regards,
Shervin

**Comment by rmehta** [comment]
You are free to sponsor this or get it built by someone in the community and we will include it in the product!

**Comment by sharmanakul** [comment]
Hey, it seems that this feature request hasn't got much traction from the community. I'm closing it for now.

**Comment by shamsi2u** [comment]
I also have the same requirement  is there any options available there now.
