### ISSUE TITLE
Chart Of Accounts Rename

### ISSUE THREAD

**Issue by seanfalloy** [frappe/erpnext#7313]
When renaming accounts the data base is updated properly but the current links on screen are not.
 
 When renaming from the Chart Of Accounts screen (select account > select rename)
 
 - Type new name in pop-up dialog
 - Select "Rename"
 
The page refreshes to what looks like the edit page with the bread crumbs at the top of the screen referencing the wrong account

To "Go up one level" does not work      
E > Accounts > **_Account_**

### EDIT: Ignore after here, I did not see the refresh button which fixes [ONLY] the problem below

_When renaming from the Chart Of Accounts screen (select account > select 'edit' > Menu > Rename )_

- _Type new name in pop-up dialog_
- _Select "Rename"_

_Select "Account" in bread crumbs and "Go up one level" works properly but the new name does not appear in the Chart Of Accounts screen_

**Comment by rmehta** [comment]
Fixed!
