### ISSUE TITLE
Edit HTML in print format - Text Editor is removed?

### ISSUE THREAD

**Issue by Devens** [frappe/erpnext#7317]
Text Editor in "Edit Html" should not be removed. It was very useful. 

![image](https://cloud.githubusercontent.com/assets/10671911/21467326/6b4534a4-ca0f-11e6-9856-487b6cd7b73c.png)

It was there already as shown in one of the help doc. 

![untitled_clipping_122416_073157_pm](https://cloud.githubusercontent.com/assets/10671911/21467330/98054c22-ca0f-11e6-85fa-748d87405530.jpg)

**Comment by Devens** [comment]
@rmehta - Whether Editor is purposefully removed? It is affecting our regular updates (as we don't know html.)

**Comment by netchampfaris** [comment]
@Devens You can use the **Print Heading** field for this
