### ISSUE TITLE
Cost Center Tree - Bugs and functionality improvements

### ISSUE THREAD

**Issue by Tropicalrambler** [frappe/erpnext#7318]
When using the Cost Center Tree page, there are several bugs or functionality issues which I think should be addressed to speed up the work.

# - Problem  1: 
I click on a specific folder to "Add Child",  enter the name of the child and whether it is a group or not. I click on "Create New".  The group or cost center simple node is created, but NOT under the specific folder chosen.  I then have to go to the **Cost Center** report view, click on the newly created node and edit it, changing its parent node to what I originally wanted.  This problem does not happen repeatedly, it happens only occasionally, and I have not been able to figure out specifically which order of commands cause it.

**# BUG UPDATE:**  Only the first child item of the Add Child command for a specific Cost Center folder is the one that does not insert into the selected folder, it actually inserts it into the previous folder that was being used for insertion with the **Add Child** command.  Thus, the "second"  add child command for the currently selected folder, will work OK. 

# - Problem 2:
Another bug is that changes will not immediately reflect when you convert a node from group to non-group and vice versa, the page has to be refreshed, and the whole tree collapses, forcing you to clicking to expand each folder to get to where you left off.  You click on a node> Edit > Convert to Group or Convert to Non Group. When you click "Save" and then back on your browser, the changes do not show until you reload the page (and collapse the tree, a time consuming task to reopen everything)
# - Problem 3:
When you rename nodes, the text changes in size, and the folder icon or the circle disappears.  If it is a recently created group, you cannot add a child to this newly create node until you refresh (and the whole tree collapses again, then you have click back down to where you were, a time consuming task.)

**Comment by mhbu50** [comment]
+1

**Comment by jwrober** [comment]
I wonder if this is related to this enhancement idea from frappe

https://github.com/frappe/frappe/issues/2448

The two seem very similar in how the platform handles tree-views like the cost center tree. They all do what @Tropicalrambler mentions.

**Comment by Tropicalrambler** [comment]
Thanks for linking to the frappe enhancement idea #2448, it is exactly what I meant in this issue.

**Comment by Tropicalrambler** [comment]
Thanks!
