### ISSUE TITLE
Create Material Requests for different Warehouses when using Production Planning Tool

### ISSUE THREAD

**Issue by dvdl16** [frappe/erpnext#7319]
Hi there!

Firstly, thank you to for everyone's contribution on this great project. I've recommended ERPNext to many of my peers.

I seem to have an issue when creating MR's with the Production Planning Tool. In the PPT, I want to create Production Orders and MR's based on an existing Material Request for a final product (with multi-level BOM). The Production Orders are created successfully with the "Create Production Orders" button. But when I want to create MR's, I have to select a single warehouse. The MR's are then created successfully (MR's are created of type "Production" for sub-assemblies, and MR's are created of type "Purchase" for purchased items). Note that the sub-assembly items have a different Default Warehouse than the purchase items. This "Default Warehouse" setting is ignored when the Production Planning Tool creates MR's, as it sets the "To Warehouse" field of the MR to the Warehouse selected when using the Production Planning Tool.

My issue seems similar to this one: [https://github.com/frappe/erpnext/issues/1792](https://github.com/frappe/erpnext/issues/1792)

Is it not possible to create MR's from the Production Planning tool, but set their "To Warehouse" field to the Default Warehouse of that item? I can work around this issue by setting the Default Material Request Type of certain items to "Transfer", but then I have to create "Purchase" MR's manually.

I can't duplicate this on the demo site as there are no multilevel BOM's with different Default Warehouses. 

Please let me know if I should explain my issue with a simple example, if it is not clear.

Also, season's greetings!

Side note:
We're using:
ERPNext: v7.1.1
Frappe Framework: v7.1.2

**Comment by dvdl16** [comment]
Can anyone maybe comment on this? Should I rather just use one big warehouse to avoid this issue?

**Comment by bcornwellmott** [comment]
This is a legitimate enhancement in my view, but it's on a big queue of things for the developers to do, so unless you want to take it on yourself it will take a while for it to get implemented. 

I use one big stores warehouse (for now), but the other option is to set them to Purchase and just cancel/amend them to correct the warehouse.

**Comment by dvdl16** [comment]
Thanks bcornwellmott for the reply. I completely understand, and have actually been interested to get more involved in this project (I just need to get more time somewhere).

I appreciate (for what it's worth) the work that you've done thus far. We'll use one big stores warehouse for the time being.

Cheers
