### ISSUE TITLE
Item Locations in warehouse

### ISSUE THREAD

**Issue by farhanayyaz1** [frappe/erpnext#7320]
Dear,

is there any way to list item location in warehouse so its easy to access them.

**Comment by rmehta** [comment]
Create a separate warehouse for each shelf.

**Comment by farhanayyaz1** [comment]
Dear,


Than how can we use them in sales invoice, isn't that a long process.



First Moon Electronics Trading.

SHIPPING MARK:  MFB

TEL:00971-4-2284525

FAX: 00971-4-2242179

Mobile Dubai: 00971-52-9291514

P.O.BOX: 86527,DUBAI-UAE

Address: SH#47,Baglaf Bldg,Nakheel Road,Dubai-UAE

________________________________
