### ISSUE TITLE
Error After Bench Update: No such file or directory: u’./assets/frappe/css/daterangepicker.css’

### ISSUE THREAD

**Issue by gvyshnya** [frappe/erpnext#7325]
Please see more details on the problem at https://discuss.erpnext.com/t/error-no-such-file-or-directory-u-assets-frappe-css-daterangepicker-css/18633

**Comment by jwrober** [comment]
To add some color to this issue; it only started when I updated my dev environment from beta 7.2 to released 7.2. My prod 7.1.x environment does not exhibit this issue.

**Comment by rmehta** [comment]
Please clear your browser cache

The latest chrome for some reason does not automatically get fresh js files (maybe we need to pass a different parameter!)

**Comment by chungyan5** [comment]
i try to clear browser by 1) push SHIFT key and 2) reload together, but same result. Actually, i am going to my note page, it will comes out this error, then all my tags (on left side) are lost. 

My upgrading is manually using git to checkout a 7.1.29 tag at ~/frappe-bench/apps/frappe/ and ~/frappe-bench/apps/erpnext/ from 7.1.19 tag. I have a VM and a real production server using same method to upgrade, but VM is good, but production server is no luck by coming out this error.

**Comment by gvyshnya** [comment]
@rmehta : one more comment on this problem. We cannot see daterangepicker.css on the file path with erp next and frappe installations physically.

**Comment by chungyan5** [comment]
i try to clear browser by 1) push SHIFT key and 2) reload together, but same result. Actually, i am going to my note page, it will comes out this error, then all my tags (on left side) are lost. 

My upgrading is manually using git to checkout a 7.1.29 tag at ~/frappe-bench/apps/frappe/ and ~/frappe-bench/apps/erpnext/ from 7.1.19 tag. I have a VM and a real production server using same method to upgrade, but VM is good, but production server is no luck by coming out this error.

**Comment by rmehta** [comment]
Does this issue still come?

**Comment by chungyan5** [comment]
hi, i have not yet done anything and not know any solution, the problem is still there.

**Comment by jwrober** [comment]
I just updated to latest develop branch on my test instance, still not there. Can find a `datepicker.min.css`, but no `daterangepicker.css`.

`erpnext@satx-erpnext-p1:~/erpnext-dev$ find . | grep picker
./apps/frappe/frappe/public/js/lib/datepicker
./apps/frappe/frappe/public/js/lib/datepicker/datepicker.min.js
./apps/frappe/frappe/public/js/lib/datepicker/datepicker.en.js
./apps/frappe/frappe/public/js/lib/datepicker/datepicker.min.css`
