### ISSUE TITLE
[feature request] Timesheet auto-email reminders

### ISSUE THREAD

**Issue by joopdo** [frappe/erpnext#7337]
## Intro
Not all the staff fillout their timesheet daily. We need to remind them
daily by hand. I check this now by looking at the daily report.

It would be great if erpnext can automatically send a reminder to the people
who forgot to enter their details before a certain time.

## Example:
For instance. Employee 'joe' is marked as 'required to log time every workday'. I can set a time. e.g. 8PM and the system will sumup the missing dates for timesheet entry in an e-mail to the employee.

## Actual:
Right now we ctrl V the 'daily report' and paste this into excel. We then manually have to see which names are missing for the list and email them. Then... they might not do it again and it will be forever lost. I think this feature is a small addition but would make the timesheet much more valuable!

**Comment by joopdorresteijn** [comment]
Would be nice to get a response! (Paid customer)

**Comment by vrms** [comment]
+1 useful feature to have

**Comment by joopdo** [comment]
One year in and not even a response?

**Comment by tundebabzy** [comment]
Where do you suggest the flag can stay. I'm yet to figure out something.

**Comment by PawanMeh** [comment]
Maybe you can try setting up an Email Alert / Notification

![email_alert](https://user-images.githubusercontent.com/20460498/47211903-6234c680-d3b4-11e8-905c-e6697872632a.png)
