### ISSUE TITLE
Bug! Cannot make multiple purchase return (debit note) from original purchase invoice

### ISSUE THREAD

**Issue by ai-erp** [frappe/erpnext#7338]
We are making debit notes directly from original purchase invoice created.
Once there is already existing debit note in an item, we can no longer make another return for the same item. Below error message is showing:

![item has already been returned](https://cloud.githubusercontent.com/assets/16744099/21502705/22e46ed8-cc6b-11e6-8165-5c11d8fcdfc9.png)

**Comment by bhupennewalkar1337** [comment]
I checked this in my test account , it's working fine. From original purchase invoice, first i made debit note for half quantities and then again made debit note for remaining quantities for the same item. Each time item returned successfully.

**Comment by electropro** [comment]
@bhupennewalkar1337 Try the issue from the post below to see if it works on your account. On my account doesn't work.

Partial Purchase return error [#7390](https://github.com/frappe/erpnext/issues/7390)

**Comment by nabinhait** [comment]
@ai-erp Closing this, included issue #7390 under version 8 milestone.
