### ISSUE TITLE
Fetch ToDo description from corresponding task's subject

### ISSUE THREAD

**Issue by strixaluco** [frappe/erpnext#7340]
On ERPNext v7.1.28 / Frappe Framework: v7.1.29 if one creates new task (e.g. desk#Form/Task/New Task 1), the corresponding todo is being created, but its description says "To Do" only:
![todo](https://cloud.githubusercontent.com/assets/10875796/21519118/cade3afa-cd25-11e6-88f8-05bd3860bf74.png)

The suggestion is to fetch description from task's subject, so that list of todos will look more informative.

**Comment by KanchanChauhan** [comment]
I think this is already fixed in the latest version.

**Comment by strixaluco** [comment]
Looks like in ERPNext: v7.2.6 / Frappe Framework: v7.2.5 there is no todo being created after new task. Not sure if this is intentional, but anyway it's another issue, so I'm closing this for a while.
