### ISSUE TITLE
Custom Print Format (Doctype Timesheet) uses only standart print format for Print and PDF

### ISSUE THREAD

**Issue by spa49** [frappe/erpnext#7347]
hi all,
as of
ERPNext: v7.2.2
Frappe Framework: v7.2.4

when selecting custom Print Format in document printview (Timesheet) the custom format is displayed correctly

![timesheet custom azubi soll](https://cloud.githubusercontent.com/assets/16170816/21533107/87577b34-cd57-11e6-9399-80561796164c.PNG)

But when printing or generating PDF it switches back to standard 

see pdf
![timesheet custom azubi pdf](https://cloud.githubusercontent.com/assets/16170816/21533118/9ed075c2-cd57-11e6-8f38-0236a9019196.PNG)

seeprint
![timesheet custom azubi print](https://cloud.githubusercontent.com/assets/16170816/21533119/9ed22480-cd57-11e6-828b-211859ad7755.PNG)

I have nor checked other doctypes though

**Comment by rmehta** [comment]
Can't replicate. Can you confirm?

**Comment by partzsch** [comment]
as of 
master branch now
ERPNext: v7.2.5
Frappe Framework: v7.2.5

still the same
here how it should be 
![ts custom print format](https://cloud.githubusercontent.com/assets/16170816/21565387/69e27a36-ce97-11e6-9d53-4998b0f368c2.PNG)


here the wrong printview

![ts custom print format_wrong print](https://cloud.githubusercontent.com/assets/16170816/21565279/1a720eae-ce96-11e6-9da7-f0dcfccf42f2.PNG)

here the wrong PDF
![ts custom print format_wrong pdf](https://cloud.githubusercontent.com/assets/16170816/21565303/77c7ae7e-ce96-11e6-9312-f15419aff1d8.PNG)

works perfect for e.g. invoices, quotitions, delivery notes
but doctype Timesheet is buggy
It is not fetching the custom print format

**Comment by partzsch** [comment]
Solved!!!

The Name of the custom print format contained an ampersand "Azubi Tages P&P" if its named 
"Azubi Tages PP" it works fine.
Maybe it should throw an error message when the print format wants to be saved and it contains special  caracters
