### ISSUE TITLE
Bounty for new POS Interface design [now 910$]

### ISSUE THREAD

**Issue by aboganas** [frappe/erpnext#7348]
Here is a link for the bounty
[https://www.bountysource.com/issues/40458024-bounty-for-new-pos-interface-design](https://www.bountysource.com/issues/40458024-bounty-for-new-pos-interface-design)
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=40458024)](https://www.bountysource.com/issues/40458024-bounty-for-new-pos-interface-design-now-910?utm_source=40458024&utm_medium=shield&utm_campaign=ISSUE_BADGE)

Here's the full details for the interface (will be linked in the bounty). the full discussion in the forum is in here
 [https://discuss.erpnext.com/t/ideas-for-new-pos-interface/14638](https://discuss.erpnext.com/t/ideas-for-new-pos-interface/14638)
You can fine a prototype for how the interface should look like in here
[http://poserpnext.bitballoon.com](http://poserpnext.bitballoon.com)

And heres is the full details for the interface
**Overview and customer tab**
<a href="http://2.1m.yt/PeRvjg6.jpg" target="_blank"><img src="http://2.1m.yt/PeRvjg6.jpg" alt="ImgLand.net image" /></a>
1. customer tab (where can add new customers, see the customers in waiting list, edit ....)
2. Cart tab (where can select items for customer shopping cart)
3. payment details (where we process the payment)
4. Online (is green when the pos online or grey when its not,) in it u can see the non synced records in case the pos is offline
5. is the customer who's shopping cart is active and being served right now (clicking on hime will take you to the customers tab where you can switch to another customer from the queue or add new customer)
6- is search bar, where you can search for new customer in the system or quickly switch with customer in queue list 
7- is the form where you can add new customer.
8. is a list of customers in the queue, the customer being served is highlighted
9. clicking the customer name will switch him to be the active customer.
10. here u can edit customer information where the will be populated in 7 where you can do quick update
11. here you can cancel and delete the customer shopping cart and remove him from the queue list

**Search Bar**
<a href="http://2.1m.yt/IvI8ZDl.jpg" target="_blank"><img src="http://2.1m.yt/IvI8ZDl.jpg" alt="ImgLand.net image" /></a>
12. clicking on the search bar, you will see customer in waiting list where u can quick switch also u see add option where it switch u to customer tab, other wise you can search and select customer from the system

**Shopping cart**
<a href="http://2.1m.yt/sDCLy8T.jpg" target="_blank"><img src="http://2.1m.yt/sDCLy8T.jpg" alt="ImgLand.net image" /></a>
13. you are able to select the category of the items, and the item view will be updated to only show that category
14. is where u can scan barcode or enter manually
15. is a list of the items in the cart, where u can delete an item by clicking the X icon in the left, also selecting an item will highlight it and populate its information in 16 to update qty or discount 
16. here you can update qty or discount for item selected in 15 (notice the information about available qty and max discount is updated on the labels)
17. the payment button takes you to the payment tab

**Payment Tab**
<a href="http://2.1m.yt/C8DS8l.jpg" target="_blank"><img src="http://2.1m.yt/C8DS8l.jpg" alt="ImgLand.net image" /></a>
18. is a summary of the items in the shopping cart
19. you can quickly add payment for different payment methods available in the system
20. you can submit the payment, print the receipt or email it, or go back to edit cart, or after payment you can clear the customer

**Online Tab**
<a href="http://2.1m.yt/kLy8rEV.jpg" target="_blank"><img src="http://2.1m.yt/kLy8rEV.jpg" alt="ImgLand.net image" /></a>
21. you see all the transactions that haven't been synced in case the pos was offline

**Comment by Almax** [comment]
Hey, is somebody working on it ?

**Comment by addymuliady** [comment]
It seems @rmehta has started on it

**Comment by rmehta** [comment]
@aboganas do you want to check the implementation in `develop` branch? Can this issue be closed / claimed now?

**Comment by aboganas** [comment]
I post replay here for the backers to see
https://discuss.erpnext.com/t/new-pos-interface-please-contribute-to-the-bounty-now-910/14638/77?u=ganas

**Comment by aboganas** [comment]
@rmehta I think you can close and claim the bounty now. Thanks for the great work
