### ISSUE TITLE
Multiple print format selection issue, system list default print format twice if there are 2 print format built by builder

### ISSUE THREAD

**Issue by jaywks** [frappe/erpnext#7350]
https://discuss.erpnext.com/t/possibly-a-print-format-bug-only-able-to-select-default-print-format/18815

When having 2 print format built with print builder, system will list both with same name, the one which has been set to default.  Creating 3rd print format 'solve' this but not ideal, also the naming of print format does seem to have unexpected effect on this.

**Comment by kennethsequeira** [comment]
Closing the issue since this was raised for v7.2.1 which is no longer supported.

Also, this is no more replicable. If this is experienced by someone else, they can open a new issue with the details.
