### ISSUE TITLE
Stock Reconciliation - upload from CSV does not work

### ISSUE THREAD

**Issue by linbingqiang** [frappe/erpnext#7351]
Hello, there is a problem described as follow:
    In Stock Reconciliation module, I can not upload the stock reconciliation from csv templates. So I tried to upload the items using python scripts, as follow:
```
 frappe.connect("preproduction")
 sr = frappe.new_doc("Stock Reconciliation")
 sr.append("items",{
    "item_code": "100303674",
    "warehouse": "北京欢乐谷微仓 - 多点生活",
    "qty": 1,
    "valuation_rate": 10.90
})
```
but i can only create a stock reconciliation item in a stock reconcilication. 
How can I create many stock reconciliation items in a stock reconciliation using python scripts?
I can not find any api in frappe/erpnext document or api.
Thank you so much!
                                              yours
                                            bingqiang.lin

**Comment by epochc** [comment]
Lin: Yes, there seems to be a problem with the Stock Reconciliation functionality. @frappe: Please have this fixed. In the meantime, Lin, you can work around this by using a Stock Entry (Stock>Stock Entry>New>Purpose - Material Receipt) load up the valuation, submit and you are good to go.

If you have to reduce stock, please use Material Issue as the purpose of the stock entry.

If you have to change valuation, its more complicated and you have to calculate the value of the items based on your valuation method FIFO or Moving Average.

If you just have to synchronize numbers, go for the Material Issue or Receipt option. If you have to align valuations, please wait for Frappe to fix this issue.

Thanks

Jay

**Comment by linbingqiang** [comment]
Yes, I can create a stock reconciliation only with a stock reconciliation item using the doctype function append("items",{******}), it seems that there is not a function that to create a stock reconciliation with more stock reconciliation items?

**Comment by rmehta** [comment]
I just checked, and upload works alright.

@linbingqiang you can call `sr.append` as many time as you want!
