### ISSUE TITLE
Recurring Opportunities [feature req]

### ISSUE THREAD

**Issue by ssenyer** [frappe/erpnext#7352]
In some business opportunities are time based. I am the owner of a Calibration Laboratory. In service business opportunities can recurring itself depending on time periods.

So I need to adjust opportunities to recurring itself once in every single year until I delete it. I guess it should be common need in service business. (time based maintanences, time based inspections, time based calibrations etc.)

Regards.

**Comment by rmehta** [comment]
#6313

**Comment by kennethsequeira** [comment]
Should be achievable via **[Auto Repeat](https://erpnext.com/docs/user/manual/en/setting-up/automation/auto-repeat)**
