### ISSUE TITLE
[v7.2.3] Server Error on Last Update

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#7356]
Hello, since the last update  I keep getting this error when visiting the index page:

> 
> Server Error
> 
> Traceback (most recent call last):
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 52, in application
>     init_request(request)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 114, in init_request
>     frappe.local.http_request = frappe.auth.HTTPRequest()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/auth.py", line 47, in __init__
>     frappe.local.login_manager = LoginManager()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/auth.py", line 109, in __init__
>     self.make_session(resume=True)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/auth.py", line 167, in make_session
>     full_name=self.full_name, user_type=self.user_type)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/sessions.py", line 183, in __init__
>     self.resume()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/sessions.py", line 238, in resume
>     data = self.get_session_record()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/sessions.py", line 255, in get_session_record
>     r = self.get_session_data()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/sessions.py", line 270, in get_session_data
>     data = self.get_session_data_from_db()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/sessions.py", line 291, in get_session_data_from_db
>     self.device = frappe.db.get_value("Sessions", {"sid": self.sid}, "device") or 'desktop'
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 412, in get_value
>     order_by, cache=cache)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 456, in get_values
>     out = self._get_values_from_table(fields, filters, doctype, as_dict, debug, order_by, update)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 587, in _get_values_from_table
>     conditions, order_by), values, as_dict=as_dict, debug=debug, update=update)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 137, in sql
>     self._cursor.execute(query, values)
>   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
>     self.errorhandler(self, exc, value)
>   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
>     raise errorclass, errorvalue
> OperationalError: (1054, "Unknown column 'modified' in 'order clause'")

Any ideas?

**Comment by joezsweet** [comment]
Got same problem ...tried a fresh install with no luck. Opened an issue #7358

**Comment by rmehta** [comment]
Please update your system. Just pushed a fix.
