### ISSUE TITLE
Print Format: Sales Taxes & Charges (Table)

### ISSUE THREAD

**Issue by addymuliady** [frappe/erpnext#7361]
Sales Taxes & Charges (Table)

Description should be in line with the rest

Setting:
![image](https://cloud.githubusercontent.com/assets/21187126/21562079/2ff8af02-ceb0-11e6-915d-87e10248527a.png)

Outcome:
![image](https://cloud.githubusercontent.com/assets/21187126/21562074/1c9a4510-ceb0-11e6-8fd2-6368b1a23463.png)

**Comment by PawanMeh** [comment]
If this is still an issue in the standard template, you can re-open.
