### ISSUE TITLE
[v7.2.6] Error importing new BOM

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#7368]
Hello,

I keep getting this error when importing new BOM:

> unsupported operand type(s) for *: 'float' and 'NoneType'

This is the BOM I'm trying to import, already tried to change decimal separators with no luck.

![bom](https://cloud.githubusercontent.com/assets/18335894/21564641/c18860f0-ce76-11e6-9f01-9aa9395c2044.png)

any ideas?

**Comment by applepipe** [comment]
The problem persists, I still cant import any new BOM, even with round numbers on the float fields.

**Comment by shachiTakalkar** [comment]
![screenshot from 2017-01-10 15 23 31](https://cloud.githubusercontent.com/assets/22912205/21801701/c802c86e-d748-11e6-8f24-3cdc66455cd6.png)

I can replicate in my account.

**Comment by paddysw** [comment]
Same issue here.

ERPNext: v7.2.11
Frappe Framework: v7.2.9

Sample CSV in the attached zip file.

[BOM.zip](https://github.com/frappe/erpnext/files/704850/BOM.zip)

![bom](https://cloud.githubusercontent.com/assets/11889098/21938078/b1bc099c-d9b1-11e6-9508-837d8dde0ccc.png)

**Comment by applepipe** [comment]
The issue persists on 7.2.14, cannot create or import new bom

**Comment by paddysw** [comment]
@applepipe 
I managed to get the data imported by including some columns that are not marked as mandatory.

I played around with columns a little until I found the two I needed to add. If I remember correctly, they were Currency and Company, which both need a valid entry, even though these columns do not appear if you download the template with only mandatory fields selected.

My final import looked like this and there were no errors.
![image](https://cloud.githubusercontent.com/assets/11889098/22302732/030e1680-e328-11e6-8d33-086e4c20c829.png)

**Comment by applepipe** [comment]
hello @paddysw you are right, I just had to put company to import the BOM, but I need the BOM for all the companies, this wasn't mandatory before and now kinda make the things a little more complicated.

I hope the team can fix this soon, I wish I had the skill to contribute.

**Comment by nabinhait** [comment]
Made the Company, Currency and Conversion Rate fields mandatory. These fields are required to make multi-currency BOM.

**Comment by applepipe** [comment]
Hello @nabinhait is there any way that I can create a BOM without linking it to a specific company? I have more than one company making the same item, create one BOM for each company doesnt look an elegant approach.
