### ISSUE TITLE
Payroll Feature Request - Option to Exclude Earning/Deduction from Total

### ISSUE THREAD

**Issue by OneiricIT** [frappe/erpnext#7389]
**The option to exclude an earning or deduction entry from being calculated in the total**
Perhaps like a check box? Example being some earnings may not be directly deposited into the employees account (i.e. Superannuation in Australia).

**Comment by KanchanChauhan** [comment]
https://discuss.erpnext.com/t/payroll-employer-contribution/19456/5

**Comment by jwrober** [comment]
This will be a great feature if you all can add it in. In the US there are a number of employer paid items that should show on the payslip like health insurance.. Then there are other items like social security tax that both sides pay and typically the employer side does not show on the slip, but is paid at the same time.

**Comment by OneiricIT** [comment]
Hi @KanchanChauhan,
Would this feature be on the road map for v8 by chance?

**Comment by KanchanChauhan** [comment]
It will need more information like how the accounting entry will be handled for such salary components.

**Comment by jwrober** [comment]
We talk about that in the forum discussion linked above. It would work essentially the same as the other component types, but would not come out of the total salary.

**Comment by OneiricIT** [comment]
@KanchanChauhan Can you confirm whether this has been addressed in the below addition to v8.0.11? 

> Introduce the ability to specify in a Salary Structure that a component is statistical. This allows components to be used in calculations without being added/deducted from earnings deductions.

[https://github.com/frappe/erpnext/releases](url)

**Comment by KanchanChauhan** [comment]
@OneiricIT Unfortunately not yet. But another wave of changes in Payroll coming soon so might incorporate it in that.

**Comment by OneiricIT** [comment]
@KanchanChauhan Great, glad to see it is still on the map.

**Comment by ckosiegbu** [comment]
Does this PR https://github.com/frappe/erpnext/pull/8429 address this issue?

**Comment by jwrober** [comment]
For the most part yes. The only thing else I would like to see is the ability to flag some of them to be shown on the payslip as "employer contributions" just to show employees what we are paying for.

**Comment by OneiricIT** [comment]
If I am not mistaken (please correct me if I am wrong), it does not appear to actually contribute to payroll journal entries. So these are only statistical information that you can play with which are not reflected in any CoA. So I do not believe it addresses this request.

Also that appears to be feature I referenced on 18th April which @KanchanChauhan advised was not applicable to this.

**Comment by utkarsh-goswami** [comment]
#10900
