### ISSUE TITLE
Partial Purchase return error

### ISSUE THREAD

**Issue by electropro** [frappe/erpnext#7390]
Hello,

I tried to return some items from a Purchase Invoice, but I can't return it only if I leave the same quantity, otherwise it appears “Item A has already been returned”.

e.g in purchase invoice I have item A-10 pieces and item B-5 pieces. In the Purchase return I want to have only item A with -3 pieces which will be returned to my supplier and the rest of 7 pieces will remain in my stock.

Is this possible with ERPNext?

**Comment by rmehta** [comment]
@Arundhatii can you replicate?

**Comment by Arundhatii** [comment]
Can replicate the issue in my test account.

Did a Purchase receipt for 10 quantity and when making a return for 2, it throwing an error. Screenshot below.
![partial return](https://cloud.githubusercontent.com/assets/20164097/21717049/909dc0a2-d434-11e6-8e13-3fe8c5d1600c.png)

**Comment by ai-erp** [comment]
Bug! Cannot make multiple purchase return (debit note) from original purchase invoice #7338

**Comment by thosvesta** [comment]
This is a basic day to day purchase cycle in all retail businesses. Hence, I think this should be fixed asap.

**Comment by rohitwaghchaure** [comment]
Hi @electropro 

You need to add -3 in the received qty 

![screen shot 2017-01-30 at 9 34 44 am](https://cloud.githubusercontent.com/assets/8780500/22411978/b2f728e8-e6cf-11e6-8872-59a3dd47ec68.png)

**Comment by electropro** [comment]
Thank you for answer, but in my example I receive 10 pieces and I have to return only 3 pieces. This is not possible yet in ERPNext because of the "item already returned" error.

**Comment by KanchanChauhan** [comment]
Could not replicate the issue. Create a Purchase receipt and was successfully able to create 2 returns.
<img width="1175" alt="screen shot 2017-02-28 at 2 55 58 pm" src="https://cloud.githubusercontent.com/assets/16913064/23399501/7202b4c0-fdc6-11e6-9ce3-b7bb3c97ac5e.png">

<img width="791" alt="screen shot 2017-02-28 at 2 59 58 pm" src="https://cloud.githubusercontent.com/assets/16913064/23399543/96e51530-fdc6-11e6-9109-8df31eca4ee7.png">

<img width="819" alt="screen shot 2017-02-28 at 2 59 47 pm" src="https://cloud.githubusercontent.com/assets/16913064/23399545/98bd14e8-fdc6-11e6-8e9e-eb9b8c9f63f3.png">
