### ISSUE TITLE
importing items

### ISSUE THREAD

**Issue by yashwantc** [frappe/erpnext#7391]
i am trying to import items. it gives this error: Error for row (#35) "20EIDLLIC-50X" : {"message": "As there are existing transactions for this item, you can not change the value of Valuation Method

i am not making any changes to valuation method. in fact the field is empty

**Comment by rmehta** [comment]
Don't keep it empty, either drop the column or set a correct value.

**Comment by nabinhait** [comment]
fixed, will be released in the next version
