### ISSUE TITLE
Invoice does not update Stock...

### ISSUE THREAD

**Issue by robertbecht** [frappe/erpnext#7393]
I use Xmas break to do my yearly accounts...and found an issue (or bug)...It took me considerable time to point down where the issue is.
A graph of item quantities showed a strong increase of slope starting september 2016... Items in stock were stongly increasing...Well, exporting doscs to excel, comparing, checking etc i could not find where the issue was...Told my wife that probably quite a number of sales were not entered...
Finally identified the issue....
A number of my invoices show under "Make" delivery and under view only the accounts ledger, not the stock. Seemingly at random selection of invoices are first to be delivered...in order to update stock...

Some background:
I use the cloud version and have not updated setup/settings since several years...things work fine...
We have seriously started to use the new POS somewhere in August.... We use it from 3 to 4 different computers...I have only one POS profile defined...And the setting is "update stock". Also sales invoice (the traditional one) is default set to "IS POS" 

Tried to filter the invoices affected using the fields delivered by supplier and delivered Qty...these fields are empty>>> So i am not capable to filter the invoices that have this "special setting" ...and see whther it is for example related to a specific user... 

Am stuck.....Hope it can be easily resolved...

UPDATE....Can filter the records using the field "Update Stock" The cause of the erratic behavior remains unknown....Two out of three users, using different computers,.....May be related to the fact that the field "update stock"  has no default value......????

**Comment by nabinhait** [comment]
Resolved offline

**Comment by robertbecht** [comment]
Hi Nabin,
Thanks for looking at the issue....

However, don't see any change....Please advice...rgds robert

[image: Inline image 1]
