### ISSUE TITLE
If in sales invoice report the field "delivered by supplier" all reords are displayed multiple times

### ISSUE THREAD

**Issue by robertbecht** [frappe/erpnext#7395]
If in sales invoice report the field "delivered by supplier" all records are displayed multiple times (3-5 times)
If the field is removed display is normal again...Cloud user....

**Comment by rmehta** [comment]
@robertbecht is it because you see a separate row for each item?

**Comment by robertbecht** [comment]
Could be, but that should not be...One can basically toggle between single row and multiple row using the field "delivered by supplier" ....

**Comment by nabinhait** [comment]
@robertbecht If you select any columns from child table (Sales Invoice Item, Tax table etc. ), the output in the report will be multiplied by the number of rows  in the child table.
