### ISSUE TITLE
z index on autosuggest in grid when selected

### ISSUE THREAD

**Issue by RobertSchouten** [frappe/erpnext#7396]
the zindex on grid for autocompelete is off see timesheet activity type and scroll and it will drop behind add row

**Comment by rmehta** [comment]
@RobertSchouten will be great if you can share a screenshot while reporting such issues

**Comment by RobertSchouten** [comment]
while scrolling (ignore the cursor position)
![image](https://cloud.githubusercontent.com/assets/15826176/21755289/87470f44-d64c-11e6-9af3-98a304f8413f.png)

**Comment by RobertSchouten** [comment]
issue not fixed on current beta.erpnext.com
![z index issue](https://cloud.githubusercontent.com/assets/15826176/22909368/b3beab78-f28e-11e6-9deb-a5e635979ac2.gif)
