### ISSUE TITLE
Duplicate Items in Purchase Order

### ISSUE THREAD

**Issue by ruchin78** [frappe/erpnext#7401]
Option under Buying -> Buying Settings 
Allow Item to be added multiple times in a transaction 
is unchecked but it still allow add multiple duplicate items in Purchase Order.

![image](https://cloud.githubusercontent.com/assets/11055625/21717169/40408634-d435-11e6-97b0-6302a7a5e44b.png)

![image](https://cloud.githubusercontent.com/assets/11055625/21717170/427c9280-d435-11e6-80ae-7e9c3884f6ab.png)

Regards
Ruchin Sharma

**Comment by Arundhatii** [comment]
Replicated the issue. System issues a warning but allows to enter the items multiple times. 
![warning](https://cloud.githubusercontent.com/assets/20164097/21765217/7157f798-d68d-11e6-92ba-b0741b658b38.png)

**Comment by ruchin78** [comment]
However, I am sure you will take care of this but I hope after fixing it will take care of scenario where same items is requested in multiple Material Request by multiple departments in the company and when the Purchase Departments creates a Purchase Order of all such items, s/he will just add all those material request which are having same item, then in that case it should club the quantity of the item in a single row instead of stopping the user.

**Comment by KanchanChauhan** [comment]
For multiple Material request for same items, clubbing them together is not a good idea since they will have different Reference doctype, back tracing will be difficult. 
I think just the warning solves the purpose here.
