### ISSUE TITLE
[v7.2.6] Header name on print format builder

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#7403]
Hello,

I noticed that when I put a header name on print format builder that has more than one word after I save and reload just the first word is present on the print format, the rest after the space is deleted (sometimes it takes more than just one reload).

**Comment by rmehta** [comment]
Can you share a screenshot?

**Comment by applepipe** [comment]
This is the name I put on header
![screen1](https://cloud.githubusercontent.com/assets/18335894/21804865/eaa2f2e2-d70f-11e6-888c-b42a5be1c48c.png)

This is the print format, I'm using "_" now to bypass this
![screen2](https://cloud.githubusercontent.com/assets/18335894/21804866/eb26bb5e-d70f-11e6-9f76-5615496d49db.png)

**Comment by gavindsouza** [comment]
Closing this issue now.
