### ISSUE TITLE
Duplicate Entry for Single Invoice in Gross Profit Report

### ISSUE THREAD

**Issue by chaitraliw** [frappe/erpnext#7405]
In Gross Profit Report Sales Invoice entry gets repeated(same qty, selling amount, buying amount)
![screenshot from 2017-01-07 00 28 12](https://cloud.githubusercontent.com/assets/23652138/21729535/7866e12a-d471-11e6-8b30-89d4d193da9d.png)

To figure out this problem I have checked Sales Invoice, and found that it's because of I have two sales person in the Invoice
![screenshot from 2017-01-07 00 29 25](https://cloud.githubusercontent.com/assets/23652138/21729653/f36802a0-d471-11e6-810f-1eb62e0b0c72.png)

So my suggestion for this is that either spilt the qty, selling amount based on the sales person or show one entry only

**Comment by Olawale1** [comment]
I was actually about to post this issue already!

I think it's fine to show only one entry since there's an option to filter by Sales Person. The splitting is also okay if the team feels that's a better approach. Whichever way, this needs to be fixed

Cheers!

**Comment by nabinhait** [comment]
fixed via #7988
