### ISSUE TITLE
Account payable doesn't take Due Date

### ISSUE THREAD

**Issue by ariellempel** [frappe/erpnext#7407]
In the Account Payable report it doesn't tale the due date. Although, the due date appears correctly.
In the screen shot you can see the PINV-00008 that must appear on the 10-20 according to its dute date and PIN-00006 in column "20-30". Any help?.

![screenshot](https://cloud.githubusercontent.com/assets/24984078/21747390/f845d496-d543-11e6-8b62-8365c3408e2d.jpg)

**Comment by PrakashH** [comment]
@nabinhait Please check and fix. Replicated in test account.

**Comment by nabinhait** [comment]
@ariellempel As age is negative for these invoice as per due date, we have added these invoice under 0-10 columns.

**Comment by bemaze** [comment]
Hi, im with the same problem, how fix it? Im using the ERPNext: v7.2.31 VM Oracle Version
