### ISSUE TITLE
Field Recipient is not selectable when accessing email queue

### ISSUE THREAD

**Issue by ioweb-gr** [frappe/erpnext#7408]
Hello, I updated today and noticed a new bug when trying to access Email Queue 

When I try to access the page I get the following message:
`Field Recipient is not selectable` 

And everything is greyed out afterwards

![image](https://cloud.githubusercontent.com/assets/20220341/21749246/d2e3098e-d5a3-11e6-8dba-f91834434cde.png)

![image](https://cloud.githubusercontent.com/assets/20220341/21749262/1800a800-d5a4-11e6-8f49-ff7ce9cf79b3.png)

I tried resetting Email Queue and Email Queue recipient from Customize Form just in case but there were no customizations there. 

Any ideas what might cause this? Thanks in advance

**Comment by rmehta** [comment]
Cannot replicate maybe your bench did not migrate correctly. Try running `bench --site sitename migrate` and try again.

**Comment by ioweb-gr** [comment]
@rmehta Tried `bench --site <sitename> migrate` however it made no difference. I don't see any error logged either. 
Any suggestions how to troubleshoot?

**Comment by ioweb-gr** [comment]
@rmehta I understand completely that it's very hard to troubleshoot an issue that you can't replicate on your end. 
However without wanting to sound rude and in my humble opinion, a problem that can be found on a single system that seems to be application related and not system related (for example when you said that the bench might not have migrated correctly hints at an application error somewhere), it is possible that this will happen again in the future and it's a reason to investigate further and not to close the issue. 
If it happened to me, it could happen to someone else and there won't be a solution available or at least an idea on how to further troubleshoot.  

In any case I managed to track the problem and fix the issue by myself. However I have no clue what the underlying cause is or at what point this happened.
The problem was fixed after in table tabCommunication I noticed a record containing `reference_doctype` as `NULL` . I tried deleting that item and it worked.
