### ISSUE TITLE
[Enh] Employee Fields Missing

### ISSUE THREAD

**Issue by jwrober** [frappe/erpnext#7416]
I would like to make a suggestion for the Employee DocType. I've tailored this in my environment, but think it would be good for the core product.

1. Create a `employee_tax_id` field. In the United States this is the Social Security Number. However I would assume that other countries have something similar. Add settings in the HR Settings area to setup the format and label of this field. E.g. the length, any dashes and where those dashes reside and then of course what it's called for the country.  You could potentially add this to the country code picked during setup as these things are often set at the highest levels of a country's government. Then an admin would not have to setup them manually, they would just come pre-configured at install time.

2. Create a `bank_routing_no` field. All banks have a unique ID or number that represents them to the world or governing jurisdiction. This goes hand in hand with the bank_ac_no field. To do proper ACH or other electronic funds transfer (say for payroll every month), you need both the routing number and account number so your bank knows where to send the funds.

**Comment by KanchanChauhan** [comment]
We gave it a thought, but dint seem generic in nature. It will be very difficult to maintain the different id formats. And bank routing is also not widely used nowadays.

**Comment by jwrober** [comment]
Thank you for reopening this.

**Comment by jasonbrowne** [comment]
We to would like to see an employee_tax_id / Social security field added for employees.
