### ISSUE TITLE
Sync data between Project Task and Task table for custom fields

### ISSUE THREAD

**Issue by KanchanChauhan** [frappe/erpnext#7419]

**Comment by rohitk75** [comment]
Hi
This issue is not fixed tested on Release v7.2.27
I added a Custom field Employee to Tasks Doctype. It shows up on a form No Issues here
I added Custom Field Employee in Project Task Doctype. It shows in the Project Form but Data is is not saved and also not fetched.

Regards

Rohit

**Comment by KanchanChauhan** [comment]
Tested, works fine. Please do not comment on closed issues, always open new one.
