### ISSUE TITLE
Show Totals Button Not Working in Custom Reports

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#7424]
Hi,

The 'Show Totals' button isn't working in reports that were created using the report builder

![show totals issue](https://cloud.githubusercontent.com/assets/9269337/21802853/bc88787e-d727-11e6-9ed1-b8eb0879959a.png)

Kindly help resolve

Regards,

**Comment by Olawale1** [comment]
It appears this issue occurs once the Custom Report is Saved

**Comment by Devens** [comment]
+1
