### ISSUE TITLE
[v7.2.6] Problem on selection of cells on grid

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#7428]
Hello,

When I do things like select collums and add items to the grid the cells becomes static, I can't type anything, and I end up opening every row, this happens more often on selecting a new column and adding a new item to table.

**Comment by pratu16x7** [comment]
Could you elaborate the steps to replicate this with screenshots?

**Comment by pratu16x7** [comment]
Unable to replicate. Closing for now.
