### ISSUE TITLE
[WN-SUP05308] Scheduled & unscheduled maintenance

### ISSUE THREAD

**Issue by vikramnarayan** [frappe/erpnext#743]
## Am moving this to Github. Below is the mail chain. 

Vikram,

Thanks for the suggestions. Can make those changes.

You are right Support and Maintenance should be separate modules, but both are also not too big hence we have clubbed them. Can consider making them separate in the future.

Will request you to post feature requests on GitHub https://github.com/webnotes/erpnext/issues

best,
Rushabh Mehta

Twitter: @rushabh_mehta

-----In response to-----

Thanks Rushabh. I didn't check out support assuming it was only for service
industry. The maintenance schedule seems fine. Only a couple of queries
1. Can we change the schedule date column in the Scheduled section to
   schedule start and end time as the downtime may not necessarily be in days.
2. For customer issue case which you mentioned, the entire contact info
   section covers the customer. However this we would need the supplier info
   here. Do you think its possible for us to get supplier info in place of
   customer info?

Are you looking at incorporating this changes and perhaps moving it under
the manufacturing module as all manufacturing industries would have such
requirements and would be part of production planning?

Vikram

On Fri, Aug 9, 2013 at 4:43 PM, ERPNext Support wrote:

> Vikram,
> 
> For scheduled maintenance, you can create Maintenance Schedule (in
> Support) and For non scheduled maintenance you can create Customer Issue
> (should ideally be renamed as Maintenance Issue).
> 
> Does that work?
> 
> best,
> Rushabh Mehta
> Hi,

we have listed out the various machines used also as part of our item list.
However during daily manufacturing process, we end up having both scheduled
and unscheduled maintenance. So how can we track that.

For scheduled maintenance we would perform a standard activity which would
take time and would like to have that captured as part of our project.

For unscheduled maintenance, we would need some way in which we could
understand the impact on orders and also some king of a log which tracks
the machine, the issue, the supplier and expected time to repair. We
currently maintain a repair register in excel where this is captured. How
can we capture this in ERP Next?

Thanks,
Vikram

**Comment by umairsy** [comment]
You can create Custom Doctypes as per your requirements.
