### ISSUE TITLE
[v7.2.7] Still having issues on "Created on" filter

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#7431]
Hello,

Last week I raised this isse https://github.com/frappe/erpnext/issues/7394, and I'm still having the same Issue, "created on" filter isnt working, and the selection of date range doesnt show the real results.

**Comment by netchampfaris** [comment]
@applepipe 
Cannot replicate the issue. Maybe it is some other problem?
Are you facing this issue on beta.erpnext.com as well?

**Comment by applepipe** [comment]
apparently it was fixed in last updates
