### ISSUE TITLE
[v7.2.7] Related Filter not working properly

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#7432]
Hello,

I'm having a Issue on tracking related documents, on the Sales Order the number of delivery notes shown is 9, but when I click and it creates the filter on Delivery Notes, only one delivery note is shown, no aditional filters where used.

In report view all the delivery notes are shown, but on several lines (no collumm with item or anything that would cause this)

**Comment by KanchanChauhan** [comment]
Could not replicate. Can you share the screenshot. In my case it just creates one filter and that is on Sales Order. Screenshot below.
<img width="968" alt="screen shot 2017-02-22 at 3 45 12 pm" src="https://cloud.githubusercontent.com/assets/16913064/23207081/04155472-f916-11e6-871d-72fc02007fe5.png">

**Comment by applepipe** [comment]
Hello @KanchanChauhan 

I think I wasn't very clear describing my issue, the issue is not the filter, it is created as you said, but the information shown is incomplete in list view.

In my case only one delivery note is listed, in report view all delivery notes are listed but on several lines without any table column that could cause this effect, its hard to read.

Sales order shows 14 delivery notes and 6 not billed
![untitled1](https://cloud.githubusercontent.com/assets/18335894/23236086/aa87c95a-f936-11e6-9c01-fc6b44ce6512.png)

When I click to see the delivery notes only one is listed
![untitled2](https://cloud.githubusercontent.com/assets/18335894/23236122/c06900cc-f936-11e6-99eb-81d3ab077ae3.png)

In report view all the delivery notes are listed, but on several lines
![untitled3](https://cloud.githubusercontent.com/assets/18335894/23236151/d82e6670-f936-11e6-8d85-1113255acc45.png)
The columns are ID, customer name, date, created by, custom field interger, status and created on

None of the columns could cause this like table columns do.

**Comment by KanchanChauhan** [comment]
I just tested with 3 Delivery Notes only but everything seems to be working fine for me.
<img width="927" alt="screen shot 2017-02-27 at 5 38 49 pm" src="https://cloud.githubusercontent.com/assets/16913064/23360842/a8483414-fd13-11e6-8921-7bdb6703332b.png">

<img width="949" alt="screen shot 2017-02-27 at 5 37 58 pm" src="https://cloud.githubusercontent.com/assets/16913064/23360851/b16b18f4-fd13-11e6-9558-7d06b7a0e587.png">

<img width="1062" alt="screen shot 2017-02-27 at 5 38 32 pm" src="https://cloud.githubusercontent.com/assets/16913064/23360853/b3ce2b04-fd13-11e6-885c-b08b76b5827a.png">

**Comment by nabinhait** [comment]
@KanchanChauhan Probably I know the issue and can help you to replicate the issue.

**Comment by KanchanChauhan** [comment]
@applepipe Can you try clicking on 100 or 500 on the Delivery Note list view and see if other Delivery Notes for that Sales order becomes visible. It is not a valid solution but just wanted to be sure.
<img width="537" alt="screen shot 2017-02-27 at 6 14 56 pm" src="https://cloud.githubusercontent.com/assets/16913064/23361844/ae14a01c-fd18-11e6-85ce-47b9ad21f34e.png">

**Comment by applepipe** [comment]
Hello @KanchanChauhan you are right, if I click on 500 I can see all the delivery notes.

**Comment by rmehta** [comment]
@nabinhait @KanchanChauhan any update on this?
