### ISSUE TITLE
using smtp server on localhost without authentication (no password)

### ISSUE THREAD

**Issue by hfr** [frappe/erpnext#7433]
To use an smtp server on localhost without authentication e.g. postfix two changes in frappe/email/smtp.py are neccessary.

Line 62 need to be changed to:
    email_account.password = email_account.get_password(raise_exception=False)
Line 84 need to be changed to:
  email_account.password = email_account.get_password(raise_exception=False)

The changes simply prevent an exception in case no password is given and the SMTPServer class is taking care of the rest.

**Comment by lasalesi** [comment]
Related to https://github.com/frappe/frappe/issues/5016
