### ISSUE TITLE
frappe.new_doc and child table

### ISSUE THREAD

**Issue by bobzz-zone** [frappe/erpnext#7434]
HI,

i think its a bugs that i have set the child table but its always gving me error for no items with validation error...

i have tried : 
record = frappe.new_doc("Sales Invoice")
reocrd.update({...})
reocrd.append("items",{....})

ehn i make the item not required i could be success but when the item is manda tory i cant create it... even that i feel may items on the append...

Thanks

**Comment by rmehta** [comment]
Please share a trace or share your full code.
