### ISSUE TITLE
Sales return with discount, wrong math.....

### ISSUE THREAD

**Issue by robertbecht** [frappe/erpnext#7436]
Hi, had a POS generated invoice E112,50, and discount of 4.45 so they paid 108.05...Sales was returned...The sales return correctly ....states the amount paid (108.05) but i have to return 116.95....the discount was subtracted from the total instead of added.....

**Comment by rohitwaghchaure** [comment]
Hi @robertbecht 

In sales return, user returns the paid amount to the customer. 

Let's consider your case,
The invoice amount is 112.50, on which you given 4.45 discount. So customer paid you 108.05 
When a customer return the product, as he paid 108.05 you need to return the same amount. 

But in your case you also want to return discounted amount(which is not received) to the customer.
So as per my understanding, you need to return 108.05 + 4.45 = 112.50

Please brief your return policy for 116.95

**Comment by robertbecht** [comment]
Hi Rohit,
The 116,95 was the amount calculated by erpnext to be returned to custo,mer
![image](https://cloud.githubusercontent.com/assets/1532439/22031400/d2be297c-dce0-11e6-9ba1-99efa9e2501e.png)


now return

![image](https://cloud.githubusercontent.com/assets/1532439/22031504/15a9d04c-dce1-11e6-9761-749ff7b240c7.png)

**Comment by rohitwaghchaure** [comment]
Hi @robertbecht 

Put additional discount amount as -4.45 and check

**Comment by robertbecht** [comment]
yes than it tallies....but one would expect the software to have this intelligence :)

**Comment by rohitwaghchaure** [comment]
Hi @robertbecht 

Have fixed the issue, soon we'll release

**Comment by robertbecht** [comment]
thanx was a small issue...rgds robert
