### ISSUE TITLE
Simplified Time Tracking for Production and Sales Orders

### ISSUE THREAD

**Issue by ccavolt** [frappe/erpnext#7458]
While I think the current method of time tracking has its place for people offering professional services and manufacturing operations where keeping track of the exact amount of time spent on each operation is critical, it doesn't really fit a company (such as ours) that just wants to be able to track the total time spent on a production order (or a sales order, if a not insignificant amount of work is required to prepare the order for shipment, say for an order containing thousands of items).  Due to the small amount of time spent on some operations, tracking time for said operations wouldn't really make sense from an administrative perspective.

With that in mind, would it be possible to create a simplified timesheet (maybe the current timesheet could be referred to as the advanced option?) that only has the following fields and would apply to the order as a whole?
- Employee Name (to set predetermined costing rate for said employee)
- Sales order or production order it's applicable to
- Activity Type (Not required)
- Workstation (Not required.  If specified, the employee costing rate from above would override the wages field, but the other operating costs would be added to the employee costing rate, if they're specified)
- Time Logged (Preferably in minutes, not hours, so employees aren't having to do conversion math)
- Notes

@rmehta We're willing to pay for this feature, so a quote would be greatly appreciated.  Let me know if you need any additional information.

**Comment by rmehta** [comment]
@corbincavolt I will let @epochc collect all ideas and put it in one coherent proposal (he has promied to get it done by Monday). Lets do it with consensus from the communty.

**Comment by corbincavolt** [comment]
@rmehta Sounds good!  I've got a few more issues to write; I'll try to get them all done today.  Consensus from the community is definitely a good thing, and I'm open to suggestions if anyone has some.

**Comment by barredterra** [comment]
Any progress on this? I'm also thinking about building a simplified time sheet.

@ccavolt If you still need this, we can talk about development. Please text me at raffael@alyf.de .

**Comment by sharmanakul** [comment]
Has there been any progress on this?
