### ISSUE TITLE
Dynamically Updating Filters for Date (Today, This Week, This Month etc)

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#7460]
Hi,

Please add an option in filters for dates to be dynamically updated e.g 'Date = Today' or 'Date = This Week' etc. While these options exist in the current Date Picker, they are static and have to be updated manually every day. The idea is that the date in such a filter should always automatically update to the current date. This way, scheduled reports (e.g. Daily Sales Register) can easily be created with the report builder by adding such a filter

Thanks

**Comment by applepipe** [comment]
+1 for this!

**Comment by Devens** [comment]
+1 (already raised similar request in past).

**Comment by mukeshmv1** [comment]
+1

**Comment by superlack** [comment]
+1

**Comment by Olawale1** [comment]
I'd suggest these Dynamic Date Filters include the following:

1. Today
2. This Week
3. This Month
4. This Year
5. Last xxx period (e.g. Last 1 Week, Last 1 Month, Last 1 Year etc)

**Comment by joezsweet** [comment]
@Olawale1 Can you share a mockup? What date should be picked for "This Week", "This Month", "This Year"

**Comment by Olawale1** [comment]
Hi @joezsweet 

I think something basic using a similar format to the Date Range Picker in V7 should suffice. Of course, other ideas are most welcome

![dynamic date filters 1](https://cloud.githubusercontent.com/assets/9269337/25739089/399f03f0-3178-11e7-9c11-43ba3cb5f4e3.png)

Kind regards,

**Comment by superlack** [comment]
In favor of closing https://github.com/frappe/erpnext/issues/7147 if it's something that can be achieved behind the ux for auto-email reports (where dynamic ranges will not be clicked by the user after the first time)

**Comment by dvdl16** [comment]
+1 For this!!

**Comment by danielmorlock** [comment]
+1

**Comment by gbard** [comment]
+1

**Comment by dvdl16** [comment]
+1

**Comment by surajshetty3416** [comment]
You can use the **Only Send Records Updated in Last X Hours** option in auto email report. Just set 24 in that. Doing this, auto email report will only mail report with records of last day.

<img width="1196" alt="screen shot 2018-05-10 at 12 46 11 pm" src="https://user-images.githubusercontent.com/13928957/39857347-9d816d9e-5450-11e8-9e49-53dab1a4dee8.png">

This option can be used accordingly based on your requirements.

**Comment by dvdl16** [comment]
That may be a solution to some scenarios, but say for example I want to auto email all a list of sales orders with a Due Date of "Today". That is not possible with the solution you provided.

**Comment by alyjee** [comment]
+1 for this! would be really nice if we can have this dynamic dates feature as this support the concept of auto email reports.

**Comment by DercioBobo** [comment]
+1 for this

**Comment by rmehta** [comment]
https://github.com/frappe/frappe/pull/7313
