### ISSUE TITLE
 How to Fetch finincial year in Invoices and reset the series automaticallly

### ISSUE THREAD

**Issue by prashantam** [frappe/erpnext#7478]
I have two queries:
1.Will it be possible to have an automatic reset in all Invoice series starting from the new financial year?
2.I want to fetch the current financial year in invoice series (i.e: SINV-0001/16-17)
Currently we can only fetch the current year (i.e: SINV-0001/17 by ####./.YY) and have to reset the series manually.

Can we reset the series automatically otherwise that is very tough to remember all the doctype and reset the series.
Also it would be better if we can fetch the financial year in the series.

**Comment by harshit-30** [comment]
Fixed.
