### ISSUE TITLE
Unable to Reference Custom Field in Salary Structure Formula

### ISSUE THREAD

**Issue by mafrica** [frappe/erpnext#7480]
Having customized the  form salary structure employee with additional fields.  However, it is not possible to reference the new fields in the salary structure formula or conditions.

The customization is necessary add a variety of variable allowances and deductions.

**Comment by rmehta** [comment]
You can reference any field in formula / condition

**Comment by mafrica** [comment]
This link to the ERPNext discussion group shows the evidence of the problem.  It was created in response to your request for screen shots, but I was later advised to post the issue here..

https://discuss.erpnext.com/t/multiple-employee-variables-in-salary-structure/17962/13

**Comment by rmehta** [comment]
Always good to give the full information about the issue.
