### ISSUE TITLE
Contact + Address Redesign Issues

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#7482]
- [ ] Fix tests
- [ ] Fix Demo
- [ ] Fix Docs
- [ ] Address and Contact Report
- [ ] Rename / Delete for Address, Contact
- [ ] Request for Quote (update_contact)

**Comment by shenglong209** [comment]
Can't create new  Lead and Opportunity, this form did not show.

**Comment by KanchanChauhan** [comment]
@shenglong209 Please do not comment on closed issues, open a new one so that we can take action. Closed thread might get ignored.
