### ISSUE TITLE
[BUG] Item Report Weight UOM modification not possible

### ISSUE THREAD

**Issue by Tropicalrambler** [frappe/erpnext#7483]
If you load a Report for Items, and then Pick the Weight UOM column, it displays the column and data for each record, if you double click a specific record's Weight UOM empty box for editing, a window pops up, complete with "Close" and "Update" buttons, but there is no field displayed where one can enter the data.  This is a [BUG].
![screen shot 2017-01-13 at 11 30 50 am](https://cloud.githubusercontent.com/assets/16600935/21939082/cb04a8c4-d983-11e6-9868-8e5b93efd8d6.png)

**Comment by Arundhatii** [comment]
Cab replicate the issue in my test account as well.
Steps to replicate. Go to Stock>> Item >> Report builder>> pick the Weight UOM Column and  refersh
Double click the Weight UOM column >> Window Pops up
![weight uom bug](https://cloud.githubusercontent.com/assets/20164097/21955097/88a7c57c-da89-11e6-8019-9ab184f2598c.png)
