### ISSUE TITLE
Mobile App Navigation Problem

### ISSUE THREAD

**Issue by ccavolt** [frappe/erpnext#7486]
In the ERPNext for iPhone app, if you click on a related document, there's no way to go directly back to the document you were using previously.  In the browser, you'd just use the back button, but as far as I can tell, that functionality doesn't exist in the mobile app.  Would it be possible to add a close button that would close the current view and return to the previous view, essentially acting like a back button?  I imagine that this functionality could also be useful in the browser in the form of a "Save and Close" button for documents.

**Comment by kodybaker** [comment]
Sounds like you could really use an Android phone... ;)
The back button functionality is there.

**Comment by corbincavolt** [comment]
Haha, sounds like it!  If it works in Android, then do I need to create an issue in https://github.com/frappe/mobile instead of here?

**Comment by OneiricIT** [comment]
+1 on navigation issue.
