### ISSUE TITLE
Various issues with POS

### ISSUE THREAD

**Issue by robertbecht** [frappe/erpnext#7488]
I have several issues with the POS (cloud user)
1. Discounts are not subtracted from total...so they dont work......reported separately as this  seems to be a real bug.....)
2. Opened the configuration screen for POS and safed...is no longer possible without defining a user....///this may be an improvement not a bug but //// Does this mean that I do have to create a POS or every user????
3. I have a 4 non-synchronized invoices...I believe for identification /management the date should be shown in the list of non-synchronized invoice....The word draft is confusing...as these invoices are not listed as draft under the invoice list......!!!!  Use not "Not fully processed"or something like that....
4...If one loads such invoice...and processes a payment which date is used ???...the present or the date the invoice was originally created....A date field in the POS is required!!! to check this
5 If i synchronize ...nothing happens...
rgds robert

**Comment by Olawale1** [comment]
Hi @robertbecht 

Just thought to chip in my 2cents 

1. This seems okay at my end (self-hosted) so I'm guessing it's an ERPNext cloud thing which needs to be looked into

2. Yes, that's the way for now though an option to define a role-based POS Profile would definitely be helpful if you're managing a number of users. Hopefully this is in the pipeline. You could post this as an issue so it gets on the map (if not already there)

3. a) I completely agree that 'Date' is a critical missing column in the Offline Records list
    b) I initially suggested 'Pending' but I think Draft was used in conformity with ERPNext parlance
    c) 'Draft' offline records don't get synced to your invoice list until payment is made
    d) When payment is made but the resulting invoice cannot be submitted (i.e No Stock), it syncs but stays as 'Draft' in your invoice list

4. From my previous experience, the original date is used. The team will have to confirm if this is still the case

5. Not sure what you mean by 'nothing happens'. If you mean that the 'Draft' offline records are still there, then it's likely payment has not been made as explained in 3c above. You need to select that record and then make the payment before the record will sync

Hope this helps :)

By the way, I think you should consider posting this message on the forum for better discussion and then post specific confirmed issues like points 1, 2, and 3a as issues here on Github. Posting issues separately helps the team assign and manage them better

Cheers!

**Comment by robertbecht** [comment]
Hi @Olawale1 .... thanks for your detailed reply....

...is no longer possible without defining a user...>>> works like before...safe without user defined
...checked the date...yes original date is used,,,,
The discount came back....

YES....the DATE IN THE POS AND THE RECORDS OF LINE....

....indeed non paid invoices are not transferred....logically...on can submit them entering zero for all accounts...logical again,,,,But the word draft is a bit confusing....

Well let us hope that the bounty is soon enough to built a better POS  rgds robert
