### ISSUE TITLE
problem creating pdf when ipv6 is used

### ISSUE THREAD

**Issue by ioweb-gr** [frappe/erpnext#7489]
Hi,

I just bumped into a weird error today when trying to create a PDF from a Sales Invoice. All formatting pretty much disappeared from the PDF while it was working on HTML Print Preview. 

The change that triggered this problem was adding an ipv6 DNS Record for the domain hosting the erpnext site. 

`dig sitename A sitename AAAA +short`
yields the correct IPs so the website should be resolving correctly

I used the provided installer script on Ubuntu 16.04 to install ERPNext

I can work around this issue by editing precedence in /etc/gai.conf however that's a workaround not a solution. Could it have something to do with nginx configuration for ipv6?

**Comment by manassolanki** [comment]
Hi @ioweb-gr ,
Are you still facing error? If yes, please comment the error traceback.

**Comment by ioweb-gr** [comment]
Hi I didn't see any errors, I just noticed my template looked defaced on the pdf. I'll update to latest version later today and see if the problem persists and report back. 

There was no notification on the error logs either.

**Comment by ioweb-gr** [comment]
The problem still occurs in ipv6 . No errors whatsoever in the logs.

**Comment by manassolanki** [comment]
Could you explain via screenshots or some gif how the pdf are distorted? I think this is print format issue

**Comment by ioweb-gr** [comment]
@manassolanki 

This is definitely not a problem with the print format. It seems to me that bootstrap formatting is getting removed from the print formats. 

A simple change in  /etc/gai.conf to set precedence for IPv4 instead of IPv6 fixes the same PDF file. I can't see any way that changing domain name resolution from IPv4 to IPv6 would affect any type of print format I wrote. 



I can provide a sample PDF produced correctly using IPv4 and a corrupted PDF using IPv6 however I can't do it publicly due to it containing sensitive information. If there is a secure location where only the core team has access to provide it or an ERPNext core team email I have no issue providing it then.

Here are the images with the sensitive areas blacked out but it won't be of much help. 

Except for the alignment and some styles which you can obviously see has changed, there are also missing assets. 

with /etc/gai.conf at IPv4 

![image](https://user-images.githubusercontent.com/20220341/27077790-f43f54f0-5039-11e7-9198-faed18b1a649.png)

## Correct one looks like this

![qtn-00028](https://user-images.githubusercontent.com/20220341/27077633-662defa0-5039-11e7-9201-60a39d297aa2.jpg)
 
with /etc/gai.conf at IPv6

![image](https://user-images.githubusercontent.com/20220341/27077766-dc04ce7e-5039-11e7-9ed9-bd66aff2bd9b.png)

## Corrupted one looks like this

![qtn-00028-corrupted](https://user-images.githubusercontent.com/20220341/27077644-6ee04f08-5039-11e7-843e-d76542128f54.jpg)

**Comment by rmehta** [comment]
@ioweb-gr thanks for the details. How does it look in the full-page view?

Are you using any external css files? it might be related to those. Frappe uses wkhtmltopdf to render the images, so I am not sure we can do anything in this matter.

Closing this for now.

**Comment by ioweb-gr** [comment]
Hi all styles I used were inline. I think mainly bootstrap wasn't included correctly. Because wkhtmltopdf is used that's what led me to believe it's a problem with the vhost setup for ipv6. I think if this is closed there should at least be a footnote in documentation that there is a problem with ipv6 configurations on how to work around it as I did.

**Comment by ioweb-gr** [comment]
Also in browser it looks ok. Just pdf creation fails
