### ISSUE TITLE
No 'Remove' button for items selected in POS 

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#7492]
Hi,

There is currently no 'Remove' button for items selected in the POS screen. For example, if a customer initially selects 10 different items and then decides he doesn't want 1 or 2 items after they have been scanned (maybe he doesn't have enough money to pay for all the items), there is no way to remove those items from the list. The cashier has to start a new invoice and scan all items again if they are serialized items. The initial invoice then has to go to the offline records from where it can eventually be deleted

It'll be much more efficient to have a 'Remove(x)' button beside each row of items selected in the POS screen so that any item no longer wanted or entered wrongly can be removed from the list with one click. For non-serialized items, they can currently be removed by reducing the quantity to zero but this is not the most efficient approach when it comes to POS

Regards

**Comment by nabinhait** [comment]
You can remove the item by setting quantity **zero** using "-" button or manually. It will remove the item from the invoice.

**Comment by Olawale1** [comment]
Hi @nabinhait, trust you're doing great. As explained in my post, that approach currently does not work for serialized items and it's also not the most efficient approach for a POS. Removal of items from the list should be one click only (and no typing on keyboard if it can be avoided)

Regards
