### ISSUE TITLE
List of Reports are displayed even when the user doesn't have access to them

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#7493]
Hi,

When a user is restricted to a report using the permission manager, all the other reports are still displayed as options even though he/she cannot view the contents. A user should only see a list of reports for which he has permission rather than seeing a myriad of reports and getting a 'Not Permitted' error when he clicks on them!

Regards

**Comment by KanchanChauhan** [comment]
Should be fixed via https://github.com/frappe/frappe/pull/2699
