### ISSUE TITLE
Ability to use supplier as customer 

### ISSUE THREAD

**Issue by vishwajeet** [frappe/erpnext#7497]
We have business model where we raise bills to our supplier and in some cases they raise bills to us.
I don't want to create two entries one for customer and other for supplier as in that case reconciliation would be pain.

Say I raise a vendor a bill of 10k and he raise me a bill 10k so ideally net outstanding should be zero but if we have two entries than it will not be the case and would require manual reconciliation and creation of the statement.

Just for your information Odoo does this already, may be a food for thought for ERPNext team to introduce concept of party and allow a party to have customer as well supplier types.

Refer the forum discussion here https://discuss.erpnext.com/t/ability-to-use-supplier-as-customer/19336

**Comment by Devens** [comment]
+1

**Comment by mhbu50** [comment]
+1

**Comment by moosabukhamsin** [comment]
+1

**Comment by vishwajeet** [comment]
@rmehta Can you or someone from you team please look into this and comment of feasibility of this? As this is deciding factor for us to use ERPNext or not.

**Comment by rmehta** [comment]
@vishwajeet please evaluate ERPNext as is. If you want this urgently, start a bounty or get some one to fix it for you.

**Comment by vishwajeet** [comment]
@rmehta Thanks for quick response. I have already evaluated it as is but this feature is blocker for our business requirement.  Bounty and all is fine I can do that but what's the high level effort to get this change done? I am willing to take the efforts for development as well but first want to gauge how deep is the assumption of the supplier and customer roles.

**Comment by me2ne** [comment]
@vishwajeet you can be sponsor to add this feature to erpnext , i can contribute $100 as gift if they add this feature in ERPNEXT . Hope we can find some more sponsor to contribute for this feature .
Regards

**Comment by vishwajeet** [comment]
@me2ne Thanks for your support and encouragement. I discuss this with a company working on ERPNext for last 6-7 years and they have given me a feedback it's a sizable amount of work to get this implemented.
So I am not sure if it will be worth the time and effort to get this done, as it stands today I may end up using Odoo. If I get this developed I will surely give it back to community. 
Cheers

**Comment by rmehta** [comment]
Post your bounty here! https://www.bountysource.com/issues/40993383-ability-to-use-supplier-as-customer

**Comment by ai-erp** [comment]
i have posted more details needed in this post #7538

**Comment by me2ne** [comment]
I agree with @ai-erp .  post #7538 has more details   , let's close this post and i'll post $100 bounty on post #7538. I hope other ERPNEXT user also contribute for this feature .

**Comment by vishwajeet** [comment]
@me2ne @ai-erp  lets do it. I will also commit $100 to start with.

**Comment by vishwajeet** [comment]
I have added bounty here https://www.bountysource.com/issues/41121617-feature-suggestion-customer-and-supplier-as-one-party

**Comment by me2ne** [comment]
hi @rmehta , can you please help to add this post to bounty , i don't know how to add

**Comment by me2ne** [comment]
Thanks @vishwajeet  , how we can add github post to bounty ?

**Comment by vishwajeet** [comment]
@me2ne it's added automatically I have used #7538 as suggested by you.

**Comment by vishwajeet** [comment]
Not sure how to merge two issues. We can close this one and move everything there.

**Comment by yashodhank** [comment]
closing this thread as more details are on #7538
