### ISSUE TITLE
Print not working in POS

### ISSUE THREAD

**Issue by thosvesta** [frappe/erpnext#7502]
Clicking on "Print" button nothing happens in POS.

![image](https://cloud.githubusercontent.com/assets/18680544/21977098/6670da22-db9a-11e6-9afb-4c79942e713c.png)

**Comment by Olawale1** [comment]
This is very likely the same issue I reported on the forum (see link below)

https://discuss.erpnext.com/t/pos-print-function-fails-from-time-to-time/19190

Whenever it happens, a receipt cannot be printed for the customer and this is quite an issue!

Regards,

**Comment by thosvesta** [comment]
I tired different servers and fresh installs, im able to reproduce this issue using latest release. Please see if anybody else is able to reproduce the same issue. Open POS 》select items 》 click pay now》 Click on Print 》 nothing happens.

**Comment by thosvesta** [comment]
I tired different servers and fresh installs, im able to reproduce this issue using latest release. Please see if anybody else is able to reproduce the same issue. Open POS 》select items 》 click pay now》 Click on Print 》 nothing happens.

**Comment by rohitwaghchaure** [comment]
Hi @thosvesta 

Thanks for reporting an issue. 
We have identified and fixed the issue, soon we'll release the fix

**Comment by Aintzanemasa** [comment]
I have the same issue since 13th of January, I'm glad this is an issue and not my fault. Looking forward for the fix!

**Comment by thosvesta** [comment]
Thanks for fixing it.
