### ISSUE TITLE
No bold font (or highlight) for balances of accounts selected in Chart of Accounts

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#7507]
Hi

In previous versions of ERPNext, whenever an account was selected in the Chart of Accounts, the corresponding balance became bold-type so that it was easy to identify. In recent versions, that feature seems to be missing and this makes it quite difficult to immediately identify which balance belongs to which account

![chart of accounts bold balances issue](https://cloud.githubusercontent.com/assets/9269337/21981577/6eaeb224-dbe8-11e6-99b7-d536a2646cba.png)

Regards

**Comment by ahmadRagheb** [comment]
i modifed it to this look :+1: 
![created file](https://cloud.githubusercontent.com/assets/23044675/21982353/9359c9c2-dbf4-11e6-9333-0f910b7a2ced.png)

**Comment by netchampfaris** [comment]
frappe/frappe#2653
