### ISSUE TITLE
Salary Slip troubles

### ISSUE THREAD

**Issue by superlack** [frappe/erpnext#7512]
I have my company set up to pay employees solely based on timesheets, but when using "Salary Slip" in ERPNext, I'm encountering troubles and possible bugs.  

- With the Salary Structures set up correctly, creating a new Salary Slip immediately throws "Please Set Payroll Frequency First"
- Choosing Payroll Frequency first and then setting start and end dates gives "No active or default Salary Structure found for employee ------- for the given dates", although setting the start/end dates before does successfully bring up relevant timesheets.

Of course, Process Payroll doesn't create any salary slips either.  Is it possible to easily use the payroll functions based off of timesheets as it is intended?  Fortnightly payroll and automatic processing seem like very great features

**Comment by KanchanChauhan** [comment]
Thanks for reporting the issue, it has been fixed, will be merged soon.
