### ISSUE TITLE
issue with period closing voucher

### ISSUE THREAD

**Issue by robertbecht** [frappe/erpnext#7516]
On jan 10 216 I made some corrections for 2014 using the PCV...I messed up the dates....Transaction date is correct 31-dec-2013,,,,Postin date and fiscal year are not....they are both entered as 2016

![image](https://cloud.githubusercontent.com/assets/1532439/22037625/381034f2-dcf8-11e6-9180-d44719171657.png)

running the ledger I see the correction is posted on 10 jan 2016....
![image](https://cloud.githubusercontent.com/assets/1532439/22037705/8ce8c278-dcf8-11e6-93f7-f431b795baab.png)

How to correct this????      

Must have misread....But Transaction date is quite misleading,,,,,,,
umairOct '14
Hi,

Posting Date will be when this entry should be executed. If your Fiscal Year ends on 31st December, then that date should be selected as Posting Date in the Period Closing Voucher.

Transaction Date will be Period Closing Voucher's creation date.

Closing Fiscal Year will be an year for which you are closing your financial statement.

Closing Account Head will be the ledger where difference on Income and Expense will be booked. Its mostly Reserve and Surplus Account, located under Liability group.

**Comment by nabinhait** [comment]
I think this is fixed as per discuss post, closing this. If you are still facing the issue, please reopen.
