### ISSUE TITLE
Print labels from purchase order

### ISSUE THREAD

**Issue by Aintzanemasa** [frappe/erpnext#7523]
Hi,
I want to know if there's a way to print labels for every item I get with my purchase order, for example:
![compra proveedor erpes](https://cloud.githubusercontent.com/assets/25102831/22066224/49e63c78-dd8c-11e6-8632-58b9c1092a4b.jpg)

So, from this order I want to print two labels for "nu380" an three labels for "libro atrevete..." and the labels may contain the sale price, code bar, and a few information. How can I create a template with this labels?

Thank for your suport.

**Comment by rmehta** [comment]
You can make a custom HTML template for labels

https://frappe.github.io/erpnext/user/manual/en/customize-erpnext/print-format
