### ISSUE TITLE
Rename Stock Reconciliation - Allow option for Opening Stock

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#7528]
Since Stock Reconciliation can be used for multiple purposes, we should have an option to select purpose. If purpose is selected for updating Opening Stock Balance, in value in the Stock Adjustment field should be set as "Temporary Opening".

**Comment by Devens** [comment]
+1

**Comment by nathan-eden** [comment]
I use stock reconciliation when I do periodic stock counts (ex: end of year reconciliation).
