### ISSUE TITLE
Query Reports headers don't always get translated

### ISSUE THREAD

**Issue by dalwadani** [frappe/erpnext#7534]
Reports with type "query report", where columns are defined in the query field in the json file, don't load translation of these values to the cache, frappe._messages. However, if the values are already in the cache, it will be translated correctly.
![screen shot 2017-01-17 at 17 12 16](https://cloud.githubusercontent.com/assets/4618082/22107767/a38f0dca-de47-11e6-9385-617f8c9b9d29.png)

**Comment by michaeleino** [comment]
Any solution here?
