### ISSUE TITLE
[Feature] Customer and Supplier as one Party [Bounty]

### ISSUE THREAD

**Issue by ai-erp** [frappe/erpnext#7538]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=41121617)](https://www.bountysource.com/issues/41121617-feature-suggestion-customer-and-supplier-as-one-party?utm_source=41121617&utm_medium=shield&utm_campaign=ISSUE_BADGE)

In the real world of retail/wholesale business, most likely, some customers are also our suppliers. In this case, we are making invoices and bills for the same party… That is why is better to have just so called Party with the option to make it customer and supplier.

In this case, for reconciliation purposes, supplier and customer Statement will be merged for the purpose of getting net of the actual payable or receivable for reconciliation as same in Odoo…  But for reporting purposes, if invoices and bills are not yet paid, it still should be shown as separate accounts in the financial statements as payable(in liabilities section) and receivables (in asset section)…

In getting the statement showing both balances of receivables and payables, there should be a button which can be used to offset amount with invoices and bill in case the party would want to pay only for the net outstanding balance for all invoices and bills. When clicking the button, it should automatically go to a journal entry wherein invoices and bills can be allocated to each other in order to allocate amounts which should take effect the offsetting of amounts to apply the receivables to payables and vice versa...

**Comment by vishwajeet** [comment]
I have added bounty https://www.bountysource.com/issues/41121617-feature-suggestion-customer-and-supplier-as-one-party

**Comment by vishwajeet** [comment]
We have business model where we raise bills to our supplier and in some cases they raise bills to us.
I don't want to create two entries one for customer and other for supplier as in that case reconciliation would be pain.

Say I raise a vendor a bill of 10k and he raise me a bill 10k so ideally net outstanding should be zero but if we have two entries than it will not be the case and would require manual reconciliation and creation of the statement.

Just for your information Odoo does this already, may be a food for thought for ERPNext team to introduce concept of party and allow a party to have customer as well supplier types.

Refer the forum discussion here https://discuss.erpnext.com/t/ability-to-use-supplier-as-customer/19336

**Comment by me2ne** [comment]
I pay already 100$ in bounty  , from attached picture may be developer can get more idea . 
![screen shot 2017-01-19 at 8 00 48 pm](https://cloud.githubusercontent.com/assets/6168204/22114391/c05c3640-de82-11e6-80cc-a0f1c0f49165.png)

**Comment by me2ne** [comment]
Thanks @ai-erp and @vishwajeet . if some one have any suggestion or experience what need it for this feature .please share here ,

**Comment by yashodhank** [comment]
#7497

**Comment by yashodhank** [comment]
Place Bounty here > [![Bountysource](https://api.bountysource.com/badge/issue?issue_id=41121617)](https://www.bountysource.com/issues/41121617-feature-suggestion-customer-and-supplier-as-one-party?utm_source=41121617&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by vishwajeet** [comment]
@rmehta As per you what should be the target of the bounty ?

**Comment by rmehta** [comment]
Lets finalize the design first. Anyone want to make a UI mockup?

**Comment by me2ne** [comment]
I'm Not technical , is it help if i make some thing is paint of excel how should show statement ?

**Comment by vladucoju** [comment]
This could be some example. 

![1](https://cloud.githubusercontent.com/assets/9590909/22281819/3875bc64-e2d9-11e6-869a-105e1aad87a5.png)
1. Create new Subject (customer, supplier, warehouse...)
2. Populate general fields.
3. On the left menu check what are you opening
4. You could select both (supplier and customer)
5. Option to open warehouse is to check warehouse and when you click on the name on the right side will be mask for warehouse settings.

That is some short explanation. 
This is much easier for user because he will have small scope of viewing.

**Comment by Albatros79** [comment]
I am also ready to make contribution 100 usd.
this feature is vital.
we also have another request for issueing a company multi currency invoices 
there is a company account , it cannot be more than one now but easily it can be multiple according to currency of the invoice you issued .
we have to create different customers now . but for the tracking it is not easy.

**Comment by ofcaah** [comment]
This is not only messy, but also probably illegal in many jurisdictions, that require you to report sales and purchases. Anyway, I'm also willing to chip in $100, should someone say that they'll do it, post some timeline and promise a way out of current mess by merging split accounts.

**Comment by me2ne** [comment]
in most of good accounting software  it's possible supplier and customer work as one party , it's happened one company is supplier and customer in one system , 
for example in Odoo there is option for that .

**Comment by aambernath** [comment]
any updates regarding this?

**Comment by faztp12** [comment]
We had a similar requirement and we did the following
1. Define the party both in Customer & Supplier
2. New doctype Consolidation
 Where a consolidation code is given to the this pair of Customer & Supplier.
3. We made a report Consolidated Statement of Accounts

https://github.com/consoleerp/consoleerp_erpnext_client/tree/master/consoleerp_erpnext_client/consoleerp_erpnext_client/report/consolidated_statement_of_account

Hope it helps somebody :)

**Comment by jigartarpara** [comment]
Any progress on it?

**Comment by ofcaah** [comment]
Hm, I suppose it will be quite difficult to turn this dead-end decision around for compatibility reasons. My idea/suggestion would be creating a third entity, which then could become a supplier and/or customer. Accounting would need an overhaul to refer directly to this entity to include transactions made as both a supplier and customer, but other than that it would prevent any major compatibility problems. Everything would work as is, except company name, addresses, tax id would be kept in one place and they would not go out of sync. Over time, in a version or two, maybe this could be cleaned up.

Common information would be linked to this new entity, along with information if it's customer, supplier, website user, transporter, or whatever else this new thing may be of use for, and then link customer and supplier objects to this entity. Probably some internal data duplication (or some view magic in database) would be required to avoid breaking everything, especially external add-ons. Tough cookie. ;)

**Comment by Olawale1** [comment]
Hi ,

Any updates here?

Kind regards,

**Comment by umairsy** [comment]
Being worked upon on these lines https://github.com/ahmadpak/doubleledger

**Comment by IcedQuinn** [comment]
this still has an active bounty listed, which should probably have something done with it.

**Comment by ashin-kk** [comment]
Hi, is this feature available now? Can we use this on frappe cloud?

Kindly guide how this will affect the ledger of the respective party.
