### ISSUE TITLE
Error when the navigation links in the breadcrumb are clicked

### ISSUE THREAD

**Issue by ajaymathangi** [frappe/erpnext#7542]
We have been using ERPNEXT for the past 3 months and from the past week, we are getting the following error when a navigation link on the breadcrumb is clicked.

Something went wrong
Close
Server Error: Please check your server logs or contact tech support.
Traceback (most recent call last):
  File "/home/frappe/benches/bench-2017-01-13/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/benches/bench-2017-01-13/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/frappe/benches/bench-2017-01-13/apps/frappe/frappe/handler.py", line 40, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/benches/bench-2017-01-13/apps/frappe/frappe/__init__.py", line 897, in call
    return fn(*args, **newargs)
TypeError: get() takes exactly 1 argument (0 given)

Regards,
Ajay

**Comment by yashodhank** [comment]
@ajaymathangi as error suggest, you should check your web server log for more details.
It usually happens when you have low resources such as low disk IO, Insufficient CPU, Insufficient Memory etc. causing scripts to timeout before processing happens.

Best approach would be troubleshooting your server and logs, post your further findings here.

Thank you

**Comment by ajaymathangi** [comment]
@yashodhank 
We are using a subscription with ERPNext hosting our instance.  Our Subdomain is theoryy.erpnext.com.

Regards,
Ajay

**Comment by yashodhank** [comment]
@ajaymathangi get in touch with support [at] erpnext.com
Thanks for reporting issue.

**Comment by nabinhait** [comment]
@ajaymathangi Are you still facing the issue?
