### ISSUE TITLE
Mapping Customer with a Group

### ISSUE THREAD

**Issue by pgarodia** [frappe/erpnext#7552]
Hi,

In our case, we do not have territories. We have teams whom we call groups. Our customers are mapped to a group. So all orders from that customer automatically get assigned to that group. How can I replicate this in the system?

Thanks,
Prateek

**Comment by joezsweet** [comment]
did you check Customer Group and Sales Partner?

**Comment by pgarodia** [comment]
Hi,

I don't know what they are. Can you please elaborate?

As per ERPNext this functionality does not exist. So they asked me to put
it up as a suggestion.

Regards,
Prateek

**Comment by joezsweet** [comment]
check under Selling module, there are both Customer Group and Sales Partner ..i'm not sure what u want to do ..i just saw customer can have a Customer Group and or Sales Partner ..

**Comment by rmehta** [comment]
@pgarodia do you have a solution or a specific feature requirement?

**Comment by pgarodia** [comment]
Specific feature requirement.
