### ISSUE TITLE
[BUG] BOM Rate does not consider UOM

### ISSUE THREAD

**Issue by bcornwellmott** [frappe/erpnext#7556]
When looking up the rate for BOM Items, the system does not look at the Stock UOM for the BOM Item and convert the quantity to the default UOM before plugging in the rate. As a result, the rate listed is in the default UOM of the item, which can be different from the stock UOM.

**Comment by nabinhait** [comment]
As per our discussions on a recent pull request, the qty in the BOM Item table is defined as per Stock UOM. And also, Default UOM and Stock UOM refers to the same in context of ERPNext.
