### ISSUE TITLE
gh_pages link missing/broken

### ISSUE THREAD

**Issue by fmorato** [frappe/erpnext#7562]
`source_link` variable is broken in https://frappe.github.io/erpnext//install.html 

I don't know how to fix. File line with the error:
 https://github.com/frappe/erpnext/blob/gh-pages/install.html#L143

Are the gh_pages auto generated somehow?

**Comment by KanchanChauhan** [comment]
Fixed via https://github.com/frappe/erpnext/commit/993358d5d791c14ae7dc8a2ac79f404d19de2690
