### ISSUE TITLE
Website view for ERPNext Demo

### ISSUE THREAD

**Issue by peefour** [frappe/erpnext#7563]
why is there no website view in the erpnext demo? It redericts to the login page.
 is there a way to view the website? maybe provide a link for that ?

see https://discuss.erpnext.com/t/no-website-view-in-erpnext/19615

**Comment by umairsy** [comment]
Hello,

We request you to create a free trial account to experience this feature. Hope you will understand that allowing Website access for the demo account will allow users to publish any sort of data in public. In cases, data published over demo website inappropriate and harmful for the community.
