### ISSUE TITLE
Email reply setup question

### ISSUE THREAD

**Issue by sgomezsym** [frappe/erpnext#7572]
When you enable outgoing email in ERPNEXT and setup different email address that the user, when clients, vendors, etc.. receive the email should reply to this address and not user address.

For example: my user sgomez@sym.....; setup address for outgoing emails comercial@sym...

Clients, vendors will receive the email as comercial@sym... that is correct, but when they want to reply to this email in outlook or other email system, directly appear sgomez@sym... not comercial@sym...

I hope is clear enough.

Thank you.

**Comment by PawanMeh** [comment]
1. If you set up smtp & send an email as some id, people would reply to the same id, I am not sure how the system can control what address a person is going to reply to. 
2. Maybe you can try to use cc, in the email list so they get your email id too.

Closing this for now, you can re-open with more specific details.
