### ISSUE TITLE
Add Email Sent Notification Field to RFQ Supplier

### ISSUE THREAD

**Issue by bcornwellmott** [frappe/erpnext#7574]
Currently, there is no easy way to tell whether an RFQ email has been sent to a supplier. You can see that an email has been sent by looking at the comments, but you can't tell who it's been sent to, and you can't tell from any report or list filter. 

I think a great enhancement would be having a field in the RFQ Supplier doc that is read-only and indicates whether an email has been sent. It could either be updated when the Send Supplier E-Mail  button is pressed (if the Send email button is checked off), or when the email is confirmed sent (so that if an email failed to send it would not indicate as being sent). I think either option would be a great addition.

**Comment by kodybaker** [comment]
I would suggest this not be a read-only field, as one may have chosen to send the email offline (outside of ERPNext), yet it should still be reflected in the status.

**Comment by Devens** [comment]
+1
