### ISSUE TITLE
Delete or reset last employee activity(timeline items)

### ISSUE THREAD

**Issue by OmarJaber** [frappe/erpnext#7579]
In erpnext, each employee activity is shown on the employee page (below comments area)

In my project, I make some fast testing in Leave Application doctype by this user. Then I delete it.
**My question is how can I delete this information(timeline items) from employee page !**

![askin](https://cloud.githubusercontent.com/assets/19759247/22281243/7e78eb1e-e2de-11e6-9c32-7de555bb9fad.png)

**Comment by rmehta** [comment]
I don't see any such item in my timeline. Maybe delete from `tabCommunication` ?

**Comment by OmarJaber** [comment]
Thanks
