### ISSUE TITLE
Employee Loans extended to Accounts for any kind of loan

### ISSUE THREAD

**Issue by jwrober** [frappe/erpnext#7584]
New employee loans feature will be available soon.  As part of this discussion

https://discuss.erpnext.com/t/blog-enhancements-in-payroll-and-employee-loan-management/19381

wanted to see if this feature could be extended into the accounts module to support any kind of loan that a company would have. Ideally the feature would auto-enter the P&I into the GL month of month and prompt for a payment entry to track the actual payment for the given period.

**Comment by mhbu50** [comment]
+1

**Comment by nabinhait** [comment]
Can you please try the Employee Loan feature on develop branch? Please let us know if it fulfils your requirements.

**Comment by thenewguy** [comment]
Consider invoice discounting and factoring https://en.wikipedia.org/wiki/Factoring_(finance)

From your forums and irc there is not currently a way to easily model this with erp next and take it into account for P&L and calculating the net margin / roi etc for individual sales

**Comment by Olawale1** [comment]
Hi @nabinhait 

The Employee Loan feature is great. It would be very helpful to apply this same feature to other types of loans and repayments. For example, managing a bank loan

Kind regards,
