### ISSUE TITLE
Ctrl+Down on row after last row makes an error in validation

### ISSUE THREAD

**Issue by superlack** [frappe/erpnext#7585]
I was trying to go through an invoice and manually refresh each link field in a row (seperate issue).  By the time I get to the last one and hit Ctrl+Down again, it closes the child table fold out but still adds a new row.  When trying to save the invoice, it freezes in validation because of the empty row and the console shows the following:

`Failed to load resource: the server responded with a status of 404 (NOT FOUND)
/#Form/Sales%20Invoice/SINV-17-00011:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0
     at JSON.parse (<anonymous>)
     at Object.<anonymous> (desk.min.js:139)
     at i (jquery.min.js:2)
     at Object.fireWith [as rejectWith] (jquery.min.js:2)
     at z (jquery.min.js:4)
     at XMLHttpRequest.<anonymous> (jquery.min.js:4)`

![error](https://cloud.githubusercontent.com/assets/12856084/22317993/1c5a49b6-e32c-11e6-984f-f82e2c2cb518.png)

(picture for legibility)

**Comment by umairsy** [comment]
Hello,

I just tried to replicate this issue. For now, on Ctrl + Down after last row, new dialog box was opened for selecting new Item in the transaction. Since it was a dialog box, I could delete it there itself. Are you still able to replicate this issue?

**Comment by superlack** [comment]
It was fine to delete the row with the table expanded, but if it was left empty and exited, validation didn't give any errors saying there was empty fields, it just went to frozen grey instead

**Comment by pratu16x7** [comment]
Validation does give an error for an empty row as of now. Do let us know if you still face the issue. Closing.

![screen shot 2017-05-15 at 11 12 53 pm](https://cloud.githubusercontent.com/assets/5196925/26070970/2224b950-39c4-11e7-904f-f50f716159d3.png)
![screen shot 2017-05-15 at 11 13 09 pm](https://cloud.githubusercontent.com/assets/5196925/26070971/2281e21a-39c4-11e7-8e95-b0885b08176b.png)
