### ISSUE TITLE
PURCHASE ACCOUNT

### ISSUE THREAD

**Issue by wanyinyirobert** [frappe/erpnext#7586]
My payables are not reflecting on my purchase account. Kindly advise.

**Comment by rmehta** [comment]
Can you please explain your problem clearly with screenshots?

**Comment by wanyinyirobert** [comment]
[screenshot.docx](https://github.com/frappe/erpnext/files/738471/screenshot.docx)
I have posted all my payables( raw material & packaging) but they are not reflecting on the purchase account on the P&L account as direct expenses.

**Comment by rmehta** [comment]
Please don't attach .docx files. Directly attach screenshots.

Also the better place for these queries is https://discuss.erpnext.com
