### ISSUE TITLE
Payment Entry List of Account Paid To Show Receivable Accounts

### ISSUE THREAD

**Issue by cphoa28** [frappe/erpnext#7588]
When making a new SUPPLIER payment entry, and when wanting to select other accounts payables accounts, drop down of Account Paid To shows only Accounts Receivables accounts instead.  Please Help!!

Version 7.2.14

![image](https://cloud.githubusercontent.com/assets/20081843/22339244/496763e6-e424-11e6-85eb-9f467d46c45f.png)

**Comment by Arundhatii** [comment]
Can replicate in test account
![payment entry bug](https://cloud.githubusercontent.com/assets/20164097/22896719/262cab94-f247-11e6-9904-a4dcb034a0ac.png)

**Comment by cphoa28** [comment]
Thanks!!  So this will be fixed in version 8?  FYI, you can still type in the correct a/p account, it's just the dropdown choice list is not working.
