### ISSUE TITLE
Total Row Disappears Whenever Reports are Filtered!

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#7592]
Hi,

The total row disappears whenever reports are filtered. This affects all reports in ERPNext (Script, Query, and Report Builder). It would really help a great deal if the Total Row could just update (re-calculate) rather than disappear. Please help fix this

Regards

**Comment by yashodhank** [comment]
@Olawale1 Unable to replicate on demo.erpnext.com, maybe post screenshot/animated screen capture (gif format) etc.

**Comment by Olawale1** [comment]
Hi @yashodhank 

Trust you're doing well. Please find an example below. This affects all reports in ERPNext as far as I know. Which reports did you check?

![total row issue 1](https://cloud.githubusercontent.com/assets/9269337/23021125/a5e2cf58-f44a-11e6-9065-02622d078c82.png)
![total row issue 2](https://cloud.githubusercontent.com/assets/9269337/23021126/a6484068-f44a-11e6-8ef8-c94e0dcdece8.png)


Regards,

**Comment by Devens** [comment]
+1

**Comment by applepipe** [comment]
+1

**Comment by vladucoju** [comment]
+1

**Comment by franciscoyasociados** [comment]
+1

**Comment by SonaliBudhrani** [comment]
+1

**Comment by ishanloya** [comment]
+1

**Comment by asbasawaraj** [comment]
+1

**Comment by strixaluco** [comment]
Guys, all these "+1"s in comments produce unnecessary noise and disrupt the topic. You should use [add reaction](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) functionality, which exists for almost 1.5 years already.

**Comment by netchampfaris** [comment]
https://github.com/frappe/frappe/pull/3898

**Comment by magic-overflow** [comment]
if(Object.values(item).includes("'Total'")) return true;

How about query report which item doesn't have Total in the row. eg. Accounts Receivable.....

**Comment by magic-overflow** [comment]
add_total_row = false but it has "Totals" in General Ledger, so it doesn't work too.
It should add_total_row = true and "Total" with without "s".

**Comment by magic-overflow** [comment]
Those report should be standardized, if they have sum columns, add_total_row have to be **true** and there's a label **"Total"**, instead of **"Totals"** in somewhere.
