### ISSUE TITLE
Payroll Processing Problems with ERPNext 7.2.6

### ISSUE THREAD

**Issue by mafrica** [frappe/erpnext#7595]
I am testing the payroll processing using ERPNext 7.2.6. In this version each Salary Component requires an association with an account - seems a very good idea.

I have associated the Basic Salary with the Salary Expense account and Income tax and insurance deductions with different liability accounts. The liabilities I initially classed as payables but when the payroll was processed the JVs were rejected as no party type or party was provided for the liability accounts. There appears no clear way to set these and so temporarily I have set the accounts as cash and so avoided the need for party information.

Now the JV progresses to the point of posting to the salary expense account but fails with the message that there is no default company cost centre, when in fact there is. The system then crashes with a complex error report which I have sent to the support team.

This gif shows the default cost centre and the processing failure.  I have sent the full error report to support@erpnext.com

http://pilgrimagepublications.com/downloads/Payroll%20Processing.gif

**Comment by KanchanChauhan** [comment]
Account type for Salary Component Account and also for the process payroll should be Bank or Cash. May be that caused this issue, since I am not able to replicate it. I have added filters so that Bank or Cash type account can be selected. https://github.com/frappe/erpnext/pull/7614

**Comment by mafrica** [comment]
I am trying to accumulate income tax owed, pension contributions owed, health insurance owed and allocate the gross salary to the P and L line of Salary.  I had already changed the tax, pensions and insurance accounts to cash (although logically they would be tax or payables accounts).  I have now changed the P and L expense account to cash (although it is an expense account) but I am afraid there is no change in behavious.  Here is the error message "Journal Entry JV-00015: Cost Center is required for 'Profit and Loss' account Salary - MAOT. Please set up a default Cost Center for the Company."

The **Salary** account is the one in the default chart of accounts P and L section.  Is your test similar?

**Comment by mafrica** [comment]
I have progressed to testing the Expense Claim Function and have encountered essentially the same issue.

When I submit an expense claim with expense type - travel - and set the expense type as posting to the Travel Expenses Expense account I get the error

Journal Entry JV-00016: Cost Center is required for 'Profit and Loss' account Travel Expenses - MAOU. Please set up a default Cost Center for the Company.

Where again there is a default cost centre but no way to explicitly state a cost centre for this transaction.

If I change the Travel Expense account to type Cash I still get the same error.  

Unlike with the payroll the system does not create a crash report after the error message.

**Comment by KanchanChauhan** [comment]
Fixed via https://github.com/frappe/erpnext/pull/7704
