### ISSUE TITLE
Invalid column name in Customised report

### ISSUE THREAD

**Issue by ipmurali** [frappe/erpnext#7596]
Hello Team...
We have a customised report based on Leads, it was running fine when we developed it.  but now it giving  a message,

> Unknown Column: fiscal_year

 but the report is giving the result.
![lead_report_issue](https://cloud.githubusercontent.com/assets/12823590/22368885/4c49f80c-e4a2-11e6-8a6c-c407684998f4.png)

**Comment by KanchanChauhan** [comment]
Can you check what error you get in browser console and also if fiscal year is in selected columns.

**Comment by ipmurali** [comment]
fiscal_year  column is not selected in the report.

Below is the error in browser console

`Failed to load resource: the server responded with a status of 404 (NOT FOUND)
desk#Report/Lead/Deepu:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (desk.min.js:142)
    at i (jquery.min.js:2)
    at Object.fireWith [as rejectWith] (jquery.min.js:2)
    at z (jquery.min.js:4)
    at XMLHttpRequest.<anonymous> (jquery.min.js:4)`

**Comment by nabinhait** [comment]
May be there is a blank column selected under "Pick Columns". If that is the case, remove that column and save the report from Menu.
