### ISSUE TITLE
Item variants broken when using Naming Series for items

### ISSUE THREAD

**Issue by ioweb-gr** [frappe/erpnext#7601]
Hi, 

when trying to make a new variant for an item using Naming Series for code generation I get presented with an error 
`Item Code is required`

![c1](https://cloud.githubusercontent.com/assets/20220341/22395794/fc149216-e550-11e6-855c-4782ac87eaec.JPG)

![c2](https://cloud.githubusercontent.com/assets/20220341/22395796/076d6084-e551-11e6-83c6-49584e36bf9f.JPG)

I remember this issue happening before because I had submitted a pull request for this issue in the past
#4550

**Comment by rohitwaghchaure** [comment]
Hi @ioweb-gr 
Not able to replicate the issue, 
in stock settings set field item naming by Naming Series and created variant item using naming series

**Comment by ioweb-gr** [comment]
Hi @rohitwaghchaure , could you have a look at this again because it's not working for numeric attributes that don't have an abbreviation which was the original pull request about. 


The following piece of code basically negates the pull request I had submitted regarding the issue. 
```python
def make_variant_item_code(template_item_code, variant):
	"""Uses template's item code and abbreviations to make variant's item code"""
	if variant.item_code:
		return

	abbreviations = []
	for attr in variant.attributes:
		sql = """select i.numeric_values, v.abbr
			from `tabItem Attribute` i left join `tabItem Attribute Value` v
				on (i.name=v.parent)
			where i.name=%(attribute)s and v.attribute_value=%(attribute_value)s"""

		item_attribute = frappe.db.sql("""select i.numeric_values, v.abbr
			from `tabItem Attribute` i left join `tabItem Attribute Value` v
				on (i.name=v.parent)
			where i.name=%(attribute)s and v.attribute_value=%(attribute_value)s""", {
				"attribute": attr.attribute,
				"attribute_value": attr.attribute_value
			}, as_dict=True)

		if not item_attribute:
			return
			# frappe.throw(_('Invalid attribute {0} {1}').format(frappe.bold(attr.attribute),
			# 	frappe.bold(attr.attribute_value)), title=_('Invalid Attribute'),
			# 	exc=InvalidItemAttributeValueError)

		if item_attribute[0].numeric_values:
			# don't generate item code if one of the attributes is numeric
			return

		abbreviations.append(item_attribute[0].abbr)
```

The query that is ran is in my case

```msyql
select i.numeric_values, v.abbr
			from `tabItem Attribute` i left join `tabItem Attribute Value` v
				on (i.name=v.parent)
			where i.name='Ώρες Τεχνικής Υποστήριξης' and v.attribute_value=155
```

However the result without filtering with the `where` clause produces in my case a NULL abbreviation row probably on the numeric attribute. 

![image](https://cloud.githubusercontent.com/assets/20220341/23452952/fda57e42-fe6e-11e6-9053-09923b1df0d6.png)

Consequently from what I can see from the comment `don't generate item code if one of the attributes is numeric` I'm guessing it's ignored and item variant generation fails.

The original idea was to apped a  dash `-` and the numeric value to the item_code so that the variant could be successfully generated if there wasn't an abbreviation (because numeric values didn't have abbreviations). 

As a sidenote, does python use tests? Could you add a test to this scenario so it won't keep breaking after updates? Variants are really important in ecommerce whether numeric or not.

The way I see it this should be either revamped so that numeric values get abbreviations for each numeric value (not really the best idea since numeric values can have vast ranges) or handle it in any place abbreviations are used as a part of the core functions.

**Comment by rohitwaghchaure** [comment]
Hi @ioweb-gr 

Thanks for brief explanation, I have identified and fixed the issue by appending the numeric value to the item name like INTENSO BEANS - G-1, INTENSO BEANS - G-2.

**Comment by ioweb-gr** [comment]
Thanks @rohitwaghchaure 

As soon as the PR is merged I'll test and report back
