### ISSUE TITLE
feature request: add rich text and inline images to comments and email textarea

### ISSUE THREAD

**Issue by peefour** [frappe/erpnext#7603]
I see that erpnext wants to upgrade its editor to summernote. This would be a great opportunity to add rich text and inline images to the comments textarea too!

For example in 'erpnext issues' it can be handy to include screenshots or other imagery inline, so you can discuss the issue alongside the right image.
otherwise you end up with a bunch of attachments that you have to sift through, moreover these are no real attachments but just images.

see discussion https://discuss.erpnext.com/t/image-management-in-erpnext-like-in-this-forum-discourse/19796/4

**Comment by peefour** [comment]
To make it easy:
You can have one input area with summernote (for both comments and email), and have a check button if you want it send as email.

**Comment by netchampfaris** [comment]
https://github.com/frappe/frappe/pull/3789
