### ISSUE TITLE
Bug: problem when changing languages 

### ISSUE THREAD

**Issue by peefour** [frappe/erpnext#7605]
see details here https://discuss.erpnext.com/t/bug-problem-when-changing-languages/19700/3

**Comment by rmehta** [comment]
Cannot replicate in develop

**Comment by peefour** [comment]
I will wait for the develop version (which version number?) to be released,
and test again.
when will it be released for production?

2017-01-30 8:09 GMT+01:00 Rushabh Mehta <notifications@github.com>:
