### ISSUE TITLE
Project % Completed error

### ISSUE THREAD

**Issue by noussh** [frappe/erpnext#7607]
Hello.

Created a project in **Task Weight** % Complete Method.  Added a task and gave 1 weight and set 6% percentage completed .   I got the 6% complete status as expected.  However I delete the task and refreshed the screen, but it still shows 6% completed in list view and detailed view even though there is no tasks.  Screenshots attached.  

list view
![image](https://cloud.githubusercontent.com/assets/76837/22413784/16c35bcc-e6d4-11e6-94c0-ab9de027aefd.png)

detailed view

![image](https://cloud.githubusercontent.com/assets/76837/22413794/2118c882-e6d4-11e6-80c1-9b42e83a8b34.png)

However, when you add again a task then the % is reset to 0%.

**Comment by Arundhatii** [comment]
Can replicate the issue in test account.
The Project Status doesn't change even after deleting the task and reloading.
![project without task](https://cloud.githubusercontent.com/assets/20164097/22896398/e22563ba-f245-11e6-953b-256a32f85bb8.png)
