### ISSUE TITLE
Attaching Cost Centre and Project References to Salary Components

### ISSUE THREAD

**Issue by mafrica** [frappe/erpnext#7611]
It appears that most forms of expense posting eg JV and Purchase Invoice offer the facility to record an expenditure against an account; a cost centre and a project.

However, when the salary component is expanded it only offers the option to post to an account.  Could this me extended to include the analysis fields of cost centre and project?

**Comment by mhbu50** [comment]
+1

**Comment by Devens** [comment]
+1

**Comment by KanchanChauhan** [comment]
Fixed via https://github.com/frappe/erpnext/pull/7704
