### ISSUE TITLE
Email screen of sales order is longer than the window size

### ISSUE THREAD

**Issue by pgarodia** [frappe/erpnext#7617]
Once a sales order is created, it is emailed to our client. The email screen is longer than the window size and there is no way to scroll up or down. The screenshot for the issue is in the URL below. 

https://pgarodia.tinytake.com/sf/MTMwMzAwNF80ODQ0NDI0

Thanks.

**Comment by nabinhait** [comment]
I can not replicate the issue in my test environment. The window is scrollable. Are you still facing the issue? Can you please try on separate browser?

**Comment by pgarodia** [comment]
Hi Nabin,

I have Windows 7. I have tried this on Chrome version 56 and IE version 11.
It is replicable on both browsers.

Thanks,
Prateek

**Comment by netchampfaris** [comment]
@pgarodia Cannot replicate on Windows 7. I am able to scroll down the email modal.

![image](https://cloud.githubusercontent.com/assets/9355208/26099720/43830c52-3a49-11e7-9424-a5edfb0feb33.png)

**Comment by tundebabzy** [comment]
Not being able to replicate this issue, let's close it for now. @pgarodia please reopen if this is still an issue for you.
