### ISSUE TITLE
Value of some items in stock analytics and stock balance are different 

### ISSUE THREAD

**Issue by nagarajannxweb** [frappe/erpnext#7618]
Value of some items in stock analytics and stock balance are different 
![screen 2](https://cloud.githubusercontent.com/assets/17669548/22453127/808013c4-e7a2-11e6-8109-1ec632a84224.png)

In Stock Analytics the item showing the value of Rs.16,137.19/-

![screen 1](https://cloud.githubusercontent.com/assets/17669548/22453153/bc0d530c-e7a2-11e6-89be-a5fcb20ca07f.png)

In stock ledger /stock balance it showing Rs. 16,749/-. Some items are showing different value when compared the stock analytics and stock balance.

**Comment by nabinhait** [comment]
Can't replicate. Are you checking both the report for the same item and warehouse?

**Comment by nagarajannxweb** [comment]
Yes checking the same item and warehouse.

**Comment by nabinhait** [comment]
This is something related to your data. Really difficult to say anything without checking your data. Please try to debug yourself, closing this issue.
