### ISSUE TITLE
 Ctrl + G does not work in Russian

### ISSUE THREAD

**Issue by ivangretsky** [frappe/erpnext#7627]
Search bar seems to be one of the most important navigation means in ERPNext. While in English I can press Ctrl + G to focus on it, but if I switch to (in my case) Russian, I can no longer do it in some browsers.

- In IE 11 on Windows 10 it works like it should.
- In latest Chrome on Windows 10 it shows the build in search box.
- In latest Firefox on Windows 10 it simply does not show anything.

I think I have seen this problem solved in some other project, so it should be possible to make this shortcut cross-lingual. 

See [this topic](https://discuss.erpnext.com/t/ctrl-g-does-not-work-in-russian/19930) for reference.

**Comment by umairsy** [comment]
Works fine in my test account.

![ctrl g](https://cloud.githubusercontent.com/assets/910238/22880666/09ecb3d6-f209-11e6-910a-e26b0534d157.gif)

**Comment by ivangretsky** [comment]
I need to switch your system locale to reproduce the issue. Something like Alt+Shift on Windows by default. Seems like you set the ERPnext lang to RU, but your system locale is still EN. 

Just checked it again - the issue persists. Please read the forum topic referenced to reproduce.

Please re-open the issue.

**Comment by netchampfaris** [comment]
I have tried to replicate on my machine. Also, changed the locale, keyboard layout and timezone to Russia. Anything else I should try to replicate?

**Comment by ivangretsky** [comment]
Good day!
I might be misusing the word "locale".

To replicate do this:
- grab a windows 10 mashine that has Russian language and english langauage (that is what I callled 'locale');
- login to erpnext;
- look in the tray in the right bottom corner, find language switcher;
- when you got 'eng' on and press CTRL+G the search bar gets the focus and you can start typing;
- when you got 'pyc' on and press CTRL+G the search bar DOES NOT get the focus, and that is the problem.
