### ISSUE TITLE
Welcome email not working for bulk import 

### ISSUE THREAD

**Issue by gmaheshkumar** [frappe/erpnext#7629]
When I try to import users using CSV, welcome email is not going out even though I have set send_welcome_email as 1 in the csv. It works fine when I add a single user from the GUI. 
When I checked the Email Queue, status is shown as "error"
and the error is "No recipients to send to"
Installed Apps:
ERPNext: v7.2.14
Frappe Framework: v7.2.13

**Comment by KanchanChauhan** [comment]
@gmaheshkumar Can you share the sample data to test. Seems to be working fine at our end.

**Comment by manassolanki** [comment]
https://github.com/frappe/frappe/pull/2835
