### ISSUE TITLE
Format issue when exporting large numbers

### ISSUE THREAD

**Issue by ASneha1** [frappe/erpnext#7630]
Fields that have large numbers e.g. Bank A/C No. in the employee doctype are re-formatted or the values are changed when exported. For example:

This number when exported
![image](https://cloud.githubusercontent.com/assets/16811259/22491386/045b7f10-e85e-11e6-83a7-c6d899b91829.png)

Is changed to 
![image](https://cloud.githubusercontent.com/assets/16811259/22491395/1295171c-e85e-11e6-89fa-0f9648b7e52f.png)

**Comment by rmehta** [comment]
Exported using what tool?

**Comment by ASneha1** [comment]
Data Import Tool

**Comment by umairsy** [comment]
Works fine in my test account.

![screen shot 2017-02-13 at 4 20 47 pm](https://cloud.githubusercontent.com/assets/910238/22880495/6c844e2e-f208-11e6-8a38-694d0ee60f55.png)

Issue seems to be related to configuration of the spreadsheet application used.

**Comment by ASneha1** [comment]
Hi Umair, we are currently using Microsoft Excel. How should be configure so as to maintain the large numbers?

**Comment by ASneha1** [comment]
Hi @umairsy, any recommendation on the spreadsheet application we should use or if we continue to use Excel, any configuration you recommend?

**Comment by umairsy** [comment]
Perhaps you should check the field type (in excel). Alternatively, you can also try libre office. It's a free and open source office applications suite.
