### ISSUE TITLE
Dual Language Invoices - [Paid Development] 

### ISSUE THREAD

**Issue by jesseorndorff** [frappe/erpnext#7631]
One of our offices works in a country where two languages are required on all invoices. We would need the ability to have our all invoice fields display both English and the national language. 

I am attaching a sample invoice as we would need it to show.

[Tax invoice for Jesse Orndoff Co..pdf](https://github.com/frappe/erpnext/files/743913/Tax.invoice.for.Jesse.Orndoff.Co.pdf)

**Comment by jesseorndorff** [comment]
I should also note that I realize we can do this with a custom translation, but it would require us to re-translate every item to a Khmer / English translation, when we would like to be able to select two languages to display.

**Comment by mhbu50** [comment]
+1

**Comment by thosvesta** [comment]
+1

**Comment by addymuliady** [comment]
+1

**Comment by strixaluco** [comment]
Just with intention to avoid duplication — does anybody mind renaming this issue to be more generic? (e.g. "Dual language print formats"). We do need similar functionality, but not only in invoices and it seems pretty reasonable to improve the framework in more generic way, so more users can benefit from this improvement.
If there's any objection, I'll create separate issue.

**Comment by rmehta** [comment]
Implemented in V11
