### ISSUE TITLE
bug: drag and drop does not work n chrome nor opera

### ISSUE THREAD

**Issue by peefour** [frappe/erpnext#7633]
I use latest versions of the browsers.
(opera is just as chrome based on chromium)

**Comment by rmehta** [comment]
Can you specify in which use case, which verison?

Please give complete information while raising an issue.

**Comment by peefour** [comment]
for more info see this discussion:
https://discuss.erpnext.com/t/bug-drag-and-drop-does-not-work-in-chrome-or-opera/19965

if you need specific info please let me know

**Comment by rmehta** [comment]
Yes specific info is very much needed, specially screenshots, animated GIFs etc.

**Comment by peefour** [comment]
okay, I wil investigate how I can do that best to give you a clearer picture.

2017-02-03 5:01 GMT+01:00, Rushabh Mehta <notifications@github.com>:
