### ISSUE TITLE
Gantt view resets to days after refresh

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#7634]
- Open Gantt
- Switch to week view
- Open document by clicking on bar (Task)
- Save document
- Back to Gantt (view changes to day view)

**Comment by netchampfaris** [comment]
frappe/frappe#2675

**Comment by netchampfaris** [comment]
frappe/frappe#2715

**Comment by joolsr** [comment]
Yes 

I must admit during my testing I found the resetting to days very annoying as our projects would normally be in weeks or months. In fact I would suggest the default should be in weeks myself
