### ISSUE TITLE
Gantt week view should have first day of the week instead of week #

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#7635]
<img width="804" alt="screen shot 2017-02-01 at 12 27 19 pm" src="https://cloud.githubusercontent.com/assets/140076/22497759/d9cc5f6e-e879-11e6-9dd6-b6ac154dc768.png">

Week #34 is meaningless...

**Comment by netchampfaris** [comment]
Fixed frappe/frappe#2667
![image](https://cloud.githubusercontent.com/assets/9355208/22547600/5d3758c4-e968-11e6-8efb-7eb12908d7e8.png)
