### ISSUE TITLE
 From “frappe bench start” to supervisord gunicorn Install / Update - silent gunicorn failure

### ISSUE THREAD

**Issue by chlarsen** [frappe/erpnext#7636]
Dear All,

_Note:_ This post had to be cross-posted from the ERPNext discussion forum to GitHub, because I have failed to receive any replies. 

Here is my environment: FreeBSD 10.3, FreeBSD jails, manual setup, running frappe bench as non-privileged frappe user, Nginx as reverse proxy with prescribed settings.
frappe bench start works.
All sections of the auto-generated supervisord.conf work - except the gunicorn one:
command=/usr/local/frappe/frappe-bench/env/bin/gunicorn -b 127.0.1.113:8000 -w 2 -t 120 frappe.app:application just does:

````
[2017-01-23 05:34:09 +0000] [78620] [INFO] Starting gunicorn 19.6.0
[2017-01-23 05:34:09 +0000] [78620] [INFO] Listening at: http://127.0.1.113:8000 (78620)
[2017-01-23 05:34:09 +0000] [78620] [INFO] Using worker: sync
[2017-01-23 05:34:09 +0000] [78628] [INFO] Booting worker with pid: 78628
[2017-01-23 05:34:09 +0000] [78629] [INFO] Booting worker with pid: 78629
````

I add --preload --forwarded-allow-ips "*" to the gunicorn command line for good measure, to accommodate any weirdness incurring my Nginx proxy, but no luck.

Any idea what could be the reason. The only change is, as said above, from bench start to using gunicorn with the same IPs, proxies, etc.
Any help would be greatly appreciated.
Thanks!

Chris

**Comment by umairsy** [comment]
Hello,

Please follow up for the issues on discuss forum only.

**Comment by chlarsen** [comment]
There has been zero input in the discussion forum. Other gunicorn issues there are unrelated.
Sorry, I am not happy to have this closed without zany resolution: After all, ERPNext has seen qiuite a few issues in the past with FreeBSD, which we have solved together. So, a silent closure is rather counter-productive, IMHO.
