### ISSUE TITLE
Link issue on new address for lead

### ISSUE THREAD

**Issue by cereneto** [frappe/erpnext#7646]
Hi,

I'm on ERPNext: v7.2.14, Frappe Framework: v7.2.12.

On new address for lead, the table reference in address doctype don't fetch link doctype and link name from the current lead. 

When I do the same for customer, link doctype and link name is created with current customer.

Did you have the same issue?

**Comment by mbauskar** [comment]
@cereneto, The issue is already resolved via https://github.com/frappe/erpnext/pull/7533.

**Comment by cereneto** [comment]
I will. 

Thank you
