### ISSUE TITLE
Data import tool - options missing

### ISSUE THREAD

**Issue by sp9leo** [frappe/erpnext#7655]
Only few items are available in data import tool.

![image](https://cloud.githubusercontent.com/assets/15377465/22548324/3777d9be-e946-11e6-8a76-f775345827ec.png)

**Comment by joezsweet** [comment]
I've post few days ago in discussion

https://discuss.erpnext.com/t/cannot-export-custom-doctype-using-import-export-feature/19830

**Comment by manassolanki** [comment]
Fixed
