### ISSUE TITLE
ERPNext Hub

### ISSUE THREAD

**Issue by KanchanChauhan** [frappe/erpnext#7658]
ERPNext Hub will be a like an in-app marketplace which will provide:
- Free listing of your products and services including ERPNext Service Providers
- Browse through products listed by other sellers, compare prices etc.

To do List:
- [x] New module Hub Node
- [x] New app Hub which will act like central for hub nodes
- [ ] Hub marketplace page
- [x] In-app registration to the Hub
- [x] Settings to publish the products to the Hub in Hub Settings

**Comment by addymuliady** [comment]
Hi @KanchanChauhan 

Does this mean that we are able to sell ERPNext apps in the future?
