### ISSUE TITLE
Customer Discount by Brand

### ISSUE THREAD

**Issue by lxnow** [frappe/erpnext#766]
Noticed there is now a Customer Discount table per Customer and it appears to already work. Feature suggestion is to include the Brand field together with Item Group.  If both fields are specified, then the item must meet both in order to apply a certain discount rate.  If only one field is specified, then it applies to all items under that Group or Brand.  

If there are overlaps, i.e. multiple discount rules that overlap, then the Item Group + Brand takes priority.  Example:

For just one customer:

Rule 1: Group A + Brand X = 10%
Rule 2: Group A + (no Brand specified) = 12%
Rule 3: (no Brand specified) + Brand X = 9%.

For item in Group B + Brand X, discount = 9%
For item in Group A + Brand Y, discount = 12%
For item in Group A + Brand X, discount = 10%

 (http://erpnext.org/docs.dev.modules.Selling.doctype.Customer%20Discount.model.html)

**Comment by anandpdoshi** [comment]
done via Pricing Rule
