### ISSUE TITLE
Payment Days not calculated in Salary

### ISSUE THREAD

**Issue by SonalR** [frappe/erpnext#7663]
Hi an employee joined on the 12th of Dec therefore we want to pay him salary from 12th to 31st december. The leave without pay is zero

The salary slip has paid him the full month's salary. Please help

**Comment by KanchanChauhan** [comment]
Can you please check payment days on the salary slip.

**Comment by SonalR** [comment]
payment days are 20 salary being paid for whole month as salary only
depends on leave without pay

CONFIDENTIALITY NOTICE: This electronic mail message and any attached files
contain information intended for the exclusive use of the individual or
entity to whom it is addressed and may contain information that is
proprietary, privileged, confidential and/or exempt from disclosure under
applicable law. If you are not the intended recipient, you are hereby
notified that any viewing, copying, disclosure or distribution of this
information may be subject to legal restriction or sanction.   Please
notify the sender, by electronic mail or telephone, of any unintended
recipients and delete the original message without making copies.

**Comment by KanchanChauhan** [comment]
You need to cancel the salary slip and Amend it, mark Salary Component as "Depends on Leave without pay".

**Comment by SonalR** [comment]
done all that

CONFIDENTIALITY NOTICE: This electronic mail message and any attached files
contain information intended for the exclusive use of the individual or
entity to whom it is addressed and may contain information that is
proprietary, privileged, confidential and/or exempt from disclosure under
applicable law. If you are not the intended recipient, you are hereby
notified that any viewing, copying, disclosure or distribution of this
information may be subject to legal restriction or sanction.   Please
notify the sender, by electronic mail or telephone, of any unintended
recipients and delete the original message without making copies.

**Comment by SonalR** [comment]
This is not working

CONFIDENTIALITY NOTICE: This electronic mail message and any attached files
contain information intended for the exclusive use of the individual or
entity to whom it is addressed and may contain information that is
proprietary, privileged, confidential and/or exempt from disclosure under
applicable law. If you are not the intended recipient, you are hereby
notified that any viewing, copying, disclosure or distribution of this
information may be subject to legal restriction or sanction.   Please
notify the sender, by electronic mail or telephone, of any unintended
recipients and delete the original message without making copies.

On Fri, Feb 3, 2017 at 5:33 PM, Sonal Ramnathkar <sonal.ramnathkar@gmail.com

**Comment by KanchanChauhan** [comment]
Tested this on local, works fine. It was fixed via https://github.com/frappe/erpnext/pull/7163/files.
@SonalR You are probably on older version.

**Comment by SonalR** [comment]
how do I upgrade to the new version? am on paid hosting

CONFIDENTIALITY NOTICE: This electronic mail message and any attached files
contain information intended for the exclusive use of the individual or
entity to whom it is addressed and may contain information that is
proprietary, privileged, confidential and/or exempt from disclosure under
applicable law. If you are not the intended recipient, you are hereby
notified that any viewing, copying, disclosure or distribution of this
information may be subject to legal restriction or sanction.   Please
notify the sender, by electronic mail or telephone, of any unintended
recipients and delete the original message without making copies.

**Comment by nabinhait** [comment]
@SonalR Please drop an email on support@erpnext.com. We need to check the issue by accessing your account, please provide the login credential and salary slip ID on the email. Closing the issue here.

**Comment by nabinhait** [comment]
@KanchanChauhan Please take it forward from support ticket.
