### ISSUE TITLE
Payroll Process Cost centers

### ISSUE THREAD

**Issue by ariellempel** [frappe/erpnext#7666]
When I do "Make bank entry" in Payroll Process there is many problems regarding cost center.
 
   1) If you don't have a default cost center for the company you get an error and the Journal Entry is not created.

   2) If you have a default cost center for the company the Journal Entry is created but every transaction is asociated with the default cost center regardless the default cost center of the account associated with every salary component.
 
   So, for me the goal would be to have an option to assign a cost center in every salary component and in the payroll have this priority order:
                      1) Salary component cost center
                      2) Default cost center of account in salary component
                      2) Company default cost center

**Comment by mhbu50** [comment]
+1

**Comment by KanchanChauhan** [comment]
Fixed via https://github.com/frappe/erpnext/pull/7704
