### ISSUE TITLE
Ukrainian 'In Words' translation

### ISSUE THREAD

**Issue by Sergeyzhol** [frappe/erpnext#7674]
Hi
I've added Ukrainian translation to num2words and sent a pull request 
https://github.com/frappe/num2words/pull/2
Please add Ukrainian 'In Words' support to ERPNext.

**Comment by umairsy** [comment]
Hello,

Thanks for your contribution. Your pull request should be reviewed and merged shortly. Request you to avoid creating Github Issue for followup purpose.
