### ISSUE TITLE
Summernote - No option to end ordered/unordered list

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#7695]
![summernote 1](https://cloud.githubusercontent.com/assets/910238/22728176/84f0d8ba-ee02-11e6-8a84-5019b95309bc.gif)

**Comment by netchampfaris** [comment]
summernote/summernote#2224

**Comment by netchampfaris** [comment]
Fixed with https://github.com/frappe/frappe/commit/8ac3a9a7cab37fb7562a0ad2a7541af5c75c2981
