### ISSUE TITLE
Lost access to "Quotations"

### ISSUE THREAD

**Issue by Mikeduncombe** [frappe/erpnext#7697]
After resetting permissions, I can no longer access "Quotations" documents. I get no error message, the link just doesn't appear on the form.

**Comment by umairsy** [comment]
Hello @Mikeduncombe,

I could replicate this issue in my test account as well. We will soon check into it and get back to you.

**Comment by rohitwaghchaure** [comment]
This issue is fixed and will release in version 8

**Comment by Hardik-mehta** [comment]
is this issue is fixed because i recently tried but it resets all permissions 
Frappe version :7.2.30
Erpnext version : 7.2.30

**Comment by Mikeduncombe** [comment]
HI,

I’ve had no re-occurrences, so I would say, yes, it’s fixed.

Mike
