### ISSUE TITLE
Date format on error on Supplier Quotation doctype kanban view, Field Name = status 

### ISSUE THREAD

**Issue by wpleasant** [frappe/erpnext#7698]
There seems to be a date format error when using the "status" field name on the "Supplier Quotes" doctype.

![image](https://cloud.githubusercontent.com/assets/582790/22740973/a403901c-eddf-11e6-83eb-48ff0df51601.png)

The error only appears when I try and select the card, yet the card can be moved from on column to the next without actually changing the status in the underlying document.

Installed Apps
ERPNext: v7.2.19
Frappe Framework: v7.2.15

Thanks

**Comment by yashodhank** [comment]
@wpleasant Wait till version 8 release.

**Comment by mbauskar** [comment]
@wpleasant ,

it is working fine in version 8 please check

![kanban](https://cloud.githubusercontent.com/assets/11224291/26100952/0c524c8a-3a4d-11e7-9e07-7640492aa8ba.gif)

Please reopen if the issue still persist
