### ISSUE TITLE
Maximum call stack size exceeded during Setup when using macOS Safari

### ISSUE THREAD

**Issue by matthewlehew** [frappe/erpnext#7699]
This behavior is observed using the Production image and running `bench-update` before setup, using Safari 10.0.3 (12602.4.8) on macOS 10.12.3. ERPNext is 7.2.19 and Frappe is 7.2.15.

When going through setup prompts, everything goes fine until `/setup-wizard/3`, where the domain is selected. I selected "Retail" and clicked "Next," and nothing happens. At this point, the Safari console throws the following: `RangeError: Maximum call stack size exceeded.` in `Scripts/libs.min.js:9918.` Clicking "Previous" and then going back restores functionality to the "Next" button.

On the "Organization" screen, the Financial Year Start Date is pre-populated with 03-03-2013 and the end date is blank. Attempting to change the start date to 01-01-2017 through the picker or manually typing results in another date being selected. Attempting to change these dates results in `RangeError: Maximum call stack size exceeded.` in `Scripts/libs.min.js:9922.`

Letting the selected (incorrect) dates remain allows the setup process to continue and complete, and ERPNext seems to work as intended from that point. 

Using Chrome 56.0.2924.87 results in the setup process working as expected with no problems.

**Comment by matthewlehew** [comment]
Just reproduced the problem on the Development image. This is the development server output after selecting "Retail" as the domain and hitting Next, which is where the problems start:

```
08:35:07 web.1            | 10.0.2.2 - - [08/Feb/2017 08:35:07] "POST / HTTP/1.1" 200 -
08:35:07 web.1            | INFO:werkzeug:10.0.2.2 - - [08/Feb/2017 08:35:07] "POST / HTTP/1.1" 200 -
08:35:07 web.1            |  * Detected change in '/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/account/chart_of_accounts/__init__.py', reloading
08:35:07 web.1            | INFO:werkzeug: * Detected change in '/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/account/chart_of_accounts/__init__.py', reloading
08:35:07 web.1            |  * Detected change in '/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/account/chart_of_accounts/__init__.py', reloading
08:35:07 web.1            | INFO:werkzeug: * Detected change in '/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/account/chart_of_accounts/__init__.py', reloading
08:35:07 web.1            |  * Detected change in '/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/account/chart_of_accounts/chart_of_accounts.py', reloading
08:35:07 web.1            | INFO:werkzeug: * Detected change in '/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/account/chart_of_accounts/chart_of_accounts.py', reloading
08:35:07 web.1            |  * Detected change in '/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/account/chart_of_accounts/chart_of_accounts.py', reloading
08:35:07 web.1            | INFO:werkzeug: * Detected change in '/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/account/chart_of_accounts/chart_of_accounts.py', reloading
08:35:08 web.1            | Exception in thread Thread-2 (most likely raised during interpreter shutdown):
08:35:08 web.1            | Traceback (most recent call last):
08:35:08 web.1            |   File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
08:35:08 web.1            |   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/watchdog/observers/api.py", line 237, in run
08:35:08 web.1            | <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'Empty'
08:35:08 web.1            |  * Restarting with inotify reloader
08:35:08 web.1            |  * Debugger is active!
08:35:08 web.1            |  * Debugger pin code: 100-628-728
```

**Comment by matthewlehew** [comment]
One more update for now, haha. The problem still exists on the Development image without updating first. This version of ERPNext is 7.2.14 and Frappe is 7.2.12.

**Comment by codrotech** [comment]
Hi Matthew, did you resolve this issue, I have same problem on my MacPro, my partner with same hardware and same configuration has no isssues.
Thank you
Maurizio

**Comment by codrotech** [comment]
Any updates on this issue?

**Comment by nabinhait** [comment]
We have pushes a fix to avoid the recursion.

https://github.com/frappe/frappe/pull/2755

**Comment by matthewlehew** [comment]
Can confirm this is working as of 7.2.26.
