### ISSUE TITLE
Leads and Opportunities Analytics & Value of Leads / Opportunities

### ISSUE THREAD

**Issue by asherfk** [frappe/erpnext#770]
It would be great to have more information on leads and opportunities for reporting purpose. There is no amount or value input in the leads / opportunities thus the sales managers cannot evaluate the current pipeline worth. Similar features are standards in all ERPs available which analytic to see reports on leads / opportunities value based on regions, products, account manager etc. Sales system is lacking a lot of depth due to this as the only value can be monitored is quotations or sales order. For sales value of leads / opportunities enables teams to focus on areas where more attention is required as well.

**Comment by PawanMeh** [comment]
Sales Efficiency & Campaign Effectiveness reports have been added to latest develop branch as part of issue #8466. These may address some of your concerns, you can have a look at them and suggest any changes.
