### ISSUE TITLE
In leave allocation making the period non mandatory

### ISSUE THREAD

**Issue by Jaliya** [frappe/erpnext#7701]
We provide half day leave when an employee works pass 3 am. He can use the leave following day or have it accumulated to his total leave. When we use leave allocation tool to enter the leave, using date is mandatory. Please consider updating Leave Allocation to add this compensatory leave to total leave entitlement without indicating a using date.

**Comment by KanchanChauhan** [comment]
You can add the new leave count to the existing leaves. You do not have to make new record.

**Comment by Jaliya** [comment]
What is the document we use to add new leave to existing leave?

**Comment by KanchanChauhan** [comment]
Leave Allocation

**Comment by Jaliya** [comment]
Do you mean by making a Leave allocation with Dates from say 2/1/2017 to 31/12/2017 and then amending it every time a leave allocation happens?

**Comment by KanchanChauhan** [comment]
You do not have to amend it, "New Leaves Allocated" is a editable field in Leave Allocation after submit, you just need to change that and save.

**Comment by Jaliya** [comment]
Thank you very much

**Comment by Jaliya** [comment]
Although I have a work around solution now, I appreciate if you could provide a straight forward way as we have to provide a report every month to employees for which of their overtime works they are awarded compensatory leave .
