### ISSUE TITLE
Security Vulnerability: Users are being mixed up

### ISSUE THREAD

**Issue by adam-je** [frappe/erpnext#7703]
I've a funny problem first reported here: NOT PERMITTED [Session expired. Logging you out]

The problem is that other users are logging into my account even when using their own user credentials.

e.g. user1 is logged in, user2 logs in on different PC but name and picture shows user 1, including all account access and details. User2 appears as user1 when they're logged in.

Details:

    I setup ERPNext and my own user account which I've been using since I've created additional users, on 2 different occurrences.
    I did a fresh setup of ERPNext v7
    Setup on Ubuntu 14.04, using the latest frappe and erpnext (I updated)
    I've imported data (including users and files) into ERPNext from my last setup which I had to erase due to the same problem but more severe issue (please refer to the linked topic).

I'll appreciate some help on this as my organisations adoption depends on it. No one else has reported this problem as far as I can see.

First posted on the Forums 

https://discuss.erpnext.com/t/other-users-are-logging-into-my-account-even-when-using-their-own-credentials/20218

**Comment by umairsy** [comment]
Hello,

Hope your post on the forum for this issue was helpful. Please do not post such queries/issues on Github Issues.

**Comment by adam-je** [comment]
Why not @umairsy. This issue has no attention on the forums and its not a simple issue.
