### ISSUE TITLE
[BUG]: Payment entry fields missing after update v7.2.18

### ISSUE THREAD

**Issue by vladucoju** [frappe/erpnext#7706]
Hello, 

when i try to add new payment entry (receive), there is no fields to enter the customer. When i change from receive to internal tranfer, and back again, the fields come back, and then i can insert customer. This is happening after update  v7.2.18. I updated yesterday again to the latest version v7.2.19 but nothing has changed. There is still bug.

**Comment by yashodhank** [comment]
@vladucoju Looks ok to me, post screenshot or animated gif of the issue.
![image](https://cloud.githubusercontent.com/assets/1083792/22790303/be235cb6-ef0b-11e6-81f0-ca0cc4eea748.png)

**Comment by vladucoju** [comment]
My version is
Installed Apps
ERPNext: v7.2.19
Frappe Framework: v7.2.15

![bug](https://cloud.githubusercontent.com/assets/9590909/22794999/58b78e94-eef5-11e6-9874-9d2da571e901.gif)

**Comment by yashodhank** [comment]
@vladucoju have you done bench update & bench migrate followed by clear cache? do that and check it resolves your issue.

**Comment by vladucoju** [comment]
I done everything you said except bench cli. I don't know what is it. Still not showing.

**Comment by ioweb-gr** [comment]
Hi, it's exactly the same for me as @vladucoju  describes. I 've also tried clearing cache, reset form for payment entry, bench update, bench migrate and bench clear-cache but it persists.

**Comment by vladucoju** [comment]
Working again. Thanks @rohitwaghchaure
