### ISSUE TITLE
[BUG] there is problem to attached contact picture 

### ISSUE THREAD

**Issue by me2ne** [frappe/erpnext#7707]
Hello
I fine a issue, when we attach picture in customer contact , don't show his picture in his profile . 

In Customer , edit one of contact , in left corner click on picture , chose picture , chose picture , un click private and upload , after than doesn't show picture , just show file in attachment . 

Regards
![screen shot 2017-02-09 at 7 59 36 pm](https://cloud.githubusercontent.com/assets/6168204/22791293/5672be08-ef02-11e6-9c7d-7480de5d23c6.png)

**Comment by yashodhank** [comment]
@me2ne update & clear cache. I was unable to replicate on
**Installed Apps**
ERPNext: v7.2.19
Frappe Framework: v7.2.15

First upload:
![image](https://cloud.githubusercontent.com/assets/1083792/22797682/366d0398-ef25-11e6-94fb-d76363c4e33b.png)

Second update on same contact:
<img width="254" alt="screen shot 2017-02-10 at 12 11 06 am" src="https://cloud.githubusercontent.com/assets/1083792/22797744/79d49844-ef25-11e6-8190-091ab9342338.png">

**Comment by dogmatus** [comment]
Hi Everyone, 

I am new to Erpnext. I found this ERP beautiful and it suits my needs. I have the same issue as @me2ne. 

I can change the picture (logo) of a client (company) but when i try to add picture on a contact, it shows for 1 second and then nothing change. It only happen on contact's picture. 

Can you please help me. 

Server : Ubuntu 16.04

Installed Apps

ERPNext: v7.2.29

Frappe Framework: v7.2.29
![image](https://cloud.githubusercontent.com/assets/26326105/23795484/ff149a3a-05a6-11e7-9118-b57abd220c4c.png)

**Comment by me2ne** [comment]
Hi @dogmatus and @yashodhank 
I still have same problem with attache picture to contact , it's show 1 sec and then not show any more , even i try in demo.erpnext.com on last version , it have same issue . 
i don't know how it's work for yashodhank , i try with different browser and disorient computer too . 
Hope some one can find and solve this issue .
