### ISSUE TITLE
POS - can't change companies

### ISSUE THREAD

**Issue by fblauer** [frappe/erpnext#7709]
Doesn't seem to be any way to change from one company to another? If we do it in global defaults, won't that affect all users? Should there be a way to chose the default company under the user settings, so other users are not affected?

**Comment by umairsy** [comment]
Hello Fred,

As discussed on forum, it will be best to have different Point of Sale Setting master. Given the pace with which POS Invoices is to be made, something like Company should be updated by default.

**Comment by fblauer** [comment]
I can't figure out what you mean. I created a POS profile for each user/company combination. I can't figure out what to do next. How do I indicate which one is in effect? I still can't figure out how to change the default company.
