### ISSUE TITLE
BOM Item does not have UOM selection

### ISSUE THREAD

**Issue by bcornwellmott** [frappe/erpnext#7711]
There is no way to pick the UOM of items when creating BOMs.

**Comment by umairsy** [comment]
In the BOM, item's default stock UOM is auto-fetched for both raw material and production item.

**Comment by bcornwellmott** [comment]
That only works for the stock him. If you want to use a different unit you can't.

**Comment by cgpurbaugh** [comment]
This is important.  UOM can be changed on PO, SO, & SE.  This is one of the last forms that needs updated.

**Comment by bcornwellmott** [comment]
I've taken this on - there's a pull request out that I need to update with some fixes. I will not be able to address it for a while though (other priorities), so if anyone else wants to take this on please feel free. https://github.com/frappe/erpnext/pull/7923
