### ISSUE TITLE
Edit Purchase Order once submitted

### ISSUE THREAD

**Issue by Lumithree** [frappe/erpnext#7717]
Hi, 

Question, how can we edit/modify a purchase order once it was submitted? 
Let say i have to change the cost of an item after the PO was submitted. 

Thank you,
Erick.

**Comment by joezsweet** [comment]
I think you have to amend it, check if the role has rights to do that ..

**Comment by nick9822** [comment]
@Lumithree 
You will have cancel and then amend the cancelled document.

**Comment by Lumithree** [comment]
Thank you @joezsweet and @nick9822. Tried what you said and it worked. Thank you for your help.
