### ISSUE TITLE
Unable to Create a fully depreciated asset

### ISSUE THREAD

**Issue by addymuliady** [frappe/erpnext#7722]
Based on @nabinhait  advice:
https://discuss.erpnext.com/t/create-a-fully-depreciated-asset/20270

I am doing an opening asset entry.
I have an existing asset which already has depreciated fully, i.e. value of 0. It is still deemed an asset in the company.
How do I create this asset?

Purchased in July 2011
Gross Purchase = $5000
Depreciated within 60 mths at a frequency of 1 mth
Value after life = $0
In ERPNext, the Next Depreciation Date cannot be a past date. For the above, the Next Depreciation Date should be Aug 2011. This is a big problem and there is no way to create this type of Asset.

**Comment by nick9822** [comment]
@addymuliady 
I did the same entry and it went through with the said warning. But I was able to create asset. Any other issue in it other than warning.

**Comment by addymuliady** [comment]
Hi @nick9822 

What is Next Depreciation Date that you keyed in?

For my case, it doesn't go through at all. I have to put a future date in Next Depreciation Date.

**Comment by nick9822** [comment]
August 1st, 2011
See this screenshot
![image](https://cloud.githubusercontent.com/assets/10139291/22890124/656ef3cc-f231-11e6-8d0e-911d5376bff2.png)

**Comment by addymuliady** [comment]
Hi @nick9822 

What version of Frappe and ERPNext are you on?

Does the depreciation graph shows the same?

Regards

Mulyadi

**Comment by nick9822** [comment]
@addymuliady 
ERPNext: v7.2.19
Frappe Framework: v7.2.15

> Does the depreciation graph shows the same?
Yes

**Comment by addymuliady** [comment]
Can the warning be taken instead? Confusing.

Thanks @nick9822 for checking!

**Comment by nick9822** [comment]
@addymuliady @nabinhait @rmehta 
I guess next depreciation date should be compared with the purchase date instead current date.

**Comment by tundebabzy** [comment]
Is this issue still persisting? I thought it was fixed in #7751
