### ISSUE TITLE
SMS settings - CSS alignment issue

### ISSUE THREAD

**Issue by thosvesta** [frappe/erpnext#7729]
Please see the SMS settings, Checkbox numbers alignment is not formatted correctly.

![image](https://cloud.githubusercontent.com/assets/18680544/22878158/446abe7e-f19e-11e6-8f7c-3871804c737f.png)

**Comment by umairsy** [comment]
Hello,

This is appearing just fine in my test account.

![screen shot 2017-02-13 at 4 15 06 pm](https://cloud.githubusercontent.com/assets/910238/22880318/ba458480-f207-11e6-8c8c-7f7469bff804.png)

May I know in which browser are you accessing your ERPNext account? For the best results of ERPNext, please access it via Firefox or Chrome.

**Comment by thosvesta** [comment]
I have tried in both Firefox and Google Chrome. And I created a new VPS to test this, Tested in two VPS instances and still the same issue. I'm running the current Release v7.2.19. Not sure why its showing correctly for you. Let's see anyone else is able to replicate this issue.
