### ISSUE TITLE
BOM import rate

### ISSUE THREAD

**Issue by chanlung** [frappe/erpnext#7740]
I would like to import BOMs into the system. I downloaded the template by exporting the BOM. There is a column in there called "rate". I'm a little confused by this MANDATORY COLUMN. If I was to create a new BOM manually, when I select the item to be part of the BOM the rate is AUTO filled for me based on what I have set for my "Rate Of Materials Based On". In my case "Valuation Rate." I would like the import to do the same. I don't want to write the value for my item I would like the system to calculate it for me.

https://discuss.erpnext.com/t/bom-import-rate/20383/3

**Comment by kennethsequeira** [comment]
Closing this issue.

In v11 and 12, the system fetches the rates serverside if available based on the condition (valuation rate, price list, or buying price)
