### ISSUE TITLE
Accounting Bugs in Multicurrency

### ISSUE THREAD

**Issue by fderyckel** [frappe/erpnext#7743]
I have noted 3 issues while doing transactions in multi-currency.  2 are bugs that causes serious accounting issues and 1 is more like an issue (enhancement?)
The currency of the Company is Euro.  Basically I'm trying to see if ERPNext can be use to keep track of my financial tradings (Portfolio) 

## Issue Number 1
In my portfolio, I have cash accounts in USD, CAD and AUD (on top of our EUR one).  
I made a JV that changed USD directly to CAD (without passing to the EUR!).  This gave some serious inconsistencies.  See pictures.  
![screen shot 2017-02-14 at 10 15 17 pm](https://cloud.githubusercontent.com/assets/7240992/22947313/3930cf38-f303-11e6-9e7e-85befbe7907b.png)
![screen shot 2017-02-14 at 10 15 28 pm](https://cloud.githubusercontent.com/assets/7240992/22947314/39346292-f303-11e6-82f6-aa90a41fa4cc.png)

The amounts have been credited and debited correctly in the respective foreign currency cash account, but for some reasons (as seen on the ledger), the transaction record some wrongs entries in the EUR account.  The against accounts are wrong.

## Issue number 2
I bought 500 Options X in USD @ $1.6.  They expire worthless.  I try to record the loss.  
I cannot use a stock entry (stock issue) as the company is in Euros (although the currency of the warehouse in the stock assets is in USD)
So I decide to use a Sale invoice with 500 Options X with Values of 0 USD.  I can save and submit, but no accounting transaction have been recorded in the system.  So Now the stock balance on that item is correct (0) but the value in the warehouse is wrong (the stock assets value is wrong) and the loss has not been recorded (that is the COGS has not been recorded).  
Everything works if I put the value at $0.01

## Issue number 3
It is not possible to do stock adjustment (at least the value of the stock) in the currency of the stock.  
In my case it is important.  I buy stocks (equities) let's say in USD and CAD and I'd like to record their change in value in USD and CAD.  It seems like I'm only able to do this in the company currency which is EUR.  But I'm buying and selling these stocks in USD and CAD... for instance ;-)

In the way I have set up things, I have created creditors, debtors, COGS, sales, stock assets (warehouse) in each of the EUR, CAD, USD, AUD.  If something is bought in one currency it will be sold in that currency.  In that way it is easier to keep track of purchase, sales without worrying immediately about exchange loss / gain.

**Comment by fderyckel** [comment]
I'm adding another issue here.  Posted on the forum
https://discuss.erpnext.com/t/multicurrency-ledger-how-to-put-it-at-0/20716

**Comment by fderyckel** [comment]
I'm adding another issue here again
The purchase invoice currency exchange label is not set correctly.
See pictures
![screen shot 2017-03-03 at 8 18 41 am](https://cloud.githubusercontent.com/assets/7240992/23540539/87143fb6-ffea-11e6-949c-031aea5f6f3b.png)

With the set exchange rate, the Total(EUR) should be less than the Total(USD)

On the sale invoice it is reading correctly
![screen shot 2017-03-03 at 8 19 17 am](https://cloud.githubusercontent.com/assets/7240992/23540550/956b1832-ffea-11e6-9c0a-69c688e261d3.png)

**Comment by mosabamf** [comment]
> 
> 
> I'm adding another issue here. Posted on the forum
> https://discuss.erpnext.com/t/multicurrency-ledger-how-to-put-it-at-0/20716
> 
> How should I record such a transaction:
> Cie currency is EUR
> Cie has a USD and a EUR Bank account
> I transfer 1,000 Euros to my USD Bank account (and I get $1,100)
> A month later, I instruct my banker to transfer back that $1,100 to my EUR account. I get for this 1050 EUR.
> So on JV0001: 1,000EUR Credit, $1,100 Debit
> on JV0002: 1050EUR Debit, $1,100 Credit.
> 
> My balance on my USD account should be 0.
> But ERPNext handled this in a strange way... it put $0 (but -50EUR) for its EUR equivalent.
> 
> How can I avoid that and how should I record that currency exchange gain / loss?

+1

**Comment by harshit-30** [comment]
Please create another issue if it is replicable in v13.10.
