### ISSUE TITLE
v 7.2.8-0 DateRange Filter Not Working

### ISSUE THREAD

**Issue by miguelangelcastellanos** [frappe/erpnext#7744]
Hello,

On all my Date fields , when searching for a Range of dates, the system always return no results.

In this example I added a Date field called fecha_pago to the Sales Invoice Payment DocType.

In the List View I tried to query for records between February 1st and February 28th, but the query that arrives at MySQL includes the following condition:

where ifnull(`tabSales Invoice Payment`.fecha_pago, '0000-00-00 00:00:00') 
Between '**2017-02-14** 19:48:20.039418' AND '**2017-02-15** 19:48:20.039653'

The query was performed at 19:48 of february 14th, so clearly the system is not sending the correct parameters to mysql. It is just searching between the current date and the next day.

Thanks for your help and time.

Miguel

**Comment by KanchanChauhan** [comment]
I tested it on `ERPNext: v7.2.22` and `Frappe Framework: v7.2.18`. Seems to be working fine. Probably the filter selection was wrong in your case.
<img width="961" alt="screen shot 2017-02-22 at 3 04 15 pm" src="https://cloud.githubusercontent.com/assets/16913064/23205573/5e8eac88-f910-11e6-8fc5-e7824c3f9d38.png">

**Comment by KanchanChauhan** [comment]
Closing since it is not getting replicated.
