### ISSUE TITLE
customer can not contact us through the website's contact

### ISSUE THREAD

**Issue by wandatsai** [frappe/erpnext#7753]
There is an issue in erpnext. Customer can not contact us through the website's contact. 
No matter which mail the customer enters, it was showed "You seem to have written your name instead of your email. Please enter a valid email address so that we can get back."

thank you

**Comment by nabinhait** [comment]
Can't replicate the issue. Which version and branch are you using?

**Comment by wandatsai** [comment]
erpnext v 7.2.19
frappe v 7.2.15
My company:  https://samplezt.erpnext.com/
I don't know why e-mail can't send via contact? 
thankyou verymuch

**Comment by umairsy** [comment]
Replicating.

![screen shot 2017-02-16 at 12 41 21 pm](https://cloud.githubusercontent.com/assets/910238/23011145/429b2c92-f445-11e6-9903-d8d483da9a2a.png)

**Comment by wandatsai** [comment]
thankyou very much! But I have another problem.
![image](https://cloud.githubusercontent.com/assets/25793574/23049135/34bebfa2-f4f5-11e6-9610-bdf1b4b1438a.png)

**Comment by KanchanChauhan** [comment]
@wandatsai Tested from your website, it works fine.
<img width="784" alt="screen shot 2017-02-21 at 11 36 50 am" src="https://cloud.githubusercontent.com/assets/16913064/23152889/286a43aa-f82b-11e6-9775-61a70858bae5.png">
