### ISSUE TITLE
[v7.2.19] Can't select date on sales analytics

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#7754]
Hello,

When selecting date on sales analytics it simply ignores selection, even if I type the date it changes the field value, a similar issue is occurring on stock balance report.

**Comment by yashodhank** [comment]
@applepipe you need to press refresh button.

**Comment by applepipe** [comment]
https://demo.erpnext.com/desk#sales-analytics

Refresh doesn't have any effect, try to select any date and you will see that it doesn't fill the date field with your selection, I've triend on firefox and chrome.

**Comment by applepipe** [comment]
These reports are also affected, just open without type anything, you will see date fields being created.

https://demo.erpnext.com/desk#query-report/Stock%20Balance
https://demo.erpnext.com/desk#query-report/Trial%20Balance

Basically any report of this kind have this problem.

**Comment by applepipe** [comment]
apparently it was fixed
