### ISSUE TITLE
Maintaining Same Valuation rate for item across all the warehouses of a particular company

### ISSUE THREAD

**Issue by koshish** [frappe/erpnext#7755]
We need to maintain same valuation rate across all the warehouses of a company.
suppose, when one warehouse purchase any item it should check the available items and its value across all the warehouses and update the same valuation rate across all the warehouses.

Regards,
Koshish

**Comment by joezsweet** [comment]
As far as i know price is not related to warehouse

**Comment by koshish** [comment]
Currently it is updating the item valuation_rate for the particular warehouse which is making the purchase of item or for the warehouse where stock entry is made.
But, Our company wants to maintain same valuation_rate across all the warehouse so that the cost_of item will be same across all the warehouses.

**Comment by joezsweet** [comment]
ah you mean in stock bin, you're right ..if u have same buying price for all warehouse you'll have same cost_of_item for all the company regardless the warehouse that got the receipt.

**Comment by koshish** [comment]
But the buying price of the item can be different for the different warehouse. So we want to update the cost_of_item across all the warehouses and repost the future entries

**Comment by koshish** [comment]
![image](https://cloud.githubusercontent.com/assets/19833048/23008142/1907e118-f427-11e6-973e-027fbe219bc6.png)

**Comment by joezsweet** [comment]
You could write a server side script and add to background jobs in order to calculate it and upgrade for all the warehouses

**Comment by hfaridgit** [comment]
Needed this feature, companies asked for it.
They need the option to make valuation rate on item allover the company not by warehouse.

**Comment by yasseralghoul** [comment]
Any update on this issue, please?

**Comment by majdalhalabi1994** [comment]
Hi
Any update??

**Comment by mincerray1** [comment]
any update?

**Comment by 0FiRE0** [comment]
Can you please update on this if it is included in the latest release yet or not.
Thank you.
