### ISSUE TITLE
Email Id not recognized

### ISSUE THREAD

**Issue by ihackalot** [frappe/erpnext#7757]
I did setup successfully a couple of different collaborative mailboxes with my Google Apps account, so I have different addresses with the same login credentials. I did expect ERPNext to recognize the _Email Id_ and trigger the relative correct _Append To_ action. What happens instead is that the first email account in the list fetches whatever mailbox using the shared login credentias and automatically triggers it's own _Append To_ action.

**Comment by yashodhank** [comment]
@ihackalot if you have selected an account as default incoming, then it is expected behaviour.
Plus upcoming Email inbox feature, in version 8 will expected to solve some related issue AFAIK.

But please elaborate on your issue with more details, use case and screenshots if possible.

**Comment by ihackalot** [comment]
Thanks @yashodhank you are right and that fixes the issue! Please let me know if you want to know more details.
