### ISSUE TITLE
v 7.2.8-0 Customer Total Unpaid Field not updated

### ISSUE THREAD

**Issue by miguelangelcastellanos** [frappe/erpnext#7759]
Hello,

I am testing with a fresh 7.2.8-0 installation with no customizations.

I created a POS invoice for a customer, where the sum of the payments is less than the sum of the prices for all the products in the invoice.

After saving the Invoice, the Customer status becomes red which I think is correct because there are pending payments for that customer.

However when I access the customer page, the field: "Total Upaid" in the customer's dashboard remains at 0. Also the Annual Billing field is zero, but do not forget an Invoice for that customer already exists.

The problem only gets solved even after submitting the invoice, which I think is not consistent with the fact that the customer was already in red state.

The problem I see is this:

I queried all customers, then I see some of them are in red state, so in order to know how much is their outstanding amount I click on them. But the "Total Unpaid" information shows 0!!!! 

In this case the only way to know what is the outstanding amount is to access all the invoices to see if there are pending payments.

So for both the customer's state and the customer's dashboard to be consistent, they both should be updated even if the invoice is not submitted. The same issue applies for the "Annual Billing" information on the customer's dashboard.

Thanks a lot for your help and time.

Miguel

**Comment by yashodhank** [comment]
@miguelangelcastellanos make sure, you upgrade to latest version and then recheck for the issue.
Some issues are known and may be fixed with version 8 release as POS module is rewritten.

```
bench update
```
