### ISSUE TITLE
New ERPNext site - Fiscal Year issue

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#7761]
Scenario:

User signup for a new ERPNext account today (i.e. 16th Feb, 2017).
In the Setup Wizard, Fiscal Year start date is set as 1-4-2017 (for Country = India)

User completes the Setup successfully. But when creating transactions, gets error message that Current Date not found in any Fiscal Year.

To be fixed: On the completion of Setup, current financial year must be added as a Fiscal Year in ERPNext.

**Comment by nabinhait** [comment]
fixed via #7769
