### ISSUE TITLE
[UX] Error in purchase transaction - Ignore instead of Prompt

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#7766]
Steps:

1. In a new Purchase Order, selected Service Item.
2. Applied taxes.

On saving Purchase Order, getting error message shown below.

![screen shot 2017-02-16 at 8 09 54 pm](https://cloud.githubusercontent.com/assets/910238/23025743/f130f1b2-f484-11e6-9518-831e34ab1fd8.png)

Suggestion: Instead of forcing the user to change tax type, we should ignore valuation for the service item, and just show a notification to the user. Referring to the error message, User doesn't understand what to change/correct.

**Comment by tundebabzy** [comment]
This isn't a bug. It's working as expected. ERPNext specifically enforces that users change the tax type for service items.

To stop this behavior there are two options I can think of presently - 
1. Remove the present validation outright
2. During validation, if the tax type is not `total`, automatically change it to `total`.

I think i'll go for option 2
