### ISSUE TITLE
[v7.2.21] Email Inbox

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#7767]
Everytime I open the email inbox it displays an error "missing deleted filter", but I can't find where to create it, aparently another user in forum has the same problem https://discuss.erpnext.com/t/email-inbox-filter-deleted-missing/20069/3

**Comment by joolsr** [comment]
I have a similar issue in #7758 https://github.com/frappe/erpnext/issues/7758

**Comment by mbauskar** [comment]
added new Email Inbox view in Communication List

**Comment by joolsr** [comment]
the actual error was recently fixed by a code update
