### ISSUE TITLE
Create item price base on formula

### ISSUE THREAD

**Issue by thekingofboys** [frappe/erpnext#7772]
Is there any development or, already done,
to be able to create a item price base on the buying price and some formula for it,
so you dont have to be always updating the selling price,
it would take the last purchasing price and insert on the formula and put as the new item price for the item,
by that way you dont have to always be changing the selling price manualy

**Comment by bcornwellmott** [comment]
This is something you should be able to implement pretty easily with custom scripts. That way you can plug in whatever formula you'd like, based on whatever criteria you'd like.
