### ISSUE TITLE
Issue with ToDo WYSIWG area

### ISSUE THREAD

**Issue by pagliaso** [frappe/erpnext#7773]
Hello,

I think there  is an issue with new ToDo' WYSIWG area.

This is whith last update to v7 development version this morning (3 hours ago).

I explain it with the gif files:
![todo_1](https://cloud.githubusercontent.com/assets/2955272/23061595/d2c6ad42-f502-11e6-9676-ba10cc28f896.gif)
![todo_2](https://cloud.githubusercontent.com/assets/2955272/23061648/fee6f54e-f502-11e6-9a08-2ad963e391d4.gif)
![todo_3](https://cloud.githubusercontent.com/assets/2955272/23061610/dc7bfa72-f502-11e6-94d4-65de471bb526.gif)

I am using Firefox.
Many thanks and kind regards,

**Comment by tundebabzy** [comment]
This is a known firefox bug - [view on firefox bug tracker](https://bugzilla.mozilla.org/show_bug.cgi?id=550434). Will be fixed in the frappe repo. See frappe/frappe#3374 to updates.
