### ISSUE TITLE
Using " causes issues

### ISSUE THREAD

**Issue by graphskill** [frappe/erpnext#7776]
I noticed some of our stocks are not updating correctly when we use POS, and it is to do with the " 

We use " to denote "inches" in product codes > but ERP does not like it

As you can see here, the code of the product at the bottom is NUTS/A4SS/Hex-1/4"UNC

It is fine in usually but when trying to do the "add" to stock levels, and using the POS (perhaps other areas also) then the code seems to be truncated to before the "

is this a bug that can be fixed are do we need to change all our codes. Are there any other specal characters that could cause issues?

![image](https://cloud.githubusercontent.com/assets/925619/23064338/7ed6d478-f507-11e6-9f96-6bd048def50a.png)

**Comment by graphskill** [comment]
This seems to be more widespread than I thought and seems to happen with any non alphnumeric characters

So if we have * or / or - or " in the item then the system breaks

For example, this product

![image](https://cloud.githubusercontent.com/assets/925619/25898032/3fb0727a-3582-11e7-9b54-98c0a920193c.png)


If I click to create a material request

![image](https://cloud.githubusercontent.com/assets/925619/25897990/0e210102-3582-11e7-9c55-32072407eda4.png)


I get an error message, when i close the message we can see the code is truncated

![image](https://cloud.githubusercontent.com/assets/925619/25898002/1e5b59be-3582-11e7-88cd-c312b134575d.png)



Can anyone confirm this is a bug? 

Can it be fixed?

**Comment by joolsr** [comment]
Thanks for this fix coming. " is used a lot in imperial screw sizes etc

**Comment by tundebabzy** [comment]
@graphskill @joolsr fixed
