### ISSUE TITLE
LDAP- Contacts and  CalDav or Subscribe - Calendar sync with ERPNext DB

### ISSUE THREAD

**Issue by Tropicalrambler** [frappe/erpnext#7779]
I have been reviewing some posts in which it seems ERPNext at some point enabled LDAP login.  I am unfamiliar with the functionality of this. Can someone explain existing functionality?

This issue is a feature request to have the ability to synchronize the contacts available in ERPNext server so that they show on my Contacts app on iOS/ Android. Also, I wish to sync the Calendar events scheduled in ERPNext so that they show in my Calendar app in iOS/Android. This applies for Reminders as well. (CalDAV)

True, while the functionality of ERPNext app allows Contacts and Calendar to be seen within the app when connected to a server on iOS/Android, when I think about calling someone I really want to just go to Contacts app. And when I am thinking about appointments or whenI need a reminder, I want it to be the Calendar app.  Basically I want to have everything in its place on the iPhone/Smartphone, (ERPNext contacts, plus my iCloud contacts,  and the same for Calendars: ERPNext calendar, iCloud Calendar, Google Calendar, etc.)  This way, I can make direct calls from the Contacts app, or get reminders and reschedule events using the Calendar app, which also is useful to see if events overlap.

Enabling this functionality would also allow ERPNext to interface with Desktop apps supporting the Contacts, Calendar and Reminders protocols.

The reasoning behind it is this:  When thinking about Contacting someone, you use Contacts app.  When thinking about scheduling, you use Calendar App.  This also begins to make ERPNext accesible to voice activated assistants like Siri.  I personally use Siri to create Calendar appointments on the fly with great success!

**Comment by ossplus** [comment]
similar to frappe/frappe#18716
close it.
