### ISSUE TITLE
ERPNext unable to access through IP in AWS EC2

### ISSUE THREAD

**Issue by ronaldpaul** [frappe/erpnext#7781]
Hi, I setup an EC2 (AWS) instance with Ubuntu 14 and installed ERPNext through the easy install script and started the server through 'bench start'. However, when I accessed the instance through the IP, it just threw the error message 'page isn't working' and the following message was displayed in the console. Please note that I configured the inbound traffic rules properly for my instance.

17:28:07 web.1 | does not exist
17:28:07 web.1 | ----------------------------------------
17:28:07 web.1 | Exception happened during processing of request from ('', 52030)
17:28:07 web.1 | Traceback (most recent call last):
17:28:07 web.1 | File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
17:28:07 web.1 | self.finish_request(request, client_address)
17:28:07 web.1 | File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
17:28:07 web.1 | self.RequestHandlerClass(request, client_address, self)
17:28:07 web.1 | File "/usr/lib/python2.7/SocketServer.py", line 649, in init
17:28:07 web.1 | self.handle()
17:28:07 web.1 | File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/werkzeug/serving.py", line 228, in handle
17:28:07 web.1 | rv = BaseHTTPRequestHandler.handle(self)
17:28:07 web.1 | File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
17:28:07 web.1 | self.handle_one_request()
17:28:07 web.1 | File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/werkzeug/serving.py", line 263, in handle_one_request
17:28:07 web.1 | return self.run_wsgi()
17:28:07 web.1 | File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/werkzeug/serving.py", line 205, in run_wsgi
17:28:07 web.1 | execute(self.server.app)
17:28:07 web.1 | File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/werkzeug/serving.py", line 195, in execute
17:28:07 web.1 | for data in application_iter:
17:28:07 web.1 | File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/werkzeug/debug/init.py", line 284, in debug_application
17:28:07 web.1 | app_iter = self.app(environ, start_response)
17:28:07 web.1 | File "/home/ubuntu/frappe-bench/apps/frappe/frappe/middlewares.py", line 15, in call
17:28:07 web.1 | return super(StaticDataMiddleware, self).call(environ, start_response)
17:28:07 web.1 | File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/werkzeug/wsgi.py", line 599, in call
17:28:07 web.1 | return self.app(environ, start_response)
17:28:07 web.1 | File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/werkzeug/wsgi.py", line 599, in call
17:28:07 web.1 | return self.app(environ, start_response)
17:28:07 web.1 | File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/werkzeug/local.py", line 228, in application
17:28:07 web.1 | return ClosingIterator(app(environ, start_response), self.cleanup)
17:28:07 web.1 | File "/home/ubuntu/frappe-bench/env/local/lib/python2.7/site-packages/werkzeug/wrappers.py", line 291, in application
17:28:07 web.1 | return f(*args[:-2] + (request,))(*args[-2:])
17:28:07 web.1 | File "/home/ubuntu/frappe-bench/apps/frappe/frappe/app.py", line 53, in application
17:28:07 web.1 | init_request(request)
17:28:07 web.1 | File "/home/ubuntu/frappe-bench/apps/frappe/frappe/app.py", line 104, in init_request
17:28:07 web.1 | frappe.init(site=site, sites_path=_sites_path)
17:28:07 web.1 | File "/home/ubuntu/frappe-bench/apps/frappe/frappe/init.py", line 130, in init
17:28:07 web.1 | local.conf = _dict(get_site_config())
17:28:07 web.1 | File "/home/ubuntu/frappe-bench/apps/frappe/frappe/init.py", line 185, in get_site_config
17:28:07 web.1 | sys.exit(1)
17:28:07 web.1 | SystemExit: 1
17:28:07 web.1 | ----------------------------------------

Following is the console output of 'bench start':

bench start
17:21:54 system | redis_queue.1 started (pid=30242)
17:21:54 redis_queue.1 | [30249] 19 Feb 17:21:54.402 # Unable to set the max number of files limit to 10032 (Operation not permitted), setting the max clients configuration to 3984.
17:21:54 redis_queue.1 | .
17:21:54 redis_queue.1 | .-__ ''-._ 17:21:54 redis_queue.1 | _.- .. ''-._ Redis 2.8.4 (00000000/0) 64 bit
17:21:54 redis_queue.1 | .-.-```. ```\/ _.,_ ''-._ 17:21:54 redis_queue.1 | ( ' , .-` | `, ) Running in stand alone mode 17:21:54 redis_queue.1 | |`-._`-...-` __...-.-.|'_.-'| Port: 11000 17:21:54 redis_queue.1 | |-. ._ / _.-' | PID: 30249 17:21:54 redis_queue.1 |-._ -._-./ .-' .-'
17:21:54 redis_queue.1 | |-._-. -.__.-' _.-'_.-'| 17:21:54 redis_queue.1 | |-.-._ _.-'_.-' | http://redis.io 17:21:54 redis_queue.1 |-._ -._-..-'.-' .-'
17:21:54 redis_queue.1 | |-._-. -.__.-' _.-'_.-'| 17:21:54 redis_queue.1 | |-.-._ _.-'_.-' | 17:21:54 redis_queue.1 |-._ -._-..-'.-' .-'
17:21:54 redis_queue.1 | -._-..-' _.-'
17:21:54 redis_queue.1 | -._ _.-' 17:21:54 redis_queue.1 |-..-'
17:21:54 redis_queue.1 |
17:21:54 redis_queue.1 | [30249] 19 Feb 17:21:54.403 # Server started, Redis version 2.8.4
17:21:54 redis_queue.1 | [30249] 19 Feb 17:21:54.403 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
17:21:54 redis_queue.1 | [30249] 19 Feb 17:21:54.403 * The server is now ready to accept connections on port 11000
17:21:54 system | watch.1 started (pid=30252)
17:21:54 system | worker_long.1 started (pid=30243)
17:21:54 system | web.1 started (pid=30244)
17:21:54 system | schedule.1 started (pid=30245)
17:21:54 system | redis_socketio.1 started (pid=30246)
17:21:54 redis_socketio.1 | [30259] 19 Feb 17:21:54.426 # Unable to set the max number of files limit to 10032 (Operation not permitted), setting the max clients configuration to 3984.
17:21:54 redis_socketio.1 | .
17:21:54 redis_socketio.1 | .-__ ''-._ 17:21:54 redis_socketio.1 | _.- .. ''-. Redis 2.8.4 (00000000/0) 64 bit
17:21:54 redis_socketio.1 | .-.-```. ```\/ _.,_ ''-._ 17:21:54 redis_socketio.1 | ( ' , .-` | `, ) Running in stand alone mode 17:21:54 redis_socketio.1 | |`-._`-...-` __...-.-.|'_.-'| Port: 12000 17:21:54 redis_socketio.1 | |-._ ._ / _.-' | PID: 30259 17:21:54 redis_socketio.1 |-._ -._-./ .-' .-'
17:21:54 redis_socketio.1 | |-._-. -.__.-' _.-'_.-'| 17:21:54 redis_socketio.1 | |-.-._ _.-'_.-' | http://redis.io 17:21:54 redis_socketio.1 |-._ -._-..-'.-' .-'
17:21:54 redis_socketio.1 | |-._-. -.__.-' _.-'_.-'| 17:21:54 redis_socketio.1 | |-.-._ _.-'_.-' | 17:21:54 redis_socketio.1 |-._ -._-..-'.-' .-'
17:21:54 redis_socketio.1 | -._-..-' _.-'
17:21:54 redis_socketio.1 | -._ _.-' 17:21:54 redis_socketio.1 |-..-'
17:21:54 redis_socketio.1 |
17:21:54 redis_socketio.1 | [30259] 19 Feb 17:21:54.427 # Server started, Redis version 2.8.4
17:21:54 redis_socketio.1 | [30259] 19 Feb 17:21:54.427 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
17:21:54 redis_socketio.1 | [30259] 19 Feb 17:21:54.427 * The server is now ready to accept connections on port 12000
17:21:54 system | redis_cache.1 started (pid=30248)
17:21:54 redis_cache.1 | [30268] 19 Feb 17:21:54.448 # Unable to set the max number of files limit to 10032 (Operation not permitted), setting the max clients configuration to 3984.
17:21:54 redis_cache.1 | .
17:21:54 redis_cache.1 | .-__ ''-._ 17:21:54 redis_cache.1 | _.- .. ''-. Redis 2.8.4 (00000000/0) 64 bit
17:21:54 redis_cache.1 | .-.-```. ```\/ _.,_ ''-._ 17:21:54 redis_cache.1 | ( ' , .-` | `, ) Running in stand alone mode 17:21:54 redis_cache.1 | |`-._`-...-` __...-.-.|'_.-'| Port: 13000 17:21:54 redis_cache.1 | |-._ ._ / _.-' | PID: 30268 17:21:54 redis_cache.1 |-._ -._-./ .-' .-'
17:21:54 redis_cache.1 | |-._-. -.__.-' _.-'_.-'| 17:21:54 redis_cache.1 | |-.-._ _.-'_.-' | http://redis.io 17:21:54 redis_cache.1 |-._ -._-..-'.-' .-'
17:21:54 redis_cache.1 | |-._-. -.__.-' _.-'_.-'| 17:21:54 redis_cache.1 | |-.-._ _.-'_.-' | 17:21:54 redis_cache.1 |-._ -._-..-'_.-' _.-'
17:21:54 redis_cache.1 | -._-..-' _.-'
17:21:54 redis_cache.1 | -._ _.-' 17:21:54 redis_cache.1 |-..-'
17:21:54 redis_cache.1 |
17:21:54 redis_cache.1 | [30268] 19 Feb 17:21:54.448 # Server started, Redis version 2.8.4
17:21:54 redis_cache.1 | [30268] 19 Feb 17:21:54.448 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
17:21:54 redis_cache.1 | [30268] 19 Feb 17:21:54.448 * The server is now ready to accept connections on port 13000
17:21:54 system | socketio.1 started (pid=30247)
17:21:54 system | worker_default.1 started (pid=30266)
17:21:54 system | worker_short.1 started (pid=30258)
17:21:57 socketio.1 | listening on *: 9000
17:22:01 watch.1 | Wrote ./assets/js/print_format_v3.min.js - 25k
17:22:01 watch.1 | Wrote ./assets/js/frappe-web.min.js - 141k
17:22:01 worker_long.1 | 17:22:01 RQ worker u'rq:worker:ip-172-31-46-236.30255.long' started, version 0.7.1
17:22:01 worker_long.1 | 17:22:01 Cleaning registries for queue: long
17:22:01 worker_long.1 | 17:22:01
17:22:01 worker_long.1 | 17:22:01 *** Listening on long...
17:22:01 web.1 | * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
17:22:01 watch.1 | Wrote ./assets/js/form.min.js - 186k
17:22:01 worker_default.1 | 17:22:01 RQ worker u'rq:worker:ip-172-31-46-236.30277.default' started, version 0.7.1
17:22:01 watch.1 | Wrote ./assets/js/report.min.js - 255k
17:22:01 worker_default.1 | 17:22:01 Cleaning registries for queue: default
17:22:01 worker_default.1 | 17:22:01
17:22:01 watch.1 | Wrote ./assets/css/list.min.css - 10k
17:22:01 worker_default.1 | 17:22:01 *** Listening on default...
17:22:01 web.1 | * Restarting with inotify reloader
17:22:01 watch.1 | Wrote ./assets/js/d3.min.js - 380k
17:22:01 watch.1 | Wrote ./assets/css/report.min.css - 8k
17:22:01 watch.1 | Wrote ./assets/css/frappe-web.css - 64k
17:22:01 watch.1 | Wrote ./assets/js/list.min.js - 127k
17:22:01 watch.1 | Wrote ./assets/js/dialog.min.js - 83k
17:22:01 worker_short.1 | 17:22:01 RQ worker u'rq:worker:ip-172-31-46-236.30281.short' started, version 0.7.1
17:22:01 worker_short.1 | 17:22:01 Cleaning registries for queue: short
17:22:01 worker_short.1 | 17:22:01
17:22:01 worker_short.1 | 17:22:01 *** Listening on short...
17:22:01 watch.1 | Wrote ./assets/js/desk.min.js - 359k
17:22:01 watch.1 | Wrote ./assets/css/form.min.css - 4k
17:22:01 watch.1 | Wrote ./assets/js/libs.min.js - 896k
17:22:01 watch.1 | Wrote ./assets/css/desk.min.css - 275k
17:22:01 watch.1 | Wrote ./assets/css/frappe-rtl.css - 31k
17:22:01 watch.1 | Wrote ./assets/css/module.min.css - 2k
17:22:02 web.1 | * Debugger is active!
17:22:02 web.1 | * Debugger pin code: 200-795-636

**Comment by chdecultot** [comment]
Hi,

I don't know if it is the source of your issue, but if you have multi-tenant enabled, make sure your site's name is your IP address. Else you won't be able to access it when entering your IP address in the browser.

Best regards,
Charles-Henri

**Comment by strixaluco** [comment]
@ronaldpaul, please post questions regarding deployment to [discuss.erpnext.com](https://discuss.erpnext.com)
