### ISSUE TITLE
Stock Entry cannot create duplicate name already exist

### ISSUE THREAD

**Issue by clemnus** [frappe/erpnext#7782]
Hello,

I cannot create any new Stock Entry recently, when I want to save it says "Duplicate Name Stock Entry..." and "Stock Entry... Already exists"

Even when I click on the first stock entry I ever made and select Duplicate, put my data and try to save it still says the same thing.

here is the screenshot :

![screen shot 2017-02-20 at 10 05 59](https://cloud.githubusercontent.com/assets/20271673/23109570/4775276e-f755-11e6-906d-dbcbbd43b437.png)

What should I do ?

Thanks

**Comment by mbauskar** [comment]
@clemnus,

I am not able to recreate the issue on both Develop and master setup can you try to reload the document and try again?
Thanks,
Makarand

**Comment by nabinhait** [comment]
Seems like the current number of the selected naming series has been reset to zero. Please update the current number of the series based on the last stock entry. 

For more details about naming series, check
https://frappe.github.io/erpnext/user/manual/en/setting-up/settings/naming-series

**Comment by clemnus** [comment]
Hello,


Thank you for your help, that solved it !


Best regards,
------------------
Clément NUSBAUMER 秦沛




 

 
 
 
------------------ Original ------------------
