### ISSUE TITLE
[Enhancement] Half day leaves

### ISSUE THREAD

**Issue by ishanloya** [frappe/erpnext#7786]
Can we add the ability to create leave application for 1.5, 2.5, 3.5, etc. days?
[Forum link](https://discuss.erpnext.com/t/half-day-leaves/20597)

Thanks

**Comment by joolsr** [comment]
Yes very useful

**Comment by KanchanChauhan** [comment]
Fixed via https://github.com/frappe/erpnext/pull/7790 and https://github.com/frappe/erpnext/pull/7860
