### ISSUE TITLE
Sales Analytics report - Feature Request

### ISSUE THREAD

**Issue by SonaliBudhrani** [frappe/erpnext#7788]
In the Sales Analytics report, is it possible to get Customer names with or without Codes. We need the customers to be saved with codes, but would want the reports to have the customer name as its very difficult to analyse the reports with just the customer codes.
![sales analytics](https://cloud.githubusercontent.com/assets/18025664/23123406/35839f84-f78e-11e6-9f40-fc7e567c9cf4.png)

**Comment by SonaliBudhrani** [comment]
We need customer Name is Accounting Ledger of particular customer Print format. In that case too Just the customer code comes, which is not helpful in analysis or sending the report to customer. Please insert Customer name along with Customer code in both or all the reports regarding Customer.

Thanks
Sonali
<img width="1062" alt="screen shot 2017-02-23 at 4 33 17 pm" src="https://cloud.githubusercontent.com/assets/18025664/23256632/436c5578-f9e6-11e6-8ef1-f261a28d7421.png">

**Comment by Arundhatii** [comment]
Can replicate the issue in test account, When the sales analytics report is fetched based on territory it shows customer codes and not names.
![screen shot 2017-02-23 at 4 59 41 pm](https://cloud.githubusercontent.com/assets/20164097/23257400/a41a61be-f9e9-11e6-882e-682033d70f14.png)

**Comment by SonaliBudhrani** [comment]
Yes It will be very helpful if We can see names too.

**Comment by SonaliBudhrani** [comment]
Also If you could test Customer Account Ledger - Print Format.

**Comment by Devens** [comment]
+1

**Comment by SonaliBudhrani** [comment]
Hi,

Please let me know if this issue is assigned to anyone or not. We are not able to send accounting ledger to customer as the print does not mention their name. Also there is no customised Print format available in order to make changes in the print of account ledger.
Also the sales Analytics report doesn't show customer name and its very difficult to analyse that report with just the codes.
It will be really helpful if this issue is taken into account and appropriate code changes are implemented as we are not able to use either of the above mentioned things.

**Comment by vishdha** [comment]
![screenshot from 2017-09-01 13-28-30](https://user-images.githubusercontent.com/6947417/29960527-a2428f0e-8f19-11e7-9340-5b2c3a969562.png)
