### ISSUE TITLE
Adding Customer Address

### ISSUE THREAD

**Issue by epochc** [frappe/erpnext#7789]
I understand that you have built the link so that an address can be associated with different DocTypes, but when a user starts from a customer page (or a supplier page) and clicks on add address, the DocType and the Party should be auto populated, don't you think.

Right now users are surprised that address does not get associated to the party type.

Thanks

Jay

**Comment by KanchanChauhan** [comment]
Just tested for Customer, it does map the document. See the screenshot below.
<img width="938" alt="screen shot 2017-02-20 at 6 13 49 pm" src="https://cloud.githubusercontent.com/assets/16913064/23125569/6add9df6-f798-11e6-8387-25e9c3b82869.png">

ERPNext version: v7.2.21
