### ISSUE TITLE
Showing Pages in the Global Search

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#7796]
As observed earlier, Pages would render in the main section of List. But now, Pages are showing after Help section. Is this intended behavior? My suggestion is that Pages should also be shown in the list section, where we show links of doctypes/list etc. 

![screen shot 2017-02-21 at 12 08 31 pm](https://cloud.githubusercontent.com/assets/910238/23153462/c4740620-f82e-11e6-97cf-89f4bbcf03e6.png)

Further, we can hide Pages as a heading, because Pages is an internal (Frappe) term, hence need not be showcased to the User.

**Comment by pratu16x7** [comment]
Thanks for the observation.
Treeviews do show in the list section if they are present for a doctype. For things like analytics, managers and so on, they can perhaps be shown under something like "Administration".
