### ISSUE TITLE
Campaign field in the Lead

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#7798]
In a Lead, Campaign field should only show up if in the Source field, "Campaign" is selected as a value.

![screen shot 2017-02-21 at 12 23 07 pm](https://cloud.githubusercontent.com/assets/910238/23153832/a5b82818-f830-11e6-9225-9ace6a244d35.png)

**Comment by fproldan** [comment]
As the Lead Source Field is self-administered may or may not exist the lead source named Campaign or may be in another language, eg in Spanish there will be "Campaña" and the constrain does not be triggered.
