### ISSUE TITLE
Lead - After attaching at image, preview is shown but get hidden automatically

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#7803]
![image-error](https://cloud.githubusercontent.com/assets/910238/23154279/0a27691a-f833-11e6-83ae-68e95eab3de2.gif)

Could it be related to Demo account? This same feature is working fine in Customers and Employee master.

**Comment by netchampfaris** [comment]
Cannot replicate in develop. Not even in demo account. Closing for now.
