### ISSUE TITLE
Auto-suggest, not showing any record after editing field

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#7806]
Steps:

1. On a link field, as soon we make a first click, auto-suggest is shown correctly.
2. After if we try editing, then after removing some text, auto-suggest is not applied.

![screen shot 2017-02-21 at 1 01 07 pm](https://cloud.githubusercontent.com/assets/910238/23154909/1f86b8e4-f836-11e6-8ec5-ab9017c41841.png)

**Comment by pratu16x7** [comment]
fixed via frappe/frappe#2771
