### ISSUE TITLE
ERPNext Customizing Notifications

### ISSUE THREAD

**Issue by arpitgoyal138** [frappe/erpnext#7810]
Hello,
I have modified frappe-bench/apps/erpnext/erpnext/startup/notifications.py 
But it is not reflecting changes... I think it is not getting executed.
Please tell me what should I do?

Thanks,
Arpit

**Comment by yashodhank** [comment]
@arpitgoyal138 Use https://discuss.erpnext.com to ask questions, this place is exclusively for reporting bugs and issues with software.
