### ISSUE TITLE
Global Search, smaller names, more perfect match should come first.

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#7814]
In the screenshot below, I should see Item first:

---

<img width="724" alt="screen shot 2017-02-22 at 10 46 47 am" src="https://cloud.githubusercontent.com/assets/140076/23198266/528566ee-f8ec-11e6-83bc-2953874db019.png">

**Comment by pratu16x7** [comment]
fixed via frappe/frappe#2760
