### ISSUE TITLE
calendar list holiday problem

### ISSUE THREAD

**Issue by mohdrizalsharif** [frappe/erpnext#7815]
hi please help me an issue  calendar not proper list holiday on calendar.  where i set weekly off on Friday & Wednesday
![calender](https://cloud.githubusercontent.com/assets/25946753/23201183/5f9b081c-f913-11e6-8a42-457e15032033.PNG)

**Comment by TamimDahri** [comment]
Hey I got same problem. Anybody mind to help us?

**Comment by mohdrizalsharif** [comment]
Wish  version are more stable?

**Comment by KanchanChauhan** [comment]
Fixed via https://github.com/frappe/erpnext/pull/7839
