### ISSUE TITLE
Salary Structure picks Global Defaults Currency instead of Company Currency

### ISSUE THREAD

**Issue by keshav-m** [frappe/erpnext#7819]
While defining a Salary Structure when we add employees in the Select employees for current Salary Structure table, the currency symbol displayed beside the amount in the Base column shows the default currency from the Global Defaults from Setup and not the from the currency of the company selected on the top of the form.

**Comment by nabinhait** [comment]
@KanchanChauhan Put `Company:company:default_currency` in Options of amount fields

**Comment by nabinhait** [comment]
Also check for salary slip
