### ISSUE TITLE
Sales Order to Production Order - Click on link doesn't refresh the page

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#7825]
Steps:

1. Save Sales Order.
2. From Menu, selected Production Order.
3. Production Order (in Draft) is created, and a prompt is shown with the link.
4. On clicking a link, though URL is updated, but page to not updated to show drafted Production Order.

![screen shot 2017-02-22 at 5 16 05 pm](https://cloud.githubusercontent.com/assets/910238/23210280/e31aa260-f922-11e6-8f48-3ac6eec000c5.png)

**Comment by rohitwaghchaure** [comment]
Not able to replicate the issue

**Comment by umairsy** [comment]
Still replicating:

![screen shot 2017-02-28 at 3 40 10 pm](https://cloud.githubusercontent.com/assets/910238/23401032/37aed320-fdcc-11e6-8284-406d59a53e03.png)
