### ISSUE TITLE
Production Order - Issue in Scrap management

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#7827]
Steps:

1. Create BOM for mobile phone, with scrap material in it.
2. Created Production Order for BOM item.
3. Created Material Transfer entry against Production Order.
4. When creating Manufacture Entry against Production Order, getting following error message. It seems like system is confusing scrap item with the raw-material item which is also getting added into finish goods warehouse.

![screen shot 2017-02-22 at 5 26 29 pm](https://cloud.githubusercontent.com/assets/910238/23210641/8b7ef7ac-f924-11e6-9634-8bf43f6c2da6.png)

**Comment by umairsy** [comment]
Though this issue doesn't seem related to version 8, still I am adding into V8 milestone, so that it is attended on priority.

**Comment by KanchanChauhan** [comment]
Closing it, could not replicate it.
<img width="1180" alt="screen shot 2017-02-28 at 12 06 56 pm" src="https://cloud.githubusercontent.com/assets/16913064/23394319/7717d25a-fdae-11e6-8a3f-8cd794d3805b.png">
