### ISSUE TITLE
Production Order - Capacity Planning feature not working

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#7829]
Steps:

1. Created BOM with operations in it.

![screen shot 2017-02-22 at 5 43 31 pm](https://cloud.githubusercontent.com/assets/910238/23211152/9f4d04ca-f926-11e6-9ea7-a1a90a7118a9.png)

2. Created Production Order for the Item. But in the Production Order, Operations was not fetched. Also Timesheet was not created automatically.

3. I could complete Production Order without creating Timesheet entry against that Production Order.

![screen shot 2017-02-22 at 5 45 13 pm](https://cloud.githubusercontent.com/assets/910238/23211162/af62681e-f926-11e6-8b55-5342ba6fac2a.png)

Note: In the Manufacturing Settings, we have a feature of Disabling Capacity Planning feature. Even this feature was not enabled.

Since this feature is working fine in an account on master branch, adding it to V8 milestone.

**Comment by rohitwaghchaure** [comment]
Hi @umairsy 

It's working fine, I have checked on develop as well on master branch. Operation are pulling properly on the production order and on submission of production order timesheet has created properly

**Comment by KanchanChauhan** [comment]
Could not replicate again, works fine. Screenshot below.
<img width="1223" alt="screen shot 2017-02-28 at 12 18 11 pm" src="https://cloud.githubusercontent.com/assets/16913064/23394579/0bedfa48-fdb0-11e6-9d80-78c0edf30124.png">

**Comment by umairsy** [comment]
Issue still replicating.

Steps:

1. Created Sales Order
2. Production Order from Sales Order.
3. In the Production Order made from Sales Order, operations table is not fetched from Production Order. Only if I manually reselect BOM in the Production Order, it fetches Operations from BOM.
