### ISSUE TITLE
Return to stock unprocessed material from subcontract

### ISSUE THREAD

**Issue by krishnanhemanth** [frappe/erpnext#7831]
Hi
how do i take in to account unprocessed material lying at the subcontract
heres an example
stock entry 10mts(1 item) of rod to subcontract
he uses 5mtrs to produce /repack 100 nos
he sends me back 5mtrs(1 item) + 100 nos
100 nos can be taken in to stock (no problem here)
but how to take the 5mtrs in to stock
regards
Hemanth

**Comment by ankush** [comment]
https://github.com/frappe/erpnext/pull/26119
