### ISSUE TITLE
Purchase price and Selling price in Item Master

### ISSUE THREAD

**Issue by prash4** [frappe/erpnext#7834]
In the item master , we are able to see the supplier details .

We need to add the purchase price and the selling price in the same item master .

So when we open an item , we can see the supplier name and the purchase price .

We have put the selling price and the purchase price in the price list .

but , we are not able to see them in the item master .

Is there a way we can link them , to see all the details in the master.

**Comment by joezsweet** [comment]
You can add a custom field and a custom script to show prices in item master under supplier child table

**Comment by yadavyk** [comment]
Please refer : [Price Lists](https://docs.erpnext.com/docs/v13/user/manual/en/stock/price-lists)
