### ISSUE TITLE
Delivery Note / Sales Order didn't change status when Items Delivered are Different Batches

### ISSUE THREAD

**Issue by addymuliady** [frappe/erpnext#7836]
Workflow - SO>DN>SI

1. We have created an SO with a quantity 20.
![image](https://cloud.githubusercontent.com/assets/21187126/23247043/b02c2f4e-f9d2-11e6-9036-b9275d523801.png)

2. We created a DN. The items were taken from different batches.
![image](https://cloud.githubusercontent.com/assets/21187126/23247056/c85387ac-f9d2-11e6-9fec-76a9cab47690.png)

3. However, SO - still show "To Deliver" and "Bill". It should be "To Bill".

4. Then we created an SI and make payment. The Delivery Note still shows "To Bill". It should be another Status such as "Invoiced". SO still shows as "To Deliver and Bill".

![image](https://cloud.githubusercontent.com/assets/21187126/23247233/d2f2c398-f9d3-11e6-98e0-def1a3d5e3c1.png)

Workflow - SO>SI>DN

1. Sales Order status changed to "Completed" when Delivery Note is submitted. So no issue.

2. However, even though DN created with all items and SI status is "Paid", the DN status is still "To Bill".

**Comment by nabinhait** [comment]
How are you adding the second row in the Delivery Note? Are you adding the 2nd row manually, after pulling first row from sales order.
May be one/both rows does not the reference of sales order.

**Comment by addymuliady** [comment]
Yes, I added the second row manually. Else, how do you suggest to do different batches?

Of course, we are able to do separate delivery notes for different batches at the moment but in terms of user needs, it has to be able to transact under 1 delivery note.

**Comment by nabinhait** [comment]
After pulling first row from Sales Order, change the qty as per batch 1. Then again pull the item from Sales Order using "Get Items From" button, it should pull pending qty in a separate row, assign it batch 2.

This way it will update delivered qty in Sales Order for both rows.

**Comment by mobentec** [comment]
Hi @nabinhait This solution does not seem to work.  When I tried following your steps by Sales Order-->MAKE-->Delivery; then allocate batch 1 to item and update quantity; then (without saving or submitting anything) used the "Get Items From" button.  However, that button is adding every single line item from the Sales Order and reinserting them into the Delivery Note.  If the Sales Order has 5 items, the Delivery Note now ends up having 10.

From your description, I thought by pushing the "Get Items From" button was supposed to insert only the missing/remaining item and its remaining quantity; at which point we would assign it batch 2.

We really need to be able to assign multiple batches of a single item on a Delivery Note so our staff can 1) pick the product; 2) customers have a printout record of what was sent to them.  Are we missing a step?  Is there another way to accomplish listing more than one batch number on a Delivery Note?

Thank you!
