### ISSUE TITLE
Calendar view - Holiday List View

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#7845]
In a new Calendar, view of Holiday List is incorrect. All the events are shown in today's date only, and not on the Date mentioned in the Holiday List master.

![holiday-list-calendar-view](https://cloud.githubusercontent.com/assets/910238/23291482/fcb4a196-fa7e-11e6-9c36-eb2d9a179292.gif)

**Comment by umairsy** [comment]
Instead, Holiday List events are shown correctly when select Leave Application from the Menu.

![screen shot 2017-02-24 at 10 51 11 am](https://cloud.githubusercontent.com/assets/910238/23291521/36d8101a-fa7f-11e6-97e1-63ad440d2b75.png)

**Comment by nabinhait** [comment]
This has been fixed yesterday.
