### ISSUE TITLE
Stock reconciliation with sub-warehouses

### ISSUE THREAD

**Issue by fredluhamaa** [frappe/erpnext#7847]
Getting Items in Stock reconciliation should allow to select Items from  "Is Group" warehouse, otherwise it's impossible to count inventory if Warehouse hierarchy tree is used as shelf/location/racks.

For example:

-- Main Warehouse - **Is Group**
----- Shelf Rack 1
----- Shelf Rack 2 - **Is Group**
--------- Shelf Rack 2 - Bin 1
--------- Shelf Rack 2 - Bin 2

It should be possible to select Items from "Main Warehouse" and get list with Items and Warehouses they belong to under that group.

Items should be returned as following (for example each "warehouse" contains 1 item)

| Item Code | Warehouse | Quantity | Valuation Rate |
|:----------- |:-------------:|-----------:|----------------:|
12345 | Shelf Rack 1 | 100 | 100
12346 | Shelf Rack 2 - Bin 1 | 50 | 120
12347 | Shelf Rack 2 - Bin 2 | 10 | 30

So we can download CSV, make item counting and upload back easily.

**Comment by fredluhamaa** [comment]
Bump. Any thoughts on this issue from anyone from Frappe team?
Thanks.

**Comment by Devens** [comment]
+1

**Comment by sharmanakul** [comment]
i think this works like that only as of today.
