### ISSUE TITLE
Select Print Format from Custom Script

### ISSUE THREAD

**Issue by fotocreaman** [frappe/erpnext#7849]
We need to be able to select a specific print format from a custom script. We use quotation for 2 different types and they have both their print format. One is a repair quotation, the other is a "normal" sales quotation.
So I would like to select the appropriate format from the custom script.

**Comment by mhbu50** [comment]
+1

**Comment by zabeehkhan** [comment]
Is there any update on this feature?

**Comment by zabeehkhan** [comment]
I was able to achieve this by adding a custom "Print" button in the DocType and adding the following custom script for it:

`
frappe.ui.form.on("Memo", { 
print: function(frm, cdt, cdn) {

var me = this;
var doc = frm.doc
var print_format = frm.doc.memo_type; // print format name

var w = window.open(frappe.urllib.get_full_url("/printview?"
	+"doctype="+encodeURIComponent(cdt)
	+"&name="+encodeURIComponent(cdn)
	+"&trigger_print=1"
	+"&format=" + print_format
	+"&no_letterhead=0"
	+(me.lang_code ? ("&_lang="+me.lang_code) : "")));

	if(!w) {
		msgprint(__("Please enable pop-ups for printing.")); return;
	}
}
});
`
I would just need to hide / disable the default print button.

**Comment by zabeehkhan** [comment]
The ideal thing would be to be able to pass the print format name to print_doc:
``` frm.print_doc(print_format); ```

**Comment by basant13** [comment]
@zabeehkhan Bro Can you please explain me the whole process. I need to print different row from the table separately.

**Comment by kennethsequeira** [comment]
Closing this thread due to inactivity and also since this is a customization related thread.

All customization questions should be posted on the community forum: https://discuss.erpnext.com

GitHub is strictly to be used for posting bugs and feature requests.
