### ISSUE TITLE
Salary Structure, Formula if Condition = False

### ISSUE THREAD

**Issue by epochc** [frappe/erpnext#7855]
Hi, Please consider adding this enhancement as shown in attached image. Please ignore content of the Condition in the Image. For demonstration purposes only.

Details: Enhancement to include a condition (currently supported in ERPNext) and a formula if the condition = true (currently supported in ERPNext) and another formula if the condition = false (proposed enhancement).

That will ensure that organizations will need to maintain fewer salary structures.

![salarystructure](https://cloud.githubusercontent.com/assets/18049961/23300622/5beb786a-faac-11e6-9180-a0aa38fff795.jpg)

**Comment by nabinhait** [comment]
@epochc I think you can achieve this by using 2 rows, one for true conditions and other for false
