### ISSUE TITLE
ERPNext v8 Features

### ISSUE THREAD

**Issue by stelden** [frappe/erpnext#7862]
Great new features coming up in v8. We would want to see the following simple additions to complete the features in:

    Customer Feedback
    a) A connection between feedback results and employee appraisal

    Employee Loan Management
    a) Rules/constraints for borrowing e.g. an employee cannot borrow more than n% of net salary (or savings) or employee cannot have more than n outstanding loans
    b) Maximum loan-book for a company as a flat figure or a percentage of some predefined account e.g. previous years net earnings
    c) Some sort of employee savings scheme (the opposite of loans) where employees can save a fixed amount from their pay into an account (such as b above) and borrow from the same using rules in a above.

**Comment by mansonkibe** [comment]
was this feature introduced?
