### ISSUE TITLE
Final Manufacture Entry

### ISSUE THREAD

**Issue by dineshpanchal93** [frappe/erpnext#7864]
Hi all,

We need solution of Multiple Stock Entry "Material Transfer to Manufacture" of against one Production order(Qty 1 ). and final we make Manufacture entry of that Production order, it will fetched all the items from Stock entry against related to Production order.

Right now, we can able to create only one Stock entry against production order.  
when we trying to add more stock entry against production order. gives me an error 
**"Material Transferred for Manufacturing (2.0) cannot be greater than planned quantity (1.0) in Production Order PRO-0002"**

Please do suggest me a solution.

"

**Comment by aptech-admin** [comment]
+1

Really needed improvement

**Comment by dineshpanchal93** [comment]
Yes we Solution for that. Please support

**Comment by dineshpanchal93** [comment]
Any Update on this ?

**Comment by djpalshikar** [comment]
+1
This is affecting us also, if there are items are added to the stock entry apart from the ones present in the BOM, we get the same message.

**Comment by dineshpanchal93** [comment]
This issue again arrived.

Please kindly look into this asap.

https://discuss.erpnext.com/t/manufacturing-issues-in-version-11/47349

**Comment by dineshpanchal93** [comment]
Allow to add items in manufacturing process which are not part of bom items #12110

Please update on the same.

**Comment by CloudERPng** [comment]
This appears n ot to be resolved yet

**Comment by mrodriguez614** [comment]
Hi everyone!
We're using ERPNext v13 and we also have the same issue above. Are there any updates on this?

**Comment by sharmanakul** [comment]
similar to #28377
