### ISSUE TITLE
Custom Serial number for serialised Items

### ISSUE THREAD

**Issue by krishnanhemanth** [frappe/erpnext#7865]
Hi
There are 2 issues that need to be addressed in the Serial number for serialized Items
1) custom start the serial number
An user should be able to assign a starting serial number for serialized items and then the system should take the serial number forward
presently, the system starts from 1 by default
2) option to delete serial numbers if corresponding material is deleted from stock and assign those serial number again
now the system takes forward the serial number inspite of the corresponding stock entry is cancelled and deleted
Regards
Hemanth

**Comment by yadavyk** [comment]
Please refer : [Serial Number](https://docs.erpnext.com/docs/v13/user/manual/en/stock/serial-no)
