### ISSUE TITLE
pull request for the new HU chart of account

### ISSUE THREAD

**Issue by krnkris** [frappe/erpnext#7866]
I just finished the new 2017 CoA for Hungary.

Could you please pull it to the next master.

https://charts.erpnext.com/chart?company=Hungary%20-%20Chart%20of%20Accounts&forked=1&submitted=1

Thank you!

ISSUE:
If I FORK from this new chart, then the fork I get is from the STANDARD-1 base chart instead of my.

**Comment by krnkris** [comment]
Please do pull for the Version 7 as well

**Comment by nabinhait** [comment]
https://github.com/frappe/erpnext/pull/10312
