### ISSUE TITLE
Summernote fixes 27 Feb 2017

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#7873]
1. Reduce options on small screen
2. Use `<br>` instead of `<p>` on enter

---

<img width="737" alt="screen shot 2017-02-27 at 3 32 16 pm" src="https://cloud.githubusercontent.com/assets/140076/23357085/47207d56-fd02-11e6-94fd-cc2a1e66857f.png">

**Comment by netchampfaris** [comment]
https://github.com/frappe/frappe/pull/2775
