### ISSUE TITLE
[Global Search] Single DocTypes should not appear in "List"

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#7874]
Maybe make a new section "Settings"

<img width="720" alt="screen shot 2017-02-27 at 3 59 16 pm" src="https://cloud.githubusercontent.com/assets/140076/23357958/f4ae3262-fd05-11e6-8fdb-3b445e4bd752.png">

**Comment by pratu16x7** [comment]
Bundled under "Setup": frappe/frappe#2774
