### ISSUE TITLE
[wording] Kanban Board

### ISSUE THREAD

**Issue by vrms** [frappe/erpnext#7881]
I think the term kanban comes from the japanese and means (same as in Chinese I think) something like "a board to look at". 

**kan** 看 = see, look at, **ban** 板 = board

so the term **Kanban Board** is a bit silly because it means something like "a board to look at board"
I suggest either to use either **Kanban** or **Board** for the current term **Kanban Board**

**Comment by aboganas** [comment]
@vrms the root of the word doesn't matter, what matter is the wide spread agreed upon definition that given to the word.
When you use **Kanban** by itself, people associate it with Kanban process or approach for managing and scheduling  manufacturing process. here is the wiki [Kanban](https://en.wikipedia.org/wiki/Kanban), also for the case of software development, **Kanban** by itself means the software management system that developers can use to make a decision. here is the wiki [Kanban](https://en.wikipedia.org/wiki/Kanban_(development))

but **[Kanban Board](https://en.wikipedia.org/wiki/Kanban_board)** is widely agreed  on and understood to be a tool of visualization for Kanban method. here is the wiki [Kanban Board](https://en.wikipedia.org/wiki/Kanban_board)

At least this how **Kanban** and **kanban Board** are understood in English, maybe its differentiated in another way in Chinese and Japanese . and Erpnext just use the visualization part of Kanban; therefore, Kanban board is the correct use in that case.

**Comment by vrms** [comment]
seems I'm all alone with this ... not relevant then I guess, closing this therefore
