### ISSUE TITLE
Error when trying to restore a deleted document

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#7883]
Steps:

1. Submitted Sales Order
2. Cancelled and Deleted it.
3. Came to Deleted Docs list and tried restoring it. Error message received when click on Restore button.

![screen shot 2017-02-28 at 3 50 24 pm](https://cloud.githubusercontent.com/assets/910238/23401432/aa1b38b2-fdcd-11e6-9ae9-4c1358054204.png)

**Comment by KanchanChauhan** [comment]
Submitted document which are deleted cannot be restored again.

**Comment by umairsy** [comment]
Then we should not show deleted transactions where were canceled/submitted. If at all we show them, it should not have Restore button on it. Or at least a validation message.
