### ISSUE TITLE
Auto-numbering for Communication. System generated nos. doesn't look good.

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#7884]
![screen shot 2017-02-28 at 3 54 46 pm](https://cloud.githubusercontent.com/assets/910238/23401604/50d25276-fdce-11e6-896f-9b5086d467ff.png)

**Comment by pratu16x7** [comment]
Perhaps we shouldn't show communications on their own but in the context of their source doctypes of creation. Will remove the standalone results for now. frappe/frappe#2790
