### ISSUE TITLE
Labeling is Wrong. update required 

### ISSUE THREAD

**Issue by shaalam** [frappe/erpnext#7895]
Payment voucher is in USD, payment allocated also in USD but labeling is in AED.

![erp next](https://cloud.githubusercontent.com/assets/25928492/23447514/f24dc400-fe64-11e6-9107-340254ad8ab1.png)

**Comment by Arundhatii** [comment]
Seems to be working fine in the test account. It is picking up the Company currency.
![screen shot 2017-03-22 at 3 08 23 pm](https://cloud.githubusercontent.com/assets/20164097/24191464/f20b5f12-0f11-11e7-8611-6516ddba631f.png)

**Comment by bcornwellmott** [comment]
I've noticed this issue before too. It seems sporadic - I think the browser uses cached data from previously opening other documents or something. Refreshing the page and clearing cache ixes the issue.

**Comment by pratu16x7** [comment]
It would be great if this can be replicated is some definite way.

**Comment by tundebabzy** [comment]
I guess we can close this pending when we are able to get steps to replicate this in a definite way.
