### ISSUE TITLE
Minimum manufature amount

### ISSUE THREAD

**Issue by chanlung** [frappe/erpnext#7902]
There should be a minimum manufacture amount. i.e. when manufacturing an item I have to produce at least a certain amount (probably because it's not worth doing less than the level or unable to without wasting materials).

I'm assuming this would be similar to a MOQ for purchasing.

**Comment by sharmanakul** [comment]
Would be best if you mention the proper use-case and the some mock ups. This helps us in prioritizing the feature requests
