### ISSUE TITLE
Tax deduction rounding up

### ISSUE THREAD

**Issue by ishanloya** [frappe/erpnext#7907]
In tax deductions for salary slips, the ESIC deduction amount needs to be rounded up always as per Govt. rules. Is there a way I can round up this calculation in the salary structure? Round doesn't work, nor does Math.ceil()

Currently I'm using this in the formula: `int(base * 0.01 - 0.001) + 1.0` to always round up. The -0.001 is for numbers that are already whole numbers. E.g. so that 212.0 is not rounded up to 213.0.

[Forum link](https://discuss.erpnext.com/t/tax-deduction-rounding-up/20735)

**Comment by harshit-30** [comment]
Please create another issue if it is replicable in v13.10.
