### ISSUE TITLE
barcode reader in POS

### ISSUE THREAD

**Issue by Golive-solutions** [frappe/erpnext#7910]
Dear all,

I hope you are fine
I have a problem regarding to barcode reader in POS, let me descrip my issue deeply.

In normal case I set the barcode in item master and it works successfully in POS, but the problem is (there are items are weighted by scale machine ) and scale machine printout label immediately
contains barcode and weight together in one label as the picture below
![60a46c31-47a5-4c1b-8185-15f06447ee65](https://cloud.githubusercontent.com/assets/26138822/23505215/44f455de-ff4b-11e6-82fa-662123192192.jpg)

The first 7 degits express the barcode, and last 6 digits express the weight.
What i need is in scanning erpnext divides barcode automatically into (item code - weight in quantity).

Thanks

**Comment by mhbu50** [comment]
+1

**Comment by Golive-solutions** [comment]
@KanchanChauhan 

kindly advise

**Comment by yadavyk** [comment]
Please refer : [POS](https://docs.erpnext.com/docs/v13/user/manual/en/accounts/point-of-sales)
