### ISSUE TITLE
Production order from Sales Order

### ISSUE THREAD

**Issue by Devens** [frappe/erpnext#7914]
If Production order is being made from Sales order then it should display only relevant items for selected sales order and not all items. 

![untitled_clipping_030217_060851_pm](https://cloud.githubusercontent.com/assets/10671911/23507474/4e484bae-ff73-11e6-86ac-32e139c19a08.jpg)

**Comment by kennethsequeira** [comment]
Creating Work Order from Sales Order let's one select the correct items before hand. 

This is a problem if only creating it manually. Even then, the validations make sure to raise an error if qty/items do match those in Sales Order
