### ISSUE TITLE
General Ledger / Stock Ledger report - When access from transaction, filter not auto-applied

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#7915]
Steps:

1. Submitted Delivery Note (DN-0000#).
1. In the View option, selected Stock Ledger.
1. In the Stock ledger report, filter is not applied on transaction (DN-0000#).

Same way, when access General Ledger report from accounting transaction, in the General Ledger report, default filter of transaction ID is not auto-applied.

**Comment by nabinhait** [comment]
Fixed
