### ISSUE TITLE
New chart of account for France

### ISSUE THREAD

**Issue by chdecultot** [frappe/erpnext#7916]
Dear Frappe Team,

I have just submitted a new version of the full chart of account for France:
https://charts.erpnext.com/chart?company=France%20-%20Plan%20Comptable%20G%C3%A9n%C3%A9ral-6&forked=1&submitted=1

Could you please consider integrating it in the next version of ERPNext ? Can it be the default CoA for France or is there another process to follow ?

Thanks a lot in advance!

PS: As mentioned in #7866 it is not possible to fork a chart in charts.erpnext.com. It would be great if that could be corrected.

Additionnally, if we could make an export of the chart in JSON for immediate use, that would be great since it represents a lot of work.

Best regards,

Charles-Henri

**Comment by nabinhait** [comment]
https://github.com/frappe/erpnext/pull/10312
