### ISSUE TITLE
Tax Calculation - Roundoff Included in Last Tax Row

### ISSUE THREAD

**Issue by akshay83** [frappe/erpnext#7918]
Why is the System including Round-off Value in last Tax row. As seen here : 

![image](https://cloud.githubusercontent.com/assets/7766272/23554808/94741610-004c-11e7-8965-2c220aba1071.png)
This was a Test done on demo.erpnext.com

This is scenario which comes up when using pre-configured Taxes Template in Sales Invoice. Simple Steps to Reproduce:
1. In Sales Invoice, select any Item with qty 1 and input 15,000 as Rate.
2. Add two taxes row, one with Rate as 14 and another with Rate as 0.
3. Check Mark 'Is this Tax included in Basic Rate?' in all taxes rows.

The above situation can also be replicated if we use Item-wise Taxes and fetching a Tax Template in Sales Invoice. eg. 
1. Item A has default Item-wise Tax as 14% and Item B has 5%. 
2. Create a Sales Tax Template having two Rows, one with 14% Tax and another with 5% Tax both having 'Is this Tax included in Basic Rate?' as checked AND template having rate set as 0. In order to fetch default item tax.

I hope I have been able to clearly explain the problem.

**Comment by vrms** [comment]
not clear, what how you think the system to behave. can you add that as `expected behavior`?

**Comment by akshay83** [comment]
only tax with rate 14% should get filled/calculated. Here the system is calculating another tax also with just .01 as the amount, which seems to be a rounding issue.
