### ISSUE TITLE
Issues in Shopify Connector

### ISSUE THREAD

**Issue by manivk** [frappe/erpnext#7920]
Just wanted to bring to your notice a lot of issues in the shopify connector. Please treat this as a feedback if the connector has to work effectively
 
1.      Think you need to give options to the customer on what they want to sync – customer data, product data, pricelist, sales order, etc. Because otherwise the connector plays havoc with our data in ERPNext and sometimes we are unable to figure out what went wrong. For e.g., the shopify connector has add some new item codes for a few items and we are struggling to figure now when we choose the items in other documents. 
2.      I had chosen Pricelist A (just for reference) in the connector. But the connector has gone and changed prices of the synced items in all pricelists (Pricelist B and C) where that item exists. Don’t know why. This has screwed up the entire billing for us. Unfortunately we did not see this and  now we have a mammoth task to rectify.
3.      And there has to be a way to test the connector without having to do so in live environment. Because once the connector does its job, we are stuck with some massive corrections which we cannot undo.
4.  And finally, your Shopify connector is matching products by the name of the product rather than the item code. The connector should match by SKU ID in Shopify and the item code in our system. Instead, it is going by the product name. The name I may use in the ERP and the name I use in Shopify could be quite different (or even slightly different), but the system is syncing all the wrong products. It also created a whole lot of new products in the ERP and now I am sitting on duplicate products in the system, need to modify all the sales invoices etc. now to delete these duplicate products.

Request you to test this a little more and I think the use cases for this connector has not been thought through properly.

Thanks
Mani.

**Comment by kennethsequeira** [comment]
Closing as the Shopify integration has been refactored since. 

Newer issues may reflect recent issues.
