### ISSUE TITLE
Set Default Standard Reply for Doctype

### ISSUE THREAD

**Issue by sbkolate** [frappe/erpnext#7921]
In v7, We can add jinjha template for Standard Reply

If we add feature to set standard reply for doctype, then it will be helpful to speed up email sending process, it will also helpful to use Email feature of ERPNext extensively

e.g
For quote, one can set email reply as
Hello {{Customer}},

Please find attached Quote.

For Invoice one can set email reply as.

Hello {{Customer}},

Your Invoice {{name}} is created, please find attached pdf.

Thanks,
{{Company Signature}}

Reference:
https://discuss.erpnext.com/t/how-to-add-jinja-templates-in-standard-reply/14128/10

Although, this can be achieve using email alerts, but in many cases client can not send same message while quoting bid.

**Comment by Devens** [comment]
Long overdue... +1

**Comment by mhbu50** [comment]
+1

**Comment by joolsr** [comment]
@erpnext Any possibility to get this implemented? 7 '+1's are quite a few demonstrating a real need for this ..

**Comment by OneiricIT** [comment]
After this too.

**Comment by jhquiroga** [comment]
This will make a big improvement in company's communications

**Comment by rmehta** [comment]
Standard Reply is not "Email Template" and it does work as a Jinja template.
