### ISSUE TITLE
[Issue] Stock Entry - Change "Is Sample Item" to "Allow Zero Valuation Rate"

### ISSUE THREAD

**Issue by bohlian** [frappe/erpnext#7928]
It is confusing to the user what "Is Sample Item" is. It actually means that the stock can be entered with a valuation rate of 0.

https://discuss.erpnext.com/t/opening-stock-balance-without-valuation/20950/6

**Comment by Olawale1** [comment]
Hi,

Could you please update the error message as well? When trying to Submit a Stock Entry or Delivery Note with Zero Value items, the error message still refers to the "Is Sample Item" field

Kind regards,
