### ISSUE TITLE
reopen #7601

### ISSUE THREAD

**Issue by ioweb-gr** [frappe/erpnext#7930]
Hi,
I'm asking you to reopen #7601 because apparently once closed an issue is never looked at again.
I've stepped through the whole code regarding variation creation in a clean system. and this issue can be reproduced 

I've pinpointed the exact location of the bug in the code that breaks variants with numeric attributes. 

As a request, when an issue is not easy to reproduce instantly, don't close it immediately and ignore it thereafter but instead it's better to ask for extra info that might be necessary to troubleshoot it. If it happens in one system, it will happen again in another. 

In that case we should try and determine first if it's caused by external parameters or by the application itself and then chose safely the proper action. You can add a tag like "needs more info", "needs investigating" etc.

**Comment by rmehta** [comment]
point noted. Closing this since #7601 is re-opened.

**Comment by ioweb-gr** [comment]
Thanks for hearing me out @rmehta. Could you reopen #7601?
