### ISSUE TITLE
Print Format Builder Issue

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#7932]
In a Print Format created using Print Format builder, following doesn't work.

If Item Code is checked, but Item Name is not checked, then Item Code won't show up in the print format.

![print-format-issue](https://cloud.githubusercontent.com/assets/910238/23606662/bc6931cc-0287-11e7-81c0-2f32ccc3fbc5.gif)

**Comment by rohitwaghchaure** [comment]
Issue fixed in version 8
