### ISSUE TITLE
[v8] Error on bech update

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#7935]
Hello,

Running a bench update after last update shows this error:

> Executing frappe.patches.v7_3.set_ref_doctype_roles_to_report in 192.168.1.42 (d56cb677eaab3383)
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
>     "__main__", fname, loader, pkg_name)
>   File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
>     exec code in run_globals
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 79, in <module>
>     main()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 16, in main
>     click.Group(commands=commands)(prog_name='bench')
>   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 696, in main
>     rv = self.invoke(ctx)
>   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
>     return callback(*args, **kwargs)
>   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
>     return f(get_current_context(), *args, **kwargs)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 24, in _func
>     ret = f(frappe._dict(ctx.obj), *args, **kwargs)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 210, in migrate
>     migrate(context.verbose, rebuild_website=rebuild_website)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/migrate.py", line 30, in migrate
>     frappe.modules.patch_handler.run_all()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 29, in run_all
>     if not run_single(patchmodule = patch):
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 63, in run_single
>     return execute_patch(patchmodule, method, methodargs)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 83, in execute_patch
>     frappe.get_attr(patchmodule.split()[0] + ".execute")()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/patches/v7_3/set_ref_doctype_roles_to_report.py", line 10, in execute
>     doc.set_doctype_roles()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/report/report.py", line 50, in set_doctype_roles
>     doc = frappe.get_meta(self.ref_doctype)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 619, in get_meta
>     return frappe.model.meta.get_meta(doctype, cached=cached)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/meta.py", line 30, in get_meta
>     return frappe.cache().hget("meta", doctype, lambda: Meta(doctype))
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 171, in hget
>     value = generator()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/meta.py", line 30, in <lambda>
>     return frappe.cache().hget("meta", doctype, lambda: Meta(doctype))
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/meta.py", line 65, in __init__
>     super(Meta, self).__init__("DocType", doctype)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 84, in __init__
>     self.load_from_db()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/meta.py", line 70, in load_from_db
>     super(Meta, self).load_from_db()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 115, in load_from_db
>     frappe.throw(_("{0} {1} not found").format(_(self.doctype), self.name), frappe.DoesNotExistError)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 312, in throw
>     msgprint(msg, raise_exception=exc, title=title, indicator='red')
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 302, in msgprint
>     _raise_exception()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 275, in _raise_exception
>     raise raise_exception, encode(msg)
> frappe.exceptions.DoesNotExistError: DocType Time Sheet not found

**Comment by nabinhait** [comment]
fixed
