### ISSUE TITLE
Split production into multiple workstation in timesheet

### ISSUE THREAD

**Issue by munimaubdullah** [frappe/erpnext#7940]
Suppose we have 5000 amount of production order and it needs 400 minute. We planned to work on workstation 1, but after finishing 200 item we decide to change the work station ex workstation 2. Or we might want to split the task in workstation 2 and workstation 3. So there should be option to split into multiple work station.

**Comment by walchandwarik** [comment]
Such splitting is necessary. Such splitting happens everyday at shop floor.

**Comment by giuseppelamatrice** [comment]
+1

**Comment by sharmanakul** [comment]
@munimaubdullah @walchandwarik @giuseppelamatrice could any of you try to define a flow or create some mockup for this? This will help us in prioritizing this.
