### ISSUE TITLE
provide possibility to change the first day of the week to Monday

### ISSUE THREAD

**Issue by vrms** [frappe/erpnext#7943]
half of the world (estimate) has Monday as the first day of the week.
However ERPNext does currently not allow to change the first day of the week in it's Calendar to Monday
This should be possible to be setup (and changed any time) for each Company under >Setup >[Company Name]

**Comment by joezsweet** [comment]
👍

**Comment by joezsweet** [comment]
Sent a pull request: 

https://github.com/frappe/frappe/pull/2894

**Comment by joezsweet** [comment]
fixed on last frappe version

**Comment by joezsweet** [comment]
This is fixed, please reopen if other issue will comes up.

**Comment by umairsy** [comment]
Duplicate - https://github.com/frappe/erpnext/issues/4484
