### ISSUE TITLE
[v8]Image view grey screen

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#7944]
Hello,

After last update the image view on item is greyed out, and no information is shown

**Comment by rmehta** [comment]
Can you share a screenshot along with your JS Console trace?

**Comment by applepipe** [comment]
Hello @rmehta 

here is the screenshot with the console

![screen shot 2017-03-09 at 13 39 19](https://cloud.githubusercontent.com/assets/18335894/23760289/fc86da14-04cd-11e7-9a3b-0fadd4b530b7.png)
