### ISSUE TITLE
Enhancement Process Payroll

### ISSUE THREAD

**Issue by KanchanChauhan** [frappe/erpnext#7946]
- [ ] Payroll as doctype
- [ ] Child table - Salary Slip info
- [ ] JV Entry Button
- [ ] Make Payment Entry Button

**Comment by Tropicalrambler** [comment]
Will this inclue rounding
to prevent the error discussed here  ?https://discuss.erpnext.com/t/error-when-making-bank-entry-in-payroll-processing/20943/15

**Comment by sumitdas4u** [comment]
is it fixed ? to prevent the error discussed here ?https://discuss.erpnext.com/t/error-when-making-bank-entry-in-payroll-processing/20943/15

**Comment by dawoodjee** [comment]
Here's my contribution.

1. Payroll Entries should also allow the selection of already created payslips. This will allow alot of flexibility.
2. Make Bank Entry should be renamed to Make Journal Entry or Make Payment Entry (a bit confusing). Because some payments are done by cash and other means.
