### ISSUE TITLE
Production Plan DocType -> Redesign Production Planning Tool

### ISSUE THREAD

**Issue by KanchanChauhan** [frappe/erpnext#7947]
- [ ] Production Plan Doctype
  - [ ] From / To Date
  - [ ] Items child table (set quantities)
  - [ ] For Warehouse
  - [ ] Status (% complete)
- [ ] Add Production Plan link in Material Request
- [ ] Add Production Plan link in Production Order

**Comment by bcornwellmott** [comment]
What is the purpose of benefit of this?

**Comment by rmehta** [comment]
@bcornwellmott see updated description

**Comment by bcornwellmott** [comment]
Thank you,

I'm wondering how this is going to work. 

For example, with status:
There are two major components for the PPT - Purchasing and Production. I'm not sure how you can characterize a % status with both these tools.

With MR and PrO documents, adding the Production Plan link can make sense, but what happens with items that are already in stock? Those won't be assigned to the production plan, so you will still have a disconnect between some items being allocated to the plan and others that aren't.

I guess I'm trying to understand the added value in having a Production Plan document that the current tool doesn't provide.

**Comment by sharmanakul** [comment]
^ as mentioned in the connected link, the production plan is already enhanced to incorporate many of the features mentioned above. 
I'm not sure, how value adding % status feature is. A descriptive status, such as not started, in progress, completed, is already provided for the production plans.

Providing links in the material requests and work orders can be userful and i'll create a separate GitHub issue for that.
