### ISSUE TITLE
Have a Salary Component that Aggregates Other Components

### ISSUE THREAD

**Issue by stelden** [frappe/erpnext#7948]
Hello,

As per the discussion [here](https://discuss.erpnext.com/t/how-to-map-requirement-in-formula-in-salary-structure/21046):

Given a scenario such as:

Taxable Pay Tax Rate (%)
0 - 10,000 10%
10,001 - 20,000 15%
20,001 - 30,000 20%
30,001 - 40,000 25%
40,000 and above 30%

One has to create a salary component of 'Taxable Pay' for each tax band. Since only a single formula can be applied per rule so one must evaluate twice for true and false. Eventually you end up having as many Salary Components on the payslip as the Tax Bands you created (5 for the above case). It gets worse if you have more. 

Is there an elegant way of making some Salary Components aggregates of others e.g. a 'Total Taxes' component to sum all the 'Taxable Pay' components and to ensure the aggregate is what is printed instead of the others?

**Comment by jwrober** [comment]
I've discussed this in a number of discuss posts about the need to have more logic capabilities in the salary component formulas. This is also a SELECT() type deal where a total gross_salary value is used to determine the taxable rate. This is big in the US as there are many tax table bands based on multiple factors. This kind of enhancement would greatly improve the re-usability of salary components on varying salary structures. You could also reduce the number of salary structures to maintain.

**Comment by ckosiegbu** [comment]
This might help https://github.com/frappe/erpnext/pull/8429

**Comment by jwrober** [comment]
Can you give an example as to how that would work?

**Comment by stelden** [comment]
For me the issue was addressed by the 'Statistical Component' option in Salary Detail. 

Now I can use a Salary Component as many times as I need to (evaluating twice for each condition) in calculations by setting 'Statistical Component' and then have the final result in a 'Not Statistical Component'.

**Comment by stelden** [comment]
@jwrober since this was solved, perhaps we could close this issue and open a more specific one to your requirements?

**Comment by jwrober** [comment]
done
