### ISSUE TITLE
Sales Invoice export to excel (data filled in form with custom fields)

### ISSUE THREAD

**Issue by ajay-eurosteel** [frappe/erpnext#7950]
We would like sales invoice (data filled in form with custom fields) to export to excel

**Comment by strixaluco** [comment]
Have you tried exporting to .csv via [Data import tool](https://frappe.github.io/erpnext/user/manual/en/setting-up/data/data-import-tool)?

**Comment by rmehta** [comment]
@ajay-eurosteel data import tool will give you a template that should work for custom fields. If you get stuck, feel free to post on the forum https://discuss.erpnext.com
