### ISSUE TITLE
Not able to select the date on enter key for the calendar

### ISSUE THREAD

**Issue by rohitwaghchaure** [frappe/erpnext#7961]
Selection of date using enter key not working
![screen shot 2017-03-08 at 7 11 10 pm](https://cloud.githubusercontent.com/assets/8780500/23706190/28dfdcaa-0433-11e7-8420-c24f177f2315.png)

**Comment by saurabh6790** [comment]
Not able to reproduce

![date_selection](https://cloud.githubusercontent.com/assets/3784093/23848115/a83892aa-07fb-11e7-81a6-b6d5d439ef02.gif)
