### ISSUE TITLE
I can not unhide the "naming_series" field.

### ISSUE THREAD

**Issue by Gleisson03** [frappe/erpnext#7962]
I am using a new account in ERPNext Online ...

I can not unhide the "naming_series" field.

Steps:
1st -> I clicked on Custom Form;
2º -> I clicked the "naming_series" field and deactivated the option "Hide"
3rd -> I updated the form and reloaded the system.

Note: I have installed on my virtual machine and have already done this process before
## Update: It seems that this problem is only in DocType "Item"

**Comment by KanchanChauhan** [comment]
Go to Stock -> Stock Settings and set `Item Naming By` as `Naming Series`, then you should be able to see Naming Series in Item.
