### ISSUE TITLE
Message is going outside the dialog on exporting customizations

### ISSUE THREAD

**Issue by nabinhait** [frappe/erpnext#7972]
<img width="1009" alt="screen shot 2017-03-09 at 6 14 18 pm" src="https://cloud.githubusercontent.com/assets/836784/23750760/74d88046-04f4-11e7-9464-5e07efe97c01.png">

**Comment by netchampfaris** [comment]
Cannot replicate
![image](https://cloud.githubusercontent.com/assets/9355208/23849293/0b33e314-0801-11e7-868d-3fe09d9646f3.png)

**Comment by nabinhait** [comment]
@netchampfaris I think if bench name does not have "-" , it will not be wrapped.

**Comment by netchampfaris** [comment]
https://github.com/frappe/frappe/pull/2880
