### ISSUE TITLE
Logout Page - Heading should not be "Not Permitted"

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#7975]
After logout, user this redirected to page with heading "Not Permitted". This has confused user if they were logged out due to permission issue. Also, it's not the best message to leave a user with.

![image00338c749](https://cloud.githubusercontent.com/assets/910238/23785231/9d486724-058c-11e7-8e13-2a4a4aedba71.jpg)

**Comment by kennethsequeira** [comment]
https://github.com/frappe/frappe/pull/9838
