### ISSUE TITLE
Issue with Portal View of RFQs

### ISSUE THREAD

**Issue by ckosiegbu** [frappe/erpnext#7983]
The RFQ

![image](https://cloud.githubusercontent.com/assets/24209199/23822372/353e9052-064c-11e7-848b-896e78d5e582.png)

The calculation of the RFQ is wrong. Amount seems to be divided by 1000. In the example below, the value should be N8,400,000.00 instead of N8,400.00

Regards,
cksgb

**Comment by umairsy** [comment]
This issue is related to number format. Zeros after 14 is being considered as decimal places. Please check your Currency master for NB and set Number Format accordingly. Please let us know if that helps.

**Comment by rohitwaghchaure** [comment]
Hi @ckosiegbu 

Calculation is working properly, the issue is related to number format you have set on the system settings.
![screen shot 2017-03-14 at 1 12 12 pm](https://cloud.githubusercontent.com/assets/8780500/23890472/0cab2b5a-08b8-11e7-900f-8c4608e52a1c.png)

**Comment by ckosiegbu** [comment]
Please see my date format in the screenshot below. I don't see how this format should cause the problem I've reported (unless the system is assuming a hard-coded format that isn't the one in the screenshot below)

![image](https://cloud.githubusercontent.com/assets/24209199/24022043/6dda2b40-0aa4-11e7-87d6-217ee4abac25.png)

Regards,
cksgb
