### ISSUE TITLE
Payroll Payable - Decimal place calculation

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#7986]
As per the value in Process Payroll, total should be 6313. Since none of the row has value in decimal place, total value in should be absolute.

![screen shot 2017-03-12 at 12 19 27 am](https://cloud.githubusercontent.com/assets/910238/23825967/93826180-06b9-11e7-86c6-690f2cbbf55b.png)

But in the Journal Entry, some difference is availed.

![screen shot 2017-03-12 at 12 19 47 am](https://cloud.githubusercontent.com/assets/910238/23825971/a2b978dc-06b9-11e7-9dba-7643171a7bd8.png)

**Comment by nabinhait** [comment]
fixed
