### ISSUE TITLE
Show Title for Page in Awesome Bar / Global Search

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#7994]
Should be "Role Permission Manager"

<img width="357" alt="screen shot 2017-03-13 at 11 37 27 am" src="https://cloud.githubusercontent.com/assets/140076/23843407/8cc9d5f2-07e1-11e7-8bb1-ff64b52381c7.png">

**Comment by pratu16x7** [comment]
fixed
frappe/frappe#2851
frappe/frappe#2857
![screen shot 2017-03-13 at 1 24 06 pm](https://cloud.githubusercontent.com/assets/5196925/23846020/66b5c38e-07f1-11e7-95cc-c931275b21e9.png)
