### ISSUE TITLE
Barcode Uniqueness Issue

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#8001]
Hi,

we are encountering issues with unique barcode in ERPNext. Manufacturers of certain lines of products treat barcodes more like batch numbers so they are not always unique. In some other ERP applications, scanning a barcode brings up all the items in this group from where you select the specific item you want

All that's required in ERPNext is to use the 'Unique' option in the Customize Form tool rather than enforcing uniqueness from the code. It can be checked by default but then it should allow users who deal with non-unique barcodes to un-check the option

Thanks

Kind regards,

**Comment by PawanMeh** [comment]
Can batch field be used for your requirement?

![screen shot 2017-05-05 at 2 13 13 pm](https://cloud.githubusercontent.com/assets/20460498/25738886/08333776-319d-11e7-9f6f-eef31abaf2fb.png)

If yes, please close the issue.

**Comment by joezsweet** [comment]
I think could be done by moving Barcode to Item Barcode child table and having it unique. That's not big deal to customize, thing is to have all barcode search pointing to this new table.
