### ISSUE TITLE
[Paid Development] SMS/Email to Student mobile number on marking Attendance

### ISSUE THREAD

**Issue by sibidharan** [frappe/erpnext#8008]
I want to send SMS while instructor marks attendance of a student. The SMS should be sent to the mobile number on his profile. The message should be customised. It should be done as a background job, because it needs to do several HTTP requests. 

I want to pay for this feature.

**Comment by helios-ventures** [comment]
Hi sibidharan, have a look at this. 

https://discuss.erpnext.com/t/attendance-module-biometric-device-integration/17352/7

**Comment by sibidharan** [comment]
That is not what I am looking for. But I have completed the requirement myself. I programmed the necessary modules myself. Frappe Development Docs were easy 👍 

What I wanted is, not biometric device. For example, someone applying using the application form, the applicant should get an SMS. Their application gets approved or disapproved, they get an SMS. Instructor marks attendance, the SMS will be sent to the notification/parent/guardian mobile number. They get enrolled, they get a fees pending, they get an SMS. 

I wanted to deliver this module for a client, since I was on deadline, I designed them myself.

**Comment by Sanad-hussain** [comment]
> That is not what I am looking for. But I have completed the requirement myself. I programmed the necessary modules myself. Frappe Development Docs were easy 👍
> 
> What I wanted is, not biometric device. For example, someone applying using the application form, the applicant should get an SMS. Their application gets approved or disapproved, they get an SMS. Instructor marks attendance, the SMS will be sent to the notification/parent/guardian mobile number. They get enrolled, they get a fees pending, they get an SMS.
> 
> I wanted to deliver this module for a client, since I was on deadline, I designed them myself.

can you help me to do the same
