### ISSUE TITLE
two times google analytics...

### ISSUE THREAD

**Issue by robertbecht** [frappe/erpnext#8009]
GA is loaded twice....My own and also the one of Frappe, I guess...

![image](https://cloud.githubusercontent.com/assets/1532439/23875449/cec9ad58-0839-11e7-85c5-5d6120070383.png)

**Comment by PawanMeh** [comment]
Do you have google analytics ID set in your website settings?

**Comment by sharmanakul** [comment]
Closing it assuming it might have already been resolved.
