### ISSUE TITLE
Bug: warehouse required for dropship items

### ISSUE THREAD

**Issue by chanlung** [frappe/erpnext#8010]
1) create a purchase order for a supplier to do by dropship. 
2) Click submit.
Bug: Message: Warehouse is mandatory for stock Item xxx in row y

Since this is a dropship order the warehouse is not required and no validation should be done.

https://discuss.erpnext.com/t/why-does-dropship-purchase-order-need-a-warehouse/21317

**Comment by vivek3377** [comment]
Hi ,

I want to preselect default warehouse in sales order/Purchase order item table as per company selection.
