### ISSUE TITLE
Export in Excel - Grid view gets hidden

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#8011]
If I export a report into Excel, then grid gets hidden.

![export-format-data](https://cloud.githubusercontent.com/assets/910238/23888189/949594ee-08ac-11e7-99fa-84d99cb7814a.gif)

**Comment by manassolanki** [comment]
Fixed

**Comment by manassolanki** [comment]
https://github.com/frappe/frappe/pull/2883
