### ISSUE TITLE
Opening Email Queue receive error

### ISSUE THREAD

**Issue by monojoker** [frappe/erpnext#8020]
When I open the Email Queue from the Super Search I get the following error and I can't proceed past to view email activity.

![image](https://cloud.githubusercontent.com/assets/10917366/23932907/97934260-0986-11e7-9123-7fee986afb80.png)

Thanks.

**Comment by rohitwaghchaure** [comment]
Hi @monojoker 

Did you added any custom field on the email queue? Can you share the version of your applications?

**Comment by monojoker** [comment]
Hi Rohit, we have not changed the email queue report in any way, I haven't tried to open it since it changed name from Bulk Email to be honest. We are on v7.2.30 as per below. Thanks.

![image](https://cloud.githubusercontent.com/assets/10917366/24088572/b450987c-0d77-11e7-97da-9ed7666de67d.png)

**Comment by monojoker** [comment]
Hi @rohitwaghchaure is there any progress yet? I need to keep track of emails that go out when customers report non-receipt and Email Queue is very handy for this. Thanks, Liam.

**Comment by jwrober** [comment]
I suggest you upgrade to latest. Lots of changes in email handling since 7.2

**Comment by monojoker** [comment]
Thanks @jwrober I hadn't checked back on an update this is now fixed.
