### ISSUE TITLE
Print to PDF not functioning in ERPNext V7

### ISSUE THREAD

**Issue by kodeproject** [frappe/erpnext#8021]
Hello!

Greetings to all The Community Members.

This is my first Issues reporting on GitHub for ERPNext...

As per guidelines in the ERPNext documentation we have successfully installed-
ERPNext V7 in Ubuntu-14.04.5-server-amd64_VM.

Most of the functions are functioning correctly, except to one issue for now, is that we, have a set of BOM's/Recipes which needs to printed as an Standard SOP for the production team. But the print to PDF Option opens up in a new blank tab and keeps loading forever with a final error as below.

504 Gateway Time-out
nginx/1.4.6 (Ubuntu)

I have also installed wkhtmltopdf with root permissions, and rebooted the system but still it does not work.

Kindly guide/help us to resolve the issue.

Thanking you!

Regards,
Keshav Murthy

**Comment by jwrober** [comment]
Its works fine. Please open a discussion on this subject in the forum - https://discuss.erpnext.com/ - to get help with this.

**Comment by bcornwellmott** [comment]
I think the issue is with your config.json file. Check the user forum...
