### ISSUE TITLE
awesome bar redirect issue

### ISSUE THREAD

**Issue by mbauskar** [frappe/erpnext#8022]
Awesome bar Document Reports are redirected to List view instead of Report View

![awesome_bar_redirect](https://cloud.githubusercontent.com/assets/11224291/23935950/2b06e2fc-0975-11e7-8674-985f338178c8.gif)

**Comment by strixaluco** [comment]
Have been fixed by https://github.com/frappe/frappe/pull/2875/commits/b9c3023a67891a3f3de248ef41c847e0da3c3cf6
Can't replicate now at beta.erpnext.com.
