### ISSUE TITLE
Expanding POS offline capabilities

### ISSUE THREAD

**Issue by wamssler** [frappe/erpnext#8023]
We are looking for a Point of Sales (POS) where we can update multiple POS stations and than go offline during Sales opening hours. The reason behind is that some of our locations don’t have a stable internet connection as well we are mobile on the go with a kind of mobile booth/ kiosk that will operate only on certain periods of time and in different locations. Below are an example how it could work;

1st)    Software installation on the POS station (Hardware)
2nd)  Upload of Data throughout Internet connection on to the POS from the main ERP System (e.g. Product details, Pricing, Promotions, sales bundles, Product description etc.)
3th)   Taking the POS station to the mobile sales outlet 
4th)    Conducting Sales (without internet connection)
5th)    Taking it back to the HQ or where Internet is available after sales and upload/ update sales data with ERPNext system

If an internet connection is available during sales, the POS system should be able to Ping back to the ERPNext system for an automatic update every few minutes. 

Further more I am looking in to the same method for collecting customer Details  for e.g. if they want to sign up on our newsletter or Phone Marketing.

 Hope that I gave you a clear picture of how it should work. If you need more information or input from my side, I will be happy to provide to you as much as I can. 

thanks and regards

Jens

**Comment by epochc** [comment]
Hi Jens,

Would you be interested in teaming up and taking a more robust, holistic approach on this?

Like an offline server that will deliver on all ERPNext functionities and not just PoS.

The only downside to that would be that your POS machines would have a local instance of ERPNext, which means that it needs to support an Operating System such as Linux (Ubuntu desktop).

So, once a local instance of ERPNext is the approach, you can have multiple POS terminals in the same location tomorrow and then, with your approach, you will have a problem about synching data across the POS terminals.

Also once there is a local instance the whole functionality of ERPNext is available and while that may run counterproductive (or maybe it doesnt) to your requirement, it will help the ERPNext community.

Please let me know and I will try and drum up support for this approach.

I definitely understand if you want to continue on the path you have chosen.

Thanks

Jay


If you are interested there is at least one other person that could contribute.

Thanks

Jay

**Comment by wamssler** [comment]
Hi Jay,

Thank you for your email. Please see my answers below.

with best regards

*Jens Wamßler

*
On 15/03/17 17:52, epochc wrote:
>
> Hi Jens,
>
> Would you be interested in teaming up and taking a more robust, 
> holistic approach on this?
>
> Like an offline server that will deliver on all ERPNext functionities 
> and not just PoS.
>
  *      In general we would be interested in getting an all in one
    solution for ERPNext and not just a POS system.

> The only downside to that would be that your POS machines would have a 
> local instance of ERPNext, which means that it needs to support an 
> Operating System such as Linux (Ubuntu desktop).
>
  *      Does all/ any POS Systems can host an Operating System (Ubuntu
    desktop) (I am not a tech person)?

> So, once a local instance of ERPNext is the approach, you can have 
> multiple POS terminals in the same location tomorrow and then, with 
> your approach, you will have a problem about synching data across the 
> POS terminals
>
  *      it is very Important to synchronize data in two (2) ways
      o   from the main ERPNext interface down to the POS Terminals
      o and backwards from the POS Terminals to the ERPNext interface
  * If there is no synchronizing it failed the main purpose to monitor
    multiple Sales Locations in real time.
