### ISSUE TITLE
Gantt Chart is not loading properly

### ISSUE THREAD

**Issue by nabinhait** [frappe/erpnext#8025]
<img width="1208" alt="screen shot 2017-03-15 at 2 17 08 pm" src="https://cloud.githubusercontent.com/assets/836784/23940269/3eb86d42-098a-11e7-979b-6a39e743737d.png">

**Comment by netchampfaris** [comment]
@nabinhait 
This is an expected behaviour. Because either start date or end date is not set.

**Comment by nabinhait** [comment]
ok
