### ISSUE TITLE
Two Factor Authentication

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#8026]
Hi ,

I would like to suggest the addition of an optional Two Factor Authentication feature to ERPNext. Considering the sensitive nature of data in an ERP, I think having this feature will go a long way to assure existing and potential users about the security of their data

Thanks

Kind regards,

**Comment by tenninjas** [comment]
Related: [frappe issue #3047](https://github.com/frappe/frappe/issues/3047)

**Comment by ckosiegbu** [comment]
Hello Guys,

Please see the following PRs for implementation of Two-factor authentication in Frappe by Manqala Ltd

#3763
frappe/erpnext#10033

Regards,
Chude

**Comment by Olawale1** [comment]
Hi @ckosiegbu 

Awesome job... Well done!
