### ISSUE TITLE
Set default route on saving of BOM, if "Show in Website" is checked

### ISSUE THREAD

**Issue by nabinhait** [frappe/erpnext#8032]
<img width="1182" alt="screen shot 2017-03-15 at 5 59 12 pm" src="https://cloud.githubusercontent.com/assets/836784/23948513/5b209bb6-09a9-11e7-8546-57d208c2b1e5.png">

**Comment by jaichavan** [comment]
Hello, @jwrober @nabinhait  this request has been integrated into the system, closing the issue. Attaching screenshot for reference:

![image](https://user-images.githubusercontent.com/40264279/51369465-b1a4a300-1b19-11e9-9f9c-f20cd42a03b2.png)
