### ISSUE TITLE
Cost Center Not Getting Pulled in Delivery Note

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#8036]
Hi,

I just noticed that the Cost Center field isn't getting properly updated in the Delivery Note document 

Steps:

1. Set Cost Center, Income Account, and Expense Account at Item Group level
2. Create Sales Invoice for Item (Income Account and Cost Center are correctly pulled)
3. From Sales Invoice, Make => Delivery
4. In Delivery Note document, Expense Account is correctly pulled but Cost Center is not!

Please check

Kind regards,

**Comment by Olawale1** [comment]
Hi @KanchanChauhan 

Trust you're doing great. I just thought to mention that the issue also exists from Sales Order to Delivery Note (Cost Center not getting pulled)

Thanks

Kind regards,

**Comment by sagarvora** [comment]
Solved. Please reopen if it persists.
