### ISSUE TITLE
Process Payroll: Bank transaction individualization Enhancement Request

### ISSUE THREAD

**Issue by Tropicalrambler** [frappe/erpnext#8037]
As I have discussed in the following post:
https://discuss.erpnext.com/t/weekly-and-fortnightly-payroll-salary-slips/16305/33

[ ] Add a selector to the **Process Payroll** tool, to make each net payment transaction individual or grouped in the ERPNext created **Journal Entry** when done processing payroll.

Goal: If individual bank transactions are picked, then each Salary Slip's net pay for the payroll will be shown individually in the Journal Entry.  This helps ease workload when reconciling bank statements to ERPNext.

Current behavior:
The sum of the net pay of the salary slips submitted for the payroll period, is entered as the bank charge in the **Journal Entry**

Example:
Person 1 Net pay:  300
Person 2 Net pay: 400
Person 3 Net Pay: 300
Sum of all net payments: 1,000
Bank entry in Journal Entry related to Payroll processing:  1,000

Desired Behavior:
User selects **Individual Bank Transaction or Cash transaction per Salary Slip**, and when making the Payment Entry, ERPNext enters everything as above, except that for each Salary Slip, the Net pay is shown in the **Journal Entry.**

Person 1 Net pay:  300
Person 2 Net pay: 400
Person 3 Net Pay: 300
Sum of all net payments: 1,000
Bank entries in Journal Entry related to Payroll processing:
Person 1: 300
Person 2: 400
Person 3: 300

**Comment by OneiricIT** [comment]
+1
