### ISSUE TITLE
Print of Warehouse Tree 

### ISSUE THREAD

**Issue by Devens** [frappe/erpnext#8050]
Print command for Warehouse tree is not available. It should be made available.

![image](https://cloud.githubusercontent.com/assets/10671911/24000046/23dfb952-0a80-11e7-9e13-3b67457d0d31.png)

**Comment by rmehta** [comment]
- [ ] Get inner html of the tree
- [ ] Open a new window and inject basic template with <html>, <head>, <body> and include bootstrap (see query_report.js)
- [ ] inject tree inner html inside the <body> - clean links and buttons if present

**Comment by ashwinisave35** [comment]
Link to PR.
https://github.com/frappe/frappe/pull/3980
