### ISSUE TITLE
[v8] Error on Activities

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#8051]
Hello,

When I try to open activity the screen becomes grey and nothing is displayed

here is the error on console:

<img width="1677" alt="screen shot 2017-03-16 at 12 02 24 pm" src="https://cloud.githubusercontent.com/assets/18335894/24002963/dd272a3e-0a40-11e7-93bd-d1aea0686684.png">

**Comment by joezsweet** [comment]
Got same probs
