### ISSUE TITLE
Purchase Return for Non Stock item

### ISSUE THREAD

**Issue by Arundhatii** [frappe/erpnext#8055]
While creating a Purchase return entry for Non Stock (Service item), it says "Warehouse is Mandatory"
![return](https://cloud.githubusercontent.com/assets/20164097/24045775/3d8fa788-0b46-11e7-9f70-c2e1c2bfca4a.gif)

**Comment by umairsy** [comment]
Purchase Return entry should be allowed for the stock item only. Even if Purchase Receipt was made for the non-stock item (which is debatable), in the Return entry, only stock items should be allowed.

Incase of services, they can simply issue Debit Note to the Supplier which can be adjusted in the future.

**Comment by bohlian** [comment]
Guys, can I take this up? I am actually doing a bunch of fixes for Credit Notes and Debit Notes. Let me know.
