### ISSUE TITLE
Allow receipt of Product Bundle, modifying individual stock items

### ISSUE THREAD

**Issue by Tropicalrambler** [frappe/erpnext#8056]
I created a product bundle, containing all the items and quantities which compose it.
Enable ERPNext to increase the individual item stock numbers when you enter a purchase receipt for the product bundle. 
For example, a "Simple first aid kit" contains the following items: 

1. 1 Cabinet

1. 2 Vinyl gloves

1. 1 scissors

1. 20 antiseptic wipes

1. 50 finger bandages

The product bundle named "Simple first aid kit" has all these items listed. When I purchase the "Simple first aid kit", upon receiving it at the warehouse, I would like for the purchase receipt to be made for "Simple first aid kit", but when stock is being modified, it should increase the following items:
Cabinet +1
Vinyl gloves +2
Scissors +1
Antiseptic Wipes + 20
Finger Bandages + 50

It would also be great to have the option of "exploding" the **Product Bundle** within the **Purchase Receipt** to reflect further details, for example, you order "Simple first aid kit" and for some reason, the Vinyl gloves are missing, you can then "explode" product bundle for which ERPNext displays all items individually in the purchase receipt, and you can enter it as a zero value or delete the item from the receipt.

https://discuss.erpnext.com/t/purchase-receipt-product-bundle-stock-entries/21335

**Comment by Tropicalrambler** [comment]
Just yesterday I came across this particular example where product bundle comes in handy.

I purchased a box of "EXPO" brand "dry erase markers".
This box contains 4 individual markers one of each color:

1. Red

1. Blue

1. Green

1. Black

![img_3946](https://cloud.githubusercontent.com/assets/16600935/24303633/56321092-107c-11e7-8d0c-7a577001a94a.JPG)

One of the problems I have faced when placing material requests, is that those responsible for the material request do NOT specify the item being requested, thus, when the purchase is made, an error occurs. They order "EXPO Dry erase marker" but do not specify color.  In many cases color is irrelevant. But for productive purposes, colors are important and meaningful, thus in this particular "marker" example, being able to bundle a box with 4 items would be very useful and detailed.

The **stock item** would be defined as a master (EXPO Dry erase marker) with 4 variants (marker01-RED, marker01-BLUE, marker01-GREEN, marker01-BLACK). One should be able to start a **product bundle** with one of the variants, add the other 3 color variants to the bundle, and add details to the bundle, such as Barcode, etc.  to simplify accounting and inventory entries when purchasing.  i.e.  20 packages of 4 markers each are purchased, warehouse receiver will scan one box, change qty to 20, and ERPNext will automatically increase inventory upon validation with 20 RED, 20 BLUE, 20 GREEN, 20 BLACK.

**Comment by joezsweet** [comment]
https://github.com/frappe/erpnext/issues/11475

**Comment by bhavishyasharma** [comment]
Hi everyone!

I have implemented the bundle in Buying Cycle. The valuation of child items is calculated based on the weightage which is defined in the ProductBundle

Steps:

1. Add weightage field to Product Bundle.
![image](https://user-images.githubusercontent.com/15744297/58901508-f32b9880-871e-11e9-8178-165c60f1dac6.png)
2. Add weightage field to Packed Item.
3. Add rate and amount fields to Packed Item.
![image](https://user-images.githubusercontent.com/15744297/58902099-1571e600-8720-11e9-9ecd-6b67fcbe0be5.png)

4. Add packed_items to Purchase Order, Purchase Receipt, Purchase Invoice.
<img width="1322" alt="Screenshot 2019-06-04 at 23 18 59" src="https://user-images.githubusercontent.com/15744297/58901743-68976900-871f-11e9-88b1-f745c35f96da.png">

5. Pass stock_entry for Purchase Receipt and Purchase Invoice.

Please let me know how to push the code adhering to your development guidelines.

**Comment by ankush** [comment]
https://github.com/frappe/erpnext/pull/27124

**Comment by frewper** [comment]
Is this implemented on erpnext v14. In am trying to implement this but unable to explode the BOM on this version. 
Has anyone tried this ?
