### ISSUE TITLE
Overdue status on Invoice & Open status on Customer

### ISSUE THREAD

**Issue by PawanMeh** [frappe/erpnext#8058]
1. Open an invoice (This invoice was partially paid and then certain amount was written off (reasons could be many, dispute, bad debt etc) using JV functionality)

![screen shot 2017-03-18 at 9 14 32 am](https://cloud.githubusercontent.com/assets/20460498/24069899/3a88487c-0bd9-11e7-9bea-5b5f31186647.png)

2. Open receivables report for this customer

![receivables_report](https://cloud.githubusercontent.com/assets/20460498/24069904/5052ca56-0bd9-11e7-9b16-47a0384b381f.png)

The initial payment entry along with Write Off amount recorded is available. The write off entry was closed with reference of an invoice. So currently this Customer has no balance outstanding but his Invoice shows "Overdue" and the Customer is in "Open" status

My suggestion would be, if the customer does not have any outstanding balance (As per logic in the receivables report), then Customer should not be in "Open" status. Also, if in the write off entry reference of invoice is given, it should take into account these amount too before marking the invoice as "Overdue"

**Comment by jk2081** [comment]
Any update?

**Comment by milindnaphade** [comment]
Surprisingly this is related to the books closure and yet not fixed? In my case, the invoices show overdue even after adding correct entries for paid amount, write off, and also allocated amounts in the payment entry against an invoice. 

I am sure I am not doing anything wrong since it could happen with one invoice but it is happening for all invoices.

**Comment by milindnaphade** [comment]
Hi Guys,

Is there an update on this one? I have the following attachment for your review. I have booked 49,000 under the TDS that means the invoice outstanding should be 0. The invoice is still showing overdue.

![tempsnip](https://user-images.githubusercontent.com/15332991/60245872-1d661580-98db-11e9-885d-15d402ff142e.png)

**Comment by PawanMeh** [comment]
For your scenario, I think it works fine. Please see below

![Payment_TDS](https://user-images.githubusercontent.com/20460498/60252108-4d1b1a80-98e7-11e9-92e1-81f87880be03.gif)

Invoice is marked as Paid

![Invoice_Paid](https://user-images.githubusercontent.com/20460498/60252150-64f29e80-98e7-11e9-9724-54a7fc89dce6.png)

**Comment by milindnaphade** [comment]
@PawanMeh thank you for the help. I think that works. Appreciate the response.
