### ISSUE TITLE
production vm no localhost / network

### ISSUE THREAD

**Issue by icf20** [frappe/erpnext#8060]
hi, i am testing this so i set up the VM whit all configs untouched and by default the localhost:8080 does not work, if i log in the VM show that the ubuntu guest have no network at all, maybe you want to look at this and fix the VM

**Comment by yashodhank** [comment]
@icf20 make sure you are using IP address and port if you are accessing ERPNext from host (google it).
If you are trying to access from within VM then
you may need to check

- if you are running developer VM/Production ready VM for ERPNext.
- If you are running VM image meant for developer then to cd ~/frappe-bench/; bench start
- if you are running VM image ment for production use, then post your nginx log.

search for answers at http://discuss.erpnext.com
