### ISSUE TITLE
Allow to specify Income account in Item for each Company

### ISSUE THREAD

**Issue by ccfiel** [frappe/erpnext#8065]
For now ERPNext does not allow to specify Income account in Item for each Company. You can only do this in the first company but the succeeding company you can only used one income account to all items. See discussion here https://discuss.erpnext.com/t/item-income-account-per-company/

**Comment by ccfiel** [comment]
Hello @nabinhait @rmehta :)

I have created a pull request for this. It just a simple solution. :) hope this will be in develop. Thanks!

Chris

**Comment by kennethsequeira** [comment]
Solved by Item Defaults section in v11 and onwards:

![image](https://user-images.githubusercontent.com/33246109/58045583-7c0fd500-7b60-11e9-9de0-60700ff1b9b9.png)

![image](https://user-images.githubusercontent.com/33246109/58045609-892cc400-7b60-11e9-9ec1-ca77e46b3cb6.png)
