### ISSUE TITLE
BOM Navigation bug

### ISSUE THREAD

**Issue by Arundhatii** [frappe/erpnext#8069]
Go to BOM List view >> Open an existing BOM >> Click on BOM >> it takes you to BOM Tree view and not to the list view.
![bom navigation bug](https://cloud.githubusercontent.com/assets/20164097/24100057/5e7612f8-0d98-11e7-879d-0399f7cfa830.gif)

**Comment by pratu16x7** [comment]
While this is the expected behaviour for treeviews, it seems that as the BOM treeview is not consolidated as others, it would be better to redirect to a list (#8518). We could either blacklist such views to be displayed as list via breadcrumbs, or revert back to the last opened view.
