### ISSUE TITLE
Cannot switch to master

### ISSUE THREAD

**Issue by fayezqandeel** [frappe/erpnext#8071]
Hi All,
When trying to bench switch-to-master, I got 

`Branch master does not exist in Upstream for erpnext`

tried to use fetch but still getting the same error!

**Comment by jwrober** [comment]
+1 I get same error

**Comment by jwrober** [comment]
@fayezqandeel - I figured this out - go into apps/frappe/ and do a `git fetch` to have git re-get all the tags. Do the same in apps/erpnext/. Then try to do a `bench switch-to-master`. This worked for me in by dev environment.

**Comment by Olawale1** [comment]
This issue still exists so I'm not sure why it was closed?! It needs to be fixed so that users don't have to keep running around looking for how to fix it themselves. I just encountered the same issue setting up a new site and the git fetch approach didn't work

Kind regards,

**Comment by Olawale1** [comment]
...Had to eventually amend the config file in the ,git directory manually!

Kind regards,
