### ISSUE TITLE
BOM - Raw-material Item's table. Reset value in BOM field on selection of Item Code

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#8085]
Steps:

1. While creating BOM, I selected a raw-material item which also had it's own BOM.
2. Then I edited Item Code and selected another raw-material Item (without BOM).
3. When saving BOM, I get the error message that Select BOM not available in the BOM selected with it.

This is because, when I replaced raw-material Item with one without BOM, value in the BOM field (in the BOM Item table) was not reset.

**Comment by sagarvora** [comment]
Merged.
