### ISSUE TITLE
BOM saving crashes

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#8095]
Current dev branch causes problems when saving a BOM

Uncaught TypeError: Cannot read property 'load_all' of undefined
Uncaught TypeError: Cannot read property 'bold' of undefined

![image](https://cloud.githubusercontent.com/assets/9136094/24196747/44c25d18-0eff-11e7-91a4-55bde2f463fe.png)

**Comment by nabinhait** [comment]
Are you still getting this error?

**Comment by dottenbr** [comment]
seems ok, I tested it with 2 BOM and didn't see the error
