### ISSUE TITLE
Multiple Shopify Shop Sync on Multiple Company in a Single ERPNext Instance

### ISSUE THREAD

**Issue by saurocapital** [frappe/erpnext#8100]
There the possible to connect multiple Shopify Online Store in a Single ERPNext Instance ?

for example:

ERPNext Instance:     XYZ.erpnext.com

that have 2 companies:

Company 1:     ABC Limited

Company 2:     DEF Limited

can install two times the Shopify App Connector to sync the two store:

Store 1;      http://ABC.myshopify.com/

Store 2:      http://DEF.myshopify.com/

This is most important because if you have two online store (example 1 for EUROPE and 1 for USA) if you use two separated companies in the same ERPNext Instance you can use a common items list...but now it's not possible to sync two different Shopify Store.

If you want to sync two separate Shopify Store you need to use two separated ERPNext Instance....but with this method you don't have a common items list...

it's possible to know how much cost this feature ?

**Comment by ankush** [comment]
We do not support this officially yet. Community created app has support for multi-shop if you're interested in this: https://github.com/ParsimonyGit/shopify_integration
