### ISSUE TITLE
Workstation Operating cost not logical

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#8101]
Typically workstation operating cost is calculated with more factors than electricity, rent, consumable and wages such as asset depreciation, maintenance cost etc. In my opinion it doesn't make sense to have 4 different fields for this because they have no effect on computation. Instead this should just have one field which is "Operating Cost" in cost per hour.

![grafik](https://cloud.githubusercontent.com/assets/9136094/24203079/0bfee42c-0f15-11e7-9205-a75561cafd86.png)

- [ ] Replace 4 fields by one field
- [ ] Write a patch that summarizes the 4 fields and puts the new value in one
- [ ] Update documentation

**Comment by bcornwellmott** [comment]
While I agree with the stated problem, I disagree with the suggested fix...

There are very good analytical reasons to have these fields split, but the current list is not exhaustive. Can we have a table of operating costs that can be added to or expanded depending on each company's usage?

**Comment by dottenbr** [comment]
That would be an alternative, to have a configurable table that gets you to the "Net Cost per Hour" and I would be fine with that. @bcornwellmott would you be willing to pick this up, fix it and write a patch?

**Comment by dottenbr** [comment]
![grafik](https://cloud.githubusercontent.com/assets/9136094/24504747/b68e8102-1557-11e7-80dc-14209720059e.png)

**Comment by bcornwellmott** [comment]
@dottenbr, I could get to it eventually. Unfortunately it won't be a big priority for me as I'm not able to put too many hours into ERPNext these days.

**Comment by AleCVERP** [comment]
dottenbr that´s a good idea but can you explain me in the ERP
