### ISSUE TITLE
Time picker problems

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#8102]
- [ ] When manually entering a time, there is no evaluation error but the time picker is not updated
- [ ] No evaluation error on incorrect time formatting
- [ ] Time picker should not have "today" but maybe rather a working "now"?
- [ ] There seems to be a caching issue, the date picker always remembers the last input even if its from another field rather than loading the current information

![grafik](https://cloud.githubusercontent.com/assets/9136094/24203392/d5afd43e-0f15-11e7-9ca9-993328680311.png)

**Comment by joezsweet** [comment]
That's more frappe than erpnext issue

**Comment by partzsch** [comment]
This is not fixed yes as of the demo version, we would love to upgrade to version 8 and further participate at least with bug reports but as timetracking is a critical thing for us we will have to wait till this offers the same stable functionality as of version 7

**Comment by partzsch** [comment]
still not fixed!?

**Comment by partzsch** [comment]
still same result as of version

ERPNext: v8.x.x-beta (113df55) (develop)

ERPNext Shopify: v2.0.12 (master)

Frappe Framework: v8.x.x-beta (91e705e) (develop)

Mandrill Integration: v0.0.1 (master)

via demo.erpnext.com

**Comment by rmehta** [comment]
seems okay to me, please share an animated GIF if possible.

**Comment by partzsch** [comment]
https://www.dropbox.com/s/ef71tp8nxrdwhxf/timesheet%20picker.webm?dl=0

**Comment by rmehta** [comment]
this happens when the system timezone is separate from the user timezone.

https://github.com/frappe/erpnext/issues/9941
