### ISSUE TITLE
Stock Balance & Print Comand in Warehouse Tree

### ISSUE THREAD

**Issue by Devens** [frappe/erpnext#8104]
Display of Stock Balance in Warehouse Tree is useful only if it shows balance "As on Date".  

Although it can be available from "Trial Balance", it has following inconveniences. 
1. Store person might not have access to accounting reports.
2. Trial balance shows all the balances. if we need to see data only related to warehouse, it cannot show. 

Further, it should have "Print" command also in Menu.

![untitled_clipping_032217_082701_pm](https://cloud.githubusercontent.com/assets/10671911/24204259/e7d323aa-0f3d-11e7-8077-7c032fecc8e7.jpg)

**Comment by deepeshgarg007** [comment]
@Devens I think the stock balance report can be used for this. Closing this issue
