### ISSUE TITLE
Fix persistant Infobox on bottom

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#8105]
The little infobox on the bottom is cool. However it is rather persistant and can not be dismissed or hidden. If you click the close button, it will be back after a reload. I think you need a "don't remind me" checkbox or button here before you release.

![grafik](https://cloud.githubusercontent.com/assets/9136094/24207505/55aa9dda-0f21-11e7-84c9-10d832c97d3b.png)

**Comment by dottenbr** [comment]
seems fixed!

**Comment by imllc** [comment]
not fixed as of 
Installed Apps

ERPNext: v8.0.14 (master)

Frappe Framework: v8.0.19 (master)

i x out infobox click reload and its back...

why cant we just have a check box in desktop icons to turn off?

**Comment by aaimaawebs** [comment]
Can we do it better way, by implementing some AI? I mean, by analytics we can do it better way.

Here is my proposed solution: 
When a user, close it too many times a day, a week can be shown back after some days. At least, this will not bother user every reload.
While, this box helps/reminds/tips of some activities which is important, this is why this box exist.

**Comment by imllc** [comment]
Even that is not user friendly we as admin should be able to turn on and off as we can with the desk icons...
