### ISSUE TITLE
Make customer.tax_id visible Sales Order print

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#8107]
In Sales Order default print format please add the Tax_ID of the Customer by default, the best position would probably be under the customer's order number

![grafik](https://cloud.githubusercontent.com/assets/9136094/24237609/4faef562-0fa7-11e7-9264-9127e590b456.png)

**Comment by dottenbr** [comment]
This is generic enough of a request to make it the default behaviour espacially since there is a lot of white space there and this is used by almost all companies.

**Comment by dottenbr** [comment]
related to and can be fixed in one pull request with
https://github.com/frappe/erpnext/issues/8111

**Comment by dottenbr** [comment]
this is a quick fix @emakis you should do it :-)

**Comment by nabinhait** [comment]
- [ ] Add "Tax Id" field in Quotation, Sales Order, Delivery Note and Sales Invoice
- [ ] Fetch Tax id from Customer in those docs, on change of customer
- [ ] Place tax id field in proper place, for showing it in print format
- [ ] Add a checkbox "Hide Tax Id in Print Format" in Selling Settings 
        * If enabled, then create property setter for "Print Hide" property for "Tax Id" field

**Comment by emakis** [comment]
@nabinhait @dottenbr : Is it needed to add the tax_id in quotation doctype? Sales Order, Delivery Note and Sales Invoice makes sense but in Quotation?

**Comment by nabinhait** [comment]
@emakis I don't know, check with @dottenbr

**Comment by emakis** [comment]
Done, but without adding the tax_id field in Quotation.
