### ISSUE TITLE
Header spacing inconsistent in print preview and pdf export

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#8108]
The print preview has clean whitespace / margin above to the page

![print preview](https://cloud.githubusercontent.com/assets/9136094/24237873/7e103438-0fa8-11e7-99c9-30fd90cd2254.png)

However when you export this to PDF that whitespace is missing

![pdf export](https://cloud.githubusercontent.com/assets/9136094/24237885/87570ee0-0fa8-11e7-8594-48787b92cbf7.png)

**Comment by dottenbr** [comment]
Was discussed in early 2016 already here https://github.com/frappe/erpnext/issues/4753

**Comment by pratu16x7** [comment]
Discussed at #8739 as well. Closing here
