### ISSUE TITLE
Incomplete Mapping in Cashflow

### ISSUE THREAD

**Issue by Fredoluka** [frappe/erpnext#8109]
Dear Team,

Much work has been done and kudos.

I just discovered that not all elements that constitute a standard cashflow report is linked to cashflow report in erpnext.

Examples are:
1. Fixed Asset disposal. The gain or loss is not adjusted in the cash flow.
2. If company income tax is paid.The amount paid is not adjusted in the cash flow.
3. No Adjustment for deferred tax
4. For investing activities only net change in fixed assets is accommodated. Other items like Investment purchase and disposal are not linked.
5. For financing activities,only change in equity is allowed,other financing options are not linked.
6. Cash activities relating to the following account groups in the chart of accounts does reflect in the cashflow: Loan and Advances (assets),Security and Deposit,Tax Assets,Investmnet,Duties and Taxes,Loan (Liability)

Kindly please link the necessary field in the cashflow report.

Here is a link for a standard cashflow:
http://www.excel-skills.com/templates/cashflow_statement_sample.xls

**Comment by Fredoluka** [comment]
Currently in ERPNEXT i discovered that the Net Change in Cash is  a balancing figure regardless of what the actual change in the cash from the previous period to the current period is.As we want to update cashflow statement ,we should  please ensure that the Net Change in Cash is based on Actual change in cash and cash equivalent and not just a balancing figure.

**Comment by tundebabzy** [comment]
@Fredoluka 
It's almost impossible to automatically generate an accurate cash flow report without chart of accounts that are set in stone. To have a correct mapping, I have opened a PR - #12969 so that the cash flow report will be customisable by an accountant. All the mappings, labels will be editable.
