### ISSUE TITLE
Customers and Suppliers should have an account number / code

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#8117]
Typically Customers and Suppliers have an account number. So we propose the same behaviour like with Item. An Item has an item_code and the item_id is typically that code. If the item_id is not filled out it takes the name.

- [ ] Add customer_code and supplier_code to respective DocTypes
- [ ] Enable the code to be the default ID
- [ ] Configure the Customer and Supplier doctype to show the name instead of the code when linked (this feature was already contributed by ESO)

**Comment by dottenbr** [comment]
Otherwise if this is not wanted in core we could add a custom field but this seems rather generic. What do you think @rmehta

**Comment by rmehta** [comment]
Yeah, seems generic!

**Comment by dottenbr** [comment]
This is needed before we can really import

**Comment by kickapoo** [comment]
@dottenbr @rmehta 
I was starting to work with it. 
If we assume I follow `Item` functionality , item_code and item_id(name) are set during autoname. This means @dottenbr once the customer_code is set and you need to update the customer_code it want update the name (customer_id) (at least from that I understand).

A more detailed example:
Customer Full Name: Test Me without customer_code --> customer_code is Test ME
Customer Full Name: Test Me without customer code and naming serries --> customer_code is CUST-0000232.
Customer Full Name: Test Me with customer_code 123 --> customer_code 123

In the above examples, if you want to change customer_code it want be able:
Change customer_code 123 to 4444 --->  in db  --> name (customer_id) is Test Me. 

So, i need your validation if this is the functionality you need or if @rmehta has another proposal.

**Comment by rmehta** [comment]
Do we *really* need a customer code?

Maybe we should have a new system where we can customize naming at the doctype level, in customize Form

1. Based On Field
2. Based on Naming Series
3. Based on Field Abbreviation

This way we can extend this to any doctype (?)

**Comment by dottenbr** [comment]
Again when it comes to accounting most companies work with a customer account number rather than a name. Names change but customer account numbers don't. The same is with suppliers after mergers and aquisitions.

**Comment by jfilz** [comment]
Just look at your bills. They all have an account. Number for you. Check your Visa Mastercard water electric gas phone or cell ..... They all have a customer numbers. Vendor number is not as nuch of an issue. Cutomer number should have rules like item number.

**Comment by joezsweet** [comment]
Wouldn't be simpler to add a custom field, kind of customer_code? Or use number_series, use the .##### part as customer number and fill it on after_save hook?

**Comment by mfazilp** [comment]
We needed the same. Need customer code for the customers. Each salesman remember their customer’s code to enter the transactions like sales invoices and payments.

I make a custom field for Customer module. I can search with customer code in sales invoice as I given it as global search and in search field of customer.

But I cannot having the same facility in payment entry.

**Comment by sbhekuza** [comment]
+1

Hi community, is it possible to auto-generate these fields and also make
them visible in invoices? How does one go about doing that? Thanks

**Comment by addymuliady** [comment]
Why not use naming series for customers and suppliers?

Mulyadi Ibrahim / Director 
+65 96479696/ mulyadi@dwenterprise.org

DW Enterprise Office: +65 31515019 / Fax: +65 31515019 
21, Bukit Batok Crescent, WCEGA Tower, #12-79, Singapore 658065
http://dwenterprise.org

This e-mail message may contain confidential or legally privileged information and is intended only for the use of the intended recipient(s). Any unauthorized disclosure, dissemination, distribution, copying or the taking of any action in reliance on the information herein is prohibited. E-mails are not secure and cannot be guaranteed to be error free as they can be intercepted, amended, or contain viruses. Anyone who communicates with us by e-mail is deemed to have accepted these risks. Company Name is not responsible for errors or omissions in this message and denies any responsibility for any damage arising from the use of e-mail. Any opinion and other statement contained in this message and any attachment are solely those of the author and do not necessarily represent those of the company.


---- On Thu, 04 Jan 2018 06:44:03 +0800 notifications@github.com wrote ----

+1

Hi community, is it possible to auto-generate these fields and also make
them visible in invoices? How does one go about doing that? Thanks

**Comment by mfazilp** [comment]
@addymuliady Salesman are aware of customer code in their previous system.

we added  custom field for customer code and can search over Sales Invoice. But In payment Entry, account receivables ...cannot search the customer with customer codec

**Comment by joezsweet** [comment]
did u add your custom field in search_fields?

**Comment by sbhekuza** [comment]
And his does one auto-generate this customer code?

**Comment by mfazilp** [comment]
@joezsweet how can i do that

**Comment by mfazilp** [comment]
Sorry ofcourse I add custome_code in search field of Customer Module. Thats Y i can search the customer in Sales invoice with customer_code.

But that was not working in payment and Account receivable or Ledger.
