### ISSUE TITLE
Multi Level Production Order Operations and BOM

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#8118]
We have decided together to say that SMT Assembly TOP and SMT Assembly BOT wil be two sub-assembly Items for the Item to manufacture. So these sub-assemblies will have the operations needed and the componbents needed. Now these two sub-assemblies are put into the Item to manufacture which has more operations like kitting or packaging and may have things like packaging material.

At the moment the Item to manufacture does not show the sub-assembly BOM and the sub-assembly operations.

Do we need to produce separate production orders for those sub-assemblies (could be a logistical nightmare) or can we manage this from within the main production order of the item to manufacture?

- [ ] Add Multi-Level BOM with actually required quantities from BOM into the Production order
- [ ] Show Operations of sub assembly BOMs in Production Order
- [ ] Enable timesheet entries for sub assembly operations within the production order

We need some guidace @umairsy and @rmehta this is blocking me from making progress.

**Comment by rmehta** [comment]
Lets do a session on this tomorrow with @nabinhait tomorrow. 

I think we should be able to create multiple Production Orders for each step automatically.

**Comment by nabinhait** [comment]
@dottenbr There is a checkbox "Use Multi-Level BOM" in the Production Order. If you check this, all the raw materials from sub-assembly as well will be considered for transfer to WIP warehouse and while back-flushing.
But you are right, the operations mentioned in the sub-assembly BOMs are not pulled in the Production Order, which it should.Once those operations are pulled, I think Timesheet entries will be made automatically against them.
Please let me know if you need any clarification on this.

**Comment by dottenbr** [comment]
@nabinhait and @rmehta we have "use multi-level bom" active and it actually works for the BOM lines. However it is not working for the operations. I can show you examples on my machine and the nwe should figure this out. This is a roadblock at the moment. 

I have released two production orders to be managed completely within ERPNext but I cant display the data to the users.

**Comment by dottenbr** [comment]
Will be discussed on Monday in a websession with @nabinhait @kickapoo and @emakis

**Comment by dottenbr** [comment]
An example of multi-level bom view

![grafik](https://cloud.githubusercontent.com/assets/9136094/24352504/25ddfdb4-12ea-11e7-81dc-1b801749c6f5.png)

**Comment by dottenbr** [comment]
Thank you for the fix @nabinhait.

I have a comment / request for the Oerations. Currently there seems to be no logic in which they are listed in the production order. I think we should do it consecutively by starting with the first BOM item, if it has operation add them to the operations table in the order in which they are in the BOM. Then go with the next item and add them to the operations table. Finally we should then list the steps from the parent assembly.

For the required items we need to know in which operation they are required so the current flat list won't do.

**Comment by dottenbr** [comment]
- [ ] Please show BOM also before ``Production Order`` is submitted

**Comment by dottenbr** [comment]
- [ ] Show ``Item`` availablity status in BOM
