### ISSUE TITLE
Add Employee Qualification to Human Resources Module

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#8122]
- [ ] Integrate current code with Training Event, Training Result, Training Feedback
- [ ] Add code to Module
- [ ] Integrate Employee Qualification into the Employee DocType so the users and HR Managers can see
- [ ] Integrate Training Events into Employee DocType so the users and HR Managers can see

**Comment by kickapoo** [comment]
@KanchanChauhan  We have already a custom solution in our dev team for Employee Qualification. I will share specs.

**Comment by PawanMeh** [comment]
Currently employees can be assigned educational qualifications.

![educational_qualifications](https://user-images.githubusercontent.com/20460498/47214569-f5bdc580-d3bb-11e8-9763-10e1ff4ee648.png)

If there is any other intended functionality, this issue can be re-opened or PR can be sent.

**Comment by dottenbr** [comment]
The educational background is completely unrelated to qualification.
