### ISSUE TITLE
Employee Address should be Address instead of Textbox

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#8123]
- [ ] Employee Permanent Address and Current Address should be an Address field instead of a textbox.
- [ ] Current Address should only be shown if a checkbox "Current Address deviates from Permanent Address" is checked. Normally current address is assumed to be the permanent address.
- [ ] I would also suggest retiring the "Permanent Address Is" and "Current Address Is" fields that let you select if the address is rented or owned. That seem like information an employer wouldn't care about.

**Comment by kickapoo** [comment]
@rmehta @nabinhait 
Please check @dottenbr suggestion about _retiring the "Permanent Address Is" and "Current Address Is" and if patch is needed.

**Comment by nabinhait** [comment]
@kickapoo Yes, we should remove those fields. If the field is used by anyone, we should write a patch to create a custom field with the same fieldname .

**Comment by dottenbr** [comment]
@KanchanChauhan are you working on this currently?

**Comment by KanchanChauhan** [comment]
@dottenbr Yes I am working on it.
https://github.com/frappe/frappe/pull/2956
https://github.com/frappe/erpnext/pull/8205
