### ISSUE TITLE
Required Items table not showing in Production Order Print Format

### ISSUE THREAD

**Issue by dvdl16** [frappe/erpnext#8125]
Hi all!

As per the issue title. When I add the "Required Items" to the Production Order Print Format, I only get a blank result when printing a production order.

Can someone perhaps point me in the right direction to investigate why this is happening?

We use:
ERPNext: v7.1.1
Frappe Framework: v7.1.2

**Comment by jwrober** [comment]
I think this is in 8.x. Please upgrade to latest in your development environment and test.

**Comment by jwrober** [comment]
@dvdl16 - did you update and test? Please advise so we can properly handle this issue.

**Comment by dvdl16** [comment]
Hi @jwrober. Thanks so much for the feedback. I'll do the upgrade on Friday and confirm the fix here.

**Comment by dvdl16** [comment]
Still need to test this. I'm having trouble getting v8 to work. Did bench update --upgrade, got to:
ERPNext: v8.0.33
Frappe Framework: v8.0.55

But when opening an Item I get the following error in browser console:
```
desk.min.js:500 Uncaught TypeError: frappe.provide(...) is not a constructor
    at Class.make_rich_text_editor (desk.min.js:500)
    at Class.make_input (desk.min.js:499)
    at make_input (desk.min.js:397)
    at HTMLDivElement.<anonymous> (desk.min.js:400)
    at HTMLDivElement.dispatch (jquery.min.js:3)
    at HTMLDivElement.$event.dispatch (report.min.js:203)
    at HTMLDivElement.r.handle (jquery.min.js:3)
    at Object.trigger (jquery.min.js:4)
    at HTMLDivElement.<anonymous> (jquery.min.js:4)
    at Function.each (jquery.min.js:2)
```

**Comment by dvdl16** [comment]
Despite my comment above, I can print Production Orders. 

Unfortunately I still get blank where Required Items are supposed to show up

**Comment by jwrober** [comment]
Thanks for confirming.
