### ISSUE TITLE
TypeError: get() takes exactly 1 argument (0 given)

### ISSUE THREAD

**Issue by binary64** [frappe/erpnext#8127]
On a new install: I deleted all my sample projects, but then I got this error:

> Traceback (most recent call last):
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
>     response = frappe.handler.handle()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
>     execute_cmd(cmd)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 40, in execute_cmd
>     ret = frappe.call(method, **frappe.form_dict)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 897, in call
>     return fn(*args, **newargs)
> TypeError: get() takes exactly 1 argument (0 given)

Additionally, when I click the `Report this issue` button, I get this error in chrome debug:-

> Uncaught TypeError: Cannot read property 'doc' of null
>     at Class.setup_print_language (desk.min.js:1000)
>     at Class.prepare (desk.min.js:988)
>     at Class.make (desk.min.js:988)
>     at Class.init (desk.min.js:987)
>     at new Class (desk.min.js:7)
>     at HTMLAnchorElement.<anonymous> (desk.min.js:161)
>     at HTMLAnchorElement.dispatch (jquery.min.js:3)
>     at HTMLAnchorElement.$event.dispatch (report.min.js:208)
>     at HTMLAnchorElement.r.handle (jquery.min.js:3)
> setup_print_language @ desk.min.js:1000
> prepare @ desk.min.js:988
> make @ desk.min.js:988
> init @ desk.min.js:987
> Class @ desk.min.js:7
> (anonymous) @ desk.min.js:161
> dispatch @ jquery.min.js:3
> $event.dispatch @ report.min.js:208
> r.handle @ jquery.min.js:3

**Comment by PawanMeh** [comment]
Please check if the issue exists on the latest version. Also, specify information like
1. Frappe Framework version
2. Hardware/RAM and OS configuration being used.
