### ISSUE TITLE
Need more decimal points for Currency

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#8130]
We buy a lot of electronic components that cost like 0,0025 so we need to set in our company that our currency format allows 4 digits. 

The System Settings Float Precision has no influence on that but only counts for float types, not currency types. The Smallest Currency Fraction Value in Currency also doesn't work.

How can we set the decimals for the currency to e.g. 4 or 5?

**Comment by kickapoo** [comment]
It can be configured  (developer_mode on) in DocType: Item Price 
<img width="1004" alt="screenshot 2017-03-24 11 21 54" src="https://cloud.githubusercontent.com/assets/5064612/24287997/6f03ad30-1084-11e7-888e-8857346ad201.png">

**Comment by dottenbr** [comment]
I was hoping that this would be made configurable. If you change it please don't do it in developer mode but by customizing the form.

**Comment by dottenbr** [comment]
This issue is not closed in my opinion. Currencies are not only in items but sales orders, quotations, all the ledger entries and we need to be able to set the float precision for all of these at once.

I would recommend to make the currency configurable system-wide in System Settings by setting the float precision or making it configurable company-wide in the Company settings next to the currency to set the float precision wanted for that company.

This should be discussed with @nabinhait to make sure the impact on accounting is tested.

**Comment by dottenbr** [comment]
frappe help neaded

**Comment by rmehta** [comment]
Also see https://github.com/frappe/erpnext/issues/8366. I think the currency format should be global and consistent in the system.

**Comment by mtyspider** [comment]
Same problem here.. am trying to implement erpnext. but this issue has me running around circles for 15 days now i might as well give up.

**Comment by nabinhait** [comment]
Fixed it, now there is a dedicated settings for Currency precision under System Settings. You can set it to 9. Also, now Currency formatting is based on "Number Format" field in System Settings.

**Comment by dottenbr** [comment]
Thank you for implementing the feature. I think it is not ideally designed yet and needs a small improvement. So when buying or selling items we need to be able to set more decimals, you did that. However now these decimals are always visible also when they are not needed.

The most common thing is to show only the two decimals unless more are used.

So instead of the current layout:

![currency](https://cloud.githubusercontent.com/assets/9136094/25124868/4f5275f4-242d-11e7-94c4-2b3d5ef26754.png)


I would suggest to show only the decimals beyond 2 when they are used:

![currency_proper](https://cloud.githubusercontent.com/assets/9136094/25124849/40834fa8-242d-11e7-9227-4c64a9dc0601.png)

This will allow people to use as many decimals as they want but will display nicely.

**Comment by rmehta** [comment]
It was implemented as designed. So it should have been specified better!

**Comment by dottenbr** [comment]
I completely agree

**Comment by dottenbr** [comment]
@rmehta can you pick this up again and have the decimals beyond 2 only show is needed (input or calculation)?

**Comment by rmehta** [comment]
Can @kickapoo try it. You just need to update the formatters

**Comment by kickapoo** [comment]
@rmehta not in the near future, sorry but I am in some deep machine communication issues.

**Comment by dottenbr** [comment]
The currency setting should allow up to that number of float precision. However whenever we display sums like the sub total or the total we should round to 2 decimals.

**Comment by KanchanChauhan** [comment]
@nabinhait Should there be another setting for currency precision for sub total and totals?

**Comment by dottenbr** [comment]
@KanchanChauhan and @nabinhait in general you can not transfer or book any currency value that has more than the currency's decimals. For Euros that is 1 full cent = 0.01 euro. To me it doesnt matter if you want to implement two currency float precisions, maybe that is useful to some. For us and for all other normal businesses it should be sufficient if sums and totals are rounded to full cents. I have just pulled 3 examples of invoices and order confirmations from some of our suppliers:

![example 1](https://user-images.githubusercontent.com/9136094/26925166-fe167822-4c48-11e7-9d4d-ac496de4c6ee.png)
![example 2](https://user-images.githubusercontent.com/9136094/26925169-fe3e5dce-4c48-11e7-960d-4df2b1553e6f.png)
![example 3](https://user-images.githubusercontent.com/9136094/26925170-fe682aa0-4c48-11e7-86b3-2c4856b27755.png)

**Comment by dottenbr** [comment]
I would like to add that I believe strongly that the decimals should only be shown if they are used. Maybe this can be configurable to say "always show decimals" or "only show used decimals" that basically converts a 1.2000 -> 1.20 / 1.2120 -> 1.212 etc.

**Comment by rmehta** [comment]
Yes, I think we can make that as the default. Show additional decimals if they are non-zero
