### ISSUE TITLE
Summernote - Image resizing issue

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#8133]
Steps:

1. In the text editor, I inserted an image.
2. I resized an image front front end using drag-end feature.
3. Saved document. After saving, image appears in the original size.
4. I re-adjust the size from front-end.
5. Save document. This time, image size is updated correctly based on the adjustment made.

**Comment by netchampfaris** [comment]
Cannot replicate

**Comment by netchampfaris** [comment]
Closing for now.
