### ISSUE TITLE
Moving Companies from one instance to another

### ISSUE THREAD

**Issue by saurocapital** [frappe/erpnext#8137]
there is a solution to move companies and data (customers, suppliers, items) to another instance or clone it to a new instance ?

this is very good for test envirorments or disaster recovery...

**Comment by umairsy** [comment]
Sure. You can take backup from one ERPNext instance, and restore into another. Please check:

https://github.com/frappe/erpnext/wiki/Restoring-From-ERPNext-Backup

Please post such queries on ERPNext discuss forum.

https://discuss.erpnext.com

**Comment by saurocapital** [comment]
Hi,


this solution you suggest is good for a local ERP installation...


I have the free cloud version, where is located the command prompt ? or the is a special menù for backup and restore ?


thanks


Best regards

--

Operations Office



SAURO CAPITAL LTD.

47 Churchfield Road, London W3 6AY, United Kingdom



Mail: operations@saurocapital.uk

Web: www.saurocapital.uk


________________________________
