### ISSUE TITLE
Purchase Order does not reflect payment made prior to receiving Invoice or purchased item.

### ISSUE THREAD

**Issue by Tropicalrambler** [frappe/erpnext#8139]
When I make a **Journal Entry** or **Payment Entry** in full value against outstanding amount of a **Purchase Order**, (before having the bill or receipt of material) it is correctly registered in the Journal, the linked Journal/payment entry is correctly shown, but the status still shows **"To Receive and Bill"**. It should read **"Paid, Awaiting Receipt and Invoice**. If a **Purchase Invoice** is created from that **Purchase Order**, and it is already paid as mentioned before, the status upon validation of the **Purchase invoice** should be **"Paid, Awaiting Receipt"**.

**Comment by harshit-30** [comment]
Please create another issue if it is replicable in v13.10.
