### ISSUE TITLE
Naming Series - missing Transaction:  Offer Letter

### ISSUE THREAD

**Issue by Tropicalrambler** [frappe/erpnext#8140]
Naming series customization is missing for **Transaction** type: "Offer Letter"

**Comment by PawanMeh** [comment]
![screen shot 2017-04-29 at 6 43 02 pm](https://cloud.githubusercontent.com/assets/20460498/25555727/c317a1d0-2d0b-11e7-80f6-11d503a4aa20.png)

Kindly recheck on the latest version & re-open issue, if needed
