### ISSUE TITLE
Salary Structure field shows incorrect employee for given ID

### ISSUE THREAD

**Issue by Tropicalrambler** [frappe/erpnext#8141]
**Desk>Human Resources> Salary Structure**>  where is says "Select employees for current Salary Structure",  the field for **Employee** allows you to enter the name or ID.  Once data is selected, the ID remains correctly, but the shown name in the same field after the ID is incorrect, it appears to be the name of the employee whose id is two ID's away.   The structure registers correctly, and in a pay slip refers correctly to the desired employee, but it simply has this bug that can be confusing and shows inconsistency.

**Comment by tundebabzy** [comment]
I believe this must have been fixed as I cannot replicate this on my setup.

![screenshot from 2017-06-06 14-40-06](https://cloud.githubusercontent.com/assets/818803/26832107/47999b8e-4ac6-11e7-8071-be8afa4ad74c.png)

![peek 2017-06-06 14-39](https://cloud.githubusercontent.com/assets/818803/26832117/4e948bf6-4ac6-11e7-8c58-8d74f232a7ed.gif)


Please feel free to reopen this if contrary is the case.

**Comment by Tropicalrambler** [comment]
Thanks. Will run an update and verify. If it pops up again, I'll reopen.

**Comment by Tropicalrambler** [comment]
Thanks on verison 9 the bug is gone.  let's close this.
