### ISSUE TITLE
[Enhancement] Contact name when lead is converted

### ISSUE THREAD

**Issue by ishanloya** [frappe/erpnext#8143]
From the [forum](https://discuss.erpnext.com/t/contact-name-when-lead-is-converted/8947):

> Say I have a lead, named John Doe. While he is a lead, his full name is stored in person_name. When I convert to a customer, the lead is converted into a contact and the full lead name is dumped into the contact's first name.
> 
> Does it make sense to either de-concatenate the name (not sure if that's the right word) when the contact is added? Or perhaps change contact name to be full name?
>

**Comment by kennethsequeira** [comment]
The system splits first and last names in contact when a lead is converted to customer
