### ISSUE TITLE
Prettify summernote code view, currently it is very difficult to edit anything

### ISSUE THREAD

**Issue by nabinhait** [frappe/erpnext#8144]
<img width="926" alt="screen shot 2017-03-25 at 2 24 24 pm" src="https://cloud.githubusercontent.com/assets/836784/24320961/f04c6a16-1166-11e7-9568-979d7b22b35c.png">

**Comment by dottenbr** [comment]
Completely agree. The code generated is not as buggy as before but it is still unreadable.
