### ISSUE TITLE
New Employee Loan Application - Employee ID is updated, but Employee Name not fetched from Employee master

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#8146]
In the New Leave Application, Employee ID is auto-updated, but Employee Name is not auto-fetched.

![screen shot 2017-03-25 at 4 07 01 pm](https://cloud.githubusercontent.com/assets/910238/24321561/3d5061ba-1175-11e7-9735-a2614745d379.png)

On saving Loan Application, Employee Name is fetched correctly.

**Comment by KanchanChauhan** [comment]
Tested on my local and demo, works fine. Can you please check again @umairsy

**Comment by jwrober** [comment]
Please open a discussion on this subject in the forum - https://discuss.erpnext.com/ - to get help with this.
