### ISSUE TITLE
Employee Loan - Monthly Installment not fetched from Loan Application

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#8147]
Loan Application already have value for the monthly installment. Also Employee loan has values (indicated with arrows) based on which Monthly Installment could be calculated.

![screen shot 2017-03-25 at 4 09 36 pm](https://cloud.githubusercontent.com/assets/910238/24321583/b6dd02a4-1175-11e7-80d6-2a5e0fc73a7b.png)

**Comment by KanchanChauhan** [comment]
@umairsy It is not fetched from Loan Application, it is populated when Installment Schedule is created.

**Comment by jwrober** [comment]
So is this an issue or not?

**Comment by jwrober** [comment]
@umairsy - please help us understand if this is an issue or not based on @KanchanChauhan comment. Please add more commentary to this issue to help team better understand the issue.
