### ISSUE TITLE
Can't add operation, can only add activity into the timesheet

### ISSUE THREAD

**Issue by mengyewc** [frappe/erpnext#8149]
During BOM of an item, I can specify operation. When I go to the timesheet to set the duration of an  operation within a production, there is an "add new row". But the added rows can only be "activity". Why can't I add a new operation to the existing one.

**Comment by PawanMeh** [comment]
Operation is linked to BOM and activity is linked to timesheet. If you have questions, kindly post them on [discuss](discuss.erpnext.com)
