### ISSUE TITLE
Sales Campaign fields

### ISSUE THREAD

**Issue by lxnow** [frappe/erpnext#815]
I intend to adapt it for the following: we want to track the sales campaigns we give to customers. We have three types of scopes, (1) customer-specific, (2) national-level, i.e. covers all customers, and (3) multiple customers. 

Useful default fields would be:
- start date
- end date
- budget (float)
- customer (link) or customer group (link)
- campaign type
- description

Key here is that we should be able to reference a campaign from a Sales Order or Invoice so that it would be useful for answering questions like:
- What sales (or orders) were generated by this campaign? Or how big was this campaign?
- How much of our sales are campaign-driven vs regular sales?

In order to do this, functionality should be that campaigns are filtered by customer, customer group or "valid for all" when selecting a campaign.  Also, campaign should be "active" (within start and end dates) when it is being selected in an order / invoice.

**Comment by PawanMeh** [comment]
Campaign effectiveness report is added in the latest develop branch (issue #8466), it may meet some of your needs, please take a look at it & if needed you can suggest enhancements to it with screen shots. Closing this for now.
