### ISSUE TITLE
Comments posted to all UOMs rather then to a current one

### ISSUE THREAD

**Issue by gvyshnya** [frappe/erpnext#8151]
**Summary**: it is possible to apply a comment you specify for one particular UOM to all UOMs in UOM list without any intention to do so

**Steps to reproduce:**
1. Log into ERP Next and go to the desk
2. Navigate to Setup > UOM to get UOM List view open
3. Click on any UOM (Kg, for example)
4. Navigate to 'Add comment' section of the UOM and put a comment
5. Click 'Save' button at the top of UOM details form

**Expected result**: the system will  put a comment to just a current UOM (Kg, in my example), similar to what happens when a user clicks on grey 'Comment' button in 'Add comment' section

**Actual result**: the system will apply the comment to all UOMs in the system per UOM List

This is reproduced on a server with
- Frappe 7.2.30
- ERP Next 7.2.30

**Comment by Arundhatii** [comment]
A comment is saved in Doctype when you click on Comment button. Please refer the gif attached. 
![uom issue](https://cloud.githubusercontent.com/assets/20164097/24407899/e2838790-13e9-11e7-9a35-e092ee381760.gif)

**Comment by gvyshnya** [comment]
@Arundhatii: we quite understand how Comment button works :-), and we understand it is a work-around to the global issue with Save button and Comment being a separate doctype vs. being the part of UOM doctype (or any other DocType that attaches comments to).

From usability stand-point, it would be nice that clicking Save button does the same. That's the sense of the bug request.

What Save button clicks does right now (saving a comment to all UOMs at once) is not appropriate.

We really understand technical complexities here (as a Comment implemented as a separate DocType and not the part of the DocType it is being associated with). However, we still have to have consistent system behaviour on this piece of functionality.
