### ISSUE TITLE
Disable Signup and Web Pages - Security Issue

### ISSUE THREAD

**Issue by stelden** [frappe/erpnext#8153]
Hi all,

1. Disabling signup on the login page only hides the signup link. Simply typing the login url with #signup will present the signup form and allow virtually ANYONE including bots (since there's no captcha) to create a user account. Fertile ground for DoS attack.

2. Same goes for default Web Pages such as Contact Us and About Us. By simply typing the 'contact' url one can access the Contact Us page (again with no captcha) even when its not in use. If these pages are not in use, they should NOT be accessible from any url. If they are they should be protected from abuse.

How can we **completely disable access to Signup, Contact Us etc** and if they are not in use?

**Comment by dottenbr** [comment]
@stelden I would recommend you split this into two issues. They are not directly linked so both can be worked on separately. Would you do that?

**Comment by stelden** [comment]
Sure.

**Comment by joezsweet** [comment]
Hi there, for 1st issue has been pushed a fix 

https://github.com/frappe/frappe/commit/a21db81a28cc0418f590db801e1e5f8f2e9eab9d

**Comment by stelden** [comment]
Great.
