### ISSUE TITLE
Disable Unused Default Web Pages

### ISSUE THREAD

**Issue by stelden** [frappe/erpnext#8154]
Hi All,

Default Web Pages such as Contact Us and About Us are accessible via url even though they may not be in use. A page like Contact Us with no Captcha is a security risk. If these pages are not in use, they should NOT be accessible from any url. We need a way to keep them 'Unpublished'.

**Comment by jwrober** [comment]
This is probably best to be in the frappe repo, website is a core component of the framework

**Comment by stelden** [comment]
Ok. will move it there. Thanks.
