### ISSUE TITLE
[Paid Development] contract module

### ISSUE THREAD

**Issue by elzeinae** [frappe/erpnext#8158]
dear Sir/ Madam
good day 
I am looking for development in erpnext, a contract module which is 

custumizable
some terms is followed eg years of subscription
those terms can be used for assessing sales personale with customizable formula
alert for resubscription
integrated with other modules if needed

how much does it cost and how long does it take

**Comment by joezsweet** [comment]
Please post at https://erpnext.org/erpnext-jobs
