### ISSUE TITLE
Need to Delete User

### ISSUE THREAD

**Issue by jonathansayeb** [frappe/erpnext#8159]
Hello one of our staff is leaving the company and she has access to ERPNEXT. We need to delete her as user but there have been auto-generated communications that prevent to do so. Also i cannot manually delete these auto-generated communication.
Please can you explain how to do in our case as 'i'am sure someone else had to do with it in the past.

Cheers,

**Comment by nabinhait** [comment]
User record cannot not be deleted, as it is linked to many documents which he/she created. You should disable the user.
