### ISSUE TITLE
Stock and Fixed Asset Query

### ISSUE THREAD

**Issue by neuralaccounts** [frappe/erpnext#8160]
Hello i require clarification or suggestion for following two three issues
1. Actually in new version of ERP we don't have the option of transferring the stock to asset through journal entry which i think should be added in the given feature as when we term any item as fixed asset then we don't have the option of tracking it through serial number as in case of fixed asset purchase there is no option for quoting the serial number. 
2. I have one more issue regarding fixed asset purchases, our company sometimes purchases some items for resale and similar items are even purchased as fixed asset so in such case we will have to altogether create duplicate item codes in order to maintain it in stock and others in fixed asset is there any option through which we can create one item and as per terms whether it can be bifurcated in particulars heads of fixed asset or stock  while booking GRN in system.
3. While calculating depreciation manual entry feature is not available as the amount of depreciation is not fixed so even required that option. As in the first year if suppose the depreciation amount is quoted Rs.12,283 but in next year it might be lessor than that so will i have to cancel the earlier year entry in order to change the next year depreciation amount. Attached screenshot for reference as the amount will differ as per depreciation rate of company's act.

![image](https://cloud.githubusercontent.com/assets/8178775/24342909/5fe9a2b4-12e1-11e7-954e-2978c961ae60.png)

Awaiting your reply.
Regards,
Gayatri Nadkarni

**Comment by neuralaccounts** [comment]
Dear Sir,

Awaiting reply for the given issues

**Comment by rmehta** [comment]
To be handled via ERPNext Support
