### ISSUE TITLE
Salary Component - Extra Fields Suggestion

### ISSUE THREAD

**Issue by brownharryb** [frappe/erpnext#8165]
I think the Salary Component doctype in the HR module should have a formula (and maybe a default amount) field.

I believe doing it at this level prevents having to deal with putting it in either earnings or deductions tables in Salary Structure just to get a value to calculate with, encourages DRY and a bit of data encapsulation and also, enabling it calculate based on other components(if exists) from the modular level.
This way, it's just a matter of linking to the right component in the earnings and deductions table.
These tables however should still retain the formula and amount fields in case of an override for an employee.

Regards
Boma.

https://discuss.erpnext.com/t/suggestion-for-salary-component/21679

**Comment by jwrober** [comment]
This would be a great feature. Thanks @KanchanChauhan for picking this up. Having the formula on the component would certainly facilitate more reuse of them.

**Comment by ckosiegbu** [comment]
I think that formulas should be left out of components and only used in the salary structure. 

However, I think that the following changes could help to increase the flexibility and ease of definition of salary structures:

- An additional type called **General** should be defined for the Component doc-type. This type of component can appear under both earnings and deductions sections in pay structure.
- Deductions and Earnings tables under the Salary Structure should have two checkbox fields added to them:
          - Statistical Item - If this is checked, it indicates that the specified row in not a deduction/earning but is used to store the values of intermediate steps of calculations and can be referred to by other steps of the calculation.
          - Display in Payslip - if this is checked it indicates whether the step in deduction/earning should be displayed in the payslip. It should be on by default. I suggest that only statistical items should have the ability to uncheck for display.

Regards,
cksgb
