### ISSUE TITLE
Link on Frappe site goes to incorrect ssl link

### ISSUE THREAD

**Issue by joolsr** [frappe/erpnext#8168]
If you click here  https://frappe.io/apps

When you click on the ERPNext link it takes you to a page with an incorrect ssl cert so browser complains and wont let you go to page ie https://github.frappe.io/erpnext ie

![screenshot 2017-03-27 at 18 15 58](https://cloud.githubusercontent.com/assets/934876/24368741/7f4301ae-1319-11e7-9785-05c681d37b4d.png)

**Comment by mona1977** [comment]
Hello, I just setup SSL certificate on erpnext,

 i will explain you , Please can you add my SKYPE - suren_gupta

**Comment by mona1977** [comment]
or give me your skype id
