### ISSUE TITLE
Sale Bom feature suggestion

### ISSUE THREAD

**Issue by ftoth** [frappe/erpnext#818]
I've set up prices for Package Items in Price List. In Selling>Sales BOM>New Sales BOM there is no information about Package Item Price (column "Rate"), it is always  0,00 (unless I manually set it up).
Goal is to have price or suggested price for Parent Item based on rate and quantity of Package Items. Otherwise I have to manually add sales prices of Package Items for Parent Item.
Suggestion:
Total value (sum) of packaged items could be default price for parent item. It could be also interesting to choose from price lists when going to determine the price of parent item from packaged items (in other words, packaged and parent item should have same price list). 
Thank you,
Ferenc

**Comment by Arundhatii** [comment]
Closing the issue for now as no further discussion or similar requirement is raised. Please feel free to reopen if it is still relevant.
