### ISSUE TITLE
[Bug] Misleading error in Stock Entry

### ISSUE THREAD

**Issue by vjFaLk** [frappe/erpnext#8180]
On Submitting a Stock Entry for an Item that doesn't have a Valuation Rate. It mentions that the Serial Nos of the Item have been created however, it doesn't actually create them.

![image](https://cloud.githubusercontent.com/assets/6697133/24399692/2df47dca-13cb-11e7-9b1f-6d971a77055e.png)

**Comment by neilLasrado** [comment]
I am working on fixing this issue.
