### ISSUE TITLE
Heading for a custom field of the type Text editor is not visible in the Print format.

### ISSUE THREAD

**Issue by Arundhatii** [frappe/erpnext#8187]
When creating a custom field in the a Doctype, if the field is of the type Text editor, the heading is not visible is the print format. Refer the discuss post.
Can replicate the issue in test account as well.

**Comment by Arundhatii** [comment]
https://discuss.erpnext.com/t/print-format-problem-of-custom-doc-types/21803

**Comment by rohitwaghchaure** [comment]
This is a by design, if you need header
