### ISSUE TITLE
Image uploaded on previously created Contacts is not displayed where as for new contact it is visible.

### ISSUE THREAD

**Issue by Arundhatii** [frappe/erpnext#8188]
When trying to upload a image for previously created contact, it is not displaying on the doctype. When creating a new contact and adding an image to that is working fine. Can replicate the issue on demo.erpnext.com. 
![image issue](https://cloud.githubusercontent.com/assets/20164097/24407374/4f341c8a-13e8-11e7-9b84-eb404cb93505.gif)

**Comment by me2ne** [comment]
I report long it , but they close case :( 

https://github.com/frappe/erpnext/issues/7707

**Comment by manassolanki** [comment]
@Arundhatii I am not able to replicate this on the demo.erpnext.com, could you please cross check again or can let me know the steps for replicating this.

**Comment by me2ne** [comment]
problem solved in last version

**Comment by netchampfaris** [comment]
Cannot replicate on the latest version. Closing.
