### ISSUE TITLE
production operation timesheet needs to be able to pause and resume

### ISSUE THREAD

**Issue by mengyewc** [frappe/erpnext#8189]
During production there has to be interruptions. In real world, there can never be totally smooth uninterrupted production cycle all the time
Interruptions can come in any form may it be power failure, power trip, change of spare parts, change of shift, staff break, lunch break, machine jam, workpiece stuck. The most common interruption is end of workday, where plant is not running 24hours nor overtime. Worker simply go back and resume the operation the next day.

There is a real need for the production operation timesheet to be able to pause and resume, essentially split the operation into multiple smaller operations whenever you pause and resume.
The total time of operation is the sum of all multiple operations

**Comment by chdecultot** [comment]
Hi @mengyewc,

A timesheet can already be split into several part by adding new rows in the timesheet table:
![image](https://cloud.githubusercontent.com/assets/4903591/25651105/8b7a5474-2fe1-11e7-821a-be72d4ab022f.png)

You want to be able to pause and resume a single row if my understanding is correct. In this case, can you please follow the [contribution guidelines](https://github.com/frappe/erpnext/wiki/Issue-Guidelines) and enhance your issue with the following elements ?
1. Can you please be very specific about how the feature should work (and how you would like the existing feature to be modified) and look like.
2. Create a mockup of the desired feature

It will help the Frappe Team and the Foundation understand your needs in details and consider this enhancement for a future release.

Thank you very much.

**Comment by sharmanakul** [comment]
I'm closing this for now. Feel free to reopen and provide the use-case and the flow that is required.
