### ISSUE TITLE
Hide Purchase Items in Production Order - Item to Manufacture

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#8191]
In ``Production Order`` when selecting ``Item to Manufacture ``we should hide Items that have ``Is Purchase Items == true`` since they are purchased, not manufactured.

**Comment by nabinhait** [comment]
I think a purchase item can also be a manufacturing item. There was a dedicated field "Is manufacturing item" in the Item to filter out the items, but we have deprecated it in some earlier version.

**Comment by dottenbr** [comment]
why would a purchase item be an item that you manufacture? I think its either buy or make.

**Comment by bcornwellmott** [comment]
@dottenbr,  because sometimes you make it and sometimes you buy it. This is a situation we often face, where we will buy something from a supplier most of the time, but if we need it right away we may make it ourselves.

**Comment by kickapoo** [comment]
@dottenbr Please check this one. If is not generic, I will make it as custom script in our instance also based on your call i will close the PR.

**Comment by dottenbr** [comment]
OK then this is a case of custom script if people need to list it please close the issue then @kickapoo
