### ISSUE TITLE
Only show Sales Orders that have the Item to Manufacture in them in Production Order

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#8192]
When selecting the ``Sales Order`` in a ``Production Order`` please only list those ``Sales Orders`` that have the ``Item to Manufacture`` in them as ``Sales Order Lines``.

**Comment by Devens** [comment]
+1

Regards,
Deven Shah
098250 60116

**Comment by dottenbr** [comment]
not as simple as it seems because it's a child of the doctype to be filtered

**Comment by kickapoo** [comment]
@rmehta @nabinhait 

Where is an example to filter parent Doctype from Child table value ?

**Comment by rmehta** [comment]
You can write a `DISTINCT` query on `parent` for Sales Order Item. That should be easy?

**Comment by kickapoo** [comment]
@rmehta the way I know to make custom query is like 👍 
```
cur_frm.fields_dict['items'].grid.get_field('fieldname').get_query = function(doc, cdt, cdn) {
  var row = frappe.get_doc(cdt, cdn)
	return {
		filters: [
                 ['parent', '=', row.item_code ]
             ]
	}
 }
```

I dont know where to write the custom sql query.

**Comment by kickapoo** [comment]
Found it

```
cur_frm.fields_dict[child table's fieldname].grid.get_field("item_code").get_query = function(doc, cut, cdn) {
return your query
}

```

**Comment by kickapoo** [comment]
@dottenbr  
Please `Item to Manufacture` your mean in Item 'default_material_request_type' == 'Manufacture' ?

Sorry but I cant find an clear indicator for `Item to Manufacture`.

**Comment by creamdory** [comment]
@kickapoo indicators for Item to manufacture would be if an item has a BOM setup.
