### ISSUE TITLE
Add Account Number

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#8194]
In ``Accounts`` we have account numbers. We use the German [SKR03](http://www.willer-partner.de/fileadmin/images/aktuelles/SKR03_mit_neu_eingefuehrten_und_geaenderten_Konten.pdf) for which every accountant ant tax consultant typically doesn't refer to the full account name but instead the account number e.g. "4955" would be "Cost related to Accounting".

- [ ] Add ``Account Number`` to ``Account``
- [ ] Show ``Account Number`` in ``Account Tree``
- [ ] Make ``Account Number`` searchable in link field and enable it for quick entry

**Comment by Olawale1** [comment]
It would be nice if the accounts could also be ordered by number instead of alphabetically

Kind regards,

**Comment by dottenbr** [comment]
Currently Stavros made a small patch which will add an account field and will render it in the chart of accounts tree view. This is a fist step but it doesn't make it searchable in link fields nor does it make it possible to order the accounts by that number.

Any ideas on how to improve on this?

**Comment by kickapoo** [comment]
@nabinhait @rmehta 

the is a link to my code on this. I have added an custom field Account Number and show it in tree view only if its added. 

How can I set the order ? based on @Olawale1 request. 
How can I add Account Number in Link Search options? (please provide the file path with Account Link functionality)

**Comment by rmehta** [comment]
> the is a link to my code on this. I have added an custom field Account Number and show it in tree view only if its added

Let us discuss the full workflow. For sorting, you can do it in the client (JS) code, maybe sort-key becomes an option.

Maybe if we just define the name as `{Account Code} {Account Name}` that should do for most cases (?)

**Comment by dottenbr** [comment]
Yes, I think the name as ``{Account Code} {Account Name}`` is probably best. So if people choose to use the ``Account code`` it will show everywhere. Slowly existing accounts could be updated for those who care.

**Comment by kickapoo** [comment]
![screenshot 2017-04-07 12 07 04](https://cloud.githubusercontent.com/assets/5064612/24793567/3712cc50-1b8b-11e7-8fa3-a1469d2d112b.png)
![screenshot 2017-04-07 12 07 23](https://cloud.githubusercontent.com/assets/5064612/24793568/37163ffc-1b8b-11e7-9296-0ebe2fe70c5c.png)
![screenshot 2017-04-07 12 08 56](https://cloud.githubusercontent.com/assets/5064612/24793569/3717e1ea-1b8b-11e7-9fe8-bc577beacbed.png)

**Comment by kickapoo** [comment]
@dottenbr @rmehta @nabinhait 
May I made a partial PR for this ?

**Comment by bghayad** [comment]
How I can download this batch?

**Comment by bghayad** [comment]
Thank you. But this batch is working with which erpnext version? My version is: v7.2.14

**Comment by nabinhait** [comment]
@bghayad It is not merged yet

**Comment by bghayad** [comment]
Yes I  understood that it is not merged. But it can be used with version 7 or version 8?
In other words, as my version is 7.2.14, so all what I need is to replace the current three files account.json, account_tree.js, utils.py with the files in the above link? And this can be applied to all versions (6 and 7 and 8)?

**Comment by nabinhait** [comment]
@bghayad No, it does not work in that way. It can lead to many other unwanted errors. Why are you not upgrading to version 8?

**Comment by bghayad** [comment]
So I have to be version 8?

**Comment by josmeldiaz21** [comment]
How can I use this feature? I have Version 8.0.15.

**Comment by vrms** [comment]
> @bghayad _"So I have to be version 8?"_

apart from the fact that this feature has not been merged (and likewise made available to use) for any version yet .... generally there will not be new features added to older Versions. 

So, if you want to be able to leverage new features like this you'll have to upgrade to the current version of ERPNext

**Comment by bghayad** [comment]
Now I have the following versions:

ERPNext: v8.0.29 (master)
Frappe Framework: v8.0.47 (master)

I got this error when I added the account number feature, can someone help me please:

  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler raise errorclass, errorvalue
OperationalError: (1054, "Unknown column 'account_number' in 'field list'")

Appreciate the kindly help.
Regards
Bilal

**Comment by bghayad** [comment]
OK, I resolved the problem by adding the field account number using form customization (customization for doctype) in the setup.
But, how to generate the account number automatically instead of adding it manual one by one?
Regards
Bilal

**Comment by krnkris** [comment]
How and where we should indicate the account numbering in the
https://charts.erpnext.com/ page to be in line of the new account numbering?

**Comment by nabinhait** [comment]
Sent a PR, closing this.
