### ISSUE TITLE
Moving material between warehouses

### ISSUE THREAD

**Issue by Priyanka-IAS** [frappe/erpnext#8197]
Since material that is shipped from our supplier takes more than 8-10 weeks to reach us, we typically show the material in and "In Transit" warehouse. Once the material physically reaches our location, we move it from "In Transit" warehouses to other warehouses.

Currently using Stock Entry to do this for each item manually. Very time consuming and error prone!

Would like one of the following:

1. Have an "Get From Purchase Invoice" option to get all items from a purchase invoice into the Stock Entry

2. Have a "Move warehouse" button on the Purchase Invoice itself where I can just select the warehouse that the material needs to be moved to.

This is an important issue for us and we would be willing to pay for this development.

- Priyanka

**Comment by Priyanka-IAS** [comment]
Please see details of our requirement below:

Summary: Since our incoming material (Purchases) comes by OCEAN from USA, it takes typically 8-9 weeks in transit before it is received at our physical warehouse. When it is shipped from our shipper, we add the material to our virtual “In-Transit” warehouse in ERPNext.

Once the material physically reaches us, we use Stock Entry to move this material from “In-Transit” warehouse to “Stores” warehouse in the ERP.

We need this implemented in the following way

In Stock Entry, have an option of “Get Items from Purchase Invoice” which gets all items from the chosen Purchase Invoice including the Batch Nos and quantity. We chose the target Warehouse and all items get moved to the target warehouse.

There would need to be a check that all items from the Purchase Invoice are still available in the source warehouse in the original quantities for each Batch No.

I hope this requirement is clear. Let me know if you need any further details.

**Comment by sharmanakul** [comment]
I think that fetching purchase invoice items is possible in the stock entry and if the batch is set in the PI then that also gets fetched into the stock entry.
Items availability can be checked through various reports.
I'm closing this issue. Please reopen if the requirement is not yet fulfilled.
