### ISSUE TITLE
Grid Layout in Production Order Operations

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#8198]
Currently the grid of ``Operations`` in ``Production Order`` is not using space well. Why dont we use the Bootstrap colum sizing to improve it from

![grafik](https://cloud.githubusercontent.com/assets/9136094/24445048/f1aef2d4-1468-11e7-8605-1dbab686caa2.png)

to

![grafik](https://cloud.githubusercontent.com/assets/9136094/24445053/f420fe40-1468-11e7-8887-214144ab80c6.png)

See https://v4-alpha.getbootstrap.com/layout/grid/#variable-width-content

**Comment by emakis** [comment]
The column sizing is a bootstrap v4 fixture which is still in alpha testing mode. Let's hope to have the first release soon and adopt it in our systems with backward compatibility

**Comment by dottenbr** [comment]
Bootstrap's v4.0.0-beta is 90% done on GitHub so I assume that v4 will be ready by the middle of the year?

**Comment by creamdory** [comment]
We can use this setting for a workaround. @dottenbr @emakis 

![columns](https://user-images.githubusercontent.com/21003054/27019401-d9e09f3a-4f6a-11e7-9ee2-d511110557da.png)
