### ISSUE TITLE
Print format custom HTML bootstrap bug

### ISSUE THREAD

**Issue by ankitmania** [frappe/erpnext#8199]
Hello,

I use custom HTML in the print format. The issue is that the print preview is fine but when the same document is saved as a PDF, the format changes.

I will illustrate through screenshots
HTML code in print format - OK
![html_code](https://cloud.githubusercontent.com/assets/5123602/24446865/b53bf5f4-1477-11e7-8c9b-0be2356eb4ba.PNG)

Print preview - OK
![print_preview](https://cloud.githubusercontent.com/assets/5123602/24446882/c8f9d3ae-1477-11e7-9223-c93d50f1daf8.PNG)

PDF view - Not OK
![issue in pdf export](https://cloud.githubusercontent.com/assets/5123602/24446886/d2f04c1c-1477-11e7-9bdf-b3ec5e128345.PNG)

**Comment by PawanMeh** [comment]
You may find the following [link](https://discuss.erpnext.com/t/setting-wkhtmltopdf-pdfkit-options-via-custom-print-format/22681/2) useful, if this helps resolve your issue, kindly close it.

**Comment by ankitmania** [comment]
works well with the col-xs-4. Closing the ticket. Thanks.
