### ISSUE TITLE
“There were errors” - Trying to setup new site (Setup wizard fails)

### ISSUE THREAD

**Issue by ratskin** [frappe/erpnext#8209]
Two topics on **discuss.erpnext.com**:
https://discuss.erpnext.com/t/there-were-errors-trying-to-setup-new-site/21827
https://discuss.erpnext.com/t/setup-wizard-fails/21881

Brief overview of my troubles:

* Ran ```bench start```
* Visited http://localhost:8000/ and logged in as Administrator
* Completed setup and clicked on **Complete Setup** button
* Waiting... then:
`Message\n There were errors.`

Here is a picture of the error screen, console and a gist of the server console while doing this:
http://i.imgur.com/FZJg2ai.png
http://ibb.co/b17N1F
https://ibb.co/iAHuFa (Seems to be a problem loading `http://{ip}:9000/socket.io/?EIO=3&transport=polling&t=1490794093971-1`)
https://gist.github.com/ratskin/9122d3665a4ac5cdc62303f7cdba53eb

My relevant system stats:
* macOS Sierra
* Frappe/ERPNext v7 develop branch
* Fresh install of Bench and Frappe.
* Old MariaDB/MySQL installation from previous attempts at this. Dropped all databases.

Relevant commands I ran previous to this
```bash
git clone https://github.com/frappe/bench bench-repo
sudo pip install -e bench-repo
bench init frappe-bench && cd frappe-bench
bench get-app erpnext https://github.com/frappe/erpnext
bench new-site site1.local
bench --site site1.local install-app erpnext
bench start
```
Also, if I don't install ERPNext then I can complete the setup

I have also tried to install frappe-bench on an ubuntu server virtual box, I was getting the same errors. **I have been having these errors for the past 5 days**

### If anyone has any suggestions, help, questions, or comments, I would appreciate them. 

*p.s. I think the error screen is quite boring, it could be made better with [haiku](https://www.gnu.org/fun/jokes/error-haiku.html)*

**Comment by salimcmd** [comment]
Any updates on this?

**Comment by ratskin** [comment]
# Update:
Make sure the last page looks like this and you are on v8 then the installation runs fine.
This is obviously still an issue though.
https://discuss.erpnext.com/uploads/default/optimized/2X/2/20fb5f98aaf31c1126a8fff40f3cfe268e8a7877_1_575x500.jpg
https://discuss.erpnext.com/uploads/default/optimized/2X/1/10602ea18bd9d5597a81c9bee509ed74f19cdb57_1_690x431.png

**Comment by ratskin** [comment]
https://discuss.erpnext.com/t/there-were-errors-trying-to-setup-new-site/21827/29?u=ratskin
https://discuss.erpnext.com/t/there-were-errors-trying-to-setup-new-site/21827/30?u=ratskin

**Comment by ishanloya** [comment]
On the items screen, when I unchecked (we sell this item and we buy this item), it worked for me.

**Comment by PawanMeh** [comment]
Kindly check on the latest version, if issue persists, create a new issue with relevant screen shots, along with information Frappe framework version.
