### ISSUE TITLE
Payment Entry Reference - Wrong currency

### ISSUE THREAD

**Issue by addymuliady** [frappe/erpnext#8217]
Scenario: Supplier is in SGD currency, Company is in USD
For Payment Entry Reference below, Total Amount (USD) is wrong. Should be Total Amount (SGD#suppliercurrency)

![image](https://cloud.githubusercontent.com/assets/21187126/24475375/35bd9e3c-1502-11e7-99c6-1a58a563580d.png)

**Comment by addymuliady** [comment]
Thanks @nabinhait !

**Comment by tundebabzy** [comment]
Hello @addymuliady 
Sorry this reply is coming so late. 

The reported situation can happen when the `Credit To` field on the purchase invoice was set to an account that is in the default currency. After selecting the `Party Type` and `Party`, ERPNext will attempt to get all outstanding invoices tied to the `Party` and assume that all the records it retrieves are in the currency of the account set in the `Account Paid To` field. The `Account Paid To` field by default is the same as the account set in the `Credit To` field of the Purchase Invoice.

The `Credit To` field is found in the `More Information` section of the Purchase Invoice form.

Please reopen if the circumstances are different.
