### ISSUE TITLE
Don't show item in list view if "User Cannot Search" is checked

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#8222]
For now, it only shows Role. And there is no detail of the DocType for which this permission rule has been added.

![screen shot 2017-03-30 at 3 20 15 pm](https://cloud.githubusercontent.com/assets/910238/24498571/81bdb394-155c-11e7-9262-988d70ab7da7.png)

**Comment by rmehta** [comment]
why do you want to see this? This is an internal document.

**Comment by rmehta** [comment]
Should not show in awesome bar if "User Cannot Search" is checked

<img width="1047" alt="screen shot 2017-03-31 at 5 26 16 pm" src="https://cloud.githubusercontent.com/assets/140076/24549521/50439cda-1637-11e7-8775-ab6ed912ff6a.png">

**Comment by pratu16x7** [comment]
frappe/erpnext#8222
