### ISSUE TITLE
[v8] Cant open any list

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#8228]
Hello,

When opening any list view, it shows this error

> Traceback (most recent call last):
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 56, in application
>     response = frappe.handler.handle()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
>     execute_cmd(cmd)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 42, in execute_cmd
>     ret = frappe.call(method, **frappe.form_dict)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
>     return fn(*args, **newargs)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/reportview.py", line 14, in get
>     args = get_form_params()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/reportview.py", line 48, in get_form_params
>     parenttype = doctype
> NameError: global name 'doctype' is not defined

**Comment by nabinhait** [comment]
Fixed
