### ISSUE TITLE
[v8] Cannot select day/week/month after upgrade

### ISSUE THREAD

**Issue by joolsr** [frappe/erpnext#8234]
After upgrading to v8.02 from v7.31 when I view a project via its gantt chart view i can no longer see a means to select which period to view the chart over.
![screenshot-gantt](https://cloud.githubusercontent.com/assets/934876/24510093/173764ee-1560-11e7-9bbc-72d1e1d5df20.png)

**Comment by netchampfaris** [comment]
@joolsr Can you also post the screenshot of your JS console?

**Comment by joolsr** [comment]
yes, here it is. It was working fine for me on vers8 develop. Using Chromium Version 57.0.2987.110 (64-bit) on Manjaro Linux
![screenshot-gantt-console](https://cloud.githubusercontent.com/assets/934876/24550547/73c95206-1616-11e7-81b6-7178ba933749.png)

**Comment by Dbonejones** [comment]
+1

Have the same issue here.
