### ISSUE TITLE
Can’t save the Notification Email account (Default sending) 

### ISSUE THREAD

**Issue by aissaghouti** [frappe/erpnext#8237]
Hi all,

I tried to configure the "Notification" Email account but each time a click on the save button, the "Saving" message appears and stays stuck on the screen indefinitely.

Do you have any idea about what is causing this issue?
I'm using ERPNext 7.

Thanks.

<img width="500" alt="6d5eb1ce9196f44ef0578e28bae3d9ecc3af23fc" src="https://cloud.githubusercontent.com/assets/8360721/24512095/ebd89dfa-156d-11e7-812f-231c49308ec2.png">

**Comment by mbauskar** [comment]
@aissaghouti,

I am able to save the Email Account settings, can you share the SMTP server details like?

**Comment by rmehta** [comment]
Catch the issue and show Timeout
