### ISSUE TITLE
[v8] Erpnext icon not appear on small screen

### ISSUE THREAD

**Issue by almeidapaulopt** [frappe/erpnext#8239]
Erpnext icon not appear on small screen, so you cannot only go to Desk with use Desk.

![peek 2017-03-30 17-35](https://cloud.githubusercontent.com/assets/22657407/24515561/e537c348-156f-11e7-88aa-743f8d9bdca2.gif)

**Comment by Arundhatii** [comment]
Can replicate the issue.
![error on mobile](https://cloud.githubusercontent.com/assets/20164097/24516458/51032f86-1598-11e7-9af5-0c662a2c677f.jpg)

**Comment by rmehta** [comment]
E icon is only seen on the home view. This is design to save space for breadcrumbts

**Comment by almeidapaulopt** [comment]
So there is no chance to go to desk on mobile?
