### ISSUE TITLE
"Folder List does not exist" when try to enter intoTools >> Files 

### ISSUE THREAD

**Issue by Arundhatii** [frappe/erpnext#8240]
"Folder List does not exist" when try to enter into file manager module in ber 8.0. Anyone can help?
When I try to create new folder I get "Server Error: Please check your server logs or contact tech support." message
Refer the gif below.
![files error v8](https://cloud.githubusercontent.com/assets/20164097/24516661/1f3723a8-1599-11e7-80a7-3769e3bf8b00.gif)

**Comment by nabinhait** [comment]
fixed
