### ISSUE TITLE
UTC Errors V8 - Stock Ledger and Accouting Ledger Reports 

### ISSUE THREAD

**Issue by RandyLowery** [frappe/erpnext#8244]
Updated to v8.3 and found errors in the new datepicker in both reports this ocurrs in demo.erpnext.com and in local isntance while creating any transaction after validating run the view accouting ledger, the default report from date shows random, an in the new datepicker hitting the today button does noting.
![untitled picture](https://cloud.githubusercontent.com/assets/20528130/24522731/b121f78a-154d-11e7-953b-c295a2792762.png)
Also in Accouting ledger report the voucher number is missing as link. 
![untitled picture2](https://cloud.githubusercontent.com/assets/20528130/24522735/b38b7b5e-154d-11e7-9a31-83f0b3dde032.png)

**Comment by joezsweet** [comment]
@RandyLowery what time zone is set in your computer?

**Comment by RandyLowery** [comment]
America / managua

**Comment by joezsweet** [comment]
@RandyLowery thought that, can you change to UTC and test? only to confirm that's working on UTC, thx

**Comment by RandyLowery** [comment]
Seems to be related. This is what i tried 
VM set to UTC 
accesing inside vm via firefox everithing work fine both error disapeared
accesing outside vm via firefox and chrome. Errors persist

VM set To UTC -6
Error accesing inside vm and outside vm

Seems that it happen when the computer i use to acceses the erpnext is not set to other than utc

**Comment by joezsweet** [comment]
I think it works till UTC-4, but now sure why.

**Comment by jwrober** [comment]
I changed my laptop to UTC from US/Chicago and it works now

**Comment by jwrober** [comment]
The Daily Timesheet Summary report is also impacted by this.

**Comment by netchampfaris** [comment]
Fixed via https://github.com/frappe/frappe/pull/3058
