### ISSUE TITLE
[v8] Can't find contacts in global search if their status is blank

### ISSUE THREAD

**Issue by joolsr** [frappe/erpnext#8246]
I've just upgraded to v8, wonderful ! But with the new global search, I was thinking that if I type in a name of a contact that if the contact exists then it would be shown in the results. This is not the case though.

I found that any contact that had the Status field as blank, ie was not filled in did not appear in the search results. Once I set Status to 'Passive' the contact appeared on a search. This can be fixed by exporting and importing records setting status to a value, but it should work out of the box.

I do not know if this issue may be relevant to other similar doctypes with a status field, I have not tested this.

**Comment by pratu16x7** [comment]
If I understand correctly, was setting a blank status on a contact possible by customizing the form?

**Comment by joolsr** [comment]
No it was how i imported the contacts from a spreadsheet

Julian

⁣Sent from BlueMail ​

**Comment by joolsr** [comment]
But as a usability issue users will be obviously typing in a contact or customers name in global search and will be confused if none appear .. as I was till I worked it out

Julian

⁣Sent from BlueMail ​

**Comment by pratu16x7** [comment]
Can't replicate it seems via Data import:
![screen shot 2017-04-10 at 3 07 26 pm](https://cloud.githubusercontent.com/assets/5196925/24856800/90c8e188-1e03-11e7-99b6-6723a64553bb.png)

![screen shot 2017-04-10 at 3 08 13 pm](https://cloud.githubusercontent.com/assets/5196925/24856807/95aa7252-1e03-11e7-9c4f-90c527375184.png)

**Comment by joolsr** [comment]
I think there were a couple of small fixes of Global search since my post which may have helped things here. But certainly most of my contacts did not show up as I imported as I described earlier.

**Comment by pratu16x7** [comment]
Seems likely. Let us know if it comes up again. Cheers!

**Comment by skbylife** [comment]
This issue happened to my system. Is there any solution?
