### ISSUE TITLE
General Ledger Report View By Account:  Add Opening, Closing Balance Columns

### ISSUE THREAD

**Issue by Tropicalrambler** [frappe/erpnext#8249]
Add the capacity to "Pick Columns"  in the General Ledger report, in particular, to add "Opening"  and "Closing" Balance columns.   The View "by Account"  is perfect for this kind of report for General Ledger.   The simplest way to comply with this and something like #6953 is to allow the user to "select"  columns to be shown.

**Comment by SonaliBudhrani** [comment]
+1

**Comment by jk2081** [comment]
+1

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.
