### ISSUE TITLE
General Ledger Report Group By Voucher [BUG/ ENHANCEMENT]

### ISSUE THREAD

**Issue by Tropicalrambler** [frappe/erpnext#8250]
The General Ledger report has two Grouping Settings. 

1. Group By Account

1. Group By Voucher

 In the Group by Account view, it groups transactions with the same accounts, and then totalizes the data, and leaves a line or two empty before the next group begins. 

In the Group by Voucher view, it does not group the transactions per voucher or per "journal entry" with the accounts affected by that particular Journal Entry, or payment entry.  

The desired functionality is that when grouping by voucher, the journal or payment entries are listed chronologically, ascending or descending by date for the selected period. With each grouping totalizing and then a total of all the movements at the end of the whole report. (At the bottom)

Our accountant wishes to print the report in one swift stroke, even if it prints on 200 sheets of paper, as per the requirements of our local tax entity.

**Comment by PawanMeh** [comment]
Could you explain with a screen shot?
