### ISSUE TITLE
Save a customizable General Ledger Report

### ISSUE THREAD

**Issue by Tropicalrambler** [frappe/erpnext#8251]
Enable a feature to save the configuration of a General Ledger Script Report, for frequent use.

**Comment by SonaliBudhrani** [comment]
Even we need this. If we can customise General Ledger report or what columns or fields to be printed in General Ledger Report, it would be great.

**Comment by tundebabzy** [comment]
Implemented in #12969

**Comment by hashimea** [comment]
This is an essential need.

**Comment by harshit-30** [comment]
You can add columns, apply filters over the report and then save it as a different report for further use.

**Comment by reubenromandy** [comment]
[#](https://github.com/frappe/erpnext/issues/8251#issuecomment-971708591)

This is not true of the general ledger report... at least not in version 13.  
When I save the report under a new name only columns are saved, filters are lost. 
I'd like to request for this issue to be reopened. It would be really nice to be able to save a filter with multiple account names chosen in the General Ledger report.
