### ISSUE TITLE
Balance Sheet Period Monthly/Quarterly/Half-Yearly Period Range

### ISSUE THREAD

**Issue by Tropicalrambler** [frappe/erpnext#8252]
Allow for the Balance Sheet Report Monthly/Quarterly/Half-Yearly period range to be selected, so that if you wish to show monthly for only two months, you select a start date and an end date, and it displays only those months.  Same for the printable report.

**Comment by jwrober** [comment]
+1, I would also like to see an option to show the same period from a year ago side by side to be able to compare pro-forma results

**Comment by PawanMeh** [comment]
![screen shot 2017-04-29 at 5 50 24 pm](https://cloud.githubusercontent.com/assets/20460498/25555436/5e4a41b0-2d04-11e7-9fe6-702c421d96bc.png)

This option exists now, closing this.
