### ISSUE TITLE
Make Manufacturer Part No a Link field

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#8257]
We have updated the Manufacturer to be a DocType so we can reference it. We missed that the Manufacturer Part No should also be a DocType so it can be referenced from various DocTypes, not only from item. The Manufacturer Part No is actually where we ourselves hold a lot of information which we will add in custom fields but we believe it would be beneficial to make it a DocType for everyone, or at least we don't see disatvantages.

- [ ] Make ``Manufacturer Part No`` a DocType with fields: Manufacturer (Link, Mandatory, In List View), Manufacturer Part No (Data, Mandatory, In List View) , Status (Select: Active [default], Obsolete, Disabled), Device Package Code (Link, Optional)
- [ ] Change field type of ``Manufacturer Part No`` in ``Item`` from Data to Link
- [ ] Write Patch that will create all the Manufacturer Part No entries and update the field

**Comment by dottenbr** [comment]
I have another request for the Manufacturer Part No Status (In Qualification) is also needed

**Comment by kickapoo** [comment]
@rmehta There do we stand on this one ?
