### ISSUE TITLE
Add Package Code Alias

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#8260]
We have package codes e.g. ``SO8`` but sometimes customers or suppliers write them a bit differently like ``SO-8`` or they call it ``SOIC8`` or ``SOIC-8``. For this we need to be able to add ``Package Code Alias`` as a child table in ``Package Code``.

Please make sure that when you create a new ``Package Code`` it is checked if there is an alias already to prevent adding a ``Package Code`` that is listed as an alias and please when adding package code show the aliases and make them searchable so we find the right package code.

**Comment by kickapoo** [comment]
refactoring this issue

- Create child Table `Package Code Alias` with fields `alias_code`
- Add child table to `Package Code`
- Add custom validate function on `Package Code`, `validate_alias_name`: If new Package Code exists throw error message `Package Code is already an alias for <Package Code>`
- In `Item` make `Device Package Code` field to show alias (?) in Package Code link field select
- In `Item` make  `Device Package Code` to be searchable by `Package Code Alias` also.

@dottenbr  please validate if its correct.

@nabinhait @rmehta the last 2 points need your help on how to do it.

**Comment by rmehta** [comment]
Is `Package Code` part of the standard yet?

**Comment by kickapoo** [comment]
yeap its on standard

**Comment by rmehta** [comment]
How is this linked to the workflow. Where is the documentation?

CC @nabinhait

**Comment by kickapoo** [comment]
Please update @nabinhait , where do we stand ?

**Comment by kickapoo** [comment]
@nabinhait any update on this ? please check the namespace of the variables etc so I can start it.
