### ISSUE TITLE
[minor] [ui] App Installer "installed" button

### ISSUE THREAD

**Issue by ratskin** [frappe/erpnext#8265]
In the App Installer the "installed" button is in the wrong position and the installed label (?) is also in the wrong position. See screen shots.
![screen shot 2017-03-31 at 11 58 39 am](https://cloud.githubusercontent.com/assets/24547185/24545901/68f6159c-1609-11e7-829a-1276b9c96fbc.png)
![screen shot 2017-03-31 at 11 58 27 am](https://cloud.githubusercontent.com/assets/24547185/24545902/68f6782a-1609-11e7-97d7-f06105cbbcc8.png)

**Comment by chdecultot** [comment]
Hi @ratskin,

The "installed" checkbox is meant to be a filter. If you click on it it will show you all applications already installed on your system.

Then you can choose to remove them or select another application and click on the "install" button on the right to install it.

Can you be more specific about the "right position" you think this button should have ?

**Comment by kennethsequeira** [comment]
App installer working as intended. Button position seems fine.

The installer has been deprecated since v11.

![app-installed](https://user-images.githubusercontent.com/33246109/56413828-63cd4180-62a6-11e9-8ae9-99ead1b08c8a.gif)
