### ISSUE TITLE
[v8] Duplicated tax_id

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#8267]
Hello,

I created before the update a field called tax_id to be filled with "add fetch", now that this is a feature the field is duplicated, so I cant personalize the form because it gives an error, I cant delete the field because the same error.

Any ideas?

**Comment by nabinhait** [comment]
I think you need to delete the Custom Field. If it has same field name, the values will be automatically reflect in the new standard field.

**Comment by applepipe** [comment]
How can I delete the field? It gives an error saying that I have duplicated fields.

**Comment by nabinhait** [comment]
How are you deleting the Custom Field?

**Comment by applepipe** [comment]
hello @nabinhait I go to personalize form and try to delete the field, the scrrenshot is in this topic:

https://discuss.erpnext.com/t/cannot-delete-duplicated-field-tax-id/22162/3

I cant personalize the form because this error prevents any modification

**Comment by applepipe** [comment]
Tried to look into "TabCustom Field" but cannot find the field to delete, maybe it only shows on personalize form, because the right field created by the last update is Tax Id and my field is named Tax ID. This is is blocking me to do any modifications

**Comment by applepipe** [comment]
solution: https://discuss.erpnext.com/t/version-8-upgrade-error-tax-id/22001/8?u=applepipe
