### ISSUE TITLE
Projects - Duplicated project loses task dependencies 

### ISSUE THREAD

**Issue by mineolatx** [frappe/erpnext#8274]
Duplicated project loses task dependencies
Trying to make a project template so I can just duplicate it for the next one and only have to change dates in the new one.
Why are the dependencies not being copied along with everything else? See screen caps below.
This is a new install from 4 days ago.
ERPNext: v8.0.0-beta (develop)
Frappe Framework: v8.0.0-beta (develop)

![test_project_2](https://cloud.githubusercontent.com/assets/18650730/24564805/e78d4a4c-1618-11e7-81d4-2b2b6495c17f.jpg)
![test_project_3](https://cloud.githubusercontent.com/assets/18650730/24564804/e78cacb8-1618-11e7-97c8-65f02f2c9415.jpg)

**Comment by mineolatx** [comment]
Is this something that has never worked or is this just in version 8? 
Just wondering since no one has commented on it.

**Comment by mineolatx** [comment]
@nabinhait 
Is this something that is going to be fixed soon? If not then I need to use another program for this but I would rather do it in ERPNext. Time has become a factor for me at this point.

**Comment by mineolatx** [comment]
Having other problems in the project gantt chart window also. 

When you move a task in the gantt chart then you see the 'saved' box pop up in the bottom right corner. If you hit the refresh button the task has moved but it has an extra day added to it.

**Comment by mineolatx** [comment]
@nabinhait This has been added to the developer version if I understand correctly. Can you tell me when it will be part of the Master version?

**Comment by nabinhait** [comment]
The fix has already been released.

**Comment by mineolatx** [comment]
Thanks!
