### ISSUE TITLE
V8 % wildcard Not working in Editable Grids 

### ISSUE THREAD

**Issue by RandyLowery** [frappe/erpnext#8275]
As described here https://discuss.erpnext.com/t/mising-for-seacrhing-links-v8/22000

**Comment by RandyLowery** [comment]
As described here https://discuss.erpnext.com/t/mising-for-seacrhing-links-v8/22000

**Comment by netchampfaris** [comment]
Link field is powerful enough to search the query in the whole text.
<img src="https://discuss.erpnext.com/uploads/default/optimized/2X/3/3fcf1245896ee960c79fc710ecfbe909e6da039b_1_690x415.png" />

You don't need wildcards.

**Comment by maxtorete** [comment]
How could I search for two non consecutive words?

For example, in V7, I could search "bar%5kg" and the grid field shown me all the bars of 5kg, even if they were named "Barbell bar Black Oxide 5kg" or "Barbell bar technique 5kg".

In V8, I have to open the advanced search, that is less than ideal when you have to add more than 50 lines to a quotation.

V7 behaviour was far better than V8 for link fields.
