### ISSUE TITLE
Reset Accounting Transactions and post fresh opening balances

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#8276]
When a user has not fully setup accounting and then wants to move accounting to ERPNext, there should be a way to reset all transactions as the user to post fresh opening balances

Easy way would be to add a flag "Non Accounting Transaction" on all accounting transactions before a particular date in the past to tag that these will not be posted again

**Comment by Jaliya** [comment]
I hope this will be valid for Stocks as well enabling entry of opening stock balances manually.

**Comment by Jaliya** [comment]
Hope you are working on this. Is it ok to feed trade debtors invoices which were raised in the last financial year, before you implement the proposed changes regarding opening balances.
