### ISSUE TITLE
AWESOME BAR SEARCH CANT FIND RESOURCE with translated links and doctype

### ISSUE THREAD

**Issue by RandyLowery** [frappe/erpnext#8279]
Search in awesome bar is giving me error while the user is in other language than english, spanish in my case. As all doctype and link menus gets translated the program report that the resource you are looking for is not avaible.

![untitled](https://cloud.githubusercontent.com/assets/20528130/24578753/8cc59d30-16d6-11e7-8116-7b02ee1f8119.png)

**Comment by jiangangwu** [comment]
I think it will be much better that awesome bar can support two languages.

Can anybody solve this problem?
