### ISSUE TITLE
Unwanted [object Object] printed for General Ledger report printing /PDF output

### ISSUE THREAD

**Issue by jaywks** [frappe/erpnext#8280]
v8.0.5

Whenever printing or generating PDF output for general ledger, and extra line "[object Object]" gets printed underneath letterhead, regardless if its set to include/exclude letterhead.
Screenshot:-
<img width="577" alt="screen shot 2017-04-02 at 8 29 15 am" src="https://cloud.githubusercontent.com/assets/16625441/24584428/f39ddac4-177e-11e7-8a1b-fb5a1c7913db.png">

**Comment by rohitwaghchaure** [comment]
Hi @jaywks 

Working properly 

![letterhead](https://cloud.githubusercontent.com/assets/8780500/24908748/dbcb90be-1ede-11e7-8964-7d716115691a.gif)

**Comment by rmehta** [comment]
@jaywks can you re-check your letter head? We cannot replicate this
