### ISSUE TITLE
Nested tasks

### ISSUE THREAD

**Issue by janmoravecfw** [frappe/erpnext#8282]
Hi, 

please, is it possible to create "multi-layer tasks"? I mean in project I have 5 main tasks and after creating it I can make new task under the one of the main task. I know, that tasks can be set to "depend on", but I would like to have a similar choice of work like in Asana.

Thank you very much.

**Comment by PawanMeh** [comment]
Hierarchy of task does not exist currently. It may need major UI changes too.

**Comment by almeidapaulopt** [comment]
"Depend on" is a different concept is a task that depend of other tasks to be done.
I also liked to see in erpnext Nested Tasks/ Group tasks. In a medium/big project the group tasks is a "must have" unless is too difficult to manage.

**Comment by asbasawaraj** [comment]
@janmoravecfw Now we have this feature... 
![screen shot 2019-02-06 at 10 46 50 am](https://user-images.githubusercontent.com/11595602/52321813-9d5b1400-29fc-11e9-81bb-e79b058d16a6.png)
