### ISSUE TITLE
[Enhancement Request] Document Date or Posting Date in List View

### ISSUE THREAD

**Issue by azharumar** [frappe/erpnext#8283]
From an accounts user perspective, it will be really helpful to have date column in all the list views. Especially in:

- Sales Order
- Quotations
- Invoice
- Purchase Invoice
- Purchase Order
- Purchase Receipt
- Payment Entry

![image 177](https://cloud.githubusercontent.com/assets/19702561/24592615/3499fb30-1837-11e7-868c-d1ed0652ef3f.png)

Almost every other ERP or Accounting Packages have dates in it. Amount and Date are two key ingredients of accountancy. Without the date, it would be really difficult to open each document and check its date.

I am attaching a screenshot from Zoho Books and Odoo ERP.

![image 178](https://cloud.githubusercontent.com/assets/19702561/24592618/3d71201c-1837-11e7-9445-4dfb15e41b27.png)
![image 179](https://cloud.githubusercontent.com/assets/19702561/24592619/3d7dba34-1837-11e7-8ba5-f12946f93014.jpg)

**Comment by tundebabzy** [comment]
I have added posting/transaction date to the list view for the documents. I will work on the frappe part so that the date would be the first column
