### ISSUE TITLE
[Enhancement Request] Date in Unreconciled Payment Details (in Match Payments with Invoices)

### ISSUE THREAD

**Issue by azharumar** [frappe/erpnext#8284]
I had posted an issue related to dates in List Views. I feel it is an important aspect in here too:

![image 179](https://cloud.githubusercontent.com/assets/19702561/24592665/16acccbe-1838-11e7-9496-0d1b84de2067.png)

However, it is there in the list showing invoices just below this table.

I understand the restriction for column width due to bootstrap. But I really think this is very key element when dealing with volume data. Otherwise opening up each payment entry to find the date is difficult.

The date can also be added here, Here there should be lot more information available relating to the document. Maybe Cheque Reference Number etc.

![image 180](https://cloud.githubusercontent.com/assets/19702561/24592715/c6917fb2-1838-11e7-88c7-5cdd8fac8839.png)

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.
