### ISSUE TITLE
Search Bar Not Working Occassionally

### ISSUE THREAD

**Issue by azharumar** [frappe/erpnext#8285]
The search bar seems to be not working at times. Please find the attached screenshot where no drop down has come even after typing into the search bar.

But it works at times.

![image 181](https://cloud.githubusercontent.com/assets/19702561/24592742/4b53f928-1839-11e7-9f0e-1a24fb4df86b.png)

**Comment by pratu16x7** [comment]
Can you post a screenshot of the browser console when this happens?
