### ISSUE TITLE
[Enhancement Request] Customer Purchase Order Number in Sales Invoices

### ISSUE THREAD

**Issue by azharumar** [frappe/erpnext#8286]
Customer Purchase Order is nowadays a standard item on all invoices. I understand, this can be configured by editing the docs.But this will be a good add-on if its available out of the box. Or at least a field which can be selected at the time of Customizing Invoices.

**Comment by adityaduggal** [comment]
@azharumar You can create a custom field for Purchase order number in SO, DN and SI and hence it can be easily accompolished
I think this should be a posted on forums since it can be resolved at user end by using custom fields.

**Comment by kennethsequeira** [comment]
Customer Purchase Order already present.
