### ISSUE TITLE
Employee Attendance Tool UI error

### ISSUE THREAD

**Issue by almeidapaulopt** [frappe/erpnext#8291]
Employee list disappear if Department field left empty instead of listing all employees.

![erpnext rh1](https://cloud.githubusercontent.com/assets/22657407/24601756/103d848a-1852-11e7-964f-7d084344ab83.gif)

**Comment by KanchanChauhan** [comment]
You will have to refresh the page to get all the employees again, once you select the Department and make it blank again, it gets the employees with Department not set.

**Comment by almeidapaulopt** [comment]
yes, that's the way I've done and it worked.
But don't you think it should list all employees like went you enter in Employee Attendance Tool ? We should minimize the need of users force refresh.

**Comment by KanchanChauhan** [comment]
Sure we will try to improve it in some way.
