### ISSUE TITLE
Daily Digest links dont get followed through

### ISSUE THREAD

**Issue by joolsr** [frappe/erpnext#8293]
Using v8.0.4

**Issue**
Link from Daily /Weekly Digest email takes you to incorrect destination unless already logged in.

**To Recreate** 

When you receive one of the automated 'Daily or Weekly Digest' emails click a link on one of the items. If not logged in you then need to login. But once logged in, instead of expecting to be taken automatically to the item, instead you are taken to the Desk. Clicking the link again from the email when logged in now takes you to the correct location and item.

**Comment by joolsr** [comment]
this is a duplicate of this earlier issue [https://github.com/frappe/frappe/issues/2567]

**Comment by rmehta** [comment]
This is fixed.

**Comment by joolsr** [comment]
great ! Many thanks ;-)
