### ISSUE TITLE
Add margins to Quotation, Sales Order and Invoice

### ISSUE THREAD

**Issue by somicoito** [frappe/erpnext#8298]
We would like to see our margins on:
Quotation and Quotation Item
Sales Order and Sales Order Item
Sales Invoice and Sales Invoice Item

Here is just an example made on Sales Order Item and on Sales Order of what we would like to have.
![personalizzazione-costi_1](https://cloud.githubusercontent.com/assets/26325987/24631221/d6a23784-18bf-11e7-92a8-f0f3b5fb0ea9.jpg)
![personalizzazione-costi_2](https://cloud.githubusercontent.com/assets/26325987/24631259/f5790660-18bf-11e7-93b4-6d3bdd93f061.jpg)

**Comment by rmehta** [comment]
Margin is already added in the latest.
