### ISSUE TITLE
Search bar not working after upgrade to v8

### ISSUE THREAD

**Issue by akiato** [frappe/erpnext#8306]
![screenshot_20170404-153049](https://cloud.githubusercontent.com/assets/20904034/24647912/0b57c3b8-194c-11e7-88e2-060face81696.png)
After upgraded to version 8, my everytime I type something into the search bar, it shows a Not found error

**Comment by ahmadRagheb** [comment]
I have the same problem when i change the language to arabic ,, in english it works with mee
