### ISSUE TITLE
POS Profile - Mode of Payment - Make Account field User editable

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#8308]
Scenario:

One user has multiple cash accounts based on different location. Since Account field in the Mode of Payment is not selectable, default Cash Account cannot be defined for that User.

![screen shot 2017-04-04 at 2 52 04 pm](https://cloud.githubusercontent.com/assets/910238/24650002/7c01ca06-1946-11e7-9a1d-08d6954ff8dd.png)

**Comment by jay-parikh** [comment]
@umairsy Are we looking for this fix yet? If yes, i can send.
