### ISSUE TITLE
Setup Wizard Error

### ISSUE THREAD

**Issue by j209** [frappe/erpnext#8311]
Hi
I setup a fresh install on CentOS 7 and i had three problems in set up wizard.
1- It won't advance from step 3 (Domain) even though I click next
2- It would appear that the javascript in the "set financial year" is over riding any manual entry. Whatever I'm clicking on does not match the date. Here I had just navigated to 1/1/17 and got a result of 7/24/16. [Time Warp!]
3-When i finally go to the latest wizard step (by changing the numbers in url bars and clicking previous and next!!) and click finish setup i got a error message.
i am completly new in erpnext and become very disappointment.

https://discuss.erpnext.com/t/setup-wizard-time-warp/20325

**Comment by joezsweet** [comment]
On what timezone is urgent host from which are you connecting to erpnext?

**Comment by j209** [comment]
ok.thanks.my problem solved.
