### ISSUE TITLE
Project Gantt Chart - ERP locks up when filter removed from chart  

### ISSUE THREAD

**Issue by mineolatx** [frappe/erpnext#8312]
Project Gantt Chart - ERP locks up when filter removed from chart. Screen grays out and only top menu works. ERP has to be restarted from bench.

![greyed-out-1-](https://cloud.githubusercontent.com/assets/18650730/24678410/104c3f4e-1950-11e7-857b-1ce65dabc51a.jpg)
![greyed-out-2-](https://cloud.githubusercontent.com/assets/18650730/24678413/15dc3e00-1950-11e7-84bb-8b27b62ba73b.jpg)

**Comment by rmehta** [comment]
Can you share a trace?

**Comment by mineolatx** [comment]
It doesn't give me an error with the popup trace window. Also no errors in the error snapshot. The main part of the screen goes gray and all that works is the very top menu. You can logout and login but can do nothing in the ERP. You have to restart it from the bench to work again.

**Comment by mineolatx** [comment]
Duplicated the error in your online demo. If the project Gantt chart that you are in has task that have dependencies and you delete the project name filter  at the top of the chart then the screen goes gray.

![online_demo_screenshot](https://cloud.githubusercontent.com/assets/18650730/24723810/81b76f78-1a0e-11e7-92e8-d4572a8421ed.jpg)

**Comment by netchampfaris** [comment]
@mineolatx 
Cannot replicate

![apr-11-2017 12-12-12](https://cloud.githubusercontent.com/assets/9355208/24895909/3f37e2f8-1eb0-11e7-8e99-01da7d8161f0.gif)

Can you provide detailed steps to replicate the issue?

**Comment by mineolatx** [comment]
I was not able to recreate it in the online demo today. I'm guessing one of the updates has fixed it.
About to make sure we have the latest version and try it on our server.

**Comment by netchampfaris** [comment]
Closing for now.

@mineolatx 
Feel free to open this when you're able to replicate.
