### ISSUE TITLE
Use of python eval in Salary Structure 

### ISSUE THREAD

**Issue by ckosiegbu** [frappe/erpnext#8313]
Hi Team,

Is it safe to use eval in erpnext python code? I suspect it opens erpnext up to vulnerabilities. Is it an option to use a library like pyparsing instead that makes parsing of forumlas safe and tightly controls what can be done?

Something along the lines of https://pyparsing.wikispaces.com/file/view/fourFn.py looks like just what's needed to make the use of formulas in components safe.

Happy to help with this if the idea is accepted.

Regards,
cksgb

**Comment by rmehta** [comment]
@ckosiegbu thanks for reporting this. I have pushed a PR replacing the globals, so there is no access to any other objects other than those explicitly passed. Does that work?

**Comment by ckosiegbu** [comment]
@rmehta it think it's a good step but all the literature on eval points to it being really hard to secure. Also, the possibility of DOS attacks using iterative statements also presents a risk. 

See this link for possibilities https://nedbatchelder.com/blog/201206/eval_really_is_dangerous.html
I hope to make some time to mock up a pyparsing alternative soon.

Regards,
cksgb

**Comment by rmehta** [comment]
@ckosiegbu please see

https://github.com/frappe/frappe/commit/517374720f663b1341672c7123d2f3a7d7df899b

https://github.com/frappe/erpnext/commit/93656417774c8b48e1d9bc18225e1547e00982e4

Will this work till we find a better option?

**Comment by ckosiegbu** [comment]
@rmehta, yes it will do for the moment.
