### ISSUE TITLE
[v8] Server Error on Sorting List View of transactions with Creaton On Field and at the same time have an Item Code Selected

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#8314]
Hello,

This error pops up when I click on related purchase receipt:
```
> Traceback (most recent call last):
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 56, in application
>     response = frappe.handler.handle()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
>     execute_cmd(cmd)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 42, in execute_cmd
>     ret = frappe.call(method, **frappe.form_dict)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
>     return fn(*args, **newargs)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/reportview.py", line 16, in get
>     data = compress(execute(**args), args = args)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/reportview.py", line 21, in execute
>     return DatabaseQuery(doctype).execute(*args, **kwargs)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/db_query.py", line 83, in execute
>     result = self.build_and_run()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/db_query.py", line 107, in build_and_run
>     return frappe.db.sql(query, as_dict=not self.as_list, debug=self.debug, update=self.update)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 149, in sql
>     self._cursor.execute(query)
>   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
>     self.errorhandler(self, exc, value)
>   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
>     raise errorclass, errorvalue
> OperationalError: (1052, "Column 'creation' in order clause is ambiguous")
```

**Comment by rmehta** [comment]
@applepipe  please explain the steps to reproduce the error

**Comment by rmehta** [comment]
Not able to replicate, please re-open by sharing the steps of the issue

**Comment by applepipe** [comment]
It happens when I click on related purchase receipt on any purchase order.

**Comment by applepipe** [comment]
I was able to reproduce this on beta.erpnext.com

**Comment by sbkolate** [comment]
@rmehta  @applepipe 
We also have same issue.

To reproduce this, do following step.

1) Open Purchase order and sort based on Column `Created On`
<img width="1193" alt="screen shot 2017-05-01 at 6 00 46 pm" src="https://cloud.githubusercontent.com/assets/6648915/25579741/2596fb20-2e98-11e7-80c0-206148917acb.png">

2) Open any Item and click on Purchase Order

**Comment by adityaduggal** [comment]
Confirmed this issue exists on v8.0.0-beta (73af73c) (develop) beta.erpnext.com
And also exists on Frappe Framework: v8.0.31 (master)

Steps to reproduce this error:

1. Goto list view of any transaction like Sales Order, Purchase Order, Purchase receipt
1. Now change the sort order to Created On
1. Now select an item code from the item table on the filter of the List and boom

![image](https://cloud.githubusercontent.com/assets/1057509/25603525/3e3aba0e-2f1a-11e7-9522-3557675f8a6f.png)

**Comment by nabinhait** [comment]
fixed
