### ISSUE TITLE
[v8] Cant access ToDo

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#8315]
Hello,

After last update I am not able to view my ToDos, here is what the console shows

<img width="1675" alt="screen shot 2017-04-04 at 9 04 34 pm" src="https://cloud.githubusercontent.com/assets/18335894/24684265/17aefb52-197b-11e7-953a-3a4689f02e1a.png">

**Comment by rmehta** [comment]
Can't replicate, please update and try again. Re-open if the issue persists.

**Comment by applepipe** [comment]
Updated and the same error persists, I just go to tools > ToDo and the screen becomes grey

I'm using developer branch for testing
