### ISSUE TITLE
Cannot create variants

### ISSUE THREAD

**Issue by KimmyY** [frappe/erpnext#8318]
I cannot create variants since today.
Please kindly help.
Thank you very much.

Our verison details is as below.
Installed Apps

ERPNext: v8.0.0-beta (develop)

Frappe Framework: v8.0.0-beta (develop)

**Comment by rmehta** [comment]
Please share an error report or screenshot

**Comment by KimmyY** [comment]
Hi rmehta,

There is no error report.
It just have no effect when I clicked "Make variants" under a Template item. This was what we did when creating variants before.

**Comment by rmehta** [comment]
Works for me. Please share your version and the trace from your JS console. Also run bench update and check again.
