### ISSUE TITLE
Updating Value in Variants based on Template

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#8319]
When value is updated in the certain field of Template item, then in the variants item, value should be updated for that specific field only, and not all the fields of Template Item should be updated in the variant item. To learn more about it's use case, please refer to Issue WN-SUP24019

**Comment by adityaduggal** [comment]
This issue is somewhat related to #4253

**Comment by umairsy** [comment]
Duplicate issue. Refer to #4253 for the original issue.
