### ISSUE TITLE
[v8] POS Batch Qty not reducing

### ISSUE THREAD

**Issue by aambernath** [frappe/erpnext#8339]
I have tried this in 2 new V8 instances. The POS module isn't reducing the batch based qty in the system. The sales invoice generated do not have batch selected after sync.

**Comment by rohitwaghchaure** [comment]
hi @aambernath 
I have checked on local account and it's working properly.
It seems that you have not enabled **Update Stock** option in the POS profile, by default update stock is disabled.

**Comment by aambernath** [comment]
ah your right. ty
