### ISSUE TITLE
Doctype Label for Program and Course

### ISSUE THREAD

**Issue by nabinhait** [frappe/erpnext#8341]
Program -> Standard
Course -> Subject

**Comment by jwrober** [comment]
I don't get the purpose of changing these school module doctypes. The names as existing make sense, the proposed ones do not - especially Program -> Standard. Schools offer degree programs (especially universities), not "standards".

**Comment by jwrober** [comment]
@nabinhait - mind answering my questions? Not sure what is the big picture purpose of the doctype name change.
