### ISSUE TITLE
Add more Contact fields like (Title /  Gender)

### ISSUE THREAD

**Issue by kickapoo** [frappe/erpnext#8343]
In many cases like print format, email the following fields are needed:

- Title: A custom data field where user can enter values like Mr. / Dr. / Prof. (Before first_name)
- Gender: A select field with option Male / Female (After email)

**Comment by kickapoo** [comment]
@nabinhait  Please validate/provide:
 - Proposed Field name are ok ? Yes/No
 - The documentation filepath that needs to update for this addition
 -  Are UnitTest needed in this case?

**Comment by ishanloya** [comment]
https://github.com/frappe/erpnext/issues/8145

**Comment by ishanloya** [comment]
https://github.com/frappe/erpnext/issues/8143

**Comment by kickapoo** [comment]
@nabinhait Please check this one.

**Comment by KanchanChauhan** [comment]
@kickapoo Already done, see PR https://github.com/frappe/erpnext/pull/8351 and https://github.com/frappe/frappe/pull/3026

**Comment by me2ne** [comment]
better to add some extra email ad field , some contact have two email address

**Comment by dottenbr** [comment]
great, looking forward to the merge so we can update our contacts
