### ISSUE TITLE
Kanban Disapear

### ISSUE THREAD

**Issue by almeidapaulopt** [frappe/erpnext#8352]
please reopen issue https://github.com/frappe/erpnext/issues/8236 . I've upgraded to v8.0.8 and Kanban still not rendered exactly the same way as showed in https://github.com/frappe/erpnext/issues/8236

**Comment by PawanMeh** [comment]
Tried this, it appears the kanban board loads up only on Reload (workaround)

**Comment by rmehta** [comment]
fixed now.
