### ISSUE TITLE
Duplicate Results in List View since V8

### ISSUE THREAD

**Issue by RandyLowery** [frappe/erpnext#8353]
V 8.08, this happens to me in any doctype like sales invoice , sales order, stock entry where sarching for a field inside a child table from the any parent doctype mentioned above. for example in one sales invoice i have 3 items which unit of mesasure is Kg so searching from UOM inside (sales invoice Item) will result in the sames sales invoice repeated 3 times in list view.

This happens to any field, custom or standar, and also in demo.erpnext.com

![error](https://cloud.githubusercontent.com/assets/20528130/24763107/500015a4-1ae8-11e7-9617-7814f5692c3f.png)

**Comment by talitaMangolin** [comment]
Hi, would you have an update on this duplication problem for version 13?
There is no 'filter.renderer' folder, and it is happening in the customer portal
