### ISSUE TITLE
Date field type decrease by one day when open form

### ISSUE THREAD

**Issue by sys3tecnologia** [frappe/erpnext#8358]
During the process to create a material request, when you set the item schedule date as of today and save it, after you open the details again the schedule date is reduced by one day (every time you open the form detail, the same date is reduced by one day)
It happens every time that you try to insert one new material request, and after you open the details you're not able to save it once the date schedule date is smaller than the request date.

**Comment by mbauskar** [comment]
@sys3tecnologia,

Is there any custom script added on Material Request? I am not able to replicate the issue

**Comment by sys3tecnologia** [comment]
In demo.erpnext.com make a new request material, include one item, set schedule date for this item and save. After open item details (item form details) and see this bug (decrease date).

**Comment by mbauskar** [comment]
fixed via https://github.com/frappe/frappe/commit/41fc67efdd501287fdb9cf45287bab01bd50521a
