### ISSUE TITLE
Fixed components in salary slip

### ISSUE THREAD

**Issue by ishanloya** [frappe/erpnext#8363]
Hi,

If I have a salary component that is fixed i.e. does not depend on LWP (e.g. Professional Tax), when I process payroll for a month, it ignores LWP as expected. But if an employee leaves in the middle of the month, then the Component also get calculated based on the number of working days. Is this a bug?

Thanks

**Comment by KanchanChauhan** [comment]
I think this is the default behavior.

**Comment by ishanloya** [comment]
Thanks for your reply Kanchan. 

In the case of Professional Tax, the amount needs to be fixed (@200, for e.g.) irrespective of the number of days worked in the month. How would I change this amount on the salary slip, since I cannot change it manually if the salary slip was created from a salary structure?

**Comment by PawanMeh** [comment]
You can handle the scenario using a formula i think. If any further queries, please post on [discuss](discuss.erpnext.com)
