### ISSUE TITLE
[developer branch] Cant access desk

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#8368]
Hello,

After the last update I'm not able to see the desk after login, it is stuck with the "E" image on the center.

This is the error on the javascript console

<img width="1677" alt="screen shot 2017-04-07 at 10 16 28 am" src="https://cloud.githubusercontent.com/assets/18335894/24801665/97d55ed2-1b7b-11e7-8200-4ea27127e2a0.png">

**Comment by rmehta** [comment]
Cannot replicate can you do Shift + Ctrl + R and recheck.

**Comment by applepipe** [comment]
Already fixed in update, but it was the first thing I've tried. Got it working executing bench watch, after seeing this topic https://discuss.erpnext.com/t/erp-showing-only-e-logo/22337

**Comment by Fauzdar1** [comment]
Not at all fixed, I've been facing this issue without any solution so far. I'm already on the latest version and I've reinstalled ERPNext and the whole server 3 times so far, it works only for first login and stops working after.
Same issues as yours.

[ERPNext Desk stuck at Logo in Production](https://discuss.erpnext.com/t/erpnext-desk-stuck-at-logo-in-production/81143)

**Comment by ankush** [comment]
> Not at all fixed

This is totally unrelated, there are thousands of users using it right now! 😄 

Just try `bench build` to rebuild assets if they're broken for whatever reason.

**Comment by Fauzdar1** [comment]
`bench build` does nothing, I've already mentioned that in the thread, it is not _totally unrelated_ if I'm getting  the exact same errors. 

And most importantly, no one has provided any working solution for this issue listed by many users.

**Comment by ankush** [comment]
It's unrelated because the desk code has changed A LOT in the last 5 years. The problem you're having is broken client-side assets.  Only "symptoms" are the same.

**Comment by ekariz** [comment]
still have the same issue with a new bench  5.17.2 install and frappe 14
