### ISSUE TITLE
Why downloading Item template with Brand data and uploading again does not find Brands.

### ISSUE THREAD

**Issue by Herbert6917** [frappe/erpnext#8372]
I downloaded Item template with only mandatory columns and data which included Brand data for all items and then I uploaded the data to change stocked status but these errors occurred for all items.  Error for row (#21) "MIT1" : {"message": "Could not find Brand: ZIMMERMAN, E.E CO. - 638", "indicator": "red"}

Error for row (#22) "MILOR1" : {"message": "Could not find Brand: ZIMMERMAN, E.E CO. - 638", "indicator": "red"}

Error for row (#23) "MILOR4" : {"message": "Could not find Brand: ZIMMERMAN, E.E CO. - 638", "indicator": "red"}

Error for row (#24) "G9049" : {"message": "Could not find Brand: WORLD AND MAIN (GAM PRODU - 330", "indicator": "red"}

Error for row (#25) "GAL CAN" : {"message": "Could not find Brand: WORLD AND MAIN (GAM PRODU - 330", "indicator": "red"}

Error for row (#26) "GBA-30502" : {"message": "Could not find Brand: WORLD AND MAIN (GAM PRODU - 330", "indicator": "red"} 
I am using the Desk version from the ErpNext website version 7... These brands were uploaded just as they were downloaded so why doesn't it find them? This is the file it tried to upload. I have tried many times with new files.
[test1.xlsx](https://github.com/frappe/erpnext/files/906757/test1.xlsx)
Thank you

**Comment by Herbert6917** [comment]
More information about this problem.  When I try to modify a Brand manually either in an item master or the Brand master the program will freeze or ask to issue a report which I did about 3 days ago.  Is there a corrupt data file or a bug?

**Comment by PawanMeh** [comment]
Could you check if you have set up the brand in your master? 

![screen shot 2017-04-29 at 5 39 34 pm](https://cloud.githubusercontent.com/assets/20460498/25555380/f7ecd384-2d02-11e7-8120-a3a0aed569e3.png)

**Comment by Herbert6917** [comment]
Hi I had to move on.  Thank you for trying.
