### ISSUE TITLE
right to left support

### ISSUE THREAD

**Issue by j209** [frappe/erpnext#8374]
hi.
When do you implement rtl for cultures like Arabic or Hebr?

**Comment by me2ne** [comment]
when there is sone sponsor can help to do it or pay for that . my sugestion make full details about RTL and what do you think needed , help in bounty source and let's other people need RTL also help in bountysource .

**Comment by strixaluco** [comment]
@j209, this has been already discussed on the forum: https://discuss.erpnext.com/t/rtl-support-in-future-plans/3644

In short: RTL support is unlikely to appear in Frappe before Bootstrap adds support for it, which they plan to do somewhere [around v4.1 or v4.2](https://github.com/twbs/bootstrap/issues/19545#issuecomment-196990781)

**Comment by strixaluco** [comment]
In fact, support for RTL has been merged into develop branch of Frappe: https://github.com/frappe/frappe/pull/2501
@j209 , did you check it?

**Comment by rmehta** [comment]
yes @dalwadani has already made some contributions. Please raise specific issues.
