### ISSUE TITLE
Customer role missing in ver 8.08 setup/user/company user

### ISSUE THREAD

**Issue by imllc** [frappe/erpnext#8390]
as detalied in this post:
setup/Role has customer and is enabled
setup/User does not have customer as an option
user linked to company in selling/contact and is primary contact
setup/Role has customer and is enabled
setup/User does not have customer as an option
user linked to company in selling/contact and is primary contact
https://discuss.erpnext.com/t/what-happened-to-customer-role-under-setup-user-username-settings/22222?u=imllc

**Comment by rohitwaghchaure** [comment]
Kindly enable desk view for customer role
![screen shot 2017-04-11 at 6 05 01 pm](https://cloud.githubusercontent.com/assets/8780500/24909461/9f7b83c8-1ee1-11e7-8423-67493c0b5c63.png)

**Comment by imllc** [comment]
why was this closed before a response from me? This did not fix the probelm upon enabling this which i had done before i post the customer check box is still unavailible in roles.

**Comment by rohitwaghchaure** [comment]
Hi @imllc 

I am not able to replicate the issue therefore have closed the issue, but don't worry you have completely rights to reopen it. If possible can you please share the GIF or screenshots?

![screen shot 2017-04-12 at 3 12 51 pm](https://cloud.githubusercontent.com/assets/8780500/24951611/a28d77b8-1f92-11e7-9eb4-905b59bbca9e.png)

**Comment by imllc** [comment]
screen shot already included at top of the post:
https://discuss.erpnext.com/t/what-happened-to-customer-role-under-setup-user-username-settings/22222?u=imllc

**Comment by imllc** [comment]
ok something has changed as of 8.10 customer is now availble but why does customer have access to these 9 desk items File manager, HR,Explore, Learn and manufaturing should not be there for a customer by default:

![3](https://cloud.githubusercontent.com/assets/22771472/24968244/ab11f2a0-1f7a-11e7-9b11-4d727c71af5c.PNG)

**Comment by imllc** [comment]
customer role should not have this by default:

![4](https://cloud.githubusercontent.com/assets/22771472/24982805/67c7d67c-1fb1-11e7-96e0-1f194b9f4ee9.PNG)

**Comment by rmehta** [comment]
@imllc the use case for customer is the portal view, lots of documents like "Print Heading" have all access, the same reason we have a separate interface for admin and non-admin users. Lets not try and mix these.
