### ISSUE TITLE
Item tax not applied correctly ver 8.08

### ISSUE THREAD

**Issue by imllc** [frappe/erpnext#8391]
Installed Apps

ERPNext: v8.0.8 (master)

Frappe Framework: v8.0.7 (master)

i went through and recreated this several times. on the quotation under taxes and chargers if you have a tax listed that has 0 rate then tax break out shows 0 rate on all items. however if you have a tax listed that has a rate of 8.0 you will see tax applied to the non taxible item. Change the 8 in the rate of the quote to 0 and then the item tax does what it should and calculates taxes and the non taxed item. we should not have make this change so i believe its a bug.

**Comment by rohitwaghchaure** [comment]
Hi @imllc 
I have checked and It's working fine
If item master has tax rate, system always pickup the rates from the master and calculate the taxes even if user has set the tax rate in the quotation. 

![screen shot 2017-04-11 at 3 51 29 pm](https://cloud.githubusercontent.com/assets/8780500/24904665/cc320a08-1ece-11e7-8d58-05c6f6d29d02.png)

In above example, item **HP APU Quad Core A8** has tax rate 10 and **Moto G** has no rate on the master. User has set the tax rate 2.0 in the quotation,  which has been applied on the MOTO G only

**Comment by imllc** [comment]
that is not what we are seeing we have duplicated this several times...

**Comment by rmehta** [comment]
@imllc can you share screenshots?

**Comment by imllc** [comment]
The default is 8.625% on items and o on service as you can see it doesnt apply correctly until o zero out the 8.625%  this is ripe for people forgeting to change it and should happen automatically.
![1](https://cloud.githubusercontent.com/assets/22771472/24968003/d1c349fe-1f79-11e7-998f-496360a55568.PNG)

![2](https://cloud.githubusercontent.com/assets/22771472/24968066/074cb7fe-1f7a-11e7-9ecd-a8cf130c57a2.PNG)

**Comment by imllc** [comment]
i have applied ERPNext: v8.0.13 (master) Frappe Framework: v8.0.18 (master) This still appears to be a problem...

**Comment by rmehta** [comment]
@imllc what are your tax rates in the Item Master?

You have to set ITECHE item to 0 in the Item master (as it is non default)

**Comment by imllc** [comment]
It is set this way to zero and it does not work as documented this only works if after you go into quotation and change the default to zero this is not a good way to do it as employees will forget so this is still a bug.



[http://imerecom.net/wp-content/uploads/2017/01/logoem.png]
