### ISSUE TITLE
Batch-wise Storage, Stock Movement and Consumption

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#8393]
At our company we have the situation that we receive, store and consume items by batch. This is important for 100% traceability but also for stockkeeping. 

We manufacture electronics and these components arrive on reels, sticks or trays. For us each of these reels etc. are called a carrier or in the ERPNext world we think this would be a batch. So of a component we may have 10 full reels of 4.000 pieces each = 40.000 pieces and 2 half consumed reels of lets say 2.300 and 1.700 which makes it a total quantity of 44.000 in 12 reels (batcheS)

Our customers need reports from us on what components we used for their production order, where the components came from and what the datecode etc. of those components was from the manufacturer. This is only possible by splitting the items into batches and by tracing their use. The components come on reels, cut tapes or sticks anyways.

Also stockkeeping is quite tricky for us. We sometimes have millions of components of one item in stock. But its not like they are lying around somewhere ready to count. The are always moved as a batch (reel, stick, cut tape) and consumed from. So we have maybe dozens of reels (batches) of one component. When we count our inventory we don't ever count them as a whole but instead we always count the individual batches that make up the whole stock quantity.

These ```batches``` have certain functionality:

1. We take pictures of each batch (reel, stick or tray) as they arrive to document them. This helps us trace errors when suppliers deliver something that was mislabeled or sent with faulty parts. 

2. We print barcode labels per batch that have information like who delivered it, when it was delivered etc. with these labels we can identify the batch and its origin at any given point in the company.

3. We store those batches in a certain warehouse, when we move items we move whole batches and we dont rip them apart (if we do need to move only a partial quantity we split a batch in which case we create two new batches from one parent). This means stock movement must always move whole batches, when we sell an item we only sell full batches or again split them.

4. When we consume from these batches we need to know in the production order what batch we consumed from.

## Purchase Receipt
- [ ] Show Purchase Order (if supplier selected filter purchase order only to that supplier, if purchase order put in first update supplier)
- [ ] Show Delivery Note Number
- [ ] Load information from Purchase Order of Booked, Unbooked and Already Booked (in other purchase receipt)
- [ ] Add "Quick find" input box that allows scanning with barcode reader of any information of purchase order line such as ```Item code```, ```Supplier Part Number```, ```Manufacturer Part Number``` also partial strings should be allowed
- [ ] If item ```has batch``` we need to be able to quickly create multiple batches per purchase order line, these batch numbers must be automatically generated (eventual batch information may be stored in them)

## Batch
- [ ] Store what ```Purchase Receipt``` a batch was created from
- [ ] Add buton ```Discard``` which creates material entry of type ```Discard``` and sets status to discarded to elminiate stock. Discard should be scrapped in accounting.
- [ ] Add button ```Split``` which splits quantity e.g. 30 into 15 and 15 pieces and creates two new batches from this split which have the information of the parent batch. Make proper warehouse entries.
- [ ] Add button ```Batch Move``` which moves the warehouse of the batch (whole quantity only)
- [ ] Show every batch move in Comment

**Comment by SOLOSOFTMA** [comment]
+1

**Comment by joshreeder** [comment]
+1 Any idea of when this will make it in or if it needs to be funded?

**Comment by uzbek14** [comment]
+1 Are there any news?
