### ISSUE TITLE
Minimum Line and Order Values and Shipping Cost

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#8397]
In Supplier we need the following information which will have an effect on purchase orders. Is this ESO specific or useful to others?

### Minimum Line and Order Value
- Minimum Line Value (Select: None, Surcharge, Strict)
- Min Line Value (Currency) [eval:minimum_line_value=="Strict, Surcharge"]
- Min Line Value Surcharge (Currency) [eval:minimum_line_value=="Surcharge"]
- Minimum Order Value (Select: None, Surcharge, Strict)
- Min Order Value (Currency) [eval:minimum_order_value=="Strict, Surcharge"]
- Min Order Value Surcharge (Currency) [eval:minimum_order_value=="Surcharge"]

**What's the workflow?** 
In Purchase order these must be added as surcharges if it is on minimum order value or on the lines if it is minimum line value.

### Shipping Cost
- Free Shipping (Check)
- Shipping Cost (Currency) [eval:free_shipping=="false"]
- Free Shipping if Value Over (Currency) [eval:free_shipping=="false"]

**What's the workflow?**
The shipping cost should automatically be applied or removed based on these conditions.

**Comment by creamdory** [comment]
Should we design this as something that a user can opt to set like Pricing Rule @dottenbr ? Because I believe that not all are using this feature.
