### ISSUE TITLE
Followup on Leads, Customers, Quotation and Opportunities.

### ISSUE THREAD

**Issue by adityaduggal** [frappe/erpnext#840]
There are a lot of features in erpnext related to management of sales but I think it is missing the punch. Just let me elaborate on this, basically if a lead is created and all meetings are put into that lead then there is no way to let the person remind about a missed followup.

Kindly also read the post no.3 here https://groups.google.com/forum/#!topic/erpnext-user-forum/Y-4RCQkVaP0

There is no way in the system to remind the user of a missed follow up on a lead or customer or quotation or opportunity. 

I think this can be achieved by using the existing functionalities but the only thing needed is to get them to work together in unison.

The suggestion for this is that:
1. Make a field in Communication for next contact date.
2. Make the communication as per request #638 
3. Now the next contact date could create a TODO in the person's todo list.
4. Also for the above to work we would need to implement the request #838 so that it becomes easier for person to track the todos.

**Comment by PawanMeh** [comment]
I think this can be closed, if any more changes are needed probably some screen shots with pending features in a separate issue may help for clarity.

**Comment by adityaduggal** [comment]
@PawanMeh I don't think that the followup capabilities of erpnext are still there and hence closing this issue might as well be a problem as follow up is an integral part of any CRM which I still think is lacking in erpnext.
