### ISSUE TITLE
BUG: Path to report is not correct.. 

### ISSUE THREAD

**Issue by justinlusg** [frappe/erpnext#8402]
![image](https://cloud.githubusercontent.com/assets/12539216/24898236/c34a49be-1ece-11e7-9938-9a1dec900068.png)

The path to reports is not correct for custom reports when using the "Reports" dropdown menu to select

**Comment by adityaduggal** [comment]
@justinlusg I checked it on https://demo.erpnext.com but I was unable to replicate this issue.
If I got to sales order list view and select a report from the reports menu on the left I am able to redirect to the correct report.

Can you confirm if this issue still exists on the latest version, if so then please try to replicate it on demo.erpnext.com

**Comment by manassolanki** [comment]
Closing the issue as there is no reply and issue isn't replicating in the demo account. 
@justinlusg Please feel free to reopen the issue if the problem still persists.
