### ISSUE TITLE
can not migrate v7 site to v8

### ISSUE THREAD

**Issue by sbkolate** [frappe/erpnext#8406]
_mysql_exceptions.ProgrammingError: (1146, "Table '8660a8394a7d7372.tabfeedback trigger' doesn't exist")

temporary solution:
comment following lines

https://github.com/frappe/frappe/blob/develop/frappe/core/doctype/feedback_trigger/feedback_trigger.py#L41-L49

**Comment by mbauskar** [comment]
@sbkolate,

Can you please share the full traceback ?
