### ISSUE TITLE
[developer branch] _mysql_exceptions.IntegrityError: (1062, "Duplicate entry '

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#8410]
Hello,

I'm having this issue with the last update:

> Executing frappe.patches.v8_0.fix_non_english_desktop_icons in 192.168.1.42 (d56cb677eaab3383)
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
>     "__main__", fname, loader, pkg_name)
>   File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
>     exec code in run_globals
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 79, in <module>
>     main()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 16, in main
>     click.Group(commands=commands)(prog_name='bench')
>   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 696, in main
>     rv = self.invoke(ctx)
>   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
>     return callback(*args, **kwargs)
>   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
>     return f(get_current_context(), *args, **kwargs)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 24, in _func
>     ret = f(frappe._dict(ctx.obj), *args, **kwargs)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 210, in migrate
>     migrate(context.verbose, rebuild_website=rebuild_website)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/migrate.py", line 31, in migrate
>     frappe.modules.patch_handler.run_all()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 29, in run_all
>     if not run_single(patchmodule = patch):
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 63, in run_single
>     return execute_patch(patchmodule, method, methodargs)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 83, in execute_patch
>     frappe.get_attr(patchmodule.split()[0] + ".execute")()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/patches/v8_0/fix_non_english_desktop_icons.py", line 22, in execute
>     set module_name=_doctype, label=_doctype where name=%s""", d.name)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 138, in sql
>     self._cursor.execute(query, values)
>   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
>     self.errorhandler(self, exc, value)
>   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
>     raise errorclass, errorvalue
> _mysql_exceptions.IntegrityError: (1062, "Duplicate entry 'ToDo-EMAILID-0' for key 'unique_module_name_owner_standard'")
> 

I raised this issue the other day https://github.com/frappe/erpnext/issues/8315 and I think something went wrong on ToDo creation, because other users are seeing ToDos normally and my user don't.

I didn't modified anything in the code, I just created a ToDo and after that the screen became grey and now this issue prevents me from updating.

**Comment by nabinhait** [comment]
There are 2 desktop  icons  exists for todo, which is creating problem. Try to delete one icon from bench console or bench mysql and then try to update again.

**Comment by applepipe** [comment]
Hello @nabinhait, thank you for helping me. Do you have any clue why this happened? The other icon for ToDo was a report, that did not had any problem until this update, I still think that this is something related to the other issue raised before.

Just to be sure since is the first time I'm deleting something directly in the db, should I delete the every data linked to ToDo present on "tabDesktop Icon" table?

Do you have any practical example? I searched in the forum but couldn't find anything in this subject.

**Comment by applepipe** [comment]
Hello again @nabinhait 
I've deleted the icon row, and the error happened to every report saved to desktop, they where saved like months ago, nothing new or edited recently.

After deleting the other rows the update ran without problems but the issue raised before persists, somehow when I click on ToDo it redirects me to /desk#List/ToDo/1fb2912197 this is the ID of the last ToDo created before the error, but this ToDo is already deleted.

I really dont know how this happened since I didnt modified anything in the code or any field, or anything related to ToDo, other users can access normally.

Can you help me follow this error?

**Comment by netchampfaris** [comment]
@applepipe 
Hi,
Open your JS console, and paste this line of code:
```
frappe.model.user_settings.save('ToDo', 'last_view', 'List')
```

**Comment by applepipe** [comment]
Thank you @netchampfaris !!
