### ISSUE TITLE
A Cost Centre is not visible in the Cost Centre Tree

### ISSUE THREAD

**Issue by Jaliya** [frappe/erpnext#8414]
When I created a cost centre "TOYOTA Kurunegala" following message pops up.
"Duplicate name Cost Center TOYOTA Kurunegala - DP"
I may have earlier created such cost centre. Then why it is not visible in the Cost Centre Tree.
Jaliya

**Comment by rmehta** [comment]
Cannot replicate. Maybe its in a different collapsed branch of the tree?
