### ISSUE TITLE
No error message if Password is wrong

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#8415]
It keeps showing validating, and user doesn't understand what is the cause of it. It should clearly indicate that password is wrong, and ask to enter correct password.

![screen shot 2017-04-12 at 11 50 06 am](https://cloud.githubusercontent.com/assets/910238/24943897/4de686d0-1f76-11e7-90d5-ba5191c86e23.png)

**Comment by netchampfaris** [comment]
Fixed via https://github.com/frappe/frappe/commit/89895718b2e4f1921467bebe05848688186b2b55
