### ISSUE TITLE
Recurring Journal Entry

### ISSUE THREAD

**Issue by yashgaglani** [frappe/erpnext#8418]
Hello Team,

There should be an option for 'Recurring' for Journal Entry as it is for Sales Invoice.
Please update this option as it will be of great help for my company.

**Comment by PawanMeh** [comment]
Auto-repeat feature is available in version11 for Journal Entry

![auto_repeat](https://user-images.githubusercontent.com/20460498/47207689-80e19000-d3a9-11e8-9dd6-24fbbd048335.png)
