### ISSUE TITLE
Material transfer for subcontracting purchase orders

### ISSUE THREAD

**Issue by cosimot** [frappe/erpnext#8428]
The tool for material transfer in subcontracting purchase orders is very useful if the bom has many child items.
However I really miss the possibility to transfer more than one item per stock entry.
If a subcontracting purchase order has 10 items I must make 10 material transfers....

**Comment by djpalshikar** [comment]
It is also a interface limitation. As each time you transfer material you need to specify the Qty for which Raw Material is being transferred. Could you suggest an interface?
