### ISSUE TITLE
[enhancement] Variant creation on sales order/quotation

### ISSUE THREAD

**Issue by almeidapaulopt** [frappe/erpnext#8435]
In Orders/quotations you can create a new item if it doesn't exist during order/quote creation, but you can't create a new variant of a item template.
In the image item template "variant" exists and it doesn't appear on search (correctly because is a template). but should exist something like "+ create a new item from 'variant'" or "+ create a new variant of 'variant'".

![screenshot from 2017-04-13 12-02-19](https://cloud.githubusercontent.com/assets/22657407/25002397/2080fee2-2042-11e7-8562-6d1cfbe73194.png)

**Comment by manasan3010** [comment]
@almeidapaulopt maybe this post might help you.
https://discuss.erpnext.com/t/create-new-item-attribute-value-quickly/69804/3
