### ISSUE TITLE
[BUG V8] No Permission to save report

### ISSUE THREAD

**Issue by vladucoju** [frappe/erpnext#8442]
Hi,

after update to v8 don't have permission to edit /create reports as admin in developer mode. In comunitty forum was two topic about same problem

https://discuss.erpnext.com/t/itemwise-recommended-reorder-level-report-with-sum/22156?u=vladucoju

https://discuss.erpnext.com/t/no-permission-to-save-report/22431?u=vladucoju

**Comment by rmehta** [comment]
seems fixed
