### ISSUE TITLE
ERPNext Website - When accessing on mobile, Item Name is truncating

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#8452]
https://frappe.erpnext.com/desk#Form/Issue/WN-SUP24296

Item names are not displaying correctly on the website when it’s being displayed on an Android smartphone using Chrome, the item image size adjusts nicely but not the item name text, it also does not hyphenate which means that words are just randomly cut.

In this example, the item name shows correctly on a PC display (see below) but when you do the same search on a smartphone the item name text does not resize and hyphenate where it should (see attached screenshot), is there an html tag to use in the item name to avoid this? Thanks.

https://frappe.erpnext.com/private/files/Screenshot_2017-04-14-11-09-11.png

**Comment by joezsweet** [comment]
Actually i'm even getting an error on Android app: index.html not found
