### ISSUE TITLE
Sales Invoice Import - Item Description in excel file is getting overwritten with Description in Item master

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#8457]
Reported by @adityaduggal 

I am trying to import the Sales Invoice through the data import tool but the problem is that the description field is getting automatically changed to the default description of the item master.

I would like to know if there is a way to over-ride the description of the item master in the sales invoice item table.

Item Code = Tool
Defualt Item master description = CS Tool

I am trying this with no luck, any help on this would be highly appreciated, enclosed is the csv file being used to import the item table of an invoice.

**Comment by adityaduggal** [comment]
@umairsy @manassolanki Any update on this issue since it was expected to work out of the box.

**Comment by adityaduggal** [comment]
@umairsy @manassolanki Please let me know if any solution can be found on this issue.

**Comment by umairsy** [comment]
@nabinhait can we please assign it to someone?

**Comment by manassolanki** [comment]
Hi @adityaduggal,
Data Import tool actually imports the data via the backend API. so while importing sales invoice, backend controller overwrites the description for the item. To work this out, we have to make modifications in the backend controller. I will update you regarding this after having a discussion with @nabinhait.

**Comment by adityaduggal** [comment]
Any update on this issue?

**Comment by adityaduggal** [comment]
@nabinhait can you please help us out with this issue as we are unable to import a lot of invoices and have to change the description manually.

**Comment by adityaduggal** [comment]
@nabinhait This issue is supposedly for WN-SUP24301 which is 2 months old and we are unable to move forward with this kindly give a hint and I would try to push a fix if I am able to understand.
@rmehta Please help me resolve this issue its a big headache for us.

**Comment by rmehta** [comment]
@adityaduggal why do you want to change descriptions in bulk? Best way would be to write your own script :)

**Comment by manassolanki** [comment]
Hi @adityaduggal ,
I have tried this and data import tool is successfully updating the description. Please have a look at the gif.
![data import](https://user-images.githubusercontent.com/20757311/29653548-e25d64cc-88c7-11e7-8b59-a0538c73d45a.gif)

I am closing the issue for now. Please reopen if you won't be able to update.
