### ISSUE TITLE
When making Sales Invoice from Delivery Note, cost center of item defaults to "Main"

### ISSUE THREAD

**Issue by sagarvora** [frappe/erpnext#8458]
Steps to reproduce:
- Create a item with cost center other than "Main".
- Create delivery note for that item.
- Make sales invoice from delivery note.
- Check cost center in Sales Invoice's item.

**Comment by Olawale1** [comment]
I reported this issue over a month ago

https://github.com/frappe/erpnext/issues/8036

I believe it's been fixed. Are you on V8?

Kind regards,

**Comment by sagarvora** [comment]
@Olawale1 Your issue was different. It applied when Delivery Note is made from Invoice. 

In my case, Invoice is made from Delivery Note.

**Comment by Olawale1** [comment]
Yes, you're right. That means the issue was both ways
