### ISSUE TITLE
Purchase invoice marked ‘is paid’ but appears to be Unpaid

### ISSUE THREAD

**Issue by cze-karel** [frappe/erpnext#8464]
Having issues on v8.0.10 with Purchase Invoice that I have marked as paid, selected Mode of Payment, Paid Amount. There is the payment visible in Accounting Ledger, however the Purchase Invoice still appears as Unpaid.

![image](https://cloud.githubusercontent.com/assets/7423230/25068987/da49e9a8-229d-11e7-862a-63ff554e51ea.png)

![image](https://cloud.githubusercontent.com/assets/7423230/25068985/c697706a-229d-11e7-8a14-47f0057f9aee.png)

![image](https://cloud.githubusercontent.com/assets/7423230/25068980/8c0353ce-229d-11e7-8adf-e14440a5b34b.png)

**Comment by nabinhait** [comment]
Can't replicate it? Are you still facing the issue and for all invoices?

**Comment by tundebabzy** [comment]
Thanks for reporting this @cze-karel .It happens sometimes but a page refresh will normally fix it. If you still experience this consistently, please reopen the issue

**Comment by cze-karel** [comment]
Sorry for the delay guys and thank you for those replies. I have tested this again in the latest version and it works as expected.
