### ISSUE TITLE
Item quantities not adjusted after Purchase Return

### ISSUE THREAD

**Issue by viraljmestry** [frappe/erpnext#8465]
1. Puchase Invoice
![purchase_invoice](https://cloud.githubusercontent.com/assets/27627459/25071650/7e1ae618-22da-11e7-9534-c9cfbeffa3e3.JPG)

2. Return Invoice
![return_invoice](https://cloud.githubusercontent.com/assets/27627459/25071652/88137a72-22da-11e7-8839-51f704b89961.JPG)

3. **Item Reports issue**
![item_reports_undefined](https://cloud.githubusercontent.com/assets/27627459/25071654/9b07b850-22da-11e7-9e43-0103237471c5.JPG)

4. **Incorrect stock**
![incorrect_stock](https://cloud.githubusercontent.com/assets/27627459/25071659/bda9832a-22da-11e7-88ab-5421434959df.JPG)

**Note:** The opening stock was 0 for all items.

**Comment by rohitwaghchaure** [comment]
Hi @viraljmestry 

Thanks for reporting an issue

**Purchase Invoice**
To deduct the stock quantity after making of purchase return entry using purchase invoice you need to enable the stock update option on the invoice else you can make purchase return entry against the purchase receipt. For more details please check link https://frappe.github.io/erpnext/user/manual/en/stock/purchase-return

**Item Reports Issue**
We have [fixed](https://github.com/frappe/frappe/pull/3101) the item report issue and soon we'll release it

**Stock Summary**
![screen shot 2017-04-17 at 12 03 21 pm](https://cloud.githubusercontent.com/assets/8780500/25081110/f8cb547a-2365-11e7-832e-d3f67e5aa322.png)

Here 3 is the non delivered sales order quantity and 1 is the actual quantity in the stock
