### ISSUE TITLE
In POS, Item Groups should appear in order, based on lft and rgt

### ISSUE THREAD

**Issue by nabinhait** [frappe/erpnext#8472]
**Current:**
<img width="795" alt="screen shot 2017-04-17 at 2 32 23 pm" src="https://cloud.githubusercontent.com/assets/836784/25084587/0cdb935c-237b-11e7-8d9a-24d83a7d3ccf.png">

**Expected:**
```
IG 0
    - IG 01
        - IG 011
        - IG 012
    - IG 02
```
For the above tree, dropdown will be like:
IG 0
IG 01
IG 011
IG 012
IG 02

**Comment by rmehta** [comment]
I think it should be alphabetic.

**Comment by nabinhait** [comment]
@rmehta Generally, when we resetting a filter from a dropdown, we select the "All" options, which normally appear as a first option. Same thing happened to me yesterday, I was searching for "All Item Groups" at the top, as a normal behaviour.
