### ISSUE TITLE
[Enhancement] AutoFill valid fields from parent form to quick entry form

### ISSUE THREAD

**Issue by aambernath** [frappe/erpnext#8475]
Many times there would be fields in Quick Entry form that needs to take data from the parent form from which it is called. An example that I came across is batch entry in stock entry. 

In batch entry we need to select the item in quick entry form when the information is already available in the parent form from which it is being called eg Sales Invoice, Stock Entry etc.

**Comment by RandyLowery** [comment]
True! can you provide a more extensive list of example?

**Comment by mobentec** [comment]
#12725

**Comment by mobentec** [comment]
Seems like this might relate to this issue: #12725 .
