### ISSUE TITLE
bom importing

### ISSUE THREAD

**Issue by SYMBARCELONA** [frappe/erpnext#8476]
i have this error message

Error for row (#21) : {"message": "Same item has been entered multiple times.", "indicator": "red"}

with this file imported
Data Import Template	Column 2	Column 3	Column 4	Column 5	Column 6	Column 7	Column 8	Column 9	Column 10	Column 11	Column 12	Column 13	Column 14	Column 15
Table:	BOM													
														
														
Notes:														
Please do not change the template headings.														
First data column must be blank.														
If you are uploading new records, leave the "name" (ID) column blank.														
If you are uploading new records, "Naming Series" becomes mandatory, if present.														
Only mandatory fields are necessary for new records. You can delete non-mandatory columns if you wish.														
For updating, you can update only selective columns.														
You can only upload upto 5000 records in one go. (may be less in some cases)														
														
DocType:	BOM					~	~	BOM Item	items			~	~	
Column Labels:	ID	Item	Quantity	Currency	Company			Item Code	Qty	Rate	Stock UOM			
Column Name:	name	item	quantity	currency	company	~	~	item_code	qty	rate	stock_uom	~	~	
Mandatory:	Yes	Yes	Yes	Yes	Yes			Yes	Yes	Yes	Yes			
Type:	Data (text)	Link	Float	Link	Link			Link	Float	Currency	Link			
Info:		Valid Item		Valid Currency	Valid Company			Valid Item			Valid UOM			
Start entering data below this line														
		86	1	EURO	SHIP YARD TECHNICAL MANAGEMENT SL			75821100	3	2.238	UNIT			
								73021100	3	1.6443	UNIT			
								75821200	24	3.618	UNIT			
								73021200	24	2.751	UNIT			
								67030093	100	0.1071	UNIT			
								71021005	20	0.357	UNIT			
								71021006	20	0.3045	UNIT			
								70122210	2	1.2285	UNIT			
								70132220	30	2.7426	UNIT			
								70020120	6	12.8919	UNIT			
								73020200	6	6.6171	UNIT			
								70022120	1	13.9104	UNIT			
								73022200	1	10.3362	UNIT			
								70025120	10	10.0107	UNIT			
								73025200	10	6.2664	UNIT			
								71021010	1	4.5717	UNIT			
								70028120	4	10.9221	UNIT			
								71021020	2	6.2769	UNIT			
								10520	100	0.4616	UNIT			
								280150	100	0.0404	UNIT			
								352160	6	3.88	UNIT			
								381155	2	2.94	UNIT			
								381170	2	2.94	UNIT			
								381180	4	5.22	UNIT			
								SGB6K2C10	10	2.8	UNIT			
								SGB6K2C16	10	2.8	UNIT			
								SGB6K2C25	20	2.8	UNIT			
								SGB6K2C40	10	2.95	UNIT			
								SGB6K2C63	5	17.21	UNIT			
								07000610V	500	0.08876	UNIT			
								7001310	300	0.14607	UNIT			
								20193535	200	0.11348	UNIT			
								20193543	200	0.18225	UNIT			
								20193548	200	0.28131	UNIT			
								21011200	100	0.2564	UNIT			
								21011250	100	0.416	UNIT			
								40021200	100	0.06	UNIT			
								40021250	100	0.072	UNIT			
								1212247050	10	13.07	UNIT			
								01380F10	100	0.0959	UNIT			
								01380F5	50	0.0959	UNIT			
								01380F16	50	0.0959	UNIT			
								01380F20	100	0.0959	UNIT			
								86210923	300	3.39953	UNIT			
								86225923	200	1.57128	UNIT			
								86223920	200	0.6766	UNIT			
								86221920	500	0.29883	UNIT			
								3NDA8321	1	117.64	UNIT			
								3NDA8322	1	176.06	UNIT			
								ENN34031	10	10.12	UNIT			
								SGV2-ME16	3	14.896	UNIT			
								SGV2-ME14	7	14.896	UNIT			
								SGV2-ME20	3	14.896	UNIT			
								SGV2-ME16	3	14.896	UNIT			
								SCP508	2	163.2	UNIT			
								NSYPLM108G	4	253.53	UNIT			
								NSYSDR200BD	10	1.3	UNIT			
								236072	15	6.97	UNIT			
								T824V60BF	35	5.98	UNIT

**Comment by rmehta** [comment]
Please see the error message check if you are adding the same item multiple times.

Best to make one BOM from the UI and then download the template with data to understand how to upload.

**Comment by SYMBARCELONA** [comment]
Already solved. Thanks.



Francisco Lage
Director

www.symbarcelona.com
