### ISSUE TITLE
Way to "Save and Add Another"

### ISSUE THREAD

**Issue by tundebabzy** [frappe/erpnext#8478]
I'm new with ERPNext and I'm trying to learn the ropes. I'm creating a lot of Items but it's getting annoying because for each Item, I have to click "New" from the Item list page (desk#List/Item). I think it would be nicer if the form for creating Items also has a "Save and Add Another". On clicking it, if the submitted data is successfully validated, the modal stays open and the form is reset so that the user can enter new data for another Item. That would save a lot of clicking and time.

![erpnext1](https://cloud.githubusercontent.com/assets/818803/25094996/89cd49d0-2391-11e7-96c7-6a9af7fb77ae.JPG)

**Comment by mbauskar** [comment]
@tundebabzy,

You can use the Data Import Tool to create multiple Item instead.

Please check the manual https://frappe.github.io/erpnext/user/manual/en/setting-up/data/data-import-tool

**Comment by tundebabzy** [comment]
@mbauskar 
Thanks for the reply. I think the data import tool is cool. I also just learnt that Ctrl + B does what I need. Thanks.
