### ISSUE TITLE
Show Supplier Part Number in Request for Quotation Report

### ISSUE THREAD

**Issue by PCzerw** [frappe/erpnext#8481]
When I'm making Request for Quotation, I can not display Supplier Part No on any report.
This field was hide by default in tabRequest for Quotation Item but after unhide still does no appear in reports.

**Comment by rmehta** [comment]
What report are you looking at?

**Comment by PCzerw** [comment]
Any rapport/document for email and printing. 

Dnia 18 kwietnia 2017 08:36:24 CEST, Rushabh Mehta <notifications@github.com> napisał(a):
>What report are you looking at?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/frappe/erpnext/issues/8481#issuecomment-294702249

-- 
Wysłane z urządzania mobilnego, przepraszam za lakoniczność.

**Comment by federicocalvo** [comment]
Hi, the same issue here.

The Supplier Part No not available form Print Format. 

<img width="605" alt="captura de pantalla 2018-06-14 a la s 12 58 26" src="https://user-images.githubusercontent.com/7256766/41424450-75b53698-6fd4-11e8-9fab-a912cd708bd7.png">

Only from a HTML which is generated from the erpnext code.

**Comment by AnveshGoud** [comment]
Is this open issue to be investigated or gone stale?

**Comment by PCzerw** [comment]
I don`t remember :)
