### ISSUE TITLE
Total Row does not tally with sum of the lines for currency

### ISSUE THREAD

**Issue by ASneha1** [frappe/erpnext#8501]
Hi Team, 

This is the Monthly Salary Register, where 'SDL' is a Salary Component of type Currency, set to precision of 2. The last row of $32.90 is the total calculated when 'Add Total Row' is ticked.
![image](https://cloud.githubusercontent.com/assets/16811259/25173876/479c97b2-2528-11e7-8182-ca5efea593e2.png)

Because of pro-rating due to LWP, the SDL for the month was calculated to be $7.825. And at the Salary Slip and Monthly Salary Register, it shows as $7.83, which we agree with. 
However, when calculating the total, it seems to be using the $7.825 amount, rather than the $7.83 amount. Thus, we are not able to reconsile the line items to sum up to the total - it is 1 cent off. 

If we export the report, we are able to see that the total is calculating based on the $7.825 amount, rather than the $7.83 amount. Since  'SDL' is a Salary Component of type Currency, set to precision of 2, should it not be calculating on the 2 decimal point amount?
![image](https://cloud.githubusercontent.com/assets/16811259/25173954/8045e550-2528-11e7-8e22-e65f28122a15.png)

**Comment by manassolanki** [comment]
Hi @ASneha1,
Is the issue still replicating? I have tried in my local and it is working fine. 
If it is still replicating, please provide some leads to replicate.

**Comment by manassolanki** [comment]
This is working properly. If the currency precision is set in the system settings, all the salary components which depend on LWP are calculated as per the precision settings. If the issue still persists, please feel free to reopen it.
