### ISSUE TITLE
Transfer Asset

### ISSUE THREAD

**Issue by ahmadRagheb** [frappe/erpnext#8502]
In the Accounts >> Asset 

After submit the asset ,, there is three custom buttons on the top .

one of them "Transfer Asset" to transfer assets from warehouse to another one ..

It doesn't work but when i goo to Asset movement in Accounts and make new movement it works good for mee ,,

**Comment by nabinhait** [comment]
Can't replicate in my local. Please share the error message from browser console if any.

**Comment by PawanMeh** [comment]
Closing this for now, kindly share more information to replicate the issue.
