### ISSUE TITLE
[minor] Spelling Mistake

### ISSUE THREAD

**Issue by OneiricIT** [frappe/erpnext#8508]
ERPNext: v8.0.14 (master)
Frappe Framework: v8.0.19 (master)

Customize Form message as below - spelling 'required'

![opera_2017-04-20_19-32-34](https://cloud.githubusercontent.com/assets/22227933/25224032/8823f7ca-2600-11e7-85aa-f25d04e7dafd.png)

**Comment by strixaluco** [comment]
fixed via https://github.com/frappe/frappe/commit/3d78df3712185de6a48f75d2a4047f61d9372c07
