### ISSUE TITLE
Unable to login to latest ERPNext production release on Safari Browser

### ISSUE THREAD

**Issue by PawanMeh** [frappe/erpnext#8510]
Version Details

1. ERPNext: v8.0.14 (master)
2. Frappe Framework: v8.0.19 (master)

Once you login to ERPNext after fresh installation, it appears that the screen hangs on the ERPNext Icon

![screen shot 2017-04-20 at 3 22 23 pm](https://cloud.githubusercontent.com/assets/20460498/25224824/35a3b134-25dd-11e7-9482-c4b8488a3204.png)

![screen shot 2017-04-20 at 3 28 45 pm](https://cloud.githubusercontent.com/assets/20460498/25225148/1e6f30dc-25de-11e7-881e-e852669be196.png)

Here is the web error.log

![screen shot 2017-04-20 at 2 34 02 pm](https://cloud.githubusercontent.com/assets/20460498/25224859/599b7892-25dd-11e7-947d-11ce06a4b19b.png)

**Comment by rmehta** [comment]
you did not migrate correctly. run `bench migrate` on your site.

**Comment by PawanMeh** [comment]
I did run, bench migrate, after that I could login from Firefox, Google Chrome but not Safari, however if this is tested on your end, it can be closed.

**Comment by krnkris** [comment]
Clear the browser cache 
+
don't use privacy blokker

Hope it helps!

**Comment by mbauskar** [comment]
@PawanMeh login through safari is now working please update and try again

![safari](https://cloud.githubusercontent.com/assets/11224291/25275033/cfdce3a0-26b0-11e7-9691-3a7991c5d855.gif)
