### ISSUE TITLE
[developer branch] Bench update hangs on Executing frappe.patches.v8_0.update_records_in_global_search 

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#8512]
Hello,

When I run bench update it hangs on this step:

Migrating erpnext.vm
Executing frappe.patches.v8_0.update_records_in_global_search in erpnext.vm (d56cb677eaab3383)

No errors are shown, it just doesnt complete the update

**Comment by nabinhait** [comment]
Yes, it takes to much time to build the global search table.
For now just comment that patch and move on. I will try to refactor the patch to make it fast.

**Comment by applepipe** [comment]
Hello @nabinhait thanks for the help, do you have any hint on how to comment the patch?

**Comment by nabinhait** [comment]
You need to comment out / delete this line temporarily.
https://github.com/frappe/frappe/blob/develop/frappe/patches.txt#L15
