### ISSUE TITLE
LookupError: You must have test.fm >= 1.0.4 installed before (https://github.com/grafos-ml/frappe)

### ISSUE THREAD

**Issue by tundebabzy** [frappe/erpnext#8514]
Hello,
I get this error when trying to install ERPNext locally:
`LookupError: You must have test.fm >= 1.0.4 installed before (https://github.com/grafos-ml/frappe)`

This really surprised me because I'm installing with pip using the bundled `requirements.txt` file. The root problem is that the required `frappe` (github.com/frappe/frappe) in `requirements.txt` does not (presently) exist on pypi therefore pip is installing the library it can find there (https://github.com/grafos-ml/frappe).

This is trivial to fix. I will attach a fix in a few minutes to solve the problem once I get ERPNext up and running on my computer.

**Comment by niamulrox** [comment]
Any way to solve the error ?

**Comment by tundebabzy** [comment]
This error was because I tried to install erpnext with pip. The way to solve the error is "don't install with pip". Follow the instructions on https://github.com/frappe/bench/blob/master/README.md
