### ISSUE TITLE
[v8] Manufacturing BOM Breadcrumb Navigation

### ISSUE THREAD

**Issue by OneiricIT** [frappe/erpnext#8518]
ERPNext: v8.0.14 (master)
Frappe Framework: v8.0.19 (master)

When in BOM Item (Manufacturing > BOM > [BOM Item]) and selecting BOM in breadcrumb navigation, it takes you to the BOM Tree instead of the BOM list where you originally came from via Manufacturing > BOM.

![2017-04-21_10-46-19](https://cloud.githubusercontent.com/assets/22227933/25258075/24f7ce08-2680-11e7-95ab-4023eaaff2e7.gif)

**Comment by ishanloya** [comment]
I agree. Also, I think the list view should be the default view instead of the tree view.

**Comment by pratu16x7** [comment]
Reported at #8069. Hence closing here.
