### ISSUE TITLE
[enhancement] option to choose separator on csv files

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#8520]
Exporting csv files to edit on excel in some countries can be a little annoying, because it requires that you import as text file going trought a menu to choose codification, separator, delimited or fixed space, etc, or set default separator as "," and go trought the same menu for files with the separator according to the region/language.

For me is not something really painfull, but some employees get a little confused over this, in brazil the default separator  is ";". So it would be really good if we can choose the separator in settings, like decimal separator/number format.

**Comment by jwrober** [comment]
+1, we prefer to use the pipe symbol ( | ) as a separator for our flat files that we process. This would be a great addition to the platform.

**Comment by manassolanki** [comment]
As now you can export and import in the Excel file format, so I think this has already fixed your use case. If you still have some issue in the usability, please feel free to reopen the issue.

**Comment by applepipe** [comment]
hello @manassolanki ! thank you, it helped a lot! But... when the employees try to download and upload attendances, grid editions, it is still in the csv format and the problem still affects us.
