### ISSUE TITLE
Unable to create salary slip via Process Payroll[V8]

### ISSUE THREAD

**Issue by abue90** [frappe/erpnext#8521]
Hi ERPNext team,

As per title, i not able to to create salary slip via Process Payroll. Upon clicking the "Create Salary Slip Button", this error was thrown in my browser's console:

![image](https://cloud.githubusercontent.com/assets/15136489/25261042/a9bd355e-2682-11e7-9394-7b389ac04eb2.png)

ERPNext version 8.0.9

Best Regards,
Abu Talha

**Comment by KanchanChauhan** [comment]
Can you please make sure you have Employee and Salary Structure for the selected filters in Process Payroll.

**Comment by abue90** [comment]
Yup, Employee and Salary Structure are exist for the selected filters in Process Payroll. I have tried on https://demo.erpnext.com, also showing same result

**Comment by KanchanChauhan** [comment]
Screenshots please, I tried on Demo worked for me. Below is the screenshot.
![image](https://cloud.githubusercontent.com/assets/16913064/25278055/d1be0efc-26be-11e7-8afd-cb678c57e036.png)

**Comment by manassolanki** [comment]
Hi @abue90,
Are you still facing the issue? If yes, please provide some steps to replicate the issue.

**Comment by manassolanki** [comment]
Closing the issue as this is not replicating in the demo and no reply from concerned persons.
