### ISSUE TITLE
Project Gannt Chart - Moving task in chart adds day

### ISSUE THREAD

**Issue by mineolatx** [frappe/erpnext#8531]
When in project gantt chart and you move a task it adds a day to all task that were moved. 

See screen cap.
![untitled-1](https://cloud.githubusercontent.com/assets/18650730/25295790/bb7aca04-26aa-11e7-8871-feef91676427.jpg)

Next I move task 2 which also moves task 3.

![untitled-2](https://cloud.githubusercontent.com/assets/18650730/25295817/dc1a037e-26aa-11e7-9b4b-aff02a4dd0c6.jpg)

Next I click refresh button.

![untitled-3](https://cloud.githubusercontent.com/assets/18650730/25295833/f530382e-26aa-11e7-9212-a1975827f188.jpg)

The result after refresh. 1 day was added to task 2 and 3. Now they are 3 days long instead of 2.

![untitled-4](https://cloud.githubusercontent.com/assets/18650730/25295854/10c10640-26ab-11e7-991c-c4ca8873e398.jpg)

**Comment by PawanMeh** [comment]
This could be because they are dependent tasks. Could you check, if you have them listed as dependent tasks?

![screen shot 2017-04-29 at 5 20 05 pm](https://cloud.githubusercontent.com/assets/20460498/25555304/3328e4f4-2d00-11e7-9047-2e9bb109c745.png)

**Comment by mineolatx** [comment]
@PawanMeh 
Has nothing to do with dependent task. Adds day to end of task if you move it in gantt chart with no dependent task. You don't see it till you refresh. I tried it in online demo and it does the same thing.
Not sure why this is closed since it is not fixed.

**Comment by strixaluco** [comment]
Can replicate the issue on ERPNext v8.0.22 / Frappe Framework v8.0.35

**Comment by mineolatx** [comment]
@netchampfaris 
The fix works great. Thanks for your hard work on this! 
Now to see if we can put the projects feature to work to track some of our maufacturing till we can implement the full software.
Thanks again.
