### ISSUE TITLE
iOS App does not allow to login to self Hosted ERPNext Server

### ISSUE THREAD

**Issue by SunnyGurnani** [frappe/erpnext#8532]
I download iOS App of ERP Next and I am trying to login to my Shelf Hosted ERP Next Server.

So I entered userid and password and clicked on Change Server and entered url of my hosted ERPNext Server.

But on Clicking GO (In Change Server Screen) nothing happens.

**Comment by netchampfaris** [comment]
Cannot replicate. Closing for now.
If you are still facing the issue, please provide iPhone version and ERPNext app version, and reopen this issue.
