### ISSUE TITLE
[developer branch] Uncaught TypeError: Cannot read property 'summernote' of undefined

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#8533]
Hello,

After last update I get this error on javascript console, whenever I try to visualize a Sales Order, Delivery Note or Quotation.

<img width="1673" alt="screen shot 2017-04-22 at 8 47 01 am" src="https://cloud.githubusercontent.com/assets/18335894/25304207/f91786f2-2738-11e7-81e1-88e376d48f30.png">

**Comment by daneekadoc** [comment]
It's a breaking bug IMHO. In addition, Sales Invoice produces it as well. I can't acces my invoices...

**Comment by rmehta** [comment]
This is fixed. Release @nabinhait ?

**Comment by nabinhait** [comment]
Released the fix, please update.

**Comment by daneekadoc** [comment]
Thanks for the quick work, 8.0.23-dev fixes this!

**Comment by applepipe** [comment]
Thank you!
