### ISSUE TITLE
[developer branch] Cant access bank reconciliation

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#8535]
I have multiple companies and can't select one as default or it would induce users to error, and when I try to access bank reconciliation the screen goes grey.  The javascript console shows this error:

<img width="1629" alt="screen shot 2017-04-22 at 9 51 13 am" src="https://cloud.githubusercontent.com/assets/18335894/25304629/a6526f46-2741-11e7-8aeb-cf785b05537d.png">

I have default bank account set on each company.

**Comment by mbauskar** [comment]
@applepipe,

Please set the default company in **Global Default** to resolve the issue

**Comment by applepipe** [comment]
hello @mbauskar,

Sadly as I said in my previous post, I cant set the default company, as this could lead employees to error, It would be good to have the option to select company like other reports, after the opening.

**Comment by mbauskar** [comment]
pushed a fixed please pull the latest changes, if the issue still persist please reopen the ticket.
