### ISSUE TITLE
[developer branch] Cant access files

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#8536]
Hello,

When I try to access the uploaded files the screen goes grey and the javascript console shows this error:

<img width="1666" alt="screen shot 2017-04-22 at 11 16 12 am" src="https://cloud.githubusercontent.com/assets/18335894/25305199/4329b922-274d-11e7-93bf-acc24118b3b2.png">

**Comment by mbauskar** [comment]
@applepipe can not replicate, please try to clear cache, run bench build if the issue still persist please post the steps to reproduce the issue

**Comment by applepipe** [comment]
hello @mbauskar,

Cleared the cache, ran bench build and everything, but the problem persists.

I did not change anything in the code, or made any complex steps, just clicked on sales order after the update on friday and noticed the error.

**Comment by rmehta** [comment]
I can't replicate either. Please share full steps or make a screencast using licecap and re-open
