### ISSUE TITLE
Subcontracting - Overhaul

### ISSUE THREAD

**Issue by epochc** [frappe/erpnext#8540]
Organizations leverage subcontracting extensively and the current way ERPNext is structured for subcontracting is very limiting.

Neither can you send an entire PO (all items have all necessary requirements for Sub Contracting) consisting of multiple items to a subcontractor in a single Stock Entry (Purpose: Sub Contract) and neither can you pull multiple PO.s (for the same supplier, of course) into a single Stock Entry (Purpose: Sub Contract).

Having to make a separate document for each item is very tedious and time consuming. We simply need a better way.

Thanks

Jay

**Comment by somicoito** [comment]
Agree with you as I also mentioned here
https://github.com/frappe/erpnext/issues/8428
I also consider the fact that subcontracting purchase order does not affect warehouse a big problem
https://github.com/frappe/erpnext/issues/8427
What do you think about it?

**Comment by joezsweet** [comment]
is there any chance to sponsor it?

**Comment by nabinhait** [comment]
@joezsweet Are you working on it? You can share the design, if you want any kind of help on that front.

**Comment by joezsweet** [comment]
@nabinhait Actually i've been contacted to develop some feature, namely:

#8428 and #8427

Thing is, they have hosted plan so it's not possible to install a custom app to get it done; so they would sponsor the features to be included in erpnext. 

About the requests and design:

#8427: I'd replicate same thing that's already in place for production order, so that each PO to supplier will reserve raw materials to send for subcontractor.

#8428: i'd change pop up so that will show all items in the PO with check box and create SE for all checked items in the pop up. 

How that sounds?

**Comment by somicoito** [comment]
@nabinhait for #8427 the actual design won't change.
In Purchase Order Item we already have Source Warehouse Field, this is the warehouse where Items will be reserved
<img width="1252" alt="8427-1" src="https://user-images.githubusercontent.com/26325987/28263839-c5f0556c-6ae8-11e7-9a6a-46b0133c509e.png">
Purchase Order Item Supplied is the list of reserved material.
<img width="1290" alt="8427-2" src="https://user-images.githubusercontent.com/26325987/28263889-e85a72ea-6ae8-11e7-87d0-a8721cd59fdf.png">

**Comment by somicoito** [comment]
@nabinhait @joezsweet  for #8540 and #8428 here is a visual sample

![3](https://user-images.githubusercontent.com/26325987/28264343-d27d7a24-6aea-11e7-8ded-2309cbfa3e2f.jpg)

If the purchased item is only one there shall not be a popup exactly as it is now, just directly the stock entry.

**Comment by rohitwaghchaure** [comment]
Hi @somicoito 

Sounds good! You can also show the items, bom_no, qty in the table, something like as below
![screen shot 2017-07-21 at 10 53 13 am](https://user-images.githubusercontent.com/8780500/28450183-57e1e5ae-6e03-11e7-89d8-c735b2e9985f.png)

**Comment by somicoito** [comment]
@rohitwaghchaure I think it is a very good Idea but also would like to keep things as simple as possible. Maybe we could show Item Code, Row Material, q.ty and BOM but would not give the option to edit anything here, once the material transfer is open you can adjust quantities there. Also BOM is selected when the PO is Submitted.
All the infos can be fetched from Raw Material Supplied Table.
@joezsweet  what is your opinion?
![material-transfer](https://user-images.githubusercontent.com/26325987/28454875-1ac225e0-6dfd-11e7-8bde-b84ef162ec76.jpg)

**Comment by djpalshikar** [comment]
Willing to sponsor this feature.

**Comment by somicoito** [comment]
Hi @djpalshikar ! I am currently sponsoring [this Pull Request](https://github.com/frappe/erpnext/pull/11719) in order to fix reserved material on subcontracting Po. 
I hope this can be released soon by @nabinhait  :) 
After this is merged the next in line is this one for transferring material to supplier.
I will be very happy if you would like to contribute!

**Comment by djpalshikar** [comment]
Yes I would like to contribute for sponsoring!

**Comment by somicoito** [comment]
@PawanMeh do you think you can make a pull-request for this?

**Comment by djpalshikar** [comment]
I am currently sponsoring issue #12150 , which I think will have some effect on how #8540 should be designed.

**Comment by somicoito** [comment]
@djpalshikar is there a pull request for this? Or this will be made with an app?

**Comment by djpalshikar** [comment]
It will be a pull request

**Comment by PawanMeh** [comment]
@somicoito, as discussed, I plan to take this up in this month.

**Comment by PawanMeh** [comment]
@somicoito, [PR](https://github.com/frappe/erpnext/pull/12602) has been sent for review.

**Comment by PawanMeh** [comment]
Closing this one as PR is merged into develop and targeted for release with v11, other dependent issues like 12150 can be worked upon/discussed in their respective issue threads.
