### ISSUE TITLE
Add Expense Claim to list of transactions available in Authorisation Rule

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#8546]
Hi,

I just noticed in the process of mapping out a custom workflow that there is no provision for applying authorization rules to Expense Claims! Expense Claims require authorizations just as much (if not more) than some of the other transactional documents available. Please add it

Note: This is especially needed because as per current design, we have to customise the Expense Claim form for managing both Imprest and Retirement

Thanks

Kind regards,

**Comment by mhbu50** [comment]
whay Authorisation Rule lemited for some few documents?!
Authorisation Rule shold be for any other transactional documents available!

**Comment by olamide2** [comment]
Can we add this back like yesterday please.

Thanks guys

**Comment by PawanMeh** [comment]
Similar to #12343
