### ISSUE TITLE
Allow selection of Asset Accounts in Expense Claim Types

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#8548]
Hi,

According to the current design of ERPNext, the Expense Claim form is used for both Imprest and Retirement. For setting up the Imprest part, account heads need to be created under Current Assets but the system is restricting selection of such accounts in Expense Claim Types. Kindly look into this

Thanks

Kind regards,

**Comment by revant** [comment]
query in `expense_claim_type.js` is not allowing current assets.
```
frm.fields_dict["accounts"].grid.get_field("default_account").get_query = function(frm, cdt, cdn){
	var d = locals[cdt][cdn];
	return{
		filters: {
			"is_group": 0,
			"root_type": "Expense",
			'company': d.company
		}
	}
}
```
https://github.com/frappe/erpnext/blob/develop/erpnext/hr/doctype/expense_claim_type/expense_claim_type.js

**Comment by tundebabzy** [comment]
Hi @Olawale1 
The Expense Claim is used to record reimbursable expenses by employees and that invoices Expenses and Account Payables. The only asset that can come into the equation is Cash/bank and that involves clicking 'is paid' and you will be asked to select the appropriate cash/bank account.
