### ISSUE TITLE
Restrict space in the naming series

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#8557]
Reference: https://frappe.erpnext.com/desk#Form/Issue/WN-SUP24464

In the Naming Series, space should not be allowed.

**Comment by Olawale1** [comment]
Hi @umairsy 

Trust you're doing great. Could you be more specific about this issue? I'm asking because some of us use spaces in the naming series! I don't think it'll be okay to just remove that without discussion or consultation

Thanks

Kind regards,

**Comment by umairsy** [comment]
Hello @Olawale1,

Thanks for the comment. As reported by the Customer, feature of updating current value doesn't work fine if series has space in between.

Disabling space in the series is also seen as a best practise, and will resolve issue of current value as well. However, we are open for the suggestion from the community member, hence the public issue on Github :)

**Comment by Olawale1** [comment]
Hi @umairsy 

Do you mean space as in "X YZ001" or "XYZ 001"? I want to believe you're referring to the first example. If that's the case, I guess there aren't as many people who use that format but it's good that users are made aware before such changes are implemented

Thanks
