### ISSUE TITLE
Payment Entry - Other Customers Orders showing in the Reference table.

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#8559]
Reported by Customer via WN-SUP24413

In the Payment Entry, Customer is already selected. But in the reference table, it is showing Sales Orders of other customers as well. This was working fine in V7. Issue found in V8 only.

**Comment by rohitwaghchaure** [comment]
Issue is fixed via PR https://github.com/frappe/erpnext/pull/9299
