### ISSUE TITLE
Delivery date per Sales Order line, not per Sales Order

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#8568]
- [ ] Instead of ```Sales Order``` having a field ```Delivery Date``` every ```Sales Order Line``` (Child Table) should have ```Requested Delivery Date``` (the date the customer actually wants and expects the delivery) and ```Confirmed Delivery Date``` (the date that we as a company actually confirm to deliver).
- [ ] Write patch for existing ```Sales Order -> Delivery Date``` to be written into the ```Sales Order Line -> Confirmed Delivery Date```
- [ ] When creating a ```Production Order``` allow to create separate production order for each line or to create one production order for all lines of one item.
- [ ] When you make ```Delivery Note``` from sales order, there can be a modal asking if you want to make full delivery note or only for a particular date and if so from which you will deliver.
- [ ] ```Requested Delivery Date``` and ```Confirmed Delivery Date``` should show up in the ```Sales Order Print```but since we don't have indefinite table columns I recommend adding it under the ```Item Description``` in the form of a sub-table that shows both.

<img width="551" alt="sample" src="https://cloud.githubusercontent.com/assets/9136094/25384130/cac866c2-29c7-11e7-8c46-7c7a2c1ac2d1.png">

### Why have Requested and Confirmed Delivery Date?

The customer requests for an item to be shipped by a certain date. But maybe due to lead times from suppliers or production lead times this may not be possible. It is important for the company and the customer to see that there is actually a difference between the two dates and that the customer should either accept the later date and send a changed PO or the company should do something to escalate the situation. In any case having both allows for tracking to make sure the information in both ERP of the customer and company are aligned.

**Comment by joolsr** [comment]
Yes I would welcome this approach for our manufacturing company too. Whether its something that should be allowed to be enabled or disabled for individual use cases I'm not sure but it may not always be relevant for some installations/company types

**Comment by emakis** [comment]
Any progress on this?

**Comment by Jammyinc** [comment]
I need this functionality as well.

**Comment by nabinhait** [comment]
Implemented the functionality, will be released within a week. #9933
