### ISSUE TITLE
Web Form not showing in main sidebar

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#8570]
Hi,

When a web form is created against a standard doctype, it doesn't show among the options in the main menu. The only way to get to the form is by typing the full path in the browser! Web forms for custom doctypes are not even working at all but that's a different issue for which I've also created a ticket

Kindly help resolve this

Thanks

Kind regards,

**Comment by rohitwaghchaure** [comment]
Hi @Olawale1 

Kindly add the path details in the custom sidebar menu of the portal settings

![screen shot 2017-04-26 at 2 44 39 pm](https://cloud.githubusercontent.com/assets/8780500/25427107/20228a40-2a8f-11e7-9cc5-8a0a5960e6f2.png)

**Web Form's View**
![screen shot 2017-04-26 at 2 46 51 pm](https://cloud.githubusercontent.com/assets/8780500/25427124/372440f8-2a8f-11e7-9629-76e5128c17e8.png)

**Comment by Olawale1** [comment]
Thanks for the clarification @rohitwaghchaure 

I'm closing this now. Kindly help look into the issue with Forms linked to custom doctypes. I've responded to your query on that ticket

Thanks again
