### ISSUE TITLE
Improving Workstation Operation Times

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#8576]
Operations should have Operation Time or Setup Time the difference is that for example machine preparation takes 30 minutes regardless if the quantity is 1 or 1000 pieces so the actual cost is determined based on the production order batch size. Any operation should have the ability to have a Setup Time and an Operation Time.

- [ ] Add field ```Setup Time``` in Workstation
- [ ] Calculate ```Total Operation Time``` in ```Production Order``` based on ```Setup Time``` + ```Operation Time``` * Quantity

**Comment by bcornwellmott** [comment]
This is a good idea!

The one thing I'd add is that there is currently a field in Manufacturing settings that adjusts the amount of time between operations. Do we want to change this field at the same time?

**Comment by sharmanakul** [comment]
@dottenbr has there been any development of this?
