### ISSUE TITLE
Add item to list

### ISSUE THREAD

**Issue by laugustos** [frappe/erpnext#8581]
Hello, how can i add an item to this list? Im trying create a new doctype, but this is not working...
(i cleaned my cache to do the tests)
![sem titulo](https://cloud.githubusercontent.com/assets/28024217/25412730/4f7784c4-29fb-11e7-820f-cdf55229997e.png)

**Comment by umairsy** [comment]
Clicking on + Criar um(a) novo(a) Dcotype will take you to form of creating new document on that DocType. Can you please explain your issue with an example, so that we can support you better.

**Comment by PawanMeh** [comment]
@laugustos, Kindly post questions on [discuss](discuss.erpnext.com) so that a more wider audience can reply to your question.
