### ISSUE TITLE
Price list Zero Increment

### ISSUE THREAD

**Issue by sarunsam** [frappe/erpnext#8582]
In my ERP the prices entered in the item price list is showing lot of zero increment after the latest update.Please fix it.

**Comment by nabinhait** [comment]
This has been fixed in the latest version. Please update and check again.

**Comment by sarunsam** [comment]
Hi 
Thank you. Usually when i open the erp it get updated automatically.

Could you please tell me how to update manually.

**Comment by nabinhait** [comment]
If you hosting with frappe cloud (erpnext.com), then we have updated your instance few hours ago. And there is no option to update manually, we always push all required fixes on priority basis. Just report via support@erpnext.com, if you found any issue.
