### ISSUE TITLE
Login to desk

### ISSUE THREAD

**Issue by hithamIsmail** [frappe/erpnext#8587]
After new update to V8 i can't login to my account from PC but i can login from mobile Erpnext Application . Can you help me to solve this problem . Thanks in advance

**Comment by nabinhait** [comment]
What is the error you are getting? While on login page, refresh the browser using Ctrl + Shift + R and try again.

**Comment by porrello** [comment]
It can be better just to delete your browser history, then refresh

**Comment by hithamIsmail** [comment]
thanks for your help it working now . it was cash problem 👍
