### ISSUE TITLE
v8.0.19 ERPNext Hosted (Free), Website Module: /products page returns 404 Not Found

### ISSUE THREAD

**Issue by moppidoo** [frappe/erpnext#8589]
Hi,

As title, on a new setup through the wizard, on the website frontend (not the desk) either click on the default link for Products on top bar or "View All Products" button returns a page not found error for the /products route.

Best Regards,

**Comment by lasalesi** [comment]
Hi moppidoo,

as a quickfix, you can go to Explore > Website >Website > Create a new website, then call it products and fill content. The page will show up (don't forget the publish checkbox).
However, I agree this should be there by default.

Best regards

**Comment by jwrober** [comment]
This is by design. You need to add items to the database and set which ones go to the website. Please open a discussion on this subject in the forum - https://discuss.erpnext.com/ for more help.
