### ISSUE TITLE
Pricing rule not effected while selecting different UOM

### ISSUE THREAD

**Issue by mfazilp** [frappe/erpnext#8592]
- I need to give 5% discount for every box purchase from my standard selling rate.

I added pen as a item with unit  Nos. 
Added another UOM 'box' with convertion factor 10.

Created pricing rule for item Pen - 5 % discount for min qty 10.
When i select UOM as box while creating sales invoice, pricing rule discount is not applying.

**Comment by mfazilp** [comment]
hi Can any one help

**Comment by PawanMeh** [comment]
Please refer to the following [link](https://frappe.github.io/erpnext/user/manual/en/accounts/pricing-rule), also in future please post such queries on [discuss](discuss.erpnext.com)
