### ISSUE TITLE
v8.0.18 Administrator cannot create new report/modify existing ones

### ISSUE THREAD

**Issue by sburanaw** [frappe/erpnext#8594]
After bench upgrade from v7 to v8, everything else works fine but it seems administrator doesn't have any permissions on the report anymore.

Not sure if this helps or not:

json from URL: "doctype=Report&with_parent=1&cmd=frappe.desk.form.load.getdoctype&_=...." contains "user_permissions":{}

Please let me know if you need more debugging info.

Thanks!

**Comment by PawanMeh** [comment]
Have you tried setting developer_mode = 1?
