### ISSUE TITLE
 Responsive web form 

### ISSUE THREAD

**Issue by shenoshadow** [frappe/erpnext#8596]
Dears 
according to my discussion here

https://discuss.erpnext.com/t/responsive-web-form/22916
i am looking for let the web form become responsive
i hope that some body can guide me 

thanks a lot

**Comment by revant** [comment]
I'm not able to replicate this issue.
![1](https://cloud.githubusercontent.com/assets/1040161/25554757/2857e3de-2cf3-11e7-806d-b965044a06f6.png)
![2](https://cloud.githubusercontent.com/assets/1040161/25554758/2e301114-2cf3-11e7-98d8-dde8903a8c65.png)
Check the text you added in introduction, it might contain html tags which might be causing the problem.

**Comment by shenoshadow** [comment]
Now i remove the introduction and every thing 
the result is same

**Comment by joezsweet** [comment]
@shenoshadow it seems you changed styles, can you confirm?

**Comment by shenoshadow** [comment]
i remove the introduction text but its still not responsive

**Comment by joezsweet** [comment]
Closing now, please reopen if needed
