### ISSUE TITLE
Shipping address formatting error on Purchase Order

### ISSUE THREAD

**Issue by cgpurbaugh** [frappe/erpnext#8603]
When creating a new purchase order, the zip code and other info of the address shows up intermittently.  Please see gif below
![purchase order error](https://cloud.githubusercontent.com/assets/13136405/25490870/31963800-2b3c-11e7-8dcf-974cc8ca0e7f.gif)

**Comment by MCD-50** [comment]
Can you tell me steps to reproduce this bug?

**Comment by cgpurbaugh** [comment]
@MCD-50 Metalcraft, Inc. is set to be our shipping address.  When the PO is loaded, it sometimes formats correctly, most of the time incorrectly.  That's what you are seeing in the GIF above.

**Comment by pratu16x7** [comment]
Unable to replicate as of now:

![address](https://cloud.githubusercontent.com/assets/5196925/26119113/c73bc5bc-3a89-11e7-95f0-3954cc39ab4c.gif)

**Comment by MCD-50** [comment]
Please provide steps to reproduce this error?

**Comment by cgpurbaugh** [comment]
Looks like this has been fixed.

**Comment by MCD-50** [comment]
Ok. Reopen if you face this problem again.
