### ISSUE TITLE
Custom Print Format - Purchase Order Items Table

### ISSUE THREAD

**Issue by opsninja1** [frappe/erpnext#8604]
Purchase order item table will not show Supplier Part Number or Brand.
![capture](https://cloud.githubusercontent.com/assets/21339160/25497267/a1a05f2e-2b49-11e7-9ba8-0b6cb04453eb.PNG)
![capture1](https://cloud.githubusercontent.com/assets/21339160/25497269/a43179c6-2b49-11e7-97e3-d345a641557c.PNG)

**Comment by chdecultot** [comment]
Hi opsninja,

I tried to reproduce your issue it worked fine on my end with the Brand name on ERPNext v8.0.20:
![image](https://cloud.githubusercontent.com/assets/4903591/25580918/afd87a0c-2e84-11e7-98c0-76fc8f28354a.png)


Can you make sure that you have the latest version of ERPNext and that your article master data are correctly filled in ?
In any case 5% are maybe to small for the data to be displayed correctly also.

I'm closing this issue.

Thank you for your understanding.

**Comment by opsninja1** [comment]
This is not fixed!  I have a hosted version of ERP, the item master date is correct, and 5% is large enough.  I never had a problem with this print format until the update.  Please fix it, don't just gloss over it and move on.

**Comment by chdecultot** [comment]
Hi @opsninja1 ,

Sorry for the confusion, I am not trying to move over this issue, just to help the Frappe Team classify the issues.

Since it is working fine on my end with the latest version I will reopen your issue and tag the Frappe Team so they can update your account.

Sorry again!

**Comment by opsninja1** [comment]
Thank you for reopening.  I have tried everything I can possibly think of on my end, and I just do not know where to go from here.

**Comment by mbauskar** [comment]
@opsninja1,

Tried to replicate the issue on my test account and it worked fine. Please find the below screenshot

<img width="1155" alt="screen shot 2017-05-04 at 6 43 39 pm" src="https://cloud.githubusercontent.com/assets/11224291/25705188/17e5df28-30fa-11e7-91da-9b613224aa9f.png">
<img width="1167" alt="screen shot 2017-05-04 at 6 46 55 pm" src="https://cloud.githubusercontent.com/assets/11224291/25705191/197234c2-30fa-11e7-9e84-b616a2d70175.png">

Did you uncheck the `Print Hide` option from Customize Form? if not please uncheck the property reload and check again.

<img width="752" alt="screen shot 2017-05-04 at 6 51 57 pm" src="https://cloud.githubusercontent.com/assets/11224291/25705406/cf0440dc-30fa-11e7-93c8-7f6d136113c2.png">

**Comment by opsninja1** [comment]
Did you uncheck the Print Hide option from Customize Form? if not please uncheck the property reload and check again.

----Where do I find this?

**Comment by opsninja1** [comment]
Sorry, rough morning here.  I went into Customize Form for Purchase Order Item and I unchecked Print Hide for Brand and Supplier Part Number.  Now it is giving me this....

![capture](https://cloud.githubusercontent.com/assets/21339160/25706633/9bf02282-30a6-11e7-8825-fe5dbdea239d.PNG)

Here are the settings for Supplier Part Number.  Brand is the exact same.

![capture1](https://cloud.githubusercontent.com/assets/21339160/25706658/a8a71db4-30a6-11e7-86a4-100d77d41f91.PNG)

![capture2](https://cloud.githubusercontent.com/assets/21339160/25706669/ac363712-30a6-11e7-800f-b60864bd9c6b.PNG)

![capture3](https://cloud.githubusercontent.com/assets/21339160/25706675/b00cc9a0-30a6-11e7-8648-fca4f167d0fd.PNG)

**Comment by opsninja1** [comment]
Now I cannot click on "Select Columns" for the Items (Table) under customize print format.

**Comment by opsninja1** [comment]
I really need this issue fixed ASAP.  I am going on a week now of not being able to print my purchase orders......

**Comment by opsninja1** [comment]
After playing around with the item table columns, I have found that seems to be related to my issue.

For some reason, the supplier part number nor the brand can be column heads.  Meaning they will show up under Description if I select it, but will not create a column of their own.

Shown below is what I have now, and what I used to have.  They are close, but not really what I am looking for.  The product Description is not necessary, as this is a purchase order.  Any ideas?

WHAT I CURRENTLY HAVE:
![capture](https://cloud.githubusercontent.com/assets/21339160/25852444/f7466cf4-348e-11e7-9e0f-d5e38f1a28ac.PNG)
![capture1](https://cloud.githubusercontent.com/assets/21339160/25852620/955bf684-348f-11e7-9682-853cb02f3735.PNG)



WHAT I USED TO HAVE:
![capture2](https://cloud.githubusercontent.com/assets/21339160/25852455/02ff126c-348f-11e7-8b38-648cb3744739.PNG)

**Comment by mbauskar** [comment]
@opsninja1,

You can set the `Print Hide` Property for the description field if it is not required. If you wish to switch to old grid view in the print format please uncheck the `Compact Item Print` in `Print Settings`

<img width="1175" alt="screen shot 2017-05-15 at 2 16 48 pm" src="https://cloud.githubusercontent.com/assets/11224291/26049716/96e5a074-3979-11e7-810b-db2b5282e21f.png">

**Comment by opsninja1** [comment]
That did it!  Thank you so much for helping me fix this issue!

**Comment by akshaychordia** [comment]
I am facing a similar type of issue but in sales invoice item table. 

> I have a custom field created in **doctype - item** by the name of **" customer drawing number "**. (it has a field name of customer_drawing_number). 

> I am trying to get this data in sales invoice item table, for which I have created a  custom field under **doctype - sales invoice item** which fetches this data from item doctype by using item.customer_drawing_number.

> I have disabled hide print

> I have added the item in the table by checking besides it in print format

>  after doing all the above steps there is still no display of values upon preview of print.


PS.

I have added the value of " customer_drawing_number" in a variant of the item and not in the actual item (now template) itself
