### ISSUE TITLE
Cost center in salary structure

### ISSUE THREAD

**Issue by gemegeme** [frappe/erpnext#8607]
Hello,

We have already checked the new updates and it's good but we would like cost center to be in salary structure not process payroll.

Thanks

**Comment by PawanMeh** [comment]
@gemegeme Could you elaborate with screen shots on the issue

**Comment by mhbu50** [comment]
+1

**Comment by gemegeme** [comment]
I sorry for delay due to travel.
Please find the attached file

![cost center](https://cloud.githubusercontent.com/assets/24754654/25887798/619735be-3518-11e7-927d-12e414980c7a.jpg)

**Comment by vishdha** [comment]
Salary structure won't generate Journal voucher you create journal entry after submitting Salary slip.

**Comment by vishdha** [comment]
@gemegeme 
Can you elaborate a problem statement for cost center in a Salary Structure?

**Comment by gemegeme** [comment]
We have operations and maintenance projects so
I need cost center in salary structure to download every project with it's own expenses.

Thanks
