### ISSUE TITLE
Fleet Management app in the ERPNext core

### ISSUE THREAD

**Issue by cyberdee** [frappe/erpnext#8613]
Dear All,

Is it possible to include Fleet Management app in the ERPNext core?

Thank you

**Comment by revant** [comment]
`Vehicle` and `Vehicle Log` doctypes are already part of ERPNext.
You can find them under Human Resource in v8.0

**Comment by vastris** [comment]
If you want to include fleet management app in the ERPNext core, you will need to consider the type of app, the features, and the development process. You can find more information about these aspects in this article: [Fleet Management App Development: How to Build a Fleet Management Solution](https://www.cleveroad.com/blog/fleet-management-app-development/).
