### ISSUE TITLE
Problem in publishing Item on the website, if Item has special characters

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#8616]
Based on Issue #WN-SUP24170

I have been setting up a website https://lestroisdudomaine.erpnext.com/. Items not being displayed on the website.

The item code field does not support certain accented letters “É”, “È”, etc. when input using html codes &Eacute; and &Egrave;

I have deleted all items which had the unavailable stock issue and noticed a pattern in the item code names, once corrected the stock appears.

I have managed to work around the issue and the accented characters are displaying correctly, please see https://lestroisdudomaine.erpnext.com/all-item-groups/consumable/vins-rouges/france/chacirc;teau-cap-de-faug%C4%8Dres-2009

I may be wrong but what I have noticed is that accented characters converted to html are correctly imported (“&Egrave;” È) but exported as ASCII “Ãˆ” and this creates a conflict between the Item Code and the Item ID name, if both use the same code as highlighted below then the conflict is gone and the stock is displayed correctly: 

Accented characters (html) when I imported the items:

![screen shot 2017-04-28 at 6 24 35 pm](https://cloud.githubusercontent.com/assets/910238/25529506/fabfb392-2c3f-11e7-88d6-fa3bcb2bd2da.png)

After correcting the names and exporting the data the accented characters show as:

![screen shot 2017-04-28 at 6 24 41 pm](https://cloud.githubusercontent.com/assets/910238/25529510/0a55cfa8-2c40-11e7-8d7a-39570f9c8529.png)
 
I hope this helps in your investigation, I had noticed the issue before when entering contact names for customers, the accented letters show fine on the UI but once you export the data these show as garbled text and make the import fail unless you correct the garbled characters back to what they should be and import again.

**Comment by KanchanChauhan** [comment]
HTML entities should be used instead of accented characters.

**Comment by umairsy** [comment]
Should have I been able to replicate issue in this cycle?

![item1 1](https://cloud.githubusercontent.com/assets/910238/25615952/be4330ea-2f57-11e7-9769-474d9392ffea.gif)

I have closed issue on frappe.erpnext since email thread that become very long. Lets continue discussion on this issue here.

**Comment by KanchanChauhan** [comment]
I am not able to replicate it either.

**Comment by KanchanChauhan** [comment]
Closing it since it is not an issue.
