### ISSUE TITLE
POS Interface gets distorted when a new Customer is created

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#8620]
Hi,

The POS interface gets distorted whenever a new Customer is created. Steps to replicate:

1. Open POS page and click in the Customer field
2. Click on 'Create a new Customer'
3. Fill in Customer details in dialog box and Save

An example of what happens is shown below

![pos interface issue 1](https://cloud.githubusercontent.com/assets/9269337/25537589/06d3cef6-2c37-11e7-8fac-0244e459628e.png)

Many times it's even worse with the Item grid moving to the left side of the screen and the keypad not getting displayed

Please help resolve

Kind regards

**Comment by vrms** [comment]
can't reproduce (using my laptop). Does the issue still exist on your end?

what kind of device are you using?

**Comment by Olawale1** [comment]
Hi @vrms 

Yes the issue still exists. I'm using a Windows 10 laptop but the device isn't the issue because I've tested it on several different laptops. As you can see from my screenshots, the issue is happening even on demo.erpnext.com which I believe is on the latest version

I also tried it on multiple browsers and the issue is still the same! Please find below:

Google Chrome:

![pos interface issue 1](https://cloud.githubusercontent.com/assets/9269337/25577567/e7ac3fb6-2e5e-11e7-8c4e-405c14f73bbd.png)

Microsoft Edge:

![pos interface issue 2](https://cloud.githubusercontent.com/assets/9269337/25577582/00f888d0-2e5f-11e7-8d4d-3fd998578d6a.png)
