### ISSUE TITLE
Email id must be unique, Email Account is already exist for user@company.com

### ISSUE THREAD

**Issue by imllc** [frappe/erpnext#8624]
email errors with update:

ERPNext: v8.0.20 (master)
Frappe Framework: v8.0.27 (master)

https://discuss.erpnext.com/t/what-changed-email-stopped-working-email-id-must-be-unique-email-account-is-already-exist-for-user-company-com/23169/5?u=imllc

**Comment by BradMK** [comment]
Upgraded from 8.0.19 to 8.0.20 and having the same issue.

**Comment by BradMK** [comment]
Looks like it was an issue with frappe, seems to be fixed with this commit https://github.com/frappe/frappe/commit/7febef2e629ac900055ca6914410aec255be1ede.

Just updated seems to be working, although still get an error when trying to add an account from the Email inbox directly.

**Comment by joezsweet** [comment]
Closing now, please reopen if problem will be back.
