### ISSUE TITLE
Kanban Board - Required browser refresh for updating values

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#8626]
Reported by customer via WN-SUP24633. Also replicating in https://indiaissecularstate.erpnext.com/desk#List/Purchase Order/Kanban/PO Status

Steps:

- Had a Purchase Order in Draft stage.
- I opened draft PO from Kanban Board and submitted it manually. Please note that I didn't submit PO from the Kanban Board itself.
- When I checked Kanban Board again, PO is shown in the Draft column only.
- Refresh list view doesn't help as wel.
- Refresh browser tab updates values correctly.

**Comment by vrms** [comment]
I confirm that you need to refresh the browser in order to update kanban ... 

problem: you loose Filters with the browser refresh. so that's a catch 22. You need to refresh the browser in order to apply the filter, but loose the filter while doing so
