### ISSUE TITLE
custom print format js cant print

### ISSUE THREAD

**Issue by kankankuli** [frappe/erpnext#8627]
hi,

i create 1 item (ITEM ABC PRICE 100 ITEM TAX SET SALES TAX 5% )
i create another one item (ITEM XYZ PRICE 100 ITEM TAX SET SALES TAX 10% )
price included sales tax
use pos make sale invoice
make custom print format type js
first column is item name item rate and item qty
second column is sales tax
third column is amount

i use {{ item.item_tax_rate }} output is {"SALES TAX 5% ‐ T":5} and {"SALES TAX 10% ‐ T":10} i want it display 5% and 10%

(please check my attachment) 
i refer http://jinja.pocoo.org/ i can use this code to convert it.

{%- if item.item_tax_rate == '{"SALES TAX 5% ‐ T":5}' -%} 5% {%- else -%} 10% {%- endif -%} 

but it can not print.

i dont know is bug or print format limitation
 
how to change the code to make it work?

![pic11](https://cloud.githubusercontent.com/assets/16223196/25553665/d167102e-2ceb-11e7-9319-0b288a403d4d.jpg)

**Comment by vrms** [comment]
this seems to be more suitable to be put as a topic in the [Forum](http://discuss.erpnext.com). I'm closing the issue for now. whether it turns out it actually **is** a bug, we can reopen it any time
