### ISSUE TITLE
Can not see attributes in Variant Item

### ISSUE THREAD

**Issue by ci2014** [frappe/erpnext#8635]
Hello there,

because of this code, which seems to be recently added

eval:doc.has_variants && doc.variant_based_on==='Item Attribute'

in Customize Form of Item, it is not possible to see the attributes of variant items. When I remove it, it's correct.

**Comment by vrms** [comment]
you seem to have the solution for this issue (which I can't comment on due to not being a developer) ... can you prepare a PR? and link it to your issue?

That'd be the most efficient way to get this solved (if the fix is working and not breaking anything else) I think,

**Comment by ci2014** [comment]
@vrms "if the fix is working and not breaking anything else" For me it didn't break anything, but that's the question.

Maybe there was a reason that this code has been implemented. If not, of course I can try to create a PR.
