### ISSUE TITLE
Subject in Standard Reply

### ISSUE THREAD

**Issue by Devens** [frappe/erpnext#8637]
Upto V7 subject of "Standard Reply" was mentioned as Document Number (it was different from "Standard Reply Name". From V8, it started to fetch subject from Standard reply Name. "Subject" of standard reply and name of "Standard Reply" are two different things. It should be separate field. 

For eg. Name of Standard reply can be something short (as it is to be selected from so many standard replies) or something like - "PO Send". But, we would not like to send PO Email with subject "PO Send".

Moreover, when Doc Number was kept  in subject, it was easy to search in email Inbox also.

**Comment by pratu16x7** [comment]
fixed via: frappe/frappe#3211
