### ISSUE TITLE
Faulty implementation of 'Create a new Customer' feature in POS (Critical)

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#8642]
Hi,

When you create a new Customer from the POS screen, you have the option to add contact details (phone number, email address, physical address) which is a very important feature. There are however some critical flaws:

1. All the aforementioned contact details only get mapped to the Address child table
2. If only the Contact Number and Email ID fields are filled while creating the Customer (which is the most common practice), that information gets discarded! It doesn't get saved anywhere!!

-The Contact Number and Email ID fields should get mapped to the Contact child table. The name of Contact should be same as Customer Name

-The Address fields should get mapped to the Address child table. Email ID and Contact Number may be copied here as well

-The information should always get saved in the appropriate child tables as described above rgardless of whether one part is filled or not. Right now, there are people using the ERPNext POS in production environments where it is most common to only capture the Customer's Phone Number (and maybe Email Address) but they will have a rude shock when they discover that all the information they think they're capturing is actually lost!

Please fix this urgently

Also, I just discovered that the Customer field is not searchable by Phone Number or Email ID! Will create a separate issue for this

Kind regards,

**Comment by strixaluco** [comment]
Can replicate on current beta.erpnext.com.

ERPNext: v8.0.0-beta (1117125) (develop)
Frappe Framework: v8.0.0-beta (73af73c) (develop).

@Olawale1, thanks for reporting and please try to follow the [contribution guidelines](https://github.com/frappe/erpnext/wiki/Issue-Guidelines).

**Comment by Olawale1** [comment]
Thanks @rohitwaghchaure , great job
