### ISSUE TITLE
Customer Field in POS should be searchable by Phone and Email ID

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#8645]
Hi,

As stated in the subject, Customer Field in POS should be searchable by Phone and Email ID

Thanks

Kind regards,

**Comment by joezsweet** [comment]
https://github.com/frappe/erpnext/wiki/Issue-Guidelines

**Comment by Olawale1** [comment]
Hi @joezsweet 

Could you please explain why you referenced the guidelines?

Kind regards,

**Comment by adityaduggal** [comment]
@Olawale1 Issue #8644 raised by you is similar to this one and hence I would request to close this issue.

**Comment by Olawale1** [comment]
Hi @adityaduggal 

Thanks for your feedback but they are not the same issue. 8644 deals primarily with being able to add fields from child tables in Search Fields generically. This does not address the case of POS because Search Fields don't work in the POS screen by default. The POS has it's own separate rules

Maybe the mixup is because I referenced POS in #8644. I'll edit that so that it's clearer. I hope my clarification is sufficient. If so, please remove the 'Duplicate' tag

Thanks

Kind regards,

**Comment by Olawale1** [comment]
Hi @adityaduggal 

Kind reminder to please remove the duplicate tag on this issue

Thanks

**Comment by Olawale1** [comment]
Thanks @chdecultot

**Comment by Olawale1** [comment]
Hi @rohitwaghchaure 

It appears you've fixed this already. Thanks a lot! Please close this unless there's something you're still working on. It appears fine from my end though

Thanks again
