### ISSUE TITLE
Custom Print Format - Purchase Order Items Table 

### ISSUE THREAD

**Issue by opsninja1** [frappe/erpnext#8647]
Purchase order item table will not show Supplier Part Number or Brand in print view.

PLEASE DO NOT JUST GLOSS OVER THIS AND CLOSE IT LIKE THE LAST GUY!  THIS IS A MAJOR ISSUE, AS I CANNOT PRINT OUT MY PURCHASE ORDERS!  I am using a hosted version of ERPNext, so it is always up to date. The item master data is filled out correctly.  

![](https://cloud.githubusercontent.com/assets/21339160/25497267/a1a05f2e-2b49-11e7-9ba8-0b6cb04453eb.PNG)

![](https://cloud.githubusercontent.com/assets/21339160/25497269/a43179c6-2b49-11e7-97e3-d345a641557c.PNG)

**Comment by revant** [comment]
Previous Issue got open:
https://github.com/frappe/erpnext/issues/8604
