### ISSUE TITLE
Created Date time for Sales Order and PO

### ISSUE THREAD

**Issue by IT-GoodMorning** [frappe/erpnext#8648]
We need to record Date time format for Sales Order and PO. sometime we have argument the delay of process. So, we need to know the SO was created morning or evening to avoid argument. But current ERPNEXT cannot do this. I hope we can have this feature soon. Thanks.

**Comment by PawanMeh** [comment]
There is creation field present in the document, you can add that to reports to view this. Kindly raise such queries on [discuss](discuss.erpnext.com)

re-open issue, if there is something else you are looking for.

**Comment by IT-GoodMorning** [comment]
Yes. Maybe the "creation" field in database but it is invisible from customize for both form and report. Can you show me how to do it? Thanks.

**Comment by adityaduggal** [comment]
@IT-GoodMorning Post it on https://discuss.erpnext.com/ this is not a BUG or feature please read the https://github.com/frappe/erpnext/wiki/Issue-Guidelines no discussions should be there for questions please use forums for the same.
