### ISSUE TITLE
[FR] Pull Employee Data from Job Applicant

### ISSUE THREAD

**Issue by lxnow** [frappe/erpnext#865]
Map fields from Job Applicant into Employee data. Some fields will not be relevant so will be exclusive to Employee doctype (such as appraisal), but most such as work background, government information, birthday, etc. can be filled up at the Job Applicant level.

The intention is to save on paper entirely for applicants who still have to fill out a paper form and needs to be re-encoded into an HR system.

**Comment by vjFaLk** [comment]
Fixed.
