### ISSUE TITLE
Safari, mac os, dashboard not showing, no access

### ISSUE THREAD

**Issue by gostf2** [frappe/erpnext#8658]
when signing in with Safari on Mac oS 10.9.5 the only thing shown on the page is the "E" icon in the middle of the page, no other links, nothing. This way you can't access the account or any other function of the page

**Comment by netchampfaris** [comment]
What version of Safari are you running? Updating it to the latest version will most probably solve the issue.

**Comment by Priyanka-IAS** [comment]
Same problem here with Safari. Cannot get past the E. Any amount of refresh and clearing the cache is not helping. Problem started with upgrade to Version 8

**Comment by ishanloya** [comment]
The current version of Safari is Version 10. Version 8 support ended in 2015/16 I think. Maybe this is why you are facing issues.

**Comment by strixaluco** [comment]
I think @Priyanka-IAS means v8 of Frappe/ERPNext. 

@gostf2, @Priyanka-IAS, it's hard to make any assumptions when you don't provide any additional information about your environment. What are exact versions of Frappe, ERPNext and browsers that you are using?

FYI, macOS 10.9.5 received last updates more than 1 year ago

**Comment by jwrober** [comment]
Please open a discussion on this subject in the forum - https://discuss.erpnext.com/ - to get more help with this and set context. If a bug is discovered a new issue can be opened.
