### ISSUE TITLE
Payment Entry Returned

### ISSUE THREAD

**Issue by adityaduggal** [frappe/erpnext#8659]
Use case:
When we do a payment entry for receipt of payment, then usually the entry is adjusted against outstanding invoices. Now if incase the cheque is RETURNED then we have to cancel the existing payment entry and UN-ALLOCATE it so that it can be adjusted against the RETURN entry.

Ideally what should happen, is that we should have a button on a payment entry and click on RETURN so it should create a REVERSING ENTRY for that Payment entry and all the allocations for Sales Invoices should be replaced with the entry so that there is no need to cancel the payment entry.

**Comment by ai-erp** [comment]
I Agree with you @adityaduggal . In the same way there should also be redeposit button as there are also cases wherein the cheque will be redeposited again(once funded, etc.).  

![payment-journal entry - return-redeposit cheques](https://cloud.githubusercontent.com/assets/16744099/26153729/da22c20e-3b1d-11e7-9ecc-785cc81bf78a.jpg)

In our case, for now, what we do when there is returned cheque is that we do not cancel the previous payment entry but instead we are making another Journal entry booking receivable for the customer for the same amount of cheque returned and when customer paid again, we then make another journal entry closing the receivable booked from the returned cheque.

This will allow us to make bank reconciliation having this returned cheque reflected.

**Comment by tundebabzy** [comment]
This is a useful feature

**Comment by creamdory** [comment]
In addition to this, I believe there should be a feature to record bounced check penalty that should be re-reimbursed by the paying company (in our country's case, banks gives penalty for bounced check).

**Comment by tundebabzy** [comment]
I'm implementing this using @ai-erp workflow.

**Comment by jk2081** [comment]
@tundebabzy I believe the PR has to be reopened. Can you please provide an update on this issue?

**Comment by tundebabzy** [comment]
I'm thinking of a better design. The Journal Entry approach means that the Payment Entry has to make a best guess to determine if the user can initiate the payment return options.

**Comment by kfcspl** [comment]
Hi Is Cheque bounce feature updated in ERPNEXt live which version as cant find, this is basic feature and missing i am not able to do receipted cheque bounced as reversal entry no option in 12.10

**Comment by harshit-30** [comment]
Please create another issue if it is replicable after v13.10.
