### ISSUE TITLE
Custom Report - Not updating after V8 Update

### ISSUE THREAD

**Issue by opsninja1** [frappe/erpnext#8670]
I have a custom receiving report that will not show any items received since 4/28.  I have a hosted account.

![capture](https://cloud.githubusercontent.com/assets/21339160/25666710/e90940aa-2fe6-11e7-96d7-49eb2f350ae7.PNG)

![capture1](https://cloud.githubusercontent.com/assets/21339160/25666754/07189186-2fe7-11e7-8736-e32597ccfac0.PNG)

**Comment by jwrober** [comment]
Please open a discussion on this subject in the forum - https://discuss.erpnext.com/ to get help with this issue. I have a ton of custom reports that work fine after upgrade.
