### ISSUE TITLE
Negative values in balance sheet

### ISSUE THREAD

**Issue by sp9leo** [frappe/erpnext#8672]
Don't know if this is a change in new version or a bug.
In previous version balance sheet report showed actual values, in latest version  values are shown as negative values.  

V8.0.10
![image](https://cloud.githubusercontent.com/assets/15377465/25683285/b85a0a96-305b-11e7-97ed-0460611967de.png)

V 8.0.21
![image](https://cloud.githubusercontent.com/assets/15377465/25683293/c3325a86-305b-11e7-9824-51dd2eba6f64.png)

**Comment by nabinhait** [comment]
We have released a potential fix. Can you please check again?

**Comment by sp9leo** [comment]
It is fixed after update. Thanks.
