### ISSUE TITLE
Healthcare Module Cleanup

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#8677]
- [x] Consultation
  - [x] Appointment
  - [x] Modal based Appointment Booking
- [x] Merge Appointment, Service unit appointment -> Patient Appointment
- [x] Merge all settings
- [x] Billing for patient
- [x] Remove spaces in naming series
- [ ] Medical terms loaded in complaint
- [x] Rename Duration -> Drug Prescription Duration
- [x] Remove Routine Observation / Service Task
- [x] Facility / Zone (Removed)-> Merge to Location (coming soon)
- [x] Rename Procedure -> "Clinical Procedure" - Removed
- [x] Module Groups 
   - Laboratory
   - Consultation
   - Patient Management
   - Inpatient (coming soon)
   - Setup
- [x] Healthcare Settings
  - [x] Remove Bold Headings
  - [x] Patient Naming By - Patient Name, Naming Series
- [x] Segregate fields into sections (Patient, Physician)
- [x] Remove Referring Physician
- [ ] Demo data

**Comment by sathishpy** [comment]
In my opinion it makes more sense to start capturing the requirements/usecases first and then map them to design/implementation tasks/issues. It gives a clear picture as what needs to be achieved and why it needs to be achieved. Opening that allows domain experts to give their opinion on the feature being implemented. For example, appointment module has following requirements
1. Provision to book an appointment by date/time: Patients who need health service on a specific date are fine with any physician/doctor available who can treat them
2. Provision to book an appointment by date/time and Doctor: Some patients are very particular about the doctor for their treatment for various reasons
3. Ability to handle patients who come to clinic/hospital without appointment: This is quite important for Indian clinics where not everyone is going to take an appointment before visiting doctor. It could be a case in other countries as well for emergency visits. In those cases, the patients will need to get an adhoc appointment though the doctors schedule is already full. The appointment system should be intelligent enough to accommodate them without impacting the scheduled appointments adversely.
4. Provide a way to capture patients waiting time. Though not directly related to appointment booking, this is an extension of the appointment usecase. The primary reason behind appointment is to reduce the patient waiting time. It shouldn't be misused by patients coming late and going straight to consultation. Normally it is handled by patients 'checking-in' to the consultation. That time and their scheduled appointment time would give good insights to the appointment system to come up with good patient waiting list queue.
It is very likely that there will be more to it. Capturing them early on and possibly prioritizing them will help in designing/implementing the same.

**Comment by akurungadam** [comment]
+1 for 
> patients 'checking-in' to the consultation

Also, self service appointment screen would also be good. Having the time slot definitions in the new design should help in implementing this. 

Also, adhoc appointment booking should be possible by overriding the scheduler.

**Comment by vladucoju** [comment]
+1

**Comment by rmehta** [comment]
Merged. Please claim the bounty 👍
