### ISSUE TITLE
Custom Translation should update value in between. Currently it only works for whole string

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#8681]
Example:

Sales Invoice has Amount in Words as: INR Five Thousand, Seven Hundred And Seventy only.

I have created Custom Translations in Urdu like this.

![screen shot 2017-05-04 at 12 47 37 pm](https://cloud.githubusercontent.com/assets/910238/25693992/d66e3cd2-30c9-11e7-9246-d71cb0a168b4.png)

As discussed over https://discuss.erpnext.com/t/customize-in-words-amount/23366/2, translation will only get update if translation was added for " INR Five Thousand, Seven Hundred And Seventy only" at once.

As expected, it should also update translation for the value in between like One, Hundred, Only separately.

**Comment by mhbu50** [comment]
+1

**Comment by abdufarag** [comment]
+1

**Comment by wyrm3535** [comment]
Is there any update on this issue? it will be a major fix that we are seeing in our current environment
