### ISSUE TITLE
Don't show empty warehouses in Item Dashboard

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#8684]
We move item batches from and to many warehouses. All of the warehouses a batch has ever been in will show in the Item dashboard.

- [ ] Only show Warehouse in Item dashboard if there is an active demand against them in sales or production order or if there is stock in them

![photo_2017-05-04_11-02-41](https://cloud.githubusercontent.com/assets/9136094/25694854/53ab9d68-30b9-11e7-8750-1b801bee49fc.jpg)

In this example 1–6 would not be shown and only 7 and 8 would show.

**Comment by joezsweet** [comment]
Probably is not needed  item code (Item name) display as well, user is looking at item details

**Comment by tundebabzy** [comment]
I believe some users will favor the default behavior for audit purposes. Perhaps we can leave the default behavior and  add an option to hide empty warehouses? @rmehta @nabinhait
