### ISSUE TITLE
Unlinking of URLs in editor doesn't work

### ISSUE THREAD

**Issue by villiger** [frappe/erpnext#8686]
When I unlink a URL in the new editor and then hit save it reappears as a link again. See the attached screenshot. It seems as if the editor automatically transforms everything that looks like a URL into a clickable URL. But this behaviour should not occur, especially not if I just unlinked the URL in the editor manually. Same if I switch the editor to HTML and do it that way, it reappears after saving again.

![Screenshot](https://cloud.githubusercontent.com/assets/347878/25697759/88a47a8c-30bc-11e7-9b83-083f25469236.png)

**Comment by ericmoon** [comment]
Does anyone have a workaround?  I'm trying to print an invoice and the html link makes the url show twice on the printout

**Comment by tundebabzy** [comment]
Hello, 
Please give me steps to reproduce the issue. Unlinking links is working for me. Also, please add the version you're working with
