### ISSUE TITLE
Salary structure lacks Up to / Maximum in any formula.

### ISSUE THREAD

**Issue by parmartejas** [frappe/erpnext#8687]
Hello Team,

We are using Salary Structures created in Ver 6 till day.
The New concepts of Ver 7 Salary Structure like Conditions & Formula, adding multiple employee in a single structure etc. are awesome at their vision. But we have some stringent requirements like some Earning Heads for e.g Conveyance Allowance is up to 1600 INR / Month, which is employee specific. It can be less than 1600 but not more than. When it is less than 1600 then it fits in Formula, but how to restrict formula in maximum up to etc.. Hence we have adopted individual Salary Structure for all employees. 

There must be some formula to restrict maximum amount at given condition etc.

**Comment by kennethsequeira** [comment]
Can be solved by using condition in the formula.
