### ISSUE TITLE
Company should always be user's default company

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#8690]
We have a multi-company setup in one site, whenever people create transactions (stock entry, sales order, production order) they need to select the right company. The company field is sometimes very visible (sales order) and sometimes very hidden (production order).

- [ ] Add ```Default Transaction Company``` for ```User```
- [ ] On creation of transactional doctype select ```Default Transaction Company``` from user

**Comment by nabinhait** [comment]
@dottenbr You can already do that using "User Permissions". Check https://frappe.github.io/erpnext/user/manual/en/setting-up/users-and-permissions/user-permissions
