### ISSUE TITLE
Ability to label doctypes

### ISSUE THREAD

**Issue by akurungadam** [frappe/erpnext#8693]
It would be nice to add a capability to add labels to doctypes based on the domain. For instance one can label the Sale Order a Pro-forma Invoice for the Services domain

**Comment by joezsweet** [comment]
you can use custom translations, have a look at `Custom Translations` in `Setup` module

**Comment by jwrober** [comment]
Please open a discussion on this subject in the forum - https://discuss.erpnext.com/ - for further assistance.
