### ISSUE TITLE
Address Type in the Shopping Cart. Two option to define Shopping Cart.

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#8694]
In the Address master, we have two field for the same purpose.

![screen shot 2017-05-04 at 6 37 13 pm](https://cloud.githubusercontent.com/assets/910238/25705031/74fc9db0-30f9-11e7-83bf-ebab80a0d26b.png)

In the Cart, Address is separate based on value selected in the Address Type field. So, even if I checked "Preferred for Shipping" in the address, but if it's Address Type is Billing (which is set by default), it will appear on the Billing Side.

Address master:

![screen shot 2017-05-04 at 6 44 26 pm](https://cloud.githubusercontent.com/assets/910238/25705183/113973ce-30fa-11e7-835b-4e362cd2c042.png)

How it renders in the Cart?

![screen shot 2017-05-04 at 6 46 11 pm](https://cloud.githubusercontent.com/assets/910238/25705189/1906b8aa-30fa-11e7-8d52-db502df84f72.png)

Since I checked Preferred for Shipping, I was expecting it on the left. But it categorized based on Address Type. Confusing!

**Comment by jwrober** [comment]
Related issue #4204 has been closed.
