### ISSUE TITLE
Error Message on Account Setting

### ISSUE THREAD

**Issue by hdtmartin** [frappe/erpnext#8695]
When I'm trying to save a setup in Account Setting, I get the following message and can no longer proceed:

"Account balance (0.00) and stock value (336,075.00) must be same"

Please help how to resolve.

Thanks!
![capture](https://cloud.githubusercontent.com/assets/26181150/25709151/20239286-311b-11e7-83d8-b207d1bac5e3.JPG)

**Comment by jwrober** [comment]
Please open a discussion on this subject in the forum - https://discuss.erpnext.com/.
