### ISSUE TITLE
Query_Report Issue in rtl mode

### ISSUE THREAD

**Issue by j209** [frappe/erpnext#8701]
There is an issue in slickgrid reports in rtl direction
![rtlissu](https://cloud.githubusercontent.com/assets/18129232/25734490/bc0a3206-3178-11e7-8950-83f47e783b53.png)

**Comment by jwrober** [comment]
@j209 would you please add more commentary to this issue?  What is the expected behavior you are looking for from the report?  Does this issue happen on any report or just he slickgrid one?

**Comment by mhbu50** [comment]
+1

**Comment by maysaa** [comment]
It is important for me also

**Comment by j209** [comment]
Closed due to PR https://github.com/frappe/frappe/pull/3506
