### ISSUE TITLE
PO FROM BOM DISCOUNTING EXISTING STOCK

### ISSUE THREAD

**Issue by SYMBARCELONA** [frappe/erpnext#8709]
We create the BOM FROM a parent item. First problem we face is that with Production Planning Tool the multilevel BOMs do not work.
We want to purchase the material, then we create a material Request but ALL items are shown, even when there is some in the warehouse. It should give the option to create a material request from BOM with all items or only the differece with the warehouse and other material requests,

Waiting your appreciate comments

**Comment by umairsy** [comment]
There has been quite a few updates in Production / Material Planning, which supports multi-level BOM as well. Do check the latest. If issue still persist, re-open the issue, with more specifics on the expectations vs current behaviour.
