### ISSUE TITLE
Moving task in gantt chart adds day to the end of task!

### ISSUE THREAD

**Issue by mineolatx** [frappe/erpnext#8715]
This issue was closed without being fixed. The guidelines say to "provide info and reopen it" but I haven't found a way to reopen the issue. One issue with the Gantt Chart has been fixed since Version 8 came out but this one has not and it makes the Gantt Chart useless. I was not using projects before Ver. 8 so I do not know if this was working before. I have been trying to get the Gantt Chart to work since Version 8 was released and no luck so far. Any help would be appreciated.

https://github.com/frappe/erpnext/issues/8531

**Comment by strixaluco** [comment]
@mineolatx, please don't duplicate the issue even if one was closed previously. Instead, just ask to reopen it. Let's get back to #8531
