### ISSUE TITLE
[BUG] Browser Freezes when opening Project Tasks (as Gantt)

### ISSUE THREAD

**Issue by paulator** [frappe/erpnext#8724]
#### Expected Behaviour
Opening project tasks should show the project tasks

#### Actual Behaviour
-Opening Tasks via Awesome Bar or via Project -> Document-Links -> Tasks forwards the browser to "https://my-hostname/desk#List/Task/Gantt"
After this the browser freezes and shows a greyed out screen without content.
The browser shows "Page is not responding" error message

I'm not able to change the view to a non-gantt view. This means, I'm stuck and can't open the task list.

![image](https://cloud.githubusercontent.com/assets/7262648/25783103/9eff51fc-3356-11e7-9bae-fd241b24bb47.png)

#### Steps to reproduce:
- Go to a project
- Create some tasks
- change to task-list
- switch to Gantt view

If I should deliver any other details, please let me know.

Frappe version: 
Frappe Framework: v8.0.36 (master)

**Comment by netchampfaris** [comment]
@paulator Can you post the JS console traceback here?

**Comment by paulator** [comment]
@netchampfaris : Sure, if you tell me how to do it. Currently my console doesn't show any errors. Can you give me instructions, how to do it?

Thx.

**Comment by paulator** [comment]
Some more details:
- I opened Chrome Task Manager and watched my ERPNext task. Its memory consumption is increasing to multiple GB. There seems to be a memory leak.
- When memory is full, the site stops working 
- During the execution I can stop JavaScript in DevTools and it seems to loop always on the same functions.


I can copy the call stack. Maybe this gives you any hint?

(anonymous) (VM444:formatted:768)
(anonymous) (VM444:formatted:767)
make_grid_ticks (VM445:formatted:547)
make_grid (VM445:formatted:458)
render (VM445:formatted:332)
change_view_mode (VM445:formatted:170)
init (VM445:formatted:126)
Gantt (VM445:formatted:842)
render_gantt (list.min.js:279)
render_view (list.min.js:279)
(anonymous) (list.min.js:276)
eval_assets (desk.min.js:formatted:123)
execute (desk.min.js:formatted:112)
frappe.require (desk.min.js:formatted:63)
load_lib (list.min.js:276)
(anonymous) (list.min.js:276)
render_view (list.min.js:148)
render_results (list.min.js:28)
callback (list.min.js:14)
callback (desk.min.js:formatted:1065)
200 (desk.min.js:formatted:1085)
(anonymous) (desk.min.js:formatted:1194)
i (jquery.min.js:2)
fireWith (jquery.min.js:2)
z (jquery.min.js:4)
(anonymous) (jquery.min.js:4)

**Comment by netchampfaris** [comment]
It is difficult to replicate without data. Can you provide your tasks data (in json) so that I can import here and try to replicate?

**Comment by paulator** [comment]
Of corse I will. How can I export the data in JSON format?

**Comment by netchampfaris** [comment]
@paulator You can send it in csv as well.

**Comment by paulator** [comment]
Here you go. I had to change the containing text. It had some customer data in it. I hope, the error is still present with this data.

[Task.zip](https://github.com/frappe/erpnext/files/1004843/Task.zip)

**Comment by paulator** [comment]
@netchampfaris : where you able to reproduce the error or do you need attitional information?

**Comment by netchampfaris** [comment]
@paulator One of your tasks has its end_date set as 31.12.3016 which results in very large computations in Gantt.
Anyway I will have to handle this so that we don't allow large durations which break the Gantt.

**Comment by farqalit** [comment]
@hrwX  Got server error on gantt chart load for attendance 
![gantt_issue](https://user-images.githubusercontent.com/12011956/53622599-29d3ad80-3c1c-11e9-9693-59655a13a296.png)
Please guide1

**Comment by farqalit** [comment]
@hrwX GOt server error on Gantt cart loading for attendance module.
![gantt2](https://user-images.githubusercontent.com/12011956/53623110-e4b07b00-3c1d-11e9-8394-c960a65ba996.png)

when I changed fields name to attendance_date in erpnext/erpnext/hr/doctype/attendance/attendance_calendar.js
It works fine.

Please guide!
