### ISSUE TITLE
Display of Account Currency in Journal Entry

### ISSUE THREAD

**Issue by addymuliady** [frappe/erpnext#8726]
Hi,

Is it possible that when I key in into the Journal Entry details with multicurrency, the currency automatically switches to account currency.

See below, it is an SGD account but when I key in 1000, it still shows USD

![image](https://cloud.githubusercontent.com/assets/21187126/25792092/0b55d60a-33f7-11e7-8f65-51660d9fc30d.png)

Thanks!

**Comment by strixaluco** [comment]
Issue tracker is for bug reports and feature requests only. Please post questions to the forum: [discuss.erpnext.com](https://discuss.erpnext.com)

**Comment by addymuliady** [comment]
Come on @strixaluco , this is a bug!

**Comment by strixaluco** [comment]
Sorry. Just to avoid confusion, try to file bug reports according to (guidelines)[https://github.com/frappe/erpnext/wiki/Issue-Guidelines]

**Comment by addymuliady** [comment]
@strixaluco thanks! will take note on this for future raising of issues

**Comment by addymuliady** [comment]
Hi @jwrober ,

May I know why this issue is closed?

See image below.

![image](https://cloud.githubusercontent.com/assets/21187126/26205774/5ee18190-3c15-11e7-98d0-d178f5049626.png)

**Comment by jwrober** [comment]
Because this looks more like a setup issue than a bug. You have been asked to provide more details based on issue submission guidelines. How do you reproduce this error so others can see it on their end too?

**Comment by addymuliady** [comment]
Hi @jwrober @strixaluco 

I put up an related issue here:
https://github.com/frappe/erpnext/issues/8919

Thanks!
