### ISSUE TITLE
Wildcard Search not Functioning Properly

### ISSUE THREAD

**Issue by addymuliady** [frappe/erpnext#8727]
Hi,

While we are doing search using wildcard, using multiple rows in Journal Entry, the search results are inconsistent.

Please see below for comparison. Should't the accounts on 2nd pic also appear in the search results in 1st pic?

![image](https://cloud.githubusercontent.com/assets/21187126/25792412/1080bd8c-33f9-11e7-93f3-48241b5403d4.png)

![image](https://cloud.githubusercontent.com/assets/21187126/25792422/243d306c-33f9-11e7-9414-c96d25567651.png)

It seems the number of searches is limited. Is that by design?

**Comment by strixaluco** [comment]
Issue tracker is for bug reports and feature requests only. Please post questions to the forum: [discuss.erpnext.com](https://discuss.erpnext.com)

**Comment by addymuliady** [comment]
@strixaluco isn't this a bug? Is the new way of things is to post in forum, confirm it is a bug and then post on Github?

**Comment by strixaluco** [comment]
Sorry, the matter of issue might have been not clear enough. Can you tell which software versions you tested this on?

**Comment by addymuliady** [comment]
Hi @strixaluco,

Sincerest apologies for being late in reply.

ERPNext: v8.0.24 (master)
Frappe Framework: v8.0.42 (master)

1. Go to Journal Entry
2. Click on "Add Multiple Row"
3. Search according to COA, my sample example is as above
