### ISSUE TITLE
Changes to Description field in Journal Entry details not saved

### ISSUE THREAD

**Issue by addymuliady** [frappe/erpnext#8728]
After a Journal Entry is saved, I changed Description field in Journal Entry Details.

However, when I clicked on Save, the changes are not saved.

Please see below.

![journal_entry_detail_save](https://cloud.githubusercontent.com/assets/21187126/25792830/9e489e1c-33fb-11e7-8ff8-3f393e485615.gif)

**Comment by strixaluco** [comment]
What are the versions of Frappe/ERPNext you are using? I can't find `description` field in the recent master and develop branches (Frappe Framework: v8.0.36/ERPNext: v8.0.23 and later)

**Comment by addymuliady** [comment]
@strixaluco am using 8.0.8 ... but I have checked on ERPNext.com ... While Description is replaced by Reference, the end result is still the same - field cannot be saved

**Comment by strixaluco** [comment]
Yes, value, typed into `reference` field doesn't get saved indeed. Can replicate in Frappe Framework v8.0.36/ERPNext v8.0.23

**Comment by rohitwaghchaure** [comment]
Hi @addymuliady 
Reference field contains the names based on the reference type. For example if you have selected reference type as Sales Invoice then you get the list of sales invoices in the reference field. For description kindly add the custom field in the **Journal Entry Account** doctype

**Comment by addymuliady** [comment]
@rohitwaghchaure thanks! I think it is better to hide the Reference field unless Reference Type is chosen.
