### ISSUE TITLE
Production Order enhancements related to Warehouse

### ISSUE THREAD

**Issue by nabinhait** [frappe/erpnext#8731]
**Source Warehouse**
- [ ]  Add "Source Warehouse" field in the "Production Order Item" child table and it can be a group warehouse.
- [ ] Default Source Warehouse will be fetched from BOM, add source warehouse field in the BOM Item table.
- [ ] Reserve raw materials on it's own "source warehouse", even if it's a group.

**WIP Warehouse**
- [ ] Allow group warehouse in the WIP Warehouse
- [ ] If group, while making transfer entry, don't set target warehouse as WIP warehouse, leave it blank

**Reference Qty**
-  [ ] Add "Available Qty at Source Warehouse" and "Available Qty at WIP Warehouse" fields in Item table.

**Comment by dottenbr** [comment]
Table status color:
- If WIP qty => required qty = green (all set to go)
- If WIP qty + source qty => required qty = orange (needs transfer)
- If WIP qty + source qty < required qty = red (needs purchase)
