### ISSUE TITLE
Suggestions/Fixes for Assessment Result Tool

### ISSUE THREAD

**Issue by nabinhait** [frappe/erpnext#8737]
<img width="1044" alt="screen shot 2017-05-08 at 6 14 36 pm" src="https://cloud.githubusercontent.com/assets/836784/25804854/f67bead4-341a-11e7-9e3b-67b74b013080.png">

**Comment by manassolanki** [comment]
- [ ] The assessment result should contain fields for academic year, term and course.
- [ ] The assessment result tool should have a save/submit/create button.

**Comment by crossxcell99** [comment]
I made a pull request #9148 which shows how I implemented a report card and multiple courses for assessment result.

![resultsreport1](https://cloud.githubusercontent.com/assets/23179734/26788749/2b61b6f6-4a06-11e7-8116-b0652fb08dd9.png)
This report lists all the student results including the criterias

![resultprint](https://cloud.githubusercontent.com/assets/23179734/26788750/2b6457da-4a06-11e7-9519-35d245fa6684.png)
This is the print format of the results report
