### ISSUE TITLE
Wrong Validations in the Grading Scale

### ISSUE THREAD

**Issue by nabinhait** [frappe/erpnext#8738]
Try to create Grading Scale, it does not save even if threshold is defined.

<img width="1021" alt="screen shot 2017-05-08 at 6 11 44 pm" src="https://cloud.githubusercontent.com/assets/836784/25804969/74ab085e-341b-11e7-9ebc-d75ec9cf77fa.png">

**Comment by manassolanki** [comment]
This seems right to me,
Here 80% threshold means 'A' grade for (80-100)%
so we have to define grade for threshold 0% ie. range (0-80)%

**Comment by Abdulsamad99** [comment]
having same issue
