### ISSUE TITLE
PDF printing messing up spacing in page

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#8739]
Print preview renders the distance to the top of the page differently from PDF export.

Print Preview
<img width="1066" alt="bildschirmfoto 2017-05-08 um 17 35 38" src="https://cloud.githubusercontent.com/assets/9136094/25811882/e8fb6d86-3414-11e7-8173-b717af288d6d.png">

PDF Export
<img width="1364" alt="bildschirmfoto 2017-05-08 um 17 33 42" src="https://cloud.githubusercontent.com/assets/9136094/25811822/bccafdf8-3414-11e7-89e0-6b5dc1d14d1e.png">

So either the preview has to be changed or the PDF export. I suggest changing the preview since the PDF export is probably what most ERPNext users care about.

**Comment by emakis** [comment]
@dottenbr 
Trying to reproduce the issue... to me seems ok
![image](https://cloud.githubusercontent.com/assets/13694115/25890116/0aa0f238-3575-11e7-927b-cfd1b0fe4c3e.png)
I test it in windows and ubuntu environment with chrome

**Comment by netchampfaris** [comment]
@dottenbr Can't reproduce here as well.

**Comment by ci2014** [comment]
I have the same problem here.

**Comment by ci2014** [comment]
Any ideas? I don't know, why this Issue is closed.

**Comment by basdereus84** [comment]
I've played around making a template which would suit my needs, a couple of months ago. I was just testing some things to see if ERPNext could suit my needs. But I also had problems to get a consistent output from the html preview to pdf.

**Comment by ci2014** [comment]
https://github.com/frappe/frappe/issues/4467

I opened this issue in Frappe.
