### ISSUE TITLE
Email Inbox not displaying any messages.

### ISSUE THREAD

**Issue by tasik17** [frappe/erpnext#8741]
I setup a new hosted account and am going through setting it up. Setup one email address as default incoming and outgoing and got email working in quotes and invoicing.
When i click on Inbox no messages are shows just a button to add new email account. 
Clicking on filters, shows all send and received emails and where they're linked to, but no messages to click on or link to other records.
Please let me know how to fix this.
Thanks in advance

**Comment by tundebabzy** [comment]
Hello @tasik17
Are you still experiencing this problem? I think a hard refresh (shift + refresh button) should resolve this. Please report back so that this issue can be properly treated.

**Comment by tundebabzy** [comment]
Hello @tasik17 
Please reopen this issue if the problem is still persisting.

**Comment by tasik17** [comment]
The issue still persists.
I did hard refresh with inbox not showing any messages only button to setup
new mailbox.

**Comment by mbauskar** [comment]
@tasik17,

You will need to assign the Email Account to user, Go to User and check the section Email Inbox

![screen shot 2017-05-19 at 6 34 36 am](https://cloud.githubusercontent.com/assets/11224291/26229171/4448ccce-3c5d-11e7-8f54-69761f428ee8.png)

**Comment by tasik17** [comment]
That worked.
Thank you

**Comment by jaimestuardo** [comment]
I have the same problem. Even when I have added the e-mail accounts to user, inbox appear empty. I can only send e-mails from those accounts.
