### ISSUE TITLE
[Enh] Accounting Statements need pro-forma comparison

### ISSUE THREAD

**Issue by jwrober** [frappe/erpnext#8747]
Right now all of the financial accounting statements just give a view of a period of time (from year, to year). What I would like to see is more granularity or other filter options. For example, if I select from to be 2016 to year to be 2017, I should then see

```
Jan-16     Jan-17     Variance     Variance %
$xxx        $yyy        $zzz       aaa%
```

I also don't need to see future dates as they don't mean anything. If I pick quarterly in this scenario the view would change to Q#-16 Q#-17

```
Q1-16     Q1-17     Variance     Variance %
$xxx      $yyy      $zzz         aaa%
```
This provides a much more useful way to see the results and be able to quickly compare.

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.
