### ISSUE TITLE
[Enh] Spending Reports

### ISSUE THREAD

**Issue by jwrober** [frappe/erpnext#8748]
There are a few reports to show spending and such in selling or buying modules that deal with the item database. What I am after is an accounting view of the expense accounts. I would like to see a report that shows spending, comparison to budget w/ variance and filters for things like period (monthly, quarterly), company and cost center. Report should report consolidated financials of any number of companies.

This report would show a future view to help with forecasting.

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.
