### ISSUE TITLE
Repeat messages

### ISSUE THREAD

**Issue by jwrober** [frappe/erpnext#8749]
There are too many messages that we have to click through. Some of them are duplicated. A good example is when you have a recurring purchase invoice. You will get a message that the next one will be created on X date on save (every save) and then at submit. I only need to see it once. This is also just a FYI type message.  I should not have to acknowledge it. Just show it (once) and then have it disappear on its own - or maybe when i click out of the window or something.

**Comment by manassolanki** [comment]
@jwrober Could you please let us know specific doctype in which you are facing this problem.

**Comment by jwrober** [comment]
Right now i mostly see it on the purchase invoice when recurring entries are setup. I don't have any recurring sales invoices, but I'll bet the issue is there as well. If you start there, that would be a great start. Thanks for picking up this issue.

**Comment by manassolanki** [comment]
As far as recurring sales invoice is to be considered, it will be redesigned with new subscription functionality (see this thread for more insight https://github.com/frappe/erpnext/issues/6313). We have already shortlisted this issues and one of the developers from frappe or foundation will be soon working on this. If there is any other doctype or functionality, please let me know.
