### ISSUE TITLE
[Enh] Purchase/Sales Invoice "templates"

### ISSUE THREAD

**Issue by jwrober** [frappe/erpnext#8750]
My need is more on the sales side vs the purchase side, but I think it would be good in both places. What I am thinking of is more than a recurring invoice feature.  For example, we sell a lot of the same item and I would like to have "template" of some kind that ...

1. Creates the SINV
2. Creates the related PE
3. Creates a related JV to handle pay pal fees and other things for COGS tracking

Right now I have to do all of this manually for every sale. Having teh ability to have drafts of all these documents created in one click would really save a lot of data entry.

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.
