### ISSUE TITLE
[Enh] Forecasting in reporting

### ISSUE THREAD

**Issue by jwrober** [frappe/erpnext#8751]
Right now the accounting financial statements show future dates (e.g. months in month view), but once yu get to current month the future months just show the same numbers.  This enhancement request would be best in cash flow statement, but is applicable to other reports too. If we have a collection of expenses (e.g. recurring invoices) or other accrued transactions in future, it would be great to see how that impacts cash down the road. Same with payroll, loan payments, etc.

**Comment by mhbu50** [comment]
+1

**Comment by henrynewman** [comment]
Was this solved?

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.
