### ISSUE TITLE
purchase orders should have reference to sales order for dropship

### ISSUE THREAD

**Issue by nathan-eden** [frappe/erpnext#8755]
1) Create Sales Order with drop ship item
2) Click on Make -> Purchase Order
3) Save Purchase Order

Note that the Purchase Order has no reference back to the Sales Order that created this Purchase Order.  To me that's a bug.  With no reference there is no way to link back to that Sales Order.  There's also no way to search for it.

**Comment by nick9822** [comment]
@nathan-eden 
It has those associations and managed in PO items.
Check **Purchase Order Item**.

**Comment by nathan-eden** [comment]
@nick9822 I don't see what you are referring to.  Can you send a screenshot?

**Comment by nick9822** [comment]
See the image below to filter Purchase Orders associated to particular sales order.

![erpnext-1-git](https://cloud.githubusercontent.com/assets/10139291/25900072/d2a1a6d0-35af-11e7-8c08-87eaa36a24a7.PNG)
