### ISSUE TITLE
Tag have disappeared

### ISSUE THREAD

**Issue by TechOfficerA** [frappe/erpnext#8758]
I assigned tags to serial numbers as well as to items as well.  The sidebar on the left does not longer list them.

**Comment by nick9822** [comment]
@TechOfficerA 
Its working at our end. Which version are you using?
Can you provide screenshot?

**Comment by TechOfficerA** [comment]
Please see below.
Screenshots taken after refresh.  No filter is applied.  There are several
tags associated with the serial numbers.  "Problem" appeared after the
update about 1 week ago.
Regards, Inge

[image: Inline images 3]

[image: Inline images 2]

Installed Apps

*ERPNext:* v8.0.24 (master)

*Frappe Framework:* v8.0.42 (master)

Inge Middendorf
Technical Officer
SwitchDin Pty Ltd
Mob 0409603789
inge.middendorf@switchdin.com
http://www.switchdin.com/ <http://switchd.in/>

**Comment by netchampfaris** [comment]
@TechOfficerA Can you post the screenshots again? It seems they didn't upload correctly.

**Comment by tundebabzy** [comment]
Please reopen this issue if the problem still persists.
