### ISSUE TITLE
Serial numbers

### ISSUE THREAD

**Issue by TechOfficerA** [frappe/erpnext#8759]
I can no longer change the serial numbers of a sales product in the delivery note.  Even though the serial numbers are available in the warehouse.  After saving the note, some of the serial numbers in the pdf are not what I selected.    ERPnext replaces some of the serial numbers.

**Comment by nick9822** [comment]
@TechOfficerA 
Is delivery note submitted? Please provide more information about the issue, preferably with screenshot.

**Comment by nick9822** [comment]
Its already reported issue #8671, hence closing it here.
