### ISSUE TITLE
Dropdown Items in Summernote Text UI dont work

### ISSUE THREAD

**Issue by felixvarghese** [frappe/erpnext#8762]
There are 3 dropdown buttons in the text editor UI. Clicking on them shows the dropdown. However, you cannot interact with the dropdown. As a result - you cant change the font size, add a table, or set alignment.

This is happening on the demo instance. I am using the latest Chrome on Windows.

The issue was reported at https://discuss.erpnext.com/t/editor-function-not-working/23649

![image](https://cloud.githubusercontent.com/assets/3396162/25899083/208172b2-35ac-11e7-856c-6f1a291fdd62.png)

**Comment by pratu16x7** [comment]
Chrome - [demo.erpnext.com](https://demo.erpnext.com/desk#Form/Event/New%20Event%201):
![screen shot 2017-05-11 at 9 54 21 am](https://cloud.githubusercontent.com/assets/5196925/25932647/1f07cac4-3630-11e7-9d44-0e373e28d6df.png)

Any more details that'd help to replicate?

**Comment by felixvarghese** [comment]
I just checked again today, and it seems like this is working again.
