### ISSUE TITLE
Improvements in Return / Credit Note (Sales Invoice)

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#8769]
- [x] In the original Sales Invoice, if Update Stock was not checked, then in the Return Invoice, it should not auto-checked, even from POS.
- [ ] Improve naming of next steps. Current it shows "Return / Credit Note". Show it based on value, like if Update Stock is checked, then Return will appear. Same way, only if Sales Invoice is Paid (Partially as well), then only Credit Note option should be visible. If Sales Invoice is not paid, then in the case of Return, Sales Invoice can be canceled.
- [ ] It will be very intuitive for the User to be able to make a future adjustment against the Credit Note, and not against the old Sales Invoice linked to that Credit Note.

**Comment by joezsweet** [comment]
👍
