### ISSUE TITLE
POS Customer Queue Delete Option

### ISSUE THREAD

**Issue by Bow-N** [frappe/erpnext#8776]
Are we able to create an option to delete POS transactions that in the customer queue and not synced

**Comment by hanselke** [comment]
you can clear the pos transactions by clearing your browsers localStorage. not sure if you can do it one line item at a time tho

**Comment by rohitwaghchaure** [comment]
In POS profile, enabled the option Allow Delete
You will get an option to delete the draft records which are not synced

![screen shot 2017-06-07 at 2 35 26 pm](https://user-images.githubusercontent.com/8780500/26870770-aeee2430-4b8e-11e7-89f1-8c46b3699334.png)

**Comment by bghayad** [comment]
Is it possible to know the draft transactions that have been deleted?
