### ISSUE TITLE
Field reference_name is not selectable on Payment Request Page

### ISSUE THREAD

**Issue by mist-01** [frappe/erpnext#8778]
When ever I load the Payments request page, I am getting the following error:
![reference_name-not-selectable](https://cloud.githubusercontent.com/assets/2146048/25945376/b5d1a9f8-3657-11e7-8736-24af11252c6c.png)

I am on the master branch commit 0d0d3bacd7d31055b575639dc9bf2595ba229caf

It looks like this bug might have been introduced by commit 9df45bbc427a5c559abe29edc39a49193d57525c

**Comment by MCD-50** [comment]
Can you give more details and screenshots?

Please refer 
https://github.com/frappe/erpnext/wiki/Issue-Guidelines

**Comment by mist-01** [comment]
Thanks for the reply.  I did some more digging, and I can now reproduce it consistently.  
Steps to reproduce: 

1. I start by selecting reload from my user menu - this seems to reset the issue.
2. If I load payment request list by navigating directly to the page (by using the search bar), there are no issues.  Things work great and there is no popup error.  I can do this repeatedly without error messages.
3. However, if I go to a sales order and then click on the "payment requests" link from the sales order, I am directed to the page and the error appears in a popup.
4. Now anytime I open the Payment Request List page, I see the popup, regardless of how I get there.  This can be done repeatedly as well
5. Each additional time I open the Payment Request List page, an additional GUI element gets added in the filter area (see screenshots to understand).  It is consistenly one added for each time I open the page.
6. If I select "Reload" from the user menu, the extra GUI elements are removed and the Payment Requests page works normally and without error until I click on the link from the sales order page - at which point the process repeats.

![payment-request-1-element](https://cloud.githubusercontent.com/assets/2146048/26065249/57f795cc-39a4-11e7-8479-0ea5f2d7f462.png)
![payment-request-3-elements](https://cloud.githubusercontent.com/assets/2146048/26065250/58055ba8-39a4-11e7-804a-3c87ca51e53b.png)
![payment-request-4-elements](https://cloud.githubusercontent.com/assets/2146048/26065251/581c1e74-39a4-11e7-8050-4f00f70ff604.png)
![payment-request-5-elements](https://cloud.githubusercontent.com/assets/2146048/26065252/5834500c-39a4-11e7-8dfc-94abd052e82f.png)

If there is other information that I can provide, please let me know.

**Comment by mist-01** [comment]
I also have received this error on a sales order page which I believe is related.  I haven't been able to produce this one consistently like the error on the Payment Request List, but if I figure out how to reproduce this one I will add those details.  However, I wanted to include it now in case it helps explain the above error:

![error-on-sales-order-page](https://cloud.githubusercontent.com/assets/2146048/26065437/fce67fe4-39a4-11e7-9c39-3db3157067a5.png)

**Comment by MCD-50** [comment]
After 4 hours of debugging looks like the issue the solved. Sending pull request. Open this issue again if you face the problem again after pull request is merged.

**Comment by MCD-50** [comment]
Merged. I'm closing this issue.
