### ISSUE TITLE
 Chart of Accounts wrong Order 

### ISSUE THREAD

**Issue by Helkyd** [frappe/erpnext#8784]
Based on Erpnext discussion https://discuss.erpnext.com/t/chart-of-accounts-wrong-order/23653
please have a look at the ordering when adding a new Chart of Account ...

**Comment by tundebabzy** [comment]
Since all the json chart of account files all seem to be written in alphabetical order, I think it's correct to display them in the same manner.

**Comment by tundebabzy** [comment]
fixed

**Comment by Helkyd** [comment]
Good work.
