### ISSUE TITLE
[beta] Multiple documents on print loses format and images

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#8785]
Hello,

I noticed that when I select multiple production orders to print, it loses the format and suppress any image, so we have to print one by one, with 500 orders/day its really difficult.

This happens on every multiple print, the logo is suppressed and no column break is considered.

**Comment by rohitwaghchaure** [comment]
Hi @applepipe 

It's working fine on my local account
Can you please share the screenshots or GIF?

**Comment by applepipe** [comment]
Hello @rohitwaghchaure !

This is the document when I print it individually

<img width="1248" alt="screen shot 2017-05-18 at 4 51 28 pm" src="https://cloud.githubusercontent.com/assets/18335894/26221121/c828e078-3beb-11e7-93d2-a43581a983dc.png">

Selecting multiple documents on list view
<img width="1205" alt="screen shot 2017-05-18 at 4 51 45 pm" src="https://cloud.githubusercontent.com/assets/18335894/26221129/cf584816-3beb-11e7-9bc7-bdde73bac1ec.png">

Printing on same custom format
<img width="738" alt="screen shot 2017-05-18 at 4 51 55 pm" src="https://cloud.githubusercontent.com/assets/18335894/26221151/e184fffc-3beb-11e7-8e86-3c13ebd85db0.png">

Result, losing image logo (hidden on screenshot) and losing all the format, curiously the QR code image that is not hosted on the server (its a <img href="">) is printed without problems, but the logo  dont.

<img width="1542" alt="screen shot 2017-05-18 at 4 52 10 pm" src="https://cloud.githubusercontent.com/assets/18335894/26221237/2a4c0460-3bec-11e7-95c9-33a6957cc174.png">

**Comment by rohitwaghchaure** [comment]
Hi @applepipe 
Can you please check the version of wkhtmltopdf, check with the version 0.12.3

**Comment by applepipe** [comment]
hello @rohitwaghchaure 

I've updated to 0.12.3 patched qt and still same result, column breaks are ignored and no logo, I also get a blank page after every document

Tried to update to latest version of wkhtmltopdf 0.12.4 and the result was a more compact view but same problems, am I missing some config file?
