### ISSUE TITLE
Leaderboards

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#8795]
- [x] Top Customers
- [x] Top Items
- [x] Top Suppliers
- [x] Top Sales Partners

**Comment by mhbu50** [comment]
+1

**Comment by vladucoju** [comment]
+1

**Comment by mosabamf** [comment]
+1

**Comment by giuseppelamatrice** [comment]
+1

**Comment by Olawale1** [comment]
+1

This is a very useful feature. I'm assuming criteria for 'Top Items' will include both Total Sales and Total Purchases, right?

Kind Regards,

**Comment by pratu16x7** [comment]
frappe/erpnext#10638

**Comment by vladucoju** [comment]
Hello pratu16x7,

LeaderBoard is excelent. Could i suggest one more usefull thing, gross profit by months (sales, purchaced, profit, margin percent)

**Comment by pratu16x7** [comment]
Let's continue this over at https://github.com/frappe/erpnext/issues/12389
@vladucoju Gross profit looks information dense, would surely be useful :)
