### ISSUE TITLE
Issue with POS on mobile devices

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#8801]
Hi,

There's an issue with the v8 POS on mobile devices. The numeric keypad is not showing up so there's no way to complete a sale! I've tried this on multiple mobile devices using default browsers, Chrome, Opera, and the ERPNext mobile app!

Also, the button for switching views between the Cart and the Customer Queue seems not to work a lot of times (on mobile devices as mentioned above)

Kindly help look into this

Thanks

**Comment by netchampfaris** [comment]
@Olawale1 
The numeric keypad is purposefully hidden in mobile devices, since the mobile keypad does the job.

![image](https://cloud.githubusercontent.com/assets/9355208/26045337/59e01eb4-3967-11e7-9481-234f28173a1e.png)

**Comment by Olawale1** [comment]
Hi @netchampfaris 

Thanks for your response. There are however still issues

1. Cashiers are compelled to select an item  and then click on a field before they can process a sale
2. The button to switch between Cart and Queue doesn't work a lot of the time 
3. The 'Pay' button isn't available on a number of devices! 
![2017-05-15 11 10 55](https://cloud.githubusercontent.com/assets/9269337/26053070/5369d050-395f-11e7-9ed0-4a82e92a3a99.png)

Thanks
