### ISSUE TITLE
Define hour rate in BOM

### ISSUE THREAD

**Issue by SYMBARCELONA** [frappe/erpnext#8805]
When defining the operations in the BOM we need to assign an hour cost.
When creating operations there is no way to define hour rate.
On the other hand when doing a timesheet you can only assign hours to activities.

Once defined the BOM we have to start the project and the correlation with the hours from the operations to the tasks is not automatic

Anyway to do that?

**Comment by nick9822** [comment]
@SYMBARCELONA 
Please ask questions to community forum at [discuss.erpnext.com](discuss.erpnext.com)

**Comment by SYMBARCELONA** [comment]
I have been asked in the discuss forum to open an issue.

Francisco Lage
Director

www.symbarcelona.com

**Comment by bcornwellmott** [comment]
This is the discussed topic. To be clear, the issue for github is not related to defining hourly rates for operations (which is done through the workstation). It's to do with tying a project task to an operation.
https://discuss.erpnext.com/t/define-hour-rate-in-bom/23657

**Comment by yadavyk** [comment]
This is implemented. Please refer : [Bill of Materials with operations](https://docs.erpnext.com/docs/v13/user/manual/en/manufacturing/bill-of-materials#21-bill-of-materials-with-operations)
