### ISSUE TITLE
[enhancement] Fields should have an option to limit number of characters and blacklisted characters

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#8807]
Fields and custom fields should have an option to limit number of characters and blacklisted characters

Example: item_name limited to 100 characters and you cant use quotes in the name.

**Comment by ishanloya** [comment]
The Length field lets you limit the number of characters.

**Comment by ishanloya** [comment]
You can maybe blacklist characters by using a custom script

**Comment by nick9822** [comment]
@applepipe 
As @ishanloya has suggested you can use length field and custom script validation.
For more details search through community forum [discuss.erpnext.com](discuss.erpnext.com)

**Comment by applepipe** [comment]
thank you @ishanloya the translation (pt-br) made me think that length was about other parameter
