### ISSUE TITLE
Salary Register report

### ISSUE THREAD

**Issue by samehmredalava** [frappe/erpnext#8808]
Hello ,

salary register report does not work " attached screen shoot "
![untitled](https://cloud.githubusercontent.com/assets/28655794/26006541/acd29aa2-36f1-11e7-808f-ce836c0ff5e6.png)

**Comment by ishanloya** [comment]
Can you try clicking on the Refresh button and see if it works?

**Comment by samehmredalava** [comment]
Yes it works , however this was not the usual for any kind of reports.

please advise.

**Comment by tundebabzy** [comment]
Hello @samehmredalava 
There are multiple reasons that can cause the 'hanging' behaviour. However a refresh of the page will usually fix it and it did in this case.

Since the problem is fixed, I'm closing the issue for now.
