### ISSUE TITLE
Posting Date error when importing Sales Invoices in v8 (Critical)

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#8809]
Hi,

When importing Sales Invoices, the system isn't using the Posting Date in the import template; instead, it is using the current date and time. This then leads to a Due Date cannot be before Posting Date error

Kindly help resolve

Thanks

**Comment by rmehta** [comment]
Set "Edit Posting Date and Time" to 1

**Comment by Olawale1** [comment]
Hi @rmehta , thanks a lot... it worked. Closing this now

Kind regards,

**Comment by rmehta** [comment]
Re-opening it. Let it be default while importing data!
