### ISSUE TITLE
[beta] error on email alert

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#8810]
Hello,

I'm having this issue when configuring an email alert on non submittable  documents. The error log says that is not allowed to print draft documents, but the document can be printed normally. This started to happen after last week update.

**Comment by MCD-50** [comment]
Use this:
https://github.com/frappe/erpnext/wiki/Issue-Guidelines

**Comment by tundebabzy** [comment]
Hello @applepipe
Please reopen the issue with steps to reproduce the issue
