### ISSUE TITLE
Exchange Rate calculation in Journal and Payment Entry

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#8814]
Hi,

In Journal Entries and Payment Entries, the exchange rate should be automatically calculated to offset the outstanding amount in Company Currency when the Bank/Cash account and Party account are in same currency

For example, let's say default currency is INR but there's a Purchase Invoice for an overseas supplier in USD and the Creditors account is also based in USD. When I generate a Payment for that invoice, the exchange rate used in the invoice should be automatically translated to the payment entry if I select a USD Bank/Cash account for settlement

Thanks

**Comment by tundebabzy** [comment]
Hello @Olawale1 
Thanks for raising this issue. 

> For example, let's say default currency is INR but there's a Purchase Invoice for an overseas supplier in USD and the Creditors account is also based in USD. When I generate a Payment for that invoice, the exchange rate used in the invoice should be automatically translated to the payment entry if I select a USD Bank/Cash account for settlement

IAS 21 requires that the exchange rate be recorded initially as the rate in effect on the day of the transaction or a reasonable average for the day. Because the invoice will not necessarily be paid on the day of the invoice and exchange rates can fluctuate wildly within 12 hours, I think it's correct to have the accountant manually input the exchange rate.

Closing this issue for now.

**Comment by Olawale1** [comment]
Hi @tundebabzy 

Trust you're doing well. Sorry I didn't explain properly; I was actually referring to the Creditor/Debtor side of the payment. This leg has to be the same rate as what was used in the Invoice. The rate which the accountant enters is the one for the Bank. The difference arising from both rates is then booked as currency exchange gain/loss

Right now in ERPNext, we need to manually copy the exchange rate from the invoice and paste in the payment entry. Ideally, it should get pulled automatically

Please let me know if you require further clarifications

Thanks

**Comment by tundebabzy** [comment]
Hi @Olawale1
Is ERPNext showing the wrong exchange rate or no exchange rate at all?

**Comment by tundebabzy** [comment]
Hello @Olawale1, any update?

**Comment by Olawale1** [comment]
Hi @tundebabzy 

Trust you're doing well. Apologies again for the delay in getting back to you. I just did another test and discovered the Journal Entry works fine now (i.e when you select the Purchase Invoice, the exchange rate gets pulled accordingly). The pending issue now is with the Payment Entry where the payment amount appears in the wrong field (Received Amount instead of Paid Amount) https://github.com/frappe/erpnext/issues/8813

Thanks
