### ISSUE TITLE
Invoice round off does not get reflected in accounts

### ISSUE THREAD

**Issue by ishanloya** [frappe/erpnext#8816]
https://discuss.erpnext.com/t/round-off-amount-not-reflecting-in-financial-statements/21671/4

**Comment by sathishpy** [comment]
Ok, I spent some time to fix this without really knwoing much about the accounting. Here is the patch I worked on.

spoojary@osboxes:~/factory-skpi/apps/erpnext$ git diff
diff --git a/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.json b/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.json
index e3c5fb4..7d6c006 100755
--- a/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.json
+++ b/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.json
@@ -2109,6 +2109,37 @@
    "bold": 0, 
    "collapsible": 0, 
    "columns": 0, 
+   "fieldname": "base_rounded_total", 
+   "fieldtype": "Currency", 
+   "hidden": 0, 
+   "ignore_user_permissions": 0, 
+   "ignore_xss_filter": 0, 
+   "in_filter": 0, 
+   "in_global_search": 0, 
+   "in_list_view": 0, 
+   "in_standard_filter": 0, 
+   "label": "Rounded Total (Company Currency)", 
+   "length": 0, 
+   "no_copy": 0, 
+   "options": "Company:company:default_currency", 
+   "permlevel": 0, 
+   "precision": "", 
+   "print_hide": 0, 
+   "print_hide_if_no_value": 0, 
+   "read_only": 0, 
+   "remember_last_selected_value": 0, 
+   "report_hide": 0, 
+   "reqd": 0, 
+   "search_index": 0, 
+   "set_only_once": 0, 
+   "unique": 0
+  }, 
+  {
+   "allow_bulk_edit": 0, 
+   "allow_on_submit": 0, 
+   "bold": 0, 
+   "collapsible": 0, 
+   "columns": 0, 
    "description": "", 
    "fieldname": "base_in_words", 
    "fieldtype": "Data", 
@@ -2231,6 +2262,36 @@
   {
    "allow_bulk_edit": 0, 
    "allow_on_submit": 0, 
+   "bold": 1, 
+   "collapsible": 0, 
+   "columns": 0, 
+   "fieldname": "rounded_total", 
+   "fieldtype": "Currency", 
+   "hidden": 0, 
+   "ignore_user_permissions": 0, 
+   "ignore_xss_filter": 0, 
+   "in_filter": 0, 
+   "in_global_search": 0, 
+   "in_list_view": 0, 
+   "in_standard_filter": 0, 
+   "label": "Rounded Total", 
+   "length": 0, 
+   "no_copy": 0, 
+   "permlevel": 0, 
+   "precision": "", 
+   "print_hide": 0, 
+   "print_hide_if_no_value": 0, 
+   "read_only": 1, 
+   "remember_last_selected_value": 0, 
+   "report_hide": 0, 
+   "reqd": 0, 
+   "search_index": 0, 
+   "set_only_once": 0, 
+   "unique": 0
+  }, 
+  {
+   "allow_bulk_edit": 0, 
+   "allow_on_submit": 0, 
    "bold": 0, 
    "collapsible": 0, 
    "columns": 0, 
@@ -3920,7 +3981,7 @@
  "istable": 0, 
  "max_attachments": 0, 
  "menu_index": 0, 
- "modified": "2017-09-19 11:22:47.074420", 
+ "modified": "2017-09-29 20:28:36.028105", 
  "modified_by": "Administrator", 
  "module": "Accounts", 
  "name": "Purchase Invoice", 
diff --git a/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py b/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py
index a46c4b9..1928090 100644
--- a/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py
+++ b/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py
@@ -359,9 +359,12 @@ class PurchaseInvoice(BuyingController):
                return gl_entries
 
        def make_supplier_gl_entry(self, gl_entries):
-               if self.grand_total:
+               grand_total = self.grand_total
+               if (self.rounded_total):
+                       grand_total = self.rounded_total
+               if grand_total:
                        # Didnot use base_grand_total to book rounding loss gle
-                       grand_total_in_company_currency = flt(self.grand_total * self.conversion_rate,
+                       grand_total_in_company_currency = flt(grand_total * self.conversion_rate,
                                self.precision("grand_total"))
                        gl_entries.append(
                                self.get_gl_dict({
@@ -371,7 +374,7 @@ class PurchaseInvoice(BuyingController):
                                        "against": self.against_expense_account,
                                        "credit": grand_total_in_company_currency,
                                        "credit_in_account_currency": grand_total_in_company_currency \
-                                               if self.party_account_currency==self.company_currency else self.grand_total,
+                                               if self.party_account_currency==self.company_currency else grand_total,
                                        "against_voucher": self.return_against if cint(self.is_return) else self.name,
                                        "against_voucher_type": self.doctype,
                                }, self.party_account_currency)
diff --git a/erpnext/accounts/doctype/sales_invoice/sales_invoice.py b/erpnext/accounts/doctype/sales_invoice/sales_invoice.py
index 7a787c4..79fdc51 100644
--- a/erpnext/accounts/doctype/sales_invoice/sales_invoice.py
+++ b/erpnext/accounts/doctype/sales_invoice/sales_invoice.py
@@ -631,9 +631,12 @@ class SalesInvoice(SellingController):
                return gl_entries
 
        def make_customer_gl_entry(self, gl_entries):
-               if self.grand_total:
+               grand_total = self.grand_total
+               if (self.rounded_total):
+                       grand_total = self.rounded_total
+               if grand_total:
                        # Didnot use base_grand_total to book rounding loss gle
-                       grand_total_in_company_currency = flt(self.grand_total * self.conversion_rate,
+                       grand_total_in_company_currency = flt(grand_total * self.conversion_rate,
                                self.precision("grand_total"))
 
                        gl_entries.append(
@@ -644,7 +647,7 @@ class SalesInvoice(SellingController):
                                        "against": self.against_income_account,
                                        "debit": grand_total_in_company_currency,
                                        "debit_in_account_currency": grand_total_in_company_currency \
-                                               if self.party_account_currency==self.company_currency else self.grand_total,
+                                               if self.party_account_currency==self.company_currency else grand_total,
                                        "against_voucher": self.return_against if cint(self.is_return) else self.name,
                                        "against_voucher_type": self.doctype
                                }, self.party_account_currency)
diff --git a/erpnext/controllers/taxes_and_totals.py b/erpnext/controllers/taxes_and_totals.py
index e85e56b..8fce462 100644
--- a/erpnext/controllers/taxes_and_totals.py
+++ b/erpnext/controllers/taxes_and_totals.py
@@ -24,7 +24,7 @@ class calculate_taxes_and_totals(object):
 
                if self.doc.doctype in ["Sales Invoice", "Purchase Invoice"]:
                        self.calculate_total_advance()
-                       
+
                if self.doc.meta.get_field("other_charges_calculation"):
                        self.set_item_wise_tax_breakup()
 
@@ -278,7 +278,7 @@ class calculate_taxes_and_totals(object):
 
        def round_off_totals(self, tax):
                tax.tax_amount = flt(tax.tax_amount, tax.precision("tax_amount"))
-               tax.tax_amount_after_discount_amount = flt(tax.tax_amount_after_discount_amount, 
+               tax.tax_amount_after_discount_amount = flt(tax.tax_amount_after_discount_amount,
                        tax.precision("tax_amount"))
 
        def manipulate_grand_total_for_inclusive_tax(self):
@@ -335,6 +335,7 @@ class calculate_taxes_and_totals(object):
                if self.doc.meta.get_field("rounded_total"):
                        self.doc.rounded_total = round_based_on_smallest_currency_fraction(self.doc.grand_total,
                                self.doc.currency, self.doc.precision("rounded_total"))
+                       self.doc.rounding_adjustment = self.doc.grand_total - self.doc.rounded_total
 
                if self.doc.meta.get_field("base_rounded_total"):
                        company_currency = erpnext.get_company_currency(self.doc.company)
@@ -342,6 +343,7 @@ class calculate_taxes_and_totals(object):
                        self.doc.base_rounded_total = \
                                round_based_on_smallest_currency_fraction(self.doc.base_grand_total,
                                        company_currency, self.doc.precision("base_rounded_total"))
+                       self.doc.base_rounding_adjustment = self.doc.base_grand_total - self.doc.base_rounded_total
 
        def _cleanup(self):
                for tax in self.doc.get("taxes"):
@@ -415,14 +417,14 @@ class calculate_taxes_and_totals(object):
                        self.doc.total_advance = flt(total_allocated_amount, self.doc.precision("total_advance"))
 
                        if self.doc.party_account_currency == self.doc.currency:
-                               invoice_total = flt(self.doc.grand_total - flt(self.doc.write_off_amount), 
+                               invoice_total = flt(self.doc.grand_total - flt(self.doc.write_off_amount),
                                        self.doc.precision("grand_total"))
                        else:
-                               base_write_off_amount = flt(flt(self.doc.write_off_amount) * self.doc.conversion_rate, 
+                               base_write_off_amount = flt(flt(self.doc.write_off_amount) * self.doc.conversion_rate,
                                        self.doc.precision("base_write_off_amount"))
-                               invoice_total = flt(self.doc.grand_total * self.doc.conversion_rate, 
+                               invoice_total = flt(self.doc.grand_total * self.doc.conversion_rate,
                                        self.doc.precision("grand_total")) - base_write_off_amount
-                               
+
                        if invoice_total > 0 and self.doc.total_advance > invoice_total:
                                frappe.throw(_("Advance amount cannot be greater than {0} {1}")
                                        .format(self.doc.party_account_currency, invoice_total))
@@ -450,22 +452,26 @@ class calculate_taxes_and_totals(object):
                                self.doc.conversion_rate, self.doc.precision("grand_total")) - self.doc.total_advance
                                        - flt(self.doc.base_write_off_amount), self.doc.precision("grand_total"))
 
-               if self.doc.doctype == "Sales Invoice":                 
+               rounding_adjustment = 0
+               if self.doc.meta.get_field("rounded_total"):
+                       rounding_adjustment = self.doc.rounding_adjustment
+
+               if self.doc.doctype == "Sales Invoice":
                        self.doc.round_floats_in(self.doc, ["paid_amount"])
                        self.calculate_write_off_amount()
                        self.calculate_change_amount()
-                       
+
                        paid_amount = self.doc.paid_amount \
                                if self.doc.party_account_currency == self.doc.currency else self.doc.base_paid_amount
-                       
+
                        change_amount = self.doc.change_amount \
                                if self.doc.party_account_currency == self.doc.currency else self.doc.base_change_amount
 
                        self.doc.outstanding_amount = flt(total_amount_to_pay - flt(paid_amount) +
-                               flt(change_amount), self.doc.precision("outstanding_amount"))
+                               flt(change_amount) - flt(rounding_adjustment), self.doc.precision("outstanding_amount"))
 
                elif self.doc.doctype == "Purchase Invoice":
-                       self.doc.outstanding_amount = flt(total_amount_to_pay, self.doc.precision("outstanding_amount"))
+                       self.doc.outstanding_amount = flt(total_amount_to_pay - flt(rounding_adjustment), self.doc.precision("outstanding_amount"))
 
        def calculate_paid_amount(self):
                paid_amount = base_paid_amount = 0.0
@@ -517,12 +523,12 @@ class calculate_taxes_and_totals(object):
 
        def set_item_wise_tax_breakup(self):
                self.doc.other_charges_calculation = get_itemised_tax_breakup_html(self.doc)
-               
+
 def get_itemised_tax_breakup_html(doc):
        if not doc.taxes:
                return
        frappe.flags.company = doc.company
-       
+
        # get headers
        tax_accounts = []
        for tax in doc.taxes:
@@ -532,14 +538,14 @@ def get_itemised_tax_breakup_html(doc):
                        tax_accounts.append(tax.description)
 
        headers = get_itemised_tax_breakup_header(doc.doctype + " Item", tax_accounts)
-       
+
        # get tax breakup data
        itemised_tax, itemised_taxable_amount = get_itemised_tax_breakup_data(doc)
 
        get_rounded_tax_amount(itemised_tax, doc.precision("tax_amount", "taxes"))
 
        frappe.flags.company = None
-       
+
        return frappe.render_template(
                "templates/includes/itemised_tax_breakup.html", dict(
                        headers=headers,
@@ -572,7 +578,7 @@ def get_itemised_tax(taxes):
                if item_tax_map:
                        for item_code, tax_data in item_tax_map.items():
                                itemised_tax.setdefault(item_code, frappe._dict())
-                       
+
                                if isinstance(tax_data, list):
                                        itemised_tax[item_code][tax.description] = frappe._dict(dict(
                                                tax_rate=flt(tax_data[0]),
@@ -599,4 +605,4 @@ def get_rounded_tax_amount(itemised_tax, precision):
        # Rounding based on tax_amount precision
        for taxes in itemised_tax.values():
                for tax_account in taxes:
-                       taxes[tax_account]["tax_amount"] = flt(taxes[tax_account]["tax_amount"], precision)
\ No newline at end of file
+                       taxes[tax_account]["tax_amount"] = flt(taxes[tax_account]["tax_amount"], precision)
(END)

It seems to work well, but I see two entries for Round-off, with net result being right. However I wished there was only one entry to be honest. Wondering whether this is good enough to send a pull request?

**Comment by sathishpy** [comment]
Ok, I spent some time to fix this without really knwoing much about the accounting. Here is the patch I worked on.
```

spoojary@osboxes:~/factory-skpi/apps/erpnext$ git diff
diff --git a/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.json b/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.json
index e3c5fb4..7d6c006 100755
--- a/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.json
+++ b/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.json
@@ -2109,6 +2109,37 @@
"bold": 0,
"collapsible": 0,
"columns": 0,

"fieldname": "base_rounded_total",
"fieldtype": "Currency",
"hidden": 0,
"ignore_user_permissions": 0,
"ignore_xss_filter": 0,
"in_filter": 0,
"in_global_search": 0,
"in_list_view": 0,
"in_standard_filter": 0,
"label": "Rounded Total (Company Currency)",
"length": 0,
"no_copy": 0,
"options": "Company:company:default_currency",
"permlevel": 0,
"precision": "",
"print_hide": 0,
"print_hide_if_no_value": 0,
"read_only": 0,
"remember_last_selected_value": 0,
"report_hide": 0,
"reqd": 0,
"search_index": 0,
"set_only_once": 0,
"unique": 0
},
{
"allow_bulk_edit": 0,
"allow_on_submit": 0,
"bold": 0,
"collapsible": 0,
"columns": 0,
"description": "",
"fieldname": "base_in_words",
"fieldtype": "Data",
@@ -2231,6 +2262,36 @@
{
"allow_bulk_edit": 0,
"allow_on_submit": 0,
"bold": 1,
"collapsible": 0,
"columns": 0,
"fieldname": "rounded_total",
"fieldtype": "Currency",
"hidden": 0,
"ignore_user_permissions": 0,
"ignore_xss_filter": 0,
"in_filter": 0,
"in_global_search": 0,
"in_list_view": 0,
"in_standard_filter": 0,
"label": "Rounded Total",
"length": 0,
"no_copy": 0,
"permlevel": 0,
"precision": "",
"print_hide": 0,
"print_hide_if_no_value": 0,
"read_only": 1,
"remember_last_selected_value": 0,
"report_hide": 0,
"reqd": 0,
"search_index": 0,
"set_only_once": 0,
"unique": 0
},
{
"allow_bulk_edit": 0,
"allow_on_submit": 0,
"bold": 0,
"collapsible": 0,
"columns": 0,
@@ -3920,7 +3981,7 @@
"istable": 0,
"max_attachments": 0,
"menu_index": 0,
"modified": "2017-09-19 11:22:47.074420",
"modified": "2017-09-29 20:28:36.028105",
"modified_by": "Administrator",
"module": "Accounts",
"name": "Purchase Invoice",
diff --git a/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py b/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py
index a46c4b9..1928090 100644
--- a/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py
+++ b/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py
@@ -359,9 +359,12 @@ class PurchaseInvoice(BuyingController):
return gl_entries

  def make_supplier_gl_entry(self, gl_entries):
          if self.grand_total:
          grand_total = self.grand_total
          if (self.rounded_total):
                  grand_total = self.rounded_total
          if grand_total:
                  # Didnot use base_grand_total to book rounding loss gle
                  grand_total_in_company_currency = flt(self.grand_total * self.conversion_rate,
                  grand_total_in_company_currency = flt(grand_total * self.conversion_rate,
                          self.precision("grand_total"))
                  gl_entries.append(
                          self.get_gl_dict({
@@ -371,7 +374,7 @@ class PurchaseInvoice(BuyingController):
"against": self.against_expense_account,
"credit": grand_total_in_company_currency,
"credit_in_account_currency": grand_total_in_company_currency \

                                          if self.party_account_currency==self.company_currency else self.grand_total,
                                          if self.party_account_currency==self.company_currency else grand_total,
                                  "against_voucher": self.return_against if cint(self.is_return) else self.name,
                                  "against_voucher_type": self.doctype,
                          }, self.party_account_currency)
diff --git a/erpnext/accounts/doctype/sales_invoice/sales_invoice.py b/erpnext/accounts/doctype/sales_invoice/sales_invoice.py
index 7a787c4..79fdc51 100644
--- a/erpnext/accounts/doctype/sales_invoice/sales_invoice.py
+++ b/erpnext/accounts/doctype/sales_invoice/sales_invoice.py
@@ -631,9 +631,12 @@ class SalesInvoice(SellingController):
return gl_entries

    def make_customer_gl_entry(self, gl_entries):
          if self.grand_total:
          grand_total = self.grand_total
          if (self.rounded_total):
                  grand_total = self.rounded_total
          if grand_total:
                  # Didnot use base_grand_total to book rounding loss gle
                  grand_total_in_company_currency = flt(self.grand_total * self.conversion_rate,
                  grand_total_in_company_currency = flt(grand_total * self.conversion_rate,
                          self.precision("grand_total"))

                  gl_entries.append(
@@ -644,7 +647,7 @@ class SalesInvoice(SellingController):
"against": self.against_income_account,
"debit": grand_total_in_company_currency,
"debit_in_account_currency": grand_total_in_company_currency \

                                          if self.party_account_currency==self.company_currency else self.grand_total,
                                          if self.party_account_currency==self.company_currency else grand_total,
                                  "against_voucher": self.return_against if cint(self.is_return) else self.name,
                                  "against_voucher_type": self.doctype
                          }, self.party_account_currency)
diff --git a/erpnext/controllers/taxes_and_totals.py b/erpnext/controllers/taxes_and_totals.py
index e85e56b..8fce462 100644
--- a/erpnext/controllers/taxes_and_totals.py
+++ b/erpnext/controllers/taxes_and_totals.py
@@ -24,7 +24,7 @@ class calculate_taxes_and_totals(object):

            if self.doc.doctype in ["Sales Invoice", "Purchase Invoice"]:
                    self.calculate_total_advance()
          if self.doc.meta.get_field("other_charges_calculation"):
                  self.set_item_wise_tax_breakup()
@@ -278,7 +278,7 @@ class calculate_taxes_and_totals(object):

    def round_off_totals(self, tax):
            tax.tax_amount = flt(tax.tax_amount, tax.precision("tax_amount"))
          tax.tax_amount_after_discount_amount = flt(tax.tax_amount_after_discount_amount, 
          tax.tax_amount_after_discount_amount = flt(tax.tax_amount_after_discount_amount,
                  tax.precision("tax_amount"))

  def manipulate_grand_total_for_inclusive_tax(self):
@@ -335,6 +335,7 @@ class calculate_taxes_and_totals(object):
if self.doc.meta.get_field("rounded_total"):
self.doc.rounded_total = round_based_on_smallest_currency_fraction(self.doc.grand_total,
self.doc.currency, self.doc.precision("rounded_total"))

                  self.doc.rounding_adjustment = self.doc.grand_total - self.doc.rounded_total

          if self.doc.meta.get_field("base_rounded_total"):
                  company_currency = erpnext.get_company_currency(self.doc.company)
@@ -342,6 +343,7 @@ class calculate_taxes_and_totals(object):
self.doc.base_rounded_total = 
round_based_on_smallest_currency_fraction(self.doc.base_grand_total,
company_currency, self.doc.precision("base_rounded_total"))

                  self.doc.base_rounding_adjustment = self.doc.base_grand_total - self.doc.base_rounded_total

  def _cleanup(self):
          for tax in self.doc.get("taxes"):
@@ -415,14 +417,14 @@ class calculate_taxes_and_totals(object):
self.doc.total_advance = flt(total_allocated_amount, self.doc.precision("total_advance"))

                    if self.doc.party_account_currency == self.doc.currency:
                          invoice_total = flt(self.doc.grand_total - flt(self.doc.write_off_amount), 
                          invoice_total = flt(self.doc.grand_total - flt(self.doc.write_off_amount),
                                  self.doc.precision("grand_total"))
                  else:
                          base_write_off_amount = flt(flt(self.doc.write_off_amount) * self.doc.conversion_rate, 
                          base_write_off_amount = flt(flt(self.doc.write_off_amount) * self.doc.conversion_rate,
                                  self.doc.precision("base_write_off_amount"))
                          invoice_total = flt(self.doc.grand_total * self.doc.conversion_rate, 
                          invoice_total = flt(self.doc.grand_total * self.doc.conversion_rate,
                                  self.doc.precision("grand_total")) - base_write_off_amount
                  if invoice_total > 0 and self.doc.total_advance > invoice_total:
                          frappe.throw(_("Advance amount cannot be greater than {0} {1}")
                                  .format(self.doc.party_account_currency, invoice_total))
@@ -450,22 +452,26 @@ class calculate_taxes_and_totals(object):
self.doc.conversion_rate, self.doc.precision("grand_total")) - self.doc.total_advance
- flt(self.doc.base_write_off_amount), self.doc.precision("grand_total"))

          if self.doc.doctype == "Sales Invoice":                 
          rounding_adjustment = 0
          if self.doc.meta.get_field("rounded_total"):
                  rounding_adjustment = self.doc.rounding_adjustment
          if self.doc.doctype == "Sales Invoice":
                  self.doc.round_floats_in(self.doc, ["paid_amount"])
                  self.calculate_write_off_amount()
                  self.calculate_change_amount()
                  paid_amount = self.doc.paid_amount \
                          if self.doc.party_account_currency == self.doc.currency else self.doc.base_paid_amount
                  change_amount = self.doc.change_amount \
                          if self.doc.party_account_currency == self.doc.currency else self.doc.base_change_amount

                  self.doc.outstanding_amount = flt(total_amount_to_pay - flt(paid_amount) +
                          flt(change_amount), self.doc.precision("outstanding_amount"))
                          flt(change_amount) - flt(rounding_adjustment), self.doc.precision("outstanding_amount"))

          elif self.doc.doctype == "Purchase Invoice":
                  self.doc.outstanding_amount = flt(total_amount_to_pay, self.doc.precision("outstanding_amount"))
                  self.doc.outstanding_amount = flt(total_amount_to_pay - flt(rounding_adjustment), self.doc.precision("outstanding_amount"))

  def calculate_paid_amount(self):
          paid_amount = base_paid_amount = 0.0
@@ -517,12 +523,12 @@ class calculate_taxes_and_totals(object):

    def set_item_wise_tax_breakup(self):
            self.doc.other_charges_calculation = get_itemised_tax_breakup_html(self.doc)
def get_itemised_tax_breakup_html(doc):
if not doc.taxes:
return
frappe.flags.company = doc.company

  # get headers
  tax_accounts = []
  for tax in doc.taxes:
@@ -532,14 +538,14 @@ def get_itemised_tax_breakup_html(doc):
tax_accounts.append(tax.description)

    headers = get_itemised_tax_breakup_header(doc.doctype + " Item", tax_accounts)
  # get tax breakup data
  itemised_tax, itemised_taxable_amount = get_itemised_tax_breakup_data(doc)

  get_rounded_tax_amount(itemised_tax, doc.precision("tax_amount", "taxes"))

  frappe.flags.company = None
  return frappe.render_template(
          "templates/includes/itemised_tax_breakup.html", dict(
                  headers=headers,
@@ -572,7 +578,7 @@ def get_itemised_tax(taxes):
if item_tax_map:
for item_code, tax_data in item_tax_map.items():
itemised_tax.setdefault(item_code, frappe._dict())

                          if isinstance(tax_data, list):
                                  itemised_tax[item_code][tax.description] = frappe._dict(dict(
                                          tax_rate=flt(tax_data[0]),
@@ -599,4 +605,4 @@ def get_rounded_tax_amount(itemised_tax, precision):
# Rounding based on tax_amount precision
for taxes in itemised_tax.values():
for tax_account in taxes:

                  taxes[tax_account]["tax_amount"] = flt(taxes[tax_account]["tax_amount"], precision)
\ No newline at end of file

                  taxes[tax_account]["tax_amount"] = flt(taxes[tax_account]["tax_amount"], precision)
(END)

```
It seems to work well, but I see two entries for Round-off, with net result being right. However I wished there was only one entry to be honest. Wondering whether this is good enough to send a pull request?

**Comment by sathishpy** [comment]
[https://pasteboard.co/GMCQMip.png](url)

**Comment by sathishpy** [comment]
Sample output
https://pasteboard.co/GMCQMip.png

**Comment by taherkhalil** [comment]
+1 this issue
@sathishpy  has your pull requested been accepted?
It seems this is still an issue.

**Comment by sathishpy** [comment]
I haven't opened the pull request yet as I am trying to figure out how to run bench-tests.

**Comment by sathishpy** [comment]
![rounding-fix-test](https://user-images.githubusercontent.com/26438479/31167255-195c77c6-a90f-11e7-9bf1-c53f51ffbfd4.gif)

**Comment by taherkhalil** [comment]
@sathishpy 
Sure - rounding seems to be a big prevailing issue and no one from the frappe foundation seems interested in resolving it.
Thanks for your hard work..
please do inform once you created a pull requested and whether it was accepted and added to main branch. :+1:
