### ISSUE TITLE
Customer DocType searchfields are ignored

### ISSUE THREAD

**Issue by faztp12** [frappe/erpnext#8821]
Hii
Searchfields in customer doctype is ignored by the link fields.
![capture](https://cloud.githubusercontent.com/assets/12441615/26031426/720f451e-3890-11e7-8205-df6c0d165c62.JPG)

In erpnext hooks, there is a `standard_queries` [hook](https://github.com/frappe/erpnext/blob/develop/erpnext/hooks.py#L139) overriding the searching of the customer doctype.

Please include the search field in the custom query. Searchfields are working for Supplier, so we can assume its working for every other doctypes without a `standard_query` override.

It works fine for the customer if we pass `searchfields` args in `get_query` of the link.
But this cant be done everywhere.

-----
Problem is here: https://github.com/frappe/frappe/blob/develop/frappe/desk/search.py#L33
searchfield parameter is sent empty, instead of fetching from doctype meta.
This applies to all custom overridden queries. Even those from `get_query` overrides.

Thank you

**Comment by vrms** [comment]
I get the impression you may know how this can be implemented. Is that correct?
If that's the case can you send a PR for this?

**Comment by faztp12** [comment]
I do not know if they left it like that on purpose or not.
The customer query hard codes the fields already defined in Search Fields of Customer DocType. [customer.py](https://github.com/frappe/erpnext/blob/develop/erpnext/selling/doctype/customer/customer.py#L150)

- Edit `search.py` to send search fields from doctype meta
- Edit `customer.py` to add the hard coded fields if it doesnt exist

**Comment by faztp12** [comment]
@mbauskar any update on this ? :)
