### ISSUE TITLE
Trial Balance For Party Report Auto Email Error

### ISSUE THREAD

**Issue by sumeetagra** [frappe/erpnext#8824]
Auto Email of the Report " Trial Balance for Party" sends a wrong report on mail or using the download option.

**Comment by MCD-50** [comment]
Refer this
https://github.com/frappe/erpnext/wiki/Issue-Guidelines

**Comment by tundebabzy** [comment]
Hello @sumeetagra
Please add more information about the problem. For now, I'm closing the issue but feel free to reopen with more information
