### ISSUE TITLE
Critical Error while posting Sales invoice REST API V8

### ISSUE THREAD

**Issue by adnanmunir83** [frappe/erpnext#8831]
![image](https://cloud.githubusercontent.com/assets/26667854/26049855/9105d644-396d-11e7-9b79-548519e8e402.png)

**while testing api with V8 i'm facing the above challange.  sales invoice without payment section is working fine.  but the moment i add payment i start getting this error message.  below is the code i'm posting.**

{
"cash_bank_account":"Cash - CP",
"is_pos":"1",
"submit_on_creation":"1",
"against_income_account":"Sales - CP",
"party_account_currency":"USD",
"owner":"administrator",
"price_list_currency":"USD",
"mode_of_payment":" Cash",
"customer_name":"Mehdi Hassan",
"update_stock":"1",
"company":"Test Company",
"customer":"Mehdi Hassan",
"territory":"All",
"is_opening":" No",
"customer_group":"Individual",
"naming_series":"MTS-",
"currency":"USD",
"debit_to":"Debtors - CP",
"remarks":" POS - 100306",
"posting_date":" 2017-05-08",
"selling_price_list":"PIP Selling",
"discount_amount":"",
"apply_discount_on":"",
"items":"FROBEN SR 200MG CAP",
"items":[
{
"cost_center":"Branch - CP",
"qty":"15",
"warehouse":"Branch - CP",
"pricing_rule":"7% Discount ",
"owner":"administrator",
"item_code":"FROBEN SR 200MG CAP",
"parenttype":" Sales Invoice",
"parentfield":"items"
}
],
"payments":[
{
"mode_of_payment":" Cash",
"amount":"282.6",
"account":"Cash - CP"
}
]
}

**Comment by joezsweet** [comment]
it seems conversion rate is missing

**Comment by adnanmunir83** [comment]
Thanks Joez for your reply.  the conversion rate is automatically picked by API once we supply "pricing_rule":"7% Discount ", parameter.

**Comment by MCD-50** [comment]
can you tell me exact steps to reproduce this error with input?

 You can refer this 
https://github.com/frappe/erpnext/wiki/Issue-Guidelines

**Comment by adnanmunir83** [comment]
hi MCD,
Thanks for the reply. the steps are below.  i already mentioned it above with data input.

to test the API, we are using "Post Man"
1. we get a successful login message.
2. to make sure sent a "get Request" for Sales Invoice"
3. we tried to make a sales invoice through API "without payment" which was successful.
4. when we tried to post sales invoice through API "with Payment" we are getting the exception.
i'm highlighting the payment entry in the below code. if we remove that it's working but the status of invoice is draft.  to make it a successful entry we need to send payment entry too.  with manual entry through ERP V8 with same parameters it's working. but with API it's generating exception.

Below is the data input.

{
"cash_bank_account":"Cash - CP",
"is_pos":"1",
"submit_on_creation":"1",
"against_income_account":"Sales - CP",
"party_account_currency":"USD",
"owner":"administrator",
"price_list_currency":"USD",
"mode_of_payment":" Cash",
"customer_name":"Mehdi Hassan",
"update_stock":"1",
"company":"Test Company",
"customer":"Mehdi Hassan",
"territory":"All",
"is_opening":" No",
"customer_group":"Individual",
"naming_series":"MTS-",
"currency":"USD",
"debit_to":"Debtors - CP",
"remarks":" POS - 100306",
"posting_date":" 2017-05-08",
"selling_price_list":"PIP Selling",
"discount_amount":"",
"apply_discount_on":"",
"items":"FROBEN SR 200MG CAP",
"items":[
{"cost_center":"Branch - CP",
"qty":"15",
"warehouse":"Branch - CP",
"pricing_rule":"7% Discount ",
"owner":"administrator",
"item_code":"FROBEN SR 200MG CAP",
"parenttype":" Sales Invoice",
"parentfield":"items"
}**],
"payments":[
{"mode_of_payment":" Cash",
"amount":"282.6",
"account":"Cash - CP"}]**
}

**Comment by MCD-50** [comment]
"amount":"282.6"
this is a string and not float
this needs to be a float.

**Comment by adnanmunir83** [comment]
Thanks MCD.

you are right i was passing all Boolean and integer as string.  

Thanks a lot for your help.  i got it working.

**Comment by MCD-50** [comment]
However, i sent a PR, which will automatically convert string amount to bool
