### ISSUE TITLE
Warehouse Renaming Issue

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#8842]
Hi,

There's an issue when trying to rename a warehouse to something that has a hyphen like 'New - Name'. Let's assume company abbreviation is ABC. The new ID is supposed to be New - Name - ABC but instead, the system names it as New - ABC

Kindly help resolve

Thanks

**Comment by tundebabzy** [comment]
Hello @Olawale1 
It seems like you are deleting the `- [abbreviation]` in the name field. Is there any special reason for doing that?

**Comment by Olawale1** [comment]
Hi @tundebabzy 

Thanks for your response. I'm not deleting anything... the system is deleting the part of the name after the first hyphen as explained in my post. That's the bug being reported

Thanks

**Comment by tundebabzy** [comment]
Ok. The rename gobbles gobbles up the last `- [abbreivation]` it finds. This is definitely a bug.

Thanks for the report. We'll fix ASAP

**Comment by Olawale1** [comment]
Hi @tundebabzy 

Well, the rename actually gobbles up the second part of the name and not the abbreviation. For example, I have a warehouse named 'Doha - ABC' (where ABC is the abbreviation of my company name). I want to rename to 'Abu - Dhabi - ABC'. Normally when I rename, I only need to enter 'Abu - Dhabi' and once I save, the system automatically adds the abbreviation so the name becomes 'Abu - Dhabi - ABC'. Currently however, the system names the warehouse as 'Abu - ABC'!

I however believe you already figured this out while testing

Thanks plenty

**Comment by tundebabzy** [comment]
:) I already figured it out. The fix would soon be merged
