### ISSUE TITLE
Renaming suggestion in the Role Permission Manager

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#8843]
- [ ] Given the issues received on support related to Permission, we could try some renaming to improve usability.

![screen shot 2017-05-15 at 7 21 16 pm](https://cloud.githubusercontent.com/assets/910238/26061145/b8fa2f56-39a4-11e7-9152-2be7d0ce80f9.png)

- [ ] In the Role Permission Manager, if Apply User Permission is checked, then option to select Link field should auto-populate.

After selection of link field based on which permission will be applied, user should be given the option to navigate to User Permissions rights from there.

In the Role Permission Manager, they just tick field “Apply User Permission”, but don’t understand the next step of creating User Permission Rule for each user.

**Comment by kennethsequeira** [comment]
Closing as user permission has been redesigned
