### ISSUE TITLE
When creating Material Request with multilevel BOM option it does not create Material Request for Items in the subassembly BOM

### ISSUE THREAD

**Issue by Arundhatii** [frappe/erpnext#8847]
Please refer the gif.
![material request issue](https://cloud.githubusercontent.com/assets/20164097/26071407/a30525ae-39c5-11e7-8cfe-7cfd94d978bb.gif)

**Comment by bcornwellmott** [comment]
Use the production planning tool to create MRs for multi-level BOMs
