### ISSUE TITLE
Kanban empty state cleanup

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#8849]
- [x] When the kanban page is first shown, the empty state with "Add a column" appears for a second. It should be a clean "loading" state.
- [x] When you press enter on a new card, the card disappears for a second and re-appears. It should remain static and maybe just disappear if the action fails.

**Comment by vrms** [comment]
we just went through an extensive labeling procedure for all issues. Would it make sense that ppl with write access to the labels would label issues they post themselves accordinggly right away?

**Comment by rmehta** [comment]
@vrms sorry it was an oversight. I don't think the callout was necessary though.
