### ISSUE TITLE
Kanban view - Duplicate Opportunities.

### ISSUE THREAD

**Issue by Arundhatii** [frappe/erpnext#8850]
The status of an Opportunity is correctly updated by moving the same in Kanban view. But the opportunities are being duplicated when we create a transaction from within the Opportunity.
Gif attached.
![kanban opportunity view](https://cloud.githubusercontent.com/assets/20164097/26091654/3df1dd46-3a2a-11e7-9191-1c54c35c5bad.gif)

**Comment by vrms** [comment]
@netchampfaris can you kindly assign a label to issues assigning to anyone in the future?
