### ISSUE TITLE
Server Error in Dropbox Settings

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#8860]
Reported via WN-SUP25101

I could save Dropbox Setting fine. When click on button "Allow Dropbox Access", getting following error message.

![screen shot 2017-05-16 at 12 13 53 pm](https://cloud.githubusercontent.com/assets/910238/26101878/5742edaa-3a50-11e7-8418-bc077cda573b.png)

**Comment by rohitwaghchaure** [comment]
The App Access Key and App Secret Key are not valid, kindly recreate them and check
![screen shot 2017-05-18 at 1 07 18 pm](https://cloud.githubusercontent.com/assets/8780500/26191312/034758ea-3bcb-11e7-8131-eb07e9e47654.png)

**Comment by rohitwaghchaure** [comment]
I am closing the issue now, feel free to reopen the issue if solution not work
