### ISSUE TITLE
Support Portal

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#8861]
The support portal should be the entry point for all customer support

- [x] Home Page (/help)
  - [x] List of Help Categories
  - [x] Button to open a new ticket
- [x] Search
  - [x] results to show title and not name
- [x] Unified view for the emails and comments in issue's timeline

**Comment by umairsy** [comment]
Example of Exotel Support portal. We have an account on Exotel, if needed for further specification.

<img width="1180" alt="screen shot 2018-05-03 at 4 01 28 pm" src="https://user-images.githubusercontent.com/910238/39572076-73636298-4eeb-11e8-89a0-ef2f5c284cc9.png">

**Comment by umairsy** [comment]
Related issue: https://github.com/frappe/erpnext/issues/12962
