### ISSUE TITLE
UOM

### ISSUE THREAD

**Issue by hithamIsmail** [frappe/erpnext#8870]
hello dears 

please i want to make p.o of item in cartoon (1*12 unit) , and selling the same item in unit 
for example : i receive item in cartoon (1*12 unit ) the price of cartoon = 120 $
and i will selling the 1 unit in 10 $ 
how can i make this please help me ????

**Comment by tundebabzy** [comment]
Hello @hithamIsmail

We have a forum where we answer these kinds of questions. You will get very helpful answers there. 

Visit https://discuss.erpnext.com
