### ISSUE TITLE
TIN Number / GST Number for VAT Returns in India

### ISSUE THREAD

**Issue by manivk** [frappe/erpnext#8876]
In India, all purchase invoices need to capture the TIN number of the supplier mandatorily and it needs to be uploaded in the VAT returns, there is no way to show the same right now in the purchase register in ERPNext. Would be nice to have a field there for the same which will capture the TIN Number and show it in the Purchase Register for easy VAT uploads.

Thanks
Mani.

**Comment by sagarvora** [comment]
This is being handled in #8711, closing.
