### ISSUE TITLE
Create Stock Summary Reports

### ISSUE THREAD

**Issue by dottenbr** [frappe/erpnext#8884]
Currently we have ```Stock Summary``` which generates stock summaries per warehouse. In Addition we need two reports:

## Total Stock Summary:

The total stock summary in the whole system, regardless of warehouse or company.

* Item
* Item Name
* Item Group
* Stock UOM
* Quantity

## Company Stock Summary:

The total stock summary per company, regardless of warehouse.

* Item
* Item Name
* Item Group
* Stock UOM
* Quantity
* Company

**Comment by dottenbr** [comment]
@nabinhait any opposition against or suggestions for this becoming core?

**Comment by nabinhait** [comment]
@dottenbr Those should not be 2 separate reports. Instead we can add another filter "Group By" and the options will be "Blank / Warehouse / Company". The default group by should be based on warehouse. If "Group By" not selected (Blank), then show qty for all warehouse for filtered company. If  "Group By" is selected as "Company", then Company filter will be non-mandatory/hidden and it wil show company-wise qty for all warehouses.

**Comment by creamdory** [comment]
Hi @dottenbr @nabinhait will this be a totally separate report independent of the current Stock Summary report or would be best to integrate?

**Comment by nabinhait** [comment]
Ok, lets do it separately

**Comment by creamdory** [comment]
Noted @nabinhait . Thanks!

**Comment by creamdory** [comment]
Hi @nabinhait ! I have been working with the report and has this so far. I haven't had the "Hiding" of the Company field yet when selecting "Company" group by, instead has a validation for now. Also, I still have been missing something with the query and will continue figuring out. Just wanted to share where we are. Thanks!
![total stock summary](https://cloud.githubusercontent.com/assets/21003054/26825126/6f5ef5ea-4ae6-11e7-981b-e44f9c785094.gif)

**Comment by creamdory** [comment]
Hi @nabinhait ! I somehow fixed the query problem. Please comment if logic is correct according to your specification. 
![fixed total stock summary](https://user-images.githubusercontent.com/21003054/26862684-e983ef3a-4b7f-11e7-896d-2e2d0ac3fb7c.gif)
