### ISSUE TITLE
Quoted Item Comparison Error

### ISSUE THREAD

**Issue by SYMBARCELONA** [frappe/erpnext#8886]
![image](https://cloud.githubusercontent.com/assets/27690279/26099186/4733ce6e-3a2a-11e7-8cd0-6c38026a0a34.png)

**Comment by bcornwellmott** [comment]
Can you submit the console logs (CTRL-Shift-I in Chrome)?

**Comment by SYMBARCELONA** [comment]
![image](https://cloud.githubusercontent.com/assets/27690279/26253428/afa3f86c-3cb3-11e7-8dae-9e36d5c3e3e2.png)

**Comment by SYMBARCELONA** [comment]
is this what you need? I am not very good in programming
