### ISSUE TITLE
Error in user page when clicking on Analytics and Customer Role

### ISSUE THREAD

**Issue by maysaa** [frappe/erpnext#8889]
![screenshot from 2017-05-17 15-04-51](https://cloud.githubusercontent.com/assets/5780171/26153224/1b3fd9f8-3b13-11e7-8862-484cccb186c0.png)

**Comment by jwrober** [comment]
Please provide more commentary. What is the setup like? Any customization that could be impacting things? What are the steps to reproduce?

**Comment by PawanMeh** [comment]
Closing this for now, if there is any replication instructions kindly re-open with the steps
