### ISSUE TITLE
Customize Feedback form

### ISSUE THREAD

**Issue by jwrober** [frappe/erpnext#8892]
The feedback form seems to be "in code" and not a standard document type that can be altered. I would like to suggest that this be done and then allow for installation specific feedback so that we could

- ask more questions
- setup a survey and send via a notification
- link feedback to different document types or modules or even custom product types or something.

See https://discuss.erpnext.com/t/customize-feedback/22009 - for initial discussion on this.

**Comment by kennethsequeira** [comment]
Closing since Feedback Form is deprecated.
