### ISSUE TITLE
Make "Amount in words" spell three decimals

### ISSUE THREAD

**Issue by mfazilp** [frappe/erpnext#8895]
Hi,

Am using erpnext for bahrain. Here we need three decimal place for the amounts. It is working perfectly. But when it convert to words, only converting two digits of decimal place.

For eg: if total amount is 428.300, then displaying Four hundred and Twenty eight and thirty Fils only instead of  Four hundred and Twenty eight and three hundred Fils only

Attached snap shot for reference.
![untitled](https://cloud.githubusercontent.com/assets/8024554/26165758/c743d620-3b39-11e7-91a6-fb104dab8f95.png)

**Comment by tundebabzy** [comment]
fixed in frappe/frappe/3358

**Comment by mfazilp** [comment]
Thanks
