### ISSUE TITLE
Item Variant should have some fields editable

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#8901]
In a Variant Item, following fields should be editable.

- Item Name
- Description
- Valuation Rate
- Standard Selling Rate
- Serial No. Naming Series

Inspection Criteria
- Complete section should be editable

Buying Section
- Default Supplier
- Manufacturer
- Manufacturer Part No.
- Supplier Part No.

Selling Section
- Item Customer Details (child table)

Fields in the Item for which No Copy should be enabled.

- Disable
- End of Life

**Comment by rmehta** [comment]
Fixed. Waiting for merge+release.
