### ISSUE TITLE
Once primary key is generated, do not allow changing Series

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#8911]
Raised via WN-SUP25185

Once the Sales Invoice is generated, Series field is not visible. But one can still edit value in the Series field from Report Builder, or (I suspect) from Data Import Tool as well.

If a primary key is generated for a document, then value in the Series field should freeze.

**Comment by tundebabzy** [comment]
Hello @umairsy 
Please follow progress on this issue in frappe/frappe#3460

**Comment by tundebabzy** [comment]
Fixed
