### ISSUE TITLE
Customer Credit Limit

### ISSUE THREAD

**Issue by AravindPranera** [frappe/erpnext#8914]
In ERPNEXT, we require a Customer Credit limit to be set based on amount.

**Comment by strixaluco** [comment]
I apologize, but "require" doesn't seem to be correct word in this case.

**Comment by adityaduggal** [comment]
There is already a Credit Limit option in the erpnext based on amount only, the requirement does not seem to be clear

**Comment by strixaluco** [comment]
@adityaduggal, in ERPNext: v8.0.28 I see only these two options:

![credit limit](https://cloud.githubusercontent.com/assets/10875796/26236321/58734ac2-3ca2-11e7-9756-4066b928a870.png)

**Comment by adityaduggal** [comment]
@strixaluco This is for Credit Days and NOT CREDIT LIMIT. I think you are mis-understanding this drop-down.

I think this is a non-issue and should be CLOSED.

**Comment by AravindPranera** [comment]
We need  a customer credit limit based on amount, already mentioned in the topic itself. @adityaduggal

**Comment by strixaluco** [comment]
@adityaduggal, I can see, that this is for credit days. Can you please advise where is the feature mentioned by OP?

**Comment by adityaduggal** [comment]
@AravindPranera Already customer credit limit is based on AMOUNT, it would be great if you could explain your requirement more descriptively or I would be forced to close this issue as it does not explain the problem at all
@strixaluco which feature are you talking about I am not aware about the feature you are talking about

**Comment by AravindPranera** [comment]
@adityaduggal for us there is no option for amount. Refer my screenshot
![customer credit limit 1](https://cloud.githubusercontent.com/assets/28756911/26249673/1ed80cee-3cc5-11e7-98e1-708837007eca.png)
![customer credit limit](https://cloud.githubusercontent.com/assets/28756911/26249674/1eda1994-3cc5-11e7-969c-30d7c75b4a9a.png)

**Comment by strixaluco** [comment]
Heck, I couldn't imagine this was not a feature request, but bug report. @AravindPranera, you have to follow [issue guidelines](https://github.com/frappe/erpnext/wiki/Issue-Guidelines) when open the issue.
