### ISSUE TITLE
keyboard shortcuts do not work when caps lock is engaged.

### ISSUE THREAD

**Issue by cgpurbaugh** [frappe/erpnext#8917]
see title

**Comment by strixaluco** [comment]
Frappe/ERPNext versions? Which browsers / DEs / their versions this has been tested on?

Haven't faced any problem with ERPNext: v8.0.28 / Frappe Framework: v8.0.46 @ Firefox ESR 45.9.0 @ GNOME Shell 3.14.1

**Comment by tundebabzy** [comment]
Hello @cgpurbaugh 
Is there any particular shortcut that isn't working for you or is it all shortcuts? My caps lock is mostly on when using ERPNext and I have not ever experienced such.

**Comment by cgpurbaugh** [comment]
I don't know what DEs are, but on chrome in `ctrl + s` saves the document, `ctrl + S` attempts to save the webpage.  `ctrl + b` makes a new record, but `ctrl + B` does nothing.  In Microsoft Edge, `ctrl + up arrow` and `ctrl + down arrow` does nothing, regardless of caps lock.

**Comment by cgpurbaugh** [comment]
Looks like this is fixed in V8, closing.
