### ISSUE TITLE
Scrollable Editable Grid

### ISSUE THREAD

**Issue by jof2jc** [frappe/erpnext#8924]
Since editable grid is introduced in v7..it's very nice but it eliminates user overview at important informations..users would have to enter details view which is not comfortable..

Switching this off also not a solution since we need faster entry..

It would be great if editable grid to be scrollable both vertically and horizontally...just like in report.. This way user can show as many as child fields they want..

Also this way allow us to just scroll items table without loosing whole view of the form..

**Comment by hachiken** [comment]
+1

**Comment by faztp12** [comment]
+1

**Comment by mhbu50** [comment]
+1

**Comment by rmehta** [comment]
Dual scrolling is a bad design also not friendly on smaller screens. Closing this for now.
