### ISSUE TITLE
When deleting emails dialog box 'Communication is not found' erroneously appears

### ISSUE THREAD

**Issue by joolsr** [frappe/erpnext#8935]
Using ERPNext: v8.0.29 (master)
Frappe Framework: v8.0.47 (master)

This problems occurs around 50% of the time I delete emails.

When I delete an email or a few emails especially I receive the following dialog box 
![document-1-page001](https://cloud.githubusercontent.com/assets/934876/26246249/fc15591c-3c8f-11e7-9769-9d816840445c.png)

The communication it refers to seems to be the email itself, so there is some kind of race condition. I think its related to the speed of the email deletion against the system frappe response. ie if frappe responds slower than the email after the email is deleted then the system is reporting that there is no email (communication) when its already been removed.

**Comment by joolsr** [comment]
As a test, I added my gmail account on my test account on erpnext.com. When I delete emails I do not see this problem any more. I think its linked to other issues Ive seen ie https://github.com/frappe/erpnext/issues/8934

I also created a fresh install on a clean VPS with same spec as before. Again emails can be deleted without issues, css rendered perfectly and also issues I got with 'Communication not found ' I also don't see any more.

So something in an earlier commit has caused problems for me.
I will keep this open for now as as a standard update has caused these problems for me, and this info may help someone with the same issue.

**Comment by sagarvora** [comment]
Hi @joolsr, should we close issue this now?

**Comment by joolsr** [comment]
No, I still see this issue. Oddly, I only see it with one email account and not the other. whether its something that Gmail does differently (which works) compared to a std IMAP/Exim setup (which has this problem) I don't know.

I 'll see if I can debug this further tomorrow.

**Comment by manassolanki** [comment]
Hi @joolsr ,
Any leads?

**Comment by joolsr** [comment]
I can arrange a screencast if this helps? I will look into this further. Its a very annoying issue ...

**Comment by manassolanki** [comment]
Yes, for sure you can share a GIF along with the console error.

**Comment by joolsr** [comment]
Here it is. There is no console error, but it shows what happens.
![anim](https://user-images.githubusercontent.com/934876/27632948-39ce6742-5bf5-11e7-99a3-45ff6960d3fe.gif)

**Comment by joolsr** [comment]
I am also seeing associated errors with 'cannot save' errors when closing emails . If I add Amend permissions this fixes this but then emails are editable and a plain text email is rendered without whitespace so becomes a jumbled mess.

**Comment by joolsr** [comment]
Ok. I managed to debug this much further and now understand exactly what is cauising the error to occur.
You can find more details here https://discuss.erpnext.com/t/bug-when-deleting-emails-with-file-attachments/25896/1

But to be concise.

If you delete an email (communication) that has an atatchment with it, you get the error. No console errors are detected here. I realised that the number of times the error message appeared was alwasy the same as the number of email attachments for the email that is being deleted.

A better way of demonstrating this and also which actually shows a console error that can be debugged further is to look at this a different way around.

If I go to https://joolsr.erpnext.com/desk#query-report/Permitted Documents For User 

ie  the menu in Setup and click on an item in the **Name** column, ie a file attachment from an email and delete this item, I receive an error in the console as below. See the video below.

ie Uncaught TypeError : cannot read property '__islocal' of undefined.
also Uncaught (in promise) TypeError : cannot read property '__islocal' of undefined

![ezgif com-crop](https://user-images.githubusercontent.com/934876/28081384-fb5c31fc-6666-11e7-8fb3-d4306fc00734.gif)

**Comment by joolsr** [comment]
any word on fixing this bug ?

**Comment by mbauskar** [comment]
@joolsr,

Tried replicating the issue but deleting email worked just fine please check the below gif

![mail](https://user-images.githubusercontent.com/11224291/29553850-a6bb062e-873a-11e7-99e9-b720dcd41995.gif)

To delete the attachments please give the delete permissions for File doctype to the user.

Also deleting the file from File > Menu > Delete worked without any error in the console
![file](https://user-images.githubusercontent.com/11224291/29553919-e7a9b400-873a-11e7-8fa3-dfaa9ea4b747.gif)

**Comment by joolsr** [comment]
This has been fixed with this hotfix https://github.com/frappe/frappe/commit/cb87bb5b587c55024de36f32f3020323be764e28 and I can now delete emails with attachments ;-)
