### ISSUE TITLE
Dropbox Access - Wrong link

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#8948]
Reported via: https://discuss.erpnext.com/t/dropbox-backup-allow-dropbox-access-url-wrong/24012

When Dropbox 'allow dropbox access' button is pressed, a page pop up shows unreachable because the url is pointing to

https://www.dropboxapi.com/1/oauth/authorize?.......................

Just rename dropboxapi.com to dropbox.com and refresh the same page, it will work.

**Comment by tundebabzy** [comment]
This is possibly because we are using the deprecated client. Will investigate and move to hotfix

**Comment by tundebabzy** [comment]
Please follow this issue on frappe/frappe#3378
