### ISSUE TITLE
Inaccurate figures on invoices

### ISSUE THREAD

**Issue by tundebabzy** [frappe/erpnext#8953]
Related to #8893, #8952  and #8910 
I have come across this issue again. This time it's not in the tax calculation.

**Before saving**
![screenshot from 2017-05-21 15-34-17](https://cloud.githubusercontent.com/assets/818803/26284831/26524fc0-3e3c-11e7-8367-b10e8e83b7f6.png)
![screenshot from 2017-05-21 15-34-24](https://cloud.githubusercontent.com/assets/818803/26284835/34c49612-3e3c-11e7-9806-1d06843945f9.png)

**After saving**
![screenshot from 2017-05-21 15-34-38](https://cloud.githubusercontent.com/assets/818803/26284842/47e08bd4-3e3c-11e7-8021-80409787fe41.png)
2 kobo was magically added.

**Comment by paulator** [comment]
I think #6954 is related as well.
