### ISSUE TITLE
Stock Summary Report redirecting to Stock Balance report

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#8954]
Stock module has Stock Summary as a report. But when click on that report, link is updated as:

https://demo.erpnext.com/desk#stock-balance

Checked Reports list and didn't find any report called Stock Summary.

**Comment by umairsy** [comment]
Also reported via Issue WN-SUP25296

**Comment by nabinhait** [comment]
fixed

**Comment by abdulrahim313** [comment]
Done
