### ISSUE TITLE
POS Invoice - Sales Return should not allow entering Payment Amount more than total

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#8960]
Reported via WN-SUP24866

Steps:

1. User created a POS Invoice of 100.
2. Then created Sales Return entry against the Sales Invoice.
3. In the Sales Return entry, user could enter -150 as a payment amount, where as total of the return invoice was just -100.

In the return entry, user should not be allowed to enter the payment amount more than the invoice amount.

**Comment by nabinhait** [comment]
Fixed via #8974
