### ISSUE TITLE
enhancement: build test for documents calculations/taxes/totals

### ISSUE THREAD

**Issue by almeidapaulopt** [frappe/erpnext#8964]
I found a lots of issues reported (example #8953) to taxes calculations  

I think that this king of bugs could be abolished if there is a complete list of tests for this kind of calculations. 

This is the a very dangerous kind of bugs for an ERP. You can live with this bugs for a long time without notice (almost nobody will confirm all these calculations and I can understand, this is a basic thing) and could be very costly to the company.

**Comment by nabinhait** [comment]
Fixed via #10135
