### ISSUE TITLE
Get item inside Request for Quote

### ISSUE THREAD

**Issue by graphskill** [frappe/erpnext#8965]
When we create an RFQ we save it for later so we can add more items to it

Now, when we  open the RFQ and choose "Get Items from Material Request" then SAVE options has gone, and we can only submit. But we need to be able to save again before submitting

Save is available:

![image](https://cloud.githubusercontent.com/assets/925619/26311725/354a80da-3efd-11e7-8efe-2be6e84a5054.png)

Choose get items from material request

![image](https://cloud.githubusercontent.com/assets/925619/26311746/48444cb6-3efd-11e7-85fe-3c0e8527d4f0.png)

Save has now gone

![image](https://cloud.githubusercontent.com/assets/925619/26311785/63a2c3ac-3efd-11e7-914a-7ed4235ed9e0.png)

**Comment by tundebabzy** [comment]
**How to reproduce**
1. Create a RFQ and save as draft.
2. Open the draft RFQ and amend it by clicking on 'get items from > material request
