### ISSUE TITLE
Default Source Warehouse field not showing up when duplicating material receipt

### ISSUE THREAD

**Issue by mobentec** [frappe/erpnext#8967]
If you look at this screen shot, notice how some have default source warehouse and some don't.

![2017-05-22 at 12-10-44](https://cloud.githubusercontent.com/assets/6663120/26318211/6a31296c-3ee8-11e7-9e63-805640872a24.png)

I noticed, that when I duplicate a material receipt, it does not put the default source warehouse.  It seems like it puts in a blank instead.

ERPNext: v8.0.8 (master)
Frappe Framework: v8.0.7 (master)

**Comment by nick9822** [comment]
@mobentec 
Actually its kept like that by default setting. You can unset option "No Copy" in the Doctype which can be only be achieved if you are on self hosted version.
