### ISSUE TITLE
Feature request: Mass print from list view

### ISSUE THREAD

**Issue by AminfiBerlin** [frappe/erpnext#897]
Dear ERPNext team,

a feature that is very very important for us is to be able to select multiple sales invoices, delivery notes and print all of them at once.
I assume this should be now easy to have as the server side HTML generating code works well now.

Best,

Amin from Fritzing

**Comment by rmehta** [comment]
This can now be done via the API:


You can write a script do download PDF via the API

`/api/method/frappe.templates.pages.print.download_pdf?doctype=Sales%20Invoice&name=SINV-000XX&format=Standard&no_letterhead=0`

Using: https://github.com/frappe/frappe-client

**Comment by goldrag1** [comment]
Hi rmehta,
The query in the above example is for print single SI only. How to print multiple SI? Given we already have document ID.
Thanks.

**Comment by grainnewalsh** [comment]
This is a feature that we also require. Our use case is similar, we need to print out the delivery notes for each delivery route as we need to obtain a customer signature for proof of delivery. It is desirable to have the option to select a number of Delivery Notes and be able to issue a bulk "Print Selected" command that will either send a print command to print each delivery note, or generate a PDF containing a copy of each delivery note (on a separate page) and download it. 
This bulk print functionality would also be useful for other document lists, for example Sales Invoices - our use case is that we have a number of customers who insist on paper copy invoices to be sent after each delivery. Again, we want to be able to select a number of sales invoices and issue a single print command to print them all. 

Many thanks
Gráinne

**Comment by rmehta** [comment]
This is implemented in the latest.
