### ISSUE TITLE
emails not updating

### ISSUE THREAD

**Issue by glibersat** [frappe/erpnext#8970]
Hi,

We're having troubles with email synching. I can find this error in the error logs, any idea ? Thanks

> {'retry': 0, 'log': <function log at 0x7f98de57a0c8>, 'site': u'erp.xxxxx.com', 'event': u'all', 'method_name': 
> u'pull_from_email_account', 'method': <function pull_from_email_account at 0x7f98de4b2668>, 'user': u'Administrator', 'kwargs': {'email_account': u'Guillaume'}, 'async': True, 'job_name': u'pull_from_email_account|Guillaume'}
> Traceback (most recent call last):
>   File "/home/glibersat/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 65, in execute_job
>     method(**kwargs)
>   File "/home/glibersat/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 698, in pull_from_email_account
>     email_account.receive()
>   File "/home/glibersat/frappe-bench/apps/frappe/frappe/email/doctype/email_account/email_account.py", line 253, in receive
>     emails = email_server.get_messages()
>   File "/home/glibersat/frappe-bench/apps/frappe/frappe/email/receive.py", line 115, in get_messages
>     uid_list = email_list = self.get_new_mails()
>   File "/home/glibersat/frappe-bench/apps/frappe/frappe/email/receive.py", line 178, in get_new_mails
>     response, message = self.imap.uid('search', None, self.settings.email_sync_rule)
>   File "/usr/lib/python2.7/imaplib.py", line 773, in uid
>     typ, dat = self._simple_command(name, command, *args)
>   File "/usr/lib/python2.7/imaplib.py", line 1088, in _simple_command
>     return self._command_complete(name, self._command(name, *args))
>   File "/usr/lib/python2.7/imaplib.py", line 918, in _command_complete
>     raise self.error('%s command error: %s %s' % (name, typ, data))
> error: UID command error: BAD ['Error in IMAP command UID SEARCH: Invalid UID messageset']

**Comment by tundebabzy** [comment]
Hello @glibersat
This isn't a problem from ERPNext so you need to investigate your IMAP server. 

This kind of question is better suited for the discussion  forum  https://discuss.erpnext.com
