### ISSUE TITLE
Stock Balance freezes

### ISSUE THREAD

**Issue by emakis** [frappe/erpnext#8982]
Stock Summary report doesn't seem working both in my localhost and in the erp-eso server. Getting frozen and the message in chrome dev tools is "Uncaught TypeError: Cannot read property 'sort_field' of undefined", as shown in the gif
![stock_balance_freezes](https://cloud.githubusercontent.com/assets/13694115/26357384/c7948f6e-3fd7-11e7-9ce7-a03fb802d5f1.gif)

**Comment by nabinhait** [comment]
fixed
