### ISSUE TITLE
item_group server exception when no items to view.  Line 43 in item_group.html

### ISSUE THREAD

**Issue by bglazier** [frappe/erpnext#8983]
line 43:
<div class="text-muted">{{ __("No items listed") }}.</div>

 in /apps/erpnext/erpnext/templates/generators/item_group.html
throws a server exception.

Removing __ solves this problem:

<div class="text-muted">{{ ("No items listed") }}.</div>

**Comment by ashwinisave35** [comment]
Hi,
We have tested on test instance and it is not reproducible. Will you please provide us more details or screenshot related to this issue.

**Comment by rohitwaghchaure** [comment]
The issue has been fixed
