### ISSUE TITLE
Error when creating Opportunity from Lead

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#8986]
Hi,

There's an issue that prevents an Opportunity from being created from (or linked to) a Lead:

Error: Value missing for: Customer

Please check

Kind regards,

**Comment by manassolanki** [comment]
Fixed, This is because of customization in which removed the mandatory field. If issue still persists, please reopen

**Comment by Olawale1** [comment]
Hi @manassolanki

Trust you're doing well. The issue persists. Please find screenshot below:

![opportunity from lead issue](https://cloud.githubusercontent.com/assets/9269337/26688538/cd00fb3a-46ea-11e7-92ea-0cd36d7a49c6.png)

This is on a cloud-hosted account

ERPNext: v8.0.42 (master)

Thanks

**Comment by Olawale1** [comment]
Hi @manassolanki 

The issue was still persistent but your comment gave me an idea of what to do. I just manually unchecked the mandatory option via customize form and it's okay now

Thanks
