### ISSUE TITLE
 Login attempts Administrator Warning!

### ISSUE THREAD

**Issue by Helkyd** [frappe/erpnext#9005]
Hi,
How can we Administrators of ERPNext know that a user has tried more than 3/5 times to login and did not succeeded?
By checking the Authentication Log but why does not the system informs the Admin of the wrong attempts and lock the account for XXXX amount of time.

This should be a security concern.

**Comment by mhbu50** [comment]
+1

**Comment by ckosiegbu** [comment]
+1

**Comment by Helkyd** [comment]
This the same as this opened ticket 

https://github.com/frappe/frappe/issues/1645

**Comment by manassolanki** [comment]
Duplicate issue. This discussion can be continued on https://github.com/frappe/frappe/issues/1645
