### ISSUE TITLE
Problems with rest api creating quotations

### ISSUE THREAD

**Issue by woischke** [frappe/erpnext#9006]
Sending the following json string to rest api creates a quotation without customer and items 

http://erpnext-dev.de/api/resource/Quotation

 { 
 "data": {
 	"quotation_to": "Customer",
	"selling_price_list": "Standard-Vertrieb",
	"territory": "Hamburg", 
	"transaction_date": "2017-05-22",
	"company": "BRÜGGEMANN DÄCHER GmbH",
	"conversion_rate": 1, 
	"currency": "EUR", 
	"customer": "Mustermann",
	"customer_name": "Mustermann",
	"doctype": "Quotation", 
	"base_grand_total": 1000.0,
	"grand_total": 1000.0, 
	"order_type": "Sales", 
	"plc_conversion_rate": 1, 
	"price_list_currency": "EUR",
	"items": { 
	"base_amount": 1000.0,
	"base_rate": 100.0,
	"description": "AKS PIXX-Transp.Qua.50cm TRAN Taubenstopleiste/Kunstst/V2A-Spikes",
	"doctype": "Quotation Item",
	"item_code": "35013",
	"item_name": "AKS PIXX-Transp.Qua.50cm TRAN Taubenstopleiste/Kunstst/V2A-Spikes",
	"parentfield": "items",
	"qty": 10.0,
	"rate": 19,
	"uom": "M",
	"stock_uom": "M",
	"conversion_factor": 1.0,
	"docstatus": 1
	} 
	}
}

answer from the server 

{
  "data": {
    "additional_discount_percentage": 0,
    "base_in_words": "",
    "campaign": null,
    "naming_series": "QTN-",
    "creation": "2017-05-24 16:31:25.534002",
    "doctype": "Quotation",
    "currency": "EUR",
    "conversion_rate": 1,
    "owner": "frank.woischke@zedach.eu",
    "total": 0,
    "shipping_rule": null,
    "customer_name": null,
    "taxes_and_charges": null,
    "language": null,
    "select_print_heading": null,
    "modified_by": "frank.woischke@zedach.eu",
    "order_type": "Sales",
    "lead": null,
    "title": "",
    "base_total": 0,
    "selling_price_list": "Standard-Vertrieb",
    "supplier_quotation": null,
    "tc_name": null,
    "amended_from": null,
    "transaction_date": "2017-05-24",
    "contact_display": null,
    "docstatus": 0,
    "territory": null,
    "company": "BRÜGGEMANN DÄCHER GmbH",
    "address_display": null,
    "letter_head": "BRÜGGEMANN",
    "terms": null,
    "ignore_pricing_rule": 0,
    "parent": null,
    "base_rounded_total": 0,
    "quotation_to": "Customer",
    "total_taxes_and_charges": 0,
    "grand_total": 0,
    "base_discount_amount": 0,
    "customer_address": null,
    "contact_email": null,
    "base_total_taxes_and_charges": 0,
    "contact_mobile": null,
    "items": [],
    "base_grand_total": 0,
    "discount_amount": 0,
    "customer": null,
    "order_lost_reason": null,
    "base_net_total": 0,
    "enq_det": null,
    "name": "QTN-00058",
    "idx": 0,
    "rounded_total": 0,
    "shipping_address_name": null,
    "price_list_currency": "EUR",
    "modified": "2017-05-24 16:31:25.534002",
    "taxes": [],
    "plc_conversion_rate": 1,
    "parenttype": null,
    "net_total": 0,
    "status": "Draft",
    "source": null,
    "shipping_address": null,
    "apply_discount_on": "Grand Total",
    "contact_person": null,
    "in_words": "",
    "customer_group": null,
    "parentfield": null
  }
}
the customer and items are not recognized by the system

**Comment by bcornwellmott** [comment]
You need to use square brackets around the array items. For example:

```
{
"data": {
"quotation_to": "Customer",
"selling_price_list": "Standard-Vertrieb",
"territory": "Hamburg",
"transaction_date": "2017-05-22",
"company": "BRÜGGEMANN DÄCHER GmbH",
"conversion_rate": 1,
"currency": "EUR",
"customer": "Mustermann",
"customer_name": "Mustermann",
"doctype": "Quotation",
"base_grand_total": 1000.0,
"grand_total": 1000.0,
"order_type": "Sales",
"plc_conversion_rate": 1,
"price_list_currency": "EUR",
"items": [{
"base_amount": 1000.0,
"base_rate": 100.0,
"description": "AKS PIXX-Transp.Qua.50cm TRAN Taubenstopleiste/Kunstst/V2A-Spikes",
"doctype": "Quotation Item",
"item_code": "35013",
"item_name": "AKS PIXX-Transp.Qua.50cm TRAN Taubenstopleiste/Kunstst/V2A-Spikes",
"parentfield": "items",
"qty": 10.0,
"rate": 19,
"uom": "M",
"stock_uom": "M",
"conversion_factor": 1.0,
"docstatus": 1
}]
}
}
```

I'm not sure about the Customer issue. Does it match the docname of the Customer exactly? The docname can be different then the customer name (hence why there is a Customer field and Customer Name field). The Customer is a Link field which needs to match the Customer doctype.

**Comment by woischke** [comment]
Thank you for your reply but nothing has changed. Still he does not recognize the customer and the articles either.

**Comment by woischke** [comment]
Hallo everybody, can anybody help me? On thursday we have got a big presentation for ERP-Next. 
and we need this function for an integration of SAP to ERP-Next.
Kind regards Frank Woischke

**Comment by bcornwellmott** [comment]
I'd suggest posting on the discuss.erpnext.com forum.
You will get better help there.

**Comment by woischke** [comment]
Bevor Posting here i created a discussion 

https://discuss.erpnext.com/t/problems-rest-api-quotation/

**Comment by tundebabzy** [comment]
Marked as solved in forum post.
