### ISSUE TITLE
Option for Exporting Price List per Item Brand (Suggestion)

### ISSUE THREAD

**Issue by ai-erp** [frappe/erpnext#9007]
Hi There, I believe it is important to have option for exporting Item price List per brand in ERPNext.
This is for the purpose of checking prices and updating it based on brand names. Most of the time, customers are asking for Price List of Items for a selected Brand. Right now, we can only export per Price List irregardless of the brand of the item.

**Comment by jwrober** [comment]
Why don't you just customize the item price form and add a read only lookup field of the brand on the item? Then you can add that field to the item list report and create filters on it.

**Comment by ai-erp** [comment]
Hi @jwrober , i have thought about customizing it, but i am afraid it might incur error upon updates. I have tried it in my test account but it is not fetching data of the brand. i am not sure if i am missing something on that. can you help?

![itemprice-read only-brand](https://cloud.githubusercontent.com/assets/16744099/26439894/0f04c206-413b-11e7-96fa-dad9f28a7b95.jpg)

**Comment by jwrober** [comment]
I think you need brand.brand in options. Existing records don't get the data, only new ones do. You can edit  existing records and at save the data will pull in.

**Comment by bohlian** [comment]
Perhaps you can explore creating a custom query report and putting the following query in. Also you can manually filter the brand by just typing into the filter section. Doubt its very useful for everyone so maybe a custom report will do..

```
SELECT DISTINCT
	`tabItem`.`brand`,
	`tabItem Price`.`price_list`
	
from `tabItem`

LEFT JOIN `tabItem Price`
	ON `tabItem Price`.`item_code` = `tabItem`.`name`
	
WHERE `tabItem Price`.`price_list` <> '' AND
	`tabItem`.`brand` <> ''
```

**Comment by dj12djdjs** [comment]
Closing, It is possible to export price list based on brand criteria.
