### ISSUE TITLE
Fraction in UOM not allowed while Selling, but allowed on Purchase! 

### ISSUE THREAD

**Issue by mdwala** [frappe/erpnext#9012]
In Sales Invoice, Fraction in UOM not allowed, 
Even when - nos is whole after fraction | UOM Case is not Checked as whole number | Already accepting Fraction while Purchasing

Example, 1 case = 100, 0.5 case(50 nos) not allowed.

https://discuss.erpnext.com/t/fraction-in-uom-not-allowed-while-selling-but-allowed-on-purchase/24166?u=mdwala

**Comment by mdwala** [comment]
As nabinhait assigned ashwinisave35, how much time it will take?

**Comment by umairsy** [comment]
Can you please share the screenshots to help this case. An screenshot of UoM, and validation message received in the Sales Invoice.
