### ISSUE TITLE
Salary calculation Error.

### ISSUE THREAD

**Issue by Arundhatii** [frappe/erpnext#9013]
Reported via https://discuss.erpnext.com/t/error-in-salary-calculation/24136

Employees having joining date in this month (May 2017), even after keeping Depends on LWP  component unchecked, it calculates amount on pro-rata bases.
Hence amount like Professional Tax is also calculated on Pro-rata bases by taking working days according to Date of Joining.
![screen shot 2017-05-24 at 11 18 07 pm](https://cloud.githubusercontent.com/assets/20164097/26417843/e8efce66-40d7-11e7-9604-6ff08303fd33.png)
![screen shot 2017-05-24 at 11 20 35 pm](https://cloud.githubusercontent.com/assets/20164097/26417875/02f89c84-40d8-11e7-86d2-9bdae7168144.png)
![screen shot 2017-05-24 at 11 23 08 pm](https://cloud.githubusercontent.com/assets/20164097/26417899/12cabe44-40d8-11e7-9b92-451136300011.png)

**Comment by tundebabzy** [comment]
Fixed
