### ISSUE TITLE
DocType Student Batch Not Found

### ISSUE THREAD

**Issue by addymuliady** [frappe/erpnext#9016]
ERPNext: v8.0.38 (master)
Frappe Framework: v8.0.59 (master)

1. Go to Naming Series
2. Select Student Batch

![image](https://cloud.githubusercontent.com/assets/21187126/26426392/f4f5c0f2-410a-11e7-9d0a-441a271cdfe7.png)

**Comment by jwrober** [comment]
Student batches are merged with student groups at this point. See https://github.com/frappe/erpnext/releases/tag/v8.0.25
