### ISSUE TITLE
Make Customer / Supplier publishable on website

### ISSUE THREAD

**Issue by lxnow** [frappe/erpnext#902]
Have option to display Supplier details on website.  Similar to implementation of Items where separate web-specific fields can be used.

The address and contacts associated to the supplier/customer should also be displayable on the website, via toggle. Multiple addresses displayed on website would be allowed.

This would be useful for sharing with end-customers who your dealers/sales partners are... who can be your direct customer.  Same thing with Suppliers, who may be partners you pay that do service related to your product.

**Comment by umairsy** [comment]
Closing this issue for now. Please reopen if still valid.
