### ISSUE TITLE
Unable to Export General ledger in PDF

### ISSUE THREAD

**Issue by Arundhatii** [frappe/erpnext#9024]
Reported via https://frappe.erpnext.com/desk#Form/Issue/WN-SUP25354
Refer the gif
![ledger](https://cloud.githubusercontent.com/assets/20164097/26445380/ad7dd4d2-415d-11e7-971c-432c9039fb09.gif)

**Comment by umairsy** [comment]
+1

**Comment by umairsy** [comment]
This is test comment.
