### ISSUE TITLE
Can not  export query-report excel file

### ISSUE THREAD

**Issue by jschen889** [frappe/erpnext#9029]
My erpnext version is V8.0.39. I found it can not export query-report excel file, because the new version add "# filter rows by slickgrid's inline filter  result = [x for idx, x in enumerate(result) if idx == 0 or idx in visible_idx]" at line 156 & 157 in the frappe-bench/apps/frappe/frappe/desk/query_report.py. Please check it.

**Comment by manassolanki** [comment]
Hi @jschen889 ,
Could you explain a little bit more, what exactly is the error message coming while you export the query reports in excel file?

**Comment by jschen889** [comment]
I can not export General Ledger for  excel but it is ok for csv file. It will show error message when exporting  excel file.After I compare frappe-bench/apps/frappe/frappe/desk/query_report.py, I find the script's difference at line 156 & 157 "# filter rows by slickgrid's inline filter result = [x for idx, x in enumerate(result) if idx == 0 or idx in visible_idx]".

**Comment by manassolanki** [comment]
This is working in our test account. Please provide some information to replicate this.

![export reports](https://cloud.githubusercontent.com/assets/20757311/26488910/df091686-4222-11e7-9fbe-a38766b46f2d.gif)

**Comment by jschen889** [comment]
Sorry, My error message is listed below. Please check it for me.
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/query_report.py", line 157, in export_query
    result = [x for idx, x in enumerate(result) if idx == 0 or idx in visible_idx]
UnboundLocalError: local variable 'visible_idx' referenced before assignment

**Comment by manassolanki** [comment]
Pushed a fix
