### ISSUE TITLE
Linking JV to SINV or PINV causes error

### ISSUE THREAD

**Issue by jwrober** [frappe/erpnext#9030]
From here - https://discuss.erpnext.com/t/how-to-link-jv-to-a-pinv/23622

It seems that the feature to associate a JV to these other document types is not very simple. The system is forcing party type and party for the references when that is not was is needed. Not sure how to "fix" per se, but all I want is to be able to simply associate a JV to a SINV or PINV without hassle.

**Comment by PawanMeh** [comment]
This appears to be fixed in latest release where if you select the Sales or Purchase Invoice, it defaults the party type. You can check.
