### ISSUE TITLE
BOM - If Valuation is based on Price List, then rate for Sub-assembly item should also fetch from Item Price

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#9040]
In the BOM, irrespective of valuation selected in "Rate Of Materials Based On", for the sub-assembly item, Rate is fetched from it's BOM. If "Rate Of Materials Based On" is based on Price List, for the sub-assembly and all other items, rate should fetch from Price List only.

**Comment by somicoito** [comment]
In case in a BOM there is a Subcontracted Item, its value should be based on:
Subcontracted Item Purchase Price List Rate + Raw Material Purchase Price List Rate

**Comment by umairsy** [comment]
Check WN-SUP25355 for more details. @rohitwaghchaure please assign it to someone.

**Comment by sagarvora** [comment]
Merged.
