### ISSUE TITLE
 Expense Claim support multi-currency

### ISSUE THREAD

**Issue by HayamMahmoud** [frappe/erpnext#9045]
Please allow multi-currency in the Expense claim

**Comment by HayamMahmoud** [comment]
Hi,
please is there any update?

**Comment by vishdha** [comment]
please provide use case to develop this feature

**Comment by HayamMahmoud** [comment]
We don’t have multi currency in the expense claim ?
Like JV we can pay in USD or EGP, but in expense claim we must enter the amount in USD ?!

**Comment by HayamMahmoud** [comment]
In the Expense Claim, we can select an Account in the base currency of the Company only?

**Comment by HayamMahmoud** [comment]
Hello,
Please is there any update ?

**Comment by vishdha** [comment]
We will start work on it soon.

**Comment by HayamMahmoud** [comment]
Hi Vishdha,
Please is there any update regarding to this issue?

**Comment by OmarJaber** [comment]
Is there any update?

**Comment by dulhaver** [comment]
> Is there any update?

[this comment on the forum from April 9th 2020](https://discuss.erpnext.com/t/expense-claim-multi-currency-settlement/58820/5?u=vrms) may interest you. Apparently there is something in the works in this matter targeting at the version-13 release.

I hope the efforts will look at the entire multi-currecy spectrum when Employees are involved, not only expense claim/advance. but also the Salary side of things.

@vishdha can you assign the person who is working on this if you have the insight?

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.

**Comment by sabgaby** [comment]
Why was this issue closed? Are there any updates as to why this is not part of v14?
