### ISSUE TITLE
[v8.x.x-beta] Can't create or modify any customer or supplier

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#9047]
Hello,

I'm having this issue after the update on thursday, and I can't see or create supplier or customer. After the update it started to ask to select a company, I cant select a default company because if would confuse users, the company selection in my operation must be done without any defaults.

Here is the screenshot:

<img width="923" alt="screen shot 2017-05-26 at 12 51 14 pm" src="https://cloud.githubusercontent.com/assets/18335894/26502428/3452bc74-4213-11e7-8f1c-a930aa1f5124.png">

And the console error log:

<img width="1661" alt="screen shot 2017-05-26 at 12 59 06 pm" src="https://cloud.githubusercontent.com/assets/18335894/26502439/3e950700-4213-11e7-8504-bb5ee46d835a.png">
<img width="1665" alt="screen shot 2017-05-26 at 12 58 53 pm" src="https://cloud.githubusercontent.com/assets/18335894/26502437/3e8fbc1e-4213-11e7-8537-4b2a03ff5606.png">
<img width="1659" alt="screen shot 2017-05-26 at 12 58 28 pm" src="https://cloud.githubusercontent.com/assets/18335894/26502436/3e8dab54-4213-11e7-9431-80188837654c.png">
<img width="1497" alt="screen shot 2017-05-26 at 12 58 17 pm" src="https://cloud.githubusercontent.com/assets/18335894/26502438/3e90fc00-4213-11e7-92ea-b271d72b4352.png">
<img width="1674" alt="screen shot 2017-05-26 at 12 57 37 pm" src="https://cloud.githubusercontent.com/assets/18335894/26502440/3e956cf4-4213-11e7-9145-c57e85050290.png">

**Comment by nabinhait** [comment]
Thanks for reporting, fixed it in the latest release.

**Comment by tundebabzy** [comment]
This issue seems to have been fixed. Are you on the latest?
