### ISSUE TITLE
Sending Docs from ERPNext should be immediate

### ISSUE THREAD

**Issue by jevonearth** [frappe/erpnext#9049]
In Version 8 sending email from Purchase Orders and Sales Orders now appear to go into the email queue, which gets processed by workers every **N** minutes.

This is a big set back. PO's are often very time sensitive, and a purchaser will sometimes be on the phone to a supplier and say: "_I just sent you the PO, can you check your email and confirm all is in good order_?".

I understand the queue has great value for bulk email, but for PO's, Sales Orders, Quotes, it just does not make sense.

Please change all email that is not "bulk email" to send immediately. Case in point:

- Quotes
- Purchase Orders
- Sales Orders

**Comment by manassolanki** [comment]
Hi @jevonearth,
Whenever you send a mail then a record is created in the email queue, but if the email is urgent then the "now" argument is passed to bypass the queue and immediately send the email. In both the cases(immediate mail and bulk mail) a record in email queue is always created.

**Comment by paulator** [comment]
Hi @manassolanki,
just for the records: How can this "now" argument passed to the message? Is it available from the GUI?

**Comment by jevonearth** [comment]
I believe there is some problem with what @manassolanki describes. 

I'm running:
```
ERPNext: v8.7.2 (master)
Frappe Framework: v8.6.7 (master)
```

And when I Email a Purchase Order, the email sits in the queue in "Not Sent" status for anywhere between a moment and several minutes. 

See attached screenshot of the detail page for a specific email queue entry. 
As an aside, on that page, it shows "Add Unsubscribe Link" and "Unsubscribe Method", but this type of email is not Bulk, it is transnational, so the concept of "Unsubscribe" should not even apply to this type of email.

![0975f4eecf](https://user-images.githubusercontent.com/1114943/29419121-21336f20-8323-11e7-8d65-977f4ac70028.png)

**Comment by manassolanki** [comment]
Hi @jevonearth ,
Every email that has been sent via the ERPNext goes via the email queue (except few). I am not sure how the priority has been set for different doctype or for different functionality, but while adding in the email queue we can set whether we want to immediately send that email or as per queue (In both cases email will be added to the email queue)

**Comment by harshvadhiya** [comment]
> Hi @jevonearth, Whenever you send a mail then a record is created in the email queue, but if the email is urgent then the "now" argument is passed to bypass the queue and immediately send the email. In both the cases(immediate mail and bulk mail) a record in email queue is always created.

How can we pass the "now" argument?
