### ISSUE TITLE
Sales Invoice: outstanding amount currency error

### ISSUE THREAD

**Issue by hanselke** [frappe/erpnext#9053]
item is set with a USD price list.

base currency of company is set in SGD.

Outstanding amount within sales invoice shows as SGD w/o currency exchange 

![screen shot 2017-05-27 at 11 20 43 am](https://cloud.githubusercontent.com/assets/1612565/26517605/af55cef0-42ce-11e7-9a5a-6bfbffcac190.png)

**Comment by tundebabzy** [comment]
Hello @hanselke 
Thanks for reporting. I'm not able to replicate this issue.
![screenshot from 2017-05-30 13-09-34](https://cloud.githubusercontent.com/assets/818803/26582563/9c8c9a70-4539-11e7-9544-fde9985be931.png)

Please add steps to reproduce the issue and also the version of ERPNext you are working with.
