### ISSUE TITLE
Unable to open a one of the suppliers, the rest is OK

### ISSUE THREAD

**Issue by addymuliady** [frappe/erpnext#9059]
https://discuss.erpnext.com/t/unable-to-open-a-supplier/24276

ERPNext: v8.0.38 (master)
Frappe Framework: v8.0.59 (master)

I received the following traceback in console log when I want to view one of my suppliers.

Traceback (most recent call last):

> File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 33, in getdoc
> run_onload(doc)
> File "/home/ubuntu/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 212, in run_onload
> doc.run_method("onload")
> File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 666, in run_method
> out = Document.hook(fn)(self, *args, **kwargs)
> File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 891, in composer
> return composed(self, method, *args, **kwargs)
> File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 874, in runner
> add_to_return_value(self, fn(self, *args, **kwargs))
> File "/home/ubuntu/frappe-bench/apps/frappe/frappe/model/document.py", line 660, in 
> fn = lambda self, args, **kwargs: getattr(self, method)(args, **kwargs)
> File "/home/ubuntu/frappe-bench/apps/erpnext/erpnext/buying/doctype/supplier/supplier.py", line 20, in onload
> self.load_dashboard_info()
> File "/home/ubuntu/frappe-bench/apps/erpnext/erpnext/buying/doctype/supplier/supplier.py", line 23, in load_dashboard_info
> info = get_dashboard_info(self.doctype, self.name)
> File "/home/ubuntu/frappe-bench/apps/erpnext/erpnext/accounts/party.py", line 396, in get_dashboard_info
> info["total_unpaid"] = -1 * info["total_unpaid"]
> TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'

**Comment by nabinhait** [comment]
This issue has been fixed in the latest version 8.0.40
