### ISSUE TITLE
Change of Workstation during Manufacture(option in Timesheet)

### ISSUE THREAD

**Issue by ajit-jain1** [frappe/erpnext#9068]
Hi All,

This is a problem I faced while entering Timesheets.

Once a BOM with operations is created, the operations are assigned to a specific machine/workstation.
But during manufacturing it is not necessary the same machine is used(in case of multiple machines of same kind), so in time sheets can an option be provided to choose another workstation incase the default workstation is busy with a certain task. Because the Timesheets dont allow for multiple enteries for the same time period on the same workstation( which is correct, since you cannot assign the same machine for two tasks at the same time.). This would be helpful.

I hope it is clear what I am trying to explain.

Thanks and regards
Ajit

**Comment by kennethsequeira** [comment]
Closing as Timesheets are no more linked to the manufacturing module.
