### ISSUE TITLE
Issues with Web Form 

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#9073]
Hi,

It appears the 'Success Message' and 'Success URL' features in the Web Form aren't working. Expected behavior is for the 'Success Message' to be displayed upon successful Saving of the Web Form following which the user is redirected to the 'Success URL' by clicking on the 'Continue' button

Right now however, none of this works **when a user is logged in** and the user has to use the Cancel button to leave the Web Form after Saving 

Please fix

Thanks

**Comment by jwrober** [comment]
Is this your issue? https://github.com/frappe/frappe/issues/2500

**Comment by Olawale1** [comment]
Hi @jwrober 

Yes! Guess the issue cropped up again?

Kind regards,

**Comment by Olawale1** [comment]
Hi @jwrober 

Trust you're doing great. Could you kindly update the tags? It makes it look like I'm asking a question whereas I'm actually reporting a bug :)

Thanks
