### ISSUE TITLE
Grammar error in HR Training Results

### ISSUE THREAD

**Issue by jwrober** [frappe/erpnext#9074]
I started using the HR module training feature. I recently held a training event and thought it cool to be able to track who got trained on what that day.

When I completed the training results I received this email:

> Thank You for attending Summer 2017 Training. You grade is A 

The grammar in the second sentence needs work (at least from an English perspective). I would propose that is says "Your grade: A". I just happened to list everyone that took the training a grade of A. Not sure if the logic does this or not, but I would recommend that if there is no value in the grade field, then you dont get that sentence.

**Comment by tundebabzy** [comment]
fixed(#9076)
