### ISSUE TITLE
Incorrect display attachment name and email subject with unicode characters

### ISSUE THREAD

**Issue by Ku4nCheang** [frappe/erpnext#9077]
### Environment

- OS: ubuntu
- Version: **v8.0.40**

Incorrect display attachment name and email subject which have unicode characters.
When the email has been sent, the email subject and attachment name cannot display unicode characters

![screen shot 2017-05-30 at 3 10 54 pm](https://cloud.githubusercontent.com/assets/4996109/26571891/6c80dd3a-454a-11e7-8347-b2d81cce075a.png)

## Generate Steps

1. Create a project and name it with unicode characters. E.g. "ABC 檔案"
2. Upload an attachment with a name that contains unicode characters. E.g. "ABC 附近"
3. In the project page, click the menu button and send an email to an email address.
4. Observe the email title and the attachment name.

**Comment by manassolanki** [comment]
Hi @Ku4nCheang, I have tried replicating the issue. This is working fine in my test account. Any other lead to replicate this?

**Comment by Ku4nCheang** [comment]
Hi @manassolanki, I have recorded an video about the bug, please check it out. [https://youtu.be/3H37BV-5gsA](url) 
I don't know whether it is my settings issue or the bug of erpnext.

**Comment by manassolanki** [comment]
I have also cross-checked, this error isn't replicating in the browser. This error is happening in the mail client on the Mac. Please cross check this once and let me know whether this is replicating in the browser also.

**Comment by Ku4nCheang** [comment]
Yes, It happened on browser too. I use a webmail portal to read the email. Same result.

Environment: MacOS
Browser: Safari

![screen shot 2017-06-16 at 3 03 13 pm](https://user-images.githubusercontent.com/4996109/27215717-39d6e920-52a5-11e7-8920-471fef900011.png)

**Comment by manassolanki** [comment]
I think that's somehow related to Apple mail client. I have sent one mail with attachments as per your steps and I found this happening only in the Apple mail client. Below is the screenshot of the same email opened using different clients.

**Gmail in the browser:**

![image](https://user-images.githubusercontent.com/20757311/27216928-67f3abfa-5295-11e7-8f10-fb2a3d29ab59.png)

**Apple Mail client:**

![image](https://user-images.githubusercontent.com/20757311/27216949-888040d6-5295-11e7-8b6e-5389576ed49b.png)

**Apple Mail client in the browser:**

![image](https://user-images.githubusercontent.com/20757311/27217170-5cb66722-5296-11e7-94ae-7f7820274048.png)

**Comment by Ku4nCheang** [comment]
I tried Gmail web portal to open the email, the attachment name displays correctly. However, the subject is not readable. Very strange.

<img width="988" alt="screen shot 2017-06-16 at 5 06 18 pm" src="https://user-images.githubusercontent.com/4996109/27220083-74e04f1e-52b6-11e7-87aa-0a51c65290f7.png">

**Comment by manassolanki** [comment]
This is a bug in Apple Mail, for fixing this you can use [this thread](https://apple.stackexchange.com/questions/15157/how-to-default-utf-8-encoding-in-text-encoding-in-mail-app?rq=1) to fix your issue. But for the Gmail, I am not able to replicate this issue.
I am closing this issue for now as this isn't at our end. Please feel free to reopen this if it persists in any email which doesn't go through Apple ecosystem.
