### ISSUE TITLE
Paid POS invoice appear as Draft after synchronization

### ISSUE THREAD

**Issue by chdecultot** [frappe/erpnext#9083]
Hi,

Since the last update, some POS invoices that have been submitted and paid appear as Draft in the invoice list.

I am trying to understand it, but since it is a major issue I prefer to report it.

Thank you!

**Comment by mdwala** [comment]
It happened with us when there were no stock for any item in selected warehouse.
Although it shouldn't accept that item at first.

**Comment by Olawale1** [comment]
Hi @mdwala 

That's the expected behavior (at least for non-serialized items). Remember that the POS works offline so it only gets to confirm the stock isn't available in the specified Warehouse at the point of synching

Kind regards,

**Comment by rohitwaghchaure** [comment]
Hi @chdecultot

System keeps the records in the draft mode if the exception caught during the submission of the records. Exceptions like deficiency of the stock, valuation rate issue etc. Kindly set the valuation rate for all new items against which purchase transaction has not made and increase the stock level of all items.

**Comment by chdecultot** [comment]
Thanks @rohitwaghchaure , I will look into this in details.

Have a nice day!
