### ISSUE TITLE
Calendar widget does not see bottom of screen

### ISSUE THREAD

**Issue by jwrober** [frappe/erpnext#9087]
When viewing any document and you want to fill in a date field that is near the bottom of the screen, the date widget does not "see" that and appears off screen forcing the user to scroll down some more to see the widget and use it. I would expect the widget to know I am at the bottom of the screen and appear above the date field and not below in it this case. The example is on an employee record, however this behavior happens all over.

![image](https://cloud.githubusercontent.com/assets/23037938/26588463/07d06998-451b-11e7-8576-7690b711c239.png)

**Comment by mhbu50** [comment]
+1
