### ISSUE TITLE
Form not scrolling to top of screen

### ISSUE THREAD

**Issue by jwrober** [frappe/erpnext#9088]
There are a number of examples where the form does not scroll to top of screen.

In a module list like Setup and have scrolled down the page a bit to click on a menu item.  In this use case I am clicking on customize form. If a form is already loaded or if i need to fill in the form name at the top of the page, i have to scroll up to get to it. See animated gif. I would expect the window to automatically scroll to the top for me. It does not happen all the time, but quite often. I have tested in chrome, ff and edge. Happens in all three of those browsers.

![scroll issue](https://cloud.githubusercontent.com/assets/23037938/26591498/757b45d2-4523-11e7-8666-0f51655a683f.gif)

**Comment by jwrober** [comment]
I found another example of the scrolling issue. If I scroll down in a table and open a row dialog box and then use the crtl-down arrow to go to the next record then the screen goes to the bottom of the page and i have to scroll all the way back up again to see the dialog box. dialogs should always center in the screen no matter where you are on the page that loaded them from my perspective

![scroll issue 2](https://cloud.githubusercontent.com/assets/23037938/26597374/63b2f6ba-4537-11e7-91ad-18c4cd6a5d96.gif)

**Comment by mdwala** [comment]
Also while entering data in list view, you can barely see that last row, may be 50% of the row.
Which makes you can't see list option for a field.
But After that Once you reach to enter new row it page scrolls up to perfect position.

**Comment by eliyas0128** [comment]
both are dialog box ?
