### ISSUE TITLE
Recording similar data for Job Applicants, transferrable to Employee

### ISSUE THREAD

**Issue by lxnow** [frappe/erpnext#909]
Here's an idea: let job applicants apply through ERPNext portal as, say, a "guest" user that is limited to only applying and not viewing any other records.  This collects all pertinent information about the applicant which can later be simply transferred to an Employee record if he/she gets hired.

It's pretty much like a PO->PR or SO->DN process.

This would be helpful for recruitment agencies type businesses, and I'd certainly find use for this as well. Saves on paper.

**Comment by vjFaLk** [comment]
Fixed
