### ISSUE TITLE
Journal Entry Account table not updated when duplicating Journal Entry

### ISSUE THREAD

**Issue by addymuliady** [frappe/erpnext#9092]
**ERPNext: v8.0.40 (master)
Frappe Framework: v8.0.60 (master)**

Fields such as _account balance_, _account currency_ and _currency exchange rate_ are not fetched in the Journal Entry Account table when duplicating Journal Entry.

This will result in inaccurate entry and calculation in return as such, duplicating Journal Entry can't be used.

## Original Entry

**This is the original journal entry**
![image](https://cloud.githubusercontent.com/assets/21187126/26614534/a8a8ab40-45f3-11e7-9b3c-7960a15a93d4.png)

**Row 1 Item Detail**
![image](https://cloud.githubusercontent.com/assets/21187126/26614652/44109c46-45f4-11e7-80c9-f6c6b104d7f7.png)

## After Duplicate

**Duplicated Entry**
![image](https://cloud.githubusercontent.com/assets/21187126/26614706/773e14d6-45f4-11e7-9a15-ab89df597101.png)

**Duplicated Row 1 Item Detail**
![image](https://cloud.githubusercontent.com/assets/21187126/26614741/a7422794-45f4-11e7-9e08-0d7b80f86db5.png)

**Comment by nick9822** [comment]
@addymuliady 
Actually its kept like that by default setting. You can unset option "No Copy" for the conerned field in the concerned Doctype which can be only be achieved if you are on self hosted version.

**Comment by addymuliady** [comment]
@nick9822 does it make sense for a user to duplicate an entry and has the currency and exchange rate not copied?

Any reason for this?

**Comment by nick9822** [comment]
@addymuliady 
Yes exchange rate can vary from time to time. And those are important things user should check in the Journal Entry.

**Comment by addymuliady** [comment]
Thanks @nick9822 

However, I do think that Account Currency (SGD, USD, EURO) should not be "No Copy" as these are tied to the account currency itself. Else, there is no point of duplicating for multi-currency journals.

Exchange rate is understandable though I think as a user, that is why I want to duplicate a journal entry.
