### ISSUE TITLE
Gross Profit Does not display Reversal of sales invoice

### ISSUE THREAD

**Issue by haiyang89** [frappe/erpnext#9096]
Below is sales invoice.
![image](https://cloud.githubusercontent.com/assets/21308275/26628370/01b3fde6-4628-11e7-830d-d28c4cfef931.png)

Below is Gross Profit Report. and this report does not show the reversal document.
![image](https://cloud.githubusercontent.com/assets/21308275/26628383/125749a0-4628-11e7-897e-e3ab1c9ae239.png)

**Comment by bohlian** [comment]
I can confirm that this is legitimate and I also do think that the GP report should take into consideration Returns / Credit Notes.

**Comment by maxfu9** [comment]
I also confirmed this issue exit

**Comment by tundebabzy** [comment]
hello @haiyang89  and all
Please show me how you make the reversal of the sales invoice? On my setup, it's not allowed as expected:

![screenshot from 2017-06-09 14-31-22](https://user-images.githubusercontent.com/818803/26977671-9bbb66a0-4d20-11e7-84f4-08f345229cdf.png)

**Comment by tundebabzy** [comment]
I get it. Negative invoice is a credit note.

**Comment by tundebabzy** [comment]
@haiyang89 fix has been merged
