### ISSUE TITLE
Jinja expressions are escaped by the WYSIWYG Editor

### ISSUE THREAD

**Issue by danielmorlock** [frappe/erpnext#9100]
E.g. if we want to have the following Jinja expression in terms and conditions:
```jinja
{% if var > 10000 %}
Larger than 100000.
{% endif %}
```
If I switch the editor mode and show the HTML code, I get:
```html
{% if var &gt; 10000 %}
Larger than 100000.
{% endif %}
```

So the editor should not escape in between the Jinja markers.

**Comment by joezsweet** [comment]
It happens also on field settings, if u put javascript checks in `Display Depends On` it's converted in the same way

**Comment by joezsweet** [comment]
no no ..i mean you get the same problem in field definition

**Comment by britlog** [comment]
It happens also when you add the google map iframe in webpage editor, saving the page destroys the iframe.

**Comment by danielmorlock** [comment]
A possible workaround is to the following at the top of your HTML code:
```
<!-- markdown -->
```

**Comment by britlog** [comment]
Please try again when the Frappe PR below will be merged 
https://github.com/frappe/frappe/pull/3751
