### ISSUE TITLE
Allow setting of public/private for files to be a parameter

### ISSUE THREAD

**Issue by jwrober** [frappe/erpnext#9102]
From here - https://discuss.erpnext.com/t/default-file-setting-to-private/23698

Would like to have a setting of some kind to be able to set the default behavior of files. In my use case I want the default to be private. However others might want public. So having a global setting run this would be great.

**Comment by Tropicalrambler** [comment]
This is CRITICAL.

**Comment by bcornwellmott** [comment]
I made a PR to have the default as private, because it's a more robust condition than making things public by default. Adding a setting will probably be harder.
https://github.com/frappe/frappe/pull/3521

**Comment by tundebabzy** [comment]
Merged

**Comment by somicoito** [comment]
now it is set as public by default again.

**Comment by mmasifashraf** [comment]
its came as public by default again

**Comment by Lewinta** [comment]
I suggest to include an option for Attach fieldtypes on Customize Forms where users can specify if this check is ready only and allow to choose a default (0 or 1)
