### ISSUE TITLE
Text Gets Truncated in PDF Instead of being wrapped

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#9107]
Hi,

Lengthy text in the print format gets truncated when converted to PDF instead of being wrapped. This is a significant issue especially for email addresses. Please see screenshots below and observe how the email address gets truncated

![pf builder wrapping issue 1](https://cloud.githubusercontent.com/assets/9269337/26668547/202136b6-46a2-11e7-8d81-78c5a093a57a.png)

![pf builder wrapping issue 2](https://cloud.githubusercontent.com/assets/9269337/26668559/2b285e0e-46a2-11e7-8fdf-109a2d198b46.png)

Please fix

Thanks

**Comment by netchampfaris** [comment]
https://github.com/frappe/frappe/pull/3486
