### ISSUE TITLE
Duplicate Customer Error blocking queue in POS

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#9110]
Hi,

There's a Duplicate Customer Error blocking the queue in POS for the past 2 days. There's nothing in the error logs. Please find screenshot below:

![pos duplicate customer issue 1](https://cloud.githubusercontent.com/assets/9269337/26677429/d57772de-46c3-11e7-9061-9dd6f33fc1ab.png)

Please help fix asap

Thanks

**Comment by Olawale1** [comment]
Pasting JS Trace below:
```
desk.min.js:1258 POST http://xxxxxxxxxx.com/ 409 (Conflict)
send @ jquery.min.js:4
ajax @ jquery.min.js:4
frappe.request.call @ desk.min.js:1258
frappe.call @ desk.min.js:1155
sync_sales_invoice @ VM201:2241
(anonymous) @ VM201:734
dispatch @ jquery.min.js:3
$event.dispatch @ report.min.js:2928
r.handle @ jquery.min.js:3
desk.min.js:1258 POST http://xxxxxxxxxx.com/ 409 (Conflict)
send @ jquery.min.js:4
ajax @ jquery.min.js:4
frappe.request.call @ desk.min.js:1258
frappe.call @ desk.min.js:1155
sync_sales_invoice @ VM201:2241
(anonymous) @ VM201:2230
desk.min.js:1258 POST http://xxxxxxxxxx.com/ 409 (Conflict)
send @ jquery.min.js:4
ajax @ jquery.min.js:4
frappe.request.call @ desk.min.js:1258
frappe.call @ desk.min.js:1155
sync_sales_invoice @ VM201:2241
(anonymous) @ VM201:2230
desk.min.js:1258 POST http://xxxxxxxxxx.com/ 409 (Conflict)

```

**Comment by rohitwaghchaure** [comment]
Hi @Olawale1 

I am trying to replicate the issue but not able to replicate it. Kindly share the following details

1. Do you have customer with name success?

1. Did you created new customer with name success?

1. What version are using for erpnext app?

If possible kindly share the web.error log

**Comment by Olawale1** [comment]
Hi @rohitwaghchaure 

Thanks for your response. Please find answers below:

1. Yes there is a customer with name 'success'
2. Yes, a new customer was created in POS with same name 'success'. When I first noticed the error, I tried renaming the earlier customer on the system to 'success 1' but the sales are still not getting synched
3. ERPNext: v8.0.40 (master)

web.error.log:
```
[2017-06-01 07:26:27 +0000] [1396] [INFO] Worker exiting (pid: 1396)
[2017-06-01 07:26:27 +0000] [1642] [INFO] Booting worker with pid: 1642
[2017-06-01 07:26:27 +0000] [1642] [INFO] Worker exiting (pid: 1642)
[2017-06-01 07:26:27 +0000] [1643] [INFO] Booting worker with pid: 1643
[2017-06-01 07:45:28 +0000] [512] [INFO] Worker exiting (pid: 512)
[2017-06-01 07:45:28 +0000] [2229] [INFO] Booting worker with pid: 2229
[2017-06-01 10:23:13 +0000] [2229] [INFO] Worker exiting (pid: 2229)
[2017-06-01 10:23:13 +0000] [3158] [INFO] Booting worker with pid: 3158
[2017-06-01 10:53:32 +0000] [3158] [INFO] Worker exiting (pid: 3158)
[2017-06-01 10:53:32 +0000] [3409] [INFO] Booting worker with pid: 3409
[2017-06-01 11:16:07 +0000] [1643] [INFO] Worker exiting (pid: 1643)
[2017-06-01 11:16:08 +0000] [3550] [INFO] Booting worker with pid: 3550
```

Thanks

**Comment by rohitwaghchaure** [comment]
Hi @Olawale1 

If you have renamed the customer success to success 1 then order with customer name success must be synced. As this issue is not replicating, I need access of your system to debug this issue. Can you please PM the details on the [discuss forum](https://discuss.erpnext.com/)

**Comment by Olawale1** [comment]
Hi @rohitwaghchaure 

Trust you're doing great. I've sent the PM

Thank you

**Comment by Olawale1** [comment]
Hi @rohitwaghchaure 

Trust you're doing well. The issue still persists. I've tried deleting the customer record from the ERP and even run a bench update but the system keeps creating the customer 'success' and giving the duplicate name error

Please help fix this

Thanks
