### ISSUE TITLE
Cannot fork chart of accounts on charts.erpnext.com

### ISSUE THREAD

**Issue by joezsweet** [frappe/erpnext#9112]
Hi there,

i'm trying to fork italian chart of accounts, it rise a message and doesn't fork, see pic:

<img width="1054" alt="schermata 2017-05-31 alle 12 45 19" src="https://cloud.githubusercontent.com/assets/11652845/26682081/834924a0-46df-11e7-94d8-fdeabe30f9f3.png">

On console it rise:

`[Error] Failed to load resource: the server responded with a status of 409 (CONFLICT) (charts.erpnext.com, line 0)`

Any hint?

**Comment by binar-argentina** [comment]
hi @pratu16x7 , any news for this?

**Comment by fproldan** [comment]
Hi! I also need fork a chart.
This issue is plan to be resolved soon?
Thanks!

**Comment by pratu16x7** [comment]
Fixed via frappe/chart_of_accounts_builder#21
