### ISSUE TITLE
File attachment upload permissions

### ISSUE THREAD

**Issue by Tropicalrambler** [frappe/erpnext#9116]
When a file is uploaded for a specific DocType, the current dialog shows a checkbox allowing for "Private" or "Public" files.

I propose a dialog with the following options:
Public - Web accesible
Internal Public - All current ERPNext users can see
Private - Only uploader can access

So, if you have the image of a product you sell (stock item), this can be uploaded with Public permissions.  Anyone with the link who is not an ERPNext user can access this image.

If you have a memo addressed to all employees, this can be uploaded with "Internal Public" setting, so that any current and new user of ERPNext can view it.

If you have a quotation, where only you need to have access, but not everyone else, then you set it as Private.

Once uploaded, for a private file, you can then select specific users to share the item with.

Also, the Sharing option should allow for specific roles, or groups of roles.

**Comment by jwrober** [comment]
Related to this one I opened too - https://github.com/frappe/erpnext/issues/9102

**Comment by umairsy** [comment]
linked to #9102
