### ISSUE TITLE
Add provision to configure page length for List/Report view

### ISSUE THREAD

**Issue by rohitwaghchaure** [frappe/erpnext#9118]
![screen shot 2017-06-02 at 11 24 11 am](https://cloud.githubusercontent.com/assets/8780500/26712721/07422d6e-4786-11e7-956d-2d1ec1c69731.png)

Currently system shows 20 as default page length, needs provision to set the page length as 20/100/500

**Comment by jwrober** [comment]
I prefer real pagination myself - https://github.com/frappe/frappe/issues/3183
