### ISSUE TITLE
Back to the front page automatically

### ISSUE THREAD

**Issue by Jeff0715** [frappe/erpnext#9119]
Dear communities:

In "supplier" page I clicked "address" to edit address data
but after I finished and clicked save it wont back to the "supplier" page automatically
this is not convenient
any solutions instead of back button on the browser?

thanks

**Comment by jwrober** [comment]
This is a good point. Same happens to things like a payment entry on a purchase invoice. I "make a payment" by filling in the PE, save and submit and then I have to go back in the browser to return to the original spot.

**Comment by chdecultot** [comment]
Hi, I added a similar issue in Frappe a few days ago: https://github.com/frappe/frappe/issues/3109

It was working fine for adresses in v7, maybe the HTML button broke it, I don't know...

But it is a major User Experience issue in my opinion.

**Comment by vishdha** [comment]
fixed via #3557
