### ISSUE TITLE
Can we search for an existing customer by contact details like mobile no. or a membership no. etc. while creating a POS invoice?

### ISSUE THREAD

**Issue by SaurabhGupta329** [frappe/erpnext#9121]
Can we search for an existing customer by contact details like mobile no. or a membership no. etc. while creating a POS invoice?

**Comment by nick9822** [comment]
Please ask questions on community forum at https://discuss.erpnext.com/

**Comment by SaurabhGupta329** [comment]
This feature is not available in ERPNext, the support team only has asked me to open this as an issue here.
Pls do not close it until there's a resolution provided.

**Comment by rohitwaghchaure** [comment]
fixed https://github.com/frappe/erpnext/pull/11998
