### ISSUE TITLE
Can not make sales invoice for a non-itemized purchase

### ISSUE THREAD

**Issue by robertbecht** [frappe/erpnext#9129]
Always enter purchase same way...Does not work anymore..

![image](https://cloud.githubusercontent.com/assets/1532439/26743145/0ffb781a-47e1-11e7-96c3-a6cedb25da78.png)
 
The item is not itemized...just some stationary....
This errors msg

![image](https://cloud.githubusercontent.com/assets/1532439/26743187/3d6ba996-47e1-11e7-9202-4f6f9c29e292.png)

Seem like a bug...

Robert

**Comment by jwrober** [comment]
This is by design. If you want to capture in accounts a non-itemized purchase then just do a JV to capture it.
