### ISSUE TITLE
cannot submit purchase

### ISSUE THREAD

**Issue by robertbecht** [frappe/erpnext#9130]
Always enter purchase same way...Does not work anymore..

![image](https://cloud.githubusercontent.com/assets/1532439/26743145/0ffb781a-47e1-11e7-96c3-a6cedb25da78.png)
 
The item is not itemized...just some stationary....
This errors msg

![image](https://cloud.githubusercontent.com/assets/1532439/26743187/3d6ba996-47e1-11e7-9202-4f6f9c29e292.png)

Seem like a bug...

Robert

**Comment by bcornwellmott** [comment]
You are missing the UOM. Fill that in and your conversion factor should update.

**Comment by robertbecht** [comment]
Hi , thnx for your swift supply, but (of course) i tried that,...did not
work
Further, in my understanding, UoM and conversion is used for itemized
items....not for non-itemized
rgds robert

**Comment by robertbecht** [comment]
I have been using Erpnext on cloud for over 5 years...this has never
occured before, robert
