### ISSUE TITLE
Can we amend search query for searching an existing customer by contact details like mobile no. or a membership no. etc. while creating a POS invoice?

### ISSUE THREAD

**Issue by SaurabhGupta329** [frappe/erpnext#9132]
Can we amend search query for searching an existing customer by contact details like mobile no. or a membership no. etc. while creating a POS invoice?
Its not available in ERPNext as of now, but is a must to have in today's world, since anyone doing a billing in POS may have to search for existing customers by their mobile or contact details, else it may result into creation of duplicate customers.

**Comment by rohitwaghchaure** [comment]
With the PR https://github.com/frappe/erpnext/pull/8933/commits/449e44387f45f089f7fe1a77e075014cf7a1b804
User can able to search the customer based on phone number or email id
