### ISSUE TITLE
Dropbox backup issues.

### ISSUE THREAD

**Issue by chanyork** [frappe/erpnext#9138]
Getting the below message when try to backup to dropbox.  I am using the cloud version.

This site can’t be reached

www.dropboxapi.com’s server DNS address could not be found.
DNS_PROBE_FINISHED_NXDOMAIN

**Comment by jwrober** [comment]
This seems like a user setup issue and not something with ERPNext specifically. Please open a discussion at https://discuss.erpnext.com/.
