### ISSUE TITLE
LANDED COST ENTRY

### ISSUE THREAD

**Issue by ai-erp** [frappe/erpnext#9140]
Hi There,  
Currently, we are using Landed Cost Voucher in our ERP and we noticed that the entry affected in making LCV is as below:

![lcv-initial entry](https://cloud.githubusercontent.com/assets/16744099/26774535/bbedaa74-49e1-11e7-9c28-b79e379a6713.png)

While entry created upon delivery of the goods is below:

![lcv-upon delivery of item](https://cloud.githubusercontent.com/assets/16744099/26774552/d4e491d2-49e1-11e7-8435-bd8496606e07.png)

I suggest that instead of Automatically creating an entry of Credit to Expense included in Valuation in making LCV, why not have the option to select Shipping company Account so that there is no need to create a new entry in booking payable to Shipping Company like Fedex, DHL, TNT, Aramex or any other shipping company. So upon payment, we only have to close the account "shipping Company" and credit to cash/cash in bank.

**Comment by SaiFi0102** [comment]
Hi, I also have the same concern with LCVs. I would like that LCVs should have a table similar to the Taxes and Charges table in POs, PRECs and PINVs. And in addition to updating the "Expenses Included in Valuation" account, LCV upon submission (just like upon submission of Purchase Invoice) should also create the GL entries for the respective tax/charges accounts to balance out the "Stock Expenses" account group.

The current system allows us to overcome the problem of delayed entry of costs, however, it also requires the user to manually create any GL entries for the tax and credit it to the respective creditor parties. This introduces the possibility that the user might forget to make the tax GL entries (manually) and cause the system to show unearned profits.

Can the LCV be made into an extension of purchase receipt/invoice which also creates linked GL entries? I would like to work on this issue, however, I don't see any response yet. Please acknowledge if this feature is viable so I can start working on it.

**Comment by harshit-30** [comment]
Please create another issue if it is replicable after v13.10.
