### ISSUE TITLE
Can't change System Language

### ISSUE THREAD

**Issue by TMF42** [frappe/erpnext#9142]
I would need some help with understanding the problem I face. When I try to change the system language from English to German and save it - then there is no change and as soon as I reload the page the system settings show up with "not saved". I'm on the latest master branch (8.0.44) 
When I change the language settings in users it works but I need to change the language of the website.

I've checked in the logs but didn't see anything. So I'm wondering if somebody could give me a pointer where to look to trouble-shoot this problem.

To me it seems the change in system settings is simply not recognized / committed no matter what I do. 
Just to be on the safe site I cleared browser caches but still the website is in English. 

Edit:
I checked the value directly in the DB for System Settings and field language and it shows up with "de" -> so the value is definitely saved but it doesn't change the language even after restarting erpnext with bench. And it somehow recognizes "System Settings" as "not saved" even though all values are the same as in the DB.

**Comment by rohitwaghchaure** [comment]
Hi @TMF42 

I have checked on local account and it's working properly
It seems that there is something problem in System Settings on your account, can you please check
I am closing the issue now, kindly reopen it if your issue has not solved
