### ISSUE TITLE
Report: Payment Entry Currency issues

### ISSUE THREAD

**Issue by ai-erp** [frappe/erpnext#9145]
Hi there, we are trying to get report on payment entry, but we found below issues:

![payment entry report1](https://cloud.githubusercontent.com/assets/16744099/26784353/3045eacc-4a0e-11e7-986c-0c0a6c20f3f2.jpg)

Is there any way we can get total per mode of payment in one single report?

Use case: to get report for each cashier from different locations how much total collections they have in each payment mode (different currencies)

**Comment by rohitwaghchaure** [comment]
Hi @ai-erp 

Can you please pick the column currency and check it again

**Comment by rohitwaghchaure** [comment]
Closing the issue now, kindly reopen if issue still persists
