### ISSUE TITLE
[Paid Development] improve payment entry 

### ISSUE THREAD

**Issue by me2ne** [frappe/erpnext#9147]
Hello
I want to sponsor to improve payment entry for  PDC  in ERPNEXT . this feature is very important because in most of middle east and some asian country one of important payment type is post paid cheque , in all this countries accounting softwares support full feature and different report for PDC  . 

bellow my suggestion for all pay or receive payment  : 

1 - on payment entry when they select cheque they have to enter cheque date too . posting date not effect on any account until cheque cleared  ( because may be cheque will bounce )  .

2 -  cashier who get or make payment ( cheque or cash ) he couldn't change payment date . for example cashier add payment entry  with posting date of yesterday . Or add RECEIPT/VOUCHER DATE so nobody can change it and report show base on RECEIPT/VOUCHER DATE . 

3 - PDC cheque we receive  usually deposit to bank 1 day before cheque date , so show in report list of pdc is due by next day or selected date so we will deposit to bank . 

4 - after deposit cheque to bank , select cheques as deposited to banks ( may be we have different bank account and we deposit cheques  to different banks account  . so we have to select bank account deposited for each cheque . 

5 - after that if cheque cleared and deposit to bank account  In BANK RECONCILIATION we confirm and then effected in bank balance and effected in customer cleared PDC . 

6 - if cheque bounce ( returned ) , it shouldn't effect in bank balance and customer account and show it  in report . 

7 - for PDC cheque we pay to supplier  also will same,  until cheque date  not come and  cheque not cleared, it's  not effect in bank account and cleared  PDC to supplier . 

8 -  In CUSTOMER dashboard, add  "PDCs RECEIVED BUT NOT YET CLEARED" 

9 - in supplier dashboard add "PDCs issued  BUT NOT YET CLEARED "

10 - we can get report of PDC issued and received and not yet cleared from all supplier and customer for special date range . 

I got very good idea from bellow issue #6946  . i copy attachment from there , thanks @ai-erp  
https://github.com/frappe/erpnext/issues/6946

![48559550-ab48-11e6-90d6-a6592f300ca1](https://cloud.githubusercontent.com/assets/6168204/26785375/10efdb4c-4a13-11e7-93a5-2063d9cd6dbd.png)
![408e39e4-ab48-11e6-84a9-394f72d6fbe3](https://cloud.githubusercontent.com/assets/6168204/26785376/11d27876-4a13-11e7-967f-9a5a6f119d9b.png)

Regards

**Comment by epochc** [comment]
Thank you very much for offering to sponsor this essential feature. I'm not sure if Frappe or the Foundation would be able to take this on directly.

Would you like to check out this approach? You can beta test the committee approach for us:

https://discuss.erpnext.com/t/approach-to-achieve-significant-enhancements-on-erpnext-a-proposal/24503

Thanks

Jay

**Comment by me2ne** [comment]
Dear Jay
Thanks for your reply , I check the link , it’s too complicated for me . if i want to invest time and money for this feature what should i do . I don’t think it’s very special feature,  it’s available in most accounting software .
Regards
Meisam


Shouki Electronics LLC 
Telephone:         +971 4 3858801 Ext: 406 | FAX: +971 4 3858804 | Email: meisam@shoukinet.com <mailto:pj@shoukinet.com> 
Address 1:           # 6, Khalid Bin Al Waleed Bldg., Khalid Bin Al Waleed Rd. Dubai, UAE  
Address 2:           # 305, Al Riffa Plaza, Khalid Bin Al Waleed ST, Dubai, UAE
Website:              www.shoukinet.com <http://shoukinet.com/>  | P.O.Box: 242671 Dubai

 <http://www.shoukinet.com/>
 <http://www.shoukinet.com/>

**Comment by jwrober** [comment]
This sounds like a nice feature, but since it impacts only certain jurisdictions I would like to suggest that this feature be enabled/disabled in accounts settings.

**Comment by epochc** [comment]
Hi Meisam,

I agree. It's a little complicated.Your best bet is to put it up on the Jobs portal https://erpnext.org/erpnext-jobs

You can also check the Service Providers link https://erpnext.org/service-providers and contact them for developing your feature.

If you still need help at the end of this, please let me know and I will see what I can do.

Thanks

Jay

**Comment by riyasrawther** [comment]
@epochc Kindly help us to accomplish this

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.
