### ISSUE TITLE
Rounding error when Manufacture within Sock Entry Qty field has high precision.

### ISSUE THREAD

**Issue by mobentec** [frappe/erpnext#9154]
When finishing a manufacturing order, the screen which has me select batch numbers for the different items that were moved from source warehouse to target warehouse is not getting rounded correctly.  Precision for Qty field within the Stock Entry Form, is set to 8.  When submitting the stock entry, ERPnext displays a popup message saying to select a batch number that has 0.xxxxxxxxx (9 decimals) qty since the selected batch number only has 0.xxxxxxxx (8 decimals) qty.

**Comment by rohitwaghchaure** [comment]
Hi @mobentec 

What precision did you set on the system settings for the Float

**Comment by rohitwaghchaure** [comment]
Hi @mobentec 

I am trying to replicate the issue on local account but not able to replicate it. Kindly pull the latest update and check

**Comment by mobentec** [comment]
Hi @rohitwaghchaure Sorry for the late reply.  I have precision set to 8 in the system wide setting.  The issue seems to be fixed.  Thank you!
