### ISSUE TITLE
Error When trying to Cancel Sales Order

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#9158]
Hi 

The following error pops up when trying to Cancel a Sales Order. Urgent fix required

![cancel sales order issue](https://cloud.githubusercontent.com/assets/9269337/26829206/82e65c68-4abc-11e7-89ee-afcaa0e2547e.png)

Thanks

**Comment by tundebabzy** [comment]
Hello @Olawale1 
There should be a traceback...

**Comment by Olawale1** [comment]
Hi @tundebabzy 

Great to hear from you. Thanks for pointing me to the trace. I observed the issue came from a linked Project which had an empty (and mandatory) Customer field. I selected the appropriate customer in that field and was able to cancel the Sales Order afterwards

Thanks a whole lot

Kind regards,
