### ISSUE TITLE
import of .vcf Address-files

### ISSUE THREAD

**Issue by quintact** [frappe/erpnext#9160]
Hallo, i think this feature would be very good for faster and easier working with new adresses.

Import of .vcf-files in contacts.

in daily business you meet somebody new, or via xing, or linked-in - or the contact is sending his adress via e-mail, the adress ist avaliable as .vcf. often via mail, because your new business contact sends it - or inside xing and linked-in i can downlad his contact data as .vcf. 

best regards

**Comment by joolsr** [comment]
You could import via say Thunderbird and export to a csv file that can be imported to ERPNext, but granted this would be a great feature.

**Comment by quintact** [comment]
Yes, i think so - if i have one or two or ... new contacts, it is no way to import them in thunderburd, to export them to csv and to import them into erpnext. That is an idea, if i have many.
But also some new contacts send their .vcf-file with their e-mail.

The question is, is it a lead then, with added first contact? 
or what is the first adress from somebody new?
