### ISSUE TITLE
[v8 beta] Delivery note Error

### ISSUE THREAD

**Issue by applepipe** [frappe/erpnext#9163]
Hello,

Since last update the console shows this error when I try to see delivery notes:

<img width="1657" alt="screen shot 2017-06-06 at 4 14 03 pm" src="https://user-images.githubusercontent.com/18335894/26847451-7fceef38-4ad3-11e7-8f8a-43ce4a26efab.png">

**Comment by applepipe** [comment]
this also happens on sales invoice

**Comment by tundebabzy** [comment]
hi @applepipe is this still an issue?

**Comment by applepipe** [comment]
sorry, can't test it anymore
