### ISSUE TITLE
Unable to create Manual Depreciation of Asset due to Error

### ISSUE THREAD

**Issue by addymuliady** [frappe/erpnext#9166]
ERPNext: v8.0.40 (master)
Frappe Framework: v8.0.60 (master)

In reference to : https://discuss.erpnext.com/t/depreciation-entry-manual-adjustments/24468/2

Replicate

1. Create Depreciation Entry via Journal Entry
2. Select "Accumulated Depreciation" Type Account
3. Select Reference Type as Asset
4. Try select Asset
5. System ask for Party (which shouldn't be the case)

![image](https://user-images.githubusercontent.com/21187126/26863043-860f96f4-4b82-11e7-8f2d-d8d602320729.png)

**Comment by addymuliady** [comment]
Update: I have selected Party Type and Party but still receiver the following error on my console log.

jquery.min.js:4 GET http://erp.asonic-aviation.com/?txt=&doctype=Asset&filters=%5B%5B%22Asset%2…stries+Pte+Ltd%22%5D%5D&cmd=frappe.desk.search.search_link&_=1496812320710 500 (INTERNAL SERVER ERROR)

**Comment by rohitwaghchaure** [comment]
Hi @addymuliady 

No need to define the party type and party name for asset depreciation.
![screen shot 2017-06-07 at 3 29 29 pm](https://user-images.githubusercontent.com/8780500/26873051-339b32fc-4b96-11e7-9c30-b3738110e17e.png)

**Comment by addymuliady** [comment]
Hi @rohitwaghchaure 

Appreciate your reply. So I assume this is a bug? I am self hosted.

Party Type and Party fields are shown by default on my side.

Thanks!

**Comment by tundebabzy** [comment]
fixed.
