### ISSUE TITLE
Customer_Name when creating Quotation from Lead.

### ISSUE THREAD

**Issue by Arundhatii** [frappe/erpnext#9171]
Reported via https://frappe.erpnext.com/desk#Form/Issue/WN-SUP25584

(1) When you MAKE >> QUOTATION from the Lead form, it inserts the lead field "lead_name" value into the "customer_name" field on the quotation.

(2) However, when you create a new quotation from the Quotation List screen, and choose the Lead >>Opportunity

 from within the quotation form, it inserts the lead field "company_name" value into the "customer_name" field on the quotation.

Preferably we want the "company_name" value to reflect on quotations (not the "lead_name" value. But we want to be able to MAKE-QUOTATIONS directly from the lead form.

![lead to quotation](https://user-images.githubusercontent.com/20164097/26873496-a54a0ca6-4b97-11e7-85e9-b91743d626b4.gif)

**Comment by manassolanki** [comment]
Fixed
