### ISSUE TITLE
"Make" Option for a submitted Material Issue/Transfer from Material Request doesn't show any dropdown options.

### ISSUE THREAD

**Issue by Arundhatii** [frappe/erpnext#9172]
Reported via https://frappe.erpnext.com/desk#Form/Issue/WN-SUP24870
![material request](https://user-images.githubusercontent.com/20164097/26873747-8dd72b84-4b98-11e7-9ff1-21494831d00f.gif)

**Comment by tundebabzy** [comment]
Fixed
