### ISSUE TITLE
Payment Entry - Supplier invoice number should be visible

### ISSUE THREAD

**Issue by Priyanka-IAS** [frappe/erpnext#9175]
When I make a payment entry for a payment made to my supplier, I typically pay 20-30 invoices together. I have made the payment based on Supplier Invoice numbers. I cannot see **Supplier invoice numbers** in the Payment Entry, only system generated PINV-XXX. How do I select the invoices I am paying other than opening another tab and manually searching for Purchase invoice name manually for each invoice. 

Some of my suppliers have over 200 outstanding invoices at any given point in time.

Please add Supplier Invoice Number to this view.

![screen shot 2017-06-07 at 4 37 15 pm](https://user-images.githubusercontent.com/8233597/26875477-b13d734c-4b9f-11e7-8f72-c88728c2f3a3.png)

**Comment by jwrober** [comment]
What view is this you are looking at? It does not look like a list view. You might be able to edit this yourself with a form customization.

**Comment by Priyanka-IAS** [comment]
I agree. Adding a Data field with name “bill_no” does not work. Is there anything else that we need to do for the Supplier Invoice number to show up?

If this works, it will really help us save a huge amount of time. Thanks.

Regards,

Priyanka Kaushal

Director Operations

Indo Aerospace Solutions  (P) Ltd

Visit us on-line at www.indo-aerospace.com <http://www.indo-aerospace.com/>

**Comment by tundebabzy** [comment]
Adding the `bill_no` is just part of the requirements. You still need to tell ERPNext how to populate the field with javascript

**Comment by Priyanka-IAS** [comment]
Can you help with the javascript? It would be a huge help. Thanks

**Comment by Priyanka-IAS** [comment]
Can anyone please help with the javascript that would be needed. It is a really mundane task to  first find out the ERP Purchase invoice ID and then update the allocated amount in the Payment Entry. 

We sometimes have upto 20-30 Supplier invoices being paid in one payment Entry.

Any help would be appreciated. Thanks.

**Comment by PankajWadkar** [comment]
How does it reflect in our Account?

**Comment by utkarsh-goswami** [comment]
@PankajWadkar 
If you are a open source user, pull the develop branch and the changes will be reflected.
In case of a cloud user, we will be releasing version 9 in few days and then all the changes will be reflected.
