### ISSUE TITLE
Payment Entry - Latest Exchange Rate not fetched

### ISSUE THREAD

**Issue by addymuliady** [frappe/erpnext#9180]
ERPNext: v8.0.44 (master)
Frappe Framework: v8.0.64 (master)

Currency Exchange Rate Setup

![image](https://user-images.githubusercontent.com/21187126/26912385-7f0018d8-4c46-11e7-8b29-1a2a80a40df0.png)

Payment Entry Set Up

Company Currency is in USD. 
However, we want to pay from a foreign currency account.
As you can see below, exchange rates are not fetched when I specify a foreign currency account.

![image](https://user-images.githubusercontent.com/21187126/26912515-89a0edfc-4c47-11e7-827d-22d973af9583.png)

![image](https://user-images.githubusercontent.com/21187126/26912443-f4bc2bb6-4c46-11e7-8546-b76807c2f5f1.png)

**Comment by tundebabzy** [comment]
Hello @addymuliady. Thanks for reporting this. 

Let me go through the issue as I understand it. Your company default currency is USD. You have a bank account in a foreign currency, say SGD. When you try to make a payment from the SGD bank, ERPNext fails to retrieve the latest exchange rate for SGD - USD. Am I correct?

**Comment by addymuliady** [comment]
Hi @tundebabzy 

Yes, that is correct.

**Comment by tundebabzy** [comment]
In my case, the exchange rate is fetched although it's the average exchange rate that is fetched.

**Comment by addymuliady** [comment]
Thanks @tundebabzy

**Comment by tundebabzy** [comment]
Fixed

**Comment by addymuliady** [comment]
@tundebabzy can you please claim your bounty? lol
https://www.bountysource.com/issues/46005757-payment-entry-latest-exchange-rate-not-fetched

However, now I have another issue. Not sure if you touched script for posting date.
https://github.com/frappe/erpnext/issues/9491

**Comment by tundebabzy** [comment]
> @tundebabzy can you please claim your bounty? lol

Gladly. I wasn't even aware of it. Thanks. I think the posting date issue has been fixed but I'll investigate.
