### ISSUE TITLE
Web Site Landing Page Problem 

### ISSUE THREAD

**Issue by sammish** [frappe/erpnext#9184]
I was change to test purpose ''landing page home to products'' after that i cant set any other page Please Check attached GIF file 
![test](https://user-images.githubusercontent.com/9355208/26966561-2fbaed0c-4d18-11e7-88bd-bd5d8974340b.gif)

**Comment by jwrober** [comment]
Can you upload that gif to the git issue here? That way it lives in the issue and not an external spot.

**Comment by sammish** [comment]
I already uploaded that GIF


Sammish Thundiyil
IT Incharge
Zia Innovation Trading Company
Al Khoniaini Building, 4th Floor, Suite1 Al Rabeea 2nd Street
Building No.8529, Dammam, KSA
M.+966-539194708
Email: sammish@sanford-me.com

________________________________

**Comment by netchampfaris** [comment]
Check if **Homepage is Products** is checked in Product Settings
![image](https://user-images.githubusercontent.com/9355208/26972933-91394998-4d31-11e7-9a5f-5dcde55981fe.png)

**Comment by sammish** [comment]
yes done ,, thank u
