### ISSUE TITLE
Browser freeze with high number of items

### ISSUE THREAD

**Issue by joezsweet** [frappe/erpnext#9186]
Hi all,
i'm experiencing problem with filters, browser freezing with a large number of items (100k) when trying to show filters or selecting field in filters when adding or when removing filters.

It doesn't matter how many record per page, the problem is that when "show filter" is clicked it has to find the number of record per filter and to do that it try to load all the records and so it freezes ..

see recorded for example: http://recordit.co/YHFkB2moJ1

**Comment by tundebabzy** [comment]
confirmed

**Comment by joezsweet** [comment]
@rohitwaghchaure do u think this is not a bug? ERPNext will become unusable ...

**Comment by sagarvora** [comment]
@joezsweet  Unable to replicate with 400K+ items.
See http://imgur.com/a/aaTH0

Maybe you need better RAM / processing power.

**Comment by joezsweet** [comment]
@sagarvora ah, i'll double check the ram and stuff. How much ram and processing power u have in the test?

**Comment by sagarvora** [comment]
@joezsweet 1 vCPU, 4 GB memory

**Comment by joezsweet** [comment]
@sagarvora uh ..that's not a lot ..could be high number of custom script in item table that's causing the problem?

**Comment by sagarvora** [comment]
@joezsweet it is highly probable. closing this issue for now. 
You can start a discussion on the forum if you are not able to figure it out. :slightly_smiling_face:
