### ISSUE TITLE
[Bug] Advance Amount is not updated in Sales Invoice.

### ISSUE THREAD

**Issue by sbkolate** [frappe/erpnext#9190]
1) Create Sales Invoice
2) Pay some amount
3) Check Outstanding Amount and Paid Amount

Note: Outstanding amount is updated, but Paid Amount is not updated. 
This is an issue when some one want paid amount in print format/report and it is not available in Invoice.
<img width="471" alt="screen shot 2017-06-08 at 9 01 31 pm" src="https://user-images.githubusercontent.com/6648915/26936937-b1fe23dc-4c8d-11e7-9db5-13f8fea83734.png">
 
Console:
<img width="215" alt="screen shot 2017-06-08 at 9 02 33 pm" src="https://user-images.githubusercontent.com/6648915/26937006-d532b49e-4c8d-11e7-9f17-064d639169a5.png">

**Comment by rohitwaghchaure** [comment]
@sbkolate We don't back update paid_amount from payment entry/journal entry. Paid Amount is shown in invoice only if it is POS. Why do you need it?

**Comment by rohitwaghchaure** [comment]
@sbkolate Same is for total_advance. If while making sales invoice, you adjust the advance payments, it updates total_advance amount.

**Comment by sbkolate** [comment]
@rohitwaghchaure This increases work while making print format & report for some clients.
We need to manually calculate Paid Amount and then format is accordingly Company Currency.

**Comment by mobentec** [comment]
@sbkolate We too would like the amount paid updated within the sales invoice.  We wanted to be able to print out an invoice so when customers call us and want a copy of what they paid and their current remaining balance, we had something to give them.  **What have you been doing as a work around?  Are there plans on making this a core update?**

**Comment by heatherpotter** [comment]
Us too! Our customers like to see the payment has been applied sometimes.
