### ISSUE TITLE
Allow bulk reconciliation from Payment Reconciliation Tool

### ISSUE THREAD

**Issue by PankajWadkar** [frappe/erpnext#9201]
We are Facing following issue while making an entry of Payment Reconciliation.

As we are trying to match payment entries with invoice Number, We are selecting the Invoice number but Allocated amount is not fetching automatically from Invoice/Journal Entry Details in Unreconciled Payment Details, as every time it has to enter manually which is time consuming process. 

Secondly Is it possible to provide a facility of Box tick in Invoice/Journal Entry Details to select the invoices, then selected invoice amount will be fetch by Unreconciled Payment Details which helps save the time in entries. If "Yes" then what is the procedure to implement the above practice.

**Comment by PankajWadkar** [comment]
Any Update?

**Comment by aakvatech** [comment]
I would like to know what is this solution going to be about. I am trying to write up a routine that will automatically do payment reconciliation by using earliest date of invoice and applying the unallocated amount to each of those invoices one by one. I hope I am not duplicating efforts here.

**Comment by Anuja-pawar** [comment]
PR: https://github.com/frappe/erpnext/pull/27128
