### ISSUE TITLE
 formula calulation is not working when Depends on Leave Without Pay is actually applied on basic 

### ISSUE THREAD

**Issue by sumitdas4u** [frappe/erpnext#9206]
![image](https://user-images.githubusercontent.com/28945509/26972313-e52be9e6-4d2e-11e7-8376-a10385b0efea.png)
i have made basic Depends on Leave Without Pay 
and PF calculation B*.12

![image](https://user-images.githubusercontent.com/28945509/26972348-0f2add10-4d2f-11e7-83be-257b4ba160f7.png)

but when someone took leave without pay then the basic got deducted but the pf calculation is same as the previous basic.

![image](https://user-images.githubusercontent.com/28945509/26972402-3bb65652-4d2f-11e7-802b-dad1cbf0789a.png)
![image](https://user-images.githubusercontent.com/28945509/26972414-49fb76de-4d2f-11e7-9551-d7a16f0f1bff.png)

**Comment by vishdha** [comment]
In Salary structure under provident fund child table check depends on leave without pay
![1](https://user-images.githubusercontent.com/6947417/27376329-73d9967a-568f-11e7-9dcf-ec2a28a90d80.png)
![2](https://user-images.githubusercontent.com/6947417/27376335-7742fcfc-568f-11e7-899a-75d5b442b732.png)
![3](https://user-images.githubusercontent.com/6947417/27376383-98a30e6e-568f-11e7-8824-5b4c0d1e0de9.png)
