### ISSUE TITLE
[Feature] IT management

### ISSUE THREAD

**Issue by ishanloya** [frappe/erpnext#9215]
Hello all,
I was thinking of creating a new module (or use the Support module) to manage my company's IT inventory. As the number of devices and software in the organisation goes up, it might be nice to have a place to manage all of this in one hub. Do let me know if this is something that others might find useful and if you have suggestions to make this better. 

Here are some thoughts:

- [ ] New module for IT or use the existing Support module

- [ ] New device doctype with fields for User, IP address, MAC address, device name, device type, device specifications, etc.

- [ ] Device naming possibly based on department/branch doctypes

- [ ] New software doctype with fields for serial keys, subscriptions (link with proposed subscription doctype or separate?), software vendor, number of licences, etc.

- [ ] Link with Active Directory/LDAP to get security groups, OUs if this possible or even useful

- [ ] Maybe a list of cloud servers, hosting provider, keys

- [ ] Report showing status of devices. E.g. antivirus installed/not, system under maintenance?

**Comment by jk2081** [comment]
I think this is a good idea. I can see it being a good fit for our company also. Perhaps, we can contribute some code from our developer resources. Also, I would prefer it to be a separate IT module. If you can help with some specifications, we can get started.

**Comment by rmehta** [comment]
Yeah seems like a lot of people can use it. A good place to start would be more detailed specs.

**Comment by Mistaaah** [comment]
Yes nice Idea! Also like an incident or support ticket system with email support and service/product request management system with approval workflows available would be great! I'm sure all business think IT is an integral backbone of the business.... like servicenow...

**Comment by jwrober** [comment]
I would take a good look at existing issues in the repository as well. There are a number about IT Asset Management and related subjects that could be combined into a nice new addition to the platform.

**Comment by giuseppelamatrice** [comment]
@ishanloya What do you think if we create first feature for this scenario:
- [ ] "Credit time" rechargeable for Customer (ex: 1.000 minutes of support).
- [ ] Customer send support request from portal.
- [ ] "Start" button to start countdown for assistance (ex. for remote control).
- [ ] "Finish" button to stop coutdown for assistance.
- [ ] Save "support timestamp" from/to.
- [ ] When finish "credit time" for support recharge it with sales order.

**Comment by robinrosenstock** [comment]
work started in this frappe app: https://github.com/tueit/it_management

**Comment by wojosc** [comment]
@geniusupgrader Thank you for posting this. We are going forward with our app pretty quickly and are always working closely to frappe guidelines.

**Comment by jma4227** [comment]
@geniusupgrader is your app working ? I’ve been trying to configure my own but I’m fairly new to erpnext . Wondering if I could fork it out and work on it.

**Comment by robinrosenstock** [comment]
@jma4227 it's not my app. It's from tüit gmbh and Wolfram Schmidt (wojosc).
I have installed it on my erpnext and its working.

See the wiki for installation: https://github.com/tueit/it_management/wiki/Installation

**Comment by wojosc** [comment]
@jma4227 you can install our app on a v12 ERPNext instance. Yes it works :)

**Comment by jma4227** [comment]
Excellent, does it utilize serialized assets? I’m so glad I don’t have to recreate the wheel ... I’ve been trying to overwrite the controllers by using hooks and I’m losing my mind

**Comment by wojosc** [comment]
@jma4227 What do you mean? I'm happy to give you a quick introduction via screen sharing if you like.

**Comment by jma4227** [comment]
So my application is asset management, all of my devices in my department have serial numbers. Employees get assigned devices, and vehicles also have assets assigned. I haven’t been able to use a serial number with any of my fixed assets

**Comment by jma4227** [comment]
Btw, I’m not trying to override your controllers ... I’ve been trying to learn how the hooks.py file works and doc_events hook. I’ve been trying to override modules such as BuyingController, StockController.

**Comment by wojosc** [comment]
@jma4227 I'm not a developer so I can't realy give you any info on the hooks.py etc.

Our first blue prints have been strongly influenced by combodos iTop https://www.combodo.com/itop-193

We mainly use IT Management for inventory of all our customers IT items. We wen't from only having Configuration Items at first to sub-grouping in Configuration Items, User Accounts, User Groups, Software Instances, Licences which are mostly all grouped under Solutions in some way useful for us. All DocTypes have different naming series.

If you would like to be printing bar- or qr codes on your assets you'll have to add this, as we do not use this yet.

IT Managment has no links to ERPNext's Assets at the moment. We have fast relationships into Items, Issues and Projects though.

Regards

**Comment by jma4227** [comment]
Okay, thanks for the insight ... I can’t seem to find a straight answer , but the docs say that assets can be serialized ... are the docs correct and there’s an underlying issue or are the docs incorrect and haven’t been updated to reflect the current version.?

**Comment by wojosc** [comment]
@jma4227 Yes, assets are serialized. Though these have no direct link to our IT Management items. And also have no direct link to a User or Contact.

You can add a field of the type Link which leads to Contact to utilize this.

Regards

**Comment by jma4227** [comment]
I think there is a slight misunderstanding between serialized and having a serial number. And I think that’s where the confusion lies with all the questions. I do not think it has anything to do with your app though. It is within the core programming

**Comment by wojosc** [comment]
@ishanloya have you installed our latest version? We have quite a bit covered from your initial need...

**Comment by ishanloya** [comment]
@wojosc not yet but will definitely check it out. Thanks 😊

**Comment by wojosc** [comment]
Latest Version to be found here: https://frappecloud.com/marketplace/apps/it_management
