### ISSUE TITLE
[Bug] Deleting Rows Unchecks Update Stock in Invoices

### ISSUE THREAD

**Issue by faztp12** [frappe/erpnext#9217]
Hi
Please see the gif below. This is observed even when there are multiple rows., in both Sales & Purchase Invoices.

![update_stock](https://user-images.githubusercontent.com/12441615/26998465-9ad75484-4da1-11e7-9ea7-82e9997a267b.gif)

I tried to find the root cause of this, but failed.

Thank you

**Comment by vishdha** [comment]
After deleting an item from child table update_stock value not getting changed but,  HTML tag value changed.

**Comment by vishdha** [comment]
![update_stock](https://user-images.githubusercontent.com/6947417/27427619-3cb99e1e-575d-11e7-994a-87b94aec6748.gif)

it refresh update_stock on save and refresh page
