### ISSUE TITLE
Cannot add new Reference Customer/Sales Partner/Supplier from Contact form

### ISSUE THREAD

**Issue by joolsr** [frappe/erpnext#9220]
Using
ERPNext: v8.0.45 (master)
Frappe Framework: v8.0.65 (master)

To Replicate:-

1. Take an email in email Inbox
2. Select 'Actions - Add Contact to add contact
3. This takes you to the Contact form with the first and last name and email address filled in correctly. 
4. Add new row under 'Reference to link contact to to Company/Sales Partner or Supplier. If required customer/sales partner or Supplier isn't shown there is no capability to add a new entry for this.

**Comment by joolsr** [comment]
This is still a bug in vers 8.6.0, please can you check and have another look at this please?

**Comment by joolsr** [comment]
![peek 2017-08-15 15-13](https://user-images.githubusercontent.com/934876/29320680-eb0bc856-81cf-11e7-8ea5-2c2735a11d4b.gif)

**Comment by mbauskar** [comment]
@joolsr,

Just checked the issue and it seems to work fine, please try to save the form then the links will appear. Closing the issue please re-open it you are still facing the problem

**Comment by joolsr** [comment]
I understand now from Umair's email that its an issue relating to the architecture of the application ie

 _As per the design, you should first create a Customer master, and then create Address and Contact from the Customer master only. Since the Contact record itself is not saved, allowing creation of new document on top of it will not be recommended user experience. Will be great if you can make a standard practice of first creating a Customer/Supplier, and then creating Contacts and Addresses from the parent master._

I still think in terms of usability this shoudl be revisited
