### ISSUE TITLE
Ignore User Permission Seems to be not Working

### ISSUE THREAD

**Issue by creamdory** [frappe/erpnext#9223]
Running on these versions:
erpnext 8.0.46
frappe 8.0.65

Hi all. So I have this setup:

1. User 1 has a role of **Employee User**.
2. **Employee User** Role has "Apply User Permission" setup with set "If Employee"  for _Employee Doctype_.
3. User 1 is only restricted to its own record in _Employee Doctype_ via User Permission Manager.
4. Now there is a _Custom Doctype_ that has a linked field to the Employee Doctype. For the linked field, I have checked "Ignore User Permissions" in order for values not to be restricted to any users.
5. But when I created a record in the _Custom Doctype_ using **User 1** log-in credentials, the link field for employee only shows "User 1" value.

Expected Output:

1. Users can only see their own employee record (cannot used "If Owner" since the HR personnel are the one creating the records).
2. Though there is a field-based restriction for Employee Doctype, link field restriction should be override by the "Ignore User Permission" setting of the link field.

Please advise.

Thanks

**Comment by maisonarmani** [comment]
Having the same problem... Even after checking "Ignore User Permissions" its still enforces...

Is it a bug that has been fixed ??
Thanks

**Comment by rohitwaghchaure** [comment]
Hi @maisonarmani @creamdory 

I have checked in local account and it's working properly. Seems you have added the restriction on the employee master.
@creamdory are you abel to view all the employees in the list

**Comment by creamdory** [comment]
Hi @rohitwaghchaure ! Thanks for checking this:

We have added restriction in the employee master since we need to restrict viewing of only the user's information in the employee doctype. Should this be override with "Ignore User Permission" ? Also, if this is our usecase, how do we do it according the ERPNext's current feature?

**Comment by rohitwaghchaure** [comment]
Hi @creamdory 

You have applied the permission on employee master which allows user 1 to see only one records of the employee. Therefore you can only see the one employee in the custom doctype, to resolve this you need to give access to view the records which has been created by the user or show all the employee records with read permission only. Kindly check with the solution maybe it will resolve your problems.
I am closing the issue now, kindly reopen it if the issue still persists

**Comment by creamdory** [comment]
Hi @rohitwaghchaure ! Unfortunately, this will not solve our usecase as the record for Employee doctype should only be visible for the current log in user employee information. But there is this link field in another Custom doctype which has link to Employee and this needs to show all.

**Comment by creamdory** [comment]
Thanks by the way @rohitwaghchaure

**Comment by ubfacility** [comment]
please did you find a solution?

**Comment by creamdory** [comment]
@ubfacility ,  we just use a "hack". We added a custom script to see if the user "has_role" then we hide some important fields in the `Employee` doctype to protect access even though all needs "Read" access because of the link.

**Comment by ubfacility** [comment]
please can i have a little pick at the custom script?

**Comment by creamdory** [comment]
@ubfacility 

```
 if (!frappe.user.has_role("Role_Here")) {
            frm.toggle_display(field_name_here, false)
        }
```
