### ISSUE TITLE
Missing field "columns" in tabCustom Field

### ISSUE THREAD

**Issue by joezsweet** [frappe/erpnext#9233]
Hi there, 

it seems we're missing field `columns` in `tabCustom Field`, can you please double check? As consequence it's not possible to resize columns width.

ERPNext: v8.x.x-beta (d0ac0bd) (develop)
Frappe Framework: v8.x.x-beta (4203ebd) (develop)

**Comment by sagarvora** [comment]
Hi, we will fix this. Meanwhile, you can create a custom field called `columns` in the `Custom Field` doctype.

**Comment by joezsweet** [comment]
@sagarvora i've added and wrote a patch to my.custom app in order to create it if not exists.

**Comment by sagarvora** [comment]
Merged.
