### ISSUE TITLE
Razorpay after payment redirect page not working. 

### ISSUE THREAD

**Issue by shashankcapoor** [frappe/erpnext#9237]
After completing the payment, the user is redirected to {Sitedomain}/integration/ordersfor which the it gives the error that the page is missing or has been moved.I have setup the redirect url to {sitedomain}/me in the Razorpay settings.But instead of redirecting there, the user is redirected to orders page.

**Comment by umairsy** [comment]
Reported via discuss https://discuss.erpnext.com/t/razorpay-integration-redirect-url-not-working/24794/2

**Comment by umairsy** [comment]
Fixed. If this issue still prevails, we can reopen.
