### ISSUE TITLE
Can't delete TAG

### ISSUE THREAD

**Issue by krnkris** [frappe/erpnext#9239]
If make a tag with not common characters
it can't be removed anymore.

as of:

https://discuss.erpnext.com/t/cant-delete-tag/24801/1

**Comment by tundebabzy** [comment]
Hello @krnkris 
Thanks for reporting this. In order to speed up the resolution of this, please add steps to reproduce this issue

**Comment by krnkris** [comment]
Hello @tundebabzy 

Thank you to taking care about this issue.

To replicate:

You log in.
Upper right corner
You go to the E-mail or Opportunities.

You make a tag for an E-mail or for an Opportunity.
TAG name: 
szállítás 
and/or 
ridefutár

Now you see the two tag.

You can't delete the two tags.
It stays for ever?

**Comment by tundebabzy** [comment]
Fixed
