### ISSUE TITLE
setting up SSL erpnext

### ISSUE THREAD

**Issue by Sealcoatings** [frappe/erpnext#9240]
Hi, can somebody help as im getting an error
403 Forbidden when i goto the SSL site of erpnext.
What is the issue and how do i redirect from http to https ?

thank you

**Comment by mona1977** [comment]
Hi, you need to setup SSL certificate , Please can you add my SKYPE - SUREN_GUPTA, I will explain you how to with erpnext.

**Comment by adityaduggal** [comment]
This does not seem like an issue with frappe or erpnext but an individual issue, please use forums for the same. Closing for the time being.

**Comment by mona1977** [comment]
Hi,

How are you? This is follow up email of the our last communication.

Do you have any project, where we can work together? If you have any query, please let me know.

 

Surendra Gupta
