### ISSUE TITLE
On multiple Delivery Notes from a Sales order the Tax applied on Actuals is applied on all the Delivery notes created.

### ISSUE THREAD

**Issue by Arundhatii** [frappe/erpnext#9243]
Reported via https://frappe.erpnext.com/desk#Form/Issue/WN-SUP25627

For tax entry rows in sales Invoice when the entry is regarding some percentage it should come in all the delivery notes. But in case of an actual value say 200/-, then if that comes in all 2-3 delivery notes its charging extra from the actual Invoice. In case of 200/- of one actual type row in Sales Invoice, Its charging that 200/-, 3 times If I make 3 Delivery notes from that Invoice.

**Comment by manassolanki** [comment]
As per the current design, the tax isn't linked with items. So if we make multiple delivery notes from a single sales order and actual tax is applied on the all the items, then it isn't possible to find out the distribution of that actual tax between all those items as this may be possible that actual tax is only for a single item or may be for all items. We can't differentiate this until and unless tax will be linked to the each item. For the time being, the user has to manually manage the tax distribution (for actual type tax only) if he/she changes the quantity or items.
