### ISSUE TITLE
Multi-currency issue in Payment Entry - Amount in Words

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#9261]
Company currency is USD. In the Payment Entry, payment amount has currency LBP. 

In the Print Format of Payment Entry, the value for Amount is Words is correctly calculated based on amount in LBP. But it still shows the currency as USD. It should show LBP as a currency.

**Comment by nabinhait** [comment]
Screenshot please

**Comment by umairsy** [comment]
![screen shot 2017-06-13 at 5 57 35 pm](https://user-images.githubusercontent.com/910238/27082338-f8dc1264-5061-11e7-9f5b-e4f023dd432c.png)

**Comment by umairsy** [comment]
![screen shot 2017-06-13 at 5 57 35 pm](https://user-images.githubusercontent.com/910238/27082386-214eecd0-5062-11e7-8b33-0aa863b55bb4.png)

**Comment by sagarvora** [comment]
Customisation issue, closing.
