### ISSUE TITLE
[Feature] Production Capacity Simulation

### ISSUE THREAD

**Issue by creamdory** [frappe/erpnext#9269]
In Production Planning Tool, it has a feature to identify the qty of needed materials for a specified number of item to manufacture. This is very helpful as it doesn't only show the needed qty but it also shows the qty requested for purchase, ordered qty and actual qty. 

Will it also be best if we had a feature that simulates Production Capacity wherein we would know how many Item to Manufacture we can produce basing from the current stock balance in stock warehouses in a company? This will allow us to know the capacity of existing stocks and how much order we can cater from the on hand raw mats inventory.

**Comment by bcornwellmott** [comment]
This is currently available using the BOM Stock Report.
![image](https://user-images.githubusercontent.com/16806041/27142656-89b16a5e-50e0-11e7-90f4-e3faae2b7a2a.png)

**Comment by creamdory** [comment]
Hi @bcornwellmott ! Thanks for the reply. Though this almost solves our usecase, it lacks calculation on how many BOM item will be produce in the enough raw materials available.
