### ISSUE TITLE
[Feature Request] Multi-currency for Tax

### ISSUE THREAD

**Issue by addymuliady** [frappe/erpnext#9270]
Currently, we are unable to collect tax based on Account Currency if the transaction is conducted in other currencies.

Of course, there is a need to set up exchange rates first for this to happen. Else, print message that there is no exchange rate for tax.

Use case: I am collecting and paying taxes in local currency.

I am not the only asking for this:
https://discuss.erpnext.com/t/multiple-currencies-tax-rates-in-pos/18098
https://discuss.erpnext.com/t/taxes-and-charges/2011/5

![image](https://user-images.githubusercontent.com/21187126/27115911-6a10934e-5100-11e7-9b5e-d405a870c09d.png)

**Comment by addymuliady** [comment]
Please back this bounty.

https://www.bountysource.com/issues/46200499-feature-request-multi-currency-for-tax

**Comment by harshit-30** [comment]
Please create another issue if it is replicable after v13.10.
