### ISSUE TITLE
Login Issue - After logout, browser's back button logs you in again

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#9272]
When we logout then press back bottom of browser it get automatic sign in.

**Comment by manassolanki** [comment]
@umairsy I think that's cached page only. You can't do anything without logging again.

**Comment by sagarvora** [comment]
![not a bug](https://user-images.githubusercontent.com/16315650/27322009-17a67f42-55ba-11e7-867e-d924816ad9e8.gif)


Even if desk if visible, cannot perform any action without logging in again. Closing.
