### ISSUE TITLE
Bug in the item while making variant of a item.

### ISSUE THREAD

**Issue by manassolanki** [frappe/erpnext#9279]
Error in the function make_variant_item_code()

From the discuss post https://discuss.erpnext.com/t/data-import-tools-error/24876

**Comment by manassolanki** [comment]
Fixed

**Comment by ShehataGhattas** [comment]
Dear, 
I have seen the fixing point i have change it manually, but its took me to another one its requesting for the item code and i have make the stock setting the Item Naming By naming series

**Error for row (#21) : {"message": "Item Code is required", "indicator": "red"}**
