### ISSUE TITLE
Error when Making Bank Entry in payroll processing

### ISSUE THREAD

**Issue by sumitdas4u** [frappe/erpnext#9288]
Hello all

When processing payroll I get stumped when its time to make bank entry.

It gives me the following error message

"Total Debit must be equal to Total Credit. The difference is -0.0100000000093"

Is this a bug or am I doing something wrong??

Regards

please refer : 

https://discuss.erpnext.com/t/error-when-making-bank-entry-in-payroll-processing/20943/15

**Comment by jwrober** [comment]
Duplicate - https://github.com/frappe/erpnext/issues/9300

**Comment by sagarvora** [comment]
Hi @sumitdas4u, can you please share the figures and console log so we can replicate this issue?
