### ISSUE TITLE
Hard coded "text-right", when trying to align labels of print format to the left

### ISSUE THREAD

**Issue by ci2014** [frappe/erpnext#9289]
Hello there,

on every print format, no matter if it is Sales Order or Sales Invoice etc., you can find the following, if you want to align the labels to the left.

![image](https://user-images.githubusercontent.com/8351245/27132197-2c578e6e-510e-11e7-92f6-16ab5af082af.png)

The tax is always aligned to the right, because there is a hard coded "text-right" class.

Any ideas?

Thank you.

**Comment by sagarvora** [comment]
Hi, what kind of customisation are you doing?
Please share the code.

**Comment by ci2014** [comment]
@sagarvora I was simply creating a print format with the User Interface and chose the setting "Align labels to the left".

![image](https://user-images.githubusercontent.com/8351245/27321747-bb3b02dc-559b-11e7-9273-7fa3a483309f.png)

I didn't code for this purpose.

**Comment by sagarvora** [comment]
Merged into `develop` branch.
