### ISSUE TITLE
Rounding error while making bank entry from Process Payroll

### ISSUE THREAD

**Issue by nabinhait** [frappe/erpnext#9300]
**Error message:**
"Total Debit must be equal to Total Credit. The difference is -0.0100000000093"

**Discussion:**
https://discuss.erpnext.com/t/error-when-making-bank-entry-in-payroll-processing/20943

**Comment by mohamadosama** [comment]
Having this issue with a multi-currency Journal Entry:
"Total Debit must be equal to Total Credit. The difference is 0.006569999997736886"
while my debit was 30,418.86
I tried this work around by adding the decimals from the third place, so I typed the debit as followin:
30,418.866569999997736886
It got automatically rounded to:
30,418.86657
and the entry was saved and submitted.
