### ISSUE TITLE
Email Error: Encryption key is invalid, Please check site_config.json

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#9303]
Hi,

The error message "Encryption key is invalid, Please check site_config.json" is popping up when trying to send email messages after a recent update. Current solution is for user to re-enter password in the Email Account. Reference below:

https://discuss.erpnext.com/t/after-migration-encryption-key-invalid/24612

Please fix

Thanks

**Comment by franzos** [comment]
I have a similar problem but with the password reset under `Settings > User > Reset Password`. I get the same error message `Encryption key is invalid, Please check site_config.json`

`desk.min.js:1258 POST http://domain.de/ 417 (EXPECTATION FAILED)`

**Comment by rmehta** [comment]
This is not a bug.

Most likely scenario is that you migrated a site to another server/bench, and did not update the encryption key in `site_config.json`. 

Check the encryption key in your original `site_config.json` or `sites/common_site_config.json`

**Comment by rohansh-tty** [comment]
I have this issue, even though I have copied encryption key from original site_config.json. 
Bench Version: 5.0.0
Frappe Version: 13.58.11
