### ISSUE TITLE
Filter using 'Not Equals' condition doesn't fetch options

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#9304]
Hi,

When using the 'Not Equals' condition in the filters, the options are not fetched. If for example, I want to filter for a particular warehouse from my list of warehouses, using the ID 'Equals' ..... presents a link field from where the required warehouse can be selected. If the condition is however changed to ID 'Not Equals' ..... there is only a data field and the warehouse ID has to be punched in manually

Please fix

Thanks

**Comment by vishdha** [comment]
Fixed via https://github.com/frappe/frappe/pull/3571
