### ISSUE TITLE
Bank Reconciliation: Clearance date for Wire transfer 

### ISSUE THREAD

**Issue by vorasmit** [frappe/erpnext#9307]
For Wire transfer transactions, Reference date = Clearence date. So we can add this logic to minimize the transactions dealt with in bank reconciliations.

Reference date for such transactions come from bank statement, and hence it should be equal to clearance date.

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.
