### ISSUE TITLE
Profit & Loss Report

### ISSUE THREAD

**Issue by Mishaal1021** [frappe/erpnext#9310]
Hi,

I need to have the ability to print P&L by month & YTD. 

For instance for May, I need two columns. Column 1 for May P&L, Column 2 for YTD P&L.

Same goes for balance sheet although its not as important, but need to have a cut off date at least. It should also allow you to Auto-email these reports. 

Regards,

Mishal

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.
