### ISSUE TITLE
Show timesheets in portal. 

### ISSUE THREAD

**Issue by shashankcapoor** [frappe/erpnext#9316]
As per the discussion

**Comment by shashankcapoor** [comment]
Issue got saved with incomplete info. 

As per the discussion https://discuss.erpnext.com/t/show-timesheets-in-the-portal/24921
A mechanism to provide timesheet information to the customer through portal is needed. 

Same is needed for tasks, documents (SLA contracts) , quotations and projects. 
We should be able to control which fields and what information can be seen by the customer. 

This would provide a greater transparency to the customer from the portal itself.

**Comment by rmehta** [comment]
- [ ] Add a property "Show in Portal"
- [ ] If checked, show in portal

**Comment by vishdha** [comment]
https://github.com/frappe/erpnext/pull/10037

**Comment by chdecultot** [comment]
This issue seems to have been addressed with the pull request referenced by vishdha.

Therefore I'm closing it.
