### ISSUE TITLE
Organisation Chart Tree

### ISSUE THREAD

**Issue by LifeP** [frappe/erpnext#9317]
Create an organisation chart in ERPNext, like profit and loss statement/ chart of accounts.
Idea is to be able to - 
1. Auto-generate an organization chart/tree (with designations). This is a requirement of quality management standards.
2. Be able to see employees department wise, designation wise in one go.
3. See HR Salaries, at a glance like in profit and loss statement.
<img width="1186" alt="screen shot 2017-06-15 at 7 14 28 pm" src="https://user-images.githubusercontent.com/16747599/27185819-1caaa360-5204-11e7-96b0-324f91ccea51.png">

**Comment by ankush** [comment]
https://github.com/frappe/erpnext/pull/26261
