### ISSUE TITLE
If field is hidden from user, the field is erased when user saves.

### ISSUE THREAD

**Issue by cgpurbaugh** [frappe/erpnext#9318]
See Title

ERPNext V7.2.31

**Comment by manassolanki** [comment]
Could you please explain your use case and some example? Are you talking about the naming of the document?

**Comment by cgpurbaugh** [comment]
@manassolanki Not the title, but any fields with a Permission level higher than that user can read.

Example: Sales Order pricing is perm level 2, but Quality User only has level 1.  If the Quality User saves the document, pricing is deleted.

**Comment by manassolanki** [comment]
@cgpurbaugh, I think it is not deleted it is overwritten by the new user ie Quality User in your scenario.

**Comment by manassolanki** [comment]
Hi @cgpurbaugh,
As of now if some permission level is applied to a field and value of that field is dependent on some front-end calculation, then we have to add that field in the cur_frm and while adding that the default value of that field is set in that variable. After that we save the form, that value got replaced in the form.
For ex., in your case, if you set permlevel on the price in the sales order. Now you won't got any data for the price from the backend but while processing that data in the frontend we need price to calculate the total price so we have to add that without any value from the backend and hence the default value is set in that field. After that, if you click on the save button the new default value got saved in the form (0 for integer or float type).
This is as per design if you want to apply permlevel on any field then that field should not be used in any frontend calculation.

**Comment by manassolanki** [comment]
Closing issue as the user has to take care when applying for permission on any field whether that field is used in any front end calculation
