### ISSUE TITLE
Hosted User able to customize Options in the Standard field

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#9323]
As observed in the issue by Moises:

In the Email Queue, he was able to add Custom Option in the standard Select field. In the Standard, hosted user should not be able to add Custom option. Also, for the Date field, he should not be able to customize value in the Option field.

**Comment by nabinhait** [comment]
@umairsy We can't stop customisation of "Options" for all the select and date fields. In some cases, it should be blocked, we need to write a validation for those cases.

**Comment by manassolanki** [comment]
Only those customization of option property will be allowed for the standard field where fieldtype is as given below
- Select
- HTML
- Read Only
