### ISSUE TITLE
Inspection required before delivery isn't working for Item Variants.

### ISSUE THREAD

**Issue by Arundhatii** [frappe/erpnext#9332]
Reported via https://discuss.erpnext.com/t/how-to-creating-inspection-criteria-items-in-the-variant/24875

I defined a template with variants. On the other hand, I checked "Inspection Required before Delivery" and stored some values in the table. My expectation was generate these items inside variants automatically when I create them. However it didn't happen.

**Comment by tundebabzy** [comment]
Confirmed this. The problem is true for all tables in the variant like Taxes. Will fix ASAP.
