### ISSUE TITLE
Reports in ERPNext mobile app are not downloading or open as pdf. 

### ISSUE THREAD

**Issue by Arundhatii** [frappe/erpnext#9333]
Reported via https://discuss.erpnext.com/t/reports-erpnext-mobile-app-not-getting-download-or-open-as-pdf/24793

In ERPNext mobile app reports are not getting download in excel or csv. It is also not opening as pdf.

**Comment by netchampfaris** [comment]
I have tried to solve this, but was not successful. Downloading works fine if ERPNext is accessed from the browser.

**Comment by netchampfaris** [comment]
Found a solution

**Comment by rioshaz** [comment]
> I have tried to solve this, but was not successful. Downloading works fine if ERPNext is accessed from the browser.

i want to be pdf to b downloaded not opening in new tab
