### ISSUE TITLE
Editor unusable to create lists

### ISSUE THREAD

**Issue by danielmorlock** [frappe/erpnext#9334]
![editor-min](https://user-images.githubusercontent.com/1263320/27224741-0f70f74c-5297-11e7-863a-e752fb7f06db.gif)

Is there a way to implement a better wysiwyg editor https://www.tinymce.com/ ?

**Comment by rmehta** [comment]
![text-editor](https://user-images.githubusercontent.com/140076/27330417-ed86c902-55d6-11e7-95b2-d5e56a10d996.gif)

Can't replicate.

**Comment by danielmorlock** [comment]
Which Erpnext Version and which browser did you use?

**Comment by tundebabzy** [comment]
@danielmorlock what browser are you using? I have a feeling this is a browser issue

**Comment by danielmorlock** [comment]
We've tested this with Firefox 52.0.2 and Chromium Version 58.0.3029.81 (64-bit).

**Comment by ribx** [comment]
Both on Linux systems btw.

**Comment by realvinay** [comment]
There is an app now to replace frappe's Quill Text Editor with TinyMCE Text Editor
https://github.com/shridarpatil/frappe_tinymce
