### ISSUE TITLE
Conversion factor get multiplied by a factor 1000 (in case of float precision 3)

### ISSUE THREAD

**Issue by joezsweet** [frappe/erpnext#9344]
Hi there,

i'm getting an error while setting conversion factor, it get multiplied by a 1000 factor. I'm not sure why, it seems it's getting wrong decimal symbol, actual settings are # ###,## with precision 3. 

Have a look at: http://recordit.co/QP2ev99yKx

**Comment by sagarvora** [comment]
Hi @joezsweet, unable to replicate. Please provide steps.

**Comment by joezsweet** [comment]
@sagarvora here that comes:

- Go to system settings and change number format to #.###,## or # ###,##
- Float precision 3
- Go to Item and select an item from list
- Add new Unit of Measure for the Item and set conversion factor as an integer (1 or 2 or whatever)
- Save the item and check conversion factor it state what you entered * 1000

**Comment by sagarvora** [comment]
@joezsweet, please see GIF.

![9344](https://user-images.githubusercontent.com/16315650/27328269-358322b2-55cf-11e7-8d20-d5497502bde5.gif)

These number formats treat comma(,) as decimal(.)

**Comment by joezsweet** [comment]
well ..not sure what to say :( in some installation i do have the prob i need to inspect it better ..closing for now
