### ISSUE TITLE
Employee Loan currency

### ISSUE THREAD

**Issue by DrTrills** [frappe/erpnext#9360]
Found an error with currency on employee loan. It is showing in $ even though I selected an employee/company which uses another currency.

**Comment by vishdha** [comment]
![loan1](https://user-images.githubusercontent.com/6947417/27377880-e123d868-5693-11e7-9526-e62c8e4a0922.png)
![loan2](https://user-images.githubusercontent.com/6947417/27377884-e2e4f47a-5693-11e7-9d00-e210ef24ff23.png)

It's working fine at my side, if you still getting same error please  share  screenshots and the version you are working with

**Comment by vishdha** [comment]
show the screen short of company deafult_currency

**Comment by DrTrills** [comment]
<img width="467" alt="screen shot 2017-07-05 at 1 37 22 pm" src="https://user-images.githubusercontent.com/1430005/27877018-242e8b00-6187-11e7-839f-1068254d195e.png">

**Comment by vishdha** [comment]
please update your bench to the lastest version.

**Comment by DrTrills** [comment]
Hi @vishdha I just updated

Installed Apps
ERPNext: v8.3.5 (master)
Frappe Framework: v8.3.9 (master)

unfortunately it is still showing the same as above. Please let me know if I can provide any additional info to help fix this bug.

Thank you for your supprt

**Comment by tundebabzy** [comment]
Hello @DrTrills 
Please confirm if the default currency in your Global Defaults is $.

**Comment by DrTrills** [comment]
Hi @tundebabzy my global defaults is set to USD $.

Does that override the other company currency?

**Comment by tundebabzy** [comment]
No but that is the source of the bug. The bug will soon be merged

**Comment by tundebabzy** [comment]
@DrTrills This has been fixed now. It should be live within a week or so

**Comment by DrTrills** [comment]
@tundebabzy confirmed it's fixed. Thank you! Nice job 👍
