### ISSUE TITLE
While importing item variant with item naming by naming series, user have to add item code manually

### ISSUE THREAD

**Issue by manassolanki** [frappe/erpnext#9361]
If in the stock settings, item naming is chosen as "naming series" and data is imported for the item variant type (creating new item variant), then user have to provide both naming series and item code in order to import that file.
Source: https://discuss.erpnext.com/t/data-import-tools-error/24876

**Comment by ankush** [comment]
Fixed in latest release. Naming series isn't a mandatory field now for variants.

**Comment by ankush** [comment]
IIRC I fixed this in last version.
