### ISSUE TITLE
"Sent Via ERPNext" in email footer

### ISSUE THREAD

**Issue by creamdory** [frappe/erpnext#9363]
Hi! Seems that ERPNext's hook variable default_mail_footer cannot be override by app hook's mail_footer: 

```
default_mail_footer = """<div style="text-align: center;">
	<a href="https://erpnext.com?source=via_email_footer" target="_blank" style="color: #8d99a6;">
		Sent via ERPNext
	</a>
</div>"""
```
I believe there should also be a global setup to use default ERPNext footer or your own customized.

**Comment by creamdory** [comment]
So there is already a setting for this in System Setting:

![disable email footer](https://user-images.githubusercontent.com/21003054/27572720-246e438c-5b40-11e7-9743-de36e2de2c5c.png)

**Comment by creamdory** [comment]
Please close. Thanks!

**Comment by Mickey-Raj** [comment]
How  to do the command in filed as mandatory:
