### ISSUE TITLE
Supplier Quotation Request screen displays Item Codes well, Report shows same thing twice.  See Below

### ISSUE THREAD

**Issue by Rgottsch1** [frappe/erpnext#9393]
![image](https://user-images.githubusercontent.com/29579531/27346598-561c198c-55b3-11e7-8fb6-d59e4f01e852.png)

![image](https://user-images.githubusercontent.com/29579531/27346618-5d86381a-55b3-11e7-82cc-1ed92959fa03.png)

**Comment by bcornwellmott** [comment]
You should be able to change this with the Print Format. The issue is that your description and item name are the same, whereas in the record table it is showing item code. Change the Print Format to show item code and item name (or description) and that should fix it.

**Comment by Rgottsch1** [comment]
Thank-you.  I have made the change, sorry still learning the system.

Rob Gottschalk
[Part 2.2]
GEM Manufacturing, Inc.
p: 262-857-7274 x 217 | f: 262-857-2917
