### ISSUE TITLE
General Ledger Report Shows Null Voucher Type in Other Lenguage

### ISSUE THREAD

**Issue by RandyLowery** [frappe/erpnext#9394]
https://discuss.erpnext.com/t/general-ledger-report-shows-null-voucher-type-in-other-lenguage/25115

In General Ledger report the field voucher type that reference the voucher number dissapear when the user language is other than english, Spanish my case, making imposible to access the voucher via the quick link as it throws a doctype not found error.

**Comment by mona1977** [comment]
Hello, Please add my SKYPE - suren_gupta, i will explain you how to resolve this issue, did you setup latest languages library?

**Comment by RandyLowery** [comment]
hi Please advise how to set up, i would really appreciate it

**Comment by mona1977** [comment]
Hello,

 

How are you? Sure , Please can you add my SKYPE – suren_gupta

 

I will explain you all details.

 

Surendra Gupta

**Comment by rohitwaghchaure** [comment]
Hi @RandyLowery 

Are you still facing the problem?
