### ISSUE TITLE
Localization Module + GST

### ISSUE THREAD

**Issue by rohitwaghchaure** [frappe/erpnext#9395]
- [x] Add localization module in erpnext app

- [ ] Add country wise doctype, reports, custom_fields folder in the localization module 

- [ ] Make new state doctype, and create states during setup wizard based on selected country.

- [x] Add GSTIN field and change the fieldtype of field state from data to link in the address doctype, also validate gstin based on regex given by the government and the state()

- [x] Make new HSN Code doctype and add field hsn_code in the item master.

- [x] Add custom field Customer GSTIN(fetch from shipping address), Company address, Company GSTIN(fetch from company address) in the sales invoice doctype

- [x] Add custom field Supplier GSTIN(fetch from supplier_address), Company GSTIN(fetch from shipping address) in the purchase invoice doctype

- [x] Add field hsn_code in the sales invoice item and purchase invoice item table. On selection of item in sales invoice item or purchase invoice item pull their respective hsn_code from item master and set into the sales invoice item or purchase invoice item's hsn_code field

- [ ] Add new report, item wise sales register, with column Posting Date, Item Code, item Group, HSN Code, Customer,  Customer GSTIN, Customer Group, Receivable Account, Mode of Payment, Project,
Sales Invoice, Rate, Qty, Amount

- [ ] Add new report, item wise purchase register, with column Posting Date, Item Code, item Group, HSN Code, Supplier,  Supplier GSTIN, Customer Group, Receivable Account, Mode of Payment, Project, Pales Invoice, Rate, Qty, Amount

**Comment by PrakashH** [comment]
Need to add SAC (Service Accounting Codes) as well.

**Comment by rmehta** [comment]
This is completed. Will finish off documentation and final testing and update by EOD today.
