### ISSUE TITLE
Leading Employee Dashboard

### ISSUE THREAD

**Issue by LifeP** [frappe/erpnext#9407]
Create a Leading Employee Dashboard

1. Idea is to create a report where we get percentage of projects completed on time for an employee.
2. Number of suggestions/ Kaizen made.
3. Other Metrics could be added such as overtime (effort). etc.

**Comment by mona1977** [comment]
hi i can create report for the HR module, expertise in erpnext more then 5 years , Please add my SKYPE - suren_gupta

**Comment by kennethsequeira** [comment]
Closing this as it should be possible to create such dashboards from v12/13 onwards.
