### ISSUE TITLE
Stock Entry - Field Type for Naming Series editable by the User

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#9409]
In the Stock Entry, Naming Series is a standard field, based on which Stock Entry ID is generated. From Customize Form, User can change the Field Type of Naming Series field from Select to Data.

This also led to an issue when user creating new item. Check Issue WN-SUP25832 for more details.

**Comment by rohitwaghchaure** [comment]
Fixed via PR https://github.com/frappe/frappe/pull/3534
