### ISSUE TITLE
Interlinking Multi-Company Transactions

### ISSUE THREAD

**Issue by rijulmanch** [frappe/erpnext#9413]
### Internal Customer / Supplier

- [x] "Is Internal Customer" - Check if customer is internal
- [x] "Represents Company" - If customer is internal, link it to Company
- [x] "Allowed to Transact With" - Child table for which companies this Customer is allowed to transact

### Inter company Sale / Purchase

- [x] If internal customer / supplier is selected, on submission, show "Make Inter Company Invoice"
- [x] Map this invoice to the other company (pick Supplier based on respresents_company)
- [x] Copy rates (don't do on basis of price list)

### Note

- Tax will be manually selected
-  [ ] In Sales Invoice, allow liability accounts to be selected as income account

**Comment by umairsy** [comment]
Hello,

Given the scale of this feature, will be better to create a bounty for it. That will also help other members in the community who need this feature to sponsor it.

https://erpnext.org/bounties
