### ISSUE TITLE
Incorrect payment accounts in purchase invoice

### ISSUE THREAD

**Issue by mobentec** [frappe/erpnext#9415]
We are entering in a bill for a purchase of raw goods.  We create a Purchase Invoice and select the "Is Paid" checkbox.

Under "Payments" subheading, we select mode of payment "Credit Card".

For Cash/Bank Account, we need to select our credit card (American Express account xxxx) which is a liabilities account, but ERPNext is only listing Asset accounts from within it's drop down.

The way we were able to get around this, is to uncheck "Is paid", and then make a Payment Entry.  
When going through Payment Entry, it allows us to select the correct liabilities account (Amex Credit Card account).

![2017-06-21 at 09-39-39](https://user-images.githubusercontent.com/6663120/27387053-99dbf054-5665-11e7-9c41-457e747b2d65.png)

**Comment by tundebabzy** [comment]
I don't think the "Is Paid" check box was meant to treat non-asset accounts though

**Comment by nick9822** [comment]
Fixed via #9418
