### ISSUE TITLE
Dropship Purchase Order Creation Issues: Quotation -> Sales Order -> Purchase Order

### ISSUE THREAD

**Issue by chanyork** [frappe/erpnext#9417]
Hello I am having issues in creating a Purchase order with dropship product via  Quotation -> Sales Order -> Purchase Order.  It is saying "Could not find select shipment xxxxxxxxxxxx"

**Comment by mona1977** [comment]
Hello, same problem i was facing in my purchase order, please can you add my SKYPE , i will explain you changes required - suren_gupta

**Comment by chanyork** [comment]
sorry I do not have Skype.

Cheers,
York Chan
Mobile/Whatsapp  +852 98662380
chanyork@gmail.com
http://www.petpalace.com.hk

**Comment by mona1977** [comment]
Hi,

How are you? This is follow up email of the our last communication.

Do you have any project, where we can work together? If you have any query, please let me know.

 

Surendra Gupta

**Comment by nick9822** [comment]
@chanyork 
Please ask questions on community forum at https://discuss.erpnext.com/
Try creating Material Request and then Purchase Order.
