### ISSUE TITLE
Suggestion to introduce TEAMS in time sheets

### ISSUE THREAD

**Issue by Jaliya** [frappe/erpnext#9434]
If there are 10 team members who perform same task during a certain period of time what we do now is to make one TIME SHEET for the first team member and then duplicate the TIME SHEET, change the name of the team member, save it and duplicate again the TIME SHEET and repeat for 8 more times. 
If you can introduce teams for projects, and make it possible to make selected workers members of a team for the duration of a particular ACTIVITY TYPE, it may save a considerable efforts of data input.

**Comment by mhbu50** [comment]
+1

**Comment by dufani1** [comment]
Nice
