### ISSUE TITLE
Auto Batch Number Creation

### ISSUE THREAD

**Issue by srivatsats** [frappe/erpnext#9453]
I dont seen an Option for "Automatically Create New Batch" in the ERPNext version "ERPNext: v8.0.0-beta (d7de3c6) (develop)", that I am running. It is the expected behaviour or am I missing any setup configurations

**Comment by nick9822** [comment]
Please ask questions on community forum at https://discuss.erpnext.com

![capture 88](https://user-images.githubusercontent.com/10139291/27506596-053587aa-58d9-11e7-90ba-32203ba278ac.png)
