### ISSUE TITLE
Setup Wizard fails in German

### ISSUE THREAD

**Issue by lasalesi** [frappe/erpnext#9454]
Affects version: ERPNext: v8.1.1 (master)
Expected behaviour: Setup Wizard completes without errors.
Actual behvaiour: Setup Wizard fails with an error occured: Domain Services not found.
![setup wizard fails](https://user-images.githubusercontent.com/26505250/27498964-cb6ada06-5861-11e7-835a-2248ae318086.PNG)

Steps to reproduce:
* take a clean install of ERPNext (python install.py --production)
* Perform setup wizard with language German
* Select Domain "Dienstleistung"
* Complete wizard with normal values and click setup.
* Error message appears.

Workaround: performing the setup wizard in English works.

**Comment by TMF42** [comment]
Did you try to change the system language after the clean install? I faced a similar issue and also did the installation in German but after completing the setup in English I was unable to switch the system language.

**Comment by lasalesi** [comment]
The problem did not reproduce in 

     ERPNext: v8.2.3 (master)
     Frappe Framework: v8.2.6 (master)
