### ISSUE TITLE
Error importing contacts to group mail

### ISSUE THREAD

**Issue by Riadh-TIPS** [frappe/erpnext#9460]
i'm using the online version. when importing my erpnext contacts, it shows this problem
"Erreur de serveur : Veuillez vérifier vos logs du serveur ou contacter le support technique."
can anyone help me with this ?

**Comment by manassolanki** [comment]
Please comment the console log error.

**Comment by umairsy** [comment]
Hi,

Please post this query with the detailed console log on ERPNext community forum.

https://discuss.erpnext.com
