### ISSUE TITLE
file manager not working in 8.1.1

### ISSUE THREAD

**Issue by shameerpuri** [frappe/erpnext#9461]
The screen freeze once click on file manager icon in desktop. need to reload the page again for running the software.

**Comment by krnkris** [comment]
Same behaviour

Installed Apps

ERPNext: v8.1.1 (master)

Frappe Framework: v8.1.1 (master)

**Comment by shameerpuri** [comment]
Reload of file manager page do not respond however the rest of the software is working fine

**Comment by vishdha** [comment]
![anim](https://user-images.githubusercontent.com/6947417/27529837-a80b33c6-5a73-11e7-9297-1c49d293cf1d.gif)
please upgrade to 8.1.2

**Comment by shameerpuri** [comment]
Thanks vishdha ...

**Comment by krnkris** [comment]
Appreciate for the great support!
