### ISSUE TITLE
DHTMLX in ERPNext [Paid Development] 

### ISSUE THREAD

**Issue by popoi90** [frappe/erpnext#9462]
I want to use DHTMLX components in ERPNext. 
I want to know what's the cleanest way to do it.
I.E. I'd like to replace all "Grids" with DHTMLX grid components.

**Comment by rmehta** [comment]
nice.. did not know dhtmlx is now free for GPL licensed projects. But this might be compatible with Frappe Framework which is MIT

**Comment by popoi90** [comment]
Hi,

Even if I paid for DHTMLX, can I not use it with ERPNext ?

Peter

On Jun 26, 2017, at 07:08 AM, Rushabh Mehta <notifications@github.com> wrote:

nice.. did not know dhtmlx is now free for GPL licensed projects. But this might be compatible with Frappe Framework which is MIT

**Comment by rmehta** [comment]
You can, but its going to be a non-trivial exercise.

You can post a job at https://erpnext.org/erpnext-jobs <https://erpnext.org/erpnext-jobs>

**Comment by popoi90** [comment]
Ok, thanks for the reply.

Peter
