### ISSUE TITLE
Error when opening any module.

### ISSUE THREAD

**Issue by shashankcapoor** [frappe/erpnext#9469]
I have two sites 1 production and other development. I have changed the domain name in the logs to example.com and dev.example.com.
I'm facing this issue on both the sides after update.
Please let me know how to fix it.

Current version of both sites:
erpnext 8.1.3
frappe 8.1.2

Error log from Frappe.log,

 active_domains = frappe.get_active_domains()
AttributeError: 'module' object has no attribute 'get_active_domains'
[ERROR] 2017-06-26 08:29:43,577 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-06-26 08:29:43.532620-106.0.59.149-c18
[DEBUG] 2017-06-26 08:31:51,179 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: example.com
Queued events for site example.com
[DEBUG] 2017-06-26 08:31:51,201 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: dev.example.com
Queued events for site dev.example.com
[ERROR] 2017-06-26 08:32:53,972 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: example.com
Form Dict: {
 "cmd": "frappe.desk.moduleview.get",
 "module": "Setup"
}
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    if frappe.local.form_dict.cmd:
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    if (a in fnargs) or varkw:
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/moduleview.py", line 14, in get
    data = get_data(module)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/moduleview.py", line 29, in get_data
    doctype_info = get_doctype_info(module)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/moduleview.py", line 119, in get_doctype_info
    active_domains = frappe.get_active_domains()
AttributeError: 'module' object has no attribute 'get_active_domains'
[ERROR] 2017-06-26 08:32:54,022 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-06-26 08:32:53.973482-106.0.59.149-e3b

**Comment by umaepoch** [comment]
Hi,

I am facing the same issue on my production, after running a bench update.

**Comment by shashankcapoor** [comment]
I restarted the bench and it seems to be resolved.
Command I ran.

`bench restart`

Need someone from Erpnext to verify why this happened.

**Comment by umaepoch** [comment]
Thanks. I also ran bench restart and am able to open the modules. But, the Customize form option is still giving errors.

**Comment by tundebabzy** [comment]
hi @umaepoch , 
> Thanks. I also ran bench restart and am able to open the modules. But, the Customize form option is still giving errors.

Please open a fresh issue for this.
