### ISSUE TITLE
Production orders not showing on Calendar

### ISSUE THREAD

**Issue by graphskill** [frappe/erpnext#9474]
Not sure if this is a bug or by design

We have some "in process" prodution orders:

![image](https://user-images.githubusercontent.com/925619/27562758-f8e2c726-5ac5-11e7-907a-e29c1cffd9ce.png)

But they are not appearing on the calendar

![image](https://user-images.githubusercontent.com/925619/27562767-076654de-5ac6-11e7-8783-e22c5d964e1d.png)

Is there perhaps something I am missing when creating the production order?

We do have dates set in the production order

![image](https://user-images.githubusercontent.com/925619/27562776-111dae96-5ac6-11e7-9ef2-90a09411a1c4.png)

https://discuss.erpnext.com/t/production-order-calender/25221/2?u=ron_taylor

**Comment by graphskill** [comment]
Can anyone comment as to whether this is a bug or not?

We need to see production expected end dates in calendar format, so if this is not possible we can look at an external application for this feature (perhaps google calendar or similar) but it would be better in ERP

**Comment by rohitwaghchaure** [comment]
Hi @graphskill 
Check below GIF
![calendar_view](https://user-images.githubusercontent.com/8780500/28366777-d40c21fc-6cab-11e7-98f1-6f819cac2d2a.gif)

**Comment by graphskill** [comment]
@rohitwaghchaure 

Thank you. That may be what we need. This only works though if you click on the calendar (or click and drag actually to define the dates). It does not work if we click the "NEW" button. That would be easier. Can it be made to work from the New button?

**Comment by somicoito** [comment]
@rohitwaghchaure I see there is no automatic timesheet creation on submit of your production order, how did you do this?

**Comment by netchampfaris** [comment]
@graphskill Production Order Calendar will show entries according to **Planned Start Date** and **Planned End Date**

**Comment by rohitwaghchaure** [comment]
@graphskill 

We have identified and fixed the issue, soon we'll release it
Thanks
