### ISSUE TITLE
Explore Icon Leads to Setup - Unable to get integration to backup to Dropbox

### ISSUE THREAD

**Issue by dsingal58** [frappe/erpnext#9476]
I am a newbie. Installed ERPNext on Amazon AWS using Bitnami. Exploring ERPnext. 
While trying to setup I am trying to set up backup and link to Dropbox. 
According to the instructions in the manual, I clicked on Explore. That then is bringing up the setup screen and I don't find the option to integrate into Dropbox. 
What am I missing?

Thanks

**Comment by yashodhank** [comment]
@dsingal58 You should contact bitnami or ask question about the same on bitnami support forum.
If you install Frappe/ERPNext using [bench installer](https://github.com/frappe/bench) and share version details then we might be able to assist you get it resolved. Make sure you seek help on forum https://discuss.erpnext.com/
Github issues is only used for reporting bugs, errors and requesting improvements with software.
