### ISSUE TITLE
No images displayed in images view for Suppliers and Contacts

### ISSUE THREAD

**Issue by basdereus84** [frappe/erpnext#9480]
If I select "Images" in the customer list, the attached image for every customer is displayed in the grid, if there hasn't been an image attached for a customer it will display the two initials instead. This feels like normal behavior.

If I select "Images" in the supplier or contact list I always get the initials no matter if an image has been attached or not. If I open the supplier or contact itself the image is displayed correctly, so it only occurs in the list. This feels like a bug. I would think that the behavior should be the same for customers, suppliers and contacts.

I noticed this problem in the V7.* and now in V8.1 it's still there. 

A while ago there was this pull request: https://github.com/frappe/erpnext/pull/8296 which solved the problem for the Customer list. I think the same fix should apply to Suppliers and contacts list.

**Comment by vishdha** [comment]
fixed for supplier  #9500
