### ISSUE TITLE
Posting Date should not fetch value from previous document

### ISSUE THREAD

**Issue by addymuliady** [frappe/erpnext#9491]
ERPNext: v8.1.3 (master)
Frappe Framework: v8.1.2 (master)

1. Create a Journal Entry
2. Select a Posting Date
3. Fill up mandatory detail
4. Save and take note of the Posting Date
5. Click module (For example, Journal Entry)
6. Click on New
7. The date will fetch the posting date of previous document.

**Comment by addymuliady** [comment]
![journal_entry](https://user-images.githubusercontent.com/21187126/27614369-bc5d8ebc-5bd3-11e7-840f-8a39f22537bd.gif)

**Comment by rohitwaghchaure** [comment]
Hi @addymuliady 

We have fixed this issue, can you please pull the latest update and check
