### ISSUE TITLE
Added contact_html field in Lead DocType,and done entry in Lead and created New Contact but shows “No contact added yet”

### ISSUE THREAD

**Issue by venku31** [frappe/erpnext#9505]
I Created new custom field contact_html in lead Doctype, and created new lead and in address & contact added new address and new contact
In Contact -new contact created, but in Lead it shows "No contact added yet"
Please help

Venkatesh
Mittal clothing, Bangalore
![lead](https://user-images.githubusercontent.com/29224707/27630752-f661002c-5c13-11e7-98f2-0d44711492f1.jpg)
![contact](https://user-images.githubusercontent.com/29224707/27630751-f659a6ba-5c13-11e7-893f-9afceffa0bdd.jpg)

**Comment by umairsy** [comment]
Please post your queries related to customization on the ERPnext community forum.

https://discuss.erpnext.com
