### ISSUE TITLE
Improvement to Bank Reconciliation

### ISSUE THREAD

**Issue by tundebabzy** [frappe/erpnext#9506]
- [ ] Add Bank Charges Account.
- [ ] Add Interest Paid Account.
- [ ] Add Exchange Rate field.
    - Display only if `Bank Account` currency is a foreign currency
- [ ] Add Revalue Currency checkbox.
    - If checked, automatically perform currency revaluation
- [ ] Add Realised Gain Account field.
    - Mandate that default Realised Gain account is set.
- [ ] Add Unrealised Gain Account field.
    - Mandate that default Unrealised Gain account is set.
- [ ] Add Realised Loss Account field.
    - Mandate that default Realised Loss account is set.
- [ ] Add Unrealised Loss Account field.
    - Mandate that default Unrealised Loss account is set.
- [ ] Add Currency Exchange Gain Account field.
    - Mandate that default Currency Exchange Gain account is set.
- [ ] Add Currency Exchange Loss Account field.
    - Mandate that default Currency Exchange Loss account is set.

The automatic currency revaluation would permanently fix issues like #7743 . It would also mean that all necessary adjustments regarding bank reconciliation can be done in one place.

**Comment by karannshah** [comment]
Is this something you have developed @tundebabzy ?
