### ISSUE TITLE
Can't set Start and End Dates in Salary Slip

### ISSUE THREAD

**Issue by theopen-institute** [frappe/erpnext#9513]
When creating new salary slips for any of my monthly employees, I am not able to set my desired Start and End Dates. No matter what I put, the Start and End dates automatically revert to the 16th and last days of whatever month I've selected (respectively).

My salary structure seems to be set correctly, and all of my employees have start dates before the current month. Something, however, is causing the dates to change as soon as I enter them.

**Comment by tundebabzy** [comment]
Hi @theopen-institute ,
Does your fiscal year start on the 16th?

**Comment by theopen-institute** [comment]
Thanks for taking this on @tundebabzy 

Good catch, yes it does. Is that the root of the problem? Even if I were to shift my payment cycle onto 16th to 15th, I'm still not able to change the end date to anything other than the last day of the month.

**Comment by tundebabzy** [comment]
@theopen-institute 
> Is that the root of the problem?

Yes. The behaviour is wrong though. The start date should be exactly the same as the start date on the salary structure. I can fix this today and hopefully into will make into into production in tomorrow's release.

**Comment by theopen-institute** [comment]
Thanks @tundebabzy

**Comment by tundebabzy** [comment]
Hello @theopen-institute 
Please follow progress on this issue on #9530 .
