### ISSUE TITLE
[Error Running Upgrade] AttributeError: 'SystemSettings' object has no attribute 'minimum_password_score'

### ISSUE THREAD

**Issue by vishwajeet** [frappe/erpnext#9517]
Hi I am facing this issue after running the command bench update --upgrade

Executing frappe.patches.v8_0.set_currency_field_precision	# 2017-05-09 in prod (f6c433acac2a27cc)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 91, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 17, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 24, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 216, in migrate
    migrate(context.verbose, rebuild_website=rebuild_website)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/migrate.py", line 31, in migrate
    frappe.modules.patch_handler.run_all()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 29, in run_all
    if not run_single(patchmodule = patch):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 63, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 83, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/patches/v8_0/set_currency_field_precision.py", line 22, in execute
    ss.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 230, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 263, in _save
    self.run_before_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 772, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 666, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 887, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 870, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 660, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/system_settings/system_settings.py", line 16, in validate
    minimum_password_score = cint(self.minimum_password_score) or 0
AttributeError: 'SystemSettings' object has no attribute 'minimum_password_score'

**Comment by rohitwaghchaure** [comment]
Hi @vishwajeet 

Can you please do following steps and run bench migrate

1. Run bench console from frappe-bench folder

1. doc =frappe.get_doc("System Settings")

1. doc. minimum_password_score = 2

1. doc.save()

**Comment by vishwajeet** [comment]
I got following error 

ProgrammingError                          Traceback (most recent call last)
/home/frappe/frappe-bench/apps/frappe/frappe/commands/utils.pyc in <module>()
----> 1 doc.save()

/home/frappe/frappe-bench/apps/frappe/frappe/model/document.pyc in save(self, *args, **kwargs)
    228         def save(self, *args, **kwargs):
    229                 """Wrapper for _save"""
--> 230                 return self._save(*args, **kwargs)
    231 
    232         def _save(self, ignore_permissions=None, ignore_version=None):

/home/frappe/frappe-bench/apps/frappe/frappe/model/document.pyc in _save(self, ignore_permissions, ignore_version)
    278 
    279                 self.update_children()
--> 280                 self.run_post_save_methods()
    281 
    282                 return self

/home/frappe/frappe-bench/apps/frappe/frappe/model/document.pyc in run_post_save_methods(self)
    788 		- `update_after_submit` for **Update after Submit**"""
    789                 if self._action=="save":
--> 790                         self.run_method("on_update")
    791                 elif self._action=="submit":
    792                         self.run_method("on_update")

/home/frappe/frappe-bench/apps/frappe/frappe/model/document.pyc in run_method(self, method, *args, **kwargs)
    664 
    665                 fn.__name__ = method.encode("utf-8")
--> 666                 out = Document.hook(fn)(self, *args, **kwargs)
    667 
    668                 self.run_email_alerts(method)

/home/frappe/frappe-bench/apps/frappe/frappe/model/document.pyc in composer(self, *args, **kwargs)
    885 
    886                         composed = compose(f, *hooks)
--> 887                         return composed(self, method, *args, **kwargs)
    888 
    889                 return composer

/home/frappe/frappe-bench/apps/frappe/frappe/model/document.pyc in runner(self, method, *args, **kwargs)
    868                 def compose(fn, *hooks):
    869                         def runner(self, method, *args, **kwargs):
--> 870                                 add_to_return_value(self, fn(self, *args, **kwargs))
    871                                 for f in hooks:
    872                                         add_to_return_value(self, f(self, method, *args, **kwargs))

/home/frappe/frappe-bench/apps/frappe/frappe/model/document.pyc in <lambda>(self, *args, **kwargs)
    658 
    659                 if hasattr(self, method) and hasattr(getattr(self, method), "__call__"):
--> 660                         fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
    661                 else:
    662                         # hack! to run hooks even if method does not exist

/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/system_settings/system_settings.py in on_update(self)
     29                 for df in self.meta.get("fields"):
     30                         if df.fieldtype not in no_value_fields:
---> 31                                 frappe.db.set_default(df.fieldname, self.get(df.fieldname))
     32 
     33                 if self.language:

/home/frappe/frappe-bench/apps/frappe/frappe/database.pyc in set_default(self, key, val, parent, parenttype)
    698         def set_default(self, key, val, parent="__default", parenttype=None):
    699                 """Sets a global / user default value."""
--> 700                 frappe.defaults.set_default(key, val, parent, parenttype)
    701 
    702         def add_default(self, key, val, parent="__default", parenttype=None):

/home/frappe/frappe-bench/apps/frappe/frappe/defaults.pyc in set_default(key, value, parent, parenttype)
    110         frappe.db.sql("""delete from `tabDefaultValue` where defkey=%s and parent=%s""", (key, parent))
    111         if value != None:
--> 112                 add_default(key, value, parent)
    113 
    114 def add_default(key, value, parent, parenttype=None):

/home/frappe/frappe-bench/apps/frappe/frappe/defaults.pyc in add_default(key, value, parent, parenttype)
    121                 "defvalue": value
    122 	})
--> 123         d.insert(ignore_permissions=True)
    124         _clear_cache(parent)
    125 

/home/frappe/frappe-bench/apps/frappe/frappe/model/document.pyc in insert(self, ignore_permissions, ignore_if_duplicate, ignore_mandatory)
    217                         self.copy_attachments_from_amended_from()
    218 
--> 219                 self.run_post_save_methods()
    220                 self.flags.in_insert = False
    221 

/home/frappe/frappe-bench/apps/frappe/frappe/model/document.pyc in run_post_save_methods(self)
    798                         self.run_method("on_update_after_submit")
    799 
--> 800                 self.run_method('on_change')
    801 
    802                 self.update_timeline_doc()

/home/frappe/frappe-bench/apps/frappe/frappe/model/document.pyc in run_method(self, method, *args, **kwargs)
    664 
    665                 fn.__name__ = method.encode("utf-8")
--> 666                 out = Document.hook(fn)(self, *args, **kwargs)
    667 
    668                 self.run_email_alerts(method)

/home/frappe/frappe-bench/apps/frappe/frappe/model/document.pyc in composer(self, *args, **kwargs)
    885 
    886                         composed = compose(f, *hooks)
--> 887                         return composed(self, method, *args, **kwargs)
    888 
    889                 return composer

/home/frappe/frappe-bench/apps/frappe/frappe/model/document.pyc in runner(self, method, *args, **kwargs)
    870                                 add_to_return_value(self, fn(self, *args, **kwargs))
    871                                 for f in hooks:
--> 872                                         add_to_return_value(self, f(self, method, *args, **kwargs))
    873 
    874                                 return self._return_value

/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/feedback_trigger/feedback_trigger.pyc in trigger_feedback_request(doc, method)
     40                 return triggers
     41 
---> 42         feedback_triggers = frappe.cache().get_value('feedback_triggers', _get)
     43         if doc.doctype in feedback_triggers:
     44                 if doc.flags.in_delete:

/home/frappe/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.pyc in get_value(self, key, generator, user, expires)
     70                         if not expires:
     71                                 if val is None and generator:
---> 72                                         val = generator()
     73                                         self.set_value(original_key, val, user=user)
     74 

/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/feedback_trigger/feedback_trigger.pyc in _get()
     35                 triggers = {}
     36                 if not (frappe.flags.in_migrate or frappe.flags.in_install):
---> 37                         for d in frappe.get_all('Feedback Trigger', dict(enabled=1), ['name', 'document_type']):
     38                                 triggers[d.document_type] = d.name
     39 

/home/frappe/frappe-bench/apps/frappe/frappe/__init__.pyc in get_all(doctype, *args, **kwargs)
   1145         if not "limit_page_length" in kwargs:
   1146                 kwargs["limit_page_length"] = 0
-> 1147         return get_list(doctype, *args, **kwargs)
   1148 
   1149 def get_value(*args, **kwargs):

/home/frappe/frappe-bench/apps/frappe/frappe/__init__.pyc in get_list(doctype, *args, **kwargs)
   1118 	"""
   1119         import frappe.model.db_query
-> 1120         return frappe.model.db_query.DatabaseQuery(doctype).execute(None, *args, **kwargs)
   1121 
   1122 def get_all(doctype, *args, **kwargs):

/home/frappe/frappe-bench/apps/frappe/frappe/model/db_query.pyc in execute(self, query, fields, filters, or_filters, docstatus, group_by, order_by, limit_start, limit_page_length, as_list, with_childnames, debug, ignore_permissions, user, with_comment_count, join, distinct, start, page_length, limit, ignore_ifnull, save_user_settings, save_user_settings_fields, update, add_total_row, user_settings)
     86                         result = self.run_custom_query(query)
     87                 else:
---> 88                         result = self.build_and_run()
     89 
     90                 if with_comment_count and not as_list and self.doctype:

/home/frappe/frappe-bench/apps/frappe/frappe/model/db_query.pyc in build_and_run(self)
     98 
     99         def build_and_run(self):
--> 100                 args = self.prepare_args()
    101                 args.limit = self.add_limit()
    102 

/home/frappe/frappe-bench/apps/frappe/frappe/model/db_query.pyc in prepare_args(self)
    115                 self.parse_args()
    116                 self.extract_tables()
--> 117                 self.set_optional_columns()
    118                 self.build_conditions()
    119 

/home/frappe/frappe-bench/apps/frappe/frappe/model/db_query.pyc in set_optional_columns(self)
    216         def set_optional_columns(self):
    217                 """Removes optional columns like `_user_tags`, `_comments` etc. if not in table"""
--> 218                 columns = frappe.db.get_table_columns(self.doctype)
    219 
    220                 # remove from fields

/home/frappe/frappe-bench/apps/frappe/frappe/database.pyc in get_table_columns(self, doctype)
    821         def get_table_columns(self, doctype):
    822                 """Returns list of column names from given doctype."""
--> 823                 return self.get_db_table_columns('tab' + doctype)
    824 
    825         def has_column(self, doctype, column):

/home/frappe/frappe-bench/apps/frappe/frappe/database.pyc in get_db_table_columns(self, table)
    817         def get_db_table_columns(self, table):
    818                 """Returns list of column names from given table."""
--> 819                 return [r[0] for r in self.sql("DESC `%s`" % table)]
    820 
    821         def get_table_columns(self, doctype):

/home/frappe/frappe-bench/apps/frappe/frappe/database.pyc in sql(self, query, values, as_dict, as_list, formatted, debug, ignore_ddl, as_utf8, auto_commit, update)
    151                                         frappe.log(">>>>")
    152 
--> 153                                 self._cursor.execute(query)
    154 
    155                 except Exception as e:

/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/cursors.pyc in execute(self, query, args)
    248         except Exception:
    249             exc, value = sys.exc_info()[:2]
--> 250             self.errorhandler(self, exc, value)
    251         self._executed = query
    252         if not self._defer_warnings:

/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/connections.pyc in defaulterrorhandler(***failed resolving arguments***)
     48     del connection
     49     if isinstance(errorvalue, BaseException):
---> 50         raise errorvalue
     51     if errorclass is not None:
     52         raise errorclass(errorvalue)

ProgrammingError: (1146, "Table 'f6c433acac2a27cc.tabFeedback Trigger' doesn't exist")

**Comment by rohitwaghchaure** [comment]
do bench console
frappe.reload_doc('core', 'doctype', 'feedback_trigger')
and then again do the above steps

**Comment by vishwajeet** [comment]
I launched a fresh instance and tried what you said but now I am getting new error. Not sure what's the issue.

--------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/home/frappe/frappe-bench/apps/frappe/frappe/commands/utils.pyc in <module>()
----> 1 doc.save()

/home/frappe/frappe-bench/apps/frappe/frappe/model/document.pyc in save(self, *args, **kwargs)
    228         def save(self, *args, **kwargs):
    229                 """Wrapper for _save"""
--> 230                 return self._save(*args, **kwargs)
    231 
    232         def _save(self, ignore_permissions=None, ignore_version=None):

/home/frappe/frappe-bench/apps/frappe/frappe/model/document.pyc in _save(self, ignore_permissions, ignore_version)
    261                 self.set_parent_in_children()
    262                 self.validate_higher_perm_levels()
--> 263                 self.run_before_save_methods()
    264 
    265                 if self._action != "cancel":

/home/frappe/frappe-bench/apps/frappe/frappe/model/document.pyc in run_before_save_methods(self)
    770 
    771                 if self._action=="save":
--> 772                         self.run_method("validate")
    773                         self.run_method("before_save")
    774                 elif self._action=="submit":

/home/frappe/frappe-bench/apps/frappe/frappe/model/document.pyc in run_method(self, method, *args, **kwargs)
    664 
    665                 fn.__name__ = method.encode("utf-8")
--> 666                 out = Document.hook(fn)(self, *args, **kwargs)
    667 
    668                 self.run_email_alerts(method)

/home/frappe/frappe-bench/apps/frappe/frappe/model/document.pyc in composer(self, *args, **kwargs)
    885 
    886                         composed = compose(f, *hooks)
--> 887                         return composed(self, method, *args, **kwargs)
    888 
    889                 return composer

/home/frappe/frappe-bench/apps/frappe/frappe/model/document.pyc in runner(self, method, *args, **kwargs)
    868                 def compose(fn, *hooks):
    869                         def runner(self, method, *args, **kwargs):
--> 870                                 add_to_return_value(self, fn(self, *args, **kwargs))
    871                                 for f in hooks:
    872                                         add_to_return_value(self, f(self, method, *args, **kwargs))

/home/frappe/frappe-bench/apps/frappe/frappe/model/document.pyc in <lambda>(self, *args, **kwargs)
    658 
    659                 if hasattr(self, method) and hasattr(getattr(self, method), "__call__"):
--> 660                         fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
    661                 else:
    662                         # hack! to run hooks even if method does not exist

/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/system_settings/system_settings.pyc in validate(self)
     13 class SystemSettings(Document):
     14         def validate(self):
---> 15                 enable_password_policy = cint(self.enable_password_policy) and True or False
     16                 minimum_password_score = cint(self.minimum_password_score) or 0
     17                 if enable_password_policy and minimum_password_score <= 0:

AttributeError: 'SystemSettings' object has no attribute 'enable_password_policy'

**Comment by vishwajeet** [comment]
after running bench migrate  now I don't see any error.

Can you let me know what's the proper process to do a upgrade from V7 to V8 ?

**Comment by vishwajeet** [comment]
Bench migrate works fine but running bench update --upgrade throws the same error 
AttributeError: 'SystemSettings' object has no attribute 'minimum_password_score'

If I try to run console commands as suggested now I am getting the error as mentioned in my previous comment AttributeError: 'SystemSettings' object has no attribute 'enable_password_policy'

Not sure what's the issue

**Comment by vishwajeet** [comment]
Can anyone update on this ? I am struggling to update to latest version to get changes related to GST

**Comment by vishwajeet** [comment]
Can anyone update on this issue ?

**Comment by vishwajeet** [comment]
I have managed to upgrade. You can close this issue.
