### ISSUE TITLE
Serial No. Issues for returned item

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#9520]
WN-SUP25991

We have Sales Return an item and issued new Delivery Note. When re-invoice Delivery Note we get attached message?

We never had this issue before. Why invoice is checking serial number once Delivery Note is already submitted and ok?

![screen shot 2017-06-29 at 11 32 49 am](https://user-images.githubusercontent.com/910238/27673784-281c39b8-5cc0-11e7-83fd-2de38c429f42.png)

**Comment by rohitwaghchaure** [comment]
Fixed via https://github.com/frappe/erpnext/pull/9593
