### ISSUE TITLE
GST - Issue in adding HSN Code manually

### ISSUE THREAD

**Issue by PawanMeh** [frappe/erpnext#9529]
ERPNext: v8.2.0 (master)
Frappe Framework: v8.2.0 (master)

1. Create HSN Code manually, you would notice the key generated shows up. This can be avoided and HSN Code can be shown or this can be removed.

![1- hsn code creation](https://user-images.githubusercontent.com/20460498/27686333-f64fdf0e-5cef-11e7-88bc-676004d9960d.png)

2. When you try to use the newly created SAC code, to associate it with an Item, the same key value shows up instead of the actual HSN/SAC Number

![2- associate item with hsn](https://user-images.githubusercontent.com/20460498/27686382-26653306-5cf0-11e7-974d-1519d5d349bc.png)

**Comment by SonaliBudhrani** [comment]
Hi, 
When will this fix be merged and released?
We need to enter HSN code and without this we can't proceed. We need only 4 digit codes. Please do it on urgent basis.
