### ISSUE TITLE
Can't set Start and End Dates in Salary Slip #9513

### ISSUE THREAD

**Issue by tundebabzy** [frappe/erpnext#9530]
Reference: #9513 
Presently, start date for salary slips and process payroll can only be set to the start of the period in the fiscal year. This problematic for companies that do not have their accounting period starting at the beginning of the month. For example, if accounting period runs from 16th - 15th, you can only create slips with pay period starting on the 16th and ending on the 30th.

I'm proposing we change this as follows:
- [x] Create a new Document - 'Payroll Cycle' which holds information about the company's payment cycle. It will be tied to `Designation`s.
- [x] Create a new Document - 'Payroll Period' to be set by the user. `Payroll Period` contains the start date, end date and name of the Payroll Period. It will be a child of `Payroll Cycle`.
- [x] Create a new Document - 'Payroll Cycle Designation' which is a link to 'Designation' and added as a child to 'Payroll Cycle'
- [x] Show status in list view (Is Active/Not Active)
- [ ] Add Payroll Cycle validation:
  - [ ] Frequency cannot be changed once saved
  - [ ] Number of Payroll Periods must be consistent with the frequency chosen. e.g if frequency is 'Monthly', there should be not more than one Payment Period per calendar month; there should be no more than 12 Payment Periods per fiscal year.
  - [ ] Dates must not overlap.
  - [ ] Gaps between dates not allowed.
  - [ ] Period dates cannot be set to dates to past periods e.g If today's date is 01-07-2017 and Payroll Cycle frequency is "Monthly", you cannot add period 01-06-2017 - 30-06-2017 to the cycle.
- [ ] Add 'Payroll Cycle' as a link field to `Process Payroll` and `Salary Slip`.
- [ ] Populate `start_date` and `end_date` from the selected `Payroll Cycle`.
- [ ] In salary slip validation, ensure that salary slip pay periods do not overlap.
- [ ] Remove `payment_frequency` field

**Comment by rmehta** [comment]
Maybe **Payroll Period** instead of **Payroll Frequency**

**Comment by tundebabzy** [comment]
> Maybe Payroll Period instead of Payroll Frequency

Yap. it's more explanatory. OP edited
