### ISSUE TITLE
Company screen freezes with error

### ISSUE THREAD

**Issue by PawanMeh** [frappe/erpnext#9531]
ERPNext: v8.2.0 (master)
Frappe Framework: v8.2.0 (master)
Browser Firefox: 54.0

1. Tried to open company master to update GST number & link address. Got the below error.

![screen shot 2017-06-29 at 5 44 52 pm](https://user-images.githubusercontent.com/20460498/27687043-e85e9c7a-5cf2-11e7-8ac1-e4662dded272.png)

**Comment by rohitwaghchaure** [comment]
Hi @PawanMeh 

Can you do bench build, bench clear-cache, reload and then check

**Comment by PawanMeh** [comment]
@rohitwaghchaure , this works, closing it for now.
