### ISSUE TITLE
Set billing hours to 0 in timesheet

### ISSUE THREAD

**Issue by christophKi** [frappe/erpnext#9535]
Hi guys!

I think there is a problem with the billing hours in the time sheet. Every time I uncheck the bill in an activity, it is still in the print view. 

It would not be a problem, but when i try to set the billing hours to 0, it sets it automatically to 1 after saving the time sheet. I can set it to everything different than 0. Also negative values but not null. 

I uploaded pictures to this description at:

https://discuss.erpnext.com/t/set-billing-hours-to-0-in-timesheet/25394

Best regards,

ChristophKi

**Comment by tundebabzy** [comment]
Hi @christophKi 
Just to be clear with the issue, ERPNext does not allow you to remove "not-to-be-billed" timesheets neither does it allow you change billable hours to 0?

**Comment by christophKi** [comment]
Hi @tundebabzy 

_does it allow you change billable hours to 0_ -> corrct, i can't set it to 0 (tested with firefox and chrome) 

_ERPNext does not allow you to remove "not-to-be-billed"_ -> no, i can uncheck the billing hours! but it's still in the print view. Please take a look at the pictures at [https://discuss.erpnext.com/t/set-billing-hours-to-0-in-timesheet/25394](https://discuss.erpnext.com/t/set-billing-hours-to-0-in-timesheet/25394) It shows you the sheet with unchecked billing hours in the second line and the print view which still shows the billing hours while billing amount and costing amount is 0 and billing hours is not. In the line above, I have checked "billing hours", so its OK to be shown in the print view. 

ERPNext version was 8.1.1 when i reported the bug.

**Comment by christophKi** [comment]
also set the billing hours to 0.5 is not possible!

**Comment by tundebabzy** [comment]
Yap. This should be a bug. If a user says billable hours is 0 then it must be 0.

**Comment by tundebabzy** [comment]
To fix this, I'm also going to reset the billing rate and costing rate fields to 0. That way, it is clear to anybody viewing the time sheet that the activity is not going to be billed.

**Comment by tundebabzy** [comment]
Fixed in #1013

**Comment by christophKi** [comment]
Thx, words now. 

Best regards, ChristophKi
