### ISSUE TITLE
[Opera] Customer/ Supplier form not loading

### ISSUE THREAD

**Issue by ishanloya** [frappe/erpnext#9539]
Unable to load customer/supplier form after update to 8.2.1 (master)

**Comment by sagarvora** [comment]
Hi, I am able to load customer/supplier forms just fine on my local instance.
Is there any console log?

**Comment by ishanloya** [comment]
Hey @sagarvora,

Here is the console log:
`Uncaught TypeError: Cannot read property 'render_address_and_contact' of undefined`

**Comment by ishanloya** [comment]
Seems to be an Opera browser issue. Loads fine in Chrome

**Comment by umairsy** [comment]
Please avoid using ERPNext from Opera browser as it has browser compatibility issues.
