### ISSUE TITLE
[Bug] New user unable to see selected modules

### ISSUE THREAD

**Issue by franzos** [frappe/erpnext#9543]
I've set-up a new user (User 2) with identical permissions as a previous user (User 1), created a number of patches ago. Unfortunately it looks like the permissions don't apply correctly, as this users can't see a majority of modules.

**Previous user**
<img width="1394" alt="screen shot 2017-06-29 at 9 45 54 pm" src="https://user-images.githubusercontent.com/2619225/27704881-b56125f0-5d14-11e7-8d1f-d91773490124.png">

**New user**
<img width="1392" alt="screen shot 2017-06-29 at 9 48 37 pm" src="https://user-images.githubusercontent.com/2619225/27704882-b5614e40-5d14-11e7-98ee-bdcf3cc533ff.png">

**Module access** (identical for both users)
<img width="941" alt="screen shot 2017-06-29 at 9 51 13 pm" src="https://user-images.githubusercontent.com/2619225/27704983-15827aa6-5d15-11e7-8ffa-f8fbfbc2699a.png">

Edit: I've deleted User 2, and duplicated User 1 to become User 2 (Copy). Everything works just fine now, even though the permissions are still identical. I suspect the permissions aren't set properly.

**Comment by umairsy** [comment]
Did you check modules setting in the Show / Hide module section? 

Setup > Permissions > Show / Hide modules

For further support on the technical queries, request posting it on the community forum. Closing this issue for now.

https://discuss.erpnext.com
