### ISSUE TITLE
GST - Company Address on Sales Invoice

### ISSUE THREAD

**Issue by PawanMeh** [frappe/erpnext#9545]
ERPNext: v8.2.0 (master)
Frappe Framework: v8.2.0 (master)

1. Link Address to Company
![gst_address_link](https://user-images.githubusercontent.com/20460498/27719253-b92aca42-5d6e-11e7-966a-86c77aa0152d.gif)

2. Create a Sales Invoice 
![sales invoice](https://user-images.githubusercontent.com/20460498/27719269-d5e11c40-5d6e-11e7-8dea-d49391c2efa7.png)
      a. Actual company address does not show up on "Standard" print format
      b. 'GST HSN Code' label can be changed to 'HSN/SAC Code' or anything more appropriate

**Comment by rijulmanch** [comment]
@rmehta is it possible to do this earlier as this is critical. I am not able to use ERPNext till this is resolved for GST.

**Comment by snvora** [comment]
I would like to add to this, GST invoicing rules require invoice to be marked as Original for Recipient, Duplicate for Transporter, and Triplicate for Supplier.

**Comment by agwldeepak** [comment]
Not working on the Hosted Instance... No company details are coming up in the Sales Invoice format....
