### ISSUE TITLE
Sorting the list view based on "Series" is not working.

### ISSUE THREAD

**Issue by Arundhatii** [frappe/erpnext#9551]
Reported via. https://frappe.erpnext.com/desk#Form/Issue/WN-SUP25901
Quotation screen

On the quotation screen if you select “Series” as the sort by field if sorts it ascending .  When you click on the arrow button to sort descending , nothing happens. 

Sales Invoice

Here the sort by series is only working for INV or CN-INV.  It is not sorting by number.  See the attched screedumps after and before the sort button
![screen shot 2017-06-25 at 18 54 26](https://user-images.githubusercontent.com/20164097/27731308-0473a664-5daa-11e7-825f-d342b72d94c9.jpg)

**Comment by rohitwaghchaure** [comment]
Hi @Arundhatii 

Not able to replicating in my local account
![series_issue](https://user-images.githubusercontent.com/8780500/27804894-fe4da2d8-604e-11e7-93dc-9906e073e6dd.gif)

**Comment by azharul-islam** [comment]
Issue still exists in the latest apps. 
ERPNext: v11.0.3-beta.34 () (staging)
Frappe Framework: v11.0.3-beta.48 () (staging)
 
![ezgif-5-84be23a61e46](https://user-images.githubusercontent.com/38819502/50849264-8c7c9b80-1387-11e9-9c33-601d3b208781.gif)
