### ISSUE TITLE
Account Receivable issue

### ISSUE THREAD

**Issue by conelco** [frappe/erpnext#9564]
Dear Support
Earlier we raised issue for Account receivable statement for Return Invoice in receivable statement,
ERP Support added the Column Debit note.
But that is not the professional in accounts book. 
please check the attachment i tried to explain hope it is clear if not pelase let me know
we gave statements to our clients and they get confused, that is the reason we are requesting you to solve this [accordingly. 

![receivable issue](https://user-images.githubusercontent.com/16674080/27760863-4cc83974-5e5a-11e7-9225-255709814c5b.png)

**Comment by adityaduggal** [comment]
@conelco AR is basically a SUMMARY of the invoices pending for getting the detailed statement you can also use the G/L statement which would show the transaction number of all the transactions as well.

**Comment by conelco** [comment]
Dear Aditya
Normal practice is to submit   Account Receivable / balance Receivable statement to customer weekly.
We cannot give them G/L

**Comment by conelco** [comment]
Dear Support

Any update on the above issue for Account Receivable Statement?

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.
