### ISSUE TITLE
same GSTIN [ 22AEEPV0898A121] generated for all sales invoice . 

### ISSUE THREAD

**Issue by shanmuganathans** [frappe/erpnext#9565]
hi, 

   if i create a sales invoice GSTIN automatically generated but here same GSTIN [22AEEPV0898A121
] was generated for created sales invoices.
https://github.com/frappe/erpnext/commit/ea92682cfdc79ccd66d15c386d71eb3ea351a5ac 
in this commit .having some fix but it not working

**Comment by adityaduggal** [comment]
Can you explain the issue this does not seem to be an issue with Sales Invoices.

**Comment by Zlash65** [comment]
Closing this issue for now as no proper explanation is provided and has been quite a while since last post. Please open it if its still an issue.
