### ISSUE TITLE
Item wise rate format for GST Invoice

### ISSUE THREAD

**Issue by LifeP** [frappe/erpnext#9566]
This is turning to be one of the most demanded features for GST on the forums.

Mandatory or not, Dealing with government authorities is a pain in India.
Having everything in black and white will not leave them scope for harassment.

**Comment by rajagopalx** [comment]
👍

**Comment by maheshengg** [comment]
👍

**Comment by nabinhait** [comment]
![1](https://user-images.githubusercontent.com/836784/27785778-463ab476-5ffc-11e7-896f-2d3f56d8620d.png)

**Comment by nabinhait** [comment]
**Invoice format in Tally:**
![sample-of-a-tax-invoice-under-gst_new](https://user-images.githubusercontent.com/836784/27788222-55eac470-6005-11e7-832b-760050d273dd.jpg)

**Comment by felixvarghese** [comment]
Tally has somewhat simplified its invoice
![tally_local_sales_printout](https://user-images.githubusercontent.com/3396162/27788498-75dbf1fe-6006-11e7-93fb-78c814b1b233.gif)

**Comment by rajagopalx** [comment]
Is there any update on this ?

**Comment by nabinhait** [comment]
@rajagopalx Sent a PR for this, will be released tomorrow.

**Comment by maheshengg** [comment]
Tax Table with HSN seems to be the only thing pending. For the rest of the things, I think we are ready with the GST Invoice print format..

![image](https://user-images.githubusercontent.com/1590079/28198630-2eddae9e-687d-11e7-8016-36f60cad34f1.png)

**Comment by nabinhait** [comment]
@maheshengg Already made the changes, will be release on next week.
