### ISSUE TITLE
Can't see BOM

### ISSUE THREAD

**Issue by Ganinakris** [frappe/erpnext#9570]
Hi, i've created some BOM a few days ago and today when i go to Manufacturing i can't see Bill of Materials anymore....
![screen shot 2017-07-02 at 12 36 09 pm](https://user-images.githubusercontent.com/29830158/27767485-0e7afe30-5f23-11e7-8085-8e652091ff26.png)

**Comment by umairsy** [comment]
Please check Permission Manager to know which Roles has permission on BOM. Ensure one of that role is assigned to your User master. 

Request to post such queries on the ERPNext community forum for faster response.

https://discuss.erpnext.com

**Comment by adam-je** [comment]
Check to see if manufacturing user/manager are not disabled in your roles

**Comment by agusputra** [comment]
Might be helpfull, ensure related roles (Manufacturing User and Manufactoring Manager) enabled on ERPNext. You can see the roles here: /desk#List/Role/List or search `Role List` on search box.
