### ISSUE TITLE
[GST] Incorrect Address being used to get GSTIN

### ISSUE THREAD

**Issue by sagarvora** [frappe/erpnext#9571]
In sales invoice, Customer GSTIN should be fetched from billing address, not shipping address. This is important in the case of drop ship where item is directly being shipped to third party but is to be billed to customer.

Custom field needs to be updated accordingly.

**Comment by felixvarghese** [comment]
This is true, but in non-dropship workflows (only two parties involved), Shipping address would be used. If the above change is made as-is, this would be incorrect.

**Comment by nabinhait** [comment]
Added E-Commerce GSTIN in GST Details section via #10405. If it does not solve the purpose, please add a custom field to manage this. Closing this issue.
