### ISSUE TITLE
[GST] Tax Rate in register

### ISSUE THREAD

**Issue by snvora** [frappe/erpnext#9572]
We plan to maintain only one account for CGST, SGST and IGST. A column in register gets populated only if its a different account.

In this scenario it would become difficult to identify what Tax Rate has been applied on Item / Invoice. Capturing Tax rate in register would make things better. 

(For both Purchase and Sales Register)

**Comment by rohitwaghchaure** [comment]
Add rows for rate in GST item-wise sales/purchase register

**Comment by nabinhait** [comment]
Add a filter for company GSTIN, in all GST reports

**Comment by snvora** [comment]
Month filter in report - which automatically chooses start date and end date will also be useful.

**Comment by addymuliady** [comment]
Can this report be available for all with the following:

- Monthly View
- Total for Item Value and Tax Value

**Comment by nabinhait** [comment]
Fixed via #10439, pending to release
