### ISSUE TITLE
Keyboard Shortcuts not working

### ISSUE THREAD

**Issue by snvora** [frappe/erpnext#9580]
I am using ERPNext v8.2.3

Since last few days I am experiencing following shortcuts are not working.

Ctrl+Down and Ctrl+Up (as shown in screenshot below)

<img width="912" alt="capture" src="https://user-images.githubusercontent.com/10496564/27782042-69671b32-5fee-11e7-8541-0be47e2eeed7.PNG">

Also, we used arrow keys to navigate in table, but now it's not working. Eg. Moving down in following screenshot.

<img width="880" alt="capture1" src="https://user-images.githubusercontent.com/10496564/27782098-ae10850c-5fee-11e7-9292-b80acab92de1.PNG">

**Comment by tundebabzy** [comment]
Hello @snvora ,
What browser are you using?

**Comment by snvora** [comment]
I use Google Chrome Version 59.0.3071.115 (Official Build) (64-bit)

**Comment by tundebabzy** [comment]
Hello @snvora 
The issue with navigating the grid with CTRL + DOWN/ CTRL + UP will soon be merged. However, ERPNext never had inbuilt table row navigation with the arrow keys. What we have is with the TAB key.

If you'll like to have arrow key navigation, please create a new issue for it. 

Meanwhile, you can track progress on the other fix here: frappe/frappe#3605

**Comment by snvora** [comment]
Sure.. Thanks...😃
