### ISSUE TITLE
GST HSN Code in Sales Order Item

### ISSUE THREAD

**Issue by manivk** [frappe/erpnext#9582]
The HSN code for item does not show in sales order. Since our tax rates are based on the item HSN Code and we have more than 2000 items falling in 6-8 HSN codes, we need to see the HSN code in the sales order item too. Currently, it shows only in the sales invoice item.

**Comment by nabinhait** [comment]
Applicable to Purchase Order too

**Comment by nagarajannxweb** [comment]
Needed in delivery note and purchase receipt
