### ISSUE TITLE
Ability to lock months for Accounts

### ISSUE THREAD

**Issue by manivk** [frappe/erpnext#9583]
Hi

We need the provision to lock months in Accounts so that once locked, no new entries can be posted in those months. Currently only period closing vouchers are available which is only for end of fiscal year. Need to be able to lock months in ERP so that once GST returns are filed, no changes are made to the entries.

Thanks
Mani.

**Comment by felixvarghese** [comment]
Go to "Accounts Settings" and set "Frozen Up To"

**Comment by yashodhank** [comment]
@manivk I hope above reply answers your question. Closing now. Feel free to reopen if looking for something different.

**Comment by heyberting** [comment]
This freezes all accounts in the CoA. What if I only want to freeze a certain "101-Account" up to last week and "102-Account" up to last month?
