### ISSUE TITLE
Jinja tags not working in Sales Invoice Email Notification

### ISSUE THREAD

**Issue by conkreet** [frappe/erpnext#9584]
Jinja tags in the Sales Invoice Email Notification (under Setup > Email Notifications > Sales Invoice) are not being replaced bij document values.

I use tags like {{ doc.due_date }} and {{ doc.grand_total }}, but they are not being replaced. In the email is just see {{ doc.due_date }} and {{ doc.grand_total }}.

**Comment by vishdha** [comment]
please provide screen short so that I can check what modification you have done on it.

**Comment by conkreet** [comment]
Screenshot is in Dutch, but I think you'll see what I mean.

<img width="1158" alt="schermafbeelding 2017-07-03 om 14 36 25" src="https://user-images.githubusercontent.com/6490153/27793136-0ec799cc-5ffd-11e7-921e-78b9354b6523.png">

**Comment by umairsy** [comment]
Just enter {{ field_name }}, no need to add "doc."
