### ISSUE TITLE
Automatically sent weekly digests are not translated

### ISSUE THREAD

**Issue by chdecultot** [frappe/erpnext#9587]
Hi everyone,

There is an issue with automatically sent weekly digests: they are not translated in the language of the system.

If I have a system in language FR and send a weekly digest, it will be sent in English, even if it appears in French in the preview.

Example:
![image](https://user-images.githubusercontent.com/4903591/27789649-a607e1c6-5fed-11e7-837c-3d8b34d71c79.png)

Email:
![image](https://user-images.githubusercontent.com/4903591/27790526-1921c304-5ff1-11e7-90e3-b556350f7456.png)

**Comment by rmehta** [comment]
https://github.com/frappe/erpnext/issues/10497
