### ISSUE TITLE
Activity Screen Frozen  

### ISSUE THREAD

**Issue by maxfu9** [frappe/erpnext#9588]
Keep Loading
![screen shot 2017-07-03 at 10 05 06 pm](https://user-images.githubusercontent.com/29174889/27792181-dc743e46-603b-11e7-889a-383990fb4aca.png)

**Comment by rohitwaghchaure** [comment]
Hi @maxfu9 

Thanks for reporting an issue,
We have identified and [fixed](https://github.com/frappe/frappe/pull/3601) the issue, soon we'll release the fix
