### ISSUE TITLE
Series, Item Code and Variant of doctype Item are not visible

### ISSUE THREAD

**Issue by ayushxx7** [frappe/erpnext#9590]
After updating to latest version 
[
ERPNext: v8.2.3 (master)

Frappe Framework: v8.2.4 (master)
}

I am having issue with some fields, which are mandatory but are not visible in both small as well as full page view. I have tested on multiple devices and tried re installing the whole package, but nothing works.

Thanks!
![](https://discuss.erpnext.com/uploads/default/original/2X/1/109360e3c089233a10bb5f4f763124625e6f6369.png)

**Comment by tundebabzy** [comment]
hello @ayushxx7 
please specify the fields

**Comment by ayushxx7** [comment]
Field Names:
1. Series
2. Item Code
3. Variant of

On Jul 4, 2017 19:30, "tundebabzy" <notifications@github.com> wrote:

hello @ayushxx7 <https://github.com/ayushxx7>
please specify the fields

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/frappe/erpnext/issues/9590#issuecomment-312885566>, or mute
the thread

**Comment by umairsy** [comment]
Is this issue still prevailing in your account? It is working just fine for other hosted and self-hosted users. Also check if its related to customization in your account.
