### ISSUE TITLE
Update Item images using Data Import Tool

### ISSUE THREAD

**Issue by SaurabhGupta329** [frappe/erpnext#9594]
Link images with items using data import tools is not happening, that this feature not available in ERPNext. We have to upload an image for each item manually, Pls provide a solution.

**Comment by manassolanki** [comment]
hi @SaurabhGupta329 , I have tried replicating this and it's working fine in my local account. Could you please let us know the Frappé and ERPNext version.

**Comment by manassolanki** [comment]
Working fine, please reopen if the issue persists.

**Comment by SaurabhGupta329** [comment]
This is not working till now, can you pls explain what exactly you did.
I am still not able to import pictures using data import tool for items.

**Comment by tundebabzy** [comment]
Hi @SaurabhGupta329 
Let's troubleshoot this on the forum

**Comment by manassolanki** [comment]
How are you trying to upload the images? Please upload your image somewhere on the web and provide the link in the data import tool or you can bulk import the image in the ERPNext and can provide the file path in the data import tool

**Comment by djpalshikar** [comment]
I faced the same issue with  ErpNext v8.10.0 and Frappe Framework: v8.9.0. I have uploaded the images using File upload tool in ERPNext, all the files were uploaded to a new folder "item_images". Then using the data import tool the items were updated with links to the images of the form "/files/fileName.svg".
After successful import the images were appeared as attachments but not as the item image.

**Comment by federojoavellaneda** [comment]
Hi, I think I have the same problem. But this functionality was working a few months ago.

From the product image, if you upload an image from a link, it works. But if that link is added in the correct field on XLS to import it does not work.

**Comment by asclar** [comment]
Hi, we need this feature. We have posted a job, please refer [here](https://erpnext.org/erpnext-jobs/update-item-images-using-data-import-tool) incase anyone is interested. Thanks.

**Comment by manassolanki** [comment]
Hi @federojoavellaneda , @asclar 
Due to recent changes the image field isn't being included in the data import tool template. We will fix this. In the meantime, if you import changing the highlighted field "website_image" to "image" , the provided link will be attached as in image in the item. 
![image](https://user-images.githubusercontent.com/20757311/32589761-6386b8b8-c53c-11e7-94a6-ed182694e442.png)

If you are expecting something more, please comment your ideas.

**Comment by asclar** [comment]
Hi @manassolanki, yes we understood that the current function will import the image as an attachment. What we need is importing the image as an item image, the main thumbnail of the item not as an attachment. Am I missing something? Thanks.

**Comment by manassolanki** [comment]
Yes, the solution I provided is the main image only. Please check the attached gif
https://imgur.com/a/jEqlf

**Comment by SaurabhGupta329** [comment]
Manas, 
We followed the same steps as shown in the video with image links of dropbox, photbucket & even from local computer, All of them failed to upload the image as attachment as shown in the video?
Can you pls share more details on the upload process or troubleshoot where we are wrong. Regards...Saurabh Gupta'9871754499'http://www.Marcloire.com 

    On Thursday, 9 November 2017 12:22 PM, Manas Solanki <notifications@github.com> wrote:
 

 Yes, the solution I provided is the main image only. Please check the attached gif
https://imgur.com/a/jEqlf—

**Comment by asclar** [comment]
@manassolanki that's exactly what we need, awesome. So we have to change the column header manually then. Can you please share the frappe/erpnext version you're using? Thanks a lot!

**Comment by spacehaven** [comment]
@SaurabhGupta329 is there anything in the error logs? Does image/attachment upload by URL through the GUI normally work? If it's not working through the GUI either, it might mean a networking issue (outbound firewall, dns resolver, proxy server, invalid https cert, routing issue).

**Comment by manassolanki** [comment]
Working fine.

**Comment by debrunner** [comment]
> Hi @federojoavellaneda , @asclar Due to recent changes the image field isn't being included in the data import tool template. We will fix this. In the meantime, if you import changing the highlighted field "website_image" to "image" , the provided link will be attached as in image in the item. ![image](https://user-images.githubusercontent.com/20757311/32589761-6386b8b8-c53c-11e7-94a6-ed182694e442.png)
> 
> If you are expecting something more, please comment your ideas.

version-13 gives me the same/similar problem: 

Update Website Item images using Data Import Tool
(got only an Attachment .jpg but no preview/thumbnail image in Webshop/Website Item)
https://imgur.com/a/jEqlf seams to be for version-12 and older where Item/Website DocType is not separated like in version-13, put problem/solution shown at video end looks very similar...

Google showed me this bug report as his best guess, hopefully somebody has a solution/hint for version-13?
