### ISSUE TITLE
Wrong Exchange Rate when making payment against Journal Entry

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#9595]
Hi,

When making a Journal Entry or Payment Entry against a Journal Entry, the Exchange Rate is not pulled. This is a significant issue especially for Payment Entries where the Exchange Rate is automatically set as '1' and is not editable. Steps to replicate:

Let's assume base currency is USD
1. Create a new Journal Entry and add a row for a Foreign Supplier with different billing currency (e,g, EUR)
2. Select corresponding payable account in supplier currency and put any figure in the Credit field
3. Set an Exchange Rate that's different from the current rate
4. Add rows needed to balance the Journal and Submit
5. Open a new Payment Entry or Journal Entry and select the supplier in step 1 above

Issue:
In the Payment Entry, the Journal Entry created in step 1 above shows up in 'Allocate Payment Amount' table but the Exchange Rate is 1! It doesn't pull the exchange rate specified in step 3 above and it's not editable (i.e Read Only)

In the case of a Journal Entry, the Exchange Rate is the current rate (as specified in Currency Exchange list) and not the rate specified in step 3 above

The correct Exchange Rate in both cases should be the rate specified in step 3 above. Please help fix this

Thanks

**Comment by tundebabzy** [comment]
Hello @Olawale1 
Thanks for reporting this. The behaviour you described is not wrong (except perhaps I'm missing something). 

Lets say the company currency is say 'USD' and you make a journal entry for a supplier whose billing currency is 'EUR' using a payables account denominated in 'EUR' and everything goes on fine. When you open a new payment entry for the supplier, the `Payment References` will not show as long as the payables account and the bank currency is not 'EUR'. If the bank currency is in 'EUR', the payables account is in 'EUR' and the journal entry is in 'EUR', then there's no exchange rate to deal with in this situation.

**Comment by Olawale1** [comment]
Hi @tundebabzy 

Thanks for your feedback. The Exchange Rate is important in this situation because that is what is used to calculate value in local currency. Because of this issue, the `Total Allocated Amount (USD)` and `Difference Amount (USD)` fields are showing wrong values! Of course I'm assuming USD as company currency using the preceding examples

It's important that the Payment Documents (Payment Entry / Journal Entry) always pull the exchange rate from the reference document. Currently they do that with Invoices but not with Journals and it needs to be fixed. Do let me know if you need further clarification

Kind regards,

**Comment by tundebabzy** [comment]
Oh ok. Understood

**Comment by tundebabzy** [comment]
@Olawale1
Fix has been merged. Should be available in the next release or so

**Comment by Olawale1** [comment]
Hi @tundebabzy 

It's been released! Thanks a great deal... You're the man!

Kind regards,
