### ISSUE TITLE
How to made a tax that is calculated on benefit at sell

### ISSUE THREAD

**Issue by meigallodixital** [frappe/erpnext#9597]
From this conversation: [https://discuss.erpnext.com/t/how-complex-could-be-change-tax-module-to-calculate-tax-amount-from-profit-not-from-net-ammount /25030](https://discuss.erpnext.com/t/how-complex-could-be-change-tax-module-to-calculate-tax-amount-from-profit-not-from-net-ammount/25030)

In Spain (I do not know if in other countries are calculated in same way) the amount of tax on used products is calculated on the time of sale on the benefit. (The purchase is zero taxed  because it is considered that these taxes are paid when the product is purchased the first time as new by the original owner)

A simple sample: buy on 100, sell on 221, tax 21%
**net base exent tax:** 100 (buy)
**net base with tax**: 100 (benefit)
tax amount: 21 (21% * net base with tax)
100 + 100 + 21

Any way to do this without break standard workflow of taxes in erpnext?

**Comment by umairsy** [comment]
Not configurable using standard ERPNext features. For now, you can calcuate tax amount separately and enter tax account based on Actual in sales tax and charges table.

**Comment by umairsy** [comment]
Hello,

Hope you will understand that this isuse is open for sometime now, but no other user has request for this feature. Perhaps you should get it customized in your ERPNext account by one of our Service Provider.

You can also post a job on the community portal and invite bids from the service providers.

https://erpnext.org/erpnext-jobs
