### ISSUE TITLE
Quotation throughs error on Cancel 

### ISSUE THREAD

**Issue by kickapoo** [frappe/erpnext#9605]
![screenshot 2017-07-04 10 05 27](https://user-images.githubusercontent.com/5064612/27818989-d5b9e56e-60a0-11e7-8059-cea4025a76ec.png)

Also:

Debug dont work, example step:
1.  Find the function on : apps/frappe/frappe/public/js/legacy/form.js
2. Make an edit (simple on like console log)
3. bench migrate (dont work)
4. bench build (dont work)
5. restart dev server (dont work)
The above include clear cache both from UI and bench commands.

**Comment by rmehta** [comment]
thanks for reporting. fixed
