### ISSUE TITLE
OKR for July 2017

### ISSUE THREAD

**Issue by tundebabzy** [frappe/erpnext#9615]
- [ ] Implement `Payroll Cycle` for a more flexible payroll runs and to fix #9513 . Ongoing discussion at https://discuss.erpnext.com/t/proposal-for-hr-payroll/25541
- [ ] Fix issues labelled as bugs in July 2017 milestone with emphasis on the more critical ones. Target is minimum of 1 per day
- [ ] Label new issues
- [ ] Answer questions on the discuss forum

cc:
@nabinhait 
@rmehta

**Comment by rmehta** [comment]
Lets not add these as issues, just add them to the July-2017 milestone!
