### ISSUE TITLE
Remove HTML markup from Exported file

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#9625]
When we export a report, then the CSV or Excel both have the HTML code in the exported file which becomes very tedious to read. Please remove the HTML code from the exported file format.

**Comment by manassolanki** [comment]
Could you please mention any specific reports because HTML is handled in Excel reports

**Comment by manassolanki** [comment]
@umairsy

**Comment by umairsy** [comment]
HTML markups were includes in the report builder report, as well as export taken from Data Import/Export tool.
