### ISSUE TITLE
Option to Change Sale Tax Template

### ISSUE THREAD

**Issue by sumitkarora** [frappe/erpnext#9626]
There must be option to Change Sale Tax Template

Because of Recent Update of GST, Invoice tax areas need to change. As per Norms, Total, Other Charges and Taxes area need to shown as below:
1. Item Total
2. Discount (If on Item Total)
3. Net Total (Item Total- Discount) 
4. Other Charges
5. Total {Taxable Amount (Net Total + Other Charges)}
6. Taxes (GST)
7. Grand Total
8. Rounded Total

As per current system, Sale Tax table shows charges detail as below:
1. Discount (If on Item Total)
2. Charges Detail (In same order as mention in Template, no matter it is other charges or Tax)

Now, If I want to add Net total (Taxable Amount) just before Taxes, that option is not available

**Comment by nabinhait** [comment]
Fixed in the latest version. HSN code based tax breakup is show in a separate table, to print GST compliant tax invoice.
