### ISSUE TITLE
Error after Website Theme Customization

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#9627]
In the hosted account, user adds a Custom Website Theme. But due to some issues, it leads to errors on login and user is not able to correct it himself. We have to remove value causing problem from backend, so that use can login again.

![screen shot 2017-07-05 at 1 49 42 pm](https://user-images.githubusercontent.com/910238/27855675-fcf117c2-6188-11e7-8739-e2d7a095bb3f.png)

**Comment by saurabh6790** [comment]
Need to validate with custom theme!
