### ISSUE TITLE
Add SAC / HSN (4 digits)

### ISSUE THREAD

**Issue by PrakashH** [frappe/erpnext#9633]
Add Service Accounting Codes to fetch automatically under HSN/SAC Code field of Item Master.

**Comment by umairsy** [comment]
Please add SAC codes as applicable. If you have list of SAC codes to be added, please share here. closing for now.

**Comment by umairsy** [comment]
HSN code field renamed to HSN/SAC No.

**Comment by PrakashH** [comment]
[SAC Codes for GST.xlsx](https://github.com/frappe/erpnext/files/1124323/SAC.Codes.for.GST.xlsx)

**Comment by umairsy** [comment]
Related https://github.com/frappe/erpnext/issues/9696

**Comment by maheshengg** [comment]
Four Digit HSN code is a part of an entire HSN code, system should accept. else there will duplication of HSN codes
