### ISSUE TITLE
Restriction in Master but needs viewing in Link Field

### ISSUE THREAD

**Issue by creamdory** [frappe/erpnext#9634]
We have this usecase wherein we need to restrict users to only view their records in Employee doctype. But there are couple of users which needs access to whole data in an employee link field in a custom doctype. How to go over this?

**Comment by umairsy** [comment]
Identify two roles, one for Employee with Owner restriction, and another for complete access.

For the Role which will only have access to their own records, check Role Permissions as following.

https://frappe.github.io/erpnext/user/manual/en/customize-erpnext/articles/user-restriction

For the other Role (say HR Manager), no permission restriction will be applied, hence all the data will be accessible.

Functional queries on https://discuss.erpnext.com please.
