### ISSUE TITLE
Serial N° Batch Selector not working with "X XXX" number format

### ISSUE THREAD

**Issue by chdecultot** [frappe/erpnext#9637]
Hi,

The new batch N° selector is great, but unfortunately not working correctly when the number format is "X XXX":

![image](https://user-images.githubusercontent.com/4903591/27859539-5f0f0bea-6179-11e7-8f3b-673bb9fd618f.png)

This is due to the javascript parseFloat() function: in this example it transforms "3 349" into "3" and finds out "52" > "3" (52 is the qty to be transferred)

![image](https://user-images.githubusercontent.com/4903591/27859208-47d2eef2-6178-11e7-8973-646bc4d084f9.png)

**Comment by umairsy** [comment]
Issue replicating in the test account. @rohitwaghchaure please assign.

**Comment by pratu16x7** [comment]
No longer seems to be replicating in test account:
![screen shot 2017-07-16 at 9 59 31 pm](https://user-images.githubusercontent.com/5196925/28249379-436fc88c-6a72-11e7-83e9-46465409ca10.png)

**Comment by pratu16x7** [comment]
@chdecultot Any update if it still persists?

**Comment by chdecultot** [comment]
Hi @pratu16x7,

Sorry didn't see your previous message.

I just re-tested it and it seems to have been fixed.

Thanks a lot!! :+1:
