### ISSUE TITLE
Email Standard Reply not getting loaded

### ISSUE THREAD

**Issue by snvora** [frappe/erpnext#9638]
ERPNext: v8.2.3 (master)
Chrome Version 59.0.3071.115 (Official Build) (64-bit)

<img width="772" alt="capture" src="https://user-images.githubusercontent.com/10496564/27859956-301cac60-6198-11e7-90b3-721f581a50c7.PNG">

**Comment by umairsy** [comment]
closed via https://github.com/frappe/erpnext/issues/9552
