### ISSUE TITLE
Setup Wizard Styling Issues

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#9640]
- [x] Use standard primary buttons
- [x] Fix alignment for item pic
- [x] Fix "we sell this item 1"
- [x] Remove italics from "will be your login id" -- brackets is good enough separation.
- [x] Rename "bootstrap"
- [x] Enforce at least 1 customer, 1 supplier and 1 item
---

<img width="551" alt="screen shot 2017-07-05 at 4 32 29 pm" src="https://user-images.githubusercontent.com/140076/27861841-2375514e-61a0-11e7-856d-e6810266a9fb.png">

**Comment by nabinhait** [comment]
In many slides, input/action area is going below the visible area of the browser in Mac. 

<img width="1280" alt="screen shot 2017-07-05 at 6 19 41 pm" src="https://user-images.githubusercontent.com/836784/27865010-886b8a24-61ae-11e7-8b29-bc0a89a91d0e.png">

**Comment by pratu16x7** [comment]
fixed by: frappe/frappe#3647
