### ISSUE TITLE
Batch modal should appear if item has qty in multiple batches

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#9643]
Currently, modal for Batches selection only appear if the value is not auto-fetched. It should also appear if item has multiple batches with stock in it, even if there is value to be auto-fetched.

**Comment by umairsy** [comment]
Also suggesting to provide trigger in the child form to re-open modal for batch/serial no. manually.

**Comment by oschauf** [comment]
I agree.  Also, the two features batch-autoselect and batch-select-modal do not work well together.

Currently the modal pops up **only** when a Default Warehouse for the Item is **not set**. Also, it pops up **right after** entering the Item Code, and **before** the user can change the Quantity. 

In case a Default Warehouse for an Item is set, then the batch-autoselect-feature will select a batch, and modal does not pop-up at all. Again, the  batch-autoselect-feature will run right after the user entered the Item Code and **before** Quantity is entered.  Thus, it selects the 1st Batch with more than 1 UOM (default Quantity) in stock (irrespective of the Expiry Date). If the afterwards entered Quantity exceeds stock, ERPnext will throw an error message on Submit (Selected Batch has not sufficient Quantity). 

The modal never pops up in case of Bundled Products (if one of the Packed Items has Batches). 

I think both features have some logic errors, and also don't work well together.

The batch-autoselect-feature should run every time if any of the relevant fields is updated (Item, Source Warehouse, Quantity). Also, it should try to select only from the Batch(es) closest to Expiry Date (if no Batches of an Item have Expiry Dates, it can select from any Batch).

If the batch-autoselect-feature is unable to select a matching batch, the modal should pop-up.  It should also pop-up when manually selecting batches (user selecting the batch field).

**Comment by tundebabzy** [comment]
@umairsy @oschauf 
I have done some work concerning this and I want to say some of my thoughts.

Documents in the sales cycle will now auto-fetch batch numbers using FEFO (First Expiring First Out) which is a variation of FIFO. The only difference is the soonest to expire is given highest priority.

Also, if warehouse (implemented in #11790), qty, item (implemented in #11454 ), the batch_no field will be updated.

While using the POS, the batch selector is displayed, the batch number is auto fetched (with FEFO) and the user only needs to input the quantity (#11767). If the quantity or batch number needs to be edited, the batch selector shows with all the information pre-populated.

Practically all the concerns raised here (See #11794) have been fixed so I'm closing this.
