### ISSUE TITLE
Clicking on Related Documents sometimes doesn't proceed to the correct linked documents

### ISSUE THREAD

**Issue by hdtmartin** [frappe/erpnext#9648]
We have had several instances where a particular Sales Order is open and clicking on the Related Delivery Notes or Related Material Request or Related Purchase Order will redirect into an incorrect document.

E.g. When SO-00692 is openned and clicking on the Related Document Material Request, the link opens into a new window with incorrect document, i.e. Material Request MREQ-00610 is shown but this is related to SO-00687 not SO-00692. The correct Material Document for SO-00692 is MREQ-00613 so this should be the one shown.

Kindly check. This is functioning well not until days ago when the change in Filter Selection was noticed. This error is really confusing the users since they are directed to a wrong related document instead of the correct one.

**Comment by adityaduggal** [comment]
Please confirm the version of frappe and erpnext being used.

**Comment by hdtmartin** [comment]
We are using the current cloud version. Our domain is vvt.erpnext.com. Thanks

**Comment by adityaduggal** [comment]
Can you add a Working GIF for clarity on this issue, does the new filters are not reset with the new ones.

**Comment by hdtmartin** [comment]
Looks like. Not all the time. Sometimes, it worked. Sometimes, not.

**Comment by hdtmartin** [comment]
Can't seem to find a case for SO right now since the issue is intermittent. But here is a similar issue with PO.

From PO-00600, when clicking the Related Documents Purchase Receipt:
![capture1](https://user-images.githubusercontent.com/26181150/27866201-08d1935c-61c8-11e7-90e2-c7e223b7c11c.JPG)

It will go to this window. Good with this one, it doesn't have any displayed doc, but sometimes, if it display a document which is not the related doc, chances are you might act on it immediately thinking it is the real linked docs.
![capture2](https://user-images.githubusercontent.com/26181150/27866222-14543de2-61c8-11e7-99c8-7b02af36142f.JPG)

**Comment by hdtmartin** [comment]
It looks like the previous filter is not reset, i.e. PREC-00612 was not cleared. That was the previously inputted filter prior to the case in the pictures above.
