### ISSUE TITLE
Using the free ERPNext hosted account I have an error when I delete email.

### ISSUE THREAD

**Issue by joolsr** [frappe/erpnext#9650]
Using the free ERPNext hosted account ie joolsr.erpnext.com, I see errors when deleting emails.

My email account is with GMail and is set up correctly using the Gmail defaults in ERPNext.
When I delete a number of emails, I get one that causes the error ie '**No permission to Write / Read** '

I see this same problem on my own hosted ERPNext install with this same Gmail account and another different IMAP account. This is with ERPNext updated yesterday.

![peek 2017-07-05 14-49](https://user-images.githubusercontent.com/934876/27867507-c2f0904e-6191-11e7-88c3-a13a5c52d281.gif)

This problem happens repeatedly. ie usually after deleting 20 emails this will cause this problem at least once. Sometimes **No permission to Write / Read** is shown three or fours times indicating a number of emails that cant be deleted. It's not down to one particularly badly formed junk email .

**Comment by umairsy** [comment]
Please also share the browser's error message. Perhaps delete permission is not for Communication, but for some other transaction linked to Quotation. Request you to post this issue on https://discuss.erpnext.com. If validated as a bug on the forum, we will reopen this Github Issue.

**Comment by joolsr** [comment]
I've checked the browser console and there are no errors when this error occurs.

**Comment by joolsr** [comment]
I've some some further debugging and found that if you allow Write permission then other errors appear. these errors I have now narrowed down to being down to when deleting emails that if an email has a file attachment then by default this cannot be deleted (or at least unlinked from the commnuication email record). I've tried opening the file permissions but have not cracked the issue as yet.
