### ISSUE TITLE
Product Bundle - Does not maintain stock, have batch number, unable to create a delivery note

### ISSUE THREAD

**Issue by addymuliady** [frappe/erpnext#9655]
ERPNext: v8.0.51 (master)
ERPNext Shopify: v2.0.10 (develop)
Frappe Framework: v8.0.70 (master)

I have a Product Bundle that has the following settings.

- Does not maintain stock
- Has Batch

In previous versions, I am able to submit a Delivery Note after selecting a Batch. This is due to the item not maintaining stock.

However, now, I am unable to submit a Delivery Note. After selecting a batch, the system requires quantity of that batch on the warehouse.

Expected Outcome:
Due to Item does not maintain stock, it should not require and check against quantity in any warehouse.

Thanks!

**Comment by umairsy** [comment]
Hello,

Thanks for elaborating your usecase.

Batch No. can only be created for the Stock Item. It is not available for the non-stock item. If you want to create a Batch for an item, please add it as a stock item.

Request you to post your inquiries on https://discuss.erpnext.com. Once it is validated as bug, you can create a Github Issue here.
