### ISSUE TITLE
Manufacturing module not showing only BOM item

### ISSUE THREAD

**Issue by Laxminarayan75** [frappe/erpnext#9657]
Dear All,

     I'm novice to ERPNext and was trying to implement BOM, Operation, Workstation etc. But Under Manufacturing I only have 
Production
    -> Production Order
    -> Stock Entry
    -> Timesheet
and
Bill of Materials
    -> Item

I would want to setup "Workstation", "Operation" etc, but not able to find where to.. On the modules, I have all the modules ticked. Am I missing something. 

Thanks,
Laxminarayan

**Comment by yashodhank** [comment]
@Laxminarayan75 never post question on Github issues, for that we have community forum https://discuss.erpnext.com. Kindly repost it on forums.
