### ISSUE TITLE
Financial Statements PDF should show decimal places according to System Settings precision

### ISSUE THREAD

**Issue by addymuliady** [frappe/erpnext#9659]
In PDF, Financial Statements to show number of decimal places according to System Settings precision.

For example, as image below, instead of 3 decimal place, should show 2 decimal place.

![image](https://user-images.githubusercontent.com/21187126/27898484-d2b67f76-6258-11e7-92a1-dc8d9545880e.png)

**Comment by umairsy** [comment]
Similar to https://github.com/frappe/erpnext/issues/9639. Please followup via linked Github Issue.
