### ISSUE TITLE
Keyboard shortcut for switching child rows not working

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#9660]
Earlier Cmnd/Ctrl + Up/Down helped in switching rows in the child table. It is not working for now. The command doesn't have any impact on the child table or open modal.

![27079646-178c2c64-5056-11e7-8da9-3e0532ae2fe2](https://user-images.githubusercontent.com/910238/27899804-5d4f37f0-6249-11e7-9a39-a26a138b6f83.png)

**Comment by tundebabzy** [comment]
Hi @umairsy 
I fixed this in frappe/frappe#3605. It has been merged but I don't think it has been released though.

**Comment by samarsingh6965** [comment]
How to disable above key shortcuts for a specific doctype
