### ISSUE TITLE
Company - Error message for new Company

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#9663]
A user reported an erro message received while creating new company. 

![screen shot 2017-07-06 at 11 48 10 am](https://user-images.githubusercontent.com/910238/27900332-923a1ffa-624b-11e7-9c23-e6e489f57d59.png)

Please improve validation message, so that user will know what to correct. Even better, check for the scope for re-design so that validation can be removed.

**Comment by tundebabzy** [comment]
This is strange. According to the screenshot, the error pops up in Setup > Company but the sentence "Account does not match with Company" does not exist in the Company doctype source. 

Perhaps this is something that can be fixed by restarting bench or reinstalling?

**Comment by tundebabzy** [comment]
This is strange. According to the screenshot, the error pops up in Setup > Company but the sentence "Account does not match with Company" does not exist in the Company doctype source. 

Perhaps this is something that can be fixed by restarting bench or reinstalling?
