### ISSUE TITLE
Pricing Rule - #Bug Discount is mandatory

### ISSUE THREAD

**Issue by drthilina** [frappe/erpnext#9664]
Hi,
This is my first issue on Github. (My ERP system is hosted at frappe, so don't have any admin rights)
- Objective = Apply a % margin for a specific set of products and limit the **Max** discount.

   I tried using pricing rule, in this particular instance I want to apply a 15% (on price list) margin for a particular product range.
The system is mandating me to insert a Price/discount, and when I put 0%, then it overrides any user applied discount to back to 0%
![image](https://user-images.githubusercontent.com/29944021/27903200-0a46c69c-6256-11e7-93fa-0501ed791b07.png)

If we take the regular use case,
- User should be able to select either Margin or Discount or both.

- For discounts, either it could be a fixed discount or a limit on the max discount

Can this issue be resolved?

Best regards

**Comment by umairsy** [comment]
Replicating. @rohitwaghchaure please check.
