### ISSUE TITLE
Customfild gender

### ISSUE THREAD

**Issue by paulator** [frappe/erpnext#9671]
Hi,

I already created a custom field called 'gender'

due to #9199 I have now two fields called 'gender' in my form.

![image](https://user-images.githubusercontent.com/7262648/27909864-003c91fc-6253-11e7-8c27-58c486eca2d6.png)

If I want to delete my custom field 'gender' I get the fillowing message:

![image](https://user-images.githubusercontent.com/7262648/27909768-92d741b6-6252-11e7-9970-d42a4d4dca47.png)

Excpected behavior:
I can delete the custom field.

ERPNext Version: 8.3

**Comment by applepipe** [comment]
Hello @paulator 

Try to delete the custom field in the custom field list, you cant delete the field on personalize form.

**Comment by paulator** [comment]
Thank you @applepipe, this did the trick.
