### ISSUE TITLE
Listbox does not sort items in alphabetical order in other language than english

### ISSUE THREAD

**Issue by gbard** [frappe/erpnext#9678]
Hi,

When using ERPNext in English there is no issues. Everything is sorted out alphabetically which makes it easy to find what I want (DocTypes, Forms, etc). But when I switch to French, everything is mixed up and harder to find in the listboxes.

Thanks!

G.

**Comment by manassolanki** [comment]
Hi @gbard 
Could you please let us know something specific in your language which is being sorted incorrectly?  I have checked few languages I know but they are being sorted properly. In ERPNext the data is being sorted by their Unicode but there are some characters whose order change in different language.

**Comment by gbard** [comment]
Here is a good example:

[http://imgur.com/a/7kvmV](url)

This is in the Permission Manager.

Paramétrages À Propos > About Settings
Compte > Account
Paramétrages des Comptes > Account Settings
Coût de l'Activité > Activity Cost
Type d'activité > Activity Type
...

As you can see, it's sorted using the default english words.

I'm using the French (fr) language.
