### ISSUE TITLE
URGENT: Error when creating invoice. We cannot create any invoice from any delivery note.

### ISSUE THREAD

**Issue by hdtmartin** [frappe/erpnext#9680]
We are encountering the following error, when creating Sales Invoice from Delivery Note.

![image](https://user-images.githubusercontent.com/26181150/27942407-34d54fce-6309-11e7-9b15-dcd4b77992ad.png)

We are using cloud version. Our domain is vvt.erpnext.com.

Please help. Thanks!

**Comment by mona1977** [comment]
Hello, I just check at my end , it work properly. Please can you add my SKYPE - suren_gupta and explain in more details.

SG

**Comment by hdtmartin** [comment]
Thanks for the fix from #9704 .
