### ISSUE TITLE
Awesome bar does not show page title unless refreshed

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#9684]
See permission manager:

<img width="474" alt="screen shot 2017-07-07 at 10 48 36 am" src="https://user-images.githubusercontent.com/140076/27944087-f580645a-6301-11e7-93e0-2bbb626b7369.png">

**Comment by pratu16x7** [comment]
Was not able to replicate
![screen shot 2017-07-12 at 3 09 58 pm](https://user-images.githubusercontent.com/5196925/28111927-cd1ee61e-6714-11e7-93bd-c0fc5ee0c60f.png)

Is there a specific case where this happens?
