### ISSUE TITLE
[GST] Invoice copy field should be allowed on submit

### ISSUE THREAD

**Issue by ishanloya** [frappe/erpnext#9685]
Shouldn't the Invoice copy field (Original/Duplicate/Triplicate) be allowed on submit so that all 3 printouts can be taken accordingly?

**Comment by snvora** [comment]
Also suggest adding duplicate for supplier. (Applicable for service provider / where transporter copy not mandatory)

**Comment by nabinhait** [comment]
@ishanloya Fixed in the latest release.

**Comment by nabinhait** [comment]
@snvora Added the new option
