### ISSUE TITLE
Signature field - box size is very large. Please make it configurable

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#9686]
Based on WN-SUP26205

Signature Box size is tooo big it's taking 1/4 of the page  Can't you remove the borders and just the signature comes with the underline and space is saved for som other text (Alignment)

![screen shot 2017-07-07 at 10 28 35 am](https://user-images.githubusercontent.com/910238/27945047-5b708dd4-6308-11e7-8845-6795fbd976fb.png)

**Comment by conelco** [comment]
Dear Support 
Signature has to be locked at the Bottom "end" of the page. 

1. we would like to have  underline for signature 1  and  Text ""Issued By""   " under the line and signature to be done Above the Line 

2.  signature 2 same but with Text Received By " Under the line and signature Above the Line.

Hope Above is clear.

**Comment by conelco** [comment]
Dear Support , 
what is the cost of fast track for the Signature issue solution..
Regards

**Comment by conelco** [comment]
How will signature pad gets integrated with the software.

**Comment by rmehta** [comment]
@conelco this is fixed now. Will come in next release.
