### ISSUE TITLE
HSN Code 

### ISSUE THREAD

**Issue by MANOJMAINKAR** [frappe/erpnext#9696]
In our system all 8 digits HSN codes are uploaded , consultant advised us to use 4digit HSN codes  instead 
of 8 digit as 
Dealers who have a turnover of Rs 1.5 crores up to 5 crores will have to use two digit HSN code.
Dealers with turnover less than 1.5crores will not have to use it.
The dealers who crosses the 5 crores margin will have to use 4 digit HSN codes.
In case of business that deals with import and export they will have to use 8 digit code which will be compulsory.
So one time codes should be uploaded in addition to 8 digit HSN codes

**Comment by umairsy** [comment]
Please followup for this feature via https://github.com/frappe/erpnext/issues/9633
