### ISSUE TITLE
Multiple Add in Materials BOM doesn't set QTY

### ISSUE THREAD

**Issue by creamdory** [frappe/erpnext#9698]
Hi All,

I have this usecase wherein when I use "Multiple Add" for Grid in Materials table (Items) in BOM, it sometimes doesn't set QTY in the grid. Please see below:

![multiple add bom](https://user-images.githubusercontent.com/21003054/27952103-bce6c49e-6339-11e7-9fbe-602f47818b0e.gif)

**Comment by tundebabzy** [comment]
Hi @creamdory 
I'm finding this very difficult to reproduce. Were you able to get a specific way to reproduce this?

**Comment by creamdory** [comment]
@tundebabzy it seems random in my end. Is it setting correctly at your end?

**Comment by tundebabzy** [comment]
@creamdory most of the time. Like you said, it fails randomly

**Comment by creamdory** [comment]
Yeah. It seems that it is breaking when passing the qty entered from the dialog. @tundebabzy

**Comment by tundebabzy** [comment]
This isn't yet fixed

**Comment by nabinhait** [comment]
@tundebabzy Have you tested after pulling frappe/frappe#4003 ?

**Comment by tundebabzy** [comment]
Yes

**Comment by Zlash65** [comment]
![bom](https://user-images.githubusercontent.com/11695402/29911165-7f7bdac2-8e4a-11e7-8b57-c0b662275a72.gif)
Seems to be fixed though, my branch was up-to-date with hotfix when i tested

**Comment by rmehta** [comment]
@tundebabzy can you share a screencast where this is failing for you?

**Comment by tundebabzy** [comment]
No longer failing. I think I was testing on the wrong branch. Sorry for the false alarm
