### ISSUE TITLE
Wrong validation message in Sales Invoice for overbilling

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#9700]
Sales Invoice:

Sales Invoice has items fetched from Delivery Note. All the item rates and qty is same as in Sales Order and Delivery Note. But on submitting Sales Order, validation message says:

![screen shot 2017-07-07 at 3 09 10 pm](https://user-images.githubusercontent.com/910238/27952640-a81ebde0-6326-11e7-83ba-a574dbba4ab1.png)

But in the Sales Order and Delivery Note, rate for this amount is zero only.

![screen shot 2017-07-07 at 3 09 32 pm](https://user-images.githubusercontent.com/910238/27952785-249437ce-6327-11e7-8d4f-b511d4652729.png)

**Comment by umairsy** [comment]
please release via Hotfix if possible

**Comment by hdtmartin** [comment]
We are also encountering the error message **"Serial No Serial No not found. The resource you are looking for is not available**" when making Sales Invoice from Delivery note since today. Hope this can be resolved soonest. Yesterday, everything is working fine.

**Comment by rohitwaghchaure** [comment]
Fixed the issue of serial no serial no not found via https://github.com/frappe/erpnext/pull/9704
Warning message showing because sales order has zero rate
