### ISSUE TITLE
Naming series with suffix

### ISSUE THREAD

**Issue by PCzerw** [frappe/erpnext#9705]
We have a problems with naming series and sequence numbers.
Our Sales invoice naming definition looks like this:

INVOICE-RET-
INVOICE./.###./17./HU
INVOICE./.###./17./PL
INVOICE./.###./07./17./PL

I wanted to split months series - each month has his own numbers starting from 1 (INVOICE/001/07/17/PL next month INVOICE/001/08/17/PL).
Now with this definition we have continuous numbers for all invoices.
Changing value in UPDATE SERIES not giving me anything.

When I`m creating invoice (even draft) and I will delete it, this also takes me a number and I don not have continuous number series.

Thanks for great software.

**Comment by rmehta** [comment]
@PCzerw As of the current design, the naming series only works with a prefix. Please adopt a different naming series.
