### ISSUE TITLE
Sales invoice not fetching complete data

### ISSUE THREAD

**Issue by ajit-jain1** [frappe/erpnext#9706]
Hi,
the following issue was observed after the latest update.
![error-1](https://user-images.githubusercontent.com/19492543/27954087-0d533e98-632c-11e7-8388-4c74157a0d25.PNG)
![error-2](https://user-images.githubusercontent.com/19492543/27954089-0dd90bfe-632c-11e7-9d01-fbdf6272c29f.PNG)

Although a credit period of 30 days was saved in the customer data, it is not being fetched by the sales invoice.
Similarly, address templates, tax rules and debit to account details are also not fetched.

**Comment by rmehta** [comment]
This is fixed now.
