### ISSUE TITLE
In Purchase Invoice due date can't be before posting date

### ISSUE THREAD

**Issue by somicoito** [frappe/erpnext#9709]
It can happen (frequently) that we receive invoices from our suppliers after due date is passed.
I think that the message "due date can't be before posting date" is not necessary.
In our case posting date cannot be changed, and I don't see the utility.

In our opinion you should let indeed due date depend on supplier's invoice date field.

We can't change how reality is to override a block...can you please remove this?

<img width="1344" alt="schermata 2017-07-07 alle 12 27 23" src="https://user-images.githubusercontent.com/26325987/27954571-ddb554d4-6310-11e7-8f12-07ebeb42416c.png">

**Comment by umairsy** [comment]
Sorry as this is very important and very legit validation in most cases. You can edit posting date of the invoice by clicking on "Editing Posting Date and Time" field.
