### ISSUE TITLE
Error in stock reposting after Landed Cost Voucher

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#9714]
Issue WN-SUP25812

Example to explain use-case based on date:

1st June: Item purchase at cost 1.7 in Stores

2nd June: Item transferred from Stores to FG warehouse

3rd June: User created Landed Cost Voucher which updated stock valuation of item to 2.

- Based on the reporting, evaluation updated in the Purchase Receipt to 2.

- In the Stock Entry of Material Transfer, valuation update for the source item, but not for the target item. Instead the additional valuation amount (added via Landed Cost Voucher) which is 0.3 in this case was posted into Stock Adjustment account.

- When Item Sold to Customer from FG Warehouse, expense of 1.7 was booked only.

**Comment by maher-haq** [comment]
Right

**Comment by nabinhait** [comment]
It will get fixed with proposed immutable ledger implementation. 
https://discuss.erpnext.com/t/discussion-immutable-ledger/31153

Closing the issue.
