### ISSUE TITLE
State / State code for GST invoice

### ISSUE THREAD

**Issue by MANOJMAINKAR** [frappe/erpnext#9715]
State / State code are missing invoice , which may required in future for data upload in GST returns

**Comment by umairsy** [comment]
Manoj,

State Code field has been added in the GST Tax Invoice format.

![screen shot 2017-07-10 at 3 59 38 pm](https://user-images.githubusercontent.com/910238/28014049-d72ade70-6588-11e7-8d65-43df5795d8bc.png)
