### ISSUE TITLE
New filter section - filters not cleared when needed

### ISSUE THREAD

**Issue by aptech-admin** [frappe/erpnext#9720]
If a filter is set using the new section on Sales Invoice for customer X, then you open up a project and click on the "Sales Invoice - n" link. The filter for the project gets added to the previously selected customer filter, displaying no result.
I think that in that case, filters from the new "filter section" should be cleared up.

![image](https://user-images.githubusercontent.com/9044651/27961801-fd0e4678-62fd-11e7-857b-30ed57d17bae.png)

Also, when a link is clicked for the first time in the "Related Documents" section, the auto-generated filter on the destination form is not applied (not even present in fact) and users have to hit back on the browser, then click again on the link in the Related Documents section and this time the filter gets applied correctly.  The second time we use links on the "Related Documents" section from the same module (PI, SI, SO, ect.), it works fine.

**Comment by rmehta** [comment]
This is fixed.
