### ISSUE TITLE
Cannot Finish Production Order if skip material transfer is checked

### ISSUE THREAD

**Issue by ishanloya** [frappe/erpnext#9726]
![screen shot 2017-07-08 at 9 56 47 am](https://user-images.githubusercontent.com/17540310/27982623-3e3af4d6-63c4-11e7-9994-9f15d6c36620.jpg)

If I click on the Finish button, nothing happens. The screen for the Stock Entry doesn't appear. Note that the skip material transfer button is checked.

**Comment by ishanloya** [comment]
```
desk.min.js:3084 Uncaught TypeError: action is not a function
    at HTMLButtonElement._action (desk.min.js:3084)
    at HTMLButtonElement.dispatch (jquery.min.js:3)
    at HTMLButtonElement.$event.dispatch (report.min.js:2967)
    at HTMLButtonElement.r.handle (jquery.min.js:3)
```

**Comment by ishanloya** [comment]
Changing lines 294-295 of production_order.js to the following seems to fix this:

```
var finish_btn = frm.add_custom_button(__('Finish'), function() {
						erpnext.production_order.make_se(frm, 'Manufacture');
					});
```

**Comment by nabinhait** [comment]
Thanks.

Sent a pull request https://github.com/frappe/erpnext/pull/9730
