### ISSUE TITLE
Insufficient Permission for GST HSN Code 

### ISSUE THREAD

**Issue by ajit-jain1** [frappe/erpnext#9731]
hi,
getting this error on new item creation
![hsn error](https://user-images.githubusercontent.com/19492543/27983681-f7f961a8-63df-11e7-9df8-e703da810aad.PNG)

have not tried with an existing item though!
User is Admin with all roles and modules accessible.

**Comment by epochc** [comment]
Ajit bhai,

An issue is after you confirm that an exiting feature is not working the way it is intended. Learning curve, configuration issues should be addressed on the Discussion Forum, which I see you have posted. But please wait a few hours or days to get a response.

All of this is voluntary work by the community, so sometimes you get an immediate response and sometimes it takes for ever.

Please do not raise an issue here till you are sure that an existing feature that's not working as it was intended.

Thanks

Jay
