### ISSUE TITLE
Navigation keys

### ISSUE THREAD

**Issue by PCzerw** [frappe/erpnext#9736]
On new version not working navigation keys:
Ctrl+Up Ctrl+Down
ESC is working.
I tried on different browsers on two computers.

![1](https://user-images.githubusercontent.com/26510702/27989506-48b99720-643a-11e7-8901-b61ed0f1cf1f.jpg)

**Comment by tundebabzy** [comment]
Hi @PCzerw 
This has been fixed in frappe/frappe#3605. It will soon be released
