### ISSUE TITLE
Setup Wizard - Improve Company Abbreviation system to ignore validation in the Setup wizard

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#9737]
To ensure that Company Abbreviation is not very long, we have added validation of abbreviation of not more than 5 characters only. But this also leads to Setup Wizard failing, as users are not aware of this validation in the Setup Wizard. Either we should show this validation on data entry in the field or auto-trim it to limited no. of characters.

`  File "/home/frappe/benches/bench-2017-07-07-a/apps/erpnext/erpnext/setup/doctype/company/company.py", line 45, in validate_abbr
    frappe.throw(_("Abbreviation cannot have more than 5 characters"))
  File "/home/frappe/benches/bench-2017-07-07-a/apps/frappe/frappe/__init__.py", line 319, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/home/frappe/benches/bench-2017-07-07-a/apps/frappe/frappe/__init__.py", line 309, in msgprint
    _raise_exception()
  File "/home/frappe/benches/bench-2017-07-07-a/apps/frappe/frappe/__init__.py", line 282, in _raise_exception
    raise raise_exception(encode(msg))
ValidationError: Abbreviation cannot have more than 5 characters`

**Comment by netchampfaris** [comment]
Should be validated at the Setup Wizard

**Comment by umairsy** [comment]
Is this enhancement completed?
