### ISSUE TITLE
Filters hidden by default on mobile view ?

### ISSUE THREAD

**Issue by chdecultot** [frappe/erpnext#9741]
Hi,

This is an enhancement suggestion regarding filters.

As discussed in https://discuss.erpnext.com/t/new-feature-filters-cleanup/25216/6, it could be nice to have the new filters hidden by default on mobile to improve UX.

On some Doctypes with a lot of filters it can seem overwhelming.

![screenshot_20170708-193810](https://user-images.githubusercontent.com/4903591/27993245-9082284e-64a6-11e7-9042-58b825fe547b.png)

But I don't have any suggestion on how to do that without adding yet another button and following UX design best practices. It's hard to find a balance between the best design and the best user experience.

If anyone has any thought don't hesitate 😉

**Comment by rmehta** [comment]
fixed. will show only 3 filters

**Comment by ShehataGhattas** [comment]
@rmehta 
your solution is good but it have issue if i have done search from computer in the fourth filter and i had opened it from the mobile its show the filtered data and i cant remove the filter that i had did from the PC,

also some time the design its not showing in good arrangement see the below 

![image](https://user-images.githubusercontent.com/22128816/31782887-1d36d272-b505-11e7-8add-fb95e8a7bfb0.png)
