### ISSUE TITLE
employee master enhancement

### ISSUE THREAD

**Issue by SOLOSOFTMA** [frappe/erpnext#9743]
- ability to put an employee on sleep for exemple (case when a employee stop working one month)
- add how much an employee spent in the company.
- employee wage
- link to working schedule (working templates)
- link to salary structure
- link to overtime template (overtime template)

**Comment by umairsy** [comment]
ability to put an employee on sleep for exemple (case when a employee stop working one month)

**You can disable Employee temporarily**

add how much an employee spent in the company.

**Expense Claim?**

employee wage

**Past Salary Slips will provide this report**

link to working schedule (working templates)

**In the Timesheet, if you select an Employee, then check Employee > Menu > Links, and you will find Salary Structure linked to that Employee.**

link to salary structure

**Employee dashboard already has link of Salary Structure**

link to overtime template (overtime template)

**In ERPNext, working hours of an Empoyee is tracked in the Timesheet only.**

**Comment by umairsy** [comment]
request you to report usability queries on the https://discuss.erpnext.com
