### ISSUE TITLE
Setup Wizard Exception - ValidationError: Setup Already Complete!!

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#9745]
We often receive this Setup Wizard Exception. It generally occurs in the case where Setup Wizard fails for some valid reason. When user try re-setup, it ends with this validation message. Have observed Saurabh resolving this issue by re-installing the site.

`Error report of: ValidationError: Setup Already Complete!!`

**Comment by pratu16x7** [comment]
#10336
