### ISSUE TITLE
Error when Saving new Stock Entry

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#9751]
Related to WN-SUP26309

Steps:

1. New Stock Entry
2. Selected Purchase as Stock Transfer
3. Select Source and Target Warehouse
4. Selected item.
5. Clicked on Save

![screen shot 2017-07-10 at 1 03 46 pm](https://user-images.githubusercontent.com/910238/28007249-45a7f7fc-6570-11e7-9500-fd8915fc34a7.png)

**Comment by rmehta** [comment]
Check custom script

**Comment by nabinhait** [comment]
@umairsy Is this communicated or fixed? The error is in custom script.

**Comment by umairsy** [comment]
Communicated
