### ISSUE TITLE
Configuarable item bundles during Sales Cycle

### ISSUE THREAD

**Issue by drthilina** [frappe/erpnext#9752]
Hi,
We are selling products that require bundling together. But in the unlikely event a particular sub-item is missing and, where we can give an Alternative sub-item. ERPNext requires us to have that configuration saved, as a bundle beforehand as well.
Is it possible to have a feature to customize the bundle during the Sales Cycle. You start with a base and keep changing its specs to your liking.  I've had this need for sometime, where we have to customize a bundle during the Sales Cycle. It is not necessarily a ADD/REMOVAL of items in the bundle but select as per the requirement. Since those Items are either delivered as assembled or together, they cannot be classified as manufacturing. The best example for this is, which I can give is, "Buying a Customized Laptop at HP".
![image](https://user-images.githubusercontent.com/29944021/28007669-e9adb71e-6571-11e7-8693-669ce055279f.png)
![image](https://user-images.githubusercontent.com/29944021/28007673-f32a51a8-6571-11e7-9509-e7210e71047c.png)

I like to say if this feature is something the community feels that will improve ERPNext experience to the user, I would like to sponsor the development of it and subsequent release to the ERPNext platform.

I hope this ISSUE will create enough momentum.

Best Regards

**Comment by umairsy** [comment]
In the Sales Order, Product Bundle items are fetched in the Packing List table. Will making this table editable sufficient, so that user can add/remove/edit items as per the requirement?

**Comment by umairsy** [comment]
![screen shot 2017-07-10 at 3 25 47 pm](https://user-images.githubusercontent.com/910238/28012678-37aea18c-6584-11e7-94bd-3bcdca4566d3.png)

**Comment by drthilina** [comment]
Thanks Umair,
   Packing list is a good workaround. But I believe this would be a quick fix, although it will raise few other problems.

- User can add anything, possible security issue (To my original example, Say add a large RAM for the same price, the motivation is that user just selects from a given set, pricing is automatic.

- Second, the "Variants" should have limitations, much like "Variants" in item stock.

- Third comes the pricing structure based on the selection. Say we create a Price list called "Bundled selling", the individual prices are fetched from that list to make the total.

Best regards

**Comment by umairsy** [comment]
@drthilina How about creating a bounty or ERPNext job for this feature? Some sponsorship for it will certainly help us prioritize it.

https://erpnext.org/bounties
