### ISSUE TITLE
viewing linked material request, material transfer for production order and  sale order

### ISSUE THREAD

**Issue by Musthafakp** [frappe/erpnext#976]
Need to identify which material request and material transferred correspond to which production order and which sale order?
I understand, for now, it is only available for material request of a  Sales Order, provided you make Material Request for same item as in Sales Order. what about raw material?. For now, Production Order is not updated in the Material Request and material transfer..
Would  like to see which material request and material transfer is for which production order and  , which sale order and viceversa.

**Comment by PawanMeh** [comment]
![screen shot 2017-04-29 at 1 00 47 am](https://cloud.githubusercontent.com/assets/20460498/25544438/188ee0fe-2c78-11e7-8c76-bc65e03a5dfc.png)

Please check if the linkage(Production Order to Material request) in the latest release meets your requirement.
