### ISSUE TITLE
[Feature] Picking List Management in Stock module

### ISSUE THREAD

**Issue by GSLabIt** [frappe/erpnext#9763]
Hi there, 

what about the idea to add a new module `Picking List`  in between `Sales Order` and `Delivery Note`?

- basically it will be generated on `Sales Order` `submit`

- warehouseman will pick items based on this `"Picking List"` 

- due to the fact that real `actual_qty` could be different from the one stored in ERPNext; effective picked qty would be different from the ordered one, so the DN should be created based on the real qty warehouseman will scan/get during pick.

Could some one at Frappe estimate costs? Prospect willing to sponsor the feature ..

**Comment by joezsweet** [comment]
@nabinhait can we integrate into ERPNext once developed? The idea is to enable, if needed, from stock settings.

**Comment by yadavyk** [comment]
Please refer : [PickList](https://docs.erpnext.com/docs/v13/user/manual/en/stock/pick-list)
