### ISSUE TITLE
GST standard Invoice print format and tax table

### ISSUE THREAD

**Issue by MANOJMAINKAR** [frappe/erpnext#9765]
We are not able to fit in one single A4 page , tried to reduced  lines no use . There should be way to fit in single A4 page . 
Also in tax table , we are not able to change the tax headings , it gets directly pulled from Account Headings from Chart of accounts , which may be too long and can not be reduced .

**Comment by nabinhait** [comment]
How is it coming right now? Can you please post a scanned copy of printed docs?

**Comment by MANOJMAINKAR** [comment]
Hi , 

Attached herewith please find scan copies of one invoice . It is without
letter head , which is required and with all the required fields to be
printed in Invoice . In second modification format (scan0051 & 52 ) , on
screen it is shown in one page , but gets printed in 2 pages. There
should be way to fit into one page as well as simple way to draw
borders/box around fields to get better look of the Invoice. 

Regards 

Manoj 

On 10-07-2017 04:37 PM, Nabin Hait wrote: 

> How is it coming right now? Can you please post a scanned copy of printed docs? 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1] https://github.com/frappe/erpnext/issues/9765#issuecomment-314075141
[2]

**Comment by nabinhait** [comment]
@MANOJMAINKAR To attach a file in the github issue, don't reply via email. Instead open the github issue and upload the image by "drag and drop".

**Comment by umairsy** [comment]
Manoj,

Can you please attached screenshots here indicating issue in the  print format?
