### ISSUE TITLE
claim amount rejected issue

### ISSUE THREAD

**Issue by sumitdas4u** [frappe/erpnext#9767]
if we reject the claim amount the sanctioned amount should automatically zero. but now its creating a voucher though it's rejected.

and also if I make sanctioned amount zero manually then its showing paid as status.

![image](https://user-images.githubusercontent.com/28945509/28015711-c630d970-658e-11e7-852c-df246723c606.png)

**Comment by umairsy** [comment]
If Expense Claim is Rejected, then it should not be visible in the Journal Entry as well.

![screen shot 2017-07-10 at 6 45 57 pm](https://user-images.githubusercontent.com/910238/28019867-0b4f9d32-65a0-11e7-817b-6ff0201f4ddc.png)

Also, issue of Paid status for Sanctioned Amount as Zero is replicating.

**Comment by sumitdas4u** [comment]
dont create Journal Entry for rejected expense
