### ISSUE TITLE
Address Title and Address Name

### ISSUE THREAD

**Issue by somicoito** [frappe/erpnext#9771]
Our client wants us to ship to their warehouse. The Name on the doorbell is different so I need the possibility to specify address name in all the transactions.
The way it is designed now I can only use the Address Name together with the suffix -billing or -shipping.
I need to be able to specify address Name without making customisation as this is a common use.
<img width="1146" alt="drop shipping 1" src="https://user-images.githubusercontent.com/26325987/28017969-b0135180-657b-11e7-8bdd-36a4555ab937.png">
<img width="1164" alt="drop shipping 3" src="https://user-images.githubusercontent.com/26325987/28017981-b78ece9e-657b-11e7-8b59-fcd711dfe537.png">

**Comment by umairsy** [comment]
How about adding a Custom Field in the Address to name with the suffix? In the Address Template, you can mention that field name as well.

In the Address and Contact, there are often multiple values with the same name, hence we add the company name to bring uniqueness.
