### ISSUE TITLE
Override max discount allowed based on roles - Items

### ISSUE THREAD

**Issue by narcisonunez** [frappe/erpnext#9774]
The issue i have is that the Items can have a maximium percent of discount, where the Item can't be sell it with a discount greater than the maximium value specified.

I want that an specific Role with more privilages can be able to sell it no matter the amount of discount they want to apply.

Based on:
https://discuss.erpnext.com/t/override-max-discount-allowed-based-on-roles-items/25730/2

**Comment by drthilina** [comment]
Even I do like to have this feature,
(Just reading my mind)The price is set in the "Price list and discount is set in the item. I guess the first step should be to have them both placed in the same location (Price list). Then based on the Role, we can have different columns with different discount?

at the moment, We apply a Additional discount on the Net Total and made that section only visible to Sales Manager Role

**Comment by umairsy** [comment]
We can have Role defined as Credit Controller also privileged to offer higher discount?

Or we can make Discount a notification instead of a validation, so that user can take a call accordingly? Next thing coming I can see is, make it configurable, like in budgets :)

**Comment by taherkhalil** [comment]
+1 :+1: 

ideally there should be possibility for role based privileges for all fields for greater control and management.

**Comment by azharul-islam** [comment]
Hi guys, has this been implemented in current v11?
