### ISSUE TITLE
Typo Error In Timezone of user panel

### ISSUE THREAD

**Issue by troin** [frappe/erpnext#9777]
Timezone is Asia/Calcutta instead of Asia/Kolkata
![typobugtimezone](https://user-images.githubusercontent.com/15824078/28033704-b71938fe-65cc-11e7-89eb-e9fc3f061a26.jpg)

**Comment by rmehta** [comment]
@troin unfortunately Asia/Calcutta is the standard. I am not sure libs are updated to handle Asia/Kolkata

**Comment by PawanMeh** [comment]
This is appearing fine in the latest release

![screen shot 2017-07-24 at 5 51 33 pm](https://user-images.githubusercontent.com/20460498/28523174-cb2804ac-7098-11e7-8d68-e8c563bbc7e5.png)
