### ISSUE TITLE
Adding a docfield length on creation

### ISSUE THREAD

**Issue by kenseii** [frappe/erpnext#9778]
It would be good if there was a **length** field similar to the one of **custom field**

**Comment by umairsy** [comment]
Can you please share the use-case? For the field with more character limit and visibility, you can insert Small Text field. Field "Text Editor" gets 100% width in the form, if no column breaks added.

**Comment by kenseii** [comment]
The use case would be in case i want to validate e.g i have a phone number field and i want the digits to be 10. this can be done through a custom script but it can be easier if there was a max length of characters or another way of easily specifying that while creating a docfield

**Comment by PawanMeh** [comment]
Kindly check below screen shot, if it does not meet your use case, re-open the issue with what you have tried.

![length_field](https://user-images.githubusercontent.com/20460498/28522267-fa06440e-7094-11e7-9b74-5c07f63c5b7d.png)

**Comment by saleemdev** [comment]
I tried changing the length on the doctype. It doesn't work
