### ISSUE TITLE
Miscalculation in Leave Without Pay calculated

### ISSUE THREAD

**Issue by ASneha1** [frappe/erpnext#9782]
Hi Team, 

Kindly note that there is a miscalculation in the Leave Without Pay due to the placement of the following line : [Line 236 in salary_slip.py ](https://github.com/frappe/erpnext/blob/master/erpnext/hr/doctype/salary_slip/salary_slip.py#L236)

Since the working_days is used in the lwp calculation, the code for lwp calculation should be before the holidays are subtracted from the working_days. If not, when the working_days is 22 days, a LWP applied on the 27th of the month is not accounted as number of LWP in Salary Slip.

**Comment by rmehta** [comment]
@ASneha1 can you propose a fix?

**Comment by ASneha1** [comment]
@rmehta, we have not pulled the latest version on the site i am working on, thus unable to send a Pull request. But it is a quick change in the order of the following line in salary_slip.py : 
![image](https://user-images.githubusercontent.com/16811259/28158644-f8bc1bc4-67ec-11e7-9c4b-43a670619e46.png)

**Comment by rmehta** [comment]
@ASneha1 you don't need to install to open a Pull Request. Just start a new branch, commit and push the changes and send a pull request!
