### ISSUE TITLE
[Feature Request] "Has Expiry" checkbox in Item with Batch

### ISSUE THREAD

**Issue by creamdory** [frappe/erpnext#9784]
It would be really helpful to have a checkbox "Has Expiry" option when an Item's "Has Batch" is tick. Also, this will be a validating feature to add "Expiry Date" during batch creation of the item so that it will not be left off.

![has expiry](https://user-images.githubusercontent.com/21003054/28060565-1c4a8196-665a-11e7-9b2b-2f5646b08f9b.png)

Let us know if this is good. We can send PR once feature is approve as this will be very helpful for us.

Thanks!

**Comment by vrms** [comment]
this is a nice feature but implementation needs to be well thought through in my eyes. 

I mean ... if you have  a "best before"/"expiry" date on batches this needs to have consequences on  products availability (FEFO first expire, first out) and also needs to scrap expired batches (which may even be be configurable). Is this something you where planning @creamdory ?

**Comment by creamdory** [comment]
@vrms There is already expiry dates on batches. This is something different. A batch can be disabled but not expired. So it is just there in stock but you cannot use them for any transactions.

**Comment by kennethsequeira** [comment]
Closing this issue as the checkbox "Has Expiry" is added in the item master (v11)

![image](https://user-images.githubusercontent.com/33246109/56414594-b60f6200-62a8-11e9-9947-de8c1f793925.png)
