### ISSUE TITLE
[GST] New Fields required in Sales Invoice

### ISSUE THREAD

**Issue by snvora** [frappe/erpnext#9791]
As per excel format of GSTR-1, Following additional fields may be required to generate accurate reports and assist in filling of returns.

1. Reverse Charge [Y / N] { default N }
2. Invoice Type [ Regular / SEZ / Deemed Export / Export ] { default Regular }
3. Export Type [ WOPAY / WPAY ] { depends on Invoice Type }
3. E-Commerce GSTIN - for sale through e-commerce platform. { maybe new category of customer }

**Also adding these fields in Tax Rule** - to determine the template that would be chosen will be added advantage.

Accounting of e-commerce sale may be complex - and it would be great to accommodate it.  i.e Billing and shipping address may be of actual user, but amount is receivable from e-commerce platform.

This is based on B2B and EXP worksheet in excel sheet attached.
 
[GSTR1_Excel_Workbook_Template-V1.0.xlsx](https://github.com/frappe/erpnext/files/1138625/GSTR1_Excel_Workbook_Template-V1.0.xlsx)

**Comment by revant** [comment]
All are additional Select fields I think.

- Reverse Charge No means Tax is collected by the company and will be paid by them as normal.
 - Reverse Charge Yes means Invoice does not contain tax, Tax will be paid by buyer. (Please confirm Reverse charge logic)

> E-Commerce GSTIN - for sale through e-commerce platform. { maybe new category of customer }

I don't thing E-commerce will be customer? Isn't it additional party? Can it be Sales Partner GSTIN?

**Comment by snvora** [comment]
Logic true for reverse charge.

Export type field gets activated if invoice type is SEZ, deemed export or export.
WPAY is with payment of tax, and WOPAY is without payment of tax.

For e-commerce operator, different logic for it needs to be built up, as accounting would be different.

In normal scenario, money is receivable from customer, so his account is debited.

But in case of e-commerce sales money is receivable from e-commerce platform.
So sales partner logic may not fit.

In Indian scenario money receivable from e-commerce would be invoice value less GST ( as it is payable by them on our behalf ) less commission. So it's like development of seperate functionality altogether.

**Comment by snvora** [comment]
Hello,
Finally official tool for upload of GST returns is available. It converts Excel workbook to JSON file.

https://www.gst.gov.in/download/returns

Uploading of invoices is now possible.

**Comment by prashant87** [comment]
Any update?

**Comment by nabinhait** [comment]
This is in my immediate todo list, hopefully will be implemented within a week.

**Comment by karannshah** [comment]
> All are additional Select fields I think.
> 
> * Reverse Charge No means Tax is collected by the company and will be paid by them as normal.
> * Reverse Charge Yes means Invoice does not contain tax, Tax will be paid by buyer. (Please confirm Reverse charge logic)
> 
> > E-Commerce GSTIN - for sale through e-commerce platform. { maybe new category of customer }
> 
> I don't thing E-commerce will be customer? Isn't it additional party? Can it be Sales Partner GSTIN?

It seems that ERPNext is not ready for handling RCM. One proposed method for managing RCM appears here - they have also included impact on Tax Ledgers, Invoice Print  and  GST reports. https://discuss.erpnext.com/t/feature-proposal-gst-india-reverse-charge-mechanism/44753
