### ISSUE TITLE
table borders / headings / font size in standard print formats

### ISSUE THREAD

**Issue by MANOJMAINKAR** [frappe/erpnext#9795]
In all standard print formats / formats created using print format builder , the borders of item details table  , tax breakup in GST invoice format are too thin and not gets printed ( or too light in grey colour ) when printed on mono laser printers. 

1) There should be some way to manage thickness of  above borders as well as column heading .
2) We are not able to add additional column for a field in item table in invoice format.
3) Users are allowed to set/change column headings in such tables.
4) User are allowed to define font size / style of each field in print format

**Comment by umairsy** [comment]
Hello Manoj, 

Inline replies below.

There should be some way to manage thickness of above borders as well as column heading .

**Feature suggestion. We will keep it open for sometime to see traction for the same from other members.**

We are not able to add additional column for a field in item table in invoice format.

**Perhaps you are using Compact Print Format? Check Print Settings in your ERPNext account. To have separate column for each field, disable Compact Print Format from Print Settings.**

Users are allowed to set/change column headings in such tables.

**You can define Custom Labels from Print Format Builder. Also, you can define that in the HTML based print formats.**

User are allowed to define font size / style of each field in print format.

**Check Print Settings tools for more option on this front.**

**Comment by MANOJMAINKAR** [comment]
We can change labels for single field in print format , but not for a table like items table , Sales taxes & charges table where I need to change the labels

**Comment by umairsy** [comment]
You can set the label for the sections of items and taxes section. If you create a Print Format using Print Format Builder, then you can enable section break and labels for the section breaks. Lastly, you can also get the HTML Print Format developed by the freelancer.

**Comment by elkd** [comment]
6 years later, I have the same issue with the font settings of the printing feature. The default font weight will have the titles and table borders really faded

**Comment by elkd** [comment]
I see [this issue is still open](https://github.com/frappe/erpnext/issues/7792) maybe instead of adding font size for cheques only you can also consider adding global printer settings for font-size + font-weight
