### ISSUE TITLE
My hosted erpnext page is unreachable!!!!!!

### ISSUE THREAD

**Issue by opsninja1** [frappe/erpnext#9800]
This is a bit of an issue for my company......

![capture](https://user-images.githubusercontent.com/21339160/28074049-33a7b134-661d-11e7-9be1-063999216a56.JPG)

**Comment by nabinhait** [comment]
Sorry, there is some problem in our proxy server. We are looking into it, will inform you as soon as it is back.

**Comment by nabinhait** [comment]
Issue fixed. Please check and confirm if you are able to access your ERPNext account fine.

Sorry for the trouble caused.

**Comment by opsninja1** [comment]
Thank you!

Rick Oster
VP of Operations
Kole Digital Systems
815-469-2000 x104
rick@koledigital.com
