### ISSUE TITLE
Hide "Make" button from form toolbar if there is no next action.

### ISSUE THREAD

**Issue by rmehta** [frappe/erpnext#9804]
For a completed Purchase Order, the make button is shown, but the drop down is empty.

**Comment by umairsy** [comment]
![screen shot 2017-07-14 at 5 23 51 pm](https://user-images.githubusercontent.com/910238/28211243-38391adc-68b9-11e7-9ddb-adba1f08d7d8.png)

**Comment by rmehta** [comment]
@tundebabzy did you work on a generic version for this?

**Comment by tundebabzy** [comment]
working on it

**Comment by tundebabzy** [comment]
Fixed in frappe/frappe#3880
