### ISSUE TITLE
Crash after Login 

### ISSUE THREAD

**Issue by sah-anshu** [frappe/erpnext#9808]
07:04:28 web.1            |  * Detected change in '/home/erpnext/frappe-bench/apps/frappe/frappe/desk/doctype/kanban_board/__init__.py', reloading
07:04:28 web.1            | INFO:werkzeug: * Detected change in '/home/erpnext/frappe-bench/apps/frappe/frappe/desk/doctype/kanban_board/__init__.py', reloading
07:04:28 web.1            |  * Detected change in '/home/erpnext/frappe-bench/apps/frappe/frappe/desk/doctype/kanban_board/__init__.py', reloading
07:04:28 web.1            | INFO:werkzeug: * Detected change in '/home/erpnext/frappe-bench/apps/frappe/frappe/desk/doctype/kanban_board/__init__.py', reloading
07:04:28 web.1            |  * Detected change in '/home/erpnext/frappe-bench/apps/frappe/frappe/desk/doctype/kanban_board/kanban_board.py', reloading
07:04:28 web.1            | INFO:werkzeug: * Detected change in '/home/erpnext/frappe-bench/apps/frappe/frappe/desk/doctype/kanban_board/kanban_board.py', reloading
07:04:28 web.1            |  * Detected change in '/home/erpnext/frappe-bench/apps/frappe/frappe/desk/doctype/kanban_board/kanban_board.py', reloading
07:04:28 web.1            | INFO:werkzeug: * Detected change in '/home/erpnext/frappe-bench/apps/frappe/frappe/desk/doctype/kanban_board/kanban_board.py', reloading
07:04:28 web.1            |  * Detected change in '/home/erpnext/frappe-bench/apps/erpnext/erpnext/startup/boot.py', reloading
07:04:28 web.1            | INFO:werkzeug: * Detected change in '/home/erpnext/frappe-bench/apps/erpnext/erpnext/startup/boot.py', reloading
07:04:28 web.1            |  * Detected change in '/home/erpnext/frappe-bench/apps/erpnext/erpnext/startup/boot.py', reloading
07:04:28 web.1            | INFO:werkzeug: * Detected change in '/home/erpnext/frappe-bench/apps/erpnext/erpnext/startup/boot.py', reloading
07:04:28 web.1            |  * Detected change in '/home/erpnext/frappe-bench/apps/frappe/frappe/geo/doctype/__init__.py', reloading
07:04:28 web.1            | INFO:werkzeug: * Detected change in '/home/erpnext/frappe-bench/apps/frappe/frappe/geo/doctype/__init__.py', reloading
07:04:28 web.1            |  * Detected change in '/home/erpnext/frappe-bench/apps/frappe/frappe/geo/doctype/__init__.py', reloading
07:04:28 web.1            | INFO:werkzeug: * Detected change in '/home/erpnext/frappe-bench/apps/frappe/frappe/geo/doctype/__init__.py', reloading
07:04:28 web.1            |  * Detected change in '/home/erpnext/frappe-bench/apps/frappe/frappe/geo/doctype/country/__init__.py', reloading
07:04:28 web.1            | INFO:werkzeug: * Detected change in '/home/erpnext/frappe-bench/apps/frappe/frappe/geo/doctype/country/__init__.py', reloading
07:04:28 web.1            |  * Detected change in '/home/erpnext/frappe-bench/apps/frappe/frappe/geo/doctype/country/__init__.py', reloading
07:04:28 web.1            | INFO:werkzeug: * Detected change in '/home/erpnext/frappe-bench/apps/frappe/frappe/geo/doctype/country/__init__.py', reloading
07:04:28 web.1            |  * Detected change in '/home/erpnext/frappe-bench/apps/frappe/frappe/geo/doctype/country/country.py', reloading
07:04:28 web.1            | INFO:werkzeug: * Detected change in '/home/erpnext/frappe-bench/apps/frappe/frappe/geo/doctype/country/country.py', reloading
07:04:28 web.1            |  * Detected change in '/home/erpnext/frappe-bench/apps/frappe/frappe/geo/doctype/country/country.py', reloading
07:04:28 web.1            | INFO:werkzeug: * Detected change in '/home/erpnext/frappe-bench/apps/frappe/frappe/geo/doctype/country/country.py', reloading
07:04:28 web.1            |  * Detected change in '/home/erpnext/frappe-bench/apps/erpnext/erpnext/setup/doctype/notification_control/__init__.py', reloading
07:04:28 web.1            | INFO:werkzeug: * Detected change in '/home/erpnext/frappe-bench/apps/erpnext/erpnext/setup/doctype/notification_control/__init__.py', reloading
07:04:28 web.1            |  * Detected change in '/home/erpnext/frappe-bench/apps/erpnext/erpnext/setup/doctype/notification_control/__init__.py', reloading
07:04:28 web.1            | INFO:werkzeug: * Detected change in '/home/erpnext/frappe-bench/apps/erpnext/erpnext/setup/doctype/notification_control/__init__.py', reloading
07:04:28 web.1            |  * Detected change in '/home/erpnext/frappe-bench/apps/erpnext/erpnext/setup/doctype/notification_control/notification_control.py', reloading
07:04:28 web.1            | INFO:werkzeug: * Detected change in '/home/erpnext/frappe-bench/apps/erpnext/erpnext/setup/doctype/notification_control/notification_control.py', reloading
07:04:28 web.1            |  * Detected change in '/home/erpnext/frappe-bench/apps/erpnext/erpnext/setup/doctype/notification_control/notification_control.py', reloading
07:04:28 web.1            | INFO:werkzeug: * Detected change in '/home/erpnext/frappe-bench/apps/erpnext/erpnext/setup/doctype/notification_control/notification_control.py', reloading
07:04:28 web.1            | Exception in thread Thread-2 (most likely raised during interpreter shutdown):
07:04:28 web.1            | Traceback (most recent call last):
07:04:28 web.1            |   File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
07:04:28 web.1            |   File "/home/erpnext/frappe-bench/env/local/lib/python2.7/site-packages/watchdog/observers/api.py", line 237, in run
07:04:28 web.1            | <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'Empty'
07:04:28 web.1            | Exception in thread Thread-4 (most likely raised during interpreter shutdown):
07:04:28 web.1            | Traceback (most recent call last):
07:04:28 web.1            |   File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
07:04:28 web.1            |   File "/usr/lib/python2.7/threading.py", line 763, in run
07:04:28 web.1            |   File "/usr/lib/python2.7/SocketServer.py", line 602, in process_request_thread
07:04:28 web.1            |   File "/home/erpnext/frappe-bench/env/local/lib/python2.7/site-packages/werkzeug/serving.py", line 548, in handle_error
07:04:28 web.1            | <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'handle_error'
07:04:28 web.1            | Exception in thread Thread-1 (most likely raised during interpreter shutdown):
07:04:28 web.1            | Traceback (most recent call last):
07:04:28 web.1            |   File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
07:04:28 web.1            |   File "/usr/lib/python2.7/threading.py", line 763, in run
07:04:28 web.1            |   File "/home/erpnext/frappe-bench/env/local/lib/python2.7/site-packages/werkzeug/serving.py", line 702, in inner
07:04:28 web.1            |   File "/home/erpnext/frappe-bench/env/local/lib/python2.7/site-packages/werkzeug/serving.py", line 539, in serve_forever
07:04:28 web.1            |   File "/usr/lib/python2.7/SocketServer.py", line 241, in serve_forever
07:04:28 web.1            |   File "/usr/lib/python2.7/threading.py", line 586, in set
07:04:28 web.1            |   File "/usr/lib/python2.7/threading.py", line 407, in notifyAll
07:04:28 web.1            | <type 'exceptions.TypeError'>: 'NoneType' object is not callable
07:04:28 web.1            |  * Restarting with inotify reloader

**Comment by rmehta** [comment]
What is the exact error?

Please do ctrl+c and restart after you do bench update.

**Comment by umairsy** [comment]
Request posting technical queries on the ERPNext community forum. https://discuss.erpnext.com Once an issue related to Frappe/ERPNext is validated, you can create a Github Issue for it.
