### ISSUE TITLE
wrong GST state code

### ISSUE THREAD

**Issue by MANOJMAINKAR** [frappe/erpnext#9814]
Please check GST state code 05 , which is suppose to be assign to state Uttarakhand . In our system it is not accepting for GST numbers starting from 05 which we have received from our Uttarakhand customer. 36 is assign to Uttarakhand in our system , please check , refer following link and do the needful ( we are not able to change it from our end )

http://statecodesofindia.blogspot.in/2017/05/list-of-state-codes-of-india-for-gst.html

**Comment by nabinhait** [comment]
This is fixed and will be released tomorrow.
