### ISSUE TITLE
Show HSN/SAC in Tax Breakup table

### ISSUE THREAD

**Issue by nabinhait** [frappe/erpnext#9816]

**Comment by maheshengg** [comment]
Much needed, this is the statutory norm. All Invoices from ERPNEXT shall be disallowed by customer and can cause further complication in tax compliance.

**Comment by maheshengg** [comment]
It will be og great help if implemented asap

**Comment by jk2081** [comment]
Can we also have an option to consolidate the tax amount for multiple items with the same HSN codes and tax rates into one line?

**Comment by maheshengg** [comment]
In that case, we can put the item table serial with HSN code followed by comma, and represent the tax amount with tax percentage

**Comment by nabinhait** [comment]
I though there is always same tax rate applicable for a specific HSN code. Can the tax rate be different for different item with same HSN code?

**Comment by maheshengg** [comment]
According to me, its the same tax rate applicable to a specific HSN Code. In my case, I have tax rates defined in item tax table for every item. All I desire to have is this.

![image](https://user-images.githubusercontent.com/1590079/28198576-c088d64e-687c-11e7-9872-16339c6a3259.png)

**Comment by jk2081** [comment]
For certain categories such as textiles, clothing, footwear and hotel rooms, the tax rate is also dependent on the price slab. Examples provided below.

Please see
http://m.economictimes.com/industry/services/hotels-/-restaurants/booking-a-hotel-after-gst-rollout-heres-how-much-you-will-pay/articleshow/59275466.cms

Clothing:

https//www.indiafilings.com/learn/gst-rate-for-apparel-clothing-and-textile-products/

**Comment by maheshengg** [comment]
May I know how to include HSN code in the tax table ?

**Comment by nabinhait** [comment]
@maheshengg The feature will be released and deployed for the cloud hosted accounts today.

**Comment by maheshengg** [comment]
Greetings of the Day !!

I see that the functionality / required for Tax table in the print format is as per desired and is implemented after followup on github, but only on the sales invoice doc type.

Would further require this on Quotation, Sales Order, Purchase Order, Purchase Receipt and Purchase invoice doc types too !

please check and confirm

**Comment by maheshengg** [comment]
Moved to https://github.com/frappe/erpnext/issues/9955
