### ISSUE TITLE
STATE CODE IN INVOICE

### ISSUE THREAD

**Issue by MANOJMAINKAR** [frappe/erpnext#9817]
While creating Sales Invoice with reference to SO's created before 1st July i.e. before GST ( Which may be partly dispatched ) ,
1)  In invoice state code field  is missing which required in Invoice (this may require for uploading returns)  2) To pull the State code we have to set address template accordingly , and edit the SO again and select the customer again , which is not possible for partly delivered SO's , same applies to GST code

**Comment by umairsy** [comment]
Manoj,

In the Sales Invoice, State Code should be fetched from the Customer master, even if not available in the Sales Order. If included in the Sales Invoice, it will fulful GST taxation requirement as well.

**Comment by MANOJMAINKAR** [comment]
In our account there is no such field in Sales Invoice table which stores state code , kindly check and advice

**Comment by umairsy** [comment]
Manoj,

In the sales transactions, State Code is fetched in the Address Details field itself, just like other Address fields (like Address Line 1, City etc.). There is no separate data field for State Code.
