### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 45: ordinal not in range(128)

### ISSUE THREAD

**Issue by jotapira** [frappe/erpnext#9818]
Hello,

I generate my first order in my shopify store and then I start to receive this error message in the shopify log over my cloud free erpnext system.

Anyone knows what causes this?

Traceback (most recent call last):
  File "/home/frappe/benches/bench-2017-07-11/apps/erpnext_shopify/erpnext_shopify/api.py", line 34, in sync_shopify_resources
    sync_orders()
  File "/home/frappe/benches/bench-2017-07-11/apps/erpnext_shopify/erpnext_shopify/sync_orders.py", line 13, in sync_orders
    sync_shopify_orders()
  File "/home/frappe/benches/bench-2017-07-11/apps/erpnext_shopify/erpnext_shopify/sync_orders.py", line 29, in sync_shopify_orders
    if e.args and e.args[0] and e.args[0].startswith("402"):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 45: ordinal not in range(128)

![error](https://user-images.githubusercontent.com/30115289/28115733-1a6d241c-66d4-11e7-806d-1dca42f3216d.jpg)

Best Regards

**Comment by joolsr** [comment]
I presume its a character that is not permitted within ascii but is allowed in UTF-8. I had something similar with an error seen with parsing a spam email

**Comment by jotapira** [comment]
The challenge is to know in which part of the purchase order and which is the word that is presenting the problem. Do you have any idea how I could know this since the log does not give me much more information?

**Comment by jotapira** [comment]
Hello,

I continue to present the reported inconvenience and I can not find the character that is presenting the inconvenience. Being a shopping cart configured in Spanish, this language handles many different accents and characters like the ñ, so if the drawback is with some of these characters I can not control the information that a user who purchases in my online store, More bearing in mind that I have a free account in the cloud where I can not modify any type of configuration file.

Is there any kind of patch or update that can solve this type of inconvenience for a site in Spanish?

For the help you can give me many thanks.

regards

**Comment by saurabh6790** [comment]
Fixed via https://github.com/frappe/erpnext_shopify/commit/68f297714a82af111b60497c0ecdae36ef02c30d
