### ISSUE TITLE
Empty School module

### ISSUE THREAD

**Issue by franciscobuendia** [frappe/erpnext#9823]
After the last 8.3.0 update, appears the School module empty, and it's not used.
(Of course, I don't need it).

Accounts hosted at Frappe cloud.

![school 1](https://user-images.githubusercontent.com/28711159/28129388-bdaaf59a-66f8-11e7-9131-6d52a66abf25.PNG)

https://discuss.erpnext.com/t/empty-school-module/25719

**Comment by rmehta** [comment]
similar to #9675
