### ISSUE TITLE
custom date field getting default value on print

### ISSUE THREAD

**Issue by sp9leo** [frappe/erpnext#9826]
On my custom print format I have custom date field, that gets today's date even if nothing is entered in the field on form. It gets displayed correctly if date is entered. It happens even on submitted documents
No defaults or custom scripts on field. This is code from my custom print format. `{{doc.get_formatted("my_custom_date_field")}}` If no value is entered line on print format should be blank.

ERPNext: v8.2.3 (master)
Frappe Framework: v8.2.6 (master)

**Comment by umairsy** [comment]
Hello,

As replicated in my test account, if custom date field doesn't have value, it doesn't appear in the print format. For the help in your custom HTML format, request you to post issue on the ERPNext Community forum.

https://discuss.erpnext.com

**Comment by sp9leo** [comment]
Thank you, but I think it is a bug, since it was working fine before update.
Looks like if you use` {{doc.custom_field}}` it works as expected. If you use `doc.get_formatted `it throws current date even on empty form field.
