### ISSUE TITLE
Recuring Contracts

### ISSUE THREAD

**Issue by hwinkel** [frappe/erpnext#983]
before implementing recurrence for individual documents like sales orders invoices or purchase orders you should consider to have recurring contracts which defining what will happen. Recurring things are always bound to contracts in real live. This infrastructure could be used to implement:

- Rental contracts
- Software, Service Subscriptions
- maintenance contracts containing a recurring fixed rate plus the chargable hours, tasks or other items
-  Recurring purchases

When reading your manual corrrectly something like this exists in the AMCs already, but is a bit to strict, and not always are on site visits for maintenance required.

**Comment by hwinkel** [comment]
Just checking erpnext again for a new project starting next year. Recurring Contracts which contain a BOM alike bundle of services is really needed there.

**Comment by rmehta** [comment]
This is already in the list #6313
