### ISSUE TITLE
unable to assign new role to user

### ISSUE THREAD

**Issue by BION-MY** [frappe/erpnext#9834]
I have signed up for a 5 users subscription. At the moment, only 2 active users.
However, when i tried to create the next 2 users (and assigning to them user role), i am hit with an error message of "Sorry. You have reached the maximum user limit for your subscription. You can either disable an existing user or buy a higher subscription plan."

Please advise.
![image](https://user-images.githubusercontent.com/30139834/28153327-65e5a17c-67d7-11e7-84a9-5eff231e2871.png)

![image](https://user-images.githubusercontent.com/30139834/28153351-8da545fa-67d7-11e7-84ff-9f09ba0dde21.png)

![image](https://user-images.githubusercontent.com/30139834/28153421-db4e261e-67d7-11e7-9c52-c850ffa3e6b9.png)

**Comment by umairsy** [comment]
Please share URL of your ERPNext account on support@erpnext.com. Request to report functional queries related to your hosted ERPNext account on our support ID.
