### ISSUE TITLE
Using Salutation in contact display / Customer Name.

### ISSUE THREAD

**Issue by vorasmit** [frappe/erpnext#9835]
We have added field salutation in contact and customer form. Use of the same has not yet started.

In contact display and customer name - we can add salutation. So that when email is created/ invoice or other document is created, it`s addressed appropriately.

Also we can add field gender in salutation, to link where possible.

**Comment by kennethsequeira** [comment]
Contact display will now show the salutations

https://github.com/frappe/frappe/pull/7237
