### ISSUE TITLE
[GST] Sales Register - Additions or changes

### ISSUE THREAD

**Issue by snvora** [frappe/erpnext#9836]
This is in addition to issue #9791 
These fields after getting created, could also be captured in respective reports. 

Additionally following additions / changes would be helpful
1.  Capturing Place of supply from billing and/or shipping address - [ GSTIN already there so can be ignored, but required as separate field in returns ]

2. Tax rate as per issue #9572 - [ where more than one rate of tax in invoice, bifurcation of each such rate of tax may be required, so B2B sheet for GSTR 1 is at invoice level + rate of tax level ]

3. Point 2 above makes it necessary to give Invoice value different from taxable value in returns furnished. [ where tax rate is constant in particular invoice, Invoice value should be logically = taxable value + tax ]

Additional changes that may be required in **Itemised sale and purchase Registers**

4. Qty getting captured is in terms of actual sales / actual purchase ; but Qty as per stock UOM could be different. When giving HSN level details, its ideal to give it as per stock UOM.

5. Capturing Stock UOM in register could also be helpful.

Its better to check if above changes ( 4 & 5)  are also required in Item - wise sales and purchase register.

**Comment by jk2081** [comment]
Can we also have an option to consolidate the tax amount for multiple items with the same HSN codes and tax rates into one line?

**Comment by snvora** [comment]
@jk2081 

Created new generalized issue #9918 that may solve the issue.

**Comment by jk2081** [comment]
Thank you

**Comment by Nehamirpuri** [comment]
@umairsy By when can we expect this changes to be part of GST reports available.Attached the report as well for your reference.
[GSTR1_Excel_Workbook_Template-V1.0.xlsx](https://github.com/frappe/erpnext/files/1168903/GSTR1_Excel_Workbook_Template-V1.0.xlsx)

**Comment by snvora** [comment]
Hello,
Finally official tool for upload of GST returns is available. It converts Excel workbook to JSON file for upload.

https://www.gst.gov.in/download/returns

Uploading of invoices is now possible.

**Additional change to report :**

b2b sheet in workbook has to different variables, Invoice value and taxable value.
Taxable value is subtotal for each rate in invoice.

So invoice level + rate of tax level details are required. But existing sales register takes care of just invoice level details.

**Comment by Nehamirpuri** [comment]
@nabinhait : Can you please update me on status on this and also what exact changes are being made?

**Comment by AravindPranera** [comment]
Hi,

I don't know whether the ERPNEXT team is preparing GST Return file format or not.

But we need GST return file report format in ERPNEXT, this is useful to everyone to post the Return file in GST portal. For your reference here is a attachment. Kindly do needful.
 
T​hanks,
Aravind.
[GSTR1_Excel_Workbook_Template-V1.1.xlsx](https://github.com/frappe/erpnext/files/1228042/GSTR1_Excel_Workbook_Template-V1.1.xlsx)

**Comment by nabinhait** [comment]
Fixed via #10405 and #10439
