### ISSUE TITLE
Issue with Tasks ToDo: description of last created task overwrites all entries

### ISSUE THREAD

**Issue by pagliaso** [frappe/erpnext#9841]
Hi, 

There is an issue with the Tasks TODO description at the moment:

When you create a new task in Tasks TODO, the name of the Task is created fine, but the description of the task goes to all the tasks you already have there. So for example, if you create task 1 with description "Prepare invoice", this description goes for all the tasks already existent in there. After this, any previous task that you click to review, has the description of the last task you created.

This is in the last development version.

Many thanks and kind regards from Spain,

Al

**Comment by umairsy** [comment]
Issue replicating. Value in the Details field of Task should not be copied to the new task.

**Comment by rohitwaghchaure** [comment]
Fixed via https://github.com/frappe/frappe/commit/e66d664ba67694be5d00f6894735fc4b142b5154
