### ISSUE TITLE
Education domain Fee module redesign

### ISSUE THREAD

**Issue by manassolanki** [frappe/erpnext#9847]
- [x] Fee Request
       - Can be created against program and batch or student group
       - Will create Fee records in the backend
- [x] Fee
      - Payment request will be created on submission of the Fee records (Fee will be reference 
         doctype)
      - Payment Entry will be done against the student as a party. 
- [x] Outstanding Balance Reports

**Comment by manassolanki** [comment]
## Fee Request

![shishuvan-8000-desk 3](https://user-images.githubusercontent.com/20757311/28171840-5c0fc008-6807-11e7-982a-8f0b0830b9ef.png)

**Comment by manassolanki** [comment]
## Fee

![shishuvan-8000-desk 4](https://user-images.githubusercontent.com/20757311/28171990-d269e396-6807-11e7-9635-a66d45546973.png)

**Comment by felixvarghese** [comment]
The Fee Doctype needs a "Discount" Field
Total Amount - Paid Amount - Discount = Outstanding Amount

**Comment by manassolanki** [comment]
Detailed Report
http://mhrd.gov.in/sites/upload_files/mhrd/files/document-reports/Report_IASEI_0.pdf

![image](https://user-images.githubusercontent.com/20757311/28203272-97316120-6896-11e7-861f-465b37776ed5.png)
