### ISSUE TITLE
Add customer group and territory to POS customer creation dialog

### ISSUE THREAD

**Issue by chdecultot** [frappe/erpnext#9853]
Hi,

In the POS, when a user creates a new customer, he/she cannot add the customer group or the territory since the fields are not available.

![image](https://user-images.githubusercontent.com/4903591/28184920-9972c69e-6815-11e7-987f-3b8460db27e3.png)

It creates two issues:

1. The customer is not fully completed and must be completed afterwards, which is not fully efficient.
2. More importantly, if there is a filter on a customer group or a territory in the cashier POS profile, he/she cannot see the customer in the list after the creation (after a browser reload for example). Which makes these filters useless and can be embarrassing if the customer comes back the same day or a few days later before the master data been enhanced.

I guess these options are not available because of the offline functionality, but maybe it could be possible to load the existing data for these two Doctypes and provide a selection based on the existing list without allowing cashier to create new customer groups or territories ?

Thank you !

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.
