### ISSUE TITLE
POS - Fields for contact first name and last name in the customer creation dialog

### ISSUE THREAD

**Issue by chdecultot** [frappe/erpnext#9854]
Hi,

An issue similar to #9853 .
In the POS, when creating a new customer, a new contact is automatically created and it's first name is populated with the full name of the customer. 

It is not a big issue, but since the point of an ERP is to have clean data and avoid rework, it could be nice to have two new fields in the dialog, like "Contact First Name" and "Contact Last Name" for example; That would allow the differenciation between the customer, which can be individual or a company, and the contact.

#### Current behavior
POS dialog:
![image](https://user-images.githubusercontent.com/4903591/28185552-15e730dc-6818-11e7-9d17-41486e187089.png)

Contact created:
![image](https://user-images.githubusercontent.com/4903591/28185621-4ccd96c2-6818-11e7-8325-5d9809050a54.png)

I can make the changes, but it would be better if anyone could share their thoughts on this! :smiley:

**Comment by tundebabzy** [comment]
Hi @chdecultot 
That means the full name field will be replaced by the first name and last name fields right?

**Comment by umairsy** [comment]
The retail can also be Company, where First Name and Last Name won't be valid. The primary use of Full Name is also to update Customer ID, which can be company name as well.

**Comment by chdecultot** [comment]
Hi @umairsy, I agree with you but don't understand why you closed this issue ?

Maybe my description was not clear, the point is just that the contact is not accurately created. 
I am proposing to add two new fields for contact first name and last name.

Of course the full name must remain as it can be a company and not an individual.

**Comment by tundebabzy** [comment]
I also support @chdecultot suggestion but I suggest we change the `Full name` field to `Company name` and add the two new fields `First name` and `Last name`. All three fields should be optional but validation should ensure that either Company name and/or [First name + Last name] is given. Of course this change will also need to be translated to Contacts also.

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.
