### ISSUE TITLE
POS - Possibility to choose the default mode of payment

### ISSUE THREAD

**Issue by chdecultot** [frappe/erpnext#9855]
Hi,

In the current POS, 'cash' is hard coded as the default mode of payment.
In reality, some shops will register more 'credit card' payments than 'cash' payments, or even sometimes 'cheques'.

It could be nice to configure the defaut mode of payment for each POS Profile for example.

I can make the changes if that's ok, but just one question, would it be easily possible to select only one checkbox in the 'Sales Invoice Payment' child table for example or do I need to make a custom JS script ?

#### For example if the default mode of payment is 'Cheque'

![image](https://user-images.githubusercontent.com/4903591/28186133-475430e6-681a-11e7-9f9b-e448dbb8702f.png)

Thanks !

**Comment by umairsy** [comment]
Replicating. We will soon check into it and get back to you.
