### ISSUE TITLE
Custom Sales Report

### ISSUE THREAD

**Issue by dhav-d** [frappe/erpnext#9860]
We wanted to develop couple of custom reports as follows:

1) We wanted to compare month on month sales(income) data filtered by sales invoices, customer group or cost centers with periodicity of monthly, quarterly, half yearly and yearly with past years' (2/3/4.. years) data; with percentage (-/+) changes for each value in column(year) compared to the corresponding data of the previous column(year). Similar comparison for P&L Statement & Profitability Analysis.

2) We would like to see sales data filtered by sales invoices, customer group or cost centers on a Weekly table view (Mon-Sun) with totals on the final row and column both for the selected period of time.

We would wish to have these reports contributed to the core ERPNext repository for everyone's use.

[Sample Reports.xlsx](https://github.com/frappe/erpnext/files/1152924/Sample.Reports.xlsx)

**Comment by umairsy** [comment]
For the second report, you can check Sales Analytics report. Set Frequency as Daily and select From Date - To Date for a week's time.

**Comment by dhav-d** [comment]
I check the sales analytics report. It looks similar to my requirement. only thing missing is a weekly view format Mon-Sun with totals to the end of each column and sort view by cost centers.
The weekly format allows us "Retailers" to further analyze the week of the day performance and a week on week sales progression. It allows us to plan and analyze sales strategy more efficiently.

**Comment by dhav-d** [comment]
hello, @jaichavan I do not know how to check that. any guide on how I could check?

**Comment by dhav-d** [comment]
@jaichavan Please reopen this request as the weekly view currently provided is a good feature but not what I had in mind.

My request was to fix the top row as Monday - Sunday and show stats as per the **Day of the Week** for a selected period for customers, items & their groups
