### ISSUE TITLE
Issue in Item Shortage Report in rtl mode

### ISSUE THREAD

**Issue by j209** [frappe/erpnext#9876]
![item_shortage_report_en](https://user-images.githubusercontent.com/18129232/28231082-e247f788-68fe-11e7-9601-68c43a19a967.png)

in ltr mode it is ok.

![item_shortage_report_ar](https://user-images.githubusercontent.com/18129232/28231122-1b26874a-68ff-11e7-9401-52d30618aedd.png)

There is an issue in Arabic lang(rtl mode)

**Comment by umairsy** [comment]
Works fine in my test account. Can you please check in another browser?

![screen shot 2017-07-17 at 3 15 47 pm](https://user-images.githubusercontent.com/910238/28263016-e8587e08-6b02-11e7-938d-120371cebea6.png)

**Comment by umairsy** [comment]
Since this issue is yet to be validated, please post it on the ERPNext community forum. https://discuss.erpnext.com
