### ISSUE TITLE
Custom report - Filters not applied as Saved in the Report

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#9882]
Reported via https://discuss.erpnext.com/t/custom-report-for-issue-do-not-apply-the-filter/25996

Steps:

1. Created a Custom Report with filters.
2. Added report to the Desktop.
3. When accessing report, the filters as defined in the List View of the Doctype are applied, and custom filters defined are not applied

**Comment by sharpec** [comment]
is there anything I can do? Where do I start looking for? Maybe I can help

**Comment by netchampfaris** [comment]
@sharpec Hi, I have tried creating a couple of custom reports with filters, and the filters are saved the way they should. If you are still facing this problem, can you share Frappé/ERPNext version you are on?

**Comment by sharpec** [comment]
After update to 
ERPNext: v8.5.4 (master)
Frappe Framework: v8.5.7 (master)

my old link on desktop, restarted to work without further modifications
thanks a lot

**Comment by netchampfaris** [comment]
@sharpec Good to hear that!
