### ISSUE TITLE
Bug while creating new batch number from stock entry

### ISSUE THREAD

**Issue by mobentec** [frappe/erpnext#9886]
When we are creating stock entries, and when we are typing in the warehouse/item and then selecting the batch number, if the batch number is not there, we then type in a new batch number and hit enter, which then pops up a quick entry popup.

![2017-07-17 at 00-26-23](https://user-images.githubusercontent.com/6663120/28255869-731f65ca-6a8a-11e7-986f-9a7d51a1b0c0.png)

The issue is that ERP takes the data we originally typed into the batch No. field, and when we hit enter, it autofills into a "new batch" popup, but puts the text inside the "item" field, when it should be the "Batch" field.  

![2017-07-17 at 00-28-05](https://user-images.githubusercontent.com/6663120/28255876-7cf3a890-6a8a-11e7-852d-730b54ff5328.png)

When we click on Edit in full page, it still does not fix the issue.  We then have to select the autofill text, delete, and then enter in batch ID, re-select the item, and then hit save.

**Comment by mbauskar** [comment]
@mobentec,

It looks like you have removed the mandatory option for Batch ID field for Batch doctype, Please make Batch ID field mandatory so, that Batch ID will appear on Quick Entry dialog.

**Comment by mobentec** [comment]
Hi @mbauskar, that is incorrect.  The Batch ID field has a check mark for "mandatory".  I kindly request that you please reopen this ticket and help address this bug.

![2018-01-31 at 12-20-20](https://user-images.githubusercontent.com/6663120/35637104-35497c2a-0681-11e8-9267-0f00940de546.png)

**Comment by mobentec** [comment]
Issue occurring with stock entries too: #12725
