### ISSUE TITLE
Overtime salary calclation feature in Payroll

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#989]
As discussed, following are the field to be added in the payroll transactions for overtime calculation.

Salary Structure:

- Per day rate for overtime

Salary Slip:

- Total days worked on holiday (calculated based on attendance and holiday list)
- Add Earning Type

Earning Type:

- Default Earning Type for overtime

**Comment by neilLasrado** [comment]
As far as i have tried to understand the concept of overtime, its usually an hourly term. ( No. of hours you have worked beyond normal working hours)

- [ ] Add overtime rate (per hour) to Salary Structure.
- [ ] Add maximum overtime to employee master(in hours / monthly).
- [ ] New Master Overtime Log ( similar to attendance, {no of overtime hours, employee, day} ).
- [ ] calculate and add overtime cost in salary slip.

**Comment by umairsy** [comment]
1. Overtime should be one of the Earning Type.
2. We can have value of Overtime calculate based on Time Log * Hourly Rate
3. Also user should be able to define Overtime Hours in the Salary Slip, just like user can directly enter LWP in the Salary Slip.

**Comment by neilLasrado** [comment]
As taken from @nabinhait :

Instead of new Overtime Log, Integrate it with Existing Time Log. 
User creates time log of type overtime.

**Comment by neilLasrado** [comment]
https://github.com/frappe/erpnext/issues/2654

**Comment by asr17** [comment]
please also add feature for hourly basis wages 
set regular rate as well as overtime rate and timings to be defined for regular and overtime

**Comment by bghayad** [comment]
Hello;
How to calculate the overtime hour rate based on the employee salary and not to be flat rate?
Regards
Bilal

**Comment by prasathchandrasekar** [comment]
Hello all,
    Now the update was available?  based on over time working hours.
