### ISSUE TITLE
An option to select the basis of calculation in a Sales Invoice in Type filed as "On Price List" is required.

### ISSUE THREAD

**Issue by SaurabhGupta329** [frappe/erpnext#9894]
Many Ecomm Portals these days are doing their commission calculations based on the MRP or List Price of the product not the Net Total achieved after discount, 
therefore one more option in the **"TYPE"** field of "Sales Taxes and Charges" form in Sales Invoice, is required where values can be calculated on the basis of Price List (MRP) & not only the Net Total.

I tried adding the new option of "On Price List Rate" in the table but its not working, system is still taking the Net Total Value only.

Can this option be provided as its a very important one not only for us, even for any retail company selling online through 3rd party portals.

**Comment by umairsy** [comment]
![image897d54](https://user-images.githubusercontent.com/910238/28263168-72516322-6b03-11e7-843a-5dffc1847f48.png)

**Comment by harshit-30** [comment]
Kindly create a new issue if the said feature/request/enhancement is not yet included after v13.10.
