### ISSUE TITLE
Payment request error when Company names contains accented characters (like é)

### ISSUE THREAD

**Issue by gbard** [frappe/erpnext#9906]
args | ('ascii', u'M\xe9dico Coiffure', 1, 2, 'ordinal not in range(128)')
-- | --
encoding | 'ascii'
end | 2
message | ''
object | Médico Coiffure
reason | 'ordinal not in range(128)'
start | 1

 /home/frappe/frappe-bench/apps/frappe/frappe/integrations/doctype/stripe_settings/stripe_settings.py: 45

43 
44 	def get_payment_url(self, **kwargs):
45 		return get_url("./integrations/stripe_checkout?{0}".format(urllib.urlencode(kwargs)))
46 
47 	def create_request(self, data):
 Locaux
 /usr/lib/python2.7/urllib.py: 1343

1341         for k, v in query:
1342             k = quote_plus(str(k))
1343             v = quote_plus(str(v))
1344             l.append(k + '=' + v)
1345     else:

**Comment by umairsy** [comment]
Hi,

Sorry for the issue and thanks for reporting it here. Can you please also share the steps to reproduce this issue?

**Comment by gbard** [comment]
Hello, just put a "é" or, I guess, any accented character into the company name , setup a stripe account and try to send a payment request.

Thanks!

G.
