### ISSUE TITLE
Add Supplier Invoice No. in the General Ledger report/print format

### ISSUE THREAD

**Issue by manivk** [frappe/erpnext#9907]
Hi

We need to send statement of accounts to suppliers frequently where we take a dump of all the purchase invoices and payments made and then give the credit or debit balance to suppliers.

Issue here is that when we do this from general ledger, we do not get the supplier invoice numbers. It only gives our purchase number series generated by ERPNext. Can we somehow get a statement from ERP which gives the supplier invoice numbers in the ledger statement of account? Would be great if it can be a separate report.

Suppliers need to see their invoice numbers, else it will not make sense to them. Again, if you could let us know the costs, we wouldnt mind funding this feature

Thanks
Mani.

**Comment by umairsy** [comment]
Hello Mani,

Thanks for the feature suggestion. We will consider adding this feature in the standard report if we have more users asking for the same feature. For now, please add Supplier No. in the remarks field as it is already covered in the GL Entry print format.
