### ISSUE TITLE
Allow Stripe checkout localization (language) setting

### ISSUE THREAD

**Issue by gbard** [frappe/erpnext#9908]
According to Stripe docs:

You can opt in to using the translated version with a single line of code. If you’re using the simple integration, just pass data-locale="auto" into the <script> tag. If you have a custom integration, use locale: 'auto' when calling StripeCheckout.configure(). There’s more info in the docs.

https://stripe.com/blog/checkout-in-more-languages

We should be able to select the checkout language.

Thanks!

**Comment by britlog** [comment]
@gbard Hi, done in https://github.com/frappe/frappe/pull/4892
