### ISSUE TITLE
Expired items should not be in inventory 

### ISSUE THREAD

**Issue by maxfu9** [frappe/erpnext#9909]
I did not fount any solution to treat expired item. These items are not sales able that’s good. But it is not possible to reduce the inventory and treated them as loss

**Comment by tundebabzy** [comment]
Hi @maxfu9
Please post this question on discuss.erpnext.com

**Comment by maxfu9** [comment]
@tundebabzy it is not question sir. treatment of expired doest not exit in system. it is my suggestion to improve inventory system. 
1- expired item should be not in inventory 
2- they have proper treatment in accounts as loss 
3- or they may be returned back to suppliers

**Comment by umairsy** [comment]
You can create an Stock Entry of type Material Issue entry for an item. In the Difference Account field of Stock Entry Item table, select an Expense Account in which item's value should be booked as an expense.
