### ISSUE TITLE
Payment Entry - Exchange Rate does not fetch based on Posting Date

### ISSUE THREAD

**Issue by addymuliady** [frappe/erpnext#9910]
ERPNext: v8.1.6 (master)
Frappe Framework: v8.1.3 (master)

As per requested by @nabinhait - https://discuss.erpnext.com/t/how-to-fetch-currency-exchange-rate-based-on-posting-date/26088

When I create or make a new Payment Entry, the Posting Date is set as Today's date and as such, the exchange rate is fetched based on that date.

When I change the Posting Date, the exchange rate should reflect the latest rate based on the new posting date.

**Comment by Olawale1** [comment]
Hi @tundebabzy ,
 
Trust you're doing great. Just to chip in here... I think the system should actually always use the latest exchange rate for the **exact posting date** as it's done in other systems like SAP etc. In the current system (at least, last time I checked), let's say posting date is 17th January and the latest exchange rate before then is 13th January, the system automatically uses this rate (13th January). This is however not best practice as exchange rates could have fluctuated significantly within the period

Ideally, the system should request that an exchange rate be entered for the posting date (i.e. 17th January in the example above). If however there are multiple exchange rates entered for 17th January, the latest one can be automatically selected

Please let me know if further clarification is required

Thanks

**Comment by tundebabzy** [comment]
You are right. Actually, ERPNext should be connected to a live feed of exchange rates but I'm not aware of any free options. Perhaps we can add a feature where users can specify a feed location that can be integrated with ERPNext. In the mean time, we decided to leave the exchange rate updates to the user hence we assume that the last exchange rate the user has saved must be the prevailing exchange rate. 

> I think the system should actually always use the latest exchange rate for the exact posting date

Yeah, this is how it's supposed to work. I'll fix the bug ASAP

**Comment by tundebabzy** [comment]
Hi @addymuliady 
I wasn't able to reproduce this. On my test system I have exchange rates as this:

| Date | AUD - NGN |
| --- | ---|
| 10-07-2017 | 239.58 |
| 05-07-2017 | 238.58 |
| 01-07-2017 | 230.58 |

On loading the invoice today (19-07-2017), exchange rate was 239.58
On changing the posting date to 06-07-2017, exchange rate changed to 238.58
On changing the posting date to 02-07-2017, exchange rate changed to 230.58

This is the correct behaviour. If your installation isn't working like this, try updating. Or you can give some more specifics.

**Comment by tundebabzy** [comment]
@addymuliady 
I'm on:
erpnext 8.4.3
frappe 8.4.1

If your installation doesn't work as above, updating should hopefully fix it. Please reopen if there are more details or the issue still persists.

**Comment by Olawale1** [comment]
> Yeah, this is how it's supposed to work. I'll fix the bug ASAP

Hi @tundebabzy , should I open a new issue for this?

Thanks

**Comment by tundebabzy** [comment]
@olawale1
Yes please

**Comment by Olawale1** [comment]
Done!

https://github.com/frappe/erpnext/issues/9973

Thanks

**Comment by addymuliady** [comment]
@tundebabzy 
Sorry as I was away ...

The fetching of rates is on Payment Entry DocType. Invoices are OK.

Thanks!
