### ISSUE TITLE
Submit 230 Salary Slips in Process Payroll page, Timeout

### ISSUE THREAD

**Issue by magic-overflow** [frappe/erpnext#9915]
Submitting 230 Salary Slips with sending email enabled, it caused the server timeout.
Disabled sending email, It took only several seconds.

**Comment by nabinhait** [comment]
Email should be sent via Email Queue (background jobs).

**Comment by sumitdas4u** [comment]
Am not able to generate the salary for this month with enabling email option. 

please resolve asap

**Comment by mbauskar** [comment]
fixed via https://github.com/frappe/erpnext/pull/10350
