### ISSUE TITLE
Changing currency or price list when creating a new quotation

### ISSUE THREAD

**Issue by villiger** [frappe/erpnext#9919]
When I change the currency during the creation of a new quotation, the prices are somehow calculated by an exchange rate instead of read out from the selected price list. Even though I have prices set for that product in the selected currency.

It works correctly though when the currency is set in the client beforehand. Just not if I have to change the currency during the creation of the quotation, respectively after selecting a client or a lead.

**This is correct:**
![price list correct](https://user-images.githubusercontent.com/347878/28308264-f5b3f71e-6ba5-11e7-9e9d-1b55a095f562.png)

**This is wrong:**
![price list wrong](https://user-images.githubusercontent.com/347878/28308285-02a04806-6ba6-11e7-93ef-051c431ee6e9.png)

The second one always happens with leads, because in leads you can't set a standard currency and price list, so it always assumes your "home currency" first (in my case CHF). Then I have to change it for example to EUR and nothing works anymore.

**Comment by umairsy** [comment]
Hello,

Thanks for elaborating your use-case.

If you select Currency before selecting items, does this issue still reoccur?

**Comment by tundebabzy** [comment]
Hi @villiger 
any updates?

**Comment by villiger** [comment]
@umairsy Yes, it happens also if I change the currency before selecting the items. Also if I save and re-open the quotation.

**Comment by villiger** [comment]
@umairsy @tundebabzy 
I just found out something pretty surprising:
If I edit the field **Exchange Rate** (for example from 1.1 to 1.2) it actually refreshes everything and picks the proper prices, according to the selected price list, and everything is fine from then on. That's a very wierd behaviour.

**Comment by tundebabzy** [comment]
Hello @villiger 
I haven't been able to reproduce this. Please assist me by listing out steps to reproduce this.
