### ISSUE TITLE
Material Request Status not updated if Purchase Order is imported

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#9927]
WN-SUP26153

Material Request MREQ-00029 is already ordered via Purchase Order PO-00066, but Material Request MREQ-00029 is still showing pending. Also, completed Qty is not updated in the Material Request Item table. Many such Material Requests and Purchase Order affected.

Issue replicating. If Purchase Order is imported, then Completed Qty is not updated in the Material Request Item. Perhaps the functionality is missing on the server side and only available on the client side.

![screen shot 2017-07-18 at 4 44 26 pm](https://user-images.githubusercontent.com/910238/28314578-be3f278a-6bd8-11e7-8d4a-3a68b99158d1.png)

**Comment by pratu16x7** [comment]
Also, it seems the autonaming is affected for new POs after importing:

![screen shot 2017-07-26 at 5 41 05 pm](https://user-images.githubusercontent.com/5196925/28620231-acda4f5e-7229-11e7-8cc6-b1de0bb5f600.png)

**Comment by nabinhait** [comment]
@umairsy It is intended behaviour, ordered qty will not be updated without reference of MR and MR item row.

But there is a workaround. User can import the POs in draft mode and then they can use "Link to Material Requests" button to link with the MR, it tries to link automatically. Then they can submit the PO.

**Comment by umairsy** [comment]
In the Purchase Order Item table, Material Request ID was provided. Please check Issue WN-SUP26153 for the instance.

**Comment by nabinhait** [comment]
Id for the Material Request Item row also required, only Material Request ID is not sufficient. But the problem is, user will never know item row id.
The problem is "Material Request Id" field is shown data-import-tool while exporting template for PO, thats why they expect order qty will be updated in MR.
