### ISSUE TITLE
Screen gets "white washed" and no buttons work

### ISSUE THREAD

**Issue by opsninja1** [frappe/erpnext#9935]
No matter what I do, my ERPNext screen is washed over with a white film and none of the buttons or links work.....

![capture](https://user-images.githubusercontent.com/21339160/28320665-ce101a12-6b96-11e7-930c-470a1f10cebe.JPG)

**Comment by Admakbs** [comment]
i am having the  same issue but in sales invoice some buttons

**Comment by opsninja1** [comment]
Now the system is doing all kinds of weird things.  When I try to search by Serial Number, it keeps going back to the original number.....

**Comment by Admakbs** [comment]
Same thing happened with me on mobile app for android, i wanted to attach screenshot but through phone the attachments not available

**Comment by opsninja1** [comment]
ERPNext is now unusable........

I have the hosted version.  Please fix ASAP!

**Comment by somicoito** [comment]
same problem here

**Comment by bcornwellmott** [comment]
Can you show a posting of your console log (F12 in chrome)?

**Comment by austinreid** [comment]
Same issue. Here is console log from whitewashed Journal Entry screen.

```
> Uncaught TypeError: Cannot read property 'for_print' of null
>     at Currency (desk.min.js:290)
>     at Object.frappe.format (desk.min.js:463)
>     at eval (eval at frappe.template.compile (desk.min.js:2355), <anonymous>:42:33)
>     at Object.frappe.render (desk.min.js:2369)
>     at Object.frappe.render_template (desk.min.js:2380)
>     at list.min.js:2815
>     at Array.map (<anonymous>)
>     at Class.get_item_html (list.min.js:2814)
>     at list.min.js:2796
>     at Array.map (<anonymous>)
```

**Comment by drthilina** [comment]
Same issue,
![image](https://user-images.githubusercontent.com/29944021/28326248-dfbbd9f6-6bfd-11e7-8f1a-f03f16500a2f.png)

**Comment by bcornwellmott** [comment]
Fixed via https://github.com/frappe/frappe/pull/3732
