### ISSUE TITLE
Bug in Sales Invoice

### ISSUE THREAD

**Issue by Admakbs** [frappe/erpnext#9936]
Dear Team 
right now i am with client and i tried to creat sales invoice to show the client how it is works but it is do not work as usual
when i press on add new row and select item and select quantity it working good but when i reach to price field the button became not active 
also i tried to delete the row but when i mark it system did not show me delete button 
i checked this issue in all the browsers
please check it as soon as possible 
![sales invoice bug](https://user-images.githubusercontent.com/29948389/28321462-0101e0a0-6bdc-11e7-8cea-d3a64bd5ab2f.PNG)

**Comment by cwt-co** [comment]
me to

**Comment by Admakbs** [comment]
I am worried because this issue accured duration i am in presentation with client
Iguess the isaue in any transaction has row button

**Comment by Admakbs** [comment]
@rmehta we need emergency action Sir, alot of clients stopped entries

**Comment by rmehta** [comment]
Sorry this is fixed now

**Comment by Admakbs** [comment]
@rmehta thank you boss, our clients will be happy for this quick response
