### ISSUE TITLE
Integration to Zapier

### ISSUE THREAD

**Issue by grynn-in** [frappe/erpnext#9943]
Zapier is a for pay integration platform that had connections to many applications around the web.  One such typical app is Woocommerce. 

A lot of ERPNext users also have ecommerce / online stores.  It would be great to use the best store for it's part and also use ERPNext for accounting and ware house manage ment.  

Generally speaking it would be great if we can have one example of Zapier integration built tip s how the community "the way" forward. 

Thanks

**Comment by seanspeaks** [comment]
We could help! :-)

**Comment by umairsy** [comment]
Nice. Will be great to see connector contributed the community. Please start a post on the community forum to learn if someone has any reference on this.

https://discuss.erpnext.com

**Comment by grynn-in** [comment]
https://discuss.erpnext.com/t/zapier-integration-with-erpnext/3655/21?u=deepak_pai

This issue was opened at the suggestion of Rushab . Could you pls reopen?

**Comment by umairsy** [comment]
@grynn-in sorry to have closed it. If Github Issue is in reference to the discussion on the forum, please also attach the link of the discuss post (like shared above).

**Comment by SaurabhGupta329** [comment]
any further progress on this Zapier integration, we are also interested in this.

**Comment by seanspeaks** [comment]
I could have someone on our team whip up a starting app on the CLI and invite others to collaborate. 

What triggers or actions are people most interested in to start?

**Comment by grynn-in** [comment]
As an example: 
Sales orders (say from a shopping cart) + Sales Invoice + Payment ----> ERPNext
ERPNext -----> Items, Prices

The good thing is Zapier has WooCommerce integration. So data can travel from Woo -> Zapier -> ERPNext. If we get one going, it will be a model to build upon.

**Comment by sathishpy** [comment]
I am interested in contributing to this. If there is a basic prototype to start with, it will certainly help others in jump starting.

**Comment by barredterra** [comment]
I recently published the first [ERPNext app for Zapier](https://github.com/alyf-de/erpnext-zapier/blob). Let me know what you think about it and feel free to contribute.

Features:
- Search all records in ERPNext.
- Create a new record in ERPNext with data from any Zapier app.
- Trigger any Zapier app when something happens to a record in ERPNext.

Works for all DocTypes. (Especially well for Leads and Opportunities.)
