### ISSUE TITLE
Salary Structure: The Doctype shape and the Salary Slip Based on Timesheet not existed

### ISSUE THREAD

**Issue by bghayad** [frappe/erpnext#9946]
I am using the following version:

Installed Apps
ERPNext: v8.5.2 (master)
Frappe Framework: v8.5.4 (master)

The check box for Salary Slip Based on Timesheet is not existed in the salary structure. Also the Salary structure document (the form) is not appearing well as it is not showing Human Resource > Salary Structure. Seems something wrong.

**Comment by umairsy** [comment]
Please post your technical queries on the community forum.

https://discuss.erpnext.com
