### ISSUE TITLE
Issue changing 'Unique' field option in v8

### ISSUE THREAD

**Issue by Olawale1** [frappe/erpnext#9948]
Hi,

There's an issue when changing the 'Unique' option for a field in ERPNext. It appears that this option doesn't actually get de-selected in the backend when the option is unchecked in the UI or even from the JSON file. Steps to replicate:

1. Set a field as 'Unique' via Customize Form. In my case, it was a Link field with 'Account' as option
2. Add at least one record for that field and Save/Submit
3. Try adding another record (selecting the same option). You should get an error message saying "FIELDNAME must be unique"
4. Go back to Customize Form and uncheck the 'Unique' option
5. Try adding another record (selecting the same option in Step 2). You still get an error message saying "FIELDNAME must be unique"!

Even if you delete the record created in Step 2 and try creating fresh records, the 'Unique Validation Error' persists!

Kindly help fix

Thanks

**Comment by tundebabzy** [comment]
Hi @Olawale1 
Please follow progress on this bug on frappe/frappe#3760
