### ISSUE TITLE
[Paid Development] Product Life Management PLM 

### ISSUE THREAD

**Issue by Rgottsch1** [frappe/erpnext#9949]
I'd like to sponsor Product Life Management   PLM is used to maintain BoM revisions and track product lifecycle based on Engineering Change orders. Basically PLM application that allows us to :

– PLM (Product Lifecycle Management) helps to create ECO (Engineering Change Orders) to :

1. Make Part and BoM revisions.

2. Make MO Route revisions.

3. Update Work Operation based on revisions in BoM.

4. Generate alerts for changes in BoM’s as well as Routes in MO.

5. Generate multi-level approvals from higher authorities for any revision (BoM or Route) before making changes in MO

– Approve Engineering Change Orders

– Manage BoM Versions

**Comment by YogiYang** [comment]
If you are not hell bent to getting this done by ERPNext company then I would advise you to post this on: https://erpnext.org/erpnext-jobs

**Comment by Rgottsch1** [comment]
I’m new to this processs.  Where I posted on Github is for ERPNext company only?  If I am ok with services by others it gets posted on erpnext-jobs post listed below?  Would ERPNext be willing to work on the project if it was sponsored?

Rob Gottschalk
[Part 2.2]
GEM Manufacturing, Inc.
p: 262-857-7274 x 217 | f: 262-857-2917

**Comment by joolsr** [comment]
I think you should always strongly consider getting Frappe (the main developers behind ERPNext) to go with this paid development as they understand this stuff better than anyone. There are some other really good ERPNext developers in other companies, but its always far better to get a feature such as PLM added to the core rather than as an addon, as fixes will become part of the core too, and everyone benefits. Separate ERPNext apps sometimes are slightly outside of the general thinking and dont get updated so often or inline with core which moves very quickly ..

**Comment by Rgottsch1** [comment]
I understand and agree.  So, can I anticipate a quote from Frappe on adding PLM, they are on this email string and have what is needed to proceed a sponser cost?

Rob Gottschalk
[Part 2.2]
GEM Manufacturing, Inc.
p: 262-857-7274 x 217 | f: 262-857-2917

**Comment by joolsr** [comment]
@Rgottsch1 read this if you haven't already https://erpnext.com/pricing/paid-feature-development send an email to hello@erpnext.com

**Comment by epochc** [comment]
@Rgottsch1 I think these features can be rolled into the Manufacturing Module that we are looking to enhance. I will loop you into another conversation we are having around the manufacturing module and you can see if that's something you want to contribute to.

Thanks

Jay

**Comment by Rgottsch1** [comment]
Sounds good thankyou.

Rob Gottschalk
GEM Mfg, Inc

________________________________

**Comment by rmehta** [comment]
@Rgottsch1 you can also get a developer and then ask them to contribute it back to the core.

**Comment by asharamseervi** [comment]
Hello @Rgottsch1, Is there any status of feature requested by you? or this already contributed to core?

**Comment by dalers** [comment]
I am also very interested in Manufacturing and in particular PLM and a change management process starting with design or engineering documentation, including work instructions, test procedures, sustaining development or manufacturability improvement, etc., all of which need revision control. @Rgottsch1 do you have a solution? @epochc, am I correct to understand there was a teleconference of manufacturing developers November 2017 on Jitsi to discuss requirements and development, ? Was there a document or anything can can be reviewed?

Fwiw, I have come across a couple discussions on document control that might be related. 

- Discuss topic started by @Ben_Cornwell_Mott https://discuss.erpnext.com/t/feature-proposal-improving-document-control/28924 

- Discuss topic started by @JayRam https://discuss.erpnext.com/t/enhancing-the-manufacturing-module/18401

**Comment by dalers** [comment]
@epochc @Rgottsch1 I am also very interested in Manufacturing and in particular PLM and a change management process starting with design or engineering documentation, including work instructions, test procedures, sustaining development or manufacturability improvement, etc., all of which need revision control. @epochc, am I correct to understand there was a teleconference of manufacturing developers November 2017 on Jitsi? Was there a document or anything can can be reviewed as a result of the Jitsi discussion?

Fwiw, I have come across a couple discussions on document control that might be related. 

- Discuss topic started by @Ben_Cornwell_Mott (@bcornwellmott) https://discuss.erpnext.com/t/feature-proposal-improving-document-control/28924 

- Discuss topic started by @JayRam https://discuss.erpnext.com/t/enhancing-the-manufacturing-module/18401

**Comment by creador30** [comment]
This is also a long awaited feature for us.
Among the most important aspects of a PLM is the restriction of document revisions from unauthorized users. In order to have a proper PLM inside ERPNext, we need to have user/role permissions for attachments.

**Comment by Rgottsch1** [comment]
WIll work around it for now.

**Comment by umairsy** [comment]
Please share your thoughts on the design proposed here.

https://discuss.erpnext.com/t/feature-product-lifecycle-management/82659/6

**Comment by kriengpre** [comment]
Here are some example function of PLM Platform
https://www.aras.com/en/resources?data-selectable-Types=Demo
https://www.arenasolutions.com/platform/plm/
https://github.com/docdoku/docdoku-plm
