### ISSUE TITLE
Stock Ageing 

### ISSUE THREAD

**Issue by MANOJMAINKAR** [frappe/erpnext#9953]
We need to submit a Stock Ageing report like AR/AP with balance quantity ,balance quantity value , stock ageing days selected for GST  (for slots for ageing days 30,90,365 from posting date etc) . as in AR/AP report . Kindly advice how we can generate this report . Such report will add more value to ERPNext.

**Comment by PawanMeh** [comment]
Will work around of using stock ageing report work?


![stock](https://user-images.githubusercontent.com/20460498/28518950-6ded3d04-7087-11e7-9fa6-2a1a5a25d240.png)
