### ISSUE TITLE
Itemised Tax Breakup table should be selectable from Print Format builder

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#9955]
Please make table of Itemised Tax Breakup table selectable in the Print Format builder. Also noticed that the HTML table in not clickable and visible in the form/controller.

**Comment by maheshengg** [comment]
how to find out if this been updated ?

**Comment by maheshengg** [comment]
chaos happening due to non-availability of tax table in forms.

**Comment by umairsy** [comment]
Hello Mahesh,

Now in the Print Formats, you can add Taxes and Charges Calculation field for the itemised tax breakup. I just added it in the custom Sales Order print format and it worked fine for me.

![screen shot 2017-07-21 at 11 06 40 am](https://user-images.githubusercontent.com/910238/28450411-d3b757f8-6e04-11e7-8d97-cfee729610ca.png)
