### ISSUE TITLE
Chapter Member leaving chapter does not purge member's ID from display

### ISSUE THREAD

**Issue by epochc** [frappe/erpnext#9957]
On https://erpnext.org/chapters, if somebody joins a Chapter her/his details are displayed on the chapter page.

However if somebody leaves, the person's details are not purged from the display. We should not delete the record, just ensure that people that leave are not displayed in the list of active members.

If this is not already being done, we should capture the date and time of exit. A quick why do you want to exit this chapter question with a simple dropdown:

Moving to another chapter
Not keen on ERPNext anymore
Not able to make time for the chapter
This chapter is not really my kind of place
Other

should help us understand trends of why people are leaving a chapter.

Thanks

Jay

**Comment by vishdha** [comment]
https://github.com/erpnext/foundation/pull/43

**Comment by vishdha** [comment]
https://github.com/erpnext/foundation/pull/98
