### ISSUE TITLE
Add a Bundle to Sales Order Through Api

### ISSUE THREAD

**Issue by ahmedonee** [frappe/erpnext#9959]
i need to know how to add a bundle to Sales Order through api and please give me an example .. thanks

**Comment by umairsy** [comment]
Hello,

Request to post technical query on the ERPNext community forum. On the Github, only bugs and feature suggestion are tracked.

**Comment by umairsy** [comment]
https://discuss.erpnext.com

**Comment by ahmedonee** [comment]
ok .. thanks
