### ISSUE TITLE
Timesheet popup reminder

### ISSUE THREAD

**Issue by shenoshadow** [frappe/erpnext#9966]
users always forgot to close their timesheet daily

so how can we show a popup to let notice them to close their timesheet before leaving work at 5pm

thank u dears.

https://discuss.erpnext.com/t/timesheet-popup-reminder/26197

**Comment by umairsy** [comment]
User Team Updates (we use internally as well).

HR > Team Updates

Please post queries on ERPNext community forum. https://discuss.erpnext.com
