### ISSUE TITLE
Role Permission not being applied on tree masters

### ISSUE THREAD

**Issue by umairsy** [frappe/erpnext#9967]
https://discuss.erpnext.com/t/user-permissions-for-warehouses/26168

I've added user permission to role sales coord (which has read access to warehouse) to limit warehouse access.

![7064b48df70c38acb6108f33b48a0fc53156de28_1_690x234](https://user-images.githubusercontent.com/910238/28364287-67912086-6ca1-11e7-92dc-4a2d626bb5fe.png)

Added user permission for user abc. Yet am unable to view any warehouse!

![b7c00d5f6435379bf27afcb1dd3de673ad6a55ab_1_690x236](https://user-images.githubusercontent.com/910238/28364291-6e9dfe08-6ca1-11e7-856a-f45faff4b9be.png)

on ERPNext v8.3.6
FRAPPE 8.3.10

**Comment by manassolanki** [comment]
You also need to give user permission of the next parent in order to have the access of a node. 
This applies everywhere in the entire frappe for nested structures.
