### ISSUE TITLE
Albanian Lek shows were all should be on email accounts sync option ERPNext: v8.5.1 (master) Frappe Framework: v8.5.1 (master)

### ISSUE THREAD

**Issue by imllc** [frappe/erpnext#9968]
![bug all](https://user-images.githubusercontent.com/22771472/28364454-813ac6f8-6c52-11e7-99bf-7099d207c6f2.JPG)

**Comment by umairsy** [comment]
Please post functional and technical queries on the erpnext community forum https://dicsuss.erpnext.com

**Comment by imllc** [comment]
why was this closed this is clearly a bug the email sync option should have either all or unseen yet it shows Albanian Lek

**Comment by umairsy** [comment]
Hi

Can you please check if this Custom option was added in the docfield from Customize Form?

**Comment by umairsy** [comment]
Closing this issue as #9970 has been also created for the same purpose. Will be helpful if you could reply on the same on the new Github Issue.

**Comment by imllc** [comment]
We’ve done no customization of forms how do we check this are you refereeing to this specific form?
