### ISSUE TITLE
Error in Dropbox Settings

### ISSUE THREAD

**Issue by gops** [frappe/erpnext#9969]
Dropbox setting, allow dropbox access gives error 

Error (400)
It seems the app you were using submitted a bad request. If you would like to report this error to the app's develope

**Comment by saurabh6790** [comment]
Hi,

Please set redirect url in Dropbox App.

Ref : https://youtu.be/Qv-E8r6aTvw

**Comment by saurabh6790** [comment]
@gops Are still facing the issue?
