### ISSUE TITLE
"Albanian Lek" instead of "ALL" or "UNSEEN" in email sync option

### ISSUE THREAD

**Issue by imllc** [frappe/erpnext#9970]
https://github.com/frappe/erpnext/issues/9968

**Comment by imllc** [comment]
no modification to our instance

**Comment by strixaluco** [comment]
@imllc, if you had followed [guidelines](https://github.com/frappe/erpnext/wiki/Issue-Guidelines) while opening the issue, misunderstanding could've been avoided.

I can't reproduce the bug on ERPNext: **v8.5.2** (master) / Frappe Framework: **v8.5.5** (master)

![emailsync](https://user-images.githubusercontent.com/10875796/28396546-b2cc5e02-6d2e-11e7-9cc9-f54268095faa.png)

**Comment by umairsy** [comment]
@imllc can you please help with the steps followed to configure your instance and email account, so that we can could try to replicate it?

**Comment by imllc** [comment]
What guidelines according to post around foundation formation this sort of stuff should not even be here, and I thought I did a pretty good job taking a screen shot and describing the bug. The point here is I have been running this product for months doing only bench updates on master we should expect master to be relatively bullet proof.  This is a hr product for it to succeed we need to transcend from be a project that can only be supported by technical people to a product where the user can expect a stable product that can be supported by HR staffers looking only to tech folks for guidance.  All the playing around should be done in development.  While I am happy that there are lots of patches to fix things broken they shouldn’t be in production in the first place especially when you’re dealing with people’s money.  I am hoping this starts to change as have been discussed in the forums I have addons I want to develop that will make the product more attractive but need this to be stabilized first.

**Comment by imllc** [comment]
Ok maybe you can explain this to me I took screen shots yesterday and posted it yesterday but today it’s not there I am running no translations in my browsers and have made no changes to the code or forms I did do a bench update yesterday but I don’t recall if it was before or after..

**Comment by umairsy** [comment]
Hope you will understand that for us to be able to locate the cause and debug it, we will need to replicate it. As checked in my hosted and locate account, and as reported by other users, it didn't replicate for them. Please let us know if this issue reoccurs in your ERPNext account, so that we can try to debug it. Till then, can we close this issue?

**Comment by imllc** [comment]
no explanation for why a monetary name was in there but since its gone and I can not replicate we shall close
