### ISSUE TITLE
Unable To Save Address On Lead

### ISSUE THREAD

**Issue by KDSNicole** [frappe/erpnext#9975]
When I try to add a new address to a lead I am able to get to the screen to add the contact information in and save it. It now asks for me to give the address a title in order to save it instead of defaulting one. Even when I put a title in and save it looks like it saved but when I go to the lead it's not there.

**Comment by joolsr** [comment]
Pls add a screenshot or animated video to explain more clearly and state which version numbers you are using of frappe/ERPNext. Thanks

**Comment by KDSNicole** [comment]
![screenshot1](https://user-images.githubusercontent.com/30293224/28377674-331b9210-6c73-11e7-9cff-5fd20d5c7c6e.JPG)
![screenshot2](https://user-images.githubusercontent.com/30293224/28377685-3e3a4056-6c73-11e7-8ee1-b9e53374c569.JPG)

**Comment by KDSNicole** [comment]
So I go to Lead then to Add Address. I put in all the fields and hit save. Then I go back to the Lead and none of it is there

**Comment by PawanMeh** [comment]
Validated this on the latest release, seems to work fine. Kindly check the steps in the video, if the issue still persists, re-open with steps, ERPNext release & Frappe Framework release you are on.

![lead_address](https://user-images.githubusercontent.com/20460498/28520960-48526328-708f-11e7-999c-4676ac6b7144.gif)

**Comment by KDSNicole** [comment]
That is where something is a disconnect because you added your address and it defaulted with a title. When I go to do this it asks me to add a title for the address. Which is probably why it's not linking it to the Lead.
