### ISSUE TITLE
Required On date for Material Request not auto populating after first instance

### ISSUE THREAD

**Issue by opsninja1** [frappe/erpnext#9980]
I used to be able to add the "Required On" date for the first line, and then all below it would automatically populate.  It is no longer doing it......  This is a major issue when I have to enter the date for a 200 line material request.

![capture](https://user-images.githubusercontent.com/21339160/28386399-088907da-6c91-11e7-9fe0-a9dc5747319f.JPG)

**Comment by umairsy** [comment]
Replicating.

![equired-date](https://user-images.githubusercontent.com/910238/28412523-1b6ea946-6d62-11e7-9c8a-091fbee41405.gif)

**Comment by opsninja1** [comment]
How are you adding a the video screen shot of the steps?  That would be seriously helpful....

**Comment by umairsy** [comment]
Licecap

**Comment by tundebabzy** [comment]
I have checked the source and this was recently removed. I'm not sure why. @rmehta will cooment on this

**Comment by rmehta** [comment]
No should no be removed? Can you add it back?

**Comment by tundebabzy** [comment]
I'll add it back
