### ISSUE TITLE
Transferred qty shouldn't be required if skip transfer checked

### ISSUE THREAD

**Issue by ishanloya** [frappe/erpnext#9988]
In production order item table, transferred qty shouldn't be required if skip_transfer is checked

**Comment by PawanMeh** [comment]
This seems to be working fine. When you click on "Finish", the stock entry being created is for Finished Goods and not for transfer.

@ishanloya , can you confirm this or if your use case is different, kindly share Frappe Framework version, ERPNext version & Steps with screen shots.

**Comment by tundebabzy** [comment]
any updates @ishanloya
