### ISSUE TITLE
Contact display to include salutation if available

### ISSUE THREAD

**Issue by ishanloya** [frappe/erpnext#9989]
Currently contact_display joins first name and last name. This should be prefixed by the salutation field if the user has entered it. It will make it easier to display contact name in quotations, etc.

**Comment by ishanloya** [comment]
At present, we have to do this using:
For quotation to customer:
`frappe.db.get_value("Contact", doc.contact_person, "salutation") + " " + doc.contact_display`
For quotation to lead:
`frappe.db.get_value("Lead", doc.lead, "salutation") + " " + doc.contact_display`

**Comment by kennethsequeira** [comment]
@ishanloya 

This was added recently in v11

https://github.com/frappe/frappe/pull/7237

When salutation is added in any contact, the system will add that to contact display
