### ISSUE TITLE
Cash reconciliation end of the day

### ISSUE THREAD

**Issue by Aintzanemasa** [frappe/erpnext#9994]
Hi.

How about the cash reconciliation in pos? I think it's very important to the people who use de POS system in Erpnext. I think, there maybe a button wich show you how much money in cash do you have, and how much in the bank.
A report like this:

SALES DETAIL     20/07/2017
___________________________________________

TOTAL AMOUN: 500€
CASH: 100€
CREDIT CARD: 400€

TAX
____________________________________________
21% of 450 :    94.5
10% of 50:        5
4% of 0: 

I think it's an easy report to include in the POS. and it will improve the use.

**Comment by chdecultot** [comment]
Hi,
It is a very important feature. An issue is already open on the topic, please add your requirements in it to avoid duplication: #7582
