### ISSUE TITLE
Interest fees on due invoices (feature request)

### ISSUE THREAD

**Issue by gbard** [frappe/erpnext#9998]
Hi,

It would be realy useful if we could have a possibility to charge interest automatically on past due invoices. For example: 3% interest per 30 days period.

Thanks!

G.

**Comment by gbard** [comment]
That would probably be the best option. The day after the due date has passed, a new "draft" invoice for the same customer should be created automatically with an item the user would choosen (create either a new article named "Interest charge" or "Administration fees", etc.). I think the "interest" invoice should be left as "Draft" because the price of the "Interest charge" would change every day based on the monthly interest rate the user would choose. For example, a 3% monthly interest rate would mean a 0.097% daily rate (http://www.datedial.com/datEquivalent_Interest_Rate.asp). Once the client pays for the initial invoice, the user could then submit the draft invoice and add the total to the outstanding balance...

I think the best method would actually be to allow the system to add the interest charge automatically to the initial invoice on a daily basis but I'm not sure it would be possible if the initial invoice has already been submited...

**Comment by dwork** [comment]
I agree, a new invoice would be best. In our case, I'd want to generate the new invoice for all past due invoices, list them on the new invoice perhaps in the description of the charge, and submit the invoice. If they pay prior to the next month-end, I'm fine not charging daily interest. There would need to be an option to charge interest on past due interest invoices or not (charging interest on interest charges isn't necessarily advisable).

**Comment by tundebabzy** [comment]
I think you can achieve this with a Subscription

**Comment by deepeshgarg007** [comment]
@gbard We have dunning as a feature in the latest versions now. Please check
