### ISSUE TITLE
Cannot delete mail attachments

### ISSUE THREAD

**Issue by luesak** [frappe/erpnext#9999]
After setting up Email Inbox using IMAP and the emails start to sync, email attachments will be displayed in the File Manager. However even after deleting everything in the Communication list, I still cannot delete these attachment files in the File Manager.

The message received in "No permission to write / remove."

What does this mean and how do I delete the files?

Kim

**Comment by strixaluco** [comment]
Please post functional questions to [discuss.erpnext.com](discuss.erpnext.com).

Your account doesn't have enough permissions¹. Refer to the "Users And Permissions"² article of the manual for details.

¹ — https://github.com/frappe/frappe/blob/develop/frappe/core/doctype/file/file.py#L221
² — https://frappe.github.io/erpnext/user/manual/en/setting-up/users-and-permissions/
